### ISSUE TITLE
beziers have to be declared above animations in hyprland.conf

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1001]
This is not really a problem, but I still wanted to ask about it here.
I think there may should be a notice in the wiki about it.

Can anyone reproduce this?

**Comment by vaxerski** [comment]
yes it's expected. The config is parsed from top to bottom

**Comment by Quantenzitrone** [comment]
the slight problem with this is:
i wrote a nix function to create my hyprland config from a nix expression
nix sorts elements of a attribute set alphabetically and animation thus comes before bezier
that's why i think this behavior is not optimal

**Comment by vaxerski** [comment]
ping @fufexan for any nix-related stuff

it is optimal. How can the animation find a bezier that has not been defined?

**Comment by fufexan** [comment]
> the slight problem with this is:
> i wrote a nix function to create my hyprland config from a nix expression
> nix sorts elements of a attribute set alphabetically and animation thus comes before bezier
> that's why i think this behavior is not optimal

Use Home Manager's DAG entries to sort stuff manually.
