### ISSUE TITLE
CS:GO mouse acts weird with SDL_VIDEODRIVER=wayland, issue doesn't occur on sway.

### ISSUE THREAD

**Issue by jamiepiccolo** [hyprwm/Hyprland#1004]
### Steps to reproduce.
- Remove libSDL2 from `~/.local/share/Steam/steamapps/common/Counter-Strike\ Global\ Offensive/bin/` and `~/.local/share/Steam/steamapps/common/Counter-Strike\ Global\ Offensive/bin/linux64`
- Run steam native
- launch csgo with the launch options `SDL_VIDEODRIVER=wayland %command% -vulkan`

### Expected Outcome

CSGO runs like you would expect, mouse behaves like it had on sway.

### Noted outcome.

Mouse input acts weird, perhaps sensitivity is not 1:1 with sway? however the sensitivity is fine when not using SDL_VIDEODRIVER=wayland.

See video. [https://www.youtube.com/watch?v=Xy9St4J0oWE](https://www.youtube.com/watch?v=Xy9St4J0oWE)

**Comment by vaxerski** [comment]
Wayland and XWayland might fetch mouse movements differently.

Can you pop your config here? (attach pls, not copy)

The video doesn't help much, I can't see how you move your mouse :P

**Comment by NotAgentBilly** [comment]
The mouse is moving as little as possible, assume 1 millimeter sends it wild.

Config attached, thanks.
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/9997159/hyprland.txt)

**Comment by vaxerski** [comment]
Odd. I assume sway works with SDL_VIDEODRIVER=wayland.

I'll see.

At any rate, you can just game thru xwayland, I guess.

**Comment by NotAgentBilly** [comment]
Yup, I've been playing CS:GO on sway with this exact setup for a few weeks. Only thing that changed is installing/running hyprland.

Thanks and good luck if you continue to dig. If there's anything else I can do, let me know.

**Comment by vaxerski** [comment]
does this still occur?
