### ISSUE TITLE
Perhaps it is a good idea to have a feature "force Xwayland"

### ISSUE THREAD

**Issue by EvilBoi123** [hyprwm/Hyprland#1005]
There is a way to force an application to be open in Xwayland. 

In sway, you have to use "env -u WAYLAND_DISPLAY _application_"

**Why do we need to force application to open in Xwayland?** -:

The thing is, Xorg is a very matured display protocol therefore many linux application were designed with x11 in mind. Some application are very well written in Xorg, but because Wayland adoption is becoming reality, these developer were also considering to port their application to Wayland, but the thing is, this application on Wayland is still not mature and it preferable to be opened in Xwayland. 

"**Some idea to implement this feature**" -:
Perhaps Hyprland can implement this feature using Windows rule, or by just simply allow itself to work like sway did.

**Comment by vaxerski** [comment]
no, why?

for most apps, you can force it with `GDK_BACKEND=x11` or `QT_QPA_PLATFORM=xcb`

why this garbo?

besides, you can launch the app with `WAYLAND_DISPLAY= [app]`
