### ISSUE TITLE
Remapping Capslock

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#1006]
I'm not sure if this is a compositor-specific issue, but any help would be greatly appreciated. I'm trying to remap capslock to esc, and although this was straightforward on X, I'm not sure about the approach on wayland.

**Comment by MahouShoujoMivutilde** [comment]
```
input {
    kb_options = caps:escape
}
```

Like with `setxkbmap`, basically.

**Comment by vaxerski** [comment]
as above. It's xkb's job.
