### ISSUE TITLE
Apps not directly detaching from terminal no longer launchable

### ISSUE THREAD

**Issue by bwachter** [hyprwm/Hyprland#1011]
At some point between v0.17.0beta and a7ed3a5e4718c5c3a84306bb190a3272e2bdecda a change got introduced breaking launching of apps not detaching from terminal directly after launch.

    bind = $mainMod, F5, exec, emacsclient -c

does nothing, while

  bind = $mainMod, F5, exec, emacsclient -c -nw

starts emacsclient. The first one waits for the terminal, while -nw makes it directly detach. Tested with some other applications not detaching as well to rule out stupid behaviour on emacs' side.

**Comment by vaxerski** [comment]
do a `git bisect` then

**Comment by bwachter** [comment]
1e5cab1ee7a82d3381f55963a0ff768c30215602 looked like the most likely culprit, and indeed things without that one.

**Comment by vaxerski** [comment]
is already reverted in head
