### ISSUE TITLE
When group focused, return to last focused window in that group

### ISSUE THREAD

**Issue by OctarineSourcerer** [hyprwm/Hyprland#1015]
I'd like for there to be an option to change which window gets selected when moving back to a previously focused group.

Take this example:
![FocusDemo](https://user-images.githubusercontent.com/6842867/201544703-4ac0ff1a-d647-4ef9-89f4-c40f915b93de.png)

With current behaviour, starting at the big window and focusing right, down, left, right would select the _top-right_ window. Having just come from bspwm and i3, this surprised me; I'd have expected it to have selected the _bottom-right_ window, as that was the window on the right of the big one that was last focused.

As far as I can tell, I can't see a way of setting this in the docs. I'd perhaps call it `focus_prefer_recent` or something?

**Comment by vaxerski** [comment]
yeah the current system.... I don't even remember how it works but iirc prefers the oldest window.

**Comment by OctarineSourcerer** [comment]
> should the system prefer _last_ over _longer shared border_?

I think so: last indicates what the user most recently used, so is more likely to be the intended target when going back again. 

If that'd cause divides between opinions, we could always do an option such as `preferred_focus_window` with options like `recent`, `biggest_shared` or `oldest`

**Comment by vaxerski** [comment]
added in 94b7b6b58475a0e802e390591f95e04c70aa676d

`binds:focus_preferred_method` can be either 0 for history (default) or 1 for longest edge
