### ISSUE TITLE
Hyprland crashed

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1017]
Stack trace:
[Hyprlandstacktrace.txt](https://github.com/hyprwm/Hyprland/files/9998906/Hyprlandstacktrace.txt)

Hyprland log:
[Hyprlandlog.txt](https://github.com/hyprwm/Hyprland/files/9998905/Hyprlandlog.txt)

Hyprland config:
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/9998904/hyprland.conf.txt)

i hope this helps

**Comment by vaxerski** [comment]
fixed in fcb5037a1d22d05d9f58b8a43d75b1870d93b896

**Comment by Quantenzitrone** [comment]
im seriously impressed how you are able to fix all these bugs so fast just by changing one line

**Comment by vaxerski** [comment]
>reads the log
>"ok this bitch"
>reads the code
>oh fuck here
>patch
>git commit git push
