### ISSUE TITLE
Submap of key bindings

### ISSUE THREAD

**Issue by japrogramer** [hyprwm/Hyprland#102]
**Describe in detail your idea.**

In Xmonad it is possible to have nested key combinations.

https://xmonad.github.io/xmonad-docs/xmonad-contrib/XMonad-Actions-Submap.html

**Comment by vaxerski** [comment]
maybe. Not important and very low prio, though.

**Comment by primalmotion** [comment]
This is the last thing I think I need to switch to Hyprland for good :)

**Comment by vaxerski** [comment]
done in 19d94b87ab639a0b22ea03809502316470de0f7a, see the wiki entry: [here](https://github.com/hyprwm/Hyprland/wiki/Advanced-config#submaps)

**Comment by primalmotion** [comment]
you're a machine!

**Comment by primalmotion** [comment]
Is there a way to to make a binding that does multiple things? for instance I'm making a submap to launch some browser by typing SUPER+B then b or p etc. I want that submap to reset after I press b or p automatically. I was able to do it by running exec "hyprctl --batch "dispatch exec firefox; dispatch submap reset" but it's not particularly pretty

**Comment by vaxerski** [comment]
nothing should stop you from doing
```
bind=SUPER,B,exec,firefox
bind=SUPER,B,submap,reset
```

**Comment by primalmotion** [comment]
oh cool. let me try that

**Comment by primalmotion** [comment]
hum. the submaps don't seem to work anymore here with the latest commits. no error. just nothing happens when I hit a binding that should enable a submap, it does nothing

**Comment by vaxerski** [comment]
work on my end.

**Comment by primalmotion** [comment]
oh. ok it fails if inside the submap, I use the same binding to reset than the one I use to enable it. I can live without that, but it feels weird
