### ISSUE TITLE
Blender Drag Bug

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#1024]
Blender 3.4 (and upwards) has finally introduced support to wayland, but when used on Hyprland there is a really big problem: drag to change a value is glitching. What do I mean by that it's that if you drag a value, as per example the location of an object, your mouse's position will be changed to the upper left corner of Blender. 
I've encoutered this bug only on blender on hyprland, on Sway it's working perfectly. To reproduce this bug you'll need to install Blender 3.4 or upwards, but if you compile it from source (blender-git on the AUR) it'll be really time consuming: up to 5 hours.

https://user-images.githubusercontent.com/61051731/201870659-e55a1994-b8be-49c0-b211-442e1aa9c02e.mp4

**Comment by vaxerski** [comment]
lmk when blender 3.4 is in the arch repos

**Comment by Estebiu** [comment]
> lmk when blender 3.4 is in the arch repos

I think you can get it from the chaotic-aur if you don't want to build it entirely.

**Comment by vaxerski** [comment]
@Estebiu are you on the discord server? That way I could make a patch and let you test it yourself :-)

**Comment by Estebiu** [comment]
> @Estebiu are you on the discord server? That way I could make a patch and let you test it yourself :-)

I am indeed! I'm one of the 5 "super active" members, and I have the same name as here :)

**Comment by CheesecakeCG** [comment]
> lmk when blender 3.4 is in the arch repos

According to this post, https://code.blender.org/2022/10/wayland-support-on-linux/
It should be enabled in the official 3.4 nightlies https://builder.blender.org/download/daily/

**Comment by vaxerski** [comment]
can yoooou check with 62f4503f07066762af9546bb4a2acdd58b72d4bf

**Comment by Estebiu** [comment]
That seems to have fixed it. Every day I fall more in love with you, vaxry. Thanks.

**Comment by vaxerski** [comment]
nohomo

**Comment by Estebiu** [comment]
Seems like there's been a recession somewhere; I restarted having this problem..

**Comment by vaxerski** [comment]
possibly 2bf7f9e4136ebef6db1159c636b163ecb96f23cc because of #1511 ?

**Comment by Estebiu** [comment]
Thanks for the very fast reply. I applied that patch and now the mouse isn't resetting it's position to the upper left corner anymore; however the mouse position after the drag should reset to it's initial position (as it does in sway).

**Comment by vaxerski** [comment]
that would bring back #1511

**Comment by vaxerski** [comment]
added the patch in edd0a141de56cb71dc46ffdaf70fe0ccd950b136

**Comment by Estebiu** [comment]
Oh well, it's good enough for the moment. Thanks!
