### ISSUE TITLE
Fcitx5 pop-up window disappears every other input

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1025]
https://user-images.githubusercontent.com/68589851/201930214-a755769f-e892-4a7b-9adb-f50ba0de572d.mp4

In chromium(xwayland or native) at least, but `foot` works fine just fine
This works in sway,

**Comment by JustSimplyKyle** [comment]
https://0x0.st/oI7R.log
The `ERR` happens when I'm typing in a xwayland window!

**Comment by JustSimplyKyle** [comment]
According to git bisect... this is the faulty commit??
![image](https://user-images.githubusercontent.com/68589851/202716436-c9113eff-a201-47db-b516-17a0ebe4de81.png)

**Comment by vaxerski** [comment]
can repro. Only chromium though. Firefox works fine.

**Comment by JustSimplyKyle** [comment]
It's probably because the fcitx5-popup in firefox isn't visible in `hyprctl clients`, but in chromium(or any other application) it is a normal client instead

**Comment by vaxerski** [comment]
le fixado in f91f3d1c81f89dc3fcb468672fbd0f1030d7b7ac
