### ISSUE TITLE
Display floating window over fullscreen one?

### ISSUE THREAD

**Issue by Ruixi-rebirth** [hyprwm/Hyprland#1032]
When I watch a video in full screen, I want to bring up a floating frame to take notes. I think it is very convenient

**Comment by System-x64** [comment]
Can't u just use Picture-in-Picture mode from the browser, it will initially pop out as another tiling window but you can toggle it to floating and Voila!

**Comment by System-x64** [comment]
Or better, pin your floating window (which u'll use to take notes with), this way it'll be above all the other things

**Comment by Pinghigh** [comment]
> 或者更好，固定你的浮动窗口（你会用它来做笔记），这样它就会高于其他所有东西
Sometimes we need to watch a 1080p video with full-screen mode :(

**Comment by lilydjwg** [comment]
Many features are missing in the PiP window, e.g. fast forward, thumbnails, comments, info cards, danmuku.

**Comment by System-x64** [comment]
> Sometimes we need to watch a 1080p video with full-screen mode :(

Bsically you want this type of setup right, your vid in full screen and 2nd app floating?
![screenshot_20221117_152713](https://user-images.githubusercontent.com/90208727/202415814-ec36ad16-dd4d-4f63-89bf-b2f801745809.png)

**Comment by Pinghigh** [comment]
> > Sometimes we need to watch a 1080p video with full-screen mode :(
> 
> Bsically you want this type of setup right, your vid in full screen and 2nd app floating? ![screenshot_20221117_152713](https://user-images.githubusercontent.com/90208727/202415814-ec36ad16-dd4d-4f63-89bf-b2f801745809.png)

Yes

**Comment by System-x64** [comment]
> Many features are missing in the PiP window, e.g. fast forward, thumbnails, comments, info cards, danmuku.

If they'll add all that info on an already small window....won't it just make it difficult to view the actual content behind

**Comment by lilydjwg** [comment]
> If they'll add all that info on an already small window

I thought you meant to use a large PiP window instead of fullscreen and put other floating windows on it...

**Comment by System-x64** [comment]
> Yes

In your `hyprland.conf` add `bind=SUPER,Y,pin`  then, making sure the app you want is selected and in floating, press mod+y to pin it, now you can shift it to the full screen window and it won't hide behind :)

**Comment by System-x64** [comment]
> I thought you meant to use a large PiP window instead of fullscreen and put other floating windows on it...
Ofc not, that would a horrible idea

**Comment by System-x64** [comment]
I meant something like this, the note taking app as tiling and the content as floating, you could do it both ways 
![screenshot_20221117_154020](https://user-images.githubusercontent.com/90208727/202418593-6fc4af18-0fb3-403a-9b00-f037bc9b2648.png)

**Comment by vaxerski** [comment]
pinned windows and floating windows created AFTER fullscreening will appear above the fullscreen one.
