### ISSUE TITLE
Weird and laggy window resizing behavior with PrismLauncher.

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1039]
https://user-images.githubusercontent.com/74491719/202596248-491517ca-4efb-4177-82ab-d7d6c055b8de.mp4

[config.txt](https://github.com/hyprwm/Hyprland/files/10036947/config.txt)

With other applications this works totally fine and smooth, some may be a tiny bit yanky but nothing compared to this.

Do you think this is an issue at PrismLauncher?

**Comment by vaxerski** [comment]
> Do you think this is an issue at PrismLauncher?

pretty sure. Seems like it just can't keep up

**Comment by JustSimplyKyle** [comment]
Is prism launcher launching in native or xwayland?

**Comment by Quantenzitrone** [comment]
xwayland

**Comment by JustSimplyKyle** [comment]
Try native
