### ISSUE TITLE
another crash 2

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1041]
[stack-trace.txt](https://github.com/hyprwm/Hyprland/files/10037233/stack-trace.txt)
[config.txt](https://github.com/hyprwm/Hyprland/files/10037234/config.txt)
[log.txt](https://github.com/hyprwm/Hyprland/files/10037235/log.txt)

It's funny that you can see me creating the other two issues I made in the log.

Also, I have no idea what I did what could cause the crash.

**Comment by vaxerski** [comment]
Completely broken coredump. Try providing a debug one. (See issue guidelines)

**Comment by Quantenzitrone** [comment]
I don't think I will be able to reproduce the bug, since I don't know what could have caused it, should I close this issue then?

**Comment by vaxerski** [comment]
yep. Reopen it if it happens again.
