### ISSUE TITLE
Unhandled python OSError

### ISSUE THREAD

**Issue by Tarch1** [hyprwm/Hyprland#1042]
Hello,
I'm using Artix and would like to install it, but I'm having this error by compiling it manually or using an AUR helper (I've installed all dependencies);
OSError: [Errno 8] Exec format error: '/usr/bin/glslangValidator'

ERROR: Unhandled Python OSE error. This is probably not a Meson bug, but a problem with your build environment.
WARNING: Running the setup command as meson [options] instead of meson setup [options] is ambiguous and deprecated.

Greetings

**Comment by Tarch1** [comment]
Yep both aur and cloning; I've installed these dep like was said in the wiki:
gdb ninja gcc cmake libxcb xcb-proto xcb-util xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland

and cloning with:
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
sudo make install

I didn't try the manual installation, by copying files in relatives folder, because it will work wo problem.
tried to google the error but I can't find any clue related to glslangValidator

**Comment by vaxerski** [comment]
Are you on x86?

**Comment by Tarch1** [comment]
Yes

**Comment by vaxerski** [comment]
no clue then. Seems like a problem with meson & your system more than anything else.

**Comment by Tarch1** [comment]
Yes was seatd that conflicted with other files during its installation.
Thanks for the help
