### ISSUE TITLE
Layout Not using Master Stack

### ISSUE THREAD

**Issue by Bcez** [hyprwm/Hyprland#1048]
Title Explains It all

Config

# Syntax is the same as in Hypr, but settings might differ.
#
# Refer to the wiki for more information.

# Variables
$browser = /usr/bin/firefox
$terminal = kitty
$editor = kitty - Neovim /usr/bin/nvim
$files = kitty xplr -e /usr/bin/xplr
$media = kitty Spotify-tui /usr/bin/spt
$locker = /home/zmenciso/.config/hypr/lock.bash
$notifications = swaync-client -t -sw

# Colors (copied from vim-moonfly-colors)
$bg = 0xff080808
$fg = 0xffb2b2b2
$fgbr = 0xffeeeeee
$black = 0xff323437
$red = 0xffff5454
$green = 0xff8cc85f
$yellow = 0xffe3c78a
$blue = 0xff80a0ff
$purple = 0xffd183e8
$cyan = 0xff79dac8
$white = 0xffc6c6c6
$blackbr = 0xff949494
$redbr = 0xffff5189
$greenbr = 0xff36c692
$yellowbr = 0xffc2c292
$bluebr = 0xff74b2ff
$purplebr = 0xffae81ff
$cyanbr = 0xff85dc85
$whitebr = 0xffe4e4e4

# monitor=HDMI-A-1,2560x1080@60,0x0,1
# workspace=HDMI-A-1,1

exec-once=hyprpaper
exec-once=waybar
exec-once=xsettingsd
exec-once=hyprctl setcursor Breeze 24
exec-once=swayidle -w before-sleep $locker lock $locker after-resume $locker
exec-once=swaync
exec-once=ibus-daemon -drxR
exec-once=spotifyd
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

windowrule=float,*.exe
windowrule=float,Rofi
windowrule=float,gnome-screenshot

input {
    kb_layout=us
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=0

	touchpad {
		disable_while_typing=true
		natural_scroll=true
		clickfinger_behavior=true
	}
}

gestures {
	workspace_swipe=true
}

misc {
	disable_hyprland_logo=true
	disable_splash_rendering=true
	no_vfr=false
}

general {
    sensitivity=1 # for mouse cursor
    main_mod=SUPER

    gaps_in=20
    gaps_out=22
    border_size=3
    col.active_border=$blue
    col.inactive_border=0xb3080808

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

}

decoration {
    rounding=12
    blur=1
    blur_size=5 # minimum 1
    blur_passes=1 # minimum 1, more passes = more resource intensive.
    blur_new_optimizations=true
}

animations {
    enabled=1
    bezier=overshot,0.22, 1, 0.36, 1
    animation=windows,1,3,overshot
    animation=border,1,5,default
    animation=fade,0,5,default
    animation=workspaces,1,3,overshot,slidevert
}

master {
    special_scale_factor=0.8
    new_is_master = true
}

# Launching applications

bind=SUPER,Return,exec,$terminal
bind=SUPER,Q,killactive,
bind=SUPER_SHIFT,M,exec,$media
bind=SUPER_SHIFT,E,exec,$files
bind=SUPER_SHIFT,N,exec,$editor
bind=SUPER_SHIFT,Space,togglefloating,
bind=SUPER_SHIFT,w,exec,$browser
bind=SUPER,D,exec,mauncher-launcher
bind=SUPER,N,exec,$notifications
bind=SUPER,F,fullscreen

# Changing focus

bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r
bind=SUPER,k,movefocus,u
bind=SUPER,j,movefocus,d

# Changing workspace

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=SUPER,bracketleft,workspace,-1
bind=SUPER,bracketright,workspace,+1

# Move window

bind=SUPER_SHIFT,h,movewindow,l
bind=SUPER_SHIFT,l,movewindow,r
bind=SUPER_SHIFT,k,movewindow,u
bind=SUPER_SHIFT,j,movewindow,d

# Move window to workspace

bind=SUPER_SHIFT,1,movetoworkspace,1
bind=SUPER_SHIFT,2,movetoworkspace,2
bind=SUPER_SHIFT,3,movetoworkspace,3
bind=SUPER_SHIFT,4,movetoworkspace,4
bind=SUPER_SHIFT,5,movetoworkspace,5
bind=SUPER_SHIFT,6,movetoworkspace,6
bind=SUPER_SHIFT,7,movetoworkspace,7
bind=SUPER_SHIFT,8,movetoworkspace,8
bind=SUPER_SHIFT,9,movetoworkspace,9
bind=SUPER_SHIFT,0,movetoworkspace,10

bind=SUPER_SHIFT,bracketleft,movetoworkspace,-1
bind=SUPER_SHIFT,bracketright,movetoworkspace,+1

# Switch monitor

bind=ALT,1,focusmonitor,1
bind=ALT,2,focusmonitor,2
bind=ALT,3,focusmonitor,3
bind=ALT,4,focusmonitor,4
bind=ALT,5,focusmonitor,5
bind=ALT,6,focusmonitor,6
bind=ALT,7,focusmonitor,7
bind=ALT,8,focusmonitor,8
bind=ALT,9,focusmonitor,9
bind=ALT,0,focusmonitor,10

# Move workspace to monitor

bind=ALT_SHIFT,1,movecurrentworkspacetomonitor,1
bind=ALT_SHIFT,2,movecurrentworkspacetomonitor,2
bind=ALT_SHIFT,3,movecurrentworkspacetomonitor,3
bind=ALT_SHIFT,4,movecurrentworkspacetomonitor,4
bind=ALT_SHIFT,5,movecurrentworkspacetomonitor,5
bind=ALT_SHIFT,6,movecurrentworkspacetomonitor,6
bind=ALT_SHIFT,7,movecurrentworkspacetomonitor,7
bind=ALT_SHIFT,8,movecurrentworkspacetomonitor,8
bind=ALT_SHIFT,9,movecurrentworkspacetomonitor,9
bind=ALT_SHIFT,0,movecurrentworkspacetomonitor,10

# Special keys

bind=,XF86AudioPlay,exec,playerctl play-pause
bind=,XF86AudioPause,exec,playerctl play-pause
bind=,XF86AudioNext,exec,playerctl next
bind=,XF86AudioPrev,exec,playerctl previous
binde=,XF86MonBrightnessUp,exec,brightnessctl set 5%+
binde=,XF86MonBrightnessDown,exec,brightnessctl set 5%-
binde=,XF86AudioRaiseVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ +5%
binde=,XF86AudioLowerVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=,XF86AudioMute,exec,pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=,XF86AudioMicMute,exec,pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Screenshots

bindr=,print,exec,cd ~/pic && grim
bindr=SUPER,print,exec,gnome-screenshot -a

# Resize mode

bind=SUPER,R,submap,resize

submap=resize
binde=,l,resizeactive,50 0
binde=,h,resizeactive,-50 0
binde=,k,resizeactive,0 -50
binde=,j,resizeactive,0 50

bind=,escape,submap,reset
bind=,r,submap,reset
bind=SUPER,r,submap,reset

submap=reset

# Lock mode

bind=SUPER,escape,submap,lock

submap=lock
bindr=,l,exec,loginctl lock-session && hyprctl dispatch submap reset
bindr=,t,exec,logout && hyprctl dispatch submap reset
bindr=,s,exec,systemctl suspend && hyprctl dispatch submap reset
bindr=,h,exec,systemctl hibernate && hyprctl dispatch submap reset
bindr=,r,exec,systemctl reboot && hyprctl dispatch submap reset
bindr=,d,exec,systemctl poweroff -i && hyprctl dispatch submap reset

bind=,escape,submap,reset

submap=reset

idk what i did wrong,  follows the wiki and default config

**Comment by Si-Ki** [comment]
add `layout = master` to general @Bcez

**Comment by vaxerski** [comment]
read the wiki
