### ISSUE TITLE
Cassowary freezes Hyprland completely

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1049]
<details>
  <summary>Coredumpctl info:</summary>

            PID: 41051 (Hyprland)
           UID: 1000 (kyle)
           GID: 1000 (kyle)
        Signal: 11 (SEGV)
     Timestamp: Wed 2022-11-16 22:06:52 CST (2 days ago)
  Command Line: Hyprland
    Executable: /usr/bin/Hyprland
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (kyle)
       Boot ID: fec8bf0cb6a344dbb2f3f9b5e2173572
    Machine ID: c16f820d3f8841e1b97c9499f899c7d0
      Hostname: arch
       Storage: /var/lib/systemd/coredump/core.Hyprland.1000.fec8bf0cb6a344dbb2f3f9b5e2173572.41051.1668607612000000.zst (present)
  Size on Disk: 12.8M
       Message: Process 41051 (Hyprland) of user 1000 dumped core.
                
                Stack trace of thread 41051:
                #0  0x00007f332e9be9e0 wl_event_loop_dispatch (libwayland-server.so.0 + 0xb9e0)
                #1  0x00007f332e9bf197 wl_display_run (libwayland-server.so.0 + 0xc197)
                #2  0x00005570d462ff71 main (Hyprland + 0x30f71)
                #3  0x00007f332df54290 n/a (libc.so.6 + 0x23290)
                #4  0x00007f332df5434a __libc_start_main (libc.so.6 + 0x2334a)
                #5  0x00005570d4637d95 _start (Hyprland + 0x38d95)
                
                Stack trace of thread 41067:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41063:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41065:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41797:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41064:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41068:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41070:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41071:
                #0  0x00007f332e03a8af accept (libc.so.6 + 0x1098af)
                #1  0x00005570d46d3463 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN13CEventManager11startThreadEvEUlvE_EEEEE6_M_runEv (Hyprland + 0xd4463)
                #2  0x00007f332e2d62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #3  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #4  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41069:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41066:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 41798:
                #0  0x00007f332dfb44b6 n/a (libc.so.6 + 0x834b6)
                #1  0x00007f332dfb6cd0 pthread_cond_wait (libc.so.6 + 0x85cd0)
                #2  0x00007f332b90799e n/a (radeonsi_dri.so + 0x10799e)
                #3  0x00007f332b8baf8c n/a (radeonsi_dri.so + 0xbaf8c)
                #4  0x00007f332b9078cc n/a (radeonsi_dri.so + 0x1078cc)
                #5  0x00007f332dfb78fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f332e039a60 n/a (libc.so.6 + 0x108a60)
                ELF object binary architecture: AMD x86-64

</details>

Debug dump is completely broken:
![image](https://user-images.githubusercontent.com/68589851/202847058-8a251cbb-79e0-4f34-82bf-76f760044b05.png)

faulty commit:
![image](https://user-images.githubusercontent.com/68589851/202847006-ad23cd32-de16-45d0-8195-7abda3f1d422.png)
This may or may not be an upstream issue

**Comment by vaxerski** [comment]
check on sway

**Comment by JustSimplyKyle** [comment]
Works fine on sway

**Comment by JustSimplyKyle** [comment]
These are fixed.... somehow.......
