### ISSUE TITLE
DPMS on has no effect on latest versions

### ISSUE THREAD

**Issue by Cowboylaserkittenjetshark** [hyprwm/Hyprland#1050]
On some monitors, dpms on does not turn the display on.
@wuyoli mentioned what sounds like the same issue here [#489#issuecomment-1317591810](https://github.com/hyprwm/Hyprland/issues/489#issuecomment-1317591810)
## Expected outcome
`hyprctl dispatch dpms off` turns the display off
`hyprctl dispatch dpms on` turns the display back on
## Noted outcome
`hyprctl dispatch dpms off` turns the display off as expected
`hyprctl dispatch dpms on` _does not_ turn the display back on
## Steps to reproduce
**I can only reproduce this on one of my two monitors.**
1. Use v0.18.0beta or the latest git version of Hyprland (installed from the AUR)
    i. When using v0.17.0beta, everything works as expected
2. Run `hyprctl dispatch dpms off && sleep 10 && hyprctl dispatch dpms on`
3. The display will turn off, but not back on after 10 seconds like expected
4. Switch to another TTY and back, turning the display on

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/202861986-b89ffba7-b1d9-49b4-9166-a3569e9947d0.png)

odd. No issues for me on 2 separate PCs.

Does `misc:mouse_move_enables_dpms` work?

**Comment by Cowboylaserkittenjetshark** [comment]
`misc:mouse_move_enables_dpms` does not work. When I revert back to v0.17.0beta, it does.

I have no issues on my laptop (running latest version), only my desktop monitor.

I get the same output as your screenshot, `dpms on` just doesn't take effect.

**Comment by vaxerski** [comment]
do a `git bisect` then and let me know which commit broke this.

**Comment by Cowboylaserkittenjetshark** [comment]
```23cd1b8c66da3e85692891e985567f6f45f6e501 is the first bad commit
commit 23cd1b8c66da3e85692891e985567f6f45f6e501
Author: vaxerski <vaxry@vaxry.net>
Date:   Sun Nov 13 11:04:28 2022 +0000

    update wlroots dep

 CMakeLists.txt      | 2 +-
 Makefile            | 8 ++++----
 subprojects/wlroots | 2 +-
 3 files changed, 6 insertions(+), 6 deletions(-)

**Comment by vaxerski** [comment]
report to wlroots then

**Comment by Cowboylaserkittenjetshark** [comment]
It looks like a fix had already been merged upstream [here](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3528), so df132e5ff3395a15c1b48461cc588e4222ae1e02 fixes this issue.
