### ISSUE TITLE
Disable VSync

### ISSUE THREAD

**Issue by Teddy-Kun** [hyprwm/Hyprland#1058]
The ability to disable VSync has just been merged into the Wayland repository. I think that Hyprland should allow disabeling VSync and/or launching a window without VSync when launched with a launch variable, so that it can be inserted into the steam launch options (and other launchers as well). Of course the change is brand new so this shouldn't be changed immediately, but I don't know how much needs to be changed for that, so in case its a deep change I opened this feature request early.

**Comment by vaxerski** [comment]
1) protocol got merged but none of the implementations yet
2) wlroots doesn't support it yet

https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3249
