### ISSUE TITLE
Movefocus inconsistent between fullscreen 0 and fullscreen 1

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/Hyprland#1061]
![image](https://user-images.githubusercontent.com/29002762/202921975-9a260c55-5ad0-4e84-8aeb-a91c2f114b5b.png)

If I have this setup on my left monitor, `fullscreen 1` window 1 and then `movefocus r`, window 1 is still shown and focus is now on my right monitor. This doesn't happen if I make window 1 `fullscreen 0` where after the movefocus window 2 is shown.

Similarly, behavior differs when dispatching `movefocus l` on the right monitor and focus shifts to the left monitor. On `fullscreen 1` focus is on an invisible window whereas on `fullscreen 0` the active window changes.

**Comment by vaxerski** [comment]
consistentizededed in 95047fb08327c5a9c38e5daa46cc3241a1b69cbe
