### ISSUE TITLE
Faq entry for not wayland ready apps

### ISSUE THREAD

**Issue by mastromberger** [hyprwm/Hyprland#1062]
I am using an app where the app developers have disabeld wayland support -> from main.c: gdk_set_allowed_backends ("x11");
It took me quite some time to find out why in this app the opening of modal dialogs does not work (same beheavour like in https://github.com/hyprwm/Hyprland/issues/726)

To troubleshoot such apps/problems, hyprctl clients provides the information --> xwayland true/false
Maybe are there are some other "not wayland ready" apps out there, I think an Faq entry would help other users also. 

greetings and thanks for this really nice app

**Comment by vaxerski** [comment]
wrong repo https://github.com/hyprwm/hyprland-wiki
