### ISSUE TITLE
Window corners look weird in 4K

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/Hyprland#1063]
**Steps to reproduce:** Use Hyprland on a 4K monitor with an Nvidia GPU (I have no idea if it could be related).

**Expected outcome:** Window corners that look good and all the same. 

**Noted outcome:** Some window corners look weird and jagged. It seems to also happen when rescaled to 1440p and 1080p.

**4K with AA:**
![20221120_17h05m18s_grim](https://user-images.githubusercontent.com/98901170/202929129-9246000a-caf2-4ec8-8941-12830ea31fcf.png)

![20221120_17h06m38s_grim](https://user-images.githubusercontent.com/98901170/202929092-6f54c3da-52c5-463a-ab22-9a8456635993.png)
![20221120_17h06m38s_grim](https://user-images.githubusercontent.com/98901170/202929148-989afb43-83c3-44ad-ad61-433ed34a8dd4.png)
![20221120_17h06m41s_grim](https://user-images.githubusercontent.com/98901170/202929095-a5510d6d-1f97-4b9b-a7c5-6df085e71b3e.png)
![20221120_17h06m41s_grim
![20221120_17h06m30s_grim](https://user-images.githubusercontent.com/98901170/202929097-d9d8e25a-8cdb-43a0-9404-7f2de8b43e4c.png)
](https://user-images.githubusercontent.com/98901170/202929065-04f1ef29-1778-41ec-b8c6-064ac374f920.png)

**4K without AA:**
![20221120_17h09m59s_grim](https://user-images.githubusercontent.com/98901170/202929166-02834d1a-35a6-4a66-81df-9af8fb4b8eca.png)

![20221120_17h10m05s_grim](https://user-images.githubusercontent.com/98901170/202929170-79e262b6-ed8a-4c63-bb9b-a6cd1ed76a6e.png)
![20221120_17h10m07s_grim](https://user-images.githubusercontent.com/98901170/202929173-8ad5a0e2-9aac-4fe4-a9ba-e374ff0f8426.png)
![20221120_17h10m10s_grim](https://user-images.githubusercontent.com/98901170/202929181-12219a43-b488-4cd9-b170-03424f994918.png)
![20221120_17h10m13s_grim](https://user-images.githubusercontent.com/98901170/202929179-75c22872-134e-4b2c-a56a-6783e548d50e.png)

**Comment by vaxerski** [comment]
I've heard about this ever since I added rounded corners. However...
![image](https://user-images.githubusercontent.com/43317083/202930503-41354288-bfd3-40d8-848c-b6dbaf812824.png)

2880x1800 looks like this to me. Don't have a 4K display to test, but iirc also was an issue sometimes on ultrawides...?

I am planning on touching the rounding shader a bit yea, but this is odd and idk where it comes from.

**Comment by vaxerski** [comment]
Can you test the rounding shader? Disable borders, launch a contrasting window and see its corners. Does it also bug out?

**Comment by vaxerski** [comment]
fixed in c78db1212ba0d0e53b8c636d745ac9b8c379d2e4
