### ISSUE TITLE
Game window never appears after launching it (Dying Light 2)

### ISSUE THREAD

**Issue by Sincide** [hyprwm/Hyprland#1068]
Steps to reproduce:
Start game (Dying light 2 for me) via Steam. 

Noted outcome:
The initial splash screen appears, then dissapears.
After that the game should start and it does, but no window appears, just the music from the game in the background.

Expected outcome:
Game window should be visible after starting it.

Not sure it matters, but I'm running a 3 monitor setup and the splashscreen atleast does not appear on the same monitor that I launched Steam on.

PS: When launching The Binding of Isaac I can get the window to appear by turning off fullscreen and then going fullscreen again. That does not work with Dying Light 2 though.

**Comment by vaxerski** [comment]
1. what is the output of `hyprctl clients` when DL2 is running? (you can hear the audio)
2. what happens if you turn on wine virtual desktop (I assume it's thru proton) or use gamescope?

**Comment by Sincide** [comment]
1. `hyprctl clients
Window a2a8d780 -> steam ~:
	at: 6413,50
	size: 1247,1370
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: Alacritty
	title: steam ~
	pid: 1342367
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0

Window a29a8220 -> [6] WebCord - #hyprland-git-feed (Hypr Development):
	at: 5140,50
	size: 1247,1370
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: WebCord
	title: [6] WebCord - #hyprland-git-feed (Hypr Development)
	pid: 1331086
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0

Window a25e49c0 -> Steam:
	at: 3853,50
	size: 1247,1370
	workspace: 1 (1)
	floating: 0
	monitor: 2
	class: Steam
	title: Steam
	pid: 1362423
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0

Window a2cffb20 -> Dying Light 2:
	at: 0,0
	size: 1,1
	workspace: 3 (3)
	floating: 1
	monitor: 2
	class: steam_app_534380
	title: Dying Light 2 (inactive)
	pid: 1366852
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0

Window a2d06a60 -> hyprctl clients ~:
	at: 2580,50
	size: 1247,1370
	workspace: 1 (1)
	floating: 0
	monitor: 2
	class: Alacritty
	title: hyprctl clients ~
	pid: 1366968
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0`

2.  It works with virtual desktop, but the game itself is all squished, see image:

![image](https://user-images.githubusercontent.com/73416873/203134680-2add74b8-8855-4f88-89d7-937e7e99975c.png)

**Comment by vaxerski** [comment]
if that's what it looks like with wine VD it seems to me like a problem with wine itself. Does it work on sway?

**Comment by Sincide** [comment]
Yes, it works on sway

**Comment by vaxerski** [comment]
ouch. No clue though why wine vd is broken, it's not governed by hl. odd.

**Comment by vaxerski** [comment]
should be fixed with 7e523e4d5e526bdf5ab86a8f4fe37efeef356707 :)

**Comment by NextWork123** [comment]
@vaxerski i tested and is working good thanks for fixed that :+1:
