### ISSUE TITLE
Add `scroll_button` to input configuration

### ISSUE THREAD

**Issue by archer-65** [hyprwm/Hyprland#1070]
I'm trying Hyprland for the first time, and I'm enjoying it a lot! Good job :D.

There is only one small problem: I use a trackball, and I need to set the `scroll_button` (libinput) option. 
I have read the wiki, searched among the issues, and also in the source code, I didn't find anything, is it possible to add this feature?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Binds/#mouse-buttons

**Comment by archer-65** [comment]
> https://wiki.hyprland.org/Configuring/Binds/#mouse-buttons

Sorry, maybe I'm misunderstanding, but how is that supposed to solve my problem? I need to set a scroll button to make use of the `on_button_down` scroll method, not to use that button as a keybind.

Do you mean it is possible to do something like `bind=SUPER,mouse:272,exec,scroll_command_i_dontknow_about` ?

Anyway, I do this on sway:
```
 input."1390:268:ELECOM_TrackBall_Mouse_HUGE_TrackBall" = {
   scroll_method = "on_button_down";
   scroll_button = "BTN_TASK";
 };
```

**Comment by vaxerski** [comment]
oh wait, I misunderstood your question.

**Comment by archer-65** [comment]
> oh wait, I misunderstood your question. 

Don't worry :)

**Comment by vaxerski** [comment]
added in eb86e7967f7d218a7c9412e484473fd578dbf64c
