### ISSUE TITLE
Window border gradient

### ISSUE THREAD

**Issue by Teddy-Kun** [hyprwm/Hyprland#1072]
I was thinking about how I could spice up my rice and this came to my mind.
Could we get the ability to set 2 colors for a window border and then have a gradient between them?

**Comment by vaxerski** [comment]
added in 0948b078e1789605c42746a024df6039bb566b45

![image](https://user-images.githubusercontent.com/43317083/204102540-1877ddb8-d792-4313-af87-e347148ca23d.png)

have fun :^)

**Comment by bklaase** [comment]
yeah gradient is amazing! Would it be possible to have it on grouped windows too?

**Comment by vaxerski** [comment]
yeah ping me on discord tmr
