### ISSUE TITLE
Performance issues with a high workspace ID open

### ISSUE THREAD

**Issue by coolGi2007** [hyprwm/Hyprland#1073]
### What I was doing beforehand:
I was doing some testing to see what the highest workspace possible with Hyprland is. It came up to 2147483647.\
Then, when I was done, I just kept a terminal window open to not close off that workspace.\
But afterwords, the compositor froze when I used certain methods for switching workspaces.

### How to recreate
Doing `hyprctl dispatch workspace e+1` would cause a lag spike, and swiping left/right on trackpad also caused the same lag spice.

Image of bottom showing it uses all resources for a small amount of time (it just shows that only 1 core is being used to process this, but this 1 core is halting the entire wm)
![btm in terminal](https://user-images.githubusercontent.com/57488297/203316655-4d773b0d-f577-4259-8aeb-929de13b2c8f.png)

#### Extra note
Another thing to note is that there is no lag when switching from any workspace using the trackpad from 1 to the last workspace from the large gap. So in this image I can switch through all the workspaces just fine except for with workspace 10 which lags even when I try to swipe to the left (to get to workspace 5).
![Open workspaces in waybar](https://user-images.githubusercontent.com/57488297/203317192-c1fb165e-fff5-4e5d-81fe-0f325f18fe6d.png)
The lag also doesn't happen when using the `hyprctl` command to switch manually to that workspace (and the sliding animation plays just fine)

#### Suggestion to fix this
Could there be a list storing all the indexes of the open workspaces, then when switching workspaces you get the ID of the workspace to show by subtracting or adding 1 from the index of the current open index.\
This is because what I think you are doing (I haven't checked the code, so this is just a guess) is going changing workspace ID's until you reach one that has a window open.

This is probably a very low priority as I don't think anyone is going to open up 2147483647 workspaces any time soon, but best to have this report in case someone actually needs that many workspaces for some reason.

**Comment by vaxerski** [comment]
should be fixed with 0803febac521ae07394eb10a628b9507118335eb
