### ISSUE TITLE
Position window with unknown size at right bottom

### ISSUE THREAD

**Issue by niki-on-github** [hyprwm/Hyprland#1075]
I want to place my mpv window with `autofit` configuration at the bottom right of my screen. Currently the `move [x] [y]` rule only allow to set positions by subtract fix offset values for `x` and `y`. 

Since I don't know any use case where you want to move the window out of the screen to the right, I simply subtracted the size of the window when the right or bottom pane is selected with '100%-' option in [my fork](https://github.com/hyprwm/Hyprland/compare/main...niki-on-github:Hyprland:fix/move-right-bottom).  Maybe we could adopt this solution **or** introduce a variable which is substituted by the window size at runtime for the `move [x] [y]` rule.

**Comment by bd4** [comment]
I'd love to see this feature too!
