### ISSUE TITLE
windowrulev2 not working if title/class is not available at window startup

### ISSUE THREAD

**Issue by niki-on-github** [hyprwm/Hyprland#1076]
When the title or class is not available at window startup all rules that are not included in the [dynamic rules](https://github.com/hyprwm/Hyprland/blob/95047fb08327c5a9c38e5daa46cc3241a1b69cbe/src/Window.cpp#L379) will not be applied to the window. 

Example `windowrulev2` rule:
```
windowrulev2 = tile,title:^(Spotify)$,xwayland:1,
```

Spotify always start in floating mode because the title is not available at startup (from log):

```
[LOG] Searching for matching rules for  (title: )
```

My workaround for now is to call [`listener_mapWindow`](https://github.com/hyprwm/Hyprland/blob/95047fb08327c5a9c38e5daa46cc3241a1b69cbe/src/events/Windows.cpp#L46) when `listener_setTitleWindow` is called (See [niki-on-github:Hyprland:fix/xwayland-windowrulev2](https://github.com/hyprwm/Hyprland/compare/main...niki-on-github:Hyprland:fix/xwayland-windowrulev2).

**Comment by taylor85345** [comment]
This is a known issue with spotify that doesn't have an easy solution. The current recommended workaround is to use [spotifywm](https://github.com/amurzeau/spotifywm)

**Comment by vaxerski** [comment]
doop of #382
