### ISSUE TITLE
Is it possible to configure a monitor with hyprctl ?

### ISSUE THREAD

**Issue by jrgiacone** [hyprwm/Hyprland#1079]
On the chance I wanted to disable and enable a monitor with a keybind is it possible to do this with hyprctl and how? I have not been able to figure it out?

**Comment by vaxerski** [comment]
hyprctl keyword monitor ...

**Comment by jrgiacone** [comment]
> hyprctl keyword monitor ...

hyprctl monitors=DP-2, 1920x1080@144, 0x0, 1 gives unknown request?

**Comment by pinkcreeper100** [comment]
you're missing an argument

**Comment by jrgiacone** [comment]
> ![image](https://user-images.githubusercontent.com/43317083/203641004-c0cbba0c-d5c3-4aec-b0d8-410a92f06d03.png) ![image](https://user-images.githubusercontent.com/43317083/203641013-fc56b7be-97ab-4021-b939-90c25f900464.png)
> 
> I tell you what to do. You do something else. Don't be surprised it doesn't work.
> 
> https://wiki.hyprland.org/Configuring/Using-hyprctl/

I'm really sorry I honestly misunderstood, thank you for your help
