### ISSUE TITLE
Hyprland completely froze

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1081]
I wasn't even able to switch to a tty.
So that may indicate that the problem is not on hyprlands side.
Anyway here is the log: 
[log.txt](https://github.com/hyprwm/Hyprland/files/10072247/log.txt)

and my config: [config.txt](https://github.com/hyprwm/Hyprland/files/10072250/config.txt)

I don't have a stacktrace of hyprland because it didn't crash, but i have a stack trace of xwayland if that helps: [xwayland-stacktrace.txt](https://github.com/hyprwm/Hyprland/files/10072251/xwayland-stacktrace.txt)

If you don't think it is a Hyprland bug, feel free to close the issue.

**Comment by DashieTM** [comment]
config.txt? As far as I know hyprland searches for hyprland.conf, unless you just renamed this here.
Other than that, is there any way to reproduce this? Specific applications that were open?

**Comment by Quantenzitrone** [comment]
you can't upload a .conf file to a github comment/issue

**Comment by DashieTM** [comment]
Alright good to know, thanks.

**Comment by K1llf0rce** [comment]
possibly related to #1103

**Comment by vaxerski** [comment]
> I wasn't even able to switch to a tty.
So that may indicate that the problem is not on hyprlands side.

TTY switching is handled by hyprland lol

**Comment by Quantenzitrone** [comment]
why is that? doesn't that defeat half of the purpose of the tty?

**Comment by vaxerski** [comment]
cuz thats how linux works. No

**Comment by Quantenzitrone** [comment]
Ok sorry for me being a noob, but wouldn't it be neat for debugging purposes, to have the TTY switching be handled by a separate process?
Like I am not 100% sure how it is handled on xorg, but afaik even when the xorg window manager freezes for some reason, you can still switch to a tty and `killall X` or something.

**Comment by yavko** [comment]
This is happening to me too

**Comment by yavko** [comment]
Seems we both use nix, it might be a nix issue

**Comment by K1llf0rce** [comment]
any specific program I can use to try and reproduce this, or is it crashing randomly?

**Comment by vaxerski** [comment]
> Like I am not 100% sure how it is handled on xorg, but afaik even when the xorg window manager freezes for some reason, you can still switch to a tty and killall X or something.

Because an xorg wm and xorg are separate. If xorg would hang, you wouldn't be able to switch ttys either. Hyprland is the xorg here.

Anyways offtopic.

**Comment by yavko** [comment]
> any specific program I can use to try and reproduce this, or is it crashing randomly?

Its not crashing, its freezing, and seems to occur on NixOS

**Comment by K1llf0rce** [comment]
> > any specific program I can use to try and reproduce this, or is it crashing randomly?
> 
> Its not crashing, its freezing, and seems to occur on NixOS

Sorry, I meant freezing. So is it freezing randomly or is it triggered by a specific action or program?
I'm asking because of a similar issue I have with certain programs which either crash or freeze Hyprland. I'd like to know if this is related or not.

**Comment by yavko** [comment]
> > > any specific program I can use to try and reproduce this, or is it crashing randomly?
> > 
> > 
> > Its not crashing, its freezing, and seems to occur on NixOS
> 
> Sorry, I meant freezing. So is it freezing randomly or is it triggered by a specific action or program? I'm asking because of a similar issue I have with certain programs which either crash or freeze Hyprland. I'd like to know if this is related or not.

On launch, it takes about like 3 seconds then permanent freeze of the whole compositor

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Haven't seen this behaviour since @vaxerski fixed tty switching long ago. I'll update and check when I have time.

**Comment by justinesmithies** [comment]
Hyprland completely freezes my laptop if I run ardour and do Ctrl + I to open the import window then close the window . the whole system just freezes indefinitely. Works fine with sway and Qtile Wayland.

**Comment by K1llf0rce** [comment]
> Hyprland completely freezes my laptop if I run ardour and do Ctrl + I to open the import window then close the window . the whole system just freezes indefinitely. Works fine with sway and Qtile Wayland.

Can reproduce this on both Hyprland and Sway, seems to also be [this wlroots issue](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3545).

**Comment by yavko** [comment]
Its on startup, for me, not anything else

**Comment by yavko** [comment]
Any progress on this?

**Comment by vaxerski** [comment]
None because I can't repro

**Comment by yavko** [comment]
> None because I can't repro

If I can record it happening could that help?

**Comment by vaxerski** [comment]
nope. You can try running with ASan though if you can repro the hangup.

**Comment by yavko** [comment]
Seems to be fixed now!

**Comment by Quantenzitrone** [comment]
im currently not using hyprland so i can't test, but i can reopen if it happens again
