### ISSUE TITLE
toggleopaque dispatcher by window class

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#1082]
The current dispatcher `toggleopaque` seems to make the current window opaque by using it's `title` to determine its uniqueness.
For example, if I switch tabs in Firefox (or rather Librewolf, but that doesn't matter) the window `title` changes and thus the opaqueness resets.
To make this experience less painful (I have to call `toggleopaque` every time I switch tabs) I think toggling opaqueness by window `class` would be preferable.

**Comment by Quantenzitrone** [comment]
sorry i send too early

**Comment by vaxerski** [comment]
probably introduced by that one guy and his dynamic window rules. Will fix.

**Comment by vaxerski** [comment]
fixed in dcb6a0425c1c902555fac43441c0581afb2defd4

toggleopaque will now override the window rules for opaque
