### ISSUE TITLE
Pin tiled windows

### ISSUE THREAD

**Issue by CaptaiNiveau** [hyprwm/Hyprland#1084]
I know of the feature that enables pinning of floating windows and I'd love to use that for normal tiled windows as well. I've looked at the IPC section in the wiki and this feature could possibly be implemented that way, too. Making it a core feature makes more sense to me though as it's already been done for floating windows, that's why I'm writing this suggestion.

My idea is that a pinned tiled window would stay in the same position across all workspaces on the same monitor. That way I'd be able to switch only parts of the current screen and keep the pinned windows there. The size of the windows wouldn't have to remain the same, just putting them in a similar position and then preserving the layout for the respective workspace would be nice. A pinned window might be in different positions and sizes if you rearrange them in a specific workspace.

Ideally you'd be able to specify that a window should only be pinned to specific workspaces.

**Comment by vaxerski** [comment]
no.

**Comment by CaptaiNiveau** [comment]
Why not? It'd be quite useful to me. 
This feature is definitely something I'd want to have so I might try to do it myself somehow. Do you have a suggestion how I could go about that?

**Comment by vaxerski** [comment]
it's not useful, no wm / de / compositor has that for a reason, and the current layout system is very much not made for that.

**Comment by CaptaiNiveau** [comment]
KDE for example has a [functionality similar to this](https://www.reddit.com/r/kde/comments/f4d6in/til_rightclick_windows_in_desktop_overview_pin/), but that's more comparable with pinning floating windows I guess.
In the same thread the OP explains a similar use case for this as I have. Personally I'd like to use the left half of my main monitor permanently for the IDE while I'm able to switch apps on the right half. Maybe I could implement a similar behavior with floating windows, but the obvious issue there is that the IDE wouldn't block the space it uses and therefore would cover other apps.
