### ISSUE TITLE
Is it possible to disable inputs like keyboard via hyprctl?

### ISSUE THREAD

**Issue by FZDSLR** [hyprwm/Hyprland#1086]
Is there a way to disable inputs like keyboard and touchpad via hyprctl? I'm using a 2-in-1 laptop and I want to disable them after the tablet:on switch event to prevent mistakenly touching.

**Comment by vaxerski** [comment]
touchpad yes
keyb no

**Comment by vaxerski** [comment]
but keyb is planned
