### ISSUE TITLE
Using `movefocus` to navigate inside group

### ISSUE THREAD

**Issue by sant0s12** [hyprwm/Hyprland#1087]
Hi,

Coming from i3, I am used to using the normal focus keybindings for moving inside the "tabs" or (groups in hyperland).
I was wondering if the same thing can be done in hyperland (I know inside a group you can use `changegroupactive` but I have not found a way to use the same key bindings for changing focus both inside and outside groups).

In case this is not possible as of now, could you consider adding this feature?

Thanks!

**Comment by vaxerski** [comment]
how would you move outside the group then?

**Comment by sant0s12** [comment]
When you are at the right/leftmost of the group and move right/left. Basically the way it works in i3 (I know hyprland is not supposed to be an i3 replacement but I do think this way of doing it is nice).

**Comment by selfuryon** [comment]
The same for me, it would be really cool to have the possibility to configure the same behavior for tab group. Using different hotkey is frustrating, can't find any comfortable key binding for that...

**Comment by Aqa-Ib** [comment]
I think that Hyprland's approach on this matter is better than i3's. 
Of course, an option to select the approach that you prefer would be even better.

**Comment by raidzero** [comment]
I worked around this with a simple script:

```
#!/bin/bash

groupSize=$(hyprctl activewindow -j | jq -r '.grouped | length')

if [[ "$groupSize" > 0 ]]; then
    IN_GROUP=1
else
    IN_GROUP=0
fi

if [[ "$1" == "left" ]]; then
    if [ $IN_GROUP -eq 1 ]; then
        hyprctl dispatch changegroupactive b
    else
        hyprctl dispatch movefocus l
    fi
else
    if [ $IN_GROUP -eq 1 ]; then
        hyprctl dispatch changegroupactive f
    else
        hyprctl dispatch movefocus r
    fi
fi
```

then I bind it to my focus keys:
```
bind=SUPER,h,exec,~/.config/hypr/focus.sh left
bind=SUPER,l,exec,~/.config/hypr/focus.sh right
bind=SUPER,k,movefocus,u
bind=SUPER,j,movefocus,d
```

Yeah, you cannot leave the group, but I still have a mouse that can focus other things. Seems like an OK compromise. It'd be cool to be able to click on the group indicator to move focus within the group.

**Comment by Diegovsky** [comment]
> how would you move outside the group then?

@vaxerski: the way sway (and I believe i3) does it is using window trees. A group contains multiple windows, so to move out of it, (assuming you're currently in a window inside a group) you go a "level" up and now you're at the same level as the group (not its windows), allowing you to treat the group as a window and move anywhere from there.

**Comment by vaxerski** [comment]
pretty easily scriptable

**Comment by Diegovsky** [comment]
Not exactly scriptable. AFAIK, you can't have splits inside hypr groups. They're their own thing. You should try Sway for yourself to see what I'm talking about. The tree navigation feature can only be done inside hypr (or a plugin). This would unify all of the movements, making the `movegroup` command family pointless.

I'm short on time to look into a script and/or plugin and I'm sure you have more important issues than this to work on, so if anyone develops anything like what I'm describing, please ping me! I'm interested :)

Btw loving hyprland

**Comment by topisani** [comment]
With #3683 this behavior is scriptable. See my comment for an example

**Comment by sant0s12** [comment]
For anyone that stumbles upon this issue, I have been using https://github.com/outfoxxed/hy3 and it solves this issue completely.

**Comment by sant0s12** [comment]
For anyone that stumbles upon this issue, I have been using https://github.com/outfoxxed/hy3 and it solves this issue completely.

**Comment by Diegovsky** [comment]
Thank you very much for this!

**Comment by hhhapz** [comment]
For posterity, I updated the shared bash script above to properly support leaving a group as well. Here's my updated bash script:
```bash
#!/bin/bash

data=$(hyprctl activewindow -j)
groupSize=$(echo "$data" | jq -r '.grouped | length')
address=$(echo "$data" | jq -r '.address')
groupIndex=$(echo $data | jq --arg address "$address" -r '.grouped | index($address)')

IN_GROUP=0
if [[ "$groupSize" > 0 ]]; then
    IN_GROUP=1
fi

if [[ "$1" == "left" || "$1" == "l" ]]; then
    if [[ "$IN_GROUP" == 1 && "$groupIndex" > 0  ]]; then
        hyprctl dispatch changegroupactive b
    else
        hyprctl dispatch movefocus l
    fi
else
    if [[ "$IN_GROUP" == 1 && "$((groupIndex + 1))" < "$groupSize" ]]; then
        hyprctl dispatch changegroupactive f
    else
        hyprctl dispatch movefocus r
    fi
fi
```

**Comment by dandy-is-lion** [comment]
> For posterity, I updated the shared bash script above to properly support leaving a group as well. Here's my updated bash script:
> 
> ```shell
> #!/bin/bash
> 
> data=$(hyprctl activewindow -j)
> groupSize=$(echo "$data" | jq -r '.grouped | length')
> address=$(echo "$data" | jq -r '.address')
> groupIndex=$(echo $data | jq --arg address "$address" -r '.grouped | index($address)')
> 
> IN_GROUP=0
> if [[ "$groupSize" > 0 ]]; then
>     IN_GROUP=1
> fi
> 
> if [[ "$1" == "left" || "$1" == "l" ]]; then
>     if [[ "$IN_GROUP" == 1 && "$groupIndex" > 0  ]]; then
>         hyprctl dispatch changegroupactive b
>     else
>         hyprctl dispatch movefocus l
>     fi
> else
>     if [[ "$IN_GROUP" == 1 && "$((groupIndex + 1))" < "$groupSize" ]]; then
>         hyprctl dispatch changegroupactive f
>     else
>         hyprctl dispatch movefocus r
>     fi
> fi
> ```

Similarly you can replace `changegroupactive` with `movegroupwindow` and `movefocus` with `movewindoworgroup` for i3-like window moving/reordering in and out of groups. Though moving a window from the left into a group from the right doesn't insert it into the beginning of the group.

**Comment by alejoguitar** [comment]
@hhhapz , I use your variables (I suck with jq, but hyprctl is making me learn a lot from it) but changed completely the conditional logic so to make the script to act as close as possible to I3/Sway. Only caveat is that when you switch focus from a regular window to a group, you won't focus the grouped window next to it. But, for the rest, applying the correct binds, it works like a charm.
Here's my version of your script, which I believe it could be helpful for anybody else trying to get this feature:

```shell
#!/usr/bin/env sh

action=$1
direction=$2

if [[ -z $1 ]]; then 
  echo "please specify modes move or switch and direction l or r"
  exit 1
fi 

data=$(hyprctl activewindow -j)
groupSize=$(echo "$data" | jq -r '.grouped | length')
address=$(echo "$data" | jq -r '.address')
groupIndex=$(echo $data | jq --arg address "$address" -r '.grouped | index($address)')

if [[ $action == "move" ]]; then 
  command_group=movegroupwindow
  command_window=movewindoworgroup
elif [[ $action == "switch" ]]; then
  command_group=changegroupactive
  command_window=movefocus
fi 

if [[ $direction == "l" || $direction == "left" ]]; then
  param_group=b 
  param_window=l 
elif [[ $direction == "r" || $direction == "right" ]]; then
  param_group=f 
  param_window=r
fi 

if [[ $(( $groupIndex + 1 )) = $groupSize && $param_window = r ]] || [[ $(( $groupIndex + 1 )) = 1 && $param_window = l ]] || [[ $groupSize = 0 ]]; then
  arguments="$command_window $param_window"
else
  arguments="$command_group $param_group"
fi

hyprctl dispatch $arguments
``` 

when calling the script, the arguments are: 
<path/to/script> [move|switch] [left|l|right|r]
which can be easily called with the regular keybindings.
