### ISSUE TITLE
Focus fullscreen window when moving focus between monitors

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/Hyprland#1090]
With [return full monitor box for fullscreen windows in idealBB](https://github.com/hyprwm/Hyprland/commit/95047fb08327c5a9c38e5daa46cc3241a1b69cbe) moving focus inside a fullscreen workspace behaves as if there was only the fullscreen window, skipping other windows. Moving focus back it is possible to end up on a different window.

To improve this I'd suggest that when movefocus changes the active monitor and the new monitor has a fullscreen window that fullscreen window should get the focus even if another window would be closer.

**Comment by vaxerski** [comment]
fixed in f6067816fb2bbd7dc9a00da6391cc6dcf5991035
