### ISSUE TITLE
gtk-layer-shell window not disappearing even after pkill

### ISSUE THREAD

**Issue by aryanjassal** [hyprwm/Hyprland#1092]
I have been using the eww bar for a while now and it worked like a charm, until I added the feature to toggle the window open or close. When I close the eww window and quickly switch to a different workspace, the phantom window remains on top of the screen for a while. This issue remains even after `pkill`-ing the eww process. 

`hyprctl layers` reveals that the `gtk-layer-shell` eww layer remains visible after closing the bar or even killing the eww process.

### STEPS TO REPRODUCE

- Clone and build `eww-wayland`
- Make and open an eww window
- Close the window
- Quickly cycle through multiple workspaces before the eww window fades out completely

### EXPECTED OUTCOME

The bar should just disappear and changing the workspace should not have an effect on it.

### NOTED OUTCOME

A ghost image of the bar remains for a few seconds when switching between workspaces quickly before disappearing completely.

**Comment by vaxerski** [comment]
seems like an issue with eww / you killing poorly. Hyprland will remove the layer whenever it receives an appropriate event from wlroots.

**Comment by aryanjassal** [comment]
I killed the bar with every conceivable method, so I don't think that it is me killing the bar poorly. I will try harder to find the weak link within eww if it exists.

**Comment by vaxerski** [comment]
does it happen on sway

**Comment by aryanjassal** [comment]
No. I just installed sway to test, but the behaviour was as expected in Sway, the bar closing immediately and not showing a ghost window upon rapidly switching the workspace.

**Comment by vaxerski** [comment]
wait, what if you disable animations?

**Comment by aryanjassal** [comment]
The problem still persists even if I disable all animations, including `windows` and `windowsOut`

**Comment by vaxerski** [comment]
does this still happen?

**Comment by aryanjassal** [comment]
sorry but i have switched to daily driving kde plasma and cannot easily test this out anymore

**Comment by vaxerski** [comment]
feel free to reopen then in case it's an issue again
