### ISSUE TITLE
REAPER never appears after launching

### ISSUE THREAD

**Issue by mgil2** [hyprwm/Hyprland#1093]
REAPER is a DAW published by Cockos used in music production.

I am currently on the latest Arch Linux, all packages up to date. It was installed via pacman under the official community repo. I did notice it has an X11 dependency and perhaps this is an XWayland issue but it does not happen in sway.

Normal behavior in other DEs has a floating window indicating its launching reaper, and then reaper launches a full window upon loading everything it needs to function. As far as I know, Reaper does not use qt5 or gtk themes.

htop indicates reaper is running and all plugins (which have separate processes) are all running, taking a predictable amount of ram. Reaper normally tries to open the last working project, and Ive run a test where I monitor output and can hear my own microphone indicating it is fully running and functioning. Its just the window not being produced.

Hyperctl clients do not list reaper at all, as if it does not exist. All other windows show up in the client list.

**Comment by vaxerski** [comment]
can you launch hyprland, launch reaper, close hyprland and attach the log here?

**Comment by mgil2** [comment]
Log attached via paste bin. Thank you for taking the time to help..

https://pastebin.com/izHGmK8K

**Comment by vaxerski** [comment]
```
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
[LOG] Process Created with pid 2499
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
[LOG] Process Created with pid 2501
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 ./.config/hypr/portals.sh
[LOG] Process Created with pid 2503
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 hyprpaper
[LOG] Process Created with pid 2505
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 dropbox
[LOG] Process Created with pid 2507
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 dunst
[LOG] Process Created with pid 2509
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 kwalletd5
[LOG] Process Created with pid 2512
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 waybar
[LOG] Process Created with pid 2515
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 /usr/lib/polkit-kde-authentication-agent-1
[LOG] Process Created with pid 2517
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 ckb-next --background
[LOG] Process Created with pid 2522
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 webcord --ozone-platform=wayland
[LOG] Process Created with pid 2524
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 reaper
[LOG] Process Created with pid 2526
```
Please launch ***only*** reaper, and not from an `exec` keyword, open a terminal / wofi and launch reaper via that.

**Comment by mgil2** [comment]
I closed Hyprland, commented out my entire exec-once list including the xdg-desktop-portals patch related to apps opening slowly. XDG Current and Session desktops are set to Hyprland, gdk backend and qt qpa platform are set to wayland as well as xdg session type. I had a previous instance of reaper running, killall'ed it and started it from kitty.

https://pastebin.com/g7KXv9mW

**Comment by vaxerski** [comment]
odd. This seems like reaper never requests.... anything. No window opened, no surface created. Wot de foq?

**Comment by mgil2** [comment]
Any logs I can check out to further dig into this? Im 90% sure it tries to open as an XWayland window due to the libx11 and libxi dependencies in the arch package. Journalctl and dmesg dont output anything particularly interesting (I can paste those if you think they'll help, but running "| grep reaper" on them returns nothing). Running reaper on terminal merely outputs a few jack-related messages (which is normal behavior anyhow).

I can confirm it opens fine on wayland kde and sway.

**Comment by vaxerski** [comment]
I genuinely have no clue. You might want to ask reaper's devs about wtf is going on

**Comment by mgil2** [comment]
Thank you. Figured it out, though the fix isn't pretty.

I have GDK_BACKEND set to wayland. Running reaper while setting it to x11 finally fixes it. I guess I didn't have sway or kde running under that variable.

Thank you for the help!

**Comment by vaxerski** [comment]
you can use `wayland;x11` btw

**Comment by Mxm40b** [comment]
Using `wayland;x11` fails, but using `x11` works. Thanks for the fix
