### ISSUE TITLE
Resize gaps dispatcher

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#1095]
Hello. This would be a nice feature to have in my humble opinion.
For example: `bind = SUPER, G, resizegaps, 5 10` increments in 5 the outer gaps and in 10 the inner gaps.

Thank you so much for your attention. Cheers!

**Comment by vaxerski** [comment]
makes no sense. Read the current values and set new ones.

**Comment by Aqa-Ib** [comment]
I am changing the values all the time though. Sometimes I prefer seeing more of the wallpaper because it makes me feel more free/comfortable, and other times I prefer that the windows take more screen space to focus more. But I can understand if you don't want to code this one for weirdos like me hehe. 
Anyway, thank you very much for everything vaxerski, have a good one!

**Comment by vaxerski** [comment]
getopt exists

**Comment by Aqa-Ib** [comment]
Thank you for the tip! I will learn the getopt way of doing it. Peace and love.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Using-hyprctl/ useful link

**Comment by Aqa-Ib** [comment]
I accomplished it with two fish scripts:

bind=SUPER,minus,exec,fish ~/.config/hypr/border_decrease.sh
```
#!/bin/fish
set -U gaps_out (math $gaps_out-10); hyprctl keyword general:gaps_out $gaps_out
set -U gaps_in (math $gaps_in-10); hyprctl keyword general:gaps_in $gaps_in
```
bind=SUPER,plus,exec,fish ~/.config/hypr/border_increase.sh
```
#!/bin/fish
set -U gaps_out (math $gaps_out+10); hyprctl keyword general:gaps_out $gaps_out
set -U gaps_in (math $gaps_in+10); hyprctl keyword general:gaps_in $gaps_in
```

Maybe it is not the most academic way of doing it but fuck it, it is working great.
For anyone wanting to make it work, first you have to declare the variables in a fish shell. You only have to do this one time, since fish remembers the variables even after the computer powers off:
set -U gaps_out 50
set -U gaps_in 50

Then put the binds in hyprland.conf and the scripts in place. Enjoy!
