### ISSUE TITLE
bemenu runs command automatically and closes

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [hyprwm/Hyprland#1096]
- Steps to reproduce
1.use bemenu with networkmanager_dmenu script
config file:https://gist.github.com/J4ckTh3R1pper/c85ed365aa5305eb7aa4db1d4e92e73b

2.open networkmanager_dmenu with mouse click on wofi

- Expected outcome
The bemenu window works normally

- Noted outcome
The first command on the list was issued instantly when the bemenu window opened. It seems like when I clicked the mouse button over the wofi menu that was used to launch bemenu, bmenu also read this click action and then ran the first command on the list, which was selected automatically on launch.

**Comment by vaxerski** [comment]
does this still happen?

**Comment by J4ckTh3R1pper** [comment]
Using -n or --no-overlap resolves this issue
