### ISSUE TITLE
Toggling special workspace with fullscreen puts waybar on top of fullscreen window

### ISSUE THREAD

**Issue by thomascft** [hyprwm/Hyprland#1098]
When toggling the special workspace on while the focused window is fullscreen moves the waybar on top of the fullscreen window. After closing the special workspace the bar stays on top of the fullscreen window until you cycle/exit fullscreen.

**Comment by vaxerski** [comment]
fixado in 9616dc7bd865ae46fb23018a7d49741f81d472a8
