### ISSUE TITLE
Seperate Workspaces per each monitor

### ISSUE THREAD

**Issue by MrEnxo** [hyprwm/Hyprland#1099]
Im not sure if this is a feature already but I want this to exist.

So each monitor has their own set of seperate workspaces 
so if workspace 1 on monitor 1 would have fire fox open
and workspace 1 on monitor 2 could have a terminal open

This is how DWM works and it would be a nice option of have

**Comment by vaxerski** [comment]
use something like https://github.com/sopa0/hyprsome

**Comment by MrEnxo** [comment]
thank you!

**Comment by teackot** [comment]
> use something like https://github.com/sopa0/hyprsome

It's a workaround, but not a solution. It has a lot of issues e.g. it doesn't work good with touchpad gestures (gestures is a core feature for me tbh).

I see it like this: each monitor has it's own set of independent workspaces. When you swipe the touchpad (or press a keyboard shortcut) you switch between workspaces on the monitor which has the focus. When a new WS is created, it is only created on the corresponding monitor.

Or how Gnome does it right now: all monitors have the same number of independent workspaces and you switch between them at the same time on all monitors (so, when one monitor has WS 3 on it, all other monitors have their own WS 3 on them)
