### ISSUE TITLE
Use of strings in config file

### ISSUE THREAD

**Issue by addy419** [hyprwm/Hyprland#1101]
I am on latest nixos flake version of hyprland on nixos.

I want to exec something like `dmenu-wl_run -b -h 32 -i -p "run:" -nf "#f8f8f2" -nb "#282a36" -sf "#282a36" -sb "#ff79c6"` in my config file but this does not work. Removing the quote works but that is not what I wanted, the command needs strings. How do I pass bash string parameters to exec?

**Comment by vaxerski** [comment]
you have a # there isterpreted as a comment marker. Escape it with ##

**Comment by addy419** [comment]
There was no need to escape the quote. Escaping # worked just fine
