### ISSUE TITLE
Set special workspace to be top level

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#1102]
The special workspace is hidden behind some fullscreen windows.
It doesn't hide e.g. behind kitty fullscreen windows, but it does if the fullscreen window is mpv or qutebrowser.

**Comment by vaxerski** [comment]
does this go away with general:no_direct_scanout set to true?

**Comment by vaxerski** [comment]
should be fixed in 381d7a430072c7b29bc5f5eb808ffbb86abefbd1

**Comment by Dickby** [comment]
it does go away with no_direct_scanout (which is 'misc' not 'general').
Don't know if that still helps.

**Comment by Dickby** [comment]
It's fixed.
Thanks!
