### ISSUE TITLE
Hyprland crashes on GTK File-Chooser window resize

### ISSUE THREAD

**Issue by K1llf0rce** [hyprwm/Hyprland#1103]
Some GTK file choosers seem to crash Hyprland for me. I observed it with Nextcloud and Shotcut so far.

### - Steps to reproduce

- open an app that displays a GTK file chooser when browsing for a file (in my case Nextcloud)
- try to resize the window

### - Expected outcome

- window resizes

### - Noted outcome

- Hyprland crashes

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/10094826/hyprland.conf.txt)
[coredump.txt](https://github.com/hyprwm/Hyprland/files/10094827/coredump.txt)
[hyprland_tail.log.txt](https://github.com/hyprwm/Hyprland/files/10094829/hyprland_tail.log.txt)

https://user-images.githubusercontent.com/43351274/204045575-bb14ba93-e08f-4ac8-aa33-789caaaf791c.mp4

Above is how I can reproduce it, video ends right where it crashes.

**Comment by vaxerski** [comment]
Crash doesn't seem hyprland-related (libwayland just dies) and I can't get a GTK4 picker on my system with shotcut (idk how nextcloud works) but I have them with firefox and they work just fine. Do firefox ones crash too?

**Comment by K1llf0rce** [comment]
Firefox ones don't seem to crash for me either. Could be that this is totally unrelated to Hyprland and I initally had the same thought. 
But what is interesting is that if I switch from Hyprland 0.18 to 0.17, the Nextcloud and Shotcut file choosers don't crash Hyprland anymore.

**Comment by vaxerski** [comment]
do a `git bisect` then!

**Comment by K1llf0rce** [comment]
So it seems like [`e2da4ff`](https://github.com/hyprwm/Hyprland/commit/1a14841a75b2c387b9f67b7f7c40e0b5d3e1f86b) is the last commit that I can build from, where I don't get the crashing behavior.
Next commit would be [`549fdf6`](https://github.com/hyprwm/Hyprland/commit/549fdf63f6f72fadf4e1f67f42fc2a99d625b42e) which is the border color rule, and that's where the crashing behavior starts.

**Comment by vaxerski** [comment]
well that makes zero sense

**Comment by K1llf0rce** [comment]
OK, I found some time to look into this again and retested to really see if [`549fdf6`](https://github.com/hyprwm/Hyprland/commit/549fdf63f6f72fadf4e1f67f42fc2a99d625b42e) was the faulty commit and it seems like it actually isn't. Must have been unlucky that I didn't get it to crash yesterday.
Anyway, what makes more sense now is that the faulty commit is [`23cd1b8`](https://github.com/hyprwm/Hyprland/commit/23cd1b8c66da3e85692891e985567f6f45f6e501) (wlroots update). I think they changed quite a few things in the last release, didn't they? Maybe there is some condition that is unhandled yet.
Also tested the crashing programs with sway today and they work fine there.

**Comment by vaxerski** [comment]
Report to wlroots then and attach the coredump.

**Comment by K1llf0rce** [comment]
Yep, just reproduced the crash in sway as well when building from latest master. Seems to be wlroots related.

**Comment by K1llf0rce** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3545

**Comment by vaxerski** [comment]
@K1llf0rce you got asked to repro with ASan. If you need help on how to do that, ping me on the discord servur
