### ISSUE TITLE
Antialiased corners look jugged

### ISSUE THREAD

**Issue by amilonop** [hyprwm/Hyprland#1109]
![image](https://user-images.githubusercontent.com/117563443/204090313-84d17434-9b19-483f-97d2-fe8d40777b48.png)
![image](https://user-images.githubusercontent.com/117563443/204090325-4d1b3ec8-a968-4aec-82f5-b455dc53f45b.png)

I don't know if I am missing something regarding antialias, but the corners look a bit jagged to me at all radius. Less noticable on darker borders with shadows on top, but that's just due to the contrast?

**Comment by vaxerski** [comment]
Although this is expected (you don't seem to have a high resolution display) something is off in the corners atm so I'll leave this open for now

**Comment by vaxerski** [comment]
done in 1c9a0be8c40ee47cd438ab33f2bfe4184b19b8a7

any pixelation now is a deficit of pixels.
