### ISSUE TITLE
No border on floating window with no_gaps_when_only

### ISSUE THREAD

**Issue by TilmanAnderson** [hyprwm/Hyprland#1110]
# Steps To Reproduce
- Launch Hyprland with the default config by running `Hyprland` on the TTY.
- Add `no_gaps_when_only = true` into `dwindle {}` inside `~/.config/hypr/hyprland.conf`.
- Open a single window on a workspace.
- Press Super+V to run `togglefloating`
# Expected Outcome
The floating window should have a border.
# Noted Outcome
The floating window doesn't have a border nor does it gain one by opening more windows. This happens in both the dwindle and the master layout.

**Comment by vaxerski** [comment]
fixed in 493fc009533b5d5b94c5d11d32bcd730094e5669
