### ISSUE TITLE
Nix home manager module without config

### ISSUE THREAD

**Issue by addy419** [hyprwm/Hyprland#1112]
So, the nix home manager config is great. This issue doesn't affect the people who use the managed config or already have a config prepared.

Since the config is generated through home manager, you need to rebuild nixos everytime you make a change. For someone who has been using hypr for a long time, this isn't an issue. But someone new needs to make a lot of changes to the config frequently until they achieve what they want. It's just inconvenient to rebuild nixos again and again to make any changes. Making the managed config optional solves this.

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
@addy419 could you apply this patch on the repo and test?
```diff
diff --git a/nix/hm-module.nix b/nix/hm-module.nix
index ac14998..6a0f61c 100644
--- a/nix/hm-module.nix
+++ b/nix/hm-module.nix
@@ -60,7 +60,7 @@ in {
     };
 
     extraConfig = lib.mkOption {
-      type = lib.types.lines;
+      type = lib.types.linesOr lib.types.null;
       default = "";
       description = ''
         Extra configuration lines to add to ~/.config/hypr/hyprland.conf.
@@ -95,7 +95,7 @@ in {
       NIXOS_OZONE_WL = "1";
     };
 
-    xdg.configFile."hypr/hyprland.conf" = {
+    xdg.configFile."hypr/hyprland.conf" = lib.mkIf cfg.extraConfig {
       text =
         (lib.optionalString cfg.systemdIntegration ''
           exec-once=${pkgs.dbus}/bin/dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && systemctl --user start hyprland-session.target
```

**Comment by addy419** [comment]
How do I apply this patch?

**Comment by fufexan** [comment]
@addy419 
1. clone this repo.
2. copy the patch and run `git apply -p1 <<< $(wl-paste)` while in the cloned repo.
3. in your system flake, run `nix flake lock --override-input hyprland <path-to-repo>`, were `<path-to-repo>` is the path to the cloned repo.
4. rebuild and test whether the change actually worked.
5. report back.

**Comment by addy419** [comment]
@fufexan Yes checked, it works. Can this be added to the flake module?

**Comment by fufexan** [comment]
Idk how it worked, it seems like the types ordering was wrong. Should've been `types.nullOr types.lines`. Corrected it, testing and if all is fine I'll push.

**Comment by fufexan** [comment]
Fixed in https://github.com/hyprwm/Hyprland/commit/516949380de1afead478e9a0c7e3e344b5295ee1
