### ISSUE TITLE
rofi does not have borer or any shadow

### ISSUE THREAD

**Issue by Aneeqasif** [hyprwm/Hyprland#1117]
i was using qtile before in X in which rofi does have shadow beneath it but in hyprland i cant have it and the  rofi window seems to get merged with my other windows with same color scheme, is there any way by which i can add border and shadow to rofi (wayland version) in hyprland. 
thanks

**Comment by vaxerski** [comment]
no, cuz it's a layer surface

**Comment by ahmedmahmud** [comment]
Could drop shadows on layer surfaces be reconsidered? Doing it with CSS then obviously messes with `ignorezero` for the layer rules
