### ISSUE TITLE
content from scratchpad windwos is not drag and dropable

### ISSUE THREAD

**Issue by Aneeqasif** [hyprwm/Hyprland#1118]
the scratchpad or special workspace in hyprland doesnot support draging some conent i-e from a dolphin window in special workspace to othher dolphin or thunar window in normal workspace which is very frustrating

**Comment by umop3plsdn** [comment]
wait what? can you move the same content you are reffereing to from one workspace to another in the non special workspaces? can you make a video demonstrating this action? I guess i'm not understanding what you are trying to accomplish.
