### ISSUE TITLE
dragging tabs to split inside pycharm fails

### ISSUE THREAD

**Issue by octdanb** [hyprwm/Hyprland#1120]
Loving hyprland! thank you so much for your efforts, 
I'm starting to use this as a daily driver and am having minimal issues, but just noticed this 

Steps to reproduce:
- Open pycharm
- Open project
- Open two files
- Drag tab to right hand side to split window vertically (within pycharm)

Expected outcome:
- pycharm should split the the files, one left, one right

Noted outcome:
- when dragging the tabs, it automatically drops the tab focus, and it splits horizontally inside pycharm

Happy to provide any logs requested.
Note there is a work around, right clicking on a tab and spiting that way does work, so not a huge issue.

installed versions if this helps:
pycharm-professional 2022.2.1-1
hyprland 0.18.0beta-1
waybar-hyprland-git r2301.d2b4076a-1

Also tried on different monitors at different resolutions, just to make sure it wasn't monitor/resolution

**Comment by romanstingler** [comment]
have you set the windowrule (adjust the name of the class accordingly?
```windowrulev2 = windowdance,class:^(jetbrains-.*) ```

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

**Comment by romanstingler** [comment]
works 
https://youtu.be/b-IdvHynyys

**Comment by CUexter** [comment]
the fix doesnt work because windowdance is gone
what should i do ?

**Comment by sTEm332** [comment]
> the fix doesnt work because windowdance is gone what should i do ?

windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$
windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^(win.*)$

This works for me.
Since windowdance is no longer available, I came up with this solution instead.

**Comment by izmyname** [comment]
> > the fix doesnt work because windowdance is gone what should i do ?
> 
> ```
> windowrulev2=noinitialfocus,xwayland:1
> ```
> 
> This works for me.

windowrulev2 is deprecated and kept only for compatibility reasons.

It's now just` windowrule=`
