### ISSUE TITLE
Spotify not fit in wtm

### ISSUE THREAD

**Issue by Pabxy** [hyprwm/Hyprland#1121]
Hi. I install spotify iin my hyprland linux desktop and is impossible for him to fit with the other windows. It appears as a floating one.

**Comment by DashieTM** [comment]
Problem with spotify, the way it renders it will spawn 2 windows, which breaks tiling on many window managers including hyprland, sway, qtile wayland etc.

What you can do is create a script that will tile the program after a few ms, in other words when the entire hurdurr I spawn window in window bs is over.

**Comment by vaxerski** [comment]
Spotify
