### ISSUE TITLE
Config error <general:damage_tracking>: No such field

### ISSUE THREAD

**Issue by xisberto** [hyprwm/Hyprland#1123]
After upgrade from AUR, I'm getting the message:

`Config error at line 56 (~/.config/hypr/hyprland.conf): Error setting value <full> for field <general:damage_tracking>: No such field.`

The current Hyprland version is 0.18.0beta-1, from aur/hyprland.

**Comment by vaxerski** [comment]
wonder if the patch notes say anything about that
![image](https://user-images.githubusercontent.com/43317083/204289009-90910007-0e9a-4d81-9c68-c824c0241156.png)
