### ISSUE TITLE
Window, monitor, workspace preview (thumbnail)

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#1132]
Good day to you!

some applications can preview windows witihin screensharing menu (telegram, skype, etc.),

is there a way to get an image of window, workspace, monitor?

Thank you!

**Comment by vaxerski** [comment]
KDE - Yes
GNOME - Yes
wlroots - no

I am working on a workaround for Hyprland.

**Comment by vaxerski** [comment]
You can now accomplish windows with the `hyprland_toplevel_export_v1` protocol. See [XDPH](https://github.com/hyprwm/xdg-desktop-portal-hyprland) for an implementation.

Workspace previews are not planned for now. I can see how it would be a "cool" feature to have, I don't see the practical side or urgence.

Monitor previews of course have always been possible through the zwlr_screencopy protocol.

**Comment by fedoranvar** [comment]
@vaxerski 
basic purpose is scipt-picker (e.g. fzf

**Comment by vaxerski** [comment]
no clue about scipt-picker, but yes. Either script-picker or some external program that utilizes the protocol and receives the buffers.

**Comment by ppenguin** [comment]
@fedoranvar are you currently working on a hack that implements this "expose" mode, or know about any efforts?

While I agree with @vaxerski that it wouldn't deserve highest priority, I really like it and use it on a Mac, because I can see which workspace I need to jump to (often can't remember where I opened stuff)

**Comment by fedoranvar** [comment]
@ppenguin 
 right now i'm trying to implement Plasma's feature `Activity/Virtual Desktop`, to learn how to write plugins for Hyprland
 possibly next plugin-project will be this `Overview` plugin, but it'll be not soon

**Comment by ppenguin** [comment]
@fedoranvar I just considered a concept that might make this work scripted (e.g. from bash):
- make screenshots of all workspaces (grim? does it work for not-shown WS?)
- relate `hyprctl dispatch` commands to the screenshots (via ad-hoc scripts in a temp dir?)
- use wofi to show the choices

Just an idea, would fit nicely with "linux philosophy" :wink:

**Comment by talbergs** [comment]
> hyprland_toplevel_export_v1

Exactly my idea, that's how I ended up in this thread. Maybe someone already has this script? Or I'll ask AI to make it for me.

The purpose - I want previews to show on waybar at mouse hover. Screenshot would be taken on every workspace that you switch away from.

It's a still image though...

The "all windows together" view may also be implemented as alternative workspace picker that listens for a keypress in "workspace bindings mode".

On sway there was a way to subscribe to events .. not sure if hyprwm has this.. ?

**Comment by jack9603301** [comment]
> @ppenguin right now i'm trying to implement Plasma's feature `Activity/Virtual Desktop`, to learn how to write plugins for Hyprland possibly next plugin-project will be this `Overview` plugin, but it'll be not soon

Hi, it looks like a cool feature. Have you started working on it?
