### ISSUE TITLE
source tarball top level directory & rename tarball

### ISSUE THREAD

**Issue by wael444** [hyprwm/Hyprland#1133]
currently the source tarball provided from github has the top level tarball containing all the files: `Hyprland-0.18beta/`, this should be considered for convenience when extracing a tarball, since one would expect something along the lines of what github makes.

[source-v0.18.0beta.tar.gz](https://github.com/hyprwm/Hyprland/releases/download/v0.18.0beta/source-v0.18.0beta.tar.gz) has no top level directory, all the files are in the top level directory, without a root directory.

example: 
github tarball:
```
Hyprland-0.18beta/meson.build
Hyprland-0.18beta/src
...
```
source & binary tarball:
```
meson.build
src
...
```

**Comment by wael444** [comment]
additionally, the github tarball is named the exact same as the binary tarball, which can cause issues with package managing.

**Comment by wael444** [comment]
> because tarballs conventionally have everything under a dir which has the name of the project or something

**Comment by vaxerski** [comment]
closing with the new release.
