### ISSUE TITLE
rofi won't be centered

### ISSUE THREAD

**Issue by barbaronbow** [hyprwm/Hyprland#1142]

**Comment by barbaronbow** [comment]
Rofi won't be centered even with window rules

Steps to reproduce:
add windowrule=float,rofi
and windowrule=center,rofi

Expected behavior:
rofi will be centered

Actual behavior:
rofi won't be centered

**Comment by vaxerski** [comment]
Use the rofi wayland fork or wofi. Rofi is made for X11, not wayland.

**Comment by ignamartinoli** [comment]
if I'm not wrong, `rofi` currently uses `xwayland`. Wouldn't that be enough?

**Comment by vaxerski** [comment]
no, xwayland cannot emulate all the weird quirks of xorg onto wayland.

**Comment by ignamartinoli** [comment]
What a pity, thanks!
