### ISSUE TITLE
Allow swipe gestures to move to next numbered workspace

### ISSUE THREAD

**Issue by heymisphere** [hyprwm/Hyprland#1143]
Currently when swipe gestures for workspace switching are turned on, it moves to m+1 workspace or m-1 workspace depending on swipe direction, i.e. it moves to next or previous available workspace. I would rather want to to move to next numbered workspace: example: I have windows spawned on workspaces 1,2,5; when I am on workspace 2, and swipe to go to right workspaces, it goes to workspace 5 because that is the next available workspace, but I would rather want to go to workspace 3, that is +1 instead of m+1. Maybe this could be implemented via a configuration setting like 'workspace_swipe_numbered'

**Comment by vaxerski** [comment]
added in cd08fa22fd1ddbb8604e42d01043617a8eb10520

merry xmas

**Comment by heymisphere** [comment]
This was an amazing gift! Thanks
