### ISSUE TITLE
Firefox resizes independently

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1152]
If  you look at the video carefully, you can see the border for firefox is resizing slower than the actual FF window

https://user-images.githubusercontent.com/208711/205379585-2ac6241a-5a6b-46e6-a7c4-85b87544326c.mp4

**Comment by vaxerski** [comment]
it's cuz firefox

**Comment by primalmotion** [comment]
OK I confirmed it's not happening with other apps

**Comment by Aleksanaa** [comment]
It is said that this issue is on the plan to fix. Could you reopen it to better track the issue? 

> it's cuz firefox. the border is not late, firefox just resizes individually (due to protocol reasons)

**Comment by Aleksanaa** [comment]
Thanks! Anyway, issue https://github.com/hyprwm/Hyprland/issues/152 is actually the same. (I'm mentioning it here just to let participants in that issue know)

**Comment by Aleksanaa** [comment]
This does not happen to firefox under xwayland (`MOZ_ENABLE_WAYLAND=0`).

**Comment by Aleksanaa** [comment]
Fun fact: Chromium has the same issue with hardware acceleration. However when hardware acceleration is disabled, chromium behaves correctly.

**Comment by romanstingler** [comment]
with disabled animations this doesn't happen at all

**Comment by vaxerski** [comment]
fixed in 382af06406e39640dac36e4e075c2c70063cb16c

**Comment by primalmotion** [comment]
indeed it is. thanks!

**Comment by Aleksanaa** [comment]
Not working for me, firefox behaves the same way as it used to be...
