### ISSUE TITLE
Error while running Hyprland

### ISSUE THREAD

**Issue by joao-saraiva** [hyprwm/Hyprland#1154]
It is my first time using arch and i tryed Hyprland, but i stucked in this error, I tried to run this command 
make legacyrenderer 
but we wont do

Hyperland.log 

[LOG] Release: 6.0.10-arch2-1
[LOG] Version: #1 SMP PREEMPT DYNAMIC Sat, 26 Nou 2022 16:51:18 +0000
[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: VMware SVGA II Adapter [15ad: 0405] (prog-if 00 [VGA contre Iler])
Subsysten: UMware SUGA II Adapter [15ad:0105]
[LOG) os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38:2:23:147:209" HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/" SUPPORT_URL="https://bbs.archlinux.org/" BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY POLICY_URL="https://terns.archlinux.org/docs/privacy-policy/"
LOGO archlinux-logo
[LOG] ==
[INFO] If you are crashing, or encounter any bugs, please consult https://github.com/hyprum/Hypr Land /wiki/Crashing-and-bugs
[LOG]
Current splash: Now you're just somebody that I used to know...
[CRITICAL] _SWLRRenderer was NULL!

COREDUMPCTL

PID: 395 (Hypr land) UID: 1000 (kimi)
GID: 1000 (kimi)
Signal: 6 (ABRT)
Timestamp: Fri 2022-12-02 19:16:11 -03 (11min ago) Command Line: Hyprland
Executable: /usr/local/bin/Hyprland
Control Group: /user.slice/user-1000.slice/session-1.scope Unit: session-1.scope
Slice: user-1000.slice
Session: 1
Owner UID: 1000 (kimi)
Boot ID: b07f6de532ae4969807fab47e619cad9 Machine ID: 1c63ec77aa8918c89b726188cc5d669c
Hostname: joao-saraiva
Storage: /var/lib/systemd/coredump/core.Huprland. 1000. b07f6de532ae4969807fab47e619cad9.395.1) Size on Disk: 1.1M
Message: Process 395 (Hyprland) of user 1000 dumped core.
Stack trace of thread 395:
#1
#0 0x00007f61dcca164c n/a (libc.so.6 0x0064c) 0x00007f61dcc51958 raise (libc.so.6+0x38958) #2 0x00007f61dcc3b53d abort (libc.so.6+0x2253d)
#3 0x00007f61dce99833 ZN9_gnu_cxx27 verbose_terninate_handlerEu (libstdc++.so.6) #4 0x00007f61dcea5cfc terninateEPFUUE (libstdc++.so.6 0xa5cfc)
#5 0x00007f61dcea5d69
#6 0x00007f61dcea5fcd
#7
2N10_cxxabiu111
28t9terminateu (libstdc++.so.6 0xa5d69)
_cxa_throu (libstdc++.so.6+0xa5fcd)
0x000055baea3c2bd4 2M110CompositorCZEU.cold (Hyprland 0x14bd4)
#8 0x000055baea3dfalb main (Hyprland 0x31a1b)
#9 0x00007f61dcc3c290 n/a (libc.so.6+0x23290)
#10 0x00007f61dcc3c34a libc_start_nain (libc.so.6 0x2334a)
#11 0x000055baca3e78f5 start (Hyprland 0x398f5)
ELF object binary architecture: AMD x86-64
Lines 1-33/33 (END)

My Config

Archlinux
CPU: Ryzen 5 5600x
GPU: RX RADEON 5600XT
RAM: 16GB

**Comment by vaxerski** [comment]
> VMware SVGA II Adapter

![image](https://user-images.githubusercontent.com/43317083/205404665-bb786a42-143d-4718-9a54-e79e672684af.png)
