### ISSUE TITLE
Unsetting `screen_shader` results in garbled image

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [hyprwm/Hyprland#1161]
As I've said in https://github.com/hyprwm/Hyprland/issues/1140#issuecomment-1334029812 (see comment for log, but I can't see anything relevant there).

> One thing I noticed is that if I:
>
> 1. ...set the shader
> 2. reload config (it'll apply as expected)
> 3. then comment out the `screen_shader` variable to unset it
> 4. and again reload config
> ...the screen will be compressed to a small line at the bottom of the monitor, the rest will be black.
>
> (Just reloading to replace the shader works fine).

<details>
  <summary>Pic</summary>

![demo](https://user-images.githubusercontent.com/14999778/205435804-1f4e763d-b25d-471d-8ce6-6de193be9c5d.jpg)

</details>

**(You can restore the screen by undoing the config change and reloading it)**

Particular shader used doesn't matter, e.g. effectively no-op shader causes the similar behavior:

```glsl
// no-op
precision mediump float;
varying vec2 v_texcoord;
uniform sampler2D tex;

void main() {
    vec4 pixColor = texture2D(tex, v_texcoord);
    gl_FragColor = pixColor;
}

```

Also, `hyprctl keyword decoration:screen_shader ~/.config/hypr/some_shader.frag` doesn't actually apply shader (visually) but

```
hyprctl getoption decoration:screen_shader
```

will show the new path.

Reload won't help, because the shader that was originally set in `screen_shader` in config will be loaded.

#### System
* Arch linux latest, 6.0.10 kernel
* Nvidia 525.60.11 (instructions from the wiki [applied](https://wiki.hyprland.org/Nvidia/#fixing-random-flickering-method-1))
* Hyprland https://github.com/hyprwm/Hyprland/commit/cb85eea261d7ee9994bcf8d3152b119e730270b9

**Comment by vaxerski** [comment]
056a45d035781a74ae80d5a5f0247f3338dca05d fbc839e8d9a6a55b25e68854a6ee9d7769353088

**Comment by MahouShoujoMivutilde** [comment]
Thanks!
