### ISSUE TITLE
Separated keyboard layout per window

### ISSUE THREAD

**Issue by and-win** [hyprwm/Hyprland#1162]
Hello,

Thank you for awesome work!
Is there a way to configure switch keyboard layout (language ) per each window, like it works in KDE or Gnome?

**Comment by vaxerski** [comment]
what?

**Comment by MahouShoujoMivutilde** [comment]
He probably means per window keyboard layout (language, that is).

**Comment by and-win** [comment]
> He probably means per window keyboard layout (language, that is).
> 
> Sway has https://github.com/artemsen/swaykbdd
@MahouShoujoMivutilde Exactly, thank you.

**Comment by MahouShoujoMivutilde** [comment]
How would one script it though, considering that we don't have sway's 
```
swaymsg input type:keyboard xkb_switch_layout <next|prev|index>
```
and 
```
hyprctl keyword device:*DEVICE*:kb_layout *layout_you_want*
``` 
is 40ms which is quite slow? (much slower than `xkb_switch_layout`)

**Comment by vaxerski** [comment]
ask me to add xkb_switch_layout and I will

**Comment by MahouShoujoMivutilde** [comment]
...Pretty please?
<img src="https://user-images.githubusercontent.com/14999778/205447556-79415388-afad-4e8e-b635-3d21ee0d8084.png" width=300px>

**Comment by MahouShoujoMivutilde** [comment]
> there isn't. You can script it though, just like with the sway thing above.

To @and-win and to the people from the search - here is my take on this.

https://github.com/MahouShoujoMivutilde/hyprland-per-window-layout/
