### ISSUE TITLE
Use Sanitizers and Fuzzers

### ISSUE THREAD

**Issue by e-dant** [hyprwm/Hyprland#1168]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

(I've read them)

If you want help setting up sanitizers, I can draft some GitHub CI rules for you. 

Fuzzing is something I'm less familiar with, but happy to explore. 

From what I've seen, there's no use of either.

**Comment by vaxerski** [comment]
we do security scanning:
![image](https://user-images.githubusercontent.com/43317083/205467678-3abc9027-675d-4f8d-95f9-6209eccacab8.png)

But I do not see the point in using a fuzzer for a compositor. Why?

**Comment by e-dant** [comment]
Flawfinder just looks for common security vulnerabilities. Github code scanning works similarly.

That's very different from sanitizing the code. At the very least, I think running the unit tests under valgrind would be helpful.

Fuzzing can help see which edge-cases some of your functions are going to break on. It's project-agnostic.

**Comment by vaxerski** [comment]
Valgrind doesn't run hl 90% of the time, due to... stuff.

Furthermore, running hl on some random single-core VM with Software Rendering sounds like a lot of pain.

**Comment by e-dant** [comment]
Unit tests, run under sanitizers, might do the trick. 

You might be the only person to know which pieces of the code are important to test.

**Comment by vaxerski** [comment]
it would be very time-consuming to write good tests for something like hyprland for not a lot of benefit. No other wl compositor does that.
