### ISSUE TITLE
Master layout unwanted gap between master and client on vertical bar

### ISSUE THREAD

**Issue by rezaamashi** [hyprwm/Hyprland#1171]
### Steps to Reproduce
1. Enable master layout by running `hyprctl keyword general:layout master`, or enabling it in `hyprland.conf`:
```
general {
   layout=master
}
```
2. Set up and enable vertical bar with "exclusive" zone from compositor option ON. In my case, I tried eww and waybar with both resulting the same bug.
3. The vertical bar could be on either left or right side of the screen

4. Open master and stacks clients
5. Observe the gap between master and stacks

### Expected Outcome
1. No gap increase between master and stacks
2. The client not pushed far to the right

### Noted Outcome
1. Extra gap space between master and stacks  (probably Hyprland regard it as an exclusive zone)
2. Stack pushed far to the right
    - When the bar is on the right, the client window is pushed to the bar area
    - When the bar is on the left, the client window is pushed off the screen

Consult the attached video below:

https://user-images.githubusercontent.com/20262272/205470176-2d7ff404-ecd3-49f0-9e4d-ddf6fa484283.mp4

**Comment by proycon** [comment]
You might want to check if this persists after #1202 is merged, I think I spotted and fixed this issue (though I didn't explicitly test it with a vertical bar yet).

**Comment by rezaamashi** [comment]
Hi, Thanks for the fix and the new feature. 
I am using AUR build `hyprland-git`. I added `orientation` setting to my `hyprland.conf` and `orientationprev`-`orientationnext` dispatcher to my keybindings. The issue is fixed for master orientation of `left`, `up`, and `down`. But persists on master orientation `right`. The attached video below showing when the vertical bar is on the right, I also test with the vertical bar on the left and the issue still persists.

https://user-images.githubusercontent.com/20262272/206946748-52c57c15-1866-4f4b-888a-fdce0462c38c.mp4
