### ISSUE TITLE
Crashes at launch on tty

### ISSUE THREAD

**Issue by sql5952** [hyprwm/Hyprland#1172]
Archlinux Linux-zen 6.011 
AMD Vega8
I build Hyprland through cmake successful,but it could not run on my PC

![IMG_2022-12-04-18-21-42-804](https://user-images.githubusercontent.com/58073263/205485470-22c7deba-4a73-4e49-b8bb-c149f4b237de.jpg)

**Comment by vaxerski** [comment]
throw in constructor of compositor, most likely null renderer, launch with `HYPRLAND_LOG_WLR=1` and consult the logs. 

Also try legacy renderer. All is in the wiki.

This is not a problem with Hyprland, but your system preventing hyprland to start a renderer.

**Comment by sql5952** [comment]
Thanks ,I had wrong version with llvm-libs and vulkan-radeon
