### ISSUE TITLE
windows don't respond to input after using tessen

### ISSUE THREAD

**Issue by ribosomerocker** [hyprwm/Hyprland#1173]
I use [tessen](https://sr.ht/~ayushnix/tessen/) to input my password. When I select a password, and I'm prompted to input my master password, I can choose to either autotype, or copy. When I choose to autotype, which uses the [`wtype` ](https://github.com/atx/wtype) utility, after it finishes autotyping, the window isn't responsive to any mouse or keyboard input... but the window does respond to mouse hovers. After switching workspaces though, the window responds to mouse and keyboard inputs. In something like River, I can use the window nomally after choosing the autotype option.

**Comment by umop3plsdn** [comment]
have you looked into alternatives? I use bwmenu with rofi-pass and ydotool and it autotypes all my bitwarden passwords through a rofi menu can even choose if i want to ouput username password or both

**Comment by MonAaraj** [comment]
This works fine in River, but is a bug in Hyprland. I'd like it more if the bug was fixed in Hyprland, rather than change my workflow to fit the limitations of Hyprland.

**Comment by ribosomerocker** [comment]
I've just updated and it seems to be fixed.
