### ISSUE TITLE
[Feature] Focus only changed when pressing somekey like `$mainMod`

### ISSUE THREAD

**Issue by Zaplae** [hyprwm/Hyprland#1176]
I want to change my focus only when pressing super to switch windows:

The focus will follow my cursor when pressing super, otherwise, it will not follow my cursor

**Comment by MightyPlaza** [comment]
isn't ```follow_mouse``` enough?
if not you can change it from 0 to 1 with hyprctl to change the behaviour using a bind

**Comment by vaxerski** [comment]
configurable
