### ISSUE TITLE
Group border remains on screen with wokspaces fade animation

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#1182]
Steps to reproduce:
1. Set this animation: `animation=workspaces,1,9,default,fade`
2. Set a border for groups.
3. Create a group.
4. Swap to an empty workspace.

You can see that the group border remains ~1 second on screen.

Thank you so much for your attention. Bless.

**Comment by vaxerski** [comment]
fixed in 7ed401e5e0779e851667c2e5d220c24e9a5b8737

**Comment by Aqa-Ib** [comment]
Amazing, it is working fine. Thank you very much.
