### ISSUE TITLE
Deform effects for moving grabbed windows

### ISSUE THREAD

**Issue by jleonardfl** [hyprwm/Hyprland#1184]
Searched the issue tracker and didn't find a duplicate for this.  

Something with the functionality of the [compiz wobbly windows extension for gnome](https://extensions.gnome.org/extension/3210/compiz-windows-effect/) ([demo video](https://www.youtube.com/watch?v=G8bAVIB9A7A)) that makes the windows wobble as you move them around.  Specifically for hyprland, when you move a window with SUPER+mouse or whatever movewindow is bound to in the config.

**Comment by i-pwl** [comment]
also interested in this!

**Comment by vaxerski** [comment]
wobbly windows can be made into a plugin easily now. IIRC @TheSunCat said they'll try some time soon
