### ISSUE TITLE
Found 0 GPUs, cannot create backend

### ISSUE THREAD

**Issue by Badless** [hyprwm/Hyprland#1185]
I got this error:
[backend/backend.c:217] Found 0 GPUs, cannot create backend
[backend/backend.c:386] Failed to open any DRM device
m_sWLRBackend was NULL!
m_sWLRBacked NULL!

I'm using NixOS with Nvidia driver installed

**Comment by vaxerski** [comment]
nvidia issue, read the nvidia page, if nothing works, you're out of luck

**Comment by Badless** [comment]
> nvidia issue, read the nvidia page, if nothing works, you're out of luck

what if i remove nvidia driver and will be using nouveau?

**Comment by vaxerski** [comment]
generally a bad idea due to the performance hit. The best idea would be to buy an AMD card.
