### ISSUE TITLE
Unable to launch Hyprland on Fedora 37 : X11 does not support DRI3 extension

### ISSUE THREAD

**Issue by Nephty** [hyprwm/Hyprland#1188]
I installed Hyprland following [this](https://github.com/hyprwm/Hyprland/discussions/284) guide, though I experienced a common issue : 
> ERROR: Neither a subproject directory nor a wayland.wrap file was found.

This was fixed by following [these](https://github.com/hyprwm/Hyprland/discussions/284#discussioncomment-4167454) steps (basically installing a version from an older commit because the most recent one requires a package that was not yet available on the most recent version of fedora (yes, fedora users are real)).
After that, I tried to run hyprland by typing
> Hyprland

in my terminal, but encountered this error : 
> 00:00:00.014 [backend/x11/backend.c:395] Creating X11 backend
00:00:00.015 [backend/x11/backend.c:462] X11 does not support DRI3 extension

Log output : 
> [LOG] Instance Signature: be6f5ce8312646c5b527020da2e576e34d325013_1670318626
[LOG] Hyprland PID: 193621
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: fedora
[LOG] Release: 6.0.7-301.fc37.x86_64
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Fri Nov 4 18:35:48 UTC 2022
[LOG] GPU information:
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev ca) (prog-if 00 [VGA controller])
[LOG] os-release:
NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
VARIANT="Workstation Edition"
VARIANT_ID=workstation
[LOG] ========================
[INFO] If you are crashing, or encounter any bugs, please consult https://github.com/hyprwm/Hyprland/wiki/Crashing-and-bugs
[LOG] 
Current splash: Is this the real life, is this just fantasy
[CRITICAL] Couldn't query the DRM FD!

[Here](https://pastebin.com/1CemUhy4) is the Hyprland coredump.

I've read every issue (open & closed) that matched the search "DRI3 extension" but none were what I was looking for.

Let me know if I should provide more details about the bug or my system.

Thanks in advance !

**Comment by vaxerski** [comment]
the error you gave with meson says nothing. You shaved off the important part and left the useless in.

X11 backend issue: Why are you launching hyprland on an X session? This is not an xorg compositor.
