### ISSUE TITLE
Weird bug after using special workspace

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/Hyprland#1189]
I'm using the latest git master of Hyprland on Arch Linux with a dual screen setup.
If I open a foot terminal ( latest git ) which opens using a rule on workspace 2 and then send it to the special workspace.
Then I move to workspace 1 and open Qutebrowser it does not open on workspace 1 but opens up in the special workspace alongside the foot terminal which was sent there.
I also notice if i then move Qutebrowser back to workspace 1 then my foot terminal disapears and i can no longer open terminals. But if before closing the special workspace i also move foot back to workspace 2 it vanishes but i can make it come back by moving to say workspace 3 then back to 2 and it reapears.
If i do not use the special work spaces and open foot on 2 and Qutebrowser on 1 then everything is fine.
Not sure what's going on there and hope someone else can reproduce it too ?

**Comment by vaxerski** [comment]
https://user-images.githubusercontent.com/43317083/206008408-4fe47041-c52d-410d-a454-8b6df06b2d19.mp4

**Comment by vaxerski** [comment]
I couldnt repro it, but check with 993c382e74faddefeb62b3ab7a7281bd9a69990b

**Comment by justinesmithies** [comment]
Sorry it's still the same.
It only happens if I open foot then send it to special then move to ws 1 and try and open say Qutebrowser. For some reason Hyprland opens Qutebrowser in the special ws ?? This doesn't happen if I don't send foot to the special workspace first.

**Comment by vaxerski** [comment]
attach your config, cant repro

**Comment by vaxerski** [comment]
that should not change anything

**Comment by justinesmithies** [comment]
Well i can no longer reproduce the bug having removed that comma ????

**Comment by vaxerski** [comment]
send your config over. I have that comma and cant repro either.

**Comment by justinesmithies** [comment]
Go easy on me though ;)

[hyprland.conf](https://paste.sr.ht/~justinesmithies/2b62b935ea2fe752fd0eb817ba49fcbf68cf84fa)
