### ISSUE TITLE
Can't compile hyprland with clang

### ISSUE THREAD

**Issue by Arisa-Snowbell** [hyprwm/Hyprland#1192]
CMakeFiles/Hyprland.dir/src/Compositor.cpp.o
error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
    Debug::log(LOG, "Running on WAYLAND_DISPLAY: %s", m_szWLDisplaySocket);

**Comment by vaxerski** [comment]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0980r0.pdf

has been impl'd in Clang 15. You're probably using outdated clang.

**Comment by vaxerski** [comment]
ah fuck wait, misread this

**Comment by vaxerski** [comment]
fixed in 6259202c0182fe3e7e36ab5b3010db567738375a

**Comment by Arisa-Snowbell** [comment]
thank you for the fix
