### ISSUE TITLE
swipe between workspaces is broken

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1196]
Since the last updates, workspace change using swipe gesture is broken. It skips some workspaces (seems random). when I manually goes to one of the skipped workspaces, it's stuck (swiping does nothing)

Here's my relevant config (I can't codeblock, f'ing github broke too...)

gestures {
	workspace_swipe = true
	workspace_swipe_invert = true
	workspace_swipe_fingers = 4
 	workspace_swipe_distance = 1300
	workspace_swipe_cancel_ratio = 0.5
	workspace_swipe_min_speed_to_force = 20
	workspace_swipe_create_new = false
}

**Comment by vaxerski** [comment]
fixed in 726732244a5d51a0da54219174c13f4428017b79

**Comment by primalmotion** [comment]
confirmed. thanks!
