### ISSUE TITLE
Boundary test for Hyprland special workspace failed - function exception occurred

### ISSUE THREAD

**Issue by jack9603301** [hyprwm/Hyprland#1197]
# Symptoms

Please watch the following video:

see: 
[2022-12-09 22-53-24.tar.gz](https://github.com/hyprwm/Hyprland/files/10196074/2022-12-09.22-53-24.tar.gz)

Let's see what happened?

1. After I created 3 konsole terminal emulators in workspace 1, I saved one of them to a special workspace through a shortcut key, and after repeated switching operations, we were surprised to find that the switch had the problem of the following screenshot :

![图片](https://user-images.githubusercontent.com/9047180/206738689-9e799d1a-40f0-4704-98b3-0b15d06981fe.png)

Yes, I believe it is a very high probability issue - although I don't know what is wrong, if I can solve it, I would like to help the community fix it, but I have no idea at the moment.

There is a strange phenomenon in this screenshot, where part of the special workspace appears in front of the user (the surface layer of another konsole instance) and the other part is obscured by another konsole instance.

2. At the same time, there is another question, please see:

![图片](https://user-images.githubusercontent.com/9047180/206739402-61bb0746-6e39-4ec2-b5e1-322047785b2b.png)

Let me explain what happens: when I move a window of some interface to the anonymous special workspace, and then at the same time move another konsole window to the named special workspace, using the shortcut key to call out the anonymous special workspace, use the command Enter the named special workspace, and try to switch out after switching (forgive me, I can’t tell here), and you will find that after the window is closed, the workspace cannot be switched to the previous workspace normally, and I have to go through another Workspace to switch.

# reproduce

I have expressed the repro method in Symptoms

# expected outcome

Similarly, I believe that every member of the community (user/contributor/maintainer) should understand that although I call it boundary testing, in fact these may be frequently used functions for some users, they Should work fine instead of producing the situation in the video. I have reason to think this is an undiscovered bug

**Comment by vaxerski** [comment]
check with fd43d2bea7e8d6e0915c7c2838554cde5356f54f

**Comment by jack9603301** [comment]
@vaxerski The first problem seems to be solved, but when the user tries to call out the special workspace, and in this case move the window of the normal workspace behind, the special workspace seems to go behind the window of the normal workspace - Although this may not be a particularly urgent issue.

Also, I found another problem: when we create multiple special workspaces, it always seems to place the windows in the same workspace, and when we try to call out to any of the special workspaces, what is displayed to the user is always A unified, multi-window workspace - where all windows are stored. Even if the user wants it to be placed in a different special workspace

**Comment by vaxerski** [comment]
you need to specify the special workspace to move to in movewindowtoworkspace

**Comment by jack9603301** [comment]
@vaxerski  see [2022-12-11 19-27-25.tar.gz](https://github.com/hyprwm/Hyprland/files/10202640/2022-12-11.19-27-25.tar.gz)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/206917060-a0ec48d6-520f-45c8-88a8-e76d629892db.png)

in togglespecialworkspace, you should use only the name, without `special:`.

the other bug I can see, fixed in f97289a3c0c9c5f694d841195b223f581d183d15

**Comment by jack9603301** [comment]
The problem has been solved, thank you
