### ISSUE TITLE
[Feature] notification event for client floating state change

### ISSUE THREAD

**Issue by LBCrion** [hyprwm/Hyprland#1199]
Would it be possible to add an event notification on socket2.sock when a client changes floating state? This would facilitate floating state tracking and taskbar filtering for floating windows (see LBCrion/sfwbar#67)

**Comment by vaxerski** [comment]
added in bf78dcecf092fc10df75ce869306ddabf8ecd640

**Comment by LBCrion** [comment]
Legend
