### ISSUE TITLE
Swap workspaces when they move on the fly

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#1200]
So I have managed to somewhat mimic XMonad's behaviour with dual monitors by assigning
bind = $mainMod, 1, moveworkspacetomonitor, 1 current
bind = $mainMod, 1, workspace, 1

On XMonad if I do mod1 on monitor1, then if the workspace 1 is not present in any of the screens, it will go to workspace 1, but if workspace 1 was on the 2nd monitor, then it would move workspace 1 to current monitor (monitor1) 
but the part that it is missing on hyprland is that when workspace 1 would move to 1st monitor, the workspace I was on in monitor1 would go to monitor2, but the way it is now the behaviour is somewhat random. 

There is the dispatcher swapactiveworkspaces, but that doesn't really suit the functionality I'm looking for. It's like an if statement, if workspace called is on another monitor, then swapactiveworkspaces would be called. That could probably be done with https://wiki.hyprland.org/Configuring/Expanding-functionality, but i'm too dumb for that.

Is it feasible to add something like this?

**Comment by vaxerski** [comment]
it's already been scripted somewhere, iirc beard has made a script for that.

If I am not mistaken, it's [this](https://github.com/taylor85345/hyprland-dotfiles/blob/master/hypr/scripts/workspace)

**Comment by jabuxas** [comment]
that workspace script is deprecated and doesn't work properly anymore, had to fix it :)

**Comment by ItsDrike** [comment]
I have a script for this in my dotfiles if you want: https://github.com/ItsDrike/dotfiles/blob/wayland/home/.local/bin/scripts/gui/hyprland/swap-workspace

**Comment by jabuxas** [comment]
@ItsDrike ty, that works flawlessly, i had problems with the other script. i might change to hyprland now

**Comment by jabuxas** [comment]
@ItsDrike actually, after some time playing with it, sometimes when I switch to another workspace, it moves to the workspace I want + changes the workspace on the other monitor to another random one, also moves my mouse to the passive monitor. I can't really find a reason for it yet, but that's the main problem with the one I was using and now yours, maybe it's a bug on hyprctl

**Comment by ItsDrike** [comment]
> @ItsDrike actually, after some time playing with it, sometimes when I switch to another workspace, it moves to the workspace I want + changes the workspace on the other monitor to another random one, also moves my mouse to the passive monitor. I can't really find a reason for it yet, but that's the main problem with the one I was using and now yours, maybe it's a bug on hyprctl

No idea why that is, I'm not using my 2 monitor setup as much nowadays, so I don't really do that much active testing, but if you do find some reason for why this is happening, please do make a PR or at least an issue about it on my dotfiles repo.

**Comment by jceb** [comment]
> I have a script for this in my dotfiles if you want: https://github.com/ItsDrike/dotfiles/blob/wayland/home/.local/bin/scripts/gui/hyprland/swap-workspace

Here's the updated link to the script: https://raw.githubusercontent.com/ItsDrike/dotfiles/main/home/.local/bin/scripts/gui/hyprland/swap-workspace

**Comment by jceb** [comment]
It would be great to have this feature built-in since the script causes a bunch of flickering (at least on my computer).
