### ISSUE TITLE
Follow mouse

### ISSUE THREAD

**Issue by mshzsh** [hyprwm/Hyprland#1201]
After recent updates, I noticed that when the mouse moves out of the window, the window loses focus, while I set `follow_mouse=0`

**Comment by vaxerski** [comment]
do a `git bisect` then please and find the faulty commit

**Comment by mshzsh** [comment]
This commit caused this problem :
[ff12a41](https://github.com/hyprwm/Hyprland/commit/ff12a41c40b8529330c06f37120787cf40bde980)

**Comment by vaxerski** [comment]
should be fixed with c3f1dc3f526a7f94c37d72f8314bc4bce969f0d8

**Comment by mshzsh** [comment]
Done!
