### ISSUE TITLE
Firefox failed to find gpus

### ISSUE THREAD

**Issue by Icelk** [hyprwm/Hyprland#1205]
When starting Firefox with the proprietary Nvidia graphics stack, the following message is printed:
```
[GFX1-]: No GPUs detected via PCI
[GFX1-]: glxtest: process failed (received signal 11)
```
and Firefox can't use hardware-accelerated video decode, webgl, or WebRender.

I tested this inside `kwin_wayland` as a nested composter, and then all is fine.

This seems to be linked to the detection of GPUs in wlroots. I'm using arch, but it also seems to be happening on other distros. Works as expected on my Intel laptop (also running Hyprland, of course)
Below are some links to other threads where this is discussed:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1759315
- https://bugzilla.mozilla.org/show_bug.cgi?id=1765042
- https://bbs.archlinux.org/viewtopic.php?id=277322&p=2
- https://github.com/NixOS/nixpkgs/issues/202454
- https://www.reddit.com/r/NixOS/comments/yz462t/nvidia_wayland_firefox_gfx1_no_gpus_detected_via/

**Comment by vaxerski** [comment]
I missed the part where that is my problem, this seems like an issue with ff and wlr?

**Comment by Icelk** [comment]
That's true. I'll go over to wlr and report the issue there.
What's your experience with ff hardware acceleration on Hyprland?

**Comment by vaxerski** [comment]
I use firefox and have not noticed any issue, but I did not explicitly test anything.

It just works, smoothly.

Worth noting, AMD GPU.

**Comment by Icelk** [comment]
wlr issue for posterity: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3549

**Comment by scorpion-26** [comment]
@Icelk FYI: I submitted a patch to firefox(See [here](https://phabricator.services.mozilla.com/D164578)), which should fix the issue. Until it is merged in for us poor nvidia users, you can compile firefox from source manually.

**Comment by Icelk** [comment]
@scorpion-26 Excellent! Thank you. I will be keeping close tabs on the patch

**Comment by kki0t** [comment]
NVIDIA/egl-wayland#74 is the fix to all this mayhem.
Firefox (and `glxtest`) isn't the main culprit.

Unfortunately, the latest release doesn't feature this PR.
I asked them for a new release.
Until then, I'm trying to get a driver installer to compile from the source instead of the old "1.1.11".

**Comment by Milor123** [comment]
How can solve it in my case? I have X11, Cinnamon desktop, and Firefox 118.0.0.1-1
GPU is AMD RX 6700 XT, in the Flatpak version all works nice, but i need use the non-flatpak version. Wha should i do? 
i've tested the anothers firefox, like librewolf, or mercury and nothing work without flapak

```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: ManageChildProcess failed
 (t=1.29365) [GFX1-]: glxtest: ManageChildProcess failed

Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: ManageChildProcess failed
 (t=1.29365) |[1][GFX1-]: No GPUs detected via PCI
 (t=1.29371) [GFX1-]: No GPUs detected via PCI
```

I am in ubuntu 22.04 LTS
