### ISSUE TITLE
cyclenext/swapnext window ordering doesn't match layout

### ISSUE THREAD

**Issue by XeroOl** [hyprwm/Hyprland#1206]
I normally prefer managing my windows with `cyclenext`+`swapnext`. However, `cyclenext` is counterintuitive and hard to predict. I would expect `cyclenext` to go the the next window in the layout, but it seems to be based on the order windows are opened instead.

This bug is one that doesn't crash Hyprland, but feels like invalid behavior.

### Steps to reproduce
1) Make sure that `cyclenext`/`swapnext` are bound to something.
2) Make sure you are using the master layout.
2) Spawn a couple windows and swap them around.
One reproducible way is to spawn four windows and then issue `swapnext` twice, but any swap that reorders the windows works.

### Expected outcome
Using `cyclenext` in master layout shifts focus in order from the top of the stack to the bottom, and then back to the main window.

### Noted outcome
Using `cyclenext` shifts focus in order from the least recently created window to the most recently created window. `swapnext` cannot actually reorder the windows, just their positions on screen.

**Comment by XeroOl** [comment]
I have read the wiki, and apparently the master layout has its own dedicated cyclenext/cycleprev/swapnext/swapprev dispatchers.

I guess I should have read the wiki more carefully, but I am very confused as to why layout-aware swapping isn't available in a layout agnostic way.

**Comment by vaxerski** [comment]
> layout-aware swapping isn't available in a layout agnostic way

precisely because of that

**Comment by XeroOl** [comment]
This does mean that floating windows are not fun to use, because they apparently don't seem to ever get cycled to
