### ISSUE TITLE
Inconsistent cursor theme on xwayland applications

### ISSUE THREAD

**Issue by 0bCdian** [hyprwm/Hyprland#1209]
I couldn't find any relevant information on the wiki on how to solve this issue so I'm here as a last resort, xwayland apps are defaulting to adwaita cursor theme, this behavior wasn't happening before, I have the xcursor env set up properly and hyprctl set cursor theme in the autostart file, as well as in the default file in .icons folder, the gtk3 and 4 settings.ini files. This behavior on gnome wayland isn't present so I guess it has to do more with hyprland and less with wayland in general.

[here's an example](https://im.ezgif.com/tmp/ezgif-1-b8779f15b5.gif)

**Comment by vaxerski** [comment]
hyprland does not handle the cursor theme on apps. Safe to say you have misconfigured something. gnome probably fixes something for you.

**Comment by vaxerski** [comment]
hm, also happened to my laptop after I did a pretty big pacman -Syu. You found what it was yet? Doesn't happen on my desktop. Odd.

**Comment by 0bCdian** [comment]
> hm, also happened to my laptop after I did a pretty big pacman -Syu. You found what it was yet? Doesn't happen on my desktop. Odd.

I just solved it yesterday, basically I forgot that when I clean install Hyprland the hyperland.desktop file gets rewritten and it wasn't running my wrapper script with the corresponding envars, I updated the hyperland.desktop file to run my script again and everything is working nice and dandy. Thanks for creating this excelent wm!

**Comment by vaxerski** [comment]
odd, as I don't use the aur pkg.

**Comment by 0bCdian** [comment]
> odd, as I don't use the aur pkg.

I always update via aur, but last update was the first to cause me this issue, it's a minor one that's why I was kind of ashamed asking, I hope my comment was somewhat helpful!

**Comment by vaxerski** [comment]
No clue how, I somehow fixed it by just redoing all the cursor stuff and recompiling hyprpaper. It still happens on the very edges of an xwayland window, but I guess thats an xwayland bug...?

**Comment by 0bCdian** [comment]
> No clue how, I somehow fixed it by just redoing all the cursor stuff and recompiling hyprpaper. It still happens on the very edges of an xwayland window, but I guess thats an xwayland bug...?

I'll try to replicate the issue and report back as soon as I can
