### ISSUE TITLE
Mapping a Tablet to an Output

### ISSUE THREAD

**Issue by vale981** [hyprwm/Hyprland#1210]
Hi, 

First, thank you for all the work that's been put into Hyprland :). It is a real game-changer for me.

Is there a feature to map a graphics tablet to an output already?
If not, I might try my luck unless someone knows how to do it quickly. I would orient myself along the work done for touchscreens.

**Comment by vaxerski** [comment]
tablets are not configured at all through Hyprland, use something like OTD.

https://wiki.hyprland.org/FAQ/#my-tablet-no-worky

**Comment by vale981** [comment]
Thanks a lot. RTFM moment for me, but i searched for this :P

**Comment by jsenecal** [comment]
Sorry to bring this back... But wouldn't it be nice if Hyprland would support what sway does simply with:
```
input "1267:8919:ELAN_Touchscreen" {
    map_to_output eDP-1
}
```

**Comment by vaxerski** [comment]
a touchscreen can be bound to an output with per-device input configs. https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs

touchscreens are not tablets
