### ISSUE TITLE
Mouse cursor doesn't change back if window closes mid-move

### ISSUE THREAD

**Issue by eriedaberrie** [hyprwm/Hyprland#1214]
### Steps to reproduce:
Have a terminal window open with `sleep 3 ; exit`.
With something like `bindm=$mainMod,mouse:272,movewindow` in your `hyprland.conf`, start moving the window, and let it close on you while still holding down the mouse button.
### Expected behavior:
The mouse cursor should return to normal.
### Actual behavior:
The mouse cursor gets permanently stuck on the "pointer" version, and I have to relaunch Hyprland to get it back to normal.
edit: nevermind, it goes back to normal as soon if I try to move another window, but either way it gets stuck until I do

**Comment by vaxerski** [comment]
you mean the "grab" version

**Comment by eriedaberrie** [comment]
Well, it's the same as the one I get when I hover over a link or clickable button, and it's the same between both move and resize windows. I did always find that kind of strange, is it supposed be the grab and resize images?

**Comment by vaxerski** [comment]
it's supposed to be grab, and if that's the same as "point" then you have a weird cursor theme.

**Comment by vaxerski** [comment]
fixed in 0c1bec023fa13df651c39c5febcecb35b5ff277a
