### ISSUE TITLE
separate no_gaps_when_only and no_border_when_only

### ISSUE THREAD

**Issue by notoyz** [hyprwm/Hyprland#1216]
I like the gaps but don't need the active border when there's only one active window.

Would be great to see either or both of these:

- [this fix](https://github.com/hyprwm/Hyprland/commit/cd483a7a37c6024347659974701a76703c6e3a3a) for #460 separated into two vars
- an option to set a different border color for when there's only one window

Thanks for the great work, loving this WM so far!

**Comment by anufrievroman** [comment]
That would be great indeed! I see this feature is discussed under several different names, but essentially it is this, the ability to set no borders on only (while keeping gaps). People suggest scripting this, but personally I was never able to achieve it with scripting.

**Comment by izmyname** [comment]
Is this still actual?

**Comment by vaxerski** [comment]
dont think so since we nuked no gaps and its now up to the user
