### ISSUE TITLE
widows moved to special workspace remain focused

### ISSUE THREAD

**Issue by theRealCarneiro** [hyprwm/Hyprland#1217]
Windows that recive `movetoworkspace special` remain focused even tho the focused workspace stays the same, the only way to regain focus is by moving the mouse (or creating another window, the new window will be created on the focused workspace)

Step to reproduce:

1. Use movetoworkspace special on any window
2. Window will remain focused even tho workspace has not changed

What should have happened

- Equivalent to movetoworkspacesilent, window should lose focus 
- Or actual behavior of movetoworkspace, special workspace should be focused

I consider this a bug because when that happens, the only way the take back focus is by moving the mouse (creating another window also works).

**Comment by vaxerski** [comment]
fixed in 668cc93962c738d791993e581443273eaca05086
