### ISSUE TITLE
hyprland crashes after hyprctl keyword monitor, and then running any application

### ISSUE THREAD

**Issue by splump** [hyprwm/Hyprland#1219]
After reconfiguring monitors with hyprctl keyword and then starting an application, hyprland crashes. Steps:

1. Start hyprland with this in config:
`monitor=DP-1, 3440x1440@143.923004, 0x0, 1`
`monitor=HDMI-A-1, disable`
2. run `hyprctl keyword monitor "HDMI-A-1,3840x2160@60,0x0,2"`
3. run `hyprctl keyword monitor "DP-1,disable"`
4. run any application (firefox, steam)

Expectation is it shouldn't crash, but work normally. Attached is my hyprland.conf, hyprland.log and regular coredump. I've also attached the script i'm running usually which reliably provokes the crash. I've tried to create a debug coredump, but am unable to since no coredumps get generated after compiling and running with debug enabled for me.

Please let me know if i can provide anything else.

[hyprland.conf](https://github.com/hyprwm/Hyprland/files/10211535/hyprland.conf.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10211545/hyprland.log)
[coredump.txt](https://github.com/hyprwm/Hyprland/files/10211566/coredump.txt)
[script](https://github.com/hyprwm/Hyprland/files/10211538/switch-screens-hypr-script.txt)

**Comment by vaxerski** [comment]
check with f8a6799d4e41662f8a624da3e4eb3622161dd705

it's hyprctl btw, not hyperctl

**Comment by splump** [comment]
Ah sorry, just got the title wrong. :) Will check and get back to you asap!

**Comment by splump** [comment]
This did not solve the issue for me, still crashing. Attaching new log and coredump.

[coredump.txt](https://github.com/hyprwm/Hyprland/files/10212049/coredump.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10212056/hyprland.log)

**Comment by splump** [comment]
It's weird that libwlroots.so.12032 gets linked to my home directory, that's from running `makepkg -si` on a freshly cloned hyprland-git from AUR. Not sure if i'm causing that by doing something wrong or not, trying to look into it.

**Comment by vaxerski** [comment]
try building manually then

**Comment by splump** [comment]
So it seems just removing the file from my build directory apparently fixed the issue, Hyprland now uses the correct one from /usr/lib:

`❯ ldd /usr/bin/Hyprland | grep wlroots`
`	libwlroots.so.12032 => /usr/lib/libwlroots.so.12032 (0x00007f4cb3e43000)`
[coredump_13_dec_2022_19:05:11.txt](https://github.com/hyprwm/Hyprland/files/10220903/coredump_13_dec_2022_19.05.11.txt)

 Still the same crash though.

**Comment by vaxerski** [comment]
can you check with e9bd2ee996c73cd86eecd244321e11c5fa5c9c0c

**Comment by splump** [comment]
> can you check with [e9bd2ee](https://github.com/hyprwm/Hyprland/commit/e9bd2ee996c73cd86eecd244321e11c5fa5c9c0c)

Looks like this did the trick!

**Comment by splump** [comment]
> can you check with [e9bd2ee](https://github.com/hyprwm/Hyprland/commit/e9bd2ee996c73cd86eecd244321e11c5fa5c9c0c)

Looks like this did the trick with the specific always reproducible crashing i was having with opening new applications directly after switching monitors! I still have the odd crash here and there when switching monitors, do you want a new issue registered for that?

**Comment by vaxerski** [comment]
no, but a coredump would be nice

**Comment by splump** [comment]
Here's another coredump!

[coredump_211222_1853.txt](https://github.com/hyprwm/Hyprland/files/10280065/coredump_211222_1853.txt)

**Comment by vaxerski** [comment]
please try this patch

[patch.txt](https://github.com/hyprwm/Hyprland/files/10280159/patch.txt)

**Comment by romanstingler** [comment]
@splump is this resolved for you ??

**Comment by splump** [comment]
@romanstingler yes i'm pretty sure some update some time ago solved the issue. I haven't been using my pc running hyprland for quite a while so from my point of view this issue can be closed.
