### ISSUE TITLE
Moving windows by dragging is slow

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#1220]
I am sure this is an issue specific to something rather niche.
https://imgur.com/a/PrdmSZm
Here is a showcase of the problem. The issue came together with the mouse grabbing feature I'm sure, I was just too lazy to report it, despite it being kind of obstructive for my workflow.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/207154613-7b2c87c9-4b5b-4658-9560-70beccc1c6c0.png)
https://wiki.hyprland.org/Configuring/Variables/#misc

**Comment by EysseW** [comment]
Oops, I noticed my cursor wasn't captured. The point is that the window that's being dragged is lagging behind, to an extend where dragging it to another monitor in a whip is near impossible. I have got to hold it still on the other monitor for a while to let it stay there.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/207154877-59175f99-1c31-48f0-8308-4eb7f7f14b04.png)

**Comment by EysseW** [comment]
Okay, the problem still occurs when I set it to off though. And even if it didn't animations shouldn't make windows lagg behind.

**Comment by vaxerski** [comment]
#1127

**Comment by EysseW** [comment]
I am terribly sorry. I have searched but I wasn't able to find any other issues. It will contribute of that thread instead.
