### ISSUE TITLE
Auto adjust DPI by default like in Sway

### ISSUE THREAD

**Issue by glyh** [hyprwm/Hyprland#1221]
A really nice feature of Sway is that you don't have to calculate and config the DPIs on HiDPI screens because it take cares of them for you. I think it would be good if hyprland can have this feature.

I also made a similar [issue](https://github.com/qtile/qtile/issues/3389#issue-1151863809) in Qtile.

**Comment by vaxerski** [comment]
I saw the edit.

**Comment by vaxerski** [comment]
Sway's method is pretty dumb IMHO

https://github.com/swaywm/sway/blob/fbf9191fb8373e6718c61586329aaf362eeaa0c0/sway/config/output.c#L326-L370

I'd probably add an option to set scale to `auto` and use that as a default. Though I'd also like for that to cover more than just 1 and 2, at least 1.5 as well.

**Comment by glyh** [comment]
@vaxerski It's dumb but it works out of the box on my HiDPI screen at least.

**Comment by vaxerski** [comment]
I am just saying I wanna do it better.

**Comment by vaxerski** [comment]
done in 374571da96ea65f810387c5ff1872d3950076d08

the default scale is now `auto` which will automatically decide on a scale based on the ppi.
