### ISSUE TITLE
hyprland-share-picker is shown multiple times

### ISSUE THREAD

**Issue by hikkidev** [hyprwm/Hyprland#1223]
### Steps to reproduce
Try to share an entire screen or a window  ([video](https://mega.nz/file/BQdXCaia#hx14vzKrtPytKAH7tw9dAiSbWcqeBOLF0durVQt9v2w)).

### Expected behavior: 
`hyprland-share-picker` is shown once

### Actual behavior: 
`hyprland-share-picker` is shown multiple times ([video](https://mega.nz/file/BQdXCaia#hx14vzKrtPytKAH7tw9dAiSbWcqeBOLF0durVQt9v2w))

### Logs
[hyprland.log](https://hastebin.com/sexuhalaxa.rust)
[xdph.log](https://hastebin.com/nicavesute.yaml)

### Soft
hyprland-bin: (https://github.com/hyprwm/Hyprland/releases/tag/v0.19.1beta)
xdg-desktop-portal-hyprland-git r240.7567892-1

### System
```
OS             Arch Linux x86_64 
Kernel         6.0.11-zen1-1-zen 
Packages       1016 (pacman) 
DE             Hyprland 
Resolution     3440x1440 
Shell          zsh 5.9.0.1-dev 
Terminal       foot 
CPU            AMD Ryzen 7 3800X (16) @ 3.9GHz
GPU            AMD ATI Radeon 6900 XT 
GPU Driver     amdgpu 
```

**Comment by vaxerski** [comment]
that should go to the xdph tracker.
