### ISSUE TITLE
Launching and installing error

### ISSUE THREAD

**Issue by Knightfall01** [hyprwm/Hyprland#1226]
I have been trying to install hyprland on  my Arcolinux distro so i installed it through recursive git clone , to check whether it works i used hyprland on tty just like the install guide it just crashes after launch . okay ? so help me @vaxerski 

[error.txt](https://github.com/hyprwm/Hyprland/files/10223858/error.txt)

**Comment by arpangreat** [comment]
Same here in arcolinux , but it's happening after update spefically after 6.0 linux kernel zen .

**Comment by Knightfall01** [comment]
![swappy-20221214_182304](https://user-images.githubusercontent.com/107239398/207600364-89be589b-adcd-44d6-b3f0-b51651fc11f3.png)
 i followed this step

**Comment by vaxerski** [comment]
then you have built without DRM, somehow.

Make sure you have libdrm for the drm backend.

**Comment by Colepng** [comment]
@Knightfall01 may I ask why your building it manually? Couldn't you just use the aur package it works flawlessly for me and [wrapping hyprland](https://wiki.hyprland.org/Getting-Started/Quick-start/#wrapping-the-launcher-recommended) may help.
You can also join the [discord](https://discord.gg/FTptm5B7) if you need more help

**Comment by romanstingler** [comment]
@Knightfall01 could you resolve the issue?

**Comment by vaxerski** [comment]
I can
