### ISSUE TITLE
Black Screen with mouse cursor.

### ISSUE THREAD

**Issue by M1ndo** [hyprwm/Hyprland#1227]
Hyprland launches with a blackscreen and a mouse cursor.
This issue doesn't happen with launching something like sway.
Full Log: https://0x0.st/onLW.log

**Comment by vaxerski** [comment]
tried legacy renderer?

**Comment by M1ndo** [comment]
> tried legacy renderer?

couldn't find anything on the docs about legacy renderer and how to switch to it?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Getting-Started/Installation/

**Comment by M1ndo** [comment]
> https://wiki.hyprland.org/Getting-Started/Installation/

Worked with legacy renderer however its just too buggy and slow.

**Comment by vaxerski** [comment]
Legacy renderer will lack some graphical features (as expected)

The slowness is usually due to your system being too old to handle hyprland.

**Comment by Truars** [comment]
> Hyprland launches with a blackscreen and a mouse cursor. This issue doesn't happen with launching something like sway. Full Log: https://0x0.st/onLW.log

Guys **DON'T CLICK ON LINK**, this one is **malicious**.
https://www.virustotal.com/gui/domain/0x0.st/detection
