### ISSUE TITLE
movetoworkspacesilent isn't always silent

### ISSUE THREAD

**Issue by pbosab** [hyprwm/Hyprland#1230]
Hello,
noted a strange behavior, while using movetoworkspacesilent with the steam client, hyprland still switch to the workspace the client is sent. for now i am able to see this behavior only with steam.

- Steps to reproduce
open steam
use the keybind while steam is focused (bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3)
- Expected outcome
remain on the current workspace
- Noted outcome
workspace switch to the one i sent the client

**Comment by pbosab** [comment]
thanks for the fast reply:
> can't repro.
> 
> It could be:
> 
>     * you're using outdated hl of course
using git version built 30 mins ag
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/10239062/hyprland.conf.txt)
o
>     * you're using focus on activate and steam requests an activate
where can i check this?
>     * you're using movetoworkspace without knowing it somehow
nope, otherwise even the others apps would do the same...
>     * something I couldn't come up with in 13s
attached config

**Comment by vaxerski** [comment]
actually no clue. Doesnt happen to me.

**Comment by aalhitennf** [comment]
I have same problem with floating windows. Tiled windows are moved silently, but when silent moving floating window it follows to the workspace and after that i don't know what happens it gets really broken, can't tile the window again or move it back to normal workspace.  

hyprctl version:   

    Hyprland, built from branch main at commit f72c237d85f406f4a6a4ca181ee35399ca8c37bcdirty (add disabling keyboards).

**Comment by vaxerski** [comment]
fixed in deb8d3d82ebe4154b04bd97af847cf83c3ae1ce2
