### ISSUE TITLE
Key repeat not working for raise/lower volume

### ISSUE THREAD

**Issue by lcavalleria** [hyprwm/Hyprland#1231]
I set the bindings of keyboard  keys like so:
```
#### Commands bindings
# Volume
bind=,XF86AudioMute,exec,pamixer -t
bind=,XF86AudioRaiseVolume,exec,pamixer -i 5
bind=,XF86AudioLowerVolume,exec,pamixer -d 5
# Screen brightness
bind=,XF86MonBrightnessUp,exec,light -A 5
bind=,XF86MonBrightnessDown,exec,light -U 5
```
and the key repeat for the audio keys is not working, so i am not able to hold the key down to keep raising/lowering the volume.
However, the brightness keys do work.

I used wev to check how the keys are detected, and this is what i found:
-  In the case of volume keys, and also audio mute, only the release is detected.
- In the case of brightness keys, only the press and repeat is detected, but they are detected as release.
- I also tried `XF86AudioMicMute`, and it detects only the press, but as 2 events: press and release at the same time.

**Comment by vaxerski** [comment]
AAAAAAAAAAAAAAAAAAAAAAAA

https://wiki.hyprland.org/Configuring/Binds/#bind-flags
