### ISSUE TITLE
winapps freezes the system

### ISSUE THREAD

**Issue by spl3g** [hyprwm/Hyprland#1232]
- steps to reproduce
1. install winapps
2. try to run word
3. system is frozen
4. force reboot system

- expected outcome
system doesn't freeze

I think the logs are not saved when i force repoot the system .

**Comment by vaxerski** [comment]
does it happen on sway?

**Comment by spl3g** [comment]
No, it works okay.

**Comment by vaxerski** [comment]
odd. I'd guess a freeze coming from mesa, but I have no grounds to prove or even suggest that.

**Comment by spl3g** [comment]
It works for me too, even rdp connection via remmina works fine

**Comment by romanstingler** [comment]
@spl3g does this issue still occur?
