### ISSUE TITLE
focusing a window with dispatcher doesn't bring it to the front when workspace is in fullscreen mode

### ISSUE THREAD

**Issue by Daxtorim** [hyprwm/Hyprland#1234]
### Steps to reproduce 
1. Open two windows in a workspace
3. Get the window address (`$a`) of window 1
2. Toggle fullscreen
4. Focus window 2 (window 1 is no longer seen)
5. Go to another workspace
6. `hyprctl dispatch focuswindow address:$a`
7. Window 1 is correctly focused, **but** window **2** is still in the front and hiding window 1

### Expected outcome
Window 1 should be focused

### Notes
Issue occurs with both fullscreen mode 0 and 1.

**Comment by vaxerski** [comment]
thats what `bringactivetotop` is for. I just pushed a fix to make it also get thrown above the fullscreen window.

**Comment by Daxtorim** [comment]
`bringactivetotop` only works on floating windows (even with your most recent commit). It doesn't do anything when trying to bring a tiled window to the front when there is another fullscreen window in front.

**Comment by vaxerski** [comment]
as expected. Tiled windows should NEVER be on top of a fullscreen one.

**Comment by Daxtorim** [comment]
Yeah, but when I change focus with the `movefocus` dispatcher it switches windows just fine. It brings the next window to the front in fullscreen mode. 
Why does that not work for the `focuswindow` dispatcher? 
Or is that just side effect of `movefocus` basically doing a `cyclenext` when used from a fullscreen window?

**Comment by vaxerski** [comment]
movefocus works like cyclenext when it doesnt find a window to move to. Try opening 4 windows in a grid and moving right or to the bottom from the bottom right one.

**Comment by Daxtorim** [comment]
Ok, I think there is some confusion on my end of how the windows are stacked &mdash; or rather aren't. I thought when toggling fullscreen it makes *all* windows on a workspace fullscreen and stacks them on top of each other. That seems to *not* be the case.

Then I guess what I really want is for `focuswindow` to *replace* the fullscreen window with the window I am trying to focus, because that is the effective behavior of `movefocus` when cannot find a candidate.  When `movefocus` cycles to the next window it will remove fullscreen from the current one, tiling it and then making the new window fullscreen again.

Anyway, here is bash function to do just that:
```bash
focuswindow_for_realsiez(){
        address=$1
        clients=$(hyprctl clients -j)
        ws=$(echo "$clients" | jq -r --arg address "$1" '.[] | select(.address == $address) | .workspace.id')
        fs_client=($(echo "$clients" | jq -r --argjson WS "$ws" '.[] | select(.workspace.id == $WS) | select(.fullscreen == true) | .address, .fullscreenMode'))
        if [ -n "${fs_client[*]}" ]; then
                hyprctl dispatch focuswindow address:${fs_client[1]}
                hyprctl dispatch fullscreen ${fs_client[2]}
        fi
        hyprctl dispatch focuswindow address:$1
        if [ -n "${fs_client[*]}" ]; then
                hyprctl dispatch fullscreen ${fs_client[2]}
        fi
} &&
        focuswindow_for_realsiez "0xfce0fc00"
```

I would still prefer it if this behaviour could be implemented natively. I see little point in being able to focus a window I won't even be able to see.
