### ISSUE TITLE
error: ‘const hyprland_toplevel_export_manager_v1_interface’ has no non-static data member named

### ISSUE THREAD

**Issue by Bkeinn** [hyprwm/Hyprland#1236]
Building Hyprland 19.2beta on Fedora following the guid.
`ninja -C _build`
```
ninja: Entering directory `_build'
[1/2] Compiling C++ object src/Hyprland.p/protocols_ToplevelExport.cpp.o
FAILED: src/Hyprland.p/protocols_ToplevelExport.cpp.o 
c++ -Isrc/Hyprland.p -Isrc -I../src -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Iprotocols -I/usr/local/include -I/usr/local/include/libdrm -I/usr/include/valgrind -I/usr/include/pixman-1 -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -O3 -g -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing '-DGIT_BRANCH="main"' '-DGIT_COMMIT_HASH="e405490593cd8f38e95bdbbc90fcb617039f23b1"' '-DGIT_COMMIT_MESSAGE="fix workspace special rules"' '-DGIT_DIRTY=""' -DHYPRLAND_DEBUG -std=c++23 -pthread -DWLR_USE_UNSTABLE -MD -MQ src/Hyprland.p/protocols_ToplevelExport.cpp.o -MF src/Hyprland.p/protocols_ToplevelExport.cpp.o.d -o src/Hyprland.p/protocols_ToplevelExport.cpp.o -c ../src/protocols/ToplevelExport.cpp
../src/protocols/ToplevelExport.cpp:73:1: error: ‘const hyprland_toplevel_export_manager_v1_interface’ has no non-static data member named ‘capture_toplevel_with_wlr_toplevel_handle’
   73 | };
      | ^
ninja: build stopped: subcommand failed.
```

**Comment by vaxerski** [comment]
clean and rebuild

**Comment by Bkeinn** [comment]
`meson setup --wipe _build/`
Same Error
`sudo rm -r -d Hyprland/` And starting again still results in the same error.

I found two errors during the meson _build process.
`Build-time dependency hwdata found: NO (tried pkgconfig and cmake)`
`wlroots| Checking for function "xcb_xfixes_set_client_disconnect_mode" with dependencies xcb, xcb-composite, xcb-icccm, xcb-render, xcb-res, xcb-xfixes, xcb-errors: NO`
Dnf prints that both of them are installed
`dnf install hwdata libxcb-devel --best`
```
Nothing to do.
Complete!
```

**Comment by vaxerski** [comment]
you did not pull recursively probably then

either way, your submodules are outdated. Not an issue with hyprland

**Comment by Bkeinn** [comment]
I cloned again and made sure that I added ```--recursive```.
I don't know much about git so I googled and found a tutorial to update git modules.
```
git submodule init
git submodule update
```
but building again still gave me the same error.

**Comment by vaxerski** [comment]
The CI does not fail to build. This means there is something wrong with your installation. Can't help much with that.

**Comment by Bkeinn** [comment]
I rebuild the 
`subprojects/hyprland-protocols`
And it build successfully
