### ISSUE TITLE
Option to disable scaling on Xwayland

### ISSUE THREAD

**Issue by BBaoVanC** [hyprwm/Hyprland#1237]
Is it possible to make an option to not scale Xwayland apps so they render at 1:1 scale on all monitors (meaning on HiDPI they'll be tiny if the app/game doesn't support scaling, but sharp rather than blurry)? I think I would prefer this over the [existing global scale factor solution](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/733) that exists, since that solution causes Xwayland to be too tiny and blurry on LoDPI monitors.

**Comment by taylor85345** [comment]
Xwayland does respond to changes made with xrandr, so you might try setting the scale with something like:

`xrandr --output screen-name --scale 1x1`

If that works, maybe try adding it to your exec list?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/XWayland/

**Comment by BBaoVanC** [comment]
> Xwayland does respond to changes made with xrandr, so you might try setting the scale with something like:
> 
> `xrandr --output screen-name --scale 1x1`
> 
> If that works, maybe try adding it to your exec list?

@taylor85345 I remember trying this before, but it just gives an error:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  26 (RRSetCrtcTransform)
  Value in failed request:  0x22
  Serial number of failed request:  28
  Current serial number in output stream:  29
```

> https://wiki.hyprland.org/Configuring/XWayland/

@vaxerski That is the "existing global scale factor solution" that I was referring to where it makes all Xwayland apps on my LoDPI monitor be tiny and blurry. I just don't want it to be scaled/stretched by the Wayland compositor and just expose every pixel at regular DPI to be sharp (but small) on HiDPI.

I noticed in `xrandr` that my HiDPI monitor is set to only 1440p instead of 4K in Xwayland, I assume that has to do with the scaling? I want X apps to see 4K so they'll render sharply.

**Comment by vaxerski** [comment]
not up to us. XWayland and X in general absolutely suck with scaling.

**Comment by BBaoVanC** [comment]
I'm ok with doing patching myself, just I can't really figure out where anything is that I need to change

**Comment by vaxerski** [comment]
dunno either. @fufexan might
