### ISSUE TITLE
"workspace" now have implicit silent attach to it

### ISSUE THREAD

**Issue by nawfalmrouyan** [hyprwm/Hyprland#1238]
I have,

`bind = $mainMod, W, exec, [workspace 2] $browser`

Previously, opening $browser would follow the window to workspace 2. But now it behaves as if `[workspace 2 silent]`.
This affects windowrule too. For example:

`windowrulev2 = workspace 5, class:^(gnome-connections)$`

behaves like below:

`windowrulev2 = workspace 5 silent, class:^(gnome-connections)$`.

It was working fine yesterday.

**Comment by vaxerski** [comment]
fixed with 7c33c7fc64203c17b4f3625a16ae6b4774992c0e
