### ISSUE TITLE
Transparency bug on Path of Building App

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#1244]
Hello, I'm experiencing an issue where the context menus, background and everything on the path-of-building-community app is transparent, and so my background makes it nearly impossible to read it in a good way.
![image](https://user-images.githubusercontent.com/94939040/208253586-0bede4e2-1451-4f54-acc7-81dc4a6a99f3.png)

I'm on Gentoo and the ebuild for this app was created by me, I tested in a vm and it works normally on dwm, tested on real hardware and it works as intended on Gnome Wayland too. 
I'm using both Hyprland and hyprpaper 9999 (git version).

hyprctl clients spits out: 
```
Window f1312d20 -> Unnamed build (Scion) - Path of Building:
	at: 7,28
	size: 1906,1045
	workspace: 3 (3)
	floating: 0
	monitor: 1
	class: pobfrontend
	title: Unnamed build (Scion) - Path of Building
	pid: 4237
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	grouped: 0
	swallowing: 0
```
	
The package is also available on the AUR and also as flatpak community.pathofbuilding.PathOfBuilding, though I'm not the maintainer of neither of those.

Any more info needed I'm glad to help!

**Comment by vaxerski** [comment]
do you have blur_xray on by any chance?

**Comment by jabuxas** [comment]
I don't. It should default to false too, according to wiki.

I do have ```
windowrule = noblur, pobfrontend
windowrule = noshadow, pobfrontend
windowrule = noanim, pobfrontend
```
on my config though. I enabled those because i thought it would fix it.

**Comment by jabuxas** [comment]
To note, it happens when floating and when tiled.

**Comment by vaxerski** [comment]
its that one bug then. blame xwayland.

**Comment by jabuxas** [comment]
what bug? are you sure it's running on xwayland? it says 0

**Comment by vaxerski** [comment]
wait, it's not xwayland? Then it's another idiot using an XRGB surface and drawing alpha. Ugh.

**Comment by jabuxas** [comment]
for reference, these are the links that constitute the main part of the package.

https://github.com/PathOfBuildingCommunity/PathOfBuilding
https://gitlab.com/bcareil/pobfrontend#branch=luajit

Is it fixable?

**Comment by vaxerski** [comment]
> Is it fixable?

Yes, but annoying

**Comment by vaxerski** [comment]
actually, can you tell me whether this happens on sway?

**Comment by jabuxas** [comment]
It doesn't happen on sway 1.7. Works as intended.
![screenshot-2022-12-17T23:05:37-03:00](https://user-images.githubusercontent.com/94939040/208276288-67a139b2-ef95-4d5e-a050-34bf28f57fb1.png)

**Comment by jabuxas** [comment]
not sure if it's related, but, obs has some transparency bugs as well

**Comment by vaxerski** [comment]
you can use the `forcergbx` windowrule tho to fix this, no?

**Comment by jabuxas** [comment]
actually, i'm not really sure how, but obs transparency bugs are gone, maybe an update to hyprland fixed it, or something else. I don't really use Path of Building anymore so I'll close this one out. Also thanks for pointing out that rule, didn't know about it.
