### ISSUE TITLE
Support for fractional percentages in windowrules

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1246]
![image](https://user-images.githubusercontent.com/68589851/208280451-1aeb0d1e-0c87-4a8f-a4fd-0a475c7c795a.png)
I'm currently trying to use the move windowrule, but it doesn't seem to support fractional percentages
(93.999% and 94% are at different locations)
This would create windows that are at fracitonal pixels... which are a problem. Maybe this can be solved by rounding?

**Comment by vaxerski** [comment]
why are you doing 93.999%?

**Comment by JustSimplyKyle** [comment]
That's just a demonstration.
I initially just wanted to use 93.5%, but itt doesn't seem to change anything.
So I tried 93.99%

**Comment by vaxerski** [comment]
but why

**Comment by vaxerski** [comment]
should be done anyways in a1143521d396b7cbe1423bbd1bcb6b2c07f8df8f
