### ISSUE TITLE
Change keyboard layout with hyprctl

### ISSUE THREAD

**Issue by Teddy-Kun** [hyprwm/Hyprland#1249]
Could we get a way to change the current keyboard layout with hyprctl? I prefer the us layout for 99% of what I do, but sometimes I have to write stuff in german and I am missing the special characters. I would love to have a simple script, accessible with a simpel shortcut, to change that as editing the config file over and over again seems like not a good way to do that.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts
