### ISSUE TITLE
Add CenterMaster layout for Ultrawide monitors

### ISSUE THREAD

**Issue by etrigan63** [hyprwm/Hyprland#1250]
When you have the time, please add a CenterMaster layout for Ultrawide monitors. The layout behaves as follows:
Single window = full screen
Two windows = Split 50/50 Master on the left
Three or more windows = Master in center 50% of screen, stack on left and right using 25% of screen each. As more windows are added to the stack, they appear round-robin in the left and right stacks.

Here is a sample from `dwm`
![image](https://user-images.githubusercontent.com/7347264/208364536-38c903fa-2f5a-4257-bdd4-67cf7b374ad5.png)

**Comment by proycon** [comment]
Just some thoughts: Implementation-wise, I think this could be implemented in the existing master layout by expanding the `orientation` functionality I implemented in https://github.com/hyprwm/Hyprland/pull/1202. Looking there might serve as a good starting point in case anybody wants to give this a try.

Extra orientations could for example be:

* `orientationcenterorleft` - master in horizontal center or on the left in case of two windows, as suggested
* `orientationcenterorright` - master in horizontal center or on the right in case of two windows

And then there's the question if people want something like this in a vertical layout (surely  there must be some crazy people who turn ultrawide monitors in portrait mode? :) ), if that's the case:

* `orientationcenterortop` - master in vertical center or at the top in case of two windows
* `orientationcenterorbottom` - master in vertical center or at the bottom in case of two windows

I'd be a bit careful of feature creep and not suggest the latter two unless there's actual demand for it. @etrigans63's use case on a horizontal wide monitor does make sense to me. (I had also thought of it when doing #1202 but didn't really have a use for it myself)

**Comment by etrigan63** [comment]
I have no issues with those suggestions, @proycon. My c++ is a bit rusty (no pun intended), but I will take a look at that request.

**Comment by etrigan63** [comment]
My skills are rustier than I thought.

**Comment by ecocode** [comment]
With an ultrawide monitor this layout is really awesome

**Comment by etrigan63** [comment]
For clarification, new windows added to the layout are always the latest master with former master being pushed to the left or right stacks in a round-robin fashion.
