### ISSUE TITLE
Enabling disable_autoreload config option has no effect

### ISSUE THREAD

**Issue by nicegamer7** [hyprwm/Hyprland#1255]
Enabling the `disable_autoreload` config option doesn't seem to do anything; the config continues to reload automatically. Also tried restarting Hyprland, but that didn't help.

**Comment by vaxerski** [comment]
it got deprecated and I forgot to remove it

**Comment by vaxerski** [comment]
removed from the wiki

**Comment by nicegamer7** [comment]
It's still being used in ThreadManager.cpp, might want to remove that.

**Comment by vaxerski** [comment]
no, wait, what?

You gaslit me. It does work. It should...? I thought I made it into a wl fd source but I did not.

Wdym it doesnt work

**Comment by vaxerski** [comment]
just tested, it does work.

**Comment by nicegamer7** [comment]
Hmm, I'm not sure why it wouldn't work on my end. I'm on the latest release using the NixOS module with Flakes; is there anything else that might be helpful to know?

**Comment by vaxerski** [comment]
cuz it nix prolly @fufexan

**Comment by fufexan** [comment]
Yeah the Nix module reloads using hyprctl on rebuild. Will fix soon.

**Comment by nicegamer7** [comment]
Hmm, I think that's okay since I was only using the option to avoid ticking in the background.

Maybe just a separate option on the module, or just leave it as is until someone else complains.

**Comment by fufexan** [comment]
Okay, I'll add that.

**Comment by fufexan** [comment]
Done in https://github.com/hyprwm/Hyprland/commit/781f0adad4dfedb74c5e05c11f95dcb153bbb6ac

**Comment by nicegamer7** [comment]
Thanks!
