### ISSUE TITLE
Setting up a proxy

### ISSUE THREAD

**Issue by spl3g** [hyprwm/Hyprland#1264]
This is more of a question than a bug.
I tried to set up a proxy through qv2ray, it changes the system proxy with gsettings, but it doesn't work in hyprland.
Can I change the proxy settings with something else or make gsettings work?

**Comment by vaxerski** [comment]
how does that relate to hyprland in any way? we're not gnome

**Comment by A7R7** [comment]
A workaround for me is to set proxy in desktop files, or run them in a shell environment where proxy is set.

**Comment by hydroakri** [comment]
It is a dirty
I use `export http_proxy=http://username:password@proxy-servername:port/`
