### ISSUE TITLE
Hyprland in state where it doesn't paint any windows after disabling monitor (hyprctl, wlr-randr, kanshi, doesn't matter)

### ISSUE THREAD

**Issue by bklaase** [hyprwm/Hyprland#1266]
After disabling a monitor with wlr-randr or kanshi, nothing gets painted anymore. Switching workspaces after that hides all windows, and switching back won't get them back. Both true for `v0.19.2beta` tag, as latest commit (96cb47fc64438c93e7663afa832a567120f82128).

[edit] clarification

**Comment by vaxerski** [comment]
what about `hyprctl`?

**Comment by bklaase** [comment]
you mean, using hyprctl to disable monitor through dpms dispatcher, or somehow setting `monitor=name,disable` with hyprctl?

**Comment by vaxerski** [comment]
> or somehow setting monitor=name,disable with hyprctl?

`hyprctl keyword monitor ...` is very well documented.

**Comment by bklaase** [comment]
`hyprctl keyword monitor LVDS-1,disable` causes the exact same issue.

starting situation is this:
```
Monitor LVDS-1 (ID 0):
	1366x768@60.103001 at 0x0
	description: AU Optronics 0x106C (LVDS-1)
	active workspace: 3 (3)
	reserved: 0 20 0 20
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1

Monitor VGA-1 (ID 1):
	1920x1080@59.933998 at 1366x0
	description: Samsung Electric Company SyncMaster H9XS915612 (VGA-1)
	active workspace: 2 (2)
	reserved: 0 20 0 20
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
```

**Comment by bklaase** [comment]
might be related, to #1219.  
Will try that patch tomorrow

**Comment by bklaase** [comment]
okay, after searching existing issues better, I became convinced this is a duplicate of #766.
