### ISSUE TITLE
Disabling a monitor causes it to no longer be detected

### ISSUE THREAD

**Issue by bklaase** [hyprwm/Hyprland#1274]
Disabling through either kanshi, wlr-randr, or hyperctl makes the monitor undetectable through either.
So for example if I run `hyprctl keyword monitor LVDS-1, disable` , the monitor `LVDS-1` can no longer be found through: `hyprctl monitors`, or `wlr-randr`. Thus making it impossible to re-enable. Perhaps the issue that is being alluded to all the way at the end of #453. Perhaps this is even introduced by the fix?

running latest git version.

**Comment by vaxerski** [comment]
> So for example if I run hyprctl keyword monitor LVDS-1, disable , the monitor LVDS-1 can no longer be found through: hyprctl monitors, or wlr-randr.

Correct

> Thus making it impossible to re-enable.

Incorrect. Run `hyprctl keyword monitor LVDS-1,pref,auto,auto` and it will come back

**Comment by bklaase** [comment]
And so it does. Reading the wiki I tried to create way to re-enable monitors regardsless of their name, through

`hyprctl keyword monitor ,pref,auto,auto`

but that doesn't work. Can I ask why it is removed, as opposed to disabled (like sway / wayfire do)?

It becomes more challenging to have kanshi automatically react to monitor disconnects, since it can't match anymore to the now removed internal monitor

**Comment by vaxerski** [comment]
disable does exactly what it says. I think you're confusing it with dpms.

**Comment by bklaase** [comment]
That might very well be the case. The reason I bring it up, is that kanshi profiles disabling a display when an external monitor is connected, depend on the original still being found (though in disabled state) when external monitor is subsequently disconnected (as is apt to happen with laptop docking). This is how it does work with wayfire and sway. However due to hyperland actually removing (also through kanshi / wlr-randr) this plug and play behavior no longer functions.

the tooling can no longer differentiate between a disconnected and disabled monitor

I'll show some output of wlr-randr when disabling primary screen in another wlroots based comp.

**Comment by bklaase** [comment]
```
LVDS-1 "LG Display 0x02EB (LVDS-1)"
  Physical size: 310x170 mm
  Enabled: no
  Modes:
    1366x768 px, 40.015999 Hz
    1366x768 px, 59.995998 Hz (preferred)
```

Note the `Enabled: no`

**Comment by vaxerski** [comment]
thats dpms

**Comment by bklaase** [comment]
I am not saying it isn't,but the way to get that output still detected, but also in the disabled state is through kanshi, `wlr-randr --output bla disable `, etc.

consequence: no windows, or workspaces can be on that monitor.
Now with DPMS, there can be. It's late here now, but tomorrow I'll run a test that will show wlr-randr output in a DPMS powered down state. But the point is, the outcome of that won't imply that the disabled state can *only * be set through DPMS. (as we  know it can be done manually).

the fact is that hyprland removes monitors after wlr-randr disable, and sway/wayfire don't. It might also be that the others do it "wrong". However tools like kanshi expect their behavior, to enable this scenario:

1. laptop is docked
2. internal screen is "disabled", external screen enabled 
3. after undock, internal screen is re-enabled

step 3 will only work, if the internal monitor isn't removed after kanshi profile application (as happens with sway/wayfire and doesn't happen with Hyprland) .

of course manually re-enabling through `hyprctl keyword monitor LVDS-1,pref,auto,auto ` would work, but requires hardcoding internal display name.

So way too much words to say, could the different ways these compositors handle this be reason to consider not removing the monitor?

**Comment by vaxerski** [comment]
not really, no. You can always make a script to move all the workspaces out when you do dpms.

**Comment by bklaase** [comment]
All but one, but

**Comment by levnikmyskin** [comment]
Hey,
sorry to comment on a closed and "old" issue. Just wanted to report [this conversation](https://gitlab.com/w0lff/shikane/-/issues/5) we've had on Gitlab regarding kind of the same problem. From the last comment of Hendrik Wolff (author of that Shikane tool):

> I just went over to [#wlroots on Libera Chat](https://web.libera.chat/gamja/?channels=#wlroots), asked around and emersion clarified that hyprland behaves incorrectly. Adding that "[…] the main difference between wl_output and wlr_output_management_head [is that] the former goes away when disabled, but not the latter".
The wayland server should send the [enabled event](https://wayland.app/protocols/wlr-output-management-unstable-v1#zwlr_output_head_v1:event:enabled) (with the 0 value) instead.
If you need more explanations just head over to the [#wlroots IRC channel](https://web.libera.chat/gamja/?channels=#wlroots).

Do you think that it could be possible to "update" Hyprland behaviour, Vaxry? (I'm available to help if necessary). Thanks :)

**Comment by vaxerski** [comment]
mhm

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11637316/patch.txt)

try this patch

**Comment by levnikmyskin** [comment]
Tried, but still didn't work

**Comment by bklaase** [comment]
For me neither. It's not a big deal, but as I mentioned in OP tooling expects the other behavior.

**Comment by k4j8** [comment]
Running `hyprctl reload` re-connects all monitors for me. I have all of them defined in my `hyprland.conf` file.

I came across this fix by reading [this comment](https://github.com/hyprwm/Hyprland/issues/2549#issuecomment-1603428605) on a similar issue.

**Comment by leiserfg** [comment]
Gosh, this is still happening, it would be nice if Hyprland had a way to define a fallback-monitor settings to try to re-enable it if there are no monitors marked as available.
The problem with using dpms instead of disabling is that the monitor will get the workspaces/windows anyway.

**Comment by levnikmyskin** [comment]
I've been investigating this a bit, but I have no time at the moment to fully understand how to implement something (will definitely try in the future), but I'll post my findings here, maybe they help somebody else (or vaxry himself, I'll tag him).

As mentioned, the problem is that apparently Hyprland is not exactly following the wayland protocol somewhere.

When a monitor is disabled, Hyprland is sending the `finished` and `done` signals via wl_roots (see my previous comment): this shouldn't happen. It seems to me that the reason this is happening is in `src/events/Monitors.cpp`, in the last line of function `listener_change`. That call to `wlr_output_manager_v1_set_configuration` is what is (then) activating the wrong signals. 
I'm not sure whether this function shouldn't be called at all in this case, or should be called but with a different `CONFIG` or `g_pCompositor->m_sWLROutputMgr` (aka `wlr_output_manager_v1`) state.

That said, I believe the problem is also in `src/helpers/Monitor.cpp`. I think the "actually completely destroy the monitor" signal is  sent by `wlr_output_manager_v1`, whereas the current connection to `wlr_output` should be used for the "disabling monitor" signal. I'm not too sure about this, in general my plan is to read sway code to understand what they're doing.

Once this is fixed, tools like kanshi or shikane can be correctly used in Hyprland too.

@vaxerski FYI

**Comment by vaxerski** [comment]
if that's the root cause, change line 25's `m_vMonitors` to `m_vRealMonitors` then and test that.

**Comment by levnikmyskin** [comment]
@leiserfg https://github.com/hyprwm/Hyprland/pull/3718 could you please try with this branch?

**Comment by leiserfg** [comment]
@levnikmyskin  it didn't work, when I unplugged the external monitor the laptop screen stayed off.
The logs of hanshi don't mention any status change.

**Comment by leiserfg** [comment]
@levnikmyskin  this issue regressed after aquamarine, can you have a look again?

**Comment by levnikmyskin** [comment]
@leiserfg I noticed Vaxry has an open pr on this. I wanted to check anyway as soon as I get some time, but lately I'm a little overworked by my daily job...I'm indeed still running hyprland 0.41 I think, or whatever version before aquamarine

**Comment by leiserfg** [comment]
I tried the PR from @vaxerski and that didn't work.

**Comment by Iss-in** [comment]
problem is that, kanshi is interfering with hyprland monitors

my case, say I have two monitors, Left and Right
and if I disable the right one using kanshi profile  `kanshictl switch left` , right monitor will be disabled, and in output of `hyprland monitors` i will see only the left monitor.

Now no matter what, i can not enable 2nd monitor using kanshi.
to enable it, I need to kill kanshi daemon. and then restart kanshi or run `hyprctl keyword monitor ,pref,auto,auto`

any fix please @vaxerski  . this is interfering in daily workflow when i want to enable and disable a monitor, and we only got kanshi as a reliable monitor configuration tool

**Comment by leiserfg** [comment]
Kanshi disables the monitor, which is correct. To see the full list do `hyprland monitors all`.
The correct way of allowing both enabling and disabling the same monitor with shikane  at least, is to have both profiles and switching to the second profile by hand. I advise moving from kanshi to shikane as its implementation is way more correct.

**Comment by Iss-in** [comment]
> Kanshi disables the monitor, which is correct. To see the full list do `hyprland monitors all`. The correct way of allowing both enabling and disabling the same monitor with shikane at least, is to have both profiles and switching to the second profile by hand. I advise moving from kanshi to shikane as its implementation is way more correct.

i tried shikane, and it seems to be extremely buggy for me, can not switch between profiles with ease, sometimes it straight outs destroys my hyprland setup when i switch between profiles quickly for testsing, sometimes it keeps picking up a secondary profile as default.

**Comment by levnikmyskin** [comment]
Kanshi can also do profile switching, like shikane does, so no reason to jump from one to the other.
That said, that behaviour is weird, in my case I manage to re enable disabled monitor with kanshi with no problems. On what hyprland commit/tag are you on?

**Comment by leiserfg** [comment]
> Kanshi can also do profile switching, like shikane does, so no reason to jump from one to the other. That said, that behaviour is weird, in my case I manage to re enable disabled monitor with kanshi with no problems. On what hyprland commit/tag are you on?

I know, I used to use Kanshi, I moved to shikane cause kanshi is easier to debug the events when something breaks.
Hyprland multimonitors is kinda broken in master now, last "stable" commit is b6e226c3200276978e487a68a16fd696fcb7e7c8.

**Comment by Iss-in** [comment]
> Kanshi can also do profile switching, like shikane does, so no reason to jump from one to the other. That said, that behaviour is weird, in my case I manage to re enable disabled monitor with kanshi with no problems. On what hyprland commit/tag are you on?

hyprland 0.44.1-2 AUR version
