### ISSUE TITLE
Support for 5k display (Dell UP2715k)

### ISSUE THREAD

**Issue by y4roslav** [hyprwm/Hyprland#1279]
I'm facing the same issue described here  https://bbs.archlinux.org/viewtopic.php?id=261808
Is there any possibility (solution) so I can setup it in Hyprland? 
 
 ```
  ~> hyprctl monitors
Monitor DP-8 (ID 1):
	3840x2160@59.997002 at 848x0
	description: Dell Inc. DELL UP2715K F1JCM55D108S (DP-8)
	active workspace: 1 (1)
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1

Monitor DP-7 (ID 2):
	848x480@59.744999 at 4688x0
	description: Dell Inc. DELL UP2715K F1JCM55D108S (DP-7)
	active workspace: 2 (2)
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1 
```

**Comment by vaxerski** [comment]
if you can't see the mode in `wlr-randr`, it's not an issue with hyprland.

You can try to force a custom mode with your desired resolution by just explicitly setting it in the conf but if that does not work the you're out of luck bud
