### ISSUE TITLE
feat: zoom to frame

### ISSUE THREAD

**Issue by edrex** [hyprwm/Hyprland#1282]
In [newm](https://github.com/jbuchermn/newm) 's infinite plane ZUI layout,
you can "climb" into and out of layout frames with a gesture. 

This multi-scale structure helps me understand what I'm working on.

Is there a "zoom to layout frame" feature in any of the existing layouts?

**Comment by vaxerski** [comment]
no

**Comment by edrex** [comment]
how about i3-style frame selection + fullscreen?

**Comment by edrex** [comment]
sorry, i should take this to chat
