### ISSUE TITLE
Feature: maximize in special workspace

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#1285]
Good day to you!

suggesting ability to maximize windows in special workspaces

thank you!

**Comment by tipa40** [comment]
Yes please, I hope this one will be implemented ;)

**Comment by MxCG** [comment]
This seems to be a good first issue.
Can someone give me some guidance on where I should start to better understand the codebase?

**Comment by vaxerski** [comment]
this is not a good first issue and is not an easy fix. Maximize is closely tied to fullscreen and fullscreen on special would be tricky to say the least.

**Comment by vaxerski** [comment]
all the other states that bind with fullscreen. Hiding top layers, optimizations, renderer, etc.
