### ISSUE TITLE
Feature: special workspace option: blur area around special workspace

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#1286]
Good day to you!

suggesting  option for special workspace: blurring area outside windows, for minimizing distractions around workarea

before:
![image](https://user-images.githubusercontent.com/52028706/209614296-7c7f1184-f572-4c76-80cc-f8284654b15c.png)
after:
![image](https://user-images.githubusercontent.com/52028706/209614266-0556c810-ee48-44ae-87d0-9ef2b28042ac.png)
 
 thank you!

**Comment by vaxerski** [comment]
why?

**Comment by fedoranvar** [comment]
@vaxerski 
for minimizing distractions around workarea
similar to popup windows in iphone

or maybe not blurring but dimming backgroun
![image](https://user-images.githubusercontent.com/52028706/209680968-309ff108-7053-49ab-aacd-2ea0a85aab40.png)

**Comment by fedoranvar** [comment]
UPD.
I think it will be universal to add option to dimm all background except some windows, if they are focused, so we can even apply it in special workspace scenario,

```bash
windowrule=dimm_arround,^(confirm_dialogue)$
```

and some rules with constraints like "if window in special workspace"

**Comment by vaxerski** [comment]
added dim_special in b5f5c26be3074a16556c2b7982029fbfcf502b16

**Comment by vaxerski** [comment]
added dimaround window rule in a6699ef30c0a7f66c4b1ff6e38ea836b8e898015

this is as far as I'm probably going to go.

Cheers

**Comment by fedoranvar** [comment]
@vaxerski 

checked it: there is some artifacts, when i'm killing window with dim_around rule

everything else is good!

**Comment by vaxerski** [comment]
759490689c3bcb897c900874fcf3be30d72ec74f

**Comment by YodaEmbedding** [comment]
Is there any way to disable the dimaround on special workspace windows, just like i3?

**Comment by vaxerski** [comment]
blur aint cheap

**Comment by au-summer** [comment]
Is it possible to dim the space around ordinary workspaces?
