### ISSUE TITLE
Resizing psudotiled window only affects it's "tilied" size

### ISSUE THREAD

**Issue by G0BL1N** [hyprwm/Hyprland#1288]
One common usecase of resizing pseudotiled windows for me is making a single window narrower on ultrawide screen, without making it floating. It's something that I used a lot on bspwm, and, sadly, it seems to be impossible on Hyprland.
It looks like on hyprland in dwindle layout `resizewindow` for tiled windows controls window's _borders_ relative to other windows, and only in the direction it was split. So it resizes like a tiled window, but actual window size depends on the size of it in floating mode, making it impossible to change, at least with a mouse.
However, in bspwm, window size for pseudotiled windows actually controlled "floating" size, and instead it's "tiled" size was impossible to change directly. However, you could still force the pseudotiled window into a smaller window or give it more space if you resize other windows, so both were possible.
Sorry If I'm vague, it's kinda hard to explain. If my explanation is not good enough, just play around with pseudotiled windows in bspwm and in Hyprland and you'll see what I mean.  
What I'm getting at: would it be possible to change the behavior of `resizewindow` for pseudotiled windows, so it would change window's "floating" size? Or add another, specific mouse bind to specifically only interact with floating size of windows?
I could try to make a PR if that's a desirable feature, but I don't know if I'm capable.

**Comment by vaxerski** [comment]
if I understand this correctly this has been long fixed
