### ISSUE TITLE
Changes to windows not rendering in active workspace while connected to external monitor

### ISSUE THREAD

**Issue by Cloudcolour** [hyprwm/Hyprland#1291]
# Description
Hyprland doesn't properly render changes to windows in the active workspace when launching or killing applications, and when opening GUI dropdown/pop-up menus while connected to an external monitor through HDMI.

Issue goes away if I'm not connected to hdmi.

# Steps to Reproduce
Connected laptop to an external monitor through HDMI. Start hyprland from a tty. Kill or start an application with a hyprland keybind. 

For app menus run anki and within the gui go to Tools > Add-ons. 

Here are my settings
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/10312427/hyprland.txt)

# Expected Outcome
When I open or kill a window the workspace will render windows and resize as needed.

For the app menu, it should open up a drop down menu and then open up a popup for add-ons. 

# Noted Outcome
Doesn't render the changes on my display. I kill the window but then it doesn't disappear/it disappears but doesn't resize other windows to fill the gap. Or I start an application and the window begins to render but then freezes and doesn't finish rendering or resizing other windows.

For the app menus they don't display, or pop-ups don't appear after clicking the option.

Switching active workspaces, either with a keybind or by moving my cursor onto the workspace on my other monitor immediately causes the frozen workspace to finish rendering.

Here is a screenshot.

![sc](https://user-images.githubusercontent.com/49924063/209752931-9d2cce1b-e16e-4312-b1b8-7e96ab62045d.jpg)
You can see the terminal instances are stuck without fully rendering.

# What I tried
I turned off blur and animations. 

This doesn't happen every time, but it happens very frequently.

**Comment by vaxerski** [comment]
what the actual fuck

**Comment by danielclucas** [comment]
Yeah. Is there any additional info you need?

**Comment by vaxerski** [comment]
have you tried performing an exorcism on your computer

**Comment by bklaase** [comment]
Could you please comment out all those window rules?
From the wiki:

> Dynamic matching properties are title, floating, fullscreen and pinned
I suspect that alacrity doesn't instantly alter its title, causing some eldritch-like behavior with all those rules.

**Comment by danielclucas** [comment]
Exorcism attempted, but the evil spirits are too powerful. 

@bklaase I removed the window rules, but I'm stilling encountering the issue. It's not restricted to alacritty, I just used alacritty as an example. A typical example is I am working on alacritty, then I close it. So it disappears, and then the outside border of the other window resizes, but doesn't fill in the space and the window for that program stops rendering. Other windows that didn't need to be resized don't have issues. Once I move my mouse to the second monitor the display instantly updates. 

I mentioned in the original post, but it also affects pop up and dropdown menus. They will freeze rendering, and once I move my mouse to my other monitor the display instantly updates.

**Comment by REALERvolker1** [comment]
Bumping this, as it also happens to me.

**Comment by vaxerski** [comment]
is this a regression?

**Comment by REALERvolker1** [comment]
it's something, alright

**Comment by bklaase** [comment]
yes, but did it behave like this in a (much) older hyprland? You could try tagged commits to help debug

**Comment by Cloudcolour** [comment]
This was resolved when I set `no_vfr=false`.
