### ISSUE TITLE
Login Manager (Least imp)

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#1293]
I am totally aware that this is out from the scope of Hyprland.
but then also thought to propose.
> available login managers :- sddm,ly,gdm

sddm: - works but get's many kde applications and xorg installed good for someone who is using kde plasma as primary.
ly:- not perfect (get's the job done. does not go with the ui asthetics of Hyprland)
gdm:- didn't gave try but naah.

a respective login manager and a lockscreen will be a good add on as if some one wants to only use hyprland.
as swaylock have less features too.

**Comment by Ziqi-Yang** [comment]
Maybe you can try lightdm, which is a cross-desktop display manager, providing you with a lot of flexibility on the choice of the front end(greeter). For example, you can try [web-greeter](https://github.com/JezerM/web-greeter), which uses webkit2gtk and allows user to create web-based themes with HTML, CSS, and JavaScript, so there won't be ui aesthetics if you write your own theme in the case that you couldn't find a right theme that fit Hyprland. You can find other greeter here: https://wiki.archlinux.org/title/LightDM

**Comment by niksingh710** [comment]
> Maybe you can try lightdm, which is a cross-desktop display manager, providing you with a lot of flexibility on the choice of the front end(greeter). For example, you can try [web-greeter](https://github.com/JezerM/web-greeter), which uses qt5-webengine and allows user to create web-based themes with HTML, CSS, and JavaScript, so there won't be ui aesthetics if you write your own theme in the case that you couldn't find a right theme that fit Hyprland. You can find other greeter here: https://wiki.archlinux.org/title/LightDM

I checked it and yep it is nice. 
but it also renders using x11.
it can start a Wayland session but to render itself it uses Xorg-server.

**Comment by 875d** [comment]
I recently tested LightDM and it was unable to start a Hyprland session.

**Comment by khaneliman** [comment]
> I recently tested LightDM and it was unable to start a Hyprland session.

Yeah, I didn't try long but I used to use lightdm when I mained AwesomeWM. When I was first setting up Hyprland it wouldn't launch it and I switched to sddm-git.

**Comment by Sunderland93** [comment]
Try greetd

**Comment by lepz0r** [comment]
> Try greetd

I tried greetd but it doesn't support user switching

**Comment by vaxerski** [comment]
hyprdm not planned

**Comment by niksingh710** [comment]
> hyprdm not planned

wat bout hyprlock? i guess it is quite needed as then it may solve lock issue on multimonitor and may have some awesome plugins........

**Comment by vaxerski** [comment]
nope

**Comment by hughesjs** [comment]
@vaxerski - What if someone else wrote it? Just gauging whether it's something the core team don't want to implement or if you just don't want it as part of the project altogether?

**Comment by vaxerski** [comment]
if you want to write it it's your choice, lol. I just don't want to do it myself.

**Comment by guttermonk** [comment]
Can anyone using Hyprland & NixOS recommend a login manager? On [this thread](https://discourse.nixos.org/t/how-to-use-ly-display-manager/13753/2), they said that ly doesn't respect the config files. Sounds like greetd or it's forks may be my best option? A hyprland specific login manager that matched hyprlock would be nice.

**Comment by hughesjs** [comment]
> Can anyone using Hyprland & NixOS recommend a login manager? On [this thread](https://discourse.nixos.org/t/how-to-use-ly-display-manager/13753/2), they said that ly doesn't respect the config files. Sounds like greetd or it's forks may be my best option? A hyprland specific login manager that matched hyprlock would be nice.

SDDM is functional. That's about the best endorsement I can give it.

**Comment by khaneliman** [comment]
> Can anyone using Hyprland & NixOS recommend a login manager? On [this thread](https://discourse.nixos.org/t/how-to-use-ly-display-manager/13753/2), they said that ly doesn't respect the config files. Sounds like greetd or it's forks may be my best option? A hyprland specific login manager that matched hyprlock would be nice.

Have used regreet with greetd and sddm. I’ve got some examples of configuration in my repo

**Comment by guttermonk** [comment]
tuigreet looks pretty cool and works well, but I get some code spam between when I log in and hyprland loads. Any way to hide that?

A matching, wayland native, login manager and lockscreen would still be cool.

**Comment by lepz0r** [comment]
lightdm works here but you must add this script to your `~/.xprofile` as in canonical/lightdm#63 & WayfireWM/wayfire#1479

```
if [ -n "$XDG_VTNR" ] ; then
    echo "Waiting for VT $XDG_VTNR:"
    for ((i=0;i<100;i++)) ; do
      CURRENT="$(</sys/devices/virtual/tty/tty0/active)" 
      echo  "  $(date +%s.%N) using $CURRENT"
      if [[ "$CURRENT" = "tty$XDG_VTNR" ]]; then
          break
      fi
      sleep 0.01
    done 
fi
```

**Comment by mock1328** [comment]
@khaneliman do you have numlock enabled, when hyprland is used with regreet? After hyprland's `0.40.x` updates it's not enabling by default for me any more. I have to press numlock button twice for it ti enable, as if it was enabled, but not really.

**Comment by khaneliman** [comment]
> @khaneliman do you have numlock enabled, when hyprland is used with regreet? After hyprland's `0.40.x` updates it's not enabling by default for me any more. I have to press numlock button twice for it ti enable, as if it was enabled, but not really.

I don’t know if I used it with the new update. You can try adding the numlock setting for hyprland to that config though and see if it helps. Numlock_by_default I think in input

**Comment by mock1328** [comment]
Yeah, I've been using below, relly simple config for quite some time, and it worked before `0.41.0` (sorry, typo in my prev message, it's 0.41, not 0.40):

```
exec-once = regreet; hyprctl dispatch exit

input {
    kb_layout = us
    numlock_by_default = true
}
```
