### ISSUE TITLE
Switching desktops will always map a letter or number

### ISSUE THREAD

**Issue by sonako0122** [hyprwm/Hyprland#1295]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.
Like this, I switched a desktop and it kept mapping 2
But he seems to be effective only for a software called icalingua，icalingua is a derivative of China's QQ，This affects my normal use
Oh, opening a software on this desktop and then switching to icalingua will always map
Thanks to the author, I really have no idea

![16723209536332049926249](https://user-images.githubusercontent.com/79687386/209961376-e93d7125-12f4-4c3b-9c00-8455ce0f61ad.jpg)

**Comment by MengE1789** [comment]
Oh yes I don't have this problem in wayfire

**Comment by MengE1789** [comment]
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10319874/hyprland.log)

**Comment by MengE1789** [comment]
I found that not only my icalingua has this problem, but many programs running in xwayland have this problem

**Comment by vaxerski** [comment]
I understand a grand total of nothing from what you're saying

**Comment by mustardfrog** [comment]
@MengE1789 
My man, What is the problem exactly. You are not providing any useful information.

**Comment by sonako0122** [comment]
> Please consult the issue guidelines at https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md BEFORE submitting. Like this, I switched a desktop and it kept mapping 2 But he seems to be effective only for a software called icalingua，icalingua is a derivative of China's QQ，This affects my normal use Oh, opening a software on this desktop and then switching to icalingua will always map Thanks to the author, I really have no idea
> 
> ![16723209536332049926249](https://user-images.githubusercontent.com/79687386/209961376-e93d7125-12f4-4c3b-9c00-8455ce0f61ad.jpg)
