### ISSUE TITLE
XWayland is completely gone

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#1297]
After a recent update, I can no longer launch any XWayland program. The `DISPLAY` environment variable is not set.
Here are the log lines from Hyprland containing `xwayland`:
```
$ cat /tmp/hypr/0baef17a02529dd5fc58eee497737ac28df160c1_1672394658/hyprlandd.log | grep -i xway
[LOG] Creating the XWaylandManager!
[LOG] Registered signal for owner de840: de880 -> 95e3c0 (owner: XWayland Manager)
[LOG] Registered signal for owner de840: de890 -> 95e3e0 (owner: XWayland Manager)
[LOG] CHyprXWaylandManager started on display :0
```
I am running Hyprland locally built, with the hidpi patches applied. I observed that this issue still occurs when I don't run the `xprop` command that enabled XWayland scaling, so I don't think it is related.

**Comment by vaxerski** [comment]
doubt this is related to hyprland. Have you tried sway-git?

**Comment by TheSunCat** [comment]
I can confirm this is also happening in Sway (non-git). How can I debug this?

**Comment by vaxerski** [comment]
no clue and it ain't my problem then lol
