### ISSUE TITLE
Scaling in master layout is not rotating with layout

### ISSUE THREAD

**Issue by Mikmert** [hyprwm/Hyprland#1298]
To scale the master window you always drag to the right for bigger and to the left for smaller. This is true even if the master layout have been rotated. 

So if master is on top and slaves at the bottom of screen, you think that expanding master down would be dragging mouse down and dragging mouse up to contract master up. But instead mouse right expands master down, mouse left contract master up. The one slave you can scale are also strange as mouse up contract left and mouse down expands right. 

When master is on right everything feels reversed as dragging mouse right scales master left and dragging mouse right scales master left. But slave scaling feels correct.

Master bottom are also wrong and the problem exists with keybindings too.

Fix so that scaling movement always is the same way that the scaling expands or contract.

**Comment by vaxerski** [comment]
fixed in a91d0a374a6e0637da8844d5c2f905c4d661adf1
