### ISSUE TITLE
Master layout slaves are able to scale.

### ISSUE THREAD

**Issue by Mikmert** [hyprwm/Hyprland#1299]
In the wiki: 

> The right, “slave” windows will always be split uniformly. You cannot change their size.

But in reality you can change their size.
This is sometimes helpful as you maybe have three windows and just want to read something from one slave as you work in master. If this scaling behavior should stay all slaves should be scalable. Right now the last slave in the stack is not scalable but all the others are.

**Comment by vaxerski** [comment]
forgot to edit that. Feel free to make a pr to the wiki

**Comment by Mikmert** [comment]
There are still the problem with the last slave in the stack can not be used for scaling.
So if you want to scale window C you think you can use the mouse to drag window C up but nothing happens.
So to scale C you have to drag the window B up to get window C bigger.
```
+-----------+-----------+
|           |     B     |
|           |           |
|     A     +-----------+
|           |           |
|           |     C     |
+-----------+-----------+
```

Wanted result:
```
+-----------+-----------+
|           |     B     |
|           +-----------+
|     A     |           |
|           |     C     |
|           |           |
+-----------+-----------+
```

**Comment by vaxerski** [comment]
yeah, that's cuz the system is quite simple. It's not really a big issue tho.

**Comment by Mikmert** [comment]
No not really it is not that much of a problem as it works fine. It is just a detail.
