### ISSUE TITLE
[NVIDIA] Hyprland fails to appear, but the log shows no errors

### ISSUE THREAD

**Issue by TheLastTeapot** [hyprwm/Hyprland#1302]
This has only happened since I installed the Nvidia driver and followed all the instructions on the wiki. Launching from SDDM and tty have the same result. When I read the log there are no errors. This is definitely an Nvidia problem. Anybody have any idea what's going on here? One note: I am using nvidia-470xx-dkms instead of nvidia-dkms because my card is legacy (Nvidia GeForce GT 730).

**Comment by vaxerski** [comment]
We don't provide support for nvidia.

Also, afaik, 470 has no support for wayland

**Comment by JustSimplyKyle** [comment]
However, you could try joining the hyprland discord and ask for help there. No guarantees tho!
