### ISSUE TITLE
Monitor scaling should not affect how many "logical" pixels are created

### ISSUE THREAD

**Issue by a-priestley** [hyprwm/Hyprland#1303]
```
monitor=DP-1,1920x1080@60,0x0,0.8
monitor=DP-2,2560x1440@60,1920x0,1
```

The above config overlaps because of the scaling on DP-1. To fix it, you need to divide the x-position of DP-2 by the scaling factor of DP-1:

```
monitor=DP-2,2560x1440@60,2400x0,1
```

Can this calculation be done automatically?

**Comment by vaxerski** [comment]
no. The core wayland spec does layout calculations by logical pixels and Hyprland physically cannot _guess_ what you mean by the values you input.
