### ISSUE TITLE
[XWAYLAND] XWayland context menus don't show after the first one

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#1306]
When using Java Swing programs such as GeoGebra 5 Classic (`geogebra-5` in the AUR), context menus only open the first time any menu is opened. After that, none shows until I restart the program. This occurs regardless of fullscreen, tiled, or floating status.

I have attached a video demonstrating the issue:
https://user-images.githubusercontent.com/44881120/210221162-fa18546b-4f85-4d45-9211-d130831e2b3e.mp4

Note that I am using the hidpi patches, though I don't think it should affect this.

**Comment by TheSunCat** [comment]
Observing the output of `hyprctl clients`, a window is created for the first context menu, but then no new windows are created after that for other context menus (hence they don't appear).

**Comment by TheSunCat** [comment]
This also occurs with Krita (which hard-disables Wayland support for some reason), so I'm changing the issue title to reflect that.

**Comment by TheSunCat** [comment]
I have confirmed this occurs only with the hidpi patches.

**Comment by vaxerski** [comment]
then it's not a hl issue?

**Comment by TheSunCat** [comment]
Well, it does not occur on Sway with the same patches, so I think it would be a Hyprland issue.

**Comment by TheSunCat** [comment]
I have collected logs for opening and closing the first context menu in Geogebra with both the hidpi patches and without. 
[hpyrlog_working.txt](https://github.com/hyprwm/Hyprland/files/10347693/hpyrlog_working.txt)
[hpyrlog_borked.txt](https://github.com/hyprwm/Hyprland/files/10347694/hpyrlog.txt)

I noticed the borked log has an extra line:
```
[LOG] Cleanup: destroyed a window
```

**Comment by vaxerski** [comment]
cleanup will only destroy a window if the `destroy` event had been emitted.

In that case, it's purely an xwayland or wlroots issue.

**Comment by TheSunCat** [comment]
I don't understand how you can be certain this is not a Hyprland issue since this doesn't happen in Sway with the same xwayland library. This is reproducible with any Qt or Swing app running in Xwayland (`QT_QPA_PLATFORM=xcb kvantummanager`, for example).

After opening and closing the menu once, then trying to open it again, the app behaves as if the context menu was opened, and sometimes you can even click the first element if you get lucky, or navigate with arrow keys. It just isn't rendered (and absolutely nothing is logged by Hyprlannd).
This is reproducible with the following patches to wlroots and xwayland respectively:

## wlroots
[hidpi.patch](https://github.com/hyprwm/Hyprland/files/10347961/hidpi.patch.txt)
[crash_revert.patch](https://github.com/hyprwm/Hyprland/files/10347963/crash_revert.patch.txt) (revert this one)

## xwayland
[733.patch](https://github.com/hyprwm/Hyprland/files/10347973/733.patch.txt)

**Comment by vaxerski** [comment]
are you testing sway or sway-git?

sway uses a much older wlroots rev.

**Comment by TheSunCat** [comment]
Hmm, I am indeed using `sway`. So this must be a wlroots issue then, as Sway can use the xwayland hidpi package fine. I'd test with `swat-git`, alas I appear unable to install it:
```
$ paru -S sway-git
resolving dependencies...
looking for conflicting packages...
:: sway-git and sway are in conflict. Remove sway? [y/N] y
:: wlroots-git and wlroots are in conflict. Remove wlroots? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing wlroots breaks dependency 'libwlroots.so=10-64' required by cage
:: removing wlroots breaks dependency 'libwlroots.so=10-64' required by gamescope
:: removing wlroots breaks dependency 'wlroots<0.16' required by wayfire
```
If sway-git exhibits this issue, then indeed it is not a Hyprland issue.

**Comment by vaxerski** [comment]
idk if it does. I can test it tomorrow. Ping me on discord plox

**Comment by vaxerski** [comment]
confirmed same happens on sway

xwayland / wlroots issue (most likely xwayland, as @fufexan said he doesnt have the issue and I assume he's on latest git of hl (so wlroots is the same as us)
