### ISSUE TITLE
[XWAYLAND] Certain games are broken in fullscreen

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#1308]
When playing Don't Starve Together (native Linux SDL game) on Hyprland (XWayland), it does not update the bottom left quadrant of the screen at all from what it was displaying when it first went fullscreen. I can force it to update once by opening the screenshot tool, which I assume is causing the full display to update once. Mouse input is also wrong, transforming the top left quadrant to the area of the full screen. None of these issues occur if I play the game windowed.
If I launch the game in Gamescope, the refresh issue is gone but my cursor is still constrained to the top left quadrant of the window, but the input is not mapped to the game at all. 

Please note that I am using the hidpi patches for XWayland.

**Comment by Estebiu** [comment]
Did you try running the game in wayland? As sdl2 has experimental support for wayland, you can force it with "SDL_VIDEODRIVER=wayland". But keep in mind that is experimental and not all games work fine with it. 

That said, I'm also having some problems with SDL games (running on wayland, didn't test with xwayland). For example, if I put osu!lazer in fullscreen, only the top left quadrant of the screen gets updated, the other 3 quadrants remain the same. Plus touch input for the whole window (even if it's not fullscreen) gets sent only to the top quadrant of the game's window.

**Comment by TheSunCat** [comment]
That sounds like the same issue I'm having yeah. Forcing SDL wayland instantly crashes the game saying that the wayland platform is invalid. I think it packages an ancient sdl2 version with no Wayland support unfortunately.

**Comment by Froggo8311** [comment]
I have DST native running just fine on Hyprland. Now with that being said, I think I'm on the mainstream wayland and not the hidpi branch.

**Comment by TheSunCat** [comment]
I cannot reproduce this anymore with `force_zero_scaling`, so I assume it was a bug with the old hidpi patches. Closing :)
