### ISSUE TITLE
[XWAYLAND] Popups have no border

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#1309]
When using XWayland programs, it is difficult to tell popup windows apart from the main program as they have no borders. This is not an issue in native Wayland programs. I have attached a screenshot of the issue occurring in a WINE program (please excuse my mouse art):
![image](https://user-images.githubusercontent.com/44881120/210222223-69040c74-2aa2-4d43-a954-1a7e62bb2f97.png)

**Comment by vaxerski** [comment]
expected as some xwayland windows request for there not to be any

**Comment by TheSunCat** [comment]
Can I override this? It is *every* XWayland popup and it makes it hard to use.

**Comment by vaxerski** [comment]
I can add an opt but remember in xwayland _a lot_ of things are windows.

**Comment by TheSunCat** [comment]
p a i n. I wonder how Sway handles this?

**Comment by vaxerski** [comment]
probably detects them differently. It's a fiddly thing due to how x11 works

**Comment by TheSunCat** [comment]
Hrm fair. I would appreciate a windowrule or option to try to detect these better if that's not too hard to implement. Also allowing these to be animated like popups are on Wayland would be epic (since XWayland popups *always* fade in).
