### ISSUE TITLE
Crash when disconnecting certain input devices

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#1310]
When unplugging a Digispark USB dev board or closing the AntiMicroX (available in AUR) input emulation program, Hyprland instantly and reproducibly crashes. I have obtained a core dump:
[asan.8897.log](https://github.com/hyprwm/Hyprland/files/10331146/asan.8897.log)

**Comment by vaxerski** [comment]
above memory issue fixed in 9ba93f4b0a56a8cec225b7719885da8bbfab1624

re-run to check if there isn't any other, as the above did not _have to_ lead to a crash.

**Comment by TheSunCat** [comment]
eyy it no longer crashes, thanks! I cannot test with the Digispark for a couple days, but AntiMicroX no longer crashes Hyprland on close. It does slightly lag the mouse, but that might be the program's fault. I'll close the issue since it seemed to be the same, and reopen if it happens again.
