### ISSUE TITLE
Possibility to execute Hyprland with specified config file

### ISSUE THREAD

**Issue by JeanSchoeller** [hyprwm/Hyprland#1314]
First, thank for the hard work, absolutely amazing.

**What?**

While trying to get greetd to run with Hyprland as the Wayland compositor (which works by the way but kind of useless without the ability to specify a config files to run the greeters), I realized there is no way, at least that I know of, that one can lunch the compositor while specifying a written config file, for example:

`Hyprland --config /path/to/config/file`

**Why?**

Because I love Hyprland and want to run it in my greetd file with tons of awesome features for the login daemon. Also if people might want to try out multiple config files.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/210408573-15ff59dc-e1bd-4ce2-9769-e75ea31bb21d.png)

reading hard
