### ISSUE TITLE
[FR] stayfocused window rule

### ISSUE THREAD

**Issue by 875d** [hyprwm/Hyprland#1317]
I request a window rule to force a window to stay focused.

A window subject to the rule will never lose focus, not even when the mouse is moved, until it is closed.

It would be useful for password managers, when they pop up asking for password: if you move the mouse, the password will end up on the underlying window....

**Comment by vaxerski** [comment]
why did you add a "france" tag? (the [FR] thing)

**Comment by 875d** [comment]
> why did you add a "france" tag? (the [FR] thing)

c'est la vie

**Comment by api-haus** [comment]
This is so much needed.

Every kind of popup window has to overtake focus and keep it until it is closed.

Examples: App Launchers, "Refactor" popups in IDE's, Confirmation dialogs, etc.

This is a must have feature for streamlining user experience for all the people who aren't yet ready to fully adopt the terminal-based IDE's and interfaces.

**Comment by rszyma** [comment]
@vaxerski any plans for this in the near future? The workaround suggested by api-haus to fullscreen a window just don't work well with app launchers e.g. rofi or other floating windows that popup to prompt.

**Comment by vaxerski** [comment]
added in 18f9fb5e0fdb3fdc1aebe61b3c589bc23aed1e9f

heck off will ya
