### ISSUE TITLE
Keybind modifiers block subset keybinds

### ISSUE THREAD

**Issue by veRYANgry** [hyprwm/Hyprland#1320]
This is possibly by design, but I'm not sure if it is.

Pressing modifier like CTRL will stop a keybind to a single key. For example I have this:
```
bindl=,0xff14,exec,pactl set-source-mute @DEFAULT_SOURCE@ false
bindlr=,0xff14,exec,pactl set-source-mute @DEFAULT_SOURCE@ true
```
Pressing modifiers or sometimes other keys while using Scroll lock for global push to talk will sometimes fail to run the second or first command during normal use.

Please help me decide if this is a bug or not and/or how to fix it.
Thanks!

**Comment by vaxerski** [comment]
not a bug, hyprland keybinds are precise. ctrl+a != a
