### ISSUE TITLE
Bordercolor rule no longer working

### ISSUE THREAD

**Issue by gnusenpai** [hyprwm/Hyprland#1321]
**Steps to reproduce:**
Add the following rule to hyprland config: `windowrulev2 = bordercolor rgba(ff0066ee), xwayland: 1`

**Expected outcome:**
Matching windows should have a pink-red border color. In this case, all XWayland windows.
![working](https://user-images.githubusercontent.com/7277686/210690816-5c45cbc8-6143-4178-9f7c-78d49a03845e.png)

**Noted outcome:**
Matching windows no longer have any active border color. The inactive border color seems to be working fine, at least with this rule.
![not-working](https://user-images.githubusercontent.com/7277686/210690957-a3f26db0-a48c-4a84-95ae-ca96e753119c.png)

This also applies with any `WINDOW` field. I did a git bisect and found that ddcae74e09ade4215da537791e10ee229e4e3f7d is when the issue started.

**Comment by vaxerski** [comment]
I'll carry on the full normalization soon, I've been telling myself.

Note to self: do it lazy ass

**Comment by vaxerski** [comment]
should be fixed with 96198dae55b1429449504e49065a10763b288431
