### ISSUE TITLE
New crash: disabling monitor twice crashes Hyprland after first toggle. Happens since at least ddcae74

### ISSUE THREAD

**Issue by bklaase** [hyprwm/Hyprland#1324]
When running version: ddcae74e09ade4215da537791e10ee229e4e3f7d This issue is not present.
A commit between then and the 2.0 milestone seems to introduce it. Perhaps: a33ecec61ef4c5749a17f52b15f0e0d0722b1f3d. Will try if you say it helps you.

### Steps to reproduce
1. Start hyperland with external monitor attached. Mine is called `LVDS-1`.
2. disable laptop/internal screen with `hyprctl keyword monitor LVDS-1,disable`
3. enable again with: `hyprctl keyword monitor LVDS-1,pref,auto,auto`
4. disable again with `hyprctl keyword monitor LVDS-1,disable`

### Expected outcome
Hyperland simply disables the monitor again.

### Noted outcome
Hyprland crashes everytime on the second disable, never the first.

### Log / Coredump
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10358927/hyprland.log)
[coredump.zip](https://github.com/hyprwm/Hyprland/files/10358943/coredump.zip)

**Comment by bklaase** [comment]
Was curious, and can confirm it was definitely introduced by https://github.com/hyprwm/Hyprland/commit/a33ecec61ef4c5749a17f52b15f0e0d0722b1f3d.

**Comment by vaxerski** [comment]
[patch.diff.txt](https://github.com/hyprwm/Hyprland/files/10360044/patch.diff.txt)

can you try this patch

**Comment by bklaase** [comment]
It doesn't unfortunately.

as for
> coredump taken wrong, see issue guidelines.

I followed [this](https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md#obtaining-the-hyprland-coredump).  
Indeed not the debugbuild coredump part. you require it now that patch didn't work?

**Comment by bklaase** [comment]
Ah I see, is this what you are looking for?  
[trace.txt](https://github.com/hyprwm/Hyprland/files/10360357/trace.txt)

**Comment by vaxerski** [comment]
thanks yea. Can you try the above patch?

**Comment by bklaase** [comment]
This was with that patch already applied!

**Comment by vaxerski** [comment]
oh, huh.

**Comment by vaxerski** [comment]
[patch.diff.txt](https://github.com/hyprwm/Hyprland/files/10360498/patch.diff.txt)

how about this?

**Comment by bklaase** [comment]
I applied this *over* the other one:  
https://github.com/bklaase/Hyprland/tree/fix/monitor_remove_crashes

this second patch resolved the issue!

**Comment by vaxerski** [comment]
464dd79246eedb0da00514b5b9c68a8969b47df0
