### ISSUE TITLE
`blur_new_optimizations=1` causes flashing

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1325]
1. open an xwayland window(the example here being webcord)
2. have a eww bar open
3. turn off your internet
4. webcord started flashing
https://github.com/hyprwm/Hyprland/commit/a163ca92377a56c196222a48c0a5676a7bb4ac3b
this *might* be the commit that introduced it, haven't got time to thoroughly check tho

**Comment by vaxerski** [comment]
can't repro.

Is the window opaque?

Define flashing. What is flashing? webcord? the blurred background?

`git bisect` would be useful.

**Comment by JustSimplyKyle** [comment]
https://0x0.st/oRdv.mkv

**Comment by JustSimplyKyle** [comment]
After doing a git bisect, I can indeed confirm that https://github.com/hyprwm/Hyprland/commit/a163ca92377a56c196222a48c0a5676a7bb4ac3b this is the commit that introduced the bug

**Comment by vaxerski** [comment]
should be fixed with 2a5ae435e19e5ccc3a4d989497f062614307f104

**Comment by JustSimplyKyle** [comment]
It is fixed! Thanks.
