### ISSUE TITLE
layoutmsg cycleprev with Master layout not working

### ISSUE THREAD

**Issue by pierfier** [hyprwm/Hyprland#1326]
Hello, I have been having an issue with binding keys for cycling the focus of windows within the master layout. Cycling to the next window with '`bind = %mainMod, J, layoutmsg, cyclenext` works just fine. My binding for cycling to the previous window is `bind = %mainMod, K, layoutmsg, cycleprev`, but for some reason it does the same as cyclenext. I then tried to use the regular Dispatcher method with `bind = %mainMod, J, cyclenext`  and `bind = %mainMod, K, cyclenext, prev`, which worked unless you swapped windows around. In this case cycling was done only in the original order, not in the stack order.

I may not understand Dispatchers super well, so any help would be greatly appreciated!

**Comment by vaxerski** [comment]
use the master layoutmsg to respect the stack
