### ISSUE TITLE
monitorremoved ipc never triggers 

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/Hyprland#1327]
I'm using the latest git version of Hyprland with ArchLinux and have everything working. My last job was to add a hook to detect and action on both monitoradded which works and monitorremoved which does not.
If I simply monitor the hooks by echoing $line it always shows `monitoradded>>HDMI-A-1` when I plug in the HDMI cable but never shows `monitorremoved>>HDMI-A-1`  when I unplug the HDMI cable. So I suspect it is a bug ??

**Comment by justinesmithies** [comment]
Ignore this sorry my mistake ;)

**Comment by vaxerski** [comment]
umm why closed

**Comment by justinesmithies** [comment]
My mistake sorry I jumped the gun. It works fine it was a numbers issue ;)

**Comment by vaxerski** [comment]
lol
