### ISSUE TITLE
Scaling settings for xwayland on hidpi monitor overwritten after a while

### ISSUE THREAD

**Issue by Bekaboo** [hyprwm/Hyprland#1328]
So I have a single 4k monitor, following the instruction on the wiki, I installed hyprland with patched xwayland and wlroots and set up the monitor and scaling in my config like this:

`~/.config/hypr/hyprland.conf`:

```conf
monitor = , 3840x2160@60, 0x0, 2
exec-once =xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
```

hyprland wrapper:

```bash
#!/usr/bin/env sh
# vim: ft=sh ts=4 sw=4 sts=4 et :

cd ~

export GDK_SCALE=2
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt5ct
export XCURSOR_SIZE=48
export XCURSOR_THEME=breeze_cursors
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

exec Hyprland
```

It works as expected, however after around 30 ~ 60s all xorg apps will spawn with giant UI. I suspect `_XWAYLAND_GLOBAL_OUTPUT_SCALE` is reset to 1 for some unknown reason, because after I run `xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2` again the issue is gone temporarily -- after a while the scaling factor is reset again and I have to manually set it to 2 once more.

I'm trying to find some workarounds like executing this command every time a new app is spawned via a hook or something like that, but haven't find a way to achieve that in Hyprland yet.

**Comment by vaxerski** [comment]
@fufexan 

hidpi patches are not officially supported, they're just a "this may work"

if you need any help, hit fuffie up on discord or anyone else who uses those.

**Comment by Bekaboo** [comment]
> @fufexan
> 
> hidpi patches are not officially supported, they're just a "this may work"
> 
> if you need any help, hit fuffie up on discord or anyone else who uses those.

Thanks for your reply! Hyprland is awesome, but the lack of hidpi support just keeps me away from it. Could I ask if there is a plane to add official hidpi support in the foreseeable future (1~2 years)?

**Comment by vaxerski** [comment]
unfortunately it's very much not up to us. As you can see, all the patches are to wlroots and xwayland. Hyprland has nothing to do with this.

**Comment by Bekaboo** [comment]
Alright. Last question, can I add a hook or something like that on Hyprland to execute a command before I execute an application?
I manage to solve the issue for Chrome by executing `xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2` every time before I launch it through the shortcut `super+g`:

```conf
bind = $super, g, exec, xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
bind = $super, g, exec, google-chrome-stable
```

But in this way I have to manually set it up for every app that use xwayland; yet it does not apply to apps that are not launched through a shortcut, for example, apps launched through wofi.

I searched through the Hyprland Wiki hoping to find some mechanism similar to a hook, but with no result.
So I would like to ask if it is possible to do this on Hyprland?

**Comment by fufexan** [comment]
There's no hook mechanism.

As for chrome, you can launch it in wayland mode with `chrome --ozone-platform=wayland`.

**Comment by Bekaboo** [comment]
It will be very helpful if we can add an `exec-before` option for window rules to mimic a hook.

> As for chrome, you can launch it in wayland mode with `chrome --ozone-platform=wayland`.

Thanks for your suggestion!
