### ISSUE TITLE
can t launch Hyprland, egl error 0x3001

### ISSUE THREAD

**Issue by Halfarne** [hyprwm/Hyprland#1329]
I can't launch Hyprland. After i launch script fór launching Hyprland, Some egl error pops with error 0x3001 egl initialize create screen ydevices
After that i Don t sebe it, because it IS too long.
Sorry for that a can't show sonething else, because my PC with it just don t work and i Don t had Time to try sonething other than finding the simmilar problems, bit i found nothing.

**Comment by mustardfrog** [comment]
What script did you use?
Can you launch from TTY with command: ```Hyprland```?
Try using a wayland login manager like ```sddm``` or ```gdm```

**Comment by Halfarne** [comment]
No i can t Launch IT with Hyprland
![P_20230107_102545_1](https://user-images.githubusercontent.com/100025715/211143739-4239c4fe-ef01-4bf1-af7d-1b2f5df7220e.jpg)
Sorry for the picture quality.

**Comment by vaxerski** [comment]
you're using an nvidia card. We do not provide support for nvidia.

Read the nvidia wiki page as you probably did not apply any of the required tweaks for wayland
