### ISSUE TITLE
Actions on key release

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#133]
Could we have a way of binding actions to key release like a menu appearing when you press super but window focus changing if you press super + h it would also be really nice if we could bind more then 2 keys eg super + shift + e

**Comment by vaxerski** [comment]
you can do super + shift, it's documented in the wiki and in the example config, use `SUPERSHIFT` for a mod.

on key release, so basically keybind conflict detection? doable.

**Comment by godalming123** [comment]
Yes or just a manual option for 1 or 0 at end of keybind definition if a keybind should be activated on release or as it is being pressed
