### ISSUE TITLE
Floating windows when moved to another monitor leave artifact /copy of old window

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/Hyprland#1331]
I'm using latest git master under Arch Linux.
If I spawn MPV I have it setup to open floating at a fixed size and position. If I move it to my other monitor it leaves behind a frozen copy of that window on the previous monitor. It will only disappear if I move the cursor out of the window that was moved IE changing focus. The same happens for the scratchpad if I open the scratchpad and move a window to another screen it leaves weird shading on the previous screen until the cursor is moved / focus changed.

**Comment by vaxerski** [comment]
check with 9c77415cda40eb334dd9306c504c0003dc14b53f

**Comment by justinesmithies** [comment]
No It still leaves a transparent grey area around where the window was say opened above my browser on moving the window to another group using key binds until I move the mouse. If the group is blanl and I open my scratchpad containing just a terminal them with key binds move it to another screen and group the window it leaves is left coloured in a transparent grey around where the window was and around my eww bar until i change groups with the mouse or keybinds.

**Comment by vaxerski** [comment]
can you video document this occurrence

**Comment by justinesmithies** [comment]
![PXL_20230115_161528754](https://user-images.githubusercontent.com/1571498/212552721-e854de7b-8c02-4d5a-8e1e-ac4f03ae4d5b.jpg)
![PXL_20230115_161505733](https://user-images.githubusercontent.com/1571498/212552725-c2c3ced8-d775-4ecb-884f-a124710d4b06.jpg)

Hopefully you can see first I have my terminal on the laptop screen id0 then with key binds move it into the scratchpad. I then move focus to my fixed screen id1 and the open the scratchpad. I then proceed to shift mod 2 to move it back yo group 2 where it came from on the laptop screen id0. I'm then left with the artifacts as seen until I move the mouse or change focus. Happens with any apps.

**Comment by vaxerski** [comment]
ping me please after the 22nd of january, cant test multimon stuff atm

**Comment by justinesmithies** [comment]
No problem

**Comment by justinesmithies** [comment]
@vaxerski You said to ping after the 22nd ref the above issue.

**Comment by vaxerski** [comment]
I still can't repro. A video would be useful.

**Comment by justinesmithies** [comment]
Very strange as I tried this yesterday again and it still produced the issue but today after updates I can no longer make this happen so I'm happy to close this now and thanks anyway ;)
