### ISSUE TITLE
No blur on semi-transparent electron app

### ISSUE THREAD

**Issue by KZDKM** [hyprwm/Hyprland#1332]
For those who are not familiar with the app, its [Obsidian.md](obsidian.md), a electron-based note-taking app (proprietary only)
- Step to reproduce
    - Launch Obsidian.md with a transparent theme
- Expected outcome
    - Blur is applied to Obsidian
- Notified outcome
    - No blur is applied
    - ![2023-01-07-170507_screenshot](https://user-images.githubusercontent.com/41317840/211142834-1f4a29bb-24ac-4b87-b57f-cb64a3490880.png)
- Temporary workaround
    - By overriding window opacity so that A!=1, the blur is applied
    - `windowrule = opacity 0.99, obsidian`
    - ![2023-01-07-170929_screenshot](https://user-images.githubusercontent.com/41317840/211142978-6841a2f8-da2d-4836-858b-c79ab5b99987.png)

Not a big problem for me now because the opacity 0.99 hack works, but I think there might be a bug that affects the blurring of other semi-transparent electron apps so I figured I should report on it anyways.

The app is not running via XWayland. Also worth noting that translucency is not supported by Obsidian on linux, I'm editing the theme css file so that the windows becomes transparent. 

I'm not familiar with the c++ API, but I'm guessing that its because the pWindow returns alpha value of 1, but it should still be handled correctly because of `/src/render/OpenGL.cpp:windowShouldBeBlurred` function? specifically:
```c++ 
if (!pixman_region32_not_empty(&inverseOpaque)) {
```
which I think is there to handle semi-transparent windows?

Any Ideas? Thanks!

**Comment by vaxerski** [comment]
most likely obsidian reports a fully opaque window when in reality it is not.

Are you launching it in native wayland?

**Comment by KZDKM** [comment]
XWayland just dont allow the app to be transparent at all, and it is blurry as I use 2x scaling.

**Comment by vaxerski** [comment]
I've read your unixporn post.

Since obsidian never expects transparency, it sets an opaque region to be the full surface area. This means it reports to hyprland as fully opaque 

Not much I can do bout that. Guess you have to use your method.

**Comment by KZDKM** [comment]
Yeah that's what I've speculated, technically the app could have transparency but reports alpha=1. The biggest problem with my workaround is that the app dont get blur under full screen as the opacity is overridden. This could be an issue for other apps as well so a new forceblur window rule would come in handy?

**Comment by vaxerski** [comment]
making windowrules for opacity 3-arg could be an option (act/inact/full)
