### ISSUE TITLE
Artifacts if one window with blur moves under another window with blur

### ISSUE THREAD

**Issue by RedNekoderr** [hyprwm/Hyprland#1335]
- I opened 2 terminals with transparency and blur and moved the first one over the second one
- The upper terminal has artifacts from the movement of another terminal under it

If I focus on the top window the artifacts will disappear
"blur_new_optimizations = yes/no" does not affect the result

[Video](https://disk.yandex.ru/i/LIKtw6beiWDTPw)

**Comment by vaxerski** [comment]
does it go away if you disable shadows?

**Comment by RedNekoderr** [comment]
I have already turned off the shadows

**Comment by RedNekoderr** [comment]
> does it go away if you disable shadows?
At the time of writing this issue, I already had shadows disabled

**Comment by RedNekoderr** [comment]
> does it go away if you disable shadows?


At the time of writing this issue, I already had shadows disabled

**Comment by vaxerski** [comment]
alr

**Comment by vaxerski** [comment]
fixed in 50e106f2e60785126331eaf2a9c43595a2a768d4
