### ISSUE TITLE
"monitoradded" and "monitorremoved" don't get triggered most of the time

### ISSUE THREAD

**Issue by MonstrousOgre** [hyprwm/Hyprland#1341]
This is how I'm checking for events

`socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock`

All other events are working but `monitoradded` and `monitorremoved` only get triggered about 10% of the time.

Moreover if I plug in my external monitor after starting Hyprland, it usually doesn't output anything to the monitor. Likewise, if I disconnect the monitor after starting Hyprland, Hyprland still thinks it's connected. Only rarely am I able to hotplug without any issues.

I can't reproduce this 100% of the time since I don't know under what circumstances it is/isn't working.

**Comment by MonstrousOgre** [comment]
Update: It's happening less frequently now. Now it gets triggered most of the time but there are times where it doesn't. Sometimes it does take up to 20 seconds after connecting/disconnecting the monitor to get triggered though.

I should probably also mention that `nvidia-xconfig` lists the external monitor as connected even when Hyprland doesn't recognize it.

**Comment by vaxerski** [comment]
does this still happen?

**Comment by MonstrousOgre** [comment]
@vaxerski sorry for the late reply. I just checked and it doesn't seem to be happening now. Thanks!
