### ISSUE TITLE
gtk-layer-shell wrapper

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#1343]
Hey there,
coming from wayfire I really miss the background-view plugin. It takes any binary path, and moves it's window into the desktop background layer.
I did a lot of searching but could not find any comparable tool that would allow me to use the wallpaper-engine window as wallpaper.
Could you implement a wrapper that can do exactly that?
Thanks!

**Comment by vaxerski** [comment]
you mean something alongside `xwinwrap`?

**Comment by UltraBlackLinux** [comment]
yeah that would be perfect!

**Comment by vaxerski** [comment]
you got mpvpaper but I don't think there is one for wayland for general apps, dk what would be the better approach, a utility or just function in hl

**Comment by UltraBlackLinux** [comment]
a general utility would probably be best, but hyprland doesn't sacrifice visuals ;)

**Comment by vaxerski** [comment]
the problem with a general utility would be that in my opinion it'd have to be a separate wayland compositor. I don't think there's a simple way to do that otherwise. A compositor that launches the app, renders it, opens a LS and plops the contents onto the LS.

Maybe a project for some day.

**Comment by vaxerski** [comment]
now available as an official plugin: https://github.com/hyprwm/hyprland-plugins/tree/main/hyprwinwrap

**Comment by UltraBlackLinux** [comment]
thank you so much!
