### ISSUE TITLE
fcitx5 not work well under full screen

### ISSUE THREAD

**Issue by aimixsaka** [hyprwm/Hyprland#1353]
- **Brief**
in many places(alacritty,  and some  other electron applications), when i comes into full screen mode(use $Mod f in my bind) and type some chinese, there is  **no panel pops up**, while out of full screen mode, candidate box woks well.
(**in firefox and telegram fcitx5 works well even in  full screen mode**)

- **system**
  - fcitx5 5.0.21
  - fcitx5-gtk 5.0.21
  - fcitx5-chinese-addons 5.0.21
  - Hyprland build from [wiki one](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/#without-flakes)

- **additional**
  - tried both in nixos-unstable and archlinux with Hyprland, same issue(and have attempted  many different fcitx5  and fcitx5-gtk version)
  - **the same environment, and change from hyprland to sway, then fcitx5 work well under full screen**

**Comment by huge-pancake** [comment]
The same situation, fcitx5 panel doesn't appear in fullscreen window.

**Comment by TTtrace** [comment]
I ran into this problem too.

**Comment by Maxx-Gong** [comment]
I am also caught up in this problem, any solutions?

**Comment by lz37** [comment]
+1

**Comment by go0d1uck** [comment]
I try to fix the problem,I find a function named `setWindowFullscreen` in file **XWaylandManager.cpp**,
In the function,if the window is not a xwayland window,a function named `wlr_xdg_toplevel_set_fullscreen` will be called
to set the window to fullscreen,I guss the fcitx window will be covered, because the fullscreen window is top level.
but I don't know how to use wlroots library,I think the author can fix this bug quickly because he family with it.
@vaxerski

**Comment by vaxerski** [comment]
chihuahua

**Comment by Jedsek** [comment]
For coming people who have the same problem not solved:
I found that my fcitx5 works well in floating window, so I could resize my window into the same size of my screen(fullscreen).


```bash
#!/usr/bin/env bash
# floating_fullscreen.sh

hyprctl dispatch setfloating
hyprctl dispatch centerwindow
hyprctl dispatch moveactive exact 0 0
hyprctl dispatch resizeactive exact 100% 100%
```

```bash
bind = $mainMod, F, exec, sh $scripts_path/floating_fullscreen.sh
```

Now your fcitx5 could works well in alacritty/kitty...

:)

**Comment by wxqwinner** [comment]
vscode obsidian +1,floating_fullscreen.sh will shuffle the order of the windows, is there any other way to do this without using floating_fullscreen?
