### ISSUE TITLE
Allow a setting that disables workspace focus by mouse cursor movement only

### ISSUE THREAD

**Issue by krims0n32** [hyprwm/Hyprland#1354]
Currently when I move my mouse to another (empty) workspace, the workspace automatically gets the focus, meaning if I spawn an application, it opens on that workspace. This is not what I want, I only want workspace focus using the dispatcher or focusing an app on said workspace.

Am I correct this is currently not possible? If not, can you add an option for this please?

**Comment by vaxerski** [comment]
currently not possible, but what is your follow_mouse set to

**Comment by krims0n32** [comment]
I have set it to 0 currently but it doesn’t seem to matter what I set it to.

**Comment by Cozy64** [comment]
this is getting to me as well. i don't like how my cursor centers to any window i focus on. It gets annoying when i deal with floating windows. 
This needs to be addressed

**Comment by vaxerski** [comment]
@Cozy64 
> this is getting to me as well. i don't like how my cursor centers to any window i focus on. It gets annoying when i deal with floating windows.

`general:no_cursor_warps = true`

Unrelated to this issue. Maybe read the wiki next time.

**Comment by Cozy64** [comment]
> @Cozy64 
> > this is getting to me as well. i don't like how my cursor centers to any window i focus on. It gets annoying when i deal with floating windows.
> 
> `general:no_cursor_warps = true`
> 
> Unrelated to this issue. Maybe read the wiki next time.

Oh my bad, i misread the issue. And thx for letting me know that variable exists. I didn't see it before

**Comment by Pyxels** [comment]
I currently have the same issue as OP.
Some of the pain is reduced by disabling `no_cursor_warps` and having a low `cursor_inactive_timeout`, at least while using the keyboard only. Have you found another workaround in the meantime @krims0n32 ?

**Comment by krims0n32** [comment]
> I currently have the same issue as OP.
> Some of the pain is reduced by disabling `no_cursor_warps` and having a low `cursor_inactive_timeout`, at least while using the keyboard only. Have you found another workaround in the meantime @krims0n32 ?

Nope, I adapted to it. But a setting would still be welcome imo.

**Comment by krims0n32** [comment]
Following up on this, this setting does the job but now when I click (focus) a window on an unfocused monitor, the monitor doesn’t receive focus, only the window. 

Is this intended? I would expect clicking on a window on an unfocused monitor or maybe even a mouseclick anywhere on the workspace  would also focus the monitor.

**Comment by vaxerski** [comment]
fixed in 7d914cd427b36d5ec8acb06e415cdf2b846f1648

**Comment by krims0n32** [comment]
Damn you’re fast 😎

**Comment by krims0n32** [comment]
And what about a keybind that activates workspace 2 on a different monitor from the current one, it activates the workspace but doesn't focus the monitor it is on. Should I alter my binds for this so that it also focuses the monitor?

bind=SUPER,2,workspace,2

**Comment by vaxerski** [comment]
huh? it should focus the monitor. What do you mean by "doesn't focus the monitor it's on"?

**Comment by krims0n32** [comment]
E.g. I'm on workspace 4 on monitor 2. I use a keybind to activate workspace 2 on monitor 1. It activates workspace 2 but doesn't focus the monitor.

**Comment by vaxerski** [comment]
> What do you mean by "doesn't focus the monitor it's on"?

what happens that you dont expect to happen or vice versa?
