### ISSUE TITLE
Kodi renders offset

### ISSUE THREAD

**Issue by so1ar** [hyprwm/Hyprland#1356]
I am running hyprland in Archlinux. When I open kodi, the interface renders offset and stretched. Here is the screenshot

![1673352701_grim](https://user-images.githubusercontent.com/54471528/211556962-c41cf54d-892b-43cb-a508-a119e0279d06.png)

I came across similar issue in sway, but it seems have been fixed swaywm/sway#4366

**Comment by vaxerski** [comment]
it never got fixed in sway according to the above, but got fixed in whatever kodi is. You sure this doesnt occur on sway?

Also, the screenshot above looks fine to me... what is offset or stretched?

**Comment by so1ar** [comment]
> Also, the screenshot above looks fine to me... what is offset or stretched?

The bottom have been cut off and black bars appears in left and right (I'm using 1920x1080 display and the video is also 1920x1080).



> You sure this doesnt occur on sway?

I have tested on sway and it doesn't occur now.

**Comment by so1ar** [comment]
I have found a temporary solution, every time kodi have been opened, you need to disable and reenable fullscreen and go to video calibration, adjust the pixel ratio to 1.000.

![1673363606_grim](https://user-images.githubusercontent.com/54471528/211589228-0bdbf6d4-d407-4846-92e9-1825c68edc02.png)

**Comment by vaxerski** [comment]
is this still an issue?

**Comment by so1ar** [comment]
> is this still an issue?

Looks like it doesn't happens any more ;)
