### ISSUE TITLE
Quotes in binds causes invalid json

### ISSUE THREAD

**Issue by abs3ntdev** [hyprwm/Hyprland#1359]
Steps to reproduce:

Have binds in your config that contain double quotes such as:

bind = SUPER SHIFT CONTROL, S, exec, wf-recorder -g "$(slurp)" --audio -f ~/Videos/Screenrecord/record.mp4

Run hyprctl binds -j

Expected outcome
Result is valid json
Noted outcome
Result is not valid json due to unescaped double quotes

**Comment by vaxerski** [comment]
fixed in b24f066c4799ac66cc86c0962447c690519df8ef
