### ISSUE TITLE
Trying to go fullscreen while the window is maximized borks the application

### ISSUE THREAD

**Issue by paveloom** [hyprwm/Hyprland#1360]
Experiencing this with Firefox and `mpv`. Here's a recording:

https://user-images.githubusercontent.com/49961859/211806967-2adc3779-e3b3-4950-9854-54ed67c4db1f.mp4

**Comment by vaxerski** [comment]
fixed in 7afb7c85a74fe3beac634f124cba5a971cb54ca2
