### ISSUE TITLE
dmg tracking when config changed through socket

### ISSUE THREAD

**Issue by flick0** [hyprwm/Hyprland#1362]
new config values set through hyprctl dont update properly on screen
they show properly only when window is moved/resized

![fix_this_vaxr](https://user-images.githubusercontent.com/77581181/211859112-2bd64301-4a7c-40a5-9399-c749095b93ff.gif)

**Comment by vaxerski** [comment]
check with 8440aa3e9b2682261cf9608e553761ec4cf21654

**Comment by flick0** [comment]
rounding works properly now but border size and some other option still seems to be broken

https://user-images.githubusercontent.com/77581181/212064754-6c0c7707-fc9e-4b87-857c-88b8de5a2b60.mp4

**Comment by vaxerski** [comment]
cbd31ba481c5be65e015647851eef4b396869073 should address this

**Comment by flick0** [comment]
yep works now
