### ISSUE TITLE
4k Monitor not recognized in-game

### ISSUE THREAD

**Issue by MalariaKills** [hyprwm/Hyprland#1370]
Description: 4K Monitor is not recognized in-game (all-games) - Highest resolution monitor available is 2560x1440.

Config file monitor is set to: Monitor=DP-1, 3840x2160@144,0x0,1.5 and the general TWM respects this. As neofetch outputs the correct 3840x2160p.

Steps to reproduce: Load any game on Steam, or through a respective launcher. ie Minecraft Launcher

Expected outcome: Game should be either be in 4k (3840x2160) or in the video settings of said game; There should be the option to switch to 4k(3840x2160).

Noted outcome: Games launched only have 2560x1440 as the highest available resolution.

This bug does NOT crash hyprland. But seems like invalid behavior.

**Comment by vaxerski** [comment]
that's how xwayland works. Unless the game itself supports native wayland your best bet is turning the scaling down to 1x for gaming.

**Comment by MalariaKills** [comment]
@vaxerski I see - so does that mean I can make a window rule to open games at 1x scaling?

If that's the case - this fix will work perfectly

**Comment by vaxerski** [comment]
Nope, you can't. Scale is bound to an output, and we'd probably have to make a wlroots patch if we wanted to fake scales per-client.

You need to manually (or with a keybind) toggle the scale before you open the game.

**Comment by MalariaKills** [comment]
> Nope, you can't. Scale is bound to an output, and we'd probably have to make a wlroots patch if we wanted to fake scales per-client.
> 
> You need to manually (or with a keybind) toggle the scale before you open the game.

Thanks - I think I can come up with some creative solution for this with scripts. But it's good to know that's what caused it.
