### ISSUE TITLE
`mpv --force-window=immediate` maximizes mpv when video loads

### ISSUE THREAD

**Issue by maximbaz** [hyprwm/Hyprland#1375]
With commented out Hyprland config and no mpv config, I observe a weird behavior:

Run: `mpv --force-window=immediate somevideo.mp4`

Expected behavior: just like without the `--force-window`, mpv would open as a normal window, and start playing video.

Actual behavior: `--force-window` shows mpv window with black content inside, until video is loaded. The initial black mpv window is placed correctly, but as soon as the video renders, mpv gets.... maximized. I can unmaximize it using `fullscreen 1` and it would be placed correctly. With a local video file, this whole thing would happen nearly instantly, and with a link to e.g. youtube it could take a few seconds to buffer, so you would have a chance to see a correctly placed black window, which suddenly gets maximized once it begins to play. 

I realize it's a bit weird, please tell me that you are able to reproduce it 😁

**Comment by vaxerski** [comment]
I can repro but a maximize always should mean an app requested that explicitly.

**Comment by maximbaz** [comment]
Okay, interesting 🤔 Is there an easy way to verify that this is indeed what happens? If so, we should close this bug of course.

I found an [interesting link](https://github.com/mpv-player/mpv/issues/4198), suggesting that this indeed was the case in mpv, which was "apparently fixed some time ago" as per early 2021. The [docs for the `--force-window`](https://github.com/mpv-player/mpv/blob/73581d8fe68054103e2913bbac5f1629b1b0ce0c/etc/mpv.conf#L44-L47) mention that mpv will resize window, but they don't explicitly say that it will *maximize* it 🤔

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/blob/668d90c70093ce10816ba525780988e848f8d4af/src/events/Windows.cpp#L979-L999

p sure it's mpv.
