### ISSUE TITLE
Some apps take a long time to open when Hyprland first starts

### ISSUE THREAD

**Issue by fishe-tm** [hyprwm/Hyprland#1376]
Hello!
I have an issue where apps like firefox and nwg-panel take somewhere around 20 seconds to load when hyprland first starts. I have seen the FAQ but the solution doesn't seem to work for me.

Just adding `exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP` does nothing. I then put the script below it into a file and added it to the config as an `exec-once` line in the config, both before and after the dbus line. This didn't work.

I then tried to make my own script, which is as follows:
```
#!/bin/bash
killall xdg-desktop-portal-wlr &
killall xdg-desktop-portal &
dbus-run-session Hyprland &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
/usr/libexec/xdg-desktop-portal &
/usr/libexec/xdg-desktop-portal-wlr &
```
I used this to launch the window manager from TTY.
However, it still is not working and it still takes 20sec for nwg-panel and firefox to load.
What should I do?

**Comment by vaxerski** [comment]
check the logs of the portals. Maybe they crash?

**Comment by fishe-tm** [comment]
it seems that xdg-desktop-portal-wlr crashes, with the message `2023/01/13 16:07:53 [ERROR] - dbus: failed to connect to user bus: No such file or directory`

**Comment by tchofy** [comment]
I had an issue with a stray gnome-keyring-daemon on my install, for me it was slowing firefox and virt-manager. Fixed it by removing gnome-keyring since I was done with gnome and didn't use it for anything else.
[Also this blog post is worth a read,](https://utcc.utoronto.ca/~cks/space/blog/linux/XdgDesktopPortalSlownessWhy) it's where I found out about my issue.

**Comment by fishe-tm** [comment]
`gnome-keyring` isn't installed on my system, but it's good to know that it's a potential cause.

**Comment by drishal** [comment]
try xdg portal hyprland once https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/
Works absolutely fine 
I wonder though if it can be used with other wlroots based WMs like qtile

**Comment by vaxerski** [comment]
yes it can. The hyprland- functions will be disabled though (e.g. window sharing) unless the compositor supports the adequate hyprland- protocol

**Comment by drishal** [comment]
> yes it can. The hyprland- functions will be disabled though (e.g. window sharing) unless the compositor supports the adequate hyprland- protocol

Ah makes sense

**Comment by fishe-tm** [comment]
xdg-desktop-portal-hyprland was exactly what I needed! I installed it and put the following in my hyprland config:
```
exec-once=/home/fishe/bin/hypr
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```

`bin/hypr` is as follows:
```
#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/libexec/xdg-desktop-portal &
```

With this, panel and firefox show up in around 2 seconds instead of 20. Thanks so much!

**Comment by adamnejm** [comment]
I wasn't really facing issues with GTK apps, but QT.
Example: Dolphin starts normally, but when I open any file from within Dolphin, it freezes for 20 seconds and only then opens the file.

`dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`
didn't resolve my issue, the following command did however:
`systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`

**Comment by tchofy** [comment]
> I wasn't really facing issues with GTK apps, but QT. Example: Dolphin starts normally, but when I open any file from within Dolphin, it freezes for 20 seconds and only then opens the file.
> 
> `dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP` didn't resolve my issue, the following command did however: `systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`

Had that issue with Kate and sometimes Dolphin as well, Adding `export $(dbus-launch)` to my hyprland wrapper fixed it.

**Comment by exbotanical** [comment]
> systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

Same. Thunar was taking about 30s to start even with the fixes recommended on the Hypr FAQ. `systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP` was the only thing that worked.

**Comment by vincentaxhe** [comment]
> # exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = /usr/local/bin/hyprdelayfix.sh

After try above ways from hyprland wiki and issue ,none of them is the right solution, I still suffer two minutes long waiting waybar to show, 30s to thunar to show, but add export $(dbus-launch) into a Hyprland launcher solve the problem, that reminds me the bspwm.desktop provided by manjaro-bspwm , so I try `Exec=dbus-launch --sh-syntax --exit-with-session Hyprland` in hyprland.desktop in wayland-session. It worked! all back to normal. Hyprland should tell everyone that is the right way to launch Hyprland.

**Comment by vincentaxhe** [comment]
> # exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> # exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> # exec-once = /usr/local/bin/hyprdelayfix.sh

After try above ways from hyprland wiki and issue ,none of them is the right solution, I still suffer two minutes long waiting waybar to show, 30s to thunar to show, but add export $(dbus-launch) into a Hyprland launcher solve the problem, that reminds me the bspwm.desktop provided by manjaro-bspwm , so I try `Exec=dbus-launch --sh-syntax --exit-with-session Hyprland` in hyprland.desktop in wayland-session. It worked! all back to normal. Hyprland should tell everyone that is the right way to launch Hyprland.

**Comment by eljejer** [comment]
> try xdg portal hyprland once https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/ Works absolutely fine I wonder though if it can be used with other wlroots based WMs like qtile

https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

is renamed to 

https://wiki.hyprland.org/Useful-Utilities/xdg-desktop-portal-hyprland/

in the meantime

**Comment by timoleistner** [comment]
Same for me starting Hyprland with `dbus-launch --exit-with-session Hyprland` is the only thing that seems to work, can anyone explain why this is the case? (I'm trying to get my config right in home-manager but don't know how to start hyprland with dbus-launch this way, therefore I'm trying to find another way and also understand it a bit more)

**Comment by fufexan** [comment]
@timoleistner the HM module already has `exec-once = dbus-update-activation-environment --systemd <variables>`. Does this not work?

**Comment by timoleistner** [comment]
I tried this like documented by hyprland with 
``` 
systemd = {
  enable = true;
  variables = ["--all"];
};
```
I've also tried the following exec-once commands for hyprland one by one
```
"export $(dbus-launch)"
"dbus-launch"
"systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
"dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
```
AGS still takes 30s to launch

**Comment by fufexan** [comment]
How are you launching ags?

**Comment by timoleistner** [comment]
Through hyprland 
```Nix
exec-once = "ags"
```

**Comment by fufexan** [comment]
Can you try enabling ags' Home Manager module and letting it start as a systemd service?

**Comment by timoleistner** [comment]
I've tried that now but did not work either. (I think ags did not start at all even though `systemctl --user status ags` yielded an active ags systemd service.
I've fixed it now with launching ags through hyprland with `exec-one = "dbus-launch --exit-with-session ags"`. This should work as a workaround as long as there are not more programs which need this...

**Comment by upfringe** [comment]
> > # exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> > # exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> > # exec-once = /usr/local/bin/hyprdelayfix.sh
> 
> After try above ways from hyprland wiki and issue ,none of them is the right solution, I still suffer two minutes long waiting waybar to show, 30s to thunar to show, but add export $(dbus-launch) into a Hyprland launcher solve the problem, that reminds me the bspwm.desktop provided by manjaro-bspwm , so I try `Exec=dbus-launch --sh-syntax --exit-with-session Hyprland` in hyprland.desktop in wayland-session. It worked! all back to normal. Hyprland should tell everyone that is the right way to launch Hyprland.

After this my waybar won't lauch. it says connection refused

**Comment by stefanpartheym** [comment]
In my case xdg-desktop-portal-gtk takes about a minute to start when I exit Hyprland once and login again:
```
● xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
     Active: active (running) since Sun 2025-07-06 15:08:08 CEST; 53s ago
 Invocation: 0093740220254139b0733b3bdeb88aa8
   Main PID: 132070 (xdg-desktop-por)
      Tasks: 5 (limit: 114794)
     Memory: 6M (peak: 6.8M)
        CPU: 98ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gtk.service
             └─132070 /usr/lib/xdg-desktop-portal-gtk

Jul 06 15:07:18 fux systemd[1950]: Starting Portal service (GTK/GNOME implementation)...
Jul 06 15:08:08 fux systemd[1950]: Started Portal service (GTK/GNOME implementation).
```

This delays the startup of a lot of apps (like waybar, ghostty, etc.). But I can't figure out what the root issue is. I do have GNOME installed alongside Hyprland. Maybe that's the issue?

**Comment by Motaphe** [comment]
~~In my case, xdg-desktop-portal-gtk was the culprit. I masked it and everything works as soon as I login.~~

Setting up hyprland through uwsm seems to have resolved this issue.

**Comment by stefanpartheym** [comment]
I switched to using uwsm with Hyprland (called `Hyprland (uwsm-managed)`). This fixed it.

**Comment by otomay** [comment]
@Motaphe @stefanpartheym did you guys leave these lines in the hyprland.conf after started using uwsm?

```conf
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```

thankss I already can see some improvements

**Comment by stefanpartheym** [comment]
> [@Motaphe](https://github.com/Motaphe) [@stefanpartheym](https://github.com/stefanpartheym) did you guys leave these lines in the hyprland.conf after started using uwsm?
> ...

No, I removed them. I think, that's the whole point of uwsm. Don't quote me on that though.

**Comment by Motaphe** [comment]
Same here, I removed them. Uwsm automatically sets these up afaik.
