### ISSUE TITLE
Nested Compositors have mouse movement problems within 3D Games

### ISSUE THREAD

**Issue by cid-chan** [hyprwm/Hyprland#1380]
Steps:
1. run a nested compositor (I tested Cage and labwc)
2. run a 3d game within them (I tested Portal and Minecraft)
3. Try to move your camera

Expected:
Movement works normally

What actually happens:
https://user-images.githubusercontent.com/76440879/212472187-bebcfc95-002a-4b69-9ed4-47ec815c63e0.mp4

---

Why did I get the idea to do this:
I thought this would help me deal with full-screen games better, since the I can just screencapture the nested compositor instead of the game itself.

**Comment by cid-chan** [comment]
Running gamescope within a nested compositor yielded me this result.
https://user-images.githubusercontent.com/76440879/212472892-27c7775f-6d2e-4c79-9aca-21cc2a413738.mp4

There is far too much mouse sensitivity.

(test.sh just makes a white terminal to increase contrast with my mouse cursor)

**Comment by Makrennel** [comment]
I'm pretty sure this is a problem with the micro compositor itself, not Hyprland. At least in my experience mouse sensitivity issues also occurs when using Gamescope in other Wayland environments.

**Comment by vaxerski** [comment]
jfc why

**Comment by vaxerski** [comment]
this is a wlroots issue iirc, generally you're not supposed to do this anyways
