### ISSUE TITLE
Show invalid configuration bar on every monitor

### ISSUE THREAD

**Issue by sahinakkaya** [hyprwm/Hyprland#1385]
When the configuration is invalid, the bar indicating something might wrong is only visible on first screen. I was using my second monitor and laptop's lid was closed. Due to this, I missed an obvious error and  opened #1382 thinking there is a bug. 

I think the bar should be visible on every monitor if it is possible.

**Comment by vaxerski** [comment]
_every_ would be an overkill. It will now show on the current active monitor, just like the API notifications. 7beb9fd606106e82554c7050aebbc5ca23dafa79
