### ISSUE TITLE
Shading on rotated monitor in specialworkplace mode

### ISSUE THREAD

**Issue by umop3plsdn** [hyprwm/Hyprland#1389]
When entering specialworkspace mode on a rotated screen it only shades half of the screen. I have attached pictures of the shading issue it's quite subtle. Doesn't bother me or anything just wanted to report it though.

Full Example with shading(ignore the bright strip to the very left that's just my other screen included in the screenshot by accident):
![2023-01-15-18:27:33](https://user-images.githubusercontent.com/696094/212573723-4736270b-0240-4315-869c-72754a0559bd.png)
Close up of smaller portion of shading divide line:
![2023-01-15-18:33:44](https://user-images.githubusercontent.com/696094/212573722-1e8839a9-9108-496e-b8e4-e9deaabb37d6.png)
Same portion of screen as before but in normal mode:
![2023-01-15-18:33:59](https://user-images.githubusercontent.com/696094/212573721-3a9093df-8ad3-44ea-86b4-1935362df196.png)

**Comment by vaxerski** [comment]
fixado in 589046ecf74965a8e22a9891290f4b289c60a334 ado
