### ISSUE TITLE
Defullscreening ignores previous maximizing

### ISSUE THREAD

**Issue by scorpion-26** [hyprwm/Hyprland#1390]
*Everything tested on 589046ecf74965a8e22a9891290f4b289c60a334*

Steps to reproduce
1. Maximize application (e.g. firefox)
2. Send a fullscreen request through the application (e.g. fullscreening a video)
3. Send a defullscreen request through the application (e.g. exiting the video)

Outcome: 
The application window is now back to its normal, unmaximized state.

This behavior feels a bit off to me, since I expect the window to return to its state before the fullscreen was requested (i.e. maximized), and not always to the normal state.

If you also think this is unwanted behavior, I can open a PR with the fixes I made in my fork, if you want.

**Comment by vaxerski** [comment]
you can make a PR to that but it is expected behavior, although maybe not the most intuitive.
