### ISSUE TITLE
env not set?

### ISSUE THREAD

**Issue by Ogromny** [hyprwm/Hyprland#1391]
I when I try to run any `hyprctl` command I get:
`HYPRLAND_INSTANCE_SIGNATURE was not set! (Is Hyprland running?)`

Here is the log:
[Hyprland log](https://gist.github.com/Ogromny/a8ef4e61ed8ea5a2e7a6595e5a01ec28) 

```
~ $ env | grep HYPR
~ $ 
```

Hyprland is started with:
```sh
#!/bin/sh -e
dbus-run-session -- "$HOME"/Hyprland/build/src/Hyprland
```

And there is no socket in the instance signature path:
```
/tmp/hypr/9c77415cda40eb334dd9306c504c0003dc14b53f_1673888953 $ ls 
hyprlandd.log
/tmp/hypr/9c77415cda40eb334dd9306c504c0003dc14b53f_1673888953 $     
```

> Hyprland (master) compiled with meson

**Comment by vaxerski** [comment]
> #!/bin/sh -e
dbus-run-session -- "$HOME"/Hyprland/build/src/Hyprland

who told you to do that??

`Hyprland` sir. `Hyprland`.
