### ISSUE TITLE
Add Window Type and Window Role properties to use with Window Rules

### ISSUE THREAD

**Issue by adamnejm** [hyprwm/Hyprland#1392]
Please add the `window-type` *(dialog, menu, etc.)* and `window-role` *(pop-up, task_dialog, GtkFileChooserDialog, etc.)* properties exposed by clients. This is necessary for making windows such as file choosers floating. Otherwise all clients have to be targeted using combination of `class` and `title` properties and that can get annoying really fast.  
  
Would be great if this property was also dumped in `hyprctl clients -j`.

**Comment by adamnejm** [comment]
NOT PART OF THIS ISSUE:

I'm not familiar with Wayland protocols, but X11 clients also exported properties such as:
- `modal` - Parent window cannot be focused while it has a modal window
- `transient` - Reference to the parent window

This would allow for doing more complex stuff, such as positioning `modal` window in the center of it's parent as a floating window.

My reference: [AwesomeWM - Client Properties](https://awesomewm.org/apidoc/core_components/client.html#Object_properties)

**Comment by vaxerski** [comment]
all of those are X11 only.

You should probably start using wayland solutions to your problems.
