### ISSUE TITLE
Crash at 5120x1440 on nvidia

### ISSUE THREAD

**Issue by ccakes** [hyprwm/Hyprland#1394]
I've been setting up Hyprland over the last couple of days, so it's somewhat difficult to pin down exactly when this "broke" but as of this morning using 5120x1440 causes some strange behaviour and a segfault.

I changed the resolution in config and updated the nvidia driver from 525.60 -> 525.78 *around* the same time yesterday. I'm 99% sure I had both working at the same time but I can't really remember. I definitely has 5120x1440 working at some point though - and sway works fine at that resolution.

I've reproduced on the [autogenerated config](https://github.com/hyprwm/Hyprland/files/10430036/hyprlandd.conf.txt) with only changing the res. When loading in 3840x1080 everything works fine, but when setting to 5120x1440 then:

- the entire screen looks a bit dim, cycling workspaces fixes this
- wofi will open on a keybind but won't refresh.. typing doesn't display until I hit enter
- opening any app causes an assertion failure [here](https://github.com/hyprwm/Hyprland/blob/6a56d1e4d035824ea5dc94180994017346c5c067/src/render/OpenGL.cpp#L936)

I built in debug mode and captured a stacktrace as well - logs:

[crash log - hyprlandd.log](https://github.com/hyprwm/Hyprland/files/10430009/hyprlandd.log)
[stacktrace - asan.log](https://github.com/hyprwm/Hyprland/files/10430015/asan.log)

I built locally from 6a56d1e4d035824ea5dc94180994017346c5c067 with the [nvidia.patch](https://aur.archlinux.org/cgit/aur.git/tree/nvidia.patch?h=hyprland-nvidia-git) applied from the `hyprland-nvidia-git` AUR package.

**Comment by vaxerski** [comment]
can you try setting the scale explicitly, manually, on that res? Like 1, 1.5, 2. The default is `auto`.

**Comment by ccakes** [comment]
Explicitly setting the scale resolved this - thanks! I tried 1, 1.5 & 2 and it worked fine for all values :+1:

**Comment by vaxerski** [comment]
can you give me the log of that happening after compiling f14e8088478bf1e80e02a213a23c528fe32d3b91

**Comment by ccakes** [comment]
:point_right: [hyprland.f14e808.log.txt](https://github.com/hyprwm/Hyprland/files/10439584/hyprland.f14e808.log.txt)

That log has the crash however when explicitly setting the scale (to workaround the crash) the debug log line looks identical.

```
~ $ find /tmp/hypr -name '*log' -exec grep -H 'Monitor DP-1 data dump:' {} \;
/tmp/hypr/f14e8088478bf1e80e02a213a23c528fe32d3b91_1673991128/hyprland.log:[LOG] Monitor DP-1 data dump: res 0x0@6mHz, scale 5120.00, transform 0, pos 0x-1, 10b 0
/tmp/hypr/f14e8088478bf1e80e02a213a23c528fe32d3b91_1673991076/hyprland.log:[LOG] Monitor DP-1 data dump: res 0x0@6mHz, scale 5120.00, transform 0, pos 0x-1, 10b 0
```

**Comment by vaxerski** [comment]
oops I fucked up the types. Can you plox do that again on head

**Comment by ccakes** [comment]
Sorry for the slow reply, debug log and stacktrace from the crash running 5112056fdbda989191310364444f328240bbf6f1

[hyprlandd.log.5112056.txt](https://github.com/hyprwm/Hyprland/files/10462269/hyprlandd.log.5112056.txt)
[asan.log.6780.txt](https://github.com/hyprwm/Hyprland/files/10462273/asan.log.6780.txt)

**Comment by milgner** [comment]
For me, I can't even get Hyprland to active this resolution. Running the current version of Hyprland and the Nvidia DKMS drivers with an Nvidia card, `hyprctl monitors` only reports 3840x1080 as the only resolution.

I have set explicit values for all arguments, tried adding `@120`  or `@60` behind the resolution. No help. No crashes either but rendering, especially font rendering, looks very weird at 3840x1080.

My current line looks like

```
monitor=G9,5120x1440,0x0,1.5
```

**Comment by ccakes** [comment]
What does [`wlr-randr`](https://sr.ht/~emersion/wlr-randr/) show when in Hyprland? eg I get this
```
$ wlr-randr                                            
DP-1 "Samsung Electric Company C49RG9x (DP-1)"
  Make: Samsung Electric Company
  Model: C49RG9x
  Physical size: 1190x340 mm
  Enabled: yes
  Modes:
    3840x1080 px, 119.973999 Hz (preferred)
    5120x1440 px, 119.970001 Hz
    5120x1440 px, 99.996002 Hz
    5120x1440 px, 59.977001 Hz (current)
    3840x1080 px, 99.956001 Hz
    3840x1080 px, 59.967999 Hz
    2560x1440 px, 59.951000 Hz
    2560x1080 px, 119.880997 Hz
    2560x1080 px, 100.000000 Hz
    2560x1080 px, 60.000000 Hz
    2560x1080 px, 59.938999 Hz
    1920x1080 px, 119.878998 Hz
    1920x1080 px, 100.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.938999 Hz
    1680x1050 px, 59.953999 Hz
    1600x900 px, 60.000000 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1440x900 px, 59.887001 Hz
    1280x800 px, 59.810001 Hz
    1152x864 px, 75.000000 Hz
    1280x720 px, 60.000000 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 70.069000 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 72.188004 Hz
    800x600 px, 60.317001 Hz
    800x600 px, 56.250000 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 72.808998 Hz
    640x480 px, 59.939999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
```

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by vaxerski** [comment]
closing
