### ISSUE TITLE
Vulkan renderer support?

### ISSUE THREAD

**Issue by Kawasaki443** [hyprwm/Hyprland#1396]
Will there be any plan to inplement Vulkan renderer in Hprland?  Wlroots 0.17-dev has made it stable.
Currently animations are slightly laggy with gles2 renderer, especially when enabling more eye candy decorations(blur dim shadow) , maybe it will gain some render perfomence improment with vulkan?

**Comment by vaxerski** [comment]
I doubt vulkan would improve the performance at all in hyprland. It would only:
 - make Hyprland even less compatible (vulkan APIs are still less common on old systems)
 - require tons of rewrites
 - negligibly, maybe, improve performance
 
 If animations are too laggy for you, consider upgrading from that 10-year-old laptop. animation smoothness on my end is comparable to KDE/Gnome.
 
 Unless properly conducted benchmarks show any difference in performance of the two in e.g. sway, I have no plans of even considering vk.

**Comment by bobbyboy5069** [comment]
> make Hyprland even less compatible (vulkan APIs are still less common on old systems)
> ...
> If animations are too laggy for you, consider upgrading from that 10-year-old laptop.

First of all, 10 year-old hardware [DOES support Vulkan](https://en.wikipedia.org/wiki/Radeon_HD_7000_series#Vulkan_(API)), so why not support it if some people will benefit?

Second, what hardware are you targeting, exactly? Because I guarantee that most people who run Linux on old hardware are not using a desktop environment with fancy effects.

**Comment by vaxerski** [comment]
my other points still stand. I will not consider vk unless someone shows a significant performance difference between vk and gles. You are free to try and benchmark stuff like sway for example that support both.

**Comment by GrabbenD** [comment]
Does setting `WLR_RENDERER=vulkan` make _any_ difference at all in Hyprland (for instance, does frames from applications like Xwayland get presented via Vulkan layer while Hyprland effects/animations continue to use GLES2)?

Figured this would answer: https://github.com/hyprwm/Hyprland/issues/3037

**Comment by vaxerski** [comment]
it does not make any difference whatsoever

**Comment by vaxerski** [comment]
WLR_RENDERER doesn't do anything.

**Comment by vaxerski** [comment]
I don't think that's related in any way, shape, or form to this issue

**Comment by YeesterPlus** [comment]
reopen please, this is a probem for me
