### ISSUE TITLE
Autodetected autoscaled monitors are placed incorrectly

### ISSUE THREAD

**Issue by 2e0byo** [hyprwm/Hyprland#1397]
With two 4k monitors hyprland correctly detects and scales them, but places using the absolute (unscaled) coordinates:

```bash
$ hyprctl monitors
Monitor DP-1 (ID 0):
	3840x2160@59.997002 at 0x0
	description: LG Electronics LG HDR 4K 0x00005F5C (DP-1)
	active workspace: 1 (1)
	reserved: 0 24 0 0
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1

Monitor DP-2 (ID 1):
	3840x2160@59.997002 at 3840x0
	description: LG Electronics LG Ultra HD 0x00004B63 (DP-2)
	active workspace: 2 (2)
	reserved: 0 24 0 0
	scale: 1.50
	transform: 0
	focused: no
	dpmsStatus: 1
```

Consequently I cannot move the mouse off either monitor, although workspace switching still works.  After manually configuring the monitors things work again:

```bash
$ grep monitor ~/.config/hypr/hyprland.conf
#monitor=,preferred,auto,auto
monitor=DP-1,3840x2160@60,0x0,1.5
monitor=DP-2,3840x2160@60,2560x0,1.5
$ hyprctl monitors
Monitor DP-1 (ID 0):
	3840x2160@59.997002 at 0x0
	description: LG Electronics LG HDR 4K 0x00005F5C (DP-1)
	active workspace: 1 (1)
	reserved: 0 24 0 0
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1

Monitor DP-2 (ID 1):
	3840x2160@59.997002 at 2560x0
	description: LG Electronics LG Ultra HD 0x00004B63 (DP-2)
	active workspace: 2 (2)
	reserved: 0 24 0 0
	scale: 1.50
	transform: 0
	focused: no
	dpmsStatus: 1
```

The autoplacing logic should take into account the applied scale.

Separately, hyprland is wonderful, thank you very much!

**Comment by Thaodan** [comment]
I noticed that switching from one screen to the other doesn't work, doesn't matter if using auto or manual position.
Changing one of the screens to no scaling workarounds the issue.

**Comment by 2e0byo** [comment]
@Thaodan how are you placing your scaled screens?  You need to use the scaled position.  Or are you unable to move between screens even when placed correctly?  (By switching do you mean moving with the mouse, or switching workspaces manually?)

**Comment by Thaodan** [comment]
The behavior is the same even when I use the scaled resolution, I'm talking about moving the mouse cursor.

**Comment by 2e0byo** [comment]
what's the failing scaled configuration? and what does `hyprctl monitors` show? [not that I own hyprland or anything, but I might be able to reproduce]

**Comment by Thaodan** [comment]
hyprctl monitors with the "working" but unscaled config"
```
Monitor DP-1 (ID 0):
        3840x2160@59.997002 at 3840x0
        description: Dell Inc. DELL U2723QE C5579H3 (DP-1)
        make: Dell Inc.
        model: DELL U2723QE
        serial: C5579H3
        active workspace: 2 (2)
        reserved: 0 17 0 0
        scale: 1.50
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: 0

Monitor HDMI-A-1 (ID 2):
        3840x2160@120.000000 at 0x0
        description: LG Electronics LG TV SSCR2 0x01010101 (HDMI-A-1)
        make: LG Electronics
        model: LG TV SSCR2
        serial: 0x01010101
        active workspace: 3 (3)
        reserved: 0 19 0 0
        scale: 1.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
```

The config with scaling enabled for the left screen/mirror where the mouse cursor can't move between the left and right screen:
```
monitor=DP-1,3840x2160,2953x0,auto
monitor=DP-3,3840x2160,auto,1.5,mirror,HDMI-A-1
monitor=HDMI-A-1,3840x2160@120,0x0,1.5
```

Hyprctl monitors from this config:
```
Monitor DP-1 (ID 0):
        3840x2160@59.997002 at 2953x0
        description: Dell Inc. DELL U2723QE C5579H3 (DP-1)
        make: Dell Inc.
        model: DELL U2723QE
        serial: C5579H3
        active workspace: 2 (2)
        reserved: 0 17 0 0
        scale: 1.50
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: 0

Monitor HDMI-A-1 (ID 2):
        3840x2160@120.000000 at 0x0
        description: LG Electronics LG TV SSCR2 0x01010101 (HDMI-A-1)
        make: LG Electronics
        model: LG TV SSCR2
        serial: 0x01010101
        active workspace: 3 (3)
        reserved: 0 17 0 0
        scale: 1.50
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
```

**Comment by 2e0byo** [comment]
Why are you using 2953?  3840/1.5 = 2560.

**Comment by Thaodan** [comment]
> Why are you using 2953? 3840/1.5 = 2560.

Oh yeah :sweat_smile:  I think this was a left over from when I used 1.3 scale.
Now it works thanks.

**Comment by MightyPlaza** [comment]
still happening?

**Comment by 2e0byo** [comment]
> still happening?
yes, with 0.28.0-1.  I can try latest master tonight if it would help.

**Comment by MightyPlaza** [comment]
no, with 0.29
since there have been changes to monitor arragement

**Comment by 2e0byo** [comment]
Brilliant.  I'll move back to the aur package and confirm, but if so this can be closed.
