### ISSUE TITLE
Waybar tray menu behind active windows

### ISSUE THREAD

**Issue by ShabirK21** [hyprwm/Hyprland#1400]
When i right click on tray icons, the  menu that pops up appears behind my currently open windows. I have to either close the windows or send them to special workspace in order to interact with the menu.

**Comment by vaxerski** [comment]
set layer to top in the waybar config instead of bottom. Not a hyprland issue.

**Comment by ShabirK21** [comment]
> set layer to top in the waybar config instead of bottom. Not a hyprland issue.

alright, thanks for the help
