### ISSUE TITLE
[Issue] Dependencie problem installing xdg-desktop-portal-hyprland-git

### ISSUE THREAD

**Issue by linuxmobile** [hyprwm/Hyprland#1403]
According to the **instructions on the hyprland wiki**, it is recommended to install `xdg-desktop-portal-hyprland-git`. And we are told that _having -wrl and -hyrpland installed together could cause conflicts_. But to be able to install one you need the other

```
paru -S xdg-desktop-portal-hyprland-git
:: Resolving dependencies...

:: There are 5 providers available for xdg-desktop-portal-impl:
:: Repository extra:
    1) xdg-desktop-portal-gnome  2) xdg-desktop-portal-gtk  3) xdg-desktop-portal-kde
:: Repository community:
    4) xdg-desktop-portal-lxqt  5) xdg-desktop-portal-wlr
Enter a number (default=1): 5
```

**Comment by vaxerski** [comment]
@ThatOneCalculator you blithering idiot your pkgbuild is fucked again

**Comment by ThatOneCalculator** [comment]
Nah that's just paru not knowing how to handle impls properly, use yay.

**Comment by vaxerski** [comment]
well paru is also used so it would be nice if it worked kainoa

**Comment by ThatOneCalculator** [comment]
The thing is paru doesn't look in the aur for impls, so either paru fixes it or our package is added to the arch community repo

**Comment by vaxerski** [comment]
odd. 

![image](https://user-images.githubusercontent.com/43317083/213744208-d3b7579d-2459-43fa-9539-83ccb4fb0c50.png)

it should fucking _provide_ not _require_

**Comment by vaxerski** [comment]
so yeah report to paru. In the meantime I will add a note to the wiki

**Comment by BvngeeCord** [comment]
Am I dumb? This is with yay.
```resolving dependencies...
:: There are 5 providers available for xdg-desktop-portal-impl:
:: Repository extra
   1) xdg-desktop-portal-gnome  2) xdg-desktop-portal-gtk  3) xdg-desktop-portal-kde
:: Repository community
   4) xdg-desktop-portal-lxqt  5) xdg-desktop-portal-wlr

Enter a number (default=1): ^C```

**Comment by vaxerski** [comment]
@ThatOneCalculator for aur

**Comment by ThatOneCalculator** [comment]
Weird, I'll investigate

**Comment by cvincent** [comment]
Also seeing this message with `yay`, as well as `makepkg -sri`. Not sure how to proceed.

**Comment by kcrmson** [comment]
> Also seeing this message with `yay`, as well as `makepkg -sri`. Not sure how to proceed.

Install option #2 (xdg-desktop-portal-gtk) as the rest will cause issues. You'll probably also want xdg-desktop-portal-hyprland-git, leaving you with three installed packages total (xdg-desktop-portal, xdg-desktop-portal-gtk, xdg-desktop-portal-hyprland-git).

**Comment by cvincent** [comment]
I did the above and then removed `xdg-desktop-portal-gtk`. No problems so far, and I've confirmed `xdg-desktop-portal-hyprland` is running.

**Comment by RedBlizard** [comment]
Today came a update of this Dependencie or yesterday already. it gives issue again i did check with yay and with paru same problem.

~ ❯❯❯ upall
[sudo] password for redblizard: 
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: 1 Packages to upgrade.
1  aur/xdg-desktop-portal-hyprland-git  r261.e1f145d-1 -> r261.ge1f145d-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 1
 there is nothing to do

I did also these steps but issue stays the same with paru and with yay.

Went to the AUR package page for xdg-desktop-portal-hyprland-git: https://aur.archlinux.org/packages/xdg-desktop-portal-hyprland-git/
Clicked on the "Download snapshot" button to download the source code.
Open a terminal and navigate to the directory where the source code was downloaded (usually your Downloads folder).
Run the command git clone https://aur.archlinux.org/xdg-desktop-portal-hyprland-git.git to clone the source code repository.
Change into the cloned directory with cd xdg-desktop-portal-hyprland-git.
Run makepkg -si to build and install the package.
This should build and install the updated version of the package, bypassing any issues with yay.

But the problem stays.

**Comment by Ubermensch85** [comment]
The pkgbuild install the **r261.e1f145d-1** not **r261.ge1f145d-2**
