### ISSUE TITLE
Compiling Hyprland from git fails

### ISSUE THREAD

**Issue by mortenivar** [hyprwm/Hyprland#1404]
Hi,

I cannot compile the latest git version of Hyprland. I am attaching a log.
[hypr-compile-fail.txt](https://github.com/hyprwm/Hyprland/files/10458044/hypr-compile-fail.txt)

**Comment by vaxerski** [comment]
seems like an issue with libdrm...?

At any rate, since the CI does not fail, it means compiling succeeds on all our test platforms.

If you are using any other distro, it's up to you to figure out what you may be missing / what might be outdated.

**Comment by mortenivar** [comment]
Hi Vaxry

But I am using Arch - which is supported. Trying to install
from AUR, both the git version and the release version also fails.

**Comment by vaxerski** [comment]
if that's the case make sure you are up to date and have all the dependencies. You can take a look at the arch CI as well, it does _not_ fail.

**Comment by mortenivar** [comment]
Actually, I forgot to update - I had just updated an Arch
system on another computer and forgot it wasn't the one I was
sitting at ...but after the update, it still fails with the
exact same error. When installing from AUR, all the
dependencies are checked automatically and therefore should be
OK.

But I am on my own, I guess.
