### ISSUE TITLE
Fullscreen window triggers tiled windows animation

### ISSUE THREAD

**Issue by impankratov** [hyprwm/Hyprland#1406]
Hi, first of all thanks for all the hard work, Hyprland is a great compositor!

I've encountered strange behaviour using [SafeEyes](https://github.com/slgobinath/SafeEyes) app. Periodically it will open fullscreen window to encourage to take a break then closes it.

I've noticed that these windows somehow trigger animations for tiled windows in background (for example right terminal in attached video on 0:10). Which looks kind of wrong.

https://user-images.githubusercontent.com/6479407/213701398-14f09ba8-bb67-4f78-a6ed-539e7e879370.mp4

I've tried to disable animations completely using this rule:

```
windowrulev2 = noanim,class:^(safeeyes)$,fullscreen:1
```

But it works only for the safeeyes window, and tiled windows in background still re-animate:

https://user-images.githubusercontent.com/6479407/213701514-83420606-4d7c-431c-ac4f-4a8c10285a7c.mp4

Just wondering if anything can be done to prevent this behaviour (except for disabling animations completely for all windows)

Running hyprland `0.20.1beta-1`

**Comment by vaxerski** [comment]
instead of adding noanim, make it `float`. Fullscreen windows are _not_ removed from the layout when they are fullscreen'd.

**Comment by impankratov** [comment]
@vaxerski thanks, perfect solution!

Resulting windows rule:
```
windowrulev2 = float,class:^(safeeyes)$
```
