### ISSUE TITLE
Grabbing a window while fullscreen causes very weird behaviour

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1407]
As stated in title, if you grab a window that's fullscreened, and then unfullscreen it. Then you grab the window again to move it to another workspace. You can make a window that renders in a workspace, but exsists in another. Very weird shit(video currently encoding, plz wait)
As seen in the `.config/wofi` terminal
![image](https://user-images.githubusercontent.com/68589851/213715560-d1e06310-d1de-4d8a-bf1b-464af0c265de.png)
And this also happens if I'm not in workspace 2

![image](https://user-images.githubusercontent.com/68589851/213716067-e309633f-d2e7-47b4-8f54-b0b918e53747.png)

The obs window is tiled.(according to hyprctl)

**Comment by JustSimplyKyle** [comment]
[weird_fullscreen.webm](https://user-images.githubusercontent.com/68589851/213724226-170ef1f5-9080-4d65-9802-f04f917e6135.webm)

**Comment by vaxerski** [comment]
LOL

**Comment by vaxerski** [comment]
fixed in d5913a23acd36eeaa46a99380afe8b2a78492f2e

also wtf are those wallpapers

**Comment by JustSimplyKyle** [comment]
oh shit, that was bad
