### ISSUE TITLE
Chromium & Electron applications freeze when trying to use wayland

### ISSUE THREAD

**Issue by ShabirK21** [hyprwm/Hyprland#1411]
Im on arch and tried to brave to wayland but it doesnt open, it just freezes my device same thing with electron apps like visual studio. Im using a AMD/Nvidia laptop, ive also installed nvidia-vaapi-driver-git

**Comment by vaxerski** [comment]
Seems like an nvidia problem. Consult the nvidia wiki page or ask around on discord.

We do not provide _official_ support for nvidia
