### ISSUE TITLE
dbus-update-activation-environment is not cleanly killed

### ISSUE THREAD

**Issue by ysh7** [hyprwm/Hyprland#1413]
[dbus-update-activation](https://github.com/hyprwm/Hyprland/blob/main/src/Compositor.cpp#L390) is started in a child process which is not cleanly closed creating zombie process. 

This doesn't crash cause crash but it is not intended behavior.

**Comment by vaxerski** [comment]
fixed in 63babcba36f5506b4da6ee7f92f2491c6e1ff726
