### ISSUE TITLE
Bind not working with xkbcommon-keysyms (question, greater, less...)

### ISSUE THREAD

**Issue by xVermillionx** [hyprwm/Hyprland#1414]
### Steps to reproduce:

    bind=SUPERSHIFT,question,exec,notify-send additional_test
    bind=SUPERSHIFT,greater,movewindow,mon:+1
    bind=SUPERSHIFT,less,movewindow,mon:-1

### Expected outcome:

    Bind the keys and dispatch command

### Noted outcome:

    Does not execute or register the binding

I worked around it using variables with their respective key codes, but since the [wiki](https://wiki.hyprland.org/Configuring/Binds/#uncommon-syms--binding-with-a-keycode) mentions the ability to use xkbcommon-keysyms, without the prefix XKB_KEYS_, I would think that not being able to use the keysyms is invalid behavior.

**Comment by vaxerski** [comment]
question is the shifted keysym lol use slash or something, check wev and dont press shift

**Comment by xVermillionx** [comment]
I just checked and as you said question does work using SUPER,/ but it still does not for less or greater trying SUPERSHIFT,. (SUPER,. also) or SUPER,> does not work, at least for me, thats why i was trying with the keysyms and less and greater:

I just checked again and these binds did not work:
    
    bind=SUPER,.,exec,notify-send test
    
    bind=,>,exec,notify-send test
    bind=SHIFT,.,exec,notify-send test
    bind=,greater,exec,notify-send test
    
    bind=SUPER,greater,exec,notify-send test
    bind=SUPER,greater,exec,notify-send test
    bind=SUPERSHIFT,.,exec,notify-send test
    bind=SUPERSHIFT,greater,exec,notify-send test

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/214034638-e8d53f1e-26ca-4c0a-8e1f-bf9060b8fcb5.png)

as wev says, the sym is `period` not `.`
