### ISSUE TITLE
Allow use of environment variables when sourcing files

### ISSUE THREAD

**Issue by adamnejm** [hyprwm/Hyprland#1416]
`source = ~/.config/hypr/binds.conf` works
`source = $XDG_CONFIG_HOME/hypr/binds.conf` errors

We can already use environment variables with `exec`, having it in `source` would be noice.

**Comment by JustSimplyKyle** [comment]
http://wiki.hyprland.org/Configuring/Keywords/#defining-variables
Wouldn't the syntax break this?

**Comment by adamnejm** [comment]
How about just importing the environment as variables when Hyprland inits?  
  
This wouldn't break anything as re-defining variables would simply override the value.  
  
Could also prove really useful for other *(future)* stuff that you may wanna pass some environment variable to without having to start a new shell.

**Comment by mewejo** [comment]
In Sway, to include workstation specific config, I'd use:

```
include $HOME/.config/sway/`hostname`/*
```

I'd expect the Hyprland version to be something like:

```
source=~/.config/hypr/workstations/`hostname`/before.conf
```

Is this possible in Hyprland? Been looking for a way, either via the init script or variable substitution, but can't see anything, and none of the usual syntax's seem to be working.

**Comment by vaxerski** [comment]
done in b03c8970e698312e237fe176ee2654e819c5c202

**Comment by tjoneseng** [comment]
It seems this was broken in 13f6f0b.
