### ISSUE TITLE
Workflow equal to newm

### ISSUE THREAD

**Issue by CRAG666** [hyprwm/Hyprland#1417]
I currently use newm as my main wm, I really like your workflow, however I recently tried this project and I found it very good, I would like to know if there would be the possibility of integrating a similar workflow.

repository:

https://github.com/jbuchermn/newm

workflow:
https://www.youtube.com/watch?v=mDw-hMW0b70

**Comment by CRAG666** [comment]
@vaxerski It's very productive if you use it with a laptop, I've been using newm for a year

**Comment by AlexD97** [comment]
I have to agree with @CRAG666. I find the workflow very productive. I think it would be sufficient for me if it would be possible to combine four workspaces to one and vice versa.

**Comment by RichardFevrier** [comment]
I was looking for this feature too I thought it was part of `Hyprland` 😕
I cannot disagree more with:
> it's not very productive

@vaxerski quite the opposite when you have a lot of terminals running in //, having an overview of all of them is mandatory! (IMHO)

Then I cannot use your immense work, but still thank you for all of it 🙏

**Comment by CRAG666** [comment]
@vaxerski I believe that it would not be possible to achieve that with a plugin, since it is more of the core than a perse plugin, but if I understand the lack of interest, I was just asking and giving an idea to differentiate a bit from the traditional wm

**Comment by vaxerski** [comment]
I don't see a single thing newm's layout has that would not be possible with a plugin.

**Comment by zim0369** [comment]
> @vaxerski It's very productive if you use it with a laptop, I've been using newm for a year

I totally agree, it's not just a gimmick, it seems very functional

**Comment by CRAG666** [comment]
@vaxerski Do you have any guide to try to create a plugin?

**Comment by vaxerski** [comment]
have you tried [rtfm](https://wiki.hyprland.org/Plugins/Development/Getting-Started/)

there is also [a template by duckonaut](https://github.com/Duckonaut/hyprland-plugin-template)

**Comment by CRAG666** [comment]
> has probado [ rtfm ](https://wiki.hyprland.org/Plugins/Development/Getting-Started/)
quite dictatorial and rude but it works for me
