### ISSUE TITLE
Antialiased border corners

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#142]
**Describe in detail your idea.**

:finnadie: 

![image](https://user-images.githubusercontent.com/44733677/171282540-fd81504f-61c6-4e4f-8473-d6f1c0a316ae.png)

**Comment by vaxerski** [comment]
basically to make the corners antialiased i think i'd have to make the entire scene antialiased (or at least border render)

I'll look into it some day lol

**Comment by ThatOneCalculator** [comment]
Since it's in OpenGL, you can just use MSAA yea?

**Comment by vaxerski** [comment]
yeah it is some settings and i think it's enabled on a per-fb basis

**Comment by ThatOneCalculator** [comment]
sick :feelsgood:

**Comment by godalming123** [comment]
Isn't it implemented in https://github.com/vaxerski/Hyprland/commit/e11cb8b328ff2ed9459f12319808226d3b900aa2 it's even in the docks https://github.com/vaxerski/Hyprland/wiki/Basic-Config#docoration

**Comment by vaxerski** [comment]
it got implemented after the issue, furthermore it's not fully done.
