### ISSUE TITLE
Autoreload of configuration doesn't work when configuration path is not default path

### ISSUE THREAD

**Issue by autofool** [hyprwm/Hyprland#1423]
Archlinux aur hyprland-git.

Configuration autoreload only works if configuration is located at `~/.config/hypr/hyprland.conf`

If configuration is provided through Hyprland command, like `Hyprland -c /my/config` and path is not the default path mentioned above then any changes to `/my/config` is not reloaded in Hyprland session.

In addition, if `/my/config` has errors then error message shown in Hyprland session has path written as `~/.config/hypr/hyprland.conf` instead of `/my/config`

Its possible that Hyprland is reverting to default config path after initial startup even if custom configuration is provided.

**Comment by aditya-K2** [comment]
couldn't replicate this.

**Comment by coffebar** [comment]
I can Confirm this bug.
I start wm this way:

```
export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_OPT="crab"
exec /usr/bin/Hyprland -c "$HOME/.config/$XDG_SESSION_OPT/hyprland.conf"
```

My config works after start, but without hot reloading.
**hyprctl reload** doesn't work too.

Logs spammed with

> [ERR] Config doesn't exist??
> [ERR] Config doesn't exist??
> [ERR] Config doesn't exist??
> [ERR] Config doesn't exist??
> [ERR] Config doesn't exist??
> [ERR] Config doesn't exist??
> [ERR] Config doesn't exist??

When config file in default location - everything is fine.
