### ISSUE TITLE
I can't set the screen refresh (amd gpu)

### ISSUE THREAD

**Issue by Zalan2006** [hyprwm/Hyprland#1427]
I can't set the screen refresh if I rewrite 1920x1080@60 > 1920x1080@120 nothing happens and no error 
[https://cdn.discordapp.com/attachments/706159647366709309/1067593201373937764/Screenshot_2023-01-25-00-46-22_26516.xcf](url)

**Comment by vaxerski** [comment]
and how do you verify it is not 120hz?

**Comment by Airmancooma** [comment]
> and how do you verify it is not 120hz?

I dont know goverlay? However, in the meantime it was solved with another config file that works if I rewrite it

**Comment by vaxerski** [comment]
you should use the debug overlay or wlr-randr to check your mode. However, if another config fixed it then the problem was with you not being able to config hyprland correctly.
