### ISSUE TITLE
Fullscreen applications detect as being launched on the first monitor in the chain

### ISSUE THREAD

**Issue by Fleimi** [hyprwm/Hyprland#1428]
Fullscreen applications such as games (tried The Outer Worlds on Steam via Proton, and Cyberpunk 2077 on Heroic via VKD3D) behave as if they are being launched on the first monitor in the virtual layout, "reading" left-to-right.

This happens even if the game is physically being launched in a different monitor. At best this results in the resolution being detected incorrectly and at worst results in an unaddressable window that exists in a limbo-state between being on one monitor and on another.

**Steps to reproduce**
Configure Hyprland such that 
```
monitor=DP-1, 2560x1440@144,1920x0,1
monitor=DP-2, 1920x1080@60,0x0,1
```
and launch a game on DP-1

**Expected outcome**
Game launches on DP-1, fetches the resolution of DP-1 and lets you adjust it to the max of the monitor

**Noted outcome**
Game launches on DP-1, but fetches the resolution of DP-2 but only lets you adjust resolution to the max of DP-2 monitor

I tested a reverse configuration of 
```
monitor=DP-1, 2560x1440@144,0x0,1
monitor=DP-2, 1920x1080@60,2560x0,1
```
,placing DP-2 to the right of DP-1. Doing this, the game detects the resolution correctly, which leads me to believe this is a bug with Hyprland/wlroots or possibly Wine. If this is the wrong place to post, please direct.

**Comment by varris1** [comment]
A workaround is to set the primary monitor via xrandr. This will only work until the main monitor is turned off however. This is not specific to Hyprland and happens on sway too I have noticed.

**Comment by vaxerski** [comment]
if this happens on sway as well then this is an xwayland issue, not hl. closing
