### ISSUE TITLE
Expose secondary kb_layout to fullscreen applications

### ISSUE THREAD

**Issue by Fleimi** [hyprwm/Hyprland#1429]
I have Hyprland configured such that 
```
input {
    kb_layout = us,us
    kb_variant = colemak,
    kb_model = pc104
    kb_options = grp:ctrl_shift_toggle
}
```
and as such, fullscreen applications such as games will only read the first entry on the list as the keyboard layout, even if I launch them with the second one pre-selected. Using the grp:ctrl_shift_toggle keybind to switch layouts has no effect inside the game. If I reverse the configuration to 
```
input {
    kb_layout = us,us
    kb_variant = ,colemak
    kb_model = pc104
    kb_options = grp:ctrl_shift_toggle
    kb_rules =
    sensitivity = -0.9
}
```
(moving the "," to the beginning of "colemak" rather than after, making the order of the layouts "us" and "us-colemak" rather than "us-colemak" and "us")

then the games will again detect the first entry on the list, it now being "us".

I realize this is probably the wrong place to post this, but as I have no knowledge of the inner workings of these things, I have to post somewhere and hope to be advised of a more suitable place to post :)

**Comment by vaxerski** [comment]
dunno what's happening but hyprland should still send the correct syms regardless of window state. Maybe the game is sniffing input differently?

**Comment by Fleimi** [comment]
Under X11, using`setxkbmap` in the terminal immediately switches it in the game, but doing that in Wayland/Hyprland doesn't make a difference. I poked around and realized the games are not running under XWayland but rather what I assume is Wine's native Wayland layer. I will submit this as a bug in Wine along with the monitor troubles I posted about as well.

**Comment by matthewperkins** [comment]
I have been using Keyd application mapper for this type of issue, it is working well.
