### ISSUE TITLE
When the mouse cursor is hidden, it reappears when switching to an empty workspace and stays visible

### ISSUE THREAD

**Issue by laszloszurok** [hyprwm/Hyprland#1430]
When cursor_inactive_timeout is used to hide the cursor after some time, the cursor will become visible again, when I switch to a workspace that has no windows. Then the cursor will not become hidden after the configured timeout, unitl I move the mouse. After I move the mouse it works correctly again. I built Hyprland from latest source.

Steps to reproduce:
* set cursor_inactive_timeout to lets say 5
* wait 5 seconds for the cursor to disappear
* switch to an empty workspace with a keybinding

Expected behavior: The cursor stays hidden.

**Comment by vaxerski** [comment]
fixed in 06b17db22776e613a714e7e936618c16c3f47eaa
