### ISSUE TITLE
New kind of workspaces. (Hard to find a good name)

### ISSUE THREAD

**Issue by AdrienDML** [hyprwm/Hyprland#1431]
Here is the idea instead of having different workspaces on each screen, a workspace is all your screens. When you change workspace all your screen changes. Gnome workspaces work this way.

I don't know if it is a feature suitable for hyprland but its a workflow i quite like. 

Note: I haven't tried scripting it yet as I'm very new to hyprland but might try to do so in the near future.

**Comment by DashieTM** [comment]
You can definitely get it done via scripting.
Just execute multiple change workspace commands (the amount of screens you have).

**Comment by vaxerski** [comment]
as above, scripting. Not planning on making this a builtin, no reason to.
