### ISSUE TITLE
virtualbox / virt-manager keybinding issue 

### ISSUE THREAD

**Issue by darkrift-opt** [hyprwm/Hyprland#1434]
I am hopping on and off from hyprland  to bspwm due to keybinding issue on virtual machines.
I wish I could use hyprland 100 percent.

Currently running Arch Linux  on my laptop  with hyprland and bspwm.

Almost everything works under hyprland except virtual machines

The issue is my host laptop keybinding interact with virtual machines.
for instance I am running hyprland and I just launch virt-manager running  bspwm for software testing, or other form of testing When I press [ mod4 and enter ] it should launch a terminal inside of the virtual machine  but not's the cause the host machine launch terminal.

In xorg virtual machines works perfect
just now I thought maybe this is a wayland issue, so I have installed sway wm and virtual machines works without keybinding issue 

If you want more info such my configuration you can check out my [dotfiles](https://github.com/darkrift-opt/dotfiles)

**Comment by vaxerski** [comment]
cuz hyprland picks up the keybind for mod4 and enter most likely. Make an empty submap with only a return bind to pass all input into the vm

**Comment by JustSimplyKyle** [comment]
https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_keyboard/mouse_via_Evdev
For me, this can capture the input.  Use L_CTRL+R_CTRL to "un_capture"/free the input back to Hyprland

**Comment by darkrift-opt** [comment]
@JustSimplyKyle  Thanks for link, I am going to figure out by tomorrow hopefully, If not than I will ask for help again.
Much appreciated.

**Comment by darkrift-opt** [comment]
@JustSimplyKyle, There's nothing under /dev/input/by-id/ ; only webcam symbolic link

also I follow this [link](https://github.com/libvirt/libvirt/blob/master/docs/formatdomain.rst#input-devicesl)
nothing seem to work for me.

@vaxerski I am not sure what you mean by pass empty bind to vm

I thought wayland-protocol extension fix the issue about keybinding - https://wiki.archlinux.org/title/wayland#Input_grabbing_in_games,_remote_desktop_and_VM_windows


Is there a way to disable keybinding while in focus in virtual-manager

**Comment by vaxerski** [comment]
```
bind=ALT,P,submap,passall
submap=passall
bind=,escape,submap,reset 
submap=reset
````
alt + p -> goes into a pass all mode, esc -> leaves

read the wiki?

**Comment by epitaphial** [comment]
> 

but this is really a uncomplicated way...we need to push this hotkey before every visit to the vm... :|
