### ISSUE TITLE
Isuue with config file on Fedora 37

### ISSUE THREAD

**Issue by Lucascito03** [hyprwm/Hyprland#1435]
When I try to edit my autogenerated config file, Hyprland still thinks it's autogenerated and won't apply the changes. I'm thinking this is a permissions issue but I'm not really sure.

**Comment by scientiac** [comment]
I have been using it since 3 days, name the config ```hyprlandd.conf``` and remove the auto-generated one. That's my workaround for now.

**Comment by vaxerski** [comment]
why are you building in debug?

**Comment by Lucascito03** [comment]
I did not build it I used the copr repository

**Comment by vaxerski** [comment]
not maintained by us, most likely broken

**Comment by Lucascito03** [comment]
Ah real, I'll just keep using it for now per @scientiac's recommendation

**Comment by scientiac** [comment]
Yeah I too used bzaisan/Hyperland copr repo... Build State is failed with the latest timestamp of '8 days ago'.

But it's working flawlessly, I haven't found any noticable bugs except this one.

Just finished uploading my fork of Chris Titus's config, it will be helpful to you @Lucascito03, I hope.

https://gitlab.com/scientiac/hyprconfig
