### ISSUE TITLE
Visual bug with blur_xray, ignore opacity, and workspaces fade animation

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#1436]
Visual bug right here.
Set it up:
animations {
    animation=workspaces,1,3,default,fade
}

decoration {
    blur=true
    blur_xray = true
    blur_ignore_opacity = 1
}

To trigger it, make a floating window on workspace 1, make a big window on workspace 2, then change between workspaces 1 and 2.

Thank you very much for the attention. Cheers!

**Comment by izmyname** [comment]
Still broken?
