### ISSUE TITLE
Support multiple special workspaces

### ISSUE THREAD

**Issue by khughitt** [hyprwm/Hyprland#1438]
Greetings!

Any chance you might consider enabling the creation of multiple special workspaces, or something similar?

There is a really good use-case for this which I use all the time in i3: toggling multiple terminals/REPLS to quickly check something.

E.g. in my setup:

```
alt-enter     # terminal scratchpad
alt-j            # Julia
alt-p           # IPython
alt-space    # R console
alt-n           # Node.js
```

With only a single ~scratchpad, this is not possible.

**Comment by vaxerski** [comment]
are you kidding me



https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces

**Comment by khughitt** [comment]
Yea.. I use my workspaces for tiling windows related to projects.

The scratchpads are to quickly check some code id / do something in the shell without having to switch workspaces or create a new one.

**Comment by vaxerski** [comment]
I literally gave you a wiki link showing how to do that.

**Comment by khughitt** [comment]
Ah okay. My mistake -- I thought you were just sharing https://wiki.hyprland.org/Configuring/Advanced-config/, which doesn't mention anything about multiple special workspaces.

Thanks for pointing that out.

**Comment by JustSimplyKyle** [comment]
http://wiki.hyprland.org/Configuring/Dispatchers/#workspaces
Here, named special workspace
