### ISSUE TITLE
Crash when laptop monitor is disabled

### ISSUE THREAD

**Issue by eneshecan** [hyprwm/Hyprland#1441]
Hi, with the release v0.21.0beta, hyprland crashes on startup with the following monitor config:
```
monitor=eDP-1,disable
monitor=desc:Dell Inc. DELL P2419H 8BD7QF3,preferred,0x0,1
monitor=desc:Dell Inc. DELL U2412M Y1H5T29Q0PFL,preferred,1920x0,1
```

Here is the coredump attached
[crash.txt](https://github.com/hyprwm/Hyprland/files/10527969/crash.txt)

**Comment by vaxerski** [comment]
check with ce632b7a05a27d121c9544607ccd873adee8bd42

**Comment by eneshecan** [comment]
Wow, fast one. Lemme check!

**Comment by eneshecan** [comment]
Works like a charm now. Thanks a lot!
