### ISSUE TITLE
movetoworkspace previous doesn't do anything

### ISSUE THREAD

**Issue by leg7** [hyprwm/Hyprland#1443]
`hyprctl dispatch movetoworkspace previous`

Does nothing when it should be moving the focused window to workspace `previous`

version:
`Hyprland, built from branch main at commit 94b7b6b58475a0e802e390591f95e04c70aa676ddirty (added binds:focus_preferred_method).
flags: (if any)
`

**Comment by vaxerski** [comment]
fixed in 4ea4efb871997a245539cae9d966ec8f07d3e907
