### ISSUE TITLE
Second monitor does not display hyprland

### ISSUE THREAD

**Issue by Bkeinn** [hyprwm/Hyprland#1444]
When I start Hyprland, my second Monitor does not change. Hyprland detects that it exists, but the Monitor displays nothing.
OS: Fedora 37, Radeon graphics card
I followed the guide and build pixman-1. When I boot my Laptop, I get into Lightdrm. Since I know that Lightdrm and Hyprland don’t like each other that much, I start a TTY and log in. While opening the TTY the second monitor stays in the light Gray Lightdrm background colour. 
After typing Hyprland in my TTY, the main Monitor displays Hyprland, but the second monitor stays in Lightdrm. 
hyprctl monitors
```
Monitor eDP-1 (ID 0):
	1920x1080@60.007000 at 0x1080
	description: BOE 0x092A (eDP-1)
	make: BOE
	model: 0x092A
	serial: 
	active workspace: 4 (4)
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1

Monitor HDMI-A-1 (ID 1):
	1920x1080@60.000000 at 0x0
	description: Ancor Communications Inc ASUS VS247 G9LMTF089294 (HDMI-A-1)
	make: Ancor Communications Inc
	model: ASUS VS247
	serial: G9LMTF089294
	active workspace: 2 (2)
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
```
hyprland.conf
```
monitor=eDP-1,1920x1080,0x1080,1
monitor=HDMI-A-1,1920x1080,0x0,1
```

**Comment by vaxerski** [comment]
you mean lightdm?

Is this a laptop with a dedicated gpu?

**Comment by Bkeinn** [comment]
Yea, I think one in the cpu and one dedicated

**Comment by Bkeinn** [comment]
The link in the wiki says that the bug has been fixed(https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3451)

**Comment by vaxerski** [comment]
then that is a problem with your configuration, not hyprland. Possibly a driver bug as well.

**Comment by vaxerski** [comment]
> The link in the wiki says that the bug has been fixed(https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3451)

"fixed", if you read the issue you linked you'll see you need to apply a patch or envvar.

**Comment by Bkeinn** [comment]
Sorry but where should I add WLR_RENDERER=vulkan

**Comment by vaxerski** [comment]
hyprland does not support vulkan

**Comment by Bkeinn** [comment]
I am really sorry but I don't know were I should add this.

**Comment by vaxerski** [comment]
to your wrapper script, which is explained in the wiki, [here](https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#launching-hyprland-part-1)
