### ISSUE TITLE
socket2 no `urgent` event

### ISSUE THREAD

**Issue by latipun7** [hyprwm/Hyprland#1447]
Hyprland v0.21.0beta implement new [workspace urgency hint](https://github.com/hyprwm/Hyprland/pull/1379).
But socket2 not emitting `urgent` event as the [documentation stated](https://wiki.hyprland.org/0.21.0beta/IPC/#events-list). 

## Step to Reproduce

- workspace 1, open wezterm (terminal), run `socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" -`
- workspace 2, open browser
- workspace 4, open kitty, run `sleep 2 && printf '\a'`
- go to workspace 2
- go to workspace 1
- bell is ringing (but didn't saw `urgent` event at the socat output).
- CTRL+C the socat output.
- on wezterm, run `hyprctl dispatch focusurgentorlast ""`
- successfully jump to kitty window at workspace 4 (not the last window which is browser at workspace 2).

<details>
<summary>socat output of socket2</summary>

```log
❯ socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" -
activewindow>>org.wezfurlong.wezterm,socat
activewindow>>,
workspace>>4
activewindow>>kitty,latipun@ArchROG:~
activewindow>>kitty,sleep 2 && printf '\a'
activewindow>>,
workspace>>2
activewindow>>Brave-browser,Variables | Hyprland Wiki - Brave
activewindow>>,
workspace>>1
activewindow>>org.wezfurlong.wezterm,socat
^C%
```

</details>

### Expected Behavior

`urgent>>WINDOWADDRESS` should appear at the socat output of socket2.

### Current Behavior

No `urgent` event at the socket2 output. But successfully jump to urgent window using dispatcher.
The current behavior didn't allow me to watch the event for script to watch urgency.

Thank you.

**Comment by vaxerski** [comment]
fixed in 4c4d3b3aa54d8b1a150715c8b4a4f138bd3dfcb4
