### ISSUE TITLE
Crash on minimize

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#1451]
So I went and testing the minimize option. When I clicked the minimize button in easyeffects, it instantly freezed and crashed after a about a minute.
[coredump.txt](https://github.com/hyprwm/Hyprland/files/10530336/coredump.txt)
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/10530337/hyprland.txt)

**Comment by vaxerski** [comment]
fixed in 32381fe6c4e33232401d7a74f587ee7296a61fcf

**Comment by EysseW** [comment]
It's not crashing anymore! The feature doesn't work though. When I minimize something, nothing happens to it at all. Do I have to make a workspace named "minimized"?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/215343760-1d78e2f8-f1ae-4845-b97a-59fb6e3ce449.png)

works for me. easyeffects tested. This is only an IPC event, handling is down to you.

**Comment by EysseW** [comment]
Got it! Thanks!

**Comment by EysseW** [comment]
I am also noticed, after using it for a while, that waybar doesn't activate the IPC event. Is this something else?
