### ISSUE TITLE
hyprctl - movetoworkspace with 2 arguments doesn't function

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#1452]
`hyprctl dispatch move to workspace <workspace> <window>` doesn't do anyhthing. It's the same for `hyprctl dispatch movetoworkspacesilent <workspace> <window>` . It does, strangely enough, return "ok" when run.

```
Hyprland, built from branch main at commit 32381fe6c4e33232401d7a74f587ee7296.
flags: (if any)
```

**Comment by vaxerski** [comment]
`"workspace window"`?

**Comment by EysseW** [comment]
https://imgur.com/a/ny4XI1J
This

**Comment by vaxerski** [comment]
well then you're missing a comma no?

**Comment by EysseW** [comment]
Comma's Arent used in the hyprctl command, are they? I have, however, tried that as well, without luck.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/215447583-088766a9-322c-49f4-b44a-4204e39513a7.png)

works for me

**Comment by JustSimplyKyle** [comment]
Yeah, remember to include 0x(it will be automatically included if you use `hyprctl clients -j`)
`hyprctl dispatch dispatch_name` only accepts one argument, so when there is more the one(the case here), you have to split comma it.

**Comment by EysseW** [comment]
Right. I am sure I tried all of above things. I did the comma, the 0x and the correct order. But probably not all at the same time. I'll try if it works when I'm home, but it most likely will. I'll also look if I can contribute to making it clearer in the wiki :)

**Comment by EysseW** [comment]
Yep, works!
