### ISSUE TITLE
Maximizing floating window with no_gaps_when_only enabled loses border and rounded corners

### ISSUE THREAD

**Issue by eriedaberrie** [hyprwm/Hyprland#1453]
### Steps to reproduce
1. Enable `no_gaps_when_only`
2. `hyprctl dispatch fullscreen 1` on a floating window
3. Unmaximize it
### Expected behavior
The window returns to normal, regaining its borders and rounded corners.
### Observed behavior
The window unmaximizes as expected, but without any borders or rounded corners.

**Comment by vaxerski** [comment]
fixed in eaf0fb14c933e49342afb0ae421e992dd84df8b9
