### ISSUE TITLE
Mouse scrolling does not work immediately after opening a new tab in Firefox/Chrome

### ISSUE THREAD

**Issue by mhats** [hyprwm/Hyprland#1456]
### Steps to reproduce
1. Open firefox/chrome and visit a site
2. Right click on a link and click on "Open Link in a new tab"
3. Now in the old page, try to scroll using mouse wheel or touchpad

### Expected behavior
The page scrolls

### Observed behavior
The page does not move. However, using the arrow keys works. Also, if we move the cursor and try again, the scrolling works.

**Comment by vaxerski** [comment]
fixed in 11234529dbc5f85fc46df479f563c2c563afe9c2
