### ISSUE TITLE
Artifacts on external screen

### ISSUE THREAD

**Issue by simonkampe** [hyprwm/Hyprland#1459]
When using my external monitor (USB C connection) there are artifacts when redrawing the windows and/or mouse. They are black squares mostly, with some triangular features. Seems to be related to damage tracking.

I tried to record it with OBS studio, but funnily enough it does not show up in the video.

`hyprctl monitors` gives:

```
Monitor eDP-1 (ID 0):
	3840x2160@60.000000 at 0x0
	description: California Institute of Technology 0x1500 (eDP-1)
	make: California Institute of Technology
	model: 0x1500
	serial:
	active workspace: 4 (4)
	reserved: 0 42 0 0
	scale: 1.75
	transform: 0
	focused: yes
	dpmsStatus: 1

Monitor DP-2 (ID 1):
	5120x1440@59.977001 at 2194x0
	description: Dell Inc. Dell U4919DW DMRWTY2 (DP-2)
	make: Dell Inc.
	model: Dell U4919DW
	serial: DMRWTY2
	active workspace: 8 (8)
	reserved: 0 42 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
```

It is DP-2 that causes problems.

My hardware is a Thinkpad P1 Gen 3, nvidia drivers are enabled but in hybrid mode. The displayports on USB C seems to go through the Nvidia card though.

`inxi --graphics`:

```
Graphics:  Device-1: Intel CometLake-H GT2 [UHD Graphics] driver: i915 v: kernel
           Device-2: NVIDIA TU117GLM [Quadro T1000 Mobile] driver: nvidia v: 525.85.05
           Device-3: Chicony Integrated Camera type: USB driver: uvcvideo
           Display: wayland server: X.org 1.20.14 driver: loaded: nvidia note: n/a (using device driver)
           resolution: <missing: xdpyinfo>
           OpenGL: renderer: llvmpipe (LLVM 14.0.6 256 bits) v: 4.5 Mesa 22.2.5
```

**Comment by vaxerski** [comment]
well if it does not show up in OBS then it's safe to assume it's a driver bug / broken cable or monitor

**Comment by simonkampe** [comment]
> well if it does not show up in OBS then it's safe to assume it's a driver bug / broken cable or monitor

Normally I'd agree with this, so just now I tested with the same monitor, same cable, same kernel & video drivers, same everything in KDE instead, and the issue is not present there.

The only thing different is that KDE reports the refresh rate as 60 Hz instead. But I do not know if that is just a rounding of the 59.977001 Hz I see in wlr-randr/hyprctl. Is there any way to force the monitor to 60 Hz?

**Comment by vaxerski** [comment]
KDE is a completely different base. How about sway-git?

> The only thing different is that KDE reports the refresh rate as 60 Hz instead. But I do not know if that is just a rounding of the 59.977001 Hz I see in wlr-randr/hyprctl. Is there any way to force the monitor to 60 Hz?

it's a rounding.

**Comment by simonkampe** [comment]
> KDE is a completely different base. How about sway-git?

Ah, you are correct. In sway 1.7 it shows the same artifacts, I can test the later versions of sway also if necessary.

**Comment by vaxerski** [comment]
most likely means a damaged cable/monitor that kde just has some band-aid for. At any rate, wlroots issue and not hl.

**Comment by simonkampe** [comment]
If someone stumbles upon this later: I tried with another cable and other monitors (via a dell WD19 dock), and the problem persists. BUT I found that if I put the nvidia card first with `WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0` the flickering disappears but the internal display stops working. Will update this if I find a combination that works.

**Comment by BenMac31** [comment]
I am also running into the same issue on my laptop. Here is my relevant system info:
- using nvx for toggling GPU.
- Razer Blade 14
- NVIDIA Geforce RTX 3070 Ti Laptop
- Arch Linux
I also do not get this issue on Gnome.

**Comment by BenMac31** [comment]
This wlroots issue may be related and a better place to address the problem:
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/2870
