### ISSUE TITLE
Cannot zoom in on firefox wayland

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#146]
**Describe the bug**

When I use firefox I cannot zoom in with the touchpad on wayland this works in wayfire.

**Comment by godalming123** [comment]
Coul'dnt find an option (here)[https://wayland.freedesktop.org/libinput/doc/latest/configuration.html]

**Comment by godalming123** [comment]
Also it would be nice to have natural scroll on touchpads but normal scroll on mouase

**Comment by Kara-Zor-El** [comment]
I just tested this as well. I can confirm that this is reproducible.

**Comment by NotAShelf** [comment]
I can confirm this is Hyprland specific and is not present on other tested Wayland compositors - this is also not associated with Firefox's zoom setting, as zoomin is allowed by default. Can't think of a reason why.

**Comment by vaxerski** [comment]
should be fixed in ef24329495d173b195a830727bfe7191c1761d12

lmk, as i dont own a touchpad.

**Comment by NotAShelf** [comment]
Testing in a minute.

**Comment by NotAShelf** [comment]
Seems to be working on the latest commit.

**Comment by godalming123** [comment]
Yay
