### ISSUE TITLE
Problem with chrome password store

### ISSUE THREAD

**Issue by goof03** [hyprwm/Hyprland#1460]
Hi, i come from plasma wayland version without problem but when i launch chrome in Hyprland i cant get my stored passwords working. i don't know why ?

**Comment by vaxerski** [comment]
not a hyprland issue. Most likely you didnt read https://wiki.hyprland.org/Useful-Utilities/Must-have/ and don't have polkit or an auth agent / keyring running. Hyprland has nothing to do with your passwords.

**Comment by goof03** [comment]
Ok you're right … I'm an idiot … Sorry for the noise...  :smile:

**Comment by GustavoJCL** [comment]
i configured acording to the wiki, but still kwallet didn't work in hyprland, this is the config:
```
exec-once = /usr/lib/pam_kwallet_init
exec-once = kwalletd5
exec-once = kded5
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = NetworkManager
exec-once = swaync
# excec-once = wpaperd
exec-once = waybar & hyprpaper
```
