### ISSUE TITLE
Kate takes too long to open

### ISSUE THREAD

**Issue by XxRiKxX** [hyprwm/Hyprland#1461]
`qt.qpa.wayland: Wayland does not support QWindow::requestActivate()` is what I get in the terminal. Though geany does not have any problems launching.
I have `QT_QPA_PLATFORM="wayland;xcb"` in my env

**Comment by vaxerski** [comment]
it's a problem with the dbus connection in some qt apps?

using `dbus-launch` fixes the issue but introduces event more.

Does this happen on sway-git too?

**Comment by XxRiKxX** [comment]
dolphin launches just fine though.
and what kind of problems are you referring too?
and I have not tried it with sway though

**Comment by vaxerski** [comment]
try it with sway-git.

> and what kind of problems are you referring too?

using dbus-launch for me would fix the kate problem but all other dbus/keyring stuff would refuse to work.
