### ISSUE TITLE
`hyprctl dispatch` forces last argument for actions with no arguments

### ISSUE THREAD

**Issue by ozwaldorf** [hyprwm/Hyprland#1463]
for example

```sh
● hyprctl dispatch exit
Usage: hyprctl dispatch <dispatcher> <arg>
            Execute a hyprland keybind dispatcher with the given argument
```

But it should instead just exit.

**Comment by JustSimplyKyle** [comment]
`hyprctl dispatch exit x` works. You just put anything in the arg part when there are no args.
Although I agree, this can be annoying.

**Comment by ozwaldorf** [comment]
yeah i generally use a random letter to workaround
