### ISSUE TITLE
ext_workspace_unstable: send output_enter when wl_output is bound late

### ISSUE THREAD

**Issue by MaxVerevkin** [hyprwm/Hyprland#1466]
Analogous to https://github.com/swaywm/wlroots/issues/2466

## Steps to reproduce

- Bind `zext_workspace_manager_v1`
- Then bind `wl_output`s

## Expected behavior

`output_enter` event is eventually sent.

## Actual behavior

`output_enter` is never sent.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10561458/patch.txt)

try this

**Comment by MaxVerevkin** [comment]
Didn't fix it

**Comment by MaxVerevkin** [comment]
By the way, currently group handles are not destroyed when output is disconnected.
