### ISSUE TITLE
Xwayland popups have visual artifacts after resizing.

### ISSUE THREAD

**Issue by archhaze24** [hyprwm/Hyprland#1468]
Intellij IDEA-based IDEs (in this case CLion) have strange artifacts with popups. For example, with code autocompletion, or find action (Ctrl + Shift + A).

Example:

https://user-images.githubusercontent.com/49359990/216067936-7eb4245e-d247-4b25-bc16-b4237cb0d11c.mp4

This seems to happen while the popup window is resizing itself.
`_JAVA_AWT_WM_NONREPARENTING` is set to 1.
Enabling or disabling animations don't help to solve the issue. Same with no_vfr or animate_manual_resizes.

Hyprland version is `0.21.0beta-2`. Distro is Arch. IDE is installed through JetBrains Toolbox.

**Comment by vaxerski** [comment]
where artifacts? you mean the stretching? that's because intellij is stupid and in xwayland.

**Comment by archhaze24** [comment]
@vaxerski 
yes. this stretching.
also forgot to mention that this does not happen on sway or gnome wayland.

**Comment by vaxerski** [comment]
gnome is a bad comparison.

Hm, can you record it on sway-git, with borders enabled?

**Comment by archhaze24** [comment]
@vaxerski 
on sway-git:

https://user-images.githubusercontent.com/49359990/216089949-1a3a0cbb-4fce-485e-8979-70e83d3f3379.mp4

**Comment by vaxerski** [comment]
huh, interesting.

**Comment by s8k3** [comment]
I experience the same thing with rofi. It seems to scale the current content to the initial window size:

![rofi_initial](https://user-images.githubusercontent.com/81437841/216362719-65a814b7-44fe-4327-a8f2-f1a51fdc56a1.png)

![rofi_search](https://user-images.githubusercontent.com/81437841/216363751-d600aae8-4eef-4c41-a20c-87fbec6a609b.png)

**Comment by amilonop** [comment]
Same, any popup window seems to have issues, rofi, emacs buffers, Ulauncher.
There is the resizing and also the flickering.

**Comment by amilonop** [comment]
@vaxerski any update on this issue, or any way we can help provide you more input or cases?

**Comment by vaxerski** [comment]
it's generally the popup's fault. You can help though by making a pr.

**Comment by romanstingler** [comment]
as soon as a window (in my case terminal) is opened and the window is resized, probably the same issue happens

![2023-06-28T22:27:34,223287879+02:00](https://github.com/hyprwm/Hyprland/assets/5576250/08396ffc-1fb5-4aca-b14a-1b99ad503b0a)
![2023-06-28T22:28:48,122557720+02:00](https://github.com/hyprwm/Hyprland/assets/5576250/099a1113-96b9-4804-804d-4649a23f5279)

**Comment by archhaze24** [comment]
i think now it's save to say that this happens to all applications which runs with xwayland

**Comment by romanstingler** [comment]
is this issue still present for you

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

**Comment by romanstingler** [comment]
it doesn't happen on the Wayland version of JetBrains products. 
I can test XWayland "tomorrow"

**Comment by romanstingler** [comment]
the jetbrains issue is resolved, the only issue, maybe we have already another one open is the redrawing speed of resized windows (good visible in vscode), but this should be another issue.
