### ISSUE TITLE
Crash with multiple users on same machine

### ISSUE THREAD

**Issue by gammons** [hyprwm/Hyprland#1470]
:wave: Hello!  I am seeing that Hyprland does not like it when there are multiple users on the same machine who use hyperland.  My use case is that I have a machine that I like to use for both work and non-work, so I have 2 separate linux users (`grant` and `grant-work`).  

The issue comes from the fact that Hyprland creates a parent directory in `/tmp`.  So if I run Hyprland as `grant`,  the `/tmp/hypr` folder will be created, owned by `grant`.  If I then switch over to `grant-work` and attempt to run Hyprland, it will crash with a permissions issue, because `grant-work` cannot create a sub-directory in `/tmp/hypr`. 

The main issue stems from line 41 of Main.cpp:

https://github.com/hyprwm/Hyprland/blob/445f8c71c50ed9cdd72299b2ddf696b7baeb1b03/src/main.cpp#L41

I am wondering if we could change the temporary directory to include the username, so that multiple instances of Hyprland could be run on separate TTYs.  

I am happy to create a PR, but I'd love some guidance from the leadership of this project first :slightly_smiling_face:

**Comment by vaxerski** [comment]
FUCK
I thought I fixed it a month ago and yet forgot to remove that line...

1a41f729a38a57c7e925237efdeeaad1df14020e

**Comment by gammons** [comment]
ah nice, so it wasn't needed at all!  Thanks @vaxerski
