### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by senarijit2021** [hyprwm/Hyprland#1472]
Getting the following error while trying to install the Hyprland using meson:

`
make clear
make[1]: Entering directory '/home/arijitsen/Hyprland'
rm -rf build
rm -f *.o *-protocol.h *-protocol.c
rm -f ./hyprctl/hyprctl
rm -rf ./subprojects/wlroots/build
make[1]: Leaving directory '/home/arijitsen/Hyprland'
make fixwlr
make[1]: Entering directory '/home/arijitsen/Hyprland'
sed -i -E 's/(soversion = 12)([^032]|$)/soversion = 12032/g' subprojects/wlroots/meson.build
rm -rf ./subprojects/wlroots/build
make[1]: Leaving directory '/home/arijitsen/Hyprland'
cd ./subprojects/wlroots && meson build/ --buildtype=release && ninja -C build/ && cp ./build/libwlroots.so.12032 /usr/lib/ && cd ../..
The Meson build system
Version: 1.0.0
Source dir: /home/arijitsen/Hyprland/subprojects/wlroots
Build dir: /home/arijitsen/Hyprland/subprojects/wlroots/build
Build type: native build
Project name: wlroots
Project version: 0.17.0-dev
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Walloca: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.16.3)
DEPRECATION: CMake support for versions <3.17 is deprecated since Meson 0.62.0.
|
|   However, Meson was only able to find CMake 3.16.3.
|
|   Support for all CMake versions below 3.17.0 will be removed once
|   newer CMake versions are more widely adopted. If you encounter
|   any errors please try upgrading CMake to a newer version first.

Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-server

meson.build:105:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.

A full log can be found at /home/arijitsen/Hyprland/subprojects/wlroots/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
make: *** [Makefile:167: install] Error 1
❯ vim /home/arijitsen/Hyprland/subprojects/wlroots/build/meson-logs/meson-log.txt

`

**Comment by vaxerski** [comment]
> Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)

please read

**Comment by akmishra99** [comment]
I am getting following error while try to build I am using ./build-ubuntu-23.sh (fromhttps://gist.github.com/Vertecedoc4545/6e54487f07a1888b656b656c0cdd9764 )script to build it ,my system is ubuntu 23.04 

The Meson build system
Version: 1.0.1
Source dir: /home/akmishra/scratch_apr_18_2024/HyprSource/hyprland-source/subprojects/wlroots
Build dir: /home/akmishra/scratch_apr_18_2024/HyprSource/hyprland-source/subprojects/wlroots/build
Build type: native build
Project name: wlroots
Project version: 0.17.0-dev
C compiler for the host machine: cc (gcc 12.3.0 "cc (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0")
C linker for the host machine: cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Walloca: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Found CMake: /usr/bin/cmake (3.25.1)
Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-server

meson.build:105:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.

A full log can be found at /home/akmishra/scratch_apr_18_2024/HyprSource/hyprland-source/subprojects/wlroots/build/meson-logs/meson-log.txt
Could not install libwlroots to /usr/lib/libwlroots.so.12032
cd subprojects/udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B./build -G Ninja && cmake --build ./build --config Release --target all -j12 && cd ../..
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 12.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python3: /usr/bin/python3 (found version "3.11.4") found components: Interpreter 
Building itab.c/itab.h...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akmishra/scratch_apr_18_2024/HyprSource/hyprland-source/subprojects/udis86/build
[7/7] Linking C static library libudis86/liblibudis86.a
make protocols
make[1]: Entering directory '/home/akmishra/scratch_apr_18_2024/HyprSource/hyprland-source'
private-code \
        /stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.c
make[1]: private-code: No such file or directory
make[1]: *** [Makefile:19: xdg-shell-protocol.c] Error 127
make[1]: Leaving directory '/home/akmishra/scratch_apr_18_2024/HyprSource/hyprland-source'
make: *** [Makefile:190: install] Error 2
 NOW YOU HAVE HYPRLAND INSTALLED!!! 
 Remember to add  

 misc {
    suppress_portal_warnings = true 
 } 

to  hyprland.conf 
akmishra [
