### ISSUE TITLE
Dunst not showing notifications

### ISSUE THREAD

**Issue by XxRiKxX** [hyprwm/Hyprland#1476]
i have it in my exec-once. I dont have any other notif daemon running `WARNING: Setting always_run_scripts in section global doesn't exist
CRITICAL: [dbus_cb_name_lost:1044] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '34974'.`. It works on bspwm, but for some reason its not working here

**Comment by vaxerski** [comment]
that's obviously an issue with your system...? dunst works for everyone else. Seems like you have dunst already running before your start hyprland, which you should not.

**Comment by vaxerski** [comment]
at any rate, this is a dbus error, and hyprland has nothing to do with that. It clearly states it's acquired by dunst with pid 34974

**Comment by barbiefan** [comment]
Even if you don't start dunst dbus will start it on first notification. You can check it - remove it from hypr config and do notify-send 123.
