### ISSUE TITLE
No border when only one window

### ISSUE THREAD

**Issue by theRealCarneiro** [hyprwm/Hyprland#1478]
If there's only one window on the workspace, remove the window's border

**Comment by vaxerski** [comment]
dwindle
https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config
master
https://wiki.hyprland.org/Configuring/Master-Layout/#config

please consider reading the wiki

**Comment by theRealCarneiro** [comment]
The only option I can see on master layout is no_gaps_when_only, and that's not the same thing

**Comment by vaxerski** [comment]
then you can script it by altering the window prop with hyprctl when there's only one window on a workspace.

**Comment by MrAkells** [comment]
I am also looking for something similar. Although it seems to me that it would not be difficult to add a setting for this, I won't ask the developer because I can't make the necessary pull request myself. However, perhaps someone can share a similar script that removes the border when there is only one window on the desktop?

**Comment by vaxerski** [comment]
with 4eb42fab7bb1b1d6c8fec4682c8c1de6dca7049b you can now do this via

```
windowrulev2 = noborder, onworkspace:1
```

**Comment by altayhunter** [comment]
> ```
> windowrulev2 = noborder, onworkspace:1
> ```

This doesn't seem to work anymore (or perhaps it never did). Instead of removing the border when there's only one window on a workspace, it removes borders from all windows on workspace 1 and has no effect on other workspaces.

**Comment by vaxerski** [comment]
onworkspace changed syntax in 0.39.0. See https://wiki.hyprland.org/Configuring/Workspace-Rules/#workspace-selectors

Now it would be `[t1]` instead of `1`

**Comment by altayhunter** [comment]
Thanks! Just to clarity for others, the updated complete rule is:
```
windowrulev2 = noborder, onworkspace:w[t1]
```

**Comment by shafayetejaman** [comment]
not working on 
Hyprland 0.53.1

**Comment by Zebra2711** [comment]
> not working on Hyprland 0.53.1

```ini
windowrule = border_size 0, match:workspace w[t1]
```
