### ISSUE TITLE
SUPER_ESC bind SUPER

### ISSUE THREAD

**Issue by coffebar** [hyprwm/Hyprland#1479]
Both of this bindings in hyprland.conf
```
bind = SUPER_ESC, S, exec, dunstify hello
bind = SUPER, S, exec, dunstify hello

```
give the same bindings:

> bind
> 	modmask: 64
> 	submap:
> 	key: S
> 	keycode: -1
> 	dispatcher: exec
> 	arg: dunstify hello
> 
> bind
> 	modmask: 64
> 	submap:
> 	key: S
> 	keycode: -1
> 	dispatcher: exec
> 	arg: dunstify hello

So when i bind 

`bind = SUPER_ESC, S, exec, dunstify hello`

it will work on press Super+s

Is it possible to fix this?

**Comment by vaxerski** [comment]
ESC is not a mod. 

https://wiki.hyprland.org/Configuring/Variables/#variable-types
