### ISSUE TITLE
Crash when closing the lid

### ISSUE THREAD

**Issue by 875d** [hyprwm/Hyprland#1483]
I have the idle_inhibitor waybar module.

I click on it to put in in "activated" mode, in order to inhibit suspend on lid closing.

I close the lid.

I connect my external monitor.

I can't see anything on the external monitor.

I re-open the lid.

Hyprland has crashed.

Here is the last part of my journal starting from when I close the lid:

[journalctl.txt](https://github.com/hyprwm/Hyprland/files/10608233/journalctl.txt)

**Comment by russelltg** [comment]
I thin this bug is easily reproducible with 

```bash
hyprctl keyword monitor eDP-1,disable ; sleep 5; hyprctl keyword monitor eDP-1,preferred,auto,1.0
```

replacing the eDP-1 with a single display that is plugged in.

**Comment by russelltg** [comment]
Maybe related to https://github.com/hyprwm/Hyprland/issues/1728 and maybe https://github.com/hyprwm/Hyprland/issues/804
