### ISSUE TITLE
Trailing whitespace after an argument followed by a comment seems be treated as part of the argument

### ISSUE THREAD

**Issue by nativerv** [hyprwm/Hyprland#1486]
That is, if trailing comments are at all allowed, of course. They seem to be in binds without argument, though.

`bind = $myMod SHIFT, i, changegroupactive, b # previous tab` -> cycles forward instead of backward (falls back to default?)
`bind = $myMod SHIFT, o, changegroupactive, f # next tab` -> works as expected, but actually also falls back to forward which happens to be correct
`bind = $myMod SHIFT, i, changegroupactive, b ` (no comment, with trailing space) -> cycles backward
`bind = $myMod SHIFT, i, changegroupactive, b` (no comment, no trailing space) -> cycles backward

**Comment by vaxerski** [comment]
should be fixed with 760b37f71d200643d3e267472e5cc290d38d1a53
