### ISSUE TITLE
vmware-view

### ISSUE THREAD

**Issue by Gambrivius** [hyprwm/Hyprland#1487]
In every other window manager I've tried, vmware-view correctly opens:
https://aur.archlinux.org/vmware-horizon-client.git

In Hyprland, the program launches but does not actually open a window.

**Comment by Gambrivius** [comment]
https://aur.archlinux.org/packages/vmware-horizon-client

**Comment by mrlnnl** [comment]
I experience the same bug. Tried latest version available of vmware-horizon-client 2212.1-1 and hyprland-git. No window appears. 

[hyprland.log](https://github.com/hyprwm/Hyprland/files/10811342/hyprland.log)

**Comment by AaronFoley** [comment]
This appears to have been fixed by https://github.com/hyprwm/Hyprland/commit/7e523e4d5e526bdf5ab86a8f4fe37efeef356707

**Comment by vaxerski** [comment]
ah, yeah.

**Comment by Gambrivius** [comment]
Confirmed this is working for me as well.  Thanks!
