### ISSUE TITLE
Dgpu gets activated when using xwayland

### ISSUE THREAD

**Issue by Albert24GG** [hyprwm/Hyprland#1488]
After some recent update, whenever I use a xwayland  program, dgpu constantly gets activated and suspended in an interval of about 2-3 seconds and this behavior stops only after rebooting and not running xwayland. This also happens by just running ```xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2```.

**Comment by vaxerski** [comment]
can you do a git bisect

**Comment by Albert24GG** [comment]
I installed hyprland via `hyprland-hidpi-xprop-git` aur package, so I am not sure how to do the git bisect. I can tell you that some update from yesterday or today caused the issue.

**Comment by vaxerski** [comment]
clone the repo manually then. What's the issue?

**Comment by Albert24GG** [comment]
Can't find a commit that works properly, it may also be another wayland component that broke.

**Comment by Albert24GG** [comment]
The issue is gone after a fresh install of linux.
