### ISSUE TITLE
Feature request: tap-to-click configuration (LMB, MMB, RMB)

### ISSUE THREAD

**Issue by coffebar** [hyprwm/Hyprland#1489]
> tap-to-click | Tapping on the touchpad with 1, 2, or 3 fingers will send LMB, RMB, and MMB respectively.

Looking for option to change buttons order in tap-to-click:

change from `LMB, RMB, MMB` to `LMB, MMB, RMB`.
2 finger click -> MMB

**Comment by vaxerski** [comment]
@fufexan probably some libinput prop no?

**Comment by coffebar** [comment]
[Here is similar issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/456) in other Wayland compositor  (resolved and merged). 
Maybe that commit will be useful to find correct prop and values.
