### ISSUE TITLE
Viewporter does not work properly with layer-shell

### ISSUE THREAD

**Issue by MaxVerevkin** [hyprwm/Hyprland#1490]
How the client is supposed to look:

![image](https://user-images.githubusercontent.com/34583604/216785681-f99e462c-514c-43ac-858a-e7c94749eeaf.png)

How it actually looks when using wp_viewport:

![image](https://user-images.githubusercontent.com/34583604/216785722-fb9c5f04-c6fa-4a00-8d96-b533ca463023.png)

What the client does:

```
[wayrs]  -> wl_registry@2.bind(46,wl_output@12)
[wayrs]  -> wl_compositor@5.create_surface(wl_surface@13)
[wayrs]  -> wp_fractional_scale_manager_v1@8.get_fractional_scale(wp_fractional_scale_v1@14,13)
[wayrs]  -> zwlr_layer_shell_v1@6.get_layer_surface(zwlr_layer_surface_v1@15,13,12,2,"i3bar-river")
[wayrs]  -> zwlr_layer_surface_v1@15.set_size(0,20)
[wayrs]  -> zwlr_layer_surface_v1@15.set_anchor(13)
[wayrs]  -> zwlr_layer_surface_v1@15.set_margin(0,0,5,0)
[wayrs]  -> zwlr_layer_surface_v1@15.set_exclusive_zone(25)
[wayrs]  -> wp_viewporter@7.get_viewport(wp_viewport@16,13)
...
[wayrs] wp_fractional_scale_v1@14.preferred_scale(144)
[wayrs] wl_callback@17.done(136803798)
[wayrs]  -> wp_viewport@16.set_source(0,0,1919,24)
[wayrs]  -> wp_viewport@16.set_destination(1599,20)
[wayrs]  -> wl_surface@13.attach(19,0,0)
[wayrs]  -> wl_surface@13.damage(0,0,2147483647,2147483647)
[wayrs]  -> wl_surface@13.commit()
```

**Comment by vaxerski** [comment]
huh, odd. is that i3bar-river? Can I get a reproducible example case (probably a config for i3bar-river)

**Comment by vaxerski** [comment]
tested on my laptop and it works properly, but fractionalScale is not bound. Maybe you can make a branch with wp-fs-v1 so that I can test?

hyprpaper uses wp-fs-v1 and it's working fine as far as I can tell.

**Comment by MaxVerevkin** [comment]
Yes, I pushed my attempt to implement fractional scaling to https://github.com/MaxVerevkin/i3bar-river/tree/wpfs. Min config:

```
$ cat .config/i3bar-river/config.toml 
command = "sh -c 'echo hello_world; sleep 99999'"
```

**Comment by MaxVerevkin** [comment]
> hyprpaper uses wp-fs-v1 and it's working fine as far as I can tell.

Hm...

```
$ WAYLAND_DEBUG=1 build/hyprpaper 2>&1 | rg viewpo
[3289227.537] wl_registry@2.global(12, "wp_viewporter", 1)
[3289227.539]  -> wl_registry@2.bind(12, "wp_viewporter", 1, new id [unknown]@5)
[3289227.969]  -> wp_viewporter@5.get_viewport(new id wp_viewport@16, wl_surface@11)
[3289274.831]  -> wp_viewport@16.set_destination(1919, 1079)
[3289289.401]  -> wp_viewport@16.set_destination(1919, 1079)
```

**Comment by vaxerski** [comment]
AFAIK with scaling you should _only_ use the destination, as no cropping is needed.

**Comment by MaxVerevkin** [comment]
That's weird that binding wp-fs changes the semantics of wp-vp. Might be worth opening an issue at wayland-protocols for clarification.

> ```
> [3289274.831]  -> wp_viewport@16.set_destination(1919, 1079)
> [3289289.401]  -> wp_viewport@16.set_destination(1919, 1079)
> ```

This still seems wrong because the physical size of my screen is 1920x1080, and with scale=1.2 it should be 1600x900.

Maybe offtopic, but this seems wrong to:

```
$ WAYLAND_DEBUG=1 build/hyprpaper 2>&1 | rg set_buffer_scale
[1813637.325]  -> wl_surface@11.set_buffer_scale(2)
[1813647.356]  -> wl_surface@11.set_buffer_scale(2)
```

Spec:

> The wl_surface buffer scale should remain set to 1.

**Comment by vaxerski** [comment]
possible. Do I look like I carefully read the spec? lol

mostly took code from the test clients.

**Comment by MaxVerevkin** [comment]
> AFAIK with scaling you should only use the destination, as no cropping is needed. Can't say I fully understand their reasoning in the spec, though.

Apparently set_source is optional in general, didn't know that.

**Comment by MaxVerevkin** [comment]
After https://github.com/hyprwm/Hyprland/commit/859d6b9b8a961669c814632bbc7a1a9d94556551 something different happens: 
![image](https://user-images.githubusercontent.com/34583604/218045440-0c5e976a-112d-4cec-9d80-4db9e780a5c8.png)

(The top uses `set_buffer_scale(2)`, the bottom uses viewporter)

**Comment by vaxerski** [comment]
possible.

Hyprpaper uses wp-fs-v1 and works. See that impl.

**Comment by MaxVerevkin** [comment]
This is not even related to fractional scaling. The client may not even bind wp-fs, receive "scale=2" event, render with scale of 2 and instead of setting "buffer_scale=2" the client may use wp-vp to scale the buffer down. This is a perfectly valid use of wp-vp.

**Comment by MaxVerevkin** [comment]
> Hyprpaper uses wp-fs-v1 and works

And it is wrong.

> ```
> [3289274.831]  -> wp_viewport@16.set_destination(1919, 1079)
> [3289289.401]  -> wp_viewport@16.set_destination(1919, 1079)
> ```
> This still seems wrong because the physical size of my screen is 1920x1080, and with scale=1.2 it should be 1600x900.

**Comment by vaxerski** [comment]
fixed in both hl and hp.

**Comment by MaxVerevkin** [comment]
Works!
