### ISSUE TITLE
Failed to enable second display on AMD iGPU

### ISSUE THREAD

**Issue by cswizard11** [hyprwm/Hyprland#1492]
Running a Ryzen 7950x CPU with integrated graphics (AMD ATI 17:00.0 Raphael) and a Radeon 6600 discrete GPU. When using 2 monitors, one connected to the discrete GPU, the other to the iGPU, the discrete head works, while the iGPU doesn't.

When testing with Qtile wayland (also wlroots based), both heads work as expected.

Log snippet:
[LOG] Instance Signature: 6867831a1b7f42033c2f326db5e63f95fda6084c_1675567926
[LOG] Hyprland PID: 780
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: matte
[LOG] Release: 6.1.9-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:39 +0000

[LOG] GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])
17:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c1) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Some legends are told, some turn to dust or to gold

[LOG] Hyprland init finished.
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 200 points, mem usage: 3.20kB, time to bake: 286.03µs. Estimated average calc time: 0.00µs.
[LOG] Creating the LayoutManager!
[LOG] Creating the ConfigManager!
[LOG] Creating the CHyprError!
[LOG] Creating the ThreadManager!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 200 points, mem usage: 3.20kB, time to bake: 3.90µs. Estimated average calc time: 0.00µs.
[LOG] Created a bezier curve, baked 200 points, mem usage: 3.20kB, time to bake: 3.99µs. Estimated average calc time: 0.00µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
[LOG] Hypr socket started at /tmp/hypr/6867831a1b7f42033c2f326db5e63f95fda6084c_1675567926/.socket.sock
[LOG] Creating the InputManager!
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Creating the Hypr OpenGL Renderer!
[LOG] Using: OpenGL ES 3.2 Mesa 22.3.4
[LOG] Vendor: AMD
[LOG] Renderer: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.49, 6.1.9-arch1-1)
[LOG] Supported extensions size: 149
[LOG] Creating the HyprRenderer!
[LOG] Creating the XWaylandManager!
[LOG] Registered signal for owner 16513160: 165131a0 -> 13ab6e20 (owner: XWayland Manager)
[LOG] Registered signal for owner 16513160: 165131b0 -> 13ab6e00 (owner: XWayland Manager)
[LOG] CHyprXWaylandManager started on display :0
[LOG] Creating the ProtocolManager!
[LOG] ToplevelExportManager started successfully!
[LOG] FractionalScaleManager started successfully!
[LOG] Creating the EventManager!
[LOG] Creating the HyprDebugOverlay!
[LOG] Registered signal for owner 158c3760: 158c3788 -> 13ab6d00 (owner: Backend)
[LOG] Registered signal for owner 1642cb30: 1642cb80 -> 13ab6ca0 (owner: XDG Shell)
[LOG] Registered signal for owner 1642cc00: 1642cc18 -> 13ab6c60 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc28 -> 13ab6c40 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc38 -> 13ab6c20 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc48 -> 13ab6c00 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc58 -> 13ab6be0 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc68 -> 13ab69c0 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc78 -> 13ab6980 (owner: WLRCursor)
[LOG] Hypr socket 2 started at /tmp/hypr/6867831a1b7f42033c2f326db5e63f95fda6084c_1675567926/.socket2.sock
[LOG] Registered signal for owner 1642cc00: 1642cc88 -> 13ab69a0 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cc98 -> 13ab6960 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cca8 -> 13ab6940 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642ccb8 -> 13ab6920 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642ccf8 -> 13ab6880 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cce8 -> 13ab6860 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cd08 -> 13ab6840 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642cd28 -> 13ab6820 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642ccc8 -> 13ab6800 (owner: WLRCursor)
[LOG] Registered signal for owner 1642cc00: 1642ccd8 -> 13ab67e0 (owner: WLRCursor)
[LOG] Registered signal for owner 158c3760: 158c3778 -> 13ab6bc0 (owner: Backend)
[LOG] Registered signal for owner 158c2568: 1645e798 -> 13ab6b60 (owner: Seat)
[LOG] Registered signal for owner 158c2568: 1645e7a8 -> 13ab6b40 (owner: Seat)
[LOG] Registered signal for owner 158c2568: 1645e7e8 -> 13ab6ac0 (owner: Seat)
[LOG] Registered signal for owner 158c2568: 1645e7f8 -> 13ab6aa0 (owner: Seat)
[LOG] Registered signal for owner 158c2568: 1645e7a8 -> 13ab6b40 (owner: Seat)
[LOG] Registered signal for owner 158c2568: 1645e7c8 -> 13ab6b20 (owner: Seat)
[LOG] Registered signal for owner 1645ea50: 1645ea70 -> 13ab6cc0 (owner: LayerShell)
[LOG] Registered signal for owner 1642c8e0: 1642c900 -> 13ab6d20 (owner: OutputLayout)
[LOG] Registered signal for owner 16421860: 16421898 -> 13ab6b00 (owner: OutputMgr)
[LOG] Registered signal for owner 16421860: 164218a8 -> 13ab6ae0 (owner: OutputMgr)
[LOG] Registered signal for owner 1642ce90: 1642cec0 -> 13ab6a80 (owner: InhibitMgr)
[LOG] Registered signal for owner 1642ce90: 1642ced0 -> 13ab6a60 (owner: InhibitMgr)
[LOG] Registered signal for owner 1642d0d0: 1642d0e8 -> 13ab6b80 (owner: PointerConstraints)
[LOG] Registered signal for owner 1645ebc0: 1645ebf0 -> 13ab6a40 (owner: XDGDecoMgr)
[LOG] Registered signal for owner 1642d2d0: 1642d300 -> 13ab6ba0 (owner: VirtPtrMgr)
[LOG] Registered signal for owner 1642d220: 1642d250 -> 13ab68a0 (owner: VKeyboardMgr)
[LOG] Registered signal for owner 16348480: 16348480 -> 13ab6a20 (owner: WLRRenderer)
[LOG] Registered signal for owner 1642d780: 1642d7b0 -> 13ab6a00 (owner: WLRIdleInhibitMgr)
[LOG] Registered signal for owner 1642c930: 1642c960 -> 13ab6900 (owner: PowerMgr)
[LOG] Registered signal for owner 1642dc00: 1642dc30 -> 13ab68e0 (owner: IMEMgr)
[LOG] Registered signal for owner 1642db50: 1642db80 -> 13ab68c0 (owner: TextInputMgr)
[LOG] Registered signal for owner 1642dcb0: 1642dcd8 -> 13ab6c80 (owner: ActivationV1)
[LOG] Registered signal for owner 158c22c0: 1642d470 -> 13ab6ce0 (owner: DRM)
[LOG] Registered signal for owner 158c37f0: 158c3950 -> 13ab69e0 (owner: Session)
[LOG] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Running on WAYLAND_DISPLAY: wayland-1
[LOG] Attached a keyboard with name Power Button
[LOG] Registered signal for owner 165ce7a0: 165bb100 -> 165ce7a8 (owner: Keyboard)
[LOG] Registered signal for owner 165ce7a0: 165bb0f0 -> 165ce810 (owner: Keyboard)
[LOG] Registered signal for owner 165ce7a0: 165bafd0 -> 165ce8e0 (owner: Keyboard)
[LOG] Registered signal for owner 165ce7a0: 165bb110 -> 165ce878 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Power Button"
[LOG] New keyboard created, pointers Hypr: 165ce7a0 and WLR: 165bafb8
[LOG] Attached a keyboard with name Video Bus
[LOG] Registered signal for owner 16596d40: 16599650 -> 16596d48 (owner: Keyboard)
[LOG] Registered signal for owner 16596d40: 16599640 -> 16596db0 (owner: Keyboard)
[LOG] Registered signal for owner 16596d40: 16599520 -> 16596e80 (owner: Keyboard)
[LOG] Registered signal for owner 16596d40: 16599660 -> 16596e18 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Video Bus"
[LOG] New keyboard created, pointers Hypr: 16596d40 and WLR: 16599508
[LOG] Attached a keyboard with name Power Button
[LOG] Registered signal for owner 165c1e40: 165a8ea0 -> 165c1e48 (owner: Keyboard)
[LOG] Registered signal for owner 165c1e40: 165a8e90 -> 165c1eb0 (owner: Keyboard)
[LOG] Registered signal for owner 165c1e40: 165a8d70 -> 165c1f80 (owner: Keyboard)
[LOG] Registered signal for owner 165c1e40: 165a8eb0 -> 165c1f18 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "power-button-1", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Power Button"
[LOG] New keyboard created, pointers Hypr: 165c1e40 and WLR: 165a8d58
[LOG] Attached a keyboard with name USB Camera: USB Camera
[LOG] Registered signal for owner 165a7400: 16695390 -> 165a7408 (owner: Keyboard)
[LOG] Registered signal for owner 165a7400: 16695380 -> 165a7470 (owner: Keyboard)
[LOG] Registered signal for owner 165a7400: 16695260 -> 165a7540 (owner: Keyboard)
[LOG] Registered signal for owner 165a7400: 166953a0 -> 165a74d8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "usb-camera:-usb-camera", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "USB Camera: USB Camera"
[LOG] New keyboard created, pointers Hypr: 165a7400 and WLR: 16695248
[LOG] Attached a keyboard with name Logitech Gaming Keyboard G610
[LOG] Registered signal for owner 164e8dd0: 166d0d40 -> 164e8dd8 (owner: Keyboard)
[LOG] Registered signal for owner 164e8dd0: 166d0d30 -> 164e8e40 (owner: Keyboard)
[LOG] Registered signal for owner 164e8dd0: 166d0c10 -> 164e8f10 (owner: Keyboard)
[LOG] Registered signal for owner 164e8dd0: 166d0d50 -> 164e8ea8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "logitech-gaming-keyboard-g610", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Logitech Gaming Keyboard G610"
[LOG] New keyboard created, pointers Hypr: 164e8dd0 and WLR: 166d0bf8
[LOG] Attached a keyboard with name Logitech Gaming Keyboard G610 Keyboard
[LOG] Registered signal for owner 1670a8f0: 1670a500 -> 1670a8f8 (owner: Keyboard)
[LOG] Registered signal for owner 1670a8f0: 1670a4f0 -> 1670a960 (owner: Keyboard)
[LOG] Registered signal for owner 1670a8f0: 1670a3d0 -> 1670aa30 (owner: Keyboard)
[LOG] Registered signal for owner 1670a8f0: 1670a510 -> 1670a9c8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "logitech-gaming-keyboard-g610-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Logitech Gaming Keyboard G610 Keyboard"
[LOG] New keyboard created, pointers Hypr: 1670a8f0 and WLR: 1670a3b8
[LOG] Attached a mouse with name Logitech G502 HERO Gaming Mouse
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile 2 (2)
[LOG] Applied config to mouse logitech-g502-hero-gaming-mouse, sens 0.00
[LOG] Registered signal for owner 16595260: 16743bf0 -> 16595320 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 16743bd8
[LOG] Attached a keyboard with name Logitech G502 HERO Gaming Mouse Keyboard
[LOG] Registered signal for owner 16744730: 16744340 -> 16744738 (owner: Keyboard)
[LOG] Registered signal for owner 16744730: 16744330 -> 167447a0 (owner: Keyboard)
[LOG] Registered signal for owner 16744730: 16744210 -> 16744870 (owner: Keyboard)
[LOG] Registered signal for owner 16744730: 16744350 -> 16744808 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "logitech-g502-hero-gaming-mouse-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Logitech G502 HERO Gaming Mouse Keyboard"
[LOG] New keyboard created, pointers Hypr: 16744730 and WLR: 167441f8
[LOG] Attached a mouse with name Logitech G502 HERO Gaming Mouse Keyboard
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile 0 (0)
[LOG] Applied config to mouse logitech-g502-hero-gaming-mouse, sens 0.00
[LOG] Applied config to mouse logitech-g502-hero-gaming-mouse-keyboard-1, sens 0.00
[LOG] Registered signal for owner 16598420: 16744390 -> 165984e0 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 16744378
[LOG] Adding completely new monitor.
[LOG] Registered signal for owner 1677f1f0: 1677ebc0 -> 1677f340 (owner: )
[LOG] Registered signal for owner 1677f1f0: 1677ec50 -> 1677f3a8 (owner: )
[LOG] Registered signal for owner 1677f1f0: 1677ec40 -> 1677f410 (owner: )
[LOG] Applying monitor rule for HDMI-A-1
[LOG] Setting preferred mode for HDMI-A-1
[LOG] Monitor HDMI-A-1 -> destroyed all render data
[LOG] Monitor HDMI-A-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Monitor HDMI-A-1 data dump: res 1920x1080@60.00Hz, scale 1.00, transform 0, pos 1080x770, 10b 0
[LOG] Added new monitor with name HDMI-A-1 at 1080,770 with size 1920x1080, pointer 1677ea80
[LOG] New monitor: WORKSPACEID 1, exists: 0
[LOG] Monitor HDMI-A-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Adding completely new monitor.
[LOG] Registered signal for owner 167d0540: 167cf510 -> 167d0690 (owner: )
[LOG] Registered signal for owner 167d0540: 167cf5a0 -> 167d06f8 (owner: )
[LOG] Registered signal for owner 167d0540: 167cf590 -> 167d0760 (owner: )
[LOG] Applying monitor rule for HDMI-A-3
[LOG] Setting preferred mode for HDMI-A-3
[ERR] Couldn't commit output named HDMI-A-3
[LOG] Monitor HDMI-A-3 -> destroyed all render data
[LOG] Monitor HDMI-A-3 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Monitor HDMI-A-3 data dump: res 1920x1080@60.00Hz, scale 1.00, transform 3, pos 0x0, 10b 0
[LOG] Added new monitor with name HDMI-A-3 at 0,0 with size 1920x1080, pointer 167cf3d0
[LOG] New monitor: WORKSPACEID 2, exists: 0
[LOG] Monitor HDMI-A-3 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Hyprland is ready, running the event loop!

**Comment by vaxerski** [comment]
> [ERR] Couldn't commit output named HDMI-A-3

XD

can you try setting an explicite rule for that display? otherwise, it seems like wlroots is at fault

**Comment by cswizard11** [comment]
Here are my current monitor rules:

monitor=HDMI-A-1,preferred,1080x770,1
monitor=HDMI-A-3,preferred,0x0,1
monitor=HDMI-A-3,transform,3

After further investigation, I believe it is related to the wlroots bug as described in the FAQ, which I initially dismissed since I am not using a laptop, and the bug mentions the iGPU display working, with the external displays not working, which is the opposite of my problem. However, the bug author said it worked as expected on wlroots 0.15, which is what Qtile uses, and explains why it works there and not on Hyprland.

**Comment by cswizard11** [comment]
Setting that environment variable worked for me, I now feel very silly.
