### ISSUE TITLE
waydroid issue

### ISSUE THREAD

**Issue by paorie** [hyprwm/Hyprland#1496]
OS: Arch Linux x86_64 
Kernel: 6.1.9-zen1-1-zen
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
GPU: Intel Alder Lake-P 

After update waydroid gui doesn't start.

```
❯ cat /var/lib/waydroid/waydroid.log
(246255) [18:46:53] session manager stopped, stopping container and waiting...
(246255) [18:46:53] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(246255) [18:46:55] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop vnic is waydroid0
(246255) [18:46:55] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(246255) [18:46:55] % umount /var/lib/waydroid/rootfs/vendor
(246255) [18:46:55] % umount /var/lib/waydroid/rootfs
(246255) [18:46:55] % umount /var/lib/waydroid/data
(246255) [18:46:55] % modprobe -q ashmem_linux
(246255) [18:46:55] % chmod 666 -R /dev/anbox-binder
(246255) [18:46:55] % chmod 666 -R /dev/anbox-vndbinder
(246255) [18:46:55] % chmod 666 -R /dev/anbox-hwbinder
(246255) [18:46:55] Container manager is waiting for session to load
```
It seems to start, i hear system sounds, but nothing appears on the screen.
On gnome it works.

**Comment by vaxerski** [comment]
> After update waydroid gui doesn't start.

please do a `git bisect` on hyprland to narrow down the faulty commit. If reverting to hyprland from before your update does not fix the issue, it's not my fault

**Comment by ayasa520** [comment]
Seems like multi-window mode doesn't work on Hyprland. After I run ` waydroid prop set persist.waydroid.multi_windows false` waydroid window can be displayed

**Comment by paorie** [comment]
> `Seems like multi-window mode doesn't work on Hyprland. After I run  waydroid prop set persist.waydroid.multi_windows false waydroid window can be displayed`

That was exactly the problem.
However some time ago it worked also in window. I tried different versions of hyprland and wlroots but got nothing.

Thanks ayasa.
