### ISSUE TITLE
Cursor disappears after keyboard input on alacritty

### ISSUE THREAD

**Issue by Sh4d1** [hyprwm/Hyprland#1498]
Hello ! 

Steps to reproduce (only tried on my laptop, w/ archlinux):

- install alacritty (`pacman -S alacritty`)
- launch alacritty
- start to type, the cursos disappears until I close the window or when I click on a non-alacritty windown
Expected outcome: the cursor should not disappear

Happy to give more info if needed ! Thanks !

**Comment by vaxerski** [comment]
can't repro.

**Comment by Sh4d1** [comment]
I changed to foot emulator anyway, I'll close this until someone hits the same issue, thank for checking!
