### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Alleop5** [hyprwm/Hyprland#1500]
I did this on a VM but also replicated on real hardware. Hyprland will not start up because of permission denied errors unless I run as root and run it with the I am really stupid flag. Then it would show the startup UI but freeze.

Here's a few screenshots of the log:
![image](https://user-images.githubusercontent.com/118361310/216923878-0a0f1a6c-348c-4e6d-96b8-0948fcacdf1d.png)
![image](https://user-images.githubusercontent.com/118361310/216923963-fb9bae85-44d9-426a-b391-42181665fa7a.png)
Also compiling Hyprland also fails:
![image](https://user-images.githubusercontent.com/118361310/216924437-0b6ba9a6-1b33-4bd3-8045-ab2db3943f07.png)
That's all! Also I'm pretty sure I've checked every page for a solution but couldn't find any.

**Comment by vaxerski** [comment]
How is that a hyprland issue? Just because you (or your void) have completely fucked up permissions on your system has nothing to do with hyprland.

Compiling fails because you didn't read the wiki and did not clone with `--recursive`.

**Comment by andrewathalye** [comment]
People who stumble into this in the future: Void does not use systemd so you need seatd or elogind to have adequate permissions to run Hyprland. This is probably what happened for the Reporter.

**Comment by burein-ita** [comment]
This ^^^ + Everything is explained in Void's documentation. READ.
