### ISSUE TITLE
Can't start hyprland with "th_drm_fd() failed!"

### ISSUE THREAD

**Issue by Yatogaii** [hyprwm/Hyprland#1506]
OS: EndeavourOS with no desktop
platform: VMware Workstation Pro 17

## Steps to reproduce

1. Install endeavourOS minimal (no DE)
2. execute `paru -S hyprland`
3. Set a wrapper (from official website manual, listed below)
4. start my wrapper.

## Expected outcome

Start hyprland successful.

## Noted outcome

![image](https://user-images.githubusercontent.com/38414438/217147299-76e323e4-ffc1-45b3-8dba-69887d12184e.png)

My wrapper:
```
#!/bin/sh

cd ~

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Bibata-Modern-Classic

# Set a cursor size
export XCURSOR_SIZE=24

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

exec Hyprland
```

Sorry for my bad english,  thx.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/217234807-c760e4d4-bbbd-4857-
b08b-68e5058b8c8e.png)

![image](https://user-images.githubusercontent.com/43317083/217234868-0dbb03f0-68b2-4a03-b0f9-6d9a5323c165.png)

**Comment by kernkraft235** [comment]
This still doesn't work with 3d accel enabled in VMware workstation 17. Enabling software rendering does work if you were just trying to make a VM to experiment with hyprland configuration
