### ISSUE TITLE
`movetoworkspacesilent` leaves invalid active window

### ISSUE THREAD

**Issue by Pyxels** [hyprwm/Hyprland#1507]
_This is not a fatal crashing bug._
When using `movetoworkspacesilent` on a multi monitor setup there is no active window left selected. `hyprctl activewindow` returns `invalid`.

### Relevant config
- version: v0.21.0beta
- general: layout = master
- input: follow_mouse = 3 (probably not important)
### Steps to reproduce
- Workspace 1 on Monitor 1
- Workspace 2 on Monitor 2
- Open two terminals in ws 1
- execute `hyprctl dispatch movetoworkspacesilent 2` in one of the two
### Expected outcome
- terminal moves to ws 2
- other terminal in ws 1 is active/focused
### Noted outcome
- terminal moves to ws 2
- no window is active/focused
- `hyprctl activewindow` returns `invalid`

Im loving this project so far, but I'm still having issues adapting to the different style of workspaces coming from leftwm. Sorry if I'm misunderstanding something here.

**Comment by Pyxels** [comment]
Also applies in dwindle mode

**Comment by vaxerski** [comment]
can't repro on -git

**Comment by Pyxels** [comment]
Switched to -git (`Hyprland, built from branch main at commit 48c86ad863017226503e02ceb2113415beb69c81dirty (Update CMakeLists.txt (1514)).`) and the problem persists.

I am watching `activewindow` by using `watch hyprctl activewindow`. Right after executing the silent move no workspace is focused/active and the watching command returns `INVALID`. I have to use `dispatch workspace 1` to regain focus.

**Comment by vaxerski** [comment]
multimon? single mon? Testing on dwindle.

**Comment by Pyxels** [comment]
This only happens when both workspaces are visible on two (or more) monitors. The one from which the window is moved, and the one to which the window is moved.

**Comment by vaxerski** [comment]
oh alr. That's why. I'll see when I am back on my desktop
