### ISSUE TITLE
XDG_CURRENT_DESKTOP= in wrapper script is overwritten 

### ISSUE THREAD

**Issue by stefonarch** [hyprwm/Hyprland#1509]
Not a real bug but an issue.

I use a [wrapper script](https://github.com/stefonarch/LXQt-Wayland-files/blob/main/start_scripts/startlxqthyprland) to start hyprland, which starts an lxqt-session.

Now hyrpland doesn't load it's desktop modules with `OnlyShowIn=LXQt;` as it overwrites the setting in the wrapper script with `XDG_CURRENT_DESKTOP=Hyprland`.

Can this be disabled somehow without recompiling? Is it necessary for Hyprland to work?

**Comment by vaxerski** [comment]
don't think so. I can make a patch to allow that tho.

**Comment by alba4k** [comment]
How about `env = XDG_CURRENT_DESKTOP=Whatever` in hyprland config

**Comment by stefonarch** [comment]
> How about `env = XDG_CURRENT_DESKTOP,Whatever` in hyprland config

In fact, don't know when this arrived but it solves:
`env = XDG_CURRENT_DESKTOP,LXQt:Hyprland`

**Comment by alba4k** [comment]
that arrived yesterday

dw was just checking out some old issues cause I had nothing to do

**Comment by Pjt727** [comment]
This problem came up for me as well:
```bash
#!/bin/sh
XDG_CURRENT_DESKTOP=KDE google-chrome-stable
```
I am able to successfully run the above from a shell but if I try to execute it from a hyprland bind or other similar mechanisms the variable is overwritten.

My use case is from [nnn](https://github.com/jarun/nnn/wiki/Advanced-use-cases#browser-integration) where they use this environment variable hack to write their own kdialog script to integrate a web file picker.

I would not want to set `XDG_CURRENT_DESKTOP` for everything just for this process.

If anyone has any workarounds let me know.

**Comment by stefonarch** [comment]
> if I try to execute it from a hyprland bind or other similar mechanisms the variable is overwritten.

A bind to a script with the snippet should work I think.

**Comment by fufexan** [comment]
This should work `bind = SUPER, g, exec, XDG_CURRENT_DESKTOP=KDE google-chrome-stable`.

**Comment by Pjt727** [comment]
Thanks for your responses...

I tried both of those without any luck. Even if I change the `/bin/google-chrome-stable` exec to include `XDG_CURRENT_DESKTOP=KDE` i.g.
`exec /opt/google/chrome/google-chrome $CHROME_USER_FLAGS "$@"` -> 
`XDG_CURRENT_DESKTOP=KDE exec /opt/google/chrome/google-chrome $CHROME_USER_FLAGS "$@"`
This still did not work when executing the script through a hyprland bind or through my program launcher wofi.

I also tried making making my own /bin wrapper exec that just called the /opt/google/chrome/chrome binary with `XDG_CURRENT_DESKTOP=KDE` but that still only worked when executing it from my terminal.

I also have tried executing the the scripts through zsh / kitty sub-processes i.e. `zsh -c [WRAPPER SCRIPT]` but that also does not work 

This seems a problem with chrome as the following test **worked as expected**:
1. create `test` script: `XDG_CURRENT_DESKTOP=KDE test2`
2. create `test2` script: `echo $XDG_CURRENT_DESKTOP > $HOME/current-desktop`
3. run through shell manually and examine `$HOME/current-desktop` for output
a. remove `$HOME/current-desktop` 
4. run through hyprland bind and compare `$HOME/current-desktop` for output


The most minimum way I think of to reproduce my problem is as follows:

0. prereqs 
    - have a chromium based browsers
    - ensure file picker works beforehand
1. create an empty kdialog script in your PATH
a. if you already have a kdialog script from KDE or for some other reason make sure this one is before it
b. close all existing sessions of the browser (if you have another session of the browser open, it will probably use that process)
2. open browser from shell ex: `XDG_CURRENT_DESKTOP=KDE google-chrome-stable`
    - test file picker and confirm it **does not work at all**
3. open with hyprland bind ex: `bind = $mainMod, g, exec, XDG_CURRENT_DESKTOP=KDE google-chrome-stable`
    - test file picker and confirm that it **works like before** 

Expected results of this test are that both starting chrome from the hyprland bind and from the shell won't work

I have settled the following script and manually launching the first chrome instance from my shell. If anyone has any other ideas let me know.
```bash
#!/bin/sh
XDG_CURRENT_DESKTOP=KDE google-chrome-stable "$@" > /dev/null 2>&1   &
```

**Comment by stefonarch** [comment]
Is the whole point using the KDE filedialog in chrome? 
If yes this could be achieved by using `xdg-desktop-portal-kde`, as I'm running LXQt Hyprland session with the portal-lxqt and chromium opens the native LXQt filedialog here. I don't remember if chrome* needs a setting for that or not though.
