### ISSUE TITLE
Drop-Down application built-in support

### ISSUE THREAD

**Issue by K1ngst0m** [hyprwm/Hyprland#1510]
the "drop-down" concept can make the window act like the [guake](http://guake-project.org/), and [tilda](https://github.com/lanoxx/tilda) terminal, which is the built-in support, and this is the most important part of my workflow (for frequently and simple terminal jobs).

and there's some work like [tdrop](https://github.com/noctuid/tdrop), it is independent of DE and application and can make every window act as the above drop-down terminal but now currently works only for X, and may need some workarounds for specific WM, I have encountered some issues like multi-monitor support in `bspwm` and flicking in `qtile` previously.

IMO the best practice is making the DE(WM) built-in support, letting the WM decide how the best behavior for the "drop down" application, like `qtile`,
according to the [docs](https://docs.qtile.org/en/latest/manual/config/groups.html) :
> ScratchPad is a special - by default invisible - group which acts as a container for DropDown configurations. A DropDown can be configured to spawn a defined process and bind thats process' window to it. The associated window can then be shown and hidden by the lazy command dropdown_toggle() (see [Lazy objects](https://docs.qtile.org/en/latest/manual/config/lazy.html#lazy)) from the ScratchPad group. Thus - for example - your favorite terminal emulator turns into a quake-like terminal by the control of Qtile.

> If the DropDown window turns visible it is placed as a floating window on top of the current group. If the DropDown is hidden, it is simply switched back to the ScratchPad group.

Hyprland is my most interest WM in Wayland and the smooth "drop-down" terminal experience is a key part of switching to the Wayland.

**Comment by vaxerski** [comment]
you can script that with hyprctl no?

if you mean something like yakuake on kde iirc. A terminal that you can toggle.

If you are fine with scratchpads, hyprland has those so idk what the problem is.

**Comment by tchofy** [comment]
I'm bad at scripting, but thought it'd be an interesting challenge even if it's inefficient, so I did some thinkering, and yeah, it's way simpler to just go with a scratchpad.

Here's a draft of my setup
Stuff in `hyprland.conf`
```
exec-once=kitty --class=kitty-dropdown
$dropterm=kitty-dropdown

windowrule=workspace 1,$dropterm
windowrule=float,$dropterm
windowrule=size 75% 20%,$dropterm
windowrule=move 12.5% -469,$dropterm
bind=,F12,exec,$HOME/.config/hypr/scripts/dropdown.sh
```
And then `dropdown.sh`
```
#!/usr/bin/env bash

TOGGLE=/tmp/droptoggle
DROPTERM=kitty-dropdown

if [ -f "$TOGGLE" ]; then
    #Hide terminal and unpin
	hyprctl --batch "dispatch movewindowpixel 0 -500,$DROPTERM; dispatch pin $DROPTERM; dispatch cyclenext"
	rm $TOGGLE
else
    #Show terminal and pin
    hyprctl --batch "dispatch movewindowpixel 0 500,$DROPTERM; dispatch pin $DROPTERM; dispatch focuswindow $DROPTERM"
    touch $TOGGLE
fi
```

For the scratchpad method it's as simple as:
```
exec-once=[workspace special; size 75% 20%;move 12.5% 40] kitty
bind=,F12,togglespecialworkspace
```

**Comment by K1ngst0m** [comment]
forgive me for the careless document searching, it works for me. thanks the help

**Comment by gfhdhytghd** [comment]
> bind=,F12,exec,$HOME/.config/hypr/scripts/dropdown.sh

I think maybe 
bind=,F12,exec, bash $HOME/.config/hypr/scripts/dropdown.sh 
will be better

**Comment by Schweber** [comment]
Do you have an idea how to improve the capabilities of such a script to emulate the behaviour of [tdrop](https://github.com/noctuid/tdrop)?

I tried to write a bash script using the capabilities of `hyprland` but i'm having trouble and was wondering if you had a solution already.

**Comment by Schweber** [comment]
I forgot about this tread. I fleshed it out in the meantime and it"s now in hyprwm/contrib and [in its own repo](https://github.com/Schweber/hdrop).
