### ISSUE TITLE
Create an official list of dependencies

### ISSUE THREAD

**Issue by bloodandcoffee** [hyprwm/Hyprland#1512]
Currently there does not seem to be a clear list of dependencies, making it rather difficult to package for distros that are currently not officially supported.

Would it be possible for a list of dependencies (w/ version requirements) to be created to facilitate the usage of Hyprland on repos such as Debian and others not currently supported?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Getting-Started/Installation/#manual-manual-build

Hyprland shouldn't require anything additional over the deps of wlroots-git (with xcb) IIRC.

**Comment by bloodandcoffee** [comment]
Hello.

Those are instructions for building on Arch (and the repos of whatever other distros Hyprland officially supports.) However, this quickly becomes untrue for different linux distros.

Providing a list of the library dependencies with their respective different versions (not package dependencies, as those vary from distro to distro) makes it such that Hyprland would be "supported" on all Linux distros, provided that the user can compile or otherwise source the dependencies themselves.

As the developers of this project, it shouldn't be too much work to provide a list of libraries/versions and would effectively make Hyprland distro-independent as well as save any potential users of this software a lot of time.

Regards,

Frank.

**Comment by vaxerski** [comment]
> As the developers of this project, it shouldn't be too much work to provide a list of libraries/versions and would effectively make Hyprland distro-independent as well as save any potential users of this software a lot of time.

_developer_. There is only me. And I to be honest have no clue.

You had to manually compile all those stuff because wlroots-git depends on them. See wlroots' deps [here](https://gitlab.freedesktop.org/wlroots/wlroots#building)

Hyprland adds no additional dependencies afaik.

**Comment by bloodandcoffee** [comment]
Upon reviewing the list of packages I had trouble with, it would seem that you are correct (aside from the CMake version being wrong, which I have created a PR for). I guess this means that I will be making some PR's for the documentation when I have more time.

https://github.com/hyprwm/Hyprland/pull/1514
