### ISSUE TITLE
Window rule bordercolor support for gradients

### ISSUE THREAD

**Issue by Fabillotic** [hyprwm/Hyprland#1515]
Currently the window rule for `bordercolor` is of type `color`.
It would be nice to use `gradient`s for dynamically setting the color when a window is in fullscreen for example.

**Comment by mutexdeveloper** [comment]
Agreed. 
Would love to see this.

**Comment by TheOnlyMrCat** [comment]
Is this fixed by #4335?

**Comment by Fabillotic** [comment]
> Is this fixed by #4335?

Yup, seems like it
