### ISSUE TITLE
Mouse cursor disappear 

### ISSUE THREAD

**Issue by mamaraddio** [hyprwm/Hyprland#1520]
I installed Hyprland on top of a fresh ArchLinux with NVIDIA GPU following the Hyprland wiki.

After pure Arch install I installed SDDM and Hyprland-bin from the AUR and followed the NVIDIA specific instructions.

Hyprland starts correctly both from SDDM and with the wrapper script with appropriate NVIDIA exports.

When Hyprland session spawns the mouse cursor is visible but as soon as I launch any application (kitty, a browser or any other app) it disappears until I exit the Hyprland session and spawn a new one, and this cycle is repeated over and over. 

Mouse is working (I can click and move it around) but I can't see where it is because the cursor disappears. Setting `WLR_NO_HARDWARE_CURSORS=1` as reported in the `HyprlandWiki#FAQ`doesn't solve the problem

**Comment by NotAShelf** [comment]
what does `echo $WLR_NO_HARDWARE_CURSORS` return?

**Comment by mamaraddio** [comment]
Thanks @NotAShelf for pointing it as an hint.

I'm just stupid because I noticed I wrote wrong the name of the variable in the wrapper script, and for the `SDDM` managed version I haven't put the `env` word in front of the `Exec` argument of the desktop file.

If this could help someone, unexperienced with WMs like me, in future I just mention that for the SDDM managed version the path for the desktop file (according to the [Hyprland Wiki](https://wiki.hyprland.org/Getting-Started/Quick-start/#wrapping-the-launcher-recommended)) is `/usr/share/wayland-sessions/hyprland.desktop`. To set the variable in the desktop file you have to change the Exec line like so:
```sh
Exec=env WLR_NO_HARDWARE_CURSORS=1 Hyprland
```
or just set as Exec value the [wrapper script]( http://wiki.hyprland.org/Getting-Started/Quick-start/#wrapping-the-launcher-recommended) with the [additional NVIDIA specific exports](https://wiki.hyprland.org/Nvidia/#how-to-get-hyprland-to-possibly-work-on-nvidia), like this:
```sh
Exec=wrappedhl # remember to add the script directory to your PATH variable 
```

**Comment by lizardonsprings** [comment]
mate you're an absolute beast, thank you for saving me hours

**Comment by vaxerski** [comment]
nowadays you can use the env hl config keyword

**Comment by yukinoli** [comment]
Holy crap dude! Thanks a lot!

**Comment by bannert1337** [comment]
https://wiki.hyprland.org/Nvidia/#how-to-get-hyprland-to-possibly-work-on-nvidia

**Comment by innocentDE** [comment]
Helped me a lot, thanks!

**Comment by Scion0Roses** [comment]
---
###### Fix: Enable Software Cursor in Hyprland
1. **Edit the Hyprland desktop file**
   ```
   /usr/share/wayland-sessions/hyprland.desktop
   ```
   Change the `Exec=` line:
   ```
   Exec=env WLR_NO_HARDWARE_CURSORS=1 Hyprland
   ```
3. **Edit Hyprland config file**
   ```
   ~/.local/share/hyprland.conf
   ```
   Scroll down to find the "Cursor" section and add:
   ```
   cursor {
       no_hardware_cursors = true
       use_cpu_buffer = true
   ```
4. **Reinitialize input devices**
   Run:
   ```
   rfkill
   ```
---
