### ISSUE TITLE
Regression with closing overlay layers

### ISSUE THREAD

**Issue by maximbaz** [hyprwm/Hyprland#1521]
Open [wldash](https://git.sr.ht/~kennylevinsen/wldash) and press Esc to close it.

Expected: window disappears.
Actual: window becomes semi-transparent, blinking, and moving cursor over it clears it like in paint :grin: 

I bisected it to:

```
a431c1b01c08cdc1c2f030bebf052aa4f534d12a is the first bad commit
commit a431c1b01c08cdc1c2f030bebf052aa4f534d12a
Author: vaxerski <vaxry@vaxry.net>
Date:   Sat Feb 4 13:12:50 2023 +0000

    bring back dynamic ls geom updates
```

https://user-images.githubusercontent.com/1177900/218045160-78d624ae-4ec0-4ec6-b059-8c701a51a910.mp4

**Comment by vaxerski** [comment]
fixed with d1a7f1dd368517854fdcc12a9bdd189578eef435
