### ISSUE TITLE
lockscreen showed behind full screen

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1523]
- open an app in full screen
-  lock the screen
- the screen is actually locked, but the lockscreen is placed behind,

**Comment by vaxerski** [comment]
still interaction with lockscreen tho right?

**Comment by primalmotion** [comment]
yeah. I can blind type my password and I get control back

**Comment by vaxerski** [comment]
fixed in bda8208aaa3d7eb9f14d49691b919f8f2e9f5594

**Comment by primalmotion** [comment]
thx!
