### ISSUE TITLE
`hyprctl animations -j` missing a terminating square bracket

### ISSUE THREAD

**Issue by neonfuzz** [hyprwm/Hyprland#1529]
Steps to reproduce:

`hyprland animations -j | jq`

Expected outcome: valid json

Noted outcome:
`parse error: Unfinished JSON term at EOF at line 129, column 0`

This appears to come from a missing square bracket ending the json output.

**Comment by vaxerski** [comment]
thanks! fixed in 287f31329e7a16b42c3f20b9b7ecf3ec6adbc51d
