### ISSUE TITLE
Creating virtual monitors/displays 

### ISSUE THREAD

**Issue by Elkellympia** [hyprwm/Hyprland#1530]
Hey, i'm a linux user who travels a lot and works remotely, and what i carry on my travel is my laptop and a pair of vr googles,
What i do in in x11 right now is making the system believe there are occupied existing inputs when they are not occupied but the inputs do exist, is very clunky and messy because the method changes whether you use nvidia, intel or radeon and is really inconsistent.
with those existing inputs i can see them through the vr googles with something like [immersed](https://immersed.com/) and then work with 3 or 4 giant displays easily instead of the 1 small display that my laptop has, i would really like if in hyprland you could create virtual displays.

i have read the [wiki](https://wiki.hyprland.org/Configuring/Monitors/) and did not found something useful in order to do so, if i'm wrong, and there is a way to do this, please, tell me.

**Comment by vaxerski** [comment]
no clue about your usecase but `hyprctl output`: https://wiki.hyprland.org/Configuring/Using-hyprctl/#output

**Comment by vaxerski** [comment]
all config
