### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by ErrorNoInternet** [hyprwm/Hyprland#1533]
## Steps to reproduce:
1. Install Hyprland
2. Start Hyprland

## Expected outcome:
1. Running perfectly with no lag

## Actual outcome:
Laggy desktop
 - Moving the cursor around causes dropped frames
 - glxgears doesn't reach 60 fps when moving cursor around
 - Scrolling in webpages isn't smooth
 - Minecraft (prime-run) has lots of small stutters (most frames will take 17-25 ms to render instead of 16 ms)
 
 The only thing I have open is Konsole

**iGPU:** Intel HD 4600 (i7-4710HQ)
**dGPU:** NVIDIA GTX 860M (525 dkms driver)
**Kernel:** 6.1.11-arch1-1
**Hyprland Version:** 0.21.0beta-2 compiled from the AUR

### Other things I've tried
 - Using the zen kernel
 - hyprland, hyprland-bin, and hyprland-nvidia packages
 - Using the NVIDIA card to render Hyprland (optimus-manager --switch nvidia)
 - Having the Kitty terminal open instead of Konsole (to run glxgears)

It seems to be better when there are no other applications open, but there is still stuttering

This problem also occurs on KDE Plasma Wayland, but I can choose "Prefer smoothest animations" in the compositor settings to fix this

**Comment by vaxerski** [comment]
nvidia is not supported in general.

if it occurs in plasma, it's safe to say your igpu just can't keep up. See your igpu's usage graph.

**Comment by ErrorNoInternet** [comment]
iGPU usage is at 5% on idle, ~50% when being used, and rarely hits 70% when I trigger lots of animations and effects

on Plasma, I can fix the issue by choosing "Prefer smoothest animations" though, and the only thing that it appears to do is fix the lag (no visible sacrifices)

weird thing is, I expected some sort of other issue when using the nvidia card (e.g. flickering), but instead I got the exact same issue

ill play around a bit more and try to fix it, thanks for the info
