### ISSUE TITLE
Core Dumped on launch

### ISSUE THREAD

**Issue by rxguy** [hyprwm/Hyprland#1534]
Launching on Fedora Linux Rawhide I get:

/usr/include/c++/13/bits/basic_string.h:1221: constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)

Expected behaviour: Hyprland to start
Observed behaviour: Core dumped

hyprland.log:
[LOG] Instance Signature: 287f31329e7a16b42c3f20b9b7ecf3ec6adbc51d_1676206370
[LOG] Hyprland PID: 1216784
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: kirk.turbolivido.ca
[LOG] Release: 6.2.0-0.rc7.20230208git0983f6bf2bfc.52.fc38.x86_64
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed Feb  8 17:47:45 UTC 2023

[LOG] GPU information:
	Flags: bus master, VGA palette snoop, 66MHz, medium devsel, latency 64
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 550 640SP / RX 560/560X] [1002:67ff] (rev cf) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Fedora Linux"
VERSION="38 (Rawhide Prerelease)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Rawhide Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
SUPPORT_END=2024-05-14

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG]
Current splash: "Hyper".replace("e", "")

[LOG] Hyprland init finished.
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 200 points, mem usage: 3.20kB, time to bake: 35.79µs. Estimated average calc time: 0.16µs.
[LOG] Creating the LayoutManager!
[LOG] Creating the ConfigManager!
[LOG] Creating the CHyprError!
[LOG] Creating the ThreadManager!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 200 points, mem usage: 3.20kB, time to bake: 23.39µs. Estimated average calc time: 0.11µs.

coredump:
           PID: 1216784 (Hyprland)
           UID: 1000 (dturner)
           GID: 1000 (dturner)
        Signal: 6 (ABRT)
     Timestamp: Sun 2023-02-12 08:52:51 AST (11min ago)
  Command Line: Hyprland
    Executable: /usr/bin/Hyprland
 Control Group: /user.slice/user-1000.slice/session-4.scope
          Unit: session-4.scope
         Slice: user-1000.slice
       Session: 4
     Owner UID: 1000 (dturner)
       Boot ID: e4d98338c0c04891bc305a7380550971
    Machine ID: ad67d57dc95b4ca19e25d7898d94a332
      Hostname: kirk.turbolivido.ca
       Storage: /var/lib/systemd/coredump/core.Hyprland.1000.e4d98338c0c04891bc305a7380550971.1216784.1676206371000000.zst (present)
  Size on Disk: 2.4M
       Package: Hyprland/0.21.0beta.20230211-1.287f313.fc39
      build-id: 569f4bf7be05f0e20c95eda8ddc8603aa83948e6
       Message: Process 1216784 (Hyprland) of user 1000 dumped core.

                Module libpciaccess.so.0 from rpm libpciaccess-0.16-8.fc38.x86_64
                Module libtinfo.so.6 from rpm ncurses-6.4-3.20230114.fc38.x86_64
                Module libedit.so.0 from rpm libedit-3.1-45.20221030cvs.fc38.x86_64
                Module libdrm_intel.so.1 from rpm libdrm-2.4.114.20230103-1.0e2c7d05.fc38.x86_64
                Module libdrm_nouveau.so.2 from rpm libdrm-2.4.114.20230103-1.0e2c7d05.fc38.x86_64
                Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.114.20230103-1.0e2c7d05.fc38.x86_64
                Module libelf.so.1 from rpm elfutils-0.188-5.fc38.x86_64
                Module libdrm_radeon.so.1 from rpm libdrm-2.4.114.20230103-1.0e2c7d05.fc38.x86_64
                Module radeonsi_dri.so from rpm mesa-23.1.0.20230204-1.221311e1e96.fc38.x86_64
                Module libselinux.so.1 from rpm libselinux-3.5-0.rc2.1.fc38.1.x86_64
                Module libxshmfence.so.1 from rpm libxshmfence-1.3-12.fc38.x86_64
                Module libxcb-sync.so.1 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-randr.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-dri2.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libX11-xcb.so.1 from rpm libX11-1.8.4-1.fc38.x86_64
                Module libglapi.so.0 from rpm mesa-23.1.0.20230204-1.221311e1e96.fc38.x86_64
                Module libEGL_mesa.so.0 from rpm mesa-23.1.0.20230204-1.221311e1e96.fc38.x86_64
                Module libbrotlicommon.so.1 from rpm brotli-1.0.9-11.fc38.x86_64
                Module libgraphite2.so.3 from rpm graphite2-1.3.14-11.fc38.x86_64
                Module libpcre2-8.so.0 from rpm pcre2-10.42-1.fc38.1.x86_64
                Module libbrotlidec.so.1 from rpm brotli-1.0.9-11.fc38.x86_64
                Module libharfbuzz.so.0 from rpm harfbuzz-6.0.0-3.fc38.x86_64
                Module libbz2.so.1 from rpm bzip2-1.0.8-13.fc38.x86_64
                Module libxml2.so.2 from rpm libxml2-2.10.3-3.fc38.x86_64
                Module libglib-2.0.so.0 from rpm glib2-2.74.1-3.fc38.x86_64
                Module libgobject-2.0.so.0 from rpm glib2-2.74.1-3.fc38.x86_64
                Module libgudev-1.0.so.0 from rpm libgudev-237-4.fc38.x86_64
                Module liblz4.so.1 from rpm lz4-1.9.4-2.fc38.x86_64
                Module libzstd.so.1 from rpm zstd-1.5.2-4.fc38.x86_64
                Module liblzma.so.5 from rpm xz-5.4.1-1.fc38.x86_64
                Module libXrender.so.1 from rpm libXrender-0.9.11-2.fc38.x86_64
                Module libXext.so.6 from rpm libXext-1.3.5-2.fc38.x86_64
                Module libX11.so.6 from rpm libX11-1.8.4-1.fc38.x86_64
                Module libfreetype.so.6 from rpm freetype-2.12.1-4.fc38.x86_64
                Module libfontconfig.so.1 from rpm fontconfig-2.14.2-1.fc38.x86_64
                Module libpng16.so.16 from rpm libpng-1.6.37-14.fc38.x86_64
                Module libz.so.1 from rpm zlib-1.2.13-3.fc38.x86_64
                Module libXau.so.6 from rpm libXau-1.0.11-2.fc38.x86_64
                Module libwacom.so.9 from rpm libwacom-2.6.0-1.fc38.x86_64
                Module libevdev.so.2 from rpm libevdev-1.13.0-2.fc38.x86_64
                Module libmtdev.so.1 from rpm mtdev-1.1.6-5.fc38.x86_64
                Module libcap.so.2 from rpm libcap-2.48-6.fc38.x86_64
                Module libexpat.so.1 from rpm expat-2.5.0-2.fc38.x86_64
                Module libGLdispatch.so.0 from rpm libglvnd-1.6.0-2.fc38.x86_64
                Module libffi.so.8 from rpm libffi-3.4.4-2.fc38.x86_64
                Module libsystemd.so.0 from rpm systemd-253~rc2-3.fc38.x86_64
                Module libcairo.so.2 from rpm cairo-1.17.6-3.fc38.x86_64
                Module libxcb-res.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-icccm.so.4 from rpm xcb-util-wm-0.4.2-2.fc38.x86_64
                Module libxcb-composite.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-xinput.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-xfixes.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-shm.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-render-util.so.0 from rpm xcb-util-renderutil-0.3.10-2.fc38.x86_64
                Module libxcb-render.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-present.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb-dri3.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libxcb.so.1 from rpm libxcb-1.13.1-11.fc38.x86_64
                Module libinput.so.10 from rpm libinput-1.22.1-2.fc38.x86_64
                Module libseat.so.1 from rpm seatd-0.7.0-3.fc38.x86_64
                Module libudev.so.1 from rpm systemd-253~rc2-3.fc38.x86_64
                Module libvulkan.so.1 from rpm vulkan-loader-1.3.239.20230119-1.125b4f665.fc38.x86_64
                Module libGLESv2.so.2 from rpm libglvnd-1.6.0-2.fc38.x86_64
                Module libgbm.so.1 from rpm mesa-23.1.0.20230204-1.221311e1e96.fc38.x86_64
                Module libEGL.so.1 from rpm libglvnd-1.6.0-2.fc38.x86_64
                Module libpixman-1.so.0 from rpm pixman-0.42.3.20221103-1.713077d.fc38.x86_64
                Module libxkbcommon.so.0 from rpm libxkbcommon-1.5.0-2.fc38.x86_64
                Module libdrm.so.2 from rpm libdrm-2.4.114.20230103-1.0e2c7d05.fc38.x86_64
                Module libwayland-client.so.0 from rpm wayland-1.21.90.20230125-1.83e9c9e.fc38.x86_64
                Module libwayland-server.so.0 from rpm wayland-1.21.90.20230125-1.83e9c9e.fc38.x86_64
                Module Hyprland from rpm Hyprland-0.21.0beta.20230211-1.287f313.fc39.x86_64
                Stack trace of thread 1216784:
                #0  0x00007f7b279ceb94 __pthread_kill_implementation (libc.so.6 + 0x8eb94)
                #1  0x00007f7b2797daee raise (libc.so.6 + 0x3daee)
                #2  0x00007f7b2796687f abort (libc.so.6 + 0x2687f)
                #3  0x00007f7b27cdf340 _ZSt21__glibcxx_assert_failPKciS0_S0_ (libstdc++.so.6 + 0xdf340)
                #4  0x0000562c72ff8f78 _Z24removeBeginEndSpacesTabsNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (Hyprland + 0xc0f78)
                #5  0x0000562c73037d1d _ZN14CConfigManager9parseLineERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (Hyprland + 0xffd1d)
                #6  0x0000562c7303fc52 _ZN14CConfigManager18loadConfigLoadVarsEv (Hyprland + 0x107c52)
                #7  0x0000562c72f94f82 _ZN11CCompositor15startCompositorEv (Hyprland + 0x5cf82)
                #8  0x0000562c72f79058 main (Hyprland + 0x41058)
                #9  0x00007f7b27967b4a __libc_start_call_main (libc.so.6 + 0x27b4a)
                #10 0x00007f7b27967c0b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x27c0b)
                #11 0x0000562c72f8a505 _start (Hyprland + 0x52505)

                Stack trace of thread 1216800:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216803:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216806:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216801:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216807:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216810:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216809:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216802:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216804:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)

                Stack trace of thread 1216808:
                #0  0x00007f7b279c9529 __futex_abstimed_wait_common (libc.so.6 + 0x89529)
                #1  0x00007f7b279cbec9 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8bec9)
                #2  0x00007f7b24f1431d cnd_wait (radeonsi_dri.so + 0x11431d)
                #3  0x00007f7b24ec315b util_queue_thread_func (radeonsi_dri.so + 0xc315b)
                #4  0x00007f7b24f1424c impl_thrd_routine (radeonsi_dri.so + 0x11424c)
                #5  0x00007f7b279ccc57 start_thread (libc.so.6 + 0x8cc57)
                #6  0x00007f7b27a52a70 __clone3 (libc.so.6 + 0x112a70)
                ELF object binary architecture: AMD x86-64

Thank you.
Dale

**Comment by ribenafan** [comment]
i'm facing a very similar issue on nixos

**Comment by jurienhamaker** [comment]
Same, just updated. On nixos.

**Comment by vaxerski** [comment]
long fixed I believe
