### ISSUE TITLE
double bind doesnt work properly || 

### ISSUE THREAD

**Issue by crypticC0der** [hyprwm/Hyprland#1535]
say i have:

`bindr=SUPER,mouse:275,exec, pkill firefox || firefox`
it does as expected, alternating between opening firefox and closing it

then say i do
`bindr=SUPER,mouse:275,exec, firefox || pkill firefox`
all it does is open firefox, never killing it

this is very odd behavior and i dont know why

the expected behavior here is the same as the first

**Comment by vaxerski** [comment]
this is not a bash help forum
