### ISSUE TITLE
Dimming bug while resizing a floating window with animate_manual_resizes=true

### ISSUE THREAD

**Issue by bakicelebi** [hyprwm/Hyprland#1537]
When a floating window is manually resized with animate_manual_resizes=true there are times when cursor is on top of the window behind the floating window(because of the animation). This leads to flickering effect when dim_inactive is true.

**Comment by romanstingler** [comment]
is this still present with the latest version ?

**Comment by izmyname** [comment]
> is this still present with the latest version ?

I take it as 'no', since the op is absent and nobody else reported the issue.

**Comment by bakicelebi** [comment]
I could not reproduce this issue on 0.41.2
