### ISSUE TITLE
Keyboard US International (with dead keys)

### ISSUE THREAD

**Issue by MrHappy** [hyprwm/Hyprland#1541]
I tried changing the conf file and through hyprctl, but I cannot get the keyboard to change from US to US Intl (with dead keys).
It is a fresh install on Arch. What am I missing?

**Comment by vaxerski** [comment]
what did you try?

**Comment by MrHappy** [comment]
I have the following. Which give me the dead keys and € sign with alt-gr, but I miss the key above the enter (pipe & backslash).
```
kb_layout = us
kb_variant = intl
kb_model = kb105
```

**Comment by vaxerski** [comment]
well if this does indeed change the behavior then it's you not being able to config the keyboard properly. Hyprland relies on xkb for this anyways, so it's not my code at fault.

If you can't find your desired keymap, you can always write a custom one.

**Comment by MrHappy** [comment]
That is weird, because it should match my keyboard.
Any hint you can give me, besides xkb? 😊

**Comment by vaxerski** [comment]
nope, I am a healthy human being and use a normal and reasonable layout

**Comment by vaxerski** [comment]
consider [reading the wiki](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts) instead of bothering me please :)

**Comment by KaniDev** [comment]
Really sorry if this sounds like a bother, I did read the wiki, hence my attempt at making it work.
The wiki shows how to switch between layouts, which works here, but I'm trying to switch variants here, and I'm not that familiar with xkb syntax. 
Anyways, I'll ask the reddit community, sorry for wasting your time.

**Comment by vaxerski** [comment]
`intl` is applied to a null layout. you should put `us,us`
