### ISSUE TITLE
`focuswindow` should bring grouped window to top

### ISSUE THREAD

**Issue by aksdb** [hyprwm/Hyprland#1542]
When a window is in a group and isn't on top, focusing that window using `focuswindow` is not possible.
`focuswindow` should do anything feasible to bring the desired window into focus. In case of a grouped window, this should include bringing that window to the top in the process.

> **Note**: As discussed in https://github.com/hyprwm/Hyprland/discussions/1540.

**Comment by vaxerski** [comment]
indeed. Fixed in ac251d7a66ec3cbd18c15f29c4f54d33d54f1b13
