### ISSUE TITLE
Intellij IDEA dialogs "do not show up" in a multi monitor environment

### ISSUE THREAD

**Issue by pulsar256** [hyprwm/Hyprland#1547]
When running a multi monitor setup IntelliJ/Idea dialogs such as file copy & paste, exit confirmation and other dialogs will either not show or flicker between two monitors until the popup window is focused or not "show" at all. 

The issue seems only to be triggered when IntelliJ is running on the secondary monitor. Can't be reproduced in a nested Hyprland session. Does not happen on sway 1.8 stable.

The issue can be only triggered when launching / using Intellij on `DP-1, 3840x2160, 3840x0, 1`.  When running 
on `monitor = DP-2, 3840x2160, 0x0, 1` everything works correctly. 

Multiple effects can be observed ranging from semi functional to non functional / breaking.

## Effect 1

Splashscreen flickers between DP-1 (at correct, centered-ish position) and DP-2 (@0x0 / left corner) 

https://user-images.githubusercontent.com/1245126/218584937-b926c512-839d-4baf-8a8b-fb803fec9ea6.mp4

```shell
monitor = DP-1, 3840x2160, 3840x0, 1
monitor = DP-2, 3840x2160, 0x0, 1
```

## Effect 2

Some popup dialogs (here copy & paste dialog) will open on the "correct" monitor but at the bottom right position (3840x0) sized to 1x1 ... or (1 in 10 times) flicker between both monitors as the splashscreen does.

https://user-images.githubusercontent.com/1245126/218584980-5027cc88-6e43-45a1-bc3e-f8ea9b60e49e.mp4

```shell
monitor = DP-1, 3840x2160, 3840x0, 1
monitor = DP-2, 3840x2160, 0x0, 1
```

```shell
Window 19946970 -> Copy:
        at: 3840,0
        size: 1,1
        workspace: 1 (1)
        floating: 1
        monitor: 0
        class: jetbrains-idea
        title: Copy
        pid: 39863
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        swallowing: 0
```

## Effect 3

when using `forceinput` dialogs will always flicker, never be sized to 1x1 2 in the lower right corner. Flickering stops once the window is focused.       

https://user-images.githubusercontent.com/1245126/218585017-00eef801-f5ca-4b52-9e23-8091e1b82e32.mp4

```shell
monitor = DP-1, 3840x2160, 3840x0, 1
monitor = DP-2, 3840x2160, 0x0, 1
windowrulev2 = forceinput,class:^jetbrains-
```

## Effect 4 (non-issue)

When using only one monitor everything is fine.

https://user-images.githubusercontent.com/1245126/218585081-87641e9d-2867-420e-93ab-172cbbd249da.mp4

```shell
monitor = DP-1, 3840x2160, 0x0, 1
monitor = DP-2, disable
```

**Comment by pulsar256** [comment]
Logfiles captured for each "Effect"

- [Effect 1 START.log](https://github.com/hyprwm/Hyprland/files/10726717/Effect.1.START.log)
- [Effect 2 START.log](https://github.com/hyprwm/Hyprland/files/10726716/Effect.2.START.log)
- [Effect 3 START.log](https://github.com/hyprwm/Hyprland/files/10726715/Effect.3.START.log)
- [Effect 4 START.log](https://github.com/hyprwm/Hyprland/files/10726714/Effect.4.START.log)

**Comment by vaxerski** [comment]
That's odd. Launched intellij idea and did the same and none of that occurs to me.

1. Is this a regression?
2. Is intellij in the "new design" mode? cuz mine is, and I kinda forgot how to revert to the old one by now

**Comment by pulsar256** [comment]
1. Could be, I'll try bisecting this later
2. It is in new design mode. Running EAP builds though, so this might be related to that as well. 

Did poke at the code a bit yesterday. I was looking for the window move logic which will bring floating widows closer to the cursor as the splash floating screen seems to be positioned at the cursor ... sometimes. Where would I find that?

**Comment by pulsar256** [comment]
Could track it down to specific build(s?) of the JetBrains custom JRE. Lets see if we get any more hints from that side. I wonder why Sway is not affected.

**Comment by vaxerski** [comment]
no clue, but if changing the JRE fixes the issue, then it's not really a hl issue, but an issue of x11 / xwayland being shite.

**Comment by pulsar256** [comment]
https://youtrack.jetbrains.com/issue/JBR-5417?utm_source=product&utm_medium=link&utm_campaign=TBA fixes it.
