### ISSUE TITLE
Workspace swipe numbered make workspace 1's windows disappear

### ISSUE THREAD

**Issue by zoriya** [hyprwm/Hyprland#1563]
After enabling the gesture's `workspace_swipe_numbered` option, swiping UP or DOWN on the first workspace (and only this workspace) makes all windows disappear until you reload the workspace (go to another one and go back).
Please note that I use LEFT/RIGHT to change workspaces normally.

Here is a video for demonstration:

https://user-images.githubusercontent.com/32224410/219585978-85f35c2c-6db8-4d54-aa3e-67c7f135cdaa.mp4

**Comment by vaxerski** [comment]
can be closed, the option has been removed
