### ISSUE TITLE
Waybar doesn't display workspace names 

### ISSUE THREAD

**Issue by HanoJing** [hyprwm/Hyprland#1565]
I have followed the instructions in the Waybar section at https://wiki.hyprland.org/Useful-Utilities/Status-Bars/
I built https://github.com/Alexays/waybar from source with the commands shown in the wiki. 
I have also tried https://github.com/r-clifford/Waybar-Hyprland which doesn't fix the issue.

to reproduce: start Hyprland, for this, I use the command `XDG_SESSION_TYPE=wayland dbus-run-session Hyprland`. To start waybar I use: `exec-once = waybar &` in `hyprland.conf`

Expected outcome: Waybar shows workspaces with their names

noted outcome: Waybar doesn't show workspaces with their names 

waybar log: [waybar.log](https://github.com/hyprwm/Hyprland/files/10771142/waybar.log)
waybar config file: [config.log](https://github.com/hyprwm/Hyprland/files/10771148/config.log)
waybar style.css file: [style.css.log](https://github.com/hyprwm/Hyprland/files/10771149/style.css.log)

The work on Hyprland is absolutely legendary, keep it up!
Thanks in advance!

**Comment by MahouShoujoMivutilde** [comment]
It's probably because you are building without `-Dexperimental=true`

https://github.com/Alexays/Waybar/issues/1766 (sad thing is it's a wontfix)

The fork you linked does use it, but only if you are building from nix

https://github.com/Alexays/Waybar/compare/master...r-clifford:Waybar-Hyprland:master#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R60

**Comment by HanoJing** [comment]
I build with `-Dexperimental=true` like done at https://wiki.hyprland.org/Useful-Utilities/Status-Bars/

I executed: 
```
sed -i 's/zext_workspace_handle_v1_activate(workspace_handle_);/const std::string command = "hyprctl dispatch workspace " + name_;\n\tsystem(command.c_str());/g' src/modules/wlr/workspace_manager.cpp
meson --prefix=/usr --buildtype=plain --auto-features=enabled --wrap-mode=nodownload build
meson configure -Dexperimental=true build
sudo ninja -C build install
```

**Comment by MahouShoujoMivutilde** [comment]
By your log it looks like a https://github.com/Alexays/Waybar/issues/1640, which is weird (considering the option is passed).

**Comment by HanoJing** [comment]
> By your log it looks like a [Alexays/Waybar#1640](https://github.com/Alexays/Waybar/issues/1640), which is weird (considering the option is passed).
> 
> My commands to build it are only _slightly_ different, but it works for me:
> 
> ```shell
> # ...
>     meson --prefix=/usr "build"
>     meson configure -Dexperimental=true "build"
>     ninja -C "build"
> # ...
> ```

Interesting find! I will definitely look into it.

**Comment by MahouShoujoMivutilde** [comment]
Also from waybar log:

```
[2023-02-17 20:51:04.348] [warning] module tray: Unknown module: tray
```

Which is also strange since I am pretty sure the `tray` module been around for ~half a year.

Maybe try building from original https://github.com/Alexays/Waybar?

The only meaningful difference (if you are not on nix) is this file https://github.com/Alexays/Waybar/compare/master...r-clifford:Waybar-Hyprland:master#diff-1e3fe235d8ac230e16d6bda17e39bf3fb4bc1d38a193ed6e42d2ad2589070513R470-R471

which you already edit with `sed` (which does nothing, since there is no 

```cpp
zext_workspace_handle_v1_activate(workspace_handle_);
```

line already.

**Comment by HanoJing** [comment]
> Maybe try building from original https://github.com/Alexays/Waybar?
I do that already.

Hmm. Still the same issue: `[warning] module wlr/workspaces: Unknown module: wlr/workspaces`

Even with the fix from https://github.com/Alexays/Waybar/issues/1640
and your build commands. 
I think --buildtype=plain makes some kind of difference when it comes to building the workspace_manager, I get warnings about it atleast.

**Comment by MahouShoujoMivutilde** [comment]
Oh, another important thing! 

I actually build it via PKGBUILD via aurutils in clean chroot, so my repo is, well, always clean.

Maybe since you are already had setup build in certain way before with `plain` you can't just easily re-setup it.

Try deleting `build` directory and running meson / ninja commands again after.

**Comment by HanoJing** [comment]
> Oh, another important thing!
> 
> I actually build it via PKGBUILD via aurutils in clean chroot, so my repo is, well, always clean.
> 
> Maybe since you are already had setup build in certain way before with `plain` you can't just easily re-setup it.
> 
> Try deleting `build` directory and running meson / ninja commands again after.

When I build waybar, I always re-clone before building and re-build it this way.

**Comment by MahouShoujoMivutilde** [comment]
Damn, IDK then...

**Comment by HanoJing** [comment]
Anyways, I'm thankful that you took time for me and tried to help, also how fast you replied!

**Comment by vaxerski** [comment]
not a hyprland issue. You're building waybar wrong, somehow. Consider using the aur pkg waybar-hyprland-git or mimicking what it does in your distro of choice.

**Comment by HanoJing** [comment]
Thanks! I built `waybar-hyprland-git` and it works now!

**Comment by MaKaNu** [comment]
I have a similar issue and wonder if this still necessary? I used waybar-hyprland and tried as well waybar (I red it is possible to use `hyprland/workspaces`). My Config also worked in the past and stopped working at a time in past I sadly don't remember. I Also launched waybar in debug, but couldn't spot anything which might guide me. 

I only see a small box at the position, where usually my workspaces are located.

I've only spotted the following:

```
Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Schnittstelle »org.freedesktop.portal.Settings« des Objekts im Pfad /org/freedesktop/portal/desktop
```

**Comment by HanoJing** [comment]
> I have a similar issue and wonder if this still necessary? I used waybar-hyprland and tried as well waybar (I red it is possible to use `hyprland/workspaces`). My Config also worked in the past and stopped working at a time in past I sadly don't remember. I Also launched waybar in debug, but couldn't spot anything which might guide me.
> 
> I only see a small box at the position, where usually my workspaces are located.
> 
> I've only spotted the following:
> 
> ```
> Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Schnittstelle »org.freedesktop.portal.Settings« des Objekts im Pfad /org/freedesktop/portal/desktop
> ```

Okay, looks interesting, have you got `xdg-desktop-portal` `xdg-desktop-portal-gtk` and `xdg-desktop-portal-hyprland` installed by any chance?

Install at least the `xdg-desktop-portal` and `-gtk` versions. 
They should start automatically.

Secondly, I use hyprland/workspaces which provides an implementation to have working workspace numbers shown in the top, take my config as a reference if you wish:
[
[config.txt](https://github.com/hyprwm/Hyprland/files/13496176/config.txt)
](url)

Important part is this, really:

```
{

    "modules-left": ["cpu", "temperature", "memory", "pulseaudio", "tray"],
    "modules-center": ["hyprland/workspaces"],
    "modules-right": ["hyprland/window", "clock"],
    "margin": 10,
    "height": 34,
    "layer": "top",

    // Modules configuration
    "hyprland/workspaces": {
         "sort-by-number": true,
         "on-click": "activate",
         "on-scroll-up": "hyprctl dispatch workspace e+1",
         "on-scroll-down": "hyprctl dispatch workspace e-1",
         "format": "{name}",
         "persistent_workspaces": {
            "1": ["DP-2"],
            "2": ["DP-2"],
            "3": ["DP-2"],
            "4": ["DP-2"],
            "5": ["DP-2"],
            "6": ["DP-2"],
            "7": ["DP-2"],
            "8": ["DP-2"],
            "9": ["DP-2"],
            "10": ["DP-2"],
            "11": ["DP-3"]
         }
    },
    "hyprland/window": {
          "format": "<span rise='1000'></span> {} <span rise='1000'></span>"
    },
```

Regarding xdg-desktop-portal-hyprland: https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

For more information regarding the integration of hyprland and waybar: https://github.com/Alexays/Waybar/wiki/Module:-Hyprland

Let me know if you need something.
