### ISSUE TITLE
QA: Random stutters

### ISSUE THREAD

**Issue by hikkidev** [hyprwm/Hyprland#1567]
Random interruptions have been spotted. In idle mode or surfing, this drops can be noticed by a lagging sound and mouse cursor interruptions as in https://github.com/hyprwm/Hyprland/issues/290. In [video](https://mega.nz/file/QJsXEDzb#QeGUzBdlSSsqqhtRJYs6bW3n0xQdqDyrp4ponDnsAjw) you can clearly see the performance drop down.

I am not sure if the problem is with Hyprland. However, the system resources (RAM, CPU and IO) is not loaded. I checked with different logging utilities. Also, I haven't noticed this problem on sway.

Could you give a couple of guesses as to what it could be other than WM? If not, I'll try to put together an extended log.

**Comment by hikkidev** [comment]
I've notice that the stuttering happens when the size of [hyprland.log](https://mega.nz/file/oUN23AJQ#rAq14gEYi7lmAhBlm-y-P3o-9ztDm1hZa0dA1j0KrxE) is a multiple of ~180Mb

**Comment by vaxerski** [comment]
to be frank I don't wanna download a 180MB log, can you tell me what spams?

**Comment by hikkidev** [comment]
@vaxerski `Constraint rechecked: 0, 0 to 3440, 1440 for 3bd63b80 (window name: Overwatch)`

**Comment by vaxerski** [comment]
should be fixed then with 6548439f6ce205795bfe55fc22d30830c725e0d2

the stutters are probably just the kernel struggling with appending to a 180MB file.

**Comment by hikkidev** [comment]
https://www.phoronix.com/news/AMD-Linux-Stuttering-Fix-fTPM

**Comment by vaxerski** [comment]
kek
