### ISSUE TITLE
`dimaround` window rule for window with blurred bg reduces blur.

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [hyprwm/Hyprland#1569]
How to reproduce:

1. Add this to your config

```
windowrulev2 = float,class:floating
windowrulev2 = dimaround,class:floating

bind = SUPER ALT, RETURN, exec, foot -a floating

```
2. Open the terminal with this binding

Result:

<details>
  <summary>Dimaround + floating terminal with transparent bg</summary>

![18-02-2023-22_18_55](https://user-images.githubusercontent.com/14999778/219884291-314ceafa-658b-4687-955a-1a97bd9617fa.jpg)

</details>

3. Now comment out the `dimaround` rule

<details>
  <summary>No dimaround</summary>

![18-02-2023-22_19_14](https://user-images.githubusercontent.com/14999778/219884300-03f3dceb-a581-44d0-83dd-97eb28ab25fd.jpg)

</details>

As you can see, blur is vastly different between the two screenshots.

Expected: same level of blur, different brightness of background. 

This is on https://github.com/hyprwm/Hyprland/commit/dbfa6eea7bf7a6f153cadf970719081e4ef729ee

**Comment by vaxerski** [comment]
Apparently this call to renderRect:
https://github.com/hyprwm/Hyprland/blob/b944386ca54cf650d660caac31f065c0211168b1/src/render/Renderer.cpp#L278

fucks up the blend func (removing the blend func setting from renderRect or that call fixes the issue but introduces other)

No clue why.

**Comment by MahouShoujoMivutilde** [comment]
Hyprland, built from branch main at commit a0b675ec9e57af8bc631fc8cc54d062b58669a9f dirty (binds: add ignoreMods flag).
Tag: v0.31.0-7-ga0b675ec

Can confirm that this no longer happens.

I've only just decided to check on it, so I didn't pay attention when/what exactly fixed it, but it now works as expected:

<details>
  <summary>Spoiler</summary>

![21-10-2023-02_22_33](https://github.com/hyprwm/Hyprland/assets/14999778/5efc7caf-56c8-464a-a77a-0e36b9a7f2a0)
![21-10-2023-02_22_19](https://github.com/hyprwm/Hyprland/assets/14999778/81e7d3a5-f2a1-4b87-ad87-1da623755da2)


</details>

**Comment by vaxerski** [comment]
yeah the switch to premult alpha did it but I forgot which commit it was. It was a while back.
