### ISSUE TITLE
Valid shell command fails silenty when using the exec dispatch

### ISSUE THREAD

**Issue by keogami** [hyprwm/Hyprland#1573]
# The bug

The following shell command would succeed in `sh`
```bash
(command; (test $? == 0) && doSomethingOnError)) | doSomethingWithTheOuput
```
But when set as a dispatch through a keybind, it wont run at all. Which is confusing.
```
bind = , key, exec, (command; (test $? == 0) && doSomethingOnError)) | doSomethingWithTheOuput
```

## Cause
After a little bit of digging, I found that it fails because hyprland is injecting some variables before the command by modifying the command itself, which is leading to a syntax error.
```
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 (true; (test $? == 0) && notify-send -a title "text")
```

## Workaround
Putting a `;` before the command removes the syntax error, but that's not the best solution and just a frustrating experience overall.
```
bind = , key, exec, ;(command; (test $? == 0) && doSomethingOnError)) | doSomethingWithTheOuput
```

## Fix
If possible, inject the variables without modifying the command itself. Basically, make no assumption about the command.

**Comment by vaxerski** [comment]
you can now use `execr` for no parsing 6e16627cbcb5d4712195c97e106f2198076c8aff
