### ISSUE TITLE
Tabbed windows disappears if layout is changed from dwindle to master

### ISSUE THREAD

**Issue by Kvn0l** [hyprwm/Hyprland#1576]
Steps to reproduce:

1. Use dwindle layout
2. Group some windows
3. Change from dwindle to master while having tabbed/grouped windows
4. Only the one on top will be visible and accessible afterwards.
5. Does not become accessible if change back to dwindle layout

Expected outcome:
Grouped windows being dispersed when layout is changed to prevent this behavior.

Noted outcome:
Windows not on top of the group goes to aether but can still be seen in `hyprctl client` list, seems not to be possible to focus or bring to top with hyprctl

Noticed this when I made a simple bash script to change the layout with hyprctl

LAYOUT=$(hyprctl getoption general:layout dwindle | grep -o dwindle)
if [[ $LAYOUT == "dwindle" ]]; then
    	hyprctl keyword general:layout master
    else
    	hyprctl keyword general:layout dwindle
fi

Then tested changing the configuration in the file, same outcome.
As with the other bug, I can provide recording and screenshots if needed

**Comment by Aqa-Ib** [comment]
Maybe related to #1571 ?

**Comment by Kvn0l** [comment]
> Maybe related to #1571 ?

I've reproduced here, it's quite similar, heh. At least over the hood.
