### ISSUE TITLE
Cursor changes size when moving

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#1577]
# Setup
- I've configured GTK to use Bibata cursors theme.
- No XWayland.
- NVIDIA GPU.

# Issue

When you move the cursor on the desktop or just inside of a application like Brave or VSCodium it shrinks and expands by about 2px. To clarify, you don't have to move it between applications to notice this as it's happening continuously.

I'm having a hard time finding the culprit of this issue but some users suggests it's due to fractional scaling of bitmap icons?

# Config
I'm using NixOS and just using this option sets the cursor options globally without having to use `exec-once=hyprctl setcursor Bibata-Modern-Ice 22` or any other configuration:
```
home.pointerCursor = {
  gtk.enable = true;
  package = pkgs.bibata-cursors;
  name = "Bibata-Modern-Ice";
  size = 22;
};
```
For reference, if you configure the cursor with a alternative approach you get the same result:
<details>
  <summary>Example</summary>
  
  ```
  # hyprland.conf
  exec-once=hyprctl setcursor Bibata-Modern-Ice 22
  ```
  With:
  ```
  # .nix
  gtk = {
    enable = true;
    cursorTheme = {
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Ice";
      size = 22;
    };
  };
  ```
</details>

**Comment by xRiot** [comment]
I've confirmed that this issue doesn't happen unless you use a cursor theme

**Comment by vaxerski** [comment]
unless the cursor is above nothing (the Hyprland logo background) the image is set by the application. This would suggest it's the app misbehaving.

**Comment by xRiot** [comment]
@vaxerski I made a video demonstration with wf-recorder of the desktop. I'm not sure if the cursor is technically above my foot terminal since I toggled float, it behaves the same way if I move to another workspace. The resizing of the cursor happens even if no applications are running:

https://user-images.githubusercontent.com/45666572/219949610-0a240559-96a6-4cbf-9257-dd70cefa7104.mp4

**Comment by xRiot** [comment]
I've noticed the resizing doesn't happen if I move the mouse perfectly horizontally (by sliding it left/right on top of the screen) or perfectly vertically (by sliding it up and down at the edge of the screen). It's easiest to spot if the curse moves diagonally or in circles. This is extremely noticeable when moving the mouse between multiple applications like Brave browser and VSCodium

**Comment by vaxerski** [comment]
I may be blind, but can't see your cursor changing size in the video.

**Comment by xRiot** [comment]
@vaxerski I believe I found the culprit of this issue!

There is a shadow underneath the cursor. If I move it in circles on the desktop the shadow changes position which makes it look like the cursor is shrinking (`Bibata-Modern-Ice`):
![28px](https://user-images.githubusercontent.com/45666572/219956269-d3abf764-47ce-4928-9f48-f9014464dd54.png)
vs
![27px](https://user-images.githubusercontent.com/45666572/219956274-9cdb92a7-e4f0-441f-af59-c7334534b7b1.png)

If we compare this against `Bibata-Original-Ice`, cursor's borders becomes thicker depending on how dark the background is:
![classic1](https://user-images.githubusercontent.com/45666572/219960953-18d697e4-cc73-4038-a3e7-55eb7bb908bb.png)
vs
![classic2](https://user-images.githubusercontent.com/45666572/219960954-5307dc68-317b-43e8-b466-22c60f030fac.png)

I'm on a 10 bit display and this subtle difference makes the cursor look like it's shrinking and expanding.

I'm not sure if we can do anything about this other than using a cursor without borders/shadow?

**Comment by vaxerski** [comment]
don't think we can.

**Comment by izmyname** [comment]
> don't think we can.

prolly close, then?
