### ISSUE TITLE
crash on opening first app with scale `auto`

### ISSUE THREAD

**Issue by sleeplessKomodo** [hyprwm/Hyprland#1579]
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10777120/hyprland.log)

I mistakenly uninstalled lxappearance to install lxappearance-gtk3 (I was attempting to match themes across different apps), and then decided to reboot my system, and then I was greeted with

`[glfw error 65544]: Wayland: fatal display error`

Upon checking the FAQ and Crashes and Bugs page, I got the log of the crash, which should be attached above. The end reads:

```
ASSERTION FAILED! 

Tried to render rect with width/height < 0!

at: line 933 in OpenGL.cpp.
```

Is there any way to reverse this damage, without reinstalling the entire OS? Re-installing lxappearance and removing lxappearance-gtk3 didn't seem to make any difference, to my surprise. 

system details:

Arch Linux, Kernel 6.1.12-zen
AMD Ryzen 7 3700X
NVIDIA 2080 Super

**Comment by sleeplessKomodo** [comment]
On second thought, this is still an issue, but I'd rather have my pc operational ASAP than in this useless state. Hoping any possible solution found can help someone else in the future.

**Comment by vaxerski** [comment]
failed asserts generate a coredump. Attach it, just like instructed in the issue guidelines you were requested to read.

**Comment by sleeplessKomodo** [comment]
sorry, this is my first time with a tiling window manager, and I have since wiped my drive. I'm very sorry, I didn't read the guidelines, but I know better for the future.

**Comment by vaxerski** [comment]
if this is not happening anymore then I will close it. Feel free to reopen if you encounter it again

**Comment by debordle** [comment]
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10782735/hyprland.log)


I am now getting this exact same issue on an effectively brand new Arch install. I was simply using my computer normally, without installing or changing anything immediately at the moment of the crash, until suddenly my desktop completely froze up unresponsive, apart from changing workspaces. I restarted my computer and now Hyprland crashes upon trying to open a window (apart from trying to open Rofi or discord-screenaudio, which don't do anything). Things I have tried:

1. Removing the last program I installed (discord-screenaudio).
2. Having the script given at https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/ launch at start with exec-once.
3. Installing sddm and launching through that.
4. Having other programs open via exec-once: firefox causes the same crash, kitty crashes, discord-screenaudio does nothing.
5. Making *extra* sure xdg-desktop-portal-kde is not installed. 

My config is identical to the stock autogenerated one apart from adding in the catppuccin colors, configuring my monitor as `monitor=DP-1,1920x1080@300,auto,auto` and now having `exec-once = bash  ~/Downloads/xdg`, which is exactly the same as that script mentioned earlier.

**Comment by vaxerski** [comment]
> EDIT: I will get the coredump, give me a moment.

Please get on -git if you aren't already and get the crash report, not coredump. See https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md#obtaining-the-hyprland-crash-report-v0220beta-and-up

**Comment by debordle** [comment]
[hyprlandCrashReport1219.txt](https://github.com/hyprwm/Hyprland/files/10783061/hyprlandCrashReport1219.txt)


It wouldn't let me upload it so I changed it to a txt so I could

**Comment by vaxerski** [comment]
oopsie, I made a wittwe fucky wucky in the crash wepowtew >///<

fixed in 0eee57aab9df98e6fe16df94da0fdfaf4f350504 OwO

couwd you redo the cwash and attach the new wepowwt pwease onii-chan? UwU

**Comment by debordle** [comment]
[hyprlandCrashReport1073.txt](https://github.com/hyprwm/Hyprland/files/10783477/hyprlandCrashReport1073.txt)

Updated the -git package and redid the crash. It produces quite a lot of crash reports, do you just want the one with the highest PID number?

**Comment by vaxerski** [comment]
that's the wrong one it seems. It should produce only one per session, sort them by date modified

**Comment by debordle** [comment]
[hyprlandCrashReport603.txt](https://github.com/hyprwm/Hyprland/files/10783534/hyprlandCrashReport603.txt)

My bad. Deleted all the files in .hyprland and did the crash once again

**Comment by vaxerski** [comment]
huh, odd. All symbols are gone. Can you give the coredump then as well?

**Comment by debordle** [comment]
[coredump.txt](https://github.com/hyprwm/Hyprland/files/10783570/coredump.txt)
[hyprlandCrashReport611.txt](https://github.com/hyprwm/Hyprland/files/10783571/hyprlandCrashReport611.txt)

**Comment by vaxerski** [comment]
mhm, odd. I'll ask you to do the debug coredump if you could.

`renderBorder` SEGVs, but it's a sizeable function that has never failed me. I'll need more details. See the issue guidelines, debug coredump part.

**Comment by debordle** [comment]
I manually changed the PKGBUILD to compile with make debug, moved my config to .config/hypr/hyprlandd.conf, and got these: 
[hyprlandd.log](https://github.com/hyprwm/Hyprland/files/10783811/hyprlandd.log)

[hyprlandCrashReport866.txt](https://github.com/hyprwm/Hyprland/files/10783810/hyprlandCrashReport866.txt)

[coredump866.txt](https://github.com/hyprwm/Hyprland/files/10783808/coredump866.txt)

When I tested it without hyprlandd.conf, it worked as expected opening the window. So here's the config:
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/10783818/hyprland.txt)
The exec-once line was added after the issues began and it also worked with the custom colors previously. I will try a test with the custom colors removed now.

(mocha.conf is this file: https://github.com/catppuccin/hyprland/blob/main/themes/mocha.conf)

**Comment by vaxerski** [comment]
what if
```
monitor=DP-1,1920x1080@300,auto,auto
```
v
```
monitor=DP-1,1920x1080@300,auto,1
```

**Comment by debordle** [comment]
I appear to be stable with `monitor=DP-1,1920x1080@390,0x0,1`.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10850187/patch.txt)

Apply this patch. It should crash again, but now with a more useful log message. Send the log afterwards.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11153542/patch.txt)

please check this patch, should fix the issue. Lmk

**Comment by vaxerski** [comment]
patch got pushed anyways, check on head.

**Comment by romanstingler** [comment]
@debordle @sleeplessKomodo is this resolved for you guys ??
