### ISSUE TITLE
Hyprland fails to spawn child-windows in WPS Office applications

### ISSUE THREAD

**Issue by Fleimi** [hyprwm/Hyprland#1581]
WPS Office applications (Writer, Spreadsheet, etc.) fail to have a child-window spawned such as when choosing options like Save As or Open File. These applications force control to the child-window and as it does not spawn, the main window becomes un-interactable as well as unresponsive to commands such as `killactive`. However, the window borders seem to mistakenly indicate that the main window is still under focus.

Tested on sway as well as on X with bspwm and these window managers do not exhibit this behaviour (i.e, they work as expected).

**Steps to reproduce:**
Click Save As or Open File inside WPS Office Spreadsheets

**Observed behaviour:**
Child window with the file selector does not spawn, main window become un-interactable as well as unkillable via `killactive`

**Comment by vaxerski** [comment]
do you have a properly running xdg-desktop-portal?

**Comment by Fleimi** [comment]
I am able to get a screenrecording going via PipeWire source in OBS, which I assume to mean xdg-desktop-portal is running without issues.

![image](https://user-images.githubusercontent.com/73422514/219972352-e4009c5f-fb9d-48d5-8124-0fd02f47e1ad.png)

**Comment by vaxerski** [comment]
hm. Odd since:

![image](https://user-images.githubusercontent.com/43317083/219974880-da8d5b12-220e-4c5b-b38c-dd76a75ff249.png)

**Comment by Fleimi** [comment]
That's LibreOffice, isn't it? My bug report is about WPS Office. I can also confirm that LibreOffice works just fine.

**Comment by vaxerski** [comment]
tf is wps office

**Comment by Fleimi** [comment]
What do you expect me to say?

**Comment by vaxerski** [comment]
"this garbage: <link to an arch package>"

**Comment by Fleimi** [comment]
You can close the bug report if you aren't going to acknowledge it.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/220061921-eae45e50-36ac-4183-aaea-cb4930804aed.png)

?

**Comment by vaxerski** [comment]
are you _sure_ the window doesnt appear? Have you checked `hyprctl clients`?

**Comment by Fleimi** [comment]
I tried navigating to it via keyboard but I wasn't able to find it. I'll get back to you with more information when I get home.

**Comment by vaxerski** [comment]
The keyboard is not a reliable source. `hyprctl clients` is a better one.

**Comment by Fleimi** [comment]
Checked with `hyprctl clients`, window appears in client list. 0.21.0beta-2.

**Comment by vaxerski** [comment]
well, what with it? does it maybe spawn outside the bounds? Behind? on a different workspace? 

Have you tried grabbing its title/class and making a windowrule?
