### ISSUE TITLE
Group rework bugs with unfloat

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#1582]
Two bugs. Nº 1 is for the togglefloat dispatcher, Nº2, for allfloat.
1. Trying to unfloat a group window does not work, the window do not go to its tile position.
2. Executing two times the 'allfloat' dispatcher for un-floating the group window freezes Hyprland.
Thank you.

**Comment by vaxerski** [comment]
1. Cannot repro, works flawlessly for me.
2. should be fixed in df2956b411bd9b8c3fbc750bfcc3e7268a59d739

**Comment by Aqa-Ib** [comment]
1. I can't repro it anymore, weird.
2. Beautiful.
Thank you so much.
