### ISSUE TITLE
New window management around groups.

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#1585]
At the moment, we do not have the ability to open a tiled window in a workspace filled with a group window.
Maybe we can approach this with a dispatcher to select the workspace (or selecting it with the mouse if gaps are present):
- If the workspace is selected, new windows become tiled. 
- If the group is selected, new windows become grouped.

**Comment by vaxerski** [comment]
I was thinking about a config option that locks groups. You could toggle it via a hyprctl call. Or maybe a dispatcher for workspaceopt.

**Comment by Aqa-Ib** [comment]
Another way I can think of would be, somehow "deselecting" the group window that is filling the workspace, then creating a new window becomes tiled beside the group.
Just giving ideas, I don't know if they are valid though. Do your best vaxerski.

**Comment by vaxerski** [comment]
added a `lockgroups` dispatcher in a66ef50469c7a347d27a9afec83db1be70be1c84

`lockgroups,lock` `lockgroups,unlock`

**Comment by Aqa-Ib** [comment]
Works great! thanks!
