### ISSUE TITLE
hyprctl clients and activewindow throw "err bad any_cast"

### ISSUE THREAD

**Issue by barondernacht** [hyprwm/Hyprland#1586]
Starting from git rev 2463 `hyprctl clients` and `hyprctl activewindow` throw the error `Err bad any_cast`.

System:
Kernel 6.1.12 on Arch Linux using hyprland-nvidia-git

**Comment by vaxerski** [comment]
fixado in ecd015626546e28e759afde606e63d71d2fae181

mamma mia
