### ISSUE TITLE
Screen rotation with Hyprctl

### ISSUE THREAD

**Issue by JeanSchoeller** [hyprwm/Hyprland#1588]
While trying to code automatic screen rotation on my Surface pro I stumbled into what seems to be a bug (at least on my side maybe it works for someone else).

**Issue**: Impossible to send a command to Hyprctl to enable screen rotation

**Reproduce the issue**: Get monitor name through `hyprctl monitors`

```
Monitor eDP-1 (ID 0):
2736x1824@59.959000` at 0x0
description: LG Display 0x0555 0x000010A1 (eDP-1)
make: LG Display
model: 0x0555
serial: 0x000010A1
active workspace: 1 (1)
reserved: 0 40 0 0
scale: 2.00
transform: 0
focused: yes
dpmsStatus: 1
vrr: 0
```

Try to rotate screen using : 

`hyprctl keyword monitor eDP-1,transform,1`

Console returns "ok" but no rotation occurs.

**Comment by vaxerski** [comment]
cfg:
```
monitor = eDP-1,[res],[pos],[scale]
```

hyprctl:
```
hyprctl keyword monitor eDP-1,transform,1
```

works 4 me

**Comment by JeanSchoeller** [comment]
So something from my system

**Comment by JeanSchoeller** [comment]
Finished building the package for automatic screen rotation
https://github.com/JeanSchoeller/iio-hyprland

**Comment by RandomLegend** [comment]
@JeanSchoeller 

i found your package, works beautifully! However, it doesn't rotate the touchinput with it....so i am using a Lenovo Yoga that has a touchscreen that can be flipped 180° to transform into a big tablet.

I'd love to have it in portrait mode when flipped, but as of right now i'd have to manually change the touchinput. Could you insert that in your package aswell? That IF there is a touchscreen, that should be rotated in the same manner as the monitor orientation.

That would be awesome!

**Comment by JeanSchoeller** [comment]
Thanks for the feedback
I wonder if this can integrated to the hyprctl command. I doubt it.
Best I can think of so far is to add a udev rule. I will look into it.

**Comment by RandomLegend** [comment]
hyprctl keyword device:wacom-hid-517f-finger:transform 1
hyprctl keyword device:wacom-hid-517f-pen:transform 1

This is the hyprctl command for that. It works, i don't know how you could implement the proper name of the specific device as config for each user

**Comment by JeanSchoeller** [comment]
I wrote a dirty solution until I figure something more in details. The last package version should work. Please write an issue if it does not.

**Comment by RandomLegend** [comment]
I can't open an issue on your project...is it disabled?

I updated it, and sadly it does not work

**Comment by JeanSchoeller** [comment]
> I can't open an issue on your project...is it disabled?
> 
> I updated it, and sadly it does not work

I opened one [here](https://github.com/JeanSchoeller/iio-hyprland/issues/1) 😄
