### ISSUE TITLE
You cannot click with the touchscreen without a mouse connected

### ISSUE THREAD

**Issue by root2185** [hyprwm/Hyprland#1592]
If you try to click using the touchscreen when no mouse is connected it doesn't work.

Luckily you can use `ydotool` that creates a virtual mouse.
But you cannot perform a click on some things, with the touchscreen, e.g. `hyprctl kill` even when a mouse is connected.

**Comment by vaxerski** [comment]
fixed in 4d3f2ca96b006fe9fd27de7f1bd4d317ad732762
