### ISSUE TITLE
Drop down menus close instantly when hovering them in some programs (MatLab)

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/Hyprland#1593]
- Steps to reproduce:
Install MatLab (it is a pain and you need a license)? I remember having the same issue on Visual Paradigm, but I don't have it anymore. I also remember someone else saying they had the same issue, but I don't remember on what software. Opening some drop down menus and hovering them will close them instantly, making it impossible to use them.

- Expected outcome:
Have a drop down menu that doesn't close when you hover it.

- Noted outcome:
It closes, for some reason. It seems like the drop down menu is considered a separate window, since it has the decorations I set in my hyprland config.

https://user-images.githubusercontent.com/98901170/220157241-17ab0c11-a116-43c3-abbd-49c82b3dd26f.mp4

**Comment by vaxerski** [comment]
xwayland moment

**Comment by MathisP75** [comment]
Ah, any known solution for this?

**Comment by vaxerski** [comment]
you have 3 options, cope, make a mr, or wait for me to eventually maybe fix this

**Comment by hikkidev** [comment]
You could try similar configs:
```
windowrulev2 = float,floating:0,class:^(ide*)
windowrulev2 = forceinput,class:^(ide*)
windowrulev2 = windowdance,class:^(ide*) # allows IDE to move child windows
```

**Comment by MathisP75** [comment]
I tried this and it doesn't fix anything...

**Comment by vaxerski** [comment]
update to -git

add a `nofocus` rule targeting the disappearing dropdowns

should fix this

**Comment by MathisP75** [comment]
Interesting, I'll try this

**Comment by dtop129** [comment]
I tried adding the nofocus rule to the dropdown menus with latest -git, and now the dropdown menus don't disappear, but then the elements inside it are clickable only if I keep the mouse button pressed and move the cursor inside the dropdown, otherwise the elements are unclickable.

**Comment by MathisP75** [comment]
I only saw that occur with Matlab, I am not sure if there's other software it affects.

**Comment by jdsee** [comment]
> You could try similar configs:
> 
> ```
> windowrulev2 = float,floating:0,class:^(ide*)
> windowrulev2 = forceinput,class:^(ide*)
> windowrulev2 = windowdance,class:^(ide*) # allows IDE to move child windows
> ```
> 
> Debug: `hyprctrl clients` and `hyprctl layers`

Just commenting in case someone else runs into this.
I had a similar problem with Zotero where some dropdown menus wouldn't show up at all. The `windowdance` rule helped with that. Thanks!

**Comment by siggsy** [comment]
## For anyone searching for a quick jank solution

For anyone stumbling upon this, current working solution is to disable focus for dropdowns, but you have to hold the mouse button in order to be able to select dropdown items.

I have the following rules:
```
# History window is stealing focus and preventing further input
windowrulev2 = nofocus, class: ^(MATLAB [\w\d]* - academic use)$, title: ^(Command HistoryWindow)$
windowrulev2 = noborder, class: ^(MATLAB [\w\d]* - academic use)$, title: ^(Command HistoryWindow)$
windowrulev2 = opacity 1.0 override, class: ^(MATLAB [\w\d]* - academic use)$, title: ^(Command HistoryWindow)$

# Disable focus for dropdowns
windowrulev2 = nofocus, class: ^(MATLAB [\w\d]* - academic use)$, title: ^(DefaultOverlayManager\.JWindow)$
```

## For anyone who has time to implement a proper fix

From what I have gathered from running `watch -n0.1 hyprctl clients` and listening to the IPC socket, I managed to get another solution with `noinitialfocus` rule on dropdowns, but it requires you to do the following:
- Click on the "open" dialog
- Move the mouse slightly down and wait for the blue hint to pop up
- This causes for `win0` window to be opened and closed
- After this, the dropdown appears to be in focus and allows for selection

I don't recommend this solution, since it takes more time to actually select the dropdown, but it gives a hint at where the problem lies.

**Comment by patri9ck** [comment]
Having this issue with Visual Paradigm.

**Comment by izmyname** [comment]
Still a thing?

**Comment by MathisP75** [comment]
> Still a thing?

I honestly have no clue. I installed Matlab on Windows with my university license, so I couldn't test it now.

**Comment by vaxerski** [comment]
closin then

**Comment by oxmb** [comment]
> > Still a thing?
> 
> I honestly have no clue. I installed Matlab on Windows with my university license, so I couldn't test it now.

Yes, I am seeing this with Visual Paradigm on 918d8340afd652b011b937d29d5eea0be08467f5

**Comment by MathisP75** [comment]
Matlab ans visual paradigm? Seems like it happens with java software.

**Comment by legolas108** [comment]
Also had this problem with a Java program on KDE 6.3.3 with latest Eclipse Adoptium Temurin-21.0.6+7 and GDK LAF.
``` shell
export GDK_BACKEND=x11
```
before running the Java program fixes this. (Not really probably, but it's at least a workaround.)
