### ISSUE TITLE
Grouping and ungrouping window causes weird state

### ISSUE THREAD

**Issue by Merlin04** [hyprwm/Hyprland#1595]
If you do these steps:
- open two windows
- group the focused one
- switch focus to the other one, group and ungroup it
- move it into the group with the first window
Then you'll have a group with two windows in it, but the little tab indicator at the top doesn't update when you switch between them, and when you create a window in the group with window 1 focused, it will make it so you can only switch between and access window 1 and that new window.

**Comment by MightyPlaza** [comment]
Never mind was testing with the mouse instead of the keyboard. Yep this is an issue.

**Comment by MightyPlaza** [comment]
also fixed @vaxerski
