### ISSUE TITLE
Rofi do not respond

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#1598]
A recent Hyprland commit broke Rofi (the wayland fork).
I am trying to git bisect but I need some guidance please. I am doing the following:
1. git clone https://github.com/hyprwm/Hyprland.git
2. setting up a PKGBUILD to build the sources from the local repository.
3. git bisect start
4. git bisect bad 40622a9
5. git bisect good af4b970
6. build the sources, install, and see if it works or not.
7. Not working → git bisect bad
8. back to step 6 and try again.

What am I doing wrong? Thanks.

**Comment by vaxerski** [comment]
git should tell you the next commit. 

Then you `git reset --hard <hash> --recurse-submodules` and check it

then  `git bisect bad/good $(git rev-parse HEAD)`

rinse and repeat

**Comment by Aqa-Ib** [comment]
My bad. I had installed by mistake the X11 version of Rofi, and this version was broken with one of the X11 commits made on Hyprland two weeks ago. The rofi wayland fork works well though.
