### ISSUE TITLE
Hyprland becomes unstable with multiple monitors

### ISSUE THREAD

**Issue by Froggo8311** [hyprwm/Hyprland#1601]
I unfortunately was unable to collect any logs, but I noticed that sometimes hyprland can become unstable when connected to a second monitor. I was moving a waterfox window around, and it stopped responding properly and never properly adjusted to the new size. It eventually terminated the process, and then something (be it Hyprland or waterfox) sprung a memory leak and used all 20 GB of RAM, rendering my system useless untill I force-restarted it. I understand this isn't useful without adding any logs, so I'm going to try to mess around with it more and then collect some logs.

Unless Hyprland stores extra logs somewhere that I'm not aware of.

**Comment by vaxerski** [comment]
I use 2 monitors on a daily basis since Hyprland began and whatever you're experiencing has never happened to me.

Hyprland stores logs in /tmp/hypr/HIS, but it also does print them to stdout, so you can pipe them into a file.

**Comment by Froggo8311** [comment]
My bad. It turnes out my friend ran a fork bomb on my laptop without me noticing.
