### ISSUE TITLE
hyprland inside hyprland and full screen problem

### ISSUE THREAD

**Issue by o69mar** [hyprwm/Hyprland#1602]
when starting hyprland on hyprland, it actually starts hyprland inside of hyprland. and you can do it over and over again.

<img src="https://media.discordapp.net/attachments/172645867570987008/1077516252022579210/20230221_12h00m12s_grim.png">

and also if you go full screen on any browser (e.g brave, chrome and firefox) and exit full screen, the window just moves to the lower left, making it hard to click on stuff on the browser.

**Comment by vaxerski** [comment]
> when starting hyprland on hyprland, it actually starts hyprland inside of hyprland. and you can do it over and over again.

yes, how is that a bug?

> also if you go full screen on any browser (e.g brave, chrome and firefox) and exit full screen, the window just moves to the lower left, making it hard to click on stuff on the browser.

can't repro

**Comment by o69mar** [comment]
> yes, how is that a bug?
i think i prob picked bug report by accident..
> can't repro
okay
