### ISSUE TITLE
Resizing and floating not working on Scratchpad

### ISSUE THREAD

**Issue by ignamartinoli** [hyprwm/Hyprland#1607]
When on the Scratchpad window, resizing mode and floating window wouldn't work, unless the window moved to the Scratchpad was already floating.

**Steps to reproduce**

1. Open a window
2. Push it to the scratchpad
3. Make it floating and try to move or resize it with mouse, or enter the resize mode and try to diminish it

**Expected outcome**

-

**Noted outcome**

-

**Comment by vaxerski** [comment]
dupe of #827

**Comment by ignamartinoli** [comment]
@vaxerski uh I'm sorry, when searching for existing issues I used the word "Scratchpad" instead of "special" workspace
