### ISSUE TITLE
How to set up wayvnc headless ? in nixos

### ISSUE THREAD

**Issue by PlumpMath** [hyprwm/Hyprland#1610]
Hello.
I am a nixos module user. (not in home-manager)
How to set up wayvnc headless ?
in my case,
After connection, gray or black screen...but able to Mouse control only.
The remote monitor comes out.

In sway, wayvnc headless is being used.
in config-code
programs.sway.extraPackages = with pkgs;[ 
         sway
         swaylock
         swaylock-effects
         sway-unwrapped 
];

You must enter these four packages to make wayvnc headless work at sway.

Is the hyprland nix project still unpatched like sway? (sway-unwrapped... is it patched right?)

...and one thing I'm curious about is that in wayland
Like x11vnc, I wonder if it is impossible to synchronize the screens of both the remote and original local computers at the same time. (I want to see the screen on the local computer in the room while controlling it on the remote computer concurrently. This is very inconvenient.)

Thanks.

**Comment by vaxerski** [comment]
@fufexan for nix

**Comment by fufexan** [comment]
> programs.sway.extraPackages = with pkgs;[ sway swaylock swaylock-effects sway-unwrapped ];
> 
> You must enter these four packages to make wayvnc headless work at sway.

No? `sway` only should be needed. `sway-unwrapped` isn't used anyway if you include it there. The other two have nothing to do with wayvnc.

> Is the hyprland nix project still unpatched like sway? (sway-unwrapped... is it patched right?)

Patched in what way? Hyprland is patched to work with HiDPI and optionally Nvidia. `sway-unwrapped` does not have any patches relevant to wayvnc (see [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/sway/default.nix#L34-L49)).

> Like x11vnc, I wonder if it is impossible to synchronize the screens of both the remote and original local computers at the same time. (I want to see the screen on the local computer in the room while controlling it on the remote computer concurrently. This is very inconvenient.)

That's just display mirroring. It's explained in the wiki.

Apart from the above, I don't see anything NixOS specific about wayvnc. You can run it just like you would on any other distro.

**Comment by PlumpMath** [comment]
sway
swaylock
swaylock-effects
sway-unwrapped

It's strange, I put only the above in programs.sway.extraPackages (At first, I put everything related to wayland, such as wayland to wayvnc, and ran it,  i'm tested filtering only four of them must be put in extraPackages to avoid errors such as collision and vnc works.)
So, hyprland is also wrapped like sway (I mistakenly thought that there was a case where the nix code was patched. Because, anyway, hyprland flake also has a similar module configuration internally.)

**Comment by izmyname** [comment]
Since the question was answered - prolly close?

**Comment by PlumpMath** [comment]
https://discourse.nixos.org/t/hyprland-screen-sharing/43658/7

It seems that it still doesn't work on NixOS. I hope Hyprland supports screen sharing soon.

**Comment by fufexan** [comment]
Hyprland has supported screen sharing for a long while now.

**Comment by PlumpMath** [comment]
@fufexan "You're right; after trying again with the AMD GPU and Hyprland as you mentioned in your comment, I successfully set up Hyprland WayVNC. The issue now is that on my NVIDIA computer, it only shows a gray screen when connecting. I'm currently looking for a solution to this."
