### ISSUE TITLE
Add mouse_left and mouse_right

### ISSUE THREAD

**Issue by argonarch** [hyprwm/Hyprland#1614]
The keys for wheel in vertical exist (mouse_up and mouse_down), and keys for wheel in horizontal (as mouse_left and mouse_right) not exist. by default his function is scroll horizontal but  there are very useful as switcher of tabs for a program

The problem is that i can not change their functionality in hyprland.conf because no exist a key for this

**Comment by vaxerski** [comment]
added in 14a2de0d0e0565ff889bcb1f5f803421a05cffc1
