### ISSUE TITLE
eww configs in the wiki get slow over time

### ISSUE THREAD

**Issue by tralph3** [hyprwm/Hyprland#1615]
I use eww with hyprland. I have a workspaces widget on the upper left side of the bar. I have used the script [provided in the hyprland wiki](http://wiki.hyprland.org/Useful-Utilities/Status-Bars/#eww) to make it work.

And, it does work, but it gets slow over time. As soon as the bar opens, it works instantly. I can instantly change workspaces and the corresponding workspace gets highlighted at the exact same time I press the button. I can also click on it and they get highlighted instantly. But after some time, it gets slower and slower.

After a while, I change workspace and it's not until maybe half a second or even a full second later that the corresponding workspace gets highlighted. And the click is messed up too. It gets the same delay, only it's worse since with keybinds at least I can still change workspaces instantly, it just takes a while for eww to catch up, but with the mouse, I need to wait for eww to catch up to switch to another workspace, making it really sluggish.

If I run `eww reload`, it fixes itself, and the workspace switcher works instantly once again. I don't know how to fix this.

I tested the get current workspace script manually, and it does seem to output instantly, so I don't know what may be the issue.

[Here](https://github.com/tralph3/.dotfiles/tree/9f8d6e5e7f53d2914808888c574d4b911824160d/.config/eww) is my eww config.

https://user-images.githubusercontent.com/41462117/220809300-44235135-5c80-4283-b4e2-f9751ab3b40e.mp4

**Comment by tralph3** [comment]
For some reason the video is not playing on the browser. You can right click and save as to download it and play it locally.

**Comment by vaxerski** [comment]
@fufexan uses eww and might help

**Comment by fufexan** [comment]
I don't know whether that's the best ever script, since it uses `hyprctl` a lot, which means waiting for a response, parsing the json, and only after that doing what you actually need to do.

I have a better implementation (imo) [here](https://github.com/fufexan/dotfiles/blob/main/home/programs/eww/scripts/workspaces).

You may have to tweak it a bit to fit your the look of your current module, but otherwise it should be functionally the same, but a lot faster.

**Comment by tralph3** [comment]
Where does it use hyprctl a lot? It calls it every time you change workspaces sure, but how does that explain the slowdown? It's instant for a good few hours, and after a while it gets slower and slower. It's really weird.

**Comment by fufexan** [comment]
Well I don't know how to explain the slowdown without more info. As a first good step I would replace `jq` with `jaq` (note jaq doesn't support string interpolation if you need it), as it's usually faster and may fix your slowdowns.

If it's still slow, please add `set -ex` to the scripts and see if anything's off in the output.

**Comment by tralph3** [comment]
I guess I can leave a separate terminal with the script running and leave it for a few hours since I can't access the output from the process eww is running, or at least I don't know how to.

**Comment by fufexan** [comment]
When `set -ex` is present in a script, the script output will be logged into `eww logs`. That's normally done as well, but it gets more verbose with `set -ex`.

**Comment by tralph3** [comment]
I left the script running in a terminal for a good while, as soon as I started the Hyprland session. Despite seeing eww slow down as usual, the script on the terminal still outputs the current workspace instantly. So I guess the script ain't being slow.

**Comment by fufexan** [comment]
Well it can't be eww that's slow, as in my case it works instantly even after days of being open.

**Comment by mewoocat** [comment]
I'm having this exact same issue with the default Hyprland EWW bar

**Comment by barondernacht** [comment]
Did you keep an eye on `eww logs` making sure the logs are not being spammed from a misconfiguration which leads to the slowdown. I also do not get a slowdown even after days of having the eww bar open.

**Comment by JustSimplyKyle** [comment]
Oh yeah that, if you have multiple defpoll's that are running at interval 0, it will cause slowdowns. It even stops tooltip from appearing.

**Comment by tralph3** [comment]
I have a single defpoll that runs every 10 seconds for the clock. The scripts are getting used with deflisten, which is their purpose theoretically, so no misuse there or anything. This is the section in my eww config where I define the variables that use the scripts:

    (deflisten workspaces :initial "[]" "scripts/get-workspaces")
    (deflisten current_workspace :initial "1" "scripts/get-current-workspace")
    (defwidget workspaces []
      (eventbox
        :onscroll "scripts/change-current-workspace {} ${current_workspace}"
        :class "workspaces-widget"
        (box
          :space-evenly false
          (for workspace in workspaces
            (eventbox
              :onclick "hyprctl dispatch workspace ${workspace.id}"
              (box
                :class "workspace-entry ${workspace.id == current_workspace ? "current" : ""} ${workspace.windows > 0 ? "occupied" : "empty"}"
                (label
                  :text "${workspace.windows > 0 ? "" : ""}")))))))

**Comment by JustSimplyKyle** [comment]
Oh hold on, I had this issue
I believe that the script itself is not the problem, since if you make its output to a file, you can see that it responds to the workspace change immediately. The issue is eww itself. It doesn't accommodate for the change, which I have no idea why.

**Comment by tralph3** [comment]
On close inspection, it appears to be eww itself what gets slow, since the clock also gets wildy out of sync.

**Comment by romanstingler** [comment]
@vaxerski could be related to
