### ISSUE TITLE
renameworkspace does not exist or does not work

### ISSUE THREAD

**Issue by 3ri4nG0ld** [hyprwm/Hyprland#1616]
In ([https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces](https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces))  renameworkspace appears, but does not work.

![image](https://user-images.githubusercontent.com/24411137/220814431-54ecec1d-fc50-4bee-bf8e-b0295e204f6b.png)

**Comment by taylor85345** [comment]
Are you running an up-to-date build of Hyprland? The dispatcher works for me exactly as you typed it, while running the latest git commit. If you are on a release it looks like that was added in 0.21.0, which landed on 1/28. 

If you are running the AUR package, you may need to cleanbuild to make sure you are up-to-date.

**Comment by 3ri4nG0ld** [comment]
It was indeed in a previous commit 😅, sorry for the inconvenience.
