### ISSUE TITLE
Can't select floating window if it's alone on a workspace

### ISSUE THREAD

**Issue by leg7** [hyprwm/Hyprland#1617]
## Steps to reproduce:

open window A in workspace
make A floating
open window B in workspace
close B

## Expected outcome:

B is unselected but can be reselected with something like "movefocus" or "cyclenext"

## Noted outcome:

It's impossible to reselect the window without clicking on it with the mouse.

## Hyprland version

Hyprland, built from branch main at commit 2bf7f9e4136ebef6db1159c636b163ecb96f23ccdirty (fixup constraint snapping on no hint).
flags: (if any)

**Comment by vaxerski** [comment]
cyclenext now will after 60e37d727def25c87a3fd6c47751c05f6082260f

can I close this?

**Comment by leg7** [comment]
Yep cyclenext works now but if I had to guess most people only use movefocus. Would fixing this for movefocus be feasible?

**Comment by 3ri4nG0ld** [comment]
Something strange happens to me, when I move an Xwayland window there is a lag, but it doesn't happen with normal Wayland windows. I don't know if this issue refers to that.

**Comment by dranull** [comment]
I've just noticed my bookmark to this issue, which I totally forgot and created a dupe #4129. :/

**Comment by izmyname** [comment]
Can't repro. I committed all focus related windowrules for floating windows, and the focus does change to a floating window, after all tiled are closed.

**Comment by izmyname** [comment]
UPD: since no one else reported, neither here nor as a separate issue, should it be closed?

**Comment by leg7** [comment]
This is fixed for me.
