### ISSUE TITLE
Fix for touchpad gestures

### ISSUE THREAD

**Issue by etherrorcode404** [hyprwm/Hyprland#1618]
I am on a Hp probook 4440s, its a decade old laptop. I have been trying to get the gestures to work on this.
here is the output of ```$ libinput list-devices```;
```
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event9
Group:            7
Seat:             seat0, default
Size:             83x40mm
Capabilities:     pointer
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    none
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive
Rotation:         n/a
```

according to the wiki this should enable gestures;
```
gestures {
    workspace_swipe = true
    #workspace_swipe_invert = true
    #workspace_swipe_min_speed_to_force=5
}
```

**Comment by etherrorcode404** [comment]
i also have these line in the input section;
```
input {
    follow_mouse = 1

    touchpad {
        disable_while_typing = 1;
        natural_scroll = false
    }
}
```

**Comment by vaxerski** [comment]
by default the gesture is a 3-finger swipe afaik, what does not work? does it not activate at all?

**Comment by etherrorcode404** [comment]
it doesn't activate at all

**Comment by vaxerski** [comment]
it might be then your touchpad not supporting it

**Comment by etherrorcode404** [comment]
how to get it to support gestures?

**Comment by vaxerski** [comment]
what I meant by not supporting is that the hardware you own might not be able to register more than one finger at a time.

**Comment by etherrorcode404** [comment]
it should detect when i use three fingers, get it log a file and everytime it logs i could use ```$hyperctl [args]``` to change workspaces

**Comment by etherrorcode404** [comment]
are you saying my potato hardware, is the issue?

**Comment by etherrorcode404** [comment]
cant be it supports two finger scrolling according to ```$ libinput list-devices```

**Comment by vaxerski** [comment]
that doesnt mean it supports it, it just means libinput set it to that. try libinput-gestures, or some diagnostic tool. Gestures work for everyone except for you so it seems like your hardware is at fault here.

**Comment by etherrorcode404** [comment]
any chance gestures require users to have ```wmctrl``` preinstalled?

**Comment by etherrorcode404** [comment]
looks like your partially correct, ```libinput-gestures``` throws permission errors

**Comment by etherrorcode404** [comment]
okay i have a feeling this because i am not using a display manager, i am using ```startw``` to start my wayland server

**Comment by etherrorcode404** [comment]
```startw``` is the same idea as ```startx``` aims to be a minimalistic way to start your display server. Unlike display managers which is bloated

**Comment by vaxerski** [comment]
which is fucking idiotic because you can start any wayland compositor by executing it in tty.

`Hyprland`

**Comment by etherrorcode404** [comment]
frr? why is that??

**Comment by vaxerski** [comment]
because wayland is not xorg?

**Comment by etherrorcode404** [comment]
it works on my end. 
```$ yay -s startw```
```$ touch .winitrc && echo "exec Hyprland" >> .winitrc```
run startw from ttyx

**Comment by etherrorcode404** [comment]
adding support to startw might not be a bad idea, because some people prefer being more cli  side of things

**Comment by vaxerski** [comment]
sir that is not on me. That is to be reported to startw devs. if you want to do cli, just run hyprland from a tty like the wiki tells you to do.

Assuming your gesture issue is fixed?

**Comment by etherrorcode404** [comment]
yes turns out, startw is pretty much useless like you mentioned we can run hyprland from tty. But that does seem to be the issue the touchpad either

**Comment by etherrorcode404** [comment]
according to [hp](https://support.hp.com/bg-en/document/c03356342); 
```
Touchpad with gestures support, on/off button with LED indicator, two-way scroll, two pick buttons.\
```

**Comment by etherrorcode404** [comment]
emphasizing on the gesture suport, it can't be a hardware issue

**Comment by vaxerski** [comment]
does kde / gnome work? or any other wlroots compositor with gestures (wayfire I think?)

**Comment by etherrorcode404** [comment]
havent tested it :/

**Comment by etherrorcode404** [comment]
i think it works on xorg

**Comment by riley-martin** [comment]
@etherrorcode404: in the output of `libinput list-devices`, it only lists `pointer` in the capabilities section. My touchpad with gesture support shows `pointer gesture`.
> according to [hp](https://support.hp.com/bg-en/document/c03356342);

>> Touchpad with gestures support, on/off button with LED indicator, two-way scroll, two pick >> buttons.  

Maybe the libinput driver for your touchpad doesn't support all its features?

**Comment by etherrorcode404** [comment]
shoud this work?
```
gestures {
    workspace_swipe = true
    #workspace_swipe_fingers = 2
    #workspace_swipe_invert = true
    #workspace_swipe_min_speed_to_force=5
}
```

**Comment by etherrorcode404** [comment]
i can figure out how to further debug this, because xdotool doesn't work in wayland obv

**Comment by vaxerski** [comment]
I think it's libinput failing to work with your touchpad.

**Comment by etherrorcode404** [comment]
> I think it's libinput failing to work with your touchpad.

unfortunately your right, ```$ libinput debug-events``` confirms it. When scrolling it with three fingers it takes input as ```POINTER_SCROLL_FINGER```

**Comment by vaxerski** [comment]
welp then not a hyprland issue

**Comment by etherrorcode404** [comment]
Reported to the libinput devs: 
https://gitlab.freedesktop.org/libinput/libinput/-/issues/867
