### ISSUE TITLE
Ability to disable mouse acceleration for mouse alone and not trackpad (setting separate config for mouse and touchpad)

### ISSUE THREAD

**Issue by suraj10k** [hyprwm/Hyprland#1621]
When adding "force_no_accel = true" under the input section of confit file it disables mouse acceleration on the mouse but trackpad becomes very sensitive and inaccurate. It would be very useful to be able to have a separate config for mouse and touchpad such that it's possible to set "force_no_accel = true" on the mouse alone and not the touchpad.

**Comment by vaxerski** [comment]
hmmm I wonder if
![image](https://user-images.githubusercontent.com/43317083/221004112-e1cd24b4-4b48-4b04-a51f-3a89de83612d.png)

hmmm

![image](https://user-images.githubusercontent.com/43317083/221004254-e17118cc-351e-40d0-8819-c746946d8728.png)
