### ISSUE TITLE
Work around for workspace gestures not working 

### ISSUE THREAD

**Issue by etherbiswas** [hyprwm/Hyprland#1622]
Reference: [issues#1618](https://github.com/hyprwm/Hyprland/issues/1618)

As of now there is no way to go to a workspace that is not currently open.

```
bind = CTRL ALT, h, workspace,e-1
bind = CTRL ALT,  l, workspace,e+1
bind = ALT SHIFT, h, movetoworkspace,e-1
bind = ALT SHIFT, l,  movetoworkspace,e+1
```

these bindings really improve workflow but it would be nice if it was possible to create new workspaces rather than iterating open workspaces. According to [wiki](https://wiki.hyprland.org/Configuring/Dispatchers/) there are 8 options for workspaces, where e is for relative open workspaces. So, to sum things up; under gestures there is an option to create new workspaces; 

```
gestures {
    workspace_swipe = true
    workspace_swipe_create_new = true
}
```

it would be nice to have the something similar for a keyboard centric workflow. Thanks for you consideration!

**Comment by vaxerski** [comment]
well you can go to an unopened workspace by the `workspace` diapatcher but I get you.

**Comment by etherrorcode404** [comment]
https://github.com/hyprwm/Hyprland/commit/60e37d727def25c87a3fd6c47751c05f6082260f 
what does this commit change?

**Comment by etherrorcode404** [comment]
I looked into the Hyprland code base itself, its really neat. I don't think this should be hard to implement at all since ```gestures:workspace_swipe_create_new``` already exists.
Reference: https://github.com/hyprwm/Hyprland/blob/cb98242ea7faff04dad3ae166aff7126184f17c5/src/managers/input/Swipe.cpp

**Comment by etherbiswas** [comment]
Use Relative ID
```
bind = CTRL ALT, h, workspace, -1
bind = CTRL ALT, l, workspace, +1
bind = ALT SHIFT, l, movetoworkspace, +1
bind = ALT SHIFT, h, movetoworkspace, -1
```
