### ISSUE TITLE
hyprctl keyword monitor doesn't rotate touchscreen input

### ISSUE THREAD

**Issue by RandomLegend** [hyprwm/Hyprland#1624]
So i use hyprctl keyword to rotate my screen and also use (https://github.com/JeanSchoeller/iio-hyprland) to do that automatically.

Works perfectly fine. But it doesn't rotate the touchinput from my touchscreen. I have a Lenovo Yoga and i like to flip the keyboard over and use it as a big tablet in portrait mode. The window rotation works nice, but how could i rotate the touchinput?

Also are there any plans to support the gestures via Touchscreen? I love the 3 finger swipe to change the workspace.

Thanks in advance!

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#touchdevice

> Also are there any plans to support the gestures via Touchscreen?

plans? ye. Not much more than that tho

**Comment by root2185** [comment]
You can use lisgd for gestures https://aur.archlinux.org/packages/lisgd.
I have some config that you can use to start if you are interested.

I also made a wvkbd (on-screen keyboard) landscape tablet 1920x1080 layout also.

**Comment by RandomLegend** [comment]
Yeah i would happily take that config to play around, thanks!

Also for the keyboard; As long as i could change the layout to 1080x1920, because that would be the orientation i would use the keyboard in

**Comment by RandomLegend** [comment]
@vaxerski the wiki you linked doesn't explain how i would use the hyprctl keyword command to rotate the touchdevice.

I used the hyprctl devices and found my touchdevice, but no matter how i format the command, i get the error: `Error setting value <wacom-hid-517f-finger,transform,1> for field <touchdevice>: No such field.`

**Comment by root2185** [comment]
> Yeah i would happily take that config to play around, thanks!

You need to find the right even in /dev/input.
Sadly here it chages, sometimes is 10 sometimes is 12.
This launch lisgd, it is based on Sxmo file `sxmo_hook_lisgdstart.sh`.
I only made one gesture,1 finger swipe up (from bottom) `-g "1,DU,B,*,keyboard.sh open"` that open the osk.
```
#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2022 Sxmo Contributors

LISGD_THRESHOLD="${SXMO_LISGD_THRESHOLD:-125}"
LISGD_THRESHOLD_PRESSED="${SXMO_LISGD_THRESHOLD_PRESSED:-60}"
#LISGD_INPUT_DEVICE=/dev/input/event12
#LISGD_INPUT_DEVICE=/dev/input/event10
LISGD_INPUT_DEVICE="${SXMO_LISGD_INPUT_DEVICE:-"/dev/input/event12"}"

#-g format:
#   fingers,swipe,edge,distance,command
#order matters, only the first match gets executed   -g "1,DU,B,*,setsid -f inputhandler.sh upbottomedge" \
lisgd "$@" -d "$LISGD_INPUT_DEVICE" ${orientation:+-o $orientation} \
	-t "$LISGD_THRESHOLD" -T "$LISGD_THRESHOLD_PRESSED" \
	-g "1,DRUL,BR,*,setsid -f inputhandler.sh bottomrightcorner" \
	-g "1,DU,B,*,keyboard.sh open" \
	-g "1,DLUR,*,*,setsid -f inputhandler.sh upright" \
	-g "1,ULDR,*,*,setsid -f inputhandler.sh downright" \
	-g "2,RL,*,*,setsid -f inputhandler.sh twoleft" \
	-g "2,LR,*,*,setsid -f inputhandler.sh tworight" \
	-g "2,DU,*,*,setsid -f inputhandler.sh twoup" \
	-g "2,UD,*,*,setsid -f inputhandler.sh twodown" \
	-g "3,RL,*,*,setsid -f inputhandler.sh threeleft" \
	-g "3,LR,*,*,setsid -f inputhandler.sh threeright" \
	-g "3,DU,*,*,setsid -f inputhandler.sh threeup" \
	-g "3,UD,*,*,setsid -f inputhandler.sh threedown"

```
 
> Also for the keyboard; As long as i could change the layout to 1080x1920, because that would be the orientation i would use the keyboard in

Portrait? That would be the default since I made the landscape.
The kbd is made for a phone so the only changes are the height values in e.g. `layout.mobintl.h`:
```
#define KBD_PIXEL_HEIGHT 660

/* how tall the keyboard should be by default (can be overriden) */
#define KBD_PIXEL_LANDSCAPE_HEIGHT 360
```

**Comment by vaxerski** [comment]
@RandomLegend 

`hyprctl keyword device:device-name:transform 1`

**Comment by RandomLegend** [comment]
> 

Thank you very much!

**Comment by Estebiu** [comment]
@RandomLegend If you're still interested, there's this:https://github.com/JeanSchoeller/iio-hyprland
to automatically rotate your screen, touchscreen and wacom layer.
You could pair it with https://github.com/alesya-h/linux_detect_tablet_mode so that the screen will rotate only if the device is in tablet mode.
They're both on the aur.

**Comment by viato115** [comment]
Sorry for reviving this thread, but @RandomLegend, how did you find out the device name? I have a l13 Yoga Gen2, hyprctl devices only spits out "wacom-pen-and-multitouch-sensor-finger", with which the hyprctl keyword device: command doesn't work. Evtest end input-utils both state something like 056a:51f8, but I don't know how to incorporate this into the hyprctl command, nothing I've tried worked so far

**Comment by RandomLegend** [comment]
@viato115 i just used hyprctl devices and got wacom-hid-517f-finger and wacom-hid-517f-pen from that, i then put this into into hyprctl keyword device
Sorry, don't have anything more for ya...
