### ISSUE TITLE
Bind won't work when the command contains hash symbol(#) eg. bind=SUPER,e,exec,echo 'some text' | rg '#regex'

### ISSUE THREAD

**Issue by benmooo** [hyprwm/Hyprland#1625]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by vaxerski** [comment]
please for christ's sake read the wiki. https://wiki.hyprland.org/Configuring/Configuring-Hyprland/#comments

**Comment by benmooo** [comment]
How this could be. I've tried to prefix a backslash to the character. I've also tried to search in the wiki but didn't get what I want. Sorry for the time we both spent
