### ISSUE TITLE
mouse and touchpad lag on floating windows 

### ISSUE THREAD

**Issue by Vikash-Singh-Tanwar** [hyprwm/Hyprland#1628]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by vaxerski** [comment]
+1 for reading the thing you posted. No clue what you are talking about.

**Comment by 3ri4nG0ld** [comment]
Something strange happens to me, when I move an Xwayland window there is a lag, but it doesn't happen with normal Wayland windows. I don't know if this issue refers to that.

**Comment by 3ri4nG0ld** [comment]
Something strange happens to me, when I move an Xwayland window there is a lag, but it doesn't happen with normal Wayland windows. I don't know if this issue refers to that.

**Comment by vs66388** [comment]
> Something strange happens to me, when I move an Xwayland window there is a lag, but it doesn't happen with normal Wayland windows. I don't know if this issue refers to that.

yup same thing normally thier is no lag

**Comment by vs66388** [comment]
> +1 for reading the thing you posted. No clue what you are talking about.

it happens only on xwayland windows i posted a vedio on reddit regarding this issue it only happens in floating windows

**Comment by vaxerski** [comment]
reddit is not a place for reporting bugs. Please post information regarding the issue _here_.

**Comment by zstg** [comment]
I've noticed that the gesture lag occurs only on Firefox windows

**Comment by romanstingler** [comment]
@vs66388 does this still occur with the latest commit?

**Comment by Sinaaaa** [comment]
> @vs66388 does this still occur with the latest commit?

This is occurring for me right now. (Latest git from AUR)
I was really happy that after I forced Firefox in normal Wayland mode the lag went away, but then I noticed the same issue with all xwayland windows.

**Comment by izmyname** [comment]
Was it fixed? I had some laggy behaviour before, but all works fine now.

**Comment by romanstingler** [comment]
no lags on my 3 machines
@zstg @Vikash-Singh-Tanwar anyone of you affected ??
