### ISSUE TITLE
Brave browser flickered when switching workspace...

### ISSUE THREAD

**Issue by EvilBoi123** [hyprwm/Hyprland#1629]
Also happened when jump between monitors. (observe the mouse)

Only Brave, the other window does not affected. 

Have tested on sway, it didn't happen there. 

https://user-images.githubusercontent.com/102599991/221233476-4553e42a-c50d-4962-8f13-537716c888ff.mp4

**Comment by vaxerski** [comment]
your bar is changing height, forcing brave to resize, triggering #1462
