### ISSUE TITLE
Feature request: kill the active window

### ISSUE THREAD

**Issue by root2185** [hyprwm/Hyprland#1631]
`killactive` actually just closes a window.
I know that there is `hyprctl kill` maybe is possible to use that with the window id or something.

**Comment by etherrorcode404** [comment]
you can create a custom script that does this.
```
#!/bin/sh

pid=$(hyprctl activewindow -j | jq '.pid')
kill $pid
```

**Comment by etherrorcode404** [comment]
place this in the ~/.config/hypr/scripts/killactive 
dont forget to chage your binding, ex;
```
$mainMod = SUPER
bind = $mainMod, q, sh ~/.config/hypr/scripts/killactive,
```

**Comment by root2185** [comment]
If you don't have/want jq:
`kill $(hyprctl activewindow | grep "pid:" | awk -F ':' '{ print $2 }') `

**Comment by etherrorcode404** [comment]
so it works, close the issue?

**Comment by root2185** [comment]
I think that it would be nice to have this as a built-in feature.

**Comment by root2185** [comment]
I think that it would be nice to have this as a built-in feature.

If you have 3 terminals opened `kill` will kill all of them.
I wonder if you can kill only the active one.

**Comment by vaxerski** [comment]
you can't because that's how computers work.
