### ISSUE TITLE
Rotating the screen ruins touchscreen axis 

### ISSUE THREAD

**Issue by root2185** [hyprwm/Hyprland#1633]
After running `hyprctl keyword monitor eDP-1,transform,1` if I go up with the touchscreen the pointer moves to the left.
If I go down it moves it to the right.
If I go right it moves it up.
If I go left it moves it down.

Also the pointer is rotated of 180°.

**Comment by etherrorcode404** [comment]
see: https://wiki.hyprland.org/Configuring/Monitors/

```
normal (no transforms) -> 0
90 degrees -> 1
180 degrees -> 2
270 degrees -> 3
flipped -> 4
flipped + 90 degrees -> 5
flipped + 180 degrees -> 6
flipped + 270 degrees -> 7
```

**Comment by vaxerski** [comment]
#1624

**Comment by root2185** [comment]
This could be done automatically maybe?
I don't that someone wants to rotate the screen but not the touchscreen input.

**Comment by Estebiu** [comment]
Back in sway I would do it like this: "exec_always swaymsg input 1267:11187:ELAN9008:00_04F3:2BB3 map_to_output eDP-1
". You plobably could do the same  with hyprctl on hyprland somehow

**Comment by root2185** [comment]
As vaxerski said in the mentioned issue:
```
bind = $mainMod SHIFT, Up, exec, hyprctl keyword monitor eDP-1,transform,1 && hyprctl keyword device:gxtp7386:00-27c6:011a:transform 1

bind = $mainMod SHIFT, Left, exec, hyprctl keyword monitor eDP-1,transform,0 && hyprctl keyword device:gxtp7386:00-27c6:011a:transform 0
```
`hyprctl devices` will list the device.
