### ISSUE TITLE
Window resolution and cursor size with weird behavior

### ISSUE THREAD

**Issue by Vinschers** [hyprwm/Hyprland#1635]
First of all, thank you very much for this project, I really love Hyprland.

So, for the past few weeks, I've been configuring Hyprland to my personal needs in my Desktop computer (Arch Linux). Everything worked great (even with a NVIDIA GPU!), but, now, I want to use my setup in my notebook as well (also Arch).

However, after installing everything on my notebook, I noticed that the cursor size kept shrinking and expanding depending on which window was active and the windows themselves seemed to have the wrong resolution.

I don't know if I did something stupid in my config, so I tried reinstalling arch linux and, once logged in, I just installed the `hyprland` and the `librewolf-bin` (my browser) packages without any configs or customizations. I just changed the shortcut SUPER + Q to open librewolf instead of kitty and the window had the same behavior as previously. Therefore, I am assuming this issue has nothing to do with my customizations.

## Steps to reproduce
- Install `hyprland` using `yay`
- Install any other program
- Open the installed program in Hyprland

## Expected outcome
The windows should open normally, without any changes to their resolution

## Noted outcome
I recorded a video showcasing what is exactly happening [here](https://youtu.be/uvcB0vH1-N4). You can see that the window sizes are unusually large (I have a 1920x1080 display) and the weird size of the mouse cursor.

Thanks again for this amazing compositor and I am sorry if I missed something very obvious.

**Comment by etherrorcode404** [comment]
```
exec-once=hyprctl setcursor [THEME] [SIZE]
```

in your hyprland config

**Comment by etherrorcode404** [comment]
see [this (https://wiki.hyprland.org/FAQ/#:~:text=How%20do%20I%20change%20me,24%2C%20which%20is%20the%20default.)

**Comment by etherrorcode404** [comment]
use lxappearence for gtk apps

**Comment by vaxerski** [comment]
additionally to the above, if you use a size other than 24, add an export of `XCURSOR_SIZE=(size)` to your wrapper

**Comment by Vinschers** [comment]
Thank you for your answers!

I tried changing the cursor theme and setting XCURSOR_SIZE as you said, but the problem persisted.

Fortunately, I could fix the issue by manually adding the `monitor` config. In my desktop, I have two monitors, so I had to set the monitor keyword accordingly. As there is only one monitor in my notebook, I thought that Hyprland would automatically adjust to the monitor, but turns out it doesn't.

Thank you for your help regardless. Maybe you could add an entry in the Hyprland FAQ to always have your monitor configured.
