### ISSUE TITLE
No friction touchpad

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#1636]
I think a really neat feature to implement would be a no friction touchpad cursor, like the one that the steam Deck has. 
I don't even know if this would be useful at all. 
If it seems like a stupid idea, which most probably is, please feel free to scape this issue right away.

Thanks in advance for having read this

**Comment by vaxerski** [comment]
a what?

**Comment by Estebiu** [comment]
You know how when you let the touchpad on the steam deck, the cursor maintants a bit of momentum and continues going? Exactly

**Comment by vaxerski** [comment]
tf

**Comment by Estebiu** [comment]
You're making me feel stupid, thanks
