### ISSUE TITLE
Feature: `hyprctl` output in json

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#164]
good day to you!

Suggestion for ability to output `hyprctl` commands in json (by adding flag?)

```bash
hyprctl clients -j > output.json
```

Usecase: comfort in parsing output by instruments such as `jq`

Thank you!

**Comment by fedoranvar** [comment]
it works good!

thank you!

**Comment by MindfulMinun** [comment]
The correct link is https://wiki.hyprland.org/Configuring/Using-hyprctl/#flags
