### ISSUE TITLE
Add key chords support.

### ISSUE THREAD

**Issue by sadikeey** [hyprwm/Hyprland#1647]
It would have been nice if we would have **keychords** support in  Hyprland just like in emacs, Xmonad, Qtile etc.

**Comment by vaxerski** [comment]
what are keychords?

**Comment by cyrinux** [comment]
> what are keychords?

I feel like its what qutebrowser do also, chaining keys,  eg to do a `next`, you do `gn` instead of `Control+n`.
You press and release `g` (go to), then press and release `n` (next).

**Comment by vaxerski** [comment]
then it's doable with submaps, no clue why this is an issue.

**Comment by sadikeey** [comment]
> what are keychords?

So in Keychords first we will have a modifier key combination like **Mod+P** that will be pressed first, after releasing that key combination we will press some other key like **n** or whatever.
For example
- Mod+P n, opens network manager
- Mod+P b, open bluetooth manager, so on and so forth 
Xmonad, Qtile, and DWM(patch) also has keychords.

**Comment by vaxerski** [comment]
yeh, submaps then

**Comment by sadikeey** [comment]
No dude, submaps and keychords are different thing. 
This [dt's video](https://youtu.be/7pfxHoAnCkE?t=556) will give you pretty good  idea what keychords are

**Comment by vaxerski** [comment]
everything keychords allow you to do is doable with submaps.

{SUPER, P}, {0, A} from the DT video would be

```
bind = SUPER, P, submap, superpsubmap
submap = superpsubmap
bind = ,A,exec,something
submap = reset
```

**Comment by sadikeey** [comment]
> everything keychords allow you to do is doable with submaps.
> 
> {SUPER, P}, {0, A} from the DT video would be
> 
> ```
> bind = SUPER, P, submap, superpsubmap
> submap = superpsubmap
> bind = ,A,exec,something
> bind = ,A,submap,reset
> submap = reset
> ```

Thanks it works and Sorry dude that I did not read the docs properly.

**Comment by sgtxn** [comment]
Hey @vaxerski sorry for necrobumping, but I guess this thread is what most people will see when googling "hyprland chords" so maybe keeping the questions here makes sense.

Anyway I got two questions regarding using submaps as chords:
- Is there a way to abord a chord chain (reset the submap) when you hit a button that isn't explicitly bound to anything in the submap? Other than binding reset to every button one-by-one, obviously, hehe.
- Is there a way to reset the submap on a timer (eg. after 2 seconds from switching to a submap) in case no button was pressed?

Cause this is kinda how it works in sxhkd, and I keep running into the problem that I somehow trigger a submap (sometimes accidentally, sometimes I forget what I wanted to run and get distracted) and as you can imagine it basically kills all the hotkeys until I figure out that I'm in a submap and press the reset key manually.  
My muscle memory is slowly getting to the point that when hotkeys stop working the first thing I do is press submap reset, but I kinda wish it was simpler than this :)

**Comment by vaxerski** [comment]
no, but it was suggested in some issue

**Comment by tchofy** [comment]
@sgtxn, It's doable if you pair it with hyprctl:

```
$reset = hyprctl dispatch submap reset && #use a variable to keep things more readable
bind = $mainMod, E, exec, sleep 2 && hyprctl dispatch submap reset #2 seconds timeout
bind = $mainMod, E, submap, execute
submap = execute
bind = , B, exec, $reset firefox
bind = ALT , B, exec, $reset firefox --private-window
bind = , E, exec, $reset kate
bind = , F, exec, $reset dolphin
bind = , C, exec, $reset discord 
bind = , V, exec, $reset virt-manager 
bind = , escape, submap, reset #can manually exit it before the 2s timeout in case you trigger it by accident
submap = reset #tell hyprland that any binds under this is not part of the execute submap, unrelated to the $reset var
```
