### ISSUE TITLE
blur_new_optimizations directive causes delay to background update when switching workspaces

### ISSUE THREAD

**Issue by zenmetsu** [hyprwm/Hyprland#1648]
I am having an issue with transparency + blur.  If I have a terminal, such as `kitty` or `havoc` open with transparency and switch quickly to a workspace with an app that does not have transparency, such as firefox or obs-studio, and then quickly switch back to the terminal, there is no issue.  But if I permit the non-transparent workspace to remain active for more than about 15 seconds and switch back to the workspace with transparency, there is a ghost-image of the non-transparent application window that persists for anywhere from 1 to about 10 seconds before the background image gets applied as expected.

This issue only exists if `blur_new_optimizations` is enabled.  

I can provide additional details if needed.

**Comment by vaxerski** [comment]
can't repro. Can I get the config and a recording?

**Comment by zenmetsu** [comment]
Thanks. I will try to get to the bottom of it.  I can confirm that the `blur_new_optimizations` was the workaround, however in going through a myriad of changes in an attempt to get Discord to work... I somehow "fixed" the issue and now the `blur_new_optimizations` setting can be enabled without issue.  I discovered this while attempting to get a recording for you.

Feel free to close this issue, however I am going to work through my changes backwards and find out which change permitted me to enable this setting without issue, and I will post my findings here in case anyone else runs into it.

**Comment by vaxerski** [comment]
Sure. Reopen it when you find it reproducible

**Comment by mjhanninen** [comment]
Just to let you know I'm hitting this exact bug currently. If `blur_new_optimizations = on` and I return to a workspace with a transparent window (Tmux here too) after having spent rougly 15 seconds or more on another workspace, a mirage of that other workspace linger for couple seconds behind the transparent windows. When `blur_new_optimizations = off` everything works just fine.

In my case this is not a big problem at all as I prefer not to blur the background in the first place.   

I'm running Hyprland 0.27.2 within an up-to-date Arch on a 6th gen. Carbon X1 (which, I think, implies Intel UHD 620 GPU).
