### ISSUE TITLE
Can't build Hyprland after Plugin API commit

### ISSUE THREAD

**Issue by UserSv4** [hyprwm/Hyprland#1649]
Steps to reproduce:
Follow https://wiki.hyprland.org/Getting-Started/Installation/#cmake-recommended
Expected outcome:
Hyprland gets built and installed.
Noted outcome:
Fails to build.
```
cmake --build ./build --config Release --target all -j16
ninja: error: '/personal/dev/Hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
make[1]: *** [Makefile:144: release] Error 1
make[1]: Leaving directory '/personal/dev/Hyprland'
make: *** [Makefile:170: install] Error 2
```

**Comment by UserSv4** [comment]
Builds fine on previous commit

**Comment by HanoJing** [comment]
Building it with meson works, which I tested.
So like this:

```
meson _build
ninja -C _build
ninja -C _build install --tags runtime,man
```

for me `--tags runtime,man` did not work, so I left them out.

**Comment by fufexan** [comment]
@UserSv4 have you done `git submodule update --init subprojects/udis86`?

**Comment by vaxerski** [comment]
`sudo make config`

**Comment by vaxerski** [comment]
fixed make install in 15d108fbc11f6e302eb42bc568e4a9d94066ed2f

**Comment by vaxerski** [comment]
oops, fixed. thanks

**Comment by emrakyz** [comment]
I also can't update on Gentoo. I normally update daily. 

![Error](https://user-images.githubusercontent.com/89175311/221744043-5fb1e1b2-ee2e-4ee6-b779-23deb5fde05f.png)

**Comment by HanoJing** [comment]
You are using the wayland-desktop overlay, right?
I use gentoo and don't use the package manager for it.
For cloned builddirs, I use an auto-update script, but that's sub-optimal.
the ebuild from the wayland-desktop overlay should work, since it doesn't involve any cmake from what I saw. 

Oh, the ebuild from wayland-desktop has `--skip-subprojects` at the last but one line.

**Comment by emrakyz** [comment]
@HanoJing Yes I use wayland-desktop overlay. Normally I could update daily from -9999 package with or without "system-wlroots" use flag. But today, there is an error. What is --skip-subprojects?

![image](https://user-images.githubusercontent.com/89175311/221874534-2558cb15-78ec-48d9-93cd-558340907aeb.png)

**Comment by HanoJing** [comment]
> @HanoJing Yes I use wayland-desktop overlay. Normally I could update daily from -9999 package with or without "system-wlroots" use flag. But today, there is an error. What is --skip-subprojects?
> 
> ![image](https://user-images.githubusercontent.com/89175311/221874534-2558cb15-78ec-48d9-93cd-558340907aeb.png)

`--skip-subprojects` is a flag that - as in the name, skips the pulled subprojects from hyprland. So, remove that flag from the ebuild and run `ebuild hyprland-999.ebuild manifest` to regenerated the manifest for the ebuild, then try to rebuild hyprland.

**Comment by emrakyz** [comment]
@HanoJing Thanks for the tip. I updated the ebuild but now I get another error:

mkdir: cannot create directory ‘/var/cache/...’: Permission denied
 * ERROR: gui-wm/hyprland-9999::wayland-desktop failed (unpack phase):

**Comment by HanoJing** [comment]
> Can it be because I changed the ebuild?

No, I changed tons of ebuilds before, they built.

I will try to reproduce your issue on my machine.
