### ISSUE TITLE
Delay in restart and poweroff from Hyprland session

### ISSUE THREAD

**Issue by asifakonjee** [hyprwm/Hyprland#1651]
I am facing delay in restart/poweroff from Hyprland. If i use systemctl poweroff/reboot or any other script like from arcolinux (arcolinux logout) or rofi powermenu, it takes almost a minute to poweroff/restart. In contrary, if I log out from the session to sddm and then restart/poweroff from there it takes only 4/5 seconds.

Am I missing something? It would be very helpful if someone point me to the right direction. Thanks

**Comment by Ryymm** [comment]
You need install [sddm-git](https://aur.archlinux.org/packages/sddm-git)
The sddm package in the extra repository does not support Wayland sessions.

**Comment by asifakonjee** [comment]
I have sddm-git installed. I have no problems in logging in or log out. The delay occurs if I reboot/power off from an open/running hyprland session.

If log out from hyprland session to sddm and then restart or power off from sddm, it works just fine.

**Comment by vaxerski** [comment]
sddm issue, use sddm-git. This is not an issue with hyprland, but with sddm.
