### ISSUE TITLE
AUR: build is broken

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1652]
I'm getting this when trying to update hyprland-git from the AUR

```
cmake --build ./build --config Release --target all -j12
ninja: error: '/home/x/.cache/yay/hyprland-git/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
```

**Comment by justinesmithies** [comment]
Yeah I too am getting the same error since today.

```
cmake --build ./build --config Release --target all -j16
ninja: error: '/home/justine/.cache/paru/clone/hyprland-git/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
make: *** [Makefile:144: release] Error 1
```

**Comment by Dickby** [comment]
Until it's fix, change the build() block of the PKGBUILD to
```
build() {
	cd "${srcdir}/${_pkgname}"
	git submodule update --init
	make fixwlr
	cd "./subprojects/wlroots/" && meson build/ --prefix="${srcdir}/tmpwlr" --buildtype=release && ninja -C build/ && mkdir -p "${srcdir}/tmpwlr" && ninja -C build/ install && cd ../
	cd udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja && cmake --build ./build --config Release --target all -j$(shell nproc) && cd ../..
	make protocols
    make release
	cd ./hyprctl && make all && cd ..
}

```

**Comment by Dickby** [comment]
@ThatOneCalculator : ping

**Comment by Dickby** [comment]
Everybody seems to have more than 10 cores these days, i'm still seeing `-j4`

**Comment by ThatOneCalculator** [comment]
I'm on vacay rn, I'll investigate when I have the chance

**Comment by WasteOfO2** [comment]
> Everybody seems to have more than 10 cores these days, i'm still seeing `-j4`

Atleast it aint a `Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz`, idk why i still have this relic

**Comment by pulsar256** [comment]
@ThatOneCalculator offering help as a contributor to the aur repo. ping me on discord if you want help.

**Comment by vaxerski** [comment]
T1C is not the owner of the aur -git pkg. @sandervankasteel  is.

**Comment by sandervankasteel** [comment]
I am aware that the AUR package isn't building. I hope to checkout it tonight (CEST) and get  it resolved. :relaxed:

**Comment by Dickby** [comment]
@WasteOfO2  

> Atleast it aint a Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz, idk why i still have this relic

Because as you are already wasting O2 you don't want to produce too much CO2?

Fun fact: it's `Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz`  on my site!

**Comment by WasteOfO2** [comment]
> @WasteOfO2
> 
> > Atleast it aint a Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz, idk why i still have this relic
> 
> Because as you are already wasting O2 you don't want to produce too much CO2?
> 
> Fun fact: it's `Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz` on my side!

**Comment by vaxerski** [comment]
@sandervankasteel @ThatOneCalculator can one of y'all move their ass and add that one fuckin' line to the pkgbuild? thanks.

**Comment by pulsar256** [comment]
why can't all of this be part of one makefile target?

**Comment by vaxerski** [comment]
it is... it's `make all`. T1C just doesn't use it for some reason (maybe cuz arch-meson)

**Comment by sandervankasteel** [comment]
> @sandervankasteel @ThatOneCalculator can one of y'all move their ass and add that one fuckin' line to the pkgbuild? thanks.

First of all, personal life stuff got in the way. Secondly, I refused to be called and treated like this. I've just disowned the package. Whoever wants to take over the responsibility for it, he or she can have it. 

I'm out.

**Comment by vaxerski** [comment]
> I've disowned the package on the AUR.

Thanks! :)

**Comment by Youngermaster** [comment]
@vaxerski If you want I can own it for now.

**Comment by vaxerski** [comment]
I'd rather Kainoa owned it (just like all hyprland packages) He is now the maintainer. (Was co-) but still for some reason can't add me as a co-.

I usually update -bin and `hyprland` for updates, and I would do the same to `-git` if I had the perms.

**Comment by pulsar256** [comment]
This adapts the approach taken by the PKGBUILD for `make all`. If it conflicts with something else, this could be an dedicated target. It would be nice not to have keep two separate build scripts in sync.

```
  diff --git a/Makefile b/Makefile
  index 0bef0dc..0b53170 100644
  --- a/Makefile
  +++ b/Makefile
  @@ -1,5 +1,7 @@
   include config.mk
   
  +ROOT_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
  +
   CFLAGS += -I. -DWLR_USE_UNSTABLE -std=c99
   
   WAYLAND_PROTOCOLS=$(shell pkg-config --variable=pkgdatadir wayland-protocols)
  @@ -156,7 +158,12 @@ clear:
   all:
    make clear
    make fixwlr
  - cd ./subprojects/wlroots && meson build/ --buildtype=release && ninja -C build/ && cp ./build/libwlroots.so.12032 /usr/lib/ && cd ../..
  + cd "./subprojects/wlroots/" \
  +   && meson build/ --prefix="$(ROOT_DIR)/tmpwlr" --buildtype=release \
  +   && ninja -C build/ \
  +   && echo mkdir -p "$(ROOT_DIR)/tmpwlr" \
  +   && ninja -C build/ install \
  +   && cd ../
    cd subprojects/udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja && cmake --build ./build --config Release --t  arget all -j$(shell nproc)
    make protocols
    make release
```

**Comment by Youngermaster** [comment]
> I'd rather Kainoa owned it...

Well I tried... hahaha, I though that would be my first contribution to the AUR (I even [created an account for that](https://aur.archlinux.org/account/Youngermaster)), I suppose that maybe I will _calm down my urges_ with another project this weekend, either way I fixed the error with @Dickby's workaround. Thanks 👍🏻

**Comment by vaxerski** [comment]
PSA: The -git package got broken another time (wlroots dep update) and now it has a hard depend on `libdisplay-info` (AUR) and `libliftoff`.

**Comment by haru02w** [comment]
> PKGBUILD needs no change to build, but you need those two.
Even with these two packages installed, it won't compile
```
sudo pacman -Qk libliftoff libdisplay-info
libliftoff: 16 total files, 0 missing files
libdisplay-info: 18 total files, 0 missing files
```
```sh
cmake --build ./build --config Release --target all -j16
ninja: error: '/home/haru02w/.cache/yay/hyprland-git/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
make: *** [Makefile:144: release] Error 1
```

**Comment by justinesmithies** [comment]
> > PKGBUILD needs no change to build, but you need those two.
> 
> Even with these two packages installed, it won't compile
> 
> ```
> sudo pacman -Qk libliftoff libdisplay-info
> libliftoff: 16 total files, 0 missing files
> libdisplay-info: 18 total files, 0 missing files
> ```
> 
> ```shell
> cmake --build ./build --config Release --target all -j16
> ninja: error: '/home/haru02w/.cache/yay/hyprland-git/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
> make: *** [Makefile:144: release] Error 1
> ```

It builds just fine for me with those two installed and changing the PKGBUILD using this:

```
build() {
	cd "${srcdir}/${_pkgname}"
	git submodule update --init
	make fixwlr
	cd "./subprojects/wlroots/" && meson build/ --prefix="${srcdir}/tmpwlr" --buildtype=release && ninja -C build/ && mkdir -p "${srcdir}/tmpwlr" && ninja -C build/ install && cd ../
	cd udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja && cmake --build ./build --config Release --target all -j$(shell nproc) && cd ../..
	make protocols
    make release
	cd ./hyprctl && make all && cd ..
}
```

**Comment by ThatOneCalculator** [comment]
As I'm now back from vacation and finally have access to my keys, the fix has been pushed

**Comment by coffebar** [comment]
This bug is relevant for me on hyprland aur package (not hyprland-git)

**Comment by kyori-kyori** [comment]
Facing the same issue on non-git hyprland on fresh archinstalled system atm

**Comment by vaxerski** [comment]
fixed

**Comment by Porkepix** [comment]
@vaxerski Could you also bump `pkgrel` in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyprland as you did for the `.SRCINFO` please?
Bumping `pkgrel` on the latter while not doing on the former means that AUR helpers are seeing a `-2` revision available, but are still building a `-1` if user don't manually edit the PKGBUILD, resulting in the AUR helper wanting to update hyprland on every run.

Also, I randomly bumped into https://github.com/hyprwm/aur which seemed to be a good idea considering there's no way for non-maintainers to submit patches on AUR, but I guess it was too painful to maintain this on different places at the same time?

**Comment by vaxerski** [comment]
my bad fixed
