### ISSUE TITLE
lid switch binding is not working anymore

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1653]
this binding

bindl = ,switch:Lid Switch,exec,lid.sh

does not do anything anymore. I have confirmed with hyprctl device that "Lid Switch" is the name of the lid switch

**Comment by vaxerski** [comment]
"anymoar"

`git bisect`? Version which broke it at least?

**Comment by primalmotion** [comment]
ah forget it. not hyprland's problem. my ACPI driver was not compatible with linux 6.2.1
