### ISSUE TITLE
Dimaround rule for layers

### ISSUE THREAD

**Issue by PolGZ** [hyprwm/Hyprland#1657]
Hi,

I've been using hyprland for a week know, and everything has been working fine. I absolutely love this WM.

On the [wiki page about rules](https://wiki.hyprland.org/Configuring/Window-Rules/#rules) it shows the `dimaround` windowrule. Also, at the end of that page, it talks about what layers are, and it seems that they only have the `noanim` rule. I have a custom rofi powermenu script for login out, reboot, etc. If I didn't understand uncorrectly, `rofi` would be a layer, and it seems to be since I can see it in `hyprctl layers` as `namespace: rofi`, and not in `hyprctl clients`.

It would be very much appreciated if we could also dim around a powermenu like that.

In that case, I think right now it wouldn't be possible to differentiate between more than one type, since `hyprctl layers` doesn't seem to report any difference between app launcher / powermenu script.

Anyway, thanks for all the work. I've finally moved from X11 + bspwm to wayland thanks to this project!

**Comment by vaxerski** [comment]
> In that case, I think right now it wouldn't be possible to differentiate between more than one type, since hyprctl layers doesn't seem to report any difference between app launcher / powermenu script.

it's on rofi to set the namespace. Maybe it has a command line argument to do that.

**Comment by tasmo** [comment]
With Wofi it is possible to use the `--normal-window` argument.

Unfortunately the experimental command `rofi -normal-window` does not work.
