### ISSUE TITLE
Some crashes

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#1663]
Seems to be related to the x11 window changes yesterday.
All crashes happend when dealing with an x11 window, regaining focus after another fullscreen window closed or something like that.
Here is a crash report and a coredump, not totally shure that they are from the same crash though. 
[hyprlandCrashReport117259.txt](https://github.com/hyprwm/Hyprland/files/10856926/hyprlandCrashReport117259.txt)
[core.txt](https://github.com/hyprwm/Hyprland/files/10856939/core.txt)

By the way if you want to make it a bit easier to send these crash reports, give them an file extension than github doesn't refuse.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10859295/patch.txt)

try this patch

**Comment by vaxerski** [comment]
should be fixed with ea717731a41be907e9bfaa2c41a3f145452c7767. plox reopen if not

**Comment by vaxerski** [comment]
Actually fixed in https://github.com/hyprwm/Hyprland/commit/71496a0a3c31d9e0b7ce55a21713304fc23a46cd

**Comment by Dickby** [comment]
No crash report was created this time:
[dump.txt](https://github.com/hyprwm/Hyprland/files/10862880/dump.txt)

**Comment by vaxerski** [comment]
That doesn't say much. Please make sure you're on the latest commit by verifying `hyprctl version` matches with the git head

**Comment by romanstingler** [comment]
@vaxerski I think we can close that

**Comment by vaxerski** [comment]
probably
