### ISSUE TITLE
`Failure occurred in build()` when using hyprland-bin, hyprland-git and hyprland to install.

### ISSUE THREAD

**Issue by danielCruzSalazar** [hyprwm/Hyprland#1664]
Seems to be like a file is missing in the git for AUR installers, please let me know if I'm the one doing something wrong!

Steps to reproduce
    -Clean Arch installation through [archinstall](https://wiki.archlinux.org/title/archinstall#:~:text=archinstall%20is%20a%20helper%20library,the%20official%20documentation%20for%20that.), desktop environment pre-set with awesome dwm and intel opensource drivers.
    -both yay and paru AUR have given me the same error, haven't tried manual instalation since AUR is _strongly_ recommended.
        `yay hyprland-git` installing packages 1-4 and 1-3.
Expected outcome
    Hyprland successful installation.
Noted outcome
ninja: error: '/home/lakakid/.cache/yay/hyprland-git/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
make: *** [Makefile:144: release] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hyprland-git`

Terminal outcome
`Checking for modules 'wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;libdrm;egl;xkbcommon;libinput'
--   Found wayland-server, version 1.21.0
--   Found wayland-client, version 1.21.0
--   Found wayland-cursor, version 1.21.0
--   Found wayland-protocols, version 1.31
--   Found cairo, version 1.17.8
--   Found libdrm, version 2.4.115
--   Found egl, version 1.5
--   Found xkbcommon, version 1.5.0
--   Found libinput, version 1.22.1
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- XWAYLAND Enabled (NO_XWAYLAND not defined) checking deps...
-- Checking for module 'xcb'
--   Found xcb, version 1.15
-- SYSTEMD support is requested (NO_SYSTEMD not defined) checking deps...
-- Checking for module 'libsystemd'
--   Found libsystemd, version 253
-- Looking for systemd/sd-daemon.h
-- Looking for systemd/sd-daemon.h - found
-- Setting link libraries
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lakakid/.cache/yay/hyprland-git/src/hyprland/build
cmake --build ./build --config Release --target all -j8
ninja: error: '/home/lakakid/.cache/yay/hyprland-git/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by 'Hyprland', missing and no known rule to make it
make: *** [Makefile:144: release] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hyprland-git`

**Comment by vaxerski** [comment]
only git is broken, see #1652
