### ISSUE TITLE
When the last display is disconnected, or fails, the entire workspace and applications running inside the session are terminated

### ISSUE THREAD

**Issue by s-daveb** [hyprwm/Hyprland#1667]
I first noticed this when my computer, which is attached to a full-blown television, would suddenly end a remote gameplay session, or I would lose my terminal windows when somebody in the other room turned on the TV to stream video content.

Update: Given the log message I found, it looks like the developers are aware this is an issue?   My apologies if there is, all I found earlier in a search was something about suspend/resume on a laptop not working.

  
## Steps to reproduce:
1.  Disconnect your second display.
2. Launch a terminal window or some applications
3. Simulate a display cable failure, or a pet chewing on your cables, by disconnecting your HDMI adapter.
4. Reconnect it.

## Expected Result:
- Hyprland (and really any WM) should be smart enough to realize that the last display has been removed, and it should try to maintain its workspace in-memory until the system has a viable display again.  

## Observed Result:
- Wallpaper daemon blanks out.
- Applications are all terminated.
- Some session daemons have to be restarted. 

## Relevant Log File lines:
```
[WARN] Unplugged last monitor, entering an unsafe state. Good luck my friend.
[LOG] Callback 8d06a508 -> 8d06a500,  removed.
[LOG] Callback 8d06a4a0 -> 8d06a498,  removed.
[WARN] Recovering from an unsafe state. May you be lucky.
[LOG] Recovering a removed monitor.
[LOG] Registered signal for owner 8d06a2c0: 8d06a030 -> 8d06a410 (owner: )
[LOG] Registered signal for owner 8d06a2c0: 8d06a0c0 -> 8d06a478 (owner: )
[LOG] Registered signal for owner 8d06a2c0: 8d06a0b0 -> 8d06a4e0 (owner: )
[LOG] Applying monitor rule for HDMI-A-1
[LOG] Monitor HDMI-A-1: requested 1920x1080@120.000000, found available mode: 1920x1080@120000mHz, applying.
[LOG] Monitor HDMI-A-1 -> destroyed all render data
[LOG] Monitor HDMI-A-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Monitor HDMI-A-1 data dump: res 1920x1080@120.00Hz, scale 1.00, transform 0, pos 0x0, 10b 0
[LOG] Added new monitor with name HDMI-A-1 at 0,0 with size 1920x1080, pointer 8d069ef0
[LOG] New monitor: WORKSPACEID 2, exists: 0
[LOG] Monitor HDMI-A-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
```

I really like Hyprland, but if this is expected behavior, then I might have to switch back to something a little less ... deletey in how it handles unknown situations. 

Wanted to file an issue specifically for this behavior to see if it can be address this specifically, rather than this being an issue associated with misbehaving laptop displays.

**Comment by s-daveb** [comment]
It occurs to me that this could be a Wayland or WLRoots-defined behavior, I apologize in advance if this isn't Hyprland's fault, I'm rather ignorant to these new display systems.

**Comment by vaxerski** [comment]
> developers

Hah, I wish there were more of me.

Unsafe state should not bring apps down. At least it didn't use to. Haven't really checked on it for a while.

**Comment by s-daveb** [comment]
> > developers
> 
> Hah, I wish there were more of me.
> 
> Unsafe state should not bring apps down. At least it didn't use to. Haven't really checked on it for a while.

Didn't know you were doing this all by yourself.  That being said, thank you for your patience with my ignorance. 

I noticed that my XWayland apps can survive the unsafe state, but some wayland applications do not handle the situation well, such as swww. 

Perhaps the issue is with the individual applications, then?

**Comment by s-daveb** [comment]
> applications that work as layersurfaces are often failing, because once you remove the last output they are closed (as the display they were on is removed), and most can't recover from such state.
> 
> Consider making a script to restart them in such cases

Thank you so much! You've been a great help.  I'll look through the application docs, maybe there's a setting I haven't toggled!
