### ISSUE TITLE
[Regression] Choppy frame rate while dragging a window

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#1668]
# Setup
* NVIDIA 525.89.02
* NixOS

# Issue
Commit https://github.com/hyprwm/Hyprland/commit/984c2fdc6857de66697a35aede457464cf7adc76 causes window drag animation to become extremely choppy with a NVIDIA card, it feels like 1 fps.

What's crazy is that this bug disappears if I start a screen recording with my monitor's refresh rate: `$ wf-recorder -D -F fps=120 -c libx264rgb`

Here's a demonstration of what I'm seeing with my eyes:

https://user-images.githubusercontent.com/45666572/222257945-e53e7888-1974-4cfb-8c36-49de9eda6c16.mp4

(Alternative upload: https://streamable.com/tflife)

# Workaround
```
misc {
    animate_manual_resizes = 0
    animate_mouse_windowdragging = 0
}
```

**Comment by vaxerski** [comment]
reopened #1127
