### ISSUE TITLE
Expand functionality of desc:[MonitorDesc]

### ISSUE THREAD

**Issue by ProdigyNerd** [hyprwm/Hyprland#1670]
Currently, `desc:[MonitorDesc]` cannot be used to bind workspaces, for example, `wsbind=1,desc:SDC 0x4154`. Would be nice to see this functionality expanded so that `desc:[MonitorDesc]` is equal to `DP-1`, for example, for any configuration parameter.

**Comment by vaxerski** [comment]
added in dea71875e40d5ff4ad649b3c04b02419b06da5df
