### ISSUE TITLE
exec rofi not work.

### ISSUE THREAD

**Issue by matianhe3** [hyprwm/Hyprland#1671]
+ Linux carch 6.2.1-arch1-1
+ hyprland 0.22.0beta-1
+ rofi-lbonn-wayland-git 1.7.5.wayland1.r46.gc6b4dfe0-1

bind=SUPER, D, exec, rofi -show drun

rofi show :
` mode drun, is not found`
any mode same that.

in terminal run :
`rofi -show drun`
succeed.

**Comment by zstg** [comment]
Create a script having `rofi -show drun` and replace with the script (for the exec option)

**Comment by Aqa-Ib** [comment]
It works for me setting it up as you said.

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/222605790-10ebaf13-5f9e-49b2-9291-4670c16b3300.jpeg)

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/222605932-6e2d4035-36dd-46ed-804a-37e569bfd0dc.jpeg)

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/222606323-99085a0c-fcb3-4bc1-adf5-c5aab3ca9a32.jpeg)

**Comment by Aqa-Ib** [comment]
yeah, probably that comma at the end of the line is fucking it up.
