### ISSUE TITLE
Reloading hyprland causes layout to change?

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1672]
![image](https://user-images.githubusercontent.com/68589851/222440911-1159a941-ea93-4683-8c1f-25563c596713.png)
I have a layout like this, and I reload it turns into this.
![image](https://user-images.githubusercontent.com/68589851/222440997-b828e855-d637-4024-9bae-87134efe1e5b.png)
Another reload this.
![image](https://user-images.githubusercontent.com/68589851/222441025-1a621c59-aafa-4dba-a2ca-b6c08fc4c70c.png)

**Comment by JustSimplyKyle** [comment]
Fixed. Possibly by newest commit(51ce3ddd670ca9fb7d359ec8be617354c23ba072)

**Comment by vaxerski** [comment]
yeh forgot to close
