### ISSUE TITLE
Mouse scrolling is not detected after switching focus untill the mose is moved

### ISSUE THREAD

**Issue by BulbaWarrior** [hyprwm/Hyprland#1675]
### Steps to reproduce:
* Lift up your mouse so it's movements are not picked up
* Switch focus from a scrollable window with a keybind (movefocus dispatcher) and then switch back
* Try scrolling with the mouse still lifted

### Expected outcome
The window scrolls

### Noted outcome
It doesn't.  However, the scrolling continues after I move my mouse inside the window

A pretty minor bug, but it would be nice if it got fixed

**Comment by vaxerski** [comment]
this has been fixed a long while ago. What version are you on? `hyprctl version`

**Comment by BulbaWarrior** [comment]
```
Hyprland, built from branch main at commit 6b7e409f05536e45baa3dabeab0df77d05c9a96fdirty (properly clamp size in dragging floating corners).
flags: (if any)
```

**Comment by BulbaWarrior** [comment]
I  guess I should mention that it's the nvidia patch (`hyprland-nvidia-git` from AUR)

**Comment by vaxerski** [comment]
Oh wait, movefocus. Alright, got it.
