### ISSUE TITLE
Lock/Unlock groups as a single toggle instead of two separate binds

### ISSUE THREAD

**Issue by Kvn0l** [hyprwm/Hyprland#1676]
Would be better to have just one bind for the lockgroups dispatcher, similar to how togglefloating works, with a boolean property "locked" or "grouplocked" to be associated with the grouped windows for showing up on, hyprctl/IPC similar to the floating, pinned etc. properties

**Comment by vaxerski** [comment]
done in 489ef7c51c7d33eeba6d6a66b6697f52441ddf45, use `toggle` in lockgroups
