### ISSUE TITLE
Hyprland crashes with no reason given in arch/qemu

### ISSUE THREAD

**Issue by WilliamBehrens** [hyprwm/Hyprland#1677]
I'm currently using QEMU to run arch and I've installed hyprland through the aur packages (hyprland hyprpaper-git hyprpicker-git xdg-desktop-portal-hyprland-git). When running the `Hyprland` command from a tty (or trying to launch from sddm) the screen flashes for a moment them crashes with no reason given. I've checked the logs and nothing seems strange there either.

**Comment by WilliamBehrens** [comment]
I've been trying to debug this for a few days and haven't gotten anywhere, but when I tried again today to get a log to upload and suddenly the logs decide to include the line about the crash
```
[LOG] Instance Signature: _1677783821
[LOG] Hyprland PID: 781
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: framework
[LOG] Release: 6.2.1-zen1-1-zen
[LOG] Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:25 +0000


[LOG] GPU information:
00:01.0 VGA compatible controller [0300]: Red Hat, Inc. QXL paravirtual graphic card [1b36:0100] (rev 05) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: To rice, or not to rice, that is the question.


[CRITICAL] m_sWLRRenderer was NULL!
```

**Comment by vaxerski** [comment]
vms are not officially supported, also have you read [the wiki](https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm)?
