### ISSUE TITLE
Cannot Rotate the Screen

### ISSUE THREAD

**Issue by zcorn2017** [hyprwm/Hyprland#1685]
# Cannot rotate the screen
I recently find that transforming/rotating the screen/monitor by any degree (e.g. 90, 180) is not possible.
I have used hyprctl, hyprland.config and wdisplays to do it and none of them works.
Hyprcrtl returns Ok but nothing happens. 
I tried to read the log, it seems that the manager did not receive the `transform` command.
For example, if I try `transform 1`, the log output is still `transform 0`.

# Perhaps issues with hyprland itself?
I have tried it on swaywm / gnome wayland and nothing wrong happened. It seems not an issue with wlroots.
Anyone meets the same problem?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/222733898-4f31daa4-469a-457d-99de-fba5841659b9.png)
