### ISSUE TITLE
Cannot rotate the screen

### ISSUE THREAD

**Issue by zcorn2017** [hyprwm/Hyprland#1686]
# Cannot rotate the screen
> Sorry for my previous issue open to misinterpretation.

I recently find that transforming/rotating the screen/monitor by any degree (e.g. 90, 180) is not possible.
I have used hyprctl, hyprland.config and wdisplays to do it and none of them works.
Hyprcrtl returns Ok but nothing happens.

# Reproduction of the problem
I tried to read the log, it seems that the manager did not receive the transform command.
For example, if I try `transform 1`, the log output is still `transform 0`. 
As you may see, I have my hyprland config as below:
```
monitor=DP-8,preferred,auto,1
workspace=DP-8,1
```
However,  my log shows the transform parameter of DP-8 is still `0`:
```
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 7b2986f0: 7b24ee50 -> 7b298700 (owner: IME Keyboard Grab)
[LOG] Set keyboard focus to surface 7b3c03c0, with window name: Cannot Rotate the Screen · Issue #1685 · hyprwm/Hyprland and 10 more pages - Personal - Microsoft​ Edge
[LOG] Disable TextInput
[LOG] Callback 7b298728 -> 7b298720, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] Set keyboard focus to surface 7b7642a0, with window name: nvim ~/.config/hypr/hyprland.conf
[LOG] Enable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 7b2986f0: 7a8be0c0 -> 7b298700 (owner: IME Keyboard Grab)
[LOG] Set keyboard focus to surface 7b78d080, with window name: zcorn@archlinux:~
[LOG] Disable TextInput
[LOG] Callback 7b298728 -> 7b298720, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] Enable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 7b24edf0: 7b2742b0 -> 7b24ee00 (owner: IME Keyboard Grab)
[LOG] Set keyboard focus to surface 7b7642a0, with window name: nvim ~/.config/hypr/hyprland.conf
[LOG] Callback 7b24ee28 -> 7b24ee20, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] Enable TextInput
[LOG] Disable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 7ae71f30: 7b2c0e40 -> 7ae71f40 (owner: IME Keyboard Grab)
[LOG] Callback 7ae71f68 -> 7ae71f60, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] Set keyboard focus to surface 7b78d080, with window name: zcorn@archlinux:~
[LOG] Disable TextInput
[LOG] Enable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 7ae71f30: 7adda3a0 -> 7ae71f40 (owner: IME Keyboard Grab)
[LOG] Searching for matching rules for Alacritty (title: hyprctl keyword monitor DP-8,preferred,auto,1)
[LOG] Window 7b757410 set title to hyprctl keyword monitor DP-8,preferred,auto,1
[LOG] Hyprctl: keyword monitor : DP-8,preferred,auto,1
[WARN] No rule found for eDP-1, trying to use the first.
[WARN] No rules configured. Using the default hardcoded one.
[WARN] No rule found for eDP-1, trying to use the first.
[WARN] No rules configured. Using the default hardcoded one.
[LOG] Applying monitor rule for eDP-1
[LOG] Setting preferred mode for eDP-1
[LOG] Monitor eDP-1 -> destroyed all render data
[LOG] LayerSurface 7b354dc0 arranged: x: 0 y: 0 w: 1706 h: 30 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 7acf3b60 arranged: x: 0 y: 0 w: 1706 h: 1066 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor eDP-1 layers arranged: reserved: 0.000000 30.000000 0.000000 0.000000
[LOG] Monitor eDP-1 data dump: res 2560x1600@60.00Hz, scale 1.50, transform 0, pos 0x0, 10b 0
[LOG] LayerSurface 7b354dc0 arranged: x: 0 y: 0 w: 1706 h: 30 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 7acf3b60 arranged: x: 0 y: 0 w: 1706 h: 1066 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor eDP-1 layers arranged: reserved: 0.000000 30.000000 0.000000 0.000000
[LOG] Applying monitor rule for DP-7
[LOG] Setting preferred mode for DP-7
[LOG] Monitor DP-7 -> destroyed all render data
[LOG] LayerSurface 7b3b7f50 arranged: x: 1706 y: 0 w: 2560 h: 30 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 7aa8b440 arranged: x: 1706 y: 0 w: 2560 h: 1440 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-7 layers arranged: reserved: 0.000000 30.000000 0.000000 0.000000
[LOG] Monitor DP-7 data dump: res 2560x1440@59.95Hz, scale 1.00, transform 0, pos 1706x0, 10b 0
[LOG] LayerSurface 7b3b7f50 arranged: x: 1706 y: 0 w: 2560 h: 30 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 7aa8b440 arranged: x: 1706 y: 0 w: 2560 h: 1440 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-7 layers arranged: reserved: 0.000000 30.000000 0.000000 0.000000
[LOG] Applying monitor rule for DP-8
[LOG] Setting preferred mode for DP-8
[LOG] Monitor DP-8 -> destroyed all render data
[LOG] LayerSurface 7ad39b90 arranged: x: 4266 y: 0 w: 2560 h: 30 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 7b5e6c60 arranged: x: 4266 y: 0 w: 2560 h: 1600 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-8 layers arranged: reserved: 0.000000 30.000000 0.000000 0.000000
[LOG] Monitor DP-8 data dump: res 2560x1600@60.07Hz, scale 1.00, transform 0, pos 4266x0, 10b 0
[LOG] LayerSurface 7ad39b90 arranged: x: 4266 y: 0 w: 2560 h: 30 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 7b5e6c60 arranged: x: 4266 y: 0 w: 2560 h: 1600 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-8 layers arranged: reserved: 0.000000 30.000000 0.000000 0.000000
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Allocated texture for BGTex
[LOG] Background created for monitor DP-7
[LOG] Shaders initialized successfully.
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Allocated texture for BGTex
[LOG] Background created for monitor DP-8
[LOG] Shaders initialized successfully.
[LOG] Searching for matching rules for Alacritty (title: zcorn@archlinux:~)
[LOG] Window 7b757410 set title to zcorn@archlinux:~
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Allocated texture for BGTex
[LOG] Background created for monitor eDP-1
[LOG] Shaders initialized successfully.
[LOG] Searching for matching rules for Alacritty (title: cat /tmp/hypr/$(ls -t /tmp/hypr/ | head -n 2 | tail -n 1)/hyprland.log)
[LOG] Window 7b757410 set title to cat /tmp/hypr/$(ls -t /tmp/hypr/ | head -n 2 | tail -n 1)/hyprland.log
```

Even if I tried the command in hyprctl, it still did not work, but it returned `Ok`.

# Perhaps issues with hyprland itself?
I have tried it on swaywm / gnome wayland and nothing wrong happened. It seems not an issue with wlroots.
Anyone meets the same problem?

**Comment by vaxerski** [comment]
```
monitor=DP-8,preferred,auto,1
workspace=DP-8,1
```
this does not set the transform at all?

`hyprctl keyword monitor "DP-8,transform,x"`

**Comment by zcorn2017** [comment]
> 

It only returns `Ok` and nothing happened.
Could you suggest some possible underlying causes for this?
There is nothing wrong with SwayWM to rotate the monitor, so I think if there is something blocking the communication but I don't know the details.

**Comment by zcorn2017** [comment]
> ```
> monitor=DP-8,preferred,auto,1
> workspace=DP-8,1
> ```
> 
> this does not set the transform at all?
> 
> `hyprctl keyword monitor "DP-8,transform,x"`

It only returns Ok and nothing happened.
Could you suggest some possible underlying causes for this?
There is nothing wrong with SwayWM to rotate the monitor, so I think if there is something blocking the communication but I don't know the details.

**Comment by vaxerski** [comment]
try setting it in the config. Maybe you got the name wrong?

**Comment by amas0** [comment]
Wanted to chime in and say I'm experiencing the same issue, just the sequence of commands I've run and output:

```
amas ~ $ hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1080@60.049000 at 0x0
	description: AU Optronics 0x233D (eDP-1)
	make: AU Optronics
	model: 0x233D
	serial: 
	active workspace: 1 (1)
	reserved: 0 27 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0


amas ~ $ hyprctl keyword monitor "eDP-1,transform,1"
ok
amas ~ $ hyprctl monitors                           
Monitor eDP-1 (ID 0):
	1920x1080@60.049000 at 0x0
	description: AU Optronics 0x233D (eDP-1)
	make: AU Optronics
	model: 0x233D
	serial: 
	active workspace: 1 (1)
	reserved: 0 27 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

The transform itself never seems to be applied despite `hyprctl` reporting ok.

**Comment by vaxerski** [comment]
If it's not being applied it means you don't have an explicit rule for `eDP-1` set in the config.

**Comment by zcorn2017** [comment]
> If it's not being applied it means you don't have an explicit rule for `eDP-1` set in the config. `ok` just means the keyword was found and executed. Whether it did what you'd expect or not is not checked.

I have confirmed that there is nothing wrong with the name cuz I have tried it on different monitors. I think it's a recent issue because I did not encounter it until I did an update on my Arch system a few months ago.
BTW, do you mean that 'an explicit rule' is `monitor=DP-8,preferred,auto,1
workspace=DP-8,1`? If so, I have confirmed that there's been such a setting in my config but the problem still persists.

**Comment by zcorn2017** [comment]
> Wanted to chime in and say I'm experiencing the same issue, just the sequence of commands I've run and output:
> 
> ```
> amas ~ $ hyprctl monitors
> Monitor eDP-1 (ID 0):
> 	1920x1080@60.049000 at 0x0
> 	description: AU Optronics 0x233D (eDP-1)
> 	make: AU Optronics
> 	model: 0x233D
> 	serial: 
> 	active workspace: 1 (1)
> 	reserved: 0 27 0 0
> 	scale: 1.00
> 	transform: 0
> 	focused: yes
> 	dpmsStatus: 1
> 	vrr: 0
> 
> 
> amas ~ $ hyprctl keyword monitor "eDP-1,transform,1"
> ok
> amas ~ $ hyprctl monitors                           
> Monitor eDP-1 (ID 0):
> 	1920x1080@60.049000 at 0x0
> 	description: AU Optronics 0x233D (eDP-1)
> 	make: AU Optronics
> 	model: 0x233D
> 	serial: 
> 	active workspace: 1 (1)
> 	reserved: 0 27 0 0
> 	scale: 1.00
> 	transform: 0
> 	focused: yes
> 	dpmsStatus: 1
> 	vrr: 0
> ```
> 
> The transform itself never seems to be applied despite `hyprctl` reporting ok.

You may try:

```
monitor=eDP-1,preferred,auto,1.5
monitor=eDP-1,transform,1
workspace=eDP-1,1
```
I think @vaxerski applied this requirement recently because I used to rotate the monitor without 'explicit rules' until an update was made on my system.

**Comment by vaxerski** [comment]
> requirement recently

if by recently you mean 10 months ago then yes.

**Comment by untitledtrack04** [comment]
I am having issues with transform,1 at the end of my second monitor's config.

here's my current working config: 
monitor=HDMI-A-1,1920x1080@60,0x0,auto
monitor=HDMI-A-2,3440x1440@144,1920x0,auto

If I now try to save this config:
monitor=HDMI-A-1,1920x1080@60,0x0,auto,transform,1
monitor=HDMI-A-2,3440x1440@144,1920x0,auto

I get an error:
Config error at line 15 (configpath): invalid syntax at "transform"

I sincerely hope I've read the wiki wrong or something.. I've tried to mess with it a bit by adding a second config for the monitor with just the transform but that doesn't work..

If I ONLY use 
monitor=HDMI-A-1,transform,1
i don't get any errors but it also doesn't do anything.

trying:
hyprctl keyword monitor "HDMI-A-1,1920x1080@60,0x0,auto,transform,1"
it actually flips the monitor but i cannot access it with my mouse now.

If anyone has any ideas or answers please let me know.
