### ISSUE TITLE
Overcome hyprland wrapper

### ISSUE THREAD

**Issue by SimoriccITA** [hyprwm/Hyprland#1693]
### Discussed in https://github.com/hyprwm/Hyprland/discussions/1690

<div type='discussions-op-text'>

<sup>Originally posted by **SimoriccITA** March  3, 2023</sup>
use a [wrapper](http://wiki.hyprland.org/Getting-Started/Master-Tutorial/#launching-hyprland-part-1) to set the necessary env variables and exec Hyprland is more inconvenient that have the possibility to simply write ```Hyprland``` in your terminal or use the default ```/usr/share/wayland-sessions/``` file (that launch the command ```exec Hyprland```)  and have Hyprland itself that execute a script 

i propose an ```hyprlandrc``` in the same folder of ```hyprland.conf```  that'll be a script executed before loading ```hyprland.conf``` and the user will write the enviroment variables there.</div>

**Comment by Incompleteusern** [comment]
This would remove the need for a wrapped session in sddm too

**Comment by droc12345** [comment]
I use several compositors, and 
wayfire creates the executable and a wayfire-session script that calls wayfire, with desktop files for both.

labwc uses an environment file similar to autostart that has env vars, they only parse the env vars once though.

As far as desktop files it's easy enough to create one, for a wrapper script.
I've created several for various programs that don't provide one, XDG typically looks in <user home>/.local/applications and they get found by fuzzel/rofi/etc automatically.

**Comment by vaxerski** [comment]
done in d5093f7af0f2d1e6d39a3facd0806c36e9667af1 to dc7d783d1439b92b16bfe1851c2b699e7c7267e0

`env = YOUR_ENV,VALUE` in the config. Initialized prior to the Wayland server, so even stuff like `WLR_NO_HARDWARE_CURSORS` will work.

**Comment by vaxerski** [comment]
wrapper section got removed from the wiki too :)

**Comment by sanjaybaskaran01** [comment]
Hey team, I am using NVIDIA and I am trying to set the necessary nvidia settings in a wrapper, and execute it in /usr/share/wayland-sessions but it does not seem to work.
This is hyprland.desktop

```[Desktop Entry]
Name=Hyprland
Comment=An intelligent dynamic tiling Wayland compositor
Exec=/home/frosty/.local/bin/wrappedh1
Type=Application
```

and this is my  /home/frosty/.local/bin/wrappedh1
```
#!/bin/sh

cd ~

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

exec Hyprland
```

when I start the session, the environment variables are not set , how do I proceed? am I doing anything wrong here?

**Comment by vaxerski** [comment]
env keywords are invalid in bash. Where did you read you need a wrapper? Wrappers have been deprecated for months.

**Comment by sanjaybaskaran01** [comment]
My bad I meant 
```
#!/bin/sh

cd ~

export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland
#export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1

exec Hyprland
```
I have a hybrid graphics card, intel and NVIDIA. When I try to set the GBM_backend as nvidia-drm my SDDM manager does not let me login. After correct password it pushes me back into the login screen instead of going inside. I ran "journalctl -b 0 --grep "renderer for" according to the docs present [here](https://wiki.archlinux.org/title/Wayland#Requirements) and I get the result 
"--- no entries --- "
any clue why? @vaxerski

**Comment by vaxerski** [comment]
No. Nvidia is fully community-driven, I don't provide support for it

**Comment by vaxerski** [comment]
oops

**Comment by vaxerski** [comment]
wait tf you mean there is no quick start page anymore its been removed ages ago

**Comment by timblaktu** [comment]
well that's odd. I confirm that that link I posted gets 404, but it didn't when i first posted that a few weeks ago. Maybe I had an old version cached in a browser or something..

**Comment by vaxerski** [comment]
I removed the page as it was deleted months ago and was terribly outdated, the automatic site sync util doesnt automatically remove old pages

**Comment by timblaktu** [comment]
Headslap Deja vu moment: forgot about this convo and ended up creating a wrapper again while troubleshooting some other stuff and finding the same old outdated wiki QuickStart link as 2nd google hit for "hyprland wrapper".. i see now that it's just [a very old version](https://wiki.hyprland.org/0.19.2beta/Getting-Started/Quick-start/) :(

I wonder if its possible to put a **WARNING: OUTDATED** banner on outdated wiki pages?
