### ISSUE TITLE
The wlroots update seems to have broken things

### ISSUE THREAD

**Issue by Froggo8311** [hyprwm/Hyprland#1696]
It also shows that the github action checked too

**Comment by vaxerski** [comment]
Nix: #1695

Arch CI succeeds.

**Comment by Froggo8311** [comment]
I'm doing a make install and it's failing at compiling the cpp files. Hold on...

**Comment by vaxerski** [comment]
L

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/issues/1652#issuecomment-1454154657

**Comment by Froggo8311** [comment]
My computer's got a skill issue. Undefined reference to wlr_drm_lease_v1_manager_offer_output in Monitor.cpp. It seems the photo doesnt wanna upload. If it's got a new dep, then chances are its not installed yet, so I'll do that.
