### ISSUE TITLE
libinput: support discrete_scroll_factor for high resolution mouse wheels

### ISSUE THREAD

**Issue by edrex** [hyprwm/Hyprland#1702]
I have fancy mouse with a high-resolution wheel (microsoft sculpt ergo). Scroll only advances every 6 ticks (on linux, works fine on windows). I believe the solution requires supporting "high resolution mouse wheels".

See https://gitlab.com/warningnonpotablewater/libinput-config#how-to-use for detail.

**Comment by Estebiu** [comment]
Hyprland does already support high resolution mouse wheels, it's the apps themselves that do not.
#728

**Comment by vaxerski** [comment]
oh yeah right, forgot. Estebiu is correct.

**Comment by edrex** [comment]
My mouse mysteriously started scrolling 1-event-per-mechanical tick right after y'all replied, so I don't have motivation to investigate further. This at least demonstrates that adjusting the scroll factor is possible at some level, although which level remains mysterious. Will update with steps taken if/when my setup goes back to 1-event-per-6-ticks (probably next reboot).

**Comment by edrex** [comment]
I think the factor I'm talking about (discrete scroll factor) is a compatibility mode for apps that are listening for the old-style 120 degree events, while apps can also listen for fine-grained events for which there is a different libinput-level adjustment factor.
