### ISSUE TITLE
Nix build failure

### ISSUE THREAD

**Issue by dev-null-undefined** [hyprwm/Hyprland#1704]
Nix build system is currently broken when trying to use it as an overlay.

Here are last few lines of trying to build `wlroots-hyprland-hidpi-2023-03-02_5ae17de`
```
Dependency pixman-1 found: YES 0.42.2 (cached)
Dependency gbm found: YES 22.3.5 (cached)
Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES 
Run-time dependency libudev found: YES 252
Run-time dependency libseat found: YES 0.7.0
Build-time dependency hwdata found: YES 0.367
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libdisplay-info found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libdisplay-info
Message: Required for the DRM backend.

backend/drm/meson.build:8:0: ERROR: Neither a subproject directory nor a libdisplay-info.wrap file was found.

A full log can be found at /build/source/build/meson-logs/meson-log.txt
```

Building wlroots-hyprland works just fine when using the packages output of the flake, but the when using overlays it fails. 
From my understanding of the flake.nix file I think it's not applying custom version of those 2 libs (https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L35-L63) when you use it as overlay. So it fall backs to the nixpkgs one (the one that you are applying the overlay to).
You can see that it applies those version in packages over here https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L110.

Possible fix: 
1) Adding libs directly into overrides? https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L74-L77
2) Moving https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L35-L63 into the overlays?

Related commits: c1217066d1e7c6cd12f43134f9ef1145787f7905
@fufexan

**Comment by fufexan** [comment]
Thanks. I went with the first option.

**Comment by dev-null-undefined** [comment]
Thanks <3
