### ISSUE TITLE
Config doesn't read environment variables while setting environment variables

### ISSUE THREAD

**Issue by MonstrousOgre** [hyprwm/Hyprland#1705]
That title was probably confusing, but this is what I mean. I just made the switch from the wrapper script, and have this in my config
```
env = HYPRSHOT_DIR,$HOME/Pictures
```
I expected the output of `echo $HYPRSHOT_DIR` to be `/home/ogre/Pictures`, but instead it's `$HOME/Pictures`.

I can still use the full path, but I'd rather avoid it.

**Comment by vaxerski** [comment]
safe to say a dupe of #1416
