### ISSUE TITLE
input-method-v2 popups are sometimes out of screen.

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#1706]
Steps to reproduce:

1. Open `foot` with `fcitx5` running.
2. Put `foot` into floating mode and drag it towards the button of screen until only the prompt remains on screen.
3. Try to input some text with IME.
4. Observe that the popup is out of screen.

sway with https://github.com/swaywm/sway/pull/7226 seems to place the popup above the prompt in this case, though they place the popup under the prompt by default.

**Comment by q234rty** [comment]
I should add that with https://gitlab.gnome.org/GNOME/fractal the popup is off the screen by default in the message input box when the window is the only one in its workspace, so this affects more than strange edges cases.

**Comment by vaxerski** [comment]
fixed with 7e5a3eb045be371f3f898e776a25d22d51ec956e

**Comment by q234rty** [comment]
The commit does fix when the prompt is at the very bottom.
But I can still make the popup go out of screen like this:
![无标题](https://user-images.githubusercontent.com/11485439/225076618-adfb02cb-dd84-4a9a-8ba1-5b88e493836d.png)
Unfortunately this is the case in fractal by default for me...
I guess the condition for the check could be relaxed somehow?

**Comment by vaxerski** [comment]
should be fixado in d63e8c8f45202f1189f78e6c5eaa7e23f7239712

**Comment by q234rty** [comment]
OK This does seem fixed.
