### ISSUE TITLE
Focus changes when dragging window quickly

### ISSUE THREAD

**Issue by yavko** [hyprwm/Hyprland#1711]
Quite self explanatory, when dragging a floating window quickly, the window will change focus to windows below for a split second.

https://user-images.githubusercontent.com/15178513/222989622-0bbbe5cf-6f5a-43d6-905b-92b94def9fca.mp4
> Also video seems to appear corrupt on firefox for me, but isn't, works in other browsers

**Comment by devil-may-c0de** [comment]
I've also experienced this in draggable parts of applications (ie; the plugins in ardour). This is annoying. I'm going to look into this.

**Comment by devil-may-c0de** [comment]
It seems my problem was unrelated. I will open an issue of my own, however I have fixed this issue. opening a pull request soon.

**Comment by vaxerski** [comment]
fixd d6b069458d990d372eaa9a35bb8726605b44a588
