### ISSUE TITLE
<master:mfact>: no such field

### ISSUE THREAD

**Issue by milkknife** [hyprwm/Hyprland#1714]
**Steps to reproduce:**
add `master:mfact = 0.55` to hyprland config

**Expected outcome:**
master split factor/ratio value should make the master slightly wider

**Noted outcome:**
`Error setting value <0.55> for field <master:mfact>: No such field.`

note: `0.55` is the default value, yet in master layout it is split perfectly down the middle. `...splitratio, +0.05` works as intended.

related: 
- https://wiki.hyprland.org/Configuring/Master-Layout/
- https://github.com/hyprwm/Hyprland/pull/1666/files

**Comment by vaxerski** [comment]
What version of Hyprland are you running?
