### ISSUE TITLE
Rotating the screen while an app is fullscreen doesn't redraw the fullscreened application

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#1717]
![image](https://user-images.githubusercontent.com/61051731/223073182-ffcd5c29-acb6-4830-be99-2b19ad24bdc9.png)
Rotating from vertical to horizontal while having a youtube video opened fullscreen
![image](https://user-images.githubusercontent.com/61051731/223073740-11833189-14de-49e1-b877-d48b31209e74.png)
Rotating from horizontal to vertical while having a terminal app fullscreen

The applications keep their last orientation's dimensions and don't adapt to the new one (they're 1920x1080 on a vertical 1080x1920, basically)

**Comment by vaxerski** [comment]
#1091
