### ISSUE TITLE
togglesplit in fullscreen

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#1718]
Using togglesplit with multiple windows on a workspace and one of them in fullscreen ends fullscreen but doesn't render any but the previous fullscreened window.
Either togglesplit should be disabled in fullscreen, or it should properly end the fullscreen state without leaving windows invisible.

**Comment by vaxerski** [comment]
> Either togglesplit should be disabled in fullscreen

probably this.

**Comment by vaxerski** [comment]
fixed in 71ef1bde7e45f94ceaab925ae065f32f91510890
