### ISSUE TITLE
nodim window rule

### ISSUE THREAD

**Issue by Leshuguita** [hyprwm/Hyprland#1724]
I believe a window rule to prevent dimming a certain window, even if it's unfocused, would be rather useful

**Comment by Zander-Labuschagne** [comment]
This would be very nice. I love the dimming but I would like to exclude CLion/IntelliJ so that the little window popups from the editor don't cause the IDE to dim out.

**Comment by vaxerski** [comment]
added in e76bd43f53197af2c64608ba6b0792326e79db07
