### ISSUE TITLE
Default split ratio for Dwindle layout

### ISSUE THREAD

**Issue by callmenoodles** [hyprwm/Hyprland#1725]
I'm coming from bspwm where you have the option to set `bspc config split_ratio 0.6` for example. I am aware of the `splitratio` dispatcher which is available and a script could be written. But it would make sense if the Dwindle layout would have the option to set the split ratio for all newly spawned Windows by default eventually.

**Comment by JustSimplyKyle** [comment]
http://wiki.hyprland.org/Configuring/Dwindle-Layout/#config
Split_width_multiplier

**Comment by vaxerski** [comment]
I don't think that's what he's after.
