### ISSUE TITLE
Crashed after resuming from lock screen (swaylock-effects)

### ISSUE THREAD

**Issue by nawfalmrouyan** [hyprwm/Hyprland#1726]
## Steps to reproduce

1. Start Hyprland session using GDM
2. Lock the screen when in Hyprland session
3. Resume from lock screen - SUCCESS
4. Lock the screen again
5. Resume from lock screen again
6. after verifying, the Hyprland session crashed and I'm back at GDM login screen

## Expected outcome

1. No crashes after resuming from screen lock

## Noted outcome

1. Hyprland crashed after resuming from screen lock

## The Hyprland log

- [hyprland.log](https://github.com/hyprwm/Hyprland/files/10905820/hyprland.log)

## Your config

- [hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/10905831/hyprland.conf.txt)

## (v0.22.0beta and up) The Hyprland Crash Report

- [hyprland-2023-03-07-13-25-05.log](https://github.com/hyprwm/Hyprland/files/10905835/hyprland-2023-03-07-13-25-05.log)

**Comment by justinesmithies** [comment]
I use swaylock-effects too except I start Hyprland from the tty and it works flawlessly so maybe it's a GDM / Hyprland issue ?

**Comment by vaxerski** [comment]
Try starting from the TTY. GDM is known to cause issues.

**Comment by nawfalmrouyan** [comment]
Tried starting from the TTY (my start script https://github.com/nawfalmrouyan/hyprland/blob/lazy/scripts/starth) but same result. It crashed after resuming from the first screen lock attempt.

Below is the crash report:

[hyprland-2023-03-07-19-14-41.log](https://github.com/hyprwm/Hyprland/files/10908754/hyprland-2023-03-07-19-14-41.log)

I think it is an issue with Nvidia driver. I'm using swayidle to dpms off after 1800 secs. After the screen is off, it stays off. Sometimes, I'm able to get into TTY using Ctrl+Alt+F* and kill Hyprland session and start again. Other times, I had to hard restart my laptop.

I think it started happening after libdisplay-info used as a dependency.

Will try to use the integrated intel gpu later.

**Comment by nawfalmrouyan** [comment]
Started using intel gpu, same result.

**Comment by vaxerski** [comment]
That is not a crash report.

**Comment by nawfalmrouyan** [comment]
Not sure if this is the correct way to compile Hyprland with debug on. But attached is the crash report.

I have a family emergency so might not be able to reply.

[hyprlandCrashReport26041.txt](https://github.com/hyprwm/Hyprland/files/10911722/hyprlandCrashReport26041.txt)

**Comment by HeadTriXz** [comment]
I use SDDM and swaylock-effects, got the same problem.

**Comment by vaxerski** [comment]
@nawfalmrouyan thanks, the debug coredump really helped.

[patch.txt](https://github.com/hyprwm/Hyprland/files/10919139/patch.txt)

this should fix the issue. Can someone testy?

**Comment by nawfalmrouyan** [comment]
The patch seems to fix the issue. Thanks! There is still a minor issue (different than this one) but I can't seem to reproduce it every time. It's random.
