### ISSUE TITLE
Crash after suspending/closing laptop lid

### ISSUE THREAD

**Issue by Duckonaut** [hyprwm/Hyprland#1728]
Potentially related to #1726, but no screenlock is involved.

### Issue
After suspending, either via closing the laptop lid or using `systemctl suspend`, the system correctly goes to sleep. After waking up, hyprland flashes the screen gray a couple times, then crashes.

### Steps
1. Run `Hyprland` from TTY
2. Open terminal, run `systemctl suspend`
3. Unsuspend, via just typing in random letters or opening the laptop lid
4. Boom, back to TTY

### Config
[hyprland.conf](https://github.com/hyprwm/Hyprland/files/10911028/hyprland.txt)

### Crash logs
Attaching the most recent report. Can easily reproduce if needed.
[hyprlandCrashReport4282.txt](https://github.com/hyprwm/Hyprland/files/10911041/hyprlandCrashReport4282.txt)

**Comment by vaxerski** [comment]
I'd kindly ask you to build in debug, reproduce, and pass the report from that.

**Comment by Duckonaut** [comment]
There you go, debug build crash report
[hyprlandCrashReport9606.txt](https://github.com/hyprwm/Hyprland/files/10923788/hyprlandCrashReport9606.txt)

**Comment by Duckonaut** [comment]
It's kind of a real pain for me so I tried debugging it, but only got hints of what's going on. On the newest commit, the crash report backtrace is different. Going from there, it seemed that the egl context used for rendering was not the current one? And it was failing on an internal wlr assert. Trying to add other checks only seemed to reveal some other broken stuff being caught by different asserts, like that the renderer attached to the monitor was invalid. Anyway, I was way out of my depth here and wlroots is completely new to me, but here's the New And Improved crash report from the last commit. Debug build of course.
[hyprlandCrashReport349045.txt](https://github.com/hyprwm/Hyprland/files/10937236/hyprlandCrashReport349045.txt)

**Comment by vaxerski** [comment]
I'll look into this tomorrow

**Comment by MathisP75** [comment]
Are you on nvidia and using `nvidia-open-dkms`?

**Comment by Duckonaut** [comment]
With that patch, the behavior is a bit different bu the end result seems to be the same crash.
With another monitor plugged in, instead of crashing right away, it shows a black screen (powered on) on eDP-1 (builtin) and the stock hyprland BG on HDMI output. When i move my mouse, it draws a (seemingly incomplete) frame to eDP-1, then crashes.

With the external display unplugged, it keeps the black screen (powered on though) and doesnt render anything forever. Can quit via my `exit` bind, but that's about it

crash report: 
[hyprlandCrashReport7415.txt](https://github.com/hyprwm/Hyprland/files/10943936/hyprlandCrashReport7415.txt)

**Comment by vaxerski** [comment]
some things have been pushed today, can I get an update on head?

**Comment by Duckonaut** [comment]
Sadly nothing new it seems, here's the crash log. Seems like debug builds don't log as well as they used to, this is debug output but has no line info
[hyprlandCrashReport71329.txt](https://github.com/hyprwm/Hyprland/files/10994747/hyprlandCrashReport71329.txt)

**Comment by hurutparittya** [comment]
Experiencing the same thing. It happens every time consistently.

[hyprlandCrashReport9430.txt](https://github.com/hyprwm/Hyprland/files/11169221/hyprlandCrashReport9430.txt)

**Comment by Duckonaut** [comment]
Can also confirm it still happening to me without any real changes since last time, my crash report still seems to indicate the same thing (different than hurutparittya's). I've also since confirmed this doesn't happen on sway, so this is def an issue on the hyprland level and not in wlroots/nvidia drivers

[hyprlandCrashReport400301.txt](https://github.com/hyprwm/Hyprland/files/11169398/hyprlandCrashReport400301.txt)

**Comment by hurutparittya** [comment]
Can confirm, sway also seems to be handling suspension well on my end.

**Comment by EvanLind** [comment]
Experiencing the same thin ...
[hyprlandCrashReport1513.txt](https://github.com/hyprwm/Hyprland/files/11408163/hyprlandCrashReport1513.txt)

**Comment by KrolixW** [comment]
Fixed it via [Preserving video memory after suspend](https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend)

**Comment by Duckonaut** [comment]
That works! Huge thanks. Now, from what i understand to have Hyprland work without that kernel module setting, it'd have to reallocate all the GPU memory on its own, so it *should* theoretically be fixable in the project. But since it's an nvidia specific fix, feel free to close the issue if you don't want to bother.

**Comment by gut11** [comment]
> Fixed it via [Preserving video memory after suspend](https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend)

It solved the problem for me too, looks like i had to include this option: 

> On some notebooks, to enable any NVIDIA settings tweaking you must include this option, otherwise it responds with "Setting applications clocks is not supported" etc.
> 
> /etc/modprobe.d/nvidia.conf
> 
> options nvidia NVreg_RegistryDwords="OverrideMaxPerf=0x1"

Without this option no other option was working so it was crashing.

**Comment by romanstingler** [comment]
@vaxerski can be closed

**Comment by Fasolovic** [comment]
> > Fixed it via [Preserving video memory after suspend](https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend)
> 
> It solved the problem for me too, looks like i had to include this option:
> 
> > On some notebooks, to enable any NVIDIA settings tweaking you must include this option, otherwise it responds with "Setting applications clocks is not supported" etc.
> > /etc/modprobe.d/nvidia.conf
> > options nvidia NVreg_RegistryDwords="OverrideMaxPerf=0x1"
> 
> Without this option no other option was working so it was crashing.

I tried this approach on Fedora 38, but it didn't work. After some research, I discovered that:


Hyprland is attempting to communicate with the NVIDIA driver after it has already entered suspend mode, so it cannot respond. Linux tries to freeze the task but fails because Hyprland is waiting for a response from the driver and cannot be frozen.


The solution is to manually suspend the Hyprland using the STOP signal before the NVIDIA driver goes into suspend mode. Then use the CONT signal upon resuming.

solution:

1. create `suspend-hyprland.sh`
```
#!/bin/bash

case "$1" in
    suspend)
        killall -STOP Hyprland
        ;;
    resume)
        killall -CONT Hyprland
        ;;
esac
```

2. create `hyprland-suspend.service` 
```
[Unit]
Description=Suspend hyprland
Before=systemd-suspend.service
Before=systemd-hibernate.service
Before=nvidia-suspend.service
Before=nvidia-hibernate.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/suspend-hyprland.sh suspend

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service

```
3. create `hyprland-resume.service`
```
[Unit]
Description=Resume hyprland
After=systemd-suspend.service
After=systemd-hibernate.service
After=nvidia-resume.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/suspend-hyprland.sh resume

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service
```

4. `sudo systemctl daemon-reload`
`sudo systemctl enable hyprland-suspend`
`sudo systemctl enable hyprland-resume`

**Comment by FrankelJb** [comment]
Sorry for the necrobump but I'm still experiencing this. I've checked my hyprland logs and there isn't even a crash like some of the other logs here.

I used the resume scripts and added a file at /etc/modprobe.d/nvidia-power-management.conf with
```
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp/tmp-nvidia
```

I've also tried with 
```
options nvidia NVreg_RegistryDwords="OverrideMaxPerf=0x1"
```

neither of these worked.

Any help would be greatly appreciated.

**Comment by FrankelJb** [comment]
Thanks @gaurav712 for mentioning the issue. I pulled the latest and built but I still seem to be encountering that same bug.

Latest crashlog if it might help

[hyprlandCrashReport28069.txt](https://github.com/hyprwm/Hyprland/files/12445484/hyprlandCrashReport28069.txt)

**Comment by gitosk** [comment]
I found a solution for Nix-OS. 

You can set the lid-switch behavior with like [this](https://wiki.nixos.org/wiki/Laptop) and then let hyprland decide what to do when the lid is closed as in [here](https://wiki.hypr.land/Configuring/Binds/#Switches).
