### ISSUE TITLE
Publish on Fedora Copr

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#173]
Basically like the AUR but for Fedora, Hyprland will have to have a build system for packaging to RPM tho

https://docs.fedoraproject.org/en-US/quick-docs/publish-rpm-on-copr/

**Comment by vaxerski** [comment]
please ask someone who uses fedora to make this for me, I don't use Fedora and don't want to get into the package mess. Developing this is enough.

**Comment by ThatOneCalculator** [comment]
Fedora users aren't real, they're all just figments of your imagination

**Comment by vaxerski** [comment]
oh no not the voices in my head again

**Comment by ThatOneCalculator** [comment]
Ok but actually for linking into github actions i think it needs ur secret or whatever

**Comment by asegarra** [comment]
Just came to say that COPR is the build system and it doesn't need any special access other than the repo to be public. It's more like Ubuntu's PPA than the AUR.

**Comment by NicTanghe** [comment]
https://copr.fedorainfracloud.org/coprs/kasion/Hyprland-git/

**Comment by tsloughter** [comment]
@NicTanghe thanks for this! Would you consider also publishing `devel` packages? I was hoping to find a pixman 0.42 package on a copr and came across this but would need `pixman-devel` in order to build Hyprland.

**Comment by nmateo** [comment]
https://copr.fedorainfracloud.org/coprs/carlwgeorge/hyprland/

Just came here to say that this copr package is working for me on f37, doesn't seem to have workspaces tho but everything else, so far so good
