### ISSUE TITLE
having trouble to build hyprland on a rasberrypi4

### ISSUE THREAD

**Issue by Costabo1** [hyprwm/Hyprland#1733]
Greeting,  I'm learning the nixos-ecosystem lately. Trying to build hyprwm+nixos on a pi4 with my flake.nix.

However, some C compiler warnings forced it stop building up. How do I fix the libitoff and wrloots packages errors?

Here is my issue: https://github.com/NixOS/nixpkgs/issues/219571

And my nix config files: https://github.com/Costabo1/Nixos/blob/f4d5beaded77bc245f8dba0eefcc6c5e34642e23/flake_bkup.nix

Any guidance to install hyprland + nixos  on a pi4?

**Comment by fufexan** [comment]
@Costabo1 Ideally you should report these issues upstream to libliftoff and wlroots. In the meantime I'll add the CFLAGS to make them compile for aarch64 in a PR, and ping you for testing.

**Comment by RedBlizard** [comment]
@vaxerski i had the same problem just running Endeavouros on my laptop and installing libliftoff and libdisplay-info solved the issue for my to thanks. by the way awesome work.
