### ISSUE TITLE
binds scoped to layouts

### ISSUE THREAD

**Issue by edrex** [hyprwm/Hyprland#1736]
eg

```
bind = $m, H, movefocus, l
bind = $m, L, movefocus, r
dwindle {
    bind = $m, K, movefocus, u
    bind = $m, J, movefocus, d
}
master {
    bind = $m, J, layoutmsg, cyclenext
    bind = $m, K, layoutmsg, cycleprev
}
```

Currently binds inside layout blocks are valid but they apply in all layouts (so the above results in a double bind on `$m [JK]`). For per-layout bindings it's necessary to `unbind`/`bind` in the layout switch dispatch. 

Enabling this functionality would add some complexity to the implementation, either storing mappings for each layout or re-evaluating the config file on layout switch. So maybe not worth it, unless somebody wants it enough to implement.

**Comment by edrex** [comment]
Another thought: the current submap implementation allows only one active map at a time.
If there were a variant of the submap feature that allowed multiple active submaps (with merged binds) these could be used to add layout-specific bindings. If you wanted to override a global bind in a submap you would `unbind` first. This might be more generally useful than the above.

**Comment by edrex** [comment]
this could be moved to discussion

**Comment by vaxerski** [comment]
just check the layout within a script every 5s and rebind if needed with `hyprctl keyword` calls?

**Comment by edrex** [comment]
I think independently toggleable submaps could enable a lot of interesting dynamic binding use cases. Keeping a mental note to self.

**Comment by lautarodragan** [comment]
Mega old thread, but, for what it's worth, this is what I'm doing:

In hyprland.conf:
```
exec-once = hyprlander rebind-on-ws-change
```

`hyprlander` being:
```
» which hyprlander | get path | first | let p
/home/taro/.local/bin/hyprlander

» $p
/home/taro/.local/bin/hyprlander

» readlink $p
/home/taro/git/taro/nushell-scripts/hyprlander.nu
```


```nushell
def socket [callback: closure] {
  let socket_path = ([$env.XDG_RUNTIME_DIR, "hypr", $env.HYPRLAND_INSTANCE_SIGNATURE, ".socket2.sock"] | path join)
  socat -U - $socket_path | lines | each { |events|
    $events | each { |event|
      let parts = ($event | split row ">>")
      if (not ($parts | is-empty)) {
        do $callback $parts
      }
    }
  }
}

# Optional: purely for debugging
def "main listen" [] {
  socket { |event|
    print ($event | str join "\t")
  }
}

# Optional: sends a notification whenever the WS changes. Useful for debugging in general, and, in my case, I don't like bars or anything that takes up screen space other than the actual programs I'm using.
def "main notify-workspace-change" [] {
  socket { |event|
    if $event.0 == "workspace" {
      notify-send -r 501 -a Hyprlander -t 4000 "Workspace" $event.1
    }
  }
  ()
}

# Where the magic happens. Obviously very fragile and tightly coupled.
def "main rebind-on-ws-change" [] {
  socket { |event|
    if $event.0 == "workspace" {
      print $event
      hyprctl activeworkspace -j | from json | get tiledLayout | let layout
      match $layout {
        "dwindle" => {
          hyprctl --batch "keyword unbind $mod1, Tab ; keyword bind $mod1,Tab,cyclenext"
        }
        "scrolling" => {
          hyprctl --batch "keyword unbind $mod1, Tab ; keyword bind $mod1,Tab,layoutmsg,focus r"
          # bug: won't allow switching focus between floating windows in scrolling layout. I haven't had time to figure out what I want to do about this.
        }
        _ => {
          # this print is useless when running from `exec`! only useful for debugging when manually running from a terminal.
          print $layout 
        }
      }
    }
  }
  ()
}
```

This is NuShell, but should be easily adaptable to Bash/Fish, or even JS/Rust. (You can probably copy-paste this into some IA and have it translated automagically with very minor or no bugs, if you're unfamiliar with X language, although I highly recommend NuShell; and, if you do use AI, I strongly suggest reading and understanding every line generated by it. It's pretty trivial code in any case).

Note: if you're not using NuShell, replace `hyprctl activeworkspace -j | from json | get tiledLayout | let layout` with someothing like `SOME_VAR=$(hyprctl activeworkspace -j | jq ".tiledLayout")`. Olther versions of NuShell will need `let layout = (hyprctl activeworkspace -j | from json | get tiledLayout)`

Here's the full repo, if you're interested: https://gitlab.com/taro.codes/nushell-scripts. It's pretty raw and designed for my persona purposes. It even has hard-coded stuff related to my own hardware. I hope I'm not leaking anything important in it. (also, if it's not ok to share a link to another work here, please let me know and I'll remove it!)

All in all, I must say Hyprland is amazing in so many ways. Being able to react to Hyprland events so easily is just beautiful. I have only been using the key re-binds for a few days, but I've used the WS notifier for months and it's been working flawlessly! (originally in bash, then migrated to nu — neither failed, ever).

Hyprland ❤️ ❤️ ❤️ ❤️ ❤️
