### ISSUE TITLE
Add text-input-v1 support 

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#1746]
support text-input-v1 can help to make fcitx5 work in electron apps on native wayland.

support in kde is here: https://invent.kde.org/plasma/kwin/-/merge_requests/3403

**Comment by vaxerski** [comment]
chromium patchset for TI3: https://chromium-review.googlesource.com/c/chromium/src/+/3220698

**Comment by vaxerski** [comment]
Do you have any other apps that use v1 other than chromium? For some weird reason chromium doesn't wanna send any events even though it binds properly. Maybe it also expects ime v1? tho that would be fucking weird.

**Comment by I-Want-ToBelieve** [comment]
Did you pass the parameters that chromium needs? --ozone-platform=wayland --enable-wayland-ime --gtk-version=4

**Comment by I-Want-ToBelieve** [comment]
I found something interesting. Fcitx5 running on hyprland can work in Microsoft’s edge browser.

**Comment by vaxerski** [comment]
--gtk-version=4 forces TI3 instead of TI1 that I am implementing.

**Comment by vaxerski** [comment]
oh. `--enable-wayland-ime` did it. Thanks.

**Comment by vaxerski** [comment]
#1778 btw

**Comment by dragove** [comment]
I've tested #1778 with this app: https://github.com/Rocket1184/electron-netease-cloud-music and got the same result as [q234rty](https://github.com/q234rty) tested. only electron 21 and above version works.
There is a bug that I can't delete my first charater in IME pre-edit region. And I also wonder why the pre-edit region has a yellow background.
btw, It also works on vscode if I use my system electron(22) to launch it. 

![swappy-20230314-221047](https://user-images.githubusercontent.com/24190403/225028138-2782215c-3467-41aa-a628-6657a6aca3ee.png)

I can't delete the last character `a`
![swappy-20230314-221107](https://user-images.githubusercontent.com/24190403/225028119-e8a96223-d14f-438b-ad10-ed06826fa196.png)

**Comment by vaxerski** [comment]
Removing first character fixed in f960f72785141639c2f68f05a27edbebeac2210f

regarding the yellow, idk. Should be `ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_NONE` which should indicate no styling.

**Comment by vaxerski** [comment]
I will close this as tiv1 is supported now, feel free to open issues for other bugs.
