### ISSUE TITLE
`movecurrentworkspacetomonitor` on monitor's last workspace causes invalid state

### ISSUE THREAD

**Issue by lbuttitta** [hyprwm/Hyprland#1747]
**Steps to reproduce**
1. Create workspaces on at least two monitors.
2. Move the last workspace on one of the monitors to the other monitor.

**Expected outcome**
A new (empty) workspace is created on the first monitor.

**Noted outcome**
The window move animation plays on the first monitor, and the workspace appears on the second monitor, but the windows aren't rendered. The output of `hyprctl workspaces` and the `wlr-workspaces` module of waybar both list no workspaces associated with the first monitor.
Also, the binds I've mapped to switching between workspaces by number don't work until I focus the first monitor (with my mouse) and create a new workspace there (by moving to it).

**Comment by vaxerski** [comment]
Can't repro.

Binds:
![image](https://user-images.githubusercontent.com/43317083/224350958-bbdf868b-76a7-47bb-b6a1-143f83e0e7d7.png)

**Comment by lbuttitta** [comment]
Strange. I could have sworn I just observed this behavior, but I can't reproduce it anymore either. I'll close this issue for now, I suppose.

**Comment by covert8** [comment]
I'm having this issue as well, but have the monitors by id.

```
bind = $mainMod SHIFT, 0x3c, movecurrentworkspacetomonitor, 0 #<
bind = $mainMod SHIFT, w, movecurrentworkspacetomonitor, 1
bind = $mainMod SHIFT, x, movecurrentworkspacetomonitor, 2
```
