### ISSUE TITLE
Grouped windows fullscreen render bug

### ISSUE THREAD

**Issue by Yopaman** [hyprwm/Hyprland#1749]
**Steps to reproduce** : 
- Add at least two windows in a grouped layout
- Set the window to fullscreen
- Switch to the next window in the grouped layout while being in fullscreen

**Expected outcome** : Normal fullscreen render

**Noted outcome** : The window disapears (we can see the wallpaper), when switching again, the first window is shown in its original size (before going fullscreen), and the other elements (ie the bar, other windows...) are invisible. When exiting fullscreen, everything go back normally.

https://user-images.githubusercontent.com/21319188/224183293-e0b8b331-45d4-4caf-a726-a1a5185a55e6.mp4

**Comment by vaxerski** [comment]
fixado in 253286669a115c4e63c3924eeec8391af2504c57
