### ISSUE TITLE
fullscreen & switching workspace &  waybar Looks abnormal.

### ISSUE THREAD

**Issue by lisuke** [hyprwm/Hyprland#1750]
In full-screen mode, waybar should not full out when switching workspace.

![image](https://user-images.githubusercontent.com/10797357/224235236-39888d3a-94c8-4fb8-9b96-08a0ee1c06e3.png)

**Comment by Estebiu** [comment]
Why not? It's useful when you're watching a film in fullscreen and want to know the time/battery level.

**Comment by vaxerski** [comment]
intentional design
