### ISSUE TITLE
Subtle laggy windows when dragging

### ISSUE THREAD

**Issue by HanoJing** [hyprwm/Hyprland#1753]
When dragging windows there is a subtle lag, maybe they aren't getting redrawn/updated fast enough.

- Steps to reproduce: Drag any window 
- Expected outcome: windows are moving smoothly like in v0.22.0beta
- Noted outcome: windows are moving choppily

From my experience, this issue appeared when udis86 was added to hyprland.
I run and ARM64 system, so udis86 might not like this.

Like in #1127 but just that the windows get centered to the cursor in like 0.25 seconds from what I'm seeing and guessing.

https://user-images.githubusercontent.com/123803351/224329375-e6f55aeb-f081-4ebf-bf52-f2ae674924c9.mp4

**Comment by MathisP75** [comment]
I am having this issue too, on x86

**Comment by HanoJing** [comment]
> I am having this issue too, on x86

Very interesting, am glad, that I'm not the only one.

**Comment by vaxerski** [comment]
`git bisect please`. There have been some changes to how this behaves because of #1127

**Comment by HanoJing** [comment]
I have identified the commit where something has changed about how laggy windows are when dragging: #fb45f8f
That is the commit where windows are less laggy, before that one, Windows were even laggier/glitchier and would only snap to the center of the cursor when the cursor is still, according to my tests.

**Comment by vaxerski** [comment]
I don't see any choppiness there - I see that they "lag" behind - that's because misc:move_manual_resizes (iirc thats the name) is on by default - meaning your drags are animated to be more fluid.

If that's the issue - it's expected behavior and can be disabled with that and another var you can find in the wiki and this can be closed.

**Comment by HanoJing** [comment]
> That's expected if your curve looks kinda like 1,0,1,1
> 
> drags are animated with your windowsMove settings.

But my curve is the default curve, so 0.05, 0.9, 0.1, 1.05.

**Comment by MathisP75** [comment]
Yes, that fixes it for me too!

**Comment by tchofy** [comment]
Seems like adding `animate_mouse_windowdragging=false` to `misc` is the intended way to prevent this behavior, [according to the wiki](http://wiki.hyprland.org/Configuring/Variables/#misc).

**Comment by MathisP75** [comment]
This is new I guess?

**Comment by HanoJing** [comment]
> Seems like adding `animate_mouse_windowdragging=false` to `misc` is the intended way to prevent this behavior, [according to the wiki](http://wiki.hyprland.org/Configuring/Variables/#misc).

Yes this fixed it for me completely, now the window moves non choppily and also stay centered to the mouse, thank you very much!
