### ISSUE TITLE
Add libcxx and meta llvm+clang build

### ISSUE THREAD

**Issue by meleehao** [hyprwm/Hyprland#1755]
Build For Musl Libc from llvm-clang . 
It is build failed that nor gcc and   libstdcxx hard-depends !

**Comment by vaxerski** [comment]
what?

**Comment by HanoJing** [comment]
From my experience, musl libc is crippled when it comes to building programs that do very beautiful graphical stuff.
For example, picom-jonaburg, failed to build on a musl system for me.

**Comment by vaxerski** [comment]
hyprland depends on execinfo which is a part of glibc, on other c libs it might require a separate dep.
