### ISSUE TITLE
game on unfocus workspace behavior

### ISSUE THREAD

**Issue by DiedByDisgust** [hyprwm/Hyprland#1758]
i normally use two monitors, so i use to put my game in one while keep discord or web, terminal, etc in another.

but recently i been using only one. so i keep my game in a workspace while iterate to other workspaces while loading screens are (of course) "loading". then i found that games doesn't progress the load process until i return to the workspace game is.

tested with WoW and MTGA. both runs under wine, lutris.

**Comment by vaxerski** [comment]
That's down to the game. Many games do that.

**Comment by DiedByDisgust** [comment]
Ok, don't want to blame the wm for this behavior. But help me here. It's probably related to a workspace going inactive. I really don't understand much about this, so I ask you to explain me or at least point me where to read about.

**Comment by vaxerski** [comment]
The app loses focus and the game pauses itself on lost focus. Most likely.

**Comment by DiedByDisgust** [comment]
> 

But isn't happen when a second monitor is in use, that's why i mention it. Literally a different workspace is been used on second monitor, so game isn't focused and it is in a different workspace on the first monitor , but behaves correctly, the "freeze" behavior is only if workspace with the game is in the back.

**Comment by vaxerski** [comment]
By design, in Wayland, we suspend rendering to surfaces that are not visible. If the game can't handle that, it may freeze.
