### ISSUE TITLE
Support for sway/i3 style modes

### ISSUE THREAD

**Issue by kevinclevenger** [hyprwm/Hyprland#1759]
In sway/i3 you can create a menu that partially overylays the bar with something like the below. The benefits are that you can create a modal submenu of sorts, and you can get a visual of the mode key mappings.

I looked through the docs and didn't see anything that could provide this, if I missed it please point me to the section or function.

sway example:
~~~
bindsym $mod+Shift+z mode "(l)ock, (e)xit, (f)reeze, (s)uspend, (h)ibernate, (r)eboot, (p)oweroff"

mode "(l)ock, (e)xit, (f)reeze, (s)uspend, (h)ibernate, (r)eboot, (p)oweroff" {
  bindsym l exec swaylock -l -F -i $wallpaper --scaling fill, mode "default"
  bindsym e exec swaymsg exit
  bindsym f exec doas zzz -s, mode "default"
  bindsym s exec doas zzz -z, mode "default"
  bindsym h exec doas zzz -Z, mode "default"
  bindsym r exec doas reboot
  bindsym p exec doas poweroff
  bindsym Return mode "default"
  bindsym Escape mode "default"
}
~~~

**Comment by vaxerski** [comment]
I don't understand. Menus are something that a client should draw, not the compositor though.

**Comment by zakk4223** [comment]
It isn't rendered by the compositor, it's part of the bar.
It's the equivalent of Hyprland 'submap' bindings. I think the event socket will emit events when the submap changes, right? Should be doable on any bar that  lets you make bar items out of shell scripts

**Comment by kevinclevenger** [comment]
It looks like submap is exactly what I need, it was right there in the doc and I missed it. Thank you and please close this one.

**Comment by kevinclevenger** [comment]
It looks like submap is exactly what I need, it was right there in the doc and I missed it. Thank you and please close this one.

**Comment by user451421541757324** [comment]
> It looks like submap is exactly what I need, it was right there in the doc and I missed it

@kevinclevenger If you can get it working, could you please share your config? I am very interested.

**Comment by kevinclevenger** [comment]
> > It looks like submap is exactly what I need, it was right there in the doc and I missed it
> 
> @kevinclevenger If you can get it working, could you please share your config? I am very interested.

Not sure 'bindl' is really needed after freeze, suspend, hibernate (versus 'bind') but this works for me. No overlay menu in the bar like sway/i3 but the functionality is there.

~~~
bind=SUPER+SHIFT,z,submap,menu

submap=menu
bind=,l,exec,swaylock -l -F -i $(cat ~/.wallpaper) --scaling fill
bindl=,l,submap,reset
bind=,f,exec,doas zzz -s
bindl=,f,submap,reset
bind=,s,exec,doas zzz -z
bindl=,s,submap,reset
bind=,h,exec,doas zzz -Z
bindl=,h,submap,reset
bind=,e,exit
bind=,r,exec,doas reboot
bind=,p,exec,doas poweroff
bind=,escape,submap,reset
bind=,return,submap,reset
submap=reset
~~~
