### ISSUE TITLE
Only one monitor resumes after dpms off with new wlroots

### ISSUE THREAD

**Issue by 2e0byo** [hyprwm/Hyprland#1760]
I have two monitors. When hyprland wakes up only one monitor resumes most of the time.  Which monitor resumes is random; both show correctly in `hyprctl monitors`.

Reproducing:

- set `mouse_move_enables_dpms` in `misc` of `hyprland.conf`.
- run `hyprctl dispatch dpms off`
- shake the mouse

This behaviour is new and was introduced by a34b74766193c21803e2bc6a51fa6c13d82eb39f.

**Comment by vaxerski** [comment]
can't repro. Might be better to report to wlroots if this was caused by a dep update

**Comment by HeadTriXz** [comment]
Can repro.

**Comment by 2e0byo** [comment]
I'll try to dig into this this weekend unless someone else has first and see if it's caused by something in wlroots, or logic changes brought in when refactoring for the update.  If wlroots has changed behaviour then this probably belongs upstream.  I don't know this codebase well enough to tell by inspection...

**Comment by arcolinuxz** [comment]
Same issue here on ArcoLinux - hyprland-dev-r2619.928de334-1

**Comment by vaxerski** [comment]
posted on the discord, I'll forward here.

test this patch plox.
[patch(15).txt](https://github.com/hyprwm/Hyprland/files/11142892/patch.15.txt)

**Comment by 2e0byo** [comment]
Will test this evening.  Sorry been too busy to fire up the debugger and figure this one out.

**Comment by 2e0byo** [comment]
Unfortunately the patch doesn't make a difference on this system.

**Comment by vaxerski** [comment]
may I get a log?

**Comment by 2e0byo** [comment]
here you go:  [hyprland.log](https://github.com/hyprwm/Hyprland/files/11157813/hyprland.log)

Hmm, we are hitting the code path in that patch, so this is clearly the right direction.

Incidentally how do you normally debug?  SSH in and run Hyprland in gdb, or live without a debugger?  Or just know the codebase like the back of your hand and have no need for debugging? :D

**Comment by 2e0byo** [comment]
Additionally, physically unplugging/replugging either monitor fixes things (although workspaces get moved around as expected when the 2nd monitor disappears).

**Comment by vaxerski** [comment]
can you launch hyprland with `HYPRLAND_LOG_WLR=1` and get the log again? (note: that envvar has to be input manually and can't be used via `env = `)

**Comment by 2e0byo** [comment]
oops, sorry, here: [hyprland2.log](https://github.com/hyprwm/Hyprland/files/11158817/hyprland2.log)

**Comment by 10leej** [comment]
> posted on the discord, I'll forward here.
> 
> test this patch plox. [patch(15).txt](https://github.com/hyprwm/Hyprland/files/11142892/patch.15.txt)

I seem to be unable to apply this patch, here's the emerge log which does include the compile errors
[build.log](https://github.com/hyprwm/Hyprland/files/11158906/build.log)

**Comment by 2e0byo** [comment]
> @2e0byo and you're saying that after dpms off, and then waking up by moving a mouse or whatever, one of the monitors does _not_ wake up?

yes.

> I can see you're exiting the compositor at the end - I suppose that one monitor is still blank at that stage, right?

yes.  It comes back on when I get to the console.

**Comment by 2e0byo** [comment]
Yep, that fixes it, thank you!  I guess that means this can be closed as it's a problem upstream.

**Comment by vaxerski** [comment]
fixed with 1a5d5bf6201bef1dbb9c1982745534761693a6ee (upstream fixed the issue)

**Comment by 2e0byo** [comment]
Confirmed fixed.
