### ISSUE TITLE
key_press_enables_dpms

### ISSUE THREAD

**Issue by HanoJing** [hyprwm/Hyprland#1761]
`mouse_move_enables_dpms`
but for key presses.

Enables DPMS when any key is pressed on the keyboard.

Thanks in advance!

**Comment by vaxerski** [comment]
done in 146d231ec5ea9059a64e34caeba06e790991e81a

**Comment by HanoJing** [comment]
It sadly doesn't work, at least for me.
Does it work for you?
`mouse_move_enables_dpms` works for me.

I use this script to turn off my monitors
and lock the session:

```
#!/bin/zsh

hyprctl dispatch dpms off;
swaylock -c 000000;
hyprctl dispatch dpms on;
```
