### ISSUE TITLE
Master/Stack `cycleprev` layoutmsg not respecting `addmaster`

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#1763]
When using the `addmaster` layoutmsg dispatcher, the natural window order is not preserved (using `swapprev` layoutmsg) in the following scenario:

Config:
```
master {
    new_is_master=false
}
```

Reproduce:
### Example 1
Create 3 windows labelled as follows:
| 1  | 2  |
|---|---|
|   | 3  |

Now select window 3 and add to master, resulting in:
| 1  | 2  |
|---|---|
|  3 |   |

Now, when using the `cyclenext`/`cycleprev` layoutmsg dispatchers, we should see cycling in 1 -> 3 -> 2 order. Hower we don't, we see 1 -> 2 -> 3.

### Example 2
This becomes more obvious in the example above when we add 2 to master instead of 3. We now have arrangement:
| 1  | 3 |
|---|---|
|  2 |   |

We should see  1 -> 2 -> 3. However, we see this breaking down into 2 separate cycles: 1 -> 2 and 2 -> 3, depending on whether we cycle previous or next.

**Comment by vaxerski** [comment]
oh my god the code I wrote for this was atrocious. Fixed in 17deeb07ad4ce1b34bfe22524f9b248c5c6e01e6. I wanna throw up
