### ISSUE TITLE
Build Failed for Hyprland

### ISSUE THREAD

**Issue by meleehao** [hyprwm/Hyprland#1764]
[387/387] Linking target src/Hyprland
FAILED: src/Hyprland 
g++  -o src/Hyprland src/Hyprland.p/Window.cpp.o src/Hyprland.p/debug_CrashReporter.cpp.o src/Hyprland.p/debug_Log.cpp.o src/Hyprland.p/debug_HyprNotificationOverlay.cpp.o src/Hyprland.p/debug_HyprDebugOverlay.cpp.o src/Hyprland.p/debug_HyprCtl.cpp.o src/Hyprland.p/hyprerror_HyprError.cpp.o src/Hyprland.p/protocols_ToplevelExport.cpp.o src/Hyprland.p/protocols_FractionalScale.cpp.o src/Hyprland.p/main.cpp.o src/Hyprland.p/helpers_Color.cpp.o src/Hyprland.p/helpers_Timer.cpp.o src/Hyprland.p/helpers_WLListener.cpp.o src/Hyprland.p/helpers_Workspace.cpp.o src/Hyprland.p/helpers_BezierCurve.cpp.o src/Hyprland.p/helpers_WLClasses.cpp.o src/Hyprland.p/helpers_MiscFunctions.cpp.o src/Hyprland.p/helpers_SubsurfaceTree.cpp.o src/Hyprland.p/helpers_AnimatedVariable.cpp.o src/Hyprland.p/helpers_Monitor.cpp.o src/Hyprland.p/helpers_Vector2D.cpp.o src/Hyprland.p/layout_DwindleLayout.cpp.o src/Hyprland.p/layout_MasterLayout.cpp.o src/Hyprland.p/layout_IHyprLayout.cpp.o src/Hyprland.p/config_ConfigManager.cpp.o src/Hyprland.p/render_Shader.cpp.o src/Hyprland.p/render_OpenGL.cpp.o src/Hyprland.p/render_Texture.cpp.o src/Hyprland.p/render_Framebuffer.cpp.o src/Hyprland.p/render_Renderer.cpp.o src/Hyprland.p/render_decorations_CHyprDropShadowDecoration.cpp.o src/Hyprland.p/render_decorations_IHyprWindowDecoration.cpp.o src/Hyprland.p/render_decorations_CHyprGroupBarDecoration.cpp.o src/Hyprland.p/managers_HookSystemManager.cpp.o src/Hyprland.p/managers_SessionLockManager.cpp.o src/Hyprland.p/managers_EventManager.cpp.o src/Hyprland.p/managers_ProtocolManager.cpp.o src/Hyprland.p/managers_AnimationManager.cpp.o src/Hyprland.p/managers_ThreadManager.cpp.o src/Hyprland.p/managers_LayoutManager.cpp.o src/Hyprland.p/managers_input_Touch.cpp.o src/Hyprland.p/managers_input_InputMethodRelay.cpp.o src/Hyprland.p/managers_input_Tablets.cpp.o src/Hyprland.p/managers_input_Swipe.cpp.o src/Hyprland.p/managers_input_IdleInhibitor.cpp.o src/Hyprland.p/managers_input_InputManager.cpp.o src/Hyprland.p/managers_XWaylandManager.cpp.o src/Hyprland.p/managers_KeybindManager.cpp.o src/Hyprland.p/Compositor.cpp.o src/Hyprland.p/plugins_HookSystem.cpp.o src/Hyprland.p/plugins_PluginAPI.cpp.o src/Hyprland.p/plugins_PluginSystem.cpp.o src/Hyprland.p/init_initHelpers.cpp.o src/Hyprland.p/wlrunstable_wlr_ext_workspace_v1.cpp.o src/Hyprland.p/events_Windows.cpp.o src/Hyprland.p/events_Monitors.cpp.o src/Hyprland.p/events_Popups.cpp.o src/Hyprland.p/events_Misc.cpp.o src/Hyprland.p/events_Devices.cpp.o src/Hyprland.p/events_Layers.cpp.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -fuse-ld=mold -Wl,-O2 -Wl,--as-needed -march=native -O3 -flto=64 -pipe -Wl,--start-group protocols/libserver_protos.a subprojects/wlroots/libwlroots.a subprojects/udis86/liblibudis86.a /usr/lib64/libwayland-server.so /usr/lib64/libwayland-client.so /usr/lib64/libdrm.so /usr/lib64/libxkbcommon.so /usr/lib64/libpixman-1.so -lm -lrt /usr/lib64/libEGL.so /usr/lib64/libgbm.so /usr/lib64/libGLESv2.so /usr/lib64/libvulkan.so /usr/lib64/libudev.so /usr/lib64/libseat.so /usr/lib64/libinput.so /usr/lib64/libcairo.so /usr/lib64/libOpenGL.so -Wl,--end-group -pthread
mold: error: undefined symbol: wlr_drm_lease_request_v1_grant
>>> referenced by <artificial>
>>>               /tmp/ccCy2cth.ltrans22.ltrans.o:(Events::listener_leaseRequest(wl_listener*, void*))
mold: error: undefined symbol: wlr_backend_is_drm
>>> referenced by <artificial>
>>>               /tmp/ccCy2cth.ltrans5.ltrans.o:(CMonitor::onConnect(bool))
mold: error: undefined symbol: wlr_drm_lease_request_v1_reject
>>> referenced by <artificial>
>>>               /tmp/ccCy2cth.ltrans22.ltrans.o:(Events::listener_leaseRequest(wl_listener*, void*))
mold: error: undefined symbol: wlr_drm_lease_v1_manager_create
>>> referenced by <artificial>
>>>               /tmp/ccCy2cth.ltrans19.ltrans.o:(CCompositor::initServer())
mold: error: undefined symbol: wlr_drm_lease_v1_manager_offer_output
>>> referenced by <artificial>
>>>               /tmp/ccCy2cth.ltrans5.ltrans.o:(CMonitor::onConnect(bool))
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.****

**Comment by vaxerski** [comment]
The CI does not fail and as such this is an issue on your end. Looks like a mismatched wlr ver.
