### ISSUE TITLE
opaque doesn't work for window background

### ISSUE THREAD

**Issue by Aleksanaa** [hyprwm/Hyprland#1765]
I was trying to make this bug https://github.com/hyprwm/Hyprland/issues/1152 not so obvious. When firefox resize in sway, the blank space is filled by a pure color background. Meanwhile in hyprland, it seems like a 100% transparent space with blur.

When I'm applying `windowrule = noblur, ^(firefox)$`, it works for this blank space and the blur is removed. However, if I use `opaque, ^(firefox)$`, it is still fully transparent, which does not make sense.

**Comment by vaxerski** [comment]
opaque references hyprland's opacity. Translucent pixels of a surface are unaffected.
