### ISSUE TITLE
Virtual Desktops

### ISSUE THREAD

**Issue by tylort69** [hyprwm/Hyprland#1767]
I would like virtual desktops to be added.
Each virtual desktop would be a parent to a set of workspaces.
I have 6 monitors so a considerable amount of workspaces are already used up, I would like to have an independent and separate “workspace 1” on both desktop 1,2 and …

Maybe default key binds for desktops could be mod+Ctrl+1-0 

edit>
or mod+Ctrl+pgup/dn

Moving windows between desktops could be mod+Ctrl+shift+1-0
And similar to using arrow keys for quick navigation and moving windows you could have pgup and pgdn round robin through the desktops 
With mod+Ctrl+shift+pgup/dn to quickly move windows 
</edit

If you’re worried it’d be too confusing or complicated for most users and would cause them to lose windows just disable it with a simple true false flag in the config by default

**Comment by vaxerski** [comment]
That's easily scriptable/pluginable and AFAIK there have been at least a dozen people who've done that and posted on github. Hyprsome is a similiar thing IIRC.

**Comment by tylort69** [comment]
I looked up [Hyprsome](https://rustrepo.com/repo/awesomelike-workspaces-for-hyprland)  and it’s not quite the functionality I’m looking for, it’s emulating awesome WM and using each monitor as a parent to a set of workspaces. There’s a reason I’m making a feature request and not a pull request and that’s because I’m a big dum dum with coding. But I do also think that it would be valuable to have this type of functionality natively implemented rather than relying on, possibly findable mods in add-ons that may or may not continue to be maintained throughout the life of the window manager

**Comment by vaxerski** [comment]
"I’m a big dumb dumb with coding" is _not_ a reason to expect a feature to be added.

I am not planning on adding this as a core feature - it's a method of managing workspaces Hyprland was not made for, and will not be.

It is easily scriptable, and Hyprsome is just an example of the fact that you can manage workspaces with scripts. IIRC someone already made it into a plugin if the relatively slower speed of scripts is an issue somehow.

The point of the scripting API and plugins is exactly this - obscure or lesser used features.

**Comment by tylort69** [comment]
Maybe I’m not just a dummy with coding but the only plugins I could find were the ones made by you in the official repo.

please don’t be offended but perhaps a donation of monetary value could be made to ease the burden of implementing such an “obscure” feature
