### ISSUE TITLE
Option to disable blur for transparent pixels

### ISSUE THREAD

**Issue by Naterr02** [hyprwm/Hyprland#1768]
If you're familiar with using `blurls=gtk-layer-shell` to achieve a blur effect with stuff like **eww**, then you might have run into this problem. Enabling the blur feature will also blur any pixels that have no content, which can be a bit of a pain.

Having an option to disable this behavior would be highly appreciated.

**Comment by tchofy** [comment]
Already being discussed in #528 and in [wayland-protocols/#43](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/43), probably won't see any progress on this until the merge on wayland-protocols's side.

**Comment by vaxerski** [comment]
as above. Dupe.
