### ISSUE TITLE
hyprland AUR pkg fails compiling with error "frame_number is deprecated"

### ISSUE THREAD

**Issue by o69mar** [hyprwm/Hyprland#1771]
I recently just reinstalled arch (i was originally running nixos) and i was ready to install hyprland v0.22.0beta, but the build failed with the error "frame_number is deprecated"

same with the hyprland-git AUR pkg, but it fails to link the cxx executable

**Comment by Techassi** [comment]
Can confirm. I get the same error.

**Comment by vaxerski** [comment]
The CI does not fail which means the issue is on your side. Besides, hyprland does not reference `frame_number` anywhere.

**Comment by o69mar** [comment]
>. Besides, hyprland does not reference `frame_number` anywhere.

i mean't when cmake was compiling it, not hyprland itself
