### ISSUE TITLE
Hyprland won't build

### ISSUE THREAD

**Issue by lyasm** [hyprwm/Hyprland#1772]
Steps to Reproduce:

1. git clone from github
2. cd into git directory and either  make install or do meson _build

Expected: Builds and works

fails to build

System: 
arch lts-kernel, 

complete install log: http://0x0.st/Higr.txt
with make -d http://0x0.st/Higc.txt

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/224584561-f6df4afb-a3e6-43b6-a528-4336500bd9d0.png)

> git clone from github

`--recursive` probably missing

At any rate, issue on your side.
