### ISSUE TITLE
Is it possible to bind a key to exec-or-focus (run-or-raise) a program?

### ISSUE THREAD

**Issue by klorax** [hyprwm/Hyprland#1773]
Is it possible to bind a key to exec-or-focus (run-or-raise) a program, i.e., start a program or focus it (switch workspace if necessary) if it is already running?

Similar to [Jumpapp](https://github.com/mkropat/jumpapp) or [Sway: Application startup via run-or-raise](https://holgerschurig.github.io/en/sway-run-or-raise/).

If this is not possible, then please consider this a feature request, thanks!

**Comment by vaxerski** [comment]
You can script it with a one-line command utilising `pidof` and `hyprctl dispatch`

**Comment by klorax** [comment]
I had the feeling there was a way, hadn't found `hyprctl` yet: awesome, thanks!
