### ISSUE TITLE
Kdeconnect remote input doesn't work

### ISSUE THREAD

**Issue by tralph3** [hyprwm/Hyprland#1775]
I'm trying to use kdeconnect's remote input feature, but it just does nothing. The device is correctly paired and connected. I can use the other features. I can use it to control multimedia, to share files, to run commands, it all works, remote input does not. I have tried to delete the kdeconnect data in my computer, I re-paired them again, same deal, remote input doesn't work.

My kdeconnect version is 22.12.3-1 (arch package)

My hyprland version is 0.22.0beta-1

I don't really know what more info I can provide to debug this. I use an AMD gpu with the open source drivers, in case that would be relevant.

**Comment by vaxerski** [comment]
does sway work?

**Comment by tralph3** [comment]
I don't know, I don't use sway. I have looked around and kdeconnect seems to work with Hyprland, so it must be something on my side. I'll check it out.sdsfsdfasdfasfsdasd fas fasd asd sdfasdfas dfs ad fasd

**Comment by tralph3** [comment]
No, it does not work with sway either. It does work on Qtile with X11.

**Comment by vaxerski** [comment]
> No, it does not work with sway either. It does work on Qtile with X11.

Well, not only a completely unrelated base, but also X11. This seems like a problem with KDEConnect then not supporting wayland / wlroots.

**Comment by cvanelteren** [comment]
@vaxerski For me KDEConnect runs under sway. Under hyprland I can pair with a device but cannot use it to send files or mouse input. Pinging works fine. I believe it has something to do with the gnome services not being called correctly under hyprland. Not sure how sway does this...

```kdeconnect.plugin.mousepad: Could not create the remote control session QDBusError("org.freedesktop.DBus.Error.UnknownMethod", "No such interface “org.freedesktop.portal.RemoteDesktop” on object at path /org/freedesktop/portal/desktop```

**Comment by Yaikava** [comment]
> @vaxerski For me KDEConnect runs under sway. Under hyprland I can pair with a device but cannot use it to send files or mouse input. Pinging works fine. I believe it has something to do with the gnome services not being called correctly under hyprland. Not sure how sway does this...
> 
> `kdeconnect.plugin.mousepad: Could not create the remote control session QDBusError("org.freedesktop.DBus.Error.UnknownMethod", "No such interface “org.freedesktop.portal.RemoteDesktop” on object at path /org/freedesktop/portal/desktop`

Getting the same thing with Hyprland on fedora.
Even though `xdg-desktop-portal-hyprland` seems to be running fine.

**Comment by ALizarazoTellez** [comment]
I get this error in the logs every time I try to use the remote input (for example when I tap on the phone screen, it should be noted that the application does not crash, it continues to work normally other than that):

```
kdeconnect.plugin.mousepad: Could not create the remote control session
QDBusError("org.freedesktop.DBus.Error.UnknownMethod", "No such interface
“org.freedesktop.portal.RemoteDesktop” on object at path /org/freedesktop/portal/desktop")
```

Maybe it's because Hyprland hasn't implemented that Desktop Portal interface?
That is what the message implies to me, I could be wrong.

I have `xdg-desktop-portal-hyprland` running successfully, since the screen sharing works without problems.


https://github.com/hyprwm/Hyprland/assets/65132831/b26581e5-db8c-4e43-bc0b-f854f523fe5d

**Comment by vaxerski** [comment]
xdpw doesn't implement RDP either.

**Comment by ALizarazoTellez** [comment]
Oh, I see, I just found this issue (emersion/xdg-desktop-portal-wlr#2) in the _XDPW_ repository.

Ironically it also seems that they were also motivated to implement it because of KDE Connect. I guess we will have to wait.

**Comment by vaxerski** [comment]
I personally am pissed by the governance and development methods of xdp and flatpak in general and will most likely _not_ implement the dbus interface myself. If anyone wants to make a mr feel free

**Comment by joelsleeba** [comment]
> I get this error in the logs every time I try to use the remote input (for example when I tap on the phone screen, it should be noted that the application does not crash, it continues to work normally other than that):
> 
> ```
> kdeconnect.plugin.mousepad: Could not create the remote control session
> QDBusError("org.freedesktop.DBus.Error.UnknownMethod", "No such interface
> “org.freedesktop.portal.RemoteDesktop” on object at path /org/freedesktop/portal/desktop")
> ```
> 
> Maybe it's because Hyprland hasn't implemented that Desktop Portal interface? That is what the message implies to me, I could be wrong.
> 
> I have `xdg-desktop-portal-hyprland` running successfully, since the screen sharing works without problems.
> kdeconnect-error-compressed.mp4

quick question! How are you getting a better GUI for KDE connect desktop app. Mine is just bare bones ugly inteface

**Comment by alba4k** [comment]
@joelsleeba [qt5ct](https://github.com/desktop-app/qt5ct)

**Comment by ALizarazoTellez** [comment]
I use qt5ct and qt6ct with Kvantum, specifically the Catppuccin theme in its Mocha flavor, this will change the look of all Qt applications, but, in the case of KdeConnect, some commands like kdeconnect-sms look a bit ugly, but at least the indicator which is the one I use most often, the theme applies to it quite well.

**Comment by killown** [comment]
same issue

**Comment by BrendanMesters** [comment]
@alan1996colo yeah, I have the same issue, to bad, cause it seems like such a nice feature to have (I don't really feel like switching back to x11 again)

**Comment by MROvaiz** [comment]
is there no way of running kdeconnect remote input in hyprland?

**Comment by alba4k** [comment]
@MROvaiz Not that I know of, sadly

**Comment by ACatWOEM** [comment]
one day... :(

**Comment by kito30** [comment]
one day..

**Comment by murakn** [comment]
one day........................

**Comment by Thunder-Blaze** [comment]
one day......

**Comment by lz37** [comment]
one day......

**Comment by cvanelteren** [comment]
look at `LocalSend`

**Comment by vaxerski** [comment]
spamming "one day" only annoys me and others and will get you banned from this repo for spam if you keep doing it

**Comment by murakn** [comment]
> spamming "one day" only annoys me and others and will get you banned from this repo for spam if you keep doing it

sorry brother

**Comment by rwb196884** [comment]
Doesn't work on ubuntu.

Has anybody actually ever witnessed this crap work?

**Comment by bbrmanole** [comment]
Isn't there a way to set an independent session for kde connect?

**Comment by AdyStudios** [comment]
Are there any intentions to make this work in the future? Should this be addressed from KDE-Connect's side?

**Comment by alba4k** [comment]
someone should open a discussion regarding this

**Comment by AdyStudios** [comment]
> someone should open a discussion regarding this

#12547

**Comment by smugman-dot** [comment]
one day..

**Comment by chaitanya02082000** [comment]
will it ever

**Comment by rsamrudh13** [comment]
Idts

**Comment by SamTheTechi** [comment]
one day ....

**Comment by y2w8** [comment]
one day  :<

**Comment by tralph3** [comment]
Stop spamming ffs.

**Comment by reubenbrown13** [comment]
check your linux distro for waylandqt5 or qt5-wayland and install it.  Then you can run 
`export QT_QPA_PLATFORM=wayland`

**Comment by alba4k** [comment]
@reubenbrown13 that's not related... at all
