### ISSUE TITLE
Returning to empty named workspace shows number

### ISSUE THREAD

**Issue by Douile** [hyprwm/Hyprland#1777]
## Information
I'm using hyprland-git (AUR)
```
Hyprland, built from branch main at commit 17deeb07ad4ce1b34bfe22524f9b248c5c6e01e6dirty (master: better cycle).
flags: (if any)
```

## Steps to reproduce
1. Enable back and forth
```
binds {
  workspace_back_and_forth = true
}
```
2. Add a named workspace
```
bind $mainMod, T, workspace, name:example
```
3. Switch to named workspace but don't open any windows there
4. Switch back to another workspace
5. Switch back to named workspace by pressing the bind for the current workspace

## Expected outcome
Hyprland returns to workspace example

## Observed outcome
Hyprland returned to unknown workspace (in my case -1337). If you open any windows here you lose them as you cannot return after moving to a different workspace: repeating the steps after opening a window on workspace -1337 I was taken to workspace -1338.

**Comment by vaxerski** [comment]
fixed in e749af7b60386f4ff414ef3e2e804523046e46a9
