### ISSUE TITLE
Link errors when building without xwayland

### ISSUE THREAD

**Issue by asdfjkluiop** [hyprwm/Hyprland#178]
Attempting to build Hyprland when wlroots does not have xwayland support enabled results in linker errors even when `-DNO_XWAYLAND=true` is set. I would expect that setting that flag completely ifdefs out the XWayland code but it doesn't. As it currently stands even if you try to disable XWayland support in hyprland you must have wlroots built with XWayland support and therefore you must have the xwayland dependencies installed even if you do not wish to use them.

**Comment by vaxerski** [comment]
NO_XWAYLAND only disables xwayland run-time. It does not ifdef it. True.
