### ISSUE TITLE
Display scaling larger screens

### ISSUE THREAD

**Issue by etherrorcode404** [hyprwm/Hyprland#1781]
```monitor=,preferred,auto,1```
this line seems to work just fine on smaller screens and very large screen like my desktop monitor but on medium sized screens (14 inch display) it scales everything too small. When changing the scale size e.g;
```monitor=,preferred,auto,1.2``` everything in gtk applications like brave, spotify becomes blurry however waybar, alacritty seems to adapt the change. Yes I increased font sizes manually, but things like browser toolbar, spotify wont change and besides using increased font sizes on the config file means it will look wierd on other displays like my monitor which doesnt have such issues. I have consulted the wiki and scaling seems the only option that hints a fix but it cause the blur issue i mentioned earlier. Any idea whats wrong?

**Comment by vaxerski** [comment]
Every XWayland app will be blurry because X11 does not support fractional scaling and XWayland doesn't support scaling at all. (IIRC) see https://wiki.hyprland.org/Configuring/XWayland/#hidpi-xwayland

If brave is blurry then you're using it in xwayland mode. Why? `chrome://flags`, search for ozone and select wayland.

**Comment by etherrorcode404** [comment]
what about spotify and others?

**Comment by etherrorcode404** [comment]
Is this how you daily drive on your laptop??

**Comment by etherrorcode404** [comment]
This is not a solution, since lot of other apps have the same issue. What about having a standard config? Isn't a pain to have to create multiple configs depending on what device your using?

**Comment by etherrorcode404** [comment]
Is the size of the display a factor? In that case I'll just buy a 13inch laptop

**Comment by etherrorcode404** [comment]
The instructions aren't intuitive, i installed the package ```xorg-xwayland-hdpi-xprop-git```  didn't change anything even after adding lines from the wiki

**Comment by etherrorcode404** [comment]
changed brave to Wayland, toolbar size is still the same unless scaling is modified from 1 to a decimal size. But the issue with that is the requirement of multiple configs

**Comment by Act0r1** [comment]
> changed brave to Wayland, toolbar size is still the same unless scaling is modified from 1 to a decimal size. But the issue with that is the requirement of multiple configs

you solved it ?
![image](https://github.com/hyprwm/Hyprland/assets/59477383/d77f1916-3f72-49a5-a30e-9886a7a8e21e)
Here also all things tiny, but in firefox everything fine

**Comment by etherbiswas** [comment]
https://wiki.hyprland.org/Configuring/XWayland/

This was resolved a long time back, read the wiki to get up to date information!

**Comment by etherbiswas** [comment]
> > changed brave to Wayland, toolbar size is still the same unless scaling is modified from 1 to a decimal size. But the issue with that is the requirement of multiple configs
> 
> you solved it ? ![image](https://private-user-images.githubusercontent.com/59477383/286656934-d77f1916-3f72-49a5-a30e-9886a7a8e21e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzIyMDEsIm5iZiI6MTcwMTc3MTkwMSwicGF0aCI6Ii81OTQ3NzM4My8yODY2NTY5MzQtZDc3ZjE5MTYtM2Y3Mi00OWE1LWEzMGUtOTg4NmE3YThlMjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEwMjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZTcwZGRjNzRkMDk4MzM1YjEwMGI0NDhiZGJkNzE1MzYyMjgxMzk2ODE4YmFjMzNhYTY2Y2IyNWU5YTJhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sO20JR0RRe_U7g_YjKx1kx0MaLYv_7rEGoQsF_rbQss) Here also all things tiny, but in firefox everything fine

In that case look into wiki instructions for multiple monitors and also the xwayland config I mentioned previously

**Comment by rafia9005** [comment]
can i change to 0.80?

**Comment by XBEAST1** [comment]
> Every XWayland app will be blurry because X11 does not support fractional scaling and XWayland doesn't support scaling at all. (IIRC) see https://wiki.hyprland.org/Configuring/XWayland/#hidpi-xwayland
> 
> If brave is blurry then you're using it in xwayland mode. Why? `chrome://flags`, search for ozone and select wayland.

dude i really needed that thank you a million times

**Comment by braveltd** [comment]
> Every XWayland app will be blurry because X11 does not support fractional scaling and XWayland doesn't support scaling at all. (IIRC) see https://wiki.hyprland.org/Configuring/XWayland/#hidpi-xwayland
> 
> If brave is blurry then you're using it in xwayland mode. Why? `chrome://flags`, search for ozone and select wayland.

OM THANK YOU MAN, YOU REALLY HELPED ME!!!

**Comment by KeronCyst** [comment]
Those links are busted. Are there any updated links?

**Comment by wabarTM** [comment]
@KeronCyst pls dont necropost

https://wiki.hypr.land/configuring/extra/xwayland/#hidpi-xwayland
