### ISSUE TITLE
Aspect ratio of floating windows that request it is not respected

### ISSUE THREAD

**Issue by nadomodan** [hyprwm/Hyprland#1788]
When resizing floating window of mpv or firefox picture in picture frame the window dimensions are both freely controlled by user resulting in black bars around the video. The intended or at least supported behavior should be to only resize one window dimension at a time according to user input and set the other to maintain the aspect ratio of video showing no black bars, this works correctly on some linux window managers (and MS Windows) that support it for applications that implement it like mpv and firefox

**Comment by nadomodan** [comment]
Found this with a quick search:
https://0x0.st/HiBi.mp4
Looks a bit buggy but it does preserve aspect ratio on resizing under sway

**Comment by vaxerski** [comment]
it's because wayland apps _can_ kind of resize themselves, but Hyprland does not honor that because a) it's hacky and b) it's buggy. Most likely mpv tries to resize itself when the user resizes it

**Comment by amilonop** [comment]
@vaxerski could there possibly be an option to allow windows certain windows to resize themselves, popup windows and launcher would be very useful if they could resize themselves, as right now it causes them to be stuck on their initial launch size on Hyprland.

**Comment by vaxerski** [comment]
Not really because the current protocol methodology is dicey from how I understand it.

**Comment by n3oney** [comment]
I agree, the ability to let apps resize themselves would be really useful. I'm trying to use the albert launcher right now, and it just gets buggy because it sets the window's max size correctly, but it stays at the old size.
So if I start with the window empty, it is a small height, and after typing a query it's all cut off:
![image](https://user-images.githubusercontent.com/30625554/227744042-5c0c9934-f110-4b42-86e4-0069b76bdc0d.png)

And if I start with a query and remove it, the whole window gets stretched.
![image](https://user-images.githubusercontent.com/30625554/227744068-214162d2-5e5e-4835-b922-c8370f641106.png)

Honestly not sure if this is an issue with albert or with Hyprland.

**Comment by jsw08** [comment]
> I agree, the ability to let apps resize themselves would be really useful. I'm trying to use the albert launcher right now, and it just gets buggy because it sets the window's max size correctly, but it stays at the old size. So if I start with the window empty, it is a small height, and after typing a query it's all cut off: ![image](https://user-images.githubusercontent.com/30625554/227744042-5c0c9934-f110-4b42-86e4-0069b76bdc0d.png)
> 
> And if I start with a query and remove it, the whole window gets stretched. ![image](https://user-images.githubusercontent.com/30625554/227744068-214162d2-5e5e-4835-b922-c8370f641106.png)
> 
> Honestly not sure if this is an issue with albert or with Hyprland.

This is probably an issue with both, since it works perfectly fine on cage. However how is it possible then that apps like wofi work perfectly fine on Hyprland.

**Comment by n3oney** [comment]
>
> This is probably an issue with both, since it works perfectly fine on cage. 

What's cage?

> However how is it possible then that apps like wofi work perfectly fine on Hyprland.

The main difference between wofi and albert is that albert is a window while wofi is a layer

**Comment by vaxerski** [comment]
Listen, I understand what you want, but in wayland, there is no "hey I want to be this size" event, but how compositors sniff it is by checking whether the toplevel's surface size is valid.

The logic here is extremely dicey and idiotic, but I can see why it came to this.

There are a multitude of reasons why I am opposed to supporting that, from the fact that it's really buggy even on sway (ref: mpv) to the fact that it's interfering with pretty much every other surface system I wrote.

Windows will not be allowed to resize themselves in the nearest future. In any case, they never should IMHO.

**Comment by ayles** [comment]
Is there any possibility to support such ratio-respecting resizing with windowrule? Kinda like "please, resize this window in two dimensions simultaneously while maintaining its original aspect ratio". Those black bars in picture-in-picture windows are really annoying.

**Comment by MightyPlaza** [comment]
there is a `keepaspectratio` window rule and you can pass an argument to the resize bind to keep the ratio as well for floating windows iirc

**Comment by ayles** [comment]
> there is a `keepaspectratio` window rule

Missed that one in docs, thanks!
