### ISSUE TITLE
AUR hyprland doesn't build

### ISSUE THREAD

**Issue by CEnjolras** [hyprwm/Hyprland#1789]
Currently unable to update hyprland getting the exact same error as [1652](https://github.com/hyprwm/Hyprland/issues/1652) which seems to have been fixed on hyprland-git but not hyprland

> I'm getting this when trying to update hyprland from the AUR
> 
> ```
> cmake --build ./build --config Release --target all -j8
> ninja: error: '/home/x/.cache/yay/hyprland/src/hyprland/subprojects/udis86/build/libudis86/liblibudis86.a', needed by >'Hyprland', missing and no known rule to make it
> ```

**Comment by vaxerski** [comment]
Fixed 2 minutes ago

**Comment by CEnjolras** [comment]
Flawlessly works now, big thanks @vaxerski for reactivity
