### ISSUE TITLE
Mouse pointer not working with recent release

### ISSUE THREAD

**Issue by sanjayjaras** [hyprwm/Hyprland#1790]
With release 0.23.0beta-1, the mouse pointer is disappearing once some window is opened. I am using Nvidia GPU.  I tried export WLR_NO_HARDWARE_CURSORS=1.

**Comment by vaxerski** [comment]
Nvidia is not supported. open a terminal and do `echo $WLR_NO_HARDWARE_CURSORS` and I am 99% sure it will report empty because you didn't export it correctly. Remember updates overwrite your .desktop file.

**Comment by sanjayjaras** [comment]
You are right, the update overwrote the hyprland.desktop to remove the wrapper script.

**Comment by vsvito420** [comment]
I still dont know what to do
