### ISSUE TITLE
[Nix] XWayland patches compiled while it's disabled?

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#1791]
Even though I'm not using XWayland in my Home-Manager config, HIDPI XWayland patches still gets compiled? 

To reproduce, you can try this config with this commit: fb45f8f2f9efd988f2f5cef5cf74d6cba19e6b0c (it's a old commit which complains about not being able to patch `include/xwayland/xwm.h` for demo purpose)
```nix
wayland.windowManager.hyprland = {
  enable = true;
  package = hyprland.packages.${pkgs.system}.default;

  xwayland = {
    enable = false;
    hidpi = false;
  };

  nvidiaPatches = true;
};
```

I'm not experienced enough with NixOS to know if it's normal to see this behavior.

Any clue @fufexan?

**Comment by fufexan** [comment]
It doesn't work because you've set the package option. If you do that, it will take precedence over the xwayland and nvidia options. You have to remove that line for it to work properly.

**Comment by GrabbenD** [comment]
Thanks for the fast reply @fufexan!

If I remove `package` option, Hyprland fails to compile with this error: https://pastebin.com/raw/BBUPNccj
```
include/wlr/xwayland/xwayland.h:15:10: fatal error: xcb/xcb_icccm.h: No such file or directory
```
Even though I'm using:
```
xwayland = {
  enable = false;
  hidpi = false;
};
```

**Comment by fufexan** [comment]
Okay, it seems I have botched the no xwalyand build back when I rewrote the meson patch. I've tested it with your options, it should build now since https://github.com/hyprwm/Hyprland/commit/595f2052c4ddd08e8e467ea355e574459555a0a0.

**Comment by fufexan** [comment]
I've broken it again for the normal package. Fixing...

**Comment by fufexan** [comment]
@GrabbenD can you verify and close if it's fixed?

**Comment by GrabbenD** [comment]
Thanks @fufexan!
Works as intended now
