### ISSUE TITLE
Can't screenshare screen in firefox with scaling

### ISSUE THREAD

**Issue by igorlfs** [hyprwm/Hyprland#1795]
Hello there,

Thanks for the program! I've been experiencing an issue with Firefox, though: I can't share my screen, Firefox crashes.
Steps to reproduce:

1. Launch a [Screen Sharing Test](https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing)
2. Try to share screen
3. Hit allow -> Crash

My setup is as follows:

```
firefox v111.0 
hyprland-git r2592.569ae86c-1 
xdg-desktop-portal-hyprland-git r258.2fa7e34-1
```

I can screen share other apps, e.g., OBS, works just fine. I can also use sway to share my screen with Firefox, which leads me to believe there's some bug with Hyprland interfacing with Firefox. If the steps aren't reproducible, I might have misconfigured something, will look into that.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/225479617-436ad01f-1eb8-4953-8030-2758c303aee7.png)

Issue on your side.

**Comment by igorlfs** [comment]
Hey!

I noticed that if I change the scale of my monitor, I can actually share the screen. Previously, I had it set to 'auto' but changed it to 1 and now it works. Do you still think this is not an issue?

**Comment by igorlfs** [comment]
Okay...

**Comment by vaxerski** [comment]
Hm. Tested on my laptop where I scale as well, and windows seem to work ok, but screen indeed is broken.

I will reopen this for now.

It's generally about "when I get arsed enough to stop using wlroots' screensharing impl"

**Comment by igorlfs** [comment]
Hey! Thanks! Anything I can do to help?

**Comment by vaxerski** [comment]
not really. Again, I just need to write my own screenshare impl for screen.

**Comment by vaxerski** [comment]
#1800
