### ISSUE TITLE
Watching live stream in chrome with xwayland doesn't inhibit idle

### ISSUE THREAD

**Issue by norris-young** [hyprwm/Hyprland#1799]
I used chrome with native wayland without idle issue before.
Recently I changed to use xwayland to use fcitx5 in chrome, and the issue comes:
swayidle locks my screen while watching lives.
I don't know if it is a bug or a bug of hyprland or chrome, just come here for some help.

**Comment by norris-young** [comment]
> xwayland probably doesn't support the idle protocol. You can use an `idleinhibit` window rule, please [read the wiki](https://wiki.hyprland.org/Configuring/Window-Rules/)

Thanks. I have read this window rule, but it seems that I cannot create a rule that only inhibit idle while video playing, isn't it?

**Comment by norris-young** [comment]
> besides, IMEs work in chrome wayland if you pass the `--gtk-version=4` flag.

Yes, I just used this flag before. However, here comes another bug:
The candidate box of fcitx5 doesn't show in chrome wayland with '--gtk-version=4' flag after recent updates. It's normal in other apps, so it might be a bug of chrome, I think.

**Comment by vaxerski** [comment]
> Thanks. I have read this window rule, but it seems that I cannot create a rule that only inhibit idle while video playing, isn't it?

You can't. How can hyprland parse the content of the website and guess when it should inhibit?

**Comment by norris-young** [comment]
> static window rules apply on app open. Make sure you restarted chrome after adding that rule.
> 
> Second possible issue is chrome having a different class on open. Check the log, and search for "rules", it should print a log of searching for rules with the class and title of the window.

It works now after system reboot. Thank you!
