### ISSUE TITLE
Previous workspace is incorrect when switching monitor with 'focusmonitor +1'

### ISSUE THREAD

**Issue by leg7** [hyprwm/Hyprland#1801]
Open workspace 4 on mon1
Open workspace 1 on mon2
hyprctl dispatch focusmonitor +1
hyprctl dispatch workspace previous

previous workspace is 3 instead of 1.

**Comment by vaxerski** [comment]
should be fixed with 606cb2832aff2c7305da1f880ce732f7eb464d04
