### ISSUE TITLE
Fullscreen window focusing is incomplete.

### ISSUE THREAD

**Issue by leg7** [hyprwm/Hyprland#1802]
When in fullscreen mode it's not possible to go backwards through the stack of windows, you can only go forwards.

`movefocus l` and `movefocus r` both go forwards in the window stack when they should go opposite directions.
Same thing for `movefocus u` and `movefocus d`.

`cyclenext prev` starts cycling in the opposite direction of `cyclenext` but after the 2nd call it will go back to the original window, so if we have windows 1-2-3 and we are on window 1 it will do this:

```
-> window 1
cyclenext prev -> window 3
cyclenext prev -> window 1 (should be 2)
cyclenext prev -> window 3 (should be 1)
cyclenext prev -> window 1 ...
```

**Comment by vaxerski** [comment]
movefocus improved in 6fec5bfbeb80a5b2231af2ac5710a8b9c8bbc08a

cant seem to repro the cyclenext thing tho

**Comment by romanstingler** [comment]
can you check if the issue is resolved for you

**Comment by leg7** [comment]
still bugged altough I'm using the nixos stable version right now and cannot verify on latest commit

**Comment by romanstingler** [comment]
@leg7 this should be resolved
