### ISSUE TITLE
switch:off for Lid Switch is triggered by external keyboard when docked.

### ISSUE THREAD

**Issue by leg7** [hyprwm/Hyprland#1803]
If I dock my laptop and close the lid any input on my external keyboard will trigger the switch:off event for lid switch.

Here's the output of `hyprctl devices`:
```
mice:
	Mouse at f7e547a0:
		synaptics-tm3276-022
			default speed: 0.000000
	Mouse at f7d7e7d0:
		tpps/2-ibm-trackpoint
			default speed: 0.000000
	Mouse at f914cc10:
		ydotoold-virtual-device-1
			default speed: 0.000000
	Mouse at f85eef90:
		wooting-wootingone-consumer-control-1
			default speed: 0.000000
	Mouse at f867d940:
		logitech-g305-1
			default speed: 0.000000


Keyboards:
	Keyboard at f7eef5f0:
		power-button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7f1f620:
		video-bus
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7efe150:
		video-bus-1
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7e9ba10:
		sleep-button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7f1f360:
		integrated-ir-camera:-integrate
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7ea98f0:
		integrated-camera:-integrated-c
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f8059e50:
		at-translated-set-2-keyboard
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f80cc870:
		thinkpad-extra-buttons
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f80cdd40:
		keyd-virtual-device
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f9117040:
		ydotoold-virtual-device
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f801f4a0:
		wooting-wootingone-consumer-control
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7df8f70:
		wooting-wootingone
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f7acaca0:
		wooting-wootingone-system-control
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at f9518cc0:
		logitech-g305
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: yes


Tablets:
	Tablet Pad at f7edc150 (belongs to 0 -> )


Touch:
	Touch Device at f7ed52a0:
		g2touch-multi-touch-by-g2tsp


Switches:
	Switch Device at f7de2650:
		Lid Switch

```

**Comment by vaxerski** [comment]
does it trigger only the `off` event or both `on` and `off`?

**Comment by romanstingler** [comment]
could that be related to that kernel bug?

**Comment by vaxerski** [comment]
honestly this doesnt look like a hyprland issue

**Comment by noamsto** [comment]
Hi, I know this issues is closed but I get a similar behavior.
My laptop is docked and connected with external keyboard, when I press any key after the lid is closed, hyprland think the switch turned off, I've examined libinput and I see it has the correct state, attached a snippet with the difference.
What i did is:
1. close the lid
2. open the lid
3. close the lid
4. press a key (up) on the external keyboard.
![image](https://github.com/user-attachments/assets/56bb6916-52c8-41e7-afec-64b01fe33616)

System info:
OS: Hyprland flake (upstream) on Nixos
PC: Thinpad p14s AMD G4
Keyboard: Logitech mx mini
Kernel: 6.10.6

**Comment by BlueHeaven1969** [comment]
I will add to this in case anyone finds this with the same issue.

I had this problem and it turned out it was the keyd service that caused the issue.

**Comment by SKCheongBrian** [comment]
> I will add to this in case anyone finds this with the same issue.
> 
> I had this problem and it turned out it was the keyd service that caused the issue.

Did you manage to find a fix to this by any chance? @BlueHeaven1969

**Comment by leg7** [comment]
> I will add to this in case anyone finds this with the same issue.
> 
> I had this problem and it turned out it was the keyd service that caused the issue.

I no longer use hyprland so I can't confirm if keyd was the issue, but I was definitely using keyd too.

**Comment by BlueHeaven1969** [comment]
> 
> I no longer use hyprland so I can't confirm if keyd was the issue, but I was definitely using keyd too.

I think the issue is if you make the libinput change to have keyd keyboards recognized as internal.  Then when using your external keyboard (using keyd) with the lid closed, the keystrokes seem to be coming from the internal keyboard so it wakes the laptop display.

I fixed it by just having keyd run on the laptop internal keyboard.  I only use it to remap a few keys on it.
