### ISSUE TITLE
bug: special workspaces and multi monitor scaling

### ISSUE THREAD

**Issue by ozwaldorf** [hyprwm/Hyprland#1804]
# What

When a window is bound to a special workspace and started on a lower resolution monitor, the scaling doesn't update when opening the workspace on other monitors.

# Steps

1. Assign an application to start in a special workspace via `hyprland.conf`
2. start the application on a lower resolution monitor
3. toggle the special workspace on a higher resolution monitor
4. You can see the window is upscaled from the lower resolution, instead of updating to the new monitors resolution

# Env

- `hyprland-nvidia-hidpi-git` from aur @ 0aeb61a95af38ad20dd4d0f8a4ec1d485d73352f
```
  $ cd ~/.cache/yay/hyprland-nvidia-hidpi-git/hyprland/
  $ cat packed-refs | grep "`cat HEAD | cut -d " " -f 2`"
    0aeb61a95af38ad20dd4d0f8a4ec1d485d73352f refs/heads/main
```

**Comment by izmyname** [comment]
Did the patch work?

**Comment by vaxerski** [comment]
god knows, will close as inactive as the patch will defo be outdated
