### ISSUE TITLE
Gestures question

### ISSUE THREAD

**Issue by droc12345** [hyprwm/Hyprland#1805]
I'm curious if gestures can or will be (in the future) enhanced to allow users to specify their own actions off of a particular swipe. I'm also interested in seeing more touch/track pad enhancements (I know there's an older pull request that has some features, but don't know how much work is needed to fit it in)

**Comment by vaxerski** [comment]
#1634 

Generally yes stuff is "planned" but I am not an AI and I can't implement everything in 15 minutes
