### ISSUE TITLE
Clang can't compile newest version

### ISSUE THREAD

**Issue by Arisa-Snowbell** [hyprwm/Hyprland#1808]
Hey, i am unable to compile it with clang but I really don't understand the errors, it looks like clang problem because it can't compile ranges and some iterators from the std lib or something, i have no idea

i found this issue on the llvm project
https://github.com/llvm/llvm-project/issues/52696

`FAILED: CMakeFiles/Hyprland.dir/src/Compositor.cpp.o`
```
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/iterator_concepts.h:999:13: error: no matchin
g function for call to '__begin'
        = decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

looks like clang problem to me so if you don't want to fix it on your side by not using these C++20 features I understand and you can close this issue

**clang --version**
```
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by vaxerski** [comment]
it's very much a clang bug. We officially support gcc only.
