### ISSUE TITLE
detached kb/mouse focus modes and pass bind behaviour

### ISSUE THREAD

**Issue by ghost** [hyprwm/Hyprland#1809]
* Steps to reproduce
1. enable `follow_mouse={2,3}`
2. enable a bind with the pass dispatcher ( in my example with `mouse:276` to `.*discord.*` )
3. focus the relevant window ( in my case discord ) 
4. move the mouse off the window
 * Expected outcome
 for the bind of the button to continue to be passed to the relevant window
 as it is when focus is on a different window or focus is on the relevant window and the cursor is above it
 * Noted outcome
 the bind is entirely ignored by the relevant window
 
I'm using the NixOS version of hyprland as explained in the wiki, sorry bout it :trollface:
```
Hyprland, built from branch  at commit 606cb2832aff2c7305da1f880ce732f7eb464d04 ().
flags: (if any)
debug
```

also not entirely sure if a bug, tho if this is intended.. why?

**Comment by vaxerski** [comment]
prolly bug
