### ISSUE TITLE
System tray not clickable on waybar

### ISSUE THREAD

**Issue by biscuitrescue** [hyprwm/Hyprland#181]
The system tray icons on waybar are not clickable on hyprland. They work on sway and river. all other modules are clickable though.

**Comment by frigaut** [comment]
https://github.com/vaxerski/Hyprland/wiki/FAQ#the-waybar-tray-context-menus-do-not-show

**Comment by biscuitrescue** [comment]
okay its clickable now, but the toolbar appears on the wrong part of the screen. 
![image](https://user-images.githubusercontent.com/67876678/173075976-e48ddc0c-cfb2-4f93-9fb3-4f327f7eb216.png)

**Comment by frigaut** [comment]
yes, that is a limitation. That's because hyprland yet does not support gtk-layer-shell.

**Comment by yavko** [comment]
> gtk-layer-shell shouldn't be something I have to support, as it's a wrapper for the layer-shell protocol, which is supported. It's just that AS USUAL gnome devs are doing something batshit stupid and it ends up not working as it should.

I'm pretty sure gtk-layer-shell isn't developed GNOME, considering they refuse to add it, also the repo isn't from them https://github.com/wmww/gtk-layer-shell. Anyways thanks for the great compositor!
