### ISSUE TITLE
When using `layerrule` with any rule except for `unset`, `hyprctl reload` closes/crashes Hyprland, when executed in a layer `launcher` for example (in my case fuzzel).

### ISSUE THREAD

**Issue by HanoJing** [hyprwm/Hyprland#1816]
Hyprland version: latest git (6e69716)

- Steps to reproduce: put `layerrule = <any rule except for unset>, <layer>` in `hyprland.conf`; execute `hyprctl reload`.
- Expected outcome: Hyprland does not close itself / crash
- Noted outcome: Hyprland closes itself / crashes.

[hyprland-conf.log](https://github.com/hyprwm/Hyprland/files/11008018/hyprland-conf.log)

[hyprland.log](https://github.com/hyprwm/Hyprland/files/11008042/hyprland.log)

[hyprlandCrashReport23898.txt](https://github.com/hyprwm/Hyprland/files/11008043/hyprlandCrashReport23898.txt)

**Comment by justinesmithies** [comment]
Strange as the above steps work perfectly on my setup and I'm using layerrule too on latest git ??

**Comment by HanoJing** [comment]
> Strange as the above steps work perfectly on my setup and I'm using layerrule too on latest git ??

Ah yes, I just figured it out.

Hyprland crashes, because I executed `hyprctl reload` in `fuzzel`. `Fuzzel` is a layer, it makes total sense that it crashes, since `hyprctl` is trying to refresh fuzzel.

**Comment by vaxerski** [comment]
explanation wrong, coredump unusable cuz you stripped symbols, but fixed in d544c30551a7e4c4b0a311535cd9c379f121e753

**Comment by HanoJing** [comment]
> explanation wrong, coredump unusable cuz you stripped symbols, but fixed in [d544c30](https://github.com/hyprwm/Hyprland/commit/d544c30551a7e4c4b0a311535cd9c379f121e753)

I didn't strip anything from the coredump, I uploaded it as is.

**Comment by vaxerski** [comment]
since you're using gentoo it's safe to assume someone who patched and packaged it for you did enable symbol stripping :)

**Comment by HanoJing** [comment]
> since you're using gentoo it's safe to assume someone who patched and packaged it for you did enable symbol stripping :)

This is also not the case, the Hyprland I use, is the git build.

**Comment by vaxerski** [comment]
No clue then, but I can see the symbols are stripped.

**Comment by HanoJing** [comment]
Also, 
I build using meson:

`meson _build; ninja -C _build; doas ninja -C _build install`

**Comment by vaxerski** [comment]
that might be it. @fufexan does meson add `-rdynamic` to `ld`?

**Comment by fufexan** [comment]
Done in https://github.com/hyprwm/Hyprland/commit/06244555915339967864292dd0b83cd9732516d8.
