### ISSUE TITLE
Input Method failing when changing from native chromium to foot

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#1818]
`hyprctl version`: `Hyprland, built from branch main at commit 6e6971606d9613f6b5aa1df9ecf68327d079c2ccdirty (windowrules: allow monitor by str).
flags: (if any)`
# Steps to reproduce
1. Have a footclient setup
2. Have chromium launched like this `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`
3. Type something in chromium.
4. Change focus to foot.
5. Find that input method has deactivated

# Temporary fixes
1. use xwayland chromium
2. launch a second foot window and then immediately closing and putting the focus back to original foot window 

A video demonstrating pressing `asdf` on chromium and foot, the expected outcome is to output `arst` instead(colemak).
And the log for the video.(https://0x0.st/H-fa.txt)
(video in question is still uploading, giv it a sec)

[test_aom.webm](https://user-images.githubusercontent.com/68589851/226109222-e4cfc499-7987-4fe2-9815-e8fdeb1a5131.webm)

**Comment by JustSimplyKyle** [comment]
From my rough LOG reading, it seems like the IME input got destroyed when leaving chromium, therefore causing it to malfunction when it's inside foot

**Comment by TTtrace** [comment]
I use alacritty/kitty with vscode (----enable-wayland-ime) , and ran into this bug too.

alacritty -> vscode -> alacritty : fcitx5 not working -> another wayland native window -> alacritty : fcitx5 working again

but firefox -> vscode -> firefox: fcitx5 still working.

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by izmyname** [comment]
Can't repro, using flatpak Chromium. All works

**Comment by vaxerski** [comment]
closing inactive
