### ISSUE TITLE
Ability to use conditional sources

### ISSUE THREAD

**Issue by Midnight1938** [hyprwm/Hyprland#1819]
Currently using monitors with a laptop, which does not work well when disconnected from the monitor.

Ive tried using the if condition shown in the `Uncommon tips & tricks` section.
But trying to use monitor = xyz fails

So does sorurce = xyz.conf with the monitor lines.

**Comment by vaxerski** [comment]
conditional sources do not make sense in the config.

Why not write a script that listens to the monitoradded/monitorremoved events like a normal human being?
