### ISSUE TITLE
[Discussion] PDA, embedded and small displays

### ISSUE THREAD

**Issue by sjehuda** [hyprwm/Hyprland#1827]
Is there support or a plan to support smaller display monitors?

Because Sway and dwm are well supported in postmarketOS (see [SXMO](https://sxmo.org/)), I guess Hyprland should also be usable as much as Sway and Dwm.

Potentially, Hyprland can be the best fitted demonstration UI for [postmarketOS](https://wiki.postmarketos.org/wiki/Hyprland) and other Linux systems on mobile devices.

**Comment by sjehuda** [comment]
https://wiki.postmarketos.org/wiki/Hyprland

**Comment by vaxerski** [comment]
What is _not_ supported here?

**Comment by sjehuda** [comment]
On Sun, 19 Mar 2023 06:16:31 -0700
Vaxry ***@***.***> wrote:

> What is _not_ supported here?
> 

I don't know. I assume it is supported.
Once I test Hyprland, I will know for certain.

At the moment, package Hyprland[1] can't be built due to an error with
a PGP signature of a required package[2]

[1]: https://aur.archlinux.org/packages/hyprland
[2]: https://aur.archlinux.org/packages/libdisplay-info

**Comment by vaxerski** [comment]
get libdisplay-info-git then lul

**Comment by vaxerski** [comment]
Furthermore, discussions should be posted in the discussions section, not as issues. Since this is just an "assumption", closing.

**Comment by sjehuda** [comment]
On Sun, 19 Mar 2023 09:42:22 -0700
Vaxry ***@***.***> wrote:

> get libdisplay-info-git then lul
> 

Thank you!

**Comment by sjehuda** [comment]
On Sun, 19 Mar 2023 12:38:54 -0700
Vaxry ***@***.***> wrote:

> Furthermore, discussions should be posted in the discussions section,
> not as issues. Since this is just an "assumption", closing.
> 

May you please start a discussion on proposed config for narrow
displays?

**Comment by vaxerski** [comment]
> proposed config for narrow displays

?

**Comment by sjehuda** [comment]
On Sun, 19 Mar 2023 13:41:17 -0700
Vaxry ***@***.***> wrote:

> > proposed config for narrow displays  
> 
> ?
> 

I want to have a discussion on making config file *specifically for PDA
and embedded devices*.

So, if you would, I'd appreciate reopening this under the tag of
discussion.

Meanwhile, I'll look into packaging Hyprland in APKBUILD format.
https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

While, in most cases, I think I prefer i3/Sway over Hyprland, I
strongly sense that Hyprland and Kitty fill a missing gap for
intermediate users who want to utilize a tiling compositor.

I might even switch from SXMO to Hyprland when I use mobile devices.
