### ISSUE TITLE
mouse should follow window focus when swapping

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#1830]
Currently when *cycling* through windows the mouse pointer location follows window focus and moves to the center of the newly focused window. 

However when two windows are *swapped* the cursor doesnt move to the new location. This doesn't seem like the most natural behaviour - now when the mouse is next moved it refocuses on the one it was swapped with.

I think it would make the most sense to have the mouse always follow window focus during these operations - unless I am missing something?

**Comment by vaxerski** [comment]
fixed in 7a514f41a34f01246eff9a21fc96fe5e89775f11
