### ISSUE TITLE
some windows are float some are tile

### ISSUE THREAD

**Issue by Dmutro4347** [hyprwm/Hyprland#1833]
So when i open kitty or spotify they are open in float mode the rules for windows are blank

**Comment by vaxerski** [comment]
windows that request float will be floated, can be overriden with the `tile` rule. Kitty should be tiled by default though, most likely you do have some windowrule for float

**Comment by Dmutro4347** [comment]
the rules for windows are 

> windows that request float will be floated, can be overriden with the `tile` rule. Kitty should be tiled by default though, most likely you do have some windowrule for float

The rules for windows are empty so it was even with the standard hyprland config

**Comment by vaxerski** [comment]
then force kitty to tile with a rule. Maybe your kitty config wonk.

**Comment by micielski** [comment]
@Dmutro4347 You may be missing `wayland` USE flag on Gentoo for kitty.

**Comment by MisterOryon** [comment]
I also encounter the same problem I have a floating window that does not want to become a tile while in my conf file I have added the following rules :
```
windowrule = unset, title:^(JetBrains Toolbox)$
windowrule = tile, title:^(JetBrains Toolbox)$
```
I think it’s a bug in Hyprland 😢.

**Comment by vaxerski** [comment]
if a window "refuses to tile" it means it sets its max size as something that is smaller than the tiled size, in which case Hyprland will refuse to tile it for obvious reasons.

**Comment by nativerv** [comment]
> if a window "refuses to tile" it means it sets its max size as something that is smaller than the tiled size, in which case Hyprland will refuse to tile it for obvious reasons.

why not pseudotile it instead or allow user to ignore size hints with float rule, as it is done by default in classic minimal window managers like dwm and xmonad?
the fact that some windows can't be tiled in a tiling window manager and stack in the floating mode in the center of the screen kind of defeats the point.
