### ISSUE TITLE
hyprctl dispatch pass how to use this api?

### ISSUE THREAD

**Issue by pact0** [hyprwm/Hyprland#1834]
How does one use the `hyprctl dispatch pass` functionality? Where I can pass keys which I want to forward and to which program? On wiki there is this example `bind = SUPER,F10,pass,^(com\.obsproject\.Studio)$` but how would one invoke passing SUPER+F10 from the CLI?

**Comment by vaxerski** [comment]
you do not dispatch passes. SUPER+F10 in `pass` means whenever you press super+f10 that super+f10 is sent to the desired application instead of the focused one.
