### ISSUE TITLE
Moving workspace input bind key - Laptop

### ISSUE THREAD

**Issue by zamk-paw** [hyprwm/Hyprland#1837]
Hello !

I have a problem with my keybind, i explain : 

when I try to change the page (with the right keys) the pages do not change, when I execute the command: hyprctl dispatch workspace 2, it works

I tried to change several times the key, I looked at the doc a lot of times but it doesn't work.

In fact I have the impression that Hyprland does not take the input from my keyboard, when I am on a terminal and I do my modkey + the key 1 of my keyboard, it marks me the result on my terminal, it does not change the workspace. I have tried with many different key combinations, but nothing works

here my config file : https://cloud.vphess.fr/s/raS5jqAcfExRLmY

Im using a Azerty keyboard so when i click on the ModKey + 1 it gives me = &, i tried to put that in the hyprland config file, didnt change anything, still dosen't work.

**Comment by zamk-paw** [comment]
if you want to read what i've done https://www.reddit.com/r/hyprland/comments/11wcyhw/need_help_workspace_single_screen/

**Comment by vaxerski** [comment]
use `wev` to find what your keys are outputting, it's most likely a weird layout. Press 1 and use whatever it spits out as the sym in the config.

**Comment by zamk-paw** [comment]
already tried, here's the result when i press 1
![image](https://user-images.githubusercontent.com/81826361/226342376-1be91691-c7ae-4be1-9331-bc2587d20619.png)

**Comment by vaxerski** [comment]
well then bind to SUPER,ampersand and not SUPER,1

**Comment by zamk-paw** [comment]
the thing is, i tried both, and none work
![image](https://user-images.githubusercontent.com/81826361/226342732-04bd2380-46a1-4293-88ce-8efeea96a6a2.png)

**Comment by vaxerski** [comment]
SUPER,ampersand  not SUPER,&

**Comment by zamk-paw** [comment]
holy shit it works, thanks man, i have to find all these characters now :
é, ", ', (, -, è, _,ç

**Comment by vaxerski** [comment]
just use wev

**Comment by zamk-paw** [comment]
holy shit u saved me, thanks man
