### ISSUE TITLE
Keycodes are overloaded by key names for single numbers

### ISSUE THREAD

**Issue by csdvrx** [hyprwm/Hyprland#1841]
I think you have a bug in bind: it recognize both the keycodes mentionned in wev (ex: 64 for Alt_L) and the keynames (Alt_L)

However, the single digit keycodes 1..9 are taken over by the number keys of the same name, this is visible if you want to specify a bind to the actual Escape keycode (9):

     bindr=,9,exec, foot

It gets executed instead executed when you press 9.

A solution would be either a toggle (to avoid having to change config files), or requiring the use of the full names for number keys, so "Nine" not 9 which should unambiguously mean the keycode.

     # Esc (keycode 9) opens a terminal
     bindr=,9,exec, foot
     # The number nine does whatever
     #bindr=,Nine,...

This will be mostly seen with a modifier as the number keys are often accessed directly, but some minimalist keyboard layouts omit the number keys so it could be a problem for them.

Even outside of this specific case, i's not always possible to just use the keynames: for examples, if using the kb_options you can have 2 different keycodes both sending the same keyname (ex: caps:ctrl_modifier: both the caps and lctrl key will send Control_L) which necessitates the use of keycodes in bindr mappings to disambiguate

**Comment by csdvrx** [comment]
Wonderful idea! It's even better, because it would clearly make the numbers stand out as a code!

I'd suggest adding a comment pointing to where the codes can be found, like how the keyboard options are found in /usr/share/X11/xkb/rules/base.lst

I'll be eagerly waiting for this fix: now that my caps key is both control and escape, I want to have the old escape key as a quaketerm :)

ty!

**Comment by vaxerski** [comment]
codes are found in `wev` and it's mentioned in the wiki.

**Comment by vaxerski** [comment]
done in 463690a27ac9c921d34dad7169a3d2c8cea5b46f
