### ISSUE TITLE
xwayland patch failures on nixOS

### ISSUE THREAD

**Issue by a-weeb-programmer** [hyprwm/Hyprland#1842]
## Bug:
So, I am trying to build hyprland from the nix flake, and it keeps failing to apply a wlroots-hdpi patch. 

## Output:
The output of `nix-log /nix/store/<hashes>-wlroots-hyprland-hidpi-nvidia-2023-03-20_1d64e12.drv` is:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/yh8n15yy91v3pa9h50q747vxg3c2rsgf-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/mvywm94qj49a6hznqwqiggpmc5bn48dw-wlroots-hidpi.patch
patching file include/xwayland/xwm.h
Hunk #2 succeeded at 97 (offset -2 lines).
patching file xwayland/xwm.c
Hunk #1 FAILED at 19.
Hunk #3 succeeded at 966 (offset -3 lines).
Hunk #4 succeeded at 998 (offset -3 lines).
Hunk #5 succeeded at 1016 (offset -3 lines).
Hunk #6 succeeded at 1134 (offset -3 lines).
Hunk #7 succeeded at 1775 (offset -3 lines).
Hunk #8 succeeded at 1793 (offset -3 lines).
Hunk #9 succeeded at 2138 (offset -3 lines).
1 out of 9 hunks FAILED -- saving rejects to file xwayland/xwm.c.rej
```

## Steps to reproduce:
1. Add hyprland as a flake input
2. Enable the program, add nvidia patch support, and leave all other defaults unchanged.
3. attempt to build

# How do I know it's a bug?
I initially thought i was a user error, but then I had a look at the latest nix status check in this repository (https://github.com/hyprwm/Hyprland/actions/runs/4473504984), which failed to build and had exactly the same output I did.

**Comment by fufexan** [comment]
I'm working on rebasing the patch. It seems to break a lot lately.

In the meantime, if you do not have HiDPI monitors, you can use the `hyprland-no-hidpi` package of this flake.

**Comment by a-weeb-programmer** [comment]
Thank you for your hard work, I know how painful fixing patches can be.

Also, if anyone reading this issue is also experiencing this problem, you can get nix to download an older commit where the patch wasn't broken by adding the commit hash `37ced6aca4ad8f18f8e205e3cdb6de9c8964d4b6` to your hyprland flake input as a workaround.

**Comment by jcdickinson** [comment]
> In the meantime, if you do not have HiDPI monitors, you can use the `hyprland-no-hidpi` package of this flake.

This can be done by something like this in your nixos (not hm) config:

```nix
{
	programs.hyprland = {
	  enable = true;
	  package = pkgs-unstable.hyprland-no-hidpi;
	};
}
```
