### ISSUE TITLE
aur/hyprland-git r2580.71ef1bde-3 issue

### ISSUE THREAD

**Issue by RedBlizard** [hyprwm/Hyprland#1850]
As soon as i install the the package aur/hyprland-git r2580.71ef1bde-3  xdg-desktop-portal-wlr-git is also being installed this cause a issue direct after reboot when i login to the hyprland session with a error message on the top of the monitor that i have to uninstall xdg-desktop-portal-hyprland-git or xdg-desktop-portal-wlr-git - timeshift also stops working correctly to fix this first i need to remove xdg-desktop-portal-wlr-git and reinstall the timeshift-bin package then reboot again , and then it is fixed.
I'm running EndeavourOS and i use yay instead of paru.

Maybe there is something wrong with my system that could also be the case but i do not know for sure.
Just wanted to let you guys know.

**Comment by RedBlizard** [comment]
Looks like the problem is on my system something is wrong i think a need to fully reinstall to make sure .

**Comment by RedBlizard** [comment]
Did a full re-install and did found out that xdg-desktop-portal-hyprland-git package was the issue you need to make choice between 5 providers but is this still needed ?

**Comment by RedBlizard** [comment]
solved

**Comment by vaxerski** [comment]
> Did a full re-install and did found out that xdg-desktop-portal-hyprland-git package was the issue you need to make choice between 5 providers but is this still needed ?

![image](https://user-images.githubusercontent.com/43317083/226901968-dd04f1ff-cef0-4db1-adb2-5d4c854bc1b9.png)

https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/#installing
