### ISSUE TITLE
Restore workspaces to output on re-enable

### ISSUE THREAD

**Issue by edrex** [hyprwm/Hyprland#1852]
I frequently plug/unplug my laptop from external displays. Each time I reconnect, I have to restore workspaces to the reconnected output manually.

t would be nice if hyprland remembered which workspaces were on an output on output disconnect, and restored them to that output on reconnect.

Implementation in sway: https://github.com/swaywm/sway/pull/2115

**Comment by CryoMyst** [comment]
This is a major issue for me as my main monitor is an OLED I frequently turn off. Workaround currently is to move everything to another workspace and back again. This is annoying to have to do many times a day.

**Comment by vaxerski** [comment]
fixed in fd3e6a3bfde6d44a62df4834ccae5b24a1f36469

**Comment by dominicrico** [comment]
@flajann2 I'm a bit late to the party, but maybe you want to give my extension a try which tries to do that.

https://github.com/dominicrico/hyprsession
