### ISSUE TITLE
Monitors connected through a Thunderbolt dock are only activated the first time they’re connected

### ISSUE THREAD

**Issue by moritzruth** [hyprwm/Hyprland#1855]
I have three monitors connected to a Thunderbolt dock.
When I connect the dock to my laptop while Hyprland is running _or_ have them connected while booting, they are working as expected.
But if I unplug the Thunderbolt cable, wait for a few seconds, and plug it in again, the monitors don’t receive any signal, even though they show up in the output of `hyprctl monitors`.

- The internal laptop screen is not affected and keeps its name `eDP-1`.
- I noticed that their names (e.g. `DP-1`) aren’t reused but are incremented by 3 (`DP-1` → `DP-4`).
- Surprisingly, restarting Hyprland didn’t help. Only after a full reboot they worked again.
- I also tested this in Gnome (40?) where I didn’t have this problem.

**Comment by vaxerski** [comment]
does sway work?

Looks like a wlroots issue if anything, possibly a driver bug. IIRC thunderbolt in general in linux is ass.

**Comment by moritzruth** [comment]
I switched to `hyprland-git` because of something else and the issue seems to be gone now.
