### ISSUE TITLE
[Question] TTY inaccessible from Hyprland?

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#1856]
# Issue
I'm able to switch between different `TTY(num)` sessions when I'm in `TTY0` with `WIN+ALT+F(num)`, e.g: `TTY(1,2,3,x,..)`.

However, as soon as I enter Hyprland this is no longer possible. I'm guessing this is because `mainMod` key is set to WIN button (SUPER).

# Why
This is troublesome since if Hyprland hard-locks/freezes, key bindings stop working like CTRL+M (exit) and you're stuck in a black screen. This can happen when you receive a notification in Brave browser without a notification daemon or sometimes if you try to launch Hyprland with 10bit colors with a Nvidia card.

# Question
How can you access different TTY sessions when inside Hyprland? E.g could it be possible with key binds?

**Comment by vaxerski** [comment]
the key shortcut to change ttys was never `win+alt+f(num)`, no clue what you are on about, it's `ctrl+alt+f(num)`.

Furthermore, if hyprland freezes and keybinds stop working, how do you expect tty switching to work? It can't.
