### ISSUE TITLE
Are graphic tablets inside the scope of the project?

### ISSUE THREAD

**Issue by kushagra-xo** [hyprwm/Hyprland#1857]
So basically i use graphic tablets by companies like wacom to take notes. Is the ability to configure them and/or fix issues related to them inside the scope of this project?

**Comment by kushagra-xo** [comment]
https://wiki.hyprland.org/FAQ/#my-tablet-no-worky
um saw this now. should i close the issue?

**Comment by vaxerski** [comment]
yes
