### ISSUE TITLE
Per-device input settings being reset when keyboard is reconnected

### ISSUE THREAD

**Issue by deivi98** [hyprwm/Hyprland#1858]
Hi there,

**Steps to reproduce**:
1. Set up per device input settings in config for a given device of choice e.g `kb_options = altwin:swap_alt_win,grp:win_space_toggle`
2. Start your Hyprland session, see how it works well
3. Disconnect your device and connect it again

**Expected outcome**: per input settings remain working as expected for device
**Noted outcome**: Although settings are shown correctly under the device when running `hyprctl devices`, they are not working.

**Please note**:
1. While device remains connected in the first place, there is no issue at all.
2. Input settings set at a global level **do work** regardless the device is disconnected or not (I believe because they are set for all input devices in session generally instead of specifically)
3. Why would I need to disconnect and reconnect my device? I don't, but I am using bluetooth keyboard and it suspends after some time. When reconnecting, settings no longer have effect.
4. Could I just set input settings options globally and forget about it? Probably, but I consider it to be a bad solution as other people might have other needs.

**My request**:
- If you do a quick search, you will see this is a common issue / problem in most WMs. There are multiple workarounds, such as using udev rules to detect devices and resetting input settings. As Hyprland already does this in the first place, I am wondering it might be possible to listen events for devices being connected, and just applying input settings to them again as it is configured in the config. I am not expert so I am unsure if it is possible / how hard it is. Another approach to do this would be implement [switches](https://wiki.hyprland.org/Configuring/Binds/#switches) when a device is connected so that users can handle it on their own as well

**Comment by deivi98** [comment]
:(

**Comment by deivi98** [comment]
pong

**Comment by izmyname** [comment]
Pong, I guess. If fixed - close, otherwise mark as stale.

**Comment by izmyname** [comment]
Still a thing?
