### ISSUE TITLE
[Nix] hyprctl version missing

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#1860]
When using Hyprland with Home Manger, the version information is missing in this command:
```
$ hyprctl version
Hyprland, built from branch  at commit dirty ().
flags: (if any)
debug
```

Seems like there was a fix for this a while ago, not sure if it's just for flakes though @fufexan? https://github.com/hyprwm/Hyprland/commit/5184b542b1f505c90f9ef4715ae949ac45b2b7ef

**Comment by fufexan** [comment]
Yes, it's for flakes only. Or the Nixpkgs package, which reports the version 0.23.0 instead.

**Comment by GrabbenD** [comment]
I suppose it's not possible to fix this with regular Nix syntax in that case @fufexan?

**Comment by fufexan** [comment]
> I suppose it's not possible to fix this with regular Nix syntax in that case @fufexan?

Not sure what you mean by "regular Nix syntax".

**Comment by GrabbenD** [comment]
> > I suppose it's not possible to fix this with regular Nix syntax in that case @fufexan?
> 
> Not sure what you mean by "regular Nix syntax".

I believe some call it the original Nix. In other words when you add the Hyprland channel directly to .nix config?

**Comment by fufexan** [comment]
Do you mean [this](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/#from-the-flake-on-nix-stable)? It doesn't work like this, but maybe you can patch it using `src.rev`.

**Comment by romanstingler** [comment]
@GrabbenD could you resolve this ???
