### ISSUE TITLE
Better messages on plugin load fail

### ISSUE THREAD

**Issue by jacekpoz** [hyprwm/Hyprland#1866]
Not gonna make a PR cause don't really know how you'd want to handle this, but currently the only thing you get if a plugin fails to load is a `error in loading plugin` which happens when `loadPlugin` returns a `nullptr`, there's 4 places where that can happen. I know you can see the whole thing in the log but would be more convenient to see the actual error when you run the command (I think).

**Comment by vaxerski** [comment]
that was fixed iirc
