### ISSUE TITLE
Running in nested mode overwrites systemd environment variables

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#1868]
When running Hyprland nested for dev/debug it sets systemd  env variables DISPLAY and WAYLAND_DISPLAY to the nested values, which means any future systemd launched programs have the wrong environment and likely won't work.

Maybe just don't do the systemctl import-environment if running nested? Or allow it to be disabled in the config, since you shouldn't really be running nested without a separate config anyways

**Comment by vaxerski** [comment]
Woops, missed it. There are two places and one was missing the check. Thanks. a5a0434fffcd1b691506f694e5e9f9091b859a85
