### ISSUE TITLE
Continuous GLES2 Error Message

### ISSUE THREAD

**Issue by Nokogiri** [hyprwm/Hyprland#1870]
Since a few days Hyprland constantly produces the same error message.

`Mär 24 08:48:56 mowteng Hyprland[285479]: 00:05:37.900 [ERROR] [GLES2] GL_INVALID_OPERATION in glUniform1(uniform "proj"@0 is matrix)`

I didn't notice anything besides my growing systemd journal, which produces roughly 300~500MB per day since the message first appeared.

**Comment by Nokogiri** [comment]
Ok not entirely a Hyprland bgu but a Hyprland + swww bug because sway + swww works fine.
I forget about the wallpaper daemon so killed it and tried swaybg which don't produce this error message.

**Comment by vaxerski** [comment]
how to repro?

**Comment by vaxerski** [comment]
should be fixed in c418007c686abc978ef4119976c2231a105a5568

check plox

**Comment by Nokogiri** [comment]
@vaxerski works as expected, thanks for the quick fix.
