### ISSUE TITLE
fractional-scale-v1-protocol is missing at compil time from xwayland-compositor

### ISSUE THREAD

**Issue by jerome-diver** [hyprwm/Hyprland#1872]
# Operator System
Pop!_OS-22.04

# compil hard time after install dependencies party
compil time show dependencies installed, but maybe version of wayland-compositor is not enough... i don't know. There is a missing wayland-server message, but it is installed already.

#Compil messages

## from `sudo make install':

> make clear
make[1] : on entre dans le répertoire « /home/dge/Hyprland »
rm -rf build
rm -f *.o *-protocol.h *-protocol.c
rm -f ./hyprctl/hyprctl
rm -rf ./subprojects/wlroots/build
make[1] : on quitte le répertoire « /home/dge/Hyprland »
make fixwlr
make[1] : on entre dans le répertoire « /home/dge/Hyprland »
sed -i -E 's/(soversion = 12)([^032]|$)/soversion = 12032/g' subprojects/wlroots/meson.build
rm -rf ./subprojects/wlroots/build
make[1] : on quitte le répertoire « /home/dge/Hyprland »
cd ./subprojects/wlroots && meson setup build/ --buildtype=release && ninja -C build/ && cp ./build/libwlroots.so.12032 /usr/local/lib/ || echo "Could not install libwlroots to /usr/local/lib/libwlroots.so.12032"
The Meson build system
Version: 0.61.2
Source dir: /home/dge/Hyprland/subprojects/wlroots
Build dir: /home/dge/Hyprland/subprojects/wlroots/build
Build type: native build
Project name: wlroots
Project version: 0.17.0-dev
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wundef: YES
Compiler for C supports arguments -Wlogical-op: YES
Compiler for C supports arguments -Wmissing-include-dirs: YES
Compiler for C supports arguments -Wold-style-definition: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Winit-self: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
Compiler for C supports arguments -Wendif-labels: YES
Compiler for C supports arguments -Wstrict-aliasing=2: YES
Compiler for C supports arguments -Woverflow: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Walloca: YES
Compiler for C supports arguments -Wno-missing-braces: YES
Compiler for C supports arguments -Wno-missing-field-initializers: YES
Compiler for C supports arguments -Wno-unused-parameter: YES
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-server

> meson.build:105:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.

> A full log can be found at /home/dge/Hyprland/subprojects/wlroots/build/meson-logs/meson-log.txt
Could not install libwlroots to /usr/local/lib/libwlroots.so.12032
cd subprojects/udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B./build -G Ninja && cmake --build ./build --config Release --target all -j12 && cd ../..
Not searching for unused variables given on the command line.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dge/Hyprland/subprojects/udis86/build
ninja: no work to do.
make protocols
make[1] : on entre dans le répertoire « /home/dge/Hyprland »
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.c
/usr/bin/wayland-scanner server-header \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o xdg-shell-protocol.o xdg-shell-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o wlr-layer-shell-unstable-v1-protocol.o wlr-layer-shell-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/wlr-screencopy-unstable-v1.xml wlr-screencopy-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/wlr-screencopy-unstable-v1.xml wlr-screencopy-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o wlr-screencopy-unstable-v1-protocol.o wlr-screencopy-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/idle.xml idle-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/idle.xml idle-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o idle-protocol.o idle-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/ext-workspace-unstable-v1.xml ext-workspace-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/ext-workspace-unstable-v1.xml ext-workspace-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o ext-workspace-unstable-v1-protocol.o ext-workspace-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/pointer-constraints-unstable-v1.xml pointer-constraints-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/pointer-constraints-unstable-v1.xml pointer-constraints-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o pointer-constraints-unstable-v1-protocol.o pointer-constraints-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/tablet-unstable-v2.xml tablet-unstable-v2-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/tablet-unstable-v2.xml tablet-unstable-v2-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o tablet-unstable-v2-protocol.o tablet-unstable-v2-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/wlr-output-power-management-unstable-v1.xml wlr-output-power-management-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/wlr-output-power-management-unstable-v1.xml wlr-output-power-management-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o wlr-output-power-management-unstable-v1-protocol.o wlr-output-power-management-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/unstable/linux-dmabuf/linux-dmabuf-unstable-v1.xml linux-dmabuf-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	//usr/share/wayland-protocols/unstable/linux-dmabuf/linux-dmabuf-unstable-v1.xml linux-dmabuf-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o linux-dmabuf-unstable-v1-protocol.o linux-dmabuf-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	subprojects/hyprland-protocols/protocols/hyprland-toplevel-export-v1.xml hyprland-toplevel-export-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	subprojects/hyprland-protocols/protocols/hyprland-toplevel-export-v1.xml hyprland-toplevel-export-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o hyprland-toplevel-export-v1-protocol.o hyprland-toplevel-export-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	protocols/wlr-foreign-toplevel-management-unstable-v1.xml wlr-foreign-toplevel-management-unstable-v1-protocol.c
/usr/bin/wayland-scanner server-header \
	protocols/wlr-foreign-toplevel-management-unstable-v1.xml wlr-foreign-toplevel-management-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -DXWAYLAND -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1        -c -o wlr-foreign-toplevel-management-unstable-v1-protocol.o wlr-foreign-toplevel-management-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/staging/fractional-scale/fractional-scale-v1.xml fractional-scale-v1-protocol.c
Could not open input file: No such file or directory
make[1]: *** [Makefile:129 : fractional-scale-v1-protocol.c] Erreur 1
make[1] : on quitte le répertoire « /home/dge/Hyprland »
make: *** [Makefile:180 : install] Erreur 2

## Try debug compil time

`make debug`

> cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -S . -B ./build -G Ninja
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gathering git info
-- Configuring Hyprland in Debug with CMake
-- Checking deps...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0")
-- Checking for modules 'wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;libdrm;egl;xkbcommon;libinput;pango;pangocairo'
--   Found wayland-server, version 1.20.0
--   Found wayland-client, version 1.20.0
--   Found wayland-cursor, version 1.20.0
--   Found wayland-protocols, version 1.25
--   Found cairo, version 1.16.0
--   Found libdrm, version 2.4.113
--   Found egl, version 1.5
--   Found xkbcommon, version 1.4.0
--   Found libinput, version 1.20.0
--   Found pango, version 1.50.6
--   Found pangocairo, version 1.50.6
-- Setting debug flags
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- XWAYLAND Enabled (NO_XWAYLAND not defined) checking deps...
-- Checking for module 'xcb'
--   Found xcb, version 1.14
-- SYSTEMD support is requested (NO_SYSTEMD not defined) checking deps...
-- Checking for module 'libsystemd'
--   Found libsystemd, version 249
-- Looking for systemd/sd-daemon.h
-- Looking for systemd/sd-daemon.h - found
-- Setting link libraries
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dge/Hyprland/build
cmake --build ./build --config Debug --target all -j12
[0/2] Re-checking globbed directories...
ninja: error: '../subprojects/wlroots/build/libwlroots.so.12032', needed by 'Hyprland', missing and no known rule to make it
make: *** [Makefile:158 : debug] Erreur 1

## error log about meson
`cat /home/dge/Hyprland/subprojects/wlroots/build/meson-logs/meson-log.txt`

> [bat error]: '/home/dge/Hyprland/subprojects/wlroots/build/meson-logs/meson-log.txt': No such file or directory (os error 2)

## What is wayland serverwaiting for something more ?

`apt list | grep wayland-server`

> libwayland-server0/jammy-security,jammy-updates,now 1.20.0-1ubuntu0.1 amd64  [installé, automatique]
libwayland-server0/jammy-security,jammy-updates,now 1.20.0-1ubuntu0.1 i386  [installé, automatique]

**Comment by jerome-diver** [comment]
ok, i check an other one method to compil... that one gave me a bit more information around about my wayland-server:

## `meson _build`

> The Meson build system
Version: 0.61.2
Source dir: /home/dge/Hyprland
Build dir: /home/dge/Hyprland/_build
Build type: native build
Project name: Hyprland
Project version: 0.23.0
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -std=c++23: YES
meson.build:16: WARNING: Consider using the built-in option for language standard version instead of using "-std=c++23".

> Executing subproject wlroots

> wlroots| Project name: wlroots
wlroots| Project version: 0.17.0-dev
wlroots| C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
wlroots| C linker for the host machine: cc ld.bfd 2.38
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: /usr/bin/pkg-config (1.8.0)
wlroots| Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
wlroots| Found CMake: /usr/bin/cmake (3.22.1)
wlroots| Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency wayland-server

subprojects/wlroots/meson.build:105:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.

So the idea is to try to upgrader wayland-server up to top edge 1.21 version without to break Pop!_OS. Maybe to create a kind of docker image or something, but a bit werd to run the main DE with a WM as xmonad i would like to run with. Do you have a plan around to rich the Hyprland destination to be installed and running ready to test ?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/227579909-b20d2dac-6f57-46bf-aeb9-dc35e80f7066.png)

popos is not supported
