### ISSUE TITLE
Warning instead of root check

### ISSUE THREAD

**Issue by root2185** [hyprwm/Hyprland#1873]
```
 Hyprland 
Hyprland shall not be run as the root user. If you really want to, use the --i-am-really-stupid flag.

```
And then it states "I hope you know what you are doing".

**Comment by vaxerski** [comment]
good. Intended

**Comment by root2185** [comment]
I know that.
I think that it should have instead a warning.
It also could have a better flag.
Is that possible?

**Comment by vaxerski** [comment]
> I think that it should have instead a warning.

No. It's one of the most terrible ideas I've ever seen and as such, no.

**Comment by vaxerski** [comment]
No.
