### ISSUE TITLE
NUMPAD keys do not operate globally with pass dispatcher

### ISSUE THREAD

**Issue by BrodieRobertson** [hyprwm/Hyprland#1875]
Version: hyprland-0.23.0beta-2

I have a binding in OBS to start and stop recording with NUMPAD 0, along with other bindings on the other NUMPAD keys

My pass bind for start and stop is setup as such:
bind = ,KP_0,pass,^(com\.obsproject\.Studio)$

Whilst focused on the OBS window the binding works as expected, but when focus is on another window it does not operate. The same behavior occurs regardless of which of the NUMPAD numbers I use.

Swapping the bind to another key such as F1 produces the expected behavior of a global hotkey.

**Comment by vaxerski** [comment]
isn't it `KP0`?

**Comment by BrodieRobertson** [comment]
wev reports it as KP_0 not KP0, KP_0 seems to be the only form that works, unsure why there's a discrepancy. But that isn't the issue I'm seeing, the key is binding to OBS just fine but will only perform the action when the window is in focus, if I changed the binding to F1 or anything other than a NUMPAD number it works globally.

**Comment by vaxerski** [comment]
Try binding the pass dispatcher by a keycode. Maybe hyprland can't pick it up for some reason. Blame xkb.

I should probably make some check to see if a keysym is valid or something, but xkb is a pain to work with tbh.

**Comment by BrodieRobertson** [comment]
I don't know if I'm missing something but keycode binding doesn't seem to work full stop, even just copying the example from the wiki of:

bind=SUPER,code:28,exec,alacritty

To have Super + T to launch the application doesn't do anything

**Comment by vaxerski** [comment]
look in the top left and you'll notice you're on the -git wiki but are running 0.23.0

version selector -> 0.23.0

for the issue: just drop the `code:`

**Comment by BrodieRobertson** [comment]
I see, that was my bad. This problem has become weirder, wev reports the keycode as 90, which doesn't work, but using the keycode of 82 I can see in that screenshot you posted gives me the same result as using KP_0 like before, where it only works whilst I'm focused on the window.

I'm coming to the conclusion that NUMPADs might be a nightmare

**Comment by vaxerski** [comment]
I dumped my keymap (`pl`) and got this:
![image](https://user-images.githubusercontent.com/43317083/227737239-dfc985b3-df16-4c61-9298-8816a790be3f.png)

you can run `watch -n 0.1 "cat /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log | grep "triggered" | tail -n 40"` and look whether you pressing `KP0` sends a new log saying "keybind triggered, calling dispatcher (...)"

If it does, then something might be wrong on OBS's side. Generally tbh a lot seems to be, when I tried it back in the day anything with mods would not be registered. Just OBS.

> wev reports the keycode as 90, which doesn't work, but using the keycode of 82

don't worry, it's cuz libinput codes are -8 from xkbcommon codes. Use whatever wev tells you.

**Comment by BrodieRobertson** [comment]
Using KP_0 or code 82 nothing shows up in the log, but I can start/stop recoding on OBS only when focused on the window

Using 90 the code that wev reports NUMPAD 0 being produces this:
`[LOG] Keybind triggered, calling dispatcher (0, , 0)`

But nothing occurs in the application itself.

**Comment by vaxerski** [comment]
which means that hyprland should be passing it onto OBS. Maybe OBS again doesn't like it for some reason.

Can you try passing numpad 0 to like a text editor, terminal or something and see if it types in it?

**Comment by BrodieRobertson** [comment]
It seems to be typing in my terminal just fine

**Comment by vaxerski** [comment]
welp means OBS is back at it with sucky keybinds

**Comment by BrodieRobertson** [comment]
I can work around it for and just use the F keys which do work as expected

**Comment by vaxerski** [comment]
I'll close this as it's just another obs issue
