### ISSUE TITLE
Wrong behavior for wofi

### ISSUE THREAD

**Issue by chenzaichun** [hyprwm/Hyprland#1876]
version: hyprland-git 41f7736c8521162cb3ea5f3c003e0643c1bcf616dirty
os: manjaro linux

There's no wofi client information (hyprctl clients) while wofi is opened and the active client information is the window class below wofi.

Any suggestions?

**Comment by vaxerski** [comment]
wofi is not a window, see `hyprctl layers`

**Comment by chenzaichun** [comment]
I use xremap to remap keyboard to emacs key bindings, it's failed as wofi is a layer (old version is a window). Is there any way to get the active layer?

**Comment by vaxerski** [comment]
don't use xremap cuz it's x?

**Comment by chenzaichun** [comment]
[xremap](https://github.com/k0kubun/xremap) could be used with wayland. I'd submitted a PR for hyprland supporting.

BTW, is there any plan to add functionality to get current active layer like activewindow?

**Comment by vaxerski** [comment]
no
