### ISSUE TITLE
Environment variables in bind exec parsed incorrectly

### ISSUE THREAD

**Issue by sant0s12** [hyprwm/Hyprland#1884]
### Steps to reproduce
1. Put `export TERMINAL=kitty` in `.zshenv`.
2. Add `bind = $mod, return, exec, $TERMINAL` to the hyprland config.

### Expected outcome
Kitty or the program set in $TERMINAL is launched.

### Noted outcome
The program is not launched and the following log is created:

> [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 linuxINAL

It seems like $TERM is resolved to "linux" instead of resolving the entire environment variable.

### Workaround
Using `${TERMINAL}` in the bind fixes the issue.

I don't know if this is a bug or not but I found this behavior a bit strange, so I hope that I can at least help anybody who might have come across this.

**Comment by vaxerski** [comment]
seems like Hyprland is not aware of the $TERMINAL env at launch, but is aware of $TERM, so it substitutes the latter.

**Comment by sant0s12** [comment]
@vaxerski I thought that was the case but I don't think so anymore because it is aware of other variables like $BROWSER and $EXPLORER but bot $TERMINAL (they are all set at the same time).

**Comment by vaxerski** [comment]
you sure you on -git? that got fixed as a part of #1813

**Comment by sant0s12** [comment]
Oops my bad sorry
