### ISSUE TITLE
Strange fullscreen toggling behaviour with mpv when switching video

### ISSUE THREAD

**Issue by dtop129** [hyprwm/Hyprland#1888]
When in my mpv playlist I switch from a video to another with different aspect ratio, the mpv window becomes fullscreen if it wasn't and goes back to windowed if it was fullscreen before switching videos.
Also, when the mpv window becomes fullscreen after the switch, the mpv internal fullscreen toggle stops working.

I could reproduce this issue opening mpv with any two videos with different aspect ratios.

This behaviour is absent in other Wayland compositors such as river.

**Comment by 11xx** [comment]
I have the same issue, it also occurs when rotating the video with something like `add video-rotate 90` (so changing the aspect ratio, right).

**Comment by suptimal** [comment]
i added this rule so mpv cant mess with fullscreen

~/.config/hypr/hyprland.conf

    windowrule=nofullscreenrequest,^(mpv)$

this fixed the issue for me, but disabled fullscreen toggle from within mpv 
to allow fullscreen toggle on keypress "f" within mpv i use


~/.config/mpv/input.conf

    f run "/bin/sh" "-c" "hyprctl dispatch fullscreen toggle"; cycle fullscreen

**Comment by 11xx** [comment]
> i added this rule so mpv cant mess with fullscreen
> 
> ~/.config/hypr/hyprland.conf
> 
> ```
> windowrule=nofullscreenrequest,^(mpv)$
> ```

Thanks, this helps.

I settled with:
```
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, F11, fullscreen, 0
```
for 'monocle' and ~the lesser used~ 'full fullscreen' respectively.

**Comment by MightyPlaza** [comment]
mpv issue, already fixed in latest release @vaxerski

**Comment by 1sixth** [comment]
I'm experiencing this issue again since ae46fbafe5ba2d707e3d2897de74bf5a1d7397c6.

**Comment by m-bartlett** [comment]
I am also experiencing this issue again after a recent update. I have been using the `nofullscreenrequest` windowrule successfully for several months.

**Comment by SherLock707** [comment]
Facing this issue since last week:

mpv 1:0.36.0-1
hyprland-git 0.34.0.r25.7e033e48-1

**Comment by Mahmoud-Alawady** [comment]
facing this issue today:

mpv 1:0.37.0-2
hyprland 0.37.1-1

**Comment by vaxerski** [comment]
mightyplaza literally gave you a solution 2 messages above. Please stop the spam...
