### ISSUE TITLE
add features to whitelist/blacklist applications from being blurred

### ISSUE THREAD

**Issue by nonetrix** [hyprwm/Hyprland#189]
For me personally I only want one application to have blur that being my terminal, it would be great if I could whitelist applications from being blurred.

This is one of my major complaints with picom that you can only blacklist applications, so it would be nice if this could be fixed for when I switch to Wayland when NVIDIA drivers are stable.

Here is how I would personally implement it in the config file.

```
BlurWhitelist = {
    "alacrity"
}

Blurblacklist = {
    "screenshotAppThatHappensToMakeATransparentWindowForSelection"
}
```

This would
- improve proformance in theory
- fix applications that are not designed for blur

**Comment by fufexan** [comment]
By default windows with opacity set to 1 won't be blurred anyway. So only windows that have transparency will be blurred. I don't see this as an issue as long as only your terminal has transparent background.

**Comment by tazimamatovzeka** [comment]
Ayzat

**Comment by tazimamatovzeka** [comment]
Hi, how are you? Let's cooperate

**Comment by vaxerski** [comment]
added noblur in 45a44f969048d232939c6931fe7ab15cf0e85b87

whitelist is stupid, we have a blacklist :P

**Comment by nonetrix** [comment]
> Hi, how are you? Let's cooperate

?

**Comment by nonetrix** [comment]
> added noblur in [45a44f9](https://github.com/hyprwm/Hyprland/commit/45a44f969048d232939c6931fe7ab15cf0e85b87)
> 
> whitelist is stupid, we have a blacklist :P

My main issue with a blacklist is that I have to edit my config to fix a application that makes a transparent window like Flameshot, in my option would be much more easier if it was just disabled for every application until I specify otherwise. 

Ideally like KDE applications(e.g. Konsole) the client window could decide if it wants to be blurred, but KDE is the only place I can see such a thing being done and not any other applications or compositors like Alacritty so that isn't practical unless people agree on a standard.

![456170c808d163c613beb8617a4e33f9105c0d49](https://user-images.githubusercontent.com/45698918/176802243-83061f3b-c14c-4189-b5dd-13c052646b81.jpeg)

**Comment by taylor85345** [comment]
If you really only want exactly one application to be blurred, windowrules do support regex matching so you could try something like this:

`windowrule=noblur,\b(?!alacritty\b)\w+`

This will apply the noblur rule to all classes except for `alacritty`. I'm sure there is a regex way to match more than one word and effectively create a whitelist, but [this](https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch05s04.html) was as far as I bothered to google on the topic.

Fair warning, hyprland crashed on my when I applied this rule to test, but it logged back in alright.

**Comment by nonetrix** [comment]
I will try this thanks

**Comment by renxzen** [comment]
This is also working to only blur Alacritty:

`windowrulev2 = noblur, class:^(?!Alacritty)$`

Rule from below was not working properly and it was producing the annoying blur behind floating windows:

> `windowrule=noblur,\b(?!alacritty\b)\w+`

![annoying](https://i.imgur.com/avtiB0X.png)

**Comment by Acumane** [comment]
Most robust:
`$blacklist = class:^((?!any|substring|here).)*$, title:^((?!or|here).)*$`

Since its exclusionary you can check against classes OR titles in the same rule
