### ISSUE TITLE
Hyprland crashing when launching games w/EAC

### ISSUE THREAD

**Issue by vars1ty** [hyprwm/Hyprland#1890]
- Steps to reproduce
  1. Launch Crossout (or any other game with EAC) via Bottles
  2. Wait for the Easy AntiCheat launch splash to finish loading
  3. Watch Hyprland crash as the splash-screen tries to fade out
- Expected outcome
  - The game should load after Easy AntiCheat is done.
  - This also happens at times with software such as Cheat Engine and just general-purpose applications, like Task Manager
- Noted outcome
  - The compositor crashes after ~2 seconds

[Crash Logs from `tmp` and `~/.hyprland`](https://gist.github.com/vars1ty/51218fec672e7d593c231e9041df6ba1)

**Comment by cp3p0n3** [comment]
I would like to add to this that Apex Legends also crashed hyprland when launched via steam after updating both hyprland and the hyprland xdg portal to latest git. However, VRChat for some reason does not crash even though it also uses EAC. 

Using gamescope mitigates the issue however it always introduces stutter every 10 seconds during gameplay so I tend to avoid using it.

Tested both games on KDE and it works fine with or without gamescope. Titanfall 2 uses EAPlay and still works on hyprland.

**Comment by vaxerski** [comment]
I need either a debug coredump or a reproducible example with something that isnt a gazilion GB game.

**Comment by vars1ty** [comment]
I'll try giving a debug coredump either later tonight or tomorrow, been busy hence the late response.
Crossout is ~9GB or something like that, fairly small if you want to try and reproduce it yourself.

**Comment by vaxerski** [comment]
I need a debug ASan trace to look further into it, as it's something that seems, to me, as something that should _never, ever_ happen

**Comment by CoolDevelopment** [comment]
[Debug Coredump](https://file.io/5h7QDPkpifzo)

**Comment by vaxerski** [comment]
that's not an asan trace, see [issue guidelines](https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md#obtaining-the-debug-hyprland-coredump)

**Comment by CoolDevelopment** [comment]
Thanks, I just tried to obtain the asan trace, but did not succeed. 
I am running the latest nixos debug flake, installed via nix profile. I have set ASAN_OPTIONS variable but somehow the log does not appear...
I am not about the problem here, if it is me doing something wrong or if it has something to do with nixos, which I recently switched to but don't completely undestand yet.
Anyway, it seems like I cannot provide one.

**Comment by vaxerski** [comment]
something is wrong here. You crash on an abort from a segv, which suggests ASan caught something, but your ASan log doesn't show any memory fault. Idek what you got from ASan, never seen that.

**Comment by vaxerski** [comment]
I am still waiting for an ASan trace, this is a blocker for 0.24.0 :P

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11173795/patch.txt)

in the meantime, yall should try this patch

**Comment by CoolDevelopment** [comment]
This patch fixed the startup.
