### ISSUE TITLE
Screen dim and flickery when overclocking monitor

### ISSUE THREAD

**Issue by TheLastTeapot** [hyprwm/Hyprland#1892]
My monitor is supposed to support 75hz, but 60hz is the default. If I set the refresh rate to 75hz, the screen becomes dim and flickers. It does run at 75hz though, tested using glxgears. I am using an nvidia geforce gt 730 without proprietary drivers, just using noveau, config is monitor=HDMI-A-1,1920x1080@75,auto,1. I have confirmed that my monitor supports 75hz in windows and xorg.

**Comment by vaxerski** [comment]
does it work on sway?

**Comment by vaxerski** [comment]
well it seems that your monitor does not support 75Hz under normal conditions then and just uses some odd hack to achieve that. Consider buying a normal monitor that doesn't use some odd driver hack to cheat on spec.

**Comment by TheLastTeapot** [comment]
Bruh

**Comment by vaxerski** [comment]
it literally has nothing to do with hyprland. dims and flickers are issues with the driver / kms / drm

**Comment by TheLastTeapot** [comment]
My annoyance is with the monitor
