### ISSUE TITLE
Dependencie update problem aur/xdg-desktop-portal-hyprland-git

### ISSUE THREAD

**Issue by RedBlizard** [hyprwm/Hyprland#1893]
Today came a update of this Dependencie or yesterday already. it gives issue again i did check with yay and with paru same problem.

~ ❯❯❯ upall
[sudo] password for redblizard:
:: Synchronizing package databases...
endeavouros is up to date
core is up to date
extra is up to date
community is up to date
multilib is up to date
:: Starting full system upgrade...
there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: 1 Packages to upgrade.
1 aur/xdg-desktop-portal-hyprland-git r261.e1f145d-1 -> r261.ge1f145d-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 1
there is nothing to do

I did also these steps but issue stays the same with paru and with yay.

Went to the AUR package page for xdg-desktop-portal-hyprland-git: https://aur.archlinux.org/packages/xdg-desktop-portal-hyprland-git/
Clicked on the "Download snapshot" button to download the source code.
Open a terminal and navigate to the directory where the source code was downloaded (usually your Downloads folder in my case projects/snapshot).
Run the command git clone https://aur.archlinux.org/xdg-desktop-portal-hyprland-git to clone the source code repository.
Change into the cloned directory with cd xdg-desktop-portal-hyprland-git.
Run makepkg -si to build and install the package.
This should build and install the updated version of the package, bypassing any issues with yay.

But the problem stays.

**Comment by vaxerski** [comment]
wrong bug tracker. This should go to xdg-desktop-portal-hyprland

**Comment by vaxerski** [comment]
generally seems like @ThatOneCalculator forgot to bump the pkgrel

**Comment by ThatOneCalculator** [comment]
I literally did tho... ill do it again...

**Comment by RedBlizard** [comment]
@vaxerski  @ThatOneCalculator 

I know did make a mistake with the bugtracker i'm sorry about that at that moment it was over here some where very early in the morning did not sleep at all but wanted to give you guys a heads-up about the issue with the Dependencie as soon possible.

By the way thank you both for the amazing work.
