### ISSUE TITLE
could you release a non-systemd version?

### ISSUE THREAD

**Issue by superiums** [hyprwm/Hyprland#1896]
i'm on void linux, i had some problems about make from source.

i've looked help from  void linux , seems they have some trouble to introduce hyprland to void repo. [https://github.com/void-linux/void-packages/issues/37544](https://github.com/void-linux/void-packages/issues/37544)

void use init instead of  systemd. could you release a non-systemd version?

**Comment by vaxerski** [comment]
build with `NO_SYSTEMD`

ref: https://wiki.hyprland.org/Getting-Started/Installation/#custom-build-flags
