### ISSUE TITLE
Hyprland either crashes after about a minute after login or works perfectly fine

### ISSUE THREAD

**Issue by YamatoHD** [hyprwm/Hyprland#1897]
Hyprland crashes about 2 out of 3 logins via SDDM-git within 1 minute after login
Otherwise it works perfectly fine, if it didnt crash in a minute, it will work
Hardware: HP Elitebook G7 ryzen5

I also use same config (only changed resolution), no issues
I am attaching most recent log after crash (taken in TTY) and config
[Hypr_crashlog1.log](https://github.com/hyprwm/Hyprland/files/11080120/Hypr_crashlog1.log)
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11080130/hyprland.conf.txt)

**Comment by vaxerski** [comment]
please post a crash report

**Comment by YamatoHD** [comment]
> please post a crash report

hello, i did, i copied it over to Hypr_crash.log

**Comment by YamatoHD** [comment]
> that's a log and not a crash report. Please read the issue guidelines: https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md

"Go to ~/.hyprland/ and you should find a file named hyprlandCrashReport[XXXX].txt"
there is no such folder is that tutorial outdated?

**Comment by vaxerski** [comment]
nope, it's not. If there is no crash reports, check `coredumpctl`. If there are no coredumps there either, hyprland is 100% not crashing.

**Comment by YamatoHD** [comment]
But it says that coredumpctl is for older than 0.22 versions, I use latest git ver.
If it's not crashing, than what is it doing? I'm being dropped to sddm

**Comment by vaxerski** [comment]
maybe somehow the crash report isnt caught? coredumpctl always catches crashes, it's for older because 0.22 and below didnt have crash reports.

> If it's not crashing, than what is it doing? I'm being dropped to sddm

It could exit. e.g. `hyprctl dispatch exit`

**Comment by taylorcoffelt** [comment]
Having a similar issue with GDM on Arch, NVidia 3080 Ti. However, my crash report is working. (Attached)

[hyprlandCrashReport2819.txt](https://github.com/hyprwm/Hyprland/files/11092186/hyprlandCrashReport2819.txt)

Was in a session for several hours this morning, crashes out randomly after logging in now.

**Comment by taylorcoffelt** [comment]
Crashed as I'm writing a response back to you 😆 
[hyprlandCrashReport2634.txt](https://github.com/hyprwm/Hyprland/files/11092351/hyprlandCrashReport2634.txt)

**Comment by vaxerski** [comment]
what about this one (different one, reset and apply, do not apply over the previous)

[patch.txt](https://github.com/hyprwm/Hyprland/files/11092404/patch.txt)

**Comment by taylorcoffelt** [comment]
Applied, I'll play with the session and report back.

**Comment by taylorcoffelt** [comment]
Here's one where it sat for about 5 minutes with no input or open windows and then crashed

[hyprlandCrashReport67596.txt](https://github.com/hyprwm/Hyprland/files/11092555/hyprlandCrashReport67596.txt)

**Comment by taylorcoffelt** [comment]
Working so far, thank you @vaxerski !

**Comment by vaxerski** [comment]
pushed the patch in d6241a3086c4abfd21e91e23c83c97c3f80123d4
lmk how it goes

**Comment by taylorcoffelt** [comment]
Got another crash just now
[hyprlandCrashReport2673.txt](https://github.com/hyprwm/Hyprland/files/11093424/hyprlandCrashReport2673.txt)

**Comment by vaxerski** [comment]
wtf

can you make a debug one (see issue guidelines)

**Comment by taylorcoffelt** [comment]
Yeah, I'll do that later today.

**Comment by taylorcoffelt** [comment]
I stopped launching from GDM and am now using just the tty to start the session with the debug compiled version.

Some interesting behavior here. On "crash", I'm now getting sent back to the tty, but the process is still running(seemingly unresponsive), with no crash logs or asan log.

[hyprlandd.log](https://github.com/hyprwm/Hyprland/files/11096066/hyprlandd.log)

**Comment by taylorcoffelt** [comment]
So the same behavior is happening with Sway (but not X11 sessions, e.g. i3/Gnome) where it kicks me back to the tty after a random amount of time, I'm thinking it's more likely an NVidia driver issue with my high-refresh rate monitor at this point ( https://github.com/NVIDIA/open-gpu-kernel-modules/issues/471 )
Thanks for your help!

**Comment by vaxerski** [comment]
closing then, cuz nvidia

**Comment by Sina-Afsharmanesh** [comment]
Ran into this exact issue today. Startup is oddly slow (about 15 seconds) and no crash reports or even logs by hyprland and getting "kicked" back to sddm login without Hyprland exiting or crashing. Logging back in fixes the issue.
After reinstalling sddm and setting it's display server to x11 explicitly things seem to be normal again.

**Comment by jh-devv** [comment]
> closing then, cuz nvidia

Seems to happen on AMD aswell

**Comment by JarzaCode** [comment]
Happening to me too, only seems to happen when starting with uwsm for me (?)

**Comment by poseidonai555** [comment]
Sina-Afsharmanesh, I am having the exact same issue as you, did you manage to find any fix?

**Comment by JarzaCode** [comment]
> After reinstalling sddm and setting it's display server to x11 explicitly things seem to be normal again.
@poseidonai555
