### ISSUE TITLE
Switching between text-input clients cause broken behavior

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#1898]
Steps to reproduce:
1. Launch `fcitx5 -d`
2. Open two `foot` instances
3. Bring up the IME and try to input some text with the IME in one `foot` instance, but don't commit the text.
4. Move the focus to the other `foot` instance while the preedit is not empty.
5. Observe that the preedit appears in the `foot` instance we have just switched to.

**Comment by q234rty** [comment]
Hmmm apparently sway has this behavior as well...

**Comment by q234rty** [comment]
However I should add that if one of the clients is text-input-v1 i.e. `weston-editor` the behavior is far more broken:
1. Launch `fcitx5 -d`
2. Open `foot`
3. Launch `weston-editor &` through `foot`
4. Switch back to `foot`, bring up the IME, input some text with the IME, and commit the text.
5. Switch to `weston-editor` and observe that IME is now broken i.e. trying to bring up the IME does not do anything.

**Comment by vaxerski** [comment]
clicking with my mouse on the weston-editor window fixes that for me

**Comment by q234rty** [comment]
Yes, it seems that does fix it for a text-input-v1 client. However:

1. Launch `fcitx5 -d`
2. Open `foot`
3. Launch `chromium --ozone-platform=wayland --enable-wayland-ime &` through `foot`
4. Click on chromium, bring up the IME, input some text with the IME, and commit the text.
5. Switch back to `foot` and observe that IME is now broken i.e. trying to bring up the IME does not do anything.

In this case clicking on `foot` does not do anything, one needs to switch to another window and switch back to fix this.
