### ISSUE TITLE
Binding german Umlauts ü ä ö doesn't work

### ISSUE THREAD

**Issue by Schweber** [hyprwm/Hyprland#1909]
Binding german Umlauts ü ä ö doesn't work for me. Neither the "direct" bind, nor the bind via keycode has an effect:

bind = $mainMod, Ö, killactive,       # doesn't work
bind = $mainMod, code:47, killactive,        # doesn't work
bind = $mainMod, W,killactive,           # works

**Comment by cambordas** [comment]
I only have "ä" bind. Have you tried without the word "code"?

```
# 48 represents adiaeresis
bind = $mainMod, 48, killactive, 
```

For reference, in the input category I have:
```
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =
```

**Comment by vaxerski** [comment]
use `wev` to retrieve info about your keystrokes

**Comment by Schweber** [comment]
Thank you, without `code:` it works. 🙂

Either the [documentation](https://wiki.hyprland.org/Configuring/Binds/) is outdated or i misunderstand it,

**Comment by vaxerski** [comment]
it's not, you're just reading the
![image](https://user-images.githubusercontent.com/43317083/228517764-01ae728f-9dd5-4e5b-9857-b7772e6d7b56.png)

without being on latest git.

**Comment by JustSimplyKyle** [comment]
So the documentation is actually *indated*(I'm so sorry)
