### ISSUE TITLE
window group not behaving as expected when killing one member of the group

### ISSUE THREAD

**Issue by frigaut** [hyprwm/Hyprland#191]
- I create three windows (e.g. kitty)
- I create a group while focusing on the second kitty.
- Group is created with kitty2 and 3. 1 is left on its own. This is normal and expected (from how I understand groups work).

Now kill kitty3. It goes away but kitty1 is gobbled by the group. Why? Is that a feature? doesn't make sense. Probably a bug.

**Comment by vaxerski** [comment]
bug. As I've said, groups are pretty badly done, more of a botch, cuz I've never intended dwindle to house groups. I need to redo them.

**Comment by vaxerski** [comment]
check with c319a2aba9cf993d26af7af66a8632aad6a83d1b

**Comment by frigaut** [comment]
Seems to work much better indeed, cheers! I am still seen an unexpected behaviour when dragging the group, but this particular issue was solved, so I am closing. I will open a new one with the dragging thingy when I have more time on my hand.
