### ISSUE TITLE
Be able to view multiple workspaces at the same time

### ISSUE THREAD

**Issue by Schweber** [hyprwm/Hyprland#1910]
In awesome i can view multiple workspaces at once by right-clicking on them in the taskbar or like this:

```
        -- Toggle tag display.
        awful.key(
            { modkey, ctrlkey },
            "#" .. i + 9,
            function()
                local screen = awful.screen.focused()
                local tag = screen.tags[i]
                if tag then
                    awful.tag.viewtoggle(tag)
                end
            end,
            descr_toggle
        ),
```

I didn't find a way to replicate this in hyprland. If it's not possible already, i tender it as a feature request.

**Comment by vaxerski** [comment]
It's scriptable / pluginable. Awesomewm works on tags, Hyprland works on workspaces.
