### ISSUE TITLE
10 bit monitor enabled - Screen Sharing wont work

### ISSUE THREAD

**Issue by JaKooLit** [hyprwm/Hyprland#1911]
Hi. Not exactly a bug but you may want to add into your documentation.

Regarding 10 bit support, even if monitor does not support but if enabled in Monitor config, OBS screen sharing wont work. 

And even Monitor support 10bit, if enabled, OBS screen sharing wont work.

I believe this is more on wayland kind of issue and not exactly Hyprland.

This is testing on my laptop (Asus G15) and Desktop with monitor Odyssey G7

**Comment by vaxerski** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/24
