### ISSUE TITLE
Some games glitch in fullscreen

### ISSUE THREAD

**Issue by AdrianoTisera** [hyprwm/Hyprland#1912]
Hi, when I go fullscreen with Unity and Godot games, video glitches. It didn't happen before.
Steps to reproduce:
- Open a Unity or Godot game (maybe there are more engines and programs that have the same issue, but at this moment I just found this issue in these two).
- Go fullscreen.
- Enjoy the colors.

Expected outcome:
- Non glitchy video.

Noted outcome:
![imagen](https://user-images.githubusercontent.com/96461803/228452220-770b2432-2001-4e3d-a35a-833bcbaf1bae.png)
I'm sorry for not posting a screenshot, when I try to use grim or OBS to record and take a frame, video works correctly.
As a matter of fact, just having OBS open makes the bug dissapear.

I'm on Arch with an NVIDIA RTX 2060, using hyprland-bin.

**Comment by tchofy** [comment]
Actually, I take it back, I've just reverted to driver 525 and having direct scanout enabled still causes all the glitches. Also I don't think it's related to specific engines, I have those graphical artifacts on Celeste too, that uses neither of those engines. Might try to do a git bissect later just for the sake of learning it.

**Comment by vaxerski** [comment]
IIRC direct scanout is indeed broken in nvidia.

**Comment by lou-perret** [comment]
Hello !

I think it's caused by xorg-xwayland-23.1.0 (no idea about 23.1.1, haven't tested yet). Downgrading to 22.1.8 fixes the issue

**Comment by tchofy** [comment]
> Hello !
> 
> I think it's caused by xorg-xwayland-23.1.0 (no idea about 23.1.1, haven't tested yet). Downgrading to 22.1.8 fixes the issue

Ah, you hit the nail in the head, seems like 23.1.0+ are having that issue, had the same result downgrading it, even while having direct scanout enbled and without WLR_DRM_NO_ATOMIC.

**Comment by lou-perret** [comment]
I had to upgrade to xorg-xwayland-23, and the issue is still there.

 `no_direct_scanout = yes` fixes it
