### ISSUE TITLE
Dynamic external displays

### ISSUE THREAD

**Issue by addy419** [hyprwm/Hyprland#1913]
Hey vaxry, I was watching your interview with brodie on hyprland and thought of some enhancements that could make hyprland more user friendly (maybe?).

In gnome/kde, you have a settings page where you can dynamically select what to do with external displays. Currently what I'm doing is writing it in the config file. But the issue is that sometimes I want both the laptop and external display to run simultaneously, sometimes(playing games mostly) I want only the external display to be on. What I currently do is change the config file. But a utility can be made to graphically(or otherwise) select what to do with external monitors on the fly and also set a default behavior. I don't have any exact implementation ideas, but if you think it's a good feature, consider it. I have little knowledge about hyprland or wayland compositors in general but have a strong C/C++ background. I'll also look into it once I'm a little free. I'll just leave the FR here.

**Comment by vaxerski** [comment]
A settings-like graphical thing is not hyprland's job. besides, wldisplays exists.

For dynamic monitor settings you can just `hyprctl keyword monitor ...` (see wiki using hyprctl) and bind that to a key.

I do not see a missing feature here.

**Comment by addy419** [comment]
No worries. I'll try something and get back to it. I'll close this now.
