### ISSUE TITLE
transform works with `hyperctl` but not in `hyperland.conf`

### ISSUE THREAD

**Issue by makerio90** [hyprwm/Hyprland#1914]
when i try to rotate my screen via `hyprctl keyword monitor "HDMI-A-1,transform,3"`, it works fin and my monitor rotates.
but when i try to edit my config as below:
```
monitor=DP-1,2560x1440@165,1080x0,1,bitdepth,10
monitor=HDMI-A-1,1920x1080,0x0,1,transform,3
```
(after adding the `transform,3` bit) suddenly my monitor goes back horizontal and i get a syntax error at the top of my screen
here is the log for when i try to load it via the config:
```
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 17.58µs. Estimated average calc time: 0.00µs.
[ERR] Config error: invalid monitor syntax
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 17.59µs. Estimated average calc time: 0.00µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
[LOG] Creating the ThreadManager!
[LOG] Hypr socket started at /tmp/hypr/72de2fa90dec2989b0597f0efe33635f0108646e_1680136452/.socket.sock
[LOG] Creating the InputManager!
[LOG]  [hookSystem] New hook event registered: keyboardFocus
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Creating the Hypr OpenGL Renderer!
[LOG] Using: OpenGL ES 3.2 Mesa 23.0.1
[LOG] Vendor: AMD
[LOG] Renderer: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.49, 6.2.8-arch1-1)
[LOG] Supported extensions size: 149
[LOG] Creating the HyprRenderer!
[LOG] Creating the XWaylandManager!
[LOG] Registered signal for owner c84a0060: c84a00a0 -> c5bc9ee0 (owner: XWayland Manager)
[LOG] Registered signal for owner c84a0060: c84a00b0 -> c5bc9ec0 (owner: XWayland Manager)
[LOG] CHyprXWaylandManager started on display :0
[LOG] Creating the ProtocolManager!
[LOG] ToplevelExportManager started successfully!
[LOG] FractionalScaleManager started successfully!
[LOG] TextInputV1Manager started successfully!
[LOG] Creating the SessionLockManager!
[LOG] Creating the EventManager!
[LOG] Creating the HyprDebugOverlay!
[LOG] Creating the HyprNotificationOverlay!
[LOG] Creating the PluginSystem!
[LOG] Hyprland init finished.
```

**Comment by yavko** [comment]
Yo its `hyprland.conf` not hyp***e***rland.conf, just wanted to say, if you want to fix issue title 😊.

**Comment by vaxerski** [comment]
you can't use the -git wiki methods on 0.23.0beta...
![image](https://user-images.githubusercontent.com/43317083/228820893-268d8564-33a2-43cc-b32c-9aec0ac1ef58.png)
exists for a reason

**Comment by makerio90** [comment]
> you can't use the -git wiki methods on 0.23.0beta... ![image](https://user-images.githubusercontent.com/43317083/228820893-268d8564-33a2-43cc-b32c-9aec0ac1ef58.png) exists for a reason

https://wiki.hyprland.org/0.23.0beta/Configuring/Monitors/ scroll to bottom. still says it should work?

**Comment by makerio90** [comment]
update - switched to git release, it works now. anoying but atleast it works lol

**Comment by vaxerski** [comment]
`monitor=HDMI-A-1,1920x1080,0x0,1,transform,3`

is invalid on 0.23.0beta and the 0.23 wiki does not tell you that you are allowed to do that.
