### ISSUE TITLE
Drawing with graphics tablet isn't smooth

### ISSUE THREAD

**Issue by sbstratos79** [hyprwm/Hyprland#1915]
Lines drawn with graphics tablet aren't smooth. I have tested this with OTD (stable and git version), as suggested in the wiki, and without it.
No such issue is observed in a wayland compositor like sway or any of the major DE's like Gnome, KDE etc.

Here's a sample image. The line isn't smooth at all:
![line](https://user-images.githubusercontent.com/4395586/228833155-9f456cb8-a711-4b06-9ea9-25e313116f3d.png)

EDIT: Btw, the tablet is Gaomon 1060 PRO. I don't think that should matter since it's compatible with OTD and linux ootb.

EDIT2: Same tablet in sway:
![line_sway](https://user-images.githubusercontent.com/4395586/228839272-48505784-9ca0-47b3-a5ff-58cd9d8d1b9f.png)

**Comment by sbstratos79** [comment]
Some more context based on some feedback by an otd dev.![image](https://user-images.githubusercontent.com/4395586/231160112-54fb9c74-9889-4189-b576-f3b665b5c3ae.jpeg)

**Comment by Bug23451** [comment]
Seems to of been resolved.

Tablet: Wacom CTL 4100
Krita: 5.1.5-10
Hyprland: v0.25.0-44-g9f8c5cb6
Kernel: 6.3.6-zen1-1-zen  
![test](https://github.com/hyprwm/Hyprland/assets/38907238/cc0824b3-42ec-4ab8-9d95-3ca1bad234be)

**Comment by sbstratos79** [comment]
> Seems to of been resolved.
> 
> Tablet: Wacom CTL 4100
> Krita: 5.1.5-10
> Hyprland: v0.25.0-44-g9f8c5cb6
> Kernel: 6.3.6-zen1-1-zen  
> ![test](https://github.com/hyprwm/Hyprland/assets/38907238/cc0824b3-42ec-4ab8-9d95-3ca1bad234be)
> 

Thanks for the heads up. I will test it on my system and close this issue if the results are positive.

**Comment by sbstratos79** [comment]
Got around to finally testing this. I am using Hyprland 6594b50e57935dd66930ccd35dba7a1b4131399d on NixOS and this issue has been resolved for me. I will close this issue.
