### ISSUE TITLE
cant launch on fresh arch install from aur 

### ISSUE THREAD

**Issue by bdreaves04** [hyprwm/Hyprland#1916]
trying to install from the aur but getting an error when trying to launch from tty. 

```
Hyprland: error while loading shared libraries: /usr/lib/libdisplay-info.so.1: file too short

**Comment by vaxerski** [comment]
`yay -S libdisplay-info-git`?

**Comment by karl0d** [comment]
same issue on fedora 37

**Comment by bdreaves04** [comment]
Managed to fix mine by doing a complete reinstall of arch and manually installing dependencies before installing from they hyprland aur
