### ISSUE TITLE
Crashing in headless mode

### ISSUE THREAD

**Issue by LDAP** [hyprwm/Hyprland#1917]
I followed the instructions on wayvnc which work for sway but not for Hyprland.

## Steps to reproduce:
1. Launch Hyprland with `WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 Hyprland`

## Expected behavior
A headless session starts. I could then start wayvnc and connect to the session.

## Actual behavior
Hyprland crashes with:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  wlr_backend_get_drm_fd() failed!
zsh: segmentation fault (core dumped)  WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 Hyprland
```

## Additional context
It works on sway. There's only a warning:
```
00:00:00.024 [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
```

**Comment by vaxerski** [comment]
Simple, Hyprland does not support the headless backend.

Why would you want to do this?

**Comment by LDAP** [comment]
> Simple, Hyprland does not support the headless backend.

:(

> Why would you want to do this?

I am traveling a lot and my main machine is stationary. This allows me to start a headless session remotely and get access to the graphical session without some kind of forwarding (X-forwarding, waypipe; which performed badly in my tests) with great performance.

What I am doing now is
```
ssh user@r<remote-tunnel-ip>
WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 sway &
WAYLAND_DISPLAY=wayland-1 wayvnc <remote-tunnel-ip>
```
and I would prefer Hyprland since that is what I use on site.

**Comment by vaxerski** [comment]
I do understand but it's a niche usecase and as such is not a priority - you're welcome to make a pr

**Comment by jennydaman** [comment]
Seems like someone had success with `WLR_BACKENDS=headless Hyprland` 4 months ago with Hyprland version 0.16.0

https://github.com/any1/wayvnc/issues/172

**Comment by Astralchroma** [comment]
having the same issue, need it for a similar reason, would be nice if this was fixed.

**Comment by Astralchroma** [comment]
Waypipe doesn't require Hyprland to run headless, or even run at all for that matter, if you don't want to use that, you can run Hyprland as a window inside of sway

**Comment by cikeZ00** [comment]
Same issue, exactly the same reason.

**Comment by gfhdhytghd** [comment]
Buy a graphics card cheater then, a small device that can tell your computer ”I’m a display” and your computer will start rendering 
![IMG_0334](https://github.com/hyprwm/Hyprland/assets/102898587/81f39567-2332-46c1-9d5a-dc93bfaa68e4)

**Comment by ezkha** [comment]
> Seems like someone had success with `WLR_BACKENDS=headless Hyprland` 4 months ago with Hyprland version 0.16.0
> 
> [any1/wayvnc#172](https://github.com/any1/wayvnc/issues/172)

This user didn't have to start Hyprland from headless: it was already running for them.

> Buy a graphics card cheater then, a small device that can tell your computer ”I’m a display” and your computer will start rendering

Could it also work by creating a virtual display with `xrandr`?

I would love to see Hyprland supporting headless mode but I understand it's not a priority.

**Comment by gfhdhytghd** [comment]
I'm not sure about xrandr, the only thing I know is this thing will work like a real physics display, but with out display

**Comment by ezkha** [comment]
Sorry for the late reply.

I'm not sure if it applies to your case,
but the way I remotely controlled Hyprland using `hyprctl`
was by :

1. making sure that Hyprland is [automatically started on boot](https://wiki.archlinux.org/title/Autostarting#On_shell_login_/_logout)
2. from remote, run `hyprctl instances`
3. copy the sole instance signature : the hexadecimal string that follows "instance" and precedes the colon
4. set an environment variable `HYPRLAND_INSTANCE_SIGNATURE` with that instance signature as value

Now you can remotely use `hyprctl` for anything, [like creating a headless monitor](https://wiki.hyprland.org/Configuring/Using-hyprctl/#output). Maybe you'll need to also auto-start WayVNC and/or configure it to use the headless monitor.

BTW I was using Moonlight with Sunshine that is more tailored for remote gaming, not VNC.

> can you point me to some documentation, i am trying to do the same.
> 
> From my host machie ->
> 
> ```
>  ssh user@r<remote-tunnel-ip>
>  WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 Hyprland &     # will be executed on remote machine
>  WAYLAND_DISPLAY=wayland-1 wayvnc&   # will be executed on remote machine
> ```
> 
> What to do after this? How to connect to the remote machine? I saw this https://wiki.hyprland.org/Configuring/Using-hyprctl/#output , is it usable, how to use it?
> 
> By the way i am trying to do this on same machine, i want to access 2nd user account applicaton in same Hyprland session. Is there some better way to do this?

**Comment by appleseedexm** [comment]
I needed a way to wake my remote screen via `dpms` and ran into this issue. I wrote a small [script](https://gist.github.com/appleseedexm/4e20d39ba03f03f05503a9de95c367b6) to easily set the current available instance as `$HYPRLAND_INSTANCE_SIGNATURE`. Could possibly be extended with setting `$DISPLAY` and `$WAYLAND_DISPLAY`.

**Comment by fxzxmicah** [comment]
Headless mode doesn't work again. https://github.com/hyprwm/Hyprland/issues/7753

**Comment by spikespaz** [comment]
could headless mode become possible to use in automatic tests which depend on a running Hyprland if the compositor could be configured with an fake output?

**Comment by vaxerski** [comment]
technically? idk what environment the gh runners run in
