### ISSUE TITLE
GPU intensive applications are starving compositor, resulting low FPS in it.

### ISSUE THREAD

**Issue by grappas** [hyprwm/Hyprland#1919]
There were no crash whatsoever.

I have a dual monitor setup. I've tested some games - native and proton ones. Pretty much majority have the same issue: FPS practically is halved. Game and/or reports double of real FPS. Though when I disable one of those monitors FPS is ok. Also when I reduce 4K monitor's resolution to HD FPS also is going back to normal.
1. Version: 0.23b on Arch Linux
2. Setup:
 - two monitors: one HD, other 4K
 - AMD RX6750xt
3. Steps to reproduce:
- enable both monitors
- launch the game
4. Expected outcome:
- FPS reported by game equals frames displayed
5. Noted outcome:
- Half of FPS are displayed in reality.

https://cdn.discordapp.com/attachments/995047159542063154/1091110417977331862/r.mp4

**Comment by vaxerski** [comment]
try `misc:no_direct_scanout=true`

**Comment by grappas** [comment]
Already tried it.

**Comment by vaxerski** [comment]
Check radeontop / corectrl / any other gpu performance utility. Maybe your gpu can't keep up?

**Comment by grappas** [comment]
It can keep up. Same setup had on GNOME without an issues, in KDE with the same issues.

**Comment by vaxerski** [comment]
what about sway?

Besides, please check it. Just because it can on gnome doesnt 100% mean it can anywhere else.

**Comment by vaxerski** [comment]
Seems like this:
https://blogs.gnome.org/shell-dev/2023/03/30/ensuring-steady-frame-rates-with-gpu-intensive-clients/

**Comment by grappas** [comment]
> what about sway?
Hyprland is my first vanilla tiling manager. So sway will be entire new experience 😆

**Comment by vaxerski** [comment]
oh. At any rate, if you say KDE has the same, why not just cap the FPS of your game? that should fix htis.

**Comment by grappas** [comment]
It's making it worse. If I cap FPS to lets say 60, I'm getting ~25-40.

**Comment by vaxerski** [comment]
odd

**Comment by grappas** [comment]
On original post there's uncut video.

**Comment by vaxerski** [comment]
can you turn on `debug:overlay` and see what it has to say?

**Comment by grappas** [comment]
Link updated in OP.

**Comment by grappas** [comment]
Valheim:
![obraz](https://user-images.githubusercontent.com/1036957/229188845-f7ab4664-5d17-40c6-9ce4-0a9eb7bf070f.png)

**Comment by vaxerski** [comment]
Never seen this happen. Perhaps something that could start working with the tearing MR.

**Comment by grappas** [comment]
> why not just cap the FPS of your game
actually... **It done the trick.** Not the fan of this solution though... 
Is there any way to make compositor have more GPU priority?

**Comment by grappas** [comment]
But you have to admit that's clearly an issue.

**Comment by vaxerski** [comment]
never said it's not...? That's why it's open

**Comment by grappas** [comment]
Temporary fix is using gamescope (it started to work with latest update?, never worked before)

**Comment by MatthiasGrandl** [comment]
Also encountering this issue. 4K monitor stable 120 FPS in game, frame drops to ~60 in the compositor.
A standalone gamescope session does not show this behavior.

**Comment by GrabbenD** [comment]
**Reproducible example**
Start a CPU bound game, e.g by using lowest graphics or only using a subset of the computer's available cores (4) like this:
```
#!/bin/bash

taskset -c 0-3 Hyprland
```

**Comment by romanstingler** [comment]
@MatthiasGrandl did you check that with hyprland overview? 

If so, I have a 240Hz Monitor on my workstation and in OpenBoardView (PCB schematic viewer) you can enable the fps 
and I get 240fps when my overlay is not activated, and it tops at 120Hz when the overlay is enabled.
So I think the way the overlay gets the stats is impacting the performance.

**Comment by GrabbenD** [comment]
There's work being done in upstream/wlroots to improve performance when GPU is under high load:
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4040

There's also some new updates around better frame scheduling in wlroots:
https://blog.krx.sh/

I personally found alternative CPU schedulers like primarily EEVDF and also BORE to make a noticeable difference over default CFS with 100% CPU load. TT/task type (Cacule successor) is better than CFS too. I wouldn't recommend using BMQ nor PDS though.

**Comment by grappas** [comment]
I don't think it's that an issue anymore. I'm closing it for now (so that Issues page would not be littered ;))

**Comment by vaxerski** [comment]
I wish I had a moderator for these issues tbh

**Comment by grappas** [comment]
There would have to be some guidelines how to moderate these things. There are some unresolved issues, there are some issues resolved for some time. There are also unresolved ones, but OP is i.e. not using hyprland anymore.

**Comment by grappas** [comment]
Do you have some todos?

**Comment by vaxerski** [comment]
> Do you have some todos?

No, not really

by moderation I mean finding out what issues to prioritize, squashing dupes / invalids, etc.
