### ISSUE TITLE
Confusing Documentation Wiki

### ISSUE THREAD

**Issue by Moerliy** [hyprwm/Hyprland#1922]
To make it quick: On the wiki for [environment variables](https://wiki.hyprland.org/Configuring/Environment-variables/#toolkit-backend-variables) at *QT_QPA_PLATFORM="wayland;xcb"* the quotation mark should be deleted. They're already gone below QT Variables headline.

**Comment by GrabbenD** [comment]
This is the wrong repository 🙈 
https://github.com/hyprwm/hyprland-wiki
