### ISSUE TITLE
Master layout: layoutmsg cyclenext doesn't work on float windows.

### ISSUE THREAD

**Issue by tienbuigia** [hyprwm/Hyprland#1927]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

1. Steps to reproduce
    1. install hyprland
    2. set layout to master and keybinds
    3. open tiled windows and a float window
    4. try keybinds 'layoutmsg cyclenext' or prev
5. Expected outcome
    - focus moves from windows to windows regardless of its state being float or tiled.
7. Noted outcome
    - the keybinds doesn't work with float windows.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/229237022-aaa919c9-dfe2-4b7e-bed9-693d613318e1.png)

for a layout-agnostic method see the `cyclenext` dispatcher

**Comment by tienbuigia** [comment]
yes, my bad. I'm sorry.

But that doesn't make sense since normal cyclenext doesn't respect the order of windows in master layout because master-layout users usually swap windows a lot.
