### ISSUE TITLE
make pluginenv does not compile (Arch Linux)

### ISSUE THREAD

**Issue by Teddy-Kun** [hyprwm/Hyprland#1928]
Using the both the latest hyprland-git and v0.23.0/beta when I try to "make pluginenv" it does not compile with the error below. The error is basically identical for the two. If I have missed a step I think the documentation should be updated. I have tried to run "make fixwlr" manually but that did nothing.

> [175/307] Compiling C object libwlroots.so.12032.p/backend_wayland_output.c.o
FAILED: libwlroots.so.12032.p/backend_wayland_output.c.o 
cc -Ilibwlroots.so.12032.p -I. -I.. -Iinclude -I../include -Iprotocol -I../protocol -Irender/gles2/shaders -Irender/vulkan/shaders -Ibackend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../= -march=native -O2 -DXWAYLAND -DWLR_USE_UNSTABLE -std=c99 -fPIC -MD -MQ libwlroots.so.12032.p/backend_wayland_output.c.o -MF libwlroots.so.12032.p/backend_wayland_output.c.o.d -o libwlroots.so.12032.p/backend_wayland_output.c.o -c ../backend/wayland/output.c
../backend/wayland/output.c: In function ‘presentation_feedback_handle_presented’:
../backend/wayland/output.c:80:16: error: variable ‘t’ has initializer but incomplete type
   80 |         struct timespec t = {
      |                ^~~~~~~~
../backend/wayland/output.c:81:18: error: ‘struct timespec’ has no member named ‘tv_sec’
   81 |                 .tv_sec = ((uint64_t)tv_sec_hi << 32) | tv_sec_lo,
      |                  ^~~~~~
../backend/wayland/output.c:81:27: warning: excess elements in struct initializer
   81 |                 .tv_sec = ((uint64_t)tv_sec_hi << 32) | tv_sec_lo,
      |                           ^
../backend/wayland/output.c:81:27: note: (near initialization for ‘t’)
../backend/wayland/output.c:82:18: error: ‘struct timespec’ has no member named ‘tv_nsec’
   82 |                 .tv_nsec = tv_nsec,
      |                  ^~~~~~~
../backend/wayland/output.c:82:28: warning: excess elements in struct initializer
   82 |                 .tv_nsec = tv_nsec,
      |                            ^~~~~~~
../backend/wayland/output.c:82:28: note: (near initialization for ‘t’)
../backend/wayland/output.c:80:25: error: storage size of ‘t’ isn’t known
   80 |         struct timespec t = {
      |                         ^
../backend/wayland/output.c:80:25: warning: unused variable ‘t’ [-Wunused-variable]
[180/307] Compiling C object libwlroots.so.12032.p/types_data_device_wlr_data_device.c.o
FAILED: libwlroots.so.12032.p/types_data_device_wlr_data_device.c.o 
cc -Ilibwlroots.so.12032.p -I. -I.. -Iinclude -I../include -Iprotocol -I../protocol -Irender/gles2/shaders -Irender/vulkan/shaders -Ibackend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../= -march=native -O2 -DXWAYLAND -DWLR_USE_UNSTABLE -std=c99 -fPIC -MD -MQ libwlroots.so.12032.p/types_data_device_wlr_data_device.c.o -MF libwlroots.so.12032.p/types_data_device_wlr_data_device.c.o.d -o libwlroots.so.12032.p/types_data_device_wlr_data_device.c.o -c ../types/data_device/wlr_data_device.c
In file included from ../include/wlr/types/wlr_data_device.h:13,
                 from ../types/data_device/wlr_data_device.c:8:
../include/wlr/types/wlr_seat.h:242:25: error: field ‘last_event’ has incomplete type
  242 |         struct timespec last_event;

**Comment by vaxerski** [comment]
CI does not fail = issue on your side.
