### ISSUE TITLE
Monitor Offset Values Affecting StardewValley Focus

### ISSUE THREAD

**Issue by cufffs** [hyprwm/Hyprland#1930]
**Issue:**
If second monitor is off and config has an offset position for the main monitor then I'm unable to gain focus on StardewValley(steam) and the mouse simply disappears when over the top of the game, if StardewValley launches in full screen, then the mouse stops at 3/4 down the screen as if there is an invisible wall

Video of full screen issue: https://streamable.com/qu7flf 
Video of windowed issue: https://streamable.com/onzxuj

The only other games I have installed are Jackbox, and they seem to work fine.
I only changed the config for second monitor 1-2 weeks ago and have not noticed any issues outside of StardewValley

**Reproducing:**
My monitors
```
DP-1:2560x1440
DP-2:1920x1200
```

In hyprland.conf the lines that cause bug are:
```
monitor=DP-1,2560x1440,0x1205,1
monitor=DP-2,1920x1200,320x0, 1
```

If I'm using only my main monitor and either or both of the above lines are active then I experience the bug.
If I'm using only my main monitor, then I must comment both lines and restart PC for it all to work as expected.
If I'm using both monitors, then I can freely comment/uncomment either or both lines and everything works as intended

As soon as I change DP-1 to the below line, everything works as intended
`monitor=DP-1,2560x1440,0x0,1`

**Expected out come**
I would expect that I should be able to turn on and off my second monitor without affecting the ability to run stardew valley (and possibly other games)
I would expect that I can use the offset values I have set as this enable me to have my second monitor centered above my main monitor.
The reason for "0x1205" instead of "0x1200" is so that my mouse stops at top of main monitor unless moving fast, making it much easier to use the top menu bar

**Comment by vaxerski** [comment]
it's an XWayland issue. The only way to fix affected apps is to run them in gamescope or wine virtual desktop.

I have the same with civ4 and it's reproducible on sway as well
