### ISSUE TITLE
feature-request: reordering of a window in a group

### ISSUE THREAD

**Issue by aktaboot** [hyprwm/Hyprland#1932]
Hey,

It would be nice to have a feature where `movewindow` also works in window groups. i.e. reordering a window's placement in a group. 
I have not found a way to do that with current bindings.

Is such a feature desirable ?

Thanks

**Comment by MightyPlaza** [comment]
@vaxerski close please

**Comment by Nohac** [comment]
I'm also looking for a way to do this. @MightyPlaza are you requesting this issue to be closed because it's already implemented? If so, I'm not able to figure out how to do it.

**Comment by MightyPlaza** [comment]
there already exists `movegroupwindow` and dragging also works

**Comment by izmyname** [comment]
Bump as a reminder to close/not to close
