### ISSUE TITLE
Waybar not showing and there is no conf

### ISSUE THREAD

**Issue by FluttyPNG** [hyprwm/Hyprland#1933]
Hi 

So i recenthy installed hyprland and i have a problem, i installed waybar but there is no conf file for waybar (.config/waybar/conf)

**Comment by outragedline** [comment]
what? its not even a hyprland issue

waybar and hyprland arent directly related one to another

this file is not created automatically, YOU must create it, here, you can use [my config](https://github.com/outragedline/dotfiles/blob/main/.config/waybar) as example

and dont forget to add `exec-once = waybar` to your hyprland config

does it solve your issues?

**Comment by FluttyPNG** [comment]
Yes it solve my isssues, thanks
