### ISSUE TITLE
Swallowed Window Does not Change Workspace with Swallower

### ISSUE THREAD

**Issue by BenMac31** [hyprwm/Hyprland#1934]
**Version:** 0.23.0beta-1
**Steps to reproduce:**
Swallow terminal into window.
Open terminal in Workspace 3 (should be empty before opening terminal)
Swallow terminal into window.
Move window to Workspace 2.
`hyprctl clients | grep -B 5 "workspace: 3"` Will show that there is still a window on Workspace 3.
**Expected Outcome:**
Nothing should show up on Workspace 3 because there are no real windows on Workspace 3.

**Comment by vaxerski** [comment]
fixed in c2b25f4701c98704303ab4ca9d008a29deb527b3

**Comment by BenMac31** [comment]
Your a legend mate
