### ISSUE TITLE
Changing focus while clicked causes weird behavior

### ISSUE THREAD

**Issue by LDAP** [hyprwm/Hyprland#1935]
## Steps to reproduce:
1. Open a window with scrollbar
2. Press the mouse button on the scrollbar
3. Move the mouse into the gap
4. Release mouse button
5. Return to the window

## Expected behavior
Window does not keep scrolling

## Actual behavior
Window keeps scrolling

## Additional context
Could be the cause for https://github.com/Alexays/Waybar/issues/1968

**Comment by godalming123** [comment]
I also get this issue but instead of stopping scrolling as soon as you leave the window I think that scrolling should be stopped when you release your mouse IE: the client still receives cursor events even when you leave it's bounding box if your mouse is being pressed.

**Comment by vaxerski** [comment]
fixed in 0fc145c52cf1743a9bb71a8d7c759305d2323a23
