### ISSUE TITLE
Setting a windowrule-v2 for opacity requires restarting the app to apply it

### ISSUE THREAD

**Issue by csdvrx** [hyprwm/Hyprland#1936]
Try:

`windowrulev2 = opacity 0.8 override,class:^(thunderbird)`

When you change the value and save your hyprland.conf, the change will not be applied unless you restart the app

**Comment by vaxerski** [comment]
That's an expected result. Rules are applied on window open, or (if it's dynamic) when a property _changes_, and the class does not change.

**Comment by shafayetejaman** [comment]
not working
windowrulev2 = opacity 1 override,class:^(code)
still has transparent effect to vscode
