### ISSUE TITLE
Return error code when toggling to empty special workspace

### ISSUE THREAD

**Issue by jdsee** [hyprwm/Hyprland#1937]
It would be nice if `togglespecialworkspace` returned an error code if the corresponding workspace is empty, to be able to launch a program conditionally in case it's not yet running.

My concrete use case is to open my file manager automatically in a separate special workspace. I would like to use the same key binding to launch the file manager and open the assigned workspace without launching multiple file manager instances.
 
The error code would be sufficient to implement that. Anyways I'm not sure if there's a better way to realize this idea or if it's possible already. Any help is much appreciated!

**Comment by vaxerski** [comment]
An error code after a dispatcher is not really planned as dispatchers were never made to return back errors.

Why can't you just `hyprctl workspaces` and see if your workspace is open?

**Comment by jdsee** [comment]
Haven't thought that far. Thanks for the quick reply!
