### ISSUE TITLE
(NVIDIA Arch) After downgrading gpu drivers to 525, Hyprland does not launch without wlr try errors

### ISSUE THREAD

**Issue by Pipenguim** [hyprwm/Hyprland#1938]
The reason that I downgraded my drivers in the first place was because I was having an issue where refresh rates above 144 just broke everything. I saw that it was a common issue, and that the fix was to downgrade to 525, so that’s what I did.
I downgraded both nvidia-open-dkms and nvidia-utils to 525, and everything seemed like it was working. DKMS said I was on 525, and no errors came out of it.
When I tried launching Hyprland, the console showed no apparent errors, and looked like the same thing I usually get when launching, just this time it did not work. I got the log and I got the error “m_sWLRRenderer was null”. I tried several things to fix this.
First I saw the gentoo thread on here where someone had the same problem and used a forked commit and it worked for them. I did the same thing but nothing changed.
Then I tried setting the environmental variable $WLR_RENDERER. While it indeed was set, nothing changed, and I am still getting the same error.
I also tried re-installing hyprland, both the normal and git versions through yay, but no luck.
I am not quite sure what to do, since no one replied in the discord, and I have been searching for several hours at this point.
I have a feeling this is a simple solution but I was not able to find anything about the swlrrenderr variable, and I don’t really know what to do.
All my logs were the same, it was all the same as before, but it just abruptly stopped when I got the error that it was not set.
What should I do?

**Comment by vars1ty** [comment]
Got no solution but just so you know; Hyprland doesn't support NVIDIA officially and you're often recommended to join the Discord and ask for help in the nvidia channel.

**Comment by Pipenguim** [comment]
I did but no one seems to reply to me. I am very lost.

**Comment by vaxerski** [comment]
Nvidia is not supported and I am unable to give you any support. I have 0 knowledge of nvidia's proprietary bullshit.

> I did but no one seems to reply to me.

Maybe nobody else has this issue.

**Comment by Pipenguim** [comment]
I used journalctl and found some potentially useful information.
![9C6D7070-D412-4F35-BBFC-73D203CC8BD1](https://user-images.githubusercontent.com/70240564/229614209-19576368-65b1-4759-bf6f-65bd95aa7589.jpeg)
![53237BB1-5617-4CB8-AB1B-4CDE33A70F45](https://user-images.githubusercontent.com/70240564/229614243-31835183-02d0-4e3e-8d7b-7d8584ff7c98.jpeg)

**Comment by Pipenguim** [comment]
I have fixed it. I am quite embarrassed to say this, but the solution was just to update arch with pacman -Syyu.
I completely forgot to do that.
