### ISSUE TITLE
Interacting with squeekboard steals focus from active window

### ISSUE THREAD

**Issue by peter-marshall5** [hyprwm/Hyprland#1939]
Steps to reproduce:
- Start squeekboard
- Try to type anything with the touchscreen

Expected outcome:
The on-screen keyboard should enter text into the active window.

Noted outcome:
Focus is stolen from the active window, making it impossible to type anything and causing the keyboard to close. The keyboard then re-opens right after closing when focus returns to the window.

**Comment by peter-marshall5** [comment]
Actually, it doesn't seem to work with a pointer either. Interestingly, Hyprland sometimes crashes altogether when launching squeekboard. 

If it helps, I'm using the testing branch of Manjaro with the latest squeekboard package and the latest hyprland-git from the AUR. How would I go around collecting a stack trace to debug this further?

**Comment by vaxerski** [comment]
`~/.hyprland/` contains crash reports, as pointed out by the issue guidelines you were supposed to read _before_ posting.

**Comment by peter-marshall5** [comment]
This is fixed as of the latest Hyprland commit.

**Comment by earboxer** [comment]
For posterity, I assume this was fixed by 4ae784dc5374092734a6ed30ba56011e50c902d6
