### ISSUE TITLE
Hyprland crash when launching modded Genshin Impact

### ISSUE THREAD

**Issue by Slimemaster0** [hyprwm/Hyprland#1940]
[hyprlandCrashReport712.txt](https://github.com/hyprwm/Hyprland/files/11140524/hyprlandCrashReport712.txt)
I had Discord and a terminal, that i run my launch script from, running when the crash happend.
The game usually launches just fine, but this time Hyprland crashes.

**Comment by vaxerski** [comment]
dupe of #1890
