### ISSUE TITLE
nix: wlroots hidpi patch broken

### ISSUE THREAD

**Issue by Kiskae** [hyprwm/Hyprland#1943]
Basically a repeat of #1842, it appears that the recent bump of the wlroots dependency has broken the patch again:

```console
       > applying patch /nix/store/jik866wm430p50kdvvfw3sspzsqknsmr-wlroots-hidpi.patch
       > patching file include/xwayland/xwm.h
       > Hunk #2 succeeded at 99 (offset 2 lines).
       > patching file xwayland/xwm.c
       > Hunk #1 FAILED at 19.
       > Hunk #3 succeeded at 969 (offset 3 lines).
       > Hunk #4 succeeded at 1001 (offset 3 lines).
       > Hunk #5 succeeded at 1019 (offset 3 lines).
       > Hunk #6 succeeded at 1137 (offset 3 lines).
       > Hunk #7 succeeded at 1778 (offset 3 lines).
       > Hunk #8 succeeded at 1796 (offset 3 lines).
       > Hunk #9 succeeded at 2141 (offset 3 lines).
       > 1 out of 9 hunks FAILED -- saving rejects to file xwayland/xwm.c.rej
```

I tried to have a look at updating the patch myself, but it isn't really documented how the patch differs from the upstream patch, but it appears to include parts that aren't upstream: https://gist.github.com/Kiskae/6f5087778206305c165c2546c6d276d5/revisions?diff=split

**Comment by vaxerski** [comment]
@fufexan for nix

**Comment by fufexan** [comment]
What happened though, why was the version rolled back @vaxerski? https://github.com/hyprwm/Hyprland/commit/bae19cb10e0c7f972c4461d1b80b416a6db6d561.
`1d64e1` is from March 20, and `5ae17de` is from March 2.

**Comment by vaxerski** [comment]
whattt

**Comment by vaxerski** [comment]
should be fixed now, idk why it rolled to 5ae17de, it's at 89dcecba39d4f49b673f2fa976354c91413a4c3f now

**Comment by Kiskae** [comment]
> wlroots-hyprland-hidpi-nvidia: 2023-03-20_1d64e12 → 2023-03-28_89dcecb

appears to be fixed.

**Comment by archer-65** [comment]
Woah, it's broken again after the latest wlroots dependency update 1a5d5bf. 
@fufexan any ideas?

**Comment by fufexan** [comment]
The main issue is Nixpkgs' xwayland version was updated, and the HiDPI patch no longer applies. I'll have to figure that out first.
