### ISSUE TITLE
[ackend.c:382] Failed to open any DRM deviceackend session

### ISSUE THREAD

**Issue by okobenoko** [hyprwm/Hyprland#1945]
Environment:Arch Linux, GTX1050ti, lastest ver

m_sWLRBackend was NULL!ackend.c:382] Failed to open any DRM deviceackend session
terminate called after throwing an instance of ‘std::runtime_error’
   what(): wlr_backend_autocreat() failed!

[LOG] Registered dynamic var “$mainMod” -> SUPER
[CRITICAL] m_sWLRBackend was NULL!

**Comment by vaxerski** [comment]
Nvidia is not supported. If you followed the nvidia wiki page and you're unable to use hl, you're out of luck.
