### ISSUE TITLE
Fps capping to 30

### ISSUE THREAD

**Issue by Reireiyan** [hyprwm/Hyprland#1949]
I have a hybrid Intel i5/NVIDIA GTX 1050 laptop, and I've noticed in Hyperland that the frame rate caps at 30 in every game. This issue also happened in Plasma, but only if the Force smoothest animation option in the compositor settings in Plasma was set. Setting the compositor to prefer smooth animations or any other setting other than forced fixes the issue there, but under Hyprland, I don't know what the equivalent fix for this is.

**Comment by vaxerski** [comment]
`misc:no_direct_scanout = true`?

**Comment by Reireiyan** [comment]
So for me, the no direct scanout option is not a perfect solution for this.

**Comment by Reireiyan** [comment]
Also, when no direct scan out is set, I've noticed the CPU usage in-game gets really high. It's a pretty bad solution.

**Comment by vaxerski** [comment]
you'll probably have to wait for tearing updates then to be merged.

**Comment by Zeioth** [comment]
If this is while gaming on a PC with two GPUs, try to launch the game with:

    DXVK_FILTER_DEVICE_NAME="AMD Radeon RX 6700 XT" %command%

This is not optional. If you have two GPU you MUST use this env var. Also, be aware that currently, wlroots will cap FPS by half on all displays connected to the 2º GPU.

**Comment by romanstingler** [comment]
have you enabled hyprland overlay?

**Comment by Reireiyan** [comment]
The latest Nvidia 545 beta fixed the jittering and the FPS cap of 30 issues.

**Comment by vaxerski** [comment]
closing then
