### ISSUE TITLE
Dialog boxes.

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#1950]
![image](https://user-images.githubusercontent.com/60490474/229985290-2fc22a07-da83-4040-af18-228acd80abb5.png)
Here the dialog box is not correctly sized. as the button is cropped.
![image](https://user-images.githubusercontent.com/60490474/229985334-67fe5487-3ccb-4aad-8440-6b7971d3ad0c.png)

These are glitched don't know for what reason. (I guess cause of x11) 👆

Forcing in floating mode fixes 
![image](https://user-images.githubusercontent.com/60490474/229985356-b62bacb4-84fe-46fd-8939-8e2248731843.png)

**Comment by NotAShelf** [comment]
I am able to replicate this. Upon simply resizing the window (by only touching the resize bind, not dragging), the popup gets back to normal.

**Comment by niksingh710** [comment]
seems to be fixed after recent updates.
