### ISSUE TITLE
Custom XKB layout not working as expected

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#1953]
Hey there,
Yesterday I installed Hyprland On my PPP, but I've been running into a keyboard issue that I did not experience on phosh (gnome).

I got my preferred keyboard [layout](https://codeberg.org/phalio/ppkb-layouts/commit/5bdbd65da92993bbc770d008b7d314c4758899cb) from [here](https://codeberg.org/phalio/ppkb-layouts/) and selected it via `xkb_layout=pp` and `xkb_variant=default-de-sprinkles` but weirdly enough, the entire keyboard does no longer output anything. I can still use the arrow keys, tab, enter and escape in fuzzel. Hyprland still picks up all keypresses with a binding.

You can find my log [here](https://chonkyrabbit.eu/files/_share/hypr.log)

Any idea what's going on?

**Comment by vaxerski** [comment]
those things are handled by xkb, and not hyprland. Does sway work?

**Comment by UltraBlackLinux** [comment]
I know it worked under gnome, and it interpreted these mappings properly.

Do you still want me to try that in sway?

**Comment by vaxerski** [comment]
yes

**Comment by UltraBlackLinux** [comment]
sway has the same issue yeah...

Why not gnome though?

**Comment by UltraBlackLinux** [comment]
It was in fact not wlroots. It was numlock, which acts weirdly with the PPKB driver.
