### ISSUE TITLE
Mouse isn't properly separated from keyboard focus

### ISSUE THREAD

**Issue by Vintodrimmer** [hyprwm/Hyprland#1954]
Focus sometimes switches to where the mouse currently is even if `follow_mouse = 3` is set. 

Steps to reproduce (Variant 1):
1. Have 2 monitors with a window open on each one
2. Place mouse cursor over the window on the right monitor and keyboard focus on the left monitor
3. Close the window on the left monitor
4. Focus is now on the right monitor

Expected outcome:
Focus stays on the left screen and I can open the next window there.

Noted outcome:
Focus switches to the right monitor and new window will be opened there.

Steps to reproduce (Variant 2):
1. Have multiple windows opened
2. Have mouse cursor and keyboard cursor on different windows
3. Launch Conky
4. Focus is now on the window with a cursor

Expected outcome:
Focus doesn't change.

Noted outcome:
Focus changes.

Steps to reproduce (Variant 3, the most annoying):
1. Have 2 monitors
2. Have windows open on monitor 1 but not on monitor 2
3. Move mouse over any of the windows on monitor 1
4. Switch between 2 empty workspaces on monitor 2
5. Focus jumps to the window under the cursor on monitor 1

Expected outcome:
I can spawn a window on the workspace I just opened on monitor 2.

Noted outcome:
Window spawns on monitor 1 unless I select the same open workspace on monitor 2 again.

**Comment by dlealmt** [comment]
@Vintodrimmer do you happen to have `no_cursor_warp = true` on your config?

**Comment by Vintodrimmer** [comment]
@dlealmt I do indeed.
Here's the entirety of my config file for work laptop: https://pastebin.pl/view/95d3558c

**Comment by dann-merlin** [comment]
I have this issue as well. `general:no_cursor_warps = true` and `input:follow_mouse = 3`.

**Comment by PatrickShaw** [comment]
In case anyone's having issues with `follow_mouse=0`:

You may want to set `float_switch_override_focus=0` as it defaults to `1` which follows mouse focus when moving the mouse from a floating to a tiled window. 

My personal expectation was that `follow_mouse=0` would fully prevent mouse movements from changing focus.

**Comment by aruhier** [comment]
I have the same issue, on the `main` branch (I can't tell if it happened before, I switched really recently to Hyprland), with:

```
input {
    follow_mouse = 2
    float_switch_override_focus = 0
    mouse_refocus = no
}

misc {
    mouse_move_focuses_monitor = no
}

general {
    layout = dwindle
    no_cursor_warps = yes
    no_focus_fallback = yes
}
```

**Comment by vaxerski** [comment]
var 1 and 2 should be fixed with b748b0734f27c978758c45b6e18520f7522b9d6f, does var 3 still occur?

**Comment by aruhier** [comment]
> var 1 and 2 should be fixed with [b748b07](https://github.com/hyprwm/Hyprland/commit/b748b0734f27c978758c45b6e18520f7522b9d6f), does var 3 still occur?

Thanks a lot!
1 and 2 are indeed fixed, but I can reproduce var 3 even with this patch.

**Comment by aruhier** [comment]
In fact, I can simplify var 3 for your debugging:

Context: 2 monitors [M1] and [M2]

1. M1 is on workspace 1, M2 on workspace 2;
2. Cursor is on M1, workspace 1 has a window opened. Focus is on M2 workspace 2;
3. Switch M2 to workspace 3 (new empty workspace);
4. Focus is now switched to M1 workspace 1 instead of staying on M2 workspace 3.

**Comment by aruhier** [comment]
Btw, if I can give here a quick review of b748b07: I think it works, but it also give me the feeling that it's a bit hackish and not super clear.

There's something I don't get with this all `// refocus on a new window if needed`: if it's the last window of a workspace/layer, why would you change the focus to somewhere else? If the option was set to sync the focus with the cursor, then the focus would have been on the closed window only if the cursor was on it, and in that case, I don't think that jumping to another monitor is wanted.

If this block is for a layer change, would it be better to simplify it to only make it about if the closed window is on a different layer than the the previous window?

**Comment by vaxerski** [comment]
never question my code as I am always correct, every "bug" is just a feature obviously

**Comment by aruhier** [comment]
@vaxerski: I sent #2320, by using the same logic as your commit. It fixes the variant 3 for me.

**Comment by aruhier** [comment]
I found another bug: doing a moveworkspacetomonitor also changes the focus and follows the cursor, I'm adding that to my PR.

**Comment by vaxerski** [comment]
closed cuz pr merged

**Comment by aruhier** [comment]
Linked to that, I also sent #2323.
