### ISSUE TITLE
Monitor grouping

### ISSUE THREAD

**Issue by imxyy1soope1** [hyprwm/Hyprland#1959]
# Feature

I want to add a feature that can **group** the monitors.
For example:
```
# hyprland.conf
workspace_groups = DP-2;HDMI-A-1, ..., ...
```
# Why I want to add this feature

With this, we can use two or more monitors as one workspace.

**Comment by vaxerski** [comment]
No, this is easily scriptable/pluginable, and has already been rejected a million times

**Comment by imxyy1soope1** [comment]
Oh, so sorry...
