### ISSUE TITLE
Can't change monitor when transform,1 (Rotation no worky)

### ISSUE THREAD

**Issue by H97-Git** [hyprwm/Hyprland#1961]
```
bind = SUPER_SHIFT, left, exec, hyprctl keyword monitor "DP-1,transform,1"
bind = SUPER_SHIFT, up, exec, hyprctl keyword monitor "DP-1,transform,0"
```
I have a dual monitor setup, when I rotato me screen with SUPER_SHIFT+Left for example my mouse is locked in whatever screen she was before rotation.

When rotated I can't invoke this or I can but nothing happens, locked in this single monitor : 
```
bind = $mainMod, Z, focusmonitor, l
bind = $mainMod, E, focusmonitor, r
```

I don't know if this is related but I can't do : 
`hyprctl keyword monitor "DP-1,1920x1080@144,0x0,1,transform,1"`

**Comment by vaxerski** [comment]
roatation changes the logical coordinates of the output, and you need to adjust its position accordingly.

How about reading the wiki?
![image](https://user-images.githubusercontent.com/43317083/230107925-81e1eadc-449a-4ee5-b0a8-981c07dae9c5.png)
