### ISSUE TITLE
Hyprland crashes in an unexpected way

### ISSUE THREAD

**Issue by ElJeffe** [hyprwm/Hyprland#1962]
Since https://github.com/hyprwm/Hyprland/commit/eea99abc49c964ed42f059d43c06db41a90809c1, some settings in hyprland.conf seems to cause hyprland to exit. 
What happened:
The screen also seems to be broken. 
What was expected:
Some animation with eggs

**Comment by vaxerski** [comment]
ah yes, an option that literally says "manual crash" should not crash. right.
