### ISSUE TITLE
`movecurrentworkspacetomonitor` is broken with special workspaces

### ISSUE THREAD

**Issue by joelkoen** [hyprwm/Hyprland#1963]
I'm trying to setup hyprland for the first time and I'm now configuring keybinds
for my two monitors (laptop screen + HDMI) after setting up special workspaces.
Using `movecurrentworkspacetomonitor` seems to be broken with special
workspaces:

1. Close all workspaces so that there is only a special workspace and a regular
   workspace on one monitor. Your second monitor is empty.

   ```
   workspace ID 1 (1) on monitor eDP-1:
   	windows: 1
   	hasfullscreen: 0
   	lastwindow: 0x2b09770
   	lastwindowtitle: hyprctl workspaces ~

   workspace ID 2 (2) on monitor HDMI-A-1:
   	windows: 0
   	hasfullscreen: 0
   	lastwindow: 0x0
   	lastwindowtitle:

   workspace ID -99 (special:p) on monitor eDP-1:
   	windows: 1
   	hasfullscreen: 0
   	lastwindow: 0x2aff520
   	lastwindowtitle: joel.kdbx [Locked] - KeePassXC
   ```

2. Move workspace 1 to your second monitor.
3. Instead of moving the workspace, hyprland gets very confused:
   - `hyprctl workspaces` says that the workspace has been moved, when really
     the windows are still on my laptop screen (eDP-1):

     ```
      workspace ID 1 (1) on monitor HDMI-A-1:
      	windows: 1
      	hasfullscreen: 0
      	lastwindow: 0x2b09770
      	lastwindowtitle: hyprctl workspaces ~

      workspace ID -99 (special:p) on monitor eDP-1:
      	windows: 1
      	hasfullscreen: 0
      	lastwindow: 0x2aff520
      	lastwindowtitle: joel.kdbx [Locked] - KeePassXC
     ```

   - focusing my second monitor and opening a new terminal causes it to be
     opened on my laptop screen
   - switching to a different workspace causes workspace 1 to completely
     disappear - it shows up in `hyprctl` but I cannot switch to it

4. If I repeat steps 1 and 2 without any special workspaces open things work as
   expected.

Could be related to https://github.com/hyprwm/Hyprland/issues/1747

**Comment by ettancos** [comment]
I just did this as a quick workaround, not sure if i have the capacity to think about all the cases, but solved my problem

```
diff --git i/src/Compositor.cpp w/src/Compositor.cpp
index a9b5cba5..c4de054f 100644
--- i/src/Compositor.cpp
+++ w/src/Compositor.cpp
@@ -1864,6 +1864,9 @@ void CCompositor::moveWorkspaceToMonitor(CWorkspace* pWorkspace, CMonitor* pMoni
     // fix old mon
     int nextWorkspaceOnMonitorID = -1;
     for (auto& w : m_vWorkspaces) {
+        if (w->m_bIsSpecialWorkspace)
+            continue;
+
         if (w->m_iMonitorID == POLDMON->ID && w->m_iID != pWorkspace->m_iID) {
             nextWorkspaceOnMonitorID = w->m_iID;
             break;
diff --git i/subprojects/wlroots w/subprojects/wlroots
--- i/subprojects/wlroots
+++ w/subprojects/wlroots
@@ -1 +1 @@
-Subproject commit 7abda952d0000b72d240fe1d41457b9288f0b6e5
+Subproject commit 7abda952d0000b72d240fe1d41457b9288f0b6e5-dirty
```

**Comment by vaxerski** [comment]
@ettancos applied your fix to head

**Comment by joelkoen** [comment]
Patch works, thank you!
