### ISSUE TITLE
Crash on exit with firefox open

### ISSUE THREAD

**Issue by Duckonaut** [hyprwm/Hyprland#1965]
Hyprland crashes on exit if there's a firefox window open. I haven't tested other big graphical programs individually, but with just alacritty for example, this doesn't happen, while with just firefox, it does.

[hyprlandCrashReport408723.txt](https://github.com/hyprwm/Hyprland/files/11170612/hyprlandCrashReport408723.txt)

**Comment by vaxerski** [comment]
should be fixed with c9f7afbf782304fef1ca629a278ce8ef35fc1e3d

**Comment by Duckonaut** [comment]
Yup, fixed!
