### ISSUE TITLE
Missing a modifier: META is not a valid mod, and can't be replaced by Mod1 +Mod4 either

### ISSUE THREAD

**Issue by csdvrx** [hyprwm/Hyprland#1966]
If the keyboard has a Meta key, it's a valid modifier.

If the keyboard doesn't have a meta key but if mapping one, for example with `kb_options = ... ctrl:lctrl_meta`,  the left control key is then mapped to Meta_L, which becomes a valid modifier: we can see in wev that Meta_L sets both Mod1 and Mod4

However, META is not a valid modifier for hyprland: adding the following to hyprland.conf causes an error:

    bindr=META,Meta_L,exec, ...

Binding actions to Meta + key don't work either, for ex Meta+a :

    bind=MOD1 MOD4,a,exec, ...

Suggestion: adding META as a valid modifier to allow shortcut using the Meta modifier, eventually adding Mod1 and Mod4 as valid aliases

**Comment by vaxerski** [comment]
hyprland implements all valid modkeys from the wayland protocol that wlroots provides, giving this list:
![image](https://user-images.githubusercontent.com/43317083/230386234-40c3d9df-41c1-47ab-91bb-c07520aee5ce.png)

MOD1 does not exist.

**Comment by csdvrx** [comment]
Alt is an alias of Mod1 (like how SUPER is an lias of Mod4), as can be inferred by the list starting with Mod2 otherwise :)

Meta often means Mod1 + Mod4

If you need extra evidence, try the line above with wev:

    [14:     wl_keyboard] key: serial: 355; time: 152980; key: 37; state: 1 (pressed)
                      sym: Meta_L       (65511), utf8: ''
    [14:     wl_keyboard] modifiers: serial: 356; group: 0
                      depressed: 00000048: Mod1 Mod4
                      latched: 00000000
                      locked: 00000000

You can see in depressed both Mod1 (which therefore exists) and Mod4

**Comment by vaxerski** [comment]
I mean, cool, hyprland gets the names from wlroots and uses those. It's clear then that you should use alt super? Why is this an issue then?

**Comment by csdvrx** [comment]
This is further documented on https://unix.stackexchange.com/questions/119212/mod-meta-super-keys and as explained on https://www.emacswiki.org/emacs/MetaKeyProblems : 

   This is because Meta and Alt are different and you can bind things to M-a and to A-a and they should not be confused. But in the case where there is no Meta binding, it’s preferable to treat Alt as Meta since Alt bindings are much more rare than Meta bindings in Emacs.

Here Meta is a virtual modifier, which you can also see listed with `grep -i meta /usr/share/X11/xkb/symbols/pc`

    key <LALT> {[  Alt_L,  Meta_L  ]};
    key <RALT> {[  Alt_R,  Meta_R  ]};
    modifier_map Mod1    { Alt_L, Alt_R, Meta_L, Meta_R };
    key <META> {[  NoSymbol, Meta_L  ]};
    modifier_map Mod1  { <META> };

Mapping a key to Meta will with xkb in hyprland.conf with `kb_options = ctrl:lctrl_meta` will make it toggle both Mod1 and Mod4 which is why I suggest defining META as Mod1 + Mod4 instead of currently having to specify: 

    bind = ALT SUPER, a, exec ...

or:

    bind = ALT MOD4, a, exec ...

At least having MOD1 as an alias for ALT would be slightly more intuitive

**Comment by vaxerski** [comment]
```
$MOD1 = ALT
```
?

```
$META = ALTSUPER
```
?

**Comment by vaxerski** [comment]
added mod1 in 80650b67225660d557e6027b1fb8fb17f0564eec

I consider this done, closing
