### ISSUE TITLE
Suggestion: add NONE for the modifiers

### ISSUE THREAD

**Issue by csdvrx** [hyprwm/Hyprland#1968]
When mapping key with ydotool, previous modifiers aren't cleared by ydotool.

For example, the following maps Caps alone to Esc:

    input {
      kb_options = shift:breaks_caps, caps:ctrl_modifier, lv3:ralt_switch_multikey
    }
    bindr=CONTROL,66,exec, YDOTOOL_SOCKET=/run/user/1000/.ydotool_socket ydotool key 1:1 1:0

However, it's then impossible to bind the Esc key proper to anything, because pressing Caps will send the linux input key 1 == keycode 9 for hyprland, 

For example, both Caps and Esc will start foot if adding:

    bindr=,code:9, exec, foot

However, Caps alone could be used to send Esc in vim, and Esc alone could be mapped to some workspace action inhibited when modifiers are set.

To support that usecase and to help debugging complex bind/bindr mappings, it would be nice to add NONE to the acceptable modifiers: it would inhibit a bind if any modifiers are already set, for example to start foot with the Esc key proper while letting Caps send Esc for vim

    bindr=NONE,code:9, exec, foot

It could be completed by other negative matches: here, NOTCONTROL could do the same job.

**Comment by vaxerski** [comment]
that's already how it works, it's just that the `key` event precedes the modifier update.

**Comment by csdvrx** [comment]
uh, so any idea how to do that in the example above, for example by forcing a modifier update by ydotool? Sending a key up event in the ydotool sequence isn't enough.

unlike xdotool, ydotool doesn't support --clearmodifiers and I don't know how to add that :(

**Comment by izmyname** [comment]
> that's already how it works, it's just that the `key` event precedes the modifier update.

The response was provided - prolly, close the issue?
