### ISSUE TITLE
Some xwayland applications seem to have broken dragging functionality

### ISSUE THREAD

**Issue by devil-may-c0de** [hyprwm/Hyprland#1969]
STEPS TO REPRODUCE:
- Open Ardour, create a project, and drag a plugin in a track mixer
- Open Yoshimi, attempt to adjust a knob

EXPECTED OUTCOME:
- Ardour's plugin is dragged without issue
- Yoshimi's knobs are adjusted without issue

NOTED OUTCOME:
- Ardour's plugin seems to gain, and then lose focus, resetting the position of the plugin
- Yoshimi's knobs seem to gain, and then lose focus, leading to a very small adjustment of the knob

possibly related to #1120 and #1083

**Comment by vaxerski** [comment]
make sure you're on -git

find the class of the window that is opened when you drag

use the `nofocus` rule on it

should fix it.

For finding the class: check the log, and search for `matching`

**Comment by devil-may-c0de** [comment]
The window class of the draggable plugin seems to be the same as Ardour's window class. When applying the nofocus rule, it unfocuses all Ardour windows, though the plugin drags correctly since the ardour window spawned before the rule was made.

**Comment by vaxerski** [comment]
try matching with v2 then, adding a title and possibly a floating: param

**Comment by devil-may-c0de** [comment]
I was able to solve my problem with ardour by also including the title of the plugin window. The yoshimi knob however had a window class of null so a rule could not be made for that.

**Comment by NoEnd-yt** [comment]
This fixes the issue but if the windowrule is active before opening Ardour, the window can't be interacted with.

**Comment by iUnstable0** [comment]
yeah same, for me its WebStorm though (jetbrains)

**Comment by devil-may-c0de** [comment]
I have solved this with what I consider a fairly elegant window rule. 

`windowrulev2=noinitialfocus,xwayland:1`

tested on both ardour and yoshimi and works without issue. there could potentially be some problems with this rule, but I am satisfied with this.

**Comment by monteship** [comment]
```
windowrulev2 = float, class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = noinitialfocus, opacity 0.9 0.9, class:^(jetbrains-.*)
```
this fix all dragging issues

**Comment by mikboc** [comment]
Hyprland 0.53+
---

I updated to Hyprland 0.53 today and the rules posted by @monteship no longer works because `windowrulev2` seems to be deprecated. You must migrate to the new syntax
```
windowrule = float on, match:class ^(jetbrains-.*), match:title ^(win.*)
windowrule = no_initial_focus on, opacity 0.9 0.9, match:class ^(jetbrains-.*)
```
