### ISSUE TITLE
lock: swipe movements still working

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1970]
- start `swaylock -c ffffff00` (so you can see through)
- swipe left/right to switch workspace
- it works, while it should not

**Comment by tchofy** [comment]
I know this is going to be asked, so I went ahead and tested it on sway. Same behavior for me.

**Comment by vaxerski** [comment]
sway has swipe gestures???

anyways fixed in 569eaff04c1da70dd06f8a6d80ea9780667825c0

**Comment by tchofy** [comment]
Yep. I had never touched sway before (and nvidia doesn't help), so I had to look around, and at first the community was using liibinput-gestures, but was later added in https://github.com/swaywm/sway/commit/cab2189aa64d04ba79dc2cbf19400435b47cdbd2

**Comment by primalmotion** [comment]
swipping while locked is still working even after 569eaff04c1da70dd06f8a6d80ea9780667825c0

**Comment by tchofy** [comment]
https://github.com/hyprwm/Hyprland/commit/569eaff04c1da70dd06f8a6d80ea9780667825c0 worked for me.

**Comment by vaxerski** [comment]
@primalmotion what lockscreen app? this patch would only work with ext-session-lock

**Comment by primalmotion** [comment]
I use swaylock-effects. Dang it's far beyond master. I'll retry with upstream

**Comment by vaxerski** [comment]
there are a kjhillion swaylock-effects forks iirc. One of them is pretty up to date

**Comment by primalmotion** [comment]
ok confirmed it works well with a more up to date fork of swaylock effects. Thanks!
