### ISSUE TITLE
any methods to start a new window when running program under cmdline?

### ISSUE THREAD

**Issue by yfaimisaka** [hyprwm/Hyprland#1978]
When running a program on terminal with command line, such as `google-chrome-stable`, found that chrome opened `on the terminal window directly`. Is there any method to `open the chrome(or others) on a new window`, thus able to see the output of the command when running?
(Sorry for loose language :(

**Comment by vaxerski** [comment]
do you have window swallowing enabled? that'd be expected behavior then.

**Comment by yfaimisaka** [comment]
> do you have window swallowing enabled? that'd be expected behavior then.

thanks. sorry for my careless. :smile: i will close this issue soon
