### ISSUE TITLE
Hyprland Crash on rapid disconnection and reconnection of input device. 

### ISSUE THREAD

**Issue by taylor85345** [hyprwm/Hyprland#198]
I've encountered a reproducible crash when rapidly disconnecting and reconnecting seemingly any input device. For example unplugging and immediately reinserting a USB keyboard, or turning a Bluetooth connected wireless mouse off and on again.

[hyprland.log](https://github.com/vaxerski/Hyprland/files/8886270/hyprland.log)

[hyprland_coredump_debug.txt](https://github.com/vaxerski/Hyprland/files/8886272/hyprland_coredump_debug.txt)

EDIT: I have determined that this does not occur every time, or equally with all devices. Turning my bluetooth mouse off and on took 8-12 cycles to trigger a crash, while turning on my dying Steam Controller immediately after it shut off crashed Hyprland every time.

**Comment by vaxerski** [comment]
check if fixed with b25bafda0834f58acf50f472bfa0534f5714f30a

**Comment by taylor85345** [comment]
Not resolved, unfortunately

**Comment by vaxerski** [comment]
give me a debug coredump then please, it probably crashes elsewhere

**Comment by taylor85345** [comment]
[hyprland_coredump_debug.txt](https://github.com/hyprwm/Hyprland/files/8984235/hyprland_coredump_debug.txt)

**Comment by vaxerski** [comment]
check with b46f45befab6e2aa6daba76ec04cec4286eec56b

**Comment by taylor85345** [comment]
Seems to be resolved.
