### ISSUE TITLE
Commit 24ace03 seems to break mouse movement screen damage

### ISSUE THREAD

**Issue by tchofy** [hyprwm/Hyprland#1981]
Might be Nvidia specific, or `WLR_NO_HARDWARE_CURSORS=1` specific, but 24ace0378083fef23735ba426f8af3180e67994f causes mouse movement to be laggy unless the cursor is moving over something else causing damage. Physical position is properly tracked according to `wev`.

Disabling debug:damage_tracking "fixes" it, and while I do hate my gpu, I don't hate it _that_ much.

**Comment by vaxerski** [comment]
should be fixed with cd1b982b2a53a526eb3b4e3c53787038e18f993d
