### ISSUE TITLE
Master layout dispatchers not working

### ISSUE THREAD

**Issue by jfinmaniv** [hyprwm/Hyprland#1985]
Dispatchers specific to the [master layout](https://wiki.hyprland.org/Configuring/Master-Layout/) seem to be not working. 
#### Reproduce

Include in config: `bind = $mainMod, I, swapwithmaster auto`.

#### Expected Result

Press `$mainMod+I` to swap the current window with master.

#### Noted Outcome

Error message:

> Invalid dispatcher, requested "swapwithmaster auto" does not exist.

This is true for all master layout dispatchers. `swapnext` happens to work but I notice this dispatcher is included in the [non-layout specific list](https://wiki.hyprland.org/Configuring/Dispatchers/) and has a slightly different syntax than the one described in the master layout list (has a possible `prev` argument separated by a comma). Have the master layout dispatchers been deprecated? I am running version 0.23.0beta-4 in the [Arch repositories](https://archlinux.org/packages/?name=hyprland).

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/230685396-da9dd71a-79b9-44c8-92a3-b82f751c670e.png)


![image](https://user-images.githubusercontent.com/43317083/230685384-4966be94-b95a-4c76-9dc2-002ab50dcac8.png)

I will not make yet another tirade about how y'all just can't read.

**Comment by nrdxp** [comment]
I have this bind set:
```
bind = $mainMod, M, layoutmsg, swapwithmaster master
```
Yet hitting the key doesn't actually swap the master, so I think this might actually be a legitimate bug (I copy pasted the example from the docs to rule out typo.
