### ISSUE TITLE
Window rule tile does not work

### ISSUE THREAD

**Issue by MisterOryon** [hyprwm/Hyprland#1987]
I have a problem I have a window that at each launch starts floating mode and does not want to become a tile while in my conf file I have added the following rule:
```
windowrule = tile, title:^(JetBrains Toolbox)$
```
I think it’s a bug in Hyprland.
I think for all applications that are not run in Wayland like WebStorm  or JetBrains Toolbox for example starts in floating mode.
Maybe my Hyprland configuration is wrong. If that is the case, I apologize for the inconvenience.

OS : Arch Linux
Kernel: Linux 6.2.9-zen1-1-zen
Wayland: 1.22.0-1
xorg-xwayland: 23.1.1-1
Hyprland: 0.23.0beta-4

**Comment by vaxerski** [comment]
it does very much work, as I've replied before

> if a window "refuses to tile" it means it sets its max size as something that is smaller than the tiled size, in which case Hyprland will refuse to tile it for obvious reasons.

**Comment by MisterOryon** [comment]
Thank you for your feedback 🙂.

Sorry about the duplicate question. I thought anyone not see my message in the other issues because it had been closed for several weeks.
