### ISSUE TITLE
Hyprctl exec application in specific workspace

### ISSUE THREAD

**Issue by Laeri** [hyprwm/Hyprland#1989]
Hi there, I am not sure if this is a bug or I am doing it wrong but previously I had a script
called in `exec-once` that opened multiple applications at startup in specific workspaces but
now this does not seem to be working anymore for all execs. Some windows are opened in workspace 1 even though I specify they should be opened in another workspace.

Not sure if I am doing something wrong or if there is a problem:

I use the `hyrpland-git` package from the aur
`hyprctl version` returns following message:

```
Hyprland, built from branch main at commit 41f7736c8521162cb3ea5f3c003e0643c1bcf616dirty (config: default manual animations to false).
flags: (if any)
```

I startup the applications like this:
```
hyprctl dispatch exec [workspace 1 silent] 'kitty tmux new-session -A -s main'
sleep 1
hyprctl dispatch exec [workspace 2 silent] firefox
hyprctl dispatch exec [workspace 3 silent] idea.sh
hyprctl dispatch exec [workspace 4 silent] firefox 
hyprctl dispatch exec [workspace 6 silent] obsidian
```

The interesting thing is that applications in workspace 4 and 6 are correctly assigned but not firefox or idea in workspaces 2 and 3. For the idea application I even have a window rule configured that should contain it within workspace 3. Also when I call the dispatch manually for firefox it is still opened within workspace 1.

[hyprland.zip](https://github.com/hyprwm/Hyprland/files/11182685/hyprland.zip)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/230720104-3baa6ed0-ead5-4577-9b44-58bd7df80e9d.png)

ref: https://wiki.hyprland.org/Configuring/Dispatchers/#executing-with-rules
