### ISSUE TITLE
Hyprland crash when tacking a screenshot with grim and useing 10bit color.

### ISSUE THREAD

**Issue by Slimemaster0** [hyprwm/Hyprland#1993]
[hyprlandCrashReport789.txt](https://github.com/hyprwm/Hyprland/files/11183261/hyprlandCrashReport789.txt)

Hyprland version: git
Distro: Archlinux

Steps to repreduce:
1: Enable 10bit color in hyprland config
2: run grim

**Comment by vaxerski** [comment]
should be fixed in 31963f823b12d79727c98ab51bd64f96cc0433e0, check

**Comment by Slimemaster0** [comment]
Hyprland does not crash anymore, bot screencopy fails.

**Comment by vaxerski** [comment]
did it use to work?

**Comment by romanstingler** [comment]
related to https://github.com/hyprwm/contrib/issues/93
