### ISSUE TITLE
Hyprland straight up crashes on using any icons for hyprctl notify

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#1997]
CASE-1
`hyprctl notify -1 10000 "rgb(ff1ea3)" "Test123"`
Expectation: A notification is sent with no icons
Actual Result: A notification is sent with no icon

CASE-2
`hyprctl notify -2 10000 "rgb(ff1ea3)" "Test123"`
Expectation: A notification is sent with _info_ icon
Actual Result: :P

Tested on [commit: (textInput: don't double destroy TI)](https://github.com/hyprwm/Hyprland/commit/86852cdc78b833ae405b6161f639424787a825e4)

**Comment by vaxerski** [comment]
idiot it's 1 or 2 not -1 -2, ugh havent added a sanity check for negatives

**Comment by vaxerski** [comment]
fixed in b32af6ebfb5ea3ffc16cbf07a6cdbaa6c486ba58

**Comment by System-x64** [comment]
> idiot it's 1 or 2 not -1 -2, ugh havent added a sanity check for negatives

Ahh never thought of that since many terminal thingys use -...-Syu, -l,-h thank you anyways!
