### ISSUE TITLE
firefox crashes when trying to launch outside of safe mode

### ISSUE THREAD

**Issue by Sivecano** [hyprwm/Hyprland#1998]
steps to reproduce:
* use hyprland
* open firefox version 111
* firefox crashes

should be a hyprland issue since the crash happens in a render thread and does not occur on both gnome (with wayland) or xorg.
* this was tested by cloning and building the most recent git version
* this happens even under fresh profiles and should thus not be related to my settings
* this didn't happen yesterday so it was probably introduced in the most recent release  (v 0.24.0)

**Comment by vaxerski** [comment]
well brilliant, it doesnt crash for me. Anything else or should I close this? No logs or anything.

Have you tested on sway-git? Gnome shares a completely different base and testing on xorg makes no sense.

**Comment by Sivecano** [comment]
will do, might be an issue with my setup. will close if I don't find anything.

**Comment by Duckonaut** [comment]
potentially related: [this reddit post](https://www.reddit.com/r/archlinux/comments/12eoj2b/wayland12201_update_causes_a_lot_of_crashes/)

**Comment by Sivecano** [comment]
> potentially related: [this reddit post](https://www.reddit.com/r/archlinux/comments/12eoj2b/wayland12201_update_causes_a_lot_of_crashes/)

yeah, that was the issue. 
sorry for wasting your time with this.
thanks for the cool work you're doing.
