### ISSUE TITLE
Move to empty workspace on next monitor with `movefocus` and `movewindow`

### ISSUE THREAD

**Issue by happenslol** [hyprwm/Hyprland#1999]
I've just moved to hyprland from sway, and I've realized that my workflow pretty much only consists of moving focus/windows in directions. In sway, it was possible to move to an empty workspace with a direction move, and I could also move a window to the next (empty) monitor by moving it in that direction.

In hyprland, it seems like moving the focus to an empty workspace with a direction is not possible at all, and moving a window is only possible if another window is on that workspace already - and the windows will be swapped instead of actually moving the window to the workspace, next to the window already there.

I'm interested in working on this feature myself. Is this feature something you would be open to?

**Comment by vaxerski** [comment]
It's been on my radar to fixup `movewindow` for a while, because atm it's not a `move`, it's a `swap`

the `movefocus` thing would be trivial to implement yes

**Comment by happenslol** [comment]
Alright, got the development environment set up. Those makefiles need cleaning up sometime, that was a real journey :sweat_smile: Any idea how I might go about testing multi-screen features in a nested window? Restarting my entire WM every time I want to test a change seems like a huge timesink :thinking:

**Comment by vaxerski** [comment]
run `hyprctl output create auto` in a nest
