### ISSUE TITLE
Unable to (entire screen, only windows) screenshare Discord/OBS

### ISSUE THREAD

**Issue by emlllano** [hyprwm/Hyprland#2000]
Hello there, I've been unable to screen share the entire screen either on discord/OBS.
Sorry for any inconvenience,  I'm new to hyprland and diy compositors/wms.
also i use a NVIDIA gtx 1070, i of course followed the screen sharing guide but couldn't get anything done but sharing separate windows using hyprland.

Here is the output of systemctl --user status pipewire wireplumber:

[outputpipe.md](https://github.com/hyprwm/Hyprland/files/11185408/outputpipe.md)

BUT here is the output of systemctl --user status xdg-desktop-portal-hyprland:

[outputxdg.md](https://github.com/hyprwm/Hyprland/files/11185410/outputxdg.md)

Also, 
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
env =   LIBVA_DRIVER_NAME, nvidia
env =   XDG_SESSION_TYPE, wayland...etc...

are all in my config file.

Considering all that the error seems to be the following one which i couldn't  fix myself:
"  wireplumber[1741]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NameHasNoOwner "

i also don't know if its a bug whatsoever 

Thank you for any answer,
and again sorry for any inconvenience :)

**Comment by vaxerski** [comment]
Nvidia currently has screensharing broken, you'll need to wait for whoever maintains nvidia patches to update them.

It's nvidia's fault, not Hyprland's.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11201584/patch.txt)

This patch might fix the issue (nvidia, 8 bit only)

**Comment by emrakyz** [comment]
I use Hyprland on Gentoo with thegreatmcpain's ebuild. I have latest git versions of Hyprland, XDGDPH and the latest Nvidia Drivers. I have no issue with screenshots. The ebuild uses this patch:
[Nvidia Patch](https://raw.githubusercontent.com/TheGreatMcPain/TheGreatMcPain-overlay/02a503cfbebc63266bb22459fa0ce85a4c6d5c50/gui-wm/hyprland/files/0001-Workaround-Screencast-for-Nvidia.patch)

**Comment by liamrahum** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/11201584/patch.txt)
> 
> This patch might fix the issue (nvidia, 8 bit only)

Hey, can I ask where should I put this patch?
