### ISSUE TITLE
`hyprland#nixosModule` incompatible with `nixos-unstable`

### ISSUE THREAD

**Issue by Kiskae** [hyprwm/Hyprland#2001]
The nixos module added in https://github.com/NixOS/nixpkgs/pull/221730 creates conflicting options with the `nixosModules.default` module.

```console
error: The option `programs.hyprland.enable' in `/nix/store/qyyw6dd6lqlhz3cqap31d071cbyh34bf-source/nixos/modules/programs/hyprland.nix' is already declared in `/nix/store/qyyw6dd6lqlhz3cqap31d071cbyh34bf-source/flake.nix'.
```

I've been able to restore equivalent functionality by just applying the overlay of the hyprland flake instead of the nixos module.

```nix
{
  nixpkgs.overlays = [ inputs.hyprland.overlays.default ];
}
```

Ping @fufexan

**Comment by fufexan** [comment]
If you wanna use the Flake NixOS module, you can disable the Nixpkgs one with `disabledModules = ["programs/hyprland.nix"];`.

**Comment by fufexan** [comment]
Also it's not a bug, this is intended behaviour. Same options provided by either module. Your choice.

I'll document the module disabling in the wiki.

**Comment by Kiskae** [comment]
Wouldn't it be possible to include the disabling statement in the module provided by the flake? I'm not sure what happens if a disabled module doesn't exist

**Comment by fufexan** [comment]
Sure, I'll try testing it as I don't have the new Nixpkgs yet.

**Comment by fufexan** [comment]
@Kiskae can you try this PR? I've added the disable statement there.
- https://github.com/hyprwm/Hyprland/pull/1957

**Comment by Kiskae** [comment]
No errors about option declarations, but getting this instead:

```console
error: attribute 'hyprland' missing

       at /nix/store/3k5cyrwrkw0g5qapw5silxbn3yz3z3ik-source/nix/module.nix:10:28:

            9|
           10|   defaultHyprlandPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.default.override {
             |                            ^
           11|     enableXWayland = cfg.xwayland.enable;
(use '--show-trace' to show detailed location information)
```

**Comment by fufexan** [comment]
Looks like you don't have the hyprland input. You can set the `package` option in that case.

**Comment by Kiskae** [comment]
> Looks like you don't have the hyprland input. You can set the `package` option in that case.

I'm using the `hyprland.nixosModules.default` flake attribute which gets its inputs from https://github.com/fufexan/Hyprland/blob/1f14070f50e024339da3a1de329c952f00efa204/flake.nix#L131- there is no `hyprland` attribute on the `inputs` set for the hyprland flake itself.
