### ISSUE TITLE
Chromium extension windows appear very narrow

### ISSUE THREAD

**Issue by mrkajetanp** [hyprwm/Hyprland#2003]
I'm experiencing a strange issue with the windows created by chrome/chromium extensions. Whenever I try clicking on them they appear very narrow and not usable. I did not have the same issue with Gnome on Wayland and Chromium is running in Wayland mode. I'm not sure if it's directly related to this project but asking here in case someone has seen this before..
Screenshot below.

![20230409_13h53m42s_grim](https://user-images.githubusercontent.com/25405190/230773889-4b9b1f9c-dd32-4d84-9cde-f5f9ba90dafa.png)

**Comment by vaxerski** [comment]
check on sway-git

**Comment by adwaymalhotra** [comment]
I face the same issue on Hyprland.

The extension windows are fine in chrome on sway.

**Comment by mrkajetanp** [comment]
Thanks for checking on sway, do you use normal chrome or some chromium variant?

**Comment by adwaymalhotra** [comment]
It's normal chrome. I initially suspected it may be a chrome issue but checked on sway after I saw this bug.

The issue has been there for at least a few months on Hyprland. Can't say if the issue existed on sway in the past.

**Comment by vaxerski** [comment]
would help if I could reproduce this

![image](https://user-images.githubusercontent.com/43317083/231561592-de55aa99-b87a-4711-893a-0ed6960bef50.png)

**Comment by mrkajetanp** [comment]
Interesting, are you running chrome in Wayland mode or  through XWayland? Which version is it?

**Comment by vaxerski** [comment]
wayland, newest from arch repos, chromium

**Comment by adwaymalhotra** [comment]
Interestingly, it doesn't happen when the window is fullscreen using `bind=SUPERALT,F,fullscreen,1` on the external monitor(s). 

On the laptop screen, it happens every time: fullscreen or not.

**Comment by Schmensch** [comment]
I'm having the same issue on Brave with `ozone-platform-hint` set to `wayland` in chrome://flags, but only when brave is maximised.

- GNOME 44.2.1
- NixOS unstable
- Brave 1.52.122 / based on Chromium 114.0

**Comment by networkException** [comment]
This is https://bugs.chromium.org/p/chromium/issues/detail?id=1282790

**Comment by Schmensch** [comment]
Thanks!

**Comment by shubh402** [comment]
any update?

**Comment by Vogete** [comment]
So this happened to me too, and I finally figured out a workaround for it. So it always happens to me when my leftmost monitor's position in hyprland is not starting at 0:0. As soon as I moved it there (I used wdisplays for a quick fix, but I assume it works with hyprland config too), the extension popups appeared normal again. If I position it back to something more right on the plane, it becomes narrow again.

This might not be a proper fix, but at least it made my extensions usable again.

**Comment by fvelotti** [comment]
> So this happened to me too, and I finally figured out a workaround for it. So it always happens to me when my leftmost monitor's position in hyprland is not starting at 0:0. As soon as I moved it to 0:0 and re-positioned all other monitors next to it (I used wdisplays for a quick fix, but I assume it works with hyprland config too), the extension popups appeared normal again. If I position it back to something more right on the plane, it becomes narrow again.
> 
> This might not be a proper fix, but at least it made my extensions usable again.

This is working! as far as there is a monitor active starting at x=0 then the extensions show correctly. Thank you very much!

**Comment by jbhardman** [comment]
Aha, that 0x0 thing fixed it for me. I didn't even realize. I had configured my monitors so that when I did plug in to my monitor, it was at 0x0 and my laptop screen started after it at 2560x0. But most of the time I'm not plugged in. Since hyprland just acted normal without the first monitor, I didn't even imagine that my config of 2560x0 was a problem.

Now to figure out how to set variable monitor setups based on what is present...

**Comment by Alxandr** [comment]
> Aha, that 0x0 thing fixed it for me. I didn't even realize. I had configured my monitors so that when I did plug in to my monitor, it was at 0x0 and my laptop screen started after it at 2560x0. But most of the time I'm not plugged in. Since hyprland just acted normal without the first monitor, I didn't even imagine that my config of 2560x0 was a problem.
> 
> Now to figure out how to set variable monitor setups based on what is present...

Exact same thing I had. Do let me know if you find a good solution.

**Comment by Magicking** [comment]
This situation happens, I fixed it by setting `0x0` to the monitor eDP-1 (I obtained from `hyperctl monitors`) settings which previously was at `2160x0` (due to usage of a tool to adjust another screen) 
![eDP-1 buggy](https://github.com/hyprwm/Hyprland/assets/284088/303b71c0-5109-423f-a518-aa3a91d302cb)

I fixed the settings eDP-1 `0x0` directly in `.config/hypr/monitors.conf`

![eDP-1 non-buggy](https://github.com/hyprwm/Hyprland/assets/284088/12efb072-9d09-4671-82ac-e2a1549dd891)

**Comment by vaxerski** [comment]
sounds like that one qt bug back in the day. I very much doubt this is a hyprland issue.

**Comment by izmyname** [comment]
Is this still actual?

**Comment by LucStr** [comment]
I used to very consistently get this issue. I haven't changed my setup and just tried to recreate it based on my description and cannot anymore. Therefore I think this can be closed.
