### ISSUE TITLE
nofocus layerrule

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/Hyprland#2005]
**precondition**

- hyprland v > 0.23
- any bars with layershell (i.e. [eww](https://github.com/elkowar/eww))
- have `:focusable false` in eww yuck config

**str**

1. open any window
2. click on bar

**exp**

- focus kept on window

**act**

- bar gets focus

[df54ab4](https://github.com/hyprwm/Hyprland/commit/df54ab40ceb6e7f74844e83d3f55739accd349cc) "allows" focus, but what if it is not desired by default. It's probably achievable with some dispatchers called on i.e. workspaces buttons clicks, but the whole bar has some other stuff :-P
Though having something like `layerrule = nofocus,<namespace>`  would be great
Disabling this internally in eww doesn't work

**Comment by vaxerski** [comment]
focusable probably refers to the keyboard focus, so this is expected.

https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-layer-shell-unstable-v1.xml#L278-L280

Hyprland ignores this though, so that's something that could be thought of.

**Comment by bvr-yr** [comment]
yep, sure this is expected, but how i can deal with that? another workaround is just setting eww layer to `bottom`, but this ruins tooltips, as they render behind windows, obviously, and there's no options to change it, sadly.
btw it concerns waybar too, so maybe it is just about my habits of clicking wspace on the bar and typing, sure there are ways to live with that, but there are so much great improvements in 0.24 release, no way to exchange ones for others.
It just seems quite an obvious thingy, dunno whether it is hard implementable

**Comment by vaxerski** [comment]
fixed in 4ae784dc5374092734a6ed30ba56011e50c902d6

**Comment by bvr-yr** [comment]
**confirmed:** done
