### ISSUE TITLE
misc:vfr not working in v0.24

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/Hyprland#2006]
**precondition**

- hyprland v > 0.23
- `hyprctl getoption misc:vfr` reports `1`

**str**

- `hyprctl keyword debug:overlay 1`
- or check `Hyprland` process load in i.e htop
- do nothing

**exp**

- fps < 10
- load < 1%

**act**

- fps ~60
- load > 1%

This happened just after package upgrade to `v0.24.0` on arch. First i thought it might be related to mesa and wayland upgrades, cause all updated at once, but just downgrading hyprland to `v0.23.0beta` confirmed this behavior.

Let me know what hard/software info do you need, cause since this issue hasn't been reported i assume it's related to my machine

**Comment by vaxerski** [comment]
https://user-images.githubusercontent.com/43317083/230786196-9f291af0-92bf-4094-bcb7-f19404e791a2.mp4

3ade6c4a9635a035ea243eab780e53d60e6897c3

**Comment by bvr-yr** [comment]
> https://github.com/hyprwm/Hyprland/commit/3ade6c4a9635a035ea243eab780e53d60e6897c3

actually, cpu usage per core bumped up to 30%. downgrading back to v0.23 with both xdpw upgraded/or not. (not sure this is related)

again, maybe u need some additional dumps? casue i'm not in clue what exactly could cause it

**Comment by vaxerski** [comment]
disable overlay, it will now schedule repaints

**Comment by bvr-yr** [comment]
**confirmed:** fixed

**Comment by vaxerski** [comment]
Life lesson: _never_ say I am wrong, because I am never wrong.

**Comment by bvr-yr** [comment]
never said that KEKW
