### ISSUE TITLE
Flameshot not work with windowrule

### ISSUE THREAD

**Issue by devalexandre** [hyprwm/Hyprland#2009]
after install flameshot, it not work with my windowrule

```
windowrule = float, flameshot , fullscreen , class:^(flameshot)$

```

![image](https://user-images.githubusercontent.com/4489558/230801008-b926412a-1e9d-4ece-afb4-ed40c7d8bf82.png)

the flameshot not open in fullscreen, only left of screen

**Comment by vaxerski** [comment]
Because flameshot does not properly support wayland and they seem to not care
