### ISSUE TITLE
XWayland applications get keystrokes after compositor-level keybind

### ISSUE THREAD

**Issue by russelltg** [hyprwm/Hyprland#2010]
After changing workspaces, XWayland clients seem to get the input from the final key in the keybind. Wayland apps work properly and don't get that input. 

It's a bit tough to see from the video but what I'm doing is pressing Meta+3 and holding them down for a while. 

https://user-images.githubusercontent.com/7105082/230802025-f10b8c34-8d71-4bbd-bb48-088ae681ff34.mp4

**Comment by vaxerski** [comment]
I am super fucking confused as I put breakpoints on all places where hyprland sends key events and the `3` is never sent, how the fuck did xwayland know lol

**Comment by vaxerski** [comment]
fixed in ea77622e0423676dc436f24bc188f13495807a45
