### ISSUE TITLE
Easy Anti Cheat crashing hyprland 

### ISSUE THREAD

**Issue by MrDisguised** [hyprwm/Hyprland#2014]
I already went through all the github issues and found a [similar issue](https://github.com/hyprwm/Hyprland/issues/1890). Whenever I try to play games like Apex Legends / Fall guys (games which have eac in them) hyprland crashes , my screen goes black and then I see my tty (I actually get logged out of my tty) (I am not using any login manager / display manager) . I think that the shitty anti cheat eac is crashing  hyprland. ( I am not sure though). Here are my crash dumps -
```
[rounak@archissexy 17:33 ~]$ sudo coredumpctl
[sudo] password for rounak: 
TIME                          PID  UID  GID SIG     COREFILE EXE               SIZE
Mon 2023-04-10 17:26:28 IST   631 1000 1000 SIGABRT present  /usr/bin/Hyprland 4.5M
Mon 2023-04-10 17:26:28 IST 27131 1000 1000 SIGABRT present  /usr/bin/Xwayland 5.3M
[rounak@archissexy 17:33 ~]$ 
```
1) Here is the crash log for PID 631 -  https://c-v.sh/looserhipsters.txt
2) Here is the crash log for PID 27131 - https://c-v.sh/heathenlacing.txt
3) Here is the crash log of the file `hyprlandCrashReport631.txt` in the directory `/home/rounak/.hyprland` - https://c-v.sh/cutestfounder.txt

**Comment by vaxerski** [comment]
You are reporting an issue.

You found an issue that says it's fixed

It got fixed 4 days ago.

Your hyprland is outdated by 2 weeks.

Hmm I wonder why it's not fixed!

**Comment by vaxerski** [comment]
nvidia-git is not maintained by us. All complaints should be voiced to its maintainer

**Comment by vaxerski** [comment]
oh just reread your comment

-git packages don't get "updates", you need to manually yay -S them and select cleanbuild.
