### ISSUE TITLE
ext_workspace_unstable implementation is not atomic

### ISSUE THREAD

**Issue by MaxVerevkin** [hyprwm/Hyprland#2015]
A switch from an empty workspace sometimes triggers two series of events, which may cause flickering in the status bar.

```
[wayrs] zext_workspace_group_handle_v1@4278190080v1.workspace(zext_workspace_handle_v1@4278190082)
[wayrs] zext_workspace_handle_v1@4278190082v1.coordinates(<array>)
[wayrs] zext_workspace_handle_v1@4278190082v1.state(<array>)
[wayrs] zext_workspace_handle_v1@4278190082v1.state(<array>)
[wayrs] zext_workspace_handle_v1@4278190082v1.name("2")
[wayrs] zext_workspace_handle_v1@4278190081v1.state(<array>)
[wayrs] zext_workspace_handle_v1@4278190082v1.state(<array>)
[wayrs] zext_workspace_manager_v1@10v1.done()
...
[wayrs] zext_workspace_handle_v1@4278190081v1.state(<array>)
[wayrs] zext_workspace_handle_v1@4278190081v1.remove()
[wayrs] zext_workspace_manager_v1@10v1.done()
```

**Comment by MaxVerevkin** [comment]
I could find that the new workspace is created at (first series of events) https://github.com/hyprwm/Hyprland/blob/16a034a34a8e97aaeed6e3f46d04c87497313c20/src/managers/KeybindManager.cpp#L912

But I couldn't find where the empty workspace is destroyed.

Would it be correct to destroy old empty workspace in `CKeybindManager::changeworkspace`?

**Comment by vaxerski** [comment]
`CCompositor::sanityCheckWorkspaces`

**Comment by MaxVerevkin** [comment]
Broken again after 287e6c4ede30c8e5e85863cd85f157e17e24879c

**Comment by vaxerski** [comment]
my bad

**Comment by vaxerski** [comment]
can be closed, we no longer support the protcool
