### ISSUE TITLE
Crash when inserting HDMI cable for screen mirroring

### ISSUE THREAD

**Issue by ignamartinoli** [hyprwm/Hyprland#2016]
Hyprland crashes when I insert the HDMI cable of my TV to mirror the screen

[This](https://gist.github.com/ignamartinoli/5bc6c549fcb16ebe511aeb8deb741930) is the log.

The relevant configuration is:

```
monitor = eDP-1, preferred, auto, 1
monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1
```

[This](https://gist.github.com/ignamartinoli/35cf8a5187f11bca9072d3e80bcb68cb) is the complete configuration.

[This](https://gist.github.com/ignamartinoli/b3ab8511918289eab4b53b82b1be47e6) is the Hyprland Crash Report.

I have `waybar` disabled.

The issue doesn't appear when not mirroring.

**Comment by vaxerski** [comment]
it would be nice if the crash report didn't have symbols stripped

**Comment by vaxerski** [comment]
it means whoever gave you the build strips symbols. It's unusable.

**Comment by ignamartinoli** [comment]
Thanks! I'm going to report that to Gentoo GURU, and as soon as I got that fixed I'm posting a useful Crash Report

**Comment by vaxerski** [comment]
If you need any info to provide them, make sure `-rdynamic` is passed to `ld` and that there is no symbol stripping process anywhere

**Comment by rycee** [comment]
I ran into something similar today. It may or may not be the same as in this report but it happened when I ran `hyprctl` to configure a mirrored screen. See https://gist.github.com/rycee/bdc1c1303bfa89a2bd678bcb797ef78e for the crash log.

**Comment by ignamartinoli** [comment]
The updates fixed this. @rycee Do you still experience this? So that I can close this

**Comment by rycee** [comment]
@ignamartinoli If it works for you now then I think you can close this issue. I ran into it yesterday but I'm running and old version of Hyprland (0.25.0).

**Comment by ignamartinoli** [comment]
@rycee alrighttt
