### ISSUE TITLE
Strange mouse grab on layers with keyboard interactivity

### ISSUE THREAD

**Issue by ettancos** [hyprwm/Hyprland#2017]
I think this is probably a bug, found it testing the eww sys tray https://github.com/elkowar/eww/pull/743#issuecomment-1501716248

there are multiple ways to reproduce, enable `:focusable` in an eww window or just run any layer-shell example like below with keyboard interactivity

I have  `follow_mouse = 2`

the smithay example is with OnDemand but its same with Exclusive too

```
git clone https://github.com/Smithay/client-toolkit/
cd client_toolkit 
cargo run --release --example simple_layer
```

expecatation:
mouse events only go to the layer surface if the cursor is over the surface, if its over another surface events go to that other surface

actual:
mouse events seem to go to the layer surface no matter where i click on the screen

sway: mouse clicks go to the intended target surface, not to the layer if mouse is not over the layer surface
does not happen with kb interactivity disabled

so I'm wondering what might keyboard interactivity have to do with mouse events

**Comment by vaxerski** [comment]
Well, not a bug per se, intended to be this way. If a layer requests exclusive focus, we grant it exclusive focus.

**Comment by ettancos** [comment]
have to admit, thats a bit surprising to me, the protocol is not very clear on what normal handling is, but in my interpretation pointer events would be handled as any other surface type

the app that wants focus over the entire screen could just set the exclusive zone that way?

use-cases that I'm used to: click away from launcher if i change my mind, fuzzel, wofi, no way to close them without keyboard
also to close tray menu and such

**Comment by aserowy** [comment]
Heho,

i think i ran into the same problem (from a somewhat different direction). Im spawning to layer with different sizes:

```sh
	Layer level 2 (top):
		Layer 23b2c70: xywh: 3440 0 1200 1920, namespace: eww_dashboard
	Layer level 3 (overlay):
		Layer 2b19ec0: xywh: 3702.5 727 675 466, namespace: rofi
```

Clicking outside of the rofi namespace does not pass clicks to the eww layer. Is there anything i can do to enable this behavior?

Sidenote: If this is unrelated let me know please. Thus i can remove this comment.

Kind regards
Alexander

**Comment by earboxer** [comment]
> If a layer requests exclusive focus, we grant it exclusive focus.

I think this is a bug, because layers are requesting exclusive *keyboard* focus, not exclusive mouse (or touchscreen) focus.

snippet from [the spec](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/protocol/wlr-layer-shell-unstable-v1.xml?ref_type=heads):
```xml
 <entry name="exclusive" value="1">
        <description summary="request exclusive keyboard focus">
          Request exclusive keyboard focus if this surface is above the shell surface layer.
```

(My use-case is that I want to use a virtual keyboard like wvkbd on a touchscreen device, and opening bemenu makes it impossible to type)
