### ISSUE TITLE
Synergy issue

### ISSUE THREAD

**Issue by piotrzarycki** [hyprwm/Hyprland#2027]
Hi 
I've been using https://symless.com/synergy on dwm, currently i've moved to hyprland, but it seems it does not working. 
Is any one had the same issue?

**Comment by Person1873** [comment]
@piotrzarycki this is a synergy issue, not a Hyprland one
please see https://github.com/symless/synergy-core/issues/4090

**Comment by piotrzarycki** [comment]
ok, thanks for info
