### ISSUE TITLE
Switch to the workspace with "active" window

### ISSUE THREAD

**Issue by shasherazi** [hyprwm/Hyprland#2028]
I don't know how to word it better, but here's the situation. Suppose you open a link from, let's say, discord. I assume that my workspace will switch automatically to where my browser is with the tab that just opened. But that doesn't happen, and I have to switch manually.

Also, `dunst` notifications actions don't switch the workspace either. The action is executed, but the workspace isn't switched. For example, when I click a discord notification, the channel gets opened in discord, but my workspace doesn't switch to discord.

Is there a way to add that? I couldn't find it in wiki or any other issues about it.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#misc

misc:focus_on_activate
