### ISSUE TITLE
Multi-gpu support (wlroots MR !3887)

### ISSUE THREAD

**Issue by sbayonag** [hyprwm/Hyprland#2030]
Hi! First of all, I want to thank you for this awesome project.
I was reading MRs in wlroots and stumbled upon this one [!3887](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3887). This MR changes some logic in the compositor code (I saw this PR on sway [#7285](https://github.com/swaywm/sway/pull/7285) it doesn't have much traction) So, I was wondering if you have plans to port this into hyprland.
Thanks again for your work! C:

**Comment by vaxerski** [comment]
why? the wlroots mr is not merged

**Comment by exkc** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8879 

i hope this bugs get fixed seen

**Comment by izmyname** [comment]
Since hyprland is a wlroots-based no more - close?

**Comment by vaxerski** [comment]
prolly
