### ISSUE TITLE
Key repeatition in xorg applications

### ISSUE THREAD

**Issue by liamrahum** [hyprwm/Hyprland#2031]
Hey, I've been having issue for quite a while now - that every time I launch rofi (Meta+Space) sometimes it'd repeat the "Space" key in the search bar
Same in Webcord, If I'm in a text box and I move between workspaces (eg.Meta+1) it'd repeat the "1" key inside the text box

On Wofi (and other Wayland-native apps) the problem doesn't seem to occur.

Config:
* OS: Arch Linux x86 (LTS kernel)
* Hyprland: hyprland-nvidia-git
* Drivers: nvidia-open-dkms
* Env variables: (same as in guide for wiki.hyprland.org.nvidia)
* Keyboard repeat delay: 500 (Even 1000 doesn't help, it's probably not the cause)

**Comment by vaxerski** [comment]
dupe of #2010

**Comment by liamrahum** [comment]
Yeah I've moved hyprland-git now, seems to work perfectly
A giant thank you for responding so quickly!
