### ISSUE TITLE
wp-fractional-scaling-v1 support is broken

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#2032]
Steps to reproduce:

1. Update to qt 6.5.0 on arch
2. Use fractional scaling
3. Launch transmission-qt or qbittorrent
4. Open a dropdown menu
5. Observe that the menu is blurry

From the WAYLAND_DEBUG=1 logs attached below it seems that `wp_fractional_scale_v1@43` has never been changed to the correct scale, which is `210` (1.75) in my setup.
[transmission-qt.log](https://github.com/hyprwm/Hyprland/files/11213674/transmission-qt.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11213820/patch.txt)

test this patch

**Comment by q234rty** [comment]
I can confirm that patch fixes this issue for me.

**Comment by vaxerski** [comment]
do I care?

yes, that's why I committed that in 5f000306f526e38ae0df551b0e83dddc9d4c2f44 have a nice day
