### ISSUE TITLE
Chrome hangs on focus if another workspace has a video running

### ISSUE THREAD

**Issue by naps62** [hyprwm/Hyprland#2033]
I've switched from sway to hyprland around a week ago. Been dealing with this issue since then.

Long story short, I usually have two different browser windows running (running different profiles, but I don't think that's relevant here).
on my work-related workspace, I'll have a browser with a test profile, terminal, editor, etc
on a separate workspace I have my actual chrome profile, where I often do video calls, or have a video running in the background

whenever I'm switching between editor & test chrome window while developing, often chrome hangs for around 5 seconds before waking up again.

I've been doing some trial & error. It seems this only happens if there is also a chrome window running in another workspace. And especially if there's a video running on it. I tried temporarily moving the other profile into the same workspace, and the problem went away

however, this is proving very hard to reproduce, because it doesn't actually happen 100% of the time.
Is there a way I can get some more info to provide proper reproduction steps?

**Comment by vaxerski** [comment]
wdym "hangs"? Does it freeze, but keep actually running, while the only frozen thing is the rendering, does it completely hang?

> Is there a way I can get some more info to provide proper reproduction steps?

Don't think so, looks like some issue within chromium tbh

I assume your workspaces are on the same monitor?

**Comment by naps62** [comment]
> wdym "hangs"? Does it freeze, but keep actually running, while the only frozen thing is the rendering, does it completely hang?

yes, only the rendering. after it gets back, all the inputs made in the meantime are processed. trying to resize the window during that time just results in black bars.

> I assume your workspaces are on the same monitor?

yes, single monitor (ultrawide).
I still have to test this with other browser, and also try to install sway again to double check if it's really only on hypr

**Comment by naps62** [comment]
After some more tinkering, I noticed today people I have google meet calls with me are reporting that, when I'm on the workspace that *doesn't* have the meet tab, my video stutters a lot

**Comment by naps62** [comment]
I haven't experienced this for a while. not sure if it was the latest update, or some other change in my own system
