### ISSUE TITLE
Some widgets are not functioning in Bitwig

### ISSUE THREAD

**Issue by n8wood-brown** [hyprwm/Hyprland#2034]
I am unable to adjust knob and fader controls in Bitwig Studio (Xwayland) when click-dragging, other widgets seem to work fine. I am able to ctrl+click them and manually enter a value, so the mouse clicks are being detected. Everything works as expected in Sway. I've tested with:

- Bitwig versions 4.4.6, 4.4.8, and 4.4.10.
- hyprland 0.24.1-1, hyprland-git (aur: r2580.71ef1bde-3)

**Comment by Person1873** [comment]
@n8wood-brown could you please have a look at the below issue & see if the resolutions suggested there help you?
https://github.com/hyprwm/Hyprland/issues/1969

**Comment by n8wood-brown** [comment]
@Person1873 , I tried `windowrulev2=nofocus,class:^(com.bitwig.BitwigStudio)` , but then I was unable to click anything in the application.

**Comment by rei-00** [comment]
having the same issue. this is the log when trying to drag the volume slider in Bitwig:

```
[LOG] New XWayland Surface created (class (null)).
[LOG] Registered signal for owner 63fc12f0: 63fc0ea8 -> 63fc1358 (owner: XWayland Window)
[LOG] Registered signal for owner 63fc12f0: 63fc0e28 -> 63fc1428 (owner: XWayland Window)
[LOG] Registered signal for owner 63fc12f0: 63fc0f68 -> 63fc19d8 (owner: XWayland Window)
[LOG] Registered signal for owner 63fc12f0: 63fc0e38 -> 63fc1838 (owner: XWayland Window)
[LOG] Registered signal for owner 63fc1a40: 63f71998 -> 63fc1a48 (owner: CWLSurface)
[LOG] CWLSurface 63fc1a40 called init()
[LOG] Registered signal for owner 63fc12f0: 63fc0eb8 -> 63fc13c0 (owner: CWindow)
[LOG] Searching for matching rules for  (title: )
[LOG] Set keyboard focus to surface 63f716b0, with window name: 
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 63fc12f0: 63fc0e88 -> 63fc1560 (owner: XWayland Window Late)
[LOG] Registered signal for owner 63fc12f0: 63fc0e98 -> 63fc17d0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 63fc12f0: 63fc0ec8 -> 63fc1490 (owner: XWayland Window Late)
[LOG] Registered signal for owner 63fc12f0: 63fc0e68 -> 63fc1698 (owner: Xwayland Window Late)
[ERR] Tried to connect a listener twice?!
[LOG] Registered signal for owner 63fc12f0: 63fc0f78 -> 63fc14f8 (owner: XWayland Window Late)
[LOG] Registered signal for owner 63fc10f0: 63f71988 -> 63fc1168 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 63fc10f0: 63f71978 -> 63fc11d0 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 63fc10f0: 63f71998 -> 63fc1238 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 63fc12f0)
[LOG] Map request dispatched, monitor HDMI-A-1, xywh: 1237.000000 161.000000 59.000000 19.000000
[LOG] Unmanaged window 63fc12f0 requests geometry update to 1244 161 59 19
[LOG] Unmanaged window 63fc12f0 requests geometry update to 1244 161 52 19
[LOG] New mouse constraint at 63fc2670
[LOG] Registered signal for owner 63f341d0: 63fc2778 -> 63f34260 (owner: Constraint)
[LOG] Registered signal for owner 63f341d0: 63fc2768 -> 63f341f8 (owner: Constraint)
[LOG] Window 63fc12f0 unmapped (class )
[LOG] Unregistered late callbacks XWL
[LOG] Callback 63fc1588 -> 63fc1580, XWayland Window Late removed.
[LOG] Callback 63fc17f8 -> 63fc17f0, XWayland Window Late removed.
[LOG] Callback 63fc14b8 -> 63fc14b0, XWayland Window Late removed.
[LOG] Callback 63fc1520 -> 63fc1518, XWayland Window Late removed.
[LOG] Callback 63fc16c0 -> 63fc16b8, Xwayland Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] On closed window, new focused candidate is 63f5c320
[LOG] Set keyboard focus to surface 63f72590, with window name: Bitwig Studio - New 1
[LOG] Destroying the SubSurface tree of unmapped window 63fc12f0
[LOG] Callback 63fc11f8 -> 63fc11f0, SurfaceTreeNode removed.
[LOG] Callback 63fc1260 -> 63fc1258, SurfaceTreeNode removed.
[LOG] Callback 63fc1190 -> 63fc1188, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 63fc1a70 -> 63fc1a68, CWLSurface removed.
[LOG] CWLSurface 63fc1a40 called destroy()
[LOG] Callback 63fc13e8 -> 63fc13e0, CWindow removed.
[LOG] Window 63fc12f0 destroyed, queueing. (class )
[LOG] XWayland class raw: (null)
[LOG] Callback 63fc1380 -> 63fc1378, XWayland Window removed.
[LOG] Callback 63fc1450 -> 63fc1448, XWayland Window removed.
[LOG] Callback 63fc1860 -> 63fc1858, XWayland Window removed.
[LOG] Callback 63fc1a00 -> 63fc19f8, XWayland Window removed.
[LOG] Unconstrained mouse from 63fc2670
[LOG] Callback 63f34288 -> 63f34280, Constraint removed.
[LOG] Callback 63f34220 -> 63f34218, Constraint removed.
[LOG] Cleanup: destroyed a window
```
the [ERR] in the log is 'Tried to connect a listener twice?!'. but i dont know what this means. issue seems to be similar to #1947. 

tried 'nofocus' and 'noanim' rules and no fix.

**Comment by gegnep** [comment]
realized this could also be an issue with how hyprland handles java clients as I know that Bitwig's UI is witten in Java with a c++ audio engine, similar to #1947  and the intelliJ UI

**Comment by Person1873** [comment]
> realized this could also be an issue with how hyprland handles java clients as I know that Bitwig's UI is witten in Java with a c++ audio engine, similar to #1947 and the intelliJ UI

In retrospect #1947 seems unrelated to this.
I will at some point attempt to replicate this issue.

Seems like somehow click+drag is causing the window to lose focus.
Is this same behavior present in other programs (even if not problematic)?

**Comment by Person1873** [comment]
Have tested in both Hyprland & sway.
this works correctly under sway.

Under sway: 
on mouse down, the cursor disappears until mouse released, all mouse events are handled by Bitwig Studio.

Under Hyprland:
on mouse down, a click is passed to Bitwig Studio, all further mouse events are handled by Hyprland.

This appears to be an issue with mouse event handling where the Xwayland window captures the mouse under Hyprland.
Somewhat surprising that this issue isn't more prevalent with other programs.

**Comment by Person1873** [comment]
I believe i may have found where the bug exists in the codebase.
I think we may be reprocessing focus a little too agressively @ Hyprland/src/managers/input/InputManager.cpp:522+23

I'll have a play & report back

**Comment by Hamblok0** [comment]
Is this still a problem? I want to get back into hyprland but I use Bitwig on a daily basis.

**Comment by jonasatnewton** [comment]
tested it yesterday and it does work now, 4.10 and 5.0 versions are all fine again at least for me

**Comment by Hamblok0** [comment]
> tested it yesterday and it does work now, 4.10 and 5.0 versions are all fine again at least for me

Still doesn't work for me.

**Comment by tomasciccola** [comment]
I was able to solve it with
```
windowrulev2=stayfocused,class:^(com.bitwig.BitwigStudio)
```

**Comment by n8wood-brown** [comment]
The rule that @tomasciccola provided has resolved the issue for me, thanks!

**Comment by Kagia001** [comment]
That rule made impossible to focus on 3rd party plugin windows, so this rule worked better:
`windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0`
This will also remove focus from all floating xwayland windows with no title or class but that hasn't been a problem for me yet.

**Comment by tomasciccola** [comment]
Heh, didn't try with third party plugins, but did notice that couldn't focus dialog windows (like opening a project with native gtk dialog), so I'll try this!

**Comment by PowerUser64** [comment]
Here's @Kagia001's window rule but rewritten for the new windowrule style currently in use on hyprland-git.
```hyprconf
windowrule = no_initial_focus 1, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
```
