### ISSUE TITLE
The window which was moved to special workspace pops out of nowhere when trying to move between workspaces

### ISSUE THREAD

**Issue by MrDisguised** [hyprwm/Hyprland#2038]
It is a weird issue that was not present before. When I move the steam window to a special workspace it works but then when I change my workspace ( move between workspaces ) I can see the steam application which was already moved to the special workspace for 3 seconds and then it dissapears. Here is the video if u cannot understand what I mean- 

https://user-images.githubusercontent.com/128170542/231753194-2b9cf850-1ebb-4fe2-b5e8-e38ca0e0b8ad.mp4 

<br>EDIT : I updated the `nvidia-hyprland-git` package from the aur. I had to do `yay -Y --gendb && yay --save --devel` which will automatically update the package next time if a new commit is made to the hyprland repo. So everything is up to date.

As you can see on `0:06` I moved the steam application to a special workspace. On `0:08` you can see that when I try to change my workspaces I can see the steam application popping up out of nowhere and then dissapearing. It shouldn't pop out like that if it is moved to a special workspace. I should only see that workspace when I use the `togglespecialworkspace` keybinding.

**Comment by Gajus84** [comment]
Same on an Multi-Monitor-Setup. When changing workspaces on the second monitor, the workspace focused before the last change on workspaces on the first monitor will appear. E.g. On 1st Monitor change from WS1 to WS3. Than WS1 will appear for 1 second when changing WS on Monitor 2.

**Comment by MrDisguised** [comment]
I don't use muti-monitor setup but I am also facing this issue on single monitor.

**Comment by Gajus84** [comment]
The latest commits seem to have solved the problem. Unfortunately, they also introduced a new problem. To change a WS in Waybar now requires two left mouse clicks after the first WS change. After switching, hovering is no longer registered. A right click anywhere on the Waybar "solves" the problem. Until the next WS change (via mouse).

If you have more than one monitor, the WS change via mouse on all other monitors becomes impossible. A left click makes the mouse jump to the center of the screen on which the last WS change via mouse took place.

@MrDisguised maybe change the Issue-Title? I feel this is not related to Steam.

**Comment by vaxerski** [comment]
> If you have more than one monitor, the WS change via mouse on all other monitors becomes impossible. A left click makes the mouse jump to the center of the screen on which the last WS change via mouse took place.

Right click first, pro-tip. But yes, I am aware

**Comment by MrDisguised** [comment]
> The latest commits seem to have solved the problem. Unfortunately, they also introduced a new problem. To change a WS in Waybar now requires two left mouse clicks after the first WS change. After switching, hovering is no longer registered. A right click anywhere on the Waybar "solves" the problem. Until the next WS change (via mouse).
> 
> If you have more than one monitor, the WS change via mouse on all other monitors becomes impossible. A left click makes the mouse jump to the center of the screen on which the last WS change via mouse took place.
> 
> @MrDisguised maybe change the Issue-Title? I feel this is not related to Steam.

Oh it's ok :+1: I am little bit busy rn so I will edit the title of the issue when I get time dw :+1: .

**Comment by MrDisguised** [comment]
I am using the `hyprland-nvidia-git` package and I am facing graphical glitches when I try to move a window to special workspace. - 

https://user-images.githubusercontent.com/128170542/232233059-c97da6dc-a920-475b-8795-eb4297984d79.mp4

<br>
WTF

**Comment by vaxerski** [comment]
fixed xD

d6c4ae71d082eecefac40216b0a1b236daa3c0ab

**Comment by MrDisguised** [comment]
> @MrDisguised fixed xD
> 
> [d6c4ae7](https://github.com/hyprwm/Hyprland/commit/d6c4ae71d082eecefac40216b0a1b236daa3c0ab)

That was kinda funny lol. It was fun drawing dicks on my computer.

**Comment by vaxerski** [comment]
Anyways, the original issue has been fixed, so I am closing this.
