### ISSUE TITLE
Ability to prevent new windows from stealing focus?

### ISSUE THREAD

**Issue by naps62** [hyprwm/Hyprland#2040]
Read the full docs, and searched through issues. apologies if this was already discussed somewhere

I'm developing a desktop app with Rust. The watcher automatically re-compiles and re-runs the app on every file save. This also triggers the app's GUI window to re-open. I need it to do so, but the fact that it steals focus away from my text editor is extremely annoying

the only workaround I found so far is `nofocus`, but that then prevents me from focusing the window afterwards to fill out forms

**Comment by Ondra3211** [comment]
You can use window to rule open it on workspace with silent option.
windowrule = workspace 1 silent, ^(window)$

**Comment by Hubro** [comment]
@naps62 Have you tried using `focuscurrentorlast` in your window rule? That should at least immediately change focus back to your editor.

**Comment by bvr-yr** [comment]
```shell
#!/usr/bin/env bash

editor_address=$(hyprctl activewindow -j | jaq -r .address) # or jq

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | \
while read -r line; do
    if [[ ${line:0:10} == openwindow ]]; then
        window=${line:27}
        # class=${window%,*}
        # title=${window#*,}
        if [[ $window == "<poping_window_class>,<popping_window_title" ]]; then
            # or use class/title separately
            hyprctl dispatch focuswindow address:"$editor_address"
        fi
    fi
done

```

**Comment by Hubro** [comment]
I'm having this problem too now. Any time Viber gives a notification, the notification grabs focus. This is beyond enfuriating when somebody keeps sending me a stream of messages while I'm trying to write something elsewhere.

The only config solution that seems to work is `nofocus`, but then I can't click the notification, which I want to be able to do.

I think it would be valuable to have a `nofocus`-like option that only prevents the *initial* focus, but still allows focusing the window later.

**Comment by vaxerski** [comment]
notifications should not open windows anyways, they should use the system notification bus

**Comment by vaxerski** [comment]
done in dbb6d9d17421618901d3e7d985af1aee4414e537

**Comment by Hubro** [comment]
@vaxerski I agree, it's damn annoying that applications keep rolling their own, but they do. This is also true for Steam.

**Comment by vaxerski** [comment]
at least steam sets the atoms correctly so that they're not focused
