### ISSUE TITLE
Failed to load GLIB_2.36 on NixOS

### ISSUE THREAD

**Issue by addy419** [hyprwm/Hyprland#2044]
After updating to latest nixos release rev 4bc3f9adbe7563817a9e1c6eac6f5e435f7db957, I am getting this error. Rolling back works fine for now.

```
pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
00:00:00.000 [INFO] [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.000 [INFO] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
00:00:00.008 [INFO] [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
00:00:00.008 [INFO] [backend/session/session.c:109] Successfully loaded libseat session
00:00:00.011 [INFO] [backend/backend.c:219] Found 1 GPUs
00:00:00.011 [INFO] [backend/drm/backend.c:201] Initializing DRM backend for /dev/dri/card0 (amdgpu)
00:00:00.011 [INFO] [backend/drm/drm.c:249] Found 4 DRM CRTCs
00:00:00.011 [INFO] [backend/drm/drm.c:207] Found 9 DRM planes
00:00:00.012 [INFO] [render/egl.c:206] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
libEGL warning: MESA-LOADER: failed to open radeonsi: /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/5k9x8dnwiq0h5czikpax6rbal547k24z-llvm-15.0.7-lib/lib/libLLVM-15.so) (search paths /run/opengl-driver/lib/dri, suffix _dri)

00:00:00.014 [ERROR] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
libEGL warning: MESA-LOADER: failed to open radeonsi: /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/5k9x8dnwiq0h5czikpax6rbal547k24z-llvm-15.0.7-lib/lib/libLLVM-15.so) (search paths /run/opengl-driver/lib/dri, suffix _dri)

00:00:00.015 [ERROR] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
00:00:00.015 [ERROR] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
00:00:00.015 [ERROR] [render/egl.c:269] Failed to initialize EGL
00:00:00.015 [ERROR] [render/egl.c:567] Failed to initialize EGL context
00:00:00.015 [ERROR] [render/gles2/renderer.c:703] Could not initialize EGL
terminate called after throwing an instance of 'std::runtime_error'
  what():  wlr_gles2_renderer_create_with_drm_fd() failed!
```

**Comment by vaxerski** [comment]
@fufexan

**Comment by addy419** [comment]
No, I'm not on stable. Here's my config https://github.com/addy419/configurations

**Comment by eadwu** [comment]
You will need to track the same nixpkgs repo as what you are building. Either through setting `nixpkgs` on `NIX_PATH` pre-flake or adding `inputs.nixpkgs.follows = "/nixpkgs"` to `inputs.hyprland` assuming standard naming conventions.

**Comment by ubersan** [comment]
thabks @eadwu can confirm that setting the follows on the input works👍

As a nixos newbie a few questions:
- I saw that now it compiled jyprland locally although I think I have setup cachix, is this expected?
- Is setting the follows a general noxos pattern?
- Is this only a temporary measure or somthing that is anyways good to have? I don't think I saw the follow setting in any of the docs?

**Comment by eadwu** [comment]
- Yes, the issue arises due to a mismatch of glibc versions, changing the glibc version necessarily creates a new derivation by that alone, (`hyprland` built using 2.35 and `hyprland` built using 2.36 are different). Even if you setup cachix, it only caches the 2.35 variant, not the 2.36.
- Whether or not it is a general nixos pattern is debatable, this is the only way to override inputs in other flakes. 
- As long as you track the same nixpkgs input in this flake (essentially the reverse of what you're doing now), it should generally be fine. You will _always_ have a problem, an external flake with a package adds an additional node for failure.

**Comment by ubersan** [comment]
I see, thanks for the insights! If hyprland needs glibc as build and apparently runtime dependency, wouldn't it make sense, that it ships its version or at least requires the correct version to exist? (I have no idea how dependencies work in nix)

**Comment by fufexan** [comment]
> I see, thanks for the insights! If hyprland needs glibc as build and apparently runtime dependency, wouldn't it make sense, that it ships its version or at least requires the correct version to exist? (I have no idea how dependencies work in nix)

Everything depends on glibc. There's no way to specify the glibc version in Hyprland. This whole mismatch was caused by a bump of the glibc version in Nixpkgs. Your configuration flake has the new version, while the Hyprland flake doesn't have it yet.

**Comment by ubersan** [comment]
indeed, all of this is against unstable without release, so it's expected that these versions can mismatch temporarily. it's called bleeding edge for a reason😅

thanks for the help🙏

**Comment by YanniPapandreou** [comment]
I am also encountering this issue, I am a bit confused how to do this in my configuration:

> adding `inputs.nixpkgs.follows = "/nixpkgs"` to `inputs.hyprland` assuming standard naming conventions.

Sorry, I am quite new to nixos!

**Comment by fufexan** [comment]
> I am also encountering this issue, I am a bit confused how to do this in my configuration:
> 
> > adding `inputs.nixpkgs.follows = "/nixpkgs"` to `inputs.hyprland` assuming standard naming conventions.
> 
> Sorry, I am quite new to nixos!

`inputs.hyprland.inputs.nixpkgs.follows = "nixpkgs";`

**Comment by YanniPapandreou** [comment]
Should that be in the input section of my `flake.nix`?  so something like this:

```nix
{
  inputs = {
      nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
      hyprland = {
         url = "github:hyprwm/Hyprland";
         inputs.nixpkgs.follows = "nixpkgs";
      };
  };
  
  outputs = { nixpkgs, hyprland, ...}@inputs: {
   .....
  };
}
```

**Comment by fufexan** [comment]
> Should that be in the input section of my `flake.nix`?  so something like this:
> 
> ```nix
> {
>   inputs = {
>       nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
>       hyprland = {
>          url = "github:hyprwm/Hyprland";
>          inputs.nixpkgs.follows = "nixpkgs";
>       };
>   };
>   
>   outputs = { nixpkgs, hyprland, ...}@inputs: {
>    .....
>   };
> }
> ```

yes

**Comment by YanniPapandreou** [comment]
> > Should that be in the input section of my `flake.nix`?  so something like this:
> > ```nix
> > {
> >   inputs = {
> >       nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
> >       hyprland = {
> >          url = "github:hyprwm/Hyprland";
> >          inputs.nixpkgs.follows = "nixpkgs";
> >       };
> >   };
> >   
> >   outputs = { nixpkgs, hyprland, ...}@inputs: {
> >    .....
> >   };
> > }
> > ```
> 
> yes

@fufexan  thanks a lot!
