### ISSUE TITLE
Disable blur, animations etc when you toggle app on fullscreen

### ISSUE THREAD

**Issue by Edgars-Cirulis** [hyprwm/Hyprland#2045]
In my option disabling blur when your in any app fullscreen may reduce gpu overhead aka gaming.

**Comment by vaxerski** [comment]
it's already done automatically?

**Comment by vaxerski** [comment]
opaque apps will not be blurred. Translucent will. Unless your game is translucent, you will be fine.

At any rate, if that's such a big issue for you, make a script lol
