### ISSUE TITLE
Hyprland crashes instantly since c2f29be9baccd14ced62105f0fc07e34e6f4fd29.

### ISSUE THREAD

**Issue by LDAP** [hyprwm/Hyprland#2046]
Hyprland crashes instantly after start since commit https://github.com/hyprwm/Hyprland/commit/c2f29be9baccd14ced62105f0fc07e34e6f4fd29. Everything works great with 16a034a34a8e97aaeed6e3f46d04c87497313c20.

Crash report:
[hyprlandCrashReport38501.txt](https://github.com/hyprwm/Hyprland/files/11225887/hyprlandCrashReport38501.txt)

**Comment by vaxerski** [comment]
should be fixed in 41c7d896e38896916f0762acbc7f811a00240b4f

lmk, if not, feel free to reopen

**Comment by LDAP** [comment]
Now it's freezing (with a gray screen and a cursor on every monitor) instead of crashing.

**Comment by vaxerski** [comment]
can I getcho config

**Comment by LDAP** [comment]
[hypr.tar.gz](https://github.com/hyprwm/Hyprland/files/11226527/hypr.tar.gz)

**Comment by vaxerski** [comment]
thank u uwu

**Comment by vaxerski** [comment]
sowwy fow the wwittwe inconwenience onii-chan uwu

can you pwease twy this patch UwU
[patch.txt](https://github.com/hyprwm/Hyprland/files/11226592/patch.txt)

**Comment by LDAP** [comment]
It's working with the patch applied.

**Comment by vaxerski** [comment]
pushed to head
