### ISSUE TITLE
Enumerating inactive devices causes performance issues

### ISSUE THREAD

**Issue by eadwu** [hyprwm/Hyprland#2051]
`Steps to reproduce`
- Install nvidia packages and drivers and tools (i.e. CUDA)
- `Hyprland`

`Expected outcome`
Same performance and responsiveness as without `nvidia` drivers and modules loaded.

`Noted outcome`
Delayed response times from keypress -> action (i.e. spawning terminal)

To clarify, this is not about support for NVIDIA - I only use it for compute-related tasks - I _do_ load `nvidia`, `nvidia-drm`, `nvidia-modeset`, ..., but I explicitly do not enable `nvidia-drm.modeset=1`. On startup, Hyprland (or some dependency) appears to enumerate the NVIDIA GPU but as expected it won't receive any response - however, it keeps attempting to either enumerate or access the device (no logs to confirm this but I believe that's what happening) causing problems in the responsiveness.

Setup TLDR:
- Headless NVIDIA setup for compute
- Integrated Display solely driven by Intel

**Comment by vaxerski** [comment]
that would not be an issue with hyprland, but with either wlroots or the apps you use.

**Comment by eadwu** [comment]
Originates from `wlroots`. For anyone who comes across this scenario, explicitly setting `WLR_DRM_DEVICES` to the subset of devices resolves this issue.
