### ISSUE TITLE
Special workspace is hidden behind fullscreen window

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#2053]
As the title says, if a workspace displays a window in fullscreen, the special workspace will not be on top of this window, but hidden behind it!

**Comment by vaxerski** [comment]
doesn't seem to be the case for me?

**Comment by Dickby** [comment]
Strange! 
For me it happens even with the default configuration.

**Comment by vaxerski** [comment]
are you on -git?

**Comment by Dickby** [comment]
Damn, after complete clean install the issue is gone.
Sorry for the noise!
There is however some thing related to this that is there for a long time.
If the special workspace animation is a slide animation and there is a fullscreen window in a workspace and the special workspace is shown on top of it. The slide out  animation is not visible. I think the special workspace is hidden behind the fullscreen window once `togglespecialworkspace` is triggered. If the window behind the special workspace is not fullscreen, the slide out animation is visible.

**Comment by MightyPlaza** [comment]
cannot repro
