### ISSUE TITLE
When you sleep/suspend and wake up sometimes hyprland changes workspace

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#2055]
When I sleep my system with systemctl if I am on the first workspace then when I resume Hyprland is on the 3rd (which in this case is the fisst workspace without application windows open), their is no animation shown both when sleeping and resuming.
I would expect Hyprland to stay on the workspace that it was on when I suspended.
**Config file:**
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11232283/hyprland.conf.txt)
**Log file:**
[hyprland.log](https://github.com/hyprwm/Hyprland/files/11232305/hyprland.log)

**Comment by vaxerski** [comment]
dupe of #1980

**Comment by LucasTran380381** [comment]
Still have this problem. I use 1 monitor

**Comment by oluijks** [comment]
Imy having this issue as well. When waking up it starts on ws5 and I only have 4 configured. Also the apps on the first ws are gone but that is another issue I think...
