### ISSUE TITLE
[Regression] `workspace previous` dispatcher breaks if `allow_workspace_cycles` is set to false.

### ISSUE THREAD

**Issue by tchofy** [hyprwm/Hyprland#2058]
Steps to reproduce
Be on commit 287e6c4ede30c8e5e85863cd85f157e17e24879c or later
set `allow_workspace_cycles = 0`
go to workspaces 1 > 2 > 3
workspace previous

Expected
1 2 [3] > `workspace previous` > 1 [2] 3 > `workspace previous` > [1] 2 3

Noted
1 2 [3] > `workspace previous` > 1 2 [3] (and in the logs: [LOG] No previous workspace to change to)

Other behavior changes noted

- Since I use workspace cycles as a sort of alt-tab between two workspaces, this commit seems to invert the behavior of allow_workspace_cycles. Previously if it was set to false, and you were on workspace 1 > 2 > 3, then workspace previous, they would cycle between 3 and 2, and if set to true, would go 3 > 2 >1, which makes less sense, so the new logic seems to work as intended.

- With `allow_workspace_cycles=1`
Switching from an empty workspace to an active one only works once. Example:
[1] 2 > `workspace 3` > 1 2 [3] > `workspace previous` > [1] 2 > `workspace previous` > 1 2 [3] > `workspace previous` > `[LOG] No previous workspace to change to`. Unsure of what's the intended behavior.

**Comment by vaxerski** [comment]
check with 83f1616a65091fe2e66d054f5ef1343d755a3e0c

**Comment by tchofy** [comment]
Aye, that fixes all issues mentioned here, thanks!
