### ISSUE TITLE
Wayland segfaults when trying to start from tty

### ISSUE THREAD

**Issue by FFFluoride** [hyprwm/Hyprland#2060]
## Steps to reproduce

open tty (I opened with Ctrl-Alt-F2). Login. Type Hyprland

## Expected outcome

Hyprland starts

## Noted outcome

It segfaults.

[hyprlandlogfile.log](https://github.com/hyprwm/Hyprland/files/11237342/hyprlandlogfile.log)

My config is the example config that comes with the latest release as of the time I am writing this issue.

`XDG_CACHE_HOME` isn't set but I don't have a `~/.hyprland` directory so I was unable to attach the file even though I'm running 0.24.1

[hyprlandcoredump.txt](https://github.com/hyprwm/Hyprland/files/11237432/hyprlandcoredump.txt)

## More about my environment

I am on pop os 22.04 LTS with wayland turned on.

Edit: I am using an amd-gpu.

**Comment by vaxerski** [comment]
> I am on pop os 22.04 LTS with wayland turned on.

Makes sense.

![image](https://user-images.githubusercontent.com/43317083/232206239-25c2035a-a872-4a48-ab56-a4704232d648.png)

ref: https://wiki.hyprland.org/Getting-Started/Installation/

**Comment by FFFluoride** [comment]
Why did you close it, what do I need to do to get it to work.

When it said bleeding edge I thought it was just that I needed to compile some packages from source.

What kind of major issue is preventing me from using it on pop?!

**Comment by vaxerski** [comment]
because it's not a hyprland issue, as wlroots fails to open a backend. You can try launching from a tty and inspecting logs. Consider launching with `HYPRLAND_LOG_WLR=1` to also print wlr errors.

> What kind of major issue is preventing me from using it on pop?!

Everything is outdated.

**Comment by FFFluoride** [comment]
Oh I see so nothing from Hyprland failed to open (yet). I have to check errors for wlroots. And also I'm ok with compiling some packages (even if I fall into dependency hell). Thanks for your help. If I need anymore, I will  go to the discord server. (Just joined it).
