### ISSUE TITLE
Windows don't get rendered after switching workspace 

### ISSUE THREAD

**Issue by dtop129** [hyprwm/Hyprland#2063]
To reproduce the bug in latest git, starting with workspace 1 on monitor MON_1 and workspace 2 on monitor MON_2

- Open terminal in workspace 1 on MON_1
- Open terminal in workspace 2 on MON_2
- On MON_2, move to workspace 3
- Return to the terminal in workspace 1, and run `hyprctl dispatch moveworkspacetomonitor 2 MON_1`
- On MON_1, move to workspace 2

**Expected outcome**
After moving to workspace 2, I see the terminal opened earlier

**Actual outcome**
After moving to workspace 2, no window is rendered, but if I try opening another window on the same workspace it then appears with the animation into view.

**Comment by MightyPlaza** [comment]
Doesn't seem to happen anymore
