### ISSUE TITLE
natural_scroll not working on ASUS Vivobook

### ISSUE THREAD

**Issue by soundscape84** [hyprwm/Hyprland#2064]
Steps to reproduce:

- Set `natural_scroll = true` in hyprland.conf `input{}` section
- Save changes

Expected outcome:

- Gesturing down on touchpad pulls page down, gesturing up on touchpad pulls page up

Noted outcome:

- Scroll direction remains unchanged from default, ie. gesturing down moves view down (page moves up), likewise gesturing up moves view up (page moves down).

`libinput` device details:
```
Device:           FTE1200:00 0B05:0701 Touchpad
Kernel:           /dev/input/event9
Group:            8
Seat:             seat0, default
Size:             101x69mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      [disabled](url)
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```
Full hardware probe data can be found here: [https://linux-hardware.org/?probe=71e03c5459](https://linux-hardware.org/?probe=71e03c5459)

-

**Comment by vaxerski** [comment]
shouldn't that be put in input:touchpad: ?

**Comment by soundscape84** [comment]
> shouldn't that be put in input:touchpad: ?

Oh, you're right. My mistake, didn't see the separate touchpad section of the wiki.
