### ISSUE TITLE
Crash on disconnecting monitor while mouse is also disconnected

### ISSUE THREAD

**Issue by 11xx** [hyprwm/Hyprland#2068]
- Steps to reproduce
  - Disconnect mouse (e.g. pull USB out, tested on a cabled one)
  - Disconnect monitor video cable/turn it off

- Expected outcome
  - Monitor gets disconnected and workspaces and mouse pointer rearranged to new primary monitor.

- Noted outcome
  - Hyprland crashes as soon as the display disconnects.

Attached are various crash reports with yyyymmdd-hhmmss format at the end:

[hyprlandCrashReport-230415-102648.txt](https://github.com/hyprwm/Hyprland/files/11240547/hyprlandCrashReport-230415-102648.txt)
[hyprlandCrashReport-230415-103451.txt](https://github.com/hyprwm/Hyprland/files/11240548/hyprlandCrashReport-230415-103451.txt)
[hyprlandCrashReport-230415-105801.txt](https://github.com/hyprwm/Hyprland/files/11240549/hyprlandCrashReport-230415-105801.txt)
[hyprlandCrashReport-230415-162248.txt](https://github.com/hyprwm/Hyprland/files/11240550/hyprlandCrashReport-230415-162248.txt)
[hyprlandCrashReport-230415-162603.txt](https://github.com/hyprwm/Hyprland/files/11240551/hyprlandCrashReport-230415-162603.txt)
[hyprlandCrashReport-230415-162643.txt](https://github.com/hyprwm/Hyprland/files/11240552/hyprlandCrashReport-230415-162643.txt)
[hyprlandCrashReport-230415-163016.txt](https://github.com/hyprwm/Hyprland/files/11240553/hyprlandCrashReport-230415-163016.txt)
[hyprlandCrashReport-230415-163057.txt](https://github.com/hyprwm/Hyprland/files/11240554/hyprlandCrashReport-230415-163057.txt)
[hyprlandCrashReport-230415-163410.txt](https://github.com/hyprwm/Hyprland/files/11240555/hyprlandCrashReport-230415-163410.txt)
[hyprlandCrashReport-230415-163447.txt](https://github.com/hyprwm/Hyprland/files/11240556/hyprlandCrashReport-230415-163447.txt)
[hyprlandCrashReport-230415-163552.txt](https://github.com/hyprwm/Hyprland/files/11240557/hyprlandCrashReport-230415-163552.txt)

Just as context: I use two monitors and both have USB hubs, I noticed Hyprland crash when turning off the second monitor (where I connected the mouse) so I though it had something to do with just that monitor but then I eventually switched the mouse USB from the secondary to the main monitor's hub and now I could turn the second monitor on and off but not the main one (where the mouse was now connected). Then I further tested connecting the mouse to the motherboard and now I could turn both monitors on and off normally, but then disconnecting the mouse USB and turning either monitor on or off or disconneting their cables makes Hyprland crash.

**Comment by vaxerski** [comment]
should be fixed in 12604b76763abf96b513ad45a1700efae6b5c420

lmk.

**Comment by 11xx** [comment]
Wow, it _is_ fixed! Thank you very much!

You're a machine haha

**Comment by vaxerski** [comment]
it was a simple issue and you provided the crash report, pretty normal I'll apply the obvious fix in a short time.
