### ISSUE TITLE
Moving layers or UI elements in GIMP causes Hyprland to crash

### ISSUE THREAD

**Issue by BrodieRobertson** [hyprwm/Hyprland#2069]
Problem:
Consistently upon attempting to moving a layer or it seems like any UI element in GIMP, Hyprland instantly crashes without fail

Upon crashing my TTY contains this message:
`/usr/include/c++/12.2.1/bits/stl_algo.h:3623: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = double]: Assertion '!(__hi < __lo)' failed.
Gdk-Message: 09:20:40.257: Error reading events from display: Broken pipe
Gdk-Message: 09:20:40.257: Error reading events from display: Broken pipe
(EE) failed to read Wayland events: Connection reset by peer
zsh: IOT instruction (core dumped)  Hyprland
gimp: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`

Hyprland Version: 24.1-1

Bug Replication:
1. Open any GIMP file/create a new one
2. Attempt to move a layer/UI element
3. Hyprland core dumps

Logs:
[error.log](https://github.com/hyprwm/Hyprland/files/11240936/error.log)
[error_cleanconfig.log](https://github.com/hyprwm/Hyprland/files/11240935/error_cleanconfig.log)
The first is using my normal config and the second using the Hyprland example config

Other Testing:
Tested both the native Arch GIMP package gimp-2.10.34-1 and the flatpak org.gimp.GIMP 2.10.34 and the problem occurs
Tested on Sway (wlroots) Awesome (X11) and problem cannot be replicated, does not seem to be an issue with GIMP itself

**Comment by vaxerski** [comment]
does not seem to happen to me, on -git.

Can you share the crash report? (`~/.hyprland/` if XDG_CACHE_HOME is not set, `$XDG_CACHE_HOME/hyprland/` if set)

**Comment by BrodieRobertson** [comment]
The problem only recently started happening somewhere between updating from 23.0.0 beta and the current stable version

[hyprlandCrashReport16938.txt](https://github.com/hyprwm/Hyprland/files/11240947/hyprlandCrashReport16938.txt)

**Comment by vaxerski** [comment]
fixed with c86f06caa0be207882266947da67125177bba5af
