### ISSUE TITLE
blur_xray does not xray with windows on special workspaces

### ISSUE THREAD

**Issue by ZachIndigo** [hyprwm/Hyprland#2071]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

Steps to reproduce:

- Turn on blur_xray in hyprland config (with prereqs)
- Open terminal with transparency (in my case foot)
- Float terminal, and see blurred background as expected
- Unfloat terminal, and open terminal on special workspace (scratchpad)
- See blurred everything open, and not background

Expected outcome:

I expected that blur_xray would work the same for floating windows on special workspaces the same as on the same workspace

Noted outcome:

Rather, floating transparent windows on special workspaces will blur all of the opened apps (as pictured) and not the background.

Noticed on Arch 0.24.1-1 package, but I also tested on the latest Hyprland commit, as requested in the above guidelines, and got the same result.

Here is when floating a window of the same workspace

![hyprland-floating](https://user-images.githubusercontent.com/43489508/232262715-2a409775-f6a3-421e-8bae-b7de8b1b5afd.png)

Here is when floating a window on a special workspace

![hyprland-scratchpad](https://user-images.githubusercontent.com/43489508/232262739-9f01d8fa-09f9-4774-ac02-a7e347063f70.png)

**Comment by vaxerski** [comment]
fixed in 28dfe215844fe33d425bda33c677a0fae835082b

**Comment by vaxerski** [comment]
whoopsie daisy 72b118cd8f8fc56e611a6b357c844637b85ccc54
