### ISSUE TITLE
[Feature] Preview workspaces

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#2074]
# Issue
Currently when working with multiple workspaces you have to remember where each window is and in which order workspaces are sorted to efficiently navigate between workspaces.

# Solution?
Windows 10+ offers a workspace preview which makes it easy to determinate location of certain windows and switch between workspaces interactively:
![virtualworkspaces-57fe7e193df78cbc2860500d](https://user-images.githubusercontent.com/45666572/232290205-50308fe3-7153-4c76-81e0-f4bebc40ebb0.png)
This preview also shows workspace names which is already a feature that is supported in Hyprland and it would nicely tie in with a workspace preview overlay/screen.

**Comment by tchofy** [comment]
It's being discussed in #1902.
