### ISSUE TITLE
Problems when moving fullscreen window to a different workspace/monitor

### ISSUE THREAD

**Issue by Rik034** [hyprwm/Hyprland#2077]
**Steps to reproduce:** Move a fullscreen window to a workspace in another monitor (in my case 16:9 to 5:4 or vice versa), see bug (*sometimes).

**Expected outcome:** The window is moved to the workspace with no issue.

**Noted outcome:** The window disappears and is visible only during animations; other windows, either in the workspace the window came from or it's moved to, disappear or behave weirdly; when changing workspace the animation makes the window appear in the other monitor.

**Hyprland Version:** hyprland-git (AUR)

*I cannot reproduce it consistently, sometimes all the behaviors described happen, sometimes just some of them, sometimes none. I get this bug more often with fullscreen videos on youtube (firefox running on native wayland), games running in wine (so xwayland) and when swapping from the bigger to the smaller monitor.

The animations I use are the ones from the default hyprland config.

I am pretty much convinced the culprit is the different aspect ratios of my monitors, so if you need me to do some more testing I will be happy to do so.

**Comment by 11xx** [comment]
I encountered a similar issue, confirm if it is the same one please.

Tested with two monitors.

To reproduce all windows from a workspace getting hidden, showing just the wallpaper:
- first get two workspaces on monitor A (e.g. 1 and 2);
- focus workspace 3 on monitor B;
- move the _unfocused_ workspace of monitor A to monitor B (e.g. while on workspace 1 of DP-1 do: `hyprctl dispatch moveworkspacetomonitor '2 DP-2'`)
- focus monitor B and dispatch to workspace 2

With this all windows from workspace 2 get invisible. A way to get them back is to: open a new window, toggle fullscreen then toggle back, this brings the windows back.

**Comment by Rik034** [comment]
> I encountered a similar issue, confirm if it is the same one please.

It's a different one because I never move workspaces to monitors. I have workspaces assigned to monitors and move just the windows.

**Comment by 11xx** [comment]
> It's a different one

Thanks, created issue (#2080) then

**Comment by MightyPlaza** [comment]
can't seem to repro on nested session

**Comment by Rik034** [comment]
Forgot to close this. I haven't seen this behavior in months

**Comment by lmansf** [comment]
I'm having this issue now with 2 monitors. I'm using Omarchy 3, when I move a window of any kind onto an empty workspace on a new monitor it just disappears.

**Comment by JBrunoX** [comment]
> I'm having this issue now with 2 monitors. I'm using Omarchy 3, when I move a window of any kind onto an empty workspace on a new monitor it just disappears.

I have his issue for chromium. I'm on Arch. I tried full screening the windows before moving, but it did not work.
