### ISSUE TITLE
Relative monitor movement behaves counter-intuitive

### ISSUE THREAD

**Issue by KaspervdHeijden** [hyprwm/Hyprland#2082]
Relative monitor movements (m+1, m-1) do not take monitor position configurations into account.

I have 3 monitors, in the configuration below:

```
------------   ------------    ------------ 
|           |  |           |   |           |
|     1     |  |     3     |   |     2     | 
|           |  |           |   |           |
------------   ------------    -------------
```

Moving a workspace from monitor 1 with `movecurrentworkspacetomontor ,+1` I would expect it to go to
monitor 3, but goes to monitor 2 instead.

When adjusting this, this might break a lot of configs. Perhaps add a script option (in hyprctl) to get the adjacent monitors
so I can script this.

Not sure if this actually inconsistent (names work the same), but still.

**Comment by KaspervdHeijden** [comment]
Created this script for now that will work as expected

```sh
#!/usr/bin/env sh

for app in jq hyprctl; do
    if ! command -v "${app}" >/dev/null; then
        printf 'binary not found: %s\n' "${app}" >&2
        exit 127
    fi
done

monitors="$(hyprctl -j monitors)"
direction="${1:-next}"

case "${direction}" in
    next)
        offset="$(printf '%s\n' "${monitors}" | jq '.[] | select (.focused) .x + .width')"
        monitor_id="$(printf '%s\n' "${monitors}" | jq ".[] | select (.focused == false and .x == ${offset}) .id")"

        if [ -z "${monitor_id}" ]; then
            monitor_id="$(printf '%s\n' "${monitors}" | jq '.[] | select (.focused == false and .x == 0) .id')"
        fi

        ;;
    prev)
        offset="$(printf '%s\n' "${monitors}" | jq '.[] | select (.focused) .x')"
        monitor_id="$(printf '%s\n' "${monitors}" | jq ".[] | select (.focused == false and .x + .width == ${offset}) .id")"

        if [ -z "${monitor_id}" ]; then
            rightmost="$(printf '%s\n' "${monitors}" | jq 'map(.x) | max')"
            monitor_id="$(printf '%s\n' "${monitors}" | jq ".[] | select (.focused == false and .x == ${rightmost}) .id")"
        fi

        ;;
    *)
        printf 'unsupported direction "%s"\n' "${direction}'" >&2
        exit 5

        ;;
esac

if [ -z "${monitor_id}" ]; then
    printf 'could not find %s monitor\n' "${direction}" >&2
    exit 6
fi

hyprctl dispatch movecurrentworkspacetomonitor "${monitor_id}"
```

**Comment by vaxerski** [comment]
you can do `l` `r` etc. +1 -1 is just ID-based.

**Comment by KaspervdHeijden** [comment]
@vaxerski two more comments:
- Perhaps document this on the wiki? I was unable to find this information.
- It does not roll-over; after moving the window to the rightmost monitor dispatching `hyprctl dispatch movecurrentworkspacetomonitor r` does nothing, where I'd expect it to go to the left most monitor instead.

**Comment by vaxerski** [comment]
> Perhaps document this on the wiki? I was unable to find this information.

![image](https://user-images.githubusercontent.com/43317083/233074069-458ebc95-8bb0-4f3f-8996-663437cf1e50.png)
