### ISSUE TITLE
ext_workspace_unstable: zext_workspace_handle_v1.activate() is ignored

### ISSUE THREAD

**Issue by MaxVerevkin** [hyprwm/Hyprland#2084]
Relevant issue: https://github.com/hyprwm/Hyprland/issues/381

From that issue:
> The protocol itself does not support that

But I think it does? From the protocol:

> ```xml
> <request name="activate">
> 	<description summary="activate the workspace">
> 		Request that this workspace be activated.
> 
> 		There is no guarantee the workspace will be actually activated, and
> 		behaviour may be compositor-dependent. For example, activating a
> 		workspace may or may not deactivate all other workspaces in the same
> 		group.
> 	</description>
> </request>
> ```

**Comment by vaxerski** [comment]
done in 086f7249514fcbaf10247ee7bd2c5ddad643d898

rust sucks

**Comment by cyrinux** [comment]
Thanks, it works 😺
