### ISSUE TITLE
Cannot install/compile on ArcoLinux.

### ISSUE THREAD

**Issue by SovnSkyrim** [hyprwm/Hyprland#209]
According to [Installation Readme](https://github.com/vaxerski/Hyprland/wiki/Installation); the AUR has 3 packages.
- Hyprland-git : Fails to clone wlroots [Pastebin](https://pastebin.com/B4v47AHi)
- Hyprland : Errors on wlroots [Pastebin](https://pastebin.com/Dv75cwjm)
- hyprland-bin : Cannot stat 'LICENSE' [Pastebin](https://pastebin.com/5bmBPdwk)
I want to say that the latest wlroots is installed [Pastebin](https://pastebin.com/MfZG20cM)

I went ahead and tried the manual build; did the yay command found in the Installation page; removing the wlroots package as it errored and downloaded it separately as showed above.
here's the Pastebin for the make error: [here](https://pastebin.com/8JeUMYFN).

**Comment by vaxerski** [comment]
freedesktop gitlab is dead, so you cant clone wlroots. Not my fault.

for bin package errors, @ThatOneCalculator

**Comment by PowerBall253** [comment]
See <https://github.com/vaxerski/Hyprland/issues/206> for more info.

**Comment by ThatOneCalculator** [comment]
@SovnSkyrim bin package should be fixed.

**Comment by vaxerski** [comment]
should work, gitlab back

**Comment by ThatOneCalculator** [comment]
wooo lets gooo

**Comment by ThatOneCalculator** [comment]
@SovnSkyrim please test again, all packages should be fixed.

**Comment by SovnSkyrim** [comment]
@ThatOneCalculator here's the latest bin package error [Pastebin](https://pastebin.com/EfKyFEPn)
Hyprland-git went [through succesfully though](https://pastebin.com/Ses7fH40)

**Comment by ThatOneCalculator** [comment]
Ah, forgot to update the sha256sum. I'll do it in the morning.
