### ISSUE TITLE
Make a window always on top or bottom

### ISSUE THREAD

**Issue by Ariodevelop** [hyprwm/Hyprland#2093]
i want to make a transparent software using [https://tauri.app/](Tauri) and make it always on top of all windows for make my custom status bar or task bar or start menu like Windows and make an app always behind other window like wallpaper with icons on it !

**Comment by vars1ty** [comment]
Aka having the compositor to basically make it a layer-shell, which has been requested once before and IIRC it was denied.

Why Tauri for a status bar? Seems overly excessive for such a basic thing. If you want to do it yourself though, you can probably make it happen through Wayland protocols.

**Comment by vaxerski** [comment]
You'll have to redirect tauri to a LS.

Ignoring the fact it's a stupid idea of course.

> Why Tauri for a status bar? Seems overly excessive for such a basic thing. If you want to do it yourself though, you can probably make it happen through Wayland protocols.

Maybe the man got inspired by Windows making all of its UI a fucking uwp-style webapp lol

**Comment by Ariodevelop** [comment]
there is no way just make window pined bottom of screen like ubuntu dock ??

**Comment by vaxerski** [comment]
no, docks are not windows in wayland

**Comment by Ariodevelop** [comment]
What should I learn . can recommend some resources?

**Comment by vars1ty** [comment]
You do realize that Tauri isn't even intended to be used as a layer-shell, or even be treated as one?
You either go with GTK and gtk-layer-shell, or you try and make it work with Tauri through Wayland Protocols and enjoy a bar that consumes more resources than needed.

**Comment by Ariodevelop** [comment]
You are right! Consuming a lot of resources is bad in Tauri or Electron. I made a window into a dock using window rule and reserved area. But I have no idea how to make something like waybar.thank you!

**Comment by vars1ty** [comment]
https://github.com/pentamassiv/gtk-layer-shell-gir/blob/main/gtk-layer-shell/examples/simple-example.rs
Good luck from here on, it's fairly easy with most things.
