### ISSUE TITLE
How to get a "scratchpad" ? A floating terminal toggle by the same keybind.

### ISSUE THREAD

**Issue by TTtrace** [hyprwm/Hyprland#2096]
I want to have a floating terminal every time I keystroke SUPER+grave:

![image](https://user-images.githubusercontent.com/39454079/232846643-fac7edc3-b5f0-4fc4-911e-42813ecf615e.png)

So I bind this:

```
bind = $mainMod, grave , exec , [ float  ; size 60% 50% ] kitty
```

But this bind has a problem that I cannot close it with the same key bind, which I have been used to (from [dwm](https://dwm.suckless.org/patches/scratchpad/)). Even if I bind another key to close it like :

```
bind = $mainMod_SHIFT, grave , killactive,
```

It is quite possible to close other working windows, incorrectly. Is there any way in Hyprland for this need?

By the way, whenever I open a new window, it will break my full screen mode ( 'monocle' layout)  back into master layout. It is really annoying, is there any solution for that?

**Comment by vaxerski** [comment]
1) move it to the special workspace and bind toggling it to super + grave

2) no

**Comment by TTtrace** [comment]
> 1. move it to the special workspace and bind toggling it to super + grave

Thanks for your answer, it helps!
