### ISSUE TITLE
ext_workspace_unstable: hidden/urgent workspace state always false

### ISSUE THREAD

**Issue by AndreasBackx** [hyprwm/Hyprland#2102]
I was looking into the following issue and as a result dove a bit into the Waybar code, the Wayland unstable protocol that's still WIP, and slightly in Hyprland: https://github.com/Alexays/Waybar/issues/2121. The initial problem there is that Waybar is not setting the `.visible` class on workspaces retrieved via `ext_workspace_unstable`. The spec being used by Hyprland (which is not the latest) doesn't have a specific "visible" field, though it can be assumed "visible" if it's not hiddden I would assume (the spec isn't entirely clear).

Is it therefore perhaps possible to set hidden to true in case the workspace is not visible on the screen? Then a PR can be proposed in Waybar to set add the `.visible` class if it's not hidden. I've had a quick look through the code and it doesn't seem trivial to me to determine whether a workspace is "visible" or not.

In the same branch I noticed that "urgent", the other available state, is also always false. Perhaps both can be tackled at the same time?

**Comment by vaxerski** [comment]
urgent is not always false. It's true when an app requests attention.

**Comment by AndreasBackx** [comment]
> urgent is not always false. It's true when an app requests attention.

You're right, my apologies. I overlooked some uses: https://github.com/search?q=repo%3Ahyprwm%2FHyprland%20wlr_ext_workspace_handle_v1_set_urgent&type=code. Thanks for mentioning!

**Comment by AndreasBackx** [comment]
@vaxerski I'm happy to provide a PR for this, though I'm not a great C++ developer. Could you explain how I could check whether a workspace is visible? Then I might be able to add support for this.

**Comment by vaxerski** [comment]
idk maybe the aptly named `CCompositor::isWorkspaceVisible`

**Comment by vaxerski** [comment]
the protocol has been dropped so closing
