### ISSUE TITLE
XDG_RUNTIME_DIR is not set error while installing Hyprland

### ISSUE THREAD

**Issue by HarshvardhanJ** [hyprwm/Hyprland#2104]
I was trying to install Hyprland on Manjaro and faced some roadblocks! I have a Nvidia GTX 1060, so when I installed nvidia-dkms driver and rebooted it got stuck at ```dev/sda1: clean, 552599/6111232 files, 7119295/24414464 blocks```, so then I uninstalled the dkms drivers and then reinstalled my linux61-nvidia drivers and now my pc was able to boot.

Next I ran Hyprland command and i got the following error:
```
00:00:00.000 [ERROR] [libseat] [libseat/backend/seatd.c:66] Could not connect to socket /run/seatd.sock: Permission denied
00:00:00.000 [INFO] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
00:00:00.008 [INFO] [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
00:00:00.008 [INFO] [backend/session/session.c:109] Successfully loaded libseat session
00:00:00.010 [ERROR] [backend/backend.c:216] Found 0 GPUs, cannot create backend
00:00:00.010 [ERROR] [backend/backend.c:382] Failed to open any DRM device
terminate called after throwing an instance of 'std::runtime_error'
  what():  wlr_backend_autocreate() failed!
segmentation fault (core dumped)
```
i was getting this error even though **seatd** was installed and running. Then I figured out that seatd can only be ran as sudo (idk why this is happening) but running ```sudo Hyprland``` fixed the previous issue but now I get this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  XDG_RUNTIME_DIR is not set!
aborted
```
I searched alot but couldn't find any solution for this. Please HELP!

**Comment by vaxerski** [comment]
consider reading the nvidia wiki page.

at any rate, Nvidia is not supported.
