### ISSUE TITLE
Don't resize on movewindow

### ISSUE THREAD

**Issue by hotsno** [hyprwm/Hyprland#2105]
I think it would be nice to have an option to not resize the windows to their floating size when moving a window. 

To demonstrate why, here's a video where I have the browser's floating size to something pretty small, and the terminal's floating size nearly identical to its original size. Dragging the browser is pretty jarring since it has to resize so much. 

Optionally maybe a little animation can be added when the moving begins (like pops in and out a bit) to indicate the window is getting dragged/just to look nice.

Sorry for the low FPS I recorded at 5k on my iGPU lol

https://user-images.githubusercontent.com/71658949/233253402-bb41cb43-b24e-4f43-803b-6f5e354a5b71.mp4

**Comment by zjeffer** [comment]
I think a good solution might be to allow the user to specify how big (relative to the desktop size) the window should always be resized to while dragging. 

This isn't just annoying with small sizes: if I have a big floating window on my high resolution monitor, and I tile it on my smaller resolution monitor, and then moved the tiled window on that monitor, the window is extremely huge (bigger than the desktop's resolution) while dragging.
