### ISSUE TITLE
Master layout: `always_center_master` no longer works

### ISSUE THREAD

**Issue by Amatrelan** [hyprwm/Hyprland#2108]
Commits between [4bc3f9ad and b1580351](https://github.com/hyprwm/hyprland/compare/4bc3f9ad...a4330fe3) broke something so `always_center_master` don't work anymore, in master layout.

**Comment by LDAP** [comment]
You can use `git bisect` to find the last working commit.

**Comment by vaxerski** [comment]
patches welcome

**Comment by hannesaronsson** [comment]
It is not working for me either anymore.
