### ISSUE TITLE
Custom transparent app background windowrule

### ISSUE THREAD

**Issue by SpomJ** [hyprwm/Hyprland#2109]
Probably already partially implemented by blur_new_optimizations.

Basically what it should do is instead of sampling default background (wallpaper) for transparent window, sample some other (unrendered by default) layer, essentially making window have a different wallpaper.

Would be useful to preload some custom wallpaper effect, like posterize or color correction for better visibility, instead of just default blur.

like this (using blur_new_optimizations):
![20230420_14h19m57s_grim](https://user-images.githubusercontent.com/75751809/233351503-53a13017-6d72-4414-9479-398e0e41e101.png)

## Advanced stuff

This can ascend beyond just xray and make other windows visible, but would require some tinkering.

**Comment by vaxerski** [comment]
I don't think this has a place in the core, but a plugin can definitely be made for this

**Comment by SpomJ** [comment]
Probably, I can do neither of those, so...

**Comment by vaxerski** [comment]
you'd have to get into my brain to fully understand that.

matter of niche vs cool. This is too niche and not cool enough to justify, imo

**Comment by SpomJ** [comment]
probably a better example
![20230420_22h35m23s_grim](https://user-images.githubusercontent.com/75751809/233470236-f8d62933-7387-4f50-9c71-8d14ada339a9.png)

**Comment by SpomJ** [comment]
> you'd have to get into my brain to fully understand that.
> 
> matter of niche vs cool. This is too niche and not cool enough to justify, imo

How do you know? It could be that everyone would want it, they just never thought of it. Also I thought this belongs to core because of how little do you actually need to change (what you see on examples is basically utilizing a half-bug)

**Comment by Duckonaut** [comment]
Was cool enough for me to do as a [plugin](https://github.com/Duckonaut/hyprlens). Check it out. No support for different shared BGs for different windows with windowrules rn, might do that if it's a popular enough request

**Comment by vaxerski** [comment]
plugin
