### ISSUE TITLE
Intellij idea missing the cursor after some actions

### ISSUE THREAD

**Issue by YinAqu** [hyprwm/Hyprland#2110]
Intellij idea not yet supports native wayland, but running on X.
After certain actions, e.g. override methods popup then exit with ESC, import on the fly with vim plugin installed, the cursor disappears, in this situation, we can't edit files any more, all shortcuts will take no effect, until open some tool popup or just restart idea.
```
os: arch 
hyprland version: rolling
idea: IntelliJ IDEA 2023.1 (Ultimate Edition)
```
BTW, popup triggers the problem in below videos is `override methods`, its default shortcut is ctrl-o. There's no this problem on sway(may help for addressing).
without vim plugin:

https://user-images.githubusercontent.com/16650765/233361035-2b03a95d-215a-49fc-9e61-395fd2728cc6.mp4

vim plugin installed:

https://user-images.githubusercontent.com/16650765/233361493-c2322d6d-3c08-4113-93db-b62736f0e8ec.mp4

**Comment by kehrazy** [comment]
Not a Hyprland issue.

**Comment by YinAqu** [comment]
@kehrazy But why? both on sway and dwm on my same laptop all goes well.

**Comment by YinAqu** [comment]
See #933, add below windowrules fix this for me:
```
# Jetbrains products
windowrulev2 = float,floating:0,class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = float,class:^(jetbrains-.*),title:^(Welcome to.*)
windowrulev2 = center,class:^(jetbrains-.*),title:^(Replace All)$
windowrulev2 = forceinput,class:^(jetbrains-.*)
windowrulev2 = windowdance,class:^(jetbrains-.*) # allows IDE to move child windows
```
