### ISSUE TITLE
Cursor themes with a space in the name cannot be set via hyprctl.

### ISSUE THREAD

**Issue by Aproxia-dev** [hyprwm/Hyprland#2111]
title

Steps to reproduce:
- `hyprctl setcursor "Phinger Cursors" 24`

Expected outcome:
- Setting the cursor theme to Phinger Cursors, size 24.

Noted outcome:
- > `size not int`

**Comment by Aproxia-dev** [comment]
from what i can tell from my bit of code digging, the issue is that the request connects the command arguments into a string, getting rid of the quotes and what not. Then when looking back at the request arguments, the code simply goes through the request and splits it every time there's a space.

i wanted to try and fix it myself, but it seems like the only way to fix it would be to make some major changes to the `request()` function and considering that i can barely make a node graph i just decided to dip and report the bug instead.

**Comment by vaxerski** [comment]
are cursor themes even allowed to have spaces?

**Comment by Aproxia-dev** [comment]
oh oops seems like they aren't

but at least adding support for changing the cursor theme via the pretty name should be added imo. yk, it confused me and i feel like it's safe to assume that it might confuse others. but at that point it's more of a feature request.

**Comment by vaxerski** [comment]
I don't think that's possible on my side as I just `wl_cursor_theme_load` and I don't feel like being all windows and parsing all the cursor themes myself

**Comment by vaxerski** [comment]
fixed in 510db64860fa307e33db5fdb843c6cc5a428b5a4 if your theme _really_ has a space in the name.
