### ISSUE TITLE
Resizing with mouse unintuitive if you grab the 'wrong' side of the window

### ISSUE THREAD

**Issue by Ashe** [hyprwm/Hyprland#2112]
Hello, I was wondering if this is feasible - currently, resizing a tiled window is really unintuitive in comparison to a floating window, as pointed out by PR #1347 .

When floating, the position of the cursor vs the container matters - if you click on the right half of the window it'll grow the window if you drag right, and shrink if you go left. If you grab the left half, it does the opposite.

When tiles however, you can grab the 'wrong' side of a window and the resize mechanism is the opposite. It also makes it hard to change the 'splits', since it means you have to figure out which window controls said split.

If you enable `resize_on_border` the issue is worsened - depending on which part of the gap you drag, you will either get the right or wrong functionality. I'd expect dragging the gap to always allow you to move the split, rather than disturbing some other split. This is just me considering horizontal splits, but as soon as you include vertical the problem gets worse as it could be the correct window for one and not the other.

I believe this is the case in `sway` and even though I hate to do direct comparisons, I do think it would make this a little nicer to daily drive.

Thank you for your hard work :slightly_smiling_face: 

---

### Summary

* Please make it so that the mouse's position is taken into account when resizing a tiled window such that you are stretching the window with the mouse:
  * Dragging right on the right side of the window will grow, and left would shrink.
  * This will mimic the way it's done for floating windows
* Visualised another way, it should look like you're manipulating the splits between windows:
  * Find the closest window corner to where the cursor clicks and change the position of the splits such that the window's corner follows the mouse

Thanks!

**Comment by Ashe** [comment]
Another weird thing I've encountered is with `hyprctl`. 

On a floating window, `hyprctl dispatch resizeactive exact 0 0` makes it tiny, as expected. Likewise, `hyprctl dispatch resizeactive exact 2560 1440` sets it to that size. Perfect!

On a tiled window however, these commands do the *opposite*. `hyprctl dispatch resizeactive exact 2560 1440` shrinks the window into the bottom right of my screen, and `hyprctl dispatch resizeactive exact 0 0` makes the window take up almost half my screen. I know tiled windows may not be able to reach the values you input, but it would be nice to try and grow and shrink other windows in available directions to reach it. For instance, if there's only a row of windows, then `exact` can't really change the vertical height as it'll be clamped to monitor size.

**Comment by vaxerski** [comment]
Yes, it's not perfect, and this is a reasonable thing to do, but it's not a high priority thing. I have other things to worry about too. Feel free to open a MR.

**Comment by DanielAdolfsson** [comment]
Maybe we can close this now?
