### ISSUE TITLE
Floating windows don't adhere to follow_mouse = 2

### ISSUE THREAD

**Issue by dann-merlin** [hyprwm/Hyprland#2113]
Steps to reproduce:

I think this video sums it up:
https://user-images.githubusercontent.com/55287004/233487707-c105fa75-8fcc-40a3-aa51-da759c8d3b68.mp4

I would expect with `follow_mouse = 2` it would not change focus when only hovering over another window with the mouse.
However it does. Note that this only happens when moving to/away from a floating window.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#input-1

float_switch_override_focus default 1
