### ISSUE TITLE
Cursor themes with spaces are not accepted by hyprctl command ?

### ISSUE THREAD

**Issue by MrDisguised** [hyprwm/Hyprland#2116]
I updated my `hyprland-nvidia-git` to the [latest commit](https://github.com/hyprwm/Hyprland/commit/510db64860fa307e33db5fdb843c6cc5a428b5a4) . I tried to add the `Breeze Light` cursor theme (which is my favourite cursor theme) but it didn't work. I don't know why it is happening. Any clue ? - 
<br>

https://user-images.githubusercontent.com/128170542/233540066-644e288d-de8a-4ba5-921c-5d92aed921ae.mp4

**Comment by Aqa-Ib** [comment]
#2111

**Comment by vaxerski** [comment]
breeze light is not the name of that cursor. That's the pretty name.

**Comment by MrDisguised** [comment]
> breeze light is not the name of that cursor. That's the pretty name.

It was `Breeze_Snow` nvm.
