### ISSUE TITLE
Error setting value <WLR_NO_HARDWARE_CURSORS,1< for field <env>: No such field. Hyprland may not work correctly.

### ISSUE THREAD

**Issue by cakarmustactalone** [hyprwm/Hyprland#2118]
Here is my setup in arch-linux ,nvidia optimus laptop

```
DE: Hyprland 
WM: sway 
Theme: Arc-Dark [GTK2/3] 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
GPU: Intel HD Graphics 630 
Memory: 1.94GiB / 7.65GiB (25%) 
GPU Driver: i915 
```
 
I have done everything what hyprland wiki page for nvidia states. Here is my env variables:

```
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
```
And I got these error for every environment variable that related with nvidia. 

Btw I use **envycontrol** to switch between drivers but I could not switch to nvidia driver.

What you recommend for this issue?

Thanks!

**Comment by Duckonaut** [comment]
What version are you running? This issue could be caused by running a severely outdated hyprland

**Comment by vaxerski** [comment]
that's precisely the issue
