### ISSUE TITLE
Request to Update Wlroots Stack for Resolving Game Stuttering Issue??

### ISSUE THREAD

**Issue by Edgars-Cirulis** [hyprwm/Hyprland#2119]
Hello there,

I would like to request an update for the wlroots stack.

I have been testing sway with the latest version of wlroots, and it appears that the game stuttering issue has been resolved. However, when I tried to rebase wlroots on the same commit point and revert some commits on sway, I noticed that the game started stuttering again. Therefore, I believe that updating the wlroots stack could fix the stuttering issue in Apex.

**Comment by vaxerski** [comment]
sure, d03dcc3d99418db415e03c8f2bb7a3ca6e261866

**Comment by Edgars-Cirulis** [comment]
> sure, [d03dcc3](https://github.com/hyprwm/Hyprland/commit/d03dcc3d99418db415e03c8f2bb7a3ca6e261866)

Keep in mind

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4069

**Comment by Edgars-Cirulis** [comment]
Fix compilation

**Comment by vaxerski** [comment]
compiles just fine for me doe

**Comment by Edgars-Cirulis** [comment]
> compiles just fine for me doe

[323/422] Compiling C object libwlroots.so.12032.p/xcursor_xcursor.c.o
FAILED: libwlroots.so.12032.p/xcursor_xcursor.c.o 
cc -Ilibwlroots.so.12032.p -I. -I.. -Iinclude -I../include -Iprotocol -I../protocol -Irender/gles2/shaders -Irender/vulkan/shaders -Ibackend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O3 -DWLR_USE_UNSTABLE -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../= -fPIC -MD -MQ libwlroots.so.12032.p/xcursor_xcursor.c.o -MF libwlroots.so.12032.p/xcursor_xcursor.c.o.d -o libwlroots.so.12032.p/xcursor_xcursor.c.o -c ../xcursor/xcursor.c
../xcursor/xcursor.c: In function ‘xcursor_load_theme’:
../xcursor/xcursor.c:597:39: error: ‘%s’ directive output between 7 and 7 bytes may cause result to exceed ‘INT_MAX’ [-Werror=format-truncation=]
  597 |         snprintf(full, full_size, "%s/%s/%s", dir, subdir, file);
      |                                       ^~
......
  765 |                 full = xcursor_build_fullname(dir, "cursors", "");
      |                                                    ~~~~~~~~~
../xcursor/xcursor.c:597:41: error: ‘/’ directive output between 1 and 1 bytes may cause result to exceed ‘INT_MAX’ [-Werror=format-truncation=]
  597 |         snprintf(full, full_size, "%s/%s/%s", dir, subdir, file);
      |                                         ^
cc1: all warnings being treated as errors
[332/422] Compiling C object libwlroots.so.12032.p/xwayland_xwm.c.o

**Comment by vaxerski** [comment]
that's a wlroots problem

**Comment by Edgars-Cirulis** [comment]
Weird it compiles fine in sway

**Comment by vaxerski** [comment]
I reported it to wlr https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3637

> Weird it compiles fine in sway

It compiles fine for me too, something's up with gcc warnings I guess.
