### ISSUE TITLE
nix build broken until nixpkgs#226283

### ISSUE THREAD

**Issue by Kiskae** [hyprwm/Hyprland#2120]
Just creating a tracking issue since the recently updated wlroots depends on wayland 1.22, which isn't yet upstream in nixpkgs.

Will be fixed by https://github.com/NixOS/nixpkgs/pull/226283 or by pinning the hyprland flake to `2df0d034bc4a18fafb3524401eeeceaa6b23e753` (the last commit before the wlroots update)

**Comment by Thiago-Assis-T** [comment]
@Kiskae , I have a configuration that is kinda diferent, my home manager is inside my configuration.nix and I don't use flakes, from the wiki I followed the step to not use flake, is there a way I can pin the package to the commit you specified or mark the package to not update yet? if you want to look at my config it is at [my-config](https://github.com/Thiago-Assis-T/nixos-config) and it is far from complete and I wasn't even messing around with hyprland, I was just trying to install brave (my presonal broweser) alongside google chrome(Wich I need for work) but because of the way I made my config I can only update home-manager with `nixos-rebuild` command, my goal is to have evrething I need to build and configure my system at a repo, so far it worked fine, until this outdated wayland package

**Comment by Kiskae** [comment]
I believe that replacing `master` with the full commit hash would work, so `builtins.fetchTarball "https://github.com/hyprwm/Hyprland/archive/2df0d034bc4a18fafb3524401eeeceaa6b23e753.tar.gz";`

**Comment by tasmo** [comment]
How to fix this in a global `/etc/nixos/flake.nix`?

```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    nixos-hardware.url = "nixos-hardware/master";
    hyprland.url = "github:hyprwm/Hyprland";
    home-manager.url = "github:nix-community/home-manager";
  };

```

**Comment by Kiskae** [comment]
`github:hyprwm/Hyprland/2df0d034bc4a18fafb3524401eeeceaa6b23e753`

**Comment by SrEstegosaurio** [comment]
Even after pinning the Hyprland flake to the relevant commit I get the same error, as if it has zero effect.
What am I missing?

Thanks.

**Comment by Kiskae** [comment]
Look in your `flake.lock` file and make sure the `<hyprland-flake>.locked.rev` field matches the commit specified above. If there are multiple entries or they don't match then your flake is still using the wrong source.

**Comment by SrEstegosaurio** [comment]
Thanks, it works now. :)

**Comment by Thiago-Assis-T** [comment]
> I believe that replacing `master` with the full commit hash would work, so `builtins.fetchTarball "https://github.com/hyprwm/Hyprland/archive/2df0d034bc4a18fafb3524401eeeceaa6b23e753.tar.gz";`

My man,it worked, thank you very much for the tip

**Comment by WilliamBehrens** [comment]
If someone doesn't see this issue this bugs out in some interesting way. I spent the last three days debugging my nixos config as I thought I did something wrong.

if running `glxinfo | grep "OpenGL renderer"` gives back `llvmpipe` it means that the commit isn't pinned in nix and you're using software rendering. Maybe make this a pinned issue?

**Comment by Kiskae** [comment]
If someone tries to use a newer revision it would fail to build since the `wlroots` dependency can't find the new version of wayland. As far as I know hyprland itself wouldn't be involved with the output of `glxinfo` since that gets handled by `xwayland`.

**Comment by GrabbenD** [comment]
> If someone doesn't see this issue this bugs out in some interesting way. I spent the last three days debugging my nixos config as I thought I did something wrong.
> 
> if running `glxinfo | grep "OpenGL renderer"` gives back `llvmpipe` it means that the commit isn't pinned in nix and you're using software rendering. Maybe make this a pinned issue?

I updated the nixos channel and my secondary GPU became my primary. The second GPU is headless and its drivers are blacklisted. Because of this I get `llvmpipe` as my renderer. Updating Hyprland to latest commit doesn't fix this issue either.

Has anyone experienced this?

**Comment by GrabbenD** [comment]
Turns out llvmpipe/software rendering in my case is a separate issue: https://github.com/hyprwm/Hyprland/issues/2170

**Comment by n3oney** [comment]
hi, #2138 for some reason doesn't help me. I still get issues about 1.22.
![image](https://user-images.githubusercontent.com/30625554/235379177-90a6ff41-cc7a-4498-a1b3-a0b21c6d749c.png)
If I'm understanding it right, I should be able to just use github:hyprwm/hyprland without locking to a specific commit now, right?

**Comment by Kiskae** [comment]
The fix only applies to the packages exported by the flake, which are the ones used by default by the nixos module. So unless you are providing your own version of the hyprland package it should be fixed on master.
