### ISSUE TITLE
Fullscreen for new windows

### ISSUE THREAD

**Issue by Rolv-Apneseth** [hyprwm/Hyprland#2122]
Hi, just wondering if this is possible already (I couldn't find it in the docs or issues here) or perhaps it could just be scripted somehow, but basically with fullscreen mode on and `inherit_fullscreen = true`, I would like a newly opened window to not break me out of fullscreen mode, as I would like to use it as a monocle layout.

Apologies if this is already outlined somewhere and I missed it.

**Comment by bradrn** [comment]
I’d really like this too. I’ve come to Hyprland from XMonad, which allows me to switch a workspace between a master layout and a fullscreen/monocle layout, and I find myself missing that feature a lot in Hyprland. It’s really useful for e.g. switching to fullscreen mode for editing a document, then switching back to compare it to another window.

**Comment by charbelnicolas** [comment]
I'm trying to migrate from awesome wm to hyprland and I'm really missing a fullscreen/monocle layout. I hope something of the like gets implemented sooner rather than later :)

**Comment by clotodex** [comment]
I hope I got right what you mean. I am using this
`bind = $mainMod, return, fullscreen,1`
I am coming from qtile and this is very similar - even better you can also use fake-fullscreen to toggle apps internal fullscreen mode independently of their actual fullscreen-ness

However I have the problem that new windows dont automatically "come to front" so instead I am using pyprlands center layout (which emulates the effect through floating - so the rest of the windows are kept in their layout)

**Comment by Rolv-Apneseth** [comment]
Not quite there for me personally. Opening a new window like you said won't focus it, it triggers the full-screen mode for the application (personally don't like this), and closing a program will kick you out of full-screen mode.

Thanks for pointing out [pyprland](https://github.com/hyprland-community/pyprland) though, gonna have a look at it

**Comment by clotodex** [comment]
If you set fullscreen to '1' (not 0 or 2) then the fullscreen state of the application is not triggered

Otherwise something that annoys me is that closing the window kills the fullscreen mode

**Comment by Rolv-Apneseth** [comment]
But then unfortunately that doesn't cover the bar. Just yeah, for me personally a proper monocle layout would be great. I'm not the one developing this fantastic window manager though, so I am happy to wait for a better solution.

**Comment by nktnet1** [comment]
@clotodex 
> However I have the problem that new windows dont automatically "come to front" so instead I am using pyprlands center layout (which emulates the effect through floating - so the rest of the windows are kept in their layout)
> ...
> Otherwise something that annoys me is that closing the window kills the fullscreen mode

I think this should now be fixed (for fullscreen mode 1, aka "maximise") with #6870 merged.

> closing a program will kick you out of full-screen mode

Once #6880 gets merged, I think this will be resolved too (by enabling the `misc:exit_window_retains_fullscreen` variable/option).

Agreed on having a monocle layout, but perhaps that is better tracked in #2050 as you've mentioned.

**Comment by Rolv-Apneseth** [comment]
> @Rolv-Apneseth once #6880 gets merged, I think this will be resolved too (by enabling the `misc:exit_window_retains_fullscreen` variable/option).

Oh nice, thanks for pointing that one out

> Agreed on having a monocle layout, but perhaps that is better tracked in #2050 as you've mentioned.

Yeah I'll go ahead and close this one, and just subscribe to that issue
