### ISSUE TITLE
Crashing if I open to many windows

### ISSUE THREAD

**Issue by tuzu128** [hyprwm/Hyprland#2124]
When I open too many windows hyprland crashes.

Hyprland version: 0.24.1-1
[log](https://github.com/hyprwm/Hyprland/files/11300672/hl.log)

**Comment by tuzu128** [comment]
Ok here it is
[hyprlandCrashReport598.txt](https://github.com/hyprwm/Hyprland/files/11302914/hyprlandCrashReport598.txt)

**Comment by vaxerski** [comment]
it's fixed in -git already
