### ISSUE TITLE
Opacity window rule only applies on windows in focus

### ISSUE THREAD

**Issue by Feel-ix-343** [hyprwm/Hyprland#2131]
Reproduce:
1. with an app, google chrome, installed, add `windowrulev2 = opacity 0.95, class:^(google-chrome)$
`
2. (re)launch the app. 
3. Notice that while it is in focus it is transparent, but when it is out of focus it is opaque

**Comment by vaxerski** [comment]
`0.95 0.95`

**Comment by Feel-ix-343** [comment]
oops thank
