### ISSUE TITLE
Pinned floating windows no longer fullscreen

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/Hyprland#2133]
I'm running the latest git master of Hyprland and have noticed that recently I am no longer able to use my fullscreen keybind on my mpv window which uses a rule to resize and position mpv then float and pin it. It used to work with fullscreen .
To test it out I temporarily floated and pinned foot and it would no longer let me fullscreen it either.
All other windows allow my fullscreen toggle just not pinned floating windows.

If it helps my [Hyprland.conf ](https://codeberg.org/JustineSmithies/hyprland-dotfiles/src/branch/master/.config/hypr/hyprland.conf)

**Comment by vaxerski** [comment]
you are not allowed to fullscreen pinned windows by design.

**Comment by justinesmithies** [comment]
Ah okay Yeah. Oops sorry so it was broken before and fixed now ;)
I'll just amend my config.
