### ISSUE TITLE
Swapping workspaces between monitors with one workspace having a fullscreen window causes status bar display problem

### ISSUE THREAD

**Issue by tsemczyszyn** [hyprwm/Hyprland#2144]
I'm not sure if this is related to #2077 or not so I'm just opening a separate issue.

Steps to reproduce:
On a setup with two monitors and waybar displayed on both monitors make a window fullscreen on one display.
Then, swap the workspaces between monitors using swapactiveworkspaces.

Expected outcome:
The swap happens with the fullscreen window moving to the other monitor.

Noted outcome:
The swap happens, but the status bar remains absent on the monitor that formerly had the fullscreen window. Likewise the status bar is overlayed on top of the fullscreen window on its new display. Swapping back and un-fullscreen'ing the window fixes the issue.

**Comment by vaxerski** [comment]
check with 247ff4e60df15c167f0f6b6b2d899aa22101b2a5

**Comment by tsemczyszyn** [comment]
Yes that seems to have resolved the issue. Thanks.
