### ISSUE TITLE
swww wallpaper disappears under transparent window

### ISSUE THREAD

**Issue by jacekpoz** [hyprwm/Hyprland#2147]
https://user-images.githubusercontent.com/64381190/234231235-7bf6154b-e912-4800-ab9d-9bbb29e9ad68.mp4

this also happens with multiple windows, the gaps still have the wallpaper

doesn't happen when the window is floating

**Comment by jacekpoz** [comment]
doesn't happen with hyprpaper, I also restarted swww and it fixed itself, gonna try relogging and checking again

**Comment by jacekpoz** [comment]
relogged and it fixed itself, if anyone else gets this too feel free to reopen

**Comment by Rolv-Apneseth** [comment]
I'm getting what I believe is a similar issue where the previous wallpaper is what's shown under a transparent `wezterm` window until the wallpaper is changed again. Seems to happen sometimes when the wallpaper is changed while I'm not on a workspace with a transparent window in it, as I never see it happen live but I do notice it multiple times a day as I have the wallpaper change every 30 minutes (using `wpaperd` if that makes any difference). I unfortunately can't find steps to specifically trigger it so not sure if anything can even be done.
