### ISSUE TITLE
x11 application's font still blurry in 4K resolution

### ISSUE THREAD

**Issue by Rainff9f58ff178** [hyprwm/Hyprland#2148]
i'v followed this post:https://wiki.hyprland.org/Configuring/XWayland/
add 
```
# change monitor to hires, the last argument is the scale factor
monitor=,highres,auto,2

# sets xwayland scale
exec-once=xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2

# toolkit-specific scale
env = GDK_SCALE,2
env = XCURSOR_SIZE,32
```
to my config file .but x11 application seem scaled to four times and still blurry
 when i change `monitor=,highres,auto,2` to `monitor=,highres,auto,1`,x11 apliication scaled to 2 times and look fine .but wayland native app get smaller.
what happen .how to fix it .T_T

**Comment by vaxerski** [comment]
@fufexan 

HiDPI patches are pretty unstable in general from what I know and I would not recommend them personally. I'd rather stick to native wayland apps and just bite the bullet in apps that cannot run thru wl

**Comment by Rainff9f58ff178** [comment]
i install this package `hyprland-hidpi-xprop-git`,and work fine now

**Comment by mukesh-jadhav** [comment]
Just install the package and its done? any hyprland configuration required?
