### ISSUE TITLE
binding ALT and SUPER with a number with different kb layout won't work!

### ISSUE THREAD

**Issue by nimaaskarian** [hyprwm/Hyprland#2151]
- Steps to reproduce 
1. `bind = SUPER ALT, 1, workspace, 11` (1 can be any number and you can bind it to anything, exec, movetoworkspace, etc)
2. Have kb_layout set to us, ir 
3. Switch to `ir`
4. Simply press the binded key
- Expected outcome
to the bind to work no matter what layout is selected.
- Noted outcome
1. Wouldn't work.
2. Switch to `us` layout
3. Works just fine

**Comment by vaxerski** [comment]
use `wev` to get the keysym name. You probably have another one of those idiotic layouts that requires shift+number to actually print numbers, so you do not have number keys by default
