### ISSUE TITLE
[winecfg] window not fully showed and mouse click not work

### ISSUE THREAD

**Issue by yfaimisaka** [hyprwm/Hyprland#2153]
**Problem**:
- run `winecfg` but got window not rendered fully(as pic bellow), and `mouse click not work` on the winecfg window
- tried `sway`, worked fine
- tried
`windowrulev2 = forceinput, title:^(Wine configuration)$`
`windowrulev2 = tile, title:^(Wine configuration)$`
still not work
<img src="https://user-images.githubusercontent.com/95036645/234503228-69dbe3f1-78cb-433c-9387-460a690d1a46.png" height=400 weight=450/>

**Comment by TheSunCat** [comment]
The window size issue is tracked in #2128, but I've never had mouse input trouble with WINE windows.

**Comment by vaxerski** [comment]
`nomaxsize` fixes the sizing issue, for input, it doesn't seem to be in focus on the screenshot

**Comment by yfaimisaka** [comment]
After reboot my pc, then run `winecfg`, mouse click works well and cannot reproduce :confused: . 
It seems have relevance to my cpu or memory or something else?(as "mouse click not work" normally comes after resuming from hibernation)

Anyway, there is nothing to do with hyprland.

**Comment by FrnkPsycho** [comment]
If anyone experienced similar bug like mouse click not working / cursor disappearing / window freezing on wine windows, try set your main monitor ( or which the wine window spawns ) to position 0x0 and it might work. 

The reason I found this is that I unplugged my external monitor and my laptop monitor isn't set to 0x0, and all the wine window spawn in laptop monitor becomes buggy.
