### ISSUE TITLE
Controlling background and foreground transparency

### ISSUE THREAD

**Issue by Hyperlegs** [hyprwm/Hyprland#2159]
It's quite trivial to change window opacity, however it doesn't differentiate between the foreground and the background.
Is there a way to set a specific opacity for the background while maintaining the opacity of the foreground? Or perhaps allowing each window instance to override the general setting. For example, allowing your terminal, in which separating opacities is simple, to override your Hyprland config.

**Comment by vaxerski** [comment]
what?

**Comment by Hyperlegs** [comment]
For example, if I change the active window's opacity setting to 0.1, and open a terminal, the text itself also becomes transparent. Is there a way to avoid this?

**Comment by vaxerski** [comment]
No. You'll have to ask the terminal app to render its background at 0.1 opacity.

**Comment by Hyperlegs** [comment]
How to allow any app to override Hyprland's config? I've tried defining this behavior in the terminal's config files, but nothing changes.

**Comment by vaxerski** [comment]
An app cannot override hyprland's config.

**Comment by Hyperlegs** [comment]
So what I'm trying to achieve here is impossible with Hyprland?

**Comment by vaxerski** [comment]
It is possible, set the opacity as 1 and control the background opacity in your terminal app.

![image](https://user-images.githubusercontent.com/43317083/234698631-7cb4afbd-24c2-461e-ba35-68b7194332c4.png)

Are you drunk?

**Comment by Hyperlegs** [comment]
Possibly. Probably just retarded. Please delete this post from existence
