### ISSUE TITLE
BUG: footclient doesn't apply the settings from 'hyprctl setcursor'

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#2160]
## DESCRIPTION

This works
```sh
hyprctl setcursor $cursor_theme $cursor_size
foot
```

This doesn't → setcursor settings will be ignored.

```sh
hyprctl setcursor $cursor_theme $cursor_size
foot --server
footclient
```

## HOW TO REPRODUCE

```sh
# Make it fail
yay -S foot
foot --server
footclient

# Make it work
foot
```
Clarification: I'm speaking about cursor size, specifically.

**Comment by vaxerski** [comment]
Not a bug.

From the wiki:
![image](https://user-images.githubusercontent.com/43317083/234863812-b6b2eaaa-129b-40a4-a9a2-89dac9aea816.png)

**Comment by Zeioth** [comment]
I'm not sure foot is a GTK application. Also, all my GTK applications scale correctly. I have:

```
$system_theme              = 'Arc-Dark'
$system_icons              = 'Numix-Square'
$system_dpi_scaling_factor = 2.6
$cursor_size               = 108
$cursor_theme              = Adwaita
$gnome-schema = org.gnome.desktop.interface
exec {
  gsettings set $gnome-schema gtk-theme $system_theme
  gsettings set $gnome-schema icon-theme $system_icons
  gsettings set org.gnome.desktop.interface text-scaling-factor $system_dpi_scaling_factor
  gsettings set $gnome-schema cursor-theme $cursor_theme
  gsettings set org.gnome.desktop.interface cursor-size $cursor_size
}
```

**Comment by Zeioth** [comment]
Also you have the fact that running 'foot' scales correctly. It is

    foot --server
    footclient

That doesn't scale. Something is going on with that speficic application. I'll ask the author for clues.

**Comment by Zeioth** [comment]
![screenshot_2023-04-27_16-10-52_252590125](https://user-images.githubusercontent.com/3357792/234889291-2fe140fd-7875-4d11-b4ca-0d6b5a2f74c6.png)
![screenshot_2023-04-27_16-11-07_791190310](https://user-images.githubusercontent.com/3357792/234889295-f7d647df-6058-4776-a883-38aa61ac67ef.png)

**Comment by vaxerski** [comment]
It's not "just gtk" but more like "some apps"

Make sure to set `XCURSOR_SIZE` to your cursor size too.

**Comment by Zeioth** [comment]
XCURSOR_SIZE actually fixed footclient, thank you so much!!

I'm currently trying to figure out how to resize obs hyprland-share-pickr. It is the last one I need to fix to have everything reescaled correctly. 
![a](https://user-images.githubusercontent.com/3357792/234903498-c7cb4910-e5e1-44d8-9290-61da1bfdf483.png)

Running this script on the terminal fixes it.

```
sleep 1
killall xdg-desktop-portal-hyprland
hyprctl dispatcher exec /usr/lib/xdg-desktop-portal-hyprland
sleep 2 
hyprctl dispatcher exec /usr/lib/xdg-desktop-portal
```
![b](https://user-images.githubusercontent.com/3357792/234903578-2ba1497a-7b67-4d31-955e-66cc8c30f957.png)


But the fix doesn't work if I run on my hyprconfig like:

    exec      =         fix-obr-hyprland-share-pickr

So my conclusion is, the script has to be runned by the user in order to work. I'll try to run it with a cron task tomorrow. I imagine the cause is xdg-desktop-portal is started by systemd. I'm not 100% sure yet.

**Comment by vaxerski** [comment]
import the relevant envvars via `dbus-update-activation-environment --systemd`

**Comment by Zeioth** [comment]
Thank you so much!! Adding this to my hyprland config did it:

    $dbus_env = dbus-update-activation-environment --systemd --all
    exec $dbus_env

For anyone finding this in the future:
https://wiki.archlinux.org/title/Systemd/User#Environment_variables
