### ISSUE TITLE
BUG: Special workspace doesn't behave as documented

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#2161]
Float windows sent to the special workspace show on top of everything.

    bind =    $mod SHIFT,    minus,    movetoworkspace,          special

[According to the documentation](https://wiki.hyprland.org/Configuring/Advanced-config/#special-workspace), windows send to the special workspace, should stop being float while they are on it. (hyprland-git AUR).

**Comment by YinAqu** [comment]
that **floating** is not your floating, use `hyprctl clients` to check if windows are floating or not. as doc says, special workspace is something like **scratchpad**, shows on  everything by design.

**Comment by fdev31** [comment]
I was wondering the same, experimenting with https://github.com/hyprland-community/hpr-scratcher which uses floating windows in special workspace...

**Comment by vaxerski** [comment]
It's a bug, but since so many people rely on it, I am not patching it.

End-goal is to allow floating on special altogether.

**Comment by Zeioth** [comment]
Well I can see the adventage. One can customize the special ws quite a lot by resizing float windows and sending them to it:
![screenshot_2023-04-27_15-54-11_234236702](https://user-images.githubusercontent.com/3357792/234884187-2360d6f1-181b-42b3-b063-2b3abea8bf88.png)

The only issue rn is float windows in the special ws are pinned to the monitor they are sent to the special ws. Even if pinned is disabled. This doesn't hapen with tiled windows on the special ws. They behave normal.

**Comment by Zeioth** [comment]
It seems the issue of my last comment has been fixed. Since the original first comment is `wontfix`: Closing issue.
