### ISSUE TITLE
BUG: Inconsist behavior when releasing bindings

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#2162]
From this config:

    general {
        no_cursor_warps = false
    }

    # BIND     MOD                  KEY       DISPATCHER           VALUE
    bind =     SUPER,               1,        workspace,           1
    bind =     SUPER,               2,        workspace,           2
    bind =     SUPER SHIFT,         1,        movetoworkspace,     1
    bind =     SUPER SHIFT,         2,        movetoworkspace,     2

* Presing super+shift+2,will move the the window to the workspace 2. (as expected)
* But if **without releasing SHIFT**, I press super+shift+1, something weird hapens: the mouse pointer move to the monitor, but the active window doesn't.

## What should hapens
Both the cursor and the window move to the need workspace.

## What hapens
The window doesn't move, but the cursor does.

**Comment by vaxerski** [comment]
huh, can't repro? Are you on -git?

**Comment by Zeioth** [comment]
Yes. I made a video, probably it is not gonna be much help.
https://www.youtube.com/watch?v=c0G7-NCU16k

**Comment by romanstingler** [comment]
can't reproduce with latest commit, can you re-test if you are still using Hyprland

**Comment by vaxerski** [comment]
it's likely fixed
