### ISSUE TITLE
Protocol includes missing in $PREFIX includes

### ISSUE THREAD

**Issue by Duckonaut** [hyprwm/Hyprland#2165]
Trying to include a file like `includes.hpp` (which basically every single Hyprland header file includes) fails with `wlr-layer-shell-unstable-v1-protocol.h: No such file or directory`. The header files still refer to the protocol files as if they were in the global directory, while they reside in `$PREFIX/include/hyprland/protocols`. Theoretically plugin builds could add a `-I/usr/local/include/hyprland/protocols` or similar after guessing the header install directory, but that's not ideal.

**Comment by vaxerski** [comment]
done in 550700bed01c114b2a200ab177ed4bc295a2c7dd

**Comment by Duckonaut** [comment]
Yeah after writing the issue I realized it could also just be added into `hyprland.pc.in`, the Cflags there did not include ./protocols, just hyprland.

**Comment by vaxerski** [comment]
Yea, I reverted it too because [meson cringe and can't do that](https://github.com/mesonbuild/meson/issues/2320)
