### ISSUE TITLE
Cursor change theme when hovers over the edge of the window

### ISSUE THREAD

**Issue by HideOnLie** [hyprwm/Hyprland#2169]
I don't know why it will cause that. The cursor will change when I move cursor to `Microsoft Edge` (which runs in Xwayland) window border. And it also happen in I type `ctrl + o` to open file.

I had read FAQ many times, But it did not work for me,  I would be grateful if someone could help me.

https://user-images.githubusercontent.com/51672711/235046538-66fbd229-8f2b-4ea6-bf36-a06b845358a1.mp4

hyprland.conf:
```
env = XCURSOR_THEME,Vimix-cursors
exec-once=hyprctl setcursor Vimix-cursors 24
exec-once=gsettings set org.gnome.desktop.interface cursor-theme Vimix-cursors
```

**Comment by HideOnLie** [comment]
And I found that the cursor will become ❎️ in  all the window in `gtk-demo` 

https://user-images.githubusercontent.com/51672711/235292099-049202d7-02f6-4bd9-a03e-c23945a8b7a0.mp4

**Comment by vaxerski** [comment]
something's off with XWayland. it's xwayland setting this cursor and hyprland has nothing to do with this. Check on sway-git, but I doubt there is gonna be any change

**Comment by HideOnLie** [comment]
I had fixed it. It look like `gtk2` will read the cursor theme from `xsetroot`?  

```
exec-once=xsetroot -xcf /usr/share/icons/<Cursor Theme Name>/cursors/left_ptr 24
```
