### ISSUE TITLE
[NixOS/MESA] No hardware acceleration after updating channel

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#2170]
OpenGL through MESA 23.0.1 was working just fine until I updated the nixos channel yesterday (meaning not Hyprland). OpenGL now uses software rendering with MESA 23.0.3:
```console
$ nix-shell -p glxinfo --run "glxinfo | grep Device"
    Device: llvmpipe (LLVM 15.0.7, 256 bits) (0xffffffff)
```

I've tried updating Hyprland to no avail.
**I've posted a lot of logs here while troubleshooting the issue:** https://github.com/NixOS/nixpkgs/issues/228586

MESA contributor suggests to:
> In case you used a different nixpkgs commit for NixOS (providing kernel and /run/opengl-drivers) and for some of the programs (e.g. compositor or anything OpenGL), I'd suggest to first trying to match the versions here again. I think with mesa >= 23.0 such mismatches are greater risk than before. I've been repeating this advice quite a lot.
https://github.com/NixOS/nixpkgs/issues/228586#issuecomment-1527030148

I'm having a hard time understanding the proposed solution as I'm new to Nix, maybe you could lend me a hand @fufexan?

**Comment by fufexan** [comment]
Basically I need to update the nixpkgs in Hyprland, or you can use `inputs.hyprland.inputs.nixpkgs.follows = "nixpkgs";` in the meantime.

**Comment by GrabbenD** [comment]
> Basically I need to update the nixpkgs in Hyprland, or you can use `inputs.hyprland.inputs.nixpkgs.follows = "nixpkgs";` in the meantime.

Thanks a lot for providing the solution
Do you know the equivalent of this outside of Flakes?

**Comment by fufexan** [comment]
No.

**Comment by GrabbenD** [comment]
Workaround: https://github.com/NixOS/nixpkgs/issues/228586#issuecomment-1528160997
Solution: https://github.com/hyprwm/Hyprland/commit/093755d53faa6f44f463a683c1ef9a823afb60db
