### ISSUE TITLE
Input method isn't "initialized" on the very few frames of input

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#2175]
When using [anyrun](https://github.com/Kirottu/anyrun), paired with rime on fcitx5. (I'm pressing the letter "f" on the keyboard in the following video, it should output "t")

log:
https://c-v.sh/quakywordbreak.txt

video:

[input_method_weirdness.webm](https://user-images.githubusercontent.com/68589851/235182411-d3468e8d-1fad-4e85-b773-bff9799ab048.webm)

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by izmyname** [comment]
> is this still a thing?

Prolly, it makes sense to close any staled issue if it's unique and the op doesn't answer for a month or two, after being asked about the progress.

**Comment by izmyname** [comment]
Bump. Makes sense to close, as there is no further feedback from the op.
