### ISSUE TITLE
Plugin api will not find function to hook if running from tty

### ISSUE THREAD

**Issue by outfoxxed** [hyprwm/Hyprland#2177]
When run from a tty, as the root compositor, hyprland fails to find functions to hook. It works as expected in a nested hyprland session (using the same version and plugin .so)

### Details
The function `HyprlandAPI::findFunctionsByName` returns 0 functions in the root instance and 1 function (as expected) in a nested instance.

### Reproducing
Call `HyprlandAPI::findFunctionsByName(PHANDLE, "updateWindowAnimatedDecorationValues")` from both a tty and nested inside another hyprland instance. One function will be returned from the nested instance and zero from the tty.

I have a plugin that demonstrates this behavior here: https://github.com/outfoxxed/hy3/tree/e41c3cb2562456f30d406d2ebe6217c41f30a615 (linked at current commit).
To reproduce with the plugin set `general:layout = hy3`. Load both from a tty and a nested instance.

**Comment by vaxerski** [comment]
![20230504_18h14m26s](https://user-images.githubusercontent.com/43317083/236277654-abe9ffa6-79c2-454c-a9b0-fd349a50047e.png)

yes.

**Comment by outfoxxed** [comment]
I have no clue then but it dosen't work for me for some reason.

**Comment by vaxerski** [comment]
how do you launch hyprland? It might be that the `/proc/self/exe` does not point to `Hyprland`.

**Comment by outfoxxed** [comment]
I have a script with all the usual wayland exports (MOZ_ENABLE_WAYLAND etc) that ends with this
```bash
export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1

/nix/store/8vd1ni9c5ihyrcwa1ia3jf481xz7mv0a-hyprland-0.25.0+date=2023-05-03_f27873a/bin/Hyprland $@
```

I run that script from a tty to launch.

Assuming this isn't particularly helpful but I `stat`ed this:
```bash
❯ stat /proc/$(pidof Hyprland)/exe
  File: /proc/1869/exe -> /nix/store/8vd1ni9c5ihyrcwa1ia3jf481xz7mv0a-hyprland-0.25.0+date=2023-05-03_f27873a/bin/Hyprland
```

**Comment by vaxerski** [comment]
no clue, might be something to do with permissions / nix stuff

**Comment by outfoxxed** [comment]
Output of the above command:
[hyprnm.txt](https://github.com/hyprwm/Hyprland/files/11465772/hyprnm.txt)

**Comment by vaxerski** [comment]
> I've tried building hyprlens with both cmake(like hy3) and with make all like provided in the hyprlens' repo. In both cases hyprlens failed to find a candidate.

might be outdated for the 0.25.0 plugin build changes

**Comment by FlafyDev** [comment]
> And that might give you some insight as to what's happening. My prime suspect is `nm` failing, might be worthwhile logging the output.

You were right. We figured it out, we were lucking `nm` in PATH, since we didn't have binutils installed.
Might be worth having unwrapped and wrapped Hyprland packages for nix, so we can add runtime dependencies such as `binutils` and `pciutils` to PATH instead of relying on the user to have them. Though this is just a nix matter.

**Comment by outfoxxed** [comment]
working on pr
