### ISSUE TITLE
Unloading and reloading a plugin with a function hook segfaults

### ISSUE THREAD

**Issue by outfoxxed** [hyprwm/Hyprland#2178]
### Details
Basically just the title.

[Crash Report](https://github.com/hyprwm/Hyprland/files/11356468/hyprlandCrashReport83162.txt)

![image](https://user-images.githubusercontent.com/83010835/235228140-cec03f38-1b6c-4c1b-bd68-129a4a262a7e.png)

### Reproducing
1. Load a plugin with a function hook (I used https://github.com/outfoxxed/hy3/tree/e41c3cb2562456f30d406d2ebe6217c41f30a615).
2. hyprctl reload
3. unload the plugin
4. hyprctl reload
5. load the plugin
6. hyprctl reload
7. segfault

**Comment by outfoxxed** [comment]
Do you have any idea what the cause could be? (hy3 reloads fine if the hook is disabled)
The differences I can immediately see are
1. hy3 loads the hook when its layout is enabled instead of on plugin init.
2. It finds the function using `HyprlandAPI::findFunctionsByName`, then stores the resulting address in a `static const auto` (is it interacting badly with dlopen / dlclose on the same file?).
Note: I've had [another problem](https://github.com/hyprwm/Hyprland/issues/2177) with `HyprlandAPI::findFunctionsByName`.

Apart from those I don't see much difference, as it reloads correctly without the hook.

**Comment by vaxerski** [comment]
no clue, but something is indeed going wrong. Might be double-hooking. If you've called `hook()`, calling `hook()` again without an `unhook()` will fuck things up

**Comment by outfoxxed** [comment]
If hyprland unloads all the hooks from a plugin when the plugin is unloaded I don't see a way for that to happen. Hyprland does unload hooks when a plugin unloads right?

**Comment by vaxerski** [comment]
yes, it does.

**Comment by outfoxxed** [comment]
I am not sure how statics behave on dlclose. If statics are not cleared on dlclose then the hook would not be reinitialized and would instead contain the hook from the old instance of the plugin with a different handle. Does that happen? Woyld it be better to always initialize the hook in plugin init and then just enable/disable it on layout load/unload?

**Comment by vaxerski** [comment]
you can try unloading it in exit and seeing what that does, but I don't think it will make much of a difference tbh.

**Comment by outfoxxed** [comment]
I dont think it would either. The only way I can see the current implementation causing an issue is if statics are not destroyed on dlclose, so I'll try re-initializing the hook unconditionally on plugin load.

**Comment by outfoxxed** [comment]
Reinitializing the hook on every plugin load fixed it.
