### ISSUE TITLE
Ability to disable libinput Tapping Drag enabled

### ISSUE THREAD

**Issue by BrianNormant** [hyprwm/Hyprland#2179]
Hello, I've read the wiki about touchpad settings and I don't find any option to disable tap and drap.
[wiki page](http://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Variables/#touchpad)

Did I miss something? I would like to keep the touchpad tapping enabled but disable the drag feature.
With X.org based application I would just run somewhere
`$xinput set-prop <TouchpadName> "libinput Tapping Enabled" 1`
`$xinput set-prop <TouchpadName> "libinput Tapping Drag Enabled" 0` 

But all anwsers I found on forums say that on wayland, the display manager is the one responsible for keyboard, mouse and other settings. I can't find a xinput equivalent on wayland.

**Comment by droc12345** [comment]
Try "tap-and-drag = 0" in input:touchpad area, looks like it inadvertently got left out of the wiki, even though there is a config option.

**Comment by BrianNormant** [comment]
I worked perfectly, thanks. should I mark this as closed?
