### ISSUE TITLE
Graphical stutters, glitches + massive lag in firefox

### ISSUE THREAD

**Issue by jacekpoz** [hyprwm/Hyprland#2183]
https://gofile.io/d/GzMcBU

yesterday I installed the linux-rt kernel, played around with it a bit but after a while I started getting graphical glitches in firefox and librewolf, the same as in the video, so I switched back to linux-zen but the issue is still here, now not only in firefox and librewolf but in general system-wide, while firefox and librewolf also have massive input lag occasionall

when looking at btop, there's some cpu usage spikes but as far as I can see they're not correlated with the firefox input lag

I checked my pacman log and I didn't see anything that could've caused this getting upgraded, I also didn't get any failures when upgrading the system so probably not that

**Comment by jacekpoz** [comment]
most issues fixed after removing `env=DRI_PRIME,1002:73df` from my hyprland config :trollface: 

although I still get this
```
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
```
on things like kmscube, not sure if that's an issue

**Comment by vaxerski** [comment]
issues are on your end

**Comment by Edgars-Cirulis** [comment]
> most issues fixed after removing `env=DRI_PRIME,1002:73df` from my hyprland config :trollface:
> 
> although I still get this
> 
> ```
> amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
> amdgpu: amdgpu_device_initialize failed.
> amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
> amdgpu: amdgpu_device_initialize failed.
> ```
> 
> on things like kmscube, not sure if that's an issue

About amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13) it requires root/sudo access to get info from kernel, just ignore it's functional.
