### ISSUE TITLE
Showing a special workspace may reveal all of them

### ISSUE THREAD

**Issue by fdev31** [hyprwm/Hyprland#2185]
Using today's git version (but it happened with the last release).
Having a couple of windows in two different special workspaces:
```shell
❯ hyprctl clients |grep special |grep -v grep
	workspace: -99 (special:scratch)
	workspace: -98 (special:minimized)
	workspace: -98 (special:minimized)
```

Showing the minimized workspace (`hyprctl dispatch togglespecialworkspace minimized`) sometimes shows the *scratch* workspace.
If I explicitly show and hide the *scratch* workspace then the bug can't be reproduced for some time, showing and hiding special workspaces will work as expected, until an undefined action/amount of time.

**Comment by MightyPlaza** [comment]
any updates?

**Comment by fdev31** [comment]
I'm not sure it's happening anymore... I didn't experience it recently.

**Comment by vaxerski** [comment]
closing then, feel free to reopen if it happens
