### ISSUE TITLE
Waybar shows on top of fullscreen windows after switching focused monitor and switching back

### ISSUE THREAD

**Issue by fdev31** [hyprwm/Hyprland#2186]
On a dual monitor setup using waybar:

- switch a window fullscreen: it shows as expected
- switch to another screen, either with mouse or a keyboard shortcut
- return focus to the original screen

Expected: it still displays the same way as it was displayed before
Current result: waybar is displayed on top of the fullscreen window

Note: switching to another desktop hides waybar

**Comment by fdev31** [comment]
Sending SIGUSR1 twice to waybar (to toggle the visibility) works around the issue.

**Comment by romanstingler** [comment]
is this resolved for you

**Comment by fdev31** [comment]
I didn't experience this issue lately.
