### ISSUE TITLE
env = XCURSOR_SIZE,48 does not take effect

### ISSUE THREAD

**Issue by yaoshiu** [hyprwm/Hyprland#2193]
# Steps to produce

Set `env = XCURSOR_SIZE,48` in hyprland.conf

# Expected outcome

The XCURSOR_SIZE environment should be 48

# Noted outcome

The XCURSOR_SIZE was set 24.

![screenshot](https://s2.loli.net/2023/04/30/587WZHtM21u6TIK.png)

**Comment by Edgars-Cirulis** [comment]
Did you reboot?

**Comment by yaoshiu** [comment]
> Did you reboot?

Yes. And by the way, I also tried to set `XCURSOR_SIZE` to 48 in TTY before starting Hyprland, but after starting Hyprland, `XCURSOR_SIZE` inside Hyprland is changed back to 48, so I think This should be the behavior of Hyprland at startup.

**Comment by Edgars-Cirulis** [comment]
> most likely here
> 
> https://github.com/hyprwm/Hyprland/blob/cde7f79af0d084cba585bb56f9302afab5a216f9/src/Compositor.cpp#L172-L173
> 
> but idk why it's unset

Hmm, by looking at this code its checking if the env variable XCURSOR_SIZE is set or empty. If it's not set or empty, it sets the "XCURSOR_SIZE" env variable to the value 24

**Comment by yaoshiu** [comment]
https://github.com/hyprwm/Hyprland/blob/79791c9ed4a9f78d8a444006e2cdd4a63d1a5862/src/debug/HyprCtl.cpp#L838-L839

^ I found another piece of code that may be related, and this may be the main reason, as I did set `exec=hyprctl setcursor Catppuccin-Frappe-Dark-Cursors 24` in hyprland.conf.

However, this is because I am currently using a high-resolution screen, so I need to set `xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2` and `GDK_SCALE=2` `XCURSOR_SIZE=48` to have a normal display under XWayland. However, I also need to use `hyprctl setcursor` to set the cursor theme and size in Hyprland, and the cursor size should be normal at 24. This seems to be an issue that cannot be both satisfied.

Should I close this issue and open a new one to describe this problem?

**Comment by vaxerski** [comment]
> Should I close this issue and open a new one to describe this problem?

No, that'd be spam

> exec=hyprctl setcursor Catppuccin-Frappe-Dark-Cursors 24

`exec=hyprctl setcursor Catppuccin-Frappe-Dark-Cursors 24 && export XCURSOR_SIZE=24`?

**Comment by yaoshiu** [comment]
I've tried patch it with
```patch
diff --git a/src/debug/HyprCtl.cpp b/src/debug/HyprCtl.cpp
index 32d544a0..eee894f5 100644
--- a/src/debug/HyprCtl.cpp
+++ b/src/debug/HyprCtl.cpp
@@ -835,8 +835,8 @@ std::string dispatchSetCursor(std::string request) {
 
     g_pCompositor->m_sWLRXCursorMgr = wlr_xcursor_manager_create(theme.c_str(), size);
 
-    setenv("XCURSOR_SIZE", SIZESTR.c_str(), true);
-    setenv("XCURSOR_THEME", theme.c_str(), true);
+    setenv("XCURSOR_SIZE", SIZESTR.c_str(), false);
+    setenv("XCURSOR_THEME", theme.c_str(), false);
 
     for (auto& m : g_pCompositor->m_vMonitors) {
         wlr_xcursor_manager_load(g_pCompositor->m_sWLRXCursorMgr, m->scale);
```
And this way `hyprctl setcursor` won't set the `XCURSOR_SIZE` if it is already set. Now cursors in Hyprland looks good and `XCURSOR_SIZE` is set 48 which I'm expecting.

But now the issue is that a `XCURSOR_SIZE` with the value 48 will lead to a too big cursor in QT applications and 24 will lead to a too small cursor in XWayland. This seems to be duplicated with https://github.com/hyprwm/Hyprland/issues/894.
