### ISSUE TITLE
BUG: Workspaces malfunction when a monitor is turned off/on

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#2199]
This might sound like a pretty niche scenario, but in my house lights go off quite often, and this bug manifests every time the screens turn off. (I have the computer connected to a SAI, but only one of my six monitors). 

## Config
```
# Monitors
monitor = $screen1,3840x2160@60,0x0,1,bitdepth,10
monitor = $screen2,3840x2160@60,3840x0,1,bitdepth,10

# Workspaces
wsbind = 1,$screen1
wsbind = 2,$screen2
```

## HOW TO REPRODUCE
* On a monitor, open any program.
* Turn off the monitor.
* Turn on the monitor again.

# WHAT HAPENS
* The window doesn't go back to its original monitor.
* If you try to move it back manually with the movetoworkspace dispatcher, it just won't. You can move to any other monitor, but not to the one you turned off/on.

# WHAT SHOULD HAPEN
* When you turn off the monitor, the windows in that monitor pass to the other (this hapen alwady, good)
* When you turn on the monitor again, the window should go back to its original monitor (this doesn't hapen)
* Also, you should be able to manually move back the window to the monitor it was (this doesn't hapen, the dispatcher glitches)

Now the dispatcher movetoworkspace won't work correctly. You won't be able to move your window back to the monitor it was.

**Comment by vaxerski** [comment]
> Also, you should be able to manually move back the window to the monitor it was (this doesn't hapen, the dispatcher glitches)

Wdym glitches? there should just be a new workspace open on the re-connected monitor. For the workspaces not coming back, this is a dupe of some issue I forgot which one now, searchable

**Comment by Zeioth** [comment]
Give me a bit of time. I'm gonna try to record it on camera tomorrow to document better this issue.

**Comment by Zeioth** [comment]
I'm quite certain this has been fixed because I haven't experience it for quite a few versions. Closing.
