### ISSUE TITLE
movefocus to move to next monitor

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#220]
Something I miss from sway is the ability for movefocus to move to the next monitor if it reaches the border of the current monitor. for insance if I have one client on eDP-1 and one on DP-2, and assuming that DP-2 is on the right, movefocus right should move the DP-2 if the current client on eDP-1  is at the right most position

**Comment by vaxerski** [comment]
I think that's how it worked in Hypr, but I just havent gotten around to implementing it in hyprland

**Comment by vaxerski** [comment]
done in f9745b0d3b85c447c3c8d3421db638f1087a1e91

**Comment by primalmotion** [comment]
that does not seem to work for me. 

this is my monitor config

```
monitor=eDP-1,1920x1080@60.000999,0x0,1
monitor=DP-2,3440x1440@59.973000,-760x-1440,1
```

**Comment by vaxerski** [comment]
don't use negative coordinated, that's first.

Second, your monitors are not side by side, so that is expected. They need to be side by side for this to work.

**Comment by primalmotion** [comment]
well yes they are not side by side horizontally.. I can't change the physical layout of my desk :) I 'm expecting up/down to work

**Comment by vaxerski** [comment]
it should. try fixing your layout by not using negative values.

**Comment by primalmotion** [comment]
ok so I changed to 

```
monitor=eDP-1,1920x1080@60.000999,760x1440,1
monitor=DP-2,3440x1440@59.973000,0x0,1
```

but it does not work better

**Comment by primalmotion** [comment]
yeah

**Comment by vaxerski** [comment]
ok then it will block the pass through. Let me fix that.

**Comment by primalmotion** [comment]
ok yeah without waybar it works.

**Comment by primalmotion** [comment]
moving window doesn't work though. only focus.

**Comment by vaxerski** [comment]
focus should be fixed in f76b9c485246849bc3af838503fedbadf68023f5

> moving window doesn't work though

and it shouldn't, by design. you move a window between workspaces with `movetoworkspace` or `movetoworkspacesilent`

**Comment by primalmotion** [comment]
cool, thanks! I'll give it a try in a few.

> and it shouldn't, by design. you move a window between workspaces with movetoworkspace or movetoworkspacesilent

Okay.. I don't know why but I find this less fluid than being able to seemlessly moving windows around the virtual space, but I guess I can live with this

**Comment by vaxerski** [comment]
u can use the mouse, hold the main_mod and drag and drop windows, if you want.

**Comment by Vintodrimmer** [comment]
Is there any way to move focus to the other monitor if there are no windows on the current monitor?
Let's say I open 1 window on the main monitor and 1 window on the monitor to the right. I can freely switch between them with `movefocus`. If I'm on the second monitor and close the active window, `movefocus` will no longer allow me to go to the main monitor. Is this the intended behaviour?

**Comment by vaxerski** [comment]
`workspace` will snap your cursor to the monitor's center.
