### ISSUE TITLE
[Nvidia] WLR_NO_HARDWARE_CURSORS is not a field for env

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/Hyprland#2212]
I am aware Nvidia isnt supported.

However, I have not been able to get a cursor at all. All nvidia-related fixes in the wiki are out of date (will be working on it)

From the looks of it, WLR_NO_HARDWARE_CURSORS is not a field within variables or keywords, at least not in the wiki

How do I get a working cursor now? Please advise

**Comment by mistakenelf** [comment]
I use Nvidia and have `env = WLR_NO_HARDWARE_CURSORS,1` in my config and its working fine

**Comment by WasteOfO2** [comment]
Fixed! Had some packages masked on gentoo, recompiling fixed it, thx!
