### ISSUE TITLE
Regression: Previous workspace is forgotten or cycles too far again

### ISSUE THREAD

**Issue by proycon** [hyprwm/Hyprland#2214]
I want to report a regression concerning https://github.com/hyprwm/Hyprland/issues/1218 ; this was fixed nicely with #1388 back in january, but now the original issue seems back (at least since b1580351, possibly a week or so before that). I'm not sure if it's entirely the same, but in any case, the toggle back and forth behaviour no longer works. I wonder if other people have noticed?

**Comment by proycon** [comment]
I'm guessing 83f1616a65091fe2e66d054f5ef1343d755a3e0c might be the culprit...

**Comment by tchofy** [comment]
Can you try setting binds:allow_workspace_cycles to true? I noticed that change a few weeks ago as well, back and forth would work with cycles set to false, but not it works for me by having it set to true.

**Comment by proycon** [comment]
Right! That seems to do the trick! Thanks!

@vaxerski I'll leave the issue open for you to decide whether this is intended behaviour this way or not... (to me allow_workspace_cycles = false feels more logical, I'd interpret true as going back in history through multiple workspaces)

**Comment by vaxerski** [comment]
idk whats the intended behavior uwu I don't use those options and they dont make sense to me either

**Comment by tchofy** [comment]
Imo cycles=true makes more sense, so two workspaces cycle between each other, and if set to false, `workspace previous` goes back until the beginning of spacetime.
