### ISSUE TITLE
Can't build hyprland

### ISSUE THREAD

**Issue by dquevid** [hyprwm/Hyprland#2218]
First i have installed all its dependencies, which are listed in docs.

> yay -S gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland libinput libliftoff libdisplay-info

I have tried `yay -S hyprland` and got this:

> [5/79] Building CXX object CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o
FAILED: CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o
/usr/sbin/c++ -DGIT_BRANCH=\"main\" -DGIT_COMMIT_HASH=\"2e28e88dfdca3d836c5dbedb916e0f629fc6a540\" -DGIT_COMMIT_MESSAGE="\"    flake.lock: update nixpkgs\"" -DGIT_DIRTY=\"dirty\" -DGIT_TAG=\"v0.24.1-141-g2e28e88d\" -DHyprland_EXPORTS -DUSES_SYSTEMD -DWLR_USE_UNSTABLE -I/home/dqvid/Hyprland/. -I/home/dqvid/Hyprland/subprojects/wlroots/include -I/home/dqvid/Hyprland/subprojects/wlroots/build/include -I/home/dqvid/Hyprland/subprojects/udis86 -I/home/dqvid/Hyprland/protocols -isystem /usr/include/cairo -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -isystem /usr/include/pango-1.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -pthread -MD -MT CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o -MF CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o.d -o CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o -c /home/dqvid/Hyprland/src/events/Devices.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[20/79] Building CXX object CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:13: release] Error 1
make[1]: Leaving directory '/home/dqvid/Hyprland'
make: *** [Makefile:38: install] Error 2

Also have tried to build it from source (hyprwm/Hyprland) and got the same.

I use Arch WSL 2 by yuk7 btw.

**Comment by vaxerski** [comment]
something's wrong on your end, CI does not fail. Please do not report compilation errors.

Couple notes: 
> I have tried yay -S hyprland and got this:

hyprland is a package in `community` and thus does not compile. Something's very wrong on your end.
