### ISSUE TITLE
Hyprland carshd when i opend discord while firefox was running

### ISSUE THREAD

**Issue by Slimemaster0** [hyprwm/Hyprland#2222]
HL version: 5a3c1449194aa70d5eacbd902fa99cc1b2910a30
Distro: Arch Linux

[hyprland.log](https://github.com/hyprwm/Hyprland/files/11385040/hyprland.log)
[hyprlandCrashReport784.txt](https://github.com/hyprwm/Hyprland/files/11385049/hyprlandCrashReport784.txt)

Soo i was watching RWBY in ff and then i decided to open discord in anolther workspace.
Also i'm useing Discod canary with Replugged.

**Comment by vaxerski** [comment]
crash in libwayland dispatching loop, doesn't seem like a hyprland issue

**Comment by romanstingler** [comment]
Can't reproduce
