### ISSUE TITLE
Issue with Window Dragging: Not as Smooth as in Sway

### ISSUE THREAD

**Issue by Edgars-Cirulis** [hyprwm/Hyprland#2223]
Hello there, upon closer looking, it seems that the window dragging is experiencing frame skips. It also feels like there are skipped frames when dragging the windows. 

I am not experiencing this issue in Sway.

Hyprland version; v0.25.0

**Comment by vaxerski** [comment]
what if you disable animations on them with `misc:animate_mouse_windowdragging = false`

**Comment by Edgars-Cirulis** [comment]
> what if you disable animations on them with `misc:animate_mouse_windowdragging = false`

Doesn't disabling animations in general wouldn't it disables this too?

**Comment by vaxerski** [comment]
I think it would, but try disabling that explicitly too, we're debugging here.

**Comment by romanstingler** [comment]
I can't reproduce it as well. 
@Edgars-Cirulis can you build the latest version and test again?

**Comment by MightyPlaza** [comment]
@vaxerski this should have been fixed with the performance improvements, right?

**Comment by vaxerski** [comment]
no clue. maybe. I think it's safe to close this
