### ISSUE TITLE
Compiling 0.25.0 throws many warnings and some errors

### ISSUE THREAD

**Issue by alerque** [hyprwm/Hyprland#2226]
I'm the packager of Hyprland in the official Arch Linux distros. I'm trying to bump the package to 0.25.0 and running into some issues. A whole pile of warnings are thrown relating to GIT_TAG and GIT_COMMIT_MASH being redefined, but in the mix is at least one error killing off the build:

```
/build/hyprland/src/Hyprland-0.25.0/src/debug/../defines.hpp:1:25: error: ‘f27873a6f06dc2f87600edb890f3c38298bfb55f’ was not declared in this scope                                                                                                                                                                             (346 results) [158/12086]
    1 | #define GIT_COMMIT_HASH f27873a6f06dc2f87600edb890f3c38298bfb55f
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Does this ring any bells?

**Comment by vaxerski** [comment]
yeah, I'll edit the tarball in a sec. It was a bug in the release ci

**Comment by vaxerski** [comment]
fixed the tarball in the release.

**Comment by alerque** [comment]
Please don't edit tarballs after posting them, do a minor bump. Now we have downstream checksum changes to cope with because a tagged artifact changed in place.

Thanks for fixing the root bug though.

**Comment by vaxerski** [comment]
I know it's a bit annoying, but I assumed 3h wasn't enough for a lot of maintainers to use it. Sorz for the inconvenience

**Comment by alerque** [comment]
Many distros fetch files and get them in the pipeline within seconds or minutes of a tag going live. No amount of time is "not enough".

Also you'll have end users that downloaded the tarball and are fiddling with it with no idea that their problem is they don't *actually* have the latest sources.

**Comment by vaxerski** [comment]
I added source `-2` and a note.
