### ISSUE TITLE
using movetoworkspacesilent on a grouped window is messing stuff

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#2229]
- create a group of window in a workspace
- focus one of the groupped window
- use movetoworkspaceslient to move it somewhere else

A lot of things are then messed up. It seems hyprland is not really moving all the window to the new workspace. 

I'm not sure what the behavior should be though: move just the focus window, or the entire group?

**Comment by MightyPlaza** [comment]
Seems fixed in latest, probably by https://github.com/hyprwm/Hyprland/commit/cbe9bf0e692010717e3d35e87a9abee79c5f8e4f

**Comment by primalmotion** [comment]
yeah seems it is. closing
