### ISSUE TITLE
Request to add my apps to Wiki -> Utilities

### ISSUE THREAD

**Issue by nwg-piotr** [hyprwm/Hyprland#2231]
Hi,

I'm writing in hope you could add some of my stuff to the Wiki:

- [nwg-panel](https://github.com/nwg-piotr/nwg-panel): GTK3-based panel w/ Hyprland taskbar and workspaces modules;
- [nwg-dock-hyprland](https://github.com/nwg-piotr/nwg-dock-hyprland): GTK3-based dock (forked from the sway version);
- [nwg-displays](https://github.com/nwg-piotr/nwg-displays): output management utility;
- [nwg-look](https://github.com/nwg-piotr/nwg-look): GTK settings editor with no need to use additional scripts;
- [nwg-drawer](https://github.com/nwg-piotr/nwg-drawer): application launcher;
- [nwg-bar](https://github.com/nwg-piotr/nwg-bar): GTK3-based button bar;
- [Azote](https://github.com/nwg-piotr/azote): wallpaper manager.

All the above are components of [nwg-shell](https://nwg-piotr.github.io/nwg-shell), which will have a Hyprland version sooner or later, too.

Many thanks for your work. It's great.

**Comment by vaxerski** [comment]
make a pr to the wiki and add them yourselves...?

wrong bug tracker anyways

**Comment by nwg-piotr** [comment]
I didn't notice it was hosted on GitHub. 🤣
