### ISSUE TITLE
Nix: using hyprland from overlays.default causes build failure

### ISSUE THREAD

**Issue by Aleksanaa** [hyprwm/Hyprland#2237]
1. clone this repo.
2. checkout `v0.25.0` tag.
3. run `nix repl`.
4. input the following expression:

```
(import inputs.nixpkgs { system = "x86_64-linux"; overlays = [ outputs.overlays.default ]; }).hyprland.buildInputs
```

We can easily find out, surprisingly, the `hyprland-protocols` dependency is using the package from nixpkgs (`«derivation /nix/store/rvjgyrq10fmjir672lkfql2cn1rqzkm5-hyprland-protocols-unstable-2023-01-13.drv»`), which will cause the build failure later, because:
https://github.com/hyprwm/Hyprland/blob/0432804b180dbdf7aed64a5bf71b912a937e2e04/protocols/meson.build#L8

I know this can be easily fixed by specifying the package in releavant callPackage function. However, the real problem is that we've used a lot of `self.overlays`. We should really consider wheels like flake-parts instead, or this kind of problems and infinite recursion will happen very frequently.

**Comment by gotjoshua** [comment]
is there a workaround?

Especially for home manager setup...

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
@Aleksanaa @gotjoshua check out master, I just merged a fix a few hours ago.

**Comment by Aleksanaa** [comment]
> @Aleksanaa @gotjoshua check out `main`, I just merged a fix a few hours ago.

Lgtm, although just a quick fix. Will close the issue for now.
