### ISSUE TITLE
blurls=waybar and hiding 

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#2238]
When using `blurls=waybar` I get a blurred bg for waybar as expected. Then send `pkill -USR1 waybar` to hide it. Waybar goes away, but the blurred background is stuck there

**Comment by vaxerski** [comment]
it's not an issue with hyprland as waybar does not unmap the surface, it just makes it transparent. `ignorezero` would fix this.

**Comment by primalmotion** [comment]
indeed! I wasn't aware of the layer rules. Thanks!
