### ISSUE TITLE
[Nvidia] Pipewire doesn't detect screens, most likely a portals issue

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/Hyprland#2239]
I am aware Nvidia isn't natively supported.

I will mention as many details as possible and try to slowly rule out possible variables, please bear with me if the issue is too long. I will also try to keep it as systematic and clear as possible.

Before I discuss the issue, I want to brief you about my system and setup.

My desktop PC:- 1. Init System: OpenRC; 2. Distro: Gentoo; 3. GPU: Nvidia GTX 1650(proprietary 
drivers)

### Installing
 
I first went over the general installation of Hyprland on Gentoo, using the package available in wayland-desktop repository and enabled the required USE flags and keywords.

I have read through and implemented Nvidia-specific changes in my config file. I have also confirmed that I am running the proprietary driver and not the nouveau ones. Direct Rendering is enabled and functions normally.

I then installed Pipewire and Wireplumber as stated in the Gentoo Wiki https://wiki.gentoo.org/wiki/PipeWire . I also enabled the required USE flags (except GStreamer, I will update in the comments once I am done emerging my packages)

Keep in mind, flags like `system-service` aren't needed as this is an OpenRC system

I have installed xdg-desktop-portal and XDPH, also verifiying that -gnome and -kde ones don't exist. I have verified that -wlr never emerges either.

Installing Pipewire/Wireplumber also requires Pulseaudio-daemon to be removed, which I have done and verified that it never launches.

Grimblast is installed as well.
### Setting up

I use Chris Titus' (forked from linux mobile) configs, and added the following lines:

```
# portals
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --all WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# gentoo-specific stuff
exec-once = gentoo-pipewire-launcher &

#NVIDIA STUFF
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
```
Aside from these, some personal adjustments were made, but none that would affect portals or wireplumber stuff.

In addition to this, I added this to my DM's config

```
[Desktop Entry]
Name=Hyprland
Comment=An intelligent dynamic tiling Wayland compositor
Exec=dbus-launch --exit-with-session Hyprland
Type=Application
```
This ensures Pipewire/Wireplumber have no issues with permissions of any sorts

### The Problem

I noticed that my screenshots are blank, OBS doesn't detect displays (even the flatpak one) and Screencasting on Firefox is also not functioning (I have verified that my about:config reflects pipewire usage). I have followed the Hyprland's Wiki for "Screenshare / OBS no worky"

**I don't get any windows from hyprland-share-picker** during the entirety of this process.

However, I do get a hyprland-share-picker prompt when manually run from terminal (as expected)

[Photo for the same](https://files.catbox.moe/h39b57.jpg)

Curiously, I get the following output from OBS logs

```
info: [pipewire] No captures available
```

I will now attaching the full logs from OBS [here](https://bpa.st/W5KRE)

An image from my OBS sources [here](https://files.catbox.moe/xggzh2.jpg) (Notice how I don't get any sources for video)

And also a sample screenshot from Grimblast [here](https://files.catbox.moe/3e8ve7.png)

I have even attempted to run OBS from flatpak, but to no avail. I have not tinkered with permissions of OBS beyond vanilla install, not even downloading any plugins for the flatpak.

### Attempted Remedies

I have approached Gentoo forums and asked for help [there](https://forums.gentoo.org/viewtopic-p-8788298.html) and also the IRC channels. I also asked around in the Pipewire Matrix room. At this point I was speculating that it could be a Pipewire/Wireplumber issue, as the Gentoo Wiki doesn't mention anything about setting up Video Sources on it's Pipewire page (linked above).

I verified if Pipewire was even running in the first place

```
$ LANG=C pactl info | grep "Server Name"
Server Name: PulseAudio (on PipeWire 0.3.67)
```
So if Pipewire's sound server is running, why would the video end not work?

As a sanity check, I also listed a bunch of services that OpenRC could run

```
$ rc-service -l

agetty
apache2
binfmt
bluetooth
bootlogd
bootmisc
cgroups
chronyd
consolefont
cups-browsed
cupsd
dbus
devfs
device-mapper
dhcpcd
dmcrypt
dmesg
elogind
fsck
fuse
gem_server
git-daemon
gpm
hostname
hwclock
ip6tables
iptables
keymaps
killprocs
kmod-static-nodes
local
localmount
loopback
ly
modules
mount-ro
mtab
net-online
net.lo
netmount
numlock
osclock
pciparm
procfs
pydoc-3.10
pydoc-3.11
pydoc-3.12
root
rsyncd
runsvdir
s6-svscan
save-keymaps
save-termencoding
savecache
seatd
seedrng
sshd
stdiscosrv
strelaysrv
swap
swclock
syncthing
sysctl
sysfs
sysklogd
systemd-tmpfiles-setup
systemd-tmpfiles-setup-dev
termencoding
udev
udev-settle
udev-trigger
```

This leads me to believe that either Nvidia is acting up(In typical fashion) or something else is at play here.

I then verified what all XDP instances were running

```
$ ps aux | grep -i xdg-desktop-portal

vigu      2787  0.0  0.0  18164  6656 tty1     Sl+  May04   0:00 /usr/libexec/xdg-desktop-portal-hyprland
vigu      2858  0.0  0.0 530292 10220 ?        Sl   May04   0:00 /usr/libexec/xdg-desktop-portal
vigu      9462  0.0  0.0   3872  2432 pts/2    R+   00:28   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i xdg-desktop-portal
```
I am not sure what the "?" on the 7th field indicates, hence I am not sure if I can blame it for my woes.

To check with dbus communications, I did the following

```
$ dbus-monitor --session sender=org.freedesktop.portal.Desktop destination=org.freedesktop.portal.Desktop

signal  time=1683214271.265300 sender=org.freedesktop.DBus ->  destination=:1.55 serial=2 path=/org/freedesktop/DBus;  interface=org.freedesktop.DBus; member=NameAcquired     string ":1.55"  signal time=1683214271.265352 sender=org.freedesktop.DBus ->  destination=:1.55 serial=4 path=/org/freedesktop/DBus;  interface=org.freedesktop.DBus; member=NameLost     string ":1.55"  method call time=1683214348.723907 sender=:1.60 ->  destination=org.freedesktop.portal.Desktop serial=2  path=/org/freedesktop/portal/desktop;  interface=org.freedesktop.DBus.Properties; member=Get     string "org.freedesktop.portal.Screenshot"     string "version"  error time=1683214348.723939 sender=:1.23 -> destination=:1.60  error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=2     string "No such interface “org.freedesktop.portal.Screenshot”"  method call time=1683214348.739966 sender=:1.60 ->  destination=org.freedesktop.portal.Desktop serial=6  path=/org/freedesktop/portal/desktop;  interface=org.freedesktop.portal.Settings; member=Read     string "org.freedesktop.appearance"     string "color-scheme"  error time=1683214348.740016 sender=:1.23 -> destination=:1.60  error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=6     string "No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop"  method call time=1683214451.221598 sender=:1.63 ->  destination=org.freedesktop.portal.Desktop serial=2  path=/org/freedesktop/portal/desktop;  interface=org.freedesktop.DBus.Properties; member=Get     string "org.freedesktop.portal.Screenshot"     string "version"  error time=1683214451.221807 sender=:1.23 -> destination=:1.63  error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=2     string "No such interface “org.freedesktop.portal.Screenshot”"  method call time=1683214451.252218 sender=:1.63 ->  destination=org.freedesktop.portal.Desktop serial=6  path=/org/freedesktop/portal/desktop;  interface=org.freedesktop.portal.Settings; member=Read     string "org.freedesktop.appearance"     string "color-scheme"  error time=1683214451.252363 sender=:1.23 -> destination=:1.63  error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=6     string "No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop"
```
You can notice a bunch of "No such interface" stuff. This potentially indicates something wrong with either dbus or portals.

### Testing on a Similar Setup

I have an old laptop, some details about it are as follows

1. Init System: SystemD; 2. Distro: Arch Linux; 3. GPU: Integrated Intel(non-Xe, don't recall exact names)

Apart from those above, everything else is practically the same as my desktop setup. Just that I run Zen kernel on the laptop

I have no such issues on this laptop. I still run Pipewire/Wireplumber on the laptop, I use OBS, I use Grimblast and Screensharing works well too.

### Theories And Speculation

As Gentoo's wiki doesn't give full information for setting up video sources for Pipewire/Wireplumber, it could be a point of failure. The logs of OBS also mention how sources weren't detected, indicating that it _might_ be incorrectly configured, but this is rather unlikely.

XDPH is probably not suited for my case. This is an edge case of a user running OpenRC, Gentoo, Nvidia with proprietary drivers and a Xanmod kernel. This is definately not a common setup and I can totally understand not having any foresight for this. It is a weird mix of things, and any of them are  potential points of failure.

Fortunately, one of the dudes in IRC who helped me out also ran a similar setup, they used an AMD GPU and SystemD instead. Same Gentoo and also ran Hyprland. They found the issue peculiar too.

### Closing Notes/ TL;DR

I want to investigate this issue and I am also willing to update the wiki about it if a fix is found.

I will also attach Hyprland log files [here](https://files.catbox.moe/sfahfs.log) if that helps.

More info will be provided upon request :3

**Comment by WasteOfO2** [comment]
Accidentally hit enter, the issue is not complete.

**Comment by vaxerski** [comment]
black screenshots: nvidia patches not applied

obs: you don't have a pipewire source in the sources: obs running either in xwayland or pipewire is missing deps / broken

firefox: if the picker doesn't come up, xdph is not running / running incorrectly / xdp died / multiple impls installed

**Comment by WasteOfO2** [comment]
> black screenshots: nvidia patches not applied
For grimblast?

> obs: you don't have a pipewire source in the sources: obs running either in xwayland or pipewire is missing deps / broken
I am currently re-emerging with gstreamer USE flag, that can maybe help
> firefox: if the picker doesn't come up, xdph is not running / running incorrectly / xdp died / multiple impls installed
Already addressed that in my original issue, here is a picture to help u understand it better/ fill gaps in my post https://files.catbox.moe/pgo2dk.jpg

**Comment by vaxerski** [comment]
> For grimblast?

for hyprland

**Comment by vaxerski** [comment]
> Already addressed that in my original issue, here is a picture to help u understand it better/ fill gaps in my post https://files.catbox.moe/pgo2dk.jpg

and that's what I said, you said the picker doesnt come up. Maybe it's outside the PATH? What about xdph logs? If you run xdph with the `-l DEBUG` flag it will produce logs.

**Comment by WasteOfO2** [comment]
> > Already addressed that in my original issue, here is a picture to help u understand it better/ fill gaps in my post https://files.catbox.moe/pgo2dk.jpg
> 
> and that's what I said, you said the picker doesnt come up. Maybe it's outside the PATH? What about xdph logs? If you run xdph with the `-l DEBUG` flag it will produce logs.

It does seem like it isnt in paths, cant seem to autocomplete it in my terminal

**Comment by WasteOfO2** [comment]
> > For grimblast?
> 
> for hyprland

What patches for nvidia? the wiki only mentions of variables, if that is what you meant

**Comment by JaKooLit** [comment]
Hi just a thought

instead of this

dbus-launch --exit-with-session Hyprland

can you try to change and ran Hyprland like this instead

dbus-run-session Hyprland

**Comment by WasteOfO2** [comment]
> Hi just a thought
> 
> instead of this
> 
> dbus-launch --exit-with-session Hyprland
> 
> can you try to change and ran Hyprland like this instead
> 
> dbus-run-session Hyprland

How would this help? I tested this but no effect :(

**Comment by JaKooLit** [comment]
> How would this help? I tested this but no effect :(

I have met somebody before, although it launch Hyprland, he have some issues. But when I suggested to launch with dbus-run-session, he said it solves alot of his issues... Worth a shot:)


Anyway, saw you using wayland-desktop overlay. I think the thegreatmcpain have a nvidia-patched. Try rebuilding from thegreatmcpain overlay instead

**Comment by WasteOfO2** [comment]
> > How would this help? I tested this but no effect :(
> 
> I have met somebody before, although it launch Hyprland, he have some issues. But when I suggested to launch with dbus-run-session, he said it solves alot of his issues... Worth a shot:)
> 
> Anyway, saw you using wayland-desktop overlay. I think the thegreatmcpain have a nvidia-patched. Try rebuilding from thegreatmcpain overlay instead

Is that so? i will look into it then, thanks!

**Comment by vaxerski** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/nvidia.patch?h=hyprland-nvidia-git
