### ISSUE TITLE
Random hangs on latest NixOS

### ISSUE THREAD

**Issue by addy419** [hyprwm/Hyprland#2244]
I don't have the logs for this issue because this is not a crash. After updating to the latest NixOS unstable and updating the kernel to 6.3, Hyprland got really unstable. At some points in time, it hangs for a solid 5 minutes before starting again. I am also unable to access tty in the middle of this.

Switching back to a previous NixOS iteration fixes this. I am unsure if it is caused by NixOS or a regression in Hyprland.

**Comment by vaxerski** [comment]
@fufexan for nix

**Comment by addy419** [comment]
@vaxerski I removed the hyprland flake and installed hyprland through nixpkgs and everything feels much faster. I don't know if the issue is solved, so I'll keep this open for a couple days. Will report back.

On a side note, after doing this, everything got bigger, like 1.5x bigger. Do you know what's causing this? I have hidpi disabled since my screen is 1920x1200, could it be that?

**Comment by fufexan** [comment]
How old was your previous version? DPI guessing was added a while ago.

As for the hangs, I've yet to test the latest version, but I'll try it as well.

**Comment by addy419** [comment]
@fufexan it was fairly recent, around 15 days ago. So maybe not then.

**Comment by fufexan** [comment]
I've tested the latest version of both Hyprland and nixos-unstable, and it does not cause hangs for me. Might be hardware-related?

**Comment by addy419** [comment]
I haven't encountered the hangs in the last few days. So I'll close this for now.
