### ISSUE TITLE
Tooltip constantly re-renders in JetBrains IDEs 

### ISSUE THREAD

**Issue by lisophoria** [hyprwm/Hyprland#2245]
This issue once cause a crash. I wasn't able to reproduce crash again, pinning crashlog. As I can say, I didn't ever notice this issue before today

Steps to reproduce:

1. Open any JetBrains IDE
2. Hover on, in example, sidebar button

Expected: successfully rendered tooltip
Noted: tooltip re-renders until you run out of memory, system become completely unusable

Full config can be found at:
[config](https://github.com/lisophoria/hyprland-dotfiles)

Logs:
[last_log.txt](https://github.com/hyprwm/Hyprland/files/11402298/last_log.txt)
[hyprlandCrashReport5512.txt](https://github.com/hyprwm/Hyprland/files/11402302/hyprlandCrashReport5512.txt)

**Comment by vaxerski** [comment]
it _does_ show up for me,
![image](https://user-images.githubusercontent.com/43317083/236351265-67c27cbf-b429-4e2f-bbb3-f32b556aafed.png)

but yeah there is some spam, probably due to the wonky focus around the buttons. Not only xwayland, but also java. Great.

**Comment by lisophoria** [comment]
For me it just appears for a moment (a very short one), then start blinking. After a few seconds all I can see is my hyprland/window waybar plugin goes crazy, as well as active border

**Comment by YinAqu** [comment]
I'm encountering the same issue, a while ago there was no this problem, seems hyprland `forceinput` all floating window by default during recent updates. see https://github.com/hyprwm/Hyprland/issues/2117#issuecomment-1522004181

> **Note: do not use the `forceinput` rule without title, like:**
> 
> ```
> windowrulev2 = forceinput,class:^(jetbrains-.*)
> ```
> 
> do so every IDEA popup will request focus, include cursor hover(on some icons, e.g. git, debug) popup windows, which will result in a infinite create->lose focus->close ->create loop when cursor is hovering on that kind of icons, and would be a performance issue in IDEA new ui.

**Comment by lisophoria** [comment]
> seems hyprland `forceinput` all floating windows by default during recent updates

Experience this issue only in JetBrains IDE's and only with tooltips. Any other floating windows work as intended without any error occurred.

But yeah, issue appeared after the latest update ☹️

**Comment by lisophoria** [comment]
It would've be nice to post this before

https://user-images.githubusercontent.com/39840328/236578544-332c729a-2089-4277-b711-42b00e46fe69.mov

**Comment by vaxerski** [comment]
WHY DOES THAT WINDOW HAVE THE `_NET_WM_WINDOW_TYPE_DIALOG` ATOM WTF

Either X11 is just completely making no sense here or intellij are setting wrong atoms

**Comment by lisophoria** [comment]
I'm actually not facing this issue on sway, everything works as intended

**Comment by vaxerski** [comment]
Cool. and? intellij is clearly setting their atoms wrong here

**Comment by vaxerski** [comment]
fixed in 4ad03af544ba56399918642b609ed538764d1c0f

**Comment by FunProgramer** [comment]
Hello, I have the same problem with idea version 2023.2.3 and hyprland commit c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a

**Comment by reinux** [comment]
I'm having a similar issue with certain dialog boxes in Jetbrains IDEs. Worst symptom is when I try to rename an identifier, the dialog pops up blank and crashes the whole IDE.

**Comment by cyhyraethz** [comment]
Those two window rules fixed it for me. Thanks, @black-fake!

**Comment by Pablu23** [comment]
For anyone looking to resolve this for the newest hyprland Version its these windowrules now
```
windowrule = float on, match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$
windowrule = no_focus on, match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$
```

**Comment by yfthbr** [comment]
used these window rules to fix them in both jetbrains and ghidra. Without the no_follow_mouse they would still disappear too quickly in the latter. 

```
windowrule {
	name = bad-x11-tooltips
	match:xwayland = true
	match:title = ^win[0-9]+$
	float = on
	no_focus = on
	no_anim = on
	no_follow_mouse = on
}
```

(This is a prominent result in Google for hyprland tooltips flickering in general)
