### ISSUE TITLE
hyprctl dispatch resizewindowpixel does nothing

### ISSUE THREAD

**Issue by YodaEmbedding** [hyprwm/Hyprland#2246]
These don't work:
```bash
$ hyprctl dispatch resizewindowpixel exact 1900 640, address:0xdeadbeef
ok
# ...but does nothing

$ hyprctl dispatch resizewindowpixel this_is_not_a_valid_command but doesnt crash
ok
```

Also, `focuswindow` sometimes works, sometimes does nothing. A bit buggy w.r.t. special workspaces.

---

EDIT: Problem resolved; no space after comma:
```bash
$ hyprctl dispatch resizewindowpixel exact 1900 640,'^Spotify$'

$ hyprctl dispatch resizewindowpixel exact 1900 640,"title:Spotify"

$ hyprctl dispatch resizewindowpixel exact 1900 640,address:0xdeadbeef

$ hyprctl dispatch resizeactive exact 1900 640
```

**Comment by vaxerski** [comment]
rtfw

>$ hyprctl dispatch resizewindowpixel exact 50 50, address:0xdeadbeef
ok
\# ...but does nothing

because no space after comma allowed

> focuswindow sometimes works, sometimes does nothing. A bit buggy w.r.t. special workspaces.

that's true
