### ISSUE TITLE
Windows sent to special workspace through movetoworkspace become floating and sticky

### ISSUE THREAD

**Issue by theRealCarneiro** [hyprwm/Hyprland#2250]
Started happening after 8435d6f
How to reproduce:

- ```hyprctl dispatch movetoworkspace special```
- Window becomes sticky and float and is not sent to special workspace

**Comment by vaxerski** [comment]
I can't repro, it gets sent to the special workspace and it opens. If you want to send the window to the special workspace without opening it, use `movetoworkspacesilent`

**Comment by theRealCarneiro** [comment]
with movetoworkspacesilent I get the desired behavior, but with movetoworkspace i still get this weird effect
Also tested using hotkeys, toggling the special workspace on and off, using the command in a terminal, specifying the window class
Using hyprland-git r2877.8435d6fc-1

**Comment by MightyPlaza** [comment]
seems fixed or can't repro

**Comment by vaxerski** [comment]
likely
