### ISSUE TITLE
WORKSPACES - Line Parsing Error

### ISSUE THREAD

**Issue by frkli1965** [hyprwm/Hyprland#2251]
Contrary to that stated in the WIKI, the following will generate a "line parsing error"...

workspace = name:Hello, monitor:DP-1, default:true

as will...

workspace = 1, monitor:DP-1, default:true

whereas...

workspace = 1, monitor:DP-1

is fine.

Therefore how does one specify a default workspace for a particular monitor?

**Comment by vaxerski** [comment]
consider updating to -git before reading the -git wiki
