### ISSUE TITLE
Crashes with dpms and lock screen

### ISSUE THREAD

**Issue by hvitoi** [hyprwm/Hyprland#2253]
Unlocking a locked session with dpms off eventually crashes Hyprland

```
exec-once = swayidle -w timeout 300 'loginctl lock-session' before-sleep 'loginctl lock-session' lock 'sleep 1 && hyprctl dispatch dpms off && swaylock -f -c 000000'
```

The crash usually happens right after inputing the password.
Maybe unrelated but I have a 3 GPU setup configured by:

```
env = WLR_DRM_DEVICES,/dev/dri/by-name/amd-radeon-rx-6600-xt:/dev/dri/by-name/amd-radeon-pro-5500m:/dev/dri/by-name/intel-uhd-graphics-630
```

Without `dpms off` I encountered no issue/crash.

[HyprlandCrash.log](https://github.com/hyprwm/Hyprland/files/11410085/HyprlandCrash.log)
[hyprlandCrashReport12418.txt](https://github.com/hyprwm/Hyprland/files/11410086/hyprlandCrashReport12418.txt)
[coredumpctl.txt](https://github.com/hyprwm/Hyprland/files/11410087/coredumpctl.txt)

**Comment by vaxerski** [comment]
completely broken coredump, consider not stripping the symbols via whatever method you installed hyprland with.

**Comment by hvitoi** [comment]
That's the output I got from `coredumpctl info` according to the [issue guidelines](https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md). Installed from AUR. 

[coredumpctl.txt](https://github.com/hyprwm/Hyprland/files/11410794/coredumpctl.txt)

**Comment by vaxerski** [comment]
something's very wrong with that coredump then, and I dunno what. At any rate, it's unusable

**Comment by tchofy** [comment]
Do you happen to be using swaylock-effects? It was the cause of dpms crashes for me and a few other users for a while, it's fine with standard swaylock.

**Comment by hvitoi** [comment]
I use the standard `swaylock 1.7.2-1`
This crash is pretty much reproductible on my machine, unfortunately the hypr logs and coredump look always like those uploaded above
Output from journalctl:

```log
May 06 14:05:08 coruscant kernel: Hyprland[807]: segfault at 20 ip 00007fde837374f6 sp 00007ffeb5db26c0 error 4 in libgcc_s.so.1[7fde83722000+1b000] likely on CPU 0 (core 0, socket 0)
May 06 14:05:08 coruscant kernel: Code: 00 00 00 00 3c 04 0f 85 90 ab fe ff 41 bd 18 00 00 00 e9 e6 fd ff ff 0f 1f 44 00 00 48 8b 95 98 00 00 00 48 8b 85 90 00 00 00 <80> 3a 48 0f 85 59 ff ff ff 48 b9 c7 c0 0f 00 00 00 0f 05 48 39 4a
May 06 14:05:08 coruscant systemd[1]: Created slice Slice /system/systemd-coredump.
May 06 14:05:08 coruscant systemd[1]: Started Process Core Dump (PID 3322/UID 0).
May 06 14:05:09 coruscant systemd-coredump[3323]: Process 807 (Hyprland) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 807:
                                                  #0  0x00007fde837374f6 x86_64_fallback_frame_state (libgcc_s.so.1 + 0x194f6)
                                                  #1  0x00007fde837393b4 _Unwind_Backtrace (libgcc_s.so.1 + 0x1b3b4)
                                                  #2  0x00007fde8332e0b3 __backtrace (libc.so.6 + 0x1180b3)
                                                  #3  0x00005588d3867c7e _ZN13CrashReporter18createAndSaveCrashEi (Hyprland + 0xfdc7e)
                                                  #4  0x00005588d3804a4c _Z25handleUnrecoverableSignali (Hyprland + 0x9aa4c)
                                                  #5  0x00007fde8324fab0 n/a (libc.so.6 + 0x39ab0)
                                                  #6  0x0000000000000020 n/a (n/a + 0x0)
                                                  ELF object binary architecture: AMD x86-64
May 06 14:05:09 coruscant systemd[1]: systemd-coredump@0-3322-0.service: Deactivated successfully.
May 06 14:05:09 coruscant polkitd[662]: Unregistered Authentication Agent for unix-session:3 (system bus name :1.30, object path /org/kde/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
May 06 14:05:09 coruscant greetd[793]: pam_unix(greetd:session): session closed for user hv
```

**Comment by hvitoi** [comment]
A workaround on this that I have found is to unset `misc.key_press_enables_dpms`, with that disabled I no longer had crashes. Instead I enable the monitors again with the mouse only `misc.mouse_move_enables_dpms=true`
