### ISSUE TITLE
Add ability to natively swap caps and escape

### ISSUE THREAD

**Issue by mbazzani** [hyprwm/Hyprland#2255]
Currently, swapping the caps and escape keys requires hacky solutions like using ydotool or caps2escape. It would be extremely convenient for the many vim users that use hyprland if we had a native solution built directly into hyprland. Thanks for considering this!

**Comment by vaxerski** [comment]
aint that an xkb opt?

**Comment by ericmurphyxyz** [comment]
It's as easy as adding `kb_options=caps:swapescape` to your `hyprland.conf` under the `input` section

**Comment by shaeinst** [comment]
can we do following natively ?
Maps Caps Lock to Escape when pressed and Control when held.

With [keyd](https://github.com/rvaiya/keyd), I have this in my keyd config:
```conf
[ids]
*

[main]
capslock = overload(capslock, esc)
esc = capslock

[capslock:C]
h = left
k = up
j = down
l = right
```
