### ISSUE TITLE
Update config file when updating Hyprland

### ISSUE THREAD

**Issue by TheLastTeapot** [hyprwm/Hyprland#226]
When you update Hyprland, any new configuration options are added to the file and set to disabled, but existing ones are unchanged.
This would be amazing, because you wouldn't have to search the wiki every time you update, or miss new features.

**Comment by PowerBall253** [comment]
We'd would first need to implement a way for Hyprland to detect it has been updated (I think).

**Comment by TheLastTeapot** [comment]
Surely it could just check every time it is compiled whether or not there are any new options? If there weren't any new ones, it wouldn't need to do anything regardless of whether it was updated or not.

**Comment by vaxerski** [comment]
pretty bad idea, no. in the wiki, why not use ctrl+f?

**Comment by TheLastTeapot** [comment]
What would that do?

**Comment by vaxerski** [comment]
make me have to add additional bloat for no fucking reason? 

The configs are backwards compatible. If you want new features, read the commits.

**Comment by fufexan** [comment]
An automated changelog on release will make this a non-problem.

**Comment by TheLastTeapot** [comment]
I didn't figure it would be that big of a deal, couldn't you just have a little script check for the presence of all the keywords, and copy any from the example config that are missing? I mean I'll do it myself once I learn how, I just didn't think it would be that hard.

**Comment by godalming123** [comment]
@TheLastTeapot is it too big of a comprimise to just have a changes list on the releases. If you ask me that's much more important then this and would easily solve this problem.

**Comment by TheLastTeapot** [comment]
That would work just fine, When I thought of this my idea just seemed like it would be easier in the long run, because it's automatic. But yeah, a changes list would be great.

**Comment by vaxerski** [comment]
closing. Release notes now exist.
