### ISSUE TITLE
0.25.0 -> broken hover scroll over workspace list in waybar-hyprland

### ISSUE THREAD

**Issue by grappas** [hyprwm/Hyprland#2261]
Steps to reproduce
1. Use waybar-hyprland with workspace list.
2. Hover mouse over workspace list.
3. Use scroll.

Expected outcome:
1. Each scroll step result in workspace switch.

Noted outcome:
1. List reacts only for one scroll step
2. Mouse cursor move resets that behavior (another step can be given on input).
3. If workspace is empty you can scroll freely.

I think that's because whenever you switch workspace window is focused (out of waybar). Happens since 0.25.0 release.

https://user-images.githubusercontent.com/1036957/236635238-4c4f834c-043c-44d6-be9a-749932604460.mp4

**Comment by dedguy21** [comment]
I have an icon next to windows indicators, and scrolling over the icon will perform the way you expect fyi.

**Comment by grappas** [comment]
It seems to be fixed in 0.26.

**Comment by cyber-sushi** [comment]
I have this issue again in v0.30.0 (was previously solved in 0.26), anyone else?

**Comment by grappas** [comment]
I got it too again. 
```
        "on-scroll-up": "hyprctl dispatch workspace -2 && sleep 0.01 && ydotool mousemove -x 2 -y 0",
```
Temporary workaround

**Comment by cyber-sushi** [comment]
Oh boy, interesting workaround, I guess I'll have to use it for now, thank you

**Comment by romanstingler** [comment]
is this resolved now?

**Comment by grappas** [comment]
seems to be
