### ISSUE TITLE
bind - scroll is locked if scrolling too fast

### ISSUE THREAD

**Issue by grappas** [hyprwm/Hyprland#2262]
Config:
```
bind = $mainMod, mouse_down, workspace, -2
bind = $mainMod, mouse_up, workspace, +2
```
Steps to reproduce:
1. Put text above to config
2. Use bind given

Expected outcome:
1. You can switch workspaces freely, whatever speed you want.

Given outcome:
1. If scrolling too fast bind is locked. You have to slow it down.

I think that's because bind is without "e" flag, therefore hyprland prevents from repeating. Although using "e" flag results in repeating that bind by just holding SUPER key and scrolling once.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#binds
