### ISSUE TITLE
layer shell keyboard mode ON_DEMAND not working with v4

### ISSUE THREAD

**Issue by dhansmair** [hyprwm/Hyprland#2264]
Hi there!

I'm playing around with GTK4 on wayland, trying to implement a simple panel in python.
I'm using the GTK4-layer-shell from https://github.com/wmww/gtk4-layer-shell.
I'm not an expert, but apparently there are different keyboard modes in the layer shell protocol: `NONE`, `EXCLUSIVE` and `ON_DEMAND`. none means a window should never grab focus, exclusive means a window should always get the focus, and on_demand is like it should get the focus when needed (?). I first mentioned this problem here: https://github.com/wmww/gtk4-layer-shell/issues/19

In my example, I have a button on the panel that opens a popover (like an application menu) with an input field.
The problem on hyprland is:
- with KeyboardMode.NONE, the input cannot receive focus
- with KeyboardMode.EXCLUSIVE, no other window can receive focus
- with KeyboardMode.ON_DEMAND, it is the same as with EXCLUSIVE, even though I expected that to work.

The expected behavior is that when I click the button, the popover opens, and the input field should get the keyboard focus, or at least I should be able to focus it by clicking. However when clicking outside the popover should close and I should be able to interact with the normal windows.

Here is a simple code snippet to reproduce (requires gtk4-layer-shell to be installed):
```python
from ctypes import CDLL
CDLL('libgtk4-layer-shell.so')

import gi
gi.require_version("Gtk", "4.0")
gi.require_version('Gtk4LayerShell', '1.0')
from gi.repository import Gtk, Gtk4LayerShell as LayerShell

def on_activate(app):
    win = Gtk.ApplicationWindow(application=app)

    LayerShell.init_for_window(win)
    LayerShell.set_layer(win, LayerShell.Layer.TOP)
    LayerShell.auto_exclusive_zone_enable(win)
    LayerShell.set_anchor(win, LayerShell.Edge.TOP, True)
    LayerShell.set_keyboard_mode(win, LayerShell.KeyboardMode.ON_DEMAND)
    
    root = Gtk.Box()
    win.set_child(root)
    button = Gtk.Button(label="click me")
    root.append(button)
    def close(*args):
        app.quit()
    popover = Gtk.Popover()
    box = Gtk.Box()
    input = Gtk.Text(placeholder_text='placeholder text')
    button2 = Gtk.Button(label='close')
    button2.connect('clicked', close)
    box.append(input)
    box.append(button2)
    popover.set_child(box)
    popover.set_parent(button)

    def clicked(*args):
        popover.popup()
    button.connect('clicked', clicked)

    win.present()
    
app = Gtk.Application(application_id='org.gtk.Example')
app.connect('activate', on_activate)
app.run(None)
```

thanks for your help and for providing hyprland!

**Comment by dhansmair** [comment]
Okay, actually, ON_DEMAND does not work on sway either. If set, I can interact with windows using the mouse, but not using the keyboard. Can it be that I misunderstand the purpose of this keyboard mode..?

**Comment by dhansmair** [comment]
Update:
Tried to get around ON_DEMAND by only using NONE and EXCLUSIVE.  However, this snippet works on sway, but does not on hyprland (_works_ meaning I can write to the input when the popup is opened and interact with the other windows when the popup is closed):

```python
from ctypes import CDLL
CDLL('libgtk4-layer-shell.so')
import gi
gi.require_version("Gtk", "4.0")
gi.require_version('Gtk4LayerShell', '1.0')
from gi.repository import Gtk, GLib, Gtk4LayerShell as LayerShell


def on_activate(app):
    win = Gtk.ApplicationWindow(application=app)

    LayerShell.init_for_window(win)
    LayerShell.set_layer(win, LayerShell.Layer.TOP)
    LayerShell.auto_exclusive_zone_enable(win)
    LayerShell.set_anchor(win, LayerShell.Edge.TOP, True)
    LayerShell.set_anchor(win, LayerShell.Edge.LEFT, True)
    LayerShell.set_anchor(win, LayerShell.Edge.RIGHT, True)
    
    root = Gtk.Box()
    win.set_child(root)
    button = Gtk.Button(icon_name='system-search-symbolic')
    root.append(button)
    popover = Gtk.Popover()
    popover.set_child(Gtk.Text())
    popover.set_parent(button)

    def clicked_cb(*args):
        LayerShell.set_keyboard_mode(win, LayerShell.KeyboardMode.EXCLUSIVE)
        GLib.idle_add(popover.popup) # need to do this instead of popover.popup() to make it work on sway
        
    def close_cb(*args):
        LayerShell.set_keyboard_mode(win, LayerShell.KeyboardMode.NONE)
        
    button.connect('clicked', clicked_cb)
    popover.connect('closed', close_cb)
    win.present()
    

app = Gtk.Application(application_id='org.gtk.Example')
app.connect('activate', on_activate)
app.run(None)
```

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11416524/patch.txt)

try this patch

**Comment by dhansmair** [comment]
Nice, my workaround https://github.com/hyprwm/Hyprland/issues/2264#issuecomment-1537550582 works with this patch.

Btw, the package `cpio` is missing in the build dependencies listed in https://wiki.hyprland.org/Getting-Started/Installation/.

Regarding the initial problem, can you elaborate on `ON_DEMAND`? From my understanding, this mode should allow to type in the focused input field out of the box.

**Comment by vaxerski** [comment]
probably. Not impl'd in hl though, or sway it seems

**Comment by Consolatis** [comment]
```xml
      <entry name="on_demand" value="2" since="4">
        <description summary="request regular keyboard focus semantics">
          This requests the compositor to allow this surface to be focused and
          unfocused by the user in an implementation-defined manner. The user
          should be able to unfocus this surface even regardless of the layer
          it is on.

          Typically, the compositor will want to use its normal mechanism to
          manage keyboard focus between layer shell surfaces with this setting
          and regular toplevels on the desktop layer (e.g. click to focus).
          Nevertheless, it is possible for a compositor to require a special
          interaction to focus or unfocus layer shell surfaces (e.g. requiring
          a click even if focus follows the mouse normally, or providing a
          keybinding to switch focus between layers).

          This setting is mainly intended for desktop shell components (e.g.
          panels) that allow keyboard interaction. Using this option can allow
          implementing a desktop shell that can be fully usable without the
          mouse.
        </description>
      </entry>
```

As far as I understood, `ON_DEMAND` should basically turn layer surfaces into usual xdg surfaces in relation to keyboard focus behavior.

**Comment by dhansmair** [comment]
So should hl support this? Or should it be implemented in wlroots?
If it's the latter feel free to close this issue @vaxerski

**Comment by vaxerski** [comment]
wlroots has no saying here, it's up to hyprland to support this.

**Comment by Consolatis** [comment]
The main issue is that hyprland still announces version 4 of the protocol although (from what I gathered) it only supports version 3. This is an issue as can be seen in for example https://github.com/pop-os/cosmic-panel/issues/15.

https://github.com/hyprwm/Hyprland/blob/398e861b554268e43e8af64ba72c682630302ec3/src/Compositor.cpp#L192

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12568188/patch.txt)
can someone try this patch?

Wasn't able to run the original python bs.

**Comment by slikie** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/12568188/patch.txt) can someone try this patch?
> 
> Wasn't able to run the original python bs.

With this patch I have it working with replying to messages with swaync
