### ISSUE TITLE
existing workspace rules are not replaced when adding new ones

### ISSUE THREAD

**Issue by ElJeffe** [hyprwm/Hyprland#2268]
When redefining a workspace rule, the old one will have precedence over the new one since the new one is added at the back of the deque, instead of modifying the exiting one.

for instance:
`hyprctl keyword workspace 8,monitor:DP-9`
`hyprctl keyword workspace 8,monitor:eDP-1`

one would expect that workspace 8 would open on eDP-1 but it opens on DP-9

**Comment by dedguy21** [comment]
So did you learn not to write conflicting rules?  Also, seems like you're trying to mix docked profile vs laptop profile, those probably need to be on separate configs.

**Comment by vaxerski** [comment]
413a36a914d5ccab38feb3cab93db8f2b1352363
