### ISSUE TITLE
Togglefloat size and position 

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#2269]
Is there anyway to center and set a specific size only for togglefloat windows

**Comment by shadowelite-sec** [comment]
> Something like this?
> 
> ```
> bind = ALT,SPACE, togglefloating
> bind = ALT,SPACE, centerwindow
> bind = ALT,SPACE, resizeactive, exact 400 200
> ```

Yes but still the resizing is not working

**Comment by YinAqu** [comment]
be sure your target window is **floating** and **active** when you execute `resizeactive`.
FYI, some other approaches depend on your needs: 
`windowrule` 
```
windowrulev2 = float,class:^com.github.hluk.copyq$
windowrulev2 = size 800 1000,class:^com.github.hluk.copyq$
windowrulev2 = center,class:^com.github.hluk.copyq$
```
and `hyprctl` in your scripts: `hyprctl --batch "dispatch resizeactive exact 800 1000; dispatch centerwindow"`

**Comment by MightyPlaza** [comment]
@vaxerski can't this be closed?

**Comment by vaxerski** [comment]
everything can be closed, question is whether it's the right thing to do
