### ISSUE TITLE
Fullscreen 1 opacity changed

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/Hyprland#2277]
Commit [internal: improve fullscreen fade](https://github.com/hyprwm/Hyprland/commit/247ff4e60df15c167f0f6b6b2d899aa22101b2a5) changed the maximize opacity (`fullscreen 1`). Before it would use active opacity but now it uses a different value that somewhat corresponds to active opacity, but is always less transparent.

**Comment by vaxerski** [comment]
fixed in f2725a374a5921903bf918fdfd8111b537cbf18f
