### ISSUE TITLE
Reaper Constant Re-focusing Within The Main Window 

### ISSUE THREAD

**Issue by Twinkie001** [hyprwm/Hyprland#2278]
Hi, sorry to bother you with the legacy X11 stuff, but i really like Hyprland and switched to it as a daily driver. Everything works great except for Reaper(of course lol).  I use Reaper as my main audio production tool and rely on it at the studio. Unfortunately there are no news from the Reaper devs about making it Wayland ready so i was hoping that we could try to get it ironed out a bit.
 As a couple of users before mentioned before that Sway seemed to had all those things too but they fixed them in the git version.

 I could see that the menu bug was fixed, but there is one with the pop-up windows and the constant refocusing one.

The pop-up window bug:
 Initially when i tried to use Reaper, the following would happen: anytime i would open a patch menu or a plugin, it would spawn a small popup window on the top of the main window(with the plugin or something similar) the window would be focused. As i start moving the mouse way from the button and towards  the window it would close itself.
 I found a fix for this by using these window rules together:   **follow_mouse=1    mouse_refocus=false**  
I don't know if it's a good fix but it seemed to have fixed the the popup disappearing problem.

The refocus bug:
This one is the most annoying: when you hover over buttons(mute, solo etc), sliders(faders) and other elements within the main window, the main window keeps constantly going in and out of focus. It seems like Hyprland thinks that each of those elements is a separate window so it keeps shifting the focus away from the min window. This causes slowness, when you work fast the mouse clicks on faders or pan wheels  don't register(or refocus) fast enough and you end up missing and there's no "fader grab action" happening so you end up dragging nothing. Sway on the other hand doesn't exhibit that behavior and the main window stays focused at all times and there's no lag and actuation misses mentioned above. 

   I don't know how useful is the Sway comparison, but it would seem like there should be a simple fix for this...
Lmk what you guys think, any help would be greatly appreciated!

**Comment by Oscillope** [comment]
I have a workaround that seems to fix these issues for me. I am using these window rules:
```
windowrulev2 = move cursor,class:REAPER,floating:1
windowrulev2 = nofocus,class:REAPER,title:^(menu)$
windowrulev2 = nofocus,class:REAPER,title:^$
```

I believe the refocus bug isn't due to the element itself, but due to the tooltip which pops up when you hover over an element or grab a fader. The last rule there sets `nofocus` on the tooltip windows, which fixes that issue.

**Comment by Twinkie001** [comment]
Seem to have worked.
I knew it was something window rule related!
Thank you!

**Comment by Twinkie001** [comment]
I ended up just keeping the windowrulev2 = nofocus,class:REAPER,title:^$
and the windowrule=noanim,^(REAPER)$ because of the janky animations on Xawyland. 
Works like a charm now, case closed!
