### ISSUE TITLE
Incorrect resize of chromium in scaled hdmi second monitor 

### ISSUE THREAD

**Issue by robertlc04** [hyprwm/Hyprland#2280]
wlr-randr information:
HDMI-A-1 "LG Electronics LG TV (HDMI-A-1)"
  Make: LG Electronics
  Model: LG TV
  Serial: (null)
  Physical size: 690x390 mm
  Enabled: yes
  Modes:
    1360x768 px, 60.014999 Hz (preferred)
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 30.000000 Hz
    1920x1080 px, 29.969999 Hz
    1920x1080 px, 24.000000 Hz
    1920x1080 px, 24.000000 Hz
    1920x1080 px, 23.976000 Hz
    1366x768 px, 59.814999 Hz (current)
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 60.317001 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
    720x400 px, 70.082001 Hz
  Position: 1920,0
  Transform: normal
  Scale: 0.800781
  Adaptive Sync: disabled
eDP-1 "BOE 0x0903 (eDP-1)"
  Make: BOE
  Model: 0x0903
  Serial: (null)
  Physical size: 340x190 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000999 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled

Screenshot:
![swappy-20230510-202102](https://github.com/hyprwm/Hyprland/assets/85315700/7eb07ce2-b8ec-4a71-a94e-296e9289286b)

Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by dedguy21** [comment]
Did you try scaling by decimal by hudreth? Ex 1.00, 1.25, 1,50, etc?

**Comment by robertlc04** [comment]
nope i gone try

**Comment by mmhobi7** [comment]
https://www.reddit.com/r/kde/comments/136wxuk/chrome_version_113_scaling_issue_under_wayland/

What I cannot figure out is how to scale by say 2.0 and have it not be fractional scaling

**Comment by webknjaz** [comment]
@robertlc04 when you run `hyprctl monitors`, what are their IDs? Would I be correct to guess that `eDP-1` is your laptop built-in display and is first in the list? This partially resembles something that I observe with an external 4k monitor, but not exactly…

**Comment by romanstingler** [comment]
is this still a thing, I haven't seen that for a long time

**Comment by izmyname** [comment]
Bump. Maybe close, since there's no response from the op?
