### ISSUE TITLE
Hot plugging monitors through an USB C dock do not get re-recognized

### ISSUE THREAD

**Issue by Zoltan-Balazs** [hyprwm/Hyprland#2282]
I'm using a laptop, that has 2 external monitors connected to it through a single USB-C cable.

If I start my laptop normally, both displays get outputs, with their own workspaces, they also show up in `xrandr` and `hyprctl monitors`. If I then unplug the USB-C cable, the all workscapes get correctly shifted over to the laptop's built-in monitor. Re-plugging the same cable (with the same monitor configuration) produces no visible results. The monitors say they are `Scanning for signal`, but fail at `No USB Type-C signal from your device.`. The monitors also do not show up in `xrandr`, nor `hyprctl monitors`.

Interestingly `usb-devices` does show a difference, the USB-C connection is recognized.`dmesg -w` also shows the disconnect/connect of the cable.

Right now I have to switch to another tty, when I do that, the screens do get re-initialized.

**Comment by dedguy21** [comment]
Are you using AMD graphics, and have you read the FAQs --> https://wiki.hyprland.org/FAQ/#my-external-monitor-is-blank--doesnt-render--receives-no-signal-laptop

**Comment by vaxerski** [comment]
wlroots bug if anything
