### ISSUE TITLE
fullscreen field not respected in windowrulev2

### ISSUE THREAD

**Issue by Preetam-Das** [hyprwm/Hyprland#2283]
**NOTE: This does not crash Hyprland.  Just an invalid behavior.** 

### Steps to reproduce
I wanted to make my terminal transparent and everything else opaque. So i changed the opacity variables to 1 and made an window rule for my terminal:
```
decoration {
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
}
windowrulev2 = opacity 0.9 0.9, class:^(kitty)$
```
This works fine *except when the terminal is fullscreen*. So i added the the `fullscreen` field to the windowrules:
```
windowrulev2 = opacity 0.9 0.9, class:^(kitty)$, fullscreen:1
windowrulev2 = opacity 0.9 0.9, class:^(kitty)$, fullscreen:0
```
According to the [wiki](https://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2) this should work, but it does not. I checked with other fields, **every other fields are working fine, even `fullscreen: 0` works fine** but `fullscreen:1`  does not seem to have any effect.

### Expected outcome
kitty should be transparent even when made fullscreen.

### Noted outcome
kitty is not transparent when made fullscreen, `fullscreen: 1` does not have any effect.

**Comment by dedguy21** [comment]
Umm, terminal emulators usually have thier own  "Opacity" settings, so in this case why not just set the Opacity in the terminal config?

I use kitty, it definitely stays transparent on full screen if you change trhe opacity in kitty config.

**Comment by Preetam-Das** [comment]
@dedguy21 Wow this never crossed my mind. It works fine by setting `background_opacity` in kitty's config. Well solves my issues, but still does not changes the fact that `fullscreen: 1` does not work (any idea why?).

I'll close the issue for now.

**Comment by dedguy21** [comment]
> @dedguy21 Wow this never crossed my mind. It works fine by setting `background_opacity` in kitty's config. Well solves my issues, but still does not changes the fact that `fullscreen: 1` does not work (any idea why?).
> 
> I'll close the issue for now.

I'm failing to see why you require a windows rule. If you set the opacity in the kitty config that will be applied whether full screen or floating.

**Comment by Preetam-Das** [comment]
> > @dedguy21 Wow this never crossed my mind. It works fine by setting `background_opacity` in kitty's config. Well solves my issues, but still does not changes the fact that `fullscreen: 1` does not work (any idea why?).
> > I'll close the issue for now.
> 
> I'm failing to see why you require a windows rule. If you set the opacity in the kitty config that will be applied whether full screen or floating.

Yea I did set the opacity in kitty's config it works fine, that's what i said. But other application which don't have their own opacity setting will have the same problem, no?

**Comment by dedguy21** [comment]
Try "true" instead of one just to double check that bool

**Comment by vaxerski** [comment]
`opacity active inactive` fullscreen is unaffected
