### ISSUE TITLE
indicate grouped windows with tabs when no_gaps_when_only is on

### ISSUE THREAD

**Issue by hazycora** [hyprwm/Hyprland#2286]
Window groups in hyprland have tabs, but when `no_gaps_when_only` is enabled they're turned off along with regular window borders, so there is no indication a window is a group when this setting is on. I think the tab lines at the top of window groups should remain visible with this setting on

**Comment by wilecoyote2015** [comment]
This is also related to #520

**Comment by hazycora** [comment]
I'm not sure it is? While it was mentioned in the comments of that issue, I think it's a separate feature, that's specific to the text being included and I'm referring to just the border being hidden with or without text

**Comment by MightyPlaza** [comment]
also implemented now @vaxerski
