### ISSUE TITLE
A few seconds after Hyprland startup  monitors suddenly turn dark with only mouse cursor working. exit and relaunch Hyprland from TTY, every thing works perfectly fine

### ISSUE THREAD

**Issue by Stewart86** [hyprwm/Hyprland#2291]
@fufexan 

Using Microsoft Surface Laptop 4 on NixOS with this flake [config](https://github.com/stewart86/flakes) on unstable channel with latest Hyprland commits.  A few seconds after Hyprland startup using TTY (logind), either laptop display only or with external monitors, suddenly turn dark with only mouse cursor working. Everything seems to be working behind the blacked out displays. tested like a blinded man, move around with cursor and typed even logging off and exiting Hyprland. All working fine just with a black out displays.

Weirdly, after exiting and relaunch Hyprland from TTY, every things work perfectly fine after all. Except for some services that required restart manually. I am even writing this issue with a running Hyprland after one relaunch.

Things I have tried:
1. disable auto start
2. clean up nix config and find faulted nix configuration
3. read and reread faqs and GitHub issues
4. study Hyprland logs to find errors
5. finding coredump (no coredump triggered) 

<details>
<summary>Start of log for System info</summary>
[LOG] Instance Signature: cc01550aff70a0cbee5b62db5f4a08789244998f_1683936592
[LOG] Hyprland PID: 1388
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: surface-nix
[LOG] Release: 6.1.18
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Mar 11 12:55:44 UTC 2023

[LOG] GPU information:

[LOG] os-release:
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.05.20230506.897876e"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.05 (Stoat)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.05 (Stoat)"
VERSION_CODENAME=stoat
VERSION_ID="23.05"

</details>

[full log here](https://pastebin.com/pyktbzhn)

**Comment by katsuja** [comment]
I have the same problem.
Surface laptop 4 on Arch linux, after a few seconds from login the screen goes black and the mouse is visible.
journalctl:
amdgpu 0000:03:00.0: amdgpu: Secure display: Generic Failure.
amdgpu amdgpu: SECUREDISPLAY: query securedisplay TA failed. ret 0x0

**Comment by fufexan** [comment]
Could you manually build Hyprland and see if that helps? If it doesn't, then Nix isn't to blame and we should ping Vaxry.

Inside the cloned repo:
```bash
$ nix develop
$ meson setup build
$ ninja -C build
```

**Comment by Stewart86** [comment]
This is my first deployment with NixOS so not sure if I am doing things right.

Followed your instruction to clone the repo and manually build with the given command. I am assuming that the build will overwrite my per-user /bin Hyprland? 

Rebooted the system without changes to my nix configuration and same problem occurred. 

Let me know if I did it as you intended @fufexan

**Comment by Stewart86** [comment]
@katsuja I check my journelctl too nothing related to GPU. By the way, I am using Intel version.

**Comment by Stewart86** [comment]
@fufexan I should also mentioned previously was working find until a recent update. I was unable to track to which commit ago since I am configuring my system update flake almost everyday.

**Comment by katsuja** [comment]
Yesterday afternoon I formatted my laptop. From there the problems started. I probably caught the latest update which broke everything.

**Comment by fufexan** [comment]
> I am assuming that the build will overwrite my per-user /bin Hyprland?

No. After building you can run the built binary directly from `<path-to-repo>/build/src/Hyprland`. Not specifying the path will make the system launch Hyprland installed through the flake.

**Comment by Stewart86** [comment]
I have tried the binary from `build/src/Hyprland`. With this, I got more information on the "crash". Technically it did not crash I suppose.

I have narrowed it down to the issue only occur on the first 30 seconds of user login via logind. If i put a `sleep 30` before `exec Hyprland` everything works. I deduce that there might be some services on startup that is causing the problem.

When I have more time, I will try to trace the commit history to find one that doesn't cause any problem. But since I am changing my configuration all the time, I don't know if the effort would worth anything. It might eventually be something that I changed and at the same time I have also did a update. Because the `nixos-rebuild` automatically fetched the latest commit.

**Comment by iynaix** [comment]
> Could you try previous revisions until you get to one that works? It would be helpful to see which commit introduced this regression.

ddfeeba was the commit that introduces the issue for me.

**Comment by Stewart86** [comment]
First of all, happy to see someone from Singapore in this community @iynaix 

It seems about right. But I will try one commit before that to confirm. So far I tried v0.24.1 and Hyprland just couldn't start at all and left me with a console cursor blinking.

**Comment by katsuja** [comment]
With a clean install of arch Linux everything worked perfectly again. I don't want the problem to be after upgrading the kernel-surface, but not following the commits I couldn't tell which.

**Comment by buttergrillcorn** [comment]
I have the same issue using Endeavour OS with Linux Surface kernel. I think it started happening after a certain update too since it worked fine before that.

**Comment by pratyush-1327** [comment]
I am also facing this issue from a recent update..

**Comment by vaxerski** [comment]
@iynaix if that's the case, what about this patch?

[patch.txt](https://github.com/hyprwm/Hyprland/files/11543949/patch.txt)

**Comment by iynaix** [comment]
Patch didn't work for me either unfortunately

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11546076/patch.txt)

use this patch (reset old one) and send log

**Comment by Stewart86** [comment]
Here is the log after adding the patch. 
[hyprland-debug-zoominfactor.log](https://github.com/hyprwm/Hyprland/files/11546224/hyprland-debug-zoominfactor.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11547803/patch.txt)

what about this, more elegant patch then?

**Comment by iynaix** [comment]
The more elegant patch is working for me. :smile:

**Comment by Stewart86** [comment]
It works for for me too!
