### ISSUE TITLE
FEATURE: ability to create custom keywords and access through `hyprctl`

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#2293]
Goog day to you!

suggesting for ability to be able to create custom variables and access them through `hyprctl`, like:
```bash
hyprctl setoption user:plugin_name:variable value
hyprctl getoption user:plugin_name:variable
```

usecase: to store and access some data related to Hyprland plugins,
i'm writing plugin similar to Plasma's `Activities` and i need to store at runtime current `activity` id

thank you!

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/blob/b748b0734f27c978758c45b6e18520f7522b9d6f/src/plugins/PluginAPI.hpp#L97-L114

for hyprctl:
`hyprctl keyword plugin:blah:name value`
`hyprctl getoption plugin:blah:name`

?

**Comment by fedoranvar** [comment]
@vaxerski 
so, i can use this `plugin` namespace if i have `plugin.so`?

i can't just add custom variables in hyprland.conf without loading plugins?

**Comment by vaxerski** [comment]
you cant add custom variables without plugins, correct
