### ISSUE TITLE
`focusmonitor +1` won't refocus a window after `movewindow, mon:+1`

### ISSUE THREAD

**Issue by 11xx** [hyprwm/Hyprland#2296]
Pretty minor issue.

On a two monitor setup, with Dwindle layout, using a keybind for `movewindow, mon:+1` on e.g. workspace 1, when switching back to the previous monitor with `focusmonitor +1` no window is focused on that workspace. Doing pretty much anything other than `focusmonitor +1` again on workspace 1 focuses a window back.

Edit: Just to add, this seems to be related to when a split is "unsplit" and the focus goes to another monitor, this makes what may be the "last window" information point to a now not-present window. This also happens in some swallowing cases.

**Comment by David-Aguilo** [comment]
I have the same issue with a master-stack layout and 3 monitors. Moving a window to another monitor with `movewindow, mon:ID` will make it so when going back to the previous monitor no window is focused. I'm using release 0.25.0-1.

**Comment by vaxerski** [comment]
should be fixed with 088b4a68e6288e7bbeb7fb9a31798d47e4d13a78
