### ISSUE TITLE
Fullscreen video crashes hyprland

### ISSUE THREAD

**Issue by addy419** [hyprwm/Hyprland#2297]
Since this is on NixOS, I'll tag @fufexan as well.

I am using echo360 for watching my university lectures. Whenever I fullscreen the video, after a while (say 5 mins) the screen goes black. Moving the mouse brings it back, but I am unable to do anything to that video anymore.
The keyboard inputs work for pausing/playing the video, but pressing esc does not do anything. It feels like a single screen (like cage) and does not accept mouse input or anything. Switching to another tty is possible, but that's it. There's no way to get back into the hyprland session except issuing a restart command from another tty.
This has occurred every single time, as I can reproduce it. It does not happen with youtube videos tho (at least I haven't experienced that. I think that it disconnects the monitor when the screen goes black, but I am not sure.

I have attached the log from my last session after restart.
[a.txt](https://github.com/hyprwm/Hyprland/files/11472650/a.txt)

**Comment by Kutaygb** [comment]
I am experiencing a similar issue with my T480 laptop system Arch Linux kernel 6.4.1-arch2-1, which has Intel UHD Graphics 620. Whenever I attempt to play a video on Firefox, Chromium or VLC , my system freezes within five minutes, rendering it unresponsive. Strangely, this problem does not occur when I watch videos using mpv or when I stream DRM-protected content on platforms like Disney+ or Netflix.

**Comment by benvonh** [comment]
Same for me. Running NixOS 23.05 on a Zephyrus G14 laptop with an AMD GPU. After a few minutes of watching YouTube on fullscreen, the screen will freeze, flicker to a black screen or between two frames with audio still playing/glitching. No keyboard or mouse movement works including when trying to switch TTY. This didn't happen before in NixOS 22.11.

**Comment by fufexan** [comment]
Does not happen to me, so please bisect.

**Comment by fufexan** [comment]
Also, does this happen with Hyprland from Nixpkgs or from the flake?

**Comment by benvonh** [comment]
> Also, does this happen with Hyprland from Nixpkgs or from the flake?

I am using the flake; don't know about the nixpkgs. I guess the specific NixOS version doesn't matter then, I'm not too sure.

**Comment by fufexan** [comment]
I'm on unstable. From what I've seen, mismatched mesa versions could cause issues. But I've taken care of that, so now whenever there's a new mesa version in nixpkgs, Hyprland's nixpkgs input is updated.

**Comment by auximorus** [comment]
Same issue when i watch any video on youtube on full screen, sometimes when i skip or rewind the video for few seconds it gets stuck on the same position, although the video slider is moving and voice is also coming fine just the display gets stuck, rest everything is functioning fine.
I am using hyprland on fedora, any help will be appreciated
