### ISSUE TITLE
[regression?] (some?!) gtk/Qt apps suddenly have double cursor size (since 0.25.0) 

### ISSUE THREAD

**Issue by ppenguin** [hyprwm/Hyprland#2298]
(@fufexan ? Not sure whether this is `nixos` related, or indirectly via updated flake deps referring to `wl` libs?)

Since using v. `0.25.0` I appear to have issues, [this one on AMD GPU](https://github.com/hyprwm/Hyprland/issues/2213#issuecomment-1540757025) and [this one](https://discourse.nixos.org/t/sudden-regression-wayland-some-apps-double-size-cursor/28170) on my laptop with `i915` (intel integrated) GPU.

This issue pertains to the second reference, but the first one might be relevant in relation to possible changed behaviour in WL libs?

At first I thought it might be a wider issue (not `Hyprland` specific, hence the post on NixOS discourse), but I tried running the same (in this case `chrome`) on `sway` on exactly the same system (`i915` GPU) with the same libs and the problem did not occur.

Note the details on the behaviour of the respective apps in the [above mentioned post](https://discourse.nixos.org/t/sudden-regression-wayland-some-apps-double-size-cursor/28170). The strangest is that the scaling issue **only** affects the cursor (and for some the hotspot coordinates), but not the scaling of fonts and graphical elements.

Any ideas what might be causing this or how to debug this?

**Comment by fufexan** [comment]
I've noticed the same problem but only on chromium. However, most GTK and Qt apps seem to work fine.

I would suggest trying this out in sway or some other Wayland compositor.

**Comment by ppenguin** [comment]
@fufexan yeah, I did try with `sway` (sorry, said `i3` above, meant `sway`) and the problem isn't there then....

**Comment by fufexan** [comment]
@vaxerski do you have the issue? I've tried changing the scale to 1, 2 and in between but it does not help. Also chromium's input seems to be warped top-left somehow.

**Comment by vaxerski** [comment]
`git bisect` plox. I don't seem to have the issue.

**Comment by ppenguin** [comment]
After my update propagated to my desktop (mostly the same config as the laptop, also `nixos`), I now see the same issue on it (`amdgpu`). For the desktop, I needed to use an overlay to force some dependencies to unstable (as mentioned above, and referred in #2213 ), notably `mesa`, to avoid `Hyprland` crashing.

**Comment by MininuxDev** [comment]
This happens to me on discord too when running with ozone (only when hovering elements, otherwise i have the default super small cursor), but weirdly not vscode despite both using electron

**Comment by vaxerski** [comment]
okay can y'all stop repeating that there is an issue and do the `git bisect`?

**Comment by MininuxDev** [comment]
Sorry i just wanted to point out it also happens on non gtk apps, but it turns out i was totally wrong. The cursor was buggy in discord just because i was running it through firejail, disabling it fixed the issue (on my side at least), sorry

**Comment by ppenguin** [comment]
> okay can y'all stop repeating that there is an issue and do the `git bisect`? I realize there is an issue, I don't need it repeated 10 times

Might find some time later this week, very busy atm... One issue is the question to `bisect` *what* exactly, since there are reasons to believe that this is being caused somewhere in a dependency.

So first in the meantime here a few more measuring points:

- to get back to a feasible system state to do actual work, I went back to `hyprland 0.24.1` (by pointing the flake input to the respective commit), which on my 2 systems have the following issues:
  - interestingly the `nix` module didn't compile due to an "unused variable" issue in `hyprctl` (no big deal, just forked and solved it)
  - reverting to this version didn't solve the scaling issue, even though I suppose the dep packages (such as the portal and wlroots) in the `nix` definition must be pinned, so this is unexpected (!?)
- `firefox` is not affected, but when I call a `hyprland-portal dialog` (in this case `jitsi` screen sharing selection), the cursor scale over that window *is* affected.

**Comment by jnsgruk** [comment]
I've just moved over to Hyprland in the last day or so. I'm on NixOS using the overlays defined in the flake here. I get the same behaviour with google-chrome where the cursor is large, and the pointer location is off.

If I change the output config to scale = 1, the issue stops. I don't have the same issue with sway (where I just came from).

Happy to try previous versions or revisions in my flake and keep retrying - haven't tracked the history too closely as I've just migrated so if anyone can point to revisions of the flake to try out I'm happy to dive in.

**Comment by vaxerski** [comment]
> One issue is the question to bisect what exactly

Hyprland, since the original reporter said it's _"since 0.25.0"_

**Comment by ppenguin** [comment]
> > One issue is the question to bisect what exactly
> 
> Hyprland, since the original reporter said it's _"since 0.25.0"_ so I assume 0.24 works

That's indeed what I thought at first (note I am the OP), but since going back to `0.24.1` (see https://github.com/hyprwm/Hyprland/issues/2298#issuecomment-1549393939) the problem was *not* solved. So I'm confused by that, because the related dependencies seem to be pinned reproduceably in the included `nix` package... That's also the reason that I'm not sure how to leverage `git bisect` here, since (1) I haven't found the previous version to work after re-install (though I haven't gone back further), (2) it seems the `nix` package is less hermetic/reproduceable than expected.

**Comment by ppenguin** [comment]
> @ppenguin I am using Brave on NixOS. [config](https://github.com/stewart86/flakes) for reference if you need. Just checking which version of Brave are you running. Reason being.

For me ad-hoc installed `brave` still has the same issue (which doesn't mean _that_ much, since it may still depend on what channel or flake input we are.

**Comment by Stewart86** [comment]
Just saw that #2280 more closely match the issue I faced with Brave v1.51.* @ppenguin does the screenshot on that issue similar to yours?

**Comment by ppenguin** [comment]
> Just saw that #2280 more closely match the issue I faced with Brave v1.51.* @ppenguin does the screenshot on that issue similar to yours?

@Stewart86 No, for me the window and the program's output (area) look completely fine, it's only the mouse cursor and hotspot that are affected (i.e. cursor double size and actual hotspot at `(cursor_x, cursor_y) / 2`)

**Comment by jnsgruk** [comment]
Just noting that on my machines that use the Hyprland flake, and track `nixos-unstable` this is now resolved for me using Google Chrome.

**Comment by ppenguin** [comment]
Since setting my `nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05"` and rebuilding `nixos` and my `home-manager` generation, for me the issue is solved as well...

Closing this as the problem was presumably caused by an incompatible but difficult to pinpoint combination of `wayland` libraries, possibly `opengl`, and `hyprland`.

Thanks to all for staying on it :muscle:
