### ISSUE TITLE
movewindowpixel with negative pixels

### ISSUE THREAD

**Issue by YodaEmbedding** [hyprwm/Hyprland#2300]
This works:
```bash
hyprctl dispatch movewindowpixel exact 40 40,address:0xdeadbeef
```

This does not work:
```bash
hyprctl dispatch movewindowpixel exact -40 -40,address:0xdeadbeef
```

Version: hyprland-nvidia-git r2757.011600ac-1

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/blob/7c207243e41b5b4f35d790767ad2e21eba1b7a0b/src/Compositor.cpp#L2222-L2225

intended behavior?

**Comment by YodaEmbedding** [comment]
Windows can already move offscreen through various means (mouse, etc), e.g.
```
$ hyprctl clients -j
[{
    "at": [-653, -512],
    "size": [800, 640],
    "floating": true,
    ...
},
{
    "at": [9999, 9999],
    "size": [800, 640],
    "floating": true,
    ...
}]
```

It would help with custom scripts if `hyprctl movewindowpixel` also allowed this.

**Comment by NickMundel** [comment]
There seems to be a regression of some sort, where negative x-values are fine, but negative y-values are not.

So this is fine:

`hyprctl dispatch movewindowpixel -1930 0`

This is not:

`hyprctl dispatch movewindowpixel -1930 -10`

Here it responds with showing me the usage details of hyprctl, which would indicate an error with the command.

As far as I can see there is also no log entry generated which would indicate an error.
