### ISSUE TITLE
mpv scaled resolution is higher than the monitor when using 1.5 scaling

### ISSUE THREAD

**Issue by jorgenberg** [hyprwm/Hyprland#2301]
The resolution seems to be divided by 1.5 then doubled. 2 times scaling gives the correct resolution.

Not sure if this is the right place to put this but I don't want to spam issues: Is there any way to have HiDPI XWayland with 1.5 scaling?

Thanks for your help.

**Comment by vaxerski** [comment]
No. X11 does not have fractional scaling at all.
