### ISSUE TITLE
nvidia-smi: only one process named hyprland

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#2302]
OS : Arch Linux

I successfully installed the Nvidia drivers in Hyprland, but `nvidia-smi` is only showing one process named Hyprland with GPU memory usage of <b>1MB</b>.

I am using the `hyprland-nvidia-git` package from AUR. I have also set the grub `nvidia_drm.modeset=1` option, enabled the mkinitcpio modules, and set all the ENV variables mentioned in the wiki.

![20230513_23h19m43s_grim](https://github.com/hyprwm/Hyprland/assets/54718375/d3da4c2c-6ac8-4100-9739-6a1a6564eab8)

I have one integrated Intel GPU and one dedicated Nvidia GPU.

![20230514_00h33m23s_grim](https://github.com/hyprwm/Hyprland/assets/54718375/770a9de0-c44f-4a90-be44-246f12b6ca5c)

please help me to fix this

**Comment by vaxerski** [comment]
great, nvidia is not supported.
