### ISSUE TITLE
Totem(GNOME video player) doesn't respect GTK_THEME envvar

### ISSUE THREAD

**Issue by Orest58008** [hyprwm/Hyprland#2304]
# Steps to reproduce
1. Launch Totem
2. Observe glorious Adwaita theme
# Expected behaviour
Totem having Catppuccin theme
# Actual behaviour
Totem having Adwaita theme

# Other notes
* Other gtk3, gtk4 and GNOME apps are working fine
* Launching totem from console doesn't result in this behaviour

**Comment by vaxerski** [comment]
how is this a hyprland issue?

**Comment by Orest58008** [comment]
It didn't occur on any other WM i tried

**Comment by vaxerski** [comment]
"any other setup" if that setup was a DE then it would handle theming for you. Hyprland has nothing to do with themes, those are handled independently.

**Comment by Orest58008** [comment]
Now that I've switched to sway, everything works perfectly. Both on Arch and Void Linux, so this was Hyprland issue. Unfortunately, I can't reproduce it anymore because I switched to sway.
