### ISSUE TITLE
Make error when building from the release tar

### ISSUE THREAD

**Issue by aadi58002** [hyprwm/Hyprland#2307]
Build trace :-
https://pastebin.com/ivtAb6Nc

pkgname=hyprland-nvidia
version=0.25.0
revision=2
build_style=cmake
hostmakedepends="jq git pkg-config glslang hwids meson ninja"
depends="libinput"
makedepends="
    ffmpeg-devel
    libX11-devel
    pango-devel
    libdrm-devel
    wayland-devel
    libxkbcommon-devel
    pixman-devel
    cairo-devel
    libseat-devel
    libinput-devel
    wayland-devel
    wayland-protocols
    xcb-util-renderutil-devel
    xcb-util-errors-devel
    xcb-util-wm-devel
    xorg-server-xwayland
    vulkan-loader
    Vulkan-Headers
    libglvnd-devel"
configure_args="-DNO_SYSTEMD:STRING=true"
short_desc="Dynamic tiling Wayland compositor that doesn't sacrifice on its looks"
maintainer="Aditya Yadav <aadi58002@gmail.com>"
license="GPL-3.0-or-later"
homepage="https://hyprland.org/"
changelog="https://github.com/hyprwm/Hyprland/releases"
distfiles="https://github.com/hyprwm/Hyprland/releases/download/v${version}/source-v${version}-${revision}.tar.gz"
checksum=0d43297469268457311a916ea3c40bed602c8c8957db81cf862d74c3d5ffbe6b

I have been trying to package hyprland for void linux but i keep getting this error when try to make it.
I also tried the git version which also fails

**Comment by vaxerski** [comment]
>     drm-backend     : NO

wlroots' drm backend is required for hyprland.

Please do not post build issues when the CI does not fail.

**Comment by vaxerski** [comment]
idk how packagers can't even seem to read build logs.

```
Run-time dependency libdisplay-info found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libdisplay-info
Neither a subproject directory nor a libdisplay-info.wrap file was found.
Subproject  libdisplay-info is buildable: NO (disabling)
Dependency libdisplay-info from subproject libdisplay-info found: NO (subproject failed to configure)
Message: Required for the DRM backend.
Run-time dependency libliftoff found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libliftoff
Neither a subproject directory nor a libliftoff.wrap file was found.
Subproject  libliftoff is buildable: NO (disabling)
Dependency libliftoff from subproject libliftoff found: NO (subproject failed to configure)
```

Pretty self-explanatory.

**Comment by aadi58002** [comment]
This is the first time i am packaging a software for a distro.
I will try to learn from this experience.
Thanks for the pointers
