### ISSUE TITLE
Feature Request: Allow client to be visible on multiple workspaces

### ISSUE THREAD

**Issue by marco-04** [hyprwm/Hyprland#2308]
It would allow to manage windows more like dwm, by letting a client being visible on multiple workspaces and preserving its position in the tiling layout

**Comment by vaxerski** [comment]
pin?

**Comment by marco-04** [comment]
Not exactly, what I mean is more like this
https://github.com/hyprwm/Hyprland/assets/61947904/9700dee4-b8ed-4cfc-81ea-90b1b96a32f9

I also saw that pins only work with floating windows and will be undone when a window is forced into a tiling layout

**Comment by marco-04** [comment]
Closing as it very likely won't be implemented
