### ISSUE TITLE
dbus-update-activation-environment zombie

### ISSUE THREAD

**Issue by Twinkie001** [hyprwm/Hyprland#2309]
Looks like #1413 is back:

![image](https://github.com/hyprwm/Hyprland/assets/133128387/a671896e-9bc6-4a29-a5f8-88f2cf44d73a)

I tried latest git and versioned version.
In Sway it goes away in about 40 seconds.

**Comment by Bryan2333** [comment]
I have the same problem. The dbus-update-activation-environment become zombie process.
![swappy-20230525-210627](https://github.com/hyprwm/Hyprland/assets/31512600/1852ea85-1899-44f3-b2df-b4a7cd6a936e)

**Comment by vaxerski** [comment]
I am jealous that y'all have such boring lives that you even have time to worry about something like this

**Comment by Twinkie001** [comment]
I'll admit it that i was bored! When i did "ps -ef|grep defunct", i just watched a Walking Dead episode and from boredom thought: "What if i had some of my own zombies?" Turns out I do ;)

**Comment by Twinkie001** [comment]
On the bright side that's the only thing that i could think of since i'm not trying to run 4 monitors in 8k or anything of that sort :)
Thank you for creating such an awesome WM!

**Comment by charbelnicolas** [comment]
I get the same zombie defunct process :(
