### ISSUE TITLE
Switcher broken in jetbrains IDEs

### ISSUE THREAD

**Issue by otisdog8** [hyprwm/Hyprland#2315]
When I try to use the switcher (ctrl+tab) in a jetbrains IDE, the switcher doesn't disappear and switch tabs. Instead, I need to press ctrl a second time in order to get the correct behavior (so ctrl+tab then ctrl works). This wasn't the case in 0.24.1, so I ran a git bisect and found the following commit to be the issue:

https://github.com/hyprwm/Hyprland/commit/ea77622

I reverted the commit and built from source, and the switcher issue was resolved. I didn't make a PR for this because idk if reverting would break something else.

**Comment by erenatas** [comment]
ctrl+shift+F window also disappears on my side whenever I move my cursor, even 1 pixel causes it to disappear.

**Comment by xbb** [comment]
Maybe related, dragging a tab in the application creates immediately a new floating window that is impossible to dock again.

I didn't test any previous Hyprland version but the workaround for me is this rule:

```
windowrulev2=noinitialfocus,class:^jetbrains-(?!toolbox),floating:1
```

it seems to "fix" also for the other issues you mentioned.

Except "find in files" (`ctrl+shift+f`) require that you focus the window to enable typing, other popups like "find actions" (`ctrl+shift+a`) not...

For the popups that disappear in general when you move the cursor (another example is 1Password Quick Access), you can also try the rule `dimaround`

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

**Comment by romanstingler** [comment]
Switcher automatically disappears as expected

**Comment by tesar-tech** [comment]
I am having the same issue. The switcher is made non-functional, as it steals the focus.

Hyprland v0.50, but was also an issue on v0.49. 
 
https://github.com/hyprwm/Hyprland/issues/2315#issuecomment-1555896701 workaround works.

**Comment by omar-co** [comment]
I had the same issue, after looking a lot for a proper solution the best way to fix it is to go to `Help | Edit Custom VM Options...` and add this: `-Dawt.toolkit.name=WLToolkit`. This will add Wayland support to the IDE.
