### ISSUE TITLE
Crash on mirror display + master layout

### ISSUE THREAD

**Issue by crazyminecuber** [hyprwm/Hyprland#2325]
@fufexan I do not think this issues is related to nix, but I'm running NixOS and build with nix, so pinging in case.

When I try to mirror my two displays and use the master layout, Hyprland crashes. Built Hyprland binary by cloning repo and running `nix build` using the nix flake.

## Steps to reproduce
Try to start hyperland with provided config on my setup

## Expected outcome
Hyperland should start (not crash) and my two displays should be mirrored
## Noted outcome
crash after 2 seconds

[crash_report.txt](https://github.com/hyprwm/Hyprland/files/11501676/crash_report.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/11501678/hyprland.log)
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11501688/hyprland.conf.txt)

**Comment by fufexan** [comment]
Is this a recent regression, or has it never worked?

**Comment by crazyminecuber** [comment]
Started playing with hyprland 3 days ago so I do not know if it has ever worked.

**Comment by crazyminecuber** [comment]
Should I try a git bisect from some commit? What commits do you recommend bisecting between?

**Comment by fufexan** [comment]
Bisecting is a waste of time if you don't know any working commits.

@vaxerski any idea?

**Comment by vaxerski** [comment]
this weekend I am pretty unavailable, ping me on monday

**Comment by vaxerski** [comment]
fixed in 62e3953f5b2274fdb6c41bee079513c5c622234c
