### ISSUE TITLE
Hyprland crashing with a multi-GPU setup

### ISSUE THREAD

**Issue by Sid127** [hyprwm/Hyprland#2328]
[For roughly a week now](https://discord.com/channels/961691461554950145/961694014615208048/1105216072690454629), Hyprland has been crashing on my laptop, Intel iGPU + nvidia dGPU. Using hyprland-nvidia-git AUR package.

most recent crash logs attached
[hyprlandCrashReport892.txt](https://github.com/hyprwm/Hyprland/files/11503860/hyprlandCrashReport892.txt)

**Comment by burein-ita** [comment]
Are you using NVIDIA as primary GPU?

Arch **community** `hyprland` and **aur** `hyprland-git` work fine if you use the Intel iGPU with PRIME render offload configured.

**Comment by Sid127** [comment]
I'm using the iGPU as primary and have PRIME configured as well. Does screenshare and other stuff work fine with the regular package?

**Comment by chiefdinkan** [comment]
> I'm using the iGPU as primary and have PRIME configured as well. Does screenshare and other stuff work fine with the regular package?

yes. I have the same hardware configuration and everything works for me

**Comment by Sid127** [comment]
using simply hyprland-git, and the nvidia GPU doesn't get initialized at all
```
[sidpr@strogg ~]$ nvidia-smi
Unable to determine the device handle for GPU0000:01:00.0: Unknown Error
```

**Comment by Sid127** [comment]
nevermind, it's a different issue with that error, thank you :)
