### ISSUE TITLE
Allow switching to a window in a dwindle group via wlr-foreign-toplevel-management

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#2329]
Steps to reproduce:

0. Install [rofi-lbonn-wayland-git](https://aur.archlinux.org/packages/rofi-lbonn-wayland-git)
1. Make a dwindle group with two windows
2. Run `rofi -show window`
3. Try to switch to a window that is not currently active in the group.
4. Observe that the switch fails.

This also happens with `misc:focus_on_activate = true` on opening an URL from another app when firefox is in a dwindle group (in this case an urgency hint is set instead).

However, `hyprctl dispatch focus` is able to switch to the same window.

**Comment by LorenzoBettini** [comment]
Maybe slightly unrelated, but does that mean that for "standard" windows, i.e., not in a group, rofi wayland works as a window switcher?

**Comment by vaxerski** [comment]
done in 0887e2ee6ec9c7ef106b71c906c6531730c8fdd4
