### ISSUE TITLE
[help] How to change split direction?

### ISSUE THREAD

**Issue by Caleb-T-Owens** [hyprwm/Hyprland#233]
Hi, By default if there are three windows they split kind of like {[  1  ][2][3]}. What I would prefer the my behavior to be when application 3 is opened, 2 and 3 above and below each other. I'd also like to make a key-bind to swap between the vertical and horizontal splits.

I'm sorry if this is really obvious in the documentation but I looked at both configuration sections and there was nothing that looked relevant to me.

**Comment by vaxerski** [comment]
see the dwindle configuration page. You can change the split dynamically, make it locked or force your preferred split direction. If you want more advanced split control, you might have to write a script.

**Comment by PinkFlufflyLlama** [comment]
Ooh, I think my issue is that my monitor is too wide for it to consider placing one beneath the other as an option. 

> The split is determined dynamically with the W/H ratio of the parent node. If W > H, it's side-by-side. If H > W, it's top-and-bottom

Is it possible for me to add a multiplier to the width or height in that comparison so it would determine the split direction differently?

**Comment by PinkFlufflyLlama** [comment]
Looking at it, that appears to a no https://github.com/vaxerski/Hyprland/blob/354e2651289861bf7027fd02be41088e45fc1c99/src/layout/DwindleLayout.cpp#L26.

Could I add a setting for that in a PR?

**Comment by vaxerski** [comment]
feel free. Remember about backwards compatibility.

**Comment by ralgar** [comment]
The forced split direction doesn't seem to be working for me with `v0.6.0` on Arch. Regardless of whether I set it to 0, 1, or 2, it always follows the mouse.

My dwindle config looks like this:
```
dwindle {
    pseudotile=0
    force_split=2
}
```

**Comment by vaxerski** [comment]
if you want to force the split, also make sure it's preserved.

```
dwindle {
    preserve_split=1
}
```
otherwise it'll be dynamically changed.

**Comment by xZecora** [comment]
I'm having this issue as well, I have all the settings listed above and it still seems to follow my mouse. Any other settings that could be affecting this?
