### ISSUE TITLE
Assign workspace to monitor not working

### ISSUE THREAD

**Issue by davxy** [hyprwm/Hyprland#2331]
I'm trying to assign workspaces  to monitors in a 2 monitors setup.

Looks like the assignment is not respected. 

E.g. workspace 3 is expected to be opened on monitor DP-1, but if I'm within a workspace in monitor DP-2 and I switch to workspace 3 then this is opened on monitor DP-2.

```
> hyprctl workspaces
...
workspace ID 3 (3) on monitor DP-2:
	windows: 1
	...
```

```
> hyprctl monitors
Monitor DP-1 (ID 0):
	1920x1080@60.000000 at 0x0
	description: Samsung Electric Company S24B300 H4XC201899 (DP-1 via HDMI)
        ...
        
Monitor DP-2 (ID 1):
	2560x1440@59.951000 at 1920x0
	description: Lenovo Group Limited LEN T27h-20 VNA61WLH (DP-2 via HDMI)
        ....
	active workspace: 3 (3)
	...
```

### Relevant config:

```
cat ~/.config/hypr/hyprland.conf
...
# Assignworkspaces to monitors
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2
...
```

**Comment by staeffn** [comment]
Hello good sir,
here's what I used from https://wiki.hyprland.org/Configuring/Workspace-Rules/ under Examples there's: 
`workspace=DP-1,3,rounding:false,bordersize:0`

I use the first part in my config to assign workspaces to a monitor.
`workspace=DP-1,1
workspace=DVI-D,2
workspace=HDMI-A-2,3
workspace=HDMI-a-2,5`

leading to the hyprctl workspaces output of:
`workspace ID 1 (1) on monitor DP-1:
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x55e3f6928b10
	lastwindowtitle: hyprctl workspaces

workspace ID 3 (3) on monitor HDMI-A-2:
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x0
	lastwindowtitle: 

workspace ID 2 (2) on monitor DVI-D-1:
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x55e3f6912fc0
	lastwindowtitle: Assign workspace to monitor not working · Issue #2331 · hyprwm/Hyprland · GitHub — Mozilla Firefox

workspace ID 5 (5) on monitor HDMI-A-2:
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x0
	lastwindowtitle: `

Hope that helps!

**Comment by staeffn** [comment]
I don't know, I installed hyprland yesterday and I just work with what's in the wiki. 

Yes, that's what I thought at first as well, but it doesn't work, so I just used the given example from the same wiki.
If that makes sense or not I cannot tell nor do I have any influence over it.

But as it is clearly given as an example in the wiki I doubt that it's unintentional and/or buggy.

[see here](https://wiki.hyprland.org/Configuring/Workspace-Rules/#examples)

**Comment by davxy** [comment]
Just updated to [v0.26](https://github.com/hyprwm/Hyprland/releases/tag/v0.26.0) that has been released last week. Issue seems to have fixed. Now works as expected

**Comment by BerenLuth** [comment]
Same for me, my rules are:

```
workspace = r[1-5], monitor:$mainMonitor, rounding:false
workspace = r[6-10], monitor:$secondaryMonitor
```
with the variables defined as
```
$mainMonitor = DP-2
$secondaryMonitor = HDMI-A-1
```
taken from the output of `hyprctl monitors all`

i put the `rounding:false` just as a visual test and i can see that the workspaces 1-5 have indeed sharp corners, but they are not assigned to the right monitors :(

Another weird thing is that apart from being on the wrong monitors, they have a strange behaviour with waybar as well, since in some cases the workspaces appear on waybar on both monitors at the same time

**Comment by Akamiblade1297** [comment]
I have the same issue and I think I found out the issue, but I don't have any idea how to fix it. So I have the rules here:

```
workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
...
workspace = 6, monitor:DVI-D-1
workspace = 7, monitor:DVI-D-1
...
```

So the rules are working, but not for 1 and 2 workspaces, 'cuz they're assigned by default and I don't know how to change it, also waybar doesn't show all the workspaces as well as `hyperctl workspaces` don't:

```
>hyprctl workspaces
workspace ID 2 (2) on monitor HDMI-A-1:
	monitorID: 1
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x5f71d2ee7d10
	lastwindowtitle: Assign workspace to monitor not working · Issue #2331 · hyprwm/Hyprland — Mozilla Firefox

workspace ID 1 (1) on monitor DVI-D-1:
	monitorID: 0
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x5f71d2eb1e60
	lastwindowtitle: hyprctl workspaces
```

I can see those rules with `hyperctl workspacerules` tho, that makes no sense

**Comment by leoferreyra-01** [comment]
For me it worked like this:
```
workspace= 1, monitor:DP-3, default:true
workspace= 2, monitor:HDMI-A-1, default:true
``` 
The "defailt: true" was the key for me. I was struggling to get the right config for the monitor for days now. Thank you all!
