### ISSUE TITLE
Issues with focusmonitor and hyprctl -j monitors if there are no clients on a workspace

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#2332]
I heavily use my keyboard to navigate across my 4 monitors and their applications.

I am having issues when focusing monitors and trying to switch workspaces.
This is how my workspaces and key bindings are set up.
```
wsbind=11,DP-1
wsbind=12,DP-1
wsbind=13,DP-1

wsbind=21,DP-2
wsbind=22,DP-2
wsbind=23,DP-2

wsbind=31,HDMI-A-1
wsbind=32,HDMI-A-1
wsbind=33,HDMI-A-1

wsbind=41,DP-3
wsbind=42,DP-3
wsbind=43,DP-3

workspace=DP-1,11
workspace=DP-2,21
workspace=HDMI-A-1,31
workspace=DP-3,41

bind=SUPER,i,focusmonitor,DP-2
bind=SUPER,k,focusmonitor,DP-1
bind=SUPER,j,focusmonitor,DP-3
bind=SUPER,l,focusmonitor,HDMI-A-1

bind=SUPER_ALT,l,exec,~/.config/hypr/workspace switch next
bind=SUPER_ALT,j,exec,~/.config/hypr/workspace switch prev

```
Here is a snippet of my custom script that determines the current workspace and increses/decreases the number to switch to it

```
from=$(hyprctl -j monitors | jq -r '.[] | select(."focused"==true).activeWorkspace.id')
if [[ $1 == "switch" ]]
then
     if [[ $2 == "next" ]]
     then
        to=$(( $from + 1 ))
     else
        to=$(( $from - 1 ))
     fi
fi
notify-send $from $to
```

This is the actual behaviour
- start on DP-1 (wsp 11-13)
- focusmonitor DP-2 (wsp 21-23)
- monitor DP-2 is focused
- switch to next workspace (from = 21, to = 22) - OK
- the workspace on DP-2 is correctly switched to 22 - OK
- switch to next workspace (from = 11, to = 12) - NOT OK
- instead of switching from 22 to 23, the workspace on DP-1 is switched to 12 - NOT OK

This is the expected behaviour
- start on DP-1 (wsp 11-13)
- focusmonitor DP-2 (wsp 21-23)
- switch to next workspace (from = 21, to = 22)
- switch to next workspace (from = 22, to = 23) 

## Info
This only happens if I use focusmonitor and if there are no clients on the "second" workspace of that monitor. However, if I move the mouse to that monitor this issue does not occur at all.

## Proposed solution
I noticed that focusmonitor does not move the mouse to the specified monitor.
focusmonitor should also move the mouse to the specified monitor, which makes me think that this issue will then be resolved.

**Comment by alerque** [comment]
Same problem here, with the additional twist that `wsbind` seems to be deprecated in 0.26.0 and it isn't clear to me how to even get back to the same behavior as shown in your config. Other changes in the release notes suggest some of the monitor switching issues might be addressed, but I can't test whether they directly fix this issue because I can't even get the workspaces bound to the right monitors to start with.

**Comment by vaxerski** [comment]
e.g. `workspace = 1, monitor:DP-1`

**Comment by xadips** [comment]
```config
monitor = DP-1, 2560x1440@179.960007,0x0,1
monitor = DP-2, 2560x1440@179.960007,2560x0,1
workspace = 1, monitor:DP-1
workspace = 11, monitor:DP-2
```
Tried using this workspace, still when I start up Hyprland up '2' workspace shows up on `DP-2` instead of '11'

**Comment by MightyPlaza** [comment]
is this still relevant?

**Comment by ad-on-is** [comment]
Nope.. it works with the latest version
