### ISSUE TITLE
cursor_inactive_timeout doesn't account for tablet pen

### ISSUE THREAD

**Issue by jneem** [hyprwm/Hyprland#2333]
I have `cursor_inactive_timeout` set to 1, and my cursor disappears 1 second after the last time I move the *mouse*, even if I'm still moving the cursor with my wacom tablet.

I'd argue that the cursor inactive timeout should take into account all input devices that move the cursor, but even if not it would be nice to be able to configure the devices that keep the cursor "alive"

**Comment by vaxerski** [comment]
fixed in 5627b70981730cf1839ae4477f9fd086d4fc7a6c
