### ISSUE TITLE
Feature request: Add an active field for windowrules

### ISSUE THREAD

**Issue by unuing** [hyprwm/Hyprland#2337]
I've configured an opacity of 0.95 for active windows.
It would be useful to have an `active` field for windowrules since you don't want some applications (e.g. image viewer, web browser) to be transparent.

**Comment by burein-ita** [comment]
Use the opacity rule.

**Comment by unuing** [comment]
> Use the opacity rule.

I’m trying to use the opaque rule, but I only want the rule to apply when the window is active because I use the different opacity to know which window is active.

**Comment by burein-ita** [comment]
> I’m trying to use the opaque rule

I'm talking about the `opacity` rule, not the `opaque` rule.
The `opacity` rule allows you to set `activeopacity` and `inactiveopacity` respectively.

**Comment by unuing** [comment]
Thanks!
