### ISSUE TITLE
can't open multiple wezterm instances on a workspace

### ISSUE THREAD

**Issue by hv-something** [hyprwm/Hyprland#2341]
Steps to reproduce:

- Start Hyprland
- Open 2 wezterm instances on a workspace

Expected outcome: 2 wezterm windows open
Noted outcome: all wezterm windows close itself

**Comment by hazycora** [comment]
this works just fine for me.

![image](https://github.com/hyprwm/Hyprland/assets/72580505/2c323aa8-c313-4295-8adf-175ada12369e)

maybe launch wezterm from a different terminal to see what errors are logged when it crashes?

**Comment by hv-something** [comment]
@hazycora I installed wezterm-git and it works fine now
