### ISSUE TITLE
Cannot set solid background wallpaper with swaybg

### ISSUE THREAD

**Issue by aerosol** [hyprwm/Hyprland#2346]
Hello,

Thanks for hyprland, it's fantastic :star_struck: 

I'd like to report a minor bug:

```
exec-once = swaybg -c '#3B6EA5'
```

won't work -- likely due to `#` character? Wrapping it with a script is fine though.

**Comment by MightyPlaza** [comment]
Use double # to escape
`exec-once = swaybg -c '##3B6EA5'`

**Comment by aerosol** [comment]
Oh amazing, thank you

**Comment by lilydjwg** [comment]
This doesn't work for me. The whole `##...` argument is missing.
