### ISSUE TITLE
Groupbar titles are cut off if gaps are too small

### ISSUE THREAD

**Issue by wilecoyote2015** [hyprwm/Hyprland#2348]
# Steps to Reproduce
1. set the following variables in the config: 
   ```
   general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
   }
   ```
2. Open some windows and put them into a group

# Expected Outcome
as titles are rendered, the group bar should always be rendered at least high as the group title.

# Observed Outcome
only a small fraction of the titles is visible because the group bar height is less than the group title height

# Ideas
Intuitively, one might assume that the group bars should always be rendered as high as the group title (+ padding), but maybe it could be a nice and more general solution to make the group bar height configurable directly, also for the case that `render_titles_in_groupbar` is `false`?

**Comment by vaxerski** [comment]
fixed in 799add8659fe896579f050ee0ddeda63a2df5b91
