### ISSUE TITLE
Group indicator fails to refresh after closing last group window

### ISSUE THREAD

**Issue by burein-ita** [hyprwm/Hyprland#2351]
Using latest commit `eb1f832`
Intel GPU
Arch Linux

When a window is grouped an indicator is shown above it.

If there is only one window left in a workspace and this window is a `group`, the moment this window is closed the indicator will not disappear until the screen is refreshed by another animation e.g., opening a window.

This affects both animations styles `popin` and `slide` (the slide animation showing a trail of indicators) and regardless of window titles being enabled or disabled.

This only happens when animations are enabled.

example:
https://youtu.be/9fQ5WEWek_I

**Comment by vaxerski** [comment]
xD

**Comment by vaxerski** [comment]
dont seem to be able to repro

**Comment by vaxerski** [comment]
obviously its a dt issue, can you send your cunfig

**Comment by burein-ita** [comment]
canfig:
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11557191/hyprland.conf.txt)

**Comment by vaxerski** [comment]
you have titles disabled, but in the window they are present...?

**Comment by burein-ita** [comment]
No, I disabled them just to test.

**Comment by burein-ita** [comment]
A lot of stuff has change since I opened this issue. Mesa updates, kernel updates, and changes in Hyprland's render engine. Dunno what fix it but the problem is gone.

**Comment by MightyPlaza** [comment]
nop you just need to disable blur
