### ISSUE TITLE
Not a Bug. Some question of kitty work with fcitx5.

### ISSUE THREAD

**Issue by awarewen** [hyprwm/Hyprland#2355]
-- fcitx5 pkg
![图片](https://github.com/hyprwm/Hyprland/assets/53365857/80995ad3-71e3-4d90-a353-1fc975efd692)

-- environment
![图片](https://github.com/hyprwm/Hyprland/assets/53365857/403a5a95-bb3e-473a-9671-e4d59af3bd92)

-- kitty
![kitty](https://github.com/hyprwm/Hyprland/assets/53365857/d18dab14-88a1-4b84-9ebb-255e19aa358f)

-- firefox
![firefox](https://github.com/hyprwm/Hyprland/assets/53365857/656e4762-6154-4e36-a177-b0d093d1d618)

## I not sure , is that a problem of fcitx5 work with kitty in hyprland?

I cant found something helpfully of that in hyprland wiki or issue or other.

Has anyone same problem like this?

## I try to change `GLFW_IM_MODULE=fcitx` but it doesnt work.

--- fcitx5-diagnose
[fcitx5_log.txt](https://github.com/hyprwm/Hyprland/files/11557011/fcitx5_log.txt)

SoS,  T-T.

**Comment by vaxerski** [comment]
for kitty, you need to set `GLFW_IM_MODULE` to `ibus` regardless of the IME being used, seems to work for me

![image](https://github.com/hyprwm/Hyprland/assets/43317083/e19417c3-d90f-41ba-9d7c-85547a3a1f31)

**Comment by awarewen** [comment]
> for kitty, you need to set `GLFW_IM_MODULE` to `ibus` regardless of the IME being used, seems to work for me, also on fcitx
> 
> ![image](https://user-images.githubusercontent.com/43317083/240682326-e19417c3-d90f-41ba-9d7c-85547a3a1f31.png)


Sure enough, I was the only one who had a strange problem here, and my friends said that their use was normal there
enm, i setting it, But the strange thing is that it doesn't pop up the candidate box for the input method correctly, it seems that only I have encountered this situation.

I'm going to report this now and ask for help.
