### ISSUE TITLE
Disabling internal laptop monitor makes Hyprland crash

### ISSUE THREAD

**Issue by kooskaspers** [hyprwm/Hyprland#2356]
When I disable the internal monitor eDP-1 (`hyprctl keyword monitor "eDP-1,disable"`), Hyprland crashes. See attachments for crashreport and configuration file. Disabling an external monitor is working fine (`hyprctl keyword monitor "DP-1,disable"`)

```
hyprctl monitors

Monitor eDP-1 (ID 0):
	1920x1080@59.990002 at 0x0
	description: Apple Computer Inc Color LCD (eDP-1)
	make: Apple Computer Inc
	model: Color LCD
	serial: 
	active workspace: 1 (1)
	reserved: 0 25 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-1 (ID 1):
	2560x1440@59.951000 at 7040x0
	description: Apple Computer Inc Thunderbolt C02L50FQF2GC (DP-1)
	make: Apple Computer Inc
	model: Thunderbolt
	serial: C02L50FQF2GC
	active workspace: 2 (2)
	reserved: 0 25 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 2):
	2560x1440@59.951000 at 4480x0
	description: Apple Computer Inc Thunderbolt C02MV3ABF2GC (DP-2)
	make: Apple Computer Inc
	model: Thunderbolt
	serial: C02MV3ABF2GC
	active workspace: 3 (3)
	reserved: 0 25 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
```

[hyprlandCrashReport26772.txt](https://github.com/hyprwm/Hyprland/files/11557322/hyprlandCrashReport26772.txt)
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11557331/hyprland.conf.txt)

**Comment by irdaislakhuafa** [comment]
Here is my hyprland configuration to manage multi monitors, and I have the same problem with you but now it has been solved, maybe this will help,
https://github.com/irdaislakhuafa/hypr/blob/797a526e90ffe6bf44e7aa7cd7fdd1652561724d/configs/submap.conf#L123

**Comment by irdaislakhuafa** [comment]
my primary monitor is eDP-1

**Comment by kooskaspers** [comment]
Thanks @irdaislakhuafa. I tried your bind, and changed it slightly to my setup:
`exec, hyprctl --batch 'keyword monitor HDMI-A-1,highres,1920x0,1;' && sleep 1 && hyprctl --batch 'keyword monitor eDP-1,disable'`
but again it's crashing Hyprland :(

**Comment by kooskaspers** [comment]
Can be closed. I wasn't on the latest git commit. It's fixed.

**Comment by irdaislakhuafa** [comment]
> 

it looks like you made a typo in writing `auto` to `audo`

**Comment by dkirchhof** [comment]
I'm struggling with a usefull setup for a multi monitor system.
Most important: If I plug off an external monitor I want to switch to the internal display (using a notebook).
I also have a submap for it. But the submap doesn't work if the config is set to "external only" and the monitor is plugged off.
If I use the keybind before plugging off, it will work...

Did you have the same experience?
