### ISSUE TITLE
Touch Input ignores LayerSurfaces if monitor not at 0x0 coordinates

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#2357]
Explanation: if the touchscreen's panel's coordinates aren't exactly 0x0, you won't be able to interact with any LayerSurfaces, such as EWW, Waybar, Rofi, ecc. 

Tested with/without external monitor attached, same result. 

Having two displays with touchscreen capabilities might seem like a very rare user case (and it is), but if you're like me and have a touchscreen laptop that you put below your external monitor then you'll find that this issue is a pain in the a*s

**Comment by vaxerski** [comment]
should be fixed in a2bb95fc60c717c873eff273f5ee035e622565d0

**Comment by Estebiu** [comment]
Unfortunately that didn't fix it.

**Comment by Estebiu** [comment]
Somehow now it's fixed; don't know when it happened or why, but thanks.
I'm gonna close this issue.
