### ISSUE TITLE
[Foot/Alacritty] window swallowing has no effect?

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#2361]
# Issue
`misc:enable_swallow=true` doesn't hide the terminal after running `$ lutris` with [Foot](https://codeberg.org/dnkl/foot) as well as [Alacritty](https://github.com/alacritty/alacritty)

# System
Distro: CachyOS (Arch)
Hyprland: `v0.25.0-29-g896a78aa`

**Comment by smsteward** [comment]
Do you have a `swallow_regex` set? The `enable_swallow=true` variable just enables the feature: you need to define a regex for the class of windows you want swallowed. You'll probably want to add something like `swallow_regex=^(alacritty)$` or `swallow_regex=^(foot)$` to your config.

Relevant wiki link: https://wiki.hyprland.org/Configuring/Variables/#misc

**Comment by GrabbenD** [comment]
Thank you it works as intended now @smsteward!
I wasn't paying attention and didn't notice `swallow_regex` and the description of `enable_swallow` didn't mention it
```
misc {
    enable_swallow = 1
    swallow_regex=^(foot)$
}
```

**Comment by smsteward** [comment]
Awesome! Glad it helped.

Can we go ahead and close this issue?

**Comment by vaxerski** [comment]
we can
