### ISSUE TITLE
Tablet doesn't make the cursor appear with `cursor_inactive_timeout`

### ISSUE THREAD

**Issue by jakubkaczor** [hyprwm/Hyprland#2362]
*Steps to reproduce*.
1. Have `cursor_inactive_timeout` set to a positive value.
2. Wait until the cursor disappears.
3. Touch the tablet with a pen.

*The expected outcome* is that touching the tablet with a pen makes the cursor appear, just like using the mouse would.

*The noted outcome* is the cursor does not appear.

*Additional information*. I have a graphics tablet like [this one](https://www.huion.com/products/pen_tablet/Inspiroy/H950P.html). That is, it doesn't have a screen, but touching it with a pen is mapped to an output display.

**Comment by arlohb** [comment]
It might be different for me as I'm using a laptop with a touchscreen and pen instead of a graphics tablet.
But isn't this a duplicate of #2333, which was fixed in commit 5627b70.

If so, this issue can be closed.

**Comment by jakubkaczor** [comment]
You are correct. Thank you for pointing this. There was a 5-day difference between the creation date of the two issues and I tested on the latest release, so I didn't notice the fix. As some time has passed, I can't remember why I didn't find the issue you mentioned.
