### ISSUE TITLE
Python program can't resize window in Hyprland

### ISSUE THREAD

**Issue by d-rot** [hyprwm/Hyprland#2365]
I use Hyprland tiling window manager and I am writing a GUI application in Python using tkinter. When I want to set the window size, nothing happens: 

```
import tkinter as tk

root = tk.Tk()
root.geometry("300x300")
root.attributes('-type', 'dialog')

root.mainloop()
```

If I add one line _root.overrideredirect(True)_ I am able to set the size, but then other things like text fields or binds don't work. This disables the resize lock, but also throws away half of the window's functionality. How can I disable this lock in a different way?

**Comment by vaxerski** [comment]
wayland apps are generally not allowed to resize themselves, see #271

**Comment by d-rot** [comment]
I used the wrong word. I don't resize the window. I can't even set the default size. _root.geometry("widthxheight")_ should do it, but it doesn't. I know it can be disabled because _overrideredirect(True) _ disables it.

**Comment by vaxerski** [comment]
override_redirect is an X11 term. It does not exist in Wayland. Are you sure your library supports wayland?

**Comment by vaxerski** [comment]
See https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_max_size

`set_max_size` and `set_min_size` can be used in tandem to make a window some specific size.
