### ISSUE TITLE
Random crash when opening steam game: Unable to reproduce

### ISSUE THREAD

**Issue by crazyminecuber** [hyprwm/Hyprland#2366]
I had a random crash sometime last week after running hyprland for a few hours. Occurred when opening an old steam game (Cars). Don't know if this is of any use since I have been unable to reproduce it, so feel free to close, but the crash log might highlight some bug.

The log is shortened since it basically contained my web history. Startup and before it crashed is still in the log.

[hyprlandCrashReport1993.txt](https://github.com/hyprwm/Hyprland/files/11576742/hyprlandCrashReport1993.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/11576743/hyprland.log)

**Comment by vaxerski** [comment]
has it resurfaced since?

**Comment by crazyminecuber** [comment]
No and I and no longer using hyprland so feel free to close. I have gone back to the dark side and I am now using Gnome :)
