### ISSUE TITLE
Window rule doesn't allow `workspace empty` to open in empty workspace

### ISSUE THREAD

**Issue by foonathan** [hyprwm/Hyprland#2368]
I have the following rule:

```
windowrule=workspace empty silent,^firefox$
```

What I expect to happen: every firefox window opens in a new workspace.

What actually happens: I get an error message in the log

```
[ERR] Invalid workspace requested in workspace silent rule!
```

**Comment by BowlBird** [comment]
Same problem. 
```
windowrule=workspace empty, title:Sharing indicator
```
successfully puts the workspace on a empty workspace, but
```
windowrule=workspace empty silent, title:Sharing Indicator
```
causes the error
xdg-desktop-portal-hyprland[53792]: sh: line 1: workspace: command not found
in journalctl

**Comment by MightyPlaza** [comment]
@vaxerski
