### ISSUE TITLE
Stuttering frames

### ISSUE THREAD

**Issue by kurpingspace2** [hyprwm/Hyprland#2369]
hi there, i'm completely new to this wayland stuff. i have an issue with the frames stuttering on some programs. gaming seems to work perfectly from what i've tested but other applications such as reaper, chrome, discord act very strange.

https://drive.google.com/file/d/1foC8GGKnDunzdEuaqLVFfXAL97r_MZ2t/view?usp=sharing

Here is another video of the same application, but running as fullscreen. Different behaviour.
https://drive.google.com/file/d/1fqVLO9LyfD_7Ia_AoOrXQdG7oxQvcxQB/view?usp=share_link

If it helps:
Kernel: 6.3.4-arch1-1 
CPU: AMD Ryzen 7 5700X (16)  
GPU: NVIDIA GeForce RTX 3060

Resolution: 2560x1440
Refresh rate: 60

Default environment names: (.config/hypr/hyprland.conf)
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

**Comment by vaxerski** [comment]
looks like normal nvidia to me

try commenting out `env = GBM_BACKEND,nvidia-drm` too, AFAIK it's redundant now and causes issues? I don't use nvidia though.

Generally nvidia is not supported, so I can't help you here, but you can ask around on the discord server, maybe someone knows.

**Comment by kurpingspace2** [comment]
Commenting it out has no difference. i'll try to find an answer in the discord, then.
