### ISSUE TITLE
Show desktop/hide-unhide windows

### ISSUE THREAD

**Issue by Harith163** [hyprwm/Hyprland#2381]
Hi!

I think it would be neat if there was a way to hide all the active windows on a workspace and show just the desktop (possibly while a key is being held) and then bring the windows back(once the key press is released).

The use case i'm imagining is to have a eww dashboard instead of a status bar like waybar or hybrid just hanging around on the bottom layer which i could just quickly check for the time/application launch and then go back to work.

Thank you!

**Comment by vaxerski** [comment]
you can make a script to set all windows' opacity prop to 0...?

![image](https://github.com/hyprwm/Hyprland/assets/43317083/ff89731c-8178-4c36-8ca9-4ef696479def)

`hyprctl setprop address:0x55a8e6570cd0 alpha 0.1 lock && hyprctl setprop address:0x55a8e6570cd0 alphainactive 0.1 lock`

Setting them to 1.0 afterwards will remove the lock

Don't think this should be in the core repo

**Comment by eliotOrderson** [comment]
## You can use my hide_unhide_window.sh script

1. add the script to you script dir
```bash
stack_file="/tmp/hide_window_pid_stack.txt"


function hide_window(){
	pid=$(hyprctl activewindow -j | jq '.pid')
	hyprctl dispatch movetoworkspacesilent 88,pid:$pid
	echo $pid >> $stack_file
}

function show_window(){
	pid=$(tail -1 $stack_file && sed -i '$d' $stack_file)
	[ -z $pid ] && exit

	current_workspace=$(hyprctl activeworkspace -j | jq '.id')	
	hyprctl dispatch movetoworkspacesilent $current_workspace,pid:$pid
}


if [ ! -z $1 ]
then
	if [ "$1" == "h" ]
	then
		hide_window >> /dev/null
	else
		show_window >> /dev/null
	fi
fi

```
2. add shortcut to hyprland.conf or keybindings.conf
 ```bash
# hide active window
bind = $mainMod,H,exec,you script path/hide_unhide_window.sh h
# show last  hide window in stack
bind = $mainMod,I,exec,you script path/hide_unhide_window.sh s
 ```

**Comment by karamanliev** [comment]
If someone else lands here, here's a simpler approach:
```
#!/bin/sh
get_opacity() {
  hyprctl getoption decoration:$1 | awk 'NR==1{print $2}'
}

set_opacity() {
  hyprctl --batch "\
    keyword decoration:active_opacity $1;\
    keyword decoration:inactive_opacity $1"
  exit
}

if [ "$(get_opacity active_opacity)" = "1.000000" ] && [ "$(get_opacity inactive_opacity)" = "1.000000" ]; then
  set_opacity 0
else
  set_opacity 1
fi
```

**Comment by brianferri** [comment]
> If someone else lands here, here's a simpler approach:
> 
> ```shell
> #!/bin/sh
> get_opacity() {
>   hyprctl getoption decoration:$1 | awk 'NR==1{print $2}'
> }
> 
> set_opacity() {
>   hyprctl --batch "\
>     keyword decoration:active_opacity $1;\
>     keyword decoration:inactive_opacity $1"
>   exit
> }
> 
> if [ "$(get_opacity active_opacity)" = "1.000000" ] && [ "$(get_opacity inactive_opacity)" = "1.000000" ]; then
>   set_opacity 0
> else
>   set_opacity 1
> fi
> ```
> 
> ```shell
> bind = , F11, exec, toggle_show_desktop.sh
> ```

Maybe unnecessary but I'll also leave this here;

I've made a version which also considers blur:
```sh
#!/bin/sh

get_option() {
  hyprctl getoption decoration:"$1" | awk 'NR==1{print $2}'
}

set_option() {
  hyprctl --batch "\
    keyword decoration:active_opacity $1;\
    keyword decoration:inactive_opacity $1"
  exit
}

toggle_blur() {
  hyprctl "keyword decoration:blur:enabled $1"
}

active_opacity=$(get_option active_opacity)
inactive_opacity=$(get_option inactive_opacity)
blur_enabled=$(hyprctl getoption decoration:blur:enabled | awk 'NR==2{print $2}')

if [ "$active_opacity" = "1.000000" ] && [ "$inactive_opacity" = "1.000000" ]; then
  [ "$blur_enabled" = "true" ] && toggle_blur no
  set_option 0
else
  [ "$blur_enabled" = "true" ] && toggle_blur yes
  set_option 1
fi
```

**Comment by UtsavBalar1231** [comment]
> > If someone else lands here, here's a simpler approach:
> > ```shell
> > #!/bin/sh
> > get_opacity() {
> >   hyprctl getoption decoration:$1 | awk 'NR==1{print $2}'
> > }
> > 
> > set_opacity() {
> >   hyprctl --batch "\
> >     keyword decoration:active_opacity $1;\
> >     keyword decoration:inactive_opacity $1"
> >   exit
> > }
> > 
> > if [ "$(get_opacity active_opacity)" = "1.000000" ] && [ "$(get_opacity inactive_opacity)" = "1.000000" ]; then
> >   set_opacity 0
> > else
> >   set_opacity 1
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > bind = , F11, exec, toggle_show_desktop.sh
> > ```
> 
> Maybe unnecessary but I'll also leave this here;
> 
> I've made a version which also considers blur:
> 
> ```shell
> #!/bin/sh
> 
> get_option() {
>   hyprctl getoption decoration:"$1" | awk 'NR==1{print $2}'
> }
> 
> set_option() {
>   hyprctl --batch "\
>     keyword decoration:active_opacity $1;\
>     keyword decoration:inactive_opacity $1"
>   exit
> }
> 
> toggle_blur() {
>   hyprctl "keyword decoration:blur:enabled $1"
> }
> 
> active_opacity=$(get_option active_opacity)
> inactive_opacity=$(get_option inactive_opacity)
> blur_enabled=$(hyprctl getoption decoration:blur:enabled | awk 'NR==2{print $2}')
> 
> if [ "$active_opacity" = "1.000000" ] && [ "$inactive_opacity" = "1.000000" ]; then
>   [ "$blur_enabled" = "true" ] && toggle_blur no
>   set_option 0
> else
>   [ "$blur_enabled" = "true" ] && toggle_blur yes
>   set_option 1
> fi
> ```

This is nice, almost works with most of the applications, but it does not work with my browser (zen). Is that due to xwayland ?

**Comment by Floperatok** [comment]
> Maybe unnecessary but I'll also leave this here;
> 
> I've made a version which also considers blur:
> 
> 
>```
> #!/bin/sh
> 
> get_option() {
>   hyprctl getoption decoration:"$1" | awk 'NR==1{print $2}'
> }
> 
> set_option() {
>   hyprctl --batch "\
>     keyword decoration:active_opacity $1;\
>     keyword decoration:inactive_opacity $1"
>   exit
> }
> 
> toggle_blur() {
>   hyprctl "keyword decoration:blur:enabled $1"
> }
> 
> active_opacity=$(get_option active_opacity)
> inactive_opacity=$(get_option inactive_opacity)
> blur_enabled=$(hyprctl getoption decoration:blur:enabled | awk 'NR==2{print $2}')
> 
> if [ "$active_opacity" = "1.000000" ] && [ "$inactive_opacity" = "1.000000" ]; then
>   [ "$blur_enabled" = "true" ] && toggle_blur no
>   set_option 0
> else
>   [ "$blur_enabled" = "true" ] && toggle_blur yes
>   set_option 1
> fi

Made some simplifications and added support for active_opacity and inactive_opacity values other than 1.00.

```sh
#!/bin/sh

get_option() {
  hyprctl getoption decoration:"$1" | awk 'NR==1{print $2}'
}

set_option() {
  hyprctl --batch "\
    keyword decoration:active_opacity $1;\
    keyword decoration:inactive_opacity $2"
  exit
}

toggle_blur() {
  hyprctl "keyword decoration:blur:enabled $1"
}

if [ $(get_option active_opacity) = "0.000000" ]; then
  toggle_blur yes
  hyprctl reload
else
  toggle_blur no
  set_option 0 0
fi
```

**Comment by ides-dev** [comment]
> Made some simplifications and added support for active_opacity and inactive_opacity values other than 1.00.
> ```sh
> #!/bin/sh
> 
> get_option() {
>   hyprctl getoption decoration:"$1" | awk 'NR==1{print $2}'
> }
> 
> set_option() {
>   hyprctl --batch "\
>     keyword decoration:active_opacity $1;\
>     keyword decoration:inactive_opacity $2"
>   exit
> }
> 
> toggle_blur() {
>   hyprctl "keyword decoration:blur:enabled $1"
> }
> 
> if [ $(get_option active_opacity) = "0.000000" ]; then
>   toggle_blur yes
>   hyprctl reload
> else
>   toggle_blur no
>   set_option 0 0
> fi
> ```
doesn't work for me because requires to use eval, so i updated it to lua :)
```sh
#!/bin/sh

get_option() {
  hyprctl getoption decoration:$1 | awk 'NR==1{print $2}'
}

if [ $(get_option active_opacity) = "0.000000" ]; then
  hyprctl reload
else
  hyprctl eval " \
  hl.config({ \
    decoration = { active_opacity = 0, inactive_opacity = 0, blur = { enabled = false } } \
  })"
fi
```
