### ISSUE TITLE
`dispatch focusmonitor <monitor_name>` doesn't focus on the displayed special workspace of the target monitor

### ISSUE THREAD

**Issue by 15cm** [hyprwm/Hyprland#2391]
Steps:
* Have two monitors called DP-1 and DP-2
* Move a window to the special workspace (-99) and then `togglespecialworkspace` to have the special workspace displayed on DP-1
* `hyprctl dispatch focusmonitor DP-2`
* `hyprctl dispatch focusmonitor DP-1`

Expected result: The window of the special workspace on DP-1 is focused for both mouse and keyboard.

Actual result: The window of the previous non-special workspace on DP-1 is focused for both mouse and keyboard.

Note: I have `input.follow_mouse = 2` to separate the focus of mouse and keyboard.

**Comment by vaxerski** [comment]
fixed in a7cfbdb8546831247a232f96a37c2c6589f01391

**Comment by 15cm** [comment]
I verified the fix in `v0.26.0`. Thank you for the quick fix!
