### ISSUE TITLE
Discord and steam not opening after closing window, Tool bar in gimp, nemo dont open after opening and closing.

### ISSUE THREAD

**Issue by MaskinBaba** [hyprwm/Hyprland#2393]
Whenever i launches discord or steam when i closes its window to manage workspace and let it run in the background. The app window cant be relaunched and needs to kill the app/exit and relaunch it.

Even Tool bar of gimp and nemo are not working so editing images are a pain now. Tool bar of steam is not even accessible.

**Comment by vaxerski** [comment]
can't repro either.

**Comment by MaskinBaba** [comment]
Im using arch linux with linux lts kernel. And have the latest hyprland github version and facing this issue.
On ROG G15 R7 4800H and RTX 3050Ti.

**Comment by MaskinBaba** [comment]
Nevermind, i was using old AUR version of hyprland which had this bug.
Just compiled the new version.
And sorry for late update on the issue
