### ISSUE TITLE
movefocus broken.

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#2396]
Since a few commits movefocus doesn't work anymore for me. 
Sometimes it's possible to use it once, after that there is no effect at all for any direction.

**Comment by Dickby** [comment]
It's caused by `no_cursor_warps=1`. Or at least everything works fine without that line in my config.

**Comment by burghoffdavid** [comment]
Had the same issue, setting `no_cursor_warps=false` fixed it as well, thanks @Dickby!

I think this is a regression, didn't have that issue on the last version (` 0.25.0`)

**Comment by ymnejmi** [comment]
Facing the same problem here, potentially also `cyclenext`, but it's more reliably replicable with `movefocus`, it seems like the cursor is focusing even without moving and `no_cursor_warps` set to true gives it a case to manifest.
