### ISSUE TITLE
Some apps not launching

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#240]
similar to #216 , I am having trouble with vivaldi not launching. It's not only vivaldi, though. A whole bunch of apps won't launch including discord youtube music. All with error:` libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
I am sorry if it is techincally a duplicate of #216 , I wasn't sure

**Comment by EysseW** [comment]
So far I've stumbled across: [Discord](https://aur.archlinux.org/packages/discord_arch_electron), [Discord Canary](https://aur.archlinux.org/packages/discord-canary-electron-bin), [Guilded](https://aur.archlinux.org/packages/guilded), Vivaldi, [Youtube Music](https://aur.archlinux.org/packages/youtube-music), [Minecraft Launcher](https://aur.archlinux.org/packages/minecraft-launcher).

What I found interesting is that [Discord PTB](https://aur.archlinux.org/packages/discord-ptb) did work. Also [Youtube Music Desktop](https://aur.archlinux.org/packages/youtube-music-desktop) worked well. 

What exactly is ozone wayland?

**Comment by vaxerski** [comment]
What exactly is ozone wayland?

a flag for electron (and chromium) to use native wayland mode and not xwayland

**Comment by taylor85345** [comment]
Are you on an Nvidia system? I think those are all electron apps except maybe minecraft-launcher, and I get those errors with virtually all electron apps running in xwayland on my Nvidia system. As vaxry suggested, enabling ozone is the solution for most electron applications:

`vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland`

swapping out vivaldi with your electron application of choice. 

Discord is one noteable exception, as their version of electron is too old and  doesn't have ozone support. On arch, the `discord_arch_electron_wayland` AUR package provides a patched version of discord with ozone support.

**Comment by Th3Whit3Wolf** [comment]
I've had issues running vscode on Arch in hyperland.

**Comment by taylor85345** [comment]
I believe vscode also uses electron and may also benefit from using the ozone backend

**Comment by Th3Whit3Wolf** [comment]
@taylor85345 it is electron but does not recognize ozone

**Comment by mrshmllow** [comment]
Also element

**Comment by EysseW** [comment]
I am not using Nvidia drivers and indeed, the ozone flag "fixed" it. I say "fixed" because the programs I run with the ozone flag are very buggy and are responding slowly. Even the minecraft launcher is running with the flag.

**Comment by vaxerski** [comment]
> I am not using Nvidia drivers and indeed, the ozone flag "fixed" it. I say "fixed" because the programs I run with the ozone flag are very buggy and are responding slowly. Even the minecraft launcher is running with the flag.

yes that is a known issue.

**Comment by PixelNova2012** [comment]
Wait how would I use Discord on Fedora? I am using Fedora Workstation 41 with ML4W dotfiles and I can't open Discord. Someone said if you are using Arch do this command (they put a command here) but what if you aren't using Arch? I do have an NVIDIA GPU by the way

**Comment by PixelNova2012** [comment]
Thanks. I saw that someone else said Discord is a notable exception to that flag, and they said to use a specific command on Arch, so I wasn't sure. I ended up going with a Discord client and just installed GoofyCord.

**Comment by Rusty-Jean** [comment]
# hey there

I think [facebook](www.facebook.com) i don't know....
