### ISSUE TITLE
1 pixel gaps on no-gap settings

### ISSUE THREAD

**Issue by bbyeen** [hyprwm/Hyprland#2402]
![photo_2023-05-31_00-49-02](https://github.com/hyprwm/Hyprland/assets/80675742/2853ca88-0d5a-410d-8799-cd29bcb37f2e)

    Steps to reproduce
gaps_in = 0
gaps_out = 0
border_size = 1
master layout 

    Expected outcome
no gaps between windows

    Noted outcome
1px gap
it doesn't matter if i change window size

**Comment by System-x64** [comment]
That 1 px is reserved for your border, to have absolutely no gap, set `border_size = 0`

**Comment by bbyeen** [comment]
It's not the border problem i guess. It really is noticeable with multiple windows
![photo_2023-05-31_11-48-37](https://github.com/hyprwm/Hyprland/assets/80675742/da52ca18-ac77-4aae-bdb3-be019a9378b5)

**Comment by System-x64** [comment]
yes, each and every window is required to leave the required space for the border, this is not a bug, without it, the border of one app would simply overlap another application. Again, set your `border_size` to 0, to not allocate any space for possible borders.

**Comment by romanstingler** [comment]
@bbyeen does `border_size=0` fix your issue?
