### ISSUE TITLE
activewindowv2

### ISSUE THREAD

**Issue by x140x1n** [hyprwm/Hyprland#2405]
Is there a reason for the window address  being separated from the activewindow event and placed inside activewindowv2 event?
Would be great if the window address could be added to the activewindow event,

Thanks.

**Comment by vaxerski** [comment]
yes.

regards

**Comment by x140x1n** [comment]
Would you mind telling what the reason is? I couldn't figure it out.

**Comment by vaxerski** [comment]
backwards compatibility with the times there was no v2 event
