### ISSUE TITLE
window group are not working as expected

### ISSUE THREAD

**Issue by Ultrahalf** [hyprwm/Hyprland#2406]
I'm also using hyprsome and pypyland scratchpad just in case this information was needed
Hyprland verison
```
hyprctl version
Hyprland, built from branch  at commit 51a930f802c71a0e67f05e7b176ded74e8e95f87 dirty ().
Tag: v0.26.0

flags: (if any)
```
config related to the issue
```
bind = $mainMod,t, togglegroup
bind = $mainMod,c, moveoutofgroup
bind = $mainMod,x, changegroupactive, f
bind = $mainMod,z, changegroupactive, b

misc {
    #render_titles_in_groupbar	= true
    #groupbar_titles_font_size	 = 20
    #groupbar_text_color
}

```
using master layout

## Steps to reproduce

1. toggle group for current window using `mod``t` => toggles group
2. open another window in the group `mod``space` in my case for terminal => opens terminal in the tab
3. press `mod``t`
both the windows turn into none group.

### another case 2
1. toggle group for current window using `mod``t` => toggles group
2. open another window in the group `mod``space` in my case for terminal => opens terminal in the tab
3.  repeat step 2
3. press `mod``t` (togglegroup)
all three the windows turn into none group.

### another case 3
1. toggle group for current window using `mod``t` => toggles group
2. open another window in the group `mod``space` in my case for terminal => opens terminal in the tab
3.  repeat step 2
3. press `mod``c` (moveoutofgroup)
window in focus moves to master view but focus remains in slave i.e tab group. 
on a side note:  master even though not part of group has a weird gap between the bar. when I try to take screenshot it expands and fixs :) its not a issue but hey ux would be better.
---

## Expected outcome
case1,2:
when a active window is toggled out of a group.
[ ] It should moved to master view
[ ] other windows of the group should be part of windowgroup

case 3:
when a window is moved out of the group.
[x]  it should be in master view
[ ] focus should be on master window as its expected window
[ ] shouldn't have weird gap between bar

---

lmk if i'm doing something fishy it was working somewhat correctly but I didn't have the bar last time. which wasn't a problem. now groupbar is fixed

**Comment by Ultrahalf** [comment]
another issue
i can see is groupbar not disappearing even after windows are closed
as soon as new normal window is open it gets fixed.

ig its not redrawn?

**Comment by MightyPlaza** [comment]
Can you send some demonstrations, I can't reproduce any of the 3 issues

**Comment by Ultrahalf** [comment]
Ya you guys can close the issue if you want
I learnt to live with whatever feature is available at this point :)
