### ISSUE TITLE
Hyprland crashes when trying to capture the screen with Pipewire

### ISSUE THREAD

**Issue by uku3lig** [hyprwm/Hyprland#2407]
When opening OBS, the screen picker appears, and when clicking one of the options, Hyprland (hyprland-git e76bd43) crashes.

Steps to reproduce:
- Open OBS
- Add a Screen Capture (Pipewire)
- Select a monitor 

[hyprland_152577.log](https://github.com/hyprwm/Hyprland/files/11619319/hyprland_152577.log)
[coredump_152577.txt](https://github.com/hyprwm/Hyprland/files/11619320/coredump_152577.txt)
[hyprlandCrashReport152577.txt](https://github.com/hyprwm/Hyprland/files/11619322/hyprlandCrashReport152577.txt)
[config](https://github.com/uku3lig/dotfiles/blob/master/.config/hypr/hyprland.conf)

**Comment by David-Aguilo** [comment]
I think it isn't only with OBS, as I also got a crass when attempting to share a screen in firefox through pipewire. Here is my log to provide extra info.

[hyprlandCrashReport837.txt](https://github.com/hyprwm/Hyprland/files/11624339/hyprlandCrashReport837.txt)

Also this issue happened for me in the git version but not in v0.26.0. So it must be a recent change that is causing this.

**Comment by NotAShelf** [comment]
Can reproduce this with Zoom, discord and Firefox.


Has practically nothing, but crash log:
[hyprlandCrashReport2174.txt](https://github.com/hyprwm/Hyprland/files/11624753/hyprlandCrashReport2174.txt)

**Comment by dtop129** [comment]
I have the same issue, the commit that for me caused the issue is the recent wlroots update b540d28
[hyprlandCrashReport8375.txt](https://github.com/hyprwm/Hyprland/files/11634959/hyprlandCrashReport8375.txt)

**Comment by David-Aguilo** [comment]
I am able to capture the screen again with today's new commits. I suppose it was commit 6ba8310c136e775683703196d62444dab430cf45 was the one that fixed it. Has the issue also been resolved for you guys?

**Comment by NotAShelf** [comment]
Seems to be resolved for me as well.

**Comment by uku3lig** [comment]
The issue seems to be fixed, closing
