### ISSUE TITLE
Hyprland Crash after closing Rofi or Wofi 

### ISSUE THREAD

**Issue by yurihikari** [hyprwm/Hyprland#2410]
I updated my package to the latest hyprland-git version (hyprland-git-r2953.e76bd43f-1), and it instantly crashes. I'm new to Hyprland so I don't really have any idea for why it does, but i can at least consistently reproduce that bug : 

How to reproduce :

1. Update hyprland-git (hyprland-git-r2953.e76bd43f-1)
2. Reboot or Relog to the Hyprland Session
3. Open wofi or Rofi (using rofi/wofi -show drun)
4. Escape from Rofi/Wofi 
5. Crash and back to Greetd screen

Crash log files :
[hyprlandCrashReport18078.txt](https://github.com/hyprwm/Hyprland/files/11623997/hyprlandCrashReport18078.txt)
[hyprlandCrashReport17091.txt](https://github.com/hyprwm/Hyprland/files/11623998/hyprlandCrashReport17091.txt)
[hyprlandCrashReport16399.txt](https://github.com/hyprwm/Hyprland/files/11624000/hyprlandCrashReport16399.txt)
[hyprlandCrashReport15537.txt](https://github.com/hyprwm/Hyprland/files/11624001/hyprlandCrashReport15537.txt)
[hyprlandCrashReport15144.txt](https://github.com/hyprwm/Hyprland/files/11624002/hyprlandCrashReport15144.txt)
[hyprlandCrashReport1052.txt](https://github.com/hyprwm/Hyprland/files/11624003/hyprlandCrashReport1052.txt)

System Specs :
OS : Garuda Linux
CPU : Intel Core i5 12500H
GPU 1 : Intel Alder Lake-P Integrated Graphics
GPU 2 : RTX 2050 (disabled)
Laptop Model : Honor MagicBook 14 2022

**Comment by JulesTanguy** [comment]
I had a similar issue with fuzzel (as soon as I launch a program with it) since the wlroots update b540d28849c1691236ee8b0572f6a694b82dbbbf

The temporary fix that works for me is to rollback the wlroots git submodule to the previous version.

**Comment by vaxerski** [comment]
#2404
