### ISSUE TITLE
Freeze after suspending

### ISSUE THREAD

**Issue by hok7z** [hyprwm/Hyprland#2411]
Hi, everyone! After suspend the laptop freezes.

I tried to install various DE(including X11 DE's) and kernels, but it didn't help.

Specifications
- Laptop: Asus VivoBook 15(K3500)
- OC: Arch Linux x86_64
- Kernel: 6.1.30-1-lts
- DE: Hyprland(XWayland) and tried Sway
- BIOS Version: 302
- GPU: Intel Iris XE Graphics(USED)

glxinfo|grep -E "OpenGL vendor|OpenGL renderer"
> OpenGL vendor string: Intel
> OpenGL renderer string: Mesa Intel(R) Xe Graphics (TGL GT2)

- GPU: Nvidia RTX 3050 Mobile

Hyprland logs: http://0x0.st/HbS1.log
dmesg logs: http://0x0.st/HbSj.log

**Comment by UTFeight** [comment]
I am having a similar issue:
- When I open a new application or do some action (like quiting Vim) my whole system freezes! 
> **Note** The audio works even after the system is frozen

**Comment by UTFeight** [comment]
One of the people on Hypr Developers Discord Server suggested:
- installing `hyprland-nvidia` and `xdg-desktop-portal-hyprland`

**Comment by UTFeight** [comment]
I have fixed my issue by using one of my timeshift backups.

It's important to backup data because it make whole lot easier to solve such problems effortlessly.

**Comment by hok7z** [comment]
I found a reason for the crash. After suspending the WiFi driver mt7921, it crashes. If I disable the driver using the command: modprobe -r mt7921, then everything works fine. I will replace the Mediatek WiFi adapter with Intel. 

**dmesg log**
```
[    6.207888] mt7921e MAC enabling device (0000 -> 0002)
[    6.226755] mt7921e MAC ASIC revision: 79610010
[    6.311903] mt7921e MAC HW/SW Version: 0x8a108a10, Build Time: 20230302150916a
[    6.617946] mt7921e MAC WM Firmware Version: ____010000, Build Time: 20230302150956
[    7.507708] mt7921e MAC wlo1: renamed from wlan0
[   35.206435] mt7921e MAC Unable to change power state from D3cold to D0, device inaccessible
[   36.403869] mt7921e MAC driver own failed
[   36.405498] mt7921e: probe of MAC failed with error -5
```
