### ISSUE TITLE
Client monitor value on the special workspace does not change

### ISSUE THREAD

**Issue by nwg-piotr** [hyprwm/Hyprland#2413]
Hi,

Actually I'm not sure whether it's a bug or a feature.

Starting from v0.26.0, `togglespecialworkspace` will show the special workspace on the currently focused monitor. However, for clients on the special workspace, the client `monitor` value remains always the same, equal to the `id` of the monitor the client was moved to the special workspace on. Is it intentional, or could it be fixed?

**Comment by vaxerski** [comment]
should be fixed with 871ab24c6e9d2fb6e48cbf990ddddf0c46a950af but lmk as I cant test cuz am on holiday

**Comment by nwg-piotr** [comment]
No hurry. I got my module to work anyway. Have fun!

**Comment by nwg-piotr** [comment]
Seems to work to some degree. If I `togglespecialworkspace` to hide it on one monitor, and then again to show it on another, the `monitor` value changes. However, if I move the mouse pointer to another monitor, and `togglespecialworkspace`, the special workspace shows up on the second monitor, but the `monitor` value remains unchanged.

**Comment by MightyPlaza** [comment]
I think I accidentally fixed this in https://github.com/hyprwm/Hyprland/pull/3163

**Comment by MightyPlaza** [comment]
should be fixed now
