### ISSUE TITLE
Crashing when closing apps

### ISSUE THREAD

**Issue by patrulhasirius** [hyprwm/Hyprland#2414]
Note: I'm using the Hyprland-nvidia-git package from the AUR

Steps to reproduce: Close any window (tested with alacritty, firefox and mpv)

Expected outcome: Closing the window

Noted outcome: hyprland crash and logout to SDDM

I could not adquire the hyprland log as the crash logs me out.

Crash reports:

[hyprlandCrashReport8965.txt](https://github.com/hyprwm/Hyprland/files/11631102/hyprlandCrashReport8965.txt)
[hyprlandCrashReport4982.txt](https://github.com/hyprwm/Hyprland/files/11631103/hyprlandCrashReport4982.txt)
[hyprlandCrashReport2382.txt](https://github.com/hyprwm/Hyprland/files/11631104/hyprlandCrashReport2382.txt)
[hyprlandCrashReport56195.txt](https://github.com/hyprwm/Hyprland/files/11631105/hyprlandCrashReport56195.txt)
[hyprlandCrashReport54019.txt](https://github.com/hyprwm/Hyprland/files/11631106/hyprlandCrashReport54019.txt)
[hyprlandCrashReport50862.txt](https://github.com/hyprwm/Hyprland/files/11631107/hyprlandCrashReport50862.txt)
[hyprlandCrashReport46983.txt](https://github.com/hyprwm/Hyprland/files/11631108/hyprlandCrashReport46983.txt)
[hyprlandCrashReport2432.txt](https://github.com/hyprwm/Hyprland/files/11631109/hyprlandCrashReport2432.txt)

My config:

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/11631175/hyprland.conf.txt)

All of the relevant coredumps apear as "missing" on coredumpctl

The issue started after updating hyprland yesterday, updating hyprland today did not fix the issue, returning to a snapshot from before has fixed the issue.

**Comment by NutellaPlox** [comment]
This is also happening to me, but only happens after a few minutes of using hyprland. I am able to close apps right after launch.

@patrulhasirius Do you know what commit you reverted to?

**Comment by CardboardTurkey** [comment]
I've been having the same problem with rofi-wayland and sometimes alacritty and reverting to #5bfd5a9 also fixed it for me

**Comment by Jadefalke256** [comment]
Same issue here, also with rofi-wayland

**Comment by vaxerski** [comment]
#2404
