### ISSUE TITLE
Rofi and Wofi keeps crashing hyprland.

### ISSUE THREAD

**Issue by noisyy13** [hyprwm/Hyprland#2417]
Hi everyone, i try to used rofi and wofi app launcher, but suddenly every time I try to open any app, it keep crashing Hyprland to sddm login screen. I noticed that If i remove WLR_NO_HARDWARE_CURSORS,1 variable from env it is no longer crashing, but in this case Hypr is not showing my cursor. Anyone had similar problem?
Specs and logs in links
![oeB0TaR_d](https://github.com/hyprwm/Hyprland/assets/37442338/40fb12e9-d933-493d-9f4a-d778c50bb209)
https://hastebin.com/share/unitedexot.ruby

**Comment by vaxerski** [comment]
#2404
