### ISSUE TITLE
Fullscreen maximize prevents from clicking to bar (waybar)

### ISSUE THREAD

**Issue by kaedwen** [hyprwm/Hyprland#2418]
`Hyprland version 0.26.0 - 51a930f802c71a0e67f05e7b176ded74e8e95f87`

If I put a window to Fullscreen (maximize)
```
bind = $mainMod, F, fullscreen, 1
```
and I try to click on my bar (e.g. alt format for date) the click does not reach the bar.

Not sure if this is more waybar related, but my initial thought was that hyprland does overlay here.

**Comment by romanstingler** [comment]
do you have 

`"layer": "top"`
in your waybar config?

I use the official arch packages
waybar: 0.9.18-2 (testing)
hyprland: 0.26.0-1
and can't reproduce it.

Fyi some people reported that the git version is currently broken.

**Comment by kaedwen** [comment]
oh yes adding `"layer": "top"` in the waybar config does fix that issue :-) thank you
