### ISSUE TITLE
HEADS-UP - Regarding WLROOTS!

### ISSUE THREAD

**Issue by frkli1965** [hyprwm/Hyprland#2422]
Evening Vaxry,

Just to let you know that today's WLROOTS updates will break Hyprland.

I fully appreciate that there's no guarantee that the latest WLROOTS is supported but I thought I let you know in advance so that you're well prepared for the inevitable in any case.

--------------------------------------------------------------------------------

The trace is as follows:-

FAILED: src/Hyprland.p/events_Popups.cpp.o
ccache c++ -Isrc/Hyprland.p -Isrc -I../src -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/udis86 -I../subprojects/udis86 -I../subprojects/udis86/libudis86 -Isubprojects/udis86/__CMake_build -I../subprojects/udis86/__CMake_build -Iprotocols -I/usr/local/include -I/usr/local/include/libdrm -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/include/cairo -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing '-DGIT_BRANCH="main"' '-DGIT_COMMIT_HASH="871ab24c6e9d2fb6e48cbf990ddddf0c46a950af"' '-DGIT_COMMIT_MESSAGE="internal: properly set monitor props on special windows"' '-DGIT_DIRTY="dirty"' -std=c++23 -pthread -DWLR_USE_UNSTABLE -MD -MQ src/Hyprland.p/events_Popups.cpp.o -MF src/Hyprland.p/events_Popups.cpp.o.d -o src/Hyprland.p/events_Popups.cpp.o -c ../src/events/Popups.cpp
../src/events/Popups.cpp: In function ‘void createNewPopup(wlr_xdg_popup*, SXDGPopup*)’:
../src/events/Popups.cpp:59:76: error: ‘struct wlr_xdg_surface::<unnamed>’ has no member named ‘map’
   59 |     pHyprPopup->hyprListener_mapPopupXDG.initCallback(&popup->base->events.map, &Events::listener_mapPopupXDG, pHyprPopup, "HyprPopup");
      |                                                                            ^~~
../src/events/Popups.cpp:60:78: error: ‘struct wlr_xdg_surface::<unnamed>’ has no member named ‘unmap’
   60 |     pHyprPopup->hyprListener_unmapPopupXDG.initCallback(&popup->base->events.unmap, &Events::listener_unmapPopupXDG, pHyprPopup, "HyprPopup");
      |                                                                              ^~~~~
[342/428] Compiling C++ object src/Hyprland.p/events_Layers.cpp.o
FAILED: src/Hyprland.p/events_Layers.cpp.o
ccache c++ -Isrc/Hyprland.p -Isrc -I../src -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/udis86 -I../subprojects/udis86 -I../subprojects/udis86/libudis86 -Isubprojects/udis86/__CMake_build -I../subprojects/udis86/__CMake_build -Iprotocols -I/usr/local/include -I/usr/local/include/libdrm -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/include/cairo -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing '-DGIT_BRANCH="main"' '-DGIT_COMMIT_HASH="871ab24c6e9d2fb6e48cbf990ddddf0c46a950af"' '-DGIT_COMMIT_MESSAGE="internal: properly set monitor props on special windows"' '-DGIT_DIRTY="dirty"' -std=c++23 -pthread -DWLR_USE_UNSTABLE -MD -MQ src/Hyprland.p/events_Layers.cpp.o -MF src/Hyprland.p/events_Layers.cpp.o.d -o src/Hyprland.p/events_Layers.cpp.o -c ../src/events/Layers.cpp
../src/events/Layers.cpp: In function ‘void Events::listener_newLayerSurface(wl_listener*, void*)’:
../src/events/Layers.cpp:47:86: error: ‘struct wlr_layer_surface_v1::<unnamed>’ has no member named ‘map’
   47 |     layerSurface->hyprListener_mapLayerSurface.initCallback(&WLRLAYERSURFACE->events.map, &Events::listener_mapLayerSurface, layerSurface, "layerSurface");
      |                                                                                      ^~~
../src/events/Layers.cpp:48:88: error: ‘struct wlr_layer_surface_v1::<unnamed>’ has no member named ‘unmap’
   48 |     layerSurface->hyprListener_unmapLayerSurface.initCallback(&WLRLAYERSURFACE->events.unmap, &Events::listener_unmapLayerSurface, layerSurface, "layerSurface");
      |                                                                                        ^~~~~
../src/events/Layers.cpp: In function ‘void Events::listener_mapLayerSurface(void*, void*)’:
../src/events/Layers.cpp:112:33: error: ‘struct wlr_layer_surface_v1’ has no member named ‘mapped’
  112 |     layersurface->layerSurface->mapped = true;
      |                                 ^~~~~~
../src/events/Layers.cpp: In function ‘void Events::listener_unmapLayerSurface(void*, void*)’:
../src/events/Layers.cpp:207:37: error: ‘struct wlr_layer_surface_v1’ has no member named ‘mapped’
  207 |     if (layersurface->layerSurface->mapped)
      |                                     ^~~~~~
../src/events/Layers.cpp:208:37: error: ‘struct wlr_layer_surface_v1’ has no member named ‘mapped’
  208 |         layersurface->layerSurface->mapped = false;
      |                                     ^~~~~~
[343/428] Compiling C++ object src/Hyprland.p/events_Misc.cpp.o
FAILED: src/Hyprland.p/events_Misc.cpp.o
ccache c++ -Isrc/Hyprland.p -Isrc -I../src -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/udis86 -I../subprojects/udis86 -I../subprojects/udis86/libudis86 -Isubprojects/udis86/__CMake_build -I../subprojects/udis86/__CMake_build -Iprotocols -I/usr/local/include -I/usr/local/include/libdrm -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/include/cairo -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing '-DGIT_BRANCH="main"' '-DGIT_COMMIT_HASH="871ab24c6e9d2fb6e48cbf990ddddf0c46a950af"' '-DGIT_COMMIT_MESSAGE="internal: properly set monitor props on special windows"' '-DGIT_DIRTY="dirty"' -std=c++23 -pthread -DWLR_USE_UNSTABLE -MD -MQ src/Hyprland.p/events_Misc.cpp.o -MF src/Hyprland.p/events_Misc.cpp.o.d -o src/Hyprland.p/events_Misc.cpp.o -c ../src/events/Misc.cpp
../src/events/Misc.cpp: In function ‘void Events::listener_startDrag(wl_listener*, void*)’:
../src/events/Misc.cpp:113:91: error: ‘struct wlr_drag_icon::<unnamed>’ has no member named ‘map’
  113 |         g_pInputManager->m_sDrag.hyprListener_mapIcon.initCallback(&wlrDrag->icon->events.map, &Events::listener_mapDragIcon, &g_pInputManager->m_sDrag, "DragIcon");
      |                                                                                           ^~~
../src/events/Misc.cpp:114:93: error: ‘struct wlr_drag_icon::<unnamed>’ has no member named ‘unmap’
  114 |         g_pInputManager->m_sDrag.hyprListener_unmapIcon.initCallback(&wlrDrag->icon->events.unmap, &Events::listener_unmapDragIcon, &g_pInputManager->m_sDrag, "DragIcon");
  
--------------------------------------------------------------------------------

A quick peruse of today's changes to Sway will probably help fast-track any necessary alterations to Hyprland I suspect.

Hyprland works fine with the latest WLROOTS up until this morning (BST) as far as I can discern btw.

All the best...

PS. By all means let me know if you find this kind of feedback a hindrance rather than of any great benefit and I'll behave accordingly in future... :-)

**Comment by vaxerski** [comment]
I always test wlroots updates before bumping. No need for opening an issue like this.
