### ISSUE TITLE
Hyprland crash on window close

### ISSUE THREAD

**Issue by LewisTansley** [hyprwm/Hyprland#2423]
Related: wofi will also cause a crash back to sddm as the window unmaps?

Steps to reproduce
exit window using killactive
Expected outcome
window exits
Noted outcome
Hyprland crashes out to sddm

Config'd based off of Hyprland / wayland requirements to exec.conf aswell as required patches (hyprland-nvidia and nvidia-open-dkms)

Specs:
OS: ArcoLinux
Kernel: 6.3.5-arch1-1
Shell: fish
Resolution: 3440x1440
DE: Hyprland
CPU: AMD Ryzen 7 2700 (16) @ 3.200GHz
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 2.61GiB / 15.55GiB (16%)
GPU Driver: NVIDIA NVRM version: NVIDIA UNIX Open Kernel Module for x86_64

Log Files below, if any other questions fire away, had to write this quick because I've already forgotten and closed a window causing a crash once so this is my second time writing this haha!

Journalctl output:
Jun 02 22:20:33 RIG systemd-coredump[7957]: [🡕] Process 1357 (Hyprland) of user 1000 dumped core.

                                            Stack trace of thread 1357:
                                            #0  0x00007f853b69f26c n/a (libc.so.6 + 0x8926c)
                                            #1  0x00007f853b64fa08 raise (libc.so.6 + 0x39a08)
                                            #2  0x00007f853b638538 abort (libc.so.6 + 0x22538)
                                            #3  0x0000564563061d41 _Z25handleUnrecoverableSignali (Hyprland + 0x9cd41)
                                            #4  0x00007f853b64fab0 n/a (libc.so.6 + 0x39ab0)
                                            #5  0x00007f853b69f26c n/a (libc.so.6 + 0x8926c)
                                            #6  0x00007f853b64fa08 raise (libc.so.6 + 0x39a08)
                                            #7  0x00007f853b638538 abort (libc.so.6 + 0x22538)
                                            #8  0x00007f853b63845c n/a (libc.so.6 + 0x2245c)
                                            #9  0x00007f853b6483d6 __assert_fail (libc.so.6 + 0x323d6)
                                            #10 0x00007f853c2751f1 gles2_get_texture (libwlroots.so.12032 + 0x421f1)
                                            #11 0x00007f853c273bac gles2_render_subtexture_with_matrix (libwlroots.so.12032 + 0x40bac)
                                            #12 0x00007f853c26e678 wlr_render_texture_with_matrix (libwlroots.so.12032 + 0x3b678)
                                            #13 0x00007f853c2a16c3 wlr_output_render_software_cursors (libwlroots.so.12032 + 0x6e6c3)
                                            #14 0x0000564563185f8c _ZN13CHyprRenderer13renderMonitorEP8CMonitor (Hyprland + 0x1c0f8c)
                                            #15 0x0000564563102cec _Z13handleWrappedP11wl_listenerPv (Hyprland + 0x13dcec)
                                            #16 0x00007f853c1ea01e wl_signal_emit_mutable (libwayland-server.so.0 + 0xa01e)
                                            #17 0x00007f853c2898b8 handle_page_flip (libwlroots.so.12032 + 0x568b8)
                                            #18 0x00007f853c1b99af drmHandleEvent (libdrm.so.2 + 0xe9af)
                                            #19 0x00007f853c28c109 handle_drm_event (libwlroots.so.12032 + 0x59109)
                                            #20 0x00007f853c1ebae2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xbae2)
                                            #21 0x00007f853c1ec2d7 wl_display_run (libwayland-server.so.0 + 0xc2d7)
                                            #22 0x00005645630528a4 main (Hyprland + 0x8d8a4)
                                            #23 0x00007f853b639850 n/a (libc.so.6 + 0x23850)
                                            #24 0x00007f853b63990a __libc_start_main (libc.so.6 + 0x2390a)
                                            #25 0x0000564563061be5 _start (Hyprland + 0x9cbe5)

                                            Stack trace of thread 1383:
                                            #0  0x00007f853b72296f accept (libc.so.6 + 0x10c96f)
                                            #1  0x0000564563122063 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN13CEventManager11startThreadEvEUlvE_EEEEE6_M_runEv (Hypr>
                                            #2  0x00007f853b8e1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                                            #3  0x00007f853b69d44b n/a (libc.so.6 + 0x8744b)
                                            #4  0x00007f853b720e40 n/a (libc.so.6 + 0x10ae40)
                                            ELF object binary architecture: AMD x86-64

======================================================================================================
Jun 02 22:20:34 RIG systemd-coredump[7996]: [🡕] Process 1733 (Xwayland) of user 1000 dumped core.

                                            Stack trace of thread 1733:
                                            #0  0x00007fe061d7126c n/a (libc.so.6 + 0x8926c)
                                            #1  0x00007fe061d21a08 raise (libc.so.6 + 0x39a08)
                                            #2  0x00007fe061d0a538 abort (libc.so.6 + 0x22538)
                                            #3  0x00005617c23f7221 n/a (Xwayland + 0x16a221)
                                            #4  0x00005617c2400b2d n/a (Xwayland + 0x173b2d)
                                            #5  0x00005617c22bf342 n/a (Xwayland + 0x32342)
                                            #6  0x00007fe061d0b850 n/a (libc.so.6 + 0x23850)
                                            #7  0x00007fe061d0b90a __libc_start_main (libc.so.6 + 0x2390a)
                                            #8  0x00005617c22bfa65 n/a (Xwayland + 0x32a65)
                                            ELF object binary architecture: AMD x86-64
=======================================================================================================
Jun 02 22:24:28 RIG systemd-coredump[12215]: [🡕] Process 8048 (Hyprland) of user 1000 dumped core.

                                             Stack trace of thread 8048:
                                             #0  0x00007f3b2ebb226c n/a (libc.so.6 + 0x8926c)
                                             #1  0x00007f3b2eb62a08 raise (libc.so.6 + 0x39a08)
                                             #2  0x00007f3b2eb4b538 abort (libc.so.6 + 0x22538)
                                             #3  0x0000563a23abcd41 _Z25handleUnrecoverableSignali (Hyprland + 0x9cd41)
                                             #4  0x00007f3b2eb62ab0 n/a (libc.so.6 + 0x39ab0)
                                             #5  0x00007f3b2ebb226c n/a (libc.so.6 + 0x8926c)
                                             #6  0x00007f3b2eb62a08 raise (libc.so.6 + 0x39a08)
                                             #7  0x00007f3b2eb4b538 abort (libc.so.6 + 0x22538)
                                             #8  0x00007f3b2eb4b45c n/a (libc.so.6 + 0x2245c)
                                             #9  0x00007f3b2eb5b3d6 __assert_fail (libc.so.6 + 0x323d6)
                                             #10 0x00007f3b2f7e31f1 gles2_get_texture (libwlroots.so.12032 + 0x421f1)
                                             #11 0x00007f3b2f7e1bac gles2_render_subtexture_with_matrix (libwlroots.so.12032 + 0x40bac)
                                             #12 0x00007f3b2f7dc678 wlr_render_texture_with_matrix (libwlroots.so.12032 + 0x3b678)
                                             #13 0x00007f3b2f80f6c3 wlr_output_render_software_cursors (libwlroots.so.12032 + 0x6e6c3)
                                             #14 0x0000563a23be0f8c _ZN13CHyprRenderer13renderMonitorEP8CMonitor (Hyprland + 0x1c0f8c)
                                             #15 0x0000563a23b5dcec _Z13handleWrappedP11wl_listenerPv (Hyprland + 0x13dcec)
                                             #16 0x00007f3b2f75801e wl_signal_emit_mutable (libwayland-server.so.0 + 0xa01e)
                                             #17 0x00007f3b2f7f78b8 handle_page_flip (libwlroots.so.12032 + 0x568b8)
                                             #18 0x00007f3b2f7279af drmHandleEvent (libdrm.so.2 + 0xe9af)
                                             #19 0x00007f3b2f7fa109 handle_drm_event (libwlroots.so.12032 + 0x59109)
                                             #20 0x00007f3b2f759ae2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xbae2)
                                             #21 0x00007f3b2f75a2d7 wl_display_run (libwayland-server.so.0 + 0xc2d7)
                                             #22 0x0000563a23aad8a4 main (Hyprland + 0x8d8a4)
                                             #23 0x00007f3b2eb4c850 n/a (libc.so.6 + 0x23850)
                                             #24 0x00007f3b2eb4c90a __libc_start_main (libc.so.6 + 0x2390a)
                                             #25 0x0000563a23abcbe5 _start (Hyprland + 0x9cbe5)

                                             Stack trace of thread 8066:
                                             #0  0x00007f3b2ec3596f accept (libc.so.6 + 0x10c96f)
                                             #1  0x0000563a23b7d063 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN13CEventManager11startThreadEvEUlvE_EEEEE6_M_runEv (Hyp>
                                             #2  0x00007f3b2eee1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                                             #3  0x00007f3b2ebb044b n/a (libc.so.6 + 0x8744b)
                                             #4  0x00007f3b2ec33e40 n/a (libc.so.6 + 0x10ae40)
                                             ELF object binary architecture: AMD x86-64
=======================================================================================================
Jun 02 22:24:29 RIG systemd-coredump[12224]: [🡕] Process 8544 (Xwayland) of user 1000 dumped core.

                                             Stack trace of thread 8544:
                                             #0  0x00007ff0d17a826c n/a (libc.so.6 + 0x8926c)
                                             #1  0x00007ff0d1758a08 raise (libc.so.6 + 0x39a08)
                                             #2  0x00007ff0d1741538 abort (libc.so.6 + 0x22538)
                                             #3  0x000055df0fe7f221 n/a (Xwayland + 0x16a221)
                                             #4  0x000055df0fe88b2d n/a (Xwayland + 0x173b2d)
                                             #5  0x000055df0fd47342 n/a (Xwayland + 0x32342)
                                             #6  0x00007ff0d1742850 n/a (libc.so.6 + 0x23850)
                                             #7  0x00007ff0d174290a __libc_start_main (libc.so.6 + 0x2390a)
                                             #8  0x000055df0fd47a65 n/a (Xwayland + 0x32a65)
                                             ELF object binary architecture: AMD x86-64

[hyprlandCrashReport1273.txt](https://github.com/hyprwm/Hyprland/files/11639412/hyprlandCrashReport1273.txt)
[hyprlandCrashReport1275.txt](https://github.com/hyprwm/Hyprland/files/11639413/hyprlandCrashReport1275.txt)
[hyprlandCrashReport1357.txt](https://github.com/hyprwm/Hyprland/files/11639414/hyprlandCrashReport1357.txt)
[hyprlandCrashReport2740.txt](https://github.com/hyprwm/Hyprland/files/11639415/hyprlandCrashReport2740.txt)
[hyprlandCrashReport4006.txt](https://github.com/hyprwm/Hyprland/files/11639416/hyprlandCrashReport4006.txt)
[hyprlandCrashReport6564.txt](https://github.com/hyprwm/Hyprland/files/11639417/hyprlandCrashReport6564.txt)
[hyprlandCrashReport8048.txt](https://github.com/hyprwm/Hyprland/files/11639418/hyprlandCrashReport8048.txt)
[hyprlandCrashReport10315.txt](https://github.com/hyprwm/Hyprland/files/11639419/hyprlandCrashReport10315.txt)
[hyprlandCrashReport12277.txt](https://github.com/hyprwm/Hyprland/files/11639420/hyprlandCrashReport12277.txt)
[hyprlandCrashReport13588.txt](https://github.com/hyprwm/Hyprland/files/11639421/hyprlandCrashReport13588.txt)
[hyprlandCrashReport16531.txt](https://github.com/hyprwm/Hyprland/files/11639423/hyprlandCrashReport16531.txt)
[hyprlandCrashReport17488.txt](https://github.com/hyprwm/Hyprland/files/11639424/hyprlandCrashReport17488.txt)
[hyprlandCrashReport24499.txt](https://github.com/hyprwm/Hyprland/files/11639425/hyprlandCrashReport24499.txt)
[hyprlandCrashReport25258.txt](https://github.com/hyprwm/Hyprland/files/11639426/hyprlandCrashReport25258.txt)
[hyprlandCrashReport25306.txt](https://github.com/hyprwm/Hyprland/files/11639427/hyprlandCrashReport25306.txt)
[hyprlandCrashReport28899.txt](https://github.com/hyprwm/Hyprland/files/11639428/hyprlandCrashReport28899.txt)
[hyprlandCrashReport29929.txt](https://github.com/hyprwm/Hyprland/files/11639429/hyprlandCrashReport29929.txt)
[hyprlandCrashReport37253.txt](https://github.com/hyprwm/Hyprland/files/11639430/hyprlandCrashReport37253.txt)
[hyprlandCrashReport43444.txt](https://github.com/hyprwm/Hyprland/files/11639431/hyprlandCrashReport43444.txt)
[hyprlandCrashReport44056.txt](https://github.com/hyprwm/Hyprland/files/11639432/hyprlandCrashReport44056.txt)
[hyprlandCrashReport67405.txt](https://github.com/hyprwm/Hyprland/files/11639433/hyprlandCrashReport67405.txt)

**Comment by vaxerski** [comment]
seventh dupe yay

#2404

**Comment by LewisTansley** [comment]
My b I should've checked closed tags, thanks Vax
