### ISSUE TITLE
cursor is too big when hovering anything other than empty workspace zone with scaling

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#2425]
I have a monitor scaled at 1.3. When my cursor hovers any client, the cursor is getting bigger. It has its normal size when not hovering anything. If I set the scaling to 1, the issue goes away.

https://github.com/hyprwm/Hyprland/assets/208711/6eb850a6-ce97-42e2-b095-80fac8977947

**Comment by vaxerski** [comment]
it's a wlroots issue that has been fixed 10h ago while I was asleep, I'll bump the dep soon

**Comment by vaxerski** [comment]
147e962370069e6e3ec8054ef4243fc3fd69c9e8
