### ISSUE TITLE
Screen freezes randomly

### ISSUE THREAD

**Issue by ryansantos1174** [hyprwm/Hyprland#2427]
When logging into hyprland, randomly the screen will freeze and no updates to the screen are visible. Sometimes this happens a few minutes after startup, sometimes there is not a problem all day. I'm still able to interact with the system. I'm able to kill Hyprland or reboot the system by mimicking the key presses I would normally use, however, nothing changes on the screen. No terminal pops up and the mouse doesn't move. Running this on arcolinux (arch derivative). Attached is the hyprland log file 
[hyprlandLog.txt](https://github.com/hyprwm/Hyprland/files/11641938/hyprlandLog.txt), the crash report
[hyprlandCrashReport2792.txt](https://github.com/hyprwm/Hyprland/files/11641947/hyprlandCrashReport2792.txt), and my config file 
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/11641955/hyprland.txt).

Not sure if the crash report is referring to when I am forced to exit Hyprland. Therefore, coredumpctl does not give any PIDs for me to post the info of.  Please let me know if I can provide any more information. I switched from the linux-lts kernel to the standard linux kernel before writing this. So far, it seems as if there has been no freezing issues, however, as I mentioned the freezing happens at random it seems.

**Comment by vaxerski** [comment]
post the log from hyprland launched with `HYPRLAND_LOG_WLR=1`  pleas

**Comment by ryansantos1174** [comment]
Attached is the log file and the bash script I used to execute Hyprland with the environment variable set
[hyprlandLog2.txt](https://github.com/hyprwm/Hyprland/files/11644331/hyprlandLog2.txt)
[hyprland_exec.txt](https://github.com/hyprwm/Hyprland/files/11644335/hyprland_exec.txt)

**Comment by ryansantos1174** [comment]
Installed base arch and the problem is no longer there. I'm going to assume this is an arcolinux problem ( maybe some weird default values). However, since I've installed the new system I can no longer help debug, will close this issue.

**Comment by Alg0v** [comment]
I have the same problem on a new Arch system. At first it wasn't doing that but IDK if I did something wrong with the config but now it crashes 2-4 times per hour.

**Comment by Alg0v** [comment]
Nevermind, might be an issue with amdgpu as we both have an AMD gpu and it also happened on XFCE4

**Comment by zelfroster** [comment]
> Nevermind, might be an issue with amdgpu as we both have an AMD gpu and it also happened on XFCE4

I also have AMD gpu, and hyprland freezes randomly once or twice in a day. dunno why.

**Comment by Alg0v** [comment]
It's been a long time since I haven't got screen freezes. It was probably an issue with `amdgpu`. Is your system up to date ? Personally, I'm running Arch Linux, so I have a pretty recent `amdgpu` package (23.1.4).
