### ISSUE TITLE
No audio output after install either pulseaudio or pipewire

### ISSUE THREAD

**Issue by anupam2150** [hyprwm/Hyprland#2428]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by vaxerski** [comment]
great, nothing to do with hyprland

**Comment by anupam2150** [comment]
How can I solve the issue?

**Comment by anupam2150** [comment]
Can you help me in this ??

**Comment by anupam2150** [comment]
I am new to hyprland as well as the arch Linux, please if you can help me?
