### ISSUE TITLE
i am having issue with the audio output even after installing pipewire or pulseaudio

### ISSUE THREAD

**Issue by anupam2150** [hyprwm/Hyprland#2429]
Please help, i don't want to change back to my previous linux distro

Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by NotAShelf** [comment]
Hyprland is not responsible for your audio though.

P.S. I love how you expect us to basically read your mind across the internet, giving literally no details on your system while asking for help.

**Comment by vaxerski** [comment]
we're not linux tech support. Your issue is not related to hyprland. Opening more duplicate issues will get you banned from here.
