### ISSUE TITLE
Text gets blurry in popup selection with two monitors

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#2433]
I have two monitors with different resolution and scale coefficient. which is configured with

```ini
# 4k with scale 2
monitor=DP-1,3840x2160,0x0,2
# 1080P with scale 1
monitor=eDP-1,1920x1080@144,1920x0,1
```

And I launched `pavucontrol` (a wayland-native app) in my 4k monitor, then select port, the text in popup is blurry.

![blur](https://github.com/hyprwm/Hyprland/assets/24190403/bf10d039-54d4-427b-b6f9-f45e2e792be8)

An interesting thing is that if I add a small scale coefficient (e.g. 1.0001) to my 1080P monitor, text will not be blurry. But if the scale coefficient is less or equal to 1, text gets blurry.

![nonblur](https://github.com/hyprwm/Hyprland/assets/24190403/df43b51c-7d2a-4cce-80d5-50fedd8e2517)

**Comment by 1024th** [comment]
I can reproduce the bug. Another thing I noticed is that only GTK applications (e.g. evince, nemo) have the problem. The popup in Qt applications (e.g. Dolphin) is not blurry.

I can confirm that if I add a small scale coefficient (e.g. 1.0001) to the 1080P monitor, text will not be blurry.

Both menu popups and tooltip popups are affected.

![nemo_blurry_menu](https://github.com/hyprwm/Hyprland/assets/47070449/8f9979a5-1552-484b-b957-5aad98b77138)

![nemo_blurry_tooltip](https://github.com/hyprwm/Hyprland/assets/47070449/e1204fe2-8195-4985-911c-cd29b6c1a7a9)

My Hyprland config about monitors:

```
monitor = eDP-1,1920x1080,3072x648,1
monitor = DP-1,3840x2160,0x0,1.25
```

Hyprland Version:

```
Hyprland, built from branch main at commit ab5497a0c9e9269b1036a0bede42cbd0bbfd94b9 dirty (input: properly track xdg surfaces' geometry in vectorToSurfaceLocal).
Tag: v0.31.0-61-gab5497a0

flags: (if any)
debug
```

**Comment by 15cm** [comment]
It doesn't seem to be an Hyprland issue on my end. I tried these version combinations:
- Fcitx5: [5.0.23, 5.11]
- Hyprland: [[0.31 at commit 4a4e13f8acedd2dc44236deed13fd47096cbe508](https://github.com/hyprwm/Hyprland/commit/4a4e13f8acedd2dc44236deed13fd47096cbe508), [0.32 at commit 2e26542e3bba3533e71e13f2257823d96da2318a](https://github.com/hyprwm/Hyprland/commit/2e26542e3bba3533e71e13f2257823d96da2318a)]

5.11 Fcitx5 has the issue regardless of Hyprland versions and 5.0.23 Fcitx5 doesn't have the issue. I worked around the issue by pinning fcitx5 version to 5.0.23 in on NixOS like [this](https://github.com/15cm/nixfiles/commit/4032445252f16e9a6f869da233063d4a10b7685a)

**Comment by q234rty** [comment]
> Update: Disabling "Enable fractional scale under Wayland" in the Fcitx5 Classic User Interface addons fixes the issue on 2X scale on 5.11 Fcitx5.

This is a hyprland issue, not a fcitx5 bug: `env WAYLAND_DEBUG=1 fcitx5` shows that a `preferred_scale` of 120 (which means a scale of `1` in this context) is sent by hyprland, even though scaling is enabled on the monitor.
[fcitx5_pr.log](https://github.com/hyprwm/Hyprland/files/13490415/fcitx5_pr.log)

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by dragove** [comment]
Yes, it's still blurry on `0.40`

![Screenshot_20240517_230201](https://github.com/hyprwm/Hyprland/assets/24190403/5ba7c4bc-42c4-40c5-9f1b-e4e0be276d29)

**Comment by dragove** [comment]
It seems this issue has been fixed. If anyone encountered again, please leave a comment with reproduce log or open a new issue. thanks.
