### ISSUE TITLE
Add hot corner functionality

### ISSUE THREAD

**Issue by lacamar** [hyprwm/Hyprland#2435]
Hot corners would be a small but useful addition to Hyprland. The idea is that an action occurs when the mouse is moved into a specific corner of the desktop for a certain amount of time (e.g. 200ms), with or without specified modifier keys.

I am only aware of it being implemented on MacOS, but the functions you can assign to it there are very limited so it can only be more potent on Hyprland.

Some functions which are useful to assign to the corners are to run an app launcher, activate a screen locker, toggle a special workspace, cycle through workspaces, or run really any command relevant to a certain workflow.

The overall effect of this feature is that it gives the mouse considerably more power to activate functions in the desktop environment.
This video demonstrates the concept briefly: https://www.youtube.com/watch?v=PaxFUybMbng

**Comment by NotAShelf** [comment]
Could you try this?

https://github.com/AndreasBackx/waycorner

I haven't had any luck with it back when I was on Arch (and it's not *yet* packaged for Nixpkgs) but you might have some luck getting it to work, it should be working in theory because Vaxry has said we implement the protocol it depends on.

**Comment by lacamar** [comment]
I wasn't aware of that project. I will try that on out Asahi Linux (arch linux ARM) when I get a chance and let you know how it goes.

**Comment by NotAShelf** [comment]
I'll also try packaging it nix, we can nag vaxry if it doesn't work.

**Comment by NotAShelf** [comment]
I was able to get it to work, great success.

**Comment by NotAShelf** [comment]
This should probably be closed, I can confirm for you that Waycorner works on Hyprland and I don't think hotcorners will be built into Hyprland outside of a plugin.
