### ISSUE TITLE
fcitx5 input window will be overlaid in some apps which were moved to special workspace, it should on the toppest layer.

### ISSUE THREAD

**Issue by uzvg** [hyprwm/Hyprland#2439]
Fcitx5 input window works well on regular workspace and floating windows, it works well too on firefox and kitty terminal when these windows were move to special workspace, but it will be overlaid if I want to input something on google-chrome browser or chromium-based app like logseq when those windows were moved to special workspace.
**The normal situation**:
![2023-06-05T11:33:43,306609090+08:00](https://github.com/hyprwm/Hyprland/assets/32935216/31f7c463-f632-410e-8363-8f2ac8247a0f)
**The overlaid situation:**
![2023-06-05T11:35:14,557512075+08:00](https://github.com/hyprwm/Hyprland/assets/32935216/c1bc3218-d98c-4f3d-b7ad-193d154bb751)

**Comment by vaxerski** [comment]
yeah because it's using the legacy xwayland mode. launch chrome with `--gtk-version=4` and it will fix this by using the native wayland protocol

**Comment by uzvg** [comment]
> yeah because it's using the legacy xwayland mode. launch chrome with `--gtk-version=4` and it will fix this by using the native wayland protocol

it works on chrome, but still not work on electron-based apps, that's electron's question, thank you! : )
