### ISSUE TITLE
Crash in group handling

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#2441]
Reproduce like this:
1. open a single window
2. make it a group with togglegroup
3. open another window that gets added to that group
4. use movetoworkspace to move the focused window to another workspace (this enters the weird stage explained in https://github.com/hyprwm/Hyprland/issues/2229
5. close the window
6. go back to the workspace with the group (now containing only one window)
7. togglegroup
8. Crash!

**Comment by MightyPlaza** [comment]
The original issue seems to be fixed on latest, probably by https://github.com/hyprwm/Hyprland/commit/cbe9bf0e692010717e3d35e87a9abee79c5f8e4f
So i think this one is as well

**Comment by MightyPlaza** [comment]
@vaxerski
