### ISSUE TITLE
Hyprland random crashes 

### ISSUE THREAD

**Issue by JaimeJimenezG** [hyprwm/Hyprland#2444]
Good morning,

I'm having 5 crashes a day more or less, when it happens I'm not doing anything essential... open windows browse google chrome... I don't know what it could be...

I have seen that more people are experiencing this.

I leave here some logs. I hope they help.

Greetings

**Comment by JaimeJimenezG** [comment]
[hyprlandCrashReport2604.txt](https://github.com/hyprwm/Hyprland/files/11653797/hyprlandCrashReport2604.txt)
[hyprlandCrashReport2610.txt](https://github.com/hyprwm/Hyprland/files/11653798/hyprlandCrashReport2610.txt)
[hyprlandCrashReport2614.txt](https://github.com/hyprwm/Hyprland/files/11653799/hyprlandCrashReport2614.txt)
[hyprlandCrashReport3377.txt](https://github.com/hyprwm/Hyprland/files/11653800/hyprlandCrashReport3377.txt)
[hyprlandCrashReport4191.txt](https://github.com/hyprwm/Hyprland/files/11653801/hyprlandCrashReport4191.txt)
[hyprlandCrashReport4785.txt](https://github.com/hyprwm/Hyprland/files/11653802/hyprlandCrashReport4785.txt)
[hyprlandCrashReport7242.txt](https://github.com/hyprwm/Hyprland/files/11653803/hyprlandCrashReport7242.txt)
[hyprlandCrashReport35738.txt](https://github.com/hyprwm/Hyprland/files/11653804/hyprlandCrashReport35738.txt)

**Comment by vaxerski** [comment]
#2438 

searching hard
