### ISSUE TITLE
Invisible pseudo-tiled windows.

### ISSUE THREAD

**Issue by PoSayDone** [hyprwm/Hyprland#2446]
If I use pseudo in window rule for any app, these apps become invisible if I try to open them.
`windowrulev2=pseudo,class:^(kitty)$`
![image](https://github.com/hyprwm/Hyprland/assets/29358657/c82e21ba-275f-4ce2-a16f-78c6d9bc285e)

**Comment by 3laws** [comment]
Yep, still have no idea why.

**Comment by mentalAdventurer** [comment]
I have the same problem. It seems that the window size is 0, 0 px. I have tried to force the window size with another rule, but to no avail.

**Comment by vaxerski** [comment]
fixed in e96fcb31f0df36a88922fa1870e3372218c79539

**Comment by danielgomez3** [comment]
How can I apply this patch to my current gentoo-packaged hyprland?

**Comment by MightyPlaza** [comment]
Update?
