### ISSUE TITLE
Bug: Hyprland logo or wallpaper partially visible in Stardew Valley

### ISSUE THREAD

**Issue by rszyma** [hyprwm/Hyprland#2454]
### Steps to reproduce
1. Run [Stardew Valley](https://store.steampowered.com/app/413150/Stardew_Valley/).
2. Go to "Carpenter's shop" or "Pierre's General Store" (or any cave or anywhere at night outside)
### Expected outcome
Everything working well.
### Noted outcome
When running Stardew Valley in `windowed mode` - I can see my wallpaper as the game's window were partially opaque:
![image](https://github.com/hyprwm/Hyprland/assets/44318430/d0d408c4-e6be-4dcd-bce2-b8b10684502e)

When running `fullscreen` or `windowed borderless` mode I can see partially opaque hyprland logo:
![image](https://github.com/hyprwm/Hyprland/assets/44318430/2064ae5e-945e-438e-bce0-45099a649981)

This bug only happens in the when there are lighting shaders (?) applied (you can see that the vertical corridor there is less light and the wallpaper is not visible there)

**Comment by Adu-3** [comment]
I did run it with my system without any issues or your issue 

Do you use any other wallpaper utility ? for your wallpaper if yes then make sure you have under `misc` section in your configuration `disable_hyprland_logo=true`

If this is not the case then try to check your config for `windowrule` that do anything with the opacity of the window for thing that is related to the game ? 

If nothing of these works run the game and on the command line run the command `hyprctl clients` and check for stardew valley window and under its information make sure that is using by `xwayland: 1`

**Comment by rszyma** [comment]
> make sure you have under `misc` section in your configuration `disable_hyprland_logo=true`
I've just set that to `true` and as expected it fixed the second case. But there's still the issue with the `windowed mode`

> Do you use any other wallpaper utility
swaybg

> check your config for `windowrule` that do anything with the opacity of the window for thing that is related to the game

There is nothing related to opacity in my config. I even disabled everything in my config but the issue is still present.

> If nothing of these works run the game and on the command line run the command `hyprctl clients` and check for stardew valley window and under its information make sure that is using xwayland by `xwayland: 1`

```
Window 55d7509b4c40 -> Stardew Valley:
	mapped: 1
	hidden: 0
	at: 12,12
	size: 1896,1006
	workspace: 3 (3)
	floating: 0
	monitor: 0
	class: Stardew Valley
	title: Stardew Valley
	initialClass: Stardew Valley
	initialTitle: Stardew Valley
	pid: 79187
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

**Comment by vaxerski** [comment]
forcergbx rule iirc
