### ISSUE TITLE
Using different natural_scroll variable for input and touchpad does not work

### ISSUE THREAD

**Issue by chronicc** [hyprwm/Hyprland#2458]
@fufexan

Hyprland is not crashing.

## Expected Outcome

Since it's possible to configure `natural_scoll` both in the input global section and the input:touchpad section, I assume that it should be possible that my mouse uses the normal behavior and the touchpad uses the mac behavior.

## Problem

However when I configure different values for both keys, the global key wins and configures the behavior for both devices.

Excerpt from my hyprland.conf:

```
input {
    kb_layout = de
    kb_variant = nodeadkeys
    kb_model = pc105
    kb_options =
    kb_rules =

    float_switch_override_focus = 1
    follow_mouse = 1
    natural_scroll = 0
    sensitivity = 0

    touchpad {
        clickfinger_behavior = 1
        disable_while_typing = 1
        natural_scroll = 1
        tap-to-click = 1
    }
}

...
```

### Hyprland

```
hyprctl version
Hyprland, built from branch  at commit 4afeedbd567ca2114f682f14a6de26d4a8188878  ().
Tag: ?

flags: (if any)
debug
```

### NixOS

```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.05 (Stoat), 23.05.20230605.70f7275`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(chronicc): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fufexan** [comment]
@chronicc you may want to set the touchpad natural scrolling inside a per-device configuration. For example, this is what I have and works:
```ini
input {
  kb_layout = ro

  # focus change on cursor move
  follow_mouse = 1
  accel_profile = flat
  touchpad {
    scroll_factor = 0.3
  }
}

device:MSFT0001:00 04F3:31EB Touchpad {
  accel_profile = adaptive
  natural_scroll = true
  sensitivity = 0.1
}
```

**Comment by chronicc** [comment]
@fufexan thanks for the suggestion.

I've just tried this and no matter how I write it, I get the "No such field." error:

```
device:uniw0001:00-093a:0255-touchpad Touchpad {
    natural_scroll = 1
}
```

```
device:uniw0001:00-093a:0255-touchpad touchpad {
    natural_scroll = 1
}
```

```
device:uniw0001:00-093a:0255-touchpad {
    natural_scroll = 1
}
```

Just to make sure, hyptctl devices lists the device:

```
mice:
...
	Mouse at 21fd940:
		uniw0001:00-093a:0255-touchpad
			default speed: 0.000000
```

**Comment by chronicc** [comment]
Ah sorry, I oversaw the fact, that the device config needs to reside outside of the input config.

Okay with this workaround, the behavior works as expected.

However I feel as if the original bug is still valid. Otherwise a documentation update may be helpful to point out, that my original assumption is not supported.

**Comment by fufexan** [comment]
I'll take a look when I have time.

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/blob/fc59cef1ee573a950c5d5f3bacf1b51142fd56db/src/managers/input/InputManager.cpp#L941-L951
It seems the code does check for `natural_scroll` in both `input` and `input:touchpad`. I'm not sure why it does not work.

@vaxerski any clue why?

**Comment by MightyPlaza** [comment]
still happening?

**Comment by chronicc** [comment]
Hi, I'm not using hyperland anymore so I can not reciprocate this.

**Comment by vaxerski** [comment]
closing then
