### ISSUE TITLE
spotifywm no longer needed?

### ISSUE THREAD

**Issue by naps62** [hyprwm/Hyprland#2461]
The [docs](https://wiki.hyprland.org/Useful-Utilities/App-Clients/) suggest installing [spotifywm](https://github.com/dasJ/spotifywm) as a workaround for spotify's behaviour not being friendly to windowrules

however, I'm currently running these rules successfully, without having to install it:
```
windowrulev2 = float, title:Spotify
windowrulev2 = size 1800 1000, title:Spotify
windowrulev2 = center, title:Spotify
```

are the docs outdated?

**Comment by naps62** [comment]
Just remembered I'm also using [spicetify](https://spicetify.app/), though I'm not sure that could have any effect on the window's initial state?

**Comment by RS-dev7** [comment]
Huh yeah spotify was also working on my hyprland on arch install with window rules until recently but I had to reinstall arch/hyprland yesterday and spotify won't launch at all now, with or without spotifywm.

**Comment by zjeffer** [comment]
I just tested and window rules indeed seem to work without spotifywm now. Tested with this rule:

```
windowrulev2 = opacity 0.90 override 0.90 override, title:^(Spotify)$
```
