### ISSUE TITLE
 "sudo make install" is not working

### ISSUE THREAD

**Issue by BrkGGM** [hyprwm/Hyprland#2462]
I am using kali I did in https://gist.github.com/Vertecedoc4545/3b077301299c20c5b9b4db00f4ca6000 but when I do sudo make install it gives this : 

FAILED: Hyprland 
: && /usr/bin/c++ -O3 -DNDEBUG -Wl,--export-dynamic -rdynamic  -rdynamic CMakeFiles/Hyprland.dir/src/Compositor.cpp.o CMakeFiles/Hyprland.dir/src/Window.cpp.o CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o CMakeFiles/Hyprland.dir/src/debug/CrashReporter.cpp.o CMakeFiles/Hyprland.dir/src/debug/HyprCtl.cpp.o CMakeFiles/Hyprland.dir/src/debug/HyprDebugOverlay.cpp.o CMakeFiles/Hyprland.dir/src/debug/HyprNotificationOverlay.cpp.o CMakeFiles/Hyprland.dir/src/debug/Log.cpp.o CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o CMakeFiles/Hyprland.dir/src/events/Layers.cpp.o CMakeFiles/Hyprland.dir/src/events/Misc.cpp.o CMakeFiles/Hyprland.dir/src/events/Monitors.cpp.o CMakeFiles/Hyprland.dir/src/events/Popups.cpp.o CMakeFiles/Hyprland.dir/src/events/Windows.cpp.o CMakeFiles/Hyprland.dir/src/helpers/AnimatedVariable.cpp.o CMakeFiles/Hyprland.dir/src/helpers/BezierCurve.cpp.o CMakeFiles/Hyprland.dir/src/helpers/Color.cpp.o CMakeFiles/Hyprland.dir/src/helpers/MiscFunctions.cpp.o CMakeFiles/Hyprland.dir/src/helpers/Monitor.cpp.o CMakeFiles/Hyprland.dir/src/helpers/SubsurfaceTree.cpp.o CMakeFiles/Hyprland.dir/src/helpers/Timer.cpp.o CMakeFiles/Hyprland.dir/src/helpers/Vector2D.cpp.o CMakeFiles/Hyprland.dir/src/helpers/WLClasses.cpp.o CMakeFiles/Hyprland.dir/src/helpers/WLListener.cpp.o CMakeFiles/Hyprland.dir/src/helpers/WLSurface.cpp.o CMakeFiles/Hyprland.dir/src/helpers/Workspace.cpp.o CMakeFiles/Hyprland.dir/src/hyprerror/HyprError.cpp.o CMakeFiles/Hyprland.dir/src/init/initHelpers.cpp.o CMakeFiles/Hyprland.dir/src/layout/DwindleLayout.cpp.o CMakeFiles/Hyprland.dir/src/layout/IHyprLayout.cpp.o CMakeFiles/Hyprland.dir/src/layout/MasterLayout.cpp.o CMakeFiles/Hyprland.dir/src/main.cpp.o CMakeFiles/Hyprland.dir/src/managers/AnimationManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/EventManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/HookSystemManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/KeybindManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/LayoutManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/ProtocolManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/SessionLockManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/ThreadManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/input/IdleInhibitor.cpp.o CMakeFiles/Hyprland.dir/src/managers/input/InputManager.cpp.o CMakeFiles/Hyprland.dir/src/managers/input/InputMethodRelay.cpp.o CMakeFiles/Hyprland.dir/src/managers/input/Swipe.cpp.o CMakeFiles/Hyprland.dir/src/managers/input/Tablets.cpp.o CMakeFiles/Hyprland.dir/src/managers/input/Touch.cpp.o CMakeFiles/Hyprland.dir/src/plugins/HookSystem.cpp.o CMakeFiles/Hyprland.dir/src/plugins/PluginAPI.cpp.o CMakeFiles/Hyprland.dir/src/plugins/PluginSystem.cpp.o CMakeFiles/Hyprland.dir/src/protocols/FractionalScale.cpp.o CMakeFiles/Hyprland.dir/src/protocols/GlobalShortcuts.cpp.o CMakeFiles/Hyprland.dir/src/protocols/Screencopy.cpp.o CMakeFiles/Hyprland.dir/src/protocols/TextInputV1.cpp.o CMakeFiles/Hyprland.dir/src/protocols/ToplevelExport.cpp.o CMakeFiles/Hyprland.dir/src/render/Framebuffer.cpp.o CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o CMakeFiles/Hyprland.dir/src/render/Shader.cpp.o CMakeFiles/Hyprland.dir/src/render/Texture.cpp.o CMakeFiles/Hyprland.dir/src/render/decorations/CHyprDropShadowDecoration.cpp.o CMakeFiles/Hyprland.dir/src/render/decorations/CHyprGroupBarDecoration.cpp.o CMakeFiles/Hyprland.dir/src/render/decorations/IHyprWindowDecoration.cpp.o CMakeFiles/Hyprland.dir/src/wlrunstable/wlr_ext_workspace_v1.cpp.o -o Hyprland  -Wl,-rpath,/home/burak/HyprSource/hyprland-source/subprojects/wlroots/build  -lxcb  -lrt  /home/burak/HyprSource/hyprland-source/subprojects/wlroots/build/libwlroots.so.12032  -lpixman-1  -lOpenGL  -lGLESv2  -lpthread  /home/burak/HyprSource/hyprland-source/ext-workspace-unstable-v1-protocol.o  /home/burak/HyprSource/hyprland-source/wlr-foreign-toplevel-management-unstable-v1-protocol.o  /home/burak/HyprSource/hyprland-source/hyprland-toplevel-export-v1-protocol.o  /home/burak/HyprSource/hyprland-source/hyprland-global-shortcuts-v1-protocol.o  /home/burak/HyprSource/hyprland-source/fractional-scale-v1-protocol.o  /home/burak/HyprSource/hyprland-source/text-input-unstable-v1-protocol.o  /home/burak/HyprSource/hyprland-source/wlr-screencopy-unstable-v1-protocol.o  /home/burak/HyprSource/hyprland-source/subprojects/udis86/build/libudis86/liblibudis86.a  /usr/lib/x86_64-linux-gnu/libwayland-server.so  /usr/lib/x86_64-linux-gnu/libwayland-client.so  /usr/lib/x86_64-linux-gnu/libwayland-cursor.so  /usr/lib/x86_64-linux-gnu/libdrm.so  /usr/lib/x86_64-linux-gnu/libEGL.so  /usr/lib/x86_64-linux-gnu/libxkbcommon.so  /usr/lib/x86_64-linux-gnu/libinput.so  /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /usr/lib/x86_64-linux-gnu/libpango-1.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libcairo.so && :
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/Compositor.cpp.o: in function `CCompositor::vectorToWindowIdeal(Vector2D const&)':
Compositor.cpp:(.text+0x311e): undefined reference to `wlr_xwayland_or_surface_wants_focus'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/Compositor.cpp.o: in function `CCompositor::cleanup()':
Compositor.cpp:(.text+0x86b7): undefined reference to `wlr_xwayland_destroy'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/Compositor.cpp.o: in function `CCompositor::initServer()':
Compositor.cpp:(.text+0xf967): undefined reference to `wlr_gles2_renderer_create_with_drm_fd'
/usr/bin/ld: Compositor.cpp:(.text+0xf9d9): undefined reference to `wlr_gles2_renderer_get_egl'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/events/Misc.cpp.o: in function `Events::listener_readyXWayland(wl_listener*, void*)':
Misc.cpp:(.text+0x666): undefined reference to `wlr_xwayland_set_seat'
/usr/bin/ld: Misc.cpp:(.text+0x6c0): undefined reference to `wlr_xwayland_set_cursor'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/events/Windows.cpp.o: in function `Events::listener_configureX11(void*, void*)':
Windows.cpp:(.text+0xdfd): undefined reference to `wlr_xwayland_surface_configure'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/events/Windows.cpp.o: in function `Events::listener_mapWindow(void*, void*)':
Windows.cpp:(.text+0x86b4): undefined reference to `wlr_xwayland_or_surface_wants_focus'
/usr/bin/ld: Windows.cpp:(.text+0x91d8): undefined reference to `wlr_xwayland_or_surface_wants_focus'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/events/Windows.cpp.o: in function `Events::listener_configureX11(void*, void*)':
Windows.cpp:(.text+0xccc): undefined reference to `wlr_xwayland_surface_configure'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/events/Windows.cpp.o: in function `Events::listener_requestMinimize(void*, void*)':
Windows.cpp:(.text+0x24a3): undefined reference to `wlr_xwayland_surface_set_minimized'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::CHyprXWaylandManager()':
XWaylandManager.cpp:(.text+0x376): undefined reference to `wlr_xwayland_create'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::activateSurface(wlr_surface*, bool)':
XWaylandManager.cpp:(.text+0x531): undefined reference to `wlr_xwayland_surface_try_from_wlr_surface'
/usr/bin/ld: XWaylandManager.cpp:(.text+0x53e): undefined reference to `wlr_xwayland_surface_try_from_wlr_surface'
/usr/bin/ld: XWaylandManager.cpp:(.text+0x54a): undefined reference to `wlr_xwayland_surface_activate'
/usr/bin/ld: XWaylandManager.cpp:(.text+0x557): undefined reference to `wlr_xwayland_surface_try_from_wlr_surface'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::activateWindow(CWindow*, bool)':
XWaylandManager.cpp:(.text+0x5b6): undefined reference to `wlr_xwayland_surface_activate'
/usr/bin/ld: XWaylandManager.cpp:(.text+0x5d1): undefined reference to `wlr_xwayland_surface_set_minimized'
/usr/bin/ld: XWaylandManager.cpp:(.text+0x5e1): undefined reference to `wlr_xwayland_surface_restack'
/usr/bin/ld: XWaylandManager.cpp:(.text+0x5f2): undefined reference to `wlr_xwayland_surface_activate'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::setWindowFullscreen(CWindow*, bool)':
XWaylandManager.cpp:(.text+0xb5f): undefined reference to `wlr_xwayland_surface_set_fullscreen'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::activateSurface(wlr_surface*, bool)':
XWaylandManager.cpp:(.text+0x569): undefined reference to `wlr_xwayland_surface_restack'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::sendCloseWindow(CWindow*)':
XWaylandManager.cpp:(.text+0x931): undefined reference to `wlr_xwayland_surface_close'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::setWindowSize(CWindow*, Vector2D, bool)':
XWaylandManager.cpp:(.text+0xa23): undefined reference to `wlr_xwayland_surface_configure'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/managers/XWaylandManager.cpp.o: in function `CHyprXWaylandManager::moveXWaylandWindow(CWindow*, Vector2D const&)':
XWaylandManager.cpp:(.text+0xb36): undefined reference to `wlr_xwayland_surface_configure'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o: in function `CHyprOpenGLImpl::CHyprOpenGLImpl()':
OpenGL.cpp:(.text+0x72c3): undefined reference to `wlr_egl_get_context'
/usr/bin/ld: OpenGL.cpp:(.text+0x72d9): undefined reference to `wlr_egl_get_display'
/usr/bin/ld: OpenGL.cpp:(.text+0x77e3): undefined reference to `wlr_egl_get_display'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o: in function `CHyprOpenGLImpl::begin(CMonitor*, pixman_region32*, bool)':
OpenGL.cpp:(.text+0x987c): undefined reference to `wlr_egl_get_context'
/usr/bin/ld: OpenGL.cpp:(.text+0x9894): undefined reference to `wlr_egl_get_context'
/usr/bin/ld: OpenGL.cpp:(.text+0x98aa): undefined reference to `wlr_egl_get_display'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o: in function `renderSurface(wlr_surface*, int, int, void*)':
Renderer.cpp:(.text+0x3024): undefined reference to `wlr_xwayland_surface_try_from_wlr_surface'
/usr/bin/ld: Renderer.cpp:(.text+0x3031): undefined reference to `wlr_xwayland_surface_try_from_wlr_surface'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/render/Texture.cpp.o: in function `CTexture::CTexture(wlr_texture*)':
Texture.cpp:(.text+0x55): undefined reference to `wlr_texture_is_gles2'
/usr/bin/ld: Texture.cpp:(.text+0x161): undefined reference to `wlr_gles2_texture_get_attribs'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:164: release] Error 1
make[1]: Leaving directory '/home/burak/HyprSource/hyprland-source'
make: *** [Makefile:191: install] Error 2

**Comment by MightyPlaza** [comment]
Did you change the release version to the current one instead of 0.24.1?

**Comment by vaxerski** [comment]
missing deps.

**Comment by BrkGGM** [comment]
> 

How can I do that?

**Comment by BrkGGM** [comment]
> missing deps.

Which ones are missing?

**Comment by vaxerski** [comment]
No clue, I don't use Kali. (and neither does anyone sane) Some xwayland and egl stuff.
