### ISSUE TITLE
Add support for matching monitors by serial number

### ISSUE THREAD

**Issue by FlavorlessQuark** [hyprwm/Hyprland#2464]
The reason for this is that for people such as me who "share" monitors between different machines (whether it be with an HDMI switch or plug/unplug), the DP of the monitors that are being switched changes after every plug/unplug, which makes it impossible to configure their position and any other related option that requires a DP number.

A more concrete example :
My middle monitor, DP-3, is being toggled to display either my  linux or windows machine. Everytime it gets toggled to windows and then back to linux, its DP changes. DP-3 -> DP-5 -> DP->7 etc..

**Comment by MightyPlaza** [comment]
You can already do that at least for monitor config, don't think you can do that for workspace rules yet.
Also monitor port changing isn't normal, although I don't know why it happens to some people.

**Comment by MightyPlaza** [comment]
this should be fully implemented now @vaxerski
