### ISSUE TITLE
workspace animation not playing with fullscreen windows

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#2465]
I am using the vertical slide workspace effect, and whenever I switch to CS:GO, not other workspaces with fullscreen windows as fas as I have tested AND the window I came from is also fullscreen, the animation doesn't play.
I have a custom brezier curve.
Very minor bug but still.
EDIT: forgot to mention, it doesn't matter if csgo is in fullscreen mode or in windowed fullscreen. I am also NOT playing it through gamescope.

**Comment by jernejmarcic** [comment]
Can you please send me your custom berzier curve, also is the same issue for there steam apps or fullscreen apps?

**Comment by MightyPlaza** [comment]
any updates?

**Comment by izmyname** [comment]
Horizontal swipe animation works with the fullscreened firefox flatpak.
