### ISSUE TITLE
Group windows unexpected behaviour when shifting it to a new workspace

### ISSUE THREAD

**Issue by tvlpirb** [hyprwm/Hyprland#2468]
# Steps to reproduce
Create a group and trying shifting the current group window to a different workspace. Return to the previous workspace and observe.

# Expected outcome
The window should split from the group when moving to a new workspace and the other members of the group should be visible on the previous workspace. Alternatively, the entire group should move to the new workspace.

# Noted outcome
The window doesn't split which causes weird behaviour where the shifted window is on the new space but if you go back to the previous workspace, the other window has disappeared. If you however try moving the focus then the window becomes visible again. It's also possible to crash hyprland when there are three or more windows apart of the group but I haven't been able to reproduce this or get the crash log.

**Comment by vaxerski** [comment]
fixed in cbe9bf0e692010717e3d35e87a9abee79c5f8e4f
