### ISSUE TITLE
2 monitors

### ISSUE THREAD

**Issue by mairm1340** [hyprwm/Hyprland#2469]
HI team I have 2 monitors i.e 1 34 ultra wide and another 32 Dell normal monitor
I totally use 9 Workspace and on dual monitors, sometime one monitor becomes primary and sometimes the other one
I want 34 inch to be primary all the time and secondy to be the other one.
Also when I use monitor 1, some workspaces dynamically opens on second. I want them to be on the same monitor.

I use Xmonad and it works fine there but in Hyperland I am not able to make this work.

I could not make Persistent workspaces as well. Kindly advise.

**Comment by mairm1340** [comment]
hyprctl monitors
Monitor HDMI-A-1 (ID 1):
	2560x1080@144.001007 at 2560x0
	description: LG Electronics 34GL750 0x00029058 (HDMI-A-1)
	make: LG Electronics
	model: 34GL750
	serial: 0x00029058
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-1 (ID 2):
	2560x1600@59.972000 at 5120x0
	description: Dell Inc. DELL U3011 PH5NY242219L (DP-1)
	make: Dell Inc.
	model: DELL U3011
	serial: PH5NY242219L
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

**Comment by mairm1340** [comment]
I wish to have 34GL750 as primary monitor with all work space and secondary monitor as Dell with only 1 or 2 workspace
Mouse cursor should go fro monitor 1 to 2
For some reason I am failing to do this. kindly assist

**Comment by UTFeight** [comment]
Read [this](https://wiki.hyprland.org/Configuring/Monitors/)

**Comment by mairm1340** [comment]
#monitor = HDMI-A-1, preferred,auto,1monitor=HDMI-A-1, 2560x1080@144, 0x0, 1
#monitor=DP-1,  2560x1600@59.9,  2560x1600, 1

I did this configuration based on WIKI and I did something wrong and I need guidance.

**Comment by mairm1340** [comment]
"wlr/workspaces": {
  //"format": "{name}",
  "format": "{name}: {icon}",
  "on-click": "activate",
  "all-outputs": true,
  "sort-by-number": true,
  "format-icons": {
   "1": "WWW  ",
   "2": "CLI  ",
   "3": "FILES  ",
   "4": "TEAMS  ",
   "5": "0365  ",
   "6": "RDP  ",
   "7": "MISC  ",
   "8": "8  ",
   "9": "9  ",
   "10": " 10 "
},

These are the work spaces even though I set monitor 1 as primary 
for some reason teh Dell 2 monitor act as primary

**Comment by UTFeight** [comment]
### For a better response
- You can check [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to learn about code blocks which will make your response prettier.
- The snippet that you sent is a kinda messy so ı will assume your setup contains 2 monitors (as you said on the title) with the following config
```python
# monitor = HDMI-A-1, preferred,auto,1 # **NOTE** I assume this line as commented!
monitor=HDMI-A-1, 2560x1080@144, 0x0, 1
monitor=DP-1, 2560x1600@59.9, 2560x1600, 1
```
### Solution
With that I think it's the *monitor positions*.

> **Note** This is from my personal config
> **I use two monitors with different resolutions**

```python
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=VGA-1,1024x768,0x0,1
monitor=HDMI-A-1,1920x1080,1024x0,1 # 1024x0, not 1024x768. also smaller is prior (on left)
```
***Assuming your both monitors are both 2K***
- Try to change your monitor settings as following

```python
monitor = HDMI-A-1, preferred,auto,1monitor=HDMI-A-1, 2560x1080@144, 0x0, 1
monitor = DP-1, 2560x1600@59.9, 2560x0, 1
```

> **Note** in such case `HDMI-A-1` is treated as main monitor.

**Comment by mairm1340** [comment]
Thanking you kindly
I did paste the config but it was showing error at 2560x1080 so I modified like

monitor = HDMI-A-1, preferred,auto,1
#monitor = eDP-1, preferred, auto, 1 
monitor = DP-1, 2560x1600@59.9, 2560x0, 1

with the above it works as expected except when i login, the mouse cursor traves through Monitor 2--to --monitor 1
how can i fix that...


I expect cursor to move from Monitor1----Monitor2

but currently it is moving from monitor2- monitor1

Thanks again for assisting me

**Comment by UTFeight** [comment]
You are welcome!

If I got that correctly, You want to switch the direction of cursor transition.

### There are two different ways to solve this problem:

- Switch them physically :)

- Switch them in software:
Try to replace your monitor configuration with:

```python
monitor = HDMI-A-1, preferred, 2560x0,1
#monitor = eDP-1, preferred, auto, 1
monitor = DP-1, 2560x1600@59.9, 0x0, 1
```
#### What did I do?
- these `0x0`'es and `2560x1600`'s represent your monitors positions on geometrical plane. (so you can put them in any order as you want. But that only the section which your monitors can display will be shown to you)
- I simply switched these monitors positions.
> **Note** Maybe you can try to but `auto` to your `DP-1` monitor

**Comment by mairm1340** [comment]
This configuration works for me finally.

monitor = HDMI-A-1, preferred, 0x0, 1 
monitor = DP-1, 2560x1600@59.9, 2560x0, 1

I did not understand what is "1monitor=HDMI-A-1,"
Is this to make monitor 1 default ? I could not make that work but finally with the above configuration it works for me now.

Wiki does not tell how to make a particular monitor as primary Or I could not understand that.

**Comment by UTFeight** [comment]
> I did not understand what is "1monitor=HDMI-A-1,"

Oh! So sorry I just copied that from your response and forgot to delete it.
fixed now.

**Comment by mairm1340** [comment]
Thanking you kindly!

**Comment by UTFeight** [comment]
Could you close the issue because it is fixed?

**Comment by Brazlucas** [comment]
> 2560x0, 1

Thank you!!
