### ISSUE TITLE
Cs:go not picking up sens properly

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#247]
I don't know how to adress this, but I am noticing cs:go doesn't pick up small mouse movement when mouse sensitivity is set to a number smaller than 1. I had to set it to 1 to be able to play the game properly, but I'd like it to be lower than 1.

**Comment by vaxerski** [comment]
mhm the constraint patch introduced that. will investigate

**Comment by vaxerski** [comment]
I think the main culprit might be that XWayland doesn't really want to accept deltas < 1. The fix to this would be to disable `general:apply_sens_to_raw` (just committed for it to be off by default) and adjust the sensitivity in-game instead.

For me this fixed everything.

**Comment by EysseW** [comment]
do you mean force_no_accel=1? I had that enabled but it didn't change anything for me. If you mean something else, how do I enable it?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/175016651-c87de7b1-7456-4b54-a7d4-72d2cb0f0428.png)

i mean `apply_sens_to_raw=0` in `general`

**Comment by EysseW** [comment]
I'm sorry, I was planning on testing if it worked but forgot about it. It works beautifully! Thanks!
