### ISSUE TITLE
cursor_inactive_timeout and OS cursor in gaming

### ISSUE THREAD

**Issue by ArtemSmaznov** [hyprwm/Hyprland#2471]
I like having my cursor hide when I am working so I have set a `cursor_inactive_timeout` but with it set I am having it reappear in games which is quite distracting. With variable set to 0 I am not experiencing any problems.

I am not sure if this is related to me using an NVidia GPU (I have followed all the instructions on the wiki as far as I can tell) or maybe just the `env = WLR_NO_HARDWARE_CURSORS,1` or if this is a more widespread issue with AMD as well so it would be nice to have a record in the issue tracker even if this is close as unsupported due to NVidia drivers if that turns out to be the case.

Please let me know if you need more info from me regarding the issue.

---

# Steps to reproduce
1. set `cursor_inactive_timeout = 5`
2. launch a game (tested with subnautica, monument valley and doom eternal via steam)
3. let the cursor disappear while the game is launching
4. wait for in-game cursor to appear
5. move the mouse
# Expected outcome
OS cursor does not appear
# Noted outcome
OS cursor appears alongside the in-game one (sometimes in a different place)
# Note
Opening menus in game seems to hide OS cursor

---

# System info
System: Arch Linux
Release: 6.3.6-zen1-1-zen
GPU: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]
Hyprland version: Hyprland, built from branch  at commit 51a930f802c71a0e67f05e7b176ded74e8e95f87 dirty (). Tag: v0.26.0

**Comment by jernejmarcic** [comment]
At least for me re-entering the game (opening the menu left clicking and exiting) fixes the issue for me

**Comment by Zeioth** [comment]
Sounds to me like that has more to do with the game implementation than hyprland itself. I don't think there is much we can do.

**Comment by ArtemSmaznov** [comment]
I don't think this can be a game issue as I have never had anything like that on xorg while running unclutter. And the cursor is fine when timeout is set to 0.
I believe this is caused either by hyprland or by Wayland itself. Or maybe due to how GPU driver is handled in Wayland. I might try some different Wayland compositor to see if this is isolated to hyprland or to Wayland as a whole.

**Comment by romanstingler** [comment]
I tested this with the latest hyprland-git on CS2, portal, Doom2016, ... the cursor doesn't appear within the game. 
Seems resolved

**Comment by ArtemSmaznov** [comment]
Thanks for letting me know, I have now tried setting it back up and haven't noticed it since. I did change a lot since then though.
