### ISSUE TITLE
Feature: togglable scratchpads

### ISSUE THREAD

**Issue by ArtemSmaznov** [hyprwm/Hyprland#2472]
Thank you for introducing special workspaces.

Are the any plans to introduces scratchpad/special workspace that can be toggled with the same keybinding to show/launch and hide an app? Similar to how qtile and xmonad handle scrachpads?
Example:
`bind = SUPER , grave , togglescratchpad sp-term`
```
if (sp-term.worspace == activeworkspace) {
  sp-term.workspace = special workspace
}
else  {
  if (sp-term is not spawned) {
    exec sp-term.command
  }
  sp-term.workspace = activeworkspace
}
```
sorry I used JS style syntax as that is what I am most familiar with

I find the current implementation very limiting and I believe a lot of people will find this a deal breaker for such a nicely feature compositor.

FYI
Right now [pyprland](https://github.com/hyprland-community/pyprland) tries to achieve this but is not ideal and it would be great to have this supported natively.

**Comment by vaxerski** [comment]
isnt this easily scriptable? Feels like a niche feature

**Comment by ArtemSmaznov** [comment]
I can't speak for everybody but I see this being a niche use case, it's my understanding that this is the primary way how people usually interact with scratchpads, although I guess I could be wrong.
Regarding scripting the functionality, I guess I can try it out. Don't really see how this can be achieved yet.

**Comment by andresilva** [comment]
I guess one possibility for this feature is that the app workspace could be set to floating (which isn't possible now with special workspaces).

**Comment by vaxerski** [comment]
then I'll close this, I don't think it's planned for the core

**Comment by dxrcy** [comment]
If it helps anyone, [this lua script](https://github.com/dxrcy/dotfiles/blob/master/hyprland/.config/hypr/special.lua) offers similar behaviour.
