### ISSUE TITLE
Persistent Desktop that keeps the apps open that you shut down using

### ISSUE THREAD

**Issue by speightashley** [hyprwm/Hyprland#2475]
I read through the documentation and guidelines for bash scripts but couldn't find anything that would be suitable to do what I want to do.

I was previously using a tiling window environment called Material Shell that was build on top of Gnome. We could have a persistent desktop with this so that when we restart, it saves the state of the programs that are open upon shutdown.

Is there a way we can do this with Hyprland?

I've done a workaround with starting my regular applications on different desktops but it's not really the same. I might be working on a specific project and when I restart, it will open VScode without that project in its current state.

**Comment by vaxerski** [comment]
I don't think hyprland can magically understand what every program you use is doing and how to restart it in a way that it comes back to that state. That would be the app's job. 

For me, when I open vs code after a restart it does come back to my last opened state, but it's vs code doing it and not hyprland.

**Comment by speightashley** [comment]
So how about just retaining that apps that were opened upon shutdown?

Let's forget about the state of each application but instead just retaining
the apps that were open in the first place.

Would that be more feasible?

**Comment by vaxerski** [comment]
I think that has already been suggested somewhere. In the meantime you can make a script to do that for you. Hyprland exposes PIDs in `hyprctl clients` which you can use to read `/proc/$PID/exe`, save that, and launch next time you start up hyprland :)

**Comment by speightashley** [comment]
Beautiful. Thanks dude.
Will have a play around with that tomorrow.

**Comment by vaxerski** [comment]
you might also want to check out `/proc/$PID/cmdline` if there are any launch args.

**Comment by speightashley** [comment]
Got it. I'm just reading the man page for proc as we speak to see how I can
do it. I'm sure this would be a common request for a lot of people ya know.

I'll be back once I have something working :-D

Amazing work btw :)

**Comment by mairs8** [comment]
Hey, is it possible to post your solution to this? was trying to do the same thing

**Comment by littleblack111** [comment]
if this not get any attention. then how about allowing a exec when shutting down(like storing info to disk) so at least we can write script ourselves to do so

**Comment by littleblack111** [comment]
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/18

there is a wayland protocol that is awaiting merge that does exactly this

**Comment by littleblack111** [comment]
im currently using hyprsession, which is a very buggy solution
