### ISSUE TITLE
plugin: crash with some function hooks?

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#2479]
I'm attempting to hook Events::listener_readyXWayland and running into crashes when calling the original function out of my hook.

I started with the code from the wiki that hooks listener_monitorFrame and that works fine.

I can't provide a debug core dump because the crash helpfully doesn't occur when Hyprland is a debug build.

I noticed the same behavior if I hook any event listener created with the LISTENER() macro. 

Am I missing something stupid in the hook code?

The hook code looks like this:

```
typedef void (*origReadyXWayland)(wl_listener *, void *);

void hkreadyXWayland(wl_listener *listener, void *data) {
  printf("HK READY %p %p %p\n", listener, data, (void *)(g_pXwaylandReadyHook->m_pOriginal));
	(*(origReadyXWayland)g_pXwaylandReadyHook->m_pOriginal)(listener, data);
  g_pEventManager->postEvent({"xwaylandready", ""});
}

APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
    PHANDLE = handle;


    static const auto XREADYMETHODS = HyprlandAPI::findFunctionsByName(PHANDLE, "listener_readyXWayland");
    printf("SIGNATURE %s %s %p\n", XREADYMETHODS[0].signature.c_str(), XREADYMETHODS[0].demangled.c_str(), (void *)(XREADYMETHODS[0].address));
    g_pXwaylandReadyHook = HyprlandAPI::createFunctionHook(PHANDLE, XREADYMETHODS[0].address, (void*)&hkreadyXWayland);
    printf("READY HOOK %p\n", g_pXwaylandReadyHook);
    g_pXwaylandReadyHook->hook();
    return {"wtf plugin", "srsly", "Zakk", "1.0"};
}

```

[wtfcrash.zip](https://github.com/hyprwm/Hyprland/files/11709742/wtfcrash.zip)
[hyprlandCrashReport416782.txt](https://github.com/hyprwm/Hyprland/files/11709757/hyprlandCrashReport416782.txt)

**Comment by vaxerski** [comment]
does it work if you use a different function?

**Comment by zakk4223** [comment]
works:
listener_mapWindow
listener_monitorFrame

doesn't work:
listener_mouseButton
listener_mouseMove

So far everything I try that's setup in Events.hpp as LISTENER() crashes. all the DYNLISTENFUNC() ones seem to be ok.

**Comment by vaxerski** [comment]
heh, thats why

```
0x000055555584da52 <+16>:	lea    0x30d1bf(%rip),%rax        # 0x555555b5ac18 <g_pInputManager>
```

**Comment by vaxerski** [comment]
I've pushed a commit to actually throw an error instead of crashing. fixing `lea` is for another day. If either one of yall wants to mr, feel free, obviously
