### ISSUE TITLE
`rofi` being tiled

### ISSUE THREAD

**Issue by Kibouo** [hyprwm/Hyprland#248]
Running `rofi -modi drun -show` results it in being tiled. I'm using the default config for both `Hyprland`, i.e. from the examples directory, and `rofi`, i.e. no file on disk.

This is undesired behavior. I expected a floating window on top of all other windows similar to `wofi`, which is being used by the default config.

Unfortunately, `wofi` is no longer being maintained thus my preference for `rofi`. Maybe I am missing an important config? Pretty new to WMs in general.

**Comment by taylor85345** [comment]
You can also use `windowrule=float,rofi` in your hyprland.conf if you're attached to the x11 verision for some reason.

**Comment by Kibouo** [comment]
Thank you for the information and the project!

**Comment by tpkee** [comment]
> You can also use windowrule=float,rofi in your hyprland.conf if you're attached to the x11 version for some reason.
I used to do this too but it doesn't work anymore though

**Comment by vaxerski** [comment]
because rule parsing changed a bit.

open rofi, use `hyprctl clients`, find the rofi entry and note it's class name. (the first name, it should be "window at xxxxx -> classname:" iirc)

then, adjust your windowrule to look like this:
```
windowrule=float,^(classname)$
```
or
```
windowrule=float,classname
```
