### ISSUE TITLE
[Feature] Columns layout for Hyprland

### ISSUE THREAD

**Issue by pranavsetpal** [hyprwm/Hyprland#2480]
I was wondering if it would be possible to implement a columns layout similar to that in Qtile.
The main idea is to have your windows sorted in columns, but unlike Master and Stack, have no fixed amount of them. As you open new tabs, it gets added to the current column and you can move windows up or down or column to column. You can resize each window vertically of the column horizontally. The current implementation of tabbed windows should work well in this layout as well.

I do have a video for demonstration but it a bit old and I'm cannot figure out how to get the link from reddit but you can find it here
https://www.reddit.com/r/xmonad/comments/xolu6n/question_how_to_replicate_qtiles_column_layout_in/ (The 1st one, with qtile caption, is the intended video)

**Comment by vaxerski** [comment]
I don't think any new layouts will be added to the core anymore. Layouts are made pluginable with the plugin API (example: [hy3](https://github.com/outfoxxed/hy3)) and thus I'd prefer that.

There's also a plugin for river's tiling protocol support so if river has that layout it might work via that too.

**Comment by pranavsetpal** [comment]
Oh okay. Unfortunately, there doesn't seem to be any be plugins for such a layout at the moment, and the limitations of [hyprRiver](https://github.com/zakk4223/hyprRiver) are too severe.
I'll explore the possibility of creating my own plugin.

**Comment by vaxerski** [comment]
also wasnt [hyprNstack](https://github.com/zakk4223/hyprNStack) exactly that layout?

**Comment by pranavsetpal** [comment]
Similar but not quite. The hyprNstack layout still follows the master and stack, and as a result, the creation of new windows only happens at the beginning or end of the stack. I don't the columns layout can be created with master and stack as a base.
To take a XMonad example, it is more symbolic to the 'Group.RowOfColumns' layout rather than 'MultiColumns'

**Comment by vaxerski** [comment]
In that case you probably have no other option than to write your own plugin. Thankfully it's not really difficult if you have a bit of C/C++ background

**Comment by pranavsetpal** [comment]
Yes, I'll use the wiki and the current master and stack layout as reference as how to design it. Luckily I am familiar with C as well as OOP so it shouldn;t be hard :)

**Comment by vaxerski** [comment]
if you use discord you can join our discord server and ask questions in `#hyprland-dev` if you need any help or have some questions about the codebase, I answer those most of the time within minutes

**Comment by pranavsetpal** [comment]
I do! Thank you very much :D

**Comment by ArtemSmaznov** [comment]
@pranavsetpal any chance you managed to write anything?

**Comment by pranavsetpal** [comment]
Unfortunately no. I ended up just switching to qtile
