### ISSUE TITLE
per-device config overwrites unchanged options from `input:touchpad`

### ISSUE THREAD

**Issue by lilydjwg** [hyprwm/Hyprland#2483]
I have the following config:

```
input {
  touchpad {
    drag_lock = true
  }
}

device:synps/2-synaptics-touchpad {
  sensitivity = 0.5
}
```

[The doc](https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs) says:

> Per-device config options will overwrite your options set in the `input` section. It’s worth noting that ONLY values explicitly changed will be overwritten.

But drag lock is not enabled for my touchpad (which matches the per-device config). Either removing the per-device config section, or setting `drag_lock = true` in the section, works fine.

(I'm not setting `sensitivity` in `input:touchpad` because it doesn't recognize there.)

**Comment by MightyPlaza** [comment]
```
input {
    touchpad {
        drag_lock = true
    }
    sensitivity = 0.5
}
```

**Comment by lilydjwg** [comment]
@MightyPlaza the intention is to set different sensitivity for touchpad than mouse.

**Comment by MightyPlaza** [comment]
```
input {
     touchpad {
     drag_lock = true
  }
     sensitivity = 1
}

device:synps/2-synaptics-touchpad {
     sensitivity = 0.5
     drag_lock = true
}
```
a bit strange, doesn't seem to happen to other settings though

**Comment by vaxerski** [comment]
oops cfa4086b0b2a2c870504b8f74b6e5b5ba276d1fc
