### ISSUE TITLE
Feature: ability to apply screen shader per monitor

### ISSUE THREAD

**Issue by JManch** [hyprwm/Hyprland#2485]
I have two monitors; one has washed-out colors and the other doesn't. I can fix the washed-out monitor by modifying the gamma using a custom screen shader. However, the shader applies to all monitors so this makes the normal monitor look bad.

Would it be possible to make the monitor number (or global pixel position) accessible in the fragment shader so that color modifications can be applied conditionally?

**Comment by vaxerski** [comment]
7932e425072bd9f57af323d15265b66b2cf139f3

`uniform int output` will contain the monitor id

**Comment by JManch** [comment]
Thanks! Unfortunately I couldn't get it to work though. I've found that the `shader->output > 0`  condition is preventing `output` from being updated.
https://github.com/hyprwm/Hyprland/blob/10fd75c8335736b1a0dcb3830a5b8c2367a02e61/src/render/OpenGL.cpp#L609-L610
Changing it to `shader->output != -1` fixes it.
