### ISSUE TITLE
Switching between maximized windows is flickering

### ISSUE THREAD

**Issue by lilydjwg** [hyprwm/Hyprland#2487]
Disable animation. Open two windows on the same workspace and maximize them with `fullscreen,1`. Then try to switch between them. The switching-to window is always half and then resize to maximum, causing flickering:

https://github.com/hyprwm/Hyprland/assets/440661/797140e6-5746-4a61-9736-ad9d9ae956a2

**Comment by vaxerski** [comment]
that's just the browser taking a while to re-render its content, this falls under #683

**Comment by lilydjwg** [comment]
So there can't two maximized windows at the same time, but the windows resize back and forth when I switch?
