### ISSUE TITLE
Fullscreen deactivation when exiting fullscreen video

### ISSUE THREAD

**Issue by vitek-borovsky** [hyprwm/Hyprland#2491]
When I have my window (browser) in fullscreen mode and I open video (like yt video but happens with any video) in fullscreen, after exiting the video fullscreen (both with escape and doubleclick) the browser itself stops being fullscreen. 

BTW: I'm using NVIDIA

**Comment by MightyPlaza** [comment]
Works on firefox, so you might want to specify the browser.

**Comment by MightyPlaza** [comment]
@vaxerski should this be closed?

**Comment by vaxerski** [comment]
ya

**Comment by ruchir-k** [comment]
facing the same issue on chromium based browser, is there a fix for this?
