### ISSUE TITLE
Weird behavior of floating window in special workspace

### ISSUE THREAD

**Issue by imxyy1soope1** [hyprwm/Hyprland#2492]
# How to reproduce
1. Open a window and set it floating
2. Use a key binding to move it to the `special` workspace such as `bind = SUPER, H, movetoworkspacesilent, special`
3. Switch to the `special` workspace by a key binding or `hyprctl`
4. Use mainMod + LMB to drag the window to another monitor
There will be some weird graphical tearing on the screen

**Comment by vaxerski** [comment]
special workspace is not supposed to have floating windows atm generally all issues fall under #827

**Comment by imxyy1soope1** [comment]
urr my fault I didnt search for a dup issue. thank for reply!
