### ISSUE TITLE
Scaling issue on wofi

### ISSUE THREAD

**Issue by DaniAndTheWeb** [hyprwm/Hyprland#2500]
Starting with commit b540d28 every time that I try to focus wofi it crashes with this error: 
`Gdk-Message: Error flushing display: Resource temporarily unavailable`
If I just use the keyboard once wofi is launched without touching the mouse at all the program doesn't crash and works as expected.

The issue is only present when using a scaling on the display other than 1, without any scaling the issue doesn't appear at all.

**Comment by DaniAndTheWeb** [comment]
It outputs this almost infinite repeating strings that ends with the wofi error when I move the cursor:
```
[  22686.710] wl_surface@25.leave(wl_output@35)
[  22686.712] wl_surface@25.leave(wl_output@18)
[  22686.714] wl_surface@25.enter(wl_output@35)
[  22686.715]  -> wl_pointer@20.set_cursor(897, wl_surface@25, 0, 1)
[  22686.717]  -> wl_surface@25.attach(wl_buffer@41, 0, 0)
[  22686.719]  -> wl_surface@25.set_buffer_scale(1)
[  22686.721]  -> wl_surface@25.damage(0, 0, 32, 32)
[  22686.722]  -> wl_surface@25.commit()
[  22686.724] wl_surface@25.enter(wl_output@18)
[  22686.726]  -> wl_pointer@20.set_cursor(897, wl_surface@25, 0, 0)
[  22686.729]  -> wl_surface@25.attach(wl_buffer@44, 0, 0)
[  22686.731]  -> wl_surface@25.set_buffer_scale(2)
[  22686.733]  -> wl_surface@25.damage(0, 0, 24, 24)
[  22686.735]  -> wl_surface@25.commit()
``` 
```
Gdk-Message: 12:16:00.349: Error flushing display: Resource temporarily unavailable
```

**Comment by vaxerski** [comment]
that was fixed with https://github.com/hyprwm/Hyprland/commit/91fbee24da21da058e7a31ddc5900f37a1e91c12

**Comment by exoess** [comment]
i'm still getting this error

**Comment by LU15W1R7H** [comment]
yes this problem seems to be back

**Comment by vaxerski** [comment]
it's tracked elsweyr I forgot issue #

**Comment by 42Willow** [comment]
I thought it was a me issue :sweat_smile:. Where is this issue being tracked? Otherwise could this please be reopened - I'd like to be notified after the fix as it means I have to use rofi.

**Comment by vaxerski** [comment]
#3729

**Comment by CountMurphy** [comment]
Problem just started for me today.  Any scaling  over 1 and wofi crashes. Could this be reopened?

**Comment by Indyandie** [comment]
> Problem just started for me today. Any scaling over 1 with focus and wofi crashes. Could this be reopened?

@CountMurphy Using `wofi` with `--normal-mode` should do the trick. [more info](https://github.com/hyprwm/Hyprland/issues/3729#issuecomment-1817642755)

**Comment by 42Willow** [comment]
@CountMurphy The commit https://github.com/hyprwm/Hyprland/commit/9e2b939024448d64df6af1f5d2ea5ceee078a539 fixes the issue. You should get the update soon (if you haven't already by now).
