### ISSUE TITLE
Void Linux

### ISSUE THREAD

**Issue by kobzar** [hyprwm/Hyprland#2502]
Please, add suppoert for void linux. 
The main problem is void dont use systemd
So, try to run Hyprland return error like

Hyprland: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory

Thanks

**Comment by MightyPlaza** [comment]
Compile with "NO_SYSTEMD" flag with the instructions on the wiki.
http://wiki.hyprland.org/Getting-Started/Installation/#custom-installation-legacy-renderer-etc

**Comment by MightyPlaza** [comment]
As said in the error you have old versions of needed dependencies. Build an older version of hyprland or get a newer version of the package.

**Comment by kobzar** [comment]
I am so sorry. 
where and how i can find/get version for 1.21  wayland?

**Comment by NotAShelf** [comment]
...from your distro's repositories, where else?

**Comment by MightyPlaza** [comment]
On void you make have to build the dependency tree from source or with another package manager. Or use an older version of hyprland
