### ISSUE TITLE
Cursor doesn't hide even if cursor inactive timeout set

### ISSUE THREAD

**Issue by glyh** [hyprwm/Hyprland#2505]
Arch Version: Linux arch 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux
Hyprland log: [here](https://pastebin.ubuntu.com/p/VP5HVRNn2v/)

To reproduce: on arch use hyprland with the following [config](https://pastebin.ubuntu.com/p/FcBSJdPwkn/)

Initially the cursor is hidden, but moving windows around seems to affect the focus of the cursor and thus waking up the cursor showing it up. After that the cursor no longer disappears.

**Comment by ALizarazoTellez** [comment]
I see you have an error in your configuration, maybe you missed a `=` sign (line 77).

**Comment by glyh** [comment]
Sry, my bad.

**Comment by glyh** [comment]
No the issue still persist even if I fix the syntax.
