### ISSUE TITLE
interact with tabbed containers using the mouse

### ISSUE THREAD

**Issue by kevenwyld** [hyprwm/Hyprland#2509]
Would it be possible to add the ability to click on tabs in tabbed layout containers and to use the scroll wheel to switch between tabs when the mouse is over them?  Similar to how you can interact with tabbed/stacked layouts in i3.

Sorry if this is already a thing, I couldn't find it anywhere in open issues or the wiki.  I think if I bound `changegroupactive b` and `changegroupactive f` to the mouse wheel it would work but then it works everywhere, not just above the tabs.

Thanks for all your hard work on this project!  I'm really enjoying using it.

**Comment by MightyPlaza** [comment]
https://discord.com/channels/961691461554950145/961691461554950148/1117752695038693467
https://github.com/hyprwm/Hyprland/pull/2503
https://github.com/outfoxxed/hy3

**Comment by MightyPlaza** [comment]
The discord link I sent is the creator of the plugin doing exactly what you want to do. Discord might be messing up the link, wouldn't be surprised.
The pull request is related to the solution.
i find it strange that the plugin doesn't allow you to switch monitors, never used it though.
If you can't make the link work search on the hypr discord for "from: outfoxxed#8737 has: video" and it's the first post.

**Comment by kevenwyld** [comment]
> i find it strange that the plugin doesn't allow you to switch monitors, never used it though.

There is a PR for it https://github.com/outfoxxed/hy3/pull/5 .  Not sure when it will get merged though.

> If you can't make the link work search on the hypr discord for "from: outfoxxed#8737 has: video" and it's the first post.

Ahh, found it, thanks!  Yes that looks like exactly what I want.  I wonder if I can use `hy3:focustab` without using the whole layout.  I will try it.

**Comment by kevenwyld** [comment]
Yeah, I tried it and using the layout is necessary for focustab to work.

I think, even without the comparison to i3, this would still be a good feature for hyprland core to support (in my opinion of course).  There are many other functions like dragging windows and moving them in and out of containers which can already be done with the mouse.  And nearly all of the workspace bar implementations allow "scrolling" to switch between workspaces when on top of the workspace list using `workspace m+1` and `workspace m-1`.  So this seems like a continuation of those other mouse based features.

Maybe I'll try to sweep the quite deep pile of dust off my C++ knowledge and attempt a PR.

**Comment by MightyPlaza** [comment]
done in b10cae3010f5b1d853eb13f8a591ee10d67fe51e
