### ISSUE TITLE
Plugin config values stay as default until end of PLUGIN_INIT

### ISSUE THREAD

**Issue by hurutparittya** [hyprwm/Hyprland#2510]
I've noticed that config values created whit HyprlandAPI::addConfigValue keep their default value in PLUGIN_INIT and in all functions called directly from PLUGIN_INIT. I'm not sure if this is the intended behavior or not, but I've seen plugins made by others also make the assumption that it should work. They work fine when called from functions triggered by events or in PLUGIN_EXIT.

How to reproduce:

1. Set the value in config:

`plugin {`
`    foo {`
`        bar=something`
`    }`
`}`

2. Do this inside of PLUGIN_INIT:

`HyprlandAPI::addConfigValue(PHANDLE, "plugin:foo:bar", SConfigValue{.strValue = STRVAL_EMPTY});`
`HyprlandAPI::reloadConfig();`
`HyprlandAPI::addNotification(PHANDLE, g_pConfigManager->getConfigValuePtrSafe("plugin:foo:bar")->strValue, CColor{0.f, 1.f, 1.f, 1.f}, 5000);`

**Comment by hurutparittya** [comment]
Ah I see. I assumed it was caused by recent breakage because multiple plugins I looked up as a reference did in fact use variables in PLUGIN_INIT and annoyingly ignored my configuration changes. 

I haven't looked at the hyprwm code very closely yet, but I hope there is an easy and straightforward way to correct this oversight. Alternatively introducing a "plugin initialized" event that is called after PLUGIN_INIT when the config values are ready could be a viable workaround.

**Comment by zakk4223** [comment]
I ended up having to hook CConfigManager::loadConfigLoadVars to get around this for one of my plugins. You can kinda use it as a crappy way to do stuff in plugin init. add the variable, call the reload config function, hook the above function and then do whatever you need to in the hook (after calling the original function). Then just unhook the function.

Which is probably not a bad suggestion for a hookable event: "configreloaded". Might even be useful as an IPC event too.

**Comment by vaxerski** [comment]
event da7ea2b33d232ff54645b6de58663934e38eff67
fixed in 0c61a1530f2da2571e8285df106b31af73843411
