### ISSUE TITLE
Screen capture low performance

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#2515]
when using 
`wf-recorder -f  x.mp4` 
the fps drops very low.

Found in https://github.com/hyprwm/Hyprland/issues/2501#issuecomment-1589548427
https://github.com/hyprwm/Hyprland/issues/2501#issuecomment-1589915169

Maybe Screencopy dmabuf could be worth a look
https://github.com/swaywm/wlroots/pull/2133/files

**Comment by vaxerski** [comment]
Hyprland already supports dmabuf since a while back. It might be a dt issue

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11745261/patch.txt)

try this patch

**Comment by romanstingler** [comment]
https://github.com/hyprwm/Hyprland/assets/5576250/688e0142-531f-4d2e-9718-e56164df2fdc

Unfortunately, I still have stuttering

**Comment by russelltg** [comment]
I have the same issue with wf-recorder--I wrote an alternative that works much better for me. Only works on Intel and AMD hardware: https://github.com/russelltg/wl-screenrec

**Comment by vaxerski** [comment]
closing, not a hl issue
