### ISSUE TITLE
Invalid keyboard layout passed

### ISSUE THREAD

**Issue by Erothas** [hyprwm/Hyprland#2516]
That is the error I started getting with my first boot of my day today. Everything has been working for months up until now. I haven't played around or even touched my settings as well.

- Steps to reproduce
```
input {
    kb_layout = dvorak
    kb_options = caps:backspace
}
```
`localectl set-keymap dvorak` and `loadkeys dvorak` do not do anything either.

It is also worth noting that I tried a few other generic layouts. The only two that worked were 'us' and 'de'??? 'Azerty' and 'uk' do not work for example...

-  Noted outcome

Hyprland defaults back to (us) qwerty. Consequently, this issue took me 15 minutes to create because I forgot most of my qwerty muscle memory. Free me from this pain :(

**Comment by vaxerski** [comment]
dvorak is a variant no?

**Comment by Erothas** [comment]
> dvorak is a variant no?

Would you look at that... problem fixed.

But why has it consistently worked for all these months, until it decided enough is enough today? :D Oh well, thanks!

**Comment by Erothas** [comment]
> dvorak is a variant no?

Would you look at that... problem fixed.

But why has it consistently worked for all these months, until it decided enough is enough today? :D Oh well, thanks!
