### ISSUE TITLE
Screenshots and screensharing both broken on scaled+rotated display

### ISSUE THREAD

**Issue by Avnzx** [hyprwm/Hyprland#2518]
Confused as I used to be able to screenshot. Running an RX570. Rendering is normal it is just screenshots and screensharing that are broken.

Normal config for all the monitors:

```
monitor=,preferred,auto,1
monitor=DP-1,highres,1080x400,2,bitdepth,10
monitor=DP-3,preferred,0x0,2
monitor=HDMI-A-1,preferred,3000x0,1
monitor=DP-3,transform,3
monitor=HDMI-A-1,transform,1
```
monitors were both moved (in the X axis) and scaled when I mention that the displays were scaled (to keep them contiguous)

![allnormalscaling](https://github.com/hyprwm/Hyprland/assets/59203114/7890ac11-f4f1-4471-a54b-ed861a0e2201)
^ All displays with their preferred resolution and scale set to 1x (left and middle are 4k, right is 1080p)

![leftscaled](https://github.com/hyprwm/Hyprland/assets/59203114/81a41eb6-4fd7-4c9f-9f76-350b32aba5d9)
^ Only the left monitor scaled to 2x

![leftmiddlescaled](https://github.com/hyprwm/Hyprland/assets/59203114/ce6b4b59-9d6d-4faf-b2da-f90f27043a40)
^ Both the left and middle monitor scaled to 2x

All of the screenshots were taken using `grim -`. 

Attempting to record the screens via `wf-recorder` appear to have the same results as the screenshots. i.e. left display is cut off, middle display is completely black (wf-recorder also **always** says `Application provided invalid, non monotonically increasing dts to muxer in stream 0:` when recording this display) , right display works perfectly.

**Comment by MightyPlaza** [comment]
Your normal config doesn't look normal to me.
`monitor=DP-1,3840x2160@60,1080x400,2
monitor=DP-3,3840x2160@60,0x0,2,transform,3
monitor=HDMI-A-1,preferred,3000x0,1,transform,1`
fixed it, resolutions might be wrong though
Also screen sharing (not sure about screen shoting) doesn't work on 10 bit displays.

**Comment by Avnzx** [comment]
> Also screen sharing (not sure about screenshotting) doesn't work on 10 bit displays.

Yeah disabled 10 bit and the middle monitor works fine now, thanks!

Changed over to that form of config (though I'm not sure why this would do anything differently? isn't preferred just the implicit way of declaring these?):
```
monitor=,preferred,auto,1
monitor=DP-1,3840x2160@60,1080x400,2
monitor=DP-3,3840x2160@60,0x0,2,transform,3
monitor=HDMI-A-1,1920x1080@60,3000x0,1,transform,1
```

And the left monitor still has that same issue

**Comment by Avnzx** [comment]
Seems like this is an issue with rotated+scaled displays.

Removing either the `scale,2` or `transform,3` from the left monitor fixes it

**Comment by MightyPlaza** [comment]
Yes I prefer defining the resolutions.
Also why do you have this line in there?
```
monitor=,preferred,auto,1
```

**Comment by Avnzx** [comment]
pretty sure that's just the default, only affects the placement of non-explicitly declared monitors

**Comment by Avnzx** [comment]
> Seems like this is an issue with rotated+scaled displays.
> 
> Removing either the `scale,2` or `transform,3` from the left monitor fixes it

Different transforms change the way it's broken..... 0 appears normal, the rest all only show 1/2 of the screen

**Comment by MightyPlaza** [comment]
The issue seems related to scaling not transform.
Also managed to repro.

**Comment by Avnzx** [comment]
Yeah confirmed on another device it's just grim, hmmm. As OBS seems to work fine irrespective

**Comment by Avnzx** [comment]
Yeah can repro on another device as well (hyprland as well)

This seems like it might be a hypr issue? Grim works fine with transformed+scaled displays with SwayWM
