### ISSUE TITLE
graphical glitch when switching windows in group

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#2519]
Latest master seems to have introduced graphical glitches when switching windows in a group. See recording

https://github.com/hyprwm/Hyprland/assets/208711/102d7422-045e-4c52-aed5-2fdd482af4c1

**Comment by MightyPlaza** [comment]
config?

**Comment by vaxerski** [comment]
ok

**Comment by vaxerski** [comment]
fixed c4dec4f79697cb789b585f8e4febf92e929b5291

**Comment by primalmotion** [comment]
thanks!
