### ISSUE TITLE
Warpd not working

### ISSUE THREAD

**Issue by glyh** [hyprwm/Hyprland#2522]
To reproduce: 
1. install waprd along with hyprland
2. run warpd --hint

Expected: warpd show up tags that I may trigger

Actual: [destroyed object]: error 4: surface was destroyed before its role object

**Comment by theoparis** [comment]
I have the same issue with https://github.com/moverest/wl-kbptr 👀

**Comment by glyh** [comment]
@abhinav3398 doesn't help.

**Comment by abhinav3398** [comment]
Oh my bad! Didn't see your error message. Your error is different than what I was getting. I'm curious as to how did you install warpd? For me, I used [warpd_wayland_git](https://aur.archlinux.org/packages/warpd-wayland-git)

**Comment by glyh** [comment]
I reinstall warpd-git instead of warpd on Arch, it's working for me now. Thanks

**Comment by rraafays** [comment]
hi, i still have this problem on nixos to this day :-(

**Comment by kanielrkirby** [comment]
Only thing that's worked for me (NixOS, Hyprland) is running `warpd` commands as `sudo`, but it's still buggy as hell.

**Comment by bluedeep** [comment]
I made hyprwarp(https://github.com/bluedeep/hyprwarp), which works well on Hyprland instead of warpd, completely simulating the mouse with the keyboard
