### ISSUE TITLE
[Wiki] Fix typo on Master Configuring page and sort dispatcher list on Advanced Configuring page alphabetically

### ISSUE THREAD

**Issue by squidgyberries** [hyprwm/Hyprland#253]
As I currently cannot make changes or pull requests for the wiki I just put this in an issue.

There's a typo on the Master Configuring where "and example" should be "an example".

I also think it would be beneficial for the dispatcher list on the Advanced Configuring page alphabetically for easier navigation.

**Comment by vaxerski** [comment]
> I also think it would be beneficial for the dispatcher list on the Advanced Configuring page alphabetically for easier navigation.

No, they are grouped by usefulness and meaning (e.g. moveactive next to resizeactive)

> There's a typo on the Master Configuring where "and example" should be "an example".

Thank you, fixed.
