### ISSUE TITLE
Crash on xwayland wine games

### ISSUE THREAD

**Issue by jocelynthode** [hyprwm/Hyprland#2531]
# Steps
## Steps to reproduce
- Run a game like Street Fighter 6. I was also able to reproduce the same issue Running Diablo 4 via Lutris.

## Expected outcome
- Game works as usual
    
## Noted outcome
- After some time or input in the game the whole display freezes and Hyprland crashes shortly after

# Logs and Config
**Hyprland Logs**

https://gist.github.com/jocelynthode/81c0b674789b706ef21247ee64f3cad4

**Hyprland Config**

https://gist.github.com/jocelynthode/b1047d02581157a31bc03ce17d988fb5

**Hyprland Crash Report**

https://gist.github.com/jocelynthode/45459cf410765b1863875a00653b85aa

Not sure if I'm doing something wrong, there. Let me know if you need more information.

**Comment by izmyname** [comment]
Is this still actual?

**Comment by jocelynthode** [comment]
No, it was actually my GPU that was drawing too much frow my PSU. Setting a power limit fixed it.

**Comment by vaxerski** [comment]
I chuckled
