### ISSUE TITLE
Unable to set col.active_border from config

### ISSUE THREAD

**Issue by Slime90** [hyprwm/Hyprland#2534]
I have tried multiple formatting types for the color (rgb, rgba, etc), and I am unable to set the active border color from the configuration, even though the same color sets successfully with hyprctl. 

```
❯ hyprctl version
Hyprland, built from branch  at commit v0.26.0  ().
Tag: ?

flags: (if any)
debug
```

General config section (Unsuccessful)
```
      general {
          # Gaps and border
          gaps_in = 4
          gaps_out = 8
          border_size = 2
          resize_on_border = true
          extend_border_grab_area = 50

          # Fallback colors
          col.active_border=0xFFF6D56A
          col.inactive_border=0x00000000

          # Functionality
          # resize_on_border = true
          layout = dwindle
      }
```

Setting the same color with hyprctl
```
hyprctl keyword general:col.active_border 0xFFF6D56A
```

**Comment by romanstingler** [comment]
works perfectly fine.
![image](https://github.com/hyprwm/Hyprland/assets/5576250/22964009-4478-48c8-aa49-eba6cff47770)

maybe you give more context, which distro and maybe try building the latest git 
and if still persists provide your config

**Comment by Slime90** [comment]
Apologies, I missed a sourced config file with defaults, which resulted in the base config items I set being overridden. Closing.
