### ISSUE TITLE
Plugin: getting data from a monitor (g_pCompositor->m_vMonitors) throws segfault

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#2536]
I'm using this plugin: https://github.com/Duckonaut/split-monitor-workspaces

Since [this commit](fbabb105c3427fbbce4dfc3ea9701ba473298206), accessing data from a monitor ([example](https://github.com/Duckonaut/split-monitor-workspaces/blob/main/src/main.cpp#L67)) crashes Hyprland entirely. Even just printing `std::cout << monitor << std::endl;` will crash it.

### Steps to reproduce:

1. Checkout this commit: fbabb105c3427fbbce4dfc3ea9701ba473298206
2. Use a plugin that accesses `g_pCompositor->m_vMonitors`, and make it access one of the monitors
3. Start Hyprland with the default config. Load the plugin in the config, or manually through hyprctl plugin load.

### Expected outcome
The plugin should work the same as it does with the parent commit fbabb105c3427fbbce4dfc3ea9701ba473298206

### Noted outcome
The plugin crashes Hyprland when loading the plugin.

### Log
(from a nested debug build of that commit, running through vscode)

[hyprlandCrashReport394375.txt](https://github.com/hyprwm/Hyprland/files/11778668/hyprlandCrashReport394375.txt)

**Comment by zakk4223** [comment]
The plugin will need to be rebuilt. Double check you are building it against the correct source tree/headers. I had the exact same crash until I did so. Once I sorted that out the plugin works fine. 

A variable was added to g_pCompositor, so any plugin that directly access members of that class needs rebuilding.

**Comment by zjeffer** [comment]
Thanks for the suggestion. I followed the manual installation from the readme of that plugin. Sadly, even after a completely clean rebuild of both Hyprland and the plugin it still crashes with the same segfault.

**Comment by zjeffer** [comment]
Interestingly, it does run fine when I build Hyprland's debug build with vscode's debug tools, instead of `make debug`. In both cases, I launch Hyprland using the provided launch.json file from the examples directory.

**Comment by zjeffer** [comment]
I managed to make it work:

1. Fully clean the Hyprland repo
2. Fully clean the plugin repo
3. `sudo make pluginenv` in the Hyprland repo
4.  `make debug` in the Hyprland repo
5. `make install` in the plugin's repo

Now it seems to work again.
