### ISSUE TITLE
why change scale is still blurry after patch

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#2538]
I've patched the source code and rebuilt it .why it doesn't work?
![image](https://github.com/hyprwm/Hyprland/assets/30348075/9c6d3fac-e9f4-4abd-a821-316594331657)
![image](https://github.com/hyprwm/Hyprland/assets/30348075/a1ca17f3-bbac-4b44-920a-e4c12e1b3a0f)

I use ubuntu23.04.  the source version is v0.24.0

**Comment by Bryan2333** [comment]
I'm not using NixOS but Arch Linux. I can share my experience about dealing with xwayland app with you.

1. Installed `xorg-xrdb` and `xsettingsd`. (change the package name accordingly)
2. create configuration file `.config/xsettingsd/xsettingsd.conf` if not exists and put the content below to it
   ```
   Gdk/UnscaledDPI 98304
   Gdk/WindowScalingFactor 2
   ```
3. write a script, put the content below to it and make it executed on startup
    ```
    #!/bin/bash
    systemctl --user start xsettingsd.service
    echo "Xft.dpi: 192" | xrdb -merge
    xprop -root -format _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
    ``` 
4. set the correct cursor size of each xwayland app in desktop file. In my case, I have to double the cursor size.
