### ISSUE TITLE
Hyprland segfaults, crashes when opening WebCord

### ISSUE THREAD

**Issue by Nekosis** [hyprwm/Hyprland#2542]
# Hyprland log, configuration file, and crash report
Hyprland log, config, and crash report in this archive: [hyprlandcrash.tar.gz](https://github.com/hyprwm/Hyprland/files/11780383/hyprlandcrash.tar.gz)

# Steps to reproduce
1. Boot the computer, or restart it if it is already booted
2. Log into a Hyprland session (SDDM is installed and enabled on this machine)
3. Wait for an amount of time (if you open WebCord too early it will not cause this issue)
4. Open [fuzzel](https://codeberg.org/dnkl/fuzzel) with keybind
5. From fuzzel, launch the [WebCord](https://github.com/SpacingBat3/WebCord) Flatpak

# Expected outcome
WebCord starts.

# Noted outcome
Hyprland will hang for a few seconds before segfaulting, crashing, and throwing back to SDDM. WebCord does not start.

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by izmyname** [comment]
Can't repro, was also using fuzzel with webcord flatpak - both xwayland and wayland native. All worked fine.
