### ISSUE TITLE
Rotate window

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#255]
If you could add the funny haha window rotation from wayfire that would be wholesome 100 morbius among us moment

https://youtu.be/Bv7Zx-BDC7M

**Comment by vaxerski** [comment]
no, useless and the renderer is not made for that

**Comment by ThatOneCalculator** [comment]
But I want my windows to go ***speeeeeeeeeeen***

![spamton-spin.gif](https://user-images.githubusercontent.com/44733677/175357616-dc42520e-d537-43ef-ac7c-c0a5dca9a3b0.gif)

**Comment by Vaisakhkm2625** [comment]
Actually this would be a nice feature to have, possibly as plugin, 

like for reading things or seeing images that rotated rotated 90 degree...

i know this can be done in various image viewer, pdf viewer etc, but
if we could bound this as a feature of composite itself, we could have it has a universal bound 

i am only telling about 90,180,270 degrees...

**Comment by ThatOneCalculator** [comment]
Wow the brainrot 2 years ago was real.... 3D rotating windows would still be funny though

**Comment by Vaisakhkm2625** [comment]
> Wow the brainrot 2 years ago was real.... 3D rotating windows would still be funny though

XD this is how we bring people to linux from windows

**Comment by vaxerski** [comment]
you can make a plugin to do this

**Comment by Vaisakhkm2625** [comment]
> you can make a plugin to do this

actually i am currently learning cpp(learned years ago in school but only basics)... to contribute to hyprland... and hopefully develop in the future..

**Comment by williamtorres64** [comment]
And here I am, 4 years later, looking for a way to rotate my chrome window just so I can see an image upside down
