### ISSUE TITLE
Visible cursor offset

### ISSUE THREAD

**Issue by Zettexe** [hyprwm/Hyprland#2551]
The visible cursor is always slightly offset by a couple pixels and sometimes its offset by something like ~10px. This happens in both x and y directions. I have disabled hardware cursors with WLR_NO_HARDWARE_CURSORS=1 as the cursor does not render without it.

**Comment by vaxerski** [comment]
can't repro

**Comment by Zettexe** [comment]
After some further investigation the bigger offset appears to happen when focusing on windows. As far as I can tell its only happening the first time the cursor focuses on the window and any subsequent times it works as expected.

**Comment by vaxerski** [comment]
cursors are handled by the client (and wlroots)

**Comment by ktufekcic** [comment]
I'm also seeing a similar issue, but in my case, no matter how many times I focus a window, it's always offset by 5-10px either top left or bottom right, and this also seems to only be affecting my second monitor

**Comment by xiyori** [comment]
Can confirm, happens to me as well in every window. Only affects my desktop PC with 4k monitor and 2x scaling. 1080p laptop with 1.25 scaling works fine

**Comment by izmyname** [comment]
Still a thing?

**Comment by izmyname** [comment]
Prolly worth closing. Whoever faces this problem will, most likely, open an issue for this, anyway.
