### ISSUE TITLE
[force_zero_scaling] Menus are initially scaled, then eventually get de-scaled

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2552]
Thanks so much for adding this as an official option! Although it seems to work fine for most programs, I have consistently had issues with pop-up windows such as right click menus or dropdowns (Steam, GeoGebra, Android Studio).
The pop-up is initially blurry and too big, as if it were getting scaled up by Hyprland. There are also damage tracking issues when in this state. Sometimes it returns back to normal if I wait long enough. Manually dragging the popup also fixes it. I have not observed anything seemingly relevant in the logs, but happy to provide them if helpful. I have attached a video showcasing the issue.

https://github.com/hyprwm/Hyprland/assets/44881120/963be36d-6916-4de3-8eb8-6924007a022f

**Comment by TheSunCat** [comment]
I also noticed the position of popups gets offset from where they should be, by a larger amount the further right the popup is meant to be. Is the offset maybe getting multiplied by my scaling factor (1.25)?

https://github.com/hyprwm/Hyprland/assets/44881120/01e32645-a039-43b5-abd6-aa1cb717516b

**Comment by yeheng282** [comment]
I also encountered some problems, In the xwayland window, the right and bottom areas, the mouse cursor cannot be operated.  please see the video below

https://github.com/hyprwm/Hyprland/assets/98092393/6ce548e1-fd4a-4455-8a5c-ec6de70c4cd2

**Comment by TheSunCat** [comment]
I can reproduce this, but only with larger window sizes. Clicking too low or to the right seems to clamp the click position up or left. Making a window small enough seems to get rid of this (or reduce it to the point of basically not happening).

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11817004/patch.txt)

try this patch

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11819917/patch.txt)

try this :)

**Comment by TheSunCat** [comment]
Hrm, position still has issues, and the lower part of the window is still inaccessible at certain sizes (you can see me try to interact with the input bar). If you need to test locally, this is a fairly small package in the AUR (`geogebra-5`), though I am happy to help with testing if it's easier for you

https://github.com/hyprwm/Hyprland/assets/44881120/8d910b94-0e3a-4fb1-b9ed-b848464da416

.

**Comment by vaxerski** [comment]
it would be generally helpful if wlroots had a method to force a specific scale to xwayland, bugs like these seem like unsolvable to me with the current "hack" of an implementation

**Comment by vaxerski** [comment]
I will commit the patch for now as it fixes some issues but the position and input might be unsolvable

**Comment by vaxerski** [comment]
check w/ 40e33719c3ed044afe328d00ab08a735ae73e638

**Comment by TheSunCat** [comment]
Can confirm it seems to work now! Menus for both GeoGebra and Steam appear in the correct place with correct scaling (and crisp!), and the bottom and right side of clients is clickable even in fullscreen. I'll close the issue now, thank you!

**Comment by cheloveg** [comment]
> check w/ [40e3371](https://github.com/hyprwm/Hyprland/commit/40e33719c3ed044afe328d00ab08a735ae73e638)

GitHub says, that this commit does not belong to any branch on this repository, and the issue with clicking on lower parts of window still persists on my version of Hyprland (hyprland-0.41.1 from nixos-24.05), will this patch ever be merged to upstream?
