### ISSUE TITLE
"Communication with the local password server failed" when using Dolphin

### ISSUE THREAD

**Issue by AtlasC0R3** [hyprwm/Hyprland#2554]
An issue I am having with Dolphin, the KDE file manager, is seen whenever I attempt to connect to a network share that has credentials stored presumably in KDE Wallet.

Steps to reproduce:
1. Open Dolphin
2. Connect to a network share (SMB, SFTP, FTP...) that requires authentication
A Samba share with locked folders works too.
3. "Communication with the local password server failed" appears, at which point it has entirely failed to ask the user to authenticate at all.

The CLI outputs this:
```
kf.kio.core: Can't communicate with kiod_kpasswdserver (for queryAuthInfo)!
kf.kio.core: "Communication with the local password server failed"
```
...whereas the expected outcome is for it to communicate with Wallet, fetch the credentials in there and let the user carry on unabated.

I'm unsure if it's a KDE issue or a Hyprland issue, but I figured I might as well share it here.
Seems as though there is some miscommunication between KDE and Wallet, which is something I have also noticed with other things (like certain apps such as Steam and Flatpak apps not opening the file select dialog).

**Comment by dmxk06** [comment]
The pam module for it needs to be started for it to work. Same goes for gnome's equivalent.

**Comment by vaxerski** [comment]
not a hyprland issue?
