### ISSUE TITLE
gnome-control-center does not run on Hyprland

### ISSUE THREAD

**Issue by D3vil0p3r** [hyprwm/Hyprland#2556]
Helllll(o)
when running `gnome-control-center` on Hyprland nothing happens. Is GNOME Control Center not compatible with Hyprland?

**Comment by q234rty** [comment]
This is not a Hyprland bug: https://gitlab.gnome.org/GNOME/gnome-control-center/-/commit/fbf8886b91b597b7bacfa93623d0c6c176ae3e9a

**Comment by hewenjin** [comment]
So I check the source code, this trickiycould let it work`XDG_CURRENT_DESKTOP=GNOME gnome-control-center`
