### ISSUE TITLE
When using touchscreen, mouse / touchpad cursor follows finger

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#2557]
My system:
 - NixOS on touchscreen laptop
 - Built Hyprland from flake latest release
 - Using home-manager module
 - My configs:
   - [nixos shell.nix files](https://git.nelim.org/matt1432/nixos-configs)
   - [Regular dotfiles](https://git.nelim.org/matt1432/wm-dots)

## Expected outcome
Whenever I use my touchscreen, I expect the inputs to be independant from the mouse cursor.

## Noted outcome
The mouse cursor will move to where the touch inputs are happening, therefore making some touchscreen gestures like in Waydroid not work at all because it thinks I'm using my mouse

@fufexan I don't know if this issue is NixOS specific but it works fine on gnome-shell and I think it used to work on Arch on Hyprland

**Comment by fufexan** [comment]
I can't test so I don't know if it's NixOS specific. I assume it's not.

**Comment by vaxerski** [comment]
thats like the point in general, I can make it toggleable though

**Comment by matt1432** [comment]
> thats like the point in general, I can make it toggleable though

huh, it never used to be like that on anything else I've tried. I would very much like that to be toggleable because it renders Waydroid basically useless on a touchscreen

**Comment by matt1432** [comment]
@vaxerski I've noticed a few recent commits were about dragging and inputs, so I was wondering if you took a look at this issue again. Here is an example of what I've been experiencing


https://github.com/hyprwm/Hyprland/assets/98562002/c8fc560e-6298-41b5-b3b4-a2aafc480b00

**Comment by vaxerski** [comment]
no, the fixes were not regarding this

**Comment by swwind** [comment]
Just leaving a stupid solution here.

Removing calls to `wlr_cursor_warp` and `wlr_seat_pointer_notify_motion` in `CInputManager::onTouchDown` temporary fixes this problem ([patch](https://gist.github.com/swwind/0bcb9b733a7fb86d480539f02efc7c85)). However, this also breaks window focus logic, which means you must focus the window first to ensure that it receives touch events. But in general, this allows my Waydroid to handle touch events without trouble.

**Comment by matt1432** [comment]
@swwind Thank you! Works perfectly now
