### ISSUE TITLE
DrawingBotV3 main menu inaccessible

### ISSUE THREAD

**Issue by bkuri** [hyprwm/Hyprland#2558]
I'm unable to interact with the main dropdown menu using the mouse. The menu appears as soon as I press on a root menu item (as expected), but disappears as soon as I release the button.

Additionally, the menu is rendered with a pretty big gap between it and the menu bar, and as soon as I move the cursor towards the menu and through the gap, the menu disappears as well.

It seems like this could be similar to the issue experienced in #1956, but I can't be completely sure at this point. Perhaps I need to create a window rule as well?

Steps to reproduce:

1. Make sure to have the OpenJDK JRE installed
2. [Install DrawingBotV3 free here](https://github.com/SonarSonic/DrawingBotV3/releases/tag/v1.5.3-stable-free) (or just run the .jar file)
3. Open the app and interact with the menu bar at the top

You should see a menu rendered like so (gap is marked in red):

![screenshot](https://cdn.discordapp.com/attachments/929089869949579335/1120432861707763794/dbv3-menu.jpg)

Hope this helps!

**Comment by bkuri** [comment]
I was able to mitigate the problem by adding the following window rules to the config file:

```
windowrulev2 = move cursor -10px 10px,class:^(drawingbot.FXApplication)$,title:^()$
windowrulev2 = noanim,class:^(drawingbot.FXApplication)$,title:^()$
windowrulev2 = noblur,class:^(drawingbot.FXApplication)$,title:^()$
```

It's still not perfect since the menu disappears if I release the mouse button outside of it, but at least I can select items now.

**Comment by MightyPlaza** [comment]
any updates? maybe try `noinititalfocus`

**Comment by bkuri** [comment]
seems to be working ok as of `v0.42.0`.
