### ISSUE TITLE
Popup windows of Intellij IDEA is far outside the screen

### ISSUE THREAD

**Issue by Bryan2333** [hyprwm/Hyprland#2559]
I have two screens, one is my laptop built-in screen, the other one is an external monitors. I'm using clamshell mode(only the external monitor is on).

My problem is that the popup windows of Intellij IDEA is far outside the screen, and I cannot see them in screen.

Here is the screen record of the case.

https://github.com/hyprwm/Hyprland/assets/31512600/142c4d68-7418-4862-a911-c0fd6a865180

My hyprland version is 0.26.0.
My monitor config is below.
```
monitor = eDP-1,2880x1800@90,0x0,2
monitor = DP-2,2560x1440@75,2880x0,1.25
```

**Comment by MightyPlaza** [comment]
Make a window rule and set the position of the spawned windows

**Comment by Bryan2333** [comment]
> Make a window rule and set the position of the spawned windows

I have tried to use window rule to set the position of the windows. But the problem is the title popup window is like `win -*`, and when the cursor hovers on the sidebar icon, the tooltip window is also like `win-*`. So I do not know how to set the window rules

**Comment by MightyPlaza** [comment]
title:$(win-)^

**Comment by zakk4223** [comment]
Does setting a primary x11 display help? xrandr --output eDP-1 --primary

**Comment by Bryan2333** [comment]
> Does setting a primary x11 display help? xrandr --output eDP-1 --primary

Nope, I have not tried yet. But I find a way which does some help.

After I disable my laptop built-in screen, I use command `hyprctl monitor DP-2,2560x1440@75,0x0,1.25` to move the position of the external monitor.

And the popup window is not far outside the screen any more, but always showing up in the right bottom cornet of the screen. Although it is not perfect, but at least I can drag the window to somewhere else.

**Comment by skogler** [comment]
Same issue here, the problem is some popups have their window position set to 0x0.
An example is the 'New Package' dialog in Android Studio (tested multiple versions, including latest Canary version, with different JBR versions).

The first time it  runs, it is sometimes positioned correctly. When you run it again, the position is at 0x0 (my primary monitor is at 2560x0, so this is on the wrong monitor).

**Comment by skogler** [comment]
What is strange is that the 'New File' dialog is not affected, which makes very little sense.

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by romanstingler** [comment]
without jetbrains window rules it is not reproducible
