### ISSUE TITLE
Binds without mod

### ISSUE THREAD

**Issue by Gargoth** [hyprwm/Hyprland#256]
Hello! I would like to be able to add a bind without any mod. This is so I could bind stuff to my XF86Audio(Play/RaiseVolume/LowerVolume) keys without needing to press SUPER or any other mod to trigger it. Thanks!

**Comment by taylor85345** [comment]
Just don't put a mod key before the first comma. For example:

`bind=,XF86AudioMedia,exec,playerctl play-pause`

**Comment by Gargoth** [comment]
Ah that makes sense, I should've figured that out without asking. Cheers!
