### ISSUE TITLE
[force_zero_scaling] Mouse location not correctly detected outside of the top left quadrant on force_zero_scaling

### ISSUE THREAD

**Issue by Jackaed** [hyprwm/Hyprland#2566]
When using force_zero_scaling on Hyprland (latest build), my mouse cursor is "bound" to the top left quadrant of my screen. The cursor itself moves beyond that, but it's location is capped at halfway along the screen horizontally and vertically.

My monitor resolution is 2880 by 1800, although xrandr lists this as 1440 by 900 (which I would imagine is what causes the issue?).

This issue occurs in Steam, Spotify, Minecraft and every other xwayland application I have tested.

**Comment by vaxerski** [comment]
Generally force_zero_scaling is a hack because wlroots does not let us set a fake scale for xwayland AFAIK

**Comment by Jackaed** [comment]
Does this mean that this issue is impossible to fix without a WLRoots patch? If so, the option sort of becomes a bit unusable.

AFAIK KDE uses a similar hack to implement it's scaling these days, where it has the option to not scale x applications and instead scale through GDK_SCALE. I know KDE doesn't use wlroots but I'd still be interested to know what is/is not possible.

**Comment by vaxerski** [comment]
> Does this mean that this issue is impossible to fix without a WLRoots patch?

likely

**Comment by vaxerski** [comment]
check with 40e33719c3ed044afe328d00ab08a735ae73e638

**Comment by Jackaed** [comment]
This seems to work correctly now! Thank you very much.

I only have a few remaining issues with it:

1) The cursor still appears blurry in xwayland applications
2) Floating xwayland applications (e.g. the steam start menu) appear in the top-left quadrant of the display on 2x scaling.

I imagine the latter will be easier to fix than the former? The first issue I experienced on KDE when I was using a similar setting over there. Regardless, this has made xwayland far more usable on hidpi, thank you very much.
