### ISSUE TITLE
protocol files installed if not installed, not installed if installed.

### ISSUE THREAD

**Issue by hboetes** [hyprwm/Hyprland#2568]
I have an automated build and install script, and every time I see the following file being removed and then added again with the next build.

```
MISSING   drwxr-xr-x      root/root       usr/local/share/hyprland-protocols/
MISSING   drwxr-xr-x      root/root       usr/local/share/hyprland-protocols/protocols/
MISSING   -rw-r--r--      root/root       usr/local/share/hyprland-protocols/protocols/hyprland-global-shortcuts-v1.xml
MISSING   -rw-r--r--      root/root       usr/local/share/hyprland-protocols/protocols/hyprland-toplevel-export-v1.xml
MISSING   -rw-r--r--      root/root       usr/local/share/pkgconfig/hyprland-protocols.pc
```

Seems like something in the installation scripts decides they don't need to be installed if they are already installed. But since my script does a fake install the result is these files being added and removed every next update.

Sounds like something that can be improved.

**Comment by vaxerski** [comment]
meson?

**Comment by hboetes** [comment]
meson.

```bash
build()
{
    cd $name
    meson --prefix=/usr/local build
    ninja -C build
    DESTDIR=$PKG ninja -C build install
}
```

**Comment by hboetes** [comment]
I found a similar fix on another project.
```bash
build()
{
    cd $name
    meson --prefix=/usr/local build \
          -Duse_system_wfconfig=disabled \
          -Duse_system_wlroots=disabled
    ninja -C build
    DESTDIR=$PKG ninja -C build install
}
```

**Comment by vaxerski** [comment]
@fufexan for meson

**Comment by fufexan** [comment]
@hboetes is there something that needs to be done on the Hyprland side, or was the fix needed in your build script?

**Comment by hboetes** [comment]
looking at meson_options.txt, there is no option for installing the file mentioned above, so I bet this behaviour will continue. Even though I don't have hyprland installed at the moment.

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by hboetes** [comment]
beats me, I'm no longer using hyprland.
