### ISSUE TITLE
Overview feature previewing all opened clients 

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#2569]
swipe up to preview all clients opened and easily switch between them using trackpad.
Now typing this makes me feel like this is a dumb feature request for a tiling wm *compositor
but now i have typed it so let it be there.

**Comment by vaxerski** [comment]
that could just be a client?

**Comment by niksingh710** [comment]
> that could just be a client?

yeah that's a nice idea a client to show all the clients open in Hyprland.
now this seems promising

**Comment by vaxerski** [comment]
iirc people have already made that with eww...

**Comment by niksingh710** [comment]
> iirc people have already made that with eww...

Have to learn eww now ..... Don't know why I m trying to avoid m quite fine with waybar..... 

If u see somewhere it please link

**Comment by vaxerski** [comment]
nothing's stopping you from for example writing your own app in gtk and C(++) :)

**Comment by TheSunCat** [comment]
Wouldn't this be better implemented as part of Hyprland (or a plugin), allowing for a 1:1 gesture to transition into the overview (like GNOME and KDE do)?

**Comment by vaxerski** [comment]
as a plugin - ok, base hyprland - don't think it's in the scope of a _tiling window manager_

**Comment by TheSunCat** [comment]
You can have a tiled overview :)
But I agree this is more in plugin territory. I think the way you showed in #1902 could work really well, and make workspaces which are further away number-wise easier to access (by moving in X and Y space to where it got placed rather than swiping n times to get to it).

> *window manager*

I can't believe you'd say this about the Hyprland compositor.

**Comment by DreamMaoMao** [comment]
@niksingh710 


https://github.com/hyprwm/Hyprland/assets/30348075/ac8f05c0-1e0b-478d-80b9-6dc1f85f359f



Is that what you're talking about? I am trying to make this hyprland plugin but I am not sure if the interface exposed by the plugin will allow me to dynamically switch layouts

**Comment by niksingh710** [comment]
Yes, Exactly this is what m talking about.

**Comment by DreamMaoMao** [comment]
@niksingh710 

It's not very perfect yet, but you can try it out.



https://github.com/DreamMaoMao/hycov

**Comment by vaxerski** [comment]
Closing, this will probably not be core and is better left to plugins like the one demonstrated IMO.
