### ISSUE TITLE
`cursor_inactive_timeout` doesn't hide cursor after `movefocus`

### ISSUE THREAD

**Issue by karb94** [hyprwm/Hyprland#2570]
When I set `cursor_inactive_timeout = 1` I expect the cursor to hide after not touching my mouse for 1 second. However, when I change the focused window via `movefocus` the cursor not only reappears and moves to the centre of the new focused window but it also won't hide (ever) unless I use my keyboard on that window (using only my mouse won't make it hide again). This issue appears in any app I've tried.

I don't know what is the expected behaviour here but I would expect the cursor to not appear when changing window focus or at the very least to disappear 1 second after the focus has changed.

**Comment by karb94** [comment]
I'm using v0.26. Here's a minimal config:
```
general {
    cursor_inactive_timeout = 1
}
    bind = SUPER, H, movefocus, l
    bind = SUPER, L, movefocus, r
    bind = SUPER, K, movefocus, u
    bind = SUPER, J, movefocus, d
```
Steps to reproduce:
1. Have a few Alacritty and Brave (Wayland mode) windows open. Note: it is not specific to these applications but it's what I'm currently using
2. Switch window focus with the above bindings
3. When the focus changes to a different window the cursor appears at the centre of that window.
4. After 1 second the cursor remains visible. Even after moving and clicking mouse buttons the cursor won't hide.
5. If I press any keyboard keys the cursor will hide immediately (without a 1 second delay)

Hope this helps.

**Comment by MightyPlaza** [comment]
Can you give the rest of the config, still can't repro on 0.26

**Comment by karb94** [comment]
There is no more config. I am running NixOS with `programs.hyprland.enable = true` and nothing else (no home-manager config).

Here's a video to better show the issue. My `~/.config/hypr/hyperland.conf` is shown on the left window

https://github.com/hyprwm/Hyprland/assets/41967813/530f8864-af3b-45f8-9454-4780684df47f

**Comment by karb94** [comment]
I still can reproduce in 0.27

**Comment by MightyPlaza** [comment]
new cursor stuff on 0.28.0, anything new?

**Comment by karb94** [comment]
Yes, unfortunately this issue is still present in 0.28.0

**Comment by MightyPlaza** [comment]
still can't repro with firefox and kitty

**Comment by Yuanda-Dong** [comment]
On my machine the cursor does not appear in the new focused window, but it appears on the old window. After  `cursor_inactive_timeout` seconds, the cursor hides itself. I would like the cursor to remain hidden all the time after focus move.
