### ISSUE TITLE
Hyprland Crashes on start

### ISSUE THREAD

**Issue by uncomfyhalomacro** [hyprwm/Hyprland#2571]
# System Information
**OS**: openSUSE Tumbleweed
**Snapshot**: 20230620
**CPU**: Intel(R) Core(TM) i5-10300H (8) @ 4.5 GHz
**GPU**: NVIDIA GeForce RTX 3060 Mobile / Max-Q

# Hyprland Information (`zypper info hyprland`)
Repository     : Main Repository (OSS)
Name           : hyprland
Version        : 0.26.0-1.2
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 4.0 MiB
Installed      : Yes
Status         : up-to-date
Source package : hyprland-0.26.0-1.2.src
Upstream URL   : https://hyprland.org/
Summary        : Dynamic tiling Wayland compositor

# Logs

[hyprland.log](https://github.com/hyprwm/Hyprland/files/11841604/hyprland.log)

[hyprlandCrashReport7149.txt](https://github.com/hyprwm/Hyprland/files/11841639/hyprlandCrashReport7149.txt)

## Relevant Backtrace

```
Backtrace:
        #0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x63a) [0x55a74f41f83a]
                ??
                ??:0
        #1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x55a74f3c313c]
                ??
                ??:0
        #2 | /lib64/libc.so.6(+0x3e2f0) [0x7fb19315a2f0]
                ??
                ??:0
        #3 | /usr/lib64/gbm/nvidia-drm_gbm.so(+0x152fb) [0x7fb180a152fb]
                ??
                ??:0
        #4 | /usr/lib64/gbm/nvidia-drm_gbm.so(+0x155c8) [0x7fb180a155c8]
                ??
                ??:0
        #5 | /lib64/libgbm.so.1(+0xd106) [0x7fb193bd9106]
                ??
                ??:0
        #6 | /lib64/libgbm.so.1(gbm_create_device+0x5b) [0x7fb193bdab9b]
                ??
                ??:0
        #7 | Hyprland(wlr_gbm_allocator_create+0x7e) [0x55a74f4d0d6e]
                ??
                ??:0
        #8 | Hyprland(allocator_autocreate_with_drm_fd+0x1c6) [0x55a74f4cc1b6]
                ??
                ??:0
        #9 | Hyprland(_ZN11CCompositor10initServerEv+0x1b5) [0x55a74f3ca435]
                ??
                ??:0
        #10 | Hyprland(main+0x4f2) [0x55a74f3b3b32]
                ??
                ??:0
        #11 | /lib64/libc.so.6(+0x27bb0) [0x7fb193143bb0]
                ??
                ??:0
        #12 | /lib64/libc.so.6(__libc_start_main+0x8b) [0x7fb193143c79]
                ??
                ??:0
        #13 | Hyprland(_start+0x27) [0x55a74f3c1905]
                ??
                ??:0
```

### What was observed?

Hyprland used to run after the Mesa update was fixed (yes there was a bug report but that was on openSUSE Mesa and it got fixed). I am currently running on RiverWM to check if I can run Hyprland in a tty but same error.

**Comment by MightyPlaza** [comment]
Looks like nvidia issue.
Have you done https://wiki.hyprland.org/Nvidia/ ?

**Comment by uncomfyhalomacro** [comment]
I will have just to disable the env vars related to nvidia and everything will be okay :0
