### ISSUE TITLE
SUPER, SPACE bind propagates SPACE to firefox and pauses the video on youtube

### ISSUE THREAD

**Issue by nativerv** [hyprwm/Hyprland#2575]
# Noted outcome

`bind = $myMod, SPACE, fullscreen, 1` causes the title. Only `SPACE`, any other letter doesn't seem to be passed through, only in firefox (not in chromium, not in mpv) and only on youtube (not invidious, not odysee, not direct link video). Very strange. 

# Steps to reproduce

1. Have the config options:
    - `$myMod = SUPER`
    - `bind = $myMod, SPACE, fullscreen, 1`
1. Open any video on youtube
1. Press Super + Space and see firefox pausing and unpausing the video and hyprland toggling fullscreen mode.

# Expected outcome

Space don't get propagated

**Comment by nativerv** [comment]
Ok, it doesn't even happen in private window in firefox. So it's caused by extensions? But how that can be, if the event supposed to be consumed by hyprland entirely?
It has nothing to do with the fullscreen/window resizing too, as the following toggles the playback on my side too:

`bind = $myMod, SPACE, exec, notify-send -u low test`

How can i even debug that further?

**Comment by vaxerski** [comment]
odd, no clue

**Comment by segalll** [comment]
couldn't replicate on my system - what extensions are you using?

**Comment by nativerv** [comment]
> couldn't replicate on my system - what extensions are you using?

Normally this list, but i just disabled them all, restarted the browser and the issue is still there.

![image](https://github.com/hyprwm/Hyprland/assets/70909425/6d4d8fb9-88e5-4168-bf15-c10f6b213912)

Private window and clean profiles still don't have the issue. As well as container tab (!) literally next to the no container one which is catching space.

On the video i first press super+space on a normal tab and get it toggled, then switch to a tab in am empty container and do the same and nothing happens (except for expected hyprland binding):

https://github.com/hyprwm/Hyprland/assets/70909425/c45e9cd4-15aa-4fe0-ad9b-c869063be598

Arch Linux

Firefox 114.0.2

Hyprland 0.26.0-3

**Comment by MightyPlaza** [comment]
still happening?

**Comment by nativerv** [comment]
doesn't seem to be happening, though i'm in a different environment on a different distro now (with the same firefox profile)
