### ISSUE TITLE
Show groupbar when no_gaps_when_only is true

### ISSUE THREAD

**Issue by RedShiningFish** [hyprwm/Hyprland#2576]
When `no_gaps_when_only` is set to true and only a single window is on a workspace, the groupbar is also hidden. However, this makes it visually impossible to tell if a window is a group. The groupbar should be shown regardless of `no_gaps_when_only`.

**Comment by MightyPlaza** [comment]
Mostly done, looks kinda strange.
not sure what spacing to put on top, maybe the normal out space, maybe the inner space, maybe a new var
![groupbar_noborder](https://github.com/hyprwm/Hyprland/assets/123664421/2df05325-6250-429a-a689-aeb90d913b4c)

**Comment by MightyPlaza** [comment]
this has been fixed already @vaxerski
