### ISSUE TITLE
..../build/libwlroots.so.12032', needed by 'Hyprland', missing and no known rule to make it

### ISSUE THREAD

**Issue by pullobi** [hyprwm/Hyprland#2577]
ninja: error: '../subprojects/wlroots/build/libwlroots.so.12032', needed by 'Hyprland', missing and no known rule to make it
i added misc{
supress_portal_warnings = true
}

**Comment by MightyPlaza** [comment]
--recursive?

**Comment by vaxerski** [comment]
--recursive indeed

**Comment by pullobi** [comment]
i am using manjaro now, it says the same error, i dont know where to add --recuresive
what am i to do

**Comment by MightyPlaza** [comment]
git clone --recursive https://github.com/hyprwm/Hyprland
Hyprland is on the arch repos and in the aur

**Comment by Makrennel** [comment]
Alternatively, if you're using the tagged release, use the "source-v0.26.0.tar.gz" download and not the normal "Source Code (tar.gz)". The former includes the subprojects.
