### ISSUE TITLE
commit 01f85a0, lutris and xwayland

### ISSUE THREAD

**Issue by pbosab** [hyprwm/Hyprland#2580]
hyprland: latest commit
lutris: tried stable and latest git

trying to launch a game that require xwayland result in lutris:

```
DEBUG    2023-06-24 14:29:23,058 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
ERROR    2023-06-24 14:29:23,059 [exceptions.wrapper:95]:Blizzard Battle.net (wine) has encountered an error: not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 628, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 192, in get_config
    return get_outputs()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 59, in get_outputs
    _, x_pos, y_pos = geometry.split("+")
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 1)
```

reverting back to 69fae18 fixes the problem.

**Comment by Fxzzi** [comment]
Bumping this. Also getting this issue on new git build.

**Comment by pbosab** [comment]
as @Fxzzi noted, pre-commit 01f85a0 xrandr output is:

```
DVI-D-1 connected 1920x1080+2560+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     59.96*+
   blah blah blah
HDMI-A-1 connected 2560x1080+0+0 (normal left inverted right x axis y axis) 670mm x 280mm
   2560x1080     59.91*+
   blah blah blah
```

after:

```
HL X11 0 connected 1920x1080+2560+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     59.96*+
   blah blah blah
HL X11 1 connected 2560x1080+0+0 (normal left inverted right x axis y axis) 670mm x 280mm
   2560x1080     59.91*+
   blah blah blah
```

**Comment by danieljohnson2** [comment]
I see what you mean. The name part has spaces in it, and so Lutris thinks the name is 'HL' and the geometry is '1', which does not parse good.

We'll need a rather more clever parser for this.

**Comment by vaxerski** [comment]
thats why, dear kids, you dont do that like that

lutris issue, but I can remove the spaces for the sake of any other idiotic methods like this

**Comment by danieljohnson2** [comment]
We try to avoid using xrandr as much as we can, but sometimes it's all we've got.

What's the correct way to parse this? Apparently it's not just space separated fields.

**Comment by vaxerski** [comment]
should be fixed with 4294456cdcdf0a28f5adbdbef83aefccc00d6701 then

> What's the correct way to parse this? Apparently it's not just space separated fields.

`name.find("connected")` and go from there?

**Comment by danieljohnson2** [comment]
That'll fail for names as simple as "connected-1". I'll manage something, but I can't figure out how to handle really awkward names like "I wish I were connected right now".

**Comment by vaxerski** [comment]
there is no fully bulletproof solution here. You can also search for the first occurrence of numberxnumber

**Comment by danieljohnson2** [comment]
I've gone with searching for the word 'connected' *starting after* the first word; that should work reliably as long as the name has no spaces, and can handle most names that do.
