### ISSUE TITLE
Hyprland + GDM does not source/run /etc/profile.d/ bash scripts

### ISSUE THREAD

**Issue by D3vil0p3r** [hyprwm/Hyprland#2581]
When Hyprland is used with GDM, all the scripts in `/etc/profile.d/` directory (both system-created and user-created) are not sourced/executed so the system or some application could not work as intended.

For testing:
1. Create `test.sh` in `/etc/profile.d/` with the following content:
    ```
    #!/bin/sh

    touch "$HOME/hello.txt"
    ```
2. Reboot or logout and login
3. The `hello.txt` file is not created

If you use Hyprland + SDDM, it works. If you use GDM + other DE, it works.

So the issue is related to the usage of Hyprland + GDM. Not sure if it impacts also `/etc/profile` script and other bash scripts run at startup.

**Comment by zakk4223** [comment]
This a GDM thing. GDM doesn't start a shell, so none of the normal shell configs will be run.

There's some discussion involving potential solutions in an older sway issue: https://github.com/swaywm/sway/issues/3109

**Comment by D3vil0p3r** [comment]
> 

Thank you. I don't understand why that member guy of sway continues to say that is a GDM bug... According to what I read, GDM was intended to not launch a login shell, and it works in GNOME because `gnome-session-binary` is invoked for calling a login shell when the user access to GNOME.

As reported in the https://github.com/swaywm/sway/issues/3109#issuecomment-437656217 comment, would be interesting to implement officially on Hyprland side.

**Comment by SymphonySimper** [comment]
Yep as @D3vil0p3r  mentioned.
```
[Desktop Entry]
Name=Hyprland
Comment=An intelligent dynamic tiling Wayland compositor
Exec=/usr/bin/zsh -l -c Hyprland
Type=Application
```
Switching this with the default one in `/usr/share/wayland-sessions/hyprland.desktop` did the trick for me.

**Comment by vaxerski** [comment]
this is not a hl issue why is this open

**Comment by D3vil0p3r** [comment]
> this is not a hl issue why is this open

Because it occurs only in Hyprland? Is it hard for you to read posts and perform tests on a (bugged) environment that you developed?

**Comment by SymphonySimper** [comment]
Agreed. But could you consider Adding this to the FAQ would help people facing this issue.

**Comment by vaxerski** [comment]
pong: why not make the wiki MR yourself as you know the issue better?

**Comment by D3vil0p3r** [comment]
Because I'm cooking spaghetti
