### ISSUE TITLE
drop shadows

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#259]
I'd really like to see window shadows. Need I explain more?

**Comment by vaxerski** [comment]
no, you dont need to, they're planned

**Comment by EysseW** [comment]
amazing!

**Comment by vaxerski** [comment]
747ff3369d6377628e3e27e3b108c8d61cbc5733 rejoice.

**Comment by EysseW** [comment]
I love you.

**Comment by EysseW** [comment]
I already love this feature but I'd like to request 1 more thing and I am probably not the only one. I don't know if this is planned but I'd like to have off center shadows. I find it really hard to explain but maybe this thread will help: https://github.com/fluix-dev/sway-borders/issues/63
Yes I am bugging multiple people about desktop porn at once :)

**Comment by vaxerski** [comment]
added in 44aeb1fc909ec9cb3e6b82a5397e9eec8839192b

**Comment by EysseW** [comment]
omg you are so fast this is amazing!

**Comment by EysseW** [comment]
After playing around with them even more, I found 
1) shadows are staying on your monitor for a little while when moving to a different workspace.
2) Maybe nice to have an opacity rule to the windows, for even more control.

**Comment by vaxerski** [comment]
1. is already fixed (just a minute ago pushed)

2. see windowrules for opacity and the basic configuring section decoration for opacity control

**Comment by EysseW** [comment]
1) Great!
2) I meant opacacity for the shadows. I mistyped some things. I meant for better control over the shadows. So yeah, an opacity rule for the shadows itself.

**Comment by vaxerski** [comment]
no need to, you can set the shadow's color, and it includes an alpha value.
