### ISSUE TITLE
Add background color options for groupbar and gradients

### ISSUE THREAD

**Issue by hmanhng** [hyprwm/Hyprland#2595]
I use swww dynamic wallpaper, so the groupbar is relatively hard to see. i don't see any option to change background color. Can add them?

**Comment by MightyPlaza** [comment]
Last ones
http://wiki.hyprland.org/Configuring/Variables/#misc

**Comment by hmanhng** [comment]
> Last ones http://wiki.hyprland.org/Configuring/Variables/#misc

what i want is background color, not text color.

**Comment by MightyPlaza** [comment]
The options beginning in col.group then
http://wiki.hyprland.org/Configuring/Variables/#general

**Comment by hmanhng** [comment]
it's just the border, not the background sir

**Comment by MightyPlaza** [comment]
Hyprland restart is required for some reason, but it changes the gradient.

**Comment by Aqa-Ib** [comment]
> Hyprland restart is required for some reason, but it changes the gradient.

What is the name of the option that changes the group gradient color? thanks.

**Comment by MightyPlaza** [comment]
col.group_...

**Comment by Aqa-Ib** [comment]
> col.group_...

Alright thanks.
I think this issue might be renamed to: recolor the groupbar gradient without having to restart hyprland.
Cheers.

**Comment by Aqa-Ib** [comment]
Is this really fixed? I can not find the way to put a background to the group bar. Thank you all.

**Comment by Aqa-Ib** [comment]
This one is not working at the moment, consider reopening.

**Comment by Aqa-Ib** [comment]
I would gladly git bisect it, but I am having problems trying to build past commits because of subprojects.

**Comment by vaxerski** [comment]
`g reset --hard --recurse-submodules`

**Comment by MightyPlaza** [comment]
> I would gladly git bisect it, but I am having problems trying to build past commits because of subprojects.

https://github.com/hyprwm/Hyprland/issues/4081#issuecomment-1847201757
I will try to fix it when I get the time

**Comment by MightyPlaza** [comment]
@vaxerski fixed now
