### ISSUE TITLE
Firefox Picture in Picture goes into fullscreen when changing video

### ISSUE THREAD

**Issue by FirelightFlagboy** [hyprwm/Hyprland#2598]
## Version

Hyprland, built from branch  at commit 51a930f802c71a0e67f05e7b176ded74e8e95f87 dirty ().
Tag: v0.26.0 (using the AUR package)

xdg-desktop-portal-hyprland: 0.4.0-1

## Steps to reproduce

1. Using `firefox-114.0.2`
2. Playing a youtube playlist
3. Toggle `Picture-in-Picture` (later called PIP) mode for the video
4. Move to the end of the current playing video
5. Wait the video to end
6. Youtube will now start playing the next video
7. At that time the `Picture-in-Picture` goes into fullscreen

## Expected outcome

When Youtube play the next video, the `PIP` don't go into fullscreen.

## Noted outcome

When Youtube play the next video, the `PIP` goes into fullscreen.

Here is the output of `hyprctl clients` for the PIP client

```txt
Window 564aa00097f0 -> Picture-in-Picture:
	mapped: 1
	hidden: 0
	at: 1102,42
	size: 3796,1556
	workspace: 5 (5)
	floating: 1
	monitor: 0
	class: firefox
	title: Picture-in-Picture
	initialClass: firefox
	initialTitle: Picture-in-Picture
	pid: 1184
	xwayland: 0
	pinned: 0
	fullscreen: 1
	fullscreenmode: 1
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

Before the next video play, here is the output of `hyprctl clients`:

```txt
Window 564aa06bcb80 -> Picture-in-Picture:
	mapped: 1
	hidden: 0
	at: 1404,-8
	size: 2766,1556
	workspace: 5 (5)
	floating: 1
	monitor: 0
	class: firefox
	title: Picture-in-Picture
	initialClass: firefox
	initialTitle: Picture-in-Picture
	pid: 1184
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

What change between the two, is the `fullscreen` & `fullscreenmode` are set to `1`.

## Custom window rule for PIP

```
windowrulev2 = float, class:(firefox), title:(Picture-in-Picture)
```

I've configured the PIP to always float

## A possible workaround

If I add the following rule to prevent the window requesting fullscreen I no longer have that problem, but I can't also go into fullscreen using the fullscreen button in PIP player

```
windowrulev2 = nofullscreenrequest, class:(firefox), title:(Picture-in-Picture)
```

**Comment by MightyPlaza** [comment]
Same happens in mpv and other random programs sometimes.
Started looking but didn't find the cause/origin of the maximize requests yet.
Not feeling like diving into mpv's code base just yet

**Comment by romanstingler** [comment]
it seems that  automatically some scanout mode is triggered 

```
[LOG] Searching for matching rules for firefoxnightly (title: Picture-in-Picture)
[LOG] Scanout mode OFF set for 55668a4baa50
[LOG] Set keyboard focus to surface 55668a4cb5d0, with window name: roman@roman: tail -f
[LOG] Window 55668a4baa50 fullscreen to 0
[LOG] Maximize request for 55668a4baa50
[LOG] Searching for matching rules for firefoxnightly (title: Picture-in-Picture)
[LOG] Scanout mode ON set for 55668a4baa50
[LOG] Activate request for surface at 55668a477ab0
[LOG] Set keyboard focus to surface 55668a477ab0, with window name: Picture-in-Picture
[LOG] Keybind triggered, calling dispatcher (64, , 102)
[LOG] Searching for matching rules for firefoxnightly (title: Picture-in-Picture)
[LOG] Scanout mode OFF set for 55668a4baa50
[LOG] Set keyboard focus to surface 55668a4cb5d0, with window name: roman@roman: tail -f
```

**Comment by MightyPlaza** [comment]
I've been digging this for a while and seems to also happen on sway.
But sway doesn't have maximize so the window doesn't get maximized.
On mpv it's caused due to "XDG_TOPLEVEL_STATE_MAXIMIZED" being set has true despite window not being maximized.
Not sure why this var is set this way, maybe to avoid giant UI issues.
No idea how to change this var so no idea how to fix, but probably seems like wlroots issue/misconfiguration

**Comment by MightyPlaza** [comment]
In mpv's case it wasn't an issue with hyprland, and I think firefox will be the same.
I think it's better to move this to firefox's bug tracker.

**Comment by FirelightFlagboy** [comment]
Hello @MightyPlaza, can you provide the issue you've opened for mpv as an example ?

**Comment by FirelightFlagboy** [comment]
I've opened an issue on firefox side: <https://bugzilla.mozilla.org/show_bug.cgi?id=1844404>

**Comment by MightyPlaza** [comment]
In the mean time https://github.com/hyprwm/Hyprland/pull/2785

**Comment by cylian914** [comment]
That is an issue with firefox not hyprland. Firefox first PiP has not the same class and title then other PiP.

**Comment by MightyPlaza** [comment]
> That is an issue with firefox not hyprland. Firefox first PiP has not the same class and title then other PiP.

It isn't the same issue, this issue has always been present since I started using hyprland, unlike that issue which started about 2 months ago.

Although it's extremely unlikely that this is an issue with hyprland, no other compositor experiences the issue since wayland is (to my knowledge) the only tiling compositor that handles maximizing events.

I'm not sure that your issue has been reported, but since it's wayland-wide and a regression it might be fixed faster despite been lower prio.

**Comment by Sohail-XD** [comment]
This issue still exists :(

**Comment by MightyPlaza** [comment]
that's what happens when nobody fixes it 
use the `nomaximizerequest` window rule as a temporary fix

**Comment by Sohail-XD** [comment]
> that's what happens when nobody fixes it use the `nomaximizerequest` window rule as a temporary fix

unfortunately it doesn't work for me

**Comment by MightyPlaza** [comment]
this issue is that firefox sends random maximize request out of nowhere
firefox can fix it or hyprland can deny maximize requests from firefox

you either have the rule wrong or your issue is not the same
example rule: `windowrulev2=nomaximizerequest, class:^(firefox)$`

**Comment by Sohail-XD** [comment]
> this issue is that firefox sends random maximize request out of nowhere firefox can fix it or hyprland can deny maximize requests from firefox
> 
> you either have the rule wrong or your issue is not the same example rule: `windowrulev2=nomaximizerequest, class:^(firefox)$`

Nope, still opens up like a new window

![image](https://github.com/hyprwm/Hyprland/assets/86248129/24e83a44-6308-4e9e-8c14-3be06c0ea0be)

**Comment by MightyPlaza** [comment]
> Nope, still opens up like a new window
> 
> ![image](https://user-images.githubusercontent.com/86248129/274824931-24e83a44-6308-4e9e-8c14-3be06c0ea0be.png)

I'm not sure what your issue is, this is not the thread for the firefox PiP window not floating with the windowrule set (https://github.com/hyprwm/Hyprland/issues/2942 and others)

**Comment by MightyPlaza** [comment]
On another note, issue is extremely unlike to be caused on hyprland's end, and it can be fully mitigated with `nomaximizerequest` with minimal impact on firefox's functionality
since it  and has been reported upstream (https://bugzilla.mozilla.org/show_bug.cgi?id=1844404) to which no response has been given

**Comment by topazrn** [comment]
My workaround for now:
```
windowrulev2 = float,class:^(firefox)$ #Picture-in-Picture hopefully nothing else
windowrulev2 = tile,class:^(firefox)$,title:^(Mozilla Firefox)$ #New window of Firefox, weirdly this also works for Private Window
```

**Comment by Jeffser** [comment]
Hi, I'm also having problems with this

windowrulev2 = opacity 0.8 0.8,title:^(Picture-in-Picture)$ #WORKS
windowrulev2 = nomaximizerequest,title:^(Picture-in-Picture)$ #DOESN'T WORK
windowrulev2 = nofullscreenrequest,title:^(Picture-in-Picture)$ #DOESN'T WORK
windowrulev2 = float,title:^(Picture-in-Picture)$ #DOESN'T WORK

I'm using
xdg-desktop-portal-hyprland 1.2.4-1
hyprland 0.30.0-1

**Comment by MightyPlaza** [comment]
> Hi, I'm also having problems with this
> 
> windowrulev2 = opacity 0.8 0.8,title:^(Picture-in-Picture)$ #WORKS windowrulev2 = nomaximizerequest,title:^(Picture-in-Picture)$ #DOESN'T WORK windowrulev2 = nofullscreenrequest,title:^(Picture-in-Picture)$ #DOESN'T WORK windowrulev2 = float,title:^(Picture-in-Picture)$ #DOESN'T WORK
> 
> I'm using xdg-desktop-portal-hyprland 1.2.4-1 hyprland 0.30.0-1

again
that is not the same issue
https://github.com/hyprwm/Hyprland/issues/2942

**Comment by Lemanrp** [comment]
Having same issue but agree this is more of a firefox issue and I think it's preferable to wait for firefox to fix it to avoid a scenario where Hyprland changes their code to fix this issue but then firefox fixes the issue and now a new issue arises (Hyprland fix being now incompatible with firefox changes for example).

Perhaps this is a 'feature request' as much as a proposed solution. I remember using a WM (river I think) where the full screen button would make the video full screen *within* it's own tile rather than within the current workspace/screen.

would something like this be a good solution? if it is, would it be something that could be implemented or would that be a large overhaul? Ultimately, in the long term, being able to enable & disable full-screen within tiles would be an awesome setting to have as I strongly prefer full screen being within tile (so like full-tile?).

**Comment by MightyPlaza** [comment]
> Having same issue but agree this is more of a firefox issue and I think it's preferable to wait for firefox to fix it to avoid a scenario where Hyprland changes their code to fix this issue but then firefox fixes the issue and now a new issue arises (Hyprland fix being now incompatible with firefox changes for example).
> 
> Perhaps this is a 'feature request' as much as a proposed solution. I remember using a WM (river I think) where the full screen button would make the video full screen _within_ it's own tile rather than within the current workspace/screen.
> 
> would something like this be a good solution? if it is, would it be something that could be implemented or would that be a large overhaul? Ultimately, in the long term, being able to enable & disable full-screen within tiles would be an awesome setting to have as I strongly prefer full screen being within tile (so like full-tile?).

`fakefullscreen`?

**Comment by JPDucky** [comment]
I disagree that it is a firefox issue, as I have the same issue here and if I use `class:^(firefox)` instead of `title:^(ChatGPT — Mozilla Firefox)$`, it works. If I use `title`, I can see in the logs that it matches, but it doesn't apply any rules even though it says it did. I can also manually change the window with a toggle fullscreen bind.

Logs:
```
[LOG] Searching for matching rules for firefox (title: ChatGPT — Mozilla Firefox)
[LOG] Window rule size 50% 50% -> title:(ChatGPT — Mozilla Firefox) matched 563ac40f5ff0 [ChatGPT — Mozilla Firefox]
[LOG] Window rule fakefullscreen -> title:(ChatGPT — Mozilla Firefox) matched 563ac40f5ff0 [ChatGPT — Mozilla Firefox]
[LOG] Window rule float -> title:(ChatGPT — Mozilla Firefox) matched 563ac40f5ff0 [ChatGPT — Mozilla Firefox]
```

**Comment by XorvatoAmigos** [comment]
There is a great solution to make pip the way we want it to be without affecting the main window, here is my rules setup:

```
# Firefox
$firefox = class:^(firefox)$
windowrulev2 = fakefullscreen,title:^(Firefox)$,$firefox
windowrulev2 = fakefullscreen,title:^(Picture-in-Picture)$,$firefox
windowrulev2 = size 50% 50%,title:^(Firefox)$,$firefox
windowrulev2 = size 50% 50%,title:^(Picture-in-Picture)$,$firefox
windowrulev2 = float,title:^(Firefox)$,$firefox
windowrulev2 = float,title:^(Picture-in-Picture)$,$firefox
```

By observing the properties of the windows, we can see this for the first time:

```
	class: firefox
	title: Picture-in-Picture
	initialClass: firefox
	initialTitle: Picture-in-Picture
```

But in all subsequent cases, the initialTitle changes:

```
	class: firefox
	title: Picture-in-Picture
	initialClass: firefox
	initialTitle: Firefox
```

**Comment by Jeffser** [comment]
I can confirm, it works, this is my config, I also use "keepaspectratio" and "pin"
```
windowrulev2 = keepaspectratio,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = noborder,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = fakefullscreen,class:^(firefox)$,title:^(Firefox)$
windowrulev2 = fakefullscreen,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = pin,class:^(firefox)$,title:^(Firefox)$
windowrulev2 = pin,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(firefox)$,title:^(Firefox)$
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
```

**Comment by aura404dev** [comment]
I use the PiP tiled, sometimes it goes fullscreen, sometimes it doesn't. What worked for me best was just the `nomaximizerequest` rule, make sure you reopen the PiP window cause it isn't applied when Hyprland is reloaded.
~~~ini
$cfirefox = class:^(firefox)$
$tpip = title:^(Firefox)|(Picture-in-Picture)$
windowrulev2 = nomaximizerequest, $cfirefox, $tpip
~~~

**Comment by Acumane** [comment]
Simplest window field, no need for duplicate rules:

`$PiP = class:^(firefox)$, title:^(Firefox|Picture-in-Picture)$`

**Comment by FirelightFlagboy** [comment]
I will test that tonight, but I'm currently using `suppressevent` so I would need to remove that rule first

**Comment by FirelightFlagboy** [comment]
I've just tested with:

```ini
hyprland = 0.41.2
firefox = 128.0
```

using the Pip window playing videos without any `suppressevent maximize` rules, on the end of a video the window did not maximize :tada:

So the original issue appear to be fixed somehow :shrug:. Given that, I'll close the issue
