### ISSUE TITLE
no output to third monitor

### ISSUE THREAD

**Issue by jnordwick** [hyprwm/Hyprland#2607]
I'm driving 3 screens on this laptop (i have 4 on another I will be trying this weekend). These work on Xorg every desktop I've tried, but this is my first wayland attempt.

eDP builtin laptop
DP-1 either DP to USB-C or HDMI into a USB-C hub
HDMI-A-1 into the HDMI port

The two externals are a 2k and 4k, tried all possible combinations. I haven't tried 2 2ks or 4ks (I have a lot of monitor real estate)

I can only ever get the built in and one of the other two to work (disabling the built in off doesn't help). hyprctl can see all three fine. If I unplug and plug them back in sometimes I get get it to change which one works for that config.

OS: EndeavourOS Linux x86_64 
Host: Latitude 3510 
Kernel: 6.3.9-zen1-1-zen 
Uptime: 1 day, 38 mins 
Packages: 1204 (pacman) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: Hyprland 
WM: sway 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-10510U (8) @ 4.900GHz 
GPU: Intel CometLake-U GT2 [UHD Graphics] 
Memory: 4355MiB / 64067MiB 

Hyprland, built from branch  at commit 51a930f802c71a0e67f05e7b176ded74e8e95f87 dirty ().
Tag: v0.26.0
flags: (if any)

**Comment by MightyPlaza** [comment]
Nvidia laptop?

**Comment by jnordwick** [comment]
```
monitor=DP-1,3840x2160,0x0,1
monitor=HDMI-A-1,2560x1440,2160x2400,1
monitor=eDP-1,1920x1080,4720x2760,1
monitor=,preferred,auto,auto
```
```
Monitor eDP-1 (ID 0):
	1920x1080@60.007999 at 4720x2760
	description: Chimei Innolux Corporation 0x15E5 (eDP-1)
	make: Chimei Innolux Corporation
	model: 0x15E5
	serial: 
	active workspace: 1 (1)
	reserved: 0 50 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor HDMI-A-1 (ID 1):
	2560x1440@60.000000 at 2160x2400
	description: HKC OVERSEAS LIMITED 27E1QA 0000000000001 (HDMI-A-1)
	make: HKC OVERSEAS LIMITED
	model: 27E1QA
	serial: 0000000000001
	active workspace: 2 (2)
	reserved: 0 50 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-1 (ID 2):
	3840x2160@30.000000 at 0x0
	description: Samsung Electric Company U32J59x H4ZM501400 (DP-1 via HDMI)
	make: Samsung Electric Company
	model: U32J59x
	serial: H4ZM501400
	active workspace: 3 (3)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
```

**Comment by MightyPlaza** [comment]
The layout looks a bit strange, what are the monitor positions?

**Comment by jnordwick** [comment]
the monitors are 4k rotated 90 CCW tot the far left, 2K to teh right of then, and the laptop to the the right. I tried dropping the 4K res a step but didn't help. I also tried disabling the laptop. I;'ve also tried to putting both on DP, but I only have 1 USB-C port so I have to use HDMI routed through a USBC-C hub, but still a no. Ir works find  w/ both lxqt kwin and openbox. Today I'm gong to try another laptop

**Comment by MightyPlaza** [comment]
```
monitor=DP-1,3840x2160,0x0,1,transform,3
monitor=HDMI-A-1,2560x1440,2160x0,1
monitor=eDP-1,1920x1080,4720x0,1
```
should be like this then

**Comment by jnordwick** [comment]
I tried using wrlr-randr to set it, but it silently happy. I just tried wdispay and I have anctual image (too a while to appear), but is only 720 x 400.

**Comment by jnordwick** [comment]
> monitor=HDMI-A-1,2560x1440,2160x0,1

I through coord origin was top left? so my y should be 3840 - 1440?

**Comment by MightyPlaza** [comment]
Seems strange really pull down the monitor res, to like 1080p or even 720p.
Make sure mesa drivers are installed
Also use nvtop (or the intel one) to check gpu usage and vram usage.
You might need to give more vram.

https://github.com/hyprwm/Hyprland/issues/2607#issuecomment-1614764666
this is my bad, still think the wrong way.

**Comment by jnordwick** [comment]
It all works fine in Xorg with any DE (plasma etc included). I can swap this out with a dev one, but for all the praise, those machines suck for dev ironically and I use this as my grab and go for working outside the home, but the dev one has some huge issues for being usable for dev.

**Comment by MightyPlaza** [comment]
Hypr is unmaintained, most of Hyprland features are probably not in there.

https://ark.intel.com/content/www/us/en/ark/products/196449/intel-core-i710510u-processor-8m-cache-up-to-4-90-ghz.html
Try this conf
```
monitor=DP-1,1920x1080@60,0x0,1,transform,3
monitor=HDMI-A-1,1920x1080@60,1080x0,1
monitor=eDP-1,1920x1080@60,3000x0,1
```
Hyprland doesn't support 24Hz, so no idea what would happen if the maximum refresh rate is that.
Also from now pls test with displayport instead of hdmi

**Comment by jnordwick** [comment]
That woks, just  the res sucks on the 2k and 4k monitors. The monitors are almost all text so the freq doesn't matter that much. What is the issue?

why does it work in Xorg and not wayland? I think it needs to put the down to 30Hz, but the monitor is capable of 4k@60. The 2k can go up to 144 Hz, but I don't see those listed either.

**Comment by MightyPlaza** [comment]
Now try to scale it up slowly and see where it breaks, keep forcing the refresh rate otherwise something might try to set it as 24hz

**Comment by jnordwick** [comment]
Oh damn. I didn't read far enough down the data sheet. Oh snap, I didn't the last part of this sentence from the laptop datasheet: `HDMI 1.4: 4096 x 2160 @ 60 Hz, 24bpp, Via optional USB Type-C to HDMI dongle`

**Comment by MightyPlaza** [comment]
Res is a bit lower might be able to do 30Hz (not doing calcs btw)

**Comment by jnordwick** [comment]
Is the problem just that it cant' downgrade to 24Hz on the 4k since that isn't supported in wayland/hyprland/whatever? bit X does?

I'll close then and mess with it later. Thanks. I bought this latitude 3510 and put 64mb in it for about $230, so total steal regardless. nice 15" matte screen, and great keyboard. sucks about the hdmi and single c port.

**Comment by jnordwick** [comment]
ps thanks, great support services. i'll give you 5 starts on the support questionnaire.
