### ISSUE TITLE
[Feature Request] Runtime configuration options?

### ISSUE THREAD

**Issue by Animeshz** [hyprwm/Hyprland#261]
WMs like bspwm or [hlwm](https://herbstluftwm.org/herbstluftwm.html) exposes everything for the configuration into shell (from sockets). This makes it easy to test out changes when windows are opened and things are running.

Hlwm also offers a locking mechanism where if the hlwm is started with `--locked`, all the style changes are deferred until `hc unlock` is called. That way default themes are not applied and after everything is queued, things start drawing. Can also manually lock and unlock with `hc lock` and `hc unlock` in case we want to do multiple changes and stay responsive/efficient while doing so, as sockets have latency (e.g. switching light/dark mode of multiple things borders / bg / frame / etc).

How cool would it be if we're able to configure & test out stuffs at runtime (with `hyprctl` which already allows socket talking as I see), without exiting the session or try to run different wm in another tty, and get the results seen in-eye at the exact moment.

**Comment by vaxerski** [comment]
if you're talking about live reloading the config, that's literally already how it works.

**Comment by Animeshz** [comment]
Oh, sorry for the issue then, I should've tried it more.
