### ISSUE TITLE
BAD_PORTALS detection is bad for multi-user systems

### ISSUE THREAD

**Issue by lugeha** [hyprwm/Hyprland#2610]
62c75883d1b275d2a6e62bf31d59a43f0a404c14

I have a computer that has more than one user, and those user prefers the gnome-shell environment? Removing the gnome portal would break their desktops.

A better solution I have found is to simply use systemctl to mask xdg-desktop-portal-gnome in my hyprland user environment.

Checks need to be either smarter, or allow suppression.

This is what I add to my hmModule to automate it on NIX.

```
home.activation.hyprland = let
    PATH = "${config.xdg.configHome}/systemd/user";
  in lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p ${PATH}
    ln -sf /dev/null ${PATH}/xdg-desktop-portal-gnome.service
  '';
```

**Comment by vaxerski** [comment]
they allow suppression...?

**Comment by lugeha** [comment]
I suppose it would help if I read the patch in its entirety. Thank you, nothing to see here.
