### ISSUE TITLE
"hyprctl cursorpos" shows wrong cursor position

### ISSUE THREAD

**Issue by helixoid** [hyprwm/Hyprland#2612]
Recently I started using Hyprland and I am pleased to say that it works and looks pretty awesome.

But few days ago, I discovered swww wallpaper manager and I learnt about it's transitions and one of them was [**_--transition-type grow --transition-pos "$(hyprctl cursorpos)"_**], which in theory should start it's transition animation from wherever the mouse cursor is at that moment but It is happening opposite to the cursor location {on y-axis}.

So I checked the **_hyprctl cursorpos_** command to find the postion of cursor and it is inverted in y-axis.
I checked it on **stable** as well as **git** version of Hyprland but it is broken in both versions.

![top cursor](https://github.com/hyprwm/Hyprland/assets/110732140/6a416f5d-6bcb-4c70-a977-91ca41500660)
Here cusor is in higher position.

![bottom cusor](https://github.com/hyprwm/Hyprland/assets/110732140/e56f3284-b193-4172-8c59-478945f26d89)
Here cursor is in lower position.

**Sorry about not providing screenshots cuz I don't know how to make grim include mouse cursor in screenshot.**

**Comment by romanstingler** [comment]
Cursor position starts at top left corner. 
because your horizontal position (x) stays the same, and you change your vertical (y) position 
everything is as expected.

**Comment by helixoid** [comment]
> Cursor position starts at top left corner. because your horizontal position (x) stays the same, and you change your vertical (y) position everything is as expected.

yeah here x-axis is same; but isn't y-axis should have higher value as the cursor is higher or in the upper side of monitor but here it is opposite upper side has lower y-coordinate value and lower side has higher y-coordinate value ?

**Comment by helixoid** [comment]
> Cursor position starts at top left corner. because your horizontal position (x) stays the same, and you change your vertical (y) position everything is as expected.
Also swww isn't working as expected.
This is the command I am running:
**_swww img <path-to-image> --transition-type grow --transition-pos "$(hyprctl cursorpos)" --transition-fps 60 --transition-duration 3_**

**Comment by helixoid** [comment]
> Cursor position starts at top left corner. because your horizontal position (x) stays the same, and you change your vertical (y) position everything is as expected.

Also swww isn't working as expected.
This is the command I am running:
**_swww img --transition-type grow --transition-pos "$(hyprctl cursorpos)" --transition-fps 60 --transition-duration 3_**

**Comment by romanstingler** [comment]
> > Cursor position starts at top left corner. because your horizontal position (x) stays the same, and you change your vertical (y) position everything is as expected.
> 
> yeah here x-axis is same; but isn't y-axis should have higher value as the cursor is higher or in the upper side of monitor but here it is opposite upper side has lower y-coordinate value and lower side has higher y-coordinate value ?

no you are wrong
![image](https://github.com/hyprwm/Hyprland/assets/5576250/16c4be77-8c45-4d78-87dd-73f404a2208d)

**Comment by helixoid** [comment]
> > > Cursor position starts at top left corner. because your horizontal position (x) stays the same, and you change your vertical (y) position everything is as expected.
> > 
> > 
> > yeah here x-axis is same; but isn't y-axis should have higher value as the cursor is higher or in the upper side of monitor but here it is opposite upper side has lower y-coordinate value and lower side has higher y-coordinate value ?
> 
> no you are wrong ![image](https://user-images.githubusercontent.com/5576250/250050085-16c4be77-8c45-4d78-87dd-73f404a2208d.png)
> 
> If you think this doesn't work as expected, create an issue in swww. The cursor position is returned correctly

Oh now I understand.
I am closing the issue and going to open one in swww repo.
