### ISSUE TITLE
Bind power-button to suspend.

### ISSUE THREAD

**Issue by mkblast** [hyprwm/Hyprland#2614]
I don't know if you already could, but i want to bind my power button to lock the screen then suspend, I tried this, however, it didn't seem to work.

I user `hyprctl devices` to get the name of the button.

```
bind  = ,power-button, exec, swaylock && systemctl suspend
```

**Comment by leonzag** [comment]
@mkblast You can set `HandlePowerKey=suspend` in _/etc/systemd/logind.conf_ [Login] section. Also some other options.
(see man logind.conf)

Further, `swayidle` able to execute commands before sleep, so you can setup actions like locking screen...
My swayidle config looks like this:
```shell
timeout 300     'hypr-kbd-layout-reset ; swaylock -f --grace 120'
timeout 600     'hyprctl --batch "dpms off" ; systemctl suspend' resume 'hyprctl --batch "dpms on"'
before-sleep    'hypr-kbd-layout-reset ; swaylock -f'
```

**Comment by SortexGuy** [comment]
i want to do something similar but instead of sleep i want to exec a script to open a rofi menu, but that original bind line doesn't seem to work

**Comment by szczescie** [comment]
@SortexGuy set `HandlePowerKey=ignore` in /etc/systemd/logind.conf then add `bind = , XF86PowerOff, exec, ~/script.sh` to ~/.config/hypr/hyprland.conf

**Comment by KAGEYAM4** [comment]
@mkblast  close the issue if it has been resolved.

**Comment by rushiiMachine** [comment]
Instead of letting logind ignore power keys, I used `systemd-inhibit` to prevent logind from handling power key presses while Hyprland is active:

```conf
exec-once = systemd-inhibit --who="Hyprland config" --why="wlogout keybind" --what=handle-power-key --mode=block sleep infinity & echo $! > /tmp/.hyprland-systemd-inhibit
exec-shutdown = kill -9 "$(cat /tmp/.hyprland-systemd-inhibit)

bind  = , XF86PowerOff, exec, wlogout
```

This allows the power button to still function like normal when Hyprland is not running.
