### ISSUE TITLE
Can't select text in certain GTK applications

### ISSUE THREAD

**Issue by donovanglover** [hyprwm/Hyprland#2619]
I was never able to select text in Thunar with Hyprland (Ctrl+A, Ctrl+L, double-clicking, etc.). Nautilus doesn't work either. Text selection works in river and other window managers. I've experienced this issue with both Arch Linux and NixOS.

Hyprland v0.26.0

**Comment by donovanglover** [comment]
For anyone else that runs into this problem, the solution is to not disable middle click paste as described in the [Hyprland FAQ](https://wiki.hyprland.org/hyprland-wiki/pages/FAQ/#how-to-disable-middle-click-paste).

**Comment by tchofy** [comment]
I was having similar issues, but for me the solution was not using wl-clip-persist. Another issue using wl-clip-persist that caused for me was corrupted images when they're pasted to discord.

**Comment by Memoframe** [comment]
> I was having similar issues, but for me the solution was not using wl-clip-persist. Another issue using wl-clip-persist that caused for me was corrupted images when they're pasted to discord.

For me _--clipboard_ regular instead of _--clipboard both_ was enough
