### ISSUE TITLE
Many xwayland apps broken since commit 01f85a0 on June 23, 2023

### ISSUE THREAD

**Issue by hewasud** [hyprwm/Hyprland#2621]
Here is an example of what happens when I try to run `xprop`:
```
$xprop
xprop:  unable to open display ''
```

Here is an example of what happens when I try to start a flatpak application:

```
$flatpak run org.signal.Signal
F: No colon found in DISPLAY=
Debug: Will run signal with the following arguments:
Debug: Additionally, user gave:
[2:0701/134058.641694:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/sudarsha/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[2:0701/134059.179805:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[2:0701/134059.179813:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
```

Applications I can't start with this version of Hyprland include:

- jetbrains-toolbox or any of the jetbrains ide's
- Signal messenger installed from flatpak
- gimp

Most applications complain about $DISPLAY not being set but setting this variable manually to ":0" doe snot fix the problem.  For now I am reverting to the previous commit to keep a functional version of hyprland.

**Comment by zakk4223** [comment]
What version of Xwayland are you using?

**Comment by hewasud** [comment]
I am using the following version of Xwayland which came with Fedora 38:

```
$ Xwayland -version
The X.Org Foundation Xwayland Version 22.1.9 (12201009)
X Protocol Version 11, Revision 0
Build ID: xorg-x11-server-Xwayland 22.1.9-2.fc38
```

Hyprland prior to commit 01f85a0 works on fedora 38 in multiple machines for me.  Thanks.

**Comment by zakk4223** [comment]
I don't have the issue with that checkout, but I'm using xwayland 23.1.2. I wonder if that version difference might matter. The problem you describe is almost as if XWayland isn't even running

**Comment by hewasud** [comment]
Thanks for letting me know. I think you are right about the version incompatibility with Xwayland and the later versions of Hyprland.

 This leaves me with two options now:

1. Build a custom Xwayland with a more recent version
2. Stay with old Hyprland until Fedora eventually update Xwayland on their repos.

The path of least resistance for me is to stick with old Hyprland and not try any new versions until fedora Xwayland is updated in Fedora.  

Still, it's a shame that it completely stopped working after that commit for me.  Aside from some scaling issues, Xwayland was functional on my machines with Hyprland.  A compatibility notice probably need to be in the wiki somewhere.  I will close with this comment. 

Thank you.
