### ISSUE TITLE
[Nvidia + Radeon] m_sWLRRenderer was NULL! on a dual gpu setup

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/Hyprland#2622]
Greetings. I plan on documenting this issue in the wiki for future reference, so I am going to be a bit verbose on this

# Setup Information
+ Distribution: Gentoo linux (AMD64)
+ Kernel: 6.1.31-gentoo-dist
+ Integrated GPU: AMD Cezanne(Radeon Mobile Vega Series) (Mesa Drivers)
+ Dedicated GPU: Nvidia GeForce GTX 1650 Max-Q (Proprietary Drivers)
+ Init System: SystemD

# Problem + Logs
From what I could find, there is no documented way to run Hyprland on a specific GPU in a multi-gpu setup. These setups are very common in the likes of gaming laptops or workstations.

The issue faced by me is as follows
`[CRITICAL] m_sWLRRenderer was NULL!`
Full output of `cat /tmp/hypr/$(ls -t /tmp/hypr/ | head -n 1)/hyprland.log` is attached [here](https://bpa.st/GUQTW)

This came off as weird to me. I have 2 GPUs with wayland-capable drivers, while none of them being used for rendering. If relevant, the output of `lspci` is attached [here](https://bpa.st/2KQNM)

I am also attaching a coredump [here](https://https://files.catbox.moe/7b6cqa.zst)

It would be preferable to have the integrated GPU as the primary renderer in this case for a lasting battery.

# Steps to Reproduce

0. Have a setup similar to that of mine
1. Set necessary USE flags for `gui-wm/hyprland` from the `guru` overlay
2. Install hyprland as described by the wiki
3. Attempt to launch
4. See issue

# Expected Outcome

Load hyprland

# Noted outcome

Hyprland fails to detect a renderer and doesn't launch as a result

# Additional Note(s)
1. Standard, vanilla configuration file was used without and changes

Additional information will be provided upon request. Thank you

**Comment by MahouShoujoMivutilde** [comment]
> From what I could find, there is no documented way to run Hyprland on a specific GPU in a multi-gpu setup. These setups are very common in the likes of gaming laptops or workstations.

There is `WLR_DRM_DEVICES` and `WLR_RENDER_DRM_DEVICE` ([wlroots docs](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md)) that likely could be used for that.

IDK about the rest.

**Comment by WasteOfO2** [comment]
> There is WLR_DRM_DEVICES and WLR_RENDER_DRM_DEVICE (wlroots docs) that likely could be used for that.

Thank you, i should have been specific when i said it wasnt documented on the hyprland wiki. I would assume a relatively common setup like this would be explained.

I will look into those variables, but i am not sure to what degree they are compatible with hyprland. The project does mention it follows wlroots closely, but i dont know any better.

**Comment by MahouShoujoMivutilde** [comment]
> I would assume a relatively common setup like this would be explained.

I do not disagree.

Wlroots is [one of the dependencies](https://github.com/hyprwm/Hyprland/tree/main/subprojects), it should work.

Regarding the variables, as far as I understand, you should run 

```
udevadm info -a -n /dev/dri/card0 | grep DRIVER
```

and the same for card1 to figure out which of the cards is integrated / dedicated.

and then 

```
export WLR_DRM_DEVICES=/dev/dri/what_you_want
....
exec Hyprland
```
(there is built-in config option to set environment variables `env = THING,value` but IDK how early in the launch process it sets them)

**Comment by WasteOfO2** [comment]
If I am understanding this correctly, the `WLR_DRM_DEVICES` and `WLR_RENDER_DRM_DEVICE` should be the same GPU?

wlroots is in itself hardware accelerated, so if i were to set my integrated gpu to both these paramaters, i should be able to get a result that i want.

But i am not sure how nvidia optimus would be handled in that case, the wiki has no mention of this

**Comment by MahouShoujoMivutilde** [comment]
Yes.

But they seem a bit redundant (RENDER sounds more specialized than DEVICES which seems more like "what cards at all will be considered") - you most likely wont be able to set them to explicitly different devices. 

However, DEVICES can be used to set priorities too  `export WLR_DRM_DEVICES="/dev/dri/card0:/dev/dri/card1"`.

While RENDER is always a single device.

So - IDK about optimus, try it and see what happens.

Just make sure it launches at all first.

**Comment by WasteOfO2** [comment]
I tried your suggestion, i added the following in my hyprland.conf

｀env = WLR_DRM_DEVICES,"/dev/dri/card1:/dev/dri/card0"｀

card1 was the radeon, card0 was nvidia. Hyprland didnt start and the output was as [follows](https://bpa.st/GRGVE)

**Comment by MahouShoujoMivutilde** [comment]
> Failed to open device: '"/dev/dri/card1': No such file or directory

See anything _wrong_ here?

Try without quotes.

**Comment by WasteOfO2** [comment]
I have tried without the quotes, but now it turns out i have a different problem, that radeonsi doesnt open cuz the file doesnt exist

https://bpa.st/KNHLA

**Comment by MahouShoujoMivutilde** [comment]
It's weird that a file that is apparently

```
❯ pacman -Qo /usr/lib64/dri/radeonsi_dri.so
/usr/lib/dri/radeonsi_dri.so is owned by mesa 23.1.3-1
``` 
a part of mesa (on arch at least) doesn't exist.

Dude [here](https://forums.gentoo.org/viewtopic-t-1020892-start-0.html) says that you should add `VIDEO_CARDS="radeon radeonsi"` to make.conf to fix it.

Just to make sure - have you read [the nvidia section](https://wiki.hyprland.org/Nvidia/#how-to-get-hyprland-to-possibly-work-on-nvidia) on the wiki?

**Comment by WasteOfO2** [comment]
Turns out i did smth funny in my make.conf and u were right.

I have ensured i have read the nvidia section fully and applied changes, even removing radeon completely out of the equation to ensure only the nvidia module gets loaded, but i seem to get the same freeze. Logs for the same https://bpa.st/VN2E2

**Comment by WasteOfO2** [comment]
Although i can still mark this as closed, it would be wise to have a fallback as nvidia to function properly. I want to investigate this a bit more

**Comment by MahouShoujoMivutilde** [comment]
Well it definitely shouldn't hang on nvidia - I am running proprietary driver 535.54.03 just fine.

**Comment by WasteOfO2** [comment]
My desktop used to work with nvidia perfectly well too, was a matter of days ago. I will investigate this myself

And no, this is a fresh install so there is no chance it is running an older version. At best maybe certain builds dont ship nvidia specific patches for hyprland

**Comment by MahouShoujoMivutilde** [comment]
There is only one patch that is still needed - format workaround for screen recording:

```diff
diff --git a/types/output/render.c b/types/output/render.c
index 2e38919a..97f78608 100644
--- a/types/output/render.c
+++ b/types/output/render.c
@@ -311,20 +311,5 @@ struct wlr_drm_format *output_pick_format(struct wlr_output *output,
 }
 
 uint32_t wlr_output_preferred_read_format(struct wlr_output *output) {
-	struct wlr_renderer *renderer = output->renderer;
-	assert(renderer != NULL);
-
-	if (!renderer->impl->preferred_read_format || !renderer->impl->read_pixels) {
-		return DRM_FORMAT_INVALID;
-	}
-
-	if (!output_attach_back_buffer(output, &output->pending, NULL)) {
-		return false;
-	}
-
-	uint32_t fmt = renderer->impl->preferred_read_format(renderer);
-
-	output_clear_back_buffer(output);
-
-	return fmt;
+	return DRM_FORMAT_XRGB8888;
 }

```

The rest just works, at least on 535, so unlikely.

**Comment by WasteOfO2** [comment]
I had screen recording run no issues, oddly

Well, perhaps that is offtopic for this issue, i will close this for now and commit a change to the wiki to address what we discussed. Thank you

**Comment by MahouShoujoMivutilde** [comment]
No problem.

One last idea - does nvidia work _at all_ right now for you? Like, in i3 on xorg? Because seems like a weird issue. No error.

Maybe journalctl / dmesg have something useful.

**Comment by WasteOfO2** [comment]
Well i want nvidia for 3D accel stuff like rendering, games and stuff anyway. It is loaded in the kernel and all the fun stuff. I think at best i need to just figure out optimus and verify if the stuff i want actually works(3D stuff)

**Comment by ToolmanP** [comment]
Can you elaborate more on how you fix this issue? I have a gentoo machine with the same specs as yours except the nvidia card. I have manually designated a wlr devices in the config but the WLR still complains it can not a render backend.  amdgpu/nvidia are loaded correctly when i type in lsmod and the mesa driver radeon_si.so was successfully installed.

**Comment by WasteOfO2** [comment]
@ToolmanP There is a wiki page for multi-gpu setup that i have written, please refer that
