### ISSUE TITLE
Adding rule to pin all floating windows doesn't work

### ISSUE THREAD

**Issue by bkuri** [hyprwm/Hyprland#2623]
## Steps to reproduce

Add this rule to the config file:

`windowrulev2 = pin,floating:1`

Adding an extra class or title filter doesn't seem to help:

`windowrulev2 = pin,floating:1,class:.*`

`windowrulev2 = pin,floating:1,title:.*`

## Expected outcome

All floating windows should be pinned

## Noted outcome

:shrug: :

**Comment by vaxerski** [comment]
fixed in 738ec900f4d5c5e2b00f90e71221ca380555b874

keep in mind the `floating:1` rule has to be below any `float` rule because they are parsed top-to-bottom

**Comment by bkuri** [comment]
Good to know! Thanks!

**Comment by bkuri** [comment]
@vaxerski this commit works well on newly-created floating windows, but not when I float an existing tiled window using the `togglefloating` dispatcher.

I've added an extra binding that allows me to pin the active window, but I need to remember to trigger it after floating a tiled window, which is a bit annoying.

I tried modifying my binding in order to call both `togglefloating` and `pin` at the same time, but that didn't work.

Do let me know if you'd like me to try something else. :+1:

**Comment by MightyPlaza** [comment]
For the rule to work, for now, the window need to be floating when the rule is applied (startup), since the rule is not dynamic. (might be a something worth changing on layout update)

You can bind the toggle float key to toggle float and make it pinned.

**Comment by bkuri** [comment]
@MightyPlaza could you show me how to trigger two dispatchers with one binding? I tried doing it using something like `bind = $mod, F, exec, hyprctl dispatch togglefloating && hyprctl dispatch pin` but nothing happened. Thanks in advance!

**Comment by MightyPlaza** [comment]
bash -c "hypr..." or hyprctl --batch

**Comment by bkuri** [comment]
@MightyPlaza  ok, so according to `hyprctl --help`:

```
...
flags:
--batch -> execute a batch of commands, separated by ';'
```

So I tried the following:

`$ hyprctl --batch "dispatch togglefloating active"; "dispatch pin active"`

.. but the result was a floating terminal window and the following output:

```
ok
bash: dispatch pin active: command not found
```

Removing the quotes gives me the following output:

```
$ hyprctl --batch dispatch togglefloating active; dispatch pin active
ok
bash: dispatch: command not found
```

Any idea as to what's going on?

**Comment by bkuri** [comment]
@MightyPlaza nevermind; I removed my earlier comment. It's working now. Thanks again for your help!
