### ISSUE TITLE
WLR gamma-control broken on main

### ISSUE THREAD

**Issue by tomKPZ** [hyprwm/Hyprland#2629]
Hyprland built at 738ec900f4d5c5e2b00f90e71221ca380555b874

I cloned the wlroots repo and built `examples/gamma-control.c`.  When running `build/examples/gamma-control -b 0.5` to set brightness to 50%, the command fails on Hyprland with `failed to set gamma table`.  The command succeeds with Sway.

**Comment by vaxerski** [comment]
sway or sway-git?

**Comment by tomKPZ** [comment]
sway-git

**Comment by svenihoney** [comment]
Gamma control not working for me as well. Gammastep and wlsunset both fail.
```
OS: NixOS 23.11.20231104.85f1ba3 (Tapir) x86_64 
Kernel: 6.6.0-zen1 
Resolution: 2560x1440, 3840x2160 
DE: Hyprland (Wayland) 
WM: sway 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Speedster MERC 319 AMD Radeon RX 6800 XT Black 
```

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by m-bartlett** [comment]
> is this still a thing?

I came to report a bug I'm observing with a similar issue as OP, and found this open issue.

I often use `gammastep` to control screen brightness at night through gamma correction. Recently I am only able to run one app that performs gamma correction per Hyprland login, and afterward all other processes that attempt to correct gamma fail with similar errors:

```console
$ gamma-control -b 1
failed to set gamma table
$ gammastep -o -b 1.0:0.66
Warning: Zero outputs support gamma adjustment.
Warning: 1/1 output(s) do not support gamma adjustment.
```

When I exit the Hyprland session and re-login I can run `gammastep` or `gamma-control` with gamma correction flags once but then I get the same errors for all executions after the first run.

The version I'm currently running is:
```console
$ hyprctl version
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4 dirty (props: bump version to 0.40.0).
Date: Sat May 4 09:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)
```

**Comment by izmyname** [comment]
Since Hyprland is no longer wlroots - perhaps, close the issue and suggest opening one for aquamarine in case, if the problem persists?

**Comment by lugabrielbueno** [comment]
the issue was just closed ? some solution ?

**Comment by lugabrielbueno** [comment]
I tried a lot of piece of softwares like wlsunset, gammastep and get the same errors, but **hyprsunset** solved for me:

```
sudo pacman -S hyprsunset

hyprsunset -t 4500
```
