### ISSUE TITLE
Automatically selecting lowest resolution

### ISSUE THREAD

**Issue by ErikReider** [hyprwm/Hyprland#263]
Every time I start hyprland without kanshi, the lowest resolutions on both of my monitors gets selected instead of the preferred one. The position is also a bit off compared to Sway and Wayfire due to both monitors being positioned at the same coordinates.

**Comment by vaxerski** [comment]
without kanshi, the monitor config in your hyprland.conf is used. Please read the wiki.

**Comment by ErikReider** [comment]
I commented every monitor setting out. By default without any configuration it should select the preferred resolution right? 720p gets selected by default on my 1440p monitor

**Comment by vaxerski** [comment]
> By default without any configuration it should select the preferred resolution right? 

no, neither I nor the wiki have ever said that.

**Comment by ErikReider** [comment]
What I meant was that most DEs, WMs usually select the "default monitor settings" without any prior configuration, so hyprland not doing so is a bit strange in my opinion. 

So a 1440p monitor should be configured to run at 1440p by default.

This isn't a issue that I'm experiencing due to me using kanshi but it's just a suggestion :)
