### ISSUE TITLE
zext_workspace_handle_v1.activate() for empty workspaces

### ISSUE THREAD

**Issue by MonstrousOgre** [hyprwm/Hyprland#2632]
I'm one of the contributors of waybar, and the one who implemented persistent workspaces.

With #2084 being implemented, you no longer need the patch to switch to workspaces with windows in them. This isn't true for empty persistent workspaces though, since they still require hyprctl to switch to.

Pardon my lack of wlroots knowledge, but is it possible to implement `zext_workspace_handle_v1.activate()` for empty workspaces? It is my undersanding that the workspace wouldn't exist and would need to be created when activate is called.

**Comment by vaxerski** [comment]
you can read the protocol spec yourself to make sure but iirc clients cannot create workspace handles

**Comment by q234rty** [comment]
I believe the protocol spec includes a "create" request to request creating a workspace though I'm not sure whether hyprland handles that at all...

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/584587af-8818-4d30-aaab-66998c57c7ff)
oh, yeah.

No, we don't, but we can. Theoretically it's just about turning that into `hyprctl dispatch workspace <str>` xD

**Comment by Neodiablow** [comment]
I would also be very interested (for reasons unrelated to waybar) in having an "empty not focused workspace".
It's annoying to have them be destroyed whenever you switch to another one.

**Comment by vaxerski** [comment]
why so? What's the point of keeping them open if you can use any and all dispatchers to get to them regardless of their open state?

**Comment by MonstrousOgre** [comment]
@vaxerski is the create workspace request something you'd be willing to implement? If so, I can make the necessary changes in waybar

**Comment by MightyPlaza** [comment]
there is a PR for hyprland/workspaces to allow clicking in workspaces (https://github.com/Alexays/Waybar/pull/2316)
hyprland/workspaces also uses hyprland's sockets so should be fully working, just needs to get merged and persistent workspaces to be implemented.

**Comment by vaxerski** [comment]
I can

**Comment by MonstrousOgre** [comment]
@MightyPlaza last I remember, there wasn't a hyprland/workspaces module for waybar. Just a wlr/workspaces. It's nice to know there's now one implemented specifically for Hyprland. I could help with the persistent workspaces part

**Comment by MonstrousOgre** [comment]
I guess with https://github.com/Alexays/Waybar/pull/2341, this isn't necessary
