### ISSUE TITLE
Hyprland 0.26.0-3 (archlinux latest) crash when sharing screen 

### ISSUE THREAD

**Issue by nimaaskarian** [hyprwm/Hyprland#2633]
### Explanation
When I share screen (doesn't matter if I'm using obs, webcord, chromium, etc), sometimes changing wallpaper makes hyprland crash.  
For changing wallpaper, I was using swww. And I switched to hyprpaper, of course because I have a lot of wallpapers preloading them using hyprpaper didn't seem like a good idea.  
so I switched back to swaybg so maybe it gets fixed; and it didn't.

### Steps to reproduce 
1. Use xdg-desktop-portal-hyprland.  
2. Share-screen.
3. Change wallpaper (do it couple of times, because it doesn't crash hyprland always).

### Files
- [hyprland.log](https://github.com/hyprwm/Hyprland/files/11935577/hyprland.log)
- [crash reoprt](https://github.com/hyprwm/Hyprland/files/11935580/hyprlandCrashReport35602.txt)
- [hyprland config](https://raw.githubusercontent.com/nimaaskarian/dotfiles/master/.config/hypr/hyprland.conf)
- [set wallpaper script](https://raw.githubusercontent.com/nimaaskarian/dotfiles/master/.config/hypr/scripts/wall/set.sh)
- [wal.sh (pywal script that calls above script)](https://raw.githubusercontent.com/nimaaskarian/dotfiles/master/Scripts/wal.sh)

**Comment by vaxerski** [comment]
what about -git?

**Comment by nimaaskarian** [comment]
> what about -git?

Tried that out too. Its the same.

**Comment by msaglietto** [comment]
Hey, same for me it's crashing while sharing using google meet no need to do any changes to the wallpaper.
Let me know if I can do something to help debug it

**Comment by vaxerski** [comment]
check with 7a7e3ee6d9367761eb225c44edf110800e4afafc

**Comment by Teddy-Kun** [comment]
I have a similar crash with the now latest -git of both Hyprland and xdph (so including 7a7e3ee).
For me it crashes when starting OBS and then moving or opening any other GUI application or even sometimes moving OBS itself. In this specific log I opened OBS, moved it to my other monitor, opened kitty and during the animation of opening it, it crashed.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12024826/hyprland.log)
[hyprlandCrashReport1335.txt](https://github.com/hyprwm/Hyprland/files/12024827/hyprlandCrashReport1335.txt)

**Comment by vaxerski** [comment]
@Teddy-Kun can you build in debug and provide a crash report from that?

**Comment by Teddy-Kun** [comment]
I have been trying for 30mins now and it is not crashing anymore since using the debug build. I'll try using my PC normally today and lets see if it crashes.

**Comment by Teddy-Kun** [comment]
Well debug has been stable for the entire day when before it crashed with 100% consistency. Does the possibility of a race condition exist?

**Comment by nimaaskarian** [comment]
Crash is consistent 100% of the time. I don't even need to change my wallpaper anymore, I just need to share screen.
Used both latest git and latest releases (0.27.0-1/0.4.0-1) of hyprland/xdph.
Its really annoying, I mean whats the point of smooth and cool animations if you can't flex it on your Xorg user friends 😅

**Comment by vaxerski** [comment]
it is some race, but I have no idea where, since the main compositor code is single-threaded. Can someone try to build with `-fsanitize=thread` maybe?

Also, this is mostly discussed in #2688 I know this is older but let's move there to unify everything

**Comment by vaxerski** [comment]
@Teddy-Kun @nimaaskarian can you try with the patch I posted there? Can be in release. Just post the log when it crashes.

**Comment by Teddy-Kun** [comment]
Sorry, I was not home and could not test it. In case it still matters: It does not crash anymore.
