### ISSUE TITLE
Waybar remains hidden when only fullscreen window in workspace is moved with `movetoworkspacesilent`

### ISSUE THREAD

**Issue by gekoke** [hyprwm/Hyprland#2634]
Reproduction:
- have Waybar running
- have exactly one fullscreen (`fullscreen, 0`) window in workspace
- have no other windows in workspace
- ensure Waybar is hidden due to fullscreen
- move said fullscreen window to another workspace using `movetoworkspacesilent`

Expected:
- Waybar is now unhidden, since no windows remain in workspace

Actual:
- Waybar remains hidden, even though no windows remain in workspace

**Comment by gekoke** [comment]
Running a different Waybar config seems to resolve the issue - weird. Not sure if this is an issue with Hyprland.

**Comment by gekoke** [comment]
The issue disappears when using `"mode": "dock"` in Waybar config - however, this is not a complete solution as the bar is visible through transparent windows while in fullscreen mode when that setting is enabled.

**Comment by memchr** [comment]
Here is a possible explanation for the bug

## The `fullscreen` dispatcher

Here is the callstack when using the `fullscreen` dispatcher

- [ls->alpha](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2070)
- [updateFullscreenFadeOnWorkspace](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2104)
- [setWindowFullscreen](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/managers/KeybindManager.cpp#L875)
- [fullscreenActive](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/managers/KeybindManager.cpp#L866)

https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2068-L2071

The alpha value of top layer surfaces (such as the waybar) in the current monitor is set to 0.f when the workspace has a fullscreen window.
```cpp
    const auto FULLSCREEN = pWorkspace->m_bHasFullscreenWindow;
```

```cpp
    for (auto& ls : PMONITOR->m_aLayerSurfaceLayers[ZWLR_LAYER_SHELL_V1_LAYER_TOP]) {
        if (!ls->fadingOut)
            ls->alpha = FULLSCREEN && pWorkspace->m_efFullscreenMode == FULLSCREEN_FULL ? 0.f : 1.f;
    }
```
## The `movetoworkspacesilent` dispatcher

Here is the callstack when using the `movetoworkspacesilent` dispatcher

- [ls->alpha](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2070)
- [updateFullscreenFadeOnWorkspace](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2104)
- [setWindowFullscreen](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2429)
- [setWindowFullscreen](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/Compositor.cpp#L2462)
- [moveWindowToWorkspaceSafe](https://github.com/memchr/Hyprland/blob/99b8a768cfe8741a0685faad8792bbf923293805/src/managers/KeybindManager.cpp#L966-L971)

`CCompositor::setWindowFullscreen(CWindow* pWindow, bool on, eFullscreenMode mode)` is called twice here, first with the parameter `on=false`, which sets the alpha of the waybar surface to `1` (fully opaque).
The second call is with `on=true`, which again sets the alpha of the waybar surface to `0` (fully transparent).
