### ISSUE TITLE
Perfomance issues when using Hyprland.

### ISSUE THREAD

**Issue by RoccoRakete** [hyprwm/Hyprland#2637]
I have this really weird issue, when using Hyprland...
I've installed Hyprland on top of an existing Arch-Installation with Gnome using Wayland. When using Gnome, everything seems to work fine, animations are smooth, no stutters whatsoever...

But using Hyprland gives me really bad performance, even on workspace/window animations, games are even worse. 

I've found multiple articles covering these issues, but all of them where nVidia related, none of them covered Intels iGPU's. 

Anyone having an idea? Or hints for debugging the issue? 

Hardware:
Core i5-8500T 
16GB RAM 
Samsung 970 evo plus

**Comment by MightyPlaza** [comment]
Make sure to disable the blur, enable the debug overlay and check gpu and vram usage. I would guess your drivers aren't working or you're out of vram

**Comment by RoccoRakete** [comment]
> Make sure to disable the blur, enable the debug overlay and check gpu and vram usage. I would guess your drivers aren't working or you're out of vram

I will take a look at that thank you! But even if that's the case, it doesn't make sense to me. My gnome desktop is heavily modified. Having Blur and animations literally everywhere ^^

**Comment by RoccoRakete** [comment]
Uhmm how do I enable the dubg overlay?

**Comment by MightyPlaza** [comment]
```
debug {
    overlay=true
}
```

**Comment by romanstingler** [comment]
@RoccoRakete I don't game on my notebook, but I use 2x 4K monitors and have no issues. 
I just use the iGPU. 
You can try using my config and adjust it step by step.
https://github.com/romanstingler/dotfiles/blob/main/.config/hypr/hyprland.conf

**Comment by RoccoRakete** [comment]
Okay, so there is something weird going on.. I'm having barely 40fps with the gpu doing nearly nothing during animations, or firing up 0 A.D.

Don't know what the issue is.

**Comment by RoccoRakete** [comment]
I'm pretty sure it has something to do with hyprland acting kind of weird. As soon as I'm starting a YouTube video in 60fps, it locks it framerate to 60fps too and everything is buttery smooth.. So I'm expecting the drivers to be working correctly.

**Comment by MightyPlaza** [comment]
Probably some power saving bullshit

**Comment by romanstingler** [comment]
@RoccoRakete does 
```
misc{
    vfr=false
}
```
make a difference?

**Comment by RoccoRakete** [comment]
> Probably some power saving bullshit #2484

Possible, yes. But how does it appear to be the case on Hyprland and on gnome it's not. Even though Hyprland has nothing to do with power control?

**Comment by RoccoRakete** [comment]
> misc{
>     vfr=false
> }

It gives me an error message "no such field"

**Comment by romanstingler** [comment]
please post your config

**Comment by RoccoRakete** [comment]
`
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

monitor=DP-1,2560x1440@120,0x0,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
exec = swaybg -m fill -i /home/martin/bspwm-gruvbox/wallpapers/solar-system-minimal.png
# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    blur = no
    blur_size = 3
    blur_passes = 1
    blur_new_optimizations = on

    drop_shadow = no^
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.25, 1, 0.5, 1

    animation = windows, 1, 1, myBezier
    animation = windowsOut, 1, 1, myBezier
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 3, myBezier
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, return, exec, kitty
bind = $mainMod, B, exec, firefox
bind = $mainMod, Q, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating, 
bind = $mainMod, Y, exec, rofi -show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
debug {
    overlay=true
}
`

**Comment by romanstingler** [comment]
please use pastebin or similar and edit your post and just share the link, thx

**Comment by RoccoRakete** [comment]
https://pastebin.com/Czyg72ft

**Comment by RoccoRakete** [comment]
> please use pastebin or similar and edit your post and just share the link, thx

jep. same mistake every time :D

**Comment by VeilSilence** [comment]
Same for me. 
I turned debug overlay and did clean system start. VFR disabled. No browser, not steam etc. Framerate on main monitor always changing. From 240fps -> 120 fps and then up/down. 
I started brave, and then i decide to test my browser framerate in "UFO test:Framerate". Test show 120fps. 
When i start OBS with replay recording, or activating "performance mode" on video card, brave framerate on this test back to stable 240fps. Same situation in desktop overlay. Stable framerate and no stuttering.
Tried same test on sway. Clean start -> brave -> UFO framerate test. It shows 240 fps. No need for "performance mode".

**Comment by vaxerski** [comment]
> sway

always check sway-git please

**Comment by vaxerski** [comment]
so far @end-4 is looking for the performance issues and has narrowed it down to fe007fd36a050103c7953bf5ba68d6ba7187b6e1 -> c386c52cf9fbd442e3c6efec4664d9907fd2cfb1 (nix build fails in between) which leads me to believe the wlroots bump from 677a3f to 5ae17d is at fault as nothing else would make sense in that frame, but if it's a wlroots bump causing the issue I also need someone to test on sway-git

**Comment by aruhier** [comment]
Can you check if it also happens while plugging a second screen and charging the laptop?

The same happened to me due to i915 powersaving, and on Tigerlake I made it better by enabling these options (refer to https://wiki.archlinux.org/title/Intel_graphics#Enable_GuC_/_HuC_firmware_loading):

```
options i915 enable_dc=4 enable_fbc=1 enable_guc=3 enable_psr=2 enable_psr2_sel_fetch=1 disable_power_well=1
```

Rebuild your initramfs and test. Be careful with the `enable_psr=2`, if you see any flickering, either remove this option or disable PSR totally with `enable_psr=0`.

**Comment by RoccoRakete** [comment]
I'll look into this, as soon as I'm home from work. Thank you for all this input!

**Comment by VeilSilence** [comment]
> > sway
> 
> always check sway-git please

i checked again with `sway-git` and `hyprland-git` All apps in this test wayland native.
1: Clean sway-git. Just brave and eww. No wallpaper. ~238-240fps out of box. 
2: My current hyprland setup ( blur enabled, shadows, rounding, animations, opacity ).  Brave + eww. Unstable fps as i mentioned early.
3: Created new user. Imported my config, but without all blur/shadows etc. No even wallpaper on background. Unstable fps on 240fps monitor. From 240 -> 120 again. Same results in brave "UFO" framerate test. 
Funny things is, when i disabled my second ( 60 fps ) monitor, framerate on main monitor down even deeper ( to 80 fps ).
"Performance mode" fixing this.

**Comment by RoccoRakete** [comment]
> > > sway
> > 
> > 
> > always check sway-git please
> 
> i checked again with `sway-git` and `hyprland-git` All apps in this test wayland native. 1: Clean sway-git. Just brave and eww. No wallpaper. ~238-240fps out of box. 2: My current hyprland setup ( blur enabled, shadows, rounding, animations, opacity ). Brave + eww. Unstable fps as i mentioned early. 3: Created new user. Imported my config, but without all blur/shadows etc. No even wallpaper on background. Unstable fps on 240fps monitor. From 240 -> 120 again. Same results in brave "UFO" framerate test. Funny things is, when i disabled my second ( 60 fps ) monitor, framerate on main monitor down even deeper ( to 80 fps ). "Performance mode" fixing this.

Interesting... How do you achive "performance mode"?

**Comment by VeilSilence** [comment]
[aruhier](https://github.com/aruhier) typed i think what you need for "performance mode" for intel graphics, or you can do window capture in obs and start `OBS Virtual Cam`. Your graphic card would run in higher clocks while OBS running.

**Comment by vaxerski** [comment]
@VeilSilence can you try an older version (e.g. 0.20, 0.15) and see if the performance is bad there too?

**Comment by RoccoRakete** [comment]
Starting a capture in OBS does in fact "fix" the issue.

**Comment by VeilSilence** [comment]
> @VeilSilence can you try an older version (e.g. 0.20, 0.15) and see if the performance is bad there too?

I tested all version from 0.15 to 0.20. I used "Release" version from github for this test.
I suspect that this bug connected somehow to issue #2442.
**0.15 version**: UFO test show 240 out of box, but every ~minute or so, fps down to 180 for 1 second and then quickly again 240. Glmark 2 quick test results:
```
[build] use-vbo=false: FPS: 4441 FrameTime: 0.225 ms
[build] use-vbo=true: FPS: 6475 FrameTime: 0.154 ms
[texture] texture-filter=nearest: FPS: 6670 FrameTime: 0.150 ms
```
**0.18 version**: looks same as 0.15 version, except that framedrops might occur more frequently ( sometimes every 20-23 seconds ). 240 fps -> quick drop to 180 for 1 seconds -> quick back up ( less than second ). glmark show same results as **0.15 version**
**0.19 version and 0.20 version**: this is where it start behave like it does right now. UFO test show 120-180fps, overlay show, that my fps is 170-175 for like 6 seconds, then it back up to 230 for ~3 seconds and quicky down again to 180-170fps. Glmark2 results:
```
[build] use-vbo=false: FPS: 2916 FrameTime: 0.343 ms
[build] use-vbo=true: FPS: 3755 FrameTime: 0.266 ms
[texture] texture-filter=nearest: FPS: 3778 FrameTime: 0.265 ms
```
Current hyprland git shows me almost same results in glmark2 as 0.19 version.  I didn't test this weird frame drop, where disabling  my 60fps monitor make fps down to 80.  I will test this if needed.

**Comment by RoccoRakete** [comment]
For me it seems to be related to my DP to HDMI cable..
But there has to be a solution for this, because it's working on X11, sway and Gnome Wayland. Maybe someone has a fix for that.

**Comment by vaxerski** [comment]
can you bisect the issue more precisely? The second change seems radical so it should be easy. The first, if you can, would help too.

`git bisect` will be your friend

**Comment by RoccoRakete** [comment]
> can you bisect the issue more precisely? The second change seems radical so it should be easy. The first, if you can, would help too.
> 
> 
> 
> `git bisect` will be your friend

Sorry? Could you explain that? 
I'm not that familiar with git and what that means.

**Comment by RoccoRakete** [comment]
Update: A new DP -> HDMI cable fixes the issue... 
But I really don't understand what's going on here, since as I mentioned, it works with other Hyprland DE's, X11 DE's and Windows. 
It also fixes the issue where I'm getting a black screen on start.

**Comment by VeilSilence** [comment]
> can you bisect the issue more precisely? The second change seems radical so it should be easy. The first, if you can, would help too.
> 
> `git bisect` will be your friend

I can do that, problem is that i can't compile from source old versions, unless i'm doing something wrong.
What do i do. 
1: `git clone --recurse-submodules https://github.com/hyprwm/Hyprland`
2: `git checkout 724e411ffcf1e2c528a7d4fb6fc24350076ad37f`
3: `git submodule update --init --recursive ( fatal: Unable to checkout '627a5c511278e67c3c308cdc6a639cbb490f48c3' in submodule path 'subprojects/wlroots'`, i guess need older wlroot? ) 
3.1: tried archived "github version" wlroots. `git submodule update --init --recursive ( Submodule path 'subprojects/wlroots': checked out '627a5c511278e67c3c308cdc6a639cbb490f48c3 )`
4: sudo make install 
Many errors on building. Tried different commit also ( df132e5ff3395a15c1b48461cc588e4222ae1e02 for example ).
Never did that before, so i suspect i do something really wrong. If someone help me with this problem, i will try to find this regression.
Master version compile without problem.

**Comment by vaxerski** [comment]
`git reset --hard <hash> --recurse-submodules && sudo make install` should work

**Comment by VeilSilence** [comment]
`git reset --hard 724e411ffcf1e2c528a7d4fb6fc24350076ad37f --recurse-submodules && sudo make install`
Error on building still. Terminal output in pastebin.
https://pastebin.com/utg36huv

**Comment by vaxerski** [comment]
that's a wlroots fault, does it happen only on that hash or always?

**Comment by VeilSilence** [comment]
Tested like 10 commits between 0.18 and 0.19 branch. Always build failed.

**Comment by vaxerski** [comment]
you can go into `subprojects/wlroots/meson.build` and edit line 10 to be `werror=false` instead of `true` and it should fix that.

**Comment by VeilSilence** [comment]
I checked commits between 0.18 and 0.19 and my results:
commit d2a7e22 Glmark2: `use-vbo=true: FPS: 6777 FrameTime: 0.148 ms` 
commit 5d39223 Glmark2:  `use-vbo=true: FPS: 6680 FrameTime: 0.150 ms`
commit f91f3d1 Glmark2:  `use-vbo=true: FPS: 6650 FrameTime: 0.150 ms`
commit 82fe530 Glmark2: `use-vbo=true: FPS: 6833 FrameTime: 0.146 ms`
commit ba05c43 Glmark2: `use-vbo=true: FPS: 6534 FrameTime: 0.153 ms`
commit 250d61e Glmark2: `use-vbo=true: FPS: 6641 FrameTime: 0.151 ms`
commit e887149 Glmark2: `use-vbo=true: FPS: 6860 FrameTime: 0.146 ms`
commit 0ffaa8d Glmark2: `use-vbo=true: FPS: 6532 FrameTime: 0.153 ms`
Brave + UFO Framerate test = same as 0.18
commit df132e5 Glmark2: `use-vbo=true: FPS: 3763 FrameTime: 0.266 ms`
Brave + UFO Framerate test = 120 fps in test, unstable fps in overlay like i mentioned early.
commit f88feec Glmark2:  `use-vbo=true: FPS: 3765 FrameTime: 0.266 ms`
main version  f864b15 Glmark2:  `use-vbo=true: FPS: 3730 FrameTime: 0.268 ms`
Brave + UFO Framerate test = overall better than commit df132e5, but still drops to 120 fps frequently.
I hope this helps.

**Comment by vaxerski** [comment]
as discussed in #2741 you should check -git's performance, recently had some massive improvements to both gpu and cpu usage

**Comment by VeilSilence** [comment]
> as discussed in #2741 you should check -git's performance, recently had some massive improvements to both gpu and cpu usage
i did check f864b15 `background: add option to force hypr chan` as i mentioned in my results.

**Comment by vaxerski** [comment]
my bad, didnt notice

**Comment by vaxerski** [comment]
I can't repro those, and since they seem to be introduced following a wlroots dep update, wouldn't this be a wlroots issue?

**Comment by VeilSilence** [comment]
> 
All tests i did on new user. 
On my current setup ( blur enabled, shadows, rounding, animations, vrr etc ) Brave + UFO Framerate test shows me 240 fps now, but Glmark2 test still low sadly compared to sway/old versions.

**Comment by vaxerski** [comment]
vfr is off by default????

![image](https://github.com/hyprwm/Hyprland/assets/43317083/296651af-91bb-4ec1-b7c4-3618a2c3850f)

since when??

**Comment by vaxerski** [comment]
> Not sure why, but enabling effects make performance better ( driver powersave )? or it is because vfr on ( disabled on new user for overlay )?

No clue.

> still low sadly compared to sway/old versions.

you bisected the issue to a wlroots dep update, so this is most likely wlroots' fault, tbh

**Comment by VeilSilence** [comment]
> vfr is off by default????
> 
> ![image](https://user-images.githubusercontent.com/43317083/255004946-296651af-91bb-4ec1-b7c4-3618a2c3850f.png)
> 
> since when??

No i just did what wiki says:

overlay | print the debug performance overlay. Disable VFR for accurate results.
-- | --

**Comment by vaxerski** [comment]
ah, yeah. VFR drastically improves performance.

**Comment by VeilSilence** [comment]
I can redo tests with vfr on if needed.
> ah, yeah. VFR drastically improves performance. The issue is overlay will show very low fps if nothing's changing with VFR on.

Should be wlroots issue yea. Maybe someone with intel videocard can test this and see if it same for them also.
Overall, on git version, my mouse no longer slugging on 240fps monitor because of framedrops. 
Thank you. Good job.

**Comment by romanstingler** [comment]
@VeilSilence 
is this what happens to you?
https://youtube.com/shorts/DoPU4ADRAfU?feature=share4

**Comment by VeilSilence** [comment]
> 

yea, look similar. 240 fps -> 120 fps and jumping between.

**Comment by romanstingler** [comment]
@VeilSilence does it also happen for you without the overlay??

**Comment by romanstingler** [comment]
@vaxerski should we close that issue, because it has been resolved and open another issue for the performance impact of the overlay?

**Comment by vaxerski** [comment]
probably.

Also refer here for more info: https://www.youtube.com/watch?v=PcRyjkYdDxM

**Comment by romanstingler** [comment]
> probably.
> 
> Also refer here for more info: https://www.youtube.com/watch?v=PcRyjkYdDxM

no clue if I should feel ashamed or proud of being austrian :)

**Comment by vaxerski** [comment]
digga dieser song ist unglaublich, was ist dein problem mit ihm :P

**Comment by RoccoRakete** [comment]
Ahh ich dachte jetzt kommt Money Boy :D
