### ISSUE TITLE
Poor Yuzu Performance on Hyprland - Not on Sway

### ISSUE THREAD

**Issue by A1029384756** [hyprwm/Hyprland#2638]
When running any games through Yuzu on Hyprland, performance is extremely poor.  Switching to Sway resolves this.
(I have previously run Yuzu through GNOME and got similar results to Sway)

My Setup:
- NixOS - [Config Here](https://github.com/A1029384756/nix-config)
- Hyprland from the Flake
- ASUS Zephyrus G14 - 2021
- Yuzu 1484 (Flatpak) (NVIDIA Vulkan)

### Steps to Reproduce
Run any Yuzu game

### FPS Comparison (In Menu)
- Hyprland => 8-14
- Sway => 60 (capped)

### Observations
When comparing Hyprland and Sway, the microprofile traces from Yuzu yielded vastly different results. One major observation was that the "Copy to Swapchain" step was taking drastically longer on the Hyprland side. For the most part, the "Execute Command Buffer" step remained unchanged between the two.  The other was that the frametimes were seemingly much less consistent on Hyprland's end.

@fufexan

**Comment by fufexan** [comment]
Doesn't seem to be a Nix-specific issue. In any case, @end-4 is on the hunt for the commit(s) that indroduced performance regressions so we may know more about what causes this when we have some of those commits figured out.

**Comment by end-4** [comment]
My yuzu is running great on the latest Hyprland though...

**Comment by vaxerski** [comment]
> Sway

sway or sway-git? always test on -git

**Comment by A1029384756** [comment]
Write the following `shell.nix` to build Sway from source.
```nix
{pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [
    bash-completion
    basu
    cairo
    cmake
    fish
    gdk-pixbuf
    glslang
    hwdata
    json_c
    libdisplay-info
    libdrm
    libevdev
    libinput
    libliftoff
    libxkbcommon
    mesa
    meson
    ninja
    pango
    pcre2
    pixman
    pkg-config
    scdoc
    seatd
    systemd
    vulkan-loader
    wayland
    wayland-protocols
    xorg.libX11
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    xwayland
  ];
}
```
When running through the latest Sway, the performance was nearly identical between the two (bad). Does that meant hat the problem is with wlroots?

**Comment by end-4** [comment]
your hardware is bad, or did you forget to plug in the charger or something?
i ran mario kart 8 deluxe on both the git version of hyprland and sway at 60fps and 16.67ms frame time. not to even mention that was using integrated radeon graphics.

**Comment by A1029384756** [comment]
Can confirm that it isn't the hardware (I had played TOTK for ~30hrs on Fedora before switching to NixOS). Out of curiosity, I reverted to the `nixpkgs` version of Hyprland and the performance went back up. The only common factor I've noticed (between both Sway and Hyprland both) is a change upstream in wlroots.

**Comment by vaxerski** [comment]
can you `git bisect` to narrow down the wlroots rev change that broke this?

**Comment by A1029384756** [comment]
I'm actually going to do a 180 and say the issue is completely on my end.  For a sanity check, I built Sway 1.8.1 (current release) and the corresponding wlroots version from source to test it out and got the same performance as I did on Sway-git.

Now why this is happening is a mystery to me, I built in release mode (`meson setup --buildtype=release --wipe build/`) and also tried manually adding `-Ofast -g3` to the meson build script but it would seem that this regression happens whenever I'm compiling it (I didn't use the cached flake builds). I can try using clang instead of gcc but in my experience, that has never made a noticeable difference.

**Comment by fufexan** [comment]
Can you check the output of `nix run nixpkgs#glxinfo`? If it doesn't report the correct GPU in renderer info and instead says llvmpipe, there's a mesa mismatch.

**Comment by A1029384756** [comment]
I get my AMD iGPU as the output which would make sense since I have supergfxctl set up.
I was fairly certain it wasn't using software rendering since my laptop doesn't sound like a jet engine and CPU usage was around ~(0-1)% according to btop.

That being said, I know Yuzu is using my NVIDIA GPU.  As an initial troubleshooting step, I had nvidia-smi open and was watching power usage and utilization and that was being registered in nvidia-smi.  I even turned on the `force max clock` option in Yuzu which ensured the GPU drew all it could of its 60W allowance and that had no effect.
