### ISSUE TITLE
relative and absolute mode for tablets

### ISSUE THREAD

**Issue by Eragonfr** [hyprwm/Hyprland#2639]
Currently there is no way to change the mode of a tablet outside of OpenTabletDriver. But the downside of this driver is it's lack of support for a lot of tablets which are supported by other drivers.

I would like to be able to switch the mode of my tablet, from absolute (the default) to relative.

**Comment by asiantuntija** [comment]
I'm in need of this also, relative is so much easier to work with that absolute.

Sway MR:
https://github.com/swaywm/sway/pull/5472

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13591285/patch.txt)
try this. Config option `input:tablet:relative_input = bool` or per-device `relative_input = bool`

**Comment by asiantuntija** [comment]
Seems to work just fine now, thanks!
