### ISSUE TITLE
Full RGB on intel gpus

### ISSUE THREAD

**Issue by MrPickles1324** [hyprwm/Hyprland#2642]
Option to set color range to Full RGB on intel gpus

**Comment by vaxerski** [comment]
what

**Comment by MrPickles1324** [comment]
on X11 you can set it with xrandr --output HDMI1 --set "Broadcast RGB" "Full"

**Comment by MrPickles1324** [comment]
There is a pr in wlroots that sets it to Full by default. If it will help. https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2310?commit_id=0096bf87b840b778f208f172922fdc8994ffa6dc#21d53b58cdaef47eaf15415ed33265b0ad69e420

**Comment by vaxerski** [comment]
this should be done on the wlroots side

**Comment by Computerdores** [comment]
If I understand correctly, then Hyprland is not based on wlroots anymore and this still isn't supported (active issue for me, also see [discussion 11607](https://github.com/hyprwm/Hyprland/discussions/11607)), so this issue should be reopened, right?

Edit: As a workaround the display refresh rate can be set to 58Hz. Presumably, this causes the "Automatic" preset (which is the default and changing it via libdrm's `proptest` doesn't work under Hyprland) to switch to Full RGB range for some reason, where as the normal 60Hz refresh rate causes it to use Limited RGB.
