### ISSUE TITLE
[Feature Request] border_on_floating_only

### ISSUE THREAD

**Issue by donovanglover** [hyprwm/Hyprland#2651]
It would be cool if there was a variable to only show borders on floating windows. This would make floating windows look better visually while still allowing tiled windows to have no borders/gaps.

Could be easy to implement since `no_border_on_floating` already exists.

**Comment by vaxerski** [comment]
doable after 2c7b2ad6ca19950f13ec4a97204bb8ff18096bb3 with

```
windowrulev2 = bordersize x, floating:1
```

**Comment by FullStackAlex** [comment]
There seems to be a bug now. I get this error when I  try to set bordersize for windowrulev2:
![image](https://github.com/hyprwm/Hyprland/assets/18289087/52ab2aeb-feae-42f9-901b-ca177ac597d5)

Everything else seems to work for me in Hyprland.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/4abd6f84-3546-48a2-b41f-de8885c7bfb8)
odd. Works just fine for me

**Comment by FullStackAlex** [comment]
How could I get to the root of the issue / debug it without knowledge of C++?

**Comment by vaxerski** [comment]
first thing I'd do is compile from source

**Comment by FullStackAlex** [comment]
Ok, I'll try. Thanx
