### ISSUE TITLE
XWayland windows still listed as clients after closing

### ISSUE THREAD

**Issue by NTICompass** [hyprwm/Hyprland#2653]
I am using hyprland-autoname-workspaces (v 1.1.2) along with hyprland.

`hyprctl version` says:
```
Hyprland, built from branch main at commit 981c71e60a4db9838e82dd721f0e5ae4981529aa dirty (Nix CI: split inputs and wlroots updating).
Tag: v0.26.0-88-g981c71e6
```

Anyway, I am seeing an issue with apps that close themselves to the system tray, like Slack or Discord.

I have them both open on a workspace, as seen here:
![05 07 2023_shot_12:19:18](https://github.com/hyprwm/hyprland-wiki/assets/409247/35ac9b28-4695-4844-b8cd-4ec95845d024)

But, when I close their windows, they are still "open" on the workspace, now as an "unknown" icon:
![05 07 2023_shot_12:19:26](https://github.com/hyprwm/hyprland-wiki/assets/409247/befaccca-097a-492f-9ee7-a8e344b74473)

I'm not sure what project this bug is from, but I also posted it on `hyprland-autoname-workspaces`: https://github.com/hyprland-community/hyprland-autoname-workspaces/issues/86#issuecomment-1622091242

Looking at `hyprctl clients`, I see some weirdness.
Discord is not open, it's closed in the system tray.
```
Window 5613aaf73660 -> Friends - Discord:
	mapped: 0
	hidden: 0
	at: 2035,154
	size: 744,803
	workspace: 2 (2:  ²)
	floating: 0
	monitor: 1
	class: 
	title: 
	initialClass: discord
	initialTitle: Friends - Discord
	pid: 13316
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

Slack is also not open, it's also closed to the system tray.
```
Window 5613aaf8df90 -> Something - Slack:
	mapped: 0
	hidden: 0
	at: 2129,154
	size: 1500,803
	workspace: 2 (2:  ²)
	floating: 0
	monitor: 1
	class: 
	title: 
	initialClass: Slack
	initialTitle: Something - Slack
	pid: 13063
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

Then I am also seeing a lot of windows on monitor -1 and/or workspace -1:
```
Window 5613aaf8f3f0 -> :
	mapped: 0
	hidden: 0
	at: 0,0
	size: 0,0
	workspace: -1 ()
	floating: 0
	monitor: -1
	class: 
	title: 
	initialClass: 
	initialTitle: 
	pid: 0
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

EDIT: I tried this with a program that does NOT run in XWayland (like QuodLibet) and this does not happen.  So I think this may be an issue only with XWayland windows/apps.

**Comment by NTICompass** [comment]
I think I "fixed" this issue with the following config in `hyprland-autoname-workspaces`

```
[exclude]
"" = "^$"
```

**Comment by cyrinux** [comment]
> I think I "fixed" this issue with the following config in `hyprland-autoname-workspaces`
> 
> ```
> [exclude]
> "" = "^$"
> ```

@NTICompass I give you some others informations in the other issues, but for workaround this kind of bug or weirdness behavior, I filter now negative/0 pid client in hyprland-autoname-workspaces.

**Comment by vaxerski** [comment]
`mapped: 0` windows mean they are not present.

X11 is a garbage protocol and yes some windows stay unmapped for a while.
