### ISSUE TITLE
Regression: Terraria don't register mouse clicks with rapid release

### ISSUE THREAD

**Issue by rszyma** [hyprwm/Hyprland#2659]
Mouse clicks worked in Terraria (via steam) normally in https://github.com/hyprwm/Hyprland/commit/51a930f802c71a0e67f05e7b176ded74e8e95f87 but in bc34713 mouse clicks don't register if tap and release is very rapid.

I did bisect and this is the result:

```
> git bisect bad                                                                                                                                                                        
cfa4086b0b2a2c870504b8f74b6e5b5ba276d1fc is the first bad commit
commit cfa4086b0b2a2c870504b8f74b6e5b5ba276d1fc
Author: vaxerski <vaxry@vaxry.net>
Date:   Wed Jun 21 20:58:35 2023 +0200

    configmgr: fix idiotic comparisons in device configs

 src/config/ConfigManager.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

This may not be Terraria-only issue, also the bug persists in Stardew Valley. I didn't test in other steam games.

**Comment by vaxerski** [comment]
check your input configs if that's the faulty commit. It fixed some fallback values in per-device configs.

**Comment by rszyma** [comment]
what should I look for exactly?

**Comment by rszyma** [comment]
this is the input part of my config 
```
input {
    kb_layout=pl
    kb_options=
    kb_variant=
    kb_model=
    kb_rules=
    repeat_rate=50 # 50
    repeat_delay=250 # 300
    numlock_by_default=1
    left_handed=0

    follow_mouse=1
    float_switch_override_focus=0
    # force_no_accel=0
    # accel_profile = flat

    touchpad {
        disable_while_typing=0
        natural_scroll=1
        clickfinger_behavior=1
        middle_button_emulation=1
        tap-to-click=1
        drag_lock=0
    }
}

device:elan071a:00-04f3:30fd-touchpad {
    sensitivity = -0
    natural_scroll = 1
    accel_profile = linear # adaptives
}

device:Logitech G403 Prodigy Gaming Mouse {
    accel_profile = flat
}

device:mx-anywhere-3-mouse {
    # sensitivity =
    accel_profile = flat
}

device:kanata-1 {
    # sensitivity =
    accel_profile = flat
}

```

**Comment by vaxerski** [comment]
check what happens if you remove your device configs, try applying the touchpad options to your device config directly, fiddle with it. Something's wrong there

**Comment by rszyma** [comment]
if I comment `middle_button_emulation=1` or set it to `0` the bug disappears

**Comment by vaxerski** [comment]
maybe you should set it to 0 for your gaming mouse then?

![image](https://github.com/hyprwm/Hyprland/assets/43317083/c3859f1f-3c11-4739-9059-bb18d9ec7887)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/11968814/patch.txt)

try this patch

**Comment by rszyma** [comment]
works

**Comment by vaxerski** [comment]
e632bf176b04968ca6a22f6e5d5f1a7bf77b6fa6
