### ISSUE TITLE
ALTSHIFT doesn't work with TAB

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#266]
I tried `bind=ALTSHIFT,TAB,workspace,m-1`, but it won't work as it sees a shifted tab as as different character than tab itself. I woudn't know as what though.

**Comment by vaxerski** [comment]
please read the wiki, you can use `xev` or `wev` to get live keystroke details.

**Comment by EysseW** [comment]
I'm sorry, should've done better research.
