### ISSUE TITLE
Close event with X11 application send too soon ?

### ISSUE THREAD

**Issue by cyrinux** [hyprwm/Hyprland#2664]
Hi, 

I feel like with my autoname toy I find an issue due to X11 close event send too soon when the app is still alive.
The behavior when I close wayland client is OK.

Basically, I receive a close event, and fetch the client list then, and I still fetch the client I just close.

This looks like a race condition, maybe there is more processing with X11 app, I don't known.

I try several things in `src/events/Windows.cpp` moving `EMIT_HOOK_EVENT("closeWindow", PWINDOW)` in several places but this doesn't help.

At the end from my side, I can only make an ugly time based fix, I would like we find the root cause.

Any idea ?

Thanks

**Comment by vaxerski** [comment]
close = unmap, X11 windows tend to stay unmapped for a while. Not really an issue here, you can just ignore those that have the `mapped: false` state.
