### ISSUE TITLE
Layer rules rounding

### ISSUE THREAD

**Issue by Skane-Gahi** [hyprwm/Hyprland#2667]
I was starting to use the layer rules on my EWW (ElKowar's Wacky Widgets) configuration and it is working pretty well until I noticed a minor issue. The blur layer is just not rounded at all but my hyprland config sets a rounding of 10. Even the css of my widgets applies border-radius and it indeed round the widget but it seems hyprland does not see it.

So I don't know if it is intended or not but I would like to apply rounding to a layer rule.

System : Arch Linux
Compositor : Hyprland
Widgets : EWW

EDIT: was able to fix the issue using the ingorezero rule. This take into account the roundings as the pixels normally here becomes invisible when applying the border-radius.

**Comment by Bavalionprolate** [comment]
>EDIT: was able to fix the issue using the ingorezero rule. This take into account the roundings as the pixels normally here becomes invisible when applying the border-radius.

Can you explain more, I'm having the same problem.

**Comment by Bavalionprolate** [comment]
I figured out what you mean, and it worked for me, too.
For those who have encountered the same problem, you need to set the layer rules as Skane-Gahi said. Here's the rule itself:
~~~
layerrule = ignorezero, gtk-layer-shell
~~~
