### ISSUE TITLE
Mouse stuttering when changing focus

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2669]
When changing focus, either by moving the mouse (with `follow_mouse=1`) or using keybinds, the mouse rendering becomes very choppy for about a second, after which it becomes smooth again. The application seems to receive accurate and smooth mouse events (verified by hovering over an SDL window which draws a square at the moue position), but Hyprland's rendering of the cursor itself is very choppy. Here are the logs when reproducing this between a `foot` window and Firefox:
```
[LOG] Set keyboard focus to surface 55d3030595c0, with window name: foot
[LOG] Set keyboard focus to surface 55d300fbe040, with window name: New Issue · hyprwm/Hyprland — Mozilla Firefox
[LOG] Set keyboard focus to surface 55d3030595c0, with window name: foot
```

I cannot record this issue as it disappears when OBS is capturing.

**Comment by vaxerski** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

try this
[patch.txt](https://github.com/hyprwm/Hyprland/files/11992463/patch.txt)

**Comment by TheSunCat** [comment]
Looking good! No lag after applying.

**Comment by vaxerski** [comment]
b33d82734fb3b88b87e1c89cbf2ec8883ea029ac and leave me alon

**Comment by TheSunCat** [comment]
This is unfortunately started happening again despite the patch. I think it relates to screen sharing, as it started happening while in a call. I am no longer sharing my screen but the lag is still occurring.

**Comment by chrispro-21** [comment]
I am experiencing this on my desktop as well. Weirdly enough, I found I didn't experience the problem when I had OBS running with pipewire.

**Comment by krakow10** [comment]
This issue can be observed more easily by running a cpu-heavy process like compiling (the linux kernel) or video encoding.  Smooth mouse movement when staying on the same application, choppy and delayed mouse movement when crossing a window border.  I have 3 monitors, so perhaps it only happens with multi-monitor configurations.

**Comment by SamuelGogarty** [comment]
Hi @chrispro-21 
I was recently running into this exact issue too, was puzzled why it would go away when I had OBS open.

A helpful person on the hyprland discord suggested adding the following to my config:
```
cursor {
    no_hardware_cursors = true
}
```
This fixed the issue for me.

**Comment by chrispro-21** [comment]
> Hi @chrispro-21 I was recently running into this exact issue too, was puzzled why it would go away when I had OBS open.
> 
> A helpful person on the hyprland discord suggested adding the following to my config:
> 
> ```
> cursor {
>     no_hardware_cursors = true
> }
> ```
> 
> This fixed the issue for me.

Thank you! This fixed it for me as well!
