### ISSUE TITLE
Mouse is laggy in game menus

### ISSUE THREAD

**Issue by NormalFall** [hyprwm/Hyprland#267]
Mouse will run at around 20 fps while the game is running at 100+ fps
Issue applies in most fps games outside of Minecraft and CS:GO

note: Trackmania 2020 has this this problem but doesn't have any mouse restraints

**Comment by NormalFall** [comment]
> well if the system is at 100% it's obvious it will slow down, no? I'd recommend to disable blur during gaming.

The problem is that the game is running at 80fps and the mouse isnt

**Comment by vaxerski** [comment]
try disabling blur, mouse is a CPU thing anyway

**Comment by NormalFall** [comment]
https://user-images.githubusercontent.com/93881091/176009812-e788e2b7-ac27-404d-b1e8-29d266df67f8.mp4

Bruh

**Comment by vaxerski** [comment]
no clue. your PC might be haunted.

**Comment by ThatOneCalculator** [comment]
@taylor85345 How do you run a game under gamescope on Hyprland?

**Comment by romanstingler** [comment]
@NormalFall can you still reproduce this without gamescope?

**Comment by NormalFall** [comment]
This issue never occurred outside of gamescope and got fixed a few months ago. 

You should open a separate issue for this.

**Comment by NormalFall** [comment]
Nope it got fixed around 6 months ago. Maybe check is your GPU or CPU hits 100%? I don't remember the issue quite well since its old but i think it was related to that.
Also i just noticed that it was only happening to proton games.

If you problem doesn't match up with this you should open a separate issue @romanstingler

**Comment by romanstingler** [comment]
@NormalFall THX for the reply, I was just looking at old open issues and wanted to know if we can close it.
If it doesn't occur anymore, please close it. 
THX
