### ISSUE TITLE
External Monitor (sometimes) not detected at full resolution

### ISSUE THREAD

**Issue by Elias-Graf** [hyprwm/Hyprland#2671]
So this is sadly one of those things, I can't really tell you how to reproduce.
Anyhow, sometimes my 4k monitor is not detected at its full resolution:

**DP-1 is the relevant monitor here.**

```
[elias@fedora ~]$ hyprctl monitors
Monitor eDP-1 (ID 0):
	2560x1600@60.000999 at 0x0
	description: Apple Computer Inc Color LCD (eDP-1)
	make: Apple Computer Inc
	model: Color LCD
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 50 0 0
	scale: 1.50
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-1 (ID 1):
	2560x1440@143.998993 at 1706x0
	description: GIGA-BYTE TECHNOLOGY CO., LTD. Gigabyte M32U 22511B001843 (DP-1)
	make: GIGA-BYTE TECHNOLOGY CO., LTD.
	model: Gigabyte M32U
	serial: 22511B001843
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 50 0 0
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

When I plug the monitor in, I get the input information popup saying "USB-C 2560x1440" (the monitor's OSD).

Currently, my monitors are configured like this:

```
monitor=eDP-1, preferred, auto, 1.5
monitor=DP-1, highres, auto, 1.5
```

When I try to "force" the resolution to 4k, using `monitor=DP-1, 3840x2160@60, auto, 1.5`, it just uses the 1440p part of the screen, and draws a gray border around it.

Here, a picture of that I took with my phone, because I cannot screenshot the gray area:

![image](https://github.com/hyprwm/Hyprland/assets/46671625/81980eae-7a12-4431-be27-106c145abdf6)

**Interestingly, I am able to move my cursor into the gray area, so something somewhere is able to correctly drive the display.**

Also, I don't think the USB cable is able to drive the monitor at 4k@144hz (which is the refresh rate it's detected at), but I'm not certain about that.

Randomly, the monitor is detected as 4k again. So as a workaround, I'm alternating between the scaling factor 1, and 1.5, depending on what resolution the monitor is detected at.

# Version

```
[elias@fedora ~]$ hyprctl version
Hyprland, built from branch main at commit b33d82734fb3b88b87e1c89cbf2ec8883ea029ac dirty (input: schedule frame on mouse move).
Tag: v0.26.0-97-gb33d8273

flags: (if any)
```

**Comment by vaxerski** [comment]
check with sway, but drm issues are wlroots' fault if anything

**Comment by justinvson-pd** [comment]
Having the same issue with 2x DP monitors running at 1440p, in issue #3431.

**Comment by Elias-Graf** [comment]
@RaySlash 

```
DP-1 "GIGA-BYTE TECHNOLOGY CO., LTD. Gigabyte M32U 22511B001843 (DP-1)"
  Make: GIGA-BYTE TECHNOLOGY CO., LTD.
  Model: Gigabyte M32U
  Serial: 22511B001843
  Physical size: 700x390 mm
  Enabled: yes
  Modes:
    3840x2160 px, 59.997002 Hz (preferred)
    3840x2160 px, 60.000000 Hz
    3840x2160 px, 59.939999 Hz
    3840x2160 px, 50.000000 Hz
    3840x2160 px, 30.000000 Hz
    3840x2160 px, 29.969999 Hz
    3840x2160 px, 25.000000 Hz
    3840x2160 px, 24.000000 Hz
    3840x2160 px, 23.976000 Hz
    2560x1440 px, 143.998993 Hz (current)
    2560x1440 px, 119.998001 Hz
    2560x1440 px, 59.951000 Hz
    1920x1080 px, 144.001007 Hz
    1920x1080 px, 119.999001 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 50.000000 Hz
    1680x1050 px, 59.953999 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1440x900 px, 59.887001 Hz
    1280x960 px, 60.000000 Hz
    1152x864 px, 75.000000 Hz
    1280x720 px, 120.000000 Hz
    1280x720 px, 119.879997 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 50.000000 Hz
    1440x576 px, 50.000000 Hz
    1440x576 px, 50.000000 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 70.069000 Hz
    1024x768 px, 60.004002 Hz
    1440x480 px, 60.000000 Hz
    1440x480 px, 60.000000 Hz
    1440x480 px, 59.939999 Hz
    1440x480 px, 59.939999 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 72.188004 Hz
    800x600 px, 60.317001 Hz
    800x600 px, 56.250000 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 72.808998 Hz
    640x480 px, 66.667000 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
    720x400 px, 70.082001 Hz
  Position: 1706,0
  Transform: normal
  Scale: 1.500000
  Adaptive Sync: disabled
eDP-1 "Apple Computer Inc Color LCD (eDP-1)"
  Make: Apple Computer Inc
  Model: Color LCD
  Serial: (null)
  Physical size: 290x180 mm
  Enabled: yes
  Modes:
    2560x1600 px, 60.000999 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 1.500000
  Adaptive Sync: disabled
  ```

**Comment by RaySlash** [comment]
@Elias-Graf  try setting them manually such as:
```
monitor=eDP-1,2560x1600@60,0x0,1.5
monitor=DP-1,2560x1440@144,0x2560, 1.5
```

You might have to play around with it to get your best setting for you.

**Comment by Elias-Graf** [comment]
> @Elias-Graf  try setting them manually such as:
> ```
> monitor=eDP-1,2560x1600@60,0x0,1.5
> monitor=DP-1,2560x1440@144,0x2560, 1.5
> ```
> 
> You might have to play around with it to get your best setting for you. Something similar is  in this [ISSUE](https://github.com/hyprwm/Hyprland/issues/3086)

I did try that, although for 4k, if you see my original question.

**Comment by Elias-Graf** [comment]
@RaySlash did I do something incorrectly? Would be awesome if I could fix this. Now having the same issue on a different OS (previously fedora, now nixos), with a different laptop.

**Comment by izmyname** [comment]
Is this still actual?

**Comment by vaxerski** [comment]
I think we can close this since the mov eto aq
