### ISSUE TITLE
How to move any window to bottom layer?

### ISSUE THREAD

**Issue by Dark-Kernel** [hyprwm/Hyprland#2674]
I am trying to get something like: https://imgur.com/a/8Mq4A

Actually, I want Cava to run on any window transparent and move it to the bottom layer so it won't affect other windows.

Thanks.

**Comment by vaxerski** [comment]
you can't

**Comment by Dark-Kernel** [comment]
So, there is no chance to get what I want?

**Comment by vaxerski** [comment]
it should be the client's job tbh - https://github.com/kovidgoyal/kitty/pull/2590

you can write your own I guess

**Comment by Dark-Kernel** [comment]
I'm sorry but, I can't.

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/hyprland-plugins/tree/main/hyprwinwrap should handle this
@vaxerski

**Comment by Dark-Kernel** [comment]
> https://github.com/hyprwm/hyprland-plugins/tree/main/hyprwinwrap should handle this @vaxerski

Thanks @MightyPlaza  will try and let you know the review.
