### ISSUE TITLE
Crash on first launch (Black screen)

### ISSUE THREAD

**Issue by RoccoRakete** [hyprwm/Hyprland#2677]
When I first start hyprland, no matter if from a tty or via a loginmanager, I get a black screen until I unplug the monitor and plug it back in. This kicks me back to the tty and I can starhyprland just as usual..

Log:

https://pastebin.com/rHQvy77L

**Comment by RoccoRakete** [comment]
#2637
Same thing, seems to be related to the DP -> HDMI Cable

**Comment by romanstingler** [comment]
have you tested it recently ??

**Comment by RoccoRakete** [comment]
> have you tested it recently ??

I haven't had this issue in months, since I don't use the HDMI to DP cable anymore.
