### ISSUE TITLE
xdg-desktop-portal-hyprland crashed when using OBS

### ISSUE THREAD

**Issue by yfaimisaka** [hyprwm/Hyprland#2679]
**description**:
when using OBS to record screen, **full screen recording is ok**, while **seperate window recording** or **region recording** gives a black screen on OBS.

**machine and soft version**:
- `Arch Linux`
- `Linux 6.4.2-zen1-1-zen`
- GPU: `Intel Alder Lake-P` and `NVIDIA GeForce RTX 3050 Mobile`
- `hyprland-nvidia 0.26.0-1`
- `xdg-desktop-portal-hyprland 0.4.0-1`

**logs**:
- `Hyprland log`:  [hyprland.log](https://github.com/hyprwm/Hyprland/files/12013110/hyprland.log)
- `Hyprland Crash Report`:  [hyprlandCrashReport2059.txt](https://github.com/hyprwm/Hyprland/files/12013140/hyprlandCrashReport2059.txt) (file created at Jul 11 16:05, don't think it's relevant)
- `coredump info`: [coredump_info.log](https://github.com/hyprwm/Hyprland/files/12013181/coredump_info.log)
- `pipewire`:  [pipewire.log](https://github.com/hyprwm/Hyprland/files/12013188/pipewire.log) (may be relevant?)

**Comment by tchofy** [comment]
Seems like a dupe of https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58.

As said in the issue above, downgrading obs to 29.0.2-6, seems to "fix" it for now.

**Comment by vaxerski** [comment]
build xdph in debug and provide the stacktrace from the coredump

**Comment by yfaimisaka** [comment]
> 

sorry for stupid, how can i build xdph in debug?(not family with meson and ninja)

**Comment by yfaimisaka** [comment]
> build xdph in debug and provide the stacktrace from the coredump ples

sorry for stupid, how can i build xdph in debug?(not family with meson and ninja)

**Comment by ronchaine** [comment]
`meson configure build -Dbuildtype=debug`

For core dumps, check:
https://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-on-a-segmentation-fault

**Comment by vaxerski** [comment]
Wait, if this is an xdph crash, why is this here? Wrong tracker...?
