### ISSUE TITLE
Window rule for browser window not work

### ISSUE THREAD

**Issue by hvppydvddy** [hyprwm/Hyprland#2687]
For the test i try to set float mode for browser window with title "Google - Mozilla Firefox"
`windowrulev2 = float,class:^(Firefox)$,title:^(Google - Mozilla Firefox)$`
Also try:
`windowrulev2 = float,class:^(Firefox)$,title:^(Google)(.*)$`
`windowrulev2 = float,title:^(Google - Mozilla Firefox)$`
`windowrulev2 = float,title:^(.*Google.*)$` 
and it dont work too.

**Comment by hvppydvddy** [comment]
At version 0.27 same problem

**Comment by MightyPlaza** [comment]
float is not a dynamic rule so what matters is the initialClass and initialTitle, since it doesn't update on title or class change
```
initialClass: firefox
initialTitle: Mozilla Firefox
```

**Comment by MightyPlaza** [comment]
that's not currently possible

**Comment by vaxerski** [comment]
it is, make a script listening to the activewindowv2 event

**Comment by iris-garcia** [comment]
I'm facing the same issue with Firefox addons and their popups windows, this isn't very pleasant, I did the script  where I check for `windowtitlev2` and it works, but you still can see a delay which makes it ugly workaround.
