### ISSUE TITLE
connector DP-1: Atomic commit failed: Permission denied

### ISSUE THREAD

**Issue by juvevood** [hyprwm/Hyprland#2696]
[LOG] Hyprland PID: 760
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: juve-archlinux
[LOG] Release: 6.4.3-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Tue, 11 Jul 2023 05:13:39 +0000

[LOG] GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================
.....

[LOG] Callback 55b85f3ee608 -> 55b85f3ee600, IdleInhibitor removed.
[LOG] Destroyed an idleinhibitor
[wlr] [backend/session/session.c:181] udev event for card0 (change)
[wlr] [backend/session/session.c:210] DRM device card0 changed
[wlr] [backend/drm/backend.c:156] Received hotplug event for /dev/dri/card0
[wlr] [backend/drm/drm.c:1509] Scanning DRM connector 78 on /dev/dri/card0
[wlr] [backend/drm/drm.c:1182] Reallocating CRTCs
[wlr] [backend/drm/drm.c:1193] State before reallocation:
[wlr] [backend/drm/drm.c:1207]   'eDP-1': crtc=1 status=connected want_crtc=1
[wlr] [backend/drm/drm.c:1207]   'DP-1': crtc=0 status=connected want_crtc=1
[wlr] [backend/drm/drm.c:1207]   'DP-2': crtc=-1 status=disconnected want_crtc=0
[wlr] [backend/drm/drm.c:1256] State after reallocation:
[wlr] [backend/drm/drm.c:1260]   'eDP-1': crtc=1
[wlr] [backend/drm/drm.c:1260]   'DP-1': crtc=0
[wlr] [backend/drm/drm.c:1260]   'DP-2': crtc=-1
[wlr] [backend/session/session.c:181] udev event for card0-DP-1 (add)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/session/session.c:181] udev event for card0 (change)
[wlr] [backend/session/session.c:210] DRM device card0 changed
[wlr] [backend/drm/backend.c:156] Received hotplug event for /dev/dri/card0
[wlr] [backend/drm/drm.c:1509] Scanning DRM connector 85 on /dev/dri/card0
[wlr] [backend/drm/drm.c:1182] Reallocating CRTCs
[wlr] [backend/drm/drm.c:1193] State before reallocation:
[wlr] [backend/drm/drm.c:1207]   'eDP-1': crtc=1 status=connected want_crtc=1
[wlr] [backend/drm/drm.c:1207]   'DP-1': crtc=0 status=connected want_crtc=1
[wlr] [backend/drm/drm.c:1207]   'DP-2': crtc=-1 status=disconnected want_crtc=0
[wlr] [backend/drm/drm.c:1256] State after reallocation:
[wlr] [backend/drm/drm.c:1260]   'eDP-1': crtc=1
[wlr] [backend/drm/drm.c:1260]   'DP-1': crtc=0
[wlr] [backend/drm/drm.c:1260]   'DP-2': crtc=-1
[wlr] [backend/session/session.c:181] udev event for card0-DP-2 (add)
[wlr] [backend/session/session.c:181] udev event for card0 (change)
[wlr] [backend/session/session.c:210] DRM device card0 changed
[wlr] [backend/drm/backend.c:156] Received hotplug event for /dev/dri/card0
[wlr] [backend/drm/drm.c:1509] Scanning DRM connector 91 on /dev/dri/card0
[wlr] [backend/drm/drm.c:1182] Reallocating CRTCs
[wlr] [backend/drm/drm.c:1193] State before reallocation:
[wlr] [backend/drm/drm.c:1207]   'eDP-1': crtc=1 status=connected want_crtc=1
[wlr] [backend/drm/drm.c:1207]   'DP-1': crtc=0 status=connected want_crtc=1
[wlr] [backend/drm/drm.c:1207]   'DP-2': crtc=-1 status=disconnected want_crtc=0
[wlr] [backend/drm/drm.c:1256] State after reallocation:
[wlr] [backend/drm/drm.c:1260]   'eDP-1': crtc=1
[wlr] [backend/drm/drm.c:1260]   'DP-1': crtc=0
[wlr] [backend/drm/drm.c:1260]   'DP-2': crtc=-1
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[wlr] [backend/drm/atomic.c:72] connector DP-1: Atomic commit failed: Permission denied
[wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
[LOG] Switching from VT 1 to VT 3
[LOG] Switched to VT 3, destroyed all render data, frames to skip for each: 2
[wlr] [backend/libinput/events.c:140] Removing Varmilo VD-1 Keyboard [13:0]
[LOG] Callback 55b85e0d3aa8 -> 55b85e0d3aa0, Keyboard removed.
[LOG] Callback 55b85e0d3970 -> 55b85e0d3968, Keyboard removed.
[LOG] Callback 55b85e0d39d8 -> 55b85e0d39d0, Keyboard removed.
[LOG] Callback 55b85e0d3a40 -> 55b85e0d3a38, Keyboard removed.
[LOG] Destroyed keyboard 55b85e0d3940
[LOG] Callback 55b85e112728 -> 55b85e112720, Mouse removed.
[wlr] [backend/libinput/events.c:140] Removing Power Button [0:1]
[LOG] Callback 55b85df68458 -> 55b85df68450, Keyboard removed.
[LOG] Callback 55b85df68320 -> 55b85df68318, Keyboard removed.
[LOG] Callback 55b85df68388 -> 55b85df68380, Keyboard removed.
[LOG] Callback 55b85df683f0 -> 55b85df683e8, Keyboard removed.
[LOG] Destroyed keyboard 55b85df682f0

**Comment by juvevood** [comment]
When I open software such as Chrome ,Idea or others,  Hyprland will crash after a while. please

**Comment by vaxerski** [comment]
this looks like a driver issue, what about with `WLR_DRM_NO_ATOMIC=1`

**Comment by juvevood** [comment]
> this looks like a driver issue, what about with `WLR_DRM_NO_ATOMIC=1`

Thanks,it's works. but new issue:

```
[wlr] [backend/drm/legacy.c:160] connector DP-1: drmModeSetCursor failed: Permission denied
[wlr] [backend/drm/legacy.c:157] drmCloseBufferHandle failed: Invalid argument
[wlr] [backend/drm/legacy.c:160] connector DP-1: drmModeSetCursor failed: Permission denied
[wlr] [backend/drm/legacy.c:157] drmCloseBufferHandle failed: Invalid argument
[wlr] [backend/drm/legacy.c:160] connector DP-1: drmModeSetCursor failed: Permission denied
[wlr] [backend/drm/legacy.c:157] drmCloseBufferHandle failed: Invalid argument
[wlr] [backend/drm/legacy.c:160] connector DP-1: drmModeSetCursor failed: Permission denied
[wlr] [backend/drm/legacy.c:157] drmCloseBufferHandle failed: Invalid argument
[wlr] [backend/drm/legacy.c:160] connector DP-1: drmModeSetCursor failed: Permission denied
[wlr] [backend/drm/legacy.c:157] drmCloseBufferHandle failed: Invalid argument
[wlr] [backend/drm/legacy.c:160] connector DP-1: drmModeSetCursor failed: Permission denied
```

**Comment by vaxerski** [comment]
something's wrong on your side. Driver issue most liklely
