### ISSUE TITLE
Screenshot blank on right monitor but not on left with a two monitor setup

### ISSUE THREAD

**Issue by Moltenkore** [hyprwm/Hyprland#2697]
I've got a two monitor setup with a 1080p display on the left and a 3440x1440 screen on the right. The right monitor is my main one. The left is plugged in via HDMI and the right is plugged into DP.

If I try and take a screenshot with the right monitor it comes out completely blank but if I try and take a screenshot on the left monitor.. it works. 

I'm not sure what's going on.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12038698/hyprland.log)

**Comment by Moltenkore** [comment]
Oh interesting, I had the bit depth set to 10 for the right display. 

I set it back to default and screenshots work again.

**Comment by MightyPlaza** [comment]
10 bit doesn't currently work

**Comment by Moltenkore** [comment]
Ah okay, is that overall or just for screenshots etc?

**Comment by vaxerski** [comment]
closing as stale
