### ISSUE TITLE
Flickering on external monitor with v0.27

### ISSUE THREAD

**Issue by Vaider7** [hyprwm/Hyprland#2699]
After updating the system, the external monitor flickers terribly. Tried both fixing methods described in wiki, neither helped. Tried to downgrade nvidia dirver, kernel, didn't help too. Tried to build from source applying `glFinish` instead of `glFlush`, also it didn't help. 

The only one workaround I found is to downgrade to v0.26. In this case everything is perfect.

**Comment by fraschm1998** [comment]
I opened the same issue as per https://github.com/hyprwm/Hyprland/issues/2698

**Comment by fraschm1998** [comment]
Also occurs using https://github.com/djpohly/dwl
