### ISSUE TITLE
Damage tracking issues on GTK context menus after moving window

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2703]
Steps to reproduce:
- open a right-click menu on a GTK app, such as Firefox
- without closing it, move the window a bit
- try hovering over entries and observe how it is broken
If you open a submenu that goes outside of the bounds of the Firefox window, it sometimes gets burned-in to the background until you hover over it again.

![image](https://github.com/hyprwm/Hyprland/assets/44881120/fc0bef9b-ef01-475f-a512-05f92540c3ef)

**Comment by zjeffer** [comment]
Can confirm:

https://github.com/hyprwm/Hyprland/assets/4633209/1e4c6c55-6e0a-4d95-8488-2a0145eb7f9b

**Comment by TheSunCat** [comment]
This is fixed as of the subsurface rewrite.
