### ISSUE TITLE
Click-and-drag GTK menus translates mouse to top left of parent

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2704]
When you click-and-drag to interact with a GTK menu, mouse coordinates are wrong. It appears the position relative to the menu is made relative to the parent instead. If I click-and-__hold__, then let go, the mouse coordinates are correct.

Here is a video demonstrating the issue. For each context menu, I first click-and-drag to try to interact with it, triggering the bug. Then, I close it, and click-and-__hold__, let go, and show the mouse coordinates being correct.

https://github.com/hyprwm/Hyprland/assets/44881120/c6748356-3a44-4b30-8868-5fa38114cb0c

**Comment by vaxerski** [comment]
right, it should not focus the subsurface.

**Comment by TheSunCat** [comment]
Unable to repro anymore, thanks! Will close this if it does not happen again for a while (since it was intermittent).
