### ISSUE TITLE
Hyprland won’t start after install

### ISSUE THREAD

**Issue by DariusChit** [hyprwm/Hyprland#2707]
![image](https://github.com/hyprwm/Hyprland/assets/57860432/b3877268-4221-4d31-9963-82bd4336bb6a)

![image](https://github.com/hyprwm/Hyprland/assets/57860432/2d245d94-fc59-4bd4-b582-76fe91593d45)

![image](https://github.com/hyprwm/Hyprland/assets/57860432/ccfcc3f8-41f5-4025-87f8-37d198b91062)

Trying to start hyprland always gives me these errors. 
I have tried all the solutions posted on wiki and other sources but nothing seems to work. 
Thank you

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Nvidia/ ?

**Comment by DariusChit** [comment]
> Tried all the solution on the wiki

**Comment by MightyPlaza** [comment]
even the equivalent to the mkinitcpio part on gentoo?

**Comment by DariusChit** [comment]
Yeah used genkernel to do the initiramfs.

**Comment by MightyPlaza** [comment]
I asume you're also using all the env vars, if so try removing one of them at a time (maybe env = GBM_BACKEND,nvidia-drm)

**Comment by vaxerski** [comment]
this ain't the place for troubleshooting convos

**Comment by DariusChit** [comment]
Can you at least tell me where i can find help please?

**Comment by MightyPlaza** [comment]
Try asking in the nvidia channel on the discord server
