### ISSUE TITLE
volume indicator and night light (blue light filter)?

### ISSUE THREAD

**Issue by leozhang1** [hyprwm/Hyprland#2710]
Hi,

Maybe there are already features for this and if so, what are the config lines of code to configure them? I have looked everywhere online and no help yet. Thank you.

**Comment by MightyPlaza** [comment]
waybar & https://github.com/hyprwm/Hyprland/issues/1140

**Comment by leozhang1** [comment]
> waybar & #1140

I have waybar already. I want something like this: https://github.com/francma/wob. I've used this on sway before and it works like a charm. I'm hoping for something similar for hyprland. Also I am not familiar with shader programming and how to apply it to my linux environment. Do you have any helpful guides?

**Comment by MightyPlaza** [comment]
http://wiki.hyprland.org/Configuring/Variables/#decoration

If it works on sway probably also works on hyprland

**Comment by leozhang1** [comment]
> http://wiki.hyprland.org/Configuring/Variables/#decoration
> 
> If it works on sway probably also works on hyprland

okay adding:
```
decoration {

screen_shader = path/to/[filename].frag 
}
```

to the config did the trick with the blue light filter.

As for the WOB, I wish I knew what the config code was to get it to work 😭

**Comment by loqusion** [comment]
@leozhang1 If you want the blue light filter activated on a schedule, you can use a script I wrote: https://github.com/loqusion/hyprshade
