### ISSUE TITLE
running wf-recorder causes Hyprland to crash

### ISSUE THREAD

**Issue by justchokingaround** [hyprwm/Hyprland#2716]
Steps to reproduce: run `wf-recorder` and then open a new terminal window
Expected outcome: screenrecording works
Noted outcome: Hyprland crashes instantly
Hyprland config (since I source several other configs, I'll just post the github link): https://github.com/justchokingaround/dotfiles/blob/main/hyprland/hypr/hyprland.conf

crash report:
[hyprlandCrashReport25821.txt](https://github.com/hyprwm/Hyprland/files/12053106/hyprlandCrashReport25821.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12053061/hyprland.log)

**Comment by vaxerski** [comment]
#2241
