### ISSUE TITLE
Screen capturing and opening new windows crash

### ISSUE THREAD

**Issue by vars1ty** [hyprwm/Hyprland#2717]
- Steps to reproduce:
1. Open up OBS, probably twice for it to even realize that you have monitors and not a black screen
2. Start recording any screen
3. Swap workspace
4. Open up 2 new terminal windows
5. Hyprland broke its neck, it's game over.

- Expected outcome
Opening new windows should work, as it worked just fine on versions prior to the latest one.
I have also tried the git version, which result in the same behavior.

- Noted outcome
The window starts to open, then mid-way it freezes for 2 seconds and throws you back into tty.

Config is just the standard, default one. Just with keybindings changed and so on.
Crash Log from `.hyprland`:
[hyprlandCrashReport20555.txt](https://github.com/hyprwm/Hyprland/files/12053377/hyprlandCrashReport20555.txt)

**Comment by vars1ty** [comment]
Possibly related to #2716, but not sure.

**Comment by vaxerski** [comment]
#2241
