### ISSUE TITLE
latest hyprland release breaks fonts

### ISSUE THREAD

**Issue by SychoAN** [hyprwm/Hyprland#2719]
![image](https://github.com/hyprwm/Hyprland/assets/61439740/fafd32a4-1253-4db9-ac5f-2a2a3ff93037)

here's how the font looks like after updating hyprland
and I am sure this is from hyprland not anyother packages because I used timeshift backups to figure out where the problem comes from

text isn't smooth anymore...plz fix this

**Comment by MightyPlaza** [comment]
probably a xwayland scaling issue, disabling scaling or using the new xwayland options should fix it

**Comment by SychoAN** [comment]
> probably a xwayland scaling issue, disabling scaling or using the new xwayland options should fix it

yes I have this line on my hyprland.conf 
```
monitor=,highres,auto,0.85
```

but I don't know about xwayland...I just have xorg-xwayland installed
can you tell me about it ?

**Comment by SychoAN** [comment]
> probably a xwayland scaling issue, disabling scaling or using the new xwayland options should fix it

exec-once=xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 24c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 1 # sets xwayland scale

I tried this also
I thought it will make xwayland apps run in scale 1 
and monitor=,highres,auto,0.85 will still make screen bigger

but it didn't work also
please fix it hypr devs ):

**Comment by MightyPlaza** [comment]
try using force_zero_scaling=true and GDK_SCALE=0.85

**Comment by SychoAN** [comment]
> try using force_zero_scaling=true and GDK_SCALE=0.85

env = GDK_SCALE,0.85
env = force_zero_scaling,1

like this ?
it didn't work also

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Variables/#xwayland
force_zero_scaling is a variable not a env var

**Comment by SychoAN** [comment]
> force_zero_scaling
I added this
xwayland {
force_zero_scaling=true
}
and it worked 
but why? the older update I could run all xwayland apps with scale 0.85 

still a bug but this is a workaround....

**Comment by vaxerski** [comment]
looks like an xwayland issue idk why you call this a hl bug

**Comment by q234rty** [comment]
Pretty sure this is because https://github.com/hyprwm/Hyprland/commit/64ce06a3536898ddae7146e8f649361ce081c8d6 switched the default to using nearest neighbors for xwayland, which is worse than bilinear when downscaling...

**Comment by q234rty** [comment]
using `use_nearest_neighbor = true` install of `force_zero_scaling = true` would allow one to continue using 0.85 scale for Xwayland apps.
