### ISSUE TITLE
Extreme lag 

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#272]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.
Sometimes randomly, hyprland would just make my curser very laggy, well not only cursor, but everything, including animation, video playback speed and stuff.
I suspect is the log spam of xwayland causing problem
https://0x0.st/oS38.txt

**Comment by vaxerski** [comment]
some app that you are using is creating an absolute spam of unmanaged windows.

**Comment by KyleUltimate** [comment]
But I'm only using my terminal and waybar? Even after I killed waybar and my terminal the lag still will happen. Is there a way to get which program causes that?

**Comment by vaxerski** [comment]
the logs should now tell you with the latest commit

**Comment by vaxerski** [comment]
hm, that's weird.

I can see you're running fcitx though, which is not officially supported. Can you try posting a log *without* fcitx?

**Comment by KyleUltimate** [comment]
yep, the problem is indeed fcitx. The strange part is I'm not even typing anything

**Comment by KyleUltimate** [comment]
I'm using `fcitx5` ? I can try ibus for now

**Comment by vaxerski** [comment]
my bad, thought fcitx5's launch command was `fcitx5`. Anyway, try iBus, it has worked perfectly for me in most GTK and QT apps

**Comment by KyleUltimate** [comment]
yeah, iBus worked for me, no more strange log spams!

**Comment by KyleUltimate** [comment]
Fcitx5 has magically fix itself... I've no idea what's happening
