### ISSUE TITLE
Release is missing runtime dependencies

### ISSUE THREAD

**Issue by ventsyv** [hyprwm/Hyprland#2720]
I've been trying to run on Ubuntu 22.04 and I've ran into a number of issues due to poor documentation.
I've documented them here: https://github.com/hyprwm/hyprland-wiki/issues/268

I believe uncommon libraries, especially ones, that do not have native OS packages, should be bundled with the release.
You are already bundling libwlroots, which by the way does have Ubuntu package, but not libdisplay-info, libliftoff, and libliftoff, which do not and are required by libwlroots.

I suggest either to remove the libwlroots from the release and add instruction to the wiki on how to install it (preferred) or bundle any 3rd level dependencies that are not commonly found in native OS package repositories.

**Comment by vaxerski** [comment]
> I believe uncommon libraries, especially ones, that do not have native OS packages

https://repology.org/project/libliftoff/versions

https://repology.org/project/libdisplay-info/versions

> I've been trying to run on Ubuntu 22.04

![image](https://github.com/hyprwm/Hyprland/assets/43317083/9ba019e2-a829-4657-87d1-63eb4421a2c0)

> I suggest either to remove the libwlroots from the release and add instruction to the wiki on how to install it (preferred)

#302

Your entire post is just a massive "I did not check anything, did not read anything, I am a ubuntu user, everything should just work" moment
