### ISSUE TITLE
hyprctl lacks the ability to query for empty workspaces

### ISSUE THREAD

**Issue by jonhoo** [hyprwm/Hyprland#2723]
We currently have `hyprctl workspaces` for listing all non-empty workspaces, but it'd be nice to also have the ability to list all the workspaces (i.e., including empty ones) for use with things like status bars. Essentially, the query equivalent to the `r` variable for workspace identifiers.

**Comment by donovanglover** [comment]
Non-focused empty workspaces don't exist so they can't be queried. See: https://github.com/hyprwm/Hyprland/issues/481#issuecomment-1207163475

Status bars like waybar have options to specify [persistent workspaces](https://github.com/Alexays/Waybar/wiki/Module:-Workspaces#persistent-workspaces). You can also infer "empty" non-existing workspaces based on current workspace IDs.

**Comment by vaxerski** [comment]
as above

**Comment by jonhoo** [comment]
Thanks for the clarification!
