### ISSUE TITLE
Double fractional scaling for dpi-aware apps

### ISSUE THREAD

**Issue by erikwb** [hyprwm/Hyprland#2726]
The foot terminal emulator recently implemented fractional scaling.  With two monitors of different physical dimensions and hyprland set to scale them each at 1.0, foot now changes its font size to look identical on each screen - but other apps are too small as they can't do this trick.

If hyprland is set to scale the physically smaller monitor higher than 1.0, it appears that both foot and hyprland apply scaling and it ends up too big.

I am not sure if it's possible for hyprland or foot, or any other wayland app, to be aware of eachothers' dpi awareness capabilities, but it would be cool to be able to run in a mixed mode where the compositor is scaling apps that are not dpi-aware while apps that can do it on their own are allowed to do so.

**Comment by vaxerski** [comment]
sounds like a foot bug? It should take the scale into account

**Comment by vaxerski** [comment]
if you want to know that, this is the thing to read: https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/protocol/wayland.xml
