### ISSUE TITLE
Cannot unlock with Swaylock on NixOS

### ISSUE THREAD

**Issue by cloudlena** [hyprwm/Hyprland#2727]
Running Hyprland on NixOS, I have a setup for Swaylock to lock the screen after a while. When it gets locked however, I cannot log in anymore. It just keeps telling me that the password is wrong. The exact same setup works using Sway.

Am I doing something wrong or is that a bug in how the NixOS setup is connected to PAM? Might be connected to https://github.com/swaywm/swaylock/issues/290.

Tagging @fufexan because it may be connected to Nix.

**Comment by donovanglover** [comment]
You need to add `security.pam.services.swaylock = { };` to your system config.

See: https://github.com/NixOS/nixpkgs/issues/143365

**Comment by cloudlena** [comment]
Indeed, that fixed it. Many thanks, @donovanglover!
