### ISSUE TITLE
Fullscreen broken in dwindle layout, unless the window is floating

### ISSUE THREAD

**Issue by gaelj** [hyprwm/Hyprland#2736]
I use hyprland-git from the Arch User Repos. I noticed yesterday that fullscreen isn't working any more in dwindle layout. It now acts as a "focus" mode where all other windows get hidden, but the active window is not resized.

If I switch to master layout, or if in dwindle I make the window floating, then I can maximize it successfully.

I haven't changed my dotfiles or installed anything Wayland-related in weeks, so I'm pretty sure it's not on my side. I just updated to today's release in the AUR but the problem is still there.

My config for fullscreen is: `bind = $mod, F, fullscreen, 0` (I just added the ending 0, to no avail)

When pressing F11 in an app that supports it, such as a browser, the same problem can be observed.

**Comment by vaxerski** [comment]
it's fixed in git
