### ISSUE TITLE
Power draw due to inefficiency 

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#2741]
### Hyprland Version

7c1dacea09e18ddf74fcb9e0be2debce9c0cf94d dirty (only return 0 when using -h (2738)). Tag: v0.27.0-26-g7c1dacea

### Bug or Regression?

Bug

### Description

Sorry to bring up this topic 
but if I watch a random video (YT or some other streaming page, tested in Firefox) 
when I compare the `intel-gpu-top` and `nvtop` outputs I get the following characteristics

1. Picture Gnome on the left, Hyprland (0.27 tag or latest commit doesn't change anything) on the right
2. Picture Sway-git

![image](https://github.com/hyprwm/Hyprland/assets/5576250/8e6f2270-0732-4cf0-a2c8-069ee749ca11)
![image](https://github.com/hyprwm/Hyprland/assets/5576250/333c2c90-da33-4895-aa2e-714943e357f8)

Gnome 1.7/23.0 W
Hyprland 11.8/30.6 W
Sway 2.5/21.7 W

Furthermore, it can be seen that Hyprland transfers much more data to the memory (via IMC) 
Gnome | read 3.3GB | write 1.6GB
Hyprland | read 9.6GB |write 7GB
Sway | read 5GB | write 4GB

### How to reproduce

Just watch a video and choose a defined  resolution (1080) and make sure that your GPU supports hardware acceleration for the file codec (should be visible in intel_gpu_top under video or in nvtop under  ENC/DEC[   0%]).

The same video draws much more power under Hyprland and transfers much more data (and has higher GPU%) as in the other "Display Managers".

**Comment by zjeffer** [comment]
@romanstingler Did you mean to close the issue?

**Comment by romanstingler** [comment]
@zjeffer I closed it becasue I had to dig in deeper.
reopened because in Gnome GPU load is ~50% of the GPU load in Hyprland when watching a video

**Comment by vaxerski** [comment]
does this also happen on older versions, like 0.18?

**Comment by romanstingler** [comment]
> 

I will check that in the evening and let you know

**Comment by vaxerski** [comment]
do you have any effects enabled? blur, shadows?

**Comment by romanstingler** [comment]
sorry, I wanted to add the details, but got distracted. 

NO animations, no blur, no transparency, no shadows. 
https://github.com/romanstingler/dotfiles/blob/main/.config/hypr/hyprland.conf

**Comment by vaxerski** [comment]
Can you check if the VRAM usage went down by at least a bit after today's changes on -git?

**Comment by vaxerski** [comment]
check with 547305c7ed02c37b68773b2ccb6fb7f702898f0a whether you see any improvements

**Comment by romanstingler** [comment]
@vaxerski I build the latest 
and compared 
gf4f0f35c with g948855a9

There was a significant drop in memory write and also lower GPU usage.
Very good work from your side. 
I will try to add a graph with sway

![image](https://github.com/hyprwm/Hyprland/assets/5576250/b6f9be1a-ad7a-4868-a304-6e5fec9e7882)
[gf4f0f35c.ods](https://github.com/hyprwm/Hyprland/files/12111303/gf4f0f35c.ods)
[g948855a9.ods](https://github.com/hyprwm/Hyprland/files/12111304/g948855a9.ods)

**Comment by vaxerski** [comment]
:+1: I added tracy as a subproject and will continue profiling the code to find possible optimization spots.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/767da8bd-8ce9-4226-89f4-ad91a3d9ae25)

curiously RenderClearWithTex for some reason uses considerably more GPU than RenderLayer...? Despite blend being disabled...???

**Comment by vaxerski** [comment]
I can also recommend to turn on `misc:disable_hyprland_logo` if you need that ultimate performance.

**Comment by romanstingler** [comment]
> 

but I love the logo :) and the anime

**Comment by vaxerski** [comment]
haha on that note I need to add a config opt to force hypr-chan

**Comment by romanstingler** [comment]
but you are right, there is a measurable difference without the logo

**Comment by vaxerski** [comment]
I have no life. I'll take a look into the texture renderer and what can be done about it.

**Comment by romanstingler** [comment]
>>I have no life. 
I know your feeling, but I highly appreciate your effort

latest commit 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/3e34a9e5-fc08-4cab-8f60-27d7d6258600)
