### ISSUE TITLE
Image doesn't fill the screen if the resolution is below the native resolution

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#2743]
### Hyprland Version

81f4a4f47182c15ee9436d9ab7b2e425a096ce5b

### Bug or Regression?

Bug

### Description

I have 2x 4k screen
my monitor config was 
```
monitor=eDP-1, 2560x1440, 0x0, 1
monitor=,highres,auto,auto
```
Because of the small internal notebook display, I ran it at the defined resolution, which worked fine.

At some point after ddb8c897762d47a22867c77897c6e39513e36029 I got this behavior 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/755d3703-496b-4178-98a0-9529e4e9fbce)

And if I change something in the `hyprland.config` regarding the monitor configuration, it reloads the screen, and it looks like this
![image](https://github.com/hyprwm/Hyprland/assets/5576250/d3930424-aba9-4157-a710-32a568da836e)

for now it works with 
```
monitor=eDP-1, 3840x2160, 0x0, 1.5
monitor=,highres,auto,auto
```

But still there must be something changing the behavior. 

### How to reproduce

relevant infos should be in the description section

**Comment by vaxerski** [comment]
do a `git bisect` then please

**Comment by romanstingler** [comment]
> do a `git bisect` then please

it would be really nice if someone could add a `git bisect` section into git for this project
because apparently it is not trivial 
(I have `libxcursor` installed) but why is the header missing in wlroots ?
![image](https://github.com/hyprwm/Hyprland/assets/5576250/0a155bc0-61a4-4549-b793-f37fc948ba95)

sorry never did anything like that before

**Comment by vaxerski** [comment]
then it's a wlroots issue

**Comment by Cloudef** [comment]
You need to update wlroots

**Comment by jbeich** [comment]
Can you show `hyprctl monitors` before and after? Does it work fine if you set position from `auto` to `2560x0` or scale from `auto` to `1` (default is `2` for 4K)? I couldn't reproduce via nested Hyprland with [emulated](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/7791ffe0584c/docs/env_vars.md#wayland-backend) displays.

Maybe try to bisect 8c9e2e1ff1d2 itself which contains 112 wlroots commits e.g.,
```
$ cd subprojects/wlroots
$ git bisect start 7791ffe0 7e7633ab
```
For API breakage within simply apply/revert parts of 8c9e2e1ff1d2:
- [wlroots@18bafbfc5703](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/18bafbfc5703): `wlr_xcursor_manager_set_cursor_image` -> `wlr_cursor_set_xcursor`
- [wlroots@67447d6cb407](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/67447d6cb407): `wlr_presentation_surface_sampled_on_output` -> `wlr_presentation_surface_scanned_out_on_output`

**Comment by romanstingler** [comment]
1 moment, I will build and add the old output 

BUT 
`auto` sets it correctly to 2560x0 
`scale 1` should be fine, which means I want that resolution with no scaling, this means draw this amount of pixels and "stretch" it to fit the screen size. 
 

1ec0b7b59a84a07f97c3ebee9f6694bc4a1b1dcd
```
❯ hyprctl monitors
Monitor eDP-1 (ID 0):
	2560x1440@60.000000 at 0x0
	description: California Institute of Technology 0x1500 (eDP-1)
	make: California Institute of Technology
	model: 0x1500
	serial:
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 33 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-3 (ID 1):
	3840x2160@59.939999 at 2560x0
	description: Samsung Electric Company U32R59x H4ZM600322 (DP-3 via HDMI)
	make: Samsung Electric Company
	model: U32R59x
	serial: H4ZM600322
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 33 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

```

**Comment by romanstingler** [comment]
@vaxerski we got a reply on wlroots side 
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3695#note_2012479
could there be some issue how the resolution is set in hl?

**Comment by vaxerski** [comment]
All comments relate to wlr faults, I don't see how this is a hl issue.

**Comment by romanstingler** [comment]
On the latest hyprland commit if I use this `#monitor=eDP-1, 2560x1440, 0x0, 1.0` on my 4k monitor 
it crashes 
with compositor doesn't support wl_compositor

[hyprlandCrashReport12220.txt](https://github.com/hyprwm/Hyprland/files/12545478/hyprlandCrashReport12220.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12545509/hyprland.log)
![2023-09-07-08-31-07-528](https://github.com/hyprwm/Hyprland/assets/5576250/f4423429-a0e3-43f5-b4d0-8fb792fa1034)

The reason was that my issue on wlr was closed 
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3695
I tried the latest hyprland official and also updating the wlr version, no change whatsoever.

**Comment by romanstingler** [comment]
I haven't tested it for a longer time. 
But currently when I change the resolution on my 4k to 
`monitor=eDP-1, 2560x1440, 0x0, 1`

I can use the full screen, but I can't see the Waybar. 
<img src="https://github.com/hyprwm/Hyprland/assets/5576250/5107cf1e-9a8e-49f9-a220-3a0acc99d59c" width="500" height="375">

<img src="https://github.com/hyprwm/Hyprland/assets/5576250/59047e4b-2576-45f8-b677-e6e8bb909fa5" width="500" height="375">

When I switch back to 4k the bar is restored.

I wanted to make a screenshot, but grimblast says `no wl_output` 

<img src="https://github.com/hyprwm/Hyprland/assets/5576250/f243d08a-b59b-4c16-b6eb-ec18b6721bf9" width="500" height="375">

Could that be a Hyprland issue or should I bug the wlroots team?

**Comment by webknjaz** [comment]
@romanstingler this does look like something I reported in May — https://github.com/hyprwm/Hyprland/issues/2364. Although, in my case I wasn't able to debug it further... Do you think it's the same? There's a YouTube video with the demonstration linked there. Any chance you could test those observations?

**Comment by scornet256** [comment]
In my case this has been resolved. I don't know since when. I think since wlroots version [0.17.0](https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.17.0) maybe.

I still have that waybar is gone and that hyprpaper doesn't work with a non-native resolution, but that is not for here.
