### ISSUE TITLE
Hyprland: undefined symbol: wlr_backend_is_drm

### ISSUE THREAD

**Issue by soanvig** [hyprwm/Hyprland#2748]
### Hyprland Version

0.27.1

### Bug or Regression?

Bug

### Description

Hey! I'm working on making Hyprland launch on Nvidia (proprietary) on Void Linux.

**We have Hyprland working on other cards** (see: https://github.com/Makrennel/hyprland-void) in Void Linux,
however for Nvidia it fails on start with:

```
Hyprland: undefined symbol: wlr_backend_is_drm
```

I've followed: https://wiki.hyprland.org/Nvidia/ thoroughly. Triple checked if all kernel modules are properly enabled and configured.

As I said, it works on other cards properly.

I know, Nvidia is not support officialy. But I cannot track where this bug comes from. Most of the people (on other distros presumably) don't have that problem.

So maybe somebody knows a solution, or at least a suggestion where to start looking.

### How to reproduce

Nvidia card, properietary driver, Void Linux, follow https://github.com/Makrennel/hyprland-void but use `hyprland-nvidia` instead of `hyprland`

**Comment by Makrennel** [comment]
As far as I can tell wlroots (and pretty much everything else) is compiled in the [same way](https://github.com/Makrennel/hyprland-void/blob/d2f518a6c3d4680895f314b9b6f7044e34fbe8af/srcpkgs/hyprland-nvidia/template#L66) as it is done in the [AUR build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyprland-nvidia#n65)

**Comment by vaxerski** [comment]
as far as I can tell hyprland complains about a symbol missing that should be in libwlroots.so.

**Comment by jbeich** [comment]
> compiled in the same way as it is done in the AUR build script

Can you show the build log? `wlr_backend_is_drm` is built only if DRM backend in wlroots is enabled. By default DRM backend is only enabled if all dependencies are present and up-to-date.

Maybe try to build wlroots standalone while aborting if autodetection failed e.g.,
```
$ meson setup --auto-features=enabled -Dexamples=false /tmp/wlroots_build subprojects/wlroots
$ meson compile -C /tmp/wlroots_build
```

**Comment by jbeich** [comment]
Also, the build log is non-verbose, so no way to ensure compiler flags used don't accidentally pick up headers from older system wlroots.

**Comment by Makrennel** [comment]
> BTW, what if our patching doesn't work like it should? Theoretically this patch is applied telling from the logs, but yeah. Even if patch wasn't applied it doesn't look like it would cause such error.

You can check if the patch applies correctly by running `./xbps-src patch hyprland-nvidia` and it'll only run the script until it completes the patching and you can go into the `masterdir` to check the code has been modified correctly.

**Comment by soanvig** [comment]
@Makrennel Thanks for confirmation, you are really dedicated. Well, if it is really something wrong on my side, my weird setup or whatsoever, I think we can close it. I will reopen it when I find the issue.

@vaxerski @Makrennel @jbeich Thanks for the assistance. I won't take up your time anymore.
