### ISSUE TITLE
Hyprland default wallpaper when switching workspaces

### ISSUE THREAD

**Issue by Schwarzeisc00l** [hyprwm/Hyprland#2751]
### Hyprland Version

hyprland-git

### Bug or Regression?

Bug

### Description

I freshly compiled Hyprland. (I am using LLVM and LTO if that makes a difference)

When I open new windows or switch between workspaces. The default Hyprland wallpaper temporarily appears.

### How to reproduce

I tried recompiling in vanilla linux.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/78359804/6930cc0a-b343-49ec-b72f-bf5c966d2f38

**Comment by vaxerski** [comment]
heh occlusion funky

**Comment by vaxerski** [comment]
fixed 2c2314faa0e3f6fe07ec112a9e31534d32a59569

**Comment by Schwarzeisc00l** [comment]
Thanks!
