### ISSUE TITLE
Resizing a window being captured by a portal hard locks system

### ISSUE THREAD

**Issue by BrodieRobertson** [hyprwm/Hyprland#2753]
### Hyprland Version

v0.27.2-7-g7091d4e5

### Bug or Regression?

Bug

### Description

In OBS I have a pipewire window capture, if I resize the window that the capture is grabbing, the portal stops updating what is being shown then my portal and pipewire start maxing out 1 core each, Hyprland spikes in CPU usage as well, then Hyprland starts to stutter, the longer I leave it running in this state the worse the stuttering gets. If left in this state for a few minutes the system completely locks up, unable to even switch TTY.

### How to reproduce

1. Select a window with pipewire window capture (only tested in OBS)
2. Resize window until the capture freezes
3. Leave it running until mouse starts to stutter
4. Eventually system should hard lock

### Crash reports, logs, images, videos

The system doesn't seem to progress far enough for Hyprland to crash.

Log as best as I could before system locks: 
[log.txt](https://github.com/hyprwm/Hyprland/files/12103718/log.txt)

Video demonstration:
[youtube video](https://youtu.be/TQPCVOMCVOg)

**Comment by vaxerski** [comment]
update xdph and hyprland to -git and check please, commits https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/43300c11a9c58020c3dd4f7587e30bcb2b1b0bec and b65adf8d4a0c239f5aa44425d14d1fe14f675643

**Comment by BrodieRobertson** [comment]
The issue occurs under the same conditions

**Comment by BrodieRobertson** [comment]
Upon updating OBS, for minor resizes eventually everything will catch back up, but I noticed my cursor continued to lag. However forcing a ton of resizes whilst it does survive a much longer time (10+ minutes) it does still eventually freeze the system
