### ISSUE TITLE
Please consent before adding anime to background wallpaper

### ISSUE THREAD

**Issue by bakrtech** [hyprwm/Hyprland#2754]
Hey there developer  
Hope you are doing great 
The wallpaper suddenly has a anime girl  
this was done without consent 
please don't do it from next time 
bye

**Comment by vaxerski** [comment]
no :)

**Comment by bakrtech** [comment]
bruh 
please man

**Comment by thcrt** [comment]
How can I disable the anime mascot? There's a config option to force it *on* but none to force it *off*.

**Comment by JustSimplyKyle** [comment]
You can just... `disable_hyprland_logo = true`?

**Comment by JustSimplyKyle** [comment]
`/usr/share/hyprland/wall_8K.png`
Or just load it with your wallpaper engine for choice(hyprpaper being an very light one)

**Comment by patricksjackson** [comment]
You also need to disable the splash screen with `disable_splash_rendering = true`

**Comment by brckd** [comment]
i would rather disable the default wallpaper :D
