### ISSUE TITLE
Different wallpaper when holding workspace swipe gesture between fullscreen window

### ISSUE THREAD

**Issue by codelif** [hyprwm/Hyprland#2756]
### Hyprland Version

v0.27.1

### Bug or Regression?

Bug

### Description

When swiping from a fullscreen application to new workspace (or any workspace), my wallpaper set by third-party utilities (`wbg`) is not shown, instead the default wallpaper is shown. 
Wallpaper reverts to normal when I unhold the gesuture (i.e. lift my fingers from touchpad)

This also happens when I use `hyprpaper`.

OS: `Arch Linux`
Kernel: `6.1.39-1-lts`
Downloaded with: `pacman`

I have uploaded a demonstration of the issue:

https://github.com/hyprwm/Hyprland/assets/68972644/b8cb570f-f457-487a-8cf2-90714a7e55b5

### How to reproduce

Step 1: Set a wallpaper using 3P utility `wbg` or `hyprpaper`

Step 2: In `~/.config/hypr/hyprland`, set
```
gestures {
    workspace_swipe = on
}
```
Step 3: Fullscreen any window
Step 4: Try swiping with 3 fingers to new workspace with the touchpad

**Comment by burein-ita** [comment]
waifu transmutation

**Comment by donovanglover** [comment]
Haven't checked the `-git` but my workaround for this was setting `fullscreen_opacity` to `0.9999999`

**Comment by vaxerski** [comment]
this is fixed in -git iirc.

**Comment by taigrr** [comment]
Sorry to necrobump but I think I am having the same issue for a different interaction: Fullscreening.
Running v0.28.0 (also arch)


https://github.com/hyprwm/Hyprland/assets/8261498/057aa6ac-77c9-4936-a2b6-f2b38b4de9a6

**Comment by vaxerski** [comment]
firefox bug, see #2817
