### ISSUE TITLE
Closing animation speed increases over time

### ISSUE THREAD

**Issue by donovanglover** [hyprwm/Hyprland#2758]
### Hyprland Version

Hyprland, built from branch  at commit v0.27.0  ().

### Bug or Regression?

Bug

### Description

Over time the speed of closing animations in Hyprland gradually increases until closing windows is almost instantaneous. `hyprctl keyword animation "windowsOut,1,7,default,popin 80%"` doesn't change anything. All other animations seem to not be affected. Fixed by running `hyprctl reload`.

### How to reproduce

Not sure what causes it but using Hyprland long enough tends to reproduce the issue. Also occurs in 0.26.0. Don't remember if it occurred in 0.24.1.

### Crash reports, logs, images, videos

[hyprland.conf](https://github.com/donovanglover/nix-config/blob/4f64d67cff3355b50cd08330e5f15ac62ddabb6d/home/hyprland.nix)

**Comment by GrabbenD** [comment]
Could this be due to `HPET`? It's known to cause strange behavior in timings, check your timer here:
```
/sys/devices/system/clocksource/clocksource0/current_clocksource
```
TSC is the best, here's the full list for your system:
```
cat/sys/devices/system/clocksource/clocksource0/available_clocksource
```

**Comment by donovanglover** [comment]
@GrabbenD I think you're right, however the only options I have are `hpet` and `acpi_pm`. Not sure why Hyprland (and the closing animation specifically) is the only thing that seems to be affected by this.

**Comment by GrabbenD** [comment]
From my limited understanding you could probably get better results with `acpi_pm` if that's what your hardware is limited to. Yet better make sure your bios is actually up to date to avoid dealing with platform specific firmware bugs. Alternatively check if something is blacklisting`tsc` with: `dmesg | grep -i tsc`. Another cause could be custom kernel config if that's something that you're using.

HPET related bugs can be mitigated in code but I'm doubtful it will get adressed any time soon if a small portion of users is affected by this 🙁

**Comment by tfkhdyt** [comment]
This issue happened to me as well

**Comment by vaxerski** [comment]
not a hl issue
