### ISSUE TITLE
Hyprland not launching after kernel and package update

### ISSUE THREAD

**Issue by ouzdll** [hyprwm/Hyprland#2761]
### Hyprland Version

both latest commit and 0.27.1

### Bug or Regression?

Regression

### Description

After updating the kernel (`linux` and `linux-zen`) and the `hyprland-git` package from AUR, Hyprland fails to launch. I noticed a similar behavior when attempting to use NVIDIA drivers and the GPU as the primary graphics card. However, reverting to integrated GPU with the non-patched version allowed Hyprland to run and haven't had any problems since then. Other applications are working correctly on my system after the updates.

**Steps Taken to Solve the Problem:**
1. Installed the LTS kernel to check if the issue was kernel-related.
2. Tried using both NVIDIA proprietary drivers and `nouveau`, but the problem persisted in both cases.
3. Removed the `hyprland-git` package from AUR and installed `hyprland` from official repositories.
4. Attempted to build Hyprland from source, but the issue remained.

There must be something I'm missing for sure. I couldn't get to write the output of Hyprland command from TTY to a file, sometimes it stops at a `seatd` error or sometimes at `Found 1 GPUs`. Please let me know if there's anything helpful I can provide.

### How to reproduce

1. Update the kernel to the latest version (`linux 6.4.4` and `linux-zen 6.4.4` or `linux-lts 6.1.139`).
2. Update the `hyprland-git` package from AUR (or install `hyprland` package from official repo).
3. Attempt to launch Hyprland (simply reboot).

### Crash reports, logs, images, videos

[hyprland-log.txt](https://github.com/hyprwm/Hyprland/files/12114306/hyprland-log.txt)
[lspci.txt](https://github.com/hyprwm/Hyprland/files/12114346/lspci.txt)

**Comment by Fxzzi** [comment]
0.27.2 is already out. Please also try latest git Nvidia package `hyprland-nvidia-git`

**Comment by ouzdll** [comment]
> 0.27.2 is already out. Please also try latest git Nvidia package `hyprland-nvidia-git`

Tried both with some possible kernel and driver combinations but still no luck :(

[hyprland-newlog.txt](https://github.com/hyprwm/Hyprland/files/12114697/hyprland-newlog.txt)
[hyprland-lastlog.txt](https://github.com/hyprwm/Hyprland/files/12114698/hyprland-lastlog.txt)

**Comment by ouzdll** [comment]
Reverting Hyprland back to `0.26` didn't help either. But now it segfaults instead and gives me a crash report. I don't know if it's related to NVIDIA but uploading logs of both drivers.

Logs with proprietary driver:
[hyprland-26log.txt](https://github.com/hyprwm/Hyprland/files/12114967/hyprland-26log.txt)
[hyprlandCrashReport1059.txt](https://github.com/hyprwm/Hyprland/files/12114969/hyprlandCrashReport1059.txt)

Logs with nouveau driver:
[hyprland-26-nouveau-log.txt](https://github.com/hyprwm/Hyprland/files/12114975/hyprland-26-nouveau-log.txt)
[hyprlandCrashReport991.txt](https://github.com/hyprwm/Hyprland/files/12114976/hyprlandCrashReport991.txt)

**Comment by ouzdll** [comment]
Installed `hyprland-git` again and now it's working. Idk wtf was the problem, didn't change anything lol. Maybe d7e9eb6 or 263b9c6 resolved this? Closing as it's not present anymore.
