### ISSUE TITLE
0.27.2 core dump/brief graphical glitch on start

### ISSUE THREAD

**Issue by jmcelroy01** [hyprwm/Hyprland#2762]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2

### Bug or Regression?

Bug

### Description

On launch, there is a brief screen glitch, sorta like black/white squares in a grid, then Hyprland starts normally. The logs indicate a core dump and several warnings. 

### How to reproduce

Build 0.27.2 on AMD hardware on gcc Gentoo and launch. 

### Crash reports, logs, images, videos

coredumpctl info

[0.27.2-coredump.txt](https://github.com/hyprwm/Hyprland/files/12114755/0.27.2-coredump.txt)

hyprland.log (warnings at the end)

[0.27.2-coredump-hyprland.log](https://github.com/hyprwm/Hyprland/files/12114757/0.27.2-coredump-hyprland.log)

It might have some overlap with #2709 but the logs are not identical.

**Comment by MightyPlaza** [comment]
Wlroots issue
happens on sway-git with wlroots-git

**Comment by jmcelroy01** [comment]
Yeah sounds right. Shall I close this issue?

**Comment by MightyPlaza** [comment]
idk, the only thing that can be done here is update wlroots when a fix comes out

**Comment by MightyPlaza** [comment]
found the wlroots commit that's causing it (https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/c4d4409deb50b23eec120da776de46ef8440879f)

**Comment by romanstingler** [comment]
> found the wlroots commit that's causing it (https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/c4d4409deb50b23eec120da776de46ef8440879f)

please create an issue in wlroots gitlab. 
I haven't found any issue which is mentioning your commit

**Comment by MightyPlaza** [comment]
link's above

**Comment by clevoman** [comment]
Issue still present in 0.29.1

**Comment by clevoman** [comment]
At this point I'll just switch to a DE; good luck with this project, Hyprland was really nice for a while

**Comment by MightyPlaza** [comment]
haven't tested yet but my issue should be fixed now

**Comment by vaxerski** [comment]
right, cuz of 47f38dbc8f160156689dff793555251066c2124a

forgot to close
