### ISSUE TITLE
Hyprland not starting after 0.27.1-1 update

### ISSUE THREAD

**Issue by Jayy-Dev** [hyprwm/Hyprland#2764]
### Hyprland Version

0.27.1-1

### Bug or Regression?

Bug

### Description

This happened yesterday after I update hyprland from extra repo in arch, and restarted my laptop after that I log in using sddm hyprland won't start my screen is just showing a terminal (virtual terminal) and a cursor in the top left and it just went back to sddm, I tried installing the hyprland-git from aur and still the same response when I launch hyprland. also tried installing the 0.27.1-2 source and still the same response (idk if i installed it right this is literally my first compile and install) also several logs is showing in <code>.hyprland</code> 

[hyprlandCrashReport8324.txt](https://github.com/hyprwm/Hyprland/files/12115963/hyprlandCrashReport8324.txt)

LOGS:

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12115982/hyprland.log)

### How to reproduce

Install:
1. Arch linux running on 6.4.4-arch1-1
2. Install hyprland on extra repo in arch or the hyprland-git in aur.
3. Start to launch it

**Comment by pranavrao145** [comment]
Judging from the crash report, this might be related to #2709, which is likely an issue due to the wlroots update that happened recently.

**Comment by Jayy-Dev** [comment]
> Judging from the crash report, this might be related to #2709, which is likely an issue due to the wlroots update that happened recently.

> Any solutions for it?

**Comment by pranavrao145** [comment]
No permanent solution yet, just waiting on a response - but what worked for me as a temporary fix is downgrading to 5c8a20b, which is the commit directly before the wlroots update. To do that though, it might be easiest to clone and build manually (using `sudo make install`).

**Comment by MightyPlaza** [comment]
pretty sure not using sddm "fixes" this

**Comment by pranavrao145** [comment]
Yep, I can confirm that the latest commit does in fact still work from the TTY. I was initially using SDDM because the wiki recommends it on [this page](https://wiki.hyprland.org/Getting-Started/Master-Tutorial/), but I guess it's not officially supported and incompatibilities are to be expected. I guess the best solution would be to use TTY until some type of fix comes from the SDDM side.

**Comment by Jayy-Dev** [comment]
> No permanent solution yet, just waiting on a response - but what worked for me as a temporary fix is downgrading to 5c8a20b, which is the commit directly before the wlroots update. To do that though, it might be easiest to clone and build manually (using `sudo make install`).

Thanks

**Comment by Jayy-Dev** [comment]
For some reason my old <code>hyprland.conf</code> doesn't work and the bug is getting triggered when I use it and when I use the generated config hyprland works but the default keybinds for kitty doesn't work and meta+m does work (This bug was showing on my fresh install of arch on my different device)

**Comment by romanstingler** [comment]
@Jayy-Dev this could be related to my issue 
https://github.com/hyprwm/Hyprland/issues/2743

You could try my build (please backup your version or make sure you have an option to install from AUR or build your version in case something shouldn't work)

This is my build with the reverted wlroots commits and Hyprland build from yesterday 
27dd07f1b8f89dcf6fe29fec75fdd5c8e9bc9ec4
[hyprland.zip](https://github.com/hyprwm/Hyprland/files/12136676/hyprland.zip)

**Comment by Jayy-Dev** [comment]
Hyprland, built from branch main at commit b21644b61143de0835fef9c3fa69fbdd2553cdfa  (input: Fix #2376 mouse movement bug in XWayland (#2776)).
Tag: ?
ninja build
--
Here's the before and after issue from me

Hyprland Version: 0.27.0-1 (I think)
[before](https://github.com/Jayy-Dev/hypr-dots/blob/main/clearview.png?raw=true)

after: 
![screenshot-2023-07-23-11:21:34](https://github.com/hyprwm/Hyprland/assets/105900291/c1f0bae0-5053-4063-8156-9c40dc8ac4c5)
So my original resolution for my screen is `1368x768` when I use `1920x1080` before it just fits on my screen  but now it doesn't allow me anymore it just shows that.

**Comment by romanstingler** [comment]
have you tried my build in the zip from above?

**Comment by Jayy-Dev** [comment]
> have you tried my build in the zip from above?

do I just change the binary or what? (I literally don't know I'm just a user and I'm not into coding yet so I don't know on how to do it)

**Comment by romanstingler** [comment]
just extract the files somewhere and there are folders
`usr/bin` 
and `usr/lib`
just copy the files in these folders to the same location 
best is to exit the GUI (Hyprland) and copy within the tty (because if you copy libwlroots it will crash.
 
and copy with (the first path where ever you have extracted the zip .
```
sudo cp -a usr/lib/* /usr/lib/
sudo cp -a usr/bin/* /usr/bin/
```

**Comment by Jayy-Dev** [comment]
> just extract the files somewhere and there are folders
> 
> `usr/bin` 
> 
> and `usr/lib`
> 
> just copy the files in these folders to the same location 
> 
> best is to exit the GUI (Hyprland (WINDOWS+M) ) and copy within the tty (because if you copy libwlroots it will crash.
> 
>  
> 
> and copy with (the first path where ever you have extracted the zip .
> 
> ```
> 
> sudo cp -a usr/lib/* /usr/lib/
> 
> sudo cp -a usr/bin/* /usr/bin/
> 
> ```

Tested versions that do not work with:
0.27.1
0.27.2

Works on 0.27.0 with commit 5e577acf516b80173f695a458c2cc188a4d64560 dirty ().

Thanks for the build @romanstingler 

Going to stay on 0.27.0 with reverted wlroots for a while.
