### ISSUE TITLE
Misuse of IPC socket causes Hyprland to lock up

### ISSUE THREAD

**Issue by heartles** [hyprwm/Hyprland#2765]
### Hyprland Version

Hyprland, built from branch  at commit 1ec0b7b59a84a07f97c3ebee9f6694bc4a1b1dcd  (). Tag: ?  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Attempting to read from .socket.sock via `socat` (say, for example, you got the direction wrong and typed `-U` instead of `-u`) causes Hyprland to lock up until the socket is closed.

While I get that at some level this is a "play dumpass games, win dumpass prizes" type of thing, Hyprland probably shouldn't lock up to the point I need to ssh in from my phone and kill some processes to get it to respond again.

I'm running Hyprland from the home-manager flake in the wiki, updated to what I think is the latest commit in `main`.

### How to reproduce

1. Open Hyprland
2. `socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket.sock`
3. Observe that Hyprland is nonresponsive, the cursor cannot be moved and keypresses are not handled.
4. SSH in from another computer and `killall socat`
5. Observe that Hyprland begins responding again.

**Comment by vaxerski** [comment]
fixed in 263b9c6e39c98a2790167db5251379e0acfd3e89
