### ISSUE TITLE
Visual bug when animations are turned off

### ISSUE THREAD

**Issue by Ru-Tao** [hyprwm/Hyprland#2767]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2

### Bug or Regression?

Bug

### Description

When spawning windows with animations off,  the windows appear stretched for a second or so on launch.
The bug is less visible with the default dwindle layout, but is easier to spot when using the master layout. 

Really love the functionality of Hyprland, but the animations can be a bit much for me sometimes is all. 

[bug.webm](https://github.com/hyprwm/Hyprland/assets/123201074/0c9e1122-8079-443b-b35c-a8d08824be27)

### How to reproduce

Set in animations enabled = false in hyprland.conf, optionally use the master layout.

**Comment by romanstingler** [comment]
what terminal are you using

**Comment by Ru-Tao** [comment]
> what terminal are you using

I'm using foot but the bug appears for more then just the terminal, I've tested with things such as thunar already

**Comment by vaxerski** [comment]
isnt this just another terminal being thrown there and it needs like a moment to re-render itself?

**Comment by romanstingler** [comment]
I was just curious if these might be related 
https://github.com/hyprwm/Hyprland/issues/1468

**Comment by Ru-Tao** [comment]
> isnt this just another terminal being thrown there and it needs like a moment to re-render itself?

Could be the case but I haven't faced this with any other wayland or x window manager, also the bug seems to scale off of the amount of windows open already weirdly enough, alongside the issue being present when closing windows too.

[scaling.webm](https://github.com/hyprwm/Hyprland/assets/123201074/879f6700-4ad5-46a7-acc2-fd300c0910b3)


> I was just curious if these might be related #1468

The artifacting looks similar, but the bug here is applying to wayland native windows too, not just xwayland.

**Comment by burein-ita** [comment]
To me this seems like Hyprland is rendering the first stretched frame of the resize animation. Almost as if the resize animation is not being disabled but instead just made super fast.

This is not limited to terminals. I'm able to reproduce with other programs like Dolphin or Firefox.

**Comment by pd2s** [comment]
same issue here

**Comment by vaxerski** [comment]
the reason is simple.

- resize occurs, hyprland changes the window size, and sends the new size to the window
- hyprland draws the window at its new size, but the window hasn't yet managed to redraw its surface, so hyprland uses the old surface, that has the old dimensions. To fit the window, it stretches the texture.
- window finally redraws its surface with the new size, everything comes back to "normal"

**Comment by TheUnknownCylon** [comment]
@vaxerski 
thx for the pointer into the right direction,
the stretching is gone when i simply set the windowBox width/height to the texture width/height in `renderSurface()`,
however this introduces a new visual artifact: the part of the window without texture will briefly show the underlying window/background (until the window filly redraws its surface I guess).

When I resize windows in Sway, I don't notice this visual artifact. By any chance, do you know why this does not happen in Sway? Does it wait to redraw the entire screen until all windows finally redraw their surface (I guess it does not...)? Is there something else that we can do about it in Hyprland?

**Comment by vaxerski** [comment]
IIRC sway does what you did to hyprland. Dunno about other specifics.

**Comment by TheUnknownCylon** [comment]
just a little update from my side on this issue: I've created a local branch where the stretching is gone,
and that also address the new glitch (where the part w/o texture of the resized window briefly flashes, showing the underlying window/background).

I'll have to test a little more --especially how it behaves when animations are turned on :)
after that I'll have to clean up my code, after witch I'll create a PR.
it may take a week or two tho.

**Comment by TripleTrable** [comment]
@TheUnknownCylon could you share what you already changed or reference your PR? 
I am having the same Problem and this is currently the only show stopper for going to Wayland for me.

**Comment by vaxerski** [comment]
worth noting I am unable to repro this on hyprland anymore

**Comment by burein-ita** [comment]
Can confirm. It doesn't happen to me anymore.

**Comment by KaiJan57** [comment]
I still see this bug, even though it disappears much quicker than in earlier versions (v0.35.0). It is most annoying when trying to resize windows manually…

**Comment by TripleTrable** [comment]
Same for me. I've build the 95abf1220f56acbe88517799fc4b92be2e908575 commit from master to test the newest version. It has improved, on some resizes from small to large it is visible that the old window is drawn in the center from the new one with transparent background on the "new" larger window. Other times nothing has changed.

**Comment by haasn** [comment]
FWIW I still get something like this on v0.35.0 when toggling windows between windowed and fullscreen with animations disabled. I'll try and test master tomorrow, in case there was a fix there.

**Comment by vaxerski** [comment]
> switching fullscreen windows also exhibits this issue

dasa different bug I forgot the #

>  It has improved, on some resizes from small to large it is visible that the old window is drawn in the center from the new one with transparent background on the "new" larger window. Other times nothing has changed.

not much can be done about that

**Comment by burein-ita** [comment]
> It has improved, on some resizes from small to large it is visible that the old window is drawn in the center from the new one with transparent background on the "new" larger window.

GTK apps do that i.e. Firefox, GIMP, it's a known bug. Also alacritty, but that's a problem on their side.

**Comment by vaxerski** [comment]
it's not any bug. It just takes a while for an app to realloc its buffers and re-render itself at a new size.

**Comment by TripleTrable** [comment]
> GTK apps do that i.e. Firefox, GIMP, it's a known bug. Also alacritty, but that's a problem on their side.

That explains the "render issues". Thanks for explaining

**Comment by KaiJan57** [comment]
I am still experiencing issues. It looks like when the size of a window changes, the „old render“ is stretched to the new window size until the application gets the chance to rerender itself… is that intended behaviour? In case it is, I think it is quite irritating. It would be really nice to have an option that controls how „rendering gaps“ should be filled.

**Comment by bigfatbrowncat** [comment]
Could we please somehow add a mode in which the resizing process is slowed down to the timings of the underlying processes redrawing, like it is implemented in MacOS?

The only good way of doing resizing is:
1. The user starts changing the window size — moved mouse 3 pixels right
2. The application got the new buffer to draw its contents. The new buffer is 3 pixels wider
3. The compositor redraws the new state with the resized application window. Without any glitches or flickers.

If you used Apple OSes, you could have noticed that some native applications have low "resizing FPS", i.e. they redraw the window only 5-10 frames per second when you drag the window's corner. For some reason many programmers are very afraid of this lag and they try to overcome it by different techniques that create equally ugly result: stretching the old contents, moving the contents somehow... Windows is the most infamous OS for this stuff.

Please, let us not see such things in Hyprland. May we please create a mode where resizing is clear and beautiful?
