### ISSUE TITLE
Master Layout: Config option to add new windows below the selected one

### ISSUE THREAD

**Issue by toniz4** [hyprwm/Hyprland#2769]
### Description

It would be nice if it was possible to add a configuration option like `new_on_top`, but instead of putting the new window on top of the stack, or the bottom, put it after the current focused window. Like this dwm patch that I used back in the days https://dwm.suckless.org/patches/attachbelow/.

I would try to submit a PR with those changes, but I'm not a cpp programmer, and even my knowledge in c is pretty limited.

**Comment by soufhehe** [comment]
can be closed 

master:new_on_active:after does that
