### ISSUE TITLE
Swaylock uses different keyboard layout

### ISSUE THREAD

**Issue by LiGoldragon** [hyprwm/Hyprland#2772]
### Hyprland Version

0.27.0

### Bug or Regression?

Bug

### Description

Config uses colemak
```
    input {
      kb_layout = us
      kb_variant=colemak
    }
```
But swaylock obviously does not.

### How to reproduce

Use different keyboard layout, then lock with swaylock.

**Comment by vaxerski** [comment]
It's a false myth that everyone seems to repeat. Studies have shown no difference in typing abilities between qwerty and other popular layouts like dvorak.

**Comment by LiGoldragon** [comment]
From an AI analysis of real world hand movements[1]:

During the research I've identified the following results: in terms of efficiency
QWERTY - 0% (baseline)
Dvorak - +77%
Colemak - +84%
Workman - +101%
Halmak - +134%

[1]: https://github.com/kaievns/halmak

**Comment by LiGoldragon** [comment]
> I also fail to see the reasoning for layout propaganda here.

I understand why some people don't have time to improve their typing efficiency, so there is no need to perceive the information it as an attack. All is as it should be. Peace, gratitude, joy. 🙏

**Comment by vaxerski** [comment]
passive-aggressive comments won't get you anywhere.

"efficiency" is misleading here, as less finger movement does not necessarily lead to faster typing.

https://repository.kulib.kyoto-u.ac.jp/dspace/bitstream/2433/139379/1/42_161.pdf

**Comment by LiGoldragon** [comment]
@vaxerski I'm very sorry I offended you. Thank you :pray:

**Comment by LiGoldragon** [comment]
Related: https://github.com/hyprwm/Hyprland/issues/1881

**Comment by LiGoldragon** [comment]
Using `kb_variant=` results in the same problem with a colemak keyboard also using `kb_variant=` in order to get around the general `kb_variant` misbehavior while still setting the laptop keyboard to colemak in hyprland (which breaks the laptop hyprland binds and swaylock on all keyboards.)

**Comment by LiGoldragon** [comment]
Adding a sway config with the layouts and using `resolve_binds_by_sym` option gives agreeable results for now. The real problem lies with the way linux handles layouts system-wide instead of per-device, so `hypr` is doing a good job at haywiring a solution. Thank you all :pray:
