### ISSUE TITLE
Hyprland Doesn't Use Whole Screen for Lower Resolutions

### ISSUE THREAD

**Issue by Creeper0004** [hyprwm/Hyprland#2773]
**This is a duplicate of https://github.com/hyprwm/Hyprland/issues/2743.**

### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Regression

### Description

Hyprland doesn't use the whole screen if the set resolution is smaller than the screen's native resolution. I set the resolution to 1920x1080 on my laptop with a 4k screen (no external monitors). This causes Hyprland to only use the top-left quarter of the screen.

This happened after upgrading Hyprland from 0.27.0-1 to 0.27.2-1 on Arch Linux. Downgrading back to the previous version fixes the issue.

This issue seems to be closely related to #2364.

### How to reproduce

1. Get laptop with a 4K monitor
2. Install Arch Linux and Hyprland
3. Add `monitor=eDP-1, 1920x1080,auto,1` to your config

### Crash reports, logs, images, videos

![hyprland_bug_uses_part_of_screen](https://github.com/hyprwm/Hyprland/assets/48888285/85196955-e1c8-4918-a4af-13961ec3453e)
The transparent area of the above image is black on my screen.

**Comment by vaxerski** [comment]
if anything, this looks like a wlr issue. Can you do a git bisect?

**Comment by romanstingler** [comment]
@Creeper0004 I posted my build in 
https://github.com/hyprwm/Hyprland/issues/2764#issuecomment-1646597088
you could try that one. 
I think that wlroots messed up the drm part.

**Comment by Ay1tsMe** [comment]
Also have this issue. Exact same setup. I have a 4k monitor set to 1920x1200 and it only uses a quarter of the screen

**Comment by MightyPlaza** [comment]
can you guys build wlroots and test tinywl
like vaxry said this is likely a wlroots issue and should be reported/handled on their gitlab

**Comment by Ajayvirmoti** [comment]
Check monitor config in hyprland.conf
correct way to add monitor is:
monitor=name,resolution,offset,scale

eg: monitor=DP-1,1920x1080@144,0x0,1 [For 1920x1080 DPs]

Or go through - [https://wiki.hyprland.org/0.18.0beta/Configuring/Monitors/](https://wiki.hyprland.org/0.18.0beta/Configuring/Monitors/)

**Comment by scornet256** [comment]
I think just as #2743 this can be closed as well.
