### ISSUE TITLE
Documented group_insert_after_current seems not to be a valid option

### ISSUE THREAD

**Issue by 875d** [hyprwm/Hyprland#2777]
### Hyprland Version

Hyprland, built from branch main at commit 7091d4e5979720ddb30f540b2d7da48080bf2487 dirty (animationmanager: optimize avar state). Tag: v0.27.2-7-g7091d4e5  flags: (if any)

### Bug or Regression?

Bug

### Description

[Docs document](https://wiki.hyprland.org/Configuring/Variables/) a 	`group_insert_after_current` option.

I have put:
```
group_insert_after_current = true
```
in the `misc` section of config file.

Hyprland complaints that there is no such field.

### How to reproduce

See above

**Comment by vaxerski** [comment]
outdated hl build lol
