### ISSUE TITLE
d7e9eb6 breaks shaders

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [hyprwm/Hyprland#2778]
### Hyprland Version

Hyprland, built from branch makepkg at commit 0af97636fa658dc5304402a64b5069134cf79b9c dirty (Nix/HM module: solve conflict with upstream HM module). Tag: v0.27.2-28-g0af97636

### Bug or Regression?

Bug

### Description

After https://github.com/hyprwm/Hyprland/commit/d7e9eb65e233f216688377df43359a822a5d098f shaders are silently broken (I don't see any errors in log, just `[LOG] Shaders initialized successfully.`). 

### How to reproduce

Build anything after https://github.com/hyprwm/Hyprland/commit/d7e9eb65e233f216688377df43359a822a5d098f and `screen_shader` in config has no effect.

Build https://github.com/hyprwm/Hyprland/commit/0af97636fa658dc5304402a64b5069134cf79b9c and shaders render as expected.

**Comment by vaxerski** [comment]
my bad, I'll fix this tomorrah

**Comment by vaxerski** [comment]
5a64c73e053f4566b8c4b03587b01d6007fb5412
