### ISSUE TITLE
Windowrule(v2) & Opacity Fails For Firefox

### ISSUE THREAD

**Issue by frkli1965** [hyprwm/Hyprland#2779]
### Hyprland Version

Hyprland, built from branch main at commit b21644b61143de0835fef9c3fa69fbdd2553cdfa  (input: Fix #2376 mouse movement bug in XWayland (#2776)). Tag: ?  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Up until yesterday both the following window rules worked:-

windowrule = opacity 1.0 override 1.0 override,^(firefox)$
windowrule = opacity 1.0 override 1.0 override,^(mpv)$

Following yesterday's commits, Firefox now starts up with 'active_opacity = 0.75' as defined in the 'decoration' section (see below).

I've tried switching to 'windowrulev2' for both but only 'windowrulev2 = opacity 1.0 1.0, class:^(mpv)$' seems to function as expected whereas for FF the outcome is the same as described above.

Decrations are defined as follows:-

decoration {
    blur = yes
    blur_ignore_opacity = true
    blur_new_optimizations = true
    blur_passes = 3
    blur_size = 4
    blur_xray = true
    fullscreen_opacity = 1.0
    active_opacity = 0.75
    inactive_opacity = 0.55
}

NOTE - Some irrelevant entries have been omitted for brevity.

'env MOZ_ENABLE_WAYLAND,1' has also been defined in 'hyprland.conf' btw.

Any suggestions would be greatly appreciated... :-)

### How to reproduce

Please see description...

**Comment by frkli1965** [comment]
The output for 'hyprctl clients' is as follows:-

Window 555c2951b420 -> Window Rules | Hyprland Wiki — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 3846,45
	size: 1908,1029
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: firefox
	title: Window Rules | Hyprland Wiki — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 2844
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

**Comment by frkli1965** [comment]
### AUTOSTART FIREFOX ###

exec-once = firefox
exec-once = ~/.config/hypr/scripts/cleanup_after_start.sh
windowrule = workspace 2 silent, firefox

**Comment by whispcat** [comment]
I can confirmed this bug from latest build from main branch. It might related to this change: [`27dd07f`](https://github.com/hyprwm/Hyprland/commit/27dd07f1b8f89dcf6fe29fec75fdd5c8e9bc9ec4) (windowrules: improve opacity)

**Comment by vaxerski** [comment]
fixed af395a8f5514a978151e237dbf284c49c9422a82
