### ISSUE TITLE
Telegram Screencast

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#278]
Good day to you!

suggesting for supporting screencasting in `telegram`.

![image](https://user-images.githubusercontent.com/52028706/176624536-cde4c224-4961-48ad-8623-7c6614afb607.png)

---

in sway screencasting is working

Thank you!

**Comment by vaxerski** [comment]
screencasting should not be left to me, as I handle everything related to the pipewire screen sharing. Unless telegram uses some mysety protocol, it should work if you have the proper xdg-portal installed and running.

**Comment by fedoranvar** [comment]
okay, i've manage to enable screensharing by forcing `telegram` in `xwayland`

```
env -u WAYLAND_DISPLAY telegram-desktop 
```

**Comment by gmankab** [comment]
hello, i can't share screen in telegram too

flatpaked telegram does not hows any screens at all

![image_2024-02-15_05-54-20](https://github.com/hyprwm/Hyprland/assets/73340745/d8589f59-902e-44d5-83b6-c265791ea10a)

binary telegram build from site shows dark screen

![image_2024-02-15_06-16-49](https://github.com/hyprwm/Hyprland/assets/73340745/ac260165-74f6-4762-ad2c-69c0d1a16c9c)

also i can not force telegram in xwayland via command provided above:
```bash
env -u WAYLAND_DISPLAY ./Telegram
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
```

screen sharing works in obs and discord without any problems

this packages are installed:
```shell
xdg-desktop-portal-hyprland
xdg-desktop-portal-wlr
wireplumber
pipewire
```

my os is fedora silverblue with hyprland installed via rpm-ostree
