### ISSUE TITLE
Toggle special workspace has stopped working

### ISSUE THREAD

**Issue by hirad1986** [hyprwm/Hyprland#2782]
### Hyprland Version

Hyprland, built from branch main at commit b21644b61143de0835fef9c3fa69fbdd2553cdfa dirty

### Bug or Regression?

Bug

### Description

Hi. I'm using hyprland-nvidia-git on Arch and its been a few days since suddenly togglespecialworkspace has just stopped working. I can move windows to special workspace, but the keybinding for toggling to see the windows stopped working. I tried changing the keybindings, or run hyprctl dispatch togglespecialworkspace, but nothing seem to work.

I even tried with a fresh configuration (auto generated, with only adding keybinding for special workspace). Still nothing.

### How to reproduce

use the keybinding to move window to special workspace:
`bind = $Mod, space, movetoworkspace, specialworkspace`
the window disappears. (goes to special workspace?)
then use keybinding to toggle it:
`bind = ALT, Space, togglespecialworkspace`
But nothing happens.
try:
`hyprctl dispatch togglespecialworkspace`
says ok, but still nothing happens

**Comment by MightyPlaza** [comment]
special not specialworkspace

**Comment by vaxerski** [comment]
^
