### ISSUE TITLE
Wallpaper not set on full screened video when swiping workspace

### ISSUE THREAD

**Issue by MiniApollo** [hyprwm/Hyprland#2786]
### Hyprland Version

v0.27.2

### Bug or Regression?

Bug

### Description

when i swipe workspace on full screened video the wallpaper is black and not what i set with swaybg 
During the swiping transition the wallpaper is black

### How to reproduce

full screen any YouTube video and swipe with touchpad to another workspace

**Comment by vaxerski** [comment]
aint this fixed in -git?

**Comment by MiniApollo** [comment]
i'm on stable 
I don't know maybe?

**Comment by vaxerski** [comment]
it was fixed with https://github.com/hyprwm/Hyprland/commit/f4f0f35c5b2725189563fc65e17a0141fd801eb7

**Comment by MiniApollo** [comment]
Thank you
