### ISSUE TITLE
Can't launch Hyprland from TTY 

### ISSUE THREAD

**Issue by hsadoyan** [hyprwm/Hyprland#2788]
### Hyprland Version

hyprland-nvidia from AUR. Signature not set because hyprland not running

### Bug or Regression?

Bug

### Description

I have a Manjaro system running KDE Plasma on my desktop. Recently switched my laptop to Hyprland and liked it a lot, so looking to do the same thing here. 

Installed hyprland from pacman.
Switched to new tty session. Ran `Hyprland` and got  a crash. Only red error is `seatd.sock permission denied` which seems optional.

Opened crash report at `~/.hyprland/` in my KDE session and saw `[CRITICAL] m_sWLRBackend was NULL!`

Tried again with hyprland-nvidia  and got the same result

### How to reproduce

My repro steps are in the description.

**Comment by MightyPlaza** [comment]
@vaxerski nvidia
