### ISSUE TITLE
No CMAKE_CXX_COMPILER could be found

### ISSUE THREAD

**Issue by shaolingit** [hyprwm/Hyprland#279]
While compiling on fedora 36 and after all the dependencies listed here :
"gdb ninja-build gcc cmake libxcb xcb-proto xcb-util xcb-util-keysyms libXfixes libX11libXcomposite xinput libXrender pixman wayland-protocols-devel wlroots wlroots-devel cairo pango meson"
i got this error after running:
`sudo make install`
this is the error: 
`-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/desktop/.wm/Hyprland/build/CMakeFiles/CMakeOutput.log".
See also "/home/desktop/.wm/Hyprland/build/CMakeFiles/CMakeError.log".
make[2]: *** [Makefile:91: release] Error 1
make[2]: Leaving directory '/home/desktop/.wm/Hyprland'
make[1]: *** [Makefile:106: all] Error 2
make[1]: Leaving directory '/home/desktop/.wm/Hyprland'
make: *** [Makefile:113: install] Error 2`

I am sorry if the fix is as easy as installing a package i tried everything. Thank you.

**Comment by fufexan** [comment]
Try `export CXX=g++`, then running the build again.

**Comment by bceric7** [comment]
You may not have a c++ compiler installed. Please try installing the gcc-c++ package.

**Comment by shaolingit** [comment]
So it turn out both of you were right, thanks a lot. but i still have a problem while compiling should i make a new issue or post the problem here?

**Comment by vaxerski** [comment]
post ere

**Comment by shaolingit** [comment]
ok

**Comment by shaolingit** [comment]
`CMake binary for 1 is cached.                                                                 Preliminary CMake check failed. Aborting.
Run-time dependency cairo found: NO (tried pkgconfig and cmake)

src/meson.build:4:0: ERROR: Dependency "cairo" not found, tried pkgconfig and cmake`

**Comment by shaolingit** [comment]
i know but cairo is installed

**Comment by fufexan** [comment]
what about its headers n stuff?

**Comment by shaolingit** [comment]
![Screenshot from 2022-06-30 21-25-56](https://user-images.githubusercontent.com/94686050/176772345-673c3fe3-9966-4121-b058-0466e97b19f7.png)

**Comment by shaolingit** [comment]
> what about its headers n stuff?

would you explain please ?

**Comment by bceric7** [comment]
Since you're on Fedora, your package names will be different from those on Arch. Fedora typically splits its development packages off separately, usually they end in "-devel". So you need to install cairo-devel, pango-devel, pixman-devel, wayland-protocols-devel, libxcb-devel, etc.

**Comment by vaxerski** [comment]
oh god fedora, if you barely understand linux good luck with getting hyprland to compile and run on fedora. I haven't heard of a single successful attempt yet

**Comment by bceric7** [comment]
I have hyprland successfully running on Fedora - it was pretty easy to get running.

**Comment by vaxerski** [comment]
oh, you could DM me some instructions on discord, I'd put them in the wiki. I've just heard fails lmao

**Comment by shaolingit** [comment]
> oh god fedora, if you barely understand linux good luck with getting hyprland to compile and run on fedora. I haven't heard of a single successful attempt yet

we shall see i used arch for over 3 years now thought of trying fedora and i still have a seperate hard drive with a good install . i got bored and distrohopped and i like fedora the only thing is i hated how frequent the updates are because of my poor insternet connection getting around 330kb/s all day

**Comment by shaolingit** [comment]
> I have hyprland successfully running on Fedora - it was pretty easy to get running.

do you have step by step instructions you can share

**Comment by vaxerski** [comment]
sure

**Comment by shaolingit** [comment]
> > oh, you could DM me some instructions on discord, I'd put them in the wiki. I've just heard fails lmao
> 
> > do you have step by step instructions you can share
> 
> I don't have discord, sorry I know I'm weird, but I'd be happy to make some Fedora instructions. Give me a while to make a clean Fedora install in a VM, and then I'll go through the process and write everything down. I'll put it all in the Discussions page, if that's cool with you.

sure take your time

**Comment by shaolingit** [comment]
it has successfully installed thank you very much still waiting for the guid tho thank you guys a lot for the support.
