### ISSUE TITLE
cursor-shape-v1 support

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#2792]
### Description

This allows clients to offload cursor rendering to the compositor, requires wayland-protocols 1.32
wlroots support: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/04e4e06986d1aad35d3ab097f3f473b799a576e2
sway support: https://github.com/swaywm/sway/pull/7571
mpv support: https://github.com/mpv-player/mpv/pull/11701
foot support: https://codeberg.org/dnkl/foot/pulls/1389

**Comment by vaxerski** [comment]
done f5913135c638997f8c13a52d0760803947ae3889
