### ISSUE TITLE
workspace_swipe_numbered enable causes problems on first workspace

### ISSUE THREAD

**Issue by sickmitch** [hyprwm/Hyprland#2798]
### Hyprland Version

b08b72358ad549fd066e5be0fc3aa4c9df367607

### Bug or Regression?

Bug

### Description

Very similar to #1563 but horizontally swiping and it happens only if there is already a window opened in workspace 2.
Tried around different workspaces combination but seems to be only on transition from first to second absolute workspace (it doesn't happens if workspace 1 is empty and transitioning from 2 to 3 and so on).

### How to reproduce

- set gestures_workspace_swipe_numbered to yes
- open a window on WS2
- open a window on WS1
- swipe to WS2

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12147055/hyprland.log)
The log of the current session where i recorded the gif.
https://imgur.com/mcAl05v
A gif showing the bug

**Comment by Quplet** [comment]
Bug still persists on v0.30.0. I have `workspace_swipe_use_r = true` which causes it.
Gif: [https://imgur.com/a/b1MwbHk](url)

**Comment by vaxerski** [comment]
can be closed, the option has been removed
