### ISSUE TITLE
Can't drag icons and files on touchpad 

### ISSUE THREAD

**Issue by ked1108** [hyprwm/Hyprland#280]
Unable to drag icons with touchpad and when it does happen it lags a lot and is basically unusable

**Comment by fufexan** [comment]
Works fine for me when dragging images in Firefox.

**Comment by vaxerski** [comment]
lag was fixed in 6ec16fdcdaf0ffa377db492a9d7d92bdd89044d9 (you're probably using the releases), the rest is maybe because you have disabled focus_follows_mouse?

**Comment by ked1108** [comment]
okay, ig I will use the git repo from now on, also I am using focus_follows_mouse
