### ISSUE TITLE
Import environment variables into systemd in NixOS modules

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/Hyprland#2800]
## Issue

Frankly speaking, using the nixos modules without modification is a XDG-"nightmare".

This is because almost all XDG/GIO calls happen through portals. The problem being that the portals are being started as a user session service by systemd. This means that important environment variables like PATH and XDG_DATA_DIRS are not accessible. Then again there are many applications that ignore default mime applications completely and look at [Well-known Message Bus Instances](https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-types) instead.

To bring order into this situation I personally did 2 things:
- Some packages install well-known bus type dbus services (usually located in `.../share/dbus-1/`) . To select a default I will symlink the corrects one the most dominant name (usually something like org.freedesktop.BasicFoo1).
- I add the following line  in my config after declaring variables and before starting any services:
```
exec-once = ${pkgs.dbus}/bin/dbus-update-activation-environment --systemd --all
```

## Proposal

I would like to:
1. Add this information to documentation. Even the first point is necessary because Hyperland does not ship with any default tools, so every n00b will throw together their own distro and cry about XDG issues.
2. Add the line in the config by default (at least when using nix module). Home-manager already provides a way to declare environment variables for a session, so it should be fine to add the line at the top of the config. 

## Related Issues
[NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/issues/160923)

**Comment by PatrickShaw** [comment]
Are you running home-manager?

To my knowledge, something similar is already handled for those running HM: https://github.com/hyprwm/Hyprland/blob/main/nix/hm-module.nix#L138

**Comment by Mikilio** [comment]
I think I remember seeing that. However it still still is not enough.
Important variables for xdg are missing like XDG_DATA_DIRS and PATH. If
there isn't any security issue I would just shorten the line by using the
flag `--all`.

**Comment by fufexan** [comment]
Are you sure we want to import all environment variables when starting the session? I don't have info on this so I just kept the var list small so as not to potentially conflict with other things.

**Comment by Mikilio** [comment]
I wasn't too concerned about any side effects because greetd is started by a greetd user anyways. I agree, in general it might be better to import only the ones you need. However right now some seems to be missing. I actually based my config off of yours and I still encountered the 25sec issue when regreet starts.

**Comment by spikespaz** [comment]
> Are you sure we want to import all environment variables when starting the session? I don't have info on this so I just kept the var list small so as not to potentially conflict with other things.

I have been deliberating this with myself as well. I think maybe it would be the most painless way to do. If we do import all environment variables, programs started from waybar click handlers would actually use my `QT_QPA_PLATFORMTHEME`. Right now they don't, and I haven't found an easy way to handle this without carefully wrapping each individual program (or having waybar be wrapped and pass along the environment).

Considering that most distros would have every variable imported, it wouldn't be unreasonable to do. However, I know that this isn't "the NixOS way".

**Comment by spikespaz** [comment]
This seems to be it. I don't use Sway, so I don't know if anything else works as I expect or if it has the same problems I do on HL.
<https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/sway.nix#L311>

**Comment by Mikilio** [comment]
Unfortunately the above link again is intended for a sway session started by systemd with a proper user. The sway session I launch is before any login and just to run regreet for greetd. While I don't know why, in this particular use-case those variables are not enough (it's actually one of the first things I tried).

**Comment by Mikilio** [comment]
I am sorry for the confusion in my last two comments for some reason I was thinking about this issue rharish101/ReGreet#34 which had a very similar workaround. As again environment variables where missing.

**Comment by Mange** [comment]
Another option is to allow us to specify a list of variables to import.

(I'm a total newbie at Nix so bear with me here.)

```nix
systemdIntegration.enable = lib.mkEnableOption "Hyprland wayland compositor";

systemdIntegration.variables = lib.mkOption {
  type = with lib.types; listOf (string);
  default = [ "DISPLAY" "HYPRLAND_INSTANCE_SIGNATURE" "WAYLAND_DISPLAY" "XDG_CURRENT_DESKTOP" ];
};

systemdIntegration.extraVariables = lib.mkOption {
  type = with lib.types; listOf (string);
  default = [ ];
};
```

```nix
xdg.configFile."hypr/hyprland.conf" = let
      # ...
    systemdVars = cfg.systemdIntegration.variables ++ cfg.systemdIntegration.extraVariables;
    updateEnvironment = "${pkgs.dbus}/bin/dbus-update-activation-environment --systemd ${lib.concatStrings systemdVars " "}";

    in lib.mkIf shouldGenerate {
      text = lib.optionalString cfg.systemdIntegration.enable ''
        exec-once = ${updateEnvironment} && systemctl --user start hyprland-session.target
      '' + lib.optionalString (combinedSettings != { })
        (toHyprconf combinedSettings 0)
        + lib.optionalString (cfg.extraConfig != "") cfg.extraConfig;
      # ...
    };
```

Then users can configure it like this:

```nix
wayland.windowManager.hyprland = {
  enable = true;
  systemdIntegration = {
    enable = true;
    extraVars = [ "PATH" "QT_QPA_PLATFORMTHEME" ];
  };
};
```

**Comment by spikespaz** [comment]
> Another option is to allow us to specify a list of variables to import.
> ...

This is totally viable and definitely something that we should do. However, this can already be accomplished by another `config.exec_start`, if you need it now.

I think the goal of this issue is to get the defaults correct, not to offload that responsibility to the user (which is what we would effectively do if we allowed `extraVars` without getting the defaults correct).

**Comment by Mikilio** [comment]
Since then options seem to have been created and I can't reproduce the issues anymore, so closing for now.
