### ISSUE TITLE
Segmentation fault when opening a single client

### ISSUE THREAD

**Issue by smb374** [hyprwm/Hyprland#2808]
### Hyprland Version

b08b72358ad549fd066e5be0fc3aa4c9df367607

### Bug or Regression?

Bug

### Description

After the wallpaper is set (either `hyprpaper` or `swaybg`), spawning a client will cause segmentation fault with no obvious error message in the crash report.

The problem also occurred on all v0.27.* versions, while everything works after I downgraded to v0.26.0.

### How to reproduce

1. Start hyprland, either from TTY or display manager.
2. Spawn any client (e.g. spawn a terminal from keybind)

### Crash reports, logs, images, videos

v0.27.2: [hyprlandCrashReport34879.txt](https://github.com/hyprwm/Hyprland/files/12161211/hyprlandCrashReport34879.txt)
v0.27.1: [hyprlandCrashReport35968.txt](https://github.com/hyprwm/Hyprland/files/12161215/hyprlandCrashReport35968.txt)
v0.27.0: [hyprlandCrashReport36507.txt](https://github.com/hyprwm/Hyprland/files/12161219/hyprlandCrashReport36507.txt)

**Comment by vaxerski** [comment]
it's a regression then, do a git bisect please

**Comment by smb374** [comment]
Took me some time doing git bisect

Result first bad commit: [01f85a09a981eb6c8784d459f729d418c0dd19e3](https://github.com/hyprwm/Hyprland/commit/01f85a09a981eb6c8784d459f729d418c0dd19e3)

Config used for testing: [hyprland.conf](https://github.com/hyprwm/Hyprland/files/12161810/hyprland.conf.txt) (It comes with a `.txt` extension as GitHub doesn't support `.conf` files.)

**Comment by vaxerski** [comment]
can you build in debug and provide the stacktrace? this is weird, I can't repro and you seem to be the only one affected.

when it crashes, to obtain the stacktrace, on systemd, do `coredumpctl`, find the last occurrence of hyprland (press END to go to the end) note its PID and then `coredumpctl debug <pid>`. When asked about symbols, say `y` when asked about pagers, do `c`. When you get to `(gdb)` do `bt -full` and paste the output here

**Comment by smb374** [comment]
Sorry for the late reply as it was near midnight in my region, here is the backtrace:
[gdb_hypr.log](https://github.com/hyprwm/Hyprland/files/12167744/gdb_hypr.log)

I've been using `pwndbg` so the output may be different.
Hyprland is built by `make debug`.

**Comment by smb374** [comment]
I got some time recently and went to HEAD to see what went wrong, it turns out there's a
`nullptr` case not be handled properly:
```cpp
// src/protocols/XDGOutout.cpp
void CXDGOutputProtocol::onManagerGetXDGOutput(wl_client* client, wl_resource* resource, uint32_t id, wl_resource* outputResource) {
    const auto OUTPUT = wlr_output_from_resource(outputResource);

    if (!OUTPUT)
        return;

    const auto PMONITOR = g_pCompositor->getMonitorFromOutput(OUTPUT);

    if (!PMONITOR)
        return;

    SXDGOutput* pXDGOutput = m_vXDGOutputs.emplace_back(std::make_unique<SXDGOutput>(PMONITOR)).get();
#ifndef NO_XWAYLAND
    if (g_pXWaylandManager->m_sWLRXWayland->server->client == client) // <- Here
        pXDGOutput->isXWayland = true;
#endif
    pXDGOutput->client = client;
    // ...
}
```
I modified the line with the `nullptr` checks on `m_sWLRXWayland` and `m_sWLRXWayland->server`, things starts to work as usual, except that later `CWaylandResource::~CWaylandResource()` segfaults when quitting hyprland.

I think that this is an uncovered case that one of these is null in the context when the function is executed, and a similar error can be traced back to [01f85a09a981eb6c8784d459f729d418c0dd19e3](https://github.com/hyprwm/Hyprland/commit/01f85a09a981eb6c8784d459f729d418c0dd19e3).

**Comment by smb374** [comment]
@vaxerski should I open a PR for this temporary fix or leave you guys to inspect further into this issue?

**Comment by vaxerski** [comment]
yea sure

**Comment by smb374** [comment]
As for the segmentation fault on exit, I've discovered some unusual stuff.

The deconstructor will call `wl_resource_destroy()`, which calls `wl_map_lookup_flags()` where the segfault happened.

Here's the code for the function:
```c
// src/wayland-util.c:380
uint32_t
wl_map_lookup_flags(struct wl_map *map, uint32_t i)
{
	union map_entry *start;
	uint32_t count;
	struct wl_array *entries;

	if (i < WL_SERVER_ID_START) {
		entries = &map->client_entries;
	} else {
		entries = &map->server_entries;
		i -= WL_SERVER_ID_START;
	}

	start = entries->data;
	count = entries->size / sizeof *start;

	if (i < count && !map_entry_is_free(start[i])) // <- Segfault happens here
		return map_entry_get_flags(start[i]);

	return 0;
}
```
where `map = &client->objects` and `id = 23`.

I looked up gdb and it tells me that (`0x55664a2dbbb0` is address of `m_pWLResource->client`):
```
pwndbg> p ((struct wl_client *)(0x55664a2dbbb0))->objects
$24 = {
  client_entries = {
    size = 328,
    alloc = 512,
    data = 0x4
  },
  server_entries = {
    size = 0,
    alloc = 0,
    data = 0x4
  },
  side = 0,
  free_list = 0
}
```
Notice that `start` is assigned to `map->client_entries->data = 0x4` which is clearly an invalid address for later operation.

I suppose that `data` should be something, but the client bound with `m_pWLResource` somehow contains a corrupted data in `objects->client_entries->data`.

**Comment by vaxerski** [comment]
resource gets destroyed and we are destroying it again prolly

**Comment by romanstingler** [comment]
@smb374 is this resolved for you ??

**Comment by smb374** [comment]
> @smb374 is this resolved for you ??

I didn't have time over the last few months to investigate the double destroy problem mentioned above as I was applying for graduate schools. Since the fix is merged and Hyprland works without any problem (including the double destroy problem) on my machine in the following versions, the issue can be considered resolved.

**Comment by romanstingler** [comment]
please close the issue as you are the op
