### ISSUE TITLE
[Feature request or documentation request] open all windows as floating

### ISSUE THREAD

**Issue by anoraktrend** [hyprwm/Hyprland#2811]
### Description

I think this may already be possible using window rules but it's not documented anywhere i can  easily find it.

**Comment by vaxerski** [comment]
`windowrule = float, .*` wtf

**Comment by anoraktrend** [comment]
Note the Documentation Request. portion of the title. This is not documented in the official documentation or any where people can easily find it. That is the issue. Thus why I made this issue to begin with.

**Comment by vaxerski** [comment]
what was not documented? it says regex. Regex can easily be made to accept "any"
