### ISSUE TITLE
After long suspend monitor placement is reversed

### ISSUE THREAD

**Issue by ryansantos1174** [hyprwm/Hyprland#2813]
### Hyprland Version

Hyprland, built from branch  at commit 2fed1badbfb3b5a10641ee41c55d7fa7c21682c8 dirty (). Tag: v0.27.1  flags: (if any)

### Bug or Regression?

Bug

### Description

I have a dual monitor setup. I use systemctl suspend to suspend my system. However, usually after a few hours of being suspended, once I wake the computer back up my wallpapers are no longer loaded and my monitor that is physically on the left, my computer thinks is to the right. Using "hyprctl monitors" I can see that the ordering of the monitors has changed, which I would think would be the source of the issue. Logging out of Hyprland back to SDDM and loggin back in will fix the issue. If I hit suspend and shortly come back, there is no issue. Anything longer than about an hour and the issues will happen consistently. 

### How to reproduce

Have two monitors and suspend the system with systemctl suspend then wait a while (maybe around an hour) and log back in.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12166345/hyprland.log)

**Comment by MightyPlaza** [comment]
send the hyprctl monitors

**Comment by ryansantos1174** [comment]
Monitor DP-3 (ID 0):
	2560x1440@59.951000 at 0x0
	description: LG Electronics LG ULTRAGEAR 205MXZJ75461 (DP-3)
	make: LG Electronics
	model: LG ULTRAGEAR
	serial: 205MXZJ75461
	active workspace: 8 (8)
	special workspace: 0 ()
	reserved: 0 48 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor HDMI-A-1 (ID 1):
	1600x900@59.978001 at 2560x540
	description: Sceptre Tech Inc Sceptre J20 (HDMI-A-1)
	make: Sceptre Tech Inc
	model: Sceptre J20
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 48 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

**Comment by MightyPlaza** [comment]
before and after

**Comment by MightyPlaza** [comment]
are you by any chance using auto in the monitor configs?
that seems like the only sane explanation

**Comment by ryansantos1174** [comment]
I do use auto to place one of my monitors. Attached is my config, if that helps any more, I'll also try and remove the auto keyword to see if that fixes it. [
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/12267775/hyprland.txt)
](url)

**Comment by ryansantos1174** [comment]
Removing auto to replace the window has fixed the issue.

**Comment by nonetrix** [comment]
Hey, I am confused. I am having this issue but I am not using auto, I've actually had this for a while and only just now thought of having a crack at fixing it. I have the following set
```
monitor=DP-2, 1920x1200, 1920x0, 1
monitor=DP-1, 1920x1080@165, 0x0, 1, vrr, 1
```
As you can see auto is never used, yet if I do `"hyprctl dispatch dpms off` then `"hyprctl dispatch dpms on` the ordering often gets completely messed up like OP showed in Hyprctl. This leads to Ags and Waybar mixing the monitors up and showing workspaces on the wrong displays, maybe I could make Ags use the monitor ID instead but I have no figured out how to do this at all
