### ISSUE TITLE
The Default Hyprland's wallpaper flash only when i try to fullscreen Firefox but not other apps.

### ISSUE THREAD

**Issue by opseter** [hyprwm/Hyprland#2817]
### Hyprland Version

Hyprland, built from branch main at commit a9b8e2159c2813a6951d0b0186fbb7f2f8554d3e dirty (renderer: reset scissor after renderTexturePrimitive). Tag: v0.27.2-54-ga9b8e215  flags: (if any)

### Bug or Regression?

Bug

### Description

When I open firefox and an other application in the same workspace and try to fullscreen firefox,I can see the default wallpaper of hyprland flash. But trying to fullscreen other apps doesn't do the same. If  delete the default wallpaper file, can't see the flash either. 
Found the issue is related to this [commit](https://github.com/hyprwm/Hyprland/commit/f4f0f35c5b2725189563fc65e17a0141fd801eb7)  using `git bisect`.And this bug still exists in the latest git branch.

### How to reproduce

1.open firefox and an another app in a workspace.
2.try to fullscreen firefox
3.you can see the default wallpaper flash.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/43690308/b587e783-c0cb-42dc-9c66-95d758439fef

**Comment by vaxerski** [comment]
it's a firefox bug. Technically can be fixed with `forcergbx`

**Comment by opseter** [comment]
Add the rule `windowrulev2 = forcergbx, class:firefox` in my config, no more wallpaper flash. But it has side effects. Firefox's pop-up menu is displayed with black borders.
before:
![20230727-081605](https://github.com/hyprwm/Hyprland/assets/43690308/0af6551e-216f-49b4-890b-28586dc8b248)
after:
![20230727-081624](https://github.com/hyprwm/Hyprland/assets/43690308/7a1ff2cc-9834-4563-bf14-30667653a02e)
 Is there a perfect way to solve this problem?
And I wonder why firefox works fine in the release version `0.27.2`, after that commit the problem appeared.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/e23076c5-b4bd-4b48-96b2-2821cd72a870)

https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/protocol/wayland.xml#L1581-1610

![image](https://github.com/hyprwm/Hyprland/assets/43317083/52c3d816-0dbc-4f72-a365-45084e1d8581)

perfectly according to the spec.

**Comment by vaxerski** [comment]
looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1841713

**Comment by willswats** [comment]
For anyone else with this issue, disabling the Hyprland logo makes this a lot less noticeable:

```
misc {
  disable_hyprland_logo = true;
}
```
