### ISSUE TITLE
Damage tracking issues for low framerate Vulkan apps

### ISSUE THREAD

**Issue by scorpion-26** [hyprwm/Hyprland#2826]
### Hyprland Version

Hyprland commit 2ea7d10

### Bug or Regression?

Bug

### Description

Vulkan applications with a framerate below the monitors refresh rate are not damage-tracked correctly on my system. As far as I can tell, OpenGL apps don't exhibit this behaviour. When recording via e.g. OBS, the apps render correctly.
Since it happens on all major compositors (Tested: gnome, plasma, sway, hyprland) and I only have a Nvidia system, I'm unsure whether this is a compositor issue or a symptom of nvidia pushing buggy driver to production. So feel free to close this if you think it's the latter, though I'd appreciate it if someone can investigate if it happens on other vendors.

### How to reproduce

1. Open a Vulkan application
2. Limit framerate to below the monitors refresh rate
3. Move the camera around

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/58082714/a1f6cb2c-7e96-4ca5-a1dd-3dba735cd2ee

*Apologies for the bad quality, I couldn't record via xdg-desktop-portal, since the recorded footage doesn't show the issue. Footage is from my Vulkan application, though the issue isn't specific to my app. I can upload binaries for it though, if needed*

**Comment by vaxerski** [comment]
> Since it happens on all major compositors (Tested: gnome, plasma, sway, hyprland)

safe to say it's not an issue with wlroots, hyprland, or any of the above, but drivers, or your code.
