### ISSUE TITLE
Spotify is blurry only on rotated monitor

### ISSUE THREAD

**Issue by carschandler** [hyprwm/Hyprland#2827]
### Hyprland Version

Hyprland, built from branch  at commit 6beb79f27b84c36b8b9ef5476d861a94a9071009

### Bug or Regression?

Bug

### Description

Spotify is blurry, but only on my vertical monitor. On my horizontal one, it looks fine.
Vertical:
![image](https://github.com/hyprwm/Hyprland/assets/92899389/69c68d13-f0e5-4997-895f-10e6a94d9585)

Horizontal:
![image](https://github.com/hyprwm/Hyprland/assets/92899389/9eaddb0c-9998-4f0e-bafb-0f3c62336d54)

### How to reproduce

Install Spotify, configure one monitor to be rotated, move Spotify window to that monitor.

**Comment by spikespaz** [comment]
I'm no expert, but this *seems* like a problem with CEF. Is Spotify using Wayland or Xwayland?

**Comment by spikespaz** [comment]
Is Hyprland compiled with HiDPI support? What distro are you using?

**Comment by spikespaz** [comment]
Try another CEF program. Does Steam appear blurry on a rotated display?

**Comment by carschandler** [comment]
@spikespaz I tried with the Minecraft launcher and the Steam launcher and both showed the same issue on vertical but not horizontal. It seems you are correct!

**Comment by carschandler** [comment]
Okay so this seems to be at least partially related to scaling...

If I set the scale of my vertical monitor back to 1 (from 1.125), I don't get the issue. I can also open Spotify at any scale (it will be blurry if fractional), and then modify the scale to any other value (fractions included) _after_ Spotify has been opened and then the blur disappears and the proper scale is applied. It's only when I open Spotify _while_ some fractional scale has been applied that the blur occurs.

**Comment by MightyPlaza** [comment]
have you done anything to fix this?

this issue with scaling on xwayland is known and I'm pretty sure it isn't going anywhere
you can use force_zero_scaling to disable the scaling on xwayland to avoid this (https://wiki.hyprland.org/Configuring/XWayland/)

ideally use don't use xwayland to avoid this issue

**Comment by carschandler** [comment]
@MightyPlaza oh thank you! No I never ended up fixing it. I didn't know about these options! I’ll just apply these and close the issue.

**Comment by MightyPlaza** [comment]
@vaxerski xwayland scaling
