### ISSUE TITLE
Cursor does not render

### ISSUE THREAD

**Issue by dmadisetti** [hyprwm/Hyprland#283]
Hi,

The mouse initializes in the upper left corner, and then on either moving the mouse, or launching a window it totally disappears. The mouse still interacts with the screen, I just can't see it! I tried changing the cursor icon (which worked), but I had the same problem.

I'm using the hyprland flake directly with NixOS, pinned at 0.62. I will upload the logs soon as I figure out how to do that with a non-visible mouse.....

I didn't have this issue before using nvidia drivers? But I wasn't able to roll back to a point where it did work.

**Comment by dmadisetti** [comment]
Ok wasn't that bad.

Started, had mouse disappear, killed session and took log

[hyprland.log](https://github.com/hyprwm/Hyprland/files/9022656/hyprland.log)
[dump.log](https://github.com/hyprwm/Hyprland/files/9022657/dump.log)

**Comment by fufexan** [comment]
Have you tried https://github.com/hyprwm/Hyprland/wiki/FAQ#how-do-i-change-me-mouse-cursor?

**Comment by taylor85345** [comment]
Are you on Nvidia? There is a known issue with Hardware cursors on Nvidia. Try setting `$WLR_NO_HARDWARE_CURSORS=1`

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/176760387-059960b6-59a4-4dba-9cf0-09966e165dce.png)
added
