### ISSUE TITLE
Dialog boxes don't appear in the center of the display

### ISSUE THREAD

**Issue by carschandler** [hyprwm/Hyprland#2830]
### Hyprland Version

 Hyprland, built from branch  at commit 6beb79f27b84c36b8b9ef5476d861a94a9071009

### Bug or Regression?

Bug

### Description

I have a horizontal main monitor with a vertical off to the side. It looks a bit like this:
```
                                   _____________
                                  |             |
                                  |             |
                                  |             |
 ________________________________ |             |
|                                ||             |
|                                ||             |
|                                ||             |
|                                ||             |
|                                ||             |
|                                ||             |
|                                ||             |
|________________________________||             |
                                  |             |
                                  |             |
                                  |_____________|
```
Due to the fact that my monitors are not aligned along the y=0 line (I'd imagine this is almost never the case for a vertical monitor), I am forced to offset set the y-position of my main monitor to 500 pixels (since I cannot offset the vertical monitor by -500):

```
monitor=DP-1, 2560x1440@144, 0x500, 1
monitor=DP-2, 2560x1440@144, 2560x0, 1.125, transform, 3
```

This works great and allows my mouse to move evenly across the monitors without jumping up/down, but now when dialog boxes spawn, they are not centered on the display and are usually partially cut off. I can always move them back into focus, but it's an annoyance and in theory they could spawn completely off-screen for other users experiencing this. The expected behavior would be to calculate the position of dialog boxes based on the monitor's active area rather than the "global" layout on which the monitors lie. FWIW, the boxes also spawn partially off-screen in a very similar fashion for the vertical monitor. I have confirmed that the boxes spawn as expected on both monitors as soon as I change the position of my main monitor back to `0x0`. I have also confirmed that it's not the presence of the vertical monitor causing this; deleting the config for that monitor and just leaving the original one still causes it.

![image](https://github.com/hyprwm/Hyprland/assets/92899389/1d8d74bf-00e3-4082-9244-273557209402)

### How to reproduce

Set the y-position of your main monitor to something nonzero, launch a file picker in Firefox somehow.

**Comment by MightyPlaza** [comment]
cannot repro with built in file picker
is this the xdg-desktop-portal-gtk file picker?
also is firefox using wayland?

**Comment by jersa** [comment]
Yep, I just fix these with window rules.

**Comment by MightyPlaza** [comment]
I think I know what is causing this
are you using size/maxsize/minsize windowrules?
if so try using the center windowrule after https://github.com/hyprwm/Hyprland/pull/2935 gets merged

**Comment by carschandler** [comment]
@MightyPlaza I'm actually not using any window rules as of now. I'll try them out pre- and post-merge and see if I can get it working! I also just recently experienced the same behavior with the printer dialog window FWIW.

**Comment by carschandler** [comment]
I think that this was potentially fixed with the addition of negative monitor offsets being allowed. Either way, I'm not experiencing the issue anymore!
