### ISSUE TITLE
Completely hide the groupbar

### ISSUE THREAD

**Issue by tgy** [hyprwm/Hyprland#2831]
### Description

Is there a way the groupbar can be completely hidden?

I currently have the following

```
misc {
    render_titles_in_groupbar = false
}
```

but the bar still remains (with no title)

**Comment by MightyPlaza** [comment]
use workspace rules, and disable decorations.
not working for floating windows for some reason

**Comment by spikespaz** [comment]
Added as item `#8` to #2415, lets keep aesthetic requests for group bars in that issue. Recommend to others to :+1: that issue.
