### ISSUE TITLE
background rendering bug while change workspace

### ISSUE THREAD

**Issue by lukas3141** [hyprwm/Hyprland#2832]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

If i have a windows running in fullscreen and change the workspace via workspace_swipe the background, set by swww or swaybg, isnt rendered until the new workspace is completely visible.

### How to reproduce

- set wallpaper with swww or swaybg
- open any window
- put window in fullscreen via hyprland. i did it with: `bind = $mainMod, f, fullscreen` 
- change workspace with touchpad gestures

**Comment by helixoid** [comment]
Similar to #2756 probably will be fixed in the next release (0.28.0), which will be very optimized and light on resources according to @vaxerski. Really looking forward to that awesome release.

**Comment by lukas3141** [comment]
nice, thanks! i'll close this
