### ISSUE TITLE
Source file doesn't exist ++

### ISSUE THREAD

**Issue by ghost** [hyprwm/Hyprland#2834]
### Hyprland Version

2ea7d10d049e26c9829912da1d16f7f35f5b265d

### Bug or Regression?

Bug

### Description

error:
```
 source file (*) doesn't exist
```
No matter how I link the file it wont work, all files are ```-rwx```
However it seems to be only with my config??
When I generate the default config and just source one file, for example my env.conf, it throws no error's and ```env``` shows the variables but they are not working correctly(no cursor nvidia) same with binds.

If i put everything in one file i still get weird problems:

1)Input wont accept empty values even though they are empty like that in the default config.

2)Values for things like ```render_titles_font_size``` and ```force_zero_scaling``` cannot be set because they dont exist.

3)```No such bezier``` even though its from the default config.

Now  If I comment things out till I get no errors, things are obviously not working. variables are not set as I get no cursor and binds don't work either, so i have to kill from tty.

the default config works fine...

UPDATE:
It seems that hyprland will only read from the hyprland.conf it creates itself. So by just pasting my config into the file hyprland created All is well. (Yes even replacing this file with an exact copy will break it again)  However this still means source files do not work :( They are at least recognized but i get random errors such as ```no such bezier``` and non of the options have an effect. I would still say this is worth investigating, any ideas? This does not happen with sway/wayfire or any other program. The only unique thing about my system is the use of btrfs subvolumes, but I fail to see how that could have an effect.

### How to reproduce

here are my configs (changed to .txt coz github)
They are 99% defaults according to wiki ( I was just setting up a complete default conf):

[hyprland.txt](https://github.com/hyprwm/Hyprland/files/12195962/hyprland.txt)
[theme.txt](https://github.com/hyprwm/Hyprland/files/12195964/theme.txt)
[env.txt](https://github.com/hyprwm/Hyprland/files/12195965/env.txt)
[binds.txt](https://github.com/hyprwm/Hyprland/files/12195966/binds.txt)

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12195987/hyprland.log)

**Comment by BlanXyz** [comment]
I have read through the wiki and my config multiple times and have tried fixing it on my own for a few days now. (Pls someone help, I need hyprland in my life)

**Comment by vaxerski** [comment]
you can't use wildcards in source. Are you using any?

**Comment by BlanXyz** [comment]
I just read through them again and as far as I can tell, no. Some comments may have, but I have already tried removing every single comment.

**Comment by vaxerski** [comment]
sounds like a fs issue then? idk never seen this

**Comment by AlexPresso** [comment]
I also have this issue when I override the config file with a different file having exact same content
Did you find any solution for that ?

**Comment by vaxerski** [comment]
a ghost can't reply. Anyways, closing cuz ghost

**Comment by AlexPresso** [comment]
Sorry but, even if the OP accounts is now a ghost, the "bug" is still here...
