### ISSUE TITLE
centerwindow dispatcher Y offset

### ISSUE THREAD

**Issue by nimaaskarian** [hyprwm/Hyprland#2839]
### Description

`centerwindow` dispatcher centers a floating window. Doesn't care for your bar.
It would be awesome if it could realize the bar height and center according to that, or had an offset argument so we could pass our bar's height manually

**Comment by MightyPlaza** [comment]
done 901236a5356a3f249af7d55e5db69889e50256b8

**Comment by MightyPlaza** [comment]
@vaxerski please close
