### ISSUE TITLE
Daisy-chained monitor does not work with multi-GPU laptop

### ISSUE THREAD

**Issue by ItachiSan** [hyprwm/Hyprland#2840]
### Hyprland Version
AUR package `hyprland-nvidia`.
Output from `hyprland version`:

Hyprland, built from branch master at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (update v0.27.2). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

I was recently able to configure my laptop with Hyprland using the AUR package `hyprland-nvidia` and I followed the steps in the *Multi GPU* page of the wiki.

Now I am able to use my USB-C for DisplayPort and my first monitor works as intended, however the daisy-chained one does not.

The monitor is properly detected from `hyprland monitors`:
<details>
<summary>Console output</summary>

```sh
hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1080@144.000000 at 5120x500
	description: Najing CEC Panda FPD Technology CO. ltd 0x004D (eDP-1)
	make: Najing CEC Panda FPD Technology CO. ltd
	model: 0x004D
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 30 0 0
	scale: 1.25
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 1):
	2560x1440@59.951000 at 2560x0
	description: Dell Inc. DELL U2722DE 3JXQ1H3 (DP-2)
	make: Dell Inc.
	model: DELL U2722DE
	serial: 3JXQ1H3
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-3 (ID 2):
	2560x1440@59.951000 at 0x0
	description: Dell Inc. DELL U2722DE JHXQ1H3 (DP-3)
	make: Dell Inc.
	model: DELL U2722DE
	serial: JHXQ1H3
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
```

</details>

But the screen stays black. 

On my other DE, KDE Plasma, all monitors work perfectly.

### How to reproduce

Have a dual GPU laptop (in my case AMD + NVIDIA).

Use USB-C to connect to the first monitor.

Daisy chain monitor 1 to monitor 2 via DP cable.

Enable required flags in the monitor settings (MST for me).

### Crash reports, logs, images, videos

Here is a picture of the issue:

![photo_2023-07-29_15-08-44](https://github.com/hyprwm/Hyprland/assets/1223421/8eed8736-2d32-46bf-9f43-48cfd1240e33)

Here is Hyprland log:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12207225/hyprland.log)

**Comment by MightyPlaza** [comment]
what gpu is being used for the monitors?

**Comment by ItachiSan** [comment]
The AMD integrated GPU is used for the internal monitor and the HDMI port, the NVIDIA card for DisplayPort.

So, I can't really deactivate the NVIDIA GPU as I need it for the external monitors.

**Comment by MightyPlaza** [comment]
then you need to set up nvidia optimus, which I guess you didn't otherwise it would probably already work

**Comment by vaxerski** [comment]
this is an issue with wlroots and proprietary drivers

**Comment by ItachiSan** [comment]
Seems the newest NVIDIA driver finally made daisy-chaining a reality! :smile: 
Version is: 545.29.02
