### ISSUE TITLE
Guaranteed crashing with dual monitors when `swapwindow` from one into another in `fullscreen`

### ISSUE THREAD

**Issue by zmazanv** [hyprwm/Hyprland#2842]
### Hyprland Version

Hyprland, built from branch master at commit b08b72358ad549fd066e5be0fc3aa4c9df367607  (update v0.27.2).

### Bug or Regression?

Bug

### Description

I have the following binds configured:
```
bind = $mainMod + CONTROL, N, fullscreen, 0 # dwindle
bind = $mainMod + SHIFT, N, fullscreen, 1 # dwindle
bind = $mainMod + SHIFT, H, swapwindow, l
bind = $mainMod + SHIFT, J, swapwindow, d
bind = $mainMod + SHIFT, K, swapwindow, u
bind = $mainMod + SHIFT, L, swapwindow, r
```

## Behaviour
*I use the dwindle layout.*
*Although, as mentioned below, I use the `hyprland-nvidia` AUR build, this bug also exists in the mainline build from the Arch `Extra` repo, as I was able to reproduce it on that build as well.*

I generally swap my windows around using my keyboard using the binds shown, with occasional fullscreen toggling when needed. As mentioned in the title, I have a dual monitor set up. Hyprland allows for swapping windows between the monitors seemlessly as you would expect. However, if one of the monitors has a window in fullscreen mode, no matter if it has other windows in that workspace or not, and I swap into that monitor's workspace, Hyprland will crash.  This will attempt to swap the focused window with the fullscreen window on the other monitor.

## Expected Result
The window on Monitor y should swap places with the fullscreen window on Monitor x without any visual artifacts or changes to the window's properties, and the system should remain stable.

## Actual Result
It is clear that Hyprland is not secured for that use case as upon executing the `swapwindow` command, the previously fullscreen window that was swapped, loses its border and rounding, as well as is not proportioned properly. This is the sign that Hyprland will crash briefly. Some seconds later, Hyprland will completely crash.

I should mention that prior to the crash, when it is in this "limbo" state where you know that a crash is coming, Hyprland does not lock up nor freeze. You can still move everything around, except for the fullscreen window that was moved. Only that window is frozen or locked-up.

## Additional Information
- I am not sure if attempting to move things around makes the crash occur sooner.
- This bug occurs regardless of the direction of the swap, meaning it also happens when swapping from right to left if the conditions to cause the crash are met.
- It does not matter how many windows exist on either workspace, as even if both workspaces only have one existing window, as long as one is in either fullscreen mode (including `fullscreen, 1` which doesn't do anything really visually for the window as it is already at its maximum size, but still changes its "mode"/"behaviour") the bug will still cause the crash.

## System Information
- Linux Distribution:
    - Arch Linux
- Kernel:
    - 6.4.7-arch1-1
- Hyprland Build:
    - `hyprland-nvidia` from AUR: https://aur.archlinux.org/packages/hyprland-nvidia
    - `hyprland` from Arch `Extra` repo
- Graphics:
    - Nvidia GeForce RTX 3080 Ti
    - Nvidia DKMS driver (*version 535.86.05-2*) from Arch `Extra` repo

### How to reproduce

1. Configure Hyprland with binds to the relevant dispatchers (`fullscreen` and `swapwindow`). The following is what I use:
    ``` 
    bind = $mainMod + CONTROL, N, fullscreen, 0 # dwindle
    bind = $mainMod + SHIFT, N, fullscreen, 1 # dwindle
    bind = $mainMod + SHIFT, H, swapwindow, l
    bind = $mainMod + SHIFT, J, swapwindow, d
    bind = $mainMod + SHIFT, K, swapwindow, u
    bind = $mainMod + SHIFT, L, swapwindow, r
    ```
2. On a dual monitor setup, place a window into fullscreen mode on Monitor 1 (it does not matter if `fullscreen, 0` or `fullscreen, 1` are used as they both cause the behaviour). This window can, for example, be playing a video. For this example, Monitor 1 will be on the left.
3. Focus on Monitor 2 on the right, specifically the window closest to Monitor 1.
4. Execute the `swapwindow` command to the left using `$mainMod + SHIFT, H`. This attempts to swap the focused window on Monitor 2 with the fullscreen window on Monitor 1.

*This also happens if the direction is reversed with Monitor 1 on the right and swapping right from Monitor 1 on the left*

### Crash reports, logs, images, videos

I have attached the log file in `/tmp/hypr`, as well as the relevant crash report that was generated as a result of me intentionally triggering the crash as described.
[hyprlandCrashReport1425.txt](https://github.com/hyprwm/Hyprland/files/12207454/hyprlandCrashReport1425.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12207457/hyprland.log)

**Comment by onerc** [comment]
Few days ago I also encountered this bug on my system with AMD GPU as well. 

[hyprlandCrashReport13366.txt](https://github.com/hyprwm/Hyprland/files/13995098/hyprlandCrashReport13366.txt)
[hyprlandCrashReport72334.txt](https://github.com/hyprwm/Hyprland/files/13995100/hyprlandCrashReport72334.txt)

**Comment by zmazanv** [comment]
Just gave it another go and it will still crash in the same way. Nothing has changed since.

What you can do to get a similar effect is to use `movewindow` instead of `swapwindow`. I ended up preferring it actually. No crashes here. Sometimes when you have windows in fullscreen and try to move either those or normal windows between displays, weird stuff with focus being lost happens, but no crashing. You just need to reengage the focus with mouse or a bind. Since the switch, Hyprland has been perfectly stable for over half a year since I submitted the report.

Until this gets fixed or I get time to look into the issue myself, I'd recommend making the change mentioned.
