### ISSUE TITLE
[Query] What is the Hyprland equivalent of `Environment=DISPLAY=:0` ?

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/Hyprland#2844]
I am looking into documenting laptop stuff for Hyprland. For this case, i want the session to lock when the lid is closed.

This can be achieved in a few ways, but 2 of the common ways it can be done so is by either goofing around with ACPI events (uncomfortable for most ppl and not easily reproducible for me atleast) or via systemd services (easily reproducible and implement)

The implementation in question is https://geoff.greer.fm/2018/01/02/linux-laptop-locking/ . Where the author goes over locking the screen when `suspend` state is detected. The systemd unit in question is 

```
[Unit]
 Description=Lock the screen
+Before=sleep.target
 
 [Service]
 User=ggreer
 Environment=DISPLAY=:0
 ExecStart=/usr/local/bin/lock-screen
 
 [Install]
-WantedBy=suspend.target
+WantedBy=sleep.target
```

Here, the `Environment` parameter is of interest, from what I can see, this is an X11 thing. What is the Wayland (or precisely, Hyprland) equivalent of this?

**Comment by MahouShoujoMivutilde** [comment]
```

~ 
❯ echo $WAYLAND_DISPLAY
wayland-1

```

**Comment by WasteOfO2** [comment]
This is for laptop lid events. It is not an idle event, where systemd detects an `idle` state, in most distros, laptop lid closing is subjected to a `suspend` event with ACPI `button/lid` action.
