### ISSUE TITLE
mpv: Inactivated windows become transparent

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#2848]
### Hyprland Version

Hyprland, built from branch main at commit bf0d8ab4a3c44728cd1330ee32a8143ad1f5dcdd dirty (NixOS module: check system version for fonts). Tag: v0.27.2-61-gbf0d8ab4

### Bug or Regression?

Bug

### Description

When I launch mpv with the `windowrule = fullscreen, ^(mpv)$ ` rule with swallow on , inactive windows become invisible and window rules are not applied to it

### How to reproduce

`windowrule = fullscreen, ^(mpv)$`
`windowrule = workspace 1, ^(mpv)$`
`swallow_regex=^(foot)$`

open  mpv with these config

> **Note**
you need to be in workspace 1
### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/54718375/4c916990-b0af-430b-ad5e-22b548b50d11

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12208924/hyprland.log)

**Comment by shadowelite-sec** [comment]
still facing this issue @vaxerski

**Comment by vaxerski** [comment]
lies and deceit

**Comment by shadowelite-sec** [comment]
> lies and deceit



> lies and deceit

What ?
