### ISSUE TITLE
Cursor becoms invisible when hovering on any GUI programme.

### ISSUE THREAD

**Issue by shaolingit** [hyprwm/Hyprland#285]
When my mouse is moved to a window where a GUI programme is displayed, the cursor becomes invisible and stay invisible until i quit the session. programmes tested are firefox, wofi, files, gedit and many others. Thank you in advance.

**Comment by taylor85345** [comment]
Might [this](https://github.com/hyprwm/Hyprland/wiki/FAQ#me-cursor-no-render) be relevant?

**Comment by taylor85345** [comment]
Disregard, just saw your duplicate issue

**Comment by vaxerski** [comment]
dupe
