### ISSUE TITLE
Windows start lagging after resizing in new versions of Hyprland

### ISSUE THREAD

**Issue by HiWhatName** [hyprwm/Hyprland#2850]
### Hyprland Version

v0.27.2

### Bug or Regression?

Regression

### Description

I'm experiencing weird behavior while resizing some windows. As demonstrated in the provided video, Hyprland starts to lag out and causes mouse movements to appear delayed or projected into the future. Surprisingly, this occurs not only during periods of high system load but seems to be caused by the specific applications in use.

GPU: Amd RX 6700 XT ( with: **open-source rcom & mesa** drivers)
Distro: Arch Linux - Up to date [2023-07-30]
Libinput: v1.23.0-1

### How to reproduce

Since I'm currently using [ArchLinux](https://archlinux.org/), you'll have to locate the corresponding packages for your specific distribution.

1. Use an AMD GPU with the open-source _rocm_ and _mesa_ drivers.
2. install **hyprland** over the official **stable** packages `hyprland xdg-desktop-portal-hyprland`  
3. Resize *2 or more* (resource intensive) windows, that are next to each other.

=> Hyprland lags, even with the GPU/CPU being under 100% utilization

### Crash reports, logs, images, videos

Video demonstrating it: https://imgur.com/a/SKCcR08

Other info:
- **Libinput**: v1.23.0-1
- **Hyprland version**: v0.27.2 ( @ commit b08b72358ad549fd066e5be0fc3aa4c9df367607)
- **xdg-desktop-portal-hyprland version:** 0.4.0-1
- **Drivers**; _Mesa_: v23.1.4-2 | _Rocm-core:_ v5.6.0-1

**Comment by HiWhatName** [comment]
Version without the bit-rate being destroyed: [here]( https://youtu.be/SLNR7AoNSio)

**Comment by vaxerski** [comment]
cant repro, do a `git bisect`

besides, test with other apps than ff too, as firefox is known to be slow with its resizes

**Comment by HiWhatName** [comment]
As you can't repro it, i'll just close it
