### ISSUE TITLE
Hyprland shows default background behind windows while resizing instead of set background

### ISSUE THREAD

**Issue by russelltg** [hyprwm/Hyprland#2853]
### Hyprland Version

77818e34578769c25bb978553f076d25704914b6

### Bug or Regression?

Bug

### Description

It seems surprising that when you're resizing a window, before the application gets a chance to resize the content the compositor renders the default background instead of the one I've set with hyprpaper. 

If you pause this video a few times you should be able to see large sections of the default wallpaper

https://github.com/hyprwm/Hyprland/assets/7105082/bcf8b574-c2a6-4aba-b73a-b93ab0a18bc7

### How to reproduce

Set a background with hyprland, and resize a window that doesn't resize instantly. Firefox seems to reproduce the issue pretty well

**Comment by MightyPlaza** [comment]
shouldn't this have been fixed in (https://github.com/hyprwm/Hyprland/issues/1152 / https://github.com/hyprwm/Hyprland/commit/382af06406e39640dac36e4e075c2c70063cb16c)

**Comment by vaxerski** [comment]
it's not fixed, but it's a firefox bug
