### ISSUE TITLE
Contain mouse in active monitor

### ISSUE THREAD

**Issue by Cloudef** [hyprwm/Hyprland#2854]
### Description

It would be nice to have option to disable monitor switching by moving mouse. That is contain mouse to the active monitor.

**Comment by MightyPlaza** [comment]
probably hackable by setting the offset larger than the monitor

**Comment by vaxerski** [comment]
indeed, adding +1 px to the offset will make it unnoticeable yet make the mouse unable to travel between the two

**Comment by Cloudef** [comment]
What's the offset in this context?

**Comment by vaxerski** [comment]
monitor position, aka offset

**Comment by Cloudef** [comment]
I see, I'll try that. Would be nice to have it as an option anyway so you don't have to hardcode monitors in your config however.

**Comment by MightyPlaza** [comment]
use hyprctl to move the monitor 1px to the side and back
