### ISSUE TITLE
Re-render after changing cursor zoom factor

### ISSUE THREAD

**Issue by M1cha** [hyprwm/Hyprland#2858]
### Description

After changing the zoom factor I have to move the mouse for the zoom to take effect. I have bindings for increasing/decreasing the factor by 0.1 and the issue with the current behavior is that I have no direct feedback if I have reached a usable factor yet. I have to constantly switch back and forth between mouse and keyboard.

**Comment by M1cha** [comment]
@vaxerski I cherry-picked that on v0.27.2 and it doesn't seem to work. Am I right in that `loadConfigLoadVars` is only called when (hotre)loading the config? I'm using the Hyprland IPC to modify the keyword `misc:cursor_zoom_factor`.

**Comment by M1cha** [comment]
Setting `general:border_size` is a workaround that removes the issue. So I guess all that's needed is to do this after changing the zoom factor: https://github.com/hyprwm/Hyprland/blob/da0c74cdf038692377eb77fbfc57067c633467c0/src/debug/HyprCtl.cpp#L744

**Comment by vaxerski** [comment]
fixed 51cda87fe47efec25265b3b9f6bebf9a0882aa08

**Comment by M1cha** [comment]
thanks a lot :+1:
