### ISSUE TITLE
monitor scaling breaks focus on multi-screen setups 

### ISSUE THREAD

**Issue by fdev31** [hyprwm/Hyprland#2860]
### Hyprland Version

Hyprland, built from branch main at commit f49af187bc0755f9b5be9376bfd52c0cf12c1e11 dirty (Xdg config home support (2047)). Tag: v0.26.0-96-gf49af187

### Bug or Regression?

Bug

### Description

Using such configuration:
```
monitor=,preferred,auto,1
monitor=eDP-1,preferred,auto,1.2
```
If I place a monitor on the *right*, or *bottom* of `eDP-1` the mouse or most keyboard shortcuts can't reach it.

Monitors sizes & positions look fine.

If I change `1.2` to `1` the problem is gone.

### How to reproduce

- use scaling for every monitor (eg: `monitor=,preferred,auto,1.1`)
- try to change focus via mouse or keyboard

The mouse is stuck on the current screen, only way to switch is via keyboard shortcuts such as `focusmonitor` (not `movefocus` - which is also broken)

EDIT: if I insist a lot trying to switch with the mouse, it may eventually work after few seconds trying...

**Comment by romanstingler** [comment]
Please upgrade your version to the latest version and check again (install git version or build from source) https://wiki.hyprland.org/Getting-Started/Installation/.

**Comment by fdev31** [comment]
I don't see any difference / improvement.

**Comment by vaxerski** [comment]
set proper absolute positions (not auto) and try again. IIRC it's an issue with auto

**Comment by fdev31** [comment]
I am using dynamic layouts depending on which other screen I plug.
Even if I set positions later with `wlr-randr` the issue is the same.
In short I can't use static positions for my monitors.

For testing purposes I did check the behavior with a fixed position, and the behavior is exactly the same.

**Comment by romanstingler** [comment]
what is the output of 
`hyprctl monitors`?

**Comment by fdev31** [comment]
For instance:
```
Monitor eDP-1 (ID 0):
	1920x1080@120.001999 at 0x0
	description: BOE 0x0A81 (eDP-1)
	make: BOE
	model: 0x0A81
	serial: 
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 50 0 0
	scale: 1.20
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor HDMI-A-1 (ID 1):
	1920x1080@60.000000 at 0x1080
	description: BNQ BenQ PJ 0x01010101 (HDMI-A-1)
	make: BNQ
	model: BenQ PJ
	serial: 0x01010101
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 50 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0


```

**Comment by romanstingler** [comment]
what happens if you for testing purposes try 
```
monitor=eDP-1,preferred,auto,1.2
monitor=HDMI-A-1,preferred,0x900,1
```

**Comment by fdev31** [comment]
You  nailed it, the scaling factor seems to be missing somewhere and with this it behaves as expected.

**Comment by romanstingler** [comment]
yeah I was just guessing because I have 4k and 1.5 scaling on one screen and also have auto on the other (dynamic screens) and the second one was positioned at 2560x0 (I have them horizontally) 

@vaxerski maybe this helps you to determine where the error is rooted.

**Comment by vaxerski** [comment]
is this stilla thing?

**Comment by fdev31** [comment]
> is this stilla thing?

I'm pretty sure scaling works as expected in multi monitor now. I recall performing some tests with success.

**Comment by romanstingler** [comment]
@vaxerski yes it works, I use multi monitors one scaled every day, no issues
