### ISSUE TITLE
screensharing: region selection blackscreen (intel)

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/Hyprland#2862]
### Hyprland Version

Hyprland, built from branch main at commit 08651736ada39f62b246c44c1d8a81e2787f23d5 dirty (keybinds: add toggle to dpms). Tag: v0.27.2-62-g08651736

### Bug or Regression?

Bug

### Description

I've been monitoring exactly this issue for quiet a long time, but since it does not bother me too much, AND, recently it worked after https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/af539f4e4d54d83cdab5303c5812877f2e8c87b6 (which seems like an accident). I left checking after that commit (i upgrade both, hyprland and xdph every time there is new commit), and now here we come again.

The most strangest thing is that, region is connected through pipewire ONLY if starting point of selection is 0x0 (no matter how monitor is defined in conf, i mean actual selection top-left corner), any other way it is black.

logs attached, but as i can see, wireplumber is silent, PW doing correctly suspend -> running, xdph reporting fps while screen is black. run with more verbose level?

### How to reproduce

- [WebRTC test page](https://mozilla.github.io/webrtc-landing/gum_test.html)
- Screen Capture
- Region (from qt-capture)

Expected: region capture
Actual: black region

### Crash reports, logs, images, videos

from start stream till close
[xdph.log](https://github.com/hyprwm/Hyprland/files/12223839/xdph.log)
[wireplumber.log](https://github.com/hyprwm/Hyprland/files/12223840/wireplumber.log)
[pipewire.log](https://github.com/hyprwm/Hyprland/files/12223841/pipewire.log)
first boot lines:
[hypr.log](https://github.com/hyprwm/Hyprland/files/12223891/hypr.log)

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/78

**Comment by vaxerski** [comment]
generally this has been fixed in hyprland, so even the older xdph should be able to do it now. see 32f4059b37cde3def606127d843f143380bc2048
