### ISSUE TITLE
fullscreen breaks cursor position in games with different resolution

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#2866]
### Hyprland Version

0.27.2.r62.08651736

### Bug or Regression?

Bug

### Description

Many (all?) games have misaligned cursor positions if you they enter fullscreen mode (either by forcing that via hyprland or via games just straight up doing that themselves) if their set resolution is smaller than the screen resolution. 

I am doing this in the first place because my GPU isn't very recent and only runs some games on lower resolutions. I can generally only change resolutions via gamescope, because this cursor misalignment makes games unplayable. The only problem is that I had man problems with gamescope, making it almost unusable in many cases.

If you manually force the fullscreen mode off, the game still has a misaligned cursor. If the games themselves turn off fullscreen, the issue goes away.

### How to reproduce

1. change the resolution of the game window to be non-native
2. Set it to fullscreen
3. misaligned cursor :(

Just to clarify - misaligned cursor:
```
x (I move my mouse here and click)


                                        x (the game registers the cursor and it's clicks here)
```

### Crash reports, logs, images, videos

https://chonkyrabbit.eu/files/_share/hyprland.log

**Comment by vaxerski** [comment]
Never seen this. Any game examples?

**Comment by UltraBlackLinux** [comment]
I just did some testing I had on a suspicion, which I was able to confirm. It's all coming full circle.

This is my display config:
```
Monitors: 2
 0: +HDMI-A-1 1680/470x1050/300+0+0  HDMI-A-1
 1: +DVI-D-1 1920/490x1200/310+1680+0  DVI-D-1
```
I first ran into this issue with source games, but now also with DeadPoly. I wanted to set them to fullscreen, but the game would only detect my left (smaller) screen instead of my right (bigger, main) screen, as if the game was only informed about the smaller screen.

The game would have borders around the edges, and after forcing fullscreen off and on again, the black bars would be gone but the cursor would now be no longer aligned to where the game suspected it to be.

I have just confirmed, this only happens on proton.

**Comment by KyrillGobber** [comment]
I had the same problems with proton games actually, and it definitelly was the display config. Just put the main display back to 0x0 and it's normal again, but if you move it, the cursor will be placed wrong.

**Comment by UltraBlackLinux** [comment]
I'll just stuff this here as well: I just got a new GPU, and by default, hyprland is no longer detecting my screen placement correctly.
I have set it up via the config file, but now something weird is happening: Whenver a fullscreen game (proton issue again?) grabs the cursor and ungrabs it, the cursor is placed on my other screen.
In gmod for example: Opening the spawn menu places my cursor on the screen that does not contain the game, but at the same cursor position. Very annoying issue...

**Comment by vaxerski** [comment]
check on -git please

**Comment by UltraBlackLinux** [comment]
if you are replying to the comment which I moved into a separate issue, then I can say that I'm already on -git

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by UltraBlackLinux** [comment]
I don't think it is. I haven't run into this issue for quite a while :)
