### ISSUE TITLE
X11 GTK2 apps ignore hidpi scale

### ISSUE THREAD

**Issue by M1cha** [hyprwm/Hyprland#2867]
### Hyprland Version

Hyprland, built from branch HEAD at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (upgpkg: 0.27.2-1). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

I'm using patched wlroots and xwayland and would expect gimp to scale even though gtk2 doesn't support it.

### How to reproduce

- start gimp

**Comment by vaxerski** [comment]
> I'm using patched wlroots

not officially supported

**Comment by M1cha** [comment]
@vaxerski Can you add that information to the documentation? https://wiki.hyprland.org/Configuring/XWayland/ and the fact that all of the patches are part of this repo clearly make it sound like it is officially supported.

**Comment by vaxerski** [comment]
patches are deprecated anyways, but I'll let fuf know.

**Comment by M1cha** [comment]
Mh I can't see any sign of deprecation within MR733. What's the replacement? New toolkits supporting hidpi is not the solution since there's still lots of older apps which will never be updated.

**Comment by vaxerski** [comment]
if GTK2 does not support scaling at all I don't know what you want me to do. iirc, gtk uses the `GDK_SCALE` envvar

**Comment by M1cha** [comment]
Well I don't want you to do anything. I was just very confused by you saying that the hidpi patches are deprecated since - if I understand them correctly - they're made exactly to fix this issue.

**Comment by vaxerski** [comment]
they are deprecated because `xwayland:force_zero_scaling` does exactly the same
