### ISSUE TITLE
Chromium & chromium-based browsers are freeze and cannot be used

### ISSUE THREAD

**Issue by jadnw** [hyprwm/Hyprland#287]
I cannot use any chromium-based browsers on Hyprland. They appeared outside of the window border and cannot be clicked. They are totally freeze and lag behind my click. You can see my [Hyprland configuration](https://github.com/jadnw/jetdots/blob/main/config/hypr). Is this a bug or my config breaks the browsers?

```bash
chromium --ozone-platform=wayland
```

**Comment by jadnw** [comment]
I am currently using Firefox Developer Edition. It can work normally. However, I hover setting context menu and no background color changes.

**Comment by taylor85345** [comment]
There are some known issues with chromium running in a native wayland session in Hyprland. I haven't heard of a case as severe as this, but in any case you will likely want to switch to x11/xwayland for the time being.

**Comment by jadnw** [comment]
> There are some known issues with chromium running in a native wayland session in Hyprland. I haven't heard of a case as severe as this, but in any case you will likely want to switch to x11/xwayland for the time being.
Should I closed this issue and wait for everything is completely fixed? I add Hyprland as one of my tiling wayland compositors in my public dotfiles. Hyprland needs more time to be perfectly stable.

**Comment by taylor85345** [comment]
In the interest of clarity, I was referring to changing your launch arguments for chromium to use the x11 backend and having chromium run under xwayland in Hyprland

`chromium --ozone-platform=x11`

Not confident this is right. Not at my PC to check the flag.

**Comment by jadnw** [comment]
It works. I have tried it before. But everything I need is running Chromium as a Wayland native application. Maybe I will came back with Hyprland later.

**Comment by nrdxp** [comment]
Just a fyi, hitting this as well:
```
❯ chromium
[0414/193232.537791:ERROR:process_memory_range.cc(75)] read out of range
```
Trying to switch from [Vivarium](https://github.com/inclement/vivarium) where chromium works with Wayland without issue, so I assume it is hyprland specific.

**Comment by vaxerski** [comment]
xdph-git has a fix already
