### ISSUE TITLE
Ignore exclusive zones in special workspace if parent workspace hasfullscreen

### ISSUE THREAD

**Issue by donovanglover** [hyprwm/Hyprland#2872]
### Description

I like using the special workspace to show a transparent terminal over a fullscreen window (such as a video) so I can watch it while working on another activity.

It would be nice if Hyprland ignored exclusive zones for special workspaces when the parent hasfullscreen. Right now there's blank space where any bars would be.

**Comment by MightyPlaza** [comment]
seems to show the bar now
