### ISSUE TITLE
Cursor not rendering when using SDDM

### ISSUE THREAD

**Issue by Luh-code** [hyprwm/Hyprland#2875]
### Hyprland Version

Hyprland, built from branch master at commit b08b72358ad549fd066e5be0fc3aa4c9df367607  (update v0.27.2). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

When I try to start Hyprland from SDDM, the cursor exists, but is invisible.
When starting it from TTY it works as intended.
I have WLR_NO_HARDWARE_CURSORS set to true (1).
Weirdly enough the cursor exists but on TTY2, where the is nothing but a black screen, whilst Hyprland is running on TTY1.

My system: AMD Ryzen 2600, MSI RTX 3080 LHR 10GB, 16 GB 3200MHz DDR4 RAM.
Because I use an NVidia GPU, I use the patched version for NVidia (ik it isn't officially supported, but I thought asking here couldn't hurt).

I have SDDM set to run on x11 w. root, but I tried Wayland (without root ofc), and it didn't help.

Heres a bit more info:
```
$ systemctl status sddm
● sddm.service - Simple Desktop Display Manager
     Loaded: loaded (/usr/lib/systemd/system/sddm.service; enabled; preset: disabled)
     Active: active (running) since Wed 2023-08-02 19:22:09 CEST; 53min ago
       Docs: man:sddm(1)
             man:sddm.conf(5)
   Main PID: 608 (sddm)
      Tasks: 4 (limit: 18963)
     Memory: 146.0M
        CPU: 929ms
     CGroup: /system.slice/sddm.service
             ├─608 /usr/bin/sddm
             └─615 /usr/lib/Xorg -nolisten tcp -background none -seat seat0 vt2 -auth /run/sddm/xauth_xRtcEI -noreset -displayfd 16

Aug 02 19:22:17 archlinux sddm-helper[696]: gkr-pam: unable to locate daemon control file
Aug 02 19:22:17 archlinux sddm-helper[696]: gkr-pam: stashed password to try later in open session
Aug 02 19:22:17 archlinux sddm-helper[696]: [PAM] returning.
Aug 02 19:22:17 archlinux sddm[608]: Authentication for user  "luh"  successful
Aug 02 19:22:17 archlinux sddm-helper[696]: pam_unix(sddm:session): session opened for user luh(uid=1000) by luh(uid=0)
Aug 02 19:22:17 archlinux sddm[608]: Auth: sddm-helper exited successfully
Aug 02 19:22:17 archlinux sddm[608]: Greeter stopped. SDDM::Auth::HELPER_SUCCESS
Aug 02 19:22:18 archlinux sddm-helper[696]: gkr-pam: unlocked login keyring
Aug 02 19:22:18 archlinux sddm-helper[696]: Starting Wayland user session: "/usr/share/sddm/scripts/wayland-session" "Hyprland"
Aug 02 19:22:18 archlinux sddm[608]: Session started true
```

### How to reproduce

I don't know for certain how to reproduce this but this is my best shot:
- Set up SDDM to run on x11 and to start Hyprland after login.
- Make sure WLR_NO_HARDWARE_CURSORS is true

### Crash reports, logs, images, videos

I have no idea why but Github refuses to let me upload the log, so here's a gist: https://gist.github.com/Luh-code/2eee59712d0060ede9a37d86912fdc60

**Comment by Luh-code** [comment]
sorry apparently misclicked, wasnt supposed to be closed

**Comment by vaxerski** [comment]
does it happen when launching from a tty?

**Comment by romanstingler** [comment]
@vaxerski he wrote " When starting it from TTY it works as intended."
so it seems to be an issue in combinationwith SDDM

**Comment by Luh-code** [comment]
yeah it's just SDDM

**Comment by Luh-code** [comment]
I am not sure of the relevancy, but GDM and LightDM both didn't work at all in combination with Hyprland. See this issue for context: https://github.com/hyprwm/Hyprland/issues/2824

**Comment by vaxerski** [comment]
then it's not an issue with hyprland. login managers are not supported. It's their issue.

**Comment by romanstingler** [comment]
@Luh-code just create issues on all the launchers git projects so they can implement it if they want. 
If nobody creates an issue there then nothing will change
