### ISSUE TITLE
The title attribute of the windowrulev2 is not working properly

### ISSUE THREAD

**Issue by hikkidev** [hyprwm/Hyprland#2876]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2

### Bug or Regression?

Bug

### Description

When attempting to configure a file save dialog in Firefox using `windowrulev2` with `title` attribute, any rule is not applied.

![image](https://github.com/hyprwm/Hyprland/assets/52655010/ab999f6a-2d35-44c1-a73f-351d0110f073)
[Example of the dialog]
### How to reproduce

hyprland.conf
```
windowrulev2 = nofullscreenrequest,class:^(firefox.*),title:^Opening.*
windowrulev2 = float,class:^(firefox.*),title:^Opening.*
windowrulev2 = size 500 190,class:^(firefox.*),title:^Opening.*
```
Try to download any file and observe that no one rule will be applied.

---

hyprland.conf
```
windowrulev2 = nofullscreenrequest,class:^(firefox.*)
windowrulev2 = float,class:^(firefox.*)
windowrulev2 = size 500 190,class:^(firefox.*)
```
Try to download any file and observe that all rules will be applied.

### Crash reports, logs, images, videos

hyprland.log
```
[LOG] Searching for matching rules for firefoxdeveloperedition (title: Opening file_Linux.rar)
[LOG] Window rule nofullscreenrequest -> class:^(firefox.*),title:^Opening.* matched 559fab03ef30 [Opening file_Linux.rar]
[LOG] Window rule float -> class:^(firefox.*),title:^Opening.* matched 559fab03ef30 [Opening file_Linux.rar]
[LOG] Window rule size 500 190 -> class:^(firefox.*),title:^Opening.* matched 559fab03ef30 [Opening file_Linux.rar]
```
hyprctl clients
```
Window 559fab0d67c0 -> Opening file_Linux.rar:
	mapped: 1
	hidden: 0
	at: 1470,627
	size: 499,186
	workspace: 1 (1)
	floating: 1
	monitor: 0
	class: firefoxdeveloperedition
	title: Opening file_Linux.rar
	initialClass: firefoxdeveloperedition
	initialTitle: 
	pid: 6721
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

---

```
[LOG] Searching for matching rules for firefoxdeveloperedition (title: Opening file_Linux.rar)
[LOG] Window rule nofullscreenrequest -> class:^(firefox.*) matched 559fab27bbb0 [Opening file_Linux.rar]
[LOG] Window rule float -> class:^(firefox.*) matched 559fab27bbb0 [Opening file_Linux.rar]
[LOG] Window rule size 500 190 -> class:^(firefox.*) matched 559fab27bbb0 [Opening file_Linux.rar]
```

hyprctl clients
```
Window 559fab114dc0 -> Opening file_Linux.rar:
	mapped: 1
	hidden: 0
	at: 1470,627
	size: 500,190
	workspace: 1 (1)
	floating: 1
	monitor: 0
	class: firefoxdeveloperedition
	title: Opening file_Linux.rar
	initialClass: firefoxdeveloperedition
	initialTitle: 
	pid: 6721
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

**Comment by hikkidev** [comment]
Sometimes a file save dialog opens at fullscreen, idk why.

**Comment by MightyPlaza** [comment]
your lucky day
new version came out so you don't even need to compile hyprland
use the new rule
```
windowrulev2=nomaximizerequest, class:^(firefoxdeveloperedition)$
```
which should fix all the maximizing nonsense
This disables maximizing but allows fullscreen request, which is the best that can be done on hyprland's side

**Comment by zenzoa** [comment]
I'm running into a similar issue (Arch Linux, Hyprland 0.28, Firefox 116.0.2), where the first time I open a video as a PiP window, my rules are followed and I get a small pinned floating window. But the second and all subsequent times (until I restart Firefox), it opens as a normal tiled window. Adding the nomaximizerequest rule hasn't affected this behavior. Could it be coming from the same/similar Firefox bug?

Here are my rules:
`windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = pin, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = move 67% 72%, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = size 33% 28%, class:^(firefox)$, title:^(Picture-in-Picture)$`

**Comment by MightyPlaza** [comment]
completely unrelated but see https://github.com/hyprwm/Hyprland/issues/2942 and https://github.com/hyprwm/Hyprland/issues/2943

**Comment by zenzoa** [comment]
Ah that actually covers my issue at least more precisely at least - Firefox changing the window title after it opens, resulting the the "float" windowrule not getting applied.

**Comment by MightyPlaza** [comment]
@vaxerski
initial title is empty, so non dynamic rules are not applied
no issue here

**Comment by vaxerski** [comment]
fair point, non-issue. Take it to firefox or write a script to listen to socket2's title event
