### ISSUE TITLE
Screenshots have a blank/transparent margin

### ISSUE THREAD

**Issue by outragedline** [hyprwm/Hyprland#2878]
### Hyprland Version

 0.27.2-1

### Bug or Regression?

Bug

### Description

I use an 1600x900 resolution on hyprland, but when i try to get an output screenshot its 1920x1080 with blank margins
<br>
I was away from my computer for some months, it didnt used to happen before
<br>

### How to reproduce

Set the screen resolution to 1600x900 and try to get a screenshot with grim or grimblast

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/contrib/assets/81770118/9b6aa7c0-eb33-4942-b408-00142455aca4)
![image](https://github.com/hyprwm/contrib/assets/81770118/5d5b92f4-9f63-4813-bc59-7385d203736c)

**Comment by MightyPlaza** [comment]
used 1600x900 with scaling 0.833 and 1, and can't repro
you may want to provide additional info like ```hyprctl monitors``` output (maybe hardware specs as well)
(and also test in v0.28.0 just to be sure)

**Comment by outragedline** [comment]
hi, i was away from my computer again for all this time

it seems like hyprland dont even support 1600x900 anymore so i will be closing this issue, thanks

**Comment by MightyPlaza** [comment]
not sure what you mean by doesn't support 1600x900, but my guess is you were using 1600x900 on a 1920x1080 display.
I don't know you would want to do that but if you wanted to https://github.com/hyprwm/Hyprland/issues/3143 would probably work
If you want things to look bigger you should set monitor scaling in your config
