### ISSUE TITLE
ibus doesn't work properly under hyprland

### ISSUE THREAD

**Issue by sunraysun** [hyprwm/Hyprland#288]
I installed ibus and ibus-libpinyin for input Chinese and it works perfectly under gnome wayland. But under hyprland I'm having trouble.
The following are the steps to reproduce the problem
1, use ibus-daemon -x -d to start ibus
2, Open any application or terminal, such as geany
3, press the Shift key to switch to the Chinese input mode
4. Press any letter, the candidate word panel appears behind the editor window then disappears immediately, no text is inserted into the editor.
Below is the log file of hyprland
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9026831/hyprland.log)
Below is my hyprland.conf
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/9026847/hyprland.conf.txt)

**Comment by vaxerski** [comment]
```
windowrule=nofocus,ibus-ui
```

**Comment by sunraysun** [comment]
I add `windowrule=nofocus,ibus-ui` in hyprland.conf , but it still not work, even after restart.

**Comment by vaxerski** [comment]
woops, wrong regex. `^(Ibus-ui-gtk3)$`

**Comment by sunraysun** [comment]
@vaxerski  Thank you very much. Now IBus can be used in many applications, except for various terminals, such as alacritty, Kitty, foot ... 
I'm still studying how to make it work.
I have set the following environment variables in `.pam_environment`, `/etc/environment`,`.profile`

`
GTK_IM_MODULE DEFAULT=ibus
QT_IM_MODULE DEFAULT=ibus
XMODIFIERS DEFAULT=@im=ibus
INPUT_METHOD DEFAULT=ibus
SDL_IM_MODULE DEFAULT=ibus`

 Do you have any suggestions?

**Comment by vaxerski** [comment]
some apps do not accept IME input under wayland through XWayland. Not much you can do afaik. You'll have to wait for Hyprland to support the wayland IME protocols natively, that *might* fix it

**Comment by muttnooob** [comment]
Hi, @sunraysun new to linux, and know just enough to get by to set up my system on hyprland, browsers, waybar, etc.  

Are you able to walk through how to get the input methods working on Hyprland?  I don't type chinese pinyin often, but when I do, it's the wife that needs me to research something or reply to her --- so  happy wife, happy life.

are you able to walk me through how to get this working?

thank you much in advance.

**Comment by daniel-hernandez-sony** [comment]
@suraysun 

I am trying to get to the same stage where you are. I have managed to get `ibus` to work but I cannot see the candidate suggestions. Would you be so kind so as to tell me what have you done to fix that in some applications?

I have:
`exec-once = ibus-daemon -x d`
And:
```
windowrule = nofocus, ^(Ibus-ui-gtk3)$
windowrule = nofocus, ^(Ibus-ui-gtk5)$
windowrule = nofocus, ^(Ibus-ui-gtk4)$
```

But still I cannot see the suggestions on any app (I've tried firefox, telegram, spotify and wezterm terminal)

**Comment by vaxerski** [comment]
use fcitx5. IBus works poorly under wl

**Comment by TanawatJukmongkol** [comment]
Update: ibus v1.5.32+ now have native wayland support 

Follow the docs here: https://github.com/ibus/ibus/wiki/WaylandDesktop
