### ISSUE TITLE
[force_zero_scaling] Context menus get weirdly scaled mouse position and damage until refocused

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2880]
### Hyprland Version

Hyprland, built from branch main at commit 51cda87fe47efec25265b3b9f6bebf9a0882aa08 dirty (hyprctl: rerender on cursor_zoom_factor dynamic calls). Tag: v0.27.2-64-g51cda87f

### Bug or Regression?

Bug

### Description

Most context menus of XWayland apps will have wrong mouse position and damage until they get refocused (f.e by entering and exiting a submenu).

### How to reproduce

- Open XWayland app (such as Android Studio)
- Open any context menu (such as top menu in Android Studio)
- Move the mouse down
- Observe how, the further down it gets, the more wrong the position is, and the worse the damage tracking is

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/44881120/3544cd14-8d9d-405a-85f3-09df817e25e3

**Comment by wowblvck** [comment]
I have a similar problem in WebStorm.

https://github.com/hyprwm/Hyprland/assets/73607681/69714da1-7c9a-4803-b31c-7790d4788cae

**Comment by TheSunCat** [comment]
This might be an issue specific to Java Swing applications, since both WebStorm and Android Studio use it. I remember encountering this in other software, but it might have been Swing as well.

**Comment by TheSunCat** [comment]
This appears fixed since the new submenu rewrite! I cannot repro in Android Studio or JetBrains Rider.
