### ISSUE TITLE
Error setting value for field <decoration: blur new optimisation>.

### ISSUE THREAD

**Issue by SumitKhatri712** [hyprwm/Hyprland#2881]
### Hyprland Version

Hyprland, built from branch main at commit da46e01b9710fdb1d8b89d577677321101f9ed96 dirty (config: update default config for new blur changes). Tag: v0.27.2-67-gda46e01b

### Bug or Regression?

Bug

### Description

After the latest update, I keep getting this error at top saying
```
Config error at line 50 (~/.config/hypr/hyprland.conf): Error setting value <on> for field <decoration:blur_new_optimisation> : No such field.
Hyprland may not work correctly
```
![1691078183_grim](https://github.com/hyprwm/Hyprland/assets/59339401/a2204c90-f947-4669-8454-78bca5b2a512)

And commenting this line just change the error to line 49 `blur_passes = 1`. and the error only goes away after all blur settings are commented out.

### How to reproduce

Update to the latest build.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12252792/hyprland.log)

No crash report

**Comment by vaxerski** [comment]
reading patch notes would help. For breaking changes on -git, join the discord server.

https://github.com/hyprwm/Hyprland/releases/tag/v0.28.0
