### ISSUE TITLE
Invalid ELF Header?

### ISSUE THREAD

**Issue by frkli1965** [hyprwm/Hyprland#2887]
### Hyprland Version

v0.28.0-3-g2e6693fb

### Bug or Regression?

Bug

### Description

Hi,

As of today's commits (x3) Hyprland will not start (on my system anyway) with the following error message:-

Hyprland: error while loading shared libraries <path_to>/libwlroots.so.12032: invalid ELF header.

Not sure what that's all about tbh so was hoping someone with greater skillz could shed  more light on the matter.

Please note that the Hyprland version given with this bug report is prior to today's updates as I had to rollback to yesterday's build in order for Hyprland to work.

### How to reproduce

Please see description...

**Comment by vaxerski** [comment]
you seem to be using a manual build from what I understand. How do you install hyprland?

Try removing the .so and reinstalling

**Comment by frkli1965** [comment]
> you seem to be using a manual build from what I understand. How do you install hyprland?
> 
> Try removing the .so and reinstalling

Evening Vaxerski,

Around a week ago I switched from using Meson to the 'cmake' method as  prescribed in the Wiki which does indeed involve a manual install of the Hyprland binary plus the app. desktop file i.e.

"sudo cp ./build/Hyprland /usr/bin && sudo cp ./example/hyprland.desktop /usr/share/wayland-sessions"

I'll revert back to the Meson technique and see whether the problem manages to resolve itself. Here's hoping... :-)

**Comment by frkli1965** [comment]
OK, my bad but a valuable lesson nevertheless as it turns out... :-)

It's just dawned on me that I did a Sway rebuild (before rebooting) after the Hyprland one which also updates wlroot's symbolic link in the process as that's the prescribed method when building Sway.

The reason I've been getting away with both on the same machine for so long without mishap is that the Meson method produces a static Hyprland binary which I've only just come to realise as it's exactly the size of 'wlroots.so.12032' bigger than the binary produced by the 'cmake' method.

Oops, silly me!

Anyway, worth noting that one can safely run both Hyprland and Sway on the same PC so long as Hyprland is built using Meson rather than 'cmake'.

Sorry to have troubled you btw, much appreciated as always and keep up the great work as I very much enjoy using Hyprland as my daily driver these days with Sway only being fired up in emergencies like today.

All the best...

**Comment by frkli1965** [comment]
Closed due to me being an idiot... LOL !
