### ISSUE TITLE
More than one (static) color possible for windowrule bordercolor?

### ISSUE THREAD

**Issue by revuwa** [hyprwm/Hyprland#2888]
### Description

Don't know if this could be related to https://github.com/hyprwm/Hyprland/issues/1515

I like moving border colors. The specific part of my configuration is:

```
general {
[...]
col.active_border = rgba(33CCFFEE) rgba(00FF99EE) 45deg
col.inactive_border = rgba(44475AAA)
}
animations {
[...]
animation = borderangle, 1, 64, linear, loop
}
windowrulev2 = bordercolor rgb(BD93F9),xwayland:1
```
I can't find a way to set more than one color for active border with windowrulev2, (last line). 
If this is possible, I would be happy for any hints.

It would be cool if I could set something like:
```
windowrulev2 = bordercolor rgba(33CCFFEE) rgba(BD93F9EE) 45deg,xwayland:1
```
to get color rotating borders with specific colors for specific windows over windowrules.

What do you think?

**Comment by vaxerski** [comment]
this is an exact dupe of the issue you linked.

**Comment by revuwa** [comment]
> this is an exact dupe of the issue you linked.

Thanks for clearing this up. Seems that my language skills aren't good enough to get this into the right context 🤷
