### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by root2185** [hyprwm/Hyprland#2890]
### Hyprland Version

Cannot run the command, `world/hyprland 0.27.0-1`

### Bug or Regression?

Bug

### Description

The screen is completely black, I can see the pointer initially.
Since it's a PinePhone it has touchscreen so pointer normally it

If I try to launch a terminal with a physical keyboard nothing happens.
Shortcut to exit works.

### How to reproduce

Just launch it.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12267504/hyprland.log)

**Comment by MightyPlaza** [comment]
try using foot terminal since it doesn't require require opengl like kitty or alacritty

**Comment by root2185** [comment]
Looks like no apps is working, I set it also to launch `wvkbd-mobile-intl` at start.

```
OpenGL vendor string: Mesa
OpenGL renderer string: Mali400
OpenGL version string: 2.1 Mesa 23.1.4
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 23.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by MightyPlaza** [comment]
your ```OpenGL ES 2.0``` is pretty old, kitty requires 3.3 and and alacritty uses 3.1 iirc
try using a terminal like foot
also you might need to use hyprland with legacy render to avoid issues

there isn't much to be done since this is a driver issue

**Comment by root2185** [comment]
I tried tilix and st, looks like I can't open anything.
(No background, only a black screen).

How do I enable legacy render?

**Comment by MightyPlaza** [comment]
you have to compile hyprland with legacy render flag
I don't know what issue not using legacy render is/will cause

check why it isn't running with something like `exec = bash -c "foot &> ~/out.log"`

**Comment by root2185** [comment]
No output for tilix, foot out.log:
```
warn: wayland.c:1507: no server-side cursors available, falling back to client-side cursors
warn: wayland.c:1364: unknown global removed: 0x0000002b
 err: wayland.c:1986: failed to roundtrip Wayland display: Connection reset by peer
 err: wayland.c:1986: failed to roundtrip Wayland display: Connection reset by peer
 err: wayland.c:1986: failed to roundtrip Wayland display: Connection reset by peer
warn: terminal.c:1798: slave exited with signal 1 (Hangup)
 err: wayland.c:1951: failed to flush wayland socket: Connection reset by peer
```

**Comment by MightyPlaza** [comment]
did you compile with legacy render?

**Comment by root2185** [comment]
>I don't know what issue not using legacy render is/will cause

Do you mean that legacy render may have big downside?

>did you compile with legacy render?
No.

**Comment by MightyPlaza** [comment]
not using it may be causing this issue, but idk
try using it

**Comment by gfhdhytghd** [comment]
install hyprland with hyprv3 script and than manually remove hyprland and install hyprland-legacyrenderer from aur by yay -S hyprland-legacyrenderer

**Comment by gfhdhytghd** [comment]
I think that for some green hands automatically install all the appliances(swww,mako,wofi,way bar,etc)and automatically set all the config file is really useful, since that it really annoying people read wiki and make up a lot of config file, green hands can learn after install and then create there own things

**Comment by root2185** [comment]
I installed hyprland-legacyrendere from the AUR and it works.
No blur options there?

**Comment by gfhdhytghd** [comment]
i advise有头turn off every thing about blur, transparent, fade, shadow or such thing is the original berthing not working and only the legacyrenderer version works, you may have a try, follow https://hyprland.org/ to configure the config file if you want I can send you my config for the legacy renderer version

**Comment by root2185** [comment]
That thing that warns you about something wrong in the config complained about blur options.
It was just a warning something like "no such option, things may work not correctly."

If you can send it I'll check it.

**Comment by gfhdhytghd** [comment]
I'v never seen some thing warn me about blur or some thing, usually it is just some gramma problem, but it does work incorrectly

**Comment by gfhdhytghd** [comment]
# Setup monitors
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,1024x768@60,0x0,1

# Dual monitor example on G15 Strix
# eDP-1 is the built in monitor while DP-1 is external
# Both monitors here are at 1440 and 165Hz
# DP-1 is on the left and  eDP-1 is on the right
#monitor=DP-1,2560x1440@165,0x0,1
#monitor=eDP-1,2560x1440@165,2560x0,1.25

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = mako
exec-once = swww init&&swww img ~/.config/HyprV/backgrounds/v2-background.jpg 
exec-once = fcitx5
exec-once = blueman-applet
exec-once = nm-applet --indicator
#exec-once = ~/.config/HyprV/hyprv_util setbg

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 3
    gaps_out = 8
    border_size = 3
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.active_border=rgb(cdd6f4)
    col.inactive_border = rgba(595959aa)

    layout = dwindle
    no_cursor_warps = true
}

misc {
    disable_hyprland_logo = yes
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
	

    rounding = 7

    drop_shadow = false
    #shadow_range = 4
    #shadow_render_power = 3
    #col.shadow = rgba(1a1a1aee)
	blur {
	    enabled = off
	    #size = 7
	    #passes = 4
	}
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.7, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier, slide
    animation = windowsOut, 1, 7, myBezier, slide
    animation = border, 0, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 10, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}
    blurls = lockscreen
    blurls = lockscreen

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic mouse V1 {
    sensitivity = -0.5
}

# Example windowrule v1
#windowrule = float, ^(kitty)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(chromium)$
windowrule = float,^(thunar)$
windowrule = float, title:^(btop)$
windowrule = float, title:^(update-sys)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# rules below would make the specific app transparent
windowrulev2 = opacity 0.8 0.8,class:^(kitty)$
windowrulev2 = animation popin,class:^(kitty)$,title:^(update-sys)$
windowrulev2 = animation popin,class:^(dolphin)$
windowrulev2 = opacity 0.8 0.8,class:^(dolphin)$
windowrulev2 = opacity 0.8 0.8,class:^(VSCodium)$
windowrulev2 = animation popin,class:^(chromium)$
windowrulev2 = move cursor -3% -105%,class:^(wofi)$
windowrulev2 = noanim,class:^(wofi)$


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, exec,konsole  #open the terminal
bind = $mainMod, F4, killactive, # close the active window
bind = $mainMod, L, exec, swaylock # Lock the screen
bind = $mainMod, M, exec, wlogout --protocol layer-shell # show the logout window
bind = $mainMod SHIFT, M, exit, # Exit Hyprland all together no (force quit Hyprland)
bind = $mainMod, E, exec, dolphin # Show the graphical file browser
bind = $mainMod, V, togglefloating, # Allow a window to float
bind = ALT, SPACE, exec, wofi # Show the graphical app launcher
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, S, exec, grim -t jpeg -q 10 -g "$(slurp)" - | swappy -f - # take a screenshot
bind = $mainMod, I, exec, vivaldi-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod SHIFT, mouse:272, resizewindow

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf
source = ~/.config/hypr/media-binds.conf
source = ~/.config/hypr/rog-g15-strix-2021-binds.conf

**Comment by gfhdhytghd** [comment]
[hyprconf.txt](https://github.com/hyprwm/Hyprland/files/12316731/hyprconf.txt)

**Comment by gfhdhytghd** [comment]
the gramma rule of blur have changed
(copy from wiki)
A subcategory is a nested category:

decoration {
    # ...
    # ...

    blur {
        # ...
        # ...
    }
}
Doing decoration:blur { is invalid!
