### ISSUE TITLE
Crashes randomly by Xwayland's SIGABRT

### ISSUE THREAD

**Issue by leonasdev** [hyprwm/Hyprland#2892]
### Hyprland Version

Hyprland, built from branch main at commit 46cf4eb837c39255f24fa32b5a740c28ce1a324f dirty (Nix: bump wlroots). Tag: v0.28.0-6-g46cf4eb8  flags: (if any)

### Bug or Regression?

Bug

### Description

As same as https://github.com/hyprwm/Hyprland/issues/1897

### How to reproduce
I found that when I log in to hyprland, if it stuck on a black screen with a cursor about 1 minutes, this session 99% will crash in 5 minutes.

### Crash reports, logs, images, videos

coredumpctl info:
[coredump.txt](https://github.com/hyprwm/Hyprland/files/12268060/coredump.txt)

log seems no error:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12268067/hyprland.log)

no crash reports generate.

**Comment by leonasdev** [comment]
now it not only crash on xwayland but hyprland:
- [coredump_hyprland.txt](https://github.com/hyprwm/Hyprland/files/12289023/coredump_hyprland.txt)
- [coredump_list.txt](https://github.com/hyprwm/Hyprland/files/12289028/coredump_list.txt)

**Comment by izmyname** [comment]
Does it still happen?

**Comment by izmyname** [comment]
UPD: Since the related problem closed -shouldn't this one be closed too?
