### ISSUE TITLE
waiting for a DRM card deviceession

### ISSUE THREAD

**Issue by JustXLS** [hyprwm/Hyprland#2893]
### Hyprland Version

0.27.2-r1

### Bug or Regression?

Bug

### Description

Hyprland doesn't start, just sending message to terminal: "waiting for a DRM card deviceession"

### How to reproduce

.

### Crash reports, logs, images, videos

log: https://pastebin.com/ghAMJnxg

**Comment by vaxerski** [comment]
looks like a crash, please provide a crash report

**Comment by JustXLS** [comment]
> looks like a crash, please provide a crash report

I guess I don't have a crash report
