### ISSUE TITLE
During use, random crashes...

### ISSUE THREAD

**Issue by ashixu** [hyprwm/Hyprland#2894]
### Hyprland Version

0.28.0

### Bug or Regression?

Bug

### Description

My device is Thinkpad neo14, R7 6800H with archlinux ,hyprland..
I also encountered this problem for the early version. (such as 0.27.2...
The desktop freezes, splashes the screen a few times and returns to tty. And sometimes it doesn't go back to tty, you can only press the power button to shut down.

### How to reproduce

I simply ran a terminal and Google Chrome using it, and it crashed randomly. The probability of crash is greater when using OBS. I can't use it as nomal.

### Crash reports, logs, images, videos

[hyprlandCrashReport1329.txt](https://github.com/hyprwm/Hyprland/files/12268651/hyprlandCrashReport1329.txt)
![photo_2023-08-06_11-34-40](https://github.com/hyprwm/Hyprland/assets/65940468/c8c443c3-84c9-48a1-8377-55e7aa9561bc)

**Comment by vaxerski** [comment]
that's odd. Does this happen when you disable blur? Or do you have it disabled?

**Comment by ashixu** [comment]
thank you for your reply, I will try to disable blur later. and My config file is that:
[hyprland (copy 1).txt](https://github.com/hyprwm/Hyprland/files/12269974/hyprland.copy.1.txt)

**Comment by ashixu** [comment]
> that's odd. Does this happen when you disable blur? Or do you have it disabled?

thank you for your reply, I will try to disable blur later. and My config file is that:
[hyprland (copy 1).txt](https://github.com/hyprwm/Hyprland/files/12269974/hyprland.copy.1.txt)

**Comment by ashixu** [comment]
oh no，although I disable blur the issue occurs again. 🥹> that's odd. Does this happen when you disable blur? Or do you have it disabled?

**Comment by vaxerski** [comment]
no clue, this is odd.

**Comment by ashixu** [comment]
> no clue, this is odd.

Okay,thank you anyway.

**Comment by izmyname** [comment]
Is this still a thing? The linked issue with the similar problem was closed as completed.
