### ISSUE TITLE
Error using Hyprland on Fedora38

### ISSUE THREAD

**Issue by lxbx44** [hyprwm/Hyprland#2899]
### Hyprland Version

Not installed yet

### Bug or Regression?

Bug

### Description

I just installed the sway spin of fedora to install hyprland (Fedora Linux 38 (Sway)) i've followed the instruction from hyprland's wiki and when i go to sddm to open hyprland it puts me again to sddm.
Additionally, when i run `Hyprland` in terminal it shows me this error:

```
-> Hyprland
Hyprland: error while loading shared libraries: libxcb-errors.so.0: cannot open shared object file: No such file or directory
```

### How to reproduce

idk

**Comment by romanstingler** [comment]
this is an sddm bug, hyprland is not officially supporting any login managers.

**Comment by lxbx44** [comment]
> this is an sddm bug, hyprland is not officially supporting any login managers. 

So how could i make it work?

**Comment by zootedb0t** [comment]
Probably your system is missing `xcb-errors` package. so you have to build it . you can find instrction [here](https://github.com/hyprwm/Hyprland/discussions/284#discussioncomment-3113925)

**Comment by katsuja** [comment]
> this is an sddm bug, hyprland is not officially supporting any login managers.

I don't think it's a bug of sddm. The same thing happens to me on my laptop: I log in from sddm and it immediately takes me back to the login screen. I've tried disabling sddm and logging in with the Hyprland command from the shell and it gives me the same error. with the desktop same thing with the latest update. I use Arch Linux on both PCs. sorry for my english, i'm using google translate

**Comment by katsuja** [comment]
I don't think it's a bug of sddm. The same thing happens to me on my laptop: I log in from sddm and it immediately takes me back to the login screen. I've tried disabling sddm and logging in with the Hyprland command from the shell and it gives me the same error. with the desktop same thing with the latest update. I use Arch Linux on both PCs. sorry for my english, i'm using google translate

**Comment by kaii-lb** [comment]
run `whereis libxcb-errors.so.0` if it doesn't give you a location, you don't have the package. Install it for your system.
