### ISSUE TITLE
windows instantly close

### ISSUE THREAD

**Issue by MoopFace** [hyprwm/Hyprland#2900]
### Hyprland Version

hyprland-0.27.2-1

### Bug or Regression?

Bug

### Description

Arch Linux ARM (raspberry pi 4B)

whenever I try to open a window in hyprland it immediately closes.
mod + Q won't open kitty, even though it's installed.
tried changing mod+Q to open alacritty and it appears for a moment before closing.

looking at /tmp/hypr/$latest I notice
[ERR] onWindowRemovedTiling node null?

### How to reproduce

start hyprland from terminal.
Hyprland
try to open alacritty(or kitty) via default keybind.
MOD+Q
sometimes I have to spam it to get anything.
ghost of terminal appears and then vanishes.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12272891/hyprland.log)

**Comment by MightyPlaza** [comment]
kitty logs please `exec=bash -c "kitty &> out.log"`

**Comment by MoopFace** [comment]
[out.log](https://github.com/hyprwm/Hyprland/files/12284579/out.log)

**Comment by MightyPlaza** [comment]
looks like driver issue, using a terminal like foot should work
use it to check you opengles version

**Comment by MoopFace** [comment]
foot will open and stay open but I never get a shell prompt. I just displays an error saying
error: 'C' is not a UTF-8 local, and failed to find a fallback
here is the full log that I saved to file.
[outfoot.log](https://github.com/hyprwm/Hyprland/files/12285050/outfoot.log)

**Comment by MightyPlaza** [comment]
pretty sure that's a locale issue, fix it on the tty

**Comment by MoopFace** [comment]
fixed locale issue(I still can't type the letter 'l' in lowercase), got a working terminal via foot, checked openGL version
OpenGL version string: 2.1 Mesa 23.1.5
according to that issue you linked I need to update my OpenGL version right?
thanks for all the help by the way!

**Comment by MightyPlaza** [comment]
not sure if you can update your opengles version
also opengles not opengl
kitty needs 3.3 and alacritty 3.1 iirc
for hyprland to fully work you need 3.2, or 2.0 using legacy render

**Comment by MightyPlaza** [comment]
not sure why this is open?
(maybe see for a possible better driver https://melissawen.github.io/blog/2022/11/10/v3d-in-the-mainline)

**Comment by vaxerski** [comment]
not a hyprland issue. Check your drivers.
