### ISSUE TITLE
Core dumped while starting hyprland

### ISSUE THREAD

**Issue by SimplyVoid** [hyprwm/Hyprland#2909]
### Hyprland Version

hyprland-git?

### Bug or Regression?

Bug

### Description

Updated hyprland-git from like 5 mins ago and rebooted but got core dumped error. It's like 3am here so switched to hyprland instead of hyprland-git stable and things are working fie rn.

OS: Arch
Kernel: Linux 6.4.8-zen1-1-zen
Cpu: Intel Core i3-7100
Gpu: integrated 

sorry for my rush on the issue but i was going to sleep.

### How to reproduce

Using latest hyprland-git?

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/pull/2908

**Comment by Slimemaster0** [comment]
Same here, i had to downgrade to v0.28.0

**Comment by SimplyVoid** [comment]
Seems like already fixed so closing😄
