### ISSUE TITLE
Hyprland not starting on virtual machine

### ISSUE THREAD

**Issue by jmfergeau** [hyprwm/Hyprland#2910]
### Hyprland Version

0.27.2

### Bug or Regression?

Bug

### Description

When starting hyprland, i get the critical error `m_sWLRRenderer was NULL!`

### How to reproduce

1. Make a fresh arch linux install on virtualbox, using archinstall script and setting it as desktop with hyprland selected as DE
2. start the installed arch
3. start hyprland from TTY

### Crash reports, logs, images, videos

I suspect the way virtualbox handles screen to cause this crash.

**Comment by MightyPlaza** [comment]
no 3d acceleration

**Comment by jmfergeau** [comment]
Thanks. Activating 3D acceleration fixed it.

Now to figure out how to use that thing...

**Comment by Droid-andy** [comment]
I use intel integrated graphics and so I **don't have the option to enable 3d acceleration** in my virtual box.
What should I do?

**Comment by MightyPlaza** [comment]
yes you have
