### ISSUE TITLE
Allow outer gaps to be set individually

### ISSUE THREAD

**Issue by kbtz** [hyprwm/Hyprland#2911]
Please allow at least the vertical and horizontal outer gaps to have their own variables, when not set they simply default to the `gaps_out` value.

This will be very helpful to bind horizontal gap toggles for those who have wide monitors. Things like browsing/reading in a single 2560px wide window gets uncomfortable real quick.

**Comment by kbtz** [comment]
The monitor setup worked out of the box so I skipped its docs, my bad. That should do the trick, thanks!

**Comment by MightyPlaza** [comment]
still not a solution since no_gaps_when_only will not work

**Comment by kbtz** [comment]
@MightyPlaza indeed, but I don't mind changing it manually for now. Later I will try to write a [script](https://wiki.hyprland.org/Configuring/Expanding-functionality/) to achieve a similar behavior and perhaps share it here if successful.
