### ISSUE TITLE
exec-desktop & exec-once-desktop

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#2912]
### Description

They should take a desktop entry and execute them.
Or better, they can have a DIR where desktop entries are present and can be executed.

Initial thought was that it will be nice for `~/.config/autostart/<appname>.desktop` but if hyprland gets these entries, it will make it easier to launch any desktop entry using `hyprctl`

**Comment by MightyPlaza** [comment]
use something like `exec-once = gtk-launch name.desktop` for that

**Comment by niksingh710** [comment]
> use something like `exec-once = gtk-launch name.desktop` for that

don't remember exactly but last time i faced a error while trying to run an desktop file

**Comment by vaxerski** [comment]
pointless, tbh.
