### ISSUE TITLE
pronlem with xwayland {   force_zero_scaling = true }

### ISSUE THREAD

**Issue by gfhdhytghd** [hyprwm/Hyprland#2916]
### Hyprland Version

hyprctl version

### Bug or Regression?

Bug

### Description

after i set 
xwayland {
  force_zero_scaling = true
}
and replace all the "-hidpi"paks by the original one

the xorg apps work in some wrong way, it seams that it have a wrong screen edge

### How to reproduce

IDK

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/102898587/581975af-1286-4154-a6a1-9b9101104ac2

**Comment by vaxerski** [comment]
weird, never seen that, but you may also want to run chrome in wayland.

**Comment by gfhdhytghd** [comment]
Some of the app’s that I have to use(WeChat and qq) have to run in x11, chrome is just for demo, I just switch back to the hidpi-patch and the problem solved.

**Comment by vaxerski** [comment]
can't repro, seems to be working just fine to me

**Comment by gfhdhytghd** [comment]
try connect to a second display?

**Comment by gfhdhytghd** [comment]
if you want maybe you can remote desktop to my computer and try to find the problem?

**Comment by maxyvisser** [comment]
I am facing similar problems. On my main monitor (DP-2, 3840x2160, 2x), applications cannot detect the cursor going any further than halfway across the horizontal axis. It is almost as if there is a border at x = 1920, and any mouse position/clicks right of that are modified to be on 1920 instead.

This did not happen when using the hidpi patches, which I stopped using after seeing the warning in the wiki.

A code-style explanation (using python syntax):
```
def on_click:
    if cursor.x > 1920 and monitor == "DP-2":
        cursor.x = 1920
    click()
```

Output of `hyprctl monitors`:
```
Monitor HDMI-A-1 (ID 0):
	1280x1024@60.020000 at 3840x0
	description: Hewlett Packard LA1951 CNK0480FBJ (HDMI-A-1)
	make: Hewlett Packard
	model: LA1951
	serial: CNK0480FBJ
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 24 0 44
	scale: 1.00
	transform: 1
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-1 (ID 1):
	1920x1080@164.500000 at 0x0
	description: ASUSTek COMPUTER INC VG249Q1R L8LMDW001342 (DP-1)
	make: ASUSTek COMPUTER INC
	model: VG249Q1R
	serial: L8LMDW001342
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 24 0 44
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 1

Monitor DP-2 (ID 2):
	3840x2160@59.997002 at 1920x0
	description: Samsung Electric Company LU28R55 H4ZT404747 (DP-2)
	make: Samsung Electric Company
	model: LU28R55
	serial: H4ZT404747
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 24 0 44
	scale: 2.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 1
```

Relevant sections of my `hyprland.conf`:
```
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-1, highrr, 0x0, 1
monitor = DP-2, highres, 1920x0, 2, bitdepth, 10
monitor = HDMI-A-1, preferred, 3840x0, 1, transform, 1

...

xwayland {
	force_zero_scaling = true
}
```

**Comment by sifmelcara** [comment]
My setup is 2 vertical monitors (2160x3840) + 1 horizontal monitor (3840x2160) + nvidia card + hyprland 8e04a80e60983f5def26bdcaea701040fea9a7ae (current version in nixpkgs) + `hyprland.conf` config similar to @maxyvisser 's and I can reproduce the issue described by @maxyvisser by running `xev` on either one of vertical monitor, except in my case it is y-axis get cut at 2159. When `xev` is on my horizontal monitor the mouse coordinate is correct.

@maxyvisser 's mouse on `DP-2` got cut at 1920 (their `DP-1`'s x-axis length), and my mouse got cut 2159 (which is very close to 2160, my monitor's x-axis length), so maybe this bug has something to do with mouse location clipping using wrong limit?

**Comment by maxyvisser** [comment]
Another potentially interesting observation: the layout of the surrounding monitors matters. My regular setup:
```
+-------------------++-------------------++-----------+
|       DP-1        ||       DP-2        || HDMI-A-1  |
|     1920x1080     ||     3840x2160     || 1040x1280 |
|     scale: 1      ||     scale: 2      || scale: 1  |
|                   ||                   || transf: 1 |
+-------------------++-------------------++-----------+
```
This has a cutoff on monitor DP-2 at x = 1915. However, when switching DP-1 and HDMI-A-1:
```
+-----------++-------------------++-------------------+
| HDMI-A-1  ||       DP-2        ||       DP-1        |
| 1280x1024 ||     3840x2160     ||     1920x1080     |
| scale: 1  ||     scale: 2      ||     scale: 1      |
| transf: 1 ||                   ||                   |
+-----------++-------------------++-------------------+
```
The cutoff changes to x = 2811.

This is not at all what I expected: 1915 is roughly the width of the leftmost monitor (so I get where that number could come from), but 2811 has nothing to do with any dimensions of any of my monitors.

Relevant monitors section:
```
monitor = DP-1, highrr, 2944x0, 1
monitor = DP-2, highres, 1024x0, 2, bitdepth, 10
monitor = HDMI-A-1, preferred, 0x0, 1, transform, 1
```

@sifmelcara Do you see any similar strange numbers when switching up your layout?

Also, this might be nvidia related (both @sifmelcara and I use a nvidia card with the patch). Could this maybe be why @vaxerski can't reproduce the issue?

**Comment by maxyvisser** [comment]
Some other monitor layouts:
```
+-------------------++-----------++-------------------+
|       DP-1        || HDMI-A-1  ||       DP-2        |
|     1920x1080     || 1040x1280 ||     3840x2160     |
|     scale: 1      || scale: 1  ||     scale: 2      |
|                   || transf: 1 ||                   |
+-------------------++-----------++-------------------+
```
Monitors section:
```
monitor = DP-1, highrr, 0x0, 1
monitor = DP-2, highres, 2944x0, 2, bitdepth, 10
monitor = HDMI-A-1, preferred, 1920x0, 1, transform, 1
```
^ Cutoff: x = 891 (Again, completely nonsensical)


```
+-------------------++-----------++-------------------+
|       DP-2        || HDMI-A-1  ||       DP-1        |
|     3840x2160     || 1280x1024 ||     1920x1080     |
|     scale: 2      || scale: 1  ||     scale: 1      |
|                   || transf: 1 ||                   |
+-------------------++-----------++-------------------+
```
Monitors section:
```
monitor = DP-1, highrr, 2944x0, 1
monitor = DP-2, highres, 0x0, 2, bitdepth, 10
monitor = HDMI-A-1, preferred, 1920x0, 1, transform, 1
```
^ No apparent cutoff? x goes all the way to 3832 (which appears to be correct considering my borders)

**Comment by maxyvisser** [comment]
Last two layouts:
```
+-------------------++-------------------++-----------+
|       DP-2        ||       DP-1        || HDMI-A-1  |
|     3840x2160     ||     1920x1080     || 1280x1024 |
|     scale: 2      ||     scale: 1      || scale: 1  |
|                   ||                   || transf: 1 |
+-------------------++-------------------++-----------+
```
Monitors:
```
monitor = DP-1, highrr, 1920x0, 1
monitor = DP-2, highres, 0x0, 2, bitdepth, 10
monitor = HDMI-A-1, preferred, 3840x0, 1, transform, 1
```
^ Again, no apparent cutoff.

```
+-----------++-------------------++-------------------+
| HDMI-A-1  ||       DP-1        ||       DP-2        |
| 1280x1024 ||     1920x1080     ||     3840x2160     |
| scale: 1  ||     scale: 1      ||     scale: 2      |
| transf: 1 ||                   ||                   |
+-----------++-------------------++-------------------+
```
Monitors:
```
monitor = DP-1, highrr, 1024x0, 1
monitor = DP-2, highres, 2944x0, 2, bitdepth, 10
monitor = HDMI-A-1, preferred, 0x0, 1, transform, 1
```
^ Again a cutoff at x = 891

It appears that if DP-2 is on the left side, no cutoff occurs. If it is on the right side, the cutoff will be at x = 891. And if it is in the middle, the cutoff is dictated by the positions of other monitors.

**Comment by vaxerski** [comment]
I cannot test multimon stuff (on holiday)

you can ping me in a week and I can see what's up. For now, on a single monitor on my laptop with 1.5 scale and force zero scaling everything seems alright

**Comment by maxyvisser** [comment]
Sure, I will ping you later. Have a nice holiday!

**Comment by woojiq** [comment]
**OT**: if you can't use "pinch-to-zoom", "smooth-scrolling" etc. with google-chrome with the new update (removed hidpi). Set `chrome://flags/#ozone-platform-hint` to Auto or Wayland. I spent half a day debugging, maybe this will save someone some time 🙂

P.S. ty for anime girl on background :)

**Comment by gfhdhytghd** [comment]
then there’ll be some problem with the input method

**Comment by imxyy1soope1** [comment]
> then there’ll be some problem with the input method

try `google-chrome-stable --ozone-platform=wayland --enable-wayland-ime`

**Comment by gfhdhytghd** [comment]
I’ve tried before, working not stable

**Comment by imxyy1soope1** [comment]
Okay, on my computer this works well. I have a 2K monitor on the left and a 1080P monitor on the right. I enabled xwayland:force_zero_scale but can't repro the problem.

**Comment by imxyy1soope1** [comment]
> Okay, on my computer this works well. I have a 2K monitor on the left and a 1080P monitor on the right. I enabled xwayland:force_zero_scale but can't repro the problem.

I tried 1x and 1.33x zoom, both work fine

**Comment by gfhdhytghd** [comment]
Try rotation?

**Comment by imxyy1soope1** [comment]
> Try rotation?

Also works fine

**Comment by gfhdhytghd** [comment]
metaphysics

**Comment by imxyy1soope1** [comment]
> metaphysics

what?

**Comment by gfhdhytghd** [comment]
usually i use this word to describe the problems hard to find the cause or describe don’t know why do something can solve something

**Comment by imxyy1soope1** [comment]
量子力学？

> usually i use this word to describe the problems hard to find the cause or describe don’t know why do something can solve something

**Comment by gfhdhytghd** [comment]
玄学

**Comment by maxyvisser** [comment]
@imxyy1soope1 do you have a Nvidia graphics card, and do you use the Nvidia patch?

**Comment by imxyy1soope1** [comment]
> @imxyy1soope1 do you have a Nvidia graphics card, and do you use the Nvidia patch?

no, I use AMD ATI Radeon RX 5500XT

**Comment by maxyvisser** [comment]
Ok, so to make a brief overview of the repro status:

| name: | @sifmelcara | @maxyvisser | @gfhdhytghd | @imxyy1soope1 | vaxerski |
| ----- | ----------- | ----------- | ----------- | ------------- | -------- |
| GPU:  | Nvidia | Nvidia | ? | AMD | ? |
| Monitor count | 3 | 3 | 2? | 2 | 1 |
| Scale | ? | 2x | ? | 1.33 | ? |
| Repro | Yes | Yes | Yes | No | No |

This table would suggest that this issue is related to Nvidia and/or triple monitor setups (depending on @gfhdhytghd's monitor count, which was not yet specified)

**Comment by gfhdhytghd** [comment]
i7-1260p+iris Xe，
3120x2080，sf=2
1920x1080，sf=1.15，rotation90
origin version

**Comment by gfhdhytghd** [comment]
this is the statue when i report this issus

**Comment by maxyvisser** [comment]
Updated the table with the new info, thanks

**Comment by gfhdhytghd** [comment]
i have the dual monitor in configuration file but not pluged when it first happens（when i first swich to original version add the “force zero”in the file），but when pluged it also happens（on both monitors）

**Comment by vaxerski** [comment]
can someone post the output of `xrandr` when the bug happens? I have an idea.

**Comment by gfhdhytghd** [comment]
wait for me to go home

**Comment by gfhdhytghd** [comment]
❯ xrandr
Screen 0: minimum 16 x 16, current 3670 x 3861, maximum 32767 x 32767
eDP-1 connected 3120x2080+550+1781 (normal left inverted right x axis y axis) 300mm x 200mm
   3120x2080     89.97*+
   2048x1536     89.91  
   1920x1440     89.91  
   1600x1200     89.91  
   1440x1080     89.93  
   1400x1050     89.92  
   1280x1024     89.91  
   1280x960      89.91  
   1152x864      89.80  
   1024x768      89.72  
   800x600       89.85  
   640x480       89.73  
   320x240       87.89  
   2560x1600     89.95  
   1920x1200     89.91  
   1680x1050     89.94  
   1440x900      89.83  
   1280x800      89.89  
   1152x720      89.83  
   960x600       89.70  
   928x580       89.74  
   800x500       89.80  
   768x480       89.62  
   720x480       89.45  
   640x400       89.60  
   320x200       87.62  
   2880x1620     89.94  
   2560x1440     89.92  
   2048x1152     89.87  
   1920x1080     89.93  
   1600x900      89.88  
   1368x768      89.74  
   1280x720      89.80  
   1024x576      89.65  
   864x486       89.72  
   720x400       89.87  
   640x350       89.05

**Comment by gfhdhytghd** [comment]
the conf
  monitor=eDP-1, 3120*2080@90, 550x1781, 2
  monitor=DP-4, 1920x1080@60, 870x0, 1.078, transform,1
 monitor=DP-3, 3840*2560@30.000, 0x342,1.5

**Comment by vaxerski** [comment]
umm, I think it got cut off? can you show xrandr for every display?

**Comment by gfhdhytghd** [comment]
❯ xrandr
Screen 0: minimum 16 x 16, current 3670 x 4208, maximum 32767 x 32767
eDP-1 connected 3120x2080+550+2128 (normal left inverted right x axis y axis) 300mm x 200mm
   3120x2080     89.97*+
   2048x1536     89.91  
   1920x1440     89.91  
   1600x1200     89.91  
   1440x1080     89.93  
   1400x1050     89.92  
   1280x1024     89.91  
   1280x960      89.91  
   1152x864      89.80  
   1024x768      89.72  
   800x600       89.85  
   640x480       89.73  
   320x240       87.89  
   2560x1600     89.95  
   1920x1200     89.91  
   1680x1050     89.94  
   1440x900      89.83  
   1280x800      89.89  
   1152x720      89.83  
   960x600       89.70  
   928x580       89.74  
   800x500       89.80  
   768x480       89.62  
   720x480       89.45  
   640x400       89.60  
   320x200       87.62  
   2880x1620     89.94  
   2560x1440     89.92  
   2048x1152     89.87  
   1920x1080     89.93  
   1600x900      89.88  
   1368x768      89.74  
   1280x720      89.80  
   1024x576      89.65  
   864x486       89.72  
   720x400       89.87  
   640x350       89.05  
DP-4 connected 1920x1080+870+350 left (normal left inverted right x axis y axis) 340mm x 190mm
   1080x1920     59.96*+
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77

**Comment by gfhdhytghd** [comment]
the things goes well on that 4k display

**Comment by vaxerski** [comment]
I think I know why. Will fix later today.

**Comment by gfhdhytghd** [comment]
OHHHH！

**Comment by gfhdhytghd** [comment]
Also I wish the program can auto set the scale of xrandr in order to let the xorg apps run in a correct size on different dpi screens

**Comment by gfhdhytghd** [comment]
CMake Error at CMakeLists.txt:183 (target_sources):
  Cannot find source file:

    protocols/hyprland-global-shortcuts-v1-protocol.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  CMakeLists.txt:211 (protocol)

**Comment by gfhdhytghd** [comment]
when i'm trying to build from github

**Comment by vaxerski** [comment]
either didnt clone --recursive or forgot to do make protocols

**Comment by gfhdhytghd** [comment]
thanks that is the problem

**Comment by gfhdhytghd** [comment]
the mouse on x11 apps totally stop working

**Comment by gfhdhytghd** [comment]
hyprctl version
Hyprland, built from branch main at commit 2b4537606f604f29b2d42d7be369182831269958 dirty (master: fix `always_center_master` (2961)).
Tag: v0.28.0-56-g2b453760

flags: (if any)

**Comment by gfhdhytghd** [comment]
xrandr
Screen 0: minimum 16 x 16, current 4750 x 4208, maximum 32767 x 32767
eDP-1 connected 3120x2080+550+2128 (normal left inverted right x axis y axis) 300mm x 200mm
   3120x2080     89.97*+
   2048x1536     89.91  
   1920x1440     89.91  
   1600x1200     89.91  
   1440x1080     89.93  
   1400x1050     89.92  
   1280x1024     89.91  
   1280x960      89.91  
   1152x864      89.80  
   1024x768      89.72  
   800x600       89.85  
   640x480       89.73  
   320x240       87.89  
   2560x1600     89.95  
   1920x1200     89.91  
   1680x1050     89.94  
   1440x900      89.83  
   1280x800      89.89  
   1152x720      89.83  
   960x600       89.70  
   928x580       89.74  
   800x500       89.80  
   768x480       89.62  
   720x480       89.45  
   640x400       89.60  
   320x200       87.62  
   2880x1620     89.94  
   2560x1440     89.92  
   2048x1152     89.87  
   1920x1080     89.93  
   1600x900      89.88  
   1368x768      89.74  
   1280x720      89.80  
   1024x576      89.65  
   864x486       89.72  
   720x400       89.87  
   640x350       89.05  
DP-4 connected 1080x1920+3670+350 left (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77

**Comment by gfhdhytghd** [comment]
the config using now   
monitor=eDP-1, 3120x2080@90, 550x2128, 2
monitor=DP-4, 1920x1080@60, 870x350, 1.078, transform,1
monitor=DP-3, 3840x2560@60.000, 0x342,1.43

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12346624/patch.txt)

okay since that didn't work I'll just post a patch for now. Test this.

**Comment by gfhdhytghd** [comment]
ok i will try

**Comment by gfhdhytghd** [comment]
problem solved

**Comment by gfhdhytghd** [comment]
https://github.com/hyprwm/Hyprland/assets/102898587/92b4a273-f725-48c0-9251-f1fd7a3e7550

is this regular?

**Comment by gfhdhytghd** [comment]
another wired problem, some x11 app with a startup windows in the centre may shown in  a place that isn't centre, or out of the screen like this
![swappy-20230816_013523](https://github.com/hyprwm/Hyprland/assets/102898587/bb1a2684-3c8c-47e8-b0f8-6366fa2e0fe9)

(when open this app when focuse on the built-in display, the windows disapear, but able to see in btop I guess it is at some where out of the screen)

**Comment by gfhdhytghd** [comment]
No such things happened on hidpi-patch version, maybe some extra work need to do

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12347032/patch.txt)

try this for positioning issues

**Comment by gfhdhytghd** [comment]
/usr/bin/ld: IHyprLayout.cpp:(.text+0x4721): undefined reference to `CHyprXWaylandManager::xwaylandToWaylandCoords(Vector2D const&)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:13: release] Error 1
make[1]: Leaving directory '/home/wilf/Downloads/Hyprland'
make: *** [Makefile:38: install] Error 2

**Comment by vaxerski** [comment]
fixed and pushed to main anyways

**Comment by gfhdhytghd** [comment]
ok

**Comment by gfhdhytghd** [comment]
it is finally on the screen, but not that centre
on DP-1, it have a few pixels offset
on eDP-1, it have a huge offset
![swappy-20230816_022012](https://github.com/hyprwm/Hyprland/assets/102898587/8f85684c-376d-4971-a850-bd7a525c85a7)
![swappy-20230816_021820](https://github.com/hyprwm/Hyprland/assets/102898587/9f070464-8f7f-4c4f-aae9-7c079fb7b082)

**Comment by vaxerski** [comment]
I will try to debug it more when I come back from holiday. For now, I am stuck with only one monitor. Since it's on the screen, it's not a big deal.

You can open a new issue for this, and ping me after the 20th

**Comment by gfhdhytghd** [comment]
ok

**Comment by gfhdhytghd** [comment]
> I will try to debug it more when I come back from holiday. For now, I am stuck with only one monitor. Since it's on the screen, it's not a big deal.
> 
> You can open a new issue for this, and ping me after the 20th

back from holiday?

**Comment by memchr** [comment]
Off topic: Chromium supports Wayland
```
--ozone-platform-hint=auto
```
