### ISSUE TITLE
Turning display off renders Hyprland unusable

### ISSUE THREAD

**Issue by MitchMG2** [hyprwm/Hyprland#2917]
### Hyprland Version

Hyprland, built from branch main at commit c748f36939cdac74332dde3afb866ad35bea1825 dirty (internal: add lock files and hyprctl instances). Tag: v0.28.0-15-gc748f369  flags: (if any)

### Bug or Regression?

Bug

### Description

Turning off the display soft crashes hyprland. Upon turning it back on again, every there is only the default Hyprland splash, waybar is gone and firefox windows will still appear if selecting the correct workspace but cannot be interacted with (at least not visually). 

Hyprland can be somewhat interacted with as switching workspace still works and opening a terminal with the usual bind to run "killall Hyprland" will bring me back to TTY. None of that can be visually seen. No visual terminal opening, just relying on muscle memory. 

AMD card with official mesa driver.

log
https://pastebin.com/DQ7QtiC2

config
https://pastebin.com/95Cx9G66

enviroment variables
https://pastebin.com/ncH5CyH3

stack trace after running killall Hyprland and then CTRL+C in tty (doesnt immediately default back to prompt)

systemd-coredump[733531]: [🡕] Process 732625 (Hyprland) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 732625:
                                                  #0  0x00007f8b0fc8e83c n/a (libc.so.6 + 0x8e83c)
                                                  #1  0x00007f8b0fc3e668 raise (libc.so.6 + 0x3e668)
                                                  #2  0x00007f8b0fc264b8 abort (libc.so.6 + 0x264b8)
                                                  #3  0x00007f8b0fc27390 n/a (libc.so.6 + 0x27390)
                                                  #4  0x00007f8b0fd1f5bb __fortify_fail (libc.so.6 + 0x11f5bb)
                                                  #5  0x00007f8b0fd208c6 __stack_chk_fail (libc.so.6 + 0x1208c6)
                                                  #6  0x0000555f72becb5b _ZN18CHookSystemManager4emitEPKSt6vectorI14SCallbackFNPtrSaIS1_EESt3any.cold (Hyprland + 0x7bb5b)
                                                  #7  0x0000555f74dedc20 n/a (n/a + 0x0)
                                                  ELF object binary architecture: AMD x86-64

### How to reproduce

Turn off physical display and back on again.

**Comment by abigrock** [comment]
@MitchMG2 Out of curiosity do you have workspace rules defined in your hyprland config? I was seeing very similar issues when swayidle would turn my monitors off via `hyprctl dispatch dpms off`. I ended up tweaking the syntax which seems to have resolved the issue.

Here's an example of workspace rules that appear to have stopped the soft crashing for me:
```
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-2, default:true
```

**Comment by phonetic112** [comment]
Having this issue as well

**Comment by abigrock** [comment]
Having a very similar issue here, but instead when swayidle triggers `hyprctl dispatch dpms off` and I leave my monitors in that state for an extended period of time - I think long enough for the monitors to go into their deepest sleep state. When I wake the monitors back up and unlock the session existing windows can be interacted with but attempting to move them causes them to go unresponsive. My background is missing and I can't open new windows (at least visually).

**Comment by iynaix** [comment]
Experiencing the same issue, I bisected and the bad commit seems to be a077b7a92e87a3edd1cebb9bdd4c4fa3ec3d7bb7.

**Comment by vaxerski** [comment]
fixad
