### ISSUE TITLE
File picker is comically large

### ISSUE THREAD

**Issue by kojq** [hyprwm/Hyprland#2918]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2

### Bug or Regression?

Bug

### Description

The file picker exceeds screen space and cannot be adjusted. Thus, it is tedious to use.

### How to reproduce

Open the file picker via any application, such as Firefox. Note, this was done with an AMD iGPU + NVIDIA dGPU (no setup was done for NVIDIA as it has been fine for me).

**Comment by MightyPlaza** [comment]
what file picker?
do you mean it uses all the tiling space?
if so it's a firefox bug, just use the `nomaximizerule` for the firefox class

**Comment by kojq** [comment]
Oh, okay. Could you elaborate a bit because I'm not sure how to do that (maybe showing the exact way to use `nomaximizerule`)? I presume it is tied to `Window Rules`.

I was going to create a new issue that Firefox bars, such as for captive portal and bookmarks, do not render at fullscreen. Is this also a Firefox bug that has the same solution?

If you know, could you explain the reason why Hyprland shouldn't generally handle this.

**Comment by MightyPlaza** [comment]
my guess is your window are getting maximized, you can check this with hyprctl clients (fullscreen: 1 fullscreenmode: 1)
`nomaximizerequest` (typo) doesn't allow the window to maximize by itself
see https://github.com/hyprwm/Hyprland/issues/2598

> I was going to create a new issue that Firefox bars, such as for captive portal and bookmarks, do not render at fullscreen. Is this also a Firefox bug that has the same solution?

this is simply firefox's fullscreen mode you get to with F11, for example
don't know if you can change it on firefox's side, but there is already an feature request for an alternative on hyprland's side https://github.com/hyprwm/Hyprland/issues/1817
or you can use no_gaps_when_only instead of fullscreen

**Comment by kojq** [comment]
`windowrulev2 = nofullscreenrequest, class:(firefox), title:(firefox)` does not work for me. I'm unsure if my title is incorrect.

**Comment by MightyPlaza** [comment]
do not set title, just class
in app fullscreen buttons won't work, but using `nomaximizerequest` (v0.28.0) solves that

**Comment by kojq** [comment]
> do not set title, just class

This is what I originally did. There is no change.

>  in app fullscreen buttons won't work, but using nomaximizerequest (v0.28.0) solves that

Okay. I'll wait for the update on Arch Linux.

However, I see no difference with this, and the file picker remains very large:

`windowrulev2 = nofullscreenrequest, class:(firefox),`

**Comment by MightyPlaza** [comment]
can you send the output of hyprctl clients?

**Comment by kojq** [comment]
```
Window 562b645b97b0 -> Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 647,22
	size: 611,676
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: firefox
	title: Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 2536
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 562b6457b6e0 -> user@arch:~:
	mapped: 1
	hidden: 0
	at: 22,22
	size: 611,676
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: foot
	title: user@arch:~
	initialClass: foot
	initialTitle: foot
	pid: 3402
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

**Comment by MightyPlaza** [comment]
where is the file picker?

**Comment by kojq** [comment]
I can't unfocus it, and it takes the whole view, so here is output for it by creating a new workspace:

```
Window 562b650551e0 -> Save As:
	mapped: 1
	hidden: 0
	at: 24,-114
	size: 1231,949
	workspace: 1 (1)
	floating: 1
	monitor: 0
	class: firefox
	title: Save As
	initialClass: firefox
	initialTitle: Save As
	pid: 2536
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

**Comment by kojq** [comment]
This is strange default behavior. I wouldn't want to resize all the time. I don't even know the resize bindings; I'd have to look it up.

**Comment by kojq** [comment]
> meta + right click

It shows the resize cursor icon for a brief moment, but I cannot manipulate the window.

> also set the maxsize windowrule to fix it

I will try this now.

**Comment by MightyPlaza** [comment]
you have to keep both buttons down

**Comment by kojq** [comment]
I realize that is how it should work, and I did that. However, the cursor keeps reverting regardless of how the click is held.

The `maxsize` rule did the trick. I find it odd to include in the config though.

**Comment by MightyPlaza** [comment]
can you resize other windows?

**Comment by kojq** [comment]
No

**Comment by MightyPlaza** [comment]
how?
what are you doing?

**Comment by kojq** [comment]
I hold super/meta/Windows key while doing press and hold right click. I also tried with press and double click hold right click. I also tried with press and triple click hold right click.

The default config last two lines are for moving and resizing the window. The moving one works fine, but not the resize one.

**Comment by MightyPlaza** [comment]
are you using a trackpad?

**Comment by kojq** [comment]
It only works with mouse...?

**Comment by MightyPlaza** [comment]
you have to mouse the cursor while pressing the other 2 keys

also try using something like `tap_and_drag`
http://wiki.hyprland.org/Configuring/Variables/#touchpad

**Comment by kojq** [comment]
I will enable `tap-and-drag`.

I have found some strange behavior (unless it is intended?).

After I set `windowrulev2 = maxsize 1000 1000, class:(firefox),` and try to open the file picker, it looks reasonable. However, removing the config, it persists across reboots.

After I changed bindm for moving the window to binde and back to bindm, I can no longer double click on the decoration to expand the window (even when closing and reopening all applications). However, a reboot resolved this.

I don't think these are intended.

**Comment by kojq** [comment]
I've no success for resizing when enabling `tap-and-drag`.

**Comment by MightyPlaza** [comment]
please try using an external mouse to find out what's happening

**Comment by kojq** [comment]
I don't have one on me at the moment. I'm concerned about all the other issues though.

**Comment by MightyPlaza** [comment]
what other issues?

the 1st one seems like the window got resized and size got stored so rule isn't needed anymore, same should happen on manual resize

> After I changed bindm for moving the window to binde and back to bindm, I can no longer double click on the decoration to expand the window (even when closing and reopening all applications). However, a reboot resolved this.

not sure what you mean by this but movewindow is for bindm anyways

**Comment by kojq** [comment]
> the 1st one seems like the window got resized and size got stored so rule isn't needed anymore, same should happen on manual resize

Oh, I see.

> not sure what you mean by this but movewindow is for bindm anyways

I changed it to binde and back to bindm, but the result was I could not expand the window with a double click until reboot.

To recap everything else, we are awaiting Firefox fullscreen issue resolution, and resize or use the windowrulev2 `maxsize` for file picker (although I think this shouldn't be needed).

**Comment by MightyPlaza** [comment]
> I changed it to binde and back to bindm, but the result was I could not expand the window with a double click until reboot.

not sure what you mean by "expand the window"

> Firefox fullscreen issue

not sure what you mean by this, but if you're talking about the firefox bar on fullscreen, that's how it work and is not even controled by hyprland


> resize or use the windowrulev2 `maxsize` for file picker

I still don't understand how you can resize it, you either broke your config or are doing it wrong, just tested on my laptop and resizing works
what laptop are you using?

**Comment by kaii-lb** [comment]
> not sure what you mean by "expand the window"

when you double click on the titlebar of a window it goes floating mode, and maximizes

**Comment by MightyPlaza** [comment]
what title bar, is this part of some plugin?

**Comment by kaii-lb** [comment]
no like in a GTK app, the top bar where the window controls are present, thats the "titlebar"

**Comment by kojq** [comment]
I've been able to resize on trackpad via:

```
general {
    resize_on_border = true
}
```

`bindm = WIN, mouse:273, resizewindow` does not work (as intended?) on trackpad, but it works fine with a mouse.

I also still don't understand why file picker is absurdly large by default.

**Comment by MightyPlaza** [comment]
the mod key is not `WIN` is super

the default size is not very large is ~ 1280x720 on what I'm guessing is a 1080p display with scaling (hyprland monitor config)

could firefox take scaling into account for the default window size, probably, but it's not hard to get around since you only have to resize it once

even if you couldn't, you could still use hyprland window rules to fix it despite it not being a hyprland issue

**Comment by kojq** [comment]
`SUPER/WIN/LOGO/MOD4` all work according to https://wiki.hyprland.org/Configuring/Variables/.

I've tried on two laptops using Arch Linux. That's how it always displays by default for me.

**Comment by MightyPlaza** [comment]
`monitor=,preferred,auto,1` setting scaling as 1 will probably make it work as intended, if note make a window rule
the only issue I see here is the trackpad not working for some reason

**Comment by kojq** [comment]
Ah, so auto scaling caused this.

For the trackpad not working part, all I know is that `bindm = SUPER, mouse:273, resizewindow` does not "work" while `resize_on_border = true` in the `general` section is a reasonable alternative for me.

**Comment by kojq** [comment]
It seems correct, as I have the cursor animation. I cannot perform the action though.

**Comment by MightyPlaza** [comment]
can you send a video. that's really strange

**Comment by kojq** [comment]
![uh](https://github.com/hyprwm/Hyprland/assets/106934605/81e8797a-34bc-4fba-89fd-aa979c24f8f1)

**Comment by kojq** [comment]
This was before `tap-and-drag`. I can add that, but I don't think there was a difference. I can't drag the cursor while holding down.

**Comment by MightyPlaza** [comment]
you're letting go
you need to keep the key pressed and drag the mouse

**Comment by kojq** [comment]
I let go some of the times. If I don't let go, it lets go for me itself.

**Comment by MightyPlaza** [comment]
it isn't supposed to
are you pressing down the right button on the trackpad while dragging it?

**Comment by kojq** [comment]
I don't recall if I tried physical press, but I can do that. I can also do double tap and hold to right click (preferred way).

**Comment by MightyPlaza** [comment]
physical press is needed by default
maybe you can do it the way you want, but idk https://wiki.hyprland.org/Configuring/Variables/#touchpad

**Comment by kojq** [comment]
Alright, thanks for the discussion. If it makes sense to do a feature request for doing this via something like a two finger tap, I'll do that. I'll close the issue in a day or so if no one has anything to add.
