### ISSUE TITLE
windows don't display well when the monitor is scaled

### ISSUE THREAD

**Issue by fdev31** [hyprwm/Hyprland#2920]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2

### Bug or Regression?

Bug

### Description

Having such configuration:
```
monitor=,preferred,auto,1
monitor=eDP-1,preferred,auto,1.2
```
When I open a window I often need to switch it fullscreen and back to have it displayed correctly. Else it shows a bit zoomed-in and cropped, mouse actions don't match with the display.
It's even more noticeable with XWayland floating windows.

### How to reproduce

- Scale a monitor
- focus it
- open a window

Example apps: Brave using wayland, Blender (Xwayland)

**Comment by idlip** [comment]
Same issue here.

And it is duplicate of #2588 , if Im not wrong.

**Comment by fdev31** [comment]
Are you sure ? I have this issue only when it's scaled and I see no mention to scaling or any specific monitor setting there... but indeed the symptom is similar, so I'm closing it since it is referred there anyway.
