### ISSUE TITLE
hyprctl `-j` option doesn't output valid json

### ISSUE THREAD

**Issue by lukeemhigh** [hyprwm/Hyprland#2921]
### Hyprland Version

adding version Hyprland, built from branch main at commit ec269622fcd1fd06d2db19d98593ffab8ff041cb dirty (flake.lock: update xdph). Tag: v0.28.0-23-gec269622  flags: (if any)

### Bug or Regression?

Bug

### Description

I apologize if this ends up being a regression and not a bug, I never encountered this problem before updating Hyprland today.
When using `hyprctl <command> -j`, the first line of output breaks the json syntax.
For example, the output of `hyprctl monitors -j` is the following:

```bash
adding monitors
[{
    "id": 0,
    "name": "eDP-1",
    "description": "Chimei Innolux Corporation 0x1515 (eDP-1)",
    "make": "Chimei Innolux Corporation",
    "model": "0x1515",
    "serial": "",
    "width": 1920,
    "height": 1080,
    "refreshRate": 60.007999,
    "x": 1920,
    "y": 0,
    "activeWorkspace": {
        "id": 1,
        "name": "1"
    },
    "specialWorkspace": {
        "id": 0,
        "name": ""
    },
    "reserved": [0, 35, 0, 0],
    "scale": 1.00,
    "transform": 0,
    "focused": true,
    "dpmsStatus": true,
    "vrr": false
}]
```
Or using `hyprctl version -j`:

```bash
adding version
{
    "branch": "main",
    "commit": "ec269622fcd1fd06d2db19d98593ffab8ff041cb",
    "dirty": true,
    "commit_message": "flake.lock: update xdph",
    "tag": "v0.28.0-23-gec269622",
    "flags": []
}
```

This creates multiple issues when trying to pipe the output of `hyprctl <command> -j` with tools like `jq`, unless the output has ben sanitized.

### How to reproduce

1. Install Hyprland
2. Try to query any json output from `hyprctl` with `jq` (e.g.: `hyprctl monitors -j | jq -rc '[ .[].id ] | sort_by( . )` )

**Comment by vaxerski** [comment]
ah fuck I left that debug log in really

**Comment by vaxerski** [comment]
fixd
