### ISSUE TITLE
blackscreen after startup

### ISSUE THREAD

**Issue by gfhdhytghd** [hyprwm/Hyprland#2923]
### Hyprland Version

0.27.2

### Bug or Regression?

Bug

### Description

black screen after startup
Thinkpad T60,T5500 ATI GPU,3+120

### How to reproduce

try use hyprland on some old thing

### Crash reports, logs, images, videos

[hyprlandCrashReport357.txt](https://github.com/hyprwm/Hyprland/files/12299173/hyprlandCrashReport357.txt)

https://1drv.ms/v/s!AvKideWdko8ngbVCuzK4_zu6hW9FLA

![IMG_0276](https://github.com/hyprwm/Hyprland/assets/102898587/02b44e69-19fe-4444-ad01-43b62177ab2c)

**Comment by kaii-lb** [comment]
you sure you have all graphics drivers installed? i don't know if the linux kernel bundles ATI drivers with it.

**Comment by gfhdhytghd** [comment]
I use archinstall to install the system and choose the "ATI/AMD" choice, and KDE plasm wayland run well on my computer

**Comment by gfhdhytghd** [comment]
after swich to hyprland-legacyrender, the problem fixed!

**Comment by gfhdhytghd** [comment]
Humm it is running but with some render problem

**Comment by MightyPlaza** [comment]
iirc there might be some rendering issues when using legacy render (https://wiki.hyprland.org/Getting-Started/Installation/#custom-installation-legacy-renderer-etc)

**Comment by gfhdhytghd** [comment]
It is something like, when I am in a clean workspace, everything work well,all animations(WiFi and mako) work on full frame, but if I open any window(kate,Vivaldi,konsole,dolphin,etc), the global fps suddenly drop to about ten, even just moving mouse is very stuck, and when I switch to another clean workspace, everything work well again,also there are some black square flashing on some app like thunar and konsole.

**Comment by gfhdhytghd** [comment]
T5500,ATI x1300,3gb ddr2, 120g hdd,no vram

when using Hyprland with a konsole open
but no command running, cpu 5%, ram 30% HDD 1%, unable to see gpu usage but I promise it is not run in full speed, and the fps is low

**Comment by gfhdhytghd** [comment]
Full fps when the same scene happened in plasm

**Comment by MightyPlaza** [comment]
1) https://www.techpowerup.com/gpu-specs/radeon-x1300.c947 256MB of vram
2) use nvtop for gpu usage
3) get a newer version of hyprland for better performance
4) maybe turn blur off or the number of passes down if the gpu is struggling

**Comment by gfhdhytghd** [comment]
Sorry I miss understand what vram is, I thought that was swap

nvtop:No GPU to monitor

version is newest

blur was already off

**Comment by MightyPlaza** [comment]
0.28.0 is newest arch repo hasn't been updated for some reason


> nvtop:No GPU to monitor

this probably means gpu isn't working properly
like I said above it's likely you need to use mesa-amber instead of mesa due to the gpu's age

**Comment by gfhdhytghd** [comment]
If I switch to mesa-amber, hyprland will just stop working

**Comment by gfhdhytghd** [comment]
I will try build the version 28

**Comment by gfhdhytghd** [comment]
![Uploading IMG_0750.jpeg…]()

**Comment by gfhdhytghd** [comment]
m_sWLRRenserer wall null

**Comment by MightyPlaza** [comment]
send output of `sudo lspci -v`

**Comment by gfhdhytghd** [comment]
00:00.0 Host bridge: Intel Corporation Mobile 945GM/PM/GMS, 943/940GML and 945GT Express Memory Controller Hub (rev 03)
        Subsystem: Lenovo ThinkPad T60
        Flags: bus master, fast devsel, latency 0
        Capabilities: [e0] Vendor Specific Information: Len=09 <?>
        Kernel modules: intel_agp

00:01.0 PCI bridge: Intel Corporation Mobile 945GM/PM/GMS, 943/940GML and 945GT Express PCI Express Root Port (rev 03) (prog-if 00 [Normal decode])
        Subsystem: Lenovo Mobile 945GM/PM/GMS, 943/940GML and 945GT Express PCI Express Root Port
        Flags: bus master, fast devsel, latency 0, IRQ 24
        Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
        I/O behind bridge: 2000-2fff [size=4K] [16-bit]
        Memory behind bridge: ee100000-ee1fffff [size=1M] [32-bit]
        Prefetchable memory behind bridge: d8000000-dfffffff [size=128M] [32-bit]
        Capabilities: [88] Subsystem: Lenovo Mobile 945GM/PM/GMS, 943/940GML and 945GT Express PCI Express Root Port
        Capabilities: [80] Power Management version 2
        Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [a0] Express Root Port (Slot+), MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [140] Root Complex Link
        Kernel driver in use: pcieport

00:1b.0 Audio device: Intel Corporation NM10/ICH7 Family High Definition Audio Controller (rev 02)
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, fast devsel, latency 0, IRQ 31
        Memory at ee400000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: [50] Power Management version 2
        Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [130] Root Complex Link
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

00:1c.0 PCI bridge: Intel Corporation NM10/ICH7 Family PCI Express Port 1 (rev 02) (prog-if 00 [Normal decode])
        Subsystem: Lenovo ThinkPad R60e
        Flags: bus master, fast devsel, latency 0, IRQ 25
        Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
        I/O behind bridge: 3000-3fff [size=4K] [16-bit]
        Memory behind bridge: ee000000-ee0fffff [size=1M] [32-bit]
        Prefetchable memory behind bridge: c0000000-c01fffff [size=2M] [32-bit]
        Capabilities: [40] Express Root Port (Slot+), MSI 00
        Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [90] Subsystem: Lenovo ThinkPad R60e
        Capabilities: [a0] Power Management version 2
        Capabilities: [100] Virtual Channel
        Capabilities: [180] Root Complex Link
        Kernel driver in use: pcieport

00:1c.1 PCI bridge: Intel Corporation NM10/ICH7 Family PCI Express Port 2 (rev 02) (prog-if 00 [Normal decode])
        Subsystem: Lenovo ThinkPad R60e
        Flags: bus master, fast devsel, latency 0, IRQ 26
        Bus: primary=00, secondary=03, subordinate=03, sec-latency=0
        I/O behind bridge: 4000-5fff [size=8K] [16-bit]
        Memory behind bridge: ec000000-edffffff [size=32M] [32-bit]
        Prefetchable memory behind bridge: e4000000-e40fffff [size=1M] [32-bit]
        Capabilities: [40] Express Root Port (Slot+), MSI 00
        Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [90] Subsystem: Lenovo ThinkPad R60e
        Capabilities: [a0] Power Management version 2
        Capabilities: [100] Virtual Channel
        Capabilities: [180] Root Complex Link
        Kernel driver in use: pcieport

00:1c.2 PCI bridge: Intel Corporation NM10/ICH7 Family PCI Express Port 3 (rev 02) (prog-if 00 [Normal decode])
        Subsystem: Lenovo ThinkPad R60e
        Flags: bus master, fast devsel, latency 0, IRQ 27
        Bus: primary=00, secondary=04, subordinate=0b, sec-latency=0
        I/O behind bridge: 6000-7fff [size=8K] [16-bit]
        Memory behind bridge: e8000000-e9ffffff [size=32M] [32-bit]
        Prefetchable memory behind bridge: e4100000-e41fffff [size=1M] [32-bit]
        Capabilities: [40] Express Root Port (Slot+), MSI 00
        Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [90] Subsystem: Lenovo ThinkPad R60e
        Capabilities: [a0] Power Management version 2
        Capabilities: [100] Virtual Channel
        Capabilities: [180] Root Complex Link
        Kernel driver in use: pcieport

00:1c.3 PCI bridge: Intel Corporation NM10/ICH7 Family PCI Express Port 4 (rev 02) (prog-if 00 [Normal decode])
        Subsystem: Lenovo ThinkPad R60e
        Flags: bus master, fast devsel, latency 0, IRQ 28
        Bus: primary=00, secondary=0c, subordinate=13, sec-latency=0
        I/O behind bridge: 8000-9fff [size=8K] [16-bit]
        Memory behind bridge: ea000000-ebffffff [size=32M] [32-bit]
        Prefetchable memory behind bridge: e4200000-e42fffff [size=1M] [32-bit]
        Capabilities: [40] Express Root Port (Slot+), MSI 00
        Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [90] Subsystem: Lenovo ThinkPad R60e
        Capabilities: [a0] Power Management version 2
        Capabilities: [100] Virtual Channel
        Capabilities: [180] Root Complex Link
        Kernel driver in use: pcieport

00:1d.0 USB controller: Intel Corporation NM10/ICH7 Family USB UHCI Controller #1 (rev 02) (prog-if 00 [UHCI])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0, IRQ 16
        I/O ports at 1800 [size=32]
        Kernel driver in use: uhci_hcd

00:1d.1 USB controller: Intel Corporation NM10/ICH7 Family USB UHCI Controller #2 (rev 02) (prog-if 00 [UHCI])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0, IRQ 17
        I/O ports at 1820 [size=32]
        Kernel driver in use: uhci_hcd

00:1d.2 USB controller: Intel Corporation NM10/ICH7 Family USB UHCI Controller #3 (rev 02) (prog-if 00 [UHCI])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0, IRQ 18
        I/O ports at 1840 [size=32]
        Kernel driver in use: uhci_hcd

00:1d.3 USB controller: Intel Corporation NM10/ICH7 Family USB UHCI Controller #4 (rev 02) (prog-if 00 [UHCI])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0, IRQ 19
        I/O ports at 1860 [size=32]
        Kernel driver in use: uhci_hcd

00:1d.7 USB controller: Intel Corporation NM10/ICH7 Family USB2 EHCI Controller (rev 02) (prog-if 20 [EHCI])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0, IRQ 19
        Memory at ee404000 (32-bit, non-prefetchable) [size=1K]
        Capabilities: [50] Power Management version 2
        Capabilities: [58] Debug port: BAR=1 offset=00a0
        Kernel driver in use: ehci-pci

00:1e.0 PCI bridge: Intel Corporation 82801 Mobile PCI Bridge (rev e2) (prog-if 01 [Subtractive decode])
        Subsystem: Lenovo ThinkPad R60e
        Flags: bus master, fast devsel, latency 0
        Bus: primary=00, secondary=15, subordinate=18, sec-latency=32
        I/O behind bridge: a000-dfff [size=16K] [16-bit]
        Memory behind bridge: e4300000-e7ffffff [size=61M] [32-bit]
        Prefetchable memory behind bridge: e0000000-e3ffffff [size=64M] [32-bit]
        Capabilities: [50] Subsystem: Lenovo ThinkPad R60e

00:1f.0 ISA bridge: Intel Corporation 82801GBM (ICH7-M) LPC Interface Bridge (rev 02)
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0
        Capabilities: [e0] Vendor Specific Information: Len=0c <?>
        Kernel driver in use: lpc_ich
        Kernel modules: intel_rng, lpc_ich, leds_ss4200

00:1f.1 IDE interface: Intel Corporation 82801G (ICH7 Family) IDE Controller (rev 02) (prog-if 8a [ISA Compatibility mode controller, supports both channels switched to PCI native mode, supports bus mastering])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, medium devsel, latency 0, IRQ 16
        I/O ports at 01f0 [size=8]
        I/O ports at 03f4
        I/O ports at 0170 [size=8]
        I/O ports at 0374
        I/O ports at 1880 [size=16]
        Kernel driver in use: ata_piix
        Kernel modules: ata_piix, pata_acpi, ata_generic

00:1f.2 SATA controller: Intel Corporation 82801GBM/GHM (ICH7-M Family) SATA Controller [AHCI mode] (rev 02) (prog-if 01 [AHCI 1.0])
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 29
        I/O ports at 18c8 [size=8]
        I/O ports at 18ac [size=4]
        I/O ports at 18c0 [size=8]
        I/O ports at 18a8 [size=4]
        I/O ports at 18b0 [size=16]
        Memory at ee404400 (32-bit, non-prefetchable) [size=1K]
        Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [70] Power Management version 2
        Kernel driver in use: ahci

00:1f.3 SMBus: Intel Corporation NM10/ICH7 Family SMBus Controller (rev 02)
        Subsystem: Lenovo ThinkPad R60/T60/X60 series
        Flags: medium devsel, IRQ 23
        I/O ports at 18e0 [size=32]
        Kernel driver in use: i801_smbus
        Kernel modules: i2c_i801

01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV515/M52 [Mobility Radeon X1300] (prog-if 00 [VGA controller])
        Subsystem: Lenovo RV515/M52 [Mobility Radeon X1300]
        Flags: bus master, fast devsel, latency 0, IRQ 16
        Memory at d8000000 (32-bit, prefetchable) [size=128M]
        I/O ports at 2000 [size=256]
        Memory at ee100000 (32-bit, non-prefetchable) [size=64K]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [50] Power Management version 2
        Capabilities: [58] Express Legacy Endpoint, MSI 00
        Capabilities: [80] MSI: Enable- Count=1/1 Maskable- 64bit+
        Kernel driver in use: radeon
        Kernel modules: radeon, amdgpu

02:00.0 Ethernet controller: Intel Corporation 82573L Gigabit Ethernet Controller
        Subsystem: Lenovo ThinkPad T60
        Physical Slot: 2
        Flags: bus master, fast devsel, latency 0, IRQ 30
        Memory at ee000000 (32-bit, non-prefetchable) [size=128K]
        I/O ports at 3000 [size=32]
        Capabilities: [c8] Power Management version 2
        Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [e0] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 00-15-58-ff-ff-2d-20-43
        Kernel driver in use: e1000e
        Kernel modules: e1000e

03:00.0 Network controller: Intel Corporation PRO/Wireless 3945ABG [Golan] Network Connection (rev 02)
        Subsystem: Intel Corporation ThinkPad R60e
        Physical Slot: 3
        Flags: bus master, fast devsel, latency 0, IRQ 32
        Memory at edf00000 (32-bit, non-prefetchable) [size=4K]
        Capabilities: [c8] Power Management version 2
        Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [e0] Express Legacy Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 00-19-d2-ff-ff-07-1a-cf
        Kernel driver in use: iwl3945
        Kernel modules: iwl3945

15:00.0 CardBus bridge: Texas Instruments PCI1510 PC card Cardbus Controller
        Subsystem: Lenovo ThinkPad T60/R60 series
        Physical Slot: 1
        Flags: bus master, medium devsel, latency 168, IRQ 16
        Memory at e4300000 (32-bit, non-prefetchable) [size=4K]
        Bus: primary=15, secondary=16, subordinate=17, sec-latency=176
        Memory window 0: e0000000-e3ffffff (prefetchable)
        Memory window 1: c4000000-c7ffffff
        I/O window 0: 0000a000-0000a0ff
        I/O window 1: 0000a400-0000a4ff
        16-bit legacy interface ports at 0001
        Capabilities: [a0] Power Management version 2
        Kernel driver in use: yenta_cardbus
        Kernel modules: yenta_socket

**Comment by MightyPlaza** [comment]
> Kernel driver in use: radeon

you're using a driver that's provided by mesa amber https://wiki.archlinux.org/title/OpenGL

**Comment by gfhdhytghd** [comment]
thanks let me check

**Comment by gfhdhytghd** [comment]
I have checked, that is just a tag but not what you are exactly using, even you are using a modern and gpu it may also shown as readon

**Comment by gfhdhytghd** [comment]
The gpu driver is installed by arch install and it work well in KDE plasma so I don’t think it is the problem of driver

**Comment by MightyPlaza** [comment]
what happens when you use mesa-amber and run nvtop in the tty, does the gpu appear?

**Comment by gfhdhytghd** [comment]
I think I found the problem, after I shut down swww, everything goes smoothly

**Comment by MightyPlaza** [comment]
nvtop is not just for nvidia, not sure if radeontop will work on older gpu's

**Comment by gfhdhytghd** [comment]
I think I found the real problem, I need to shut down all the “shadow” things

**Comment by gfhdhytghd** [comment]
Also the border rander cause some performance problem

**Comment by gfhdhytghd** [comment]
I would like to know how could I disable the color change gradually of the active window border and the inactive border

**Comment by gfhdhytghd** [comment]
Ok I found it

**Comment by MightyPlaza** [comment]
why is this open?
