### ISSUE TITLE
Crashes unexpectedly while typing with Fcitx5 in Chromium/Electron

### ISSUE THREAD

**Issue by vikoprez** [hyprwm/Hyprland#2926]
### Hyprland Version

Built from branch  at commit v0.25.0 (). Tag: ? flags: (if any): debug

### Bug or Regression?

Bug

### Description

I got Hyprland crashed randomly while typing with Fcitx5 using another input method than the default in Chromium and Electron applications (Brave and Discord/Webcord for more specific) on NixOS. Brave crashes regardless of using `--gtk-version-4` or `--enable-wayland-ime` flag for it, Electron apps are obviously using later flag. It mostly crashes when I suddenly edit a text after a while, after switching from other tabs or windows.

### How to reproduce

1. Open a website that has input box and type something
2. Switch to other tabs/windows for a while and go back
3. Getting crashed to the login manager

### Crash reports, logs, images, videos

[hyprlandCrashReport1665.txt](https://github.com/hyprwm/Hyprland/files/12304733/hyprlandCrashReport1665.txt)
[hyprlandCrashReport11664.txt](https://github.com/hyprwm/Hyprland/files/12304736/hyprlandCrashReport11664.txt)

**Comment by MightyPlaza** [comment]
v0.25 ???

**Comment by vikoprez** [comment]
Haha, I'm a little lazy switching over flakes to get latest build than the one in NixOS's stable channel stucking at v0.25, but I did not see any fixes related to my issue from forward builds neither. Should be done upgrading to v0.28 in next few hours and report back if it's happen to be fixed.

**Comment by vikoprez** [comment]
I think my bug is caused by the combination of Hyprland + Waybar + Fcitx5 and there is already an opened issue, just in a different way, as when Waybar is not running the reproduced steps don't make it crash.
