### ISSUE TITLE
SDL2 program crashes Hyprland (doesn't happen through xwayland)

### ISSUE THREAD

**Issue by jacekpoz** [hyprwm/Hyprland#2927]
### Hyprland Version

Hyprland, built from branch  at commit d7209b90bb8d866a641a49f815481fa9bc323105  (). Tag: ?  flags: (if any) debug debug

### Bug or Regression?

Bug

### Description

happens in both debug and normal builds

with `SDL_VIDEODRIVER=x11` the wall texture gets replaced by the healthkit texture and the game does freeze but I can still do anything else in Hyprland and sometimes the game even recovers

I can't get a crash report in the debug build, the hyprland log and coredump are both from the debug build but I managed to get a crash report in the normal build, attached all of those

not sure if this is in any way connected to the crash or if it helps you out, but when running ezquake wayland native at first my cursor gets stuck in the top left corner, when I refocus (go to another workspace and then back) it isn't stuck but the game doesn't capture it, then the 2nd time I refocus it all works; running ezquake through xwayland it all just works

### How to reproduce

install ezquake (only tested the appimage)

get the .pak files, put them into `$ezquake_dir/id1`

run ezquake, open the console (~) and run `map dm3`

without doing anything, open the console again if it closed and run `r_drawflat 1`

the wall texture should be replaced by a wiggling and flickering healthkit texture (only tested on amd, this happens on x11, xwayland and wayland, not sure about nvidia)

at that point just do some random stuff in game, run around, shoot, jump, whatever

after a while the game will freeze, you won't be able to switch ttys or do anything in Hyprland

wait a few seconds, you should be able to switch ttys and move the mouse cursor, besides that you can't do anything in Hyprland

wait for the crash

### Crash reports, logs, images, videos

(can't drag and drop the files from pcmanfm, firefox crashes so I'm posting the links)

hyprland debug log: https://0x0.st/H_pU.log
hyprland debug coredump: https://0x0.st/H_p0.txt
hyprland normal crash report: https://0x0.st/H_pG.txt

**Comment by jacekpoz** [comment]
also I got [this](https://files.catbox.moe/a9awka.jpg) twice, the first time I couldn't do anything besides pressing the power button, the second it somehow recovered and I was back at my login manager

**Comment by jacekpoz** [comment]
oh and my config is [here](https://codeberg.org/jacekpoz/niksos/src/branch/master/homes/jacek/gui/hypr.nix)

**Comment by jacekpoz** [comment]
tried it on sway from da flake and on weston from nixpkgs

sway hangs for a bit but does survive the healthkit walls, game works fine after it recovers

later I tried killing the window, it did nothing, typing `quit` into quaketerm froze the game and sway but it didn't crash, I had to kill it with loginctl

weston crashed even faster than hyprland #ripbozo

**Comment by MightyPlaza** [comment]
still happening?

**Comment by jacekpoz** [comment]
tested it on this intel laptop and it seems fine, I'll test it on my amd machine when I have access to it

**Comment by jacekpoz** [comment]
seems to be working fine on amd too, will reopen if it comes back
