### ISSUE TITLE
Bad oclussion behaviour with pinned windows + slide workspace animation

### ISSUE THREAD

**Issue by burein-ita** [hyprwm/Hyprland#2928]
### Hyprland Version

Hyprland, built from branch main at commit d7209b90bb8d866a641a49f815481fa9bc323105 dirty (renderer: remember extents before removing a window and use them for dt). Tag: v0.28.0-25-gd7209b90  flags: (if any)

### Bug or Regression?

Bug

### Description

When using the `slide` or `slidevert` workspace animation and having `pinned` windows, switching workspace causes the default wallpaper to leak through squares matching the exact size of the pinned windows.

This only happens when the workspace has no tiled windows.

https://github.com/hyprwm/Hyprland/assets/131406764/b501fddc-29a3-4fe8-8d69-8b351d8d5a0d

### How to reproduce

\> set `slide` or `slidevert` workspace animation
\> pin a window
\> switch workspace
\> i see hypr-chan
\> cry

**Comment by vaxerski** [comment]
very rude of you to cry when you see hypr-chan. She's cute and always happy to see you! :)

anyways, fixed in 126792584fa4eb25f6c8e3b3eb6bfb00b58a787a
