### ISSUE TITLE
Completely disable hypr-chan

### ISSUE THREAD

**Issue by REALERvolker1** [hyprwm/Hyprland#2930]
### Description

I suggest a new bool config line, `disable_hypr_chan`. This will disable the random hyprchan that is displayed on the default background.

Personally I find it very strange how this wasn't added when hypr-chan was introduced.

**Comment by NotAShelf** [comment]
nah

**Comment by vaxerski** [comment]
hypr-chan is very sad from reading this.

**Comment by pechano** [comment]
There is probably an easier way, but if you build from source, you can edit the top line of this file:
`Hyprland/assets/meson.build`
 to not include the anime wallpapers, like this:
`wallpaper_types = ['']`

**Comment by jlkn** [comment]
```patch
diff --git a/assets/meson.build b/assets/meson.build
index ba2c77bd..2c37dbac 100644
--- a/assets/meson.build
+++ b/assets/meson.build
@@ -1,4 +1,4 @@
-wallpaper_types = ['', 'anime_', 'anime2_']
+wallpaper_types = ['']
 
 foreach type : wallpaper_types
   foreach size : [2, 4, 8]
```

**Comment by kojq** [comment]
What's wrong with `disable_hyprland_logo`?

**Comment by pechano** [comment]
> What's wrong with `disable_hyprland_logo`?

That also disables the normal logo. So you need something like hyprpaper to set the non-amine background as your wallpaper. Which is what I do now.

**Comment by burein-ita** [comment]
> > What's wrong with `disable_hyprland_logo`?
> 
> That also disables the normal logo. So you need something like hyprpaper to set the non-amine background as your wallpaper. Which is what I do now.

That closes the issue. No?

**Comment by pechano** [comment]
Yes, it was closed five days ago.

**Comment by pechano** [comment]
kek indeed

**Comment by meedstrom** [comment]
> (for the record I also support the option to disable hyprchan, but I am fine with this solution for now)

I am not fine with compiling from source.

Maybe the documentation can indicate that `disable_hyprland_logo` does the trick.

**Comment by fufexan** [comment]
I've made a PR that lets you disable Hyprchan, please test it if you're interested.

**Comment by janithcooray** [comment]
such betryal, hypr-chan will be sad

**Comment by Sbatushe** [comment]
> What's wrong with `disable_hyprland_logo`?

Because it's cringe to have a girl anime wallpaper bug appearing from nowhere while at work or (worse) work calls and meet

**Comment by Sbatushe** [comment]
This anime-thing "feature" should be disabled by default, or to not exist at all (personal opinion)

**Comment by Notarin** [comment]
Putting the "mascot" on your screen as a wallpaper is without a doubt a "feature".
I also find this very strange being the default behavior.
Wouldn't it make sense to have it in the auto-generated config but not in the official starting config (or potentially a config generator that allows you to easily opt out)?
I really just can't take this seriously when it defaults to cartoon imagery.
Please don't take me as shitting on the mascot, having a mascot is fine, but due to its artistic style having it presented to the user as default is strange.
It leaves me feeling as serious about this as I feel about among us OS.
Tomorrow when I wake up and I see Chrome-chan in my browser I'm losing it.

**Comment by vaxerski** [comment]
the default and autogenerated configs explicitly have the option to disable the mascot listed and commented to clarify.
![image](https://github.com/hyprwm/Hyprland/assets/43317083/8eb595b5-bd8d-445a-9116-9d850ec43fce)

**Comment by Notarin** [comment]
I appreciate the option to disable the anime wallpaper in the generated and default config, but that doesn't address the real issue: it's enabled by default. While the comment in the config is helpful, it doesn't mitigate the jarring experience of seeing it when first installing the software. My suggestion for a config generator wasn't aimed at making it easy to opt-out, but to avoid confronting users with an element that many may find inappropriate or unprofessional right from the start. This choice of default prevents the project's credibility for a broad range of users.

**Comment by AnotherRandomGitHubAccount** [comment]
Just wanted to add on to this: I'm in high school, was messing around in class using linux in a VM, and i tried out hyprland and everyone saw "hypr chan" on my computer, like wtf. please disable this by default. not all hyprland users are weebs, it was indeed a jarring experience for me.

**Comment by janithcooray** [comment]
> Just wanted to add on to this: I'm in high school, was messing around in class using linux in a VM, and i tried out hyprland and everyone saw "hypr chan" on my computer, like wtf. please disable this by default. not all hyprland users are weebs, it was indeed a jarring experience for me.

lesson learnt i guess, don't try hyprland on a VM in high school. 

anyway, i'm am too a weeb and i also think it should be disabled by default as these inconveniences will affect the popularity of hyprland.
lets also rename the option from `disable_hyprland_logo = false` to `chad_user = false`

**Comment by AnotherRandomGitHubAccount** [comment]
> lesson learnt i guess, don't try hyprland on a VM in high school.

How was i supposed to know the devs added an anime mascot since i last checked out the project! this is a wayland window manager / compositor, what kind of messed up default is displaying some kind of anime mascot!?! either your crazy or your trying to gatekeep Hyprland from people

**Comment by Notarin** [comment]
I Don't think accusing maintainers or "gatekeeping" Hyprland is the proper language to be using or a tone to hold, but the fact that this was added; pushing said default wallpaper to end users who have used their config and expect what they expect definitely compounds this issue to a degree.
