### ISSUE TITLE
any app with opacity will make the background look this bad

### ISSUE THREAD

**Issue by rxmmah** [hyprwm/Hyprland#2933]
### Hyprland Version

v0.28.0

### Bug or Regression?

Bug

### Description

the wallpaper is broken

### How to reproduce

i dont know

### Crash reports, logs, images, videos

![20230810_14h26m00s_grim](https://github.com/hyprwm/Hyprland/assets/115156210/c9740af0-819a-48bf-8beb-851762db0bf6)

**Comment by vaxerski** [comment]
driver bug. Looks like things that happen on asahi
