### ISSUE TITLE
togglesplit affects fullscreen apps

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2934]
### Hyprland Version

Hyprland, built from branch main at commit 126792584fa4eb25f6c8e3b3eb6bfb00b58a787a dirty (renderer: don't add workspace offset to pinned). Tag: v0.28.0-28-g12679258

### Bug or Regression?

Bug

### Description

Executing togglesplit on a fullscreen app shows where it would be if it weren't fullscreen.

### How to reproduce

1. Add the following binds:
```
bind=SUPER,tab,layoutmsg,togglesplit
bind=SUPER,F,fullscreen,
```

2. Open at least two tiled windows
3. Fullscreen one of them
4. Press SUPER,tab

### Crash reports, logs, images, videos

This image shows `foot` after triggering the bug with two tiled windows in that workspace.

![image](https://github.com/hyprwm/Hyprland/assets/44881120/b6d8b460-f8e7-46f6-aac1-dfbac204711f)

**Comment by vaxerski** [comment]
lol

**Comment by TheSunCat** [comment]
Agreed!

**Comment by MightyPlaza** [comment]
doesn't happen to me when using hyprctl disaptch
didn't test binds yet

**Comment by vaxerski** [comment]
e4e8ae8f885104bb948afa24f1cd9fc3bdb450e9
