### ISSUE TITLE
wlr-input-inhibitor support

### ISSUE THREAD

**Issue by fufexan** [hyprwm/Hyprland#2937]
### Description

[gtklock](https://github.com/jovanlanik/gtklock) depends on this protocol to keep the environment secure in case it crashes/gets killed.

**Comment by vaxerski** [comment]
IIRC it's been supported forever. I need a bug repro case if it's not working

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/assets/36706276/33ccaba4-0147-4a17-bb21-452d42decba5

**Comment by vaxerski** [comment]
how would gtklock use a protocol if it's killed? I don't see an issue?

**Comment by fufexan** [comment]
It uses it when it's launched. Killing it would then lock down Hyprland, just like `swaylock` does.

**Comment by vaxerski** [comment]
would it? does sway behave like that?

**Comment by fufexan** [comment]
Gonna check.

**Comment by fufexan** [comment]
Looks like gktlock behaves exactly the same on sway. Weird.

**Comment by q234rty** [comment]
Because it does not use ext-session-lock so killing it won't lock down the compositor, see https://github.com/jovanlanik/gtklock/issues/53

**Comment by fufexan** [comment]
Cool, let's hope it will be fixed soon.

**Comment by vaxerski** [comment]
input-inhibitor was never meant for the issue explained in the original post, so yes

**Comment by kfirufk** [comment]
any updates ?
```
$ gtklock 

** (gtklock:19059): CRITICAL **: 02:32:11.972: Your compositor doesn't support wlr-input-inhibitor
```

on gentoo linux ~amd64
hyprland 0.33.1
gtklock 2.1.0

**Comment by prometheaus** [comment]
> any updates ?
> 
> ```
> $ gtklock 
> 
> ** (gtklock:19059): CRITICAL **: 02:32:11.972: Your compositor doesn't support wlr-input-inhibitor
> ```
> 
> on gentoo linux ~amd64 hyprland 0.33.1 gtklock 2.1.0

i have the same issue since the latest update on arch linux

**Comment by vaxerski** [comment]
swaylock supports ext-session-lock. Update from your 2 years out-of-date fork.

wlr-input-inhibitor support was dropped in wlroots and hyprland because it's long deprecated.

**Comment by kfirufk** [comment]
swaylock with swayidle works amazing, thank you :)

**Comment by blauch** [comment]
same issue here as well on Manjaro. currently i am not able to lock my screen at all :( 

```
 $ gtklock 

** (gtklock:40293): CRITICAL **: 09:57:47.945: Your compositor doesn't support wlr-input-inhibitor
```

```
$ swaylock 
2023-12-14 09:57:43 - [main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely
```

**Comment by fufexan** [comment]
Gtklock no longer works. Please use swaylock or waylock.

**Comment by prometheaus** [comment]
> same issue here as well on Manjaro. currently i am not able to lock my screen at all :(
> 
> ```
>  $ gtklock 
> 
> ** (gtklock:40293): CRITICAL **: 09:57:47.945: Your compositor doesn't support wlr-input-inhibitor
> ```
> 
> ```
> $ swaylock 
> 2023-12-14 09:57:43 - [main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely
> ```

try swaylock-effects-git if you are using swaylock-effects. otherwise, regular swaylock works now but looks bad

**Comment by blauch** [comment]
@prometheaus many thanks for the hint! swaylock works again after replacing `swaylock-effects` with `swaylock-effects-git`  :tada:

**Comment by mdwalters** [comment]
i found a solution to the `** (gtklock:63438): CRITICAL **: 18:07:41.283: Your compositor doesn't support wlr-input-inhibitor` issue, it seems that running `gtklock` with the `-i` flag (makes `gtklock` not use `wlr-input-inhibitor`) makes it work again.

**Comment by Proximus888** [comment]
> i found a solution to the `** (gtklock:63438): CRITICAL **: 18:07:41.283: Your compositor doesn't support wlr-input-inhibitor` issue, it seems that running `gtklock` with the `-i` flag (makes `gtklock` not use `wlr-input-inhibitor`) makes it work again.

Thanks, works flawlessly. I cannot find any ```-i``` flag in the man pages or there github. Any idea what it does?
