### ISSUE TITLE
SecureCRT doesnt work on Hyperland

### ISSUE THREAD

**Issue by mairm1340** [hyprwm/Hyprland#2938]
### Hyprland Version

v0.27.2 Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

Unable to run the securecrt software. It works on all window managers except Hyprland.

### How to reproduce

On terminal when you run 
SecureCRT

We see the below error :

qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

**Comment by vaxerski** [comment]
`QT_QPA_PLATFORM=xcb securecrt`

Reading the error would've helped.

**Comment by mairm1340** [comment]
thank you so much.
