### ISSUE TITLE
Microsoft Teams screensharing

### ISSUE THREAD

**Issue by mairm1340** [hyprwm/Hyprland#2940]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

When I share screen, others only see blank screen

when I run the app from the terminal I get the below logs

[98612:0811/212127.432181:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[98612:0811/212127.432227:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[ERROR] connect ECONNREFUSED ::1:80
/usr/share/libdrm/amdgpu.ids: No such file or directory
[98788:0811/212129.295033:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[98788:0811/212141.688732:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[98788:0811/212144.854871:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[98790:0811/212145.747490:ERROR:socket_tcp.cc(317)] Error when reading from TCP socket: -101
[OpenH264] this = 0x0x27d016d0ad60, Warning:ParamValidationExt(), eSpsPpsIdStrategy setting (2) with iUsageType (1) not supported! eSpsPpsIdStrategy adjusted to CONSTANT_ID
[OpenH264] this = 0x0x27d016d0ad60, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x27d016d0ad60, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x27d016d0ad60, Warning:Actual input framerate 0.000000 is different from framerate in setting 13.000000, suggest to use other rate control modes

### How to reproduce

just launch teams and screensharing doesnt work

**Comment by vaxerski** [comment]
does it work under sway? looks like a teams issue

**Comment by mairm1340** [comment]
I tested on all other window mangers and it works
i can share teh screen
but on hyperland only I get this error

Is there a way I can disable wayland only for teams and check without logging out of hyprland

**Comment by vaxerski** [comment]
_window managers_? Have you tested any wayland compositors, like e.g. sway?

> Is there a way I can disable wayland only for teams and check without logging out of hyprland

Teams itself should decide what it's using. If it's electron, you have to manually pass flags to it to launch it in wayland, so remove those to launch it in xwayland. Screensharing will only work in native wayland, however.

**Comment by ferrreo** [comment]
The native linux teams app was discontinued, this means it's electron version is very old and is not being updated anymore so things like this will be a struggle.

You now should use the teams site and install it as a webapp from the url bar (it will also prompt you itself). 

Then as long as you have xdg-desktop-portal-hyprland installed and set up correctly it will just work.

It's working great here on hyprland.

**Comment by wilecoyote2015** [comment]
I also encountered this issue recently using Teams in the browser.
I tried it with Chromium and Firefox, both resulting in a black screen for the other participants.
`xdg-desktop-portal-hyprland 0.4.0-1` is installed.

**Comment by ferrreo** [comment]
> I also encountered this issue recently using Teams in the browser. I tried it with Chromium and Firefox, both resulting in a black screen for the other participants. `xdg-desktop-portal-hyprland 0.4.0-1` is installed.

You can try this test page to see if screen capture is working on your setup in general: https://mozilla.github.io/webrtc-landing/gum_test.html

Also make sure you follow the steps here:

https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

**Comment by mairm1340** [comment]
HI
quick update #
teams sharing did work for me on all window manager so I did not think it was a teams issue.
I did the following

Uninstalled teams to ensure I dont have any...
 sudo pacman -R teams-for-linux
 sudo snap remove teams-for-linux

Then I installed via snap 
 sudo snap install teams-for-linux
It had the same problem so uninstalled it
 sudo snap remove  teams-for-linux

Clone the latest one for AUR

 git clone https://aur.archlinux.org/ms-teams-for-linux-bin.git
 cd ms-teams-for-linux-bin
 ls
 makepkg -si
 teams-for-linux


Rebooted the computer and voila it works on hyprland

Just shared all the steps which helped me so that it can help others if they face similar one

**Comment by mairm1340** [comment]
resolved

**Comment by caulagi** [comment]
I can confirm the same behavior as well. Using teams from pacman (`1.5.00.2361-1`) doesn't let me share screens hyprland (`v0.27.2-62-g08651736`). But using teams classic from aur works for me.

I was able to share after this - 

```
$ sudo pacman -Rs teams
checking dependencies...

Packages (1) teams-1.5.00.23861-1

Total Removed Size:  273.86 MiB
...

$ yay -S ms-teams-for-linux-bin
AUR Explicit (1): ms-teams-for-linux-bin-1.3.5-1
:: (1/1) Downloaded PKGBUILD: ms-teams-for-linux-bin
  1 ms-teams-for-linux-bin                   (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/pcaulagi/.cache/yay/ms-teams-for-linux-bin
HEAD is now at b9e9599 added global link
  1 ms-teams-for-linux-bin                   (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
==> Making package: ms-teams-for-linux-bin 1.3.5-1 (Sun 10 Dec 2023 05:15:27 PM CET)
```

**Comment by blairMe** [comment]
> I can confirm the same behavior as well. Using teams from pacman (`1.5.00.2361-1`) doesn't let me share screens with hyprland (`v0.27.2-62-g08651736`). But using teams classic from aur works for me.
> 
> I was able to share screen downgrading teams like this -
> 
> ```
> $ sudo pacman -Rs teams
> checking dependencies...
> 
> Packages (1) teams-1.5.00.23861-1
> 
> Total Removed Size:  273.86 MiB
> ...
> 
> $ yay -S ms-teams-for-linux-bin
> AUR Explicit (1): ms-teams-for-linux-bin-1.3.5-1
> :: (1/1) Downloaded PKGBUILD: ms-teams-for-linux-bin
>   1 ms-teams-for-linux-bin                   (Build Files Exist)
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> A
> :: Deleting (1/1): /home/pcaulagi/.cache/yay/ms-teams-for-linux-bin
> HEAD is now at b9e9599 added global link
>   1 ms-teams-for-linux-bin                   (Build Files Exist)
> ==> Diffs to show?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> N
> ==> Making package: ms-teams-for-linux-bin 1.3.5-1 (Sun 10 Dec 2023 05:15:27 PM CET)
> ```


I'm trying your solution but I'm getting the error below - 

`❯ sudo pacman -Rs teams`
`[sudo] password for bird: `
`error: target not found: teams`

**Comment by bechampion** [comment]
This might be really old , but what i notice is that using `env XDG_SESSION_TYPE=wayland /usr/local/bin/teams` plus 
`xdg-desktop-portal` + `wireplumber` + `hyprpolkitagent` running ,   when i share my screen i get offerd monitors ,  windows and region . When i select any nothing happens ,*until*  i move the mouse in the  monitor/window im sharing , odd as , but it does work.
```
❯ /usr/local/bin/teams --version
1.12.7

~
❯ hyprland --version
Hyprland 0.51.1 built from branch  at commit 71a1216abcc7031776630a6d88f105605c4dc1c9  ([gha] Nix: update inputs).
```

**Comment by bechampion** [comment]
i also have these running 
```
❯ systemctl --user --state=running --type=service
  UNIT                                         LOAD   ACTIVE SUB     DESCRIPTION
  at-spi-dbus-bus.service                      loaded active running Accessibility services bus
  dbus-:1.20-org.a11y.atspi.Registry@0.service loaded active running dbus-:1.20-org.a11y.atspi.Registry@0.service
  dbus-broker.service                          loaded active running D-Bus User Message Bus
  dconf.service                                loaded active running User preferences database
  gnome-keyring-daemon.service                 loaded active running GNOME Keyring daemon
  gpg-agent.service                            loaded active running GnuPG cryptographic agent and passphrase cache
  gvfs-daemon.service                          loaded active running Virtual filesystem service
  gvfs-metadata.service                        loaded active running Virtual filesystem metadata service
  gvfs-udisks2-volume-monitor.service          loaded active running Virtual filesystem service - disk device monitor
  hyprpolkitagent.service                      loaded active running Hyprland Polkit Authentication Agent
  pipewire.service                             loaded active running PipeWire Multimedia Service
  pulseaudio.service                           loaded active running Sound Service
  wireplumber.service                          loaded active running Multimedia Service Session Manager
  xdg-desktop-portal-gtk.service               loaded active running Portal service (GTK/GNOME implementation)
  xdg-desktop-portal-hyprland.service          loaded active running Portal service (Hyprland implementation)
  xdg-desktop-portal.service                   loaded active running Portal service
  xdg-document-portal.service                  loaded active running flatpak document portal service
  xdg-permission-store.service                 loaded active running sandboxed app permission store

```
