### ISSUE TITLE
Float window rule not always working with Firefox Picture-in-Picture

### ISSUE THREAD

**Issue by giannilabella** [hyprwm/Hyprland#2942]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

Window rules with Firefox Picture-in-Picture works inconsistently

### How to reproduce

1. Using `Mozilla Firefox 116.0.2`
2. Open YouTube
3. Toggle `PiP` mode for a video
4. Window rule works and window float
5. Close `PiP` window
6. Toggle `PiP` mode again for a video
7. Window does not float

### Crash reports, logs, images, videos

My window rules (third one for debugging):
```
windowrulev2 = float, title:(Picture-in-Picture)
windowrulev2 = size 600 337.5, title:(Picture-in-Picture)
windowrulev2 = bordercolor rgb(FF0000), title:(Picture-in-Picture)
```

Hyprland logs:
```
[LOG] Searching for matching rules for firefox (title: Picture-in-Picture)
[LOG] Window rule float ->  title:(Picture-in-Picture) matched 55bce45b12b0 [Picture-in-Picture]
[LOG] Window rule size 600 337.5 ->  title:(Picture-in-Picture) matched 55bce45b12b0 [Picture-in-Picture]
[LOG] Window rule bordercolor rgb(FF0000) ->  title:(Picture-in-Picture) matched 55bce45b12b0 [Picture-in-Picture]
[LOG] Window 55bce45b12b0 set title to Picture-in-Picture
```

The windows when the rule worked (`hyprctl clients` command):
```
Window 55bce4549dc0 -> Picture-in-Picture:
	mapped: 1
	hidden: 0
	at: 1669,22
	size: 600,337
	workspace: 10 (10)
	floating: 1
	monitor: 1
	class: firefox
	title: Picture-in-Picture
	initialClass: firefox
	initialTitle: Picture-in-Picture
	pid: 63524
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

The windows when the rule didn't work  (`hyprctl clients` command):
```
Window 55bce4549dc0 -> Picture-in-Picture:
	mapped: 1
	hidden: 0
	at: 2712,22
	size: 931,1036
	workspace: 10 (10)
	floating: 0
	monitor: 1
	class: firefox
	title: Picture-in-Picture
	initialClass: firefox
	initialTitle: Firefox
	pid: 63524
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

I noticed that it works when the `initialTitle` is `Picture-in-Picture`, so it probably is Firefox's fault
If the `float` rule was dynamic like `bordercolor` it would work, but that could cause other problems I don't know

**Comment by MightyPlaza** [comment]
just in case you want to open an issue this started 2 releases before firefox 116.0.2-1

**Comment by danielwerg** [comment]
Not sure about vanilla Firefox since I don't use it, but here my window rules for LibreWolf:
```bash
# LibreWolf Picture-in-Picture
$librewolfPiPClass = LibreWolf
$librewolfPiPTitle = ^(Picture-in-Picture)$
windowrulev2 = float, class:$librewolfPiPClass, title:$librewolfPiPTitle
# Fix for Picture-in-Picture only floats once
$librewolfPiPInitialTitle = Firefox
windowrulev2 = float, class:$librewolfPiPClass, title:$librewolfPiPInitialTitle
```

shout-out to `hyprctl client`

related: #2943 #2876

**Comment by Sohail-XD** [comment]
Any fix?

**Comment by xav-ie** [comment]
Recent update caused it to not work the same. This works:
```
windowrulev2 = size 640 360, title:(Picture-in-Picture)
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 1906 14, title:(Picture-in-Picture)
windowrulev2 = float, title:^(Picture-in-Picture)$
```
Also, there is neat keybinding for Firefox PIP `Ctrl+Shift+{` puts video PIP.
