### ISSUE TITLE
Firefox Picture-in-Picture only floats once

### ISSUE THREAD

**Issue by morr0ne** [hyprwm/Hyprland#2943]
### Hyprland Version

adding version Hyprland, built from branch main at commit ec269622fcd1fd06d2db19d98593ffab8ff041cb dirty (flake.lock: update xdph). Tag: v0.28.0-23-gec269622  flags: (if any)

### Bug or Regression?

Bug

### Description

When using Firefox Picture-in-Picture mode to watch the video it only floats the first time, after closing the windows an opening again it is instead open as any other window. 
I'm pretty sure my config is correct, here is the relevant section:
```
windowrulev2 = float, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = nofullscreenrequest, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = nomaximizerequest, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = pin, class:(firefox),title:(Picture-in-Picture)
```

I'm also attaching the full config just in case
<details>
  <summary>hyprland.conf</summary>

```
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-1,1920x1080@165,0x0,1,

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Launch apps
exec-once = waybar & hyprpaper & mako
exec-once = gnome-keyring-daemon --start
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Input config
input {
    kb_layout = it,us # Sets the layout to italian
    kb_options = grp:win_space_toggle

    follow_mouse = 1

    touchpad {
        natural_scroll = yes # Inverts touchpad scroll
    }

    sensitivity = 0 # Don't change sensitivity
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    groupbar_titles_font_size = 9
    # render_titles_in_groupbar = false
    groupbar_gradients = false
    vrr = 1
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    # max_fps = 

    gaps_in = 0
    gaps_out = 5
    border_size = 0
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    # col.group_border = rgba(000000aa) 
    # col.group_border_active = rgba(000000ff)

    # layout = dwindle
}

animations {
    enabled = no

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = yes
}

decoration {
    # col.shadow = rgb(ff0000)
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mod, RETURN, exec, foot
bind = $mod SHIFT, Q, killactive, 
bind = $mod SHIFT, E, exit, 
bind = $mod, V, togglefloating, 
bind = $mod, D, exec, rofi -modi drun,run -show drun
bind = $mod, F, fullscreen,
bind = $mod, a, togglefloating,

# Move focus with mainMod + arrow keys
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Weird keyboard keys
binde =, XF86MonBrightnessDown, exec, brightnessctl set 5%-
binde =, XF86MonBrightnessUp, exec, brightnessctl set +5%
binde =, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
binde =, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind =, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind =, XF86AudioNext, exec, playerctl next
bind =, XF86AudioPrev, exec, playerctl previous

bindm=ALT,mouse:272,movewindow
bindm=ALT,mouse:273,resizewindow

# Scroll through existing workspaces with mainMod + scroll
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

bind = $mod SHIFT, right, workspace, e+1
bind = $mod SHIFT, left, workspace, e-1

windowrule = float, file_progress
windowrule = float, confirm
windowrule = float, dialog
windowrule = float, download
windowrule = float, notification
windowrule = float, error
windowrule = float, splash
windowrule = float, confirmreset
windowrule = float, title:Open File
windowrule = float, title:branchdialog
windowrule = float, Lxappearance
windowrule = float, Rofi
windowrule = animation none,Rofi
windowrule = float,viewnior
windowrule = float,feh
windowrule = float, pavucontrol-qt
windowrule = float, pavucontrol
windowrule = float, file-roller
windowrule = fullscreen, wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrule = idleinhibit focus, mpv
windowrule = idleinhibit fullscreen, firefox
windowrule = float, title:^(Media viewer)$
windowrule = float, title:^(Volume Control)$

windowrulev2 = float, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = nofullscreenrequest, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = nomaximizerequest, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = pin, class:(firefox),title:(Picture-in-Picture)

# tabbing
bind = $mod, w, togglegroup
bind = $mod, tab, changegroupactive, f
bind = $mod, Backslash, changegroupactive, b
bind = $mod, l, lockactivegroup, toggle

bind = $mod, s, exec, grim - | wl-copy
bind = $mod SHIFT, s, exec, grim -g "$(slurp)" - | wl-copy
```
</details>

### How to reproduce

Open any video on Firefox, right click and select Picture-in-Picture. Close the floating windows that open, Select Picture-in-Picture again. This time the window will act as any other window instead of floating. This will persist until Firefox is closed and reopened, then again only the first time will work.

### Crash reports, logs, images, videos

<details>
  <summary>What happens the first time</summary>

![image](https://github.com/hyprwm/Hyprland/assets/35099273/2145dae8-9207-4454-b10f-431d5ca7f25b)
</details>

<details>
  <summary>Then after closing the windows and clicking on pip again</summary>

![image](https://github.com/hyprwm/Hyprland/assets/35099273/eda13b54-3e46-4d0b-a7b2-700af178f293)
</details>

**Comment by MightyPlaza** [comment]
bruh

**Comment by morr0ne** [comment]
It is truly a weird issue, I'm kinda hoping there's something wrong with my config because this is driving me crazy. I'm not sure what kind of logs I should provide to help debug this issue, any advice is welcome.

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/issues/2942

**Comment by morr0ne** [comment]
> #2942

Well I didn't see that lol, I think we might have opened it at the same time

is there nothing that can be done? I'm not even sure what would cause this, how can firefox interfere with hyprland windowrules? Can they not be forced?

**Comment by vaxerski** [comment]
a recent firefox update sets the title you are targetting after opening the window, meaning hyprland doesnt catch it. (float is not dynamic)

**Comment by morr0ne** [comment]
> a recent firefox update sets the title you are targetting after opening the window, meaning hyprland doesnt catch it. (float is not dynamic)

While this is definitively caused by firefox but can it really be considered a bug? It doesn't seem that weird of a behavior for a program to change it's title after a window is already open. Wouldn't it be better for windowrules to support being applied dynamically? Is there a technical reason for that or is it simply not been implemented?

**Comment by vaxerski** [comment]
tile / float window rules are not dynamic because it's not implemented as it makes less sense than e.g. a dynamic border rule. It's absolutely doable, just never been requested properly.

**Comment by MightyPlaza** [comment]
this is easy to script by listening to the ipc for `windowtitle` events

**Comment by morr0ne** [comment]
> this is easy to script by listening to the ipc for `windowtitle` events

How would one go about doing that?. Would a script need to be running all the time in the background?

>tile / float window rules are not dynamic because it's not implemented as it makes less sense than e.g. a dynamic border rule. It's absolutely doable, just never been requested properly.

Should I open a feature request issue or is does that already exist?

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/IPC/

opening a feature request likely won't make it get implemented faster
the faster* and simpler solution is to open an issue on firefox's bug tracker

**Comment by vaxerski** [comment]
> opening a feature request likely won't make it get implemented faster

not opening a feature request on the other hand will make it 99.9% not get implemented lol

**Comment by morr0ne** [comment]
I wrote a simple program that literally only floats every single Firefox pip it finds, not ideal cause you can't stop it but in case anyone has the same problem here it is: https://github.com/morr0ne/pipfloat
