### ISSUE TITLE
`hyprctl hyprpaper` commands no longer work

### ISSUE THREAD

**Issue by shadeyg56** [hyprwm/Hyprland#2947]
### Hyprland Version

Hyprland, built from branch  at commit 3f7f4207a6dd8bd217c01514ea40e9e4b9b7874a  

### Bug or Regression?

Bug

### Description

This issue was already made in the hyprpaper repo [here](https://github.com/hyprwm/hyprpaper/issues/84) but it seems to be more related to hyprland. Every single `hyprctl hyprpaper` command returns `unknown request`

I am currently building hyprland from the NixOS flake

### How to reproduce

1. run any `hyprctl hyprpaper` command

for instance, running `hyprctl hyprpaper unload all` returns `unknown request`

**Comment by JustSimplyKyle** [comment]
It's most likely an Regression, so it can help if you can provide a faulty commit

**Comment by shadeyg56** [comment]
Yes, I should've marked it as a regression.

Looks like b68292340c910292b6df3d504c9ee706027d8407 is the fault commit

**Comment by Frontear** [comment]
Can confirm, just did a revert on that commit and built hyprland and the command worked. Looks like someone forgot to use `requestHyprpaper` :p

**Comment by vaxerski** [comment]
oops

**Comment by vaxerski** [comment]
apologies. 3fc4ac07e05da41149363f4c03ec6ae657a13f2c
