### ISSUE TITLE
No shadows when only

### ISSUE THREAD

**Issue by YingchangLiu** [hyprwm/Hyprland#2953]
### Description

There are two gaps between the bar and my left screen edge and the  window behind it. 

When the bar is not fully aligned with the window, the window shadow near the bar is visible, but not in the other three edges. It looks strange. 

Request a setting option ``` no_shadows_when_only ``` or adding it into ```no_gaps_when_only``` to eliminate shadows when there is only one window.

**Comment by MightyPlaza** [comment]
I think I enabled this because otherwise group bar would not be visible which, in my opinion, is even worse than only having shadows at the top.

I'll see if I can disable it again without totally disabling decorations
