### ISSUE TITLE
key_press_enables_dpms = yes makes screen turn on immediately

### ISSUE THREAD

**Issue by pescepalla** [hyprwm/Hyprland#2954]
### Hyprland Version

0.28.0

### Bug or Regression?

Bug

### Description

I'm not sure why, but `key_press_enables_dpms` immediately turns dpms on. If I launch from the terminal, a number of phantom  returns are registered following the command (I did not touch the keyboard).

These phantom returns are not present if `key_press_enables_dpms = off`.

### How to reproduce

Launch `hyprctl dispatch dpms off` with `key_press_enables_dpms = on`.

### Crash reports, logs, images, videos

![2023-08-12-175348_hyprshot](https://github.com/hyprwm/Hyprland/assets/46329185/8a480375-cce0-40ac-ab46-0e6aacc088ea)

**Comment by vaxerski** [comment]
you mean turns dpms on?

**Comment by pescepalla** [comment]
WithI `key_press_enables_dpms = yes`, I expect `hyprctl dispatch dpms off` to turn my screen off until:

- I pass `hyprctl dispatch dpms on` or,
- I press a button

Instead this does not happen. The screen turns off but it turns on almost immediately and the terminal shows that some returns have been typed.

If I `key_press_enables_dpms = no`, when I turn on the screen again (e.g. by moving the mouse with `mouse_move_enables_dpms = yes`), those returns are not there.

**Comment by pescepalla** [comment]
Here's my config if needed: https://gitlab.com/alemacilenti/dotfiles/-/tree/main/hyprland.stellaris/.config/hypr?ref_type=heads

**Comment by vaxerski** [comment]
simple. The key up event that is sent after you hit enter to execute dpms off turns the dpms back on. do sleep 1 && hyprctl dispatch ... and it will work as you expect it

**Comment by pescepalla** [comment]
Fantastic. Thanks, closing.
