### ISSUE TITLE
swayidle is notified that the system is idle when mouse is moving

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/Hyprland#2955]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

swayidle is notified that the system is idle when mouse is moving around the wallpaper.

### How to reproduce

1. Configure hyprland:
`exec-once = swayidle -w timeout 10 'hyprctl dispatch dpms off'`
2. Run hyprland.
3. Move mouse around the screen (do not press any buttons) and wait for 10 seconds.
4. The screen goes blank despite the system is not idle. I know, no useful work is done by the user, but the system is definitely not idle.

**Comment by Frontear** [comment]
first off youre on an old build of hyprland. update and reproduce the issue

**Comment by akdevservices** [comment]
Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty ().
Tag: v0.28.0
flags: (if any)

The bug is still there.

**Comment by vaxerski** [comment]
should be fixado in 0220e4c1eac1f797e3c3406e0e92d4311ce8090c
