### ISSUE TITLE
window wrong size when opening second window on master layout

### ISSUE THREAD

**Issue by uoou** [hyprwm/Hyprland#2957]
### Hyprland Version

Hyprland, built from branch main at commit 739598717bbff79aad8599dcd0ca7a423682482a dirty (remove shadow no_gaps_when_only (2956)). Tag: v0.28.0-36-g73959871

### Bug or Regression?

Bug

### Description

This only happens on master layout and when `no_gaps_when_only = 1` and gaps are present.

When an existing window is open, opening a second window causes the first window to be incorrectly sized. The original window seems to have the border width added to its dimensions.

This happens with most applications I've tested with, for example qutebrowser, chromium, firefox and foot all exhibit this. It does not happen if the second window is kitty (regardless of what the other window is).

The problem is corrected if I switch workspaces, open a third window or, as I just discovered, take a screenshot with grim.

I'm attaching a screenshot where I've set gaps and borders big to make the problem more obvious.

I hope this makes sense, it's a little tricky to explain.

I'll gladly provide more info if required, there's nothing exotic in my configs, and I'm using hyprland-git from the AUR.

### How to reproduce

- use master layout
- set `no_gaps_when_only = 1`
- set gaps and borders to something chunky to make the problem obvious
- open (for example) foot twice

### Crash reports, logs, images, videos

![2023-08-13_005216_904400879](https://github.com/hyprwm/Hyprland/assets/5243056/f21090c3-8853-43ff-925a-425858b1c42d)

**Comment by MightyPlaza** [comment]
cannot repro with foot, are you by any chance setting a border workspace rule?

**Comment by uoou** [comment]
Okay, thanks. I just tried with a default config with just the changes I mentioned and it doesn't happen. So it must be something else in my config. I had assumed not, since I'm not doing anything weird.

Thanks for your help, I'll find the culprit then close the issue.

**Comment by uoou** [comment]
Right, it happens on this config for me.

The only things I've changed from default are:

- changed layout to master
- increased border size to 10 to make it more noticeable
- added `no_gaps_when_only = 1` inside master layout
- changed default terminal keybinding from kitty to foot

Can you confirm that it doesn't exhibit on this config for you?

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/12328598/hyprland.conf.txt)

**Comment by MightyPlaza** [comment]
my bad was setting no_gaps in dwindle and master was using no_gaps = 2

**Comment by MightyPlaza** [comment]
should be fixed https://github.com/MightyPlaza/Hyprland/tree/border-improv
can you test it?

**Comment by MightyPlaza** [comment]
should be fixed https://github.com/MightyPlaza/Hyprland/tree/border-improv
can you test it?

**Comment by uoou** [comment]
Yup, that fixes it. That's great, thank you!
