### ISSUE TITLE
Bemenu not displaying over fullscreen windows

### ISSUE THREAD

**Issue by fictitiousexistence** [hyprwm/Hyprland#2959]
### Hyprland Version

Hyprland, main commit 7395987

### Bug or Regression?

Bug

### Description

When I run bemenu while a window is fullscreen it does not show over the fullscreen window. Bemenu will be behind the fullscreen window instead of on top. 

There is an issue open for bemenu here: https://github.com/Cloudef/bemenu/issues/81

However, I was not sure if this was a bemenu direct issue as bemenu functions properly on dwl.

Thanks!

### How to reproduce

Run bemenu from keyboard shortcut while a window is set to fullscreen

**Comment by vaxerski** [comment]
huh, right. it used to work correctly, guess I broke it.

**Comment by vaxerski** [comment]
regressed by https://github.com/hyprwm/Hyprland/pull/2686

**Comment by vaxerski** [comment]
fixed in 0314a727eb27dd880b172b9ff2dc78c863f3ce5f

**Comment by fictitiousexistence** [comment]
@vaxerski THANK YOU !!!!!
