### ISSUE TITLE
Update wiki section on blur configuration

### ISSUE THREAD

**Issue by georgetian3** [hyprwm/Hyprland#2962]
### Description

#2877 changed the blur configuration making https://wiki.hyprland.org/Configuring/Basic-Config/#decoration out of date.

**Comment by vaxerski** [comment]
that page does not exist and has not existed for a year now. The bot that keeps the wiki updated just doesnt remove pages that got yeeted and I have to do it manually

**Comment by Are10** [comment]
It's actually mentioned on this page: https://wiki.hyprland.org/Configuring/Variables/#blur
