### ISSUE TITLE
Swaylock freezes on multimon

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#2963]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

lock screen get's freezed on one display and mouse is accessible on the other one.

[issue](https://github.com/jirutka/swaylock-effects/issues/43) Is this somehow related to hyprland?

created this issue for knowing this.

### How to reproduce

the laptop should be locked and then plugged in to the monitor.

**Comment by vaxerski** [comment]
atm unable to debug multimon issues but last time I checked it worked just fine on my end

**Comment by niksingh710** [comment]
> atm unable to debug multimon issues but last time I checked it worked just fine on my end

it happens randomly sometimes plugging in the monitor works fine.
but sometimes it freezes will try to get log or something next time if it happens next time.

**Comment by niksingh710** [comment]
Got hyprlock
