### ISSUE TITLE
Rendering Issues with the last update

### ISSUE THREAD

**Issue by SychoAN** [hyprwm/Hyprland#2964]
### Hyprland Version

v0.28.0

### Bug or Regression?

Bug

### Description

I updated hyprland today from 0.27.2 to 0.28.0 and now I when I open any app it gets blurry and pixelated, it takes a lot of time to open

it was working fine with all old versions
but maybe pacman maintainer did something wrong or hyprland devs

also I don't think my device is that old!
cpu i5 3470
card amd r5 240
ram 8gb
hdd

```
glxinfo | grep "OpenGL"
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon R7 200 Series (oland, LLVM 15.0.7, DRM 3.52, 6.4.10-zen2-1-zen)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

### How to reproduce

I am not sure...I use
arco linuxB 
zen-kernel
xdg-portal-hyprland not -wlr

**Comment by vaxerski** [comment]
> it takes a lot of time to open, some apps like waybar doesn't even work

sounds like xdp crashing / dbus timeouts

> open any app it gets blurry and pixelated,

you mean native wl too? or just xwayland?

**Comment by SychoAN** [comment]
> > it takes a lot of time to open, some apps like waybar doesn't even work
> 
> sounds like xdp crashing / dbus timeouts
> 
> > open any app it gets blurry and pixelated,
> 
> you mean native wl too? or just xwayland?

here's my startup tasks
I fixed startup time like a month ago with this commands

```
exec-once = /usr/lib64/polkit-kde-authentication-agent-1
exec-once = killall -q hyprpaper || hyprpaper # Set wallpaper
exec-once = waybar -c $HOME/.config/hypr/waybar/config.jsonc -s $HOME/.config/hypr/waybar/style.css
exec-once = dunst # start notification demon
exec-once = cliphist wipe
exec-once = wl-paste --watch cliphist store
#exec-once = hyprctl plugin load $HOME/.config/hypr/plugins/csgo-vulkan-fix.so
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once=systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=sleep 3 && systemctl --user restart xdg-desktop-portal.service &
```

I don't understand how but xwayland apps is working great...

but the native is the issue
apps like foot terminal, Wl-Logout, wofi ....... this apps takes time to render 

apps doesn't work like waybar
the output when opening waybar
```
waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory
```

**Comment by SychoAN** [comment]
I have detected the issue !!
it's an issue with downscaling
try it on your own
```
monitor=,highres,auto,0.85

#this xwayland options doesn't work anymore
xwayland {
use_nearest_neighbor = false
}
```
fixed by making scale 100% 
"monitor=,highres,auto,1"

**Comment by SychoAN** [comment]
two things I request from hyprland devs

-when I updated hyprland only without updating kernel and other pacakges I got black screen...I couldn't even open TTY...so plz tell us the needed dependencies on the release changelog...or when installing with pacman

-plz plz plz add downscaling to your tests when you finish a new version...because each update breaks it ):

**Comment by vaxerski** [comment]
> -when I updated hyprland only without updating kernel and other pacakges I got black screen...I couldn't even open TTY...so plz tell us the needed dependencies on the release changelog...or when installing with pacman

That's expected on arch with anything.

> -plz plz plz add downscaling to your tests when you finish a new version...because each update breaks it ):

Very niche feature, all things considered.

**Comment by romanstingler** [comment]
is this still an issue?
