### ISSUE TITLE
Yuzu(game emulator) displaying nothing when running a game

### ISSUE THREAD

**Issue by NormalFall** [hyprwm/Hyprland#297]
https://user-images.githubusercontent.com/93881091/177010517-e8d7a1a4-d762-42de-b840-7b863ef37b59.mp4

I played with pretty much every graphic settings in yuzu and always get this result
no idea why this is happening

**Comment by vaxerski** [comment]
does it work in sway / wayfire / vivarium?

**Comment by NormalFall** [comment]
Oh whoops thought it would run fine on sway/hyprland since it worked fine on kde but i guess its not how it works.

**Comment by vaxerski** [comment]
didnt answer my question but ok

**Comment by vaxerski** [comment]
at any rate, for games, it's best to run them through gamescope.

**Comment by NormalFall** [comment]
Its broken in sway and wayfire.
Apparently it has not fixes for now

**Comment by vaxerski** [comment]
that usually means the problem is in wlroots, which I am based on. You can try reporting the issue on their gitlab: [https://gitlab.freedesktop.org/wlroots/wlroots](https://gitlab.freedesktop.org/wlroots/wlroots)
