### ISSUE TITLE
Remove waybar overlay or make it optional

### ISSUE THREAD

**Issue by CnTeng** [hyprwm/Hyprland#2971]
### Hyprland Version

a0cf89029263decba29b0f4216b38576f4418335

### Bug or Regression?

Bug

### Description

nixpkgs has waybar-hyprland now, I think waybar overlay can be removed or be optional. 
@fufexan

### How to reproduce

[waybar-hyprland](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/waybar/default.nix#L21C4-L21C4)

**Comment by fufexan** [comment]
Sure, I need the opinion of waybar users first. @NotAShelf ?

**Comment by NotAShelf** [comment]
We can remove it. Though, what do you mean by "make it optional"?
