### ISSUE TITLE
Documentation on eww scripts for workspaces appears to be outdated

### ISSUE THREAD

**Issue by MCotocel** [hyprwm/Hyprland#2975]
### Hyprland Version

Hyprland, built from branch at commit 8e04a80e60983f5def26bdcaea701040fea9a7ae

### Bug or Regression?

Bug

### Description

When running the script `get-workspaces`, as shown in https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#eww, the following error is shown:

```
parse error: Invalid numeric literal at line 1, column 7
jq: invalid JSON text passed to --argjson
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

Additionally, when running `get-active-workspace`, although the active workspace is eventually echoed, a similar error is shown at first:

```
parse error: Invalid numeric literal at line 1, column 7
```

These errors seem to result in the workspace widget for eww disappearing. I assume this is caused by a recent commit to hyprland, since the eww and jq versions are the same as when the workspace widget was working.

### How to reproduce

Install the mentioned version of hyprland.

Configuration for hyprland: https://github.com/MCotocel/nixdots/blob/master/config/hypr/default.nix
Configuration for eww: https://github.com/MCotocel/nixdots/tree/master/config/eww

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/hyprland-wiki/issues

**Comment by MCotocel** [comment]
My bad
