### ISSUE TITLE
Idk if this is a bug but unintuitive, ws 10 after ws 1

### ISSUE THREAD

**Issue by Lavishq** [hyprwm/Hyprland#2978]
### Description

![image](https://github.com/hyprwm/Hyprland/assets/96654752/c6b75527-f357-4342-99e9-c0269d4cd56b)

i don't think this is a issue but having 10 at end would help, like in other wm's or compositors per se.

the reasoning is that i put important thing at 1,2,3 and 10 by clicking 0 and it is very easy  to click super 0 to switch 10ws to when you look at wlr/workspaces it doesnt look good [1, 10, 2, 3] or correct or perfect🐧🐧

[1,2,3,...10] would make it better

i like hyprland but sometimes mouse arrow doesn't turn to pointer on links or button where it should, this happens often🐧🐧

**Comment by tchofy** [comment]
For the workspace order issue, that's up to the bar you're using, as hyprland itself does not come with a bar. If you're using waybar, add ``"sort-by-number": true,`` to your ``wlr/workspaces`` (or ``hyprland/workspaces``) module.

Second issue could be https://github.com/hyprwm/Hyprland/issues/2532, try adding ``hover_icon_on_border = false`` to the ``general {}`` part of your config, if that doesn't work, try also adding ``resize_on_border = false``.

**Comment by Lavishq** [comment]
@tchofy thanks, you solved the first issue
i thought i had it in sequence w/ sway but on hyprland the sequence is lost

idk about the second one, it often happens in browsers like chromium or brave🐧🐧
