### ISSUE TITLE
changing workspace dont change focus

### ISSUE THREAD

**Issue by Polluktus** [hyprwm/Hyprland#298]
**Steps to reproduce**
open terminal in workspace 1
open terminal in workspace 2
switch back to workspace 1
focus stays on terminal in workspace 2

**Expected outcome**
focus should switch to terminal in workspace 1

**fix**
this problem seems to be caused by commit [7d7e82d](https://github.com/hyprwm/Hyprland/commit/7d7e82d446f097692e24220614951da435dcca2b) simple git revert should fix it.

**Comment by vaxerski** [comment]
but I will not revert it. I'll fix it once I'm back or I will pester @fufexan to fix it
