### ISSUE TITLE
Core dumped on every exit from Hyprland

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/Hyprland#2980]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Core dumped on every exit from Hyprland.

### How to reproduce

Arch Linux, LTS kernel 6.1.XX

The issue is reproducible with SDDM, seatd, no initial Hyprland config (i. e. with default autogenerated config). Hyprland xdg desktop portal is installed.

### Crash reports, logs, images, videos

[systemd-journal.txt](https://github.com/hyprwm/Hyprland/files/12343244/systemd-journal.txt)

**Comment by ashixu** [comment]
oh! I have same problem with you.  #2894 , It's my early log. And my most recent Hyprland crash report was similar with yours. You can see here :
[hyprlandCrashReport137922.txt](https://github.com/hyprwm/Hyprland/files/12355886/hyprlandCrashReport137922.txt)

**Comment by akdevservices** [comment]
Now I run Hyprland without any display manager under a regular user from tty (via .bash_profile) and reboot or poweroff the machine via `systemctl reboot/poweroff` from Hyprland, everythng works OK. The core is dumped only when I exit from Hyprland back to tty login.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12504526/patch.txt)
try this

**Comment by akdevservices** [comment]
Now I'm running ver. 0.29 (Arch Linux packaging from `extra` repo), it's fixed, no need to try your patch.
