### ISSUE TITLE
xwayland force_zero_scaling actually does scale, just very slightly.

### ISSUE THREAD

**Issue by potatoalienof13** [hyprwm/Hyprland#2985]
### Hyprland Version

Hyprland, built from branch main at commit 91e28bbe9df85e2e94fbcc0137106362aea14ab5 dirty (xwayland: use a completely separate coordinate system). Tag: v0.28.0-57-g91e28bbe  flags: (if any)

### Bug or Regression?

Bug

### Description

At certain scaling factors, even with force_zero_scaling, xwayland apps are told to render at a resolution that is 1 or 2 pixels short of the resolution they should render at, and then scaled up to the proper resolution. 

On my 2560x1600 monitor, a global scaling factor of 1.3 will cause a fullscreen xwayland program to render with a resolution of 2559x1598.

### How to reproduce

1. Enable zero scaling for xwayland.
2. Set a non-integer scaling factor.
3. Run this command. It will report the size of the xev window when it receives configures.
```
xev -event structure
```
4. Fullscreen xev, and compare its text output with the known resolution of your screen.
5. Change your scaling factor a bit, if the output and resolution of your screen are the same.

**Comment by potatoalienof13** [comment]
this issue caused me great pain and suffering until i noticed firefox was running on xwayland. firefox consistently had its center column of pixels duplicated.

**Comment by potatoalienof13** [comment]
1.3 * 1600 and 1.3 * 2560 are both integers.

**Comment by vaxerski** [comment]
it's 1600 / 1.3, not * 1.3

**Comment by hholst80** [comment]
Is that on point or not? The scaling coefficient should not be relevant in a zero scaling scenario.  Xwayland should render on the native resolution no matter what scaling Wayland apps are using.

**Comment by izmyname** [comment]
Is this still actual?

**Comment by potatoalienof13** [comment]
I am not sure, I've had scaling turned off for a while.

**Comment by vaxerski** [comment]
closing then
