### ISSUE TITLE
Mouse and windows not in center

### ISSUE THREAD

**Issue by cristiangrossano** [hyprwm/Hyprland#2997]
### Hyprland Version

v0.28.0-58-g4986d74e

### Bug or Regression?

Bug

### Description

Mouse during game moving to the side of the screen during Minecraft and windows on open appearing to thee side.

### How to reproduce

Opening new app or opening inventory in minecraft.

**Comment by juvevood** [comment]
now all menus of xwayland application has become centered

**Comment by vaxerski** [comment]
can't quite repro that. Any app examples?

**Comment by cristiangrossano** [comment]
https://github.com/hyprwm/Hyprland/assets/81424772/51c9ab2b-2408-43b6-be46-0577d2a07af0

**Comment by cristiangrossano** [comment]
I want to say that is not a minecraft bug. Downgrading to "hyprland" from "hyprland-git" solved the problem.

**Comment by vaxerski** [comment]
do you use force_zero_scaling with a scaled display?

**Comment by Neptune1520** [comment]
> I want to say that is not a minecraft bug. Downgrading to "hyprland" from "hyprland-git" solved the problem.

How did you do that?

**Comment by cristiangrossano** [comment]
> do you use force_zero_scaling with a scaled display?

`monitor=eDP-1,1920x1080,1920x0,1`

and I dont use force_zero_scaling.

**Comment by cristiangrossano** [comment]
> > I want to say that is not a minecraft bug. Downgrading to "hyprland" from "hyprland-git" solved the problem.
> 
> How did you do that?

`pacman -Syu hyprland`

Then uninstalling `hyprland-git`

**Comment by tagomaco** [comment]
I have the same problem only when using force_zero_scaling.

**Comment by Neptune1520** [comment]
> > > I want to say that is not a minecraft bug. Downgrading to "hyprland" from "hyprland-git" solved the problem.
> > 
> > 
> > How did you do that?
> 
> `pacman -Syu hyprland`
> 
> Then uninstalling `hyprland-git`

Thank you!

**Comment by vaxerski** [comment]
I played some minecraft today and haven't noticed anything off. Can I get your monitor config?

**Comment by vaxerski** [comment]
check with 942ee943f5b0f3f9611b2ff5481dacf19aed6a17

**Comment by cristiangrossano** [comment]
The minecraft app opened to the side of the screen, but I have no more the mouse issue.

**Comment by tagomaco** [comment]
mouse centering problem fixed for me after this commit

**Comment by cristiangrossano** [comment]
Yeah, mouse Is solved, but apps sometimes open on the side

**Comment by vaxerski** [comment]
that is tracked cumulatively at #3029 so closing
