### ISSUE TITLE
Ability to interact with unfocused windows with a mouse

### ISSUE THREAD

**Issue by stomar117** [hyprwm/Hyprland#300]
Currently if a window is outside of focus then we cannot do some actions like scrolling on a window, which do not require the window to be in focus. Instead all those actions are interpreted by the window in focus, this leads to a very confusing behavior.

One method is to enable `follow_mouse` but that also has its own caveats, like the focus being all over the place when navigating with the mouse.

If there could exist any method do some mouse actions on a window without actually bringing it into focus, then any such inconvenience could be resolved.

I hope you'll look into it.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/177052224-ba0ae8bd-526e-4cf0-86c5-5e496cdf036e.png)

if only such thing existed, and if only the wiki would mention it, I wonder how it would be...
