### ISSUE TITLE
SUPER+ESCAPE binding: ESCAPE is passed to the app when it shouldn't

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/Hyprland#3000]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Bug

### Description

SUPER+ESCAPE binding: ESCAPE is passed to the app when it shouldn't

### How to reproduce

1. Add to config:
```
binds {
    workspace_back_and_forth = yes
    allow_workspace_cycles = yes
}
```
2. Create binding: `bind = SUPER, ESCAPE, workspace, previous`
3. Run Firefox, open Youtube, start playing any video, make it fullscreen.
4. Switch to any other workspace,
5. Press SUPER+ESCAPE to get back to the workspace with fullscreen video.

The video is not fullscreen anymore, because SUPER+ESCAPE works when pressing ESCAPE button, but Firefox is obviously receiving ESCAPE release button event. I think Firefox should not consume ESCAPE in this case.

**Comment by vaxerski** [comment]
does it also happen with other keys or just escape?

Also happy 3k issue :)

**Comment by memchr** [comment]
This is probably because Firefox exits full-screen mode when it detects the release of the Escape key.

Hyprland will not pass the key press event in a keybinding, but it will pass the key release event in most circumstances, this is true for all keys, not just the Escape key.

**Comment by zakk4223** [comment]
I have a super+space bind for my app launcher and it consistently causes youtube videos in firefox to pause when I use it with firefox focused. I feel like this is a new-ish behavior so I'll attempt a bisect when I can get some time to close all 5,000 windows I have
