### ISSUE TITLE
Context menus not selectable or clickable through a Drawing Tablet 

### ISSUE THREAD

**Issue by DeckedSpring67** [hyprwm/Hyprland#3004]
### Hyprland Version

Hyprland, built from branch HEAD at commit 4986d74ef201171a930c312a8e3b72a22d9b84ee dirty (xwayland: fix use of xwayland coords in native spaces).

### Bug or Regression?

Bug

### Description

On many (but not all, for example Dolphin works) applications, the context menu does not work correctly in Hyperland while using a drawing tablet, with or without OpenTabletDriver.

I've tried on Sway and Plasma Wayland and it works as intended.

There's another bug I think it's related to this same issue, whenever there's something that triggers a cursor icon change (for example hovering into a resizable area border), if you go to another area where the cursor should be back to the default one, it just doesn't change, you can update the change by moving the mouse instead of the drawing tablet, video below.

### How to reproduce

Open a context menu with a drawing tablet (for example on Xournal++), the items are not being selected when hovering over them and if you click on them the context menu just closes without having done any action.

### Crash reports, logs, images, videos

First clip: opening a menu first with a mouse which is how the application should behave, then with a drawing tablet not being able to select anything and if I click with it it just removes the menu, then I do the same thing but switch to mouse to show that it works, then mouse into tablet and it doesn't work, then tablet into mouse into tablet again showing it doesn't work.

https://github.com/hyprwm/Hyprland/assets/10902117/1701cd74-2ddf-4562-b2f0-ea19140c226a

Second clip: Works as intended on sway 

https://github.com/hyprwm/Hyprland/assets/10902117/deaa917f-46aa-4ba2-9851-c967a1d14588

Third clip: Cursor issue on Dolphin (also happening in other applications like Xournal, which is noticable at 00:17 on the first video), the cursor turns back to the default one when moving the mouse

https://github.com/hyprwm/Hyprland/assets/10902117/ffc36828-34b6-4311-adc0-817774db1178

**Comment by Izaird** [comment]
I was thinking on opening a ticket about this it happens the same on blender when you try to hold and drag certain stuff like for example on the shading part if you want to adjust a slider you can't drag it

**Comment by kotbaton** [comment]
> idk, does this happen on -git still?

Yes, it also happens on freshly installed git version (I used AUR package for it).

`hyprctl version` outputs that its build from commit bc15a8f60028539690cccdb78eed7fc9175fe792 so it's pretty much last version.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14617894/patch.txt)
try this?

**Comment by kotbaton** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14617894/patch.txt) try this?

Thank you but it does not seems to solve the problem. I also tried to change 2 more "refocus()" calls to "simulateMouseMovement()" but it doesn't solve the issue either.

**Comment by vaxerski** [comment]
no clue then why this doesn't work and me not having a tablet doesn't help either :P

**Comment by kotbaton** [comment]
I can try to check it later but I have little experience with C++ and no experience with wayland managers so I don't think I will be able to fix it by myself. However I did some testing and there are some info which can be helpful (I think):
- The issue also appears in relative mode (changed in the configuration).
- In sway I am able to click in the widgets in waybar using tablet's pen and they react on it (I can change workspaces, click wifi icon in tray and so on) - However I can't do this in Hyprland. It makes me think that maybe problem is not with how the cursor moves, but how the clicks processed?

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14629195/patch.txt)
can someone give me the log from moving their tablet pen around with this patch applied?

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14629298/patch.txt)
this could be a fix? idk test it I don't have a tablet

**Comment by qwertyuiopr** [comment]
I'll try both of those, give me a little bit
Compiling from gentoo 0.37.1

https://gitweb.gentoo.org/repo/gentoo.git/tree/gui-wm/hyprland/hyprland-0.37.1.ebuild

**Comment by vaxerski** [comment]
likely cuz `patch` will fail because one hunk won't apply. just `patch -p1 < /path/to/patch || echo ""`

**Comment by qwertyuiopr** [comment]
patch didn't fix cursor issues in osu
for xournal, i can select the options from the dropdown menus but i have to hold my pen down throughout the whole thing using artist mode
log if it's of any use:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14629844/hyprland.log)

p.s. should i move my issue back to

**Comment by vaxerski** [comment]
```
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
```
someone hasn't read the log itself.

**Comment by qwertyuiopr** [comment]
sorry, got back up to provide a proper log
and one quick thing, managed to get xournal menus working properly by using mouse button binding instead of linux artist mode binding for left click
all still under artist mode
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14630010/hyprland.log)

**Comment by vaxerski** [comment]
are you sture this is with the first patch?

**Comment by qwertyuiopr** [comment]
this was with the second patch. i can compile with the first quickly, give me a second

**Comment by qwertyuiopr** [comment]
was having issues uploading the file, here's the log with 1st patch only:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14630209/hyprland.log)

**Comment by vaxerski** [comment]
thanks, will look into tomorrow

**Comment by kotbaton** [comment]
Not sure how much helpful it will be, but I tried to apply all three patches one by one, and third fails. I compiled and test, but this don't fix the problem. Please see actually applied changes and logs:

[changes.txt](https://github.com/hyprwm/Hyprland/files/14632464/changes.txt)
[hyprlandd.log](https://github.com/hyprwm/Hyprland/files/14632468/hyprlandd.log)

Tablet testing starts at line 350 I reattached one and first tried to draw in xournalpp (It worked as expected even before the patches) and then I tried to click some menus and it is not possible to choose anything from menu.

Hope this helps.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14640890/patch.txt)
try this. Apply over clean -git

**Comment by kotbaton** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14640890/patch.txt) try this. Apply over clean -git

Thank you, I tried it on the clean git (also pulled from master just to be sure that it is the last version), and I can say it partially fixes the problem please see the video attached.

https://github.com/hyprwm/Hyprland/assets/40325905/271a34da-0f02-4e92-886c-1cd4d166bd0f

**Comment by qwertyuiopr** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14640890/patch.txt) try this. Apply over clean -git

xournal seems to work perfectly fine for me. osu still has the same issue, sometimes cannot even detect inputs now

p.s. is my osu issue still relevant in this thread? 


https://github.com/hyprwm/Hyprland/assets/117125180/b04d2281-b7e6-4729-b3a3-7bf5f033568b

**Comment by kotbaton** [comment]
@qwertyuiopr I see that you using xournal and I am wondering then why xournalpp is not functioning properly for me. Maybe I am missing some dependencies on the arch or something, idk. I tried to check it later. However it is strange that everything works good for me in sway on the same distro and same machine.

**Comment by qwertyuiopr** [comment]
are you using the artist bindings on xournal? when i select the artist bindings in opentabletdriver, i have a similar issue where just tapping on the menus won't work, and i have to hold down my pen to access the menus. though using the mouse bindings work, they're only supposed to be there as a fallback option rather than what you use mainly.

https://github.com/hyprwm/Hyprland/assets/117125180/d0633ab6-a6ee-46cb-85e8-9475c8fc3359

**Comment by kotbaton** [comment]
> are you using the artist bindings on xournal? when i select the artist bindings in opentabletdriver, i have a similar issue where just tapping on the menus won't work, and i have to hold down my pen to access the menus. though using the mouse bindings work, they're only supposed to be there as a fallback option rather than what you use mainly.
> 2024-03-18.21-03-10.mp4

Yeah, it can be this, but I just use standard wacom driver on arch, I didn't change any configuration on this etc, it just worked. Also, I am using xounrnalpp (fork of xournal I believe) and not just xournal. But I doubt that it can be a source of the issues here.

**Comment by qwertyuiopr** [comment]
> > are you using the artist bindings on xournal? when i select the artist bindings in opentabletdriver, i have a similar issue where just tapping on the menus won't work, and i have to hold down my pen to access the menus. though using the mouse bindings work, they're only supposed to be there as a fallback option rather than what you use mainly.
> > 2024-03-18.21-03-10.mp4
> 
> Yeah, it can be this, but I just use standard wacom driver on arch, I didn't change any configuration on this etc, it just worked. Also, I am using xounrnalpp (fork of xournal I believe) and not just xournal. But I doubt that it can be a source of the issues here.



uploaded video to discord because of 10mb file size limit on github
using xournalpp, i'm able to reproduce all of the exact same issues with artist bindings you are having. may have missed some from the video, but i don't doubt i can't recreate them either.

https://cdn.discordapp.com/attachments/1219382320377888900/1219394844024246332/2024-03-18_21-16-44.mp4?ex=660b24f2&is=65f8aff2&hm=70ce13959a9fe13247f6544f49999179b073a5996a841369f4cad8470434d821&

**Comment by kotbaton** [comment]
@vaxerski @qwertyuiopr I installed open tablet driver and it seems to fix the problem. I have no bindings in it, and I am able to normally draw and click on menus, so the problem is solved I think. It is strange for me that everything worked as intended with sway, but I am happy that it is fixed. Thank you :)

**Comment by vaxerski** [comment]
yea this can be closed I believe
