### ISSUE TITLE
Some popup windows position incorrect

### ISSUE THREAD

**Issue by univeous** [hyprwm/Hyprland#3009]
### Hyprland Version

Hyprland, built from branch main at commit 7155b4c26606d7681bacb2517b1d19495336c6c3 dirty (renderer: Border improvements (2986)).

### Bug or Regression?

Regression

### Description

Fcitx5 candidate box position is incorrect, it shows on the other monitor.
It used to work fine, but recent commits break it.
hyprland(0.28.0-1) and hyprland-nvidia(0.28.0-2) from AUR are still working fine but the latest hyprland-git and hyprland-nvidia-git are not. Maybe a regression.

### How to reproduce

use fcitx5 with latest hyprland-git or hyprland-nvidia-git.

**Comment by YinAqu** [comment]
Some Jetbrains idea popup windows encounter this issue too recently when there are two monitors, such as double shift window and code completion window.

**Comment by univeous** [comment]
Yes I'm using dual monitors as well. 
Also I found this issue also happened on the Edge's right-click menu sometimes.

**Comment by VeilSilence** [comment]
Can confirm. 
2 monitors. DP-1 2560x1440, HDMI 1920x1080.
Steam popup messages appear on high resolution monitor ( 2560x1440 ) but position placement is like he think i'm at 1920x1080 resolution.
In World of Warcraft for example, ( game on DP-1 ) WOW only see 1920x1080 resolution. If i move game on my secondary monitors, WOW see 2560x1440. Also my mouse jump on second monitor if i'm trying to click anything in game. For example, game on DP-1 -> click something in game -> cursor appear on HDMI monitor. If i move game to HDMI monitor and click something, cursor jump to DP-1.
Didn't updated hyprland for some time, so i reverted back to 2e6693fbb650dd2c9b7ad4b6d830899589504bda commit and it works as intended.
Looks like only xwayland application affected.

**Comment by vaxerski** [comment]
#3002

**Comment by univeous** [comment]
I could confirm 14f20a737221f09a601d846c2b37b969afe2e725 fixes some menus like the Edge's right-click menu, but fcitx5's candidate box position is still incorrect. 
![1692413297](https://github.com/hyprwm/Hyprland/assets/40604180/2df83058-fed2-4950-9006-df2ba90bbdce)

**Comment by vaxerski** [comment]
can't repro しょくざい

![image](https://github.com/hyprwm/Hyprland/assets/43317083/5f28839f-6052-4475-9139-d02d9184cc0a)

**Comment by univeous** [comment]
I believe this is related to the monitor position. Issue appears with
```
monitor = DP-2,highres,1080x506,1
monitor = DP-3,1920x1080@165,0x0, auto, transfrom, 3
```
If I comment both lines it looks fine.

**Comment by dingiso** [comment]
Same thing happens on my dual monitor setting
