### ISSUE TITLE
Feature:  dispatchers support monitor names and workspace names

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#301]
Good day to you!

suggestions for:

1) Supporting for workspace names in:
```
# default named workspace `workspaceName` on `monitorName`
workspace=monitorName, name:workspaceName
```
usecase: to be able to startup `Hyprland` with default named workspaces.

2) supporting monitor names in `moveworkspacetomonitor`:
```
exec=hyprctl dispatch moveworkspacetomonitor "name:term DP-1"
```
usecase: workaround and addition to paragraph 1), but also to be able to move multiple workspaces at startup to monitor

Thank you!

**Comment by vaxerski** [comment]
both 1 and 2 are already supported.

multiple workspaces at startup are impossible, as Hyprland will close a workspace thats out of focus and empty.

**Comment by fedoranvar** [comment]
1. my bad. thank you!

2. that's why i asked in first message about 
![image](https://user-images.githubusercontent.com/52028706/177177802-7896594e-eabe-4b59-ae84-4036caf04d25.png)

**Comment by vaxerski** [comment]
sure

**Comment by fedoranvar** [comment]
it works good.

Thank you!
