### ISSUE TITLE
Build Hyprland for Debian

### ISSUE THREAD

**Issue by izzy8799** [hyprwm/Hyprland#3010]
### Description

**Please build Hyprland for Debian.**
Very inconvenient when trying to install Hyprland the convenient and quick way via apt, but it's not available as a .deb package. Maybe I don't know or understand something, please explain why you don't build Hyprland for debian.

**Comment by vaxerski** [comment]
because nobody here uses debian, plus debian has way too outdated deps

**Comment by izzy8799** [comment]
> because nobody here uses debian

Maybe because they are inconvenient to install hurlland due to inconvenient manual installation?

> plus debian has way too outdated deps
What is the problem with opening a separate repo for debian or giving out a separate file on the site?

**Comment by vaxerski** [comment]
by "nobody here" I mean nobody in the org that maintains hyprland in any capacity.

**Comment by andrPonomarenko** [comment]
@izzy8799 Egor, please ask Donya to check his Proton email. I wrote a letter for all of you.

I apologize for posting here. I'm in rehab and can't contact @izzy8799 otherwise.

**Comment by izzy8799** [comment]
> @izzy8799 Egor, please ask Donya to check his Proton email. I wrote a letter for all of you.
> 
> I apologize for posting here. I'm in rehab and can't contact @izzy8799 otherwise.

God, Andrey! Glad to see you again! I haven't opened Github messages for a long time. And so, Donya has already read the letters.
