### ISSUE TITLE
Border alpha is ignored

### ISSUE THREAD

**Issue by Lassebq** [hyprwm/Hyprland#3013]
### Hyprland Version

Hyprland, built from branch main at commit 7e8a21202729ca806cd244fb37e5b45abb4cc69b dirty (internal: allow negative monitor offsets). Tag: v0.28.0-63-g7e8a2120  flags: (if any)

### Bug or Regression?

Regression

### Description

Border alpha is ignored and instead it displays a solid rgb color

### How to reproduce

Set general:col.inactive_border to an rgba value

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/68742864/fbb30b5d-316d-45e4-b8c9-2dd0cc93007a)

**Comment by vaxerski** [comment]
if this is a regression please do a `git bisect` for it

**Comment by vaxerski** [comment]
nvm 6c10c384813890ed137f73ee79452cbe8c6f1dca

**Comment by vaxerski** [comment]
fixed in 3d9545d2e0aee9f6c67867b22cf3fb9b1f708bc6

**Comment by Lassebq** [comment]
ok cool.
