### ISSUE TITLE
Hyprland freezes when using XWayland software sometimes

### ISSUE THREAD

**Issue by refrogerator** [hyprwm/Hyprland#3015]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty ().

### Bug or Regression?

Bug

### Description

When playing some XWayland games like minecraft 1.8.9 or roblox the screen sometimes locks up completely and I am unable to do anything, not even switch to any TTYs. Sometimes it works after waiting a bit or gets choppy but most of the time i have to reboot. In those cases where it gets choppy, closing the program fixes it.

### How to reproduce

Play Minecraft 1.8.9 vanilla on say hypixel for some amount of time.

**Comment by vaxerski** [comment]
sounds like an OOM

**Comment by vaxerski** [comment]
using an oomd. At any rate, not a hl issue
