### ISSUE TITLE
Slow Animations after waking from sleep or logout

### ISSUE THREAD

**Issue by SychoAN** [hyprwm/Hyprland#3018]
### Hyprland Version

v0.28.0

### Bug or Regression?

Bug

### Description

everything is working fine_until I make it sleep 
-animations becomes laggy
-videos takes time to render
-Didn't test games but I am sure it will have low fps also after waking from sleep

tell me if you need any information about my system
intel i5 3470
ram 8gb 
amd r5 240
hdd

I use xdg-desktop-portal-hyprland not -wlr

and this is my boot tasks 
```
exec-once = /usr/lib64/polkit-kde-authentication-agent-1
exec-once = killall -q hyprpaper || hyprpaper # Set wallpaper
exec-once = waybar -c $HOME/.config/hypr/waybar/config.jsonc -s $HOME/.config/hypr/waybar/style.css
exec-once = dunst # start notification demon
exec-once = cliphist wipe
exec-once = wl-paste --watch cliphist store
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once=systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=sleep 3 && systemctl --user restart xdg-desktop-portal.service &
```

### How to reproduce

maybe old amd card and intel cpu

or maybe I did something wrong with the portals
but both xdg-desktop-portal and  xdg-desktop-portal-hyprland are "active (running) "

**Comment by vaxerski** [comment]
looks like an issue on your end. Possibly some power saving shenanigans? Did you test on e.g. sway? or a different machine?

**Comment by SychoAN** [comment]
> 

hmm no I tested openbox kde gnome never had this issue

but I did make garuda linux Performance tweaks
like installing this tools
ananicy-cpp irqbalance dbus-broker preload

and changing this file
sudo nano /usr/lib/udev/rules.d/50-sata.rules

# SATA Active Link Power Management
ACTION=="add", SUBSYSTEM=="scsi_host", KERNEL=="host*", ATTR{link_power_management_policy}="max_performance"

I'll make a timeshift backup
and try to revert this tweaks

**Comment by vaxerski** [comment]
all of the above likely ran on X11, and neither share a common base. Please test sway.

**Comment by SychoAN** [comment]
> all of the above likely ran on X11, and neither share a common base. Please test sway.

Done Tested sway but didn't have that issue...but bro I have to say that Hyprland is better 100% than any other window manager

**Comment by SychoAN** [comment]
> all of the above likely ran on X11, and neither share a common base. Please test sway.

It wasn't a hyprland issue...after updating with pacman -Syu 
it updated packages like zen-kernel, arcolinux-hyprland-git, xorg-xwayland
I think one of these 3 was the issue
thanks for your help :+1:

**Comment by SychoAN** [comment]
Fixed

it's was a gpu waking up issue
making it on powersave or performance will fix it

install CoreCtrl
and make gpu on performance mode
then restart

add it to startup
cp /usr/share/applications/org.corectrl.corectrl.desktop ~/.config/autostart/org.corectrl.corectrl.desktop


don't ask for password at startup
```
pkaction --version

Polkit version < 0.106
Create the file /etc/polkit-1/localauthority/50-local.d/90-corectrl.pkla with the following contents:

[User permissions]
Identity=unix-group:your-user-group
Action=org.corectrl.*
ResultActive=yes

Replace //your-user-group// with your user group name.

Polkit version >= 0.106
Create the file /etc/polkit-1/rules.d/90-corectrl.rules with the following contents:

polkit.addRule(function(action, subject) {
    if ((action.id == "org.corectrl.helper.init" ||
         action.id == "org.corectrl.helperkiller.init") &&
        subject.local == true &&
        subject.active == true &&
        subject.isInGroup("your-user-group")) {
            return polkit.Result.YES;
    }
});

Replace //your-user-group// with your user group name.
```
