### ISSUE TITLE
Borders are outside the screen space with no_gaps_when_only property

### ISSUE THREAD

**Issue by a125x** [hyprwm/Hyprland#3020]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Kinda hard to describe, but basically borders are somewhere outside the screen with no_gaps_when_only and gaps_out = 0 properties after opening second window. They come back to their positions after some minor events such as changing spaces, but it still seems weird and inconsistent. I'll attach an image with this weird borders behaviour and another with correct borders.

### How to reproduce

Set gaps_out option in general to 0
Set no_gaps_when_only option in master to 1
Close all the windows except one
Open another window
Enjoy ^~^

### Crash reports, logs, images, videos

Bad borders (hyprland does not show top, bottom and right ones):

![bug_hyprland](https://github.com/hyprwm/Hyprland/assets/91656458/367bba88-9368-4084-b63c-24803ca364e4)

Good borders:

![good_hyprland](https://github.com/hyprwm/Hyprland/assets/91656458/89b8bb91-3487-4ad4-8665-28e2b8e7bfa0)

**Comment by vaxerski** [comment]
@MightyPlaza you recently meddled with borders, isnt this your wrongdoing?

**Comment by MightyPlaza** [comment]
if anything I should have fixed it, please test latest build

**Comment by vaxerski** [comment]
right, this is on 0.28. Try with -git.

**Comment by a125x** [comment]
Thanks, it solved the issue
