### ISSUE TITLE
XWayland: no mouse input in monitors that are not at 0x0

### ISSUE THREAD

**Issue by DiedByDisgust** [hyprwm/Hyprland#3021]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

no mouse input in XWayland app.

### How to reproduce

Just config a monitor other than 0x0.

### if monitor isn't at 0x0

[recording_20230818-151229.webm](https://github.com/hyprwm/Hyprland/assets/25803026/130cb12d-dc76-4039-ba24-154dd9fdb51a)

### Normal behavior at 0x0

[recording_20230818-151319.webm](https://github.com/hyprwm/Hyprland/assets/25803026/cc41c5f1-79ce-4877-882f-d33e59caa118)

**Comment by vaxerski** [comment]
That is a very old version. Please report bugs from -git.

**Comment by DiedByDisgust** [comment]
> That is a very old version. Please report bugs from -git.

ok. sorry, totally fair, updating. btw when do this repo get so big, it use to be some few MBs

**Comment by burein-ita** [comment]
hypr-chan is fat.

**Comment by burein-ita** [comment]
This happens to me when using negative position values.

**Comment by vaxerski** [comment]
> hypr-chan is fat.

so is your mother but I ain't going around badmouthing her.

**Comment by h0tc0d3** [comment]
Possibly related to the same error. In wine games, the cursor is lost and starts looking up.
After move the mouse back, a few more times cursor is a return to the top. This happens with different mice.

**Comment by musicfunfan** [comment]
I have the same problem. I use hyprland version ``extra/hyprland 0.28.0-1 (7.6 MiB 11.8 MiB) (Installed)``
And all the xwayland windows Discord,Chromium,wine/proton games and others... They loose the cursor accuracy. I can not click when i want to click. Cursors has a vertical offset from the position on the screen and the actually position of the cursor. 

This only happens on the screen with the 1920x0 configuration. 

Btw this is my config. 

 ## This is fine. But wrong screens geometry. 
```#monitor set up.
monitor=DP-1,3840x2160@60,0x0,2
monitor=DVI-D-1,1920x1080@60,1920x0,1
```

## This is not fine but correct screens geometry. 
```#monitor set up.
monitor=DP-1,3840x2160@60,1920x0,2
monitor=DVI-D-1,1920x1080@60,0x0,1
```
I also have xwayland scaling off. 

```xwayland {
  force_zero_scaling = true
}
```

**Comment by xz-dev** [comment]
> I have the same problem. I use hyprland version `extra/hyprland 0.28.0-1 (7.6 MiB 11.8 MiB) (Installed)` And all the xwayland windows Discord,Chromium,wine/proton games and others... They loose the cursor accuracy. I can not click when i want to click. Cursors has a vertical offset from the position on the screen and the actually position of the cursor.
> 
> This only happens on the screen with the 1920x0 configuration.
> 
> Btw this is my config.
> ## This is fine. But wrong screens geometry.
> 
> ```
> monitor=DP-1,3840x2160@60,0x0,2
> monitor=DVI-D-1,1920x1080@60,1920x0,1
> ```
> 
> ## This is not fine but correct screens geometry.
> 
> ```
> monitor=DP-1,3840x2160@60,1920x0,2
> monitor=DVI-D-1,1920x1080@60,0x0,1
> ```
> 
> I also have xwayland scaling off.
> 
> ```
>   force_zero_scaling = true
> }
> ```

If I disable `force_zero_scaling`, everthing will clickable, but it looks a lot jagged.

**Comment by musicfunfan** [comment]
Yea this is happening coz xwayland apps do not scaling. So if you use scaling you gonna see some pixels and on the Game. This is bad and in generally i like my 4k and my 1080p panel to be crisp. So what i do is run the screens with wrong geometry and waiting for a solution to my problem. :)

**Comment by colrobloxkid69420** [comment]
Hope it's not too annoying that I am bringing this up again but I got the same issue but in reverse (that is, mouse input only works on non 0x0 monitors)

**Comment by vaxerski** [comment]
I think this should be closed tbh

@colrobloxkid69420 your issue is likely that one with overlapping xwayland displays, forgot the #

**Comment by colrobloxkid69420** [comment]
> I think this should be closed tbh
> 
> @colrobloxkid69420 your issue is likely that one with overlapping xwayland displays, forgot the #

That was exactly the issue and I managed to fix it somehow, thank you very much for pointing that out, I wouldn't have been able to figure it out otherwise.

**Comment by DreadsCasey** [comment]
changing my display to 0x0 worked for 2 xWayland apps. This ended hours of debugging for me thanks to this thread.
