### ISSUE TITLE
When I switch from hyprland to tty and from tty back to hyprland, hyprland crashes

### ISSUE THREAD

**Issue by MchalTesla** [hyprwm/Hyprland#3023]
### Hyprland Version

Hyprland, built from branch main at commit 37a211a2ae94abad0f606433a58603e70261d0bb dirty (animations: add slidefade and slidefadevert styles for workspaces (3008)). Tag: v0.28.0-65-g37a211a2

### Bug or Regression?

Bug

### Description

When I switch from hyprland to tty, and then switch back from tty to hyprland, hyprland will fail. The failure shows that the waybar fails, the window is translucent and cannot be locked, and the virtual desktop cannot be locked when switching left and right (it cannot be fixed to a suitable position).
My laptop is ASUS FX507ZM, I used supergfx to turn off the NVDIA graphics card

### How to reproduce

Switch from hyprland to tty, and from tty back to hyprland

**Comment by MightyPlaza** [comment]
if crashing provide crash log

**Comment by MchalTesla** [comment]
https://paste.sh/TqKMqmza#5y-eyV8Y6Jfm1bRcYbN-TRLA
I borrowed another logger who had the same problem as me

**Comment by MightyPlaza** [comment]
not crash report
https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md#obtaining-the-hyprland-crash-report-v0220beta-and-up

**Comment by memchr** [comment]
Does your system use systemd? Can you post the result of `coredumpctl`?

**Comment by Yi-Qing** [comment]
I have a similar phenomenon, but I won't crash, I just can't switch workspace.

If switch to another workspace, the screen will get stuck in the previous workspace content. Switching back to the previous workspace will lose all windows and only display layers. 

It seems that the main problem is that I set the `drop_shadow = false`.
---------
OS: Arch Linux
Hyprland version: `0.29.0` commit:`a78f6031c8fcc6773f136fccde3d560aaac239d`

**Comment by uoou** [comment]
Yep, weird as it sounds, can confirm that if `drop_shadow = yes` then there's no problem. Whereas if `drop_shadow = no` then switching back from other TTY is broken.

(for me, when I switch back from another TTY everything looks fine until I try to switch workspace. It looks like it works but every workspace besides the one I came back to appears empty)

**Comment by vaxerski** [comment]
> It seems that the main problem is that I set the `drop_shadow = false`

![image](https://github.com/hyprwm/Hyprland/assets/43317083/e01e1585-e661-4e35-b2cd-e9d4a2d194cd)

how

**Comment by romanstingler** [comment]
@vaxerski is this resolved ??

**Comment by vaxerski** [comment]
no clue but I'd say so, if it isn't a new issue will spring up
