### ISSUE TITLE
Eclipse Bug

### ISSUE THREAD

**Issue by cristiangrossano** [hyprwm/Hyprland#3027]
### Hyprland Version

Hyprland, built from branch main at commit 942ee943f5b0f3f9611b2ff5481dacf19aed6a17 dirty (input: unify constraint hint logic).

### Bug or Regression?

Bug

### Description

Java Eclipse glich and don't show suggestions.

https://github.com/hyprwm/Hyprland/assets/81424772/768eca3b-3a9e-4dfe-91cf-f3048b85f467

### How to reproduce

Activating suggestions in the preferences of eclipse, then writing something for getting an suggestion.

**Comment by MightyPlaza** [comment]
is this still happening?

**Comment by izmyname** [comment]
I guess not?
