### ISSUE TITLE
Hyprland eat CPU

### ISSUE THREAD

**Issue by neuromagus** [hyprwm/Hyprland#303]
![20220704_17h41m51s_grim](https://user-images.githubusercontent.com/63796667/177177261-77489d88-2f5d-47c0-8092-56051a167621.png)

Arch linux, hyprland-bin 0.6.2-beta

in idle hyprland eat 11-12% cpu!

P.S. config - default (only bind changes and layout (customized Dvorak)), GPU -Intel. Installed with all depends.
P.P.S. Hyperland have layout for simulating DWM behavior? Master window? And factor master area? Changing 50/50 tiling to another factor (1/3 - xmonad or 0.64 - DWM)?

**Comment by n1rdeks** [comment]
River, DWL have this problem before... After changed ver wlroots (damage blah-blah) now all fine.

**Comment by vaxerski** [comment]
> After changed ver wlroots (damage blah-blah) now all fine.

?? Hyprland uses almost the latest wlroots from the git head

> Hyperland have layout for simulating DWM behavior? Master window? And factor master area? Changing 50/50 tiling to another factor (1/3 - xmonad or 0.64 - DWM)?

Read the wiki, no.

**Comment by n1rdeks** [comment]
>Read the wiki, no.

thanks, sadly..

**Comment by n1rdeks** [comment]
And I tested Hypr - work fine (need option silent for movewindow, but who cares? Xorg rock solid, but Wayland - future), in idle - 0.7 percents...

**Comment by n1rdeks** [comment]
)) Np. I apologize for that, but u asking for testing, well, I install - cool project. I use Xmonad and DWM (where GHC to large) for daily usage.

P.S. This is hypr
![2022-07-04-180229_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/177180630-6f193703-7efc-43ea-936a-13f70979000f.png)
