### ISSUE TITLE
prevent cursor from entering specific monitor

### ISSUE THREAD

**Issue by M1cha** [hyprwm/Hyprland#3030]
### Description

One of my monitors is a TV which I exclusively use for running RetroArch. Having a way to prevent the mouse cursor from entering that monitor would prevent me from loosing my cursor.

If you currently don't have time to implement this, it'd be great if you could explain what you'd like the configuration to look like so I can take a look at it.

**Comment by vaxerski** [comment]
you can move the display to not touch any other and the mouse won't travel from/to it.
