### ISSUE TITLE
Silent crash on `std::runtime_error` with libc++

### ISSUE THREAD

**Issue by jbeich** [hyprwm/Hyprland#3031]
### Hyprland Version

v0.28.0-70-gfff118fa

### Bug or Regression?

Bug

### Description

According to [`std::runtime_error`](https://en.cppreference.com/w/cpp/error/runtime_error) there's no default behavior to print diagnostics on exit. GCC-based distros use libstdc++ by default where this isn't an issue but many Clang-based distros use libc++ where uncaught `std::runtime_error` results in a crash without error messages. Affects at least FreebSD, OpenBSD, ChimeraLinux.

### How to reproduce

```
$ export CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++
$ meson setup /tmp/hyprland_build
$ meson compile -C /tmp/hyprland_build -c /dev/null
$ env -u XDG_RUNTIME_DIR /tmp/hyprland_build/src/Hyprland
Abort trap
```

```c++
$ cat a.cc
#include <stdexcept>

int main(void)
{
    throw std::runtime_error("test");
    return 0;
}

$ g++ -stdlib=libc++ a.cc
$ ./a.out
Abort trap

$ g++ -stdlib=libstdc++ a.cc
$ ./a.out
terminate called after throwing an instance of 'std::runtime_error'
  what():  test
Abort trap
```

**Comment by vaxerski** [comment]
done in 7713daa86adf7980fd73cae40203ab6deb6be8b8

**Comment by jbeich** [comment]
7713daa86adf doesn't cover all `std::runtime_error` instances in Hyprland source. For example, lack of an error message about `XDG_RUNTIME_DIR` is what caused https://github.com/hyprwm/hyprland-wiki/issues/308 isn't covered.

**Comment by vaxerski** [comment]
woops my bad

**Comment by vaxerski** [comment]
fixd

**Comment by jbeich** [comment]
A few more left that likely handle pilot errors, so important to log:
https://github.com/hyprwm/Hyprland/blob/63b2189ce81f08ca77894f50e3d484902283189a/src/config/ConfigManager.cpp#L1873
https://github.com/hyprwm/Hyprland/blob/63b2189ce81f08ca77894f50e3d484902283189a/src/Window.cpp#L518

**Comment by jbeich** [comment]
Ditto src/config/ConfigManager.cpp, so nevermind.
