### ISSUE TITLE
Qt flags for xwaylandvideobridge support

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/Hyprland#3033]
### Description

It would be nice if hyprland could support following QWindow flags without extra rules:

- `Qt::WindowDoesNotAcceptFocus`
- `Qt::WindowTransparentForInput`

Also setOpacity doesn't seem to be working. Maybe this feature is already planned so we can use this issue to track it post workarounds specifically for people who don't read the full wiki. (like me)

**Comment by vaxerski** [comment]
how are they implemented? haven't seen much about this in the wayland xdg-shell spec. Maybe it's related to the `wl_surface.input_region`?

**Comment by Mikilio** [comment]
If you're asking me I might as well just do a PR XD. This really isn't urgent I'll see if I get to it.

**Comment by vaxerski** [comment]
Feel free, I don't work at qt and have no idea how those flags are implemented. For windows, `.input_region` is ignored, yes.

**Comment by Mikilio** [comment]
Closing as no one ever actually complained about setting rules for it.
