### ISSUE TITLE
[Question] WLroots Vulkan renderer questions

### ISSUE THREAD

**Issue by Ratatouilledummie** [hyprwm/Hyprland#3037]
### Hyprland Version

Hyprland, built from branch makepkg at commit b79dfcceb45669cac3cfae0be0b2146c725d7a7a 

### Bug or Regression?

Bug

### Description

I had just modified a single line in Hyprland-git AUR package to build with vulkan renderer "-Drenderers=gles2,vulkan" and add in /etc/envirolment a line "WLR_RENDERER=vulkan" but after reboot i can't find what WLR renderer is using get a log, just appear a code and wlr render info, but nothing about if is using OpenGLES Renderer or Vulkan as renderer.

Question: 
1. how i can get this wl_renderer information?
2. Hyprland contains a internal shaders and decorations, this supports vulkan?
3. Hyprland don't support vulkan as backend?

### How to reproduce

Just build WLRoots library with Vulkan renderer enabled in meson options and set a env var as "WLR_RENDERER=vulkan"

**Comment by vaxerski** [comment]
hyprland doesn't use the wlroots renderer and does not support vulkan

**Comment by Ratatouilledummie** [comment]
Had a plan to support vulkan in future?

**Comment by vaxerski** [comment]
no
