### ISSUE TITLE
High output latency

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#3039]
### Hyprland Version

v0.28.0

### Bug or Regression?

Bug

### Description

Textures in fast paced games looks like they're fuzzy/vibrating when moving quickly while the cursor feels choppy in its movement.

### Workaround?

This can be reproduced in Sway 1.8.1 / wlroots 1.6.2 as well as Sway 1.9.0-dev / wlroots 1.7.0-dev. **However it can be fixed by disabling Direct Scanout (`$ sway -Dnoscanout`) which makes the experience very similar to X11/DWM.**

### What I've tried

* This can't be resolved by disabling direct scanout nor vfr with Hyprland:
   ```ini
   monitor = DP-3, 3840x1600@119.982002, 0x0, 1, bitdepth, 8
   
   misc {
       vrr = 1
       vfr = 0
       no_direct_scanout = 1
   }
   ```
* Furthermore starting Gamescope under Hyprland (in a nested session) doesn't make a difference.

### How to reproduce

1. Play any fast paced game like Halo Infinite (XWayland) via Proton which is free in Steam (e.g. use Custom Game > Create Match > Play).
2. Move cursor around while standing still.
3. FPS should preferably be below monitor's refresh rate to easily spot it (however, it can also be observed when it's the same as monitor's refresh rate).

### Crash reports, logs, images, videos

N/A

**Comment by vaxerski** [comment]
vfr should never be disabled. If anything, vrr is better to disable to test.

**Comment by GrabbenD** [comment]
Good observation @vaxerski 
Just for clarity, the choppiness is the same whether or no VFR is disabled.
Please let me know if there's any other options which I could try toggling or any test(s) that I can run to properly debug this issue!

**Comment by GrabbenD** [comment]
I've verified that damage tracking isn't causing it:
```ini
debug:damage_tracking = 0
```

Furthermore I made sure Hyprland has the right cap (which seems to be a performance optimization of Sway https://github.com/swaywm/sway/pull/6994) but it made no difference either:
```console
sudo setcap 'cap_sys_nice=eip' $(which Hyprland)
dbus-run-session Hyprland
```

(This was tested with latest -git https://github.com/hyprwm/Hyprland/commit/41d9b6f0d72947de1b0871795f8d8af32d0e9f98)

**Comment by GrabbenD** [comment]
@vaxerski I can't actually see any significant difference between `0`, `1`, `2` with `misc:vrr`. Seems like vblank update rate is the culprit here!

This was tested on a RX 6800 XT with AW3821DW (which has a refresh range of 1 - 144Hz).
VRR works in Sway [as long as direct scanout is disabled](https://github.com/swaywm/sway/issues/7370) and without any issues in X11 (DWM & BSPWM).

**Comment by GrabbenD** [comment]
I've concluded that this is mostly a upstream issue after comparing different compositors with various settings: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3721

**Comment by vaxerski** [comment]
I will close it here then
