### ISSUE TITLE
Set wallpaper

### ISSUE THREAD

**Issue by xyproto** [hyprwm/Hyprland#304]
Hi, author of [wallutils](https://github.com/xyproto/wallutils) here. I wish to add support for Hyprland, but I can not find a way to set the wallpaper when Hyprland is running.

Is there a method or utility that can be used?

**Comment by vaxerski** [comment]
[swaybg](https://github.com/swaywm/swaybg) works well, and if you want to test out the new utility from me, (still early indev though) [hyprpaper](https://github.com/hyprwm/hyprpaper)

**Comment by xyproto** [comment]
Thanks for the reply and pointers!

**Comment by vaxerski** [comment]
haha pointers hee hee i love pointe-

Process Vaxry exited with signal SIGSEGV

**Comment by xyproto** [comment]
The latest release of `wallutils` now also supports Hyprland, by using `swaybg`.
