### ISSUE TITLE
Monitors no longer auto-position correctly.

### ISSUE THREAD

**Issue by ApproachingApathy** [hyprwm/Hyprland#3043]
### Hyprland Version

Hyprland, built from branch main at commit 17d8e4750bd79e0d18b5d0c9f578f23fa47552f4 dirty (Nix: remove waybar completely). Tag: v0.28.0-76-g17d8e475  flags: (if any)

### Bug or Regression?

Bug

### Description

After updating to the latest git version, my third auto-positioned monitor is no longer positioned correctly. Namely, the monitor is positioned far away from the other two. This means I can't mouse over to it and can only reach it by using keybinds. 

Below is my monitor config. With this  config I would expect my monitor to position eDP-1 at 0x0, HP at 2256x0, and my last monitor, DP-6, at 4816x0. Instead, for some reason, DP-6 is placed at 7072. It looks like it's moving DP-6 an additional 2256 (the width of eDP-1).
```
monitor = , preferred, auto, auto
monitor = eDP-1, preferred, auto, 1
monitor = desc:HP Inc. HP X27i CNK0410H0R, 2560x1440@144, auto, auto
```

![Watershot_21-08-2023_09:37](https://github.com/hyprwm/Hyprland/assets/26229099/b77ebeab-e065-4e88-9f06-00482a43a460)

### How to reproduce

I'm not sure if this happens on all three-monitor setups or just mine. Start hyprland with three monitors with auto positioning set.

**Comment by vaxerski** [comment]
eDP-1 should be at 4816x0, but for some reason isn't.

**Comment by vaxerski** [comment]
can you update to 9977a8bfd4f5fcf932880b72f1271546c401f783 and give the log?

**Comment by vaxerski** [comment]
oops, I made a mistake in the original commit. Sorry, can you pull head again and share the log?

**Comment by ApproachingApathy** [comment]
Sorry I missed this for a bit. Here's the new log. 
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12430245/hyprland.log)

**Comment by vaxerski** [comment]
should be fixed.
