### ISSUE TITLE
How to use pywal colors in border?

### ISSUE THREAD

**Issue by XxRiKxX** [hyprwm/Hyprland#3044]
### Description

seems like the hex color format used by pywal is not working.

**Comment by memchr** [comment]
> hex color format used by pywal is not working

Can you be more specific? 

> added the enhancement label 13 minutes ago

And this does not look like a [feature request] at all.

**Comment by vaxerski** [comment]
`sed`?

**Comment by XxRiKxX** [comment]
how to use sed for this?
