### ISSUE TITLE
Hide cursor on key press

### ISSUE THREAD

**Issue by ItsProfessional** [hyprwm/Hyprland#3045]
### Description

If this option is enabled, the cursor should hide if the user starts to type something, and show up again if the user moves their mouse.

Essentially a hyprland port of xbanish. Sway also has this feature (`seat * hide_cursor when-typing enable`)

**Comment by vaxerski** [comment]
every time I get pinged I'll postpone the FR by a week. I have watch set to all, I see all the activity, no need to push annoying notifications to my phone by pinging.

**Comment by taigrr** [comment]
Hey vaxerski  (no ping!), now that the plugins are more front-and-center, would this be possible to do in a plugin or perhaps somewhere inside of hyprcursor? Knowing a bit more about client-drawn vs server-drawn cursors I'm not totally sure where it would be best implemented, but I'm interested in this

**Comment by vaxerski** [comment]
I mean it's a fair core feature, but I gotta unbreak timeout too cuz I break that constantly I feel like lmao

it's just a few loc probably, not a big deal

**Comment by vaxerski** [comment]
enjoy

**Comment by taigrr** [comment]
ko-fi secured
