### ISSUE TITLE
Chrome context menu rounded corners not working on Wayland

### ISSUE THREAD

**Issue by rakibdev** [hyprwm/Hyprland#3046]
### Hyprland Version

v0.28.0-3-g2e6693fb

### Bug or Regression?

Bug

### Description

hyprland.conf
`decoration {
    rounding=20
}
`

This happens when it's a chrome or electron app running under wayland (not xwayland). Thought it was chromium issue but it doesn't happen if there are more than one window/not fullscreen.

### How to reproduce

Description.

**Comment by vaxerski** [comment]
context menus are controlled by the toolkit, hyprland does not round them
