### ISSUE TITLE
Discord screen sharing still not working even after applying patch

### ISSUE THREAD

**Issue by secretknowledge** [hyprwm/Hyprland#3047]
### Hyprland Version

Hyprland, built from branch main at commit 09cc96c0d57512e9db801a3888a0d9c773c79dc2 dirty (feat(debug): add debug:suppress_errors to suppress errors. (3032)). Tag: v0.28.0-73-g09cc96c0

### Bug or Regression?

Bug

### Description

Recently after installing Hyprland on my computer I realized Discord screen sharing did not work. As recommended by the wiki, I followed [this](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580) guide on fixing screen sharing. This did not appear to work actually made things worse, breaking audio and mic. I managed to to fix that by installing the pipewire-pulse package.

### How to reproduce

Install Hyprland (on arch) with Nvidia card, install Discord, apply patch.

**Comment by vaxerski** [comment]
nvidia moment + you are probably launching discord in xwayland
