### ISSUE TITLE
Could Hyprland add dynamic wallpaper support?

### ISSUE THREAD

**Issue by hyq12358** [hyprwm/Hyprland#305]
For example, to set mac OS `.heic` image as wallpaper.
This should be cool.

**Comment by vaxerski** [comment]
Hyprland does not provide a wallpaper system at all. Anything you do to modify Hyprland in order to get a wallpaper is not intended.

As the wiki states:
![image](https://user-images.githubusercontent.com/43317083/177202876-9aa3a168-c40b-4bd6-b98b-1b730e7eed92.png)

**Comment by xyproto** [comment]
The very latest release of Wallutils (5.11.1) can now be used for setting .heic images as wallpapers also under Hyprland:

```sh
curl -O 'https://cdn.dynamicwallpaper.club/wallpapers/3mj0fahqhsv/Dome.heic'
sudo heic-install Dome.heic
settimed Dome
```
