### ISSUE TITLE
need headless monitors

### ISSUE THREAD

**Issue by gfhdhytghd** [hyprwm/Hyprland#3050]
### Description

On sway, there's some thing like this, and it can create a virtual monitor

output HEADLESS-1 {
pos 1200,0
mode 2048x1536
bg ~/tausta_kuva fill #002633
transform 90
}

this virtual monitor can be used like this 

wayvnc --output=HEADLESS-1 192.168.8.20 5900

so then an ipad could be used as a second monitor

My schoon have just banned me from using monitors other than the built-in monitor, but I'm addicted to dual screens, so I hope this feature could be added in the future

**Comment by vaxerski** [comment]
you can use `hyprctl output`, refer to the wiki. Doesn't that do the same?

**Comment by gfhdhytghd** [comment]
oh sorry I miss that
