### ISSUE TITLE
After enabling waybar blur, when other windows are in full screen mode, waybar exit will have an additional lag panel delay to exit.

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#3051]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any) debug

### Bug or Regression?

Bug

### Description

After enabling waybar blur, when other windows are in full screen mode, waybar exit will have an additional lag panel delay to exit.

https://github.com/hyprwm/Hyprland/assets/30348075/27ef9276-e996-4f41-bf99-f9bb8d6a5d92

### How to reproduce

1.set hyprland decoration  config:
    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = true
        xray = true
        blurls = waybar
    }

2.fullscreen any window

**Comment by tchofy** [comment]
Does the same happen with ``layerrule = blur,waybar``? I don't know if they're the same in the code, but I remember getting an error when they introduced ``layerrule``

**Comment by DreamMaoMao** [comment]
> Does the same happen with `layerrule = blur,waybar`? I don't know if they're the same in the code, but I remember getting an error when they introduced `layerrule`

when use :  `layerrule = blur,waybar`  , there is  the same problem.
