### ISSUE TITLE
Cursor still blurry on XWayland when using xwayland force_zero_scaling = on

### ISSUE THREAD

**Issue by Jackaed** [hyprwm/Hyprland#3054]
### Hyprland Version

Hyprland, built from branch  at commit  dirty (). Tag: ?  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Minor gripe with the xwayland force_zero_scaling option, but the cursor remains blurry/pixelated on xwayland applications regardless of the setting, as it gets scaled similarly to how an application is scaled with the setting off.

### How to reproduce

Use a HiDPI display, set xwayland force_zero_scaling to on, and observe the blurry cursor on xwayland applications if using a scaling greater than 1.

**Comment by vaxerski** [comment]
limitation of xwayland
