### ISSUE TITLE
nix/wlroots-hidpi.patch сontains an error

### ISSUE THREAD

**Issue by h0tc0d3** [hyprwm/Hyprland#3055]
### Hyprland Version

git

### Bug or Regression?

Bug

### Description

Compilation Error log:

```
ayland_xwm.c.o.d -o subprojects/wlroots/libwlroots.a.p/xwayland_xwm.c.o -c ../subprojects/wlroots/xwayland/xwm.c
../subprojects/wlroots/xwayland/xwm.c: In function 'xwm_handle_unmap_notify':
../subprojects/wlroots/xwayland/xwm.c:1145:23: error: 'xcb_unmap_notify_event_t' has no member named 'atom'
 1145 |                 if (ev->atom == xwm->atoms[XWAYLAND_GLOBAL_OUTPUT_SCALE]) {
      |                       ^~
../subprojects/wlroots/xwayland/xwm.c:1147:55: error: 'xcb_unmap_notify_event_t' has no member named 'atom'
 1147 |                                         ev->window, ev->atom, XCB_ATOM_ANY, 0, 2048);
      |    
```

An error in the code. `ev` is of type `xcb_unmap_notify_event_t` and does not contain an atom.

```C
#include <xcb/xproto.h>

typedef struct xcb_unmap_notify_event_t {
  uint8_t response_type;
  uint8_t pad0;
  uint16_t sequence;
  xcb_window_t event;
  xcb_window_t window;
  uint8_t from_configure;
  uint8_t pad1[3];
} xcb_unmap_notify_event_t;
```

Reference: https://www.x.org/releases/current/doc/man/man3/xcb_unmap_notify_event_t.3.xhtml

### How to reproduce

```
patch -p1 < wlroots-hidpi.patch
compile hyprland git && wlroots git
```

**Comment by h0tc0d3** [comment]
With patches from [wlroots-hidpi](https://aur.archlinux.org/packages/wlroots-hidpi-xprop-git), the compilation works.

**Comment by q234rty** [comment]
Looks to me like you haven't applied the patch correctly, but the wlroots-hidpi.patch in this repo is no longer being maintained anyway, see https://github.com/hyprwm/Hyprland/pull/2870
If `xwayland:force_zero_scaling` does not fit you use case, feel free to use https://aur.archlinux.org/packages/hyprland-hidpi-xprop-git, but please report any issue you encounter that might be related to Xwayland HiDPI there first.

**Comment by vaxerski** [comment]
aren't the patches removed now? @fufexan

**Comment by fufexan** [comment]
Oops, I forgot to remove them. I will now.

**Comment by fufexan** [comment]
Removed.

**Comment by vaxerski** [comment]
closing then
