### ISSUE TITLE
X wayland screen share low FPS when not on monitor

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/Hyprland#3057]
### Description

When I screen share a Xwayland window (in my case xwaylandvideobridge) on discord it runs fine if the streamed window is present on one of my monitors. However, if I switch workspaces and the streamed window isn't on either of my monitors anymore the stream display in around 1 FPS.

Of course this does not happen on a normal screen share via pipewire. Also, not rendering all frames of a window, that is not visible, is probably intended behavior.

Right now I am working around the issue with a small script that listens on an IPC socket and moves my xwaylandvideobridge to my active workspace at the monitor I'm on.

However I would like to request a variable or a mode that allows for xwayland windows or windows in general to stay on the active workspace or be rendered actively.

**Comment by romanstingler** [comment]
try config, `misc.vfr=false`
http://wiki.hyprland.org/Configuring/Variables/#misc

**Comment by vaxerski** [comment]
that wont help. It's due to the way wayland works in general. It's been requested somewhere iirc

**Comment by Mikilio** [comment]
Can we maybe use a special workspace for this?

**Comment by Mikilio** [comment]
Yeah ... I'm actually sorry for being so blind. But since I'm probably not the only blind person it would be nice to have a reference to in in the monitors section as well. I will close this issue though because it's solved for me.
