### ISSUE TITLE
Release binds don't properly work in submaps

### ISSUE THREAD

**Issue by nenikitov** [hyprwm/Hyprland#3058]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty ()

### Bug or Regression?

Bug

### Description

There is an inconsistent behavior when creating submaps that deactivate on release. Relevant config is in "How to reproduce".
- The submap works, pressing `SUPER s` triggers it, and releasing exits it (as long as I don't press any keys in between)
- Pressing any key (no matter if it is a valid bind or not) breaks exiting out of the submap

### How to reproduce

1. Add this to your config:
    ```py
    bind = SUPER, s, submap, resize

    submap = resize

    binde = SUPER, h, resizeactive, -20, 0
    # None of these will trigger reset
    bindr = SUPER, s, submap, reset
    bindr = SUPER, SUPER_L, submap, reset
    bindr = , s, submap, reset

    submap = reset
    ```
2. Resize a window by holding `SUPER + s + h`
3. Let go of `SUPER + s + h`
4. Notice that you are still on the submap resize, even despite releasing the keys `SUPER` or `s`
    - You can resize the window with `SUPER + h`
    - Other keybinds don't work
    - Shouldn't a release of `SUPER` or `s` have triggered any of the `submap, reset` dispatchers?
5. To leave the submap, press and release `SUPER + s`

**Comment by vaxerski** [comment]
all the binds get shadowed by activating SUPER+H

for the same reason that you don't want your SUPER,Super_L bind activated when you press your bind on SUPER+C for example.

It's planned somewhere as transparent binds.

**Comment by vaxerski** [comment]
```
bindr = SUPER, s, submap, reset
```
vvvv
```
bindrt = SUPER, s, submap, reset
```
and it now seems to work alright to me.

**Comment by nenikitov** [comment]
Thank you, works exactly how I wanted. Here is my config now:
```py
bind = SUPER, s, submap, resize
submap = resize
binde = SUPER, h, resizeactive, -20 0
binde = SUPER, l, resizeactive, 20 0
binde = SUPER, k, resizeactive, 0 -20
binde = SUPER, j, resizeactive, 0 20
bindrt = SUPER, s, submap, reset
submap = reset
```
