### ISSUE TITLE
Segfault when using tilde in path for input.kb_file

### ISSUE THREAD

**Issue by t-veor** [hyprwm/Hyprland#3060]
### Hyprland Version

Hyprland, built from branch main at commit 41d9b6f0d72947de1b0871795f8d8af32d0e9f98 dirty (dwindle: use smart on display borders (2897)). Tag: v0.28.0-81-g41d9b6f0  flags: (if any)

### Bug or Regression?

Bug

### Description

Hyprland segfaults if you use `~` in your path specification for `input.kb_file`. I didn't dig too deep into it, but it looks like the issue is here:
https://github.com/hyprwm/Hyprland/blob/17ea7db23a21a3150343b3ab0c9404dff8d198b8/src/managers/input/InputManager.cpp#L784-L794

`FILEPATH` is resolved into an absolute path, checked to see if the file exists... and then the unresolved `FILEPATH` is passed into `fopen`. So, if `FILEPATH` was `~/.config/hyprland/mykeymap.xkb`, it gets expanded into `/home/username/.config/hyprland/mykeymap.xkb`, which `std::filesystem::exists` reports exists. Then, `~/.config/hyprland/mykeymap.xkb` is passed into `fopen`, which returns `NULL`. There's no null pointer check on `KEYMAPFILE`, so `xkb_keymap_new_from_file` blows up.

(In this case, wouldn't it be better to just try and go ahead and open the file first... and then check if it's `NULL`, instead of trying to use `std::filesystem::exists`? Since something else on the system could delete/move/rename the file in between the `std::filesystem::exists` check and actually opening it with `fopen`.)

When doing a search through the repository I also found this code which is vulnerable to this issue, although it doesn't appear to be the cause of my segfault: https://github.com/hyprwm/Hyprland/blob/17ea7db23a21a3150343b3ab0c9404dff8d198b8/src/managers/KeybindManager.cpp#L145-L148

### How to reproduce

Ensure a file called `existing_file.xkb` exists in your home directory:
```bash
touch ~/existing_file.xkb
```

Put this in your `hyprland.conf`:
```
input {
  kb_file = ~/existing_file.xkb
}
```

launch Hyprland.

### Crash reports, logs, images, videos

[crash.txt](https://github.com/hyprwm/Hyprland/files/12424218/crash.txt)

**Comment by memchr** [comment]
A grave mistake indeed. tlide(`~`) is interpreted by the shell, not the c library function.

While `std::filesystem::exits` yield truðy if file exists, it doesn't care if file is readable by the current process. So that's one reason to check the fopen result.
