### ISSUE TITLE
is misc:background_color not yet impletemented, but in the wiki?

### ISSUE THREAD

**Issue by evelinwillow** [hyprwm/Hyprland#3062]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0

### Bug or Regression?

Bug

### Description

The config file entry background_color in the category misc does not work. Since it seems to have been added after v.0.28 (due to not being present in the wiki of v.0.28.0, but the latest git version), i just rebuilt from source - i still get a "config error [...] for field <misc:background_color>: No such field.

There is a decent change i am an idiot and i messed something up; but i can't seem to figure out what. I tried to verify if my build from source actually installed properly, but i did a stupid and forgot to write down the output of hyprctl version beforehand.

Sorry for wasting your time and thanks a bunch for this awesome WM btw, absolutely in love with it.

### How to reproduce

1) Be stupid
2) Add background_color = #ffbcd9 or background_color = 0xffbcd9 to the config file under "misc"
3) :wq
4) ???
5) Sadness

### Crash reports, logs, images, videos

uhhhhhhh i cannot figure out the naming scheme of the logs have the entire directory im sorry

i just tar -c'd all of this
![image](https://github.com/hyprwm/Hyprland/assets/105907940/78f6c602-f855-478e-99dc-715836ad613e)
i hope it worked it cried about sockets but i think it just skipped them

[logs.tgz](https://github.com/hyprwm/Hyprland/files/12426605/logs.tgz)

**Comment by evelinwillow** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/105907940/6ceb5c6a-5eb4-4912-b148-2fbec8a70baa)
thats the error message (in case you forgot what your error messages look like...)

**Comment by evelinwillow** [comment]
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/12426674/hyprland.txt)

Here's my config, by the way.

**Comment by memchr** [comment]
Please update your local build, your source is out of date.

**Comment by memchr** [comment]
Any documented change in the wiki reflects existing commits or merged PRs.

**Comment by evelinwillow** [comment]
But i literally just did minutes ago?? I'll try again, then

**Comment by evelinwillow** [comment]
So as it turns out, i had foolishly assumed that running the commands listed under "Manual Build" on the wiki would actually install the built files;
This is not the case. Thank you very much for your help!
