### ISSUE TITLE
if 3 maximize window are on ws they not stay maximized

### ISSUE THREAD

**Issue by kristoferus75** [hyprwm/Hyprland#3065]
### Description

hi !

if i open 3 kitty windows and press

`bind = SUPER, M, fullscreen, 1`

all windows on ws are maximzed

but if i close one window or open window on other monitor

the 2 (or3 ) remaining windows become tiled windows 

is that a normal behavior or a bug or it need a feature for ws ?

is it possible that windows in this ws stay maximized ?

hmm even all three windows with window rule configured

windowrule = maximize, kitty

but this seems doesnt matter ? (fullscreenmode:1 )

```
Window 55a4cfb32c90 -> hyprctl clients:
mapped: 1
hidden: 0
at: 2565,25
size: 2550,1410
workspace: 2 (2)
floating: 0
monitor: 1
class: kitty
title: hyprctl clients
initialClass: kitty
initialTitle: bash
pid: 2513
xwayland: 0
pinned: 0
fullscreen: 1
fullscreenmode: 1
fakefullscreen: 0
grouped: 0
swallowing: 0
```

hmm in dwm the windows stay in monocle mode because all opened and new windows would be maximized then and if i press keybinding to tile mode all windows would be tiled but if i have a rule in dwm to open window float then only that window is floating but the rest stay maximized or tiled because of the monocle or tiled mode and that is what i want -> i don't want that windows change to tiled if i open a new windows or close a window or open a window in other monitor

thanks

regards

**Comment by MightyPlaza** [comment]
`hyprctl dispatch exec [maximize] kitty`

**Comment by kristoferus75** [comment]
what should this command help ?

sorry it happens also if i 
if i close one window (not kitty) on same monitor  or open a window (not kitty) on other monitor
the maximized windows become tiled 

i don't want that windows become tiled automatically if i don't want it ?!

Sorry that's a little comic behavior -> so i need to press always again SUPER, M

**Comment by kristoferus75** [comment]
its ok that if i open a tiled window on same ws that
