### ISSUE TITLE
Cannot `switchxkblayout` for keyboards having newline in `name`

### ISSUE THREAD

**Issue by rbroggi** [hyprwm/Hyprland#3066]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0

### Bug or Regression?

Bug

### Description

```
❯ hyprctl devices -j | jq '.keyboards[] | select(.name | contains("annepro2-key"))'
{
  "address": "0x557bc50375a0",
  "name": "obins-obins\nannepro2-keyboard",
  "rules": "",
  "model": "",
  "layout": "us,us",
  "variant": ",intl",
  "options": "",
  "active_keymap": "English (US)",
  "main": false
}
```

notice the name `obins-obins\nannepro2-keyboard`. 

the command without `-j` leads to:

```
        Keyboard at 557bc50375a0:
                obins-obins
annepro2-keyboard
                        rules: r "", m "", l "us,us", v ",intl", o ""
                        active keymap: English (US)
                        main: no
```

the swithc command is not capable to match the keyboard name with the name in the json format:

```
❯ hyprctl switchxkblayout "obins-obins\nannepro2-keyboard" next
device not found
```

I tried with and without quotes without them, defining a variable and several other ways, would it make sense to support a flag that allows us to define using the `address` property instead of name if we don't come up with a sensible strategy? 

### How to reproduce

above explanation.

**Comment by vaxerski** [comment]
wat de foq why would anyone do this
