### ISSUE TITLE
I want to get the candidate column information of Fcitx5

### ISSUE THREAD

**Issue by PILIHU2022** [hyprwm/Hyprland#3068]
# I want to set the transparency of the candidate bar of Fcitx5 separately, but I can't get its title and other information. What should I do to get its title and other information?

# **I am not good at English,so I translated it**

**Comment by JustSimplyKyle** [comment]
try these
```
windowrule=opacity 0.6 override 0.6 override,^(fcitx)$
```
this will match the candidates for xwayland applications

**Comment by JustSimplyKyle** [comment]
for wayland applications, classes would get disappeared, and I'm not sure whether if it's possible to match against initialClass
![image](https://github.com/hyprwm/Hyprland/assets/68589851/d4de11a6-0918-4f2f-bcd6-6fff7137e25f)

**Comment by PILIHU2022** [comment]
> try these
> 
> ```
> windowrule=opacity 0.6 override 0.6 override,^(fcitx)$
> ```
> 
> this will match the candidates for xwayland applications

Thank you for your help! Have a nice day!
