### ISSUE TITLE
Misplaced windows and popups

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#3069]
### Hyprland Version

0.28.0.r73.09cc96c0

### Bug or Regression?

Bug

### Description

Since recently, windows started behaving weird.

The "move to trash" popup in Nemo started opening in the upper left corner of my screen, with only a tiny part visible. I always have to drag it back to actually see all buttons.

In Zrythm and Steam, context menus started appearing on the other screen only (opened left, opens right and the other way around). Somehow, they are still present on the correct screen, since I can only select context menu items on the screen it was supposed to be, and yet they render on the other screen.

### How to reproduce

Use `Del` to remove something in Nemo, right click on something in Zrythm, open a context menu in Steam (this seems a little inconsistent)

### Crash reports, logs, images, videos

https://chonkyrabbit.eu/files/_share/hyprland.log

**Comment by vaxerski** [comment]
I believe it was fixed in 025c023e4bbe22fc61a9dc39a33c0c14495230be

please update

**Comment by UltraBlackLinux** [comment]
oh yes that seems to be the case. 

Thank you so much!

**Comment by UltraBlackLinux** [comment]
Actually, that seems to be only half of my bug report (I guess these were two issues)

Nemo still opens that popup at the wrong location, same with the libre office wrtier splash: 
![image](https://github.com/hyprwm/Hyprland/assets/62404294/30237f68-00b6-4ba6-a2eb-a509891b2c3c)

**Comment by vaxerski** [comment]
LOs writer splash has always been misplaced for me.

If xwayland, #3029

**Comment by vaxerski** [comment]
should be fixed.

**Comment by UltraBlackLinux** [comment]
awesome, thank you! (~~I'm always amazed at the speed at which you fix these things. Do you even do anything else apart from hyprland development?~~)

**Comment by vaxerski** [comment]
>  (I'm always amazed at the speed at which you fix these things. Do you even do anything else apart from hyprland development?)

yes, as evident by the following:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/45cbb82c-6935-487d-b520-0153d19cd0b2)
