### ISSUE TITLE
Broken XWayland scaling on monitors with different resolutions

### ISSUE THREAD

**Issue by SapuSeven** [hyprwm/Hyprland#3070]
### Hyprland Version

v0.28.0, built at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25

### Bug or Regression?

Bug

### Description

I have 2 monitors: one 1080p (DP-2) and one 2160p (DP-1).
Following the instructions from the [Hyprland Wiki](https://wiki.hyprland.org/Configuring/XWayland/), I added the  changes in my config file (see below).

Using these settings, opening an application with XWayland on the high-res monitor works perfectly, it's scaled correctly and everything is crisp and clear.
However, once I move the window to the low-res monitor, it's scaled incorrectly, meaning everything is twice as large as it should be.

I tried it with disabling `force_zero_scaling` and setting `GDK_SCALE=1`. This makes the application look great on the low-res monitor, but on the high-res monitor it's pixelated (but the scale is correct).

Is there anything I am missing here or is this setup just not supported yet?

### How to reproduce

Connect a low-res and high-res monitor with different scaling factors and use the following config:

```
monitor=DP-1,highres,auto,2
monitor=DP-2,preferred,auto,1

xwayland {
  force_zero_scaling = true
}

env = GDK_SCALE,2
env = XCURSOR_SIZE,32
```

Then open an application with `GDK_BACKEND=x11`.

**Comment by vaxerski** [comment]
with force_zero_scaling it's pixelated on the highres monitor? what if the app is opened on the high res monitor?

generally, solving multi-scale is _not possible_ with xwayland. It physcially cannot do that.

What should happen is that with GDK_SCALE 2 it should be huge on the low-res monitor while with GDK_SCALE 1 it should be tiny on the high-res monitor, but there shouldnt be any pixelation.

**Comment by SapuSeven** [comment]
> What should happen is that with GDK_SCALE 2 it should be huge on the low-res monitor while with GDK_SCALE 1 it should be tiny on the high-res monitor, but there shouldnt be any pixelation.

Yes, that's exactly what's happening (with `force_zero_scaling = true`).

> with force_zero_scaling it's pixelated on the highres monitor? what if the app is opened on the high res monitor?

With `force_zero_scaling = true` there's no pixelation.
Only when setting `force_zero_scaling = false` it's pixelated on high-res.
But at least then the scaling is correct on both monitors.

I remember I used sway with all the hidpi-patches for sway/wlroots/xwayland previously and I managed a setup where everything is sharp and scaled correctly, but the wiki mentioned that the hidpi-patches are not supported anymore.

**Comment by vaxerski** [comment]
well, with force_zero_scaling off, it's expected that apps will be blurry or pixelated when scaled, because xwayland cannot scale.

Without any patching, what you are trying to accomplish is not possible. What you can do is keep force_zero_scale on, and depending on the monitor you want your app to be, alter the `GDK_SCALE` env.

Or, like, avoid xwayland.

**Comment by SapuSeven** [comment]
Alright, good to know. Thanks for your support.
It's just a bit disappointing because some apps I use still don't support Wayland and it would be great to be able to use them on Hyprland without these issues.

**Comment by vaxerski** [comment]
The reasoning behind removing the patches is because they were unstable, required maintenance and generated issue tickets that had nothing to do with hyprland.
