### ISSUE TITLE
XWayland randomly crash when manipulating windows 

### ISSUE THREAD

**Issue by moetayuko** [hyprwm/Hyprland#3071]
### Hyprland Version

Hyprland, built from branch main at commit 90c03e5bd2204ba6d1a0167c68f65b7a9231bef4 dirty (master: layout resize makes the wrong size changes (3064)). Tag: v0.28.0-89-g90c03e5b

### Bug or Regression?

Bug

### Description

XWayland randomly crashes when manipulating windows, such as switching workspace, minimize to tray, close, resize (floating), move (floating), etc. Hyprland itself doesn't crash.

The log attached was captured when minimizing an electron app to system tray.

### How to reproduce

As described above.

### Crash reports, logs, images, videos

[crashlog.log](https://github.com/hyprwm/Hyprland/files/12440084/crashlog.log)
[backtrace.txt](https://github.com/hyprwm/Hyprland/files/12440095/backtrace.txt)

**Comment by izmyname** [comment]
Does it still crash?

**Comment by moetayuko** [comment]
no
