### ISSUE TITLE
Chromium window warping-resizing on startup

### ISSUE THREAD

**Issue by h0tc0d3** [hyprwm/Hyprland#3072]
### Hyprland Version

git

### Bug or Regression?

Bug

### Description

Chrome window warping-resizing strangely on startup.

### How to reproduce

Compile hyprland and start chromium.

### Crash reports, logs, images, videos

Video: https://drive.google.com/file/d/1rwxwrWch77SvMhHxLDKuVF5dvg4gjhrk/view?usp=sharing

**Comment by vaxerski** [comment]
#2588
