### ISSUE TITLE
Emacs swapping frames

### ISSUE THREAD

**Issue by markgdawson** [hyprwm/Hyprland#3073]
### Hyprland Version

0.28.0

### Bug or Regression?

Bug

### Description

Using Emacs commands to switch focus between Emacs windows (frames as Emacs calls them) doesn't work. Emacs can move the cursor, but the original window remains the "active" one which receives keyboard input.

This prevents workflows where Emacs delegates window management to Hyprland (by popping up new frames rather than new buffers).

### How to reproduce

Open Emacs

Create a new frame with `M-x make-frame`.

Try to switch to another frame with `M-x other-frame`.

The cursor will jump, but keyboard input remains in the current window.

**Comment by Dickby** [comment]
@markgdawson This one should be fixed by setting `misc:focus_on_activate=true`.
If so please close this issue.

**Comment by panchoh** [comment]
The fix works like a charm, thanks!

**Comment by Dickby** [comment]
@vaxerski , I think this issue can be closed.
Enabling `focus_on_activate` will deal with this.
Waiting a month for a response should be more than enough!

**Comment by panchoh** [comment]
In case some from the future lands here, there is now a better solution, which is to use a [Window Rule](https://wiki.hypr.land/Configuring/Basics/Window-Rules/) targetting `emacs` windows, and enabling `focus_on_activate` just for them (instead of globally with `misc.focus_on_activate`):

```
hl.window_rule({
  name = "honor-focus-events-for-emacs-windows",
  match = {
    initial_class = "^emacs$"
  },

  focus_on_activate = true
})
```
