### ISSUE TITLE
Can't set GTK/icon theme using `gsettings` under any circumstances

### ISSUE THREAD

**Issue by Andy3153** [hyprwm/Hyprland#3075]
### Hyprland Version

Hyprland, built from branch main at commit 3a1f30519bb3ae265fc4f9cc720513217e928fdb dirty (compositor: fix offset in auto arrangeMonitors). Tag: v0.28.0-92-g3a1f3051

### Bug or Regression?

Bug

### Description

Before anyone says anything, YES, I DID read the [FAQ](https://wiki.hyprland.org/FAQ/#gtk-settings-no-work--whatever) and the [link inside it](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland). I'm (**hopefully**) not stupid

You might ask "why do you want to use `gsettings`?" I'd be so happy if I were able to use something normal like [`nwg-look`](https://github.com/nwg-piotr/nwg-look), but that only changes files the Sway wiki specifically says that the Wayland GDK backend completely ignores.

You also might ask "why don't you use the `GTK_THEME` envvar?" [I am](https://github.com/Andy3153/hyprland-rice/blob/231fd4fd28368b4e91573446b59081844bad8442/dotconfig/hypr/hyprland.conf#L58). But that only changes the GTK theme. You can't change anything else like icon themes or cursors with environment variables.

So, since [`nwg-look`](https://github.com/nwg-piotr/nwg-look) doesn't work, the Wayland GDK backend ignores anything inside `$XDG_CONFIG_HOME/gtk-*`, and environment variables only get me so far, `gsettings` is **all I have left**. And it does not work at all. I can't switch to any GTK/icon theme at all, not even the high contrast ones. It's as if it sees nothing else except Adwaita.

Combining all the time I've spent on this off and on ever since I switched to Hyprland around the beginning of July, I think I spent at least 4 hours just on GTK theming alone. I'm going crazy already. Please help.

### How to reproduce

See attached video.
1. I try applying stuff with `gsettings`
2. I show it's useless, as Adwaita is still applied in both GTK and icon theme sections
3. I try applying stuff with `gsettings`, now having open two terminals where I use the 'monitor' function to actively show changes made
4. I show that I have installed the themes using my package manager
5. I show that the theme files are present inside the filesystem

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/53472302/e529de50-e30f-441e-97f7-7a3291cc7fdd

**Comment by vaxerski** [comment]
I'd love to help you but I have no clue what is wrong.

At any rate, theming is completely separate from hyprland so it's not an issue here.

You can join the discord server and ask around for help there.

IIRC for my icons I just edited the config files manually by hand. Ignore the sway wiki, go with the files on the arch wiki.

**Comment by Andy3153** [comment]
> IIRC for my icons I just edited the config files manually by hand. 
What config files? `$XDG_CONFIG_HOME/gtk-*`?

> Ignore the sway wiki, go with the files on the arch wiki.
You mean [this](https://wiki.archlinux.org/title/GTK#Configuration)?

**Comment by vaxerski** [comment]
> You mean [this](https://wiki.archlinux.org/title/GTK#Configuration)?

yah

**Comment by Andy3153** [comment]
Tried that. Didn't work either. It's the files nwg-look modifies, but I've tried manually modifying them as well

**Comment by jakubreron** [comment]
I might have somewhat related issue, in my case, the gtk theme switch is not instant, I need to restart all gtk apps to apply the new theme, is it supposed to work like this? I didn't find any other theming issues here on github, only this one, so I'm thinking it's something on my side maybe 🤔

**Comment by Andy3153** [comment]
Completely unrelated. At least you can set a theme. And, yes, I'd expect I'd have to reopen a program to set a new theme
