### ISSUE TITLE
wlroots bump causes weird behavior when scale factor is not "auto"

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#3079]
### Hyprland Version

ae69b9a2fa559d869f4e9c61ddf24e152d97df2f

### Bug or Regression?

Regression

### Description

After the wlroots bump, on my single monitor setup with a manually specified scale factor, hyprland seems to freeze when starting but returns to normal after trying to move the pointer using the touchpad. Interestingly, this does not happen when the scale factor is "auto".

### How to reproduce

Use `monitor=,preferred,auto,1` and observe the weird behavior mentioned above.

**Comment by stonewell** [comment]
similar issue when set scale factor to 1, always show default wallpaper, log shows key binding works and process created, but no window show up. only SUPER+M works.
set scale factor to auto has no problem

**Comment by stonewell** [comment]
get workaround is
exec-one = hyprctl keyword monitor ",preferred,auto,1"

**Comment by vaxerski** [comment]
can you bisect wlroots to find the issue? I can't repro

**Comment by stonewell** [comment]
could you describe more how to bisect wlroots? I am pretty new to wayland

**Comment by ferrreo** [comment]
getting this as well will take a look at wlroots to see which commit it is

**Comment by ferrreo** [comment]
@vaxerski it was the literal last commit: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/717ded9bb0191ea31bf4368be32e7a15fe1b8294

Going back to 7bf6c1fc fixes it

**Comment by vaxerski** [comment]
probably worth reporting upstream whenever it's back.

**Comment by ferrreo** [comment]
Raised it upstream here: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3725

Not fully convinced this isn't a hyprland issue though as the wlroots commit doesn't look like it is doing anything hyprland should not handle gracefully.

**Comment by glepnir** [comment]
@stonewell  thanks for your work around. for me is this. because i use 1080p after this I can't see any animation on startup . did you get this ?

```
exec-once = hyprctl keyword monitor ",preferred,auto,auto"`
```

**Comment by mangkoran** [comment]
So for the time being, should we downgrade the `wlroots` until it is fixed upstream?

**Comment by faergeek** [comment]
This patch seems to fix the issue for me, though I'm not entirely sure why exactly, because I have no idea what I'm really doing :-)

```patch
diff --git a/src/render/Renderer.cpp b/src/render/Renderer.cpp
index 1d22935f..e60be91c 100644
--- a/src/render/Renderer.cpp
+++ b/src/render/Renderer.cpp
@@ -1864,6 +1864,8 @@ bool CHyprRenderer::applyMonitorRule(CMonitor* pMonitor, SMonitorRule* pMonitorR
         pMonitor->enabled10bit = false;
     }
 
+    wlr_output_enable(pMonitor->output, 1);
+
     if (!wlr_output_commit(pMonitor->output)) {
         Debug::log(ERR, "Couldn't commit output named %s", pMonitor->output->name);
     }
@@ -1881,8 +1883,6 @@ bool CHyprRenderer::applyMonitorRule(CMonitor* pMonitor, SMonitorRule* pMonitorR
         pMonitor->vecPixelSize = Vector2D(transformedBox.width, transformedBox.height);
     }
 
-    wlr_output_enable(pMonitor->output, 1);
-
     // update renderer (here because it will call rollback, so we cannot do this before committing)
     g_pHyprOpenGL->destroyMonitorResources(pMonitor);
 
```

But before this change https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/717ded9bb0191ea31bf4368be32e7a15fe1b8294 `wlr_output_commit(pMonitor->output)` would go into this "no-op shortcut" for the first time only. And now it's gone.

IIUC this `wlr_output_commit` is only needed for the following call to `wlr_output_transformed_resolution` to make sense, right?

**Comment by vaxerski** [comment]
if that's the case then this should be fixed with 423b129b24a0ff14c5e2898a748b916f892cc0b9, let me know

**Comment by faergeek** [comment]
Yep, seems to work on https://github.com/hyprwm/Hyprland/commit/423b129b24a0ff14c5e2898a748b916f892cc0b9

**Comment by ferrreo** [comment]
@vaxerski working great now. Any chance of a 0.29.1 release with this in it please? I had to keep my package at the 0.28.0 release because this broke too many users.

**Comment by vaxerski** [comment]
0.29.1 will be released today

**Comment by UltraBlackLinux** [comment]
Oh awesome. I was just about to report this earlier today. it's such weird behavior. Glad that it's fixed.
