### ISSUE TITLE
touchpad tap-to-click=false has no effect

### ISSUE THREAD

**Issue by kflak** [hyprwm/Hyprland#3080]
### Hyprland Version

Hyprland, built from branch  at commit b08b72358ad549fd066e5be0fc3aa4c9df367607 dirty (). Tag: v0.27.2  flags: (if any)

### Bug or Regression?

Bug

### Description

Given this configuration:

```input {

    touchpad {
        natural_scroll = true
        tap-to-click = false
    }

    kb_layout = us
    kb_variant = altgr-intl
    kb_options = ctrl:nocaps,altwin:swap_lalt_lwin

    follow_mouse = 1

    natural_scroll = true
}
```
The tap-to-click=false seems to have no effect.

System: Arch LInux 6.4.10-arch1-1

### How to reproduce

Set `input.tap-to-click` to false and see if it actually does what it says...

**Comment by vaxerski** [comment]
please update to -git, you're on a very outdated version

**Comment by kflak** [comment]
Ah, obviously... thanks! This solves the issue for me. Thanks for a beautiful wm! Migrated from sway a couple of weeks ago, and so far very happy!

**Comment by 1player** [comment]
I'm actually having this same issue with an Apple Magic Trackpad 2. Tap to click is disabled on GNOME with no issue:

```
tranquility:~/.config/hypr % hyprctl version
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)
```

Tapping with three fingers to send a MMB event doesn't seem to work either.
