### ISSUE TITLE
wlr_commit_ouptut aborts when using custom resolution.

### ISSUE THREAD

**Issue by memchr** [hyprwm/Hyprland#3083]
### Hyprland Version

ae69b9a2

### Bug or Regression?

Regression

### Description

Since the wlroots commit [e85c7905](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/e85c79051cc5003568ace6a29ce6e13d16796e48), setting a custom mode will cause `wlr_commit_ouptut()` to abort via `drm_connector_state_init()`. As a result, the use of a custom resolution is no longer possible.

Since the above-mentioned commit, wlroots would set `output->current_mode` to NULL when using a custom output mode.

```c
case WLR_OUTPUT_STATE_MODE_CUSTOM:
			output->current_mode = NULL;
```
This results in the failure of the NULL assert within `drm_connector_state_init`.
```c
struct wlr_drm_mode *mode =
			wl_container_of(conn->output.current_mode, mode, wlr_mode);
		assert(mode != NULL);
		state->mode = mode->drm_mode;
```

Based on the references of the `wlr_output.current_mode` , it seems that `output->current_mode` can only be set to NULL or to a pending mode when employing a fixed mode (`WLR_OUTPUT_STATE_MODE_FIXED`), which is clearly not the case when using a custom mode

I am uncertain if this should be reported upstream, therefore creating an issue here initially.

### How to reproduce

Configure the monitor to use a non-standard resolution in hyprland configuration file, such as 
```conf
monitor=,1800x1030,1,1
```

### Crash reports, logs, images, videos

<details>
<summary>callstack</summary>

```python
___lldb_unnamed_symbol3604 (@___lldb_unnamed_symbol3604:77)
raise (@raise:10)
abort (@abort:50)
___lldb_unnamed_symbol3083 (@___lldb_unnamed_symbol3084:3)
__assert_fail (@7ffff7236d26..7ffff7236db2:3)
drm_connector_state_init (/home/arthur/src/tmp/hyprland/subprojects/wlroots/backend/drm/drm.c:473)
drm_connector_test (/home/arthur/src/tmp/hyprland/subprojects/wlroots/backend/drm/drm.c:605)
drm_connector_commit (/home/arthur/src/tmp/hyprland/subprojects/wlroots/backend/drm/drm.c:786)
wlr_output_commit_state (/home/arthur/src/tmp/hyprland/subprojects/wlroots/types/output/output.c:820)
wlr_output_commit (/home/arthur/src/tmp/hyprland/subprojects/wlroots/types/output/output.c:859)
CHyprRenderer::renderMonitor(CMonitor*) (/home/arthur/src/tmp/hyprland/src/render/Renderer.cpp:1106)
Events::listener_monitorFrame(void*, void*) (/home/arthur/src/tmp/hyprland/src/events/Monitors.cpp:161)
void std::__invoke_impl<void, void (*&)(void*, void*), void*, void*>(std::__invoke_other, void (*&)(void*, void*), void*&&, void*&&) (/usr/include/c++/13.2.1/bits/invoke.h:61)
std::enable_if<is_invocable_r_v<void, void (*&)(void*, void*), void*, void*>, void>::type std::__invoke_r<void, void (*&)(void*, void*), void*, void*>(void (*&)(void*, void*), void*&&, void*&&) (/usr/include/c++/13.2.1/bits/invoke.h:111)
std::_Function_handler<void (void*, void*), void (*)(void*, void*)>::_M_invoke(std::_Any_data const&, void*&&, void*&&) (/usr/include/c++/13.2.1/bits/std_function.h:290)
std::function<void (void*, void*)>::operator()(void*, void*) const (/usr/include/c++/13.2.1/bits/std_function.h:591)
CHyprWLListener::emit(void*) (/home/arthur/src/tmp/hyprland/src/helpers/WLListener.cpp:52)
handleWrapped(wl_listener*, void*) (/home/arthur/src/tmp/hyprland/src/helpers/WLListener.cpp:9)
wl_signal_emit_mutable (/usr/src/debug/wayland/wayland-1.22.0/src/wayland-server.c:2241)
wlr_output_send_frame (/home/arthur/src/tmp/hyprland/subprojects/wlroots/types/output/output.c:877)
```

</details>

**Comment by vaxerski** [comment]
should be reported upstream

**Comment by memchr** [comment]
Confirmed upstream bug, there is a pending MR on the wlroots repo that will fix this issue.

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4339
