### ISSUE TITLE
Animations get faster over time.

### ISSUE THREAD

**Issue by Oglo12** [hyprwm/Hyprland#3085]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Bug

### Description

It seems that some animations speed up over time. After a while, closing a window animates for 2 seconds, but after a while, closing takes 1 second, and then later on, the animations are instant!

### How to reproduce

Compare closing a window when first logging in, and closing a window after 2 hours or so....

### Crash reports, logs, images, videos

There are no crashes, so, I don't need anything here.

**Comment by vaxerski** [comment]
#2758
