### ISSUE TITLE
Monitor 1 will take 10 second to load and render cursor and applications in a triple-monitor setup.

### ISSUE THREAD

**Issue by RaySlash** [hyprwm/Hyprland#3086]
### Hyprland Version

Hyprland, built from branch main at commit 4a41d013a27c9919ed41a50c43c4224d8443a415 dirty (internal: Fix XDP multi-portal issues (3077)). Tag: v0.28.0-101-g4a41d013

### Bug or Regression?

Bug

### Description

I have a triple monitor setup through DP on my archlinux setup.
```console
smj@arch $ neofetch
Arch Linux x86_64
6.4.12-arch1-1
1837 (pacman)
/usr/bin/zsh 5.9

Catppuccin-Mocha-Standard-Lavender-dark [GTK2/3]
Papirus-Dark [GTK2/3]
alacritty

MS-7C95 1.0
AMD Ryzen 5 5600 (12) @ 3.5GHz
AMD ATI Radeon RX 6650 XT / 6700S / 6800S
1753MiB / 15915MiB (11%)
31 mins
1920x1080
```
In my config I have set this for my monitors to load.
```
monitor=,highrr,auto,1
```
The output  of ``` hyprctl monitors ```
```
Monitor DP-1 (ID 0):
	1920x1080@74.986000 at 0x0
	description: Lenovo Group Limited T24v-20 V906520D (DP-1)
	make: Lenovo Group Limited
	model: T24v-20
	serial: V906520D
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 1):
	1920x1080@165.003006 at 1920x0
	description: AOC 24G2W1G3- SXIN91A010369 (DP-2)
	make: AOC
	model: 24G2W1G3-
	serial: SXIN91A010369
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 1

Monitor DP-3 (ID 2):
	1920x1080@74.986000 at 3840x0
	description: Lenovo Group Limited T24v-20 V90650ZZ (DP-3)
	make: Lenovo Group Limited
	model: T24v-20
	serial: V90650ZZ
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

```
On boot, the screen with ID 0 connected to DP-1 takes longer to show up the screen. The other screens (DP-2, DP-3) loads instantly. The wallpaper of DP-1 loads in 3-5 seconds after all other screen have loaded completely. Next to this, it takes another 5 seconds to render the cursor and applications in the workspace under DP-1. This was not happening in the Hyprland version (pacman -S hypland).
```
Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty ().
Tag: v0.28.0
```
 I am not sure why this is happening. I could pick more information if needed.

### How to reproduce

1) Install hypland-git [(AUR)](https://aur.archlinux.org/packages/hyprland-git)
2) Set the triple monitor hypland config to
```
monitor=,highrr,auto,1
```
3) Restart system (or log out and log back in / crash the hyprctl by some binding )
4) Now, the monitor 1 will take 10 second to load and render cursor and applications.

### Crash reports, logs, images, videos

Hyprland log from /tmp/hypr 
[https://raw.githubusercontent.com/RaySlash/dotfiles/main/hyprland.log](https://raw.githubusercontent.com/RaySlash/dotfiles/main/hyprland.log)

My hyprland config:
[https://github.com/RaySlash/dotfiles/blob/main/config/hypr/hyprland.conf](https://github.com/RaySlash/dotfiles/blob/main/config/hypr/hyprland.conf)

**Comment by sgse** [comment]
A user "fix" it, more on [Garuda Linux](https://forum.garudalinux.org/t/i-got-issues-on-hyprland-10-sec-blackscreen/30533/2)

Use output from hyprctl monitors
~~~
monitor=eDP-1, 2880x1800@90, 0x0, 1.5
~~~
before we use standard settings
~~~
monitor=, preferred, auto, 1.5
~~~

***
I appreciate Hyprland very much, if now flameshot would no longer adopt the scale value 1.5, it would be perfect for me. At "normal" 1920x1080 px, scale 1, everything is good.


Thanks to all who make Hyprland possible.

**Comment by vaxerski** [comment]
I will close this then
