### ISSUE TITLE
hyprland portals not working at all

### ISSUE THREAD

**Issue by betaRadiation** [hyprwm/Hyprland#3087]
### Hyprland Version

v0.25.0 (nix os)

### Bug or Regression?

Bug

### Description

When doing anything that would require a portal (clicking a link, opening something in file browser ect.) it doesn't work/open.

### How to reproduce

Do anything that would need a portal. 

When adding the `--log-session-bus` launch argument to a flatpak application it gives this error .
`C15: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B66: <- :1.7 return error org.freedesktop.DBus.Error.UnknownMethod from C15
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop`

It also doesn't work when using the `xdg-open` command

`> xdg-open "https://google.com"`
`Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop`

**Comment by vaxerski** [comment]
very old ver + hyprland doesn't implement portals. That's the job of xdg-desktop-portal
