### ISSUE TITLE
Steam internal browser has issues with flickering (damage tracking?)

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#3091]
### Hyprland Version

08310b4af9ce289180d2b3adef157642379f158e

### Bug or Regression?

Bug

### Description

Has been happening for as long as I've been using Hyprland (around december 2022 I think). It might be a problem that Steam needs to fix but I wanted to make a bug report just to be sure.

https://github.com/hyprwm/Hyprland/assets/4633209/a6fb0a0c-ff14-48de-8d58-33a02dffb8d7

Using `hyprland-nvidia-git 0.28.0.r101.g4a41d013-1` from the AUR.

### How to reproduce

1. Open Steam (Native or Runtime, doesn't matter)
2. Go to the Store page (or any page that opens the browser)
3. Flickering 

### Crash reports, logs, images, videos

Here's what I see in the hyprland logs when reproducing this: [hyprland-log.txt](https://github.com/hyprwm/Hyprland/files/12448110/hyprland-log.txt)

**Comment by vaxerski** [comment]
looks like a novideo thing?

**Comment by iggut** [comment]
same issue here, let me know if you need any info/data

**Comment by zjeffer** [comment]
> same issue here, let me know if you need any info/data

Are you using Nvidia?

**Comment by zjeffer** [comment]
Setting damage_tracking to 0 doesn't seem to make any difference, so I guess it's due to nvidia. Closing..

@tchofy Which GPU are you using?

**Comment by tchofy** [comment]
It's a GTX 1650 mobile, I've heard the flickering issues happen more often
on faster GPUs due to timing problems, can't confirm myself. I'm also using
the beta channel on steam,  with their recent new UI and all.

**Comment by zjeffer** [comment]
I'm using an RTX 3070 Mobile, with nvidia-dkms driver version 535.104.05, also using the new UI.

**Comment by tchofy** [comment]
I've managed to reproduce it after enabling ``Steam > Interface > Enable GPU accelerated rendering in web views``, I might've disabled it a while ago when I first got into the new UI and forgot about it. Just disable it and it'll stop flickering, at the cost of lower performance.

**Comment by zjeffer** [comment]
That fixes it entirely! Thanks!
