### ISSUE TITLE
 movewindow (moveto floating) fullscreen windows

### ISSUE THREAD

**Issue by kristoferus75** [hyprwm/Hyprland#3092]
### Description

Hi !

on dwm is it possible to move to floating also with fullscreen windows

on hyprland you cannot move to floating fullscreen windows -> you need first make window float or tiled

`bindm = SUPER, mouse:272, movewindow`

Is it possible to make this feature with fullscreen windows also in hyprland realizable ?

Thanks

**Comment by vaxerski** [comment]
I've allowed dragging and toggling floating status of fullscreen windows with 981386d2ae6ba8c7c5c0ebb1c9837fccfab9150c and b8f38dcbd36813772057b70b7421f52bd403fbac

> Is it possible to make this feature with fullscreen windows also in hyprland realizable ?

?

I assume the two commits above close this
