### ISSUE TITLE
Low GPU usage, Low FPS in games 

### ISSUE THREAD

**Issue by techyporcupine** [hyprwm/Hyprland#3094]
### Hyprland Version

Hyprland, built from branch  at commit 4a41d013a27c9919ed41a50c43c4224d8443a415

### Bug or Regression?

Bug

### Description

When playing different games, my dedicated GPU (Nvidia GT840M) may turbo up to its full clock speed for a couple seconds, before dropping to around the minimum clock speed (~135mhz). In both Gnome and Sway this issue is not present. Sorry if this issue has already been reported, I could not find one identical to this though.

### How to reproduce

Launch a game on dedicated GPU, observe low FPS. 

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/70345789/4a6d63ae-23fe-43d3-9782-e801f32b63d9)
Example shown: Minecraft launched via PrismLauncher, MangoHud showing clocks.

**Comment by alspinu** [comment]
What is your full spec? Did it work differently before under the same setup or hardware? Did something change since then apart from the hyprland version?

It sounds very similar to a bottle neck.

**Comment by Guanran928** [comment]
Can reproduce, issue is not present on Sway or GNOME.
OS: NixOS
GPU: nVidia GTX 1050Ti Mobile
Hyprland version: (using nix flake)
````
Hyprland, built from branch  at commit 4a41d013a27c9919ed41a50c43c4224d8443a415  ().
Tag: ?

flags: (if any)
debug
```

**Comment by Guanran928** [comment]
> Did you have to do anything special to get it to have this issue? Mine is also built using nix flakes.

No, I got this issue after updating Hyprland.

**Comment by Guanran928** [comment]
> Do you know what version the issue started at?

Not really, I was using Sway for the past few days.

**Comment by Guanran928** [comment]
> Ok, good to know it's not just me with the issue.

The nixpkgs version of Hyprland works fine for me, maybe you could try using that temporally.

**Comment by techyporcupine** [comment]
Do you think it may be worth it to roll back a couple versions and progress forward to see what version caused this issue?

**Comment by memchr** [comment]
Try [git bisect](https://git-scm.com/docs/git-bisect)

Is this specific to certain games?

**Comment by techyporcupine** [comment]
I'm not sure that I know enough to debug using that, but I can attempt it. I'll need to find a version that does not have the issue first. 
> Is this specific to certain games

As far as I know, it is not. I have only tried it in two "games". One was Minecraft as I noted above, and the other was Dolphin Emulator, both exhibited the same issue, so I assume it is not just an issue with one game.

**Comment by memchr** [comment]
> my dedicated GPU (Nvidia GT840M)

Given NVIDIA's hostility to Linux, I'd rather check if it's a driver issue first.

**Comment by techyporcupine** [comment]
It worked on Sway though, so I would be inclined to say it's not, but I'm not sure if I'm totally correct on that. And according to @Guanran928 it works with the version of Hyprland in nixpkgs.

**Comment by techyporcupine** [comment]
Just found something new that may relate to this issue. I noticed I also got poor video performance launching Minecraft using my integrated GPU, which is somewhat expected, but it was also around the 10-20ish fps mark that I saw on my dedicated GPU. I decided to look further and noticed that Minecraft said the render device was "llvmpipe", when I was expecting it to be "Mesa Intel(R) HD Graphics 5500" that is listed when Minecraft is launched in Sway. Could there be some relation between these two issues?

**Comment by GrabbenD** [comment]
This is why I stopped using NixOS a couple of months ago.
It's a reoccuring bug or more precisely a design flaw
So much for reproducible builds

**Here'a the best ~~workaround~~ fix:**
https://github.com/hyprwm/Hyprland/issues/2170#issuecomment-1528163470

**Comment by techyporcupine** [comment]
I have attempted adding `inputs.nixpkgs.follows = "nixpkgs-unstable";` already.

**Comment by techyporcupine** [comment]
Actually, if its an issue with a MESA mismatch, I have to use nixpkgs, not nixpkgs-unstable because my system is on stable.

**Comment by GrabbenD** [comment]
Yes
Anyhow, the proper fix is to update flake.lock in Hyprland repo
Pinging @fufexan

**Comment by techyporcupine** [comment]
The reason I was using the unstable repos was because `wayland-protocols` is too old for Hyprland in the stable repo.

**Comment by techyporcupine** [comment]
Is my only real solution to use NixOS Unstable?

**Comment by techyporcupine** [comment]
This issue is technically not fixed for NixOS Stable users, but a good fix for now is using NixOS Unstable (I was planning on doing so already, but this jumpstarted that) I will close this issue now.
