### ISSUE TITLE
context menu not showing up after update 

### ISSUE THREAD

**Issue by sacsbrainz** [hyprwm/Hyprland#3100]
### Hyprland Version

Hyprland, built from branch  at commit 91e28bbe9df85e2e94fbcc0137106362aea14ab5  ().

### Bug or Regression?

Bug

### Description

in my ```hypr.conf``` i have this
```
 monitor = HDMI-A-2, preferred, 0x0, 1
 monitor = eDP-1, preferred, 1920x0, 1
```
 
everything worked fine, but after the update that inlcuded the xdg stuffs by default was added
then i started obsering that all my context menu where not working when i use my laptop without the second display (the HMDI)
but when i plug in my hdmi and use 2nd display everything worked fine 

so after carefully playing around
turns out the menu actually opens but its invisible but if i click on something based on imagination it actually clicks
so i changed my ```hypr.conf``` to this

```
monitor = , preferred, auto, 1
```

and everything works fine
i will asume this is a bug

### How to reproduce

add this in your ```hypr.conf``` 
```
in my hypr.conf i have this
 monitor = HDMI-A-2, preferred, 0x0, 1
 monitor = eDP-1, preferred, 1920x0, 1
 ```

### Crash reports, logs, images, videos

https://github.com/sacsbrainz/tmp/blob/main/2023-08-28%2016-43-57.mkv

**Comment by vaxerski** [comment]
update. This has been fixed. In the case of it not being so, it's probably safe to assume it's a weird variation of #3029

**Comment by sacsbrainz** [comment]
has it been merged?
