### ISSUE TITLE
`WLR_RENDERER_ALLOW_SOFTWARE` Now Needed to Startup and Phantom Display Detected 

### ISSUE THREAD

**Issue by zmazanv** [hyprwm/Hyprland#3108]
### Hyprland Version

Hyprland, built from branch master at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d  (update v0.29.0). Tag: v0.29.0  flags: (if any)

### Bug or Regression?

Bug

### Description

The environment variable `WLR_RENDERER_ALLOW_SOFTWARE=1` needs to be set for startup with Nvidia graphics, as the latest version changes something that now necessitate this variable, where it was not necessary before (version  0.28.0-1). Hyprland is able to launch with it, whereas it immediately segfaults without it upon attempting to launch, stating that it is unable to initialize EGL. After updating to the latest version of Hyprland and setting the variable, a "phantom" display labeled as "Unknown-1" is detected. This display is not physically connected and does not appear when the environment variable is unset or when using an older version of Hyprland where the variable was not necessary.

## Unable to Start
1. Update to the latest version of Hyprland.
2. Ensure WLR_RENDERER_ALLOW_SOFTWARE is not set.
3. Start Hyprland (I start from TTY with `Hyprland`).
4. Observe immediate crash and segfault, with message mentioning inability to initialize EGL.

## Phantom Display
1. Update to the latest version of Hyprland.
2. Set the environment variable WLR_RENDERER_ALLOW_SOFTWARE to 1 in the Hyprland environment variables configuration.
3. Start Hyprland (I start from TTY with `Hyprland`).
4. Use the `hyprctl monitors` command to list connected displays.
5. Observe an additional display labeled "Unknown-1" that is not physically connected.

### Crash reports, logs, images, videos

[hyprlandCrashReport17681.txt](https://github.com/hyprwm/Hyprland/files/12471635/hyprlandCrashReport17681.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12471638/hyprland.log)

**Comment by vaxerski** [comment]
IIRC it's an issue with nvidia drivers and wlroots.
