### ISSUE TITLE
Hyprland crashes on startup with Intel G31 Graphics

### ISSUE THREAD

**Issue by lolplayer69420** [hyprwm/Hyprland#3118]
### Hyprland Version

v0.29.0-4-g28a90d60

### Bug or Regression?

Bug

### Description

I tried to install Hyprland with the `  legacyrenderer```   option, but when i try to start it up, it fails with the following 2 errors:
m_sWLRRenderer was NULL!, and wlr_gles2_renderer_create_with_drm_fd() failed!

### How to reproduce

idk, i think im the only one with this error since i wasnt able to find somebody else with the same problem on the internet

### Crash reports, logs, images, videos

Logs:
[hyprland_logs.txt](https://github.com/hyprwm/Hyprland/files/12482133/hyprland_logs.txt)
Crash Report:
[hyprlandCrashReport1570.txt](https://github.com/hyprwm/Hyprland/files/12482137/hyprlandCrashReport1570.txt)
Coredump:
[hyprland_coredump.txt](https://github.com/hyprwm/Hyprland/files/12482142/hyprland_coredump.txt)

**Comment by MightyPlaza** [comment]
looks like an old gpu
are you using Hyprland with legacy render?

**Comment by lolplayer69420** [comment]
> looks like an old gpu are you using Hyprland with legacy render?

yup, actually the second error happens with the lagacy renderer, without it only the first one happens

**Comment by MightyPlaza** [comment]
can you build before last wlroots bump?

**Comment by lolplayer69420** [comment]
an older version?

**Comment by MightyPlaza** [comment]
checkout at 116b9a80566e7956233b39697ac78c112d514c3c

**Comment by lolplayer69420** [comment]
> checkout at [116b9a8](https://github.com/hyprwm/Hyprland/commit/116b9a80566e7956233b39697ac78c112d514c3c)

i tried to compile that but it fails, it says that it cant find the file subprojects/wlroots/meson.build

**Comment by memchr** [comment]
> > checkout at [116b9a8](https://github.com/hyprwm/Hyprland/commit/116b9a80566e7956233b39697ac78c112d514c3c)
> 
> i tried to compile that but it fails, it says that it cant find the file subprojects/wlroots/meson.build

```bash

**Comment by lolplayer69420** [comment]
> can you build before last wlroots bump?

i already did it, same errors

**Comment by MightyPlaza** [comment]
`hyprctl version` ?

**Comment by lolplayer69420** [comment]
> `hyprctl version` ?

for some reason the command doesnt exist

**Comment by lolplayer69420** [comment]
> how did you install hyprland? run `sudo make clear && sudo make config && make protocols && make legacyrenderer && sudo cp ./build/Hyprland /usr/bin && sudo cp ./example/hyprland.desktop /usr/share/wayland-sessions`

i used that same command to install it

**Comment by MightyPlaza** [comment]
that doesn't seem to install it
change in the Makefile
```
diff --git a/Makefile b/Makefile
index d32c4ec1..6c265370 100644
--- a/Makefile
+++ b/Makefile
@@ -35,7 +35,7 @@ install:
        $(MAKE) fixwlr
        cd ./subprojects/wlroots && meson setup build/ --buildtype=release && ninja -C build/ && mkdir -p ${PREFIX}/lib/ && cp ./build/libwlroots.so.12032 ${PREFIX}/lib/ || echo "Could not install libwlroots to ${PREFIX}/lib/libwlroots.so.12032"
        cd subprojects/udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B./build -G Ninja && cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF` && cd ../..
-       $(MAKE) release
+       $(MAKE) legacyrender
        $(MAKE) -C hyprctl all
```
and run `sudo make clear && sudo make install`

**Comment by lolplayer69420** [comment]
> 

now the command exists but it fails due to not having any hyprland instance running

**Comment by MightyPlaza** [comment]
send the new crash report
you need Hyprland running to use hyprctl

**Comment by lolplayer69420** [comment]
There you have it
[hyprlandCrashReport32769.txt](https://github.com/hyprwm/Hyprland/files/12490103/hyprlandCrashReport32769.txt)

**Comment by MightyPlaza** [comment]
also send `lspci -vvv` (VGA section)

**Comment by lolplayer69420** [comment]
i wasnt able to run tinywl-git because it has an error on the source code and the compiler fails, i tried with bot the AUR package and the gitlab source, anyway, here is the VGA section of `  lspci -vvv`
[vga.txt](https://github.com/hyprwm/Hyprland/files/12490552/vga.txt)

**Comment by MightyPlaza** [comment]
what error did you get?
i built last commit without any issues

**Comment by lolplayer69420** [comment]
Here are the compile errors (its in spanish, sorry for that)
[tinywl_error.txt](https://github.com/hyprwm/Hyprland/files/12490623/tinywl_error.txt)
And here is the VGA section of `lspci -vvv`
[vga.txt](https://github.com/hyprwm/Hyprland/files/12490624/vga.txt)

**Comment by MightyPlaza** [comment]
works for me
```
git clone https://gitlab.freedesktop.org/wlroots/wlroots && cd wlroots/ && meson setup build/ && ninja -C build/
```
then run `./build/tinywl/tinywl`

**Comment by lolplayer69420** [comment]
> works for me
> 
> ```
> git clone https://gitlab.freedesktop.org/wlroots/wlroots && cd wlroots/ && meson setup build/ && ninja -C build/
> ```
> 
> then run `./build/tinywl/tinywl`

tinywl exits with status 1

**Comment by MightyPlaza** [comment]
strange
what about sway from arch repo?
also send `glxinfo | grep "OpenGL"` (needs to be run from inside a wm, i3, hyprland, ...)

**Comment by lolplayer69420** [comment]
> strange what about sway from arch repo? also send `glxinfo | grep "OpenGL"` (needs to be run from inside a wm, i3, hyprland, ...)

sway has the same result of tinywl, using the `--verbose`   option doesnt give more info. Here is the output from `glxinfo | grep "OpenGL"`  :
[glxinfo.txt](https://github.com/hyprwm/Hyprland/files/12491011/glxinfo.txt)

**Comment by MightyPlaza** [comment]
GLES version is enough to run Hyprland on legacy render
no idea why sway/tinywl don't work, but if anything should be a OS/packages issue
try doing a small install if you have some extra space and see if it works there

**Comment by lolplayer69420** [comment]
ill try on void linux on an unused hard disk that i have, old pc's are weird

**Comment by MightyPlaza** [comment]
hyprland isn't very easy to set up on void
use something like archinstall and you could get a system running in less than 10 mins

**Comment by lolplayer69420** [comment]
in which distros hyprland is easy to set up?, i used sway before and it suddenly stopped working on arch, i wan to try with another distro, maybe its a distro problem

**Comment by MightyPlaza** [comment]
arch is pretty much install and run, it's even in the archinstall script

**Comment by lolplayer69420** [comment]
> arch is pretty much install and run, it's even in the archinstall script

ill try a clean arch install again then, something weird about trying to run sway here is that only works when opened from inside i3 or any other X-based window manager / desktop environment

**Comment by lolplayer69420** [comment]
> GLES version is enough to run Hyprland on legacy render no idea why sway/tinywl don't work, but if anything should be a OS/packages issue try doing a small install if you have some extra space and see if it works there

sorry for the delay, i tried sway in a clean install and it failed to create a renderer with the following error: 
`EGL_EXT_image_dma_buf_import not supported`

**Comment by MightyPlaza** [comment]
if you can't launch sway/tinywl this is either a driver or wlroots issue

**Comment by lolplayer69420** [comment]
> if you can't launch sway/tinywl this is either a driver or wlroots issue

i replaced mesa-amber with mesa and loaded the i915 module, and it started up, but it doesnt load the cursor

**Comment by vaxerski** [comment]
```
env = WLR_NO_HARDWARE_CURSORS, 1
```

Anyways, this is not a hyprland issue
