### ISSUE TITLE
Bug: toggle special workspace when in fullscreen

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#312]
Good day to you!

When i've fullscreen (or maximized) window and i'm toggling special workspace :

`special` workspace appears, but all interactions appears still with fullscreen'd application, so i can't do anything with `special` workspace

thank you!

**Comment by vaxerski** [comment]
Can't seem to reproduce, although the mouse is a bit off, that is a bug. I can interact with them though.

**Comment by vaxerski** [comment]
if that was the bug, fixed in 0d54451c677498ad5c37510d02abc646ea38f8aa

**Comment by fedoranvar** [comment]
my bad , i didn't specified, that problem is with:

`fuillscreen,1` - fullscreen that keeps outer gaps
`fullscreen,0` - works fine

**Comment by fedoranvar** [comment]
it works good!

Thank you!
