### ISSUE TITLE
The window list in a group is wrong color

### ISSUE THREAD

**Issue by Fincali197** [hyprwm/Hyprland#3121]
### Hyprland Version

Hyprland, built from branch main at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (props: bump ver to 0.29.0). Tag: v0.29.0

### Bug or Regression?

Bug

### Description

When you have a window group, there is this window list at the top. It also has a yellow highlight as a subtle background. Well, the highlight color doesn't sync with the border color(and I didn't find a configuration option to change it, so guess it is a bug?).

### How to reproduce

Open a group. The window list(the bar on the top of the group) background is always yellow

### Crash reports, logs, images, videos

![new](https://github.com/hyprwm/Hyprland/assets/130681919/eef6a524-775f-4db5-a279-6eb3d44411ee)

**Comment by MightyPlaza** [comment]
known issue, restart hyprland after changing groupbar gradient colors

**Comment by Fincali197** [comment]
> known issue, restart hyprland after changing groupbar gradient colors

Thanks!
