### ISSUE TITLE
Options for group title customization

### ISSUE THREAD

**Issue by Fincali197** [hyprwm/Hyprland#3122]
### Description

Basically, an option to disable the bar on the top of a window group(or maybe just some options to customize it)

**Comment by memchr** [comment]
have you checked the [wiki](https://wiki.hyprland.org/Configuring/Variables/)


- col.group_border
- col.group_border_active
- col.group_border_locked
- col.group_border_locked_active
- group_insert_after_current
- render_titles_in_groupbar
- groupbar_titles_font_size
- groupbar_gradients

**Comment by Fincali197** [comment]
> have you checked the [wiki](https://wiki.hyprland.org/Configuring/Variables/)

damn, I would've sworn I've read through the entire wiki. Thank you though, "render_titles_in_groupbar" is the exact thing I was looking for

**Comment by MightyPlaza** [comment]
please close this issue
