### ISSUE TITLE
Occasional afterimage of an application on the previous workspace visible inside the blurred background

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [hyprwm/Hyprland#3123]
### Hyprland Version

Hyprland, built from branch main at commit 9c4f776757d673e5fb73716c874afbe20c66f045 dirty (keybinds: fixup release conditions). Tag: v0.29.0-8-g9c4f7767  flags: (if any)

### Bug or Regression?

Bug

### Description

Basically, the title.

Sometimes (1-2 times a day) a blurred background of my terminal (foot) will display some part of the previous window.

I've only noticed this with firefox so far, and since I have `no_gaps_when_only = yes` set and most of the time run a single application per workspace (expect terminals) it is hard to tell whether it captures just an application or all of the workspace.

__This patch from here https://github.com/hyprwm/Hyprland/issues/2941#issuecomment-1675153387 fixes the issue.__

I've mentioned it in https://github.com/hyprwm/Hyprland/issues/2941, but since you didn't respond / merged it, I thought that it was already fixed in some other way.

But then I tried to build hyprland without manually applying this patch and could see the same issue the next day.

### How to reproduce

Sadly, I don't have a definitive way to reliably reproduce it.

Having more workspaces with windows open on them increases the chance to observe it.

Changing the window from tiled to floating or opening a new layer (e.g. tofi) resets the background to normal.

### Crash reports, logs, images, videos

System: 
* Arch linux, linux-zen 6.4.12, nvidia-dkms 535.104.05

Demo:

https://github.com/hyprwm/Hyprland/assets/14999778/679b4964-403c-431e-8a07-3ce0082fa638

**Comment by vaxerski** [comment]
I just want to mention I hate all of you why the fuck did the guy close it before I merged the patch that made me forget

**Comment by MahouShoujoMivutilde** [comment]
Yeah, that was weird.

Thanks!
