### ISSUE TITLE
Mod key not working

### ISSUE THREAD

**Issue by xoores** [hyprwm/Hyprland#3125]
### Hyprland Version

0.28.0

### Bug or Regression?

Bug

### Description

I've run into similar issue as #1762: I configured Hyprland with CZ keyboard layout and after few minutes Hyprland starts ignoring all my shortcuts that have `Super` in them... In terminal I can see something like `^[[100;9m` when pressing my shortcuts. It will work for a few moments though (which is kind of strange) - I can generally open few terminal windows.

It seems like there is some kind of a bug in a way Hyprland handles keystrokes - everything works OK in Xorg and in Sway. Also it seems that it is only `Super` key that will behave in this way as `Alt`+`F2` (for example) keeps working.

Snippet of my config:
```
input {
    kb_layout = cz
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    numlock_by_default = yes

    touchpad {
        natural_scroll = yes
        tap-and-drag = yes
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

$mainMod = SUPER
bind = $mainMod, D, exec, kitty
bind = ALT, F4, killactive, 
bind = $mainMod, M, exit, 
```

### How to reproduce

Configure Hyprland with CZ locale.

**Comment by alaricljs** [comment]
I have a custom kb_layout that I use and have the same result.  SUPER does not work, Mod3 does  (same key).

**Comment by vaxerski** [comment]
what does `wev` print if you press super?

**Comment by alaricljs** [comment]
This is Super w/ my keymap:
```
[14:     wl_keyboard] key: serial: 649; time: 234706; key: 133; state: 1 (pressed)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000020: Mod3 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 651; time: 234811; key: 133; state: 0 (released)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

This is Super w/ the us keymap:
```
[14:     wl_keyboard] key: serial: 846; time: 285161; key: 133; state: 1 (pressed)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000040: Mod4 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 848; time: 285271; key: 133; state: 0 (released)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

xmodmap for mine:
```
xmodmap:  up to 2 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c)
mod2      
mod3        Super_L (0x85),  Super_R (0x86)
mod4        Meta_L (0x42)
mod5     
```

xmodmap for us:
```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Alt_L (0xcc),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        ISO_Level5_Shift (0xcb)
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c)
```

**Comment by vaxerski** [comment]
well then it seems that the `cz` layout changes your super key into Mod3. That's what you will have to use.

**Comment by alaricljs** [comment]
I'm not using the `cz` layout, I was just providing another data point in case it might help point to the issue.  The `cz` layout does not impact the assignment of Super/Mod4, perhaps @xoores can verify his modmap is default?

**Comment by xoores** [comment]
@vaxerski: No, `Mod3` does _**not work**_ for me. Why would you close this issue befor I even had a chance to write anything? 😳 For me the issue is definitely not resolved, the problem unfortunately persists.


@alaricljs: xmodmap under Wayland/Hyperland only says something like `Unable to open display`. Under X it says:
```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_L (0xcc),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        ISO_Level5_Shift (0xcb)
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c)
```

Also `wev` says:
```
[14:     wl_keyboard] key: serial: 791; time: 650795; key: 36; state: 0 (released)
                      sym: Return       (65293), utf8: ''
[14:     wl_keyboard] key: serial: 792; time: 652343; key: 133; state: 1 (pressed)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 16
                      depressed: 00000040: Mod4 
                      latched: 00000000
                      locked: 00000010: Mod2 
[14:     wl_keyboard] key: serial: 794; time: 652595; key: 40; state: 1 (pressed)
                      sym: d            (100), utf8: 'd'
[14:     wl_keyboard] key: serial: 795; time: 652713; key: 40; state: 0 (released)
                      sym: d            (100), utf8: ''
[14:     wl_keyboard] key: serial: 796; time: 652855; key: 133; state: 0 (released)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 16
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000010: Mod2                    
```

I tried Mod3 and also Mod4 (since it is the one reported as depressed by wev) but to no avail - it is ignored by Hyprland.

**Comment by vaxerski** [comment]
you have a locked Mod2.

**Comment by alaricljs** [comment]
Mod2 should be Num_Lock, so shouldn't be a big deal... until it is.

**Comment by xoores** [comment]
Yup, I see it. I thought it was either Capslock or Numlock... Or FNlock (I'm on laptop).

I will try in a few minutes to switch back to Hyprland & check again 🙂

**Comment by vaxerski** [comment]
it still counts to the modifier mask

**Comment by alaricljs** [comment]
It probably is the Num_Lock thing, tho I can't prove it because I don't have one.   On the other hand the `cz` layout works just fine w/ Super for me.

**Comment by xoores** [comment]
That means I would have to have SUPERNUM in the config? :flushed: I honestly did not see that coming, so sorry if I'm bit confused. Numlock is generaly ignored in configs like that (Sway and i3 don't have any problem with numlock)

I will try in a few minutes - I have a laptop w/ numpad so this *might* be the problem.

**Comment by xoores** [comment]
I've tried and the Numlock unfortunately is not the problem - I turned NumLock off and the keybinding still did not work (tried multiple times with `SUPER`, `Mod3` and `Mod4`).

relevant part of config:
```
$mainMod = Mod4    <----- this was SUPER, Mod3 and Mod4
bind = $mainMod, d, exec, kitty
```

wev:
```
[14:     wl_keyboard] key: serial: 628; time: 2784031; key: 133; state: 1 (pressed)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000040: Mod4 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 630; time: 2784135; key: 40; state: 1 (pressed)
                      sym: d            (100), utf8: 'd'
[14:     wl_keyboard] key: serial: 631; time: 2784302; key: 40; state: 0 (released)
                      sym: d            (100), utf8: ''
[14:     wl_keyboard] key: serial: 632; time: 2784449; key: 133; state: 0 (released)
                      sym: Super_L      (65515), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

**Comment by vaxerski** [comment]
odd. No submaps or anything?

**Comment by xoores** [comment]
Two submaps - resize & "exit" one. That one allows me to exit Hyprland (and the problem was present even before I created it so I'd guess that it should not be a problem :shrug:)

Full config without comments - it is mostly just the default one with few changes :slightly_smiling_face: 
```
monitor=,preferred,auto,auto
exec-once = /home/xoores/.condig/hypr/_startup.sh once
env = XCURSOR_SIZE,24

input {
    kb_layout = cz
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    numlock_by_default = yes

    touchpad {
        natural_scroll = yes
        tap-and-drag = yes
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
    workspace_swipe_fingers = 4
    workspace_swipe_forever = yes
}

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 1
    }
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = on
}

device:epic-mouse-v1 {
    sensitivity = -0.5
}

misc {
    mouse_move_enables_dpms = yes
    key_press_enables_dpms = yes
}
$mainMod = Mod4
$mainModShift = SUPERSHIFT

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, plus, workspace, 1
bind = $mainMod, ecaron, workspace, 2
bind = $mainMod, scaron, workspace, 3
bind = $mainMod, ccaron, workspace, 4
bind = $mainMod, rcaron, workspace, 5
bind = $mainMod, zcaron, workspace, 6
bind = $mainMod, yacute, workspace, 7
bind = $mainMod, aacute, workspace, 8
bind = $mainMod, iacute, workspace, 9
bind = $mainMod, eacute, workspace, 10

bind = $mainMod SHIFT, plus, movetoworkspace, 1
bind = $mainMod SHIFT, ecaron, movetoworkspace, 2
bind = $mainMod SHIFT, scaron, movetoworkspace, 3
bind = $mainMod SHIFT, ccaron, movetoworkspace, 4
bind = $mainMod SHIFT, rcaron, movetoworkspace, 5
bind = $mainMod SHIFT, zcaron, movetoworkspace, 6
bind = $mainMod SHIFT, yacute, movetoworkspace, 7
bind = $mainMod SHIFT, aacute, movetoworkspace, 8
bind = $mainMod SHIFT, iacute, movetoworkspace, 9
bind = $mainMod SHIFT, eacute, movetoworkspace, 10

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod, d, exec, kitty
bind = ALT, F4, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, Return, exec, pcmanfm-qt 
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = ALT, F2, exec, rofi -show run -color-enabled -scroll-method 1, # dwindle
bind = $mainMod, escape, exec, swaylock

bind = $mainMod, R, submap, resize
submap=resize
    binde=,right,resizeactive,10 0
    binde=,left,resizeactive,-10 0
    binde=,up,resizeactive,0 -10
    binde=,down,resizeactive,0 10
    bind=,escape,submap,reset 
submap=reset

bind = ,XF86PowerOff, submap, exit
submap=exit
    bind=,E,exit
    bind=,XF86PowerOff,exec,/scripts/sleep.sh
    bind=,escape,submap,reset
    bind=,Return,submap,reset
    bind=,D,exec,kitty
submap=exit

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

windowrule = center,pavucontrol
windowrule = float,pavucontrol
```

**Comment by vaxerski** [comment]
exit submap is not finished properly (no submap=reset) jsyk

this is definitely odd.

**Comment by xoores** [comment]
Funny thing is that I fixed that exit submap and the problem did not manifest so far (writing this from Hyprland) :flushed:  However I jumped from X to Hyprland several times and it might be possible that something somewhere got stuck...

Tomorrow I will try to reboot to wipe the slate clean and then I will report back. Thanks for your help @vaxerski, hopefully this was it!

**Comment by xoores** [comment]
Sorry for the delay - had to switch back to X for some time as I had to do some work & I had some problems with Hyprland and multi-monitor setup (the worst one was that it randomly froze my whole computer :sweat_smile:)

I did some tests and finally figured out how to trigger this behavior. Definitely the exist submap was the culprit (I'm an idiot and overlooked the simplest thing - thanks @vaxerski a lot for your help :slightly_smiling_face:), however in order to actually *trigger* this behaviour, it needs to reload *twice* (don't ask me why). So if I have `submap=exit` and I save the config, everything works. I have to save it once more and now it is triggered.

Funny thing is that to fix this, I need to properly finish the submap (`submap=reset`) and also save it *twice*, otherwise it will still be broken.

I have a few more questions about Hypr and multimonitor setup - I will try & search for IRC or open a discussion so you can close this issue :slightly_smiling_face: 

Thanks again!

**Comment by swimmingchar** [comment]
I have encountered a similar problem recently. The default mainMod binding key will be pressed on the second and later desktops. I have restored the configuration file many times. In addition, I can't capture it using wev, because after the problem occurs, as long as a terminal appears, it can be restored. Other things such as file managers don't work.
This is my xmodmap:
First is normal, Second is have a problem,

![Image](https://github.com/user-attachments/assets/e0638799-a805-44db-aa93-2df8fc00bbcf)

This is my conf:
`monitor=,preferred,auto,auto

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$wg = rofi -modi WireGuard:~/.config/waybar/wireguard-rofi-waybar/wireguard-rofi.sh -show WireGuard
$nutstore = /usr/bin/python3 /home/meet/.nutstore/dist/bin/nutstore-pydaemon.py
$brower = firefox

exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = waybar & hyprpaper & swaync & swayidle & fcitx5 -d
exec-once = nm-applet & mako & udiskie
exec-once = /home/meet/.config/hypr/wallpaper.sh &
exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 28
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/lib/hyprpolkitagent
exec-once = $nutstore &  remmina -i
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

general {
    gaps_in = 3
    gaps_out = 7
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
    }

    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

animations {
    enabled = yes, please :)

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    #animation = workspacesIn, 1, 1.21, almostLinear, fade
    #animation = workspacesOut, 1, 1.94, almostLinear, fade
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = false
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

$mainMod = Mod4 # Sets "Windows" key as main modifier
bind = $mainMod, T, exec, $terminal
bind = $mainMod, D, exec, $menu
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, F, togglefloating,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, B, exec, $brower
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod SHIFT, W, exec, $wg

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0`
