### ISSUE TITLE
TTY comand Hyprland dont work

### ISSUE THREAD

**Issue by elvenaz0** [hyprwm/Hyprland#3127]
### Hyprland Version

v0.25.0

### Bug or Regression?

Bug

### Description

hi, 

I am trying to start hyprland from a new installation of nixos without graphical environment or desktop environment in a virtual machine on vmware workstation pro, I am starting with nixos if anyone has information is appreciated.

attached photos of the bug report

### How to reproduce

i dont now

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/143763280/089c1a04-d5b4-4a18-9326-072144d5fe13)
![image](https://github.com/hyprwm/Hyprland/assets/143763280/df09ee37-12ad-42e6-8da5-9c40dd385b7d)
![image](https://github.com/hyprwm/Hyprland/assets/143763280/2ca220e4-7563-4d0c-891a-a6f15dd892be)

**Comment by MightyPlaza** [comment]
1 - very old version
2 - from the tty screenshot I'm gonna guess you're on a VM, and I'm gonna also guess hardware acceleration isn't enabled

**Comment by elvenaz0** [comment]
> 1 - very old version 2 - from the tty screenshot I'm gonna guess you're on a VM, and I'm gonna also guess hardware acceleration isn't enabled

guessed correctly

**Comment by MightyPlaza** [comment]
I don't use nix but you need to use unstable
but just enabling 3d acceleration should fix the issue

**Comment by vaxerski** [comment]
invalid, didnt read the wiki, not a hyprland issue, blah blah

**Comment by elvenaz0** [comment]
> invalid, didnt read the wiki, not a hyprland issue, blah blah

okey..., i gess...
