### ISSUE TITLE
Passed Binds Sometimes Act As Non-Consuming Binds

### ISSUE THREAD

**Issue by KineticAeon** [hyprwm/Hyprland#3129]
### Hyprland Version

Hyprland, built from branch main at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (props: bump ver to 0.29.0). Tag: v0.29.0

### Bug or Regression?

Bug

### Description

When passing a bind to an application (in my case = `bind=,KP_Prior,pass,^(discord)$`), the bind acts as a non-consuming bind and will be sent to the currently application. This causes me to either scroll up or type 9 when using this bind, which seems to be unintended behaviour.

This behaviour seems to differ between applications. I have observed the following with these binds:
`bind=,h,pass,^(discord)$`: 
- Discord does not accept the passed bind unless it is focused.
- Firefox does not type `h` on press, but the current text field is highlighted.
- VSCode will type `h` on press.
- Kitty will not type `h` on press.

`bind=,h,pass,^(firefox)$`:
- Firefox types `h` when passed from an outside program.
- Kitty, Discord, and VSCode will not type `h`.

`bind=,KP_Prior,pass,^(discord)$`
- Kitty and Firefox intercept the bind and Discord does not receive it.
- The bind is correctly passed to Discord in VSCode.

### How to reproduce

1. Add a passed keybind with no preceding modifier key.
2. Attempt to use this bind in various apps.

**Comment by imxyy1soope1** [comment]
dup with #3000
