### ISSUE TITLE
Bug: `dwindle`'s `togglegroup` focus

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#313]
Good day to you!>

when i'm toggling `dwindle` group i'm loosing focus on window (so i can't interact with appeared window)
but if i `toggle` off and on again , then focus sustain

Thank you!

**Comment by vaxerski** [comment]
please explain this better or provide a video, I can't seem to reproduce. I am toggling a group on and I have focus on the visible window.

**Comment by fedoranvar** [comment]
description:

i'm openning two terminals, after toggling group , cursor is empty box - no focus.
i'm moving mouse and focus appears
i'm entering text
toggling off and on group
and cursor appears as pipe  - focus on

https://user-images.githubusercontent.com/52028706/177556209-3d272338-d486-4691-b820-2b546b8ac17f.mp4

**Comment by vaxerski** [comment]
fixed in 5a22335b8d0d69cabf7038c4d6409d3905762479

**Comment by fedoranvar** [comment]
it works good!

Thank you!
