### ISSUE TITLE
Freezing applications: Lost connection/Broken Pipe

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#3133]
### Hyprland Version

v0.29.0-1-gc5084f36

### Bug or Regression?

Bug

### Description

I have noticed, that quite a few applications that freeze from time to time crash when they do so.
For example:
- Zrythm using `GDK_BACKEND=wayland /path/to/zrythm` whenever it autosaves
- Cambalache when inserting anything into the editor

It works in xwayland (it just freezes, without crashing), but some applications, like Zrythm, have a really hard time working properly there. I need them to run natively via wayland.

Can you fix that?

### How to reproduce

Open Zrythm, Save, or create a folder track.

Open Camabalache and to pretty much anything inside the editor

### Crash reports, logs, images, videos

Sometimes "Lost connection to wayland compositor", sometimes "Broken Pipe"

**Comment by MightyPlaza** [comment]
works on other compositors?

**Comment by UltraBlackLinux** [comment]
I haven't tried any other compositors. I only use hyprland and I don't have any configs for other compositors set up.

I was told that it must be the hyprland's fault.

**Comment by vaxerski** [comment]
"I was told" by whom? developers of the game? random idiots on the internet? barack obama?

**Comment by UltraBlackLinux** [comment]
Sway users. I cannot confirm that because I don't have a config

**Comment by vaxerski** [comment]
sway has a default config no?

**Comment by UltraBlackLinux** [comment]
apparently your question was justified because what I was told was wrong. Also broken pipe on sway, also lost connection to wayland compositor. I'll check back with the devs

**Comment by vaxerski** [comment]
see the first mistake you made was thinking that I might be wrong
