### ISSUE TITLE
hyprctl won't run inside tmux session

### ISSUE THREAD

**Issue by unifreak** [hyprwm/Hyprland#3134]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Regression

### Description

I'm on  Arch linux, version is:

    Linux me 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux

I replaced kitty with alacritty. when inside alacritty, I can run `hyprctl` command fine. But if started a `tmux` session inside alacritty, then running `hyprctl <anysubcommand>`, it will error out like this:

    Couldn't connect to /tmp/hypr/9654749244117f7f150c6f2a2ce4dede6e8cbb25_1693567633/.socket.sock. (3)

I checked my `/tmp/` dir, and made sure all user have read/execute permission along the path, but the error still happens.

### How to reproduce

just to inside a tmux session, then run `hyprctl` with any subcommands.

**Comment by memchr** [comment]
This is **not** a hyprland/hyprctl bug, rather you need to update the value of the **HYPRLAND_INSTANCE_SIGNATURE** environment variable in tmux, as tmux may use the older value of this variable, since it uses the first instance started as a server for other instances.

**Comment by memchr** [comment]
You can import variables into tmux automatically when hyprland is started by running a script, for example, 

create a script as [~/.local/lib/import_env](https://gist.github.com/memchr/a40f9fdb95f9e263fc7a3f6a784b3feb)

Then use exec-once to execute the script when hyprland starts.

```
exec-once = $HOME/.local/lib/import_env tmux
```

**Comment by jbeich** [comment]
Another option is to let tmux auto-update those e.g.,
```sh
$ tmux set -ag update-environment " HYPRLAND_INSTANCE_SIGNATURE HYPRLAND_CMD"
```
or (more complete)
```sh
$ cat ~/.tmux.conf
# non-systemd
set -ag update-environment " DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR"
# wlroots, QtGui; rarely used outside of DEs
set -ag update-environment " XDG_SESSION_TYPE"
# Cursors (see also gsettings for Gtk, xrdb for X11)
set -ag update-environment " XCURSOR_SIZE XCURSOR_THEME"
# Generic Wayland
set -ag update-environment " WAYLAND_DISPLAY"
# Arcan
set -ag update-environment " ARCAN_CONNPATH"
# Xorg or Xwayland
set -ag update-environment " DISPLAY XAUTHORITY"
# Hyprland + defaults in main.cpp
set -ag update-environment " HYPRLAND_INSTANCE_SIGNATURE HYPRLAND_CMD _JAVA_AWT_WM_NONREPARENTING MOZ_ENABLE_WAYLAND XDG_CURRENT_DESKTOP"
# Sway or i3
set -ag update-environment " SWAYSOCK I3SOCK"
# Wayfire IPC plugin
set -ag update-environment " WAYFIRE_SOCKET"
# labwc --exit/--reconfigure
set -ag update-environment " LABWC_PID"
# etc
```

**Comment by vaxerski** [comment]
`hyprctl --instance 0 clients`

or the above

**Comment by unifreak** [comment]
Both of these two works, thanks!

**Comment by danielkrajnik** [comment]
Thank you for explaining solution, but could you please also explain what causes tmux to fail to pick up this environment variable? Even a brief explanation would be useful.

I'm concerned that there may be other things missing when starting Hyprland that will lead to silent errors later down the line like [this one](https://github.com/altdesktop/playerctl/issues/323).

I'm happy to read through the source code, but any hint as to where to start reading would be really appreciated.

**Comment by danielkrajnik** [comment]
Is this problem specific to any Wayland compositor or only Hyprland? I spent hours trying to understand why [playerctl](https://github.com/altdesktop/playerctl/issues/323) and [hyprctl](https://www.reddit.com/r/zsh/comments/14tlcnt/comment/k6yev1e/?utm_source=share&utm_medium=web2x&context=3) don't work.

Could this please be added to FAQ or README?

**Comment by yalikebaz** [comment]
Hi I know this is an old issue however I was able to fix this another way (which I might argue is better) and wanted to comment in case anyone comes across this in the future.

Just detach from your tmux session, and kill the server with `tmux kill-server`. Then when you create a new server things should work correctly.
