### ISSUE TITLE
blurry client in some cases

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#3138]
### Hyprland Version

Hyprland, built from branch main at commit f242f9447b02e304e214ef36443bd795719c3330 dirty (keybinds: suppress up event if down was consumed). Tag: v0.29.0-17-gf242f944

### Bug or Regression?

Regression

### Description

in master layout, when I have 4 client (not <4 or >4) the font looks blurry. Happens on all the terminals I tried (foot, alacritty)
![screenshot-2023-09-01-14:47:54](https://github.com/hyprwm/Hyprland/assets/208711/ec716f2f-33a2-4a5f-bc5b-d81d842cf25e)

You can see here that the master term is fine, while the 3 other are blurry

### How to reproduce

Open 4 terms

**Comment by primalmotion** [comment]
it actually happens for any app 

![screenshot-2023-09-01-14:50:29](https://github.com/hyprwm/Hyprland/assets/208711/5360245a-9e75-4b61-a0df-efe17085482f)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12501672/patch.txt)
try

**Comment by primalmotion** [comment]
yep that fixes it
