### ISSUE TITLE
Autodetection of monitor resolution/scaling doesn't work properly in ver. 0.29

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/Hyprland#3140]
### Hyprland Version

Hyprland, built from branch  at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (). Tag: v0.29.0  flags: (if any)

### Bug or Regression?

Regression

### Description

Autodetection of monitor resolution/scaling doesn't work properly in ver. 0.29. Ver. 0.28 works fine.
Seems to be related to  #3103.

### How to reproduce

1. Default autogenerated config, run Hyprland from tty (seatd is used).
2. The mouse is not responsive.
3. Press `Super+Q` (run kitty). No effect.
4. Press `Super+2` and then `Super+1`. It seems that the resolution is being fixed and kitty is displayed.

Specifying a resolution and scale in config file explicitly fixes the issue:
```
monitor = , 1920x1080, auto, 1
```

**Comment by romanstingler** [comment]
what happens if you use 
`monitor = , preferred, auto, auto`

**Comment by akdevservices** [comment]
> what happens if you use
> `monitor = , preferred, auto, auto`

The same as described in _How to reproduce_. I see an empty screen with a default wallpaper in wrong resolution (lower than my standard 1920x1080). Running kitty (`SUPER+Q`) has no visual effect. After pressing `SUPER+2` and `SUPER+1` (switching to workspace `2` and then back to `1`) everything gets back to normal and I see the kitty window in the expected resolution (1920x1080).

**Comment by vaxerski** [comment]
dupe

**Comment by Ordoviz** [comment]
@vaxerski Please mention this bug in the [release notes](https://github.com/hyprwm/Hyprland/releases/tag/v0.29.0) and make a Discord announcement about it. This would have saved me an hour of time.

**Comment by vaxerski** [comment]
it's being worked on, and doesn't affect everyone, just a handful of people.
