### ISSUE TITLE
Add custom resolution support through modeline

### ISSUE THREAD

**Issue by cjuniorfox** [hyprwm/Hyprland#3143]
### Description

Sometimes, setting up a custom resolution not natively supported for your monitor is desirable. Example: when you're using adapters for connecting CRT monitors or projectors using an HDMI-to-VGA or HDMI-to-YPbPr adapters. In other cases it's when you're mirroring the screen using a GPU-hardware-accelerated feature does in Sunshine, setting up a custom resolution is needed.
I want to ask for supporting "modeline" settings, like the existing ones in Sway and X11.
Use case example. Let's suppose that I want to enable the resolution 2560x1080 on a monitor that the connected display does not natively support or not informing at the "edid" the intended resolution.

1. Using the cvt command line utility, for obtaining the intended modeline.
```
$ cvt 2560 1080 60
# 2560x1080 59.98 Hz (CVT) hsync: 67.17 kHz; pclk: 230.00 MHz
Modeline "2560x1080_60.00"  230.00  2560 2720 2992 3424  1080 1083 1093 1120 -hsync +vsync
```
2. Setting up Hyprland settings file to setup and use the intended modeling:

hyprland.conf
```
modeline=HDMI-A-1,2560x1080_60.00, 230.00,  2560, 2720, 2992, 3424,  1080, 1083, 1093, 1120, -hsync, +vsync
monitor=HDMI-A-1,2560x1080@60,0x0,1
```
being the "modeline" options as described:
```
modeline=<output>,<name>,<clock>, <hdisplay>, <hsync_start>, <hsync_end>, <htotal>, <vdisplay>, <vsync_start>, <vsync_end>, <vtotal>, <hsync>, <vsync>
```

**Comment by vaxerski** [comment]
it's supported, but we forgot to document it.

https://github.com/hyprwm/Hyprland/pull/2254

**Comment by AndrewGraber** [comment]
For future readers, this has been documented: https://wiki.hypr.land/Configuring/Monitors/#custom-modelines
