### ISSUE TITLE
Package hyprland-headers

### ISSUE THREAD

**Issue by xdavidel** [hyprwm/Hyprland#3148]
### Description

The plugin system is very cleaver and OP.

The only "drawback" is from what I can tell - you'll have to pin your plugins to
a specific version of Hyprland - hence the idea of maybe distribute the corresponding 
header files of each packaged version of Hyprland in the same manner?

Basically, it will be like the Linux kernel and it's linux-headers package.

I don't know I that is too much of a hassle and not really worth it...

**Comment by memchr** [comment]
Isn't this more of a distribution packaging issue than Hyprland itself?

The downstream packaging is not controlled by this repo.

**Comment by vaxerski** [comment]
we don't package shit
