### ISSUE TITLE
segfault on startup

### ISSUE THREAD

**Issue by dalton-elmo** [hyprwm/Hyprland#3151]
### Hyprland Version

v0.29.0

### Bug or Regression?

Regression

### Description

After upgrading Hyprland from `v0.28.0` to `v0.29.0` on Arch, a segfault occurred on startup.

I tried the default config on different versions (`hyprland`, `hyprland-git`, `hyprland-nvidia`, `hyprland-nvidia-git`),
but segfault still occurs (note: I am using `nvidia-dkms`).

For now I downgraded it to `hyprland v0.28.0`.

### How to reproduce

Use nvidia card, I guess.

### Crash reports, logs, images, videos

[hyprlandCrashReport678.txt](https://github.com/hyprwm/Hyprland/files/12504803/hyprlandCrashReport678.txt)

**Comment by vaxerski** [comment]
iirc nvidia funk

**Comment by dalton-elmo** [comment]
Fixed by adding:
```
env = WLR_RENDERER_ALLOW_SOFTWARE, 1
```
Sorry to bother you.
