### ISSUE TITLE
Scratchpad blur when nothing is in scratchpad

### ISSUE THREAD

**Issue by tvlpirb** [hyprwm/Hyprland#3154]
### Hyprland Version

Hyprland, built from branch  at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (). Tag: v0.29.0

### Bug or Regression?

Bug

### Description

When bringing up the scratchpad/specialworkspace even though it is empty the background still gets blurred out.

Expected behaviour:
Nothing should happen if the scratchpad is empty

### How to reproduce

Toggle specialworkspace when it is empty

**Comment by vaxerski** [comment]
it's on purpose like that, so you see it's open.
