### ISSUE TITLE
Make the xray option available for non-blurred windows

### ISSUE THREAD

**Issue by Runeword** [hyprwm/Hyprland#3155]
### Description

Make the xray option available for non-blurred windows.
Related to https://github.com/hyprwm/Hyprland/discussions/3034

**Comment by MightyPlaza** [comment]
can't you do that with passes=0 or disabling blur?

**Comment by Runeword** [comment]
passes=0 does not remove blur entirely, and disabling blur disable xray at the same time.

**Comment by MightyPlaza** [comment]
are you sure?
even after https://github.com/hyprwm/Hyprland/pull/3181?

**Comment by Runeword** [comment]
Sorry for the confusion, I had pass=1 to avoid the problem encountered in #3181.
Last commit and pass=0 fix it !
Thanks for your help!
