### ISSUE TITLE
Hyprland plays workspace switch animation for multiple monitors even if they're already open

### ISSUE THREAD

**Issue by RoootTheFox** [hyprwm/Hyprland#3159]
### Hyprland Version

Hyprland, built from branch makepkg at commit bb0933437f4602080a66cc877fee36dce8dcb3ff dirty (wlr-ext-workspace: remove protocol impl).

### Bug or Regression?

Regression

### Description

Before commit bb0933437f4602080a66cc877fee36dce8dcb3ff Hyprland didn't play the workspace animation when switching between workspaces on different monitors (that were already open!) when using the `workspace` keybind.
Starting from this commit, it always plays the workspace animation regardless.

(I should also mention that this ALSO happens on the latest commit as of writing this, 96d555e8e794627bfc561e294e148ab8a9961fcc)

### How to reproduce

- update hyprland to or past commit bb0933437f4602080a66cc877fee36dce8dcb3ff
- open 2 workspaces on 2 different monitors (with windows on them)
- switch between them using keybinds
- observe the animation
- downgrade hyprland to a version prior to this commit
- observe no animation

### Crash reports, logs, images, videos

[video](https://foxgirl.wtf/b7cecad169df4abcba8e2c9caee19b2b)
Hyprland was supposed to play zero workspace animations in this video.

**Comment by vaxerski** [comment]
fixed in 5126bfab72ff0cf74ebd4c6346e19ac52ea7b00b
