### ISSUE TITLE
How do i actually switch keyboard layouts?

### ISSUE THREAD

**Issue by YamatoHD** [hyprwm/Hyprland#316]
I love this WM probably the most of all and would love to actually use it, so far only two issues are actually problematic: right click tray menus in waybar are all over the place and behind the bar and i did not find a way to do this in config and fcitx5, which i used in Sway, does not work at all, even IN the app testing line

Is there a way to switch any other way?

**Comment by vaxerski** [comment]
both problems are documented in the wiki.

ibus: https://github.com/hyprwm/Hyprland/wiki/Uncommon-tips-&-tricks

waybar: https://github.com/hyprwm/Hyprland/wiki/FAQ
