### ISSUE TITLE
[Question] How to recover previous layout on closing master

### ISSUE THREAD

**Issue by kflak** [hyprwm/Hyprland#3160]
Hi,

I am wondering if it's possible to achieve the following when using master layout:

1. Open window A
2. Open window B
3. Open window C (now master)
4. Close window C (A is now master)

I would like in step 4 that B becomes master instead of A, basically unwinding the stack instead of cycling forward in it. Is this possible to accomplish?

**Comment by shadowmax31** [comment]
Pretty sure `new_on_top` does what you want

https://wiki.hyprland.org/Configuring/Master-Layout/

**Comment by kflak** [comment]
Perfect, just what I was looking for! Thanks :-)
