### ISSUE TITLE
Master layout don't put first application as fullscreen

### ISSUE THREAD

**Issue by Anakael** [hyprwm/Hyprland#3161]
### Hyprland Version

0.29.0

### Bug or Regression?

Bug

### Description

Before update first application in master layout was put as fullscreen (just as on a gif here: https://wiki.hyprland.org/Configuring/Master-Layout/)
Now first application take only `mfact` (like there is another application on window, but it's not).

### How to reproduce

```
layout = master

master {
    new_is_master = true
    orientation = center
    always_center_master = true
}
```

### Crash reports, logs, images, videos

New first application on window:
![image](https://github.com/hyprwm/Hyprland/assets/17771546/03ab3ff1-92f0-4682-980c-d90a320f6736)

**Comment by shadowmax31** [comment]
From docs:
always_center_master | when using orientation=center, keep the master window centered, even when it is the only window in the workspace.
-- | --

**Comment by Anakael** [comment]
Yes, without that options it works as expected.
Was the behavior of this option changed?

**Comment by shadowmax31** [comment]
I think it was fixed in one of the latest releases, but I might be wrong about that
