### ISSUE TITLE
No workspace waybar

### ISSUE THREAD

**Issue by cristiangrossano** [hyprwm/Hyprland#3173]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

No workspace shown on latest update of hyprland. Before on latest git version, now also on latest stable update in the official repos.

OS: Arch Linux 6.4.12-arch1-1

### How to reproduce

Just start both.

**Comment by MightyPlaza** [comment]
... https://github.com/hyprwm/Hyprland/issues/3171

**Comment by cristiangrossano** [comment]
perfect.
