### ISSUE TITLE
Enabling laptop monitor leads to crash.

### ISSUE THREAD

**Issue by rszyma** [hyprwm/Hyprland#3175]
### Hyprland Version

Hyprland, built from branch main at commit 4eecb8bffc829ab2222b4acea1942ef8ee7b8904 dirty (config: don't enable vrr 2 for maximized workspaces). Tag: v0.29.1-11-g4eecb8bf  flags: (if any)

### Bug or Regression?

Bug

### Description

I have an external hdmi monitor. Enabling laptop monitor while the hdmi one is plugged with the config below leads to crash. It only happens when live reloading. When running Hyprland fresh from terminal it works normally.

### How to reproduce

1. Use this config for monitors:
```
monitor=eDP-1,disable
monitor=HDMI-A-1,1920x1080@180,0x0,1
```
2. Change the monitors config to this:
```
monitor=HDMI-A-1,1920x1080@180,0x0,1
```
3. Hyprland crashes

### Crash reports, logs, images, videos

[hyprlandCrashReport15979.txt](https://github.com/hyprwm/Hyprland/files/12517762/hyprlandCrashReport15979.txt)

**Comment by jakubreron** [comment]
Looks like your issue is similar to this one: https://github.com/hyprwm/Hyprland/issues/2770

**Comment by rszyma** [comment]
It's a different issue. I've tried today's patches and the crash is still reproductible.

I haven't looked at the code (and neither I will, because is my eyes start to bleed when I see c++), but just from the last log messages in crash log, I can tell that the laptop monitor is being initialized with wrong position (2147483647,-2147483647) and size (0x0).

**Comment by vaxerski** [comment]
somehow that rule doesn't get picked up. Wuuttt

**Comment by rszyma** [comment]
Trying again in fa3de9b70e95ea8f0ebac16ae02f8f0eba0d5b92 (v0.29.1-17-gfa3de9b7) and I can't reproduce there. Maybe db48f97 fixed this? I'll also make sure if there's no regression on master just in case, and close this issue after confirming.

**Comment by rszyma** [comment]
I've noticed that the crash only happens when starting Hyprland with the monitors config in `1.` (laptop monitor disabled). When started with monitors config like in `2.` I can comment/uncommment `monitor=eDP-1,disable` line freely without any crashes.

**Comment by rszyma** [comment]
no longer can repro on main f10996b
