### ISSUE TITLE
Special Workspace Not Hidden at Startup

### ISSUE THREAD

**Issue by shanqs12** [hyprwm/Hyprland#3187]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

I use two special workspaces defined in the conf file to autostart.

`exec-once = [ workspace special ] wezterm`
`exec-once = [ workspace special:music ] wezterm -e ncmpcpp`

Upon starting hyprland one of them is visible and it's random as to which.  Downgrading to v0.29.0-1 returns to expected behavior of them being hidden until activated by keybind.

`bind = $MK,      grave,     togglespecialworkspace`
`bind = $MK $MK1, grave,     togglespecialworkspace, music`

I have no window rules defined for the wezterm class or ncmpcpp title.

### How to reproduce

Upgrade from v0.29.0-1 to v0.29.1-1 in Arch extra repo with config formatted as above.

**Comment by MightyPlaza** [comment]
intended behavior, use `silent` if you don't want it to open when using exec rules

**Comment by shanqs12** [comment]
Thank you, that resolved my issue.
