### ISSUE TITLE
Cursor is moved to center when clicking in vmware workstation guest

### ISSUE THREAD

**Issue by MoetaYuko** [hyprwm/Hyprland#3190]
### Hyprland Version

Hyprland, built from branch main at commit c3a83daa1e61285a418c39a1d9f29427c2c9a2c3 dirty (monitor: minor adjustments). Tag: v0.29.1-18-gc3a83daa

### Bug or Regression?

Bug

### Description

1. Prior to https://github.com/hyprwm/Hyprland/commit/28a90d6055f7b616c611c839967765f6536a7cd9, it works fine
2. After https://github.com/hyprwm/Hyprland/commit/28a90d6055f7b616c611c839967765f6536a7cd9, the cursor is moved to the top left corner every time I click in a vmware virtual machine, making it unusable.
3. After https://github.com/hyprwm/Hyprland/commit/d9937fcdba978af4f36be6cb20311e08f43841f5 which claims to fix https://github.com/hyprwm/Hyprland/commit/28a90d6055f7b616c611c839967765f6536a7cd9, the cursor is moved to center of the grabbed area on clicking.

ps: vmware workstation works in xwayland mode. More specifically, the cursor move happens on mouse button release, and clicking in textarea doesn't trigger the issue.

### How to reproduce

click the mouse in vmware workstation guest

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/5774651/9ad8958a-0fd1-4ec4-838b-290eece23022

Log is at https://fars.ee/gnAO (but not of the same run as the video). I left-clicked the mouse three times, corresponding to the three occurrences of `Constrained/Unconstrained mouse` pairs in the log.

edit: more specifically, `Constrained mouse` is triggered on press, cursor doesn't move. `Unconstrained mouse` is triggered on release, cursor gets moved to center.

**Comment by memchr** [comment]
Can you debug your Hyprland session? the function to watch for is `CCompositor::warpCursorTo`.

Even though warpCursor has no effect on the host compositor in the nested session, the function call should still be there so it can be debugged, 

Watch out for something like
```cpp
Vector2D middle = PWINDOW->m_vRealPosition.goalv() + PWINDOW->m_vRealSize.goalv() / 2.f
g_pCompositor->warpCursorTo(middle)
```

**Comment by MoetaYuko** [comment]
Emm...unfortunately vmware can't start in nested hl session:
```
(vmware:211227): Gtk-WARNING **: 14:17:21.806: cannot open display: :1
```
got the same error when trying to start another gtk-based xwayland application zotero, any ideas?

**Comment by MoetaYuko** [comment]
> Can you debug your Hyprland session? the function to watch for is `CCompositor::warpCursorTo`.
> 
> Even though warpCursor has no effect on the host compositor in the nested session, the function call should still be there so it can be debugged,
> 
> Watch out for something like
> 
> ```c++
> Vector2D middle = PWINDOW->m_vRealPosition.goalv() + PWINDOW->m_vRealSize.goalv() / 2.f
> g_pCompositor->warpCursorTo(middle)
> ```
> 
> `CCompositor::warpCursorTo(const Vector2D& pos, bool force)` is in `src/Compositor.cpp` line 2210.

I added a breakpoint at https://github.com/hyprwm/Hyprland/blob/c3a83daa1e61285a418c39a1d9f29427c2c9a2c3/src/Compositor.cpp#L2215 but it's never entered.

**Comment by MoetaYuko** [comment]
My issue is gone after commenting https://github.com/hyprwm/Hyprland/blob/c3a83daa1e61285a418c39a1d9f29427c2c9a2c3/src/events/Devices.cpp#L125-L126
the if condition may need to be tuned.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12537443/patch.txt)
?

**Comment by MoetaYuko** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/12537443/patch.txt) ?

it works, thanks

**Comment by ThomChroma** [comment]
I still have the exact same behavior with Blender: to top-left with 0.29 and now to center of the window with 0.30. I thought 6860e2d and the patch would fix it but apparently not.

It happens when clicking or grabbing a number input where arrows appear when the cursor hovers it.

Disabling 'Input/Continuous grab' in Blender fixes it but it's not ideal then.

[cursor-issue.log](https://github.com/hyprwm/Hyprland/files/12709132/cursor-issue.log)

**Comment by memchr** [comment]
> I still have the exact same behavior with Blender: to top-left with 0.29 and now to center of the window with 0.30. I thought https://github.com/hyprwm/Hyprland/commit/6860e2d254d9f1ed40f9edfcb1a0b4e662317e66 and the patch would fix it but apparently not.

#3270 pointer constraints problem

**Comment by ThomChroma** [comment]
Thanks, I didn't see this one…
