### ISSUE TITLE
Hyprland take over binds of vms. 

### ISSUE THREAD

**Issue by musicfunfan** [hyprwm/Hyprland#3193]
### Hyprland Version

Hyprland, built from branch  at commit 0a78f6031c8fcc6773f136fccde3d560aaac239d dirty (). Tag: v0.29.0  flags: (if any)

### Bug or Regression?

Bug

### Description

I have a vm that is the same system as the host. The vm i use for testing stuff that i do not want to test on the bare metal. So the problem is that the vm and the main system have the same binds. And when i try to use this binds on the vm Hyprland takes over even when i have focus on the vm window. 

I use VirtManaget for the vms with qemu. 
I am on archlinux. 

What i do wrong ?

### How to reproduce

Run a vm on VirtManager wirh the key binds as the host system.

**Comment by MightyPlaza** [comment]
submap?

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Binds/#submaps

**Comment by musicfunfan** [comment]
Ok so i look it up on the wiki no my binds is not submaps.

**Comment by MightyPlaza** [comment]
make an empty submap just with a key to exit the submap

**Comment by musicfunfan** [comment]
I do not understand what this have to do with my problem... I mean the binds is not like the resize mode is just for running a command.

**Comment by musicfunfan** [comment]
But i am not. I do not have submap binds on the config...

**Comment by musicfunfan** [comment]
The vm is still on sway... xD i was trying to update it to hyprland...

**Comment by musicfunfan** [comment]
But the key binds is the same.

**Comment by vaxerski** [comment]
jesus christ lmfao

```
bind = SUPER, S, submap, passthru
submap = passthru
bind = SUPER, Escape, submap, reset
submap = reset
```

`SUPER+S` to enter "no binds mode" then `SUPER+Escape` to exit.

**Comment by MightyPlaza** [comment]
in the host hyprland config

**Comment by musicfunfan** [comment]
Why when i focus the vm not all the keyboard goes to the vm? 
Why modify key stuck on host os ?

**Comment by MightyPlaza** [comment]
how would you close the application or do anything else in the host system, without the mouse

**Comment by musicfunfan** [comment]
You can press CTRL+ALT to unlock the keyboard from the vm....

**Comment by musicfunfan** [comment]
So in order to make my vm keybinds work i need make **all my keybinds** submap on the host. And i need to have a bind to exit the submap when i need to use my keyboard for the host ?

I ques i will try that. But i still thing that this is bug... 

The ability to block a window to take the whole keuboard is **very nice** but in my opinion this need to be an optional thing. Because most windows that need to take over the whole keyboard they also have an option to "unlock" the keyboard.

But anyway thenx for the response.
