### ISSUE TITLE
Some programs crashing when disconnect the external monitor

### ISSUE THREAD

**Issue by coffebar** [hyprwm/Hyprland#3199]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

When I disconnect the external monitor some of the apps crash.

### Noticed these apps:
- google-chrome-stable
- keepassxc
- telegram-desktop

### How to reproduce

1. Connect a monitor 
2. Start app `keepassxc` from the terminal emulator
3. Disconnect a monitor 
4. See `keepassxc` process finished with logs:
```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
wl_display@1: error 0: invalid object 26
The Wayland connection experienced a fatal error: Invalid argument
```

### Crash reports, logs, images, videos

I have a [core-dump](https://github.com/hyprwm/Hyprland/files/12542063/crash-chrome.txt) of the google-chrome-stable, but I doubt it is useful.

**Comment by vaxerski** [comment]
fixed in git
