### ISSUE TITLE
Fail compilation on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by Lampadina17** [hyprwm/Hyprland#3203]
### Hyprland Version

main

### Bug or Regression?

Bug

### Description

Error while compilation

### How to reproduce

sudo apt-get install -y meson wget build-essential ninja-build cmake-extras cmake gettext gettext-base fontconfig libfontconfig-dev libffi-dev libxml2-dev libdrm-dev libxkbcommon-x11-dev libxkbregistry-dev libxkbcommon-dev libpixman-1-dev libudev-dev libseat-dev seatd libxcb-dri3-dev libvulkan-dev libvulkan-volk-dev  vulkan-validationlayers-dev libvkfft-dev libgulkan-dev libegl-dev libgles2 libegl1-mesa-dev glslang-tools libinput-bin libinput-dev libxcb-composite0-dev libavutil-dev libavcodec-dev libavformat-dev libxcb-ewmh2 libxcb-ewmh-dev libxcb-present-dev libxcb-icccm4-dev libxcb-render-util0-dev libxcb-res0-dev libxcb-xinput-dev xdg-desktop-portal-wlr

git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
sudo make install

### Crash reports, logs, images, videos

- Setting precompiled headers
-- Setting link libraries
Could not open input file: No such file or directory
Could not open input file: No such file or directory
Could not open input file: No such file or directory
Could not open input file: No such file or directory
-- Configuring done
CMake Error at CMakeLists.txt:95 (add_executable):
  Cannot find source file:

    protocols/fractional-scale-v1-protocol.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
make[1]: *** [Makefile:12: release] Errore 1
make[1]: uscita dalla directory «/home/francesco/Hyprland»
make: *** [Makefile:38: install] Errore 2

**Comment by vaxerski** [comment]
ubuntu is not supported
