### ISSUE TITLE
d9937fc Breaks League of Legends constraints on Double Monitor

### ISSUE THREAD

**Issue by DeckedSpring67** [hyprwm/Hyprland#3204]
### Hyprland Version

d9937fcdba978af4f36be6cb20311e08f43841f5

### Bug or Regression?

Regression

### Description

When using a double monitor, starting the game on the one in the right makes the mouse be constrained in a little rectangular window to the right making it unplayable. Worked fine before, works fine in gamescope but it's annoying/partially unusable since cursor icons are rendered half way, the window is unmovable since it grabs the mouse and the game needs to be started from a launcher (client).
EDIT: It also works fine if I set the secondary monitor to -1600 instead of 0. (I used to have my primary one at +1600,0) 

Works fine on a single monitor.

### How to reproduce

Start the game, focus it, the mouse is constrained incorrectly.

### Crash reports, logs, images, videos

Monitor Config: 

monitor=HDMI-A-1, 1600x900, 0x0, 1
monitor=DP-3, 1920x1080@144.001007, 1600x0, 1 (The one where the game is launched)

Client: 
Window 55c66ed4a830 -> League of Legends (TM) Client:
    mapped: 1
    hidden: 0
    at: 1600,0
    size: 1920,1080
    workspace: 2 (2)
    floating: 0
    monitor: 1
    class: league of legends.exe
    title: League of Legends (TM) Client
    initialClass: league of legends.exe
    initialTitle: League of Legends (TM) Client
    pid: 17625
    xwayland: 1
    pinned: 0
    fullscreen: 1
    fullscreenmode: 0
    fakefullscreen: 0
    grouped: 0
    swallowing: 0

https://github.com/hyprwm/Hyprland/assets/10902117/efb6d632-676c-4da7-a089-3078db704e70

**Comment by vaxerski** [comment]
thats good, we dont want people playing league of legends

**Comment by romanstingler** [comment]
love your MOTD (Message of the day) :)

**Comment by DeckedSpring67** [comment]
> thats good, we dont want people playing league of legends

Still, it's something that regressed after a commit, and only under certain circumstances (secondary monitor on a positive offset), I'm sure it's not limited to League of Legends, it's just the first issue I've encountered so I think it's worth investigating it.

**Comment by NotAShelf** [comment]
y'all need to understand that league of legends misbehaving is a *feature*, not a bug

**Comment by vaxerski** [comment]
please test #3381

**Comment by DeckedSpring67** [comment]
#3381 Fixed it on my end, I'll wait for other feedback before closing it
