### ISSUE TITLE
Remember focus per-workspace

### ISSUE THREAD

**Issue by uoou** [hyprwm/Hyprland#3205]
### Description

Current behaviour seems to be that, when switching workspaces, the focused window on the workspace you're switching to matches (as best it can) the focus of the workspace you're switching from.

i.e. if I'm on workspace 1 with three windows open and focus on the first window, then switch to workspace 2, also with three windows open and switch focus to the third window, then switch back to workspace 1 and focus is on the third window.

It'd be nice if workspaces 'remembered' which window is focused. *Or* just focus the first window when switching (I did the latter with keybinds but that breaks monocled workspaces out of monocle mode when switching to them).

Apologies if this is mentioned elsewhere - I did search - or possible in configs - I did try!

**Comment by uoou** [comment]
I just tried a blank config and it definitely doesn't behave that way for me (and never has).

**Comment by MightyPlaza** [comment]
works for me, do you have `follow_mouse` != 1

**Comment by uoou** [comment]
Ahh okay, so it works how I expect with `follow_mouse = 0`. **But**... I also want focus to follow mouse. Just not on workspace switching. i.e. after switching it should only follow the mouse after the mouse moves.

**Comment by MightyPlaza** [comment]
use 2 to change focus when you click the window

**Comment by uoou** [comment]
Yeah that's absolutely fair enough - but not what I want.

**Comment by MightyPlaza** [comment]
having to move mouse isn't a solution either since any slight vibration would change the focused window out of nowhere
warping mouse to center of focused window on workspace change doesn't seem like a good idea as well

**Comment by uoou** [comment]
> any slight vibration would change the focused window

I've literally never had that happen in all my years of using WMs!

You've given me a clue though. What I was trying to do before was adding a binding (on the same keys) after switching workspace to focus the first window. But, as mentioned, this popped monocled workspaces out of monocle.

Instead I could just add a binding which move the mouse to top left (or, ideally centre of first window if I can figure that out) after switching.

**Comment by uoou** [comment]
On digging a bit deeper into the wiki:

```
mouse_refocus

If disabled and follow_mouse=1 then mouse focus will not switch to the hovered window unless the mouse crosses a window boundary.
```

Sounds like exactly what I want. But on setting `mouse_refocus = false` either it's doing nothing or I don't understand what it's doing and it's not what I expected.

**Comment by andresilva** [comment]
After https://github.com/hyprwm/Hyprland/commit/b884544ee63b4c3b3b150ff69cf24c90058c2777 this seems to be fixed for me.

> Sounds like exactly what I want. But on setting mouse_refocus = false either it's doing nothing or I don't understand what it's doing and it's not what I expected.

I also have no clue what `mouse_refocus` is meant to do. Didn't notice any difference in behavior after disabling it.

**Comment by uoou** [comment]
That definitely fixes it when switching on the same monitor, but when switching to another monitor, *no* window is focused, which is not good.

Definitely getting there though!

I *greatly* appreciate the work.

**Comment by uoou** [comment]
As far as I can tell this all works great now. Gonna close this issue.

Thanks for the work, devs. Greatly appreciated <3
