### ISSUE TITLE
Combinational window rules

### ISSUE THREAD

**Issue by siyia2** [hyprwm/Hyprland#3206]
### Description

For some odd wine apps i would like combinational window rules in order to make them behave.

For example: windowrulev2 = workspace name:4.Games-Misc, fullscreen: 1 floating: 1

**Comment by imxyy1soope1** [comment]
read the wiki

**Comment by vaxerski** [comment]
read the wiki moment indeed

**Comment by siyia2** [comment]
from wiki: windowrulev2 = opacity 0.5 0.5,floating:1, i would like this => windowrulev2 = opacity 0.5 0.5,floating:1 fullscreen: 1, two conditions for rule to apply not one.

**Comment by burein-ita** [comment]
comma moment

**Comment by siyia2** [comment]
`windowrulev2 = workspace name:4, fullscreen:1, floating:1` rule doesnt work

**Comment by burein-ita** [comment]
space moment

**Comment by siyia2** [comment]
`windowrulev2 = workspace name:4 fullscreen:1 floating:1` same

**Comment by siyia2** [comment]
can we just face reality and accept that it just doesn't work? ;)

**Comment by imxyy1soope1** [comment]
maybe it's just about shitty xwayland...?

**Comment by siyia2** [comment]
maybe it needs to be implemented :)

**Comment by vaxerski** [comment]
it's implemented already.

**Comment by siyia2** [comment]
> it's implemented already.

both conditions -> for one rule?

**Comment by vaxerski** [comment]
yes.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/47a42110-08d6-4585-a000-e5c7787c5550)

works without issues.

Your problem is that the `workspace` rule is not dynamic.

**Comment by siyia2** [comment]
is it possible to make it dynamic?

**Comment by vaxerski** [comment]
no
