### ISSUE TITLE
Unpluggin external monitor closes all programs from workspaces > 4

### ISSUE THREAD

**Issue by honuonhval** [hyprwm/Hyprland#3211]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

I have some programs running on workspace 9 (i.e. spotify, but could be anything) and I also have programs running on workspaces 1-5.  When I unplug external monitor from laptop all programs on workspaces 5-9 (and 10? I don't use it) closes and I have to start it again.

### How to reproduce

1. start hyprland
2. plug in external monitor to the laptop
3. start some program on workspace 1 (ie firefox)
4. start some program on workspace 9 (ie spotify)
5. unplug external monitor

### Crash reports, logs, images, videos

I don't see any logs or crash reports around this incident

**Comment by MightyPlaza** [comment]
`hyprctl clients` before and after?

**Comment by honuonhval** [comment]
Might have been issue on my machine.  Can't repro anymore.

**Comment by honuonhval** [comment]
Issue keeps coming back once in a while:

Before (monitor plugged in, spotify music playing):
`Window 561051e94330 -> daily.org – Doom Emacs:
	mapped: 1
	hidden: 0
	at: 11,41
	size: 1898,1148
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: emacs
	title: daily.org – Doom Emacs
	initialClass: emacs
	initialTitle: *scratch* – Doom Emacs
	pid: 1583
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 5610526c0b00 -> hyprctl clients:
	mapped: 1
	hidden: 0
	at: 1931,41
	size: 1898,1028
	workspace: 3 (3)
	floating: 0
	monitor: 1
	class: kitty
	title: hyprctl clients
	initialClass: kitty
	initialTitle: bash
	pid: 2414
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 5610526aff60 -> Instagram — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 1931,41
	size: 1898,1028
	workspace: 2 (2)
	floating: 0
	monitor: 1
	class: firefox
	title: Instagram — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 2064
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 5610530d0e40 -> Spotify:
	mapped: 1
	hidden: 0
	at: 1931,41
	size: 1898,1028
	workspace: 9 (9)
	floating: 0
	monitor: 1
	class: 
	title: Spotify
	initialClass: 
	initialTitle: Spotify
	pid: 46929
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0`

After (monitor unplugged, spotify music keeps playing and see it in my tray but cannot access):
`Window 561051e94330 -> daily.org – Doom Emacs:
	mapped: 1
	hidden: 0
	at: 11,41
	size: 1898,1148
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: emacs
	title: daily.org – Doom Emacs
	initialClass: emacs
	initialTitle: *scratch* – Doom Emacs
	pid: 1583
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 5610526c0b00 -> ~/projects/yaotai:
	mapped: 1
	hidden: 0
	at: 11,41
	size: 1898,1148
	workspace: 3 (3)
	floating: 0
	monitor: 0
	class: kitty
	title: ~/projects/yaotai
	initialClass: kitty
	initialTitle: bash
	pid: 2414
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 5610526aff60 -> Instagram — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 1931,41
	size: 1898,1028
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: firefox
	title: Instagram — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 2064
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0`

**Comment by vaxerski** [comment]
this was fixed in -git iirc. Please check.

**Comment by honuonhval** [comment]
Confirmed.  Fixed in -git
