### ISSUE TITLE
Event "renameworkspace" is not fired

### ISSUE THREAD

**Issue by targodan** [hyprwm/Hyprland#3212]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1  flags: (if any)

### Bug or Regression?

Regression

### Description

When renaming workspaces, the event "renameworkspace" does not get fired. This is critical to work for autorenamers with waybar. The waybar module "hyprland/workspace" does listen for the event, but it is never fired. Thus workspace names do not get updated until a restart of waybar.

Also the documentation is inconistent. On the [IPC page](https://wiki.hyprland.org/IPC/) the event is listed. But on the [Plugin Event List](https://wiki.hyprland.org/Plugins/Development/Event-list/) it is missing.

### How to reproduce

Start hyprland and listen for the events:

```shell
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock
```

Now while looking at the socat output, rename a workspace.

```shell
# For example
hyprctl dispatch renameworkspace 1 "1 no event"
```

You'll see in the socat output, that no renameworkspace event is fired.

**Comment by vaxerski** [comment]
docs arent inconsistent, socket2 events do not 1:1 correspond to plugin events.

MRs welcome, currently on a plane.

**Comment by MightyPlaza** [comment]
old version, not implemented

**Comment by vaxerski** [comment]
fact

**Comment by targodan** [comment]
I feel like the communication here is a bit lacking.

Okay, I understand that argument about the docs not being inconsistent. :+1: 

> old version, not implemented

What's an old version? The version I'm running? Afaik it's the latest released version. What do you mean by "not implemented" what isn't implemented? The socket2 event "renameworkspace"? Although the documentation lists it without any mention of it being not implemented?

Also if that is indeed not implemented, dropping the `ext_workspace_v1` supports seems to have been called early. With `ext_workspace_v1` I was able to use the waybar module `wlr/workspaces` which worked nicely. The `hyprland/workspaces` module on the other hand (at least without the renameworkspaces event) is barely usable for me.

As things stand, my experience with hyprland has been crippled.

**Comment by MightyPlaza** [comment]
latest release has before the event was added
you either have to build from main branch or wait for new release
documentation by default shows latest not last release (maybe this should changed or a warning should be added)
either way there is no issue
https://github.com/hyprwm/Hyprland/discussions/3215

**Comment by targodan** [comment]
Okay, I see. Thanks for clarifying. 🙂
