### ISSUE TITLE
blur_new_optimizations

### ISSUE THREAD

**Issue by definetly-not-carl** [hyprwm/Hyprland#3213]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc  (). Tag: v0.29.1  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Hello there!
I'm using F38 and I managed to install it through the guide under the already opened discussion.

I don't know how, but hyprland is giving me an error with the blur_new_optimizations saying that this field does not exists.

Could you tell me how to resolve it?

### How to reproduce

I don't know how to reproduce it since it continues to happen no matter what I do

### Crash reports, logs, images, videos

```
Config error at line 69 (/home/notcarl/.config/hypr/hyprland.conf) Errore setting value <false> for field <decoration:blur_new_optimizations>: No such field. Hyprland may not work correctly.
```

**Comment by vaxerski** [comment]
because it doesnt. Read the wiki.
