### ISSUE TITLE
Your implementation preferences?

### ISSUE THREAD

**Issue by alaricljs** [hyprwm/Hyprland#3214]
### Description

I'd like to add some floating-window specific features & changes and would like your advanced input on basic design goals.

An example is the dispatcher `bringactivetotop`.  I'd like to implement `pushactivetobottom` and would like to know if that's a good name choice/implementation style, or if you'd rather a single new dispatcher w/ a parameter for top/bottom, or something completely different?

There's a collection of other small improvements as well, would you want this all as separate PRs or one?

Thanks!

**Comment by vaxerski** [comment]
> An example is the dispatcher bringactivetotop. I'd like to implement pushactivetobottom and would like to know if that's a good name choice/implementation style, or if you'd rather a single new dispatcher w/ a parameter for top/bottom

changing that takes 5 minutes. You make a MR  I review it

> There's a collection of other small improvements as well, would you want this all as separate PRs or one?

if they regard the dispatcher, one. If they don't, separate. Use your brain and feeling for this one.
