### ISSUE TITLE
can you include all wlroots files and meson build in the source?

### ISSUE THREAD

**Issue by adcdam** [hyprwm/Hyprland#322]
i want to package this for Slackware but they dont allow the Slackbuilds to gitclone or download the subprojects as you dont want Hyprland to use system wlroots can you at least include the files needed in the source  Hyprland subproject?

**Comment by vaxerski** [comment]
no, thats what subprojects are for.

**Comment by eli-schwartz** [comment]
> but they dont allow the Slackbuilds to gitclone or download the subprojects

It seems strange that a slackbuild cannot do *either* of the valid choices:
- git clone as a subproject
- list a second source tarball in the recipe, and download it together with the Hyprland sources, then unpack it into the subprojects/wlroots/ directory.

It is ***absolutely*** not the responsibility of any project, anywhere, to sacrifice the clarity of git submodules and corrupt their `git log` output with tons and tons of diffed file changes for files that are vendored and checked into git.

Some projects might decide to do that anyway, and that's their choice. But if a project does the sensible thing and uses git submodules, they have a reason for it. :)

"Slackware has an arbitrary rule that all sources need to be part of the initial project sources" sounds like either a policy bug in slackware, or more likely a misunderstanding of the slackware rules. I'm pretty sure any other distro I ever looked at, allows multiple source tarballs. It's the correct solution. It doesn't require doing networky things during the build.

**Comment by adcdam** [comment]
stick your arch linux in your ass. you dont want to al least put the fucking wlroots in suproject.

**Comment by eli-schwartz** [comment]
@adcdam 

Personally I agree that it should build with the system wlroots.

But if you're going to accept building a private copy of wlroots, there is no reason not to download both these files:

https://github.com/hyprwm/Hyprland/archive/refs/tags/v0.6.3beta.tar.gz
https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/5c4384a1330faedf975c8b8644881d50390f3613/wlroots-5c4384a1330faedf975c8b8644881d50390f3613.tar.gz

It is absolutely 100% compatible with any distro that is willing to use a bundled wlroots in the first place.
And unpack the second tarball into the `subprojects/wlroots/` directory of the first tarball.
