### ISSUE TITLE
wlr_output_management_v1 protocol not implemented properly

### ISSUE THREAD

**Issue by Smona** [hyprwm/Hyprland#3220]
### Hyprland Version

v0.27.0

### Bug or Regression?

Bug

### Description

I am trying to update [rot8](https://github.com/efernau/rot8) to support Hyprland, by making it use the wlroots output_management protocol to apply output rotations. I have it working in Sway, but in Hyprland I'm seeing some unusual behavior.

I can find the display and apply a new configuration with the transform modified, but the output doesn't actually rotate. I get an OutputConfiguration::Success event, but no new configuration serial is advertised via OutputManager::Done event. On future rotation attempts, the configuration change is cancelled, likely because an incorrect serial number was provided. Also, new transforms aren't reported via the OutputHead::Transform event when rotating an output using `hyprctl keyword monitor eDP-1,preferred,auto,1,transform,1`.

I could just add a hyprland-specific backend which uses hyprctl to communicate, but would love to get to a single implementation for all wlroots compositors.

### How to reproduce

Clone [my branch](https://github.com/Smona/rot8/tree/wlroots-support) and `cargo run` with rustc and cargo installed, both on sway and hyprland.

**Comment by vaxerski** [comment]
> wlr_output_management_v1 protocol not implemented properly

Very likely, the impl is half-assed

also version really old jsyk

**Comment by pdamianik** [comment]
@Smona could you try #3234 to see if it fixes your issue. I added a test flag for [rot8](https://github.com/efernau/rot8) locally to set the transform property since I don't have a acceleration sensor and confirmed it to be working, but I'd like to see if it also works for you.

**Comment by Smona** [comment]
I see y'all haven't lost your reputation for being the fastest guns in the west :)

@pdamianik your branch works perfectly for me, and appears to behave exactly the same as sway so far. I'll continue working on my change and cross-testing Sway x Hyprland from your branch until that gets merged. Thanks!

Just for the sake of completeness, I also tested against 0.29.1. In that version, my code _is notified_ of external transform changes from hyperctl, but transform changes from my code are still ignored without #3234.
