### ISSUE TITLE
Option to resize only bottom right corner

### ISSUE THREAD

**Issue by djvs** [hyprwm/Hyprland#3221]
### Description

Flag to act like resizing is always clicked on the bottom right corner would be very helpful.  Helps reduce mouse movement a lot & associated strain.  E.g., if you mod+right-click the top left corner, it'll just start resizing at the bottom right.

**Comment by djvs** [comment]
Me investigating the same issue 7 months later :(

**Comment by djvs** [comment]
https://github.com/hyprwm/Hyprland/issues/4440

**Comment by djvs** [comment]
A configuration option could be injected here: 

https://github.com/hyprwm/Hyprland/blob/6c53d4d82fd81aaa8aeb8c89ece1b88455a1f2a1/src/layout/IHyprLayout.cpp#L220

to just always enforce `m_eGrabbedCorner = CORNER_BOTTOMRIGHT` (or an arbitrary corner).  Would someone be so kind as to add that.

**Comment by vaxerski** [comment]
feel free to make a mr

**Comment by djvs** [comment]
https://github.com/hyprwm/Hyprland/pull/5090

**Comment by djvs** [comment]
Booyah achieved
