### ISSUE TITLE
Mouse jumps to center of monitor on click while playing Eve.

### ISSUE THREAD

**Issue by Eckstrom13** [hyprwm/Hyprland#3222]
### Hyprland Version

Hyprland, built from branch main at commit 664827473583f8e986f9fb2a37a13e9b3a232cc2 dirty (fix: focusWindow on hidden workspace triggers another focusWindow. (3216)). Tag: v0.29.1-33-g66482747

### Bug or Regression?

Bug

### Description

Hello,

Bit of a weird bug. Whenever i click on anything in Eve Online my mouse will immediately jump to the center of the current monitor

### How to reproduce

Download Eve and try to click something.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/110136044/d221aa18-6284-481d-b148-6c670195cb2f

**Comment by tchofy** [comment]
Seems like another case of https://github.com/hyprwm/Hyprland/issues/3190. Could either try the patch there or revert https://github.com/hyprwm/Hyprland/commit/28a90d6055f7b616c611c839967765f6536a7cd9 until this is fixed.
