### ISSUE TITLE
Building Plugin Env failing

### ISSUE THREAD

**Issue by Bcez** [hyprwm/Hyprland#3223]
### Hyprland Version

0.29.1

### Bug or Regression?

Bug

### Description

when building the plugin env, it stops because libinput is required but when installing it it says its already installed.

Fedora 38

### How to reproduce

i dont know how

### Crash reports, logs, images, videos

cd subprojects/udis86 && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B ./build -G Ninja && cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`
Not searching for unused variables given on the command line.
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/eric/hyprland-plugins/Hyprland/subprojects/udis86/build
ninja: no work to do.
make fixwlr
make[1]: Entering directory '/home/eric/hyprland-plugins/Hyprland'
sed -E -i -e 's/(soversion = 12)([^032]|$)/soversion = 12032/g' subprojects/wlroots/meson.build
rm -rf ./subprojects/wlroots/build
make[1]: Leaving directory '/home/eric/hyprland-plugins/Hyprland'
meson setup subprojects/wlroots/build subprojects/wlroots --prefix=/usr/local --buildtype=release -Dwerror=false -Dexamples=false
The Meson build system
Version: 1.0.1
Source dir: /home/eric/hyprland-plugins/Hyprland/subprojects/wlroots
Build dir: /home/eric/hyprland-plugins/Hyprland/subprojects/wlroots/build
Build type: native build
Project name: wlroots
Project version: 0.17.0-dev
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)")
C linker for the host machine: cc ld.bfd 2.39-9
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Walloca: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency wayland-server found: YES 1.22.0
Run-time dependency libdrm found: YES 2.4.114
Run-time dependency xkbcommon found: YES 1.5.0
Run-time dependency pixman-1 found: YES 0.42.2
Library m found: YES
Library rt found: YES
Run-time dependency wayland-protocols found: YES 1.32
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Build-time dependency wayland-scanner found: YES 1.22.0
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Has header "linux/dma-buf.h" : YES 
Run-time dependency egl found: YES 1.5
Run-time dependency gbm found: YES 23.1.6
Run-time dependency glesv2 found: YES 3.2
Program ./embed.sh found: YES (/home/eric/hyprland-plugins/Hyprland/subprojects/wlroots/render/gles2/shaders/./embed.sh)
Run-time dependency vulkan found: NO (tried pkgconfig and system)
Message: Required for vulkan renderer support.
Dependency pixman-1 found: YES 0.42.2 (cached)
Dependency gbm found: YES 23.1.6 (cached)
Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES 
Run-time dependency libudev found: YES 253
Found CMake: /usr/bin/cmake (3.27.4)
Run-time dependency libseat found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libseat
Neither a subproject directory nor a seatd.wrap file was found.
Subproject  seatd is buildable: NO (disabling)
Dependency libseat from subproject seatd found: NO (subproject failed to configure)
Message: Required for session support.
Found CMake: /usr/bin/cmake (3.27.4)
Build-time dependency hwdata found: NO (tried pkgconfig and cmake)
Message: Required for the DRM backend.
Run-time dependency libdisplay-info found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libdisplay-info
Neither a subproject directory nor a libdisplay-info.wrap file was found.
Subproject  libdisplay-info is buildable: NO (disabling)
Dependency libdisplay-info from subproject libdisplay-info found: NO (subproject failed to configure)
Message: Required for the DRM backend.
Run-time dependency libliftoff found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libliftoff
Neither a subproject directory nor a libliftoff.wrap file was found.
Subproject  libliftoff is buildable: NO (disabling)
Dependency libliftoff from subproject libliftoff found: NO (subproject failed to configure)
Run-time dependency libinput found: NO (tried pkgconfig and cmake)
Message: Required for libinput backend support.
Run-time dependency xcb found: YES 1.13.1
Run-time dependency xcb-dri3 found: YES 1.13.1
Run-time dependency xcb-present found: YES 1.13.1
Run-time dependency xcb-render found: YES 1.13.1
Run-time dependency xcb-renderutil found: NO (tried pkgconfig and cmake)
Message: Required for X11 backend support.
Run-time dependency wayland-client found: YES 1.22.0
Run-time dependency xwayland found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency xwayland
Neither a subproject directory nor a xserver.wrap file was found.
Subproject  xserver is buildable: NO (disabling)
Dependency xwayland from subproject xserver found: NO (subproject failed to configure)
Configuring config.h using configuration
Configuring version.h using configuration
Configuring config.h using configuration
Build targets in project: 129

wlroots 0.17.0-dev

    drm-backend     : NO
    x11-backend     : NO
    libinput-backend: NO
    xwayland        : NO
    gles2-renderer  : YES
    vulkan-renderer : NO
    gbm-allocator   : YES
    session         : NO
    xcb-errors      : NO
    egl             : YES

  Subprojects
    libdisplay-info : NO Neither a subproject directory nor a libdisplay-info.wrap file was found.
    libliftoff      : NO Neither a subproject directory nor a libliftoff.wrap file was found.
    seatd           : NO Neither a subproject directory nor a seatd.wrap file was found.
    xserver         : NO Neither a subproject directory nor a xserver.wrap file was found.

  User defined options
    buildtype       : release
    prefix          : /usr/local
    werror          : false
    examples        : false

Found ninja-1.11.1 at /usr/bin/ninja
ninja -C subprojects/wlroots/build/
ninja: Entering directory `subprojects/wlroots/build/'
[273/273] Linking target libwlroots.so.12032
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B ./build -G Ninja
Not searching for unused variables given on the command line.
-- Gathering git info
-- Found WaylandScanner at /usr/bin/wayland-scanner
-- Found wayland-protocols at //usr/share/wayland-protocols
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Checking for modules 'wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;libdrm;xkbcommon;libinput;pango;pangocairo;pixman-1'
--   Package 'libinput', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:91 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
make: *** [Makefile:99: pluginenv] Error 1

**Comment by vaxerski** [comment]
reading the error would help.
```
-- Package 'libinput', required by 'virtual:world', not found
```

**Comment by Bcez** [comment]
> 

I know that the problem is that libinput is already installed and i tried reinstalling it but didint work

**Comment by vaxerski** [comment]
that's a problem with your system, not hyprland.
