### ISSUE TITLE
Can't compile since "formatting" changes

### ISSUE THREAD

**Issue by droc12345** [hyprwm/Hyprland#3228]
### Hyprland Version

git 1a6f961de2eff84e4725255f09d33395c4a52fcc (latest)

### Bug or Regression?

Bug

### Description

Can't compile, complains about missing file - format, doesn't understand std:vformat 

I'm using gcc 12.3, 

### How to reproduce

Try compiling the latest git.

### Crash reports, logs, images, videos

no crash reports as this is a compilation issue

**Comment by memchr** [comment]
You should use at least gcc-13 or clang-16.

**Comment by droc12345** [comment]
I chased down the problem, as it appears that >= gcc 13 is needed, 

Which is a ridiculous requirement (IMO), and it should have been caught in the meson build file, and not even tried to compile

**Comment by droc12345** [comment]
SIgh, I guess I'll have to update gcc Sigh

**Comment by memchr** [comment]
Hyprland is using C++23, what do you think?

**Comment by vaxerski** [comment]
pff, <format> is C++20.
