### ISSUE TITLE
Floating window snapping would be awesome!

### ISSUE THREAD

**Issue by Oglo12** [hyprwm/Hyprland#3230]
### Description

I often find myself using picture in picture mode to watch YouTube videos whilst programming, and something I always hate is having to line up the pop-up perfectly! I would love to see a feature where windows that move near the edges of the screen or other windows would snap to the edge of the target, and takes a little bit of movement to unsnap. Kind of like what is in most desktop environments and even some floating WMs/compositors. I think this would be an amazing improvement, even for a tiling WM/compositor!

**Comment by shadowmax31** [comment]
I'll give it a shot

**Comment by alaricljs** [comment]
@shadowmax31 are you still working on this?  I would love to see this get merged.

**Comment by shadowmax31** [comment]
@alaricljs It's done on my part, I've been using it for 2 weeks, it works fine. I kinda just don't feel like going through the review process...feel free to take over my merge request if you want :)

**Comment by asiantuntija** [comment]
Added in https://github.com/hyprwm/Hyprland/pull/8088
