### ISSUE TITLE
Give bars the possibility to movetoworkspace by dragging a window on a workspace

### ISSUE THREAD

**Issue by loissascha** [hyprwm/Hyprland#3231]
### Description

Idk how this would be done or if it's even possible in the first place, but I think it would really be a nice feature to be able to just drag a window on top of a workspace number/icon/whatever on my bar and just drop it there.
Maybe it's possible to trigger an event or something if a window is dropped with the exact display location so bars can subscribe to the event to make something like this possible? 

 I use my pc all the time and while a very keyboard heavy workflow is great for work, it sometimes can be a bit annoying if you actually need 2 hands to move things. I guess I still need 2 hands to even drag a window (I wish there was like a button I could press to enable somehow a mouse only drag and drop kinda workflow for the less productivity heavy stuff I'm doing; something like a mouse 4 + mouse 1 to drag a window or to be able to show header bars which can be dragged)

**Comment by MightyPlaza** [comment]
only thing that should be done on hyprland's side is adding IPC/plugin events for begin/end dragging window
the rest would have to be handled on the bar's end

**Comment by vaxerski** [comment]
not possible
