### ISSUE TITLE
Waybar workspaces stopped working (both waybar and waybar-hyprland)

### ISSUE THREAD

**Issue by AdrianBonpin** [hyprwm/Hyprland#3238]
### Hyprland Version

0.29.1

### Bug or Regression?

Bug

### Description

After an update, waybar workspaces suddenly stopped working. I've already tried with both the waybar and waybar-hyprland versions but its still the same. Checked if it was my config but it still didnt work. I'm not really sure what is wrong and no errors are being thrown out so I'm pretty confused.

![20230910_11h10m07s_grim](https://github.com/hyprwm/Hyprland/assets/122008616/1132ccda-b5cb-4dd7-a819-2835e1608e45)

### How to reproduce

1. Start hyprland
2. Install waybar
3. set to wlr/workspaces
4. sad

**Comment by memchr** [comment]
`wlr/workspaces` is deprecated, use `hyprland/workspaces` instead

**Comment by AdrianBonpin** [comment]
> `wlr/workspaces` is deprecated/removed, use `hyprland/workspaces` instead

holy how did I not see this. Thank you very much!
