### ISSUE TITLE
Workspace back-and-forth (Similar to i3)

### ISSUE THREAD

**Issue by antecomp** [hyprwm/Hyprland#324]
Amazing project you have here!
Is there any plan to add functionality similar to [i3s back-and-forth](https://i3wm.org/docs/userguide.html#back_and_forth) to switch to the previously focused workspace?

Config could maybe something along the lines of `workspace,previous`?

**Comment by vaxerski** [comment]
I think he meant last focused one

**Comment by godalming123** [comment]
ok

**Comment by CharlesEkkel** [comment]
@antecomp My PR got merged! If it does what you wanted then it might be good to close this issue.
