### ISSUE TITLE
commit d490f19 - mouse never release

### ISSUE THREAD

**Issue by pbosab** [hyprwm/Hyprland#3240]
### Hyprland Version

Hyprland, built from branch main at commit c55fe27e90017860a2c494a7f5404e53eba94941 dirty (Revert keybinds: ignore mods on release of special binds).

### Bug or Regression?

Bug

### Description

Mouse clicks never get released.
Reverting commit d490f19 fixes the issue.

### How to reproduce

...

**Comment by zjeffer** [comment]
Can confirm, same issue here.

**Comment by vaxerski** [comment]
あ！ちょっと過失した、すまん
