### ISSUE TITLE
[FR] Option to change position of red "Config error" bar

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#3241]
### Description

This is an extremely small, low priority issue but when an error occurs, the red config error bar is displayed: 

![image](https://github.com/hyprwm/Hyprland/assets/4633209/1cc593d4-ae83-4292-8ece-0011d322e27d)

This bar always appears at the top of the screen, but this obscures my waybar. 
I'd like an option to always put this bar at the bottom of the screen. 

I'm aware it is possible to disable the bar, but I like to see if there are any problems. I often get errors due to plugins needing to be updated, so it's nice that the bar is there, but I don't want it to be in the same location as my waybar while I'm fixing the issue.

**Comment by zjeffer** [comment]
> how can I disable the bar?

In your Hyprland config, you can enable `suppress_errors`:

https://wiki.hyprland.org/Configuring/Variables/#debug

debug {
  suppress_errors = true
}

**Comment by Dreded** [comment]
> or u can close current one with `hyprctl seterror disable`

Thank you, the error is always Overtop of the text or website url I need to copy in order to fix the issue..

**Comment by KeepThisTicket** [comment]
The list of errors doesn't fit in the preview window for me - where can I see the full list of errors?
