### ISSUE TITLE
Message "[Runtime Error] Invalid keyboard layout passed. ( rules: , model: , variant: , options: , layout: abnt2 )"

### ISSUE THREAD

**Issue by estevaolelis** [hyprwm/Hyprland#3243]
### Hyprland Version

2.1

### Bug or Regression?

Bug

### Description

I new in this world of Hyprland, but I did everything right about installation but have this problem with keyboard: "[Runtime Error] Invalid keyboard layout passed. ( rules: , model: , variant: , options: , layout: abnt2 )". I tried put "abnt2" and "br-abnt2". I know is something stupid, and I want some help about this.

### How to reproduce

I watched this video: https://www.youtube.com/watch?v=sgDJnaMgtY0&lc=UgxsewaMgABFzruR3zh4AaABAg.9uRv8c4Mel29uUh-XyJO4v

I did everything the same way he did, but changed in minute 10:43, I tried "abnt2" and "br-abnt2"

**Comment by MightyPlaza** [comment]
please follow the wiki and not some random tutorial (https://wiki.hyprland.org/Getting-Started/Master-Tutorial/)

that being said and assuming he's setting up the layout on the config file
you can get all available layouts with `cat /usr/share/X11/xkb/rules/base.lst `
I have no idea what layout you're looking, for but should be in there

**Comment by vaxerski** [comment]
neither are a layout

**Comment by criskell** [comment]
`br` keyboard layout worked for me.
