### ISSUE TITLE
Release is a tarbomb

### ISSUE THREAD

**Issue by aldrenean** [hyprwm/Hyprland#325]
Steps to reproduce:

Download the latest release.

tar -xzvf release.tar.gz

Expected Outcome:

Files should be extracted into a subfolder.

Noted Outcome:

Files are extracted directly into the current directory.

This is pretty basic etiquette.

**Comment by vaxerski** [comment]
the AUR packages work with this in mind. If I was to change this with the next release, I'd need @ThatOneCalculator's approval

**Comment by ThatOneCalculator** [comment]
i mean yea go for it :D just ping me when u change shit :bowtie:

**Comment by vaxerski** [comment]
ok qt

**Comment by ThatOneCalculator** [comment]
*gtk :trollface:

**Comment by vaxerski** [comment]
fixed with 0.7.0beta
