### ISSUE TITLE
Waybar "wlr/workspaces" stopped working on latest release

### ISSUE THREAD

**Issue by rbroggi** [hyprwm/Hyprland#3251]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Regression

### Description

After the latest release (could be on `v0.29.0` or `v0.29.1`) the waybar module "wlr/workspaces" stopped working (I no longer can see the workspace where I currently am).

### How to reproduce

boot hyprland with waybar with a waybar config containing:

```json
{
    ...
    "modules-left": [
        "custom/power_btn",
        "custom/lock_screen",
        "wlr/workspaces"
    ],
    ...
}
```

**Comment by memchr** [comment]
Duplicate of #3238 (closed), please search for existing issue before opening one.
