### ISSUE TITLE
Mouse presses are not being released

### ISSUE THREAD

**Issue by Jadefalke256** [hyprwm/Hyprland#3256]
### Hyprland Version

Hyprland, built from branch main at commit df51c45d7f9e4e280b959f790f7cde6c88b9b451 dirty (keybinds: unify changeworkspace dispatcher (3250))

### Bug or Regression?

Bug

### Description

I am in great pain as I write this. I have been trying to figure out what was happening for hours, until I realized that my mouse-presses were not being released. 
Debugging with `wev` it seems like left- and right- presses are not being released, whereas middle presses are.

This is not a hardware issue, as it seems to work just fine on X11. 

### How to reproduce

I have no idea, this seems not to be happening to anyone else

### Crash reports, logs, images, videos

Sep 11 16:59:59 archlinux kernel: Code: 18 81 c3 00 00 00 01 81 fb 00 00 f0 00 77 56 48 8b 45 00 48 c1 e8 03 39 d8 72 5a 39 c3 74 1e 48 8b 45 10 43 8d 14 24 48 09 d1 <48> 89 0c d8 31 c0 48 83 c4 10 5b 5d 41 5c c3 0f 1f 40 00 48 89 4c
Sep 11 16:59:59 archlinux systemd[1]: Created slice Slice /system/systemd-coredump.
Sep 11 16:59:59 archlinux systemd[1]: Started Process Core Dump (PID 1317/UID 0).
Sep 11 16:59:59 archlinux systemd-coredump[1318]: Process 1198 (alacritty) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 1198:
                                                  #0  0x00007ff188e0f415 n/a (libwayland-client.so + 0x8415)
                                                  #1  0x00007ff188e0f573 n/a (libwayland-client.so + 0x8573)
                                                  #2  0x00007ff188e11132 wl_proxy_marshal_array_flags (libwayland-client.so + 0xa132)
                                                  #3  0x00007ff188e11bda wl_proxy_marshal_flags (libwayland-client.so + 0xabda)
                                                  #4  0x00007ff188a5a52f n/a (libnvidia-egl-wayland.so.1 + 0x852f)
                                                  #5  0x00007ff188a5d10f n/a (libnvidia-egl-wayland.so.1 + 0xb10f)
                                                  #6  0x00007ff1838acdd0 n/a (libEGL_nvidia.so.0 + 0xacdd0)
                                                  #7  0x00007ff1838a2c20 n/a (libEGL_nvidia.so.0 + 0xa2c20)
                                                  #8  0x00007ff188840cc6 n/a (libc.so.6 + 0x40cc6)
                                                  #9  0x00007ff188840e10 exit (libc.so.6 + 0x40e10)
                                                  #10 0x00007ff188827cd7 n/a (libc.so.6 + 0x27cd7)
                                                  #11 0x00007ff188827d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                                  #12 0x0000562f042941b5 n/a (alacritty + 0x8a1b5)
                                                  
                                                  Stack trace of thread 1259:
                                                  #0  0x00007ff18890359f __poll (libc.so.6 + 0x10359f)
                                                  #1  0x00007ff181d3615f n/a (libnvidia-eglcore.so.535.104.05 + 0x153615f)
                                                  #2  0x00007ff181d34aca n/a (libnvidia-eglcore.so.535.104.05 + 0x1534aca)
                                                  #3  0x00007ff18888c9eb n/a (libc.so.6 + 0x8c9eb)
                                                  #4  0x00007ff188910dfc n/a (libc.so.6 + 0x110dfc)
                                                  
                                                  Stack trace of thread 1208:
                                                  #0  0x00007ff188911226 epoll_wait (libc.so.6 + 0x111226)
                                                  #1  0x0000562f044d02a0 n/a (alacritty + 0x2c62a0)
                                                  #2  0x0000562f044cc1f4 n/a (alacritty + 0x2c21f4)
                                                  #3  0x0000562f044e0864 n/a (alacritty + 0x2d6864)
                                                  #4  0x0000562f045dd925 n/a (alacritty + 0x3d3925)
                                                  #5  0x00007ff18888c9eb n/a (libc.so.6 + 0x8c9eb)
                                                  #6  0x00007ff188910dfc n/a (libc.so.6 + 0x110dfc)
                                                  
                                                  Stack trace of thread 1209:
                                                  #0  0x00007ff18890ed6d syscall (libc.so.6 + 0x10ed6d)
                                                  #1  0x0000562f045ad814 n/a (alacritty + 0x3a3814)
                                                  #2  0x0000562f0430d871 n/a (alacritty + 0x103871)

**Comment by Jadefalke256** [comment]
I'm sorry for the format of the alacritty crash-dump format, I'm writing this while in enormous amounts of agony.
Not being able to use your mouse sucks.

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/issues/3240

**Comment by MightyPlaza** [comment]
@vaxerski

**Comment by vaxerski** [comment]
odchodząc zabierz mnie
