### ISSUE TITLE
Flatpak apps aren't able to open links in Browsers. 

### ISSUE THREAD

**Issue by RoccoRakete** [hyprwm/Hyprland#3258]
### Hyprland Version

v0.29.1-2-g8fefb180

### Bug or Regression?

Bug

### Description

Flatpak apps aren't able to open links in Browsers. According to #https://github.com/emersion/xdg-desktop-portal-wlr/issues/193 this seems to be an issue with xdg-desktop-portal.
Does anyone has the same issue or even a fix for that? Is it a bug?  

xdg-desktop-portal-hyprland-git 1:r296.aca5160-1

### How to reproduce

Try to open a link in a flatpak-app

### Crash reports, logs, images, videos

Output from Iotas: 

 Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface
»org.freedesktop.portal.Settings« n object at path /org/freedesktop/portal/desktop

**Comment by hoywu** [comment]
For anyone who encounters this problem:
Edit `/usr/share/xdg-desktop-portal/hyprland-portals.conf` as follows helped me solve the issue.
```
[preferred]
default=hyprland;gtk
```

Reference:
https://github.com/flatpak/flatpak/issues/1508#issuecomment-1702714679
https://github.com/hyprwm/Hyprland/pull/3469

**Comment by vaxerski** [comment]
this is not a hyprland issue, so closing
