### ISSUE TITLE
Q: How should I handle multiple monitor sources?

### ISSUE THREAD

**Issue by pebkacerr** [hyprwm/Hyprland#3259]
I have 2 monitors which I share (mix) between desktop (Windows) and laptop (Linux/Hyprland).
The laptop is connected to both monitors through a docking station (lid closed).

I've managed to turn off the laptop display using Switches (since the lid is closed) but when I change the input/source in one of the other monitors such that 1 monitor will be used by the desktop and the remaining one by the laptop, the desktop monitor is not being closed/removed in Hyprland (if I can phrase it like that) - it remains in the background. This leaves the possibility for the mouse to leave the active/visible workspace and get lost in the desktop (invisible workspace) monitor (which is currently showing Windows).

Is the above the expected behavior? 

I've tried to:
 - use socket2 IPC to detect "invisible" monitors such that I can turn the relevant monitor on/off but I didn't manage to pull that off since there's no such event for changing inputs - the monitor is not removed
 - dispatch DPMS off event manually (although not ideal) just to see how it would react and while it turns off the image for the monitor it doesn't close/remove it so the cursor can still wander

Is there a way such that when I switch the second monitor input/source to Windows, to have Hyprland (on the first monitor) close/remove the second monitor and rearrange/move the windows on the first monitor?

**Comment by vaxerski** [comment]
I do not understand what you are trying to achieve at all, but this is the issue tracker. For questions go to the discussions tab or discord server.

**Comment by t00** [comment]
@vaxerski 

I just struggled with a similar issue - laptop with external monitor connected and lid closed "loses" windows when switching/moving between workspaces. hyprland does not detect the monitor being removed and keeps windows on a laptop screen with closed lid. I use the same workflow on gnome and these happen:

1. When closing the lid, all windows are moved to the second monitor.
2. When lid is closed, switching workspace and moving window to workspace ignores closed lid screen
3. When opening lid workspaces are added but windows are not moved.

I would argue closed lid screen should not be accessible so this sounds like a bug, unless there is a toggle switch to change unexpected default behavior?

**Comment by vaxerski** [comment]
you can make a bind to the lid switch to execute a script to disable the monitor.

**Comment by t00** [comment]
Hint much appreciated, I found a similar bug with a toggle binds and an apparently more reliable script. I must say it feels like a hack for such typical scenario but I will live with it and give hyprland another go 👍 Thanks again.
