### ISSUE TITLE
Error when trying to build with Clang

### ISSUE THREAD

**Issue by SrEstegosaurio** [hyprwm/Hyprland#3263]
### Hyprland Version

ed51fe7bac76248933c71d3958fdb9a973066dfd

### Bug or Regression?

Bug

### Description

In the home-manager module, while settting the `package` to be:

```nix
package = inputs.hyprland.packages.x86_64-linux.default; #.override {stdenv = pkgs.clang16Stdenv;}; 
```

The build would fail with the following error:

```
-- snip snip --

[44/116] Compiling C object protocols/libserver_protos.a.p/meson-generated_.._pointer-constraints-unstable-v1-protocol.c.o
[45/116] Compiling C object protocols/libserver_protos.a.p/meson-generated_.._tablet-unstable-v2-protocol.c.o
[46/116] Linking static target protocols/libserver_protos.a
[47/116] Precompiling header ../src/pch/pch.hpp
FAILED: src/Hyprland.p/pch.hpp.pch
clang++ -Isrc/Hyprland.p -Isrc -I../src -Iprotocols -I/nix/store/jg74fkb8rgkybs18zryzdcsqwp901kgj-wayland-1.22.0-dev/include -I/nix/store/bw8kpklh132dxm34ryg7m13vbi2yrgr0-wlroots-hyprland-202
In file included from ../src/pch/pch.hpp:1:
In file included from ../src/Compositor.hpp:7:
In file included from ../src/defines.hpp:2:
../src/debug/Log.hpp:4:10: fatal error: 'format' file not found
#include <format>
         ^~~~~~~~
1 error generated.
[48/116] Compiling C++ object hyprctl/hyprctl.p/main.cpp.o

-- snip snip --
```

### How to reproduce

By setting the `package` to the value provided in the description.

### Crash reports, logs, images, videos

[Full build log](https://privatebin.net/?00e9d0064669866a#4UcSMkN9LCCJ7eRWoLy3EdGLy5WA1Rt6CzrC7cDqcziu)

**Comment by memchr** [comment]
First, you need to use libc++ instead of libstdc++ with clang, and add `-stdlib=libc++`, `-fexperimental-library` to both compile and linker args.

lld is also recommended over ld.bfd

**Comment by memchr** [comment]
e.g. with meson
```
CC="clang" CXX="clang++" CC_LD=lld CXX_LD=lld meson setup build -Dcpp_args="-stdlib=libc++ -fexperimental-library" -Dcpp_link_args="-stdlib=libc++ -fexperimental-library"
```

**Comment by SrEstegosaurio** [comment]
Thanks for you're fast response.

Then I just need to overwrite a few nix things and I should be okey.

I'll be closing this since it's a me-issue.
