### ISSUE TITLE
Hyprland v0.29.1 parsing windowrulev2 workspace commands incorrectly

### ISSUE THREAD

**Issue by ikubetoomuzik** [hyprwm/Hyprland#3265]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1  flags: (if any)

### Bug or Regression?

Regression

### Description

Hyprland is not parsing windowrulev2's with workspace commands correctly, if the workspace names have spaces in them.

### How to reproduce

Set the following in config file:
`windowrulev2 = workspace name:2. web,class:^(firefox)$`

**Expected Behaviour:**
Firefox will appear on a workspace named *2. web* (This occurs on version *0.29.0* and previous.)

**Actual Behaviour:**
Firefox appears on a workspace called *2.*, stopping parsing at the space.

**Comment by MightyPlaza** [comment]
this is likely due to using a `CVarList` to check if 3rd arg is `silent`
spaces were not taken into account

@vaxerski what would be the solution here?
allow/require escaping named workspace with `'` or similar
or try the best to guess what user wants (ex: `workspace aa silent`)
