### ISSUE TITLE
df51c45 effectively breaks waybar workspace scrolling

### ISSUE THREAD

**Issue by Ghosthree3** [hyprwm/Hyprland#3266]
### Hyprland Version

Hyprland, built from branch HEAD at commit df51c45d7f9e4e280b959f790f7cde6c88b9b451 dirty (keybinds: unify changeworkspace dispatcher (3250)).

### Bug or Regression?

Regression

### Description

With the introduction of commit https://github.com/hyprwm/Hyprland/commit/df51c45d7f9e4e280b959f790f7cde6c88b9b451 it has become impractical to use scrolling to flick through workspaces with waybar as suggested by the wiki here, https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Status-Bars/#scrolling-through-workspaces
This is due to the cursor always being teleported to the center of the screen/new window every time the workspace is changed, requiring you to move the mouse back to the status bar between every scroll/workspace change.
This is not a bug if you consider the above wiki suggestion unsupported.

It is somewhat worth noting that workspace scrolling in this way was already somewhat unusable on multi-monitor setups because if e+1 or e-1 involved changing to a workspace on a different monitor this same issue would already occur.
However I considered this somewhat out of scope for Hyprland as the actual issue here is Waybar's current inability to scroll through workspaces present only on the current status bar (ie. the workspaces on the current monitor only) like it does natively under Sway, instead relying on the hacky e+1 e-1 method.

This change is also quite frustrating when switching workspaces by clicking on them, as the cursor is also teleported center, which makes changing your mind and choosing to click another workspace annoying and is just jarring in general.
Perhaps the 'fix' here is just to have some kind of option to disable mouse warping on workspace swapping? I don't _believe_ this is currently an option? Or better yet, a bool supplied to workspace change commands that optionally disables the cursor warping, as you would only really want this behavior under the above mentioned use cases, and I could see disabling cursor warping entirely when swapping workspaces as also being annoying when you use more traditional keybind methods of doing so.

### How to reproduce

Use https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Status-Bars/#scrolling-through-workspaces on any build after commit https://github.com/hyprwm/Hyprland/commit/df51c45d7f9e4e280b959f790f7cde6c88b9b451.

**Comment by tchofy** [comment]
Seems like `general:no_cursor_warps = false` prevents this behavior, and according to the PR that introduced this change, setting `input:follow_mouse` to anything other than 1 also prevents this, but has it's downsides.

**Comment by Ghosthree3** [comment]
`no_cursor_warps` would fix this yeah (missed this option), though as I brought up has its downsides. When moving window focus with the keyboard you probably do want the mouse to be warped, but you don't want the cursor being warped when using the mouse.
Given that this exists, this may not actually be a regression and instead a fix to previously bugged behavior. In which case, this is actually a feature request.

`follow_mouse`, at least according to the docs, should not be relevant here.
> 1 - Cursor movement will always change focus to the window under the cursor.

This just suggests when moving the mouse over a window it will become focused?
Nothing about any of the options suggest a change in warp behavior, if it is changing, that may be a bug.

**Comment by tchofy** [comment]
Agreed on the downsides, just suggesting a workaround for now.

> 
> `follow_mouse`, at least according to the docs, should not be relevant here.
> 
> > 1 - Cursor movement will always change focus to the window under the cursor.
> 
> This just suggests when moving the mouse over a window it will become focused? Nothing about any of the options suggest a change in warp behavior, if it is changing, that may be a bug.

That was according this comment on the PR that introduced this behavior https://github.com/hyprwm/Hyprland/pull/3250#issuecomment-1713419576

**Comment by memchr** [comment]
```diff
From d49ab7abb9086d8de1bda466d52921e842739a8f Mon Sep 17 00:00:00 2001
From: memchr <memchr@proton.me>
Date: Tue, 12 Sep 2023 07:34:59 +0000
Subject: [PATCH] tmp

---
 src/managers/KeybindManager.cpp | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/src/managers/KeybindManager.cpp b/src/managers/KeybindManager.cpp
index c2a7b6c..a4c1865 100644
--- a/src/managers/KeybindManager.cpp
+++ b/src/managers/KeybindManager.cpp
@@ -871,8 +871,12 @@ void CKeybindManager::changeworkspace(std::string args) {
     } else
         pWorkspaceToChangeTo->rememberPrevWorkspace(PCURRENTWORKSPACE);
 
-    if (auto PLASTWINDOW = pWorkspaceToChangeTo->getLastFocusedWindow(); PLASTWINDOW && *PFOLLOWMOUSE == 1)
-        g_pCompositor->warpCursorTo(PLASTWINDOW->middle());
+    if (auto PLASTWINDOW = pWorkspaceToChangeTo->getLastFocusedWindow(); PLASTWINDOW && *PFOLLOWMOUSE == 1) {
+        Vector2D       surfaceCoords;
+        SLayerSurface* pFoundLayerSurface = nullptr;
+        if (!g_pCompositor->vectorToLayerSurface(g_pInputManager->getMouseCoordsInternal(), &PMONITOR->m_aLayerSurfaceLayers[ZWLR_LAYER_SHELL_V1_LAYER_TOP], &surfaceCoords, &pFoundLayerSurface))
+            g_pCompositor->warpCursorTo(PLASTWINDOW->middle());
+    }
 
     g_pInputManager->simulateMouseMovement();
 }
-- 
2.42.0

```

**Comment by Ghosthree3** [comment]
Recent commits have reverted the mouse warp behavior, however Waybar also becomes unfocused which stops subsequent scroll actions from working until you jiggle the mouse slightly to refocus the bar.

**Comment by gwstorm** [comment]
I've been tracking this issue and and just noticed that it's no longer an issue for me. I'm on v0.34.0-13-g1607e967, but there's been 15 commits within the last 24 hours, sooo... @Ghosthree3 is it fixed for you as well?

**Comment by Ghosthree3** [comment]
Yep, it appears that one of those commits has resolved the issue.
