### ISSUE TITLE
Bug: window trace after |movetoworkspace special`

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#327]
Good day to you!

with recent build, there is a some window trace of size of special workspace after `movetoworkspace special`

![image](https://user-images.githubusercontent.com/52028706/177925631-2325d624-7418-44d9-8809-44b99a5fb40c.png)

Thank you!

**Comment by vaxerski** [comment]
uhh what? Have not seen that. Can you post a video?

**Comment by fedoranvar** [comment]
https://www.veed.io/view/d83bd6b1-9886-4d2e-bfe3-cf797595036d?sharingWidget=true

blur area size of special workspace

**Comment by vaxerski** [comment]
( 91249675dede80d59096313797e3293257cbda86 )

**Comment by fedoranvar** [comment]
yes, bug is fixed

Thank you!
