### ISSUE TITLE
Add a note about keyboard model

### ISSUE THREAD

**Issue by SupremeDeity** [hyprwm/Hyprland#3272]
I was having this issue for many days where random combinations would just not work on my keyboard for some reason even though it worked fine on Windows. The problem was me having a fresh install of Arch with Hyprland and not setting the current keyboard `model`. It would be good to add a small note in the readme or some where in the docs to make it more obvious for any one having keyboard related issues to go ahead and correctly set the `kb_model` variable in the input section of the config.

For me i just counted the total number of keys and used the generic keyboard model `pc104`. A list of all available models can read from from `/usr/share/X11/xkb/rules/base.lst`

**Comment by vaxerski** [comment]
make a wiki mr then :)
