### ISSUE TITLE
File picker in brave looks weird

### ISSUE THREAD

**Issue by alfaroale** [hyprwm/Hyprland#3280]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

There is an empty space between the border and the window
I tried window rules like noborder and noblur, but didn't work well.

### How to reproduce

Opening the file picker in brave(flatpak)
I also tried with the aur package and the same happen.

### Crash reports, logs, images, videos

![20230911_19h49m08s_grim](https://github.com/hyprwm/Hyprland/assets/90881123/2014e8d6-b7a2-4d3e-addb-65d70707432e)

Running hyprctl clients i get:
Window 5638c376d9b0 -> All Files:
	mapped: 1
	hidden: 0
	at: 561,318
	size: 797,444
	workspace: 1 (1)
	floating: 1
	monitor: 1
	class: Xdg-desktop-portal-gtk
	title: All Files
	initialClass: Xdg-desktop-portal-gtk
	initialTitle: All Files
	pid: 2105
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

**Comment by Gliczy** [comment]
This is an issue with apps running through xwayland.

To run Brave in native Wayland mode, you can either set the `ozone-platform-hint` flag to `Wayland` in `brave://flags`, or add `--ozone-platform-hint=auto` in `~/.config/brave-flags.conf`.

**Comment by alfaroale** [comment]
Thank you
