### ISSUE TITLE
Wofi does not display over waybar

### ISSUE THREAD

**Issue by XxRiKxX** [hyprwm/Hyprland#3282]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1  flags: (if any)

### Bug or Regression?

Bug

### Description

I have configured wofi to look like dmenu but I want it to display over waybar which it does not.

### How to reproduce

use wofi and waybar

**Comment by MightyPlaza** [comment]
how is this an hyprland issue?
set the layer you want it to use on wofi's config

**Comment by vaxerski** [comment]
not a hyprland issue. waybar has an exclusive zone, and as per the protocol, it works as an exclusive zone.

You can avoid this by using the `overlay` layer and not `top`

**Comment by XxRiKxX** [comment]
I tried overlay in the wofi config but its still not working

**Comment by MightyPlaza** [comment]
`hyprctl layers` will show you what layer it's on

**Comment by XxRiKxX** [comment]
hyprctl layers did not detect wofi. I have layer=overlay in wofi config file and it still does not allow me to place it over waybar. it shows up below it.

**Comment by MightyPlaza** [comment]
if wofi is open it will appear on hyprctl layers

**Comment by aserowy** [comment]
Heho,

i have the exact same strange behavior. In my case, i am using waybar and rofi.

Is there anything i can do, to enable overlay over the whole screen?

```sh
$  hyprctl layers
Monitor HDMI-A-1:
	Layer level 0 (background):
		Layer 29b5160: xywh: 3440 0 1200 1920, namespace: swww
	Layer level 1 (bottom):
		Layer 21be780: xywh: 3440 0 50 1920, namespace: waybar
	Layer level 2 (top):
	Layer level 3 (overlay):
		Layer 2152e80: xywh: 3490 0 1150 1920, namespace: rofi
```

The effect is shown in the picture and does the exact thing shown in the layers output (rofi starts 50px further right).

![image](https://github.com/hyprwm/Hyprland/assets/8199164/2a193ca5-9922-4c4d-ae6b-0a9e3090cdc8)

My current config for Hypr is here:
https://github.com/aserowy/dots/blob/main/home/modules/hyprland/hyprland.conf

**Comment by XxRiKxX** [comment]
try this once windowrule = fullscreen, rofi

**Comment by aserowy** [comment]
This is not working. I guess because rofi is only shown in layers and is not listed under clients. Thus, windowrules are not working (just my guess).

**Comment by aserowy** [comment]
For anyone who is looking for clarification and (in my case for rofi) a solution:

https://github.com/hyprwm/Hyprland/issues/4162

**Comment by XxRiKxX** [comment]
Yeah I forgot that wofi has a config that changes the window type making it a normal window. Due to that the above rule works. Try to see if there something that make rofi a normal window as well
