### ISSUE TITLE
Glob in `source` does not support full path names

### ISSUE THREAD

**Issue by dantefromhell** [hyprwm/Hyprland#3283]
### Hyprland Version

Built from commit be19773

### Bug or Regression?

Bug

### Description

The `source` globbing implemented in #3276 does not support full path globs like `/home/nixos/.config/overrides/hyprland/*.conf`.

When using this, I get an error message saying
```
source= glob error
```

When replacing the string with `~/.config/overrides/hyprland/*.conf` the configuration works, which doesn't work with the way configuration is managed with `home-manager` under NixOS.

home-manager abstracts the `~/.config` folder location into the `${config.xdg.configHome}` variable, which yields a full path, not a relative path. 

### How to reproduce

see above

**Comment by memchr** [comment]
How does the glob expand in your shell? Because I cannot reproduce that.

```cpp
auto const HOME              = std::string{getenv("HOME")};
    auto const rawpath           = HOME + "/.config/hypr/*.conf";
    auto const configCurrentPath = HOME + "/.config/hypr/hyprlandd.conf";

    std::cout << std::format("HOME: {}\nrawpath: {}\nconfigPath: {}\n", HOME, rawpath, configCurrentPath);
    //
    std::unique_ptr<glob_t, void (*)(glob_t*)> glob_buf{new glob_t, [](glob_t* g) { globfree(g); }};
    memset(glob_buf.get(), 0, sizeof(glob_t));

    if (glob(rawpath.c_str(), GLOB_TILDE, nullptr, glob_buf.get()) != 0) {
        std::cout << "glob error"
                  << "\n";
        return 1;
    }

    for (size_t i = 0; i < glob_buf->gl_pathc; i++) {
        auto value = absolutePath(glob_buf->gl_pathv[i], configCurrentPath);
        std::cout << value << '\n';
    }
```

**Comment by dantefromhell** [comment]
I can't reproduce it anymore either, accounting this to some transitory state issues.

**Comment by memchr** [comment]
Ja, your CPU has probably suffered a transient ischaemic attack.
