### ISSUE TITLE
group_focus_removed_window doesn't work

### ISSUE THREAD

**Issue by nathanchere** [hyprwm/Hyprland#3287]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

When adding group_focus_removed_window to config, it raises error "No such field".

### How to reproduce

Running hyprland 0.29.1-1

An example of the misc section from my config:

```
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

    group_insert_after_current	= false
    group_focus_removed_window = false
    # group_focus_removed_window = true
    groupbar_scrolling = true
    render_titles_in_groupbar = true
    groupbar_titles_font_size = 12
    groupbar_gradients = true
    groupbar_text_color = 0xff000000
}
```

### Crash reports, logs, images, videos

>  Error setting vaue <false> for field <misc:group_focus_removed_window>: No such field.
> Hyprland may not work correctly.

**Comment by memchr** [comment]
Update your program, #3006 was merged only 3 days ago.
https://github.com/hyprwm/Hyprland/commit/96d555e8e794627bfc561e294e148ab8a9961fcc is from a week ago.
