### ISSUE TITLE
Changing mfact using keyword doesn't update until layout change

### ISSUE THREAD

**Issue by cjber** [hyprwm/Hyprland#3292]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

I have a script that I want to use to toggle the `mfact` of the master window in the master layout. Unless I include the lines to switch the layout type, the master window does not update. `getoption` does however return the correct value. Here is the current script:

```
#!/bin/sh

if [ $(hyprctl getoption master:mfact -j | jq -r ".float") == "0.330000" ]
then
    hyprctl keyword master:mfact 0.5
    hyprctl keyword general:layout "dwindle"
    hyprctl keyword general:layout "master"
else
    hyprctl keyword master:mfact 0.33
    hyprctl keyword general:layout "dwindle"
    hyprctl keyword general:layout "master"
fi
```

Ideally the `hyprctl keyword general:layout ...` lines shouldn't be necessary.

### How to reproduce

`hyprctl keyword master:mfact 0.5`

nothing happens.

**Comment by thejch** [comment]
Adding a dispatcher would be best here. Live rendering doesn't use the config keyword because the master could have been resized so it's using that actual value instead. The keyword is only used when the window is created.
