### ISSUE TITLE
Customize border rounding on tooltips separately from windows

### ISSUE THREAD

**Issue by Lassebq** [hyprwm/Hyprland#3296]
### Description

At the moment, decoration:rounding affects both tooltip's and window's borders. However, there are cases where tooltips are intended to be rectangle-shaped, with borders being drawn inside of tooltip area.
I think there should be a way to set border rounding on tooltips separately. Even though tooltips aren't windows, I think a windowrule-like approach would suit them.

**Comment by Lassebq** [comment]
Okay, I may also need to clarify that it affects vscode's tooltips, GTK ones seem to be unaffected

**Comment by Lassebq** [comment]
It's running wayland. Reopen the issue.

**Comment by Lassebq** [comment]
Here are the screenshots demonstrating the issue. You either get all windows with rounded borders or none
![image](https://cdn.discordapp.com/attachments/967398886530515067/1151597397894508605/image.png)
![image](https://cdn.discordapp.com/attachments/967398886530515067/1151597398154543104/image.png)

**Comment by vaxerski** [comment]
I did break it then, but it's your fault

**Comment by vaxerski** [comment]
can you `git bisect` this

**Comment by Lassebq** [comment]
I'm sure this is a really old bug, pretty sure it was happening all the way back during v0.26

**Comment by Lassebq** [comment]
I'll try bisecting though

**Comment by vaxerski** [comment]
nah no way, I just noticed this.

**Comment by Lassebq** [comment]
Earliest release I could compile is v0.29, still happens there. v0.28 wont build

**Comment by Lassebq** [comment]
Nvm, something was wrong on my side. v0.28 builds, but the issue is still there

**Comment by Lassebq** [comment]
I swear, it happened in v0.26 too. I may not be able to test it now, but going that far back is impossible with git bisect, as I cannot build past v0.27.

**Comment by tchofy** [comment]
You could [try the binary releases](https://github.com/hyprwm/Hyprland/releases), it wouldn't be able to point to a specific commit, but can give you a range.

**Comment by vaxerski** [comment]
fixe d 3b1e09e5a18bd1cf137f8f50394aa0c1eaac1e30
