### ISSUE TITLE
Scrollwheel binds are ignored when repeated too quickly

### ISSUE THREAD

**Issue by Lassebq** [hyprwm/Hyprland#3297]
### Hyprland Version

Hyprland, built from branch HEAD at commit 5a6d0e9963eaca457a1f91c5ab4c3142c145b646 dirty (refactor: fix missed middle() call in CKeybindManager). Tag: v0.29.1-53-g5a6d0e99  flags: (if any)

### Bug or Regression?

Bug

### Description

```
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
```
I have these two binds in my config, moving scrollwheel up/down once works always, but as soon as you start scrolling too fast, it ignores the bind and starts scrolling application's view.

### How to reproduce

Add binds which bind mouse_up or down, and start scrolling with modifier held. Scrollwheel bind will be ignored if you move scrollwheel by more than one scroll event.

**Comment by thejch** [comment]
check your `binds:scroll_event_delay` setting, by default theres a delay. if you want it to be immediate you can set it to 0
