### ISSUE TITLE
Focus mouse on window in separate monitor not working

### ISSUE THREAD

**Issue by CreativeKittens** [hyprwm/Hyprland#3299]
### Hyprland Version

v0.29.1-68-g84f8f4d7

### Bug or Regression?

Bug

### Description

When changing workspace in separate monitor the window in that separate monitor not being focused, instead the focus keep in window from previous monitor

i have `follow_mouse = 1`

it work on the previous version, i don't know which version that break it

### How to reproduce

1. Have multiple monitor
2. Set keybind that move between workspace
3. open 2 workspace in separate monitor also open a random windows
4. ie. open workspace 1 in your first monitor and focus to the window,
5. then move to workspace 2 that in your secondary monitor, try to interact with the windows that opened in that workspace

**Comment by Ghosthree3** [comment]
Sounds related to what I've just written here, https://github.com/hyprwm/Hyprland/issues/3266#issuecomment-1718512342

**Comment by CreativeKittens** [comment]
solve per hyprland version

Hyprland, built from branch main at commit 60f10e60375612a378c57556bbef9a9c62cfc1b3 dirty (hyprctl: print monitor IDs as int64).
Tag: v0.29.1-90-g60f10e60
