### ISSUE TITLE
Cycle previos option

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#330]
I can fund a cycle next option: https://github.com/hyprwm/Hyprland/wiki/Advanced-config#cyclenext but no cycle previous option?

**Comment by vaxerski** [comment]
precisely. I can add one though.

**Comment by godalming123** [comment]
Also there's no error message for incorrect arguments as long as you have a real dispatcher

**Comment by vaxerski** [comment]
yes. The config manager cannot check your params.

**Comment by vaxerski** [comment]
added in c44cafda9723e268dcedd71eb2f9b918429bbd0f
