### ISSUE TITLE
cursor changes its position while changing workspace

### ISSUE THREAD

**Issue by fahimscirex** [hyprwm/Hyprland#3303]
### Hyprland Version

v0.29.1-61-gbe19773a

### Bug or Regression?

Bug

### Description

When I change workspace cursor changes it's position to the center of the active windows. Happens through keybinding and also through the waybar module.

### How to reproduce

Change workspace by clicking on waybar module or just by keybindings.

**Comment by Ghosthree3** [comment]
Duplicate, https://github.com/hyprwm/Hyprland/issues/3266
