### ISSUE TITLE
Dwindle layout: movewindow in special workspace yeets the window out of special workspace

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#3305]
### Hyprland Version

Hyprland, built from branch main at commit 84f8f4d77ddf4b6c772459584234e1f8f9d5f2ce dirty (keybinds: warp cursor to correct window in moveWindowOutOfGroup (3290)). Tag: v0.29.1-68-g84f8f4d7

### Bug or Regression?

Bug

### Description

Dwindle layout.
In special workspace, if you try to move windows around using movewindow, it will move your window out of special workspace and into the main workspace
Expected bahavior: window should stay in special workspace

### How to reproduce

1. Set layout to dwindle
2. Send a few windows into special workspace
3. Open special workspace
4. Use movewindow to move windows around

**Comment by vaxerski** [comment]
2536630049f3847c0c44340f4706f3664c8b52fb

https://github.com/hyprwm/Hyprland/assets/43317083/3bda28d4-7659-4f5f-bafe-578dc7fc952a
