### ISSUE TITLE
Workspace dissapear when unplugging monitor

### ISSUE THREAD

**Issue by cvanelteren** [hyprwm/Hyprland#3306]
### Hyprland Version

0.29.1

### Bug or Regression?

Bug

### Description

My workspaces are divided over my monitors as

```
workspace = eDP-1, 1
workspace = eDP-1, 3
workspace = eDP-1, 5
workspace = eDP-1, 7

workspace = HDMI-A-1, 2
workspace = HDMI-A-1, 4
workspace = HDMI-A-1, 6
```

When I unplug my monitors the workspaces (and their open apps) disappear including the special workspace if it is opened there.

### How to reproduce

- Set config
- open apps on workspaces
- disconnect
- Profit(?)

**Comment by vaxerski** [comment]
do the apps crash or are they just invisible? if invisible, it's a minor bug, just switch the workspace. if crash, it's fixed in git

**Comment by cvanelteren** [comment]
The apps are still active (I believe) but not visible anymore. My special workspace becomes inaccessible. Switching workspaces does not bring them back.

**Comment by cvanelteren** [comment]
It is not fixed in the build listed fyi @vaxerski @rurigk
