### ISSUE TITLE
vscode (electron app) crash when opening new window

### ISSUE THREAD

**Issue by Cosss7** [hyprwm/Hyprland#3309]
### Hyprland Version

f6473aa3adacb5fbd63fda7c39cc2e9fd9540e6a (latest main branch)

### Bug or Regression?

Bug

### Description

I tried f6473aa3adacb5fbd63fda7c39cc2e9fd9540e6a (latest main branch) and v0.28.0, both have the issue.
Electron app like Obsidian and vscode will crash when opening new window (or new it instance from launcher or terminal).
Sometimes it can open two or three new window, but most to four they finally crash.
I also tried sway, it's same. So I think the issue may be wlroots or electron?

### How to reproduce

code  --ozone-platform=wayland --disable-gpu --disable-extension
and fast repeatlly open new window of vscode

### Crash reports, logs, images, videos

I got log by running
Hyprland > log.txt 2>&1 

logs will upload later

**Comment by vaxerski** [comment]
I believe thats an electron issue, does it work on sway-git?

**Comment by memchr** [comment]
Probably it is, vscode has been naughty with wayland since 1.7x, see 
- microsoft/vscode#184124
- microsoft/vscode#181533 (closed, but I don't think it's been resolved)

**Comment by Cosss7** [comment]
Yep, I think it's the issue.
I will follow https://github.com/microsoft/vscode/issues/184124 
Thanks, just closed this.

**Comment by Cosss7** [comment]
Yep, I think it's the issue.
I will follow https://github.com/microsoft/vscode/issues/184124
Thanks, just closed this.
