### ISSUE TITLE
SUPER suddenly not binding

### ISSUE THREAD

**Issue by Dungeonseeker** [hyprwm/Hyprland#3310]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty ().

### Bug or Regression?

Bug

### Description

Seemingly entirely randomly, I can no longer bind SUPER as my mod key.

Everything has been working totally fine until this morning, I've been using Hyprland for over a month with essentially the same config (only minor adjustments and mostly to waybar and CSS) and nothing changed from shutting down last night to booting up today.

What's really odd is that WEV shows that when I press the SUPER key its instantly released and holding it does nothing.

[hyprland.txt](https://github.com/hyprwm/Hyprland/files/12610571/hyprland.txt)
^mod is currently set to ALT because SUPER doesn't work.

### How to reproduce

Unsure

### Crash reports, logs, images, videos

N/A

**Comment by Jaques22** [comment]
My super key is working fine on latest commit. It kinda sounds like your super key is broken. Have you tried another keyboard?

**Comment by Dungeonseeker** [comment]
> My super key is working fine on latest commit. It kinda sounds like your super key is broken. Have you tried another keyboard?

Yes, problem exists on an external USB keyboard (this is a laptop).

As I said, nothing changed with Hyprland at all, the only change that might have affected it is Arch updating the Kernel from 6.5.2 to 6.5.3 which happened when I booted my machine up yesterday.

Also yeah, ^^^ others have the exact same issue as me so it has to be a bug somewhere. I'll try to roll back to 6.5.2 later on today (or maybe swap over to LTS for a test).

**Comment by Dungeonseeker** [comment]
OK, I found the issue and its neither Hyprland or a kernel issue, turns out my Laptop has a super key toggle function.

The fix (for me at least) was to press FN+SUPER once and now SUPER is working as expected.

Might be a good thing to add to the FAQ, maybe?

**Comment by martinpiz097** [comment]
> OK, I found the issue and its neither Hyprland or a kernel issue, turns out my Laptop has a super key toggle function.
> 
> The fix (for me at least) was to press FN+SUPER once and now SUPER is working as expected.
> 
> Might be a good thing to add to the FAQ, maybe?

This solution works for me! Thanks

**Comment by ProximusLoyd** [comment]
That didn't worked for me
