### ISSUE TITLE
0.29.1 breaks Waybar workspace names

### ISSUE THREAD

**Issue by opensourcecheemsburgers** [hyprwm/Hyprland#3312]
### Hyprland Version

0.29.1

### Bug or Regression?

Bug

### Description

After updating from to 0.29.1, my Waybar workspace names have disappeared.

Downgrading back to 0.28.0 fixes the issue and also another issue with black screens after inactivity.

Using `waybar-hyprland` nor `waybar-hyprland-git`, instead of `waybar`, fixes the issue.

### How to reproduce

Use my waybar config on `0.28.0` and then upgrade to `0.29.1`:

Waybar config:
```
{
    "height": 32,
    "layer": "top", 
    "margin-top": 6,
    "margin-left": 10,
    "margin-bottom": 0,
    "margin-right": 10,
    "spacing": 5,
    "modules-left": ["custom/launcher", "cpu", "memory", "wlr/workspaces"],
    "modules-center": ["hyprland/window"],
    "modules-right": ["tray", "pulseaudio", "network"],
    "wlr/workspaces": {
      "format": "{}",
      "on-click": "activate",
      "format-icons": {
        "1": "",
        "2": "",
        "3": "",
        "4": "",
        "5": "",
        "urgent": "",
        "active": "",
        "default": ""
      }
    },
    "hyprland/window": {
        "format": "{}"
    },    
    "tray": {
        "spacing": 10
    },
    "clock": {
        "format": "<span color='#bf616a'> </span>{:%a %b %d}",
        "format-alt": "<span color='#bf616a'> </span>{:%I:%M %p}",
        "tooltip-format": "<big>{:%B %Y}</big>\n<tt><small>{calendar}</small></tt>",
    },

    "cpu": {
      "interval": 10,
      "format": " {}%",
      "max-length": 10,
      "on-click": "",
    },
    "memory": {
        "interval": 30,
        "format": " {}%",
        "format-alt":" {used:0.1f}G",
        "max-length": 10,
    },
    "network": {
        "format-wifi": "直 {signalStrength}%",
        "format-ethernet": " wired",
        "format-disconnected": "睊",
        "on-click": "bash ~/.config/waybar/scripts/rofi-wifi-menu.sh",
        "format-disconnected": "Disconnected  ",
    },

    "pulseaudio": {
        "format": "{icon} {volume}%",
        "format-bluetooth": "  {volume}%",
        "format-bluetooth-muted": " ",
        "format-muted": "婢",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        },
        "on-click": "pavucontrol"
    },
    "bluetooth": {
        "on-click": "~/.config/waybar/scripts/rofi-bluetooth &",
        "format": " {status}",
    },
    "custom/launcher": {
        "format": " <span color='#6a92d7'></span>",
        "on-click": "fuzzel",
    },
}
```

**Comment by memchr** [comment]
replace with `hyprland/workspaces`

this change has been breeding duplicates like rabbits.

#3238 #3171 #3173 #3251

**Comment by opensourcecheemsburgers** [comment]
My bad, my google searches didn't bring up any of the aforementioned duplicates.

I have made the change and logged out of my hyprland session. However, it still does not show the workspaces. 

I have also uninstalled `waybar-hyprland` and reinstalled `waybar` which also did not fix the problem.

**Comment by memchr** [comment]
Please upload your current waybar config.

**Comment by opensourcecheemsburgers** [comment]
Apologies, I forgot to change the modules to `hyprland/workspaces` as well. 

The workspaces have appeared again but they are showing as negative numbers instead of their respective names?

**Comment by memchr** [comment]
why not read [waybar wiki](https://github.com/Alexays/Waybar/wiki/Module:-Hyprland)?

---

Change `"format": "{}"` to `"format": "{icon}"`

**Comment by opensourcecheemsburgers** [comment]
> why not read [waybar wiki](https://github.com/Alexays/Waybar/wiki/Module:-Hyprland)?

I'm an idiot sandwich.

A quick look at the wiki fixed my issue. I just needed `"format": "{name}"`.
