### ISSUE TITLE
Window swallowing doesn't work in lf.

### ISSUE THREAD

**Issue by Mxstyz** [hyprwm/Hyprland#3314]
### Hyprland Version

v0.29.1-68-g84f8f4d7

### Bug or Regression?

Bug

### Description

I configured Hyprland so programs that the foot terminal open will swallow programs but whenever i use lf/ranger/nnn it makes a new window. 

### How to reproduce

open a foot window, use a terminal file manager like lf and open a video.

**Comment by Mxstyz** [comment]
Sorry i am so stupid fixed my issue

**Comment by arsham** [comment]
@Mxstyz can you explain how you fixed your issue please?

**Comment by shadowelite-sec** [comment]
> Sorry i am so stupid fixed my issue

how ?

**Comment by Mxstyz** [comment]
Sorry I done this a while ago. I think this was a problem how I configured
lf.
