### ISSUE TITLE
SUPER KEY not working 

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#3318]
### Hyprland Version

Hyprland, built from branch main at commit f8008e4b3beb4aae2365973879a46fe0f15c79b4 dirty (Nix CI: use DetSys' install & cache actions). Tag: v0.29.1-75-gf8008e4b

### Bug or Regression?

Bug

### Description

Hyprland Super key stopped working randomly. I attempted to reboot to resolve the issue, but it still persists. The only way I was able to fix it was by booting into Windows and then back into Linux. Unfortunately, I have since completely removed Windows, and now I am unable to use Hyprland. I also tried Gnome, but the same issue occurs.

### How to reproduce

No

### Crash reports, logs, images, videos

Super key before the issue 

![IMG_20230915_084129_476](https://github.com/hyprwm/Hyprland/assets/54718375/91afe772-dd25-4fba-9ed4-580832476814)

After the issue

![IMG_20230915_084134_970](https://github.com/hyprwm/Hyprland/assets/54718375/db550bc5-4ab2-492f-a565-679b29e71608)

**Comment by memchr** [comment]
Duplicate of #3310 ?

**Comment by shadowelite-sec** [comment]
I also tried all these mod
` SHIFT CAPS CTRL/CONTROL ALT MOD2 MOD3 SUPER/WIN/LOGO/MOD4 MOD5 `

`$mainMod = MOD4`

Still the same issue

**Comment by memchr** [comment]
Cannot reproduce, what is your full configuration?

**Comment by shadowelite-sec** [comment]
> Cannot reproduce, what is your full configuration?

https://github.com/shadowelite-sec/hypr/blob/main/hypr/.config/hypr/keybind.conf

https://github.com/shadowelite-sec/hypr/tree/main/hypr/.config/hypr

**Comment by memchr** [comment]
Maybe this will give you some inspiration?

from https://github.com/hyprwm/Hyprland/issues/3310#issuecomment-1720882586
> OK, I found the issue and its neither Hyprland or a kernel issue, turns out my Laptop has a 
> super key toggle function.
>
> The fix (for me at least) was to press FN+SUPER once and now SUPER is working as expected.
>
> Might be a good thing to add to the FAQ, maybe?

**Comment by shadowelite-sec** [comment]
> Maybe this will give you some inspiration?
> 
> from [#3310 (comment)](https://github.com/hyprwm/Hyprland/issues/3310#issuecomment-1720882586)
> 
> > OK, I found the issue and its neither Hyprland or a kernel issue, turns out my Laptop has a
> > super key toggle function.
> > The fix (for me at least) was to press FN+SUPER once and now SUPER is working as expected.
> > Might be a good thing to add to the FAQ, maybe?

Hmm, this is weird. My issue just fixed itself by connecting an external keyboard. After pressing the Super key on the external keyboard, my laptop's Super key also started working.

I don't know when this problem will occur again.

**Comment by shadowelite-sec** [comment]
> Maybe this will give you some inspiration?
> 
> from [#3310 (comment)](https://github.com/hyprwm/Hyprland/issues/3310#issuecomment-1720882586)
> 
> > OK, I found the issue and its neither Hyprland or a kernel issue, turns out my Laptop has a
> > super key toggle function.
> > The fix (for me at least) was to press FN+SUPER once and now SUPER is working as expected.
> > Might be a good thing to add to the FAQ, maybe?

yes , its working . Thanks :)

**Comment by Saravana707** [comment]
> Duplicate of [#3310](https://github.com/hyprwm/Hyprland/issues/3310) ?

i downloaded arch Hyprland and now my super key is not working not even in windows 11 what should i do?

**Comment by Saravana707** [comment]
i downloaded arch Hyprland and now my super key is not working not even in windows 11 what should i do?

**Comment by memchr** [comment]
Does your keyboard have a <kbd>fn</kbd> key? If so, press <kbd>fn</kbd>+<kbd>super</kbd>

---

> i downloaded arch Hyprland and now my super key is not working not even in windows 11 what should i do?

**Comment by TAnomaly** [comment]
Same bug, i cannot fix.I try Super+fn method but doesnt work.How can i fix the bugs ?

**Comment by shadowe1ite** [comment]
Open a discussion. This issue is closed, only previous participants will be notified.

> Same bug, i cannot fix.I try Super+fn method but doesnt work.How can i fix the bugs ?

**Comment by Saravana707** [comment]
I found what it was fn+f12 locks meta/super key that was the issue.

**Comment by Pygrammerik** [comment]
Same. And any of fixes not working  i have a laptop and i connected external keyboard and on laptop not working and on a external keyboard not working. Any other fix?

**Comment by CapsAdmin** [comment]
> I found what it was fn+f12 locks meta/super key that was the issue.

That was the problem for me as well. I have a "hyperx alloy origins" keyboard which disables the super key when "game mode" is enabled at a hardware level. So pressing FN + F12 fixed the problem for me.

**Comment by qapquiz** [comment]
I also have the same problem and connect to the external to press the super once fixed my issue! ♥️ Not sure why though
