### ISSUE TITLE
Feature: get current kbd_layout

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#332]
Good day to you!

is there a way to get current keyboard layout? (`us`, `ru`, etc)

maybe adding attribute to `hyprctl devices`?

thank you!

**Comment by vaxerski** [comment]
added in 92e17f29256af4db05ebd17b9f2d013ee3ca37ab

**Comment by fedoranvar** [comment]
Thank you!

**Comment by fedoranvar** [comment]
is it possible to add current active layout atrribute ?

**Comment by vaxerski** [comment]
?

**Comment by fedoranvar** [comment]
current active layout - so if i printing english letters, so my CAL is `us`

if i'm printing cyrllic letters, then it will show `ru`

**Comment by vaxerski** [comment]
its already there

**Comment by vaxerski** [comment]
```
rules: r "", m "", l "pl", v "", o ""
```
`l` is layout

**Comment by fedoranvar** [comment]
not exactly, it shows declared layouts, but now currently active
![image](https://user-images.githubusercontent.com/52028706/178149598-008b7257-3a45-46be-977f-4241837f471d.png)

**Comment by vaxerski** [comment]
I am unsure whether I am allowed to even get that then. I'll see.

**Comment by vaxerski** [comment]
added in ef7ee2fd0f64a1a0a0088b90d3cbaeb6b3436c32

it's not like `pl`, it prints the full name (e.g. `Polish`) but it will work. :-)

**Comment by fedoranvar** [comment]
have tried wirelles (2.4 GHz) and usual usb-keyboards 
didn't worked for me: it shows `English (US)` for all devices and that's all. t

![image](https://user-images.githubusercontent.com/52028706/179443109-150cc36e-1090-4b7c-a634-a84f6729e522.png)

am i doing something wrong?

**Comment by eneshecan** [comment]
Always shows `English (US)` for me too...

**Comment by AdsonCicilioti** [comment]
OMG!! Very verbose...
