### ISSUE TITLE
hide bar and show it after pressed modifier

### ISSUE THREAD

**Issue by roland-5** [hyprwm/Hyprland#3320]
### Description

The functionality I miss is the ability to hide the bar and show it only when pressing the appropriate button. `Sway` has this feature natively, without the need to kill the bar. I often have a few windows open and quickly check the CPU, RAM usage or even the time.

In `sway` I have this:
```
bar {
    swaybar_command waybar
    mode hide
    modifier Mod4
}
```

and in `waybar` I have this:
```
{
    "bar_id": "bar-0",
    "ipc": true,
    "position": "top"
}
```

**Comment by vaxerski** [comment]
binds exist

waybar will toggle hide/unhide when met with SIGUSR1

`pkill -SIGUSR1 waybar`

**Comment by tchofy** [comment]
And the hold button toggle can be done with
```
bind = SUPER, W, exec, pkill -SIGUSR1 waybar
bindr = SUPER, W, exec, pkill -SIGUSR1 waybar
```

**Comment by roland-5** [comment]
@vaxerski Won't this command kill/stop waybar as a process? What about desktop notifications when an application requires attention/give notification?
Out of curiosity: wouldn't you want native status bar support like Sway has because there is no native status bar for Hyprland (like there is swaybar for Sway), or would you rather Hyprland not deal with the status bar at all?

@tchofy I don't want the bar to disappear and reappear when pressing separate shortcuts. In your example, one shortcut would activate it and the other would kill/stop it. What I want is for it to appear only when the button is pressed and disappear when the button is released. Since I have it set in Sway as mod4, if I press SUPER it appears and disappears when I release the button. I have all the shortcuts set together with mod4, so when I run an application, e.g. the terminal mod4+enter the status bar shows up and then my terminal, I want spawn file manager so mod4+e also shows the status bar when I press this combination and then my file manager or when I move windows to another desktop etc.

**Comment by vaxerski** [comment]
```
bindt = , Super_L, exec, pkill -SIGUSR1 waybar
bindrt = SUPER, Super_L, exec, pkill -SIGUSR1 waybar
```
will do exactly what you want

> Out of curiosity: wouldn't you want native status bar support like Sway has because there is no native status bar for Hyprland (like there is swaybar for Sway), or would you rather Hyprland not deal with the status bar at all?

Hyprland doesn't provide its own bar and I'd rather it stayed that way

**Comment by tchofy** [comment]
> @tchofy I don't want the bar to disappear and reappear when pressing separate shortcuts. In your example, one shortcut would activate it and the other would kill/stop it. What I want is for it to appear only when the button is pressed and disappear when the button is released. Since I have it set in Sway as mod4, if I press SUPER it appears and disappears when I release the button. I have all the shortcuts set together with mod4, so when I run an application, e.g. the terminal mod4+enter the status bar shows up and then my terminal, I want spawn file manager so mod4+e also shows the status bar when I press this combination and then my file manager or when I move windows to another desktop etc.

Think of it like a toggle switch, if the bar is currently visible, then the behavior will be like you described, but if you do a `pkill -SIGUSR1 waybar` first (either in your hyprland config file or manually on  terminal), the behavior will be like you want.

As for the confusion about pkill, by default it passes a SIGTERM to a given process, here we're telling it to send a SIGUSR1 instead, and waybar was programmed to hide/unhide itself upon receiving that signal, and SIGUSR2 to reload it's style.css.

From trying to do it myself, the behavior is a big buggy sometimes, maybe waybar doesn't like the quick hide/unhide calls, it'll need some testing.

**Comment by roland-5** [comment]
Thank you both for answers.

**Comment by louregni** [comment]
> ```
> bindt = , Super_L, exec, pkill -SIGUSR1 waybar
> bindrt = SUPER, Super_L, exec, pkill -SIGUSR1 waybar
> ```
> 
> will do exactly what you want
> 
> > Out of curiosity: wouldn't you want native status bar support like Sway has because there is no native status bar for Hyprland (like there is swaybar for Sway), or would you rather Hyprland not deal with the status bar at all?
> 
> Hyprland doesn't provide its own bar and I'd rather it stayed that way

Is it possible that the release is never sent when hyprlock is called with SUPER shortcut? I see that the bar get inverted (always displayed) when I lock screen with a SUPER binding.

**Comment by an4s911** [comment]
> And the hold button toggle can be done with
> 
> ```
> bind = SUPER, W, exec, pkill -SIGUSR1 waybar
> bindr = SUPER, W, exec, pkill -SIGUSR1 waybar
> ```

Hi, i came across this issue when I was looking for a way to hide waybar. And when I wrote exactly what you've given here (ie I put both those above keybindings, not just one), something interesting happened, idk if that was intentional in your comment, but what happened is that waybar was hidden, and only visible while holding on to Super + W, I kinda liked it, and this was because I hid it first by running the same command on the terminal. 

But I feel like making the same keybinding twice is kinda weird, so is there a better way to do it. Also how do i make it such that it stays hidden when hyprland loads the first time on login.

Or maybe, all windows should be above waybar, and only visible on a keybinding, but if no windows are open then waybar should be visible. Is this even possible? 

i tried adding `pkill -SIGUSR1 waybar` to the `exec-once` of hyprland config, but that didn't work.

**Comment by vslutov** [comment]
For users, who is looking new lua syntax:

`~/.config/hypr/hyperland.lua`:
```lua
hl.bind("SUPER_L", hl.dsp.exec_raw("killall -SIGUSR1 waybar"), {transparent = true})
hl.bind("SUPER + SUPER_L", hl.dsp.exec_raw("killall -SIGUSR2 waybar"), {transparent = true, release = true})

-- optional: if your keyboardoard has right Logo button
hl.bind("SUPER_R", hl.dsp.exec_raw("killall -SIGUSR1 waybar"), {transparent = true})
hl.bind("SUPER + SUPER_R", hl.dsp.exec_raw("killall -SIGUSR2 waybar"), {transparent = true, release = true})
```


and  `~/.config/waybar/config.jsonc`:
```jsonc
{
    "on-sigusr1": "show",
    "on-sigusr2": "hide",
    "start_hidden": true,
    // optional: don't allocate space for waybar, draw on top of other windows
    "layer": "top",
    "exclusive": false,
    ...
```

**Comment by feelamee** [comment]
there is also useful option [long_press](https://wiki.hypr.land/Configuring/Basics/Binds/#bind-flags) in bind flags. This allow to not flicker bar when pressing other hotkeys (SUPER+Return, and so on).

Unfortunately `release` don't bother about `long_press`, so fast click to SUPER will still execute release binding.
