### ISSUE TITLE
Startup crash on nvidia

### ISSUE THREAD

**Issue by Tofixrs** [hyprwm/Hyprland#3322]
### Hyprland Version

56adec7c1a49c079f320ba3c0c5ae3948946a9e5

### Bug or Regression?

Bug

### Description

Title

### How to reproduce

Launch hyprland

### Crash reports, logs, images, videos

[hyprlandCrashReport166732.txt](https://github.com/hyprwm/Hyprland/files/12621497/hyprlandCrashReport166732.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12621625/hyprland.log)

**Comment by vaxerski** [comment]
nvidia issue
