### ISSUE TITLE
vscode/vscodium crash on hyprland

### ISSUE THREAD

**Issue by pshirshov** [hyprwm/Hyprland#3324]
### Hyprland Version

Hyprland, built from branch  at commit f8008e4b3beb4aae2365973879a46fe0f15c79b4

### Bug or Regression?

Bug

### Description

vscode/vscodium frequently crash on mouse clicks (not always, but very frequently). The relevant part of the stack is:

```
                #0  0x000056347dbcd0e4 n/a (codium + 0x6e590e4)
                #1  0x000056347daa7a0e n/a (codium + 0x6d33a0e)
                #2  0x000056347dacdc13 n/a (codium + 0x6d59c13)
                #3  0x000056347dacd897 n/a (codium + 0x6d59897)
                #4  0x000056347dacd740 n/a (codium + 0x6d59740)
                #5  0x000056347dacd8ba n/a (codium + 0x6d598ba)
                #6  0x000056347dacd740 n/a (codium + 0x6d59740)
                #7  0x000056347dacd8ba n/a (codium + 0x6d598ba)
                #8  0x000056347dacd740 n/a (codium + 0x6d59740)
                #9  0x000056347dab2e1f n/a (codium + 0x6d3ee1f)
                #10 0x000056347d3564b6 n/a (codium + 0x65e24b6)
                #11 0x000056347dbbe61b n/a (codium + 0x6e4a61b)
                #12 0x00005634800e5436 n/a (codium + 0x9371436)
                #13 0x000056347d359cc9 n/a (codium + 0x65e5cc9)
                #14 0x0000563479b0f538 n/a (codium + 0x2d9b538)
                #15 0x0000563479b0f305 n/a (codium + 0x2d9b305)
                #16 0x000056347d3422eb n/a (codium + 0x65ce2eb)
                #17 0x0000563479aef4a4 n/a (codium + 0x2d7b4a4)
                #18 0x0000563479aef1d2 n/a (codium + 0x2d7b1d2)
                #19 0x0000563479b0126f n/a (codium + 0x2d8d26f)
                #20 0x0000563478fa8025 n/a (codium + 0x2234025)
                #21 0x0000563478fa7579 n/a (codium + 0x2233579)
                #22 0x000056347d3e4327 n/a (codium + 0x6670327)
                #23 0x000056347d3e281a n/a (codium + 0x666e81a)
                #24 0x000056347d3e228d wl_display_dispatch_queue_pending (codium + 0x666e28d)
                #25 0x0000563479b338e6 n/a (codium + 0x2dbf8e6)
                #26 0x0000563479b3420d n/a (codium + 0x2dc020d)
                #27 0x00007f364daf2ead g_main_context_dispatch (libglib-2.0.so.0 + 0x5dead)
                #28 0x00007f364daf3158 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x5e158)
                #29 0x00007f364daf31ec g_main_context_iteration (libglib-2.0.so.0 + 0x5e1ec)
                #30 0x000056347c441eec n/a (codium + 0x56cdeec)
                #31 0x000056347c3e1b2c n/a (codium + 0x566db2c)
                #32 0x000056347c3a3b81 n/a (codium + 0x562fb81)
                #33 0x000056347b4f2c7f n/a (codium + 0x477ec7f)
                #34 0x000056347b4f4a62 n/a (codium + 0x4780a62)
                #35 0x000056347b4f02a9 n/a (codium + 0x477c2a9)
                #36 0x00005634792cb374 n/a (codium + 0x2557374)
                #37 0x00005634792ccbfe n/a (codium + 0x2558bfe)
                #38 0x00005634792cca18 n/a (codium + 0x2558a18)
                #39 0x00005634792ca355 n/a (codium + 0x2556355)
                #40 0x00005634792ca445 n/a (codium + 0x2556445)
                #41 0x0000563479007eed n/a (codium + 0x2293eed)
                #42 0x00007f364c59eace __libc_start_call_main (libc.so.6 + 0x23ace)
                #43 0x00007f364c59eb89 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x23b89)
                #44 0x0000563478c6602a _start (codium + 0x1ef202a)
```

### How to reproduce

Run vscode or vscodium, click into the window.

### Relevant

1. This issue looks like https://github.com/microsoft/vscode/issues/184124, though it only reproduces on Hyprland, everything is fine under Plasma and Sway

**Comment by vaxerski** [comment]
without debug symbols from codium this is a useless report as I can't do shit.

Besides, it's more of a codium issue to me.

**Comment by gmontanola** [comment]
FYI @pshirshov - [this solution](https://github.com/microsoft/vscode/issues/184124#issuecomment-1717650430) fixed it for me.

**Comment by pshirshov** [comment]
It doesn't actually fix things, it just makes them better. I have these settings and I'm able to open the first Code window in ~50% cases, but when I open a second one it would crash 100%.

**Comment by NicolaiVdS** [comment]
> It doesn't actually fix things, it just makes them better. I have these settings and I'm able to open the first Code window in ~50% cases, but when I open a second one it would crash 100%.

seems like setting `"window.titleBarStyle": "custom"` in the settings.json file to be fixing it for me

**Comment by romanstingler** [comment]
this also fixes it for me 

> > It doesn't actually fix things, it just makes them better. I have these settings and I'm able to open the first Code window in ~50% cases, but when I open a second one it would crash 100%.
> 
> seems like setting `"window.titleBarStyle": "custom"` in the `.config/VSCodium/User/settings.json` file to be fixing it for me

**Comment by pshirshov** [comment]
Unfortunately that does not completely fix the problem for me. As I said before, frequently I'm able to open the first VSCode/VSCodium window but it always crashes on the second one. I'm on 6900XT if that matters.

**Comment by romanstingler** [comment]
@vaxerski not-hyprland label plz
https://github.com/microsoft/vscode/issues/184124

**Comment by vaxerski** [comment]
closing cuz not hl
