### ISSUE TITLE
Could not add steam games in steam. 

### ISSUE THREAD

**Issue by EvilBoi123** [hyprwm/Hyprland#3325]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

Could not add non steam game in steam.  :'(

ps. have tested on sway, it worked there

### How to reproduce

Just launch steam and press that lil button

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/102599991/55574d00-8ab4-4033-a70e-6103e60feddd

**Comment by obsqrbtz** [comment]
Seems that it's related to issue #2661 
As a quick workaround you may open steam in full-screen.

**Comment by vaxerski** [comment]
dupe

**Comment by EvilBoi123** [comment]
> Seems that it's related to the issue #2661 As a quick workaround you may open steam in full-screen.

Thanks for clarification bruh 👍👍
