### ISSUE TITLE
VMWare - mouse jumping out of window on click in a VM

### ISSUE THREAD

**Issue by ronasimi** [hyprwm/Hyprland#3326]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty ().

### Bug or Regression?

Bug

### Description

When running a Windows 10 virtual machine in VMware Workstation 17.0.2 build-21581411, the mouse jumps out of the window to the top left corner on click.  I'm sure it's something with xwayland and the way hyprland uses mouse bindings, but the issue never occurred on previous hyprland versions.

### How to reproduce

Open a windows 10 VM in VMware under hyprland, click on anything.

**Comment by ronasimi** [comment]
Just to add, this happens when VMWare is set to full screen as well

**Comment by vaxerski** [comment]
was fixed in -git
