### ISSUE TITLE
Firefox unfocusing itself

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#3328]
### Hyprland Version

Hyprland, built from branch main at commit cc630c90b5d743b380ff2da741881796ec79e997 dirty (master: partially revert 0e64dd2e and fix the animation (3327)). Tag: v0.29.1-80-gcc630c90  flags: (if any)

### Bug or Regression?

Bug

### Description

Sometimes when the cursor is not over a firefox window, it will unfocus itself. Not sure if this is a firefox bug or can we do something to prevent a window from unfocusing itself? 

### How to reproduce

1. open a random window e.g. terminal
2. move the cursor to the left half of the screen
3. open a firefox window on the right half of the screen (note: at this point firefox is focused/active, but the cursor is over the other window
4. ctrl+k open firefox search bar
5. type amogus into the search bar
6. press enter to search
7. notice that firefox has unfocused itself and is somehow not the active window anymore, and now the other random window is active. and if you didnt notice and keep trying to type stuff into firefox you will be typing into the other window instead

**Comment by memchr** [comment]
Depends on configuration, not universal.
e.g. with the example config, the new window will always open under the cursor.

So what is your config?

**Comment by awarewen** [comment]
maybe #3205 ?   unsure.

**Comment by thejch** [comment]
> > open a firefox window on the right half of the screen (note: at this point firefox is focused/active, but the cursor is over the other window
> 
> Depends on configuration, not universal. e.g. with the example config, the new window will always open under the cursor.
> 
> So what is your config?

just use the example config and set dwindle:force_split = 2

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by thejch** [comment]
not sure but i dont really care about this anymore i'll close
