### ISSUE TITLE
hyprctl setcursor crashes >0.29

### ISSUE THREAD

**Issue by Readf0x** [hyprwm/Hyprland#3330]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

Running `hyprctl setcursor` instantly crashes on any version greater than 0.29

### How to reproduce

run hyprctl setcursor

### Crash reports, logs, images, videos

[hyprlandCrashReport720.txt](https://github.com/hyprwm/Hyprland/files/12640880/hyprlandCrashReport720.txt)

**Comment by vaxerski** [comment]
doesnt for me lol

what's the command you are running?

**Comment by ArsenyPogosov** [comment]
I'm having the same problem

**Comment by Readf0x** [comment]
> what's the command you are running?
`hyprctl setcursor Afterglow-Catppuccin-Sapphire`

**Comment by IanKatsy** [comment]
Can confirm, happens on arch linux, both on hyprland and hyprland-git

[crash.txt](https://github.com/hyprwm/Hyprland/files/12653166/crash.txt)
[crash2.txt](https://github.com/hyprwm/Hyprland/files/12653175/crash2.txt)

**Comment by IanKatsy** [comment]
Turns out not setting a size is what makes it crash.

Running: `hyprctl setcursor x 16` works perfectly but running `hyprctl setcursor x` causes an instant crash

If you need an other crash log let me know

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12704976/patch.txt)

try this

**Comment by IanKatsy** [comment]
patch works :)

**Comment by vaxerski** [comment]
fixed in 9c00381dfcdebc1b392f0e05552775adc069f163
