### ISSUE TITLE
Hyprland is forgetting window rules

### ISSUE THREAD

**Issue by I-OutOfGravity-I** [hyprwm/Hyprland#3331]
### Hyprland Version

Hyprland, built from branch master at commit 96d555e8e794627bfc561e294e148ab8a9961fcc  (update v0.29.1). Tag: v0.29.1  flags: (if any)

### Bug or Regression?

Bug

### Description

Hyprland is forgetting the window rules I set for Picture in Picture mode in Firefox. When I start my Session the PIP Window is doing what it is supposed to do, but when I close PIP and open a new PIP then it is ignoring the window rules and just puts the Video next to Firefox when it should follow the rules I set up.

windowrulev2 = pin,                                    class:(firefox), title:(Picture-in-Picture)
windowrulev2 = float,                                  class:(firefox), title:(Picture-in-Picture)
windowrulev2 = move 1508 65,                class:(firefox), title:(Picture-in-Picture)
windowrulev2 = maxsize 400 225,           class:(firefox), title:(Picture-in-Picture)
windowrulev2 = nofullscreenrequest,       class:(firefox), title:(Picture-in-Picture)
windowrulev2 = nomaximizerequest,       class:(firefox), title:(Picture-in-Picture)

### How to reproduce

open PIP and close it again

**Comment by vaxerski** [comment]
dupe #2942
