### ISSUE TITLE
Hyprland does not like monitor descriptions with commas

### ISSUE THREAD

**Issue by Slabity** [hyprwm/Hyprland#3332]
### Hyprland Version

Hyprland, built from branch  at commit v0.29.1  ().

### Bug or Regression?

Bug

### Description

I have a monitor that, for some reason, provides a description that includes a comma:

`HYC CO., LTD. DUAL-DVI (DP-3 via HDMI)`

Hyprland's configuration parser does *not* like that as it's a comma separated value :laughing: 

I can get by using the connector ID instead, but any way to fix that so I can either escape the comma manually *or* put the entire description in quotes to parse it properly?

### How to reproduce

Use a monitor that provides a comma in the description and try to add it to your monitor configs.

**Comment by Slabity** [comment]
Just a note, this monitor is one of those old korean models that lets you overclock it by providing the kernel with a fake EDID, so this issue is *definitely* not something that most people would likely run into.

However, I think it might be a good idea to allow escaping commas out regardless for any other part of the config to prevent any similar issues. That's mostly why I'm opening this ticket.

**Comment by thejch** [comment]
#2457
