### ISSUE TITLE
X11 windows often don't obey center or move rules (race condition?)

### ISSUE THREAD

**Issue by alaricljs** [hyprwm/Hyprland#3333]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1    flags: (if any)

### Bug or Regression?

Bug

### Description

X11 windows often will not be placed correctly w/ wrv2 using `center` or `move`.

Tried with and w/o xwayland { force_zero_scaling=true }

### How to reproduce

```
windowrulev2 = float,class:.*
windowrulev2 = move cursor -50% -50%,floating:1
## OR this rule:
# windowrulev2 = center,floating:1 
```
Spam some X11 windows and many land at 0,0  some will obey the ruleset and land where they should.

### Crash reports, logs, images, videos

Image:  https://pasteboard.co/EnpWBJbzIF63.jpg

[LOG] Window rule float -> class:.* matched 55c1bba18700 [~]
[LOG] Window rule center -> floating:1 matched 55c1bba18700 [~]
[LOG] Searching for matching rules for xfce4-terminal (title: )
[LOG] Window rule float -> class:.* matched 55c1bb98b7d0 []
[LOG] Window rule center -> floating:1 matched 55c1bb98b7d0 []
[LOG] Searching for matching rules for xfce4-terminal (title: ~)
[LOG] Window rule float -> class:.* matched 55c1bb98b7d0 [~]
[LOG] Window rule center -> floating:1 matched 55c1bb98b7d0 [~]
[LOG] Searching for matching rules for Gvim (title: Vim)
[LOG] Window rule float -> class:.* matched 55c1bd09b180 [Vim]
[LOG] Window rule center -> floating:1 matched 55c1bd09b180 [Vim]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM)
[LOG] Window rule float -> class:.* matched 55c1bd09b180 [[No Name] - GVIM]
[LOG] Window rule center -> floating:1 matched 55c1bd09b180 [[No Name] - GVIM]
[LOG] Searching for matching rules for Gvim (title: Vim)
[LOG] Window rule float -> class:.* matched 55c1bcec77e0 [Vim]
[LOG] Window rule center -> floating:1 matched 55c1bcec77e0 [Vim]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM1)
[LOG] Window rule float -> class:.* matched 55c1bcec77e0 [[No Name] - GVIM1]
[LOG] Window rule center -> floating:1 matched 55c1bcec77e0 [[No Name] - GVIM1]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM2)
[LOG] Window rule float -> class:.* matched 55c1bd1699a0 [[No Name] - GVIM2]
[LOG] Window rule center -> floating:1 matched 55c1bd1699a0 [[No Name] - GVIM2]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM3)
[LOG] Window rule float -> class:.* matched 55c1bd0af970 [[No Name] - GVIM3]
[LOG] Window rule center -> floating:1 matched 55c1bd0af970 [[No Name] - GVIM3]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM4)
[LOG] Window rule float -> class:.* matched 55c1bd08e4d0 [[No Name] - GVIM4]
[LOG] Window rule center -> floating:1 matched 55c1bd08e4d0 [[No Name] - GVIM4]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM5)
[LOG] Window rule float -> class:.* matched 55c1bd3022a0 [[No Name] - GVIM5]
[LOG] Window rule center -> floating:1 matched 55c1bd3022a0 [[No Name] - GVIM5]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM6)
[LOG] Window rule float -> class:.* matched 55c1bd305460 [[No Name] - GVIM6]
[LOG] Window rule center -> floating:1 matched 55c1bd305460 [[No Name] - GVIM6]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM8)
[LOG] Window rule float -> class:.* matched 55c1bd309800 [[No Name] - GVIM8]
[LOG] Window rule center -> floating:1 matched 55c1bd309800 [[No Name] - GVIM8]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM7)
[LOG] Window rule float -> class:.* matched 55c1bdc98bc0 [[No Name] - GVIM7]
[LOG] Window rule center -> floating:1 matched 55c1bdc98bc0 [[No Name] - GVIM7]
[LOG] Searching for matching rules for Gvim (title: [No...VIM7)
[LOG] Window rule float -> class:.* matched 55c1bdc98bc0 [[No...VIM7]
[LOG] Window rule center -> floating:1 matched 55c1bdc98bc0 [[No...VIM7]
[LOG] Searching for matching rules for Gvim (title: [No Name] - GVIM7)
[LOG] Window rule float -> class:.* matched 55c1bdc98bc0 [[No Name] - GVIM7]
[LOG] Window rule center -> floating:1 matched 55c1bdc98bc0 [[No Name] - GVIM7]

**Comment by imxyy1soope1** [comment]
dup of #3029

**Comment by vaxerski** [comment]
not dupe, but expected x11 behavior unfortunately.

Some windows request a move to wherever they want shortly after being launched. 

In wayland, windows can't move themselves, that's a fix to this bs.
