### ISSUE TITLE
Crash when trying to overclock/set a non-standard monitor frequency

### ISSUE THREAD

**Issue by 6yntar05** [hyprwm/Hyprland#3336]
### Hyprland Version

d63a42e93fc49f57f69270ad70adea008a3bafec (ae69b9a2fa559d869f4e9c61ddf24e152d97df2f)

### Bug or Regression?

Regression

### Description

Last working commit: 116b9a80566e7956233b39697ac78c112d514c3c
Regression commit: d63a42e93fc49f57f69270ad70adea008a3bafec (ae69b9a2fa559d869f4e9c61ddf24e152d97df2f)
(when wlroots updated from c74f89 to 717ded)

I typically use `hyprctl keyword monitor "eDP-1,1920x1080@$FREQ,1280x0,1"`  to overclocking/downclocking the monitor.
This may not be the correct way, but it worked before
However, since the regression commit, Hyprland crashes when trying to set any non-standard frequency (for example: 30, 75, 81 for a 60Hz laptop screen; this problem affects all connected monitors)."

### How to reproduce

Compile d63a42e93fc49f57f69270ad70adea008a3bafec or later
hyprctl keyword monitor "$,$@$ANY_NOT_STANDART_FREQ,$,$"

### Crash reports, logs, images, videos

[d63a42e_hyprland.log](https://github.com/hyprwm/Hyprland/files/12642149/d63a42e_hyprland.log)

**Comment by vaxerski** [comment]
update to -git. Besides, this is a dupe, but I won't try and find it now, since it's fixed anyways.
