### ISSUE TITLE
Provide an option to identify workspaces per-monitor as in Awesome WM

### ISSUE THREAD

**Issue by vityafx** [hyprwm/Hyprland#3338]
### Description

The idea is to separate the workspaces, just as hyprsome does. Unfortunately, doing it from outside of hyprland is difficult due to many various reasons, and having it inside of hyprsome would:

1. Be easier to implement.
2. Would be easier to configure and use.
3. It would probably provide with much more options.

For anyone who has never worked with Awesome WM: if there is more than one monitor, for example, two, the workspaces are bound to the monitors in use: the first (`1`) workspace on one of the monitors is not the same as the workspace `1` on the other.
The current behaviour of Hyprland is that the workspace with id=1 is always unique and, once occupied, can't be reused on another monitor. The suggestion here is to make it optional to allow IDs to be unique inside the context of a monitor. This way is also backwards-compatible with one monitor.

**Comment by NotAShelf** [comment]
Have you tried the split-monitor-workspaces plugin? It provides the awesome-like functionality that you need.

**Comment by vaxerski** [comment]
yes, it should be a plugin. Can also be a script. No need for this is the core, as it's a way less preferable system than the current one.
