### ISSUE TITLE
Hypr ちゃん wants to see you more often. Hypr ちゃん wants to meet you alone.

### ISSUE THREAD

**Issue by kojq** [hyprwm/Hyprland#3348]
### Description

I saw #3343 attempting to address concerns from #2930. However, I suggest two more improvements.

1. Remove `force_hypr_chan` and make her stay with you forever, or make her appearing consistently the default option (requires changing the `force_hypr_chan` name)
2. `disable_hyprland_logo` should disable the logo and not also Hypr ちゃん (since that makes way more sense now)

**Comment by vaxerski** [comment]
ha ha funny

**Comment by kojq** [comment]
Thanks. I'm fine with the request not being considered, but it seems reasonable to have more features with the same number of variables present.

**Comment by janithcooray** [comment]
i suggested ` chad_user ` instead
