### ISSUE TITLE
Mixed Input Device Hotkeys

### ISSUE THREAD

**Issue by JoshuaFern** [hyprwm/Hyprland#335]
I have one of these fancy MMO gaming mice, a Logitech G600. My workflow is designed to use both of these input devices simultaneously for window management.

For some reason when I mix input devices with my hotkeys, for example SUPER on my mouse and D on my keyboard to launch dmenu, the hotkey doesn't register. However using SUPER+D on my keyboard alone works just fine and likewise hotkeys on my mouse alone work just fine.

This has never been an issue for me with Sway or i3 but I encountered a similar issue with dwl.

**Comment by vaxerski** [comment]
done in 6f7377f38138af5e41f094fbae90b4f68e94d49b
