### ISSUE TITLE
N-Point Bezier Curves

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#3351]
@vaxerski : There is a Todo in BezierCurve.hpp about implementing Bezier Curves with N Points.
I am not shure if that really gives any benefit to the animations, but if you think so, 
i would be happy to implement it.
If you (like me) don't think it adds any real value, we could get rid of the Todo.
The Bezier performance could suffer a bit from this, or we could have the old functions for cubic Beziers, but it would still be an extra if statement for every get[X/Y]ForT (except we would keep a specialized getYForPoint for cubic beziers, in that case the if statement would be for every getYForPoint).

Let me know what you think

**Comment by vaxerski** [comment]
I think it was a comment I left as a "maybe" but from what I can see right now nobody would care, so there is no point. Current ones work well.
