### ISSUE TITLE
Tiled windows are automatically trying to force Tooltip items to be tiled

### ISSUE THREAD

**Issue by RyanOrigens** [hyprwm/Hyprland#3353]
### Hyprland Version

Arch Repo

### Bug or Regression?

Bug

### Description

Tiled windows are trying to tile tooltip items.

[Kooha-2023-09-17-15-19-41.webm](https://github.com/hyprwm/Hyprland/assets/103891807/e508af17-1bb4-40ca-a146-3d69a90c2331)

### How to reproduce

Not needed

**Comment by n3oney** [comment]
That's on the program - why is it spawning windows for tooltips?

**Comment by RyanOrigens** [comment]
It happens for all programs, it isn't spawning windows for tooltips, the tile mode is forcing the tooltips into tiling.

It doesn't happen on gnome with a tiling extension neither on bspwm.

Another application showcase. 
 
If i give the tiling flag it simply bugs.

[Kooha-2023-09-17-17-21-02.webm](https://github.com/hyprwm/Hyprland/assets/103891807/eea2fcd5-74bb-48f1-b459-de9799786994)

**Comment by RyanOrigens** [comment]
Correction, it doesn't seem to happen for all applications, I'm trying to find a pattern, but it is happening in more than one application so this is not the application itself. Maybe some specific method how those applications are handling tooltips.

**Comment by RyanOrigens** [comment]
If i toggle the window as tiling through hotkeys it does not happen, only if i set it on the config file.

**Comment by n3oney** [comment]
It's probably XWayland.

**Comment by n3oney** [comment]
> If i toggle the window as tiling through hotkeys it does not happen, only if i set it on the config file.

Of course, if you set a windowrule that you want some class tiled, and a window spawns with that class, it will be tiled. Either write a better windowrule, stop the app from using XWayland or make the app's devs fix it.

**Comment by RyanOrigens** [comment]
These two windows have one thing in common: both of them spawn as floating windows in a tiling window manager, which shouldn't happen to start with.

It doesn't happen on bspwm, sway, or GNOME with a tiling extension.

On sway, these windows are recognized as tiling immediately. I don't need to force them into anything, and the tooltip item problem doesn't occur.

I don't believe the tooltip starts with any class and also there are a lot of applications that are not being recognized as tiling that i need to force them into it. (Chromium/Onlyoffice/ZapZap so on) All of them is immediately recognized as such on other tilings.

**Comment by n3oney** [comment]
Try getting everything to run not in XWayland first.

**Comment by RyanOrigens** [comment]
Also, another thing I tried was identifying which windows didn't automatically set themselves as tiles. Those windows were Xwayland windows. My Chromium was unable to launch a web application window as tiling and i had to force it into tiling mode. I switched my Chromium to native Wayland, and it didn't require manual setting to tiling mode; it automatically recognized it as such.

**Comment by RyanOrigens** [comment]
At last, I've tested setting tiling in other window managers for those buggy windows, and even though I forced them into tiling, no problems occurred with the tooltips.

In conclusion, there seem to be two problems with Hyprland:

1. Hyprland seems incapable of tiling XWayland windows properly.

2. When setting the tiling flag to windows in Hyprland, it appears to force tiling on more types of windows than it should.

**Comment by RyanOrigens** [comment]
You could take a look at another problem I found with the window manager on Hyprland. (This issue has nothing to do with XWayland; the application runs with native Wayland.)

https://github.com/hyprwm/Hyprland/issues/3359

**Comment by vaxerski** [comment]
this is 99.9% a windowrule just like another dude who was complaining his popups were being centered.

My guess: You copied&pasted someone else's config, didnt understand anything, and now have issues.

If this is reproducible with the default config feel free to come back here, but that would be the app's fault.
