### ISSUE TITLE
Godot mono not all renderers work

### ISSUE THREAD

**Issue by centuryhopper** [hyprwm/Hyprland#3354]
### Hyprland Version

Tag: v0.29.1

### Bug or Regression?

Bug

### Description

whenever I create a project with either forward+ or mobile, the editor won't open up. Only one that currently works is compatibility renderer.

### How to reproduce

try creating a project from godot mono on arch linux hyprland and set renderer to either one and see that the editor won't open.

### Crash reports, logs, images, videos

n/a

**Comment by PaulUlanovskij** [comment]
I believe this is actually an issue with godot`s wayland support. It will be fixed eventually. Some info about this is covered in this article: [https://godotengine.org/article/dev-snapshot-godot-4-3-dev-3/](url)

**Comment by izmyname** [comment]
> I believe this is actually an issue with godot`s wayland support. It will be fixed eventually. Some info about this is covered in this article: [https://godotengine.org/article/dev-snapshot-godot-4-3-dev-3/](url) Also if I run godot 4.2.2 stable in verbose mode I get this error message:
> 
> ```
> ERROR: Can't create a Vulkan window
>    at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:5640)
> ```
> 
> Which suggests no support for vulkan renderer on wayland

If this isn't a Hyprland issue - close?
