### ISSUE TITLE
Jetbrains IDEs doesn't run fullscreen

### ISSUE THREAD

**Issue by IliaSobolev** [hyprwm/Hyprland#3355]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

When I try to open Jetbrains IDEs (pycharm, goland) in fullscreen they don't open in fullscreen.

### How to reproduce

Try to open Jetbrains IDEs in fullscrean

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/143018142/d396f2f8-5083-472d-8363-16ba58e9b3c6

**Comment by MightyPlaza** [comment]
are you using the dispatcher or in-app shortcuts?

**Comment by IliaSobolev** [comment]
> are you using the dispatcher or in-app shortcuts?

i use bind in hyprland.conf

**Comment by MightyPlaza** [comment]
try the `nofullscreenrequest` window rule
jetbrains stuff doesn't like to play nice with wayland, let's hope they get a wayland frontend soon

**Comment by IliaSobolev** [comment]
> `nofullscreenrequest`
it didn't work and I still can't open it.

**Comment by MightyPlaza** [comment]
does it happen elsewhere? (sway for example)

**Comment by IliaSobolev** [comment]
> does it happen elsewhere? (sway for example)

No, when I used sway everything was well.

**Comment by MightyPlaza** [comment]
are you sure the windowrule was properly set up? (try using it and `nomaximizerequest` as well)
also test on latest sway from git (https://aur.archlinux.org/packages/sway-git-wlroots-git)

**Comment by IliaSobolev** [comment]
> are you sure the windowrule was properly set up? (try using it and `nomaximizerequest` as well) also test on latest sway from git (https://aur.archlinux.org/packages/sway-git-wlroots-git)
On the latest version of sway it also doesn't open full screen and after windowrule =nofullscreenrequest,nomaximizerequest,^(goland)$ it doesn't start.

**Comment by MightyPlaza** [comment]
if it doesn't work on sway as well it's unlikely to be an hyprland issue
likely is an issue with wlroots (why it stoped working from packaged sway to git sway)
but in the end should really be fix on application's end
