### ISSUE TITLE
Possible Bug, Pop UP window is forced into floating

### ISSUE THREAD

**Issue by RyanOrigens** [hyprwm/Hyprland#3359]
### Hyprland Version

Arch Repo

### Bug or Regression?

Bug

### Description

The pop-up window, which shouldn't be recognized as a window, is being recognized as one. What happens is that this window automatically closes when it loses focus. To work around this issue, I had to configure the window to never lose focus.

Please look at the top left side of the screen; there is an Application Tag on each desktop. You can observe that in GNOME, this is never recognized as an application, and neither does the window behind it ever lose focus nor does it ever gain focus."

### How to reproduce

Gnome (With tiling extension proving that this is a Pop up window and that doesn't get recognized as a window, it also happens to bspwm.)

[Screencast from 2023-09-17 18-09-53.webm](https://github.com/hyprwm/Hyprland/assets/103891807/6dadb2b9-357c-4e76-b617-5d4f32d383c6)

Hyprland (Being recognized as a window)

[Kooha-2023-09-17-18-13-39.webm](https://github.com/hyprwm/Hyprland/assets/103891807/5e615887-2f4f-4cc5-aa49-2fa9d33332d6)

The Application is called Crow Translator

The key is a global key, you would need to set this hotkey:

bind = CTRL SHIFT, C, exec, dbus-send --type=method_call --dest=io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow io.crow_translate.CrowTranslate.MainWindow.translateSelection

**Comment by vaxerski** [comment]
looks like an xwayland app. XWayland only has windows. This is some edge case about wonky xorg behavior. Since you seem to have fixed it: "To work around this issue, I had to configure the window to never lose focus." I have no plans of fixing this. Too much of an edge case

**Comment by RyanOrigens** [comment]
The app is running under native wayland.

**Comment by vaxerski** [comment]
then it should not be a toplevel if it wants to hog focus :)
