### ISSUE TITLE
How to keep my focused window after switching to another workspace then coming back?

### ISSUE THREAD

**Issue by hyq12358** [hyprwm/Hyprland#336]
I already set `follow_mous=0`, when I focus a window A in workspace 1,then I switch to workspace 2,do something,now if I switch back to workspace 1,  I do not focus on window A anymore.
How to reserve my focus after switching to other workspaces?

**Comment by vaxerski** [comment]
not supported as of right now, can add tho

**Comment by nsavch** [comment]
Would be very cool to have it indeed, the current way it works requires too much window refocusing during workspace switching...

**Comment by Dickby** [comment]
The most annoying version of that problem:
switching to the special workspace, if the mouse isn't atweeee a position that is occupied by one of the special workspace windows,
the whole special workspace doesn't gain focus.

**Comment by vaxerski** [comment]
done in dacaf72e02b8d1819135f6aef3911e8211e98630
