### ISSUE TITLE
surface was destroyed before its role object

### ISSUE THREAD

**Issue by theoparis** [hyprwm/Hyprland#3360]
### Hyprland Version

Hyprland main (gentoo hyprland-999)

### Bug or Regression?

Bug

### Description

```
$ wl-kbptr
53x26+53+187
[destroyed object]: error 4: surface was destroyed before its role object
```

It is supposed to move the mouse cursor to the chosen location. It works correctly on Sway.

### How to reproduce

Build and run https://github.com/moverest/wl-kbptr on Hyprland

**Comment by vaxerski** [comment]
> Hyprland main (gentoo hyprland-999)

is this the output of `hyprctl version` as you were prompted? Please stick to the issue format, it's there for a damn reason.

> It works correctly on Sway.

sway release or sway-git? Always test against sway-git please

**Comment by theoparis** [comment]
I have encountered some build errors when attempting to build the latest commit of Hyprland only seem to happen with a meson gentoo ebuild I copied from gentoo's release ebuild. When building with meson manually it works fine.
In VarList.cpp it complains that `removeBeginEndSpacesTabs` is undeclared - adding `#include "MiscFunctions.hpp"` gets somewhere. However  `wlr/util/region.h` needs to be included with `extern "C"` or else it causes wlr_region_scale to be undefined at link time 🤔 
If it helps I am using clang/lld 17 with LTO.

Anyway, If I use the manual meson build method the original issue is still relevant:
```
theo@gigatop ~> hyprctl version
Hyprland, built from branch main at commit 1b48642fd15c433c53876f1b933dcd46265caf8f  (props: bump version to 0.30.0).
Tag: ?

flags: (if any)
debug
```

In terms of sway I used `sway version 0.3.2-6f6991a1 (Sep  9 2023, branch 'master')` which was built from [SwayFX](https://github.com/WillPower3309/swayfx).

**Comment by id-ekaagr** [comment]
facing the same issue on nixos 23.11 with hyprland.

**Comment by id-ekaagr** [comment]
> Note that your compositor needs to support the [wlr-layer-shell-unstable-v1](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) and [wlr-virtual-pointer-unstable-v1](https://wayland.app/protocols/wlr-virtual-pointer-unstable-v1) protocols.

Possible to deal with this?

**Comment by vaxerski** [comment]
closing then
