### ISSUE TITLE
Crash when hovering over waybar?

### ISSUE THREAD

**Issue by PucklaJ** [hyprwm/Hyprland#3361]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

I just moved my cursor over waybar shortly after booting the system and then hyprland crashed. I hope the crash report can help.

### How to reproduce

It does not seem to be reproducible that easily because it does not crash the other times I hover my cursor over waybar. 

### Crash reports, logs, images, videos

[waybar_hover_crash.txt](https://github.com/hyprwm/Hyprland/files/12645246/waybar_hover_crash.txt)

**Comment by memchr** [comment]
What is your operating system? Did you build hyprland yourself or use a package from repo?

**Comment by PucklaJ** [comment]
I am using Artix Linux and I installed hyprland from the world repository of said distro. I don't know if the crash report is of much help, but I thought I would share it.

**Comment by imxyy1soope1** [comment]
we may need your waybar log

how did you install waybar?

**Comment by vaxerski** [comment]
can you try on -git?

**Comment by PucklaJ** [comment]
I don't think that it is necessarily waybar related. It does not happen anymore. It just crashed on this specific instance.

**Comment by romanstingler** [comment]
@fufexan can be closed
