### ISSUE TITLE
Touch device work not good with xwayland-x11 apps

### ISSUE THREAD

**Issue by gfhdhytghd** [hyprwm/Hyprland#3362]
### Hyprland Version

v0.29.1-85-gc8cc811e

### Bug or Regression?

Bug

### Description

The position I touch is not the position the APP get, build from main half-day before and reinstall from aur several hours ago and both version have the problem, if you remember the "x11 not in the certer" problem, with my measurement，the offsets for both errors are almost the same, so mayde the same rootcause.

### How to reproduce

turn on a x11 app on a very hidpi touchscreen

**Comment by gfhdhytghd** [comment]
Monitor eDP-1 (ID 0):
	3120x2080@90.00100 at 1781x2128
	description: California Institute of Technology 0x1415 0x4E433030 (eDP-1)
	make: California Institute of Technology
	model: 0x1415
	serial: 0x4E433030
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 2.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-4 (ID 1):
	1920x1080@60.00000 at 0x2106
	description: GSV GS156FT Pro  (DP-4)
	make: GSV
	model: GS156FT Pro
	serial: 
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.08
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

**Comment by gfhdhytghd** [comment]
09 monitor=eDP-1, 3120x2080@90, 1781x2128, 2, bitdepth,10
 10 #monitor=eDP-1, 3120x2080@90, 550x2128, 2
 11 #monitor=eDP-1, 1920x1080@90, 550x2128, 1, bitdepth,10 
 12 monitor=DP-4, 1920x1080@60, 0x2106, 1.078,
 13 monitor=DP-2, 1920x1080@60, 1661x1126, 1.078,
 14 monitor=DP-3, 3840x2560@60.000, 1231x363, 1.45, bitdepth,10
 15 monitor=DP-1, preferred, 3891x2128, 1.75
 16 monitor=HEADLESS-1, 3168x2375@120,3891x2128, 2.284

**Comment by hanspaerna** [comment]
Unfortunately, I can confirm the same issue on my laptop with HiDPI touchscreen. If I set the display scale to 2 (200%) and disable experimental fractional scaling to avoid blurriness in Xwayland applications, all my touches in Xwayland windows are misaligned, to say the least. It's quite important to me since I use Bitwig Studio.

**Comment by sakria9** [comment]
Because the position didn't scale. Not sure whether it is an upstream issue.

The position semantic is not consistent between `wlr_cursor_warp` and `wlr_seat_touch_notify_motion`.
`wlr_cursor_warp` will scale the position, `wlr_seat_touch_notify_motion` will not scale the postition.

```cpp
const auto PMONITOR = g_pCompositor->getMonitorFromID(m_sTouchData.touchFocusWindow->m_iMonitorID);

// pass unscaled parameter, but will result in scaled cursor move
wlr_cursor_warp(g_pCompositor->m_sWLRCursor, nullptr, PMONITOR->vecPosition.x + e->x * PMONITOR->vecSize.x, PMONITOR->vecPosition.y + e->y * PMONITOR->vecSize.y);

auto local = g_pInputManager->getMouseCoordsInternal() - m_sTouchData.touchSurfaceOrigin;
if (m_sTouchData.touchFocusWindow->m_bIsX11)
    local = local * m_sTouchData.touchFocusWindow->m_fX11SurfaceScaledBy;

// pass unscaled parameter, result in unscaled touch motion
wlr_seat_touch_notify_motion(g_pCompositor->m_sSeat.seat, e->time_msec, e->touch_id, local.x, local.y);
wlr_seat_pointer_notify_motion(g_pCompositor->m_sSeat.seat, e->time_msec, local.x, local.y);
```

**Comment by vaxerski** [comment]
wasn't this fixed like yesterday?

**Comment by sakria9** [comment]
Sorry, I didn't work on the latest commit. This was fixed.

**Comment by gfhdhytghd** [comment]
> wasn't this fixed like yesterday?

Fixed

**Comment by gfhdhytghd** [comment]
> wasn't this fixed like yesterday?

If you still remember the xwayland app not in the center problem, that problem is still there
