### ISSUE TITLE
Hypr-chan flashing in Firefox while resizing fast with wallpaper set

### ISSUE THREAD

**Issue by nullsystem** [hyprwm/Hyprland#3367]
### Hyprland Version

v0.29.1 (NixOS Unstable)

### Bug or Regression?

Bug

### Description

Edge case and very minor visual bug, only seen on Firefox (dunno if there's other programs that have this) with a wallpaper set by Hyprpaper. Can see hypr-chan flashing while resizing really fast or changing window mode. Although `misc.disable_hyprland_logo = true` does mitigate the issue.

### How to reproduce

- `misc.disable_hyprland_logo = false`/the default showing Hypr-chan, yet have Hyprpaper set
- Firefox set to use wayland
- Just resize Firefox really fast or switch floating/tiling of that window quickly and see Hypr-chan flash up.

### Crash reports, logs, images, videos

[2023-09-18T220834.webm](https://github.com/hyprwm/Hyprland/assets/15316579/d5408ecd-ac40-4df0-80f3-c58a3cd02233)

**Comment by vaxerski** [comment]
dupe https://github.com/hyprwm/Hyprland/issues/2817
