### ISSUE TITLE
Dialogs do not appear

### ISSUE THREAD

**Issue by bearcatsandor** [hyprwm/Hyprland#337]
[LOG] Instance Signature: 1cf2f378d4a0e5e3da757d90404c2816a6765626_1657308302
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: jaguarundi
[LOG] Release: 5.18.2-zen1

Using hyprland git from Wednesday 

Dialogs don't appear at all.  Save/download dialogs in qutebrowser, chrome-beta, and firefox freeze the respective browser (because they're modal) due to my being unable to close them. If they were just invisible ESC would get rid of them and return control.  Launching rofi from a terminal leaves me with a hanging prompt and no menu on my screen. Interestingly wofi works. I'd think that was due to it's being a wayland app, but my 3 browsers aren't running under xorg, so xwayland (which is running) probably is not the culprit.

It's probably a misconfiguration.  I'd attach my config, but it would freeze this browser.

My Config:
$TERMINAL = alacritty -e tmux -u new-session -t 'MoonWind' && tmux new-window -t 'MoonWind-1'
monitor=,1920x1080@60,0x0,1

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=1
    natural_scroll=1 
}

general {
    sensitivity=1.0 # for mouse cursor
    main_mod=SUPER

    gaps_in=5
    gaps_out=5.0
    border_size=2
    col.active_border=0x5b768eff
    col.inactive_border=0x5f5f87ff

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

    damage_tracking=full # leave it on full unless you hate your GPU and want to make it suffer
}

decoration {
    rounding=10
    multisample_edges=1.0

    blur=1
    blur_size=3 # minimum 1
    blur_passes=1 # minimum 1, more passes = more resource intensive.
    # Your blur "amount" isBEFORE submitting.
 blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
    active_opacity=0.95
    inactive_opacity=0.8
    fullscreen_opacity=1.0

    drop_shadow=1.0
    shadow_range=40   #Shadow range (in pixels), more = larger shadow
    shadow_render_power= 4  #int - (1 - 4), in what power to render the falloff (more power, the faster the falloff)
    shadow_ignore_window= 0  #int - (0/1) if true, the shadow will not be rendered behind the window itself, only around it.
    # col.shadow=0x00000088 #col -  shadow's color. Alpha dictates shadow's opacity.
    shadow_offset= 2.0 0.0  #vec2 - shadow's rendering offset.
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=borders,1,10,default
    animation=fadein,1,10,default
    animation=workspaces,1,6,default
}

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

# example window rules
# for windows named/classed as abc and xyz
#windowrule=move 69 420,abc
#windowrule=size 420 69,abc
#windowrule=tile,xyz
##windowrule=float,dialog
windowrule=float,gimp
windowrule=float,mpv
##windowrule=float,pop-up
windowrule=float,qjackctl
windowrule=float,rofi
windowrule=float,task_dialog
windowrule=workspace 1 silent,$TERMINAL
windowrule=workspace 2 silent,qutebrowser
windowrule=workspace 3 silent,telegram-desktop
#windowrule=pseudo,abc
#windowrule=monitor 0,xyz

bind=SUPER,RETURN,exec,$TERMINAL
bind=SUPER,X,killactive,
bind=SUPER,Q,exit,
bind=SUPER,E,exec,dolphin
bind=SUPER,V,togglefloating,
bind=SUPER,D,exec,rofi --show combi
bind=SUPER,R,exec,wofi
bind=SUPER,P,pseudo,
bind=SUPER,C,exec,rofi -show calc -modi "calc:qalc +u8"  -no-sort

bind=SUPER,H,movefocus,l
bind=SUPER,L,movefocus,r
bind=SUPER,K,movefocus,u
bind=SUPER,J,movefocus,d

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspace,1
bind=ALT,2,movetoworkspace,2
bind=ALT,3,movetoworkspace,3
bind=ALT,4,movetoworkspace,4
bind=ALT,5,movetoworkspace,5
bind=ALT,6,movetoworkspace,6
bind=ALT,7,movetoworkspace,7
RrndrrLT,8,movetoworkspace,8
bind=ALT,9,movetoworkspace,9
bind=ALT,0,movetoworkspace,10

# device rules
device: Logitech MX Ergo {
    # natural_scroll=1 
}

# execute startup applications
exec-once=mako               # notifications
exec-once=udiskie            # removable drive handling
exec-once=waybar
#exec-once=mpv --profile=wallpaper ~/.config/sway/jaguarundi.jpg
exec-once=swaybg -m fill -i ~/.config/sway/jaguarundi.jpg

exec-once=$TERMINAL
exec-once=qutebrowser
exec-once=telegram-desktop
exec-once=~/.config/hypr/cleanup_after_start.sh

**Comment by vaxerski** [comment]
cannot reproduce, issue on your side. Furthermore, firefox runs natively on wayland and unless you set the envvars to force it not to, hyprland will force it under native wl.

**Comment by bearcatsandor** [comment]
Weird. I'll close it and keep poking, and re-open if need be.  Thank you for the rapid response!

Firefox works now, so this may be a QT issue.

**Comment by bearcatsandor** [comment]
For anyone else that may be dealing with this, the culprit was a QT_STYLE_OVERRIDE=gtk2 that has snuck into my system envars from someplace.
