### ISSUE TITLE
Exec does not populate custom desktop entry files

### ISSUE THREAD

**Issue by RichardFevrier** [hyprwm/Hyprland#3370]
### Hyprland Version

v0.29.1

### Description

Hello 👋

I am trying to populate `wofi` launcher with some custom `.desktop` entry files placed at `~/.local/share/applications/`.

It works well when using directly the command from `bash`: 
```
wofi --show drun --allow-images --no-actions --insensitive
``` 
Problem happens when using the exact same command thru a `hyprland` `bind`:
```
bind = $mainMod, space, exec, wofi --show drun --allow-images --no-actions --insensitive
```
Does hyprland needs something specific? (like `XDG` var)

Thanks.

**Comment by vaxerski** [comment]
it's possible that you export some env in something like `.bashrc` and execs don't pick the env up.

Try printing the env with something like `,exec, env > /tmp/blahdbdejfne.txt` and inspecting it

**Comment by RichardFevrier** [comment]
There is definitely a difference with `printenv` but `XDG_DATA_DIRS` are equals and in both cases nothing points directly to `~/.local/share/applications/` (they both point to the parent tho)

**Comment by vaxerski** [comment]
are you sure that's what it's using and not something like home?

**Comment by RichardFevrier** [comment]
I have just checked by moving the `.desktop` entry file somewhere else and it did disappear from the first method too.
So I guess yes that's what it's using.

**Comment by vaxerski** [comment]
Nothing else should differ. exec is just a `/bin/sh -c "[some envs] cmd"`

**Comment by RichardFevrier** [comment]
Closing it.
I've spent one hour checking my env vars one by one and I still cant figure which one is responsible of it so I've ended up injecting the binaries paths pointed by my custom entry files in front of the command.
Thanks for the help
