### ISSUE TITLE
Hyprland 29.* does not start in arch linux

### ISSUE THREAD

**Issue by CRAG666** [hyprwm/Hyprland#3372]
### Hyprland Version

29.1

### Bug or Regression?

Bug

### Description

Hyprland does not start

### How to reproduce

Install hyprland pkg in arch linux, start Hyprland

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11 (Segmentation fault)

Version: 96d555e8e794627bfc561e294e148ab8a9961fcc
Tag: v0.29.1

System info:
	System name: Linux
	Node name: P53
	Release: 6.5.3-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117GLM [Quadro T2000 Mobile / Max-Q] [10de:1fb8] (rev a1) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x557a66f44492]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x42c) [0x557a66f1f05c]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x47) [0x557a66eb69d7]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7fd4d323e710]
		??
		??:0
	#4 | /usr/lib/libwlroots.so.12032(wlr_backend_get_drm_fd+0x4) [0x7fd4d3e84a54]
		??
		??:0
	#5 | /usr/lib/libwlroots.so.12032(+0x3c585) [0x7fd4d3e75585]
		??
		??:0
	#6 | /usr/lib/libwlroots.so.12032(wlr_drm_backend_create+0x9d6) [0x7fd4d3e8b946]
		??
		??:0
	#7 | /usr/lib/libwlroots.so.12032(+0x52fa3) [0x7fd4d3e8bfa3]
		??
		??:0
	#8 | /usr/lib/libwlroots.so.12032(wlr_backend_autocreate+0x50e) [0x7fd4d3e8c6ae]
		??
		??:0
	#9 | Hyprland(_ZN11CCompositor10initServerEv+0x13e) [0x557a66ebcdae]
		??
		??:0
	#10 | Hyprland(main+0x8ba) [0x557a66ea606a]
		??
		??:0
	#11 | /usr/lib/libc.so.6(+0x27cd0) [0x7fd4d3227cd0]
		??
		??:0
	#12 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fd4d3227d8a]
		??
		??:0
	#13 | Hyprland(_start+0x25) [0x557a66eb41c5]
		??
		??:0

Log tail:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117GLM [Quadro T2000 Mobile / Max-Q] [10de:1fb8] (rev a1) (prog-if 00 [VGA controller])

[WARN] Warning: you're using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Join the discord server!

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 68.36µs. Estimated average calc time: 0.14µs.
[LOG] Creating the ConfigManager!
[LOG] Creating the CHyprError!
[LOG]  [hookSystem] New hook event registered: focusedMon
[LOG]  [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 49.30µs. Estimated average calc time: 0.12µs.
[LOG] Using config: /home/think-crag/.config/hypr/hyprland.conf
[LOG] Registered dynamic var "$rofiScripts" -> ~/.config/rofi/scripts
[LOG] Registered dynamic var "$scriptsDir" -> /home/think-crag/.config/hypr/scripts
[LOG] Registered dynamic var "$notifycmd" -> notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 47.10µs. Estimated average calc time: 0.12µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 47.12µs. Estimated average calc time: 0.12µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 46.96µs. Estimated average calc time: 0.12µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 46.94µs. Estimated average calc time: 0.11µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG]  [hookSystem] New hook event registered: configReloaded

**Comment by vaxerski** [comment]
driver issue. Nvidia spotted.

**Comment by CRAG666** [comment]
@vaxerski Version 28 does not present these problems, it seems to me that version 29 will have problems.

**Comment by tchofy** [comment]
Check the -git version, there was a wlroots "issue" on nvidia gpus.

**Comment by vaxerski** [comment]
if you want to even use nvk with hyprland you'll also have to wait for hyprland to support vulkan :P

**Comment by tchofy** [comment]
Didn't they go with Zink for the opengl part? Now if it'll work nicely with wlroots remains to be seen.

**Comment by CRAG666** [comment]
I don't really use Nvidia with Open drivers, and before I had no problems with Hyprland
@vaxerski 
@tchofy 
Thanks
