### ISSUE TITLE
some apps closed after systemctl suspend

### ISSUE THREAD

**Issue by bobblkabb** [hyprwm/Hyprland#3376]
### Hyprland Version

0.29.1

### Bug or Regression?

Bug

### Description

Hello,

after a systemctl suspend some apps are closed and some things don't work properly anymore: I can't open the foot terminal via keyboard shortcut anymore.
Can see the behavior on both my computers. Both with openSUSE Tumbleweed. 
Closed programs include: telegram-desktop, dolphin, teamviewer and openSCAD.

Übrigens habe ich den PC am 19.September um ca. 16:00 Uhr schlafen gelegt und am 20.September ca. 6:00 Uhr aufgeweckt. Es sind aber auch Einträge um 20:56 Uhr in dmesg. Is that normal?

[dmesg.txt](https://github.com/hyprwm/Hyprland/files/12668509/dmesg.txt)

BR,
Michael

### How to reproduce

Lock pc via systemctl suspend and wake it up.

**Comment by vaxerski** [comment]
das wurde in der -git version behoben
