### ISSUE TITLE
Cannot set Environment Variables with "hyprctl keyword"

### ISSUE THREAD

**Issue by trowgundam** [hyprwm/Hyprland#3379]
### Hyprland Version

Hyprland, built from branch  at commit 96d555e8e794627bfc561e294e148ab8a9961fcc dirty (). Tag: v0.29.1

### Bug or Regression?

Bug

### Description

I am using the build from the Official Arch Repositories. I am attempting to use the following script:

```bash
#!/bin/bash

for var in $(run-parts /usr/lib/systemd/user-environment-generators | sed '/:$/d; /^$/d'); do
    IFS="=" read -ra PARTS <<<"$var"
    hyprctl keyword env "${PARTS[0]},${PARTS[1]}"
done
```

However this doesn't result in any environment variables being added to my `printenv` output. I also checked after restarting my terminal emulator. I've also tried executing the script through `hyprctl dispatch exec` and as a `exec-once` in my config. I've even tried just running `hyprctl keyword env Test,Test`, just ensure it wasn't my script. All calls to hyprctl does output "ok".

An alternative to all this would just be someway for Hyprland to source variables from ~/.config/environment.d. The above script was just my attempt to do so.

### How to reproduce

Execute `hyprctl keyword env Test,Test` and then check output of `printenv`.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/c5451b7b-e8a3-4ed3-bdfa-cd58ada94eb1)
