### ISSUE TITLE
TTY launch segfaults on Gentoo, XWayland launch works fine

### ISSUE THREAD

**Issue by mrkajetanp** [hyprwm/Hyprland#3382]
### Hyprland Version

0.29.1, built from branch at commit 96d555e8e794627bfc561e294e148ab8a9961fcc

### Bug or Regression?

Bug

### Description

Hi, I'm trying to get this working on Gentoo. I encountered a strange issue where Hyprland runs okay when launched from a terminal using XWayland but crashes immediately with a segfault if I try launching it from a TTY (using dbus or just exec) as well as through a display manager (sddm).

Looking at the error logs the backtrace goes through `wlr_drm_backend_create` and the log from a successful XWayland launch shows it's successfully creating the backend right after the error log from a failed launch cuts off. I'm assuming it's something related to the renderer backend but I'm not sure how these things work enough to be able to understand the issue. Any ideas what could be causing this?

I'll attach the error log with the backtrace below.

Installed package versions are as follows:
```
wayland 1.22.0
wayland-protocols 1.32
xwayland 23.2.0
hyprland 0.29.1
hyprland-protocols 0.2
xdg-desktop-portal-hyprland 0.5.0
wlroots 0.16.2-r1
libdrm 2.4.116
mesa 23.2.0_rc3 (built with gles2)
```

### How to reproduce

1. Install Gentoo (good luck)
2. Follow the instructions from the wiki
```
emerge --ask gui-wm/hyprland
emerge --ask gui-libs/xdg-desktop-portal-hyprland
eselect repository enable guru
emaint sync -r guru
emerge --ask gui-apps/hyprland-plugins
emerge --ask gui-apps/hyprpaper
emerge --ask gui-apps/hyprpicker
emerge --ask gui-wm/hyprland-contrib
```
3. Launch from an X session in the terminal - happy result
4. Go to TTY
5. `dbus-run-session Hyprland` - sad result
6. Select the Hyprland session in sddm or other display manager - even sadder result

### Crash reports, logs, images, videos

[hyprlandCrashReport23670.txt](https://github.com/hyprwm/Hyprland/files/12673679/hyprlandCrashReport23670.txt)

**Comment by mrkajetanp** [comment]
Note: The error also occurs if I try building from source. The last commit I was able to build from source was c3a83daa1e61285a418c39a1d9f29427c2c9a2c3.
Building from source after this commit fails with this error introduced with commit 61a71c65ace5124cb26a074715280537e6e34d00. Not sure what the solution for that is either.

```
/usr/bin/c++ -DGIT_BRANCH=\"\" -DGIT_COMMIT_HASH=\"\" -DGIT_COMMIT_MESSAGE=\"\" -DGIT_DIRTY=\"dirty\" -DGIT_TAG=\"\" -DHyprland_EXPORTS -DWLR_USE_UNSTABLE -I/home/kajetan/git/Hyprland/. -I/home/kajetan/git/Hyprland/src -I/home/kajetan/git/Hyprland/subprojects/wlroots/include -I/home/kajetan/git/Hyprland/subprojects/wlroots/build/include -I/home/kajetan/git/Hyprland/subprojects/udis86 -I/home/kajetan/git/Hyprland/protocols -isystem /usr/include/libdrm -isystem /usr/include/pango-1.0 -isystem /usr/include/harfbuzz -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/uuid -isystem /usr/include/json-c -isystem /usr/include/blkid -isystem /usr/include/fribidi -isystem /usr/include/libmount -isystem /usr/include/libpng16 -isystem /usr/lib64/libffi/include -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -pthread -Winvalid-pch -x c++-header -include /home/kajetan/git/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx -MD -MT CMakeFiles/Hyprland.dir/cmake_pch.hxx.gch -MF CMakeFiles/Hyprland.dir/cmake_pch.hxx.gch.d -o CMakeFiles/Hyprland.dir/cmake_pch.hxx.gch -c /home/kajetan/git/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx.cxx
In file included from /home/kajetan/git/Hyprland/src/defines.hpp:2,
                 from /home/kajetan/git/Hyprland/src/Compositor.hpp:7,
                 from /home/kajetan/git/Hyprland/./src/pch/pch.hpp:1,
                 from /home/kajetan/git/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/kajetan/git/Hyprland/src/debug/Log.hpp:4:10: fatal error: format: No such file or directory
    4 | #include <format>
      |          ^~~~~~~~
compilation terminated.
```
Attaching the crash report when building from source here is as well - it's the same apart from it being more verbose with which parts of `libwlroots.so` the issue is going through.
[hyprlandCrashReport4467.txt](https://github.com/hyprwm/Hyprland/files/12674552/hyprlandCrashReport4467.txt)

**Comment by vaxerski** [comment]
crash: driver issue unfortunately. Also keep in mind certain settings might be broken on 0.29.1 due to a few wlr issues. Try -git.

build: too old of a compiler (or stdlib) gcc >= 13 (clang >= 17 iirc)

both issues are not bugs though, so closing.
