### ISSUE TITLE
nomacs cannot drag

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#3385]
### Hyprland Version

Hyprland, built from branch main at commit 0dbd9970031940b50f9cce4c88989c2830d2a15f dirty (input: Various constraint handling fixes (3381)). Tag: v0.29.1-95-g0dbd9970

### Bug or Regression?

Bug

### Description

I'm using nomacs and I just realized I cannot correctly crop images with Hyprland. The dragging of the cropping box is interupted.

This does not happen on sway, where the dragging of the zone works fine.

### How to reproduce

- open nomacs on an image
- hit 'C' to crop
- start dragging a crop zone
- dragging is interupted almost immediately

**Comment by vaxerski** [comment]
oh shit XD

**Comment by primalmotion** [comment]
works perfectly now. thanks!
