### ISSUE TITLE
Hyprland crashes when display is turned on

### ISSUE THREAD

**Issue by iguanajuice** [hyprwm/Hyprland#3388]
### Hyprland Version

0.29.1

### Bug or Regression?

Regression

### Description

When a display is turned off and then on again, either by dpms or physically, Hyprland will crash once you turn on a display.

This issue did not exist in the previous version of Hyprland nor the current version of sway.

### How to reproduce

Description.

### Crash reports, logs, images, videos

[crash log](https://github.com/hyprwm/Hyprland/files/12686283/ileftswayforthis.txt)

**Comment by spector700** [comment]
I have the same issue, I think. On the same version with Nvidia and with powerManagment enabled.

Turning the monitors off and on with power or dpms works fine. But if the monitors have been off for 15 min or more, hyprland always crashes when the screens come back on.

[CrashReport.txt](https://github.com/hyprwm/Hyprland/files/12689751/hyprlandCrashReport1700.txt)

**Comment by vaxerski** [comment]
release will be released when release time is upon us again.

Although that will most likely happen to be more-or-less soon
