### ISSUE TITLE
Chroma key

### ISSUE THREAD

**Issue by ElSargo** [hyprwm/Hyprland#3391]
### Description

# What it is
I'm sure you know about green screens for TV, movies etc. They change all the pixels of a certain color to something else.
I would like to see an option that applies this to the compositor. For example 
```
chroma_key = #00ff00
chroma_replace = rbga(0.2,0.2,0.2,0.3)
```
That would replace all a windows pixels that match chroma_key with chroma_replace or something similar
Or better yet a window rule
```
windowrulev2 = chroma_key #00ff00 rbga(0.2,0.2,0.2,0.3), class:(firefox)
```

# Why the f ???
Many applications don't support transparency at all, or only in a half baked way. This would create an easy way for any program that has a customizable appearance to have transparency enabled, or even allow things like transparent web pages in browsers through the use of something like [stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/).

**Comment by vaxerski** [comment]
this is a bad idea. Chroma keying is quite difficult and in no way nearly as easy as you make it out to be.

Ignoring how computationally expensive it is.

I do not believe this has a place in Hyprland.
