### ISSUE TITLE
weird blinking when toggling scratchpad on and offf

### ISSUE THREAD

**Issue by pwnwriter** [hyprwm/Hyprland#3396]
### Hyprland Version

v0.29.1

### Bug or Regression?

Bug

### Description

Whenever I toggle my scratchpad or special workspace, it starts blinking. I have the following mapping:

```bash
$mainMod = SUPER
$terMinal = alacritty
$launCher = wofi

bindr = $mainMod, Grave, togglespecialworkspace, $terMinal

bindr = $mainMod_Shift, Grave, exec, [workspace special:$terMinal] $terMinal
```

### How to reproduce

Toggle on and off your scratchpads xD

### Crash reports, logs, images, videos

[recording.webm](https://github.com/hyprwm/Hyprland/assets/90331517/f061bfa8-49ee-4ced-a9a2-a543133562ca) 

If this video doesn't render, consider giving a shot [here](https://www.reddit.com/r/hyprland/comments/16p3dzc/weird_blinking_when_toggling_scratchpad_on_and/)

**Comment by vaxerski** [comment]
does this go away if you enable animations?

**Comment by pwnwriter** [comment]
It doesn't happen when i have animations enabled :)

[recording.webm](https://github.com/hyprwm/Hyprland/assets/90331517/c5c9f1b2-2c0d-42e9-93a4-7738231a0f4e)

**Comment by vaxerski** [comment]
oopsie :P
