### ISSUE TITLE
Regression: Hyprland crashes when setting (laptop) monitor to a higher than expected refresh rate

### ISSUE THREAD

**Issue by CactiChameleon9** [hyprwm/Hyprland#3397]
### Hyprland Version

v0.29.1

### Bug or Regression?

Regression

### Description

My laptop monitor/display is able to run (unofficially) at 68Hz and this has worked fine up to (at least) 91e28bbe9df85e2e94fbcc0137106362aea14ab5

Somewhere past that, Hyprland crashes on startup unless I use a normal 60Hz refresh rate

I want to make it clear that the extra 8Hz is noticeable in daily use so the setting did used to fully work

### How to reproduce

1. Set `monitor=eDP-1,1920x1080@68s,auto,1` in your `hyprland.conf` (on a laptop?)
2. Launch `Hyprland`
3. Crashes

### Crash reports, logs, images, videos

[hyprlandCrashReport63397.txt](https://github.com/hyprwm/Hyprland/files/12700436/hyprlandCrashReport63397.txt)

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12700448/hyprland.log)

**Comment by vaxerski** [comment]
IIRC this was fixed in -git

I'd also like to note that `68s` is not a valid refresh rate

**Comment by CactiChameleon9** [comment]
> IIRC this was fixed in -git
Ah, whoops. Thanks for pointing this out :)


> I'd also like to note that `68s` is not a valid refresh rate
I am not sure why that `s`... must have been a typo that still worked so I never removed it - thanks again!
