### ISSUE TITLE
problem installing in debian 12 

### ISSUE THREAD

**Issue by dexjr** [hyprwm/Hyprland#3399]
### Hyprland Version

latest

### Bug or Regression?

Bug

### Description

`ir/src/render/Texture.cpp.o CMakeFiles/Hyprland.dir/src/render/decorations/CHyprDropShadowDecoration.cpp.o CMakeFiles/Hyprland.dir/src/render/decorations/CHyprGroupBarDecoration.cpp.o CMakeFiles/Hyprland.dir/src/render/decorations/IHyprWindowDecoration.cpp.o CMakeFiles/Hyprland.dir/src/wlrunstable/wlr_ext_workspace_v1.cpp.o -o Hyprland  -Wl,-rpath,/home/ayxxn/HyprSource/HyprSource/hyprland-source/subprojects/wlroots/build
 -lxcb  -lrt  /home/ayxxn/HyprSource/HyprSource/hyprland-source/subprojects/wlroots/build/libwlroots.so.12032  -lpixman-1  -lOpenGL  -lGLESv2
 -lpthread  /home/ayxxn/HyprSource/HyprSource/hyprland-source/ext-workspace-unstable-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/wlr-foreign-toplevel-management-unstable-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/hyprland-toplevel-export-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/hyprland-global-shortcuts-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/fractional-scale-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/text-input-unstable-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/wlr-screencopy-unstable-v1-protocol.o  /home/ayxxn/HyprSource/HyprSource/hyprland-source/subprojects/udis86/build/libudis86/liblibudis86.a  /usr/lib/x86_64-linux-gnu/libwayland-server.so  /usr/lib/x86_64-linux-gnu/libwayland-client.so  /usr/lib/x86_64-linux-gnu/libwayland-cursor.so  /usr/lib/x86_64-linux-gnu/libdrm.so  /usr/lib/x86_64-linux-gnu/libEGL.so  /usr/lib/x86_64-linux-gnu/libxkbcommon.so  /usr/lib/x86_64-linux-gnu/libinput.so  /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /usr/lib/x86_64-linux-gnu/libpango-1.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libcairo.so && :
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/Compositor.cpp.o: in function
`CCompositor::initServer()':
Compositor.cpp:(.text+0xf967): undefined reference to `wlr_gles2_renderer_create_with_drm_fd'
/usr/bin/ld: Compositor.cpp:(.text+0xf9d9): undefined reference to `wlr_gles2_renderer_get_egl'
/usr/bin/ld: OpenGL.cpp:(.text+0x990a): undefined reference to `wlr_egl_get_display'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/render/Texture.cpp.o: in function `CTexture::CTexture(wlr_texture*)':
Texture.cpp:(.text+0x55): undefined reference to `wlr_texture_is_gles2'
/usr/bin/ld: Texture.cpp:(.text+0x171): undefined reference to `wlr_gles2_texture_get_attribs'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:164: release] Error 1
make[1]: Leaving directory '/home/ayxxn/HyprSource/HyprSource/hyprland-source'
make: *** [Makefile:191: install] Error 2
 NOW YOU HAVE HYPRLAND INSTALLED!!!
 Remember to add

 misc {
    suppress_portal_warnings = true
 }

to  hyprland.conf
`

### How to reproduce

wget https://gist.githubusercontent.com/Vertecedoc4545/6e54487f07a1888b656b656c0cdd9764/raw/2c5e8ccb428fc331307e2f653cab88174c051310/build-ubuntu-23.sh
chmod +x build-ubuntu-23.sh
./build-ubuntu-23.sh

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/4954f495-bd2a-4b9e-98a1-7e9ab46ff3be)
https://wiki.hyprland.org/Getting-Started/Installation/
