### ISSUE TITLE
Window Switcher / Alt-Tab functionality

### ISSUE THREAD

**Issue by ghassanyounes** [hyprwm/Hyprland#340]
So far I'm really loving this compositor! 
Having a functionality similar to gnome/windows's alt-tab feature to switch between all active windows from all workspaces would be great to see, or some sort of plugin to waybar to show a task switcher  / minimized applications

**Comment by vaxerski** [comment]
> gnome/windows's

You just described perfectly what this compositor is aiming **not** to be.

You can use `cyclenext` to cycle between windows on the same workspace and `workspace` to switch workspaces. An overview like this will not be added.
