### ISSUE TITLE
Commit fb80cb breaks follow_mouse = 2

### ISSUE THREAD

**Issue by dtop129** [hyprwm/Hyprland#3402]
### Hyprland Version

Hyprland, built from branch main at commit fb80cbe415835a7e0c64e2038d0fc56e8aba0ab4 dirty (input: properly track mouse focus on drag operations). Tag: v0.30.0

### Bug or Regression?

Regression

### Description

After latest commit, with follow_mouse = 2, when clicking on an unfocused window, the focus doesn't change.

### How to reproduce

With follow_mouse = 2, open any 2 clients and try switching focus by clicking on the unfocused one.

**Comment by vaxerski** [comment]
it's all your fault
