### ISSUE TITLE
closing-opening lid with external monitor connected crashes hyprland

### ISSUE THREAD

**Issue by Seme4eg** [hyprwm/Hyprland#3403]
### Hyprland Version

Hyprland, built from branch main at commit fb80cbe415835a7e0c64e2038d0fc56e8aba0ab4 dirty

### Bug or Regression?

Bug

### Description

Failing to setup a laptop to work with external monitor connected via HDMI. To move all workspaces on external monitor by disabling eDP-1 on lid close and on lid open move them back by turning it back on. For now to achieve it i use a script that i call on lid off and on events, screens below.

### How to reproduce

And all the times i try to open a lid after closing it with external monitor plugged in i am having either a black screen, like eDP-1 can't be enabled or straight a hyprland crash (logs attached).

### Crash reports, logs, images, videos

Crash report:
[hyprlandCrashReport10414.txt](https://github.com/hyprwm/Hyprland/files/12706372/hyprlandCrashReport10414.txt)

script that i run on open/close lid:
```bash
#!/bin/bash

state=$1

if [ "$state" == "on" ]; then
  systemctl --user restart wlsunset
  change-theme
  sync_tz_and_loc
  hyprctl keyword monitor "eDP-1,highrr,0x0,1.7"
else
  count_monitors=$(hyprctl monitors | grep -c '^Monitor')
  hyprctl keyword monitor "eDP-1, disable"
  # in order for this to work gotta have 'HandleLidSwitch=ignore' set in
  # /etc/systemd/logind.conf
  [ "$count_monitors" = 1 ] && systemctl suspend
fi
```
my bindl switch bindings:
```conf
bindl=,switch:on:Lid Switch,exec,lidhandle on
bindl=,switch:off:Lid Switch,exec,lidhandle off
```

My hyprland config directory in case that can help: https://github.com/Seme4eg/dotfiles/tree/master/.config/hypr

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12706439/patch.txt)

try this

**Comment by Seme4eg** [comment]
that did fix it, thanks! Should i close the issue?

**Comment by vaxerski** [comment]
yeah. Sorry, didn't reply in time. Glad it helped
