### ISSUE TITLE
Make Mouse buttons valid MOD-keys

### ISSUE THREAD

**Issue by inkfs** [hyprwm/Hyprland#3407]
### Description

okay, MOD-buttons, you get it. 

USE-CASE
Using mouse-buttons as MOD allow for additional mouse only actions without having to use the keyboard.

EXAMPLE
Changing volume-level with scroll-wheel while holding down a mouse button as MOD

**Comment by vaxerski** [comment]
no. mouse buttons are not mods

**Comment by tchofy** [comment]
I do it with https://github.com/sezanzeb/input-remapper, since there's an issue with libratbag/piper where extra buttons can't be mapped to ~~facebook~~ meta

**Comment by inkfs** [comment]
> I do it with https://github.com/sezanzeb/input-remapper, since there's an issue with libratbag/piper where extra buttons can't be mapped to ~facebook~ meta

I owe you 1 Internet. Thank you kind sir.
