### ISSUE TITLE
hyprctl keyword misc:cursor_zoom_factor +0.1，Suggest adding this feature to increase the size of the magnifying glass

### ISSUE THREAD

**Issue by 0a00** [hyprwm/Hyprland#3408]
### Description

hyprctl keyword misc:cursor_zoom_factor +0.1，Suggest adding this feature to increase the size of the magnifying glass
After you bind the shortcut keys, you can only change the specified magnifying factor fixedly. You want to increase the magnifying factor by something like + 0.1 for the title
thanks

**Comment by tchofy** [comment]
Idk if they'll want to add it when it can be easily scriptable with something like:
 `hyprctl keyword misc:cursor_zoom_factor $(echo "$(hyprctl getoption misc:cursor_zoom_factor -j | jq -r '.float') + 0.1" | bc)`

**Comment by 0a00** [comment]
Thanks for the advice, I am not familiar with hyprctl, this method is very good

**Comment by vaxerski** [comment]
closing then

**Comment by tchofy** [comment]
Another tip, I've noticed `misc:cursor_zoom_factor` can go all the way to roughly `-3^10x36`, so checking if the current zoom level is `> 1` before decreasing it is a good idea.

**Comment by vaxerski** [comment]
hyprland should also probably clamp the value
