### ISSUE TITLE
Game: Dota2 mouse is always centered

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#341]
step to reproduce:
1. install dota2 and start game.
2. click hero and select a hero then enter demo hero.
3. you can move your mouse but if you right click, it will always happen in center of the screen.
expected behavior: the right click happens on where the mouse is.

**Comment by vaxerski** [comment]
never played dota2, but also never noticed any right-clicks out of place. Since dota2 is running via XWayland, I'd recommend you try to launch it through gamescope.

**Comment by dragove** [comment]
I've never used gamescope. I tried running dota2 via `gamescope -h 720 -H 1080 -n -- %command%` but there is no game displayed. I can see gamescope and dota2 process in background. I've also tried running cs:s with gamescope and I can hear the sound of startup video but no display.

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Try running just `gamescope -e -- %command%` and see if it works.

**Comment by fufexan** [comment]
I can't see your recording. Firefox says it's corrupt.

**Comment by vaxerski** [comment]
> Firefox says it's corrupt.

cuz it voted for trump?

**Comment by dragove** [comment]
I don't know why firefox says it's broken, video can be played on chromium based browsers.

**Comment by Kruhlmann** [comment]
GIF version of @dragove's recording for firefox users.

![rec](https://user-images.githubusercontent.com/3380818/178477150-0bbe39b0-d202-4bca-ab5b-9183459c1d9a.gif)

**Comment by dragove** [comment]
After I installed `vulkan-intel`  and `vulkan-mesa-layers`, it goes well with param `prime-run gamescope -h 1080 -H 1080 -b -- %COMMAND%`. `prime-run` is a shell script just add environment variables for nvidia prime-offloading.

**Comment by dragove** [comment]
Update: in version `v0.18.0beta`, now mouse pointer works well without gamescope.
