### ISSUE TITLE
Blurred window does not blend correctly with background with ignore_opacity=true

### ISSUE THREAD

**Issue by WhiteBlackGoose** [hyprwm/Hyprland#3411]
### Hyprland Version

Hyprland, built from branch  at commit c8cc811e85eec16932f59fdf3783e9a6195f20f8  (). Tag: ?  flags: (if any) debug

### Bug or Regression?

Bug

### Description

So I'm not 100% sure if it's by design or not, but I didn't receive any response on the discord server so let's see.

Here's blur enabled

![image](https://github.com/hyprwm/Hyprland/assets/31178401/eeb37516-e443-4274-aded-b6ab0fabd8da)

Here's blur disabled

![image](https://github.com/hyprwm/Hyprland/assets/31178401/37d841eb-4640-4c51-9982-7da8e429794d)

The first one is noticably darker.

However, if I set `ignore_opacity=false;` in `blur` settings, then the blurred one is not dark anymore, however, it doesn't blur anything either.

(if it's by design, sorry and please let me know how to make blur not get dark while keeping it actually blurring)

### How to reproduce

The first one: set `blur` to enable and `ignore_opacity` to true.

The second one:
1. Either disable blur
2. Or enable `forcergbx`
3. Or set `ignore_opacity` to false

**Comment by WhiteBlackGoose** [comment]
I'm a dumb fuck.
```
brightness = 1.0
```
solved it

**Comment by vaxerski** [comment]
lmao that is an option that defaults to a bit less than 0, true :P
