### ISSUE TITLE
Hyprland Scroll_Lock_Button Variable not working

### ISSUE THREAD

**Issue by xllvrr** [hyprwm/Hyprland#3414]
### Hyprland Version

0.29.1-1

### Bug or Regression?

Bug

### Description

Within the variable section of Hyprland under Input, there should be an option for scroll_button_lock set to a default of 0; however when I try to change the value of this it informs me that there is no such field.

I'm not sure whether this is expected behavior (i.e. the variable itself is yet to be implemented) or whether this is a bug.

### How to reproduce

Within the hyprland.conf file, add the following line:

```
input{
...
   scroll_button_lock = 1
}

### Crash reports, logs, images, videos

_No response_

**Comment by vaxerski** [comment]
because there is no such field in your hyprland, as you're on an outdated version.

**Comment by xllvrr** [comment]
I am currently on the most up to date version 0.30-1 and it still doesn't have such a field; the same error is appearing

**Comment by vaxerski** [comment]
if you are still using the same config, there is a missing space before `{`
```
input{
```

vvv
```
input {
```

Other than that, verify your version with `hyprctl version`
