### ISSUE TITLE
Android studio emulator (AVD) does not work

### ISSUE THREAD

**Issue by nizarfadlan** [hyprwm/Hyprland#3417]
I don't know why this is, have tried setting `_JAVA_AWT_WM_NONPARENTING=1` in hyprland.conf

setting on hyprland.conf

```
env=QT_QPA_PLATFORM,"wayland;xcb"
```

error 
```
INFO    | Android emulator version 32.1.15.0 (build_id 10696886) (CL:N/A)
INFO    | Found systemPath /home/nizar/Android/Sdk/system-images/android-29/google_apis/x86/
INFO    | Storing crashdata in: /tmp/android-nizar/emu-crash.db, detection is enabled
INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
WARNING | Please update the emulator to one that supports the feature(s): Vulkan
WARNING | Failed to process .ini file /home/nizar/.android/avd/Pixel_5_API_29.avd/quickbootChoice.ini for reading.
INFO    | Warning: Could not find the Qt platform plugin "wayland" in "/home/nizar/Android/Sdk/emulator/lib64/qt/plugins" ((null):0, (null))
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
INFO    | Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
[30658:30658:20230925,175230.957073:ERROR elf_dynamic_array_reader.h:64] tag not found
[1]    30651 IOT instruction (core dumped)  ./emulator @Pixel_5_API_29
```

https://github.com/hyprwm/Hyprland/assets/40895148/35beb897-7e6d-4e69-b4cf-2d67df7bb16f

https://github.com/hyprwm/Hyprland/assets/40895148/f8cad38d-1e58-44a7-9687-d2d52a143729

**Comment by IhsFace** [comment]
I also had this issue and was able to find a solution in this post: https://stackoverflow.com/a/77142772/13463099

Try commenting out or removing the following variables from the `hyprland.conf` configuration file:

1. `env = QT_AUTO_SCREEN_SCALE_FACTOR,1`
2. `env = QT_QPA_PLATFORM,wayland`

**Comment by vaxerski** [comment]
worth noting your env keyword is wrong, no quotes should be there.

```
env = QT_QPA_PLATFORM,wayland;xcb
```

**Comment by nizarfadlan** [comment]
> worth noting your env keyword is wrong, no quotes should be there.
> 
> ```
> env = QT_QPA_PLATFORM,wayland;xcb
> ```

thank you it's solved

**Comment by neronguyenvn** [comment]
The emulator progress has terminated. Please help. I already add the above line to config.

![image](https://github.com/hyprwm/Hyprland/assets/50225603/bfdefb5f-0d50-4035-8be0-a066af50ea09)

**Comment by tryprncp** [comment]
hello, i have the same problem. why isn't this working? i put this in my hyprland.conf
