### ISSUE TITLE
Android studio cannot run emulator (AVD) 

### ISSUE THREAD

**Issue by nizarfadlan** [hyprwm/Hyprland#3418]
I don't know why this is, have tried setting `_JAVA_AWT_WM_NONPARENTING=1` in hyprland.conf

https://github.com/hyprwm/Hyprland/assets/40895148/576da3a3-e40c-4518-81cf-b50e572703bb

https://github.com/hyprwm/Hyprland/assets/40895148/4d154172-7e71-47d6-9da0-7ec14ae7976a

**Comment by TowhidMolla-Dev** [comment]
just add this line in hyprland conf file:

env = QT_QPA_PLATFORM,wayland;xcb
