### ISSUE TITLE
crash when recovering from unsafe state

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#3419]
### Hyprland Version

3b657257ecb7628a12a4fe72e733a60f031bfec2

### Bug or Regression?

Regression

### Description

Recovering from unsafe state leads to crash.

The regression was introduced in 46d66f4bcc95d9fb7fede18ad5c2c043796b9071. Issue doesn't happen before that commit.

### How to reproduce

> Turn off single monitor
> Turn it back on

### Crash reports, logs, images, videos

[hyprlandCrashReport128825.txt](https://github.com/hyprwm/Hyprland/files/12714216/hyprlandCrashReport128825.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12714291/patch.txt)

try this.

FYI this is due to you calling `hyprctl activeworkspace` in unsafe state

**Comment by andresilva** [comment]
I wasn't directly calling `hyprctl activeworkspace`, but it was being done by waybar for its workspaces module. The patch does solve the problem.

I found another issue though, Xwayland apps crash, presumably because the X connection is killed. Here's an example output:

```sh
❯ , xeyes
X connection to :0 broken (explicit kill or server shutdown).
```

**Comment by vaxerski** [comment]
interesting. Will look into, can you make another issue for that? I'll close this one by committing the patch
