### ISSUE TITLE
hyprland Crash during login

### ISSUE THREAD

**Issue by cyear** [hyprwm/Hyprland#3420]
### Hyprland Version

0.30.0.r11.3b657257-1

### Bug or Regression?

Bug

### Description

The Intel graphics card used can still be used today, but I don't know what operation is preventing it from running due to the update or other issues
The system is ArchLinux

mesa 1:23.1.8-1
I tried my best to use Google search, but it couldn't solve it

The following images are logs, lspci, and crash reports, respectively

### How to reproduce

I cannot reproduce

### Crash reports, logs, images, videos

![IMG_20230925_211322](https://github.com/hyprwm/Hyprland/assets/77969791/d1cb8ce8-fd37-4eec-88a0-bf052b0ea4a7)
![IMG_20230925_211342](https://github.com/hyprwm/Hyprland/assets/77969791/39f23820-1d8d-443e-92cb-cc9335b35673)
![IMG_20230925_211731](https://github.com/hyprwm/Hyprland/assets/77969791/0dc3200f-3a69-41f2-a5ee-93be88ea3fa7)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/cd25e2f7-821d-45f8-a8a5-202d0357368a)

not a hyprland issue

if this is an old gpu, try building with legacy_renderer

**Comment by cyear** [comment]
> ![image](https://github.com/hyprwm/Hyprland/assets/43317083/cd25e2f7-821d-45f8-a8a5-202d0357368a)
> 
> not a hyprland issue
> 
> if this is an old gpu, try building with legacy_renderer

It has been working normally recently, but it broke down yesterday. GPU is A730m，But I feel like he can't use GPU, he can only use kernel display，I can't find a good solution to this problem

**Comment by cyear** [comment]
> ![image](https://github.com/hyprwm/Hyprland/assets/43317083/cd25e2f7-821d-45f8-a8a5-202d0357368a)
> 
> not a hyprland issue
> 
> if this is an old gpu, try building with legacy_renderer

Thank you very much. Because I am missing 'llvm lbs', I can use it normally after installation. Therefore, when I installed KDE and ran the Kitty terminal, I found that llvm reported an error, which was ultimately resolved through Google search
