### ISSUE TITLE
Firefox causes keyboard focus to break

### ISSUE THREAD

**Issue by rytec-nl** [hyprwm/Hyprland#3421]
### Hyprland Version

3b657257ecb7628a12a4fe72e733a60f031bfec2

### Bug or Regression?

Bug

### Description

Seemingly at random using Firefox (and clicking?) causes the keyboard focus to disappear. I can no longer use the keyboard in any window, until I click in another window to move the focus. 

Mouse focus keeps working, so without clicking I can move the mouse to any window and mouse focus moves with it, e.g. scroll is working. I have `follow_mouse` set to `1`.

When using socat to view the output from `.socket2.sock` it outputs the `activewindow` events when moving the mouse over windows. When the keyboard focus is lost these events also stop.  

Please let me know what info is needed for debugging or ask for any other information. Thanks is advance :)

### How to reproduce

Open multiple windows side by side, including Firefox. Use Firefox for a bit, switch tabs, click around. After a short amount of time when moving the mouse over other windows the keyboard focus no longer updates.

**Comment by vaxerski** [comment]
never seen this happen. What does socket2 print _when that happens?_

**Comment by rytec-nl** [comment]
nothing at all :( the `activewindow` events that are normally there stop, and there are no other events or output generated at that moment. I did just notice that switching workspaces back and forth also restores normal behaviour.

**Comment by rytec-nl** [comment]
I figured out that killing my eww bar makes the problem go away. Looking at eww there is [this issue](https://github.com/elkowar/eww/issues/651). 

Im not quite sure why it started happening after updating Hyprland (I have not updated my eww config in a while and the issue exists since dec 2022), or why it only happens in some windows but it seems to be an eww problem, not a Hyprland problem.
