### ISSUE TITLE
The screen will be black after entering the account password,

### ISSUE THREAD

**Issue by zlgxzswjy** [hyprwm/Hyprland#3427]
### Hyprland Version

0.30

### Bug or Regression?

Bug

### Description

 installed archlinux and hyprland on my miniPC, which has only one integrated graphics card. After installation I saw the login interface, but after entering the account password displayed a black screen. I checked the log via tty4, and there were a lot of error messages in the middle, which may mean that the rendering was not successful. 

I tried hyprland hyprland-git separately. It's all like this. But when I loaded the hard drive into my ROG laptop, I also used the integrated graphics card to boot it up, and everything worked fine, logging in and using it properly. Please help me confirm what exactly is the problem? What drivers do I need to install if I want to use it on my miniPC with Intel integrated graphics

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12725800/hyprland.log)

### How to reproduce

sorry ,I don't know,This is what happens when it's started

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12725800/hyprland.log)

**Comment by zlgxzswjy** [comment]
I add a strange phenomenon, when I use DP-1 and DP-2 at the same time, the login will show a black screen, but when I use only one of the monitor, it will work normally

However, when I connect an external monitor to my laptop, both monitors work fine

**Comment by RaySlash** [comment]
@zlgxzswjy Follow the issue template properly. You need to grab logs and report. Also, set your monitor configs in your `~/.config/hypr/hyprland.conf` like this for example:
```shell
monitor = DP-1, 1920x1080@60, auto, 1
monitor = DP-2, 1920x1080@165, auto, 1
monitor = DP-3, 1920x1080@60, auto, 1

# rest of the config
```

**Comment by MightyPlaza** [comment]
please test without using a login manager (like sddm), by starting hyprland from the tty
send new logs from doing this
