### ISSUE TITLE
Nix doesn't update Hyprland

### ISSUE THREAD

**Issue by jx319** [hyprwm/Hyprland#3429]
I am using the Hyprland flake on NixOS-unstable as described in the wiki, along with `inputs.hyprland.inputs.nixpkgs.follows = "nixpkgs";`, because of [https://github.com/hyprwm/Hyprland/issues/2170](url), however changing this doesn't seem to impact the issue.

When I update my system flake with `nix flake update` it changes the rev in the lock file to the latest commit. When I then run `nixos-rebuild switch --flake .#HOSTNAME` it compiles Hyprland on the same commit. But when I then restart and run `hyprctl version` I always get the same message: 

```
$ hyprctl version
Hyprland, built from branch  at commit 4a41d013a27c9919ed41a50c43c4224d8443a415  ().
Tag: ?

flags: (if any)
debug
```

The commit there is from August 26th and it's not the one specified in the lock file or shown when rebuilding. This also has the side effect of breaking hardware acceleration because Mesa updated in the meantime but the updated Hyprland package isn't being used (though it gets compiled), so it's still the one compiled with an old version of Mesa.

**Comment by NotAShelf** [comment]
also, `inputs.hyprland.inputs.nixpkgs.follows = "nixpkgs";` hasn't been necessary for a long while

**Comment by jx319** [comment]
> sounds like you've added the flake to your inputs, but forgot to set the Hyprland module's package attribute to the one provided by the flake

you mean `programs.hyprland.package = inputs.hyprland.packages.${pkgs.system}.hyprland;` ?
I did that after the problem occured, it didn't fix it (I know I should have done it in the first place)

I had to use `inputs.hyprland.inputs.nixpkgs.follows = "nixpkgs";` just a couple of weeks ago...

**Comment by NotAShelf** [comment]
is your configuration available somewhere

**Comment by jx319** [comment]
sorry for the late answer, I managed to upload it to Github: https://github.com/jx319/nix-config
It's really messy though since I've been using NixOS for just one and a half months so be warned...

**Comment by jx319** [comment]
I found the problem in my config and fixed it.
Turns out you have to set the package for Hyprland package in home-manager as well. I don't think this is documented in the wiki.
Thanks for helping anyway! I probably wouldn't have found it if it wasn't for you..
