### ISSUE TITLE
Crash with wine/proton games

### ISSUE THREAD

**Issue by keifufu** [hyprwm/Hyprland#3433]
### Hyprland Version

Hyprland, built from branch  at commit 56adec7c1a49c079f320ba3c0c5ae3948946a9e5

### Bug or Regression?

Bug

### Description

When playing windows games, in this case on lutris with gamescope, after some time in-game my screens freeze and hyprland crashes shortly after.

#2531 looked similar, but the assertion it's failing on is different.

### How to reproduce

Play a game with proton. The crash happens at a seemingly random time.

### Crash reports, logs, images, videos

[hyprlandCrashReport2130.txt](https://github.com/hyprwm/Hyprland/files/12740188/hyprlandCrashReport2130.txt)
[hyprlandCrashReport1916.txt](https://github.com/hyprwm/Hyprland/files/12740191/hyprlandCrashReport1916.txt)

**Comment by vaxerski** [comment]
looks like a driver issue, perhaps out of vram?

**Comment by keifufu** [comment]
I'm pretty sure I wasn't running out of vram, unless gamescope is leaking some?
I've stopped using gamescope since this report and haven't had any issues yet but with these crashes being (seemingly) entirely random I'll have to give it more time and testing.

**Comment by keifufu** [comment]
Hasn't happened since I've stopped using gamescope so I'm closing this.
