### ISSUE TITLE
make install creates /usr/include/hyprland/wlroots/wlr/config.h.in when .in should be dropped

### ISSUE THREAD

**Issue by Frontear** [hyprwm/Hyprland#3434]
### Description

This is a bug in the original wlroots project, and i'm way too lazy to wait for upstream to realize it.

Essentially, when it attaches the include/ directory in the meson build from wlroots, it doesnt rename the files correctly, leaving a "config.h.in" and "version.h.in" when both should have their .in extension dropped. I figure this is a decent thing to add to the already existing "fixwlr" make task, since it would simplify building from an external perspective.

**Comment by memchr** [comment]
> This is a bug in the original wlroots project

No, the gettext files are used by meson to generate config.h, `meson install` doesn't copy them.

Essentially, when it attaches the include/ directory in the meson build from wlroots, it doesnt rename the files correctly

`make install` copies these gettext files  because in the following line, `*.h*` glob matches `*.h.in`.
```
cd subprojects/wlroots/include && find . -name '*.h*' -print0
```
This should be harmless.

**Comment by Frontear** [comment]
So are you saying its a bug in the hyprland make? Upon building I did not see a "config.h", though I did see the ".in" equivalent

**Comment by memchr** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/118117622/37e7ccdc-a871-4ff6-af92-e6e3293ea840)

**Comment by Frontear** [comment]
Fair, i'll leave the issue open in case someone else is faster, if not i'll submit a pr soon

**Comment by izmyname** [comment]
> This is a bug in the original wlroots project, and i'm way too lazy to wait for upstream to realize it.

Hyprland is no more wlroots. Should it be closed?
