### ISSUE TITLE
Cursor warps incorrectly on constraint removal if mouse did not move

### ISSUE THREAD

**Issue by teschnei** [hyprwm/Hyprland#3436]
### Hyprland Version

Hyprland, built from branch main at commit ffacd2efd1ca7fdf364a519c9d8d8644da28412b

### Bug or Regression?

Regression

### Description

When playing FFXIV, I noticed my mouse warping sporadically since around 0.29 (I don't have the exact version because there was another issue with another game that made me stay on 0.28.0 for a while).  So I added some extra logging and poked around a bit, and it seems to be because warpMouseToConstraintMiddle (being called from listener_destroyConstraint) will not have a hint set if the mouse didn't move, so it falls back to warping to the center of the game.

Expected behaviour: When releasing the mouse (which, in-game, disappears and allows rotating of the camera), the cursor should reappear wherever it was when the click was started.
Actual behaviour: If the click is released without the mouse moving, the cursor appears in the center of the game.

It could be because the hint used to be initialised to the cursor's position and isn't anymore (at least according to the hint position's comment and a bit of git history snooping), or something that was supposed to set the hint got refactored out, but I'm not sure.  I can't even be sure why the cursor warps in the first place when a constraint is removed, either.

I have no problems with making a MR to fix this, since it seems easy enough to reproduce for me, I'm just not familiar enough with the project to know what the exact issue is.  So if you can point out what you think the problem is, I can look into it more.

### How to reproduce

Play FFXIV through XIVLauncher, with the wine config set to constrain mouse to the game window (which doesn't actually work, but it does stop a weird keyboard issue), click and release mouse button without moving mouse.

**Comment by RochaLAJ** [comment]
Same...there is a manual fix but as the code base increases, it's becoming harder to apply 
You can find similar reports here: 
https://github.com/hyprwm/Hyprland/issues/1511 
https://github.com/hyprwm/Hyprland/issues/3170

For now, you can select SOFTWARE CURSOR/MOUSE in configs...you will feel a huge lag/delay but the bug won't be there.  You can also play in windows mode.

**Comment by teschnei** [comment]
Oh, it's not an ongoing issue for myself, since I just removed the warp entirely for myself locally.  I just want to figure out how to fix it properly for upstream.

**Comment by RochaLAJ** [comment]
> Oh, it's not an ongoing issue for myself, since I just removed the warp entirely for myself locally. I just want to figure out how to fix it properly for upstream.

Sorry, perhaps i got it wrong. In my case, any attempt to fix worked...but i got lazy and now i just deal with it the way  i described before. I am curious to know why previous attempts did not work upstream.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12748833/patch.txt)

try this patch.

**Comment by teschnei** [comment]
Tested FFXIV and Hunt: Showdown with the patch, I haven't found any issues. Looks good

**Comment by zanarknd** [comment]
Hi. This issue reproduces on 0.41.2 and current main [be2dfa3](https://github.com/hyprwm/Hyprland/commit/be2dfa36ef635add2d55c96f7616ec61b96e7bb1) in FFXIV and WoW.

I've been able to isolate it to this function https://github.com/hyprwm/Hyprland/blob/main/src/managers/input/InputManager.cpp#L115-L120

Attached patch fixes it for me by disabling `CInputManager::simulateMouseMovement` if `cursor.no_warps` is set. I don't have cpp experience to make a proper pr, but hope this helps.
[patch.txt](https://github.com/user-attachments/files/16474931/patch.txt)

**Comment by vaxerski** [comment]
yea thats not a good fix xd

**Comment by activaigor** [comment]
for somebody using QMK keyboards, the quick and easy hack would be to implement a switch-workspace + register_code(KC_MS_DOWN) to move cursor just a little bit so it will sync it's actual position with a virtual one, that hyprland provides
