### ISSUE TITLE
Swiping to second workspace makes first disappear

### ISSUE THREAD

**Issue by pinnouse** [hyprwm/Hyprland#3437]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty ().

### Bug or Regression?

Bug

### Description

Swiping from first workspace to 2nd makes all apps on first workspace disappear. The apps are still active and I can keep creating new apps (I swipe to workspace 2 then back and I see the new apps I started are laid out properly), the workspace just seems to go invisible.

### How to reproduce

Be on first workspace with gestures enabled to swipe to change workspaces. Swipe to second wokrspace halfway then back, all apps have disappeared.

**Comment by vaxerski** [comment]
can I get a video and config? Can't repro

**Comment by pinnouse** [comment]
https://github.com/hyprwm/Hyprland/assets/11915698/99f55a94-1e03-4aaa-9c07-38fa9b30e589

in the video, I created some more windows on ws 1 while they were invisible so I suspect everything is still active, it just doesn't show.

if this is helpful: I'm on i7 Dell XPS 15 9560 running from only iGPU.

and config

```
monitor=eDP-1,1920x1080@60,0x0,1
#monitor=HDMI-A-1,1920x1080@60,0x0,
monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1
monitor=,preferred,auto,1

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=1
}

general {
    sensitivity=1.0 # for mouse cursor

    gaps_in=5
    gaps_out=10
    border_size=2
    col.active_border=0x6611eeee
    col.inactive_border=0x66333333

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
}

decoration {
    rounding=6
    active_opacity=0.97
    inactive_opacity=0.7
    drop_shadow=0
    shadow_range=12
    shadow_render_power=2
    col.shadow=0xd82e30-3b
    blur {
        size=8
        passes=1
        ignore_opacity=true
    }
}

bezier=easeOut,0.16,1,0.3,1

animations {
    enabled=1
    animation=windows,1,3,default
    animation=border,1,6,default
    animation=fadeIn,1,2,default
    animation=fadeOut,1,2,default
    # animation=workspaces,1,3,easeOut
    animation=workspaces,1,2,easeOut,slidefade 20%
}


input {
    force_no_accel=1

    touchpad {
        natural_scroll=1
      	tap-to-click=1
        scroll_factor=0.7
    }
}

gestures {
    workspace_swipe=1
    workspace_swipe_min_speed_to_force=60
    workspace_swipe_create_new=true
    workspace_swipe_forever=false
    workspace_swipe_numbered=true
}

misc {
    disable_hyprland_logo=1
    disable_splash_rendering=1
    vfr=1
    focus_on_activate=0
#    no_vfr=0
#    animate_manual_resizes=true
}

debug {
    #overlay=1
}

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

# example window rules
# for windows named/classed as abc and xyz
windowrule=workspace 5 silent,^(discord)$
#windowrulev2=noinitialfocus,class:(discord)
windowrule=float,^(zoom)$
windowrulev2=move onscreen 20 80,class:^(jetbrains-toolbox)$
windowrulev2=maxsize 640 360,title:^(Picture-in-Picture)$
windowrulev2=nofocus,title:(im-emoji-picker)
windowrulev2=opaque,title:(im-emoji-picker)

# LMB -> 272, RMB -> 273
bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

bind=SUPER,RETURN,exec,alacritty
bind=SUPER,Q,killactive,
bind=SUPER,M,exit,
bind=SUPER,V,togglefloating,
bind=SUPER,space,exec,pkill wofi; wofi --show drun -I -o DP-3
bind=SUPER,P,pseudo,

bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r
bind=SUPER,k,movefocus,u
bind=SUPER,j,movefocus,d

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5

bind=SUPER,u,workspace,e-1
bind=SUPER,o,workspace,e+1

bind=ALT,1,movetoworkspacesilent,1
bind=ALT,2,movetoworkspacesilent,2
bind=ALT,3,movetoworkspacesilent,3
bind=ALT,4,movetoworkspacesilent,4
bind=ALT,5,movetoworkspacesilent,5
#bind=ALT,6,movetoworkspacesilent,6
#bind=ALT,7,movetoworkspacesilent,7
#bind=ALT,8,movetoworkspacesilent,8
#bind=ALT,9,movetoworkspacesilent,9
#bind=ALT,0,movetoworkspacesilent,10

# sets repeatable binds for resizing the active window
binde=SUPER_ALT,right,resizeactive,10 0
binde=SUPER_ALT,left,resizeactive,-10 0
binde=SUPER_ALT,up,resizeactive,0 -10
binde=SUPER_ALT,down,resizeactive,0 10

bind=SUPER_SHIFT,S,exec,grim -g "$(slurp)" - | wl-copy

binde=,xf86monbrightnessup,exec,brightnessctl s +5%
binde=,xf86monbrightnessdown,exec,brightnessctl s 5%-


binde=,XF86AudioRaiseVolume, exec, amixer set Master 1%+
binde=,XF86AudioLowerVolume, exec, amixer set Master 1%-

blurls=waybar
blurls=gtk-layer-shell
blurls=eww
blurls=wofi
layerrule=ignorezero,wofi

# Startup
source=~/.config/hypr/startups.conf
```

startup conf:

```
exec-once=hyprpaper
exec-once=discord
exec-once=eww daemon && eww open topbar
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=scripts/battery.sh
#exec-once=waybar
exec-once=dunst
exec-once=fcitx5 -d
```

**Comment by vaxerski** [comment]
idk why onions fly, but I can't repro this even with your gestures config. Odd.

**Comment by pinnouse** [comment]
> idk why onions fly,

ref: https://youtu.be/StXA0C8KW1A?si=0eXacLnEBjeu1qVi

> Can you try on -git?

Issue no longer exists on hyprland-git :smile: sorry for the trouble. I have a massive appreciation of dedication to the making and maintaining of this incredible project! Thank you!

**Comment by pinnouse** [comment]
Reopening since bug seems to still persist. It appears that it only happens when there is something open on the workspace I'm swiping to (the second one) that the apps on the first disappear.

**Comment by Filz0r** [comment]
I can confirm that this also happens on Arch Linux on an Thinkpad T480S using an Intel iGPU, it has been like this for a long time, but in my case it happens more often when I am plugged into an external monitor, I thought this was because I have my first 5 workspaces binded to my laptop display and I usually move the workspace I have configured to run my IDE up to this external monitor and leave workspace 1 and 2 on the internal monitor and sometimes when I'm moving these workspaces and I swipe one to many times causing the workspace 3 that is on the external monitor to stop rendering the window that is open.

Here is how I set the rules for workspaces:
workspace=eDP-1, 1, gapsin:2, gapsout:2
workspace=eDP-1, 2
workspace=eDP-1, 3
workspace=eDP-1, 4
workspace=eDP-1, 5
workspace=HDMI-A-2, 6
workspace=HDMI-A-2, 7
workspace=HDMI-A-2, 8
workspace=HDMI-A-2, 9
workspace=HDMI-A-2, 0

And here is my gestures configuration:
gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = on
    workspace_swipe_fingers = 3
    workspace_swipe_numbered = true 
}

I can try and see if this is related to Intel iGPU or if it also happens on AMD dGPU later this month if it helps

**Comment by burgerindividual** [comment]
To provide more reproducibility info, I'm fairly confident that this only happens when `workspace_swipe_numbered=true` and the second workspace already exists/there is at least one window on it.

**Comment by Rishabh672003** [comment]
yup @burgerindividual is correct, I can confirm using with the latest git-commit, when `workspace_swipe_numbered` is set to true, this issue happens

**Comment by TanawatJukmongkol** [comment]
also happens with `swipe_use_r`

**Comment by romanstingler** [comment]
can someone test this? 
haven't seen it for a very long time

**Comment by Rishabh672003** [comment]
@romanstingler nope havent seen this in a very long time now, this issue should be close now
