### ISSUE TITLE
Bind workspace to multiple monitors

### ISSUE THREAD

**Issue by alexmo1997** [hyprwm/Hyprland#3438]
### Description

I have a setup with an external dock that is connected to two monitors. When I connect them, they sometimes get added as DP-5 and DP-6 and sometimes as DP-7 and DP-8. I have found no way to prevent this, so I would like to be able to bind a workspace to both DP-5 and DP-7 (prioritize DP-5 if both were to exist I guess).

**Comment by vaxerski** [comment]
that's unfortunately an issue with your driver.

Why can't you use `desc:`?

**Comment by alexmo1997** [comment]
Right, I didn't see that in the docs, thank you, that solves my issue.
However, I still think this could be a good addition, for instance if I have a deck at home and at work with different monitors but still would want the same configuration.

**Comment by vaxerski** [comment]
it doesn't make much sense and would imo introduce more confusion than good
