### ISSUE TITLE
Ulauncher prevents focus changes

### ISSUE THREAD

**Issue by Chr1s70ph** [hyprwm/Hyprland#3440]
### Hyprland Version

Hyprland, built from branch main at commit 6d7dc70f663891ef39dcfb8ba8e5ff643b4d9ed8 dirty (input: Add map to region options for tablets (3425)). Tag: v0.30.0-13-g6d7dc70f

### Bug or Regression?

Bug

### Description

When starting ulauncher, the mouse is not able to change focus on other windows.
Additionally after launching an application with ulauncher, the focus is not set on the newly opened application, and ulauncher remains in focus.

This does work in Sway and even in i3. 

### How to reproduce

Start Hyprland
run `ulauncher`
Select Application
Be amazed that ulauncher stays open

### Hyprland minimal config

```config
# Some default env vars.
env = XCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GB_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = XDG_SESSION_DESKTOP,Hyprland

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = master

    no_focus_fallback = true
}

master {
# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = false
    allow_small_split = yes
    orientation = center
    mfact = 0.5
}

misc {
   focus_on_activate = true
   disable_hyprland_logo = true
   allow_session_lock_restore = false
   no_direct_scanout = true
   vrr = 0
}


$lock = swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5 --effect-vignette 0.5:0.5 --ring-color 192330 --key-hl-color 9d79d6 --line-color 000000 --separator-color 000000 --datestr "%a %e.%m.%Y" --timestr "%k:%M" --fade-in 0.1

# Applications to run when starting Hyprland
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = blueman-applet
exec-once = env GDK_BACKEND=$XDG_SESSION_TYPE ulauncher --no-window
exec-once = copyq --start-server
exec-once = hyprctl setcursor Fluent-cursors 16
exec-once = nm-applet --indicator
exec-once = swaybg -i ~/.config/hypr/images/wallpaper -m fillS
exec-once = swayidle lock '$lock' 
exec-once = thunar --daemon 
exec-once = waybar 

bind = $mainMod, D, exec, gapplication launch io.ulauncher.Ulauncher
```

**Comment by FakeMichau** [comment]
Is that still an issue? If so, could you provide your config file?

**Comment by Chr1s70ph** [comment]
Sadly it does not.
I'm not quite sure if this is a hyprland problem or not, since [albert](https://github.com/albertlauncher/albert) is working just fine...

My config is fairly comprehensive, so I won't post stuff like binds.

**Comment by izmyname** [comment]
Bump. Does it still happen?

**Comment by Chr1s70ph** [comment]
Since I no longer use Hyprland or Ulauncher, I cannot confirm this.
However, since this issue didn't drive any traffic, I assume this isn't relevant.
