### ISSUE TITLE
create binds with non-mod-keys only.

### ISSUE THREAD

**Issue by chloecdn** [hyprwm/Hyprland#3446]
### Description

I have a very stupid mini-keyboard, not allowing me to rebind keys in any way, so i have to rely 100% on external software to do that. So i currently had my right menu key + f9-f11 bound to my media keys (because fn does not have that functionality).

Is there any way to bind for example menu + f10? because from what ive seen, only specific keys (like super, alt, etc) can be used for that. What i intend is using something like `bind = , menu ssharp, exec, playerctl play-pause`.

**Comment by chloecdn** [comment]
Found a way for this, using an external tool.

**Comment by tchofy** [comment]
There's a good chance it was https://github.com/sezanzeb/input-remapper.

**Comment by chloecdn** [comment]
Sorry for not answering, my github mail notifications are doing all kinds of shenanigans at the moment.

It was this one: https://github.com/rvaiya/keyd

All i did in my case was just remapping the menu key ("compose" apparently) to "super", because it doesnt seem like keyd can work with actual key **combinations**
