### ISSUE TITLE
no documentation for creating layout monocle (or how do this behavior), need examples.

### ISSUE THREAD

**Issue by neuromagus** [hyprwm/Hyprland#3447]
### Hyprland Version

0.30

### Bug or Regression?

Bug

### Description

'inherit_fullscreen' in Master layout not worked. Or behavior is not correct (in Wiki docs).
I want expect monocle mode (fullscreen for this workspace or default behavior on all Hyprland).

inherit_fullscreen = true - nothing...

### How to reproduce

just use default example conf and add this option in Master section.

Hypr, if I not wrong, inheritance behavior from Xmonad, DWM and another tiled WMs, so, I expect monocle mode...

P.S. Sorry for my terrible english.

**Comment by vaxerski** [comment]
there is no documentation for monocle because there is no monocle.

What you can do is fullscreen a window and use `focuswindow` with `l/r` to cycle between windows
