### ISSUE TITLE
compositor crash on wakup from sleep

### ISSUE THREAD

**Issue by Seme4eg** [hyprwm/Hyprland#3448]
### Hyprland Version

 built from branch main at commit ffacd2efd1ca7fdf364a519c9d8d8644da28412b dirty

### Bug or Regression?

Bug

### Description

crash on wakeup from sleep

### How to reproduce

Have same setup and dotfiles as i do and try to go to sleep and out :
                           
OS: Arch Linux x86_64                      
Kernel: 6.5.4-arch2-1                      
Uptime: 16 hours, 12 mins                  
Packages: 958 (pacman)                     
Shell: zsh 5.9                             
Resolution: 3440x1440                      
DE: Hyprland                               
WM: sway                                   
Theme: Adwaita [GTK2], Arc [GTK3]          
Icons: Adwaita [GTK2], Numix-Circle [GTK3] 
Terminal: foot                             
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz      
GPU: NVIDIA GeForce RTX 2060 Rev. A        
Memory: 5991MiB / 15922MiB                 

### Crash reports, logs, images, videos

[hyprlandCrashReport869.txt](https://github.com/hyprwm/Hyprland/files/12762440/hyprlandCrashReport869.txt)

my dots with hyprland config files: https://github.com/seme4eg/dotfiles

**Comment by tchofy** [comment]
Just for sanity checking:

If you're on the `nvidia-open` driver, [suspend/wakeup is currently broken if PreserveVideoMemoryAllocations is enabled](https://github.com/NVIDIA/open-gpu-kernel-modules/issues/472), which seems to be necessary to avoid crashes on wakeup depending on the amount of vram currently being consumed.

Also services `nvidia-suspend`, `nvidia-resume` and `nvidia-hibernate` need to be enabled (disabled by default).

**Comment by Seme4eg** [comment]
well, no, i had nvidia-dkms and i didn't have those services enabled (that wasn't stated neither in nvidia arch wiki nor in hyprland wiki). But i installed nvidia-open-dkms, enabled those services and still get the same problem (rebooted ofc). Here is a new crash log:

[hyprlandCrashReport900.txt](https://github.com/hyprwm/Hyprland/files/12763982/hyprlandCrashReport900.txt)

**Comment by vaxerski** [comment]
to me looks like an nvidia issue if anything

**Comment by tchofy** [comment]
Use nvidia-dkms, the open drivers are the ones that are broken, then enable
the services (just enable, they're started by systemd on
sleep/hibernate/resume).

**Comment by Seme4eg** [comment]
adding this kernel parameter did help indeed, maybe worth adding to nvidia documentation page?

**Comment by tchofy** [comment]
Eh, sure, I'm not very familiar with pull requests and I'm not a good writer, but here's my attempt: https://github.com/hyprwm/hyprland-wiki/pull/359

**Comment by FatngatirBilek** [comment]
> Use nvidia-dkms, the open drivers are the ones that are broken, then enable the services (just enable, they're started by systemd on sleep/hibernate/resume). Edit: Also add `nvidia.NVreg_PreserveVideoMemoryAllocations=1` to your kernel parameters if you haven't already.

kernel parameter?? is it the modprobe thing??
