### ISSUE TITLE
Popups in IntelliJ Idea break input

### ISSUE THREAD

**Issue by pshirshov** [hyprwm/Hyprland#3450]
### Hyprland Version

88b63a00b68350d6d001445357a2582ab5975f9c

### Bug or Regression?

Regression

### Description

Something has been broken recently with IntelliJ intellisense popups. They start stealing focus from the main window thus breaking keyboard input.

### How to reproduce

1. Install IntelliJ Idea
2. Create a project in any language
3. Start typing and make the intellisense popup appear
4. The main intellij window will lose the focus regardless of `input:follow_mouse` and mouse position. So it won't be possible to continue typing or to select anything in the popup using the keyboard
5. You would have to manually refocus main window

**Comment by pshirshov** [comment]
This looks like https://github.com/hyprwm/Hyprland/issues/3012 but it worked for me before

**Comment by pshirshov** [comment]
Suggested fix (`windowrulev2 = noborder, class:^(jetbrains-idea)(.*)$`) does not help.

**Comment by pshirshov** [comment]
It seems like this helps:

```
input {
  follow_mouse = 2
  float_switch_override_focus = 0
}
```

**Comment by pshirshov** [comment]
Currently I'm using the following rules which make the editor barely usable:

```
input {
  float_switch_override_focus=0
  follow_mouse=2
  mouse_refocus=1
}

xwayland {
  force_zero_scaling=true
}
windowrulev2 = noinitialfocus,class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = noborder, class:^(jetbrains-idea)(.*)$
```

Unfortunately the "noinitialfocus" rule completely breaks the menus: 

[idea-menus.webm](https://github.com/hyprwm/Hyprland/assets/295225/7310d67c-081d-4183-aa39-426b04882cee)

Moreover, `noinitialfocus` is not a reliable fix, it's just makes things better. The editor still loses focus from time to time.

**Comment by Blackburn29** [comment]
@pshirshov These are my window rules which fix a bunch of issues I've come across. These focus issues are related to xwayland applications running under wl-roots as the same problems happen in Sway as well.

```
# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrulev2 = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

#! Center popups/find windows
windowrulev2 = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Disable window flicker when autocomplete or tooltips appear
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1
```

Also add `suppress.focus.stealing=false` to your IDE properties.


I should mention that these do not "fix" everything. In my case, using a multi monitor setup will cause popups to open where ever they want sometimes. But at least the editor focus issues are fixed

**Comment by pshirshov** [comment]
Menus rendering remains broken with these properties.

**Comment by Blackburn29** [comment]
The biggest issue I have now is that the autocomplete popup rendering has been broken since 0.30 in hyprland. The key to the focus issues with the editor is the windowdance rule though

**Comment by liperium** [comment]
> The biggest issue I have now is that the autocomplete popup rendering has been broken since 0.30 in hyprland.

Same here, do you have any recommended fixes for now? It seems that the window size is fine, it's the inner rendering of it?

**Comment by onyasumi** [comment]
@Blackburn29's fixes seems to fix an issue with IntelliJ's New UI that causes unusable flickering when hovering over the left sidebar buttons.

See here for a demo of someone else having a similar problem in action
https://youtrack.jetbrains.com/issue/RIDER-103759

@vaxerski is there any way we can make these settings default, in the Hyprland sample config, or at the very least, document this in the wiki?

**Comment by onyasumi** [comment]
> Currently I'm using the following rules which make the editor barely usable:
> 
> ```
> input {
>   float_switch_override_focus=0
>   follow_mouse=2
>   mouse_refocus=1
> }
> 
> xwayland {
>   force_zero_scaling=true
> }
> windowrulev2 = noinitialfocus,class:^(jetbrains-.*),title:^(win.*)
> windowrulev2 = noborder, class:^(jetbrains-idea)(.*)$
> ```
> 
> Unfortunately the "noinitialfocus" rule completely breaks the menus:
> idea-menus.webm
> 
> Moreover, `noinitialfocus` is not a reliable fix, it's just makes things better. The editor still loses focus from time to time.

`noinitialfocus` doesnt break the menu with the new jetbrains UI. `nofocus` meanwhile breaks things like the search popup, or the new file popup. At least in the new UI.

**Comment by KAGEYAM4** [comment]
> Also add suppress.focus.stealing=false to your IDE properties.

Can someone please tell how/where to add this ?

I went through these but it's still confusing ->
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206874755-Don-t-steal-focus?page=3#community_comment_115000586044
https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties
https://developer.android.com/studio/intro/studio-config.html#customize_ide

I am using android-studio

**Comment by nizarfadlan** [comment]
> @pshirshov These are my window rules which fix a bunch of issues I've come across. These focus issues are related to xwayland applications running under wl-roots as the same problems happen in Sway as well.
> 
> ```
> # -- Fix odd behaviors in IntelliJ IDEs --
> #! Fix focus issues when dialogs are opened or closed
> windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
> #! Fix splash screen showing in weird places and prevent annoying focus takeovers
> windowrulev2 = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
> windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
> windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
> 
> #! Center popups/find windows
> windowrulev2 = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
> windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
> windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
> #! Disable window flicker when autocomplete or tooltips appear
> windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1
> ```
> 
> Also add `suppress.focus.stealing=false` to your IDE properties.
> 
> I should mention that these do not "fix" everything. In my case, using a multi monitor setup will cause popups to open where ever they want sometimes. But at least the editor focus issues are fixed

How to fix, popup in android studio not clickable after unfocused from input
https://github.com/hyprwm/Hyprland/assets/40895148/800dcaad-e3c5-4d4d-9645-c35011c3e0fe

**Comment by pshirshov** [comment]
I've tried a lot of similar things, in the end I've given up on Hyprland for now.

**Comment by mindrunner** [comment]
switching to experimental native wayland with jbr pre-release solves many of those issues

**Comment by liperium** [comment]
For the people using Android Studio, I think the Canary channel has fixes. Will report back, but the popups and autocomplete seem to work fine without any tweaks for now.

**Comment by kamssiopeia** [comment]
> switching to experimental native wayland with jbr pre-release solves many of those issues

Could you please instruct me on how to do it?

**Comment by reinux** [comment]
With the beta runtime and the Hyprland config changes, for me, it's gone from crashing outright to just hanging for 10+ seconds half the time when I try to rename an identifier and working fine the other half.

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

**Comment by MightyPlaza** [comment]
OP doesn't seem to still use hyprland, has this been fixed?

**Comment by Blackburn29** [comment]
> OP doesn't seem to still use hyprland, has this been fixed?

Use the latest jbr21 with the WLToolkit flag enabled in the IDE.

**Comment by kamssiopeia** [comment]
> OP doesn't seem to still use hyprland, has this been fixed?

I use latest hyprland and intellij version and everything seems to work perfectly. Even coursor being "stuck" is fixed for me now

**Comment by MightyPlaza** [comment]
alr thx
@vaxerski

**Comment by matejdro** [comment]
Unfortunately, WLToolkit mode seems to cause some weird scaling issues with some popups, which makes them nearly unusable: https://youtrack.jetbrains.com/issue/JBR-8356

Because of this I switched back to XWayland + all of above workarounds to have at least use-able experience. Thanks for everybody for providing those workarounds!

**Comment by manuel3053** [comment]
In mi config I put the following lines and everything seems to work just fine:
`windowrulev2 = noinitialfocus, class:jetbrains-toolbox, floating:0
windowrulev2 = noinitialfocus, class:(jetbrains-)(.*), floating:0
windowrulev2 = noinitialfocus, class:(jetbrains-)(.*), title:^$, initialTitle:^$, floating:0
windowrulev2 = center, class:(jetbrains-)(.*), initialTitle:(.+), floating:0
windowrulev2 = center, class:(jetbrains-)(.*), title:^$, initialTitle:^$, floating:0
windowrulev2 = noinitialfocus, class:(jetbrains-) (.*), title:^win(.*), initialTitle:win.*, floating:0
`

**Comment by thisismeamir** [comment]
Is this issue solved? 
I've failed to solve this problem using codes here. which one is the final solution?

**Comment by fubuki4649** [comment]
> Is this issue solved? I've failed to solve this problem using codes here. which one is the final solution?

You can take a look at my dotfiles [here](https://github.com/fubuki4649/dotfiles/blob/master/.config/hypr/hyprland.conf)

IntelliJ has gotten alot better on Wayland in general in recent years. XWayland works pretty much flawlessly and Native Wayland works good enough too.

**Comment by matejdro** [comment]
For the XWayland IntelliJ, https://github.com/hyprwm/Hyprland/discussions/10332 is the showstopper for me as I cannot copy paste large code blocks around without things freezing.
