### ISSUE TITLE
CANT USE my nvidia gpu HDMI PORT ON HYPRLAND

### ISSUE THREAD

**Issue by SteavenGamerYT** [hyprwm/Hyprland#3451]
### Hyprland Version

NEWEST

### Bug or Regression?

Bug

### Description

can someome please  patch hyprland with this patch?
here is the patch urls for gnome and kde
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3304
https://invent.kde.org/plasma/kwin/-/merge_requests/4177 

### How to reproduce

GET GAMING LAPTOP with IGPU that is intel UHD and nvidia gpu that is wired to hdmi port 
and that laptop should have no MUX SWITCH for the main gpu to be intel uhd and secnderoy to be nvidia

**Comment by vaxerski** [comment]
newest is not a version

We cannot patch hyprland with those patches as they are for kde and gnome

Nvidia is not supported

No need to yell
