### ISSUE TITLE
Crashing After Upgrading from ffacd2ef to 9cc614d09

### ISSUE THREAD

**Issue by sl33nyc** [hyprwm/Hyprland#3452]
### Hyprland Version

9cc614d09

### Bug or Regression?

Bug

### Description

Hyprland crashes after login.

### How to reproduce

I did a `yay -Syu` which upgraded Hyprland to HEAD.  Afterwards, Hyprland refused to start after login even after reboot.

### Crash reports, logs, images, videos

[hyprlandCrashReport3453.txt](https://github.com/hyprwm/Hyprland/files/12768686/hyprlandCrashReport3453.txt)

**Comment by vaxerski** [comment]
I fixed that within 12 mins lol 27cd7ef0c94f3dc2d2038520da8d95063ae7f2a9
