### ISSUE TITLE
Hyprland crash randomly

### ISSUE THREAD

**Issue by gmr458** [hyprwm/Hyprland#3461]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f  (). Tag: v0.30.0  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Hyprland crash

### How to reproduce

I don't know, it just happens, I still haven't found a pattern.

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
I tried so hard, and got so far...

Hyprland received signal 11 (Segmentation fault)

Version: 1b48642fd15c433c53876f1b933dcd46265caf8f
Tag: v0.30.0

System info:
	System name: Linux
	Node name: fedora
	Release: 6.5.5-200.fc38.x86_64
	Version: #1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])

os-release:
	NAME="Fedora Linux"
	VERSION="38 (Workstation Edition)"
	ID=fedora
	VERSION_ID=38
	VERSION_CODENAME=""
	PLATFORM_ID="platform:f38"
	PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
	ANSI_COLOR="0;38;2;60;110;180"
	LOGO=fedora-logo-icon
	CPE_NAME="cpe:/o:fedoraproject:fedora:38"
	DEFAULT_HOSTNAME="fedora"
	HOME_URL="https://fedoraproject.org/"
	DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
	SUPPORT_URL="https://ask.fedoraproject.org/"
	BUG_REPORT_URL="https://bugzilla.redhat.com/"
	REDHAT_BUGZILLA_PRODUCT="Fedora"
	REDHAT_BUGZILLA_PRODUCT_VERSION=38
	REDHAT_SUPPORT_PRODUCT="Fedora"
	REDHAT_SUPPORT_PRODUCT_VERSION=38
	SUPPORT_END=2024-05-14
	VARIANT="Workstation Edition"
	VARIANT_ID=workstation
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x69) [0x5647ae860d89]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x6ba) [0x5647ae80055a]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x48) [0x5647ae8d40b8]
		??
		??:0
	#3 | /lib64/libc.so.6(+0x3dbb0) [0x7f1e6e97ebb0]
		??
		??:0
	#4 | Hyprland(+0xf9401) [0x5647ae7f8401]
		??
		??:0
	#5 | /lib64/libwayland-server.so.0(+0xc791) [0x7f1e6f4c0791]
		??
		??:0
	#6 | /lib64/libwayland-server.so.0(wl_client_destroy+0xab) [0x7f1e6f4c0f2b]
		??
		??:0
	#7 | /lib64/libwayland-server.so.0(+0xd4b8) [0x7f1e6f4c14b8]
		??
		??:0
	#8 | /lib64/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7f1e6f4c08e2]
		??
		??:0
	#9 | /lib64/libwayland-server.so.0(wl_display_run+0x35) [0x7f1e6f4c1125]
		??
		??:0
	#10 | Hyprland(main+0x803) [0x5647ae7b1f13]
		??
		??:0
	#11 | /lib64/libc.so.6(+0x27b8a) [0x7f1e6e968b8a]
		??
		??:0
	#12 | /lib64/libc.so.6(__libc_start_main+0x8b) [0x7f1e6e968c4b]
		??
		??:0
	#13 | Hyprland(_start+0x25) [0x5647ae7bf465]
		??
		??:0

Log tail:
[LOG] Removing last node (dwindle)
[LOG] On closed window, new focused candidate is [Window nullptr]
[LOG] Destroying the SubSurface tree of unmapped window [Window 5647b0802a80: title: "Alacritty"]
[LOG] Callback 5647b0857138 -> 5647b0857130, SurfaceTreeNode removed.
[LOG] Callback 5647b08571a0 -> 5647b0857198, SurfaceTreeNode removed.
[LOG] Callback 5647b08570d0 -> 5647b08570c8, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 5647b08030c0 -> 5647b08030b8, Toplevel removed.
[LOG] Callback 5647b0803058 -> 5647b0803050, Toplevel removed.
[LOG] Callback 5647b0803128 -> 5647b0803120, Toplevel removed.
[LOG] Callback 5647b08032d0 -> 5647b08032c8, CWLSurface removed.
[LOG] CWLSurface 5647b08032a0 called destroy()
[LOG] Callback 5647b0802b78 -> 5647b0802b70, CWindow removed.
[LOG] [Window 5647b0802a80: title: "Alacritty", class: ] destroyed, queueing.
[LOG] Callback 5647b0802b10 -> 5647b0802b08, XDG Window removed.
[LOG] Callback 5647b0802be0 -> 5647b0802bd8, XDG Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Keybind triggered, calling dispatcher (64, , 52)
[LOG] Set keyboard focus to surface 5647b07e8f30, with [Window 5647b0808cb0: title: "Alacritty"]
[LOG] Destroying workspace ID 3
[LOG] Cleanup: destroyed a window
[LOG] Keybind triggered, calling dispatcher (64, , 99)
[LOG] [Window 5647b0808cb0: title: "Alacritty", class: Alacritty] unmapped
[LOG] Unregistered late callbacks XDG
[LOG] Callback 5647b0808cd8 -> 5647b0808cd0, XDG Window Late removed.
[LOG] Callback 5647b0808e78 -> 5647b0808e70, XDG Window Late removed.
[LOG] Callback 5647b0808fb0 -> 5647b0808fa8, XDG Window Late removed.
[LOG] Callback 5647b08090e8 -> 5647b08090e0, XDG Window Late removed.
[LOG] Callback 5647b0809080 -> 5647b0809078, XDG Window Late removed.
[LOG] Callback 5647b0809018 -> 5647b0809010, XDG Window Late removed.
[LOG] Callback 5647b0809150 -> 5647b0809148, XDG Window Late removed.
[LOG] Callback 5647b0808f48 -> 5647b0808f40, XDG Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] Removing last node (dwindle)
[LOG] On closed window, new focused candidate is [Window nullptr]
[LOG] Destroying the SubSurface tree of unmapped window [Window 5647b0808cb0: title: "Alacritty"]
[LOG] Callback 5647b08014a8 -> 5647b08014a0, SurfaceTreeNode removed.
[LOG] Callback 5647b0801510 -> 5647b0801508, SurfaceTreeNode removed.
[LOG] Callback 5647b0801440 -> 5647b0801438, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 5647b08092f0 -> 5647b08092e8, Toplevel removed.
[LOG] Callback 5647b0809288 -> 5647b0809280, Toplevel removed.
[LOG] Callback 5647b0809358 -> 5647b0809350, Toplevel removed.
[LOG] Callback 5647b0809500 -> 5647b08094f8, CWLSurface removed.
[LOG] CWLSurface 5647b08094d0 called destroy()
[LOG] Callback 5647b0808da8 -> 5647b0808da0, CWindow removed.
[LOG] [Window 5647b0808cb0: title: "Alacritty", class: ] destroyed, queueing.
[LOG] Callback 5647b0808d40 -> 5647b0808d38, XDG Window removed.
[LOG] Callback 5647b0808e10 -> 5647b0808e08, XDG Window removed.
[ERR] onWindowRemovedTiling node null?

**Comment by vaxerski** [comment]
> I don't know, it just happens, I still haven't found a pattern.

then what do you want me to do about this

**Comment by gmr458** [comment]
Sorry, I thought the crash report would have useful information, if you want, close this.

**Comment by vaxerski** [comment]
they usually do, but this one doesn't. It's unfortunately an equivalent of "oops something went wrong lol"

If you can repro, or it occurs often, feel free to come back
