### ISSUE TITLE
Not being able to drag sliders on blender with pen tablet

### ISSUE THREAD

**Issue by Izaird** [hyprwm/Hyprland#3468]
### Hyprland Version

v0.30.0-29-g7b002d60

### Bug or Regression?

Bug

### Description

while using a pen tablet(xp pen deco pro medium)  I'm not able to hold and drag sliders on blender

https://github.com/hyprwm/Hyprland/assets/31055847/d8d0511a-bf16-462e-aca5-b639102d795b

Expected behavior on Sway:

https://github.com/hyprwm/Hyprland/assets/31055847/524c36b8-2189-4ed3-a32a-ee52270893b8

### How to reproduce

Launch blender
Hold and drag a slider with a pen tablet

**Comment by Estebiu** [comment]
Same issue here.

**Comment by Dezhnev** [comment]
Try to check Windows Ink both in Blender preferences and XP-Pen soft.
That solved the problem for me. I'm using Blender 3.6 and XP-Pen Artist 15.6.

**Comment by Izaird** [comment]
I don't have those options

**Comment by Izaird** [comment]
are you using hyprland that looks like windows

![2023-10-18T13:04:12,262268509-06:00](https://github.com/hyprwm/Hyprland/assets/31055847/ee09bfa3-6bec-4a4c-9473-75785c749206)

**Comment by Izaird** [comment]
Just a little update on this if I hold and drag with the pen it doesn't work but if I move the mouse a little bit while still holding with the pen it works as it should 

https://github.com/hyprwm/Hyprland/assets/31055847/d29ff64d-5e42-4781-a6de-6cb99fba5b1c

**Comment by Agent00Ming** [comment]
Please check latest git. This works for me after #5902

**Comment by Izaird** [comment]
It's working, thank you
