### ISSUE TITLE
Incorrect fullscreen event data in socket2

### ISSUE THREAD

**Issue by owbosh** [hyprwm/Hyprland#347]
If you use fullscreen with parameter '1' (keep gaps and bars), this sends an incorrect event through socket2. It will always send the event fullscreen>>0, regardless of if you enter or exit fullscreen. The event works correctly for the other version of fullscreen, the 'true' fullscreen.

I am using this command to test it:
`socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do echo $line; done`

**Comment by vaxerski** [comment]
fixed in 2936368e8070fc53dd4095a786be4d92d20c4158
