### ISSUE TITLE
Cursor goes invisible on closing wofi

### ISSUE THREAD

**Issue by vityafx** [hyprwm/Hyprland#3471]
### Hyprland Version

9ec656a37df103edc111e8e48cdfe89528dfe92e

### Bug or Regression?

Bug

### Description

When I launch `wofi` to launch something and when my cursor is on top of it, once I press the Escape, the cursor is hidden until it intersects with another window or a monitor.
I am using software cursors.

### How to reproduce

1. Install `wofi`.
2. Launch wofi.
3. Move the cursor to the middle of the displayed `wofi` popup window.
4. Close `wofi`, for example, by pressing the Escape key.
5. Observe that the software cursor isn't rendered anymore until it intersects with another window or a monitor/workspace.

### Crash reports, logs, images, videos

The relevant part of the log is attached.

Description:
1. `Wofi` is spawned.
2. It is closed, and the cursor won't appear again until the `Falling back to software cursor on output` lines appear in the log.

[bug.log](https://github.com/hyprwm/Hyprland/files/12780258/bug.log)

**Comment by vaxerski** [comment]
noticed it too since a while back but couldnt be arsed to fix it

**Comment by lukejcollins** [comment]
Also getting this as well. Had this since I switched to Hyprland a couple of months ago. I just reflexively mouse up to waybar after wofi closes to resurrect the cursor.

I also experience it when using my grim/slurp/swappy setup as well.
