### ISSUE TITLE
Spawning new window behind fullscreen is visible

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#3474]
### Hyprland Version

Hyprland, built from branch makepkg at commit 5ffb1032e171b88dc45e0169159e449989a0fc58 dirty (events: don't focus new window if spawned behind fullscreen). Tag: v0.30.0-44-g5ffb1032

### Bug or Regression?

Bug

### Description

If the fullscreen window is transparent, you can see that the new spawn window is visible behind it.
Aside that, i think the much more intuitive behaviour would be to make the new spawn window the new fullscreen shown window instead of hiding it behind the actual fullscreened one.
When do you want to spawn a new window, and not see it?
If you think the behind fullscreen spawn way is prefered, please consider making this a customizeable variable.
I know it could probably be scripted, but i think lots of users would prefer the other way, so to prevent making multiple people write the same script...

And there is still the fact that closing a fullscreen window will go back to showing the workspace tiled.

### How to reproduce

Open a transparent window, fullscreen it, open another window.

**Comment by vaxerski** [comment]
> When do you want to spawn a new window, and not see it?

when I am gaming and steam opens a stupid window by fucking itself when not asked (fuck you steam)

**Comment by Dickby** [comment]
Thanks buddy!

**Comment by vaxerski** [comment]
yours truly
