### ISSUE TITLE
Screen lock and Idle Management Inside hyprland.conf

### ISSUE THREAD

**Issue by estnml** [hyprwm/Hyprland#3475]
### Description

Hello, first of all i would like to thank everyone who contributed to this beautiful project. The suggestion that I think can be added is that hyprland provides its own (by implemeting wayland protocols) screen locking and customizable lock screen system. We can do these functionalities thanks to softwares such as swaylock and swayidle, but it would be nice if we could make these settings directly in hyprland.conf and add more customization options. For example, in the variables section there can be a subcategory named locking just like blur, and we can make the necessary settings there.

**Comment by MightyPlaza** [comment]
don't see any good reason to do this, specially for locking, since it's critical software which requires security auditing.
swayidle and swaylock are just programs, you can use `exec-once` and set your options there or in their own configs

**Comment by vaxerski** [comment]
no
