### ISSUE TITLE
Software cursor framerate synced with tearing client

### ISSUE THREAD

**Issue by lualeet** [hyprwm/Hyprland#3478]
### Hyprland Version

Hyprland, built from branch  at commit  dirty (). Tag: ?  flags: (if any) debug

### Bug or Regression?

Bug

### Description

(hyprland built on commit b784931e678f907b1f1e41d04485fefd8a1faaf8, seems like `hyprctl version` doesn't like nix)

When using software cursors (WLR_NO_HARDWARE_CURSORS=1) and tearing is active, the cursor will only render whenever the client draws a frame.
This causes cursor stuttering when the client is at a low framerate, or will completely freeze the cursor if the client doesn't render anything when it's redundant (i.e. mpv).

### How to reproduce

a) using vrrtest
  1. launch hyprland with the envvar "WLR_NO_HARDWARE_CURSORS" set to 1
  2. open vrrtest, ensure tearing is active
  3. hold `down arrow` to lower the vrrtest framerate
  4. cursor movement will now match the lowered framerate 

b) using mpv
  1. launch hyprland with the envvar "WLR_NO_HARDWARE_CURSORS" set to 1
  2. open any video in mpv, ensure tearing is active
  3. if the video has a lower framerate than your monitor refresh rate, your cursor movement will stutter
  4. pause the video
  6. your cursor will now only move whenever the gui redraws

### Crash reports, logs, images, videos

expected results of the vrrtest repro:

https://github.com/hyprwm/Hyprland/assets/43719546/c138fcc0-0655-4d70-b4db-03b39f640bf2

**Comment by vaxerski** [comment]
this is expected, I will remove the forcing of software cursors soon

**Comment by vaxerski** [comment]
since been done, closing
