### ISSUE TITLE
May I ask if there is a way to run Hyprland in wsl

### ISSUE THREAD

**Issue by w934423231** [hyprwm/Hyprland#3479]
### Hyprland Version

无法运行

### Bug or Regression?

Bug

### Description

Unable to use Hyprland in wsl

### How to reproduce

Running Hyprland in wsl

### Crash reports, logs, images, videos

[lietu@lietu 93442]$ Hyprland
Welcome to Hyprland!
[LOG] Instance Signature: b784931e678f907b1f1e41d04485fefd8a1faaf8_1696340196
[LOG] Hyprland PID: 206
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: lietu
[LOG] Release: 5.15.90.1-microsoft-standard-WSL2
[LOG] Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023

lspci: Unable to load libkmod resources: error -2
[LOG] GPU information:

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG]
Current splash: h

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 14.07µs. Estimated average calc time: 0.04µs.
[LOG] Creating the ConfigManager!
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 5.96µs. Estimated average calc time: 0.02µs.
[LOG] Using config: /home/lietu/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 5.67µs. Estimated average calc time: 0.03µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
terminate called after throwing an instance of 'std::runtime_error'
  what():  wlr_backend_get_drm_fd() failed!
lspci: Unable to load libkmod resources: error -2
[CRITICAL] Hyprland has crashed :( Consult the crash report at /home/lietu/.hyprland/hyprlandCrashReport206.txt for more information.
Aborted (core dumped)

**Comment by vaxerski** [comment]
no
