### ISSUE TITLE
CMake install method errors out, cannot find meson.build

### ISSUE THREAD

**Issue by LarsThePenguin** [hyprwm/Hyprland#3483]
### Hyprland Version

0.30.0

### Bug or Regression?

Bug

### Description

So, I was installing Hyprland with CMake (Which is the recommended way to install on the website) and every time it errors out and says it can't find a file "Hyprland/subprojects/wlroots/meson/build"

### How to reproduce

Follow the instructions on the website for installing with CMake

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/93080905/374ebdbb-4a57-4ea0-b392-83a02c324053)

**Comment by FakeMichau** [comment]
Did you do recursive git clone?

**Comment by vaxerski** [comment]
they did
