### ISSUE TITLE
AUR update xdg-desktop-portal-hyprland-git and add missing build deps

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#3487]
### Hyprland Version

-

### Bug or Regression?

Bug

### Description

The build needs sdbus-cpp

### How to reproduce

-

**Comment by vaxerski** [comment]
I don't manage aur

**Comment by romanstingler** [comment]
love it 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/388e76de-2a5d-45b5-a54d-6910be6e604d)

**Comment by vaxerski** [comment]
oh wait I do? I'll see then. At any rate this is the wrong tracker
