### ISSUE TITLE
Binding workspaces to monitors.

### ISSUE THREAD

**Issue by owariee** [hyprwm/Hyprland#349]
It would be nice if we have a option to bind workspaces to a determined output(monitor).
Many people that are switching from bspwm/i3/sway to Hypr wants this feature.

Syntax suggestion:
workspace_bind=output,workspace_name

Idk, if this is already supported on Hyprland, but i couldnt find anything in the bug reports or in the wiki.

**Comment by avalsch** [comment]
Are you looking for `workspace=name,number`? 'Its in the wiki [here](https://github.com/hyprwm/Hyprland/wiki/Advanced-config#Monitors)

**Comment by vaxerski** [comment]
```
bind=SUPER,6,focusmonitor,DVI-D-1
bind=SUPER,6,workspace,6
```

**Comment by Roger-Roger-debug** [comment]
How would I do this with workspaces created with `movetoworkspace` or `movetoworkspacesilent` if the workspace is supposed to go on a different monitor?

**Comment by owariee** [comment]
> How would I do this with workspaces created with `movetoworkspace` or `movetoworkspacesilent` if the workspace is supposed to go on a different monitor?

I was wondering the same, and i came up with this:
```
bind=ALT,1,movetoworkspace,1
bind=ALT,1,movecurrentworkspacetomonitor,DP-2
```

So, if the workspace is not created, it will create it, move the window and then send it to the right monitor that it needs to, if its already created it will just move the window to the right workspace, and then move the workspace to the same monitor that it already is. Works pretty much the same as bspwm/i3/sway.

**Comment by Lenan** [comment]
Hey guys, I know this issue has been closed but I was having the same "issue" but I didn't want to add extra lines to my config file just to move workspaces to different monitors, so I made this script as an alternative. It has some quirks but it should work just fine for the most part. 
https://pastebin.com/xvvcFPwS
You need to have socat installed for this to work though.

P.S.: I recommend autostarting this script before any apps in case you have some rules set up.

**Comment by teksauce** [comment]
> Hey guys, I know this issue has been closed but I was having the same "issue" but I didn't want to add extra lines to my config file just to move workspaces to different monitors, so I made this script as an alternative. It has some quirks but it should work just fine for the most part. https://pastebin.com/xvvcFPwS You need to have socat installed for this to work though.
> 
> P.S.: I recommend autostarting this script before any apps in case you have some rules set up.

you're a legend dude works wonderfully thanks alot

**Comment by lucafulgenzi** [comment]
> Hey guys, I know this issue has been closed but I was having the same "issue" but I didn't want to add extra lines to my config file just to move workspaces to different monitors, so I made this script as an alternative. It has some quirks but it should work just fine for the most part. https://pastebin.com/xvvcFPwS You need to have socat installed for this to work though.
> 
> P.S.: I recommend autostarting this script before any apps in case you have some rules set up.

Your script works fantastically. I have two screens positioned one above the other and I manage them  at the same time: when I move one, the other moves with a workspace value of +5. 

The only thing I did was modify your script in this way:
``` 
socat - UNIX-CONNECT:/${XDG_RUNTIME_DIR}/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do handleworkspaces $line; done
```

I changed ` /tmp` to `XDG_RUNTIME_DIR`
