### ISSUE TITLE
Drop KDE idle protocol support

### ISSUE THREAD

**Issue by h0tc0d3** [hyprwm/Hyprland#3492]
### Hyprland Version

git

### Bug or Regression?

Bug

### Description

wlroots removed KDE idle protocol support. Hyprland build now fails.

```text
src/includes.hpp:50:10: fatal error: wlr/types/wlr_idle.h: No such file or directory
   50 | #include <wlr/types/wlr_idle.h>

src/Compositor.hpp:57:5: error: 'wlr_idle' does not name a type
   57 |     wlr_idle*                                  m_sWLRIdle;
      |     ^~~~~~~~                             
```

https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/a289f812d62059d5aac92cbd374dcb7b03bb08a6

### How to reproduce

Build with latest wlroots.
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/a289f812d62059d5aac92cbd374dcb7b03bb08a6

**Comment by vaxerski** [comment]
hyprland is not meant to be built against latest wlroots, but against the rev in the subproject

**Comment by h0tc0d3** [comment]
@vaxerski so kde idle protocol is deprecated. 
Are you planning to support it? 

Swaylock switches kde idle protocol to staging ext-idle-notify
https://wayland.app/protocols/ext-idle-notify-v1
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/tree/main/staging/ext-idle-notify

Kde idle is unstable: https://wayland.app/protocols/kde-idle

**Comment by vaxerski** [comment]
I will drop it once I bump wlroots past the rev in which it was deprecated
