### ISSUE TITLE
[hyprpaper] Opening or closing a layersurface causes reconfigure

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#3496]
### Hyprland Version

Hyprland, built from branch main at commit 1b99a69dc11c3c8266559c3c20b2f4dac6621dcc dirty ([gha] Nix: update wlroots).

### Bug or Regression?

Bug

### Description

For each notification received (through dunst), Hyprpaper prints the following:

Notification appears:
```ini
[LOG] configure for eDP-2
[LOG] Image data for eDP-2: /home/apm/.config/wallpapers/hk1.jpg at [-31.40, 0.00], scale: 1.05 (original image size: [2498, 1522])
[LOG] Submitting viewport dest size 2048x1280 for ddd74040
[LOG] configure for eDP-2
[LOG] handlePreferredScale: 1.25 for 564dddd74040
[LOG] Image data for eDP-2: /home/apm/.config/wallpapers/hk1.jpg at [-31.40, 0.00], scale: 1.05 (original image size: [2498, 1522])
[LOG] Submitting viewport dest size 2048x1280 for ddd74040
[LOG] handlePreferredScale: 1.25 for 564dddd74040
```

Notification disappears:

```ini
[LOG] configure for eDP-2
[LOG] Image data for eDP-2: /home/apm/.config/wallpapers/hk1.jpg at [-31.40, 0.00], scale: 1.05 (original image size: [2498, 1522])
[LOG] Submitting viewport dest size 2048x1280 for ddd74040
[LOG] handlePreferredScale: 1.25 for 564dddd74040
```

### How to reproduce

1. Run hyprpaper from terminal
2. `notify-send hi`
3. Observe logs

### Crash reports, logs, images, videos

From chaotic-aur:
```
Name            : hyprpaper-git
Version         : r110.e5a18a1-1
```

See closed issue https://github.com/hyprwm/hyprpaper/issues/97

**Comment by vaxerski** [comment]
why is this an issue tho

**Comment by TheSunCat** [comment]
Mainly unexpected log spam in journalctl when I'm trying to debug other issues, but also might (?) have a performance impact if we're reloading all the data.
