### ISSUE TITLE
Poor performance in games after ~10 minutes

### ISSUE THREAD

**Issue by sawb** [hyprwm/Hyprland#3498]
### Hyprland Version

Hyprland, built from branch main at commit 3d1a1679604e9de18a46a9a0819daf2044b08fa6 dirty (wsrules: check for workspace ID matches on numbered workspaces). Tag: v0.30.0-59-g3d1a1679

### Bug or Regression?

Bug

### Description

In the past couple weeks, I have been troubleshooting degraded performance in all games after about 10 minutes. The stutter/lag goes away if I switch my session to KDE/GNOME and remains after I restart Hyprland.

At first, I thought this was something to do with my video driver. But after further investigation, I have found that this issue is isolated to Hyprland only.
I can be lagging in Hyprland, then kill it and launch another DE/WM. I will get full FPS here. Then if I go back to Hyprland, I will still have the poor performance. The only thing that ends up resolving the issue is a full system reboot, then after about 10-20 mins of gameplay I'm lagging in Hyprland again.
  
If I restart CS2 in Hyprland after I have played for ~10 min, I will be down to 60fps in menus, and about 2/3 my normal FPS in game with heavy stutter. If I kill Hyprland (or every process by my user with pkill -U <username>) and restart, the lag and stutter is still there. From this point, the performance gets gradually worse over time.

When I have normal FPS, my GPU usage will be near 100%, but when this stutter happens my GPU is usually below 50% utilization.

I am using Arch linux with a 7900x+7900XTX, and running the games through gamescope. All games exhibit this behavior, and also happens without gamescope.

### How to reproduce

1. Play game under Hyprland (any Steam/Lutris games are doing this)
2. Have poor performance after about 10 minutes
3. Keep having poorer and poorer performance until full system reboot

### Crash reports, logs, images, videos

**Menu FPS on a fresh system boot**
![image](https://github.com/hyprwm/Hyprland/assets/39344564/10ed9b51-07d3-49ee-8fbd-d2e8f8c4caf8)
**Ingame FPS on a fresh system boot**
![image](https://github.com/hyprwm/Hyprland/assets/39344564/8d1865b4-afc3-4a1b-9d11-f6215574fd8e)

**Menu FPS after about 30 min**
![Menu FPS after about 30 min](https://github.com/hyprwm/Hyprland/assets/39344564/6c4dc63e-3bd7-47dc-87f9-0bcdfff15638)
**Ingame FPS after about 30 min**
![Ingame FPS after about 30 min](https://github.com/hyprwm/Hyprland/assets/39344564/47314612-63cf-4183-ab66-96b34c427fb7)

**Comment by sawb** [comment]
I have tried the following versions of Hyprland, and get the same issue on all of them. This does not happen on any other DE/WM I have tried so far.

hyprland-git-r3042.e632bf17
hyprland-git-r3023.e96fcb31
hyprland-git-0.30.0.r8.352ceb11
hyprland-git-0.29.1.r98.1925e64c

Also have used these versions of mesa:
mesa 23.2.1-1
mesa-tkg-git-23.3.0_devel.178503.60dd34b02a6-1
mesa-tkg-git-23.3.0_devel.178134.c04f313cc53-1

**Comment by vaxerski** [comment]
can you post a log from the offending session?

**Comment by vaxerski** [comment]
also have you verified `htop` that nothing is amiss there?

**Comment by sawb** [comment]
> also have you verified `htop` that nothing is amiss there?

I did check htop. There's nothing running that is unexpected, and resource utilization is low. In troubleshooting, I went as far as to kill everything started under my user, leaving only these processes still running as root,rtkit,systemd, etc...:
![2023-10-04T22:51:13,468320635-07:00](https://github.com/hyprwm/Hyprland/assets/39344564/1e52b6ec-1ce3-45f5-984e-ad929d080755)
After this, I started up a new Hyprland session and it still does this until I fully reboot my system.




> can you post a log from the offending session?

I'm not getting crashes or anything, so there's no log being dumped. I also tried running steam in a terminal, and there's nothing abnormal written there either. Can I force some sort of log for my current session? I am currently booted into a session with this behavior.

**Comment by vaxerski** [comment]
your logs are stored in /tmp/hypr

**Comment by sawb** [comment]
I just started a fresh session (with my system in the previous state as the screenshot above, pkill -U <username>). In this session, all I did was launch CS2 and had about 10 FPS in the menu. 
[hyprland.log](https://github.com/hyprwm/Hyprland/files/12825637/hyprland.log)

**Comment by vaxerski** [comment]
nothing looks amiss to me :/

**Comment by sawb** [comment]
@vaxerski Uhh wow, I found the problem. I was thinking the only difference between Hyprland/KDE would be my startup programs, and I started closing them one by one. It turns out OpenRGB is causing this to happen without taking any system resources. Very strange bug, but I thank you very much for your quick help on this. I will go ahead and close it.

**Comment by vaxerski** [comment]
lmao
