### ISSUE TITLE
Firefox unable to use META key for ui.key.accelkey

### ISSUE THREAD

**Issue by RichardFevrier** [hyprwm/Hyprland#3499]
### Hyprland Version

v0.30.0 1b48642fd15c433c53876f1b933dcd46265caf8f

### Bug or Regression?

Bug

### Description

Using `Firefox flatpak` version, I like to use `META` key as modifier key instead of `CTRL`.
The only problem is that I like `Hyprland` too but both are incompatible for now 😅
This workflow is perfectly working with `Sway` and `Gnome Wayland` (also I have checked with `Alt` as `mainMod` key in `Hyprland` config to be sure no conflict would happen here)

### How to reproduce

In `Firefox` go to `about:config` and look for `ui.key.accelkey`.
Change the value `17` for `91`.
`Restart Firefox`.
Try to open a new Tab with `META` + `T`.

**Comment by vaxerski** [comment]
firefox issue: https://www.reddit.com/r/swaywm/comments/m8amyy/using_win_key_as_accelkey_in_firefox/

**Comment by RichardFevrier** [comment]
> that value doesn't change anything to me. It stays at ctrl regardless

Did you restart `Firefox` ?

> firefox issue: https://www.reddit.com/r/swaywm/comments/m8amyy/using_win_key_as_accelkey_in_firefox/

It is working with `Sway`

**Comment by vaxerski** [comment]
> It is working with Sway have you tried ? (I did)

maybe because sway doesn't set the firefox wayland env by default and it runs via xwayland. `MOZ_ENABLE_WAYLAND=0 firefox` works on hyprland too.

**Comment by RichardFevrier** [comment]
My bad you are the goat 😌

**Comment by RichardFevrier** [comment]
If ever someone has the same problem [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1857289) is the issue link on the Mozilla side.
