### ISSUE TITLE
Feature: Opacity transition (animation?) on `movefocus`

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#350]
Good day to you!

Suggesting: smooth opacity transition between windows with different opacities

usecase: i've set opacity for active and inactive windows, and some for custom class.

when i `movefocus`, activewindow smoothly increases/decreases opacity to `active opacity`, and previous active window smoothly increases/decreases opacity to `inactive opacity` 

Thank you!

**Comment by vaxerski** [comment]
added in a4f82491b7e825255253a1fbea509e823b73115b

animation speed and curve tied to the `fadein` animation

**Comment by fedoranvar** [comment]
it works good . 

Thank you!
