### ISSUE TITLE
Weird flickering and resizing

### ISSUE THREAD

**Issue by vccrurial** [hyprwm/Hyprland#3500]
### Hyprland Version

v0.30.0

### Bug or Regression?

Bug

### Description

1) When moving a window between workspaces, there is flickering: the wallpaper appears for a second, and then the program shows up.
2) The same issue occurs when opening a new window in grouped clients. Additionally, changing the focus in the group causes strange blinking.
3) Weird resizing of graphical apps like LibreOffice occurs when you open something next to them and then close it.

### How to reproduce

animations:enabled = false

### Crash reports, logs, images, videos

First video: There is flickering when you move a window between workspaces, open a new window in a group, or change focus within the group.

Second video: The video has been slowed down to allow viewers to notice the unusual resizing behavior of LibreOffice (this also applies to other graphical apps like Firefox or Chromium).

https://github.com/hyprwm/Hyprland/assets/72652534/f21f0d0b-a215-456b-8d85-eac6c9d4d2e6

https://github.com/hyprwm/Hyprland/assets/72652534/a3283a2b-fe3c-4874-95ba-c2045f3c4043

**Comment by vaxerski** [comment]
#2767
