### ISSUE TITLE
No crashreport can be found after a session crash

### ISSUE THREAD

**Issue by kiuKisas** [hyprwm/Hyprland#3504]
### Hyprland Version

 v0.30.0, 1b48642fd15c433c53876f1b933dcd46265caf8f

### Bug or Regression?

Bug

### Description

 After a session crash (see https://github.com/hyprwm/Hyprland/issues/3484 and https://github.com/hyprwm/Hyprland/issues/3489 for references), I could not find a crash report. 
 - Without `XDG_CACHE_HOME` , `.~/.hyprland` folder stay empty. I found a crashreport from august though (I deleted it for testing this issue, no backup).
 - With this variable set, `hyrpland` folder stay empty after a crash.
 
I could not find it either with `find / -name "hyprlandCrashReport*"`
 
 But it seems to be generated as shown in this pic:
 ![photo_2023-10-04_16-43-16](https://github.com/hyprwm/Hyprland/assets/12698940/225c79b5-2f24-41fc-bf01-b3e63ac777f0)

### How to reproduce

- Set or unset `XDG_CACHE_HOME`
- Wait for a crash
-  check if a crash report exist

**Comment by vaxerski** [comment]
check with 24c04a8b7c874ead168bb2418f4325cb8bdaca5b

**Comment by kiuKisas** [comment]
Didn't work without `XDG_CACHE_HOME`, I try with it and let you know

**Comment by vaxerski** [comment]
that's odd because I don't have XDG_CACHE_HOME set either and I do get crash reports.

**Comment by kiuKisas** [comment]
Well, after a 2-hour session with  https://github.com/hyprwm/Hyprland/commit/4b3efc73c5d059e828f79952d80ff79c97521c3d compiled in debug mode, I still haven't had the crash. I notice that everything is slower though, dunno if it can impact the crash. Gonna try with the same commit but without the debug flag.
Also, `xdg-desktop-portal-hyprland`  consume 20% of my cpu all the time.

**Comment by vaxerski** [comment]
> Also, xdg-desktop-portal-hyprland consume 20% of my cpu all the time.

use -git it was fixed

**Comment by kiuKisas** [comment]
Updated. In case my crash doesn't happen anymore, I tried with a `SIGTERM` signal and the crash report was saved

**Comment by vaxerski** [comment]
closing
