### ISSUE TITLE
Changing from and to empty workspaces between monitors messes up selection

### ISSUE THREAD

**Issue by Diaoul** [hyprwm/Hyprland#3513]
### Hyprland Version

v0.30.0

### Bug or Regression?

Bug

### Description

When switching back and forth from workspaces attached to monitors through rules, hyprland looses track of the actual workspace that should be selected and misplace it.

Attached a video as I could not screen record on multiple monitors.
In this video:
- Workspaces 4, 5, 6, 7 have a monitor rule on the left one
- Workspaces 8, 9, 10 have a monitor rule on the right one
- Workspaces 4, 5, 8 have windows on them, the others are empty
- Initially, workspace 6 is active
- I only press shortcuts to move to workspace 9 and 10, never 6. Yet it is selected sometimes and sometimes not
- It's not just a waybar display issue: when I try to open a window, it opens on the 6 even though I explicitly executed "workspace 10" right before
- Running `hyprctl workspaces -j` reveals no anomaly, workspaces are on the monitors they should be

```
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10
```

https://github.com/hyprwm/Hyprland/assets/319220/e8dc12cc-c062-4141-a77d-dd6683d7ae69

### How to reproduce

- Have 2 monitors, see setup above
- Navigate between empty workspaces on different monitors
- Especially seems to happen when navigating on consecutive empty workspaces on the same monitor and another one from another monitor

**Comment by MightyPlaza** [comment]
is this still happening, if so please post what's going on with `socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock`

**Comment by Diaoul** [comment]
I don't think so, I have other issues related to waybar/hyprland but not this one in particular
