### ISSUE TITLE
Support for software rendering backend

### ISSUE THREAD

**Issue by jack9603301** [hyprwm/Hyprland#3516]
### Description

Although most of today's graphics cards support hardware-accelerated rendering, some of the newer hardware may have difficulty working in hardware-rendering mode. For example, my intel iris Xe graphics card reports an EGL initialization error in hardware rendering, and it may not be able to use hardware-accelerated rendering under the i915 driver. Does hyprland have plans to support a software rendering backend? Sway and other wlroots support unity rendering backend, does hyprland have plans to support it?

**Comment by vaxerski** [comment]
`WLR_RENDERER_ALLOW_SOFTWARE=1`

**Comment by jack9603301** [comment]
> `WLR_RENDERER_ALLOW_SOFTWARE=1`


Strangely, it doesn't seem to respond. I'll try again, but sway's pixman renderer works fine.

**Comment by vaxerski** [comment]
if that doesn't work it's not planned. Hyprland uses gles and IIRC the env used to work in the past.

**Comment by jack9603301** [comment]
@vaxerski So what you're saying is, if hardware rendering doesn't work, I might have to use sway or some other compositor, right?

**Comment by vaxerski** [comment]
yes
