### ISSUE TITLE
Suddenly no wayland compositor works after installing mesa git

### ISSUE THREAD

**Issue by XxRiKxX** [hyprwm/Hyprland#3517]
### Hyprland Version

0.30.0-1

### Bug or Regression?

Bug

### Description

I am on arch with amd rx570. I installed mesa-git from the unofficial repo and after reboot it does not works. I got some /run/seate.sock error. I installed mesa from the official repo again but still didn't worked. I enabled seats.service. and then I got permission denied error in /run/seatd.sock so I chmod 777 that file and now it gives no error but does not works either. I checked the log files in .hyprland and got a critical m_sWlrrendered is null error. Sway does not works either. Deleted the config file. Still does not works

### How to reproduce

Don't know

### Crash reports, logs, images, videos

![2023-10-07-22-32-15-412](https://github.com/hyprwm/Hyprland/assets/102613873/892a0b2e-19db-40da-a25b-0783b58cbcf5)
![2023-10-07-22-31-59-407](https://github.com/hyprwm/Hyprland/assets/102613873/9942a42e-450a-4f08-bc01-d2f23f5a3a92)
![2023-10-07-22-31-23-351](https://github.com/hyprwm/Hyprland/assets/102613873/cd5cfcac-9d0c-4e4e-b10e-c33ab9dbbf0e)

**Comment by vaxerski** [comment]
well then this is not a hyprland issue

**Comment by XxRiKxX** [comment]
OK. Sorry for posting it here then. But do you know anything about how to fix this. kitty terminal is not working either. it gives this error
[280 23:25:43.016811] [glfw error 65542]: GLX: GLX extension not found
[280 23:25:43.016825] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.

**Comment by MightyPlaza** [comment]
you need a display server running to use kitty
you will likely have better luck finding the issue by taking a look into the mesa-git PKGBUILD (and asking for help on the arch forum)

**Comment by XxRiKxX** [comment]
I have am using xfce at the moment. and I already uninstalled mesa-git and using normal mesa now. even in lutris or yuzu its not detecting my gpu
