### ISSUE TITLE
Bug: interaction with hyprpaper is broken

### ISSUE THREAD

**Issue by iddm** [hyprwm/Hyprland#3523]
### Hyprland Version

499df49f7b28f9e3be9b1c53843fd5c465dec60b

### Bug or Regression?

Bug

### Description

hyprpaper not filling the entire screen. There is a bottom line of pixels (presumably with the height of just one pixel) which is still visible when hyprpaper has already filled the screen.

As an OLED user, I have a full-black workspace background. I noticed a line of pixels of one height. Those pixels are exactly where the girl's legs are if I kill `hyprpaper`. This happens on both monitors and is reproducible 100% of the time.

W.r.t. to the screen settings, workspace, hyprpaper, any other settings basically - nothing has changed exactly. I think the problem has only appeared within the commits of last week.

### How to reproduce

1. Install hyprpaper (doesn't matter which version).
2. Fill the screen with full black background.
3. Observe the lowest line of pixels in the screen is not entirely black as it should be given the wallpaper is black: there is a grey line. If you `kill hyprpaper`, you'll notice that this line is exactly where the girl's legs are.

### Crash reports, logs, images, videos

With some good eye, it can also be seen in this screenshot.
![screenshot](https://github.com/hyprwm/Hyprland/assets/1146369/1ea29060-8223-4f83-91e9-50f151cbc5e0)

UPD: Removed mentions of regression and 0.30 version since it has always been there.

**Comment by vaxerski** [comment]
`git bisect` please

**Comment by vaxerski** [comment]
uhh idk on your screenshots I can't see it and I also can't see it on my screen

**Comment by vaxerski** [comment]
can I get a hyprland log

**Comment by vaxerski** [comment]
nothing looks amiss to me in the log. hyprpaper is 1440 pixels high. Do you use scaling? Does the same happen with swaybg? Are aliens real?

**Comment by FakeMichau** [comment]
This somewhat sidesteps the issue but you can do this instead of using hyprpaper
```
misc {
    disable_hyprland_logo=true
    background_color=0x000000
}
```

**Comment by FakeMichau** [comment]
> in my screenshot, it is clearly not (you can see the bottom line I mentioned)

I've downloaded your screenshot, enhanced it heavily and still couldn't see any line at the bottom, only a faint vertical line exactly in the middle became visible. But the photo you took clearly shows it, I agree.

Also, hyprpaper let's you define a wallpaper [per monitor](https://github.com/hyprwm/hyprpaper#usage). So you could be using the method I mentioned and make use of hyprpaper for whatever wallpaper you want, but only on that one monitor, leaving the other black.

**Comment by vaxerski** [comment]
does it also happen if you run hyprpaper with `-n`?

**Comment by FakeMichau** [comment]
I can somewhat reproduce the issue using a 1920x1080 wallpaper on a 3440x1440 screen - I get vertical white lines, one pixel in width on the left and right side. ``-n`` doesn't change anything. swaybg has the same issue

**Comment by FakeMichau** [comment]
@vityafx Could you try the PR above? Thanks
