### ISSUE TITLE
Allow dragging windows to a different workspace

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#3525]
### Description

If I'm dragging a window with the mouse and switch to another workspace with a keybind, the dragging is immediately cancelled, but I think it would be cool to keep the window dragged so that you can drop it in the other workspace.

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/issues/988

**Comment by thejch** [comment]
I see, will close this one.
