### ISSUE TITLE
idleinhibit windowrule not working

### ISSUE THREAD

**Issue by h0useofdupree** [hyprwm/Hyprland#3526]
### Hyprland Version

Hyprland, built from branch main at commit 9ec656a37df103edc111e8e48cdfe89528dfe92e dirty (makefile: make binaries 755 instead of 711). Tag: v0.30.0-40-g9ec656a3  flags: (if any)

### Bug or Regression?

Bug

### Description

After adding the windowrule:

`windowrulev2 = idleinhibit focus,class:(org.qutebrowser.qutebrowser)
`
(or any other mode for idleinhibit, including non existent modes (which btw doesn't raise any errors))

nothing keeps swayidle from firing after given timeout.

Setting a different rule like 'dimaround' for testing works.

### How to reproduce

add the above mentionend windowrule for whatever window class or title:

`windowrulev2 = idleinhibit focus,class:([window])`

set your idle handler (in my case swayidle) to a short timeout for testing:

`swayidle -w timeout 5 [your_lock_command]`

**Comment by hydroakri** [comment]
same here `windowrulev2 = idleinhibit always, fullscreen:1` not working

**Comment by AdsonCicilioti** [comment]
Same here...

I've try `windowrulev2 = idleinhibit fullscreen, fullscreen:1` but swayidle isn't stop.

**Comment by vaxerski** [comment]
works for me. What's your swayidle ver?

**Comment by cuanim** [comment]
Facing a similar issue too. My swayidle version is `swayidle.x86_64 1.8.0-2.fc38`

To check I opened my game on a different workspace and ran swayidle -w timeout 5 swaylock.
It ended up locking the screen after 5 seconds.

`windowrulev2 = idleinhibit fullscreen, fullscreen:1`
hyprctl clients
```
Window 55c14b845f90 -> Hollow Knight:
	mapped: 1
	hidden: 0
	at: 0,0
	size: 1536,864
	workspace: 1 (1)
	floating: 1
	monitor: 0
	class: Hollow Knight
	title: Hollow Knight
	initialClass: Hollow Knight
	initialTitle: Hollow Knight
	pid: 30356
	xwayland: 1
	pinned: 0
	fullscreen: 1
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```

**Comment by vaxerski** [comment]
idleinhibit is not dynamic, your wr will not work. That is expected. 

Although fair point it should be.

**Comment by dingleboss** [comment]
Using hyprland 0.30.0-1 and swayidle 1.8.0-1 (both from Arch Extra repo).
The rule I have for fullscreen works as anticipated:
`windowrulev2 = idleinhibit fullscreen,class:(.*)`
But the rules I have for focused windows do not. Example:
`windowrulev2 = idleinhibit focus,class:(mpv)`
Additionally, changing 'focus' to 'always' seems to have no effect and neither does changing 'class' to 'title'.
`hyprctl clients` for mpv is as follows:

> Window 5556323ce280 -> No file - mpv:
	mapped: 1
	hidden: 0
	at: 1920,48
	size: 1920,1032
	workspace: 7 (7)
	floating: 0
	monitor: 1
	class: mpv
	title: No file - mpv
	initialClass: mpv
	initialTitle:
	pid: 56668
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Going to try the sway-audio-idle-inhibit-git package as a workaround for now.

**Comment by vaxerski** [comment]
forgot to mention, it now is since like 3 days ago: 49597688e975c23b4f3bb53e77617ed3cd1e4937

**Comment by cuanim** [comment]
Yep works for me. Thanks a lot orz

**Comment by khaneliman** [comment]
@vaxerski one thing i'm noticing while playing around with rules since it hasn't been behaving for me and i'm actually looking into it more... is that the rules i set up seem to only apply for idleinhibit on the monitor my mouse is on. I have a rule set up for firefox when i have videos playing, but it only inhibits idle when my mouse is on the monitor with that firefox window. If I have my mouse on my main monitor, it doesn't inhibit idle.

**Comment by khaneliman** [comment]
> @khaneliman from my testing it seems that Firefox only requests inhibition when it's focused, and unregisters the cookie when it's not. Chromium keeps the cookie alive as long as media is playing.

I thought the idleinhibit rules were specifically for specifying my own scenarios and not to rely on the application.

**Comment by h0useofdupree** [comment]
Thanks @vaxerski , works perfectly fine when playing content. 

Also, thanks in general for this whole project, no, **eco-system**. Been using Hypr* for a while and I love the progress. Got to leave a tip for your good work.

Can I close this, or should I leave this open for now? This is resolved for me
