### ISSUE TITLE
movewindoworgroup bypasses lockgroups

### ISSUE THREAD

**Issue by BluewyDiamond** [hyprwm/Hyprland#3529]
### Hyprland Version

Hyprland, built from branch main at commit 728a8bb48e0f7de1cbe1ad13fb469754c3d0bc97 dirty (config: mention force_default_wallpaper in default configs). Tag: v0.30.0-67-g728a8bb4

### Bug or Regression?

Bug

### Description

Toggling `lockgroups` does not make it immune to movewindoworgroup.

### How to reproduce

Toggling `lockgroups -> on` and then move a window using `movewindoworgroup` to the direction where the group is, will place the window into the group.

### Crash reports, logs, images, videos

![2023-10-09T01:55:28,553402787+02:00](https://github.com/hyprwm/Hyprland/assets/115411576/27492baf-4b9d-4500-a680-aba1a92f0ebd)
![2023-10-09T01:55:31,726617328+02:00](https://github.com/hyprwm/Hyprland/assets/115411576/bef3416f-ac77-430e-abb6-5c1340d0a907)

**Comment by BluewyDiamond** [comment]
`hyprctl dispatch lockgroups lock` instead of `on` also has the same behaviour.

**Comment by memchr** [comment]
It doesn't check the global lock (should it check or not?)

https://github.com/hyprwm/Hyprland/blob/499df49f7b28f9e3be9b1c53843fd5c465dec60b/src/managers/KeybindManager.cpp#L2054-L2069

Try lockactivegroup?

**Comment by BluewyDiamond** [comment]
I just tried `lockactivegroup` and it works, but since the wiki says "Locks the groups (all groups will not accept new windows)", I feel like `lockgroups` should also do the same for all groups, otherwise it would be confusing I think.

**Comment by memchr** [comment]
moveintogroup doesn't check global locks either, this has been the case for a long time. I assume the original intent for this lock is just to prevent new windows from being mapped into a group.

Does it need to be changed?

**Comment by BluewyDiamond** [comment]
I recommend implementing changes to enhance consistency in the functionality. Specifically, it should be modified to verify global locks. Additionally, it's worth noting that 'lockgroups' lacks the visual indicator that 'lockactivegroup' provides when activated, and it does not restrict moving the window out of the group, a behavior that 'lockactivegroup' does exhibit. Therefore, I propose making adjustments to ensure a more consistent behavior across these features.

**Comment by BluewyDiamond** [comment]
summarizing:
`lockgroups` -> should show the visual border that `lockactivegroup` has
`moveintogroup`, `movewindoworgroup` and possibly `moveoutofgroup` -> check if group is locked
     
Does this make sense or covers it all?

**Comment by memchr** [comment]
`moveoutofgroup` does not check for locks, only `movewindoworgroup` does. This is indeed inconsistent. 

> 'lockgroups' lacks the visual indicator that 'lockactivegroup' provides when activated

lockactivegroup is tied to individual groups, so the border of that group has been used to represent the status of the lock.
Because lockgroups triggers a global lock, it cannot be logically bound to individual window decorations. Instead, it fires an IPC event, you can listen for it on socket2, and adjust the status bar accordingly, for example.

**Comment by BluewyDiamond** [comment]
Does it make sense to make `lockgroups` show the visual border across all existing groups? maybe a different border color for it?

**Comment by memchr** [comment]
Then how do you know if the lock is engaged when there is no group?

**Comment by BluewyDiamond** [comment]
Now that you mention it, that is a very good question. I guess I will have to remember that it is engaged. Thinking of a solution is hard :(.

**Comment by BluewyDiamond** [comment]
I was thinking of flashing the border red and then back to the original color in order to indicate that the lock is engaged thus not allowing you to group the window.

**Comment by memchr** [comment]
A lock is a persistent state, the blinking is momentary, stalemate?

**Comment by BluewyDiamond** [comment]
Oh, honestly I don't know how I did not think of that.

**Comment by BluewyDiamond** [comment]
Though I was thinking more in the lines of without needing to rely programs like waybar, but using a visual indicator on waybar might be more ideal.

**Comment by memchr** [comment]
As in the same argument why submap does not have a visual identifier, because there is no good place for it in the compositor. But a bar would serve this purpose well, I suppose?

**Comment by BluewyDiamond** [comment]
how are things progressing?
