### ISSUE TITLE
Can I force the mouse position on the specified monitor when hyprland starts？

### ISSUE THREAD

**Issue by zlgxzswjy** [hyprwm/Hyprland#3533]
### Hyprland Version

Hyprland, built from branch main at commit 499df49f7b28f9e3be9b1c53843fd5c465dec60b dirty (dispatchers: fix extra monitor offset when snapping floating (3520)). Tag: v0.30.0-68-g499df49f

### Bug or Regression?

Bug

### Description

I'm using dual monitors, and I've set them up to go up and down. But I found that when I entered my account password into hyprland, the default mouse start position was always at the bottom of the display. 

I also used xrandr to set up the above monitor as the primary monitor, but this didn't work

Can I force the mouse position on the specified monitor when hyprland starts？

my monitor.conf
```
monitor = ,preferred,auto,1
monitor = eDP-1,preferred,0x0,1
monitor = DP-1,preferred,0x1080,2
workspace = 1,monitor:eDP-1,default:true
workspace = 2,monitor:DP-1
exec-once = xrandr --output eDP-1 --primary
```

### How to reproduce

No need to reproduce.

**Comment by vaxerski** [comment]
wayland has no such thing as a primary display. 

You can call `hyprctl` to execute a focusmonitor, technically.

Not a bug anyways
