### ISSUE TITLE
Workspace binding change needs restart to be applied in hyprland.conf file

### ISSUE THREAD

**Issue by JohRest** [hyprwm/Hyprland#3534]
### Hyprland Version

0.30

### Bug or Regression?

Bug

### Description

I've changed my workspace bindings to rearrange workspaces with my three monitor setup. Normally changes are applied immediately after saving, but the following change did not become active, only after a restart:

# -----------------------------------------------------
# Workspace binding to specific monitors
# -----------------------------------------------------
workspace=HDMI-A-1,1
workspace=HDMI-A-2,2, default:true
workspace=DP-2,3

I am unsure if this is a bug or just my misunderstanding of how it's supposed to work... but you'll deal with this appropriatly, of that I'm sure... :-)

Cheers

Johannes

### How to reproduce

Change the workspace settings, especially binding workspaces to specific monitors. Save the change. The change does not become effective immediately, only after a restart of hyprland.

**Comment by pdamianik** [comment]
The first segment of a workspace rule is the [workspace identifier](https://wiki.hyprland.org/Configuring/Dispatchers#workspaces), which can't be a display. The wiki seems to contain the invalid example `workspace=DP-1,3,rounding:false,bordersize:0` for this case. Any further configuration can be done after the first segments, e.g. binding a workspace to a specific monitor with `monitor:[m]` (See [Example Rules](http://wiki.hyprland.org/Configuring/Workspace-Rules/#example-rules)). Also for changing the monitor of a workspace the `moveworkspacetomonitor` [dispatcher](http://wiki.hyprland.org/Configuring/Dispatchers/#list-of-dispatchers) can be used.

**Comment by pdamianik** [comment]
This seems to be undocumented behavior (apart from the example), but you are right. The first argument can be a monitor which requires the second argument to be a workspace. Interestingly the `default:true` option is implied by this form of configuring the default workspace (see [src/config/ConfigManager.cpp:1137-1150](https://github.com/hyprwm/Hyprland/blob/v0.30.0/src/config/ConfigManager.cpp#L1137-L1150)). This configuration only gets used when adding a monitor (internally also called output) to Hyprland (see [src/helpers/Monitor.cpp:348-350](https://github.com/hyprwm/Hyprland/blob/v0.30.0/src/helpers/Monitor.cpp#L348-L350) and [src/config/ConfigManager.cpp:2269-2279](https://github.com/hyprwm/Hyprland/blob/v0.30.0/src/config/ConfigManager.cpp#L2269-L2279)). This happens either at startup or when connection a new monitor. So the rules only come into effect on those cases. For assigning a workspace to a monitor during runtime the `moveworkspacetomonitor` dispatcher has to be used.

**Comment by JohRest** [comment]
also I noticed that the last NVIDIA driver is definately worse than the version before... mouse cursor is improperly redrawn, missing when I move the mouse and also parts of the screen are not properly drawn / refreshed... but that's another thing...
