### ISSUE TITLE
Change gaps and other decorative properties of special workspaces

### ISSUE THREAD

**Issue by diniamo** [hyprwm/Hyprland#3537]
### Description

I've been looking for this for a while in the docs, but couldn't find anything. I've tried
```
workspace = special:fm,gapsin:0,gapsout:0
```
but it doesn't do anything.

**Comment by SergioQuijanoRey** [comment]
I was trying to do this, but as said, It does nothing. It would be really useful because special workspace has a lot of unused space for my taste.

**Comment by diniamo** [comment]
This fixes `bordersize`, `border`, `shadow`, `rounding`, `decorate`. `gapsin` and `gapsout` still don't work, which was the main reason for why I opened the issue.

**Comment by vaxerski** [comment]
nvm. It works.

**Comment by diniamo** [comment]
Ah, that's what I've been looking for all along, thank you.
