### ISSUE TITLE
Request: match rotation between outputs and mapped inputs

### ISSUE THREAD

**Issue by Smona** [hyprwm/Hyprland#3538]
### Description

After the acceptance of #996 and #3220, Hyprland is _almost_ a first class experience on 2-in-1s! At this point, there is only one thing keeping me from switching entirely to Hyprland on my 2-in-1 laptop.

In Sway, it is possible to map inputs to outputs with the `map_to_output` message. This causes inputs to automatically rotate when their mapped output does, ensuring touch inputs always map correctly to dynamically rotated outputs (e.g. when using [rot8](https://github.com/efernau/rot8)). Hyprland also supports mapping inputs to outputs via the `inputs.touchdevice.output` keyword (and apparently maps inputs automatically when it can), but in my experience this does not lock the transform of the input to the output.

It's important for hyprland to support this in my opinion, because AFAICT there is no way for third-party programs to control the transform of existing input devices via a wayland protocol, so at the moment users will always have to implement their own, hyprland specific scripts to achieve what should be a universally desirable behavior: touchscreens inputting where the user's finger is, regardless of dynamic rotation.

Since there is already a `transform` option for inputs, perhaps the right way to implement this would be to _add_ any output rotation changes to the user-configured input rotation.

**Comment by pdamianik** [comment]
Same as last time, I have no 2in1 so I can't test #3544, but this should be all to get it working. As for the remaining items, nothing major is open, just a implementation detail so this should be the final state of the pr.

**Comment by Smona** [comment]
Thank you @pdamianik! I'm traveling at the moment so I don't have my 2-in-1 with me, but I will test this as soon as I get back :slightly_smiling_face:

**Comment by pdamianik** [comment]
@Smona I assume you aren't subscribed to #3544 and didn't get a notification for my latest changes. If you did and just didn't have time to check them out then feel free to ignore this reminder.

**Comment by Smona** [comment]
Thanks for the reminder! This is still on my radar but life got very busy recently. I should be able to re-test this weekend.

**Comment by pdamianik** [comment]
If you are occupied it is always ok to leave this issue open. I was just worried you might be waiting for further changes from my side.
