### ISSUE TITLE
Confirmation on exit

### ISSUE THREAD

**Issue by bonsairobo** [hyprwm/Hyprland#3540]
### Description

I like to have this binding:

```
bind = $mainMod, M, exit
```

But it's easy to accidentally type that and kill the entire session. Some kind of confirmation UI would be appreciated.

**Comment by vaxerski** [comment]
this is not a DE. Making a confirmation prompt would be left to you.

**Comment by bonsairobo** [comment]
OK I see where you are coming from. I guess I will write an interactive script for this to bind to that key combo instead.
