### ISSUE TITLE
Option to toggle off borders/gaps when there is only 1 window in workspace

### ISSUE THREAD

**Issue by owbosh** [hyprwm/Hyprland#355]
There is a feature that I really liked in bspwm that allows you to automatically toggle off borders and gaps when there is only 1 window in the workspace (basically an 'auto-maximize'). I like this feature because I believe gaps are only necessary when there is more than 1 window, so you can easily distinguish them apart. When there is only 1 window, I don't want any gaps so I can dedicate the whole screen to that window.

If this is possible with a script, I would like to know about it. But as I understand, you would have to be checking the current workspace's number of windows, and to get that data you would have to be constantly running awk or something to extract it from the info produced by hyprctl? Just seems really messy and inefficient.

**Comment by vaxerski** [comment]
done in f892387b7020ce27dbcf370244e26e09c9ecc1e5 and 60c16f77a64ef1e992f7aa7476b2e52847d18c25
