### ISSUE TITLE
"Hyprctl notify" notifications only appear after another input has been made

### ISSUE THREAD

**Issue by gnarlsnishi** [hyprwm/Hyprland#3552]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0

### Bug or Regression?

Bug

### Description

I have the following lines in my hyprland.conf, to see the time and my current workspace at a glance.

`bind = $mainMod, D, exec, hyprctl notify -1 2000 0 "$(date)"`
`bind = $mainMod, W, exec, hyprctl notify -1 2000 0 "$(hyprctl activeworkspace | head -n 1)"`

My expected behaviour is that the notification would pop up instantly with the requested info.
What occurs is that the notification only appears if I immediately follow the "mainMod + D or W" input with any other input, such as moving the mouse, typing something, etc. Additionally, if I have a video or music playing, the notification behaves properly, appearing instantly.
Not sure if this is a bug or intended behaviour.

I am also open to using another tool entirely if this is not an intended use case of "hyprctl notify"

Thank you for your help!

### How to reproduce

Paste the above lines into your hyprland.conf. Input the relevant keybinding.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12876056/hyprland.log)

Relevant lines start at 356.

**Comment by Duckonaut** [comment]
Can confirm I'm having similar behavior with notifications called from plugins

**Comment by FakeMichau** [comment]
It's most likely caused by hyprland not updating the screen when a notification should appear.

**Comment by gnarlsnishi** [comment]
@FakeMichau Thank you!!!

**Comment by amandeep2102** [comment]
@tomysurya use something like this

`hyprctl notify 0 10000 0 "fontsize:20 this is the message" `

basically use fontsize:@value before the actual message in the string
