### ISSUE TITLE
Incorrect cursor positioning in context menus in firefox

### ISSUE THREAD

**Issue by TAforever** [hyprwm/Hyprland#3553]
### Hyprland Version

0.30.0

### Bug or Regression?

Bug

### Description

When I click “open link in a new tab” in the context menu, I am shown the “save object as” dialog box, I also select one site in the bookmarks and go to the one 5 lines below. The bug is not always reproduced, sometimes it is gone for a long time but then it returns. I tried to reproduce it in sway-git but this bug is not there.

### How to reproduce

Described above

**Comment by dmitryponomarev** [comment]
+1 on bookmarks problem in firefox:
- create folder with multiple bookmarks in bookmarks toolbar
- click on folder and click on first bookmark from the list
**Result:** bookmark number 4 in the list gets opened (instead of first one)

**Comment by TAforever** [comment]
There is a problem, but it doesn’t always appear, I’ll try to record a video.

**Comment by vaxerski** [comment]
but... firefox doesn't use sdl...?

**Comment by dmitryponomarev** [comment]
I don't have `SDL_VIDEODRIVER` variable, but issue is reproducible for me. Feels like it might be the result of more generic problem: I cannot drag any bookmarks inside a folder. Folders are "draggable" but bookmarks inside a folder are not.

Possibly relevant env variables which I have:
```
WAYLAND_DISPLAY=wayland-1
HYPRLAND_CMD=Hyprland
XDG_BACKEND=wayland
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=Hyprland
MOZ_ENABLE_WAYLAND=1
```

Below is the video:
https://github.com/hyprwm/Hyprland/assets/18329297/65a9c1ed-2fba-4587-a501-d9deef107063

**Comment by vaxerski** [comment]
I have the same and definitely can drag shit around.

Worth noting I am on -git. Can anyone check -git?

**Comment by Schweber** [comment]
I can't check git but on hyprland 0.30.0 in librewolf 118.0.1 i experience Menus opening in the wrong place (the right click context menu even has a variable offset to the mouse cursor depending on its position on screen) and in differing sizes/zoom states. So e.g. if i open the same menu multiple times it might open enlarged/zoomed in a few times and a few times in its correct zoom state, seemingly on random.

Also my mouse cursor is not working in librewolf and a default one is shown. I have set

```
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = _JAVA_AWT_WM_NONREPARENTING,1

env = GTK_THEME,Flat-Remix-GTK-Grey-Darkest
env = XCURSOR_THEME,Bibata-Modern-Amber
env = XCURSOR_SIZE,28
env = NIXOS_OZONE_WL,1
env = MOZ_ENABLE_WAYLAND,1

env = GDK_BACKEND,wayland
#env = GDK_DEBUG,gl-fractional
#env = GDK_SCALE,2
# deaktiviert das Vergrößern des Texts
# export GDK_DPI_SCALE=0.5

env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
#env = QT_SCREEN_SCALE_FACTORS=2
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
```

**Comment by TAforever** [comment]
Yes, the problem is still reproducible

**Comment by Schweber** [comment]
I found the reason for my problems: i set `widget.wayland.fractional-scale.enabled` to `true` in librewolf `about:config` yesterday. I just remembered and when reverting to `false` the problems are gone.

Sorry for the trouble.

**Comment by vaxerski** [comment]
that's a nice clue. Sway-git also supports fractional scale iirc, can you check there?

**Comment by Schweber** [comment]
> that's a nice clue. Sway-git also supports fractional scale iirc, can you check there? Fractional scale seems completely broken for me on firefox-developer-edition atm.

I'm happy with the way things are, everything is working. Just wanted to update you so that you don't follow red herrings.

Thank you for your great work!

**Comment by TAforever** [comment]
Here's a video.

https://github.com/hyprwm/Hyprland/assets/52626363/ebf8f7f0-c319-4ae9-ab69-cfb27f1f12a8

**Comment by TAforever** [comment]
I just compiled hyprland-git because for some reason archlinux is still version 0.30.0 and the problem seems to have gone away. I will test for a few more days and if the problem does not return, I will close the issue.

**Comment by TAforever** [comment]
In version 0.32.3 the problem is resolved.
