### ISSUE TITLE
`swapworkspaces` Dispatcher

### ISSUE THREAD

**Issue by austinliuigi** [hyprwm/Hyprland#3554]
### Description

I would like it if I would be able to swap two workspaces, i.e. swapping workspace 1 and 2 would make it so that all windows initially on workspace 1 end up on workspace 2 and all windows initially on workspace 2 end up on workspace 1.

As far as I cal tell, there isn't currently a way to do this with the available dispatchers.

Thank you!

**Comment by MightyPlaza** [comment]
also scriptable

**Comment by vaxerski** [comment]
scriptable, and like, I don't see a point?

**Comment by austinliuigi** [comment]
Thinking about how to script it, I can only think of a hacky way:
1. save all windows in target workspace
2. move all windows from current workspace to target workspace
    - use `focuswindow` dispatcher first to focus on window to be moved
    - user `movetoworkspace` dispatcher
3. move all windows stored from (1) using the method in (2)

I haven't yet tested this out, but would this be the right approach? Would this keep the window orientations?

**Comment by tchofy** [comment]
I was interested in such functionality, and got something usable based on my limited shell scripting skills:

```
#!/bin/sh

CURRENT_WS_ID=$(hyprctl activeworkspace -j | jq -r ".id")
TARGET_WS_ID="$1"
CURRENT_WS_WINDOWS=$(hyprctl clients -j | jq -r --arg id "$CURRENT_WS_ID" '.[] | select(.workspace.id == ($id | tonumber)) | .address')
TARGET_WS_WINDOWS=$(hyprctl clients -j | jq -r --arg id "$TARGET_WS_ID" '.[] | select(.workspace.id == ($id | tonumber)) | .address')

echo "$CURRENT_WS_WINDOWS" | xargs -I {} hyprctl dispatch movetoworkspacesilent "$TARGET_WS_ID",address:{}
echo "$TARGET_WS_WINDOWS" | xargs -I {} hyprctl dispatch movetoworkspacesilent "$CURRENT_WS_ID",address:{}
```

Usage is `wsswap <number>`. Unfortunately window order isn't preserved, but I think it could be done with further scripting.

The way I've implemented it into my config is with a keychord approach, like this:

```
$reset = hyprctl dispatch submap reset &&
bind = $mainMod, S, exec, sleep 2 && hyprctl dispatch submap reset
bind = $mainMod, S, submap, wsswap
submap = wsswap
bind = , 1, exec, $reset $HOME/.config/hypr/scripts/wsswap 1
bind = , 2, exec, $reset $HOME/.config/hypr/scripts/wsswap 2
bind = , 3, exec, $reset $HOME/.config/hypr/scripts/wsswap 3
bind = , 4, exec, $reset $HOME/.config/hypr/scripts/wsswap 4
bind = , 5, exec, $reset $HOME/.config/hypr/scripts/wsswap 5
bind = , 6, exec, $reset $HOME/.config/hypr/scripts/wsswap 6
bind = , 7, exec, $reset $HOME/.config/hypr/scripts/wsswap 7
bind = , 8, exec, $reset $HOME/.config/hypr/scripts/wsswap 8
bind = , 9, exec, $reset $HOME/.config/hypr/scripts/wsswap 9
bind = , escape, submap, reset
submap = reset
```

So Mod + S to enter the workspace swapping submap, pressing a number will swap windows on the active workspace with the ones on the workspace id that was pressed, at time same time resetting the submap to prevent further unwanted swaps, and if nothing is pressed for 2s it times out.
