### ISSUE TITLE
Gentoo fresh install crash on start from tty

### ISSUE THREAD

**Issue by Mihuy1** [hyprwm/Hyprland#3565]
### Hyprland Version

0.30.0

### Bug or Regression?

Bug

### Description

Can't launch into hyprland.

### How to reproduce

Just type: Hyprland into tty.

### Crash reports, logs, images, videos

[hyprlandCrashReport700.txt](https://github.com/hyprwm/Hyprland/files/12902740/hyprlandCrashReport700.txt)

![20231014_084028](https://github.com/hyprwm/Hyprland/assets/98083973/c032777f-395a-4723-acc3-6e898596d50a)

**Comment by ToolmanP** [comment]
I guess you need include `amdgpu` and `radeonsi` in your make.conf and reemerge the drivers.

**Comment by Mihuy1** [comment]
Yeah, that was the issue, literally just came home and got it.

Thanks!
