### ISSUE TITLE
Set Size for Floating windows

### ISSUE THREAD

**Issue by gguman** [hyprwm/Hyprland#3566]
### Hyprland Version

v0.30.0

### Bug or Regression?

Bug

### Description

Trying to increase a size of floating window. According wiki I've set:

windowrulev2=float,class:^(thunar)$
windowrulev2=size 950 600,floating:1

When I start Thunar then it opens as floating but without resizing

### How to reproduce

1. set windowrulev2=float,class:^(thunar)$
2. set windowrulev2=size 950 600,floating:1

open thunar and check the size of the window

**Comment by FakeMichau** [comment]
There might be some race condition. Trying to use ``windowrulev2 = size 100 100,floating:1`` with rofi sometimes works and sometimes doesn't. Worth adding that rofi floats without any extra window rules.

**Comment by inmny** [comment]
I also meet this.
Exactly:
`
windowrulev2 = float,size 1000 600,class:^(free-kitty)$
`
and same with
`
windowrulev2 = float,size 50% 50%,class:^(free-kitty)$
`
The result is: when open "free-kitty", its size is always the size of the last "free-kitty" closed.

If "free-kitty" is first open, it will be nearly fullscreen.

**Comment by gguman** [comment]
> Trying to use `windowrulev2 = size 100 100,floating:1`

I've tried to use the same command before

**Comment by Estebiu** [comment]
If you open a window directly as floating (´´´windowrule=float,thunar´´´) it should remember the last size it had when you closed it.

**Comment by FakeMichau** [comment]
It doesn't. 
Even if it did work, size still wouldn't come from the window rule meaning it still doesn't work as expected.

**Comment by AngelouDi** [comment]
Here's what I did for my case:

```
windowrulev2 = float,title:(Not\ titled.*)
windowrulev2 = size 1000 600,title:(Not\ titled.*)
```

**Comment by szymon420699** [comment]
hey did u find a solution

**Comment by abkrm** [comment]
I can set the size for a floating window (for example for Discord) as follows:
`windowrulev2 = size 1000 2000, class:(discord)`
And it works as expected.

**Comment by vaxerski** [comment]
I'll close this as stale and likely fixed. Make sure to run thunar in native wl as xwayland has some compatibility issues, as usual
