### ISSUE TITLE
VRAM Memory Leak on window close

### ISSUE THREAD

**Issue by HenrikBGF** [hyprwm/Hyprland#357]
* Steps to reproduce
   * Launch terminal with `watch -n 1 -d nvidia-smi`
   * Launch 2 new kitty instances (or any other terminal) and then close them
* Expected outcome
   * The VRAM usage should decrease after closing the instances
* Noted outcome
   * The VRAM usage instead increases, this happens until your GPU runs out of VRAM, freezes and you have to kill Hyprland for it to release the memory.

While I know NVIDIA support isn't directly there, it's more a question for how to properly fix this as I don't use Discord. A reset was also performed, without making any difference.
Tried `nvidia-open`, `nvidia` and `nvidia-lts` drivers (both DKMS and non), all ending in the same memory leak.

Env:
```
export CLUTTER_BACKEND=wayland
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export MOZ_ENABLE_WAYLAND=1
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
```

nvidia-smi:
Before opening 2 instances:
`0   N/A  N/A       918      G   Hyprland                          294MiB`
After opening and closing 2 instances:
`0   N/A  N/A       918      G   Hyprland                          314MiB`

I've also tried to disable things like blur, which also didn't reduce the leaks. This is using the standard-generated config with changed keybindings and `exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP` added at the bottom.

**Comment by vaxerski** [comment]
are you sure it's related to hyprland? does sway also leak or no?

**Comment by vaxerski** [comment]
doesn't answer my question

**Comment by HenrikBGF** [comment]
> are you sure it's related to hyprland? does sway also leak or no?

Tested and it doesn't seem like it, also tested on Weston and no issues there either

**Comment by vaxerski** [comment]
Not only NVIDIA, can see it on my rig too.

**Comment by vaxerski** [comment]
should be fixed with bf762f566f1c8c5e9c636f0d1ad4e485ad322da9 but please verify.

**Comment by HenrikBGF** [comment]
Seems to be fixed, opening and closing windows flushes the memory to the value seen here
`0   N/A  N/A     32831      G   Hyprland                           53MiB`

I'll give it ~3h before I close the issue, just to make sure.

**Comment by HenrikBGF** [comment]
Fixed, no more than 200mb of VRAM was ever allocated, and it was instantly freed after closing respective processes.

Thanks for the quick fix!

**Comment by MahouShoujoMivutilde** [comment]
I don't think it's fully fixed, VRAM / RAM usage still increases on config reload (file save), and never decreases.

Here I just commented -> saved -> uncommented -> saved one option (binding) a bunch of times:
![screenshot](https://user-images.githubusercontent.com/14999778/194615494-7e7a8668-b81e-4b37-b27d-291a1629732f.png)

System:
* Arch Linux latest
* linux-zen 5.19.13
* nvidia-dkms 515.76-1 ([Instructions](https://wiki.hyprland.org/Nvidia/) from the wiki applied except fixes for flickering)
* Hyprland 0.15.1beta, generated config + few bindings, nothing fancy

**Comment by vaxerski** [comment]
open a new issue plox
