### ISSUE TITLE
fixwlr target was removed, what shall novideo users do?

### ISSUE THREAD

**Issue by NekoCWD** [hyprwm/Hyprland#3577]
### Hyprland Version

d4e4931008cc64e5b94a65c5e692ff9ed459280b

### Bug or Regression?

Regression

### Description

I cannot build `hyprland-nvidia-git` aur package, because fixwlr target was removed from makefile.

### How to reproduce

Try to install hyprland-nvidia-git from aur

**Comment by jasonKoogler** [comment]
Just encountered this last night as well.  Glad I'm not the only one lol.

**Comment by vaxerski** [comment]
we don't maintain that package

**Comment by jasonKoogler** [comment]
Sorry if this is a dumb question, but the aur upstream url points to this repo, who are we supposed to contact about this?

**Comment by vaxerski** [comment]
whoever maintains the package
