### ISSUE TITLE
Some windows acting like pinned windows (in a way)

### ISSUE THREAD

**Issue by LazarusCat59** [hyprwm/Hyprland#3578]
### Hyprland Version

Hyprland, built from branch main at commit 424c9a7e704590db5c823557e5e388e366f7b1cd dirty (render: stop locking SWC on tearing). Tag: v0.30.0-86-g424c9a7e

### Bug or Regression?

Bug

### Description

Some windows act like pinned windows, following me across workspaces. Video attached to show what I mean. Behavior is not exactly consistent across apps, for example in CS2 if I send it to another workspace *after* it followed me to a workspace, then it won't come to the active workspace, but Genshin Impact launcher always ends up on the active workspace. I have seen this issue in CS2, Genshin Impact Launcher, ESO Launcher and a few installers from winetricks (Visual C++ I think I'm not sure). Have tried to use unset windowrule at the end of my config for these windows but it doesn't really help. Tested the same on sway and this issue does not occur there. First time ever opening an issue on github, sorry if I messed up something. Also thanks for all the awesome work on Hyprland!

### How to reproduce

Open CS2 in fullscreen/Genshin Impact Launcher/ESO Launcher, switch to another workspace.

### Crash reports, logs, images, videos

I added the log I got right after I did a bunch of the Genshin Impact launcher shenanigans, not sure if it helps.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12909246/hyprland.log)

CS2:
https://github.com/hyprwm/Hyprland/assets/56857868/3675b667-fbbf-4fc7-8816-81d364ede1e2

Genshin Impact launcher:
https://github.com/hyprwm/Hyprland/assets/56857868/13faaec6-5eb3-4112-a06d-c8a7f10ef6ba

Edit: Had to encode CS2 video to HEVC to get it to upload, so you might need to download it to watch

**Comment by tchofy** [comment]
You could try the instructions in https://github.com/hyprwm/Hyprland/issues/3507, could work for the genshin launcher as well, but if it doesn't, there's the native alternative `anime game launcher` (omitting links due to their own policy), with the same functionality + some extra tweaks.

**Comment by LazarusCat59** [comment]
> You could try the instructions in #3507, could work for the genshin launcher as well, but if it doesn't, there's the native alternative `anime game launcher` (omitting links due to their own policy), with the same functionality + some extra tweaks.

I just tried out the instructions from #3507, it works for CS2 but not for the Genshin Impact launcher. I'm assuming since it doesn't work for Genshin it won't really work for ESO Launcher (don't have it installed rn) or the other wine windows I had issues with. I will try the native alternative for Genshin that you mentioned but that still does not solve the issue for other wine windows, mainly ESO Launcher. I'll leave the issue open for now so as to look for a potential fix. Thanks for the quick reply!

**Comment by beh-10257** [comment]
https://github.com/hyprwm/Hyprland/assets/77834479/5dae4859-c580-4316-8d72-765875004cc4

@tchofy same problem here but I have this behaviour in ubisoft connect launcher as well
I guess a feature to make it so windows are pinned to a certain workspace would be nice

**Comment by vaxerski** [comment]
this might be a configure request from xwayland. in the case of cs2, it's a combo of that and maximize iirc

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13641879/patch.txt)
try

**Comment by tchofy** [comment]
I can report the patch worked for the genshin launcher.

**Comment by LazarusCat59** [comment]
Just built from commit b2e5a80 and tested it, neither genshin launcher nor ubisoft connect acts like that anymore, but if I don't switch back to the workspace quickly, the window is no longer visible. The wine tray icon is still active but using any options from the right-click menu of the tray icon cannot restore the window again. Only way is to exit the program either from tray icon or by killing it and then trying again.

**Comment by vaxerski** [comment]
check on git

**Comment by LazarusCat59** [comment]
Built from 01e5c59 and tested, working perfectly now. Windows do not disappear and does not follow me to any workspaces. Great work, thanks!
