### ISSUE TITLE
auto assign window to workspace by title or class

### ISSUE THREAD

**Issue by enigma158an201** [hyprwm/Hyprland#3579]
After a search on the web, i still haven't found how to auto assign an application to a specific workspace in conf files (even if i launch it in command Line interface, like i3 or sway)

For example, I d like firefox to be assigned to workspace number 2 even when i write firefox in a terminal

Is there a proper way to do it?

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Window-Rules/

**Comment by enigma158an201** [comment]
i tried with this rule and it still doesn't work, what's wrong with it:
windowrule = workspace 2,class:^(firefox)(.*)$,title:^(firefox)(.*)$

**Comment by memchr** [comment]
Wrong regex, if you meant to match firefox, use `^firefox&` [^1].

Also, don't match title, it's not fixed and usually changes to the title of the website in the current tab.

[^1]: (`^(firefox)(.)&` matches something like firefoxa firefoxb, firefox/)

**Comment by enigma158an201** [comment]
Sorry for late answer, a string like `term` works as well for terminator 👍
