### ISSUE TITLE
CMake after improvements in the pipeline requires systemd. 

### ISSUE THREAD

**Issue by therafal** [hyprwm/Hyprland#3585]
### Hyprland Version

1f58245

### Bug or Regression?

Regression

### Description

Previously, when compiling without libsystemd it would throw up that it was unavailable, but WM would compile and run without any problems. After recent updates, Meson terminates the compilation with code 1. 

### How to reproduce

Install hyprland-git on a system with an init system other than `systemd`.

## meson-log.txt
```
Preliminary CMake check failed. Aborting.
Run-time dependency libsystemd found: NO (tried pkgconfig and cmake)
 
meson.build:54:14: ERROR: Dependency "libsystemd" not found, tried pkgconfig and cmake
```

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12910500/patch.txt)

try this. Please note the `NO_SYSTEMD` flag still exists.

**Comment by therafal** [comment]
Seems like it works. Thanks

**Comment by vaxerski** [comment]
8af3e7beebb96eceb8a094a20286d57e3b135938

**Comment by therafal** [comment]
Also, the package doesn't build through AUR helpers(paru and yay) after the latest update of the PKGBUILD without libsystemd. Is it because of the switch from make to meson in the `build()` function? Is this temporary or should there be a separate package on AUR for the non-systemd version?

**Comment by vaxerski** [comment]
no clue, as the aur maintainers.

**Comment by tchofy** [comment]
[I got it to build after following these instructions from the nvidia package.](https://aur.archlinux.org/packages/hyprland-nvidia-git#comment-938449)

**Comment by therafal** [comment]
> [I got it to build after following these instructions from the nvidia package.](https://aur.archlinux.org/packages/hyprland-nvidia-git#comment-938449)

Yeah, changing back to the `make` fixes all of the issues. Gonna write later to the AUR guys.
