### ISSUE TITLE
Drop down menus disappear when nested on Jet Brains IDE's

### ISSUE THREAD

**Issue by ashdevelops** [hyprwm/Hyprland#3596]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0 flags: (if any)

### Bug or Regression?

Bug

### Description

Upon navigating popup-based drop down menus on JetBrains IDE's, when going into a nested menu both parent and child menus disappear.

### How to reproduce

A lot of existing reports are made here where they've just remained unsolved, check history.

I've tried lots of things such as setting `-Drecreate.x11.input.method=true` VM option

Tried setting these window rules no luck
```
windowrulev2 = forceinput,class:^(jetbrains-.*)
windowrulev2 = windowdance,class:^(jetbrains-.*) # allows IDE to move child windows
```

The class is indeed jetbrains-whatever, so jetbrains-phpstorm or jetbrains-rider, happens on them all.

### Crash reports, logs, images, videos

N/A

**Comment by TheSunCat** [comment]
JetBrains menus work fine for me, without any special window rules. I do have `_JAVA_OPTIONS` set to this, but I don't think it affects it:
```
-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
```

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

**Comment by romanstingler** [comment]
can be closed
