### ISSUE TITLE
Window rule doesn't work, popup windows spawn at first monitor top left regardless of explicitly stating center

### ISSUE THREAD

**Issue by ashdevelops** [hyprwm/Hyprland#3597]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Popup based windows are spawning at the top left of my left monitor, even if the IDE window is on the right monitor?

Window rule:
`windowrule = center, class:jetbrains-phpstorm`

Debugging:
```
sleep 5; hyprctl activewindow
Window 55bb7e5da660 -> win5:
	mapped: 1
	hidden: 0
	at: 0,0
	size: 332,69
	workspace: 1 (1)
	floating: 1
	monitor: 1
	class: jetbrains-phpstorm
	title: win5
	initialClass: jetbrains-phpstorm
	initialTitle: win5
	pid: 725147
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0


```

### How to reproduce

Exists for everyone just installed lasted hyprland, jetbrains and see for yourself.

**Comment by MightyPlaza** [comment]
above should fix
@vaxerski
