### ISSUE TITLE
Provide debug symbols on debuginfod

### ISSUE THREAD

**Issue by danielkrajnik** [hyprwm/Hyprland#3599]
### Description

Would it be possible to upload Hyprland debug symbols? It would be really helpful!

Alternatively is there any way to debug a packaged Hyprland? Or is it necessary to compile it from source and start from scratch (it would be really hard to replicate the  exact configuration that is shipped with packages).

Sorry, I'm new to many of these things and struggling to get displaylink to work. Any advice would be really appreciated.

**Comment by memchr** [comment]
It's the packager's job.

**Comment by romanstingler** [comment]
@danielkrajnik https://github.com/hyprwm/Hyprland/issues/2752 have you read this ?

**Comment by danielkrajnik** [comment]
sorry, I'll close it then. But if you are using ArchLinux could you kindly [suggest any solution](https://www.reddit.com/r/archlinux/comments/17a799o/can_you_rebuild_a_package_with_debug_symbols/) for adding debug symbols to a package? I'm stuck and can't even figure out how to setup debugging.

**Comment by memchr** [comment]
@danielkrajnik 

edit /etc/makepkg.conf 
```
options=(debug !strip)
```

or enable both to separate debug and main package

```
options=(debug strip)
```

**Comment by danielkrajnik** [comment]
> @danielkrajnik #2752 have you read this ?

@romanstingler  Yes, you can see my comments below.

I'm pretty sure I've researched this topic thoroughly for the past two days and no resources were published that address this specific issue yet, so manual debugging of the source code may be necessary.

**Comment by danielkrajnik** [comment]
@memchr  Thank you very much! But I don't think that this specific package published a separate version with debug symbols. That's what you're suggesting right? To add extra "channel" of packages?

> However, Hyprland PKGBUILDS may require manual modification to remove options that disable debugging symbols.

Exactly, that's what I'm trying to do. Do you know how to install a PKGBUILD that has been modified locally?

**Comment by memchr** [comment]
If you plan to debug, there is no need to build a separate package. You can just `meson setup build`, `ninja -C build` and `gdb ./build/src/Hyprland`

**Comment by danielkrajnik** [comment]
Thank you, the problem is that this package also applies a patch (for displaylink to work), as well as customizes wlr. Is there any way to add this changes to PKGBUILD directly and "trick"  paru into thinking that they were always there, so to create the exact same binaries, but with these local changes (debug symbols)?

**Comment by memchr** [comment]
Use `patch -n1 < path_to.patch` or `git pull origin pull/pr_number/head --no-edit` if it is in a PR.

**Comment by danielkrajnik** [comment]
Thank you, but there are many many other steps that this package includes and may include in the future, so it's not really possible trying to replicate them all. I was hoping just to modify PKGBUILD and let pacman or paru install it as usual? Is this not possible?

**Comment by memchr** [comment]
Can you be more specific? 
- What is the source of the patch, github or standalone patch files?
- What do you intend to do with the debug info? Are you trying to debug hyprland?

**Comment by danielkrajnik** [comment]
Sorry, the patch, the changes everything is already provided in [the AUR package](https://aur.archlinux.org/packages/hyprland-displaylink-git). It's practically ready to install, the only thing are the debug symbols.

All I'm trying to do is just to rebuild this package again with `make debug` instead of `make release`. Just change that line and run paru -S hyprland-displaylink-git or makepkg PKGBUILD or any command that is necessary to rebuild this package. I can't seem to find any documentation on this process (of adding local changes to an AUR package), so apologies if this questions sounds strange.

**Comment by memchr** [comment]
Debugging is better done without packaging, as a full package build is rather slow and may prevent incremental compilation.

Please try the following commands.

```bash
git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/hyprwm/hyprland
cd hyprland
curl -LO 'https://aur.archlinux.org/cgit/aur.git/plain/displaylink.patch?h=hyprland-displaylink-git'
patch -d subprojects/wlroots -Np0 < displaylink.patch
meson setup build --buildtype=debug --debug --wipe -Db_pch=false
ninja -C build
```

The resulting binary with debug symbols is in build/src/Hyprland. You can directly execute it with `./build/src/Hyprland`. Or debug with `gdb build/src/Hyprland`

I also recommend a feature-rich editor or IDE for debugging, using gdb directly is not very convenient.

**Comment by danielkrajnik** [comment]
Thank you very much for your detailed instructions, however at this stage it was easier just to change make release to make debug and run makepkg -i (I wasn't aware that it is that easy - a single command). I had to educate myself about ABS (arch build system) to understand that it's all that aur helpers / pacman are doing and it doesn't require messing with GPG keys of changing checksum values. It also didn't seem to override these changes on the next udpate (although it may do it later with my luck...)

Sorry for not trying to build it from source at this point - I will try it if it turns out to be necessary to frequently rebuild the package. Yes, rebuilding it takes time (especially recompiling the wlroots "subproject"), but at this stage I really only need the debug symbols to just understand what is causing the issue - the issue may be completely elsewhere in the system.
