### ISSUE TITLE
Fails to build on aarch64

### ISSUE THREAD

**Issue by nolight132** [hyprwm/Hyprland#3600]
Failed to build from AUR on Arch Linux ARM (Mac). Assuming it's not a Hyprland-related bug, just trying to figure out where to submit it.

`[4/103] Building CXX object hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o
FAILED: hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o 
/usr/bin/c++ -DHAS_EXECINFO -DUSES_SYSTEMD -DWLR_USE_UNSTABLE -Dhyprctl_EXPORTS -I/home/pavelolizko/Hyprland/. -I/home/pavelolizko/Hyprland/src -I/home/pavelolizko/Hyprland/subprojects/wlroots/include -I/home/pavelolizko/Hyprland/subprojects/wlroots/build/include -I/home/pavelolizko/Hyprland/subprojects/udis86 -I/home/pavelolizko/Hyprland/protocols -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -MD -MT hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o -MF hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o.d -o hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o -c /home/pavelolizko/Hyprland/hyprctl/main.cpp
/home/pavelolizko/Hyprland/hyprctl/main.cpp:15:10: fatal error: format: No such file or directory
   15 | #include <format>
      |          ^~~~~~~~
compilation terminated.
[9/103] Building C object subprojects/u...s86/CMakeFiles/libudis86.dir/decode.c.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:15: release] Error 1
make[1]: Leaving directory '/home/pavelolizko/Hyprland'
make: *** [Makefile:31: all] Error 2 `

**Comment by MightyPlaza** [comment]
my guess is your gcc version is too old (12.x) https://archlinuxarm.org/packages/aarch64/gcc

**Comment by vaxerski** [comment]
thats the issue indeed
