### ISSUE TITLE
bug: special workspaces don't close with `misc:close_special_on_empty` enabled

### ISSUE THREAD

**Issue by ozwaldorf** [hyprwm/Hyprland#3602]
### Hyprland Version

Hyprland, built from branch main at commit 54e1c2ccbdfa6dfade63221b5df02bf8578d96a6 dirty (fix(build): do not include wlr headers directly, use includes.hpp instead. (3587)). Tag: v0.31.0-1-g54e1c2cc  flags: (if any) debug

### Bug or Regression?

Bug

### Description

The newly added config `misc:close_special_on_empty` does not have any effect when moving the last window out of the special workspace via a dispatch keybind or moving the window with the mouse. Previously, before the config was added, either of these actions would close the special workspace.

### How to reproduce

1. Move a window into a special workspace and open the workspace. 
2. Move the window out of the workspace with a dispatch keybind.
3. Pick up the window with the mouse and release it
4. The window will be moved into the special workspace, showing that it did not close correctly.

OR

1. Move a window into a special workspace and open the workspace.
2. Pick up the window with the mouse and release it.
3. The window will move back into the special workspace, instead of it being closed and the window moving to the normal workspace behind it.

**Comment by CDTay** [comment]
Still having this issue. Moving with the mouse doesn't close the special workspace despite the implication of close_special_on_empty being that if the last window is removed the special workspace will close (silent or not).

Regardless, moving with the mouse seems inherently not "silent", so it feels like it should close the special workspace when moving a window out of it.
