### ISSUE TITLE
`misc:new_window_takes_over_fullscreen = 1` does not respect the `fullscreen, 1` mode

### ISSUE THREAD

**Issue by xrevv** [hyprwm/Hyprland#3603]
### Hyprland Version

Hyprland, built from branch HEAD at commit 5b8cfdf2efc44106b61e60c642fd964823fd89f3  (props: bump ver to v0.31.0). Tag: v0.31.0  flags: (if any) debug

### Bug or Regression?

Bug

### Description

`misc:new_window_takes_over_fullscreen = 1` does not respect the `fullscreen, 1` mode (maximize (keeps gaps and bar(s))).
Minimal sample config:
```
bind = $mainMod, W, fullscreen, 1
misc {
    new_window_takes_over_fullscreen = 1
}
```

### How to reproduce

- Set `misc:new_window_takes_over_fullscreen = 1` 
- Open at least 2 windows
- Maximize one (`fullscreen, 1`)
- Open a new window
- The new window goes full-screen (`fullscreen, 0`) instead of maximized (`fullscreen, 1`)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/pull/3588
