### ISSUE TITLE
SFML issue opening window

### ISSUE THREAD

**Issue by FukuInTheCode** [hyprwm/Hyprland#3604]
### Hyprland Version

Hyprland, built from branch main at commit 5ffb1032e171b88dc45e0169159e449989a0fc58 dirty (events: don't focus new window if spawned behind fullscreen). Tag: v0.30.0-44-g5ffb1032

### Bug or Regression?

Bug

### Description

Hello, I'm currently trying to using SFML (more precisely CSFML in C), and I tried to open a basic window using the lib and the code below
`#include <SFML/Graphics.h>

int main(int argc, char **argv)
{
    sfVideoMode mode = {1000, 1000, 32};
    sfRenderWindow *w = sfRenderWindow_create(mode,
        "test", sfDefaultStyle, NULL);

    sfEvent evt;
    while (sfRenderWindow_isOpen(w)) {
        while (sfRenderWindow_pollEvent(w, &evt)) {
            if (evt.type == sfEvtClosed)
                sfRenderWindow_close(w);
        }
    }
    sfRenderWindow_destroy(w);
}`

I have no problem compiling the code with SFML, and if I run the output on another distro it work fine.
When I look at `hyprctl clients` it give me:
`Window 55d6f410a990 -> :
	mapped: 0
	hidden: 0
	at: 0,0
	size: 0,0
	workspace: -1 ()
	floating: 0
	monitor: -1
	class: 
	title: 
	initialClass: 
	initialTitle: 
	pid: 0
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 55d6f4a150a0 -> :
	mapped: 0
	hidden: 0
	at: 0,0
	size: 0,0
	workspace: -1 ()
	floating: 0
	monitor: -1
	class: 
	title: 
	initialClass: 
	initialTitle: 
	pid: 3941
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

Window 55d6f4a16570 -> :
	mapped: 0
	hidden: 0
	at: 0,0
	size: 0,0
	workspace: -1 ()
	floating: 0
	monitor: -1
	class: 
	title: 
	initialClass: 
	initialTitle: 
	pid: 0
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
`
If you can help me with this problem I would be very glad.
Thanks for reading.

### How to reproduce

install CSFML and it's depedancies.
compile the code I gave.

**Comment by vaxerski** [comment]
why is this a hyprland issue? This is not a sfml help forum?
