### ISSUE TITLE
Plugging in monitor crashes Swaylock

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#3605]
### Hyprland Version

v0.31.0-7-ga0b675ec

### Bug or Regression?

Bug

### Description

Swaylock crashes when pluggin in external monitor.
I do have misc:allow_session_lock_restore set to true, but that doesn't seem to restart swaylock.
This doesn't happen in sway.
Can someone confirm this is a problem? 

### How to reproduce

1) Launch swaylock
2) Attach monitor
3) Booom

**Comment by MightyPlaza** [comment]
does it happen on sway-git?
also you may still need to manually restart swaylock by killing it and starting it again iirc
