### ISSUE TITLE
xdg-desktop-portal-hyprland uses two full cpu cores whenever I exit and re-enter hyprland

### ISSUE THREAD

**Issue by benthejack-vuw** [hyprwm/Hyprland#3606]
### Hyprland Version

v0.30.0

### Bug or Regression?

Bug

### Description

Whenever I exit hyprland (using keybind to exit function) and re-enter from sddm, xdg-desktop-portal-hyprland continuously uses 2 full cores of processing. This seems to happen every time I re-launch hyprland from the display manager and requires a full reboot to fix.

nixos unstable

### How to reproduce

Exit hyprland via keybind (to sddm in my case, will check with other DMs)
re-enter hyprland
run top - .xdg-desktop-portal-hyprland will take large amounts of cpu (way more than before the exit/re-enter)

### Crash reports, logs, images, videos

![area-18-10-2023_10-54-40](https://github.com/hyprwm/Hyprland/assets/20331719/c9fb538c-8a29-4cfe-bb0d-57a2f1cbafca)
![area-18-10-2023_10-54-21](https://github.com/hyprwm/Hyprland/assets/20331719/c5a3c403-5692-4d69-9aac-ae29654a78a1)
[hyprland-log.txt](https://github.com/hyprwm/Hyprland/files/13010952/hyprland-log.txt)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/116
