### ISSUE TITLE
Floating focused window does not go to the top of the stack

### ISSUE THREAD

**Issue by ymnejmi** [hyprwm/Hyprland#3608]
### Hyprland Version

v0.31.0

### Bug or Regression?

Bug

### Description

Floating window does not go to the top of the stack on keyboard focus and needs to be clicked with the mouse, this is especially annoying when the focused window is completely covered with another floating window, so you have to move/resize the bigger window to click the window you want to focus..
I am aware of the `alterzorder` and `bringactivetotop` dispatchers, and plan on using one of them as workaround for the time being, but I really do believe that bringing active to top should be default behaviour, or a variable to be toggled.

### How to reproduce

- create 2 floating windows.
- overlap them.
- move focus between the 2 (im using cyclenext binded on alt tab).

expected behaviour:
 focused window covers all other.
actual behaviour:
 focused window stays covered by other window.
 [attachment](https://github.com/hyprwm/Hyprland/assets/134085326/f96ef5f3-b16e-499c-bc7e-7d747e8b8774)

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/134085326/f96ef5f3-b16e-499c-bc7e-7d747e8b8774

**Comment by Seme4eg** [comment]
i guess my issue is related. 
when being in fullscreen (pseudo or not doesn't matter) mode and opening a floating window (`bind = SUPERCTRL, Return, exec, [float] foot`), it appears on top of fullscreen window, but isn't focused, like there is a 'noinitialfocus' rule, but there isn't. I am aware of `new_window_takes_over_fullscreen`, but when set to 2 it just unfullscreens me whenever any floating window pops up (ie steam friends playing something), which is really annoying. So this value is set to 0 for me and i can't replicate old behavior when newly opened floating windows weren't behind the stack and were opening having focus right away without me clicking on them.

**Comment by imxyy1soope1** [comment]
expected behaviour

**Comment by vaxerski** [comment]
as above
