### ISSUE TITLE
Debugging Hyprland in tty with gdb completely freezes the machine. 

### ISSUE THREAD

**Issue by danielkrajnik** [hyprwm/Hyprland#3609]
### Hyprland Version

0.30.0-1

### Bug or Regression?

Bug

### Description

when Hyprland crashes while running under gdb (e.g. `gdb Hyprland`) it freezes the machine completely. Can't input anything, can't Ctrl+C or change to other tty. It happens even if it's being debugged remotely (e.g. `gdbserver 127.0.0.1:8000 Hyprland`).

I don't know if it's universally reproducible or specific to this type of crash, but if anyone has some crashing Hyprland and could confirm that would be really helpful. I'm bending backwards right now trying to get the [displaylink package](https://aur.archlinux.org/packages/hyprland-displaylink-git) to work and it seems to be going nowhere for the past two days.

### How to reproduce

1. switch to tty1 
`Ctrl Alt F3`

2. run Hyprland under gdb in a faulty configuration that will make it crash:
`gdb Hyprland`

3. Your computer should become unresponsive now.

### Crash reports, logs, images, videos

Just the usual log: https://pastebin.com/ubkGr9Vy

**Comment by vaxerski** [comment]
thats how gdb works?

**Comment by danielkrajnik** [comment]
I went around it without having to hard reset the PC by setting up ssh access on Termux (or any other machines) and killing gdbserver remotely - that unlocks the tty.

**Comment by danielkrajnik** [comment]
@vaxerski if you have seen this an have any idea how to get around it that would be really appreciated. After `wlr_backend_autocreate` gdb just freezes and I am unable to continue debugging it. It takes over the entire machine and I can't continue solving the issue. It seems to be checking enviornment variables for "WAYLAND_DISPLAY" or "DISPLAY".

**Comment by vaxerski** [comment]
launch hyprland, ssh to your computer from another one, and do `sudo gdp -p $(pidof Hyprland)`. You'll now be able to control gdb from ssh

**Comment by danielkrajnik** [comment]
Sorry, are you sure that it works?

````
Attaching to process 1392085
warning: process 1392085 is already traced by process 1380924
ptrace: Operation not permitted.
````

It doesn't seem to attach. I've run `echo 0 > /proc/sys/kernel/yama/ptrace_scope`, but it still doesn't allow you to connect to gdb if it's already traced by another gdb process?

**Comment by vaxerski** [comment]
it's because you launched hyprland via gdb. Launch it normally, with `Hyprland`. Not `gdb Hyprland`.

**Comment by danielkrajnik** [comment]
@vaxerski thank you, but Hyprland immediately crashes, so I won't be abel to connect to with gdb before it exits...

I don't know if that's possible, but do you think there is any way to prevent gdb from grabbing input? Is this a normal behavior? Perhaps it has some standard name I could search for?

**Comment by vaxerski** [comment]
this is normal behavior and can't really be prevented.

What you can do is clone hyprland, add a `sleep(20);` in main() before it launches and debug that :)

**Comment by danielkrajnik** [comment]
@vaxerski No worries, it's run from [this AUR package](https://aur.archlinux.org/packages/hyprland-displaylink-git), so modifying it is easy.

It grabs input immediately after call to the `wlr_backend_autocreate` function, so I will start there.

**Comment by vaxerski** [comment]
I recommend putting the sleep as the first thing in the `int main`.

**Comment by danielkrajnik** [comment]
ok, I will try it.

I've also noticed that evsieve is still able to grab input events to virtual machines when this infinite loop happens, so it might be also possible to use it to block Hyprland and bring input back to other sessions.

**Comment by danielkrajnik** [comment]
@vaxerski thank you for your help again. Starting a virtual machine and running gdb+emacs there (and gdbserver on hsot tty) allows for seamless debugging even when Hyprland grabs all the input events.

I know this outside of the scope of the project, but can I ask you about your opinion on displaylink? KWin managed to get it to work flawlessly on Wayland and there were some success stories on wlrtoots, but this is still quite difficult to wrap your head around - do you think there is any point trying to debug this? Is there any chance for this to work on Hyprland?

**Comment by vaxerski** [comment]
displaylink support would be left to wlroots, not hyprland.
