### ISSUE TITLE
wlr_backend_autocreate() failed

### ISSUE THREAD

**Issue by Moncheeta** [hyprwm/Hyprland#361]
I'm running nixos-unstable on an Nvidia GTX 1650 Super gpu. I tried launching Hyprland from lightdm, sddm, and the tty.

Hyprland seems to launch for a few seconds before returning back to either lightdm or sddm. I have even tried launching sway it seems to have the same behavior.

When I tried launching Hyprland from a tty, I got
```
00:00:00.005 [ERROR] [backend/backend.c:217] Found 0 GPUs, cannot create backend
00:00:00.005 [ERROR] [backend/backend.c:386] Failed to open any DRM device
terminate called after throwing an instance of 'std::runtime_error'
  what():  wlr_backend_autocreate() failed!
```
Could this be something with Wayland since openbox on Xorg launches fine on my gpu.

**Comment by vaxerski** [comment]
please read the wiki. Wayland does not work on NVIDIA out of the box, you need to apply certain kernel parameters and envvars.

https://www.youtube.com/watch?v=RtxiYW-s3bE

this video is adequate, apply the same steps to hyprland and ignore the wlroots-eglstreams part.

For more info, RTFW and use google.
