### ISSUE TITLE
Swapping workspace also moves CS2.

### ISSUE THREAD

**Issue by MichaelDeets** [hyprwm/Hyprland#3610]
### Hyprland Version

main

### Bug or Regression?

Bug

### Description

Using the default configuration for window rules; switching to a different workspace also moves CS2, without being instructed to.

It can be mitigated using window rules; the first rule should tile CS2, the second should fullscreen or maximize CS2. 

1. `windowrulev2=tile, class:(cs2)`
2. `windowrulev2=maximize, class:(cs2)` or `windowrulev2=fullscreen, class:(cs2)`

From this this, toggling fullscreen will switch between tiled/normal, and fullscreen. Without doing this, it will instead switch between normal fullscreen and "fullscreen" but with the aforementioned issues where the window moves workspace on its own.

I would imagine this issue extends to other fullscreen xwayland applications, but I have only tested two (CS2 and BattleBit) so I don't want to claim otherwise.

I apologise if this has already been issued; but from some searching, I couldn't find anything relevant.

### How to reproduce

Run CS2 in fullscreen, then attempt to switch workspace.

**Comment by vaxerski** [comment]
cs2 issue, use the nofullscreenrequest and nomaximizerequest rules
