### ISSUE TITLE
crash when disconnect monitor

### ISSUE THREAD

**Issue by bootids** [hyprwm/Hyprland#3613]
### Hyprland Version

v0.31.0-8-gd70cc88d

### Bug or Regression?

Bug

### Description

When switching or powering off the display, Hyprland crashes when both my hosts are connected to the same monitor via KVM.
Furthermore, there are no crash logs generated under the ~/.hyprland/ directory.

### How to reproduce

When turning off the monitor while using Hyprland.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13038705/hyprland.log)
[hyprctl monitors output.log](https://github.com/hyprwm/Hyprland/files/13038708/hyprctl.monitors.output.log)

**Comment by vaxerski** [comment]
where crash report?
