### ISSUE TITLE
proton games not working

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#3618]
### Hyprland Version

hyprland-git 0.31.0.r12.38670856-1

### Bug or Regression?

Bug

### Description

proton games does not launch, steam button play hangs as if the game is running, but no window appear.
Works fine on gnome wayland by the way, so the issue is hyrland.

### How to reproduce

play steam proton game

**Comment by killown** [comment]
extra/hyprland 0.30.0-1 works fine with proton games

**Comment by vaxerski** [comment]
`git bisect` then

**Comment by killown** [comment]
issue solved by manually compiling, [Chaotic-AUR] package is the issue, thank you
