### ISSUE TITLE
CS2 is not full screen in 4:3 1024x768 display mode in Hyprland

### ISSUE THREAD

**Issue by leagyrosix** [hyprwm/Hyprland#3620]
### Hyprland Version

V0.30.0

### Bug or Regression?

Bug

### Description

My monitor is 1920x1080@144. I am using Arch Linux. When I open the CS2 game in the Hyprland window manager and set it to 4:3 1024x768, black bars appear and it is not full screen. My monitor is 1920x1080@144. I am using Arch Linux. When I open the CS2 game in the Hyprland window manager and set it to 4:3 1024x768, black bars appear and it is not full screen.

### How to reproduce

Open cs2 on steam and change resolution to 4:3 aspect ratio

**Comment by vaxerski** [comment]
this is a cs2 issue. Also, https://github.com/hyprwm/hyprland-plugins/tree/main/csgo-vulkan-fix

**Comment by leagyrosix** [comment]
Thank you, fixed but this time in cs2 menu mouse offset is wrong
