### ISSUE TITLE
How to focus the next floating window in the current workspace?

### ISSUE THREAD

**Issue by karb94** [hyprwm/Hyprland#3621]
I would like to have a shortcut to cycle through floating windows in the current workspace. Is this possible in Hyprland? I can see that there is the `focuswindow` dispatcher but it only seems to accept the class, title, pid and adress attributes.

Thank you.

**Comment by vaxerski** [comment]
no, it's not possible. You can write a script though.

Also, invalid issue, didn't use a template, closing.
