### ISSUE TITLE
The Obs-studio mouse cursor is not visible  when move cursor into obs window.

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#3623]
### Hyprland Version

Hyprland, built from branch main at commit 386708563c3d9d85ffd60b4eeb6c767d29f948db dirty (workspacerules: search forspecial properly). Tag: v0.31.0-12-g38670856  flags: (if any) debug

### Bug or Regression?

Bug

### Description

 The Obs-studio mouse cursor is not visible  when move cursor into obs window.

https://github.com/hyprwm/Hyprland/assets/30348075/34ea2a10-4c33-43a7-b0fb-e3a0d70d9939

there are a same problem in dwl:

https://github.com/djpohly/dwl/issues/500

### How to reproduce

1.open obs-studio and move mouse curor into obs window

**Comment by vaxerski** [comment]
no issue here.

**Comment by DreamMaoMao** [comment]
I didn't see an exception in the log. 
When I went back to version 0.30.0 the problem disappeared

**Comment by DreamMaoMao** [comment]
When I disable cursor_shape the problem disappeared

![image](https://github.com/hyprwm/Hyprland/assets/30348075/e004dd96-005d-43f1-983f-e01bc287da95)

https://github.com/hyprwm/Hyprland/assets/30348075/dd8e7529-46b9-4a87-95ef-d028a12eed3e

**Comment by vaxerski** [comment]
this now means that every program utilizing that protocol is unable to work properly though.

**Comment by DreamMaoMao** [comment]
When I explicitly specified the topic with hyprctl setcuror, the cursor disappeared issue was resolved
