### ISSUE TITLE
HELP! xdg-desktop-portal-hyprland  high cpu 

### ISSUE THREAD

**Issue by wxn5211** [hyprwm/Hyprland#3627]
### Hyprland Version

0.30

### Bug or Regression?

Bug

### Description

I don't know whats wrong with xdg-desktop-portal-hyprland after use OBS

### How to reproduce

It's first time

**Comment by vaxerski** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/116
