### ISSUE TITLE
[glfw error 65544] Wayland fatal display error : protocol error #6741

### ISSUE THREAD

**Issue by alopezj97** [hyprwm/Hyprland#3636]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0 flags: (if any)

### Bug or Regression?

Bug

### Description

Using kitty in Hyprland doesn't work. There are three scenarios:

1. When trying to run kitty using `SUPER+q` (default keybinding), it doesn't open.
2. When trying to run kitty from the rofi menu (`SUPER+r` + select kitty), it doesn't open and the system kind of gets unresponsive for a few seconds.
3. When trying to run it from another terminal, in my case foot, it shows the following error (see screenshot attached).

**Additional context**

I'm running my installation of Arch Linux in a VM using VMware Workstation. Before jumping to reply that the issue is based on the fact that I'm using a VM, please read:

- I did set Accelerate 3D graphics to true (in fact first in another installation I set it to false to verify that the error message was not the same).
- It is not related to the virtualization software. If I use KDE instead of Hyprland for example, kitty works fine, so either it is a configuration issue or a dependency issue.

### How to reproduce

1. Install arch using archinstall and select Hyprland desktop profile
2. Once installed, run kitty from Hyprland

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/22918075/be4a4e94-e107-4401-a65e-e26ddce2036a)

![image](https://github.com/hyprwm/Hyprland/assets/22918075/1d1444f7-353e-45a2-bc5c-44b629835ab5)

**Comment by vaxerski** [comment]
it's an issue on your system, possibly with the vm or kitty. As you said yourself, other things work.
