### ISSUE TITLE
Workspace focus

### ISSUE THREAD

**Issue by BlanXyz** [hyprwm/Hyprland#3642]
### Hyprland Version

a0b675ec9e57af8bc631fc8cc54d062b58669a9f

### Bug or Regression?

Regression

### Description

Before updating from Tag: ``` v0.31.0-7-ga0b675ec. ```
The behavior of launched windows with  a workspace window-rule, was that they would movesilently resulting in no workspace focus switch. 
Since updating the workspace focus switches as these window's launch.
```
noinitialfocus 
```
window rule, does not change this behavior.

Use cases: 
1) Launching window in special/normal workspace 
On startup, for later access.

2) keybind that starts window in special workspace and sleeps x,before toggling.

### How to reproduce

Open a window with a workspace, window-rule from a different workspace. Focus will switch to new window's workspace.

**Comment by MightyPlaza** [comment]
don't see an issue here, use `silent` if you want to open it on a workspace without changing to it

**Comment by BlanXyz** [comment]
> don't see an issue here, use `silent` if you want to open it on a workspace without changing to it

My Apologies, I missed the silent option. Thankyou!
