### ISSUE TITLE
Crash on startup when USB keyboard is connected

### ISSUE THREAD

**Issue by rowanG077** [hyprwm/Hyprland#3645]
### Hyprland Version

Hyprland, built from branch  at commit v0.30.0  ().

### Bug or Regression?

Bug

### Description

When logging in when I have USB keyboard connected without fail hyprland instantly crashes.

When I first login and then reconnect my keyboard it works.

I'm running hyprland on apply silicon with nixos

### How to reproduce

Have USB keyboard connected

### Crash reports, logs, images, videos

[hyprlandCrashReport1474.txt](https://github.com/hyprwm/Hyprland/files/13090148/hyprlandCrashReport1474.txt)

**Comment by vaxerski** [comment]
doesn't look like related to your keyboard. wlroots can't find a GPU. Issue on your side.

**Comment by rowanG077** [comment]
Any idea how I can debug this further?

If I manually start Hyprland from a terminal entered with ctrl+alt+f3 it works fine.

**Comment by vaxerski** [comment]
then it's your login manager's fault most likely. Ask those people
