### ISSUE TITLE
Can't set correct resolution on my display 

### ISSUE THREAD

**Issue by JaimeJimenezG** [hyprwm/Hyprland#3646]
### Hyprland Version

 built from branch main at commit 015664eb4cde5ab93cfacbfd8c2e831eeb876634 dirty 

### Bug or Regression?

Bug

### Description

Can't set the correct resolution on my display, it just don't go over 100hz on the 2nd display, when it should be 165.

I have 2 displays
1. 1920x1080@144 (No problem)
2. 3440x1440@165 (cannot go over 100)

Also I'm in a system with a GTX 970 dedicated to Hyprland and a 3080 that servs a windows trugh a VM with Windows.
 
i tried a lot of different things, like edit params on grub and generate an EDID configuration and injecting it... nothing has been successfully to show the correct mode. Also a tried to inject the modeline with 3440x1440@165 properties to the hyprland config, but this will just crash the selected resolution making it inaccessible until a reboot.

Il provide a log of my wlr-randr if someone need some thing more to try to see what's wrong tell me and I will add it.

Thank u for any collaboration.

### How to reproduce

Thats a good question.

Monitor Works good, before I was on Windows with near the same configuration and was working fine... also on Xorg system was working as intended.

### Crash reports, logs, images, videos

┌──────────────────────────────────────────┐ 
​ ​​  OS : ArcoLinux x86_64 
​​ ​  Kernel : 6.5.8-arch1-1 
​​ ​  Packages : 1391 (pacman) 
​​ ​  Resolution : 3440x1440 
​​ ​  DE : Hyprland 
​​ ​  Terminal : kitty 
└──────────────────────────────────────────┘ 
┌──────────────────────────────────────────┐ 
​​ ​  CPU : Intel i9-9900KF (16) @ 5.000GHz 
​​ ​  GPU : NVIDIA GeForce RTX 3080 Lite Hash Rate 
​​ ​  GPU : NVIDIA GeForce GTX 970 
​​ ​  GPU Driver : NVIDIA 535.113.01 
​​ ​ ﬙ Memory : 3171MiB / 32012MiB 
└──────────────────────────────────────────┘ 

DP-1 "Huawei Technologies Co., Inc. ZQE-CAA 0xC080F622 (DP-1)"
  Make: Huawei Technologies Co., Inc.
  Model: ZQE-CAA
  Serial: 0xC080F622
  Physical size: 800x330 mm
  Enabled: yes
  Modes:
    3440x1440 px, 99.982002 Hz (preferred, current)
    3440x1440 px, 59.973000 Hz
    2560x1440 px, 59.951000 Hz
    2580x1080 px, 164.686005 Hz
    2580x1080 px, 59.939999 Hz
    1920x1080 px, 119.878998 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.938999 Hz
    1920x1080 px, 50.000000 Hz
    1680x1050 px, 59.953999 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1280x960 px, 60.000000 Hz
    1152x864 px, 75.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.943001 Hz
    1280x720 px, 50.000000 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 70.069000 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 72.188004 Hz
    800x600 px, 60.317001 Hz
    800x600 px, 56.250000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 72.808998 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.929001 Hz
  Position: 1920,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
DVI-I-1 "BNQ ZOWIE XL LCD FAH03218SL0 (DVI-I-1)"
  Make: BNQ
  Model: ZOWIE XL LCD
  Serial: FAH03218SL0
  Physical size: 530x300 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000000 Hz (preferred)
    1920x1080 px, 144.001007 Hz (current)
    1920x1080 px, 119.982002 Hz
    1920x1080 px, 99.930000 Hz
    1280x1024 px, 119.958000 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1440x900 px, 119.851997 Hz
    1024x768 px, 119.988998 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 119.972000 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 60.317001 Hz
    640x480 px, 120.008003 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 59.939999 Hz
  Position: 0,193
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: enabled

**Comment by Michota** [comment]
you managed to fixe that @JaimeJimenezG ?
