### ISSUE TITLE
Corruption on scrolling and stair case boxes flicking etc

### ISSUE THREAD

**Issue by sjhaleprogrammer** [hyprwm/Hyprland#3647]
### Hyprland Version

v0.30.0

### Bug or Regression?

Bug

### Description

I get corruption when scrolling in the terminal with Kitty, some flickering, etc, and staircase black boxes for a split second on YouTube videos.

### How to reproduce

have a monitor plugged into the secondary Nvidia laptop GPU (hybrid mode)

**Comment by vaxerski** [comment]
nvidia issue
