### ISSUE TITLE
New floating windows are not interactive if they appear above maximized windows.

### ISSUE THREAD

**Issue by Killercat103** [hyprwm/Hyprland#365]
Steps to reproduce:
- Maximize a windowed program such as Firefox.
- Have the program open a new floating window while maximized. (For instance open a page in Firefox which downloads a file. Firefox will then open a floating window asking what it should do with the corresponding file.)
- The new floating window is visible in front of the maximized tiled window. But is not interactive unless the maximized program is no longer maximized or the floating window is moved to a sepperate workspace.

Expected outcome:
The new floating window is interactive on top of the maximized tiled window.

OS: Gentoo Linux x64 5.15.41
Hyprland version: 0.7.1beta

**Comment by vaxerski** [comment]
fixed in c2215e4efbe4e7351b8ccd12341e3c8dfe23cc39

**Comment by Killercat103** [comment]
Can confirm that this commit fixed the issue. Thank you for your help!
