### ISSUE TITLE
Toggleopaque for several window

### ISSUE THREAD

**Issue by NoahFraiture** [hyprwm/Hyprland#3655]
### Description

Hey, I searched for a while but didn't find anything to make this command on several (or all in my case) window at the same times. The only thing I found was to set a window rule with `hyprctl keyword windowrulev2 'opaque,class:(.)'` but only the new windows respect this rule and the active one. The other doesn't seems to detect the change.
Another technique I found was to source a file with this only rules, but the result is the same.

I'm trying to make a shortcut that disable animations, blur and set opacity to 1 but I can't without setting the opacity.
Thank you for reading me

**Comment by vaxerski** [comment]
why not set the `decoration:*_opacity` values? If you set the opacities directly via windowrules, why not use `opacity 1.0 override 1.0 override`?

**Comment by NoahFraiture** [comment]
It don't know why but it doesn't work either. Here's my script `#!/usr/bin/env sh
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '2p' | awk '{print $2}')
if [ $HYPRGAMEMODE = 1 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:active_opacity 1.0;\
        keyword decoration:inactive_opacity 1.0;\
        keyword decoration:rounding 0"
    exit
fi
hyprctl reload
`

**Comment by vaxerski** [comment]
hyprctl reload will clear any dynamic vars and replace them with config'd ones.

**Comment by NoahFraiture** [comment]
Yeah it execute this line only when execute this script again, every other line works (animations, blur, ...) but not the opacity. Am I doing something wrong or is it a bug ?

**Comment by tchofy** [comment]
From what I can understand, and some testing I did, your script should work as expected. Am I wrong, or what you actually want is to disable transparency for windows that have them, like your bar and terminals?

**Comment by NoahFraiture** [comment]
Yes that's what I want but it doesn't work for me :(
I have a nvidia setup that works perfectly except for that. I have a keybind for command "toggle opaque" that works well for the active window

**Comment by tchofy** [comment]
Yeah for that unfortunately you'll have to handle it on an app by app basis, as far as I know hyprland can't block an application from drawing a transparent surface, so that'd have to be a feature request.

However, I don't think the performance impact is going to be noticeable, hyprland does not repaint the parts of the screen behind a transparent surface unless something's moving behind them. You can see what parts of the screen are being repainted by using `hyprctl keyword debug:damage_blink 1` <b>(epilepsy warning)</b>, you'll see only certain parts of the screen are being repainted, unless you have `debug:damage_tracking` set to 0 for some reason (2 by default).

**Comment by NoahFraiture** [comment]
> Yeah for that unfortunately you'll have to handle it on an app by app basis, as far as I know hyprland can't block an application from drawing a transparent surface, so that'd have to be a feature request.
> 
> However, I don't think the performance impact is going to be noticeable, hyprland does not repaint the parts of the screen behind a transparent surface unless something's moving behind them. You can see what parts of the screen are being repainted by using `hyprctl keyword debug:damage_blink 1` (epilepsy warning), you'll see only certain parts of the screen are being repainted, unless you have `debug:damage_tracking` set to 0 for some reason (2 by default).

But if so, I don't understand why the command `hyprctl dispatch toggleopaque` works perfectly. 
The command `hyprctl keyword decoration:active_opacity 1.0` doesn't work for none applications, waybar, kitty or discord

**Comment by tchofy** [comment]
Not sure tbh, to me toggleopaque only changes the full opacity of a window and not just it's background if I set my opacity to < 1.0, background opacity only changes if I edit my terminal's config file.

But if it works for you, what about approaching this with with the `hyprctl setprop` function? Can't test it myself, but one of those props would probably work:

```
hyprctl clients -j | jq -r ".[].address" | xargs -I {} hyprctl setprop address:{} forceopaque 1 lock
hyprctl clients -j | jq -r ".[].address" | xargs -I {} hyprctl setprop address:{} forceopaqueoverriden 1 lock
hyprctl clients -j | jq -r ".[].address" | xargs -I {} hyprctl setprop address:{} alphaoverride 1 lock
hyprctl clients -j | jq -r ".[].address" | xargs -I {} hyprctl setprop address:{} alpha 1 lock
hyprctl clients -j | jq -r ".[].address" | xargs -I {} hyprctl setprop address:{} alphainactiveoverride 1 lock
hyprctl clients -j | jq -r ".[].address" | xargs -I {} hyprctl setprop address:{} alphainactive 1 lock
```

**Comment by NoahFraiture** [comment]
First one works but reload doesn't change a thing so I added the same line with 0 after the reload and it works great (except I removed the lock for confort)
Thank you !
