### ISSUE TITLE
Swaylock not working with blur?

### ISSUE THREAD

**Issue by ghost** [hyprwm/Hyprland#366]
# Note

Sorry if the solution to this is really obvious, I tried looking in the FAQ but my issue wasn't mentioned :(

# Steps to reproduce

- Make sure that blur is enabled
- Install `swaylock`
- Execute `swaylock -F -c 0000007F`

# Expected outcome

The whole screen is blurred

# Actual outcome

The whole screen is not blurred, only half-transparent.

# Blur Config
```ini
    blur=1
    blur_size=3 # minimum 1
    blur_passes=3 # minimum 1, more passes = more resource intensive.
    blur_ignore_opacity=1
```

# Logs
None, didn't crash.

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/wiki/Advanced-config#blurring-layersurfaces
