### ISSUE TITLE
Hypland Crash on launch

### ISSUE THREAD

**Issue by Boatster45** [hyprwm/Hyprland#3660]
### Hyprland Version

AUR hyprland-nvidia-git (0.31.0.r29.g616ff343-1)

### Bug or Regression?

Bug

### Description

Hi, I currently am running Hyprland on Arch Linux and use the display manager ly. A few days ago I was running Hyprland fine until my laptop had died and now I cannot access Hyprland. 

My laptop is a HP Victus with an i5-12450h cpu with integrated graphics and an Nvidia GTX 1650 Mobile. I am running Hypland-nvidia under hybrid mode (I was never able to confirm whether or not the gpu was being used) and suspect that that is the case for this crash. Furthermore, even before the crash began, I have never been able to suspend/close the laptop lid without Hypland or Wayland crashing.  

Listed below is the crash dump as displayed by the Crashed Processes Viewer. I will post more info if necessary.

### How to reproduce

Launch Hyprland in ly

### Crash reports, logs, images, videos

           PID: 829 (Hyprland)
           UID: 1000 (b00xter)
           GID: 1000 (b00xter)
        Signal: 6 (ABRT)
     Timestamp: Tue 2023-10-24 21:02:37 CDT (15s ago)
    Command Line: Hyprland
    Executable: /usr/bin/Hyprland
    Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (b00xter)
       Boot ID: 8e89e1afe9c94d9dbac0e63fe8be92b2
    Machine ID: c562a2276ba74478a59fc2014d4760c1
      Hostname: a4chb0x
       Storage: 
     /var/lib/systemd/coredump/core.Hyprland.1000.8e89e1afe9c94d9dbac0e63fe8be92b2.829.1698199357000000.zst (present)
      Size on Disk: 1.5M
         Message: Process 829 (Hyprland) of user 1000 dumped core.
                
                Stack trace of thread 829:
                #0  0x00007f9c51d9a83c n/a (libc.so.6 + 0x8e83c)
                #1  0x00007f9c51d4a668 raise (libc.so.6 + 0x3e668)
                #2  0x00007f9c51d324b8 abort (libc.so.6 + 0x264b8)
                #3  0x000055eb5f59877a _Z25handleUnrecoverableSignali (Hyprland + 0xc177a)
                #4  0x00007f9c51d4a710 n/a (libc.so.6 + 0x3e710)
                #5  0x00007f9c526bb664 wlr_backend_get_drm_fd (libwlroots.so.12032 + 0x4e664)
                #6  0x00007f9c526a4e32 n/a (libwlroots.so.12032 + 0x37e32)
                #7  0x00007f9c526c3f3c n/a (libwlroots.so.12032 + 0x56f3c)
                #8  0x00007f9c526be4d2 wlr_drm_backend_create (libwlroots.so.12032 + 0x514d2)
                #9  0x00007f9c526bb435 n/a (libwlroots.so.12032 + 0x4e435)
                #10 0x00007f9c526bbbae wlr_backend_autocreate (libwlroots.so.12032 + 0x4ebae)
                #11 0x000055eb5f5ae190 _ZN11CCompositor10initServerEv (Hyprland + 0xd7190)
                #12 0x000055eb5f584205 main (Hyprland + 0xad205)
                #13 0x00007f9c51d33cd0 n/a (libc.so.6 + 0x27cd0)
                #14 0x00007f9c51d33d8a __libc_start_main (libc.so.6 + 0x27d8a)
                #15 0x000055eb5f5985f5 _start (Hyprland + 0xc15f5)
                
                Stack trace of thread 843:
                #0  0x00007f9c51d954ae n/a (libc.so.6 + 0x894ae)
                #1  0x00007f9c51d97d40 pthread_cond_wait (libc.so.6 + 0x8bd40)
                #2  0x00007f9c520d9e11 __gthread_cond_wait (libstdc++.so.6 + 0xd9e11)
                #3  0x000055eb5f6936b6 n/a (Hyprland + 0x1bc6b6)
                #4  0x00007f9c520e1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
                #5  0x00007f9c51d989eb n/a (libc.so.6 + 0x8c9eb)
                #6  0x00007f9c51e1c7cc n/a (libc.so.6 + 0x1107cc)
                ELF object binary architecture: AMD x86-64

**Comment by tchofy** [comment]
Symptoms of https://github.com/hyprwm/Hyprland/issues/3582. Suspend issues could be the nvidia services not being enabled, [try these steps from the wiki](http://wiki.hyprland.org/Nvidia/#fixing-suspendwakeup-issues).

**Comment by vaxerski** [comment]
nvidia isue
