### ISSUE TITLE
Add a timestamp of the last window activation to `hyprctl clients`

### ISSUE THREAD

**Issue by UserSv4** [hyprwm/Hyprland#3661]
### Description

I have a small program that allows me to quickly switch to different windows by typing their name kinda like [this](https://github.com/kvakulo/Switcheroo) and I would really like to sort the windows by their last activation time so that if I type a part of the name and just press enter I would be taken to the most recently activated window containing what I've typed.

**Comment by vaxerski** [comment]
activation time? you mean focus?

**Comment by vaxerski** [comment]
Not the solution you asked for, but a more wayland-like approach that also allows you to do what you want to.

focusHistoryID: 0 for current, 1 previous, 2 previous before that, etc.
