### ISSUE TITLE
Wezterm cannot be opened

### ISSUE THREAD

**Issue by 0a00** [hyprwm/Hyprland#3666]
### Hyprland Version

Tag: v0.31.0-36-g6650e4ba

### Bug or Regression?

Bug

### Description

Wezterm cannot be opened

### How to reproduce

Wezterm cannot be opened

### Crash reports, logs, images, videos

Wezterm cannot be opened
![图片](https://github.com/hyprwm/Hyprland/assets/59482058/f65eb764-f1f8-4513-9d2e-a2c1db6cab4d)

**Comment by huanglei104** [comment]
能分享一你的终端模糊的配置的吗 我设置了不生效

**Comment by 0a00** [comment]
> Can you share a fuzzy configuration of your terminal? I set it not to work
主页有配置文件，

**Comment by vaxerski** [comment]
wezterm issue https://github.com/wez/wezterm/issues/4483

**Comment by ezkha** [comment]
The issue got introduced with 59f27e7, according to this [comment](https://github.com/wez/wezterm/issues/4483#issuecomment-1780880648).

It could be a Hyprland issue. It also happened to me on 92cf1c23. Running an AMD 6750 (not Nvidiarse).

**Comment by vaxerski** [comment]
yeah, that commit improves hyprland's accordance to the wayland spec. :)
