### ISSUE TITLE
Blur behind special workspace with blur disabled

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#3668]
### Hyprland Version

Hyprland, built from branch makepkg at commit b0b88a63b6d17b759a85c28cab29c5986fa6e3ff dirty (renderer: fix missed box scale). Tag: v0.31.0-39-gb0b88a63

### Bug or Regression?

Bug

### Description

I suspect https://github.com/hyprwm/Hyprland/commit/5b0dc779ed91b08a9b0bfafb97b28f927dfdda0c to cause this

### How to reproduce

Turn off blur, open a special workspace with an trasparent window

**Comment by imxyy1soope1** [comment]
enable blur, then use `windowrulev2 = noblur, class:^(.*)$` to disable blur for all the clients

**Comment by Dickby** [comment]
Thanks, but shouldn't it be disabled for all clients if blur is disabled globally?
Seems a bit backwards to disable blur and disable it for all clients per regexp

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/2c3d677f-89c3-49b4-b602-0506eb2c3d0f)
can't repro

**Comment by Dickby** [comment]
With the example config, just blur disabled, a window that has transparency from the application itself on a special workspace is blurred on my computer!?

**Comment by vaxerski** [comment]
haunted

**Comment by Dickby** [comment]
Fixed by https://github.com/hyprwm/Hyprland/commit/9d2a5fb41752c0dcc8e863d7e98b541656584dd9
