### ISSUE TITLE
`hyprctl activewindow` broken

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#367]
```
% hyprctl activewindow    
unknown request
```

happens for me and other people: https://stop.voring.me/notes/92o7gkncms

**Comment by vaxerski** [comment]
fixed in 65e75c0b4427965a0fa3386e2bd27e58f195d2d6, but FYI this issue is because hyprctl got an update and you recompiling hyprctl would've fixed it
