### ISSUE TITLE
Flicking Camera Position In Game(s)

### ISSUE THREAD

**Issue by cprin21** [hyprwm/Hyprland#3672]
### Hyprland Version

Hyprland, built from branch HEAD at commit 5b8cfdf2efc44106b61e60c642fd964823fd89f3  (props: bump ver to v0.31.0).

### Bug or Regression?

Bug

### Description

World of Warcraft, run through Proton via Steam, the camera direction will sometimes 'flick' upwards and cause my character to start running the opposite way if I hold right click (which changes camera and character direction alongside it). Apparently fixed in Sway?
Gamescope glitches the game out causing disconnects and auto walk to stop working when in a different workspace (single monitor setup), not an ideal solution. Worse experience than the occasional camera flick.

### How to reproduce

Play a game, make camera direction tied to cursor position. Occasionally will flick the position away at seemingly random.

**Comment by vaxerski** [comment]
wasn't that a general wayland issue? IIRC similiar things happened in FFXIV which would also happen on sway and KDE.

**Comment by cprin21** [comment]
Have not ever had this issue happen on KDE Plasma and reportedly fixed on Sway.

**Comment by vaxerski** [comment]
"reportedly fixed" by what commit/pr?

**Comment by cprin21** [comment]
> "reportedly fixed" by what commit/pr?

Apologies it may be just false info fed to me by a redditor (reddit moment). Misinformation spreads so easily!
I will be doing my own testing to see if SDL_VIDEODRIVER=x11 helps resolve the occasional and random camera flick. 

It is likely a similar Wayland issue causing the problem in FFXIV, but Gamescope causes more problems than it solves for me to the game when I do not have it in focus.

**Comment by Stinjul** [comment]
I have the same issue in ffxiv on hyprland, but never on sway (I've been playing ffxiv on sway for more than 1.5 years now without issues).
So I'm not sure where the notion came from that this is a general wayland issue, because I've never seen this occur in any game I played when using sway.

It also doesn't seem to be limited to games, because something similar happens randomly in chrome on https://loadout.tf/ when rotating the models (whenever the mouse gets constrained basically).

**Comment by Roger-Roger-debug** [comment]
I'm not sure if the FFXIV is the same issue.

In FF my mouse would occasionally flick when clicking a mouse button (though I feel like it's gotten better). It only happened in FF and never in other games.

I'm now seeing a similar issue in other games. It's especially noticeable in Borderlands 2 (running in gamescope) where my character will randomly look elsewhere (not on mouse click like in FF).

**Comment by vaxerski** [comment]
please check #4889

**Comment by vaxerski** [comment]
closing as stale

**Comment by Airradda** [comment]
This still occurs for me when playing World of Warcraft. I unfortunately won't be able to help get more information if you need it as I am not home and won't be till next weekend.

**Comment by a-usr** [comment]
Experiencing the same issue with all of the games i tried (using proton). When I switch workspaces while the game is keeping the mouse captured, and then switch back to the game, pressing any buttons on the mouse (even hotkeys / extra keys) causes the camera to flick into an a apparently random direction. This behaviour stops when I go into the pause menu and then back (any other menu that allows the free movement of the cursor probably has the same effect), until i switch workspaces again.

**Comment by ToxicMushroom** [comment]
I too have this issue on 42.0 in ffxiv: https://www.youtube.com/watch?v=QRSGuRKxSbk
Not in sway or i3 which I've both been using for 2 years.

**Comment by ToxicMushroom** [comment]
@vaxerski Can you reopen this ? 
My youtube video I linked above is still applicable.

Can still reproduce on version: 
````
Hyprland 0.45.0 built from branch main at commit af83c825138386d269d69b3ef755b844a2eacb22 dirty (hyprctl: add json output on hyprctl -j plugins list (8480)).
Date: Sun Nov 17 00:18:30 2024
Tag: v0.45.0-29-gaf83c825, commits: 5462
built against aquamarine 0.5.0


flags set:
debug
````

Some things I found notable in the trace log (idk what I'm doing though):
`HYPRLAND_TRACE=1 AQ_TRACE=1 Hyprland`


Mouse movement:
````
[TRACE] [AQ] libinput: Event 400
[TRACE] [AQ] atomic moveCursor
````

Mouse tp ? :
````
[LOG] [AQ] [libinput] event3  - debounce state: DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS → DEBOUNCE_EVENT_TIMEOUT_SHORT → DEBOUNCE_STATE_IS_UP_WAITING

[TRACE] listener_commitWindow (last presentation 7.343 - 136.18413 fps)
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 6, needsFrame false, isPageFlipPending false, frameEventScheduled false
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 6, needsFrame true, isPageFlipPending false, frameEventScheduled true
[ERR] BUG THIS: null fb texture while attempting to blur main fb?! (introspection off?!)
[TRACE] [AQ] drm: Committed a buffer, updating state
[TRACE] [AQ] drm: CDRMFB: buffer has drmfb attachment with fb 5f3ae5e3fd30
[TRACE] [AQ] atomic addConnector blobs: mode_id 23, active 22, crtc_id 20, link_status 5, content_type 0
[TRACE] [AQ] atomic addConnector values: CRTC 89, mode 0
[TRACE] [AQ] atomic drm request: adding id 112 prop 20 with value 89
[TRACE] [AQ] atomic drm request: adding id 89 prop 22 with value 1
[TRACE] [AQ] atomic drm request: adding id 89 prop 19 with value 104706548131716
[TRACE] [AQ] atomic drm request: adding id 89 prop 24 with value 0
[TRACE] [AQ] atomic planeProps: prop blobs: src_x 9, src_y 10, src_w 11, src_h 12, crtc_w 15, crtc_h 16, fb_id 17, crtc_id 20, crtc_x 13, crtc_y 14
[TRACE] [AQ] atomic drm request: adding id 58 prop 9 with value 0
[TRACE] [AQ] atomic drm request: adding id 58 prop 10 with value 0
[TRACE] [AQ] atomic drm request: adding id 58 prop 11 with value 125829120
[TRACE] [AQ] atomic drm request: adding id 58 prop 12 with value 70778880
[TRACE] [AQ] atomic drm request: adding id 58 prop 15 with value 1920
[TRACE] [AQ] atomic drm request: adding id 58 prop 16 with value 1080
[TRACE] [AQ] atomic drm request: adding id 58 prop 17 with value 144
[TRACE] [AQ] atomic drm request: adding id 58 prop 20 with value 89
[TRACE] [AQ] atomic drm request: adding id 58 prop 13 with value 0
[TRACE] [AQ] atomic drm request: adding id 58 prop 14 with value 0
[TRACE] [AQ] atomic drm request: adding id 58 prop 18 with value 148
[TRACE] [AQ] atomic drm request: adding id 58 prop 21 with value 0
[TRACE] [AQ] atomic planeProps: disabling plane 86
[TRACE] [AQ] atomic drm request: adding id 86 prop 17 with value 0
[TRACE] [AQ] atomic drm request: adding id 86 prop 20 with value 0
[TRACE] [AQ] atomic drm request: adding id 86 prop 13 with value 0
[TRACE] [AQ] atomic drm request: adding id 86 prop 14 with value 0
[TRACE] Aquamarine returned an explicit out fence at 134
[TRACE] Explicit: 1 presented
[LOG] cursorImage request: surface 5f3ae5e02a40
[LOG] CWLSurface 5f3ae5b52900 called init()
[TRACE] [pointer] monitor: DP-2, size: [Vector2D: x: 64, y: 64], hw buf: [Vector2D: x: 64, y: 64], scale: 1.00, monscale: 1.00, xbox: [Vector2D: x: 64, y: 64]
[TRACE] fb 239 released
[TRACE] [pointer] hw transformed hotspot for DP-2: [Vector2D: x: 32, y: 24]
[TRACE] [AQ] drm: CDRMFB: buffer has drmfb attachment with fb 5f3ae5fe9aa0
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 148
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 3, needsFrame false, isPageFlipPending true, frameEventScheduled false
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 3, needsFrame true, isPageFlipPending true, frameEventScheduled false
[TRACE] [AQ] atomic moveCursor
````

Full log if interested but looks like too much to go through. 
First half of log is probably launching the game..
37MB: https://seafile.melijn.me/f/1bde8111c8374612a535/

**Comment by vaxerski** [comment]
open a new bug report. Plus, trace logs here arent needed, they will be just needlessly spammy
