### ISSUE TITLE
custom slide animation?

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [hyprwm/Hyprland#3675]
### Description

basically i would think it would be pretty cool if for example i could choose the direction from which new windows slide in, and from what direction they slide out. so for example i could use a "bouncing" bezier curve and have windows land and bounce and make it feel like its gravity or smthn no matter where the new window is spawned. and also make all windows that r closed slide out from the bottom. if its too complex to implement nvm, but if not i think this would be AMAZING and stuff. thanks. sry for my lazy writing, im extra eepy today. thank u :)

**Comment by U-L-M-S** [comment]
you can use `animation`.
Here is a simple example:
`windowrule=animation popin,Rofi`

This way when I use my shortcut to start my Rofi, it starts with the animation of popin.

Here are other examples that you may want to try:
`windowrule = animation slide left, title:(Thunderbird)`
`windowrule = animation slide top, title:(Todoist)`

**Comment by vaxerski** [comment]
you can't specify the direction, that's what the request is about

**Comment by AnotherRandomGitHubAccount** [comment]
I tried it and it kind of works, but not really. you only have the options of top, left, right, bottom, and it doesn't work for windows going out. I think a good way to implement this would be with degrees. like you know how you can do "popin 80%"? I think if you could append a degree, like "slide 0deg" or something, like "animation = windowsIn, 1, 5, default, slide 0deg".

**Comment by unifreak** [comment]
I wonder why the slide's `top,bottom,left,right` arguments is not documented, it's very useful to know.

**Comment by AnotherRandomGitHubAccount** [comment]
another thing: i did a little tinkering and was able to get the direction working the way i wanted, yet it always comes from the sides. this means that depending on where the window is, the animation would look faster or slower. if you could have something where it like "slides down from 500 px above" that would be really cool (ofc fade-in would need to be enabled for this to work as well)

**Comment by vaxerski** [comment]
btw this is a thing and has been for an eternity I just forgot to mention it in the wiki
