### ISSUE TITLE
VSCode tooltips interfere with new_window_takes_over_fullscreen

### ISSUE THREAD

**Issue by dantefromhell** [hyprwm/Hyprland#3676]
### Hyprland Version

Hyprland, built from branch  at commit 5b8cfdf2efc44106b61e60c642fd964823fd89f3  ().

### Bug or Regression?

Bug

### Description

Setting `misc:new_window_takes_over_fullscreen = [1|2]` leads to weird behaviour when fullscreening VSCode.

Any tooltip (e.g. hovering over a filename in the Explorer sidebar either makes the tooltip fullscreen (for `misc:new_window_takes_over_fullscreen = 1`) or un-fullscreens vscode (for `misc:new_window_takes_over_fullscreen = 2`).

IMO tooltips should be excluded/ ignored by this setting.

### How to reproduce

1. Switch VSCode to fullscreen
2. Click on the Explorer view icon
3. Hover mouse over any filename and wait for tooltip to pop-up

**Comment by MightyPlaza** [comment]
is it running under native wayland?

**Comment by dantefromhell** [comment]
According to `hyprctl clients` it's using xwayland

**Comment by MightyPlaza** [comment]
don't forget xwayland is compatibility layer
vscode can be run in native wayland mode
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland

(it will probably crash due to https://github.com/microsoft/vscode/issues/184124 but you can get around it)

**Comment by vaxerski** [comment]
I think I fixed that in -git like 2 days ago

**Comment by dantefromhell** [comment]
> I think I fixed that in -git like 2 days ago

I wasnt able to pin-point the exact commit, which one is it?

Sadly testing against commit ab5497a triggers https://github.com/wez/wezterm/issues/4483 for me, creating a bigger issue than I had before.

**Comment by vaxerski** [comment]
don't use wezterm then, use a better terminal, problem solved
