### ISSUE TITLE
Full screen program black screen on fade transition when switching workspace

### ISSUE THREAD

**Issue by MiniApollo** [hyprwm/Hyprland#3680]
### Hyprland Version

v0.31.0

### Bug or Regression?

Bug

### Description

When switching workspace with the Godot editor fullscreen and fade transition the window become black for the transition After the transition is complete the window is displaying correctly
I don't tested it in git version.

### How to reproduce

Make the Godot editor fullscreen 
Switch workspace

**Comment by MightyPlaza** [comment]
try the following
`windowrulev2=nofullscreenrequest, title:^(<title_here>)$`
`windowrulev2=nomaximizerequest, title:^(<title_here>)$`

**Comment by vaxerski** [comment]
the above is unrelated

**Comment by MiniApollo** [comment]
I have found out that this is also happens with games that are full screen
