### ISSUE TITLE
Starting from zsh causes hyprctl issue: `HYPRLAND_INSTANCE_SIGNATURE not set!```, but starting from bash works fine

### ISSUE THREAD

**Issue by danielkrajnik** [hyprwm/Hyprland#3681]
### Hyprland Version

0.30.0-1

### Bug or Regression?

Bug

### Description

Starting Hyprland from zsh causes error:

```
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
```

Interactive Zsh runs inside tmux, but I assume that .zprofile should trigger first?

Starting from bash works fine (logging in and running `Hyprland`)

It's most likely error in .zshrc configuration, but if anyone saw this before and has any advice that would be really appreciated. 

### How to reproduce

1. have zsh with tmux installed
.zshrc:
```
command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] \
&& [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ] && exec tmux
```
2. add to .zprofile:
```
[[ $(tty) = /dev/tty1 ]] && exec Hyprland
```

3. login to tty1

**Comment by MightyPlaza** [comment]
see https://github.com/hyprwm/Hyprland/issues/3134

**Comment by danielkrajnik** [comment]
Thank you, but still don't understand what causes initialization started from tmux to fail. [Here](https://www.reddit.com/r/zsh/comments/14tlcnt/comment/k6y35zw/?utm_source=share&utm_medium=web2x&context=3) is the current behavior on zsh (z4h). What assumptions Hyprland makes about the underlying environment?
