### ISSUE TITLE
Wiki: Unnecessary vulkan dependencies for ubuntu

### ISSUE THREAD

**Issue by espro1** [hyprwm/Hyprland#3684]
### Hyprland Version

wiki

### Bug or Regression?

Bug

### Description

The installation guide for ubuntu (at: http://wiki.hyprland.org/Getting-Started/Installation/#installation) lists a few vulkan dependencies: 

`libvulkan-dev libvulkan-volk-dev  vulkan-validationlayers-dev libvkfft-dev libgulkan-dev`

I have consulted The Experts (tm), and they say these are in fact not necessary to compile Hyprland, and suggested I create this issue.

### How to reproduce

Look at the wiki http://wiki.hyprland.org/Getting-Started/Installation/#installation

**Comment by vaxerski** [comment]
wrong issue tracker
