### ISSUE TITLE
Rounding for layers 

### ISSUE THREAD

**Issue by the-fuckin-nobody** [hyprwm/Hyprland#3685]
### Description

As the title suggests, the ability to be able to set border radius for layers aka rounding would be great cuz enabling blur on layer based apps like rofi whilst also setting the border radius to >1 in the rofi config, resultant layer has sharp corners as theres no option to set rounding for borders

**Comment by vaxerski** [comment]
No.

> resultant layer has sharp corners as theres no option to set rounding for borders

`layerrule = ignorezero, <regex>`

**Comment by the-fuckin-nobody** [comment]
Okay it works but it does come with its quirks. the borders (if they are rounded) on a  layer surface like  waybar look kinda ugly. 
See the top left corner of this screenshot:
![Screenshot_2023-12-28-11-08-01](https://github.com/hyprwm/Hyprland/assets/97352165/24f280eb-e7e2-4150-b2f5-6a77b6b5d76c)

**Comment by vaxerski** [comment]
since then `ignorezero` has been deprecated in favor of `ignorealpha [val]`. val goes from 0-1. Play around with the value until it looks good.

**Comment by the-fuckin-nobody** [comment]
Okay it seems like changing the blur contrast, and brightness values to 1 solved the issue for me. Great work man !

**Comment by HassaineAhmed** [comment]
> No.
> 
> > resultant layer has sharp corners as theres no option to set rounding for borders
> 
> `layerrule = ignorezero, <regex>`

what is in the <regex>
