### ISSUE TITLE
Launching anyrun via exec causes it to crash after typing a single letter only after resuming from hibernation

### ISSUE THREAD

**Issue by Yohannnn** [hyprwm/Hyprland#3687]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

I am using anyrun as my app launcher and it works fine off of a fresh boot. However if I close my laptop or manually hibernate then resume anyrun will crash after I type a single letter into the entrybox. However this bug only happens when I launch anyrun via the exec dispatcher if run it manually from a terminal it works fine. I also am using lemurs as my display manger and I noticed if instead of launching hyprland with it, I just launch it manually from the TTY the bug is gone. Looking in journalctl there is a massive coredump when anyrun crashes but I can't really find anything that could point me to an issue in there but I also don't really know what I am looking at. I wasn't really sure if I should make this issue on the anyrun repo, lemurs, or here because I can't really pin down which app is not working correctly but I thought here would be best as anyrun does work when using lemurs and resuming from hibernate when I launch it manually from the terminal instead of using the exec dispatcher.

### How to reproduce

Use lemurs display manager launch Hyprland and try to launch anyrun via exec dispatcher after hibernating and resuming.

### Crash reports, logs, images, videos

[coredump.txt](https://github.com/hyprwm/Hyprland/files/13197341/coredump.txt)

**Comment by vaxerski** [comment]
this is an issue with your setup then. Please remember login managers are not officially supported.
