### ISSUE TITLE
active_opacity only works for first time opening windows

### ISSUE THREAD

**Issue by XCiMi** [hyprwm/Hyprland#369]
Issue is what the title says. I thought it was related to follow_mouse, but issue still persists even with follow_mouse set to 0.

**Steps to reproduce**
1. Open a new window. (active_opacity still works at this point)
2. Switch to another window.
3. Switch back to original window, or any other window at all. (active_opacity now doesn't work/ no transparency)

**Expected outcome**
Switching back to already opened windows would have active window transparency.

**Noted outcome**
Switching back to already opened windows makes them lose active window transparency. Freshly opened windows would still have active window transparency before being switched out of.

**Comment by vaxerski** [comment]
I hate every single one of you. fixed in 8b52858bb5e4ef3009301af07966c4f350c03063
