### ISSUE TITLE
Numbered workspaces < 1

### ISSUE THREAD

**Issue by haysidney** [hyprwm/Hyprland#3690]
### Description

Is there any particular reason why numbered workspaces have to start at 1? On i3 I got accustomed to using 0 for a terminal session. super+` would take me there. If I simply name a workspace to the string "0" then waybar wants to sort it at the end of the list of workspaces, which irks me. lol

**Comment by vaxerski** [comment]
Very old and fundamental design decisions. 

That's a problem with your waybar if anything. You can always edit its config or source to sort however you want. It's nothing hyprland mandates.

**Comment by haysidney** [comment]
I've not been able to configure waybar to sort the way I want yet, unfortunately. I was just curious if the limitation in Hyprland was arbitrary or not.

I'll take the problem up with waybar then. ^^ Thanks!
