### ISSUE TITLE
cs 2 mouse cursor issue

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#3692]
### Hyprland Version

v0.31.0-54-g86318ce0

### Bug or Regression?

Bug

### Description

mouse working in-game but the system cursor won't disappear the game screen

### How to reproduce

test cs 2

**Comment by vaxerski** [comment]
would be nice to select that "regression" instead.

**Comment by killown** [comment]
I am not sure if it's hyprland fault yet, I am still checking old versions

**Comment by killown** [comment]
not hyprland issue, after system reboot this issue disappeared somehow

**Comment by vaxerski** [comment]
it was a hyprland issue. I just fixed it in the linked commit.
