### ISSUE TITLE
Whether the built-in layout node data can be placed in public

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#3694]
### Description

I want to do some plugins related to dynamic switching layouts. Can the plug-in be allowed to obtain previous layout data so that the plug-in can make some judgments about the node information.

![image](https://github.com/hyprwm/Hyprland/assets/30348075/2542ebda-9c41-4a99-9c85-d487aed1bf01)

**Comment by vaxerski** [comment]
what for?

**Comment by DreamMaoMao** [comment]
重点词汇
24/5000
翻译
通用场景
Maybe I can inherit from the built-in layout class instead of using the built-in layout directly

**Comment by DreamMaoMao** [comment]
Maybe I can inherit from the built-in layout class instead of using the built-in layout directly

**Comment by vaxerski** [comment]
you coooulldd...

What you can also do

```cpp
#define private public
#include <hyprland/ ...>
#undef private
```

it's technically UB but we use that stuff already for some C shenanigans so it should work :P
