### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#3697]
### Description

The plugin system is nice and so much powerful.
But to get a plugin working it needs to be compiled and Hyprland needs to be compiled with it also.
Now that's what make it a bit cumbersome.
Like isn't there any possibility to make it independent of Hyprland compilation?
plug and play like system.

**Comment by vaxerski** [comment]
Hyprland doesn't need to be compiled with the plugin. You can compile hyprland and then compile your plugins whenever you want, and load them whenever you want via `hyprctl plugin load/unload`.

Nothing can change here.
