### ISSUE TITLE
Ibus not working properly on non-chromium application

### ISSUE THREAD

**Issue by xenoxanite** [hyprwm/Hyprland#3699]
### Hyprland Version

v0.31.0

### Bug or Regression?

Bug

### Description

I install ibus and openbangla-keyboard ibus plugin to write bangla. But the problem it works on just chromium, codium and some other's electron based application. It doesn't work properly in Firefox and discord and others. 
I don't know, is it only me or everyone else facing this issue. And how can i fix it ?

### How to reproduce

Try to use ibus on non-chromium application.

**Comment by vaxerski** [comment]
ibus is not supported. Please use fcitx5

**Comment by xenoxanite** [comment]
openbangla-keyboard in nixos repo has some problem with fcitx5. when i switched to openbangla-keyboard layout, fcitx5 crashed.

**Comment by vaxerski** [comment]
well, too bad. Afaik ibus doesn't implement some needed protocols. Or didn't last time I checked.

**Comment by xenoxanite** [comment]
So the only thing can do is waiting for proper openbangla support in fcitx5.

**Comment by vaxerski** [comment]
or proper wayland support with ime-v2 in ibus
