### ISSUE TITLE
Regression: Nautilus file selection has random offset

### ISSUE THREAD

**Issue by DashieTM** [hyprwm/Hyprland#3703]
### Hyprland Version

Hyprland, built from branch main at commit 5b8cfdf2efc44106b61e60c642fd964823fd89f3  (props: bump ver to v0.31.0)

### Bug or Regression?

Regression

### Description

Since some commit between 0.30.0 and 0.31.0 Nautilus has a small offset to the top left. (sorry for whatever reason I can't compile individual commits even with recursing submodules) 

The same version of Nautilus does not exhibit this behavior on either sway or gnome, i believe this to be either a hyprland specific issue, or an issue with the currently used wlroots version.
One of the reason I also post this here is that gtk4 seems to have some other weird behavior right now on hyprland(random buttons not working on first click -> will investigate more), and as shown below other file managers like thunar, pcmanfm or dolphin all work fine since none of them use gtk4.
(likely all region selection in gtk4 is broken, but I have no other reference application in my head)

Tested on: 
- 0.30.0: issue doesn't happen here
- 0.31.0: issue happens
- git: issue happens

### How to reproduce

Use hyprland 0.31.0 or later

Open nautilus, use region selection with mouse.

### Crash reports, logs, images, videos

Moving selection towards top left:
![Pasted_image_2](https://github.com/hyprwm/Hyprland/assets/72016555/fb5db347-492c-4927-accf-91e49a6f2353)
Moving selection towards bottom right:
![Pasted_image](https://github.com/hyprwm/Hyprland/assets/72016555/1e13b462-e1f0-4be3-bdc8-7ccae482742f)
For reference Thunar(gtk3)
![Pasted_image_1](https://github.com/hyprwm/Hyprland/assets/72016555/4881a6d9-ad8f-4bc5-a9b9-211ff4e5a8ef)

**Comment by vaxerski** [comment]
fb80cbe415835a7e0c64e2038d0fc56e8aba0ab4
