### ISSUE TITLE
Crash when switching back to workspace 1 multiple times

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#371]
Coredump: https://zer0b.in/tcgss_p8

**Comment by ThatOneCalculator** [comment]
no that was coredumpctl

**Comment by vaxerski** [comment]
the coredump is very random as there isnt a single thing that failed. Nothing raised.

**Comment by ThatOneCalculator** [comment]
what this thing acting crazy for ‼️

**Comment by ThatOneCalculator** [comment]
ok i got it to not be weird https://stepbro.voring.me/9XvI0FD

**Comment by ThatOneCalculator** [comment]
> WHAT
> 
> debug coredump please this is fucking weird

aaaasdkjashdk now i have to uninstall aur and do debug 😢

**Comment by ThatOneCalculator** [comment]
Also turns out that even without my tablet plugged in, going back and forth causes the same crash.

**Comment by vaxerski** [comment]
yeah well give coredump

**Comment by ThatOneCalculator** [comment]
I did baka

**Comment by vaxerski** [comment]
where is the debug coredump

**Comment by ThatOneCalculator** [comment]
Soon im not at home lol

**Comment by vaxerski** [comment]
assuming it doesnt happen anymore, inactivity, closing.

**Comment by ThatOneCalculator** [comment]
actually it still does lol

**Comment by vaxerski** [comment]
give me the f coredump in debug then

**Comment by ThatOneCalculator** [comment]
fine i will soontm

**Comment by ThatOneCalculator** [comment]
For some reason I can't get it to coredump but running from the tty I got this:

![PXL_20220725_224428786.jpg](https://user-images.githubusercontent.com/44733677/180886637-e5370c42-5c2a-4638-a793-7a8357c8395b.jpg)

**Comment by vaxerski** [comment]
fix your compoota

**Comment by ThatOneCalculator** [comment]
:(((

**Comment by ThatOneCalculator** [comment]
Ok so turns out its from that silly little wallpaper switcher thingy
