### ISSUE TITLE
Error setting value <true> for field <input:misc:disable_splash_rendering>: No such field.

### ISSUE THREAD

**Issue by Lasauce6** [hyprwm/Hyprland#3710]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

I cannot use disable_splash_rendering or disable_hyprland_logo in my hyprland config i get this error : 
Error setting value <true> for field <input:misc:disable_splash_rendering>: No such field.
I'm using hyprland 0.30.0-1 from aur on arch 6.5.9-arch2-1

### How to reproduce

misc {
disable_hyprland_logo = true
disable_splash_rendering = true
}

### Crash reports, logs, images, videos

![screenshot-20231031-140158](https://github.com/hyprwm/Hyprland/assets/61377616/979b90f7-aeb7-4fca-a02c-d1450ea7e057)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/3cf5e6e1-a872-44d3-a709-846beb4bfa55)

You have an unclosed input: category somewhere in your config.
