### ISSUE TITLE
[Wlroots] RE: new frame scheduler interface

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/Hyprland#3720]
Heads up, there's performance oriented improvements coming to Wlroots which introduces breaking changes:

The new frame scheduling interface is completed here:
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4307

Rose Hudson talks about this new implementation at 06:37:17
https://www.youtube.com/live/Gg4eSAP1uc4?si=XdDjKDWv0XJVZfPA&t=23837

Simon Ser is working on supporting this in Sway:
https://github.com/swaywm/sway/pull/7780

**Comment by vaxerski** [comment]
Doesn't feel like very breaking? Why the heads-up?

**Comment by GrabbenD** [comment]
It's taking time to get this right in Sway
Figured it could be the case here too and wanted to let you guys know before the changes reach upstream 🙂

**Comment by vaxerski** [comment]
I'll close this, I'd like to keep issues for bugs/FRs. Thanks for the heads up, but a discussion / dm on discord would probably work better.

I keep track of wlroots stuff as it gets merged anyways before bumping the dep :P
