### ISSUE TITLE
Hyprland crashes wayvnc

### ISSUE THREAD

**Issue by hollowshiroyuki** [hyprwm/Hyprland#3723]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Regression

### Description

wayvnc on Hyprland crashes when opening or refreshing a window when a client is connected.

The issue was reported to any1/wayvnc/issues/248 and it seems it should be [fixed](https://github.com/any1/wayvnc/issues/248#issuecomment-1520677342), I think by this commit : https://github.com/hyprwm/Hyprland/commit/eb570c88e65171eaf3a25d278640d80e42c3af9a

The neatvnc (lib used by wayvnc) [patch](https://github.com/any1/wayvnc/issues/248#issuecomment-1519036469) proposed at that time still works but the root of the problem may still be in Hyprland ?

### How to reproduce

- Create an headless output : `hyprctl output create headless` (not required but does not crash wayvnc instantly on my setup)
- Start `wayvnc`, it should select the headless monitor automatically
- Connect to the VNC server, I tested with [wlvncc](https://github.com/any1/wlvncc) and [MultiVNC](https://github.com/bk138/multivnc) : `wlvncc localhost`
- Move the cursor to the headless monitor (not hovering the VNC window) -> the cursor shows up in the VNC window and you can see it moving
- Try to open a window like wofi or a terminal (kitty)
- wayvnc crashes

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/35398794/6d37b14e-9bc3-4e3d-b675-3b8837241875

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13239474/hyprland.log)
[wayvnc.log](https://github.com/hyprwm/Hyprland/files/13239487/wayvnc.log)
[wlvncc.log](https://github.com/hyprwm/Hyprland/files/13239489/wlvncc.log)

**Comment by vaxerski** [comment]
can you launch wayvnc with `WAYLAND_DEBUG=1` and give the output of that

**Comment by hollowshiroyuki** [comment]
Sure 👍
[wayvnc.log](https://github.com/hyprwm/Hyprland/files/13251920/wayvnc.log)

**Comment by romanstingler** [comment]
https://www.phoronix.com/news/WayVNC-0.8-Released

**Comment by izmyname** [comment]
> https://www.phoronix.com/news/WayVNC-0.8-Released WayVNC 0.8 Adds Auto Server-Side Resizing Of Headless Outputs, Detached Mode

Fixed, then? No response from the op, either.
