### ISSUE TITLE
preferred_buffer_scale advertised is the wrong value

### ISSUE THREAD

**Issue by aakamenov** [hyprwm/Hyprland#3724]
### Hyprland Version

Hyprland, built from branch main at commit 062f749450da9d280f85d3052d7f8bc9b70db62b dirty (xdg: send unconstrain events after a popup reposition (3716)).

### Bug or Regression?

Bug

### Description

Continuing from #3635 (not OP so opening a new issue), the scale factor value is still not being reported (at least not by the [library](https://github.com/Smithay/client-toolkit)). However, looking at the debug log, `preferred_buffer_scale` is now being sent but it's the wrong value - 1 (it should be 2).

### How to reproduce

In https://github.com/Smithay/client-toolkit run `WAYLAND_DEBUG=1 cargo run --example simple_window`

### Crash reports, logs, images, videos

[wayland_debug.log](https://github.com/hyprwm/Hyprland/files/13240841/wayland_debug.log)

**Comment by vaxerski** [comment]
oops, it was floor'd instead of being ceil'd
