### ISSUE TITLE
regression: focus always goes to the window under the mouse

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#3726]
### Hyprland Version

062f749450da9d280f85d3052d7f8bc9b70db62b

### Bug or Regression?

Regression

### Description

Whenever a new window is opened it doesn't get the focus and instead the focus goes to whatever is under the mouse (without it being moved).

Regression introduced in https://github.com/hyprwm/Hyprland/commit/a4db48b46b9b92b5a04b1f34490cb38802942656.

### How to reproduce

- Open a bunch of windows
- Realize that the window under the mouse cursor always gets focused
- Same thing applies when you close windows

**Comment by andresilva** [comment]
We are now unconditionally calling `simulateMouseMovement` whenever a new window is mapped or unmapped, which explains the behavior.

**Comment by vaxerski** [comment]
right, for ffm 1 it shouldn't be called.
