### ISSUE TITLE
Rename --i-am-really-stupid option to something more neutral

### ISSUE THREAD

**Issue by perdolique** [hyprwm/Hyprland#3728]
### Description

There is an option called "--i-am-really-stupid" in help message of Hyprland, that allow launch it under root. 

![2023-11-02T23:34:09,237333758+04:00](https://github.com/hyprwm/Hyprland/assets/142721811/d8d1daf6-8e2f-438d-8d36-9bb23228bc2b)

This project now have a Code of Conduct, which say "Our standards are: Do not harass, attack, or in any other way discriminate against anyone ... Examples of breaking each rule respectively include: Harassment, bullying or inappropriate jokes about another person", so this option name now doesn't fit in the project's standard. I think it's time to become more mature and change this joke name to something more neutral.

Imagine rm option "--no-presevre-root" will be "--i-am-r*tarded-i-want-delete-my-system" or something similar. Cool, but not appropriate for software, that used by a lot of people.

**Comment by vaxerski** [comment]
last time I checked "stupid" was not considered offensive, unlike your example of "retarded"

**Comment by hansfbaier** [comment]
Haha some people genuinely lack any sense of humor.

**Comment by alpimany** [comment]
Seeing you use immature naming convention is disappointing. You need to think technically, and follow your (CoC) to keep quality in your work, this is the real fun.

**Comment by neko-san1432** [comment]
its just a joke men, it doesn't necessary to be so technical when it comes to naming stuff just like that.

**Comment by ItsOhen** [comment]
> its just a joke men, it doesn't necessary to be so technical when it comes to naming stuff just like that.

Weird necro on a closed issue. But okey.
