### ISSUE TITLE
Bindings randomly stop working

### ISSUE THREAD

**Issue by ashdevelops** [hyprwm/Hyprland#3736]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Every key binding stops working (jlike hyprland doesn't even register them. Back space is disabled. Enter key opens a new tab in browser. Typing in terminal produces garble like:  0;11u0;11u9;13u9;13u9;13u9;13u9;

### How to reproduce

Unsure

**Comment by vaxerski** [comment]
sounds like your keyboard got a modifier stuck?

**Comment by rszyma** [comment]
Possibly fixed by #4304

**Comment by izmyname** [comment]
> Possibly fixed by #4304

Should it be closed, in this case?
