### ISSUE TITLE
A way to disable window switching in fullscreen

### ISSUE THREAD

**Issue by Vintodrimmer** [hyprwm/Hyprland#3738]
### Description

I'm often working with 2+ displays and move between them using `movefocus l/r/u/d`. This doesn't work as expected if one of the screens has multiple windows with one of them being in full screen mode.

Let's say I have two monitors side by side. On the left monitor I have a terminal and an IDE open, with the latter being full-screen; On the right screen I have a browser and a PDF document in regular dwindle layout, one under another. I move from the PDF to the left screen using `movefocus l` and then, after editing something, attempt to switch back to the right screen using `movefocus r`.

Expected behaviour:
1. I move to the right screen and focus a PDF document

Actual behaviour:
1. Instead of switching to the right monitor, I switch to the other app on the left monitor, meaning that terminal is now in fullscreen.
2. AFAIK, there is now no way to switch focus to the right monitor except for the use of `movetoworkspace`, which is much less convenient.

Proposed solution:
Adding a configuration parameter that would treat full screen window as the only one on the workspace, so it's not possible to focus the others using `movefocus` unless you exit full-screen mode.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13253832/patch.txt)

try this. config opt `binds:movefocus_cycles_fullscreen` set it to 1

**Comment by Vintodrimmer** [comment]
Thanks for the quick patch!
I might need some help, however, as it doesn't apply properly with the following error:
```
==> Starting prepare()...
patching file src/Compositor.cpp
patching file src/config/ConfigManager.cpp
patching file src/managers/KeybindManager.cpp
File subprojects/wlroots is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file subprojects/wlroots.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'hyprland-git-0.31.0.r7.a0b675ec-1':
error: packages failed to build: hyprland-git-0.31.0.r7.a0b675ec-1
```
Unfortunately, it's a bit unspecific for me. Would you know a solution?

**Comment by vaxerski** [comment]
`patch -p1 < /path/to/patch`

Ignore last hunk, it's my dev wlroots submodule. Git does that.

**Comment by Vintodrimmer** [comment]
Thanks, just tried 
```
binds {
    movefocus_cycles_fullscreen = 0
}
```
it and it works perfectly!

**Comment by vaxerski** [comment]
what?

**Comment by Vintodrimmer** [comment]
Nevermind, I actually prefer the new handling. Before, having this pinentry window (even floating) forced fullscreen off and tiled my browser. Now it doesn't, which is great.
Again, thanks for the quick patch!
