### ISSUE TITLE
Chromium/Web Based apps run with no display

### ISSUE THREAD

**Issue by Stella-Zephyr** [hyprwm/Hyprland#3743]
### Hyprland Version

Hyprland, built from branch main at commit 21ba8b363e94294c3af8ac535728d5ad27762d35 dirty (fractional-scale: fix addon existence check).

### Bug or Regression?

Bug

## Chromium Web Apps do not display properly, though they run without it

Certain apps that are based on Electron or Chromium, like Spotify, fail to display their screens when run under Hyprland. They function normally despite this, resulting is programs that cannot be seen but can be interacted with.

Below is an example of the bug. This screen is supposed to be displaying Spotify but the screen is blank, though I can still use keybinds and click on where the icons are meant to be to interact with the program.

Note that this can happen with some odd events, like the LibreOffice opening splash, and will not happen with Firefox derivates like LibreWolf or Tor Browser.

### How to reproduce

1. Have a generalized blur amount in your hyprland.conf file. (Untested)
2. Attempt to open a program like Discord, Spotify or others that connect to a webpage.
3. Attempt to interact with an audio element. You should succeed, hearing audio but without a display output from the program. 

### Crash reports, logs, images, videos

![imagen](https://github.com/hyprwm/Hyprland/assets/149267509/baa1491e-aa79-472a-9086-8229ac2da4a6)

![imagen](https://github.com/hyprwm/Hyprland/assets/149267509/9c01cf76-6bbb-4bff-9de6-557d8f519844)

**Comment by Stella-Zephyr** [comment]
### Addemdum

I have realized this makes it seem like the program does not get a window in places. This is not what I meant. The window opens, but seems to be empty. I apologize for any confusion.

**Comment by grappas** [comment]
Same here.

**Comment by vaxerski** [comment]
any concrete examples? "some" doesn't help. Chromium works just fine on my end.

**Comment by thejch** [comment]
Appears to be xwayland + chromium

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/53e8d31a-5830-4d4c-a2a2-6ee6da37201e)

maybe something in the config triggers this?

**Comment by Stella-Zephyr** [comment]
Examples would be Discord, Spotify, Prepros and the LibreOffice splash. Not got much else here.

**Comment by Stella-Zephyr** [comment]
I'll try to check my setup, will check back with more

**Comment by thejch** [comment]
> maybe something in the config triggers this?

was able to reproduce with the default config

With this line, https://github.com/hyprwm/Hyprland/blob/main/src/helpers/WLSurface.cpp#L34
Some xwayland things report 0 size, causing it to return false.

**Comment by grappas** [comment]
Newly opened apps (discord_arch_electron i.e.)
![obraz](https://github.com/hyprwm/Hyprland/assets/1036957/5c0234e3-1fd8-4984-90c5-f003a07bb8b8)
