### ISSUE TITLE
Window content does not automatically get painted on program launch

### ISSUE THREAD

**Issue by REALERvolker1** [hyprwm/Hyprland#3745]
### Hyprland Version

200cccdd3bbb3e093164d6cce61eedfe527f74da

### Bug or Regression?

Regression

### Description

When I press the keybind to open programs, their windows should open and the contents should be immediately visible. However, at the latest commit, the window needs to be resized for the contents to be painted.

### How to reproduce

1. Open a window (Preferably a GTK or Electron app)
2. observe

### Crash reports, logs, images, videos

Refer to this video

https://cdn.discordapp.com/attachments/961691461554950148/1170181700609908818/Kooha-2023-11-03-20-54-31.mp4?ex=65581ba2&is=6545a6a2&hm=ea6d71f3e356479fe7fc8ca5174f36e1aa5e42ae2638ede0bcbaa1b0b7840105&

**Comment by vaxerski** [comment]
I cannot repro. What apps specifically are affected? Also, Xwayland?

**Comment by REALERvolker1** [comment]
Here is a list:
- xfce4-terminal
- gnome-font-viewer
- missioncenter
- gucharmap
- evince (Gnome Document Viewer)
- Flatseal
- alacritty
- VLC Media Player
- and others

I found that opening windows on workspaces that have other windows on them, or windows that are forced floating will not reproduce the bug. Also, certain windows do not have this issue, like for example, kitty terminal.

My configs are up to date [here](https://github.com/REALERvolker1/homescripts/tree/main/.config/hypr). I assume it has something to do with `dwindle.no_gaps_when_only`

**Comment by tchofy** [comment]
I've noticed it too but thought it was an nvidia moment, since I got a driver update earlier today. I track latest git fairly close, issue started happening in the last 24 hours. No time to bissect right now, but I can confirm it only happens when `no_gaps_when_only` is set to either 1 or 2, doesn't matter if layout is dwindle or master.

**Comment by KineticAeon** [comment]
This is also happening to me with Xwayland apps, notably: League of Legends, VSCode, Minecraft Launcher, and most Steam windows (Not the main one, but login and notification windows). An image of this affecting VSCode is put below. 
![image](https://github.com/hyprwm/Hyprland/assets/56273352/fa8e0363-3356-488d-a446-eb4c548e96ed)
This was not affected by changing `dwindle.no_gaps_when_only` or any other dwindle settings.

**Comment by thejch** [comment]
Likely related to #3743 and probably caused by the same commit because the behavior looks very similar.

**Comment by REALERvolker1** [comment]
I just updated to the latest git, and now I get this new issue. Window content is shown at startup, but everything is really small. Client-side decorations work like the window is normal-size. Browsers and electron apps do not have this issue.

https://cdn.discordapp.com/attachments/961691461554950148/1170439432487313449/Kooha-2023-11-04-14-05-28.mp4?ex=65590baa&is=654696aa&hm=bb8acd37e5f112b9b4769356c3b32372d89935ac2938589402da866825922bfb&
