### ISSUE TITLE
Crash on re-open lid / resume of laptop

### ISSUE THREAD

**Issue by G-Rowell** [hyprwm/Hyprland#3746]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0

### Bug or Regression?

Bug

### Description

Hi there, just doing my duty to log this!

I had a Hyprland crash when re-opening my laptop lid (it was previously turned on and running Hyprland).
The screen flickered and graphical bugs (patterned random colours) happened.
Then Hyprland crashed and sent me back to my TTY.

Here are some system details

<details>

`uname`

```
[growell@rowell-framework ~]$ uname -a
Linux rowell-framework 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux
```

`hyprctl version`

```
[growell@rowell-framework ~]$ hyprctl version
Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty ().
Tag: v0.30.0

flags: (if any)
```

`.config/hypr/hyprland.conf` is almost default, nothing special (but happy to provide)

</details>

### How to reproduce

I'm not sure the correct way to reliably replicate this, (sorry!)

1. laptop on and running Hyprland
2. close laptop
3. open laptop
4. crash occurs

### Crash reports, logs, images, videos

[hyprlandCrashReport744.txt](https://github.com/hyprwm/Hyprland/files/13255822/hyprlandCrashReport744.txt)

(log from /home/<username>/.hypyland/hyprlandCrashReport744.txt)

**Comment by vaxerski** [comment]
that is really old. Can you test on -git?

**Comment by G-Rowell** [comment]
@vaxerski 

Happy to, but it's hard to re-produce

I installed using `sudo pacman -S hyprland` (not `hyprland-git`)

I'm happy to close for now
