### ISSUE TITLE
Special Workspace 'shadow' bug

### ISSUE THREAD

**Issue by 404ALegend** [hyprwm/Hyprland#3749]
### Hyprland Version

4a4e13f8acedd2dc44236deed13fd47096cbe508 dirty

### Bug or Regression?

Bug

### Description

I encountered this bug where if more than 2 windows are in a special workspace, the left most windows casts it's 'shadow' onto the windows on the right. After removing all config files and themes I narrowed it down to the position values for monitors. I have dual monitors, starting from left to right one vertical and one normal. The first monitor being 0x0 works just fine, the second monitor anything that is not 0x0 causes the issue. For the images included I offset the Y value to 100 to better show what is the issue

### How to reproduce

If using a second monitor, set the second monitor position with any value other than 0x0 and save, enter a special workspace and attach 2 windows to said workspace, left side window should cast a shadow onto the right window. 

P.S. Tested with the simplest config and full config. Additionally tested with VRR set to 0 and 1. Image posted is with full config enabled

### Crash reports, logs, images, videos

![231104_04h51m59s_screenshot](https://github.com/hyprwm/Hyprland/assets/20951141/ab94e5a9-51fd-48d1-89ca-2ef9c7f28198)

**Comment by vaxerski** [comment]
1) that's an old commit. Please test on -git.
2) please do not use imgur for hosting your images. You can attach media directly on github.
