### ISSUE TITLE
Alacritty crashes if the mouse is placed where the window will open.

### ISSUE THREAD

**Issue by ke1satsu** [hyprwm/Hyprland#3753]
### Hyprland Version

Hyprland, built from branch  at commit ed3d5053b23d2b725cda507cb5fcc9e9a2f35ba9

### Bug or Regression?

Bug

### Description

I usually use wezterm, but it broke a few days ago due to a change in Hyprland that supposedly was done to make the latter more compliant with the spec. Since I know jack about that I decided to use alacritty in the meantime until wezterm could get fixed.

But I get a strange crash if I attempt to start alacritty. I've attached the crash report with RUST_BACKTRACE=1.

I saw that a new bug report was filed because of the wezterm crash, and speculations that these could be related to fractional scaling. Judging by the crash error I got that might be the case? I hope this is to any help. 

What's really weird is that I actually can start alacritty if I move my mouse over to the edge of the screen where I have gaps. As long as my cursor isn't placed where the alacritty terminal will spawn it appears to run fine o_o

I'm running Nixos unstable is that is useful to know.

### How to reproduce

Try to start alacritty via wofi or from another terminal such as kitty. If the mouse is placed where alacritty will spawn it will crash. If you move the cursor aside it appears to spawn fine.

### Crash reports, logs, images, videos

wp_fractional_scale_manager_v1@14: error 0: Fractional scale exists.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/alacritty-0.12.3-vendor.tar.gz/glutin/src/api/egl/surface.rs:246:44
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: alacritty::display::Display::new
   4: alacritty::window_context::WindowContext::new
   5: alacritty::window_context::WindowContext::initial
   6: alacritty::event::Processor::create_initial_window
   7: alacritty::event::Processor::run::{{closure}}.3854
   8: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
   9: alacritty::event::Processor::run
  10: alacritty::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: queue 0x7fce10000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@26 still attached
  zwp_primary_selection_device_manager_v1@22 still attached
  wl_data_device@25 still attached
  wl_seat@24 still attached
  wl_data_device_manager@23 still attached
  wl_registry@21 still attached
warning: queue 0x55e5bb85c100 destroyed while proxies still attached:
  xdg_wm_base@35 still attached
  wl_output@16 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by ke1satsu** [comment]
Hmm my report might be a bit misleading. It stopped working at all for a bit regardless of where I positioned my mouse, and now after moving it to other workspaces and focusing other windows for a bit I could spawn alacritty even if my mouse was over the place it would spawn. Then after doing the same little dance it started crashing again.

**Comment by ke1satsu** [comment]
Updated to ed3d5053b23d2b725cda507cb5fcc9e9a2f35ba9 and alacritty seems to start fine now, upon exit there is this error now:

warning: queue 0x7f54f8000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@26 still attached
  zwp_primary_selection_device_manager_v1@22 still attached
  wl_data_device@25 still attached
  wl_seat@24 still attached
  wl_data_device_manager@23 still attached
  wl_registry@21 still attached
warning: queue 0x55cab953f4d0 destroyed while proxies still attached:
  wl_shm_pool@45 still attached
  xdg_wm_base@35 still attached
  wl_output@16 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
warning: queue 0x55cab9550780 destroyed while proxies still attached:
  wl_callback@44 still attached

As alacritty seems perfectly usable this report can probably just be closed. I'll leave it open for a while for visibility in case the information is useful to the maintainers.

**Comment by vaxerski** [comment]
that's an alacritty thing, not an error and unrelated
