### ISSUE TITLE
Some clients fail to display

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#3754]
### Hyprland Version

Hyprland, built from branch  at commit 73e78f05ad5cafa20ac5bf177c94ac9ecca37097  ().

### Bug or Regression?

Bug

### Description

Some clients only display the border with nothing inside.

### How to reproduce

Open Hyprland, try to open a window.

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/98562002/178091d0-ad87-43fa-bb44-ccca1984d638)

**Comment by micahsoftdotexe** [comment]
I am having the exact issue with the same commit.

**Comment by tchofy** [comment]
Same behavior as https://github.com/hyprwm/Hyprland/issues/3745 and https://github.com/hyprwm/Hyprland/issues/3743, the fix that was implemented seems to only work for xwayland, bug still happens on native wayland.
Workaround for now is to set `no_gaps_when_only` to 0.

**Comment by vaxerski** [comment]
I cannot repro, with anything.

**Comment by matt1432** [comment]
It might be because of the way I launch those apps?
This is how I do it :
```
exec-once = [workspace special:spot silent] spotify
```

**Comment by micahsoftdotexe** [comment]
> It might be because of the way I launch those apps? This is how I do it :
> 
> ```
> exec-once = [workspace special:spot silent] spotify
> ```

I am having the same issue with Spotify and I don't have any special rules. At first I thought this was an electron issue with my distro because Firefox would work but there was one electron program would work. Sometimes dialog boxes for some applications fail to display as well but the buttons are still intractable (if you have memorized where they are within the window).

**Comment by tchofy** [comment]
After bisecting, issue starts happening since 9d2a5fb41752c0dcc8e863d7e98b541656584dd9 for me, any prior revision works as expected.

**Comment by matt1432** [comment]
> Workaround for now is to set `no_gaps_when_only` to 0.
This doesn't do anything for me

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13257143/patch.txt)
try this

**Comment by tchofy** [comment]
Same behavior unfortunately. And unlike op, the PR mentioned above doesn't fix it for me, I get the same behavior as https://github.com/hyprwm/Hyprland/pull/3755#issuecomment-1793489087.

**Comment by matt1432** [comment]
My issue was fixed by the PR
