### ISSUE TITLE
On very specific occasions, the cursor will remain visible after using the touchscreen.

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#3756]
### Hyprland Version

Hyprland, built from branch  at commit 55b4f84fea33adee3ec4b0a69c2bca6e7a1f5754  ()

### Bug or Regression?

Bug

### Description

Ever since this [PR](https://github.com/hyprwm/Hyprland/pull/3755), the cursor sometimes remains when using the touchscreen.

### How to reproduce

If I swipe from the edge of my screen with my finger, the cursor will be visible until I use my touchpad and then the cursor disappears if I use my finger. As far as I can tell this only happens on edge screen swipes and is only a visual bug.

I tried recording my screen but with OBS open, the bug didn't happen? Very weird stuff

**Comment by horriblename** [comment]
any chance you have `general:resize_on_border` and `general:hover_icon_on_border` on? and that the cursor icon appears as one of the border hover icons

**Comment by matt1432** [comment]
no the cursor is always the default one

**Comment by horriblename** [comment]
ok different issue then
