### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by Stella-Zephyr** [hyprwm/Hyprland#3757]
### Hyprland Version

Hyprland, built from branch main at commit 200cccdd3bbb3e093164d6cce61eedfe527f74da dirty (events: set reported size on the end of mapping). (Note: this bug refers to updating to the latest build))

### Bug or Regression?

Bug

## Latest devel update cannot be compiled with yay on Arch Linux

Upon attempting to use the yay commands to update my build, the following showed up near the end of compilation:

FAILED: src/Hyprland.p/helpers_Region.cpp.o 
c++ -Isrc/Hyprland.p -Isrc -I../src -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/udis86 -I../subprojects/udis86 -I../subprojects/udis86/libudis86 -Isubprojects/udis86/__CMake_build -I../subprojects/udis86/__CMake_build -Iprotocols -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -DHAS_EXECINFO -DUSES_SYSTEMD -std=c++23 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIE -pthread -DWLR_USE_UNSTABLE -MD -MQ src/Hyprland.p/helpers_Region.cpp.o -MF src/Hyprland.p/helpers_Region.cpp.o.d -o src/Hyprland.p/helpers_Region.cpp.o -c ../src/helpers/Region.cpp
En el fichero incluido desde ../src/helpers/Region.cpp:1:
../src/helpers/Region.hpp:19:17: error: expected ‘)’ before ‘*’ token
   19 |     CRegion(CBox* box);
      |            ~    ^
      |                 )
../src/helpers/Region.hpp:48:5: error: ‘CBox’ no nombra a un tipo
   48 |     CBox                        getExtents();
      |     ^~~~
../src/helpers/Region.cpp:24:17: error: expected constructor, destructor, or type conversion before ‘(’ token
   24 | CRegion::CRegion(CBox* box) {
      |                 ^
../src/helpers/Region.cpp:107:1: error: ‘CBox’ no nombra a un tipo
  107 | CBox CRegion::getExtents() {
      | ^~~~

I would like to know if this is my mistake or if the compilation requires attention.

### How to reproduce

1. Have yay installed via the Arch User Repository
2. Be on commit 200cccdd3bbb3e093164d6cce61eedfe527f74da of Hyprland
3. Attempt to update via yay -Syu
4. When prompted, clear the files for Hyprland (preferably all)
5. Wait during the compilation until the helpers section appears

### Crash reports, logs, images, videos

FAILED: src/Hyprland.p/helpers_Region.cpp.o 
c++ -Isrc/Hyprland.p -Isrc -I../src -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/udis86 -I../subprojects/udis86 -I../subprojects/udis86/libudis86 -Isubprojects/udis86/__CMake_build -I../subprojects/udis86/__CMake_build -Iprotocols -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -DHAS_EXECINFO -DUSES_SYSTEMD -std=c++23 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIE -pthread -DWLR_USE_UNSTABLE -MD -MQ src/Hyprland.p/helpers_Region.cpp.o -MF src/Hyprland.p/helpers_Region.cpp.o.d -o src/Hyprland.p/helpers_Region.cpp.o -c ../src/helpers/Region.cpp
En el fichero incluido desde ../src/helpers/Region.cpp:1:
../src/helpers/Region.hpp:19:17: error: expected ‘)’ before ‘*’ token
   19 |     CRegion(CBox* box);
      |            ~    ^
      |                 )
../src/helpers/Region.hpp:48:5: error: ‘CBox’ no nombra a un tipo
   48 |     CBox                        getExtents();
      |     ^~~~
../src/helpers/Region.cpp:24:17: error: expected constructor, destructor, or type conversion before ‘(’ token
   24 | CRegion::CRegion(CBox* box) {
      |                 ^
../src/helpers/Region.cpp:107:1: error: ‘CBox’ no nombra a un tipo
  107 | CBox CRegion::getExtents() {
      | ^~~~

**Comment by vaxerski** [comment]
pipelines are passing, not my problem
