### ISSUE TITLE
Window content is smaller than window size on launch

### ISSUE THREAD

**Issue by REALERvolker1** [hyprwm/Hyprland#3758]
### Hyprland Version

7a09d24065050ad5b9490a6be947229ae83cb824

### Bug or Regression?

Regression

### Description

When I open certain windows, the window content does not fit the size of the window. However, when the window is not alone on the desktop, window contents behave correctly. I believe this issue is related to whatever fixed issue #3745.

### How to reproduce

1. use dwindle layout, make sure the option `no_gaps_when_only` is set to `true`
2. Open a window
3. observe

### Crash reports, logs, images, videos

https://cdn.discordapp.com/attachments/961691461554950148/1170439432487313449/Kooha-2023-11-04-14-05-28.mp4?ex=65590baa&is=654696aa&hm=bb8acd37e5f112b9b4769356c3b32372d89935ac2938589402da866825922bfb&

**Comment by primalmotion** [comment]
Yeah same thing here. I have the issue with foot and alacritty. The window opens and the client is sized according to their config's initial size instead of being forced to use the window size

**Comment by REALERvolker1** [comment]
I just updated to commit `56dec1c6a28c59b11c00e1b727517484ec4fb5ac` and the issue is not fixed
