### ISSUE TITLE
when I try to connect with my device I got this issue ??? 

### ISSUE THREAD

**Issue by Seeom6** [hyprwm/Hyprland#3759]
### Hyprland Version

23

### Bug or Regression?

Bug

### Description

INFO | Android emulator version 32.1.15.0 (build_id 10696886) (CL:N/A) INFO | Found systemPath C:\Users\alsla\AppData\Local\Android\Sdk\system-images\android-31\google_apis_playstore\x86_64\ WARNING | Please update the emulator to one that supports the feature(s): Vulkan ERROR | Running multiple emulators with the same AVD ERROR | is an experimental feature. ERROR | Please use -read-only flag to enable this feature. INFO | Storing crashdata in: C:\Users\alsla\AppData\Local\Temp\\AndroidEmulator\emu-crash.db, detection is enabled INFO | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag. INFO | IPv4 server found: 10.2.0.1

### How to reproduce

flutter issue 

### Crash reports, logs, images, videos

plz anyone can help me ??

**Comment by vaxerski** [comment]
???
