### ISSUE TITLE
text is now blurry in my terminal when it is put in the special workspace

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#3761]
### Hyprland Version

Hyprland, built from branch main at commit 3b786419d817a76b834d5e010afbed4d0cf98804 dirty (subprojects: update tracy). Tag: v0.31.0-95-g3b786419  flags: (if any) debug

### Bug or Regression?

Regression

### Description

testing with foot or alacritty. The rendering of the font is blurry when on a special workspace. It's fine otherwise

### How to reproduce

open a term
put it in the secial workspace
see the blurry mess

**Comment by vaxerski** [comment]
cant repro :(

**Comment by primalmotion** [comment]
dang.. I'll provide more info then

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13258181/patch.txt)
check this.

Note to self: do NOT commit this, this is terrible

**Comment by vaxerski** [comment]
wait no sec let me correct that patch

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13258184/patch.txt)

this.

Still note to self: dont commit this

**Comment by primalmotion** [comment]
that fixes the issue.

side note: the blurryness was not affecting only the special workspace. it is also happening to normal workspaces, depending on the size of the client. The patch seems to fix everything

**Comment by primalmotion** [comment]
no actually scratch that.. it was working for a while and it started again :(

**Comment by h0tc0d3** [comment]
Somewhere after this commit https://github.com/hyprwm/Hyprland/commit/73e78f05ad5cafa20ac5bf177c94ac9ecca37097, yesterday blurring of fonts appeared, blurring occurs in chromium.

**Comment by h0tc0d3** [comment]
@vaxerski The patch didn't help me. This patch only affects xwayland. Chromium works through native wayland. I have fractional scaling = 1.25.

**Comment by vaxerski** [comment]
oh shit okay that is blurry yea

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/f11639c9-ed39-49c8-bda6-0d8b9c7c55dd)
rofl

**Comment by primalmotion** [comment]
it's better but not completely fixed. Some clients are still blurry sometimes

![screenshot-2023-11-05-17:07:21](https://github.com/hyprwm/Hyprland/assets/208711/3c56d651-fe01-4ec3-85b8-f01548aaf8fd)

**Comment by vaxerski** [comment]
what layout is that @primalmotion ? how to repro

**Comment by vaxerski** [comment]
these are rounding errors from the recent changes, sorry about those, but I really wanted to migrate to a cleaner solution for the damn coordinate space. It's fixed a bunch of issues elsewhere and improved code under the hood.

**Comment by primalmotion** [comment]
the layout is master, there is no scaling, 1080p. the term is foot and the font is https://b612-font.com/.  it always happens to the middle term of stack when there is 4 clients opened. I don't have my conf handy now so I'm not sure about gaps and borders.If you need them I'll send them tomorrow

**Comment by vaxerski** [comment]
should be fixed in the above

**Comment by vaxerski** [comment]
anyone can report back?

**Comment by primalmotion** [comment]
it seems to work great now, at least for the basic cases. I'll keep an eye on it tomorrow. Thanks!

**Comment by h0tc0d3** [comment]
@vaxerski I have solved problems with blurry fonts.
