### ISSUE TITLE
Unable to start Hyprland, keeps landing loop

### ISSUE THREAD

**Issue by hui3215** [hyprwm/Hyprland#3762]
### Description

Hello, I am very eager for your help because I have a problem that is difficult to solve.

At the beginning, I updated the system and found that `xwaylandvideobridge-cursor-mode-2-git` was out of date, then I uninstalled it and installed `xwaylandvideobridge-git`, but now I can't get in, the desktop can only stay on the login page, the following picture is Hyprland's boot log

![f96844c444db440355249e35fd6c0bca_750](https://github.com/prasanthrangan/hyprdots/assets/53279456/bd65eea2-3e2e-4335-b0e6-e1844e84d248)

**Comment by vaxerski** [comment]
well, remove it?

**Comment by hui3215** [comment]
> 好吧，删除它？

why？

**Comment by vaxerski** [comment]
because it's not supported on hyprland
