### ISSUE TITLE
Can't run rofi

### ISSUE THREAD

**Issue by huanmoon** [hyprwm/Hyprland#3764]
I'm trying to use rofi on hyprland, it can run on kde
but when I try to run it on hyprland(rofi -show drun), it failed to run and warned
(process:4587): Rofi-WARNING **: 12:36:04.512: Failed to set locale.

**Comment by Aqa-Ib** [comment]
Try using using the lbonn rofi fork that supports wayland.

**Comment by vaxerski** [comment]
not a hyprland issue?
