### ISSUE TITLE
Include 'floating' attribute in the `focuswindow` dispatcher

### ISSUE THREAD

**Issue by karb94** [hyprwm/Hyprland#3766]
### Description

Currently I need to use the mouse to focus on a floating window. I would like to have a shortcut to cycle through floating windows in the current workspace. Currently, the `focuswindow` dispatcher only accepts the class, title, pid and adress attributes. Would it be possible to add the 'floating' attribute so that we can cycle through our floating windows?

**Comment by vaxerski** [comment]
also allowed `tiled` in 600a128f83c9f6d6cf37d4e9de6bf9001d321bd0 for coming back
