### ISSUE TITLE
Found which commit broke the scaling that was noticed in PR#3755

### ISSUE THREAD

**Issue by TheK0tYaRa** [hyprwm/Hyprland#3767]
### Hyprland Version

v0.31.0-94-g999cb0c0

### Bug or Regression?

Bug

### Description

The scaling broke in 54e51b7acf809b4cf705ae516f78a910c70e651f

### How to reproduce

Compile 54e51b7acf809b4cf705ae516f78a910c70e651f and run [kotatogram](https://github.com/hyprwm/Hyprland/pull/3755#issuecomment-1793488915) or [foot terminal](https://github.com/hyprwm/Hyprland/pull/3755#issuecomment-1793489087).

Observe fullscreen apps affected.

**Comment by vaxerski** [comment]
and was fixed in d3e5796ee1d298b3819d04febaae58ceb9230e5b: https://github.com/hyprwm/Hyprland/issues/3758

**Comment by TheK0tYaRa** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/27967034/423a9822-046d-400d-b2fe-a0a0c6ea750f)
Was it tested on kotatogram too?
`v0.31.0-95-g3b786419` built on [3b78641](https://github.com/hyprwm/Hyprland/commit/3b786419d817a76b834d5e010afbed4d0cf98804)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/7491123b-c4fa-4a3f-856d-43ff02bb2d69)

**Comment by TheK0tYaRa** [comment]
I suppose i should be more specific. The part that scaling breaks on is the fullscreen media viewer.

**Comment by vaxerski** [comment]
yeah but I won't create an account and shit just to test this. If you tell me what's wrong within the codebase I'm happy to fix it

**Comment by TheK0tYaRa** [comment]
I've tracked down the commit and so far lack the knowledge within the code of hyprland to fix that myself. I would have made a PR if i could have fixed it by now. Alas i can only fix it by reverting said commit which i doubt is a proper fix.

**Comment by TheK0tYaRa** [comment]
Although i suppose i can check which of 6 (or 4) edits is the reason.

**Comment by vaxerski** [comment]
you can also check the values of realsize.goalv() and reportedsize in renderWindow

**Comment by TheK0tYaRa** [comment]
Reverting specifically the 
```
PWINDOW->m_vPendingReportedSize = PWINDOW->m_vRealSize.goalv();
PWINDOW->m_vReportedSize        = PWINDOW->m_vPendingReportedSize;
```
to
```
PWINDOW->m_vReportedSize = PWINDOW->m_vPendingReportedSize;
```
in `src/events/Windows.cpp` does undo the issue. For some reason.

**Comment by vaxerski** [comment]
hm, honestly it does make sense, it was a temporary band-aid I believe. But it needs a bit more testing from my side. Sec

**Comment by TheK0tYaRa** [comment]
Feel free to send me a patch to test. Can do.

**Comment by TheK0tYaRa** [comment]
Seems to work so far, nicely done.
