### ISSUE TITLE
cursor render incorrect

### ISSUE THREAD

**Issue by Jedsek** [hyprwm/Hyprland#3768]
### Hyprland Version

0.31.0

### Bug or Regression?

Bug

### Description

Open https://jedsek.xyz in `firefox`, which will change the cursor style, then switch workspace to move focus to `alacritty`(or `wezterm`).

Cursor style does not return to normal.

### How to reproduce

See video

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/63626406/b1886c2d-8c99-4974-9869-ebd60f391afd

[hx.log](https://github.com/hyprwm/Hyprland/files/13259643/hx.txt)

**Comment by vaxerski** [comment]
you are on an old commit, please test on -git.

IIRC this was fixed, and I can't repro either.

**Comment by wrenby** [comment]
I apologize for the ping; I copied the wrong issue number :sob:
