### ISSUE TITLE
After boot first launch crashes

### ISSUE THREAD

**Issue by miniks-github** [hyprwm/Hyprland#3769]
### Hyprland Version

0.30.0-1

### Bug or Regression?

Bug

### Description

Hello,

I'm currently running Arch Linux using kernel version `6.5.9.arch2-1` on my newly received Framework 13 AMD laptop. I also encountered this issue when trying to install NixOS (at the time I couldn't figure the error out, and returned back to Arch).

After boot my first Hyprland launch always freezes/crashes on startup with weird errors regarding my monitor eDP-1. I tried several `monitor=` settings, but none of them seemed to work. My second launch appears to be working without any issues.

My screen resolution is a bit weird with 2256x1504 (not sure if that causes any issues)

### How to reproduce

I removed Hyprland autostart from my config.fish to debug the issue. (fresh arch install) and after logging in I manually started Hyprland from TTY. 

First time starting it freezes up until it let's me manually exit Hyprland by pressing my own custom hotkey. (time of hyperland.log recording).

After starting again the issue seems 'resolved'.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13259933/hyprland.log)

**Comment by vaxerski** [comment]
your version is very old. Please update to -git for reporting issues.

**Comment by miniks-github** [comment]
Upgraded to -git. Problem still occurs. Same steps to reproduce. Added new hyprland.log
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13260282/hyprland.log)

**Comment by vaxerski** [comment]
this looks like an issue with your system. Does sway-git work?

**Comment by miniks-github** [comment]
Nope, seems to be a problem on my end. Thanks for the quick responses, though.

**Comment by vaxerski** [comment]
well then I'll close this, you can try debugging your graphics driver setup, but I don't think I can help much here
