### ISSUE TITLE
touchpad settings not working

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyprwm/Hyprland#377]
```
input {
  touchpad {
        disable_while_typing=1
        natural_scroll=1
        clickfinger_behavior=1
        middle_button_emulation=0
        tap-to-click=0
    }
}
```

I am using the above as my input config but none of the settings seem to work.

**Comment by ChristianChiarulli** [comment]
Just confirmed this is only happening for `hyprland-git`, seems to be fine using `hyprland-bin`

**Comment by vaxerski** [comment]
have you tried... restarting hyprland after changing those as the wiki prompts you to do?

**Comment by ChristianChiarulli** [comment]
I must have missed this: `Note: Touchpad config changes may require a Hyprland restart.` I switched to bin, rebooted and it worked, it was likely just the restart.Thanks!
