### ISSUE TITLE
Hyprland v0.31.0 crahes on NixOS, on home manager using the flake

### ISSUE THREAD

**Issue by 0LaMica** [hyprwm/Hyprland#3770]
### Hyprland Version

v0.31.0

### Bug or Regression?

Bug

### Description

Whenever I try to launch hyprland on the latest NixOS unstable build, which should be on v0.31.0 on nixpkgs, it crashes on launch. My hyprland configs are managed by home manager using the flake. I tried updating the flake inputs to see if it was a version mismatch since it's apparently still running on v0.30.0 on home manager but that didn't work either. It only works on generations that still use v0.30.0.

### How to reproduce

Launch hyprland on NixOS, from the flake on home manager.

### Crash reports, logs, images, videos

[hyprlandCrashReport49784.txt](https://github.com/hyprwm/Hyprland/files/13260196/hyprlandCrashReport49784.txt)

**Comment by vaxerski** [comment]
this is an issue with your setup / gpu driver
