### ISSUE TITLE
Changing workspacerules inside a plugin doesn't apply them outside of the plugin

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#3774]
### Hyprland Version

Hyprland, built from branch main at commit 2b07d54bc74f34a3561612bedaa44ad8ab550b8b dirty

### Bug or Regression?

Bug

### Description

Setting workspacerules from inside a plugin doesn't seem to actually apply them outside the plugin. As if the plugin is running its own instance?

For example:
```cpp
// workspaceName is a string, monitor->szName is the name of the monitor:
HyprlandAPI::invokeHyprctlCommand("keyword", "workspace " + workspaceName + ",monitor:" + monitor->szName + ",persistent:true");`
```

After calling this function, I log the output of `hyprctl workspacerules -j` like this:
```cpp
auto result = HyprlandAPI::invokeHyprctlCommand("workspacerules", "", "j");
Debug::log(LOG, "workspacerules: {}", result);
```

And it properly logs the workspace rule I set, when I load the plugin.
However, if after this I manually call `hyprctl workspacerules -j`  in my terminal, I get an empty array `[]`.

I tried logging the workspacerules before and after calling, and the first log is always an empty array, and the second log (after setting) correctly shows the workspacerules. 
Reloading the plugin will again show the first log as an empty array => it seems the rules are being reset every time? 

The code: https://github.com/zjeffer/split-monitor-workspaces/blob/main/src/main.cpp#L67
I log the workspacerules at the start and end of that function.

If I log the workspacerules after calling the mapWorkspacesToMonitors function, I still get the correct workspacerules. If I however log the workspacerules in one of the dispatcher callbacks, the workspacerules are always empty.

I also notice if I first set workspacerules in a terminal, then load the plugin, then print the workspacerules again in a terminal, the rules array will be empty again.

### How to reproduce

1. Set workspacerules by invoking the hyprctl command through a plugin
2. Load the plugin
3. Open a terminal and print the workspacerules

The workspacerules will be empty, while I expect them to contain the same rules as the Debug::log line prints when loading the plugin.

**Comment by vaxerski** [comment]
are you sure there is no config reload after?

**Comment by zjeffer** [comment]
Ah, indeed: there is a `HyprlandAPI::reloadConfig();` line **before** setting the workspacerules, but maybe it actually reloads later, maybe **after** returning out of the PLUGIN_INIT function? 

https://github.com/zjeffer/split-monitor-workspaces/blob/main/src/main.cpp#L100

Is this not how the reloadConfig method should be used? I was under the impression that the config should be reloaded after using `addConfigValue()` to add a new config option, if we want to use the value of the added option inside the plugin's constructor. 

Removing the reloadConfig call successfully sets the workspacerules outside of the plugin, but isn't a viable solution because we still want to use the newly added config value inside the PLUGIN_INIT function.

Am I not using this reloadConfig function correctly?

**Comment by vaxerski** [comment]
idk

since you have a plugin you can just manually add workspace rules tho, no?

**Comment by zjeffer** [comment]
What do you mean? I want to add workspace rules dynamically, so if I connect a new monitor, new persistent workspaces are automatically defined. But if I add the workspace rules in the PLUGIN_INIT function, the config is reloaded at some point *after* adding the workspacerules, so it deletes the workspacerules again right after adding them.

**Comment by zjeffer** [comment]
@vaxerski Would you have time to take a look at this issue again? This issue is still present.

**Comment by vaxerski** [comment]
precisely.
