### ISSUE TITLE
New information for Vaxry's toxicity: He is a Nazi

### ISSUE THREAD

**Issue by cinnabartalli** [hyprwm/Hyprland#3775]
In the wayland discord server, Vaxry has just admitted that he thinks Nazis should be included. Do with this info what you will.
![IMG_0987](https://github.com/hyprwm/Hyprland/assets/137727530/f6693a96-d8c5-4d28-8170-3bae59c7506a)
![IMG_0988](https://github.com/hyprwm/Hyprland/assets/137727530/346b01e6-d139-44f4-bad2-df0ca9ae0bd6)
![IMG_0990](https://github.com/hyprwm/Hyprland/assets/137727530/09dc1d91-c926-44d7-ba4e-e36fdc26495f)
![IMG_0989](https://github.com/hyprwm/Hyprland/assets/137727530/c05ee910-f706-4564-8f1f-99ab02961bf5)

**Comment by andresilva** [comment]
Why do you think it's appropriate to create an issue for this? An issue tracker is not your personal blog.

**Comment by vaxerski** [comment]
because talli has some sort of a personal vendetta against me

**Comment by NotAShelf** [comment]
funny

**Comment by Vagahbond** [comment]
wtf

**Comment by easton36** [comment]
These light mode screenshots burned my eyes!! Arrest this man for digital violence

**Comment by fybx** [comment]
get a life dude

**Comment by Visual-Dawg** [comment]
You did not understood what Vaxry wrote and now try to cancel him.
You are proving his point

**Comment by tabre** [comment]
So if a man is willing to look past political differences to work towards a common goal, he thereby adopts the differences in question? Setting aside the paradoxical nature of this thinking, if we apply this "logic" consistently, vaxerski is simultaneously nazi and communist.

**Comment by vaxerski** [comment]
I'll lock this thread as it's offtopic
