### ISSUE TITLE
Add an option to force application rendering when windows is out of sight

### ISSUE THREAD

**Issue by NeXySssss** [hyprwm/Hyprland#3776]
### Description

CS2: After switching to another workspace, it kicks me from the server after 30 seconds.
Overwatch2: The same issue as CS2.
Apex Legends: After switching to a workspace with the game, damage is not registered during the period when the window was out of sight (i.e., not rendered).

If you use "pipewire window capture" through OBS, the window starts rendering continuously, and such issues no longer occur.

Video(av1): https://i.nexy.one/u/i1iHIm.mp4

**Comment by qwert0p** [comment]
+1 for this, not sure about games, but for me it would be useful to force rendering of the browser

**Comment by FakeMichau** [comment]
From what I can tell, sway for example still renders those other workspace but at 1FPS, just so they are active. 
Maybe similar approach could be taken

**Comment by Veraticus** [comment]
This is still a thing and would be cool to correct if possible!

**Comment by Veraticus** [comment]
Sorry, to maybe make a more contributive comment: it'd be cool if there were a window rule that ensured the window would always render, even if it's not visible.

**Comment by Myned** [comment]
I can no longer reproduce my main issue with GW2 accumulating frames @ 4beac91cbd791657cc53d6e483eb41bf4df1ec0c, so this may be fixed.

It's worth retesting affected games with aquamarine if mitigating those issues are the only reason for an option.
