### ISSUE TITLE
Firefox stutters if there's monitor on the left side and firefox is maximized

### ISSUE THREAD

**Issue by Cloudef** [hyprwm/Hyprland#3778]
### Hyprland Version

Hyprland, built from branch  at commit 3b786419d817a76b834d5e010afbed4d0cf98804 

### Bug or Regression?

Bug

### Description

Weird issue but the exact thing happens as described in the title.
Video of the issue in action https://www.youtube.com/watch?v=YualBHt3LYI (ignore the clipping sound)
It seems this only affects firefox, but maybe other GDK/GTK apps might be affected?

### How to reproduce

Have monitor left side (does not matter if empty or not) and then firefox running maximized on the right monitor.

**Comment by vaxerski** [comment]
can you turn on `debug:overlay` and record with that?

**Comment by Cloudef** [comment]
The issue itself does not repeat with the overlay but the data might still be interesting:
https://www.youtube.com/watch?v=9wEcLru_x4s

window:
![mpv-shot0001](https://github.com/hyprwm/Hyprland/assets/480330/a348936a-873e-4741-809c-e960c86663a9)
maximized:
![mpv-shot0002](https://github.com/hyprwm/Hyprland/assets/480330/e9c5ad31-8c23-4003-8bed-5b180b2b5fc2)

**Comment by vaxerski** [comment]
> The issue itself does not repeat with the overlay but the data might still be interesting:

suggests firefox isn't reporting damage correctly, or hyprland doesn't read it correctly.

**Comment by Cloudef** [comment]
It only happens on secondary monitor arranged to left side, but not when right side. From the video it seems to also cause the secondary monitor to render at 60 FPS when firefox is maximized

**Comment by vaxerski** [comment]
if you do not have photosensitive epilepsy, try turning on `debug:damage_blink` and seeing if the firefox window blinks purple.

You can also inspect the log after doing `debug:damage_log` and seeing whether damage is applied properly.

I'll get back to you probably tomorrow, it's 3:30am and I probably should go sleep

**Comment by Armaldio** [comment]
Can confirm that it blinks purple

**Comment by pascalj** [comment]
I have the same issue (and possibly #4781), but it is not exclusive to Firefox. For example, after working a few seconds in a single/full screen Kitty window, it will not update its contents. Only very occasionally or when I move the mouse, the updated text is shown.
AFAICT, this can be "fixed" by either opening a second window, disabling `vfr` or disabling scaling on the primary (internal) monitor.

As a side note: Hyprland has a very high idle workload of ~8-11% on a relatively current Ryzen 7840U in the following scenarios:

1. Internal monitor with no scaling, Firefox not in fullscreen (does not happen with, say, Kitty or Chromium)
2. Internal monitor with 1.33 scaling, any window not in fullscreen
3. Internal monitor with 1.33 scaling and vfr disabled.

There's no stuttering/freezing in all three cases. Please let me know if I can provide more data.

<details>
<summary>hyprctl systeminfo</summary>

```
Hyprland, built from branch  at commit v0.35.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: ruth
Release: 6.7.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jan 20 10:53:02 UTC 2024


GPU information: 
c1:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c4) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240121.612f972"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"
plugins:
```

</details>

<details>
<summary>hyprctl monitors</summary>

```
Monitor eDP-1 (ID 0):
	2256x1504@59.99900 at 0x0
	description: BOE 0x0BCA (eDP-1)
	make: BOE
	model: 0x0BCA
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 37 0 0
	scale: 1.33
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-10 (ID 1):
	2560x1440@59.95100 at 1691x0
	description: Lenovo Group Limited LEN L27q-30 U162N9ZK (DP-10)
	make: Lenovo Group Limited
	model: LEN L27q-30
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 37 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```
</details>


<details>
<summary>perf report --stdio --sort=dso -g none</summary>

```
# Samples: 4K of event 'cycles:Pu'
# Event count (approx.): 1507136223
#
# Overhead  Shared Object              
# ........  ...........................
#
    45.44%  crocus_dri.so              
    15.12%  libc.so.6                  
    13.68%  .Hyprland-wrapped          
     9.22%  libwlroots.so.13           
     2.71%  libwayland-server.so.0.22.0
     2.02%  libpixman-1.so.0.43.2      
     1.80%  libdrm.so.2.4.0            
     1.71%  libglapi.so.0.0.0          
     1.49%  libstdc++.so.6.0.32        
     1.34%  libGLdispatch.so.0.0.0     
     1.15%  libGL.so.1.7.0             
     1.03%  libEGL_mesa.so.0.0.0       
     0.95%  [unknown]                  
     0.90%  libEGL.so.1.1.0            
     0.63%  [vdso]                     
     0.42%  libm.so.6                  
     0.23%  libdrm_amdgpu.so.1.0.0     
     0.15%  libinput.so.10.13.0        
```
</details>

**Comment by vaxerski** [comment]
can you test with #5748 merged?

**Comment by de-vri-es** [comment]
I had the same issue on my laptop with Firefox and Thunderbird, and I can confirm that for me, it is now fixed! \o/
