### ISSUE TITLE
Master Stack Layout (like DWM)

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyprwm/Hyprland#378]
I'm not sure if there is a way to do this with the dwindle layout that I'm overlooking.

Basically just a layout where all new windows will open to the left and gain focus and old windows will be stacked to the right.

**Comment by vaxerski** [comment]
yeah I have been planning that for a long time. Now with the recent internal layout changes i'll prolly add it soon.

**Comment by vaxerski** [comment]
5c836e6460ae5e8c290cfff61ec0d2d0e99dfa15

will add more configuraibility in the future, but the basic layout is done.

Wiki: https://github.com/hyprwm/Hyprland/wiki/Master-Layout

Use the layout with `general:layout = master`
