### ISSUE TITLE
what(): XDG_RUNTIME is not set!

### ISSUE THREAD

**Issue by Storm99999** [hyprwm/Hyprland#3783]
### Hyprland Version

.

### Bug or Regression?

Bug

### Description

[libseat] [libseat/backend/seatd.c:66] could not connect to socket /run/seatd.sock: Permission denied
[libseat] [libseat/.c:76] backend 'seatd' failed to open seat, skipping
when running Hyprland
-------------------------------------------------------------------
when running sudo Hyprland
terminate called after throwing an instance of 'std::runtime_error
what(): XDG_RUNTIME_DIR is not set!
aborted

### How to reproduce

Installed using the archinstall script and then copied the git and after did makepkg -si

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/87811650/e7cea0e7-a2d2-41e8-ad4a-9859aec69ebf)

**Comment by TeleportAura** [comment]
Is there a specific reason as to why you're running Hyprland as superuser? Have you checked whether XDG_RUNTIME_DIR is set in your superuser environment? (When entering it with sudo)

**Comment by vaxerski** [comment]
don't sudo

**Comment by Storm99999** [comment]
> don't sudo

I didn't.

**Comment by vaxerski** [comment]
> when running sudo Hyprland

At any rate, this means that you're not inside of a user that is meant to run anything. This is an issue on your end.

I recommend googling for xdg_runtime_dir not set, as it's not a hyprland issue.
