### ISSUE TITLE
Error when calling zwlr_layer_surface_v1::get_popup

### ISSUE THREAD

**Issue by aakamenov** [hyprwm/Hyprland#3785]
### Hyprland Version

Hyprland, built from branch main at commit ecf98069f655a4e54943ec70d638ddcf429211d1

### Bug or Regression?

Bug

### Description

Calling [zwlr_layer_surface_v1::get_popup](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:get_popup) with an xdg popup object that was created by calling [xdg_surface::get_popup](https://wayland.app/protocols/xdg-shell#xdg_surface:request:get_popup) with the "parent" argument set as NULL yields the following error message: `Request zwlr_layer_surface_v1@8.get_popup expects an argument of interface xdg_popup but zxdg_output_manager_v1 was provided instead.` Or at least Smithay (the library I'm using) [says so](https://github.com/Smithay/wayland-rs/blob/master/wayland-backend/src/rs/client_impl/mod.rs#L445). As far as I can see WAYLAND_DEBUG=1 log (attached here) doesn't show anything suspicious and neither does the Hyprland log. Is it possible that Hyprland creates/assigns the wrong object somehow? Otherwise, it may be a library issue...

### How to reproduce

Smithay provides an abstraction for creating popups: https://github.com/Smithay/client-toolkit/blob/master/src/shell/xdg/popup.rs#L76 which is what I'm using in my code.

### Crash reports, logs, images, videos

[wayland_debug.log](https://github.com/hyprwm/Hyprland/files/13270946/wayland_debug.log)

**Comment by vaxerski** [comment]
Can you test sway-git? I don't think it's me handling this.

**Comment by aakamenov** [comment]
True, also happens on sway-git. So this is handled in wlroots then?

**Comment by vaxerski** [comment]
yeh

**Comment by aakamenov** [comment]
The bug was in my own code... was mixing Wayland objects created by different connections which apparently isn't how this works.
