### ISSUE TITLE
Blur is white

### ISSUE THREAD

**Issue by OnlyCS** [hyprwm/Hyprland#3787]
### Hyprland Version

Hyprland, built from branch main at commit 29e0a7112ef5c412e4af640b9d80f80b81a26c94

### Bug or Regression?

Bug

### Description

The blur is white. The top half of my terminal window has a white window border type thing? idk watch the video.

[recording.zip](https://github.com/hyprwm/Hyprland/files/13273171/e.zip)

### How to reproduce

Enable blur and open a window

### Crash reports, logs, images, videos

[logs_tmp_hypr_latest.zip](https://github.com/hyprwm/Hyprland/files/13273184/logs_tmp_hypr_latest.zip)

from /tmp/hypr.

**Comment by vaxerski** [comment]
is this a regression? if anything this looks like your gpu driver giving up.

**Comment by OnlyCS** [comment]
unsure - i know that 
- this didn't use to happen
- i have forced everything on linux to use my integrated gpu rather than nvidia. games, etc are working fine. i'd be very surprised if it was a driver issue.

i'm going to try to build HEAD~1 from source or something soon.

**Comment by vaxerski** [comment]
most likely #3650 if a regression, can you send a log? You attached an empty zip.

**Comment by OnlyCS** [comment]
i dont think its #3650. i built a1b7a5a53d66d6289f1a3036d1aa4daa965c363c with the same issue.
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13283246/hyprland.log)

**Comment by vaxerski** [comment]
if this started happening without you updating, then is this an issue with hyprland or did you just goof something up?

**Comment by davisbwlwv** [comment]
I have the same problem, however the white part is 3/4 of the screen and not just 1/4.

Other strange things to note:
 - It is only effecting floating windows
 - It effects all windows of my terminal (even tiled ones) if I run my terminal in my exec-once

**Comment by OnlyCS** [comment]
I also have white corner pieces on other windows (i.e. chrome)

![image](https://github.com/hyprwm/Hyprland/assets/61358474/65a9842f-22a6-4809-b8d6-35e4c1605f12)

**Comment by vaxerski** [comment]
is this perhaps fixed with 1d9bfa60a19975274afb5fd9a3492f8cb6742c2e

**Comment by davisbwlwv** [comment]
I am using legacy renderer and even though it works in tiled windows, the blur doesn't show either.

**Comment by OnlyCS** [comment]
I will use 1d9bfa60a19975274afb5fd9a3492f8cb6742c2e and report back if it works, but I am currently in the process of moving to a different distro. recent updates caused a plethora of things (sound, cam, kb light indicators, bt, network displays, battery %age reporting, +more) to stop working, and I don't want to fix it all. Just a heads-up, I may not be able to reproduce this bug on the next install.

**Comment by OnlyCS** [comment]
yep, it was fixed with 1d9bfa6, thanks!
