### ISSUE TITLE
Hyprland, last focused window freezes after forced redraw (from closing other window)

### ISSUE THREAD

**Issue by Lemanrp** [hyprwm/Hyprland#3793]
### Bug or Regression?

Bug

### Description

weird to explain so I'll give an example. If I have 3 windows (one google-chrome, one alacrity, one firefox) and I'm using google-chrome. If I delete another window, lets assume it's alacritty, and this forces google-chrome to get redrawn as a result then google-chrome becomes frozen to keyboard and mouse inputs (does not respond) however the other redrawn window (in this case firefox) is perfectly fine.
### Behavior observed
A redrawn window becomes frozen to mouse clicks and keyboard input

### Expected 
The window, when clicked after being redrawn, should change the focus to the new window and also respond appropriately to what was clicked.

### How to reproduce

I found I can reproduce this when I have a minimum of 2 windows and I delete the other window. Specifically I've tested this using google-chrome and alacritty and depending on the program not all programs fail to stay responsive (for example firefox doesn't have this issue)

### Here are relevant versions of programs to recreate:
Nixos (unstable branch) version 23.11 (Tapir)
google-chrome-stable (nixos-unstable branch) is version 118.0.5993.70
Hyprland version is v0.31.0_1699383659 ( listed as "instance signature" when Hyprland is launched in alacritty).
alacritty version 0.12.3

I am aware of no error logs and this error does not trigger one to be produced.

### Crash reports, logs, images, videos

~/.hyprland/ contains no logs and I am unaware of other logs but can look and update this as needed if anyone wants me to check a log.

### update
encase it's relevant, when I say 'delete' or 'deleting a window' I mean I am using a keybinding that uses 'killactive'. This is the keybinding
bind = $super, escape, killactive,

**Comment by vaxerski** [comment]
your hyprland version is very old. Please test on a recent one.

Also @fufexan for nix

**Comment by Lemanrp** [comment]
@vaxerski 
That's very odd, I've been actually trying to learn nix overlays to tinker with dwl and was sure in that process I had updated my channels. Sorry about that but issue resolved.

On the off chance someone finds this and doesn't know how to update their system here is a line to update the channel, rebuild system.

`nix-channel --update && sudo nixos-rebuild switch --upgrade`

also if you want to delete old generations

`nix-collect-garbage --delete-old`
