### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by Storm99999** [hyprwm/Hyprland#3794]
### Hyprland Version

.

### Bug or Regression?

Bug

### Description

Finally got Hyprland to start, on an Arch **VM**, however when logging in, the screen turns black, it waits 2 seconds and puts me back on the login page even though the password is 100% correct.

### How to reproduce

Installed Arch on VirtualBox, with archinstall

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/87811650/68f52422-52ad-4336-8cfc-268b5d45db45)
![image](https://github.com/hyprwm/Hyprland/assets/87811650/30d9d619-dada-497f-97b5-cd85635c1d85)

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm
