### ISSUE TITLE
Screenshot/screenshare/screencast stopped working on scaled monitors

### ISSUE THREAD

**Issue by levnikmyskin** [hyprwm/Hyprland#3795]
### Hyprland Version

751d2851cc270c3322ffe2eb83c156e4298a0c0e

### Bug or Regression?

Regression

### Description

Looks like since commit `7a09d24065050ad5b9490a6be947229ae83cb824`, or PR #3755 , capturing the screen is broken if the monitor is scaled (it's working correctly on previous commit `73e78f05ad5cafa20ac5bf177c94ac9ecca37097`).  
`grim` fails with: 
```
[destroyed object]: error 1: Invalid stride (7679)
failed to screenshoot all outputs
```
`chromium` fails (when sharing the screen e.g. on meet), with:
```
[25102:25505:1107/234319.724942:ERROR:shared_screencast_stream.cc(241)] PipeWire stream state error: error alloc buffers: Invalid argument
[25102:25505:1107/234319.724976:ERROR:shared_screencast_stream.cc(204)] PipeWire remote error: error alloc buffers: Invalid argument
```

The monitor (my laptop's display) is scaled at 1.2. If I scale it back to 1.0, then everything works well.

### How to reproduce

- Set the scale of a monitor > 1 (mine is on 1.2);
- launch `grim`;
- no screenshot :(

**Comment by vaxerski** [comment]
great. I make a change, ask for yall to test, yall fucking dont, and then right as I make a release after a month you find huge issues.

And I get a bad name for it.

**Comment by vaxerski** [comment]
can't repro. Can I get a hyprland log?

**Comment by thejch** [comment]
> can't repro. Can I get a hyprland log?

Did you test with exactly 1.2? some values like 1.25, 1.5, 1.75 etc seem to work fine

**Comment by vaxerski** [comment]
rounding errors I am guessing from fractional pixels. Can I, again, get a log?

**Comment by q234rty** [comment]
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13291351/hyprland.log)
This is from a 2560x1440 monitor with 1.75 scaling.

**Comment by MathisP75** [comment]
Are you on Nvidia? I was able to reproduce.

**Comment by jmc-figueira** [comment]
I can reproduce this issue on NixOS unstable, Hyprland 0.32.0, with a resolution of 3840x2160 and a scale of 1.6.

Notably, this happens not only when using `grimshot` (in which the error is identical to the original submitter's) but also when attempting to start `swaylock-effects`, where it hangs with the message `[destroyed object]: error 1: Invalid stride (15353)`. Leaving it running without forcefully closing it with `Ctrl + C` will result in memory usage eventually spiking to 100% until the OOM killer kicks in.

`hyprland.log` doesn't seem to register any error related to this issue:

```
[LOG] CWLSurface 15c3158 called init()
[LOG] Callback 15c3198 -> 15c3190, CWLSurface removed.
[LOG] CWLSurface 15c3158 called destroy()
[LOG] Registered signal for owner 15c3158: 1e127a0 -> 15c3170 (owner: CWLSurface)
[LOG] CWLSurface 15c3158 called init()
[LOG] Searching for matching rules for Alacritty (title: swaylock -f -F -e --clock --indicator --fade-in 3 --effect-blur 80x4 --grace)
[LOG] Window 1e83230 set title to swaylock -f -F -e --clock --indicator --fade-in 3 --effect-blur 80x4 --grace
[LOG] ScreencopyProtocolManager bound successfully!
[LOG] Searching for matching rules for Alacritty (title: jmc-figueira@iMac-NixOS-Joao:~)
[LOG] Window 1e83230 set title to jmc-figueira@iMac-NixOS-Joao:~
[LOG] Callback 15c3198 -> 15c3190, CWLSurface removed.
[LOG] CWLSurface 15c3158 called destroy()
[LOG] Registered signal for owner 15c3158: 1e127a0 -> 15c3170 (owner: CWLSurface)
[LOG] CWLSurface 15c3158 called init()
[LOG] Callback 15c3198 -> 15c3190, CWLSurface removed.
[LOG] CWLSurface 15c3158 called destroy()
[LOG] Registered signal for owner 15c3158: 1e127a0 -> 15c3170 (owner: CWLSurface)
[LOG] CWLSurface 15c3158 called init()
[LOG] Searching for matching rules for Alacritty (title: tail -20 /tmp/hypr/_1699408803/hyprland.log | wl-copy)
[LOG] Window 1e83230 set title to tail -20 /tmp/hypr/_1699408803/hyprland.log | wl-copy
```

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13294917/patch.txt)

how about this

**Comment by imxyy1soope1** [comment]
![20231108_20h31m46s_grim](https://github.com/hyprwm/Hyprland/assets/103114856/9679374b-2361-46c4-ab98-c3c3e717c0a8)
screenshot is fixed, but more bugs occur

**Comment by vaxerski** [comment]
great, but that bug is unrelated to this issue + no steps to repro = invalid
