### ISSUE TITLE
Problem with display at 5120x1440 resolution

### ISSUE THREAD

**Issue by KlapenHz** [hyprwm/Hyprland#3796]
### Hyprland Version

Hyprland, built from branch main at commit 751d2851cc270c3322ffe2eb83c156e4298a0c0e dirty (props: bump ver to 0.32.0). Tag: v0.32.0

### Bug or Regression?

Bug

### Description

I tested it also on v.0.30.0 from pacman repo and behavior is the same
Maximum working resolution is 3840x1080. At 5120x1440 I have problems with display and functional (screen)
![swappy-20231108_005304](https://github.com/hyprwm/Hyprland/assets/110558378/7ba1797e-3bbc-4c7f-a772-4af15d01cb8c)
Hyprland is installed on Arch:
[neofetch.txt](https://github.com/hyprwm/Hyprland/files/13290418/neofetch.txt)
My graphic drivers:
[lspci.txt](https://github.com/hyprwm/Hyprland/files/13290376/lspci.txt)
Output from wlr-randr:
[wlr-ranr.txt](https://github.com/hyprwm/Hyprland/files/13290387/wlr-ranr.txt)
Output from xrandr:
[xrandr.txt](https://github.com/hyprwm/Hyprland/files/13290391/xrandr.txt)

### How to reproduce

Plug ultrawide monitor.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13290463/hyprland.log)

**Comment by vaxerski** [comment]
does sway-git work?

**Comment by KlapenHz** [comment]
Probably also doesn't.

**Comment by vaxerski** [comment]
"probably". Does it work or no? If you don't want to test, I'll say it doesn't and thus is not a hyprland issue.

**Comment by KlapenHz** [comment]
I reported a bug on Hyperland's issue. I didn't do it on sway's issue, where nothing has been released since Feb. As a user, I don't need to know that errors on Sway are also errors on Hyperland. You don't write about it anywhere, so you might not be rude when someone asks about important functionality with the aim of improving the quality of the product you are creating.

**Comment by vaxerski** [comment]
the thing is that this bug is most likely originating from the shared library we're using, being wlroots. If the bug is present on sway it would confirm that.

**Comment by KlapenHz** [comment]
Ok, I understand, I wasn't aware that you asked me for a test on Sway ;) It wasn't obvious to me. And I didn't know before that in this case the problem was in the shared library. This was my first issue created here. I will know it for the future.
On sway also problem exists, but behavior is different. My monitor turns off, on hyperland is working, but the resolution is scaling down and looks like on picture from attachment.
I created a ticket on sway couple months ago, but as I mentioned, I didn't know about shared library causing that.
https://github.com/swaywm/sway/issues/7721

**Comment by vaxerski** [comment]
my guess is a problem with the driver/wlroots. Can't see how this could be an issue with hyprland.

**Comment by KlapenHz** [comment]
`WLR_DRM_NO_MODIFIERS=1` as environment variable resolves my issue.

**Comment by pearagit** [comment]
> I reported a bug on Hyperland's issue. I didn't do it on sway's issue, where nothing has been released since Feb. As a user, I don't need to know that errors on Sway are also errors on Hyperland. You don't write about it anywhere, so you might not be rude when someone asks about important functionality with the aim of improving the quality of the product you are creating.

it's free and open source software so you might not want to be an entitled prick

I'd be ashamed to post a comment like yours without making a substantial donation to the maintainers
