### ISSUE TITLE
`center` window rule inconsistency

### ISSUE THREAD

**Issue by TheDenast** [hyprwm/Hyprland#3797]
### Hyprland Version

Hyprland, built from branch main at commit 386708563c3d9d85ffd60b4eeb6c767d29f948db dirty (workspacerules: search for special properly). Tag: v0.31.0-12-g38670856

### Bug or Regression?

Bug

### Description

Hi, I'm using the following bind to spawn a floating terminal at the center of the screen: `bind = $shiftMod, RETURN, exec, [float; center; size 1000 600] kitty`. 

- First time I use the bind, the terminal spawns not centered, but somewhere at the top left (in a not consistent position). 
- If I close it and immediately use the bind again, the terminal spawns perfectly centered and it stays like that for the rest of the session

Terminal position on first bind call:
![image_2023-11-07_20-46-47](https://github.com/hyprwm/Hyprland/assets/99830990/b711b575-9d1f-4686-b616-58ef39579a40)

Terminal position on subsequent calls:
![image_2023-11-07_20-47-03](https://github.com/hyprwm/Hyprland/assets/99830990/de14c3bb-9d07-4fde-a265-71beff9b3050)

I usually have a dual-monitor setup:
```
monitor=HDMI-A-1,2560x1440@120,0x0,1
monitor=eDP-1,1920x1080@120,2560x0,1
```
But to check it is not related, changed it to this:
```
monitor=HDMI-A-1,2560x1440@120,0x0,1
monitor=eDP-1,disable
```
Issue stays on one monitor as well.
Important note: it is a laptop where `eDP-1` is internal screen, `HDMI-A-1` is external monitor.
I've also seen similar bug appearing with apps like Rofi.

### How to reproduce

1) Put the following like in the config: `bind = $shiftMod, RETURN, exec, [float; center; size 1000 600] kitty`
2) Right after startup, trigger the bind
3) Observe window position
4) Close said window
5) Trigger the bind again
6) Observe window position

**Comment by TheDenast** [comment]
Additional note: just tried executing the bind while on laptop monitor, window still spawns in the wrong position. After several attempts is spawned in the center, and later was able to spawn centered on both monitors

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/pull/2935 fixed this for window rules but no for exec rules
don't have the time to look into fixing it currently, but simply set the `size` before the `center` for it to work properly
the reason that only happens the 1st time is kitty stores your last size, and the next time it opens, it already has that size when centered

**Comment by TheDenast** [comment]
Please excuse me for neglecting this issue, yes, setting `size` before `center` fixes the problem
