### ISSUE TITLE
Version 0.32.0 seg faults on exit

### ISSUE THREAD

**Issue by denisstrizhkin** [hyprwm/Hyprland#3798]
### Hyprland Version

Hyprland, built from branch HEAD at commit 751d2851cc270c3322ffe2eb83c156e4298a0c0e dirty (props: bump ver to 0.32.0).

### Bug or Regression?

Bug

### Description

When I press META+M (close Hyprland) it crashes

### How to reproduce

Compiled latest version from git it started to crash on exit.

### Crash reports, logs, images, videos

[hyprlandCrashReport111057.txt](https://github.com/hyprwm/Hyprland/files/13291438/hyprlandCrashReport111057.txt)
[hyprland.conf](https://github.com/hyprwm/Hyprland/files/13291445/hyprland.txt)

**Comment by romanstingler** [comment]
is this still happening for you ?
