### ISSUE TITLE
cyclenext not working in fullscreen

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyprwm/Hyprland#380]
```
bind=SUPER,j,cyclenext
bind=SUPER,k,cyclenext,prev
```
^^ these are the binds I'm using

**Comment by vaxerski** [comment]
what doesn't work, exactly?

**Comment by ChristianChiarulli** [comment]
https://user-images.githubusercontent.com/29136904/179363852-01141893-84f5-4937-a027-fb3017f4ea15.mp4

I would expect `cyclenext` to cycle between both windows in fullscreen. Or for that keybind to potentially do nothing. Right now it focuses the other window but doesn't increase it's "z index".

Maybe I'm expecting the behavior of the monocle layout.

**Comment by vaxerski** [comment]
Uhm yeah, it should probably do nothing.

**Comment by vaxerski** [comment]
fixed in edcecae7a074f76d6e0a9c7c29e796621c5b9e52
