### ISSUE TITLE
Question. How to use function keys from f13 to f24?

### ISSUE THREAD

**Issue by Aukstkalnis** [hyprwm/Hyprland#3801]
Hello.

I am using qr code scanner that prints scanned code by adding f23 at the beginning and f24 at the end of scanned code. I have a program that scans keyboard input and if it gets f23 then all message will be read until f24 key is received. This is how it works and I can not change this behavior. This functionality works on i3 but not on hyprland. Any ideas hot to enable f13-f24 keys?

**Comment by vaxerski** [comment]
those keys aren't disabled in any way shape or form. Make sure whatever app listens for the keys is in focus. the Wayland security model does not allow for an arbitrary app to "scan keyboard input"

**Comment by aphelei** [comment]
```
input {
    kb_options = fkeys:basic_13-24
}
```
