### ISSUE TITLE
Window too small for code completion

### ISSUE THREAD

**Issue by elliot-zen** [hyprwm/Hyprland#3802]
### Hyprland Version

Tag: v0.31.0-105-g29e0a711

### Bug or Regression?

Bug

### Description

The window is so small that I can't see the candidates.
I used the default configuration 

### How to reproduce

Use jetbrans ide

### Crash reports, logs, images, videos

[LOG] Creating a surfaceTree Root! [Window 55570d51e180: title: "win33"]
[LOG] Map request dispatched, monitor HDMI-A-1, window pos: [1099.00000, 438.00000], window size: [822.00000, 260.00000]
[LOG] Searching for matching rules for jetbrains-idea (title: foo-web – DemoController.java [foo-web.main])
[LOG] Window 55570d0d9360 set title to foo-web – DemoController.java [foo-web.main]
[LOG] Unmanaged window [Window 55570d51e180: title: "win33"] requests geometry update to [1099, 438] 822 90
[LOG] Searching for matching rules for jetbrains-idea (title: foo-web – DemoController.java [foo-web.main])
[LOG] Window 55570d0d9360 set title to foo-web – DemoController.java [foo-web.main]
[LOG] Searching for matching rules for jetbrains-idea (title: foo-web – DemoController.java [foo-web.main])
[LOG] Window 55570d0d9360 set title to foo-web – DemoController.java [foo-web.main]

https://github.com/hyprwm/Hyprland/assets/112766964/e3a54137-a862-47a1-bec0-57a46047dcf4

**Comment by elliot-zen** [comment]
https://github.com/hyprwm/Hyprland/assets/112766964/b996a255-affe-4503-a98d-d5455a017e2c

**Comment by vaxerski** [comment]
it's one of these 
https://github.com/hyprwm/Hyprland/issues?page=1&q=is%3Aissue+jetbrains

I forgot which one

At any rate, it's jetfarts being jetfarts

**Comment by elliot-zen** [comment]
I've looked at all the issues involved, but haven't found anything like what I'm looking for.
