### ISSUE TITLE
force_default_ wallpaper and new_window_takes_over_fullscreen return "no such field" error

### ISSUE THREAD

**Issue by CDTay** [hyprwm/Hyprland#3803]
### Hyprland Version

Hyprland, built from branch at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty ().

### Bug or Regression?

Bug

### Description

When I set `force_default_wallpaper` to 0 and `new_window_takes_over_fullscreen` to 2 in `hyprland.conf` I get the red error "Error setting value <0> for field <misc:force_default_wallpaper>: No such field." (And of course a similar message for the new window takeover command).

However `disable_splash_rendering = true` works in the same `misc {  }` section.

Have these variables been removed and left behind on the wiki?

### How to reproduce

Set those same settings in misc inside `hyprland.conf`

**Comment by vaxerski** [comment]
maybe, could it be, that it has something to do with the fact that you're using options from 0.32 but are on 0.30???? Noo...

**Comment by Aworldc** [comment]
hmm pacman thinks 0.30 is the latest. i guess i need to use the aur version.

**Comment by MightyPlaza** [comment]
> hmm pacman thinks 0.30 is the latest. i guess i need to use the aur version.

> nup yay doesnt like the aur version, guess i have to copy releases manually

from both comments I'm gonna guess your pacman mirror is dead and your system is extremely out of date
