### ISSUE TITLE
Squircles

### ISSUE THREAD

**Issue by nabato** [hyprwm/Hyprland#3804]
Does it support squircles? Please, add a definitive answer to the docs if possible.

**Comment by vaxerski** [comment]
No it doesn't.

> definitive answer to the docs if possible.

if it's not explicitly listed as supported, it's not. That's how docs work. Should I also mention it can't make a sandwich?

**Comment by nabato** [comment]
@vaxerski, `awesome-wm` or `i3` than. Thank you nonetheless.

**Comment by woutdp** [comment]
Just leaving this here for anyone who wants to implement Squircles, this code is the shader code to make squircles, it replaces the regular corner code. You'd still need to keep the previous code for the regular corners as squircles should be an option and not the default. `squirclePolynomial` might be interesting to keep as a config setting, something between 2 and 8 gives good results.

https://github.com/hyprwm/Hyprland/blob/main/src/render/shaders/Textures.hpp#L5-L33
```
inline static constexpr auto ROUNDED_SHADER_FUNC = [](const std::string colorVarName) -> std::string {
    return R"#(

    // branchless baby!
    highp vec2 pixCoord = vec2(gl_FragCoord);
    pixCoord -= topLeft + fullSize * 0.5;
    pixCoord *= vec2(lessThan(pixCoord, vec2(0.0))) * -2.0 + 1.0;
    pixCoord -= fullSize * 0.5 - radius;
    pixCoord += vec2(1.0, 1.0) / fullSize; // center the pix dont make it top-left

    if (pixCoord.x + pixCoord.y > radius) {
      float squirclePolynomial = 4.0;
      float squircle = pow(abs(pixCoord.x / radius), squirclePolynomial) + pow(abs(pixCoord.y / radius), squirclePolynomial) - 1.0;
      float edgeTransition = 1.0 - smoothstep(-0.02, 0.02, squircle);
      )#" + colorVarName + R"#( = )#" + colorVarName + R"#( * edgeTransition;
    }
    )#";
};
```

Won't pursue this further but migh be helpful to someone.

This is only the code for the texture, you'd still need to make the border work.
