### ISSUE TITLE
Adding noise on Nvidia only darkens the window background and creates dotted diagonal lines

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/Hyprland#3806]
### Hyprland Version

Hyprland, built from branch main at commit 751d2851cc270c3322ffe2eb83c156e4298a0c0e dirty (props: bump ver to 0.32.0).

### Bug or Regression?

Bug

### Description

`noise = 0.0`
![image](https://github.com/hyprwm/Hyprland/assets/98901170/e8e8771c-6e33-4892-af64-abcf1e265027)

`noise = 1.0`
![image](https://github.com/hyprwm/Hyprland/assets/98901170/fc53dc42-2b39-4cb6-b5c0-ca8c86373a45)

### How to reproduce

On an Nvidia GPU, set noise to a value higher than 0 and see the darkness increase as you increase the value. No noise is being generated. The dotted lines also become more visible.

**Comment by MathisP75** [comment]
My card is a 1660ti. Applies on `nvidia-dkms`for both 535 and 545.

**Comment by MathisP75** [comment]
Another user reproduced the issue on a 3090
![image](https://github.com/hyprwm/Hyprland/assets/98901170/8d2ec768-d668-42a8-928a-af11c016075c)

This is his result for a `pacman -Qs nvidia`:
```
local/cuda 12.3.0-1
    NVIDIA's GPU programming toolkit
local/egl-wayland 2:1.1.13-1
    EGLStream-based Wayland external platform
local/ffnvcodec-headers 12.1.14.0-1
    FFmpeg version of headers required to interface with Nvidias codec APIs
local/lib32-nvidia-utils 535.113.01-1
    NVIDIA drivers utilities (32-bit)
local/libva-nvidia-driver-git 0.0.11.r1.gea6d862-1
    VA-API implementation that uses NVDEC as a backend (git version)
local/libvdpau 1.5-2
    Nvidia VDPAU library
local/libxnvctrl 545.29.02-1
    NVIDIA NV-CONTROL X extension
local/nvidia-open-dkms 535.113.01-8
    NVIDIA open kernel modules
local/nvidia-utils 535.113.01-2
    NVIDIA drivers utilities
local/opencl-nvidia 535.104.05-1
    OpenCL implemention for NVIDIA
```

**Comment by MathisP75** [comment]
This is mine:
```
local/egl-wayland 2:1.1.13-1
    EGLStream-based Wayland external platform
local/ffnvcodec-headers 12.1.14.0-1
    FFmpeg version of headers required to interface with Nvidias codec APIs
local/hyprland-nvidia-git 0.32.0.r5.g8dd02eb5-1
    A dynamic tiling Wayland compositor based on wlroots that doesn't sacrifice on its looks. (NVIDIA patch)
local/lib32-libvdpau 1.5-2
    Nvidia VDPAU library
local/lib32-nvidia-utils 535.113.01-1
    NVIDIA drivers utilities (32-bit)
local/libva-nvidia-driver-git 0.0.11.r1.gea6d862-1
    VA-API implementation that uses NVDEC as a backend (git version)
local/libvdpau 1.5-2
    Nvidia VDPAU library
local/libxnvctrl 535.113.01-1
    NVIDIA NV-CONTROL X extension
local/nvidia-dkms 535.113.01-2
    NVIDIA drivers - module sources
local/nvidia-settings 535.113.01-1
    Tool for configuring the NVIDIA graphics driver
local/nvidia-utils 535.113.01-2
    NVIDIA drivers utilities
local/nvtop 3.0.2-1
    GPUs process monitoring for AMD, Intel and NVIDIA
```

**Comment by MathisP75** [comment]
The issue also occurs on a default Hyprland config on a separate profile.

**Comment by MathisP75** [comment]
Other users encounter the same issue. This is with an Nvidia GPU, where there is no noise but the dotted lines are visible: 
![image](https://github.com/hyprwm/Hyprland/assets/98901170/f4591bd9-fb5e-4d07-af84-f1bc0da7c6b6)

This is the same user running on an iGPU, where the noise works:
![image](https://github.com/hyprwm/Hyprland/assets/98901170/100e5e98-92c6-4a38-b011-ac0c3425c354)
The lines might be there too, but they could be harder to see if it's the case.

**Comment by MathisP75** [comment]
Another user has the noise working, but the lines are present (3 passes, 0.5 noise and size 8):
![image](https://github.com/hyprwm/Hyprland/assets/98901170/725c5e9d-7649-48b4-8fd6-c59ca6d2d98d)

Tweaked colors for better visibility:
<img width="1137" alt="image" src="https://github.com/hyprwm/Hyprland/assets/98901170/6f9bc22d-0f89-480a-b8a2-8d4b96eb99ef">

**Comment by vaxerski** [comment]
with all due respect, I don't give a shit. Why should I be the one responsible for nvidia's shader compiler having a tantrum?

Feel free to experiment with the noise generator for yourself:
https://github.com/hyprwm/Hyprland/blob/b8a615ffb892aaa35a15dc732208bb7ad2a60209/src/render/shaders/Textures.hpp#L386-L413

Closing. If you find a fix, feel free to MR, but I won't be the one hunting for it.

**Comment by Epikastema** [comment]
Have a fix working for the lines on my machine (RTX 4090). Would appreciate a test on different hardware to confirm

[0001.patch](https://github.com/hyprwm/Hyprland/files/14553246/0001.patch)

**Comment by vaxerski** [comment]
feel free to make a MR, but will need some further testing for sure.
