### ISSUE TITLE
weird flashing when closing windows.

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#3807]
### Hyprland Version

Hyprland, built from branch main at commit c619e6976f8d7f9637b4bee098159935412c2e99 dirty (screencopy: round boxes). Tag: v0.32.0-1-gc619e697

### Bug or Regression?

Regression

### Description

When a client is closed (using the window `slide` animation), remaining clients flash sometimes. This was not happening before this version. 

### How to reproduce

Open a few clients, then close them

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/208711/db42600f-1ee5-464d-94f0-b1d09ec5d3a1

**Comment by andresilva** [comment]
I can replicate.

**Comment by vaxerski** [comment]
what term is that

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13310632/patch.txt)
try

**Comment by primalmotion** [comment]
that patch does not seem to apply. 

1 out of 1 hunk FAILED -- saving rejects to file src/layout/IHyprLayout.cpp.rej

**Comment by primalmotion** [comment]
forget it. me dumb. compiling

**Comment by primalmotion** [comment]
the patch does not fix the problem. The terminal is foot. It also happens with alacritty

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13312831/patch.txt)
let's put it to grave.

**Comment by primalmotion** [comment]
It's actually flashing even more

**Comment by vaxerski** [comment]
excuse me what? It's fixed for me. Video evidence?

**Comment by primalmotion** [comment]
let me double check with a clean build

**Comment by primalmotion** [comment]
nah. still flashing


https://github.com/hyprwm/Hyprland/assets/208711/55c699f8-1b46-464e-b01b-ba11082457f4

**Comment by vaxerski** [comment]
why :(

**Comment by primalmotion** [comment]
I don't know :( The only difference is that I have to remove from the patch the dirty state of wlroots submodules. otherwise...
