### ISSUE TITLE
zwlr_screencopy_frame_v1 - invalid buffer dimensions

### ISSUE THREAD

**Issue by psoldunov** [hyprwm/Hyprland#3809]
### Hyprland Version

0.32.0

### Bug or Regression?

Bug

### Description

In tools like grim or hyprpicker I get following zwlr_screencopy_frame_v1 error:

`zwlr_screencopy_frame_v1@8: error 1: invalid buffer dimensions`

Screen sharing seems to be borked as well.

Using Hyprland version 0.32.0, xdph version 1.2.4, Fedora 39 from this [COPR](https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/).

### How to reproduce

run grim or similar

### Crash reports, logs, images, videos

[LOG] Window 5559d7dc34a0 set title to grim /t/h/751d2851cc270c3322ffe2eb83c156e4298a0c0e_1699559317
[LOG] ScreencopyProtocolManager bound successfully!
[ERR] [sc] invalid dimensions in 5559d76548b0

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/issues/3795
