### ISSUE TITLE
Waybar Workspaces Activation

### ISSUE THREAD

**Issue by hackedXD** [hyprwm/Hyprland#381]
When using waybar's `wlr/workspaces` module, everything works except for the `on-click` function. When clicked, neither `activate` nor `close` actions work. Is this intended or a bug on my end?

**Comment by vaxerski** [comment]
you need to apply a patch for switching to workspaces on click. The protocol itself does not support that. See https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=waybar-hyprland-git#n58

**Comment by nosvagor** [comment]
Forgive my ignorance, but using `waybar-hyprland-git` does not solve this in my case. I have the experimental features enabled (wlr/workspaces works), but the activate/close does not work still. Do I need to still apply an addition patch?

**Comment by vaxerski** [comment]
`waybar-hyprland-git` should apply the patch itself. For changing the workspace, of course. You can't just "close a workspace"

**Comment by nosvagor** [comment]
Hmm, just reinstalled waybar-hyprland-git from AUR to make sure. Still not working.

Waybar's wiki describes activate / close as actions (my waybar config is current same as the example, to test default case): 
https://github.com/Alexays/Waybar/wiki/Module:-Workspaces#actions

I assumed close just killed all windows in the workspace (that would be nice feature, I guess). I really don't ever click, as I use the keyboard 95% of the time to move between workspaces. However, I'm confused why it doesn't work and want it to work for no other reason to figure it out, mostly.

**Comment by vaxerski** [comment]
Close won't work. Activate should work as a patch is applied to make it use hyprctl.

**Comment by nosvagor** [comment]
Hmm, okay. How do I use hyprctl with the wlr/workspace module? hyprctl dispatch workspace {ID} would work as an on-click, but I'm not sure how to pass the ID via the module. 

Even just testing `"on-click": "hyprctl dispatch workspace e+1"` does nothing, still. (using wlr/workspaces) 

I could just set up custom modules for each workspace (that way I could also have workspaces show up, even no active windows are in the workspace). But then the whole active workspace would be a new issue to work around.
