### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#3810]
### Hyprland Version

Hyprland, built from branch  at commit da6fa9cbd24fb45edf35cc51317392e18f682595  ().

### Bug or Regression?

Bug

### Description

Crashes on launch since latest commit

### How to reproduce

Launch Hyprland from greetd or tty

### Crash reports, logs, images, videos

[hyprlandCrashReport3567.txt](https://github.com/hyprwm/Hyprland/files/13312947/hyprlandCrashReport3567.txt)

**Comment by vaxerski** [comment]
```
[wlr] [backend/backend.c:383] Failed to open any DRM device
```
driver issue

**Comment by matt1432** [comment]
why is this only happening since the latest commit though? Hyprland is the only thing different from my previous NixOS generation and it was perfectly fine

**Comment by vaxerski** [comment]
No clue, I don't use nix. It's definitely an issue on your end.

**Comment by matt1432** [comment]
Well, it works now with the newest commits, no clue why. Sorry for bothering you with this
