### ISSUE TITLE
Add the ability to switch to the wlroots vulkan renderer for use with nouveau/nvk

### ISSUE THREAD

**Issue by zeakzzz** [hyprwm/Hyprland#3812]
### Description

Currently, Nouveau's OpenGL driver has significant limitations. NVK aims to adopt Zink as its OpenGL driver, offering the potential for Vulkan support would benefit Nouveau/NVK users by eliminating an additional translation layer, streamlining the rendering process.

**Comment by vaxerski** [comment]
#1396
