### ISSUE TITLE
Screen sharing rotated screen or window shares unrotated

### ISSUE THREAD

**Issue by robertoash** [hyprwm/Hyprland#3815]
### Hyprland Version

Hyprland, built from branch main at commit 751d2851cc270c3322ffe2eb83c156e4298a0c0e dirty (props: bump ver to 0.32.0). Tag: v0.32.0  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Screen rotation works like a charm. However, when screen sharing a rotated screen on Google Meet on Chromium for example, the output is unrotated.

Please let me know if you need any additional information.

### How to reproduce

I have followed [these instructions](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580). 

I ended up using `xdg-desktop-portal-wlr` even though it is not recommended simply because `xdg-desktop-portal-hyprland` has the exact same screen sharing issues I am describing but also implements an additional window when you want to select what window to share (`xdg-desktop-portal-wlr` requires far less clicks to share a window than `xdg-desktop-portal-hyprland`). However, if a solution can be found using `xdg-desktop-portal-hyprland`, I would change despite it being more cumbersome.

[This fix](https://github.com/hyprwm/Hyprland/issues/2518) seems to relate to this issue but, from what I can understand, it has fixed screenshots but not necessarily screen sharing?

I have tried screen sharing in Vivaldi & Brave but the outcome is the same.

### Crash reports, logs, images, videos

This is a screenshot of the monitor:

![image](https://github.com/hyprwm/Hyprland/assets/42000824/7dff9ec8-f990-4a31-a61a-126eadf8ef6c)

And this is a screenshot of the shared screen:

![image](https://github.com/hyprwm/Hyprland/assets/42000824/c0003f5c-669c-4249-9c69-dfa307476be9)

**Comment by vaxerski** [comment]
so what you're saying is that xdpw rotates the screen properly? 

Well, in such a case, wrong tracker.

https://github.com/hyprwm/xdg-desktop-portal-hyprland
