### ISSUE TITLE
Qt scaling issue

### ISSUE THREAD

**Issue by ilyss01** [hyprwm/Hyprland#3817]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

I wrote about it [here](https://github.com/qutebrowser/qutebrowser/issues/7926#event-10455031204). Basically qutebrowser's scaling is very bad when hyprland scaling is set to anything but 1. I've seen [this](https://forums.ankiweb.net/t/pixelated-text-anki-in-hyprland-and-plasma-wayland-with-scaling-1-25/33746) so my guess is that hyprland scales Qt applications wrong

1 scale:
![1 0](https://github.com/hyprwm/Hyprland/assets/47274578/5104da33-3b8f-4f54-9f5b-83766a061a7b)

1.1 scale
![1 1](https://github.com/hyprwm/Hyprland/assets/47274578/22081824-fa65-4b16-946b-13e7f505021b)

Another thing to note: when qutebrowser is already started and I rewrite scaling 1 -> 1.1 - the browser looks fine. But as soon as I start qutebrowser under 1.1 scaling - it looks blurry

### How to reproduce

Set screen scaling to anything other than 1, start qutebrowser

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13320262/hyprland.log)

**Comment by ilyss01** [comment]
Forgot to mention: sway works just fine with the same global variables

**Comment by vaxerski** [comment]
is qutebrowser running in xwayland?

**Comment by q234rty** [comment]
This can also be repro'd on kwin and mutter; See https://bugreports.qt.io/browse/QTBUG-113574

**Comment by vaxerski** [comment]
oops - not hyprland then

**Comment by ilyss01** [comment]
> is qutebrowser running in xwayland?

No, I explicitly said it to use wayland
