### ISSUE TITLE
Not working in external monitor when refresh rate is overclocked

### ISSUE THREAD

**Issue by AFAgarap** [hyprwm/Hyprland#3818]
Hello. Not sure if this issue belongs to this repository, but whenever I try to overclock my external monitor to 75Hz, 100Hz, 120Hz, 144Hz, hyprland successfully does it but waybar unexpectedly quits. I've never encountered this when using sway. Thanks.

**Comment by vaxerski** [comment]
Probably not. Besides - invalid report. Please use the templates next time
