### ISSUE TITLE
workspace_back_and_forth doesn't work with try_swap_workspace

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#3819]
### Hyprland Version

Hyprland, built from branch HEAD at commit 5b8cfdf2efc44106b61e60c642fd964823fd89f3  (props: bump ver to v0.31.0). Tag: v0.31.0  flags: (if any) debug

### Bug or Regression?

Bug

### Description

When using try_swap_workspace, workspace_back_and_forth doesn't work

### How to reproduce

```
bind = $mainMod, 1, exec, try_swap_workspace 1
bind = $mainMod, 2, exec, try_swap_workspace 2
```
```
binds {
    workspace_back_and_forth = true
}
```
try swapping.

**Comment by vaxerski** [comment]
try_swap_workspace is not a part of hyprland. I don't know what that is.

This issue is invalid as it does not provide a hyprland bug.

**Comment by jabuxas** [comment]
wdym? https://github.com/hyprwm/contrib

**Comment by jabuxas** [comment]
but, sure, i can open the bug there

**Comment by vaxerski** [comment]
my bad, fuf maintains contrib
