### ISSUE TITLE
Opacity doesn't change for class 'Spotify'

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#382]
Hello! 
Soo...as the title says, idk for some weird reason, the Spotify app doesn't get affect by the opacity function even after putting it in the config file, yes i have used `hyprctl clients` to fetch the class info and thats what it says its class name is "Spotify".

Steps to reproduce: 
1) set the opacity for Spotify in the config file
2) open Spotify

my guesses are that either the class for Spotify is wrong or its something to do with Spotify's way of displaying things

and yeah, i've downloaded spotify from AUR

Thanks in advance!

![screenshot_20220716_191454](https://user-images.githubusercontent.com/90208727/179357577-e345321f-31bb-4798-a34c-380a144a68c4.png)
![screenshot_20220716_191637](https://user-images.githubusercontent.com/90208727/179357598-ce43acd7-9e48-4f79-8e6e-4771aa4f46e4.png)
![screenshot_20220716_191745](https://user-images.githubusercontent.com/90208727/179357628-486df90e-7d9b-4584-8ebc-67736d9aa7e3.png)

**Comment by vaxerski** [comment]
Ah yes, the broken spotify app. As far as I'm aware (I don't use spotify) the spotify app opens two windows, one being an invisible one with the class of "Spotify" and one being the visible one without a class.

Do `sleep 5 && hyprctl activewindow` in a terminal and focus spotify and it should show the broken window. If it has a class, that means spotify sets the class after mapping the window, which is kinda a violation of the protocol.

**Comment by System-x64** [comment]
Nope, it still only shows the one with a class 

![screenshot_20220716_193834](https://user-images.githubusercontent.com/90208727/179358310-fb7dd5eb-2db6-44de-84b6-98952ae0177f.png)

**Comment by vaxerski** [comment]
the second then. I'll probably add dynamic window rules soon so that would be fixed.

**Comment by System-x64** [comment]
K, thanks mate!

**Comment by System-x64** [comment]
shall i close this issue then?

**Comment by vaxerski** [comment]
keep it so i dont forget

**Comment by System-x64** [comment]
k

**Comment by patrickaldis** [comment]
Also @System-x64 how is your spotify so pretty?

**Comment by System-x64** [comment]
Hi @patrickaldis!

I use an app called spicetify, it themes the entire app with just a couple of commands, check it out!

https://spicetify.app/

**Comment by patrickaldis** [comment]
That's sick

**Comment by System-x64** [comment]
Ikr!!!!!!!

**Comment by crypticC0der** [comment]
any update on this

**Comment by System-x64** [comment]
@vaxerski

**Comment by System-x64** [comment]
> any update on this

@vaxerski

**Comment by Alxandr** [comment]
I just ran into a similar issue (which I assume is for the same reason) - spotify starts floating. I tried to create a rule to make it tiled, but looking at the hypr logs, it seems that the window is created with class `null` - which doesn't match my rule I imagine.

**Comment by pupbrained** [comment]
> I just ran into a similar issue (which I assume is for the same reason) - spotify starts floating. I tried to create a rule to make it tiled, but looking at the hypr logs, it seems that the window is created with class `null` - which doesn't match my rule I imagine.

Yeah, I've had the same issue for months. I've just resorted to starting it then tiling it right after.

**Comment by System-x64** [comment]
I just found a work around, instead of specifying spotify to be transparent, i used the `active_opacity` to make every active window a little transparent and then individually used the `windowrule opacity` for apps I dont want to be transparent (eg. firefox or videoplayers) keep in mind tho that active_opacity will make EVERY window transparent except the ones u explicitly specify

**Comment by fufexan** [comment]
You can use https://github.com/dasJ/spotifywm to fix spotify's lazy class/title set.

**Comment by Alxandr** [comment]
Guessing that's not an option for running spotify from flatpack?

**Comment by fufexan** [comment]
Why not? Does flatpak prevent prepending `LD_PRELOAD`?

**Comment by Alxandr** [comment]
Oh, wait, it's just an environment variable that needs to be set? Then I have no idea whether or not that'd work...
