### ISSUE TITLE
Drop shadow doesnt move with window when switching workspaces.

### ISSUE THREAD

**Issue by Slimemaster0** [hyprwm/Hyprland#3829]
### Hyprland Version

844da8db561f00f99d7e861b4b9a8bf51bbcd10c

### Bug or Regression?

Bug

### Description

.

### How to reproduce

1. Have drop shadows enabled and workspace switching animation enabled.
2. Open a window
3. Switch workspaces

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/51412894/98bea465-8811-4e68-a571-9faa99ee0781

**Comment by vaxerski** [comment]
oops

**Comment by Slimemaster0** [comment]
Thanks
