### ISSUE TITLE
Firefox based applications fail to render properly

### ISSUE THREAD

**Issue by Stella-Zephyr** [hyprwm/Hyprland#3830]
### Hyprland Version

Hyprland, built from branch main at commit 844da8db561f00f99d7e861b4b9a8bf51bbcd10c dirty (shaders: Avoid calculating unused values in hsl2rgb. (3827)).

### Bug or Regression?

Bug

## Firefox and programs based on its engine render improperly 

After installing this development build, attempting to open Firefox has resulted in me getting a poorly rendered version of the window. This seems to be exclusive to Firefox based programs. The top and left margins of the page are not rendered, while the right one seems to be improperly placed, and the bottom one has a melting like effect on nearby pixels. Additionally, cursor interaction is skewed and does not work properly on these windows.

Opening Discord and Spotify verifies that this does not replicate on Electron or Chromium based apps.

### How to reproduce

1. **Open Firefox** on this build of Hyprland. The bug should present itself.
2. Attempt to **click on the window**. Results should be skewed towards the top left.
3. Open a **custom fork** of Firefox. Example given is LibreWolf. The bug should present itself.
4. Open an Electron based web app. The bug **should not present itself**.

### Crash reports, logs, images, videos

![imagen](https://github.com/hyprwm/Hyprland/assets/149267509/52696b79-7759-498d-b810-b3ce094f5b53)

**Comment by vaxerski** [comment]
scaling? can't repro.

**Comment by sentakuhm** [comment]
> scaling? can't repro.

same issue without scaling, firefox and thunderbird.

**Comment by Makesesama** [comment]
I have the same problem, but not while firefox is fullscreen

**Comment by Stella-Zephyr** [comment]
Scaling is disabled.

**Comment by Stella-Zephyr** [comment]
Not sure this helps but my log seems kinda normal...

![imagen](https://github.com/hyprwm/Hyprland/assets/149267509/85354a32-8cf0-4a2e-a195-b64ea29ff850)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/b831a578-3bea-4deb-a4c5-c0f17c09fe69)
well...

a bisect or narrowing down the bug to some config opt is needed.

**Comment by vaxerski** [comment]
nvm, got it repro'd with librewolf.

**Comment by leon-erd** [comment]
Not sure if related but I assume so as the commit states "xdg: set state maximized for all tiled windows "
I configured firefox such that it opens a window where it asks me if I want to open a pdf in firefox or download it for example (setting browser.download.improvements_to_download_panel=false in about:config)
This window will sometimes appear maximized and the following windowrules do not help (they indeed match the window as changing the opacity for example works)
windowrulev2 = nofullscreenrequest, class:firefox, title:^Opening.*
windowrulev2 = nomaximizerequest, class:firefox, title:^Opening.*
windowrulev2 = float, class:firefox, title:^Opening.*

**Comment by leon-erd** [comment]
Window 55ac78b7db30 -> Opening studienbestaetigung.pdf:
	mapped: 1
	hidden: 0
	at: 1927,43
	size: 2546,1390
	workspace: 2 (2)
	floating: 1
	monitor: 1
	class: firefox
	title: Opening studienbestaetigung.pdf
	initialClass: firefox
	initialTitle:
	pid: 1503
	xwayland: 0
	pinned: 0
	fullscreen: 1
	fullscreenmode: 1
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
