### ISSUE TITLE
crash when opening steam (signal 11)

### ISSUE THREAD

**Issue by psoldunov** [hyprwm/Hyprland#3833]
### Hyprland Version

v0.32.2

### Bug or Regression?

Bug

### Description

Hyprland session crashes when opening Steam. Doesn't happen every time, but happened at least twice since updating to 0.32.2

### How to reproduce

1. Update to 0.32.2
2. Use system as usual
3. After a while launch steam and witness the crash

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Who tried dividing by zero?!

Hyprland received signal 11 (Segmentation fault)

Version: eab279984285250bd544de40868888186a8edeb7
Tag: v0.32.2

System info:
	System name: Linux
	Node name: Whopper
	Release: 6.5.11-300.fc39.x86_64
	Version: #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023

GPU:
	03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX] [1002:744c] (rev c8) (prog-if 00 [VGA controller])

os-release:
	NAME="Fedora Linux"
	VERSION="39 (Thirty Nine)"
	ID=fedora
	VERSION_ID=39
	VERSION_CODENAME=""
	PLATFORM_ID="platform:f39"
	PRETTY_NAME="Fedora Linux 39 (Thirty Nine)"
	ANSI_COLOR="0;38;2;60;110;180"
	LOGO=fedora-logo-icon
	CPE_NAME="cpe:/o:fedoraproject:fedora:39"
	DEFAULT_HOSTNAME="fedora"
	HOME_URL="https://fedoraproject.org/"
	DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
	SUPPORT_URL="https://ask.fedoraproject.org/"
	BUG_REPORT_URL="https://bugzilla.redhat.com/"
	REDHAT_BUGZILLA_PRODUCT="Fedora"
	REDHAT_BUGZILLA_PRODUCT_VERSION=39
	REDHAT_SUPPORT_PRODUCT="Fedora"
	REDHAT_SUPPORT_PRODUCT_VERSION=39
	SUPPORT_END=2024-05-14
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x69) [0x55f90c95ed29]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x6b8) [0x55f90c9288f8]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x48) [0x55f90c8adee8]
		??
		??:0
	#3 | /lib64/libc.so.6(+0x3e9a0) [0x7f65ba45c9a0]
		??
		??:0
	#4 | /lib64/libc.so.6(+0x1d8c40) [0x7f65ba5f6c40]
		??
		??:0

Log tail:
[wlr] [xwayland/xwm.c:1143] Failed to get window property
[LOG] [Window 55f90e515590: title: "", class: ] destroyed, queueing.
[LOG] XWayland class raw: null
[LOG] Callback 55f90e5156f0 -> 55f90e5156e8, XWayland Window removed.
[LOG] Callback 55f90e515b00 -> 55f90e515af8, XWayland Window removed.
[LOG] Callback 55f90e515ca0 -> 55f90e515c98, XWayland Window removed.
[LOG] Callback 55f90e515d08 -> 55f90e515d00, XWayland Window removed.
[LOG] Callback 55f90e515d70 -> 55f90e515d68, XWayland Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Unmapped [Window 55f90e515590: title: ""] removed instantly
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 55f90e515590: 55f90e5f7c40 -> 55f90e515ce0 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e5f7c50 -> 55f90e515d48 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e5f7bc0 -> 55f90e5156c8 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e5f7cf0 -> 55f90e515c78 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e5f7bd0 -> 55f90e515ad8 (owner: XWayland Window)
[LOG] [Window 55f90e515590: title: "", class: ] destroyed, queueing.
[LOG] XWayland class raw: null
[LOG] Callback 55f90e5156f0 -> 55f90e5156e8, XWayland Window removed.
[LOG] Callback 55f90e515b00 -> 55f90e515af8, XWayland Window removed.
[LOG] Callback 55f90e515ca0 -> 55f90e515c98, XWayland Window removed.
[LOG] Callback 55f90e515d08 -> 55f90e515d00, XWayland Window removed.
[LOG] Callback 55f90e515d70 -> 55f90e515d68, XWayland Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Unmapped [Window 55f90e515590: title: ""] removed instantly
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 55f90e515590: 55f90e513560 -> 55f90e515ce0 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e513570 -> 55f90e515d48 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e5134e0 -> 55f90e5156c8 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e513610 -> 55f90e515c78 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e5134f0 -> 55f90e515ad8 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 55f90e2faab0: 55f90e5f7c40 -> 55f90e2fb200 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e2faab0: 55f90e5f7c50 -> 55f90e2fb268 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e2faab0: 55f90e5f7bc0 -> 55f90e2fabe8 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e2faab0: 55f90e5f7cf0 -> 55f90e2fb198 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e2faab0: 55f90e5f7bd0 -> 55f90e2faff8 (owner: XWayland Window)
[LOG] Registered signal for owner 55f90e515590: 55f90e28b130 -> 55f90e5155f8 (owner: XWayland Window)
[ERR] Tearing hint 94528175561024 was attached to an unknown surface
[LOG] Registered signal for owner 55f90e515590: 55f90e3a6790 -> 55f90e515ba8 (owner: Toplevel)
[LOG] Registered signal for owner 55f90e515590: 55f90e3a67a0 -> 55f90e515c10 (owner: Toplevel)
[LOG] Registered signal for owner 55f90e515590: 55f90e3a67b0 -> 55f90e515b40 (owner: Toplevel)
[LOG] Registered signal for owner 55f90e515e18: 55f90e28b160 -> 55f90e515e30 (owner: CWLSurface)
[LOG] CWLSurface 55f90e515e18 called init()
[LOG] Registered signal for owner 55f90e515590: 55f90e28b140 -> 55f90e515660 (owner: CWindow)
[LOG] Searching for matching rules for steam (title: Sign in to Steam)
[LOG] Window rule noborder -> class:(steam) matched [Window 55f90e515590: title: "Sign in to Steam"]
[LOG] Window rule rounding 0 -> class:(steam) matched [Window 55f90e515590: title: "Sign in to Steam"]
[LOG] Window rule nomaxsize -> class:(steam) matched [Window 55f90e515590: title: "Sign in to Steam"]
[LOG] Set keyboard focus to surface 55f90e28ae50, with [Window 55f90e515590: title: "Sign in to Steam"]

**Comment by vaxerski** [comment]
was addressed in .3
