### ISSUE TITLE
Make `float` rule dynamic (related issue with Bitwarden opening maximized window on vault unlock)

### ISSUE THREAD

**Issue by ok-nick** [hyprwm/Hyprland#3835]
### Description

Unlocking a Bitwarden vault (from the Bitwarden extension) on Firefox causes a new maximized window to open. Bitwarden intends for only a small floating window to open, but I'm assuming there is some interference with the WM. So, windowrules.

The next issue is that Bitwarden initially opens the window as a regular Firefox instance (no unique `title` or `class` properties). Thus, it isn't possible(?) to prevent Bitwarden from initially opening the window maximized, unless there is a windowrule on all Firefox instances. However, Bitwarden does eventually rename  the window to `Extension: (Bitwarden - Free Password Manager) - Bitwarden — Mozilla Firefox`.

A solution is to apply windowrules properties, such as `float`, to the window when the `title` property changes. The only issue is that Hyprland doesn't mark the `float` rule as `dynamic`. Is there a reason behind this? Can it be feasibly implemented?

Related threads in the Discord server:
[`windowrulesv2` not working for Bitwarden Firefox window](https://discord.com/channels/961691461554950145/1160645555907735722)
[Window opens fullscreen and I need it to open as a small floating window](https://discord.com/channels/961691461554950145/1172327010526314637)

**Comment by vaxerski** [comment]
a dynamic float rule makes no sense.

**Comment by mfdorst** [comment]
Having the same issue. How does one script this behavior?

**Comment by vaxerski** [comment]
`hyprctl dispatch togglefloating <regex>`

**Comment by justanotherariel** [comment]
It took me a while, but for anyone being as annoyed as me, here is the script I wrote.

# Universal Script
```bash
#!/bin/sh

handle() {
  case $1 in
    windowtitle*)
      # Extract the window ID from the line
      window_id=${1#*>>}

      # Fetch the list of windows and parse it using jq to find the window by its decimal ID
      window_info=$(hyprctl clients -j | jq --arg id "0x$window_id" '.[] | select(.address == ($id))')

      # Extract the title from the window info
      window_title=$(echo "$window_info" | jq '.title')

      # Check if the title matches the characteristics of the Bitwarden popup window
      if [[ "$window_title" == *"(Bitwarden - Free Password Manager) - Bitwarden"* ]]; then
      
        # echo $window_id, $window_title
        # hyprctl dispatch togglefloating address:0x$window_id
        # hyprctl dispatch resizewindowpixel exact 20% 40%,address:0x$window_id
        # hyprctl dispatch movewindowpixel exact 40% 30%,address:0x$window_id

        hyprctl --batch "dispatch togglefloating address:0x$window_id ; dispatch resizewindowpixel exact 20% 40%,address:0x$window_id ; dispatch movewindowpixel exact 40% 30%,address:0x$window_id"        
      fi
      ;;
  esac
}

# Listen to the Hyprland socket for events and process each line with the handle function
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```

# For those that use NixOS & Home Manager:
`bitwarden-resize-script.nix`
```nix
pkgs:

pkgs.writeScript "hyprland-bitwarden-resize" ''
#!/bin/sh

handle() {
  case $1 in
    windowtitle*)
      # Extract the window ID from the line
      window_id=''${1#*>>}

      # Fetch the list of windows and parse it using jq to find the window by its decimal ID
      window_info=$(hyprctl clients -j | ${pkgs.jq}/bin/jq --arg id "0x$window_id" '.[] | select(.address == ($id))')

      # Extract the title from the window info
      window_title=$(echo "$window_info" | ${pkgs.jq}/bin/jq '.title')

      # Check if the title matches the characteristics of the Bitwarden popup window
      if [[ "$window_title" == *"(Bitwarden - Free Password Manager) - Bitwarden"* ]]; then
      
        # echo $window_id, $window_title
        # hyprctl dispatch togglefloating address:0x$window_id
        # hyprctl dispatch resizewindowpixel exact 20% 40%,address:0x$window_id
        # hyprctl dispatch movewindowpixel exact 40% 30%,address:0x$window_id

        hyprctl --batch "dispatch togglefloating address:0x$window_id ; dispatch resizewindowpixel exact 20% 40%,address:0x$window_id ; dispatch movewindowpixel exact 40% 30%,address:0x$window_id"
      fi
      ;;
  esac
}

# Listen to the Hyprland socket for events and process each line with the handle function
${pkgs.socat}/bin/socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
''
```

`home.nix`
```
xdg.dataFile."scripts/hyprland-bitwarden-resize.sh".source = (import ./bitwarden-resize-script.nix pkgs);
```

# Hyprland.conf
```
# Fix Bitwarden Window
windowrulev2 = suppressevent maximize, class:^(firefox)$
exec-once = $HOME/.local/share/scripts/hyprland-bitwarden-resize.sh
```

We need to supress the maximize event, for the whole class, as I couldn't find a hyprctl command which would allow me to do that based on the windowid or a regex expression (only currently focused window afaik). Just setting the window to float doesn't unmaximize the window. Maybe something to add @vaxerski?

Other than that, this should make the window the proper size and center it on the screen. Definetly not an easy solution. Let me know if there is an easier approach.

**Comment by Dreded** [comment]
for me there is an annoying issue that the window gets renamed twice, I am sure this is a bug on the firefox side but I had to use this script to limit it to one run per second also this floats it centered rather than tiling it to one edge like above script

```
#!/usr/bin/env bash
previous_time=$SECONDS
repeat_rate=1 #in seconds
handle() {
	case $1 in
	windowtitle*)
		local time=$((previous_time + repeat_rate))
		if ((time > SECONDS)); then
			return
		fi
		previous_time=$SECONDS
		# Extract the window ID from the line
		window_id=${1#*>>}

		# Fetch the list of windows and parse it using jq to find the window by its decimal ID
		window_info=$(hyprctl clients -j | jq --arg id "0x$window_id" '.[] | select(.address == ($id))')

		# Extract the title from the window info
		window_title=$(echo "$window_info" | jq '.title')

		# Check if the title matches the characteristics of the Bitwarden popup window
		if [[ "$window_title" == *"Extension: (Bitwarden - Free Password Manager)"* ]]; then
			#echo $window_id, $window_title
			hyprctl --batch "dispatch togglefloating address:0x$window_id ; dispatch centerwindow"
		fi
		;;
	esac
}

# Listen to the Hyprland socket for events and process each line with the handle function
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```

**Comment by celikj** [comment]
any up to date solution? this scripting thing is so complex for me

**Comment by terminal-enlightenment** [comment]
> any up to date solution? this scripting thing is so complex for me

The scripts above appear to solve this, have you tried them? Is it only bitwarden through firefox that you're having trouble with?

**Comment by cyhyraethz** [comment]
To get this to work for me, I needed to use `"$XDG_RUNTIME_DIR"` instead of `/tmp` for the path to the Hyprland socket on the last line of the script and change the window title check line to be more general and work in more cases, e.g. in case the window title ends with `— LibreWolf` instead of `— Mozilla Firefox`, or the parentheses read `(Bitwarden Password Manager)` instead of `(Bitwarden - Free Password Manager)`.

I also sort of combined the `hyprctl --batch` lines from each of the previous scripts. The first one did center the window for me, but always on my left monitor. The second one centered the window on my active monitor, but didn't resize the window so it ended up being way too big and covering the center half of my screen. To get the best of both worlds, I simply replaced `movewindowpixel exact 40% 30%` with `centerwindow`.

These were simple modifications anyone could have done, but I wanted to share them anyway in case it ends up helping anyone or even just saves them a bit of time. I also want to thank [ok-nick](https://github.com/ok-nick) for creating this issue in the first place, [justanotherariel](https://github.com/justanotherariel) for writing the original script, and [Dreded](https://github.com/Dreded) for sharing their own modified version of the script.

Here's what I ended up using:

```bash
#!/bin/bash

timeout=0
handle() {
    case $1 in
        windowtitle*)
            # Extract the window ID from the line
            window_id=${1#*>>}

            # Fetch the list of windows and parse it using jq to find the window by its decimal ID
            window_info=$(hyprctl clients -j | jq --arg id "0x$window_id" '.[] | select(.address == ($id))')

            # Extract the title from the window info
            window_title=$(echo "$window_info" | jq -r '.title')

            # Check if the title matches the characteristics of the Bitwarden popup window
            if [[ "$window_title" == *"(Bitwarden"*"Password Manager) - Bitwarden"* ]]; then

                # in case of double rename only allow once per second
                if ((SECONDS < timeout)); then
                    return
                fi
                timeout=$((SECONDS + 1))

                # echo "$window_id", "$window_title"
                hyprctl --batch "dispatch togglefloating address:0x$window_id; dispatch resizewindowpixel exact 20% 54%,address:0x$window_id; dispatch centerwindow"
            fi
            ;;
    esac
}

# Listen to the Hyprland socket for events and process each line with the handle function
socat -U - UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock | while read -r line; do handle "$line"; done
```

**Comment by martindmtrv** [comment]
Awesome, the provided scripts worked for me too! The huge bitwarden popup was driving me nuts

**Comment by Lywel** [comment]
This comment is for future me and @celikj (I hope you find it simpler). I keep having to search for this every time I reinstall Hyprland.

This is based on based on previous iteration on this thread + the current [doc about socket2](https://wiki.hyprland.org/IPC/).

```bash
#!/usr/bin/env bash

handle_windowtitlev2 () {
  # Description: emitted when a window title changes.
  # Format: `WINDOWADDRESS,WINDOWTITLE`
  windowaddress=${1%,*}
  windowtitle=${1#*,}

  case $windowtitle in
    *"(Bitwarden"*"Password Manager) - Bitwarden"*)
      hyprctl --batch \
        "dispatch togglefloating address:0x$windowaddress;"\
        "dispatch resizewindowpixel exact 20% 54%,address:0x$windowaddress;"\
        "dispatch centerwindow"
      ;;
#   specificwindowtitle) commands;;
  esac
}

handle() {
  # $1 Format: `EVENT>>DATA`
  # example: `workspace>>2`

  event=${1%>>*}
  data=${1#*>>}

  case $event in
    windowtitlev2) handle_windowtitlev2 "$data";;
#   anyotherevent) handle_otherevent "$data";;
    *) echo "unhandled event: $event" ;;
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```

**Comment by erahhal** [comment]
To be frank this isn't really a proper solution, as it requires a bunch of code and also behaves strangely - the window starts out tiled then jumps to center while resizing. It indicates that the WM itself needs to implement something to handle this, as there is no way to do it without strange behavior.

**Comment by celikj** [comment]
tysm bro @Lywel 

> This comment is for future me and @celikj (I hope you find it simpler). I keep having to search for this every time I reinstall Hyprland.
> 
> This is based on based on previous iteration on this thread + the current [doc about socket2](https://wiki.hyprland.org/IPC/).
> 
> ```shell
> #!/usr/bin/env bash
> 
> handle_windowtitlev2 () {
>   # Description: emitted when a window title changes.
>   # Format: `WINDOWADDRESS,WINDOWTITLE`
>   windowaddress=${1%,*}
>   windowtitle=${1#*,}
> 
>   case $windowtitle in
>     *"(Bitwarden"*"Password Manager) - Bitwarden"*)
>       hyprctl --batch \
>         "dispatch togglefloating address:0x$windowaddress;"\
>         "dispatch resizewindowpixel exact 20% 54%,address:0x$windowaddress;"\
>         "dispatch centerwindow"
>       ;;
> #   specificwindowtitle) commands;;
>   esac
> }
> 
> handle() {
>   # $1 Format: `EVENT>>DATA`
>   # example: `workspace>>2`
> 
>   event=${1%>>*}
>   data=${1#*>>}
> 
>   case $event in
>     windowtitlev2) handle_windowtitlev2 "$data";;
> #   anyotherevent) handle_otherevent "$data";;
>     *) echo "unhandled event: $event" ;;
>   esac
> }
> 
> socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
> ```

tysm

**Comment by johnhamelink** [comment]
> This comment is for future me and [@celikj](https://github.com/celikj) (I hope you find it simpler). I keep having to search for this every time I reinstall Hyprland.
> 
> This is based on based on previous iteration on this thread + the current [doc about socket2](https://wiki.hyprland.org/IPC/).
> 
> #!/usr/bin/env bash
> 
> handle_windowtitlev2 () {
>   # Description: emitted when a window title changes.
>   # Format: `WINDOWADDRESS,WINDOWTITLE`
>   windowaddress=${1%,*}
>   windowtitle=${1#*,}
> 
>   case $windowtitle in
>     *"(Bitwarden"*"Password Manager) - Bitwarden"*)
>       hyprctl --batch \
>         "dispatch togglefloating address:0x$windowaddress;"\
>         "dispatch resizewindowpixel exact 20% 54%,address:0x$windowaddress;"\
>         "dispatch centerwindow"
>       ;;
> #   specificwindowtitle) commands;;
>   esac
> }
> 
> handle() {
>   # $1 Format: `EVENT>>DATA`
>   # example: `workspace>>2`
> 
>   event=${1%>>*}
>   data=${1#*>>}
> 
>   case $event in
>     windowtitlev2) handle_windowtitlev2 "$data";;
> #   anyotherevent) handle_otherevent "$data";;
>     *) echo "unhandled event: $event" ;;
>   esac
> }
> 
> socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done

The NixOS configuration I'm using of this script - I had to add a  tweak to make it work with NixOS's directory structure:

`bitwarden-resize-script.nix`:

```nix
pkgs:

pkgs.writeScript "hyprland-bitwarden-resize" ''
#!/bin/sh

handle() {
  case $1 in
    windowtitle*)
      # Extract the window ID from the line
      window_id=''${1#*>>}

      # Fetch the list of windows and parse it using jq to find the window by its decimal ID
      window_info=$(hyprctl clients -j | ${pkgs.jq}/bin/jq --arg id "0x$window_id" '.[] | select(.address == ($id))')

      # Extract the title from the window info
      window_title=$(echo "$window_info" | ${pkgs.jq}/bin/jq '.title')

      # Check if the title matches the characteristics of the Bitwarden popup window
      if [[ "$window_title" == *"(Bitwarden Password Manager) - Bitwarden"* ]]; then

        hyprctl --batch "dispatch togglefloating address:0x$window_id ; dispatch resizewindowpixel exact 500 800,address:0x$window_id"
      fi
      ;;
  esac
}

# NB: the directory should match the UID of the user you are running hyprland in.
# Listen to the Hyprland socket for events and process each line with the handle function
${pkgs.socat}/bin/socat -U - UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
''
```

```nix
  wayland.windowManager.hyprland.settings = {
    exec-once = "$HOME/.local/share/scripts/hyprland-bitwarden-resize.sh";
    windowrulev2 = [
      "suppressevent maximize, class:^(firefox)$"
    ];
  };

  xdg.dataFile."scripts/hyprland-bitwarden-resize.sh".source =
    (import ./bitwarden-resize-script.nix pkgs);
```

**Comment by TophC7** [comment]
Here's my take at this, for Zen and able to handle any extension I define
A fish script in a NixOS config. All you gotta do is import it where appropriate.

I tried using 'builtins.toJSON'  directly in the script instead of making a file but it wasnt working 
idk what I was doing wrong so made a file instead. If anyone figures that out lemme know lol 
For now this works great

```nix
{ pkgs, lib, ... }:
let
  zen-extensions = {
    bitwarden = {
      regex = "'*(Bitwarden Password Manager) - Bitwarden*'";
      x = 500;
      y = 900;
    };
    authenticator = {
      regex = "'*(Authenticator) - Authenticator*'";
      x = 335;
      y = 525;
    };
  };

  zen-json = pkgs.writeText "zen-extensions.json" (builtins.toJSON zen-extensions);
  zen-script = pkgs.writeScript "zen-script" ''
    #!/usr/bin/env fish

      function handle
          set -l line $argv[1]
          switch $line
              case "windowtitlev2*"
                  # Expected format: windowtitlev2>><id>,<title>
                  set -l payload (string replace -r '^windowtitlev2>>' "" $line)
                  set -l parts (string split "," $payload)
                  set -l window_id (string trim $parts[1])
                  set -l title (string join "," $parts[2..-1])
                  
                  # Debug output
                  echo "Extracted window_id: [$window_id]"
                  echo "Extracted title: [$title]"
                  
                  # Loop over the extensions defined in the JSON file.
                  for ext in ( ${pkgs.jq}/bin/jq -r 'keys[]' ${zen-json} )
                      echo "Processing extension: [$ext]"
                      # Get regex, x and y for the current extension.
                      set -l reg ( ${pkgs.jq}/bin/jq -r --arg k $ext '.[$k].regex' ${zen-json} )
                      set -l ext_x ( ${pkgs.jq}/bin/jq -r --arg k $ext '.[$k].x' ${zen-json} )
                      set -l ext_y ( ${pkgs.jq}/bin/jq -r --arg k $ext '.[$k].y' ${zen-json} )
                      
                      # Remove any extra surrounding single quotes.
                      set -l reg (string trim -c "'" $reg)
                      
                      # Debug: show the extension and regex being used.
                      echo "Checking extension [$ext] with regex [$reg] against title [$title]"
                      
                      # If the title matches the regex, dispatch floating commands.
                      if string match -q -- "*$reg*" "$title"
                          echo "$ext window id: $window_id -- setting float mode with size $ext_x x $ext_y"
                          hyprctl dispatch togglefloating address:0x$window_id
                          hyprctl dispatch resizewindowpixel exact $ext_x $ext_y,address:0x$window_id
                          hyprctl dispatch movewindowpixel exact 64% 3%,address:0x$window_id
                          return
                      end
                  end
                  ;;
              case "*"
                  # Do nothing for other events.
                  ;;
          end
      end

      ${pkgs.socat}/bin/socat -U - UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -l line
          handle "$line"
      end
  '';
in
{
  wayland.windowManager.hyprland.settings = {
    exec-once = [
      "${pkgs.fish}/bin/fish ${zen-script}"
    ];

    windowrulev2 = [
      # Zen Extensions
      "suppressevent maximize, class:^(zen)$"
    ];
  };
}

```

**Comment by karamanliev** [comment]
I just wanted to share a solution which is really simple and I've found is more consistent (for me at least). The scripts posted here don't work 100% of the times, even though they are great. Also I don't like the way the window starts tiled, then goes to floating mode. In my workflow bitwarden popups are opened more frequently than browser windows.

What I did is setting up a windowrule for my browser which makes it open always in floating mode and in the wanted size:
```bash
windowrule = float, class:zen
windowrule = center, class:zen
windowrule = size 620 920, class:zen
```

Then I created a simple `launch_browser.sh` script:
```bash
#!/bin/bash

BROWSER="zen-browser"
BROWSER_CLASS="zen"
SLEEP_TIME=0.5
ACTIVE_ONLY=false
BROWSER_ARGS=()

for arg in "$@"; do
  case "$arg" in
  --sleep=*)
    SLEEP_TIME="${arg#--sleep=}"
    ;;
  --active-only)
    ACTIVE_ONLY=true
    ;;
  *)
    BROWSER_ARGS+=("$arg")
    ;;
  esac
done

if [[ "$ACTIVE_ONLY" = true ]]; then
  active_class=$(hyprctl activewindow -j 2>/dev/null | jq -r .class)
  if [[ "$active_class" != "$BROWSER_CLASS" ]]; then
    exit 0
  fi
fi

"$BROWSER" "${BROWSER_ARGS[@]}" &

sleep "$SLEEP_TIME"

browser_address=$(hyprctl clients -j 2>/dev/null | jq -r ".[] | select(.class == \"${BROWSER_CLASS}\").address" | tail -1)

if [ -n "$browser_address" ]; then
  hyprctl dispatch settiled address:$browser_address
fi
```

Then I set this script to run on startup instead of just `zen-browser` and changed my browser bind and desktop shortcuts to open this script instead of just `zen-browser`:
```bash
# ~/.config/hypr/hyprland.conf
exec-once = [workspace 1 silent] /path/to/launch_browser.sh --sleep=3

bind = $mainMod, RETURN, exec, /path/to/launch_browser.sh
bind = CTRL SHIFT, P, exec, /path/to/launch_browser.sh --active-only --private-window # change to your new private window bind inside the browser
```

```bash
# ~/.local/share/applications/zen.desktop
[Desktop Entry]
Name=Zen Browser
Comment=Experience tranquillity while browsing the web without people tracking you!
Exec=/path/to/launch_browser.sh %u
Icon=zen-browser
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;application/pdf;application/json;
StartupWMClass=zen
Categories=Network;WebBrowser;
StartupNotify=true
Terminal=false
X-MultipleArgs=false
Keywords=Internet;WWW;Browser;Web;Explorer;
Actions=new-window;new-private-window;profilemanager;

[Desktop Action new-window]
Name=Open a New Window
Exec=/path/to/launch_browser.sh %u

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=/path/to/launch_browser.sh --private-window %u

[Desktop Action profilemanager]
Name=Open the Profile Manager
Exec=/path/to/launch_browser.sh --ProfileManager %u
```

Cheers!

**Comment by shellkr** [comment]
> To be frank this isn't really a proper solution, as it requires a bunch of code and also behaves strangely - the window starts out tiled then jumps to center while resizing. It indicates that the WM itself needs to implement a first class mechanism to handle this, as there is no way to do it without strange behavior.

Yes, a WM 2025 should be able to handle this. Others do. A lot of people have an issue with this so it does make sense to add support for this. Instead of needing to make hacks to get it working.

**Comment by raygamedev** [comment]
any updates on it ?, I was trying to solve it using the obvious solution of trying to match:title *bitwarden* or whats ever, only to find out a whole thread on it here. 

i am surprised people need to go through a ninja course only to get it working properly

**Comment by lou-bi** [comment]
Honestly just an optional delay parameter would already be a huge win. I refuse to use IPC to solve this, its too much!

**Comment by xnov22** [comment]
In hyprland 0.55 with lua config, at least it's possible to do this without an external script (but it's still a workaround):

```lua
hl.on("window.title", function(w)
    local prefix = "Extension: (Bitwarden - Free Password Manager) - Bitwarden"
    if w.title:sub(1, #prefix) == prefix then
        local monitor = hl.get_active_monitor()
        if monitor == nil then
            return
        end

        local win = { width = 500, height = 800 }
        local pos = { x = monitor.width - win.width - 40, y = 160 }

        hl.dispatch(hl.dsp.window.float({ action = "enable", window = w }))
        hl.dispatch(hl.dsp.window.resize({ x = win.width, y = win.height, relative = false, window = w }))
        hl.dispatch(hl.dsp.window.move({ x = pos.x, y = pos.y, relative = false, window = w }))
    end
end)
```

**Comment by Lywel** [comment]
As its the tradition now I'll add my own version:
```lua
---@class FloatRule
---@field width    integer    width as percent of monitor width  (1..100)
---@field height   integer    height as percent of monitor height (1..100)
---@field patterns string[]   Lua patterns matched against window title

---@type FloatRule[]
local rules = {
  { width = 30, height = 54, patterns = {
      "%(Bitwarden.*Password Manager%) %- Bitwarden",
      "^Bitwarden$",
  }},
  { width = 25, height = 54, patterns = {
      "^Connexion : comptes Google %—",
      "^Sign In %- Google Accounts %— ",
      "^Sign in %- Google Accounts %- Helium$",
  }},
  { width = 25, height = 54, patterns = {
      "^Extension: %(MetaMask%) %- MetaMask %— Firefox",
  }},
}

---Return true if `title` matches any pattern in `rule`.
---@param title string
---@param rule  FloatRule
---@return boolean
local function matches(title, rule)
  for _, pattern in ipairs(rule.patterns) do
    if title:match(pattern) then return true end
  end
  return false
end

hl.on("window.title", function(window)
  local title = window.title or ""
  for _, rule in ipairs(rules) do
    if matches(title, rule) then
      local monitor = hl.get_active_monitor()
      if not monitor then return end

      hl.dispatch(hl.dsp.window.float({  window = window, action = "on" }))
      hl.dispatch(hl.dsp.window.center({ window = window, action = "on" }))
      hl.dispatch(hl.dsp.window.resize({
        window = window,
        x = math.floor(monitor.width  * rule.width  / 100),
        y = math.floor(monitor.height * rule.height / 100),
      }))
      return
    end
  end
end)
```

**Comment by Malick-Tammal** [comment]
small temporary solution 
the issue is when I open the extension it get tailed then it get float fast move
```lua
hl.on("window.title", function(win)
	if win.class == "firefox" and string.find(win.title, "Bitwarden Password Manager") then
		local target = "address:" .. win.address
		hl.notification.create({ text = target, timeout = 10000 })

		hl.dispatch(hl.dsp.window.float({ action = "enable", window = target }))
		hl.dispatch(hl.dsp.window.center({ window = target }))
	end
end)

```
