### ISSUE TITLE
Support DRM_MODE_PAGE_FLIP_ASYNC 

### ISSUE THREAD

**Issue by h0tc0d3** [hyprwm/Hyprland#3838]
### Description

I used https://wiki.hyprland.org/Configuring/Tearing/ and tried to configure tearing, but in this mode the game lags and the cursor lags. My system have xwayland and mesa 23.3 with PresentOptionAsyncMayTear support. WLR_DRM_NO_ATOMIC uses the old DRM API, I think this is the reason, but there are patches for the kernel to support the new API and Hyprland apparently does not support it. I would also like to know what vrr and vfr values to use to get the minimum input and output lag for 240Hz monitor.

https://lore.kernel.org/all/20231025005318.293690-3-andrealmeid@igalia.com/T/#u

**Comment by vaxerski** [comment]
we already support that.

The new API still doesn't have support for tearing, the patches are not in the kernel AFAIK. Even if they are, wlroots doesn't support that yet.

I would like to point that:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/b4057e96-10e3-4a22-9aae-efa8a6961733)

**Comment by h0tc0d3** [comment]
@vaxerski https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4445
```
The kernel patches [1](https://patchwork.freedesktop.org/series/120103/) have been merged.
```

**Comment by vaxerski** [comment]
well then we need a wlroots mr first :)
