### ISSUE TITLE
Support for openGL 2.1

### ISSUE THREAD

**Issue by 21givenchy** [hyprwm/Hyprland#3839]
### Description

Hi I have been trying to use hyperland but it does not support OpenGL 2.1 since my graphic drivers are old and can only support opengl2.1. Would love to move to Hyperland.
Lets goo

**Comment by tchofy** [comment]
Have you tried [compiling it with legacy renderer](https://wiki.hyprland.org/Getting-Started/Installation/#custom-installation-legacy-renderer-etc)?

**Comment by 21givenchy** [comment]
Trying it now

**Comment by 21givenchy** [comment]
Works thanks @tchofy
