### ISSUE TITLE
[Gestures] Changing to final workspace shows first workspace briefly

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyprwm/Hyprland#384]
At the end of the video you can see the first workspace briefly appear behind the windows.

https://user-images.githubusercontent.com/29136904/179372396-d0077368-e9a2-4c7c-8f41-04ce40c4e42f.mp4

**Comment by vaxerski** [comment]
does this also happen if you wait for the animation to end and then switch? You did 2 quick switches.

**Comment by ChristianChiarulli** [comment]
https://user-images.githubusercontent.com/29136904/179372581-3da7f290-96d0-4720-8e92-bec65a4b006f.mp4

yes, if I wait for the animation to finish, then swipe again it will still happen

**Comment by vaxerski** [comment]
alr, will try to fix tmr

**Comment by vaxerski** [comment]
fixed in 0026414f9bbefed9ba4838b600dd2566968bfc8a
