### ISSUE TITLE
Screen shader not appled to hradware rendered cursors

### ISSUE THREAD

**Issue by KorigamiK** [hyprwm/Hyprland#3840]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

The cursor remains unaffected by the shader.

### How to reproduce

Use `env = WLR_NO_HARDWARE_CURSORS,0` with a screen shader applied

```
decoration {
      screen_shader = ~/.config/hypr/shaders/blue-light.hlsl
}
```

**Comment by vaxerski** [comment]
obviously...?

**Comment by KorigamiK** [comment]
> obviously...?

Maybe I'd want that to happen 😞

**Comment by vaxerski** [comment]
you can't, they are _hardware_
