### ISSUE TITLE
Weird artefacts around layer elements

### ISSUE THREAD

**Issue by fybx** [hyprwm/Hyprland#3844]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

[swaync](https://github.com/ErikReider/SwayNotificationCenter) provides a layer namespace for floating notifications. I created a valid GTK-style CSS and set the background of floating notifications to transparent. Then I set `layerrule = ignorezero, swaync-notification-window` to remove this artefact, which didn't work.

`$ hyprctl layers`:
```
Layer level 3 (overlay):
		Layer 55ef3fab01f0: xywh: 3340 32 500 164, namespace: swaync-notification-window
```

Here's how it looks:
![image](https://github.com/hyprwm/Hyprland/assets/41127439/17a28071-ee5c-4093-9894-c1b22e55b79e)

Same issue on swaync: https://github.com/ErikReider/SwayNotificationCenter/issues/335

### How to reproduce

1. Install swaync
2. Use a style.css with 
```css
.floating-notifications { background: transparent; }
.background { background: transparent; }
```
3. The artefact is clearly there.

**Comment by vaxerski** [comment]
looks like layerrule blur is in effect.

Ignorezero works properly. It ignores _zero_, and a shadow is not _zero_.

Looks like expected behavior
