### ISSUE TITLE
number of dispatchers that hyprctl and its socket can take as a batch is limited

### ISSUE THREAD

**Issue by Aylur** [hyprwm/Hyprland#3846]
### Hyprland Version

Hyprland, built from branch  at commit 0ba2e6870478bcf1af1b6508677b46a3484fb21f  ().

### Bug or Regression?

Bug

### Description

Basically title. I am trying to dispatch 48 commands on the socket as a batch, but it can't take more than 24. The socket just closes if its more than that. I tested it by dispatching `keyword general:border_size 1;` as many times as it could, and it can't take more than 31, so I suspect its the length of the string.

### How to reproduce

last one the 32nd fails 
```bash
hyprctl --batch "keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; keyword general:border_size 1; "
```

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13329464/patch.txt)

all hail lord aylur, can you try this?

**Comment by Aylur** [comment]
Applied the patch, same thing happens with `hyprctl`. I can't test the socket because with this patch applied Hyprland freezes up on start. Now it could be related that I am on NixOS and I am not quite sure how to apply patches. I cloned the repo, did `git apply path-to.patch`, `nix build` `./result/bin/Hyprland`

**Comment by vaxerski** [comment]
I'll test a bit more myself later today. Protip: don't use `git apply`, use `patch -p1 < /path/...`

**Comment by vaxerski** [comment]
all hail lord aylur
