### ISSUE TITLE
Kitty's background_opacity not working as expected

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#3847]
Please, read the bug report here:
https://github.com/kovidgoyal/kitty/issues/6815

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/ceb04f44-edf8-49db-8102-572710daa649)

Most likely you have blur enabled with brightness/contrast settings set high.

or #3787

**Comment by Aqa-Ib** [comment]
I have blur disabled.

Also, you did not achieve to reproduce the bug, my bad for not explaining it:
Steps to reproduce:
1. Disable Hyprland's transparency and blur for kitty.
2. Use the attached wallpaper. Reason: not every wallpaper triggers a big contrast change, it depends on the colors. The colors of the girl in the attached wallpaper triggers a big contrast change.
3. Set kitty's background_opacity to 0.1 . Reason: if you set a lower value, you can not perceive the contrast change. 

![another-anime-girl](https://github.com/hyprwm/Hyprland/assets/16420574/f96f3e9e-c488-4904-8ef5-db6e847be2f3)

**Comment by Aqa-Ib** [comment]
Worth noting is that Alacritty does not trigger this bug. Kitty's developer is confident that this is not kitty's doing, so something is up here.

**Comment by vaxerski** [comment]
what if you disable `decoration:blur:vibrancy`? (set to 0)

**Comment by Aqa-Ib** [comment]
Same thing.

**Comment by Aqa-Ib** [comment]
What, there is another step I did not mention to reproduce it:
4. Choose a light kitty theme. For example this one:
`kitty +kitten themes GitHub Light `

**Comment by Aqa-Ib** [comment]
Wait a minute. With dark themes there is no problem at all. The problem is only reproducible with kitty light themes.

**Comment by Aqa-Ib** [comment]
I have tried with sway and Plasma wayland and the same problem arises. This is on kitty for sure.

Thanks.
