### ISSUE TITLE
Alacritty crash on start

### ISSUE THREAD

**Issue by MiniApollo** [hyprwm/Hyprland#3848]
### Hyprland Version

v0.32.3

### Bug or Regression?

Bug

### Description

When opening up alacritty from anywhere (terminal, hotkey with exec), it crashes.
The window just closes as soon as possible.
This started happening after v0.32.0 release.

### How to reproduce

Open up alacritty from anywhere.

### Crash reports, logs, images, videos

[LOG] Registered signal for owner 55c3910ec540: 55c392cfe590 -> 55c3910ec698 (owner: SurfaceTreeNode)
[LOG] Added a new subsurface 55c392ce8ac0
[LOG] Registered signal for owner 55c392d064f0: 55c392d07930 -> 55c392d06508 (owner: Subsurface)
[LOG] Registered signal for owner 55c392d064f0: 55c392d07940 -> 55c392d06570 (owner: Subsurface)
[LOG] Registered signal for owner 55c392d064f0: 55c392ce8b40 -> 55c392d065d8 (owner: Subsurface)
[LOG] Creating a surfaceTree Root! [Window 55c392d12720: title: "foot"]
[LOG] Map request dispatched, monitor eDP-1, window pos: [0.00000, 0.00000], window size: [1920.00000, 1046.00000]
[LOG] Registered signal for owner 55c3919cf948: 55c392cfd530 -> 55c3919cf960 (owner: CWLSurface)
[LOG] CWLSurface 55c3919cf948 called init()
[LOG] Cleanup: destroyed a window
[LOG] New Gamma event at 7ffc91ee6ae0
[LOG] Callback 55c3919cf988 -> 55c3919cf980, CWLSurface removed.
[LOG] CWLSurface 55c3919cf948 called destroy()
[LOG] Registered signal for owner 55c3919cf948: 55c392cfd530 -> 55c3919cf960 (owner: CWLSurface)
[LOG] CWLSurface 55c3919cf948 called init()
[LOG] New Gamma event at 7ffc91ee6ae0

**Comment by MrDuartePT** [comment]
Having the same problem. Alacritty log:
```interface 'wl_surface' has no event 2
warning: queue 0x7f91ec000ca0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190081 still attached
  zwp_primary_selection_offer_v1@4278190080 still attached
  zwp_primary_selection_device_v1@25 still attached
  zwp_primary_selection_device_manager_v1@21 still attached
  wl_data_device@24 still attached
  wl_seat@23 still attached
  wl_data_device_manager@22 still attached
  wl_registry@20 still attached
warning: queue 0x55873e969350 destroyed while proxies still attached:
  xdg_wm_base@36 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
warning: queue 0x55873e9a3540 destroyed while proxies still attached:
  wl_callback@31 still attached
  wl_surface@33 still attached
Error: "Event loop terminated with code: 1"```

**Comment by vaxerski** [comment]
this is an alacritty issue

**Comment by MrDuartePT** [comment]
@vaxerski sorry but I think is not a alacritty issue since happen to the Wayland backend after updating 0.31.0 to 0.32.3.

**Comment by vaxerski** [comment]
it is an alacritty issue

**Comment by MrDuartePT** [comment]
Can confirm that x11-terms/alacritty-0.12.3 solve it

**Comment by MiniApollo** [comment]
yes alacritty-0.12.3 fixes the issue
