### ISSUE TITLE
Mouse scrolling is not detected after closing window on another layer until the mouse is moved

### ISSUE THREAD

**Issue by vE5li** [hyprwm/Hyprland#3852]
### Hyprland Version

9afdd61adeaf413afbe853dbc5fdf6853c8bde21

### Bug or Regression?

Bug

### Description

Same issue as #3679 just in a different situation

### Steps to reproduce:
- Open a window (window scrolls fine)
- Open window in another layer (e.g. `rofi-wayland`)
- Close overlay window
- Scroll without moving the mouse

### Expected outcome:
The window should scroll

### Noted outcome:
It doesn't. However, the scrolling continues after I move my mouse inside the window.

**Comment by soufhehe** [comment]
it works, can be closed
