### ISSUE TITLE
Primary selection is buggy

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#386]
step to reproduce:
1. select some texts in anywhere (text editor/browser/etc)
2. use `wl-clipboard` tool `wl-paste -p` to paste primary selection to terminal

expected behavior: selected texts are shown in the terminal. (As a ref, sway doesn't have this defect)

actual behavior: `wl-paste -p` shows there is not selection.

**Comment by vaxerski** [comment]
fuixed in afeb040684017dfb27ca3cb3823e41dd95310af1 :-)))))))
