### ISSUE TITLE
Performance regression with many windows open

### ISSUE THREAD

**Issue by end-4** [hyprwm/Hyprland#3860]
### Hyprland Version

since 64a084477ea8df67cbb35b22826a1f6a0845e123

### Bug or Regression?

Regression

### Description

As the title suggests

### How to reproduce

- In two workspaces, open 30-32 windows in each.
- Switch between the two workspaces with animations enabled
- The lag should be noticeable at commit 64a084477ea8df67cbb35b22826a1f6a0845e123  (shadows: fix on transformed) or later.

### Commit 7a09d24065050ad5b9490a6be947229ae83cb824 (shadow: fix ignore_window false)
- Smooth

https://github.com/hyprwm/Hyprland/assets/97237370/6ccb56c3-83de-4e95-b22a-1609127bad3c

### Commit 64a084477ea8df67cbb35b22826a1f6a0845e123 (shadows: fix on transformed)
- Goes below 30fps

https://github.com/hyprwm/Hyprland/assets/97237370/6e86559c-bc29-481d-ba7b-17d2689b13f6

### Latest (keybinds: Close special workspace after moving windows out of it)
- Reaches below 40fps

https://github.com/hyprwm/Hyprland/assets/97237370/911e9a94-a7a2-4945-80a6-a948065347d1

**Comment by end-4** [comment]
oops, forgot to select the right label

**Comment by vaxerski** [comment]
does it go away with shadows off?

**Comment by end-4** [comment]
Right, should've tested that.
- Disabling shadows made it run just fine
- Disabling ignore_window while having shadows enabled also makes hyprland run smoothly, because it makes shadows not get drawn at all (which is different to what the wiki says)

**Comment by vaxerski** [comment]
> Disabling ignore_window while having shadows enabled also makes hyprland run smoothly, because it makes shadows not get drawn at all (which is different to what the wiki says, in my interpretation)

well it shouldnt xd

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13376875/patch.txt)
try

**Comment by end-4** [comment]
it works
enabling shadows no longer causes lag

**Comment by vaxerski** [comment]
why?
