### ISSUE TITLE
Crash when `windowrulev2` has no regex after field name

### ISSUE THREAD

**Issue by ENDERZOMBI102** [hyprwm/Hyprland#3863]
### Hyprland Version

1b48642fd15c433c53876f1b933dcd46265caf8f

### Bug or Regression?

Bug

### Description

Having an incomplete rule v2 ( `windowrulev2 = float, class:` in our case ) and saving will lead Hyprland to crash instead of producing the usual "there's an error in your config" red message box.

Encountered while using Hyprland from `extra` repository on Arch and an editor with autosave, was not a manual save.

### How to reproduce

1. Write an incomplete window rule v2 in the config (`windowrulev2 = float, class:` as example)
2. Save
3. Hyprland crashes

### Crash reports, logs, images, videos

[hyprlandCrashReport8884.txt](https://github.com/hyprwm/Hyprland/files/13376771/hyprlandCrashReport8884.txt)

**Comment by vaxerski** [comment]
I think my hyprland is indestructible. 

![image](https://github.com/hyprwm/Hyprland/assets/43317083/d48f0b57-2653-4571-b563-674c8383ff00)

maybe it's too scared of me in order to crash?

**Comment by ENDERZOMBI102** [comment]
i presume that's build with the latest commit?

**Comment by ENDERZOMBI102** [comment]
alright building from latest makes it work, was looking at the commit history to see what fixed it but not familiar enough with the codebase to find it, will close this.

Thank for your work on Hyprland!
