### ISSUE TITLE
Hyprland crash when i open a window

### ISSUE THREAD

**Issue by Slimemaster0** [hyprwm/Hyprland#3865]
### Hyprland Version

859841f

### Bug or Regression?

Bug

### Description

The title says it all

### How to reproduce

I startup Hyprland and then i open a window, note that nither wofi nor waybar causes the crash.

### Crash reports, logs, images, videos

[hyprlandCrashReport2938.txt](https://github.com/hyprwm/Hyprland/files/13380386/hyprlandCrashReport2938.txt)

**Comment by vaxerski** [comment]
I wanna kill myself

**Comment by Slimemaster0** [comment]
Thanks
