### ISSUE TITLE
Hyprland create a small size of floating windows

### ISSUE THREAD

**Issue by LudovicoSforza** [hyprwm/Hyprland#387]
So whenever i tried to login on some website with Login with Google button, hyprland gonna create a small (dot) floating windows.

Steps to reproduce: 
1. Open Website that has Login with Google button
2. Click the button
3. It's gonna create a new page with small size ( see my screenshot )

Expected outcome: It should create a floating windows with normal size 

![image](https://user-images.githubusercontent.com/44255157/179497607-ef4e0f18-6e95-4da4-bd32-f6563c44505d.png)

**Comment by vaxerski** [comment]
provide a better example.  Login with google on the site i tested redirects me to a google website.

**Comment by LudovicoSforza** [comment]
Alright, seems like the latest commit fix my issue. Thanks.
