### ISSUE TITLE
[QUESTION] about the focus_on_activate function

### ISSUE THREAD

**Issue by TAforever** [hyprwm/Hyprland#3870]
### Description

This is a very useful feature that I unfortunately cannot use.
The function is very useful when I click on a link in a third-party application and instantly go to the browser automatically, but if, for example, I play some online game and I receive a message from Telegram, then I automatically go to the workspace where Telegram is located. If a letter arrives, this does not happen with Thunderbird. Can anything be done about this?

**Comment by vaxerski** [comment]
I believe you can disable that in telegram. This is a dupe of some other issue here

**Comment by TAforever** [comment]
> I believe you can disable that in telegram. This is a dupe of some other issue here

Unfortunately, there is no such setting in Telegram and the problem relates to the focus_on_activate function

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/issues/2732

**Comment by TAforever** [comment]
> #2732
Thank you sir!

**Comment by TAforever** [comment]
> #2732

Thank you sir!
