### ISSUE TITLE
Can't Load any Plugin

### ISSUE THREAD

**Issue by 0xUnixy** [hyprwm/Hyprland#3874]
### Hyprland Version

Hyprland, built from branch main at commit db8f13291a4e046e82c9b11c5bfd08f223bd52b1 dirty (hyprctl: add monitors all to report all connected monitors (3730)). Tag: v0.32.3-29-gdb8f1329  flags: (if any) debug

### Bug or Regression?

Bug

### Description

i can't load any plugin even i installed `hyprland` the right && normal way.

### How to reproduce

- install `hyprland` :
```bash
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
make all && sudo make install
```
- compile and load the plugin:
```bash
git clone https://github.com/hyprwm/hyprland-plugins && cd hyprland-plugins/borders-plus-plus
make all
hyprctl plugin load borders-plus-plus.so
```

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/137896711/7ffdc9d5-febf-4566-bc7a-494f658cbca2)

**Comment by vaxerski** [comment]
are you sure you're running the correct hyprland rev? verify with `hyprctl version`. Plugins should also pop up a notification in the case of a rev mismatch.

**Comment by 0xUnixy** [comment]
yes i am sure
![image](https://github.com/hyprwm/Hyprland/assets/137896711/c9b5cbb3-4672-415d-9e1b-e0ca5df5e8f7)

and... no, there is notification. just the error in the screenshot.

**Comment by vaxerski** [comment]
oh, I see it.

```
hyprctl plugin load borders-plus-plus.so
```

this has to be an absolute path. cwd is not passed between hyprctl and hyprland.

**Comment by 0xUnixy** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/137896711/8a7e8d9c-5ff2-415e-abf1-9ae907273e5c)
worked like **charm** , thanks dude >3

**Comment by vaxerski** [comment]
I'll improve the logging a bit in a sec. This is resolved though, so closing :)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/cd7ebaa2-a3dd-4efa-b6a4-795973e0aec4)

a bit better, I think.
