### ISSUE TITLE
Sigabort with the sub-command `setcursors`

### ISSUE THREAD

**Issue by FirelightFlagboy** [hyprwm/Hyprland#3876]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

I wanted to investigate why `hyprland` wasn't using the cursor theme configured in `gsettings`.

By looking to similar issue on the internet, stumble upon this reddit discussion:

> `gsettings set org.gnome.desktop.interface cursor-theme Adwaita` do this, 
> alongside with `hyprctl setcursor`, and `lxappearance`. I made my own ""[script](https://github.com/EuCaue/dotfiles/blob/main/scripts/cursor.fish)"" to do this. 
> If you want to look. :)
> 
> https://www.reddit.com/r/hyprland/comments/zrvp78/comment/j163s5n/?utm_source=share&utm_medium=web2x&context=3

So I've tried the command `hyprctl setcursor`.

### How to reproduce

My current cursor theme is `Nordzy-cursors` (I used the same value returned by `gsettings get org.gnome.desktop.interface cursor-theme` minus the single-quote).

So I used that value in the following command 

```shell
hyprctl setcursor Nordzy-cursors
```

And `hyprland` abort just after (I've tried 2 time and it abort at each).

### Crash reports, logs, images, videos

[hyprlandCrashReport6185.txt](https://github.com/hyprwm/Hyprland/files/13399390/hyprlandCrashReport6185.txt)
[coredump-hyprland-6185.bin.zip](https://github.com/hyprwm/Hyprland/files/13399412/coredump-hyprland-6185.bin.zip)

**Comment by vaxerski** [comment]
you're on a very old version and using the command incorrectly. 

First, update.

Second, you're missing a size:
```
hyprctl setcursor Nordzy-cursors 24
```

**Comment by FirelightFlagboy** [comment]
I've update to `0.32.3` after discovering that the package on archlinux was out-of-date thanks to your comment (now using aur).

With the update, the issue is resolved, it no longer abort so I'll close this issue.
