### ISSUE TITLE
Swipe gesture doesn't respect animation disable

### ISSUE THREAD

**Issue by kdb424** [hyprwm/Hyprland#3878]
### Hyprland Version

483302a2cdc3cc8f4854aecb9cb0ed841babe30c

### Bug or Regression?

Bug

### Description

Swipe animation (trackpad gesture swipe) is not disabled with animations disabled. This appears to be an oversight, or possibly just deemed a requirement as it's a gesture. If so, would a fade out of the current workspace into the new workspace be a sane default? MacOS does this for their motion reduction mode as it can cause users to get motion sickness. On this note, if an animation must happen, the sudden snap at the end is quite jarring, and should likely be given a smooth animation finish instead of a snap when you are past the cancel ratio.

### How to reproduce

Enable gestures, disable animation. Example partial config in nix

```nix
    gestures = {
      workspace_swipe = true;
      workspace_swipe_fingers = 3;
      workspace_swipe_cancel_ratio = 0.01;
      workspace_swipe_distance = 2000;
      workspace_swipe_invert = true;
    };
    animations.enabled = false;
```

**Comment by desssai** [comment]
Issue still present. But for those who want a quick fix:
`
    workspace_swipe_min_speed_to_force = 0
    workspace_swipe_distance = 2
    workspace_swipe_cancel_ratio = 0.01;
`
disables the sliding animation. 

You can also use hyprctl to trigger a swritch workspace (relative to the current one) dispatch on a gesture.

**Comment by vaxerski** [comment]
I mean it makes no sense to disable that. It's a gesture, not an animation. 

Not planning on disabling this. You can disable it yourself.
