### ISSUE TITLE
Certain Games Break After Workspace Switch

### ISSUE THREAD

**Issue by JoshuaFern** [hyprwm/Hyprland#388]
When I'm playing a game on Steam and I switch to another workspace, the game is often completely borked after switching back.

Tested games with this issue: Rocket League, Prey, Idle Spiral (free)
All the games affected seem to be running on Proton, but not all Proton games are affected.

Nvidia 515.57, NixOS

**Comment by NotAShelf** [comment]
define "borked"
graphical issues? crashes? the game kidnaps your family and asks for a ransom?

**Comment by JoshuaFern** [comment]
> define "borked" graphical issues? crashes? the game kidnaps your family and asks for a ransom?

It just kind of freezes/crashes.

**Comment by vaxerski** [comment]
use the wine virtual desktop

**Comment by JoshuaFern** [comment]
I tried the virtual desktop, it appears for a second and then vanishes.

**Comment by JoshuaFern** [comment]
Ah, it's another problem that's exacerbating the issue. 

I've noticed sometimes when I move a game to another workspace it seems to make the game window vanish. I have a window rule `windowrule=workspace 15 silent,steam_app_*` in my config and when the game starts in virtual desktop mode it gets moved and vanishes, however if I quickly switch to that workspace before the game starts it runs fine and the virtual desktop does indeed prevent it from crashing from switching workspaces.

**Comment by fufexan** [comment]
I've also experienced the issue with games vanishing. The thing is, they're not vanishing, just flying to oblivion (-62457 -56535 anyone?). That also happens for spotify when it's in floating mode. So what you can do is go to the workspace it's on and type
`hyprctl dispatcher focuswindow <name>`, then make it tiled to get it back in a sane position.

Also, saw you're using NixOS. I hope you're using the flake.

**Comment by JoshuaFern** [comment]
> I've also experienced the issue with games vanishing. The thing is, they're not vanishing, just flying to oblivion (-62457 -56535 anyone?). That also happens for spotify when it's in floating mode. So what you can do is go to the workspace it's on and type `hyprctl dispatcher focuswindow <name>`, then make it tiled to get it back in a sane position.
I've noticed this happen once with MPV, it seems you're right about this happening with the games as well. Perhaps a windowrule preventing games from floating would help.
> > Also, saw you're using NixOS. I hope you're using the flake.
Indeed I am.

**Comment by vaxerski** [comment]
check with the latest commit.

**Comment by JoshuaFern** [comment]
Seems to be working better with the latest commit and `windowrule=tile,steam_app_*`. I'm not getting vanishing windows anymore and I'm able to move games to other workspaces.

**Comment by vaxerski** [comment]
have you tried the latest commit?

**Comment by JoshuaFern** [comment]
Yep. The original issue of games freezing still happens and while using a WINE virtual desktop is functional, it's more of a workaround and it would be nice if games just worked out of the box.

**Comment by crypticC0der** [comment]
this is still happening
tested with ultrakill and splunkey 2

**Comment by vaxerski** [comment]
What happens? Can I get a video of this happening?

**Comment by crypticC0der** [comment]
its sorta hard to video
basically, if not focused on start it turns into a black window and refuses to load
if you move your focus away from the game to another window, when you refocus the game it goes into the black window state mentioned above

**Comment by vaxerski** [comment]
wot de foq

**Comment by vaxerski** [comment]
Narrowed it down to DXVK requesting a `minimize` whenever the game goes out of focus. Additionally, it seems, as usual, that due to the shitton of band-aids X11 has received, that I have no fucking idea what is happening there and after 2h of trying to battle it out with the stupid legacy protocol, I was unable to find a solution.

The window *refuses* to come back, despite being asked to.

in the meantime, ofc, wine virtual desktop / gamescope fix this issue

**Comment by vaxerski** [comment]
follow this issue over at https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3520

**Comment by vaxerski** [comment]
should be fixed with 206360177fcae23436928542ed860c854b985db4 please verify

**Comment by vaxerski** [comment]
@0x4nt @JoshuaFern @crypticC0der ping

**Comment by crypticC0der** [comment]
its fixed, great job
hyprland is coming along very well
