### ISSUE TITLE
Hyprland freezes with CPU usage 100%

### ISSUE THREAD

**Issue by anarrak** [hyprwm/Hyprland#3880]
### Hyprland Version

Hyprland, built from branch main at commit 483302a2cdc3cc8f4854aecb9cb0ed841babe30c dirty (aur hyprland-git) AND Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (aur hyprland)

### Bug or Regression?

Bug

### Description

When I launch the hyprland with default config, the black screen appears. But cpu usage is ~100% and nothing works. When I'm trying to kill it (except SIGKILL) or use the Ctrl+C, it just doesn't work. My distribution is archlinux and I've tried several aur versions - hyprland and hyprland-git, but both have the same problem. I had installed the wm half a year ago and everything was working fine. When I launch it through tty the last thing that is being displayed is "Assigning super to mod key" or something similar. After that, the tty stops responding. Everything is fine when I launch the Hyprland from i3wm.

P.S It looks like I figured out why the CPU usage is so high. The last line in the log file is repeated more than 80,000 times! So the problem is in "Couldn't attach render to display eDP-1 ???" line

### How to reproduce

🤷

### Crash reports, logs, images, videos

File: /tmp/hypr/1b48642fd15c433c53876f1b933dcd46265caf8f_1700299344/hyprland.log
[LOG] Instance Signature:1b48642fd15c433c53876f1b933dcd46265caf8f_1700299344
[LOG] Hyprland PID:1553
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: DESKTOP-FI1T13T
[LOG] Release: 6.6.1-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000

[LOG] GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c2) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://2wiki.hyprland.org2/Crashes-and-Bugs/

[LOG] 
Current splash: Say no way, say no way ya, no way!

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked255 points, mem usage: 4.08kB, time to bake: 47.11µs. Estimated average calc time: 0.10µs.
[LOG] Creating the ConfigManager!
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked255 points, mem usage: 4.08kB, time to bake:20.61µs. Estimated average calc time: 0.06µs.
[LOG] Using config: /home/andreno/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked255 points, mem usage: 4.08kB, time to bake:20.45µs. Estimated average calc time: 0.07µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the ThreadManager!
[LOG] Hypr socket started at /tmp/hypr/1b48642fd15c433c53876f1b933dcd46265caf8f_1700299344/.socket.sock
[LOG] Creating the InputManager!
[LOG] [hookSystem] New hook event registered: keyboardFocus
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Creating the Hypr OpenGL Renderer!
[LOG] Using: OpenGL ES 3.2 Mesa23.2.1-arch1.2
[LOG] Vendor: AMD
[LOG] Renderer: AMD Radeon Graphics (renoir, LLVM16.0.6, DRM 3.54, 6.6.1-arch1-1)
[LOG] Supported extensions size:150
[LOG] Creating the HyprRenderer!
[LOG] Creating the XWaylandManager!
[LOG] Registered signal for owner 563eff11fa10: 563eff11fa50 -> 563efcf640a0 (owner: XWayland Manager)
[LOG] Registered signal for owner 563eff11fa10: 563eff11fa60 -> 563efcf64080 (owner: XWayland Manager)
[LOG] CHyprXWaylandManager started on display :1
[LOG] Creating the ProtocolManager!
[LOG] ToplevelExportManager started successfully!
[LOG] FractionalScaleManager started successfully!
[LOG] TextInputV1Manager started successfully!
[LOG] GlobalShortcutsManager started successfully!
[LOG] ScreencopyProtocolManager started successfully!
[LOG] [proto XDGOutput] started
[LOG] [hookSystem] New hook event registered: monitorLayoutChanged
[LOG] [hookSystem] New hook event registered: monitorRemoved
[LOG] Creating the SessionLockManager!
[LOG] Creating the EventManager!
[LOG] Creating the HyprDebugOverlay!
[LOG] Creating the HyprNotificationOverlay!
[LOG] Hypr socket2 started at /tmp/hypr/1b48642fd15c433c53876f1b933dcd46265caf8f_1700299344/.socket2.sock
[LOG] Creating the PluginSystem!
[WARN] Failed to change process scheduling strategy
[LOG] Hyprland init finished.
[LOG] Registered signal for owner 563efe718fa0: 563efe718fc8 -> 563efcf5c5c0 (owner: Backend)
[LOG] Registered signal for owner 563eff06d7b0: 563eff06d800 -> 563efcf5c5a0 (owner: XDG Shell)
[LOG] Registered signal for owner 563eff06d880: 563eff06d898 -> 563efcf5c580 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d8a8 -> 563efcf5c560 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d8b8 -> 563efcf5c540 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d8c8 -> 563efcf5c520 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d8d8 -> 563efcf5c500 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d8e8 -> 563efcf5c4e0 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d8f8 -> 563efcf5c4c0 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d908 -> 563efcf5c4a0 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d918 -> 563efcf5c480 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d928 -> 563efcf5c460 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d938 -> 563efcf5c440 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d978 -> 563efcf5c420 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d968 -> 563efcf5c400 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d988 -> 563efcf5c3e0 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d9a8 -> 563efcf5c3c0 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d948 -> 563efcf5c3a0 (owner: WLRCursor)
[LOG] Registered signal for owner 563eff06d880: 563eff06d958 -> 563efcf5c380 (owner: WLRCursor)
[LOG] Registered signal for owner 563efe718fa0: 563efe718fb8 -> 563efcf5c360 (owner: Backend)
[LOG] Registered signal for owner 563efe706f00: 563eff12e7f8 -> 563efcf5c340 (owner: Seat)
[LOG] Registered signal for owner 563efe706f00: 563eff12e808 -> 563efcf5c320 (owner: Seat)
[LOG] Registered signal for owner 563efe706f00: 563eff12e848 -> 563efcf5c300 (owner: Seat)
[LOG] Registered signal for owner 563efe706f00: 563eff12e858 -> 563efcf5c2e0 (owner: Seat)
[LOG] Registered signal for owner 563efe706f00: 563eff12e808 -> 563efcf5c320 (owner: Seat)
[LOG] Registered signal for owner 563efe706f00: 563eff12e828 -> 563efcf5c2c0 (owner: Seat)
[LOG] Registered signal for owner 563eff12fc80: 563eff12fca0 -> 563efcf5c2a0 (owner: LayerShell)
[LOG] Registered signal for owner 563eff06d6b0: 563eff06d6d0 -> 563efcf5c280 (owner: OutputLayout)
[LOG] Registered signal for owner 563eff12fea0: 563eff12fed8 -> 563efcf5c260 (owner: OutputMgr)
[LOG] Registered signal for owner 563eff12fea0: 563eff12fee8 -> 563efcf5c240 (owner: OutputMgr)
[LOG] Registered signal for owner 563eff12ff80: 563eff12ffb0 -> 563efcf5c220 (owner: InhibitMgr)
[LOG] Registered signal for owner 563eff12ff80: 563eff12ffc0 -> 563efcf5c200 (owner: InhibitMgr)
[LOG] Registered signal for owner 563eff1300f0: 563eff130108 -> 563efcf5c1e0 (owner: PointerConstraints)
[LOG] Registered signal for owner 563eff12fdf0: 563eff12fe20 -> 563efcf5c1c0 (owner: XDGDecoMgr)
[LOG] Registered signal for owner 563eff131510: 563eff131540 -> 563efcf5c1a0 (owner: VirtPtrMgr)
[LOG] Registered signal for owner 563eff131460: 563eff131490 -> 563efcf5c180 (owner: VKeyboardMgr)
[LOG] Registered signal for owner 563efe907d60: 563efe907d60 -> 563efcf5c160 (owner: WLRRenderer)
[LOG] Registered signal for owner 563eff132ae0: 563eff132b10 -> 563efcf5c140 (owner: WLRIdleInhibitMgr)
[LOG] Registered signal for owner 563eff06d700: 563eff06d730 -> 563efcf5c120 (owner: PowerMgr)
[LOG] Registered signal for owner 563eff132f60: 563eff132f90 -> 563efcf5c100 (owner: IMEMgr)
[LOG] Registered signal for owner 563eff132eb0: 563eff132ee0 -> 563efcf5c0e0 (owner: TextInputMgr)
[LOG] Registered signal for owner 563eff134240: 563eff134268 -> 563efcf5c0c0 (owner: ActivationV1)
[LOG] Registered signal for owner 563eff134390: 563eff134398 -> 563efcf5c0a0 (owner: SessionLockMgr)
[LOG] Registered signal for owner 563eff06d600: 563eff06d640 -> 563efcf5c080 (owner: GammaCtrlMgr)
[LOG] Registered signal for owner 563eff134430: 563eff134438 -> 563efcf5c060 (owner: CursorShapeMgr)
[LOG] Registered signal for owner 563efe706c60: 563eff1316b0 -> 563efcf5c040 (owner: DRM)
[LOG] Registered signal for owner 563efe719030: 563efe719190 -> 563efcf5c020 (owner: Session)
[LOG] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Running on WAYLAND_DISPLAY: wayland-1
[LOG] Attached a keyboard with name Video Bus
[LOG] Registered signal for owner 563eff186bf0: 563eff198e60 -> 563eff186bf8 (owner: Keyboard)
[LOG] Registered signal for owner 563eff186bf0: 563eff198e50 -> 563eff186c60 (owner: Keyboard)
[LOG] Registered signal for owner 563eff186bf0: 563eff198d30 -> 563eff186d30 (owner: Keyboard)
[LOG] Registered signal for owner 563eff186bf0: 563eff198e70 -> 563eff186cc8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] [hookSystem] New hook event registered: activeLayout
[LOG] Set the keyboard layout to us and variant tofor keyboard "Video Bus"
[LOG] New keyboard created, pointers Hypr: 563eff186bf0 and WLR: 563eff198d18
[LOG] Attached a keyboard with name Power Button
[LOG] Registered signal for owner 563eff0d2d70: 563eff1e03c0 -> 563eff0d2d78 (owner: Keyboard)
[LOG] Registered signal for owner 563eff0d2d70: 563eff1e03b0 -> 563eff0d2de0 (owner: Keyboard)
[LOG] Registered signal for owner 563eff0d2d70: 563eff1e0290 -> 563eff0d2eb0 (owner: Keyboard)
[LOG] Registered signal for owner 563eff0d2d70: 563eff1e03d0 -> 563eff0d2e48 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Power Button"
[LOG] New keyboard created, pointers Hypr: 563eff0d2d70 and WLR: 563eff1e0278
[LOG] Attached a switch device with name Lid Switch
[LOG] New switch with name "Lid Switch" added
[LOG] Registered signal for owner 563eff13c190: 563eff24bf98 -> 563eff13c1a0 (owner: SwitchDevice)
[LOG] Registered signal for owner 563eff13c190: 563eff24bfb8 -> 563eff13c208 (owner: SwitchDevice)
[LOG] Attached a mouse with name Logitech G102 Prodigy Gaming Mouse
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile2 (2)
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse, sens 0.00
[LOG] Registered signal for owner 563eff1a8240: 563eff231080 -> 563eff1a8300 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 563eff231068
[LOG] Attached a keyboard with name Logitech G102 Prodigy Gaming Mouse Keyboard
[LOG] Registered signal for owner 563eff1f8210: 563eff231560 -> 563eff1f8218 (owner: Keyboard)
[LOG] Registered signal for owner 563eff1f8210: 563eff231550 -> 563eff1f8280 (owner: Keyboard)
[LOG] Registered signal for owner 563eff1f8210: 563eff231430 -> 563eff1f8350 (owner: Keyboard)
[LOG] Registered signal for owner 563eff1f8210: 563eff231570 -> 563eff1f82e8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "logitech-g102-prodigy-gaming-mouse-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Logitech G102 Prodigy Gaming Mouse Keyboard"
[LOG] New keyboard created, pointers Hypr: 563eff1f8210 and WLR: 563eff231418
[LOG] Attached a mouse with name Logitech G102 Prodigy Gaming Mouse Keyboard
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile 0 (0)
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse, sens 0.00
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse-keyboard-1, sens 0.00
[LOG] Registered signal for owner 563efe707000: 563eff2315b0 -> 563efe7070c0 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 563eff231598
[LOG] Attached a mouse with name GXTP7863:0027C6:01E0 Mouse
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile2 (2)
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse, sens 0.00
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse-keyboard-1, sens 0.00
[LOG] Applied config to mouse gxtp7863:00-27c6:01e0-mouse, sens 0.00
[LOG] Registered signal for owner 563eff098010: 563eff2889a0 -> 563eff0980d0 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 563eff288988
[LOG] Attached a mouse with name GXTP7863:0027C6:01E0 Touchpad
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile2 (2)
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse, sens 0.00
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse-keyboard-1, sens 0.00
[LOG] Applied config to mouse gxtp7863:00-27c6:01e0-mouse, sens 0.00
[LOG] Applied config to mouse gxtp7863:00-27c6:01e0-touchpad, sens 0.00
[LOG] Registered signal for owner 563eff27af50: 563eff2747d0 -> 563eff27b010 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 563eff2747b8
[LOG] Attached a keyboard with name Huawei WMI hotkeys
[LOG] Registered signal for owner 563eff275310: 563eff274f20 -> 563eff275318 (owner: Keyboard)
[LOG] Registered signal for owner 563eff275310: 563eff274f10 -> 563eff275380 (owner: Keyboard)
[LOG] Registered signal for owner 563eff275310: 563eff274df0 -> 563eff275450 (owner: Keyboard)
[LOG] Registered signal for owner 563eff275310: 563eff274f30 -> 563eff2753e8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "huawei-wmi-hotkeys", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Huawei WMI hotkeys"
[LOG] New keyboard created, pointers Hypr: 563eff275310 and WLR: 563eff274dd8
[LOG] Attached a keyboard with name AT Translated Set2 keyboard
[LOG] Registered signal for owner 563eff2c5ac0: 563eff2c56d0 -> 563eff2c5ac8 (owner: Keyboard)
[LOG] Registered signal for owner 563eff2c5ac0: 563eff2c56c0 -> 563eff2c5b30 (owner: Keyboard)
[LOG] Registered signal for owner 563eff2c5ac0: 563eff2c55a0 -> 563eff2c5c00 (owner: Keyboard)
[LOG] Registered signal for owner 563eff2c5ac0: 563eff2c56e0 -> 563eff2c5b98 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "AT Translated Set2 keyboard"
[LOG] New keyboard created, pointers Hypr: 563eff2c5ac0 and WLR: 563eff2c5588
[LOG] Registered signal for owner 563eff2ee1e0: 563eff300660 -> 563eff2ee4d0 (owner: )
[LOG] Registered signal for owner 563eff2ee1e0: 563eff3006f0 -> 563eff2ee538 (owner: )
[LOG] Registered signal for owner 563eff2ee1e0: 563eff3006e0 -> 563eff2ee5a0 (owner: )
[LOG] Registered signal for owner 563eff2ee1e0: 563eff300670 -> 563eff2ee608 (owner: )
[LOG] Registered signal for owner 563eff2ee1e0: 563eff300680 -> 563eff2ee670 (owner: )
[LOG] Registered signal for owner 563eff2ee1e0: 563eff3006a0 -> 563eff2ee6d8 (owner: )
[LOG] Registered signal for owner 563eff2ee1e0: 563eff3006c0 -> 563eff2ee740 (owner: )
[WARN] No rule found for eDP-1, trying to use the first.
[LOG] Applying monitor rule for eDP-1
[LOG] Setting preferred mode for eDP-1
[ERR] output eDP-1 failed basic test on format DRM_FORMAT_XRGB8888
[ERR] output eDP-1 failed basic test on format DRM_FORMAT_XBGR8888
[ERR] output eDP-1 failed basic test on format DRM_FORMAT_INVALID
[ERR] Couldn't commit output named eDP-1
[LOG] Monitor eDP-1 -> destroyed all render data
[LOG] arrangeMonitors:1 to arrange
[LOG] arrangeMonitors: eDP-1 auto [0, 0.00]
[LOG] arrangeMonitors: eDP-1 xwayland [0, 0.00]
[LOG] Monitor eDP-1 layers arranged: reserved: [0.00000, 0.00000] [0.00000, 0.00000]
[LOG] Monitor eDP-1 data dump: res1920x1080@60.00Hz, scale1.00, transform 0, pos 0x0,10b 0
[LOG] Added new monitor with name eDP-1 at [0, 0] with size [1920,1080], pointer 563eff300510
[LOG] New monitor: WORKSPACEID1, exists: 0
[LOG] [hookSystem] New hook event registered: createWorkspace
[LOG] [hookSystem] New hook event registered: monitorAdded
[LOG] Monitor eDP-1 layers arranged: reserved: [0.00000, 0.00000] [0.00000, 0.00000]
[LOG] Hyprland is ready, running the event loop!
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && hash dbus-update-activation-environment2>/dev/null && dbus-update-
ivation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
[LOG] Process Created with pid1589
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 alacritty
[LOG] Process Created with pid1592
[LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Video Bus"
[LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Power Button"
[LOG] ApplyConfigToKeyboard for "logitech-g102-prodigy-gaming-mouse-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Logitech G102 Prodigy Gaming Mouse Keyboard"
[LOG] ApplyConfigToKeyboard for "huawei-wmi-hotkeys", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "Huawei WMI hotkeys"
[LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant(rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant tofor keyboard "AT Translated Set2 keyboard"
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse, sens 0.00
[LOG] Applied config to mouse logitech-g102-prodigy-gaming-mouse-keyboard-1, sens 0.00
[LOG] Applied config to mouse gxtp7863:00-27c6:01e0-mouse, sens 0.00
[LOG] Applied config to mouse gxtp7863:00-27c6:01e0-touchpad, sens 0.00
[WARN] No rule found for eDP-1, trying to use the first.
[LOG] Applying monitor rule for eDP-1
[LOG] Setting preferred mode for eDP-1
[ERR] output eDP-1 failed basic test on format DRM_FORMAT_XRGB8888
[ERR] output eDP-1 failed basic test on format DRM_FORMAT_XBGR8888
[ERR] output eDP-1 failed basic test on format DRM_FORMAT_INVALID
[ERR] Couldn't commit output named eDP-1
[LOG] Monitor eDP-1 -> destroyed all render data
[LOG] arrangeMonitors:1 to arrange
[LOG] arrangeMonitors: eDP-1 auto [0, 0.00]
[LOG] arrangeMonitors: eDP-1 xwayland [0, 0.00]
[LOG] Monitor eDP-1 layers arranged: reserved: [0.00000, 0.00000] [0.00000, 0.00000]
[LOG] Monitor eDP-1 data dump: res1920x1080@60.00Hz, scale1.50, transform 0, pos 0x0,10b 0
[LOG] Monitor eDP-1 layers arranged: reserved: [0.00000, 0.00000] [0.00000, 0.00000]
[LOG] [hookSystem] New hook event registered: render
[ERR] Couldn't attach render to display eDP-1 ???
[ERR] Couldn't attach render to display eDP-1 ???
[ERR] Couldn't attach render to display eDP-1 ???
[ERR] Couldn't attach render to display eDP-1 ??? // < ---- This line will be repeated 80000 times! Seems like that's the cause of high cpu usage

**Comment by vaxerski** [comment]
> ```
> [ERR] output eDP-1 failed basic test on format DRM_FORMAT_XRGB8888
> [ERR] output eDP-1 failed basic test on format DRM_FORMAT_XBGR8888
> [ERR] output eDP-1 failed basic test on format DRM_FORMAT_INVALID
> ```

Your monitor rejects all valid pixel formats, this is not a problem with hyprland, but most likely with your display / driver.

Have you tested sway-git?

**Comment by anarrak** [comment]
> > ```
> > [ERR] output eDP-1 failed basic test on format DRM_FORMAT_XRGB8888
> > [ERR] output eDP-1 failed basic test on format DRM_FORMAT_XBGR8888
> > [ERR] output eDP-1 failed basic test on format DRM_FORMAT_INVALID
> > ```
> 
> Your monitor rejects all valid pixel formats, this is not a problem with hyprland, but most likely with your display / driver.
> 
> Have you tested sway-git?

Sway worked after the second time, and XDG_SESSION_TYPE was equal to wayland.

**Comment by vaxerski** [comment]
> after the second time

?

**Comment by anarrak** [comment]
> > after the second time
> 
> ?

The first attempt was the same as with hyprland (only there was no bug with logs). But when I killed it and started again, everything was fine.

**Comment by anarrak** [comment]
The problem was in lightdm. Removing it and installing sddm instead fixed the problem. Although the bug with endless recording of errors in the config file is still present.
