### ISSUE TITLE
Gaps between windows disappear if gaps_in is set to a decimal number

### ISSUE THREAD

**Issue by retchohrips** [hyprwm/Hyprland#3881]
### Hyprland Version

Hyprland, built from branch main at commit 483302a2cdc3cc8f4854aecb9cb0ed841babe30c dirty (env: add HYPRLAND_NO_RT). Tag: v0.32.3-33-g483302a2  flags: (if any) debug

### Bug or Regression?

Bug

### Description

gaps_in does not work if set to a decimal number like 2.5, whole numbers work fine.

### How to reproduce

Set gaps_in in config to a decimal number. Gaps between windows are now gone.

**Comment by MightyPlaza** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/123664421/4316a9cc-e37a-4025-a39a-7670efe58088)

**Comment by retchohrips** [comment]
It did work in the last version, though.

**Comment by Dickby** [comment]
And 'decimal' is not what you mean

**Comment by vaxerski** [comment]
expected behavior. Recently type safety around some internal stuff was hardened. 2.5 is not a valid int.
