### ISSUE TITLE
Broken window decoration drawing when switching to a workspace with a floating window in it

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#3882]
### Hyprland Version

Hyprland, built from branch main at commit 483302a2cdc3cc8f4854aecb9cb0ed841babe30c dirty (env: add HYPRLAND_NO_RT). Tag: v0.32.3-33-g483302a2  flags: (if any) debug

### Bug or Regression?

Regression

### Description

When switching to a workspace with a floating window inside of it, the window decorations are partially not rendered and a weird gray rectangle appears instead of part of the windows.

https://github.com/hyprwm/Hyprland/assets/84153269/a04234a4-e9e8-40a9-8dcc-3934c72bd550

### How to reproduce

Place a floating window in a workspace.

Switch to another one

Go back to the first workspace.

This also happens when using the swipe gesture but not completing it (the remaining animations shows the issue.

**Comment by alba4k** [comment]
The black rectangle doesn't seem to appear anymore, but the window appearing at the wrong location still does

**Comment by vaxerski** [comment]
should be fixed by 8b57a1973ea8b242783069e9a3e3d31e3cd939a8 lmk

**Comment by alba4k** [comment]
Yes, thanks :)

**Comment by thejch** [comment]
Not fixed for me

**Comment by alba4k** [comment]
What version are you running?

**Comment by thejch** [comment]
> What version are you running?

latest git commit. maybe it's not the exact same issue but the floating window gets cut when switching workspaces. the issue seems to only happen when scale > 1

**Comment by alba4k** [comment]
maybe send a video? I am using scaling 1

**Comment by thejch** [comment]
I have another issue open.
https://github.com/hyprwm/Hyprland/issues/3875
Since it doesn't look like the same issue, I'll probabaly add the video there later
