### ISSUE TITLE
Refresh rate issue

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#3886]
### Hyprland Version

Hyprland, built from branch main at commit 483302a2cdc3cc8f4854aecb9cb0ed841babe30c dirty (env: add HYPRLAND_NO_RT). Tag: v0.32.3-33-g483302a

### Bug or Regression?

Bug

### Description

Dual monitor setup, 
DP-1 = 75hz
DP-2 = 144hz
when I start CS 2 in DP-2, the game only sticks with 75hz then I need to disable DP-1 to start cs and get 144hz

### How to reproduce

start cs 2 in a dual monitor setup which both having distinct virtual sync

**Comment by vaxerski** [comment]
wouldnt that be an xwayland issue solvable by selecting a primary monitor with xrandr?

**Comment by killown** [comment]
Thank you,  solved with xrandr --output DP-2 --primary --left-of DP-1
