### ISSUE TITLE
Transparency difference on special workspace

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#3888]
### Hyprland Version

Hyprland, built from branch makepkg at commit 8b57a1973ea8b242783069e9a3e3d31e3cd939a8 dirty (internal: Allow floating windows on special (3872)). Tag: v0.32.3-34-g8b57a197

### Bug or Regression?

Bug

### Description

Semi-Transparent windows are less transparent if they are in a special workspace.

### How to reproduce

Well, open a semitransparent window on a non-special, memorize how transparent it is, and then move it to a special workspace and compare

**Comment by vaxerski** [comment]
isnt that just the default dim around special?

**Comment by Dickby** [comment]
No, happens without

**Comment by Dickby** [comment]
@vaxerski: This is not fully fixed.
Some observations:
1. If a fullscreen window is behind the special workspace, the problem is not there.
2. The problem is gone after switching workspaces with active special workspace 
3. new windows on a special workspace will have that problem even after 2.

**Comment by Dickby** [comment]
While the special workspace is 'sliding in' the transparency and shadow strength is wrong, after the animation ends it's right.

**Comment by vaxerski** [comment]
my bad

**Comment by vaxerski** [comment]
check with above

**Comment by Dickby** [comment]
Seems like it's fixed, but i'm not totally shure.
I never looked at the responsible code before, having done that now, it's quite complicated and inefficient.
Why not having a render order system, like 3 different lists/vectors for the different 'layers'. Those lists get drawn in order.
So promoting a window to be on top of it's layer would be just to move it to the beginning of the list. 
Every time a window is e.g. made floating, the a window is moved from the tiled-list to the floating-list and so on.
That way we don't check for all those flags every frame, and changes to the render order are no big thing. 
The way it is right now, it's really confusing to read, and your struggle to get the special workspace to just render once, shows that it's not totally clear for you either.
I'm not talking about reorganizing the windows in a ws really, but just to have some lists that hold pointers to the windows in the workspace.

After the last change, floating windows on a regular workspace will be on top of special workspaces again.

**Comment by Dickby** [comment]
When opening an empty special workspace, and opening a transparent window in it. 
After that, slide the special workspace off screen. 
Now if you slide it in again, while the animation the special workspace is clearly rendered more than once.
After the animation it seems to be fine.

**Comment by vaxerski** [comment]
it is complicated, but it isn't inefficient, all things considered. If you don't use xwayland there really aren't enough windows to make any difference. We should move unmapped xwayland off of m_vWindows, but that's a todo.

**Comment by vaxerski** [comment]
I'll try to put all those three issues to rest tomorrow, after I am done with #3920

**Comment by thejch** [comment]
It seems that transparency in special stopped working again? When i have one tiled window in special there's no transparency at all as far as I can tell

**Comment by phonetic112** [comment]
I also have no transparency in special, kitty is just black background

**Comment by vaxerski** [comment]
my bad adeb20ea114ff56d78804697e9ba8328f684b7b1

**Comment by phonetic112** [comment]
Thanks

**Comment by Dickby** [comment]
@vaxerski there is one hopefully last edge case where this happens, and that is if a special workspace is activated while another special workspace is active. During the slide animation, the newly activated special workspace is rendered more than once.
