### ISSUE TITLE
Special workspace not visible during workspace switching

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#3889]
### Hyprland Version

Hyprland, built from branch makepkg at commit 8b57a1973ea8b242783069e9a3e3d31e3cd939a8 dirty (internal: Allow floating windows on special (3872)). Tag: v0.32.3-34-g8b57a197

### Bug or Regression?

Bug

### Description

Switching workspaces when a special workspace is visible, causes that special ws to hidden behind the windows on the non-special new workspace until the switching is finished.
Also, In my opinion switching a workspace with a visible special workspace should either keep the special focused (i would prefer that), or hide the special one.
The way it is now after switching the special is still visible but not focused, i think that is not usefull at all, and a state that can't be reached in other ways.

### How to reproduce

See description

**Comment by Lillecarl** [comment]
confirmed 572fd554b8e86b3b3533f05631348c3374815ab5

It's especially entertaining when you have a window rule to fade in the windows 😸

**Comment by Dickby** [comment]
@vaxerski after the last change, this issue is back too!

**Comment by Dickby** [comment]
This seems to be fixed!
Thanks
