### ISSUE TITLE
Crash on Install

### ISSUE THREAD

**Issue by Jumima67** [hyprwm/Hyprland#3892]
### Hyprland Version

idk

### Bug or Regression?

Bug

### Description

If I try to run the last command "sudo make install", I get the error 

cmake --build ./build --config Release --target all -j16
[0/2] Re-checking globbed directories...
ninja: error: '../subprojects/wlroots/build/libwlroots.so.12032', needed by 'Hyprland', missing and no known rule to make it
make: *** [Makefile:156: legacyrenderer] Error 1

### How to reproduce

Probably a me issue

### Crash reports, logs, images, videos

Would appreciate some help!

**Comment by MightyPlaza** [comment]
1- that's not a crash
2- you have to `git clone --recursive https://github.com/hyprwm/Hyprland`
https://wiki.hyprland.org/Getting-Started/Installation/

**Comment by Jumima67** [comment]
Then I get this error:


CMake Error at CMakeLists.txt:115 (add_executable):
  Cannot find source file:

    protocols/cursor-shape-v1-protocol.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

**Comment by MightyPlaza** [comment]
what distro?

**Comment by Jumima67** [comment]
I will try that

**Comment by romanstingler** [comment]
is this resolved for you ??
