### ISSUE TITLE
Failed to set kb_layout=fr-bepo

### ISSUE THREAD

**Issue by alexandrenavarro** [hyprwm/Hyprland#3894]
### Hyprland Version

0.30.0

### Bug or Regression?

Bug

### Description

Failed to set kb_layout=fr-bepo

I don't know if it is linked but it is available in localectl list-keymaps but not in /usr/share/X11/xkb/rules/base.lst

### How to reproduce

Just set in config
kb_layout=fr-bepo

**Comment by MightyPlaza** [comment]
layout = fr
variant = bepo

**Comment by alexandrenavarro** [comment]
Thank you
