### ISSUE TITLE
fcitx5 can't awaken when open two foot terminal

### ISSUE THREAD

**Issue by yadex** [hyprwm/Hyprland#3896]
### Hyprland Version

0.30

### Bug or Regression?

Bug

### Description

I open two foot terminal, but the second terminal can't use fcitx any more.Only if i change focus,then back to the second terminal it can works. 

### How to reproduce

1. use default hyprland config
2. set monitor scale to 1
3. open two foot terminal
4. fcitx5 can't be awakened in the second terminal

**Comment by yadex** [comment]
I test alacritty, it has similar issue,but not the same.If i open two alacritty,then close one,then the left can't use fcitx5.

**Comment by vaxerski** [comment]
very old hyprland version, can you test on git?

**Comment by yuWorm** [comment]
hyprland: 0.33.1-2
termiterminal: alacritty

I'm having the same problem, and it seems that it's not just the terminal program, but all programs running on wayland!

https://github.com/hyprwm/Hyprland/assets/34805071/3f618d0f-afff-4202-a713-5b8edd9a7a9b

**Comment by go0d1uck** [comment]
hyprland: 0.34.0-51-gc4365f20
terminal: alacritty

same problem,not only alacritty.

https://github.com/hyprwm/Hyprland/assets/15233200/fe1b8edf-2f13-4a55-b5b7-18a600988b77

**Comment by sungyoonc** [comment]
Can you check latest git?
