### ISSUE TITLE
direct scanout on invisible workspaces

### ISSUE THREAD

**Issue by focus64** [hyprwm/Hyprland#3899]
### Description

I enable direct scanout (misc:no_direct_scanout=false) to improve battery life when playing videos with mpv in fullscreen. This works well for me. But direct scanout is stopped when I switch to other workspaces, as shown in Hyprland log and intel_gpu_top, and my battery drains noticeably faster.

Is it possible to keep scanout on for the fullscreened mpv when it is invisible? Or, more generally, is it possible to inhibit some rendering activities for the fullscreened mpv in this case?

**Comment by vaxerski** [comment]
direct scanout can only work when there is a single surface visible on screen.

**Comment by focus64** [comment]
A bit letdown, but understandable.

Regardless of direct scanout, I have the following observation.

When mpv is moved to an off-screen workspace while still playing, either fullscreened or not, Sway (Gnome as well) stops its render activity, (intel_gpu_top shows 'Render/3D' load is down to almost zero), but Hyprland still keeps render work load (not much different from when mpv is visible).

So I guess there might be some room for optimization in this case.

Thanks for creating Hyprland.
