### ISSUE TITLE
Chromium based Browsers flickering on XPS 13 (9310) with Intel iGPU

### ISSUE THREAD

**Issue by tsndr** [hyprwm/Hyprland#3900]
### Hyprland Version

v0.30.0 and v0.32.3-40-g646f4bc6

### Bug or Regression?

Bug

### Description

I wanted to try out Hyprland on my XPS 13 (9310), but whenever I start a Chromium based browser it starts flickering (see video).

My search attempts only lead me to NVIDIA related issues, whereas my Laptop only has Intel integrated graphics.

I've tested both Arch packages available to me, `hyprland` (`v0.30.0`) and `hyprland-git` (`v0.32.3-40-g646f4bc6`). For browsers I've tested `brave` and `chromium`, both behave exactly as seen in the video below. I've also tested `gnome` and `sway` on the same machine, without any issues.

Please let me know what further information I can provide to help getting to the bottom of this.

### How to reproduce

I don't know how anyone could reproduce this. It's happening to me on Arch with a freshly installed Hyprland, even without any configuration applied.

### Crash reports, logs, images, videos

[![Hyprland Chromium Flickering](https://i.ytimg.com/vi/jGQKb4P5dA8/maxresdefault.jpg)](https://youtu.be/jGQKb4P5dA8)
https://youtu.be/jGQKb4P5dA8

**Comment by vaxerski** [comment]
is the browser running in native wayland mode?

**Comment by tsndr** [comment]
Yes, these are my `~/.config/brave-flags.conf`

```
--enable-features=TouchpadOverscrollHistoryNavigation,WebRTCPipeWireCapturer
--ozone-platform=wayland
--disable-features=WaylandFractionalScaleV1
```

**Comment by vaxerski** [comment]
have you verified they apply with `hyprctl clients`?

**Comment by vaxerski** [comment]
can repro. Fixable by removing `--disable-features=WaylandFractionalScaleV1`. Why is that even there?

**Comment by tsndr** [comment]
You're right, removing `--disable-features=WaylandFractionalScaleV1` fixes it, but introduces another problem:

![IMG_0886](https://github.com/hyprwm/Hyprland/assets/2940127/097438a1-1dcb-42e8-855f-deaaa58f37f8)

**Comment by vaxerski** [comment]
nudge the window

**Comment by tsndr** [comment]
Thanks, I had to fullscreen and unfullscreen again, but it seems to happen everytime I start my browser. Is there a setting I have to change somewhere?

**Comment by vaxerski** [comment]
no, it's a chromium bug

**Comment by tsndr** [comment]
Alright, thank you so much for your help with this :)
