### ISSUE TITLE
Ignore reposition requests

### ISSUE THREAD

**Issue by BlanXyz** [hyprwm/Hyprland#3905]
### Description

It would be great to have an option to ignore window reposition requests, to fix [misbehaving](https://github.com/floating/frame/issues/1453#issuecomment-1819276210) applications. Frame is the only app I know that I has this problem, but it makes sense that there would be others. Be it bug or opinionated devs. Just ignoring it would not be that efficient because the window would still keep polling, so perhaps lying to the application about its position would be the best approach.

**Comment by vaxerski** [comment]
not possible due to how x works
