### ISSUE TITLE
[Special Workspace]: Windows sent to special workspace still visible on the monitor worspaces

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#3908]
### Hyprland Version

Hyprland, built from branch main at commit 646f4bc63861e03b01fed3833bb65d1d014e1bf3 dirty (general: add workspace gaps (3877)). Tag: v0.32.3-40-g646f4bc6  flags: (if any) debug

### Bug or Regression?

Bug

### Description

special workspace windows are sometime visible to every workspace of the monitor.
the window is non focusable.

### How to reproduce

move window to special workspace and remove and readd monitor

now the special workspace window is visible to every worspace of the monitor.

**Comment by MightyPlaza** [comment]
is this still happening?
