### ISSUE TITLE
Steam menus disappear after mouse movement

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#3910]
### Hyprland Version

Hyprland, built from branch main at commit 572fd554b8e86b3b3533f05631348c3374815ab5 dirty (renderer: Fix floating clipbox (3907)). Tag: v0.32.3-43-g572fd554

### Bug or Regression?

Bug

### Description

Steam menus disappearing after mouse movement, quick fix is using big picture but I would like to use normal steam window, any plans to fix that?

### How to reproduce

trying steam menus

**Comment by vaxerski** [comment]
I believe it's tracked at #2661

FYI the top steam menus can be interacted with, you just have to click at the very bottom of the button and then move the mouse down.

**Comment by phonetic112** [comment]
try adding the `stayfocused` window rule to steam, this fixed it for me

**Comment by haasn** [comment]
> ~try adding the `stayfocused` window rule to steam, this fixed it for me~
> 
> actually try this:
> 
> ```
> windowrulev2 = stayfocused, title:^()$,class:^(steam)$
> ```
> 
> this works but might break some stuff lol

After adding this, interacting with the steam toolbar froze my system completely (requiring hard reboo)t

**Comment by pamo22** [comment]
> After adding this, interacting with the steam toolbar froze my system completely (requiring hard reboo)t

Same here, beware with this fix. One time it just crashed into TTY, but no useful error message :(
