### ISSUE TITLE
Drop shadow in special workspace be looking extra thicc

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#3916]
### Hyprland Version

Hyprland, built from branch main at commit 812a3f6d78681abbfbc0b01f3b5956c38ae06c1c dirty (renderer: fix double render of tiled on workspace switch). Tag: v0.32.3-47-g812a3f6d

### Bug or Regression?

Bug

### Description

drop shadow in special workspace be looking extra thicc
maybe related to #3888 ?
also its not the dim. i disabled it

### How to reproduce

default config
run `hyprctl keyword decoration:shadow_range 50`
compare drop shadow in a special workspace and a regular workspace. it looks much thicker in special

**Comment by vaxerski** [comment]
looks like double rendering

**Comment by thejch** [comment]
seems to still happen

**Comment by vaxerski** [comment]
??? was defo fixed for me. Repro steps??

**Comment by thejch** [comment]
I can reproduce this every time i launch kitty in special. so i am not sure what to provide as repro steps.
but try the following so its more noticeable:
```sh
#!/bin/sh

hyprctl keyword misc:disable_hyprland_logo true
hyprctl keyword misc:background_color "rgb(ffffff)"
hyprctl keyword decoration:shadow_range 50
hyprctl keyword decoration:dim_special 0
hyprctl dispatch exec "[size 100 100;float;move 20% 20%] kitty"
sleep 1;
hyprctl dispatch workspace special
hyprctl dispatch exec "[size 100 100;float;move 50% 20%] kitty"

```

**Comment by vaxerski** [comment]
check with above

**Comment by thejch** [comment]
Seems partially fixed.
However, there's is a few new issues that I noticed.
1. have floating window in regular, and open special. now the floating window in regular is double rendered
2. following 1, now open a window in special, and close special, the regular window blinks a few times for some reason
3. and if the window in special is tiled, the window in regular gets rendered on top of it, while it should be under it
4. sometimes when you have a maximized window in regular, and you open up special, the special window gets double rendered during the animation

**Comment by Dickby** [comment]
On my side, this seems to be fixed.
