### ISSUE TITLE
The new default config with nomaximizerequest triggers red warning bar

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#3917]
### Hyprland Version

Hyprland, built from branch main at commit 812a3f6d78681abbfbc0b01f3b5956c38ae06c1c dirty (renderer: fix double render of tiled on workspace switch). Tag: v0.32.3-47-g812a3f6d

### Bug or Regression?

Bug

### Description

The new default config with nomaximizerequest triggers red warning bar
![image](https://github.com/hyprwm/Hyprland/assets/66577496/2101d02c-f5e2-4852-85e4-d3de2e3fee63)

### How to reproduce

run hyprland with default config

**Comment by vaxerski** [comment]
pff I am an idiot
