### ISSUE TITLE
Weird exec behavior

### ISSUE THREAD

**Issue by yavko** [hyprwm/Hyprland#392]
commit: `f35d513bf55d5232936f017aa2697a6b4d64f6e6`
Okay so this started happening pretty recently, basically lets say in my config I have a exec-once to run my autostart files with dex (hasn't been updated in like a year so not a dex issue), so first of all I can't kill them normally, running `pkill app-name` doesn't work I have to use `pkill -KILL app-name`, and yes this doesn't happen when I run it from like kitty, and yes it started recently, secondly my policy-kit agent (pantheon-polkit, looks nice so thats what I use) (which I'm running with dex as a autostart file) wont appear, and yes I checked `hyprctl clients`, but it works just fine if I run the same command in kitty. Has something changed in the way stuff are executed? I'm a doing something wrong? idk

**Comment by vaxerski** [comment]
last change to execs was on the 17th of June

**Comment by vaxerski** [comment]
have you found a fix?

**Comment by yavko** [comment]
> have you found a fix?

Nope I just use systemd now (for most things)

**Comment by yavko** [comment]
> have you found a fix?

But im not sure if this is related, but one time i think it said you can't kill this process since it belongs to another user, but ive never gotten that again, and maybe its unrelated

**Comment by vaxerski** [comment]
closing then
