### ISSUE TITLE
button.active color in waybar not working after update

### ISSUE THREAD

**Issue by Nocxium** [hyprwm/Hyprland#3924]
### Hyprland Version

v0.32.3

### Bug or Regression?

Bug

### Description

After updating, "color" isnt working in my waybar config under #workspaces active.button
background-color and other things like fonts are working fine, so its just this specifc thing that isnt working.

### How to reproduce

#workspaces button.active {
    color: #00BFBC;
    border-color: #00BFBC;
    font-size: 18px;
}

This is what im currently using

**Comment by vaxerski** [comment]
I don't think this is a hyprland issue...?

**Comment by h0tc0d3** [comment]
@Nocxium I don't have such problems, the problem is in Waybar settings. СSS file probably contains errors.

**Comment by Nocxium** [comment]
You are right @vaxerski It probably is on waybars side. Thought id ask here as well since there were some changes related to hyprland/workspaces recently. My bad... I did manage to fix it just now so thought id add my solution here in case anyone else have the same problem in the future.

To fix my issue i had to restructure the config so button.persistent was above button.active, and also add button.empty...
With the update, button.persistent holds the color of "busy" desktops, while button.empty holds the color of empty desktops.

Here is the relevant config:
#workspaces button.persistent {
    color: #00BFBC;
    font-size: 18px;
}

#workspaces button.empty {
    color: #3c485d;
}

#workspaces button.active {
    color: #00BFBC;
    border-color: #00BFBC;
    font-size: 18px;
}
