### ISSUE TITLE
Rotated monitor stoped working

### ISSUE THREAD

**Issue by lseman** [hyprwm/Hyprland#3929]
### Hyprland Version

v0.32.3-57-gbe3d6352

### Bug or Regression?

Regression

### Description

Rotated monitor with transform,1 stopped working correctly.
Now it only works on like 1/3 of the screen.

### How to reproduce

Rotate a monitor in the configuration with transform,1
Maybe it's only on NVIDIA cards (need to verify).

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/1711758/85fd7bb7-bb90-4061-adf1-a9515c27fd01)

**Comment by vaxerski** [comment]
looks fine to me, people who rotate their monitors are the devil
