### ISSUE TITLE
install fails with Hunk #1 FAILED at 15.

### ISSUE THREAD

**Issue by Mahgozar** [hyprwm/Hyprland#3930]
### Hyprland Version

v0.32.3-43-g572fd554

### Bug or Regression?

Bug

### Description

when trying to update the package with yay -Syu --devel the process fails with the following report 
```
Hunk #1 FAILED at 15.
1 out of 1 hunk FAILED -- saving rejects to file meson.build.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: hyprland-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-git - exit status 4
```

### How to reproduce

just do yay -Syu --devel hyprland-git

**Comment by vaxerski** [comment]
AUR packages are not maintained by us. Please contact the maintainers of the package to update it.
