### ISSUE TITLE
swaylock - Compositor does not support the input inhibitor protocol, refusing to run insecurely

### ISSUE THREAD

**Issue by rbroggi** [hyprwm/Hyprland#3932]
### Hyprland Version

Compositor does not support the input inhibitor protocol, refusing to run insecurely

### Bug or Regression?

Bug

### Description

After upgrading to latest version, swaylock no longer works. Here is the error:

```
❯ swaylock 
2023-11-24 18:22:32 - [main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely
```

### How to reproduce

Install `swaylock` and latest hyprland version. 

### Crash reports, logs, images, videos

none

**Comment by h0tc0d3** [comment]
@rbroggi `wlr-input-inhibitor-unstable-v1` protocol has been removed from wlroots as deprecated. Update swaylock it supports ext-session-lock-v1 protocol.

https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3760
