### ISSUE TITLE
[BUG v0.32.3] Session is unlocked after recovering from unsafe state

### ISSUE THREAD

**Issue by levnikmyskin** [hyprwm/Hyprland#3934]
### Hyprland Version

Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3). Tag: v0.32.3

### Bug or Regression?

Bug

### Description

Hey,
it's me again with some more monitor problems, I'm sorry :D
As per title, if the session is locked with swaylock (only one I've tried), and all monitors are disabled (putting Hyprland into unsafe state), reenabling one monitor gives full access to the computer.  
  
I've tried this on my laptop only.

### How to reproduce

1. Connect laptop to external monitor;
2. Disable laptop's monitor;
3. Run `swaylock -f; sleep 10 && hyprctl keyword monitor eDP-1,preferred,0x0,1.2`;
    1. alternatively, you can remove the `swaylock` call and just lock the screen yourself while the command is sleeping;
4. Remove the HDMI/DP cable (i.e., phisically disconect the external monitor);
5. Wait for the laptop's monitor to come back up...session is fully unlocked.

**Comment by vaxerski** [comment]
sounds like you running outdated swaylock, with ext-session-lock-v1 that should never happen.

**Comment by levnikmyskin** [comment]
Uuuups my bad. I was actually still running swaylock-effects, didn't notice that it went completely unmantained in the meanwhile.  
Sorry for the trouble, closing this!
