### ISSUE TITLE
Cursor size is being scaled

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#3935]
### Hyprland Version

Hyprland, built from branch makepkg at commit d79cf0afe26fd6503a47c17a524d45742bf2461a dirty (renderer: fix software cursors on nvidia). Tag: v0.32.3-59-gd79cf0af

### Bug or Regression?

Regression

### Description

Cursor size is being scaled
please don't scale width and height here: https://github.com/hyprwm/Hyprland/commit/d79cf0afe26fd6503a47c17a524d45742bf2461a

### How to reproduce

Have a scale of 2 on your monitor

**Comment by vaxerski** [comment]
oh, right. I should only scale position.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13462165/patch.txt)
try this

**Comment by thejch** [comment]
yea works

**Comment by vaxerski** [comment]
oki doki thanks :)
