### ISSUE TITLE
Steam games crashing hyprland and ArmCord not rendering properly.

### ISSUE THREAD

**Issue by RadovanSk** [hyprwm/Hyprland#3937]
### Hyprland Version

Hyprland, built from branch  at commit d79cf0afe26fd6503a47c17a524d45742bf2461a  (). Tag:   flags: (if any) debug

### Bug or Regression?

Bug

### Description

After updating Hyprland to the newest commit, running any Steam games seems to crash Hyprland and ArmCord does not render properly. Maybe there are more issues but I haven't found any yet.

### How to reproduce

1. Update to the latest commit.
2. Start ArmCord, rendering issue should be visible
3. Start Steam and try running any game.
4. Hyprland should crash

### Crash reports, logs, images, videos

[hyprlandCrashReport14370.txt](https://github.com/hyprwm/Hyprland/files/13462110/hyprlandCrashReport14370.txt)

**Comment by vaxerski** [comment]
armcord render issues sound like nvidia, can I get a video / image?

crash looks like wlroots, I've asked on IRC, but it doesn't seem like hyprland's fault.

**Comment by vaxerski** [comment]
can you build in debug with symbols? idk how 2 on nix, but both wlroots and hyprland. @fufexan cuz nix

**Comment by RadovanSk** [comment]
> armcord render issues sound like nvidia, can I get a video / image?
> 
> crash looks like wlroots, I've asked on IRC, but it doesn't seem like hyprland's fault.

I have only AMD on my system. RX 6800M and iGPU with Ryzen 9 5980HX. Below is the video showing the issue

https://github.com/hyprwm/Hyprland/assets/64273472/67ed1e3c-3e94-4ec8-96a5-43ea7cee508e

.

**Comment by RadovanSk** [comment]
After downgrading to commit https://github.com/hyprwm/Hyprland/commit/812a3f6d78681abbfbc0b01f3b5956c38ae06c1c of hyprland the issue with games is fixed. ArmCord still has rendering issues however.

**Comment by RadovanSk** [comment]
Disabling wayland on ArmCord fixes the rendering issue, I am not sure if it is Hyprland related but I thought I'd say this too. I believe this is not Hyprland related however.

**Comment by eriedaberrie** [comment]
That ArmCord issue is a faulty GPU cache which can be deleted at ~/.config/ArmCord/GPUCache, entirely unrelated to Hyprland.

**Comment by vaxerski** [comment]
can you build in debug and repro the crash? would help wlroots maintainers.

**Comment by RadovanSk** [comment]
> can you build in debug and repro the crash? would help wlroots maintainers.

I'm sorry but I have no idea how to do that on NixOS yet. I will try to research about this tomorrow and see if I can do it. I'll inform you about the progress.

**Comment by RadovanSk** [comment]
> can you build in debug and repro the crash? would help wlroots maintainers.

Ok I have built it in debug mode and reproduced the crash. Everything was the same. Here's below crash report of hyprland during debug mode.
[hyprlandCrashReport2748.txt](https://github.com/hyprwm/Hyprland/files/13463898/hyprlandCrashReport2748.txt)

**Comment by vaxerski** [comment]
doesn't look like debug to me.

Are you on systemd?

if so, you can provide the gdb backtrace with `coredumpctl debug Hyprland`, then once you get to `(gdb)` (it will ask you whether you want symbols before that, say yes, if pager, say continue without one) type `bt -full` and give output

**Comment by RadovanSk** [comment]
> doesn't look like debug to me.
> 
> Are you on systemd?
> 
> if so, you can provide the gdb backtrace with `coredumpctl debug Hyprland`, then once you get to `(gdb)` (it will ask you whether you want symbols before that, say yes, if pager, say continue without one) type `bt -full` and give output

Doing the command ``coredumpctl debug Hyprland`` simply outputs ``No match found.``

**Comment by patrickr-de** [comment]
[gdb_logging.txt](https://github.com/hyprwm/Hyprland/files/13464964/gdb_logging.txt)

I have no clue how this stuff works, so I'm not sure if the txt is helpful and captures what happened. I've obtained it after a crash:

- Started game with Steam
- Got a blackscreen and was thrown back to SDDM
- Relogged and did bt -full

I've also tried disabling vrr for both monitors with the same result.

**Comment by vaxerski** [comment]
I've downgraded the wlr dep for now.

a5f64b48ca23edfba807c8842ff12e3d96494f5f

**Comment by vaxerski** [comment]
assert is good, gonna report.

**Comment by vaxerski** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3770

**Comment by vaxerski** [comment]
closing as this isn't a hyprland issue per-se, and I have downgraded so it should be gone now
