### ISSUE TITLE
hyprctl setprop alpha not working within script

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#3938]
### Hyprland Version

Hyprland, built from branch main at commit e40e486f61f2643578b9977b86f408799dbc75fd dirty (renderer: better checks for special rendering in renderWorkspaceWindows). Tag: v0.32.3-50-ge40e486f

### Bug or Regression?

Bug

### Description

I am planning to use mwheeldown and up to increase and decrease the window opacity from the active window

**but for example**

```
import subprocess
import json

def SetAlpha(address):
    print("hyprctl setprop address:{0} alpha 1".format(address))

address = subprocess.check_output("hyprctl activewindow -j".split()).decode()
address =  json.loads(address)
address = address['address']
SetAlpha(address)
```

in this example, the alpha is set to 1 but instantly is set back to the default from hyprland.conf
but if I execute the full command in a terminal hyprctl setprop address:... alpha 1  that works

### How to reproduce

try set window opacity with the following python script 

```
import subprocess
import json

def SetAlpha(address):
    print("hyprctl setprop address:{0} alpha 1".format(address))

address = subprocess.check_output("hyprctl activewindow -j".split()).decode()
address =  json.loads(address)
address = address['address']
SetAlpha(address)
```

**Comment by vaxerski** [comment]
what if you lock it?

What's the output of the cmd?

**Comment by killown** [comment]
worked with your suggestion

> what if you lock it?
> 
> What's the output of the cmd?

**Comment by vaxerski** [comment]
kinda expected. not locking means any change of the window status triggers a recalc of alpha, as it's dynamic.
