### ISSUE TITLE
Mirrored monitors crash Hyprland

### ISSUE THREAD

**Issue by eriedaberrie** [hyprwm/Hyprland#3939]
### Hyprland Version

822775aa8c0134e66cbf09b7dfd785fad13f329a

### Bug or Regression?

Regression

### Description

Hyprland crashes when I start it with mirrored monitors in my configuration. It seems to run fine without.

(I cannot for the life of me figure out how to get asan working with nix but according to coredumpctl it is from a renderMonitor call.)

### How to reproduce

Add something like `monitor = HDMI-A-1, preferred, auto, 1, eDP-1` into your Hyprland config on the latest commit and then try to run Hyprland.

### Crash reports, logs, images, videos

[hyprlandCrashReport266872.txt](https://github.com/hyprwm/Hyprland/files/13462548/hyprlandCrashReport266872.txt)

**Comment by vaxerski** [comment]
oopsie woopsie XD
