### ISSUE TITLE
Per-device sensitivity

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#394]
As of writing this request, the only way to increase mouse speed is via the `sensitivity` setting in `hyprland.conf` file. However, increasing the value for my trackpad to make it fast also makes my already fast mouse even faster!

It would be really nice if we could individually set mouse & trackpad sensitivity (and even natural scrolling)  just like we could in X11 using `libinput`

Ik this feature is not a necessary one but having it would certainly make the hyprland experience much more pleasureful!

**Comment by vaxerski** [comment]
I am unsure whether that is possible, I don't get the device passed with pointer motion events. Does sway support that?

also, it's mouse sensitivity, not accel.

**Comment by System-x64** [comment]
I Suppose you can?

![20220719_22h31m29s_grim](https://user-images.githubusercontent.com/90208727/179808009-fdbb9e62-1419-4068-aaa8-a7c55152c929.png)

link to the issue-  [https://github.com/swaywm/sway/issues/3174](url)

**Comment by vaxerski** [comment]
tank you.

**Comment by System-x64** [comment]
i know this may sound like a dumb question but are mouse accel and mouse sensitivity 2 different things or the same?

**Comment by vaxerski** [comment]
no, it's libinput mouse sens vs hyprland mouse sens

**Comment by System-x64** [comment]
so i assume what you are trying to say is that sway uses `libinput sens` where it is indeed possible whereas hyprland uses its own `hyprland sens` where it _may_ be posssible but you'll need to configure that?

**Comment by vaxerski** [comment]
I'm adding a libinput sens option rn. bro chill

**Comment by System-x64** [comment]
Thank you !!!!!!!!

**Comment by System-x64** [comment]
Also its about 11pm here so i may not be able to reply going forward 💤 💤💤

**Comment by vaxerski** [comment]
added in d52446135bd46dc0260d9507e82173847d4196c8

**Comment by System-x64** [comment]
Wow...thanks alot mate! i guess if you'll keep adding these tiny tiny tweaks, hyprland will become the bspwm of wayland
