### ISSUE TITLE
Errors occur when trying to open an application in the special workspace.

### ISSUE THREAD

**Issue by DRAGONTOS** [hyprwm/Hyprland#3940]
### Hyprland Version

main

### Bug or Regression?

Bug

### Description

When I open something like Kitty in the special workspace, it gives errors and doesn't do anything.
![image](https://github.com/hyprwm/Hyprland/assets/46651680/89e8a4dc-c9ed-41b2-baa7-e300a6c8e167)

### How to reproduce

1. Install Hyprland from Git.
2. Start Hyprland.
3. Open a special workspace.
4. Try to open something in it.

**Comment by DRAGONTOS** [comment]
Im guessing this is because of the update to wlroots.

**Comment by vaxerski** [comment]
your report is invalid:
- main is not a version
- that error does not exist in hyprland. This is most likely a faulty plugin.
