### ISSUE TITLE
Support virtual keyboards: maliit

### ISSUE THREAD

**Issue by appsforartists** [hyprwm/Hyprland#3943]
### Description

To make Hyprland usable without a keyboard, it needs to support a virtual (touch) keyboard.  So far as I can tell, Nokia's Maliit is the closest equivalent to what you might find on an iPad or Chromebook.  Unforunately, it doesn't draw anything in Hyprland.

I tried installing the nixpkg and running it.  I don't see any fatal errors, but it doesn't draw anything in Hyprland:

```
$ maliit-keyboard
wordengine.cpp plugin "/nix/store/2rzb2k58hlw8q4qqy66lm2baz3z869qb-maliit-keyboard-2.3.1/lib/maliit/keyboard2/languages/en/libenplugin.so" loaded
inputmethod_p.h registerActiveLanguage(): activeLanguage is: "en"
in inputMethod.cpp setActiveLanguage() activeLanguage is: "en"
DB path: /nix/store/2rzb2k58hlw8q4qqy661m2baz3z869qb-maliit-keyboard-2.3.1/lib/maliit/keyboard2/languages/en/database_en.db spellechecker.cpp in setLanguage() lang="en" dictPath= "/var/empty/share/hunspell"
Did not find a dictionary for "en" - checking for "en" 
No dictionary found for "en" turning off spellchecking
no dictionary to turn on spellchecking
inputMethod::reset()
in clear preedit.. clearing word engine
QSoundEffect (pulseaudio): Error decoding source file:///nix/store/2rzb2k58hlw8q4qqy66lm2baz3z869qb-maliit-keyboard-2.3.1/share/maliit/keyboard2/sounds/key_tick2_quiet.wav
```

**Comment by vaxerski** [comment]
virtual keyboards are supported. It's up to them to support wayland properly and not kde / gnome / x11.

ref: https://github.com/jjsullivan5196/wvkbd

**Comment by earboxer** [comment]
Anyone coming here to see the state of virtual keyboard support: https://github.com/hyprwm/Hyprland/issues/2017 is a big issue with using wvkbd as it won't be able to interact with keyboard-grabbing layers (like rofi).
