### ISSUE TITLE
Gnome activities and macos mission control

### ISSUE THREAD

**Issue by craftergarage** [hyprwm/Hyprland#3951]
### Description

I want to list all open windows when I press the Super key. Can I add a feature similar to Mission Control on MacOS or Activities Overview on GNOME? Is there a way to configure or implement this?

**If there is a different method, can you inform me about it?**

![image](https://github.com/hyprwm/Hyprland/assets/121237802/3902752e-f64f-4b99-9f7f-0985452102ed)

![image](https://github.com/hyprwm/Hyprland/assets/121237802/4293c2f1-8c77-454b-b91c-8d02882b7a67)

**Comment by craftergarage** [comment]
not change

**Comment by imxyy1soope1** [comment]
see https://github.com/DreamMaoMao/hycov

**Comment by vaxerski** [comment]
see #3955
