### ISSUE TITLE
Perfomance is bad when animations are running with iGPU

### ISSUE THREAD

**Issue by RadovanSk** [hyprwm/Hyprland#3959]
### Hyprland Version

Hyprland, built from branch  at commit 3fe6162af1904f15fc5526c179c06a48265bdbff  (). Tag:   flags: (if any) debug

### Bug or Regression?

Bug

### Description

When there is any kind of animation playing, whether it is video playing or animations inside an application (like steam for example) switching between workspaces is not smooth at all.

I have tried many things and none worked. I have set CPU and GPU to performance mode, I have set GPU to Hybrid mode, I have enabled vrr and disabled it and same with vfr. Disabled scaling too.

What I have noticed is that the load on my iGPU and dGPU is just unreasonable. With vrr disabled my iGPU is at around 50% (that's fine) but the performance is bad. With vrr on iGPU is at 100% load and the performance is just a little bit better. The only time I am able to make Hyprland go fully smooth is when I use my dGPU as primary one and iGPU as secondary on Hyprland which seems unreasonable for me, considering that for other people iGPU is just enough for smooth experience, even on 4K monitors.

I have RX 6800M GPU and Ryzen 9 5980HX CPU with iGPU. My monitor is 2560x1440 with 165hz. Below I will send pictures of my tests while some kind of animation is playing (in this case video playing). I will gladly provide more info if needed. All of the tests were made in performance mode btw.

iGPU with vrr set to ``1`` and vfr set to ``true``
![20231125_19h44m52s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/5a7c8d3c-18c2-4f79-931e-d56e1a4d9e1a)

iGPU with vrr set to ``1`` and vfr set to ``false``
![20231125_19h47m18s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/a818766f-1ea3-441c-8e96-4442174c58ff)

iGPU with vrr set to ``0`` and vfr set to ``true``
![20231125_19h49m40s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/db0df3e2-ec37-4076-84ae-63435048419a)

iGPU with vrr set to ``0`` and vfr set to ``false``
![20231125_19h51m32s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/aabcf73e-e2f6-4975-959e-bb959a1c4ee6)

dGPU (main) and iGPU (secondary) with vrr set to ``1`` and vfr set to ``true``
![20231125_19h56m01s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/c1f1315b-7913-47c7-8f8e-7de0bbdd077d)
![20231125_19h57m16s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/81eeaeff-4ac9-4974-b8e5-27ac0e7a9b79)

dGPU (main) and iGPU (secondary) with vrr set to ``1`` and vfr set to ``false``
![20231125_20h11m03s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/372a3111-2910-413e-ba48-7a39a7be9cf8)
![20231125_20h11m12s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/9a9abefa-a857-4dfb-9605-a75f8fd7276b)

dGPU (main) and iGPU (secondary) with vrr set to ``0`` and vfr set to ``true``
![20231125_20h13m12s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/93e41007-54ee-4b1a-859e-e3533c81cced)
![20231125_20h13m24s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/84d0e289-9a5f-4a82-9b4c-a25c22e6cd9e)

dGPU (main) and iGPU (secondary) with vrr set to ``0`` and vfr set to ``false``
![20231125_20h15m32s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/65823126-b4dd-41a2-96b9-da9e3ae362a0)
![20231125_20h15m43s_grim](https://github.com/hyprwm/Hyprland/assets/64273472/8b1143b2-7ab0-46ff-8308-396191f92cf6)

Each of these tests were done after session restart. 

One thing to note is that iGPU sometimes jumps to 2100mHz according to ``nvtop`` while dGPU is the main one. I would do tests with purely dGPU enabled but Hyprland refuses to launch when this is the case. A person who has literally the same machine as me reports that Hyprland goes smoothly for them with iGPU only while they have two monitors. I am certain that the behavior my session is showing is not normal at all. One could say that maybe something is wrong in my machine but I have checked everything so many times that I am starting to doubt that the issue is on my part.

Like mentioned before, I will gladly provide more information if needed. I just want Hyprland to run smoothly with iGPU only without my fans going crazy as if I were playing AAA games. Especially when it is possible for others.

### How to reproduce

1. Install Hyprland.
2. Use iGPU only.
3. Try running a video on firefox in workspace 1 for example.
4. Run steam on main page in workspace 2.
5. Try switching between them.
6. The issue should be hopefully visible.

**Comment by vaxerski** [comment]
have you tried kde? sway? 1440p at 165Hz seems impossible to me for an igpu.

**Comment by RadovanSk** [comment]
> have you tried kde? sway? 1440p at 165Hz seems impossible to me for an igpu.

Yes. Both work with no issues.

**Comment by vaxerski** [comment]
what workspace animation are you using?

**Comment by RadovanSk** [comment]
> what workspace animation are you using?

Default ones. My hyprland is mostly default besides binds and scaling. I haven't gotten to ricing my hyprland yet.

**Comment by vaxerski** [comment]
no clue then. on fade, I'd understand, as it's the most taxing one, but slide is default and it shouldn't be.

Sway was a bad example from my side tbh, no anims there. KDE running smooth though is definitely odd.

To me this is just weird. I'd bet on either gpu not keeping up or that funky gpu clock thing when the load is not enough to sustain high clocks but high enough to need them

**Comment by RadovanSk** [comment]
> no clue then. on fade, I'd understand, as it's the most taxing one, but slide is default and it shouldn't be.
> 
> Sway was a bad example from my side tbh, no anims there. KDE running smooth though is definitely odd.
> 
> To me this is just weird. I'd bet on either gpu not keeping up or that funky gpu clock thing when the load is not enough to sustain high clocks but high enough to need them
> 
> FYI: don't play with vfr. vfr should always be enabled, as it is by default.

I was playing with vfr for the sake of tests. I am aware that it should be always on like indicated on the variable page of Hyprland.

Yes, this thing is very weird to me too. I do not understand why would the animations not be smooth on Hyprland with iGPU. Especially when plenty of people do not have this issue. Even the person with the same machine as me does not have these issues. 

I do not think that gpu is the issue here, or at least gpu only. I see no reason for KDE working fine but Hyprland not, there must be something more going on. I would understand that GPU would be not able to keep up if I didn't have high-end laptop. Though considering what kind of machine I have, I see no reason for tiling compositor to not run smoothly out of all things.

I'll try to get more info if possible, but for now I am just stuck with this issue.

**Comment by Evangelospro** [comment]
I can confirm I am having the same issue, igpu is always above 80% from the Hyprland itself when idling... Is there any info I could provide to help troubleshoot this? My animations are completely disabled, same for blur

**Comment by droc12345** [comment]
I'm wondering it this isn't related to the full gl rendering pipeline - commit 2ebfd0c, because I notice that my rx560 is using significantly more power, even when idle. pre that commit it ran at ~8 watts idle, after the commit it's 16 and up.
If I build with commit before 2ebf0c, power usage goes back to what it was.

I set the card for low power performance and it keeps it at the ~8 range, but all animations are very choppy.

So it's a choice between much more power being used or no animations and choppiness in movement. 

To me, there's no noticeable performance difference with or without the commit.
In my case no improvement in smoothness, etc, just more power being used.

**Comment by RadovanSk** [comment]
> I'm wondering it this isn't related to the full gl rendering pipeline - commit [2ebfd0c](https://github.com/hyprwm/Hyprland/commit/2ebfd0c7456eff7e9c03d379d1dfbc611dc26672), because I notice that my rx560 is using significantly more power, even when idle. pre that commit it ran at ~8 watts idle, after the commit it's 16 and up. If I build with commit before 2ebf0c, power usage goes back to what it was.
> 
> I set the card for low power performance and it keeps it at the ~8 range, but all animations are very choppy.
> 
> So it's a choice between much more power being used or no animations and choppiness in movement.
> 
> To me, there's no noticeable performance difference with or without the commit. In my case no improvement in smoothness, etc, just more power being used.
> 
> With the above people mention the igpu, it's probably because of limited resources, exacerbated by the commit.

I had these issues way before that commit. And I do not mind using more power as long as it is still reasonable. Though my iGPU running constantly at 100% and still have hyprland animations to be choppy is just crazy. That's just not normal imo.

I wonder if the issue is related to the CPU. Something like Hyprland needing to use CPU too but not much goes into it, only GPU. Though I do not know exactly how Hyprland works from that aspect. I guess I might as well try overclocking my CPU and see if anything changes.

**Comment by vaxerski** [comment]
I've made some performance improvements in 68e57b7ee36f015d99988f38cb3a8b83c23ae7c3 and 408d96668d57fdd1a713e56f1d40a9befd51bd4a

also, for best results, use hyprpaper for your wallpapers and not swaybg. Haven't tested swww or any others.

**Comment by RadovanSk** [comment]
> I've made some performance improvements in [68e57b7](https://github.com/hyprwm/Hyprland/commit/68e57b7ee36f015d99988f38cb3a8b83c23ae7c3) and [408d966](https://github.com/hyprwm/Hyprland/commit/408d96668d57fdd1a713e56f1d40a9befd51bd4a)
> 
> also, for best results, use hyprpaper (git!!! commit from today) for your wallpapers and not swaybg. Haven't tested swww or any others.

I use SWWW and I did tests without it running too and it does not seem to impact the perfomance in any way, only when the wallpaper changes which I do not mind and is to be expected. I will build into the latest branch now and report if anything changes for me.

**Comment by RadovanSk** [comment]
The perfomance seems to be actually better,. The GPU also uses a little bit less resources. The animations are still snappy however. I'll try checking if it is some service or process ruining it on my system.

**Comment by vaxerski** [comment]
at least another confirmation my patches worked, even if just a bit :)

**Comment by droc12345** [comment]
Interesting, I am running latest git (hypr) 
pre gl  with swaybg and waybar - ~8 watts
post gl with swaybg and waybar - 16-18 watts consistent
post gl with swaybg, no waybar - ~10 watts

So it appears as if some interaction with waybar, and the gl pipeline keeping the gpu busy so watts stays higher than it used to.
I haven't checked other resource usage on the gpu, I just happen to keep track of watts in waybar.

**Comment by vaxerski** [comment]
that's odd, as the new pipeline allows for some shortcuts where it's possible and keeps everything just like it was otherwise.

**Comment by droc12345** [comment]
I removed parts of waybar config, to see if I could narrow things down.

Running clock with display per second - 16-18  watts
Without clock, it drops to ~14 watts (things displayed every 2 seconds or longer)
and without waybar it runs ~10

I even built the latest git waybar to see if any changes, still the same.

The only other time I've seen >= ~16 watts is if I'm trying to run 2 monitors off the card at the same time.

**Comment by RadovanSk** [comment]
> The perfomance seems to be actually better,. The GPU also uses a little bit less resources. The animations are still snappy however. I'll try checking if it is some service or process ruining it on my system.

I tried to kill as many services and processes as I could and nothing seems to have changed the performance.

Though I have noticed something that could help a lot I believe. I found out that it might not be animations but rather a video playing, specifically on youtube. I use firefox as my browser and I listen to music all the time. I have noticed that the animations are not smooth mostly when I switched between workspaces in which one of them is the video playing (the video must be on the screen). There are small lags when switching between matrix and steam too but it's barely noticable. Youtube videos seem to be mostly affecting the perfomance. I tried twitch, discord and reddit with videos and none affect the perfomance like Youtube does.

This is weird to me though because I asked others to play a video on youtube and switch between workspaces and tell me if it affects their performance and everyone told me that it does not and they use iGPU only too.

What do you think that the issue may be?

**Comment by vaxerski** [comment]
in that case, I think the issue may be youtube or firefox... Tried chromium? does it do the same? if so, the issue is youtube.

**Comment by RadovanSk** [comment]
> in that case, I think the issue may be youtube or firefox... Tried chromium? does it do the same? if so, the issue is youtube.

After more testing I found out what the issue was. My normal config has set scaling to ``1.5``. I set it to ``1`` and everything goes fine, even the youtube video. I assume that was also a difference between other people's config and mine.

The problem is that I have 2K monitor and I can't see the text very well with scaling set to ``1``. Furthermore, on KDE I have scaling set to 150% which is the equivalent to ``1.5`` in Hyprland, that's why I had such scaling in the first place.

Why does it happen though? On KDE the scaling works fine but not on Hyprland? Is there a way to mitigate or fix this problem? My eyes kinda hurt trying to read the text and all of that stuff when it's too small.

**Comment by vaxerski** [comment]
what if you set it to 2?

**Comment by RadovanSk** [comment]
It's very smooth. That is beyond weird. 1.5 has issues but 2 doesn't? It is pretty big for my liking but a lot better than 1.

**Comment by vaxerski** [comment]
hahahaha welcome to fractional scaling on wayland :)

my guess is firefox is not using the new fractional scaling protocol yet, so what happens is:

firefox gets logically resized to size / 1.5 and receives a scale of 2
firefox renders at (size / 1.5) * 2 = 4/3 of the monitor's res
lag because 4/3 of 1440p is almost 4k

**Comment by RadovanSk** [comment]
> hahahaha welcome to fractional scaling on wayland :)
> 
> my guess is firefox is not using the new fractional scaling protocol yet, so what happens is:
> 
> firefox gets logically resized to size / 1.5 and receives a scale of 2 firefox renders at (size / 1.5) * 2 = 4/3 of the monitor's res lag because 4/3 of 1440p is almost 4k

Ooooooh that makes sense hahaha. KDE has pretty good fractional scaling from what I have heard, I believe my experience confirms it too. But I have totally forgotten about the state of fractional scaling on wayland overall.

Well, I am glad that this issue can be fixed in a way, I believe that's what other people are struggling with too. I would suggest documenting it somewhere on hyprland website so people know not to use non-integer numbers as scaling on Hyprland. I have seen plenty of people do the same thing I did.

Thank you again for willing to help me. I will close this issue now because the root of the problem has been found and it can be fixed.

**Comment by vaxerski** [comment]
You can use fractional scaling and there's nothing wrong with it, it works. More and more apps support it. Chromium and qt I know already do. IIRC firefox did too, but guessing by the lag it might not / impl sucks

**Comment by RadovanSk** [comment]
That's true I guess. Especially when everything worked and there were some small issues with specific apps and big issue with firefox. Though it is not perfect it seems and many people wish to have the "perfect" experience if you get what I mean.

I pretty much fall under the same category too. It works mostly yes, but firefox makes it problematic and I do not want to use anything else and I believe other people will have similar excuses too. So I believe it would be great to at least inform people that if they have performance issues and are using fractional scaling then they should try non-fractional scaling and see if this fixes their problems.

**Comment by vaxerski** [comment]
feel free to make a mr to the wiki :)

**Comment by RadovanSk** [comment]
Sure!

**Comment by RadovanSk** [comment]
> feel free to make a mr to the wiki :)

Done :)

**Comment by vars1ty** [comment]
Read this https://www.phoronix.com/news/Firefox-Fractional-Scale-v1, Firefox 121 is also supposedly getting some Wayland updates.

**Comment by vaxerski** [comment]
worth noting that impl seems to be dogshit and broken as hell
