### ISSUE TITLE
Spotify in special tag causes problems on multi-monitor setups

### ISSUE THREAD

**Issue by Pebor** [hyprwm/Hyprland#396]
Reproduce:
- open spotify and switch to tiled
- move it to the special workspace
- move an another window from not your primary monitor into the special workspace
- weird behavior regarding the primary monitor ensues
(this has not been thoroughly tested, might be also applicable under more circumstances)

Expected outcome is for Spotify to play nice and work as any other tiled window in the special workspace and not cause trouble.
Noted outcome is breakage fixable by switching to a different workspace on the broken monitor.
**Spotify is regarded as being broken and at fault.**

Video to visualize:
 
[2022-07-20 12-24-36.webm](https://user-images.githubusercontent.com/32438954/179964242-92dd67fb-701d-4762-a311-141d720643f6.webm)

**Comment by vaxerski** [comment]
Is this still a thing?

**Comment by Pebor** [comment]
Still happens. But its.. better? A bit. Doesn't seem to happen every time now. Seems like the requirement is a bit different :shrug:
Spotify can break it in both tiled and floating, but I've noticed that when putting anything floating into the special workspace it breaks as well, windows in a workspace disappear and the floating window that was moved to special is not shown on the right monitor it should be + damage tracking leaves a trail from the animation. Only saw https://github.com/hyprwm/Hyprland/issues/827 which doesn't talk about rendering breakage so am reporting this just in case

**Comment by Pebor** [comment]
Well actually, putting anything into special as a second item and upwards breaks my workspace the same way also..
Having focus on the second monitor first, then moving a window from the first monitor breaks the second monitor's workspace

**Comment by vaxerski** [comment]
odd. Doesn't do that for me.

**Comment by Pebor** [comment]
Have you tried with only two monitors? (if I remember, you have a 3 monitor setup)
It's also weird that this kind of behavior only seem to happen to me. At least I haven't seen any other issue here.

My monitors are different. One is a 60Hz 24 inch, while my primary is a 165Hz 23.8 inch, both 1080p though.

**Comment by vaxerski** [comment]
I now have only 2 monitors (sadge)

**Comment by Pebor** [comment]
:disappointed:

**Comment by OtaK** [comment]
Same issue here but not only on spotify. I think it might be related to heterogenous setups (whether in scale or refresh rate).

What happens is that my 4k screen scaled at 1.25 will sometimes become a "no-go zone" - i.e. if I move any window to it (whether by mod+dragging or with `hyprctl dispatch` they just...vanish?
They are still listed as a running process and are present in `hyprctl clients` so they didn't crash but Hyprland doesn't render them.

If that's useful I make extensive use of both the special workspace (to tuck away my kitty terminal) and dwindle groups. I also noted that manually assigning workspaces to monitors seems to trigger this pretty consistently.

As you can see I have a *very* heterogenous setup: 

<details>
<summary>`hyprctl monitors` Output</summary>

```
Monitor DP-1 (ID 0):
	1920x1080@239.759995 at 3072x0
	description: BenQ Corporation ZOWIE XL LCD EBRAL01378SL0 (DP-1)
	active workspace: 1 (1)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1

Monitor DP-2 (ID 1):
	1920x1080@60.000000 at 4992x0
	description: ViewSonic Corporation VA2456 Series VC4183200617 (DP-2)
	active workspace: 2 (2)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 1
	focused: no
	dpmsStatus: 1

Monitor DP-3 (ID 2):
	3840x2160@143.998993 at 0x0
	description: LG Electronics LG ULTRAGEAR+ 201NTPCEA896 (DP-3)
	active workspace: 3 (3)
	reserved: 50 0 0 0
	scale: 1.25
	transform: 0
	focused: no
	dpmsStatus: 1

```

</details>

**Comment by vaxerski** [comment]
can we close this?

**Comment by OtaK** [comment]
@vaxerski Yeah. Haven't had that happening to me for a looooooong while. So for me it can be closed np
