### ISSUE TITLE
1440p 165hz screen is stuck at 1440p 120hz

### ISSUE THREAD

**Issue by OliverGeneser** [hyprwm/Hyprland#3960]
### Hyprland Version

hyprland, built from branch main at commit 512a59731b2e579b66325d0e9ce770919eecd685 dirty (config: default special_scale_factor to 1). Tag: v0.32.3-64-g512a5973

### Bug or Regression?

Bug

### Description

My primary monitor is 2560x1440 165hz but in hyprland it's only detected as 2560x1440 120hz. 
165hz works in windows so I know its not a hardware issue but a software/driver issue.

I have tried both highres, highrr and 2560x1440@165 with the same result.

This is my hyprland.conf
```bash
monitor = DP-1,highres, 1920x0, 1
monitor = HDMI-A-1,highres,0x0,1
monitor = DVI-D-1,highres,1920x-1080,1
```

xrandr
```bash
DP-1 connected primary 2560x1440+1920+0 (normal left inverted right x axis y axis) 600mm x 340mm
   2560x1440    119.95*+
   1920x1440    119.97  
   1600x1200    119.82  
   1440x1080    119.92  
   1400x1050    119.90  
   1280x1024    119.83  
   1280x960     119.89  
   1152x864     119.77  
   1024x768     119.80  
   800x600      119.85  
   640x480      119.52  
   320x240      117.34  
   1920x1200    119.90  
   1680x1050    119.89  
   1440x900     119.94  
   1280x800     119.85  
   1152x720     119.73  
   960x600      119.74  
   928x580      119.55  
   800x500      119.47  
   768x480      119.71  
   720x480      119.65  
   640x400      119.64  
   320x200      117.55  
   2048x1152    119.89  
   1920x1080    119.93  
   1600x900     119.95  
   1368x768     119.83  
   1280x720     119.67  
   1024x576     119.85  
   864x486      119.69  
   720x400      119.54  
   640x350      119.24
```

hyprctl monitors
```bash
Monitor DP-1 (ID 1):
	2560x1440@119.99800 at 1920x0
	description: ASUSTek COMPUTER INC VG27A N8LMQS070105 (DP-1)
	make: ASUSTek COMPUTER INC
	model: VG27A
	serial: N8LMQS070105
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

### How to reproduce

.

**Comment by phonetic112** [comment]
can't you just do `monitor = DP-1,2560x1440@165,1920x0,1`

**Comment by OliverGeneser** [comment]
> can't you just do `monitor = DP-1,2560x1440@165,1920x0,1`

Forgot to mention that I have also tried that :smile:

**Comment by vaxerski** [comment]
wlroots issue. does happen.

**Comment by MadsKelberg** [comment]
@vaxerski Happens to me too.. Is there a solution?

**Comment by vaxerski** [comment]
afaik, no

**Comment by RadovanSk** [comment]
Try doing ``cvt -r 2560 1440``. You should hopefully get something along those lines``Modeline "2560x1440_165.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync``. This basically shows the Modeline for the resolution you want.

Then you need to type ``xrandr --newmode`` and add everything yafter Modeline you got before, so in this case ``"xrandr --newmode "2560x1440_165.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync``. to create a new xrandr mode.

Then type ``xrandr --addmode DP-1 2560x1440_165.00`` to add this mode to your current output device.

And then you just change the output to the new mode you added by doing this ``xrandr --output DP-1 --mode 2560x1440_165.00``

Hopefully this should fix your issue. I don't think that this fix always works but you can give it a try.

**Comment by vaxerski** [comment]
this only works for xwayland. For hyprland, you can put this modeline as your monitor res param (see https://wiki.hyprland.org/Configuring/Monitors/#custom-modelines )

**Comment by OliverGeneser** [comment]
> cvt -r 2560 1440

cvt gives me # 2560x1440 164.90 Hz (CVT) hsync: 261.86 kHz; pclk: 938.50 MHz
Modeline "2560x1440_165.00"  938.50  2560 2792 3072 3584  1440 1443 1448 1588 -hsync +vsync

but adding "modeline 938.50  2560 2792 3072 3584  1440 1443 1448 1588 -hsync +vsync" to Hyprland doesn't work... @vaxerski

**Comment by abmantis** [comment]
Similar issue. Modeline does not seem to work.
