### ISSUE TITLE
windows invisible while switching to a fullscreen workspace

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#3961]
### Hyprland Version

Hyprland, built from branch main at commit a6eba919356b08a2a403a52c1e5e020734411668 dirty (opengl: require introspection on mirroring). Tag: v0.32.3-63-ga6eba919

### Bug or Regression?

Bug

### Description

Switching workspaces with a sliding animation, the windows on the 'old' workspace become invisible during the animation if the 'new' workspace has a fullscreen window.

### How to reproduce

Open a window on a workspace and fullscreen it.
switch to another workspace and open some windows there.
Now while switching to the fullscreen worskpace, the windows on the second workspace are not visible while the fullscreen workspace slides in.

**Comment by Dickby** [comment]
Closing this because https://github.com/hyprwm/Hyprland/issues/4076 is a duplicate of this issue (not the other way around i want to stress)

**Comment by dranull** [comment]
@Dickby Sorry :/, I was looking through issues before posting, but I missed it somehow. At least now it got some attention.

**Comment by Dickby** [comment]
@dranull, don't worry! I was just trying to be funny!
