### ISSUE TITLE
Crash tring to launch AOE l or AOE lV

### ISSUE THREAD

**Issue by JacobFrodermann** [hyprwm/Hyprland#3963]
### Hyprland Version

Hyprland, built from branch main at commit 745b998587fc39db6e3f77caa54074da618cd509

### Bug or Regression?

Bug

### Description

It crashes trying to launch AOE I or lV.
Other Steam games run.
AOE l and lV were installed back to back may that matters.

### How to reproduce

Install AOE l or lV and attempt to start it

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
"stable"

Hyprland received signal 6 (Aborted)

Version: 745b998587fc39db6e3f77caa54074da618cd509
Tag: v0.32.3-62-g745b9985

System info:
	System name: Linux
	Node name: ArchDesktop
	Release: 6.6.2-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000

GPU:
	0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x48) [0x5590bf24db98]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x598) [0x5590bf200d28]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x5590bf17d67c]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7fbb90b6f710]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x8e83c) [0x7fbb90bbf83c]
		??
		??:0
	#5 | /usr/lib/libc.so.6(raise+0x18) [0x7fbb90b6f668]
		??
		??:0
	#6 | /usr/lib/libc.so.6(abort+0xd7) [0x7fbb90b574b8]
		??
		??:0
	#7 | /usr/lib/libc.so.6(+0x263dc) [0x7fbb90b573dc]
		??
		??:0
	#8 | /usr/lib/libc.so.6(+0x36d26) [0x7fbb90b67d26]
		??
		??:0
	#9 | Hyprland(wlr_xwayland_surface_activate+0) [0x5590bf3b5d00]
		??
		??:0
	#10 | Hyprland(+0x320410) [0x5590bf3b7410]
		??
		??:0
	#11 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7fbb91625ae2]
		??
		??:0
	#12 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7fbb916262d7]
		??
		??:0
	#13 | Hyprland(_ZN11CCompositor15startCompositorEv+0x775) [0x5590bf1949b5]
		??
		??:0
	#14 | Hyprland(main+0xace) [0x5590bf1679be]
		??
		??:0
	#15 | /usr/lib/libc.so.6(+0x27cd0) [0x7fbb90b58cd0]
		??
		??:0
	#16 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fbb90b58d8a]
		??
		??:0
	#17 | Hyprland(_start+0x25) [0x5590bf17d505]
		??
		??:0

Log tail:
al for owner 5590c25d2320: 5590c25b59a0 -> 5590c25d2a08 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d2320: 5590c25b5880 -> 5590c25d2868 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25d38d0: 5590c25dd430 -> 5590c25d4020 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d38d0: 5590c25dd440 -> 5590c25d4088 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d38d0: 5590c25dd3b0 -> 5590c25d3a08 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d38d0: 5590c25dd4e0 -> 5590c25d3fb8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d38d0: 5590c25dd3c0 -> 5590c25d3e18 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25d4e80: 5590c25f4600 -> 5590c25d55d0 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d4e80: 5590c25f4610 -> 5590c25d5638 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d4e80: 5590c25f4580 -> 5590c25d4fb8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d4e80: 5590c25f46b0 -> 5590c25d5568 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d4e80: 5590c25f4590 -> 5590c25d53c8 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25d6430: 5590c25b87d0 -> 5590c25d6b80 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d6430: 5590c25b87e0 -> 5590c25d6be8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d6430: 5590c25b8750 -> 5590c25d6568 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d6430: 5590c25b8880 -> 5590c25d6b18 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d6430: 5590c25b8760 -> 5590c25d6978 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25d79e0: 5590c25b8b20 -> 5590c25d8130 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d79e0: 5590c25b8b30 -> 5590c25d8198 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d79e0: 5590c25b8aa0 -> 5590c25d7b18 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d79e0: 5590c25b8bd0 -> 5590c25d80c8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d79e0: 5590c25b8ab0 -> 5590c25d7f28 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25d9be0: 5590c25d9190 -> 5590c25da330 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d9be0: 5590c25d91a0 -> 5590c25da398 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d9be0: 5590c25d9110 -> 5590c25d9d18 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d9be0: 5590c25d9240 -> 5590c25da2c8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25d9be0: 5590c25d9120 -> 5590c25da128 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25e3230: 5590c25e30e0 -> 5590c25e3980 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e3230: 5590c25e30f0 -> 5590c25e39e8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e3230: 5590c25e3060 -> 5590c25e3368 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e3230: 5590c25e3190 -> 5590c25e3918 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e3230: 5590c25e3070 -> 5590c25e3778 (owner: XWayland Window)
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 5590c25e4f40: 5590c25e49e0 -> 5590c25e5690 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e4f40: 5590c25e49f0 -> 5590c25e56f8 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e4f40: 5590c25e4960 -> 5590c25e5078 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e4f40: 5590c25e4a90 -> 5590c25e5628 (owner: XWayland Window)
[LOG] Registered signal for owner 5590c25e4f40: 5590c25e4970 -> 5590c25e5488 (owner: XWayland Window)

**Comment by vaxerski** [comment]
can you try on latest?
