### ISSUE TITLE
workspace_swipe_numbered causes windows to disappear on the first workspace

### ISSUE THREAD

**Issue by BowlBird** [hyprwm/Hyprland#3965]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Having the two configurations:

- workspace_swipe = on
- workspace_swipe_numbered = true

causes windows on specifically the first workspace to disappear (they do not actually close, just visually disappear) when swiping to the second workspace. 

### How to reproduce

1. Open any amount of windows on workspace 1
2. have workspace_swipe = on and workspace_swipe_numbered = true in config file
3. swipe (slower swipes are easier to see, but works with fast ones as well) to the second workspace
4. the windows disappear while swiping. They do come back when swiping back.

**Comment by vaxerski** [comment]
option has since been removed
