### ISSUE TITLE
Blur does not work on higher blur size/pass

### ISSUE THREAD

**Issue by taiwbi** [hyprwm/Hyprland#3967]
### Hyprland Version

Hyprland, built from branch main at commit cd96ceecc551c25631783499bd92c6662c5d3616  (build: remove nv patches (3957))

### Bug or Regression?

Bug

### Description

Blur does not work on high blur size even though I increase passes, in lower resolution it's also not really nice but at least there is something. 

### How to reproduce

I had Fedora 38 and compiled Hyprland for the first time in Fodora 38, then I upadted to Fedora 39 and problem exist in both versions. I even tried to recompile Hyprland to check if it still exist in newer versions and yes, it is still here.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/85298827/f5e80ba4-f91a-43fd-bcf3-4e1aa51dd78f

I've completely transparent the background of terminal to show how it is, It's the same even when opacity of window is not 0

**Comment by vaxerski** [comment]
I believe 80 is just too high

**Comment by taiwbi** [comment]
Even in lower blur size, it's not really good, specially when opacity is not 1 :(

Here opacity of terminal window is exactly 1:

![20231126_20h41m23s_grim](https://github.com/hyprwm/Hyprland/assets/85298827/ceacb055-e198-4e74-a2cf-310b05c4d404)

But when I reduce the opacity a little bit

![20231126_20h42m01s_grim](https://github.com/hyprwm/Hyprland/assets/85298827/de1189bd-c80a-4713-aff3-c4276b300be0)

**Comment by taiwbi** [comment]
Why did I think that means it will blur window background even if it's not transparent? I feel dumb now :/
Thank you so much
