### ISSUE TITLE
Firefox crash when moving cursor between monitors of different scales

### ISSUE THREAD

**Issue by MoetaYuko** [hyprwm/Hyprland#3968]
### Hyprland Version

Hyprland, built from branch main at commit cd96ceecc551c25631783499bd92c6662c5d3616 dirty (build: remove nv patches (3957)). Tag: v0.32.3-75-gcd96ceec  flags: (if any) debug

### Bug or Regression?

Bug

### Description

I have two monitors, one is 4k of **scale 2** on the left and the other is 1080p of **scale 1** on the right:
```
monitor=DP-1, preferred, 0x0, 2
monitor=DP-2, preferred, 1920x0, 1
```

Firefox and other Firefox-based applications (such as Thunderbird) crash when the window is on the left screen, and I move the cursor around its right edge (which is also the boundary between monitors), see the video for details:

https://github.com/hyprwm/Hyprland/assets/5774651/7db691f8-c0f4-4348-8636-4564dfaf47f0

Specifically, the crash happens only if the two monitors are of different scales. For instance, the following two settings are fine:
```
monitor=DP-1, preferred, 0x0, 2
monitor=DP-2, preferred, 1920x0, 2
```
```
monitor=DP-1, preferred, 0x0, 1
monitor=DP-2, preferred, 3840x0, 1
```
but this also leads to a crash:
```
monitor=DP-1, preferred, 0x0, 1
monitor=DP-2, preferred, 3840x0, 2
```

### How to reproduce

1. Enable native wayland of firefox via `env = MOZ_ENABLE_WAYLAND,1`
2. Setup two monitors of different scales
3. Launch Firefox, make sure one edge of its window overlaps with the boundary between monitors
4. Move the cursor around the edge, observe FF crash

**Comment by vaxerski** [comment]
can you launch ff with WAYLAND_DEBUG=1 and attach the output of it when the crash happens?

**Comment by MoetaYuko** [comment]
> can you launch ff with WAYLAND_DEBUG=1 and attach the output of it when the crash happens?

here's stderr w/ that env https://fars.ee/2h6R

pay attention to outputs around `Exiting due to channel error.`

**Comment by vaxerski** [comment]
check the above commit

**Comment by MoetaYuko** [comment]
thanks for the update, issue fixed now.
