### ISSUE TITLE
Telegram Media Viewer always tries to tile even with windowrule.

### ISSUE THREAD

**Issue by sokryptk** [hyprwm/Hyprland#397]
Only setting windowrule to the Telegram client itself gets rid of the problem (somewhat), now both floating.

Steps:
   Open an image on telegram-desktop.

![image](https://user-images.githubusercontent.com/28943200/179982136-2cf16352-ea67-42ac-badb-3c6d61e5abf8.png)

Expected outcome:
  Media Viewer screen has to tile given the windowrule.

hyprctl clients:
![image](https://user-images.githubusercontent.com/28943200/179982264-febb3bce-fd30-4ea8-9651-5224f49274ff.png)

Rule:
`windowrule=float,(.*viewer.*)`

Thanks!

**Comment by Pebor** [comment]
I have my window rule as such `windowrule=float,title:^(Media viewer)$` which works as expected. You have to add the first argument `float`
