### ISSUE TITLE
Double cursor on boot. A cursor is rendered on 0,0 while the real cursor is on another output

### ISSUE THREAD

**Issue by PucklaJ** [hyprwm/Hyprland#3973]
### Hyprland Version

v0.32.3-79-g68e57b7e

### Bug or Regression?

Bug

### Description

This is a small issue that has been occurring all the time since I started using hyprland this year. I have two monitors:
```
Monitor HDMI-A-1 (ID 0):
	1920x1080@60.00000 at 1920x0
	description: BNQ BenQ GL2250H 7CF03165019 (HDMI-A-1)
	make: BNQ
	model: BenQ GL2250H
	serial: 7CF03165019
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 50 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DVI-D-2 (ID 1):
	1920x1080@60.00000 at 0x0
	description: AOC 2370 ABKFB9A000474 (DVI-D-2)
	make: AOC
	model: 2370
	serial: ABKFB9A000474
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 50 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

When I boot my cursor is in the middle of `HDMI-A-1` which is the "primary" monitor, but there is a second "ghost" cursor at 0,0 on `DVI-D-2`. If I move my focus to `DVI-D-2` it disappears. 

### How to reproduce

I don't know if this is specific to my setup. If not follow these steps:
1. Have at least two monitors
2. Have your cursor be at the right one when booting
3. Don't move the cursor
4. Pay attention to the top left corner of the left screen
5. You should see a "ghost" cursor that disappears as soon as you move your focus to the left monitor

**Comment by vaxerski** [comment]
yeah but it goes away when you move it, right?

**Comment by PucklaJ** [comment]
> yeah but it goes away when you move it, right? 

Yes it does. So it's not a fatal issue, but I thought I'd report it, since it ideally should not happen.

**Comment by REALERvolker1** [comment]
can confirm. also happens on my machine

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by PucklaJ** [comment]
@vaxerski On version 0.38.1 it does not happen anymore.

**Comment by vaxerski** [comment]
closing then

**Comment by dsmith48867-coder** [comment]
Mmm, Most recent hyprland, and it is happening to me. Just a ghost cursor on my other monitor, Not that big of deal, Just weird to have stuck mouse over everything on that screen.

**Comment by neksodebe** [comment]
currently experiencing this, but the ghost cursor doesn't go away when i move my mouse over to the other monitor.

**Comment by negativems** [comment]
Have the same problem too, turning off and on the monitor fixed it, but this happens every time I login in.

**Comment by mark-boute** [comment]
> Mmm, Most recent hyprland, and it is happening to me. Just a ghost cursor on my other monitor, Not that big of deal, Just weird to have stuck mouse over everything on that screen.

> currently experiencing this, but the ghost cursor doesn't go away when i move my mouse over to the other monitor.

> Have the same problem too, turning off and on the monitor fixed it, but this happens every time I login in.

Setting cursor.no_hardware_cursors = 0 fixes this for me (running Hyprland on iGPU), it does happen for setting it to 1 or 2.

**Comment by DeltaCream** [comment]
> Setting cursor.no_hardware_cursors = 0 fixes this for me (running Hyprland on iGPU), it does happen for setting it to 1 or 2.

I second this solution, I have this issue surprisingly in 0.53.3, setting it 0 fixed it, but otherwise setting it to 2 (which was the default value) causes the bug,

**Comment by 90th** [comment]
> Have the same problem too, turning off and on the monitor fixed it, but this happens every time I login in.

Same, This seemed to fix my phantom cursor.
Is making `cursor.no_hardware_cursors = 0` the complete fix?


I am on v0.53.3

**Comment by DippamTheFirst** [comment]
>Setting cursor.no_hardware_cursors = 0 fixes this for me (running Hyprland on iGPU), it does happen for setting it to 1 or 2.

hyprland 0.54.2
the issue is still there, and this fixed my issue(i am using igpu)
