### ISSUE TITLE
Hyprland as a systemd user service: immediate core dump

### ISSUE THREAD

**Issue by VTimofeenko** [hyprwm/Hyprland#3978]
### Hyprland Version

Hyprland, built from branch  at commit 745b998587fc39db6e3f77caa54074da618cd509  ().

### Bug or Regression?

Bug

### Description

I am trying to run Hyprland as a user service since I want to let systemd restart user services that depend on Hyprland.

When run from command line as `systemd-cat --identifier hyprland Hyprland`, it works just fine.

Coredump output:
```
                Stack trace of thread 365926:
                #0  0x00007f936d3c4d7c __pthread_kill_implementation (libc.so.6 + 0x8cd7c)
                #1  0x00007f936d3759c6 raise (libc.so.6 + 0x3d9c6)
                #2  0x00007f936d35e8fa abort (libc.so.6 + 0x268fa)
                #3  0x000000000049ef64 _Z25handleUnrecoverableSignali (.Hyprland-wrapped + 0x9ef64)
                #4  0x00007f936d375a70 __restore_rt (libc.so.6 + 0x3da70)
                #5  0x00007f936d3c4d7c __pthread_kill_implementation (libc.so.6 + 0x8cd7c)
                #6  0x00007f936d3759c6 raise (libc.so.6 + 0x3d9c6)
                #7  0x00007f936d35e8fa abort (libc.so.6 + 0x268fa)
                #8  0x00007f936d6acc0b _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0xacc0b)
                #9  0x00007f936d6bc21a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xbc21a)
                #10 0x00007f936d6bc285 _ZSt9terminatev (libstdc++.so.6 + 0xbc285)
                #11 0x00007f936d6bc4d7 __cxa_throw (libstdc++.so.6 + 0xbc4d7)
                #12 0x00000000004618b1 _Z10throwErrorRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold (.Hyprl
and-wrapped + 0x618b1)
                #13 0x00000000004b52fd _ZN11CCompositor10initServerEv (.Hyprland-wrapped + 0xb52fd)
                #14 0x0000000000489f0d main (.Hyprland-wrapped + 0x89f0d)
                #15 0x00007f936d35ffce __libc_start_call_main (libc.so.6 + 0x27fce)
                #16 0x00007f936d360089 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x28089)
                #17 0x000000000049edc5 _start (.Hyprland-wrapped + 0x9edc5)
                
                Stack trace of thread 365931:
                #0  0x00007f936d3bfc96 __futex_abstimed_wait_common (libc.so.6 + 0x87c96)
                #1  0x00007f936d3c2488 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8a488)
                #2  0x000000000058e71d _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN9CWatchdogC4EvEUlvE_EEEEE6_M_runEv (.Hyprland-wrapped + 0x18e71d)
                #3  0x00007f936d6e8683 execute_native_thread_routine (libstdc++.so.6 + 0xe8683)
                #4  0x00007f936d3c3084 start_thread (libc.so.6 + 0x8b084)
                #5  0x00007f936d44560c __clone3 (libc.so.6 + 0x10d60c)
                ELF object binary architecture: AMD x86-64
```

### How to reproduce

1. Add a user service like so:

    ```nix
    { pkgs, lib, config, ... }:
    {
        systemd.user.services.hyprland-run = {
          Unit = {
            Description = "Hyprland wrapper that runs it in systemd user service";
            BindsTo = [ "graphical-session.target" ];
          };
          Service = {
            # As in example user service from Hyprland github repo
            Type = "notify";
            # Get the executable from home manager module
            ExecStart = "${lib.getExe config.wayland.windowManager.hyprland.package}";
            Environment =
              let
                # Stuff that hyprland needs to start
                path = lib.makeBinPath [ pkgs.coreutils-full pkgs.gnugrep ];
              in
              [ "PATH=${path}" ];
          };
          # Install: {} # NOTE: To be run manually
        };
    }
    ```
2. Run `systemctl --user start hyprland-run`

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13470330/hyprland.log)

<details><summary>Systemd logs</summary>
<pre>
Nov 26 21:40:08 uranium systemd[2834]: Starting My hyprland wrapper that runs it in systemd...
Nov 26 21:40:08 uranium Hyprland[365928]: pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
Nov 26 21:40:08 uranium Hyprland[365926]: terminate called after throwing an instance of 'std::runtime_error'
Nov 26 21:40:08 uranium Hyprland[365926]:   what():  wlr_backend_autocreate() failed!
Nov 26 21:40:08 uranium Hyprland[365933]: pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
Nov 26 21:40:09 uranium systemd-coredump[365954]: [🡕] Process 365926 (.Hyprland-wrapp) of user 1000 dumped core.
<then the backtrace>
</pre>
</details> 

<details><summary>Coredumpctl output</summary>
<p>
<pre>
           PID: 365926 (.Hyprland-wrapp)
           UID: 1000 (spacecadet)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: Sun 2023-11-26 21:40:08 PST (30min ago)
  Command Line: /nix/store/kkn5s8d7wfi6m8il261iqc97v56h53h2-hyprland-0.32.3+date=2023-11-24_745b998/bin/Hyprland
    Executable: /nix/store/kkn5s8d7wfi6m8il261iqc97v56h53h2-hyprland-0.32.3+date=2023-11-24_745b998/bin/.Hyprland-wrapped
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/hyprland-run.service
          Unit: user@1000.service
     User Unit: hyprland-run.service
         Slice: user-1000.slice
     Owner UID: 1000 (spacecadet)
       Boot ID: d05ab6abae2c47189e76a59e4710bbbc
    Machine ID: d194f255852f406e8701447b2b99018a
      Hostname: uranium
       Storage: /var/lib/systemd/coredump/core.\x2eHyprland-wrapp.1000.d05ab6abae2c47189e76a59e4710bbbc.365926.1701063608000000.zst (present)
  Size on Disk: 462.6K
       Message: Process 365926 (.Hyprland-wrapp) of user 1000 dumped core.
                
                Module libpcre.so.1 without build-id.
                Module libbrotlicommon.so.1 without build-id.
                Module libgraphite2.so.3 without build-id.
                Module libdatrie.so.1 without build-id.
                Module libselinux.so.1 without build-id.
                Module libpcre2-8.so.0 without build-id.
                Module libgudev-1.0.so.0 without build-id.
                Module libbrotlidec.so.1 without build-id.
                Module libbz2.so.1 without build-id.
                Module libxcb-randr.so.0 without build-id.
                Module libexpat.so.1 without build-id.
                Module libpangoft2-1.0.so.0 without build-id.
                Module libharfbuzz.so.0 without build-id.
                Module libthai.so.0 without build-id.
                Module libfribidi.so.0 without build-id.
                Module libGLX.so.0 without build-id.
                Module libcap.so.2 without build-id.
                Module libXdmcp.so.6 without build-id.
                Module libXau.so.6 without build-id.
                Module libwacom.so.9 without build-id.
                Module libevdev.so.2 without build-id.
                Module libmtdev.so.1 without build-id.
                Module libGLdispatch.so.0 without build-id.
                Module libXrender.so.1 without build-id.
                Module libXext.so.6 without build-id.
                Module libX11.so.6 without build-id.
                Module libfreetype.so.6 without build-id.
                Module libfontconfig.so.1 without build-id.
                Module libpng16.so.16 without build-id.
                Module libz.so.1 without build-id.
                Module libxcb-errors.so.0 without build-id.
                Module libxcb-res.so.0 without build-id.
                Module libxcb-icccm.so.4 without build-id.
                Module libxcb-ewmh.so.2 without build-id.
                Module libxcb-composite.so.0 without build-id.
                Module libxcb-xinput.so.0 without build-id.
                Module libxcb-xfixes.so.0 without build-id.
                Module libxcb-shm.so.0 without build-id.
                Module libxcb-render-util.so.0 without build-id.
                Module libxcb-render.so.0 without build-id.
                Module libxcb-present.so.0 without build-id.
                Module libxcb-dri3.so.0 without build-id.
                Module libliftoff.so.0 without build-id.
                Module libdisplay-info.so.2 without build-id.
                Module libseat.so.1 without build-id.
                Module libudev.so.1 without build-id.
                Module libvulkan.so.1 without build-id.
                Module libGLESv2.so.2 without build-id.
                Module libdrm.so.2 without build-id.
                Module libffi.so.8 without build-id.
                Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module libpangocairo-1.0.so.0 without build-id.
                Module libpango-1.0.so.0 without build-id.
                Module libGL.so.1 without build-id.
                Module libudis86.so.0 without build-id.
                Module libsystemd.so.0 without build-id.
                Module libxcb.so.1 without build-id.
                Module libinput.so.10 without build-id.
                Module libxkbcommon.so.0 without build-id.
                Module libEGL.so.1 without build-id.
                Module libwlroots.so.13 without build-id.
                Module .Hyprland-wrapped without build-id.
                Stack trace of thread 365926:
                #0  0x00007f936d3c4d7c __pthread_kill_implementation (libc.so.6 + 0x8cd7c)
                #1  0x00007f936d3759c6 raise (libc.so.6 + 0x3d9c6)
                #2  0x00007f936d35e8fa abort (libc.so.6 + 0x268fa)
                #3  0x000000000049ef64 _Z25handleUnrecoverableSignali (.Hyprland-wrapped + 0x9ef64)
                #4  0x00007f936d375a70 __restore_rt (libc.so.6 + 0x3da70)
                #5  0x00007f936d3c4d7c __pthread_kill_implementation (libc.so.6 + 0x8cd7c)
                #6  0x00007f936d3759c6 raise (libc.so.6 + 0x3d9c6)
                #7  0x00007f936d35e8fa abort (libc.so.6 + 0x268fa)
                #8  0x00007f936d6acc0b _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0xacc0b)
                #9  0x00007f936d6bc21a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xbc21a)
                #10 0x00007f936d6bc285 _ZSt9terminatev (libstdc++.so.6 + 0xbc285)
                #11 0x00007f936d6bc4d7 __cxa_throw (libstdc++.so.6 + 0xbc4d7)
                #12 0x00000000004618b1 _Z10throwErrorRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold (.Hyprland-wrapped + 0x618b1)
                #13 0x00000000004b52fd _ZN11CCompositor10initServerEv (.Hyprland-wrapped + 0xb52fd)
                #14 0x0000000000489f0d main (.Hyprland-wrapped + 0x89f0d)
                #15 0x00007f936d35ffce __libc_start_call_main (libc.so.6 + 0x27fce)
                #16 0x00007f936d360089 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x28089)
                #17 0x000000000049edc5 _start (.Hyprland-wrapped + 0x9edc5)
                
                Stack trace of thread 365931:
                #0  0x00007f936d3bfc96 __futex_abstimed_wait_common (libc.so.6 + 0x87c96)
                #1  0x00007f936d3c2488 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8a488)
                #2  0x000000000058e71d _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN9CWatchdogC4EvEUlvE_EEEEE6_M_runEv (.Hyprland-wrapped + 0x18e71d)
                #3  0x00007f936d6e8683 execute_native_thread_routine (libstdc++.so.6 + 0xe8683)
                #4  0x00007f936d3c3084 start_thread (libc.so.6 + 0x8b084)
                #5  0x00007f936d44560c __clone3 (libc.so.6 + 0x10d60c)
                ELF object binary architecture: AMD x86-64

</pre>
</p>
</details>

**Comment by vaxerski** [comment]
this is not a hyprland issue. We do not support such launching. Something (maybe you'd know more if you checked the crash report I wonder what those are for) is preventing it from launching

**Comment by VTimofeenko** [comment]
> We do not support such launching.

I would suggest dropping the [example service](https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.service) then. Otherwise users might start having silly ideas.

> Something (maybe you'd know more if you checked the crash report I wonder what those are for) is preventing it from launching

I'd wager a guess: those are for reading. A problem though: it's very hard to read them if one cannot find them. There are no mentions of a crash report in the logs or on the [crashes and bugs page](https://wiki.hyprland.org/Crashes-and-Bugs/).

Strace ultimately helped me to find it in `~/.hyprland`(odd location, but what do I know), and here's the latest one:

[hyprlandCrashReport396255.txt](https://github.com/hyprwm/Hyprland/files/13477898/hyprlandCrashReport396255.txt)

Along with the log:

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13477900/hyprland.log)

Not too much to go on:
```
[CRITICAL] m_sWLRAllocator was NULL!
[CRITICAL] Critical error thrown: wlr_allocator_autocreate() failed!
```

#1212 is not very applicable since I am not using Asahi on a Macbook, it's NixOS on an AMD laptop. `override { legacyRenderer = true; }` produced the same result.

**Comment by VTimofeenko** [comment]
OK, after poring over more strace outputs and reading [swaywm/sway/5160](https://github.com/swaywm/sway/issues/5160) along with [sway systemd-integration article](https://github.com/swaywm/sway/wiki/Systemd-integration) I came up with something that works, but loses some environment variables:

```nix
  systemd.user.services.hyprland-run = {
    Unit = {
      Description = "My hyprland wrapper that runs it in systemd";
      BindsTo = [ "graphical-session.target" ];
    };
    Service = {
      ExecStartPre = "systemctl --user unset-environment WAYLAND_DISPLAY DISPLAY";
      Type = "notify";
      ExecStart = "${lib.getExe config.wayland.windowManager.hyprland.package}";
      # StandardOutput = "journal";
      # StandardError = "journal";
      # Stuff that hyprland needs to start
      Environment =
        let
          path = lib.makeBinPath [ pkgs.coreutils-full pkgs.gnugrep ];
        in
        [ "PATH=${path}:/run/current-system/sw/bin/" ];
    };
    # Install # NOTE: Run manually
  };
```

Probably a better approach would be to:

* Manually override all relevant services with `BindsTo = [ "hyprland-session.target" ]` 
* Restart the hyprland-session.target when starting Hyprland (currently it's just `systemctl --user start`) to clean up whatever services were left after previous Hyprland run.
