### ISSUE TITLE
Floating windows go unresponsive and appear distorted.

### ISSUE THREAD

**Issue by sokryptk** [hyprwm/Hyprland#398]
Clicking settings button -> ![image](https://user-images.githubusercontent.com/28943200/179983218-8f0b10a8-296f-4d83-97c5-5d25ad6ce579.png)

Right-clicking the projects tab -> ![image](https://user-images.githubusercontent.com/28943200/179983250-85762f8d-af23-47c6-ab83-ecceedf425c7.png)

![image](https://user-images.githubusercontent.com/28943200/179986811-6d0eac18-65a2-417f-a8bd-99c365046795.png)

Steps:
-> Click on the follow settings or projects on [planner](https://github.com/alainm23/planner).

Expected outcome:
->  either it should float properly or tile.
 
Noted outcome:
->  distorted UI and menus unclickable. hides when out of focus.

EDIT: Maybe, I'm seeing this issue at other places as well?

![image](https://user-images.githubusercontent.com/28943200/180202019-693c60c0-493b-4085-9062-18748aa61dd5.png)

**Comment by dmadisetti** [comment]
Floating -> Full screen captures this pretty well.

Example, kitty. Note browsers seem to do pretty well though.

![20220721_16h35m47s_grim](https://user-images.githubusercontent.com/2689338/180310828-e95cde52-cc17-48cf-8b03-107207f4d57b.png)
![20220721_16h37m24s_grim](https://user-images.githubusercontent.com/2689338/180310832-ce634765-373c-4307-bbfe-1eda1f9ef7cc.png)

**Comment by vaxerski** [comment]
doesnt happen to me

**Comment by dmadisetti** [comment]
Hmm. After reboot I'm not seeing this. I think I may have had a stale dbus session? I cannot speak to OP's issues- hope I am not adding to noise

**Comment by sokryptk** [comment]
Hmm, it seems to happens on and off in between. Is persistent only in planner whom I have now migrated out of. Closing.
