### ISSUE TITLE
add listen to  foreign_tolelvel_mimimize and foreign_toplevel_maximize request 

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#3984]
### Description

I noticed that some people have a need to minimize the window to taskbar of waybar, I would like to make a plugin for this,waybar is currently supported, but hyprland ignores the foreign_tolelvel_mimimize and foreign_toplevel_maximize request from waybar . so  i can't hook the two handler function to finish it.

can we just add listen the two reuqest?and can do nothing,just allow developer to hook the two handle function.

![image](https://github.com/hyprwm/Hyprland/assets/30348075/cd0882df-804a-4c72-87b7-fb30ed0a1b2f)
![image](https://github.com/hyprwm/Hyprland/assets/30348075/ae6c0604-cc7c-4bb3-af1d-366c201d8fc5)

**Comment by h0tc0d3** [comment]
@DreamMaoMao tiling desktop environments ignore these requests because this complicates the code and requires full support for float windows. For example, in sway, when maximizing windows, the application freezes until you switch to another desktop. 
And hyprland adds force ignoring of maximization requests to the config to eliminate unpredictable behavior.
https://github.com/hyprwm/Hyprland/commit/44accacff934e798b4ce127b009c39004040385a

**Comment by DreamMaoMao** [comment]
I understand, but I just want an empty function that doesn't have to actually send maximization and minimization requests to the client. I just want to hook this empty function, and when waybar sends a minimization request, I will make it not appear on the screen, and when the maximization request comes, I will make it appear on the screen again.

@h0tc0d3

**Comment by DreamMaoMao** [comment]
like this :

https://github.com/hyprwm/Hyprland/assets/30348075/369626a1-eb58-4603-8b5e-7cf33924dd44

@h0tc0d3

**Comment by DreamMaoMao** [comment]
> @DreamMaoMao tiling desktop environments ignore these requests because this complicates the code and requires full support for float windows. For example, in sway, when maximizing windows, the application freezes until you switch to another desktop. And hyprland adds force ignoring of maximization requests to the config to eliminate unpredictable behavior. [44accac](https://github.com/hyprwm/Hyprland/commit/44accacff934e798b4ce127b009c39004040385a) If you want to minimize a window, it must support the system tray. The waybar system tray in hyprland works well.

The taskbar module on waybar works well as a tray for pallet-free apps because it can customize the appearance of the app in various states

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/771f3319-c3e1-4507-854c-9baf60a368eb)
minimize is sent

fwiw you can use the fullscreen thing for fullscreen?

**Comment by DreamMaoMao** [comment]
This is the minimize event initiated by the client. This listener cannot listen to the minimum event from waybar. It needs to listen to foreign_toplevel protocal requests.(used by dunst or waybar ..etc)
