### ISSUE TITLE
Group Configuration Formatting & Crashes

### ISSUE THREAD

**Issue by m-nelly** [hyprwm/Hyprland#3989]
### Hyprland Version

Hyprland, built from branch main at commit 99ca26d4eb84e0071264713902e5b287fcab392e dirty (hooksystem: fix missed log include). Tag: v0.32.3-84-g99ca26d4  flags: (if any) debug

### Bug or Regression?

Bug

## Configuration Formatting Issues  
When writing in the variables for group properties, it does not take the normal json formatting.  
```
group {
    groupbar{
        gradients=false
    }
}
```
Instead, variables must be specified inline `group:groupbar:gradients=false`.  

## Configuration Crashes  
When making modifications to any of the color configurations (not tested with other options) Hyprland will crash on save. I was using NeoVim to make the modifications and had an active group in the workspace I was editing from. 

### How to reproduce

Group windows and make configuration modifications. It should crash when you save the settings or throw an error if you attempt to format in json. 

### Crash reports, logs, images, videos

[hyprlandCrashReport4275.txt](https://github.com/hyprwm/Hyprland/files/13491677/hyprlandCrashReport4275.txt)
[hyprlandCrashReport3595.txt](https://github.com/hyprwm/Hyprland/files/13491678/hyprlandCrashReport3595.txt)
[hyprlandCrashReport526.txt](https://github.com/hyprwm/Hyprland/files/13491679/hyprlandCrashReport526.txt)

**Comment by m-nelly** [comment]
No crash when making modifications without a group active.

**Comment by vaxerski** [comment]
> When writing in the variables for group properties, it does not take the normal json formatting.

your syntax is invalid, I will refer you to the wiki: https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

**Comment by m-nelly** [comment]
That works, but I'm still getting crashes when modifying properties. It looks like they're isolated to having titles rendered. If I turn off title rendering the crashes don't occur when modifying other properties.

**Comment by vaxerski** [comment]
check with e2f18f8c7f95e4094acb94c5a06dc6d75d7fc9c1

**Comment by m-nelly** [comment]
No crashes! Gradients don't update dynamically, but I'm assuming that's intended.

**Comment by m-nelly** [comment]
Let me clarify, removing/adding the gradient doesn't update dynamically. The color will update dynamically without issue.

**Comment by vaxerski** [comment]
toggle another group, open a window in a group, or something to reload them

**Comment by vaxerski** [comment]
I'll consider this solved then
