### ISSUE TITLE
Entering an invalid keyboard layout causes Hyprland to crash

### ISSUE THREAD

**Issue by BeauTheBeau** [hyprwm/Hyprland#3990]
### Hyprland Version

Hyprland, built from branch, at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty ().

### Bug or Regression?

Bug

### Description

When changing `input.kb_layout` to a layout that does not exist, e.g. "en" rather than "gb", Hyprland crashes and does not start.

### How to reproduce

- Set `input.kb_layout` to an invalid layout, eg "en"
- If already running, Hyprland will crash
- When executing `Hyprland`, Hyprland will also crash

### Crash reports, logs, images, videos

[log.txt](https://github.com/hyprwm/Hyprland/files/13492936/bBYfI.txt)

**Comment by romanstingler** [comment]
Is this resolved for you?

**Comment by BeauTheBeau** [comment]
Yep!
