### ISSUE TITLE
Wallpaper flashing

### ISSUE THREAD

**Issue by vcsuwu** [hyprwm/Hyprland#3991]
### Hyprland Version

Hyprland, built from branch main at commit 3fe6162af1904f15fc5526c179c06a48265bdbff dirty (opengl: fix xray modes in introspection checks for ls). Tag: v0.32.3-68-g3fe6162a  flags: (if any) debug

### Bug or Regression?

Bug

### Description

When i tabbing between workspaces, my wallpaper is flashing (happened on both swaybg and hyprpaper). I dont really know is it related to my gpu or hardware but here it is: intel hd 4000 (mesa driver). I watched wiki for some dispatchers for that and stuff, but maybe cuz im blind not finded any, same with already opened issues.

### How to reproduce

Just open some fullscreen,0 window and try to tab between it and other non fullscreen apps, it will flash your wallpaper in that case. For tabbing i was using that allow_workspace_cycles and workspace,previous bind. Hope i described this issue normally, doing it first time :D (animations is turned off)

EDIT: happens on both fullscreen 0 and fullscreen 1 (and on every fullscreen app)

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/142719620/8e98df7a-703f-4c08-b8c6-19f408005c6f

**Comment by ByyLafe** [comment]
Same problem here with my nvidia card...sadly

**Comment by xircon** [comment]
Same on all versions except 0.30.0-1.  EndeavourOS,  6.6.3 kernel.

Occurs on all -git versions and all nVidia versions, currently running non-nVidia version.

Lenovo Legion AMD/RTX3070.

**Comment by vcsuwu** [comment]
> Same problem here with my nvidia card...sadly
> 
> Edit : In my case, I'm on Fedora 39 with kernel 6.6.2. And I'm having flashes.
> 
> By booting on the older 6.5.12 kernel, I no longer have these problems...

sorry for not saying a lot here. tbh error like this happens on all wm's for me (bspwm with picom, and hyprland)
idk the reason behind that but maybe its really kernel related smh. If it will ever be fixed pls ping
