### ISSUE TITLE
Touchdevice { ... } closes input section along itself in config

### ISSUE THREAD

**Issue by engibengi** [hyprwm/Hyprland#3992]
### Hyprland Version

0.32.3-85-ge2f18f8c

### Bug or Regression?

Bug

### Description

In config, while in input section, closing the nested touchdevice section exits the input section too, giving error for any config param set after it.

### How to reproduce

NB: I source a file containing variables from outside hypr.conf!

In a variables file set:
```
input {
       touchdevice {
                    transform = 1
       }
       follow_mouse = 2
}
```
Result:
`Error setting value <2> for field <follow_mouse>: No such field`
This error can be reproduced also without variables inside touchdevice { ... }

**Comment by vaxerski** [comment]
zum glück bin ich verrückt
