### ISSUE TITLE
Hyprland regression on 7a0a5666d565a3ef892a7ab433a5007dd1cc72dd crash on launch

### ISSUE THREAD

**Issue by Evangelospro** [hyprwm/Hyprland#3993]
### Hyprland Version

Hyprland, built from branch HEAD at commit 1778fb77e20a7ff0c9fc20bb139b2e63fa41c7ef dirty (functionhooks: throw an exception on unsupported %rip usage).

### Bug or Regression?

Regression

### Description

Hyprland crashes on launch with no apparent error in logs. I have git bisected and it first appears on commit 7a0a5666d565a3ef892a7ab433a5007dd1cc72dd, the exact previous commit(1778fb77e20a7ff0c9fc20bb139b2e63fa41c7ef) launches successfully

### How to reproduce

Build the after the faulty commit?

### Crash reports, logs, images, videos

[faulty.log](https://github.com/hyprwm/Hyprland/files/13497505/hyprland.log)
[hyprlandCrashReport22186.txt](https://github.com/hyprwm/Hyprland/files/13497526/hyprlandCrashReport22186.txt)
[working.log](https://github.com/hyprwm/Hyprland/files/13497519/hyprland.log)

**Comment by Evangelospro** [comment]
Ok update: seems to be the plugin i use `split-monitor-workspaces` because without it latest commit, loads. Idk if it helps but loading the plugin after Hyprland launches works perfectly, on the latest commit as well...

**Comment by Omrigan** [comment]
Same as #3985?

**Comment by Evangelospro** [comment]
Hmm seems like it, Hyprland plugin system broken?

**Comment by marrobHD** [comment]
Same issue.
Plugins: hyprbars (Vaxry) 1.0
[hyprlandCrashReport52722.txt](https://github.com/hyprwm/Hyprland/files/13499667/hyprlandCrashReport52722.txt)

**Comment by vaxerski** [comment]
dupe #3985
