### ISSUE TITLE
Toggle window opacity via keyboard shortcut

### ISSUE THREAD

**Issue by japrogramer** [hyprwm/Hyprland#400]
Sometimes my default window rule for having the window opacity set makes
seeing the contents of the window difficult to see depending on the wallpaper.

I would like to be able to map a keyboard binding that would allow me to toggle the window opacity between fully opaque
and whatever opacity would be assign to that window 
if it was just opening.

**Comment by vaxerski** [comment]
added in 9dd17a4be6a719ab0cc501f63cf07cfd066f3ef8

`toggleopaque` dispatcher
