### ISSUE TITLE
`grim` no longer works 

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#4001]
### Hyprland Version

v0.32.3-91-g776f9446

### Bug or Regression?

Regression

### Description

https://github.com/hyprwm/Hyprland/blob/main/src/protocols/Screencopy.cpp#L446
I guess we have an answer :)

### How to reproduce

1. Run `grim`
2. It fails with `failed to copy output eDP-1`

**Comment by vaxerski** [comment]
fuck

**Comment by vaxerski** [comment]
oops

**Comment by q234rty** [comment]
Seems to work for me now.

**Comment by vaxerski** [comment]
:)
