### ISSUE TITLE
crash after recovering from unsafe state

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#4006]
### Hyprland Version

29970228c5f71f417b0a3e1b4851d9430ed095dd

### Bug or Regression?

Regression

### Description

Monitor goes to sleep, hyprland crashes when it turns back on.

### How to reproduce

- Turn off monitor
- Turn it back on

### Crash reports, logs, images, videos

[hyprlandCrashReport190927.txt](https://github.com/hyprwm/Hyprland/files/13513961/hyprlandCrashReport190927.txt)

**Comment by vaxerski** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4471

**Comment by vaxerski** [comment]
0a4c4da5f0dde3a24ef8c64aa65a9d21fe074370
