### ISSUE TITLE
mouseAxis Event issue

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#4008]
### Hyprland Version

Hyprland, built from branch main at commit 29970228c5f71f417b0a3e1b4851d9430ed095dd dirty (nix: override libdrm to use newer version (4003)). Tag: v0.32.3-95-g29970228

### Bug or Regression?

Bug

### Description

```
static void testHook(void* self, SCallbackInfo &info, std::any data)
{
//do something
}    

//both works
HyprlandAPI::registerCallbackDynamic(PHANDLE, "mouseMove",[&](void* self, SCallbackInfo& info, std::any data) { testHook(self, info, data); });
HyprlandAPI::registerCallbackDynamic(PHANDLE, "mouseButton", [&](void* self, SCallbackInfo& info, std::any data) { testHook(self, info, data); });

//not working with mouseAxis event, not calling the testHook while using the mouse wheel 
HyprlandAPI::registerCallbackDynamic(PHANDLE, "mouseAxis", [&](void* self, SCallbackInfo& info, std::any data) { testHook(self, info, data); });


```

Am I doing something wrong or is this event not working with HyprlandAPI ?

### How to reproduce

try the code

**Comment by vaxerski** [comment]
it doesn't exist: https://wiki.hyprland.org/Plugins/Development/Event-list/

**Comment by killown** [comment]
Do you have any plan to implement axis and keypress events for plugins?
