### ISSUE TITLE
Switching workspaces drops mouse-dragged window

### ISSUE THREAD

**Issue by Monopoly9569** [hyprwm/Hyprland#4009]
### Hyprland Version

Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3). Tag: v0.32.3  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Moving a window with a mouse fails when switching workspaces via keyboard binds; the window is dropped at the previous workspace. Works when switching with mouse wheel binds from `/example/hyprland.conf`, but not with keyboard binds.

### How to reproduce

Use `/example/hyprland.conf` and try switching workspaces while dragging a terminal window with a mouse.

**Comment by mustardfrog** [comment]
I think that is the expected result.

**Comment by vaxerski** [comment]
dupe #988
