### ISSUE TITLE
[Master Stack] Cyclenext doesn't take into account order of stack

### ISSUE THREAD

**Issue by mwglen** [hyprwm/Hyprland#401]
**Steps to Reproduce:**
1. Use `layout=master` in `hyprland.conf`.
2. Create multiple windows
3. Move windows
4. Use `cyclenext` command

**Expected Outcome:**
`cyclenext` traverses from the master window, down the stack, and then returns to the master window.

**Noted Outcome:**
`cyclenext` traverses in the order that the windows were created

**Comment by vaxerski** [comment]
that's the intended cyclenext behaviour though. It's called cyclenext, not cyclenicelyonmaster. you can still move freely with movefocus l/r/u/d

**Comment by mwglen** [comment]
Can I create a feature request/issue for a command with this behavior? The default behavior of the mod-H and mod-L keys in DWM and XMonad is to cycle through windows as in my "Expected Outcome:" section.

Using "movefocus u" and "movefocus d" ignores the master window.
