### ISSUE TITLE
Keypress Event issue

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#4016]
### Hyprland Version

Hyprland, built from branch main at commit 8440a30231ea41a6b1dacc60a28837b265a6efec dirty (input: fix overzealous mouse capture on resize_on_border (4010)). Tag: v0.32.3-101-g8440a302

### Bug or Regression?

Bug

### Description

using a code like this 
```
static void keyPressHook(void* self, SCallbackInfo &info, std::any data)
{
     SKeyboard *pKeyboard = std::any_cast<SKeyboard *>(data);
}

 HyprlandAPI::registerCallbackDynamic(PHANDLE, "keyPress", [&](void* self, SCallbackInfo& info, std::any data) { keyPressHook(self, info, data); });
```

will crash the plugin when using keyPress event, plugin works until a keypress is detected, the event works fine while not using those codes
 
this
```
wlr_keyboard_key_event *e = std::any_cast<wlr_keyboard_key_event *>(self);
```
this
```
 SKeyboard *pKeyboard = std::any_cast<SKeyboard *>(data);
```
and this  for mouseAxis event too
```
wlr_pointer_axis_event *e = std::any_cast<wlr_pointer_axis_event *>(self)
```

just one of those lines is needed to crash a plugin, any clue?

### How to reproduce

trying the code

**Comment by vaxerski** [comment]
well stdlib is throwing `std::bad_any_cast` because you didn't read what `data` is passing: https://wiki.hyprland.org/Plugins/Development/Event-list/

```cpp
const auto DATA = std::any_cast<std::unordered_map<std::string, std::any>>(data);
const auto PKEYBOARD = std::any_cast<SKeyboard*>(DATA["keyboard"]);
```
