### ISSUE TITLE
Unknown io error crashes screenshot tools(grim, watershot, wayshot) and swaylock

### ISSUE THREAD

**Issue by awarewen** [hyprwm/Hyprland#4019]
### Hyprland Version

Hyprland, built from branch main at commit 8440a30231ea41a6b1dacc60a28837b265a6efec dirty (input: fix overzealous mouse capture on resize_on_border (4010)). Tag: v0.32.3-101-g8440a302

### Bug or Regression?

Bug

### Description

This problem occurs when using screenshot-related tools after updating to the latest.

### How to reproduce

Runs any screenshot-related tools

### Crash reports, logs, images, videos

❯ hyprctl version
Hyprland, built from branch main at commit 8440a30231ea41a6b1dacc60a28837b265a6efec dirty (input: fix overzealous mouse capture on resize_on_border (4010)).
Tag: v0.32.3-101-g8440a302

flags: (if any)
debug

❯ swaylock
proxy 0x561efba225e0 already has listener
proxy 0x561efba21eb0 already has listener
[destroyed object]: error 0: Unsupported format
^C
❯ watershot --copy -s | satty --filename -
thread 'main' panicked at 'Failed to parse grim image!: IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', src/runtime_data.rs:91:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Unrecognized image file format
Error: Unrecognized image file format
❯ grim -g "$(slurp)" -
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
❯ wayshot -c -s "$(slurp)" --stdout | satty --filename -
Error: Unrecognized image file format
Error: Unrecognized image file format

**Comment by awarewen** [comment]
> can't repro. Can I get your config?
[hypr.zip](https://github.com/hyprwm/Hyprland/files/13530121/hypr.zip)
Yep. thanks for help.

**Comment by vaxerski** [comment]
got it

**Comment by awarewen** [comment]
> got it

Hyprland, built from branch main at commit 3caaa483d4bf8f18f62f8a8f03a0922ea8a4cb7e dirty (configmgr: fix parsing of touchdevice groups).
Tag: v0.32.3-86-g3caaa483

flags: (if any)
debug

---
v0.32.3-86-g3caaa483 anything works fine, (screenshot and swaylock)
