### ISSUE TITLE
[Master Stack] Support multiple windows in master pane of master/stack layout

### ISSUE THREAD

**Issue by mwglen** [hyprwm/Hyprland#402]
XMonad has a feature where you can increment/decrement the number of windows that are on the left pane in the master/stack layout. This gives extra flexibility to the layout.

Supporting this in Hyprland would require adding two extra commands: one to increment and one to decrement the count (or one command with a parameter). If the count goes to zero, the left pane vanishes and is replaced by an expanded stack.

**Comment by vaxerski** [comment]
added in c545ab4993f3cb06d68a6637d0088efaf2d00a01

haven't tested it super heavily, but from my basic tests it does work as it should.

layout messages `addmaster` and `removemaster`

Please note hyprland will not let the slave side be empty, ever. So, if you remove the last slave with 3 masters, the last master will be moved to the slaves.

**Comment by OopsYao** [comment]
> added in [c545ab4](https://github.com/hyprwm/Hyprland/commit/c545ab4993f3cb06d68a6637d0088efaf2d00a01)
> 
> haven't tested it super heavily, but from my basic tests it does work as it should.
> 
> layout messages `addmaster` and `removemaster`
> 
> Please note hyprland will not let the slave side be empty, ever. So, if you remove the last slave with 3 masters, the last master will be moved to the slaves.
> 
> Sorry for the long wait!

Hi @vaxerski, is there any reason why empty slave side not allowed, can we add an option about this? I find this feature useful especially sometimes when I just want several windows split evenly as masters without slaves.

**Comment by vaxerski** [comment]
I don't use master, if you believe it's useful you can make a MR.
