### ISSUE TITLE
Inverted colors in screenshots, but not visually or in recordings

### ISSUE THREAD

**Issue by REALERvolker1** [hyprwm/Hyprland#4023]
### Hyprland Version

6e8b9ef7d8aa53247d5122b6641b9afa0df798df

### Bug or Regression?

Regression

### Description

I updated hyprland-git today, and now screenshot colors are inverted. This bug also happens with video captured through pipewire and xdg-desktop-portal-hyprland. However, the colors on my monitor appear just fine and are not inverted to my eyes. I would also like to add that I am running Hyprland on my intel iGPU, not my Nvidia dGPU.

### How to reproduce

1. Run Hyprland
2. take a screenshot (eg: `grim -g "$(slurp)" - | swappy -f -`)
3. Record your screen using a capture tool that isn't OBS studio (eg: Kooha)
4. view your screenshot and screen recording

### Crash reports, logs, images, videos

Fullscreen image
![image](https://github.com/hyprwm/Hyprland/assets/73304952/63b6b2ea-89b3-48b8-b2c4-099e9a3b015f)

Screenshot of a screenshot
![image](https://github.com/hyprwm/Hyprland/assets/73304952/c4e2e49b-3681-4b87-8171-27540a197d3e)

**Comment by REALERvolker1** [comment]
🥺
![image](https://github.com/hyprwm/Hyprland/assets/73304952/5e2bd9d0-b80b-4b01-8ba3-a35f94bb9ebd)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13533328/patch.txt)
?

**Comment by tchofy** [comment]
Still reproducible after applying the patch;

**Comment by vaxerski** [comment]
wait this is only nvidia?

**Comment by salimp2009** [comment]
I had the same issue . it happened after todays update. last week it was working. I am on Nvidia too but nvidia drivers did not get updated this week. using hyprland-git, nvidia-dkms 545.29.06-1

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13536534/patch.txt)
?

**Comment by salimp2009** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/46407603/33146d9e-690f-4b2d-8db1-674dead1b6e3)

original color 
![image](https://github.com/hyprwm/Hyprland/assets/46407603/9a58db02-0d04-4c45-aed6-dec487651951)

**Comment by vaxerski** [comment]
yes can you try the patch I posted

**Comment by salimp2009** [comment]
i did not build from source. Can i use with the pkgbuild of hyprland-git cause it does not have a patch ? not sure how to do it

**Comment by tchofy** [comment]
Can confirm the patch works.

**Comment by salimp2009** [comment]
i will try it once my mirror gets updated. Thnks :)

**Comment by salimp2009** [comment]
just did the update and it works. thank you

**Comment by REALERvolker1** [comment]
I don't exactly know what you did but it's fixed on commit 80b9b21f9f24b6e8db2fc6f7705cd124f436ffba
