### ISSUE TITLE
Pen pressure not detected by Blender on Hyprland

### ISSUE THREAD

**Issue by Demigirlboss** [hyprwm/Hyprland#4024]
### Hyprland Version

Hyprland, built from branch main at commit 29970228c5f71f417b0a3e1b4851d9430ed095dd dirty (nix: override libdrm to use newer version (4003)). Tag: v0.32.3-95-g29970228

### Bug or Regression?

Bug

### Description

**System Information**
Operating system: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38 64 Bits, WAYLAND UI
Graphics card: AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1) AMD 4.6 (Core Profile) Mesa 23.2.1-arch1.2

**Short description of error**
[Originally posted [here](https://projects.blender.org/blender/blender/issues/114369)] Blender does not detect pen pressure for brush intensity in the Hyprland compositor. It only detects pen pressure for brush radius. It detects it in KDE Plasma running on Wayland, and on KDE Plasma or Budgie running on X11. Issue presents in sculpting and texture painting. Issue does not present in Krita or in [this online pen pressure test](https://openprocessing.org/sketch/591905). OpenTabletDriver debugger detects pen pressure levels without issue. Issue persists with both OpenTabletDriver and Linux kernel driver. Tablet is Wacom CTL-672.

### How to reproduce

**Exact steps for others to reproduce the error**
Attempt to perform any sort of sculpting or texture painting task which employs pen pressure while using the Hyprland Wayland compositor with [this configuration.](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/install.sh) Unknown if issue persists in other configurations as well. No pen pressure will be detected. Essentially, identical to using a mouse.

### Crash reports, logs, images, videos

[system-info.txt](https://github.com/hyprwm/Hyprland/files/13533558/system-info.txt)

**Comment by vaxerski** [comment]
isn't this a blender issue then?

I don't have any tablets

**Comment by Demigirlboss** [comment]
It might be seen as a Blender issue, given that it only occurs in Blender. But it might also be seen as a Hyprland issue, given that it only occurs on Hyprland, and not on other compositors, like Weston. As such, I have filed reports on both relevant trackers. If nothing else, other people facing the issue can feel a little less insane than I did looking for reports of the issue and finding none.

**Comment by vaxerski** [comment]
does it work on sway-git?

**Comment by Demigirlboss** [comment]
I can't seem to get sway-git to play nice with Hyprland and Plasma, so I'm unable to test this. However, the following was commented by maintainer Campbell Barton on the Blender bug tracker report for this issue:

> This bug should be reported to hyperland, checking their tablet support and it looks to be incomplete, as of 9ca0c7d814d6039450ff0341556faa1ce9b37e82 the tablet time-stamps are always zero and the radius scale is erratic. There are also TODO's noted in src/managers/input/Tablets.cpp that hint that this is work in progress.

**Comment by calebaden** [comment]
I also have this issue and just tested with Sway 1.8.1-4 from the arch repo (non git) and it works as expected. Using pen pressure correctly varies the strength of the brush in sculpt mode on Blender 4.0.2-4. 
In Hyprland 0.33.1-2, the pen pressure does not work on the strength attribute at all (always at maximum strength) and while the radius does work, it is not as smooth/gradual as I would expect. 
Using pen pressure on Krita with Hyprland works just fine.

**Comment by vaxerski** [comment]
drawing tablet support on hyprland is spotty indeed, I don't have a tablet to test and thus rarely focus on the code.

I can check the timestamps and radius code tho, remind me tomorrow please

**Comment by Demigirlboss** [comment]
I just logged on to GitHub for an unrelated tablet issue and saw this, so I guess here's the reminder to check timestamps and radius code!

**Comment by DNACFRA** [comment]
Hey, did some (maybe helpful)testing with Blender ran over Wine or Steams Proton runtime
I want to start with the info that both are probably not really usable, as they crash on things like adding a Subdivision Modifier
But: 
- Steams Proton running Blender also doesn't have working pressure like hyprland
- Wine works completely with pressure and even fixing the drag Problems, that are referenced  in  #1024 when using a pen, the mouse drag does not work

Notes: 
- This was done with factory settings Blender, so there might be a difference in how Steams Proton and Wine use the Windows Tablet API(Windows Ink vs Wintab).
- No manual changes were done to Wine, maybe it can be made usable as duct-tape-solution 

(Hope this helps)

**Comment by Izaird** [comment]
A little update on this if I hold and drag with the pen it doesn't work but if I then move the mouse a little bit while still holding it works as it should

https://github.com/hyprwm/Hyprland/assets/31055847/b9bc1d4a-f8fc-40fe-b4f3-507289905b16

**Comment by Agent00Ming** [comment]
Please check latest git. This works for me after #5902
