### ISSUE TITLE
Hyprland fails to start every time and receives signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by Cg1340** [hyprwm/Hyprland#4026]
### Hyprland Version

0.30.0

### Bug or Regression?

Bug

### Description

This is the first time I have installed and used Hyprland. But once Hyprland was launched, it was accompanied by long stutters. During this time, the keyboard was unresponsive, but when I pressed the left mouse button, Hyprland quickly crashed.

### How to reproduce

1. Boot system
2. Go into tty
3. run ``Hyprland``
4. Click the left mouse button
5. Crashed

### Crash reports, logs, images, videos

[coredumpctl output.txt](https://github.com/hyprwm/Hyprland/files/13536200/coredumpctl.output.txt)
[hyprlandCrashReport8455.txt](https://github.com/hyprwm/Hyprland/files/13536201/hyprlandCrashReport8455.txt)

https://github.com/hyprwm/Hyprland/assets/88421542/c2d51b4a-0d7d-408c-b5ff-165e23b5a636

https://github.com/hyprwm/Hyprland/assets/88421542/8cd96811-f279-40a9-9202-863b7e6bd2ab

**Comment by Cg1340** [comment]
And two videos:

https://github.com/hyprwm/Hyprland/assets/88421542/e1972265-9286-4860-b486-dc10fbedd3c5

https://github.com/hyprwm/Hyprland/assets/88421542/d4823f6e-2738-4f46-b995-80c13b876fee

**Comment by Cg1340** [comment]
But I can run it successfully on the KDE desktop???

**Comment by vaxerski** [comment]
you're on a very outdated version, please check on -git.

**Comment by re-masashi** [comment]
Happens here as well. All similar issues are related to NVIDIA graphics drivers, but in my case, it isn't.

```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Maybe you should try dusting your PC in the meantime?

Hyprland received signal 11 (Segmentation fault)

Version: 79f3888b4bd9796850189ed3e151a6c831e6faae
Tag: v0.33.1-68-g79f3888b

System info:
        System name: Linux
        Node name: 0xwaifu
        Release: 6.6.7-arch1-1
        Version: #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000

GPU:
        00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])


os-release:
        NAME="EndeavourOS"
        PRETTY_NAME="EndeavourOS"
        ID="endeavouros"
        ID_LIKE="arch"
        BUILD_ID="2023.05.28"
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://endeavouros.com"
        DOCUMENTATION_URL="https://discovery.endeavouros.com"
        SUPPORT_URL="https://forum.endeavouros.com"
        BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
        PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
        LOGO="endeavouros"
        
```

### Backtrace
```
        #0 | Hyprland(_Z12getBacktracev+0x62) [0x55e4a0536422]
                ??
                ??:0
        #1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x64d) [0x55e4a050282d]
                ??
                ??:0
        #2 | Hyprland(_Z25handleUnrecoverableSignali+0x48) [0x55e4a0497fb8]
                ??
                ??:0
        #3 | /usr/lib/libc.so.6(+0x3e710) [0x7f6420d6f710]
                ??
                ??:0
        #4 | /usr/lib/libwlroots.so.13032(+0x36bfa) [0x7f64216edbfa]
                ??
                ??:0
        #5 | /usr/lib/libwlroots.so.13032(+0x3af8f) [0x7f64216f1f8f]
                ??
                ??:0
        #6 | /usr/lib/libwlroots.so.13032(wlr_renderer_begin_with_buffer+0x24) [0x7f64216ebc34]
                ??
                ??:0
        #7 | /usr/lib/libwlroots.so.13032(+0x53e0c) [0x7f642170ae0c]
                ??
                ??:0
        #8 | /usr/lib/libwlroots.so.13032(+0x5decd) [0x7f6421714ecd]
                ??
                ??:0
        #9 | /usr/lib/libwlroots.so.13032(wlr_output_cursor_set_buffer+0xee) [0x7f64217151de]
                ??
                ??:0
        #10 | /usr/lib/libwlroots.so.13032(+0x78e33) [0x7f642172fe33]
                ??
                ??:0
        #11 | /usr/lib/libwlroots.so.13032(wlr_cursor_set_xcursor+0x68) [0x7f64217305b8]
                ??
                ??:0
        #12 | Hyprland(_ZN11CCompositor15startCompositorEv+0x7f7) [0x55e4a049cef7]
                ??
                ??:0
        #13 | Hyprland(main+0x818) [0x55e4a047ff88]
                ??
                ??:0
        #14 | /usr/lib/libc.so.6(+0x27cd0) [0x7f6420d58cd0]
                ??
                ??:0
        #15 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f6420d58d8a]
                ??
                ??:0
        #16 | Hyprland(_start+0x25) [0x55e4a0495575]
                ??
                ??:0
```

**Comment by Cg1340** [comment]
So it is not the NVIDIA's graphics drivers' problem?

**Comment by NotAShelf** [comment]
In the trace above, debug symbols are omitted. Try building with debug (you'll have to build from source for that) and provide the trace that's generated by that version

**Comment by re-masashi** [comment]
> So perhaps it is not the NVIDIA's graphics drivers' problem?

@Cg1340 it makes sense. Since, my device uses Intel Graphics.

**Comment by vaxerski** [comment]
stale, closing

**Comment by re-masashi** [comment]
> stale, closing

any updates?
I still cannot get Hyprland on my ThinkPad. It works fine on modern laptops though.

**Comment by Cg1340** [comment]
_Now Hyprland 0.44.1._

I've found that when I delete something like 'env = AQ_DRM_DEVICES,/dev/dri/card0' in the config, the bug goes away, and if I add this line, the bug recurs stably.
