### ISSUE TITLE
Hyprland not detecting my 2nd screen on new versions

### ISSUE THREAD

**Issue by Exatio** [hyprwm/Hyprland#4030]
### Hyprland Version

0.32.3

### Bug or Regression?

Bug

### Description

`hyprctl monitors` doesn't detect my 2nd screen on the 0.32.3 version and the AUR hyprland-git package.
For some reason, in 0.30.0 there is no problem at all

### How to reproduce

Upgrade Hyprland from 0.30 to 0.32

**Comment by vaxerski** [comment]
can you git bisect this?

**Comment by Exatio** [comment]
okay, so I tried to git bisect, latest version builds fine but commit 92311d26 can't compile with `make all && sudo make install `: I get a fatal error: wlr/types/wlr_idle.h no such file or directory

**Comment by vaxerski** [comment]
you need to `git reset --hard --recurse-submodules` between every step

**Comment by Exatio** [comment]
Thanks for this response.
After git bisecting this, this is the commit that breaks the 2nd monitor :
```
df00727310b8a428a4977878cdf5597373a2ad31 is the first bad commit
commit df00727310b8a428a4977878cdf5597373a2ad31
Author: Vaxry <vaxry@vaxry.net>
Date:   Wed Oct 25 00:27:16 2023 +0100

    deps: update wlroots

 src/Compositor.cpp               | 3 ---
 src/Compositor.hpp               | 1 -
 src/events/Monitors.cpp          | 2 +-
 src/includes.hpp                 | 1 -
 src/protocols/Screencopy.cpp     | 4 ++--
 src/protocols/ToplevelExport.cpp | 2 +-
 subprojects/wlroots              | 2 +-
 7 files changed, 5 insertions(+), 10 deletions(-)
```

**Comment by vaxerski** [comment]
exactly what I thought. This is a wlroots issue, not a hyprland one. Should be reported upstream

**Comment by Exatio** [comment]
I searched for the wlroots logs in order to provide it on their gitlab but I can't find it, could anyone tell me their location ?

**Comment by webknjaz** [comment]
@Exatio does it break like this https://github.com/hyprwm/Hyprland/issues/2364?

**Comment by Exatio** [comment]
I dont think so, since I dont even have the monitor in the hyprctl monitors list

**Comment by Exatio** [comment]
For any future references, deleting the line env = WLR_RENDER,vulkan in my hyprland configuration did the trick.
Although I don't understand why I could use vulkan before and not anymore
