### ISSUE TITLE
Vram leak on open/close windows and layersurfaces

### ISSUE THREAD

**Issue by tchofy** [hyprwm/Hyprland#4036]
### Hyprland Version

e496b0f250139b572307d048f3189aa6dde72f18

### Bug or Regression?

Bug

### Description

First of all, it's nvidia, so might be isolated case. Whenever a window or layersurface is closed, there's a high chance vram consumption will go up by 10mb and such memory won't be freed, eventually consuming all vram and making the system unusable. My record so far was 2gb of vram being used by hyprland. Also managed to reproduce using default config.

### How to reproduce

Open nvtop
Spam open/close window or layersurface
Watch vram usage spike (expected)
Watch vram usage stay the same even though all windows were closed

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/64620317/653854d7-8242-4e54-b7aa-747637250b7f

**Comment by jlamprou** [comment]
+1 same problem on nvidia on arch branch of hyprland

**Comment by vaxerski** [comment]
repro'd, above should fix. Lmk. Thanks for spotting!

**Comment by tchofy** [comment]
Aye, that works, thanks!
