### ISSUE TITLE
Grimblast Selecting Window Behind Fullscreen

### ISSUE THREAD

**Issue by TZProgrammer** [hyprwm/Hyprland#4038]
### Hyprland Version

Hyprland, built from branch main at commit 68783d904d850df65887adb1bab7eff59943c1ac dirty (screencopy: use buffer format for glReadPixels). Tag: v0.32.3-112-g68783d90  flags: (if any)

### Bug or Regression?

Bug

### Description

When there are two or more windows on a screen, even after setting one of those to fullscreen, grimblast still highlights and let's me select the other panes.

If I try to take a screenshot of those, nothing comes out, which makes sense since they are occluded, but I do not think grimblast should be able to select those windows in the first place.

### How to reproduce

In a screen, create at least two windows. Set one of those windows to fullscreen. Then, use grimblast and move your mouse on top of where the non-fullscreen panel should be. The window should be highlighted by grimblast.

**Comment by wxlyyy** [comment]
Can be reproduced
