### ISSUE TITLE
Artefacts and blur problems with wallpapers (?) and layers (?)

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/Hyprland#4041]
### Hyprland Version

Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3). Tag: v0.32.3  flags: (if any)

### Bug or Regression?

Bug

### Description

There are artefacts and blur problems with wallpapers (?) and layers (?).

1. When starting Hyprland with my config I have blurry wallpapers, but when the first window is displayed, everything gets back to normal and works as it should. See screenshorts with a night city.
2. When nwg-bar is displayed/hidden, there are artefacts remaining on the wallpaper. Artefacts disappear when the first window is displayed.  See screenshots with a parrot.

### How to reproduce

I don't know how to reproduce it. I just have it when running my config. It seems that using programs that add other layers (waybar, nwg-bar etc) aggrevates the problem.

I didn't notice the problem on Hyprland ver. 0.30.0

### Crash reports, logs, images, videos

![wp1_1](https://github.com/hyprwm/Hyprland/assets/29972256/021f298d-3f79-4446-ba35-128e80c58b95)
![wp1_2](https://github.com/hyprwm/Hyprland/assets/29972256/e819d702-9b91-4311-8941-25f250f93195)
![wp2_1](https://github.com/hyprwm/Hyprland/assets/29972256/13202d99-3963-4aee-b17b-a94dd0341fa1)
![wp2_2](https://github.com/hyprwm/Hyprland/assets/29972256/89edea51-e8e5-4d14-9b41-2115d301c3ec)
![wp2_3](https://github.com/hyprwm/Hyprland/assets/29972256/88240828-f986-4783-abaf-fb5d92d98c85)

**Comment by vaxerski** [comment]
certainly odd, what do you use for your wallpapers?

**Comment by akdevservices** [comment]
> certainly odd, what do you use for your wallpapers?

`swaybg -m fill -i myimg.jpg`

But the problems persist even with `force_default_wallpaper = 1`, without using any third-party wallpaper tools.

It seems that there are two different bugs. I just found out that the bug with blurry wallpapers depends on `animations::enabled`. If animations are disabled `animations::enabled = false`, it goes away.

**Comment by akdevservices** [comment]
just installed v0.33.0, the issues seem to be fixed, no artefacts or blurry wallpapers even with enabled animation.
