### ISSUE TITLE
Blank Spots in Screenshot/Screencapture when Capturing with Certain Apps

### ISSUE THREAD

**Issue by FlyingButteryTuna** [hyprwm/Hyprland#4042]
### Hyprland Version

3bb9c7c5cf4f2ee30bf821501499f2308d616f94

### Bug or Regression?

Bug

### Description

The problem was briefly mentioned in issue #4029: capturing an area with certain apps results in blank spots on the screenshot/screencapture. Just wanted to open a separate issue for this.

This issue did not exist before commit e496b0f250139b572307d048f3189aa6dde72f18. The likely culprit appears to be the coordinates in glReadPixels in the screencopy.cpp file, e.g. changing
```
if (packStride == stride) {
        glReadPixels(frame->box.x, frame->box.y, frame->box.w, frame->box.h, glf, glt, data);
``` 
back to
```
if (packStride == stride) {
        glReadPixels(0, 0, frame->box.w, frame->box.h, glf, glt, data);
``` 
solves the issue for me (tested on wayshot & pipewire).
Not sure if that's nvidia only or if something's wrong on my end.

### How to reproduce

1. Share the screen with Pipewire.
2. Capture an area. 
OR
Make a screenshot with Wayshot:
wayshot -s "$(slurp)"

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13562413/patch.txt)
try this

**Comment by FlyingButteryTuna** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/13562413/patch.txt) try this

that works

**Comment by vaxerski** [comment]
or does it...?

hey vsauce michael here
