### ISSUE TITLE
Windows from the special workspace loose their focus when switching workspaces

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/Hyprland#4048]
### Hyprland Version

Hyprland, built from branch HEAD at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94  (props: bump ver to 0.33.0). Tag: v0.33.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Windows from the special workspace loose their focus when switching workspaces.

### How to reproduce

1. Use empty/default Hyprland config.
2. Press `SUPER+Q` (run kitty).
3. Run from kitty's prompt: `hyprctl dispatch togglespecialworkspace`.
4. Press `SUPER+Q` (run another kitty instance in the special workspace).
5. Switch around workspaces with `SUPER+1`, `SUPER+2`, `SUPER+1`.

Kitty's window in the special workspace should retain its focus when switching workspaces, but it doesn't.

**Comment by dranull** [comment]
I think this can be closed now.

**Comment by akdevservices** [comment]
@dranull, I will close the issue when I verify it in the next release.

**Comment by vaxerski** [comment]
it's fixed in git, I will not wait for the next release. Feel free to reopen if the issue arises again
