### ISSUE TITLE
hyprctl: Couldn't get host (2)

### ISSUE THREAD

**Issue by mxxntype** [hyprwm/Hyprland#405]
hyprctl almost doesn't work at all. running **just** `hyprctl` goes smoothly:
```
usage: hyprctl [(opt)flags] [command] [(opt)args]

commands:
    monitors
    workspaces
    clients
    activewindow
    layers
    devices
    dispatch
    keyword
    version
    kill
    splash
    hyprpaper
    reload

flags:
    j -> output in JSON
```
but trying to use any command (like `hyprctl clients`, `hyprctl keyword`) results in `Couldn't get host (2)`

**steps to reproduce:**
i'm on Artix Linux with **runit**, linux-zen, nouveau. **I tried the regular linux kernel too, same issue.** I assume this isn't really important, but who knows.
- get `hyprland-git` (from AUR, as recommended)
- launch from tty with `dbus-run-session Hyprland`
- run any hyprctl command inside a terminal emulator - alacritty in my case.

**expected behavior:**
- hyprctl works normally, e.g. able to switch layouts with it like the wiki suggests.

**actual behaviour:**
- none of the hyprctl commands (except pure `hyprctl`) work; "`Couldn't get host (2)`" is printed out instead

I guess that's all? I wasn't able to find any clue on what could cause this. If this ends up unfixable: is there any other way (even a **really** hacky one would go) to switch keyboard layouts? for now that is the exact thing I hoped to use hyprctl for. Sorry if that is a stupid question, I'm stilll rather new to wayland

**Comment by vaxerski** [comment]
1) that's an issue with your system

2) should be fixed as that was a remnant of the past and could've been removed.
