### ISSUE TITLE
Dragging tabs into a browser unfocuses the window

### ISSUE THREAD

**Issue by MatthiasBenaets** [hyprwm/Hyprland#4051]
### Hyprland Version

Using flake.nix
37d7a8c64dfabfe81330c819c24fd6b13b292194asdf

### Bug or Regression?

Bug

### Description

Whenever a browser is opened twice or more, tabs can be dragged between each bar of the browser windows.
However, when moving a tab from one window to another, the focus stays on the browser of which the tab was just moved.
This is not ideal but fine. Now, when selecting the browser (where the tab was moved to), the keyboard does not interact with this browser window, but with the unfocused window.
This can only be fixed by cycling through windows or workspaces and selecting them.
This issue also persists when a browser only has 1 tab open that is moved to another browser window. (pretty much closing one of the windows)
I was able to reproduce this on both Firefox and Chrome.

### How to reproduce

0. Set input.follow_mouse=2
1. Open 2 separate browser windows.
2. Click and drag the tab (at the top of the browser) over to the other browser's bar.
3. Try to enter a URL in this moved tab. This should not work.
4. Focusing another window or workspace will reset this. The browser is now usable again for the keyboard.

**Comment by NotAShelf** [comment]
I can partially reproduce this. The window I've moved the tab to steals focus, but not input.

**Comment by MatthiasBenaets** [comment]
Tested it again today, and the issue seems to be fixed with the development progress.
