### ISSUE TITLE
some plugins may not work if not delay the load

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#4054]
### Description

#quick fix is when the plugin doesn't load sometimes along with hyprland
exec-once = sleep 4; hyprctl plugin load /usr/lib/hyprlandplugin.so

would be great to have something like

```
plugin {
    delay = N # delay to load N seconds
    load-after-session = true   #only start load plugins after hyprland.conf fully load
    hyprlandplugin {
        #only get the options after the delay or load-after-session
    }
}
```

**Comment by zakk4223** [comment]
Fix the plugins. (If it is one of mine tell me, so I can fix it)

**Comment by killown** [comment]
if the code is working after hyprland session is ready, it's not the code fault, it's working as intended, thus I am requesting this feature, could be even in main.cpp hyprland_is_ready(//then start main) == true; so the api call would only start after hyprland.conf load, any way the developer desires, this is just an idea, my request is someway to delay the load

**Comment by killown** [comment]
https://github.com/killown/hyprshell  it's random, working now without delay, depends on hyprland updates, some versions crashed the whole WM, some the plugin won't load, some plugin loads but not working and now with the latest version is working. 

It's very random, you see, I don't want to fix the plugin every time something changes in hyprland API or whatever creates a conflict. 

For me, even if it's working now, I would prefer delay the load to avoid future issues, but no problem, if the dev don't plan to do such thing I will just stay with exec-once = sleep 4; hyprctl plugin load /usr/lib/hyprlandplugin.so
