### ISSUE TITLE
swaylock refuses to run

### ISSUE THREAD

**Issue by AyushmaanAggarwal** [hyprwm/Hyprland#4058]
### Hyprland Version

Hyprland, built from branch HEAD at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94  (props: bump ver to 0.33.0).

### Bug or Regression?

Bug

### Description

Swaylock refuses to run after updating to version v0.33.0 of hyprland, swaylock outputs "2023-12-05 10:48:55 - [main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely"

### How to reproduce

run swaylock in the terminal on version v0.33.0 of hyprland

**Comment by zakk4223** [comment]
You need to update to a newer version of swaylock

**Comment by AyushmaanAggarwal** [comment]
oh just realized that this is an issue exclusively to swaylock-effects...
