### ISSUE TITLE
bindr ignores mouse click

### ISSUE THREAD

**Issue by g3r** [hyprwm/Hyprland#406]
I have this in my config:
```bindr=SUPER,Super_L,exec,killall -INT rofi || rofi -show ```

When I move or scale a window with SUPER-mouse drag and then release SUPER the binding is activated.

Expected result:
The binding is not activated because the mouse click cancels it.

**Comment by vaxerski** [comment]
fixed in 19cd04c85f6c1cf8f4a88f6a1588ff676f1c9779
