### ISSUE TITLE
[NVIDIA] Out of order frames on xwayland games

### ISSUE THREAD

**Issue by trippballs** [hyprwm/Hyprland#4063]
### Hyprland Version

Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3). Tag: v0.32.3

### Bug or Regression?

Bug

### Description

Frames randomly stick in place for more than one, sometimes I see older frames pop/flicker in. For example in cs2, I will see a frame of a different position i was in 2 seconds ago for one frame before it goes back to normal. Occurs in other games running d3vk, does not occur in opengl games, such as native TF2.

Nvidia 545.29.06
Kernel 6.6.3-arch1-1
OS Arch  Linux

### How to reproduce

Turn VSYNC off in your vulkan game.

**Comment by phonetic112** [comment]
because Xwayland doesn't support [explicit sync](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/967) yet. 

You could try patching Xwayland yourself if you want support now, or just wait until it gets merged

**Comment by vaxerski** [comment]
as above, not really our issue either as IIRC wlroots has no explicit sync yet
