### ISSUE TITLE
Missing borders

### ISSUE THREAD

**Issue by zstg** [hyprwm/Hyprland#4064]
### Hyprland Version

Hyprland, built from branch HEAD at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94  (props: bump ver to 0.33.0). Tag: v0.33.0  flags: (if any)

### Bug or Regression?

Regression

### Description

Borders are missing

### How to reproduce

Update to v0.33.0

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/69384921/ab5507fa-6f1a-40b4-858f-245363151e59)

[Video of my blue borders](https://packaged-media.redd.it/q4bso5t53nra1/pb/m2-res_480p.mp4?m=DASHPlaylist.mpd&v=1&e=1701842400&s=c8fa8ca43f1b9bb1a8f59fad2f426db6ddf772db#t=0)

**Comment by zstg** [comment]
I must add that this issue occurs with both the `Hyprland` and `hyprland-git` repos.

Here's the relevant part in my config:
```
general {
    gaps_in = 6
    gaps_out = 10 
    border_size = 2.5
    resize_on_border = true
    col.active_border = 0x33ccffee # rgba(00ff99ee) 45deg # stopped working since 33
    col.inactive_border = 0x595959aa
    # col.inactive_border = rgb(c19ee0) rgb(5a189a) 45deg # purple gradient
}
```

**Comment by trippballs** [comment]
+1 Issue only started occuring since last release

Hyprland, built from branch HEAD at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94  (props: bump ver to 0.33.0).
Tag: v0.33.0

**Comment by vaxerski** [comment]
`border_size = 2.5`

2.5 is not an int.

Please rtfw.

**Comment by zstg** [comment]
I'm sorry, did this change recently?

**Comment by vaxerski** [comment]
no. It's just that type checking has gotten stricter and invalid ints will be turned into 0 now.
