### ISSUE TITLE
swaylock broken in version 0.33.0-1 "Compositor does not support the input inhibitor protocol, refusing to run insecurely"

### ISSUE THREAD

**Issue by neilking01** [hyprwm/Hyprland#4065]
### Hyprland Version

0.33.0-1

### Bug or Regression?

Bug

### Description

swaylock refuses to run and shows message: "Compositor does not support the input inhibitor protocol, refusing to run insecurely".  works fine on v0.32.3

### How to reproduce

install version 0.33.0-1 and run swaylock

**Comment by vaxerski** [comment]
support for input inhibitor was dropped as it's a long-deprecated protocol. swaylock supports it and has supported it for about 2 years. Time to update.
