### ISSUE TITLE
Hyprland Crash 

### ISSUE THREAD

**Issue by userDoffy** [hyprwm/Hyprland#4066]
### Hyprland Version

Hyprland 0.33 from Fedora Copr

### Bug or Regression?

Bug

### Description

Hyprland crashes whenever i make a change to hyprland.conf and logout .
It doesn't crash if i haven't made changes to hyprland.conf file.

### How to reproduce

Log into hyprland session, make changes to hyprland.conf and logout

### Crash reports, logs, images, videos

Black screen and can't even access TTY

**Comment by userDoffy** [comment]
Dec 07 12:28:10 fedora systemd-coredump[13720]: [🡕] Process 2687 (xdg-desktop-por) of user 1000 dumped core.
                                                
                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-9.fc39.x86_64
                                                Module libtinfo.so.6 from rpm ncurses-6.4-7.20230520.fc39.x86_64
                                                Module libedit.so.0 from rpm libedit-3.1-48.20230828cvs.fc39.x86_64
                                                Module libxcb-dri3.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                                                Module libdrm_intel.so.1 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libdrm_nouveau.so.2 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libelf.so.1 from rpm elfutils-0.190-4.fc39.x86_64
                                                Module libdrm_radeon.so.1 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libsensors.so.4 from rpm lm_sensors-3.6.0-14.fc39.x86_64
                                                Module libz.so.1 from rpm zlib-1.2.13-4.fc39.x86_64
                                                Module radeonsi_dri.so from rpm mesa-23.2.1-2.fc39.x86_64
                                                Module libglapi.so.0 from rpm mesa-23.2.1-2.fc39.x86_64
                                                Module libspa-journal.so from rpm pipewire-1.0.0-1.fc39.x86_64
                                                Module libspa-support.so from rpm pipewire-1.0.0-1.fc39.x86_64
                                                Module libXau.so.6 from rpm libXau-1.0.11-3.fc39.x86_64
                                                Module libxcb.so.1 from rpm libxcb-1.13.1-12.fc39.x86_64
                                                Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
                                                Module libzstd.so.1 from rpm zstd-1.5.5-4.fc39.x86_64
                                                Module liblzma.so.5 from rpm xz-5.4.4-1.fc39.x86_64
                                                Module liblz4.so.1 from rpm lz4-1.9.4-4.fc39.x86_64
                                                Module libcap.so.2 from rpm libcap-2.48-8.fc39.x86_64
                                                Module libxcb-randr.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                                                Module libexpat.so.1 from rpm expat-2.5.0-3.fc39.x86_64
                                                Module libwayland-server.so.0 from rpm wayland-1.22.0-2.fc39.x86_64
                                                Module libwayland-client.so.0 from rpm wayland-1.22.0-2.fc39.x86_64
                                                Module libsystemd.so.0 from rpm systemd-254.7-1.fc39.x86_64
                                                Module libpipewire-0.3.so.0 from rpm pipewire-1.0.0-1.fc39.x86_64
                                                Module libdrm.so.2 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libgbm.so.1 from rpm mesa-23.2.1-2.fc39.x86_64
                                                Module xdg-desktop-portal-hyprland from rpm xdg-desktop-portal-hyprland-1.2.5-1.fc39.x86_64
                                                Stack trace of thread 2687:
                                                #0  0x000055631061363f _ZNSt17_Function_handlerIFvPvEZN5sdbus8internal10Connection15addObjectVTableERKNSt7__c>c 07 12:08:05 fedora kernel: Bluetooth: hci0: Firmware revision 0.3 build 24
                                                #1  0x000055631061c54f _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N5sdbus>vice plugin: NMBluezManager (/usr/lib64/NetworkManager/1.44.2-1.fc39/libnm-d
                                                #2  0x000055631061c8c6 _ZN5sdbus8internal6ObjectD0Ev (xdg-desktop-portal-hyprland + 0x578c6)
                                                #3  0x00005563105eab8b _ZN14CPortalManagerD2Ev.lto_priv.0 (xdg-desktop-portal-hyprland + 0x25b8b)
                                                #4  0x00005563105ead7d _ZNSt10unique_ptrI14CPortalManagerSt14default_deleteIS0_EED1Ev (xdg-desktop-portal-hyp>c 07 17:52:58 fedora kernel: integrity: Loading X.509 certificate: UEFI:db
                                                #5  0x00007f6c9305efd6 __run_exit_handlers (libc.so.6 + 0x40fd6)
                                                #6  0x00007f6c9305f11e exit (libc.so.6 + 0x4111e)
                                                #7  0x00007f6c93046151 __libc_start_call_main (libc.so.6 + 0x28151)
                                                #8  0x00007f6c9304620b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
                                                #9  0x00005563105dd595 _start (xdg-desktop-portal-hyprland + 0x18595)
                                                ELF object binary architecture: AMD x86-64
Dec 07 12:28:10 fedora systemd[1]: systemd-coredump@1-13706-0.service: Deactivated successfully.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Main process exited, code=dumped, status=11/SEGV
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Failed with result 'core-dump'.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Consumed 6.569s CPU time.
Dec 07 12:28:11 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@1-13706->
Dec 07 12:28:11 fedora audit: BPF prog-id=95 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=94 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=93 op=UNLOAD
Dec 07 12:28:11 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Scheduled restart job, restart counter is at 1.
Dec 07 12:28:11 fedora systemd[2299]: Starting xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)...
Dec 07 12:28:11 fedora systemd[2299]: Started xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation).
Dec 07 12:28:11 fedora systemd-coredump[13718]: [🡕] Process 2380 (Hyprland) of user 1000 dumped core.
                                                
                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-9.fc39.x86_64
                                                Module libtinfo.so.6 from rpm ncurses-6.4-7.20230520.fc39.x86_64
                                                #7  0x00007f6c93046151 __libc_start_call_main (libc.so.6 + 0x28151)
                                                #8  0x00007f6c9304620b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
                                                #9  0x00005563105dd595 _start (xdg-desktop-portal-hyprland + 0x18595)
                                                ELF object binary architecture: AMD x86-64
Dec 07 12:28:10 fedora systemd[1]: systemd-coredump@1-13706-0.service: Deactivated successfully.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Main process exited, code=dumped, status=11/SEGV
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Failed with result 'core-dump'.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Consumed 6.569s CPU time.
Dec 07 12:28:11 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@1-13706->
Dec 07 12:28:11 fedora audit: BPF prog-id=95 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=94 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=93 op=UNLOAD
Dec 07 12:28:11 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Scheduled restart job, restart counter is at 1.
Dec 07 12:28:11 fedora systemd[2299]: Starting xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)...
Dec 07 12:28:11 fedora systemd[2299]: Started xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation).
Dec 07 12:28:11 fedora systemd-coredump[13718]: [🡕] Process 2380 (Hyprland) of user 1000 dumped core.
                                                
                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-9.fc39.x86_64
                                                Module libtinfo.so.6 from rpm ncurses-6.4-7.20230520.fc39.x86_64
                                                #7  0x00007f6c93046151 __libc_start_call_main (libc.so.6 + 0x28151)
                                                #8  0x00007f6c9304620b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
                                                #9  0x00005563105dd595 _start (xdg-desktop-portal-hyprland + 0x18595)
                                                ELF object binary architecture: AMD x86-64
Dec 07 12:28:10 fedora systemd[1]: systemd-coredump@1-13706-0.service: Deactivated successfully.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Main process exited, code=dumped, status=11/SEGV
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Failed with result 'core-dump'.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Consumed 6.569s CPU time.
Dec 07 12:28:11 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@1-13706->
Dec 07 12:28:11 fedora audit: BPF prog-id=95 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=94 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=93 op=UNLOAD
Dec 07 12:28:11 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Scheduled restart job, restart counter is at 1.
Dec 07 12:28:11 fedora systemd[2299]: Starting xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)...
Dec 07 12:28:11 fedora systemd[2299]: Started xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation).
Dec 07 12:28:11 fedora systemd-coredump[13718]: [🡕] Process 2380 (Hyprland) of user 1000 dumped core.
                                                
                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-9.fc39.x86_64
                                                Module libtinfo.so.6 from rpm ncurses-6.4-7.20230520.fc39.x86_64
                                                #7  0x00007f6c93046151 __libc_start_call_main (libc.so.6 + 0x28151)
                                                #8  0x00007f6c9304620b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
                                                #9  0x00005563105dd595 _start (xdg-desktop-portal-hyprland + 0x18595)
                                                ELF object binary architecture: AMD x86-64
Dec 07 12:28:10 fedora systemd[1]: systemd-coredump@1-13706-0.service: Deactivated successfully.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Main process exited, code=dumped, status=11/SEGV
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Failed with result 'core-dump'.
Dec 07 12:28:10 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Consumed 6.569s CPU time.
Dec 07 12:28:11 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@1-13706->
Dec 07 12:28:11 fedora audit: BPF prog-id=95 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=94 op=UNLOAD
Dec 07 12:28:11 fedora audit: BPF prog-id=93 op=UNLOAD
Dec 07 12:28:11 fedora systemd[2299]: xdg-desktop-portal-hyprland.service: Scheduled restart job, restart counter is at 1.
Dec 07 12:28:11 fedora systemd[2299]: Starting xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)...
Dec 07 12:28:11 fedora systemd[2299]: Started xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation).
Dec 07 12:28:11 fedora systemd-coredump[13718]: [🡕] Process 2380 (Hyprland) of user 1000 dumped core.
                                                
                                                Module libpciaccess.so.0 from rpm libpciaccess-0.16-9.fc39.x86_64
                                                Module libtinfo.so.6 from rpm ncurses-6.4-7.20230520.fc39.x86_64
                                                Module libedit.so.0 from rpm libedit-3.1-48.20230828cvs.fc39.x86_64
                                                Module libdrm_intel.so.1 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libdrm_nouveau.so.2 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libelf.so.1 from rpm elfutils-0.190-4.fc39.x86_64
                                                Module libdrm_radeon.so.1 from rpm libdrm-2.4.118-1.fc39.x86_64
                                                Module libsensors.so.4 from rpm lm_sensors-3.6.0-14.fc39.x86_64
                                                Module radeonsi_dri.so from rpm mesa-23.2.1-2.fc39.x86_64
                                                Module libxshmfence.so.1 from rpm libxshmfence-1.3-13.fc39.x86_64
                                                Module libxcb-sync.so.1 from rpm libxcb-1.13.1-12.fc39.x86_64
                                                Module libxcb-dri2.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                                                Module libX11-xcb.so.1 from rpm libX11-1.8.7-1.fc39.x86_64
                                                Module libglapi.so.0 from rpm mesa-23.2.1-2.fc39.x86_64
                                                Module libEGL_mesa.so.0 from rpm mesa-23.2.1-2.fc39.x86_64
                                                Module libnvidia-egl-gbm.so.1 from rpm egl-gbm-1.1.0-5.fc39.x86_64
                                                Module libnvidia-egl-wayland.so.1 from rpm egl-wayland-1.1.13-1.fc39.x86_64
                                                Module libblkid.so.1 from rpm util-linux-2.39.2-1.fc39.x86_64
                                                Module libbrotlicommon.so.1 from rpm brotli-1.1.0-1.fc39.x86_64
                                                Module libgraphite2.so.3 from rpm graphite2-1.3.14-12.fc39.x86_64
![20231207_12h30m19s_grim](https://github.com/hyprwm/Hyprland/assets/122683480/990babb0-be3e-4229-a35b-650db9ea8355)

**Comment by MightyPlaza** [comment]
the crash log in ~/.hyprland/ ?
also could be nvidia related

**Comment by romanstingler** [comment]
can you post your config and tell us which changes you did and test again?

**Comment by vaxerski** [comment]
closing, stale
