### ISSUE TITLE
Crash on call of `hyprctl dispatch exit` (SIGSEGV Address boundary error)

### ISSUE THREAD

**Issue by mxaddict** [hyprwm/Hyprland#4067]
### Hyprland Version

Hyprland, built from branch HEAD at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94  (props: bump ver to 0.33.0).

### Bug or Regression?

Bug

### Description

Hyprland exits with non 0 status, and errors the following:
```
SIGSEGV (Address boundary error)
```

### How to reproduce

Just run `hyprctl dispatch exit`

### Crash reports, logs, images, videos

There is no crash report in `~/.hyprland` for some reason

**Comment by vaxerski** [comment]
check with 03c6f4506ab06d2920c59b3c64f45cb4eec8c97a

**Comment by tchofy** [comment]
> Do I have to build this myself? Or is there an AUR PKGBUILD that I could use for this version?
If you just reinstall from the aur it should pull the latest commit and build it for you. You only need to build manually if you get a patch file or if you need to test a specific PR.

**Comment by mxaddict** [comment]
> > Do I have to build this myself? Or is there an AUR PKGBUILD that I could use for this version?
> 
> If you just reinstall from the aur it should pull the latest commit and build it for you. You only need to build manually if you get a patch file or if you need to test a specific PR.

The version that is on the AUR is currently a0b675ec
I will try with this version though as it should be newer

**Comment by mxaddict** [comment]
> > > Do I have to build this myself? Or is there an AUR PKGBUILD that I could use for this version?
> > 
> > 
> > If you just reinstall from the aur it should pull the latest commit and build it for you. You only need to build manually if you get a patch file or if you need to test a specific PR.
> 
> The version that is on the AUR is currently [a0b675e](https://github.com/hyprwm/Hyprland/commit/a0b675ec9e57af8bc631fc8cc54d062b58669a9f) I will try with this version though as it should be newer

Actually when I built it just now, I got 62a8d0be which was a push from just a few hours ago, so should be good.

**Comment by mxaddict** [comment]
> > > > Do I have to build this myself? Or is there an AUR PKGBUILD that I could use for this version?
> > > 
> > > 
> > > If you just reinstall from the aur it should pull the latest commit and build it for you. You only need to build manually if you get a patch file or if you need to test a specific PR.
> > 
> > 
> > The version that is on the AUR is currently [a0b675e](https://github.com/hyprwm/Hyprland/commit/a0b675ec9e57af8bc631fc8cc54d062b58669a9f) I will try with this version though as it should be newer
> 
> Actually when I built it just now, I got [62a8d0b](https://github.com/hyprwm/Hyprland/commit/62a8d0be5c1959ade8410f8f964e362288f22175) which was a push from just a few hours ago, so should be good.

Seems to be fixed with the latest commits, I guess I can close this now, thanks for the help
