### ISSUE TITLE
Gap between drop shadow and window border when scale > 1

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#4068]
### Hyprland Version

Hyprland, built from branch main at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94 dirty (props: bump ver to 0.33.0). Tag: v0.33.0

### Bug or Regression?

Bug

### Description

Sometimes there's a gap between the drop shadow and the border of a window. The gap looks like 1 pixel wide. Only happens when scale > 1. Probably some rounding issue with scaling.

### How to reproduce

Have 1.2 scaling.
Have drop shadow enabled.
Drag and resize windows and the gap will show up intermittently.

**Comment by vaxerski** [comment]
check #4104

**Comment by thejch** [comment]
It wasn't fixed

**Comment by vaxerski** [comment]
:(

**Comment by vaxerski** [comment]
ah. It's because you're creating fractional pixels. It's the root of many issues. I should disallow scales (or round them to the nearest valid) if they don't cleanly divide.

**Comment by vaxerski** [comment]
check now

**Comment by thejch** [comment]
seems fixed, thanks

**Comment by thejch** [comment]
So apparently that added some new issues. I opened https://github.com/hyprwm/Hyprland/issues/4225
