### ISSUE TITLE
[Master Stack] Additional commands for master layout

### ISSUE THREAD

**Issue by mwglen** [hyprwm/Hyprland#407]
I was wondering if you could implement two commands that would drastically improve managing the master layout:

1. Swap with Master Command
Could we get a command to swap the current window with the master window?

2. Cycling Command (Related to #401)
The default behavior of the mod-J and mod-K keys in DWM and XMonad is to cycle through windows down the master pane, then down the stack, and the back to the master pane. Could we get a command that implements this feature?

**Comment by vaxerski** [comment]
both done in 3904351678f9e76ee67896e39641c82efbb9ed01

https://github.com/hyprwm/Hyprland/wiki/Master-Layout#dispatchers
