### ISSUE TITLE
Screen share on individual clients dosent work

### ISSUE THREAD

**Issue by chiefdinkan** [hyprwm/Hyprland#4070]
### Hyprland Version

Hyprland, built from branch main at commit 8bd86cf37e245088433156796f1bc72542ca09ad dirty (hyprctl: order commands alphabetically (4061)). Tag: v0.33.0-6-g8bd86cf3

### Bug or Regression?

Bug

### Description

Screen sharing using hyprland-share-picker dosent work on individual clients in discord-screenshareaudio or google-meet

![image](https://github.com/hyprwm/Hyprland/assets/87846149/3d325fe0-6b7f-42b5-9951-91a64d61ccb8)

only a blank background with a cursor is present when sharing clients
also on the latest build of  xdg-desktop-portal-hyprland-git   and hyprland-git

### How to reproduce

    1. Initiate the Google Meet application.
    2. Activate the screen-sharing feature utilizing the share picker tool to present visual content  from the  clients.
    3.Observe a solitary, immobile cursor against a featureless background.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13587317/patch.txt)
try this

**Comment by romanstingler** [comment]
@vaxerski screensharing was broken today, after building with that patch it works again :+1:
