### ISSUE TITLE
GPU is not being detected (NVIDIA)

### ISSUE THREAD

**Issue by liamrahum** [hyprwm/Hyprland#4074]
### Hyprland Version

0.32.3

### Bug or Regression?

Bug

### Description

I'm trying to run Hyprland on Debian (silly, I know - but [there's proof it works](https://github.com/JaKooLit/Debian-Hyprland)), I installed all the necessary drivers, set up kernel & env parameters - but it still cannot detect my GPU for some reason, though it is detected by other DEs.

### How to reproduce

(On Debian "trixie" testing)
* Use [Debian Hyprland](https://github.com/JaKooLit/Debian-Hyprland) install script
* Hyprland no work :(

### Crash reports, logs, images, videos

```[wlr] [backend/session/session.c:410] Unable to open /dev/dri/card0 as DRM device```
```[wlr] [backend/backend.c:210] Found 0 GPUs, cannot create backend```
```[wlr] [backend/backend.c:376] Failed to open any DRM device```

**Comment by vaxerski** [comment]
unlucky, no official nvidia support. See the wiki's nvidia page or ask on discord in #hyprland-nvidia

**Comment by liamrahum** [comment]
Dang, fastest reply I've ever seen - thanks anyways!
