### ISSUE TITLE
Swaylock Fails on Hyprland Update

### ISSUE THREAD

**Issue by 0x76OID** [hyprwm/Hyprland#4080]
### Hyprland Version

Latest

### Bug or Regression?

Bug

### Description

After updating to the latest version, swaylock fails to run with the error: 

> Compositor does not support the input inhibitor protocol, refusing to run insecurely.

Seeking assistance to resolve the compatibility issue with Hyprland compositor.

### How to reproduce

Update Hyprland to the latest version.

Run swaylock.

**Comment by 0x76OID** [comment]
I am currently using the latest version of swaylock, v1.7.2, and the issue persists despite the update. Any additional guidance or troubleshooting steps would be greatly appreciated.

**Comment by vaxerski** [comment]
you definitely are not.

https://github.com/swaywm/swaylock/commit/1d1c75b6316d21933069a9d201f966d84099f6ca

check your `swaylock -v`

**Comment by 0x76OID** [comment]
> you definitely are not.
> 
> [swaywm/swaylock@1d1c75b](https://github.com/swaywm/swaylock/commit/1d1c75b6316d21933069a9d201f966d84099f6ca)
> 
> check your `swaylock -v`

I assure you that I have verified the swaylock version, and it is indeed 1.7.2

> swaylock -v
> swaylock version 1.7.2

I wouldn't have reported the issue without checking first, Anyway i appreciate your attention to this matter. I'll look into it further and see if i can identify or fix the issue.

**Comment by vaxerski** [comment]
no way in the name of all thats holy that 1.7.2 is preferring input-inhibitor, it's been using ext-session-lock forever
