### ISSUE TITLE
[Bug] Since update 0.33 groupbar gradients disappear after boot

### ISSUE THREAD

**Issue by fleurc** [hyprwm/Hyprland#4081]
### Hyprland Version

0.33.0

### Bug or Regression?

Bug

### Description

Whenever booting up, no matter if `gradients = true` in `group:groupbar` or not the gradients disappear the minute there's a reboot, only way of "fixing" it is to reload the configuration, and once upon reboot the problem comes back. Same with sleep/suspend.

This is happening in Archlinux, if that information is at all necessary.

### How to reproduce

1. Update to 0.33
2. Use group with gradients on
3. Reboot
4. Gradients disappear in all groups until configuration reload

**Comment by vaxerski** [comment]
... reboot? how does that change anything?

I have never had that happen

**Comment by fleurc** [comment]
> ... reboot? how does that change anything?
> 
> I have never had that happen

When I reboot, this is what happens:
https://files.catbox.moe/fp8nfl.mkv

**Comment by fleurc** [comment]
I also don't know how I'm getting it back, but I am, still I lose them every time there is a reboot or suspend and I didn't see an issue about this before, so I put one out.

**Comment by shot-codes** [comment]
I'm seeing this as well. No gradients at all, reboot doesn't bring them back.

**Comment by MightyPlaza** [comment]
I think I have found what's causing this issue
the egl context doesn't exist outside `CHyprRenderer::renderMonitor` since d2c3b23ace745d3f79926c71d4cb3c481a394841 added  `unsetEGL()` to `CHyprRenderer::endRender`

since `refreshGroupBarGradients` seems to get called from the outside, the context doesn't exist and nothing gets rendered.

one option is

```diff
diff --git a/src/render/decorations/CHyprGroupBarDecoration.cpp b/src/render/decorations/CHyprGroupBarDecoration.cpp
index ae1d76a7..d1315e53 100644
--- a/src/render/decorations/CHyprGroupBarDecoration.cpp
+++ b/src/render/decorations/CHyprGroupBarDecoration.cpp
@@ -295,10 +295,14 @@ void refreshGroupBarGradients() {
         m_tGradientLockedInactive.destroyTexture();
     }
 
+    g_pHyprRenderer->makeEGLCurrent();
+
     renderGradientTo(m_tGradientActive, ((CGradientValueData*)PGROUPCOLACTIVE->get())->m_vColors[0]);
     renderGradientTo(m_tGradientInactive, ((CGradientValueData*)PGROUPCOLINACTIVE->get())->m_vColors[0]);
     renderGradientTo(m_tGradientLockedActive, ((CGradientValueData*)PGROUPCOLACTIVELOCKED->get())->m_vColors[0]);
     renderGradientTo(m_tGradientLockedInactive, ((CGradientValueData*)PGROUPCOLINACTIVELOCKED->get())->m_vColors[0]);
+
+    g_pHyprRenderer->unsetEGL();
 }
 
 bool CHyprGroupBarDecoration::onEndWindowDragOnDeco(CWindow* pDraggedWindow, const Vector2D& pos) {
```

another would be to call this function from inside the rendering loop
