### ISSUE TITLE
Hyprpm doesn't work with packaged headers

### ISSUE THREAD

**Issue by solopasha** [hyprwm/Hyprland#4082]
### Hyprland Version

a794eecd6a71e431b654cebb1b28dbff0d6da079

### Bug or Regression?

Bug

### Description

When Hyprland is installed from a package, the prefix is usually /usr
pkg-config --cflags hyprland returns:
```
❯ pkg-config --cflags hyprland                                  
-I/usr/include/hyprland/protocols -I/usr/include/hyprland/wlroots
```
Then hyprpm complains that Headers corrupted.

I managed to fix it with:
```
diff --git a/hyprpm/src/core/PluginManager.cpp b/hyprpm/src/core/PluginManager.cpp
index 8efcdf98..f0f6f01d 100644
--- a/hyprpm/src/core/PluginManager.cpp
+++ b/hyprpm/src/core/PluginManager.cpp
@@ -253,7 +253,7 @@ eHeadersErrors CPluginManager::headersValid() {
     const auto HLVER = getHyprlandVersion();
 
     // find headers commit
-    auto headers = execAndGet("pkg-config --cflags hyprland");
+    auto headers = execAndGet("pkg-config --cflags --keep-system-cflags hyprland");
 
     if (!headers.contains("-I/"))
         return HEADERS_MISSING;
@@ -687,4 +687,4 @@ void CPluginManager::listAllPlugins() {
 
 void CPluginManager::notify(const eNotifyIcons icon, uint32_t color, int durationMs, const std::string& message) {
     execAndGet("hyprctl notify " + std::to_string((int)icon) + " " + std::to_string(durationMs) + " " + std::to_string(color) + " " + message);
-}
\ No newline at end of file
+}
```
but I don't know if it'd break manually built Hyprland (or with any prefix other than /usr), just too lazy to setup this.

### How to reproduce

Install hyprland-git
hyprpm add https://github.com/hyprwm/hyprland-plugins

**Comment by vaxerski** [comment]
why didnt you just make a mr then?

**Comment by Andy3153** [comment]
Anything new about this? Any fix coming? Still affects me on latest git.

**Comment by vaxerski** [comment]
if latest git's hyprpm doesn't work with system headers it means the system headers are packaged incorrectly.

**Comment by Andy3153** [comment]
Using `hyprland-git` from the AUR. What do you suggest then?

**Comment by vaxerski** [comment]
what's the error you are getting?

**Comment by Andy3153** [comment]
```
$ hyprpm update

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.
✔ cloned
✔ checked out to running ver
! configuring Hyprland
✔ configured Hyprland
! in order to install the sources, you will need to input your password.
  If nothing pops up, make sure you have polkit and an authentication daemon running.
✖ failed to install headers with error code 5
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed

✖ Headers duplicated!!! This is a very bad sign.
 This could be due to e.g. installing hyprland manually while a system package of hyprland is also installed.
 If the above doesn't apply, check your /usr/include and /usr/local/include directories
 and remove all the hyprland headers.
````

**Comment by vaxerski** [comment]
yeah probably means you installed hyprland-git and also installed hyprland manually, or installed hyprland and installed manually. Exactly what it says.

**Comment by Andy3153** [comment]
I only ever installed `hyprland` from the Arch repos and then later switched to `hyprland-git` from the AUR.

**Comment by Andy3153** [comment]
> Using `hyprland-git` from the AUR. What do you suggest then? Just `rm` them like I've seen in another issue and rebuild?

I just did what I said here and it works now. I always used the package manager to install hyprland no matter the package I used, but whatever, something caused the issue.

**Comment by vaxerski** [comment]
maybe arch packages the headers in an invalid way
