### ISSUE TITLE
Strange redrawing issue on versions above v0.30.0

### ISSUE THREAD

**Issue by bkuri** [hyprwm/Hyprland#4085]
### Hyprland Version

v0.32.3, v0.33.0, v0.33.1

### Bug or Regression?

Bug

### Description

I'm having an issue with versions above `v0.30.0` where the entire window layout gets redrawn every 5 seconds or so. Please check out the videos for more details.

[Here's my main config file FWIW](https://github.com/hyprwm/Hyprland/files/13605245/hyprland.conf.txt).

### How to reproduce

update from `v0.30.0` to any version after that (I tried up to `v0.33.1`)

### Crash reports, logs, images, videos

`v0.30.0`:
https://cdn.discordapp.com/attachments/961694014615208048/1182416855890141224/v03001.mp4?ex=65849e82&is=65722982&hm=9e36e4dd5edc0c802fdb86736709f66f540daa75455e1b23ce3f82597872a600&

`v0.33.1`:
https://cdn.discordapp.com/attachments/961694014615208048/1182416856628334602/v03312.mp4?ex=65849e82&is=65722982&hm=1dbda0eb49b96f71bd9168ff10ccb034962d018182c7e1ff9fe45a87cebfbd21&

`uname -a`:

```
6.6.4-AMD-znver2 #1 SMP PREEMPT_DYNAMIC Sun Dec  3 08:15:20 CET 2023 x86_64 GNU/Linux
```

`lspci -v`:

```
0b:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
    Subsystem: Tul Corporation / PowerColor Radeon RX 570 4G [Red Dragon]
    Flags: bus master, fast devsel, latency 0, IRQ 164, IOMMU group 27
    Memory at d0000000 (64-bit, prefetchable) [size=256M]
    Memory at e0000000 (64-bit, prefetchable) [size=2M]
    I/O ports at f000 [size=256]
    Memory at fce00000 (32-bit, non-prefetchable) [size=256K]
    Expansion ROM at fce40000 [disabled] [size=128K]
    Capabilities: <access denied>
    Kernel driver in use: amdgpu
    Kernel modules: amdgpu
```

**Comment by bkuri** [comment]
@vaxerski I was able to track the issue by listening to socket2. It seems that `espanso` is crashing/reloading constantly under `v0.33.1`. No idea as to why.

Some sample output:

```
activewindow>>kitty,systemctl --user start espanso
activewindowv2>>560f9edbe410
windowtitle>>560f9edbe410
activewindow>>kitty,bk@bkuri-desktop:~
activewindowv2>>560f9edbe410
windowtitle>>560f9edbe410
activewindow>>kitty,~
activewindowv2>>560f9edbe410
activewindow>>,Espanso Sync Tool
activewindowv2>>560f9edde6c0
openwindow>>560f9edde6c0,1,,Espanso Sync Tool
closewindow>>560f9edde6c0
activewindow>>kitty,./scripts/sock2.sh
activewindowv2>>560f9ee06210
activewindow>>,Espanso Sync Tool
activewindowv2>>560f9edde6c0
openwindow>>560f9edde6c0,1,,Espanso Sync Tool
closewindow>>560f9edde6c0
activewindow>>kitty,./scripts/sock2.sh
activewindowv2>>560f9ee06210
activewindow>>,Espanso Sync Tool
activewindowv2>>560f9ee1d960
openwindow>>560f9ee1d960,1,,Espanso Sync Tool
closewindow>>560f9ee1d960
```

… and so on.

The issue stops after issuing the following command:

```
systemctl --user stop espanso
```

I do use espanso pretty extensively, so I guess I'll revert to `v0.30.0` for now.

More info on that app here: https://espanso.org/

Definitely let me know if you'd like me to try something else out.

**Comment by vaxerski** [comment]
#3858 then

**Comment by vaxerski** [comment]
I'd like to remind you I am not going to fix some random garbaj that doesnt work

**Comment by bkuri** [comment]
@vaxerski oh, absolutely. Wasn't expecting you to lol.

Do you know what change within hyprland could have caused this, though? So that I can let those folks know?

Thanks again!

**Comment by vaxerski** [comment]
I have no clue and additionally I hate rust so no. They should know best how they debug issues
