### ISSUE TITLE
Allow hyprctl instances even when HYPRLAND_INSTANCE_SIGNATURE is unset

### ISSUE THREAD

**Issue by eriedaberrie** [hyprwm/Hyprland#4088]
### Description

`hyprctl instances` doesn't need `HYPRLAND_INSTANCE_SIGNATURE` at all, and will work perfectly fine if it's set to some random gibberish. However, if it's entirely unset, it doesn't work because hyprctl errors very early on if the instance signature is unset, even if it doesn't actually end up using it. I think it would be nice if `hyprctl instances` could be used without an instance signature.

**Comment by Lillecarl** [comment]
https://github.com/hyprwm/Hyprland/blob/main/nix/hm-module.nix#L147 This could be simplified into
```
      for i in $(${pkgs.hyprland}/bin/hyprctl instances -j | jq ".[].instance" -r); do
        HYPRLAND_INSTANCE_SIGNATURE=$i ${hyprlandPackage}/bin/hyprctl reload config-only
      done
```

**Comment by vaxerski** [comment]
288f1863f0b6886e0cdf85d16bb2460bb042acf2
