### ISSUE TITLE
Yambar disappears when turning on the monitor after turning it off

### ISSUE THREAD

**Issue by mrkcee** [hyprwm/Hyprland#409]
Yambar disappears (or probably not rendered) when turning on the monitor after turning it off despite it still running in the background.

**Replication steps:**
1. Configure yambar to run during startup in hyprland.conf
2. Launch Hyprland
3. Turn off monitor
4. Turn on monitor

**Tested in:**
Gentoo Linux (X86_64-OpenRC)
Hyprland (latest commit)
Single monitor setup

One observation is that, before turning off the monitor, Layer level 1 is named panel but after turning off then on, the Layer level 1 is empty.

**Before**
>  Monitor DP-2:
>        Layer level 0:
> 		Layer 1fa43820: xywh: 0 0 2560 1440, namespace: wallpaper
> 	Layer level 1:
> 		Layer 1f76b730: xywh: 0 0 2560 35, namespace: panel
> 	Layer level 2:
> 	Layer level 3:

**After**

> Monitor DP-2:
> 	Layer level 0:
> 		Layer 1f76a200: xywh: 0 0 2560 1440, namespace: wallpaper
> 	Layer level 1:
> 	Layer level 2:
> 	Layer level 3:

I also tested this in Sway. The issue does not happen there.

**Comment by vaxerski** [comment]
why not just make a script that restarts yambar when you plug in the monitor? thats what the socket2 is for

**Comment by mrkcee** [comment]
That's an option, yes. I was just wondering why yambar is not recreating the surface layer. It must not be able to process a certain event being sent by compositor.
