### ISSUE TITLE
Hyprctl Reload to not wake up EDP-1 or laptop monitor

### ISSUE THREAD

**Issue by JaKooLit** [hyprwm/Hyprland#4090]
### Description

First, Im not sure if this already been asked but I couldnt find it..

Anyway, I have this on my config
bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, preferred, auto, 1"
bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"

When I close my laptop lid, All workspaces and the external monitor became now the "main" display and all workspaces including mouse cursor moved to external monitor. (which is good)

However, when I change something on the settings, i.e. change some color settings, or monitor settings, the hyprctl reload wakes up the eDP-1. Closing and opening lid will of course disable the laptop's main display.

One solution is to of course disable the hyprctl reload, however, the waybar that I set to reload during wallpaper automatic change does not work anymore. 

so probably you can set that if the Lid Switch is on, laptop monitor wont be wake up during reload.... something like that

**Comment by vaxerski** [comment]
this is precisely how hyprctl keyword works. It's temporary until the next reload.

if you want permanent solutions, you can always `source = monitorConfig.conf` and echo your settings to the config.

`monitor=` keywords are overwrite, so you can set your regular rules at the top, then source your monitorconfig, and whatever you put in that config will overwrite the rules in the main config.

**Comment by JaKooLit** [comment]
thanks for your reply.

I forgot to mention that this are the contents of my hyprland.conf

# Sourcing external config files
$configs = $HOME/.config/hypr/configs

source=$configs/ENVariables.conf
source=$configs/Execs.conf
source=$configs/Keybinds.conf
source=$configs/Laptops.conf
source=$configs/Monitors.conf
source=$configs/WindowRules.conf
source=$configs/Settings.conf

and nothing else. Are you suggesting that I should also populate hyprland.conf?

**Comment by vaxerski** [comment]
`source=$configs/MonitorSetup.conf` and then `echo "monitor=...." > $configs/MonitorSetup.conf`

**Comment by JaKooLit** [comment]
alright cool.. I got it now.. Appreciate your quick reply. 

But this is my last question I promise :)

So I created another LaptopDisplay.conf file and  add as a source 

and then on edited this part as like this.

bindl = , switch:off:Lid Switch,exec,echo "monitor = eDP-1, preferred, auto, 1" > $configs/LaptopDisplay.conf
bindl = , switch:on:Lid Switch,exec,echo "monitor = eDP-1, disable" > $configs/LaptopDisplay.conf

I tested it and it works...

So my last question, is how you mean? Did I do it right?

**Comment by vaxerski** [comment]
looks fine

**Comment by JaKooLit** [comment]
Thanks.....

Before I close this.. I just want to add some notes regarding this so others, if they will search about it, will know the caveats about this approach

As ive said this is not for you Lord Vaxerski but for others

while this approach works,

bindl = , switch:off:Lid Switch,exec,echo "monitor = eDP-1, preferred, auto, 1" > $configs/LaptopDisplay.conf
bindl = , switch:on:Lid Switch,exec,echo "monitor = eDP-1, disable" > $configs/LaptopDisplay.conf

be very careful and REMEMBER to OPEN your laptop lid before shutting down your laptop. If you dont open laptop lid before shutting down, next boot, no laptop display since last entry was to disable eDP-1

**Comment by vaxerski** [comment]
`exec-once = echo "" >$configs/laptopdisplay.conf`?

**Comment by JaKooLit** [comment]
> `exec-once = echo "" >$configs/laptopdisplay.conf`?

oh my.... why I didnt thought about that...

thanks a million :)

**Comment by JaKooLit** [comment]
hmmmm I dont know if I am doing wrong but it didnt work..... while the 

exec-once = echo "" >$configs/laptopdisplay.conf

does indeed erase the contents of the laptopdisplay.conf

there is no display. Until I connect the external monitor again.


So, to give you an idea of what I am doing...
I added
exec-once = echo "" >$configs/laptopdisplay.conf

I have a Monitors.conf and contents is only
monitor=,preferred,auto,1

then I have these, on my Laptops.conf
bindl = , switch:off:Lid Switch,exec,echo "monitor = eDP-1, preferred, auto, 1" > $configs/LaptopDisplay.conf
bindl = , switch:on:Lid Switch,exec,echo "monitor = eDP-1, disable" > $configs/LaptopDisplay.conf


I close the lid, and then shutdown my laptop.


remove the external monitor, and boot up my laptop. 

NO display on laptop and will only have display once I reconnect external monitor

**Comment by JaKooLit** [comment]
sorry.... got it now

need to add like this instead :)

exec-once = echo "monitor=eDP-1,preferred,auto,1" >$configs/laptopdisplay.conf

**Comment by rafia9005** [comment]
If my monitor is only 1336, can I use 1920?

this one :
monitor = DP-3, 1920x1080@240, auto, 1

**Comment by rafia9005** [comment]
If my monitor is only 1336, can I use 1920?

this one :
monitor = DP-3, 1920x1080@240, auto, 1

**Comment by angel-gruevski** [comment]
> If my monitor is only 1336, can I use 1920?
> 
> this one : monitor = DP-3, 1920x1080@240, auto, 1

What exactly do you mean?
