### ISSUE TITLE
Autocomplete is beeing squashed in IntelliJ

### ISSUE THREAD

**Issue by caeruleusDraconis** [hyprwm/Hyprland#4093]
### Hyprland Version

Hyprland, built from branch main at commit 11d1c50420cdeaa5426b837a6479455f47368f29

### Bug or Regression?

Bug

### Description

The IntelliJ autocomplete gets squished. This happens most commonly when the list of available options gets short enough so that the autocomplete window resizes 

This happens with **and** without animations enabled. I have also tested this in sway and couldn't observe this behavior there.

### How to reproduce

1. `pacman -S intellij-idea-community-edition` (version should be `4:2023.2.4-1`)
2. Open a project and start typing somewhere and observe the outocomplete

Yes, I know. IntelliJ is with 2.07 GiB not really a minimalist application :)

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/108017831/1f621c4b-e6ac-48d8-acdf-a33771d69e9c

**Comment by JakeStanger** [comment]
Can confirm this is happening across the Intellij platform on the latest 2023.3 versions too

**Comment by cainytheslave** [comment]
Same issue here :( Some really good IDEs not beeing supported unfortunately.

**Comment by vaxerski** [comment]
it's been reported in at least 4 other issues. Intellij sucks because it abuses the hell out of x11.

**Comment by qxb3** [comment]
@vaxerski can you link us to those?

**Comment by vaxerski** [comment]
#3012 #3450 #2559 and more. They're on my `wontfix` list atm.

**Comment by mordax7** [comment]
I did not find any mention of a workaround in the other issues. Anyone already has something which could fix this squashing problem?

**Comment by vaxerski** [comment]
it's been long fixed, the fix is in -git.
