### ISSUE TITLE
Background blur extends to the decoration area of a pinned window while switching workspaces

### ISSUE THREAD

**Issue by dranull** [hyprwm/Hyprland#4094]
### Hyprland Version

11d1c50420cdeaa5426b837a6479455f47368f29

### Bug or Regression?

Bug

### Description

Default settings can be used, just pick a more colorful wallpaper to see it better.
It's easier to see when switching between empty workspaces.
I also put two floating windows on the workspaces for reference, but they're not necessary.

Note that there is another rendering issue in the video, where the whole window is hidden when the animation starts, then it will be gradually painted as the workspace slides in.

### How to reproduce

- Open a window and pin it
- Switch between workspaces back and forth

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/150595692/64244f32-87eb-44d2-8a61-06577acb130f

**Comment by vaxerski** [comment]
check with above

**Comment by dranull** [comment]
Seems to be working properly now.
