### ISSUE TITLE
Hyprland not working , gives crach report!!

### ISSUE THREAD

**Issue by heisenberg0002** [hyprwm/Hyprland#4096]
### Hyprland Version

hyprland-0.33.1-2 is up to date

### Bug or Regression?

Regression

### Description

Please someone help to solve this, tried and tired installing hyprland WM from past month , tried installing it many times but however it fails now trying to install it in endavor Os .

### How to reproduce

hyprland-0.33.1-2 is up to date -- reinstalling
warning: kitty-0.31.0-1 is up to date -- reinstalling
warning: gtk3-1:3.24.38-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (3)     Old Version  New Version  Net Change

extra/gtk3      1:3.24.38-1  1:3.24.38-1    0.00 MiB
extra/hyprland  0.33.1-2     0.33.1-2       0.00 MiB
extra/kitty     0.31.0-1     0.31.0-1       0.00 MiB

Total Installed Size:  101.71 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
(3/3) checking keys in keyring                                                                                                                [---------------------------------------------------------------------------------------] 100%
(3/3) checking package integrity                                                                                                              [---------------------------------------------------------------------------------------] 100%
(3/3) loading package files                                                                                                                   [---------------------------------------------------------------------------------------] 100%
(3/3) checking for file conflicts                                                                                                             [---------------------------------------------------------------------------------------] 100%
:: Processing package changes...
(1/3) reinstalling hyprland                                                                                                                   [---------------------------------------------------------------------------------------] 100%
(2/3) reinstalling kitty                                                                                                                      [---------------------------------------------------------------------------------------] 100%
(3/3) reinstalling gtk3                                                                                                                       [---------------------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/6) Arming ConditionNeedsUpdate...
(2/6) Compiling GSettings XML schema files...
(3/6) Probing GTK3 input method modules...
(4/6) Updating icon theme caches...
(5/6) Checking which packages need to be rebuilt
(6/6) Updating the desktop file MIME type cache...
walter-rogstrixg% hyprland
zsh: command not found: hyprland
walter-rogstrixg% Hyprland
Welcome to Hyprland!
[LOG] Instance Signature: d74607e414dcd16911089a6d4b6aeb661c880923_1702107933
[LOG] Hyprland PID: 2664
[LOG] Hyprland PID: 2664
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: walter-rogstrixg
[LOG] Release: 6.6.3-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 29 Nov 2023 00:37:40 +0000

[LOG] GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f9d] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [1002:1636] (rev c6) (prog-if 00 [VGA controller])

[WARN] Warning: you're using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Woo, animations!

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 49.09µs. Estimated average calc time: 0.11µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 19.36µs. Estimated average calc time: 0.07µs.
[LOG] Using config: /home/walter/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.71µs. Estimated average calc time: 0.03µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
[CRITICAL] Hyprland has crashed :( Consult the crash report at /home/walter/.hyprland/hyprlandCrashReport2664.txt for more information.
zsh: IOT instruction (core dumped)  Hyprland

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Sorry, didn't mean to...

Hyprland received signal 11 (Segmentation fault)

Version: d74607e414dcd16911089a6d4b6aeb661c880923
Tag: v0.33.1

System info:
	System name: Linux
	Node name: walter-rogstrixg
	Release: 6.6.3-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Wed, 29 Nov 2023 00:37:40 +0000

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f9d] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [1002:1636] (rev c6) (prog-if 00 [VGA controller])

os-release:
	NAME="EndeavourOS"
	PRETTY_NAME="EndeavourOS"
	ID="endeavouros"
	ID_LIKE="arch"
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://endeavouros.com"
	DOCUMENTATION_URL="https://discovery.endeavouros.com"
	SUPPORT_URL="https://forum.endeavouros.com"
	BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
	PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
	LOGO="endeavouros"
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x55d067257b92]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x4f4) [0x55d067226924]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x47) [0x55d0671a1df7]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7f2cfa85c710]
		??
		??:0
	#4 | /usr/lib/libwlroots.so.13032(+0x36b9a) [0x7f2cfb294b9a]
		??
		??:0
	#5 | /usr/lib/libwlroots.so.13032(+0x3af2f) [0x7f2cfb298f2f]
		??
		??:0
	#6 | /usr/lib/libwlroots.so.13032(wlr_renderer_begin_with_buffer+0x24) [0x7f2cfb292bd4]
		??
		??:0
	#7 | /usr/lib/libwlroots.so.13032(+0x53dac) [0x7f2cfb2b1dac]
		??
		??:0
	#8 | /usr/lib/libwlroots.so.13032(+0x5de6d) [0x7f2cfb2bbe6d]
		??
		??:0
	#9 | /usr/lib/libwlroots.so.13032(wlr_output_cursor_set_buffer+0xee) [0x7f2cfb2bc17e]
		??
		??:0
	#10 | /usr/lib/libwlroots.so.13032(+0x78dd3) [0x7f2cfb2d6dd3]
		??
		??:0
	#11 | /usr/lib/libwlroots.so.13032(wlr_cursor_set_xcursor+0x68) [0x7f2cfb2d7558]
		??
		??:0
	#12 | Hyprland(_ZN11CCompositor15startCompositorEv+0x604) [0x55d0671a30f4]
		??
		??:0
	#13 | Hyprland(main+0xa89) [0x55d06718b009]
		??
		??:0
	#14 | /usr/lib/libc.so.6(+0x27cd0) [0x7f2cfa845cd0]
		??
		??:0
	#15 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f2cfa845d8a]
		??
		??:0
	#16 | Hyprland(_start+0x25) [0x55d06719f035]
		??
		??:0

Log tail:
8 -> 55d067376220 (owner: OutputMgr)
[LOG] Registered signal for owner 55d068393fd0: 55d068393fe8 -> 55d067376200 (owner: PointerConstraints)
[LOG] Registered signal for owner 55d0683c0650: 55d0683c0680 -> 55d0673761e0 (owner: XDGDecoMgr)
[LOG] Registered signal for owner 55d06835bf20: 55d06835bf50 -> 55d0673761c0 (owner: VirtPtrMgr)
[LOG] Registered signal for owner 55d06835be70: 55d06835bea0 -> 55d0673761a0 (owner: VKeyboardMgr)
[LOG] Registered signal for owner 55d067bf7be0: 55d067bf7be0 -> 55d067376180 (owner: WLRRenderer)
[LOG] Registered signal for owner 55d06835c1d0: 55d06835c200 -> 55d067376160 (owner: WLRIdleInhibitMgr)
[LOG] Registered signal for owner 55d06835b850: 55d06835b880 -> 55d067376140 (owner: PowerMgr)
[LOG] Registered signal for owner 55d06835c650: 55d06835c680 -> 55d067376120 (owner: IMEMgr)
[LOG] Registered signal for owner 55d06835c5a0: 55d06835c5d0 -> 55d067376100 (owner: TextInputMgr)
[LOG] Registered signal for owner 55d06835c700: 55d06835c728 -> 55d0673760e0 (owner: ActivationV1)
[LOG] Registered signal for owner 55d06835c850: 55d06835c858 -> 55d0673760c0 (owner: SessionLockMgr)
[LOG] Registered signal for owner 55d06835b730: 55d06835b770 -> 55d0673760a0 (owner: GammaCtrlMgr)
[LOG] Registered signal for owner 55d06835c8f0: 55d06835c8f8 -> 55d067376080 (owner: CursorShapeMgr)
[LOG] Registered signal for owner 55d06835c990: 55d06835c9c0 -> 55d067376060 (owner: TearingControlMgr)
[LOG] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Running on WAYLAND_DISPLAY: wayland-1
[LOG] Attached a keyboard with name x11-keyboard
[LOG] Registered signal for owner 55d068361460: 55d06796e300 -> 55d068361468 (owner: Keyboard)
[LOG] Registered signal for owner 55d068361460: 55d06796e2f0 -> 55d0683614d0 (owner: Keyboard)
[LOG] Registered signal for owner 55d068361460: 55d06796e1d0 -> 55d0683615a0 (owner: Keyboard)
[LOG] Registered signal for owner 55d068361460: 55d06796e310 -> 55d068361538 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "x11-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout de with variant  (rules: , model: , options: )
[LOG] [hookSystem] New hook event registered: activeLayout
[LOG] Set the keyboard layout to de and variant to  for keyboard "x11-keyboard"
[LOG] New keyboard created, pointers Hypr: 55d068361460 and WLR: 55d06796e1b8
[LOG] Registered signal for owner 55d06849dd80: 55d0684734c8 -> 55d06849e1d0 (owner: )
[LOG] Registered signal for owner 55d06849dd80: 55d068473558 -> 55d06849e238 (owner: )
[LOG] Registered signal for owner 55d06849dd80: 55d068473548 -> 55d06849e2a0 (owner: )
[LOG] Registered signal for owner 55d06849dd80: 55d0684734d8 -> 55d06849e308 (owner: )
[LOG] Registered signal for owner 55d06849dd80: 55d0684734e8 -> 55d06849e370 (owner: )
[LOG] Registered signal for owner 55d06849dd80: 55d068473508 -> 55d06849e3d8 (owner: )
[LOG] Registered signal for owner 55d06849dd80: 55d068473528 -> 55d06849e440 (owner: )
[WARN] No rule found for X11-1, trying to use the first.
[LOG] Applying monitor rule for X11-1
[LOG] Set a custom mode 1920x1080@60.000000 (mode not found in monitor modes)
[LOG] output X11-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] Monitor X11-1 -> destroyed all render data
[LOG] arrangeMonitors: 1 to arrange
[LOG] arrangeMonitors: X11-1 auto [0, 0.00]
[LOG] arrangeMonitors: X11-1 xwayland [0, 0.00]
[LOG] Monitor X11-1 data dump: res 1920x1080@60.00Hz, scale 1.00, transform 0, pos 0x0, 10b 0
[LOG] Added new monitor with name X11-1 at [0, 0] with size [1920, 1080], pointer 55d0684733a0
[LOG] New monitor: WORKSPACEID 1, exists: 0
[LOG] [hookSystem] New hook event registered: createWorkspace
[LOG] [hookSystem] New hook event registered: monitorAdded
[LOG] Attached a mouse with name x11-pointer
[LOG] Registered signal for owner 55d0688ec400: 55d068473648 -> 55d0688ec4c0 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 55d068473630
[LOG] Attached a touch device with name x11-touch
[LOG] New touch device added at 55d0688d0770
[LOG] Registered signal for owner 55d0688d0770: 55d068473760 -> 55d0688d07b8 (owner: TouchDevice)

**Comment by vaxerski** [comment]
X11 backend is not supported.
