### ISSUE TITLE
Failed to start Portal service (Hyprland implementation).

### ISSUE THREAD

**Issue by Mahgozar** [hyprwm/Hyprland#4098]
### Hyprland Version

Hyprland, built from branch main at commit 6fb1b89b982eea26ecae75b93f1742537c4f31ae dirty (makefile: add rm hyprpm for uninstall (4086)). Tag: v0.33.1-9-g6fb1b89b

### Bug or Regression?

Bug

### Description

after the update every time i boot the system waybar and firefox take a very long time to lunch fixes suggested in the wiki dont work

### How to reproduce

happens after the latest update of hyprland with rebooting the system 

### Crash reports, logs, images, videos

results of the systemctl --user status xdg-desktop-portal-hyprland 
```
× xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr
/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: failed (Result: exit-code) since Sat 2023-12-09 14:44:11 +0330; 5min ago
   Main PID: 2729 (code=exited, status=127)
        CPU: 1ms

Dec 09 14:44:11 haku systemd[2370]: xdg-desktop-portal-hyprland.service: Scheduled restart job, r
estart counter is at 5.
Dec 09 14:44:11 haku systemd[2370]: xdg-desktop-portal-hyprla
nd.service: Start request repeated too quickly.
Dec 09 14:44:11 haku systemd[2370]: xdg-desktop-portal-hyprla
nd.service: Failed with result 'exit-code'.
Dec 09 14:44:11 haku systemd[2370]: Failed to start Portal service (Hyprl
and implementation).
```
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13623911/hyprland.log)

**Comment by vaxerski** [comment]
wrong tracker
