### ISSUE TITLE
Laptop monitor broken on nixos without flakes

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#410]
When I start hyprland with my config that worked before (on version 6.1) my laptop monitor shows a blank screen no matter what when I move my cursor onto it it hides and I cannot drag windows to it.

**Comment by fufexan** [comment]
> without flakes

So is the package coming from Nixpkgs?

**Comment by godalming123** [comment]
No its coming from https://github.com/hyprwm/Hyprland/wiki/Installation#without-flakes

**Comment by godalming123** [comment]
It is also possible this is a hyprland 0.7 and above issue since I have not tested that releaso on my hardware

**Comment by dmadisetti** [comment]
What graphics card are you using?

**Comment by godalming123** [comment]
It works if I remove all of my workspace and monitor settings.

**Comment by godalming123** [comment]
Turns out that my monitor no longer likes being 1080x760 (which worked on older versions) but after setting it to 1366x768 it works
