### ISSUE TITLE
fullscreen 1 fullscreens weirdly when switching monitors

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#4106]
### Hyprland Version

Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3). Tag: v0.32.3  flags: (if any) debug

### Bug or Regression?

Bug

### Description

In the images it's shown better, but, when you switch a workspace from one monitor to another, the window that had fullscreen 1 fullscreens in a weird way not intended.

### How to reproduce

Open two windows and fullscreen 1 one of them
Then, either swapactiveworkspaces or moveworkspacetomonitor.
???
Bug.

### Crash reports, logs, images, videos

before switching monitor: 
![image](https://github.com/hyprwm/Hyprland/assets/94939040/638a7496-5a2f-4371-91b6-6354b363e76f)

after switching monitor:
![image](https://github.com/hyprwm/Hyprland/assets/94939040/abac45f7-68f5-492f-9f32-4f5abfe3bf0d)

**Comment by thejch** [comment]
was fixed in https://github.com/hyprwm/Hyprland/pull/5131 i believe
