### ISSUE TITLE
Firefox lags on >60hz monitor

### ISSUE THREAD

**Issue by ricardo177m** [hyprwm/Hyprland#4109]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to v0.33.1). 
Tag: v0.33.1

flags: (if any)

### Bug or Regression?

Regression

### Description

When firefox is open it lags while scrolling. On testufo.com it inconsistently gets 144fps (getting 70fps on 144hz).
Note: nvidia mobile gpu

### How to reproduce

Upgrade from 0.31.0 (works correctly)
Open firefox (on fullscreen or floating mode this problem goes away)

**Comment by vaxerski** [comment]
maybe hw accel broke? doesn't seem like a hl issue. If you can downgrade to 0.31 and the issue goes away, please `git bisect` it.

**Comment by tchofy** [comment]
Just a hunch, might be worth it to check if it isn't the nvidia drivers causing the issue, the 545 drivers are causing frames to display out of order if the current fps and refresh rate aren't matching.

**Comment by ricardo177m** [comment]
@vaxerski I tried installing nouveau and now the problem persists even on 0.31.0, this problem did not occur on hyprland-nvidia package with nvidia drivers.

@tchofy installing nouveau didn't fix the main problem, but curiously it fixed other non-related problems :D

**Comment by ricardo177m** [comment]
Update: setting decoration:rounding to 0 fixes the problem.
Ended up adding `windowrulev2 = rounding 0, class:^[fF]irefox` to the hyprland config.
