### ISSUE TITLE
Popup treats screen local coordinates like global

### ISSUE THREAD

**Issue by Wumianzhe** [hyprwm/Hyprland#411]
When I rightclick in Dolphin, creating a popup, it behaves like there's a screen boundary, approximately at 1200/800, which is boundary in my screen setup. But popup is entirely within second screen.

Vertical monitor definitely helps to reproduce that as "right edge of left monitor" is within second monitor.

Steps to reproduce:

using config file with lines:
```
monitor=eDP-1,1920x1080@60,1200x800,1
monitor=HDMI-A-1,1920x1200@59.95,0x0,1
monitor=HDMI-A-1,transform,1
```
otherwise example config file.

Expected outcome:
Popup appearing similarly to left side of the screen
![image](https://user-images.githubusercontent.com/49762386/180504858-54abbeb1-0c6b-480d-b8b0-42eb33b70e51.png)

Noted outcome:
Screen boundary that should not exist (there's no pointer on screenshot sadly, it is near right edge of popup)
![image](https://user-images.githubusercontent.com/49762386/180505024-e8b56b68-b205-4502-8bde-3dc8ae03ce85.png)

And the most noticeable one
![image](https://user-images.githubusercontent.com/49762386/180505048-21f70422-5997-48b8-bfc5-f27254bf7b96.png)

**Comment by vaxerski** [comment]
check with cc146f03441bd1512f42d768a321a3fad110671e

**Comment by Wumianzhe** [comment]
I should do something about notifications, and bug is still there. Sorry for delay

**Comment by vaxerski** [comment]
Is this only QT? Because if so, it might just be related to #580 which was a QT issue

**Comment by Wumianzhe** [comment]
Currently unable to confirm, and will be unable for a few months in best case, so I'll close the issue
