### ISSUE TITLE
Hyprland just go black

### ISSUE THREAD

**Issue by MisileLab** [hyprwm/Hyprland#4110]
### Hyprland Version

I cant use hyprctl, but version is 0.32.3 from gentoo

### Bug or Regression?

Bug

### Description

Just go black when open
Cant use tty
(Currently I use gentoo linux)

### How to reproduce

Run hyprland via command

**Comment by vaxerski** [comment]
zero logs
zero info
zero crash reports
outdated hyprland

invalid issue

**Comment by MisileLab** [comment]
I just upgraded to 0.33.1, but issue not fixed
and im using default hyprland config for testing
log: https://bpa.st/4FMQ
@vaxerski
