### ISSUE TITLE
Can't use windowrulev2 for automatically centering floating windows

### ISSUE THREAD

**Issue by MariaSolOs** [hyprwm/Hyprland#4118]
### Hyprland Version

v0.33.1

### Bug or Regression?

Bug

### Description

I've been trying to configure Hyprland to automatically center floating windows. From the docs it seems like I should be able to achieve this with a window rule like `windowrulev2 = center, floating:1`, but that's not working.

I managed to achieve this by using the following binding to combine both dispatchers:
```
bind = SUPER, F, exec, hyprctl --batch "dispatch togglefloating ; dispatch centerwindow"
```
Although that works when using the binding, I wonder if there's a better way workaround...

### How to reproduce

Add the following to your Hyprland configuration:
```
bind = SUPER, F, togglefloating
windowrulev2 = center, floating:1
```

Toggle the floating status of a window using the `SUPER + F` mapping above. Notice how the floating window isn't automatically centered.

**Comment by phonetic112** [comment]
with the winrule it only centers when the window initially opens

**Comment by MariaSolOs** [comment]
> with the winrule it only centers when the window initially opens

It doesn't center it at all.

**Comment by phonetic112** [comment]
probably because it doesn't float by default

do `windowrulev2 = float, window`

**Comment by MariaSolOs** [comment]
> probably because it doesn't float by default
> 
> 
> 
> do `windowrulev2 = float, window`

I don't want all windows to be floating, I just want all floating windows to be centered initially.

**Comment by phonetic112** [comment]
yeah so specify the windows you want in the `window` field, that was a placeholder

**Comment by MariaSolOs** [comment]
> yeah so specify the windows you want in the `window` field, that was a placeholder

Yeah I know how window rules work, but I want _ALL_ floating windows to be centered. It's similar to this example taken from the docs:
```
windowrulev2 = opacity 0.5 0.5,floating:1
```
But instead of changing the opacity, I want to center the window.

**Comment by phonetic112** [comment]
ok, i think floating windows should automatically be centered (it is for me), what are your monitor configs?

**Comment by MariaSolOs** [comment]
@phonetic112 This is the output of `hyprctl monitors`:
```
Monitor eDP-1 (ID 0):
        2560x1440@59.99800 at 0x0
        description: LG Display 0x058B (eDP-1)
        make: LG Display
        model: 0x058B
        serial:
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 0 0 0
        scale: 2.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
        activelyTearing: false
```

And I set `monitor = , highres, auto, 2` in my config.

**Comment by phonetic112** [comment]
hm idk then, where exactly do floating windows open for you? even at different scales floating windows open up in the center for me (1080p monitor)

**Comment by MariaSolOs** [comment]
It's arbitrary, they open in different positions.
May I ask what do you have configured for `monitor` in your configuration?

**Comment by phonetic112** [comment]
`monitor = DP-1, highrr, auto, 1`

**Comment by MariaSolOs** [comment]
> `monitor = DP-1, highrr, auto, 1`

Hmmm this doesn't work for me either...

**Comment by bvr-yr** [comment]
> > yeah so specify the windows you want in the `window` field, that was a placeholder
> 
> Yeah I know how window rules work, but I want _ALL_ floating windows to be centered. It's similar to this example taken from the docs:
> 
> ```
> windowrulev2 = opacity 0.5 0.5,floating:1
> ```
> 
> But instead of changing the opacity, I want to center the window.


`opacity` is dynamic windowrule, that's why it changes. `center` is not, it is for newly spawned floating windows.


> ok, i think floating windows should already automatically be centered (it is for me), what are your monitor configs?

don't think it should, atleast neither for me. seems like window is centered relative to its tiled position, so if u have one window, it would be centered on monitor.


u can just chainbind like:
```
bind = SUPER, F, togglefloating
bind = SUPER, F, centerwindow
```

from docs:
> The keybinds will be executed in the order they were created. (top to bottom)

**Comment by MariaSolOs** [comment]
Thanks @bvr-yr for explaining! It makes sense now. 

It sounds like this is the intended design though, so I'll close this issue.
