### ISSUE TITLE
Can only resize windows to be larger when using resizeactive and resizewindow dispatchers

### ISSUE THREAD

**Issue by m-bartlett** [hyprwm/Hyprland#4119]
### Hyprland Version

Hyprland, built from branch main at commit 62a8d0be5c1959ade8410f8f964e362288f22175  (keybinds: check for null last monitor in changeworkspace (4077)). Tag: v0.33.1-3-g62a8d0be

### Bug or Regression?

Regression

### Description

When using the dispatchers `resizeactive` and `resizewindowpixel` either as a bind or directly from `hyprctl`, it seems only values for the `resizeparams` argument to these dispatchers only actually change the window's size if the resulting resize is bigger. It also has the effect of appearing as if it will only resize if the expansion is towards the opposite end of the screen.

It also appears these dispatchers have no effect on floating windows.

`hyprctrl` simply outputs `ok`, and there is no errors in my logs.

Resizing the window using the mouse drag functionality works as expected, and is currently the only way I can resize windows to be smaller.

My keybinds for resizing windows to be smaller worked in previous versions of Hyprland. There doesn't seem to be anything in [the docs for `resizeparams`](https://wiki.hyprland.org/Configuring/Dispatchers/#parameter-explanation) that explain this behavior at least that I can see. However I fully respect the possibility I am misinterpreting this dispatcher's functionality or am not using it as intended.

In the bottom-most section is a screen capture I took of using the `resizeactive` dispatcher to successfully increase window size and unsuccessfully decrease it, only being able to shrink with the mouse drag resizing.

Possibly related to https://github.com/hyprwm/Hyprland/issues/3704

### How to reproduce

Simply try to resize a window with a relative position vector that is towards the side of the screen that the window is adjacent to. My demo video below shows what I mean, but for example if you have a terminal that's adjacent to the rightmost side of the screen and you execute `hyprctl dispatch resizeactive 50 0` (i.e. resize the window 50 pixels to the right), you will observe the window does not change size.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/85039141/aef1aa1b-51ec-4318-8c95-2b262d18fb8a

Here is the only portion of my config that uses the `resizeactive` dispatcher:

```ini
## Resize mode/submap
bind=SUPER,R,submap,resize
submap=resize
    unbind = ,down
    binde = , right, resizeactive,  100 0
    binde = , left,  resizeactive, -100 0
    binde = , down,  resizeactive,  0 100
    binde = , up,    resizeactive,  0 -100
    binde = SHIFT, right, resizeactive,  10 0
    binde = SHIFT, left,  resizeactive, -10 0
    binde = SHIFT, down,  resizeactive,  0 10
    binde = SHIFT, up,    resizeactive,  0 -10
    bind = , escape,submap,reset 
    bind = , return,submap,reset 
submap=reset
```

**Comment by zach-wahrer** [comment]
Are you by chance using hy3 plugin? I'm seeing the same issue, but only when using the hy3 layout. Keybind works as expected when using the master layout.

**Comment by m-bartlett** [comment]
@zach-wahrer good catch, I am using hy3 and just tested that the resizing works as expected when I don't load the plugin. I'll close this issue since it seems to be an issue with hy3.
