### ISSUE TITLE
Screen share broken again bisected

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#4122]
### Hyprland Version

git :)

### Bug or Regression?

Bug

### Description

In google meet screen share just gives a black screen 
bisected 
```
❯ git bisect bad
d02ba422daae97498ffe6cdf84914b74ddf1fd44 is the first bad commit
commit d02ba422daae97498ffe6cdf84914b74ddf1fd44
Author: Vaxry <vaxry@vaxry.net>
Date:   Sun Dec 10 19:30:14 2023 +0000

    hyprpm: guard empty command

    fixes #4114

 hyprpm/src/main.cpp | 5 +++++
 1 file changed, 5 insertions(+)
```

With love :heart: 

### How to reproduce

build your own fancy pants Hyprland

**Comment by vaxerski** [comment]
if that's the result of the bisect then your problem is not hyprland
