### ISSUE TITLE
2d screen for vr support

### ISSUE THREAD

**Issue by ivanbalashov239** [hyprwm/Hyprland#4125]
### Description

looking into using hyprland with vr/ar glasses(headmounted display with 3dof) (xreal for example)

what i would like to have(if it doesnt require redesign pr from me is possible) is a regular 2d desktop, with a viewport for the visible part of UI that moves according to 3dof sensors(head position)
and optionally two overlapping viewports providing 3d effect for two eyes (side by side 3d)

Do you think its possible without significant changes to the current code base?

P.S An alternative that i can think of(without implementing the whole wm myself) would be to have a lightweight wayland compositor that displays a nested wayland compositor and provides only support for the "headmovement", would that be easier/slicker?

**Comment by vaxerski** [comment]
excuse me _what_?

This is definitely not something I will implement, but if I understand this correctly, you can make this a plugin.

**Comment by ivanbalashov239** [comment]
Oh, I completely understand you won't do it yourself, it was more of a
question if it's technically feasible.

And I now realize that discord would probably be a better place for such a
question.

P.S. for anyone interested, if I ever get to implement it in any way, I
will post a link here
