### ISSUE TITLE
Inconsistent focus when scrolling in master layout

### ISSUE THREAD

**Issue by LanderMoerkerke** [hyprwm/Hyprland#4127]
### Hyprland Version

v0.33.1

### Bug or Regression?

Bug

### Description

If in master layout and you switch focus using the `swapnext` and `swapprev` bindings to a different window, the scrolling affects the original focused window and not the current active window. This is the case when the mouse doesn't move and only the scroll is utilised.

The bug does not occur if the layout is set to the default, dwindle layout.

### How to reproduce

1. Open two windows that are scrollable
2. Move the focus to the other window
3. Use the scroll wheel or scroll functionality of the trackpad to scroll
4. Observe the scroll to affect the 1st window 

```
monitor=,preferred,auto,1.3

input {
    mouse_refocus = false
}

$mainMod = SUPER

general {
    border_size = 2
    col.active_border = 0xffff0000
    layout = master
}

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev

bind = $mainMod, Return, exec, alacritty
```

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/20244592/fce277fc-388f-455e-9c0d-4c3bf754e998

**Comment by LanderMoerkerke** [comment]
Might be related to: !3227

**Comment by vaxerski** [comment]
can you test #5074

**Comment by LanderMoerkerke** [comment]
> can you test #5074

I tried to build it but failed to do so. Manual building is currently a bit flaky on Arch linux with the added dependency of `hyprcursor` and not yet up to date dependencies. 

Will test once the repositories are up to date.
