### ISSUE TITLE
Unable to start onlyoffice

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#413]
https://0x0.st/ojag.log
Terminal:
```
╭─kyle@arch ~
╰─➤  /opt/onlyoffice/desktopeditors/DesktopEditors
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
[1]    98409 IOT instruction (core dumped)  /opt/onlyoffice/desktopeditors/DesktopEditors
```
I can confirm onlyoffice works on sway.
Setting QT platfrom to xcb or wayland doesn't help

**Comment by vaxerski** [comment]
you're either missing qt5-wayland or onlyoffice doesn't support wayland and you need to run it with `QT_QPA_PLATFORM=xcb`

**Comment by KyleUltimate** [comment]
nvm, I just happen to launch it incorrectly. I should use `/usr/bin/onlyoffice-desktopeditors` instead of directly using `/opt/onlyoffice/desktopeditors/DesktopEditors`
