### ISSUE TITLE
I cant pass the login screen

### ISSUE THREAD

**Issue by CainaGN** [hyprwm/Hyprland#4131]
### Hyprland Version

0.32.3

### Bug or Regression?

Bug

### Description

I just installed Hyprland for the very fisrt time, but i cant access it because every time i try to log in, it just goes back to the login screen. The crash reports says something about the keyboard not being loaded cuz it couldnt find the layout. During the installation i typed ptbr (i meant brazilian portuguese, but maybe it was pt-br instead). I wuold try to change it for testing but i dont know how

### How to reproduce

Sorry, i have no idea about how one can reproduce this error

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Vaxry is going to be upset.

Hyprland received signal 11 (Segmentation fault)

Version: 9afdd61adeaf413afbe853dbc5fdf6853c8bde21
Tag: v0.32.3

System info:
	System name: Linux
	Node name: caina
	Release: 6.5.0-14-generic
	Version: #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023

GPU:
	0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

os-release:
	PRETTY_NAME="Ubuntu 23.10"
	NAME="Ubuntu"
	VERSION_ID="23.10"
	VERSION="23.10 (Mantic Minotaur)"
	VERSION_CODENAME=mantic
	ID=ubuntu
	ID_LIKE=debian
	HOME_URL="https://www.ubuntu.com/"
	SUPPORT_URL="https://help.ubuntu.com/"
	BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
	PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
	UBUNTU_CODENAME=mantic
	LOGO=ubuntu-logo
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x61) [0x555aad1d68d1]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x5bf) [0x555aad189e0f]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x40) [0x555aad0fa2a0]
		??
		??:0
	#3 | /lib/x86_64-linux-gnu/libc.so.6(+0x42910) [0x7ff902242910]
		??
		??:0
	#4 | /lib/x86_64-linux-gnu/libc.so.6(+0x19045c) [0x7ff90239045c]
		??
		??:0
	#5 | Hyprland(_ZNSt16basic_format_argISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE8_M_visitIZNS1_19_Formatting_scannerIS3_cE13_M_format_argEmEUlRT_E_EEDcOS9_NS1_6_Arg_tE+0x4ec) [0x555aad13c52c]
		??
		??:0
	#6 | Hyprland(+0xd97a1) [0x555aad1087a1]
		??
		??:0
	#7 | Hyprland(_ZSt7vformatB5cxx11St17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE+0x141) [0x555aad13e011]
		??
		??:0
	#8 | Hyprland(_ZN13CInputManager21applyConfigToKeyboardEP9SKeyboard+0xaf5) [0x555aad260335]
		??
		??:0
	#9 | Hyprland(_ZN13CInputManager11newKeyboardEP16wlr_input_device+0x4dc) [0x555aad2614fc]
		??
		??:0
	#10 | Hyprland(_ZN6Events17listener_newInputEP11wl_listenerPv+0xb2) [0x555aad1aa002]
		??
		??:0
	#11 | /lib/x86_64-linux-gnu/libwayland-server.so.0(wl_signal_emit_mutable+0x7c) [0x7ff902d326ec]
		??
		??:0
	#12 | /lib/x86_64-linux-gnu/libwayland-server.so.0(wl_signal_emit_mutable+0x7c) [0x7ff902d326ec]
		??
		??:0
	#13 | /home/caina/Debian-Hyprland/Hyprland/subprojects/wlroots/build/libwlroots.so.12032(+0x570f8) [0x7ff902dd20f8]
		??
		??:0
	#14 | /home/caina/Debian-Hyprland/Hyprland/subprojects/wlroots/build/libwlroots.so.12032(+0x56613) [0x7ff902dd1613]
		??
		??:0
	#15 | /home/caina/Debian-Hyprland/Hyprland/subprojects/wlroots/build/libwlroots.so.12032(+0x5c805) [0x7ff902dd7805]
		??
		??:0
	#16 | Hyprland(_ZN11CCompositor15startCompositorEv+0x56f) [0x555aad11120f]
		??
		??:0
	#17 | Hyprland(main+0xb12) [0x555aad0e5402]
		??
		??:0
	#18 | /lib/x86_64-linux-gnu/libc.so.6(+0x280d0) [0x7ff9022280d0]
		??
		??:0
	#19 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7ff902228189]
		??
		??:0
	#20 | Hyprland(_start+0x25) [0x555aad0fa135]
		??
		??:0

Log tail:
[LOG] Registered signal for owner 555aaef76920: 555aaef769a8 -> 555aad36cb00 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef769b8 -> 555aad36cac0 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef769c8 -> 555aad36caa0 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef769d8 -> 555aad36ca80 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef76a18 -> 555aad36c9e0 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef76a08 -> 555aad36c9c0 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef76a28 -> 555aad36c9a0 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef76a48 -> 555aad36c980 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef769e8 -> 555aad36c960 (owner: WLRCursor)
[LOG] Registered signal for owner 555aaef76920: 555aaef769f8 -> 555aad36c940 (owner: WLRCursor)
[LOG] Registered signal for owner 555aae65f900: 555aae65f918 -> 555aad36cd20 (owner: Backend)
[LOG] Registered signal for owner 555aae63daa0: 555aaefe50e8 -> 555aad36ccc0 (owner: Seat)
[LOG] Registered signal for owner 555aae63daa0: 555aaefe50f8 -> 555aad36cca0 (owner: Seat)
[LOG] Registered signal for owner 555aae63daa0: 555aaefe5138 -> 555aad36cc20 (owner: Seat)
[LOG] Registered signal for owner 555aae63daa0: 555aaefe5148 -> 555aad36cc00 (owner: Seat)
[LOG] Registered signal for owner 555aae63daa0: 555aaefe50f8 -> 555aad36cca0 (owner: Seat)
[LOG] Registered signal for owner 555aae63daa0: 555aaefe5118 -> 555aad36cc80 (owner: Seat)
[LOG] Registered signal for owner 555aaefe5350: 555aaefe5370 -> 555aad36ce20 (owner: LayerShell)
[LOG] Registered signal for owner 555aaef75210: 555aaef75230 -> 555aad36ce80 (owner: OutputLayout)
[LOG] Registered signal for owner 555aaefe5570: 555aaefe55a8 -> 555aad36cc60 (owner: OutputMgr)
[LOG] Registered signal for owner 555aaefe5570: 555aaefe55b8 -> 555aad36cc40 (owner: OutputMgr)
[LOG] Registered signal for owner 555aaefe5650: 555aaefe5680 -> 555aad36cbe0 (owner: InhibitMgr)
[LOG] Registered signal for owner 555aaefe5650: 555aaefe5690 -> 555aad36cbc0 (owner: InhibitMgr)
[LOG] Registered signal for owner 555aaef76e00: 555aaef76e18 -> 555aad36cce0 (owner: PointerConstraints)
[LOG] Registered signal for owner 555aaefe54c0: 555aaefe54f0 -> 555aad36cba0 (owner: XDGDecoMgr)
[LOG] Registered signal for owner 555aaef77000: 555aaef77030 -> 555aad36cd00 (owner: VirtPtrMgr)
[LOG] Registered signal for owner 555aaef76f50: 555aaef76f80 -> 555aad36ca00 (owner: VKeyboardMgr)
[LOG] Registered signal for owner 555aae762020: 555aae762020 -> 555aad36cb80 (owner: WLRRenderer)
[LOG] Registered signal for owner 555aaef77390: 555aaef773c0 -> 555aad36cb60 (owner: WLRIdleInhibitMgr)
[LOG] Registered signal for owner 555aaef767a0: 555aaef767d0 -> 555aad36ca60 (owner: PowerMgr)
[LOG] Registered signal for owner 555aaef77810: 555aaef77840 -> 555aad36ca40 (owner: IMEMgr)
[LOG] Registered signal for owner 555aaef77760: 555aaef77790 -> 555aad36ca20 (owner: TextInputMgr)
[LOG] Registered signal for owner 555aaef778c0: 555aaef778e8 -> 555aad36cde0 (owner: ActivationV1)
[LOG] Registered signal for owner 555aaef77a10: 555aaef77a18 -> 555aad36c920 (owner: SessionLockMgr)
[LOG] Registered signal for owner 555aaef75160: 555aaef751a0 -> 555aad36c900 (owner: GammaCtrlMgr)
[LOG] Registered signal for owner 555aaef77ab0: 555aaef77ab8 -> 555aad36c8e0 (owner: CursorShapeMgr)
[LOG] Registered signal for owner 555aaef77b50: 555aaef77b80 -> 555aad36c8c0 (owner: TearingControlMgr)
[LOG] Registered signal for owner 555aae63d800: 555aaef771a0 -> 555aad36ce40 (owner: DRM)
[LOG] Registered signal for owner 555aae65f990: 555aae65faf0 -> 555aad36cb40 (owner: Session)
[LOG] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Running on WAYLAND_DISPLAY: wayland-1
[LOG] Attached a keyboard with name Video Bus
[LOG] Registered signal for owner 555aaefeceb0: 555aaf05db80 -> 555aaefeceb8 (owner: Keyboard)
[LOG] Registered signal for owner 555aaefeceb0: 555aaf05db70 -> 555aaefecf20 (owner: Keyboard)
[LOG] Registered signal for owner 555aaefeceb0: 555aaf05da50 -> 555aaefecff0 (owner: Keyboard)
[LOG] Registered signal for owner 555aaefeceb0: 555aaf05db90 -> 555aaefecf88 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
[LOG] Attempting to create a keymap for layout ptbr with variant  (rules: , model: , options: grp:alt_shift_toggle)
[ERR] Keyboard layout ptbr with variant  (rules: , model: , options: grp:alt_shift_toggle) couldn't have been loaded.
[LOG] [hookSystem] New hook event registered: activeLayout

**Comment by CainaGN** [comment]
It was the keyboard. It is solved

**Comment by ChromanicAI** [comment]
> It was the keyboard. It is solved

Mark the issue as solved then please
