### ISSUE TITLE
Resize on border cursor stays after switching workspace

### ISSUE THREAD

**Issue by elijahimmer** [hyprwm/Hyprland#4133]
### Hyprland Version

Hyprland, built from branch  at commit v0.32.3  (). Tag:  flags: (if any) debug

### Bug or Regression?

Bug

### Description

If your cursor is changed to the resizing cursor while you switch to a workspace, the cursor stays that way until you go over another border.

I could not do it reliably enough, but what made this more annoying is that if you spawn a window and switch workspace, during the animation the cursor will be over the border, change to resizing, then not go back to normal until I go over another border.

### How to reproduce

Have general:resize_on_border on.
Place your cursor on the edge of a window so that it shows you can resize the window.
Move to a empty workspace. (or just one without a window where your cursor is)

The mouse is stuck in this state until you hover over another border.

It seems to stop applications from changing the cursor, I assume from the compositor overriding the application's set cursor.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/73551650/c7efc30b-b524-4822-9bcb-c841f765a205

**Comment by vaxerski** [comment]
I believe this was reported somewhere
