### ISSUE TITLE
Xwayland windows allow interaction with windows from different workspaces

### ISSUE THREAD

**Issue by Elandig** [hyprwm/Hyprland#4135]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Bug

### Description

I was fixing Steam's context menus and now whenever I open any context menu, I can interact with windows from different workspaces by clicking on any window besides the context menu parent.

Rules that I used:
```
windowrulev2 = stayfocused, title:^(?!.*Steam Settings)$, class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$, class:^(steam)$
```

### How to reproduce

1. Make sure to set window rules;
2. Open some window you want to interact with;
3. On a second workspace, open up Steam (or any any other program that has to use this window rule workaround) tiled with some window or placed on a different monitor;
4. Open any context menu by clicking or hovering in the UI (essentially open any window affected by this rule);
5. Try clicking on other windows besides the context parent (could be on other monitors), ending up interacting with windows from workspaces underneath.

### Crash reports, logs, images, videos

Starting video playback from another workspace

https://github.com/hyprwm/Hyprland/assets/15586732/88f84fbe-929d-4dab-b5b8-3dfc6f90958d

**Comment by Elandig** [comment]
Okay, I figured out that it's not even related to stayfocused window rule, it just makes it easier to reproduce it.
I can interact with windows from other workspaces just by clicking the gaps/borders of xwayland windows.

**Comment by vaxerski** [comment]
can you test on -git?

**Comment by Elandig** [comment]
Yeap, it still persists.
```
Hyprland, built from branch main at commit b2e5a80e2ff1fcbf8164a45c5ef8ebffbb511fae dirty (hyprpm: Link against tomlplusplus when using cmake (4145)).
Tag: v0.33.1-39-gb2e5a80e

flags: (if any)
debug
```

**Comment by Elandig** [comment]
Running [an example config](https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.conf) does not cause this issue, so there must be something up with my config.
I'll try to find out what's causing this.

**Comment by Elandig** [comment]
I'm so confused.

I tweaked the example config and I managed to unreliably recreate it. It only happened if I started xwayland applications from my external bigger monitor (I have a laptop with an external monitor connected, both have 1920x1080 resolution with scaling set to auto.)
```
Monitor eDP-1 (ID 0):
	1920x1080@60.00400 at 0x0
	description: BOE (eDP-1)
	make: BOE
	model: ***********
	serial:
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-2 (ID 1):
	1920x1080@60.00000 at 1920x0
	description: BNQ BenQ *********** (DP-2 via HDMI)
	make: BNQ
	model: BenQ ***********
	serial: ***********
	active workspace: 9 (9)
	special workspace: 0 ()
	reserved: 0 30 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```
So it's somehow PPI related?
I believe the culprit was XCURSOR_SIZE set to 14. After changing it to 24, the issue appears to be resolved. (I need to test it further, since it happened with many other xwayland apps during my workflow)

**Comment by Elandig** [comment]
I've tried all possible configurations, from changing monitor scale, disconnecting external monitors, changing gaps/border sizes, window rules and environment variables. It's all the same.
I'm able to reproduce it using [an example config](https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.conf) and the latest commit.
```
Hyprland, built from branch main at commit 01e5c59d752d3fe7fa484330fa48e010054b8fa1 dirty (Revert xwayland: push invisible windows outside layout).
Tag: v0.33.1-40-g01e5c59d

flags: (if any)
debug
```
### How to reproduce

- Start an xwayland application (Something that would open with multiple windows, like Steam, so it's easier to test with them tiled);
- Hop on a second workspace;
- Start another xwayland application (In my case, it's FreeTube);
- Hop onto the first workspace and start interacting with a second workspace window by clicking precisely on the gaps.

**Comment by AndreasYNY** [comment]
Hello, I also experienced this issue, i notice it only happen on chromium apps like spotify, VSC and freetube with xwayland. for me it happened randomly and i still don't know what triggers it. I will try to use ozone layer and see if it still doing the same.
[video](https://streamable.com/749p8p)

<details close>
<summary>Versions Info</summary>
<br>


- `xorg-xwayland 23.2.3-1`
- `FreeTube io.freetubeapp.FreeTube 0.19.1 Beta stable user` (flatpak, running on xwayland)
- `Visual Studio Code com.visualstudio.code 1.84.2-1699528352 stable user` (flatpak, running on xwayland)
- 
```
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).

Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0
  
  flags: (if any)
```

</details>

**Comment by FelipeJz** [comment]
Experiencing the same issue between brave and chromium apps, it seems to be triggered some times after moving windows around with the mouse. To stop it i have to close such window.

**Comment by FelipeJz** [comment]
After some time dealing with this issue i noticed that making the apps full screen and back solves it without needing to close them. I hope this is resolved soon is really annoying

**Comment by Elandig** [comment]
I've noticed that this issue affects all wlroots-based compositors in one way or another. I decided to give Hyprland another try, since it has become independent, and now it appears to be fixed.
