### ISSUE TITLE
Unable to get sirula id

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#414]
https://0x0.st/oja0.log
Normally, you can get any window's id with `hyprctl clients` but with sirula, you can't.
You can't move it either.
https://github.com/DorianRudolph/sirula

**Comment by vaxerski** [comment]
maybe, apps written in rust behave very weirdly. It's a known issue

**Comment by vaxerski** [comment]
is this still an issue? Also, are you sure it's a window? It seems like a layersurface to me

**Comment by KyleUltimate** [comment]
Nope, I might thought it was a window... 2 month ago
