### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by umop3plsdn** [hyprwm/Hyprland#4141]
### Hyprland Version

Newest

### Bug or Regression?

Bug

### Description

Trying to manually compile I pull in all dependencies with --recursive then try to build it all dependencies are found except for tomlplusplus and build fails

### How to reproduce

git clone --recursive https://github.com/hyprwm/Hyprland.git       
meson setup build

**Comment by vaxerski** [comment]
tomlplusplus is a dependency that is not bundled - use your system's package manager.

Please do not report such build failures - ci passes so it's an issue on your side.

**Comment by umop3plsdn** [comment]
I don't have a package manager I use LFS. Anyways, thanks for your time

**Comment by vaxerski** [comment]
that's a problem that should be reported to fedora. Maybe hpp is in a separate `-devel` package?

**Comment by ilyazub** [comment]
hpp is available for Fedora 39 (not 38): https://fedora.pkgs.org/39/fedora-updates-x86_64/tomlplusplus-devel-3.4.0-1.fc39.x86_64.rpm.html.

Why not `meson wrap install tomlplusplus` instead?

**Comment by BenMcAvoy** [comment]
I'm on Linux Mint, tried installing tomlplusplus from source as it's not in repos.

It installed to `/usr/local/include/toml++`. I tried moving it to `/usr/include/toml++` and some other things such as setting prefixes.

After many attempts I'm still getting:
```cmake
-- Setting link libraries
Could not open input file: No such file or directory
Could not open input file: No such file or directory
-- Checking for module 'toml++'
--   No package 'toml++' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  hyprpm/CMakeLists.txt:12 (pkg_check_modules)```

I tried `meson wrap install tomlplusplus` and I'm still getting this (Sorry, I do not typically work with C++ build tools other than gcc)
