### ISSUE TITLE
Regression: Wayland applications don't open with a not supported refresh rate

### ISSUE THREAD

**Issue by CactiChameleon9** [hyprwm/Hyprland#4147]
### Hyprland Version

v0.32.3

### Bug or Regression?

Regression

### Description

I upgraded to NixOS 23.11 and I could no longer open wayland applications on Hyprland

I have problems when I use `monitor=eDP-1,1920x1080@68,auto,1` in my config  
I don't have problems when I use `monitor=eDP-1,1920x1080@60,auto,1` in my config

- swaybg didn't startup
- fuzzel gave an error `err: wayland.c:2012: no monitors`

Terminator does run however, not entirely sure why.. but most applications completely fail to launch

Running at 68Hz has no problems in Hyprland 0.25.0

### How to reproduce

Probably on a laptop,

Run your monitor at 68Hz and see that wayland applications fail to start
Edit your config back to 60Hz and see that everything now runs normally

### Crash reports, logs, images, videos

I started at 60Hz. Opened terminator. Tested fuzzel. Edited my hyprland config in terminator to 68Hz. Tested fuzzel (twice, one shortcut one cli). Logged out of Hyprland
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13659740/hyprland.log)

I have swapped back and forth between 68 and 60 hertz several times during this session:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13659671/hyprland.log)

**Comment by vaxerski** [comment]
I don't think 68Hz is a valid mode...? is it listed under the available modes in `wlr-randr`?

**Comment by CactiChameleon9** [comment]
No it isn't listed.
```
eDP-1 "Chimei Innolux Corporation 0x151E (eDP-1)"
  Make: Chimei Innolux Corporation
  Model: 0x151E
  Serial: (null)
  Physical size: 340x190 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000999 Hz (preferred, current)
    1680x1050 px, 60.000999 Hz
    1280x1024 px, 60.000999 Hz
    1440x900 px, 60.000999 Hz
    1280x800 px, 60.000999 Hz
    1280x720 px, 60.000999 Hz
    1024x768 px, 60.000999 Hz
    800x600 px, 60.000999 Hz
    640x480 px, 60.000999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
```

It somehow worked before however, with a notable increase in smoothness and no problems running applications. Increasing above 68 would cause massive display glitches.

**Comment by CactiChameleon9** [comment]
Just tested, 50 and 40 Hz also both cause the same issues.

**Comment by vaxerski** [comment]
do they work on sway?

**Comment by CactiChameleon9** [comment]
Yes it does work in sway, I had to use --custom modes, but it does work.

**Comment by vaxerski** [comment]
can you `git bisect` it? idk how to do so on nix tho you might wanna ask @fufexan

**Comment by CactiChameleon9** [comment]
Help with the equivalent of git bisecting on nixos would be appreciated @fufexan. I am not currently using flakes, which I imagine would make said process a bit easier

**Comment by fufexan** [comment]
Glad you found a solution. An alternative solution that lets you use releases pushed to Nixpkgs (so no compiling) would be to have an extra channel `nixpkgs-hyprland` and manually set that to revisions where Hyprland was updated.

**Comment by CactiChameleon9** [comment]
Turns out that nix refuses to build your older flake packages because of syntax errors, I will try with nix-store versions... which will unfortunately be less precise

**Comment by fufexan** [comment]
It should have no issues since everything's self-contained. Can you post one of those errors, or tell me the commit you tried to build from?

**Comment by CactiChameleon9** [comment]
```
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/skzb00cq9vb43ryyr8dyzxlqmqmfy0ss-nixos-23.11/nixos/lib/attrsets.nix:922:11:

          921|         || pred here (elemAt values 1) (head values) then
          922|           head values
             |           ^
          923|         else

       … while evaluating the attribute 'value'

         at /nix/store/skzb00cq9vb43ryyr8dyzxlqmqmfy0ss-nixos-23.11/nixos/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'enableNvidiaPatches'

       at /nix/store/wjsns8ds9d69cklbkwjq12yzhs86dx6g-source/nix/default.nix:1:1:

            1| {
             | ^
``` 

2fed1badbfb3b5a10641ee41c55d7fa7c21682c8

**Comment by CactiChameleon9** [comment]
Worked fine with master.tar.gz, but not 2fed1badbfb3b5a10641ee41c55d7fa7c21682c8.tar.gz

**Comment by fufexan** [comment]
I managed to build it fine using `nix build github:hyprwm/hyprland/2fed1badbfb3b5a10641ee41c55d7fa7c21682c8`. I need a full stacktrace and the code you're using to get the flake-compat-built hyprland into your config.

**Comment by CactiChameleon9** [comment]
```
let
	flake-compat = builtins.fetchTarball "https://github.com/edolstra/flake-compat/archive/master.tar.gz";
	hyprland-flake = (import flake-compat { src = builtins.fetchTarball "https://github.com/hyprwm/Hyprland/archive/2fed1badbfb3b5a10641ee41c55d7fa7c21682c8.tar.gz"; }).defaultNix;
in
{
	programs.hyprland = {
		enable = true;
	    package = hyprland-flake.packages.${pkgs.system}.hyprland;
	};
}
```

**Comment by fufexan** [comment]
Oh, I see the issue. The module is out of sync with the package. The module expects the package to have certain override flags, but it may or may not have them.

I think your best bet is building through the CLI, or have that code in a separate file that you can `nix-build`, and running hyprland manually from tty.

**Comment by CactiChameleon9** [comment]
Just tried that... seems it won't launch on my system? My guess old new driver proplem?
[hyprlandCrashReport176570.txt](https://github.com/hyprwm/Hyprland/files/13678509/hyprlandCrashReport176570.txt)

**Comment by fufexan** [comment]
Ah, yes. With all the glibc and other stuff happening, it's probably easier to switch your system entirely.
An alternative would be to clone the repo, checkout a commit, `nix flake lock --update-input nixpkgs` and try to build it.
Or entering the devshell and manually building with meson & ninja.

There are many ways to go about it, but none are trivial.

**Comment by CactiChameleon9** [comment]
Hmph. I may just have to boot up a traditional distro to bisect this. I am not that used to flakes (I haven't needed them up till now), and most of what I can find is flakey (excuse the pun)

**Comment by fufexan** [comment]
You can totally use legacy Nix to build this as well, you just need to add a `default.nix` file like [here](https://github.com/fufexan/nix-gaming/blob/master/default.nix) and then you can use `nix-build -A hyprland`.

**Comment by CactiChameleon9** [comment]
I am downgrading my system to a temporary minimal config. I should manage to run the older builds from there, hopefully I should start making progress

**Comment by CactiChameleon9** [comment]
I found a full on hyprland crash when changing refresh rate at b4f123d1f2af8e7b42c730789d863aa22ea9fb56

But that doesn't match my behaviour (as it crashes before I can test anything). Should I say good or bad?

[hyprlandCrashReport272407.txt](https://github.com/hyprwm/Hyprland/files/13678904/hyprlandCrashReport272407.txt)

**Comment by fufexan** [comment]
Say good and search again.

**Comment by CactiChameleon9** [comment]
Next build 563fe83db269bb19e796cf6b21d3e1bcbf1b41f1 has same crashing behaviour, good again?

**Comment by fufexan** [comment]
I suppose so.

**Comment by CactiChameleon9** [comment]
:unamused: 
```
c5d1faf72dc5e7e4fa357007974ced0f573f1f32 is the first bad commit
commit c5d1faf72dc5e7e4fa357007974ced0f573f1f32
Author: vaxerski <vaxerski@users.noreply.github.com>
Date:   Sat Nov 11 14:53:18 2023 +0000

    [gha] Nix: update wlroots

 flake.lock               | 8 ++++----
 flake.nix                | 2 +-
 subprojects/wlroots.wrap | 2 +-
 3 files changed, 6 insertions(+), 6 deletions(-)
```

**Comment by fufexan** [comment]
Sounds like wlroots broke it. Sway still works because it's on versioned wlroots, so it didn't reach this commit yet.

**Comment by CactiChameleon9** [comment]
That was the commit that fixed crashing on refresh change. All commits >= that one have the refresh-change no fuzzel.

I never actually had a good-good commit. I will need to bisect again assuming that a crash is bad.

**Comment by CactiChameleon9** [comment]
```
daniel@danielLaptop ~/T/Hyprland ((ae69b9a2)|BISECTING)> git bisect good
d63a42e93fc49f57f69270ad70adea008a3bafec is the first bad commit
commit d63a42e93fc49f57f69270ad70adea008a3bafec
Author: Mihai Fufezan <fufexan@protonmail.com>
Date:   Sat Aug 26 12:07:08 2023 +0300

    Nix & Meson: bump wlroots

 flake.lock               | 8 ++++----
 flake.nix                | 2 +-
 subprojects/wlroots.wrap | 2 +-
 3 files changed, 6 insertions(+), 6 deletions(-)
```

OK. So it is indeed wlroots.

To summarise:
-  ?? - d63a42e93fc49f57f69270ad70adea008a3bafec  :  no crashing, unsupported refresh rate without issues
- d63a42e93fc49f57f69270ad70adea008a3bafec - c5d1faf72dc5e7e4fa357007974ced0f573f1f32  :  crashing on unsupported refresh rate
- c5d1faf72dc5e7e4fa357007974ced0f573f1f32 - ??  :  unsupported refresh rate with launching wayland app issues

**Comment by vaxerski** [comment]
yep, I'll close this. Feel free to come back here if it proves to be a hyprland issue.

**Comment by CactiChameleon9** [comment]
Just wanted to provide a quick update (for future reference): now working again in the version of v0.35.0
