### ISSUE TITLE
crash with "[LOG] Callback xxxxxxx -> xxxxxxx, textInput removed."

### ISSUE THREAD

**Issue by valerino** [hyprwm/Hyprland#4149]
### Hyprland Version

Hyprland, built from branch main at commit 167f2ed3b2bb18ceeabb831ac80b655ef8e16867 dirty (border: fix failed assert on small windows). Tag: v0.33.1-23-g167f2ed3

### Bug or Regression?

Bug

### Description

random crash, happens often. daemon is crashed, waybar still running and i can still use the desktop somehow.

obviously, no keybind works until i reboot/logout to restart the daemon.

### How to reproduce

it's random, i sincerely don't know how exactly to trigger it.

the only thing i can say is that i have 2 monitors, one with the browser (chrome) and the other with vscode. 

that's what is running on my desktop 99,99% of the times  when i realize hyprland is crashed, and recently hyprland started to crash this way very often.

happens also when resuming from hibernation, but not necessarily always.

### Crash reports, logs, images, videos

[hyprlandCrashReport189629.txt](https://github.com/hyprwm/Hyprland/files/13660799/hyprlandCrashReport189629.txt)

**Comment by vaxerski** [comment]
this is not a crash. You ran `hyprctl dispatch exit`
