### ISSUE TITLE
Some apps takes a ridiculously long time to open

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#415]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.
I've tried this
`exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`
no help
`exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`
Similar stuff, also no help.
Currently I'm trying to use `wezterm` and `sirula`, both takes a super long time to open.
The logs clearly says it successfully launch it, but in fact I can't see anything on my screen.
https://0x0.st/ojBi.log
```
[LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:1 sirula
[LOG] Process Created with pid 16044
```

**Comment by KyleUltimate** [comment]
After further inspection, enabling wayland in wezterm fixes it, but I have to have it off for my input method to work.
I've failed to find any workarounds for sirula

**Comment by KyleUltimate** [comment]
Found a really really really werid way to fix this problem
1. Login into hyprland, will notice the programs are launching very slowly.
2. Logout, and logie to sway. And the launch the programs you need in sway.
3. Log out sway, and login into

**Comment by vaxerski** [comment]
the apps you're trying to launch are probably gtk / dbus, you probably have a part of the xdg portals broken (most likely xdg-desktop-portal) and dbus times out after 30s.

**Comment by KyleUltimate** [comment]
yep, after using the special version in the AUR, it works flawlessly!

**Comment by KyleUltimate** [comment]
well, I still have to do some weird xdg-desktop-portal hacks.
```bash
#!/bin/bash
systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user start wireplumber
/usr/lib/xdg-desktop-portal-wlr -r
```
I ran this script, and it works! although from what I've heard, doesn't xdg-desktop-portal will be spawned whenever any programs needs it?

**Comment by vaxerski** [comment]
> doesn't xdg-desktop-portal will be spawned whenever any programs needs it?

no, afaik, it has to be running at all times.
