### ISSUE TITLE
Swaylock not working anymore

### ISSUE THREAD

**Issue by stauersbol** [hyprwm/Hyprland#4150]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).

### Bug or Regression?

Bug

### Description

When trying to lock screen swaylock will refuse to start up.

### How to reproduce

1. Install Swaylock with latest version of Hyprland
2. Open a terminal and write `swaylock`

### Crash reports, logs, images, videos

This is the exact error message I'm getting. This could however be a issue with swaylock
`2023-12-13 18:23:55 - [main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely`

**Comment by stauersbol** [comment]
Duplicate of multiple issues

**Comment by vaxerski** [comment]
is #4092 it #4080 really #4065 that #4058 fucking #3932 hard #2937 to use the damn search feature?
