### ISSUE TITLE
Wlroots logs 

### ISSUE THREAD

**Issue by Exatio** [hyprwm/Hyprland#4151]
As mentionned in #4030, I went to the wlroots gitlab in order to fix this issue.
Unfortunately, I can't find wlroots logs anywhere.
I asked on reddit, someone brought up systemd journal but it doesnt seem to be the case.
It doesn't seem to be in the hyprland.log file either, so I'm here asking you : where can I find the wlroots debug logs.
Thanks

**Comment by vaxerski** [comment]
this is not a place for questions. Move to discussions or the discord server for such.

enable wlroots logs:
```
env = HYPRLAND_LOG_WLR,1
```

enable logs to a file:
```
debug {
    disable_logs = false
}
```

log will be in `/tmp/hypr/<instance>/hyprland.log`
