### ISSUE TITLE
VM crashes when opening kitty through default installation

### ISSUE THREAD

**Issue by G4mingJon4s** [hyprwm/Hyprland#4152]
### Hyprland Version

v0.33.1

### Bug or Regression?

Bug

### Description

Installed basic hyprland setup for arch linux inside a vm. 3D acceleration is active. I triple-checked that all dependencies are installed.
Running `Hyprland` shows the default installation with the basic config. Pressing SUPER + Q to open kitty crashes the entire vm.
Says it wants to read some specific memory address. The address never changes. No crash report was generated.

The file manager dolphin works just fine, though I did not test any other applications.

### How to reproduce

1. Install basic arch linux using the latest iso on a vm.
2. Follow the hyprland installation tutorial.
3. Run hyprland and press SUPER + Q

### Crash reports, logs, images, videos

![Bild_2023-12-13_210151890](https://github.com/hyprwm/Hyprland/assets/40526179/33ee3996-4703-47a5-9516-a90352e6da26)
Translation:
The instruction in *first address* points to memory in *second address*. The process *read* couldn't be executed.

**Comment by vaxerski** [comment]
I think that's a problem with your vm. There is a nullptr deref somewhere in it, it seems.

**Comment by G4mingJon4s** [comment]
So, looked for some vm settings I could change, but none seemed to fix it. I found this stack trace using `journalctl`. Not sure if it helps. I have no idea what is happening here. This error repeats a few times before the vm crashes.
![Bild_2023-12-13_214740473](https://github.com/hyprwm/Hyprland/assets/40526179/702ccd95-c496-4e97-8231-f9adcaa119df)

**Comment by vaxerski** [comment]
that looks like a throw from a failed init, check your logs
