### ISSUE TITLE
League of Legends client disappears if the workspace it is on is not focused when it becomes active. 

### ISSUE THREAD

**Issue by xusiai** [hyprwm/Hyprland#4154]
### Hyprland Version

Hyprland, built from branch  at commit 4de986072c12af8081f877f4792d57b4a11a0a6a 

### Bug or Regression?

Bug

### Description

The League of Legends client disappears when it becomes active on a non-focused workspace. This happens with and without focus_on_activate set to true. League has been broken (unrelated to Hyprland) on Linux for most of the past three weeks so I'm not sure of the exact date _when_ this started occurring however the client did not vanish prior to that so it would have been introduced within the past month. 

### How to reproduce

1. Open League client and queue for a match.
2. Send the client to its own workspace or leave it where it is and switch to a new workspace.
3. Wait for the queue to pop.
4. Client has now vanished but is still running.

**Comment by vaxerski** [comment]
can you update

**Comment by xusiai** [comment]
Updated to commit f7cde9c92cb9e7c908f18ecf10ebdb366d0832b5 and it works as expected now. Thanks!

**Comment by xusiai** [comment]
This seems broken once more and I couldn't find another issue opened. It isn't working on aeeeace102c14ea0ab4df6840ee225e1b14ea970 but it hasn't been working for about a week.
