### ISSUE TITLE
cursor_inactive_timeout requires moving cursor to activate

### ISSUE THREAD

**Issue by dusanx** [hyprwm/Hyprland#4156]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Bug

### Description

Marked as bug as I am fairly new on Hyprland so I don't know if it is regression, please feel free to change.
With ```cursor_inactive_timeout = 3``` set, cursor is hiding as expected but when spawning new application (terminal or firefox for example), if the hidden cursor happens to be on top of newly spawned window, cursor is shown and *does not* hide again unless moved. Even slight move triggers normal behavior, if left intact it won't hide at all.
Desired behavior: If already hidden, cursor should stay hidden regardless of if it covers newly spawned window or not.

### How to reproduce

1. Set cursor_inactive_timeout to any few seconds value
2. Wait cursor to hide
3. Using keyboard bind, spawn firefox or terminal (happens with all applications for me)
    - see cursor reappearing since first application covers most of the screen
4. Move cursor around, wait to hide, spawn few more applications.
    - if the (hidden) cursor coordinates fall within boundaries of newly spawned window, it will reappear and won't hide before mouse moves cursor, even slightly.
    - if the (hidden) cursor doesn't cover newly spawned window, it will stay hidden and behave properly.

### Crash reports, logs, images, videos

I have lots of experience with programming and debugging so I would be happy to help, just let me know what you need.

**Comment by dusanx** [comment]
Update, confirming initial report, and a temporary fix:

If I use usual ```bind = $mainMod SHIFT, RETURN, exec, $terminal```, hidden cursor will re-appear if it happens to be withing newly spawned terminal window boundaries, and block any hiding before I move cursor.

Hovever if I move cursor to 0,0, so it is over waybar on top, before spawning terminal, with ```bind = $mainMod SHIFT, RETURN, exec, hyprctl dispatch movecursor 0 0 && $terminal``` it won't re-appear since it won't ever be over newly spawned window.

As a temporary fix this could work for me, I'll modify every exec I have to use 'movecursor' before spawning application, but it remains to be something that doesn't behave properly.

**Comment by andresilva** [comment]
Duplicate of https://github.com/hyprwm/Hyprland/issues/3698.

**Comment by dusanx** [comment]
Closing this duplicate to continue working in #3698
