### ISSUE TITLE
osu-lazer crashes on launch (on arch), on wayland, on 0.33.0 and later (0.32.3 is fine)

### ISSUE THREAD

**Issue by DJXJD** [hyprwm/Hyprland#4158]
### Hyprland Version

Hyprland, built from branch main at commit f7cde9c92cb9e7c908f18ecf10ebdb366d0832b5 dirty (Nix: remove duplicate options from modules (4012)). Tag: v0.33.1-41-gf7cde9c9  flags: (if any) debug

### Bug or Regression?

Bug

### Description

When launching osu-lazer via command line, process exits after this message:
`wp_viewport@38: error 2: source rectangle out of buffer bounds`

`SDL_VIDEODRIVER=wayland,x11` is present. Without that env var, osu-lazer successfully spawns an xwayland window to run in, but has other issues.

### How to reproduce

1) Install osu-lazer from [here](https://aur.archlinux.org/packages/osu-lazer)
2) Make sure `SDL_VIDEODRIVER=wayland,x11` is present as an environment variable
3) Run `osu-lazer` in command line
4) See output

### Crash reports, logs, images, videos

[This](https://github.com/ppy/osu/issues/25657) issue seems related, but the claim is made there that the issue is either with wayland, hyprland, or sdl... notably not osu itself.

In case it helps, here is my hyprland config. In case scaling is related, ill point out that I have 2 monitors, and both are at 1.25.
[hyprland.conf](https://github.com/hyprwm/Hyprland/files/13679281/hyprland.conf.txt)

**Comment by vaxerski** [comment]
that's a protocol error. it's osu's fault. Well, could be SDL's too.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/e55d4e22-b3d0-4999-bce5-2cebe61edac3)

It started crashing because wlroots improved their checks, see https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3766

**Comment by vaxerski** [comment]
does this also happen on sway-git?

**Comment by DJXJD** [comment]
Just checked, this does not also happen on sway-git. Also, thank you very much for the quick reply 😁

**Comment by vaxerski** [comment]
"does not also happen".... so does it or doesnt?

**Comment by DJXJD** [comment]
so far it didn't, but i just realized that i didn't 100% ensure that osu-lazer wasn't running under xwayland, so im gonna go do that now and report back

**Comment by DJXJD** [comment]
ok confirmed, running `SDL_VIDEODRIVER=wayland osu-lazer` works just fine

**Comment by vaxerski** [comment]
odd

**Comment by vaxerski** [comment]
can you `git bisect` the issue just to make sure it's a wlroots bump causing this?

**Comment by DJXJD** [comment]
Sure, I'll get back to you with that shortly

**Comment by zakk4223** [comment]
Even more odd: I'm on arch, sdl 2.28.5-1, hyprland v0.33.1-31-g8f384878 and osu-lazer seems to work just fine for me

**Comment by DJXJD** [comment]
Sorry for the delay... I was unfortunately unable to build hyprland on any commit but the latest, whether fully from source, or using the -git aur package...

I'd be happy to try bisecting again if I got some help though

**Comment by vaxerski** [comment]
in that case, please provide a log of osu when launched with `WAYLAND_DEBUG=1`

**Comment by DJXJD** [comment]
Here you go

[osu-lazer_wayland_debug.log](https://github.com/hyprwm/Hyprland/files/13687667/osu-lazer_wayland_debug.log)

**Comment by vaxerski** [comment]
this is an osu bug to me:
`wl_surface@37` gets `wp_viewport@38` which after some valid-looking viewports gets this:
```
[ 330254.136]  -> wp_viewport@38.set_source(0.00000000, 0.00000000, 3440.00000000, 1440.00000000)
```

later, `wl_surface@37` gets `wl_buffer@46` which is:
```
[ 330564.480]  -> zwp_linux_buffer_params_v1@48.create_immed(new id wl_buffer@46, 1595, 1738, 875713112, 0)
```
meaning you get a viewport source of 3440x1440 on a surface of 1595x1738.

Does this happen without display scaling too?

**Comment by DJXJD** [comment]
Just saw and tested this now, works fine without display scaling

**Comment by vaxerski** [comment]
did you accidentally test sway-git without scaling?

If not, could you provide the wayland debug log of osu on sway with scaling?

**Comment by DJXJD** [comment]
Aie aie aie, i tested on fully default sway-git... So, i would imagine that means without scaling... I'll go test again, this time with scaling! If it works, I'll provide the wayland debug log

**Comment by DJXJD** [comment]
Ok, so, when running osu-lazer in wayland mode on sway-git, with proper display scaling, the window shows up fullscreen at the correct aspect ratio, but with a decreased resolution. When i change the resolution in osu settings to 3440x1440, the osu window disappears and `wp_viewport@38: error 2: source rectangle out of buffer bounds` gets output to the terminal... In that case, even though i couldn't see the window, i could still hear the music.

**Comment by DJXJD** [comment]
Seems like when osu remembers the resolution, it crashes at launch on sway as well. However, after 1 crash on launch, the next launch spawns a window on my second monitor, also at a reduced resolution.

**Comment by DJXJD** [comment]
Some times, interacting with that second messed up launch of osu crashes sway instantly. Other times, trying to set the monitor back to my primary monitor causes sway to crash. Either way, with display scaling, osu-lazer doesn't behave the way it should on sway-git either...

**Comment by vaxerski** [comment]
then it's a problem with osu. Most likely their interaction with SDL.

The wayland debug logs show a clear indication of invalid viewporter data. Try reporting to osu / SDL.
