### ISSUE TITLE
Difficulty binding XF86Fn

### ISSUE THREAD

**Issue by apple-corps** [hyprwm/Hyprland#4161]
I have a config like http://0x0.st/HYPP.conf

In the config above, I've been setting keybindings using a variable like `$mainMod = Ctrl` and `bind = $mainMod` ... . Now I want to change the key to `XF86Fn` which is in the left most corner of my keyboard. (US macOS layout)

Perhaps the `Ctrl` key is special modifier keytype because when I set `$mainMod = XF86Fn` and similar, I get errors.  I read the wiki within the bounds of my limited capacity regarding sections on variables, binds, and including 

https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Binds/#uncommon-syms--binding-with-a-keycode

Then by the bind definition in the wiki:     I think I have to set `$mainMod = ",XF86Fn,"` . Perhaps because XF86Fn is not a special Mod key. ( 1 ) . This is cumbersome if true coming from the configuration above because it suggests a specific ordering different than above when using the desired key.

I thought perhaps the ordering needed to change for my keybindings because of ( 1 ). But I tried this and it also failed, even with a skeleton configuration.

I explained my ignorance in https://discord.com/channels/961691461554950145/967398886530515067/1185116874032304138  .

Will someone help relieve my ignorance?

**Comment by vaxerski** [comment]
are you trying to bind the fn key? it's a hardware key, it doesn't get sent to the OS.

**Comment by apple-corps** [comment]
> are you trying to bind the fn key? it's a hardware key, it doesn't get sent to the OS.

I don't think that's true. For example, wev shows key press events for this key.

```
[14:     wl_keyboard] key: serial: 11788; time: 2971696; key: 472; state: 1 (pressed)
                      sym: XF86Fn       (268964304), utf8: ''
[14:     wl_keyboard] key: serial: 11789; time: 2971844; key: 472; state: 0 (released)
                      sym: XF86Fn       (268964304), utf8: ''
```


Also see comment by Asahi lead dev:

https://www.reddit.com/r/AsahiLinux/comments/zmuz5l/comment/j0f8xsn/?utm_source=share&utm_medium=web2x&context=3

**Comment by vaxerski** [comment]
if it's not a hardware key on your keyboard, you can bind it like any other key. Fn is _not_ a modifier, and cannot be used as one, though.

**Comment by apple-corps** [comment]
> you can bind it like any other key

I tried setting my poorly named `$mainMod = ",XF86Fn,"` or even renaming the variable to` $notMod = ",XF86Fn,"` and rewriting the configuration even with a minimal configuration.

Two challenges arrive. The specific ordering required for special modifier keys. But even with bindings set without modifiers, I believe the configuration would not load. I will give it another shot and create another issue if it will not work.

**Comment by vaxerski** [comment]
you're not allowed to bind multiple keys to an action. That's why it doesn't work.

**Comment by tchofy** [comment]
If wev catches it, it's likely https://github.com/sezanzeb/input-remapper would catch it too, then you could bind it to a modifier key and do what you want.

**Comment by guttermonk** [comment]
Using a US MacOS keyboard also, in theory should you be able to use [keysym combos](https://wiki.hypr.land/Configuring/Binds/#keysym-combos) to use Fn as a mod key? I know that "Fn is not a modifier" but neither is escape or apostrophe, and the wiki shows the following example where they use the Escape and Apostrophe keysyms as mod keys:

> If you are feeling a little wild... you can use other keys for binds...
> binds = Escape&Apostrophe&F7, T&O&A&D, exec, battletoads 2: retoaded

If that's true, shouldn't something like this also work?
```
binds = XF86Fn, n, sendshortcut, , Home,
binds = XF86Fn, o, sendshortcut, , End,
binds = XF86Fn, i, sendshortcut, , Page_Up,
binds = XF86Fn, e, sendshortcut, , Page_Down,
```
