### ISSUE TITLE
Overlay layer does not cover waybar (on bottom layer)

### ISSUE THREAD

**Issue by aserowy** [hyprwm/Hyprland#4162]
### Hyprland Version

Hyprland, built from branch  at commit v0.32.3  (). Tag:   flags: (if any) debug

### Bug or Regression?

Bug

### Description

Heho,

i am using waybar and rofi. In rofi i configured width and height to cover 100%. `hyprctl layers` shows, that the overlay with namespace rofi starts exactly after the namespace waybar which is in layer bottom.

```sh
$  hyprctl layers
Monitor HDMI-A-1:
	Layer level 0 (background):
		Layer 29b5160: xywh: 3440 0 1200 1920, namespace: swww
	Layer level 1 (bottom):
		Layer 21be780: xywh: 3440 0 50 1920, namespace: waybar
	Layer level 2 (top):
	Layer level 3 (overlay):
		Layer 2152e80: xywh: 3490 0 1150 1920, namespace: rofi
```

The effect is shown in the picture and does the exact thing shown in the layers output (rofi starts 50px further right).

My current config for Hypr is here:
https://github.com/aserowy/dots/blob/main/home/modules/hyprland/hyprland.conf

### How to reproduce

Install and run waybar and rofi.

### Crash reports, logs, images, videos

![screenshot-20231215-111252](https://github.com/hyprwm/Hyprland/assets/8199164/1b663ba0-cbaf-4e61-aec8-d8c0169368e8)

**Comment by vaxerski** [comment]
https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-layer-shell-unstable-v1.xml#L171-174

**Comment by aserowy** [comment]
@vaxerski 

The specification specifies, that non exclusive zones can specify how to interact with exclusive zones. How is it possible i can tell the rofi layer to extend over the exclusive zone in Hyprland?

> Surfaces that do not wish to have an exclusive zone may instead specify how they should interact with surfaces that do. If set to zero, the surface indicates that it would like to be moved to avoid occluding

Kind regards
Alexander

**Comment by aserowy** [comment]
And this is the example given in the specification, which describes exactly the behavior im looking for:

> For example, a panel might set its exclusive zone to 10, so that maximized shell surfaces are not shown on top of it. A notification might set its exclusive zone to 0, so that it is moved to avoid occluding the panel, but shell surfaces are shown underneath it. A wallpaper or lock screen might set their exclusive zone to -1, so that they stretch below or over the panel.
>
> The default value is 0.

**Comment by aserowy** [comment]
@vaxerski 

I got it now. The indication has to be set by the 'client' Application, which iniciates the layer. Thus, rofi in my case! Thanks for giving me the hint with the specification :D

I found that setting

```rasi
window {
  fullscreen: true;
}
```

in .rasi will do exactly that!
