### ISSUE TITLE
Allow floating windows to auto resize

### ISSUE THREAD

**Issue by navidmafi** [hyprwm/Hyprland#4164]
### Description

Allow resizing of windows based on the application request.

Current behavior forces the box boundary which squishes the application to that boundary which causes problems for several apps that change their window size based on user interactions including but not limited to

- All of JetBrains IDEs (Popups either don't show or they are displayed scaled/squished)
- Telegram Desktop 
- Windscribe VPN Client

Windscribe after opening the dropdown location selection list (Not Using XWayland)
![20231215_17h20m34s_grim](https://github.com/hyprwm/Hyprland/assets/46371349/a55b2284-714d-4ae7-ae7c-7768d314a600)

JetBrains popups can't resize to a logical size and fill the screen height or display incorrectly  (Using XWayland)

![image](https://github.com/hyprwm/Hyprland/assets/46371349/05169881-7989-42c8-92e7-995430e39351)

![image](https://github.com/hyprwm/Hyprland/assets/46371349/354bd217-b100-46b0-b944-c62064b6950c)

A window resize is required for Telegram desktop to show the sidebar after enabling it (Not Using XWayland)
![20231215_17h18m26s_grim](https://github.com/hyprwm/Hyprland/assets/46371349/9e9be911-6f29-4f64-b28e-7ceb5a7fe249)

**Comment by vaxerski** [comment]
floating apps are allowed to resize themselves, they just have to ask for it in a better way than some do.

See e.g. ulauncher for a native app that knows how to resize itself, or mpv.

I'll loosen the requirements for wl a bit, sure, but I have no clue if it will help (I dont have windscribe to test) and the xwayland bug is a separate issue.

**Comment by vaxerski** [comment]
should be improved a bit with 395ab3ba370f5e12fcba594232c338c16deef0ed

**Comment by AlpSha** [comment]
Does anyone have a config that helps with Jetbrains popup issue? It is so annoying. I literally code without using any autocompletion. Or I stop typing, close the current popup and open new one because each new letter causes it to be not readable anymore :(

**Comment by vaxerski** [comment]
IIRC it was broken in 0.30.0, so you could downgrade. It's tracked elsweyr, I forgot issue #, there are like 10. Search for intellij

**Comment by AlpSha** [comment]
I have some config that requires the newer versions. Though I can change these config for now. Thanks @vaxerski. It is still same after your commit. I just got a build from master
![image](https://github.com/hyprwm/Hyprland/assets/41454613/245e2f77-9a38-4fba-af90-788dbd1b7746)

**Comment by UnFunnyGuy** [comment]
is there any workaround for this? its just really annoying

**Comment by navidmafi** [comment]
`Hyprland, built from branch HEAD at commit 0dc0b95853a00fd70da244483e593640cc6f58a3

Windscribe works much better now and does not get squashed on window resize which is nice

JetBrains popups are still problematic 

![20231217_17h57m29s_grim](https://github.com/hyprwm/Hyprland/assets/46371349/2fb72515-ae0b-461d-a667-a1ec97531ef0)

**Comment by vaxerski** [comment]
because jetbrains popups are a different issue how many times do I have to reiterate

**Comment by AlpSha** [comment]
Maybe just once with a more clear explanation. Because it was not clear which issue you refer to on your previous entry. Be safe

**Comment by vaxerski** [comment]
this should be fixed on git

**Comment by navidmafi** [comment]
> because jetbrains popups are a different issue how many times do I have to reiterate

It wasn't clear from your previous response

Maybe add a pinned issue about the JetBrains bug and explain everything and link people to that when they ask/get confused?
