### ISSUE TITLE
broken window screensharing in armcord flatpak and nix version of webcord-vencord in arch linux

### ISSUE THREAD

**Issue by beh-10257** [hyprwm/Hyprland#4165]
### Hyprland Version

hyprland-git 0.33.1.r44.79d8d14f-1

### Bug or Regression?

Bug

### Description

when I screenshare specifically a window hyprland will crash in both flatpak armcord and nix webcord-vencord
tested with stable hyprland it didn't crash there but it was a black screen
these issues don't exist on the aur version of both webcord and vencord

### How to reproduce

enter any of the formentioned app and screenshare a window
screensharing a region or the screen works

### Crash reports, logs, images, videos

[hyprlandCrashReport6819.txt](https://github.com/hyprwm/Hyprland/files/13689698/hyprlandCrashReport6819.txt)
[hyprlandCrashReport8468.txt](https://github.com/hyprwm/Hyprland/files/13689699/hyprlandCrashReport8468.txt)

one of them is webcord the other is armcord hopefully both of them point to the same bug
yeah peace and love

+ I want to point out that if this is a problem with flatpak or nix since no problem in the aur
at least I expect hyprland to not crash until session restore comes around at least

**Comment by vaxerski** [comment]
check with above

**Comment by beh-10257** [comment]
@vaxerski wasn't fixed sadly
[hyprlandCrashReport23171.txt](https://github.com/hyprwm/Hyprland/files/13689852/hyprlandCrashReport23171.txt)
[hyprlandCrashReport28667.txt](https://github.com/hyprwm/Hyprland/files/13689853/hyprlandCrashReport28667.txt)

**Comment by vaxerski** [comment]
check with above

**Comment by beh-10257** [comment]
@vaxerski its now fixed thanks a lot ヽ(´▽`)/
