### ISSUE TITLE
"hyprctl activeworkspace" shows wrong info when in a special workspace

### ISSUE THREAD

**Issue by FullStackAlex** [hyprwm/Hyprland#4166]
### Hyprland Version

0.33.1

### Bug or Regression?

Bug

### Description

When focused on a window in a special workspace, `hyprctl activeworkspace` shows the workspace below the special workspace. Since it was always the case, I'm not sure whether it's a bug or an intended feature... But now I'm trying to implement a couple things through scripting where I rely on correct information about the active workspace. I've tried to circumvent this by using `hyprctl activewindow` and its `workspace.id` property. But it obviously doesn't work when the focused workspace is empty. Instead it shows info about some other windows. So it would be really cool to behave `hyprctl activeworkspace` the same way with special workspaces as with normal workspaces.

### How to reproduce

1. open a terminal in a special workspace. 
2. run `hyprctl activeworkspace`

**Comment by vaxerski** [comment]
#3406
