### ISSUE TITLE
Fullscreen weird mouse behaviour on HIDPI Screen

### ISSUE THREAD

**Issue by Mewsen** [hyprwm/Hyprland#417]
I have a 4k Display and when i start a game, my mouse is not where it should be and sometimes my mouse is stuck inside the game window.

It's not on every game but most games not sure why some games work.

video: https://www.youtube.com/watch?v=iP6i0Vi9Wb4
my config : https://pastebin.com/DNTAq7K3

**Comment by vaxerski** [comment]
I'll look into it tomorrow. Is it maybe possible that the games that do work run in native Wayland? If so, that would be an easy explanation. Also, if they are Wine/Proton, have you tried turning on virtual desktop? generally fixes a LOT of game issues. (winecfg -> graphics tab)

**Comment by Mewsen** [comment]
Wine virtual desktop fixed it, Thank you !
