### ISSUE TITLE
Steam is transparent

### ISSUE THREAD

**Issue by SrEstegosaurio** [hyprwm/Hyprland#4173]
### Hyprland Version

Hyprland, built from branch  at commit b1b8d732e64ecf527baef010ad2f28ed3b8c4ac1  ().

### Bug or Regression?

Bug

### Description

The Steam window is transparent. It is possible to interact with the menus _(you can even see some of them while hovering with the mouse over)_ and even open games but the client itself is unusable. The loading windows that appear during lunch are also visible.

A screenshot for reference:
![image](https://github.com/hyprwm/Hyprland/assets/49443421/b88c9005-9390-4735-89e3-18e0a74a8e34)

### How to reproduce

Open Steam in Hyprland.

### Crash reports, logs, images, videos

Hyprland log:
https://privatebin.net/?27af7b0f512ba413#8Gr4r6LahxgbQtgcRxnXE79BjUCyra6tBT9dZYxyocqJ

Let me know if anything else is needed. I will be happy to provide more information.

**Comment by vaxerski** [comment]
looks like a steam issue. Does it happen in sway? What if you resize the window?

**Comment by SrEstegosaurio** [comment]
It does work without problems in Sway.

_(I think I should note that this is an Nvidia optimus laptop and that Hyprland runs in the iGPU while Sway was running in the dGPU)_.

**Comment by vaxerski** [comment]
what if you run hl on dgpu? what if you disable hw accel in steam?

**Comment by tchofy** [comment]
Me and other users have had issues with it flickering. Nvidia and Steam's CEF hardware acceleration don't work well together, should be able to "fix" it while using with the dgpu by going to `Steam > Settings > Interface > Untick Enable GPU accelerated rendering in web views` and restart steam.

**Comment by SrEstegosaurio** [comment]
That fixed the issue for me, thanks!

_(And also sorry for the late response)_.
