### ISSUE TITLE
alterzorder not working

### ISSUE THREAD

**Issue by CreativeKittens** [hyprwm/Hyprland#4175]
### Hyprland Version

v0.33.1-48-g9ca0c7d8v0.33.1-48-g9ca0c7d8

### Bug or Regression?

Bug

### Description

i have little script to open certain app on certain workspace, it will open new instance if window not found using hyprctl clients, if window is found in certain workspace then it will focus to it instead using hyprctl focus. the problem is when there is other window on full screen, it will focus but it's on the bottom of that other window, i tried to use hyprctl dispatch alterzorder but it doesn't work, maybe my script is wrong, maybe i don't understand enough alterzorder i'm still not sure the param alterzorder in documentation `zheight[,window]` what is that mean, any help?

### How to reproduce

here's the script to reproduce

usage: $PATH_TO_SCRIPT.sh [workspace_id] [window_class] [program/binary/runscript]

```
#!/bin/bash

workspace_id=$1
class=$2
program=$3

shift 3  # Shift the first two arguments (workspace_id and program) out

window_address=($(hyprctl clients -j | jq -r --arg class "$class" --arg workspace_id "$workspace_id" '.[] | select(.workspace.id == ($workspace_id | tonumber)) | select(.class == $class) | .address'))

echo $window_address

if [[ $window_address != "" ]]; then
  hyprctl --batch "dispatch workspace $workspace_id; dispatch focuswindow address:$window_address; hyprctl dispatch alterzorder top,address:$window_address"
else
  hyprctl dispatch workspace $workspace_id
  "$program" "$@"
fi
```

**Comment by dranull** [comment]
Remove "hyprctl" from the `hyprctl dispatch alterzorder top,address:$window_address"` part in your `--batch` request.

**Comment by CreativeKittens** [comment]
> Remove "hyprctl" from the `hyprctl dispatch alterzorder top,address:$window_address"` part in your `--batch` request.

my bad there, but still not working, somehow stil not wroking, the window still won't to go to the top

**Comment by CreativeKittens** [comment]
i'm expecting the behaviour similar to `cyclenext `in terms of z order on fullscreen, i'm expecting focuswindow dispatch will do that automatically but it's not, the focused window still on the bottom. but the windows is focused based on what i see in waybar window title

**Comment by dranull** [comment]
Ahh, I missed the fullscreen part, zorder won't help here then.
By the way, the root cause seems to be the same as in #4172 (I know the window is moved there, but similarly the switch won't happen).

**Comment by vaxerski** [comment]
alterzorder is only for floating windows
