### ISSUE TITLE
first workspace vanishes when doing a workplace swipe guesture

### ISSUE THREAD

**Issue by knoc-off** [hyprwm/Hyprland#4178]
### Hyprland Version

Hyprland, built from branch  at commit 3bb9c7c5cf4f2ee30bf821501499f2308d616f94  (). Tag:   flags: (if any) debug

### Bug or Regression?

Bug

### Description

This only happens in the first workspace, no matter what window is on it. other workspace are completely unaffected 
if you only partially swipe do it it still stays gone until switching away and back again.
using the workspace switch ie, mod 1,2,3. works fine.

it seems to be specifically transitioning away from using gestures, to with gestures works fine.

### How to reproduce

https://github.com/knoc-off/nixos/tree/d4d2405a47e742a56d15553704cf32a4cdfdc966
my nixos configs. please let me know if i can send any info

using intel integrated graphics. 

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13698046/hyprland.log)

**Comment by vaxerski** [comment]
#3437
