### ISSUE TITLE
HEAD crashes in radeon.si

### ISSUE THREAD

**Issue by davidsielert** [hyprwm/Hyprland#4180]
### Hyprland Version

main

### Bug or Regression?

Bug

### Description

Crashed on startup

### How to reproduce

download and install hyprland-git using makepkg -si

### Crash reports, logs, images, videos

[hyprlandCrashReport69259.txt](https://github.com/hyprwm/Hyprland/files/13698232/hyprlandCrashReport69259.txt)
[hyprlandCrashReport82731.txt](https://github.com/hyprwm
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/13698247/hyprland.conf.txt)
/Hyprland/files/13698233/hyprlandCrashReport82731.txt)
[coredump.txt](https://github.com/hyprwm/Hyprland/files/13698238/coredump.txt)

**Comment by vaxerski** [comment]
#4179
