### ISSUE TITLE
dragging interactive widgets no longer working in some applications

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#4186]
### Hyprland Version

0.33.1.r48.9ca0c7d8

### Bug or Regression?

Regression

### Description

After maybe one or two weeks I decided to update hyprland again, and since then, I am no longer able to drag sliders or  knobs in Bitwig Studio

### How to reproduce

1. Download bitwig-studio (has a free demo mode)
2. Drag the volume slider on a track or drag knobs to turn them
3. They move the slightest bit, as if the clicks were registered as single mouse clicks

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13706824/hyprland.log)

**Comment by UltraBlackLinux** [comment]
Two problems:
1. I've never done this before, but I guess the git docs can somewhat help
2. I'm using the AUR package (hyprland-git) to install hyprland, and I have no idea how to do bisecting in there

**Comment by UltraBlackLinux** [comment]
I cannot compile the bisect result since the part of the build script that does something in tmpwlr tries to copy a nonexistant library file to the packaging directory, I did however notice something: The commit I just mentioned is actually not from the second most recent version I had installed. That was in fact https://github.com/hyprwm/Hyprland/commit/11d1c504 and since that commit actually has something to do with focus I'd actually say the issue was introduced around about there. To clarify: The commit that I linked to *works*, but the newest commit doesn't

**Comment by vaxerski** [comment]
is there anything besides bitwig that I can test this on

**Comment by UltraBlackLinux** [comment]
I'm sorry but bitwig is everything that I encountered this on... I assume that similarly working applications have the same problem.

What sets the bitwig widgets apart is that they grab the mouse when you use them. I think there's some weird kind of focus issue where it instantly ungrabs or focuses some invisible popup where it shouldn't

**Comment by UltraBlackLinux** [comment]
I just noticed that it in fact _is_ a focus problem. The moment it should grab the mouse the focus shortly moves to an invisible window before returning back to the application, and thus ungrabbing the mouse.
It's not related to follow_mouse - I just tried toggling that, but no change.

**Comment by UltraBlackLinux** [comment]
I found something at last: This weird selection issue seems to completely de-select the window as a whole.

I ran this script: `while true; do hyprctl activewindow | grep initial;  sleep 0.01; done` and after trying to drag a widget it showed no window class and no window title, so it's not an issue with a popup or something like that. It's straight up losing focus out of the blue...

**Comment by vaxerski** [comment]
sounds like xwayland shenanigans

**Comment by UltraBlackLinux** [comment]
it is related to hyprland though, since it was working with a previous build.

Bitwig is running on xwayland though, you are correct at that.

**Comment by UltraBlackLinux** [comment]
I asked the Bitwig community and I was told that Wayland support is not going to be a thing anytime soon since wayland does not support embedding windows, which is apparently required for audio plugins to work properly

**Comment by UltraBlackLinux** [comment]
> is there anything besides bitwig that I can test this on

can I ask why you're so hesitant to install bitwig? If it's not because you have better things to do, then the only problem I'm seeing is that the package is like 300 megs big, but you can find bitwig in the aur and chaotic aur. It has a trial (which is infinite I believe) that doesn't require an account or anything like that, so it's pretty easy to test it

**Comment by UltraBlackLinux** [comment]
I just found out that the aur just uses git for their makefiles, so I was able to use an older revision, manually git bisected the commits, and this is the bad commit: https://github.com/hyprwm/Hyprland/commit/ba2af6f86d26fbf4b51aa37bf901e0118f46bbe3

Please add a toggle for that or something like that ;) 
Sorry for the hassle, this really wasn't too difficult

**Comment by vaxerski** [comment]
right. Probably needs a check for active grabs. I'll whip up a patch later, currently in italy in a bus

**Comment by UltraBlackLinux** [comment]
@vaxerski Ding Ding

**Comment by UltraBlackLinux** [comment]
did you even get the notification? or are you already working on it?

**Comment by vaxerski** [comment]
I have shit real life stuff going on and I just forgot. Sec

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14045753/patch.txt)
try this

**Comment by UltraBlackLinux** [comment]
Hmm, there's some problem with the patch, applied against the master branch:
```
error: patch failed: src/events/Windows.cpp:639
error: src/events/Windows.cpp: patch does not apply
```

**Comment by UltraBlackLinux** [comment]
could you merge that?

**Comment by vaxerski** [comment]
I could

**Comment by abstractionmage** [comment]
I just want to add that I experienced a similar issue today as the one OP described, only less frequent (I only occasionally lose focus when dragging sliders in Bitwig, but not always). I was able to get around it with the following window rules:

```
windowrulev2 = stayfocused, class:com.bitwig.BitwigStudi
windowrulev2 = noinitialfocus, class:com.bitwig.BitwigStudi
``` 

The obvious downside is that I am now unable to unfocus Bitwig without switching workspaces, but that's a limitation that I will happily accept.

**Comment by UltraBlackLinux** [comment]
we've also found a workaround a while back in the bottom most closed issue from the list right above your comment.

to cut it short: https://github.com/hyprwm/Hyprland/issues/6543#issuecomment-2399352274

**Comment by abstractionmage** [comment]
Thanks, this workaround works even better and has none of the downsides of the one I found.
For the convenience of others finding this thread through a search engine like me, here it is:
```
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
```

**Comment by RegularTetragon** [comment]
that is to say

```
windowrule = match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0, no_focus on
```
in the parlance of our times
