### ISSUE TITLE
overwatch in floating mode follows me through workspaces

### ISSUE THREAD

**Issue by BluewyDiamond** [hyprwm/Hyprland#4189]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1

### Bug or Regression?

Bug

### Description

This does not happen with fullscreen or maximize cause of nofullscreenrequest or nomaximizerequest. Is nofloatingrequest a thing?

### How to reproduce

Launch Overwatch, put it in floating mode and switch between workspaces.

**Comment by vaxerski** [comment]
fixed in git
