### ISSUE TITLE
Add touchpad settings to demo config

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#419]
since version 0.7.0 1:1 gestures have been added to hyprland but I cannot get them to work I get the error
```
Errror setting value <1> for field <input:touchpad:natural_scroll>: No such field
```
So I looked at the demo config and the option is not set so I don't know how to set it properly (also could natural scrolling be the default)

**Comment by vaxerski** [comment]
> (also could natural scrolling be the default)

no cuz it stinks.

Done in 92d1d21a3d2c5027cb8702274006c24f70df13c6
