### ISSUE TITLE
Different acceleration settings for different devices

### ISSUE THREAD

**Issue by Ahwxorg** [hyprwm/Hyprland#4192]
### Description

I'd like to tell Hyprland to force no acceleration on my mouse, but use default acceleration on my trackpad. My mouse name is glorious-model-o and my trackpad name is apple-mtp-multi-touch.

[The wiki says it's not supported](https://wiki.hyprland.org/Configuring/Keywords/#executing), so I thought I'd make an issue.

**Comment by camerondugan** [comment]
This is possible, but requires some device specific settings.
https://wiki.hyprland.org/Configuring/Variables/#per-device-input-config
Here's my issue on making this easier: #4181

**Comment by vaxerski** [comment]
where does it say it's not supported?

force_no_accel? It's an old thing that should honestly be removed altogether.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/4be8147b-be39-4030-a714-3d9a6c97cfd5)

Just set a flat profile

**Comment by vaxerski** [comment]
but yeah #4181 seems to talk about the same thing

**Comment by Ahwxorg** [comment]
> where does it say it's not supported?

![image](https://github.com/hyprwm/Hyprland/assets/87855602/9eec6532-f853-41f2-a71f-ea96162120a6)

I'll set a flat profile, thanks!
