### ISSUE TITLE
Blur layer for waybar still visible after hiding waybar

### ISSUE THREAD

**Issue by Timbaloo** [hyprwm/Hyprland#4194]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1

### Bug or Regression?

Bug

### Description

When you add a blur layer to waybar (layerrule = blur, waybar), the blur layer (assumption on my side...) is still visible after hiding waybar (killall -SIGUSR1 waybar).

![20231219_19h02m28s_grim](https://github.com/hyprwm/Hyprland/assets/154364105/27fe5243-586f-4dd7-ad59-3d1d1c60bf1d)
![20231219_19h02m35s_grim](https://github.com/hyprwm/Hyprland/assets/154364105/70b19fa7-6a5e-41e5-b110-dd7e31a276cc)

### How to reproduce

- Add a blur layer to the waybar/bar layer
- hide Waybar via (killall -SIGUSR1 waybar)

**Comment by MikeWalrus** [comment]
I think it's because waybar just becomes transparent when hiding. This can be fixed by adding a layer rule:
```
layerrule = ignorezero, waybar
```

**Comment by Timbaloo** [comment]
Well, that works :)

I did not think about it just becoming transparent, since the freed space will be used by Hyprland, if that makes sense.

So I guess it's not a bug, but still a bit weird behaviour (at least for me). I'll close.

**Comment by MikeWalrus** [comment]
Other windows take the space because waybar sets the exclusive zone to 0. :)

**Comment by Timbaloo** [comment]
Thanks for the clarification :)

Makes perfekt sense now 👍
