### ISSUE TITLE
xdg-desktop-portal-hyprland service - core dump error on hyprland 0.33.1-2

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#4195]
### Hyprland Version

0.33.1-2

### Bug or Regression?

Regression

### Description

I install it like this. 
```
sudo pacman -S hyprland xdg-desktop-portal-hyprland    
```
Reboot and login. But the portal service doesn't seem to start correctly:

![screenshot_2023-12-19_20-33-46_042073102](https://github.com/hyprwm/Hyprland/assets/3357792/42576f70-2de8-4c86-bcb3-763495fec903)

**Comment by vaxerski** [comment]
please launch xdph with `-v` and provide a log.

**Comment by Zeioth** [comment]
Forgive my ignorance, but how can I run xdph? I don't see it in [the docs](https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Hyprland-desktop-portal/)

**Comment by vaxerski** [comment]
open your [mind](https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/#usage)

**Comment by Zeioth** [comment]
Sorry for the derpyness. [Here](https://pastebin.com/raw/PazD09ca) is the output of running:

```
killall -e xdg-desktop-portal-hyprland
/usr/lib/xdg-desktop-portal-hyprland -v
```

**Comment by vaxerski** [comment]
it seems like an issue with your system.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/4bc040cf-e825-466e-9234-e22e0df0a389)

you have a directory in $PATH that your user has no permissions to access.

**Comment by vaxerski** [comment]
besides this being not really an xdph issue, wrong tracker. this is hyprland, not xdph.
