### ISSUE TITLE
Cursor stays hidden or hides unnecessary

### ISSUE THREAD

**Issue by dranull** [hyprwm/Hyprland#4197]
### Hyprland Version

d9b74ff96b3e3f0341a386451b9a3375b6f05503

### Bug or Regression?

Regression

### Description

Since 0c74df4f9efa0efe6ff1e73c74999acc217f68bb I noticed two issues with cursor hiding.

1. With `cursor_inactive_timeout = 2` opening a video from qBittorrent hides the cursor immediately and even if I move the cursor to another window, or close the video player the cursor stays hidden.

2. With `cursor_inactive_timeout = 0` if I move the cursor to window that will hide the cursor, for example mpv, and I move the cursor to another window while it's visible, it will be hidden over the second window.

### How to reproduce

(all floating windows)

1) `cursor_inactive_timeout = 2`
Open a video from a torrent in qBittorrent
The video will open (mpv) under the cursor, which will immediately be hidden
Move cursor back to qBtitorent, you'll see that the window gets the focus, but cursor stays hidden
Moving the cursor over waybar will make it reappear

3) `cursor_inactive_timeout = 0`
Open mpv on the left, a second window on the right (I used alacritty)
Move cursor over mpv, and move it to the other window before it disappears
Wait a sec and the cursor will disappear on top of the second window
(sometimes it works, sometimes it doesn't, so try a few times moving it from one window to anoter)

**Comment by SherLock707** [comment]
For me inside mpv, once cursor is hidden due to inactivity, it stays hidden (in full screen/floating/tiled ) even after moving cursor, I have to move it outside mvp to make it visible again.

**Comment by vaxerski** [comment]
check with above

**Comment by andresilva** [comment]
d1b8a63a8ef1d7258d49854d2256fa9b99fd99bc obviously breaks `cursor_inactive_timeout`.

**Comment by vaxerski** [comment]
ok, but does it fix this issue?

**Comment by vaxerski** [comment]
@andresilva check on latest, should work

**Comment by andresilva** [comment]
Now the cursor is never hidden at all.

**Comment by dranull** [comment]
No change for me, both issues still persist.

@andresilva Unfortunately, the never hiding issue is not new. You have to move around your cursor, to a window which changes the cursor, then back, and at some point it will start working again.
(Just like hidden cursor in games, not respecting the timeout (sometimes it takes much longer than the setting), the cursor repeatedly appears/hides in some applications without touching the mouse (while watching a video for example).)

**Comment by andresilva** [comment]
No, it's a different issue, with a197fe3c11d5ac095bf8e2f491edf28bde9f9b49 the cursor literally never hides. And d1b8a63a8ef1d7258d49854d2256fa9b99fd99bc just regresses to the state it was before 0c74df4f9efa0efe6ff1e73c74999acc217f68bb, i.e. when you move focus with keyboard the cursor reappears.

**Comment by vaxerski** [comment]
done some testing, above seems to work for me

**Comment by andresilva** [comment]
Fixed for me on https://github.com/hyprwm/Hyprland/commit/48ecb13b14d99241725a65582edf42cd51843e94, including the original issue described in OP (although I only tested with `cursor_inactive_timeout = 2`).

**Comment by dranull** [comment]
Actually I just tested with default settings, so `cursor_inactive_timeout = 0` and it has both issues.

I forgot to tell that I'm on nVidia and I have `WLR_NO_HARDWARE_CURSORS = 1`.

https://github.com/hyprwm/Hyprland/assets/150595692/18670d1f-acb0-44be-a706-369ef54bc903

**Comment by dtop129** [comment]
I fixed it by removing the check of `m_bWindowRequestedCursorHide` in `CHyprRenderer::shouldRenderCursor()`, and because the variable didn't have any other uses, I just removed it entirely.

I'm 90% sure that this breaks cursor hiding in other ways, but from my testing(which is just seeing if mpv with `cursor-autohide=always` actually hides the cursor and whether `cursor_inactive_timeout` works) I haven't experienced any of that.

If it changes anything, I'm also on NVIDIA with `WLR_NO_HARDWARE_CURSORS = 1`
```diff
diff --git a/src/managers/input/InputManager.cpp b/src/managers/input/InputManager.cpp
index db06de55..a3a649fe 100644
--- a/src/managers/input/InputManager.cpp
+++ b/src/managers/input/InputManager.cpp
@@ -483,11 +483,6 @@ void CInputManager::onMouseButton(wlr_pointer_button_event* e) {
 }
 
 void CInputManager::processMouseRequest(wlr_seat_pointer_request_set_cursor_event* e) {
-    if (!e->surface)
-        g_pHyprRenderer->m_bWindowRequestedCursorHide = true;
-    else
-        g_pHyprRenderer->m_bWindowRequestedCursorHide = false;
-
     if (!cursorImageUnlocked())
         return;
 
diff --git a/src/render/Renderer.cpp b/src/render/Renderer.cpp
index 3afbd551..c0a43056 100644
--- a/src/render/Renderer.cpp
+++ b/src/render/Renderer.cpp
@@ -2097,7 +2097,7 @@ void CHyprRenderer::setCursorHidden(bool hide) {
 }
 
 bool CHyprRenderer::shouldRenderCursor() {
-    return !m_bCursorHidden && !m_bWindowRequestedCursorHide && m_bCursorHasSurface;
+    return !m_bCursorHidden && m_bCursorHasSurface;
 }
 
 std::tuple<float, float, float> CHyprRenderer::getRenderTimes(CMonitor* pMonitor) {
diff --git a/src/render/Renderer.hpp b/src/render/Renderer.hpp
index 32815344..6f0d3c51 100644
--- a/src/render/Renderer.hpp
+++ b/src/render/Renderer.hpp
@@ -75,7 +75,6 @@ class CHyprRenderer {
     bool      beginRender(CMonitor* pMonitor, CRegion& damage, eRenderMode mode = RENDER_MODE_NORMAL, wlr_buffer* buffer = nullptr, CFramebuffer* fb = nullptr);
     void      endRender();
 
-    bool      m_bWindowRequestedCursorHide = false;
     bool      m_bBlockSurfaceFeedback      = false;
     bool      m_bRenderingSnapshot         = false;
     CWindow*  m_pLastScanout               = nullptr;
```

**Comment by shadowelite-sec** [comment]
> Fixed for me on [48ecb13](https://github.com/hyprwm/Hyprland/commit/48ecb13b14d99241725a65582edf42cd51843e94) ~, including the original issue described in OP (although I only tested with `cursor_inactive_timeout = 2`).~ (the original issue in OP still persists).

am also facing the exact same issue any updates ?

**Comment by shadowelite-sec** [comment]
> No, it's a different issue, with [a197fe3](https://github.com/hyprwm/Hyprland/commit/a197fe3c11d5ac095bf8e2f491edf28bde9f9b49) the cursor literally never hides. And [d1b8a63](https://github.com/hyprwm/Hyprland/commit/d1b8a63a8ef1d7258d49854d2256fa9b99fd99bc) just regresses to the state it was before [0c74df4](https://github.com/hyprwm/Hyprland/commit/0c74df4f9efa0efe6ff1e73c74999acc217f68bb), i.e. when you move focus with keyboard the cursor reappears.

i am also facing the exact same issue , any updates ?

**Comment by shadowelite-sec** [comment]
> For me inside mpv, once cursor is hidden due to inactivity, it stays hidden (in full screen/floating/tiled ) even after moving cursor, I have to move it outside mvp to make it visible again.

i am also facing the exact same issue , any updates ?

**Comment by vaxerski** [comment]
committed the patch, thanks dtop129!

**Comment by vaxerski** [comment]
lmk if it's fixed.

**Comment by dranull** [comment]
Seems to be fine now.
