### ISSUE TITLE
If a qt programs has no wayland support, automatic make it run under xwayland

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#420]
Basically, if that qt program doesn't have wayland support, run it under xcb instead
This would make my life easier, since I don't have to go on the journey of finding each program's .desktop file(not always located in `/usr/share/applications` :sob: )

**Comment by vaxerski** [comment]
No clue how to detect that, I'll have to look into that.

Have you also tried exporting `QT_QPA_PLATFORM=wayland xcb` to your Hyprland launch script?

**Comment by g3r** [comment]
I think the problem is that hyprland is setting that variable and ```MOZ_ENABLE_WAYLAND=1``` in ```Compositor.cpp:170``` AFAIK this is the only compositor that does that, It should be up  to the users to decide using them.

**Comment by vaxerski** [comment]
ok 1ddd7ee713cb67459eba9d78f6f2061995ec1f76

**Comment by KyleUltimate** [comment]
Yep that's the cause! now polymc launches, and obs also launch with wayland!
