### ISSUE TITLE
monitor settings cause kernel panic (NVIDIA drivers)

### ISSUE THREAD

**Issue by christiannicola** [hyprwm/Hyprland#4202]
### Hyprland Version

Hyprland, built from branch main at commit d9b74ff96b3e3f0341a386451b9a3375b6f05503 dirty (renderer: staticize local functions). Date: Tue Dec 19 12:55:56 2023 Tag: v0.33.1-60-gd9b74ff9  flags: (if any) debug

### Bug or Regression?

Bug

### Description

Using the `highres` or `highrr` settings in my Hyprland configuration crash the kernel. I was able to consistently reproduce this using the latest `6.1.68-1-lts` kernel on EndeavourOS with the following `nvidia-dkms` drivers:

- 545.29.06
- 535.113.01
- 530.41.03
- 525.89.02
- 520.56.06
- 515.76 

See the logs attached for the logs and system settings.

Workaround:

- Configure the monitor in `~/.config/hypr/hyprland.conf` with `monitor=,preferred,auto,auto`
- Use `exec-once = wlr-randr --output HDMI-A-1 --mode 7680x2160@119.997002Hz --scale 2` instead

### How to reproduce

- Use a monitor with high resolution and refresh capabilities
- Use a relatively recent NVIDIA graphics card that can drive the monitor
- Install Arch
- Install Hyprland (use something like https://github.com/prasanthrangan/hyprdots that configures everything correctly)
- Reboot to verify that everything is working on stock settings
- Configure the monitor in `~/.config/hypr/hyprland.conf` with `monitor=,highres,auto,1`
- Hyprland will switch to the new monitor settings without issues (in my case to 7680x2160@120Hz)
- Reboot the system
- Kernel panic after logging into the system

### Crash reports, logs, images, videos

[nvidia_smi.log.gz](https://github.com/hyprwm/Hyprland/files/13729464/nvidia_smi.log.gz)
[kernel_panic.log.gz](https://github.com/hyprwm/Hyprland/files/13729449/kernel_panic.log.gz)
[wlr-randr.log.gz](https://github.com/hyprwm/Hyprland/files/13729458/wlr-randr.log.gz)

**Comment by vaxerski** [comment]
this is a bug in the nvidia driver

**Comment by christiannicola** [comment]
I posted this on the NVIDIA forums, let's see if they pick it up.

https://forums.developer.nvidia.com/t/monitor-settings-cause-kernel-panic-nvidia-drivers/276819
