### ISSUE TITLE
Random crashes + flickering even I updated to latest Hyprland version

### ISSUE THREAD

**Issue by T3l3sc0p3** [hyprwm/Hyprland#4204]
### Hyprland Version

Hyprland, built from branch main at commit 395ab3ba370f5e12fcba594232c338c16deef0ed dirty (xdg: use better min/max size checks for floating resizes). Tag: v0.33.1-43-g395ab3ba

### Bug or Regression?

Bug

### Description

Hmm, this bug happened about 3-4 months ago and it annoyed me a lot even when I updated Hyprland or Arch Linux
As you can see in the video, the screen suddenly flickers randomly for about 8-9 seconds and it automatically restarts after that

### How to reproduce

I don't really know how to reproduce this because it almost random. But I noticed it crashes more frequently when I run some apps like VSCode, VMware

### Crash reports, logs, images, videos
This is the recent crash report that I found in `~/.cache/hyprland`. However, this file was created on 12/9/2023 while I still have problem on 12/21/2023:
[hyprlandCrashReport980.txt](https://github.com/hyprwm/Hyprland/files/13730538/hyprlandCrashReport980.txt)

The video:
https://github.com/hyprwm/Hyprland/assets/96990857/76f852f0-1d9b-4c93-b7af-96d01e19a8b4

**Comment by vaxerski** [comment]
something is terribly wrong with your system

**Comment by T3l3sc0p3** [comment]
@vaxerski Is there any way to fix that?

**Comment by vaxerski** [comment]
no clue, call an exorcist or use a more user-friendly distro that maybe comes with hl preinstalled, like arco / garuda / etc

**Comment by T3l3sc0p3** [comment]
I'll reinstall to check if the bug still exist or not. Thanks for your response

**Comment by T3l3sc0p3** [comment]
Hi @vaxerski, after following ["Fixing random flickering, (nuclear method)"](https://wiki.hyprland.org/Nvidia/#fixing-random-flickering-nuclear-method), I fixed this bug, thank you!
