### ISSUE TITLE
'moveintogroup' to a group on a different monitor makes windows disappear

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#4205]
### Hyprland Version

git

### Bug or Regression?

Bug

### Description

Using the moveintogroup dispatcher to send a window to a group on another monitor, makes the group disappear.

### How to reproduce

1. Set up two monitors.
2. Make a group in one monitor and a simple window on the other.
3. Use moveintogroup dispatcher to move the window from one monitor to the group on the other monitor.
4. Observe windows disappeareance.

### Crash reports, logs, images, videos

I hope you enjoy the holidays.
Cheers.

**Comment by MightyPlaza** [comment]
different workspaces aren't being properly handled in `CKeybindManager::moveWindowIntoGroup`
the window isn't moved to the new workspace

(using the `movetoworkspace` dispatcher on the "invisible" group will give you your windows back)

**Comment by MightyPlaza** [comment]
found ya https://github.com/hyprwm/Hyprland/pull/7030
@vaxerski
