### ISSUE TITLE
[Master Layout] Spawn client bellow the focused client

### ISSUE THREAD

**Issue by toniz4** [hyprwm/Hyprland#4208]
### Description

Hello!

It would be nice if it was possible to have a configuration option to spawn new clients on the bottom of the current focused client. Like the [attachbelow](https://dwm.suckless.org/patches/attachbelow/) dwm patch.

If it's of interest to implement this feature, I can try to make a PR, with some guidance because I don't know much about cpp.

Thanks!

**Comment by thejch** [comment]
Why did you open 2 issues about the same thing? https://github.com/hyprwm/Hyprland/issues/2769

**Comment by toniz4** [comment]
> Why did you open 2 issues about the same thing? #2769

Sorry, I didn't remembered that I had already opened the issue a couple of months ago.
