### ISSUE TITLE
black block on Wechat wine 

### ISSUE THREAD

**Issue by pypeetpy** [hyprwm/Hyprland#4211]
![20231221_14h49m19s_grim](https://github.com/hyprwm/hyprland-wiki/assets/59130593/d9df3938-8bfb-4c41-964d-c9f10a06f284)
![20231221_14h49m10s_grim](https://github.com/hyprwm/hyprland-wiki/assets/59130593/8308df6c-d999-496b-ab44-015639ebd654)

**Comment by kellerman** [comment]
Do you mean something like this? @pypeetpy 
This happens with wine application menu, when there are shadows. WinSCP for instance. I attached a screenshot.
![2024-02-06T21:44:47,166294778+02:00](https://github.com/hyprwm/Hyprland/assets/917901/cab8d453-6356-4b26-8294-401615141d1a)
