### ISSUE TITLE
[force_zero_scaling] Cursor too big with scaling enabled

### ISSUE THREAD

**Issue by manio** [hyprwm/Hyprland#4212]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Bug

### Description

The cursor size (`xfreerdp` window) on scaled display is bigger than it should be. On scaled (scale 2.0) it shows like this (did against notepad.exe File menu to have some constant reference):
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/c765b30f-92c3-40b8-a20b-f3626ddcf200)
When setting scale to 1.0 or moving a window to unscaled display it shows correctly like this:
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/c021d996-be66-4f81-94ca-83b0d7f95879)

Initialy I was trying to report it in freerdp but I realized that it is related to scaling.
Freerdp report (contains more screenshots when needed): https://github.com/FreeRDP/FreeRDP/issues/9687

Related to https://github.com/hyprwm/Hyprland/issues/3969 ?

### How to reproduce

Set `force_zero_scaling = true`, scale = `2.0` to specific display and try to start xfreerdp session to any Win10 host like this:
`xfreerdp +auto-reconnect +clipboard /cert:ignore /dynamic-resolution /prevent-session-lock -grab-keyboard /sound /v:XXXXX /kbd:layout:0x00000415 /scale:180`

**Comment by vaxerski** [comment]
XWayland is the one that sets the cursor.

**Comment by manio** [comment]
OK, thanks
