### ISSUE TITLE
 Mouse cursor lags under high GPU load (Intel GPU)

### ISSUE THREAD

**Issue by Nmzik** [hyprwm/Hyprland#4213]
### Hyprland Version

v0.33.1 (latest)

### Bug or Regression?

Bug

### Description

First of all, I apologize if this issue has already been discussed. It has already been discussed in numerous Wayland compositors, such as Sway, Weston, and Kwin. My integrated GPU is fairly modern (Intel UHD Graphics 630, 9th generation Intel CPU) for light 3D work.

The issue is not the performance of the rendered 3D scene but rather the cursor movement itself. I assume the 3D scene can be (and should be) rendered at, for example, 10fps, but we are talking about smooth cursor movement.

I don't use `WLR_NO_HARDWARE_CURSORS=1`, therefore, I assume it uses hardware cursors by default (correct me if I'm wrong).
Direct scanout is enabled; however, again, I assume it doesn’t get triggered when not in full screen.

**Status of the current date:**
Kwin (Kde Plasma 6 beta): Everything is smooth.
Kwin (Kde Plasma 5.27): Lags.
Hyprland (v0.33.1): Lags.
Sway (v1.8.1): Lags.
Windows 11: Everything is smooth.
All tests were conducted in “not fullscreen” mode

If you need any further information, feel free to ask.

### How to reproduce

1) Launch Chrome or Firefox (Xwayland or Wayland native) (WebGL acceleration is enabled)
2) Open [https://web.basemark.com/]. Start the benchmark
3) Starting from the test 4 of 20 mouse cursor starts to shutter/lags

**Comment by vaxerski** [comment]
pretty sure #3373
