### ISSUE TITLE
session desktop example

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4215]
After try several ways from hyprland wiki and issue ,none of them is the right solution, I still suffer two minutes long waiting waybar to show, 30s to thunar to show, but add export $(dbus-launch) into a Hyprland launcher solve the problem, that reminds me the bspwm.desktop provided by manjaro-bspwm , so I try Exec=dbus-launch --sh-syntax --exit-with-session Hyprland in hyprland.desktop in wayland-session. It worked! all back to normal.Simplely Exec=Hyprland is not enough.

**Comment by vincentaxhe** [comment]
please delete it

**Comment by vincentaxhe** [comment]
please delete it

**Comment by romanstingler** [comment]
have you installed
```
xdg-desktop-portal
xdg-desktop-portal-hyprland
```

**Comment by vincentaxhe** [comment]
> have you installed
> 
> ```
> xdg-desktop-portal
> xdg-desktop-portal-hyprland
> ```
yes ,the solution is about dbus, after I fix it, no delay ever occur. I make sure all dependencies is installed.
