### ISSUE TITLE
Rendering glitches/freeze with disable_hyprland_logo = no

### ISSUE THREAD

**Issue by dranull** [hyprwm/Hyprland#4216]
### Hyprland Version

79f3888b4bd9796850189ed3e151a6c831e6faae

### Bug or Regression?

Regression

### Description

Watch the video.

Default settings with WLR_NO_HARDWARE_CURSORS = 1

If your try to run `hyprctl reload` (or change settings) twice the PC will freeze.

### How to reproduce

Install and open Hyprland.
Open a window (Ctrl+Q).

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/150595692/3e596a76-9ee9-457b-8832-5a1d472e7bce

**Comment by vaxerski** [comment]
disable_hyprland_logo = no, yet there is no default background. Have you removed the assets...?

**Comment by dranull** [comment]
I did `make clear; make all; sudo make install; Hyprland` (with auto-generated config), same with meson-ninja.

I tried specifically to disable these settings (not changing the `disable_hyprland_logo`), but no change:
```
    disable_splash_rendering = yes
    force_hypr_chan = no
    force_default_wallpaper = 0
```

It's not nVidia, Intel iGPU has the same issue.

Also, in the video I removed `autogenerated = 1`, but if I leave it the configs, then the cursor renders normally, though opening a window still has the same artifacts.

**Comment by vaxerski** [comment]
mhm so you did disable the back layer. Okay, and hyprland forgets to clear the buffer. Makes sense. I assume if you add a hyprpaper or swaybg instance these go away

**Comment by dranull** [comment]
Yes, in my second try. The first try I didn't touch those setting.
Or you mean earlier? My main config has all those settings off, and I exited Hyprland with SIGKILL (because of #4083). Maybe something didn't clean up properly?

Anyway, if I use a wallpaper (wpaperd in my case), then no rendering issues, but I still have to use `disable_hyprland_logo = yes` (only change in default config) because if I run `hyprctl reload` twice, the PC freezes.

**Comment by dranull** [comment]
Something fixed this in the meantime...
