### ISSUE TITLE
Systemd service startup notification?

### ISSUE THREAD

**Issue by Vladimir-csp** [hyprwm/Hyprland#4217]
### Hyprland Version

0.33.1

### Bug or Regression?

Bug

### Description

Hi.
Since example systemd unit contains `Type            = notify`, I wonder if Hyprland detects being in a systemd service and sends notification itself?

And if it is, is it possible to disable or tune this behavior?

A user of my [session manager](https://github.com/Vladimir-csp/uwsm/) encountered [breakage](https://github.com/Vladimir-csp/uwsm/issues/14) of startup ordering that happens due to early startup declaration.

### How to reproduce

With https://github.com/Vladimir-csp/uwsm/ launch `wayland-session start Hyprland`. Observe service startup `Started Main service for Hyprland.` comes before `Finalizing startup of Hyprland`

### Crash reports, logs, images, videos

https://github.com/Vladimir-csp/uwsm/issues/14

**Comment by Vladimir-csp** [comment]
[Bingo](https://github.com/Vladimir-csp/uwsm/issues/14#issuecomment-1866875373)! 

It's a feature request then: Please add an option to disable systemd startup notification.

**Comment by Vladimir-csp** [comment]
Thanks!

**Comment by vaxerski** [comment]
yours truly

**Comment by Vladimir-csp** [comment]
https://github.com/Vladimir-csp/uwsm/commit/06e9be06edd455de066a9ed3176ffa8f0579b604
