### ISSUE TITLE
.hyprland folder is created as world-writable

### ISSUE THREAD

**Issue by notpeelz** [hyprwm/Hyprland#4218]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1)

### Bug or Regression?

Bug

### Description

`~/.hyprland`/`~/.cache/hyprland` is created as world-writable (`777`).
It should probably honor the umask instead. My umask is set to `077` globally on my machine, so I would've expected the dir to get created with permissions `700`.

```
$ ls -ald ~/.cache/hyprland
drwxrwxrwx 2 peelz peelz 4,096 Dec 21 15:14 /home/peelz/.cache/hyprland
```

https://github.com/hyprwm/Hyprland/blob/79f3888b4bd9796850189ed3e151a6c831e6faae/src/debug/CrashReporter.cpp#L133-L135
Why are the permissions set explicitly? Doesn't `std::filesystem::create_directory` set the appropriate permissions?

### How to reproduce

1. Run hyprland
2. `ls -ald ~/.hyprland`

**Comment by vaxerski** [comment]
we can leave them default.
