### ISSUE TITLE
instable after update

### ISSUE THREAD

**Issue by wuyoli** [hyprwm/Hyprland#4220]
### Hyprland Version

Hyprland, built from branch  at commit v0.33.1  (). Tag:  flags: (if any) debug

### Bug or Regression?

Bug

### Description

I recently (over the last 2 Days) had a lot more crashes than before (~every few hours). I suspect this is connected to a update i did around that time.

### How to reproduce

They seem to be more frequent when watching videos in qutebrowser. (qutebrowser sometimes crashes by itself , but usually hyprland dies too.)

### Crash reports, logs, images, videos

[hyprlandCrashReport129331.txt](https://github.com/hyprwm/Hyprland/files/13747101/hyprlandCrashReport129331.txt)

**Comment by vaxerski** [comment]
this looks like a crash in your display driver, nouveau.

**Comment by wuyoli** [comment]
ok, thanks i will look into that
