### ISSUE TITLE
Code completion popup does not scale properly in Jebrains IDE

### ISSUE THREAD

**Issue by moonleay** [hyprwm/Hyprland#4223]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).

### Bug or Regression?

Bug

### Description

When using a Jetbrains IDE the code compleation does not resize properly, making it hard / impossible to read. There are no (usable) logs in /tmp/hypr/. This issue appeared after upgrading from hyprland v0.30.1 to v0.33.x on an Archlinux install. Rolling back to v0.30.1 makes this issue go away.

### How to reproduce

1. Open a Jetbrains IDE (I used IntelliJ Idea in my example)
2. Write something that would make code completion pop up
3. Continue to write, narrowing the completion results
4. Watch, as the code completion window get squished until it it not readable anymore

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/74376181/6153bd79-4fb7-4c87-a41f-94d08e9bbb58

**Comment by tobiichi3227** [comment]
This problem is same as #1947 #3012 #3450.
This problem seems to be fixed in the new version without any setting window rule.

**Comment by moonleay** [comment]
> This problem is same as #1947 #3012 #3450. This problem seems to be fixed in the new version without any setting window rule.
Yes, true. I just installed -git and its fixed there, thanks for bringing that to my attention!
