### ISSUE TITLE
escaping of special characters in monitor description

### ISSUE THREAD

**Issue by notpeelz** [hyprwm/Hyprland#4224]
### Hyprland Version

d74607e414dcd16911089a6d4b6aeb661c880923

### Bug or Regression?

Bug

### Description

I have a monitor that contains a `#` in its description field.
This directive results in a parsing error:
```
monitor = desc:Acer Technologies XB270HU #ASM9tUVZnard, 2560x1440@120, 0x0, 1
```
Maybe it would be worth considering extending the config file grammar to support quoting or backslash-escaping?

Related: #2457

### How to reproduce

.

**Comment by MightyPlaza** [comment]
`##`?

**Comment by vaxerski** [comment]
yeah common case of not reading the wiki, I am wondering if it's treatable medically

**Comment by notpeelz** [comment]
> `##`?

Thanks.

> yeah common case of not reading the wiki, I am wondering if it's treatable medically

No need to be rude. I'm sure this isn't the first time the non-standard nature of the config syntax created some confusion... something like `\#` (or quoting) would be much more intuitive.

I noticed that a lot of the config parsing logic is manually implemented.
Maybe it would be a good idea to use a parser generator for the config file? This would make it a lot simpler for things like [tree-sitter-hypr](https://github.com/luckasRanarison/tree-sitter-hypr/)
Related: #2843
