### ISSUE TITLE
Wrong scaling when scaling > 1

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#4225]
### Hyprland Version

Hyprland, built from branch main at commit c416880cf96aee783b6a00f356512e5d758e6056 dirty (shadow: correctly scale boxes). Date: Fri Dec 22 10:54:31 2023 Tag: v0.32.3-200-gc416880c  flags: (if any) debug debug

### Bug or Regression?

Regression

### Description

`hyprctl monitors` shows wrong scaling when using fractional scaling
Furthermore, the cursor cannot reach the right and bottom edges of the screen
`git bisect` says https://github.com/hyprwm/Hyprland/commit/37d2840246af43a7141e2a036820fc3dec468f01

### How to reproduce

1. Set scaling to 1.15
2. Somehow on my monitor `hyprctl monitors` shows scaling as 1.11 instead
3. Try moving cursor to the right or bottom edge of screen. The cursor is blocked by an invisible wall and can't reach the edge

**Comment by vaxerski** [comment]
expected

**Comment by vaxerski** [comment]
oh wait point 3 is an issue

**Comment by vaxerski** [comment]
check with above

**Comment by thejch** [comment]
So point 3 issue is fixed, but there's some new problems. I can't move the cursor between my two monitors anymore with my current config. Also my two monitors are not aligned anymore.

**Comment by vaxerski** [comment]
hm, yeah, thats a problem. Maybe instead of automatically correcting the scale we should pop an error?

The thing is you're creating a very un-nice scale. Your logical size is fractional, and nothing likes that. Hyprland corrects that to the nearest, valid one

**Comment by thejch** [comment]
I would like to have the previous behavior. I use a calculated scale so that my two monitors can be perfectly aligned.
For context this is my config
```
monitor=HDMI-A-1,preferred,0x0,1.75 # 4k monitor
monitor=DP-2,preferred,2194x0,1.1669 # 1440p monitor. Calculation: 3840 / 1.75 = 2194; 1440 / (2160 / 1.75) = 1.1669
```
Is there some way to make it work like before instead of showing an error or autocorrecting it?

**Comment by vaxerski** [comment]
well if your scale would be perfectly aligned to produce integer logical sizes then no problems should arise

**Comment by thejch** [comment]
```
2560 / 1.1669 = 2193.85
1440 / 1.1669 = 1234.04
```
If we round it then the logical size should be 2194 * 1234
And it should be aligned with the 4k because 
```
3840 / 1.75 = 2194.28
2160 / 1.75 = 1234.29
```
which rounds to 2194 * 1234 as well

**Comment by vaxerski** [comment]
and this rounding causes issues. Logical sizes should divide cleanly into ints.

**Comment by vaxerski** [comment]
because #3511 #2618 and many more

**Comment by thejch** [comment]
Can we just round the logical size to an integer and store it as an integer then? Not sure what it was stored as before

**Comment by vaxerski** [comment]
> Can we just round the logical size to an integer and store it as an integer then? Not sure what it was stored as before

that's what we do. The problem is all the other apps physically cannot render correctly.

**Comment by vaxerski** [comment]
I'll add an option to override this, but it really should not be set.

**Comment by thejch** [comment]
I don't really mind what happens under the hood, but I would very much like it to:
1. let me have something other than 1.25, 1.5 etc
2. let me align the two monitors

Right now it doesn't even let me have 1.75 though

**Comment by vaxerski** [comment]
it's because you cannot have 1.75 on 4K as 3840 / 1.75 is not an integer.

**Comment by thejch** [comment]
> align in what way? as in, same logical size?

I simply want the logical size to be 2194, but there seems to be no way I can make it that. I tried 1.7502278942570648 and that didn't work either. It's fractional but I can only put a floating point number

**Comment by vaxerski** [comment]
uhhh yeeaa there is also the fractional scale protocol which demands scales are (int / 360)

**Comment by thejch** [comment]
So I tried 1.92 on 4k and that still didn't work. And it autocorrected it back to 1.00. But it should be an integer because
```
3840 / 1.92 = 2000
2160 / 1.92 = 1125
```
Is it cuz the fractional scale protocal or why is this

**Comment by thejch** [comment]
But tbh, I can live with that config option and just use that in the future. I just feel like there should still be a better way to handle this cause it was working so perfectly before except that 1 pixel weird behavior sometimes

**Comment by murleo** [comment]
I also observe an issue with >1 scaling after update, which didn't exist before.

My config is:
```
monitor = DP-1,2560x1440@165,0x0,1.33
```
The apps that like VS Code, Telegram were scaling nicely, and the rendered image was sharp.

After update, I get an error message with the same config saying that 1.33 is bad and the nearest valid scale value can be 1.333333.

I updated the config to use 1.333333. However, now the apps like VS Code and Telegram are blurry.

The mitigation is to use
```
debug {
  disable_scale_checks = 1
}
```
 and old 1.33 scale value.

With both 1.33 and 1.333333 `hyprctl monitors` returns the same output:

```
Monitor DP-1 (ID 0):
	2560x1440@165.08000 at 0x0
	description: Dell Inc. DELL S2721DGF D6ZSR83 (DP-1)
	make: Dell Inc.
	model: DELL S2721DGF
	serial: D6ZSR83
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 42 0 0
	scale: 1.33
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

**Comment by vaxerski** [comment]
odd that 1.33 is sharp but 1.333333 is not. 1.33 creates 1924.8x1082.7, fwiw.

**Comment by murleo** [comment]
See the screenshots:

1.33
![1 33_231227_20h33m23s_screenshot](https://github.com/hyprwm/Hyprland/assets/12598936/0903c56f-04e8-4e08-8bae-81c45cfef7ac)

1.333333
![1 333333_231227_20h33m57s_screenshot](https://github.com/hyprwm/Hyprland/assets/12598936/8bf941d1-3792-45fa-96e5-cade9e040a3d)

**Comment by vaxerski** [comment]
is it a thing for _all_ wayland apps or just select ones?

**Comment by murleo** [comment]
Firefox and kitty seem to work fine with both scale values. So, only the selected apps.

**Comment by vaxerski** [comment]
ah, fractional scaling protocol usage most likely then.

**Comment by vaxerski** [comment]
I nailed down the issue, but it's midnight. I hope I wont forget to fix it tomorrow.

**Comment by vaxerski** [comment]
can you add a `nearestneighbor` windowrule to your affected apps and tell me how it looks?

**Comment by murleo** [comment]
Using `nearestneighbor` windowrule VS Code looks veery sharp :open_mouth: with both 1.33 and 1.333333. I believe even better than before with 1.33. Thanks! Also, some interesting screen tearing-like effect start to happen during animation between float/tiling mode. Probably, it cannot decide where to put that extra 1 pixel you mentioned. On the other hand, that's a minor nuance.

**Comment by vaxerski** [comment]
Can you record it?

**Comment by murleo** [comment]
1.333333 with nearestneighbor (look at the `return 0;` statement):
https://github.com/hyprwm/Hyprland/assets/12598936/ef1a2d66-793a-4e72-831c-6c1edd9423ab

1.333333 without nearestneighbor:
https://github.com/hyprwm/Hyprland/assets/12598936/fa6a0f15-3ce0-4026-8b4f-07f700d7aa19

**Comment by vaxerski** [comment]
yeah, I think we should just use nearestneighbor on fractional-scale surfaces. At least when still. Maybe in motion we could temporairly revert to bilinear. I'll see tomorrow. Thanks

**Comment by murleo** [comment]
BTW, I have set `nearestneighbor` for 3 apps so far to fix the blurriness with 1.333333 scale. It turns out that all of them are using [Electron](https://github.com/electron/electron). Probably, filtering Electron apps may be useful.

**Comment by vaxerski** [comment]
yeah sorry I'll try to get this sorted soon, xmas, new year, hyprlang, too many things going on at once and I have to work on my laptop as I am back home for the winter break, away from my desktop.

**Comment by vaxerski** [comment]
check with above

**Comment by lawmx** [comment]
I want to add that on my pc (monitor resolution of 2560x1600 and scale set to 1.5) it correctly warned that it's not a clean divisor, but instead of setting the scale to the recommended value of 1.6, I set it to auto. Weirdly enough, with the value set to auto it still tries to set a scale of 1.5, which I thought was odd.
No issues if I set the scale explicitly to 1.6 or 1.33.

**Comment by vaxerski** [comment]
oh oopsie daisy

**Comment by vaxerski** [comment]
check with above

**Comment by lawmx** [comment]
The above commit fixed the issue, thanks!

**Comment by q234rty** [comment]
It seems that b5b025a1ed6cfa2b94ad0eff38a247223edd95bb has forced extra/telegram-desktop into nearest neighbor for some reason...

**Comment by vaxerski** [comment]
uhh it will if fractional scaling + using fs protocol + buffer misaligned + not animated. Does it look wrong, or what?

**Comment by q234rty** [comment]
It looks very wrong, I guess it's using the fractional scale protocol but sends a scale of 2, not sure

**Comment by vaxerski** [comment]
screenshot?

with the fractional-scale protocol you're not allowed to use a scale of 2 per protocol.

**Comment by q234rty** [comment]
![extra/telegram-desktop](https://github.com/hyprwm/Hyprland/assets/11485439/9d241cbd-2c51-4e73-8ae6-6e1d11931442)
I _think_ this is the result of downscaling via nearest neighbor.

**Comment by vaxerski** [comment]
looks rough indeed.

**Comment by thejch** [comment]
@vaxerski would it be better to put `debug:disable_scale_checks` under something like misc? the debug category makes it sound like it's a hack that you're not supposed to use and only for developers (which perhaps you think it is, but i think it's a valid config option, at least for me). This may prevent confusion in the future

**Comment by thejch** [comment]
@vaxerski debug:disable_scale_checks was not added to the wiki btw

**Comment by vaxerski** [comment]
woops

**Comment by vaxerski** [comment]
fixed

**Comment by vaxerski** [comment]
> @vaxerski would it be better to put debug:disable_scale_checks under something like misc? the debug category makes it sound like it's a hack that you're not supposed to use and only for developers (which perhaps you think it is, but i think it's a valid config option, at least for me). This may prevent confusion in the future

nononono it's there for a reason. It should not be used by users. Really.

**Comment by thejch** [comment]
> nononono it's there for a reason. It should not be used by users. Really.

what exact issue does it cause? i've been using it for a week and it's working very smoothly, 0 bugs

**Comment by vaxerski** [comment]
just because you don't see any doesn't mean they aren't there.
I won't be searching for exact ticket numbers but:
 - pixel gaps between windows
 - blurry surfaces using fractional-scale protocol
 - pixel gaps on wallpaper apps
just to name three
