### ISSUE TITLE
hyprland doesn't clean up its Wayland sockets after exit

### ISSUE THREAD

**Issue by appsforartists** [hyprwm/Hyprland#4226]
### Hyprland Version

0.32.3

### Bug or Regression?

Bug

### Description

Hyprland sets `WAYLAND_DISPLAY` when it starts up, but doesn't release it when quit.  This prevents other sessions (like `gamescope`) from starting correctly.

On my system, exiting Hyprland leaves me in a loop of this printing to the console:

```
DEBUG Using pkexec loader
DEBUG Found wayland session
```

until I hold the power button down long enough for the firmware to kill the OS.

### How to reproduce

1. `systemctl --user show-environment` before starting Hyprland.  Observe that `WAYLAND_DISPLAY` is unset.
2. Start a Hyprland session.
3. `hyprctl dispatch exit`
4. `systemctl --user show-environment`  Observe that `WAYLAND_DISPLAY` is _still_ set to `wayland-1`.
5. Observe that `/run/user/1000/wayland-1` still exists (when it should have been cleaned up during exit).

**Comment by vaxerski** [comment]
maybe hyprland crashed? is there a crash report?

**Comment by appsforartists** [comment]
This happens consistently for me when I try to exit Hyprland, so I don't think it's a crash. 

Where would I find a crash report?

**Comment by vaxerski** [comment]
`$XDG_CACHE_HOME/hyprland` or `~/.hyprland`

**Comment by appsforartists** [comment]
`No such file or directory` for both.

**Comment by vaxerski** [comment]
dam

**Comment by thomascft** [comment]
I'm having the same issue.

**Comment by wvffle** [comment]
I can confirm the issue. When `hyprctl dispatch exit` is run, `systemctl --user show-environment` still shows `WAYLAND_DISPLAY=wayland-1` and there is no crash log.

**Comment by thomascft** [comment]
Sounds like the issue may be with wlroots itself. Someone reported the same issue with sway here: https://github.com/Jovian-Experiments/Jovian-NixOS/issues/267

**Comment by appsforartists** [comment]
cc @emersion

**Comment by emersion** [comment]
wlroots is not involved in the system environment stuff.

**Comment by vaxerski** [comment]
yeah sorry simon idk why they pinged you

**Comment by izmyname** [comment]
> I can confirm the issue. When `hyprctl dispatch exit` is run, `systemctl --user show-environment` still shows `WAYLAND_DISPLAY=wayland-1` and there is no crash log.

Aquamarine doesn't clean up WAYLAND_DISPLAY, either

**Comment by ShizukanaOtaku** [comment]
Close?

**Comment by vaxerski** [comment]
ah yeah I think this was solved a while ago
