### ISSUE TITLE
Exec with workspace window rule broke

### ISSUE THREAD

**Issue by phonetic112** [hyprwm/Hyprland#4227]
### Hyprland Version

Hyprland, built from branch main at commit 6c8e0f9863d86755d7931a9d6ad920b2049cf6a6 dirty (config: add debug:disable_scale_checks). Date: Fri Dec 22 18:21:02 2023 Tag: v0.33.1-77-g6c8e0f98  flags: (if any) debug

### Bug or Regression?

Regression

### Description

Exec with workspace window rule not working after 4eb42fa.

### How to reproduce

1. run `hyprctl dispatch exec [workspace 4 silent] thunderbird`
2. thunderbird starts in active workspace, rather than workspace 4

**Comment by random2907** [comment]
https://github.com/hyprwm/Hyprland/assets/81547183/58430c10-40e3-4071-9cdd-ca368e650311

cant reproduce .

**Comment by random2907** [comment]
Hyprland, built from branch main at commit 6c8e0f9863d86755d7931a9d6ad920b2049cf6a6 dirty (config: add debug:disable_scale_checks).
Date: Sat Dec 23 04:51:02 2023
Tag: v0.33.1-77-g6c8e0f98

flags: (if any)
debug

yes its reproducible .

**Comment by bvr-yr** [comment]
yep, it exists since 4eb42fab7bb1b1d6c8fec4682c8c1de6dca7049b
actually, now u need one extra rule, e.g.
`hyprctl dispatch exec [tile; workspace 4 silent] thunderbird` to run

the same thing is about `windowrulev2`, u can't use single `workspace:1` match, need to add another match
