### ISSUE TITLE
only login twice can enter hyprland with sddm

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4228]
### Hyprland Version

Hyprland, built from branch main at commit bd952dcef2ead3b0b7e2d730930a3fc528813ee0 dirty (systemd: add HYPRLAND_NO_SD_NOTIFY). Date: Fri Dec 22 05:27:12 2023 Tag: v0.33.1-71-gbd952dce

### Bug or Regression?

Bug

### Description

I try garuda hyprland linux and config based on it , even Garuda did not fix it .need to type twice password to login in every time. now I use hyprland with xfce and bspwm session in manjaro, it still take twice to login in hyprland, it could be tricky .

### How to reproduce

garuda reproduce the issue in his offical hyprland version

**Comment by vaxerski** [comment]
crash report? log?

**Comment by 257m** [comment]
Does this happen with only hyprland when logging in from sddm or other WM/DEs as well?

**Comment by vincentaxhe** [comment]
sorry for the bother, I didnot create sddm.conf in /etc, after I copy sddm.conf from garuda ,and set proper autologin like this.
[Autologin]
Relogin=true
Session=hyprland.desktop
User=vincent
I can login in directly, garuda didnot correct sddm.conf,before like this
[Autologin]
Relogin=false
Session=plasma
User=vincent
which lead to repeatly login attempt.
I follow archwiki ,create file in /etc/sddm.conf.d,it's unnecessary. sddm.conf in /etc can do the work.
