### ISSUE TITLE
Visual glitch when discord is minimized in tray and attempting to switch worspaces 

### ISSUE THREAD

**Issue by Amrit-codes** [hyprwm/Hyprland#4229]
### Hyprland Version

b9c1414f25bfe6972d1996b79566f63c215ec78a

### Bug or Regression?

Bug

### Description

https://github.com/hyprwm/Hyprland/assets/128936479/1e5949fb-50ee-4ed6-ade2-66f941a447d9

Abrupt loading of a window when switching workspaces

### How to reproduce

~Minimize discord to tray in waybar. 
Open multiple windows in two adjacent workspace
Maximize one window in each workspace
Attempting to switch between workspace results in this glitch~

Open multiple windows in two adjacent workspace
Maximize one window in each workspace
Attempting to switch between workspace results in this glitch

**Comment by vaxerski** [comment]
isnt this #3437 or some shit

**Comment by Amrit-codes** [comment]
> isnt this #3437 or some shit

`workspace_swipe_numbered`  is not set to true in my configs

**Comment by Amrit-codes** [comment]
Small correction
This doesn't happen due to discord being in tray, but when you switch between two workspace where each one has a window maximized.
Not when one workspace has a window maximize and the other doesn't but when both of them have a window maximized.

**Comment by vaxerski** [comment]
ah, then #4076
