### ISSUE TITLE
Crash, segmentation fault

### ISSUE THREAD

**Issue by Saltyc0der** [hyprwm/Hyprland#4233]
### Hyprland Version

Hyprland, built from branch main at commit af6aae4e12b96fff701d8ae8fcb48ea8bb51009f dirty (renderer: don't use clipBox for pinned window occlusion during animations). Tag: v0.33.1-16-gaf6aae4e

### Bug or Regression?

Bug

### Description

It crashed when I tried to open sshfs mounted directory in vscode from terminal. coudnt reproduce after that idk

### How to reproduce

idk

### Crash reports, logs, images, videos

[hyprlandCrashReport596824.txt](https://github.com/hyprwm/Hyprland/files/13760257/hyprlandCrashReport596824.txt)

**Comment by vaxerski** [comment]
if it's not reproducible it could be anything, so closing. If you can repro, feel free to reopen
