### ISSUE TITLE
Cyclenext dispatcher doesn't work consistently on master layout.

### ISSUE THREAD

**Issue by tienbuigia** [hyprwm/Hyprland#4236]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Regression

### Description

I tried to write an issue on this problem quite long ago, but I did not describe it clear enough, so here it is.

The layoutmsg:cyclenext doesn't work with float windows, I know this is intended, so I'll just have to use the cyclenext dispatcher, right? But this dispatcher has some weird interacts (or at least with master layout).

1. Cyclenext works opposite of layoutmsg:cyclenext (next = prev & prev = next), so I have to set the keybinds the opposite way, this is fine with me.
2. When I open a float window(A), open another window then set the float to tiled, the order of windows got messed up. To fix this I have to toggle float on window(A) again.

### How to reproduce

1. Install Hyprland on artixlinux (basically Arch linux)
2. Set general:layout = master; master:new_is_master = false; master:new_on_top = true
3. Set keybinds for cyclenext dispatcher (not the layoutmsg ones)

### Crash reports, logs, images, videos

[video](https://0x0.st/Hg6S.mkv)

**Comment by vaxerski** [comment]
this is intended, though? If you want this, why not make a script to toggle tiled/floating focus, and use `cyclenext` on floating and `layoutmsg:cyclenext` on tiled?

**Comment by tienbuigia** [comment]
Doesn't it make more sense when you toggle a float window back to tiled, it should position itself in right order? Or if it be in the top of slaves, it should has this order accordingly?

**Comment by vaxerski** [comment]
cyclenext is strictly by the ordering of which was opened more recently

**Comment by tienbuigia** [comment]
I see, it makes sense.

> this is intended, though? If you want this, why not make a script to toggle tiled/floating focus, and use `cyclenext` on floating and `layoutmsg:cyclenext` on tiled?

Can you show me an example, many thanks for your works though

**Comment by vaxerski** [comment]
uhh my bash is a bit shady, but wouldnt this work?
```bash
hyprctl activewindow | grep "floating: 0" && hyprctl dispatch layoutmsg cyclenext || hyprctl dispatch cyclenext
```
though cyclenext will cycle all (not just floating) maybe I can add an option for that.

Although worth noting you can already focus floating windows with movefocus

**Comment by vaxerski** [comment]
alright I made a commit to allow that, so now it will become
```bash
hyprctl activewindow | grep "floating: 0" && hyprctl dispatch layoutmsg cyclenext || hyprctl dispatch cyclenext floating
```
and it should work.

**Comment by tienbuigia** [comment]
It's gonna separate tiled and floating windows and I'll need to bind another key to switch focus back and forth between them. This will work for me.

I still think that the easiest way to do this is to make the layoutmsg:cyclenext works on both tiled and float windows.

**Comment by vaxerski** [comment]
because master doesn't govern floating windows, + it wouldnt make much sense to me

**Comment by tienbuigia** [comment]
Ok, I think this is it.

**Comment by akdevservices** [comment]
I think this is only one issue from a bunch of related issues with focusing windows in master layout, for instance, see #3449.

**Comment by tienbuigia** [comment]
@akdevservices I think it is because @vaxerski doesn't use master-stack layout, so it doesn't make sense to him. I tried hyprland lately to see how it goes, but the reason I stopped using it is still the same as before, the master layout does not work. So I've comeback to my comfy dwm and wait longer to checkout wayland again.
