### ISSUE TITLE
Monitor related settings not working

### ISSUE THREAD

**Issue by kuldeepaher01** [hyprwm/Hyprland#4242]
### Hyprland Version

v0.31.0

### Bug or Regression?

Bug

### Description

Even if i change the resolution in my hyprland.conf 
neither the scaling nor resolution or for dual monitor the position is changing. 

### How to reproduce

![17034990705617692748227387368540](https://github.com/hyprwm/Hyprland/assets/76651819/81447772-1e8c-4092-9c4f-7b2a6b0b68a3)
![17034990944191121724838886911630](https://github.com/hyprwm/Hyprland/assets/76651819/b5efa9da-f784-41a7-85c6-6d95622f7742)

**Comment by vaxerski** [comment]
ignoring your wildly out of date version, the mode might be getting rejected. Check if it's listed in wlr-randr

**Comment by kuldeepaher01** [comment]
@vaxerski how do i update it to latest version and will that break anything?

**Comment by vaxerski** [comment]
do I sit in your computer? No. Use whatever package manager you use to update. If your repos are outdated, thats on you for using them.

**Comment by kuldeepaher01** [comment]
Oh you don't sit on my computer. If u didn't want to answer there's no compulsion to reply. I mentioned I am new to this thing, instead of barking i DoNt sIt oN ur.... U could have said u can use PKG manager or Google
