### ISSUE TITLE
swallow wrong window

### ISSUE THREAD

**Issue by tienbuigia** [hyprwm/Hyprland#4245]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Bug

### Description

The swallow option sometimes swallow wrong windows or doesn't swallow at all. The reason seems to be that hyprland swallows the current focus window, but sometimes the application starts slower and user have moved focus to another window already. Slow cmd: `mpv "youtube url"`

### How to reproduce

1. enable swallow. set misc:enable_swallow = true; misc:swallow_regex = terminal-regex
2. run a slow cmd in terminal like this one `mpv "youtube url"`, before mpv spawn, move focus to another window

**Comment by vaxerski** [comment]
what's your terminal? swallowing works by tracking PIDs. If your terminal works on a "single process" principle, it has to guess, and it guesses based on focus.

Foot does this by default, opt-out. Kitty does this with `--single-instance` iirc.

**Comment by tienbuigia** [comment]
I use foot. I start foot --server with Hyprland (exec-once) then binds Super+Return to run footclient

my swallow_regex is ^footclient$

After changed swallow_regex to ^(kitty|footclient)$ to test out kitty as well then kitty does not get swallow, with or without `--single-instance`.

And can I ask what is iirc?

**Comment by tienbuigia** [comment]
I figure the kitty not being swallow issue, it because the environment has to have TERMINAL=kitty for it to work. And yeah, kitty doesn't swallow wrong window. Why I need to set TERMINAL var? since I have regex.

**Comment by vaxerski** [comment]
no clue what you talking about but `foot --server` is your issue. if you want swallowing to work properly, you cannot use that. Just use `foot`.
