### ISSUE TITLE
Windows are unstable; frequently losing focus and flickering.

### ISSUE THREAD

**Issue by reteov** [hyprwm/Hyprland#4246]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Regression

### Description

Hyprland (any version after 0.30) is causing all windows to "re-draw," meaning that, on a regular rhythm (approximately 2 seconds), the window will cycle its focus, and, in the case of the "Master" layout, reset its size and position; this has the effect of the animation causing the window to flicker and (sometimes) swapping with the master window.  One thing of note is that this only happens in the monitor the mouse is residing in; the windows in non-active monitors will not show this behavior.

I have found a workaround that can stabilize the desktop: I launch a non-Hyprland compositor first (in my case, sway), then close it down and launch Hyprland.  After doing this, the issue no longer occurs (until the next reboot).

### How to reproduce

First, cold-start the system, making sure everything is off.  Then, start up the system and sign into Hyprland (or start it up from the command line).  Open at least one window (a terminal emulator, for example), and wait for approximately 2 seconds.  In the case of a multiple-monitor system (such as mine), make sure the mouse is in the monitor with the window.

### Crash reports, logs, images, videos

I have included the log, although there does not seem to be any indication in the log that there is a problem.
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13766497/hyprland.log)

I have taken a screen capture, which demonstrates the behavior of Hyprland (0.31+) without the workaround.
[Video Demonstration.](https://youtu.be/K_SJmDcQ1X0)

**Comment by vaxerski** [comment]
espanso? #4085 #3858

if espanso, please close

**Comment by reteov** [comment]
That's what it was, alright!  Thanks!  Closing now.
