### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by TrimVis** [hyprwm/Hyprland#425]
Hi, I just got a random crash. Not sure what it was caused by, but hopes this still helps to harden your stability.

I was currently setting up & testing some basic hyprland config & also configuring swhkd simultaniously.
For that I had X running on tty1 and hyprland on tty2. I switched around for a full hour without any issues, but at some point after switching back it just had crashed, without me really interacting with it.
I'm not sure if it crashed during the switch to tty2 or while I was working in tty1. I wasn't changing any hyperland config files during my 'stay' in tty1.

Log: https://0x0.st/oj2G.log
Coredump: https://0x0.st/oj2D.txt

**Comment by vaxerski** [comment]
no clue. If this is not reproducible, it might be a one-off bug, possibly just after multiple TTY switches something imploded.

**Comment by TrimVis** [comment]
In case I can reproduce this issue reliantly, I will get back at you.
But for now I'm just gonna assume its a one-off bug.
