### ISSUE TITLE
Vim like <leader> key functionality.

### ISSUE THREAD

**Issue by nonl4331** [hyprwm/Hyprland#4251]
### Description

In Vim key combinations with the <leader> key don't require the <leader> key to be held down the entire time, instead after the <leader> key is pressed you have a short (default 1s) timeout to type the rest of the shortcut. 

This has the following advantages:
1. Significantly better one hand support, some keybinds are nearly impossible with one hand current such as meta+0 on QWERTY. This is especially useful if you are somebody that often keeps one hand on a mouse rather then both hands on a keyboard.
2. Better ergonomics, some claim that key chords can increase rates of RSI: (http://xahlee.info/kbd/banish_key_chords.html)
3. Reduced conflict with existing keybinds, most existing applications do not implement this kind of keyboard shortcut which reduces the conflict rate with existing software

My recommendation is to implement this kind of keybind for modifier keys as they do not directly type a letter when tapped so this should not conflict with existing behavior.

**Comment by tchofy** [comment]
You can do that with submap binds.
https://github.com/hyprwm/Hyprland/issues/1647#issuecomment-1809464370
