### ISSUE TITLE
initialTitle for nautilus shows "Loading..."

### ISSUE THREAD

**Issue by killown** [hyprwm/Hyprland#4254]
### Hyprland Version

Hyprland, built from branch main at commit 4f99e805b900b72f5e2bed54a1a44d10c8d54771 dirty (flake.lock: update). Date: Mon Dec 25 14:27:25 2023 Tag: v0.33.1-87-g4f99e805

### Bug or Regression?

Bug

### Description

Carregando = Loading

    "floating": false,
    "monitor": 0,
    "class": "org.gnome.Nautilus",
    "title": "Pasta pessoal",
    "initialClass": "org.gnome.Nautilus",
    "initialTitle": "Carregando…",
    "pid": 944592,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": "0x0",
    "focusHistoryID": 1
}]

### How to reproduce

hyprctl -j clients and check

**Comment by vaxerski** [comment]
makes perfect sense, not a bug
