### ISSUE TITLE
variable overshadowing or proper handling of variables when they are set multiple times

### ISSUE THREAD

**Issue by flick0** [hyprwm/Hyprland#4255]
### Description

let variables that are set multiple times in config use the value that was last set

**Comment by vaxerski** [comment]
elaborate?

**Comment by flick0** [comment]
i have this is config
```
$hello = 1
$hello = 2

exec=echo $hello
```

this shud output 2 but it wud output 1

**Comment by flick0** [comment]
also right now the variables feel like they take a random value(?) when theve been set multiple times, i have this setup where some variables are set in hyprland.conf and act as default values while im sourcing another theme.conf that wud set the same variables *before* hyprland.conf sets them, so in theory the variable value shud be taken from the one set in theme.conf and thats not always the case


for example ([video](https://github.com/hyprwm/Hyprland/assets/77581181/1ce9e39a-62e1-4af1-a6ea-4159d3534f1b))(it isnt previewing for some reason)

in the video, im not even changing the value of $FISHCONF but commenting and uncommenting $DRUN changes $FISHCONF's value (notice the different theme on terminal before and after commenting $DRUN) :0

what i have in hyprland.conf:
```
source=theme.conf

$DRUN=wofi --show drun
$FOOTCONF=~/.config/fish/config.fish

$TERM=footclient -o shell="fish -C 'source $FISHCONF'"
```
