### ISSUE TITLE
Jetbrains IDE keeps rendering tooltips

### ISSUE THREAD

**Issue by PoltyPoltou** [hyprwm/Hyprland#4257]
### Hyprland Version

Hyprland, built from branch HEAD at commit bfb4d66c8144a36f2c52530f10ae4bac2ac03b09  (compositor: spawn environment setup with keybind manager (3722)).

### Bug or Regression?

Regression

### Description

Jetbrains IDE keeps rendering tooltip. The bug I have is identical to #2245 . It is working in v0.33.1.

I bisected and found ba2af6f86d26fbf4b51aa37bf901e0118f46bbe3 to be faulty.

Reverting the commit on top of bfb4d66c8144a36f2c52530f10ae4bac2ac03b09 removes the bug.

### How to reproduce

Open a JetBrains IDE and leave mouse idle on left bar buttons. The tooltip will flicker, opening and closing repeatedly.

There is a video in the older ticket #2245 .

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13773201/hyprland.log)
Reading the socket while hovering a button (for 2sec) that should display a tooltip : [socket2.log](https://github.com/hyprwm/Hyprland/files/13773221/socket2.log)
My [config](https://github.com/hyprwm/Hyprland/files/13773241/config.txt)

**Comment by PoltyPoltou** [comment]
Thanks to https://github.com/hyprwm/Hyprland/issues/2315#issuecomment-1555896701 it solved my issue with version v0.34.0 !

The workaround is to add `windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1`  to your config.

**Comment by campbellcole** [comment]
The fix for this issue has changed recently. I was able to find a set of window rules that fix this issue again for Hyprland 0.47.2 and IntelliJ IDEA CE 2024.3.1.1:

```
# fix tooltips (always have a title of `win.<id>`)
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^(win.*)$
# fix tab dragging (always have a single space character as their title)
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^\\s$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^\\s$
```

Not entirely certain if all of these are required but I know this works so I'm happy with it.

**Comment by foxwoosh** [comment]
Thanks but I still cannot drag tabs for some reason, even with these rules :(

**Comment by dasmikko** [comment]
> Thanks but I still cannot drag tabs in Android Studio for some reason, even with these rules :(

I found some other window rules, and using them in conjunction with the rules from @campbellcole, tab draggins works flawlessly

```
windowrulev2 = tag +jb, class:^jetbrains-.+$,floating:1
windowrulev2 = stayfocused, tag:jb
windowrulev2 = noinitialfocus, tag:jb
```

**Comment by CUexter** [comment]
@laktosterror 
```
        windowrulev2 ="focusonactivate,class:^jetbrains-(?!toolbox)"
```

**Comment by laktosterror** [comment]
> [@laktosterror](https://github.com/laktosterror)
> 
> ```
>         windowrulev2 ="focusonactivate,class:^jetbrains-(?!toolbox)"
> ```

Hey, thanks for yor reply!
Doesnt seem to work, i believe because the rules conflict? noinitialfocus vs focusonactivate.

What i tried togheter with wayland mode: 

```
windowrulev2 = tag +jb, class:^jetbrains-.+$,floating:1
windowrulev2 = stayfocused, tag:jb
windowrulev2 = noinitialfocus, tag:jb
windowrulev2 ="focusonactivate,class:^jetbrains-(?!toolbox)"
```

**Comment by CUexter** [comment]
@laktosterror i tried to switched to wayland mode and encounter the same issue, any fix yet ?

**Comment by CUexter** [comment]
@laktosterror i think it is impossible in wayland mode, cuz there is no window title to differentiate tab and search box

**Comment by laktosterror** [comment]
> [@laktosterror](https://github.com/laktosterror) i tried to switched to wayland mode and encounter the same issue, any fix yet ?

No sorry, i went back to xwayland and use only this line in hyprland.conf to fix tabs/icon/shortcut on hover issue.

`windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$`

And as you say the title is the same for search window and tabs so they cant be differentiated. 

To bad we cant catch windows by initial size or something, tabs and icons are quit small.
