### ISSUE TITLE
Allow for bind and bindr on the same key

### ISSUE THREAD

**Issue by JoshuaFern** [hyprwm/Hyprland#426]
I'm trying to setup a universal push-to-talk key as a workaround to programs like Discord which don't yet support push-to-talk due to Wayland's security model.
```
bind=,191,exec,ponymix --source unmute
bindr=,191,exec,ponymix --source mute
```
With this configuration only the first bind seems to be working with the second ignored.

**Comment by vaxerski** [comment]
check if not fixado with 067e2d39f61324b3e04e63370d41142bf9355b5f

**Comment by JoshuaFern** [comment]
Seems to be fixed, thanks.
