### ISSUE TITLE
Open program in a layer

### ISSUE THREAD

**Issue by dafitt** [hyprwm/Hyprland#4266]
### Description

I would like to be able to set a window as a backgound. I thought of moving the window into an layer.

For example moving a terminal with an active command `pipes.sh` or `asciiquarium` into `Layer level 0 (background)` would look really cool.

**Comment by tchofy** [comment]
Have a look at [hyprwinwrap](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprwinwrap) from https://github.com/hyprwm/hyprland-plugins

**Comment by tchofy** [comment]
Have you tried a special workspace? Sounds just like what you want.

**Comment by vaxerski** [comment]
the answer is no. You have special workspaces for that just like tchofy said
