### ISSUE TITLE
exec program show in floating window without define it in windowrule

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4268]
### Description

I normally open thunar in tiled mode. But sometimes I want to open it in a floating window.
bind = SUPER, t, exec thunar
I wish this can work
bind = SUPER SHIFT, t, exec thunar ,floating:1
defined in windowrule make window always obey it, open it and togglefloating on it is not what I want.
even like preselect ,could preset next open window state as floating
bind = SUPER, f, layoutmsg, prewindowstate floating

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Dispatchers/#executing-with-rules

**Comment by vincentaxhe** [comment]
thank you , I recall a little about it ,but cannot find the related info, there is an old saying in China "抛砖引玉"
