### ISSUE TITLE
FIrefox cut off edges, different for each gtk theme

### ISSUE THREAD

**Issue by 0rteip** [hyprwm/Hyprland#4270]
### Hyprland Version

Hyprland, built from branch main at commit a0b675ec9e57af8bc631fc8cc54d062b58669a9f dirty (binds: add ignoreMods flag). Tag: v0.31.0-7-ga0b675ec  flags: (if any) debug

### Bug or Regression?

Regression

### Description

I'm facing an issue with Firefox, and I'm not certain which update is responsible because I recently performed a series of updates. After upgrading everything, I've observed that Firefox now displays cut-off edges. Interestingly, when I change the GTK theme, the extent of the cut-off area seems to vary – it can either increase or decrease.

I'm unsure about the specific update causing this problem. It would be great to get guidance on resolving this issue and understanding if it's related to a particular update or GTK theme. 

![screenshot_23 12 27-16:48:17](https://github.com/hyprwm/Hyprland/assets/94202558/c63f4254-2c5e-440b-a9db-7e3396639545)
![screenshot_23 12 27-17:30:48](https://github.com/hyprwm/Hyprland/assets/94202558/940d3fe3-6401-4dc9-aedd-611f5878e0ce)

### How to reproduce

I can't excatcly say how, i just updated from my previous configuration.

firefox version:
local/firefox-developer-edition 122.0b3-1

**Comment by vaxerski** [comment]
this was fixed months ago, you are on a very outdated version
