### ISSUE TITLE
thunar tend to restore last window size but hyprland ignore it

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4271]
### Description

as far as I know thunar tend to start in the same window size of last time in Xfce.  But in hyprland the request is ignored or none requests is accepted by hyprland nature. is there any rule can add an exception, support it to restore its last window size.

**Comment by vaxerski** [comment]
that's up to thunar to do correctly. Is it running in xwayland?

**Comment by vincentaxhe** [comment]
@vaxerski 
xwayland: 0 ,thunar run on wayland.
