### ISSUE TITLE
Change binary name from Hyprland -> hyprland

### ISSUE THREAD

**Issue by hughesjs** [hyprwm/Hyprland#4272]
Most linux binaries are lowercased by convention.

It's quite irritating to have to remember that `Hyprland` has a capital `H`.

Could we change this? 

It would also then line up with `hyprctl`.

**Comment by MightyPlaza** [comment]
alias ?

**Comment by vaxerski** [comment]
alias?

**Comment by hughesjs** [comment]
Like I know I *can* alias. I have aliased it... However, it just feels to me like it probably shouldn't be necessary and this would be a nice little QoL improvement

**Comment by vaxerski** [comment]
yeah but now that it's been Hyprland so long it would be a problem the other way, for all the people who are used to the capital

**Comment by hughesjs** [comment]
I think people will be generally fairly happy to revert to the norm, even if they are used to the capital. Unlearning an exception to a rule is generally easier than learning an exception

**Comment by vaxerski** [comment]
what if we ship an `ln -s` for the time being?

correct me if I am wrong but I think you can make relative links like `./Hyprland`

**Comment by vincentaxhe** [comment]
Hyprland reminds  people he is the one and true supervisor.

**Comment by vaxerski** [comment]
added a link in the makefile.

**Comment by hughesjs** [comment]
I think that's a reasonable compromise, is that going to be a long-term thing or will it be deprecated in a bit?

**Comment by vaxerski** [comment]
idk, either way it's minor, if anything.

**Comment by tienbuigia** [comment]
I support this lowercase change. And It would be better to add a link to the capital case just so old user doesn't need to change their config, but the official should be lowercase.

**Comment by vaxerski** [comment]
what's the difference...?

**Comment by tienbuigia** [comment]
So we can deprecate the capital one and remove it latter on.

**Comment by vaxerski** [comment]
which one is the symlink and which one is not does not change that.

**Comment by tienbuigia** [comment]
You are right.

**Comment by hughesjs** [comment]
> which one is the symlink and which one is not does not change that.

I don't think it makes a practical difference. It does make a signalling difference though. Hugely minor mind.

**Comment by hholst80** [comment]
Instead of low prio label it as "good First issue" and invite people to help

**Comment by vaxerski** [comment]
what is there to help with??

**Comment by hughesjs** [comment]
> added a link in the makefile.

> Instead of low prio label it as "good First issue" and invite people to help

Was this not already solved in https://github.com/hyprwm/Hyprland/commit/78f9ba9fdd7e258747b862ca2ae7d4cf5335f4ed

Should we just close this?

**Comment by vaxerski** [comment]
kinda was. We can.

**Comment by austinliuigi** [comment]
The linking was removed after changing the installation to use CMake rather than Make by 99aa34d. Could this be re-added?

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/pull/9091 voila
