### ISSUE TITLE
Deterministic monitor IDs

### ISSUE THREAD

**Issue by Cloudef** [hyprwm/Hyprland#4276]
### Description

Hyprland should process named monitors set up in config in order.
Consider config like this:
```
monitor = HDMI-A-1,highres,0x0,1
monitor = ,highres,auto,1
```
I wish the HDMI-A-1 monitor would always get the ID 0.

**Comment by vaxerski** [comment]
No. Why?

**Comment by Cloudef** [comment]
So that
```
bind = SUPER, 1, focusmonitor, 1
bind = SUPER, 2, focusmonitor, 2
```
actually work as expected

**Comment by vaxerski** [comment]
using IDs is discouraged. Why not `focusmonitor, HDMI-A-1`?

**Comment by Cloudef** [comment]
Because I don't want to specify others than my main monitor. But I think you are still correct.
Better way for me would be to do my own focusmonitor script that gets the ID order like this:
`hyprctl monitors -j | jaq 'sort_by(.x)[].id'`

**Comment by Cloudef** [comment]
What I ended up as a reference
https://github.com/Cloudef/nixos-flake/commit/c78d8f423c7bb9735346f91a4282114c25769231
