### ISSUE TITLE
-fcf-protection breaks function hooks

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#4277]
### Hyprland Version

Hyprland, built from branch main at commit 07132741bc02631966ca06ed54b55598a8487a5d dirty (renderer: use 120 as the denominator in scale checks). Date: Wed Dec 27 17:47:01 2023 Tag: v0.33.1-102-g07132741  flags: (if any)

### Bug or Regression?

Bug

### Description

[LOG] [functionhook] assembler returned:
/tmp/hypr/.hookcode.asm: Assembler messages:
/tmp/hypr/.hookcode.asm:1: Error: no such instruction: `invalid '

[ERR] [functionhook] failed, unsupported asm / failed assembling:
invalid 
push %r15
push %r14
push %r13
mov %rdi, %r13
push %r12

### How to reproduce

Build hyprland with CXXFLAGS="-fcf-protection" set.

Unfortunately this is one of the defaults in arch's /etc/makepkg.conf :/

I think all of my function hooks are broken, but I know 100% that getWorkspaceRuleFor and workspaceRulesRequest hooks fail with the above error. They both worked before the changes in 7474c81

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/b5e9e701-63d7-46f7-8574-cdeb9e530c46)
what the fuck is endbr64

**Comment by vaxerski** [comment]
hm. Reading the intel docs, this seems like something that _should_ terminate any function that was hooked as a "hacking attempt". Idk how it worked before. I think the biggest problem is just that udis86 doesn't understand this op.

**Comment by vaxerski** [comment]
check with above

**Comment by vaxerski** [comment]
though it's worth noting that, at least from what it seems to me, fcf-protection (intel CET) is precisely used to detect and prohibit what we are doing here; IOW it might be worth it to disable it in cmake / meson

**Comment by zakk4223** [comment]
Everything works again with that commit

**Comment by vaxerski** [comment]
great, closing
