### ISSUE TITLE
Hyprpm: Headers corrupted. pkexec returned: You need to run make all first.

### ISSUE THREAD

**Issue by mariospicross** [hyprwm/Hyprland#4284]
### Hyprland Version

Hyprland, built from branch main at commit 5f65946c84ed6ba3703e865d9a70f98cbb1ae479 dirty

### Bug or Regression?

Bug

### Description

i followed the steps to fix #4108, but when doing `hyprpm update` it fails to fix the headers. it states i need to run make all first, but its been months since i installed plugins manually and i honestly don't remember where to do this. if this is an easy fix and im just stupid i apologize

### How to reproduce

`sudo rm -rf /usr/include/hyprland`
`hyprpm update`

### Crash reports, logs, images, videos

[log.txt](https://github.com/hyprwm/Hyprland/files/13788470/log.txt)

**Comment by vaxerski** [comment]
that's odd. Can you give the log of `hyprpm update -v`?

**Comment by mariospicross** [comment]
is that not what I attached in the initial post or are you asking for something different?

**Comment by vaxerski** [comment]
right my bad

**Comment by vaxerski** [comment]
uhh can you clone the source manually, run `cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B ./build -G Ninja` in it and see if it doesn't fail by chance?

**Comment by mariospicross** [comment]
seemed to have built fine:
[log.txt](https://github.com/hyprwm/Hyprland/files/13789852/log.txt)

**Comment by vaxerski** [comment]
it's not built, it's configured, but yeah. That's odd.

**Comment by mariospicross** [comment]
any idea what it might be?

**Comment by vaxerski** [comment]
no clue. Hyprpm just runs standard commands in the background. See the source, try running the commands manually, see what's broken, I guess.

**Comment by UltraBlackLinux** [comment]
> uhh can you clone the source manually, run `cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B ./build -G Ninja` in it and see if it doesn't fail by chance?

For me it's not even configuring on fedora. I have all the deps installed, and it's not able to find any of them... Annoying.

<details>

```
-- Gathering git info
CMake Error at CMakeLists.txt:30 (add_subdirectory):
  The source directory

    /tmp/Hyprland/subprojects/udis86

  does not contain a CMakeLists.txt file.


-- Setting up wlroots
-- Found WaylandScanner at WaylandScanner-NOTFOUND
-- Found wayland-protocols at
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Checking for modules 'wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;libdrm;xkbcommon;libinput;pango;pangocairo;pixman-1'
--   Package 'wayland-server', required by 'virtual:world', not found
--   Package 'wayland-client', required by 'virtual:world', not found
--   Package 'wayland-cursor', required by 'virtual:world', not found
--   Package 'wayland-protocols', required by 'virtual:world', not found
--   Package 'cairo', required by 'virtual:world', not found
--   Package 'xkbcommon', required by 'virtual:world', not found
--   Package 'libinput', required by 'virtual:world', not found
--   Package 'pango', required by 'virtual:world', not found
--   Package 'pangocairo', required by 'virtual:world', not found
--   Package 'pixman-1', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:104 (pkg_check_modules)
```

</details>

**Comment by vaxerski** [comment]
Blame your packagers.

> For me it's not even configuring on fedora. I have all the deps installed, and it's not able to find any of them... Annoying.

Looks like you didn't clone `--recursive`. Assuming this is not from hyprpm because 1) it does and 2) it wouldn't clone to `/tmp/Hyprland`

**Comment by UltraBlackLinux** [comment]
> Looks like you didn't clone `--recursive`. Assuming this is not from hyprpm because 1) it does and 2) it wouldn't clone to `/tmp/Hyprland`

Ah that seems to be one problem at least. It's still not able to find all the deps, but that at least got rid of the first error.
I had to run it manually because, as I said, hyprpm just errors out, doing ... something.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/30348075/319153da-ef8e-4277-99eb-7d26f2f6121c)

![image](https://github.com/hyprwm/Hyprland/assets/30348075/e64e4d2f-e6dc-488f-88a5-3a4e21f98cdb)

It seems that the latest update has dealt a fatal blow to hyprpm.

1. Hyprpm will automatically detect and install header files in `/usr/local/include/hyprland` path. 
But the arch user use the command `yay - S  hyprland-git` installed hyprland header files in `/usr/include/hyprland`. 
So, all arch users having to manually remove `/usr/include/hyprland`  before using hyprpm updates.

2. There seems to be a bug in the header file detection of hyprpm. Even if you manually delete the previous `/usr/include` and `/usr/local/include` header files, and then run hyprpm update, the installation still fails.

**Comment by DreamMaoMao** [comment]
version:

Hyprland, built from branch main at commit 4b4bd90b1450cbfc01d9ac429363cc7cecd6be8b dirty (renderer: fixup misaligned fsv1 surfaces with uv).
Date: Mon Jan 29 07:42:49 2024

Tag: v0.34.0-79-g4b4bd90b

flags: (if any)

**Comment by vaxerski** [comment]
Oops, will fix in a sec.

**Comment by vaxerski** [comment]
check above.

**Comment by DreamMaoMao** [comment]
> ![image](https://private-user-images.githubusercontent.com/30348075/300364980-319153da-ef8e-4277-99eb-7d26f2f6121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjUyODMsIm5iZiI6MTcwNjUyNDk4MywicGF0aCI6Ii8zMDM0ODA3NS8zMDAzNjQ5ODAtMzE5MTUzZGEtZWY4ZS00Mjc3LTk5ZWItN2QyNmYyZjYxMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEwNDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMTg0NzU3ZTY1MzFlNTU4NGU1ZGVhNjUwOWE0ZDMzOGM3YmE5ZTY5ZjgwZGM2NDcwOGFlYzFjNTQzOGFiZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZlqzyq0fG5cNGiJ_e-WMGwcXZYwAJeZ8rmH0mggE4k)
> 
> ![image](https://private-user-images.githubusercontent.com/30348075/300365390-e64e4d2f-e6dc-488f-88a5-3a4e21f98cdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjUyODMsIm5iZiI6MTcwNjUyNDk4MywicGF0aCI6Ii8zMDM0ODA3NS8zMDAzNjUzOTAtZTY0ZTRkMmYtZTZkYy00ODhmLTg4YTUtM2E0ZTIxZjk4Y2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEwNDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNTU5OWZmNGMyMmQ4M2MzOGQ2MzE4NDVjNjY1NmZlYzEyNGYwY2EwY2YwMTMxYmY4MTQ5YjlhMmZlMDQ1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sEn3HOYsnYbfG3mG_uqQfm5ZS-wqAaiw63dqDxTPXqA)
> 
> It seems that the latest update has dealt a fatal blow to hyprpm.
> 
> 1. Hyprpm will automatically detect and install header files in `/usr/local/include/hyprland` path.
>    But the arch user use the command `yay - S  hyprland-git` installed hyprland header files in `/usr/include/hyprland`.
>    So, all arch users having to manually remove `/usr/include/hyprland`  before using hyprpm updates.
> 2. There seems to be a bug in the header file detection of hyprpm. Even if you manually delete the previous `/usr/include` and `/usr/local/include` header files, and then run hyprpm update, the installation still fails.

the second issue was fixed, how about the first issue?

I still need to remove `/usr/include/hyprland` after running 'yay-S hyprland-git' before using  `hyprpm update`.

Why not set the installation path of hyprpm to /usr instead of /usr/local?

**Comment by vaxerski** [comment]
overwriting system headers is a bad idea and nobody should do it. It can corrupt updates.

For example:
 - hyprland's headers have a new header, `"xyz.h"`. 
 - hyprpm writes it
 - user later updates their system headers
 - pacman: `error, cannot update. "xyz.h" exists in the filesystem`

**Comment by DreamMaoMao** [comment]
> overwriting system headers is a bad idea and nobody should do it. It can corrupt updates.
> 
> For example:
> 
> * hyprland's headers have a new header, `"xyz.h"`.
> * hyprpm writes it
> * user later updates their system headers
> * pacman: `error, cannot update. "xyz.h" exists in the filesystem`

The user had to delete /usr/include/hyprland themselves, otherwise hyprpm update could not be used, 

so now the system header file is not only overwritten but also needs to be deleted. 

That doesn't sound like a good idea either...

**Comment by vaxerski** [comment]
if system headers are up-to-date, no errors should occur.

I have said that elsweyr and will say it again, what to do when system headers are outdated is a question that needs thought and thinking through, both of which I am not very able to do right now

**Comment by vaxerski** [comment]
so what you are saying is that if we have system headers already, and they are mismatched, hyprpm should refuse to run?

**Comment by DreamMaoMao** [comment]
> so what you are saying is that if we have system headers already, and they are mismatched, hyprpm should refuse to run?

It seems that  if there is a system header,hyprpm will refuse to run until the user manually deletes the system header now.

So either the policy I proposed above or the current one,hyprpm is not allowed if there is a system header.

The only difference is that what I mentioned above is reminding the user to update, rather than forcing the user to delete the system header.

**Comment by rodrigolitzius** [comment]
(I'm not sure if this relates to this issue, but it's the closest one to the problem i had and since it's still open, i figured i'd post it here, sorry if this doesn't help)

the first time i tried updating hyprpm (first time using hyprland) i got a very similar issue. I unfortunately did not save the logs. The only difference i remember is the error code being 2 instead of 3 (The "You need to run make all first" part was the same). after a while i uninstalled cmake (I did not know hyprpm required it) and tried updating again. This time i got these error messages

```
[v] cmake returned: sh: line 1: cmake: command not found
[v] meson returned: sh: line 1: meson: command not found
```

I then installed both packages and got a little further. This time the error was:
```
/bin/sh: line 1: cpio: command not found
```

And after installing cpio, the update completed with no errors

So, it seems the issue here is that hyprpm does not warn you if don't have cmake, meson and cpio installed

full log: [hyprland-log.txt](https://github.com/hyprwm/Hyprland/files/14455762/hyprland-log.txt)

**Comment by rodrigolitzius** [comment]
and apprently the "Command not found" messages only appear if cmake is not installed. If it is, the errors messages for meson and cpio are hidden

**Comment by rodrigolitzius** [comment]
@vaxerski see my messages above. Sorry if this is unrelated to the issue.

**Comment by vaxerski** [comment]
I think this can be closed cuz how we store headers has changed since

**Comment by UltraBlackLinux** [comment]
well I ran into a similar issue again recently. It wouldn't even start compiling and errored out at the command that uses "*.h", apparently unable to find anything. No idea why but hyprpm definitely still has its issues... :/

**Comment by vaxerski** [comment]
nothing's perfect

**Comment by rodrigolitzius** [comment]
what about warning the user if one of the required packages is not installed? In the arch repos meson, cpio and cmake are listed as optional dependencies, and imo it should stay like that, but there should be at least a warning if they're not installed.

**Comment by vaxerski** [comment]
feel free to MR or open an issue for that
