### ISSUE TITLE
Trigger configreloaded ICP event after reloading the config

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#4285]
### Description

According to the [Plugin hooks event list](https://wiki.hyprland.org/Plugins/Development/Event-list/), reloading the config will trigger a hook `configReloaded` that can be used in plugins.

This issue requests that a `configreloaded` event is also sent to the IPC, and added to the [IPC event list](https://wiki.hyprland.org/IPC/#events-list). This is useful for things like the hyprland/workspaces module in waybar: if a new persistent workspace is set and the config is reloaded, a new workspace will have to be created.

**Comment by zjeffer** [comment]
I think it's as simple as just adding a call to `g_pEventManager->postEvent`, like we do here?

https://github.com/hyprwm/Hyprland/blob/4f3ee4c645c70a25072545ed8251412290e108f8/src/Compositor.cpp#L2573-L2575

**Comment by vaxerski** [comment]
ye, sure
