### ISSUE TITLE
xdg-shell's suspend state is set but never cleared leading to clients stop rendering

### ISSUE THREAD

**Issue by kchibisov** [hyprwm/Hyprland#4287]
### Hyprland Version

Don't know unfortunatelly, but I guess pretty recent.

### Bug or Regression?

Bug

### Description

See this https://github.com/alacritty/alacritty/issues/7485

and the logs in the end of the issue.

### How to reproduce

Follow the linked issue. It has all the relevant logs from which you may see configures not ever resetting suspend.

**Comment by vaxerski** [comment]
oops, odd

**Comment by vaxerski** [comment]
aw fuck

**Comment by kchibisov** [comment]
>aw fuck

can relate.

**Comment by vaxerski** [comment]
life sucks. Even more so when you have to write code.

**Comment by kchibisov** [comment]
Seems like the issue is still present with multiple monitors with the recent hyprland get.

hyprland tells us that the window is suspended, but then never makes it non-suspended, even though it's focused and getting keyboard. input.

cc @zmingee

**Comment by zmingee** [comment]
I can troubleshoot on my end and share any logs as needed, just let me know

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/84e4854b-c060-4c2e-b7da-6749c30403a3)
¯\\\_(ツ)_/¯

**Comment by kchibisov** [comment]
it's not like our handling is overly complex either.

![image](https://github.com/hyprwm/Hyprland/assets/27620401/d7542cb4-2ac6-4547-bd7d-ecdfe3d4cddc)

and we basically pause rendering once `Occluded(true)` which is what happening, but then never getting a `Occluded(false)` to resume. Maybe the window got `hidden` once you send it from one monitor to another, since it kind of changes workspace and maybe it makes window to be hidden for a short period of time thus messes up the state?

But that's just a guess, since it's likely user has 2 workspaces visible at the same time on multiple monitors and sending from one to another.

**Comment by zmingee** [comment]
> But that's just a guess, since it's likely user has 2 workspaces visible at the same time on multiple monitors and sending from one to another.

That is the case. I have two monitors, with independent workspaces on them. When the transition occurs between monitors _and_ workspaces, the rendering output of alacritty stops.

**Comment by vaxerski** [comment]
> When the transition occurs between monitors and workspaces, the rendering output of alacritty stops.

`movetoworkspace`? `movewindow`? Repro steps?

**Comment by zmingee** [comment]
Generally it breaks for me with the following sequence:

- launch alacritty
- start `echo` loop to monitor output rendering
- move workspace with alacritty window to other monitor (dual setup) with `movecurrentworkspacetomonitor` (rarely seems to occur with `movetoworkspace` or `movewindow` across a monitor boundary.
- note output rendering freeze
- quit alacritty

**Comment by kchibisov** [comment]
I'd add that according to the logs output gets frozen once we get `Occluded(true)` which is expected from our side and the logic we run is present on the screenshot I've posted.

I'd kind of suggest to re-ensure that the hyprland was really from the latest git though and that you've actually ran it, somehow.

**Comment by zmingee** [comment]
I've updated to/installed the latest hyprland from git multiple times. Last time I did was yesterday afternoon.
