### ISSUE TITLE
hyprctl dispatch window param does not support title/class regex

### ISSUE THREAD

**Issue by kkard2** [hyprwm/Hyprland#4289]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1). Tag: v0.33.1  flags: (if any)

### Bug or Regression?

Bug

### Description

title. `pid:` and `address:` seem to work fine. my current workaround is:
```bash
hyprctl dispatch togglefloating pid:$(hyprctl clients | grep -A 2 'initialClass: org.kde.dolphin' | sed -n 's/\s\+pid: \([0-9]\+\)/\1/p')
```
instead of just running `hyprctl dispatch togglefloating 'class:^(org.kde.dolphin)$'` (i know this regex is scuffed but it works fine in a `windowrulev2`)

if this is intended it should be documented

### How to reproduce

try to use  `class:` or `title:` specifiers in `hyprctl dispatch` (tested `togglefloating` and `movetoworkspace`)

**Comment by MightyPlaza** [comment]
just add the class in the end, like:
`hyprctl dispatch togglefloating foot`

**Comment by kkard2** [comment]
> just add the class in the end, like: `hyprctl dispatch togglefloating foot`

i don't think i understand; would that match a class "foot"? (i can't check it rn)
is this behavior explained somewhere?

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Dispatchers/#parameter-explanation

**Comment by kkard2** [comment]
okay, i have no idea how i managed to make `title:` not work yesterday, but now it does so that's definitely my skill issue
and i also thought `class:` is necessary because of `windowrulev2` syntax, but now i see that it's different (i literally ignored documentation)

sorry for wasting anyone's time
