### ISSUE TITLE
[Gestures] Swiping to move to the right when at the last workspace causes weird animation

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#429]
When I swipe to move one workspace to the right while I'm on the last workspace, normally nothing should happen. However, the windows from the leftmost workspace animate as if I were moving from the first workspace to the left. This only happens once, and then it won't happen until I go to the first workspace and back again.

https://user-images.githubusercontent.com/44881120/180759928-24c2f984-36d2-47c5-8318-a590c8ce25d5.mp4

**Comment by vaxerski** [comment]
yes yes I will rewrite it

**Comment by vaxerski** [comment]
should be fixed in 3e6abaf680ac85daacc677836655e9aa222b1528

**Comment by TheSunCat** [comment]
Thanks! That fixed it. However it seems gestures are now broken if you only have one workspace. It still tries to animate even though there's nowhere to go.

**Comment by vaxerski** [comment]
14176f01ca5c584cc17db2dea3d0968c05d8cc01 fixed\

**Comment by TheSunCat** [comment]
I am never not astounded by the speed you fix these issues with.
It is indeed fixed, thank you! Closing.

**Comment by vaxerski** [comment]
I am in the middle of nowhere on a 10 year old laptop with 5Mb/s down and 2Mb/s up
