### ISSUE TITLE
Strange clipboard behaviour

### ISSUE THREAD

**Issue by quepop** [hyprwm/Hyprland#4292]
### Hyprland Version

r113.78f9ba9f

### Bug or Regression?

Bug

### Description

I've been using `hyprland-git` package along `hyprpaper-git` and `xdg-desktop-portal-hyprland-git` on my Manjaro install for a month now. Everything worked flawlessly till the latest hyprland update - I update AUR packages frequently. After my latest upgrade which brought the version of:

- `hyprland`  to r113.78f9ba9f
- `hyprpaper` to r124.ef0e051 
- `xdg-desktop-portal-hyprland` to r336.0a318a7

I can no longer copy out of Mathematica to any other app besides Alacritty but i still can paste to it. I've tested it with and without clipboard managers and in both cases there is nothing in the PRIMARY and CLIPBOARD buffers. All my apps are running under Wayland natively including Mathematica. The bug is really frustrating and I had to stop using hyprland altogether beacuse of it. 

### How to reproduce

First Install Mathematica 13.3.1 and Alacritty. To test the clipboard behaviour copy out of Mathematica then paste to alacritty and some other app e.g Firefox.

**Comment by MightyPlaza** [comment]
does it work on https://aur.archlinux.org/packages/sway-git-wlroots-git?
if no it's a wlroots issue

**Comment by quepop** [comment]
> does it work on https://aur.archlinux.org/packages/sway-git-wlroots-git ? if no it's a wlroots issue

I've tested it now. It doesn't work. Should I open a new issue in the wlroots repo?

**Comment by MightyPlaza** [comment]
> > does it work on https://aur.archlinux.org/packages/sway-git-wlroots-git ? if no it's a wlroots issue
> 
> I've tested it now. It doesn't work. Should I open a new issue in the wlroots repo?

I'm not sure
You could build wlroots from source and use tinywl (wlroots-included compositor) to finding the commit that broke it
However it's more likely that the issue is on the client than on wlroots, so maybe try to get some support from them

If nothing else works try running it under xwayland

**Comment by NotAShelf** [comment]
If you can reproduce the issue reliably on other wlroots compositors (sway-git, river, etc.) it's not exactly a Hyprland issue. You've mentioned it started occuring after a Hyprland update, so chances are it's a regression/bug in wlroots itself. Try bisecting it to help the wlroots developers on their gitlab repository.

**Comment by Gruak** [comment]
I have quite similar issues with copying to clipboard and interestingly I'm on manjaro as well.

**Comment by quepop** [comment]
I solved it by launching Mathematica with QT_QPA_PLATFORM env variable set to xcb. Whats strange about it is that Mathematica still runs on wayland and not xwayland as it supposed to (after changing the value of the variable).

**Comment by quepop** [comment]
Mathematica 14 somehow solves this issue without the need for any extra flags.
