### ISSUE TITLE
Blur Pixel Drop 

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#4293]
### Hyprland Version

Hyprland, built from branch main at commit 78f9ba9fdd7e258747b862ca2ae7d4cf5335f4ed dirty (makefile: add symbolic link for lowercase binary name). Date: Fri Dec 29 15:07:58 2023 Tag: v0.33.1-113-g78f9ba9f

### Bug or Regression?

Bug

### Description

I have encountered an issue where the pixel blurring in Hyprland drops significantly when moving windows on my system.

i noticed this issue in both waybar and foot 

https://github.com/hyprwm/Hyprland/assets/54718375/4f577064-06a6-41e9-b3b4-2171c61f4510

### How to reproduce

1 . add this configuration
```
decoration {
    active_opacity = 1
    inactive_opacity = 1

    blur {
	enabled = yes
	size = 3
	passes = 3
	popups = true
	noise = 0.04
	brightness = 0.9
	contrast = 0.9
	new_optimizations = 1
	special = 0
   }
   
layerrule = blur,waybar
layerrule = ignorezero, waybar

```
2. try moving windows

**Comment by vaxerski** [comment]
#3822

I am still unable to repro on my own 10bit laptop.

FWIW it will go away if you set the bitdepth to 8
