### ISSUE TITLE
Dropping window on fullscreen window weird behavior

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#4298]
### Hyprland Version

❯ hyprctl version Hyprland, built from branch main at commit 78f9ba9fdd7e258747b862ca2ae7d4cf5335f4ed dirty (makefile: add symbolic link for lowercase binary name). Date: Fri Dec 29 01:37:58 2023 Tag: v0.33.1-113-g78f9ba9f

### Bug or Regression?

Bug

### Description

If you drag and drop a window over a fullscreen window, the window floats strangely above the fullscreen window but it's not focused. It's in both dwindle and master, but the behavior is slightly different in each

### How to reproduce

1. Have two monitors
2. have a fullscreen window on monitor 1
3. drag a window from monitor 2 and drop it over monitor 1

**Comment by Seme4eg** [comment]
did reproduce your issue, yes
your case helped me see that my issue can be reproduced only if there are 2 fullscreen (maximised) windows on workspace
then when  you move that workspace to another monitor the window that is on top of the stack is bigger than it should be. Will edit my issue now/
but i don't know whether those issues are related or not, hopefully when either of one gets fixed another one will as well

**Comment by thejch** [comment]
I don't know why or how, but this seems to have been fixed.
