### ISSUE TITLE
Dragging a window to a floating group doesn't adjust its size after it's added

### ISSUE THREAD

**Issue by dranull** [hyprwm/Hyprland#4302]
### Hyprland Version

5f8e406

### Bug or Regression?

Bug

### Description

Title, video...

### How to reproduce

- Have a floating window with grouping
- Open a new floating window outside of the group and make it smaller than the group window
- Drag the floating window to the group

The content will be upscaled, resizing or moving the window will correct it.

### Crash reports, logs, images, videos
https://github.com/hyprwm/Hyprland/assets/150595692/345f4b87-9730-43c9-ac5e-844ffac7516a

**Comment by MightyPlaza** [comment]
don't think I can repro this anymore
