### ISSUE TITLE
Mouse doesn't work when in the middle of the screen

### ISSUE THREAD

**Issue by AhoyISki** [hyprwm/Hyprland#431]
### Steps to reproduce:
1- Put the mouse in a region in the center of the screen.
2- Try to do anything with the mouse.

### Expected outcome:
The mouse does the action I have requested.

### Noted outcome:
The mouse does nothing. Clicking, dragging, scrolling, and even auto focus when switching workplaces don't work.

Another thing to note is that on workspaces with the kitty terminal, the mouse is doubled in size _outside_ of the central area, and only has a normal size within it.

### Here's a demonstration:
https://user-images.githubusercontent.com/91404038/180819399-89c9cb8f-9e27-4ecd-a180-447001b4aa2e.mp4

**Comment by AhoyISki** [comment]
Nvm, it was eww on my end

**Comment by AhoyISki** [comment]
Although the doubling of cursor size part still remains, it's just that now it's on the whole screen

**Comment by vaxerski** [comment]
my man's forgot to `export XCURSOR_SIZE=24` omegalul

**Comment by AhoyISki** [comment]
> my man's forgot to `export XCURSOR_SIZE=24` omegalul

It works, but that's never been needed in any other WM or DE I've ever used.

**Comment by AhoyISki** [comment]
Thanks for the tip tho

**Comment by vaxerski** [comment]
cuz they usually export it themselves
