### ISSUE TITLE
Press(Mod)+Press(Key)+Release(Mod)+Release(Key) sends release for the Key

### ISSUE THREAD

**Issue by rszyma** [hyprwm/Hyprland#4310]
There's a bug, when Press(Mod)+Press(Key)+Release(Mod)+Release(Key) a release for Key is sent (incorrect behavior), while Press(Mod)+Press(Key)+Release(Key)+Release(Mod) don't sent the release for Key (correct behavior)

_Originally posted by @rszyma in https://github.com/hyprwm/Hyprland/issues/4304#issuecomment-1872566066_
            
____

IMO very unlikely to cause issues, but reporting this anyway so it's known.

Can be observed for example in https://config.qmk.fm/#/test

**Comment by MightyPlaza** [comment]
is this fixed?

**Comment by rszyma** [comment]
seems like so (at least on 918d8340afd652b011b937d29d5eea0be08467f5)
