### ISSUE TITLE
Hyprland received signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by 3xploiton3** [hyprwm/Hyprland#4311]
### Hyprland Version

d74607e414dcd16911089a6d4b6aeb661c880923

### Bug or Regression?

Bug

### Description

command `Hyperland`

Hyprland received signal 11 (Segmentation fault)

Version: d74607e414dcd16911089a6d4b6aeb661c880923
Tag: v0.33.1

### How to reproduce

crash at startup

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Who tried dividing by zero?!

Hyprland received signal 11 (Segmentation fault)

Version: d74607e414dcd16911089a6d4b6aeb661c880923
Tag: v0.33.1

System info:
	System name: Linux
	Node name: arch
	Release: 6.6.8-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x55c2e40b4b92]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x4f4) [0x55c2e4083924]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x47) [0x55c2e3ffedf7]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7f4d4d25c710]
		??
		??:0
	#4 | /usr/lib/libwlroots.so.13032(+0x36b9a) [0x7f4d4dbe9b9a]
		??
		??:0
	#5 | /usr/lib/libwlroots.so.13032(+0x3af2f) [0x7f4d4dbedf2f]
		??
		??:0
	#6 | /usr/lib/libwlroots.so.13032(wlr_renderer_begin_with_buffer+0x24) [0x7f4d4dbe7bd4]
		??
		??:0
	#7 | /usr/lib/libwlroots.so.13032(+0x53dac) [0x7f4d4dc06dac]
		??
		??:0
	#8 | /usr/lib/libwlroots.so.13032(+0x5de6d) [0x7f4d4dc10e6d]
		??
		??:0
	#9 | /usr/lib/libwlroots.so.13032(wlr_output_cursor_set_buffer+0xee) [0x7f4d4dc1117e]
		??
		??:0
	#10 | /usr/lib/libwlroots.so.13032(+0x78dd3) [0x7f4d4dc2bdd3]
		??
		??:0
	#11 | /usr/lib/libwlroots.so.13032(wlr_cursor_set_xcursor+0x68) [0x7f4d4dc2c558]
		??
		??:0
	#12 | Hyprland(_ZN11CCompositor15startCompositorEv+0x604) [0x55c2e40000f4]
		??
		??:0
	#13 | Hyprland(main+0xa89) [0x55c2e3fe8009]
		??
		??:0
	#14 | /usr/lib/libc.so.6(+0x27cd0) [0x7f4d4d245cd0]
		??
		??:0
	#15 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f4d4d245d8a]
		??
		??:0
	#16 | Hyprland(_start+0x25) [0x55c2e3ffc035]
		??
		??:0

Log tail:
al for owner 55c2e65dbc90: 55c2e65dbcd8 -> 55c2e41d3220 (owner: OutputMgr)
[LOG] Registered signal for owner 55c2e660a4b0: 55c2e660a4c8 -> 55c2e41d3200 (owner: PointerConstraints)
[LOG] Registered signal for owner 55c2e660a300: 55c2e660a330 -> 55c2e41d31e0 (owner: XDGDecoMgr)
[LOG] Registered signal for owner 55c2e65e87b0: 55c2e65e87e0 -> 55c2e41d31c0 (owner: VirtPtrMgr)
[LOG] Registered signal for owner 55c2e65e8700: 55c2e65e8730 -> 55c2e41d31a0 (owner: VKeyboardMgr)
[LOG] Registered signal for owner 55c2e5e1c630: 55c2e5e1c630 -> 55c2e41d3180 (owner: WLRRenderer)
[LOG] Registered signal for owner 55c2e65e8a10: 55c2e65e8a40 -> 55c2e41d3160 (owner: WLRIdleInhibitMgr)
[LOG] Registered signal for owner 55c2e65e57e0: 55c2e65e5810 -> 55c2e41d3140 (owner: PowerMgr)
[LOG] Registered signal for owner 55c2e65e8e90: 55c2e65e8ec0 -> 55c2e41d3120 (owner: IMEMgr)
[LOG] Registered signal for owner 55c2e65e8de0: 55c2e65e8e10 -> 55c2e41d3100 (owner: TextInputMgr)
[LOG] Registered signal for owner 55c2e65e8f40: 55c2e65e8f68 -> 55c2e41d30e0 (owner: ActivationV1)
[LOG] Registered signal for owner 55c2e65e9090: 55c2e65e9098 -> 55c2e41d30c0 (owner: SessionLockMgr)
[LOG] Registered signal for owner 55c2e65e56c0: 55c2e65e5700 -> 55c2e41d30a0 (owner: GammaCtrlMgr)
[LOG] Registered signal for owner 55c2e65e9130: 55c2e65e9138 -> 55c2e41d3080 (owner: CursorShapeMgr)
[LOG] Registered signal for owner 55c2e65e91d0: 55c2e65e9200 -> 55c2e41d3060 (owner: TearingControlMgr)
[LOG] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Running on WAYLAND_DISPLAY: wayland-1
[LOG] Attached a keyboard with name x11-keyboard
[LOG] Registered signal for owner 55c2e64a3040: 55c2e5d3b9f0 -> 55c2e64a3048 (owner: Keyboard)
[LOG] Registered signal for owner 55c2e64a3040: 55c2e5d3b9e0 -> 55c2e64a30b0 (owner: Keyboard)
[LOG] Registered signal for owner 55c2e64a3040: 55c2e5d3b8c0 -> 55c2e64a3180 (owner: Keyboard)
[LOG] Registered signal for owner 55c2e64a3040: 55c2e5d3ba00 -> 55c2e64a3118 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "x11-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] [hookSystem] New hook event registered: activeLayout
[LOG] Set the keyboard layout to us and variant to  for keyboard "x11-keyboard"
[LOG] New keyboard created, pointers Hypr: 55c2e64a3040 and WLR: 55c2e5d3b8a8
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703d18 -> 55c2e672cd40 (owner: )
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703da8 -> 55c2e672cda8 (owner: )
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703d98 -> 55c2e672ce10 (owner: )
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703d28 -> 55c2e672ce78 (owner: )
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703d38 -> 55c2e672cee0 (owner: )
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703d58 -> 55c2e672cf48 (owner: )
[LOG] Registered signal for owner 55c2e672c8f0: 55c2e6703d78 -> 55c2e672cfb0 (owner: )
[WARN] No rule found for X11-1, trying to use the first.
[LOG] Applying monitor rule for X11-1
[ERR] Monitor X11-1 has NO PREFERRED MODE
[LOG] output X11-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] Monitor X11-1 -> destroyed all render data
[LOG] arrangeMonitors: 1 to arrange
[LOG] arrangeMonitors: X11-1 auto [0, 0.00]
[LOG] arrangeMonitors: X11-1 xwayland [0, 0.00]
[LOG] Monitor X11-1 data dump: res 1024x768@60.00Hz, scale 1.00, transform 0, pos 0x0, 10b 0
[LOG] Added new monitor with name X11-1 at [0, 0] with size [1024, 768], pointer 55c2e6703bf0
[LOG] New monitor: WORKSPACEID 1, exists: 0
[LOG] [hookSystem] New hook event registered: createWorkspace
[LOG] [hookSystem] New hook event registered: monitorAdded
[LOG] Attached a mouse with name x11-pointer
[LOG] Registered signal for owner 55c2e672d040: 55c2e6703e98 -> 55c2e672d100 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 55c2e6703e80
[LOG] Attached a touch device with name x11-touch
[LOG] New touch device added at 55c2e65cbc10
[LOG] Registered signal for owner 55c2e65cbc10: 55c2e6703fb0 -> 55c2e65cbc58 (owner: TouchDevice)

**Comment by vaxerski** [comment]
running hyprland inside an x11 session is not supported
