### ISSUE TITLE
Save Window and Workspace position on exit

### ISSUE THREAD

**Issue by Root-Time** [hyprwm/Hyprland#4312]
### Description

Is it possible to create the feature for example on crash or default that we save the position of windows and workspace on exit like on shutdown and so on?

Would be especially nice on crashes.

**Comment by vaxerski** [comment]
Not planned. Already discussed somewhere else I forgot where

**Comment by Root-Time** [comment]
> Not planned. Already discussed somewhere else I forgot where

would it be even possible like as a plugin?

**Comment by vaxerski** [comment]
yes, of course

**Comment by tchofy** [comment]
I remember this one, it was discussed in https://github.com/hyprwm/Hyprland/pull/3337.

**Comment by vaxerski** [comment]
thanks. I get lost in all the issues more and more.
