### ISSUE TITLE
Firefox's window is offsetted + Odd scaling

### ISSUE THREAD

**Issue by zinh88** [hyprwm/Hyprland#4313]
### Hyprland Version

Hyprland, built from branch main at commit 424c9a7e704590db5c823557e5e388e366f7b1cd dirty (render: stop locking SWC on tearing). Tag: v0.30.0-86-g424c9a7e

### Bug or Regression?

Bug

### Description

![20240101_01h40m32s_grim](https://github.com/hyprwm/Hyprland/assets/89087139/c989da77-8f43-4516-8a5b-ab52ff17d5d8)

After updating all system packages (which included Firefox 121), pic is how it looks now. The cursor is also pointing at a point skewed downward. Downgrading firefox to 120 did not help at all, the result was the same.

### How to reproduce

Open Firefox

**Comment by phonetic112** [comment]
ancient version, this was fixed recently

**Comment by zinh88** [comment]
Oh, I am so sorry, it had been working perfectly for a long time.

**Comment by iTzGooDLife** [comment]
How did you fix it? I have the same bug

**Comment by phonetic112** [comment]
update

**Comment by iTzGooDLife** [comment]
I did. I updated a few minutes ago...

**Comment by zinh88** [comment]
I just closed the issue because I assumed it would work after updating, will do that later.

**Comment by iTzGooDLife** [comment]
I was using `hyprland-nvidia-git`. I had no idea the package was deprecated. I uninstalled it and installed `hyprland-git` and the problem is solved. Thanks!

**Comment by zinh88** [comment]
Okay, tested and working on:
Hyprland, built from branch main at commit 46997a764304366d772456c20b1c719960927aa7  (renderer: fix auto scale detection with fractional).
Date: Sun Dec 31 17:54:24 2023
Tag: v0.33.1-119-g46997a76
