### ISSUE TITLE
Unable to access regular workspace from special workspace 

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#4314]
After the update, I am unable to access normal workspace when the special workspace is enabled. I can only focus on windows within the special workspace.

Is this a new feature or a bug? Is there any way to access the regular workspace while the special workspace is active?

**Comment by NotAShelf** [comment]
This is the new behaviour of the special workspace. To my knowledge there isn't a config option to change it, but it's worth taking a look at the [wiki](https://wiki.hyprland.org/Configuring/Variables)
