### ISSUE TITLE
need to drag the file twice to successfully drag the file

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/Hyprland#4316]
### Hyprland Version

Hyprland, built from branch main at commit 46997a764304366d772456c20b1c719960927aa7  (renderer: fix auto scale detection with fractional). Date: Sun Dec 31 20:54:24 2023 Tag: v0.33.1-119-g46997a76  flags: (if any

### Bug or Regression?

Bug

### Description

It takes dragging the file twice for the gtk client in xwayland mode to receive a drag event signal.

you can't drag file in gtk file explorer(xwayland mode) at the first times.

then, you  can successfully drag the file at  the second and third times ...

when you close the file explorer, and reopen it.the problen occur again.

Have tested in nemo and thunar.

https://github.com/hyprwm/Hyprland/assets/30348075/cef5a941-faf4-4e5b-8b9d-3c3706a1627c

### How to reproduce

1.exec comand:

GDK_BACKEND=x11 thunar 
or
GDK_BACKEND=x11 nemo

2.drag a file

### Crash reports, logs, images, videos

[log.txt](https://github.com/hyprwm/Hyprland/files/13804262/log.txt)

**Comment by DreamMaoMao** [comment]
thunar and nemo have also are tested in xorg-gnome, wayland-gnome and dwm. the problem just occur in hyprland.

**Comment by vaxerski** [comment]
what about sway?

**Comment by DreamMaoMao** [comment]
https://github.com/hyprwm/Hyprland/assets/30348075/830885f6-1741-4e14-8271-8f74e8a3893b

sway no this problem

@vaxerski

**Comment by vaxerski** [comment]
no clue, maybe the commit that rejects focus to random unmanaged?

https://github.com/hyprwm/Hyprland/commit/cdcc5aba06f20005842cf966b23af50456dc7142

Anyways, closing
