### ISSUE TITLE
Floating windows don't seem to render properly when switching workspaces with the touchpad

### ISSUE THREAD

**Issue by flpFlan** [hyprwm/Hyprland#4317]
### Hyprland Version

Hyprland, built from branch main at commit 46997a764304366d772456c20b1c719960927aa7 dirty (renderer: fix auto scale detection with fractional). Date: Sun Dec 31 20:54:24 2023 Tag: v0.33.1-119-g46997a76  flags: (if any)

### Bug or Regression?

Bug

### Description

I have a float window open on a full screen window, with the float window partially outside the full screen window. 

When I switch the workspace halfway with the touchpad, the float window doesn't render properly, as the attached image shows.

However, without the full screen window open, the float window still works fine.

My Window rules:
```
 #chromium
 windowrule = noborder, chromium

 windowrule = float,title:apps_floating
 windowrule = size 1280 720, title:apps_floating
 windowrule = center, title:apps_floating
 windowrule = float,title:math
 windowrule = size 1000 300, title:math
 windowrule = center, title:math
 windowrulev2 = float, title:drawing
 windowrulev2 = center,floating:0
```

### How to reproduce

Just open a fullscreen window with a float window partially out of it, and swipe with three fingers to the left or right on touchpad

### Crash reports, logs, images, videos

![2024-01-01-191256_hyprshot](https://github.com/hyprwm/Hyprland/assets/112972069/83915378-d5e1-46fe-900f-3f6bc8dd048f)

**Comment by NotAShelf** [comment]
Is this on a nvidia gpu, perchance?

**Comment by flpFlan** [comment]
> Is this on a nvidia gpu, perchance?

No, it's amd

**Comment by wxlyyy** [comment]
https://github.com/hyprwm/Hyprland/assets/150794012/138460d0-0573-4849-ae42-200bfd8b2241

**Comment by romanstingler** [comment]
this one is solved
