### ISSUE TITLE
Discover clients which prevent sleep by using inhibit_idle

### ISSUE THREAD

**Issue by mindrunner** [hyprwm/Hyprland#4322]
### Description

In `sway` I was using a script to determine whether a client is inhibiting idle or not:
```
swaymsg -t get_tree | jq -e 'recurse(.floating_nodes[]?,.nodes[]?) | select(.inhibit_idle == true) | .name'
```

Is there any equivalent in `Hyprland` or can this be added to `hyprctl clients`?

**Comment by vaxerski** [comment]
not atm, can be added as a prop to hyprctl clients

**Comment by mindrunner** [comment]
Would love to see that.

**Comment by demonspork** [comment]
Just adding to this, this is a great idea. I cannot for the life of me figure out which application is keeping the monitor awake.

**Comment by vaxerski** [comment]
sure
