### ISSUE TITLE
option to access regular workspace from special workspace

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#4323]
### Description

After the update, I am unable to access normal workspace when the special workspace is enabled. I can only focus on windows within the special workspace.

it would be nice to add an option to enable and disable access to regular workspaces from the special workspaces

**Comment by vaxerski** [comment]
why?

**Comment by shadowelite-sec** [comment]
> why?

> why?

just like minimize 

I use 'special' for reference purposes. For example, I start some processes in a special workspace, such as an Android emulator and web preview. However, I don't want them to be displayed all the time because I'm using a small display. When I want to see the preview from the special workspace and interact in the regular one, I use the 'togglespecialworkspace' option.

After the update, it really affected the workflow.

**Comment by vaxerski** [comment]
it's intended behavior, though. With the special workspace open, you work on the special workspace. If you want to go back to work on the regular workspace, you toggle the special workspace off.

If you want a preview with the input on the regular windows, why not just use a floating window?

**Comment by shadowelite-sec** [comment]
> it's intended behavior, though. With the special workspace open, you work on the special workspace. If you want to go back to work on the regular workspace, you toggle the special workspace off.
> 
> If you want a preview with the input on the regular windows, why not just use a floating window?

I appreciate your suggestion of using a floating window, but I am more comfortable with the method I mentioned. If the method I referred to earlier is not planned for implementation, please feel free to close this issue. Thanks.

**Comment by Oglo12** [comment]
@vaxerski It really broke my workflow too! I really hope you add an option or revert the change!
I use Picture-in-picture mode so I can watch videos whilst doing my work, and I really enjoyed how the special workspace automatically made the windows "sticky", and how the windows would also display over fullscreen apps!

![image](https://github.com/hyprwm/Hyprland/assets/80219532/fac880dc-a51e-46bd-bf3f-57671db14a15)
