### ISSUE TITLE
VRAM leak (?) on nvidia when resizing some windows

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#4326]
### Hyprland Version

Hyprland, built from branch main at commit 1a4f23eb2fee77b23b2cc6ff1fbfc87f60f10314 dirty (renderer: Only force nearest neighbor when the sizes are off by one or two (4325)).
Date: Mon Jan 1 11:20:27 2024
Tag: v0.34.0-12-g1a4f23eb

### Bug or Regression?

Bug

### Description

vram leak (?) on nvidia when resizing some windows, e.g. firefox
requires nvidia_anti_flicker = false
It does seem to stop at a certain amount though
Maybe related to #4294

### How to reproduce

1. Have an nvidia GPU
2. Set OpenGL:nvidia_anti_flicker = false
3. In an empty workspace, open kitty and firefox next to each other. Drag to resize them, and vram goes through the roof

**Comment by vaxerski** [comment]
if it stops, it might be nvidia just queueing frees but not actually conducting them right away

**Comment by thejch** [comment]
Yeah it stops but it's after it reaches 1.5 or 2 GB for me so still very bad. Nothing can be done on hyprland side?

**Comment by vaxerski** [comment]
No clue, I've never seen this happen on AMD, so it could also be an nvidia bug.

**Comment by wxlyyy** [comment]
I can't reproduce it on nvidia

**Comment by kelvie** [comment]
I wonder if it's related to the issue I'm seeing here (although it's xwayland and not firefox)

https://gitlab.freedesktop.org/xorg/xserver/-/issues/1617

**Comment by thejch** [comment]
This seems somehow mostly gone now, probably due to some of the recent rewrites. Now although it does still happen sometimes, it never lasts very long before the vram goes back down so it doesn't really concern me anymore. I'm just gonna close this for now.
