### ISSUE TITLE
Example plugin isn't buildable

### ISSUE THREAD

**Issue by Micovec** [hyprwm/Hyprland#4329]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 13:03:15 2024
Tag: v0.34.0

flags: (if any)

```

</details>

### Bug or Regression?

Regression

### Description

Example plugin in `example/examplePlugin` is no longer buildable after first party package manager was added. Some Hyprland API got changed and there is missing `hyprpm.toml` for the new `hyprpm`.

I also checked `hyprwm/hyprland-plugins` and they seem to be fine.

### How to reproduce

- Clone repo
- Navigate to `example/examplePlugin`
- Run `make`

### Crash reports, logs, images, videos

g++ -shared -fPIC --no-gnu-unique main.cpp customLayout.cpp customDecoration.cpp -o examplePlugin.so -g `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++2b
main.cpp: In function ‘void onNewWindow(void*, std::any)’:
main.cpp:38:85: error: invalid new-expression of abstract class type ‘CCustomDecoration’
   38 |     HyprlandAPI::addWindowDecoration(PHANDLE, PWINDOW, new CCustomDecoration(PWINDOW));
      |                                                                                     ^
In file included from main.cpp:8:
customDecoration.hpp:7:7: note:   because the following virtual functions are pure within ‘CCustomDecoration’:
    7 | class CCustomDecoration : public IHyprWindowDecoration {
      |       ^~~~~~~~~~~~~~~~~
In file included from /usr/local/include/hyprland/src/Window.hpp:6,
                 from main.cpp:5:
/usr/local/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:38:40: note:     ‘virtual SDecorationPositioningInfo IHyprWindowDecoration::getPositioningInfo()’
   38 |     virtual SDecorationPositioningInfo getPositioningInfo() = 0;
      |                                        ^~~~~~~~~~~~~~~~~~
/usr/local/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:40:40: note:     ‘virtual void IHyprWindowDecoration::onPositioningReply(const SDecorationPositioningReply&)’
   40 |     virtual void                       onPositioningReply(const SDecorationPositioningReply& reply) = 0;
      |                                        ^~~~~~~~~~~~~~~~~~
main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
main.cpp:73:68: warning: converting from ‘void (CCompositor::*)(CWindow*, wlr_surface*)’ to ‘void*’ [-Wpmf-conversions]
   73 |     g_pFocusHook = HyprlandAPI::createFunctionHook(PHANDLE, (void*)&CCompositor::focusWindow, (void*)&hkFocusWindow);
      |                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:85:143: warning: narrowing conversion of ‘((SConfigValue*)PBORDERCOLOR)->SConfigValue::intValue’ from ‘int64_t’ {aka ‘long int’} to ‘uint64_t’ {aka ‘long unsigned int’} [-Wnarrowing]
   85 | (PBORDERCOLOR->intValue)}, {"time", (uint64_t)10000}, {"color", CColor{PBORDERCOLOR->intValue}}, {"icon", ICON_HINT}});
      |                                                                        ~~~~~~~~~~~~~~^~~~~~~~

In file included from /usr/include/c++/13.2.1/memory:78,
                 from /usr/local/include/hyprland/src/plugins/HookSystem.hpp:5,
                 from /usr/local/include/hyprland/src/plugins/PluginAPI.hpp:24,
                 from globals.hpp:3,
                 from main.cpp:3:
/usr/include/c++/13.2.1/bits/unique_ptr.h: In instantiation of ‘constexpr std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = CHyprCustomLayout; _Args = {}; __detail::__unique_ptr_t<_Tp> = __detail::__unique_ptr_t<CHyprCustomLayout>]’:
main.cpp:64:58:   required from here
/usr/include/c++/13.2.1/bits/unique_ptr.h:1070:30: error: invalid new-expression of abstract class type ‘CHyprCustomLayout’
 1070 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from main.cpp:7:
customLayout.hpp:11:7: note:   because the following virtual functions are pure within ‘CHyprCustomLayout’:
   11 | class CHyprCustomLayout : public IHyprLayout {
      |       ^~~~~~~~~~~~~~~~~
In file included from /usr/local/include/hyprland/src/layout/DwindleLayout.hpp:3,
                 from /usr/local/include/hyprland/src/managers/LayoutManager.hpp:3,
                 from /usr/local/include/hyprland/src/Compositor.hpp:14,
                 from main.cpp:6:
/usr/local/include/hyprland/src/layout/IHyprLayout.hpp:46:18: note:     ‘virtual void IHyprLayout::onWindowCreatedTiling(CWindow*, eDirection)’
   46 |     virtual void onWindowCreatedTiling(CWindow*, eDirection direction = DIRECTION_DEFAULT) = 0;
      |                  ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/hyprland/src/layout/IHyprLayout.hpp:87:18: note:     ‘virtual void IHyprLayout::resizeActiveWindow(const Vector2D&, eRectCorner, CWindow*)’
   87 |     virtual void resizeActiveWindow(const Vector2D&, eRectCorner corner = CORNER_NONE, CWindow* pWindow = nullptr) = 0;
      |                  ^~~~~~~~~~~~~~~~~~
/usr/local/include/hyprland/src/layout/IHyprLayout.hpp:137:18: note:     ‘virtual void IHyprLayout::moveWindowTo(CWindow*, const std::string&)’
  137 |     virtual void moveWindowTo(CWindow*, const std::string& direction) = 0;
      |                  ^~~~~~~~~~~~
customDecoration.cpp: In constructor ‘CCustomDecoration::CCustomDecoration(CWindow*)’:
customDecoration.cpp:6:54: error: no matching function for call to ‘IHyprWindowDecoration::IHyprWindowDecoration()’
    6 | CCustomDecoration::CCustomDecoration(CWindow* pWindow) {
      |                                                      ^
In file included from customDecoration.hpp:5,
                 from customDecoration.cpp:1:
/usr/local/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:35:5: note: candidate: ‘IHyprWindowDecoration::IHyprWindowDecoration(CWindow*)’
   35 |     IHyprWindowDecoration(CWindow*);
      |     ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:35:5: note:   candidate expects 1 argument, 0 provided
/usr/local/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:33:7: note: candidate: ‘constexpr IHyprWindowDecoration::IHyprWindowDecoration(const IHyprWindowDecoration&)’
   33 | class IHyprWindowDecoration {
      |       ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:33:7: note:   candidate expects 1 argument, 0 provided
customDecoration.cpp: In member function ‘virtual void CCustomDecoration::draw(CMonitor*, float, const Vector2D&)’:
customDecoration.cpp:36:21: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowPos.Vector2D::x - (double)*(long int*)PBORDERSIZE)’ from ‘int’ to ‘double’ [-Wnarrowing]
   36 |     CBox fullBox = {(int)(m_vLastWindowPos.x - *PBORDERSIZE), (int)(m_vLastWindowPos.y - *PBORDERSIZE), (int)(m_vLastWindowSize.x + 2.0 * *PBORDERSIZE),
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
customDecoration.cpp:36:63: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowPos.Vector2D::y - (double)*(long int*)PBORDERSIZE)’ from ‘int’ to ‘double’ [-Wnarrowing]
   36 |     CBox fullBox = {(int)(m_vLastWindowPos.x - *PBORDERSIZE), (int)(m_vLastWindowPos.y - *PBORDERSIZE), (int)(m_vLastWindowSize.x + 2.0 * *PBORDERSIZE),
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
customDecoration.cpp:36:105: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowSize.Vector2D::x + 2.0e+0 * (double)*(long int*)PBORDERSIZE)’ from ‘int’ to ‘double’ [-Wnarrowing]
   36 | {(int)(m_vLastWindowPos.x - *PBORDERSIZE), (int)(m_vLastWindowPos.y - *PBORDERSIZE), (int)(m_vLastWindowSize.x + 2.0 * *PBORDERSIZE),
      |                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

customDecoration.cpp:37:21: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowSize.Vector2D::y + 2.0e+0 * (double)*(long int*)PBORDERSIZE)’ from ‘int’ to ‘double’ [-Wnarrowing]
   37 |                     (int)(m_vLastWindowSize.y + 2.0 * *PBORDERSIZE)};
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
customDecoration.cpp: In member function ‘virtual void CCustomDecoration::damageEntire()’:
customDecoration.cpp:71:16: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowPos.Vector2D::x - ((CCustomDecoration*)this)->CCustomDecoration::m_seExtents.SWindowDecorationExtents::topLeft.Vector2D::x)’ from ‘int’ to ‘double’ [-Wnarrowing]
   71 |     CBox dm = {(int)(m_vLastWindowPos.x - m_seExtents.topLeft.x), (int)(m_vLastWindowPos.y - m_seExtents.topLeft.y),
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
customDecoration.cpp:71:67: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowPos.Vector2D::y - ((CCustomDecoration*)this)->CCustomDecoration::m_seExtents.SWindowDecorationExtents::topLeft.Vector2D::y)’ from ‘int’ to ‘double’ [-Wnarrowing]
   71 |     CBox dm = {(int)(m_vLastWindowPos.x - m_seExtents.topLeft.x), (int)(m_vLastWindowPos.y - m_seExtents.topLeft.y),
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
customDecoration.cpp:72:16: warning: narrowing conversion of ‘(int)(((CCustomDecoration*)this)->CCustomDecoration::m_vLastWindowSize.Vector2D::x + ((CCustomDecoration*)this)->CCustomDecoration::m_seExtents.SWindowDecorationExtents::topLeft.Vector2D::x + ((CCustomDecoration*)this)->CCustomDecoration::m_seExtents.SWindowDecorationExtents::bottomRight.Vector2D::x)’ from ‘int’ to ‘double’ [-Wnarrowing]
   72 |                (int)(m_vLastWindowSize.x + m_seExtents.topLeft.x + m_seExtents.bottomRight.x), (int)m_seExtents.topLeft.y};
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
customDecoration.cpp:72:96: warning: narrowing conversion of ‘(int)((CCustomDecoration*)this)->CCustomDecoration::m_seExtents.SWindowDecorationExtents::topLeft.Vector2D::y’ from ‘int’ to ‘double’ [-Wnarrowing]
   72 |      (int)(m_vLastWindowSize.x + m_seExtents.topLeft.x + m_seExtents.bottomRight.x), (int)m_seExtents.topLeft.y};
      |                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~

make: *** [Makefile:6: all] Error 1

**Comment by vaxerski** [comment]
yeah I've long abandoned it, should be deleted tbh. We have hyprland-protocols for examples.

**Comment by Micovec** [comment]
> yeah I've long abandoned it, should be deleted tbh. We have hyprland-protocols for examples.

Could you also update the wiki? Because [Making your first plugin](http://wiki.hyprland.org/Plugins/Development/Getting-Started/#making-your-first-plugin) is referencing this example.

**Comment by vaxerski** [comment]
done
