### ISSUE TITLE
`cyclenext` and `cycleprev` don't focus floating windows

### ISSUE THREAD

**Issue by gekoke** [hyprwm/Hyprland#4330]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.33.1  ().
Tag: 

flags: (if any)
debug
```

</details>

### Bug or Regression?

Bug

### Description

When using `cyclenext` and `cycleprev` floating windows do not receive focus - althought the docs imply that they should.

### How to reproduce

Have at least 1 floating window open in a workspace. Have 0 or more tiled windows open in the same workspace. Use master layout. Execute `cyclenext`.

Expected: floating window receives focus

Actual: floating window never is focused

### Crash reports, logs, images, videos

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/13811790/hyprland.conf.txt)

**Comment by vaxerski** [comment]
you have:
```ini
binde = SUPER, J, layoutmsg, cyclenext
```

![image](https://github.com/hyprwm/Hyprland/assets/43317083/392daa36-ac2f-4f57-96ec-aea32579e1f0)

That one cycles only the master stack.

For floating, use `cyclenext`. For only floating, use `cyclenext floating`, e.g.:
```ini
binde = SUPER, X, cyclenext, floating
```

**Comment by gekoke** [comment]
> you have:
> 
> ```ini
> binde = SUPER, J, layoutmsg, cyclenext
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43317083/293748520-392daa36-ac2f-4f57-96ec-aea32579e1f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTY3MzUsIm5iZiI6MTcwNDIxNjQzNSwicGF0aCI6Ii80MzMxNzA4My8yOTM3NDg1MjAtMzkyZGFhMzYtYWMyZi00ZjU3LTk2ZWMtYWVhMzI1NzllMWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE3MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ODZlN2Q0ZDY1YzQ2NTY0NWIzMTllMWJhZDA0YmQxYTE1Njg3YmYyMDE1ZjBhNjAzNjY3YjliZTlhNDczNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o7ingXsecXsPjMpA5oz70SUoZUDQW0cjHrMUVFD-N84)
> 
> That one cycles only the master stack.
> 
> For including floating, use regular `cyclenext`. For only floating, use `cyclenext floating`, e.g.:
> 
> ```ini
> binde = SUPER, X, cyclenext, floating
> ```

Doh! Thanks a lot for your quick reply - your compositor is lovely :)
