### ISSUE TITLE
disable_splash_rendering not working?

### ISSUE THREAD

**Issue by flippette** [hyprwm/Hyprland#4338]
### Hyprland Version

<details> <summary><code>hyprctl version</code></summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Tue Jan 2 22:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)
```

</details>

<details> <summary><code>hyprctl systeminfo</code></summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Tue Jan 2 22:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)


System Information:
System name: Linux
Node name: orbital
Release: 6.7.0-rc8-1-mainline
Version: #1 SMP PREEMPT_DYNAMIC Sun, 31 Dec 2023 22:48:53 +0000


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The `disable_splash_rendering` option doesn't seem to do anything, even after a reboot.

![image](https://github.com/hyprwm/Hyprland/assets/43138244/2262a13d-1f65-4456-bfda-7a4bb076632d)

### How to reproduce

Start hyprland with `misc:disable_splash_rendering = true` set?

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13820934/hyprland.log)

**Comment by ilyss01** [comment]
Having same issue

**Comment by MightyPlaza** [comment]
I'm gonna guess that is hyprpaper
Hyprland (and that var) doesn't control it, it has it's own config

my guess is last update changed it from true to false by default

**Comment by ilyss01** [comment]
Yes, setting `splash = false` in hyprpaper config file disables splash rendering
