### ISSUE TITLE
Splash rendering ignores settings in 0.34.0

### ISSUE THREAD

**Issue by Vintodrimmer** [hyprwm/Hyprland#4341]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

After updating to 0.34.0 on Arch, splash message is always rendered on top of my wallpapers, despite
```
misc {
    disable_splash_rendering = true
}

```
Being in the settings.

### How to reproduce

1. Update to 0.34.0 on Arch Linux
2. Restart Hyprland

**Comment by vaxerski** [comment]
that's not hyprland, that's hyprpaper
