### ISSUE TITLE
misc:new_window_takes_over_fullscreen = 1 is not making new window takes over if fullscreen is maximize by fullscreen, 1

### ISSUE THREAD

**Issue by minsoehan** [hyprwm/Hyprland#4345]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).
Tag: v0.33.1

flags: (if any)


```

</details>

### Bug or Regression?

Bug

### Description

Actually I'm not sure it is a bug or not. But it is not as expected, I think. Dispatcher `fullscreen` has `1` option that is similar to `maximize` rule of window rules to my understanding. And `misc:new_window_takes_over_fullscreen = 1` means new window takes over fullscreen. But it only works if `fullscreen` is **not maximize** or `fullscreen, 1`. It shows only red border suggesting a new window opens under the current `fullscreen, 1` window.

### How to reproduce

Set `misc:new_window_takes_over_fullscreen = 1`. Open two windows and dispatch `fullsccreen, 1` and open third window. It will only show red border suggesting the third window opened under the current `fullscreen, 1` (maximize) window.

**Comment by gc-jackpocket** [comment]
Did you find a solution for this?
