### ISSUE TITLE
resize_on_border does not care about mouse constraints

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#4348]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 46997a764304366d772456c20b1c719960927aa7 dirty (renderer: fix auto scale detection with fractional).
Date: Sun Dec 31 07:54:24 2023
Tag: v0.33.1-119-g46997a76
```

</details>

### Bug or Regression?

Bug

### Description

Multi-monitor setup: a app/game constraining the mouse on the main monitor (fullscreen), resize_on_border=true in the config.

Sometimes when you click the mouse the game will lose focus. I traced through the source and figured out it is coming from processMouseDownNomal calling resizeWithBorder().

There's a bunch of extra logging in the log file, sorry. Was trying to figure out wtf the focus grab was coming from. Just search for "RESIZE WITH BORDER", that's emited from within processMouseDownNormal

### How to reproduce

resize_on_border+Multi monitor -> run game on main that constrains mouse. Have a window open on the second monitor. "move" the mouse until it would "normally" be on the edge of the second display, and then click+drag. After a few tries you'll eventually trigger a border resize.

### Crash reports, logs, images, videos

[hyprlandd-constrain.log](https://github.com/hyprwm/Hyprland/files/13825973/hyprlandd-constrain.log)

**Comment by vaxerski** [comment]
please check #4889
