### ISSUE TITLE
Scaling no longer allows any decimal values

### ISSUE THREAD

**Issue by Pheon-Dev** [hyprwm/Hyprland#4349]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Wed Jan 3 00:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.6.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

EDIT: Scaling only allows a factor of 0.5, 0.666667, 1 or greater no decimals
```sh
monitor=eDP-1,1366x768@59.99300,0x0,1
```

### How to reproduce

```sh
monitor=eDP-1,1366x768@59.99300,0x0,0.85
```

### Crash reports, logs, images, videos

```sh
Invalid scale passed to monitor eDP-1, failed to find a clean divisor. Suggested nearest scale: 1.000000
Hyprland may not work correctly
```

**Comment by fufexan** [comment]
You mean it doesn't allow any decimals lower than 1. There should be no reason to use that, as it messes up the rendering.

**Comment by Pheon-Dev** [comment]
I'm using an awful 1366x768 display for my x250 and could only use 1 or 0.666667.
But now I have changed the settings to 1600x900,0x0,1 and it now works alright but with the wrong display config

**Comment by thejch** [comment]
set debug:disable_scale_checks = true to use decimal

**Comment by Pheon-Dev** [comment]
I will look into it

**Comment by vaxerski** [comment]
0.5 should definitely work.

Either do what thejch said (not really recommended...)

Or make sure your scale divides the monitor's res without decimals.

E.g.: 1920x1080 with scale 2:
1920 / 2 = 960
1080 / 2 = 540
ok.

1920x1080 with scale 1.8:
1920/1.8 = 1066.66666667 .... not ok.

Everything seems alright.

**Comment by carschandler** [comment]
@vaxerski for context, I've been using a scale of 1.125 on my 24" 1440p monitor to bring it up to the scale of my 27" 1440p monitor (27 / 24 = 1.125), which has been working mostly fine in the past...

With this new error, I'm confused at your explanation in the previous comment because while dividing 2560 by 1.125 does not give a whole number, neither does 1.2, but when I use this value, the error goes away. Thanks!

**Comment by vaxerski** [comment]
Idk according to my calculator 2560/1.2 is not a whole number

**Comment by carschandler** [comment]
@vaxerski yeah that was why I was confused because using 1.2 made my error disappear. It seems that the error may go away when the scale number is changed from an invalid value to *any* new value regardless of whether it's actually valid.

**Comment by vaxerski** [comment]
hm. That might be a bug, but it still shouldn't accept an invalid value and drop you to an integer scale. meh
