### ISSUE TITLE
Window size is 1 by1

### ISSUE THREAD

**Issue by GlennMm** [hyprwm/Hyprland#435]
The bug is one that doesn't crash Hyprland, but feels like invalid behavior

Reproduction step:

1. download Bitnami lampstack binary
2. install the binary ( i installed using sway )
3. cd into the directory where lampstack was installed ( mine is in ~/lampstack )
4. run the manager binary using this command ./manager-linux-x64.run
5. open a new terminal and run hyprctl clients and i got the results in the screenshot below

as you can see the window size is 1x1.

![Screenshot_2022-07-27-09-33-25_24468](https://user-images.githubusercontent.com/37818661/181188806-c4d87413-282c-4eab-8cf3-0adf498c80fc.png)

**Comment by vaxerski** [comment]
two options:

1) you're using old hyprland
2) the window itself requests the dimensions 1x1

Hyprland will disallow any window to be created with dimensions below 5x5. Furthemore, native wayland windows cannot resize themselves, so it has to be XWayland.

**Comment by GlennMm** [comment]
owky thank i have updated hyprland, now the window is no longer opening, so let me check on the xwayland side and whats happening there.

**Comment by vaxerski** [comment]
My recommendation is to set a window rule for the window. Hyprland will strongly reject tiny xwayland windows, as most of them are windows that shouldnt be visible.
