### ISSUE TITLE
Firefox has a broken ui with gaps on top and left side since update last week

### ISSUE THREAD

**Issue by alemNative** [hyprwm/Hyprland#4350]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Tag: v0.31.0
```

</details>

### Bug or Regression?

Bug

### Description

since i update last week firefox has a broken ui. 
![swappy-20240104_100723](https://github.com/hyprwm/Hyprland/assets/68378664/6f7e5ccc-04a9-4651-b25a-da8552fde2c8)

Also the menu are so small that they are unusable. its also a problem that you on website you can't click on a button. you must klick a little bit under the button and right (so oposite of the gap from the window)

### How to reproduce

hard to say. i just update everything on archlinux with hyperland and firefox does not works propellly.

**Comment by fufexan** [comment]
This was fixed in 0.34. Please update. If you're on nvidia, you no longer need to be on `hyprland-nvidia-git`, as the normal git/release packages work on nvidia now.

**Comment by alemNative** [comment]
you're the man!!

**Comment by vaxerski** [comment]
@fufexan this was fixed in 0.31.2 or .3 iirc lol

**Comment by gobraves** [comment]
I have installed firefox 0.35.0, but firefox still has issue.
I also try to install the lastest hyprland and the git version is f085ed4454fc0c9045b324c32f9ca34cd4c28808, and the firefox also has the issue

**Comment by vaxerski** [comment]
can't repro, likely horribly out of date hyprland install.

**Comment by cluac7** [comment]
I'm not really worried about this anymore since it only occurs on my PC and not on my laptop and only or Floorp, not on Firefox (as it did before) but just to answer you I'm on `hyprland-git 0.34.0.r98.1ed4f1cb-1`

**Comment by cluac7** [comment]
Hmm that is weird that floorp is on a firefox version from 7 months ago but nah `MOZ_ENABLE_WAYLAND=1 floorp` or `MOZ_ENABLE_WAYLAND=1 org.ablaze.floorp` (flatpak version) both didn't work.

**Comment by TheLastTeapot** [comment]
Hi, this is still an issue for me with Hyprland version 0.35. My system and firefox are both up to date as well.

**Comment by vaxerski** [comment]
I use firefox daily and this is not an issue.

**Comment by TheLastTeapot** [comment]
![20240216_20h13m02s_grim](https://github.com/hyprwm/Hyprland/assets/82473273/db3209cb-a1f5-4c9a-a7e4-8eb0c157ac16)

**Comment by TheLastTeapot** [comment]
Happens with and without nvidia, by the way, so it's not that

**Comment by vaxerski** [comment]
lies and deceit. `hyprctl version`?

Plus, is firefox in xwayland? make sure it's in wayland native.

Other than that, can't repro. Have you tried disabling deco? customize toolbar -> menu bar

**Comment by cluac7** [comment]
> I use firefox daily and this is not an issue.

Yeah so do I and its fine on FF now, but I did used to have it on older hyprland versions and still do on Floorp. What I did notice though is that these broken menus that gets scaled weirdly and require you to to click a few centimeters to the right and down to actually interact on Floorp (and I recall now that I did as well on FF before) are also present on some gnome apps. I rarely use them (and assumed its a GTK issue) so I didn't bother bringing them up and tbh basically forgot about them but I see now it looks like a similar issue 
![brokenmenus](https://github.com/hyprwm/Hyprland/assets/77187291/6defc3e9-9e9c-4885-85a3-d0b8d8113291)

Also the output of `hyprctl version` for me is:
```
Hyprland, built from branch main at commit f69c5469d79f31f77f4662731ac6255e285febed dirty (readme: refactor and update a bit).
Tag: v0.29.0-21-gf69c5469

flags: (if any)
```

**Comment by vaxerski** [comment]
yeah. Exactly. Your version is half a year out of date.

**Comment by cluac7** [comment]
Oh I see...
```
pacman -Qi hyprland-git 
Name            : hyprland-git
Version         : 0.35.0.r38.fbf5ba87-1
Description     : A dynamic tiling Wayland compositor based on wlroots that doesn't
                  sacrifice on its looks.
Architecture    : x86_64
URL             : https://github.com/hyprwm/Hyprland
Licenses        : BSD
Groups          : None
Provides        : hyprland=0.35.0
Depends On      : cairo  gcc-libs  glib2  glibc  glslang  libdisplay-info  libdrm
                  libglvnd  libinput  libliftoff  libx11  libxcb  libxcomposite
                  libxfixes  libxkbcommon  libxrender  opengl-driver  pango  pixman
                  polkit  seatd  systemd-libs  tomlplusplus  wayland  wayland-protocols
                  xcb-proto  xcb-util  xcb-util-errors  xcb-util-keysyms
                  xcb-util-renderutil  xcb-util-wm  xorg-xinput  xorg-xwayland
                  libdisplay-info.so=1-64
Optional Deps   : None
Required By     : grimblast-git
Optional For    : None
Conflicts With  : hyprland
Replaces        : None
Installed Size  : 51.83 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Fri 16 Feb 2024 05:25:31 AM AEDT
Install Date    : Fri 16 Feb 2024 07:37:19 PM AEDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
```hyprctl version
Hyprland, built from branch main at commit f69c5469d79f31f77f4662731ac6255e285febed dirty (readme: refactor and update a bit).
Tag: v0.29.0-21-gf69c5469

flags: (if any)```

These aren't meant to be 6 subversions apart are they...
How did I f this up

**Comment by vaxerski** [comment]
that's what's called using DIY distros and then not knowing how to use DIY distros.

Likely you have duplicate binaries, one of them is old and unmanaged by your package manager. See `whereis Hyprland`

**Comment by TheLastTeapot** [comment]
Yeah, that was the problem for me too. Thanks!

**Comment by cluac7** [comment]
> that's what's called using DIY distros and then not knowing how to use DIY distros.
> 
> Likely you have duplicate binaries, one of them is old and unmanaged by your package manager. See `whereis Hyprland`

Ahhh you're right I completely forgot at one point I built a debug version because of other issues. Must've forgotten to completely purge it before going back to the AUR helper managed one.
