### ISSUE TITLE
blurred waybar + hyprpaper fails to update wallpaper behind waybar when no windows are present

### ISSUE THREAD

**Issue by shot-codes** [hyprwm/Hyprland#4352]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Tue Jan 2 22:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)


System Information:
System name: Linux
Node name: GLaDOS
Release: 6.6.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28a0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I have enabled blurring on waybar, tested with both blurls and layerrule. I am using hyprpaper to change wallpapers when I change workspace. When I navigate between two workspaces that each have windows, the wallpaper is correctly updated behind waybar -- when I naviagte to a workspace that has no windows the wallpaper is not updated behind waybar. If I open a window in the empty space the background behind waybar corrects itself

### How to reproduce

- preload multiple images in hyprpaper
- add layerrule/blurls for waybar
- bind workspace navigation to change wallpaper with `hyprctl hyprpaper wallpaper ""` as per documentation
- Use bind to switch between workspaces that have windows and no windows open

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/43202406/c25b78e5-d97a-4bdf-b850-d272804b12f8

**Comment by vaxerski** [comment]
kek

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13835169/patch.txt)
try

**Comment by nonetrix** [comment]
Could this be related?
![image](https://github.com/hyprwm/Hyprland/assets/45698918/d099c5fe-ab30-4bf0-8409-f35cceba13ab)

**Comment by vaxerski** [comment]
it is an optimization. Why not try the patch?

**Comment by nonetrix** [comment]
I might look into that later not sure how to apply it on NixOS but probably isn't too hard? Hopefully? Will it be upstreamed eventually?

**Comment by fufexan** [comment]
@nonetrix you can use this override:

```nix
wayland.windowManager.hyprland.package = pkgs.hyprland.overrideAttrs (old: {
  patches = (old.patches or []) ++ [
    (pkgs.fetchpatch {
      url = "https://github.com/hyprwm/Hyprland/files/13835169/patch.txt";
      hash = "";
    })
  ];
});
```

Change as appropriate for either the NixOS module/flake package.

The first time it will fail due to mismatched hashes. Copy the "got" hash that nix provides, and set the `hash` to that.

**Comment by nonetrix** [comment]
> @nonetrix you can use this override:
> 
> ```nix
> wayland.windowManager.hyprland.package = pkgs.hyprland.overrideAttrs (old: {
>   patches = (old.patches or []) ++ [
>     (pkgs.fetchpatch {
>       url = "https://github.com/hyprwm/Hyprland/files/13835169/patch.txt";
>       hash = "";
>     })
>   ];
> });
> ```
> 
> Change as appropriate for either the NixOS module/flake package.
> 
> The first time it will fail due to mismatched hashes. Copy the "got" hash that nix provides, and set the `hash` to that.

I just have a shell alias to get the hash from a URL, just a nice tip. I'll look into that tomorrow though

**Comment by POP303U** [comment]
I fixed this issue by putting this layerrule in my hyprland.conf:
```sh
layerrule = xray,waybar
```

Makes sense considering Waybar needs to be able to update itself on background change.

**Comment by vaxerski** [comment]
can you test today's git

**Comment by miniMinn24** [comment]
> I fixed this issue by putting this layerrule in my hyprland.conf:
> 
> ```shell
> layerrule = xray,waybar
> ```
> 
> Makes sense considering Waybar needs to be able to update itself on background change.

I've been looking for this solution for a long time, thanks TT

**Comment by izmyname** [comment]
Can't repro, but I use a static symlink to wallpaper in my hyprpaper.conf and change a wallpaper by ln -sf ~/picture .wallpaper, then reload hyprapper with a keybind.

**Comment by shot-codes** [comment]
This has been fixed for me
