### ISSUE TITLE
Custom splash text

### ISSUE THREAD

**Issue by CaptainJack2491** [hyprwm/Hyprland#4354]
### Description

It would be really nice if we can set up a list of our own custom splash text, maybe in the config file or a specific location? It is currently possible to change them but not without recompiling every time a change happens.

**Comment by vaxerski** [comment]
already rejected on the discord like minutes after it was first added

**Comment by Zelzahn** [comment]
What's the reason for this rejection?

**Comment by vaxerski** [comment]
opinionated development practices

**Comment by 0x796935** [comment]
Change them in /usr/include/hyprland/src/helpers/Splashes.hpp, compile it and DIY

edit: dunno if you have to compile it again, im not a developer

**Comment by coderonline** [comment]
I am interested in what was discussed more than two years ago on Discord about this. If the answer is: A splash screen is not a wallpaper overlay, it would be interesting to document it, if the solution was to add such a feature to `hyprpaper` and leave splash messages be just that.

**Comment by ItsOhen** [comment]
Weird necro. But i bet it came down to it being super easy to do with plugins instead, and that way not having to be maintained by someone who don't want it.

https://github.com/ItsOhen/splash_thing

for example.

**Comment by coderonline** [comment]
Okay, it works really well and encourages playing around with plugins. Thanks!

I am also glad that this changes the tone of this old bug, making it more helpful. For some weird reason, it has a high priority on at least one search engine.
