### ISSUE TITLE
[render/allocator/gbm.c:208] gbm_create_device failed

### ISSUE THREAD

**Issue by Motchi0731** [hyprwm/Hyprland#4355]
I just installed hyprland in Debian 12 using 6.6.9-x64v3-xanmod1 kernel. 
[hyprlandCrashReport31957.txt](https://github.com/hyprwm/Hyprland/files/13834199/hyprlandCrashReport31957.txt)

**Comment by vaxerski** [comment]
not a hyprland issue. Most likely way too out of date deps. Debian 12 is old.
