### ISSUE TITLE
Cannot match Thunderbird popup by initial class

### ISSUE THREAD

**Issue by raffaem** [hyprwm/Hyprland#4356]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
➜ hyprctl systeminfo
Hyprland, built from branch main at commit 4d6d662c67786c86647cf41b5b20d9c0b418dbb3 dirty (Makefile: force ln command to overwrite symlink (4347)).
Date: Thu Jan 4 10:20:17 2024
Tag: v0.34.0-20-g4d6d662c

flags: (if any)


System Information:
System name: Linux
Node name: ABRIDGED
Release: 6.6.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: ABRIDGED
01:00.0 VGA compatible controller [0300]: ABRIDGED


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When you click on a calendar event, Thunderbird produces the following popup:

```
Window 55f84c7764a0 -> CHECK-IN:
	mapped: 1
	hidden: 0
	at: 726,320
	size: 467,439
	workspace: 1 (1)
	floating: 1
	monitor: 0
	class: thunderbird
	title: CHECK-IN
	initialClass: thunderbird
	initialTitle: 
	pid: 47155
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```

This  works to match the popup:
```
windowrulev2 = float,class:^(thunderbird)$,initialTitle:^(\s*)$
```

But this doesn't work, although it should:
```
windowrulev2 = float,initialClass:^(thunderbird)$,initialTitle:^(\s*)$
```

### How to reproduce

Create an event in Thunderbird.

Go in the calendar and click on it.

Try to match the popup.

**Comment by romanstingler** [comment]
`windowrulev2 = float,  initialTitle: ^(?!thunderbird$).*`

**Comment by themaxw** [comment]
I have the same problem, so i tried @MightyPlaza's approach.
I tried to float all thundebird windows, except the main window which has an initialTitle of `Mozilla Thunderbird`.
However all thunderbird windows get floated, so initialTitle matching might also not work (or i might be missing something obvious).
My rules are 
```
windowrulev2 = float,class:^(thunderbird)$
windowrulev2 = tile,class:^(thunderbird)$,initialTitle:^Mozilla Thunderbird$
```

The relevant outpt of `hyprctl clients` is
```
Window 5558e560c4d0 -> Calendar - Mozilla Thunderbird:
	mapped: 1
	hidden: 0
	at: 20,-26
	size: 1879,1132
	workspace: -95 (special:mail)
	floating: 1
	monitor: 0
	class: thunderbird
	title: Calendar - Mozilla Thunderbird
	initialClass: thunderbird
	initialTitle: Mozilla Thunderbird
	pid: 17335
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```

**Comment by romanstingler** [comment]
How about a different approach. 
I guess you guys want the main thunderbird as tiled and all others as float. 
For me calendar entries and responses work like this, I don't use any other functionality so this is what I have testes do far.

In this case I have 
```
windowrulev2=float,class:thunderbird,title:^(?!Mozilla*)
```

**Comment by raffaem** [comment]
> How about a different approach. I guess you guys want the main thunderbird as tiled and all others as float. For me calendar entries and responses work like this, I don't use any other functionality so this is what I have testes do far thunderbird 115.
> 
> In this case I have
> 
> ```
> windowrulev2=float,class:thunderbird,title:^(?!Mozilla*)
> ```

Indeed that's exactly what I needed ... than you so much!

**Comment by themaxw** [comment]
This workaround works, but i still think the initialTitle not working (with thunderbird) is probably a bug.
