### ISSUE TITLE
Moving window to special workspace doesn't allow the cursor to interact with regular windows.

### ISSUE THREAD

**Issue by Oglo12** [hyprwm/Hyprland#4357]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When I upgraded Hyprland, I was noticing that moving windows to the special workspace wouldn't allow me to use windows that are on the regular workspace! Please fix this, it really breaks my (and probably many others') workflow!

### How to reproduce

Make sure you are using the version of Hyprland specified, and then just move a window to the special workspace, and try to interact with the window on the regular workspace:

My Case:

Opening up youtube.com in Brave, then opening the video in picture-in-picture (on special workspace), then trying to open a new Brave tab. (I cannot click the new tab button anymore)!

**Comment by dranull** [comment]
Dupe #4323?
