### ISSUE TITLE
Focus_on_activate seems broken

### ISSUE THREAD

**Issue by xusiai** [hyprwm/Hyprland#4360]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit aeeeace102c14ea0ab4df6840ee225e1b14ea970  ().
Date: 2024-01-04
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: naiad
Release: 6.6.8
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Dec 20 16:02:07 UTC 2023


GPU information: 
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240102.bd645e8"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Focus_on_activate hasn't been working with the League of Legends client for the past week. I don't have other applications which make use of this function. Is there a simple method to test the option without one?

### How to reproduce

1. Open League client
2. Queue for a match
3. Switch to a different workspace

**Comment by jabuxas** [comment]
if there's a fix to this, it would be quite nice. 
lots of wine games don't respect their rules at all, they appear on the current workspace instead of in their own workspace  (set by rules), they follow the workspace change as well if not fullscreened, sometimes you switch them to a workspace and they are initially invisible, but after fullscreening they appear out of the sudden, its weird.

in concerns to league, if it happens on sway as well then probably no fix will be made here

**Comment by dennkaii** [comment]
is the league of legends client working? as far as i know it is broken since a month or something

**Comment by xusiai** [comment]
> is the league of legends client working? as far as i know it is broken since a month or something

It is working. It was broken a while back but has been working for a few weeks.

**Comment by vaxerski** [comment]
is this stilla  thing?

**Comment by jabuxas** [comment]
league doesnt really work on linux anymore so i dont really know

**Comment by xusiai** [comment]
As mentioned above Riot blocked League on Linux so I no longer use this feature. As far as I'm concerned you can close this issue. Whether it works or not for other applications I do not know.

**Comment by vaxerski** [comment]
closing then fellow linux users
