### ISSUE TITLE
minimize and close buttun are shown.

### ISSUE THREAD

**Issue by 0ashkan0** [hyprwm/Hyprland#4362]
### Hyprland Version

Hyprland, built from branch main at commit cfd94c5b30719c1c512b0d0ef4366a0cb64793e0 dirty (input: Stop propagating axis events after valid binds (4059)).
Tag: v0.33.0-5-gcfd94c5b

### Bug or Regression?

Bug

### Description

why my hyprland is showing minimize and close buttuns in all apps?
![240105_22h22m30s_screenshot](https://github.com/hyprwm/Hyprland/assets/125137398/86acf0d8-6e71-410e-ae14-9f0a57f73c2e)

### How to reproduce

how?

**Comment by taylorcoffelt** [comment]
@0ashkan0 Hyprland doesn't handle drawing window decorations (without a plugin), that looks like you have a setting in firefox affecting those.
Do you have the 'Title Bar' setting turned on under Menu -> More Tools -> Customize Toolbar? 

> showing minimize and close buttuns in all apps?

Do you have another example of an application showing window controls other than firefox?

**Comment by vaxerski** [comment]
firefox setting
