### ISSUE TITLE
Visible scaling regression after 0.34.0, especially with GTK 4.0 apps

### ISSUE THREAD

**Issue by dmxk062** [hyprwm/Hyprland#4365]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

Fonts, widgets and images in GTK 4.0 applications are no longer scaled correctly. This leads to blurry and pixelated icons and text. This issue persists even if a scale that fits the monitor size is chosen. This used to work perfectly in 0.33. Integer scales still work as expected.
Screen size: 2880x1800  
Tested scales: 
- 1.5
- 1.75
- 1.8

### How to reproduce

Use any non integer scale and open a GTK 4.0 application.

### Crash reports, logs, images, videos

![2024_01 06_13:37:52_sc](https://github.com/hyprwm/Hyprland/assets/138803455/27acd1b1-9631-4971-bc31-a45b1957e655)
![2024_01 06_13:38:26_sc](https://github.com/hyprwm/Hyprland/assets/138803455/bb352b30-853e-4a29-8cd4-42331c78928a)
![2024_01 06_13:45:17_sc](https://github.com/hyprwm/Hyprland/assets/138803455/c8c2e0de-8678-41e9-8a77-be9a63335ea0)

**Comment by vaxerski** [comment]
it's fixed in git
