### ISSUE TITLE
Tap-to-click doesn't work on trackpoints

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/Hyprland#4369]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 5f8e4068e51480791dbccbe48e86910e9b3cc881 dirty (groupbar: Middle click on groupbar to close tab (4297)).
Date: Sat Dec 30 00:38:12 2023
Tag: v0.33.1-114-g5f8e4068

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Enabling `tap-to-click` doesn't seem to work for [trackpoint devices](https://wayland.freedesktop.org/libinput/doc/1.12.1/trackpoints.html).

### How to reproduce

**Approach 1:**

Enabling tap-to-click globally for all input devices:
```
input {
  touchpad {
    tap-to-click = true
  }
}
```

and tapping on a trackpoint, nothing will happen.

**Approach 2:**

Setting a device specific configuration for the trackpoint, where tap-to-click is enabled.
```
device:tpps/2-elan-trackpoint {
  enabled = true
  tap-to-click = true
}
```

and tapping on a trackpoint, nothing will happen either.

**Comment by fufexan** [comment]
Can you enable that in sway or other compositor/WM/DE? Afaik the newer trackpoints don't support tap to click anymore.

**Comment by ItsDrike** [comment]
> Afaik the newer trackpoints don't support tap to click anymore.

Oh, I thought that was purely a software option, not a hardware one. If trackpoints do indeed need hardware support to enable tap-to-click then yeah, this is not a bug.

However if it would be possible to handle in software, I'd love to see that option. I'm not sure how hyprland is handling such input devices though, perhaps i should forward this issue to libinput?

**Comment by fufexan** [comment]
> However if it would be possible to handle in software, I'd love to see that option.

Based on [this post](https://www.reddit.com/r/thinkpad/comments/66ltor/trackpoint_tapping_not_working_does_it_still) it looks like it is already handled in libinput, but if the hardware lacks support, there's nothing libinput can do.

**Comment by ItsDrike** [comment]
I see, that's a real shame, it would be really nice to have the support for tapping, but alright, guess there's not much that can be done here. Thanks for the help!
