### ISSUE TITLE
Unable to exclusively use one GPU in multi-gpu setup

### ISSUE THREAD

**Issue by jess-sol** [hyprwm/Hyprland#4370]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  ().
Date: 2024-01-01
Tag:

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

I'm unable to get Hyprland to exclusively use one of two GPUs in my system. I have an AMD GPU (`pci_0000_09_00_0`), and an nvidia GPU (`pci_0000_42_00_0`). After starting Hyprland, I'm unable to detach the nvidia GPU from its nvidia drivers, to pass into a VM. I must detach before starting Hyprland. If I reattach the GPU while Hyprland is running, and leave it for a while; it'll start failing to detach again, too.

I have `env=WLR_DRM_DEVICES,/dev/dri/card0` in my config, it has no effect; `card0` is the AMD GPU.

### How to reproduce

```bash
### Validate detaching GPU works without Hyprland running
sudo lspci -s 42:00 -vvv | grep driver
# Shows nvidia drivers

sudo virsh nodedev-detach --device pci_0000_42_00_0
sudo lspci -s 42:00 -vvv | grep driver
# Shows vfio drivers

sudo virsh nodedev-reattach --device pci_0000_42_00_0
sudo lspci -s 42:00 -vvv | grep driver
# Shows nvidia drivers

### Show issue with Hyprland using GPU when told not to via WLR_DRM_DEVICES

# Start Hyprland
Hyprland

sudo lspci -s 42:00 -vvv | grep driver
# Shows nvidia drivers

sudo virsh nodedev-detach --device pci_0000_42_00_0
# Hangs indefinitely
# Ctrl-C

sudo lspci -s 42:00 -vvv | grep driver
# Still shows nvidia drivers, after attempting to detach

pkill Hyprland
sudo lspci -s 42:00 -vvv | grep driver
# Shows vfio-pci now that detaching was successful after killing Hyprland

sudo virsh nodedev-reattach --device pci_0000_42_00_0
sudo lspci -s 42:00 -vvv | grep driver
# Shows nvidia drivers again
```

**Comment by izmyname** [comment]
Still a thing?

**Comment by vaxerski** [comment]
can be closed cuz wlroots was dropped
