### ISSUE TITLE
Ability to set the splitratio to an absolute value using hyprctl

### ISSUE THREAD

**Issue by LateNightIceCream** [hyprwm/Hyprland#4376]
### Description

The dispatcher `splitratio` currently adds or subtracts from the current split ratio.

For example:
`hyprctl dispatch splitratio 0.5` adds `0.5` to the current window split ratio.

Instead, I would like to be able to set this ratio to a specific absolute value.

I am aware of the `default_split_ratio` configuration option. But this only applies to newly opened windows and I would like to act on already existing windows.

My proposal:
Perhaps you could add an optional argument to the `splitratio` dispatcher to clarify that it should be set to an absolute ratio. Or alternatively a `hyprctl` command which returns the current split ratio. Then it would be possible to solve this with a script.

**Comment by bvr-yr** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/130279855/78a8b568-7f0e-4130-89ae-772e3bf21a9e)
![image](https://github.com/hyprwm/Hyprland/assets/130279855/24d4e5fb-2541-480e-985f-ef421d8cb92e)

**Comment by LateNightIceCream** [comment]
oops, cant believe I missed that.. thank you <3
