### ISSUE TITLE
per window shaders like picom

### ISSUE THREAD

**Issue by quantenzitrone** [hyprwm/Hyprland#4392]
### Description

I'd like to have window shaders similar to picoms `window-shader-fg-rule`.

What i want to archive is color based transparency to turn the background color of my windows transparent without affecting visibility.
https://github.com/ikz87/picom-shaders/wiki/Shader-gallery#color-based-transparency

**Comment by vaxerski** [comment]
I dont see a point. Easily done with a plugin, anyways

**Comment by alexhulbert** [comment]
@quantenzitrone I forked the hypr-darkwindow plugin [here](https://github.com/alexhulbert/HyprChroma) and made it do chromakey transparency. You can find the installation instructions [here](https://github.com/alexhulbert/SeaGlass?tab=readme-ov-file#background-transparency)
