### ISSUE TITLE
why no work bro a havent hacked your pc to get live feeds yet

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [hyprwm/Hyprland#4394]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

How do I remove this message on my desktop? 

### How to reproduce

.

### Crash reports, logs, images, videos

.

**Comment by tchofy** [comment]
[misc:disable_splash_rendering](http://wiki.hyprland.org/Configuring/Variables/#misc)

**Comment by IgnIVertiKalCaD** [comment]
thx

**Comment by fufexan** [comment]
See the pinned issue.

**Comment by IgnIVertiKalCaD** [comment]
It working. THX

https://github.com/hyprwm/Hyprland/issues/4338
