### ISSUE TITLE
Special workspaces occasionally appear on screen after wakeup/dpms wakeup

### ISSUE THREAD

**Issue by diniamo** [hyprwm/Hyprland#4398]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d7d333d162da2d3fc852b2c7a3faa2709440cefa dirty (opengl: apply box rot to projections).
Date: Sun Jan 7 18:51:08 2024
Tag: v0.34.0-31-gd7d333d1

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

As I said in the title, special workspaces will occasionally appear on my desktop, after the mentioned events. They are stacked on top of each other, but this seems to be only visual, because I can't click on them, and they don't go away until I toggle them twice (when I toggle one, it disappears, and comes back again, becoming interactive).

I have 2 monitors, and they appear on my primary monitor, if that matters.

### How to reproduce

Not consistent
1. `hyprctl dispatch dpms off` or `systemctl suspend` (unless you don't use systemd)
2. Turn the screen on again, or wake the computer up
3. Should see the special workspaces

**Comment by diniamo** [comment]
Just reproduced this on latest
<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 252aaaecfa3b57eb07822177a8bf3b609aff7115 dirty (input: add special_fallthrough).
Date: Tue Jan 9 13:17:55 2024
Tag: v0.34.0-35-g252aaaec

flags: (if any)
```

</details>

**Comment by goggi** [comment]
I am having the same issue. 
I have 2 monitors, and if I turn off one of the monitor and turn it back on, then the special workspace is activated, some times all of the speical workspaces are activated and I have to toggle all them to take them down. And for me I'm not able to focus on the special workspaces that are toggled after the monitor is turned on. I have to toggle them off and on to make them foucs again. 

System/Version info: 
```
Hyprland, built from branch  at commit c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a  ().
Date: 2024-01-17
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: gza
Release: 6.6.9-xanmod1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
24:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])
2f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240115.c3e128f"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

**Comment by dcaixinha** [comment]
I'm also seeing this running `hyprland v.0.35.0`, without any plugins.

**Comment by diniamo** [comment]
I haven't had this happen in ages, closing. I can reopen it if someone else has.
