### ISSUE TITLE
Fullscreen windows don't cover all the screen on certain scaling settings

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#4403]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

In the image you can see the issue, hypr-chan is visible at the bottom of the fullscreen window. This happens when scaling is set to 1.333333 or 1.6, but does not happen at 1, 1.25, 1.666667 or 2

### How to reproduce

in hyprland.conf:
`monitor=eDP-2,2560x1440@240,0x0,1.333333`

### Crash reports, logs, images, videos

![IMG_20240110_040702_001](https://github.com/hyprwm/Hyprland/assets/5684325/f6b16113-c87a-491a-a916-d2c660c9c81a)

**Comment by vaxerski** [comment]
dupe #3511
