### ISSUE TITLE
Freezes in mpv's OSC and excessive GPU load

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/Hyprland#4408]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit b240704bee1d04eacc27654ea875cf6f15033c7c dirty (renderer: allow rendering multiple fullscreen windows in third fs pass).
Date: Tue Jan 9 22:42:07 2024
Tag: v0.34.0-37-gb240704b

flags: (if any)


System Information:
System name: Linux
Node name: localhost
Release: 6.7.0-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 09 Jan 2024 21:19:29 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

https://github.com/hyprwm/Hyprland/commit/71166ef40b5f7640fcddb1951d84f0f086e198d2 causes excessive load on the graphics card when the terminal emulator is running, as well as serious freezes in the mpv's OSC. Reverting this commit solves all issues.

### How to reproduce

1. Open terminal emulator (in my case, it was Alacritty) and look at the GPU load (for example, via nvtop).
2. Try interacting with the mpv's OSC.

**Comment by dranull** [comment]
If you run alacritty with `WAYLAND_DEBUG=1 alacritty --print-events` you can see that is receives these events repeatedly, which probably leads to its constant memory allocation and high CPU usage:
<details> <summary>Log (just one block, but the same is repeating)</summary>

```
winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7728, tv_nsec: 717311177 }, requested_resume: None })
winit event: WindowEvent { window_id: WindowId(WindowId(94553792490304)), event: RedrawRequested }
Padding: 4 x 4
Width: 468, Height: 1030
winit event: AboutToWait
winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7728, tv_nsec: 721951064 }, requested_resume: None })
winit event: WindowEvent { window_id: WindowId(WindowId(94553792490304)), event: ScaleFactorChanged { scale_factor: 1.0, inner_size_writer: InnerSizeWriter { new_inner_size: (Weak) } } }
winit event: WindowEvent { window_id: WindowId(WindowId(94553792490304)), event: Resized(PhysicalSize { width: 468, height: 1030 }) }
winit event: AboutToWait
Font size changed to 15.0 px
Cell size: 9 x 22

```

</details>

**Comment by monkhaze** [comment]
I'm having the same issue with mpv.

Reverting to the commit before https://github.com/hyprwm/Hyprland/commit/71166ef40b5f7640fcddb1951d84f0f086e198d2 also fixes the issue for me.

This is what the issue actually looks like. OSC is almost completely frozen during playback. When the video is paused it works but is very laggy.

https://github.com/hyprwm/Hyprland/assets/6921039/7a8ee8c2-9e26-482c-b206-ade2507c4a13
