### ISSUE TITLE
Prevent cursor from warping when changing workspaces

### ISSUE THREAD

**Issue by rosshadden** [hyprwm/Hyprland#4409]
### Description

The `workspace_center_on` option either warps the cursor to the center of a workspace, or to the center of a window on the workspace. Is there a way to prevent the cursor from warping at all? If not, is this feasible to add, perhaps with setting the above to a value of `2`?

**Comment by vaxerski** [comment]
`no_cursor_warps`?

**Comment by rosshadden** [comment]
Ah, I missed that, sorry!
