### ISSUE TITLE
Drop Shadows not rendered correctly if blur is off and inner gaps are small enough

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#441]
This pictures are showing the cropped shadows.
It seems not to happen with blur enabled. Also it doesn't happen if the inner gaps are bigger. I hope the settings seen in the right window of the pictures are enough to reproduce.

![20220728_15h31m31s_grim](https://user-images.githubusercontent.com/10100765/181520328-85b17ea8-ed5f-4eab-a5ac-9d9a2d9b60f9.png)
![20220728_15h31m51s_grim](https://user-images.githubusercontent.com/10100765/181520365-71d63bb7-9869-4211-b4a9-af2c20793708.png)

**Comment by vaxerski** [comment]
cannot reproduce. Are you maybe on legacy renderer?

**Comment by vaxerski** [comment]
if you dont know, then you aren't running it. Weird.

**Comment by vaxerski** [comment]
can you pass me your full config?

**Comment by Dickby** [comment]
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################

monitor=,1366x768@60,0x0,1
exec-once=wbg ~/wallpapers/orblue.jpg

input {
    kb_layout=de
    kb_variant=nodeadkeys
    kb_model=
    kb_options=ctrl:nocaps
    kb_rules=
    repeat_rate=39
    repeat_delay=280
    follow_mouse=1
}

general {
    layout="master"
    max_fps=60 # deprecated, unused
    sensitivity=1.0
    main_mod=SUPER
    gaps_in=3
    gaps_out=6
    border_size=0
    # col.active_border=0x33ff0000
    # col.inactive_border=0x66333333
    damage_tracking=full # leave it on full unless you hate your GPU and want to make it suffer
}

decoration {
    rounding=10
    multisample_edges=2
    blur=0
    blur_size=1 # minimum 1
    blur_passes=1 # minimum 1, more passes = more resource intensive.
    blur_ignore_opacity=0
    active_opacity=1.0
    inactive_opacity=1.0
    fullscreen_opacity=0.0
    drop_shadow=1
    shadow_range=10
    shadow_render_power=3
    shadow_ignore_window=1
    shadow_offset=5 5
    # col.shadow=0xc0000050
    col.shadow=0xc0ffffff
    # col.shadow_inactive=0xd0000000

    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,6,default
}

gestures {
    workspace_swipe=1
}

misc {
    disable_hyprland_logo=1
}

dwindle {
    pseudotile=1 # enable pseudotiling on dwindle
}

# example window rules
# for windows named/classed as abc and xyz
#windowrule=move 69 420,abc
#windowrule=size 420 69,abc
#windowrule=tile,xyz
windowrule=float,kitty
windowrule=size 1366 380,kitty
windowrule=move 0 0,kitty
#windowrule=pseudo,abc
#windowrule=monitor 0,xyz
windowrule=animation slide bottom,wofi
windowrule=animation slide top,kitty
windowrule=animation slide top,Guake
# windowrule=animation fade 0,Guake
windowrule=float,Guake
windowrule=tile,chess
windowrule=size 1366 380,Guake
windowrule=move 0 0,Guake

# example binds
bind=SUPER+SHIFT,Q,exit,
bind=SUPER,T,exec,tdrop -ma -y 0 -h 50% kitty
bind=SUPER,C,killactive,
bind=SUPER,E,exec,dolphin
bind=SUPER,V,togglefloating,
bind=SUPER,O,exec,wofi -n -G --show run -o DP-3
bind=SUPER,P,pseudo,
bind=SUPER,f,fullscreen
bind=SUPER,g,exec,guake

bind=SUPER+SHIFT,l,movewindow,r
bind=SUPER+SHIFT,k,movewindow,u
bind=SUPER+SHIFT,h,movewindow,l
bind=SUPER+SHIFT,j,movewindow,d
bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r
bind=SUPER,j,movefocus,d
bind=SUPER,k,movefocus,u

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspace,1
bind=ALT,2,movetoworkspace,2
bind=ALT,3,movetoworkspace,3
bind=ALT,4,movetoworkspace,4
bind=ALT,5,movetoworkspace,5
bind=ALT,6,movetoworkspace,6
bind=ALT,7,movetoworkspace,7
bind=ALT,8,movetoworkspace,8
bind=ALT,9,movetoworkspace,9
bind=ALT,0,movetoworkspace,10

**Comment by vaxerski** [comment]
whoa, attach it please don't paste it

**Comment by Dickby** [comment]
After some testing i think the damage tracking doesn't take the shadow-offset into account!?

**Comment by vaxerski** [comment]
it does

**Comment by Dickby** [comment]
I don't know if that information helps you, but if i enable damage_blink, it works just fine and the damage regions are perfect.

**Comment by vaxerski** [comment]
please check with d72f1cc644b30b1517d5a1725fb9014cffde5642

**Comment by Dickby** [comment]
Works perfectly so far.
Thanks again!
