### ISSUE TITLE
Bug with FL_studio | wine. Drag&drop doesn't work on version 0.34

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [hyprwm/Hyprland#4410]
### Hyprland Version

<==| hyprctl version |==>

Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

### Bug or Regression?

Bug

### Description

I've tried running through vanilla **wine** and through **bottles**. None of these helped to fix the error seen in the video. **I can't grab the sample and drag it to the timeline**. In **0.33** everything worked, but in **0.34**.... The hyprland config used was the same as on 0.33

### How to reproduce

Start fl_studio and try to move the sample to the audio track window

### Crash reports, logs, images, videos

https://youtu.be/3r6ojHOEFh0

**Comment by vaxerski** [comment]
`git bisect` please

**Comment by IgnIVertiKalCaD** [comment]
> `git bisect` please
I don't understand you.

**Comment by MightyPlaza** [comment]
> > `git bisect` please
> 
> I don't understand you.

build from source and use git bisect to find the 1st commit where it doesn't work (https://git-scm.com/docs/git-bisect)

**Comment by IgnIVertiKalCaD** [comment]
> > > `git bisect` please
> > 
> > 
> > I don't understand you.
> 
> build from source and use git bisect to find the 1st commit where it doesn't work (https://git-scm.com/docs/git-bisect)

I get it now. I'll do it this weekend

**Comment by FlashOnFire** [comment]
I had a similar issue and managed to get it to work with this simple windowrule :

```
windowrulev2 = nofocus, class:^(fl64.exe)$, title:^()$
```

**Comment by IgnIVertiKalCaD** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/54883747/9927d76e-ca55-4259-b429-e7eab394fd77)


Tried your method and it didn't work. 
You can also verify this problem by working in webstorm, rustrover, jetbrains projects.
I just don't have them drag and fly away from the cursor to the corner of the screen (on hyprland v0.33), and on v0.34 there is no effect of moving the tab at all and it just flies away.

![image](https://github.com/hyprwm/Hyprland/assets/54883747/19f90b69-e14f-42b0-b908-2391d9d52819)

So this problem is most likely due to hyprland's implementation of XWayland or my monitors settings.

**Comment by FlashOnFire** [comment]
It's fl64.exe in lowercase, it's not the name of the .exe file but the class of the window (you can see it with hyprctl clients)
When drag&dropping, fl studio creates another window with no title which is dragged with your mouse. but by default, the newly created window takes focus and the main fl studio window loses it which causes the issue (fl just assumes you focused another window)

The window rule prevents the new window from taking focus from the main one.

Also, could you explain the exact problem you have with jetbrains tools ? I use them regularly and don't have issues either

**Comment by IgnIVertiKalCaD** [comment]
I apologize for being silly with the config. I really checked **fl64.exe** and **FL64.exe** and had the same result - loss of focus. 
Now I made: 
`windowrulev2 = nofocus, class:^(fl64.exe)$, title:^()$`

And oh boy, it finally works as it should. I take the sample and drag it from the left side of the screen to the right side. 
Thank you very much.

The problem with webstorm persisted. Demonstration of the problem in the video. I can't drag and drop tabs as they immediately teleport to nowhere. The rule applied is as follows:
`windowrulev2 = nofocus, class:^(jetbrains-webstorm)$, title:^()$`

When I hover over a tab, I see ripples, as if the focus jumps and back to the original position again. This is the problem I don't know how to solve, even with the window rule you suggested.

Problem:
https://youtu.be/VMBc5hY6gRA

**Comment by tepri-g** [comment]
Does `windowrulev2=noinitialfocus,xwayland:1` solve this issue?

**Comment by IgnIVertiKalCaD** [comment]
Yes. Thank you very much. Now I don't have the problems that have been bugging me for so long. We can consider these problems closed and the solution is in this issue

windowrulev2 = nofocus, class:^(fl64.exe)$, title:^()$
windowrulev2 = noinitialfocus, xwayland:1

Thank you all so much!!!
