### ISSUE TITLE
`hyprctl dpms off` does not turns the screen off

### ISSUE THREAD

**Issue by the-fuckin-nobody** [hyprwm/Hyprland#4415]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit b240704bee1d04eacc27654ea875cf6f15033c7c dirty (renderer: allow rendering multiple fullscreen windows in third fs pass).
Date: Wed Jan 10 01:12:07 2024
Tag: v0.34.0-37-gb240704b

flags: (if any)
no xwayland


System Information:
System name: Linux
Node name: arch
Release: 6.6.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT1 [UHD Graphics] [8086:46a3] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Whent he `key_press_enables_dpms` feature is turned on in the config, the command `hyprctl dispatch dpms off` does not seem to turn the screen off for my laptop i.e the screen turns off and then automatically powers on.
On executing the command from the terminal, it is noticed that the command after execution, sends additional key-presses automatically(the enter key gets pressed ~ 10 times every time the command gets executed).
Also, after I set `key_press_enable_dpms` to false in the config, then the command works exactly as expected, and also the additional key-presses are not passed.

Screenshots for both the cases:
With the `key_press_enables_dpms` feaure turned on, additional (enter) key-presses are passed as can be seen in the terminal:
![Screenshot_2024-01-11-13-15-30](https://github.com/hyprwm/Hyprland/assets/97352165/7c90c225-b45e-4009-9ae2-5a122003b3f9)

Issue is not present if the feature is turned off:
![Screenshot_2024-01-11-13-15-51](https://github.com/hyprwm/Hyprland/assets/97352165/d723363e-f636-4560-947d-8967055fedd6)

### How to reproduce

+ Set the variable `key_press_enables_dpms` = `true` in the Hyprland config
+ Run `hyprctl dispatch dpms off` from terminal
+ Screens goes black, then lights up again, automatically
+ Additional keypresses of the `Return` key can be seen in the terminal

**Comment by kRHYME7** [comment]
Try
https://wiki.hyprland.org/Configuring/Dispatchers/
![image](https://github.com/hyprwm/Hyprland/assets/53417443/d7c4a896-c926-4e63-a6d6-0128925c7ee0)
![image](https://github.com/hyprwm/Hyprland/assets/53417443/fcf69425-7d6a-4e0e-9ea1-a8658be9fa0c)

**Comment by the-fuckin-nobody** [comment]
Damn! I did not see to that, thanks buddy !
