### ISSUE TITLE
vrr 120 Hz @ 144 Hz monitor not working

### ISSUE THREAD

**Issue by tecumses** [hyprwm/Hyprland#4416]
### Hyprland Version

Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

### Bug or Regression?

Bug

### Description

vrr ist not working at all when choosing 120 Hz on my 144 Hz monitor. The refresh rate stays fixed at 120 Hz.

### How to reproduce

Set monitor to 120 Hz

**Comment by vaxerski** [comment]
how are you verifying that?

**Comment by tecumses** [comment]
Yes, it is. And it‘s working fine with 144 Hz.
I can verify it with the internal fps counter on my monitor (acer xv272up).

**Comment by vaxerski** [comment]
then I am pretty sure it's a problem with either the driver or your monitor. Does sway work?

**Comment by tecumses** [comment]
ok, in sway it's working. Here is why:
wlr-randr outputs:
> 2560x1440 px, 120.066002 Hz (current)
> 2560x1440 px, 119.998001 Hz

hyprland config says:
> monitor = DP-2, 2560x1440@119.998001, 0x0, 1, vrr, 1, bitdepth, 10

sway vrr only works with 119.998001 Hz, not with 120.066002 Hz, but hyprland selects 120.066002 Hz, no matter which of the two is written in the config, so no vrr @ 120 Hz, as seen in wlr-randr aswell hyprctl monitors.
Is my config wrong?

**Comment by tecumses** [comment]
ok, I was able to fix it with
> monitor = DP-2, 2560x1440@119, 0x0, 1, vrr, 1, bitdepth, 10
