### ISSUE TITLE
pass all bindings to focused application

### ISSUE THREAD

**Issue by fabolous005** [hyprwm/Hyprland#4419]
### Description

when connecting to Virtual Machines i would like to pass various key combinations to the vm without interfering with the binds in my config.
Easiest solution for this would be to configure applications to which ALL combinations should be passed to and make exception rules.

eg.:
```
passthrough = virt-viewer
# idk if this is possibly without major changes
virt-viewer[e] = SUPER_SHIFT,Q

# maybe even just this
passthrough = virt-viewer, SUPER_SHIFT,Q

# or somehow extend the bind keyword 
```

Or maybe an inner circle of validity of keybinds, where applications can be flagged so all combinations would be inserted into it when its focused. And the bind keyword would get a new flag to describe binds of an inner circle that would make the exceptions.

Your opinions?

**Comment by MightyPlaza** [comment]
can't you just use a empty submap?

**Comment by vaxerski** [comment]
you can, support for shortcut inhibit was also added since
