### ISSUE TITLE
flatpak applications improper dpi

### ISSUE THREAD

**Issue by LaptopDev** [hyprwm/Hyprland#4424]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 3d89654254a3cc23a57e1bdcd39ad9f743bf98e2  (vector: New operator overloads and small fix in Vector2D. (3891)).
Tag: v0.32.3-37-g3d896542

flags: (if any)
debug

```

</details>
The dpi scaling does not properly work for flatpak applications when the monitor is scaled.

### Bug or Regression?

Bug

### Description

Flatpak font and ui elements display unsmooth, jagged and blurry.

### How to reproduce

my configuration of secondary monitor which the problem occurs on:
`monitor=DP-1,2560x1440@144,auto,1.3`

**Comment by vaxerski** [comment]
means they are using xwayland, which physically can't do fractional scaling. See the wiki https://wiki.hyprland.org/Configuring/XWayland/

on a side note, you're on a very outdated version.
