### ISSUE TITLE
[Mouse Click Bind] Meddle click for non-meddle button mouse

### ISSUE THREAD

**Issue by xz-dev** [hyprwm/Hyprland#4428]
### Description

I have a kensington orbit which only have 2 buttons which are right click and left click, I want to set right + left together for middle click like KDE or others. But I can't even I tried [submap](https://github.com/hyprwm/Hyprland/discussions/1703) and `xdotool`.
And I don't know why, `xdotool click 2` wont work at all, even I bind the command to normal keyboard like `bind = $mainMod, B, exec, xdotool click 2`

**Comment by fufexan** [comment]
https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs. See the example config section.

**Comment by xz-dev** [comment]
> https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs. See the example config section.

Thank you so much, it's working well. But do you know why `xdotool` command not work?
