### ISSUE TITLE
when on master layout windows don't get dinamically resized

### ISSUE THREAD

**Issue by Seme4eg** [hyprwm/Hyprland#4429]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Wed Jan 3 00:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When being in maximized window mode (2 windows on a workspace) and moving current workspace to another monitor, window on top of the stack gets wrong size and takes space even behind statusbar.

### How to reproduce

If you have 2 monitors than use master layout, open 2 tiled windows, maximize and then move that workspace to another monitor. Window will take up space even behind statusbar and will not respect gaps.
And on laptop monitor you should be able to reproduce same behavior by closing / opening status bar (eww in my case). When you close it maximized window won't resize unless you cycle windows or manually resize it. On statusbar open it won't resize again. (Tho same case works fine on dwindle layout)

**Comment by thejch** [comment]
same thing as #4298 ?

**Comment by Seme4eg** [comment]
Yes, might be related, since its also about windows messing up its size. Updated description of my issue.
