### ISSUE TITLE
Hyprland ignores device-specific keyboard layout

### ISSUE THREAD

**Issue by Occhioverde** [hyprwm/Hyprland#443]
Good morning.

Since my laptop's integrated keyboard has a different layout than the external one I sometimes attach via USB, I tried to set the `kb_layout` parameter inside a section named after what `hyperctl devices` suggested me:

```
device:AT Translated Set 2 keyboard { 
    kb_layout=it
}
```

However, this setting seem to be completely ignored by Hyprland, which loads only the layout specified inside the global `input` section.

I tried to replace the spaces in the keyboard's name with hyphens and underscores, but it seems that the correct layout is never actually loaded, so I'm writing here in search of some help.

Thank you in advance to anyone who can help me figure out what am I doing wrong to get this behavior.

**Comment by vaxerski** [comment]
output of `hyprctl devices` with the kb attached pls

**Comment by Occhioverde** [comment]
Yeah, sorry, I should have attached it to my first message:

```
mice:
	Mouse at cc8f7810:
		SynPS/2 Synaptics TouchPad


Keyboards:
	Keyboard at cc78fd40:
		Power Button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
	Keyboard at cc668a00:
		Video Bus
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
	Keyboard at cc933350:
		Power Button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
	Keyboard at cc973920:
		Sleep Button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
	Keyboard at cc9a3100:
		VGA Webcam: VGA Webcam
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
	Keyboard at cc9dda20:
		AT Translated Set 2 keyboard
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
	Keyboard at cca18610:
		Acer WMI hotkeys
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)


Tablets:
```

**Comment by vaxerski** [comment]
should-a be fixado in 4076a3b6d7930ea30799f180fec2f13e1819f3d7

**Comment by Occhioverde** [comment]
Yes, now it works perfectly! Thank you very much!
