### ISSUE TITLE
Hyprland crash if I unplug every monitors

### ISSUE THREAD

**Issue by lou-perret** [hyprwm/Hyprland#4430]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c4da4b026deefd58f532353b64e9f17130e760ca dirty (layershell: Fix greedy mouse grab from keyboard_interactive layer (4401)).
Date: Fri Jan 12 15:43:16 2024
Tag: v0.34.0-42-gc4da4b02

flags: (if any)


System Information:
System name: Linux
Node name: arch-5900X
Release: 6.6.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:41 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
13:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Hello ! 

I'm using a KVM switch to use two computers with the same monitors, keyboard and mouse.

Hyprland will sometime crash when I do that. I'm not sure, but I think it crashes only when I have an xwayland app opened (like Steam). I'll do some tests

### How to reproduce

- Start an xwayland app (EDIT: it seems to be related to Steam, I cannot manage to reproduce the crash with any other app. if Steam is opened, it crashes everytime)

- unplug every monitors

### Crash reports, logs, images, videos

[hyprlandCrashReport39750.txt](https://github.com/hyprwm/Hyprland/files/13927736/hyprlandCrashReport39750.txt)

**Comment by endeavour** [comment]
Possibly a duplicate of https://github.com/hyprwm/Hyprland/issues/5309

**Comment by vaxerski** [comment]
possibly just stale and fixed
