### ISSUE TITLE
I found a bug with the blur layer rules 

### ISSUE THREAD

**Issue by RedBlizard** [hyprwm/Hyprland#4431]
### Hyprland Version

Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

### Bug or Regression?

Bug

### Description

thunar is causing a blackscreen when left open ,and you use wlogout in combination with sddm  to logout this causes a blackscreen. when layerrule = blur,gtk-layer-shell # blurs wlogout  is used .

### How to reproduce

If thunar is not closed and if still open on a workspace , and you use wlogout to logout,  when sddm is used you get a blackscreen and you need to restart sddm the get to the greeter.
This cause of this , is this line blur layer rule : layerrule = blur,gtk-layer-shell # blurs wlogout 
Thunar als uses the gtk-layer-shell ! , with dolphin no issue but i think also same issue  with all the gtk- file managers.

**Comment by rudy-in** [comment]
Nvidia problem maybe

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by RedBlizard** [comment]
No this is solved @vaxerski
