### ISSUE TITLE
clang build fails: format file not found

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#4433]
### Hyprland Version

unrelaetd

### Bug or Regression?

Regression

### Description

The build with clang (and meson) fails for some reason. I cannot get it to work, so maybe somebody here knows what's wrong?

### How to reproduce

going off [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyprland-git#n100) add to the meson command: `CC=clang CXX=clang++ meson setup build ... -Dcpp_args=--stdlib=libstdc++ -Dc_args=-Wno-unused-command-line-argument"` (the guide on the wiki definitely doesn't make getting this to work sound as difficult as I find it to be. I had to had the c args as well since the build would fail still. I wonder why I'm facing these issues...)

This really should work, and it mostly does, but the moment it's trying to compile hyprpm, I'm seeing this error: `../hyprctl/main.cpp:15:10: fatal error: 'format' file not found`, which is funnily the error that this whole clang endeavor is supposed to get rid of...
I cannot get rid of this, nomatter what I try. Any idea what's wrong? I cannot find anything about this online

### Crash reports, logs, images, videos

```
FAILED: hyprctl/hyprctl.p/main.cpp.o
clang++ -Ihyprctl/hyprctl.p -Ihyprctl -I../hyprctl -flto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -DHAS_EXECINFO -std=c++2b -stdlib=libstdc++ -fPIE -MD -MQ hyprctl/hyprctl.p/main.cpp.o -MF hyprctl/hyprctl.p/main.cpp.o.d -o hyprctl/hyprctl.p/main.cpp.o -c ../hyprctl/main.cpp
../hyprctl/main.cpp:15:10: fatal error: 'format' file not found
#include <format>
         ^~~~~~~~
1 error generated
```

**Comment by fufexan** [comment]
What clang version do you have? IIRC only version >= 16 has the `<format>` header.

**Comment by UltraBlackLinux** [comment]
@fufexan I'm on version 16, that's the confusing part

**Comment by SakuraHaruko** [comment]
I have the same problem...

**Comment by SakuraHaruko** [comment]
#3263
