### ISSUE TITLE
Weird font rendering near the center of the terminal

### ISSUE THREAD

**Issue by MickaelCa** [hyprwm/Hyprland#4448]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
hyprctl version
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

The font rendering is weird near the center of the terminal (consistent across both foot and gnome-terminal)

For exemple, with ncmpcpp on foot (`foot version: 1.16.2-10-g242767d3 (Nov 27 2023, branch 'master') +pgo +ime +graphemes -assertions`) : 

![image](https://github.com/hyprwm/Hyprland/assets/71669881/62d96974-48e6-4933-9a41-368e72692af9)

When "In Flames" is centered in the list (bad, blurry) : 

![image](https://github.com/hyprwm/Hyprland/assets/71669881/48cbe05e-2a1c-48b8-a8ab-941f37930dc5)

When it's lower in the list (perfect) : 

![image](https://github.com/hyprwm/Hyprland/assets/71669881/89bc3368-98b4-4970-accb-485c86a7356d)

### How to reproduce

Upgrade from 0.30.0 to 0.34.0.

**Comment by vaxerski** [comment]
scaling?
if this is a regression, can you `git bisect` it?

**Comment by hyperpuncher** [comment]
I've got the same problem, it only appears on pseudo tiling in every app. Bisected it and got https://github.com/hyprwm/Hyprland/commit/55b4f84fea33adee3ec4b0a69c2bca6e7a1f5754.

**Comment by vaxerski** [comment]
IIRC this has been fixed in -git. Also doesn't answer my question wrt. scaling

**Comment by hyperpuncher** [comment]
Nope, not fixed in -git. No scaling.

**Comment by hyperpuncher** [comment]
Before
![before](https://github.com/hyprwm/Hyprland/assets/39203616/e8f243e4-0172-4030-ba61-f64f52ff51fd)
After https://github.com/hyprwm/Hyprland/pull/4698
![after](https://github.com/hyprwm/Hyprland/assets/39203616/f5443806-0ee8-42a5-bda9-4d4153a32cf9)

**Comment by vaxerski** [comment]
4698 is not a fix. it's a random code change that happens to improve this for you while breaking other things.

**Comment by vaxerski** [comment]
check pseudo with e7cdde84251b737a8bdc5aea742b6c824a84ce2b

**Comment by hyperpuncher** [comment]
I'm not at home right now, will test it in the evening, but it fixed other problem I had at work with incorrect rendering in Telegram.

**Comment by MickaelCa** [comment]
Hi, really sorry I'm a bit swamped, and didn't had the time to try to bisect, thanks a lot @hyperpuncher for trying on your side

No scaling for me too

**Comment by vaxerski** [comment]
@MickaelCa is this fixed

**Comment by MickaelCa** [comment]
Will check asap

**Comment by MickaelCa** [comment]
Short testing with -git shows no more scaling issue, but I've not been able to build [hy3](https://github.com/outfoxxed/hy3) with it so going back to v0.30.0 after

**Comment by vaxerski** [comment]
alr closing
