### ISSUE TITLE
Could disabled monitors be visible to `hyprctl monitors`, with the `enabled: no` status?

### ISSUE THREAD

**Issue by nwg-piotr** [hyprwm/Hyprland#4451]
### Description

In my software I try to ensure that equivalent features are available on both sway and Hyprland. Unfortunately, in nwg-displays, after disabling a monitor, I can no longer detect it again with `hyprctl monitors`. Use of `wlr-randr` helps partially: it detects disabled monitors as enabled, and with wrong coordinates. Also it works via DisplayPort only, but not via HDMI, at least on my setup.

Would it be possible to make `hyprctl monitors` report all monitors, with the `enabled: yes/no` value?

Related: https://github.com/nwg-piotr/nwg-displays/issues/42

**Comment by kRHYME7** [comment]
hyprctl monitors all will give output for all monitors. 

http://wiki.hyprland.org/Configuring/Using-hyprctl/#info

``` monitors - lists active outputs with their properties, 'monitors all' lists active and inactive outputs ```

**Comment by nwg-piotr** [comment]
> hyprctl monitors all will give output for all monitors.
> 
> http://wiki.hyprland.org/Configuring/Using-hyprctl/#info
> 
> `monitors - lists active outputs with their properties, 'monitors all' lists active and inactive outputs`

Thank you!

**Comment by nwg-piotr** [comment]
However: it does not indicate enabled/disabled status :(

**Comment by kRHYME7** [comment]
Sadly yes, Workaroundish is to compare both outputs.

**Comment by nwg-piotr** [comment]
Hmmm, good finding. I'll check if we can use this.

**Comment by nwg-piotr** [comment]
My biggest problem is that once disabled HDMI monitor refuses to turn back on until I exit & run Hyprland again. It's all right on DP displays. :/

**Comment by kRHYME7** [comment]
https://github.com/hyprwm/Hyprland/issues/2549

``` hyprctl reload ``` seems to work for them

**Comment by nwg-piotr** [comment]
It doesn't work, at least on my hardware. Turning them physically off and back on helps. Then I need to `hyprctl reload` to detect their size (initially I have 0x0 px).

**Comment by nwg-piotr** [comment]
Closing, as it's doable by comparing to `hyprctl monitors all`.
