### ISSUE TITLE
Using movecurrentworkspacetomonitor does not focus the moved workspace.

### ISSUE THREAD

**Issue by ApproachingApathy** [hyprwm/Hyprland#4459]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

I'm using the following to move my workspaces around my monitor.
```
bind = $mainMod ALT, period, movecurrentworkspacetomonitor, +1
bind = $mainMod ALT, comma, movecurrentworkspacetomonitor, -1
```
When I do so my cursor moves with the active workspace, as expected. However, my focus does not move to the new monitor. Therefore, subsequent calls to movecurrentworkspacetomonitor act on the original monitor.

For example suppose I had the following workspaces:
- M1: 
  - Workspace 1
- M2: 
  - Workspace 2 
- M3
  - Workspace 3 < Cursor, Focus
  - Workspace 4

After using the binding above to move Workspace 3: I have the following:
- M1: 
  - Workspace 1
- M2: 
  - Workspace 2
  - Workspace 3 < Cursor
- M3:
  - Workspace 4 < Focus

I would expect to have: 
- M1: 
  - Workspace 1
- M2: 
  - Workspace 2
  - Workspace 3 < Cursor, Focus
- M3:
  - Workspace 4
 
This mean that when I press the bind again, instead of the following:
- M1: 
  - Workspace 1
  - Workspace 3 < Cursor, Focus
- M2: 
  - Workspace 2
- M3:
  - Workspace 4
 
what happens instead is:
- M1: 
  - Workspace 1
- M2: 
  - Workspace 2
  - Workspace 3 < Cursor, Focus
  - Workspace 4
- M3:
  - Workspace 5 [NEW]

Workspace 4 moves in the background and is not even set to active. I can workaround this doing anything to set a window active in Workspace 3. However, I'd like to be able to make multiple moves in a row without having to add extra steps. Additionally, this is not consistent with how window movements work.

### How to reproduce

1. Create a bind for movecurrentworkspacetomonitor -1

2. Create a monitor setup like the following (M is monitor, W is workspace):
- M1:
  - W1
- M2:
  - W2
- M3:
  - W3
  - W4

3. Use the bind to move W3 to M2.
    - W4 will be focused instead of W3
5. Repeat the bind to move W3 to M1.
    - W4 will move instead of W3.
    - W3 will become focused.

**Comment by Scrumplex** [comment]
I have proposed a fix for this in #4660. Feel free to test
