### ISSUE TITLE
Frame rendering delayed in Xwayland apps when resizing

### ISSUE THREAD

**Issue by phonetic112** [hyprwm/Hyprland#4461]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 7904188de9ca631436484cde733ef871f518d962 dirty (input: allow focusSurface when locked if surfase is sessionLock).
Date: Sun Jan 7 08:04:32 2024
Tag: v0.34.0-27-g7904188d

flags: (if any)


System Information:
System name: Linux
Node name: artix
Release: 6.6.9-artix1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 03 Jan 2024 18:30:58 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

frame rendering is late when resizing Xwayland windows. It also makes it lag a lot

### How to reproduce

1. open Xwayland window
2. resize it outwards
3. see a gap between the window border and the actual rendered window as it resizes

### Crash reports, logs, images, videos

top window is lxappearance (xwayland)
bottom is nwg-look (wayland)

https://github.com/hyprwm/Hyprland/assets/73647246/07777d48-c7b4-41e1-8bd9-7d15aefa06e3

**Comment by quantenzitrone** [comment]
I'll add a comparison to sway.

Sway(fx):
- smooth resizing
- a bit of lag
https://github.com/hyprwm/Hyprland/assets/74491719/224cb9b1-084d-4d10-9e16-f5c78ec05364

Hyprland:
- delayed resizing
- weird stretching and wobbling #4391
- white background
- massive lag
https://github.com/hyprwm/Hyprland/assets/74491719/71207288-6925-47f9-9a4a-3b9c72f8f6f1

**Comment by fufexan** [comment]
Oh so it's an xwayland issue? I thought my wine build was the problem.

**Comment by phonetic112** [comment]
Turning on misc:animate_manual_resizes seems to fix this. The stretching behavior as described in https://github.com/hyprwm/Hyprland/issues/4391 is much worse, but turning off animations helped a bit. I also didn't have anymore lag or stuttering at all.

Video (with animations on):

https://github.com/hyprwm/Hyprland/assets/73647246/2803852e-3935-4784-8f65-330422141611

**Comment by quantenzitrone** [comment]
enabling `misc:animate_manual_resizes` seems to fix the lag, but

sometimes windows get stretched:
![2024-01-19 01-56-24-00:00:01](https://github.com/hyprwm/Hyprland/assets/74491719/bacbde21-498c-4ec3-8fe7-a5b0fe2263a6)

sometimes windows get double padded:
![2024-01-19 01-56-24-00:00:03](https://github.com/hyprwm/Hyprland/assets/74491719/885cd7c7-993a-4ff3-a431-600626b02081)

i don't like the stretching
