### ISSUE TITLE
nixos failed to start home manager environment

### ISSUE THREAD

**Issue by sgj123456** [hyprwm/Hyprland#4466]
![PXL_20240117_150743344.jpg](https://github.com/hyprwm/Hyprland/assets/94758390/e33ed00f-e76d-45ab-8b08-0cd98f209aa0)

![PXL_20240117_150805039.jpg](https://github.com/hyprwm/Hyprland/assets/94758390/9171a0cd-0aa4-4ebd-b983-6f079d94a86e)

**Comment by sgj123456** [comment]
I didn't set anything else, it's an original configuration. Do you need anything else? If I modify hyprland to sway, I don't have this problem.

**Comment by fufexan** [comment]
Did you read the error? It says there's a file in place of `~/.config/hypr/hyprland.conf`, probably your old config file. (Re)move it and restart `home-manager-maopao.service` and it will work.
