### ISSUE TITLE
Add smart gaps

### ISSUE THREAD

**Issue by Dorian-DS** [hyprwm/Hyprland#447]
Can smart gaps be implemented as a config option?  Turning this on would remove the gaps when only one window is open, and restore them if a 2nd window is open.  Similar to how it works in Sway.  This takes advantage of all the monitor space and is great when you only have one editor or browser open.

**Comment by KyleUltimate** [comment]
https://github.com/hyprwm/Hyprland/issues/355
If I'm understanding correctly, isn't this issue very similar to that?

**Comment by vaxerski** [comment]
done in f892387b7020ce27dbcf370244e26e09c9ecc1e5 and 60c16f77a64ef1e992f7aa7476b2e52847d18c25
