### ISSUE TITLE
Apply shadow to layerSurfaces

### ISSUE THREAD

**Issue by iagorrr** [hyprwm/Hyprland#4470]
### Description

Currently there is no way to apply shadow to *layerSurfaces*, such as notifications or bars, would be nice to apply shadows to *layerSurfaces* or at least use something like `layerrule = shadow, NAMESPACE`

**Comment by vaxerski** [comment]
No. Layers should style themselves.

**Comment by noahgitsham** [comment]
> No. Layers should style themselves.

But shadows go behind and around the layer, they don't change the actual rendering of the layer itself.

You've already added the blurring layerrule which I would argue changes the layer's style more than shadows would.

It's also a huge pain reserving space for shadows to extend beyond the edge of a layer.

I understand why you say layers should style themselves, but I think this is one case where the compositor is justified in styling layers.

**Comment by fufexan** [comment]
Blur is easier to get right than shadows. You know you have a transparent surface, you blur it. It works with rounded corners just fine because of the `ignorealpha` layerrule.

Shadows are harder to do, precisely because they're *outside* the layer.

> It's also a huge pain reserving space for shadows to extend beyond the edge of a layer.

It's really not. All you need is

```css
.window {
  margin: 5px 10px 15px;
  box-shadow: 0 3px 5px 1px rgba(0, 0, 0, 0.3);
}
```

**Comment by noahgitsham** [comment]
> Shadows are harder to do, precisely because they're outside the layer.

Forgive me, I haven't looked into the codebase, but why wouldn't the current shadow rendering functionality for windows work for other layers?

> It's really not. All you need is
> 
> ```css
> .window {
>   margin: 5px 10px 15px;
>   box-shadow: 0 3px 5px 1px rgba(0, 0, 0, 0.3);
> }
> ```

The box shadow is cut off at the edge of the reserved space for the layer. It would be nice if the shadows could extend beyond this, which would be simple if it were done by the compositor.
For example, it would be nice if my bar had a shadow which could extend into the `gaps_out` area.

**Comment by fufexan** [comment]
> Forgive me, I haven't looked into the codebase, but why wouldn't the current shadow rendering functionality for windows work for other layers?

Layers can take various shapes visually, but all that Hyprland knows about them is that there's a rectangle WxH at X,Y on the screen. So simply adding shadows to the rectangle, when in reality the layer surface has rounded corners, won't look good.

> The box shadow is cut off at the edge of the reserved space for the layer.

Which is why I've added the `margin` there. It has to be set on a box inside the layer, not the widget itself (talking in GTK terms).

**Comment by noahgitsham** [comment]
> Layers can take various shapes visually, but all that Hyprland knows about them is that there's a rectangle WxH at X,Y on the screen. So simply adding shadows to the rectangle, when in reality the layer surface has rounded corners, won't look good.

Ah makes sense, but could `ignorezero` not be used to recognise the shape of the layer, and generate shadows for it, as it is for not blurring rounded corners? 
 
> Which is why I've added the `margin` there. It has to be set on a box inside the layer, not the widget itself (talking in GTK terms).

Is there a way to make this margin overlap with `gaps_out`? As you said, Hyprland doesn't know the contents of the layer, so surely there's no way it can know about the margin

**Comment by fufexan** [comment]
> Ah makes sense, but could `ignorezero` not be used to recognise the shape of the layer, and generate shadows for it, as it is for not blurring rounded corners?

Perhaps, but it's up to Vaxry.

> Is there a way to make this margin overlap with `gaps_out`? As you said, Hyprland doesn't know the contents of the layer, so surely there's no way it can know about the margin.

Yes, setting it manually to the same value.

**Comment by noahgitsham** [comment]
> Yes, setting it manually to the same value.

When I try this, they do not overlap, am I misunderstanding you? The layer has to reserve space for said margin, so how could it overlap with `gaps_out`?

**Comment by fufexan** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/36706276/bea61694-408d-4f3c-b725-9b02447f1823)
In my case they do overlap. What I have in my config (that affects this) is the CSS snippet I sent above, and the anchor of the LS being top right.

**Comment by noahgitsham** [comment]
Ah I believe we are referring to different kinds of layers, sorry for not being clearer.

I am talking about my statusbar, which has its own reserved area on the screen. I would like a shadow around this bar, which can be in the `gaps_out` area.

![image](https://github.com/hyprwm/Hyprland/assets/73707948/bdc35033-f04f-4c23-bae3-5f9971543bbc)
This is what I would like to achieve, but I don't think it's currently possible.

The two possible solutions I can think of to achieve this are:
- Adding the ability to set individual values for the different sides of `gaps_out`, in this case the bar's margin and `gaps_out(left)` would be half of the standard `gaps_out` value.

    - This would be a bit hacky (but separate gaps could be useful in other cases). 

- Add shadows for layers.

It also makes sense for Hyprland to generate shadows globally for the sake of consistency.

**Comment by vaxerski** [comment]
make bar not exclusive and add reserved area in hl config manually.

**Comment by noahgitsham** [comment]
Ah, I was unaware you could do that, thank you. Regardless, what do you think about the revised arguments for Hyprland handling layer shadows [here](https://github.com/hyprwm/Hyprland/issues/4470#issuecomment-1907401128) and the proposed solution [here](https://github.com/hyprwm/Hyprland/issues/4470#issuecomment-1908771949)?

**Comment by vaxerski** [comment]
> Ah makes sense, but could ignorezero not be used to recognise the shape of the layer, and generating shadows for it, as it is for not blurring rounded corners?

not possible
