### ISSUE TITLE
Ability to specify colors with #color, not just rgb(color) or rgba(color)

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#4473]
### Description
According to the Hyprland documentation color can be specified in 3 formats - `rgba(rrggbbaa)`, `rgb(rrggbb)` and legacy ARGB, but can not be specified with commonly used almost everywhere format using a leading number sign (#), like `#RRGGBB` for six-value syntax and `#RRGGBBAA` for eight-value syntax with transparency. When I try to specify it in this format, it just applies a transparent color.

### Why?
I have some global pallete in this format, that automatically applied to all configs and work everywhere, from cli tools to browser themes, but not in Hyprland. Also it's not even a proper rgb format like `rgb(255,255,255)`, it's just hex triplet inside rgb(), so it probably won't be valid anywhere outside Hyprland.

### Expected Behavior
It would be nice if something like this was also a valid format:
```
col.active_border = #33ccff #00ff99 45deg
col.inactive_border = #595959aa
```

**Comment by fufexan** [comment]
There is `0xAARRGGBB` or `0xRRGGBB` if that helps. Not sure how you manage your global palette, but in mine I have the `rrggbb` colors which I can then extend with other functions, like prepending `#` or converting to `rgb[a]`.

**Comment by Ligthiago** [comment]
Yes, some hacky way can always be used, but I think such simple things just need to work out of the box. 
I use NixOS, for now I just copy your convert functions for your dotfiles as you mention, thanks for the advice.

**Comment by Ligthiago** [comment]
Oh, I see, just don't commenting stuff and missed it. Anyway, thanks for answer.

**Comment by KrolixW** [comment]
Now that we have lua config and # there isn't a comment can we have it, please?

Colors are passed as a string anyway. And having 'rgb(RRGGBB)' looks stupid IMO
