### ISSUE TITLE
Scaled Display not Covering Full Screen Width

### ISSUE THREAD

**Issue by mewoocat** [hyprwm/Hyprland#4474]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit dcd7a92b01a360bbe7afa7299604c4040abb4c62  ().
Date: 2024-01-15
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: scythe
Release: 6.1.72
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Jan 10 16:10:37 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240113.9b19f5e"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Setting the monitor scale to something besides 1x results in a small vertical line of rendered space on the right side of the screen.  I have discussed this issue in the Discord and it was suggested that this is a rounding error.  

### How to reproduce

This issue has been observed at 1.33 and 1.5 scale on a 2560x1440 display.

### Crash reports, logs, images, videos

For example, this prevents the ability to click on a button that is at the far right when the mouse is at the edge of the screen.

Photo: (The mouse can be observed to be rendered in the blank space)
![20240118_082351](https://github.com/hyprwm/Hyprland/assets/97066700/184b948d-f256-4655-b5e7-4811c2d19006)

Screenshot: (The extra space seems to be transparent so it's difficult to see)
![image](https://github.com/hyprwm/Hyprland/assets/97066700/12d75612-df35-4ac6-b0cd-f31b723031f3)

**Comment by vaxerski** [comment]
can you attach `hyprctl monitors`?

**Comment by mewoocat** [comment]
```
Monitor eDP-1 (ID 0):
	2560x1440@59.95100 at 0x0
	description: Sharp Corporation LQ125T1JW02 (eDP-1)
	make: Sharp Corporation
	model: LQ125T1JW02
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 48 0 0
	scale: 1.33
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

**Comment by vaxerski** [comment]
and how many pixels are there on the right, unused?

Plus, can a floating window be moved and render there?

**Comment by mewoocat** [comment]
Seems to be 8 pixels.  Yes, it does render floating windows in the blank space.
![20240118_103743_1](https://github.com/hyprwm/Hyprland/assets/97066700/a198a1eb-19e4-420f-b12e-b756ba364fe8)

**Comment by mewoocat** [comment]
The previous example was at 1.3x.  I can't test 1.5x anymore, but 1.6x seems to have about 2 pixels.

**Comment by rdvm** [comment]
I started noticing the same thing, but in my case it's a gap along the bottom edge of my display. I _think_ I'm seeing is the teal color of the Hyprland splash screen/wallpaper character peaking out (that's what caught my eye to begin with).
 
![swappy-20240118-192803](https://github.com/hyprwm/Hyprland/assets/22112107/94700746-6223-47c5-9445-c11abbc9821d)

Here's a screenshot of the same area for comparison:
![swappy-20240118-192529](https://github.com/hyprwm/Hyprland/assets/22112107/517f7713-0564-4870-a096-c7ad227857ec)

```
hyprctl version
Hyprland, built from branch  at commit v0.34.0  ().
Date: 2024-01-01
Tag:

flags: (if any)
```

```
Monitor eDP-1 (ID 0):
        2256x1504@59.99900 at 0x0
        description: BOE 0x095F (eDP-1)
        make: BOE
        model: 0x095F
        serial:
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 36 0 0
        scale: 1.33
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
        activelyTearing: false
```

**Comment by eskiq** [comment]
I don't know if that would be of any help but I also have the same issue. With helix in foot I do have those "lines" on right and bottom side only while with helix in kitty they are around whole text editor.

**Comment by vaxerski** [comment]
can you test with #5748 merged?

**Comment by rdvm** [comment]
```
 hyprctl version
Hyprland, built from branch  at commit 1d40af64d352bd5a87c7d53a52707fc5cfc6940e  ().
Date: 2024-04-25
Tag: , commits: @COMMITS@

flags: (if any)
```

This appears to be working for me! 

I did notice a bug after updating to this commit (was previously on v39, I think), but I'm guessing it's unrelated to this; haven't checked yet for any open issues about it, but I'll do that.

Both Chrome and Brave are just transparent when running under `xwayland`. They seem to work fine under `wayland`, and other apps under `xwayland` seem fine too, including 1Password which I believe is an Electron app ¯\_(ツ)_/¯

![image](https://github.com/hyprwm/Hyprland/assets/22112107/31ed5579-a36b-4031-a07a-a510347616bd)

**Comment by vaxerski** [comment]
thats a chromium bug
