### ISSUE TITLE
Add matrix bridge to discord

### ISSUE THREAD

**Issue by ParetoOptimalDev** [hyprwm/Hyprland#4475]
### Description

I see this was asked about in #878, however I don't see any way to join via matrix and it's not on https://hyprland.org/.

**Comment by fufexan** [comment]
There is no official Matrix room. There exists one at https://matrix.to/#/#hyprland:matrix.org, however the room admin has been inactive for a long time and we don't have any way of getting control of it.

**Comment by ParetoOptimalDev** [comment]
Okay. I guess not possible/too much friction in creating a new one and bridging it? The phone verification on the discord keeps me from joining the Discord room to be honest. I don't want to give Discord my number.

I guess Matrix is losing the fight in "cool open source software" :cry:

**Comment by fufexan** [comment]
You can still join the server and message me in DMs, and I can grant you permission to talk in the server without you needing to verify with the phone number. My @ is fufexan on Discord as well.
