### ISSUE TITLE
home-manager variables

### ISSUE THREAD

**Issue by TalkierTick9904** [hyprwm/Hyprland#4477]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a  ().
Date: 2024-01-17
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: nix
Release: 6.7.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun Jan  7 20:18:38 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 SUPER] [10de:1f06] (rev a1) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240117.842d9d8"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I was setting up hyprland through home-manager and ran into a problem. I defined the gtk and qt theme through the corresponding modules in the home-manager and after that, when I tried to run the command `hyprctl dispatch exec obs`, obs and hyprland-share-picker started with the default themes. After some time I managed to set up the qt theme by adding 3 variables that were already added to the user environment via the home-manager in hyprland module:
```nix
{ pkgs, inputs, lib, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = true;
    ...
    env = [
      "GTK2_RC_FILES,/home/USER/.config/gtk-2.0/gtkrc"
      "QT_QPA_PLATFORMTHEME,gtk2"
      "QT_STYLE_OVERRIDE,gtk2"
    ];
    ...
  };
}
```
And also adding these commands to the startup script:
``` sh
dbus-update-activation-environment --systemd --all &
systemctl --user import-environment QT_QPA_PLATFORMTHEME &
```
That being said, if you run any qt program through the terminal, the theme will be applied since these variables are already defined in the home-manager.
Is it possible to pass home-manager variables to hyprctl without copying all of them?

### How to reproduce

My themes.nix file:
```nix
{ config, pkgs, ... }:
{
  gtk = {
    enable = true;
    gtk2.configLocation = "${config.xdg.configHome}/gtk-2.0/gtkrc";
    theme.name = "Catppuccin-Mocha-Standard-Blue-Dark";
    iconTheme.name = "Tela-circle-dracula-dark";
    font = {
      name = "Inter Nerd Font";
      size = 12;
    };
  };

  qt = {
    enable = true;
    platformTheme = "gtk";
    style.name = "gtk2";
  };

  home.packages = with pkgs; [
    (tela-circle-icon-theme.override {
      colorVariants = [ "dracula" ];
    })
    (catppuccin-gtk.override {
      accents = [ "blue" ];
      size = "standard";
      tweaks = [ "normal" ];
      variant = "mocha";
    })
  ];
}
```
Include that in your home.nix file and try running any qt app via hyprland bind or `hyprctl dispatch exec`.

**Comment by fufexan** [comment]
The problem is that Home Manager can only set those variables for the interactive shell, but they need to be set in the login shell for the programs to pick them up. The solution is to set them using `environment.variables` in your NixOS config.
