### ISSUE TITLE
Clicking an empty workspace on a non-focused monitor will not focus it

### ISSUE THREAD

**Issue by KaspervdHeijden** [hyprwm/Hyprland#4482]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
[vanderheijdenk@spaceship zsh Linux 6.6.11 ~ 2024-01-19 10:54]
% hyprctl version
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

[vanderheijdenk@spaceship zsh Linux 6.6.11 ~ 2024-01-19 10:54]
% hyprctl systeminfo
usage: hyprctl [(opt)flags] [command] [(opt)args]

commands:
    activewindow
    activeworkspace
    binds
    clients
    cursorpos
    decorations
    devices
    dispatch
    getoption
    globalshortcuts
    hyprpaper
    instances
    keyword
    kill
    layers
    layouts
    monitors
    notify
    plugin
    reload
    setcursor
    seterror
    setprop
    splash
    switchxkblayout
    version
    workspacerules
    workspaces

flags:
    -j -> output in JSON
    --batch -> execute a batch of commands, separated by ';'
    --instance (-i) -> use a specific instance. Can be either signature or index in hyprctl instances (0, 1, etc)

[1 vanderheijdenk@spaceship zsh Linux 6.6.11 ~ 2024-01-19 10:54]
% 
```

</details>

(Please consider updating the template, `hyprctl systeminfo` does not work)

### Bug or Regression?

Bug

### Description

When clicking on a empty workspace on a monitor that does not have focus, I expect that workspace and monitor to obtain focus. However, it does not.

### How to reproduce

- Have `swaybg` render a nice background image
- Have `follow_mouse` set to either `0` or `2`
- Have a multi monitor setup:
    - Monitor A: this has focus
    - Monitor B: this does not have focus, and does not have any windows (so an empty workspace)
- Click on the desktop B: It does not obtain focus.
    - (If a window is on monitor B, then clikcing it will result in the workpsace/monitor to obtain focus)

**Comment by KaspervdHeijden** [comment]
Note: I can mitigate this by enabling `mouse_move_focuses_monitor`, but I would prefer that to be `off`. Moving the mouse and clicking the mouse are two distinct operations.

**Comment by vaxerski** [comment]
> (Please consider updating the template, hyprctl systeminfo does not work)

![image](https://github.com/hyprwm/Hyprland/assets/43317083/d96ce10b-dd17-441c-a552-49698593a6f3)

> Tag: v0.34.0

Please consider reading carefully...?

**Comment by KaspervdHeijden** [comment]
Missed that :) Any update on the actual issue?

**Comment by vaxerski** [comment]
seems to work on my end

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by KaspervdHeijden** [comment]
Hey @vaxerski, thganks for getting back and sorry for neglecting thi issues. I've since moved back to Sway. If I return to hyprland in the future and encounter this issue, I'll make a new issue.

Closing.
