### ISSUE TITLE
hyprctl can use "hyprctl clients -j" info to manipulate windows

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4487]
### Description

It's reasonable to do something like focus window based on 'hyprctl clients -j" parsered info such as "address", So that can make a rofi window switch tool.
I already got perl script prepared.
```
#!/bin/perl
use v5.10;
use utf8;
no warnings;
use Data::Dumper;
use JSON;
$hyprinfo = qx(hyprctl -j clients);
$windows = decode_json $hyprinfo;
# print Dumper($windows);
foreach my $window (@$windows){
	if ($window->{workspace}->{id} ne '-1'){
	say $window->{title}, ' in WORKSPACE: ', $window->{workspace}->{name};
	}
}
```

**Comment by vaxerski** [comment]
whats the issue?

**Comment by vincentaxhe** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by vaxerski** [comment]
I don't speak chinese.

**Comment by romanstingler** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
this is just a autoresponder

This is a vacation autoresponder email from QQ Mail. Hi, I'm on vacation recently and can't respond to your email personally. I will get back to you as soon as possible after my vacation is over.

**Comment by vaxerski** [comment]
why is an autoresponder responding to autogen emails...

**Comment by romanstingler** [comment]
Absolutely no clue

**Comment by vincentaxhe** [comment]
> whats the issue?

it's an enhancement request, not an issue. About use hyprctl output to make a window switch.
I will try to close autoresponder,sometimes it intervene.

**Comment by kensad-ops** [comment]
@vincentaxhe isn't we already have that ? according to the wiki you can use [focuswindow](https://wiki.hyprland.org/Configuring/Dispatchers/) for that

**Comment by vincentaxhe** [comment]
> @vincentaxhe aren't we already have that ? according to the wiki you can use [focuswindow](https://wiki.hyprland.org/Configuring/Dispatchers/) for that

it's for keybinding, nowhere show how to use hyprctl command to focus a specified window with such as "address", The result be like a window list show and select then focus to the titled window.

**Comment by kensad-ops** [comment]
> it's for keybinding, nowhere show how to use hyprctl command to focus a specified window with such as "address", The result be like a window list show and select then focus to the titled window.

@vincentaxhe oh you can use `hyprctl dispatch` [wiki](https://wiki.hyprland.org/Configuring/Using-hyprctl/) to call dispatcher with hyprctl

**Comment by vincentaxhe** [comment]
@kensad-ops 
thank you, that's exactly what I want, I can close it now.
I should search 'address' keyword under dispatcher topic page, But the wiki cannot global search, which ConText wiki did better.

**Comment by vincentaxhe** [comment]
here is my work, a simple window switcher, can only open special workspace than focus any window in special workspace
```
#!/bin/perl
use v5.10;
use utf8;
no warnings;
use Data::Dumper;
use JSON;
$hyprinfo = qx(hyprctl -j clients);
$windows = decode_json $hyprinfo;
# print Dumper($windows);
$i = 0;
foreach my $window (@$windows){
	if ($window->{workspace}->{id} ne '-1'){
	push @windowarr, [$window->{address}, $window->{workspace}->{name}];
	push @menuarr, $i++, "\t", $window->{workspace}->{name}, "\t", $window->{title}, "\n";
	}
}
$menu = join '', @menuarr;
$index = (split /\t/, qx(echo '$menu'|wofi --dmenu))[0];
$dest = $windowarr[$index];
if ($dest->[1] =~ /^special/){
system "hyprctl dispatch workspace $dest->[1]"}
else{system "hyprctl dispatch focuswindow address:$dest->[0]"
}
```
