### ISSUE TITLE
Floating windows focus.

### ISSUE THREAD

**Issue by g3r** [hyprwm/Hyprland#449]
Floating windows are not automatically focused when other windows are closed.

Steps to reproduce:
In an empty workspace open two windows and make them float.
Close one of them

Observed behaviour:
The remaining window is not focused until hovered with mouse

 In fact when no window is focused and press the close window binding the remaining floating window is focused.

**Comment by vaxerski** [comment]
I mean, why would it be? it's focus follows mouse, and your mouse is not on the window.

**Comment by g3r** [comment]
> I mean, why would it be? 

I don't see the use case of focusing nothing . It makes you have to move the mouse.
Tiling and non-tiling wm/compositors automatically select the remaining window. Tested with sway, awesomewm and plasma.

> it's focus follows mouse, and your mouse is not on the window.

When you have only 1 focused floating window in the workspace and move the mouse away, the window remain focused. So hyprland is already ignoring the focus follows mouse (which is correct IMO).

**Comment by vaxerski** [comment]
done in dba4596c7eac61d84edc883b1e0e7c6ba6af7efc
