### ISSUE TITLE
focusworkspaceoncurrentmonitor does not exist

### ISSUE THREAD

**Issue by erooke** [hyprwm/Hyprland#4491]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.34.0  ().
Date: 2024-01-01
Tag: 

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland complains that the `focusworkspaceoncurrentmonitor` dispatcher as documented on the [wiki](https://wiki.hyprland.org/Configuring/Dispatchers/) does not exist.

```
Config error at line 153 (/home/ethan/.config/hypr/hyprland.conf): Invalid dispatcher, requested "focusworkspaceoncurrentmonitor" does not exist
```

### How to reproduce

Edit the default config, replace the `workspace` dispatcher with `focusworkspaceoncurrentmonitor`.

**Comment by MightyPlaza** [comment]
you're using Release v0.34, but the git (not release) wiki
https://github.com/hyprwm/Hyprland/pull/4439 isn't on a release yet

**Comment by erooke** [comment]
Woops, my bad. Carry on 😅
