### ISSUE TITLE
tty bash execute Hyprland, not load ~/.bashrc

### ISSUE THREAD

**Issue by yuzhen1024** [hyprwm/Hyprland#4493]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
hyprctl version   
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

hyprctl systeminfo
usage: hyprctl [(opt)flags] [command] [(opt)args]

commands:
...
```

</details>

### Bug or Regression?

Regression

### Description

I need to load some `$PATH` which is stored in my `~/.bashrc` .
So if I need to bind some programs in `Hyprland.conf` , I can't just go by the name of the program, but by the full path.

### How to reproduce

Before updating to `0.34.0` , there was no problem with changing it, but after updating, this problem appears.
I'm not sure which step is wrong, it may be a Hyprland problem, it may not.

**Comment by vaxerski** [comment]
hyprland doesn't have anything to do with your bashrc. That's the job of your login manager
