### ISSUE TITLE
Hyprland crashes when monitor gets unplugged 

### ISSUE THREAD

**Issue by RoccoRakete** [hyprwm/Hyprland#4495]
### Hyprland Version

4d403dac3244aab217fb9bf17a68e9a009fcadd8

### Bug or Regression?

Bug

### Description

If a Monitor gets unplugged, Hyprland crashes 

### How to reproduce

Unplug a monior.

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Vaxry is going to be upset.

Hyprland received signal 11 (Segmentation fault)

Version: 4d403dac3244aab217fb9bf17a68e9a009fcadd8
Tag: 

System info:
	System name: Linux
	Node name: ThinkPad
	Release: 6.7.0
	Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun Jan  7 20:18:38 UTC 2024

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [Iris Xe Graphics] [8086:46a8] (rev 0c) (prog-if 00 [VGA controller])

os-release:
	BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
	BUILD_ID="24.05.20240119.bbe7d8f"
	DOCUMENTATION_URL="https://nixos.org/learn.html"
	HOME_URL="https://nixos.org/"
	ID=nixos
	IMAGE_ID=""
	IMAGE_VERSION=""
	LOGO="nix-snowflake"
	NAME=NixOS
	PRETTY_NAME="NixOS 24.05 (Uakari)"
	SUPPORT_URL="https://nixos.org/community.html"
	VERSION="24.05 (Uakari)"
	VERSION_CODENAME=uakari
	VERSION_ID="24.05"
	

Backtrace:
	#0 | /run/current-system/sw/bin/Hyprland(_Z12getBacktracev+0x48) [0x57ca28]
		_Z12getBacktracev
		??:?
	#1 | /run/current-system/sw/bin/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x659) [0x533f19]
		_ZN13CrashReporter18createAndSaveCrashEi
		??:?
	#2 | /run/current-system/sw/bin/Hyprland(_Z25handleUnrecoverableSignali+0x44) [0x4a4564]
		_Z25handleUnrecoverableSignali
		??:?
	#3 | /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6(+0x3deb0) [0x7f71c3854eb0]
		??
		??:0
	#4 | /run/current-system/sw/bin/Hyprland(_ZN8CMonitor15changeWorkspaceEP10CWorkspacebbb+0x1de) [0x58827e]
		_ZN8CMonitor15changeWorkspaceEP10CWorkspacebbb
		??:?
	#5 | /run/current-system/sw/bin/Hyprland(_ZN11CCompositor22moveWorkspaceToMonitorEP10CWorkspaceP8CMonitorb+0x64b) [0x4bb7db]
		_ZN11CCompositor22moveWorkspaceToMonitorEP10CWorkspaceP8CMonitorb
		??:?
	#6 | /run/current-system/sw/bin/Hyprland(_ZN8CMonitor12onDisconnectEb+0x5b3) [0x58b083]
		_ZN8CMonitor12onDisconnectEb
		??:?
	#7 | /run/current-system/sw/bin/Hyprland(_ZN11CCompositor16leaveUnsafeStateEv+0x217) [0x4b9947]
		_ZN11CCompositor16leaveUnsafeStateEv
		??:?
	#8 | /run/current-system/sw/bin/Hyprland(_ZN15CHyprWLListener4emitEPv+0x3b) [0x59567b]
		_ZN15CHyprWLListener4emitEPv
		??:?
	#9 | /run/current-system/sw/bin/Hyprland(_Z13handleWrappedP11wl_listenerPv+0x3f) [0x596eef]
		_Z13handleWrappedP11wl_listenerPv
		??:?
	#10 | /nix/store/8ggx8dnicpljzjcfijk8swy4l0fa2j01-wayland-1.22.0/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7c) [0x7f71c4550a0c]
		??
		??:0
	#11 | /nix/store/3jmkakkzcs9a7afyml9w76m6vc1j63vw-wlroots-hyprland-2023-12-30_f81c3d9/lib/libwlroots.so.13(+0x56788) [0x7f71c447d788]
		??
		??:0
	#12 | /nix/store/589gf7jf57pcmzlq5fwq4jzn3a9m9zc0-libdrm-2.4.119/lib/libdrm.so.2(drmHandleEvent+0x127) [0x7f71c42d7b17]
		??
		??:0
	#13 | /nix/store/3jmkakkzcs9a7afyml9w76m6vc1j63vw-wlroots-hyprland-2023-12-30_f81c3d9/lib/libwlroots.so.13(+0x57df9) [0x7f71c447edf9]
		??
		??:0
	#14 | /nix/store/8ggx8dnicpljzjcfijk8swy4l0fa2j01-wayland-1.22.0/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7f71c45528f2]
		??
		??:0
	#15 | /nix/store/8ggx8dnicpljzjcfijk8swy4l0fa2j01-wayland-1.22.0/lib/libwayland-server.so.0(wl_display_run+0x25) [0x7f71c4550455]
		??
		??:0
	#16 | /run/current-system/sw/bin/Hyprland(main+0x7a2) [0x48e9d2]
		main
		??:?
	#17 | /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6(+0x280ce) [0x7f71c383f0ce]
		??
		??:0
	#18 | /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libc.so.6(__libc_start_main+0x89) [0x7f71c383f189]
		??
		??:0
	#19 | /run/current-system/sw/bin/Hyprland(_start+0x25) [0x4a43c5]
		_start
		??:?

Log tail:
[LOG] Callback 31ee790 -> 31ee788, layerSurface removed.
[LOG] Callback 31ee7f8 -> 31ee7f0, layerSurface removed.
[LOG] Callback 31ee860 -> 31ee858, layerSurface removed.
[LOG] Callback 31ee930 -> 31ee928, layerSurface removed.
[LOG] LayerSurface 31eefc0 destroyed
[LOG] Removing LayerSurface that wasn't mapped.
[LOG] Callback 31ef3b8 -> 31ef3b0, layerSurface removed.
[LOG] Callback 31ef280 -> 31ef278, layerSurface removed.
[LOG] Callback 31ef2e8 -> 31ef2e0, layerSurface removed.
[LOG] Callback 31ef350 -> 31ef348, layerSurface removed.
[LOG] Callback 31ef420 -> 31ef418, layerSurface removed.
[LOG] LayerSurface 31efa00 unmapped
[LOG] Framebuffer created, status 36053
[LOG] Callback 31efc40 -> 31efc38, CWLSurface removed.
[LOG] CWLSurface 31efbf0 called destroy()
[LOG] LayerSurface 31efa00 destroyed
[LOG] Callback 31efdf8 -> 31efdf0, layerSurface removed.
[LOG] Callback 31efcc0 -> 31efcb8, layerSurface removed.
[LOG] Callback 31efd28 -> 31efd20, layerSurface removed.
[LOG] Callback 31efd90 -> 31efd88, layerSurface removed.
[LOG] Callback 31efe60 -> 31efe58, layerSurface removed.
[LOG] LayerSurface 300ae00 unmapped
[LOG] Framebuffer created, status 36053
[LOG] Callback 300b020 -> 300b018, CWLSurface removed.
[LOG] CWLSurface 300afd0 called destroy()
[LOG] LayerSurface 300ae00 destroyed
[LOG] Callback 300b1d8 -> 300b1d0, layerSurface removed.
[LOG] Callback 300b0a0 -> 300b098, layerSurface removed.
[LOG] Callback 300b108 -> 300b100, layerSurface removed.
[LOG] Callback 300b170 -> 300b168, layerSurface removed.
[LOG] Callback 300b240 -> 300b238, layerSurface removed.
[LOG] Removed monitor HDMI-A-1!
[WARN] Unplugged last monitor, entering an unsafe state. Good luck my friend.
[LOG] Entering unsafe state
[LOG] Registered signal for owner 2748f50: 2748dc8 -> 27493a8 (owner: )
[LOG] Registered signal for owner 2748f50: 2748e58 -> 2749410 (owner: )
[LOG] Registered signal for owner 2748f50: 2748e48 -> 2749478 (owner: )
[LOG] Registered signal for owner 2748f50: 2748dd8 -> 27494e0 (owner: )
[LOG] Registered signal for owner 2748f50: 2748de8 -> 2749548 (owner: )
[LOG] Registered signal for owner 2748f50: 2748e08 -> 27495b0 (owner: )
[LOG] Registered signal for owner 2748f50: 2748e28 -> 2749618 (owner: )
[WARN] No rule found for HEADLESS-1, trying to use the first.
[WARN] No rules configured. Using the default hardcoded one.
[LOG] Applying monitor rule for HEADLESS-1
[ERR] Monitor HEADLESS-1 has NO PREFERRED MODE
[LOG] output HEADLESS-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] Monitor HEADLESS-1 -> destroyed all render data
[LOG] arrangeMonitors: 3 to arrange
[LOG] arrangeMonitors: HDMI-A-1 explicit [0.00, 0.00]
[LOG] arrangeMonitors: eDP-1 auto [2560, 0.00]
[LOG] arrangeMonitors: HEADLESS-1 auto [4480, 0.00]
[LOG] arrangeMonitors: HDMI-A-1 xwayland [0, 0.00]
[LOG] arrangeMonitors: eDP-1 xwayland [2560, 0.00]
[LOG] arrangeMonitors: HEADLESS-1 xwayland [4480, 0.00]
[LOG] Monitor HEADLESS-1 data dump: res 1920x1080@60.00Hz, scale 1.00, transform 0, pos 4480x0, 10b 0
[LOG] Added new monitor with name HEADLESS-1 at [4480, 0] with size [1920, 1080], pointer 2748ca0
[LOG] New monitor: WORKSPACEID 3, exists: 0
[ERR] Couldn't commit output HEADLESS-1 in ensureVRR -> true
[LOG] Callback 2447a90 -> 2447a88, CRenderbuffer removed.
[LOG] Callback 3193d50 -> 3193d48, CRenderbuffer removed.
[LOG] Removing monitor HDMI-A-1 from realMonitors
[LOG] Callback 2cdf928 -> 2cdf920,  removed.
[LOG] Callback 2cdf990 -> 2cdf988,  removed.
[WARN] Attempted to render frame on inactive session!
[LOG] Leaving unsafe state
[LOG] onDisconnect called for HEADLESS-1
[LOG] Callback 27493d0 -> 27493c8,  removed.
[LOG] Callback 2749508 -> 2749500,  removed.
[LOG] Callback 2749570 -> 2749568,  removed.
[LOG] Callback 27495d8 -> 27495d0,  removed.
[LOG] Callback 2749640 -> 2749638,  removed.
[LOG] Removed monitor HEADLESS-1!
[LOG] moveWorkspaceToMonitor: Moving 2 to monitor 0

**Comment by vaxerski** [comment]
latest git is not a version

**Comment by RoccoRakete** [comment]
> latest git is not a version

better like this?

**Comment by vaxerski** [comment]
still would be better if you did what the form asked you to do but whatever this will do

**Comment by killown** [comment]
try kernel lts, 6.7 has some monitor issues

**Comment by vaxerski** [comment]
[patch69.txt](https://github.com/hyprwm/Hyprland/files/14408257/patch69.txt)
try this fam

**Comment by euuurgh** [comment]
> [patch69.txt](https://github.com/hyprwm/Hyprland/files/14408257/patch69.txt) try this fam

Oh my god. Thank you so much, I recompiled, rebooted and tested, and it worked flawlessly.
I tested it in a few scenarios, and did not encounter any bugs or issues either, but when I actually looked at the diff I just had to burst out laughing. Good Job!
