### ISSUE TITLE
Window switcher in lbonn/rofi is broken

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#4498]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit 17339e0ae9ad01dcfdede76e8dfaf516a8cbb924 dirty (input: track exclusive LSes).
Date: Fri Jan 19 23:45:34 2024
Tag: v0.34.0-54-g17339e0a

flags: (if any)


System Information:
System name: Linux
Node name: arch-g14
Release: 6.6.13-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 20 Jan 2024 14:48:01 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Using https://github.com/lbonn/rofi , `rofi -show window` can no longer switch windows with 17339e0ae9ad01dcfdede76e8dfaf516a8cbb924.

### How to reproduce

1. Install rofi-lbonn-wayland-git
2. Run `rofi -show window`
3. Select a window and press enter.
4. Observe that no window switching happens.

### Crash reports, logs, images, videos

[hyprland-rofi-logs.log](https://github.com/hyprwm/Hyprland/files/14002583/rofi-logs.log)

**Comment by vaxerski** [comment]
I believe that's a rofi bug then.

I don't know how it works, but if rofi calls `focuswindow` while the LS is still open (not unmapped) then that will now be ignored (because rofi has exclusive keyboard focus) which is adhering to the spec.

**Comment by q234rty** [comment]
> exclusive keyboard focus

Hyprland could very well switch to the window while still forwarding keyboard events to rofi.

**Comment by earboxer** [comment]
I'm inclined to think this as a Hyprland bug, as the window-switching works in sway... but we may be better off to fix it in rofi.

**Comment by earboxer** [comment]
(This bemenu equivalent still works for anyone adversely affected, CC-0)
```
#!/bin/sh
hyprctl dispatch focuswindow address:"$(hyprctl -j clients | jq -r '.[]|(.class+" "+.title+"\t"+.address)' | bemenu | cut -f2)"
```

**Comment by vaxerski** [comment]
> Hyprland could very well switch to the window while still forwarding keyboard events to rofi.

no, not really. The definition of window focus is keyboard focus

**Comment by TheM1Stery** [comment]
> (This bemenu equivalent still works for anyone adversely affected, CC-0)
> 
> ```
> #!/bin/sh
> hyprctl dispatch focuswindow address:"$(hyprctl -j clients | jq -r '.[]|(.class+" "+.title+"\t"+.address)' | bemenu | cut -f2)"
> ```

I also added so that the windows who don't have a title to not appear in the list and used rofi -dmenu instead
```sh
hyprctl dispatch focuswindow address:"$(hyprctl -j clients | jq -r '.[]|select(.address != ""  and .title != "")|(.class + "\t" + .address + "\t" + .title)' | rofi -dmenu | cut -f2)"
```
