### ISSUE TITLE
Hyprland doesn't detect any external displays

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/Hyprland#4499]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 4d403dac3244aab217fb9bf17a68e9a009fcadd8 dirty (build: protocols: require wayland-protocols >= 1.32).
Date: Sun Jan 21 02:03:12 2024
Tag: v0.34.0-57-g4d403dac

flags: (if any)


System Information:
System name: Linux
Node name: vigu
Release: 6.7.0-arch3-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f9d] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland doesn't seem to detect my external projector, connected through the HDMI port on my laptop

I have verified that the port itself is okay by trying the same on Windows

xdph version installed `xdg-desktop-portal-hyprland 1.3.1-2`

Manually invoking `hyprland-share-picker` doesn't help either

### How to reproduce

1) Install the latest hyprland git and xdph
2) Put cable in hole
3) See nothing

### Crash reports, logs, images, videos

Output from `wdisplay`

![image](https://github.com/hyprwm/Hyprland/assets/45941793/36895a1b-bf57-4cea-9264-10be4fd11ec7)

Output from `hyprctl monitors all`

```
Monitor eDP-1 (ID 0):
	1920x1080@60.05600 at 0x0
	description: AU Optronics 0x5799 (eDP-1)
	make: AU Optronics
	model: 0x5799
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 42 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

My current monitor setup in `hyprland.conf`

```
monitor =,highres,auto,1
monitor=HDMI-0, 1920x1080, 0x0, 1
```

**Comment by MightyPlaza** [comment]
external ports are likely wired to the nvidia gpu, that is likely the issue
(setting up prime/... should make them work)

**Comment by WasteOfO2** [comment]
> external ports are likely wired to the nvidia gpu, that is likely the issue (setting up prime/... should make them work)

Thx for the reply, there seems to be next to no documentation for this for wayland. I am not sure whether the output is indeed attached to the dGPU either, how would i go about confirming this?

**Comment by MightyPlaza** [comment]
> > external ports are likely wired to the nvidia gpu, that is likely the issue (setting up prime/... should make them work)
> 
> Thx for the reply, there seems to be next to no documentation for this for wayland. I am not sure whether the output is indeed attached to the dGPU either, how would i go about confirming this?

setting up the nvidia gpu (https://wiki.hyprland.org/Nvidia/) and prime (https://wiki.archlinux.org/title/PRIME) should make it work

**Comment by WasteOfO2** [comment]
> > > external ports are likely wired to the nvidia gpu, that is likely the issue (setting up prime/... should make them work)
> > 
> > 
> > Thx for the reply, there seems to be next to no documentation for this for wayland. I am not sure whether the output is indeed attached to the dGPU either, how would i go about confirming this?
> 
> setting up the nvidia gpu (https://wiki.hyprland.org/Nvidia/) and prime (https://wiki.archlinux.org/title/PRIME) should make it work

I have followed the wikis to the best of my abilities, yet `hyprctl monitors all` seems to show only my laptop's screen

Output:
```
Monitor eDP-1 (ID 0):
	1920x1080@60.05600 at 0x0
	description: AU Optronics 0x5799 (eDP-1)
	make: AU Optronics
	model: 0x5799
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 42 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

```

not exactly sure where to go from here

**Comment by vaxerski** [comment]
not a hyprland issue. That's a wlroots issue (and nvidia)

**Comment by WasteOfO2** [comment]
> not a hyprland issue. That's a wlroots issue (and nvidia)

Apparently wlroots doesn't accept issues regarding proprietary drivers, am i just SoL then?
