### ISSUE TITLE
Enable sound buttons without modkeys

### ISSUE THREAD

**Issue by MarcPartensky** [hyprwm/Hyprland#450]
Hey I was wondering if there was a way to enable sound buttons without pressing mod keys ?

Here's how I deal with this currently:
 bind=SUPER,XF86AudioRaiseVolume,exec,pamixer -i 5
 bind=SUPER,XF86AudioLowerVolume,exec,pamixer -d 5
 bind=SUPER,XF86AudioMute,exec,pamixer -t
 
 Same goes for brightness.
 
 Maybe this already exists but I didn't find it in the wiki though and i can't find any results about this.
 Thanks in advance, love what you do

**Comment by KyleUltimate** [comment]
Easy, do this.
`bind=,XF86AudioMute,exec,pamixer -t`
Also it's here
![image](https://user-images.githubusercontent.com/68589851/182034122-52daed03-3eac-4c90-9626-df44ec7e6bde.png)

**Comment by MarcPartensky** [comment]
Oh that was simpler than i thought hahaha. Thanks !

**Comment by zspekt** [comment]
this is in my .conf. if held, it will run ad infinitum.
`
bind =, XF86MonBrightnessUp, exec, light -A 5`

this is also in my .conf. if held, however, it will only run once. i.e. i need to let go of the key and press it again.
`
bind =, XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%`

same behavior if i use pamixer. didn't had this problem on x with sxhkd.

**Comment by vaxerski** [comment]
use binde https://wiki.hyprland.org/Configuring/Binds/#bind-flags
