### ISSUE TITLE
Matching monitors by desc doesn't work if the description contains a # character

### ISSUE THREAD

**Issue by UwUnyaa** [hyprwm/Hyprland#4507]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a dirty (damage: use buffer_damage instead of effective_damage).
Date: Wed Jan 17 16:01:20 2024
Tag: v0.34.0-51-gc4365f20

flags: (if any)


System Information:
System name: Linux
Node name: MemePad-T480
Release: 6.7.0-arch3-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  split-monitor-workspaces by Duckonaut ver 1.1.0
```

</details>

### Bug or Regression?

Bug

### Description

Using the `desc:` rule for matching monitors doesn't handle the case where their description has a `#` in the name somewhere, for example in the serial number.

In my case the offending monitor is described as such:
```
Monitor DP-5 (ID 1):
	1920x1080@143.98100 at -1920x0
	description: Microstep MSI NXG253R #GjMYMxgwAAYH (DP-5)
	make: Microstep
	model: MSI NXG253R
	serial: #GjMYMxgwAAYH
	active workspace: 12 (12)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

A monitor rule with the serial number escaped like so simply doesn't work:

```
monitor = desc:description: Microstep MSI NXG253R ##GjMYMxgwAAYH,  highres,   -1920x0, 1
```

Only matching this monitor by its output is handled properly.

### How to reproduce

1. Plug in a monitor with a `#` somewhere in the description, such as the serial number.
2. Write a rule to match it by its description, escaping `#` by using `##` as per documentation.
3. The rule isn't functional.
4. Replace the `desc:` field with the output name.
5. Observe how the rule functions as intended.

**Comment by UwUnyaa** [comment]
Ok it was me being dumb, too  bad I can't remove issues off github.

**Comment by vaxerski** [comment]
hehe that's the cool part, your being dumb is immortalized
