### ISSUE TITLE
Override wayland socket's buffer size

### ISSUE THREAD

**Issue by Cloudef** [hyprwm/Hyprland#4508]
### Description

This issue has been in wayland for years now and it's ridiculous. Could hyprland patch the socket size of wayland, so we don't have to use wrapper programs or LD_PRELOAD hacks to not make programs crash? 
https://github.com/swaywm/sway/issues/7645#issuecomment-1646797349

**Comment by romanstingler** [comment]
it seems that it will be probably solved on wayland side soon.
https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/188

**Comment by Cloudef** [comment]
>2 years ago

**Comment by romanstingler** [comment]
very active in the last week 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/511c77fa-2962-477a-b829-3598abc72c18)

If it is important top you just contribute if you can.
