### ISSUE TITLE
Variable to Rotate Monitor Focus

### ISSUE THREAD

**Issue by mtwb47** [hyprwm/Hyprland#4509]
### Description

I apologize if this already exists. It would be awesome if there were a variable to allow you to create a binding to rotate through multiple monitors. 

E.g. Super+Tab would move the mouse and focus to the next monitor in the list and then the next and then the next, allowing you easily to move the focus to the workspaces on the other monitors.

**Comment by Cloudef** [comment]
[`hyprctl](https://wiki.hyprland.org/Configuring/Dispatchers/)
>monitor	One of: direction, ID, name, current, relative (e.g. +1 or -1)
>focusmonitor	focuses a monitor	monitor

**Comment by mtwb47** [comment]
Thank you. 

For anyone who comes across this in the future this is how it worked out:
```

bind = $mainMod, Tab, focusmonitor, +1
bind = $mainMod SHIFT, Tab, focusmonitor, -1
```
