### ISSUE TITLE
Layer shell like `bemenu` cannot be used with on screen keyboard

### ISSUE THREAD

**Issue by racheandre** [hyprwm/Hyprland#4512]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```
</details>

### Bug or Regression?

Bug

### Description

When using `Hyprland` on a tablet, I want to use a on screen keyboard like `wvkbd` based on wlr layer shell with dmenu program like `bemenu` also based on wlr layer shell to start some command or app. On `sway`, it works as expected, but not working on `Hyprland`. In `Hyprland`, `bemenu` will get all the focus so that the on screen keyboard cannot be trigger by touch input or mouse click etc. Though it is not just the on screen keyboard, `Hyprland` actually does not handle any input device for any app below the focused layer shell. It could be fine for desktop, but is not ideal behavior for a touchscreen device like a tablet or a linux phone.

### How to reproduce

1. Install `wvkbd` and `bemenu`
2. Run `wvkbd-mobintl` and then `bemenu-run`
3. Try to trigger `wvkbd` key by touch input or mouse

**Comment by vaxerski** [comment]
can you test on -git?

**Comment by racheandre** [comment]
> can you test on -git?

Tested. It's working on -git. Thanks!
