### ISSUE TITLE
Interacting with groups sometimes crashes Hyprland

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/Hyprland#4513]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 791e1b96b3cd12d56648b3ce7ffb0832eba2b37d dirty (internal: minor header cleanup).
Date: Mon Jan 22 20:32:34 2024
Tag: v0.34.0-59-g791e1b96

flags: (if any)


System Information:
System name: Linux
Node name: LEGION-Mathis
Release: 6.7.0-arch3-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hycov by DreamMaoMao ver 0.1
  hyprbars by Vaxry ver 1.0
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashed after I pressed a tab in a group bar. It does not always happen.

### How to reproduce

Either close a window in a group or change the active window inside that group. I've had both crash Hyprland.

### Crash reports, logs, images, videos

[hyprlandCrashReport107069.txt](https://github.com/hyprwm/Hyprland/files/14026583/hyprlandCrashReport107069.txt)

**Comment by MathisP75** [comment]
Here is another crash report. This one happened when closing a window inside a group I think, while the other happened while clicking a group bar tab.
[hyprlandCrashReport123868.txt](https://github.com/hyprwm/Hyprland/files/14026648/hyprlandCrashReport123868.txt)

**Comment by MathisP75** [comment]
Just to show that it happens without hycov:
[hyprlandCrashReport1050.txt](https://github.com/hyprwm/Hyprland/files/14027800/hyprlandCrashReport1050.txt)

**Comment by BackHDLP** [comment]
I'm getting this too. 
I opened kitty, made it a group, opened kitty 2 more times which were automatically part of the group, hit the killactive keybind, [crash](https://github.com/hyprwm/Hyprland/files/14063472/hyprlandCrashReport2204.txt). 
Repeat but close kitty by exiting the shell, [crash again](https://github.com/hyprwm/Hyprland/files/14063447/hyprlandCrashReport2192.txt).


#### `hyprctl version`
```
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```
#### `uname -a`
```
Linux gentoo 6.7.1-gentoo-dist #1 SMP PREEMPT_DYNAMIC Sat Jan 20 14:14:01 -00 2024 x86_64 AMD Ryzen 5 5500U with Radeon Graphics AuthenticAMD GNU/Linux
```

**Comment by MathisP75** [comment]
It seems like this has something to do with Hyprbars

**Comment by Staksor** [comment]
> It seems like this has something to do with Hyprbars

It seems you're correct. Removing hyprland-plugins which contains the hyprbars plugin with `hyprpm remove hyprland-plugins` solved the issue for me.

**Comment by izmyname** [comment]
Should it be closed or moved to hyprland-plugins repo?
