### ISSUE TITLE
Allow Floating Windows To Revert To Original Position After Un-Fullscreening

### ISSUE THREAD

**Issue by PacificViking** [hyprwm/Hyprland#4516]
### Description

As of v0.34.0, when a floating window (dragged so half of it is outside the display) is put into fullscreen and un-fullscreened, it reverts to its original position. This is no longer true following commit https://github.com/hyprwm/Hyprland/commit/813af393f1b61ecd0105e126681986e58e73ffee .

Judging from the name of the commit, I suspect this may be intended (thus the feature request). If this is the case, is it possible to add an option to toggle this behavior? I use this to multitask games that take up the entire screen. Thank you!

**Comment by bvr-yr** [comment]
duplicate #4388
