### ISSUE TITLE
input-leap client (libei) captures screen enter / leave, but does not update cursor or issue keypresses

### ISSUE THREAD

**Issue by bennypowers** [hyprwm/Hyprland#4518]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

an input-leap server, using libei, is running on a fedora 39 GNOME desktop

when connecting to that server from hyprland, the input-leap log shows that the client is aware when the mouse pointer enters and leaves the screen, but the cursor does not move on the client screen, and no keypresses are entered into app windows

### How to reproduce

0. the gentoo ebuild for input-leap-9999 is broken atm, but i used it to get all the dependencies (USE libei globally).
1. on the client, [build input-leap from source](https://github.com/input-leap/input-leap/wiki/Building-on-Linux)
  ```sh
  INPUTLEAP_BUILD_LIBEI=ON ./clean_build.sh && sudo cmake --install build
  ```
2. run input-leap and connect to the server
3. move the server's pointer to the appropriate screen edge

### Crash reports, logs, images, videos

observe the client's input-leap log:

```
connected to server
[2024-01-23T20:20:21] INFO: entering screen
[2024-01-23T20:20:21] INFO: clipboard was updated
[2024-01-23T20:20:21] INFO: clipboard was updated
[2024-01-23T20:20:27] INFO: leaving screen
[2024-01-23T20:20:27] INFO: entering screen
[2024-01-23T20:20:27] INFO: leaving screen
[2024-01-23T20:25:50] INFO: entering screen
[2024-01-23T20:25:51] INFO: leaving screen
```

and the server's input-leap log:

```
[2024-01-23T20:42:51] INFO: switch from "server" to "client" at 1,1027
[2024-01-23T20:42:51] INFO: leaving screen
      ... | [0;1;39mDEBUG[0m | dispatching ei_pointer.motion_relative() on object 0xff00000000000004
      ... | [0;1;39mDEBUG[0m | queuing pending event type EI_EVENT_POINTER_MOTION (300)
      ... | [0;1;39mDEBUG[0m | dispatching ei_device.frame() on object 0xff00000000000003
      ... | [0;1;39mDEBUG[0m | queuing event type EI_EVENT_FRAME (100)
```

**Comment by killown** [comment]
if this leap thing requires org.freedesktop.portal.RemoteDesktop, hyprland still has no support

**Comment by bennypowers** [comment]
https://github.com/emersion/xdg-desktop-portal-wlr/issues/278
