### ISSUE TITLE
Nixos installation issue in 22.05

### ISSUE THREAD

**Issue by sarveshrulz** [hyprwm/Hyprland#452]
Not using flake,
Latest nixos (22.05) has wayland version 1.20.0, I got an error saying I need at least 1.21.0 so I created a nixpkgs overlay Ty use it from unstable repos, then after hours of compiling I got another similar error for libdrm. I have those chacix lines in my configuration. I have decent specs in my laptop and it's been like 8h 😂. Any better way?

**Comment by viperML** [comment]
Upgrade to nixos-unstable, we don't support nixos-22.05
