### ISSUE TITLE
Hyprland + Nvidia cursor lag issue

### ISSUE THREAD

**Issue by SarjyantShrestha** [hyprwm/Hyprland#4523]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When I export  these variables in the hyprland config, applications like chrome, discord and vscode uses NVIDIA (which is what I want) but I get cursor stutter issue while navigating in any of these applications. There's also like a "lag spike" when  I move my cursor from an application that uses NVIDIA (eg chrome) and another one that don't (Kitty).
```
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia 
```
This problem didn't occur when I completely disable intel and only used NVIDIA on a second display.

### How to reproduce

Export these variables on hyprland config.

```
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia 
```

**Comment by vaxerski** [comment]
does it happen on sway

**Comment by SarjyantShrestha** [comment]
> does it happen on sway

yes it does.

**Comment by SarjyantShrestha** [comment]
> does it happen on sway

I haven't been able to test it on sway because it says "propriety nvidia drivers are in use"
I can only run sway --unsupported-gpu

**Comment by SarjyantShrestha** [comment]
> Idk if sway has an env import system or how it works, but I don't think the ones you tried would work there. You can just run a quick test from the tty with: `LIBVA_DRIVER_NAME=nvidia GBM_BACKEND=nvidia-drm __GLX_VENDOR_LIBRARY_NAME=nvidia sway --unsupported-gpu`.

It worked but yes I got the same issue as explained above.

**Comment by sewerslider** [comment]
> > does it happen on sway
> 
> I haven't been able to test it on sway because it says "propriety nvidia drivers are in use" I can only run sway --unsupported-gpu
> 
> I don't know how to export these on sway env = LIBVA_DRIVER_NAME,nvidia env = GBM_BACKEND,nvidia-drm env = __GLX_VENDOR_LIBRARY_NAME,nvidia
> 
> I tried
> 
> ```
> exec export LIBVA_DRIVER_NAME,nvidia
> exec export GBM_BACKEND,nvidia-drm
> exec export __GLX_VENDOR_LIBRARY_NAME,nvidia 
> ```
> 
> inside sway config but that don't seem to work.
> 
> I appreciate your guidance.

AFAIK, sway just use environment variable so it's something like:
`export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME =nvidia`
put this in your shell config file or somewhere like /etc/environment

**Comment by SarjyantShrestha** [comment]
> > > does it happen on sway
> > 
> > 
> > I haven't been able to test it on sway because it says "propriety nvidia drivers are in use" I can only run sway --unsupported-gpu
> > I don't know how to export these on sway env = LIBVA_DRIVER_NAME,nvidia env = GBM_BACKEND,nvidia-drm env = __GLX_VENDOR_LIBRARY_NAME,nvidia
> > I tried
> > ```
> > exec export LIBVA_DRIVER_NAME,nvidia
> > exec export GBM_BACKEND,nvidia-drm
> > exec export __GLX_VENDOR_LIBRARY_NAME,nvidia 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > inside sway config but that don't seem to work.
> > I appreciate your guidance.
> 
> AFAIK, sway just use environment variable so it's something like:
> 
> ```
> export LIBVA_DRIVER_NAME=nvidia
> export GBM_BACKEND=nvidia-drm
> export __GLX_VENDOR_LIBRARY_NAME=nvidia
> ```
> 
> put this in your shell config file or somewhere like /etc/environment

I already did what @tchofy said but got the same lag.

**Comment by sewerslider** [comment]
@SarjyantShrestha This is just a shot in the dark but have you tried putting
``` 
env = WLR_NO_HARDWARE_CURSORS,1 
```
inside your Hyprland config?

**Comment by chermnyx** [comment]
It sounds like an NVIDIA bug with multi-gpu systems on wayland (it should be fixed on drivers 550 with the environment variable `OGL_DEDICATED_HW_STATE_PER_CONTEXT=ENABLE_ROBUST`)

**Comment by bddvlpr** [comment]
Got this issue on 550.100 and onwards, solved by using setting `no_hardware_cursors = true` in the config under `cursor`.

**Comment by izmyname** [comment]
Did you try 555? How's it?

**Comment by SarjyantShrestha** [comment]
> Did you try 555? How's it?

Yeah it's runs well now.

**Comment by wilville** [comment]
> It sounds like an NVIDIA bug with multi-gpu systems on wayland (it should be fixed on drivers 550 with the environment variable `OGL_DEDICATED_HW_STATE_PER_CONTEXT=ENABLE_ROBUST`)

This works amazingly it feels smooth as butter using intel as main gpu. Thanks
