### ISSUE TITLE
I got some bug report here, please consider them 

### ISSUE THREAD

**Issue by antkss** [hyprwm/Hyprland#4529]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

there some issues about running application like ida or ghidra, it's lag and freeze sometime 

https://github.com/hyprwm/Hyprland/assets/88892713/1a3a24d5-3dcc-49be-82c9-a729892a4f1f

### How to reproduce

can you fix them, i don't want them appear again

### Crash reports, logs, images, videos

[report.txt](https://github.com/hyprwm/Hyprland/files/14054181/report.txt)

**Comment by kossLAN** [comment]
Not very descriptive, also just to add my input running on nixos (both ghidra & idafree), I experience no such issues on latest commit of hyprland. Likely, this is not a hyprland issue.

**Comment by antkss** [comment]
how about cursor lagging on hyprland?, how can i know exactly what's make these bugs ??

**Comment by romanstingler** [comment]
plugin an external monitor so the GPU driver clocks the GPU higher and see what happens
