### ISSUE TITLE
Disabling laptop display (eDP-1) causes either render problems or crash

### ISSUE THREAD

**Issue by eneshecan** [hyprwm/Hyprland#453]
Hi, thanks a lot for the great compositor!

I have two external monitors connected via a docking station and I mostly don't use my laptop display. With the following config, I get two empty monitors with the default wallpaper and it seems that non of the `exec-once` apps are run.
```
monitor=eDP-1,disable
monitor=DP-7,1920x1080@60,0x0,1
monitor=DP-4,1920x1200@59.95,1920x0,1
```

If I were to enable my laptop display before Hyprland starts, it works. However, disabling it while Hyprland is running results in a crash
```
monitor=eDP-1,3840x2160@59.997,0x1080,2
monitor=DP-7,1920x1080@60,0x0,1
monitor=DP-4,1920x1200@59.95,1920x0,1
```

Core dump is attached.
[dump.txt](https://github.com/hyprwm/Hyprland/files/9232969/dump.txt)

**Comment by vaxerski** [comment]
Always compile manually when giving coredumps. This one is unusable.

**Comment by eneshecan** [comment]
Ah, sorry. Here is the dump after installing `hyprland-git`:
[dump.txt](https://github.com/hyprwm/Hyprland/files/9233431/dump.txt)

**Comment by eneshecan** [comment]
Here is the log after disabling the laptop monitor (eDP-1) on startup while facing default empty screens:
[log.txt](https://github.com/hyprwm/Hyprland/files/9245558/log.txt)

**Comment by vaxerski** [comment]
please check with the recent commits.

**Comment by eneshecan** [comment]
I'll check when I get home. Thanks!

**Comment by godalming123** [comment]
When I disable my laptop monitor the display is still on but my mouse cannot move to it after a hyprland restart when built from latest (v0.9.1) with nix os

**Comment by vaxerski** [comment]
please use the latest commit, not release

**Comment by godalming123** [comment]
That is with latest commit built with https://github.com/hyprwm/Hyprland/wiki/Nix#without-flakes also upon further testing:
1. If I disable my main monitor (hdmi plugged into laptop) the hyprland logo still shows despite nothing else showing and hyprland behaving as if the monitor is nonexistent
2. If I disable my laptop monitor my wofi breaks giving error:
   ```
   (wofi:25046): Gdk-CRITICAL **: 18:30:16.709: ../gdk/wayland/gdkdisplay-wayland.c:1328: mmap'ping shared memory file failed: Invalid argument
   fish: Job 1, 'wofi --show drun' terminated by signal SIGSEGV (Address boundary error)
   ```

**Comment by godalming123** [comment]
The same behavior (main monitor showing hyprland logo but unusable) happens when my main monitor is disabled and I start hyprland with it unplugged then plug it in

**Comment by vaxerski** [comment]
> The same behavior (main monitor showing hyprland logo but unusable) happens when my main monitor is disabled and I start hyprland with it unplugged then plug it in

If by "main monitor" you mean the laptops' monitor, then you might be right and this will NOT be fixed. You're trying to run a compositor without any output, what do you expect will happen?

**Comment by godalming123** [comment]
By main monitor I mean HDMI monitor

**Comment by fufexan** [comment]
I've just tested this, it works fine for me. Using latest commit with the flake.

Can you post `realpath $(which Hyprland)` @godalming123 ?

**Comment by godalming123** [comment]
> I've just tested this, it works fine for me. Using latest commit with the flake.
> 
> Can you post `realpath $(which Hyprland)` @godalming123 ?

```
in /home/whatever > realpath $(which Hyprland)                                     < at 19:09 at 03/08/22
/nix/store/45f1ad1bz4wwnix535zb1rphzwf53sfc-hyprland-0.9.1beta+date=1970-01-01/bin/Hyprland
in /home/whatever >                                                                < at 19:10 at 03/08/22
```

**Comment by godalming123** [comment]
Also how did you start hyprland I start it from tty

**Comment by fufexan** [comment]
TTY as well. You seem to be having the latest version, so idk why it's not working.

**Comment by godalming123** [comment]
I was disabling the monitor by setting the scaling to 0 instead of using the disable option @vaxerski is there a warning when you set scaling to 0 or is it just that the warning cannot show due to the scaling? As I think more warnings is important to prevent silly issues like this. But when I disable my laptop monitor using the official docs method I still cannot run apps

**Comment by vaxerski** [comment]
> I was disabling the monitor by setting the scaling to 0 instead

oh my fucking god, yeah I guess I should add a warning for idiots.

> But when I disable my laptop monitor using the official docs method I still cannot run apps on my main monitor

share your config.

**Comment by godalming123** [comment]
Here is my config:
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/9254406/hyprland.txt)

**Comment by vaxerski** [comment]
hm, all looks good to me. Weird, I can't reproduce.

**Comment by godalming123** [comment]
Is there a way to try and see the error message the programs return I've tried:
```
Hyprland; sleep 1 & alacritty
```
But I get no text when exiting hyprland for the result off the alacritty process

**Comment by vaxerski** [comment]
> `Hyprland; sleep 1 & alacritty`

I don't think thats even valid bash.

Probably, redirect the alacritty output to a file.

**Comment by godalming123** [comment]
Will try but firstly here is the log when I open hyprland try to open alacritty a few times and then exit with my laptop monitor disabled
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9254546/hyprland.log)

**Comment by vaxerski** [comment]
everything seems in order.

**Comment by godalming123** [comment]
Redirecting the alacrity output doesn't work for me I run into a few issues:
1. Alacrity can't be ran at the same te as hyprland because at that point the Wayland environment variables are not set
2. I cannot find a way to use sleep to make alacrittys execution delayed I still get the same result in the file
3. So I decide to run `Hyprland & ./my-script.sh` where my script will sleep for a second to wait for hyprland to launch then start alacritty and put the result in a log file
4. This doesn't appear to work I still get the same error maybe it's something to do with my script remembering the environment variables from when it was launched. Is there a way to update environment variables at runtime? And is it possible to put the result of a command when it is executed with exec to the hyprland logfile it would be much easier.

**Comment by vaxerski** [comment]
`ENV_VAR=val myprogram` doesnt work? No, you cant append it to the logfile.

**Comment by eneshecan** [comment]
I just checked with the latest git version and confirmed that the issue still persists.

Let me explain what I tried again if helps.

* If I disable my laptop monitor before Hyprland starts, nothing renders except the default Hyprland background, no crash whatsoever
* If I enable my laptop monitor before Hyprland starts, it works fine
  * Disabling laptop monitor afterward while it's running mostly works but I just ran into a crash after several trials [coredump.txt](https://github.com/hyprwm/Hyprland/files/9255244/coredump.txt)

My monitors:
```
Monitor eDP-1 (ID 0):
	3840x2160@59.997002 at 0x1080
	active workspace: 1 (1)
	reserved: 0 40 0 0
	scale: 2.00
	transform: 0
	active: no

Monitor DP-4 (ID 1):
	1920x1200@59.950001 at 1920x0
	active workspace: 5 (5)
	reserved: 0 40 0 0
	scale: 1.00
	transform: 0
	active: no

Monitor DP-7 (ID 2):
	1920x1080@60.000000 at 0x0
	active workspace: 2 (2)
	reserved: 0 40 0 0
	scale: 1.00
	transform: 0
	active: yes
```

My display config:
```
monitor=eDP-1,3840x2160@59.997,0x1080,2
#monitor=eDP-1,disable
monitor=DP-7,1920x1080@60,0x0,1
monitor=DP-4,1920x1200@59.95,1920x0,1
```

**Comment by vaxerski** [comment]
As I've said, I cannot reproduce this on my desktop. However, I'll try to find an HDMI cable and try it on my laptop tomorrow.

**Comment by eneshecan** [comment]
No worries, thanks a lot for looking into it.

**Comment by eneshecan** [comment]
No worries, thanks a lot for looking into it.

**Comment by vaxerski** [comment]
tested with a huge-ass OLED TV and a laptop, cannot reproduce. Everything works as expected.

**Comment by eneshecan** [comment]
Maybe this is about the refresh rate. One of my monitors default is 59.997 but I am sure there are more digits if you want to be exact. Should I increase the decimal precision?

**Comment by vaxerski** [comment]
no, hyprland finds the adequate refresh rate anyways. you can put in 60 and it will find the first within 1Hz

**Comment by vaxerski** [comment]
check with recent commits.

**Comment by eneshecan** [comment]
I will check soon. Thanks!

**Comment by eneshecan** [comment]
Finally works! The only issue for me is reenabling the laptop monitor doesn't work. I also tried to enable it with wdisplays and that caused a crash. Here are the logs and dump if helps;

[dump.txt](https://github.com/hyprwm/Hyprland/files/9303675/dump.txt)
[logs.txt](https://github.com/hyprwm/Hyprland/files/9303676/logs.txt)

However, I believe those issues don't belong here and we can close this as it's fine for me.

Thanks a lot!

**Comment by vaxerski** [comment]
open a new issue please :-)
