### ISSUE TITLE
PREFIX value doesn't seem to propagate well enough when packaging

### ISSUE THREAD

**Issue by pkreuzt** [hyprwm/Hyprland#4531]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
legacyrenderer

```

</details>

### Bug or Regression?

Bug

### Description

Built Hyprland for Debian Testing (for own use only) with PREFIX=/usr and a local DESTDIR for packaging, On installed package, hyprpm has similar behaviour to #4082 . In my case, the problem was hyprland.pc still pointing to /usr/local as prefix. Once this was corrected, it worked fine. Somehow cmake believed that prefix was still /usr/local when creating hyprland.pc.

### How to reproduce

Build with prefix different than default /usr/local

**Comment by fufexan** [comment]
Did you build using CMake (with the Makefile) or using Meson?

**Comment by pkreuzt** [comment]
With the Makefile.

**Comment by fufexan** [comment]
I'll look into it, but it might take a while. In the meantime you could use Meson to build Hyprland, as that's known to work properly.

**Comment by vaxerski** [comment]
issue is here:
https://github.com/hyprwm/Hyprland/blob/4b4bd90b1450cbfc01d9ac429363cc7cecd6be8b/CMakeLists.txt#L14-L15

cmake prefix is never set to the PREFIX env in the makefile.

Probably should add `-DCMAKE_INSTALL_PREFIX:STRING=${PREFIX}` in the makefile to cmake config commands.

**Comment by fufexan** [comment]
@pkreuzt can you try this patch?
[patch.txt](https://github.com/hyprwm/Hyprland/files/14097233/patch.txt)

**Comment by pkreuzt** [comment]
Tried your patch and it seems to set the prefix fine on hyprland.pc

On a sidenote, I've not hit (yet) the above referenced issue about mismatched packaged headers. At least with hyprland.pc path correctly set. Actually I updated my installed (official) plugins today with hyprpm without an issue.

**Comment by vaxerski** [comment]
it would happen if you for example:
 - install an official package (e.g. hyprland on arch)
 - clone hyprland from git
 - install manually

**Comment by vaxerski** [comment]
e65f52bf2d6abb001c402c8302ac7003da8cd06d
