### ISSUE TITLE
Hyprland is unusable without waybar and kitty. make them dependencies

### ISSUE THREAD

**Issue by deshpandetanmay03** [hyprwm/Hyprland#4534]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Installed hyprland on arch linux with pacman. cannot open terminal and there is no topbar. this can be solved by installing kitty (default terminal) and waybar by default

### How to reproduce

install hyprland on arch linux without having kitty or waybar

**Comment by ErrorNoInternet** [comment]
How is this a Hyprland issue? It's just that Kitty is specified as a default terminal. You can easily change this in the configuration.

> Installed hyprland on arch linux

You went through all the hassle of installing Arch already, setting up so many things, and you want Waybar and Kitty to be installed alongside Hyprland automatically?

How did you install Hyprland? From a TTY? Edit the configuration from a TTY.

**Comment by tchofy** [comment]
This would create another issue - people who don't want or don't like kitty and waybar, having them as hard dependencies and having to `-Rdd` them. At best they could be listed as optional dependencies.

And Hyprland's auto generated config doesn't execute waybar or add any keybindings to do so, just having it installed wouldn't give you a bar.

**Comment by vincentaxhe** [comment]
waybar maybe, kitty not necessary, just a terminal.And bar is a just a decoration, Hyprland is not meant to bulid adaptable only to waybar.
leave users to decide, hyprland wiki give advices about companion softwares.

**Comment by Arajtav** [comment]
I'm using Hyprland without waybar and I'm fine. I don't think it's necessary. If You can install Hyprland You can install these things with one comnand. Not everyone uses kitty and not everyone needs waybar.

**Comment by deshpandetanmay03** [comment]
When i installed hyprland it said i could run mod q for kitty with no indication it wasn't installed. Wofi want there either. Without installing them be default with hyprland the first launch is completely unusable

**Comment by deshpandetanmay03** [comment]
> This would create another issue - people who don't want or don't like kitty and waybar, having them as hard dependencies and having to `-Rdd` them. At best they could be listed as optional dependencies.
> 
> And Hyprland's auto generated config doesn't execute waybar or add any keybindings to do so, just having it installed wouldn't give you a bar.

This may become a problem. A fix can be that we make it an optional dependency or give an indication on the installation page that kitty, waybar and wofi will be required for first launch to be usable https://wiki.hyprland.org/Getting-Started/Installation/

**Comment by ErrorNoInternet** [comment]
> When i installed hyprland it said i could run mod q for kitty with no indication it wasn't installed. Wofi want there either. Without installing them be default with hyprland the first launch is completely unusable

And what about Arch Linux itself?

**Comment by vaxerski** [comment]
it's not.
