### ISSUE TITLE
[XWAYLAND, force_zero_scaling] Steam and some games are terrified of my mouse

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#4536]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 754eaf5b8b65c9764abe67ec2d599036cd51e381 dirty (pluginapi: fix hooks with negative rip offsets).
Date: Wed Jan 24 14:53:18 2024
Tag: v0.34.0-61-g754eaf5b

flags: (if any)


System Information:
System name: Linux
Node name: apg
Release: 6.7.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c2) (prog-if 00 [VGA controller])
37:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hycov by DreamMaoMao ver 0.1
```

</details>

### Bug or Regression?

Regression

### Description

When I move my mouse to a floating Steam window (also happens with Ori and the Will of the Wisps), the window moves down-right to escape the mouse. See the video attached for a better description.

I am using force zero scaling for Xwayland, and focus follows mouse.

### How to reproduce

1. open a floating Steam window
2. try to move the mouse onto it

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/44881120/71771784-79a4-4c8b-9944-20d2f0dd14a2

**Comment by vaxerski** [comment]
take a shower. Your odor is scaring them.

On a real note, does this happen without scaling?

**Comment by Rabcor** [comment]
Same issue here, exact same issue, also if it's floating and i'm tabbed out of it, it'll fly off the screen to infinity and only way to get it back is to restart steam entirely.

I do have 

    force_zero_scaling = true

**Comment by TheSunCat** [comment]
It does not happen with `force_zero_scaling` disabled.
<br><br>
> take a shower. Your odor is scaring them.
<details>
<summary>Click to see my (offtopic) response</summary>

![image](https://github.com/hyprwm/Hyprland/assets/44881120/694fba22-3397-476d-ba12-6027f6b0d6e9)
</details>

**Comment by vaxerski** [comment]
ping me tomorrow

**Comment by SDA-31** [comment]
Same happens to me
Telegram's fullscreen mode is impossible to use (it twitches very hard)
![image](https://github.com/hyprwm/Hyprland/assets/80205117/a590cbcd-9b17-43f8-8772-8bc0ccae548b)

**Comment by vaxerski** [comment]
check with above

**Comment by TheSunCat** [comment]
Thanks, that fixed it!
