### ISSUE TITLE
High CPU usage & low GPU frequency in GTK context menu and some qt6 apps

### ISSUE THREAD

**Issue by shvedes** [hyprwm/Hyprland#4538]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When I open the context menu in Firefox or Thunar and hover over it, the CPU usage increases significantly and the CPU temperature rises significantly, while the GPU frequency drops to a minimum. The same thing happens with the OBS window when the cursor is on preview. If you run Firefox with GDK_BACKEND=x11, then there is no such problem. I tried a lot: installed the git version of Hyprland and XDPH, mesa and other drivers, removed variables related to graphics, etc., reinstalled the system. Nothing helped

Edit: same issue with Telegram context menu. I have no idea why this happening

```
env = VDPAU_DRIVER,radeonsi
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,
env = GDK_BACKEND,wayland
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC,1
env = SDL_VIDEODRIVER,wayland
env = _JAVA_AWT_WM_NONREPARENTING,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
```

### How to reproduce

I have not yet seen a single open issue with such a problem. Perhaps this is just with my system and its incorrect settings that I have not found yet

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14067369/hyprland.log)
[Video](https://youtu.be/Xn7XoLDF8no)

**Comment by shvedes** [comment]
Works well with 0.33 ver

**Comment by vaxerski** [comment]
`git bisect` then please

**Comment by malcolmrebughini** [comment]
I was experiencing this issue in v0.34 but it seems fixed after updating to v0.35. I think this issue can be closed.

**Comment by romanstingler** [comment]
@MightyPlaza could you please close this <3

**Comment by shvedes** [comment]
The more window rules are applied, the stronger the lags in the conditions described above. For example, my main config, which imported a separate file with 300 lines of rules, caused the system to lag very much. I decided to try to write it from scratch, thinking that the problem might be due to a specific application, and noticed that literally a few rules for several applications are enough for the system to start lagging (as in the attached video). Again, everything works fine on version 0.33, but not on versions higher

[Video](https://www.youtube.com/watch?v=ClzY5JOQ-nk)

**Comment by shvedes** [comment]
> can't repro on -git.

What do you mean?

**Comment by shvedes** [comment]
> can't repro on -git.

Same problem on -git for me

**Comment by shvedes** [comment]
> give your config then

https://pastebin.com/1zmRwHMz

**Comment by shvedes** [comment]
any news?

**Comment by vaxerski** [comment]
I was busy, that is the news

**Comment by vaxerski** [comment]
pasted your windowrules, can't repro. cpu quiet.

**Comment by shvedes** [comment]
sadly
