### ISSUE TITLE
Open dialog of some Electron apps aren't floating

### ISSUE THREAD

**Issue by FlysoftBeta** [hyprwm/Hyprland#4541]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 72987dee88a0359d42af9f3064a62b934dcd7be0 dirty (opengl: rassert false on lost context).
Date: Fri Jan 26 02:26:10 2024
Tag: v0.34.0-62-g72987dee

flags: (if any)


System Information:
System name: Linux
Node name: flysoft
Release: 6.7.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] [10de:1f08] (rev a1) (prog-if 00 [VGA controller])
        DeviceName: VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Open dialog of some Electron apps like VSCode aren't floating, other programs like firefox works pretty fine. 

Also checked `hyprctl clients`, and this dialog doesn't have any special class for me to match. 

Doesn't know if this is a hyprland issue or an electron issue.

### How to reproduce

Use open file/open folder in VSCode.

### Crash reports, logs, images, videos

<img width="811" alt="2024-01-27_15-02" src="https://github.com/hyprwm/Hyprland/assets/49718840/e4e60fd6-0f37-4f1a-b33d-1fc23501cb3b">
<img width="592" alt="2024-01-27_15-02_1" src="https://github.com/hyprwm/Hyprland/assets/49718840/16248a27-a47f-4807-bf32-4e22b9935ba9">

**Comment by vaxerski** [comment]
this is an issue with electron
