### ISSUE TITLE
Don't stretch Hypr-chan

### ISSUE THREAD

**Issue by ArtemSmaznov** [hyprwm/Hyprland#4543]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 754eaf5b8b65c9764abe67ec2d599036cd51e381 dirty (pluginapi: fix hooks with negative rip offsets).
Date: Wed Jan 24 08:53:18 2024
Tag: v0.34.0-61-g754eaf5b

flags: (if any)


System Information:
System name: Linux
Node name: izumi
Release: 6.7.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:13:51 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

I have an ultra-wide monitor and about a month ago after an update hyprland started stretching the hypr-chan wallpapers instead of filling them like it was before.

### How to reproduce

1. Have a non-standard aspect ratio monitor (maybe switching an existing one to vertical orientation will do the same - I have not tested this)
2. Don't set the wallpaper using other tools
3. Login to hyprland
4. Poor Hypr-chan

### Crash reports, logs, images, videos

I have 2 monitors - a regular one above which looks fine and an untra-wide one below which stretches the background:
![screenshot-2024-01-27_10-59-19](https://github.com/hyprwm/Hyprland/assets/31800376/e2f76b92-0702-4d94-b62b-eeafed5da0b5)

**Comment by vaxerski** [comment]
it shouldn't do that. You selected regression, can you bisect the regression?

**Comment by ArtemSmaznov** [comment]
@vaxerski 6b92144f15117f9f7d93fe9867d6ec849d9abce1 is the first bad commit

**Comment by vaxerski** [comment]
oops, that must've been a mistake.
