### ISSUE TITLE
hyprpm: force rebuild

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#4547]
### Description

I just updated to latest git and had a few plugins that needed rebuilding due to internal hyprland changes. I had to go fucking around with the state.toml files to invalidate the hashes so I could rebuild the plugins. Gimmie a flag.
(Would also be helpful when doing dev from a local git dir)

**Comment by vaxerski** [comment]
odd that hyprpm didn't detect that itself, though...?

**Comment by zakk4223** [comment]
Yeah, it never rebuilds on git hash version changes for me, I think I figured out why. I'm using hyprland-git AUR, which installs headers into /usr/include/hyprland

If you update hyprland-git, restart hyprland and then run hyprpm update: The on-disk headers in /usr/include match the running  hyprland version. So it doesn't trigger a rebuild of plugins.

If you run hyprpm update BEFORE you restart hyprland, it detects the version mismatch. And then clones hyprland, runs make installheaders and then fails after detecting duplicate headers. Now hyprpm is broken forever since there are headers in both /usr/include and /usr/local/include AND hyprland.pc has been updated to point to /usr/local/include.

I think the forced update will also break in the same way.

**Comment by vaxerski** [comment]
should be fixed.

**Comment by zakk4223** [comment]
Now it detects the plugins were built with a different version of the headers, flags stuff as needing a rebuild. And then downloads the headers and breaks everything with the duplicate header issue.

Is it ever going to end well to download headers if there are existing headers in /usr/include?

**Comment by vaxerski** [comment]
hm. True.

We should... hm. Maybe we should just find other .pc files and remove them if managed by hyprpm?

**Comment by zakk4223** [comment]
If there are headers in /usr/include you should just assume those are system/user managed and not try to download new headers (since it will break hyprpm anyways). If the version doesn't match the running Hyprland instance just exit with an error message and tell the user to sort out whatever is broken.

Headers in /usr/local/include I guess you could update those, although I dunno how that works with package managers that install the headers there already. Not any worse than what's already being done, tho.

**Comment by vaxerski** [comment]
could be. Requires some thinking through, though.

**Comment by lisuke** [comment]
fixed.

**Comment by zakk4223** [comment]
hyprpm update -f will still break if you have headers in /usr/include. But I'll wait for braining to happen; there must be some condition/use case I'm just ignorant of that makes it more complicated than it seems to me.

**Comment by zakk4223** [comment]
Also the latest commit no longer updates the global state.toml, so the hash in there never changes. Every run of hyprpm update recompiles all plugins
