### ISSUE TITLE
Certain window sizes cause artifacts in text

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#4548]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 754eaf5b8b65c9764abe67ec2d599036cd51e381 dirty (pluginapi: fix hooks with negative rip offsets).
Date: Wed Jan 24 14:53:18 2024
Tag: v0.34.0-61-g754eaf5b

flags: (if any)


System Information:
System name: Linux
Node name: apg
Release: 6.7.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c2) (prog-if 00 [VGA controller])
37:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hycov by DreamMaoMao ver 0.1
```

</details>

### Bug or Regression?

Regression

### Description

At certain window sizes, text rendering gets wonky and it makes it hard to read. Here are a few examples on Armcord; I have also seen it in foot:

![image](https://github.com/hyprwm/Hyprland/assets/44881120/0effa469-112f-41c1-a6cd-fee13247f433)
![image](https://github.com/hyprwm/Hyprland/assets/44881120/ae298661-de59-47e4-a865-befc1a0d8d0e)

### How to reproduce

/shrug no idea
It notice it most often when a window is 1011 pixels wide (using 1.25 scaling on a 1600x1440 display, with one window tiled on each side, this is the window size that I always get), and it seems to happen to random characters. It goes away if I resize the window even by a single pixel. If I align another of the same character vertically, the new character also gets the bug (see second screenshot).

**Comment by vaxerski** [comment]
after effect of #4225

For oversized we could clip the last column / row come to think of it.

**Comment by TheSunCat** [comment]
That would explain why it's only started happening recently. It makes text really hard to read when it happens, I'm all for losing one pixel on the edge and not have this artifact :)
