### ISSUE TITLE
movewindow and movefocus behaviour when fullscreen

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#455]
The behaviour of these two functions in combination with a fullscreen window is quite confusing.
I think movewindow should be disabled if a window is shown fullscreen.
If i could choose how movefocus behaves with a fullscreen window, i would vote for a fullscreen-mode like behaviour,
where the window that gains focus becomes the new fullscreen window.
If that is not desired, movefocus should be disabled aswell i guess.
What do you think?

**Comment by Dickby** [comment]
also a function for moving a window to another workspace, without moving focus to that workspace would make sense.

**Comment by vaxerski** [comment]
> also a function for moving a window to another workspace, without moving focus to that workspace would make sense.

`movetoworkspacesilent` exists

**Comment by Dickby** [comment]
nice, Thanks!

**Comment by vaxerski** [comment]
done something about that in fff7534721738b49f8338537bde97d1443391dba and movewindow seems to work ok.

**Comment by Dickby** [comment]
Thanks a lot!
Keep up the good work, it's very much appreciated!
