### ISSUE TITLE
Wrong workspace name when focus window in a closed special workspace

### ISSUE THREAD

**Issue by PostCyberPunk** [hyprwm/Hyprland#4556]
### Hyprland Version

```sh
 hyprctl version
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82c
d54322f
42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

### Bug or Regression?

Bug

### Description

```
focus_on_activate = true
```
when some window take focus in a specialWorkspace.it will create a new specialWorkspace with wrong name
```
 hyprctl -j monitors

    ...
    "specialWorkspace": {
        "id": -93,
        "name": "special:special:Aspb"
    },
```
the actual  focused window is in the right workspace
```
 hyprctl -j activewindow
{
    "address": "0x583084965ff0",
    "mapped": true,
    "hidden": false,
    "at": [58, 74],
    "size": [1804, 938],
    "workspace": {
        "id": -90,
        "name": "special:Aspa"
    },
```

### How to reproduce

this only happens when the  window is in a special workspace ,and this workspace is turned off,when this window take focus,a special special workspace will be created

**Comment by vaxerski** [comment]
great title.

Anyways can you list exact steps to reproduce and not paraphrase?

**Comment by PostCyberPunk** [comment]
i am so sorry about the title...
1. open firefox in a special workspace.then close this special workspace
2. open terminal in a normal workspace ``git-credential-manager github login`` ,choose sign-in web browser(or whatever operation that can open a tab in that firefox window )
3. Instead of opening the special workspace which firefox is in, it opens a blank special workspace.in this blank special workspace, open a terminal ``hyprctl -j monitors`` returns
```
    "specialWorkspace": {
        "id": -93,
        "name": "special:special:Aspb"
    },
```
4.  in the firefox's special workspace,``hyprctl -j activewindow`` returns
```
    "workspace": {
        "id": -90,
        "name": "special:Aspa"
    },
```

**Comment by PostCyberPunk** [comment]
here is my config about the special workspace
```
bind = $mainMod SHIFT, U, movetoworkspace, special:Aspa
bind = $mainMod CTRL, U, movetoworkspacesilent, special:Aspa
bind = $mainMod, U, togglespecialworkspace,Aspa
```

**Comment by PostCyberPunk** [comment]
![swappy-20240129-114142](https://github.com/hyprwm/Hyprland/assets/134976996/c19dcdfa-8845-4665-b2c1-d35d8ec7e9eb)
![swappy-20240129-114048](https://github.com/hyprwm/Hyprland/assets/134976996/183886bb-1937-4d64-abf3-2e2359419b59)
i think i found out why, the line 514 in Monitor.cpp ,normally we should do ,``togglespecialworkspace magic``,instead of that this line actually does ``togglespecialworkspace special:magic``
