### ISSUE TITLE
follow_mouse_click option

### ISSUE THREAD

**Issue by Vintodrimmer** [hyprwm/Hyprland#456]
Would it be possible to make it so the window isn't focused even if I click within it?
For example, in BSPWM this is done by setting

```
bspc config focus_follows_pointer false
bspc config click_to_focus none
```

Currently I'm using `follow_mouse=2` which is almost perfect, as I can interact with windows (e.g., scroll within them) using the mouse without losing keyboard focus of the window I need, but clicking on the window (e.g. to switch to the next song, or using mouse to copy tex by selecting it) still switches focus.

**Comment by vaxerski** [comment]
if I am understanding correctly, you want to be able to click on another window while the *keyboard* focus does not change, right?

**Comment by Vintodrimmer** [comment]
Exactly!

**Comment by vaxerski** [comment]
yall be multitasking hard

**Comment by Vintodrimmer** [comment]
I like my many monitors :)
Semi-related, is there any way to make mouse not jump to the center of the focused window?

**Comment by vaxerski** [comment]
> I like my many monitors :)

I have 3 and cant multitask like this

> Semi-related, is there any way to make mouse not jump to the center of the focused window?

no, but i can make it configurable

**Comment by vaxerski** [comment]
follow mouse 3 added in 338865e4334b5c60ba2657ff6ab7a069b8d7e19d, will not focus on click

**Comment by vaxerski** [comment]
added `general:no_cursor_warps` in 1edd66618f45a2e042260e4af81933d532e82394

**Comment by Vintodrimmer** [comment]
Thank you very much.
