### ISSUE TITLE
hyprpm: Do something about system headers

### ISSUE THREAD

**Issue by vaxerski** [hyprwm/Hyprland#4563]
### Description

cc @zakk4223 @DreamMaoMao @fufexan

We gotta do something about system headers being hash mismatched.

To me, it seems like the best option would be to clone headers, force compilation with our headers, then remove them.

Although, this seems like it could just break one time and cause a headache. Maybe it should be guarded behind a flag? (`--ignore-system-headers`)

Otherwise, we can reject to build/update as long as mismatched headers are present.

**Comment by fufexan** [comment]
Ok, but why remove the headers? We could just cache them in `$XDG_CACHE_HOME/hyprpm`.

**Comment by vaxerski** [comment]
we have to somehow make `pkg-config` not return the system headers. I don't think .pc files can have a "priority", though.

**Comment by fufexan** [comment]
You can set `PKG_CONFIG_LIBDIR`, from what I understand from the [manpage](https://linux.die.net/man/1/pkg-config).

**Comment by zakk4223** [comment]
pkg-config manpage says that is a colon separated list of directories to search, and then it searches system directories after that

**Comment by vaxerski** [comment]
great! so we can just append at the beginning our temp path and it should work. Top.

**Comment by fufexan** [comment]
Not really.

> the default is libdir/pkgconfig:datadir/pkgconfig where libdir is the libdir where pkg-config and datadir is the datadir where pkg-config was installed. 

If we set `PKG_CONFIG_LIBDIR` to our temp path it'll only search in there.

If you want to prepend our temp path and then *also* search in the system paths, there's `PKG_CONFIG_PATH`.

**Comment by vaxerski** [comment]
what I am envisioning right now in my barely functioning brain is:
 - install to a random place e.g. `$XDG_CACHE_HOME/hyprpm/` (headers would end up in `./include`, pc in `./share/pkgconfig`)
 - make the `$XDG_CACHE_HOME/hyprpm/share/pkgconfig` directory the first in .pc search list somehow
 - compile plooginz

One problem I noticed is...

https://github.com/hyprwm/Hyprland/blob/3ff59e7e1d859daa503b88ef125d087bc100abfe/Makefile#L87

that's a fix for pkgconfig not searching `/usr/local/share/pkgconfig`, but even if we set `PREFIX` to the install dir, this will still check it...

I guess we just have to XD and `std::filesystem::exists` that shit before installing, if doesn't just `touch` it and remove afterwards. Prone to break but I don't see a different solution

**Comment by vaxerski** [comment]
also @fufexan we still need to propagate prefix to cmake for this to work otherwise pc will be misconfig'd, see #4531

**Comment by fufexan** [comment]
I'll do it tomorrow night possibly.

**Comment by zakk4223** [comment]
Doing this and ignoring the system headers entirely seems much better. 

I think the only thing that might mess this up is if someone uses the pkg-config (or equivalent cmake) option to make it keep system headers in the output. But that's a documentation problem

**Comment by DreamMaoMao** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/30348075/d4b1f466-5bd0-4ead-8745-9d316d9447b9)

There is a small error here, the directory `headersRoot` is not excluded, when enable plugin,hyprpm will look for the state.toml in `headersRoot` directory. 

![image](https://github.com/hyprwm/Hyprland/assets/30348075/3d372efe-ecc2-42f2-92e0-e7a66fd6506a)

@vaxerski

**Comment by vaxerski** [comment]
oops

**Comment by vaxerski** [comment]
fixd
