### ISSUE TITLE
Resizing a window changes the shape of its corners

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/Hyprland#4565]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 791e1b96b3cd12d56648b3ce7ffb0832eba2b37d dirty (internal: minor header cleanup).
Date: Mon Jan 22 20:32:34 2024
Tag: v0.34.0-59-g791e1b96

flags: (if any)


System Information:
System name: Linux
Node name: LEGION-Mathis
Release: 6.7.0-arch3-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Changing the size of a window will slightly alter the shape of the rounded corners.
On some sizes, windows will have small gaps of a few pixels in their corners.

### How to reproduce

1. Set rounding to 15 and border_size to 4, for example.
2. Spawn multiple windows.
3. Resize them very slowly with your mouse until you notice the shape difference and the small holes.

### Crash reports, logs, images, videos

**Small gaps:**
![image](https://github.com/hyprwm/Hyprland/assets/98901170/557cda69-2dc2-4460-a261-844440f66ea1)

**Visible shape change:**
![image](https://github.com/hyprwm/Hyprland/assets/98901170/3188c420-bd29-438a-b5b0-53b3afdaaa8b) ![image](https://github.com/hyprwm/Hyprland/assets/98901170/266d95ee-503f-4758-a304-0d0744a18e59) ![image](https://github.com/hyprwm/Hyprland/assets/98901170/13524052-030c-422d-be63-6d74b898f033)

**Comment by MathisP75** [comment]
Here is a short video where the issue is clearly visible:
https://github.com/hyprwm/Hyprland/assets/98901170/e09c6afa-35fc-4123-ba4d-df49f0ee7372

**Comment by vaxerski** [comment]
why

**Comment by MathisP75** [comment]
Why what?

**Comment by oYakate** [comment]
idk I couldn't reproduce this

**Comment by MathisP75** [comment]
I could not reproduce it either on my new laptop, closing the issue.
