### ISSUE TITLE
No blur radius in Waybar

### ISSUE THREAD

**Issue by jhenrique04** [hyprwm/Hyprland#4569]
blurls=waybar in the .conf enables the blur in waybar, but the blur stays in a rectangle shape, not obeing the radius that I setted in waybar

![image](https://github.com/hyprwm/Hyprland/assets/115225048/b30fec23-5c0b-452a-ac4f-9b4db784ad6e)

Not that much visible in this photo, but if i make the waybar transparent we can see the block of blur that is below the waybar

![image](https://github.com/hyprwm/Hyprland/assets/115225048/3ec6b5d6-f028-43cc-a12b-d45ac3cc4ab4)

Is there any workaround ? Already did some searching and also looked in the documentation but nothing  solved it

Sorry if noob question, thanks in advice.

**Comment by vaxerski** [comment]
> Already did some searching and also looked in the documentation but nothing solved it

sure you did

![image](https://github.com/hyprwm/Hyprland/assets/43317083/e2e4192f-c793-4a29-a1e3-bf9981ddad4c)

https://wiki.hyprland.org/Configuring/Window-Rules/#layer-rules

**Comment by jhenrique04** [comment]
Well, for those who are wondering, it didn't work.

**Comment by vaxerski** [comment]
you have to tune the `a` value for your specific use case.
