### ISSUE TITLE
Black screen with just a cursor 

### ISSUE THREAD

**Issue by Binaryfetch** [hyprwm/Hyprland#4579]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

I have gnome, hypr, hyprland desktop. Gnome and Hypr are working fine but when I use hyprland after clicking login black screen appears with cursor. I have installed hyprland from pacman(sudo pacman -S hyprland). Please tell some solution. How get logs information as screen turns black nothing opens and I have to shutdown forcefully by button.

System information 
Dell - vostro 1440 
I3 4 CORE PROCESSOR 
8GB RAM
256 SSD MEMORY

It is possible my laptop not supported?? But hypr from arch tweak tool is working fine.

### How to reproduce

Dell vostro 1440
8gb ram
I3 processor
256 Ssd memory

**Comment by stickyburn** [comment]
Check [crashes and bugs,](https://wiki.hyprland.org/Crashes-and-Bugs/) will help understanding the issue more.

**Comment by Binaryfetch** [comment]
I am using command hyprctl version but showing output HYPRLAND_INSTANCE_SIGNATURE not set (is hyprland running)

**Comment by MightyPlaza** [comment]
from the specs you sent, I guess you need to compile hyprland with legacy renderer (https://wiki.hyprland.org/Getting-Started/Installation/#custom-installation-legacy-renderer-etc)
that should solve the issue

**Comment by vaxerski** [comment]
invalid issue

**Comment by Binaryfetch** [comment]
i have compile it but only logo of wayland display then black screen appears
