### ISSUE TITLE
Rofi not starting on Hyprland from sddm

### ISSUE THREAD

**Issue by cristiangrossano** [hyprwm/Hyprland#4581]
### Hyprland Version

Hyprland, built from branch main at commit 15316aaa311ce27982d4df3c9514f042290853a3  (subsurfaceTree: Fix nullptr crash when disconnecting a monitor (4577)).
Date: Thu Feb 1 04:09:31 2024
Tag: v0.34.0-89-g15316aaa

flags: (if any)

System Information:
System name: Linux
Node name: matebookd15
Release: 6.7.2-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 31 Jan 2024 09:22:15 +0000

GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

When I start Hyprland from sddm-git rofi doesnt start with the specified keybind, instead by starting Hyprland from tty fix the issue, keybinds works perfectly.  

```
bind = SUPER, M, exec, .config/rofi/scripts/launcher
```

### How to reproduce

Start hyprland from sddm and tty.

**Comment by fufexan** [comment]
Showing the contents of the launcher script may be helpful.

**Comment by cristiangrossano** [comment]
ops, forgot to paste it, here you are:

```
#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Github : @adi1090x
#
## Rofi   : Launcher (Modi Drun, Run, File Browser, Window)
#

dir="$HOME/.config/rofi/launchers/type-1"
theme='style-1'

## Run
rofi \
    -show drun \
    -theme ${dir}/${theme}.rasi

```

**Comment by Logical-sh** [comment]
Is SDDM setting the working dir correctly?
Does it work if you change
.config/rofi/scripts/launcher
to 
/home/{username}/.config/rofi/scripts/launcher

**Comment by vaxerski** [comment]
likely doesn't. This is not an issue with hyprland
