### ISSUE TITLE
Wayland-0

### ISSUE THREAD

**Issue by Binaryfetch** [hyprwm/Hyprland#4582]
### Hyprland Version

Hyrpland_instance_signature not set

### Bug or Regression?

Bug

### Description

How I change wayland-0 to wayland-1 

### How to reproduce

Please

**Comment by fufexan** [comment]
Please fill in the issue properly.

**Comment by MightyPlaza** [comment]
> Please fill in the issue properly.

likely a dupe/... of https://github.com/hyprwm/Hyprland/issues/4579

**Comment by vaxerski** [comment]
invalid
