### ISSUE TITLE
panel disappears when pluggin in external monitor

### ISSUE THREAD

**Issue by zimbipw** [hyprwm/Hyprland#4583]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

</details>

### Bug or Regression?

Bug

### Description

I'm using nwg-panel on a Laptop running hyprland on Arch. When plugging in an external monitor via HDMI the panel disappears. ps shows the process as still running.

### How to reproduce

plugin monitor on HDMI port
run ps | grep nwg-panel to show it's still running

**Comment by fufexan** [comment]
Are you sure this is a Hyprland bug and not a nwg-panel one? For me and many other users this does not happen with other panels/bars.

**Comment by zimbipw** [comment]
Am Donnerstag, dem 01.02.2024 um 07:34 -0800 schrieb Mihai Fufezan:
> Are you sure this is a Hyprland bug and not a nwg-panel one? For me
> and many other users this does not happen with other panels/bars.
> 
just checked with waybar and looks like a nwg-panel issue.
Sorry
