### ISSUE TITLE
Failed to start on arch linux

### ISSUE THREAD

**Issue by commonuserlol** [hyprwm/Hyprland#4584]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
> sudo pacman -Q hyprland
hyprland 0.34.0-1
```

</details>

### Bug or Regression?

Bug

### Description

Failed (seems segfault) to start under xfce4 session

### How to reproduce

Run xfce4 session, install `hyprland` package, run `Hyprland` from terminal emulator

### Crash reports, logs, images, videos

[hyprlandCrashReport17962.txt](https://github.com/hyprwm/Hyprland/files/14127550/hyprlandCrashReport17962.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14127649/hyprland.log)

**Comment by Logical-sh** [comment]
What exactly are you trying to do?
Hyprland is its own **_WAYLAND_** compositor, its not meant to be ran inside of X11 or another desktop (xfce4).
If you installed it, you should be able to launch it from your login manager if you have one.
It will not run inside of X11.

**Comment by vaxerski** [comment]
casual case of not reading the wiki, can be closed
