### ISSUE TITLE
Hyprland crashes with

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [hyprwm/Hyprland#4586]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
[I] bongo@laptop ~> hyprctl systeminfo
Hyprland, built from branch  at commit 15316aaa311ce27982d4df3c9514f042290853a3  ().
Date: 2024-02-01
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: laptop
Release: 6.1.74
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jan 20 10:50:11 UTC 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Mendocino [1002:1506] (rev c1) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240121.612f972"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes when windows are resized to minimum

### How to reproduce

use the version of hyprland i am on and try resizing windows as small as possible. (it requires extra windows and weird resizing but easily possible). it just crashes when they get too small.

### Crash reports, logs, images, videos

pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
Environment variable $QT_QPA_PLATFORMTHEME not set, ignoring.
Environment variable $QT_QPA_PLATFORMTHEME not set, ignoring.
[032 18:19:51.841856] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[032 18:19:51.845629] [PARSE ERROR] Unknown OSC code: 708
[032 18:19:52.058436] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[032 18:19:52.063006] [PARSE ERROR] Unknown OSC code: 708
[032 18:19:52.230493] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[032 18:19:52.236907] [PARSE ERROR] Unknown OSC code: 708
*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

[032 18:19:59.510014] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[032 18:19:59.516280] [PARSE ERROR] Unknown OSC code: 708
[032 18:20:01.592518] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[032 18:20:01.597543] [PARSE ERROR] Unknown OSC code: 708
[032 18:20:02.593026] Ignoring resize request for tiny size: 6x141
[032 18:20:02.613970] Ignoring resize request for tiny size: 1x141
Hyprland: types/xdg_shell/wlr_xdg_toplevel.c:558: wlr_xdg_toplevel_set_size: Assertion `width >= 0 && height >= 0' failed.
pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
[032 18:20:02.678676] Invalid geometry ignored: framebuffer: 1x141 window: 1x141

[032 18:20:03.322224] [032 18:20:03.322225] [032 18:20:03.322238] [032 18:20:03.322252] [glfw error 65544]: Wayland: fatal display error: Connection reset by peer[032 18:20:03.322261] [glfw error 65544]: Wayland: fatal display error: Connection reset by peer[glfw error 65544]: Wayland: fatal display error: Connection reset by peer[glfw error 65544]: Wayland: fatal display error: Connection reset by peer
[glfw error 65544]: Wayland: fatal display error: Connection reset by peer

**Comment by vaxerski** [comment]
missing crash report

**Comment by AnotherRandomGitHubAccount** [comment]
What do you mean? what do i need to add?

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md#reporting-bugs

**Comment by AnotherRandomGitHubAccount** [comment]
oh ok i get it. here is
hyprlandCrashReport892881.txt:
```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Calm down, it was a misinput! MISINPUT!

Hyprland received signal 6 (Aborted)

Version: 01e5c59d752d3fe7fa484330fa48e010054b8fa1
Tag: 

System info:
	System name: Linux
	Node name: laptop
	Release: 6.1.67
	Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Dec 11 09:41:01 UTC 2023

GPU:
	03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Mendocino [1002:1506] (rev c1) (prog-if 00 [VGA controller])


os-release:
	BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
	BUILD_ID="23.11.20231212.cf28ee2"
	DOCUMENTATION_URL="https://nixos.org/learn.html"
	HOME_URL="https://nixos.org/"
	ID=nixos
	LOGO="nix-snowflake"
	NAME=NixOS
	PRETTY_NAME="NixOS 23.11 (Tapir)"
	SUPPORT_END="2024-06-30"
	SUPPORT_URL="https://nixos.org/community.html"
	VERSION="23.11 (Tapir)"
	VERSION_CODENAME=tapir
	VERSION_ID="23.11"
	


Backtrace:
	#0 | /home/bongo/.nix-profile/bin/Hyprland(_Z12getBacktracev+0x48) [0x573f28]
		_Z12getBacktracev
		??:?
	#1 | /home/bongo/.nix-profile/bin/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x58b) [0x52df9b]
		_ZN13CrashReporter18createAndSaveCrashEi
		??:?
	#2 | /home/bongo/.nix-profile/bin/Hyprland(_Z25handleUnrecoverableSignali+0x3f) [0x4a237f]
		_Z25handleUnrecoverableSignali
		??:?
	#3 | /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6(+0x3da70) [0x7fd702a55a70]
		??
		??:0
	#4 | /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6(+0x8cd7c) [0x7fd702aa4d7c]
		??
		??:0
	#5 | /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6(raise+0x16) [0x7fd702a559c6]
		??
		??:0
	#6 | /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6(abort+0xd7) [0x7fd702a3e8fa]
		??
		??:0
	#7 | /nix/store/bnxmmiv8svr5bjpcap5zv9g7i9dy0liw-gcc-13.2.0-lib/lib/libstdc++.so.6(+0xacc0b) [0x7fd702cacc0b]
		??
		??:0
	#8 | /nix/store/bnxmmiv8svr5bjpcap5zv9g7i9dy0liw-gcc-13.2.0-lib/lib/libstdc++.so.6(+0xbc21a) [0x7fd702cbc21a]
		??
		??:0
	#9 | /nix/store/bnxmmiv8svr5bjpcap5zv9g7i9dy0liw-gcc-13.2.0-lib/lib/libstdc++.so.6(+0xbc285) [0x7fd702cbc285]
		??
		??:0
	#10 | /nix/store/bnxmmiv8svr5bjpcap5zv9g7i9dy0liw-gcc-13.2.0-lib/lib/libstdc++.so.6(+0xbc4d7) [0x7fd702cbc4d7]
		??
		??:0
	#11 | /home/bongo/.nix-profile/bin/Hyprland() [0x463800]
		_Z10throwErrorRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold
		??:?
	#12 | /home/bongo/.nix-profile/bin/Hyprland(_ZN11CCompositor10initServerEv+0x5bd) [0x4b612d]
		_ZN11CCompositor10initServerEv
		??:?
	#13 | /home/bongo/.nix-profile/bin/Hyprland(main+0x754) [0x48c764]
		main
		??:?
	#14 | /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6(+0x27fce) [0x7fd702a3ffce]
		??
		??:0
	#15 | /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/libc.so.6(__libc_start_main+0x89) [0x7fd702a40089]
		??
		??:0
	#16 | /home/bongo/.nix-profile/bin/Hyprland(_start+0x25) [0x4a21e5]
		_start
		??:?


Log tail:
[LOG] Instance Signature: 01e5c59d752d3fe7fa484330fa48e010054b8fa1_1705392926
[LOG] Hyprland PID: 892881
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: laptop
[LOG] Release: 6.1.67
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Dec 11 09:41:01 UTC 2023


[LOG] GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Mendocino [1002:1506] (rev c1) (prog-if 00 [VGA controller])


[LOG] os-release:
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.11.20231212.cf28ee2"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.11 (Tapir)"
SUPPORT_END="2024-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.11 (Tapir)"
VERSION_CODENAME=tapir
VERSION_ID="23.11"

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: Thanks ThatOneCalculator!


[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 59.71µs. Estimated average calc time: 0.09µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 21.47µs. Estimated average calc time: 0.07µs.
[LOG] Using config: /home/bongo/.config/hypr/hyprland.conf
[LOG] Disabling stdout logs! Check the log for further logs.
[backend/backend.c:106] Timeout waiting session to become active
[backend/backend.c:358] Failed to start a DRM session
[CRITICAL] m_sWLRBackend was NULL!
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!
```

**Comment by vaxerski** [comment]
this crash doesn't look like whatever you described above. This one was failing to launch because of wlroots failing to create a drm session

**Comment by AnotherRandomGitHubAccount** [comment]
Sry, idk... but heres a crappy video to demonstrate (note that this happens CONSISTENTLY, even with no plugins)

https://github.com/hyprwm/Hyprland/assets/111426011/b7cadd02-0ffa-4484-84e2-72f81d6a0287

**Comment by AnotherRandomGitHubAccount** [comment]
Thanks so much!
