### ISSUE TITLE
Mouse cursor can leave games on empty monitor

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/Hyprland#4587]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

```

</details>

### Bug or Regression?

Regression

### Description

My mouse cursor only stays in the game's window if there is a window on the adjacent monitor. If there's an empty workspace the cursor will just leave the game.

git bisect blames c298439433f9b6861c7c62ea587289ac2e4ef2f8, but maybe I did something wrong.

### How to reproduce

- Open a game
- Have no window on your second monitor
- in the game, look in the direction of the second monitor
- notice your mouse leaving the game window

**Comment by vaxerski** [comment]
you definitely did something wrong if thats the cmmit to blame

**Comment by Roger-Roger-debug** [comment]
I think it was just me somehow not having 'proper' focus in the game. It received keyboard + mouse input but would not capture the mouse. I just tried it again and it works properly now.
