### ISSUE TITLE
Hyprland-git from AUR fails to build

### ISSUE THREAD

**Issue by superNWHG** [hyprwm/Hyprland#4588]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 91e8c428431deac1e5eb8e537f002ab960777174 dirty (hyprpm: don't update headers if they are up-to-date, only recompile).
Date: Mon Jan 29 11:30:31 2024
Tag: v0.34.0-80-g91e8c428

flags: (if any)


System Information:
System name: Linux
Node name: Laptop-Nico
Release: 6.7.2-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 31 Jan 2024 09:22:15 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] [8086:3ea0] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprtrails by Vaxry ver 1.0
```

</details>

### Bug or Regression?

Bug

### Description

When I try to update hyprland-git from the AUR with ```yay -S hyprland-git```, I get the following error:
```sh
/home/nico/.cache/yay/hyprland-git/PKGBUILD: line 93: subprojects/packagefiles/wlroots-meson-build.patch: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: hyprland-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-git - exit status 4
```

### How to reproduce

Update hyprland-git from the AUR using the command `yay -S hyprland-git`

### Crash reports, logs, images, videos

[install_hyprland-git_output.txt](https://github.com/hyprwm/Hyprland/files/14130958/install_hyprland-git_output.txt)
I provided the output of `yay -S hyprland-git`. If I can share any other logs please let me know!

**Comment by MightyPlaza** [comment]
this isn't a hyprland issue
it begins at e6f7724ab0f72f190e0005c6959c11625cc0c6fe
the PKGBUILD as already been flagged as out-of-date
you just have to either wait for the maintainer to update it, do it yourself or checkout before the commit above

**Comment by vaxerski** [comment]
dam bro that sucks

**Comment by superNWHG** [comment]
> this isn't a hyprland issue
> it begins at e6f7724ab0f72f190e0005c6959c11625cc0c6fe
> the PKGBUILD as already been flagged as out-of-date
> you just have to either wait for the maintainer to update it, do it yourself or checkout before the commit above

Okay, thank you for your response. I think I would spend so much time troubleshooting until I found this :)

**Comment by superNWHG** [comment]
the pkgbuild got updated:)

**Comment by FraktalDeFiDAO** [comment]
I get this same error, both, when trying to install from Yay (arch aur) or building from source
'''
pi@auto-pi-01:~/projects/hyprspace $ go build
# github.com/hyprspace/hyprspace/config
config/config.go:62:18: undefined: schema.Config
pi@auto-pi-01:~/projects/hyprspace $ 
'''

**Comment by gulafaran** [comment]
> I get this same error, both, when trying to install from Yay (arch aur) or building from source
> 
> ```
> ./projects/hyprspace $ go build
> \# github.com/hyprspace/hyprspace/config
> config/config.go:62:18: undefined: schema.Config
> ./projects/hyprspace $ 
> ```
> 
> ```
> go: downloading go.opentelemetry.io/otel/metric v1.16.0
> \# github.com/hyprspace/hyprspace/config
> config/config.go:62:18: undefined: schema.Config
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: hyprspace-git-exit status 4
>  -> Failed to install the following packages. Manual intervention is required:
> hyprspace-git - exit status 4
> go: downloading go.opentelemetry.io/otel/metric v1.16.0
> \# github.com/hyprspace/hyprspace/config
> config/config.go:62:18: undefined: schema.Config
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: hyprspace-git-exit status 4
>  -> Failed to install the following packages. Manual intervention is required:
> hyprspace-git - exit status 4
> ```

Eh hyprspace??

**Comment by FraktalDeFiDAO** [comment]
Closing — this build issue from 2025 is stale. The build system has changed significantly since then.
