### ISSUE TITLE
Huge Lag when reloading configuration

### ISSUE THREAD

**Issue by LunaticWasTaken** [hyprwm/Hyprland#4594]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 7447be822080fac5b8515a177773ec74b4d6c925 dirty (hyprpm: fix crash on add plugin).
Date: Fri Feb 2 02:51:14 2024
Tag: v0.34.0-92-g7447be82
```

</details>

### Bug or Regression?

Bug

### Description

Whenever the config is reloaded (through ctrl+s for example) there is quite a huge lag-spike for abt 5/7 seconds.
Normally this would be fine as most people don't reload that often, but if you hold ctrl+s for even 1ms too long, it will stay pressed the entire lag-process, leading to all those "s" characters being printed after the lag.

### How to reproduce

Save the hyprland.conf file.

edit: additionally, this lag is not present in the latest stable release.

**Comment by vaxerski** [comment]
please git bisect if this is a regression

**Comment by kianagit** [comment]
I have no idea what a git bisect is, but from google i assume it's just the process of finding out which commit is at fault?

i did some builds manually, and it seems like [this commit](https://github.com/hyprwm/Hyprland/commit/2e3f0d5991874edb01f1bfe4ffc75701f8b398dc) introduces it... And after a few reloads i am fairly sure it has to do with the wallpaper. It seems like [this wallpaper](https://github.com/hyprwm/Hyprland/blob/main/assets/wall1.png) is by far the worst, while the others do have less lag (abt 1 second approx.?)

**Comment by vaxerski** [comment]
okay, yes. Thanks. For some reason then the wallpaper is re-rendered every time the config is reloaded which shouldn't happen

**Comment by kianagit** [comment]
i know i suck, but how exactly would i patch the code with this? ._.

**Comment by vaxerski** [comment]
since you managed to make some manual builds, I assume you have hyprland cloned

checkout to latest git and run `patch -p1 < /path/to/the/patch.txt`

**Comment by kianagit** [comment]
yup, that seems to solve the issue. Thanks, and keep up the awesome work <3
