### ISSUE TITLE
sluggish cursor under 99%+ gpu load 

### ISSUE THREAD

**Issue by nutta-git** [hyprwm/Hyprland#4595]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

OS: Arch Linux
GPU: AMD Radeon RX 6600 XT
Mesa: mesa-tkg-git 24.0.0.183253.ee25160ed5d-1

Notable changes from my Hyprland.conf

monitor=,1920x1080@165,auto,1

env = QT_QPA_PLATFORMTHEME,qt6ct 

input { 
accel_profile = flat 
    force_no_accel = true 
} 

misc  { 
no_direct_scanout = false
} 
```

</details>

### Bug or Regression?

Bug

### Description

GPU under 99%+ load causes stutter-y cursor in adjacent workspaces. 
I was playing warframe and noticed if I switched to different workspace, my cursor felt like its was under 60Hz. Its not just a feeling, I clearly saw large gaps between my cursor icon when moving it back and forth really fast. 
It doesn't feel stuttery in game, but only in other workspaces.  

### How to reproduce

1. Use my Hyprland.conf 
2. Launch [Warframe](https://store.steampowered.com/app/230410/Warframe/) from steam. 
3. Use [nvtop](https://archlinux.org/packages/extra/x86_64/nvtop/) to monitor gpu usage. 
4. In game max settings, no vsync or frame limit. 
5. switch to another workspace and move the cursor. 

[hyprland.txt](https://github.com/hyprwm/Hyprland/files/14141019/hyprland.txt)

**Comment by vaxerski** [comment]
why is that a surprise? hyprland uses your gpu to render too. If you strain it, it struggles.

**Comment by nutta-git** [comment]
I don't know much about this topic, but my assumption is that the cursor was supposed to render separately... something about hardware cursors not being my system load.

**Comment by vaxerski** [comment]
I don't think hw cursors are unaffected by system load.

**Comment by nutta-git** [comment]
Then I really don't know what I am talking about. 
Since this situation seems like intended behavior, "hyprland uses your gpu to render too. If you strain it, it struggles". I can convert this to a feature request or close it.

**Comment by zakk4223** [comment]
With my 6900XT I get no cursor lag. GPU at 100%. 

What's the in-game frame rate display show as your frame time?

**Comment by Cloudef** [comment]
I don't think hardware cursors are supported on nvidia?

**Comment by nutta-git** [comment]
@zakk4223 my frame times are fine ingame, my bug report has more to do with other workspaces. If the game running (99%+ gpu load) and I switch to a new workspace my cursor get sluggish in that new workspace. 

While your game is ruining (100% load), can you switch to another workspace and see if you notice the cursor lag.  Here are some of my notable changes: 

```
Notable changes from my Hyprland.conf

monitor=,1920x1080@165,auto,1

env = QT_QPA_PLATFORMTHEME,qt6ct 

input { 
accel_profile = flat 
    force_no_accel = true 
} 

misc  { 
no_direct_scanout = false
} 

```
Also can you list your kernel version?

**Comment by nutta-git** [comment]
I was testing with another game and noticed when it maxed out the gpu, it didn't cause a cursor stutter. So I played around with the settings in Warframe and seem to have landed on the culprit. SSAO (Screen space ambient occlusion), disabling has resolved this issue. 
![warframe_ssa0](https://github.com/hyprwm/Hyprland/assets/59726608/13b7fc30-f15d-472e-99d6-ecc5617b7460)
Sorry for wasting your time, 
Thank you
