### ISSUE TITLE
Tearing not working without WLR_DRM_NO_ATOMIC=1 on Linux 6.8

### ISSUE THREAD

**Issue by CNR0706** [hyprwm/Hyprland#4596]
### Hyprland Version

Output of hyprctl version (is it supposed to look like that?):

Hyprland, built from branch  at commit  dirty ().
Date:
Tag:

flags: (if any)

hyprctl systeminfo does not work (option not found).

Hyprland package version: 0.34.0-1.1
Hyprland source package: hyprland-0.34.0-1.1.src
Host OS: openSuSE Tumbleweed
Kernel: Linux 6.8-rc2
Mesa: 23.3.4
GPU: RX 6700XT
CPU: R7 5800X3D
RAM: 32 GiBs DDR 4 3600MT/s CL16

### Bug or Regression?

Bug

### Description

Enabling the tearing master toggle and setting the appropriate window rule does not result in tearing actually working on my system running Linux 6.8.0-rc2-4.g97de76a-default.

After setting WLR_DRM_NO_ATOMIC=1 tearing starts working again*

*using the legacy API causes my system to occasionally hard lock when switching focus between a full screen application and another window.

### How to reproduce

1. Install linux-default from the Kernel:HEAD repository.
2. Remove env = WLR_DRM_NO_ATOMIC,1 from hyprland.conf
3. After logging in the configuration warning will be displayed and tearing won't work.

**Comment by vaxerski** [comment]
> 0.34.0

read the wiki for 0.34.0 then, not for -git.

**Comment by CNR0706** [comment]
Sorry! Didn't realize the wiki defaulted to -git.

Updated my Hyprland version to git but now the applications just freeze. I thought AMDGPU should support Tearing? Am I missing something?

**Comment by fufexan** [comment]
It doesn't. It used to in older versions of Mesa, but now it doesn't work at all.

**Comment by CNR0706** [comment]
That's unfortunate.

Fixes specific to the legacy Kernel API aren't planned right? Cause there is a pretty annoying bug that prevents me from using Hyprland with the legacy API.

**Comment by vaxerski** [comment]
amdgpu supports tearing with legacy API just fine on my end.
