### ISSUE TITLE
different keyboard layout depending on device breaks bindings (also in apps)

### ISSUE THREAD

**Issue by Vexcited** [hyprwm/Hyprland#4598]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

I'm on a laptop. The keyboard integrated with the laptop is in AZERTY layout (French : `fr`)
When I'm home, I use my USB keyboard which is in a QWERTY layout (US-intl : `us`)

Now the issue, is that it feels like every bindings (on Hyprland but also on apps such as VSCode) are constantly on the AZERTY layout.

For example, I assigned SUPER + Q to quit a tab on my `fr` layout but when using my USB keyboard I have to use SUPER + A to trigger SUPER + Q. Same in VSCode, when I hit CTRL + Z it triggers CTRL + W, closing my file :')

It's strange because when I type, the characters are correct depending on the layout selected.

### How to reproduce

This is how I configured the layouts in my hyprland configuration file, maybe something's wrong here ?

```
input {
    kb_layout = fr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = yes
}

# Home QWERTY keyboard, should never be used in `fr` layout.
device:hp,-inc-hyperx-alloy-origins-1 {
  kb_layout = us
  kb_variant = intl
  kb_options =
}
device:hp,-inc-hyperx-alloy-origins {
  kb_layout = us
  kb_variant = intl
  kb_options =
}
device:hp,-inc-hyperx-alloy-origins-system-control {
  kb_layout = us
  kb_variant = intl
  kb_options =
}
device:hp,-inc-hyperx-alloy-origins-consumer-control {
  kb_layout = us
  kb_variant = intl
  kb_options =
}
```

I was desperate and put every devices that I got when running `hyprctl devices` but had no luck.

### Crash reports, logs, images, videos

About apps, it seems like when I run them using my USB keyboard, they define the key binds to US but when I run them using my laptop keyboard it's always in FR. Is this related ?

If anything is needed, please tell me, thanks !

**Comment by MightyPlaza** [comment]
set `kb_variant = azerty`
and use wev for keyboard debugging

**Comment by vaxerski** [comment]
read the big yellow important box

https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts
