### ISSUE TITLE
No borders on only

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#460]
When I have one window I would like to have no gaps and borders simialar to https://github.com/hyprwm/Hyprland/issues/447 but for borders

**Comment by vaxerski** [comment]
done in cd483a7a37c6024347659974701a76703c6e3a3a

**Comment by hazycora** [comment]
this fix also disables the tabs in grouped windows when `no_gaps_when_only` is enabled, which is a little frustrating because it causes me to often forget whether I've already grouped a window
