### ISSUE TITLE
Floating window appears on other monitor when swiping workspaces

### ISSUE THREAD

**Issue by lsofiabo** [hyprwm/Hyprland#4602]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3).
Tag: v0.32.3

flags: (if any)
debug
```

</details>

### Bug or Regression?

Bug

### Description

I have a laptop and a second monitor connected to it via HDMI. Floating windows behave strangely when swiping workspaces with gestures. Let's suppose i swipe workspaces on **"Screen 1"** and they appear on **"Screen 0"**.

1. If swiping out of workspace with floating window, it will appear on both monitors and will leave artifacts on **"Screen 0"**.
2. Sometimes the window won't be artifacted, but i couldn't figure any pattern to it. Seems like it's more likely when:
    a. **"Screen 0"** has OBS opened (not necessary recording)
    b. **"Screen 1"** has more than 1 floating window opened on the workspace.
    
3. This appears on any screen, both built-in and external.
4. If sliding into workspace with floats from the one without floats, everything is fine.

### How to reproduce

1. Get a multi-monitor setup.
2. Set `gestures:workspace_swipe = on`.
3. Open a window on one of the monitors and make it floating.
4. Swipe out of the workspace.

### Crash reports, logs, images, videos

1. The bug:
https://github.com/hyprwm/Hyprland/assets/79804918/8b986576-7cbf-43dd-8c31-62ba942586ef

2. No artifacts when two floats:

https://github.com/hyprwm/Hyprland/assets/79804918/ab17f53f-6be1-472c-bd73-e4618d4220d3

3. No artifacts when OBS is opened:

https://github.com/hyprwm/Hyprland/assets/79804918/e4e00b60-d166-44c5-bcdd-4c1a88497c93

4. No bugs when swiping into workspace with floats from the one without them:

https://github.com/hyprwm/Hyprland/assets/79804918/7c1af616-3572-429b-9d51-03b609a83ccf

**Comment by MightyPlaza** [comment]
please update to the latest version before creating issues on github

**Comment by vaxerski** [comment]
invalid, as above
