### ISSUE TITLE
Hyprland on FreeBSD with nvidia not working right

### ISSUE THREAD

**Issue by bonspry** [hyprwm/Hyprland#4603]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
```

</details>

### Bug or Regression?

Bug

### Description

It doesn't launch for some reason.

### How to reproduce

<details> <summary>How to reproduce this issue:</summary>
Go on FreeBSD, install the nvidia driver, load it into the kernel, set XDG_RUNTIME_DIR, launch Hyprland.
</details>

### Crash reports, logs, images, videos

[hyprlandCrashReport1377.txt](https://github.com/hyprwm/Hyprland/files/14151617/hyprlandCrashReport1377.txt)

**Comment by vaxerski** [comment]
you did not read the wiki, are missing a seat manager, and are using nvidia which is not officially supproted.

**Comment by bonspry** [comment]
i have seatd tho

**Comment by bonspry** [comment]
how do i configure them?

**Comment by vaxerski** [comment]
that's on you to figure out - I don't sit in your computer. Using DIY distros assumes you know how to deal with them.

**Comment by bonspry** [comment]
i fixed seatd.sock issue but now it still doesn't let me launch

**Comment by jbeich** [comment]
Anything Wayland on NVIDIA requires [nvidia-drm-kmod](https://www.freshports.org/graphics/nvidia-drm-kmod). It's similar to `nvidia_drm.modeset=1` on Linux. Current versions of NVIDIA driver tarball for FreeBSD don't include nvidia-drm code (DRM API glue) but this may change with 550 series.

I don't have an NVIDIA GPU, so don't expect me update Hyprland Wiki. Instructions must be verified to work lest the cargo cult would just create more confusion.
