### ISSUE TITLE
How to disable update loop?

### ISSUE THREAD

**Issue by skylize** [hyprwm/Hyprland#4605]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```
</details>

### Bug or Regression?

Bug

### Description

Hyprland is automatically running an update check. On Arch Linux Pacman manages the updates, not Hyprland. So this is check of minimal value.

I have frequent system freezes running Warframe (which don't happen in Sway). Last thing logged during/after the freeze is ...
```
hyprland[8008]: Background update loop checking for update. . .
hyprland[8008]: Checking for available updates...
```
... so I'm hoping that disabling the update loop will prevent the need to report this as a much harder to pin down bug involving Steam and/or Wine.

So how do I disable it? Thx

### How to reproduce

Looking for help at this stage, not bug fix.

**Comment by vaxerski** [comment]
hyprland has no update loops and this log does not come from hyprland.

**Comment by skylize** [comment]
Hmm okay. 🤔

**Comment by n3oney** [comment]
this is a log coming from Steam most likely
