### ISSUE TITLE
Bindings with shift and numerals not working.

### ISSUE THREAD

**Issue by the-bokya** [hyprwm/Hyprland#461]
### Steps to Reproduce:
Add a binding with Shift and some numeral to the config. For example:
`bind=SHIFTSUPER,1,movetoworkspace,1`

### Expected Outcome
The binding should execute. And in this case move to workspace 1.

### Noted Outcome
It doesn't work.

**Comment by fufexan** [comment]
Does `SUPERSHIFT` work?

**Comment by vaxerski** [comment]
maybe read the wiki before posting an issue that has been described in it.

https://github.com/hyprwm/Hyprland/wiki/Advanced-config#binds

**Comment by the-bokya** [comment]
Oh sorry my bad.
