### ISSUE TITLE
Make caps lock behave like escape when pressing, and ctrl and combine with another key.

### ISSUE THREAD

**Issue by mkblast** [hyprwm/Hyprland#4611]
### Description

I'd like to see if it duable in wayland and hyprland. I used to use a hack in xorg and can't find a way to replicate it in wayland.

**Comment by fufexan** [comment]
Perhaps not the answer you're looking for, but [KMonad](https://github.com/kmonad/kmonad), [kanata](https://github.com/jtroo/kanata/) and [keyd](https://github.com/rvaiya/keyd) can do it.

**Comment by mkblast** [comment]
Thanks, interception tools and caps2esc were what i was looking for. they work really well and not hard to setup.

anyways I'll this issue as resolved.
