### ISSUE TITLE
Rasberry pi imager settings floating page does not display properly

### ISSUE THREAD

**Issue by M0-7** [hyprwm/Hyprland#4614]
### Hyprland Version

<details> <summary>System/Version Info</summary>

```sh
>Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

Rasberry pi imager settings floating page doesn't show properly and when resized the app starts to act weird. This is also an issue with nheko verification page. I tried opening this in sway and the page displayed properly as intended with all the options available without the need to resize it or anything. I tried toggling floating on or off and it didn't seem to change anything.

#### Things I tried
- Opening the new window in fullscreen mode. This showed all the options but then I wasn't able to change settings or tweak anything. Everything was unclickable

### How to reproduce

1. Download Rasberry pi imager from flathub or the AUR and open the app.
2. Press Control Shift X to acess the settings page

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/135035314/0d7d5d10-b963-497f-a215-816fea31d098

No other logs or crashes

**Comment by MightyPlaza** [comment]
can repro
I'm pretty sure this isn't a hyprland issue, likely happens at least wlroots-wide
You should probably open an issue on their tracker (rpi-imager) or use the cli version

**Comment by MightyPlaza** [comment]
> It works as intended on sway so I don't think its related to wlroots

sway-git (https://aur.archlinux.org/packages/sway-git-wlroots-git)?

**Comment by haras-unicorn** [comment]
got the same problem on nixos

**Comment by kepi** [comment]
I tried to play with resizing and nomaxsize window rules, but didn't help.

As a workaround, you can run imager in XWayland, i.e. with `env -u WAYLAND_DISPLAY rpi-imager`
