### ISSUE TITLE
Latest commit causes non-XWayland clients to get squished and hypr™scaled

### ISSUE THREAD

**Issue by Donnerinoern** [hyprwm/Hyprland#4621]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit f9202f791e3690ad248c842158ee9fa9e1105ea6  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: brutus
Release: 6.7.3-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c1) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240202.e92b601"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Latest commit somehow causes windows to get squished and weirdly scaled. Look at attached images.

### How to reproduce

Use commit https://github.com/hyprwm/Hyprland/commit/f9202f791e3690ad248c842158ee9fa9e1105ea6. Launch Wayland-clients on multiple monitors.

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/72634505/f8e640cd-d521-425d-9015-db58a877b04a)
![image](https://github.com/hyprwm/Hyprland/assets/72634505/a3ff8b9b-0a93-4291-bda0-c59a715e4432)

**Comment by Donnerinoern** [comment]
sorry, i think i used the wrong label :skull:

**Comment by vaxerski** [comment]
fwiw been running without the patch for an entire day and havent noticed this.
