### ISSUE TITLE
More crashes on rollnext

### ISSUE THREAD

**Issue by Seme4eg** [hyprwm/Hyprland#4627]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1512b81126dd115f089fd21244692d92034c78f8 dirty (master: guard PNODE in roll*).
Date: Wed Jan 3 00:18:38 2024
Tag: v0.34.0-19-g1512b811

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

3 tiled windows on workspace, 2 monitors (maybe that matters), calling rollnext - got a crash. Also i had some cpu intensive compilation going in one of thoes windows (being a terminal), maybe that also matters.

### How to reproduce

Open 3 windows on workspace, one of them being browser, 2nd being emacs, 3rd one being foot terminal with `telegram-tdlib-git` compilation going on in it. And call rollnext.

### Crash reports, logs, images, videos

[hyprlandCrashReport1124.txt](https://github.com/hyprwm/Hyprland/files/14173235/hyprlandCrashReport1124.txt)

**Comment by thejch** [comment]
Wasn't this fixed? Can you update to latest

**Comment by Seme4eg** [comment]
i did update after #4343 tho

**Comment by thejch** [comment]
Then why does your version show a version older than that?

**Comment by Seme4eg** [comment]
then maybe i am confusing my 2 laptops, on which i did update, on which i didn't. My bad.
