### ISSUE TITLE
`inactive_border_size` or some other way to disable inactive border

### ISSUE THREAD

**Issue by carschandler** [hyprwm/Hyprland#4631]
### Description

Currently, you can *sort of* disable inactive borders by setting `col.inactive_border = rgba(00000000)`. However, if you use shadows, then this leaves a jarring space where there is no shadow around the window. I propose an `inactive_border_size` option under `general`, which would let you control their size independently with the option to completely disable by setting to `0`.

If for some reason this would be much more difficult than simply adding a `disable_inactive_border` toggle, then that's all I really care about anyway and would be happy to see either added!

Thanks

**Comment by tchofy** [comment]
Try these:
```
windowrulev2 = noborder, focus:0
windowrulev2 = noshadow, focus:0
```

**Comment by carschandler** [comment]
@tchofy thanks! The top was sufficient for what I wanted, but the toggling on/off of borders does make windows jump around a bit sometimes, and it seems that window rules override animations, at least in this case. For example, I found that if you want to disable shadows for inactive borders, it's better to use `col.shadow_inactive` as that preserves shadow fade in/out animations.

I'm going to leave the issue open and let the team decide if it's worth their time to add a proper setting that animations work for in case it's a super simple addition.

**Comment by neilking01** [comment]
thanks! I was looking for this option for a long time.

**Comment by shadowelite-sec** [comment]
> @tchofy thanks! The top was sufficient for what I wanted, but the toggling on/off of borders does make windows jump around a bit sometimes (this may be unavoidable), and it seems that window rules override animations, at least in this case. For example, I found that if you want to disable shadows for inactive borders, it's better to use `col.shadow_inactive` as that preserves shadow fade in/out animations.
> 
> I'm going to leave the issue open and let the team decide if it's worth their time to add a proper setting that animations work for in case it's a super simple addition.

find any other solution ?

**Comment by vaxerski** [comment]
I dont think theres anything left to do here
