### ISSUE TITLE
Text in groupbar titles are not scaled

### ISSUE THREAD

**Issue by sin-ack** [hyprwm/Hyprland#4633]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

#3851 appears to be fixed (titles used to render completely wrong on 0.32.0), however titles still render in a tiny font despite scale > 1 being set for the output.

Note that changing the font size isn't a fix because it doesn't play well with multiple monitors.

### How to reproduce

1. Set monitor scale > 1 in hyprland.conf
2. Start a tabbed group
3. Observe little baby text

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/77421532/52468813-13e8-4ddf-96f4-90420307a3a8)

**Comment by sin-ack** [comment]
Since #4640 fixed this, I'm closing it.

**Comment by mastrof** [comment]
I'm having this same issue on 0.47.2. Text was scaling well in 0.47.0

```
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1

no flags were set
```

**Comment by vaxerski** [comment]
bisect then

**Comment by mastrof** [comment]
Actually after a bit of trials I was unable to reproduce a state where groupbar titles scale properly. I tried all the 0.47.x releases but none does it for me now. Yet I'm sure it *was* scaling at some point when I was on 0.47.0 (i.e., I remember the titles being large enough that I could read them). May this possibly be related to some other package? I'm currently on Arch (6.13.2-arch1-1) if that helps; let me know if there's any useful info I can provide to narrow this down.
I see a couple people upvoted the prev comment so I assume it's not only a me problem
