### ISSUE TITLE
Workspace dispatch to switch between seperate monitor workspaces.

### ISSUE THREAD

**Issue by jasper-at-windswept** [hyprwm/Hyprland#4634]
### Description

In Dispatchers/Workspaces currently you can filter between active workspaces and active workspaces on the current monitor, but the issue is then if you have two workspaces active that are bound to one monitor and then you want to switch to you second monitor, you would have to run your keybinding 3 times to get to the next monitor.

Adding a new dispatcher for example, `sm-1`, `sm+1` for switching between monitors only would resolve this.

**Comment by zakk4223** [comment]
Isn't this just focusmonitor?

**Comment by jasper-at-windswept** [comment]
> Isn't this just focusmonitor?

No because focusmonitor cannot move windows to the other monitor. That is why a new dispatcher must be made/\.

**Comment by jasper-at-windswept** [comment]
@vaxerski 
Ok how about this, instead make a function that works the exact same way as `focusmonitor` but instead it is `movetomonitor`, so it moves the active window to the next monitor as an example.

```
# Move the active window to the next monitor on the right
bind = SUPER, V, movetomonitor, r
```

**Comment by fufexan** [comment]
You mean `movecurrentworkspacetomonitor`, which already exists?

**Comment by jasper-at-windswept** [comment]
> You mean movecurrentworkspacetomonitor, which already exists?

No not at all, that moves the entire workspace.
I want to just move the focused window to a monitor.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/beff46f6-ae75-4377-9d2c-ec97c1b647ac)
movewindow?

**Comment by jasper-at-windswept** [comment]
> movewindow?

Ah I see, I didn't notice that sorry. Thank you for you help!
