### ISSUE TITLE
memory leak in jvm application

### ISSUE THREAD

**Issue by Emiya173** [hyprwm/Hyprland#4635]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When JVM application windows are rapidly and significantly resized, memory can quickly increase until the system becomes unresponsive

### How to reproduce

1. Have a float jvm application window(e.g. IDEA or compose multiplatform application)
2. Quickly resize window

**Comment by vaxerski** [comment]
how is this a hyprland issue?

**Comment by Emiya173** [comment]
If I use plasma(wayland), this issue won’t occur

**Comment by vaxerski** [comment]
what about sway?

**Comment by Emiya173** [comment]
It won't happen in Sway either

**Comment by vaxerski** [comment]
I still would take it to whoever is maintaining your jvm, after all it's a leak in _their_ code, not mine.

**Comment by Emiya173** [comment]
After trying version 0.35, this issue no longer occurs.
In previous version, Electron also encountered the same issue.
