### ISSUE TITLE
A variable to exclude layer shells from windows' blur source

### ISSUE THREAD

**Issue by sin-ack** [hyprwm/Hyprland#4636]
### Description

My goal is to have a contiguous blur between the terminal and waybar here:

![image](https://github.com/hyprwm/Hyprland/assets/77421532/850b4b3a-d46d-4789-a284-fdcddd4baf87)

The issue is that, based on the render order of the window and bar, we either include the window (with `"layer": "top"` in waybar config) or the bar (with `"layer": "bottom"`) in the other side's blur source image. This causes the ugly shadow-like effect starting from the top of the bar.

I would like to be able to configure Hyprland such that the following happens:
1) The bar and its blur effect (using background as a source since it's at the bottom) gets rendered into a separate buffer.
2) Windows and their effects are rendered as if the bar isn't present.
3) The layers are composited together in background -> bar -> windows order.

This would allow me to have the contiguous blur as I described.

**Comment by vaxerski** [comment]
uhh xray?

**Comment by sin-ack** [comment]
Yep, turning `new_optimizations` and `xray` on works perfectly. Thank you!
