### ISSUE TITLE
Mark Milestone 1 as completed

### ISSUE THREAD

**Issue by 10leej** [hyprwm/Hyprland#4637]
### Hyprland Version

master branch

### Bug or Regression?

Bug

### Description

https://github.com/hyprwm/Hyprland/milestone/1

Still listed as incompleted

### How to reproduce

Look at link, confirm no open issues on milestone
https://github.com/hyprwm/Hyprland/milestone/1

### Crash reports, logs, images, videos

![2024-02-07T19:17:10,301808785-05:00](https://github.com/hyprwm/Hyprland/assets/2258333/5462cec3-77b5-43da-9f89-cc7f80f539bf)

**Comment by vaxerski** [comment]
my bad, fixed
