### ISSUE TITLE
Switching between two workspaces with fullscreen windows causes one to not render

### ISSUE THREAD

**Issue by ProtoSharkk** [hyprwm/Hyprland#4641]
### Hyprland Version

Hyprland version: Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).

### Bug or Regression?

Bug

### Description

When switching between two workspaces that both have fullscreen windows, the window on the workspace being switched to does not render until the animation is complete. Much more noticable when using workspace swipe.

### How to reproduce

Create two workspaces, fullscreen a window on both windows, and then switch between the two workspaces.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/130694806/2d83a82f-f80d-4591-aaaa-4c90bf3e8887

[LOG] Instance Signature: 03ebbe18ed8517ee22591eac82cd54322f42cb7d_1707324246
[LOG] Hyprland PID: 724
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: hummingbird
[LOG] Release: 6.6.10-1-MANJARO
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Fri Jan  5 17:38:36 UTC 2024

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a1] (rev 04) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Two trailer park girls go round the outside

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 38.17µs. Estimated average calc time: 0.10µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.

**Comment by Fxzzi** [comment]
I also experience this. Especially noticeable when using workspace gestures on touchpad.

**Comment by daniele821** [comment]
i experience something similar: i am in workspace x with a window open in fullscreen, then i press a binding which launch kitty and kitty gets places into workspace y  by a windowrule, but once hyprland switches to workspace y, kitty doesn't show, unless i go to an other workspace and come back to workspace y.

**Comment by Arajtav** [comment]
Im on `Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).` and there is no problem, I think it was fixed already.
