### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by linuxmobile** [hyprwm/Hyprland#4644]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit f9202f791e3690ad248c842158ee9fa9e1105ea6  ().
Date: 2024-02-05
Tag: 

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Yesterday I updated the flakes, and after restarting it seems that there is an error in the scaling (obviously, everything worked perfectly before).

### How to reproduce

---

### Crash reports, logs, images, videos

https://youtu.be/NOKhTutKnVY

**Comment by fufexan** [comment]
Looks like you're one commit behind the fix. Please update again.

**Comment by linuxmobile** [comment]
> Looks like you're one commit behind the fix. Please update again.

Thank you fufexan. Solved
