### ISSUE TITLE
hyprctl notify not working when an app is fullscreen

### ISSUE THREAD

**Issue by sky-cypher** [hyprwm/Hyprland#4647]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: [REDACTED]
Release: 6.7.4-artix1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 01:37:44 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Built-in notification or config error message doesn't show up when an app is in fullscreen mode.

Also could you please add configuration for increasing size of notification.

### How to reproduce

run and open an app in  fullscreen mode
```sh
sleep 1 && hyprctl notify 3 8000 0 " Hello"
```

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14270764/patch.txt)
try

**Comment by sky-cypher** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14270764/patch.txt) try

Hi @vaxerski 
Its Working, the notifications are showing up on fullscreen apps after applying the patch,

Thank you for looking into the issue in such a short time.
