### ISSUE TITLE
Apply windowrule to specific window

### ISSUE THREAD

**Issue by Piroro-hs** [hyprwm/Hyprland#4648]
### Description

Exec with window rules ~~is not always working~~can not handle some usecases. It would be convenient if something like "apply windowrule dispatcher" or `hyprctl apply rule window` and someway of undone is available.

My specific usecase is to toggle nofocus rule.

**Comment by Piroro-hs** [comment]
`exec` rule itself is working as expected. It does not handle my usecase (dynamically apply and clear windowrule to existent window) .

**Comment by vaxerski** [comment]
elaborate?

**Comment by phonetic112** [comment]
what about `hyprctl keyword "windowrulev2 [rule], [window]"`

**Comment by Piroro-hs** [comment]
> what about `hyprctl keyword "windowrulev2 [rule], [window]"`
windowrulev2 does not support specifying window id.

**Comment by vaxerski** [comment]
what's a window id? Never heard of such a thing.

**Comment by Piroro-hs** [comment]
Ah, I mean, address

**Comment by vaxerski** [comment]
it's dynamic and always changes, though.

**Comment by Piroro-hs** [comment]
Does address change during window is open? 
Then pid is ok?
`hyprctl apply [rule] [pid]`

**Comment by vaxerski** [comment]
no, once it's open it doesn't...

have you checked `hyprctl setprop`?

**Comment by Piroro-hs** [comment]
Yes but setprop does not support nofocus...

**Comment by vaxerski** [comment]
ok I finally understand what you want from me, tho xD

**Comment by MightyPlaza** [comment]
> Yes but setprop does not support nofocus...

it does now
