### ISSUE TITLE
Mouse work not correct in some games

### ISSUE THREAD

**Issue by risa-tyan** [hyprwm/Hyprland#4654]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
commit 3d9ca6381df1cdbf1731d7e2b39ea3f7574fce1e dirty (crashreporter: fix logging of function data (4632)).
Tag: v0.35.0-7-g3d9ca638
```

</details>

### Bug or Regression?

Bug

### Description

Most of the launches, for example, CS2, do not have correct capture, show too reliable sensitivity, changing the window to full screen does not help, switching between windows does not help.

### How to reproduce

Test in CS2

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/111539573/332f0a95-4a80-4932-bbfb-f538ffb680dc

**Comment by vaxerski** [comment]
IIRC that's a cs2 bug.

For me, with csgo-vulkan-fix from hyprland-plugins, I've never had this happen.

**Comment by risa-tyan** [comment]
> For me, with csgo-vulkan-fix from hyprland-plugins, I've never had this happen.

its work fine :D
