### ISSUE TITLE
[IHyprWindowDecoration] Positioning info updates

### ISSUE THREAD

**Issue by ldgrcc** [hyprwm/Hyprland#4655]
### Description

Hi, i think that window decorations should have a way to tell to the compositor that there is a change in positioning info to allow dynamic resizing of reserved area, sticky edges, etc.
I've looked up in the issues, opened and closed ones, and not found something similar.
I was playing with window methods, many functions, hacking the rendering pipeline, for the sake of triggering a call to IHyprWindowDecoration::getPositioningInfo() but it's only called on instance creation. The idea is to make responsive decorations.
I don't think in reloading plugins or reattaching decoration instances as a good solution. Maybe a call to HyprWindowDecoration::updateWindow() or other periodic method could return the new positioning info.

**Comment by vaxerski** [comment]
`CDecorationPositioner::repositionDeco(IHyprWindowDecoration*)`?

**Comment by ldgrcc** [comment]
It works, thank you. Sorry for the issue. I was lost in the source code. That was a quick answer, wow.
