### ISSUE TITLE
no password needed when waking from suspend

### ISSUE THREAD

**Issue by gregallem** [hyprwm/Hyprland#4657]
### Hyprland Version

<Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: fedora
Release: 6.7.3-200.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Thu Feb  1 03:29:52 UTC 2024

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06) (prog-if 00 [VGA controller])

os-release: NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation

plugins:
details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

When I wake hyprland from suspend It will now wake without needing a password. That is it will wake just by any key-press. Before the recent update to version 0.35. I needed to enter my login password to wake the computer

### How to reproduce

Put hyprland into suspend by entering 'systemctl suspend'
Wake by pressing any key. No password is required.

**Comment by zakk4223** [comment]
Which program are you using for the screen locker? And are you also using swayidle?

**Comment by vincentaxhe** [comment]
there need a way to autolock the screen after wake up from suspend.

**Comment by Varad-Codes** [comment]
you need to call your screen lock util before suspend

**Comment by logno-dev** [comment]
As others have stated, you need a screen locker. If you were using gtklock, this was a known issue and calling gtklock with "-i" flag solves it

**Comment by gregallem** [comment]
I'm using swayidle then systemctl suspend here is my hyprland config
exec-once = swayidle timeout 300 'hyprctl dispatcher dpms off' timeout 600 'systemctl suspend'

**Comment by zakk4223** [comment]
If this was working before you have to have had some other program presenting a lock screen. Since it isn't working now I think multiple of us suspect you may have been using gtklock, which requires the flag like someone said above.

(although at this point gtklock  isn't _really_ a screen locker due to it not using any of the lock screen protocols)

**Comment by gregallem** [comment]
Yes it was working previously until the latest update hyprland stable version on Fedora. I'm not using a lock screen program.
Thank you for your feedback.

**Comment by gregallem** [comment]
I have solved the issue. Thank you for your support. I needed to call swaylock in my script.
exec-once = swayidle timeout 300 'hyprctl dispatcher dpms off && swaylock'
Regards
Greg
