### ISSUE TITLE
Pipewire does not start on non-systemd systems

### ISSUE THREAD

**Issue by o0nd7ots** [hyprwm/Hyprland#4658]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: buk9
Release: 6.7.4-artix1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 01:37:44 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

[The wiki](https://wiki.hyprland.org/Useful-Utilities/Must-have/) says that pipewire autostarts.
From what I gather it does that using systemd, since it doesn't launch for me.

For Plsama I needed to symlink `/usr/share/applications/pipewire.desktop` to `/etc/xdg/autostart/pipewire.desktop`.

I think Hyprland should either communicate the systemd depencency more clearly or add support for other init systems. I think the second one is better of course.

### How to reproduce

1. Do not use systemd
2. Install pipewire-pulse and hyprland
3. launch hyprland

**Comment by vaxerski** [comment]
systemd is not a hard dependency in any way, shape or form.

I believe if you are a technical user that chooses not to use it, you should deal with the problems that arise from that.

FWIW, hyprland doesn't launch pipewire on sysd either. It's pipewire that supports sysd here, not hyprland.
