### ISSUE TITLE
Layer shell blur rounding

### ISSUE THREAD

**Issue by altacountbabi** [hyprwm/Hyprland#4659]
### Description

When using something like rofi with layer blur the layer blur cant be rounded and it can look bad under bright backgrounds
![Screenshot_2024-02-09-17-54-37-518_dev beefers vendetta](https://github.com/hyprwm/Hyprland/assets/82091823/2b7c726c-7caa-4203-b801-0232124990b3)
Would it be possible to add a rounding option to layer blur?

**Comment by ErrorNoInternet** [comment]
`layerrule=ignorezero,rofi`

**Comment by vaxerski** [comment]
as above
