### ISSUE TITLE
Some xwayland apps has unusable size

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#466]
Clion: pop-up size 1,1 -> unable to resize, since I don't know every single pop-up that it creates, I can't make a windowrule
OnlyOffice: save prompt size is small(100,30), title is different tho, so it's fixable
Chromium: Sometimes login pop-op prompts will appear as size(1,1), this is quite impossible to fix on the user side since the title will be different for every website

**Comment by vaxerski** [comment]
I am aware of that, but XWayland creates a plethora of windows that are 1,1. Some should be visible, and some not, and I've yet to find a way to distinguish between the two.

For chromium, run it in native wayland and it should go away. Or, you know, use Firefox.

**Comment by KyleUltimate** [comment]
Running chromium in native wayland does fix it, but my input method goes away too
Though surprisingly, running firefox in wayland does work with input methods, strange

**Comment by vaxerski** [comment]
Simple, firefox is superior.

Chromium probably only supports native wayland protocols for IME, while firefox backports with GDK. Hyprland is yet to support native Wayland IME protocols.

**Comment by vaxerski** [comment]
should be fixed with recent commits, please verify.

**Comment by KyleUltimate** [comment]
It's somewhat fixed
Clion certainly works perfectly now, but onlyoffice still has that strange pop-up size

**Comment by KyleUltimate** [comment]
Well, I just found out this, its size is `1280,720`
![image](https://user-images.githubusercontent.com/68589851/183072137-c8a6d357-7887-4d3f-a63c-df08af6515da.png)

**Comment by vaxerski** [comment]
regarding chromium and IMEs - Chromium (and consequentially, stuff like electron as well) only support native Wayland IME protocols with GTK4 - pass the `--gtk-version=4` flag to the app (e.g. `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --gtk-version=4`) and it will work.

Be aware that some apps, e.g. VSCode or WebCord do NOT support GTK4 - meaning either XWayland or no IME.
