### ISSUE TITLE
Weird artifacts caused by Nvidia

### ISSUE THREAD

**Issue by MOj0** [hyprwm/Hyprland#4661]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 289d4241bea72ebd891e037996ec4ffd356aadc8 dirty (groupbar: scale groupbar text according to monitor scale (4640)).
Date: Thu Feb 8 23:29:10 2024
Tag: v0.35.0-9-g289d4241

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Strange artifacts occur when scrolling (or when any motion happens) on the external monitor.
This occurs on **any** application only on the external monitor. I have a HP laptop with Intel Iris integrated graphics and Nvidia GTX 1050 Max-Q. External monitor is connected through HDMI.

I did everything the [Nvidia wiki page](https://wiki.hyprland.org/Nvidia/) specified. I also tried with several Nvidia driver versions, namely 550 (beta), 545, 535, 525. The artifacts always occur (although on version 525 monitor did not give any output at all). I tried the open source Nouveau drivers aswell and the artifacts did not occur there, however the experience with those drivers is simply terrible (external monitor feels like it is set to ~25Hz).

I also messed around with variables, however no matter how I set them, the result was always the same. They are pasted here anyway:
```
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

env = SDL_VIDEODRIVER,wayland
env = _JAVA_AWT_WM_NONREPARENTING,1
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC,1
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm

env = MOZ_DISABLE_RDD_SANDBOX,1
env = MOZ_ENABLE_WAYLAND,1

env = OZONE_PLATFORM,wayland
```

### How to reproduce

(everything is already described above)

### Crash reports, logs, images, videos
![20240209_204616](https://github.com/hyprwm/Hyprland/assets/59799831/43f1ccb4-a5a2-46d4-9b18-56e2f3f63e28)

**Comment by vaxerski** [comment]
nvidia is not officially supported. Looks like your drivers are not having a good day.
