### ISSUE TITLE
Hyprland not starting up in default fish shell

### ISSUE THREAD

**Issue by arpangreat** [hyprwm/Hyprland#4662]
I have changed my user default shell to fish using chsh. My root shell is still dash.

But somehow in this case hyprland not starting up and stays at login manager.

Any work arounds ?

**Comment by MahouShoujoMivutilde** [comment]
Do you actually need fish as a default user's shell, or do you want it as an _interactive shell_ first and foremost?

If the latter - don't change the default shell and just run your terminal with a different shell. 

e.g.


```
bind = SUPER, RETURN, exec, foot fish
```

**Comment by arpangreat** [comment]
I get your point, but plasma ( wayland ) , bspwm , i3, awesome ( wayland ) working normally in that case, so why shouldn't hyprland ?

**Comment by hiddenruins** [comment]
Logs?

I have fish as the default shell and it's working without issues. 

I don't use a login manager. Just `Hyprland` from TTY.

**Comment by pdamianik** [comment]
Sounds like this issue is between SDDM (if you are using plasmas display manager) and Hyprland. I am running fish as my users login shell, bash as the `/bin/sh` symlink and GDM as my login manager and Hyprland boots up fine.

**Comment by arpangreat** [comment]
@pdamianik I'll try it out and see if Sddm is the issue maker

**Comment by arpangreat** [comment]
Yup that was a sddm issue. Thanks for pointing that out.

**Comment by pdamianik** [comment]
Still, I find it strange that only Hyprland fails to start. I might investigate this issue a little more so a log capture would be helpful.

**Comment by pdamianik** [comment]
Allright its a known SDDM issue and not something specific to Hyprland. Related issues:
 - sddm/sddm#1592
 - sddm/sddm#1391 - proposes the fix add `export -n PROFILEREAD` to `~/.profile` for openSUSE Users

**Comment by acuteaura** [comment]
nixos-23.11 is broken too :/ https://github.com/NixOS/nixpkgs/issues/287646

**Comment by DartMitai** [comment]
> Журналы?
> 
> По умолчанию у меня установлена оболочка fish, и она работает без проблем.
> 
> Я не использую менеджер логинов. Только `Hyprland` через TTY.

how do you run it via tty?
`# Start X at login
if status is-login
    if test -z "$DISPLAY" -a "$XDG_VTNR" = 1
        exec startx -- -keeptty
    end
end`
I tried using this method, but tty1 just hangs and looks through cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 1)/hyprland.log in tty2 it is not possible to write about the absence of a file
