### ISSUE TITLE
movewindow changes cyclenext order

### ISSUE THREAD

**Issue by megumintyan** [hyprwm/Hyprland#4663]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ded174d6e5d14bc376919194cbc52c238a07f640 dirty (misc: remove unused var).
Date: Tue Feb 6 02:39:19 2024
Tag: v0.35.0-5-gded174d6
```

</details>

### Bug or Regression?

Bug

### Description

when moving windows or changing the master client `cyclenext` changes the order

### How to reproduce

1. open 3-4 clients
2. try cyclenext
3. movewindow or change master client (layout doesn't matter)
4. try cyclenext

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/34505936/4b91cc2d-1a56-4889-8eff-4e98780e1304

**Comment by thejch** [comment]
hyprctl dispatch layoutmsg cyclenext?

**Comment by megumintyan** [comment]
layoutmsg cyclenext is working
