### ISSUE TITLE
Only me or gesture pinch zoom on tochpad is not working ?

### ISSUE THREAD

**Issue by wgnalvian** [hyprwm/Hyprland#4665]
### Description

I don't know if the pinch zoom feature is there or not but it doesn't work on my laptop.

**Comment by fufexan** [comment]
It only works in applications that support it (browsers, image viewers, etc). Whole-screen zooming isn't controlled with the touchpad, but with [`misc:cursor_zoom_factor`](https://wiki.hyprland.org/Configuring/Variables/#misc).

**Comment by wgnalvian** [comment]
even my chrome cannot use pinch zoom gesture :( . yeahh i has tried misc:cursor_zoom_factor and its only zoom my window. but thankyou @fufexan
