### ISSUE TITLE
Window width can become less than 0, which causes a crash.

### ISSUE THREAD

**Issue by Sheryna1** [hyprwm/Hyprland#4666]
![240210_17h35m09s_screenshot](https://github.com/hyprwm/Hyprland/assets/75541035/4462a623-586c-41e0-bd70-86a48af388aa)
### Hyprland Version

OS: archlinux
Hyprland ver: latest update (installed with hyprdots)

### Bug or Regression?

Bug

### Description

When you have 3 or more windows on 1 monitor horizontally tiled and 1 of them has the minimal width you can increase width of any other window until width of other window becomes less than 0, which causes a crash.

### How to reproduce

1) Have 3 windows horizontally tiled.
2) Make 1 window have minimal possible width.
3) Increase width of any other window
4) Get crashed to swaylock

**Comment by Sheryna1** [comment]
Same behaviour with vertical tiling

**Comment by vaxerski** [comment]
fixed in git. Plus, "latest update" is not a version.
