### ISSUE TITLE
hyprpm missing headers

### ISSUE THREAD

**Issue by kaspernyhus** [hyprwm/Hyprland#4668]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I'm getting the missing headers error when running any hyprpm command

this is where it fails, I think:
```
/bin/sh: line 1: cd: subprojects/wlroots/build/include: No such file or directory
```

### How to reproduce

hyprpm -v update

### Crash reports, logs, images, videos

kaspernyhus@archlinux:~$ hyprpm -v update
[v] version returned: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

[v] parsed commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47 at branch HEAD

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                                                                                                  
✔ cloned                                                                                                                                                                                 
[v] git returned: Your branch is up to date with 'origin/main'.                                                                                                                          
HEAD is now at 84ab8d11 props: bump ver to 0.35.0

✔ checked out to running ver                                                                                                                                                             
! configuring Hyprland                                                                                                                                                                   
[v] setting PREFIX for cmake to /home/kaspernyhus/.local/share/hyprpm/headersRoot                                                                                                        
[v] cmake returned: Not searching for unused variables given on the command line.                                                                                                        
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gathering git info
-- Found Python3: /usr/bin/python3.11 (found version "3.11.7") found components: Interpreter 
Building itab.c/itab.h...
-- Setting up wlroots
-- Found WaylandScanner at /usr/bin/wayland-scanner
-- Found wayland-protocols at //usr/share/wayland-protocols
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.0") 
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Checking for modules 'wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;libdrm;xkbcommon;libinput;pango;pangocairo;pixman-1'
--   Found wayland-server, version 1.22.0
--   Found wayland-client, version 1.22.0
--   Found wayland-cursor, version 1.22.0
--   Found wayland-protocols, version 1.33
--   Found cairo, version 1.18.0
--   Found libdrm, version 2.4.120
--   Found xkbcommon, version 1.6.0
--   Found libinput, version 1.25.0
--   Found pango, version 1.51.0
--   Found pangocairo, version 1.51.0
--   Found pixman-1, version 0.43.2
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Configuration supports execinfo
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- XWAYLAND Enabled (NO_XWAYLAND not defined) checking deps...
-- Checking for module 'xcb'
--   Found xcb, version 1.16
-- SYSTEMD support is requested (NO_SYSTEMD not defined) checking deps...
-- Looking for systemd/sd-daemon.h
-- Looking for systemd/sd-daemon.h - found
-- Checking for module 'libsystemd'
--   Found libsystemd, version 255
-- Systemd found
-- Setting precompiled headers
-- Setting link libraries
-- Checking for module 'tomlplusplus'
--   Found tomlplusplus, version 3.4.0
-- Configuring done (2.0s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/hyprland/build

[v] meson returned: sh: line 1: meson: command not found                                                                                                                                 

✔ configured Hyprland                                                                                                                                                                    
[v] installation will run: sed -i -e "s#PREFIX = /usr/local#PREFIX = /home/kaspernyhus/.local/share/hyprpm/headersRoot#" /tmp/hyprpm/hyprland/Makefile && cd /tmp/hyprpm/hyprland && make installheaders
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing sources[v] installer returned: mkdir -p /home/kaspernyhus/.local/share/hyprpm/headersRoot/include/hyprland        
mkdir -p /home/kaspernyhus/.local/share/hyprpm/headersRoot/include/hyprland/protocols
mkdir -p /home/kaspernyhus/.local/share/hyprpm/headersRoot/include/hyprland/wlroots
mkdir -p /home/kaspernyhus/.local/share/hyprpm/headersRoot/share/pkgconfig
find src -name '*.h*' -print0 | cpio --quiet -0dump /home/kaspernyhus/.local/share/hyprpm/headersRoot/include/hyprland
cd subprojects/wlroots/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /home/kaspernyhus/.local/share/hyprpm/headersRoot/include/hyprland/wlroots && cd ../../..
cd subprojects/wlroots/build/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /home/kaspernyhus/.local/share/hyprpm/headersRoot/include/hyprland/wlroots && cd ../../../..
/bin/sh: line 1: cd: subprojects/wlroots/build/include: No such file or directory
make: *** [Makefile:84: installheaders] Error 1

✖ failed to install headers with error code 2                                                                                                                                            
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed                                                                                                                       

✖ Headers missing. Please run hyprpm update to fix those.

**Comment by vaxerski** [comment]
missing deps. You need `meson`, `cmake` and `cpio` outside of hyprland deps.

**Comment by kaspernyhus** [comment]
yes, I just realized. Thanks!

**Comment by iddm** [comment]
I have everything installed, but I get the same error. Any suggestion?
