### ISSUE TITLE
Sluggish moving windows in 0.35

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [hyprwm/Hyprland#4669]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
```

</details>

### Bug or Regression?

Bug

### Description

The video faintly shows this effect, but I compiled 0.34 and confirmed that the bug is there. The bug consists in statting when dragging a window. I noticed that the more "fat" the application is, the more lags occur. Strangely enough, changing desktops  is smooth.

### How to reproduce

Drag and drop windows

### Crash reports, logs, images, videos

https://youtu.be/iuprk8g_hDc

**Comment by bvr-yr** [comment]
seems like #4542

can u tell me your monitor refresh rate and mouse model? just to confirm

**Comment by IgnIVertiKalCaD** [comment]
> seems like #4542
> 
> can u tell me your monitor refresh rate and mouse model? just to confirm

I have 2 test stands:

comp - 2 monitors (60Hz and 75Hz) AMD gpu
laptop - 2 monitors (60Hz and 60Hz) INTEL gpu

Statters on the laptop are absent, lags on the comp.

Mouse - logitech master 2s

**Comment by Aman49362** [comment]
> seems like #4542
> 
> can u tell me your monitor refresh rate and mouse model? just to confirm

i am having the same issue 

laptop monitor 60hz 1366x768
mouse dell ms116 (a basic mouse)

it started happening from 0.35 update and still remains on 0.36
