### ISSUE TITLE
Default size for floating windows

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#467]
# Problem
When you float a window it stays the same size which makes the fact that it has floated unobvios and means it covers a tremendios portion of the screen so I have to resize (and move) it.
# Solution
I think that there should be an option for how a window will resize and reposition itself when you float it EG: when I float a window it moves to 50x50 and resies to 450x600

**Comment by vaxerski** [comment]
it gets an animation, unless you've disabled window animations.

> I think that there should be an option for how a window will resize and reposition itself when you float it EG: when I float a window it moves to 50x50 and resies to 450x600

No, I am probably in the future gonna make it return to its' previous floated size.

**Comment by frigaut** [comment]
> No, I am probably in the future gonna make it return to its' previous floated size.

Indeed, that would be the best I think.

**Comment by godalming123** [comment]
ok

**Comment by vaxerski** [comment]
done in 4ea37fe64d74600c7a89246dfa42ab6f52794c6c

**Comment by godalming123** [comment]
1 bug: when I have 1 window and no gaps turned on if I float said window it has no corner rounding

**Comment by vaxerski** [comment]
fixed
