### ISSUE TITLE
GPU spikes after enable/disable `mouse_move_enables_dpms`

### ISSUE THREAD

**Issue by patch-jh** [hyprwm/Hyprland#4670]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```
</details>

### Bug or Regression?

Bug

### Description

Hi, 

I was thiking that I had some error in my config, because I have really high iGPU use. But seems that it is related with the `mouse_move_enables_dpms`.

See this: https://www.reddit.com/r/hyprland/comments/1anfyrf/config_to_minimal_gpu_use_to_save_battery_life/

The user [kakaduuu6996](https://www.reddit.com/user/kakaduuu6996/) was trying to help me, but after enable/disable the `mouse_move_enables_dpms` he also had this spikes.

Maybe this can be related with: https://github.com/hyprwm/Hyprland/issues/2669, and this https://github.com/hyprwm/Hyprland/issues/3747

I have an `CPU: Intel i5-10210U (8) @ 4.200GHz` but kakaduuu6996 uses a `Ryzen 7 5700u`.

### How to reproduce

Enable the option 

```
misc { 
    mouse_move_enables_dpms = true
}
```

And try to disable it....

**Comment by Danvenrit** [comment]
Got the exactly same problem!
enabled mouse_move_enables_dpms

problem isn't fixed even after turning it off and changin back to older backup dotfiles.

With vrr on I idle at 0 gpu usage, and very low cpu usage, but when mouse is moved 15-30% gpu usage instantly. 

When vrr is off 26% gpu usage at idle. before this setting change there was no issue at all!

**Comment by vaxerski** [comment]
what's the issue? enabling it causes gpu spikes or disabling it?

**Comment by Danvenrit** [comment]
After enabling it. The issue occurs, and doesn't get fixed after turning it off. I'm not quite sure why.

**Comment by patch-jh** [comment]
There is another files besides ~/.config/hypr/hyprland.conf to completely reset hyprland?

Because I tried to clean install without set `mouse_move_enables_dpms` and I yet have the spikes.

**Comment by vaxerski** [comment]
honestly I think this is unrelated to hyprland?

> After enabling it. The issue occurs, and doesn't get fixed after turning it off. I'm not quite sure why.

What fixes it then?

> There is another files besides ~/.config/hypr/hyprland.conf to completely reset hyprland?

Nope

**Comment by patch-jh** [comment]
This is my config, you see something that can causes these spikes?

```
monitor=, 1920x1080@60, 0x0, 1

# External Config
source = ~/.config/hypr/mocha.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/windowrule.conf

#env = WLR_DRM_DEVICES,/dev/dri/card1
#env = QT_QPA_PLATFORMTHEME,qt6ct 


# Keyboard Layout
input {
    kb_layout = br
    numlock_by_default = true
    follow_mouse = 1 
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}


general {
    gaps_in = 4
    gaps_out = 4
    border_size = 3
    col.active_border = rgba(FF0000FF)
    col.inactive_border = rgba(FFFFFFFF)
    no_border_on_floating = false
    no_cursor_warps = true
    layout = dwindle
}

decoration {
    rounding = 3
    drop_shadow = false
    shadow_range = 4
    shadow_render_power = 3
    blur {
        enabled = false
    }
}

animations {
    enabled = no
    # animation = workspaces, 1, 3, default
}


dwindle { 
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master { #Default from the OG Hyprland Conf
    new_is_master = true
}


debug {
    # overlay = yes 
}

misc { 
    mouse_move_enables_dpms = true
    vfr = true
    vrr = 1
    # animate_manual_resizes = true
    # mouse_move_focuses_monitor = true
    disable_splash_rendering = true
    disable_hyprland_logo = true
    enable_swallow = false
    swallow_regex = ^(wezterm)$  
    focus_on_activate = true
    no_direct_scanout = true
    # animate_mouse_windowdragging = true
}


```

**Comment by Danvenrit** [comment]
well, I'm not sure, but when I change to gnome desktop wayland version I do not have the issue at all.

**Comment by patch-jh** [comment]
> well, I'm not sure, but when I change to gnome desktop wayland version I do not have the issue at all.

Me either!

**Comment by vaxerski** [comment]
sounds like a general issue then unrelated to the config option, though

**Comment by patch-jh** [comment]
I am not sure what you mean by:

> Have you tried -git?

I suppose that is to git clone and compile/install Hyprland from the version in git. If yes, I compiled it. Yet, I have the same issues.

My iGPU, with mouse moviments has 20% to 40% of use by Hyprland.

![1707621685_grim](https://github.com/hyprwm/Hyprland/assets/159664499/fc050a58-ddcd-475e-ac5f-fe0fcc1ab3ed)

**Comment by Danvenrit** [comment]
well it must be, since gpu usage is under hyprland.
![image](https://github.com/hyprwm/Hyprland/assets/63874507/05b9b1fa-77cb-42ef-8981-bb0a926be44c)
Also this kind of gpu usage is present only when mouse is moved when vfr is turned on, but when vfr is turned off it's idling at that gpu usage.

**Comment by Danvenrit** [comment]
smaller update: I tried downgrading using Downgrade to different versions of hyprland, and I found that at version 0.29 the gpu issue is not present. anything above that the issue is present.

**Comment by vaxerski** [comment]
`git bisect` then please :)

**Comment by NNxCLUTCHERxCPP** [comment]
this also happens when I hold down a button for example the letter "d" in my browser search field, but it doesn't increase the GPU usage to extreme amount when doing the same in a terminal

**Comment by NNxCLUTCHERxCPP** [comment]
❯ git bisect good
2ebfd0c7456eff7e9c03d379d1dfbc611dc26672 is the first bad commit
commit 2ebfd0c7456eff7e9c03d379d1dfbc611dc26672
Author: Vaxry <43317083+vaxerski@users.noreply.github.com>
Date:   Fri Nov 24 10:54:21 2023 +0000

    renderer: Move to a full Hyprland GL rendering pipeline (#3920)

    Also updates wlroots

 .github/workflows/ci.yaml        |   2 +-
 CMakeLists.txt                   |   2 +-
 flake.lock                       |   8 +-
 flake.nix                        |   2 +-
 src/Compositor.cpp               |   5 +-
 src/Compositor.hpp               |   4 +-
 src/debug/TracyDefines.hpp       |   9 ---
 src/events/Events.hpp            |   6 +-
 src/events/Misc.cpp              |  14 ----
 src/events/Windows.cpp           |   2 +-
 src/helpers/Monitor.cpp          |   9 +++
 src/helpers/Monitor.hpp          |  54 ++++++-------
 src/helpers/Region.cpp           |   9 +++
 src/helpers/Region.hpp           |   2 +
 src/includes.hpp                 |   4 +-
 src/managers/XWaylandManager.cpp |  10 ++-
 src/protocols/Screencopy.cpp     |  24 +++---
 src/protocols/ToplevelExport.cpp |  62 ++++-----------
 src/render/Framebuffer.cpp       |  15 ++++
 src/render/Framebuffer.hpp       |   1 +
 src/render/OpenGL.cpp            | 109 +++++++++++++++-----------
 src/render/OpenGL.hpp            |  22 ++++--
 src/render/Renderbuffer.cpp      |  81 +++++++++++++++++++
 src/render/Renderbuffer.hpp      |  25 ++++++
 src/render/Renderer.cpp          | 163 ++++++++++++++++++++++++++++++---------
 src/render/Renderer.hpp          |  47 +++++++----
 subprojects/wlroots              |   2 +-
 subprojects/wlroots.wrap         |   2 +-
 28 files changed, 459 insertions(+), 236 deletions(-)
 create mode 100644 src/render/Renderbuffer.cpp
 create mode 100644 src/render/Renderbuffer.hpp

**Comment by vaxerski** [comment]
so... in short, high gpu usage when moving your mouse? That's it?

I assume WLR_NO_HARDWARE_CURSORS is _not_ set?

**Comment by Danvenrit** [comment]
for me it's not. but setting it makes no difference in my case.

**Comment by vaxerski** [comment]
can you try on latest git?

**Comment by Danvenrit** [comment]
For me it didn't do much (I'm assuming hyprland-git on AUR is the latest build). 
But again it does it when I move my mouse, but this is when vrr is turned on, but when vrr is off the same gpu usage we are talking about is constant, even at idle, I do have all the animations and such turned off fully.

**Comment by SnipeXandrej** [comment]
I have the same behavior as @Danvenrit 

With **VFR** (not VRR) set to true, while not moving my mouse the GPU usage of the Hyprland process is 1%, while moving my mouse, the GPU usage of Hyprland goes to 21%.

With VFR set to false, the GPU usage of Hyprland is always 21%, regardless if I move my mouse or not.

Changing **VRR** does not make any difference on my system.

This is on Arch with hyprland-git 289d952a6ee02f6d54a0899870bbec52ff9a53df on a Zephyrus G15 GA502IV (Ryzen 9 4900HS / Vega 8)

**Comment by Kagukara** [comment]
Just installed `hyprland-git` for the first time and edited the config a little, turned off `drop_shadow`, `animations` and set my monitors to how I have them in `sway`.
```
monitor=desc:Samsung Electric Company Odyssey G7 H1AK500000,modeline 1498.25 3840 4192 4616 5392 2160 2163 2168 2316 -hsync +vsync,1920x1080,1,vrr,1,bitdepth,10
monitor=desc:Ancor Communications Inc VG248 DCLMQS078349,1920x1080@60,0x1280,1
monitor=desc:Dell Inc. DELL P2418D MY3ND7B70VLT,1920x1080@60,2810x0,1
```
- GPU: MD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 16.0.6, DRM 3.57, 6.7.5-arch1-1)
- GPU Driver: 4.6 Mesa 24.0.1-arch1.1

With the mouse not moving my GPU uses ~9W of power. Moving the mouse on the 3840x2160 monitor causes the GPU to 40W and the 1920x1080 monitors to 20W.

On `sway` the GPU power only goes up to 12W on the 3840x2160 monitor and stays at ~9W on the 1920x1080 monitors.

**Comment by NNxCLUTCHERxCPP** [comment]
I am on commit 7e8bcd67 and issue persist

**Comment by Danvenrit** [comment]
> I have the same behavior as @Danvenrit
> 
> With **VFR** (not VRR) set to true, while not moving my mouse the GPU usage of the Hyprland process is 1%, while moving my mouse the GPU usage of Hyprland goes to 21%.
> 
> With VFR set to false, the GPU usage of Hyprland is always 21%, regardless if I move my mouse or not.
> 
> Changing **VRR** does not make any difference on my system.
> 
> This is on Arch with hyprland-git [289d952](https://github.com/hyprwm/Hyprland/commit/289d952a6ee02f6d54a0899870bbec52ff9a53df) on a Zephyrus G15 GA502IV (Ryzen 9 4900HS / Vega 8)

Yes it's vfr for me too, my mistake.

**Comment by NNxCLUTCHERxCPP** [comment]
With VFR set to false, the GPU usage of Hyprland is 51% in my case. My Monitor runs @ 360Hz

**Comment by tharrmeehan** [comment]
![Screenshot_18-Feb_11-19-59_4843](https://github.com/hyprwm/Hyprland/assets/58373200/ada9ed06-affa-4f76-8ae2-d8860b13a1b0)
Can also confirm, it seems moving my cursor around firefox increases CPU usage as well and my GPU usage is constantly at 50-70%. Changing VFR does not do anything, neither does changing resolution or turning off shadows/blur and animations. Using the latest hyprland-git.

**Comment by Danvenrit** [comment]
> ![Screenshot_18-Feb_11-19-59_4843](https://private-user-images.githubusercontent.com/58373200/305705804-ada9ed06-affa-4f76-8ae2-d8860b13a1b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTIxMzcsIm5iZiI6MTcwODI1MTgzNywicGF0aCI6Ii81ODM3MzIwMC8zMDU3MDU4MDQtYWRhOWVkMDYtYWZmYS00Zjc2LThhZTItZDg4NjBiMTNhMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDEwMjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNGMwOTZjNGI3ZjNkOGIxM2FhMTRmZTE1MDYzZjNiZTBlOTljN2Q4MWQ1ODVjNWUxMWUzOWE5MWNjOGFiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d10vqVMS8bEeVbWc5bX9MsVCF7vHqY3stnsTgaIiiKk) Can also confirm, it seems moving my cursor around firefox increases CPU usage as well and my GPU usage is constantly at 50-70%. Changing VFR does not do anything, neither does changing resolution or turning off shadows/blur and animations. Using the latest hyprland-git.

is vrr set to 1? because if set to 1 it will always be enabled, and not just for fullscreen apps.

**Comment by tharrmeehan** [comment]
> > ![Screenshot_18-Feb_11-19-59_4843](https://private-user-images.githubusercontent.com/58373200/305705804-ada9ed06-affa-4f76-8ae2-d8860b13a1b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTIxMzcsIm5iZiI6MTcwODI1MTgzNywicGF0aCI6Ii81ODM3MzIwMC8zMDU3MDU4MDQtYWRhOWVkMDYtYWZmYS00Zjc2LThhZTItZDg4NjBiMTNhMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDEwMjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNGMwOTZjNGI3ZjNkOGIxM2FhMTRmZTE1MDYzZjNiZTBlOTljN2Q4MWQ1ODVjNWUxMWUzOWE5MWNjOGFiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d10vqVMS8bEeVbWc5bX9MsVCF7vHqY3stnsTgaIiiKk) Can also confirm, it seems moving my cursor around firefox increases CPU usage as well and my GPU usage is constantly at 50-70%. Changing VFR does not do anything, neither does changing resolution or turning off shadows/blur and animations. Using the latest hyprland-git.
> 
> is vrr set to 1? because if set to 1 it will always be enabled, and not just for fullscreen apps.

Yessir, enabling it does not change anything. I'm not sure if this makes a difference though, since I'm on a 60hz display anyways.

**Comment by NNxCLUTCHERxCPP** [comment]
@vaxerski on sway I have 0% GPU usage when moving my mouse

**Comment by vaxerski** [comment]
found the issue, working on a fix.

**Comment by patch-jh** [comment]
I can confirm the fix!

Thank you very much!

**Comment by Danvenrit** [comment]
same! thank you!

**Comment by Kagukara** [comment]
> Just installed `hyprland-git` for the first time and edited the config a little, turned off `drop_shadow`, `animations` and set my monitors to how I have them in `sway`.
> 
> ```
> monitor=desc:Samsung Electric Company Odyssey G7 H1AK500000,modeline 1498.25 3840 4192 4616 5392 2160 2163 2168 2316 -hsync +vsync,1920x1080,1,vrr,1,bitdepth,10
> monitor=desc:Ancor Communications Inc VG248 DCLMQS078349,1920x1080@60,0x1280,1
> monitor=desc:Dell Inc. DELL P2418D MY3ND7B70VLT,1920x1080@60,2810x0,1
> ```
> 
> * GPU: MD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 16.0.6, DRM 3.57, 6.7.5-arch1-1)
> * GPU Driver: 4.6 Mesa 24.0.1-arch1.1
> 
> With the mouse not moving my GPU uses ~9W of power. Moving the mouse on the 3840x2160 monitor causes the GPU to 40W and the 1920x1080 monitors to 20W.
> 
> On `sway` the GPU power only goes up to 12W on the 3840x2160 monitor and stays at ~9W on the 1920x1080 monitors.
> 
> EDIT: If this is a different issue please let me know, just didn't want to make a duplicate as this issue seemed related.
> Comment: https://github.com/hyprwm/Hyprland/issues/4670#issuecomment-1950504415

@vaxerski The latest commit didn't work for me although it brought it down from 40W to 25W. Would what I'm experiencing be a different issue?

**Comment by vaxerski** [comment]
no clue

**Comment by SMTKamikaze** [comment]
having more than 3 windows on one workspace makes the GPU usage 50% all time even when I am doing nothing but when there are 1-2 windows on one workspace then only 10%
