### ISSUE TITLE
bind sometimes not "releasing" SUPER key

### ISSUE THREAD

**Issue by tetsugakusha256** [hyprwm/Hyprland#4673]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: _
Release: 6.7.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])
00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Sunrise Point-LP Integrated Sensor Hub [8086:9d35] (rev 21)


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

```

</details>

### Bug or Regression?

Bug

### Description

The bug happens when I press SUPER to change workspace sometimes it appears it's not released and the focus window receives the SUPER key with any keys until I press SUPER again.

### How to reproduce

To make the bug happens (not systematic)
For example:
1. Be at workspace 1
2. Holding SUPER
3. Press backspace (it's my workspace previous mapping but I made it bug without previous too)
5. Type a
6. The focus window receive <D-a>(SUPER+a) instead of just a

I can't make it systematic but it happens quite often.
I noticed that pressing ANY modifier key remove the bug

**Comment by tetsugakusha256** [comment]
I saw [this](https://github.com/hyprwm/Hyprland/issues/4378) issue that seemed to have the same problem.

**Comment by izmyname** [comment]
Is this still a problem on latest git? I think there was a pr fixing this problem?

**Comment by tetsugakusha256** [comment]
This bug made me go back to X actually so I haven't checked since then.

If I have time this week I'll try to launch my Wayland config again and report back.

**Comment by tetsugakusha256** [comment]
I just launched wayland again and it seemed fixed!

Version:
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886
