### ISSUE TITLE
add an  idle managment tool with  which integrates with config file easily

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#4675]
### Description

lets be serious, swayidle, its kinda bad, i mean for me, on more laptops i tried to make it work, but every time, it just didnt want to wake hyprland from sleep, or getting screen on again after it goes black, it will be cool from the creator of hyprland to add a idle managment function inside hyprland, bc he knows the best its compositor, and integrating a idle managment tool inside te config, or maybe as a optional package would be cool, to work uk, out of the box ,like how hyprpaper, or hyprpicker. it would be cool to have another hyprland idle alternative to swayidle, which easily integrates with the hyprland config, and its smart like how hyprland is. thank you.

**Comment by vaxerski** [comment]
sounds like a misconfiguration, to be honest.

**Comment by mooncoffee1** [comment]
> check the repo [Hypridle](https://github.com/hyprwm/hypridle) . This is made by this team and the configuration is also quite simple.

yes, thats what i imagined. now its like, integrated, and its even better than swayidle, thx hypr team, ur the best!!
