### ISSUE TITLE
Special characters in Hyprland keybind conf

### ISSUE THREAD

**Issue by LVGrinder** [hyprwm/Hyprland#4676]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.34.0  ().
Date: 2024-01-01
Tag:

flags: (if any)


```

</details>

### Bug or Regression?

Bug

### Description

![Code](https://github.com/hyprwm/Hyprland/assets/60237496/b94ca614-92db-4093-a2a5-ee039e06a158)
 
Trying to add keybind to ; - , - . without any luck. Can't find documentation on being possible to escape these characters in the config

### How to reproduce

Adding keybind with special characters in hyprland config

**Comment by Haerteleric** [comment]
You cant use them with their Explicit Name:

```
bind = SUPER, COMMA, splitratio, -0.1
bind = SUPER, PERIOD, splitratio, +0.1
```

**Comment by vaxerski** [comment]
```
[14:     wl_keyboard] key: serial: 19795; time: 3641336; key: 47; state: 1 (pressed)
                      sym: semicolon    (59), utf8: ';'
```
last time I checked `;` was not a sym.
