### ISSUE TITLE
Electron apps still blurry/aliased on some setups

### ISSUE THREAD

**Issue by Spatchy** [hyprwm/Hyprland#4677]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e4bb5fa4af1a6c36aab1c28651b5403dc4952f93 dirty (input: focus monitor on mouse down).
Date: Sat Feb 10 17:39:53 2024
Tag: v0.35.0-13-ge4bb5fa4

flags: (if any)


System Information:
System name: Linux
Node name: Crane
Release: 6.7.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev e2) (prog-if 00 [VGA controller])
03:00.7 Non-VGA unclassified device [0000]: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/Renoir Non-Sensor Fusion Hub KMDF driver [1022:15e6]


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Electron/Chromium-based apps are still blurry/aliased on my fresh install of EndeavourOS. This was supposedly a bug with 0.34.0 (according to [this reddit thread](https://www.reddit.com/r/hyprland/comments/194br8s/terrible_native_font_rendering_under_hyprland_for/) but is still occurring as of more recent versions, I was on 0.35.0, before switching to `hyprland-git` to try and fix it (see output of `hyprctl systeminfo` above). I have tested this with VS Code OSS (installed from the Arch `extra` repo) and the Spotify and Discord flatpaks from flathub, all of which suffer from the issue.

### How to reproduce

This issue seems to be system-specific.

- Install any electron app
- App GUI is blurry/aliased

### Crash reports, logs, images, videos

![Code](https://github.com/hyprwm/Hyprland/assets/17989046/29cd7c8e-9215-49a0-88d0-af9e30ac6aeb)
![Discord](https://github.com/hyprwm/Hyprland/assets/17989046/a893f5b9-7ca0-4186-8692-6ddad83c328c)
![Spotify](https://github.com/hyprwm/Hyprland/assets/17989046/2a4aef17-3726-457e-988c-145b9ea3f7fa)

**Comment by romanstingler** [comment]
why don't you use wayland flags ??

```
-enable-features=WaylandWindowDecorations
-ozone-platform-hint=auto
```

**Comment by vaxerski** [comment]
yeah they will be if you don't enable xwayland:force_zero_scaling because X cannot do fractional scaling

**Comment by p6laris** [comment]
@vaxerski Thanks worked for me, but this should honestly be the default.
