### ISSUE TITLE
Opening many windows of same type crashes hyprland

### ISSUE THREAD

**Issue by benni347** [hyprwm/Hyprland#4678]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000


GPU information: 
28:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev ca) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When opening many windows of the same program tested with alacritty and kitty. It core dumps. I counted the number of windows that I opened by moth it was over 15 windows opened.

### How to reproduce

1. Open 15 windows from eg kitty

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14233192/hyprland.log)
[hyprlandCrashReport12826.txt](https://github.com/hyprwm/Hyprland/files/14233193/hyprlandCrashReport12826.txt)
[hyprland.conf](https://github.com/hyprwm/Hyprland/files/14233198/hyprland.conf.txt)

**Comment by vaxerski** [comment]
fixed in git
