### ISSUE TITLE
Cannot (mousewheel) scroll with Alacritty in hyprland

### ISSUE THREAD

**Issue by wreedb** [hyprwm/Hyprland#468]
Alacritty does not respond to scroll wheel in Hyprland. I've duplicated this 3 times on 3 different distributions (arch, fedora, gentoo) all compiled from source while following the instructions given.  I have attempted manually binding scroll wheel actions in alacritty to no evail.

steps to reproduce:
build hyprland from master branch
open alacritty
try to scroll with mouse wheel

due to alacritty being the most popular terminal amongst tiling wm users, i assumed this would have been in the issues already. I searched closed and open issues and didn't find an issue about it- so here we are

**Comment by frigaut** [comment]
I can confirm that.
Interestingly, trackpad scroll works.

**Comment by frigaut** [comment]
Related to #465 ?

**Comment by vaxerski** [comment]
probable dupe of #465
