### ISSUE TITLE
Lingering Floating Window rule

### ISSUE THREAD

**Issue by Haerteleric** [hyprwm/Hyprland#4683]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0
```

</details>

### Bug or Regression?

Bug

### Description

I recently moved from i3 to Hyperland. I'm a heavy scratchpad user so i moved most of my "glance"-Apps into a pyprland skratchpad. Later on i decided that i want a specific "Messanger"-Workspace, so i removed all messenger related Skratchpads from pyprland and started them with the following script instead:

```
$ cat .config/hypr/scripts/focusOrStart.sh 
#!/bin/sh

execCommand=$1
className=$2
workspaceOnStart=$3

running=$(hyprctl -j clients | jq -r ".[] | select(.class == \"${className}\") | .workspace.id")
echo $running

if [[ $running != "" ]]
then
	echo "focus"
	hyprctl dispatch focuswindow $className    
else 
	echo "start"
	hyprctl dispatch workspace $workspaceOnStart 
	${execCommand} & 
fi 
```
Hotkey binding in hyperland.conf:
```
bind = , W, exec, .config/hypr/scripts/focusOrStart.sh "chromium --class=whatsApp --user-data-dir=$HOME/.cache/chromium/whatsApp-webApp --app=https://web.whatsapp.com/" "whatsApp" "9"
```

Now the Problem: 
The apps always starts in a floating state and i have to manually make them tile. I don't have any window rule active for their class. Even if i completely disable pyprland the issue persists. 

### How to reproduce

- make a app a pyprland skratchpad. 
- Remove the app from pyprland
- Start the app normally

**Comment by Haerteleric** [comment]
Update: 
i noticed the floating Behavior is cause by the --app command line switch of chromium

**Comment by milesdredd** [comment]
hey i'm getting the same issue with brave web apps , 
all window from `--app` open in floating windows , tiling manually is annoying !

i have created many .desktop file with line 
`Exec=brave --app=https://[any_site].com`
which opens in floating windows always
