### ISSUE TITLE
ghost window if opened while fullscreen

### ISSUE THREAD

**Issue by daniele821** [hyprwm/Hyprland#4687]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: 

flags: (if any)
```

sorry, i don't think that output was useful, but i can say the version is 0.34.0-1.2

</details>

### Bug or Regression?

Bug

### Description

while i am focused on a fullscreen window on workspace x, and then launch an application which is opened by a windowrule on workspace y, that window is not rendered (altough it is indeed open)

https://github.com/hyprwm/Hyprland/assets/137685223/255faacb-0ada-4a9e-aaba-83ebbd761aee

### How to reproduce

- assign an application (in the video is kitty) to open on a certain workspace (in the video is on workspace 1)
- create a binding to open the application (kitty in the video) with it
- open an other application (in the video is obs) in fullscreen on an other workspace (in the video is on workspace 7) 
- launch the application (kitty in the video) with the keybinding

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14241024/hyprland.log)

**Comment by vaxerski** [comment]
0.34.0 is very old. Please test on -git.

**Comment by daniele821** [comment]
yes, from manually build at commit cca3c643 (tag: v0.35.0-15-gcca3c643), the problem is still there.

**Comment by vincentaxhe** [comment]
yeah I open a similar [issue](https://github.com/hyprwm/Hyprland/issues/4395)

**Comment by daniele821** [comment]
> yeah I open a similar [issue](https://github.com/hyprwm/Hyprland/issues/4395) before

true. Well this issue is the generalization of yours, as i think it just happens on every kind of workspace, if you open a window in it while in fullscreen.

And the strange thing is, that even if the window doesn't render, in `hyprland clients` it is listed, and also it accepts keyboard input. It basically feels as if the window had opacity set to 0, but i don't know C++ well enough to dig for the problem

**Comment by zmeyka3310** [comment]
bump, happens to me too. the window is invisble btw, since spamming the close keybind on all workspaces fixes the issue eventually. my main way to trigger it is to open firefox from apex (clicking on the watch trailer link for yt or whatever it is now)

**Comment by tomben13** [comment]
I will try to work on that. I can reproduce.
