### ISSUE TITLE
Improve usability of workspace swipe

### ISSUE THREAD

**Issue by aflyingpumpkin** [hyprwm/Hyprland#469]
While using the workspace swipe feature I ran into two distinct issues:
1: If I am on workspace 10, with windows open in all other workspaces I need to swipe 9 times or use keyboard shortcut to get back to workspace 1.
2: I am unable to open up an empty workspace.

The first issue can be fixed by adding a config option to allow wrapping the workspace swipe gesture.

The second issue is a bit more difficult to fix in an intuitive way. One way is to add in a config option to allow actually swapping between workspaces and not workspaces with windows, though when the user is not trying to open a blank workspace this feature becomes annoying. Another is to do as mentioned in #385 and open a new workspace when swiping on the final workspace, though this solution runs into a problem if workspace 1 and 3 have windows open. In this scenario it would be impossible to open workspace 2, and workspace 4 would instead be opened. Some logic could be implemented to circumvent this but that logic would likely cause the workspace number to teleport in an unnatural way. Due to this, I believe these are the best ways of addressing this issue:
- Seperate gesture (different amount of fingers) for switching between workspaces and workspaces with windows.
- Configurable key to hold down when using the gesture, that changes the behavior.
- Way to add a keybind to toggle between different behaviors.

**Comment by vaxerski** [comment]
swiping on last will now create a new workspace by default, can be disabled

**Comment by vaxerski** [comment]
all of this is configurable and has been for a while now I believe
