### ISSUE TITLE
Mouse Click Accuracy Degraded After Upgrading to 0.35

### ISSUE THREAD

**Issue by mtwb47** [hyprwm/Hyprland#4691]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch main at commit 890307532caa3369ea089b606b7786ccce4b8504 dirty (input: avoid reassigns of unchanged surfaces in processMouseRequest).
Date: Mon Feb 12 15:02:00 2024
Tag: v0.35.0-18-g89030753

flags: (if any)


System Information:
System name: Linux
Node name: ares
Release: 6.7.4-1-default
Version: #1 SMP PREEMPT_DYNAMIC Tue Feb  6 05:32:37 UTC 2024 (01735a3)


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240208"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240208"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240208:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240208"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

When clicking to place the cursor in text or to highlight text, the cursor is consistently inaccurate by at least on character, as seen in the video linked here. https://imgur.com/a/GA2ErZD  

On the first part of the video, I clicked on the right side of the "p" yet the highlight started on the left side. In the second attempt, I clicked on the right side of the "e" and it started the highlight on the left. 

This happens in both Vivaldi, Discord, and Zimwiki. At first I thought it would be because of Chrome/Electron whatever, but Zim is not an electron app. 

Sorry if this isn't a good explanation of what's happening, unsure how to explain it better. It's very annoying as it feels as if the mouse clicks are happening slightly to the left of where I want them to be.

Using openSUSE tumbleweed, with hyprland built from source. 

### How to reproduce

Unsure, other than to click on things. 

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14256224/hyprland.log)

**Comment by mtwb47** [comment]
Just to add some more, I tested this on Xmonad and do not have the same issue. I wanted to ensure this wasn't an openSUSE thing.

**Comment by ajiiisai** [comment]
Happens to me as well.

<details>
<summary>System Info</summary>

```
Hyprland, built from branch main at commit 890307532caa3369ea089b606b7786ccce4b8504 dirty (input: avoid reassigns of unchanged surfaces in processMouseRequest).
Date: Mon Feb 12 21:02:00 2024
Tag: v0.35.0-18-g89030753

flags: (if any)


System Information:
System name: Linux
Node name: gensokyo
Release: 6.7.4-273-tkg-bore
Version: #1 SMP PREEMPT_DYNAMIC TKG Sun, 11 Feb 2024 00:45:54 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])
14:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev cb) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

**Comment by frkli1965** [comment]
Same here...

Culprit appears to be commit #8903075 as rolling back to previous commit (#f33d73b) resolves the issue.

**Comment by cprin21** [comment]
Also getting this issue. I thought it was wl-clip-persist which enabling its primary clipboard feature causes this inaccuracy bug (normal clipboard does not). Seems others are getting this from Hyprland itself.

**Comment by NamelessDev0000** [comment]
Yes, same issue here

**Comment by ErynGalen** [comment]
It looks like the `|` cursor (as well as the hand one) isn't at the correct location.

https://github.com/hyprwm/Hyprland/assets/115268502/6f98fcc7-a04d-40ab-be64-658948ab4d24

**Comment by cmargiotta** [comment]
Same issue here, using NixOS.
