### ISSUE TITLE
Wokspace Float WIndows by Default

### ISSUE THREAD

**Issue by TsujimotoYukasuke** [hyprwm/Hyprland#4692]
### Description

Please add a workspace rule for having all windows within that workspace to float.

I noticed a possible duplicate of this request: #1682, but I believe that the difference here is that I would like there to be a workspace that floats all windows by default rather than having a keybind to do that instead.

**Comment by hiddenruins** [comment]
You can add windowrule for a certain workspace. http://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2

`windowrulev2 = float, workspace:< id or name: and name>`

eg
`windowrulev2 = float, workspace:5`

**Comment by dlealmt** [comment]
@TsujimotoYukasuke why do you want this? Could you describe your use-case?

**Comment by vaxerski** [comment]
as above

**Comment by TsujimotoYukasuke** [comment]
> @TsujimotoYukasuke why do you want this? Could you describe your use-case?

I would like to use Hyprland as both a Stacking and Tiling Window Manager. Keeping specific workspaces as Stacking so that I can have the standard Desktop experience, but having others as Tiling for work related tasks where having multiple windows that I can switch between using keybindings would be nice.

Most window managers I know of have this functionality in some way.

> You can add windowrule for a certain workspace. http://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2
> 
> `windowrulev2 = float, workspace:< id or name: and name>`
> 
> eg `windowrulev2 = float, workspace:5`

I tried doing this before (and tried again just now), but it does not seem to work.

**Comment by TsujimotoYukasuke** [comment]
@vaxerski

Hey, if this really is just something you guys don't want to add, then that's fine. I'm pinging you just in case you closed this out of the assumption that my issue was resolved.

**Comment by vaxerski** [comment]
this does work, just verified.

**Comment by TsujimotoYukasuke** [comment]
Modified my config, was using this: `windowrulev2 = float,workspace:1,workspace:2`, changed it to this:
```
windowrulev2 = float, workspace:1
windowrulev2 = float, workspace:2
```

I'm a bit embarrassed right now, but I should have copied exactly instead of assuming how the config syntax works. Sorry about that, and thank you for the help.
