### ISSUE TITLE
Export highest resolution monitor to programms or define a primary display

### ISSUE THREAD

**Issue by jakob-scholz** [hyprwm/Hyprland#4699]
### [Problem]
When using two monitors with different resolutions and the lower resolution monitor is picked as primary, the lower resolution is exported to most apps and someone refuse to accept any resolution higher than the lower resolution monitor.
This means If Hyprland picks a monitor, the games might refuse to run at the resolution of the highest monitor, resuling in n low quality and streching if another monitor is used than the primary.

### [Fix]
The resolution that apps and games get is the highest resolution of all monitors instead of the primary.
As Alternative settinge the primary monitor via the config would bei a viable fix too.

### [Example]

how the config could look:

`
monitor=eDP-1,1920x1080@60,0x0,1,primary
`

this would set the display as primary for wayland and Xwayland application.

Sorry if this is the wrong place to report this, i am quite new to bug reports.

**Comment by vaxerski** [comment]
wayland has no such thing as a primary display.

For xwayland you can do it with xrandr.
