### ISSUE TITLE
Option to disable rounding 

### ISSUE THREAD

**Issue by pinkcreeper100** [hyprwm/Hyprland#470]
rounding=0 in the config does not disable rounding

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/182881701-6a1a96f1-8b27-476b-b850-fe354ea4be40.png)

?

**Comment by pinkcreeper100** [comment]
That is still rounded (and looks kinda jank tbh)

**Comment by vaxerski** [comment]
the window is not.

**Comment by pinkcreeper100** [comment]
but the border has a diagonal line

**Comment by vaxerski** [comment]
yes

**Comment by pinkcreeper100** [comment]
what I would normally expect is to have 90° corners

**Comment by pinkcreeper100** [comment]
Rather than two 45°

**Comment by vaxerski** [comment]
fixed in 3947fe9e9f8fb2912b969a20fbbec3f2ab62cef0
