### ISSUE TITLE
Merge or add hyprXPrimary plugin to allow set xwayland primary displays and resolutions within hyprland itself

### ISSUE THREAD

**Issue by AlexanderCurl** [hyprwm/Hyprland#4700]
### Description

Please take a look at https://github.com/zakk4223/hyprXPrimary

This plugin allows to set X11 apps primary display on wayland, which should not be a plugin, it should be a main functionality within hyprland itself.
Please consider adding it in the future, it lacks the feature to set resolutions though, that should be a nice addition to it if it's possible.

Setting display properties should be in the main project I think, this is very neat and works at the most part as I tested.

Found some quirks with it, which probably requires a little digging, on the secondary screen now, my cursor is shifted down a little bit once the plugin ran.

Thanks your awesome work, keep it up.

**Comment by vaxerski** [comment]
No. You can literally `exec-once` one xrandr command.

**Comment by zakk4223** [comment]
You can't exec-once an xrandr command. 

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2988

wlroots sets a flag that causes the xwayland server to clean up and exit after some idle time with no x11 clients connected. When it restarts the --primary flag is lost. It's also lost if the monitor disconnects+reconnects. (or sleeps)

If you could just xrandr it once and never worry about it again, I wouldn't have written the plugin to begin with.

This really feels like something that should be addressed in wlroots, but they've shown little interest in it over the last few years, and I suspect even less people will care once wine goes wayland native.

**Comment by vaxerski** [comment]
likely. Anyways, supporting legacy xwayland isn't my top priority
