### ISSUE TITLE
focus_on_activate as a window rule like how there are nofullscreenrequest and nomaximizerequest

### ISSUE THREAD

**Issue by UserSv4** [hyprwm/Hyprland#4705]
### Description

Fixes issues like https://github.com/hyprwm/Hyprland/issues/3870 without having to have apps provide any additional settings

**Comment by vaxerski** [comment]
what?

**Comment by vaxerski** [comment]
I think 7f52db806c149cb3331d6567706e7c19f5a8b692 closes this
