### ISSUE TITLE
Bring back the mascot

### ISSUE THREAD

**Issue by blacklightpy** [hyprwm/Hyprland#4706]
### Description

I saw on Reddit that the Hypr-chan wallpapers have been removed. The boomers still using Reddit in 2024 are now rejoicing in the fact that Hyprland has become more matured. I think it has become less cool, perhaps we might even call it Boomerland now. Speaking on behalf of Gen-Z and feminism, I protest that Hypr-chan be added back.

From Reddit:
> Nothing said "accessible software for everyone" than a drawing of an overtly sexualised girl... Good riddance.

The girl is not even overly sexualized. It's just a cool girl wearing nice outfits. Only the patriarchy would ever say something like that.

Nothing says "accessible software for everyone" than based non-corpo pilled software with a waifu mascot.

I see from the commit that there was a contest, and I don't know how it was conducted. If I were to know nothing better, I'd say the voting was hijacked by corporate AI to enforce the will of American right wing traditionalist capitalists. How did [this abomination](https://raw.githubusercontent.com/hyprwm/Hyprland/v0.35.0/assets/wall1.png) (which is the corpse of Hypr-chan, how disrespectful) win instead of [this](https://hyprland.org/imgs/blog/contestWinners/Meptl.png)?

To the complaining boomers: the future is now, old man.

### Ideas (for people who have complaints)
- For people afraid of installing Hyprland on projector: Man up and stand for the rights of women
- For boomers who hate anime girls: That's against feminism, level up to the 21st century
- For people who hate anime: Anime is better than reality so shut up
- If these don't work: On first launch, ask if you are chad enough to be in the presence of Hypr-chan, our mascot. If no, set `disable_hyprland_logo` to `true` before loading the wallpaper.

**Comment by vaxerski** [comment]
firstly, https://github.com/hyprwm/Hyprland/blob/main/assets/wall2.png

secondly, I don't care about you protesting

**Comment by blacklightpy** [comment]
> secondly, I don't care about you protesting

neither do I, as this is a joke.

Also the old one was subjectively better but I guess you've made your choice.
