### ISSUE TITLE
[hyprctl] Source keyword for hyprctl.

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#4709]
### Description

```bash
hyprctl source ~/.config/path/to/some/file.conf
```
This will make it easier to source some stuff and less translation of everything to hyprctl when working in scripts.

Also, hyprctl source can take input from `stdin` e.g `cat file | hyprctl source`

As recently I started using hycov plugin and whenever I log in hyprland reports dispatcher is invalid and then the error goes, as in the meantime `hyprpm reload` has kicked in.

Was thinking to perform this in a script so that after login the mapping is only loaded when the plugins are reloaded

**Comment by niksingh710** [comment]
https://github.com/DreamMaoMao/hycov/issues/81

**Comment by zakk4223** [comment]
While this may or may not be a good feature, I feel like it's just masking an issue that needs fixing other ways. 

Now that plugins are mostly loaded via hyprpm there's enough of a delay that any plugin that defines dispatchers/keywords etc causes a big red banner to show up until hyprpm reload finishes. It's kind of a crap user experience to get a big red banner that goes away 1 or 2 seconds later every time you launch hyprland. (for me personally it was annoying enough i just turned off the syntax error banner)


Any idea i have to fix this involves some sort of blocking exec mechanism in the config file :/

**Comment by niksingh710** [comment]
> (for me personally it was annoying enough i just turned off the syntax error banner)

can you please explain how you did it?

**Comment by zakk4223** [comment]
debug { 
 suppress_errors=true
}

**Comment by bvr-yr** [comment]
```sh
hyprctl keyword source ~/.config/path/to/some/file.conf
```
?

**Comment by niksingh710** [comment]
> ```shell
> hyprctl keyword source ~/.config/path/to/some/file.conf
> ```
> 
> ?

Wow 
never gave this a thought 
after seeing, you mentioning this, it feels so obvious.
