### ISSUE TITLE
adding version file for flake builds

### ISSUE THREAD

**Issue by luxus** [hyprwm/Hyprland#471]
i would expect Hyprland --version would display the version (and last commit)
but it shows me no error.. just the help

**Comment by vaxerski** [comment]
`hyprctl version`??

**Comment by luxus** [comment]
~~> hyprctl version
    Hyprland, built from branch  at commit dirty ().
    flags: (if any)
    debug

**Comment by luxus** [comment]
i use the nixos flake so it should report 0.9.1?

**Comment by vaxerski** [comment]
it reports nothing because you're building with meson and @fufexan has not yet added versioning for meson. It only works through CMake.

**Comment by luxus** [comment]
thanks for answering, i guessed it has todo with the manual build situation

**Comment by fufexan** [comment]
Versioning does work in meson as well since #321.

The problem here is that the flake has no way of determining that git info, since it strips out `.git`.

We should probably switch to using a `version` file which the flake and everything else can then check.

**Comment by luxus** [comment]
can the version file used to update the nix file?
https://github.com/hyprwm/Hyprland/blob/3947fe9e9f8fb2912b969a20fbbec3f2ab62cef0/flake.nix#L36

**Comment by viperML** [comment]
Speaking of that string, shouldn't it supposed to be automatically updated?

**Comment by fufexan** [comment]
It was, but the GH runner doesn't get the git info properly and instead replaces the version with `""`. So I disabled it and then forgot about it.

**Comment by fufexan** [comment]
I'll try to make a release action with the actor set as Vaxry, that'll solve our problems.

**Comment by vaxerski** [comment]
@fufexan any updates here or should I close this

**Comment by fufexan** [comment]
You can close it for now.
