### ISSUE TITLE
Monitor Description not working

### ISSUE THREAD

**Issue by georghimself** [hyprwm/Hyprland#4710]
Cheers,

Everytime i plugin my external monitors they have a different ID. 
So i tried using the monitor description like shown in an Isssue here. But its somehow not doing anything.

monitor=Iiyama North America PL2530H 1154310241653, 1920x1080, 0x0, 1
monitor=Iiyama North America PL2530H 1154310241654, 1920x1080, 1920x0, 1

Also switching them does not work. If i revert back to IDs an switch its switching monitors instantly.
Am i missing something here?
thanks in advance

**Comment by fufexan** [comment]
To use the monitor description you have to use the `desc:` keyword, as explained in [the wiki](https://wiki.hyprland.org/Configuring/Monitors/)

> then the description value up to the portname (eDP-1) can be used to specify the monitor:
`monitor=desc:Chimei Innolux Corporation 0x150C,preferred,auto,1.5`


```ini
monitor=desc:Iiyama North America PL2530H 1154310241653, 1920x1080, 0x0, 1
monitor=desc:Iiyama North America PL2530H 1154310241654, 1920x1080, 1920x0, 1
```

**Comment by georghimself** [comment]
Thank you!
