### ISSUE TITLE
Invalid Rule In Default Config

### ISSUE THREAD

**Issue by cprin21** [hyprwm/Hyprland#4713]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a42b984f51a00e88a13a45e1b5e9e3d4ec470254 dirty (screencopy: fix ~dtor being in monitorRenderResources map).
Date: Wed Feb 14 21:01:40 2024
Tag: v0.35.0-36-ga42b984f

flags: (if any)


System Information:
System name: Linux
Node name: navi
Release: 6.7.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

On the given commit (`a42b984f51a00e88a13a45e1b5e9e3d4ec470254`), nomaximizerequest is considered an invalid rulev2, something that came with the default hyprland.conf

### How to reproduce

Start Hyprland session, see config error at top of screen about nomaximizerequest.

### Crash reports, logs, images, videos

![1707985256_grim](https://github.com/hyprwm/Hyprland/assets/107228497/09525e29-bbae-47df-94ff-e1ecb2f6c4a9)

**Comment by cprin21** [comment]
Closing, I'm a moron, no*request rules were nuked a few commits ago.

**Comment by vaxerski** [comment]
I always announce breaking changes on the discord if you are on git :)

**Comment by xdevs23** [comment]
> Closing, I'm a moron, no*request rules were nuked a few commits ago.

Why though? Is it replaced by `nomaxsize` and `fakefullscreen`? I used this to prevent certain games from forcing fullscreen so I can switch workspaces and keep these games in their workspaces and make them tiled if necessary.

**Comment by vaxerski** [comment]
oops forgot to mention in release notes.

**Comment by vaxerski** [comment]
fixed: 
![image](https://github.com/hyprwm/Hyprland/assets/43317083/c1eda4d6-aa31-4646-b444-fe986fd2378c)

**Comment by xdevs23** [comment]
> fixed: ![image](https://private-user-images.githubusercontent.com/43317083/308687867-c1eda4d6-aa31-4646-b444-fe986fd2378c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDg2MjEsIm5iZiI6MTcwOTE0ODMyMSwicGF0aCI6Ii80MzMxNzA4My8zMDg2ODc4NjctYzFlZGE0ZDYtYWEzMS00NjQ2LWI0NDQtZmU5ODZmZDIzNzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE5MjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTVkMGY0ZmQ5NzEwNDZhYWY5ODM1YTBmNmU0ODczZDI2NjAzYzhlNDFhZTRkMDc1OTUzOWM2NzgyYWI5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tQxVcBzELGhpFJDcD5nqYH9PIOpxGigrYWFZJrGFZ8M)

Thank you!
