### ISSUE TITLE
Package manager can't connect to X, gets stuck

### ISSUE THREAD

**Issue by haasn** [hyprwm/Hyprland#4716]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: xor
Release: 6.6.11-1-default
Version: #1 SMP PREEMPT_DYNAMIC Thu Jan 11 08:01:39 UTC 2024 (05ae4ad)


GPU information: 
44:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX] [1002:744c] (rev cc) (prog-if 00 [VGA controller])


os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240213"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240213"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240213:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240213"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"


plugins:
```

Note: Not sure why the version is reported blank, but the installed package version is 0.35.0-37.3.

</details>

### Bug or Regression?

Bug

### Description

This is a complex multi-component issue that involves at least three separate projects. But a basic rundown of what happens is:

1. Some RPM post-install script attempts to run some tool as root (e.g. `xset fp rehash`, or `dbus-launch` which preferentially resolves to `dbus-launch.x11`)
2. This hits `xcb_connect` inside libxcb, which attempts to connect to X
3. This function hits an internal error "Authorization required, but no authorization protocol specified"
4. Due to a bug in libxcb, it does not handle this error condition correctly and instead attempts to `retry` the connection
5. Infinite loop occurs, resulting in 100% CPU usage in both libxcb and Xwayland.

I will cross-file this in libxcb (should not infinite loop) and openSuSE (should not connect to X as root), but given that it works under X I believe this could also be improved under Hyprland, specifically w.r.t the "authorization required" error condition.

It's worth pointing out that I *did* add `exec-once = /usr/libexec/polkit-kde-authentication-agent-1` to my `hyprland.conf`

### How to reproduce

`sudo xset fp rehash`

**Comment by haasn** [comment]
Update: Turns out *libxcb* is innocent here. OpenSuSE in their infinite wisdom decided to apply a local patch that adds this infinite loop: https://build.opensuse.org/package/view_file/openSUSE:Factory/libxcb/n_If-auth-with-credentials-for-hostname-fails-retry-with-XAUTHLOCALHOSTNAME.patch?expand=1

**Comment by vaxerski** [comment]
not a hyprland bug
