### ISSUE TITLE
Sometimes keyboard input stops to work

### ISSUE THREAD

**Issue by Serpentian** [hyprwm/Hyprland#4721]
### Hyprland Version

<details> <summary>System/Version info</summary>

```diff
diff --git a/flake.lock b/flake.lock
index a848fd2..6ef7e4a 100644
--- a/flake.lock
+++ b/flake.lock
@@ -49,10 +49,10 @@
       },
       "locked": {
         "lastModified": 1708018354,
-        "narHash": "sha256-MlbqBzAjiz4Va2M/AvLN96Wq+jsCbEedhfMs5wW1yFM=",
+        "narHash": "sha256-Vdf5QGzkZe6UUdVZ80YT78id7Yw5ww9Fku0rEyPAkCg=",
         "owner": "hyprwm",
         "repo": "Hyprland",
-        "rev": "fbf5ba87ce57752653f3bebf6e2be090c702836e",
+        "rev": "e4bb5fa4af1a6c36aab1c28651b5403dc4952f93",
         "type": "github"
       },
       "original": {
```

</details>

### Bug or Regression?

Regression

### Description

Version e4bb5fa4af1a6c36aab1c28651b5403dc4952f93 works all right. When I switch to fbf5ba87ce57752653f3bebf6e2be090c702836e, sometimes SOME keys of my keyboard, which corresponds to the keybindings in Hyprland, stops to work. E.g. I have Win + H/J/K/L binds, H,J,K,L become not recognised at all, I can't input them even into kitty. `hyprctl reload` doesn't help, only killing Hyprland and restarting it.

Though, after killing Hyprland, keyboard works great in TTY.

### How to reproduce

No idea

**Comment by Sxmourai** [comment]
You should provide some logs

**Comment by vaxerski** [comment]
`git bisect` the exact commit please

**Comment by vaxerski** [comment]
also try with 294e51a857d158ce0b03c5fd752bbd05e67f6bc9

**Comment by Serpentian** [comment]
https://github.com/hyprwm/Hyprland/commit/294e51a857d158ce0b03c5fd752bbd05e67f6bc9 fixes the issue. Closing the ticket, thank you

**Comment by incogcyberpunk** [comment]
I am still having this issue as of Nov 2025, randomly the keys that are used for the hyprland binds don't work , while other keys input just fine.
