### ISSUE TITLE
Freeze due to window rules on 0.35.0

### ISSUE THREAD

**Issue by Seercat3160** [hyprwm/Hyprland#4722]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: neodymium
Release: 6.7.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:37 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation AlderLake-S GT1 [8086:4680] (rev 0c) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080 Ti] [10de:2208] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When some window rules are present in the config on v0.35.0, clicking the "Library" button in Steam can freeze the compositor, making it display the same frame constantly until SIGKILLed, and not take any input. It's not even possible to switch TTY. The logs are filled with tens of thousands of repeats of the line `Searching for matching rules for steam (title: Steam)`.

The config in question:
```
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
```

Removing those lines from the config or downgrading to v0.34.0 fixes the issue. It happens even with logging disabled, so that's not the problem.

### How to reproduce

1. Use v0.35.0, with the Steam client beta (context menu compat is enabled there, in case it matters)
2. Add those lines to your config
3. Open the Steam client, and go to the Downloads menu
4. Hover over the "Library" tab in the top menu and click it

### Crash reports, logs, images, videos

Log from a time this happened, where I've passed it through `uniq -c` so it's not ridiculously huge (314 MB before) but you can still see the magnitude of the log spam: [hyprland.log](https://github.com/hyprwm/Hyprland/files/14307847/hyprland.log)

**Comment by VeilSilence** [comment]
It happens in steam beta only isn't?

**Comment by Seercat3160** [comment]
I am using the Steam client beta, yes. I probably should have specified that in the OP. I don't know about without, I haven't tested. Regardless, this is a Hyprland issue as the behaviour of clients shouldn't lead to crashes or freezes of the compositor in any scenario ideally.

**Comment by vaxerski** [comment]
likely `stayfocused` is violating x11's protocol rules and leading to trashing of the protocol with activate requests

**Comment by Seercat3160** [comment]
I can't repro on https://github.com/hyprwm/Hyprland/commit/cdcc5aba06f20005842cf966b23af50456dc7142 so I think that's done the trick! Thanks for looking into it.

**Comment by barbiefan** [comment]
This started happening today on flatpak steam (no beta) and regular steam (on arch), took a while to figure out the culprit until i stumbled into this issue. But yeah, removing those window rules stopped the freezing.
I guess beta changes went into mainline steam :/

**Comment by Seercat3160** [comment]
Works fine on 0.36.0 for me
