### ISSUE TITLE
No resolution options above 1080p in applications

### ISSUE THREAD

**Issue by npc-glitch** [hyprwm/Hyprland#4729]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:37 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])
04:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 SUPER] [10de:1f06] (rev a1) (prog-if 00 [VGA controller])
```

</details>

### Bug or Regression?

Bug

### Description

Applications does not have options for resolutions above 1080p unless I disable my 1080p monitors, my main monitor is 1440p.

Here's my monitor config
```
monitor=DP-3, highrr, 1920x200, 1
monitor=DP-2, highrr, 0x230, 1
monitor=HDMI-A-1, highres, 4480x0, 1, transform,3
```

If I replace my 1080p monitors with this to turn them off
```
monitor=DP-2, disable
monitor=HDMI-A-1, disable
```

And if once they're disabled I revert back to the first config again, everything works as intended (I'm able to select 1440p in game settings), however you have to repeat this process every time you start Hyprland.

### How to reproduce

1. Have monitors with different resolutions.

2. Set them up in the config.

3. Try to change resolution of a Game or Fullscreen app to the resolution of the higher rez monitor.

**Comment by vaxerski** [comment]
that's a problem with xwayland. Set the xwayland primary as your highest-res monitor via xrandr
