### ISSUE TITLE
`movewindow` dispatcher to have option for next/previous window

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#473]
It makes sense to navigate the master/stack layout with the `cyclenext` dispatcher for next/previous windows. It also makes sense to want to move windows in the same way - currently `movewindow` only accepts u/d/l/r

**Comment by vaxerski** [comment]
cyclenext or the dedicated master layoutMessage?

**Comment by patrickaldis** [comment]
Ah I've been using the standard `cyclenext` dispatcher - I'll change this, I wasn't reading the config and didn't see `layoutMessage`. It would make sense to add a `movetonext`/`movetoprev` for `layoutMessage` though

**Comment by patrickaldis** [comment]
I think `movewindow` u/d almost works, but doesn't respect the next/previous

**Comment by port19x** [comment]
I kinda need this to comfortably use hyprland.
`movenext` is ideal because of consistency with `cyclenext`.
Previous isn't really necessary as it's own dispatcher since it doesn't exist in `cyclenext` either.
5€ bounty (I'll send via ko-fi)

**Comment by vaxerski** [comment]
> 5€ bounty (I'll send via ko-fi)

I'd prefer hentai

**Comment by vaxerski** [comment]
done.

see `swapnext` in advanced configuring for dwindle / global and `swapnext` and `swapprev` layoutmsgs in the Master Layout page for the master layout-respecting equivalents. (wait like 30s for the wiki to update)
