### ISSUE TITLE
Video of cat dancing makes Hyprland go crazy

### ISSUE THREAD

**Issue by sin-ack** [hyprwm/Hyprland#4732]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

When I play this video on mpv using Hyprland, it starts going nuts, but *only if* it's not the only tiled window on the screen. The following display the issue:

1. Opening the video on `mpv` using a terminal (which opens the video to the side)
2. Opening the video on an empty workspace and then making the video floating

### How to reproduce

1. Download video
2. Get mpv if you don't have it
3. Play video with `mpv video.webm` in one of the above two situations

The video in question: [1707543465070317.webm](https://github.com/hyprwm/Hyprland/assets/77421532/58f5177b-0aeb-48ff-aeae-3a984d9e8d15)

<video src="https://github.com/hyprwm/Hyprland/assets/77421532/58f5177b-0aeb-48ff-aeae-3a984d9e8d15"></video>

### Crash reports, logs, images, videos

Demonstration video (seizure warning):

https://github.com/hyprwm/Hyprland/assets/77421532/a0daec6f-ab98-455b-9a95-83b21899739a

**Comment by DRAGONTOS** [comment]
it does work in a special workspace

**Comment by vaxerski** [comment]
what do you expect? You're opening a specifically crafted malicious file.

**Comment by RossComputerGuy** [comment]
Maybe this should be reopened or a new issue opened which suggests adding a way to make a window have a fixed size. I run into a similar issue with Firefox's PiP.
