### ISSUE TITLE
Missing author credits for wallpapers and notification of new added wallpaper

### ISSUE THREAD

**Issue by LinuxCodingGod** [hyprwm/Hyprland#4733]
### Description

Many wallpapers are included in the Hyprland assets, but there seems to be no mention of credits or authors for these works. Acknowledging the artists work is crucial, especially to respect and appreciate the time and creativity invested in the creations.
This oversight not only disrespects the creative efforts of these individuals but also undermines the ethical standards expected within the open-source community. I'm particularly interested in knowing who created these wallpapers for potential future collaborations or commissions.

New wallpapers are added to the project without any announcement or notification to the users, this approach can lead to unexpected surprises for users in the professional context or environment, such as the appearance of random or potentially borderline content.

Here is the todo list:

- [ ] Add artist credits
- [ ] Content guidelines - guidelines for what constitutes acceptable content for wallpapers included and standards for appropriateness
- [ ] User notifications and consent - before introducing new wallpapers, it should be better implementing a notification system or an option to review and accept these changes could enhance the user experience

**Comment by vaxerski** [comment]
Who are you? Ethics police?

https://hyprland.org/news/contestWinners/

Authors are mentioned there.

> This oversight not only disrespects the creative efforts of these individuals but also undermines the ethical standards expected within the open-source community. I'm particularly interested in knowing who created these wallpapers for potential future collaborations or commissions.

No, fuck off. Rules of the competition were laid out and followed.

> New wallpapers are added to the project without any announcement or notification to the users, this approach can lead to unexpected surprises for users in the professional context or environment, such as the appearance of random or potentially borderline content.

I don't care about your surprises, I am not obliged in any way, shape, or form to inform you about anything.

**Comment by upsidedownsweetfood** [comment]
> Who are you? Ethics police?
> 
> https://hyprland.org/news/contestWinners/
> 
> Authors are mentioned there.
> 
> > This oversight not only disrespects the creative efforts of these individuals but also undermines the ethical standards expected within the open-source community. I'm particularly interested in knowing who created these wallpapers for potential future collaborations or commissions.
> 
> No, fuck off. Rules of the competition were laid out and followed.
> 
> > New wallpapers are added to the project without any announcement or notification to the users, this approach can lead to unexpected surprises for users in the professional context or environment, such as the appearance of random or potentially borderline content.
> 
> I don't care about your surprises, I am not obliged in any way, shape, or form to inform you about anything.

Damn bro :skull: chill

**Comment by LinuxCodingGod** [comment]
> No, fuck off. 

> I don't care about your surprises, I am not obliged in any way, shape, or form to inform you about anything.

Rude bruh

**Comment by vaxerski** [comment]
said the one attacking in the original post after creating an account today probably to avoid backlash.
