### ISSUE TITLE
Screenshotting fails after updating to 0.35.0.r42.289d952a-1

### ISSUE THREAD

**Issue by krims0n32** [hyprwm/Hyprland#4735]
### Hyprland Version

```
Hyprland, built from branch main at commit 289d952a6ee02f6d54a0899870bbec52ff9a53df dirty (dispatchers: add Fullscreen without sending fullscreen to application (4720)).
Date: Sat Feb 17 17:21:06 2024
Tag: v0.35.0-42-g289d952a

flags: (if any)


System Information:
System name: Linux
Node name: nyx
Release: 6.7.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti Rev. A] [10de:1e07] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

### Bug or Regression?

Bug

### Description

None of the screenshot tools work anymore.

grim says: 
```
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
```

Other tools like hyprshot write empty screenshot files.

### How to reproduce

Run Hyprland v0.35.0-42-g289d952a and execute grim. I've downgraded Nvidia but that doesn't help.

**Comment by kulothunganug** [comment]
I am using `v0.35.0-53-g17635663`
```
~ 
❯ hyprctl version
Hyprland, built from branch main at commit 176356630853a6558b8125726bbdaf6411593488 dirty (surface: minor fixes for last logicalDamage calc fix).
Date: Mon Feb 19 17:04:55 2024
Tag: v0.35.0-53-g17635663
```
and `grimblast-git` which is based on `grim`
works fine for me.

**Comment by thejch** [comment]
nvidia issue, linking my comment in another thread for info
https://github.com/hyprwm/Hyprland/issues/4791#issuecomment-1962008299

**Comment by CRAG666** [comment]
@thejch 
It is not an Nvidia problem, since with version 0.35 it works fine. I also tried another computer without Nvidia, just with Intel and I have the same problem.

**Comment by romanstingler** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/5576250/7d716f95-854d-4a16-a8ae-7ef0e32822dc)
![image](https://github.com/hyprwm/Hyprland/assets/5576250/92e4a246-dce9-49d0-bf4f-8f460a305cb8)
this works

**Comment by CRAG666** [comment]
Not working for me...

**Comment by taylorcoffelt** [comment]
> Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
> Nvidia Driver Version 550.67

I had the same issue, was working on prior versions of Hypr:

```$ grim
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
```

Disabling 10-bit color in Hyprland config allows grim / grimblast to work for me.

**Comment by krims0n32** [comment]
Latest hyprland git fixed this issue for me without changing anything else.

**Comment by julius-boettger** [comment]
> Latest hyprland git fixed this issue for me without changing anything else.

For me too, at least concerning screenshots.

Screenshare also seems to be broken for me, last Hyprland version I can get it to work with is 0.34.0. Also tested on latest git today, doesn't work. Is anyone else experiencing this? Should this be its own issue? I'm also on NVIDIA.

**Comment by iddm** [comment]
> > Latest hyprland git fixed this issue for me without changing anything else.
> 
> For me too, at least concerning screenshots.
> 
> Screenshare also seems to be broken for me, last Hyprland version I can get it to work with is 0.34.0. Also tested on latest git today, doesn't work. Is anyone else experiencing this? Should this be its own issue? I'm also on NVIDIA.

I hate the "same thing comments" myself, but just to confirm that this happens - I also have been experiencing the problem where I cannot share my screen for quite a while now; however, it had to be working for a long time, too. I rebuilt everything from scratch, from the latest branches, including the desktop-portal, but it is still broken for me. Also using NVIDIA, but I don't think it matters actually in this particular case.

**Comment by julius-boettger** [comment]
Then let's move to #5306 for this.
