### ISSUE TITLE
Long starting time and hangs in Hyprland when DRM_FBDEV_EMULATION=y is set on amdgpu

### ISSUE THREAD

**Issue by Nanderty** [hyprwm/Hyprland#4737]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

On an AMD Radeon RX 7900 XTX using the amgpu driver,  when DRM_FBDEV_EMULATION=y is set in the Kernel, Hyprland starts very slowly, causes the sysfs interface for the gpu not to work anymore and is not able to display gpu intensive things(if I try, it hangs).
I am submitting a bug here, since gamescope doesn't cause this.
Setting DRM_FBDEV_EMULATION=n, Hyprland works perfectly, but then one doesnt have a tty.

### How to reproduce

Set DRM_FBDEV_EMULATION=y on a system using amdgpu video driver and start Hyprland.

### Crash reports, logs, images, videos

I am supplying my dmesg, since the Hyprland log is not different between working and problematic runs.
[dmesg.log](https://github.com/hyprwm/Hyprland/files/14320547/dmesg.log)

Edit: corrected FRAMEBUFFER_CONSOLE_DETECT_PRIMARY to DRM_FBDEV_EMULATION

**Comment by vaxerski** [comment]
well your ver is quite old, but tf is `FRAMEBUFFER_CONSOLE_DETECT_PRIMARY`?

**Comment by zakk4223** [comment]
```
[zakk@blkheart:~][1]$ zcat /proc/config.gz | grep -i FRAMEBUFFER_CONSOLE_DETECT                            
CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY=y
```

I'm on a 6900XT and have never had any such issues as you describe. So it's either some RDNA3 specific bug, or some wlroots thing?
I would try other wlroots compositors to see if they also do this.

**Comment by Nanderty** [comment]
Thank you for your quick replies.
Sorry, made a mistake here, the issue is DRM_FBDEV_EMULATION=y .
Both this and FRAMEBUFFER_CONSOLE_DETECT_PRIMARY are kernel options. DRM_FBDEV_EMULATION=y allows the amdgpu driver to provide a framebuffer which you need to have a visible tty, without it one will have a blackscreen in tty.
The issue doesn't happen with gamescope, which is, as far as I know, also wlroots based.

**Comment by Nanderty** [comment]
I can confirm it still happens on the newest version:

```sh
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0

flags: (if any)
```

**Comment by Nanderty** [comment]
I found the culprit:
This problem only occurs if one doesn't use logind/elogind.
This is especially interesting since the issue doesn't occur on NVIDIA without logind/elogind, but does on AMD.
Is this desired behaviour and thus should I close this?

**Comment by Nanderty** [comment]
Strangely enought I do not have this issue anymore when using seatd only - without any elogind.
Either did I do a config/permission mistake or a Hyprland/Kernel update fixed this.

**Comment by Nanderty** [comment]
Strangely enought I do not have this issue anymore when using seatd only - without any elogind.
Either did I do a config/permission mistake or a Hyprland/Kernel update fixed this.
