### ISSUE TITLE
wine under vulkan not working issue

### ISSUE THREAD

**Issue by byomi** [hyprwm/Hyprland#4742]
### Hyprland Version

<details> <summary>System/Version info</summary>

hyprctl systeminfo output:

Hyprland, built from branch main at commit 7e8bcd675de15ee2498f1aa15c5b335e9a9a55f0 dirty (monitors: fix outputmgr nullptr crash (4738)).
Date: Sun Feb 18 03:24:01 2024
Tag: v0.35.0-45-g7e8bcd67

flags: (if any)

System Information:
System name: Linux
Node name: unkown-hp
Release: 6.7.5-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:21 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Haswell-ULT Integrated Graphics Controller [8086:0a16] (rev 09) (prog-if 00 [VGA controller])

os-release: NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=garudalinux

plugins:

### Bug or Regression?

Bug

### Description

so basicaly idk if its a bug or what,so i am using garuda linux hyprland which comes pre configured and i followed the https://wiki.hyprland.org/Nvidia/ site in order to make the nvidia work and its working fine i have nvidia gt 740m and using the nvidia-470xx-utils  as the main arch site suggested for my card so what i faced while working with lutris anything i launch using it gives error 
```
libEGL warning: egl: failed to create dri2 screen
MESA-INTEL: warning: Haswell Vulkan support is incomplete
ERROR:             ICD associated with VkPhysicalDevice does not support GetPhysicalDeviceCalibrateableTimeDomainsKHR
```

first this ``MESA-INTEL: warning: Haswell Vulkan support is incomplete`` didnt show untill after couple search and checking what the issue where i didnt find anywhere i though i just need to install vulkan as i found out its the issue 

so what i concluded is that the ``nvidia-470xx-utils`` doesn't work with hyprland under vulkan since when i use the defaul nouevu driver the everything in lutris work well  but i prefer ``nvidia-470xx-utils`` because it has better performance and battery life 

lastly thanks for this awesome desktop its pretty cool and easy to configure and pretty lightwieght with cool animations i am using it for 2 days now and its awesome thanks for the team

### How to reproduce

grab nvidia gt 740m card  and try it lmao

**Comment by vaxerski** [comment]
nvidia is not supported
