### ISSUE TITLE
BUILD ERROR - MAIN BRANCH INCL. LATEST COMMIT (#301b48b)

### ISSUE THREAD

**Issue by frkli1965** [hyprwm/Hyprland#4743]
### Hyprland Version

<details> <summary>System/Version info</summary>
Up to commit #301b48b
```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Hi,

Encountering build errors on the main branch as follows:-

/usr/bin/ld: /tmp/ccTW4JTD.ltrans7.ltrans.o: in function `CConfigManager::CConfigManager()':
<artificial>:(.text+0x63cd): undefined reference to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)'
/usr/bin/ld: <artificial>:(.text+0x63fd): undefined reference to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)'
/usr/bin/ld: <artificial>:(.text+0x642d): undefined reference to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)'
/usr/bin/ld: <artificial>:(.text+0x645d): undefined reference to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)'
/usr/bin/ld: <artificial>:(.text+0x648d): undefined reference to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)'
/usr/bin/ld: /tmp/ccTW4JTD.ltrans7.ltrans.o:<artificial>:(.text+0x64bd): more undefined references to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)' follow
/usr/bin/ld: /tmp/ccTW4JTD.ltrans9.ltrans.o: in function `CConfigManager::deviceConfigExists(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x1251): undefined reference to `Hyprlang::CConfig::specialCategoryExistsForKey(char const*, char const*)'
/usr/bin/ld: /tmp/ccTW4JTD.ltrans9.ltrans.o: in function `CConfigManager::addPluginConfigVar(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Hyprlang::CConfigValue const&)':
<artificial>:(.text+0x2287): undefined reference to `Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)'
/usr/bin/ld: /tmp/ccTW4JTD.ltrans9.ltrans.o: in function `CConfigManager::removePluginConfig(void*)':
<artificial>:(.text+0x2d9b): undefined reference to `Hyprlang::CConfig::unregisterHandler(char const*)'
/usr/bin/ld: <artificial>:(.text+0x2f7e): undefined reference to `Hyprlang::CConfig::removeSpecialConfigValue(char const*, char const*)'
/usr/bin/ld: /tmp/ccTW4JTD.ltrans10.ltrans.o: in function `CConfigManager::handleSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x4fca): undefined reference to `Hyprlang::CConfig::parseFile(char const*)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:15: release] Error 1

Same for both hyprlang v0.3.2 and v0.4.0

### How to reproduce

Checkout main branch and build with 'make all'

**Comment by fufexan** [comment]
Looks like hyprlang wasn't properly installed. What does `pkg-config --list-all | grep hyprlang` say?

**Comment by frkli1965** [comment]
> Looks like hyprlang wasn't properly installed. What does `pkg-config --list-all | grep hyprlang` say?

'hyprlang                       hyprlang - The official implementation library for the hypr config language.'

No version number for some reason, will try reinstalling...

**Comment by frkli1965** [comment]
Recompiled and re-installed hyprlang in the prescribed manner:-

git clone https://github.com/hyprwm/hyprlang.git
cd hyprlang
git checkout v0.4.0
mkdir build
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target hyprlang -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`
sudo cmake --install ./build

Tried installing in '/usr' and '/usr/local' (on separate occasions) yet no joy regrettably.

Also, used 'mold' to double-check errors and got the following:-

mold: error: undefined symbol: Hyprlang::CConfig::specialCategoryExistsForKey(char const*, char const*)
>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans9.ltrans.o:(CConfigManager::deviceConfigExists(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))
mold: error: undefined symbol: Hyprlang::CConfig::parseFilePKc
>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans10.ltrans.o:(CConfigManager::handleSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))
mold: error: undefined symbol: Hyprlang::CConfig::addSpecialConfigValue(char const*, char const*, Hyprlang::CConfigValue const&)
>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans9.ltrans.o:(CConfigManager::addPluginConfigVar(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Hyprlang::CConfigValue const&))>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans7.ltrans.o:(CConfigManager::CConfigManager())>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans7.ltrans.o:(CConfigManager::CConfigManager())>>> referenced 28 more times

mold: error: undefined symbol: Hyprlang::CConfig::unregisterHandlerPKc
>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans9.ltrans.o:(CConfigManager::removePluginConfigPv)
mold: error: undefined symbol: Hyprlang::CConfig::removeSpecialConfigValue(char const*, char const*)
>>> referenced by <artificial>
>>>               /tmp/cck1wJgF.ltrans9.ltrans.o:(CConfigManager::removePluginConfigPv)
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:15: release] Error 1
make[1]: Leaving directory '/... ... .../hyprland'
make: *** [Makefile:31: all] Error 2

So not really sure what's going on tbh.

This is on Arch btw (hate having to say that) with latest updates e.g. glibc v2.39, gcc v13.2.1, etc.

**Comment by tharrmeehan** [comment]
Hmm I tried it with hyprlang-git and it worked, maybe try that?

**Comment by frkli1965** [comment]
> Hmm I tried it with hyprlang-git and it worked, maybe try that?

Removed 'git checkout v0.4.0' and it worked!

Um, that's a bit obscure but well done for sussing it out nevertheless. :-)

Now I have a load of hyprland.conf  errors to attend to...

Let me know if you want me to close this but might be worth keeping it open for a while so that others can take heed.

**Comment by vaxerski** [comment]
please don't report build errors, those are **always** your fault:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/1e95bfe1-f166-4545-8393-e0c9edca3a11)
