### ISSUE TITLE
Cannot change keyboard layout

### ISSUE THREAD

**Issue by duncanf95** [hyprwm/Hyprland#475]
I am trying to change from US ansi keyboard layout to UK iso keyboard layout but it doesn't seem to switch at all. I have double checked this in my gnome instance and just tty with no DE, keyboard is set correctly in system but not for hyprland. 

**Steps to reproduce:**
load up a fresh copy of hyprland, copy example config to local config folder and set `kb_layout` to `uk`

```
input {
    kb_layout=uk
    follow_mouse=1

    touchpad {
        natural_scroll=false
        tap-to-click=false
        middle_button_emulation=false
    }
}
```

**Expected Outcome:**

the keyboard layout should change to uk iso, the `\` key on a us keyboard should output a `#` if layout changed correctly

**Actual Outcome:**

keyboard remains as us layout, does not register change

**Comment by patrickaldis** [comment]
I struggled with this - problem is you need the right string for uk layout. It's `gb` rather than `uk`

**Comment by vaxerski** [comment]
thats why reading the xkb docs is useful.
