### ISSUE TITLE
Unable to get 5px gap for `gaps_in`

### ISSUE THREAD

**Issue by Kagukara** [hyprwm/Hyprland#4752]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 301b48b74087cc59753ffa144b215540e6f82831 dirty (renderer: fix invalid damage accumulation with invalid buffer_age).
Date: Sun Feb 18 16:04:08 2024
Tag: v0.35.0-49-g301b48b7

flags: (if any)


System Information:
System name: Linux
Node name: destrarch
Release: 6.7.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When using `gaps_in` it doesn't set the gap to the number you put. On the wiki it states "gaps between windows", but its more like the gaps of one window being combined with another, so the number is being doubled from what you put for `gaps_in`. For example I want to have `gaps_in` to have a 5px gap, you'd think I'd just have to put `gaps_in = 5` but that will result in a 10px gap. You can't have an inwards gap of 5px, you can only have either 4px or 6px by putting either `gaps_in = 2` or `gaps_in = 3`.

If there is a reason behind this an explanation would be appreciated as its not documented on the wiki, at least from my searching.

### How to reproduce

1. Change the `gaps_in`  number in your hyprland.conf to whatever number
2. Capture/Screenshot the "gaps between windows"
3. Open the image in something like GIMP and check how many pixels there are.

### Crash reports, logs, images, videos

Capture of `gaps_in = 2` with coloured boxes indicating it being 4px not 2px:
![capture_2024-02-19_01-15-59](https://github.com/hyprwm/Hyprland/assets/43391109/30a786cd-f4f7-4523-bf7f-995b07c06de1)
_open in GIMP to view the image larger & clearer_

**Comment by vaxerski** [comment]
that's just how it works. Why are you so anal about the 5px?

**Comment by Kagukara** [comment]
Sorry if providing information and asking for classification on a subject one time is being "anal"about something. I just wanted to know if 5px gap between windows was a bug or intended.

I guess your answer to what I said previously:
> If there is a reason behind this an explanation would be appreciated as its not documented on the wiki, at least from my searching.

Is this then:
> that's just how it works.

Very informative, thank you.
