### ISSUE TITLE
 hyprlang and dependency 'libhyprlang.so=0-64' required by xdg-desktop-portal-hyprland are in conflict

### ISSUE THREAD

**Issue by AnkurAlpha** [hyprwm/Hyprland#4757]
About hyprlang

~~~
installing hyprlang (0.4.0-1) breaks dependency 'libhyprlang.so=0-64' required by xdg-desktop-portal-hyprland
~~~

_Originally posted by @sgse in https://github.com/hyprwm/Hyprland/issues/4754#issuecomment-1952354126_

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprlang/issues/22

does this look like an arch linux bug tracker?
