### ISSUE TITLE
Disable cursor follows focus

### ISSUE THREAD

**Issue by jpc0** [hyprwm/Hyprland#4758]
### Description

Not sure if I am doing something weird here, my current setup is as follows. I have two monitors, I generally want a workspace per monitor (in reality I would want a workspace to span both but a workspace per monitor is fine) and to cycle between them per monitor, to do this I have in my config:
```
bind = SUPER SHIFT, right, movetoworkspace, r+1
bind = SUPER SHIFT, left, movetoworkspace, r-1

bind = SUPER CTRL, right, workspace, r+1
bind = SUPER CTRL, left, workspace, r-1

bind = SUPER, right, focusmonitor, +1
bind = SUPER, left, focusmonitor, -1
```

A small gripe I have is the with the `SUPER, ****, focusmonitor` combination the cursor moves with the focus.

Is there any way to have the cursor not follow focus when changing monitors?

**Comment by vaxerski** [comment]
idk maybe the wiki mentions something like this

![image](https://github.com/hyprwm/Hyprland/assets/43317083/0aeec2d9-1cee-46c3-b560-18af4e392832)

https://wiki.hyprland.org/Configuring/Variables/#general

**Comment by jpc0** [comment]
> idk maybe the wiki mentions something like this
> 
> ![image](https://private-user-images.githubusercontent.com/43317083/306034060-0aeec2d9-1cee-46c3-b560-18af4e392832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjM0NDYsIm5iZiI6MTcwODM2MzE0NiwicGF0aCI6Ii80MzMxNzA4My8zMDYwMzQwNjAtMGFlZWMyZDktMWNlZS00NmMzLWI1NjAtMThhZjRlMzkyODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE3MTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NzdiZTdlMDM2MWMyMjcyN2ZmYTAyODgxNTUyMGM3MWFhOTIyNTM1OGNiNmMwMjIxOTY1MjIwYzcwZWRiM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-LCOLf9U_zidO3neHr1Y_q9F7XmJVtLRcEsC3ylnj4)
> 
> https://wiki.hyprland.org/Configuring/Variables/#general

Many thanks

I swear I did CTRL-F for cursor and just never saw that one... Apparently I am just blind.
