### ISSUE TITLE
Ability to contain user interaction with window size

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#4760]
### Description

Some windows just don't look right when they are tiled, very large or very small, so it would be nice to have a way of doing this:
- Set the maximum possible size for floating window. At the moment (as far as I can see in docs) there is only a static `maxsize` rule which only affects window creation, user is still able to resize the window more than this. I tried to find the upper limit, but Hyprland just crashed at 40000x40000.
- Set minimum possible size for floating window, same as before, but right now minimum size is at least exist - it is 20x20 window, just point on screen.  Can it be customized globally and per window?
![2024-02-19T23:03:26,857272455+04:00](https://github.com/hyprwm/Hyprland/assets/142721811/afbad4dd-175d-46bd-b6dd-5e5d1900c517)

- Same issue for tiling windows with use case examples https://github.com/hyprwm/Hyprland/issues/4414

- Add window rule that allows always floating window (set float and ignore togglefloating dispatcher, even if user accidentally press it). I guess it can be done with bash script, but window rule is more convenient.

### Some use case for max/min possible size:
![usecase](https://github.com/hyprwm/Hyprland/assets/142721811/88adc292-8fbb-4bda-a9fe-90d539081b33)

**Comment by Ligthiago** [comment]
Btw, after some recent changes, minimal size seems to work fine in most GTK applications, at least they can't become barely existing unusable dot, smaller that it's content. Very good.
So examples is no longer reproducible, but issue is still valid for other apps and maxsize.

https://github.com/hyprwm/Hyprland/assets/142721811/f0137bb0-c7c2-45da-8d5d-819d0c074e47

**Comment by vaxerski** [comment]
The app itself should set its maxsize properly.
