### ISSUE TITLE
Random crashing on AMD GPU

### ISSUE THREAD

**Issue by Maybegus** [hyprwm/Hyprland#4762]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.35.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: desktop
Release: 6.1.77
Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Feb  5 20:13:03 UTC 2024


GPU information: 
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240216.5863c27"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland randomly crashes after working for ~30min, freezes for a couple of seconds and then puts me back to TTY.

This doesn't happen on my laptop, with the same nixos configuration and Intel GPU.

### How to reproduce

Launch Hyprland
Wait

### Crash reports, logs, images, videos

[hyprlandCrashReport1638.txt](https://github.com/hyprwm/Hyprland/files/14336810/hyprlandCrashReport1638.txt)

**Comment by vaxerski** [comment]
gpu driver died

**Comment by Maybegus** [comment]
Is there anywhere I should direct this?

**Comment by vaxerski** [comment]
amdgpu probably
