### ISSUE TITLE
Various hyprland crashes triggered by xdg-desktop-portal features

### ISSUE THREAD

**Issue by georgesboris** [hyprwm/Hyprland#4763]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.35.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.7.4-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240218.e015f24"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The problem causes two different scenarios randomly:
- Window freezing (e.g. can't close firefox window anymore unless I kill the process)
- Session "crashing" making hyprland automatically restart, though waybar is not visible anymore.

The randomness makes me thing there is some sort of state/service access that is not deterministic.
It seems the problem is always triggered through different accesses of xdg-desktop-portal features.

I'm opening the issue here because the stacktrace is always consistent, even though the triggers are different.

### How to reproduce

- Install Hyprland through NixOS - reproduced the problem through nixpkgs 23.11 until the current unstable release.
- Try to share your screen on Firefox or Chrome.
- Problem also happened after some time when I'm using OBS Studio (though the screenshare works initially the crash happens after some time (from a few to several minutes, less than an hour).

### Crash reports, logs, images, videos

[hyprlandCrashReport2233.txt](https://github.com/hyprwm/Hyprland/files/14336978/hyprlandCrashReport2233.txt)
[hyprlandCrashReport2288.txt](https://github.com/hyprwm/Hyprland/files/14336979/hyprlandCrashReport2288.txt)
[hyprlandCrashReport2887.txt](https://github.com/hyprwm/Hyprland/files/14336980/hyprlandCrashReport2887.txt)
https://gist.github.com/georgesboris/83023d2a1c3856b731ef20fad8f8e777

**Comment by vaxerski** [comment]
ye not much I can do here without a proper ASan log. You can _try_, but it's painful and I myself haven't been able to repro this, but I believe it's the same as brodie's crashes.

ASan debugging: ref: https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

Before that, though. I see you're on 0.35.0. Please test on -git (both xdph and hyprland), there have been some improvements.

Also, I believe the ff thing isn't actually hyprland, it's a thing where firefox's wayland fd overflows I believe?

**Comment by georgesboris** [comment]
I've tried building xdph and hyperland from flakes (closest thing to -git) but the problem continued.
I've not yet tested debugging with ASan.

However, I just got an error that might throw some light (maybe?), it was caused by chrome this time not ff, the stacktrace is the same as shown before ([gist](https://gist.github.com/georgesboris/83023d2a1c3856b731ef20fad8f8e777)) but I noticed this warning always appears just before the error:

```sh
Feb 21 09:19:48 nixos /nix/store/avj536sgrzcpdaih782w0gh7wf53rysr-gdm-45.0.1/libexec/gdm-wayland-session[47472]: 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Feb 21 09:19:51 nixos systemd[1]:
systemd-hostnamed.service: Deactivated successfully.
Feb 21 09:19:56 nixos /nix/store/avj536sgrzcpdaih782w0gh7wf53rysr-gdm-45.0.1/libexec/gdm-wayland-session[47472]: 
WARNING: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#56 is a dynamic-sized tensor).
Feb 21 09:19:56 nixos /nix/store/avj536sgrzcpdaih782w0gh7wf53rysr-gdm-45.0.1/libexec/gdm-wayland-session[70710]: 
The compositor does not seem to implement seat, which is required for wl-clipboard to work
Feb 21 09:20:06 nixos systemd[1]:
systemd-timedated.service: Deactivated successfully.
Feb 21 09:20:07 nixos /nix/store/avj536sgrzcpdaih782w0gh7wf53rysr-gdm-45.0.1/libexec/gdm-wayland-session[70761]: 
lspci: Unknown option 'vnn' (see "lspci --help")
```

The hope is based on it mentioned the compositor directly.
I'm adding a bit more context on the gist as an additional file.

**Comment by vaxerski** [comment]
> I've not yet tested debugging with ASan.

please try.

**Comment by izmyname** [comment]
Bump. How's it going?

**Comment by georgesboris** [comment]
Update here! Seems like a somewhat recent update fixed these problems - however I've not been able to figure out the root cause.

I'm closing the issue. Thanks!
