### ISSUE TITLE
Hyprland crashes when turning on one monitor (two monitor setup) 

### ISSUE THREAD

**Issue by goggi** [hyprwm/Hyprland#4770]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 86be75dd97b5633b8c0aa6bdcb3346fa871a8480  ().
Date: 2024-02-20
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: gza
Release: 6.1.78
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:06:32 UTC 2024


GPU information: 
24:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])
2f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240218.b98a4e1"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

I have a two monitor setup
monitor=DP-2,preferred,0x0,1
monitor=DP-2,addreserved,0,0,700,700
monitor=DP-3,preferred,1800x-1080,1

If I turn off DP-2 and turn it back on hyprland will always crash. 
It wont happen if I turn DP-3 on and off tho. 

### How to reproduce

Have two monitors turned on, turn one of the monitors off and turn it back on. 

### Crash reports, logs, images, videos

[hyprlandCrashReport5179.txt](https://github.com/hyprwm/Hyprland/files/14343882/hyprlandCrashReport5179.txt)

**Comment by goggi** [comment]
Issue does not exist on Hyprland, built from branch  at commit v0.35.0

```sh
Hyprland, built from branch  at commit v0.35.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: gza
Release: 6.1.78
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:06:32 UTC 2024


GPU information: 
24:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])
2f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240218.b98a4e1"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

**Comment by khaneliman** [comment]
Experiencing this as well. I have multi monitor that i toggle one between 2 different computers and will experience a crash when my other computer sleeps my one monitor and i wake it back up. 
[hyprlandCrashReport4513.txt](https://github.com/hyprwm/Hyprland/files/14345973/hyprlandCrashReport4513.txt)

**Comment by abihf** [comment]
Hi, I have same problem. I patched my Hyprland and never crash again.

I created PR here https://github.com/hyprwm/Hyprland/pull/4782

**Comment by abihf** [comment]
do you also use pyprland or other plugins? I just realized I still use pyprland 1.7 and vaxerski's make it  throws some warning.

**Comment by khaneliman** [comment]
my crash went away, as well, on latest builds

**Comment by goggi** [comment]
Unfortunately, like I mentioned earlier. With the latest commit the system freezes when turning the monitor back on. 
I'm not able to get a coredump and this is how the log file looks
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14389096/hyprland.log)

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit f389f77015ebeee30a2527b8eb7488879dd626e0  ().
Date: 2024-02-23
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: gza
Release: 6.1.78
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:06:32 UTC 2024


GPU information: 
24:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])
2f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240221.0e74ca9"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

0.35 is working good for me, so its not critical. What else would be useful for identifying the issue?

**Comment by goggi** [comment]
What I can add is that if I build https://github.com/hyprwm/Hyprland/commit/94aeb06d6ba14d403c46b52d1d2e397acb5906a4 (which is the commit before https://github.com/hyprwm/Hyprland/commit/c4283abb9f5797e1ec054d1161a9632bf005b98e) I still get a regular crash and a coredump + hyprlandCrashReport like earlier. But when I build with any commit after the system freezes fully.

**Comment by vaxerski** [comment]
try launching latest with `HYPRLAND_NO_CRASHREPORTER=1` and see if that doesn't fix the freezes.

**Comment by goggi** [comment]
> try launching latest with `HYPRLAND_NO_CRASHREPORTER=1` and see if that doesn't fix the freezes.

I tried, it didn't help

**Comment by goggi** [comment]
But your fix seems have solved the problem for most people. Seems like I have a different issue now. Do you want me to close this issue and open a new one for my specific problem?

**Comment by goggi** [comment]
@vaxerski, So I updated to latest commit. I still have the same issue with freezing if I turn of one monitor or disconnect it. But if I disconnect both the  monitors and reconnect them it goes from a freeze to a crash.  I have attached the crash report (slimmed). 
In the original version the "[backend/drm/atomic.c:250] Failed to acquire FB for plane 98" line keeps going forever, the report is 23mb big. But its the last line. 
 
Any guess what the issue could be? 

[hyprlandCrashReport5299.slim.txt](https://github.com/hyprwm/Hyprland/files/14433363/hyprlandCrashReport5299.slim.txt)

**Comment by vaxerski** [comment]
your display driver?

```
[backend/drm/atomic.c:250] Failed to acquire FB for plane 98
```

sounds like a kernel error

**Comment by xbb** [comment]
> But your fix seems have solved the problem for most people. 

Can confirm it did for me, using that patch on v0.35.0

**Comment by goggi** [comment]
> your display driver?
> 
> ```
> [backend/drm/atomic.c:250] Failed to acquire FB for plane 98
> ```
> 
> sounds like a kernel error

@vaxerski  I have now gone through the commits from 0.35.0 everything works correctly all until this commit https://github.com/hyprwm/Hyprland/commit/d62e7a5125c551fe8a94e076e64d42b702d923b1 
I went through the changes in this commit and found that if I comment out: 
https://github.com/hyprwm/Hyprland/compare/main...goggi:Hyprland:damageWindow-test?diff=unified&w=#diff-dbcd1ce1e0b916536f17c999473ad9e22c014646ddb2df15c45d726884a3481cR1267
the freeze issue stops

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14438112/patch.txt)
does this do the trick?

**Comment by goggi** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14438112/patch.txt) does this do the trick?

That did the trick! Thanks

**Comment by victorballester7** [comment]
Hi, everyone. I a newbie in Hyprland. How do I apply the patches that you are referring to to my Hyprland config?
Thanks!

**Comment by Aqa-Ib** [comment]
That patch was added to hyprland on february 28th. So if you are not using an outdated version, you already have it.

**Comment by victorballester7** [comment]
I am using `hyprland 0.40.0-1`. But I still have the problem. :( When the 2nd monitor is connected with hdmi but turned off all goes well. But if then I turn it on, the session crashes and it logs out automatically.

**Comment by Aqa-Ib** [comment]
I suggest you to first build hyprland from the latest git commit and try it because there are a lot of changes lately.

If it does not work, I would just open a new bug report and provide the requested info.

Good luck.

**Comment by victorballester7** [comment]
Thank you I will try that!
