### ISSUE TITLE
hyprctl not working 

### ISSUE THREAD

**Issue by Amrit-codes** [hyprwm/Hyprland#4772]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e793f10b8bd1685a2e2bbd7cc90063f12bf380c4 dirty (screencopy: fix invalid damage being used for final copy in dma).
Date: Tue Feb 20 01:35:51 2024
Tag: v0.35.0-57-ge793f10b

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprctl keywords not working

### How to reproduce

Try using hyprctl

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/128936479/8a28264c-603d-4272-bdcd-78cc6d128645)

**Comment by Ligthiago** [comment]
Please, refer to docs and look at subcategory: https://wiki.hyprland.org/Configuring/Variables/#blur

Yo need `hyprctl keyword decoration:blur:enabled true` in first case and `hyprctl keyword decoration:rounding 0` (without '=') in second case

**Comment by Amrit-codes** [comment]
Any idea how I can disable animation?

**Comment by Ligthiago** [comment]
`hyprctl keyword animations:enabled false` for all or `hyprctl keyword animation workspaces,1,8,default` for specific (in this case for the workspace switch) if using hyprctl. You can also disable it permanently in config. 
All possible animations can be found at https://wiki.hyprland.org/Configuring/Animations/

**Comment by vaxerski** [comment]
everything according to spec
