### ISSUE TITLE
Move workspace to monitor using direction

### ISSUE THREAD

**Issue by elythh** [hyprwm/Hyprland#4774]
### Description

Hello, there is a feature from Xorg that I'd love to see implemented in Hyprland.
The ability to move the current workspace to another monitor using the direction.

Currently the only options to move a workspace to another monitor is to specify which monitor. 
Instead, we could do something like `hyprctl dispatch moveworkspacetomonitor 1 left` or `hyprctl dispatch moveworkspacetodirection 1 left` to move the workspace to the left side monitor

**Comment by shauser** [comment]
If you switch left for l, as [documented](https://wiki.hyprland.org/Configuring/Dispatchers/#parameter-explanation), it will work perfectly fine:

```
bind = $mainMod CTRL, left, movecurrentworkspacetomonitor, l
bind = $mainMod CTRL, right, movecurrentworkspacetomonitor, r
bind = $mainMod CTRL, up, movecurrentworkspacetomonitor, u
bind = $mainMod CTRL, down, movecurrentworkspacetomonitor, d
```

**Comment by elythh** [comment]
> If you switch left for l, as [documented](https://wiki.hyprland.org/Configuring/Dispatchers/#parameter-explanation), it will work perfectly fine:

But isn't `movecurrentworkspacetomonitor` excepting a `monitor` option instead of a `direction` as described in the doc ?
