### ISSUE TITLE
`follow_mouse=2` drag & drop focus issues

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#4776]
### Hyprland Version

<details> <summary></summary>

Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.17-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 08:28:50 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When `follow_mouse=2` is set in `hyprland.conf`, if I drag & drop from one window to another, visually Hyprland will appear as if it's focus is on the window dragged to, but in reality it's focus is still on the window that was dragged from.

Furthermore, to fix the focus, you have to click on another window and then back on the window you want to focus on (clickin gon  the window that was dragged to does not change the focus unless another window is clicked first, it can be the window that was dragged from that is clicked)

So in a nutshelll, if I drag a file from my file manager to my text editor, then start trying to type things in the text editor, what'll happen is it'll instead search for files in my file manager and no input goes through to the text editor at all, I click on the text editor and nothing changes. I click on another window and then back on the text editor, and now the keyboard inputs get sent to the text editor again as they should.

### How to reproduce

- set `follow_mouse=2`
- open 2 windows
- drag and drop from one window to the other window.
- press buttons on keyboard to see which window inputs get sent to.

**Comment by vaxerski** [comment]
fixed in git
