### ISSUE TITLE
Firefox freezes when fullscreened on a second monitor

### ISSUE THREAD

**Issue by dropbear32** [hyprwm/Hyprland#4781]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.7.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P Integrated Graphics Controller [8086:4626] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```
</details>

### Bug or Regression?

Bug

### Description

When fullscreening Firefox (e.g. F11), the window will no longer update. Moving the cursor does cause the window to update, but only for as long as the cursor is being moved.

Chromium is not affected by this problem, nor is Firefox when on my laptop's built-in monitor. This only happens when Firefox is on an external monitor. (In my case, it's over HDMI.)

<details> <summary>hyprctl monitors</summary>

```
Monitor eDP-1 (ID 0):
	2256x1504@59.99900 at 0x0
	description: BOE 0x095F (eDP-1)
	make: BOE
	model: 0x095F
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.57
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-1 (ID 1):
	2560x1440@59.95100 at 1439x0
	description: Dell Inc. DELL S2721DGF B86BQ83 (DP-1 via HDMI)
	make: Dell Inc.
	model: DELL S2721DGF
	serial: B86BQ83
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.25
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```
</details>

Worth noting that setting `misc:vfr = false` or `debug:damage_blink = true` gets rid of the problem, but obviously neither are viable fixes long-term.

### How to reproduce

1. Open Firefox on an external monitor.
2. Go to a page that has motion, such as one with a video or a GIF (or open a local video file).
3. Fullscreen Firefox.

**Comment by karlwancl** [comment]
same issue happens for me
I have also found out that the stutter on 2nd monitor only happens for specific fractional display ratios.
If I set my main monitor (2560x1600@1.25 or 1.666667), my 2nd monitor (1920x1080@auto) won't stutter
but if I set it (2560x1600@1.333333 or 1.6), it will stutter

it was working before somewhere at version 0.32.x or 0.33.x but broke when arbitrary fractional display ratio is forbidden

**Comment by vaxerski** [comment]
#3778 ?

**Comment by dropbear32** [comment]
> I have also found out that the stutter on 2nd monitor only happens for specific fractional display ratios.

This appears to be the issue, or at least part of it. The freezing goes away for me at 1x scaling for the main monitor (usually 1.566667x).

**Comment by vaxerski** [comment]
can you test with #5748 merged?

**Comment by karlwancl** [comment]
can confirm it fixes the issue for me
