### ISSUE TITLE
Dropshadows are occluded by transparent windows even with decoration:shadow_ignore_window=false

### ISSUE THREAD

**Issue by chaorace** [hyprwm/Hyprland#4785]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit e5eb1bdf01013728293f4bf930dce81f1ebd366f  ().
Date: 2024-02-21
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: chao-desktop
Release: 6.7.4-2-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Sat Feb 10 09:41:20 UTC 2024


GPU information: 
0b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

I recently upgraded from a February 10th build to the latest commit as of the time of writing. After upgrading and restarting, I've found that dropshadows have begun getting occluded by transparent window borders even when `decoration:shadow_ignore_window` has been configured to `false`. (see screenshot)

### How to reproduce

1. Build Hyprland from latest source
2. Add `shadow_ignore_window = false` to the `decoration` section of Hyprland's config
3. Ensure that window borders are not disabled and have a positive size
4. Add `col.active_border = rgba(00000000)` to the `general` section of Hyprland's config
5. Restart Hyprland
6. Note the unexpected appearance of the dropshadow

### Crash reports, logs, images, videos

![306734138-8bac16b8-6c7a-4f00-91a9-ae537a2388a3](https://github.com/hyprwm/Hyprland/assets/6462592/83396a7e-ce4d-4e51-9002-9dc2c188f3c9)

**Comment by chaorace** [comment]
Oh... wait a moment I'm completely misinterpreting the output of `hyprctl getoption`. `int:0` indicates false, obviously.

Well, in that case I'll be updating my issue to reflect that shadows have begun getting occluded even with `decoration:shadow_ignore_window = false`. This is still a regression because prior to upgrading the exact same configuration would prevent that occlusion issue.

**Comment by vaxerski** [comment]
oops
