### ISSUE TITLE
Issues since the last update

### ISSUE THREAD

**Issue by iTzGooDLife** [hyprwm/Hyprland#4791]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ea3fd13e24d7d3a74cf803bef3e6133b5d708d1b dirty (shadow: fix missed invalid use of cfg val ptr).
Date: Wed Feb 21 16:26:21 2024
Tag: v0.35.0-68-gea3fd13e

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Today I updated and since then I have multiples issues. I can't share my screen, take screenshots, use swaylock, hyprpicker, among other things (I was able to do all these thing before the udpate). I think it could because xdph isn't starting. I tried to start the service, but I couldn't.

```bash
systemctl --user status xdg-desktop-portal-hyprland
× xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: failed (Result: exit-code) since Wed 2024-02-21 19:28:04 -03; 21min ago
   Main PID: 1194 (code=exited, status=203/EXEC)
        CPU: 1ms

feb 21 19:28:04 Julius systemd[915]: xdg-desktop-portal-hyprland.service: Scheduled restart job, rest>
feb 21 19:28:04 Julius systemd[915]: xdg-desktop-portal-hyprland.service: Start request repeated too >
feb 21 19:28:04 Julius systemd[915]: xdg-desktop-portal-hyprland.service: Failed with result 'exit-co>
feb 21 19:28:04 Julius systemd[915]: Failed to start Portal service (Hyprland implementation).
```

When I tried to use `swaylock` I get:

```bash
[destroyed object]: error 0: Unsupported format
```

### How to reproduce

checkout to the commit `ea3fd13` and then thy to use `swaylock`, `hyprpicker`, `satty` or share screen.

### Crash reports, logs, images, videos

As I said before, I can't take screenshots, but I'm attaching the logs.
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14366100/hyprland.log)

**Comment by ravarage** [comment]
Not sure if it related to your issue, few commit ago hypr.conf format changed you should update your config based on new change you can find it in the git changes 
I am arch user before I used xdg-desktop-portal-hyprland git version it was so buggy, I installed the version from extra repo  xdg-desktop-portal-hyprland most of my issues got fixed

**Comment by iTzGooDLife** [comment]
> Not sure if it related to your issue, few commit ago hypr.conf format changed you should update your config based on new change you can find it in the git changes I am arch user before I used xdg-desktop-portal-hyprland git version it was so buggy, I installed the version from extra repo xdg-desktop-portal-hyprland most of my issues got fixed

**Comment by iTzGooDLife** [comment]
I closed the issue by accident xd. I'm gonna look the changes and give a try to the extra repo thx.

**Comment by iTzGooDLife** [comment]
> Not sure if it related to your issue, few commit ago hypr.conf format changed you should update your config based on new change you can find it in the git changes I am arch user before I used xdg-desktop-portal-hyprland git version it was so buggy, I installed the version from extra repo xdg-desktop-portal-hyprland most of my issues got fixed

Before this update I didn't have an old version and I didn't see a big change in the format of hyprland.conf:(. Also I tried install  `xdg-desktop-portal-hyprland` from extra instead of git and the service start now but the things still doesn't work. 

The responses are the same:
```bash
$ hyprpicker
[destroyed object]: error 0: Unsupported format
zsh: segmentation fault (core dumped)  hyprpicker

$ swaylock
[destroyed object]: error 0: Unsupported format
```

**Comment by vaxerski** [comment]
I can use all of them. Please do a `git bisect`.

**Comment by iTzGooDLife** [comment]
> I can use all of them. Please do a `git bisect`.

If I installed from AUR using paru, do you recommend me to build from git and then do the git bisect?

**Comment by ravarage** [comment]
> > I can use all of them. Please do a `git bisect`.
> 
> If I installed from AUR using paru, do you recommend me to build from git and then do the git bisect?

Git bisect is command to compare git with repo if you are building from git, try to install version from aur or even chaotic repo see if that fixes your issue

**Comment by iTzGooDLife** [comment]
Before I tried `git bisect` I  wanted to try with `hyprland` package instead `hyprland-git`. The most of issues got solved, now I can take screenshots, use swaylock and hyprpicker. But I still can't share my screen. I'll do `git bisect` as you said.

**Comment by ravarage** [comment]
I have same issue it's not related to hyprland, install xdg-desktop-portal-hyprland it will fix screen share screen record and more related stuff that goes throw pipewire

**Comment by iTzGooDLife** [comment]
I already built from the git and again I can't use the things I mentioned before, like hyprpicker, swaylock, etc... I'm trying `git bisect` but when I try to compile I get an error, I left it attached. Does anyone know what the error is due to?
[build.log](https://github.com/hyprwm/Hyprland/files/14374985/build.log)

**Comment by thejch** [comment]
Are you using 10 bit? I only get this from grim when using 10 bit

**Comment by thejch** [comment]
In any case, did a bisect and I believe it's the combination of these 2 commits that broke it:
ef490965a23e043692584ae26dec4f863c88f2f6
a42b984f51a00e88a13a45e1b5e9e3d4ec470254
reverting them fixes it for me

**Comment by atropos112** [comment]
Can confirm that i am experiencing the same behaviour `[destroyed object]: error 0: Unsupported format`  on NixOS using both flakes for hyparland and xdg-desktop-portal-hyprland. I have swaylock attached to my suspend operation, when I do this swaylock is not visible after un-suspend and yet consumes about 30GB of RAM until I kill it.

**Comment by wxlyyy** [comment]
reverting ef49096 fixes it for me

**Comment by vaxerski** [comment]
is this nvidia only?

**Comment by wxlyyy** [comment]
nvidia will be this issues with 10bit

**Comment by natto1784** [comment]
okay i dont know if this is related but the screen share does not work on 10bit color but works on 8 bit color. Not using nvidia, just mesa (Arc A750).

**Comment by wxlyyy** [comment]
> > reverting [ef49096](https://github.com/hyprwm/Hyprland/commit/ef490965a23e043692584ae26dec4f863c88f2f6) fixes it for me
> 
> can confirm this is the commit where the problems start, the parent commit allows me to stream from webcord but breaks firefox altogether for me 😬 I am not using nvidia, im using mesa drivers

There will be bugs when using 10 bits, it has nothing to do with the graphics card

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14640792/patch.txt)
does this work?

**Comment by thejch** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14640792/patch.txt) does this work?

seems to work

**Comment by natto1784** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14640792/patch.txt) does this work?

yep fixes my issue at least
