### ISSUE TITLE
Fedora 39: Top-Level Steam Menus Disappear on Mouse Move

### ISSUE THREAD

**Issue by centuryboy774** [hyprwm/Hyprland#4792]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.7.4-200.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])
11:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev cb) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="39 (Sway)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Sway)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://gitlab.com/fedora/sigs/sway/SIG/-/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Sway"
VARIANT_ID=sway


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When using the Steam client on Fedora 39 with the Hyperland Wayland compositor, hamburger menus associated with top-level navigation items (e.g., "Friends," "Store") disappear immediately upon moving the mouse cursor off the initial hover area. This behavior is not present for bottom-level navigation items (e.g., "Community," "Library").

Importantly, this issue does not occur when using the Sway Wayland compositor, suggesting a potential incompatibility or bug specifically related to Hyperland. I have installed Steam from the RPM Fusion non-free repository.

This may or may not be a steam specific issue being on there end but the fact that this issue isn't present on sway makes me believe that it could be a hyprland issue. 

### How to reproduce

    1. Launch Steam on Fedora 39 with Hyperland running.
    
    2. Hover the mouse cursor over a top-level navigation item like "Store" or "Friends."
    
    3. Observe that the hamburger menu appears as expected.
    
    4. Move the mouse cursor slightly away from the navigation item.
    
    5. Notice that the hamburger menu disappears prematurely, preventing interaction with its options.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/71953305/667e8f1c-3671-45cf-be1f-5d4202b7da6a

**Comment by M-Sviridov** [comment]
Hey, I use to have the same problem but adding the following two lines to my `hyprland.conf` file seemed to fix the issue.
`windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$`

**Comment by centuryboy774** [comment]
Oh interesting, I will for try that. I wonder why this issue occurs on hyrland.

**Comment by vaxerski** [comment]
this is fixed in git
