### ISSUE TITLE
Window Rule to force cursor theme/cursor size over a client's own preferences. 

### ISSUE THREAD

**Issue by Sinaaaa** [hyprwm/Hyprland#4795]
### Description

If something like this is feasible, then this could give Hyprland users a way to replicate Yolomouse functionality in linux gaming, while also could use this combat misbehaving flatpaks.

**Comment by vaxerski** [comment]
if the app is not using the new cursor_shape protocol you can try lying to it with XCURSOR_THEME

Oherwise, this is a stupid idea imo
