### ISSUE TITLE
black screen when killing hyprland with super + m in nixos

### ISSUE THREAD

**Issue by sachinchaudhary1808** [hyprwm/Hyprland#4799]
### Hyprland Version

Hyprland, built from branch at commit v0.35.0 ().
Date: 2024-02-05
Tag:

flags: (if any)

System Information:
System name: Linux
Node name: nixos
Release: 6.7.5
Version: https://github.com/hyprwm/Hyprland/pull/1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:14:32 UTC 2024

GPU information:
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c2) (prog-if 00 [VGA controller])

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05pre586498.0e74ca98a74b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

### Bug or Regression?

Bug

### Description

so when i try to kill hyprland with mod + m it shows me black screen sometimes and sometimes don't so i have tried to do this in sway and i found the logs.

also i use greetd as a display manager i have tired like gdm sddm still this same issue

### How to reproduce

like u can't reproduce this all the time but yeah just do mod + m

### Crash reports, logs, images, videos

❯ Hyprland
Welcome to Hyprland!
[LOG] Instance Signature: v0.35.0_1708614379
[LOG] Hyprland PID: 10972
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: nixos
[LOG] Release: 6.7.5
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:14:32 UTC 2024

[LOG] GPU information:
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c2) (prog-if 00 [VGA controller])

[LOG] os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05pre586498.0e74ca98a74b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG]
Current splash: Compile, wait for 20 minutes, notice a new commit, compile again.

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 70.40µs. Estimated average calc time: 0.34µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Reloading the config!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 30.10µs. Estimated average calc time: 0.29µs.
[LOG] Using config: /home/coco/.config/hypr/hyprland.conf
[LOG] Registered dynamic var "$terminal" -> alacritty
[LOG] Registered dynamic var "$fileManager" -> kitty -e yazi
[LOG] Registered dynamic var "$menu" -> rofi -show drun
[LOG] Registered dynamic var "$browser" -> brave
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 30.52µs. Estimated average calc time: 0.34µs.
[LOG] Registered dynamic var "$mainMod" -> SUPER
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
Error: "There seems to already be another instance running..."
/bin/sh: line 1: sway-audio-idle-inhibit: command not found
registry: adding output 48
gamma control of output 48 failed
calculated sun trajectory: dawn 06:43, sunrise 07:21, sunset 18:25, dusk 19:04
setting temperature on output '48' to 4000 K
(EE) could not connect to wayland server
xhost:  unable to open display ":1"

(lxqt-policykit-agent:11006): Gtk-WARNING **: 20:36:22.019: cannot open display: :1

~ took 2s
❯
(nm-applet:11005): Gtk-WARNING **: 20:36:22.138: cannot open display: :1

(waybar:11003): Gtk-WARNING **: 20:36:22.157: cannot open display: :1

(.blueman-applet-wrapped:11008): Gtk-CRITICAL **: 20:36:22.228: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/nix/store/mid4741yhahc6zhmv1ikiq99708gvlpj-blueman-2.3.5/bin/..blueman-applet-wrapped-wrapped", line 41, in <module>
    app = BluemanApplet()
          ^^^^^^^^^^^^^^^
  File "/nix/store/mid4741yhahc6zhmv1ikiq99708gvlpj-blueman-2.3.5/lib/python3.11/site-packages/blueman/main/Applet.py", line 19, in __init__
    setup_icon_path()
  File "/nix/store/mid4741yhahc6zhmv1ikiq99708gvlpj-blueman-2.3.5/lib/python3.11/site-packages/blueman/Functions.py", line 155, in setup_icon_path
    ic.prepend_search_path(ICON_PATH)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepend_search_path'
[2024-02-22 20:36:38.040] [error] Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached
❯

**Comment by vaxerski** [comment]
#3558
