### ISSUE TITLE
Passing keybinds doesn't work

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#480]
For example, I have this in config
`bind=CTRLALT,o,pass,^(com.obsproject.Studio)$`
![image](https://user-images.githubusercontent.com/68589851/183229069-5f504671-3d54-43bf-82bf-da1afd685a5e.png)

When I actually type it, it doesn't start the recording
But I know it got somewhat passthough because when setting other keybinds, it won't let me type control+alt+o, which if it doesn't passthough, I would've been able to

**Comment by vaxerski** [comment]
have you tried other keybinds, esp a different mod? the pass feature is still indeed a bit funky.

**Comment by KyleUltimate** [comment]
Tried `CTRL + o` `CTRLSHIFT +o` `nothing + o`
None of them works

**Comment by vaxerski** [comment]
`watch -n 0.1 "cat /tmp/$(echo HYPRLAND_INSTANCE_SIGNATURE) | grep -v "nimat" | tail -n 35`

see if the logs mention that the window has not been found (pass: window not found)

I'll check it myself and probably tinker with the method a bit too.

**Comment by KyleUltimate** [comment]
by looking at the logs, it seems like when I press `CTRL o`. Most of the time, it's just stuff with IME(IME TextInupt Keyboard Grab new, Disable TextInupt etc.)
But very rarely, it will have `Keybind triggered, calling dispatcher` which does in fact activate the recording!

**Comment by vaxerski** [comment]
oh, okay I know what's happening then. The IME Grab does not have keybind processing, at all. That's why your keybind is not activated. Weird though, as your real keyboard should still have it. I'll look into that.

**Comment by vaxerski** [comment]
check with 87a2ecb90eef965bfab6a6d683db18cb99755221

**Comment by KyleUltimate** [comment]
nope, still doesn't work, although it has improved
the logs only has ` Keybind triggered, calling dispatcher (12, , 111)` this, doesn't have any IME logs when pressing the keybindgs

**Comment by Roger-Roger-debug** [comment]
The binds get passed just fine for me, however obs doesn't seem to like any keybinds with modifiers. Does the keybind work when obs has focus and it's not bound in your config?

**Comment by KyleUltimate** [comment]
It's uhh, inconclusive. If I press the two buttons at the exact same moment, it does activate. But when I do ctrl, and then f10, it doesn't work. You must really press ctrl+f10

**Comment by vaxerski** [comment]
it's still an IME thing. Outside of programs that use the native text input protocol, this doesn't happen to me.

**Comment by vaxerski** [comment]
aaand now it decided to work for me every time. I don't get it.

Maybe it's connected to the other IME issues.

**Comment by vaxerski** [comment]
please check with 6565c31dbfb590c9173a192f4f26e6ea5c787375

**Comment by KyleUltimate** [comment]
Yeah, it still has the same outcome.

**Comment by alec-lefors** [comment]
Also have this problem- logs from pressing SUPER+R multiple times:

```[LOG] Subsurface b7b5bbb0 unmapped
[LOG] Subsurface b7b5bbb0 destroyed
[LOG] Callback b7b5bcc0 -> b7b5bcb8, Subsurface removed.
[LOG] Callback b7b5bbf0 -> b7b5bbe8, Subsurface removed.
[LOG] Callback b7b5bc58 -> b7b5bc50, Subsurface removed.
[LOG] Keybind triggered, calling dispatcher (64, , 114)
```

with binding config set with: `bind=SUPER,R,pass,^(com\.obsproject\.Studio)$`

On latest release v0.11.0.beta

**Comment by alec-lefors** [comment]
> Also have this problem- logs from pressing SUPER+R multiple times:
> 
> ```
> [LOG] Subsurface b7b5bbb0 destroyed
> [LOG] Callback b7b5bcc0 -> b7b5bcb8, Subsurface removed.
> [LOG] Callback b7b5bbf0 -> b7b5bbe8, Subsurface removed.
> [LOG] Callback b7b5bc58 -> b7b5bc50, Subsurface removed.
> [LOG] Keybind triggered, calling dispatcher (64, , 114)
> ```
> 
> with binding config set with: `bind=SUPER,R,pass,^(com\.obsproject\.Studio)$`
> 
> On latest release v0.11.0.beta

I just ended up using obs-cli to get around this but let me know if additional logs/testing is needed.

**Comment by vaxerski** [comment]
Seems like OBS itself works poorly with keybinds involving mods. Even if you have it focused, it will refuse to use a hotkey e.g. `CTRL+F1`.

setting it to `F1` and passing that works as intended.

**Comment by vaxerski** [comment]
mentioned the issue on the wiki. https://wiki.hyprland.org/Configuring/Advanced-config/#global-keybinds
