### ISSUE TITLE
Incorrect resolution when hyprland started inside hyprland

### ISSUE THREAD

**Issue by loki1368** [hyprwm/Hyprland#4802]
### Hyprland Version

<details> <summary>System/Version info</summary>

Hyprland, built from branch HEAD at commit 13d985489788fa5349b3457d6eb1c19bad8f37e9  (xdgpopup: fix UAF because of an invalid listener connection).
Date: Tue Feb 20 21:14:36 2024
Tag: v0.35.0-63-g13d98548
<Paste the output of the command here>
Hyprland, built from branch HEAD at commit 13d985489788fa5349b3457d6eb1c19bad8f37e9  (xdgpopup: fix UAF because of an invalid listener connection).
Date: Tue Feb 20 21:14:36 2024
Tag: v0.35.0-63-g13d98548

flags: (if any)

System Information:
System name: Linux
Node name: home
Release: 6.6.13-gentoo-x86_64
Version: #1 SMP PREEMPT_DYNAMIC Tue Feb 20 13:59:31 MSK 2024

GPU information: 
09:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070 Ti] [10de:2782] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"

plugins:

</details>

### Bug or Regression?

Bug

### Description

When I started Hyprland inside Hyprland and main Scale factor is not equals 1.0. Resolution of inner Hyprland depends on scale factor. 

For example: 3840p host and 1.875 scale, guest Hyprland has 2048x1152 resolution instead of 3840. 

I  use nested Hyprland to start Hyprland with different XWAYLAND_NO_GLAMOR option. I need to set up this option to 0 in main session and to 1 in nested session. 

### How to reproduce

Start Hyprland inside Hyprland with Scale factor

**Comment by vaxerski** [comment]
life. That's how wlroots does it and for a good reason tbh

if anything this could be tied to #3861
