### ISSUE TITLE
Focusing a window in a special workspace should activate it

### ISSUE THREAD

**Issue by mavonarx** [hyprwm/Hyprland#4803]
### Description

When the focus changes to a window in a special workspace this workspace should get activated. (As it is the case with normal workspaces).

**Comment by v411e** [comment]
This would be great. Currently, when clicking on a notification of an app that sits in a special workspace, the background gets dimmed (I configured this to happen when opening a special workspace) and the mouse moves to the center of the (invisible) focused window, but the focused window on the special workspace is still invisible. So there seems to be a kind of switch, but it is incomplete.

**Comment by thejch** [comment]
Sounds like the same issue as what https://github.com/hyprwm/Hyprland/pull/4557 tries to fix

**Comment by MrYuto** [comment]
This is really handy when using `focusurgentorlast`
