### ISSUE TITLE
Graphical glitches are often visible on screen

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#4804]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d9757b61bfb7dcfaf3d903092435a1aaff52b7ed dirty (xdg: manually schedule initial configures).
Date: Thu Feb 22 18:33:23 2024
Tag: v0.35.0-78-gd9757b61

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.7.5-zen1-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 20:06:55 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

sometimes, when opening or closing a window, weird graphical glitches appear. those glitches usually consist in some formation of randomly placed randomly colored pixels in a selected area (usually rectangles, about ~40% of pixels appear glitched).

This is what this issue looks like, most of the time (similar glitches sometimes appear in smaller parts of the screen). It shows part of the window that was previously open, even though it might not even exist anymore. Also, as can be seen from this video, the opening time of firefox is a lot longer when the glitch appears (it should always be nearly instantaneous).

Although this could be fairly random, only using the laptop's screen seems to generate those glitches more consistently. A glitch that is always seen in that scenario is a weird grey box in the bottom left corner (possibly because of the taller aspect ratio? check the second video)

### How to reproduce

Open a window. Close it. Open another window. Sometimes, a glitched version of the old window will be seen before the new one appears

### Crash reports, logs, images, videos

All that was done in this session was opening a window, closing it, and repeating a few times (firefox or kitty), then logging out
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14379866/hyprland.log)

Recording one of my 2 external screens (0x0 in a setup with two 1920x1080 displays):

https://github.com/hyprwm/Hyprland/assets/84153269/10d256f5-774f-4e15-aa39-83181726901b

[Uncompressed video](https://imgur.com/a/E9DFg7f), yeah, its imgur, sorry, feel free to recommend anything else and I'll repost it using that asap

Recording the laptop's internal screen (0x0 in a single 1920x1200 setup, using my phone as nothing would appear when using obs, except the extremely delayed startup):

https://github.com/hyprwm/Hyprland/assets/84153269/81833132-7356-46f5-af1c-aa1f0dcdf975

[Uncompressed video](https://imgur.com/a/prQsSjk), yeah, its imgur again, sorry

**Comment by vaxerski** [comment]
do they go away if you have a non-xray blurred, floating window?

**Comment by vaxerski** [comment]
[patch69.txt](https://github.com/hyprwm/Hyprland/files/14380482/patch69.txt)
try this.

**Comment by vaxerski** [comment]
[patch69.txt](https://github.com/hyprwm/Hyprland/files/14380572/patch69.txt)
how

**Comment by vaxerski** [comment]
should be gone with 8c3613632a6ccebf9fb797ec756ecfce99514eec

**Comment by niksingh710** [comment]
> should be gone with [8c36136](https://github.com/hyprwm/Hyprland/commit/8c3613632a6ccebf9fb797ec756ecfce99514eec)

haven't faced it yet after this commit.
