### ISSUE TITLE
Chromium getting heavily distorted and not immediately updated when resized

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#4808]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c1ef361e02e4c4a52fbc5dbd9e67b79e0afab4f3  (renderer: fix logs).
Date: Thu Feb 22 16:02:48 2024
Tag: v0.35.0-82-gc1ef361e
```

</details>

### Bug or Regression?

Bug

### Description

Chromium/electron either gets distorted or goes black for a second every time it's resized.
Chromium and electron apps running in wayland native.
Doesn't happen on sway-git

### How to reproduce

1. Open chromium in wayland native mode
2. Maximize/fullscreen it, resize it or swap it with a smaller window etc (any action that resizes it). Chromium gets heavily stretched and distorted.

**Comment by Ligthiago** [comment]
Did you mean something like this? Yes, can confirm, this shit happens for a long time. Also longer animations == longer distortions.  This issue is probably a duplicate btw.


https://github.com/hyprwm/Hyprland/assets/142721811/62376988-8370-4dbc-90e2-4348c50debb0

**Comment by vaxerski** [comment]
#1462

I would have expected better from you. Search feature is right there

**Comment by thejch** [comment]
mb, only started happening to me like last week for some reason
