### ISSUE TITLE
Create a new workspace between workspaces

### ISSUE THREAD

**Issue by oati** [hyprwm/Hyprland#481]
I'm not sure if I'm missing something, but this is a feature I expected when I read "fully dynamic workspaces" in the feature list.

As far as I can tell right now, the only way to create a new workspace is by giving it a name or an ID.
For the lifetime of the workspace, the workspace's ID cannot change.
This means that if I have workspaces 1 and 2 open, I can't create a "workspace 1.5".
(Another side-effect is that I cannot reorder workspaces.)

I think this system of "static workspaces" is rigid and inflexible, since it requires you to "pre-allocate" all of your future workspaces in your mind.

For this proposed feature to work well under this system, workspace IDs would need to be automatically managed: destroying a workspace would need to collapse the IDs of any higher workspaces.

This could technically be implemented using IPC, but I feel like this feature is close enough to Hyprland's goals for it to potentially be a core feature.

(I think having a "dynamic workspaces system" in this sense would also allow for nice features down the road, like an interactive "workspaces overview" that allows you to create and reorder workspaces or move windows across workspaces.)

**Comment by vaxerski** [comment]
no. Dynamic workspaces means they are dynamically created when opened for the first time, and destroyed when out of focus and empty.

Collapsing IDs is just a great way to introduce confusion.

Workspace overview - maybe planned maybe not, doubt it's gonna happen any time soon.

This system is not static. In a static system, you config what workspaces you have, and they are open at all times, on the same display.

**Comment by oati** [comment]
How would collapsing IDs introduce confusion, if this became how the workspace system works?

**Comment by oati** [comment]
Having static integer IDs is implicitly a static system. My workspace occupies one integer and cannot easily be moved out of the way to make space for anything else - it's static within the natural numbers.

**Comment by vaxerski** [comment]
you're wrong on many levels. First of all, you can name your workspace whatever you want, not just an integer. You've clearly not read the wiki.

Second of all, your shallow thinking forgets that there are way more ways to make a workspace than with the dispatcher bound to a keybind, where the dynamic setting makes complete sense.

If in your opinion the system is static, ok. Do I care? no. That's what the system is and it will not change.

**Comment by oati** [comment]
Please, tell me. What's another way I can make a workspace, other than with a keybind?

**Comment by oati** [comment]
Your wiki doesn't even have a section on creating workspaces. You just have a generic workspace identifier that happens to include an ID and a name.

**Comment by oati** [comment]
Oh, are you going to tell me to use `hyprctl dispatch workspace`? to program an IPC app to create workspaces? That doesn't solve the underlying issue that there is no integer between 1 and 2.

**Comment by oati** [comment]
You do realize that #385 will leak the IDs to infinity unless you take this system... Why don't you close that as not planned also?

**Comment by oati** [comment]
Oh, are you going to create those by name? Well, I tested that before I made this post, having not read the wiki and all, and workspaces created by name seem to get ordered *before* numbered ones.

Besides, how are you going to systematically come up with new workspace names? I'm pretty sure that this problem is the *definition* of natural numbers - a base case and a successor map. The same problem remains.

**Comment by vaxerski** [comment]
> That doesn't solve the underlying issue that there is no integer between 1 and 2.

ok and? This is not KDE.

> You do realize that #385 will leak the IDs to infinity unless you take this system... Why don't you close that as not planned also?

if you would read the issue, you'd realize that's not the case. Also #469 mentions similiar behaviour.

Literally all you want is automatic changing of workspace IDs, which will NOT happen. Workspace ID is tied to the workspace and will never change once the workspace is open. That's how the system works and I am not willing to change it just because 0.01% of the user base wants to put a new workspace in the middle of their workspaces while moving all the others.

**Comment by oati** [comment]
Well, the solution isn't necessarily automatic changing of workspace IDs.
You could also allow workspaces to be ordered differently from workspace IDs.

**Comment by oati** [comment]
(might I remind you of the name of this issue)

**Comment by vaxerski** [comment]
There is no guaranteed order of the workspaces. Of any workspace, really. They're kept in random order, and it's up to the status bar or any other program utilizing them to order them. You can use dispatchers to move like e+1 or m+1 or -1, which will operate on IDs, but nothing is stopping you from writing your own bash script to manage workspace order however you please:
```
bind=mod,key,exec,./myWorkspaceScript.sh +1
```

**Comment by oati** [comment]
Is there any way to control the ordering for touchpad guestures?

**Comment by vaxerski** [comment]
for those, no.

**Comment by oati** [comment]
IDs also seem to determine the direction of the workspace animation. I assume this can't be controlled either?

**Comment by oati** [comment]
Would you consider a hyprland native representation of workspace ordering, independent of workspace IDs?

**Comment by vaxerski** [comment]
probably not

**Comment by oati** [comment]
ok

**Comment by humanplayer2** [comment]
Sorry if this is naive, but couldn't you set up a loop to move all windows one workspace up, leaving an empty one where you need it?

Say you have workspaces 1, 2 and 3, with 1 and 2 with windows on them. You want workspace 1.5. Then open 4, move all windows from 2 to 3, and focus on 2 (= 1.5).

**Comment by oati** [comment]
The problem with that is that (as far as I'm aware) hyprland does not support "moving all windows" between workspaces while preserving your window layout.

I have gotten this to work on sway, since sway supports reassigning workspace numbers:
https://github.com/oati/sway-workspace-manager

**Comment by Dari4sho** [comment]
@oati a bit late, but with this script + binding you can swap workspaces: https://github.com/basecamp/omarchy/discussions/1337
