### ISSUE TITLE
Todays commits break Eww bar

### ISSUE THREAD

**Issue by justinesmithies** [hyprwm/Hyprland#4818]
### Hyprland Version

Hyprland, built from branch main at commit d9757b61bfb7dcfaf3d903092435a1aaff52b7ed dirty (xdg: manually schedule initial configures).
Date: Thu Feb 22 17:33:23 2024
Tag: v0.35.0-78-gd9757b61

### Bug or Regression?

Bug

### Description

Using any version of Hyprland after the aboves version commit makes my Eww bars start to flash randomly and lose their gaps at both ends. If I roll back to the version listed above then everything is fine.
I think it is maybe the damage commit from today that is the issue linked below ?

[[renderer: nuke lastFrameDamage and rework finalDamage](https://github.com/hyprwm/Hyprland/commit/8c3613632a6ccebf9fb797ec756ecfce99514eec)](https://github.com/hyprwm/Hyprland/commit/8c3613632a6ccebf9fb797ec756ecfce99514eec)

### How to reproduce

Install any version of Hyprland after the version listed above.

**Comment by vaxerski** [comment]
sounds impossible, can I get a recording of it?

**Comment by justinesmithies** [comment]
https://github.com/hyprwm/Hyprland/assets/1571498/41eecb51-ccbc-49bf-9da2-53935ee0ad4a

As I said if I roll back Hyprland to the above commit then everything is fine. But if I use from hyprland-git on AUR today's commit which there are three then eww bar starts flashing and losing it's gaps at the edges.

**Comment by vaxerski** [comment]
should be fixed with above

**Comment by justinesmithies** [comment]
> damn justine could've been nicer to mention your bar is on the bottom layer not top as usual.
> 
> Anyways repro'd (the regressor shouldnt be what you pointed to but whatever) and working on a fix.

Sorry forgot to mention it was on the bottom layer the reason for that I cannot remember but might move it to the foreground to find out why I originally put it there ??
Any way thank you so much that did indeed fix my issue :heart:
