### ISSUE TITLE
Graphical glitches (again)

### ISSUE THREAD

**Issue by brettalcox** [hyprwm/Hyprland#4819]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
gentoo :: ~ » hyprctl version
Hyprland, built from branch HEAD at commit f389f77015ebeee30a2527b8eb7488879dd626e0  (core: Try to fix the exit hang (4811)).
Date: Fri Feb 23 10:48:27 2024
Tag: v0.35.0-84-gf389f770

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

Similar to the OG issue: https://github.com/hyprwm/Hyprland/issues/3962
And seemingly a regression of the just fixed https://github.com/hyprwm/Hyprland/issues/4804

The issue _does_ go away if you float a window with blur 

### How to reproduce

Open a master and slave window, shift focus between the two and artifacting/glitching is noticed in lower right quadrant.

**Comment by brettalcox** [comment]
https://github.com/hyprwm/Hyprland/assets/7462622/b2d8bf26-06cd-4870-be19-39cdabf0eb80

**Comment by vaxerski** [comment]
regressed by what? `git bisect`

**Comment by brettalcox** [comment]
@vaxerski c353b7c4f75e53af006bc2cf686b02c9a6495b60

**Comment by brettalcox** [comment]
also, nvidia per usual

**Comment by vaxerski** [comment]
I guess it's nvidia being nvidia. I'll add an option to force enable introspection.

I assume having a floating, non-xray blurred window fixes the artifacts, as usual?

**Comment by brettalcox** [comment]
@vaxerski yep floating blur fixes it

**Comment by vaxerski** [comment]
nvidia fuck you :)

**Comment by vaxerski** [comment]
default is `2` aka "yes if nvidia" so defaults should cover ya
