### ISSUE TITLE
[animations] minimum size option for scale

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#482]
# Problem
When windows scale onto the screen when at the start of the animation they are really small they look pixialted and bad
# Solution
Is it possible to have an optional minimum scale option for the scale animation eg:
```
animation=windows,1,5,scale,70% # <- last value is minimum scale option
```
This would mean that windows start there scale animation at 70% so the animation looks more like it does on gnome

**Comment by vaxerski** [comment]
done in 64e80991ca335c4ef7da736bb5582747caca284a

really cool effect, ngl.

how 2 use (example):
```
animation=windows,1,8,default,popin 80%
```
