### ISSUE TITLE
Binding $mainMod + Shift + e dosen't work as expected

### ISSUE THREAD

**Issue by distek** [hyprwm/Hyprland#4824]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

Hey there!

I was trying to figure out why my script kept crashing hyprland _(or so I thought)_ every time I tried to run it when bound like this:
```
bind = $mainMod SHIFT, e, exec, /path/to/script
```

Took entirely way to long for me to try binding a different key, only to find out that apparently `$mainMod SHIFT, e` is hardcoded _somewhere_ to exit hyprland.

Where is this defined? _Is_ it defined somewhere? I may also be missing something with the default config on my system, though I'd believe hypyland only uses the config in my `~/.config/hypr` if present.

I couldn't find anyone else having this issue, though it's kind of weird to search for.

Let me know if there's any more info I can provide!

### How to reproduce

In the config:
```
bind = $mainMod SHIFT, e, exec, /path/to/script
```

And experience it not working as expected.

### Crash reports, logs, images, videos

[hypr.log](https://github.com/hyprwm/Hyprland/files/14391290/hypr.log)

**Comment by vaxerski** [comment]
it's not hardcoded, and you are using an extremely outdated version.

**Comment by distek** [comment]
Updated:
```
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

```

Still happening, however.

Does hyprland cascade configurations or does it just use the one in my local configuration directory?

**Comment by vaxerski** [comment]
reads `~/.config/hypr/hyprland.conf`

Pretty sure you just have an odd bind somewhere. You can check with `hyprctl binds | grep -C3 "key: a"` and `hyprctl binds | grep -C3 "key: A"` for uppercase

**Comment by distek** [comment]
There it is:
```
bind
        modmask: 65
        submap:
        key: E
        keycode: 0
        dispatcher: exit
        arg:
```

I was searching for `e` not `E`:
```
bind = $mainMod SHIFT, E, exit,
```

Apologies for the noise!
