### ISSUE TITLE
gaps_out needs window refresh when set from a script

### ISSUE THREAD

**Issue by schromp** [hyprwm/Hyprland#4830]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ea3fd13e24d7d3a74cf803bef3e6133b5d708d1b  ().
Date: 2024-02-21
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: tower
Release: 6.1.78
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 16 18:06:32 UTC 2024


GPU information:
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c3) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240221.0e74ca9"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When running the command ```hyprctl keyword general:gaps_out 15``` from inside a script or a tmux session the window needs currently displayed windows need to refresh to respect the new setting.
The refresh can be achieved through:
1. changing workspaces
2. resizing the window
3. using movewindow

When runnning from inside a normal terminal it works.

### How to reproduce

Run the command ```hyprctl keyword general:gaps_out 15``` from a script or inside a tmux session.

**Comment by vaxerski** [comment]
`hyprctl -r keyword general:gaps_out 15`?

**Comment by schromp** [comment]
> `hyprctl -r keyword general:gaps_out 15`?
> 
> Also I believe [e9528fc](https://github.com/hyprwm/Hyprland/commit/e9528fc214bb3d807a4fcb6d35894f59760fba51) fixed this.

Ah yes that on the latest commit this works even without -r. Thanks :)
