### ISSUE TITLE
Changing between fullscreen modes 0 and 1 should not require going out of fullscreen

### ISSUE THREAD

**Issue by batsim** [hyprwm/Hyprland#4831]
### Description

Currently, using any `fullscreen` bind while already in fullscreen will put the user back into non-fullscreen mode. 

However, `fullscreen` and `fullscreen, 1` are visually distinct from each other, thus using `fullscreen` while in `fullscreen, 1` should still send the user into fullscreen mode, and vice-versa.

**Comment by thejch** [comment]
Same as https://github.com/hyprwm/Hyprland/issues/2662?

**Comment by vaxerski** [comment]
I think so.
