### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by human-0** [hyprwm/Hyprland#4833]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: [name]
Release: 6.7.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 630 [8086:5912] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK208B [GeForce GT 730] [10de:1287] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

After about three hours with `swaylock`, Hyprland crashed. The keyboard and mouse were disconnected and the monitor was switched off. The Intel graphics was being used and the display was connected to motherboard output. This does not happen every time.

Possibly related: usually, when Hyprland if left in similar circumstances, after connecting the mouse and keyboard and switching on the monitor, Hyprland does not respond until the monitor is disconnected and reconnected (stays on blank swaylock screen). No idea if this is a Hyprland issue, but it did not happen before some recent updates (not sure which updates, unfortunately).

### How to reproduce

No idea, it doesn't happen every time.

### Crash reports, logs, images, videos

[hyprland_crashreport.txt](https://github.com/hyprwm/Hyprland/files/14394666/hyprland_crashreport.txt)

**Comment by vaxerski** [comment]
try on -git.

**Comment by human-0** [comment]
Seems fixed.
