### ISSUE TITLE
dpi changes when charger plugged in

### ISSUE THREAD

**Issue by posilash** [hyprwm/Hyprland#4836]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: annihilator
Release: 6.7.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q] [10de:249d] (rev a1) (prog-if 00 [VGA controller])
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:>
```

</details>

### Bug or Regression?

Bug

### Description

I have a 2k screen on my laptop, so i set the dpi to scale 1.25 but whenever i plug the charger in the dpi scale changes to 1.
EDIT:
Apparently whenever i plug in the charger, it is read as a lid switch event which then triggers my script bound to the lid switch keybind in the configuration.
Why is it being recognized as a lid switch event?

### How to reproduce

Set dpi in monitor = preferred, auto, 1.25
Plug charger in
dpi scale changes to 1

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/114579277/1eb0dbfb-018a-4d8d-a3a4-5301f8500622

**Comment by vaxerski** [comment]
sounds to me like you installed some dotfiles that you dont understand? hyprland will not do this by itself.

**Comment by posilash** [comment]
Apparently, my charger getting plugged in is being registered as a lid switch key press, therefore activating a key bind.
You're right its not a hyprland issue.

**Comment by vaxerski** [comment]
> Apparently, my charger getting plugged in is being registered as a lid switch key press, thereby activating a key bind.

ah yes since some kernel ver my laptop does this too

**Comment by posilash** [comment]
So, is it a hyprland issue?
I'm reopening the issue, since no other solution seems to work.
Not even a udev scancode mapping.

**Comment by vaxerski** [comment]
it's not a hyprland issue, it's kernel doing it. FWIW it's firing an `on` and `off` event almost instantly so you can wait like 0.5s and see if the other wasnt triggered (a bash script would do)

**Comment by posilash** [comment]
Alright, I'll keep the issue closed then.
Thank you.
