### ISSUE TITLE
Firefox freezes after switching ttys

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#4841]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 5824b0f305e95132184241832653d528b12c75e2 dirty (hyprctl: fix showing invalid instances).
Date: Sat Feb 24 09:36:43 2024
Tag: v0.35.0-92-g5824b0f3
```

</details>

### Bug or Regression?

Bug

### Description

Firefox freezes if i switch to another tty and back
Edit: after some testing pretty sure it's not a regression so it might be some new firefox changes or something, but doesn't happen on sway.

Maybe related: https://github.com/hyprwm/Hyprland/issues/4781 

### How to reproduce

Open firefox
Ctrl+alt+f2 to tty2
Ctrl+alt+f1 back to tty1
Firefox is frozen

**Comment by vaxerski** [comment]
bisect if regression

**Comment by thejch** [comment]
> bisect if regression, you can also check older ff vers (worth noting never happened to me)

After some testing pretty sure it's not a regression so it might be some new firefox changes or something, also could be related to green gpu, but it doesn't happen on sway so I'm keeping this for now.

**Comment by rurigk** [comment]
I cant reproduce Firefox 123.0 (64-bit) with MOZ_ENABLE_WAYLAND=1
Hyprland https://github.com/hyprwm/Hyprland/commit/f590505daf90dfb4059289a906863b59663e70a6

**Comment by thejch** [comment]
> I cant reproduce Firefox 123.0 (64-bit) with MOZ_ENABLE_WAYLAND=1 from Arch repos Hyprland [f590505](https://github.com/hyprwm/Hyprland/commit/f590505daf90dfb4059289a906863b59663e70a6)

I suspect it's green gpu related then.

**Comment by talpadk** [comment]
I think I can reproduce on an AMD iGPU 
AMD Renoir [Radeon RX Vega 6 ]
in a
AMD Ryzen 7 PRO 4750U

Hyprland, built from branch main at commit 063708df26e8b930f492200e1907eb47950f50e6 dirty (config: improve config value infrastructure).
Date: Sun Mar 3 19:41:38 2024
Tag: v0.36.0-43-g063708df

My Firefox 123.0 from the Debian unstable package "firefox/unstable,now 123.0-1 amd64"
Doesn't freeze totally, only mouse input is unresponsive, it still reacts to keyboard input

When starting it from a terminal it spams "Error: WaylandMessage::Write() too many files to send" after the VT switch

**Comment by talpadk** [comment]
Does not seem to affect the nightly build of firefox "firefox-125.0a1.en-GB.linux-x86_64.tar.bz2"

**Comment by talpadk** [comment]
Also affects firefox/unstable,now 124.0.1-1 amd64 , hopeful that when Debian packages 125 this will fix it for me

**Comment by sungyoonc** [comment]
For me the mouse input is not working in firefox after switching ttys, keyboard still works though.

**Comment by sungyoonc** [comment]
Firefox seemed to have fixed the issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1882449

And like @talpadk said, the issue doesn't happen since [125.0a1 (Build ID: 20240229210642)](https://hg.mozilla.org/mozilla-central/firefoxreleases#e094286867e7nightlylinux3220240229210642)

**Comment by vaxerski** [comment]
can this be closed then?

**Comment by sungyoonc** [comment]
Maybe after @thejch confirms this fixes the issue
