### ISSUE TITLE
Fullscreen window + floating window breaking click handling

### ISSUE THREAD

**Issue by kaarelen** [hyprwm/Hyprland#4843]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
cub@cubic ~/P/grayjay_desktop> hyprctl version
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Fullscreen window + floating window breaking click handling - while i have fullscreen window, floating window from same workspace captures mouse events (clicks, at least)

### How to reproduce

1) make floating window (with YouTube video for good example)
2) make any other window fullscreen (in my case, it's browser in tiling mode)
3) click in place where was floating window before making another window fullscreen
4) floating window will receive click, while I CANT see it, because it's "under" fullscrreen window

Additional: mouse hover will work not properly too, but only when my mouse hovering over floating window position AFTER first click in same way as described in STR.

### Crash reports, logs, images, videos

There is no crash, so no logs.

**Comment by vaxerski** [comment]
that's fixed in git

**Comment by kaarelen** [comment]
thanks!
