### ISSUE TITLE
Unable to set OpenGL force_introspection setting

### ISSUE THREAD

**Issue by BeauTaapken** [hyprwm/Hyprland#4846]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 86be75dd97b5633b8c0aa6bdcb3346fa871a8480 dirty (events: bring back accidentally nuked preConfigReload).
Date: Tue Feb 20 04:24:15 2024
Tag: v0.35.0-59-g86be75dd

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000


GPU information: 
2d:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  split-monitor-workspaces by Duckonaut ver 1.1.0
```

</details>

### Bug or Regression?

Bug

### Description

When i try to set
`opengl {
    force_introspection=0
}`

in my hyprland config file, I get the following error: config option <opengl:force_introspection> does not exist.
I would like to try changing it, to see if i can get my performance in games to be a bit better, but I'm unable to test this setting right now. Enabling tearing and the nvidia anti flicker setting seem to improve the stuttering of games I've been running into, so I was hoping that force_introspection set to 0 (instead of the default 2) might make it even better.

### How to reproduce

Go into your hyprland.conf file and add 
`
opengl {
    force_introspection=0
}
`

**Comment by vaxerski** [comment]
for the love of god please make sure you're on latest before opening issues about config options from the -git wiki being missing

**Comment by BeauTaapken** [comment]
> for the love of god please make sure you're on latest before opening issues about config options from the -git wiki being missing

Sorry about that, thought i was on latest, seems i was wrong though, next time I'll double check
