### ISSUE TITLE
External Monitors Detected But Inactive

### ISSUE THREAD

**Issue by treatybreaker** [hyprwm/Hyprland#485]
Hey, great project here!

Unfortunately, I've run into a bit of a bug with connecting an external monitor to my laptop. I've tested out another compositor, [river](https://github.com/riverwm/river), that works on multiple displays. This seems to be a hyprland issue specifically. 

Here's what I get from `hyprctl monitors`:
```
Monitor eDP-2 (ID 0):
	2560x1600@120.000000 at 0x0
	active workspace: 1 (1)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	active: yes

Monitor DP-2 (ID 1):
	2560x1440@59.951000 at 2560x0
	active workspace: 2 (2)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	active: no
```

And here's my configuration:
```
monitor=eDP-1,2560x1600@120,0x0,1
monitor=eDP-2,2560x1600@120,0x0,1
monitor=DP-2,2560x1440@60,2560x0,1

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=1

    touchpad {
        natural_scroll=no
    }
}

bind=SUPER,RETURN,exec,wezterm
bind=SUPER,F,exec,firefox
bind=SUPER,Q,killactive,
bind=SUPER,M,exit,
```

When checking `wlr-randr` it shows the second monitor (DP-2) as `Enabled: no`.

Again, river runs the second monitor just fine, so I'm not quite sure what I've done wrong here.
I'm running an AMD GPU and AMD CPU (6900S & 6900H respectively).

Here's my [hyprland.log](https://pastebin.com/Diza4YYt).

I believe this to be a bug, but if I've done something boneheaded then I apologize ahead of time.

EDIT: To be clear the bug is that the external monitor is a blackscreen -- not on, but it's detected.

**Comment by vaxerski** [comment]
whats the bug, you didnt tell me.

**Comment by treatybreaker** [comment]
Apologies, yeah you're right. The bug is that the second monitor sees the output but doesn't turn on. External monitor is left black.

**Comment by vaxerski** [comment]
```
[ERR] Couldn't commit output named DP-2
```
can you try a different mode for it? try `preferred` first, check if that works, and if no, try a lower res from the options `wlr-randr` will give you. (just type `wlr-randr` in a terminal to get the modes printed out)

**Comment by treatybreaker** [comment]
Setting to preferred results in a black screen with `hyprctl monitors` giving:
```
Monitor eDP-2 (ID 0):
	2560x1600@120.000000 at 0x0
	active workspace: 1 (1)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	active: yes

Monitor DP-3 (ID 1):
	1280x720@60.000000 at 0x0
	active workspace: 2 (2)
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	active: no
```
I had to duplicate a line for `DP-3` now.

And setting the monitor to 
```
monitor=DP-3,800x600@72,2560x0,1
```

Still results in a black screen.

Here's my [wlr-randr output](https://pastebin.com/RfM40w7B).

**Comment by vaxerski** [comment]
alright. I'll look into it. It's midnight atm and I'm on vacation, so I'll see what I can do in the evening tomorrow.

**Comment by treatybreaker** [comment]
Yeah, thanks, after all you're providing this for *free*. Really appreciate you looking into it.

**Comment by treatybreaker** [comment]
I found the issue: has to do with how AMD handled muxing and hybrid mode with an iGPU & dGPU on linux.

With how I have the laptop set only a single port on the left side is actually good -- had to buy a external USB-C to display port cable and that is now working flawlessy.

Sorry for taking up your time and I hope you enjoy your vacation :).

**Comment by vaxerski** [comment]
weird that river works though.

**Comment by cvanelteren** [comment]
I have a similar problem that occurs where the monitor is not detected after hibernation, is there a fix for this?
