### ISSUE TITLE
radical request : Scrollable tiling mode

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4852]
### Description

Scrollable tiling is implemented by [niri](https://github.com/YaLTeR/niri), It will be wonderful to have it as another choice in addition to darwin and master mode.

**Comment by vaxerski** [comment]
No. https://gitlab.com/magus/hyprslidr

**Comment by vincentaxhe** [comment]
> Also [Hyprscroller](https://github.com/dawsers/hyprscroller)

yeah, I use it in 0.39, but failed to complie it ever since, now 0.41, I cannot even sucessfully update hyprpm, I  just ignore it, scrollable tiling mode is not attractive to me like before.

**Comment by Malix-Labs** [comment]
Btw now there is the official [hyprscrolling](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprscrolling) plugin

**Comment by PixsaOJ** [comment]
hyprscrolling is now merged to hyprland

**Comment by Malix-Labs** [comment]
@PixsaOJ can you please link to the source of that information (a PR, a commit, anything) ?

Also, it's still showing in https://hypr.land/plugins/

**Comment by PixsaOJ** [comment]
@Malix-Labs its in docs, in Layouts
https://wiki.hypr.land/0.54.0/Configuring/Scrolling-Layout/

**Comment by Malix-Labs** [comment]
@PixsaOJ is that a 1:1 hyprscrolling implementation? What are the details?

**Comment by PixsaOJ** [comment]
@Malix-Labs This is a merge of this plugin into `hyprland`. So we can use exact same thing without plugin. And bonus+ we don't need custom shortcuts to customize navigation.

I suggest you try it yourself.
