### ISSUE TITLE
Filebot not running correctly 

### ISSUE THREAD

**Issue by tippunmon1953** [hyprwm/Hyprland#4854]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Installed hyprland on Arch. Very impressed but couldn’t get Filebot to operate correctly. Neither the AUR version or the flatpak version runs in hyprland arch. Advised filebot who responded they had “never heard of hyprland” and wished me luck in sorting it myself. Great.

### How to reproduce

Try Filebot on hyprland arch and let us know

**Comment by vaxerski** [comment]
invalid.

No version.
No logs.

> dvised filebot who responded they had “never heard of hyprland” and wished me luck in sorting it myself.

it's their app. Not my problem. Every other app runs. 

Never heard of filebot.

**Comment by tippunmon1953** [comment]
Now resolved. Discovered a solution.
