### ISSUE TITLE
Explicit sync support

### ISSUE THREAD

**Issue by LazarusCat59** [hyprwm/Hyprland#4857]
### Description

As the [linux-drm-syncobj-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/90) wayland protocol MR is ready to merge, and the wlroots implementation ([wlroots!4262](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4262) and [wlroots!4260](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4260)) is pretty much complete, I would like to request explicit sync support in the compositor too. For NVIDIA users like me this is really important since it gets rid of lot of flickering and artifacts in apps like Steam and Spotify and a bunch of games, since the driver lacks support for implicit synchronization. Thanks a lot for the awesome work you've done here, and I hope this can be implemented soon!

**Comment by HirschBerge** [comment]
Since NixOs has now moved the production nvidia drivers to 550, this has pretty much blocked me from being able to game on my desktop.

**Comment by vaxerski** [comment]
no need to leave pointless comments - I can't force our Lord and Savior Simon Ser the Great to merge everything right away. Leave a :+1: and be patient.

**Comment by Fxzzi** [comment]
The compositor does not REQUIRE explicit sync support for these patches to work AFAIK. It will just fix edge cases and provide optimal performance. I've tested with these patches and they have fixed things without changes in Hyprland (has not fixed everything ofc, that would require a driver update and POSSIBLY this being implemented in Hyprland)

**Comment by akshitgaur2005** [comment]
@HirschBerge Wait it is because of 550 version that I am not able to game. Should I switch to stable?

**Comment by irldoggo** [comment]
> @HirschBerge Wait it is because of 550 version that I am not able to game. Should I switch to stable?

I rolled back to the 535 drivers. That more or less solves the horrid desync issues in the meantime. However it seems that we won't have to wait much longer. The 555 drivers next month(ish) along with most of the explicit sync patches being mainlined (mesa, xwayland, xdg) should solve the problems we are facing. At least this one. My misinformed self was under the impression that it was a problem with Hyprland, but it really isn't. The problem really seems to be with the aforementioned packages and the lack of explicit sync support. There isn't really anything the Hyprland team can do about it until these changes roll out.

**Comment by LazarusCat59** [comment]
> I rolled back to the 535 drivers. That more or less solves the horrid desync issues in the meantime. However it seems that we won't have to wait much longer. The 555 drivers next month(ish) along with most of the explicit sync patches being mainlined (mesa, xwayland, xdg) should solve the problems we are facing. At least this one. My misinformed self was under the impression that it was a problem with Hyprland, but it really isn't. The problem really seems to be with the aforementioned packages and the lack of explicit sync support. There isn't really anything the Hyprland team can do about it until these changes roll out.

Actually, the explicit sync changes won't be in the NVIDIA driver until 560. See [here](https://github.com/NVIDIA/egl-wayland/pull/104#issuecomment-2029850414). I sure hope the wlroots changes don't take too long though, the MR has been active for quite a long while.

**Comment by Fxzzi** [comment]
> > The 555 drivers next month(ish) along with most of the explicit sync patches being mainlined (mesa, xwayland, xdg) should solve the problems we are facing. At least this one.
> 
> Actually, the explicit sync changes won't be in the NVIDIA driver until 560. See [here](https://github.com/NVIDIA/egl-wayland/pull/104#issuecomment-2029850414). I sure hope the wlroots changes don't take too long though, the MR has been active for quite a long while.
> 
> Edit: I think explicit sync changes for Wayland Vulkan programs is the one meant for 560, rest of the changes will be in 555.

Correction:

It'll be there for Xwayland / X11, EGL Opengl etc but not for vulkan.

**Comment by diniamo** [comment]
With Hyprland having its own wlroots fork, is there a chance we can get preemptive patches of the 2 MRs (see the original post for links), and a Hyprland implementation (if there needs to be one)?

**Comment by vaxerski** [comment]
right now, no, too busy with other stuff. In the near future, I'd hope to either do this or rewrite the backend altogether.

**Comment by SamuelGogarty** [comment]
> right now, no, too busy with other stuff. In the near future, I'd hope to either do this or rewrite the backend altogether.

To clarify, we shouldn't be expecting explicit sync support being added to hyprland when nvidia 560 gets released?

**Comment by vaxerski** [comment]
You shouldn't. Nvidia drivers don't matter here.

If someone wants to write an impl based on the not-yet-merged two wlroots MRs and gets it working, sure I can merge it. But I probably won't write it because (busy as can be seen) and I don't even have the hardware (nvidia) to like... fully verify it's working.

**Comment by diniamo** [comment]
I don't think you would have trouble with testing this, since this is the single most important change for nvidia, a lot of people would volunteer.

**Comment by vaxerski** [comment]
just like we can see with 5902 this approach sucks. I hope I can at least in some way verify this on my rig whenever I get to it.

But yea, if anyone wants to write this with the wlroots MRs be my guest

**Comment by SamuelGogarty** [comment]
> You shouldn't. Nvidia drivers don't matter here.
> 
> If someone wants to write an impl based on the not-yet-merged two wlroots MRs and gets it working, sure I can merge it. But I probably won't write it because (busy as can be seen) and I don't even have the hardware (nvidia) to like... fully verify it's working.
> 
> When (if) I will be rewriting the backend I will have a stab at it in the new backend, but that will not be that soon I am afraid.

why don't nvidia drivers matter here? 
A lot of people use nvidia, why simply neglect to support it? especially with all the wayland compositors and nvidia implementing explicit sync support?

**Comment by vaxerski** [comment]
I said that whether the driver supports it doesn't matter until the compositor supports it too.

I am not neglecting it, I just have other stuff to do. If you want it so much, I welcome you to write an impl based on the wip wlroots MRs and make a MR to hyprland. It's foss.

**Comment by SamuelGogarty** [comment]
> I said that whether the driver supports it doesn't matter until the compositor supports it too.
> 
> I am not neglecting it, I just have other stuff to do. If you want it so much, I welcome you to write an impl based on the wip wlroots MRs and make a MR to hyprland. It's foss.

I clearly misunderstood then, I appreciate the clarification.

**Comment by chairclr** [comment]
The 555 Beta driver released early today and seems to have fixed all the Xwayland flickering issues for me.

**Comment by NEUKhoaLe** [comment]
The driver should fix most issues, but compositor support will improve performance and remove edge cases. In his blogpost, Varxy will implement explicit sync after the backend rewrite

**Comment by akshitgaur2005** [comment]
> The 555 Beta driver released earlier today and seems to have fixed all the Xwayland flickering issues for me.

Wait, I am on nixos-unstable, if I update will I get it too?

**Comment by SamuelGogarty** [comment]
I have also updated to 555, all previous observed issues are gone.

**Comment by w-lfchen** [comment]
> Wait, I am on nixos-unstable, if I update will I get it too?

No, you'll have to wait until https://github.com/NixOS/nixpkgs/pull/313440 is merged and [makes its way through hydra](https://nixpk.gs/pr-tracker.html?pr=313440).

There are workarounds if you want to run the driver now, but you might have to compile things yourself depending on what you do.

**Comment by FrancescoCaracciolo** [comment]
I also updated to 555 (Arch, RTX 3060, hyprland-git), all the flickering problems in games and electron applications seem to be fixed

**Comment by gnusenpai** [comment]
XWayland seems pretty solid in 555, but Chromium/Electron under native Wayland still has glitching/hitching. Ironically, it's more stable under XWayland now lol. Sounds like I might be hitting some edge case, so I imagine we'll need explicit sync in the compositor to iron the rest out.

**Comment by diniamo** [comment]
Yep, can't do anything about that until Hyprland gets explicit sync support. Use either xwayland or --disable-gpu for electron apps. I personally use the latter since I prefer avoiding Xwayland, but I've been told that it doesn't work well for 4k monitors, since it becomes laggy.

**Comment by akshitgaur2005** [comment]
> > Wait, I am on nixos-unstable, if I update will I get it too?
> 
> No, you'll have to wait until [NixOS/nixpkgs#313440](https://github.com/NixOS/nixpkgs/pull/313440) is merged and [makes its way through hydra](https://nixpk.gs/pr-tracker.html?pr=313440).
> 
> There are workarounds if you want to run the driver now, but you might have to compile things yourself depending on what you do.
> 
> Edit: The pr has been merged and the tracking website is broken for some reason. If I'm not mistaken, this commit should be in unstable and therefore in the caches as well once https://hydra.nixos.org/eval/1806475 is done.

Thanks for that. I have updated to the new 555 driver through manually selecting the package. Although I see very little/no improvement in the performance.

**Comment by w-lfchen** [comment]
> Thanks for that. I have updated to the new 555 driver through manually selecting the package. Although I see very little/no improvement in the performance.

I just checked, the driver [is in unstable](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/nvidia-x11/default.nix) now.
I haven't been able to test anything so far, though I think using the latest hyprland commit, for example through the flake, could potentially improve your experience there

**Comment by chrbauer** [comment]
With RTX 3060 and 555 driver (NixOS, unstable) there are some flickering problems in chromium (scrolling). They are not visible with 535 driver. Hyperland version is 0.39.1.

**Comment by Atemo-C** [comment]
My system is currently on [NixOS 24.05](https://nixos.org/blog/announcements/2024/nixos-2405/), using the `NVIDIA 555` drivers from the unstable branch with the `ZEN` Linux kernel, with `Hyprland` also from the unstable branch. My GPU is an NVIDIA GTX 1660 SUPER.

`Hyprland` is just as stable as before, performances seem to have improved in most of my games, and most `Xwayland` programs no longer have issues on my end. Also, [Steam](https://store.steampowered.com/) no longer has huge graphical glitches with GPU acceleration enabled on my end, which is really f🦆cking nice.

However, as pointed out by @gnusenpai, some *(at least, the ones I use)* Wayland-native Electron programs do have flickering and various graphical issues. This is, for example, the case for me with [Vesktop](https://github.com/Vencord/Vesktop) and [Element desktop](https://github.com/element-hq/element-desktop). Running them through Xwayland now seems to fix most of these issues, which is, well, quite ironic, but of course, it breaks other things such as screen sharing without the use of something like [XWayland Video Bridge](https://github.com/KDE/xwaylandvideobridge).

I have no idea how much of the remaining issues are because of the drivers, Electron, or Hyprland, but the experience still remains much better than it used to be.

**Comment by diniamo** [comment]
Those issues already existed, and read my comment. They will be fixed when Hyprland gets explicit sync support.

**Comment by Myew420** [comment]
> I have also updated to 555 (Arch, RTX 3060, hyprland-git), all the flickering problems in games and electron applications seem to be fixed

ain't no fucking way sir.

**Comment by proJM-Coding** [comment]
I still have problems in super tux. Other than that it's all fixed.

**Comment by UjinT34** [comment]
wlroots MR moved to [wlroots!4715](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4715)

**Comment by VectorKappa** [comment]
> wlroots MR moved to [wlroots!4715](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4715)

The MR has been approved! Now we're waiting for the merge.

**Comment by diniamo** [comment]
The wlroots MR is irrelevant. Explicit sync is only being implemented after wlroots is gone from Hyprland.

**Comment by cinnamonpancake** [comment]
`--disable-gpu-compositing` fixes chromium flickering for me without completely disabling hardware acceleration

**Comment by pati08** [comment]
@diniamo Yeah, that beef vaxry had is now measurably hurting Hyprland's users.

**Comment by faileon** [comment]
> `--disable-gpu-compositing` fixes chromium flickering for me without completely disabling hardware acceleration

I tried this with vesktop. While it did fix every flickering issue, it also kinda disables hw acceleration. nvidia-smi reports vesktop only uses 4MiB while having fullscreen screenshare. Without the flag it reports ~133MiB.

**Comment by vaxerski** [comment]
explicit sync is being worked on in #6608

**Comment by maakiono** [comment]
can this be closed now that #6608 is merged?

**Comment by vaxerski** [comment]
Not 100%, because explicit sync is experimental and has some issues

**Comment by BasitAli** [comment]
@vaxerski On the latest git, what else do I need other than `experimental:explicit_sync = true` in my config? I am find with it being experimental but not sure at all if it's enabled for me. I am on the latest drivers and everything. Any way I can debug if it's indeed enabled?

**Comment by vaxerski** [comment]
thats all, a restart of hl is needed for it to take effect though

**Comment by BasitAli** [comment]
I was hoping to see reduced flashes with this enabled or maybe some other strange stuff. But I don't see anything different at all. Would love some pointers to how I can enable debug logs for aq and review them to see this log https://github.com/hyprwm/aquamarine/blob/601f6cf95cbe4fef02dc7faf34bba58566c914e9/src/backend/drm/DRM.cpp#L1197

**Comment by vaxerski** [comment]
it's printed to your hl log

if you enable tracing in hyprland `HYPRLAND_TRACE=1` you should see a spam of logs related to explicit sync if it's working.

Worth noting it's mesa that uses it, and for example on my RX 6700 XT it decides not to, but for nvidia and others it does.

**Comment by Honkazel** [comment]
Mesa uses it only for vulkan and for opengl it still does implicit sync(default for opengl, but nvidia don't think so)

**Comment by BasitAli** [comment]
Yeah, I've been reading about Mesa and unfortunately at this point, I don't understand what you mean 😕. Chrome and electron based apps have been the ones with the most issues with flickering. Worth mentioning that firefox seems to be working pretty well so far (don't remember if it had flickers or not in the past).

**Comment by Atemo-C** [comment]
I personally have no flickering issues outside of Electron apps running natively under Wayland (though forcing them through Xwayland gets rid of most bugs, but it's not ideal). Drivers 555.58.02, CUDA 12.5. With my AMD GPU, of course, everything works fine.

**Comment by diniamo** [comment]
> Yeah, I've been reading about Mesa and unfortunately at this point, I don't understand what you mean 😕. Chrome and electron based apps have been the ones with the most issues with flickering. Worth mentioning that firefox seems to be working pretty well so far (don't remember if it had flickers or not in the past).

Firefox never had flickers in the first place, however it's weird that it works perfectly for you, because it's supposed to crash with explicit sync. Do you use nightly?

**Comment by BasitAli** [comment]
@Atemo-C Yeah, it's nvidia I am stuck with that has all these issues.

@diniamo It does run pretty well which is why I had the doubt that explicit sync may not really be enabled for me.

I do see these log entries which may indicate it indeed is enabled,

```
[LOG] [DRMSyncobj] New linux_drm_timeline at 6501c8f8abd0
[LOG] [DRMSyncobj] New linux_drm_timeline at 6501c8f49d60
[LOG] [DRMSyncobj] New linux_drm_timeline at 6501c8f601e0
```

**Comment by diniamo** [comment]
Sooo when are we gonna talk about how explicit sync just doesn't work?

The best proof I've found is with https://github.com/ascent12/compositor-killer (credit: @ErrorNoInternet). Running it on KDE Plasma works fine, but running it on Hyprland doesn't (meaning explicit sync doesn't work).

**Comment by vaxerski** [comment]
It's tagged as experimental for a reason. Feel free to contribute and fix it in a MR, I'd be happy to accept it.

I am overworked enough

**Comment by diniamo** [comment]
I have no idea about Wayland, nor the graphics stack sadly. Just wanted to make sure that you are aware.

**Comment by vaxerski** [comment]
#7151 should close this as explicit sync will be finalized

**Comment by vaxerski** [comment]
nota bene we need testing there so feel free

**Comment by b33slayer** [comment]
> nota bene we need testing there so feel free

what do i need to add to the hyprland config to make explicit sync work? I use a branch explicit-sync

**Comment by Honkazel** [comment]
> > nota bene we need testing there so feel free
> 
> what do i need to add to the hyprland config to make explicit sync work? I use a branch explicit-sync

Nothing
Works by default in explicit-sync branch
But if you want disable it, then set render:explicit_sync to 0 and restart
