### ISSUE TITLE
Submap With `movewindow` causes crash

### ISSUE THREAD

**Issue by treatybreaker** [hyprwm/Hyprland#486]
### Issue
Using a submap with a `movewindow` action causes `Hyprland` to crash.

#### Reproduction
1. Take the configuration from the **Relevant Configuration** section and place it into your Hyprland configuration.
2. Open a window (terminal, firefox, etc. doesn't matter)
3. Hit `SUPER+M`
4. Hit any arrow key (left, right, up down)

#### Expected Outcome
Window will move in direction pressed after activating the submap

#### Noted Outcome
Hyprland crashes

### Relevant configuration
```config
### Move Window ###
bind=SUPER,M,submap,move_window

submap=move_window
bind=,right,movewindow,r
bind=,left,movewindow,l
bind=,up,movewindow,u
bind=,down,movewindow,d

bind=,escape,submap,reset
submap=reset
```

### Attachments
[Hypr Log](https://github.com/hyprwm/Hyprland/files/9276183/hypr-crash.log)
[Core Dump](https://github.com/hyprwm/Hyprland/files/9276189/hypr-crash.txt)
[Full Configuration](https://github.com/hyprwm/Hyprland/files/9276194/hypr.tar.gz)

### Notes
- `uname -r` output: `5.18.16-arch1-1`
- Hyprland is installed via AUR as the `hyprland-git` package (`hyprland-git r1330.9564a4c-1`)

**Comment by vaxerski** [comment]
![Screenshot_20220807-084328_Root Explorer.jpg](https://user-images.githubusercontent.com/43317083/183278707-5f0469c7-02c9-419f-8cac-38a87258cad0.jpg)

is this a troll?
