### ISSUE TITLE
Maybe a notification daemon?

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#4860]
### Description

I mean, like whats stoping this team? u are the best i mean, swayidle and swaylock it was buggy as hell, just errors, crashes and freezes, but with the  newest packages of hypridle and hyprlock, its like its a entirely ecosystem, runs smooth, everything its like integrated. With that matter, what is stopping you ;) ? HyprNotify, as a notification daemon, which is simple, yet one of the best in the wayland world. Thank you

**Comment by vaxerski** [comment]
no such plans, you have ags and eww
