### ISSUE TITLE
Getting config values inside PLUGIN_INIT returns default values

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#4861]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit f7a34534873bf499fc1a04a5fa25ada03c4ee415 dirty (socket2: move to the wayland event loop).
Date: Mon Feb 26 18:20:51 2024
Tag: v0.35.0-103-gf7a34534

flags: (if any)


System Information:
System name: Linux
Node name: zjeffer
Release: 6.7.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q] [10de:24dd] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

This was fixed here: https://github.com/hyprwm/Hyprland/issues/2510#issuecomment-1628840030, but seems to not work anymore.

### How to reproduce

```cpp
HyprlandAPI::addConfigValue(PHANDLE, k_workspaceCount, Hyprlang::INT{10});

static auto* const workspaceCountPtr = (Hyprlang::INT* const*)HyprlandAPI::getConfigValue(PHANDLE, k_workspaceCount)->getDataStaticPtr();

int workspaceCount = **workspaceCountPtr;
```
`workspaceCount` is always 10 in `PLUGIN_INIT`, but if I add a `configReloaded` listener and call the same code inside the listener's callback, I get 5 (the value that is set in my config).

**Comment by vaxerski** [comment]
Yes that's the new expected behavior. Config reloading is deferred for after plugin_init

**Comment by zjeffer** [comment]
Is there no workaround? Because this means there's no way to initialize things based on user config values at boot.

**Comment by vaxerski** [comment]
https://github.com/DreamMaoMao/hycov/blob/7d48cff8364a7b6ae52a3472ad1dfe01b9f728ae/src/main.cpp#L39-L40

**Comment by zjeffer** [comment]
That works perfectly! Thanks!
