### ISSUE TITLE
Dim and blur effect of special workspace behaving strangely when vfr is enabled

### ISSUE THREAD

**Issue by Bruce0206** [hyprwm/Hyprland#4862]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: komputer
Release: 6.7.6-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:32:48 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When switching into the special workspace, the gradual dim and blur effects seem to only progress when something on the screen is moving (e.g. the mouse).  When I disable misc:vfr in the configuration, the effects occur normally.  

### How to reproduce

1. Enable misc:vfr
2. Set decoration:dim_special and decoration:blur:special
3. Disable animations
4. Switch into special workspace when nothing on the screen is moving
5. Move the mouse

**Comment by vaxerski** [comment]
can't repro. more info needed

**Comment by Bruce0206** [comment]
> can't repro. more info needed

Sorry, I forgot to include this.  Can you try it with animations disabled?

**Comment by vaxerski** [comment]
thanks, that did it.
