### ISSUE TITLE
Incorrect mouse position on refocus until moved

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#4868]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 94aeb06d6ba14d403c46b52d1d2e397acb5906a4 dirty (toplevelexport: set last damage for dmabuf copy).
Date: Thu Feb 22 04:10:01 2024
Tag: v0.35.0-69-g94aeb06d

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Mouse coordinates given to app are incorrect when a click is the first event it receives after being refocused. This is fixed the moment the mouse is moved again.

### How to reproduce

1. Open an Xwayland app for which the mouse position matters and which uses tooltips/subwindows
2. Get a tooltip to open
3. Click on the app
4. Observe that the position of that click is incorrect

### Crash reports, logs, images, videos

Tested with the Qt Xwayland app SideFX Houdini (free Apprentice trial), can likely make a demo app if needed.

You can see the connection goes way to the left first, until I move the mouse cursor.

https://github.com/hyprwm/Hyprland/assets/44881120/80929063-673b-41ec-a7f0-00b25e0ee2d1

**Comment by vaxerski** [comment]
demo app and I'll fix this

**Comment by TheSunCat** [comment]
Darn, this doesn't repro in the Qt app I just wrote to test. I've seen this happen in other X11 programs (Unreal Engine as well), will try to find an easy to download example.
Would it be possible to have a windowrule to send a spurious mouse movement event on focus? Would get around this bug I think.

**Comment by vaxerski** [comment]
a window rule here is pointless, this should be the behavior. IIRC we already do, thats why I want a test client xd

**Comment by TheSunCat** [comment]
I adapted the Qt "elasticnodes" example to show a tooltip (just `setToolTip("Hi :)");`) on the Node ctor, then ran it with the xcb QPA. I let the tooltip open, and clicked on a node without moving the mouse. This worked correctly, whereas it does not in any case within Houdini (nodes, 3D viewport, menus), which uses Qt (5).
Maybe I'm missing some special configuration Houdini does to Qt? Not sure.

Note that Houdini has a [trial](https://www.sidefx.com/products/houdini/), though I'd be happy to help debug on my end.

**Comment by TheSunCat** [comment]
This appears fixed since I opened the issue! May be thanks to the subsurface tree rewrite. Closing for now, will reopen if I encounter it again.
