### ISSUE TITLE
More warnings

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#487]
I think more warning would be useful for new users.
My list for what should be a warning but isnt so far:
- warning for invalid animation name done in https://github.com/hyprwm/Hyprland/commit/3a8dcf284aa3953585e3f700afa1095903c3a65f
- warning for invalid animation properties (negative or 0 for numbers) done in https://github.com/hyprwm/Hyprland/commit/3a8dcf284aa3953585e3f700afa1095903c3a65f
- warning for too many/few values in a bezier curve
- warning for invalid keyboard varient
- warning for invalid keyboard layout
- warning for invalid keyboard options
- the current warning for booleans (yes/no) options does not list the avilable options (cannot be done to to hyprlands codebase)

I will comment on here as I find more things that need warning

**Comment by pjalsGit** [comment]
invalid animation name/properties is an error?

**Comment by vaxerski** [comment]
most cases in which a warning is not reported arise because at the time of parsing the said keyword they cannot be checked for correctness.

Example: 
```
bind=mod,key,focusmonitor,IAMABADPERSON
```
The config parser doesn't know whether the monitor won't exist in the future.

some I can hack around some warnings though, fair.

**Comment by godalming123** [comment]
You could also add runtime warnings instead of just in the config manager I believe this is already done in the log files but I think it should be more clearly visible for warnings

**Comment by vaxerski** [comment]
some done in 3a8dcf284aa3953585e3f700afa1095903c3a65f

**Comment by vaxerski** [comment]
> the current warning for booleans (yes/no) options does not list the avilable options

booleans are not a separate data type. It's literally an int. I made them called "bool" in the wiki to avoid confusion and people setting bools to stuff like 31

**Comment by godalming123** [comment]
How does that stop you from listing available values in the error message

**Comment by vaxerski** [comment]
hyprland internally doesn't know which value is a bool. Either I can suggest both int and bool values, which could be confusing, or I can suggest none.

**Comment by godalming123** [comment]
ok

**Comment by vaxerski** [comment]
all done.
