### ISSUE TITLE
huge amounts of data being written into `.local/share/sddm/wayland-session.log` after each reload

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#4873]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 29cdd7de1f8d99462915540569fbe54f10f609f4 dirty (layers: minor fixes for new animations).
Date: Wed Feb 28 16:59:45 2024
Tag: v0.36.0-4-g29cdd7de

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.7.6-zen1-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 24 Feb 2024 04:03:29 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

My home folder was full. After investigating, I had a 37GB file in `~/.local/share/sddm/wayland-session.log`. Not sure if this is an issue with sddm or hyprland, but it does appear to increase in size after each `hyprctl reload`. (tried to run it once to see how much per reload, it was ~10KB, but it is now going up QUICKLY

got from 100MB to 3 GB in a few seconds, I've now deleted it. 

### How to reproduce

Unsure if `hyprctl reload` is the culprit, after starting the session it did only appear to go up after each run.

### Crash reports, logs, images, videos

After 1 reload (8 -> 28 KiB)

[wayland-session.log-1.txt](https://github.com/hyprwm/Hyprland/files/14438225/wayland-session.log-1.txt)

After 2 reloads (28 -> started going up by itself, idk, 640MB when I stopped it after a couple of seconds)

[wayland-session.log-2.txt.gz](https://github.com/hyprwm/Hyprland/files/14438242/wayland-session.log-2.txt.gz)

**Comment by vaxerski** [comment]
what does it write there, tho? Looks like an sddm issue

**Comment by alba4k** [comment]
Yeah sorry, had to restart the session to upload that, as I had already deleted it (for obvious reasons)

**Comment by alba4k** [comment]
Ok it does appear to increase by 20 KB per reload (7.8, 28, 48, 69, 89, ...) and then at some point blow up and start increasing at ~100MB per second

**Comment by alba4k** [comment]
Looking into it, it appears to be because of lxpolkit.

Interestingly, removing the exec line and starting it manually will still cause this issue. Also, the logs still keep growing after I kill the process. Don't really know how polkit stuff works tho

Unrelated, but do you have any idea what might be causing these xkbcomp warnings?
```
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
```

**Comment by vaxerski** [comment]
no clue wrt either. Not a hyprland issue tho, it seems
