### ISSUE TITLE
Weird screen flickering/blurring on login

### ISSUE THREAD

**Issue by waddyhussain** [hyprwm/Hyprland#4875]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit 097f561e41e5660333492c1f188199e837742efe dirty (surfacetree: Revert subsurfaceTree: assign surfaces to a CWLSurface).
Date: Wed Feb 28 19:42:04 2024
Tag: v0.36.0-7-g097f561e

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.7.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000


GPU information: 
26:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070 Ti] [10de:1b82] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

After upgrading to the latest version, my displays get a weird flickering blur effect when I first login. Any movement stops the blurring in that area.

Video:

https://github.com/hyprwm/Hyprland/assets/41598382/d9a39cd3-c210-4eea-98d0-7c6fe08bdad4

### How to reproduce

Start Hyprland session, cursor will be flickering until moved (not sure what other factors are causing it e.g Nvidia)

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14439534/hyprland.log)

**Comment by vaxerski** [comment]
heh
[patch.txt](https://github.com/hyprwm/Hyprland/files/14440297/patch.txt)
try this

**Comment by waddyhussain** [comment]
Still getting it :/

These are the steps I did to apply the patch
```sh
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland/
patch -p1 < ~/Downloads/patch.txt
make all && sudo make install
```
Didn't seem to be any errors from the command outputs

Lmk if you need logs from running the patched version or anything

**Comment by vaxerski** [comment]
make sure no duplicate binaries exist on your system :P `whereis Hyprland`

**Comment by waddyhussain** [comment]
Yeah I checked with `which` to make sure it was using the `/usr/local/bin` one, but I just deleted the other binaries now to be sure and it's still happening

Also I noticed that connecting another display after log in stops the flickering as well (look for when DP-3 added):
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14450901/hyprland.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14451301/patch.txt)
try this

**Comment by waddyhussain** [comment]
Yep fixed it ;)

There's still blur at the beginning but I think that's just from the zoom out effect

https://github.com/hyprwm/Hyprland/assets/41598382/96c0aaff-ad08-4557-aa81-1e050ce7545d
