### ISSUE TITLE
 Hyprland crashes when opening any app ,switching workspaces a few times, or just running for a few seconds.

### ISSUE THREAD

**Issue by DoctorPatita** [hyprwm/Hyprland#4879]
### Hyprland Version

can't use _hyprctl systeminfo_ or any command while Hyprland is running.

### Bug or Regression?

Regression

### Description

Did "pacman -Syu" and now Hyprland crashes when opening any app or switching workspaces a few times, tell me if you need more info, I'm a newbie in Hyprland and Arch, someone in the Hyprland discord told me "graphics drivers giving up", how do i fix this?

### How to reproduce

Don't know

### Crash reports, logs, images, videos

[hyprlandCrashReport1141.txt](https://github.com/hyprwm/Hyprland/files/14441158/hyprlandCrashReport1141.txt)

**Comment by vaxerski** [comment]
it looks like your gpu driver giving up.

However, since you say it's a regression, please `git bisect` it.

**Comment by DoctorPatita** [comment]
.

**Comment by DoctorPatita** [comment]
Closing issue
