### ISSUE TITLE
Hyprland not working with nvidia drivers 550

### ISSUE THREAD

**Issue by Sheryna1** [hyprwm/Hyprland#4880]
### Hyprland Version

Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.7.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28a1] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

### Bug or Regression?

Bug

### Description

After updating nvidia drivers using "yay" package manager and rebooting PC, Hyprland suddenly stopped working.  After reinstalling the older drivers from cache everything worked just fine.

P.s. I'm actually a noobie in writing Bug Reports so, please, don't be angry if something was wrong in my report.

### How to reproduce

Install the newest nvidia drivers using yay package manager

### Crash reports, logs, images, videos

[hyprlandCrashReport848.txt](https://github.com/hyprwm/Hyprland/files/14442000/hyprlandCrashReport848.txt)

**Comment by vaxerski** [comment]
firstly, you're on a very old version.

Secondly, what do you want me to do? Go and nuke nvidia's hq? I can't do anything about closed-source drivers.
