### ISSUE TITLE
Can not move window to other special workspace

### ISSUE THREAD

**Issue by Asthestarsfalll** [hyprwm/Hyprland#4884]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: czh-81tc
Release: 5.5.13-1-mbp
Version: #1 SMP PREEMPT Wed, 15 Apr 2020 00:54:47 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The window only can be moved to default special workspace. My keybindings:

### How to reproduce

```conf
# Special workspaces (scratchpad)
bind = $mainMod SHIFT, SPACE, movetoworkspacesilent, special
bind = $mainMod, SPACE, togglespecialworkspace

bind = $mainMod SHIFT, E, movetoworkspacesilent, wechat
bind = $mainMod, E, togglespecialworkspace, wechat
bind = $mainMod CONTROL, E, exec, wechat-uos

bind = $mainMod SHIFT, W, movetoworkspacesilent, qq
bind = $mainMod, W, togglespecialworkspace, qq
bind = $mainMod CONTROL, W, exec, linuxqq
```
Using `Mod Shift Space` will move window to default special workspce. But `Mod Shift W` cannot.

**Comment by vaxerski** [comment]
qq is not a special workspace, it moved it to a named workspace called `qq`. https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces

**Comment by Asthestarsfalll** [comment]
@vaxerski Thank you for your reply. According to the documents:
> You can define multiple named special workspaces, but the amount of those is limited to 97 at a time.

Does it mean that I can define multiple special workspace but cannot move to them expect for the default special workspace? 
Using `bind = $mainMod, W, togglespecialworkspace, qq` indeed toggle a new special workspace. How can I move window to it?

**Comment by Asthestarsfalll** [comment]
For those who may have same question. To move window to user-defined special workspace, you can use
```
bind = $mainMod SHIFT, Q, movetoworkspacesilent, special:qq
bind = $mainMod, Q, togglespecialworkspace, qq
```
