### ISSUE TITLE
Custom configuration location

### ISSUE THREAD

**Issue by LelouBil** [hyprwm/Hyprland#4898]
### Description

I would like to tell Hyprland to use a custom configuration file (other than $XDG_CONFIG_HOME/.config/hypr/hyprland.conf), either with an environment variable or a CLI argument.

I looked around in the documentation and in the code, and I don't think that's possible.

I also think it would not be a difficult feature to implement. (I could try to do a PR if a maintainer doesn't have the time)

**Comment by vaxerski** [comment]
you surely did
![image](https://github.com/hyprwm/Hyprland/assets/43317083/3352abba-09cb-48a7-8c7a-3abcacfabf43)

**Comment by LelouBil** [comment]
Whoops, sorry. I added a PR to the wiki here https://github.com/hyprwm/hyprland-wiki/pull/495
I think that's the most likely place people will search for this.
