### ISSUE TITLE
[Gestures] when swiping applications briefly show up on incorrect monitor

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyprwm/Hyprland#490]
https://user-images.githubusercontent.com/29136904/183315932-8628ff4f-d4e6-45e3-be1f-8cd74a5e6374.mp4

In the above video I am recording the first monitor and swiping between workspaces on the other.

You can also see the active border when in fullscreen bleeds into the other monitor as well.

**Comment by vaxerski** [comment]
what the foq, that's really weird.

**Comment by vaxerski** [comment]
I am guessing this does NOT happen with the workspace `slide` style animations?

**Comment by ChristianChiarulli** [comment]
depends which way the program slides from, if I slide from the direction of the other monitor, then it passes through that monitor first.

**Comment by vaxerski** [comment]
so, is workspace anim slide bugged exactly like swiping then or not? yes/no. Sorry, I am not Shakespeare, I need clear information.

**Comment by ChristianChiarulli** [comment]
yes, but like I said it depends on which way you slide the window from.

**Comment by vaxerski** [comment]
ok thank you

**Comment by spikespaz** [comment]
Would it help if each monitor could have its own set of workspaces independently?

**Comment by vaxerski** [comment]
Just tested with my laptop, is this still a thing? Doesn't happen to me
