### ISSUE TITLE
Damage tracking issues in GTK3 combo box

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#4900]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1698d336f2511ee7c93d0a520c7ba3491c831e8d dirty (core: fix crashes on access of deleted wlr_ surface).
Date: Thu Feb 29 18:23:44 2024
Tag: v0.36.0-16-g1698d336

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

There is inconsistent damage tracking on GTK3 combo boxes. This is reproducible with `pavucontrol`. Note that I am using fractional scaling.

### How to reproduce

Open a combo box in pavucontrol.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/44881120/231838a6-b0d9-4ca5-aefd-2804e7a9d389

Note how 4s in the shadow is also partially left over.

**Comment by vaxerski** [comment]
fuck right, also without scaling.

**Comment by TheSunCat** [comment]
Well hey I've been able to close a ton of bugs I previously had open. It's a really good net positive :)

**Comment by vaxerski** [comment]
https://www.youtube.com/watch?v=zNOenjbBA-E

**Comment by TheSunCat** [comment]
Beautiful. No need to fix the issue anymore.
