### ISSUE TITLE
`resolve_binds_by_sym` input option does not seem to change behavior

### ISSUE THREAD

**Issue by AntoineGuilminCrepon** [hyprwm/Hyprland#4908]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0

flags: (if any)


System Information:
System name: Linux
Node name: mistral
Release: 6.7.6-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Feb 2024 19:08:51 +0000


GPU information:
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I use two different keyboards on Hyprland (namely `fr,us`), and I tried the new `resolve_binds_by_sym` option from the latest release. However, this option does not change my keybinds in regard to my current keyboard.

### How to reproduce

1. create a keybind (e.g SUPER SHIFT + Q for killactive)
2. set input with `fr, us` without `resolve_binds_by_sym`
3. the keybind is triggered by the same combination in both keyboards (e.g leftmost key of second row)
4. set input with `fr, us` WITH `resolve_binds_by_sym`
5. the keybind is triggered by the same combination in both keyboards (e.g leftmost key of second row)

Expected behavior:
 At step 5, the keybind is triggered by different key combination (e.g leftmost key of second row in AZERTY, leftmost key of first row in QWERTY)

**Comment by AntoineGuilminCrepon** [comment]
If I am not mistaken, this option was specifically created for multi-layout configuration, so that the binds are changed according to the layout.

That is what is said in the wiki, and also what I could guess from the PR https://github.com/hyprwm/Hyprland/pull/4851 that added this (disclaimer: I don't know much C++, but I could kinda guess what it does, I may be mistaken).

**Comment by vaxerski** [comment]
no the thing is you need to set the layout per-device for htis to work

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14465417/patch.txt)
try this

**Comment by vaxerski** [comment]
oops - that won't compile. This: 
[patch.txt](https://github.com/hyprwm/Hyprland/files/14465430/patch.txt)
