### ISSUE TITLE
hyprctl instances give an error, if /tmp/hypr/hyprland-share-picker.conf is exist

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#4916]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 555afea73c87f8e2bb374d1112431bb3a6f451dd  ().
Date: 2024-03-01
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: theseus
Release: 6.7.6
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 23 08:51:59 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240229.1536926"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hycov by DreamMaoMao ver 0.3
```

</details>

### Bug or Regression?

Bug

### Description

`hyprctl instances` fail if the file `/tmp/hypr/hyprland-share-picker.conf` exists. Removing the file fixes the problem.
```
❱ hyprctl instances
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoull
Aborted (core dumped)
```

Releated to https://github.com/hyprwm/Hyprland/issues/4825 , deletion of file fixes this

### How to reproduce

1) Have an OBS or similar screen sharing tool, on first launch or while selecting source it will create `/tmp/hypr/hyprland-share-picker.conf` file
2) Try to `hyprctl instances` when file exist
3) Get error:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoull
Aborted (core dumped)
```
4) Delete `/tmp/hypr/hyprland-share-picker.conf`
5) No more errors until OBS opened again and file created

**Comment by vaxerski** [comment]
I am pretty sure I fixed that a while back. Are you sure your hyprctl also comes from the latest commit?

**Comment by Ligthiago** [comment]
```
❱ whereis hyprctl
hyprctl: /nix/store/3pnr5abyn137wgmd7zwvxfg0v6kfrssc-home-manager-path/bin/hyprctl /nix/store/1zmxd8w7xx5bxbsbyy5k2pwhkpk5rj2a-system-path/bin/hyprctl
```

`/nix/store/1zmxd8w7xx5bxbsbyy5k2pwhkpk5rj2a-system-path/bin/hyprctl ` is a symlink to `/nix/store/8jiv0gz5a4arz5i7p1hcf2sqcj8lr5r9-hyprland-0.36.0+date=2024-03-01_555afea/bin/hyprctl` and as you can see by `555afea` it comes from 555afea73c87f8e2bb374d1112431bb3a6f451dd , same as my Hyprland version

**Comment by vaxerski** [comment]
odd
