### ISSUE TITLE
floating dimensions for foot 

### ISSUE THREAD

**Issue by AERDU** [hyprwm/Hyprland#4918]
### Hyprland Version

Hyprland, built from branch makepkg at commit 7ce781e87cf7cf789a54d37af7d78f1c11d66dbc dirty (keybinds: better follow xkb translation state).
Date: Sat Mar 2 02:46:55 2024
Tag: v0.36.0-25-g7ce781e8

flags: (if any)

System Information:
System name: Linux
Node name: machine
Release: 6.7.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000

GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Regression

### Description

f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0 causes some floating windows to launch with really weird aspect ratios, so far I've only had this issue with foot and abaddon. Was also an issue with firefox's filepicker/prompts before 1e7eb3a5a5419f97b61a3403880b161c85dd7b17. 

### How to reproduce

Launch foot with ```hyprctl dispatch exec [float]foot```.
It's the most obvious when there's two tiled windows (horizontally), and then a floating window launched on top of them.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/30103360/fdbcbe94-126f-4a99-afc2-ed2a843df84f

**Comment by bvr-yr** [comment]
yeah.. in current stance foot is a mess

the only way i found to make it work is set explicit size and pos with `windowrulev2`

somewhere in-between 097f561e41e5660333492c1f188199e837742efe and 8811f4b69ade469285635c539f20194d717c8e17 (i can bisect if really needed) `center` rule had stopped working, it moves top-left corner to center

so what i do now: launch foot with `--title=foot-float` and match with rules
```ini
windowrulev2 = float,class:^(foot)$,title:(-float)$
windowrulev2 = size [X] [Y],class:^(foot)$,title:(-float)$
windowrulev2 = move [X] [Y],class:^(foot)$,title:(-float)$
```

interesting that `initialTitle` doesn't match, despite `activewindow` dispatcher correctly reports foot-float

**Comment by bvr-yr** [comment]
but why close? it is only a workaround
and given multiple monitors with different resolutions requires a script to set uniq title to match with explicit size and pos to get it centered

does it mean it won't be fixed? maybe there is a point to create issue upstream?

**Comment by vaxerski** [comment]
ahem ahem 
![image](https://github.com/hyprwm/Hyprland/assets/43317083/2b5005cb-23d4-4c07-bc73-3c06076cd733)

**Comment by bvr-yr** [comment]
jesus.. happens :D

https://github.com/hyprwm/Hyprland/assets/130279855/137087d4-68a4-4835-9ac3-1841919ef279
