### ISSUE TITLE
This happens when i try to build Hyprland

### ISSUE THREAD

**Issue by itaysharir** [hyprwm/Hyprland#492]
https://user-images.githubusercontent.com/87126382/183410544-84a5c731-2440-4e36-83ec-a67bbbe02e7a.mp4

Am i doing something wrong? i tried to run make install with sudo but the same thing happend.

Thanks in advance!

**Comment by fufexan** [comment]
`wayland-server` found: NO.

So install that, then try again.

**Comment by itaysharir** [comment]
I know it's a stupid question but how? I use debian and i tried "sudo apt install wayland-server", it didn't work. i googled it but i didn't find anything.

**Comment by viperML** [comment]
Probably you won't even be able to compile it on debian, as the wayland version they use is too old

**Comment by viperML** [comment]
You might want to search for whatever package provides `wayland-server.pc`, required by pkg-config

**Comment by itaysharir** [comment]
Can i install wayland-server on fedora 34? if i'll get it to build on fedora i will have no problem with that

**Comment by itaysharir** [comment]
I searched for it in the copr website and was unable to find it. So sorry to bother but can anyone send me a link?

**Comment by viperML** [comment]
https://github.com/hyprwm/Hyprland/wiki/Installation#fedora

**Comment by itaysharir** [comment]
That's what i also did on Fedora, got the same error

**Comment by viperML** [comment]
Then open an issue in their repo

**Comment by itaysharir** [comment]
I dont think it's an issue with fedora tho
