### ISSUE TITLE
Hyprland on arm64

### ISSUE THREAD

**Issue by itaysharir** [hyprwm/Hyprland#493]
I have an M1 mac and i want to install Hyprland in a arm64 Fedora VM. I researched a lot, i thought i couldn't install Hyprland for some other reason but then i came to the conclusion that Hyprland doesn't support arm64.

Is there any way to maybe force Hyprland to run on arm64? Thanks

**Comment by viperML** [comment]
You can build the NixOS package perfectly fine for arm64. A different problem is that fedora is not supported.

```console
$ git diff
diff --git a/flake.nix b/flake.nix
index 4cb7c64..bbc7d3f 100644
--- a/flake.nix
+++ b/flake.nix
@@ -18,6 +18,7 @@
     genSystems = lib.genAttrs [
       # Add more systems if they are supported
       "x86_64-linux"
+      "aarch64-linux"
     ];
     pkgsFor = nixpkgs.legacyPackages;
     mkDate = longDate: (lib.concatStringsSep "-" [

$ nix build .#packages.aarch64-linux.hyprland -L
warning: Git tree '/home/ayats/Downloads/Hyprland' is dirty

$ file ./result/bin/Hyprland
./result/bin/Hyprland: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /nix/store/il2mpl6qjc4aa42mbiy3p3wicm3d6nz5-glibc-2.35-163/lib/ld-linux-aarch64.so.1, for GNU/Linux 2.6.32, not stripped
```

**Comment by itaysharir** [comment]
Oh, I'll try installing NixOS then. Where can i download a generic iso?

**Comment by fufexan** [comment]
For aarch64 you may want to grab it from [here](https://releases.nixos.org/nixos/unstable/nixos-22.11pre398503.4bdf4169ad2).

**Comment by viperML** [comment]
I don't know if there are iso's for unstable aarch64. Otherwise you can install unstable nixos from the stable (22.05) iso

**Comment by itaysharir** [comment]
sorry to bother but is there an installer version for arm?

**Comment by fufexan** [comment]
I linked it. `aarch64 == arm64`. The latter is just apple naming.

**Comment by itaysharir** [comment]
I know, but for x86-64 there is a version that ships with a GUI. Is there something like that for arm?

**Comment by fufexan** [comment]
No.

**Comment by itaysharir** [comment]
I tried NixOS and i think it's just not for me. Is there any way to force it on arm with fedora? Maybe installing it manually without copr or the building script?

**Comment by fufexan** [comment]
Install it using Nix then.

**Comment by itaysharir** [comment]
How?

**Comment by vaxerski** [comment]
by compiling with an aarch64 compiler, duh. Like gcc, for aarch64: https://archlinux.org/packages/community/x86_64/aarch64-linux-gnu-gcc/

**Comment by itaysharir** [comment]
Sorry for me being a newbie but should i just cd into the Hyprland repo and run gcc? on what file? I just don't know...

**Comment by vaxerski** [comment]
everything is in the wiki. For setting a custom compiler you can use the CC and CXX envvars with CMake. Meson - dunno.

**Comment by itaysharir** [comment]
I just don't understand... I tried "sudo make install" and this is was the output
![Screen Shot 2022-08-08 at 22 27 12](https://user-images.githubusercontent.com/87126382/183498624-469ea211-93b0-4d31-93de-a5c55dfb7648.jpg)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/183500017-aba9709b-3996-481c-b24e-6f0233ae5b31.png)

oh no totally not like meson tells you what is wrong...

**Comment by itaysharir** [comment]
I tried to install it with dnf, i tired to google it, i obviously enabled wayland in fedora, what should i do?

**Comment by vaxerski** [comment]
install the dependency...

**Comment by itaysharir** [comment]
I said i tried to install the package wayland-server with dnf, i tried to find stuff on google about, and i found nothing

**Comment by vaxerski** [comment]
wow that was really hard to find then I guess, no clue how I did it in 12s:
https://fedora.pkgs.org/36/fedora-aarch64/libwayland-server-1.20.0-4.fc36.aarch64.rpm.html

The official fedora package is too old though, you'll have to wait for 1.21 to land in fedora's repos or compile wayland-server manually.

**Comment by itaysharir** [comment]
Also, the Hyprland install guide tells you all the dependencies you need to install on fedora. I installed all of them but still, this happens

**Comment by vaxerski** [comment]
you did not...

https://github.com/hyprwm/Hyprland/discussions/284#discussioncomment-3075455

**Comment by itaysharir** [comment]
What am i not understanding here, it says libwayland-server is already installed, i installed all the dependencies from the comments on your last comment (all of them were already installed accept one) and i still get the same error. I mostly don't understand how libserver-wayland is already installed.

**Comment by vaxerski** [comment]
don't ask me - I am not the maintainer of your system, and I have never used fedora.

**Comment by itaysharir** [comment]
> Install it using Nix then.

i did a "nix-env -i hyprland"
![Screen Shot 2022-08-09 at 0 12 14](https://user-images.githubusercontent.com/87126382/183515556-a2414a1d-1e08-45b9-a56b-127ce92855c3.jpg)

**Comment by fufexan** [comment]
That's the nixpkgs version. Don't use that.

**Comment by itaysharir** [comment]
What version should i install then? Should i put the the stuff from [here](https://github.com/hyprwm/Hyprland/wiki/Nix) in configuration.nix? If so, where should i put the configuration.nix file on fedora?

**Comment by fufexan** [comment]
You're using Nix, not NixOS, so no `configuration.nix` for you. Start using [flakes](https://nixos.wiki/wiki/Flakes) though, and then
 `nix profile install github:hyprwm/hyprland`.

**Comment by itaysharir** [comment]
I understand what are flakes, I didn't understand where should i put these flakes. There is a flake.nix file in the repo, should i do something with it?

**Comment by fufexan** [comment]
Run the last command I wrote. Nix will figure out what to do. You don't need to clone or anything.

**Comment by eli-schwartz** [comment]
> wow that was really hard to find then I guess, no clue how I did it in 12s:
> https://fedora.pkgs.org/36/fedora-aarch64/libwayland-server-1.20.0-4.fc36.aarch64.rpm.html

I regret to inform you that those 12s told you the wrong thing. :) It turns out that this is indeed hard. (Or at least not trivial.)

Fedora is a distro that uses "split" development packages, so they have packages for libraries which contain just the library, no headers and no pkg-config dependency files. In theory this is supposed to be incredibly useful for users, because they save 15kb of disk space due to not needing to install files that aren't needed for booting into a desktop (only needed for compiling programs).

@itaysharir

The general solution here is to figure out the file you need -- for a pkg-config dependency "wayland-server" this will be `wayland-server.pc`.

Then run this command to look up what package provides it:

```
dnf provides "*filename"

# or in this case
dnf provides "*wayland-server.pc"
```

In this case it will turn out to be https://fedora.pkgs.org/36/fedora-updates-testing-aarch64/wayland-devel-1.20.0-4.fc36.aarch64.rpm.html

So install wayland-devel (development packages on Fedora are usually named "*-devel") and the dependency should be found.

**Comment by vaxerski** [comment]
god damn it fedora

**Comment by viperML** [comment]
We already told them https://github.com/hyprwm/Hyprland/issues/492#issuecomment-1208067026

**Comment by itaysharir** [comment]
> Run the last command I wrote. Nix will figure out what to do. You don't need to clone or anything.

it says it's an experimental fetaure

**Comment by itaysharir** [comment]
> So install wayland-devel (development packages on Fedora are usually named "*-devel") and the dependency should be found.

It says the dependency is found but i need a newer version

**Comment by fufexan** [comment]
> it says it's an experimental fetaure

Yeah, so run it with `--experimental-features 'flakes nix-command'`, or put those options in `nix.conf`.

**Comment by fufexan** [comment]
`nix profile install github:hyprwm/hyprland --experimental-features 'flakes nix-command'`
You'll also need to use [nixGL](https://github.com/guibou/nixGL) since Nix can't figure out where your graphics drivers are otherwise.

**Comment by itaysharir** [comment]
Ohh sorry i didn't realize you had to literally write 'flakes nix-command' and not just put the actual command there.
![Screen Shot 2022-08-09 at 13 15 08](https://user-images.githubusercontent.com/87126382/183624395-bd83437f-6e50-4af0-874f-146d40d147d3.jpg)

Anyways,

**Comment by fufexan** [comment]
Ah yeah, one sec I'll add `aarch64-linux` as a supported platform.

**Comment by fufexan** [comment]
Now try the previous command plus the flag `--refresh`.

**Comment by itaysharir** [comment]
IT WORKED! I just don't see Hyprland in my login manager

**Comment by itaysharir** [comment]
I don't see it in SDDM but the instalation guide said it's supported

**Comment by itaysharir** [comment]
I ended up going into a tty and i ran Hyprland as the guide sai
![Screen Shot 2022-08-09 at 13 43 34](https://user-images.githubusercontent.com/87126382/183629467-0210fd86-0ea0-450d-8991-2d4dbab7b0a0.jpg)
d

**Comment by fufexan** [comment]
Did you read the part about nixGL I wrote earlier?

**Comment by itaysharir** [comment]
Oh i forgot. I'm installing it and it tells me to use nix profile instead of nix-env, but when i do it doesn't recognize the -iA flag

**Comment by fufexan** [comment]
`nix profile` doesn't use `-iA`. The equivalent of that is `install flake#package`, which would be `install github:guibou/nixGL` here, since you can leave out defaults.

**Comment by itaysharir** [comment]
![Screen Shot 2022-08-09 at 14 43 18](https://user-images.githubusercontent.com/87126382/183639037-c67f4af1-bf50-4aa7-8241-abd73663155c.jpg)

Should i ignore it?

**Comment by fufexan** [comment]
Yes, append the flag it tells you.

**Comment by itaysharir** [comment]
![Screen Shot 2022-08-09 at 14 51 25](https://user-images.githubusercontent.com/87126382/183640427-c9458628-71a6-4ba9-907d-5eca4cb2b6d4.jpg)
I don't think it supports arm64

**Comment by fufexan** [comment]
I compiled an arm64 Hyprland appimage. Will post shortly so you can test. If it works I'll add building appimages to CI.

**Comment by itaysharir** [comment]
I rarely use appimages but i downloaded it, made it an executable and ran it and nothing happend

**Comment by itaysharir** [comment]
Ok i ran in the terminal exec and then the path to the appimage and it printed the same text as the message i replied to, the it crashed

> I ended up going into a tty and i ran Hyprland as the guide sai
> ![Screen Shot 2022-08-09 at 13 43 34](https://user-images.githubusercontent.com/87126382/183629467-0210fd86-0ea0-450d-8991-2d4dbab7b0a0.jpg)

**Comment by fufexan** [comment]
No idea then.

**Comment by itaysharir** [comment]
> ![Screen Shot 2022-08-09 at 14 51 25](https://user-images.githubusercontent.com/87126382/183640427-c9458628-71a6-4ba9-907d-5eca4cb2b6d4.jpg)
> I don't think it supports arm64

So there is nothing i can do about this?

**Comment by fufexan** [comment]
Just saw you opened an issue there. I'd say wait for the owner to reply.

**Comment by itaysharir** [comment]
So sorry to bother you again but i got it to display a different error! This time on debian, with the appimage.
![Screen Shot 2022-08-10 at 1 18 37](https://user-images.githubusercontent.com/87126382/183878541-7bd6e8b0-ead5-4851-869c-bd50a70835e1.jpg)

**Comment by viperML** [comment]
Why don't you just use Arch or NixOS? We won't be able to provide much support for a OS that we don't use, let alone care about

**Comment by itaysharir** [comment]
Well, i can but the VM software i use doesn't officially support arch so i will have no audio and some things won't work
