### ISSUE TITLE
Windows no longer open in the center of the screen with 'center' rule

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#4934]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
❱ hyprctl systeminfo
Hyprland, built from branch  at commit d72ea5f2a7fdb0d0a7bf914412327195b05199b0  ().
Date: 2024-03-02
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: theseus
Release: 6.7.6
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 23 08:51:59 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240229.1536926"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

After the last update, windows no longer open in the center of the screen with `windowrule=center,^(window_class)$`. Not sure what is causing the problem, everything worked fine yesterday with the same config. Works fine on 555afea73c87f8e2bb374d1112431bb3a6f451dd

### How to reproduce

1) Set `windowrule=center,^(windows_class)$`
2) Open it

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/142721811/c6a697b8-0268-44d9-bfb2-46e40c75dab8

**Comment by vaxerski** [comment]
I AM THE SEMI TRUCK
