### ISSUE TITLE
Hypridle inhibitor maybe ?

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#4938]
### Description

the hypridle its new and its amazing, but would be cool to have an inhibitor for it, when we play songs with spotify, or just to click a button on waybar, and hypridle its sleeping, and presing again its back with idle management. Idk my opinion, i mean there is swayidle inhibit, but ig it will not work with hypridle.

**Comment by justinesmithies** [comment]
I just made an [idleinhibit](https://git.sr.ht/~justinesmithies/dotfiles/tree/master/item/.config/eww/scripts/idleinhibit.sh) script that is run when I click on the bar or I can bind it to a keypress. So that might help you @mooncoffee1 ?

**Comment by vaxerski** [comment]
killall hypridle?

**Comment by renxzen** [comment]
sway-audio-idle-inhibit works for me with hyprland + hypridle
