### ISSUE TITLE
IME sometimes breaks.

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#494]
Only happens in apps that have native wayland support.
Using fcitx5

# Reproduction steps
Select only Keyboard-US-colemak in config
![image](https://user-images.githubusercontent.com/68589851/183446810-30ab9b58-18bf-4535-876d-09317fbbe37b.png)
select the variant colemak then apply.
Open a wayland native app(such as kitty, foot), type something in it, and you will notice the layout doesn't switch to colemak(typing `j` on your keyboard should result in the output of `n`)
Tada, you have broke your hyprland IME.
Funny thing is, no go back to any xwayland applications, the input method is also broken too.

# relevant files
The logs is full of spam that seems to be caused by unable to focus on the `fcitx5-configtool`, so it's kinda hard to read
ttps://0x0.st/o2sD.log

**Comment by KyleUltimate** [comment]
Updated logs that are easier to read. Things I did in this seesion
Type in chromium, confirms that it does work.
Open foot, breaks it.
https://0x0.st/o2s5.log

**Comment by KyleUltimate** [comment]
FYI, this is the profile in `~/.config/fcitx5`
![image](https://user-images.githubusercontent.com/68589851/183449600-bf1b65d7-b364-4964-9cae-7d91da41fe2c.png)

**Comment by vaxerski** [comment]
show me your config (hyprland)

**Comment by vaxerski** [comment]
why not set colemak/whatever in the config for your keeb?

**Comment by KyleUltimate** [comment]
Well, because my main input method is rime, which it works on top of the xcb layout(technically this isn't a bug, but it's very annoying)
So if I set it as colemak in it, everything I type in rime is completely messed up

**Comment by vaxerski** [comment]
found the most likely culprit.

**Comment by vaxerski** [comment]
please check with 6565c31dbfb590c9173a192f4f26e6ea5c787375

**Comment by KyleUltimate** [comment]
Oh hell yeah it's fixed.
Thanks so much!
