### ISSUE TITLE
'animate_manual_resize' is not considered in master layout. In dwindle layout it works as expected.

### ISSUE THREAD

**Issue by schieni** [hyprwm/Hyprland#4940]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit cc94123fa7d45e816327b4b8c8592589313f4718 dirty (renderer: minor fixes to transformations).
Date: Sun Mar 3 03:18:06 2024
Tag: v0.36.0-39-gcc94123f

flags: (if any)


System Information:
System name: Linux
Node name: workstation
Release: 6.7.6-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Feb 2024 19:08:51 +0000


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

I'm an old man, so I don't like hectic movements anymore :-), thus my animations take a bit longer and with my personal bezier curve it is also more difficult to handle.

It looks like 'animate_manual_resize' is not considered in the master layout, neither for keyboard nor mouse window resizing.

**In the dwindle layout it works as expected.**

Greetings fom Wuppertal, Germany.

### How to reproduce

Set or unset (true or false) the 'animate_manual_resizes' keyword in the misc section.

### Crash reports, logs, images, videos

**Bug in master layout:**

https://github.com/hyprwm/Hyprland/assets/49512667/f26eda98-ddea-4417-959c-c5daf21a6744

**In dwindle layout it works fine and fast:**

https://github.com/hyprwm/Hyprland/assets/49512667/c8511cf0-5719-4955-b423-5922a5b241c8

**Comment by Aqa-Ib** [comment]
That does not happen to me. Can you post you hyprland configuration file please ?

**Comment by Aqa-Ib** [comment]
I can reproduce on my end too.

**Comment by schieni** [comment]
> I see whats going on. missing a * after the hyprlang migration lol

Build hyprland with your patch, seems to work.

Thanks!
