### ISSUE TITLE
multiple layouts on devices after commit  "[7ce781e87cf7cf789a54d37af7d78f1c11d66dbc] keybinds: better follow xkb translation state" causes Hyprland to crash on startup

### ISSUE THREAD

**Issue by Evangelospro** [hyprwm/Hyprland#4941]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit b2c34404777ea0850f90f4c38f64484f03599d14 dirty (animations: Refactor AnimatedVariable (4911)).
Date: Sat Mar 2 02:35:17 2024
Tag: v0.36.0-24-gb2c3440

flags: (if any)


System Information:
System name: Linux
Node name: ELARCH-F15
Release: 6.7.4-arch1-1.1-g14
Version: #1 SMP PREEMPT_DYNAMIC Wed, 07 Feb 2024 13:01:49 +0000


GPU information:
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT1 [UHD Graphics] [8086:46a3] (rev 0c) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

Hyprland crashes on startup when devices have multiple layouts configured,

I have git bisected and first bad commit is 7ce781e87cf7cf789a54d37af7d78f1c11d66dbc which has to do with xkb translation state, so something must have happened there

### How to reproduce

Have multiple layouts on devices like:
device {
    name = at-translated-set-2-keyboard
    kb_layout = us,gr # here having both the layouts causes the crash while having just  1 works
    kb_variant = qwerty
    kb_options = grp:alt_shift_toggle,caps:escape
    numlock_by_default=true
}

### Crash reports, logs, images, videos

[hyprlandCrashReport7786.txt](https://github.com/hyprwm/Hyprland/files/14472744/hyprlandCrashReport7786.txt)

**Comment by vaxerski** [comment]
segmentation fault (core dumped)
