### ISSUE TITLE
Size prediction mess and not remembering floating size

### ISSUE THREAD

**Issue by bvr-yr** [hyprwm/Hyprland#4948]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit cc94123fa7d45e816327b4b8c8592589313f4718 dirty (renderer: minor fixes to transformations).
Date: Sun Mar 3 05:18:06 2024
Tag: v0.36.0-39-gcc94123f

flags: (if any)


System Information:
System name: Linux
Node name: Arch-ASUS
Release: 6.6.20-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 07:25:31 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Since f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0 things gone mad

how gtk and qt things looks on sway(-git)?:
- launch app tiled
- set float
- change float size
- close
- it get saved

or set kinda rule to launch floating:
- change float size
- close
- it get saved

next time you launch and toggle, or launch floated it got saved size
one drawback is that changing floating size not remembered when just toggling float/tiled, without closing app

as far as i can remember, Hyprland mostly never did making apps to save state, or maybe long time ago it did
but atleast before f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0 already saved sizes have been respected
for majority of gtk apps this sizes can be set/querried with `gsettings` or `dconf`
qt, as i understand stores in per-app config

what we have now:
for example i wish to launch [Authenticator](https://gitlab.gnome.org/World/Authenticator) floating with rule.
okay, but as soon as it been launched tiled once, this settings got overwritten, if i `togglefloating` or launch again with rule, it get sized with this new weird predicted size

then i have to explicitly set it with gsettings, until next tiled launch
for qt apps thing might be more complicated as it might look like `geometry=bytearray...`, and it's not even possible to find all this config files with different naming schemas
or just launch sway and set it there, lul

sure i can use windowrules to set exact or atleast restrict max size for floating, but toggling float on tiled window not worky now

some apps i tested:
- firefox (didn't found size settings)
- [Authenticator](https://gitlab.gnome.org/World/Authenticator) (gtk)
- qBittorent (qt)
- wireshark (qt)
- Nautilus (gtk)
- Telegram (qt)
- [easyeffects](https://github.com/wwmm/easyeffects) (gtk)

i understand that it might be apps' responsibility to correctly handle such thing, but still,
all of them save/restore sizes on sway

prior f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0 only Telegram saved floating size without any intervention
rest atleast respected it when `togglefloating` and float windowrule

exceptions are apps like Helvum (pipewire's native gtk patchbay) without any stored settings and always launching at fixed floating size, but toggling from tiled again gives predicted weirdo

the ideal thing would be sway's behaviour + respect floating size change when toggling float/tiled (like it works now, but until app is closed)

PS: and yeah, toggling tiled **foot** to float neither works, initially targeted by f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0

### How to reproduce

above

**Comment by bvr-yr** [comment]
le pardon for such a long story, sometimes its hard to explain when there are no obvious conditions

**Comment by vaxerski** [comment]
remembering the size is the app's job. Hyprland seems to send the correct `0,0` configure whenever app is launching floating (aka. "do whatever") and sends a specific size when it's tiled to avoid a "flash" at the beginning.

Nautilus has this bug, but Dolphin doesn't, which further solidifies the case of this being a bug on the side of the apps.

`windowrulev2 = size 600 400,floating:1` I guess

**Comment by bvr-yr** [comment]
like okay.. but

1. togglefloating? chain size dispatcher or script? sure why not
2. sway is doing smth wrong and apps' bugs become features?

**Comment by vaxerski** [comment]
> sway is doing smth wrong and apps' bugs become features?

yes, basically. Sway always sends the apps a "do whatever". I assume some apps take the last "don't do whatever" and forcefully remember that.
