### ISSUE TITLE
Using focuswindow with follow_mouse=2 will warp cusor but not cursor focus.

### ISSUE THREAD

**Issue by ProtoSharkk** [hyprwm/Hyprland#4949]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: 

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

If the follow_mouse variable is set to 2, using the focuswindow dispatcher will warp the cursor to the focused window but not move cursor focus. The cursor focus will stay on the previously focused window. In order to move cursor focus, you need to either click or move the cursor.

### How to reproduce

Set follow_mouse to 2, and no_cursor_warps to false. Select one window and then use the focuswindow dispatcher to move keyboard focus. Try scrolling on the newly focused window, and scroll will apply to the previously focused window.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/130694806/eab4df1a-376c-4de8-8e41-b0513aa5e2d9

**Comment by antonok-edm** [comment]
Seemingly related:

1. Set `follow_mouse = 2` and `cursor:no_warps = true`.
2. Use a `movefocus` bind to focus on a window away from the cursor.
3. Scroll the mouse wheel. Scrolling applies to the newly focused window, despite the cursor hovering over the previous window.
4. Nudging the cursor by a miniscule amount will return scrolling to the window under the cursor.
