### ISSUE TITLE
movefocus in fullscreen scaling issue

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#495]
If fullscreen is enabled and movefocus is used to display another window of the workspace in fullscreen,
the new focused window is not rescaled sometimes.

**Comment by vaxerski** [comment]
can't reproduce

**Comment by Dickby** [comment]
I use qutebrowser, with it it happens quite often.
I tried other browsers (firefox and chromium) and don't get the same problem with them.
Maybe it's reproducable with qutebrowser.

**Comment by vaxerski** [comment]
@fufexan can you repro this pls ty

**Comment by fufexan** [comment]
Works properly after the XDG blur fix.

**Comment by Dickby** [comment]
Well, i don't use blur.

**Comment by vaxerski** [comment]
don't worry, fluffexan is a bit special just like me. Try with the latest regardless.

**Comment by Dickby** [comment]
Still doesn't rescale.

**Comment by vaxerski** [comment]
might be something with qutebrowser then. Can't reproduce.

**Comment by vaxerski** [comment]
check with daeb0d341882f221029d1f608516a7fca7decfa7

**Comment by Dickby** [comment]
It's fixed. probably commit d0ec2b72aec8a91a904b7678ab093e648bd59cf2 .
Thanks a lot!

**Comment by vaxerski** [comment]
cheerios
