### ISSUE TITLE
minecraft freezing when suspending

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#4950]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

when i suspend with systemctl suspend, minecraft goes black, not responding, if it was opened in that time, maybe am a sussy noob, and this its not a hyprland problem, some1 help me pls. i have dedicated nvidia gpu btw

### How to reproduce

intall minecraft 1.20.4 idk, open it, join a world or smth, then run systemctl suspend, woke from suspend, and try to play minecraft again and u will see the problem. Thank you

**Comment by vaxerski** [comment]
nvidia is not supported.

Most likely an nvidia bug.
