### ISSUE TITLE
Ability to swap all content of one workspace with another at once

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#4953]
### Description

Sometimes  user may want to arrange workspaces with many windows in them, e.g. move the contents of one workspace to another, but doing this manually for each window with `movetoworkspace` dispatcher and arranging them afterwards is **TOO TIRESOME**.

### Proposition

Add `swapworkspacecontent` or `swapworkspacecontentsilent` dispatchers, which take `workspace` param and swap content of active workspace with content of specified workspace.  `swapworkspacecontent` will change active workspace to specified one,  `swapworkspacecontentsilent` - not.

This will allow basically rearrange workspaces on same monitor without pain it some places. 

![scheme](https://github.com/hyprwm/Hyprland/assets/142721811/ac8f63ee-0ad6-4d12-924f-59ee89040070)

**Comment by Ligthiago** [comment]
Oops, I miss already closed issue https://github.com/hyprwm/Hyprland/issues/3554. But scripting, really?

**Comment by vaxerski** [comment]
or a plugin. This makes zero sense.
