### ISSUE TITLE
json ipc

### ISSUE THREAD

**Issue by almostnobody** [hyprwm/Hyprland#4954]
### Description

 why did you decide against using json as message format for events ipc socket2?

I would imagine if it was json and the code just wrote to into socket on every change of data, it would make ipc plugins much more capable and flexible

Additionally to that sending a json of the same format as we get from hyprctl to socket and expecting the state of hyprland  to change accordingly, could be an easier way to script hyprland

**Comment by vaxerski** [comment]
json is _not_ easier to parse, it's actually considerably less efficient. The events in socket2 contain very little data anyways; json makes no sense there.
