### ISSUE TITLE
Add cmake install target

### ISSUE THREAD

**Issue by theoparis** [hyprwm/Hyprland#4956]
### Description

Currently it seems like the makefile is used for the install target even though ninja is used via cmake in the makefile.
I think it would make more sense to add a cmake install target so that you can do this:
```
cmake -B build -G Ninja
cmake --build build
sudo cmake --install build
```

This would also benefit the use case of customizing cmake features such as `-DNO_XWAYLAND=ON` or `-DCMAKE_BUILD_TYPE=MinSizeRel` without having to modify the makefile. This also impacts setting custom compilers and/or compiler flags.

**Comment by vaxerski** [comment]
the problem is install isn't that easy, as we for example use `cpio` which I don't think cmake has an equivalent.

**Comment by cnt0** [comment]
I guess this is about the [installheaders](https://github.com/hyprwm/Hyprland/blob/1343aa865d04d80313b0e674c28ecfdbeb90e876/Makefile#L100). @vaxerski what you're trying to do with cpio? Keep symlinks? I'm pretty sure cmake has such options in at least some commands, might take a look

**Comment by vaxerski** [comment]
feel free to MR

**Comment by fufexan** [comment]
I've worked on porting most of the stuff from the Makefile to CMake, and it works fine, except in the Nix build, where CMake seems to build Hyprland twice for some reason. https://github.com/hyprwm/Hyprland/tree/cmake

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/pull/5667 please test this.
