### ISSUE TITLE
Dota 2 cursor not registering inputs in game

### ISSUE THREAD

**Issue by VeilSilence** [hyprwm/Hyprland#4959]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9d89b7109da9b58904caf7c53a7af4b6daed1696 dirty (config: update per device input configs link (4951)).
Date: Mon Mar 4 02:00:28 2024
Tag: v0.36.0-44-g9d89b710

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

Greetings.
Cursor in dota 2 ( wayland native ) broke after update. In "main menu" it works fine, but when i start the game or just watching how someone playing it basically didn't registering any clicks on screen or if i'm trying to manipulate camera in game.
I didn't test dota 2 in xwayland for this.

My mouse related settings in hyprland in case this required:
<details><summary>Details</summary>
<p>

force_no_accel = false
sensitivity = 0
follow_mouse = 1
env = WLR_NO_HARDWARE_CURSORS,1
Poll Rate = 8000hz ( still broken at 1000Hz also )

</p>
</details> 
Offended commit founded at d72ea5f2a7fdb0d0a7bf914412327195b05199b0

I record video to showcase this bug, but github not allow to attach files bigger than 10MB. I can send to PM in discord/video hosting if needed. 

### How to reproduce

Set Dota 2 wayland native. 
<details><summary>Details</summary>
<p>

1: Edit dota2.sh and comment export SDL_VIDEO_DRIVER=x11.
2: Set this game launch options: SDL_VIDEO_DRIVER=wayland DISPLAY= %command% -novid -fullscreen -w 2560 -h 1440.
For some reason, dota 2 only see my second monitor resolution even in wayland native, so forcing 1440p is required. Same for CS2.

</p>
</details> 

Launch the game. Try to observe how someone play, or start test lobby. 
Try to move camera around.

**Comment by vaxerski** [comment]
please do try in xwayland, does dota 2 even officially support wayland native?

**Comment by VeilSilence** [comment]
Tested in xwayland. Same issue. CS2 seems unnafacted. I'll test some games also. 
No, no official support for "wayland native", but it's planned.
Vavle force dota and cs2 run to x11:
```shell
# Remove when Source 2 supports Wayland
if [ "$UNAME" == "Linux" ]; then
   export SDL_VIDEO_DRIVER=x11
fi
```

**Comment by VeilSilence** [comment]
Small update: I loaded in test lobby, and for example click on left part of screen, hero goes to this place. After that, if i click on the right/top/bottom part of my screen, dota 2 show that i clicking in same place always. Moving cursor to my second monitor on the right, then moving cursor from right to left make that dota will continiously moving camera to the right. 
Shall i make video for example?

**Comment by vaxerski** [comment]
that wont help much. What would help is a game that isn't 20GB to repro this lel.

a hyprland log excerpt when this happens could help too

**Comment by VeilSilence** [comment]
Sure, here.
[hypr.log](https://github.com/hyprwm/Hyprland/files/14485707/hypr.log)

**Comment by vaxerski** [comment]
nothing looks amiss :/

**Comment by DashieTM** [comment]
[Kooha-2024-03-04-22-30-40.webm](https://github.com/hyprwm/Hyprland/assets/72016555/95322230-c52a-49e5-90c1-d71005368f1e)
Here is a short showcase of what happens (file limit), the cursor is locked into place, clicks are registered, but the mouse position isn't moved.

**Comment by vaxerski** [comment]
dam bro you didnt have to moan so loud on the recording.

Anyways, I will bring that back, as in my understanding of the protocol that's what we should be doing anyways.

**Comment by vaxerski** [comment]
done, check 7a76ab01d16cdeb3bbb11449476d2b8ad84a3fda

**Comment by DashieTM** [comment]
doto worky, thanks. 

This can be closed then, I hope the issue for the other guys can be solved differently over time.
Should this be reopened? -> https://github.com/hyprwm/Hyprland/issues/3669
