### ISSUE TITLE
Active window glitch

### ISSUE THREAD

**Issue by noahofcarpetballfame** [hyprwm/Hyprland#496]
if you are on say workspace one, and window A is active, and then you switch to an empty workspace, move your mouse where window B would be on workspace one and switch back to workspace one, both window A and B have the active outline

only window B ought to have the outline, but instead window A and B have it

sorry for bad video quality

https://user-images.githubusercontent.com/82473273/183478818-687f0be2-7d0d-4ed9-b036-f19ca5a40143.mp4

**Comment by vaxerski** [comment]
trololololo

**Comment by TheLastTeapot** [comment]
what

**Comment by noahofcarpetballfame** [comment]
???

**Comment by vaxerski** [comment]
should be fixed in bf9d358d3b73416ac76812038534863a9e245d85

**Comment by noahofcarpetballfame** [comment]
nope, still happening

**Comment by vaxerski** [comment]
fuck piss shit cunt

**Comment by vaxerski** [comment]
should be fixed

**Comment by noahofcarpetballfame** [comment]
yes
