### ISSUE TITLE
FPS issues both in and outside games

### ISSUE THREAD

**Issue by yashranjan1** [hyprwm/Hyprland#4964]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
Version Info:

Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)



System Info:

System Information:
System name: Linux
Node name: arch
Release: 6.7.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD106M [GeForce RTX 4070 Max-Q / Mobile] [10de:2860] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

My fps seems to be extremely low even though I have high refresh rate monitors and have set the refresh rate in the config for hyprland. Even doing trivial activities like moving the cursor around or scrolling on a webpage, I feel like my fps is sub 40. 

### How to reproduce

My setup:

  CPU : 13th Gen Intel i9-13900HX (32) @ 5.400GHz 
​​ ​ GPU : NVIDIA GeForce RTX 4070 Max-Q / Mobile 
​​  GPU : Intel Raptor Lake-S UHD Graphics 
Display: 2560x1600 @ 165Hz  laptop display with an external 1920x1080 @ 240Hz display
Graphics Drivers: nvidia-dkms (I updated them just now so whatever the most updated version is right now)

I'm not exactly sure what other information you might need to help me. Please do let me know what more I can share with you that would help.

Note: This does not feel like an issue in SDDM when I'm logging in.

**Comment by vaxerski** [comment]
two things:

very outdated hyprland (please update...)
nvidia.

At any rate, this looks like either an nvidia issue, or some performance regressions fixed a while ago in a newer version.

**Comment by yashranjan1** [comment]
Hi,

My hyprland is updated to the latest available version according to pacman. Should I just wait for the new version?

**Comment by vaxerski** [comment]
pacman is lagging behind atm

**Comment by yashranjan1** [comment]
ok ill just wait for the new version then, thanks!

**Comment by yashranjan1** [comment]
ahh okay, ill do that thanks :)

**Comment by yashranjan1** [comment]
hi so i tried that out and paru still seems to be trying to install an older version of hyprland git?

**Comment by vaxerski** [comment]
aur version names do not get updated. Clear your cache (if paru) or select cleanbuild (if yay) to build the newest version
