### ISSUE TITLE
`hyprctl monitors` should show monitor bit depth

### ISSUE THREAD

**Issue by nergdron** [hyprwm/Hyprland#4971]
### Description

the `hyprctl monitors` command should show any information that is configurable by hyprland using the monitor directive. notably, right now it doesn't report bit depth, so there's no easy way to programmatically validate if the monitor is running in 10bit mode after setting it in the config. it also doesn't show things like colour modes, for displays that use things like ypbpr, so it's hard to determine if you're running in something other than RGB. (I have an HDTV which does this, and it's super annoying to get it to RGB mode)

**Comment by nwg-piotr** [comment]
To finally get rid of `wlr-randr`, we would also need listing of available modes. :bulb:

**Comment by nwg-piotr** [comment]
Thank you, @vaxerski!
