### ISSUE TITLE
Steam windows missbehave when assigning them to a specific workspace

### ISSUE THREAD

**Issue by lucasreis1** [hyprwm/Hyprland#4976]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 07c7235b7245375802c767472d62b776458c221d dirty (keybinds: Better handling of workspace_back_and_forth  (4952)).
Date: Mon Mar 4 13:05:20 2024
Tag: v0.36.0-46-g07c7235b

flags: (if any)


System Information:
System name: Linux
Node name: lucas
Release: 6.7.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] [10de:2488] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Sometimes, Steam Friend list spawns with size `5,5`, ignoring even `minsize` window rules. It often spawns not centered to the screen monitor too.
```sh
> hyprctl clients -j | jq '.[] | select(.title=="Friends List")'

{
  "address": "0x5997e79add20",
  "mapped": true,
  "hidden": false,
  "at": [
    957,
    897
  ],
  "size": [
    5,
    5
  ],
  "workspace": {
    "id": 9,
    "name": "9"
  },
  "floating": true,
  "monitor": 0,
  "class": "steam",
  "title": "Friends List",
  "initialClass": "steam",
  "initialTitle": "Friends List",
  "pid": 748791,
  "xwayland": true,
  "pinned": false,
  "fullscreen": false,
  "fullscreenMode": 0,
  "fakeFullscreen": false,
  "grouped": [],
  "swallowing": "0x0",
  "focusHistoryID": 7
}
```

Here's the window rules in place for Steam:

```
windowrulev2 = workspace 9, class:steam
windowrulev2 = float, class: ^(steam)$, title:^(?!Steam).*$
windowrulev2 = minsize 280 635, class: ^(steam)$, title:^(Friends.*)$
```

Same result with or without known workarounds for different issues:
```
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
```

### How to reproduce

1. Assign steam to a specific workspace (e.g. `windowrulev2 = workspace 9, class:steam`)
2. Start Steam (flickering ensues...)
3. open and close friend list until it refuses to open again in the same workspace/size

**Comment by BRS5672023** [comment]
If I recall correctly, this happens just after recent steam updates... and this also happens sometimes when launching a game which has a launch option dialog

**Comment by lucasreis1** [comment]
Further investigation and this only happens when I link steam to a specific workspace:
`windowrulev2 = workspace 9, class:steam`

I have two monitors and workspace 9 is tied to one of them via
`workspace = 9, monitor:$left`

The "Signing in to Steam" window flickers between the center and top left of the screen. Then, it's just a matter of time before other windows just won't show up when i click them (including the Friends List).

Here's the logs pertaning to starting steam up and trying to open the friends list:

[log.txt](https://github.com/hyprwm/Hyprland/files/14779289/log.txt)

**Comment by BRS5672023** [comment]
This issue seems no longer appears in latest steam beta (1716970740)

**Comment by lucasreis1** [comment]
I am still able to replicate it in the new beta, although only in a forced manner (spam open and close the friends list tab until it happens). The blame seems to be entirely on the steam client though, so I've opened an issue with them a few months ago: https://github.com/ValveSoftware/steam-for-linux/issues/10706

**Comment by lucasreis1** [comment]
Pretty much solved now :) Closing.
