### ISSUE TITLE
ALT TAB feature maybe ?

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#4978]
### Description

it would be cool to have a alt tab like feature. I dont ask for a pop up that shows all the windows, like in gnome, but like, when u are in workspace 1 and then u go in workspace 3 or 4 idk, and press alt tab, it will send u back to the windows from workspace 1, bc that was the last focused one. Its alt tab, but without a GUI if u can say so, it would be usable, when u like, have a tiled window, and then on top a full screen one, with an alt tab action, u get to the window behind the full screen one. Thank you

**Comment by vaxerski** [comment]
No. `focuscurrentorlast` exists, history is exposed via `hyprctl clients` for scripting.
