### ISSUE TITLE
Hyprland runs on the nvidia GPU insted of radeon integrated

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#4979]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

even tho i have env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0 in hyprland config file it just run on nvidia gpu, idk if it keeps my gpu active, and drains power faster, or should i not wory. who knows better plase help.

### How to reproduce

 env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0 in your hypr config, then run nvidia-smi and you will see hyprland there

**Comment by vaxerski** [comment]
nvidia is not supported.

That + issue invalid, no version.

Furthermore Hyprland does not choose the drm device, that's done by wlr

**Comment by mooncoffee1** [comment]
sad, god i hate nvidia, i always wanted a gaming latop, but i cant get one with radeon dGPU, i hate my life
