### ISSUE TITLE
bemenu focus loss

### ISSUE THREAD

**Issue by JoshuaFern** [hyprwm/Hyprland#498]
When I start bemenu it often receives no focus, this behavior is inconsistent.
* Sometimes focus is correctly assigned to bemenu at launch but if I accidentally bump my mouse focus is lost.
* Other times bemenu never receives focus on launch. I have to move my mouse over to use it.

Ideally bemenu should be always focused while running, without having to move the mouse over the layer.

Using `follow_mouse=1`

**Comment by vaxerski** [comment]
> Sometimes focus is correctly assigned to bemenu at launch but if I accidentally bump my mouse focus is lost.

That's how it should work.

> Ideally bemenu should be always focused while running, without having to move the mouse over the layer.

Uhh, no. You don't even realize the amount of issues that would entail.

> Other times bemenu never receives focus on launch. I have to move my mouse over to use it.

That's a bug indeed. Will investigate.

**Comment by vaxerski** [comment]
always recieves focus for me.

**Comment by JoshuaFern** [comment]
> > Ideally bemenu should be always focused while running, without having to move the mouse over the layer.
> 
> Uhh, no. You don't even realize the amount of issues that would entail.

Oh, okay. I'm used to this behavior from using dmenu on i3 and I think it's a better user experience, however if it could at least be consistent in receiving focus on launch I would be satisfied with being careful not to bump my mouse.

> always recieves focus for me. Bemenu config / launch cmd?

Managing my hyprland config on nixos with home-manager like so:
`bind=SUPER,D,exec,PATH=$PATH:${config.xdg.dataHome}/../bin ${pkgs.bemenu}/bin/bemenu-run`

This results in the following:
`bind=SUPER,D,exec,PATH=$PATH:/home/jdf/.local/share/../bin /nix/store/njgj9gch3i56crmcp2bn4rc88h2mx4vy-bemenu-0.6.10/bin/bemenu-run`

**Comment by vaxerski** [comment]
bemenu looks very different for me. Send over your config.

**Comment by JoshuaFern** [comment]
https://gist.github.com/JoshuaFern/b7752eb6856a531e8e3552b88832457b

**Comment by vaxerski** [comment]
bemenu config for god's sake

**Comment by JoshuaFern** [comment]
I don't have a bemenu config, I'm just using the default.

**Comment by vaxerski** [comment]
why is mine a bar on top then?

**Comment by JoshuaFern** [comment]
Mine is a bar on top too, I'm confused why you thought it wasn't.

**Comment by vaxerski** [comment]
oh wait maybe that wasnt u on the discord nvm im stoopid.

In any case, it works for me 100% of the times

**Comment by vaxerski** [comment]
try watching the config:
```
watch -n 0.1 "cat /tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/hyprland.log | grep -v "nimat" | grep -v "IME" | grep -v "extInp" | tail -n 45"
```

and look for any focus changes. When you open bemenu, the last log should be "changed focus to surface <ptr>"

**Comment by JoshuaFern** [comment]
Here's a part of my log where the issue is happening:
https://gist.github.com/JoshuaFern/f829eefa8c134585d75fbf53381833a1

I have a terminal window open, press my hotkey for bemenu, type, and it's still focused on the terminal window - no mouse movement. Earlier I was doing this same thing and it was working fine but I restarted hyprland and the issue came back.

**Comment by JoshuaFern** [comment]
![grim screenshot](https://user-images.githubusercontent.com/4300747/183513234-5aed08a3-53ae-4cb6-8084-e82e5a9924b7.png)

**Comment by vaxerski** [comment]
hm. Weird, it seems like it doesn't receive focus, but that would mean that https://github.com/hyprwm/Hyprland/blob/main/src/events/Layers.cpp#L136-L136 is false. Bemenu is interactive. Mouse doesn't seem to be constrained. What

**Comment by vaxerski** [comment]
on your screenshot though you can see what happens, you prolly move your mouse

**Comment by vaxerski** [comment]
I'll test your config tomorrow. Will see.

**Comment by JoshuaFern** [comment]
Okay, I've done some sleuthing. This is getting a little weird.

I tried a few things and discovered that killing xwayland remedied the problem, so I went through all my autostart applications to see which one might be causing the issue and I think it's Steam in a Flatpak. I close it, everything works fine.

Narrowing it down even further, it specifically occurs when any "Steam Chat" window is open on any workspace and tiled so it's smaller than it wants to be.

Sized 1278,1078 = No issue
Sized 638,1078 = Issue occurs

The Steam client window doesn't seem to cause any issues. Seems to happen with non-flatpaked Steam as well.

**Comment by vaxerski** [comment]
pretty sussy, but that's XWayland for ya.

I'll see if it happens to me too, tomorrow. I haven't noticed anything like this though with my wofi.

**Comment by MonAaraj** [comment]
I also agree about bemenu needing to hog-up the focus even while moving the mouse with follow_mouse on, personally. As it's the behavior that every other piece of software I've tried uses, and I quite like it.

**Comment by vaxerski** [comment]
added `misc:layers_hog_keyboard_focus` in 9eb750c00b576d6c1de0a80239c7085de504f72d
