### ISSUE TITLE
hyprland 0.36.0 fails to compile musl

### ISSUE THREAD

**Issue by notmentaloutlaw** [hyprwm/Hyprland#4985]
### Hyprland Version

0.36.0

### Bug or Regression?

Bug

### Description

hyprland fails to compile

### How to reproduce

compile hyprland against musl

### Crash reports, logs, images, videos

[build.log.txt](https://github.com/hyprwm/Hyprland/files/14501777/build.log.txt)

**Comment by thejch** [comment]
Theres a pull request open https://github.com/hyprwm/Hyprland/pull/4805

**Comment by romanstingler** [comment]
please test, should be fixed now
