### ISSUE TITLE
release 0.36 stable build to replace arch 0.35.0-2 stable build

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4990]
### Description

hyprland-git update too frequently, it release five versiones for about five days,one of which may be the reason leads to fail boot I just experienced,I hope it settled on a stable version of 0.36, now It contains enough feature and bug fixes.It's maybe a good time to realease a stable version of 0.36.

**Comment by zakk4223** [comment]
There's already an 'official' 0.36.0 release, it was done last week.

There's a 0.36.0 arch package sitting in extra-testing; you'll have to wait until they promote that out of the testing repo

**Comment by BrodieRobertson** [comment]
Vaxry is not the maintainer of the Arch Linux package, please direct your concerns to the Arch Linux Gitlab

**Comment by vaxerski** [comment]
brother I am not a manintainer for your distro
