### ISSUE TITLE
Crash on attempt to open a lot of windows on one workspace

### ISSUE THREAD

**Issue by kaarelen** [hyprwm/Hyprland#4993]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
cub@cubic ~/.hyprland> hyprctl version
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

Hypr crashed when I've opened a lot of windows in one workspace 
PS My assumption: 
I think it happened because every new window is smaller than previous one and on some point window got to negative size\zero size or smth like that.

### How to reproduce

Keep opening new windows until it crushes. (kitty terminal in my case)

### Crash reports, logs, images, videos

[hyprlandCrashReport525.txt](https://github.com/hyprwm/Hyprland/files/14507996/hyprlandCrashReport525.txt)
[hyprlandCrashReport3697.txt](https://github.com/hyprwm/Hyprland/files/14507999/hyprlandCrashReport3697.txt)

**Comment by vaxerski** [comment]
very outdated and a 17th dupe
