### ISSUE TITLE
Release file is missing libhyprlang

### ISSUE THREAD

**Issue by bsamseth** [hyprwm/Hyprland#4996]
### Hyprland Version

<details> <summary>System/Version info</summary>
Using this prebuilt release: https://github.com/hyprwm/Hyprland/releases/download/v0.36.0/v0.36.0.tar.gz
</details>

### Bug or Regression?

Bug

### Description

After following the instructions for a manual install on the wiki, `Hyprland` fails to run with a complaint that it can't find `libhyprlang.so.1`. This library file is not included in the release (neither is `hyprpm`, also mentioned on the wiki). 

My guess, based on the release notes for version `0.36.0`, is that this library file has recently become required, but not yet included in the release artifact.

### How to reproduce

Download the [release](https://github.com/hyprwm/Hyprland/releases/download/v0.36.0/v0.36.0.tar.gz ), follow the wiki's instructions for manual installation, and finally run `Hyprland`.

**Comment by vaxerski** [comment]
release artifact will not include libhyprlang, as it's not a vendored dependency.

For hyprpm, I didn't know. I'll add it to the CI I guess
