### ISSUE TITLE
kitty causes to display "%" randomly when starting kitty. Please see screenshot

### ISSUE THREAD

**Issue by alekgr** [hyprwm/Hyprland#4997]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch main at commit fb87e332c59ce386a095b3e81bb1abbcc9cc3e5c dirty (input: fix window move stutter by introducing additional checks for low-hz monitors (4553)).
Date: Tue Mar 5 18:15:44 2024
Tag: v0.36.0-59-gfb87e332

flags: (if any)


System Information:
System name: Linux
Node name: rocket
Release: 6.7.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

when starting kitty it displays % on the top like this. 

%                                                                                           
alek at rocket in ~/.config/hypr 
$ 

I also see this error message not sure if this is related. This maybe issue with glfw.

066 10:15:18.308491] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

### How to reproduce

Please let me know what do you need from me to troubleshoot the issue.

### Crash reports, logs, images, videos

![kitty_issue](https://github.com/hyprwm/Hyprland/assets/1727023/3f0d1c1f-f677-4b0c-b52a-3b8927bb23e6)

**Comment by alekgr** [comment]
btw,

My glfw is 3.4-2 and kitty version is 0.31.0

**Comment by Aqa-Ib** [comment]
Do you have the same error on other desktop environments ? 
If I had to guess I would say that is something on your bashrc / zshrc / fishrc.

**Comment by alekgr** [comment]
My  default shell is zsh,
It happens too with bash shell

I have tried with awesome window manger  and I don't see the issue
I have tried with weston(another wayland compositor)  and I got the same glfw message but I don't see the symptom of printing "%"

**Comment by vaxerski** [comment]
why would this be a hyprland issue?
