### ISSUE TITLE
virt-manager cannot grab keys 

### ISSUE THREAD

**Issue by thomascft** [hyprwm/Hyprland#501]
I use virt-manager regularly, and recently I made the switch to Hyprland. I noticed that hyperland doesn't redirect input involving shortcuts to the spice session. If I try to switch workspaces, or open a terminal in my vm it switches/opens on the host. RiverWM has the ability to pass all input through using a shortcut to toggle back and forth. Any way to fix this?

**Comment by vaxerski** [comment]
you can hack it with a submap.

Make an empty submap with only a keybind to go back to your regular one. If you enter it, all keybinds except the return one will be ignored and forwarded to the vm

**Comment by thomascft** [comment]
Perfect! Is this in the wiki, or would somebody need to add it?

**Comment by thomascft** [comment]
I can't get both bound to the same keybind, is there anything I'm missing? I'd like to use the default `Ctrl_L + Alt_L`

```
bind=CTRL,ALT_L,submap,passthrough
submap=passthrough
bind=CTRL,ALT_L,submap,reset
submap=reset
```

**Comment by vaxerski** [comment]
```
bind=CTRLALT,Alt_L,blahblah
```

**Comment by vaxerski** [comment]
> Perfect! Is this in the wiki, or would somebody need to add it?

submaps are, this tip isn't

**Comment by thomascft** [comment]
> ```
> bind=CTRLALT,Alt_L,blahblah
> ```

The second one works, but if I try to use the same bind to start the submap it doesn't seem to work.

**Comment by vaxerski** [comment]
my bad, forgot that for MOD binds you have to use `bindr`

**Comment by thomascft** [comment]
If I manually trigger the submap with `hyprctl`, I can use the assigned bind to leave it, but if I try to start it with the same I just doesn't start.

**Comment by vaxerski** [comment]
use `bindr` for mod-only keybinds and it will work.

**Comment by thomascft** [comment]
This doesn't work for init `bindr=CTRLALT,ALT_L,submap,passthrough`

**Comment by vaxerski** [comment]
ah, I see. Yeah a bug with bindr and submaps. Sec

**Comment by thomascft** [comment]
I would also add that the one for exiting works just fine as `bind=CTRL,ALT_L,submap,reset`

**Comment by thomascft** [comment]
This works fine for entering and exiting, it almost seems as it removes the first bind in favour of the on in the submap
```
bind=CTRL,ALT_L,submap,passthrough
submap=passthrough
bindr=CTRL,Escape,submap,reset
submap=reset
```

**Comment by vaxerski** [comment]
fixed

**Comment by thomascft** [comment]
Ok, building rn. Thx

**Comment by thomascft** [comment]
Works great!

**Comment by q234rty** [comment]
Would still be great to support keyboard-shortcuts-inhibit-unstable-v1 as having to switch the keymap when switching between the vm and other apps is still annoying.
