### ISSUE TITLE
Broken on screen keyboard

### ISSUE THREAD

**Issue by AmirDahan** [hyprwm/Hyprland#5011]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 6c4e2489a0a153ac2a92744ecb2985280c97fc89 dirty (layout: Fix toggling fullscreen special workspace on different monitor (5000)).
Date: Thu Mar 7 15:27:58 2024
Tag: v0.36.0-69-g6c4e2489

flags: (if any)


System Information:
System name: Linux
Node name: system
Release: 6.7.0+
Version: #42 SMP PREEMPT Thu Mar  7 23:52:56 IST 2024


GPU information: 


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
  hyprgrass by horriblename ver 0.5
```

</details>

### Bug or Regression?

Bug

### Description

wvkbd seems to have broken on ARM a few updates back (Not older than a week or two ago)
I don't know which update exactly broke it but it's not that old

Running wvkbd now and tapping any key causes wvkbd to hide and never shows again
It also says ``xdg_surface@22: error 3: xdg_surface has never been configured``

As a sanity check i also tested labwc and it works fine there
Same for an older version of hyprland i had on another install (which i updated without noting down the current version)
After updating it stopped working again

### How to reproduce

1. Own an ARM device e.g Raspberry pi, Phone, Ect
2. Boot any linux distro (In my case arch/artix)
3. Have a touchscreen
4. Install wvkbd and launch it
5. Press any button
6. Observe

**Comment by vaxerski** [comment]
#4806
