### ISSUE TITLE
hyprctl notify randomly gives `invalid fontsize kwarg`

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#5012]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 6c4e2489a0a153ac2a92744ecb2985280c97fc89 dirty (layout: Fix toggling fullscreen special workspace on different monitor (5000)).
Date: Thu Mar 7 14:27:58 2024
Tag: v0.36.0-69-g6c4e2489

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.7.8-zen1-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 17:02:55 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprctl sometimes gives `invalid fontsize kwarg` instead of sending a notification

### How to reproduce

run `hyprctl notify -1 1000 0 "jjjjjjjjj"`
> ok

run `hyprctl notify -1 1000 0 "jjjjjjjjjj"`
> invalid fontsize kwarg

this only appears to happen for some notifications, I was unable to find a pattern. The lenght isn't the problem

**Comment by vaxerski** [comment]
#4981

@ItsDrike wanna comment on this?

**Comment by alba4k** [comment]
I mean the implementation is fine, just update the wiki accordingly or, even better, put the font size after the text and make it optional

**Comment by ItsDrike** [comment]
I assumed `string::compare` returns a boolean, it returns an integer indicating the result of the comparison. It's an easy fix, give me like 2 minutes, I can PR it

**Comment by alba4k** [comment]
Damn I wish github had a 🤡 reaction
