### ISSUE TITLE
$(cat) in source for dynamic loading of config files

### ISSUE THREAD

**Issue by Kommynct** [hyprwm/Hyprland#5018]
### Description

in sway I do the following:

```
include {
	~/.config/sway/modules/*
	"~/.config/sway/$(cat /etc/hostname)"
	/etc/sway/config.d/*
}
```

This allows me to have a file in my sway config folder that is the hostname of the machine i'm on, this also lets me do a git pull of my dotfiles and have machine-specific configs stay machine specific

I understand source = exists, but there doesn't seem to be a way to make $(cat /etc/hostname) work within it.

**Comment by zakk4223** [comment]
You can use environment variables in the config. Stuff the hostname into an ENV that's visible to hyprland on launch and just do source=~/.config/hypr/config.d/$HOSTNAME_VAR.conf

**Comment by Kommynct** [comment]
that's perfect, thank you!

I added export `HOSTNAME=$(cat /etc/hostname) `to my .zprofile and set it to be 

`source = ~/.config/hypr/$HOSTNAME.conf`

works perfectly!
