### ISSUE TITLE
Hyprctl keyword broken?

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#5025]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 6c4e2489a0a153ac2a92744ecb2985280c97fc89 dirty (layout: Fix toggling fullscreen special workspace on different monitor (5000)).
Date: Thu Mar 7 20:27:58 2024
Tag: v0.36.0-69-g6c4e2489

flags: (if any)


System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.21-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 06 Mar 2024 16:59:55 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

```sh
$ hyprctl devices | grep touch
		asue120a:00-04f3:319b-touchpad
$ hyprctl keyword "device:asue120a:00-04f3:319b-touchpad:enabled" false
special category's first value must be the key. Key for <device> is <name>
```

This command used to work at some point before, but on the current version it seems not to be.

If I use getoption instead of keyword, it always says no such option (I do not think it is understanding the name key either)

### How to reproduce

use hyprctl keyword to try to change a property of a device (such as disabling it)

**Comment by cybergaz** [comment]
yeah , i'm facing same issue.

i need to toggle my touchpad more often , and there's no way in wayland to toggle it except through Hyprland.

it's so annoying , is is too much to ask for just disabling an input device ??

anyway, in the mean time you can use `hyprctl keyword "general:sensitivity" 0`

**Comment by vaxerski** [comment]
```ini
$ENABLE_MOUSE = true

device {
    name = mouse
    enabled = $ENABLE_MOUSE
}
```

```sh
hyprctl keyword '$ENABLE_MOUSE' "false"
```

**Comment by cybergaz** [comment]
it's not working,
hyprctl is unable to modify the variable's value

**Comment by vaxerski** [comment]
make sure you have hyprlang >0.4.0 and use single quotes around the variable name

**Comment by Rabcor** [comment]
> ```ini
> $ENABLE_MOUSE = true
> 
> device {
>     name = mouse
>     enabled = $ENABLE_MOUSE
> }
> ```

No worky...

![image](https://github.com/hyprwm/Hyprland/assets/5684325/3e93e171-622c-4064-8aa2-1291cfd81b8f)


And I do have hyprlang 0.4.1.

Also the old way was way better, this is kind of a lame change, it was nice to be able to reliably toggle devices this way without a special config.

**Comment by vaxerski** [comment]
my bad, you need to pass the `-r` flag to hyprctl. 

> Edit: Actually even if I set it to false in the config file directly (without hyprland keyword) it still doesn't do anything, this straight up just does not work.

Nothing besides the config parser changed, so this is not related if true

**Comment by vaxerski** [comment]
ah, your bug is I believe a dupe of https://github.com/hyprwm/hyprlang/issues/29 which was fixed in hyprlang 0.4.2

**Comment by Rabcor** [comment]
Seems like it yeah.

**Comment by cybergaz** [comment]
this update looks superfluous...
now i have to **interact with hyprland.conf** for making my touchpad toggle script work.
sigh....

**Comment by vaxerski** [comment]
you don't, just update hyprlang, arch's been very behind on updates recently.

**Comment by cybergaz** [comment]
no, i mean i've updated and all , and it's working by creating that variable.

all i was saying that,
now i can't automatically grep out my touchpad device and just create a oneliner/script for toggling touchpad (like before),
now i have to explicitly put my device name in hyprland config , create a variable and then create a script to toggle it.

it's problematic when i share my script to someone who is less experienced in linux and hyprland.

**Comment by Rabcor** [comment]
Indeed, that's why i said the old way is better, this just seems like a poor design choice.

**Comment by vaxerski** [comment]
you can report official packages as out-of-date, they've been reported as such for weeks.
