### ISSUE TITLE
Fullscreen games reading cursor position wrong

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#5029]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 6c4e2489a0a153ac2a92744ecb2985280c97fc89 dirty (layout: Fix toggling fullscreen special workspace on different monitor (5000)).
Date: Thu Mar 7 20:27:58 2024
Tag: v0.36.0-69-g6c4e2489

flags: (if any)


System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.21-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 06 Mar 2024 16:59:55 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Ever since i recompiled from git yesterday (it did not happen before then), I have been having a problem where sometimes when i launch games in fullscreen the game reads the cursor position incorrectly (see screenshot for what i mean)

### How to reproduce

Launch a game (seemingly any game, i have had this issue with a proton/dxvk game and a native opengl game) in fullscreen and see if the mouse works. It doesn't happen 100% of the time but it is quite frequent.

### Crash reports, logs, images, videos

As you can see, the cursor is a bit below the racemenu, but there's a tooltip where the game thinks the cursor is (just about right in the middle of the screen)
![image](https://github.com/hyprwm/Hyprland/assets/5684325/f04ef625-fdb9-4e57-b96b-c1454090acae)

**Comment by Rabcor** [comment]
> well I'll need some more information about your setup brother as it doesn't happen in any game I play.
> 
> Is this perhaps xwayland with force_zero_scaling?

yes

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14542437/patch.txt)
try

**Comment by Rabcor** [comment]
> well I'll need some more information about your setup brother as it doesn't happen in any game I play.
> 
> Is this perhaps xwayland with force_zero_scaling?

I tested it a bit more after you said that, it seems with openmw the issue always occurs when force_zero_scaling is on, but never when it is off (at least between about 5 launches under each condition),  so it is definitely related to this.

The other game it still only happens sometimes when force_zero_scaling is on, i haven't been able to test that one very thoroughly though because it takes a min to launch

**Comment by Rabcor** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14542437/patch.txt) try

I'm afraid I don't know how, i'm on arch and have just been installing with the aur package, i could maybe edit the pkgbuild to include the patch but i have used the patch command so rarely i'm not even  sure what the exact command would look like :/

**Comment by vaxerski** [comment]
`patch -p1 < /path/to/patch || echo ""`

**Comment by Rabcor** [comment]
```
source=(
  "git+https://github.com/hyprwm/Hyprland.git"
  "git+https://gitlab.freedesktop.org/wlroots/wlroots.git"
  "git+https://github.com/hyprwm/hyprland-protocols.git"
  "git+https://github.com/canihavesomecoffee/udis86.git"
  "git+https://github.com/wolfpld/tracy.git"
  "patch.txt"
)
b2sums=(
  'SKIP'
  'SKIP'
  'SKIP'
  'SKIP'
  'SKIP'
  'SKIP'
)

pick_mr() {
  git pull origin pull/$1/head --no-edit
}

prepare() {
  cd Hyprland
  patch -p1 < "$srcdir/patch.txt" || echo ""> `patch -p1 < /path/to/patch || echo ""`
```

The command didn't seem to work, this was the output:

```
patching file src/managers/input/InputManager.cpp
File subprojects/wlroots is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file subprojects/wlroots.rej
```

**Comment by Rabcor** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14542437/patch.txt) try

Ok, i'm pretty sure it worked, at least i can't replicate the issue after i applied it.

**Comment by bubba-champion** [comment]
Looks like I'm having the same or similar problem. DXVK / Proton / Xwayland. Video demonstration from Hyprland compiled from https://github.com/hyprwm/Hyprland/commit/717d5b3cc2b9e2f94d3ec1ba794e21bc2bb787e3 with the above patch applied: https://youtu.be/KtpDyNPXzO4
