### ISSUE TITLE
Fails to build on Gentoo Linux aarch64

### ISSUE THREAD

**Issue by Ahwxorg** [hyprwm/Hyprland#5038]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
gui-wm/hyprland-0.35.0-r1
```

Some system info:
```sh
OS: Gentoo Linux aarch64
Host: Apple MacBook Pro (14-inch, M2 Pro, 2023)
Kernel: 6.6.0-asahi-15-liv-2
Shell: zsh 5.9
DE: Hyprland
Terminal: foot (no clue if this could matter...)
CPU: Apple Blizzard-M2-Pro (10) @ 2.424GHz
Memory: 3099MiB / 15579MiB (was down to 1GB when compiling, so the system had 15GB for the compile jobs)
```

</details>

### Bug or Regression?

Bug

### Description

`gui-wm/hyprland-0.35.0-r1` failed to build when I tried to update it.

### How to reproduce

Be on Gentoo and run `emerge gui-wm/hyprland`

### Crash reports, logs, images, videos

Since the issue would be a bit big, I uploaded the log to [https://0x0.st/HhPR.log](https://0x0.st/HhPR.log)

**Comment by Ahwxorg** [comment]
Oh, forgot, I also have `USE="X legacy-renderer -systemd"` on Hyprland.

**Comment by vaxerski** [comment]
please do not report build failures, CI passes. Also, very old ver.
