### ISSUE TITLE
Hyprland crashes on launch

### ISSUE THREAD

**Issue by KoPlayz** [hyprwm/Hyprland#5039]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?%
```
Version from pacman says 0.35.0-2

</details>

### Bug or Regression?

Bug

### Description

Hyprland fails to start from both TTY and sddm

### How to reproduce

Attempt to use “Hyprland” command (without quotations) or launch hyprland from any other DM

### Crash reports, logs, images, videos

coredump [log.txt](https://github.com/hyprwm/Hyprland/files/14545756/log.txt)

**Comment by vaxerski** [comment]
you did not attach a log
you did not provide any info
you're on an outdated hyprland version

**Comment by KoPlayz** [comment]
> you did not attach a log
> 
> you did not provide any info
> 
> you're on an outdated hyprland version

I attached a coredump, and this is the latest version available in my package manager

**Comment by vaxerski** [comment]
I don't care about your package manager, I do not maintain the package.
