### ISSUE TITLE
wvkbd layer_shell popup surface seems wrongly configured with hyprland master

### ISSUE THREAD

**Issue by stacyharper** [hyprwm/Hyprland#5040]
### Hyprland Version

v0.36.0..3e930a56 (current master)

### Bug or Regression?

Bug

### Description

Wvkbd now seems to crash on the first touch with Hyprland dev master:

https://github.com/jjsullivan5196/wvkbd/issues/65

We are configuring a xdg_popup surface on top of the layer_shell surface.

It looks like you recently re-implemented xdg_popup. Is Master currently expected to works for this case?

### How to reproduce

Run wvkbd, click, or touch on a key

**Comment by stacyharper** [comment]
@proycon just mentionned the error here: https://github.com/hyprwm/Hyprland/pull/4877#issuecomment-1986825772

Sorry if this is duplicate.

**Comment by vaxerski** [comment]
see the wvkbd issue linked
