### ISSUE TITLE
Screen seems to wrap around from the bottom to the top

### ISSUE THREAD

**Issue by Dimev** [hyprwm/Hyprland#5041]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

On my left monitor (connected with displayport -> hdmi adapter) on first startup, the screen seems to be misaligned, so a bit of the bottom ends up at the top of the screen. This only happens on my left screen. I'm using an AMD RX7600 GPU. (this didn't happen with my old nvidia gtx 1660)

### How to reproduce

Start hyprland, Issue appears. Stop hyprland and start it again, issue is gone.

### Crash reports, logs, images, videos

![QQ](https://github.com/hyprwm/Hyprland/assets/49782454/305de6a5-9cd7-447d-9642-670c3e0f54ac)

**Comment by vaxerski** [comment]
this is a driver bug

**Comment by Dimev** [comment]
Is this a known driver bug somewhere?
if so, how could I fix it?

**Comment by vaxerski** [comment]
I've never seen this happen and thus can't be of much help here.

**Comment by Dimev** [comment]
Oh, sadge, but thanks anyway
