### ISSUE TITLE
Hyprland crashes after creating multiple windows on the same desktop

### ISSUE THREAD

**Issue by progzone122** [hyprwm/Hyprland#5042]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
```

</details>

### Bug or Regression?

Bug

### Description

After opening several windows of the same application (this doesn't only happen with alacritty terminal), a crash occurred on the same desktop (video below)

### How to reproduce

The video is attached below

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/80642969/7308261e-85e4-4f33-8d2b-ab8b212f57c3

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14546152/hyprland.log)
[hyprlandCrashReport73310.txt](https://github.com/hyprwm/Hyprland/files/14546153/hyprlandCrashReport73310.txt)

**Comment by Ligthiago** [comment]
Update to 0.36.0, it's already fixed, братан.

**Comment by progzone122** [comment]
> Update to 0.36.0, it's already fixed, братан.

Спасибо, сейчас попробую

**Comment by progzone122** [comment]
Update to 0.36.0
