### ISSUE TITLE
Surface doesn't immediately update on resize

### ISSUE THREAD

**Issue by phonetic112** [hyprwm/Hyprland#5044]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit 717d5b3cc2b9e2f94d3ec1ba794e21bc2bb787e3 dirty (hyprctl: hide unmapped windows without -a).
Date: Fri Mar 8 12:47:12 2024
Tag: v0.36.0-77-g717d5b3c

flags: (if any)


System Information:
System name: Linux
Node name: artix
Release: 6.7.8-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 08:30:13 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

When resizing a window the surface isn't immediately updated for the new window size, resulting in brief stretching artifacts. It's more noticeable with animations turned off.

### How to reproduce

1. Open a window
2. Toggle floating or resize the window somehow
3. Window is briefly stretched

### Crash reports, logs, images, videos

Slow motion video of this happening: Hyprland, 60hz, recorded at 1000 fps

https://github.com/hyprwm/Hyprland/assets/73647246/4d37a8ef-53eb-4798-a09e-0e51c0a47452

Sway, 60hz

https://github.com/hyprwm/Hyprland/assets/73647246/b4fb766d-a91f-4ee0-9458-5d7c52e955c4

**Comment by vaxerski** [comment]
idk why this happens tbh, we send the configure the same way, maybe sway waits for the surface to update before commencing the fullscreen?

**Comment by phonetic112** [comment]
probably

**Comment by phonetic112** [comment]
been experimenting a bit, I found that setting m_vReportedSize to m_vRealSize.goal() fixes the stretching, but it still creates a frame of the old window on the resize

Slow-mo video, 30hz:

https://github.com/hyprwm/Hyprland/assets/73647246/c39ee3a9-9f0a-423e-8b3f-d9199e9147da
