### ISSUE TITLE
Hyprland

### ISSUE THREAD

**Issue by Shaantshikari** [hyprwm/Hyprland#5045]
### Hyprland Version

Waming: You're using an autogenerated config! (config file: /home/shaantshikari/.config/hypr/hyprland.conf)

SUPER+Q-> kitty

SUPER+M-> exit Hyprland

When i flash hyprland it's shows this type of icon I can't access the main menu it stuck at this point what's i can do plz help

### Bug or Regression?

Bug

### Description

Atenção: você está usando uma configuração gerada automaticamente! (arquivo de configuração: /home/shaantshikari/.config/hypr/hyprland.conf)

SUPER+Q-> gatinho

SUPER+M-> saída de Hyprland

### How to reproduce

How to use hyprland in proper ways plz tell me

**Comment by Z0achary** [comment]
this is not a bug!

**Comment by Z0achary** [comment]
please go learn hyprland

**Comment by Shaantshikari** [comment]
Aayein bro ye bata do na kii iske home manager pe kaise jaye matlab kii main screen pe
