### ISSUE TITLE
Unable to update hyprpm

### ISSUE THREAD

**Issue by Z0achary** [hyprwm/Hyprland#5046]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

I wanted to get static tiling on hyprland using a [plugin](https://github.com/outfoxxed/hy3)
following the install guide
hyprpm update
output:
! Cloning https://github.com/hyprwm/hyprland, this might take a moment.
✔ cloned
✔ checked out to running ver
! configuring Hyprland
✔ configured Hyprland
✖ failed to install headers with error code 2
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed

✖ Headers missing. Please run hyprpm update to fix those.

### How to reproduce

hyprpm update

### Crash reports, logs, images, videos

![20240309_22h36m18s_grim](https://github.com/hyprwm/Hyprland/assets/86001650/abad2715-da8a-4174-80ef-7d3802873a0b)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14547569/hyprland.log)

**Comment by Z0achary** [comment]
also i got hyprland from pacman if that helps

**Comment by vaxerski** [comment]
you're most likely missing deps, please rtfm: https://wiki.hyprland.org/Plugins/Using-Plugins/#hyprpm

**Comment by Z0achary** [comment]
I do have the deps.

**Comment by vaxerski** [comment]
really? post the output with `-v`

**Comment by Z0achary** [comment]
i did have dependencies doing, ``hyprpm update`` gives me an error about headers missing. After doing ``hyprpm update -v`` it works now. thanks
