### ISSUE TITLE
Direct scanout no longer working

### ISSUE THREAD

**Issue by zmeyka3310** [hyprwm/Hyprland#5047]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0

flags: (if any)


System Information:
System name: Linux
Node name: SamsungSmartFridge
Release: 6.6.21_1
Version: #1 SMP PREEMPT_DYNAMIC Fri Mar  8 01:01:43 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a68] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

frames being pushed to render in the wrong order/repeating when being pushed from the secondary gpu, direct scanout no longer working. downgrading nvidia drivers to 535 didnt help either.

### How to reproduce

install hyprland using makrennels tempelate: https://github.com/Makrennel/hyprland-void/, enable direct scanout in the config, no worky

### Crash reports, logs, images, videos

config:
[conf.txt](https://github.com/hyprwm/Hyprland/files/14547610/conf.txt)
[packages.txt](https://github.com/hyprwm/Hyprland/files/14547620/packages.txt)

**Comment by vaxerski** [comment]
> downgrading nvidia drivers to 535 didnt help either.

nvidia is not supported.

Anyways no direct scanout sounds like #4935

rest is nvidia
