### ISSUE TITLE
Wiki is wrong about dwindle configuration

### ISSUE THREAD

**Issue by br-olf** [hyprwm/Hyprland#5049]
I tried to change the dwindle tabbed layout's boarder color and found the documentation in the wiki is wrong.

See 
https://wiki.hyprland.org/0.18.0beta/Configuring/Dwindle-Layout/ 
and compare this to the actual source code:
https://github.com/hyprwm/Hyprland/blob/26cd1bf949d0460b754fe3b1ae7f06bd4b2535ee/src/Compositor.cpp#L1871
https://github.com/hyprwm/Hyprland/blob/26cd1bf949d0460b754fe3b1ae7f06bd4b2535ee/src/Compositor.cpp#L1872

The configuration that ended up working with Hyprland version `1.3.1-5` was:
```
group {
    col.border_active = $color_active_border
    col.border_inactive = $color_inactive_border
}
```

For all people looking into this issue:
Configuration examples I found that configure this options in the `general` or `dwindle` blocks are not working in the current upstream version of Hyprland.

**Comment by Ligthiago** [comment]
You a looking to wiki for 0.18.0beta, current release version is 0.36.0, wtf bro. Select wiki version in sidebar
