### ISSUE TITLE
Launching kanshi instantly crashes hyprland

### ISSUE THREAD

**Issue by Kommynct** [hyprwm/Hyprland#5054]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

launching kanshi on latest master or current archlinux instantly crashes hyprland for me

### How to reproduce

launch kanshi

### Crash reports, logs, images, videos

https://pastebin.com/gRNNU1K9

**Comment by vaxerski** [comment]
very old version, dupe, fixed in git
