### ISSUE TITLE
Include screenSize uniform in  screen_shader

### ISSUE THREAD

**Issue by leiserfg** [hyprwm/Hyprland#5059]
### Description

Some shaders need the size of the screen to calculate the real position of the pixel. The other option is to hardcode the screen size but it breaks in multi-monitor setups.

**Comment by leiserfg** [comment]
Sorry for the annoyance, but in the other shader the uniform is called `"screenSize"`  I think it makes sense to use the same name in both places isn't it?

**Comment by vaxerski** [comment]
in what shader

**Comment by leiserfg** [comment]
https://github.com/hyprwm/Hyprland/blob/4ffcdc41ff8233a92f02c633475ac3472b0998df/src/render/OpenGL.cpp#L422

**Comment by vaxerski** [comment]
that shader doesn't exist

**Comment by vaxerski** [comment]
there, allowed both.
