### ISSUE TITLE
Confusing ID values for named workspaces

### ISSUE THREAD

**Issue by barbashovtd** [hyprwm/Hyprland#506]
When number for workspace set as ID, everything is good: right order of workspaces and hyprland's ID to workspace name mapping.
But, according to
https://github.com/hyprwm/Hyprland/blob/main/src/helpers/Workspace.hpp
when workspace created as named, ID becomes negative (-1337), which slightly breaks waybar's wlr/workspaces:
1. sort-by-coordinates works incorrectly
2. I dunno why, but ID's assigned a bit unevenly (see below)

So, the user is limited to two options in waybar:
1. Indexed workspaces + sort-by-coordinate with no ws names
2. Named workspaces and alphabetical order and no control over ws order 

hyprctl workspaces:
```
workspace ID -1337 (photo) on monitor eDP-1:
   windows: 2
   hasfullscreen: 0
 workspace ID -1340 (dev) on monitor eDP-1:
   windows: 1
   hasfullscreen: 0
 workspace ID -1341 (web) on monitor eDP-1:
   windows: 1
   hasfullscreen: 0
 workspace ID -1342 (social) on monitor eDP-1:
   windows: 1
   hasfullscreen: 0
 workspace ID -99 (special) on monitor eDP-1:
   windows: 1
   hasfullscreen: 0
```

It seems like order of workspaces creation does not follows order of commands in .conf file.
Also it affect workspace sliding effect, e.g. changing with mouse scroll in one direction (1>2>3>4) reveals workspaces from different directions.

Sorry if I wasn't clear or just didn't get feature-not-a-bug)) (or just stupid)

Related part of config file (there's no any other modifications for workspaces in file):
```
# desired order: dev web social photo
workspace = eDP-1,name:dev
workspace = eDP-1,name:web
workspace = eDP-1,name:social
workspace = eDP-1,name:photo
# real order: photo (always) dev web social
```

**Comment by vaxerski** [comment]
```
workspace = eDP-1,name:dev
workspace = eDP-1,name:web
workspace = eDP-1,name:social
workspace = eDP-1,name:photo
```
this is wrong

> sort-by-coordinates works incorrectly

all have the same coordinates, what do you expect?

> I dunno why, but ID's assigned a bit unevenly (see below)

https://github.com/hyprwm/Hyprland/blob/main/src/Compositor.cpp#L1124-L1132

Propose a solution then, and not just point out the mechanism's faults.

**Comment by pdf** [comment]
The linked code didn't use a permalink, so I can't see now what it was meant to refer to, but couldn't we pre-allocate IDs for named workspaces when they're declared in the config, rather than allocating IDs just-in-time?
