### ISSUE TITLE
hyprctl notify: fontsize does not work

### ISSUE THREAD

**Issue by xk67** [hyprwm/Hyprland#5063]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.36.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.6.19
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar  1 12:35:11 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240303.b8697e5"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

The font size of the notification of hyprctl notify does not work. Displays fontsize property in the message instead.

### How to reproduce

`hyprctl notify -1 10000 "rgb(ff0000)" "fontsize:35 This text is big"`

### Crash reports, logs, images, videos

![20240310_17h42m13s_grim](https://github.com/hyprwm/Hyprland/assets/144571295/e7bd2297-6dfa-4dfc-aa69-e934b55589f6)

**Comment by Ligthiago** [comment]
It's for git, it merged like a few days ago, you're on stable v0.36.0. Choose wiki version properly.
