### ISSUE TITLE
Custom ".desktop" Startup Applications Not Working

### ISSUE THREAD

**Issue by KareemMukbil** [hyprwm/Hyprland#5064]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Linux Fedora
Release: 6.7.7-200.fc39
Hyprland version: 0.36.0
```

</details>

### Bug or Regression?

Bug

### Description

A .desktop application that was created in `.local/share/applications/` is not launching at startup with `exec-once = ~/.local/share/applications/appishere.desktop`
 Otherwise, it launches just fine.

### How to reproduce

1. Create a .desktop file under `.local/share/applications`
2. Go into your hyprland config file, and add the line `exec-once = ~/.local/share/applications/appishere.desktop`
3. Reboot.
4. Wait in disappointment as you realize it will never launch.

### Crash reports, logs, images, videos
It says Desktop: command not found, TextEditor: command not found. Although those are typical commands you would have in a .desktop file.

**Comment by Ligthiago** [comment]
How do you want to launch .desktop file? Open it in text editor or `cat`, take all after `Exec=` from it and paste to `exec-once =` in hyprland config

**Comment by KareemMukbil** [comment]
Fixed, thank you.

**Comment by xmalbertox** [comment]
> Fixed, thank you.

To auto start desktop files in a seamless way checkout [dex](https://github.com/jceb/dex).
