### ISSUE TITLE
Cursor sporadically keeps "resetting" to same location on screen

### ISSUE THREAD

**Issue by sl33nyc** [hyprwm/Hyprland#5067]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 981296f101cf79176a8da7a1aa64fa297b2976dc dirty (flake: bump inputs (5066)).
Date: Sun Mar 10 15:52:54 2024
Tag: v0.36.0-95-g981296f1
flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

It's not totally predictable, but my pointer keeps resetting to coordinates, 227x327.  The mouse is unusable.

### How to reproduce

Err... unsure.

**Comment by sl33nyc** [comment]
I'm temporarily switching over to Gnome, which doesn't exhibit the same problem.

**Comment by vaxerski** [comment]
that doesn't sound like it can happen without user input. Is this repro on the default config?

Maybe it's a misbehaving app?

**Comment by sl33nyc** [comment]
I'll start disabling scripts and see if things improve.

**Comment by sl33nyc** [comment]
I had been meaning to switch from Manjaro to ArchLinux, so after a fresh install of `hyprland-git` on barebones ArchLinux, I present to you:

https://photos.app.goo.gl/cYWtRG1TfnB5CkFaA

Start watching from 20s+.  The mouse pointer jumps and sticks to the upper left hand window (Firefox).

**Comment by vaxerski** [comment]
```ini
misc {
    focus_on_activate = false
}
```
?

**Comment by sl33nyc** [comment]
No change - same behavior.

Let me know if there's any data/logging that I can provide.  I can reluctantly live with Gnome for now.  :P

**Comment by vaxerski** [comment]
this definitely looks like focus on activate. 

Can you provide a log? https://wiki.hyprland.org/Configuring/Variables/#debug -> set disable_logs = false and repro

**Comment by sl33nyc** [comment]
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14581311/hyprland.log)

I also noticed in system logs:
```
[Tue Mar 12 22:50:20 2024] Hyprland[8430]: segfault at 378 ip 000055f4e97292c4 sp 00007ffde2dec020 error 4 in Hyprland[55f4e9645000+1b9000] likely on CPU 2 (core 2, socket 0)
```

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/09520d34-40e6-429f-87be-9cb447d7516f)
log 404?

**Comment by sl33nyc** [comment]
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14581787/hyprland.log)

**Comment by sl33nyc** [comment]
Hmm... Github's "Paste, drop of click to add files" link below doesn't work for me?  Anyway, https://gist.github.com/sl33nyc/2c1a173c41e07db29d3e599dc0664c77

**Comment by vaxerski** [comment]
I can't see firefox in that log, which window was the cursor jumping to?

**Comment by sl33nyc** [comment]
The window itself doesn't matter.  The mouse cursor was always jumping towards the upper left window.

**Comment by sl33nyc** [comment]
:man_facepalming: Thank you for humoring me, but yes, I'm an idiot!

It turns out that I had a USB drawing tablet input peripheral that was generating some noise input.  I've had it plugged in and sitting idle for a long time, so it's still curious that Hyprland (and not Gnome) started picking up input only after it being upgraded from 0.35ish to latest `-git`.  As far as I'm aware, I have never touched the input sensitivity and currently don't have a non-zero input sensitivity, so it's still odd IMHO.

Going to close this as this feels 95+% user error and maybe 5% subtle, but aberrant constant change.

**Comment by vaxerski** [comment]
IIRC the input mode changed to support relative and stuff or something if I'm not mistaken, maybe that
