### ISSUE TITLE
Windows won't release focus

### ISSUE THREAD

**Issue by thomascft** [hyprwm/Hyprland#507]
When playing Genshin Impact, I've noticed that it won't release focus when switching workspaces unless I open a menu that doesn't take raw input like the pause menu. This same issue is present in other games that capture the mouse to aim. In some cases the fix was to open a terminal in the same workspace causing the focus to be released and the ablility to switch to other clients. Upon reentering the  game the focus is held unless I open another terminal causing the focus to shift.

**Comment by vaxerski** [comment]
It's an XWayland issue unfortunately. I am trying to get this fixed too man...

**Comment by thomascft** [comment]
All good, thought I'd just report it. I found that workaround so I should be good.

**Comment by vaxerski** [comment]
try with 8e5985d70e3370bc2c6155b58488499d5f6f067d

**Comment by thomascft** [comment]
Works great! You're super quick with these fixes. Sorry I couldn't do much to help, I don't know cpp.
