### ISSUE TITLE
hyprland.cong at line 1: Invalid config file

### ISSUE THREAD

**Issue by egemenc21** [hyprwm/Hyprland#5071]
### Hyprland Version

<details>  <summary>System/Version info</summary>

```sh
os-release: NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

</details>

### Bug or Regression?

Bug

### Description

I am having a config error after updating 0.36. Line 1 is looking fine to me but it looks like there's an error and I couldn't figure it out

`#AUTOGENERATED HYPR CONFIG.
#PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
#OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

monitor=,preferred,auto,auto
monitor=eDP-1,1920x1080@60,0x0,1
monitor=HDMI-A-1,1920x1080@60,1920x0,1`

here are the first few lines of my hyprland.conf file

### How to reproduce

d

### Crash reports, logs, images, videos

![20240311_21h50m05s_grim](https://github.com/hyprwm/Hyprland/assets/112320683/9563a51e-7c71-4456-b622-4dce299a496c)

**Comment by vaxerski** [comment]
please attach your config as a file

**Comment by egemenc21** [comment]
> please attach your config as a file

[hyprland (copy).txt](https://github.com/hyprwm/Hyprland/files/14570295/hyprland.copy.txt)

**Comment by Ligthiago** [comment]
Seems like your file encoded like `UTF-8 with BOM`, which is not working correctly, dunno. Save it like just `UTF-8` or create new file and copy content from your file to it.

```
❱ cmp -b /home/ligthiago/Downloads/hyprland.conf /home/ligthiago/.config/hypr/hyprland.conf
/home/ligthiago/Downloads/hyprland.conf /home/ligthiago/.config/hypr/hyprland.conf differ: byte 1, line 1 is 357 M-o  43 #
```

Anyway, it's seems like hyprland not okay with byte order mark

**Comment by vaxerski** [comment]
as above, anything other than ascii / utf8 is not supported

**Comment by egemenc21** [comment]
> Seems like your file encoded like `UTF-8 with BOM`, which is not working correctly, dunno. Save it like just `UTF-8` or create new file and copy content from your file to it.
> 
> ```
> ❱ cmp -b /home/ligthiago/Downloads/hyprland.conf /home/ligthiago/.config/hypr/hyprland.conf
> /home/ligthiago/Downloads/hyprland.conf /home/ligthiago/.config/hypr/hyprland.conf differ: byte 1, line 1 is 357 M-o  43 #
> ```
> 
> Anyway, it's seems like hyprland not okay with byte order mark

thanks man I fixed it!!!! you were right my encoding was using utf-8 with rom
