### ISSUE TITLE
Cannot close app

### ISSUE THREAD

**Issue by kito30** [hyprwm/Hyprland#5077]
### Hyprland Version

So basically, im currently using onedriver-gui and that apps seems can not use kill active to close the windows
Hyprland ver: 0.35.0
System Information:
System name: Linux
Node name: KitoArchLinux
Release: 6.7.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

### Bug or Regression?

Bug

### Description

After run the app, cannot close the app, most apps like discord when you close it it goes to system tray but for onedrive-gui you cannot close the apps

### How to reproduce

Install onedriver-gui AUR ver. open it, cannot close

**Comment by Ligthiago** [comment]
It seems that it's expected behavior for this application, see https://github.com/bpozdena/OneDriveGUI/issues/104 . You should click on the quit button in the top left corner of the app, then it will give you a confirmation popup. Bad app design, not hyprland issue

**Comment by kito30** [comment]
I couldnt see the x nor the tiltle bar on the app. Therefore I couldnt close it

**Comment by kito30** [comment]
its seems that when I try to exec-once ondrivegui then I couldnt close it for some reason.

**Comment by kito30** [comment]
Found way to fix it is that make the apps startup to sleep few seconds before startup. However, could find a way to fix it completely

**Comment by vaxerski** [comment]
not a hyprlandi ssue
