### ISSUE TITLE
Loosing scroll functionality for mouse

### ISSUE THREAD

**Issue by JohRest** [hyprwm/Hyprland#5082]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: archwork
Release: 6.7.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080 Lite Hash Rate] [10de:2216] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I'm using the Microsoft arc mouse for hyprland. Suddenly I do have the effect that I loose the ability to scroll in windows by moving the middle mouse button up or down. I've connected my logitech mouse which has no problem. So I guess it's related to bluetooth and perhaps the mouse itself? I'm unable to tell where this effect comes from. I can use the logitech mouse instead, so it's no major issue. I've searched the issues, but couldn't find any similar issue. So I filed it...

### How to reproduce

Use microsoft arc mouse for a while. After some time the middle mouse button does no longer scroll active window. Regardless what applliction window that is.

**Comment by vaxerski** [comment]
please test on -git, you're on a very outdated version

**Comment by JohRest** [comment]
Hi, will do so. Thanks!
