### ISSUE TITLE
Freeze after plugging in monitor and moving mouse when no window is present (hardware cursor)

### ISSUE THREAD

**Issue by M4he** [hyprwm/Hyprland#5084]
### Hyprland Version

<details> <summary>System/Version info</summary>

Sorry, but my `hyprctl version` output is not showing any version (just empty strings), so here's the relevant NixOS flake input instead that I adopted [from the wiki](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/):

```
hyprland-flake = (import flake-compat {
  src = builtins.fetchTarball {
    url = "https://github.com/hyprwm/Hyprland/releases/download/v0.36.0/source-v0.36.0.tar.gz";
    sha256 = "1gvykjx4q88skdyvhgb18ld7h8k8fc1njsphb4z0hxhbwzqqbyga";
  };
}).defaultNix;
```

System:

- OS: NixOS 23.11 (Tapir)
- GPU: Intel CometLake-U GT2 UHD Graphics

</details>

### Bug or Regression?

Bug

### Description

I have been experiencing issues with Hyprland sessions freezing related to monitor connects and disconnects lately that seemed pretty random at first. But now I have been able to identify a scenario that triggers a freeze every single time for me.

Key requirements to trigger the freeze:

- `WLR_NO_HARDWARE_CURSORS=0` or variable unset
- no visible window on the current workspace
- external monitor connect and subsequent mouse movement towards that monitor

Note that if there is any open window on the internal screen before connecting the external monitor, the issue does *not* happen. Only if the workspace is empty.
Also, I have not been able to reproduce this scenario with `WLR_NO_HARDWARE_CURSORS=1` set either (Intel GPU).

My monitor configuration is pretty simple:

```
monitor=eDP-1,1920x1080,auto,1.25
monitor=,preferred,auto,auto
```

Aside from the reproduction scenario, the information situation is pretty poor on my end currently, I apologize. So far I haven't been able to squeeze any log messages out of Hyprland related to the freezes. If there's anything I can do to provide more relevant debug information, I'd appreciate your guidance.

### How to reproduce

1. Have `WLR_NO_HARDWARE_CURSORS=0` set.
2. Start Hyprland, either via a display manager (e.g. GDM) or by simply typing `Hyprland` into the TTY.
3. Connect external monitor via any USB-C to HDMI adapter or dock.
4. Important: do not start any application on the workspace, i.e. have no visible window on the current workspace.
5. After the second monitor initializes, move the mouse to the right towards where the second monitor begins as if you wanted to move the cursor to the second monitor.

(As weird as it sounds, the mouse movement is crucial as the freeze only triggers when approaching the second screen with the mouse after connecting it.)

The following happens:

- About 1cm from the right edge of the internal screen (it's the same horizontal distance every time), the cursor stops moving and Hyprland freezes.
- Hyprland does not react to any input. Switching to TTY via e.g. Ctrl + Alt + F2 does not work as input is locked.
- After pressing the magic SysRq key `r` (Alt + PrtScn + R) to ungrab the input, it is possible to switch to a different TTY and execute `pkill -9 Hyprland` (SIGTERM is insufficient) to kill it and regain session control.

### Crash reports, logs, images, videos

Unfortunately, even with `HYPRLAND_LOG_WLR=1` no log messages are recorded by Hyprland around the freeze at all.

**Comment by vaxerski** [comment]
enable logging (see https://wiki.hyprland.org/Configuring/Variables/#debug ) for the logs and send a log.

Also, nvidia?

Also, have you tried -git?

**Comment by M4he** [comment]
> enable logging (see https://wiki.hyprland.org/Configuring/Variables/#debug ) for the logs and send a log.

Thanks for the hint. I've set `enable_stdout_logs=true` and now I can see the following being spammed to the TTY I start Hyprland from after killing it:

```
[backend/drm/atomic.c:250] Failed to acquire FB for plane 89
[backend/drm/atomic.c:250] Failed to acquire FB for plane 89
[backend/drm/atomic.c:250] Failed to acquire FB for plane 89
[backend/drm/atomic.c:250] Failed to acquire FB for plane 89
[backend/drm/atomic.c:250] Failed to acquire FB for plane 89
[backend/drm/atomic.c:250] Failed to acquire FB for plane 89
...
```

> 
> Also, nvidia?
> 

Just the "Intel CometLake-U GT2 UHD Graphics" as mentioned in the report. It's not hybrid graphics or anything.

> Also, have you tried -git?

Not yet, will try to!

**Comment by M4he** [comment]
Cannot reproduce on latest git version. Sorry for the noise.
