### ISSUE TITLE
Empty error bar?

### ISSUE THREAD

**Issue by nxy7** [hyprwm/Hyprland#5086]
### Hyprland Version

Hyprland, built from branch  at commit v0.36.0  ().
Date: 2024-02-05
Tag:

flags: (if any)

### Bug or Regression?

Bug

### Description

For whatever reason after updating my NixOS I have empty red error bar on my screen. `journalctl` doesn't show any errors and I don't know how to troubleshoot that issue :S

![image](https://github.com/hyprwm/Hyprland/assets/32909532/b0006246-b12b-4b5c-9936-b8e36cb3142d)

Any ideas what I can do to look for a potential cause of this?

### How to reproduce

No clue

**Comment by vaxerski** [comment]
probably a weird error in the config I guess, have you tried the default config? if that fixes it, I guess comment out parts of your config until you find it

**Comment by Ligthiago** [comment]
Did you updated from 0.35.0? I check your dots, this is changed in 0.36.0:

```
device:epic-mouse-v1 {
   sensitivity = -0.5
}
```
Check how it configured now: https://wiki.hyprland.org/0.36.0/Configuring/Keywords/#per-device-input-configs

**Comment by nxy7** [comment]
Okay, so device section of my config was indeed the issue (thanks @Ligthiago). Should I leave this issue open? I don't think the intended behavior is to leave empty error bar.

**Comment by Ligthiago** [comment]
I don't have an empty error bar with your config, so I guess it fixed in git

**Comment by nxy7** [comment]
If that's not reproducible then I'll close the issue. Thanks for help again, I should track release notes more closely before making an issue :P
