### ISSUE TITLE
Some applications freeze when GPU memory usage comes to 100%

### ISSUE THREAD

**Issue by epitaphial** [hyprwm/Hyprland#5095]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.7.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107GL [Quadro P620] [10de:1cb6] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Some applications (e.g. Firefox, VMware, alacrity) freeze up when the GPU memory is full. Typing or clicking in these apps produces an effect, but the change no longer appears on the screen. Close some more apps and let the GPU memory lower to unfreeze.

### How to reproduce

Especially when using applications that take up more GPU memory, such as browsing videos and PDFs, there will be frequent occurrences.

**Comment by fufexan** [comment]
Can you try updating to the latest Hyprland first and seeing if it happens anymore?

**Comment by tchofy** [comment]
Not op but I'm on fa886d8b11b5d38f9fa12debcdd1f992b258406a and can replicate this, have been able for a while, though it's on nvidia, so I just cope with such issues.

**Comment by epitaphial** [comment]
> Can you try updating to the latest Hyprland first and seeing if it happens anymore?

Thanks, I just realized that the official arch hyprland package is outdated, I'll try installing the latest version manually!

**Comment by epitaphial** [comment]
> Not op but I'm on [fa886d8](https://github.com/hyprwm/Hyprland/commit/fa886d8b11b5d38f9fa12debcdd1f992b258406a) and can replicate this, have been able for a while, though it's on nvidia, so I just cope with such issues.

Thank you very much, so is it because the wlroot version is too old, I decided to give it a try!

**Comment by epitaphial** [comment]
> Can you try updating to the latest Hyprland first and seeing if it happens anymore?

I used version 36.0 from commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8, but the issue is still there. I suspect it's an incompatibility issue with Nvidia graphics cards

**Comment by vaxerski** [comment]
nvidia issue
