### ISSUE TITLE
Random Crashing when opening Discord/Telegram

### ISSUE THREAD

**Issue by LivacoNew** [hyprwm/Hyprland#5096]
### Hyprland Version

<details> <summary>System/Version info</summary>

Using the Arch repo;
```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```
Haven't yet tested with latest git.

</details>

### Bug or Regression?

Bug

### Description

Randomly upon opening Discord/Telegram, my DE has a chance of just crashing. It's quite inconsistent, almost random. Has been going on for a couple weeks or so now.

No idea what could be causing this, as my Desktop running the same version works just fine.

### How to reproduce

Open a random program, again I've gotten it with Discord and Telegram but doubt it's limited to those two.
Only about a 20% chance of crash and even then depends on your hardware as stated above with my Desktop working fine.

### Crash reports, logs, images, videos

[hyprlandCrashReport803.txt](https://github.com/hyprwm/Hyprland/files/14584644/hyprlandCrashReport803.txt)

**Comment by fufexan** [comment]
Please update Hyprland first.

**Comment by LivacoNew** [comment]
Just had it reoccur on 0.37.1, again from the official arch repo.
```
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)
```

[hyprlandCrashReport773.txt](https://github.com/hyprwm/Hyprland/files/14719654/hyprlandCrashReport773.txt)

**Comment by vaxerski** [comment]
trashed backtrace, try `bt -full` from gdb

**Comment by LivacoNew** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007171b9526e66 in epoll_wait () from /usr/lib/libc.so.6
(gdb) c
Continuing.
bt -full
[Detaching after fork from child process 32858]
[New Thread 0x7171860006c0 (LWP 33031)]
[Thread 0x7171860006c0 (LWP 33031) exited]
[Detaching after fork from child process 38735]

Thread 1 "Hyprland" received signal SIGSEGV, Segmentation fault.
0x00007171b9d77ae0 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
(gdb) bt -full
#0  0x00007171b9d77ae0 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#1  0x00007171b9d782d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#2  0x00005d3af70829e9 in CCompositor::startCompositor() ()
#3  0x00005d3af70676e7 in main ()
(gdb) 
```
From opening Telegram again.

**Comment by vaxerski** [comment]
wotdafoq

**Comment by vaxerski** [comment]
can you try ASan, explained at the bottom here: https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by LivacoNew** [comment]
> can you try ASan, explained at the bottom here: https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

Naturally, unable to replicate now, even on my normal Hyprland. Will try again tomorrow when I'm a bit more awake.

**Comment by LivacoNew** [comment]
Gonna call this stale, as I've not had any problems since my last reply lol.
