### ISSUE TITLE
Game on full-screen is frozen when tearing is enabled

### ISSUE THREAD

**Issue by marcosnigp1** [hyprwm/Hyprland#5097]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: inspiron3583
Release: 6.7.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Whiskey Lake-U GT1 [UHD Graphics 610] [8086:3ea1] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

After tearing is manually enabled with:

```
general {
    allow_tearing = true
}

env = WLR_DRM_NO_ATOMIC,1
```
Some game's display just freeze, but is still active. 

### How to reproduce

1. Enable tearing manually.
2. Open a game, turn off VSync in it, and make sure it is running full-screen.
3. Observe how the display is frozen, but the game is still running normally.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/126048022/9fd05df3-df9b-4599-a6be-8455169246fa

**Comment by fufexan** [comment]
This happens to a portion of the users. It is the driver's fault, not Hyprland's. Nothing that we can do.

**Comment by marcosnigp1** [comment]
> This happens to a portion of the users. It is the driver's fault, not Hyprland's. Nothing that we can do.

Weird, it was working before with no issues, just recently this bug happens when I updated the system.

**Comment by fufexan** [comment]
I had that happen as well after a system update. It's unfortunate.

**Comment by vaxerski** [comment]
IIRC some kernel update broke tearing on intel

**Comment by vaxerski** [comment]
yes amd doesn't support tearing on non-legacy

**Comment by nonetrix** [comment]
> yes amd doesn't support tearing on non-legacy

Please consider adding this to the wiki it's somewhat misleading as it is

**Comment by nonetrix** [comment]
https://github.com/hyprwm/hyprland-wiki/pull/596

**Comment by jakobkukla** [comment]
I think this should be reopened? See https://gitlab.freedesktop.org/drm/amd/-/issues/3271

**Comment by Hubro** [comment]
I have the exact same issue with an Intel iGPU (`Intel Corporation Meteor Lake-P [Intel Arc Graphics]`).

[According to Hyprland's wiki](https://wiki.hyprland.org/Configuring/Tearing/#apps-that-should-tear-freeze), my GPU driver simply doesn't support tearing.

However, a gentleman on [this bug report](https://gitlab.freedesktop.org/drm/amd/-/issues/3271#note_2473684) says:

> Kwin 6.1.1.2 with a backported merge request seems to work great. I'm going to close this issue as it appears it is not an issue with drm but rather with individual compositors that implement tearing.

And closed the issue, making it sound like it's a wlroots issue.

But, a week later, [another gentleman posted](https://gitlab.freedesktop.org/drm/amd/-/issues/3271#note_2473896):

> wlroots appears to need these two kernel patches, or a combination thereof:
>
> https://lore.kernel.org/dri-devel/20240629152204.666748-1-contact@emersion.fr/T/#u
> https://lore.kernel.org/dri-devel/20240622170951.738735-1-andrealmeid@igalia.com/
> 
> Rather, it needs the condition check to be a combination of (pseudo conditions):
> 
> `(!= prop_fb_id && != prop_in_fence_id && != prop_fb_damage_clips) || != PRIMARY`
> 
> Edit: This condition is GPU agnostic, the change applies to the DRM subsystem in general, not to a specific GPU driver.

Which makes it sound like it's *not* a specific GPU driver issue and *not* an issue with wlroots :thinking: I'm confused.

**Comment by nonetrix** [comment]
I am not sure if it's still a issue on AMD I haven't tried, might be able to remove thing that says you can't use it on AMD

**Comment by nonetrix** [comment]
Also as of now Hyprland doesn't use wlroots on the git version!

**Comment by ardishko** [comment]
I'm having this issue and my GPU drivers support tearing. I'm on the official AMD drivers and my card is a 6900XT. Tearing works on KDE Plasma (tested), so It probably is a Hyprland issue.
