### ISSUE TITLE
Floating apps are too big on the screen

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#5098]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
hyprctl systeminfo 

Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.6.21-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 06 Mar 2024 16:59:55 +0000

GPU information: 
35:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 0a) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

</details>

### Bug or Regression?

Bug

### Description

when a make a tiled window fullscren with the keybind, itsead of being small, its big as the entire screen, like its fullscreen, and with right click and super button, i need to make it small again. 

### How to reproduce

like how i said.

### Crash reports, logs, images, videos

this is blueman manager for example, from tiling to floating its bigger but not smaller like it used to be in previous versions. 

![image](https://github.com/hyprwm/Hyprland/assets/118976333/ae783f51-490e-47a7-a3d9-386978f4bf86)

**Comment by fufexan** [comment]
The app sizes itself, and Hyprland respects its size. This is not a bug.

**Comment by Ligthiago** [comment]
Anyway, on git, when new windows become float - they stay about the same size as they were when tiled, so old version issue. The min/max size also becomes dynamic, which is very useful in this type of workflow.
