### ISSUE TITLE
Window groups is stacked on top of each other if you move a window into it

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#510]
1. create 3 windows
2. make the left/right two windows a group
3. move the right window left(or opposite)
4. enjoy your confusion
the right window is stacked on top of the two left windows while not being in the group
![image](https://user-images.githubusercontent.com/68589851/184151006-ff22fbfc-8553-46c7-8913-42e9b8ac8c97.png)

**Comment by vaxerski** [comment]
yeah groups need to be redone

**Comment by vaxerski** [comment]
check with c319a2aba9cf993d26af7af66a8632aad6a83d1b

redone groups

**Comment by KyleUltimate** [comment]
it's sorta fixed, the specific way that I described in this issue is in fact fixed.
Managed to reproduce it like this.
![image](https://user-images.githubusercontent.com/68589851/184473388-10a94596-f5af-426d-93b4-f88ecffabebe.png)
make the left top two groups, drag the bottom one into the top group, close the right window, and there you go

**Comment by vaxerski** [comment]
fixado in 214c2c7b1c0182594a07a2c5ac7d99e9d7b5fcb3 he he ha ha
