### ISSUE TITLE
Hyprland is very laggy when running in own session

### ISSUE THREAD

**Issue by julikober** [hyprwm/Hyprland#5105]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
```

</details>

### Bug or Regression?

Bug

### Description

When i start Hyprland in a session, the fps barely go above 20, but when i launch Hyprland inside of Gnome i get stable 60 fps. I didn't find any errors in the logs, so currently i do not have anything else to show.

Specs:
- HP Spectre x360
- Intel i7 cpu
- Nvidia gpu (currently not used, even disabled)
- Arch (btw)

### How to reproduce

Start Hyprland with the command 'Hyprland' in tty.

**Comment by tharrmeehan** [comment]
does updating to v0.36.0 fix anything?

**Comment by julikober** [comment]
It actually does, but not completely. When i have an empty workspace, the fps reach up to 60 fps, but as soon as i open a program, for example alacritty, the fps drop down to 30 or below. So it is better as before, but i would not consider it fixed.

**Comment by vaxerski** [comment]
sounds like your gpu not keeping up. We don't artificially boost your clocks and igpus are known to not do that out of their own volition, meaning lag.
