### ISSUE TITLE
Hyprland failed to read config with comments starting with "#"

### ISSUE THREAD

**Issue by arcatva** [hyprwm/Hyprland#5107]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
hyprland-git 0.36.0.r107.3e67ee0f-1 in AUR repo
Linux arch-sf314 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland failed to read config with comments starting with "#"

I have config goes like `#################### It just works™ keybinds ###################
## Volume
bindl = ,XF86AudioMute, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%
bindl = Super+Shift,M, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%
bindle=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindle=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-`

When the Hyprland starts, it pops out a window full of errors indicating it can not read the lines starting with '#'.

I didnt encounter this issue in build 0.36.0.r93.335506d5-1 and build 0.35.0-2

### How to reproduce

Use the latest build from AUR or hyprland-git 0.36.0.r107.3e67ee0f-1. Add lines starting with '#' in hyprland.conf

**Comment by Ligthiago** [comment]
https://github.com/hyprwm/Hyprland/issues/4975

Add space between first and second hash

**Comment by arcatva** [comment]
@Ligthiago That is what I want. Thx!
