### ISSUE TITLE
Question about config file comment format.

### ISSUE THREAD

**Issue by ticks-tan** [hyprwm/Hyprland#5109]
I haven't used hyprland for a while now, why is the config file comment only now:
```
# xxx
```
and can't be:
```
## `# xxx
```

I used the previous config file and hyprland reported a bunch of errors because of the comment format, after changing it, it worked fine!

**Comment by vaxerski** [comment]
because since the migration to hyprlang, `##` escapes are treated properly as `#`: https://wiki.hyprland.org/Configuring/Configuring-Hyprland/#comments

**Comment by ticks-tan** [comment]
Sorry, I didn't read the wiki, thanks!
