### ISSUE TITLE
Hyprland crashes on start, starting on commit: c3882bb

### ISSUE THREAD

**Issue by nine7nine** [hyprwm/Hyprland#5111]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
N/A - I cant start hyprland to run hyprctl. it immediately crashes.

My version is commit: 3e67ee0f5f66c74c0a0bd4f797361fd100c2e2d2 (latest), but the problems begin with commit: c3882bb83240b602277f2d22f21d71690531f62e
```

</details>

### Bug or Regression?

Bug

### Description

Starting with commit: c3882bb83240b602277f2d22f21d71690531f62e I can no longer run hyprland at all. it crashes immediately on start (from TTY or GDM).

I manually bisected; rebuilding and running hyprland - everything works fine until the above commit.

I've also tried rebuilding hyprcursor and any related hyprland dependencies, which didn't solve or change anything.

### How to reproduce

On my Archlinux system I am using Hyprland+Aylur's Gtk Shell. ~ Everything  works correctly with commit: e7a5db4852d654596e554b9cdeaa2694b346ee03 , but no further; it simply crashes if i build from any newer commit.

Commit: c3882bb83240b602277f2d22f21d71690531f62e is the culprit, as i manually bisected; building / testing until Hyprland crashes / stopped working... I also tried using the auto-generated hyprland.conf - in case it was a problem with my config or AGS related, but it still crashes. 

My only solution  is to simply roll back to commit: e7a5db4852d654596e554b9cdeaa2694b346ee03

### Crash reports, logs, images, videos

[hyprlandCrashReport56146.txt](https://github.com/hyprwm/Hyprland/files/14606332/hyprlandCrashReport56146.txt)

Hopefully, the crash report is useful here.

**Comment by vaxerski** [comment]
that was fixed in libhyprcursor, update it.

**Comment by nine7nine** [comment]
my hyprcursor-git package should be up-to-date. commit: 1761f6ce

All oy my hyprland related packages seem to be up-to-date, and have been rebuilt today.

**Comment by vaxerski** [comment]
have you installed any hyprcursors?

Can you build in debug, launch hyprland with `HYPRLAND_NO_CRASHREPORTER=1` and provide the `bt -full` from gdb?
