### ISSUE TITLE
flicker-resizing

### ISSUE THREAD

**Issue by znd4** [hyprwm/Hyprland#5112]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: t470
Release: 6.6.21
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:48:45 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240312.0ad13a6"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Non-fullscreened windows flicker-resize.

I've seen a few issues that look similar to this, but I don't think they're quite the same. This happens with mouse-resizing enabled and disabled, and with `master` and `dwindle` layouts.

#### necessary steps

1. Install [Clipboard](https://github.com/Slackadays/Clipboard)
2. Open kitty (in a default hyprland configuration)
3. `echo foo | cb`

watch screens flicker

#### Long Reproduction

If you want to get as close to my environment as possible without actually purchasing a specific 5+ yr old computer:

1. Fresh nixos install
2. `export NIX_CONFIG="extra-experimental-features=flakes,nix-command`
3. `nix run nixpkgs#git -- clone https://github.com/znd4/nixfiles`
4. copy hardware-configuration.nix to `nixfiles/nixos/machines/t470.nix`
5. `cd nixfiles && sudo nixos-rebuild switch --flake ".#t470"
6. `systemctl reboot` --> login
7. `cd ~/nixfiles && home-manager switch --flake .`
8. `systemctl reboot` --> login
9. `Super+R` to open the launcher and then launch kitty
10. `echo foo | cb`

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/17930657/1bffc3fb-9d51-4eb5-81d9-eec6916f2e46

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14606803/hyprland.log)

**Comment by vaxerski** [comment]
have you tried with the default config? I've never seen this.

**Comment by znd4** [comment]
I'll try that. Assuming it'll be generated automatically when running from a TTY?

**Comment by vaxerski** [comment]
should be, dunno if nix wont fuck that up

**Comment by znd4** [comment]
I don't see it so far with the default config, although I don't see a fullscreen toggle option. I'll try adding a fullscreen toggle and a special workspace section to the default config and see if I'm able to reproduce this

**Comment by znd4** [comment]
Okay, the fullscreen toggle doesn't seem to reliably reproduce it, but what *does* is breaking the hyprland config -- e.g. adding

```
bind = a, a, a, a
```

Then waiting for hyprland to reload (or `hyprctl reload`), revert back and `hyprctl reload` again. At this point, hyprland is stuck in the flicker-resizing state

**Comment by vaxerski** [comment]
can you add clear repro instructions? I can't make out exactly what you are doing

**Comment by znd4** [comment]
Sorry, it isn't *super* helpful, but I just updated based on what I've found so far.

It's triggered by deleting a line in neovim, but specifically with my configuration -- doing it in `nvim --clean` doesn't work. I can binary search through my configuration until I find the offending content, but maybe I should first try to capture a full video of it starting? (difficult because wf-recorder seems to only record a few seconds before crashing)

**Comment by vaxerski** [comment]
sounds like a problem on your end tho

**Comment by znd4** [comment]
And to clarify, once it's in that state, it doesn't require any action on my part - it just keeps flickering like that as long as there isn't a full screen window in the current workspace

**Comment by znd4** [comment]
Potentially - it seems strange that one window resizing causes every window to start flickering like that (even after the original application is closed)

**Comment by znd4** [comment]
@vaxerski , got it to something a lot simpler, which might be reproducible on other systems:

1. Install [Clipboard](https://github.com/Slackadays/Clipboard)
2. Open kitty (in a default hyprland configuration) + make sure that `wl-copy` and `wl-paste` are installed
3. `echo foo | cb`

This is being triggered by some behavior in `cb`, although I don't know if the issue is graphical (it does something in the terminal emulator's rendering that's problematic) or the way it's using wayland's clipboard API

**Comment by znd4** [comment]
Ah, [this](https://github.com/Slackadays/Clipboard/issues/106) is definitely the issue -- `cb` creates and then destroys a window, which triggers this "everything-flickering" state

**Comment by vaxerski** [comment]
likely it's opening a window, and by default it becomes the fullscreen window IIRC. Yeah, not a hyprland bug then, as suspected

**Comment by znd4** [comment]
Is this an upstream Wayland issue? Opening and closing a window shouldn't break a window manager (IMO)

**Comment by vaxerski** [comment]
no, it's in your configs, or cb itself, is entering a loop where it constantly opens a window.

**Comment by vaxerski** [comment]
just checked, yes. Clipboard constantly opens and closes a window. This is their bug, not mine.

**Comment by Slackadays** [comment]
This is a Wayland bug because they refuse to implement a real clipboard system because of """SeCuRiTy""" so you either need to do this ugly window hack or implement an unofficial unsupported protocol
