### ISSUE TITLE
Redraw artifacts / rendering glitches on some Wayland applications

### ISSUE THREAD

**Issue by M4he** [hyprwm/Hyprland#5113]
### Hyprland Version

<details> <summary>System/Version info</summary>

Hyprland: git [@3e67ee0f5f66c74c0a0bd4f797361fd100c2e2d2](https://github.com/hyprwm/Hyprland/tree/3e67ee0f5f66c74c0a0bd4f797361fd100c2e2d2) via [official NixOS Flake](https://github.com/hyprwm/hyprland-wiki/blob/27b9014e80ff216327c7a8cdec2a6ac638a31162/pages/Nix/Hyprland%20on%20NixOS.md?plain=1#L78-L93)

System:

- OS: NixOS 23.11 (Tapir)
- GPU: Intel CometLake-U GT2 UHD Graphics

</details>

### Bug or Regression?

Regression

### Description

Ever since updating from v0.36.0 release to the git version ([@3e67ee0](https://github.com/hyprwm/Hyprland/tree/3e67ee0f5f66c74c0a0bd4f797361fd100c2e2d2)), I'm experiencing weird redraw artifacts / rendering glitches in some Wayland-native applications.

Notable examples are:

- KWrite (Qt5): the word completion suggestion popup often leaves borders or entire parts of itself behind until the covered areas are redrawn again
- Thunderbird calendar new event dialog: combobox dropdown menus will have their item's mouse hover highlight either not updated at all or updated delayed; former highlight states of date or time selections will not vanish correctly and flicker
- popup tooltips on some applications will leave parts of them behind

Both applications running natively in Wayland mode confirmed via `hyprctl clients`. The funny thing about Thunderbird is that the main window does not show those symptoms at all, only the calendar entry dialog (or for example the calendar reminder popup). See the screen recordings below.

### How to reproduce

For KWrite:

1. Make sure auto completion is enabled in the editing settings of KWrite.
2. Type some text in KWrite.
3. Start repeating words from already written text, so that the auto completion popups start appearing.
4. Popups that disappear will leave rendering artifacts behind.

For Thunderbird:

1. Open Thunderbird's calendar view.
2. Click on "New Event".
3. Attempt to select start and end dates, times and use the dropdowns for configuring event repetition and reminder values.
5. Using the mouse to hover and select elements of those UI widgets should show the problem quite visibly.

#### KWrite

Note the border lines that the word suggestion popup leaves behind:

[kwrite.webm](https://github.com/hyprwm/Hyprland/assets/1408105/a3028b36-bdfe-4a60-b6c7-f9b9247cb37b)

#### Thunderbird calendar dialog

Redraw glitches on the new event calendar dialog in Thunderbird. Note that during OBS recording, the issue is exaggerated greatly. Normally, it would just tend to not update the selection highlights at all properly or previous highlights would keep flickering on and off. When OBS is running it gets really funky:

[tb_event_dialog.webm](https://github.com/hyprwm/Hyprland/assets/1408105/5161dfe0-96f5-4d8c-afc6-fc0c43a63fd4)

#### Thunderbird main window (not affected)

In contrast, the main window of Thunderbird is rendering just fine:

[tb_mainwindow.webm](https://github.com/hyprwm/Hyprland/assets/1408105/602def74-4cfa-4b28-86ee-a17f16e8e0cb)

**Comment by M4he** [comment]
Sorry, this should have been classified as regression, not bug. My bad. I adjusted the description.

**Comment by vaxerski** [comment]
how the fuck do I open that buggy calendar thing I dont use thunderbird

**Comment by vaxerski** [comment]
for number 1 see above commit

**Comment by M4he** [comment]
> how the fuck do I open that buggy calendar thing I dont use thunderbird

1. Open Thunderbird.
2. If you don't have an email account set up, simply cancel the "Account Setup" wizard that appears. You can use basic functionality without any email setup.
3. Click the "Calendar" tab right below the primary toolbar that looks like a CSD.
4. Within the calendar tab, click the big blue "+ New Event" button on the top left.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/30e5e712-defa-4d2d-9d8c-926537dd0757)
cant new event

**Comment by vaxerski** [comment]
oh, new calendar first

**Comment by vaxerski** [comment]
got it, thanks.

**Comment by vaxerski** [comment]
oops

**Comment by vaxerski** [comment]
alright everything should be fixed, please check

**Comment by M4he** [comment]
> alright everything should be fixed, please check

On 045c3fbd854090b2b60ca025fedd3e62498ed1ec now. Seems to fix KWrite popup borders as well as Thunderbird dialog UI widgets for me.

@vaxerski you are awesome! Many thanks.
