### ISSUE TITLE
Mouse cursor goes invisible on second monitor

### ISSUE THREAD

**Issue by Spectralpt** [hyprwm/Hyprland#5114]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: ArchLaptop
Release: 6.7.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I'm on a laptop with an intel CPU and and NVIDIA graphics card, because i didn't want to go through the hassle of doing all the configuration for the NVIDIA graphics card i just enabled the "switchable graphics" and that made hyprland able to start.
I connected my laptop to my second monitor trough HDMI and everything expect for the mouse rendering on that second screen works fine, the mouse is still there just invisible.

I took a look at the wiki and tried what's described on [Me cursor no render?](https://wiki.hyprland.org/FAQ/#me-cursor-no-render), despite the fact that I'm using the integrated graphics i figured that the NVIDIA card might be interfering somehow and was at least worth a try but did not work.

### How to reproduce

Connect a laptop on "switchable graphics" and an NVIDIA card to a second monitor.

**Comment by vaxerski** [comment]
disable hw cursors like the wiki says

**Comment by Spectralpt** [comment]
@vaxerski I thought i had already done that but because you told me to do it looked at my config again and only now noticed i had set it incorrectly in the config. Thanks for the help and sorry for bothering with such a simple issue.
