### ISSUE TITLE
Randomly kicked out to login screen

### ISSUE THREAD

**Issue by tesioai** [hyprwm/Hyprland#5118]
### Hyprland Version

```sh
Hyprland, built from branch main at commit 3e67ee0f5f66c74c0a0bd4f797361fd100c2e2d2 dirty (events: ignore setTitle when title didn't change).
Date: Wed Mar 13 15:38:24 2024
Tag: v0.36.0-107-g3e67ee0f

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.7.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000


GPU information:
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Randomly everything closes and it goes to the login screen. Happened multiple times recently. Crash reports saying its a segfault.

### How to reproduce

Really not sure whats causing this, most recent happened when i tried to open a new terminal with ctrl + alt + t, dont know if its related. 

### Crash reports, logs, images, videos

[hyprlandCrashReport829.txt](https://github.com/hyprwm/Hyprland/files/14610218/hyprlandCrashReport829.txt)
[hyprlandCrashReport822.txt](https://github.com/hyprwm/Hyprland/files/14610219/hyprlandCrashReport822.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14610268/patch.txt)
try this

**Comment by tesioai** [comment]
I cant find the cpp file, only Popup.hpp in /usr/include/hyprland/src/, theres only header files there.

Im not compiling myself, im using the AUR package.

**Comment by tesioai** [comment]
I have compiled from source now with the changes, will update if it happens again.

**Comment by vaxerski** [comment]
sorry, went to sleep lol

**Comment by vaxerski** [comment]
cool, gonna commit and close. If this happens again, feel free to reopen

**Comment by tesioai** [comment]
> Hey I have the same problem. Could someone explain how to patch it step by step?

switch to hyprland-git, its fixed in the recent versions

**Comment by RicardoZanandrea** [comment]
> > Hey I have the same problem. Could someone explain how to patch it step by step?
> 
> switch to hyprland-git, its fixed in the recent versions

Hey, I'm having the same issues, I'm new to this hyprland world, how can I switch to hyprland-git?

**Comment by MathiasOdlund** [comment]
Hey, I'm having the same issues, I'm new to this hyprland world, how can I switch to hyprland-git?



> > > Hey I have the same problem. Could someone explain how to patch it step by step?
> > 
> > 
> > switch to hyprland-git, its fixed in the recent versions
> 
> Hey, I'm having the same issues, I'm new to this hyprland world, how can I switch to hyprland-git?

I am in the same boat bud.

**Comment by fufexan** [comment]
@RicardoZanandrea @MathiasOdlund depends on your distro. For example, on Arch you would need to remove Hyprland installed from the Arch repos with `pacman -Rs hyprland`, and install `hyprland-git` from the AUR manually or using a helper such as yay or paru.
