### ISSUE TITLE
Some GTK popups are displaying with a transparent background

### ISSUE THREAD

**Issue by revsuine** [hyprwm/Hyprland#5119]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: huaweilaptop
Release: 6.7.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hy3 by outfoxxed ver 0.1
```

</details>

### Bug or Regression?

Bug

### Description

Firstly I am not sure if this is a Hyprland bug or a more general Wayland bug or caused by something else. But I know I did not experience this on i3 or xfce on X11.

I have noticed that certain GTK popups render with a transparent background in Hyprland. So far, I have only seen this happen for the Libreoffice popups prompting you to save in an open source file format instead of .doc(x) or .ppt(x), and the final popup window when importing a private PGP key in Thunderbird.

### How to reproduce

# Libreoffice

Install `libreoffice-still 7.6.5-2` from the Arch repos (possibly works on other Libreoffice packages or building from source, but I've not checked—I have used this same package (but possibly a lower version) in X11 and not had this issue).

Open any .doc, .docx, .ppt, .pptx, etc. Attempt to save. Observe a transparent background in the popup.

# Thunderbird

Install `thunderbird 115.8.1-1` from the Arch repos (again, possibly an issue in other Thunderbird packages or building from source, but I've only used this package). Log in with an email address.

Go to Tools > OpenPGP Key Manager and import a private PGP key for one of your email addresses. Follow the instructions, accepting it as a personal key, and on the final screen (screenshot attached below), the bottom of the window is transparent.

### Crash reports, logs, images, videos

Note that in the below screenshots, the appearance of the background is expected behaviour for transparent backgrounds due to my blur settings, however the backgrounds are not expected to be transparent in the first place.

![20240315_12h17m12s_grim](https://github.com/hyprwm/Hyprland/assets/10424281/64facb51-7a46-4bf6-8b61-fc39b8690056)
![20240315_12h16m46s_grim](https://github.com/hyprwm/Hyprland/assets/10424281/c23d8280-0e0e-4fe4-85d1-92b5bc426831)
![20240315_12h12m24s_grim](https://github.com/hyprwm/Hyprland/assets/10424281/1560c360-fcdd-4b2a-914b-33871b54b4ba)

**Comment by Ligthiago** [comment]
I experienced this stuff in older versions, but don't see it for a while. Probably old version issue. 

![2024-03-15T16:48:00,815782374+04:00](https://github.com/hyprwm/Hyprland/assets/142721811/d9d4d7c7-e6c5-4af3-9011-5e74fda0c3cf)

**Comment by revsuine** [comment]
Switched to `libreoffice-fresh 24.2.1-3` and tried again. Same issue I'm afraid.

Thunderbird is up to date with the latest Arch package.

![20240315_13h11m14s_grim](https://github.com/hyprwm/Hyprland/assets/10424281/d13948c0-5aa6-4686-bc32-ed04166ec93d)

**Comment by Ligthiago** [comment]
No, I mean update Hyprland. 0.35.0 is kinda outdated

**Comment by vaxerski** [comment]
this is not a hyprland issue

**Comment by M4rti21** [comment]
i have the same problem, its not a GTK theme problem, as the popups show just fine on other X11 sessions, it does seem like a hyprland issue
(im on version 38.1-1 arch)

**Comment by vaxerski** [comment]
what about other _wayland_ sessions...

**Comment by M4rti21** [comment]
> this is not a hyprland issue
just tried it in sway, didnt happent there, i even tried with different gtk themes and the issue persisted on across themes (on hyprland)

**Comment by vaxerski** [comment]
forcergbx but I don't recommend that, rather fix your theme :P

**Comment by M4rti21** [comment]
ok tyty :D
