### ISSUE TITLE
Steam dropdowns don't work

### ISSUE THREAD

**Issue by dev11n** [hyprwm/Hyprland#512]
## Reproduce
1. Open Steam
2. Press on any navbar button, like `View`
3. Try and click on anything in the dropdown, it'll just vanish into nothing

This is on the latest commit btw.
## Video
https://streamable.com/wqf2dm
## Hacky fix
`windowrule=center,title:`

**Comment by vaxerski** [comment]
fixed with f4f049505076c95aaf613feb87e39a6cdf730dd2
