### ISSUE TITLE
means to adjust pseudo windows

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#5120]
### Description

Maybe I miss something on wiki, I try to get my pseudo terminal window a bit larger, I don't know hyprland shrink it based on what rule, anything I can alter.

**Comment by vaxerski** [comment]
you can use the resizewindow mouse bind on it. by default super + rmb

You can also use `resizewindow` for keybinds

**Comment by vincentaxhe** [comment]
> you can use the resizewindow mouse bind on it. by default super + rmb
> 
> You can also use `resizewindow` for keybinds

can I set rules about pseudo instead of adjust everytime

**Comment by vaxerski** [comment]
uhh you can use the `size` windowrule iirc?

**Comment by vincentaxhe** [comment]
how could I bind 'resizewindow' to keys, since wiki of dispatchers and binds did not reveal it.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/2d19a1b1-c068-4945-8062-96032e3bab87)
you sure?

**Comment by vincentaxhe** [comment]
I seen it ,just try to run "hyprctl dispatch resizewindowpixel 100 100, ^alacritty$" inside alacritty window ,nothing happens except of the comfortable 'ok'. 
'size' rule I use it only on floating window, I assume the rule will apply on newly opened window.

**Comment by vincentaxhe** [comment]
```
#!/bin/dash
state=$(hyprctl activewindow -j |jq -r ".floating")
if [ $1 = inc ];then
if $state ;then
hyprctl --batch 'dispatch resizeactive 32 18; dispatch moveactive -16 -9'
else
hyprctl dispatch resizeactive 32 18
fi
elif [ $1 = dec ];then
if $state ;then
hyprctl --batch 'dispatch resizeactive -32 -18; dispatch moveactive 16 9'
else
hyprctl dispatch resizeactive -32 -18
fi
fi
```
I use the script to resize floating windows avoid of tiled windows, I found It works on pseudo window too ,so add 'else' condition, but it resize the opposite way, hyprctl activewindow -j did not tell pseudo or not, why not? so I cannot make it works on only floating and pseudo window.

**Comment by vincentaxhe** [comment]
> how could I bind 'resizewindow' to keys, since wiki of dispatchers and binds did not reveal it.

I mean 'resizewindow' works only for mouse,isn't it? keyboard cannot trigger resize state and use up or right to resize it like 'xfwm' can do.

**Comment by vaxerski** [comment]
wdym works the opposite way? Seems to be working the same way on my end both floating and pseudo

**Comment by vincentaxhe** [comment]
```
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0

flags: (if any)

```
it's a bit outdated, but its the stable version on arch test-extra, I will stick to it.
I use the script, the same key makes a floating window get larger while get a pseudo window smaller,  but I will swap commands just fine.
is there any way to tell apart from a tiled pseudo window from a normal tiled window?

**Comment by vincentaxhe** [comment]
```
#!/bin/dash
state=$(hyprctl activewindow -j |jq -r ".floating")
if [ $1 = u ];then
	if $state ;then
	hyprctl --batch 'dispatch resizeactive 32 18; dispatch moveactive -16 -9'
	else
	hyprctl dispatch resizeactive 0 -16
	fi
elif [ $1 = l ];then
	if $state ;then
	hyprctl --batch 'dispatch resizeactive -32 -18; dispatch moveactive 16 9'
	else
	hyprctl dispatch resizeactive -16 0
	fi
elif [ $1 = r ];then
	if $state ;then
	hyprctl --batch 'dispatch resizeactive 32 18; dispatch moveactive -16 -9'
	else
	hyprctl dispatch resizeactive 16 0
	fi
elif [ $1 = d ];then
	if $state ;then
	hyprctl --batch 'dispatch resizeactive -32 -18; dispatch moveactive 16 9'
	else
	hyprctl dispatch resizeactive 0 16
	fi
fi
```
just use this to make resize floating or tiled window consistently
