### ISSUE TITLE
Hyprland received signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by fraschm1998** [hyprwm/Hyprland#5122]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Turn off monitor before bed, wake up turn it on and it's in TTY.

### How to reproduce

Turn off monitor before bed, wake up turn it on and it's in TTY.

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Well this is awkward.

Hyprland received signal 11 (Segmentation fault)

Version: 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8
Tag: v0.36.0

System info:
	System name: Linux
	Node name: epyc-main
	Release: 6.8.0-gentoo-x86_64
	Version: #1 SMP PREEMPT_DYNAMIC Mon Mar 11 21:22:20 EDT 2024

GPU:
	81:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3090] [10de:2204] (rev a1) (prog-if 00 [VGA controller])

os-release:
	NAME=Gentoo
	ID=gentoo
	PRETTY_NAME="Gentoo Linux"
	ANSI_COLOR="1;32"
	HOME_URL="https://www.gentoo.org/"
	SUPPORT_URL="https://www.gentoo.org/support/"
	BUG_REPORT_URL="https://bugs.gentoo.org/"
	VERSION_ID="2.15"
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x65) [0x560b5fae17b5]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x739) [0x560b5fa97d89]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x45) [0x560b5fa09e15]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /lib64/libc.so.6(+0x3c9d0) [0x7ff081d789d0]
		??
		??:0
	#4 | Hyprland(+0x12b3e1) [0x560b5fa533e1]
		unregisterVar(void*)
		??:?
	#5 | Hyprland(+0x2e195e) [0x560b5fc0995e]
		wlr_buffer_try_from_resource
		??:?
	#6 | Hyprland(_ZN7CWindow14updateToplevelEv+0x22) [0x560b5fa55212]
		CWindow::updateToplevel()
		??:?
	#7 | Hyprland(_ZN6Events23listener_setTitleWindowEPvS0_+0x201) [0x560b5face1d1]
		Events::listener_setTitleWindow(void*, void*)
		??:?
	#8 | Hyprland(_Z13handleWrappedP11wl_listenerPv+0x5b) [0x560b5faf87fb]
		handleWrapped(wl_listener*, void*)
		??:?
	#9 | /usr/lib64/libwayland-server.so.0(wl_signal_emit_mutable+0x7c) [0x7ff0828ac24c]
		??
		??:0
	#10 | /usr/lib64/libffi.so.8(+0x7aee) [0x7ff082325aee]
		??
		??:0
	#11 | /usr/lib64/libffi.so.8(+0x6bf1) [0x7ff082324bf1]
		??
		??:0
	#12 | /usr/lib64/libffi.so.8(ffi_call+0x12e) [0x7ff08232552e]
		??
		??:0
	#13 | /usr/lib64/libwayland-server.so.0(+0xe2d4) [0x7ff0828b02d4]
		??
		??:0
	#14 | /usr/lib64/libwayland-server.so.0(+0x93a3) [0x7ff0828ab3a3]
		??
		??:0
	#15 | /usr/lib64/libwayland-server.so.0(wl_event_loop_dispatch+0xd2) [0x7ff0828ae302]
		??
		??:0
	#16 | /usr/lib64/libwayland-server.so.0(wl_display_run+0x25) [0x7ff0828abc25]
		??
		??:0
	#17 | Hyprland(main+0x881) [0x560b5f9f7821]
		main
		??:?
	#18 | /lib64/libc.so.6(+0x26350) [0x7ff081d62350]
		??
		??:0
	#19 | /lib64/libc.so.6(__libc_start_main+0x89) [0x7ff081d62409]
		??
		??:0
	#20 | Hyprland(_start+0x25) [0x560b5fa09c75]
		_start
		??:?

Log tail:
[LOG] Callback 560b61703d10 -> 560b61703d08, CWLSurface removed.
[LOG] CWLSurface 560b61703cc0 called destroy()
[LOG] LayerSurface 560b688bc5f0 destroyed
[LOG] Callback 560b61703ec8 -> 560b61703ec0, layerSurface removed.
[LOG] Callback 560b61703d90 -> 560b61703d88, layerSurface removed.
[LOG] Callback 560b61703df8 -> 560b61703df0, layerSurface removed.
[LOG] Callback 560b61703e60 -> 560b61703e58, layerSurface removed.
[LOG] Callback 560b61703f30 -> 560b61703f28, layerSurface removed.
[LOG] LayerSurface 560b60dc7910 unmapped
[LOG] Framebuffer created, status 36053
[LOG] Callback 560b60dd7e20 -> 560b60dd7e18, CWLSurface removed.
[LOG] CWLSurface 560b60dd7dd0 called destroy()
[LOG] LayerSurface 560b60dc7910 destroyed
[LOG] Callback 560b60dd7fd8 -> 560b60dd7fd0, layerSurface removed.
[LOG] Callback 560b60dd7ea0 -> 560b60dd7e98, layerSurface removed.
[LOG] Callback 560b60dd7f08 -> 560b60dd7f00, layerSurface removed.
[LOG] Callback 560b60dd7f70 -> 560b60dd7f68, layerSurface removed.
[LOG] Callback 560b60dd8040 -> 560b60dd8038, layerSurface removed.
[LOG] Removed monitor DP-3!
[WARN] Unplugged last monitor, entering an unsafe state. Good luck my friend.
[LOG] Entering unsafe state
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c748 -> 560b60a2e208 (owner: )
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c7d8 -> 560b60a2e270 (owner: )
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c7c8 -> 560b60a2e2d8 (owner: )
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c758 -> 560b60a2e340 (owner: )
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c768 -> 560b60a2e3a8 (owner: )
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c788 -> 560b60a2e410 (owner: )
[LOG] Registered signal for owner 560b60a2de00: 560b60a3c7a8 -> 560b60a2e478 (owner: )
[WARN] No rule found for HEADLESS-1, trying to use the first.
[WARN] No rules configured. Using the default hardcoded one.
[LOG] Applying monitor rule for HEADLESS-1
[ERR] Monitor HEADLESS-1 has NO PREFERRED MODE
[LOG] output HEADLESS-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] Monitor HEADLESS-1 -> destroyed all render data
[LOG] arrangeMonitors: 2 to arrange
[LOG] arrangeMonitors: DP-3 auto [0, 0.00]
[LOG] arrangeMonitors: HEADLESS-1 auto [5120, 0.00]
[LOG] arrangeMonitors: DP-3 xwayland [0, 0.00]
[LOG] arrangeMonitors: HEADLESS-1 xwayland [5120, 0.00]
[LOG] Monitor HEADLESS-1 data dump: res 1920x1080@60.00Hz, scale 1.00, transform 0, pos 5120x0, 10b 0
[LOG] Added new monitor with name HEADLESS-1 at [5120, 0] with size [1920, 1080], pointer 560b60a3c6a0
[LOG] New monitor: WORKSPACEID 2, exists: 0
[LOG] Callback 560b60ab4650 -> 560b60ab4648, CRenderbuffer removed.
[LOG] Callback 560b60b1ab30 -> 560b60b1ab28, CRenderbuffer removed.
[LOG] Removing monitor DP-3 from realMonitors
[LOG] Callback 560b60a3f5e8 -> 560b60a3f5e0,  removed.
[LOG] Callback 560b60a3f650 -> 560b60a3f648,  removed.
[WARN] Attempted to render frame on inactive session!
[WARN] Attempted to render frame on inactive session!
[LOG] cursorImage request: surface 560b60dc8920
[LOG] Registered signal for owner 560b60a3d190: 560b60dbe258 -> 560b60a3d390 (owner: layerSurface)
[LOG] Registered signal for owner 560b60a3d190: 560b688bc6b8 -> 560b60a3d258 (owner: layerSurface)
[LOG] Registered signal for owner 560b60a3d190: 560b60dbe268 -> 560b60a3d2c0 (owner: layerSurface)
[LOG] Registered signal for owner 560b60a3d190: 560b60dbe278 -> 560b60a3d328 (owner: layerSurface)
[LOG] Registered signal for owner 560b60a3d190: 560b688bc6c8 -> 560b60a3d3f8 (owner: layerSurface)
[LOG] LayerSurface 560b688bc5f0 (namespace waybar layer 2) created on monitor HEADLESS-1
[WARN] Orphaned wlr_surface 560b60dbdf80 in setPreferredScaleForSurface
[WARN] Orphaned wlr_surface 560b60dbdf80 in setPreferredTransformForSurface
[LOG] LayerSurface 560b688bc5f0 mapped
[LOG] Registered signal for owner 560b60a3d1b0: 560b60dbe298 -> 560b60a3d1d8 (owner: CWLSurface)
[LOG] CWLSurface 560b60a3d1b0 called init()
[LOG] Searching for matching rules for firefox (title: Mozilla Firefox)

**Comment by vaxerski** [comment]
this is fixed in -git
