### ISSUE TITLE
Hyprland freezes when resuming after all monitors disconnected

### ISSUE THREAD

**Issue by dmayle** [hyprwm/Hyprland#5123]
### Hyprland Version

<details> <summary>System/Version info</summary>
I'm running 0.36.0 with a single patch on top to add timestamps to WLR logging.

```sh
Hyprland, built from branch  at commit cf9fe875624b2b03a069094f821e3c1f287e2f3d  ().
Date: 2024-03-14
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: beast
Release: 6.6.21
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:48:45 UTC 2024


GPU information: 
2d:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080] [10de:2206] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240312.0ad13a6"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hy3 by outfoxxed ver 0.1
```

</details>

### Bug or Regression?

Bug

### Description

Every few days, when I come back to my computer after having turned off the display, Hyprland freezes and is unable to wake up.  I left comments on #4134 , but after removing swaylock completely, I still have the issue.

After adding timestamps to the logging (and checking over a couple of days), I think there's enough information to warrant making an issue directly against Hyprland.

### How to reproduce

My Nix Home-Manager config can be found at:
https://github.com/dmayle/nix-config

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/14618536/hyprland.conf.txt)

In general, though, I just turn off my display, which causes it to disconnect.

For this morning's freeze, I looked through the logs for interesting events in order to establish a timeline.  I was accidentally logging hyprland time in unix time, which means that there is a seven hour offset

1. I started this instance of hyprland at 09:21 yesterday morning (from timestamp on /tmp/hypr directory, marked 16:21 in hyprland log), but had left my house by 9:28 (16:28 Unix) and did not use my computer again until the evening.
2. While I was away from my computer, there is an event that says "Destroy called for monitor HDMI-A-1" at 09:35 (16:35).
3. Hyprland logging stops completely at 09:35 (16:35)
4. I use the computer in the evening, briefly at 18:33 (01:33) until 18:51 (01:51)
5. I used it again starting at 20:36 (03:36) until 20:54 (03:54)
6. Hyprland stops logging at 20:54 (03:54)
7. I turn on my display around 08:13 and Hyprland is frozen

### Crash reports, logs, images, videos

[Mar_15_freeze_hypr_filtered.log](https://github.com/hyprwm/Hyprland/files/14618745/Mar_15_freeze_hypr_filtered.log)
[Mar_15_freeze_dmesg.log](https://github.com/hyprwm/Hyprland/files/14618748/Mar_15_freeze_dmesg.log)

**Comment by dmayle** [comment]
I just had this happen again today.  I updated my logging patch to fix timestamps to local time, and to use the same timestamp logging format across dmesg, and all hyprland log sources, so it should be easier to correlate:

[March_15_freeze_hyprland_filtered.log](https://github.com/hyprwm/Hyprland/files/14621828/March_15_freeze_hyprland_filtered.log)
[March_15_freeze_dmesg.log](https://github.com/hyprwm/Hyprland/files/14621829/March_15_freeze_dmesg.log)

I'm going to try a patch to wlroots that I saw online for retrying page flips, to see if that helps.

**Comment by mtwb47** [comment]
Unsure if I'm having the same issue, as I don't disconnect my monitors, but I too am having an issue where Hyrpland freezes after resuming from sleep. Sometimes I go a day without this happening, sometimes it happens every time I wake the computer up.

**Comment by dmayle** [comment]
> Unsure if I'm having the same issue, as I don't disconnect my monitors, but I too am having an issue where Hyrpland freezes after resuming from sleep. Sometimes I go a day without this happening, sometimes it happens every time I wake the computer up.

I don't disconnect my monitor physically, I just power it off, which causes the GPU to see it as disconnected.  Do you power off your displays?

I'm currently trying out a patch to wlroots that performs a blocking page flip if the device is busy when it tries the non-blocking pageflip.

If that makes things better, I'm going to change the patch to retry the non-blocking pageflip a set number of times (3? 5?) instead.

And if that works, than I think it will mean that there is a problem with how non-blocking pageflips are handled when they don't succeed, and won't ever succeed.  (ie. the monitor is disconnected).  It's not clear whether this would be a problem in wlroots, Hyprland, or simply the contract between the two, but I'll update this issue in a few days if I don't otherwise trigger the issue with the current patch.

**Comment by mtwb47** [comment]
My monitors go into "sleep" when the computer hibernates, I assume that they appear disconnected. When I come back to the computer and wake it from sleep, the monitors will come on, swaylock comes up and will allow me to unlock. But then the computer is completely frozen. Won't even go to a TTY and requires a hard reboot to get working again.

**Comment by dmayle** [comment]
> My monitors go into "sleep" when the computer hibernates, I assume that they appear disconnected. When I come back to the computer and wake it from sleep, the monitors will come on, swaylock comes up and will allow me to unlock. But then the computer is completely frozen. Won't even go to a TTY and requires a hard reboot to get working again.

In that case, this is almost certainly the same issue.  What brand of video card?

If it's Nvidia, you can check for sure by going to a TTY before trying to unlock and issue `dmesg` to check for a message like "[drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000900] Flip event timeout on head 0", though the flip event issue is not limited to just nvidia.

**Comment by mtwb47** [comment]
I have a 6750xt, it's an all AMD System.

**Comment by dmayle** [comment]
Unfortunately, the patch I tried still freezes.  I have a suspicion that it may be related to using USB input before the monitor is fully powered up.  I'm going to try to be careful to wait until the monitor is fully powered before touching the keyboard or mouse for the next couple of days.

[March_17_freeze_dmesg.log](https://github.com/hyprwm/Hyprland/files/14629756/March_17_freeze_dmesg.log)
[March_17_freeze_hyprland_filtered.log](https://github.com/hyprwm/Hyprland/files/14629758/March_17_freeze_hyprland_filtered.log)

**Comment by dmayle** [comment]
I'm starting to think that this is either caused by a bug in wlroots, or in the way wlroots is used (since the same bug affects sway, but not mutter with gnome).  I'm going to try to capture a stack trace when it's frozen, and use that as a tool to dig deeper.  If anyone has a hyprland stack trace (0.37.0 or 0.37.1 preferably) from this freeze, it would be useful to be attached here

**Comment by mtwb47** [comment]
Now, I'm knocking on wood, but I haven't had this happen since I upgraded to 0.37 and to the latest pull of the portal (been three days). I will say though that I've been waiting for my external hard drive to spool up, so maybe that was what I needed to do.

**Comment by dmayle** [comment]
I just updated to 0.37.1 yesterday, I'll keep my fingers crossed.

**Comment by dmayle** [comment]
Well, it froze for me again.  I just captured a stacktrace with gdb, I'll dig into the code later:

```
[nix-shell:~]$ gdb
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) attach 2573
Attaching to process 2573
[New LWP 2592]
warning: File "/nix/store/hjsvh50fy7g4dhhj3znsjh14a3p678b4-gcc-13.2.0-lib/lib/libstdc++.so.6.0.32-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/agp6lqznayysqvqkx4k1ggr8n1rsyi8c-gcc-13.2.0-lib".
To enable execution of this file add
	add-auto-load-safe-path /nix/store/hjsvh50fy7g4dhhj3znsjh14a3p678b4-gcc-13.2.0-lib/lib/libstdc++.so.6.0.32-gdb.py
line to your configuration file "/home/douglas/.config/gdb/gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/douglas/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/libthread_db.so.1".
0x00007febbf019c3f in ioctl () from /nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/libc.so.6
(gdb) bt
#0  0x00007febbf019c3f in ioctl () from /nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/libc.so.6
#1  0x00007febbf974978 in drmIoctl () from /nix/store/6n7r4hfrz7wcfgyyy4wly2dl8wpmgrln-libdrm-2.4.120/lib/libdrm.so.2
#2  0x00007febbf97c9a4 in drmModeAtomicCommit () from /nix/store/6n7r4hfrz7wcfgyyy4wly2dl8wpmgrln-libdrm-2.4.120/lib/libdrm.so.2
#3  0x00007febbfb543c7 in atomic_commit () from /nix/store/39mi7ka1g2xmi8g5ylm7bj7ih4w4sr6f-wlroots-hyprland-custom-2024-03-15_3/lib/libwlroots.so.13
#4  0x00007febbfb54e49 in atomic_crtc_commit () from /nix/store/39mi7ka1g2xmi8g5ylm7bj7ih4w4sr6f-wlroots-hyprland-custom-2024-03-15_3/lib/libwlroots.so.13
#5  0x00007febbfb57621 in drm_crtc_commit () from /nix/store/39mi7ka1g2xmi8g5ylm7bj7ih4w4sr6f-wlroots-hyprland-custom-2024-03-15_3/lib/libwlroots.so.13
#6  0x00007febbfb578f9 in drm_connector_commit_state () from /nix/store/39mi7ka1g2xmi8g5ylm7bj7ih4w4sr6f-wlroots-hyprland-custom-2024-03-15_3/lib/libwlroots.so.13
#7  0x00007febbfb70334 in wlr_output_commit_state () from /nix/store/39mi7ka1g2xmi8g5ylm7bj7ih4w4sr6f-wlroots-hyprland-custom-2024-03-15_3/lib/libwlroots.so.13
#8  0x000000000058f06f in CMonitorState::commit() ()
#9  0x000000000067c84e in CHyprRenderer::renderMonitor(CMonitor*) ()
#10 0x00000000005a199b in CHyprWLListener::emit(void*) ()
#11 0x00000000005a2acf in handleWrapped(wl_listener*, void*) ()
#12 0x00007febbfc2ca0c in wl_signal_emit_mutable () from /nix/store/55kjzqzn2a3g0v3wssbq9507rkpnp3k6-wayland-1.22.0/lib/libwayland-server.so.0
#13 0x00007febbfc2e82b in wl_event_loop_dispatch_idle () from /nix/store/55kjzqzn2a3g0v3wssbq9507rkpnp3k6-wayland-1.22.0/lib/libwayland-server.so.0
#14 0x00007febbfc2e94a in wl_event_loop_dispatch () from /nix/store/55kjzqzn2a3g0v3wssbq9507rkpnp3k6-wayland-1.22.0/lib/libwayland-server.so.0
#15 0x00007febbfc2c455 in wl_display_run () from /nix/store/55kjzqzn2a3g0v3wssbq9507rkpnp3k6-wayland-1.22.0/lib/libwayland-server.so.0
#16 0x00000000004907d6 in main ()
(gdb)
```

**Comment by vaxerski** [comment]
talked to the wlroots devs, this is an nvidia bug.

**Comment by gwagner** [comment]
@vaxerski maybe a naive question, but is this an nvidia bug if it is happening with AMD cards?  I am running an 6700xt and I am getting the same thing.

**Comment by vaxerski** [comment]
your stacktrace is probably different and not related to this.

**Comment by dmayle** [comment]
For what it's worth, despite this supposedly being an Nvidia bug, once I switched to 0.41.2 which removed most of wlroots, the problem went away.
