### ISSUE TITLE
[FEATURE REQUEST] Tabbed monocle layout

### ISSUE THREAD

**Issue by luravoid** [hyprwm/Hyprland#5127]
### Description

In a sense, this is a duplicate of already existing feature requests (see #2050, #2822), but I want to expand on them and describe in more detail a feature that I think would be very useful and hopefully inspire developers capable of creating it.

I think one of the biggest weaknesses of hyprland's window management is that there is no proper monocle layout, and I think to create one, it would be a really good idea to use the already existing groups feature, but implement it as a layout.

Of course, I know that there is a fullscreen 0 and 1 dispatcher, which in a way works like a monocle, but its purpose is a bit different. You only want to toggle fullscreen for a moment when the window is too small to see things more clearly, and then untoggle it. 

With a properly implemented monocle layout, you can spawn windows, move them to or from the workspace, arrange them in a specific order, all without leaving the layout. 

Take a look at this script from #2822, which replicates this behavior to some extent, but the problem is that it's still quite limiting and a proper implementation needs to be more than a hacky bash script:
https://gist.github.com/Atrate/b08c5b67172abafa5e7286f4a952ca4d

Here is the video showcasing the script:

https://github.com/hyprwm/Hyprland/assets/103893901/cff0247a-3722-4d30-b58f-4da3631feb71

The problems with the script are that:

1. If there's too many windows on the screen then not every window will be toggled as group
2. I can't use my keybindings for master layout, I need to define specific dispatchers for groups and if the bindings will be the same as for the master then I will not be able to use groups in the normal way.
```
bind  = $mainMod, J, layoutmsg, cyclenext
bind  = $mainMod, K, layoutmsg, cycleprev
bind  = $mainMod SHIFT, J, layoutmsg, swapnext
bind  = $mainMod SHIFT, K, layoutmsg, swapprev

bind = $mainMod, J, changegroupactive, f
bind = $mainMod, K, changegroupactive, b
bind = $mainMod SHIFT,J, movegroupwindow, f
bind = $mainMod SHIFT,K, movegroupwindow, b
```
The solution would be to add specific dispatchers, such as "monocle, cyclenext", "monocle, swapprev", etc.

3. I cannot move a window in a group to another workspace without moving the whole group. First I have to detach the window from the group and only then I can move it. Same as when I want to move a window to an already toggled group.
4. The position of the windows changes randomly when I use this script, and the desired behavior would be so the placement of the windows in the monocle layout would mirror the placement of the windows in the tiled layout.

So yeah, I think tabbed layout would be a really nice feature to have

**Comment by vaxerski** [comment]
#2050

use the search feature
