### ISSUE TITLE
Windows animations no longer applied?

### ISSUE THREAD

**Issue by nosvagor** [hyprwm/Hyprland#513]
After updating binary, "popin" is no longer valid style for windows.

An error appears: "invalid minperc"

Adding a percentage value e.g., "popin 80%" appears to fix the error message, but the no animation is present. 

Leaving out the line entirely (defaults) also makes windows lack any animations. 

border, fade, workspaces all appear to be fine.

**Comment by vaxerski** [comment]
fixed in 008cc63dc03a31797142772885129fd32c964776
