### ISSUE TITLE
38576d6 breaks rendering of VirtualBox window

### ISSUE THREAD

**Issue by M4he** [hyprwm/Hyprland#5130]
### Hyprland Version

<details> <summary>System/Version info</summary>

Hyprland: git 38576d651a9a7edcf5d7b782a2f415c8a1f0f4e6 via [official NixOS Flake](https://github.com/hyprwm/hyprland-wiki/blob/27b9014e80ff216327c7a8cdec2a6ac638a31162/pages/Nix/Hyprland%20on%20NixOS.md?plain=1#L78-L93)

System:

- OS: NixOS 23.11 (Tapir)
- GPU: Intel CometLake-U GT2 UHD Graphics

</details>

### Bug or Regression?

Regression

### Description

Since 38576d651a9a7edcf5d7b782a2f415c8a1f0f4e6 the VirtualBox main window fails to render its contents. Only borders are visible, the window content itself is fully transparent (as in not rendered at all). Hovering over the (invisible) UI widgets of the window *will* render popups.

### How to reproduce

Open VirtualBox main window.

**Comment by vaxerski** [comment]
what if you resize the window?

**Comment by fufexan** [comment]
I've just updated my system (including Hyprland) and I cannot replicate this. VirtualBox shows up fine.

**Comment by vaxerski** [comment]
fixed with 5e5d7e2abcd91c83058ba80ec64ec5054cae5bfa
