### ISSUE TITLE
hyprctl dispatch exit requires keypress to exit

### ISSUE THREAD

**Issue by dmayle** [hyprwm/Hyprland#5134]
### Hyprland Version

<details> <summary>System/Version info</summary>
I'm running 0.36.0 with a single patch on top to add timestamps to WLR logging.

```sh
Hyprland, built from branch  at commit cf9fe875624b2b03a069094f821e3c1f287e2f3d  ().
Date: 2024-03-14
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: beast
Release: 6.6.21
Version: https://github.com/hyprwm/Hyprland/issues/1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:48:45 UTC 2024


GPU information: 
2d:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080] [10de:2206] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="[https://github.com/NixOS/nixpkgs/issues](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)"
BUILD_ID="24.05.20240312.0ad13a6"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hy3 by outfoxxed ver 0.1
```

</details>

### Bug or Regression?

Bug

### Description

I use wlogout to issue a `hyprctl dispatch exit` when I wish to logout.

If I use the mouse to trigger the button, then Hyprland hangs until I press any key, and which point the logout continues.

I'm currently debugging #5123 so I don't want to exit Hyprland.  The next time Hyprland crashes (or it doesn't because my workaround is solving that crash), I will generate logs specific to this issue, along with a stack trace.

### How to reproduce

My Nix Home-Manager config can be found at:
https://github.com/dmayle/nix-config

[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/14618536/hyprland.conf.txt)

**Comment by M4he** [comment]
Already reported in #4599 see this comment: https://github.com/hyprwm/Hyprland/issues/4599#issuecomment-1925187942
