### ISSUE TITLE
Weird floating window resizing after update

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#5135]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit c5e28ebcfe00a510922779b2c568cfa52a317445  ().
Date: 2024-03-16
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: theseus
Release: 6.7.9
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:54:01 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240314.d691274"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

Floating windows resizing become kinda weird after last update.

Tested with default config, same stuff. Problem occurs with all windows, so not app or toolkit specific stuff.

See vid

### How to reproduce

1) Resize any floating window from smaller to larger, see the corner opposite to resize direction (top left on vid)
2) 🤡

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/142721811/9a955abf-ee26-44be-9137-989d88591e28

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14624541/patch.txt)
does this suit your tastes better?

**Comment by Ligthiago** [comment]
Oh god, I don't want to compile stuff right now, if it's reproducible for you can you choose for your own taste?

**Comment by vaxerski** [comment]
for my own taste the above looks right

**Comment by Ligthiago** [comment]
Nah, bad taste. Fixed when resizing to bottom right, but not otherwise. See vid

https://github.com/hyprwm/Hyprland/assets/142721811/43c85c5a-e586-4166-93c8-8895e0dcadc1

**Comment by Ligthiago** [comment]
Also it not really fixed in this direction. I check older generation (like couple of days ago) and this stuff not appeared in it.
![2024-03-16T21:39:43,377925589+04:00](https://github.com/hyprwm/Hyprland/assets/142721811/0fe95462-6f43-487f-a99c-27bb33231229)

**Comment by vaxerski** [comment]
it would be stretched instead, which IMO is a worse option.

**Comment by vaxerski** [comment]
repaint artifacts are a bug though yeah I'll fix that

**Comment by Ligthiago** [comment]
Like it work 100% perfect without any artifacts several days ago, so there must be a solution

**Comment by vaxerski** [comment]
it didn't work perfect, it would be stretched, again.

**Comment by vaxerski** [comment]
there, fuck off, it will stretch again.

**Comment by Ligthiago** [comment]
This vid from some older commit, I don't see there anything worse than now. If it considered stretching, it's also appear now.

https://github.com/hyprwm/Hyprland/assets/142721811/f66c432c-32d5-472a-98a0-7a5fd711a356

**Comment by vaxerski** [comment]
I'd be worried for your eyesight if you can't see the jitter caused by the stretching

**Comment by Ligthiago** [comment]
Yea, it jitter a bit, okay, I can see it. It wasn't work 100% perfect and I am wrong, very sorry. 
But if border moving faster than window is much worse.
