### ISSUE TITLE
Weird popin animation behavior when open floating window with size 70% 70% windowrule 

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#5136]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0e87a08e15c023325b64920d9e1159f38a090695  ().
Date: 2024-03-16
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: theseus
Release: 6.7.9
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:54:01 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240314.d691274"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

This one is weird. Tested on default config, work with all windows.
See vid and how to repro

### How to reproduce

1) (Optional) Set window animation to slow to better see effect
2) Launch any window in floating mode with 70% 70% size, for example `hyprctl dispatch exec "[float;size 70% 70%;center] kitty"`. In this case I have 1920x1080 mon, maybe it will not reproducible otherwise.
3) Weird part: It will not appear with 60% or 80%

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/142721811/b47a8c4c-44e2-42a7-b958-4492861531f3

**Comment by vaxerski** [comment]
still a thing on -git?

**Comment by Ligthiago** [comment]
Yes, still a thing.

**Comment by Ligthiago** [comment]
This commit 38576d651a9a7edcf5d7b782a2f415c8a1f0f4e6 seems to introduce regression, it worked fine in previous ones.

>supersedes # 5104 Prevent stretching when resizing window

Oh boy, is this connected after all?

**Comment by vaxerski** [comment]
on -git, can't repro

**Comment by vaxerski** [comment]
nvm can repro
