### ISSUE TITLE
Attempted to draw NULL texture!

### ISSUE THREAD

**Issue by Kelares** [hyprwm/Hyprland#514]
Steps to reproduce:
Open hyprland from the terminal with cmd Hyprland(after installing through aur or even building on my own).

Expected outcome:
Hyprland starts

Noted outcome:
OpenGL cant find any texture and finishes the process with critical error.

###########    Hyprland log
https://pastebin.pl/view/44e89043

################# Coredump
https://pastebin.pl/view/edc034be

################# Config file
https://pastebin.pl/view/1005318b

**Comment by vaxerski** [comment]
my god please attach those not paste

**Comment by vaxerski** [comment]
is this a regression or is this your first time launching hl?

**Comment by Kelares** [comment]
It's my first time launching, and also sorry for the logs its my first time reporting on an issue.

**Comment by vaxerski** [comment]
either attach them as files, or use some pastebin or something. It's painful to read these.

I need more information: Arch Linux, is this a VM? What's your GPU? Have you got mesa and friends installed?

**Comment by Kelares** [comment]
No its not a VM. My gpu is Intel Corporation HD Graphics 620 (rev 02). I have installed mesa through pacman (mesa-22.1.6-1).

**Comment by vaxerski** [comment]
do you have `vulkan-intel`?

why do you have radeon and nvidia graphics installed then?

**Comment by Kelares** [comment]
It's an artifact after first installing arch on this laptop, it was an old laptop and I didn't bother to gather information about it's specs and while installing I figured that one of the graphics should work and indeed it did. Right now I removed all of the radeon and nvidia packages that I could find in my system and still nothing changed.

**Comment by vaxerski** [comment]
if it's an old laptop - have you tried doing as instructed in the wiki and building with legacy renderer?

**Comment by Kelares** [comment]
Yes I also tried building it manually throguh Legacy render. Nothing seems to change the outcome

**Comment by Kelares** [comment]
Yes I also tried building it manually throguh Legacy render. Nothing seems to change the outcome

**Comment by Kelares** [comment]
Ok, so I made some progress, it turned out that sddm had no trouble with opening hyprland and from there I started configuring it. And once I came back to my kde installation and tried running hyprland cmd again, it worked.

**Comment by vaxerski** [comment]
It's most likely an issue with your system then. Closing.
