### ISSUE TITLE
Alpha show ghost of animation

### ISSUE THREAD

**Issue by regit** [hyprwm/Hyprland#5143]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 01:32:40 2024
Tag: v0.36.0

flags: (if any)


System Information:
System name: Linux
Node name: brussels
Release: 6.7.9-amd64
Version: #1 SMP PREEMPT_DYNAMIC Debian 6.7.9-2 (2024-03-13)


GPU information: 
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660] [10de:2184] (rev a1) (prog-if 00 [VGA controller])


os-release: PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


plugins:
```

</details>

The bug appears when running newer version than the one here which does not exhibit the problem. I have tried up to e68c07d8096ee5f83e29508c8762279ab80a924b

### Bug or Regression?

Regression

### Description

The borders of the window during animation are leaving ghosts on the window surface. We can see how the animation did increase the size. The ghosts can only be seen when the window is not in focus.

### How to reproduce

Usually, spawning a kitty terminal is enough.

**Comment by vaxerski** [comment]
try git

**Comment by regit** [comment]
> try git (like, git right now)

It works perfectly on my first monitor but the second one is having the same issue.

**Comment by vaxerski** [comment]
well I will need your config and a recording would be useful.

**Comment by regit** [comment]
> well I will need your config and a recording would be useful. (I can't repro)

Thanks for the super quick feedback and partial fix! I'm sadly away any of my 2 screens setup this week. I'll build latest git when I come back and feedback with requested information if the bug is still there.

**Comment by regit** [comment]
I've booted the system and directly build and installed main at commit 0dfdb6678f5362fda449694639e8fee806ca1ae4 and it is not showing the problem anymore. I'm closing the issue.
