### ISSUE TITLE
global fix for blurry electron apps on xwayland?

### ISSUE THREAD

**Issue by abysssdweller** [hyprwm/Hyprland#5149]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

discord, spotify and other electron apps are blurry to fix it i had to add --ozone-platform="wayland" to the '''exec''' args in the .desktop file for each electron app which is tiring. is there a global way to fix this. 

### How to reproduce

launch any electron app (xwayland)

**Comment by Ligthiago** [comment]
Basically all info you need is here https://wiki.archlinux.org/title/Wayland#Electron
