### ISSUE TITLE
Hyprcursor misalignment

### ISSUE THREAD

**Issue by FUFSoB** [hyprwm/Hyprland#5150]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 30c5911718c02e0215bf0006faa6aa229558a501 dirty (renderer: minor fixups for misaligned surface rendering offsets).
Date: Sun Mar 17 21:08:59 2024
Tag: v0.37.1-9-g30c59117

flags: (if any)


System Information:
System name: Linux
Node name: arch-pc-nvme
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000


GPU information: 
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Using slightly modified default config.

When `enable_hyprcursor = true`:
- cursor jumps a few pixels when moving cursor from and onto ags;
- cursor jumps a few pixels when moving cursor from and onto url bar in Steam (from the top).

When `enable_hyprcursor = false`, then only Steam bug persists. I think Steam renders hyprcursor there regardless of set option.

### How to reproduce

Move cursor slowly between elements that do and don't support hyprcursor.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/32937947/e55a0fb6-103a-4839-a635-cdac2fe468da

**Comment by vaxerski** [comment]
This is not really a bug with hyprcursor; it's most likely a slightly different hotspot between the hyprcursor theme and the xcursor theme.

Steam _never_ renders a hyprcursor
ags is gtk which doesn't support server-side cursors and thus also _never_ renders a hyprcursor.

**Comment by FUFSoB** [comment]
> ags is gtk which doesn't support server-side cursors

Yeah, I understand, I never claimed that it does.

> Steam _never_ renders a hyprcursor

If so, I'm really confused about Steam's behavior.

https://github.com/hyprwm/Hyprland/assets/32937947/2b29cb0c-d48f-4ce6-b28e-3cdd4c270d88

**Comment by vaxerski** [comment]
can't really explain that. My guess is the embedded CEF could use xcursor differently than the gtk client
