### ISSUE TITLE
Slidefade for layers 

### ISSUE THREAD

**Issue by PoSayDone** [hyprwm/Hyprland#5151]
### Description

It would be very useful to have this type of animation for layers.

**Comment by vaxerski** [comment]
windows dont have slidefade though? wdym?

**Comment by PoSayDone** [comment]
> windows dont have slidefade though? wdym?

sry, windows really don't have that type of animation.

but, it will be quite useful for layers, as they are often launchers, settings panels, etc.

**Comment by vaxerski** [comment]
can't you just combine the `layersFade` and `layers` animations, tho?

**Comment by PoSayDone** [comment]
> can't you just combine the `layersFade` and `layers` animations, tho?
> 
> edit: er, `fadeLayers`

I don't really understand how this is supposed to work.
If I put slide for layers, will fadeLayers work? I tried it and it didn't work for me

**Comment by PoSayDone** [comment]
Do not work for me
![image](https://github.com/hyprwm/Hyprland/assets/29358657/29b020b7-02d7-4ba9-b533-704fb7884d87)
![image](https://github.com/hyprwm/Hyprland/assets/29358657/81475394-f622-4114-8074-3e3ae0a6dfd4)

https://github.com/hyprwm/Hyprland/assets/29358657/7de2abb6-1193-4bba-b2f8-1d828be5d592

**Comment by vaxerski** [comment]
oops right my bad
