### ISSUE TITLE
Transparency correctly implemented / configured?

### ISSUE THREAD

**Issue by JohRest** [hyprwm/Hyprland#5154]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: archwork
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080 Lite Hash Rate] [10de:2216] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I've noticed that when I do not use the tiling mode and do have overlapping windows, the transparency always displays the desktop instead of correctly? showing the underlying window content:
![image](https://github.com/hyprwm/Hyprland/assets/2835797/b393271e-ee26-4332-a48d-180b2ece950b)
In this example I'd expect to have hyrpland show the underlying grid of the chromium window. Instead I do see  my background image. Is that expected? Or do I have a configuration problem?

### How to reproduce

start hyprland session. Launch multiple windows in non-tiling mode, have the windows overlap. You need to have transparency set.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14632169/hyprland.log)

**Comment by Ligthiago** [comment]
Do you have `xray=true` in `decoration:blur:`? If so, disable it.

**Comment by JohRest** [comment]
thanks for the hint, will give it a try!

**Comment by JohRest** [comment]
works like a charm! thanks for taking a look at my issue.
