### ISSUE TITLE
Hyprland creates new monitor and switches to it after closing laptop lid and resuming

### ISSUE THREAD

**Issue by zachcoyle** [hyprwm/Hyprland#5156]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit bd332a79e7669f1dc05ce7ea6b5d78028f1f02bc  ().
Date: 2024-03-16
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos-laptop
Release: 6.5.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] [1002:7340] (rev 43) (prog-if 00 [VGA controller])
04:00.1 Non-VGA unclassified device [0000]: Apple Inc. T2 Bridge Controller [106b:1801] (rev 01)
04:00.2 Non-VGA unclassified device [0000]: Apple Inc. T2 Secure Enclave Processor [106b:1802] (rev 01)


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240317.299d466"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hyprtrails by Vaxry ver 1.0


```

</details>

### Bug or Regression?

Bug

### Description

Opened laptop lid, unlocked the computer, and I was on a "new monitor" as reported by `hyprctl monitors all -j`. I wasn't sure exactly what was going on, but was able to open a terminal I couldn't see and redirect that command to a file before rebooting.  Not sure whether this is a duplicate of #4562.  

### How to reproduce

Close laptop lid, open laptop lid, unlock hyprlock

### Crash reports, logs, images, videos

`hyprctl monitors all -j` pre-sleep
[monitors.json](https://github.com/hyprwm/Hyprland/files/14639049/monitors.json)

`hyprctl monitors all -j` post-sleep
[monitors2.json](https://github.com/hyprwm/Hyprland/files/14639048/monitors2.json)

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14639095/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14639101/hyprland.log)

**Comment by vaxerski** [comment]
somehow your monitor duped itself? That might be a driver bug.

**Comment by zachcoyle** [comment]
After updating my kernel and hyprland to the latest, this does not happen anymore
