### ISSUE TITLE
Dragging floating windows is stuttery.

### ISSUE THREAD

**Issue by JunaidQrysh** [hyprwm/Hyprland#5157]
### Hyprland Version

Hyprland, built from branch main at commit c34ad12183506cb5f52bfb65b44e3a274e996fc3 dirty (cursormgr: scale hotspot with buffer).
Date: Mon Mar 18 00:30:21 2024
Tag: v0.37.1-10-gc34ad121

flags: (if any)

System Information:
System name: Linux
Node name: asus
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000

GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] [10de:25a2] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

core i9-11900h rtx 3050 laptop.
120hz screen.

Animations look smooth in 120hz than 60hz as expected but dragging a floating windows looks same in 60hz and 120hz.

Other DEs dont have this problem.

### How to reproduce

Drag a floating windows in 120hz and 60hz using
monitor=eDP-1,1920x1200@60,0x0,1
monitor=eDP-1,1920x1200@120,0x0,1

**Comment by vaxerski** [comment]
well I am on 240hz and can not reproduce this.

**Comment by JunaidQrysh** [comment]
> well I am on 240hz and can not reproduce this.

**Comment by JunaidQrysh** [comment]
> > well I am on 240hz and can not reproduce this.

could you give me any idea how can i solve this? I'm a linux beginner since a few weeks.

**Comment by vaxerski** [comment]
I have no idea because you seem to be the only one with this issue.

**Comment by JunaidQrysh** [comment]
> I have no idea because you seem to be the only one with this issue.

I think #4553 is related to my issue.

**Comment by JunaidQrysh** [comment]
> I have no idea because you seem to be the only one with this issue.

I can confirm the video provided in #4669 is exactly the case with me , but seeming the bug is fixed,not in my case.

**Comment by JunaidQrysh** [comment]
Update:
I installed hyprland 0.34.0 and now floating windows feel buttery smooth. I hope this bug get fixed as soon as possible.

**Comment by vaxerski** [comment]
I don't think that one does anything for monitors that aren't 60hz.

**Comment by bvr-yr** [comment]
here we go again
what's your package manager for `-git` version?
