### ISSUE TITLE
hyprctl setcursor stopped working

### ISSUE THREAD

**Issue by eveloth** [hyprwm/Hyprland#5160]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: altair-gentoo
Release: 6.7.10-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Sat Mar 16 07:48:45 -00 2024


GPU information: 
28:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

`hyprctl setcursor` stopped working for an unknown reason in v0.37.1

### How to reproduce

- Install any cursor theme in `~/.local/share/icons` or `/usr/share/icons`
- Execute `hyprctl setcursor THEME SIZE`
- Nothing happens

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/83219056/15a3d365-0d3c-4baf-b661-1167de39b8a9

**Comment by vaxerski** [comment]
it still works, it just only accepts hyprcursor themes now.

If you want to use legacy xcursor themes, use the `XCURSOR_SIZE` and `XCURSOR_THEME` env vars.

https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/
