### ISSUE TITLE
Implement XDG Autostart

### ISSUE THREAD

**Issue by Kuruyia** [hyprwm/Hyprland#5169]
### Description

The [XDG Autostart specification](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html) is a spec implemented by major desktop environments (GNOME, KDE...) that allows programs to register themselves to be automatically started when the user logs in. 
This is implemented through `.desktop` files that are either present in `$XDG_CONFIG_HOME/autostart` (when a specific user logs in, used by Discord and Steam for instance) or `$XDG_CONFIG_DIRS/autostart` (when any user logs in, used by gnome-keyring for instance).

For now (and as far as I know), Hyprland only provides such functionality through the `exec-once` keyword in its configuration file. It would be nice for Hyprland to support this specification, as it would make software with a "Launch when the user logs in" setting to behave as expected. 
As this might be a big change of behavior for current installations of Hyprland, this feature could be behind a configuration flag.

What do you think about having this in Hyprland?

**Comment by vaxerski** [comment]
why is the question?

**Comment by Kuruyia** [comment]
> why is the question?

I'm asking this because not all tiling window managers implement this specification, so this might be considered unwanted in Hyprland too.

Also, this might be considered out of scope as there are programs (such as dex) that can provide such an implementation of the spec, given that the user `exec-once` them in their config.

**Comment by vaxerski** [comment]
I mean yea that sounds more reasonable, this aint a de

**Comment by vincentaxhe** [comment]
not necessary, a config file defines everything is its advantage, there is no good of desktops, just a bunch of commands, use systemd to implement it if exec-once cannot do willingly.

**Comment by Kuruyia** [comment]
Closing this as it is out of scope.
