### ISSUE TITLE
Match multiple properties with window rules

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#517]
Hi! I would like to make all floating windows opened by the program with the title `nheko` fullscreen by default (and have no animation when going fullscreen). I haven't found a way to do this with current windowrules.
Here is the output of `hyprctl clients | grep -A 10 "nheko:"`, from which I want to make the second window fullscreen:
```
Window 7076710 -> nheko:
	at: 12,42
	size: 895,1088
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: nheko
	title: nheko
	pid: 35500
	xwayland: 0

--
Window 72f2260 -> nheko:
	at: 664,321
	size: 500,500
	workspace: 2 (2)
	floating: 1
	monitor: 0
	class: nheko
	title: nheko
	pid: 35500
	xwayland: 0
```

As far as I am aware, it is not possible to achieve this with currently existing features, so I'm opening this issue to request being able to match multiple properties of a window. This way, I could match `title: nheko` and `floating: 1`.

**Comment by vaxerski** [comment]
e71a4d75dea28db4437b2aab34efb3ac399ba079

**Comment by budimanjojo** [comment]
@vaxerski you're a saint! will there be an updated documentation for this? How do I use this? Is it `class` should be explicitly called in the config file now?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Advanced-config/#window-rules-v2
