### ISSUE TITLE
Hyprland crash Kicad when add library element

### ISSUE THREAD

**Issue by Hyderman** [hyprwm/Hyprland#5170]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit bcba3951f45f11245d424274130eb3a0ac790d93 dirty (input: Only limit drag resizes (5164)).
Date: Tue Mar 19 17:03:31 2024
Tag: v0.37.1-22-gbcba3951

flags: (if any)


System Information:
System name: Linux
Node name: archDesktopHyderman
Release: 6.6.22-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 06:20:33 +0000


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c1) (prog-if 00 [VGA controller])
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Each time I try to add a symbol in kicad, my hyprland crashes. I tried with sway I don't have this problem.

### How to reproduce

Kicad version 8.0.0-1
Go to kicad schematic and try to add a symbol.

### Crash reports, logs, images, videos

I don't have any crash report from hyprland but get some errors in my journal.

[journal.txt](https://github.com/hyprwm/Hyprland/files/14654785/journal.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14654862/hyprland.log)

**Comment by vaxerski** [comment]
thanks for spotting

**Comment by Hyderman** [comment]
Sorry if it supposes to work but I updated my Hyprland and I always have the crash.
This time I have a crash report:
[hyprlandCrashReport1494.txt](https://github.com/hyprwm/Hyprland/files/14656705/hyprlandCrashReport1494.txt)
Seems I have the last commit so idk.

**Comment by vaxerski** [comment]
how the fuck

**Comment by vaxerski** [comment]
ah, kicad doing a bit of trolling
