### ISSUE TITLE
Nested/recursive variable expansion broke somewhere after v0.35.0

### ISSUE THREAD

**Issue by alerque** [hyprwm/Hyprland#5172]
I skipped from v0.35.0 to v0.35.1, so I'm not sure which version this broke in, but it's a regression of some sort.

I have a config that nested variable expansion, like so (in this order):

```hyprlang
$TERMINAL = alacritty
$comms = [workspace special:hyprake] $TERMINAL --class hyprake
workspace = special:hyprake, on-created-empty:$comms
```

This stopped working when I upgraded from v0.35.0, so sometime after that. Replacing `$TERMINAL` in the `$comms =` definition with it's expanded value `alacritty` works fine.

**Comment by kojq** [comment]
> Replacing $TERMINAL in the $comms = definition with it's expanded value alacritty works fine.

This does not seem relevant.

So, I took your config and tried. It works. What I can assume is happening is if you close alacritty and perform your insert bind quickly (before it fully closes), your bind will not open a new alacritty within the special workspace.

**Comment by kojq** [comment]
I tried to replicate again. Now, using something other than `$TERMINAL` like `$CONSOLE` or `TERM` is fine.

**Comment by vaxerski** [comment]
I don't think hyprlang allows overwriting env vars, and $TERMINAL looks like one.

**Comment by kojq** [comment]
$TERM is one, but works.

**Comment by kojq** [comment]
overwrote my foot to be alacritty

**Comment by vaxerski** [comment]
there aint no way to dump env from hyprlang but make sure it's in hyprland env, you can exec-once = env I guess

**Comment by kojq** [comment]
I know what is happening

**Comment by kojq** [comment]
globbing and splitting

**Comment by kojq** [comment]
$TERM becomes the term name

**Comment by kojq** [comment]
so it becomes alacrittyinal

**Comment by kojq** [comment]
which is not alacritty, so nothing opens

**Comment by kojq** [comment]
qed

**Comment by kojq** [comment]
sry for spam, anw, case closed

**Comment by vaxerski** [comment]
that's a hyprlang bug then

**Comment by kojq** [comment]
cool, ig reference this issue there in new one

**Comment by vaxerski** [comment]
bug been fixed
