### ISSUE TITLE
When laptop lid is closed the display should be disabled

### ISSUE THREAD

**Issue by Un1q32** [hyprwm/Hyprland#5175]
### Description

On Gnome, KDE, Windows, any every other system I've tested this on, if I have a laptop connected to an external monitor and then close the laptop lid, the laptop display is disabled and only the external monitor display is enabled.

**Comment by vaxerski** [comment]
that's up to you to configure. Read the wiki. https://wiki.hyprland.org/Configuring/Binds/#switches
