### ISSUE TITLE
cursor problem

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#5176]
After upgrading from v0.37.0 to v0.37.1, the cursor will be reset to the center of the screen when switching programs in the taskbar. I am using waybar.

**Comment by vaxerski** [comment]
nothing changed between 0.37.0 and 0.37.1 that could cause this.

Also, invalid because you didn't follow the template.

**Comment by hdm9527** [comment]
> nothing changed between 0.37.0 and 0.37.1 that could cause this.
> 
> Also, invalid because you didn't follow the template.

Thank you for your reply. I found the reason. The default value of no_cursor_warps is false. Setting it to true solves the problem.
