### ISSUE TITLE
Arch linux update libhyprcursor conflict with hyprlang

### ISSUE THREAD

**Issue by spigatl** [hyprwm/Hyprland#5179]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

:: Procurando atualizações no AUR...
:: Procurando atualizações nos bancos de dados...
 -> Pacotes que não estão no AUR: alci-grub-theme-git  khotkeys  kpeoplevcard  kquickcharts5  plasma6-applets-window-buttons
 -> Pacotes de debug do AUR em falta: applet-window-buttons-git-debug  hypridle-debug  hyprlock-debug  plasma6-applets-window-buttons-debug  xfce-polkit-debug  yay-debug
 -> Pacotes AUR órfãos (não mantidos): kdav5  krunner5
:: 10 pacotes para atualizar/instalar.
10  arcolinux_repo_3party/zsh-theme-powerlevel10k-git  r4269.3fe8706d-1 -> r4270.da9b0377-1
 9  core/jfsutils                                      1.1.15-8         -> 1.1.15-9
 8  extra/firefox                                      123.0.1-1        -> 124.0-1
 7  extra/hypridle                                     0.1.1-1          -> 0.1.1-2
 6  extra/hyprland                                     0.36.0-1         -> 0.37.1-1
 5  extra/hyprlang                                     0.4.2-1          -> 0.5.0-1
 4  extra/hyprlock                                     0.2.0-1          -> 0.2.0-2
 3  extra/hyprpaper                                    0.6.0-3          -> 0.6.0-4
 2  extra/python-pyparted                              3.13.0-1         -> 3.13.0-3
 1  extra/xdg-desktop-portal-hyprland                  1.3.1-5          -> 1.3.1-6
==> Pacotes a excluir: (ex: "1 2 3", "1-3", "^4" ou nome do repositório)
 -> A exclusão de pacotes pode causar atualizações parciais e quebrar sistemas
==>
Sync Explicit (8): hyprland-0.37.1-1, zsh-theme-powerlevel10k-git-r4270.da9b0377-1, hypridle-0.1.1-2, jfsutils-1.1.15-9, hyprlock-0.2.0-2, firefox-124.0-1, xdg-desktop-portal-hyprland-1.3.1-6, hyprpaper-0.6.0-4
Sync Dependency (2): hyprlang-0.5.0-1, python-pyparted-3.13.0-3
:: Sincronizando a base de dados de pacotes...
 arcolinux_repo                                                                      44,8 KiB   430 KiB/s 00:00 [##################################################################] 100%
 arcolinux_repo_3party                                                              146,8 KiB  1071 KiB/s 00:00 [##################################################################] 100%
 arcolinux_repo_xlarge                                                               17,3 KiB   157 KiB/s 00:00 [##################################################################] 100%
 core está atualizado
 extra está atualizado
 multilib está atualizado
:: Iniciando atualização completa do sistema...
resolvendo dependências...
atenção: não é possível resolver "libhyprcursor.so=0-64", uma dependência de "hyprland"
:: O seguinte pacote não pode ser atualizado devido a dependências não resolvidas:
      hyprland

:: Deseja ignorar o pacote acima para esta atualização? [s/N] s
procurando pacotes conflitantes...
erro: falha ao preparar a transação (não foi possível satisfazer as dependências)
:: a instalação de hyprlang (0.5.0-1) quebra a dependência "libhyprlang.so=1-64" necessária por hyprland
 -> error installing repo packages

### How to reproduce

yay -Syu

**Comment by vaxerski** [comment]
not a hyprland issue and I don't speak portuguese
