### ISSUE TITLE
Workspace selector range doesn't work with monitors

### ISSUE THREAD

**Issue by thejch** [hyprwm/Hyprland#5180]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 95ac8a34b1809375030b4ec2780a2b7a35ae8162 dirty (workspace: fix integer overflow in selector parser (5177)).
Date: Tue Mar 19 19:33:39 2024
Tag: v0.37.1-28-g95ac8a34
```

</details>

### Bug or Regression?

Bug

### Description

Workspace selector range doesn't work with monitors

### How to reproduce

Set rules like this
```
workspace = r[1-5], monitor:WL-1
workspace = r[6-10], monitor:WL-2
```
and restart hyprland
workspace 2 still goes to the second monitor
However, the old way works
```
workspace = 1, monitor:WL-1
workspace = 2, monitor:WL-1
workspace = 3, monitor:WL-1
workspace = 4, monitor:WL-1
workspace = 5, monitor:WL-1
workspace = 6, monitor:WL-2
workspace = 7, monitor:WL-2
workspace = 8, monitor:WL-2
workspace = 9, monitor:WL-2
workspace = 10, monitor:WL-2
```

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/6de9b3f6-0169-48c5-b8c4-15e183b1c569)
that is correct. We cannot match a selector for a workspace that is yet to be created.

**Comment by thejch** [comment]
but this works:
```
workspace = r[1-5], gapsout:100
workspace = r[6-10], gapsout:10
```

**Comment by vaxerski** [comment]
yes, because it's applied after a workspace is already created.

**Comment by vaxerski** [comment]
if you wanna make it supported, feel free

**Comment by Evangelospro** [comment]
This would be really helpful for people like me using an awesome like approach to workspaces, who want e.g first 10 workspaces on first monitor and next 10 on the second monitor. So please consider reopening this as a feature request rather than a bug.
