### ISSUE TITLE
Latest Update broken

### ISSUE THREAD

**Issue by NULL-BITS** [hyprwm/Hyprland#5181]
### Hyprland Version

Hyprland

error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory

### Bug or Regression?

Bug

### Description

On start Hyprland isn't able to find the libaries, reinstalling them changes nothing

### How to reproduce

try to start Hyprland

### Crash reports, logs, images, videos

Hyprland: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory

**Comment by tchofy** [comment]
Try installing hyprlang, it's a dependency that might've not been automatically installed for some reason.

**Comment by DaraghD** [comment]
Can you try run 
`find /usr/lib -type f -name "*.so*" | grep libhyprlang`
If it finds anything you can try and symlink it, 
` sudo ln -s /usr/lib/<the one thats found>  /usr/lib/libhyprlang.so.1`
This may or may not work, i've had similar issues in the past with libraries and this fixed it. Libraries could be in a different place - this is arch atleast.

**Comment by NULL-BITS** [comment]
> Try installing hyprlang, it's a dependency that might've not been automatically installed for some reason.

i already tried that, but with no luck

**Comment by NULL-BITS** [comment]
> Can you try run `find /usr/lib -type f -name "*.so*" | grep libhyprlang` If it finds anything you can try and symlink it, ` sudo ln -s /usr/lib/<the one thats found> /usr/lib/libhyprlang.so.1` This may or may not work, i've had similar issues in the past with libraries and this fixed it. Libraries could be in a different place - this is arch atleast.

removing hyprland-git and installing the latest release of hyprland fixed my issue

**Comment by vaskark** [comment]
I have the exact same issue. I have hyprlang installed, with the symlink, and I'm still not able to login. I'm using 0.37.1 (manual copy install).
Things were working fine a little while ago.

**Comment by DaraghD** [comment]
Did you make the symlink to the library it was looking to specifically ? , in the one I replied to it was `libhyprlang.so.1` but yours may be a different number at the end e.g - If the error was libhyprlang.so.3 , your symlink would be to that.
`sudo ln -s /usr/lib/libhyprlang.so.<number that was found> /usr/lib/libhyprlang.so.<number in error>`
 If the symlink is 100% set up correctly and it still cant find the library then I dont know, sorry.

**Comment by DaraghD** [comment]
> I have the exact same issue. I have hyprlang installed, with the symlink, and I'm still not able to login. I'm using 0.37.1 (manual copy install). Things were working fine a little while ago.

Responded but didnt quote reply, not sure if you get a notification so sending this aswell just incase.

**Comment by vaskark** [comment]
@ DaraghD

Yes. it's libhyprlang.so.1 for me too (although I installed mine to /usr/local) and the symlink points to libhyprlang.so.0.5.0 as needed. Not sure what exactly changed for me. Things were working fine for me until these last few days. Although I am on Ubuntu 23.10 so I realize performance/functionality may be spotty. Things were fine on 0.35.0 but I lost ability to drag floating windows on 0.36.  And now this.

Thanks for responding and for all your effort to help.

**Comment by DaraghD** [comment]
Thats unfortunate, I would suggest making another issue to get more attention or trying the ubuntu forums or hyprland discord. There are a lot of people out there that can definitely help you ( and that have more knowledge than me ), hope you fix it :heart:

**Comment by vaskark** [comment]
Those are great ideas for further help. I'll try again. 

Many thanks. It's a beautiful wm and I hope to continue using it.

**Comment by vaskark** [comment]
Ok. I think I figured it out.
I installed hyprlang into /usr/local. And had no problems til recently.
I needed to do this:

sudo ln -s /usr/local/lib/libhyprlang.so.0.5.0 /usr/**lib**/libhyprlang.so.1 -- NOT /usr/local!

I can login again \o/
I might just install hyprlang fully into /usr just to be safe. Everything else I'll keep as /usr/local until I know different.

**Comment by vaxerski** [comment]
> sudo ln -s /usr/local/lib/libhyprlang.so.0.5.0 /usr/lib/libhyprlang.so.1 -- NOT /usr/local!

please don't do that. Just recompile your hyprland.

**Comment by vaxerski** [comment]
This issue is invalid. Please match your dependencies against your packages.

Arch will do it for you if you use the repos. If you use -git, it's your responsibility.

Symlinking ABI-incompatible .so files will only lead to memory corruption and crashes. Do not link any libraries ever for fucks sake the numbers are there for a reason
