### ISSUE TITLE
config parsing breaking change in 0.37

### ISSUE THREAD

**Issue by nathanchere** [hyprwm/Hyprland#5182]
### Hyprland Version

Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

### Bug or Regression?

Regression

### Description

Previously a comments like these worked fine:

```
#################
#this is a comment which worked with v<0.37
#$CFG_X = 4
```

As of 0.37, all of the above will cause a config parsing error. It seems it only recognises hash followed immediately by a space as a comment, e.g.

```
# ################
# this is a comment which worked with v<0.37
# $CFG_X = 4
```

It also changes the way vectors are parsed, e.g. before `$val = [1 2]` causes a parsing error, it needs to have no braces now i.e. `$val = 1 2`

This is far from the first time a minor version upgrade has broken things like this which appear to be intentional changes.

I realise it can hard to keep track of all these kind of things but maybe some kind of 'breaking changes' in the release notes would be a nice idea?

### How to reproduce

See description

**Comment by rabaimorp** [comment]
Same here. 
Also I use separated files for stuff like keybinds, colors, etc. and thats also shows as an error even tho its still working. for example:
`source=~/.config/hypr/keybinds.conf`

Plus for some reason there are duplicates
in my error message. Config error line 6 and 18 are the same for example

![screenshot_2024-03-20_13-55-03](https://github.com/hyprwm/Hyprland/assets/161316025/42c06c9a-4e59-4d2b-a989-8e3f2cd8a4d0)

**Comment by vaxerski** [comment]
expected behavior, ## is an escape of #

**Comment by rabaimorp** [comment]
My whole config breaking after an update with no warning shouldnt be expected behavior. Neither the other false errors.

> expected behavior, ## is an escape of #

**Comment by vaxerski** [comment]
it's not without warning, you just ignore the warning:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/f3f878b2-c355-4467-ac63-a3febaa8e780)

**Comment by rabaimorp** [comment]
> it's not without warning, you just ignore the warning: ![image](https://private-user-images.githubusercontent.com/43317083/314617753-f3f878b2-c355-4467-ac63-a3febaa8e780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzQ4MDEsIm5iZiI6MTcxMDk3NDUwMSwicGF0aCI6Ii80MzMxNzA4My8zMTQ2MTc3NTMtZjNmODc4YjItYzM1NS00NDY3LWFjNjMtYTNmZWJhYThlNzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIyNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmU3ZGQwZjNjMDdhNmRmOTZiYjJlNzAyMjYyNjllN2M2ZWVmY2IxYWU5YTQ4NWNlMzk2YmEzNTY1YWQxYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Acozp3yHMIWxjD2fCUweBGZqNaccOG6b-HNkY_lN_TE)

I wasn't refering to that. I though a bunch of my other stuff broke, because I had a bunch of fake errors shown as well, but disappeared as I fixed the double ## s, so everything is fine now 👍

**Comment by vaxerski** [comment]
they aren't fake...
