### ISSUE TITLE
text-input-v3 clients sometimes crash Hyprland

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#5189]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9ddf1b105e1b63a77b851af5e541a9412b0e0928 dirty (tablet: Add left_handed option for tablets (5178)).
Date: Wed Mar 20 12:00:43 2024
Tag: v0.37.1-29-g9ddf1b10

flags: (if any)


System Information:
System name: Linux
Node name: arch-g14
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hy3 by outfoxxed ver 0.1
```

</details>

### Bug or Regression?

Regression

### Description

When using text-input-v3 clients, hyprland sometimes crashes. Haven't bisected yet but I guess this is a regression from https://github.com/hyprwm/Hyprland/pull/5147 , so CC @sujoshua .

### How to reproduce

It happens when using text-input-v3 clients but I'm not sure how to reliable repro.

### Crash reports, logs, images, videos

This is a full gdb session, including `bt full` and printing some variables.
[gdb.txt](https://github.com/hyprwm/Hyprland/files/14668985/gdb.txt)

**Comment by q234rty** [comment]
It's mostly gtk3 software(I don't have GTK_IM_MODUlE`

**Comment by FUFSoB** [comment]
Same issue here. Reliable steps to reproduce:
1. Have `/usr/bin/foot --server=3` active with either `exec-once = ...` or `systemctl --user start foot-server`
2. Open `footclient` with keybind on empty workspace
3. Close footclient
4. Open footclient (or anything else, also tested with Qt and Chromium apps) and get a crash

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14671075/patch.txt)
try this

**Comment by q234rty** [comment]
Unfortunately Hyprland seem to crash with the same bt more under the above patch.

**Comment by vaxerski** [comment]
well dunno then, can't really repro in a nest. I'll let @sujoshua try and repro this

**Comment by sujoshua** [comment]
reproduced. Foot in server mode will not send destory event to Hyprland when a window is closed. Hmm.. then a listener to listen surface destoryed in Hyprland side is needed

**Comment by Zyuke** [comment]
encountered similar issue when exiting kitty terminal

crash report:
[hyprlandCrashReport3095.txt](https://github.com/hyprwm/Hyprland/files/14686709/hyprlandCrashReport3095.txt)

**Comment by sujoshua** [comment]
can you test this ?

**Comment by Elixity1** [comment]
I believe I have the same problem too, infact my hyprland crashed while making this report and I had to re-write this so thats fun. Anyway I got a problem with something to do with text-input-v1 clients registering as v3 or   something weird but that's also crashing my thing.

Opening Kvantum:  [hyprlandCrashReport927.txt](https://github.com/hyprwm/Hyprland/files/14712578/hyprlandCrashReport927.txt)

Opening KDE system setting by accident:  [hyprlandCrashReport3874.txt](https://github.com/hyprwm/Hyprland/files/14712703/hyprlandCrashReport3874.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14715299/patch.txt)
reprod and this seems to fix it for me

**Comment by FUFSoB** [comment]
Patch does fix original repro steps, but does not fix it if on step 2 you open two `footclient` instances.

**Comment by vaxerski** [comment]
I've debugged that - it seems like case 2 is a wlr bug? Anyways it looks unrelated to this so I'll commit the patch.

**Comment by vaxerski** [comment]
it's not a wlr bug - it's a regression from #5147 that I am unable to track down why it happens.

**Comment by vaxerski** [comment]
found it. Will post a patch soon. Very poor wlroots design

**Comment by vaxerski** [comment]
should be done.

**Comment by MoetaYuko** [comment]
There's still something wrong. I can't use IME in Firefox textboxes, and the workaround is to move focus to another window and move back. The process must be repeated once the textbox loses focus (e.g. mouse click on a link).

**Comment by vaxerski** [comment]
I use firefox daily and have never encountered that. Repro steps?

**Comment by MoetaYuko** [comment]
> I use firefox daily and have never encountered that. Repro steps? (also always try updating first)

Just upgraded to acf15e5579a5d2bbbe4a13e87306445e31ea5e4f but still reproducible. I use fcitx5 and set ctrl+shift as the switching combo:
1. Launch Firefox
2. focus any textbox (the built-in address bar or one on the webpage) and press ctrl+shift, it may or may not respond depending on the initial window state
3. (if step2 responded) click anywhere else to unfocus from the textbox, then click the textbox to focus again, ctrl+shift will no longer respond and IME won't be activated
4. move the cursor to focus on any other application window, then move back to Firefox, you should be able to activate the IME now
5. repeat step4 once the textbox lost focus

**Comment by sungyoonc** [comment]
@MoetaYuko Can you try ae52b7f4680716976d05b638aaa90e169d199117?

**Comment by MoetaYuko** [comment]
> @MoetaYuko Can you try [ae52b7f](https://github.com/hyprwm/Hyprland/commit/ae52b7f4680716976d05b638aaa90e169d199117)?

It works, thanks for the fix.
