### ISSUE TITLE
Change gaps on the fly

### ISSUE THREAD

**Issue by arifvn** [hyprwm/Hyprland#519]
Hi, first I wonder if it was possible to change the gaps on the fly with some keybindings? The current workaround I achieved is by running some little bash scripts using `awk` or `sed` to change config file related to gaps on the fly (because the config is reloaded automatically anyway)
but I just imagine if it possible using the official way.

Second, is it also possible to for example resize the window by just holding the keys a couple seconds, instead of pressing it multiple times?

btw, thanks for such great tool.

**Comment by KyleUltimate** [comment]
> Second, is it also possible to for example resize the window by just holding the keys a couple seconds, instead of pressing it multiple times?

I think you want `binde` as state in the wiki.
As of the first problem you said, you could probably use hyprctl's keyword to do it
https://github.com/hyprwm/Hyprland/wiki/Using-hyprctl

**Comment by vaxerski** [comment]
exactly as above.
