### ISSUE TITLE
Huge Borders on Some Floating Windows

### ISSUE THREAD

**Issue by mtwb47** [hyprwm/Hyprland#5192]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh

Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: ares
Release: 6.7.9-1-default
Version: #1 SMP PREEMPT_DYNAMIC Thu Mar  7 06:07:11 UTC 2024 (6049de6)


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240314"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240314"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240314:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240314"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

On some floating windows, usually file pickers, you get a huge border. 
![1710383012_grim](https://github.com/hyprwm/Hyprland/assets/32562514/a32e0a9b-d8d7-48ac-afe9-1a372959daa3)

It's not all floating windows, as if you pull a window out of the tile and into a floating version of itself, the boarders look fine. 
![1710954919_grim](https://github.com/hyprwm/Hyprland/assets/32562514/29a1f9c0-09b8-4986-a33b-85bed5aeeaca)

All I've ever really seen it on is the file picker. And it's always the gtk file picker. Unsure if it would happen if the qt file picker was used. 

A link to my dots if needed: https://gitlab.com/thelinuxcast/my-dots/-/tree/master/hypr?ref_type=heads

Using openSUSE TW, with hyprland installed from the main repos. Version 0.36.0
### How to reproduce

Bring up a file picker.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14670310/hyprland.log)

**Comment by vaxerski** [comment]
I think those are xwayland apps that add client-side window decorations, is it running in xwayland?

**Comment by mtwb47** [comment]
Webcord probably is. Vivaldi, I think is using Wayland, at least that is what the settings say. Is there a way to check?

And I just noticed that where I find this is in Electron/Chromium based browsers. Now, is that because that's the only place where I ever get a file picker or is it because it's an Electron/Chromium problem? IDK. Could be either.

**Comment by MrYuto** [comment]
I think it's an issue related to decoration blue and by disabling it it's no longer visible. 

![image](https://github.com/hyprwm/Hyprland/assets/75252297/35dd43a4-1216-4252-96b2-ea6e6b874af2)

**Comment by vaxerski** [comment]
you can check with hyprctl clients

**Comment by mtwb47** [comment]
@MrYuto All disabling blur does for me is remove the color. I think if I also got rid of the border completely it'd go away, but that'd just be a work around. 
![1711038940_grim](https://github.com/hyprwm/Hyprland/assets/32562514/dc40dc89-d941-4336-9dbf-e7daac55f8bd)

**Comment by mtwb47** [comment]
> you can check with hyprctl clients

Both Vivaldi and Webcord, where I see this happening, are xwayland.

**Comment by vaxerski** [comment]
I don't think this is fixable on my side - well, in xdg we get info about CSD, I don't think we do in xwayland. Have you tried seeing if this is equally broken on sway?

**Comment by mtwb47** [comment]
I haven't. If I can get it to actually work on openSUSE I will try. I will check on River later on though, as I have that installed.

**Comment by mtwb47** [comment]
For anyone who comes across this, and you want to fix it, add `--ozone-platform-hint=auto` as a flat to the application if it is an electron app, where this seems to happen most often. If it's the Chromium browser itself, in chrome://flags there will be a place where you can force Chrome/Chromium itself to use Wayland. On Vivaldi its vivaldi://flags. Changing it to  Wayland from Auto/default/xorg will fix the issue.

**Comment by 0pLuS0** [comment]
Hello,

I'm running CachyOS, hyprland 0.49

I'm seeing this also on a lot of different windows too...

This is Thunar Preferences;

![Image](https://github.com/user-attachments/assets/3531ead2-1da5-42e0-b628-9ed4d1832254)

Is there a fix for this?

THANKS
