### ISSUE TITLE
workspace_center_on stopped working

### ISSUE THREAD

**Issue by aloispichler** [hyprwm/Hyprland#5194]
### Hyprland Version

0.37.1

### Bug or Regression?

Bug

### Description

`workspace_center_on` stopped working

### How to reproduce

`workspace_center_on` stopped working

**Comment by vaxerski** [comment]
seems to be working just fine on my end. I'll need more repro steps.

**Comment by aloispichler** [comment]
what I actually want (and had) is that the mouse should not follow the window when switching windows (the mouse should just stick on the old window) – is there a new setting to achieve this???

This stopped working. Instead, I see is that switching windows always centers the cursor on the new window and `workspace_center_on` does not change anything.

**Comment by vaxerski** [comment]
general:no_mouse_warps? I don't think I understand

**Comment by aloispichler** [comment]
Indeed, `general:no_cursor_warps` solves my problem, thank you!
