### ISSUE TITLE
Damage in Steam is broken

### ISSUE THREAD

**Issue by phonetic112** [hyprwm/Hyprland#5196]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit bcba3951f45f11245d424274130eb3a0ac790d93 dirty (input: Only limit drag resizes (5164)).
Date: Tue Mar 19 12:03:31 2024
Tag: v0.37.1-22-gbcba3951

flags: (if any)


System Information:
System name: Linux
Node name: artix
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 17 Mar 2024 08:05:02 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

Damage in steam is borked after 301b48b74087cc59753ffa144b215540e6f82831

### How to reproduce

1. Open Steam
2. Interact with the library a bit, open a game install prompt, open update posts, etc. Damage should be bugged after awhile

**Comment by vaxerski** [comment]
> Interact with the library a bit, open a game install prompt, open update posts, etc. Damage should be bugged after awhile

that is definitely one of the reproduction steps of all time. Can't repro. Anything else?

**Comment by phonetic112** [comment]
Ok I found some better steps:

1. Open steam
2. Click on any game that hasn't been installed
3. Wait 30 seconds
4. Click install
5. Damage should be bugged

**Comment by phonetic112** [comment]
Video showing it

https://github.com/hyprwm/Hyprland/assets/73647246/2094f5ba-076b-4dc8-a3dd-4ff046f7c122
