### ISSUE TITLE
The `nomaximizerequest` and `nofullscreenrequest` windowrules have disappeared

### ISSUE THREAD

**Issue by KoyeBosh** [hyprwm/Hyprland#5197]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit bfc95e992d460cbefe2c69de04da52e6089f6258 dirty (swipe: fix nullptr in `onSwipeUpdate` (5191)).
Date: Wed Mar 20 19:13:31 2024
Tag: v0.37.1-32-gbfc95e99

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a1] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Having either `nofullscreenrequest` or `nomaximizerequest` in your config now throws an error and allows windows to maximize or enter fullscreen without user input. 

### How to reproduce

I am having this bug triggered by the line `windowrulev2 = nomaximizerequest, class:.*`

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/69683207/47e36883-82f1-4e77-bc89-4da6e7e12e3f)
`Config error in file <path>/hyprland.conf at line 128: Invalid rulev2 found: nomaximizerequest`
`Config error in file <path>/hyprland.conf at line 128: Invalid rulev2 found: nofullscreenrequest`

**Comment by phonetic112** [comment]
They were removed, you should use:

```
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = suppressevent fullscreen, class:.*
```

**Comment by KoyeBosh** [comment]
Aha, my confusion comes from the fact that they are still listed as windowrules on the wiki. Thank you!

**Comment by phonetic112** [comment]
they're not tho? make sure you've selected the latest version in the top left

**Comment by KoyeBosh** [comment]
You are right! I didn't realize that the wiki saved your preference and I had to change versions. This is on me, lol
