### ISSUE TITLE
Make the groups have an option to display their names

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#520]
Basically it's just like i3 tabbed, this will make differentiate between normal and groups easier, since the only difference between them now is the border color

**Comment by KaspervdHeijden** [comment]
In addition, when having `no_gaps_when_only` set to `true`, there is no visual indication of a window being in a group (tab)

**Comment by wilecoyote2015** [comment]
Furthermore, in case of groups, the window titles to not necessarily occlude additional space, as the may (and in my opinion should) replace the visual group indication).

Personally, I try to transition from Sway / i3 and the missing window titles in groups appear as a strong drawback regarding productivity, as I use groups extensively and it is difficult to keep track on which windows are present (and in which order) in the groups without titles.

**Comment by vaxerski** [comment]
y'all's lucky day today :)

206ac000b98ebab6acef9047f2dbd211d715c5b4

![image](https://github.com/hyprwm/Hyprland/assets/43317083/57540518-d7e3-4c89-afbd-600579fe9f6d)
