### ISSUE TITLE
After the update, there are some error messages after booting up the computer

### ISSUE THREAD

**Issue by FriendsZonn** [hyprwm/Hyprland#5200]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

System Information:
System name: Linux
Node name: fri
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000

GPU information: 
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
</details>

### Bug or Regression?

Bug

### Description

Config error in file /home/fds/dotfiles/hypr/conf/ml4w.conf at line 7 Invalid rulev2 found: no maximizer request
Config error in file /home/fds/dotfiles/hypr/conf/ml4w.conf at line 7 Invalid rulev2 found:nofullscreenrequest
Something like that

### How to reproduce

NO

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/108604742/ed670545-f21e-4e51-b839-247c3a2a2856)

**Comment by pyiedpiper** [comment]
i see there is new entry on the wiki...  suppressevent maxsize. 
works but  wlr/taskbar(waybar) is broken with new configs after hypr update on my end.

**Comment by vaxerski** [comment]
please read the breaking changes section of the 0.36 release.

**Comment by FriendsZonn** [comment]
> please read the breaking changes section of the 0.36 release.

Thank you for your guidance. I am a beginner and I hope my problem has not caused you any trouble
