### ISSUE TITLE
hyprland.conf error at the sensitivity setting. 

### ISSUE THREAD

**Issue by musicfunfan** [hyprwm/Hyprland#5209]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] [1002:67ef] (rev e5) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

```

</details>

### Bug or Regression?

Bug

### Description

So i start my computer today after an update. And now i get this error. 
![εικόνα](https://github.com/hyprwm/Hyprland/assets/86926443/6c39b636-eb4a-49b1-9ac9-cee5e5246ec5)

Did something change on the config file? If so what i need to do?

All i understand from the massage is that i need to specify the device name... on the setting but i am not sure what the syntax is... I need to specify like mouse model after the ``device:`` or something like that ?

This is the line/block from my config file.

```config
device:epic-mouse-v1 {
    sensitivity = -0.5
}
```

If my full config is needed is available [here](https://gitlab.com/musicfunfan/main_configs_files/-/blob/main/hyprland/hyprland.conf?ref_type=heads).  

### How to reproduce

I thing you can paste my config block 
```config
device:epic-mouse-v1 {
    sensitivity = -0.5
}
```
On a ``hyprland.conf`` file. And load the config.

**Comment by tharrmeehan** [comment]
use hyprctl devices to find your real mouse name and replace epic-mouse-v1 with the name of your mouse.

**Comment by musicfunfan** [comment]
So i did that nothing change.
```config
device:logitech-g502-hero-gaming-mouse {
    sensitivity = -0.5
}
```
hyprctl devices | grep mouse
		logitech-g502-hero-gaming-mouse
		logitech-g502-hero-gaming-mouse-keyboard-1
		logitech-g502-hero-gaming-mouse-keyboard
```
This is the out put. 

I added the first think.

**Comment by tharrmeehan** [comment]
sorry made a mistake, ignore my comment

try 
input {
sensitivity = -0.5
}

instead of the mouse

**Comment by tharrmeehan** [comment]
Replace device:logitech-g502-hero-gaming-mouse with input basically

**Comment by musicfunfan** [comment]
Ok. 

This is working. Thenx you for your help.

**Comment by tharrmeehan** [comment]
If you still want to seperately edit your mouse sensitivity by any chance, the syntax changed and the new one would be:
![image](https://github.com/hyprwm/Hyprland/assets/58373200/efc1d402-9267-49f8-ab2b-6dccc77d8be5)
where you replace epic-mouse-v1 with your logitech mouse name (if you need it)
cheers

**Comment by Ligthiago** [comment]
Nah, input is global stuff. It will work, but not the same if you have several devices. Basically per-device config is changed in new version, see here https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs

You need something like this

```
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
```

instead of 

```
device:epic-mouse-v1 {
    sensitivity = -0.5
}
```

**Comment by musicfunfan** [comment]
This setting was this way by default... I did not want to change anything about the mouse.... sooo...

Its better to comment it out then, and keep it here as comment for documentation?.
