### ISSUE TITLE
stayfocus or idlehabit does not work with an new empty workspace

### ISSUE THREAD

**Issue by YjzJim** [hyprwm/Hyprland#5214]
### Hyprland Version

Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

System Information:
System name: Linux
Node name: Arch
Release: 6.7.10-lqx1-2-lqx
Version: #1 ZEN SMP PREEMPT Mon, 18 Mar 2024 08:04:02 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Regression

### Description

when no window is present in a new workspace, opening rofi will not shift focus on it. Even if stayfocus and idlehabit is used. If i need to search i have to shift focus to rofi.

### How to reproduce

open rofi in new empty workspace and try to type.

**Comment by vaxerski** [comment]
that hard to use the search feature? #5142
