### ISSUE TITLE
[FEATURE] add bind descriptions

### ISSUE THREAD

**Issue by ArtemSmaznov** [hyprwm/Hyprland#5215]
### Description

# Request
add an optional `description` parameter to binds
```
bind=MODS,key,dispatcher,params,description
```
so it would show in `hyprctl binds -j`
```
{
  "locked": false,
  "mouse": false,
  "release": false,
  "repeat": false,
  "non_consuming": false,
  "modmask": 0,
  "submap": "toggle",
  "key": "g",
  "keycode": 0,
  "catch_all": false,
  "dispatcher": "exec",
  "arg": "/home/artem/.config/hypr/scripts/toggle-gaps.sh 20",
  "description": "toggle gaps"
}
```

# Use Case
I am currently writing a script that would print my binds for a given submap (probably will write one for all binds as well later) and my current logic is to parse my `hyprland.conf` which is structured like so:
```
bind = SUPER , t , submap , toggle

submap = toggle
bind =       , s , exec   , $myHyprConfig/toggle-status-bar.sh                        # toggle status bar
bind =       , b , exec   , $myHyprConfig/toggle-borders.sh $borders                  # toggle window borders
bind =       , c , exec   , $myHyprConfig/toggle-corners.sh $corners                  # toggle corners
bind =       , g , exec   , $myHyprConfig/toggle-gaps.sh $gaps_inner                  # toggle gaps
bind =       , z , exec   , $myHyprConfig/toggle-zen.sh $borders $corners $gaps_inner # toggle zen mode
bind =       , h , exec   , $myScript/toggle-headphones.sh                            # toggle bluetooth headphones

# reset submap
bind = , escape , submap , reset
bind = , s      , submap , reset
bind = , b      , submap , reset
bind = , c      , submap , reset
bind = , g      , submap , reset
bind = , z      , submap , reset
bind = , h      , submap , reset

submap = reset
```
All I am really doing is printing all lines between `submap\s*=\s*$submap` and `# reset submap`, and awking it to print the second parameter and the comment line resulting in this:
```
 s - toggle status bar
 b - toggle window borders
 c - toggle corners
 g - toggle gaps
 z - toggle zen mode
 h - toggle bluetooth headphones
```

This is fine but I feels like a waste to not utilize `hyprctl binds` functionality, but that doesn't have descriptions so I can't use that as it is.

# Implementation
Ideally, I see this added as a last optional parameter so it doesn't break anyone's config (default to an empty string or null when not specified). But I don't know if there are any dispatchers that accept multiple parameters making this impossible. If that is the case maybe it can be this instead
```bind=MODS,key,description,dispatcher,params```

**Comment by vaxerski** [comment]
not possible, impossible to detect description with exec scripts.

**Comment by Ligthiago** [comment]
Sorry for annoyance, but why exactly is not possible to detect it, if they just separated by comma in this case? Like detect next comma is hard or something?

**Comment by ArtemSmaznov** [comment]
@vaxerski are you talking specifically this suggestion
`bind=MODS,key,dispatcher,params,description`
or does that apply to putting `description` param before `dispatcher` as well?
`bind=MODS,key,description,dispatcher,params`

if either is impossible then can we come up with some other mechanism to achieve this? Maybe something like this is possible to assign description to existing bind:
```
bind = , h , exec , $myScript/toggle-headphones.sh
bind_desc = , h , "toggle headphones"
```

**Comment by vaxerski** [comment]
both suck, one is a breaking change and has limitations, the other isnt possible.

bind_desc is an option, but I still find this kinda stupid.

**Comment by ArtemSmaznov** [comment]
Yeah, I sort of agree. I saw no drawback to `description` at the end, but the others do suck a bit.

**Comment by f0rdprefect** [comment]
Glad I found this issue because I was going to suggest something like this. I still think it would be beneficial do have a way to lookup things which are bound and see which key combos they have been assigned to. Maybe something `rofi` and other `dmenu` like tools could digest and make available. If starting a config from scratch, of course muscle memory will develop as you go. If taking pieces and parts from the internets that is a different story...

**Comment by ArtemSmaznov** [comment]
looks like this has been added after all 😄 
https://wiki.hyprland.org/Configuring/Binds/#description
