### ISSUE TITLE
Unexpected key mappings

### ISSUE THREAD

**Issue by CaptainBloodz** [hyprwm/Hyprland#5217]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: amd64
Release: 6.8.0-gentoo-std
Version: #13 SMP Fri Mar 15 14:24:18 EAT 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

pc104 keybord here.

Most keys between alpha block and numpad block have unexpected values as listed below:

up arrow:
detected:
keycode 98 (keysym 0xff26, Katakana)
expected:
keycode 98 (keysym 0xff52, Up)

left arrow:
detected:
keycode 100 (keysym 0xff23, Henkan_Mode)
expected:
keycode 100 (keysym 0xff51, Left)

right arrow:
detected:
keycode 102 (keysym 0xff22, Muhenkan)
expected:
keycode 102 (keysym 0xff53, Right)

down arrow:
detected:
keycode 104 (keysym 0xff8d, KP_Enter)
expected:
keycode 104 (keysym 0xff54, Down)

insert
detected:
keycode 106 (keysym 0xffaf, KP_Divide)
expected:
keycode 106 (keysym 0xff63, Insert)

del
detected:
Can't capture, add light to the screen
expected:
state 0x10, keycode 107 (keysym 0xffff, Delete)

pgdown
detected:
keycode 105 (keysym 0xffe4, Control_R)
expected:
keycode 105 (keysym 0xff56, Next)

pgup
detected:
keycode 99 (keysym 0xff25, Hiragana)
expected:
keycode 99 (keysym 0xff55, Prior)

home
detected:
keycode 97 (keysym 0x0, NoSymbol)
expected:
keycode 97 (keysym 0xff50, Home)

end
detected:
keycode 103 (keysym 0x0, NoSymbol)
expected:
keycode 103 (keysym 0xff57, End)

printscreen/sysreq
detected:
keycode 111 (keysym 0xff52, Up)
expected:
keycode 111 (keysym 0xff61, Print)

scrolllock
detected:
keycode 78 (keysym 0xff14, Scroll_Lock)
expected:
keycode 78 (keysym 0xff14, Scroll_Lock)

pause/break
detected:
keycode 110 (keysym 0xff50, Home) in repeated mode
expected:
keycode 110 (keysym 0xff6b, Break)

### How to reproduce

use xev

### Crash reports, logs, images, videos

Hyprland launched from a X11 terminal.

**Comment by vaxerski** [comment]
> Hyprland launched from a X11 terminal.

yea we dont support that, how did it even start? the backend is disabled, rofl

anyways keyboard is xkb / wlr, not us
