### ISSUE TITLE
Move window to new workspace

### ISSUE THREAD

**Issue by mshzsh** [hyprwm/Hyprland#522]
The `movetoworkspace,e+1`  takes the window only in already created workspaces and it is not possible to create new workspace and move to it after last workspace

**Comment by vaxerski** [comment]
yes thats what e means

**Comment by mshzsh** [comment]
Yes, I read the new documentation (wiki.hyprland.org) and realized that I should use `movetoworkspace,+1` .
I have an unrelated question, how should I view current keyborad layout? for example  us or de.
`setxkbmap` and `swaymsg` not working on hyprland

**Comment by vaxerski** [comment]
`hyprctl devices` should show the active keymap for each keyboard.

**Comment by mshzsh** [comment]
`hyprctl devices` always shows `active keymap: English (US)` even if the keyboard language is german or persian

**Comment by vaxerski** [comment]
should have been fixed 11 minutes ago with 6e2467cc24f8afb70a4aaad3841a7c41fbc568b5

**Comment by romanstingler** [comment]
@mshzsh could you close this issue if it is resolved for you

**Comment by vaxerski** [comment]
can be closed iirc with r+1
