### ISSUE TITLE
hyprland crashes when windows popup to prompt the user 

### ISSUE THREAD

**Issue by Mahgozar** [hyprwm/Hyprland#5221]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9bad62b85f179ad2c95c6e7f734768ef060a604b dirty (layershell: release all mouse buttons before focus on new ls (5219)).
Date: Fri Mar 22 02:28:50 2024
Tag: v0.37.1-39-g9bad62b8

flags: (if any)


System Information:
System name: Linux
Node name: haku
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprgrass by horriblename ver 0.5
```

</details>

### Bug or Regression?

Bug

### Description

hyprland crashes when programs open popup windows prompting for saving files or attaching something. it literally crashed as i was attaching the previous crash report for this issue. 

### How to reproduce

save a file in a program that asks you where it should put the file or anything that prompts a new window, it will cause a crash 

### Crash reports, logs, images, videos

[hyprlandCrashReport6569.txt](https://github.com/hyprwm/Hyprland/files/14718859/hyprlandCrashReport6569.txt)

**Comment by command-z-z** [comment]
same the problem:) But for me, i can report this bug, when I often click the swaync icon in waybar(same the window popup).

**Comment by vaxerski** [comment]
dupe #5189
