### ISSUE TITLE
Crash at startup (last 24h, arch)

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#5225]
### Hyprland Version

can't run it as I can't login into Hyprland.

### Bug or Regression?

Bug

### Description

Probably triggered by a mesa (stable) update considering the error is `amdgpu: amdgpu_cs_ctx_create2 failed. (-13)`

### How to reproduce

On arch linux using a AMD gpu, try to start Hyprland normally.

### Crash reports, logs, images, videos

https://pastebin.com/LMv3xHzh

**Comment by vaxerski** [comment]
thats a problem with your system / drivers

**Comment by Zeioth** [comment]
Ok I got that error because I was running Hyprland from the terminal in full screen. If I do it without full screen I get the actual error: https://pastebin.com/raw/LmNtquGw

By removing my config and using the generated one, I can login into wayland correctly. So I guess I'll add my old config from scratch and try to figure out what breaks it (I haven't changed anything recently).

**Comment by Zeioth** [comment]
I see there have been deep changes in the config. I got it working already. I'll update my config with the new changes later.

https://github.com/Zeioth/zeioth-hyprland-config
