### ISSUE TITLE
random crashes (only while running dragons dogma 2?)

### ISSUE THREAD

**Issue by cndofx** [hyprwm/Hyprland#5228]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9bad62b85f179ad2c95c6e7f734768ef060a604b dirty (layershell: release all mouse buttons before focus on new ls (5219)).
Date: Thu Mar 21 19:28:50 2024
Tag: v0.37.1-39-g9bad62b8

flags: (if any)


System Information:
System name: Linux
Node name: taylorpc
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
2f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

hyprland will randomly crash, seemingly only while running dragon's dogma 2. I've had 5 or 6 crashes in the last couple days with DD2, and zero crashes ever otherwise. Issue occurred on hyprland 0.35, still occurs on 37.1/latest.

after the crash where i get booted to the tty, i ctrl+c to exit what remains and run `Hyprland` again 
at this point, DD2 can't seem to launch anymore while other games still work fine?
i doubt it's really a hyprland issue but any pointers as to what else it might be would be appreciated

### How to reproduce

play dragon's dogma 2 and wait indefinitely :(
seems to crash more frequently during loading screens 

### Crash reports, logs, images, videos

[hyprlandCrashReport762.txt](https://github.com/hyprwm/Hyprland/files/14729978/hyprlandCrashReport762.txt)
[hyprlandCrashReport766.txt](https://github.com/hyprwm/Hyprland/files/14729979/hyprlandCrashReport766.txt)
[hyprlandCrashReport780.txt](https://github.com/hyprwm/Hyprland/files/14729980/hyprlandCrashReport780.txt)

**Comment by vaxerski** [comment]
```
[CRITICAL] 
==========================================================================================
ASSERTION FAILED! 

Aborting, glGetGraphicsResetStatus returned GL_INNOCENT_CONTEXT_RESET. Cannot continue until proper GPU reset handling is implemented.

at: line 239 in OpenGL.cpp
```

Blame your game or gpu driver.
