### ISSUE TITLE
Monocle alternative to full screen. (and automatic monocle?)

### ISSUE THREAD

**Issue by nosvagor** [hyprwm/Hyprland#523]
I have a large monitor, and full screen is often too much. Other window managers like bspwm have a monocle layout, which I think is just all the windows stacked on top of each other and can be cycled or something like that. 

However, my primary use case: if I have just one or two windows, I'd prefer a different layout, with much larger gaps. Ideally, I could also toggle this layout to get a pseudo full screen effect on workspaces with many windows. 

I realize that I could probably manually with sockets (https://github.com/hyprwm/Hyprland/wiki/Expanding-functionality), but I'm not quite sure how to do so. Perhaps expanding this wiki (https://github.com/hyprwm/Hyprland/wiki/IPC) would be enough to allow me to create such scripts.

**Comment by vaxerski** [comment]
technically, monocle is automatic when you enter fullscreen. Using cyclenext / movefocus will select a new fullscreen window.

> However, my primary use case: if I have just one or two windows, I'd prefer a different layout, with much larger gaps. Ideally, I could also toggle this layout to get a pseudo full screen effect on workspaces with many windows.

"pseudo" fullscreen, you mean fullscreen 1 (maximize)? That's already a thing.

A script - you need to be more precise when requesting a script. Your descriptions are pretty vague.

**Comment by nosvagor** [comment]
Oh, missesd
