### ISSUE TITLE
`blur` window rule

### ISSUE THREAD

**Issue by somebody1234** [hyprwm/Hyprland#5230]
### Description

The opposite of `noblur` -  uses the blur settings configured in the config for the window, assuming in config, `decoration.blur.enabled = false`

**Comment by vaxerski** [comment]
wouldn't that be very confusing? conflicts can happen between blur and noblur, what then?

**Comment by somebody1234** [comment]
i mean, i think ideally it'd be `blur true` and `blur false` maybe? and then `blur` window rule in general would just override global blur.

i guess it isn't really that vital to my setup though
