### ISSUE TITLE
Hyprland crashes when opening a layer with an input

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#5231]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 8c88689faf691a4369528e6d3d52c024cd61125d  ().
Date: 2024-03-22
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: wim
Release: 6.8.0-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev d1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240321.20f77aa"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hyprgrass by horriblename ver 0.6
  hycov by DreamMaoMao ver 0.3
```

</details>

### Bug or Regression?

Bug

### Description

Opening a layer with an text input crashes Hyprland since 9f2ed02f35232f0362db45d5f580025f5724500a.

### How to reproduce

Open a layer such as an AGS widget with a text input

### Crash reports, logs, images, videos

[hyprlandCrashReport13309.txt](https://github.com/hyprwm/Hyprland/files/14730539/hyprlandCrashReport13309.txt)

**Comment by sungyoonc** [comment]
@matt1432  Can you check if it still crashes?

**Comment by matt1432** [comment]
@sungyoonc unfortunately still getting the same error as of c7fbea3368452c34c47a4a634e642de6cd4090cb

[hyprlandCrashReport3278.txt](https://github.com/hyprwm/Hyprland/files/14734000/hyprlandCrashReport3278.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14734162/patch.txt)
how about this

**Comment by matt1432** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14734162/patch.txt) how about this

Looks like this fixes it, thank you
