### ISSUE TITLE
Facing random Crashes on hyprland

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#5233]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit bfc95e992d460cbefe2c69de04da52e6089f6258 dirty (swipe: fix nullptr in `onSwipeUpdate` (5191)).
Date: Wed Mar 20 23:43:31 2024
Tag: v0.37.1-32-gbfc95e99

flags: (if any)


System Information:
System name: Linux
Node name: mach
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hypr-darkwindow by micha4w ver 1.0.0


```

</details>

### Bug or Regression?

Bug

### Description

Randomly Hyprland will Crash (No Specific Pattern Observed)

### How to reproduce

Just Random

### Crash reports, logs, images, videos

[hyprlandCrashReport905.txt](https://github.com/hyprwm/Hyprland/files/14731196/hyprlandCrashReport905.txt)
[hyprlandCrashReport2036.txt](https://github.com/hyprwm/Hyprland/files/14731197/hyprlandCrashReport2036.txt)
[hyprlandCrashReport4030.txt](https://github.com/hyprwm/Hyprland/files/14731198/hyprlandCrashReport4030.txt)
[hyprlandCrashReport12972.txt](https://github.com/hyprwm/Hyprland/files/14731199/hyprlandCrashReport12972.txt)
[hyprlandCrashReport29185.txt](https://github.com/hyprwm/Hyprland/files/14731200/hyprlandCrashReport29185.txt)
[hyprlandCrashReport41737.txt](https://github.com/hyprwm/Hyprland/files/14731201/hyprlandCrashReport41737.txt)
[hyprlandCrashReport80498.txt](https://github.com/hyprwm/Hyprland/files/14731202/hyprlandCrashReport80498.txt)
[hyprlandCrashReport650639.txt](https://github.com/hyprwm/Hyprland/files/14731203/hyprlandCrashReport650639.txt)

**Comment by niksingh710** [comment]
As the crashes were to often i switched to `hyprland` package instead of using `-git` one 

and found out that `https://github.com/Alexays/Waybar/issues/3042` is not happening anymore.
now i think the issue on waybar has nothing to with waybar it has to do something with hyprland.

**Comment by vaxerski** [comment]
all your crashes happen in DarkWindow.so, can you disable that plugin?

**Comment by niksingh710** [comment]
will close this in a day after observing.
btw give an invert color option in hyprland by default.

**Comment by vaxerski** [comment]
wdym, you have screen shareds

**Comment by niksingh710** [comment]
> wdym, you have screen shareds

Yeah, Shader feature is there.
will try `hyprshade`

**Comment by niksingh710** [comment]
seems the cause was `hycov` plugin as it is not maintained anymore.
