### ISSUE TITLE
hyprland setcursor don't work anymore

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/Hyprland#5237]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: zeioht-pc
Release: 6.6.1-273-tkg-eevdf
Version: #1 SMP PREEMPT_DYNAMIC TKG Thu, 09 Nov 2023 05:15:13 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])
2d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

`hyprctl setcursor` don't work as expected.

### How to reproduce

Without any of the next env vars defined
```
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,108
env = HYPRCURSOR_THEME,Adwaita
env = HYPRCURSOR_SIZE,108 
```
run
> hyprctl setcursor Adwaita 108

It won't set the desktop cursor size correctly, as it did before `v0.37`. But the command is still listed in `hyprctl --help`

## Additionally
It would be good if 
```
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,108
```
Was capable of setup the hyprland desktop cursor size, so the user is not forced to use the hyprland cursor format if he doesn't want to → Only `HYPRCURSOR_THEME` and `HYPRCURSOR_SIZE` have been able to change the desktop cursor on my tests.

**Comment by vaxerski** [comment]
> `env = XCURSOR_SIZE,108`

worked on my end with xcursors iirc...

for the main issue: rtfm, you can't assume with hyprland that nothing will change lol

https://wiki.hyprland.org/Configuring/Using-hyprctl/#setcursor

![image](https://github.com/hyprwm/Hyprland/assets/43317083/371e9d17-07b7-480f-a49d-524a27acc5ec)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/9d18c11b-cbe3-4a4f-ab67-6f442b5ac396)

It will use XCURSOR_SIZE if HYPRCURSOR_SIZE is unset

**Comment by vaxerski** [comment]
ah wait fuck there is a bug mb

**Comment by vaxerski** [comment]
fixed.
