### ISSUE TITLE
no_gaps_when_only bug with multiple monitors

### ISSUE THREAD

**Issue by nullchilly** [hyprwm/Hyprland#525]
Config
```bash
dwindle {
	pseudotile=0
	no_gaps_when_only = 1
}
```
Screenshot 
![20220814_07h56m59s_grim](https://user-images.githubusercontent.com/56817415/184527881-ebac3100-d6c9-4c3b-b01a-0963e5174498.png)

Screenshot with scaling (Now the border is weirdly offset)
![20220814_08h01m50s_grim](https://user-images.githubusercontent.com/56817415/184528010-4de9d758-0d43-4e8c-b90c-79285b642677.png)

Expected behavior: The second monitor's border doesn't burn into the first one

**Comment by vaxerski** [comment]
Do I understand correctly that with no_borders_when_only the border is rendered on the other monitor?

**Comment by nullchilly** [comment]
Yes

**Comment by vaxerski** [comment]
should be fixed with bec75013658836e24d4bc9d3a5a96d328b8c7bf0 but please test as i cannot atm
