### ISSUE TITLE
Xmonad's Easymotion-like way to select windows and kill them

### ISSUE THREAD

**Issue by sophronesis** [hyprwm/Hyprland#5252]
### Description

Xmonad have this cool feature, where you can select window, what you can interact with.
can be seen better here:
https://www.youtube.com/watch?v=39vl0Cmx3iI
Would appreciate to see this functionality in hyprland

**Comment by vaxerski** [comment]
this looks like a simple thing a plugin could do.

**Comment by modestbadger1773** [comment]
I don't have the skills to make this plugin (nor the time to learn how to while I'm in med school). But it would be something I would use if others with the skills to do so were looking for a project to do.

**Comment by vaxerski** [comment]
nice one! closing.

**Comment by zakk4223** [comment]
I wrote one with window decorators!
https://github.com/zakk4223/hyprland-easymotion

Bonus arbitrary command execution so you can do stupid things!

Perhaps the person who did it with GTK layer shell is smarter than I am because now I am cursed with the knowledge of how window decorators work.

**Comment by vaxerski** [comment]
> Perhaps the person who did it with GTK layer shell is smarter than I am because now I am cursed with the knowledge of how window decorators work.

it's useful if you want to write window decorations in hyprland
