### ISSUE TITLE
Use ZSH fpath in hyprland.conf

### ISSUE THREAD

**Issue by JoshElias** [hyprwm/Hyprland#5253]
### Description

I would like to setup vars, path and fpath with ZSH before starting Hyprland and be able to use them in my `hyprland.conf`.

This could be done by sourcing a script before starting Hyprland. Like in your login shell for example:

```
if tty -s; then
  if [[ $(tty) == "/dev/tty1" ]]; then
    source /usr/local/share/setup-zsh
    dbus-run-session Hyprland
  fi
fi
```

### Benefits

Allow you to reference scripts and functions from your fpath.

**Comment by vaxerski** [comment]
I don't understand. How do you want for hyprland to launch something... before hyprland?

**Comment by JoshElias** [comment]
Thanks for the response. I wasn't sure exactly if this was a bug, feature, or just general question.

I'm trying to understand why I can't reference scripts that are on my `fpath` from `hyprland.conf`. I would expect the Hyprland process to have `fpath` in it's environment if I imported it in the parent process.

I'm pretty new to shell scripting though so maybe the fact that nobody else's config does this means it's harder than I think. Is it something that I could potentially work on/help with if it is possible but annoying?

**Comment by bvr-yr** [comment]
> I'm trying to understand why I can't reference scripts that are on my fpath from hyprland.conf. Primarily for binds.

on `bind ..., exec` Hyprland calls /bin/sh, not your shell

you can use exec `zsh -c 'somecommand -someflag'`, but you still need source your `/usr/local/share/setup-zsh` in `.zprofile`, because zsh will not run in interactive mode in this case, and fpath will be the default one, not from .zshrc

**Comment by JoshElias** [comment]
> on `bind ..., exec` Hyprland calls /bin/sh, not your shell

Oh it uses `bin/sh`...that makes sense now thank you!

> you can use exec `zsh -c 'somecommand -someflag'`, but you still need source your `/usr/local/share/setup-zsh` in `.zprofile`, because zsh will not run in interactive mode in this case, and fpath will be the default one, not from .zshrc

Sorry I'm confused. I know `.zprofile` is read before `.zshrc`, but are you saying that by sourcing what I need explicitly before running `Hyprland` in my .zprofile (like in my example above ^), that my 'fpath` still won't be available if I use `zsh -c 'somecommand -someflag'` in my `hyprlan.conf`?

**Comment by bvr-yr** [comment]
you can test what fpath it will use by binding `exec zsh -c 'echo $fpath > /tmp/fpathtest'`

**Comment by bvr-yr** [comment]
> Sorry I'm confused.

yeah sorry, I've been incorrect, it should be `.zshenv` to modify, because `zsh -c` is neither login nor interactive.

I don't know content of your `setup-zsh`, but anyway you can `source` or `fpath+=( '...' )`
in `.zshenv`, or what you are doing in .zshrc

**Comment by JoshElias** [comment]
On second thought this is pretty convenient as is, but still curious on your thoughts.

`bind = $mainMod, X, exec, zsh -c screen-capture-area-note`
vs
`bind = $mainMod, X, exec, $SCRIPTS/screen-capture-area-note`
