### ISSUE TITLE
zwp_input_popup_surface_v2::text_input_rectangle is relative to wrong surface

### ISSUE THREAD

**Issue by sam-mccall** [hyprwm/Hyprland#5255]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 6b28bf563e3b4e5f6631985f24c88e8a8ebaa0d4  (keybinds: Fix exit trigger by moving it to monitor.frame (5240)).
Date: Mon Mar 25 02:46:59 2024
Tag: v0.37.1-63-g6b28bf56

flags: (if any)


System Information:
System name: Linux
Node name: anacletus
Release: 6.6.13-1rodete3-amd64
Version: #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1rodete3 (2024-03-04)


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: PRETTY_NAME="Debian GNU/Linux rodete"
NAME="Debian GNU/Linux rodete"
VERSION_CODENAME=rodete
ID=debian


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When an IME using `input-method-unstable-v2` shows a popup, it receives the `zwp_input_popup_surface_v2::text_input_rectangle` event to describe where the text field is.

Hyprland is sending coordinates relative to the surface containing the text field, not relative to the popup surface. The `y` coordinate is always positive, and gets bigger if I trigger the input method further down the editor window. (See screenshots).
Instead it should be relative to the popup: e.g. `y` is negative if the popup is below the text. (This is what Sway does).

(While the spec isn't totally explicit, relative to the popup surface is the only thing that makes sense: the purpose of this event is to tell where the text is compared to the popup: e.g. is it above or below, so it can vertically align its content to be near the text.
The position of the text inside the text's window doesn't help with this as the input method doesn't know where that window is.)

### How to reproduce

Here is a test IME that prints events including these rectangles: https://github.com/sam-mccall/bugreports/blob/hyprcoord/sway-im-popup/src/main.rs

(naming is weird, it's a modified testcase from another bug report)

### Crash reports, logs, images, videos

![screenshot_2024-03-25_03-07-47](https://github.com/hyprwm/Hyprland/assets/548993/6b5d74d5-3e56-4942-be60-0bc1671e14d5)
![screenshot_2024-03-25_03-08-06](https://github.com/hyprwm/Hyprland/assets/548993/2e0745ca-0b3b-4c2c-be1c-1af609b504b4)
![screenshot_2024-03-25_03-08-28](https://github.com/hyprwm/Hyprland/assets/548993/5fbe87ed-f6b7-427a-8274-8366b7fe1db0)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14744738/patch.txt)
is this correct?

**Comment by q234rty** [comment]
>  is this correct?

Unfortunately, not for me :)

**Comment by vaxerski** [comment]
idk what the problem is then, feel free to inspect the patch and get something to work. Myabe I'm just stupid

**Comment by Zyuke** [comment]
I have a similar experience with fcitx5. When I switch to a non-English input method and type in firefox on a 2nd monitor the text box would appear in the first monitor
