### ISSUE TITLE
Turning off monitor leads to background being cut off

### ISSUE THREAD

**Issue by pgosar** [hyprwm/Hyprland#5258]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 356414639fc06ace7045236ec41d673342981057 dirty (core: fix missing workspace events during swapping (5251)).
Date: Sun Mar 24 20:50:41 2024
Tag: v0.37.1-64-g35641463

flags: (if any)


System Information:
System name: Linux
Node name: inator
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

Upon disabling my laptop's screen, my background is cut off. This persists until I reload hyprland, generally by writing to the config.
before:
![image](https://github.com/hyprwm/Hyprland/assets/55164602/0d42a4b7-8f7a-4892-bbf1-0758deb54829)
after:
![image](https://github.com/hyprwm/Hyprland/assets/55164602/4b86fac6-2eb3-4f9e-88b0-52234165db64)

Windows are still able to be in the black area. Sizes of the monitors are 3840x2560 (the one being turned off), and 2560x1440. You can also see that part of my waybar gets cut off on the right side. I've confirmed that this is not a waybar bug since this worked fine at least a couple weeks ago along with the background. It also only happens when disabling the 1440p monitor... I'm thinking there's a regression with any pixel math hyprland does when disabling monitors. 

The same issue happens when using hyprpaper along with windows I try to close flickering in a half-closed state and freezing up. Once I look into that a bit more I'll make a separate issue but it might be related to the same bug here.

### How to reproduce

1. Start hyprland, with two monitors
2. disable monitor with hyprctl keyword monitor <monitor>,disable

### Crash reports, logs, images, videos

[hyprlandconf.txt](https://github.com/hyprwm/Hyprland/files/14739669/hyprlandconf.txt)
[test.txt](https://github.com/hyprwm/Hyprland/files/14739726/test.txt)
my config and logs from /tmp/hypr are attached

**Comment by vaxerski** [comment]
if this is a regression please git bisect

**Comment by pgosar** [comment]
4bc669f9331bb66ab30bd705d09f1239bc3e83ed


Commit from Feb 28th

**Comment by vaxerski** [comment]
what wallpaper tool is this

**Comment by pgosar** [comment]
Currently using swaybg, but it happens on hyprpaper too
