### ISSUE TITLE
Segmentation Fault when leaving Monitor Off Overnight

### ISSUE THREAD

**Issue by vhalragnarok-ffxiv** [hyprwm/Hyprland#5263]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
0.37.1-1 (Arch Linux Extra Repository, not AUR Git)
```

</details>

### Bug or Regression?

Bug

### Description

I normally leave my PC on 24/7, but physically power the monitor off through a hardware button when I will not be using the PC overnight. This morning I wake up to TTY1 saying Hyprland has crashed and it gave me a Crash Report.

### How to reproduce

This issue was occurring with no indication when I was using SDDM. I removed SDDM and just use TTY1 to login and has been fine for a few days, until last night. To reproduce I guess just have 1 monitor, physically turn it off and leave for a while. I hope that the Crash Report shows more way to reproduce than this, because this is the first time since I removed SDDM on Thursday, March 21st. 

If it helps I had Librewolf & Discord open on Desktop 2 when I turned my monitor off if my memory serves me correctly. 

### Crash reports, logs, images, videos

[hyprlandCrashReport972.txt](https://github.com/hyprwm/Hyprland/files/14744887/hyprlandCrashReport972.txt)

**Comment by vaxerski** [comment]
dupe #5241
