### ISSUE TITLE
IME not working when opening new window without unfocusing textbox

### ISSUE THREAD

**Issue by sungyoonc** [hyprwm/Hyprland#5265]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 356414639fc06ace7045236ec41d673342981057 dirty (core: fix missing workspace events during swapping (5251)).
Date: Mon Mar 25 10:50:41 2024
Tag: v0.37.1-64-g35641463

flags: (if any)


System Information:
System name: Linux
Node name: acacia
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

When opening another window without unfocusing the textbox in the first window, the IME does not work.

There is a difference how the IME breaks.
- first text-input-v3 then v3(same program): both stop working until one is closed.
- first text-input-v3 then v3(different program): the first one keeps working, but the second one does not work.
- first text-input-v3 then v1: the second one works, the first one works, but when you go back to the second one it doesn't work this time.
    - A is the first v3 client, B is the v1 client.
    - Open A(ime works) -> Open B(ime works) -> Switch back to A(ime works) -> Switch back to B(ime not work)

### How to reproduce

first text-input-v3 then v3(same program):
1. Open a text-input v3 client and focus any textbox. (in my case wayland firefox) (Do not unfocus the textbox)
2. Open another instance of the same text-input-v3 client in step 1. (I opened another firefox)
3. On the second client, the IME is not working(cannot switch between inputs, cannot types english when the icon says it's not in english)
4. Switch back to the first client, the IME is not working.
5. Close any of the 2 clients.
6. On the remaining client, the IME will start working again.

**Comment by sungyoonc** [comment]
It seems like when switching windows, `void CInputMethodRelay::onKeyboardFocus(wlr_surface* pSurface)` calls `ti->leave();`.
https://github.com/hyprwm/Hyprland/blob/a9d7526aae38dcdceb391fe9f00919c6c400abe3/src/managers/input/InputMethodRelay.cpp#L169-L174

But after that `hyprListener_textInputDisable` gets triggered and `void CTextInput::onDisabled()` calls `leave();` again.
https://github.com/hyprwm/Hyprland/blob/a9d7526aae38dcdceb391fe9f00919c6c400abe3/src/managers/input/TextInput.cpp#L84-L90

**Comment by vaxerski** [comment]
does removing the leave in the relay fix it?

**Comment by sungyoonc** [comment]
Nope, but adding `hyprListener_textInputDisable.removeCallback();` to `leave()` seems to fix it.

**Comment by vaxerski** [comment]
yeah but that's not a good fix.

**Comment by sungyoonc** [comment]
Yeah, it felt like a hacky way

**Comment by vaxerski** [comment]
it's not hacky, it's wrong

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14759082/patch.txt)
try this

**Comment by sungyoonc** [comment]
It only fixes `first text-input-v3 then v3(same program)` case. The other cases are still not working.

**Comment by sungyoonc** [comment]
how about this? This fixes all the cases.
[patch.txt](https://github.com/hyprwm/Hyprland/files/14760081/patch.txt)
