### ISSUE TITLE
Modifier related keybinds broken

### ISSUE THREAD

**Issue by BobVarioa** [hyprwm/Hyprland#5266]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)


System Information:
System name: Linux
Node name: heracles
Release: 6.8.1-060801-generic
Version: #202403151937 SMP PREEMPT_DYNAMIC Fri Mar 15 19:52:22 UTC 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When I recently updated my kernel and packages, all of my modifier + mouse keybinds, and some general modifier related keybinds do not work anymore. Also, very inconsistently, when I press these keybinds all my other keybinds completely break. 
The two examples in question:
```hyprlang
bindm = super, mouse:272, movewindow 
bind = super shift, 2, movetoworkspace, 2
# these keybinds don't work even when its alt, shift, etc
```

### How to reproduce

In all honesty, I'm completely unsure. 

### Crash reports, logs, images, videos

There were no crash reports or logs whenever all my keybinds broke, or just the single one did. However, `hyprctl` did say that it couldn't connect to `hyprland` thinking it wasn't running, even though it was.

**Comment by vaxerski** [comment]
does this happen with the default config too? it has the same binds.

**Comment by BobVarioa** [comment]
Yep! Seems to happen with that as well. I also  found the cause of all my keybinds breaking: whenever I opened Kate to edit my config, after I focused it at least once, they all broke. I would guess that's a separate issue though, should I open another for that one?

**Comment by vaxerski** [comment]
oh I just noticed, your version is extremely old, please update.

**Comment by BobVarioa** [comment]
Oh, oops, my bad. The issue still persists after the update however, here's the new system info if its at all helpful.
<details> <summary>System Info</summary>
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: heracles
Release: 6.8.1-060801-generic
Version: #202403151937 SMP PREEMPT_DYNAMIC Fri Mar 15 19:52:22 UTC 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo


plugins:
</details>

**Comment by BobVarioa** [comment]
Just noticed something, it seemed like the config I was using had an unclosed submap which made it seem like those things were broken, although they weren't. I'm not quite sure why the example config didn't work either, but my guess is whatever issue there was was due to my hyprland being outdated. Regardless, my issue is solved now so I'll close this.
