### ISSUE TITLE
No ignorezero equivalent for popups exists

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#5267]
### Description

with the `blurpopups` layerrule, an `ignorezero` equivalent would also be nice

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/6fb36cf6-a463-4235-a923-aa4073fcbdf4)

Also, why can't the standard `blur` and `ignorezero` rules be applied to all layers by default?

**Comment by vaxerski** [comment]
exists. It uses the parent values.

**Comment by alba4k** [comment]
My bad, it's actually just waybar behaving weirdly. Using `ignorealpha 0.1` works :shrug:
