### ISSUE TITLE
rearrange window

### ISSUE THREAD

**Issue by aloispichler** [hyprwm/Hyprland#5268]
### Description

It is possible to rearrange the windows 1 and 2 from
 1
─
 2
to
1 │ 2
with `usewindoworgroup l, r, d` or `u`. This is not intuitive.
What is the command for the reverse, for example?

It should be possible to move from the first to the second arrangement of windows by `{l, r}`, and
from the second to the first arrangement of windows by `{u, d}`.

**Comment by coltn** [comment]
Maybe I misunderstand you... but isn't this `togglesplit`? 
https://wiki.hyprland.org/Configuring/Dwindle-Layout/#layout-messages

**Comment by vaxerski** [comment]
yes
