### ISSUE TITLE
Save Window Layouts; Re-Open later

### ISSUE THREAD

**Issue by nosvagor** [hyprwm/Hyprland#527]
Using `hyprctl clients -j`will list all windows and their respective workspaces. I guess I could write a script that parses the JSON for the relevant information, save it, then use it re-open the layout later. However, I'm not sure if this is the best approach. 

Is there a better way I am missing?

**Comment by vaxerski** [comment]
hyprctl clients will not show you the layout tho, so idk what you mean. Only what workspace each window is on.

**Comment by nosvagor** [comment]
Perhaps layout is the wrong word, since that might refere to master/dwindle.

My problem: I fucking hate zoom, but have to use it, so I have a workspace that is all floating windows to deal with zoom calls. 

I don't want to have to open windows, move them around, and position browser and what ever else I'm using for that call. I'd rather just save a the positions, size, and application of each window within the workspace, since most of the time I have a PDF, browser, and zoom open. 

Then when I get a call, can just open them all up like I had it before and get right into things.

**Comment by vaxerski** [comment]
Not planning on implementing such a feature, but I will be adding more flexibility to `hyprctl`, as it currently lacks some stuff that would make something like this cleaner to script.

Stuff like moving windows between workspaces in the background, manipulating positions and sizes without focus, etc.

**Comment by vaxerski** [comment]
added all of the above. This is now perfectly doable with a script.
