### ISSUE TITLE
Tessen fails to launch when using exec

### ISSUE THREAD

**Issue by drnfc** [hyprwm/Hyprland#5270]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 8c88689faf691a4369528e6d3d52c024cd61125d  ().
Date: 2024-03-22
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: renfield
Release: 6.8.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:19:29 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240323.44d0940"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

When launching tessen using a keybinding or via `hyprctl dispatch exec tessen` it just fails silently.  

I can launch tessen via the command line, 
I have even tried writing a bash script with tessen as the sole thing being run and it still fails silently.

### How to reproduce

Installing tessen and running the command 
```
hyprctl dispatch exec tessen
```
or alternatively my flake can be found here:
https://gitlab.com/drnfc/nix-flake

**Comment by vaxerski** [comment]
when launching hyprland from a display manager, your bashrc or whatever is not sourced. That's likely the case.

However erring on the side of caution, @fufexan for nix

**Comment by fufexan** [comment]
Make sure you set any needed variables in `environment.variables` in your NixOS config. Also make sure you have `exec-once = dbus-update-activation-environment --systemd <VARIABLES>`, where `<VARIABLES` is either a space-separated list of env variables you want to import, or `--all` if you want to import all of them.

I can't test with tessen since I don't have a `pass` store set up.

**Comment by drnfc** [comment]
Yep, the lack of environmental variables being set was the issue.  I thought I already set those, but it turns out the only place I actually set them globally was in my hyprland config which got deleted when I decided to nixify it.

Thanks for the help.
