### ISSUE TITLE
 Keybinds doesn't work when focusing on programs like moonlight and looking glass

### ISSUE THREAD

**Issue by c127dev** [hyprwm/Hyprland#5273]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: me.c127.dev
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] [8086:4c8a] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Keybinds configuration does not work when opening certain programs.

### How to reproduce

When opening any of these programs (moonlight/looking glass) keybinds stop working until the program is forced to close or focus other program.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/160180792/c6170df1-075b-409e-87bf-68b054ede265

**Comment by vaxerski** [comment]
it's not a bug, the app itself requests that.

**Comment by c127dev** [comment]
Thanks for the reply.

But in previous versions this doesn't happen, it seems to have been implemented recently, so there should be some type of option to allow keybinds globally, now if an application being in full screen does not allow you to close it or move it or change workspace.

Additionally, to resolve these cases where any type of keybind can be used in the transmission, I used to use a configuration like this to remap when I want to use all keys when an transmission app its open:

```conf
bind = $mainMod,P,submap,clean
submap = clean

bind = $mainMod,Q,submap,reset
submap = reset

# Other Global Keybinds 
```

It is much more comfortable and allows more control in the interaction of the applications.

**Comment by vaxerski** [comment]
I guess it can be configurable
