### ISSUE TITLE
Focusing a window in a special workspace doesn't open the special workspace

### ISSUE THREAD

**Issue by MrYuto** [hyprwm/Hyprland#5276]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: ali-pc
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [Geforce RTX 3050] [10de:2507] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Focusing a window in a special workspace only moves the cursor to the center of that window in the current workspace. If you try this from another special workspace the special workspace will close but the target special workspace won't open.

`hyprctl activewindow` shows that the active window is not changing at all and it's just the cursor that is moving.

### How to reproduce

1. Open a window in a special workspace
2. Open terminal in non-special workspace
3. Run `hyprctl dispatch focuswindow [name of window]`
4. Non-special workspace is still visible and the active window is still the terminal. 

`focuscurrentorlast` and `focusurgentorlast` have the same behavior.

**Comment by v411e** [comment]
Related: #4803

**Comment by MrYuto** [comment]
Closing as duplicate
