### ISSUE TITLE
Option for `blurls` to look better with rounded corners/fully transparent pixels

### ISSUE THREAD

**Issue by Gutawer** [hyprwm/Hyprland#528]
`blurls` is great for my notification and bar styling, but right now I can't really put rounded corners on them as Hyprland still blurs the pixels that aren't really part of the window (corner radius on `dunst` exaggerated to show the effect):

![image](https://user-images.githubusercontent.com/9727338/184680755-f44cc95f-7f22-40a7-82a9-11c51f601f6f.png)

In all of my cases this would be fixable by simply not blurring pixels that are completely transparent, but there might be some better way of achieving this that I'm not thinking of.

Apologies if there already is a way around this!

**Comment by vaxerski** [comment]
we're discussing this as a part of the ext-blur protocol @ wayland-protocols: [https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/43](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/43)

I am not sure whether I should introduce a per-layer option in the meantime before this gets merged and adopted. Lmk.

**Comment by vars1ty** [comment]
Although not affected currently, having the option to exclude certain layers from blur would be nice.

**Comment by vaxerski** [comment]
well that's already done with blurls no?

**Comment by vars1ty** [comment]
Almost forgot about `blurls` smh, mb lmao

**Comment by amilonop** [comment]
Any updates on this issue? Would lead into some *super* cool UIs with EWW and waybar :D

**Comment by HanoJing** [comment]
Yeah, I have the same issue I guess. Layers that are blurred using `blurls=NAMESPACE` have corners pretruding from the rounded corners seen on fuzzel for example (although the corners are very subtle).

**Comment by vaxerski** [comment]
done in e5870d47c74150aa744ed55f9b7e58713d968209
