### ISSUE TITLE
Apply shader to window only

### ISSUE THREAD

**Issue by igor-semyonov** [hyprwm/Hyprland#5282]
### Description

Greetings,

I would like to implement the option to apply a shader to a window, instead of the whole screen.
This is related to issue #1861 , as I want to use this to be able to invert the colors of a single window that doesn't have dark mode. Being visually impaired, I can't use anything in light mode.

I have cloned the repo and am starting to look around the codebase, specifically the file src/render/OpenGL.cpp and related areas.

I would appreciate any advice about:
- Whether this is even possible
- Suggestions about how to go about this

**Comment by vaxerski** [comment]
> Whether this is even possible

yes.

Does it make sense? 

No.

Is this a good idea?

Hell no.

**Comment by igor-semyonov** [comment]
Understood.
I will be working on it then.

**Comment by tchofy** [comment]
Late i guess, but there's a third party plugin to invert colors on a window, https://github.com/micha4w/Hypr-DarkWindow

**Comment by SpomJ** [comment]
> Is this a good idea?
> 
> Hell no.

Imagine a random godawful rice that runs an ocean simulation on inactive windows, wouldn't it be beautiful?

**Comment by R33S3Y** [comment]
Hi there, 

Just to throw in my two cents I think it would be cool to have this.
i was hoping to use this to use this to change the opacity for of the app background while leaving the foreground colors alone (for the apps I have themed) so I could still see my background while keeping the text easy to see.
Thanks.
