### ISSUE TITLE
Regression: Tablet/Stylus Misaigned/offset cursor/pointer on Menus && Popups

### ISSUE THREAD

**Issue by nine7nine** [hyprwm/Hyprland#5284]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ae52b7f4680716976d05b638aaa90e169d199117 dirty (textinput: fix ime when opening multiple windows (5281)).
Date: Tue Mar 26 10:16:09 2024
Tag: v0.37.1-71-gae52b7f4

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.1-rt8-5-nspa
Version: #1 SMP PREEMPT_RT Sun, 17 Mar 2024 15:39:48 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Plus Graphics G7 [8086:8a52] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

I've been using my Microsoft Surface 7 (which has a touchscreen + Stylus) with Hyprland (+ AGS) for about 5 months, and it has worked rather well. However, in the last couple of days it has stopped working correctly.

Specifically, the pointer from the Stylus seems to be misaligned / offset with menus and popups, making Hyprland completely unusable with my Stylus now (Mouse && Touch seem to be fine). A bit more detail:

- Popups: As seen in my application menu (AGS), the pointer/cursor is always offset below (by 24px or an entry?).
- Menus: As seen in Gedit & Nautilus: the pointer/cursor is always offset above (by one?) menu entry. Note: While I am showing GTK apps here -- the same is true from any/all applications (OBS/Qt, for example. same offset).
- My (AGS) dock is even stranger: the offset seems to be by 5-6 app buttons/icons.

This all worked perfectly a couple of days ago, and I am unsure of the breaking changes: if it is hyprland specifically, some combination of Hyprland & wlroots, or wlroots specifically... While AGS may be used here -- the same problems exist without using AGS / just Pure Hyprland. Either way though: Hyprland is unusable with my Stylus/Tablet device now.

I'll also the note the strange output from 'hyprctl devices' in my tablet section:

```
Tablets:
	Tablet at 557273add5d0:
		ipts-045e:099f-stylus
			size: 259.4594594594595x171.42857142857142mm
	Tablet at 5572738a2850:
		ipts-stylus
			size: 259.4594594594595x171.42857142857142mm
	Tablet at 55727434b500:
		input-remapper-ipts-stylus-forwarded
			size: 259.4594594594595x171.42857142857142mm
```

maybe I am mistaken: but I would've expected a 'size' that actually matches my display ( 2736 x 1824 ), and surely not something with so many decimal places (?). This seems odd to me... That said: i did try using some of the new tablet variables to see if I could correct my tablet/stylus issues and nothing changed the situation.

I also haven't had any stylus issues with other WM/DEs (eg: KDE6, Gnome 46). Everything works perfectly, outside of Hyprland. 

### How to reproduce

N/A - You would need a Microsoft Surface 7 device + there are no real steps to reproduce, beyond what is shown in the video that I've included to demonstrate the issues. ~ if another Hyprland user has the same device - they may be able to reproduce / confirm (?).

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/20159346/70a1e4f2-ab20-47c7-8abe-ed6b568e9e85

**Comment by fufexan** [comment]
I also have the offset cursor problem on menus, using my wacom tablet. Must be caused by the recent commits addressing clicking on menus.

**Comment by nine7nine** [comment]
@fufexan - Thanks for piping in and verifying the issue! ~ my touch is also wacom-based. (but I have to use out-of-tree patches. eg: lbwacom-surface, for Intel's IPTS driver).

Interestingly, this commit: ae17e90 did actually fix clicking on some menus, that previously never worked with my stylus... which is great! ... but obviously the offset cursor is driving me nuts!

Question: do you also see similar output for tablet section in `hyprctl devices`. ie: the wild decimal places? ( assuming that isn't normal? )

**Comment by vaxerski** [comment]
bisect it

**Comment by nine7nine** [comment]
@vaxerski - When i have some free time, I will try and bisect it ( likely on the weekend ).

For now, I used Arch Linux Archive and moved back to Hyprland 0.36.0 (along with all related deps). Interestingly, while that solves the majority of the issues in the video (menu offsets, dock issues, etc), it doesn't resolve the Popup Menu offset (although, clicking on a menu entry does select the correct one)... So there may be more at play here, than just hyprland / wlroots... (that said: obviously, later commits in Hyprland and/or wlroots make the stylus completely unusable).

but hey! at least I can use my stylus without issue again.

**Comment by nine7nine** [comment]
Okay, I dug up sometime to look into this.

reverting commit: 7a31c954e5962db07b1b83e8a7340c38e7988ab6 gets rid of the crazy offset on my dock and also in menus. ~ I just rebuilt against HEAD now, reverting this commit only.

it does not, however, fix the offset in my popup menu in AGS - but even with the offset, when i click on a menu entry - it does open the correct app (it just selects them both for a second visually)...

clicking on GTK app menu entries doesn't seem to work (although it never really did), and I would expect to see hover animations - which i also don't see. (this used to work on my dock. doesn't now though).

so clearly, there are still some screwy things going on -- but it is commit: 7a31c954e5962db07b1b83e8a7340c38e7988ab6 that was making my Stylus completely unusable.

**Comment by Agent00Ming** [comment]
Try latest since #5902 has been merged and probably changed the behaviour @nine7nine

**Comment by izmyname** [comment]
> test

How was it? Is the problem fixed?

**Comment by nine7nine** [comment]
@Agent00Ming & @izmyname - Yeah, this issue is fixed.

Sorry for the delayed response - Hyprland was pretty broken for a while with plugins I use, so I was avoiding updating.

but all seems well now
