### ISSUE TITLE
Vertical slide for layers

### ISSUE THREAD

**Issue by musjj** [hyprwm/Hyprland#5285]
### Description

There's already `slide` for layers, but it always slides horizontally. A version that always slides vertically would be nice, like `slidevert` for workspaces.

**Comment by vaxerski** [comment]
my launcher slides from the top. It's automatic.

**Comment by musjj** [comment]
Oh, I guess it depends on the position of the window?

I have a widget that spawns on the top-right of the screen, but it currently slides horizontally from the right. I would like to have it slide from the top instead (so that it looks it's coming out of my top bar).

**Comment by vaxerski** [comment]
I can add the same props as for windows (top, right, left, bottom) so you can control the direction directly. Would that solve it?

**Comment by musjj** [comment]
Didn't know it's a thing for windows ([undocumented?](https://github.com/hyprwm/Hyprland/issues/3675)), but yeah that would be cool!

**Comment by vaxerski** [comment]
it's undocumented, yes

**Comment by vaxerski** [comment]
added to wiki too
