### ISSUE TITLE
Bug: decoration opacity probably shouldn't overrule windowrules

### ISSUE THREAD

**Issue by Dreded** [hyprwm/Hyprland#5286]
### Hyprland Version
Installed: 0.37.1-1.1

### Bug or Regression?

Bug

### Description

as the title says no matter what order they come in

```
decoration {
  active_opacity = 1.0
  inactive_opacity = 0.9
  fullscreen_opacity = 1.0
  }
}
```
always over rules `windowrulev2 = opacity 1.0 1.0, class:^(firefox)$`

in my case I want most windows to go slightly transparent when inactive except for 2 or 3 of them

### How to reproduce

put the above into a config in any order

**Comment by vaxerski** [comment]
the only bug here is in your "reading the wiki" department:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/83450da7-4ccd-468c-9ac9-629d1134d19b)

https://wiki.hyprland.org/Configuring/Window-Rules/#dynamic-rules
