### ISSUE TITLE
Random crash with IME popups

### ISSUE THREAD

**Issue by juvevood** [hyprwm/Hyprland#5287]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
the lastest commit:ae52b7f4680716976d05b638aaa90e169d199117
```

</details>

### Bug or Regression?

Bug

### Description

random cash with IME popups

### How to reproduce

When popup IME input window with xwayland and wayland programs, There is a high probability that it will cause Hyprland crash

### Crash reports, logs, images, videos
[wlr] [xwayland/xwm.c:867] unhandled X11 property 338 (_NET_WM_USER_TIME) for window 6291474
[LOG] X11 Activate request for window [Window 55d966483e90: title: "DingTalk"]
[wlr] [xwayland/xwm.c:1655] unhandled X11 event: FocusOut (10)
[wlr] [xwayland/xwm.c:867] unhandled X11 property 338 (_NET_WM_USER_TIME) for window 6291474
[LOG] Registered signal for owner 55d9657616b8: 55d969918038 -> 55d965761700 (owner: CWLSurface)
[LOG] Registered signal for owner 55d9657616b8: 55d969917ff8 -> 55d965761768 (owner: CWLSurface)
[LOG] CWLSurface 55d9657616b8 called init()
[LOG] Registered signal for owner 55d9657616b0: 55d969917ff8 -> 55d965761948 (owner: IME Popup)
[LOG] Registered signal for owner 55d9657616b0: 55d969918008 -> 55d965761810 (owner: IME Popup)
[LOG] Registered signal for owner 55d9657616b0: 55d969918018 -> 55d965761878 (owner: IME Popup)
[LOG] Registered signal for owner 55d9657616b0: 55d966168528 -> 55d9657618e0 (owner: IME Popup)
[LOG] New input popup
[LOG] Mapped an IME Popup
[ERR] BUG THIS: No owner in imepopup::damageentire
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[LOG] Unmapped an IME Popup
[ERR] BUG THIS: No owner in imepopup::damageentire
[LOG] Callback 55d965761970 -> 55d965761968, IME Popup removed.
[LOG] Callback 55d965761908 -> 55d965761900, IME Popup removed.
[LOG] Callback 55d965761838 -> 55d965761830, IME Popup removed.
[LOG] Callback 55d9657618a0 -> 55d965761898, IME Popup removed.
[LOG] Callback 55d965761728 -> 55d965761720, CWLSurface removed.
[LOG] Callback 55d965761790 -> 55d965761788, CWLSurface removed.
[LOG] CWLSurface 55d9657616b8 called destroy()
[LOG] No focused TextInput on IME Commit

_No response_

**Comment by vaxerski** [comment]
post the crash report then or actual repro steps, this doesn't happen to anyone but you

**Comment by juvevood** [comment]
switch IME pop window with xwayland and wayland programs, repeat this operation, Hyprland must be crashed.

**Comment by sungyoonc** [comment]
I have reproduced this log spam part but it didn't crash for me.
```
[ERR] BUG THIS: No owner in imepopup::damageentire
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
...
```

**Comment by sungyoonc** [comment]
@juvevood When did the crash occur exactly? Were you just switching from xwayland to wayland or vice versa? Or did you type something? Or anything you did just before the crash.

Also, provide a full crash report, if you can.

**Comment by juvevood** [comment]
> @juvevood When did the crash occur exactly? Were you just switching from xwayland to wayland or vice versa? Or did you type something? Or anything you did just before the crash.
> 
> Also, provide a full crash report, if you can.

I have updated the latest commit and still crashes. 
reproduce: xwayland program first and start chrome, crash happend.
[hyprlandCrashReport1170.txt](https://github.com/hyprwm/Hyprland/files/14782665/hyprlandCrashReport1170.txt)

**Comment by sungyoonc** [comment]
Can you try this?
[patch.txt](https://github.com/hyprwm/Hyprland/files/14783844/patch.txt)

**Comment by juvevood** [comment]
> Can you try this? [patch.txt](https://github.com/hyprwm/Hyprland/files/14783844/patch.txt)

its works, Thanks for your patch.
I reproduced yesterday's crash again，confirmed that it is the same problem. 
full crash log here
[hyprlandCrashReport3327.txt](https://github.com/hyprwm/Hyprland/files/14784545/hyprlandCrashReport3327.txt)

**Comment by sungyoonc** [comment]
I have reproduced your first crash.
The strange thing is this patch fixed the crash for me. 
> Can you try this? [patch.txt](https://github.com/hyprwm/Hyprland/files/14783844/patch.txt)

Maybe your second crash report is a different crash?

My steps to reproduce:
1. open 2 text input v1 windows or text input v1 and xwayland
2. hold the text input v1 window with mouse cursor(the movewindow dispatcher)
3. crash (if it doesn't crash just spam movewindow dispatcher)

**Comment by sungyoonc** [comment]
Wait the stack trace is different maybe my crash is a different crash.

[hyprlandCrashReport66423.txt](https://github.com/hyprwm/Hyprland/files/14797749/hyprlandCrashReport66423.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14797849/patch.txt)
try

**Comment by MoetaYuko** [comment]
> Can you try this? [patch.txt](https://github.com/hyprwm/Hyprland/files/14783844/patch.txt)

this doesn't fully address the issue. I still experience it in some rare cases, but dunno how to reproduce it so far.

**Comment by sungyoonc** [comment]
@MoetaYuko Is the issue you are talking about #5288?
If so, I think you should reopen #5288, because I don't think this issue is actually related to it.

**Comment by MoetaYuko** [comment]
> @MoetaYuko Is the issue you are talking about #5288? If so, I think you should reopen #5288, because I don't think this issue is actually related to it.

Yes, but I'm unable to reopen it, @vaxerski should be able to do so.

**Comment by vaxerski** [comment]
> this doesn't fully address the issue. I still experience it in some rare cases, but dunno how to reproduce it so far.

and you dont post anything. Asan traces, crash reports, nothing.

**Comment by MoetaYuko** [comment]
> > this doesn't fully address the issue. I still experience it in some rare cases, but dunno how to reproduce it so far.
> 
> and you dont post anything. Asan traces, crash reports, nothing.

I reported reproduction steps in https://github.com/hyprwm/Hyprland/issues/5288#issue-2210066171, which have been confirmed by @sungyoonc at https://github.com/hyprwm/Hyprland/issues/5288#issuecomment-2023027812, and my logs are the same as he posted. No crash on my side. Please drop me a note if you need any additional info.
