### ISSUE TITLE
IME not working properly when there are both xwayland and native wayland windows

### ISSUE THREAD

**Issue by moetayuko** [hyprwm/Hyprland#5288]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ae52b7f4680716976d05b638aaa90e169d199117 dirty (textinput: fix ime when opening multiple windows (5281)).
Date: Tue Mar 26 23:16:09 2024
Tag: v0.37.1-71-gae52b7f4

flags: (if any)


System Information:
System name: Linux
Node name: arch-pc
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000


GPU information:
02:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] [1002:6fdf] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```
</details>

### Bug or Regression?

Bug

### Description

When having both xwayland and native wayland windows, switching IME in the xwayland window will show two prompts as if I'm switching in both windows simultaneously. After IME is activated, typing in the xwayland window is extremely slow but the words won't get typed after confirmation.

One interesting thing to notice is that the native wayland window can be gtk3, firefox, electron, kitty, ..., but **not Qt**.

I guess there's still something wrong after recent IME updates, so Cc @sujoshua @sungyoonc

### How to reproduce

1. launch an xwayland app
2. launch a wayland app (e.g. firefox, kitty) except qt-based ones
3. click a textbox in the xwayland app, then press the shortcut to activate IME, observing two prompts
4. type something, observing slow response from the IME
5. confirm your typing, observing nothing in the textbox

**Comment by sungyoonc** [comment]
I think I have reprㄹㄴㅇㄹㄹㄴㄹㅇㄴㄹㄴㄹㄴㄹㄴㅇㄹㄴoduced it.ㅇㄹㄴ

**Comment by sungyoonc** [comment]
I think I have reproduced it.

When I switched from native to xwayland, the prompt opened in the top left of the monitor and started to jitter. Also it spammed this in the log.
[ERR] BUG THIS: No owner in imepopup::damageentire
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
[ERR] BUG THIS: No owner in imepopup::globalbox
...

When I tried to go to next candidate while the prompt was jittering, it responded slow.

Is this seem like the same behavior you encountered?

**Comment by vaxerski** [comment]
#5287

**Comment by sungyoonc** [comment]
Can you try this?
[patch.txt](https://github.com/hyprwm/Hyprland/files/14815527/patch.txt)

**Comment by MoetaYuko** [comment]
> Can you try this? [patch.txt](https://github.com/hyprwm/Hyprland/files/14815527/patch.txt)

thanks, appears to be working

**Comment by vaxerski** [comment]
modified the patch a bit and committed. lmk how it works.

**Comment by MoetaYuko** [comment]
> modified the patch a bit and committed. lmk how it works.

The issue is *mostly* fixed now, but it happened **once** during the past hour, and I failed to reproduce it after that. I'll keep an eye on it.

**Comment by moetayuko** [comment]
@vaxerski I finally found a way to reproduce the issue reliably, I hope this can assist you in fixing it:
1. start a fresh hyprland session
2. open an xwayland app (zotero in my case)
3. open a native wayland app (kitty in my case)
4. close the native wayland app
5. now the xwayland app is left alone. click a textbox in it and switch IME, then observe the mentioned issue

This is still reproducible with the latest main branch

**Comment by arahiko-ayami** [comment]
Did you try 0.41.2? I haven't try but 0.39.1 works well with fcitx5

**Comment by moetayuko** [comment]
> Did you try 0.41.2? I haven't tried but 0.39.1 works well with fcitx5

I use the -git version

**Comment by arahiko-ayami** [comment]
> > Did you try 0.41.2? I haven't tried but 0.39.1 works well with fcitx5
> 
> I use the -git version

So you could try to switch to 0.39.1 if you really uncomfortable with it. It is the latest version that works well with fcitx5. I have no time to try `bisect` so I don't know what happened with version >= 0.40. Just a workaround for now

**Comment by sungyoonc** [comment]
Can anyone try this?
[patch.txt](https://github.com/user-attachments/files/16829129/patch.txt)

**Comment by moetayuko** [comment]
I'm still experiencing the issue but previous approach cannot reproduce. I'll update once I figure out how to reproduce.

**Comment by sungyoonc** [comment]
> I'm still experiencing the issue but previous approach cannot reproduce. I'll update once I figure out how to reproduce.
> ```
> Hyprland, built from branch main at commit d35e70a8c6599bb058cf86eb87c783ce1cf72471 dirty (cmake: drop ninja dep).
> Date: Sat Sep 14 00:56:44 2024
> Tag: v0.43.0-22-gd35e70a8, commits: 5218
> ```

Is it the same with #7775?

**Comment by moetayuko** [comment]
> > I'm still experiencing the issue but previous approach cannot reproduce. I'll update once I figure out how to reproduce.
> > ```
> > Hyprland, built from branch main at commit d35e70a8c6599bb058cf86eb87c783ce1cf72471 dirty (cmake: drop ninja dep).
> > Date: Sat Sep 14 00:56:44 2024
> > Tag: v0.43.0-22-gd35e70a8, commits: 5218
> > ```
> 
> Is it the same with #7775?

yes, can repro here.
1. open vscode in native wayland mode
2. open an xwayland app
3. activate fcitx5 in the xwayland app, type something, then observe the prompt at the top left corner of the screen

**Comment by sungyoonc** [comment]
@moetayuko Try the patch in #7775.

**Comment by moetayuko** [comment]
> @moetayuko Try the patch in #7775.

thanks for the patch. it seems to be effective. at least I can't reproduce the issue with the steps above.
