### ISSUE TITLE
[nixos] Hyprland fails to build because of conflict with symlinking file on flake

### ISSUE THREAD

**Issue by plurpio** [hyprwm/Hyprland#5289]
### Hyprland Version

<details> <summary>System/Version info</summary>
hyprctl systeminfo fails to run (prob bc im still using nixpkgs hyprland)
so here is startup logs of hypr, looks pretty similar to hyprctl systeminfo

Welcome to Hyprland!
[LOG] Instance Signature: v0.32.3_1711531257
[LOG] Hyprland PID: 13154
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: penguin
[LOG] Release: 6.1.82
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:27:50 UTC 2024

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

[LOG] os-release:
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.11.20240322.56528ee"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.11 (Tapir)"
SUPPORT_END="2024-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.11 (Tapir)"
VERSION_CODENAME=tapir
VERSION_ID="23.11"
</details>

### Bug or Regression?

Bug

### Description

When using the NixOS Hyprland flake it fails because of a file conflict when trying to make a symlink.

### How to reproduce

1. Rebase your system onto a NixOS flake.
2. Add the Hyprland flake.
3. Try rebasing but this time it will fail.
*my flake.nix if important (only configuration done outside is enabling hyprland)*
```
{
  description = "Plurpio's NixOS configuration flake.";

  inputs = {
#    nixpkgs.url = "github:nixos/nixpkgs/nixos-23.11";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nix-flatpak.url = "github:gmodena/nix-flatpak/?ref=v0.3.0";
    hyprland.url = "github:hyprwm/Hyprland";
  };

  outputs = { self, nixpkgs, nix-flatpak, hyprland, ... }@inputs: {
    nixosConfigurations.default = nixpkgs.lib.nixosSystem {
      specialArgs = {inherit inputs;};
      modules = [
        hyprland.nixosModules.default
        nix-flatpak.nixosModules.nix-flatpak
        ./configuration.nix
        ./pkgs.nix
        ./users.nix
        ./ssh.nix
        ./services.nix
        ./locale.nix
      ];
    };
  };
}
```

### Crash reports, logs, images, videos

**output of rebuilding system with sudo nixos-rebuild switch --flake /etc/nixos#default**
```
building the system configuration...
error: builder for '/nix/store/cchp3qf9rn90xlipxgn5bi6w6i1r3isj-user-units.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/jk3php28h2wvfnpczad0rg3ji37z2xlp-user-units/xdg-desktop-portal-hyprland.service': File exists
       For full logs, run 'nix log /nix/store/cchp3qf9rn90xlipxgn5bi6w6i1r3isj-user-units.drv'.
error: 1 dependencies of derivation '/nix/store/f3rv60f7r6zhyz61iwpz5ljd2x3nkwqy-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yr4qmfzr6s89rii1g414yz415j4sww5k-nixos-system-penguin-24.05.20240325.57e6b3a.drv' failed to build
```

**Comment by M4he** [comment]
Only thing that comes to my mind: make sure the `xdg.portal.extraPortals` list *does not* contain `pkgs.xdg-desktop-portal-hyprland` or similar references when building Hyprland from Flake.

**Comment by plurpio** [comment]
thanks for the help @M4he. i'm now on the hyprland flake but now the hyprland will complain about a correct configuration file.

![image](https://github.com/hyprwm/Hyprland/assets/148961679/a7653d02-85a5-4588-b6e8-9496dc6f780d)

**first lines of hyprland.conf**
```
###################################
#              STARTUP
###################################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1, 1920x1080@60, 0x1080, 1
monitor=HDMI-A-1, 1920x1080@144, 0x0, 1
```

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/issues/4975

**Comment by plurpio** [comment]
thanks hyprland corporation™️ very epik, love ya
