### ISSUE TITLE
flickering when killing swaybg

### ISSUE THREAD

**Issue by liyjii** [hyprwm/Hyprland#5295]
### Hyprland Version

<details> <summary>System/Version info</summary>

```shHyprland, built from branch  at commit 93d05114716e847c37f49d3cc2d0c5cb01d06a24  ().
Date: 2024-03-27
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: art
Release: 6.8.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:19:29 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240325.57e6b3a"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

https://github.com/hyprwm/Hyprland/assets/146618064/cd260cce-55c4-492d-a9b7-8f603778b22a

kill swaybg result in flickering
I also tried 37.1 from nixos-unstable which works fine.

### How to reproduce

install latest hyprland from flake and kill swaybg.

**Comment by HIDE-r** [comment]
happen same with me.

**Comment by vaxerski** [comment]
git bisect then

**Comment by liyjii** [comment]
I'm sorry I did many updates in my nixos and I can't find that regression commit.
But the issue is  gone in last several commit.

**Comment by vaxerski** [comment]
if it's gone then I'm closing

**Comment by liyjii** [comment]
Sorry,I forget to pin hyprland to flake.
bisect to ca17a89d86b73f37019c4cc0c7087303adbcc1f9

**Comment by tinmarr** [comment]
Not just a swaybg issue. Also applies when changing/setting wallpapers with hyprpaper.

**Comment by vaxerski** [comment]
congratulations for bisecting it wrong lol
