### ISSUE TITLE
Add "stable" branch for those who want to pin to the latest release

### ISSUE THREAD

**Issue by LennyLizowzskiy** [hyprwm/Hyprland#5300]
### Description

Add "stable" branch to this repo so Nix users (and other people that use this repo directly) would be able to pin against latest release.

Right now we need to check if a new release is available and update the input if it is manually, but if there would be such branch then `nix flake update hyprland` would be able to do all the dirty work

**Comment by fufexan** [comment]
Something like this is better handled by npins or nvfetcher, which have builtin functionality to fetch the latest release of a repo.

Besides, tags for each release exist.

**Comment by LennyLizowzskiy** [comment]
These tools were designed for Nix derivation generation and there's almost no way to use them as input in Nix flakes (I can imagine some hacky workarounds, but nah)

Right now I use tags, but they can't be updated easily as I described in the first message

**Comment by khaneliman** [comment]
Just curious what you're using the repo flake for if you're tracking stable? Wouldn't it make more sense to just use nixpkgs if you want latest release?
