### ISSUE TITLE
Hyprland Crashes after Update

### ISSUE THREAD

**Issue by VoreckLukas** [hyprwm/Hyprland#5301]
### Hyprland Version

<details> <summary>System/Version info</summary>

I can't run the command as Hyprland crashes before running it and running it outside of hyprland get me this
```sh
❯ hyprctl systeminfo
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
```

</details>

### Bug or Regression?

Bug

### Description

I updated Hyprland. After that it keeps crashing when trying to start. on the discord someone guessed it had to do with cursors but i dont have a cursor theme set anywhere. 

### How to reproduce

-> Update the flake
-> Start Hyprland
-> crash

### Crash reports, logs, images, videos

[hyprlandCrashReport23213.txt](https://github.com/hyprwm/Hyprland/files/14787440/hyprlandCrashReport23213.txt)

**Comment by vaxerski** [comment]
update hyprcursor. Since this is nix, @fufexan

**Comment by mairs8** [comment]
i have the same issue. could someone please clarify what exactly the solution is here? Can i just update my flake.lock to match `d8429ee` to fix it?
