### ISSUE TITLE
Focus the window when clicking on a group bar tab

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#5302]
### Hyprland Version

Hyprland, built from branch  at commit 981540207490f402d1382eb3df149ece6db8b809  ().
Date: 2024-02-26
Tag: 

flags: (if any)

System Information:
System name: Linux
Node name: odyssey
Release: 6.6.22
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:25:07 UTC 2024

GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev dd) (prog-if 00 [VGA controller])

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240325.57e6b3a"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

plugins:

### Bug or Regression?

Bug

### Description

Currently Hyprland doesn't focus the window when a group bar tab is clicked. I never noticed before, but today I did. I don't think this is very strange, maybe it isn't a bug, maybe it's intentional. That is because the issue I describe here isn't actually the what I observed. I saw something weird happen but I can't describe it so I describe this instead :100:.

### How to reproduce

1. Have sex without contraceptives
2. Create a group of two or more windows.
3. Lock the group.
4. Switch to the first window in the group.
5. Open another window to the side or on another monitor.
   - Ensure the new window (outside the group) is focused.
6. Click on the second window in the group.
7. Observe that the focused window does not change.
   - The window outside the group remains focused.

**Comment by MightyPlaza** [comment]
should be fixed in git

**Comment by spikespaz** [comment]
Was it a regression that has been fixed within the last day?

**Comment by MightyPlaza** [comment]
you're on a month old version
https://github.com/hyprwm/Hyprland/pull/5224

**Comment by spikespaz** [comment]
Thanks for catching that, very strange.
