### ISSUE TITLE
document how to use libinput-gestures with hyprctl?

### ISSUE THREAD

**Issue by 2Senn** [hyprwm/Hyprland#5303]
### Description

I want to create a pinch to zoom gesture which does not exist in the default gestures. The docs say I should use libinput-gestures with hyprctl but I am not too sure how to go about doing that? 

Also what is the best way to implement pinch to zoom ? I only care about it working on browsers. 

I use vivaldi and brave browser. I thought it should work by default but does not seem like it.

**Comment by vaxerski** [comment]
it does work, you just have to launch it in wayland native mode.... read the wiki. https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland
