### ISSUE TITLE
IME does not work correctly with foot terminal emulator

### ISSUE THREAD

**Issue by horror-proton** [hyprwm/Hyprland#5305]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 93d05114716e847c37f49d3cc2d0c5cb01d06a24 dirty (layershell: update render pos and size in arrange).
Date: Thu Mar 28 00:30:08 2024
Tag: v0.37.1-72-g93d05114

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.2-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 27 Mar 2024 14:17:07 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT1 [UHD Graphics] [8086:46a3] (rev 0c) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] [10de:25a2] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

- fcitx5 candidate popup is not damaged correctly in [foot](https://codeberg.org/dnkl/foot) when typing
- in some cases IME popup were in wayland style at the top-left corner of the screen and cannot type anything into xwayland application.

### How to reproduce

- launch foot terminal emulator and fcitx5
  env:
  ```
  GTK_IM_MODULE=fcitx
  INPUT_METHOD=fcitx
  XMODIFIERS=@im=fcitx
  SDL_IM_MODULE=fcitx
  QT_IM_MODULE=fcitx
  ```
- type in foot terminal with IME, the popups does not disappear after finished typing
- launch `xterm` in the shell
- try to type with IME in xterm, IME works correctly
- terminate xterm and reopen in the same way
- try to type in the new xterm window again, IME does not work now

### Crash reports, logs, images, videos
```
0.37.1-29-9ddf1b10 good
0.37.1-72-93d05114 bad
```

it does not reproduce with konsole
foot seems to use text-input-unstable-v3

**Comment by q234rty** [comment]
probably a dup of https://github.com/hyprwm/Hyprland/issues/5256
