### ISSUE TITLE
Screenshare broken since v0.35.0 (on NVIDIA?)

### ISSUE THREAD

**Issue by julius-boettger** [hyprwm/Hyprland#5306]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 25718754534d0ccd87b198b63459497e63887f35  ().
Date: 2024-03-28
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.8.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:19:29 UTC 2024


GPU information:
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD103 [GeForce RTX 4080] [10de:2704] (rev a1) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.11.20240322.56528ee"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.11 (Tapir)"
SUPPORT_END="2024-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.11 (Tapir)"
VERSION_CODENAME=tapir
VERSION_ID="23.11"


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

When trying to share my screen (tested with Firefox and OBS Studio), I don't get any prompt to select the monitor/window/area I want to share (I think that prompt is from XDPH?). So effectively, I can not share my screen.

0.34.0 of Hyprland is the last version that works for me, I also just tested 0.35.0, 0.36.0, 0.37.1 and latest git (25718754534d0ccd87b198b63459497e63887f35), they all behave the same.

Could have to do with my proprietary NVIDIA GPU drivers or NixOS, not sure.

#4735 seems kind of similar.

### How to reproduce

- Use NVIDIA proprietary drivers and be on NixOS (not sure if relevant)
- Try to share your screen with a version newer than 0.34.0

**Comment by iddm** [comment]
Using Hyprland on ArchLinux, same thing. Also, have an NVIDIA video card, but I don't think it matters for some reason.

**Comment by skykanin** [comment]
Using Hyprland v0.37.1 on Nixos and having the same issue also with an NVIDIA GTX 1070 card.

**Comment by vaxerski** [comment]
bisect

**Comment by anders130** [comment]
Using both Hyprland v0.36.0 and v0.37.1 works on my NixOS setup. I currently have a NVIDIA GeForce GTX 1080 Ti card.

**Comment by vaxerski** [comment]
and that was fixed on -git ffs

**Comment by vaxerski** [comment]
#4791

if using 10-bit, this is an nv issue

**Comment by vaxerski** [comment]
> When trying to share my screen (tested with Firefox and OBS Studio), I don't get any prompt to select the monitor/window/area I want to share (I think that prompt is from XDPH?).

means XDPH is not running. Likely crashed. Check the unit (`systemctl --user xdg-desktop-portal-hyprland`) update it.

**Comment by MahouShoujoMivutilde** [comment]
After upgrading from 0.35.0 to 0.37.1 on Arch pipewire screenshare broke for me too, but I was able to """fix""" it by deleting my custom xdg-desktop-portal config.

Curious enough, it wasn't, as far as I could tell, wrong, and it only set my preferred filechooser to kde's one, like on the wiki.

After that portal started working fine.

**Comment by skykanin** [comment]
> #4791
> 
> if using 10-bit, this is an nv issue

Yeah that was the issue, disabling 10-bit in my hyprland config works as a workaround
