### ISSUE TITLE
Update `always_center_master`  to work on non-centered master mode orientations

### ISSUE THREAD

**Issue by derethil** [hyprwm/Hyprland#5312]
### Description

The current implementation of `always_center_master` only works with orientation=center. It would be nice to have the same option for e.g. orientation=left, so the master window doesn't fill the entire screen when it is the only window in the workspace. 

The option name would be rather misleading after implementing this feature, however, so maybe `always_center_master` can be removed in favor of `keep_master_when_only` or something.

### Use Case
Personally, my ultrawide screen isn't wide enough for the 3-column centered orientation but it's too wide for windows to take the full screen width comfortably. I wrote a small script to handle this by floating and resizing windows but it would be nice to have it builtin so windows are still tiled.

**Comment by thejch** [comment]
Possible with workspace selectors:
`workspace = w[t1], gapsout:20 400 20 400`

**Comment by derethil** [comment]
I completely missed that workspace selector in the docs, thanks - that solves my problem nicely

**Comment by thejch** [comment]
> I completely missed that workspace selector in the docs, thanks - that solves my problem nicely. I'll leave the issue open for now since your PR is related to it.

now you should be able to do
`workspace = w[t1], layoutopt:orientation:center`
to force center orientation when theres only 1 tiled window
better than the gaps solution IMO

also set `master:always_center_master = true` of cource

**Comment by derethil** [comment]
That doesn't seem to be doing anything for me - are there other settings I need to check to enable that behavior?

**Comment by derethil** [comment]
Adding this rule seems to introduce some weird behavior for me. (I normally use the left orientation:
- My default workspace is always left orientation. even with 1 tiled window. 
- Non-default workspaces are always center orientation, even with >1 tiled window. 
Are there some other options I should check that might be interfering with this?

**Comment by thejch** [comment]
probably a bug then. may get fixed in the future but i guess use gaps for now

**Comment by thejch** [comment]
actually, you can try
```
workspace = w[t1], layoutopt:orientation:center
workspace = w[t2], layoutopt:orientation:left
```
i think this works

**Comment by derethil** [comment]
Yep, can confirm that adding that second rule fixes it, thanks. Still seems like a bug though

**Comment by thejch** [comment]
yea it's bug but i cba to fix it now, since you can always just override it like that depending on your need
