### ISSUE TITLE
Hyprland Crashing periodically

### ISSUE THREAD

**Issue by iliesh** [hyprwm/Hyprland#5321]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
System Information:
System name: Linux
Node name: pc1
Release: 6.6.23-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 27 Mar 2024 07:47:20 +0000


GPU information:
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

~ x hyprctl version
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes periodically

### How to reproduce

It's intermintent, cannot reproduce

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14804884/hyprland.log)

**Comment by endeavour** [comment]
I am also seeing this. I can't reproduce it reliably either but I have noticed it tends to happen more often when I'm using VLC. Crash report attached.

[hyprlandCrashReport538995.txt](https://github.com/hyprwm/Hyprland/files/14806777/hyprlandCrashReport538995.txt)

**Comment by vaxerski** [comment]
run with asan please https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by endeavour** [comment]
Find asan log attached. It happened this time when I was closing the VLC window.
[asan.log](https://github.com/hyprwm/Hyprland/files/14807357/asan.log)

**Comment by endeavour** [comment]
Another crash that looks like it may be a different bug.
[asan2.log](https://github.com/hyprwm/Hyprland/files/14807481/asan2.log)

**Comment by endeavour** [comment]
I have a feeling this might have something to do with dragging and dropping. If I open a video by double-clicking it in dolphin it opens in VLC, and when I close VLC I haven't yet seen it crash.

If I open VLC, then drag a file from dolphin into the VLC window, occasionally the cursor in dolphin gets stuck on something it shouldn't be (like a resize cursor instead of a pointer), and then when I close the VLC window it crashes. Again it's not 100% reproducible consistently though.

**Comment by JakeTompkins** [comment]
I'm experiencing a much higher than usual number of crashes over the past few days too, but mine seem to have something to do with non-tiled windows.

Zoom and ags seem to be the most frequent offenders but it's hard to tell what exactly triggers it as like you said, it doesn't seem to be 100% consistent.

**Comment by vaxerski** [comment]
should be fixed, please report back.

**Comment by vaxerski** [comment]
oops, small mistake, fixed. Try now

**Comment by vaxerski** [comment]
re: asan log 2 looks like wlroots, not us, though. asan log 1 should be fixed.

**Comment by vaxerski** [comment]
though OPs log looks different, as if a fortify fail in FDtick of hyprctl.  @iliesh are you running any hyprctl commands? any that repeatedly crash hyprland?

**Comment by endeavour** [comment]
> should be fixed, please report back.

Looking promising so far, though difficult to be certain with these hard to reproduce bugs.

**Comment by endeavour** [comment]
Had another crash :(
[asan3.log](https://github.com/hyprwm/Hyprland/files/14808446/asan3.log)

**Comment by vaxerski** [comment]
both this and log nr 2 were from drag and drop operations, seemingly a crash in wlr. Anything odd you're doing?

**Comment by endeavour** [comment]
Nope but as mentioned above I have noticed some weird behaviour with the mouse cursor when dragging from Dolphin to VLC. When you move the cursor back over the dolphin window afterwards the incorrect cursor is shown. I don't recall ever having seen this when running kde plasma.

Not sure if this is related to the crash but perhaps it offers a clue.

Video attached.

https://github.com/hyprwm/Hyprland/assets/91404/b0ad71c2-efc8-4c64-8c6b-2d1edd489509

**Comment by vaxerski** [comment]
video aint playin

**Comment by MightyPlaza** [comment]
works on mpv

**Comment by vaxerski** [comment]
ah thats just dolphin. Dnd from wayland -> x11 is kinda wonky

**Comment by iliesh** [comment]
> though OPs log looks different, as if a fortify fail in FDtick of hyprctl. @iliesh are you running any hyprctl commands? any that repeatedly crash hyprland?

Not, just using the browser and few alacritty terminals. It happens randomly, sometimes 1-2 times per day, some days - no crash at all.

**Comment by roycrippen4** [comment]
I may be having the same issue. Very intermittent. It seems to only be happening to me when my mouse goes from one screen to another.

**Comment by iliesh** [comment]
> I may be having the same issue. Very intermittent. It seems to only be happening to me when my mouse goes from one screen to another.

Good point, I also use multiple screen, if that helps.

**Comment by endeavour** [comment]
Another crash report... this one looks different from the others (seems to be popup related).

[hyprlandCrashReport684646.txt](https://github.com/hyprwm/Hyprland/files/14816613/hyprlandCrashReport684646.txt)

**Comment by vaxerski** [comment]
can you grab the gdb `bt -full`? this one got kinda corrupted

**Comment by endeavour** [comment]
[bt.log](https://github.com/hyprwm/Hyprland/files/14817782/bt.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14817824/patch.txt)
try

**Comment by endeavour** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14817824/patch.txt) try

I haven't seen that particular stacktrace reoccur since applying the patch a couple of days ago but I'm still seeing other random crashes more similar to the other logs in this thread.

**Comment by vaxerski** [comment]
post stacktrace please

**Comment by endeavour** [comment]
In some cases I'm not seeing a hyprland log file and the core dump doesn't contain a stacktrace:

```
~  coredumpctl dump 863937 > /tmp/foo.dmp                                                                                            15.4s  Thu 04 Apr 2024 16:57:52 BST
           PID: 863937 (Hyprland)
           UID: 1000 (james)
           GID: 1000 (james)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-04-01 16:49:39 BST (3 days ago)
  Command Line: Hyprland
    Executable: /usr/local/bin/Hyprland
 Control Group: /user.slice/user-1000.slice/session-60.scope
          Unit: session-60.scope
         Slice: user-1000.slice
       Session: 60
     Owner UID: 1000 (james)
       Boot ID: bb6b03055f464eae93ccca99492fd5e7
    Machine ID: 0ba64d9f438a4548bb4591ef451dda1b
      Hostname: james-office-desktop
       Storage: none
       Message: Process 863937 (Hyprland) of user 1000 terminated abnormally without generating a coredump.
Coredump entry has no core attached (neither internally in the journal nor externally on disk).
```

I've attached the gdb stacktrace of the last crash I had that I was able to get a stacktrace from - again in this case no hyprland .log file seems to have been saved in .cache/hyprland for some reason.

[foo3.log](https://github.com/hyprwm/Hyprland/files/14873984/foo3.log)

**Comment by endeavour** [comment]
Another crash that just occured.
[hyprlandCrashReport1063413.txt](https://github.com/hyprwm/Hyprland/files/14874507/hyprlandCrashReport1063413.txt)

**Comment by vaxerski** [comment]
yea this is odd. Can you run asan?

**Comment by endeavour** [comment]
I haven't had any crashes for a couple of days running commit 558d1be7e3c9242b39fe78efe74ada1298112892 so fingers crossed it's fixed.

**Comment by izmyname** [comment]
> I haven't had any crashes for a couple of days running commit [558d1be](https://github.com/hyprwm/Hyprland/commit/558d1be7e3c9242b39fe78efe74ada1298112892) so fingers crossed it's fixed.

Prolly, worth closing then?
