### ISSUE TITLE
Window rules not enforced for special workspace

### ISSUE THREAD

**Issue by Kommynct** [hyprwm/Hyprland#5325]
### Discussed in https://github.com/hyprwm/Hyprland/discussions/5318

<div type='discussions-op-text'>

<sup>Originally posted by **Kommynct** March 29, 2024</sup>
I have a bunch of

windowrulev2 = bordersize 0,class:(firefox)

In my config file, but I have a special workspace that I want everything to always have borders in (because there are gaps in the special workspace anyway)

workspace=special,gapsin:20,gapsout:120,bordersize:2,border:true

I've tried the above, but it doesn't effect firefox, how would I achieve this?</div>

**Comment by MightyPlaza** [comment]
use the `unset` window rule and match it to the class and workspace you want, put those rules at the top of the config file

**Comment by Kommynct** [comment]
windowrulev2 = unset,class:(firefox),workspace:special
windowrulev2 = bordersize 0,class:(firefox)
workspace=special,gapsin:20,gapsout:120,bordersize:2,border:true

in that order is not resolving the issue, am I doing something wrong?

**Comment by MightyPlaza** [comment]
should be `windowrulev2 = unset, workspace:special, class:(firefox)` and not
`windowrulev2 = unset, workspace special, class:(firefox)`

**Comment by Kommynct** [comment]
windowrulev2 = unset, workspace:special, class:(firefox)
windowrulev2 = bordersize 0,class:(firefox)
workspace=special,gapsin:20,gapsout:120,bordersize:2,border:true

in that order is still not working for me

**Comment by MightyPlaza** [comment]
it does work for non special workspaces, so it's likely a bug

**Comment by Kommynct** [comment]
Yeah, can confirm
windowrulev2 = bordersize 0,class:(firefox)
windowrulev2 = bordersize 2, workspace:1, class:(firefox)
workspace=special,gapsin:20,gapsout:120,bordersize:2,border:true

sets the border only when on workspace 1, @vaxerski somethings definitely wrong with special workspaces

**Comment by vaxerski** [comment]
I dont understand

**Comment by Kommynct** [comment]
if you have a config file with:

windowrulev2 = bordersize 0,class:(firefox)
windowrulev2 = bordersize 2, workspace:1, class:(firefox)

then when firefox is on workspace 1 it has a 2px border, elsewhere it has a 0px border

but if you set 

windowrulev2 = bordersize 0,class:(firefox)
windowrulev2 = bordersize 2, workspace:special, class:(firefox)
workspace=special,gapsin:20,gapsout:120,bordersize:2,border:true

firefox does not have a 2px border in the special workspace

**Comment by MightyPlaza** [comment]
workspace rules for special are fixed on git, does that close this?
