### ISSUE TITLE
Touch input carries across monitors

### ISSUE THREAD

**Issue by Oskar-Idland** [hyprwm/Hyprland#5327]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

# The Issue
My laptop (Lenovo Yoga 7i) has touch input. When connected to a second monitor, the output of the touch is spread across both . Touching the right-hand side of the screen, affects the content on the monitor on the right, not what is on the right-hand side of the laptop screen. This makes the touch unusable when having a multi-monitor setup. My laptop is a bit over 1/2 the width of the monitor, and that corresponds perfectly to where the cutoff between the input affecting the other monitor begins. See the attached video

# Tested Solutions
If I understood the wiki on [touch devices](https://wiki.hyprland.org/Configuring/Variables/#touchdevice) correctly, there should be a way to set the output of touch to a specific monitor (hopefully my laptop screen). I tried adding the following to my config file:
```sh
touchdevice {
 output = eDP-1
}
```
as that is the name of the monitor when using `hyprctl monitors all`, but it did not work.
# Video
https://github.com/hyprwm/Hyprland/assets/69601310/762caf04-06c1-4d2d-8237-32ffa4b1371f

### How to reproduce

Connect a laptop with touch screen to a monitor, and check to see if the touch input persist across the other monitor when touching the edges.

**Comment by Oskar-Idland** [comment]
Is that not what I did/attempted?

**Comment by vaxerski** [comment]
it should be in `input { }`

**Comment by Oskar-Idland** [comment]
It is. Here is the full input config:
```sh
input {
    kb_layout = no
    follow_mouse = 1

    sensitivity = 0.2 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = false
    scroll_points = 0.2 0.0 0.5 1 1.2 1.5

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.25
    }
    touchdevice {
        output = eDP-1
    }
}
```

**Comment by vaxerski** [comment]
I've noticed you're on 0.37.1, have you tried on git?

**Comment by Oskar-Idland** [comment]
Yes I just tested it now. Still the same

**Comment by Oskar-Idland** [comment]
`hyprctl devices` showed the following:
```sh
Tablets:
	Tablet at 591143b2c460:
		wacom-hid-5363-pen
			size: 301.82x188.64mm
	Tablet Tool at 591144942910 (belongs to 591144942910)


Touch:
	Touch Device at 591143546ba0:
		wacom-hid-5363-finger
```
meaning that both `Tablet` and `Touch` had to redirect the output. The solution was the following:
```
input {
	tablet {
		output = eDP-1
	}
	touchdevice {
		output = eDP-1
	}	
}
```
