### ISSUE TITLE
Hyperpm Causes C Out of Range Error

### ISSUE THREAD

**Issue by modestbadger1773** [hyprwm/Hyprland#5329]
### Hyprland Version

Hyprland, built from branch main at commit 54376d7b5f88bffd96ce9ded26637d83d7aa95b1 dirty (compositor: remove windows from fading out on destroy).
Date: Sat Mar 30 06:07:18 2024
Tag: v0.37.1-84-g54376d7b

flags: (if any)

System Information:
System name: Linux
Node name: NewWestAtlantis
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000

GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 02) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 22) > this->size() (which is 0)
[1]    3794 IOT instruction (core dumped)  hyprpm reload -f

### How to reproduce

hyprpm update
hyprpm reload

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/165446573/ffe9c208-e956-4029-970c-f0cc37213fe1)

**Comment by vaxerski** [comment]
can you use `coredumpctl debug hyprpm` and show `bt -full`?

**Comment by modestbadger1773** [comment]
> can you use `coredumpctl debug hyprpm` and show `bt -full`?

'coredumpctl debug hyprpm'

           PID: 4673 (hyprpm)
           UID: 1000 (cyber-cowboy-poseidon)
           GID: 1000 (cyber-cowboy-poseidon)
        Signal: 6 (ABRT)
     Timestamp: Sat 2024-03-30 13:47:55 AEDT (16min ago)
  Command Line: hyprpm update
    Executable: /usr/bin/hyprpm
 Control Group: /user.slice/user-1000.slice/user@1000.service/tmux-spawn-5f0a3a0f-099b-46c8-a191-8de9848920fe.scope
          Unit: user@1000.service
     User Unit: tmux-spawn-5f0a3a0f-099b-46c8-a191-8de9848920fe.scope
         Slice: user-1000.slice
     Owner UID: 1000 (cyber-cowboy-poseidon)
       Boot ID: 71c24c6f0b4842689e09ae4f7b7f7aed
    Machine ID: c77a82fbf90e4c09a85b9ea4724ccdf8
      Hostname: NewWestAtlantis
       Storage: /var/lib/systemd/coredump/core.hyprpm.1000.71c24c6f0b4842689e09ae4f7b7f7aed.4673.1711766875000000.zst (present)
  Size on Disk: 53.5K
       Message: Process 4673 (hyprpm) of user 1000 dumped core.
                
                Stack trace of thread 4673:
                #0  0x00007d6d604ab32c n/a (libc.so.6 + 0x8d32c)
                #1  0x00007d6d6045a6c8 raise (libc.so.6 + 0x3c6c8)
                #2  0x00007d6d604424b8 abort (libc.so.6 + 0x244b8)
                #3  0x00007d6d6069ca6f _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9ca6f)
                #4  0x00007d6d606b011c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb011c)
                #5  0x00007d6d606b0189 _ZSt9terminatev (libstdc++.so.6 + 0xb0189)
                #6  0x00007d6d606b03ed __cxa_throw (libstdc++.so.6 + 0xb03ed)
                #7  0x00007d6d606a025f _ZSt24__throw_out_of_range_fmtPKcz (libstdc++.so.6 + 0xa025f)
                #8  0x00005e50a20fdad7 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6substrEmm (hyprpm + 0x9ad7)
                #9  0x00005e50a210d5dd _ZN14CPluginManager12headersValidEv (hyprpm + 0x195dd)
                #10 0x00005e50a20fbd8b main (hyprpm + 0x7d8b)
                #11 0x00007d6d60443cd0 n/a (libc.so.6 + 0x25cd0)
                #12 0x00007d6d60443d8a __libc_start_main (libc.so.6 + 0x25d8a)
                #13 0x00005e50a20fcce5 _start (hyprpm + 0x8ce5)
                ELF object binary architecture: AMD x86-64

'bt -full'

#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {137908722542640}}
        ret = <optimized out>
#1  0x00007d6d604ab393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
No locals.
#2  0x00007d6d6045a6c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007d6d604424b8 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {103700410949784, 69, 137908720368164, 137908721775840, 137908720375645, 103700410949784, 137908721775840, 137908721766480, 137908721775971, 1, 
              137908720368164, 1, 10, 103700410947296, 566, 140722361687648}}, sa_flags = 1615464489, sa_restorer = 0x7d6d605f74e0 <_IO_2_1_stderr_>}
#4  0x00007d6d6069ca6f in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#5  0x00007d6d606b011c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
No locals.
#6  0x00007d6d606b0189 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
No locals.
#7  0x00007d6d606b03ed in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7d6d6086c0e8 <typeinfo for std::out_of_range>, dest=0x7d6d606c85c0 <std::out_of_range::~out_of_range()>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
        globals = <optimized out>
        header = 0x5e50a2285eb0
#8  0x00007d6d606a025f in std::__throw_out_of_range_fmt (__fmt=__fmt@entry=0x5e50a211d0e0 "%s: __pos (which is %zu) > this->size() (which is %zu)") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/functexcept.cc:101
        __len = 54
        __alloca_size = 566
        __s = 0x7ffc7a615a00 "basic_string::substr: __pos (which is 22) > this->size() (which is 0)"
        __ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffc7a615d40, reg_save_area = 0x7ffc7a615c60}}
#9  0x00005e50a20fdad7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_check (__s=0x5e50a211f246 "basic_string::substr", __pos=<optimized out>, this=<optimized out>)
    at /usr/include/c++/13.2.1/bits/basic_string.h:379
No locals.
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr (this=<optimized out>, __pos=<optimized out>, __n=<optimized out>) at /usr/include/c++/13.2.1/bits/basic_string.h:3153
No locals.
#11 0x00005e50a210d5dd in CPluginManager::headersValid (this=<optimized out>) at ../hyprpm/src/core/PluginManager.cpp:336
        HLVER = {branch = "main", hash = "54376d7b5f88bffd96ce9ded26637d83d7aa95b1"}
        cmd = "PKG_CONFIG_PATH=\"/home/cyber-cowboy-poseidon/.local/share/hyprpm/headersRoot/share/pkgconfig\" pkg-config --cflags --keep-system-cflags hyprland"
        headers = ""
        verHeader = "/home/cyber-cowboy-poseidon/.local/share/hyprpm/headersRoot/include/hyprland/src/version.h"
        ifs = {<std::basic_istream<char, std::char_traits<char> >> = {<std::basic_ios<char, std::char_traits<char> >> = {<std::ios_base> = {_vptr.ios_base = 0x7d6d6086fd68 <vtable for std::basic_ifstream<char, std::char_traits<char> >+64>, 
                static boolalpha = std::_S_boolalpha, static dec = std::_S_dec, static fixed = std::_S_fixed, static hex = std::_S_hex, static internal = std::_S_internal, static left = std::_S_left, static oct = std::_S_oct, 
                static right = std::_S_right, static scientific = std::_S_scientific, static showbase = std::_S_showbase, static showpoint = std::_S_showpoint, static showpos = std::_S_showpos, static skipws = std::_S_skipws, 
                static unitbuf = std::_S_unitbuf, static uppercase = std::_S_uppercase, static adjustfield = std::_S_adjustfield, static basefield = std::_S_basefield, static floatfield = std::_S_floatfield, static badbit = std::_S_badbit, 
                static eofbit = std::_S_eofbit, static failbit = std::_S_failbit, static goodbit = std::_S_goodbit, static app = std::_S_app, static ate = std::_S_ate, static binary = std::_S_bin, static in = std::_S_in, 
                static out = std::_S_out, static trunc = std::_S_trunc, static __noreplace = std::_S_noreplace, static beg = std::_S_beg, static cur = std::_S_cur, static end = std::_S_end, _M_precision = 6, _M_width = 0, _M_flags = 4098, 
                _M_exception = std::_S_goodbit, _M_streambuf_state = std::_S_goodbit, _M_callbacks = 0x0, _M_word_zero = {_M_pword = 0x0, _M_iword = 0}, _M_local_word = {{_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {
                    _M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}}, _M_word_size = 8, 
                _M_word = 0x7ffc7a616000, _M_ios_locale = {static none = 0, static ctype = 1, static numeric = 2, static collate = 4, static time = 8, static monetary = 16, static messages = 32, static all = 63, 
                  _M_impl = 0x7d6d60878d20 <(anonymous namespace)::c_locale_impl>}}, _M_tie = 0x0, _M_fill = 0 '\000', _M_fill_init = false, _M_streambuf = 0x7ffc7a615ed0, _M_ctype = 0x7d6d60878740 <(anonymous namespace)::ctype_c>, 
              _M_num_put = 0x7d6d608786d0 <(anonymous namespace)::num_put_c>, _M_num_get = 0x7d6d608786e0 <(anonymous namespace)::num_get_c>}, 
            _vptr.basic_istream = 0x7d6d6086fd40 <vtable for std::basic_ifstream<char, std::char_traits<char> >+24>, _M_gcount = 0}, _M_filebuf = {<std::basic_streambuf<char, std::char_traits<char> >> = {
              _vptr.basic_streambuf = 0x5e50a2125850 <vtable for std::basic_filebuf<char, std::char_traits<char> >+16>, _M_in_beg = 0x0, _M_in_cur = 0x0, _M_in_end = 0x0, _M_out_beg = 0x0, _M_out_cur = 0x0, _M_out_end = 0x0, _M_buf_locale = {
                static none = 0, static ctype = 1, static numeric = 2, static collate = 4, static time = 8, static monetary = 16, static messages = 32, static all = 63, _M_impl = 0x7d6d60878d20 <(anonymous namespace)::c_locale_impl>}}, 
            _M_lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, _M_file = {_M_cfile = 0x0, 
              _M_cfile_created = true}, _M_mode = 0, _M_state_beg = {__count = 0, __value = {__wch = 0, __wchb = "\000\000\000"}}, _M_state_cur = {__count = 0, __value = {__wch = 0, __wchb = "\000\000\000"}}, _M_state_last = {__count = 0, 
              __value = {__wch = 0, __wchb = "\000\000\000"}}, _M_buf = 0x0, _M_buf_size = 8192, _M_buf_allocated = false, _M_reading = false, _M_writing = false, _M_pback = 0 '\000', _M_pback_cur_save = 0x0, _M_pback_end_save = 0x0, 
            _M_pback_init = false, _M_codecvt = 0x7d6d608786b0 <(anonymous namespace)::codecvt_c>, _M_ext_buf = 0x0, _M_ext_buf_size = 0, _M_ext_next = 0x0, _M_ext_end = 0x0}}
        verHeaderContent = ""
        hash = "v@\"GU^\000\000\270\n_\2001e^\304wboy-poseidon/.local/share/hyprpm/headersRoot/include"
#12 0x00005e50a20fbd8b in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at ../hyprpm/src/main.cpp:95
        headersValid = <optimized out>
        headers = <optimized out>
        ARGS = std::vector of length 2, capacity 2 = {"hyprpm", "update"}
        command = std::vector of length 1, capacity 1 = {"update"}
        notify = <optimized out>
        verbose = <optimized out>
        force = <optimized out>

**Comment by vaxerski** [comment]
thanks! should be fixed with above, try that.

**Comment by modestbadger1773** [comment]
> thanks! should be fixed with above, try that.

Sorry, really noob question, suggestion on how to install this? Where do I find the file to modify?

**Comment by vaxerski** [comment]
just update, it's a commit

**Comment by modestbadger1773** [comment]
> just update, it's a commit

Works, thanks!
