### ISSUE TITLE
Sporadic Crashing

### ISSUE THREAD

**Issue by JoshuaFern** [hyprwm/Hyprland#533]
Not sure the cause. Probably not a one off bug, had crashes like this before but I didn't look into it.

Nvidia/NixOS

[coredump.log](https://github.com/hyprwm/Hyprland/files/9353855/coredump.log)

**Comment by vaxerski** [comment]
check on latest, cant promise anything tho as i couldnt reproduce this so i had to take a guess

**Comment by ThatOneCalculator** [comment]
Possibly nvidia related?

**Comment by vaxerski** [comment]
no, lol, the crash is clearly hl

**Comment by ThatOneCalculator** [comment]
guess im just bad at reading logs kek

**Comment by JoshuaFern** [comment]
Thanks, I'll follow up if it happens again.

**Comment by JoshuaFern** [comment]
Hi, had two more crashes today with the latest hyprland. 

[hyprland.log](https://github.com/hyprwm/Hyprland/files/9385322/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9385324/coredump.log)

**Comment by vaxerski** [comment]
no, you did not. It's just your fantasy. 


(jk let me finish my shower i'll fix that rq)

**Comment by JoshuaFern** [comment]
And here's the other crash log... 
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9385335/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9385337/coredump.log)

**Comment by vaxerski** [comment]
I think I fixed it. Please verify.

**Comment by JoshuaFern** [comment]
Seems okay, no crashes so far.

**Comment by JoshuaFern** [comment]
Hi, had two crashes today.

I was playing a game and switched workspaces when this one happened.
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9413708/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9413720/coredump.log)

Not sure what I was doing during this one.
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9413729/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9413733/coredump.log)

**Comment by JoshuaFern** [comment]
Another one...
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9436787/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9436790/coredump.log)

**Comment by vaxerski** [comment]
might be fixed.

**Comment by JoshuaFern** [comment]
Thanks, closing until it happens again.

**Comment by JoshuaFern** [comment]
I'm back again.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/9457231/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9457233/coredump.log)

**Comment by JoshuaFern** [comment]
> Meaning you corrupted the dwindle binary tree. What were you doing?

I was just playing a game, it was using Proton.

> but i suck at those, what does this do?

It's a hacky way to setup my workspace switching, basically it uses `jq` to parse the json output of `hyprctl` so I can have twice as many workspaces with the same buttons.

Like if I'm on workspace 2 and I hit the workspace 1 bind it goes to workspace 1, and I hit the workspace 1 bind again while on workspace 1 it goes to workspace 11 instead. Every workspace has like a mirror workspace that I can store other windows on.

Here's how it looks in my config:
```
    # Double tap workspaces
    bind=SUPER,1,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "1" ]; then NW=11; else NW=1; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,1,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "1" ]; then NW=11; else NW=1; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,2,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "2" ]; then NW=12; else NW=2; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,2,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "2" ]; then NW=12; else NW=2; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,3,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "3" ]; then NW=13; else NW=3; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,3,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "3" ]; then NW=13; else NW=3; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,4,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "4" ]; then NW=14; else NW=4; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,4,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "4" ]; then NW=14; else NW=4; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,5,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "5" ]; then NW=15; else NW=5; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,5,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "5" ]; then NW=15; else NW=5; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,6,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "6" ]; then NW=16; else NW=6; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,6,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "6" ]; then NW=16; else NW=6; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,7,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "7" ]; then NW=17; else NW=7; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,7,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "7" ]; then NW=17; else NW=7; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,8,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "8" ]; then NW=18; else NW=8; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,8,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "8" ]; then NW=18; else NW=8; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,9,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "9" ]; then NW=19; else NW=9; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,9,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "9" ]; then NW=19; else NW=9; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,0,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "10" ]; then NW=20; else NW=10; fi; hyprctl dispatch workspace $NW
    bind=SUPERSHIFT,0,exec,CW=$(hyprctl -j monitors | jq '.[]|.activeWorkspace.id'); if [ $CW = "10" ]; then NW=20; else NW=10; fi; hyprctl dispatch movetoworkspacesilent $NW
    bind=SUPER,grave,togglespecialworkspace
    bind=SUPERSHIFT,asciitilde,movetoworkspacesilent,special
```

Let me know if you have a better way to do this.

**Comment by JoshuaFern** [comment]
Hi, back again. Was playing Splitgate when it crashed this time.

[hyprland.log](https://github.com/hyprwm/Hyprland/files/9484363/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9484367/coredump.log)

**Comment by vaxerski** [comment]
yuck, splatgate

**Comment by vaxerski** [comment]
Although I am unsure what happened and why, might be fixed in ff26531e11b55854c5937dac2f2ba121c78e11b9

**Comment by JoshuaFern** [comment]
That was fast, thanks again.

**Comment by JoshuaFern** [comment]
Happened again

[hyprland.log](https://github.com/hyprwm/Hyprland/files/9485623/hyprland.log)
[coredump.log](https://github.com/hyprwm/Hyprland/files/9485625/coredump.log)

**Comment by vaxerski** [comment]
can you fucking stop breaking my software? >:((

**Comment by vaxerski** [comment]
cb839c9dcc0196312e5c6b7014114d9b489e0632 should prevent this crash. Although this might cause some layout issues whenever it would've crashed before.

Can you tell me what you were doing though? This is some spooky fucking shit that's happening. Somehow you're on a workspace with a fullscreen window that doesnt have a fullscreen window.

**Comment by JoshuaFern** [comment]
What can I say? I'm apparently great at breaking things.

I wasn't doing anything crazy, just using my computer as I normally do. I think I was just closing a window when the crash happened. 

Here's my hyprland.conf if you'd like to review it https://gist.github.com/JoshuaFern/b7752eb6856a531e8e3552b88832457b

**Comment by vaxerski** [comment]
what window were you closing? maybe i can repro this? Again, your issue stems from a workspace with an apparently fucking quantum state of fullscreen-ness

**Comment by JoshuaFern** [comment]
I don't remember what I was closing, might be related to https://github.com/hyprwm/Hyprland/issues/625

**Comment by KyleUltimate** [comment]
Crash, when opening/switching layouts and playing osu
log: https://0x0.st/ofMJ.log
hyprland coredump: https://0x0.st/ofMy.txt
xwayland coredump: https://0x0.st/ofMt.txt

**Comment by vaxerski** [comment]
can you give me `bt -full` from the gdb debug console of this dump? `coredumpctl debug <pid>` and then once you get to `(gdb)` do `bt -full`

**Comment by vaxerski** [comment]
yes thank you

shame the dump didnt record even locals, meh
