### ISSUE TITLE
Limit Number of Config Errors Displayed At Once

### ISSUE THREAD

**Issue by modestbadger1773** [hyprwm/Hyprland#5331]
### Description

Limit the number of config error warnings displayed to 5 (or 10, etc) and the final warning be 'and n other errors.' (Where n is number of errors beyond what was displayed).

Reasoning: I updated today not realizing the change to the interpretation of ## comments and rebooted into this:

![hyprconfigerrors](https://github.com/hyprwm/Hyprland/assets/165446573/6942a8a1-0d3f-43f5-9af1-4e431809a218)

**Really not helpful** - I had to load into gnome to fix my config files as the warnings covered the entire screen.

I understand that some may want this to still be possible, but could we have a setting that defaults to my suggestion.

Thanks,

modest.

**Comment by Ligthiago** [comment]
Already implemented in https://github.com/hyprwm/Hyprland/pull/5165
