### ISSUE TITLE
Using my custom keyboard layouts doesn't work as expected when using `grp:alt_space_toggle` or `grp:win_space_toggle`

### ISSUE THREAD

**Issue by rempas** [hyprwm/Hyprland#5332]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ae52b7f4680716976d05b638aaa90e169d199117 dirty (textinput: fix ime when opening multiple windows (5281)).
Date: Tue Mar 26 16:16:09 2024
Tag: v0.37.1-71-gae52b7f4

flags: (if any)


System Information:
System name: Linux
Node name: Arco
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
10:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] [1002:67ef] (rev cf) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

First of all, hello and thank you and every who contributes for your amazing work! I switched to Gnome (Wayland) a couple of months ago from using Plasma (X11) and yesterday, I finally gave Hyprland a try (avoiding it as I wanted to avoid tilling window management) and I have to say, the project is great and even dare say that it's close to Gnome's Wayland compositor!
 
Now, for the actual problem! I am using two custom keyboard layouts, [rempas](https://opengist.thomice.li/rempas/37f02c6807bd4e3e96863d17b5dc9fa9) and [rempas_el](https://opengist.thomice.li/rempas/2f14086f4b884a7088d1064f1bacb071). While they are normally recognized and work, the problem is that, when setting either `grp:alt_space_toggle` or `grp:win_space_toggle` in the `kb_options` variable, the "Shift+Space" keybind (that generates a backspace), doesn't work and now just generates a space.

What's even wired is that, if I use `grp:lalt_lshift_toggle` instead, it works as expected! So, I have found something that works (tho I prefer `grp:win_space_toggle`) and this is low priority but thought to report it anyway because it's the bug nonetheless!

In case that helps, here is my "input" section in the config file:

```conf
input {
    kb_layout = rempas, rempas_el
    kb_variant =
    kb_model =
    kb_options = caps:swapescape, grp:alt_space_toggle # or `grp:win_space_toggle`
    kb_rules =
    repeat_rate = 35
    repeat_delay = 200

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = -0.7 # -1.0 - 1.0, 0 means no modification.
}
```

Thanks to everyone who works on Hyprland and provides alternatives to the bloated and heavy desktop environments! If you need anything else, I'll be happy to help!

### How to reproduce

Set the options and try to type!

**Comment by vaxerski** [comment]
that's handled by xkb, not hyprland

**Comment by rempas** [comment]
> that's handled by xkb, not hyprland

You are right, I can confirm! I tried it on OpenBox and it indeed has the same behavior! Gnome does work however so I couldn't knew that they do it another way. Thanks for the support and have a lovely day!

**Comment by ArshiAAkhavan** [comment]
> > that's handled by xkb, not hyprland
> 
> You are right, I can confirm! I tried it on OpenBox and it indeed has the same behavior! Gnome does work however so I couldn't knew that they do it another way. Thanks for the support and have a lovely day!

Did you report the bug in xkb?

I have the same issue and Shift+Space doesn't produce the zero-length,non-joiner space in IR keyboard when I set win+space for toggle

**Comment by rempas** [comment]
> Did you report the bug in xkb?
> 
> I have the same issue and Shift+Space doesn't produce the zero-length,non-joiner space in IR keyboard when I set win+space for toggle

Yes, [I did report it](https://github.com/xkbcommon/libxkbcommon/issues/479). But you should also report your problem.
