### ISSUE TITLE
WOOO, rofi got pop up animation !!!

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/Hyprland#5336]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

well its not a bug, now with updating my arch system, notifications and rofi, got popup animations. ITS SOO COOL, but how do i modify the animation speed or change the type of animation ?
PLease help

### How to reproduce

no need

**Comment by tchofy** [comment]
The wiki would've been a good start. Check https://wiki.hyprland.org/Configuring/Animations/#animation-tree

You want the layers one.

**Comment by vaxerski** [comment]
this is not where you ask for help
