### ISSUE TITLE
How can I get c-cedilla on US Intl. keyboard layout?

### ISSUE THREAD

**Issue by bitterteriyaki** [hyprwm/Hyprland#5338]
When I use `' + c`, I get `ć` instead of `ç`.

My `hyprland.conf`:
```
input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}
```

**Comment by vaxerski** [comment]
this is not an xkb help forum

**Comment by bitterteriyaki** [comment]
Hi, @vaxerski. Thank you for the quick answer. XKB has nothing with this issue because Hyprland does not use X11. When I used X11, I used to create a `~/.XCompose` file to change the default XKB mapping but this does not work on Wayland (only apps that use XWayland), and there isn't any material on internet about this.

What is a good place to ask this?

**Comment by vaxerski** [comment]
wayland uses xkb and so does hyprland.

**Comment by bitterteriyaki** [comment]
Oh, ok then. Thank you for the answer!
