### ISSUE TITLE
NVK Support

### ISSUE THREAD

**Issue by Zambieslar** [hyprwm/Hyprland#5341]
### Description

Partially a feature request but also a question. Are there any plans on adding NVK support in the future, or is it already supported? Given that they are just around the corner and the drivers are available it would be nice to know if opening issues when using NVK is feasible in it's current state. 

I have tested NVK on Hyprland and they are phenomenal, but there are a couple of crashes that I'm not entirely sure is Hyprland related, wlroots related, or just a bug with the NVK drivers.

**Comment by vaxerski** [comment]
NVK, as the name suggests, works on _vulkan_. We do not ship a vulkan renderer.

**Comment by KosmX** [comment]
When running on nouveau drivers, there are two possible hardware accelerated drivers: nouveau gallium and zink on NVK.  
> by default, the gallium driver is used for OpenGL (as of today), you can force zink on NVK by setting `MESA_LOADER_DRIVER_OVERRIDE` env var to `zink`


The zink driver is waay faster than the gallium driver, but something is still missing from NVK to be able to run wlroots based compositors.



Anyway, here's some logs from an attempt:
```

[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 21.52µs. Estimated average calc time: 0.03µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 9.48µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/kosmx/.config/hypr/hyprland.conf
[wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
[wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
[wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
[wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
[wlr] [render/egl.c:268] Failed to initialize EGL
[wlr] [render/egl.c:571] Failed to initialize EGL context
[wlr] [render/gles2/renderer.c:503] Could not initialize EGL
[CRITICAL] m_sWLRRenderer was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_gles2_renderer_create_with_drm_fd() failed!
[CRITICAL] Hyprland has crashed :( Consult the crash report at /home/kosmx/.cache/hyprland/hyprlandCrashReport18229.txt for more information.
```

**Comment by RLB2310** [comment]
NVK from the AUR works fine apart from running any 3D application. I believe this is due to the lack of DRi3 support through Xwayland. Testing NVK for a while and these are some logs from vkcube:```
 Selected GPU 0: NVIDIA GeForce RTX 2060 (NVK TU106), type: DiscreteGpu
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
Could not find both graphics and present queues
```
Xorg config is as per the vulkan DRI3 recommendations:

```
Section "Device"
    Identifier      "NVIDIA Corporation"
    Driver          "nouveau"
    BusID            "PCI:1:0:0"
    Option           "DRI"      "3"
EndSection
```
