### ISSUE TITLE
Wrong assumption in CMakeLists.txt

### ISSUE THREAD

**Issue by cnt0** [hyprwm/Hyprland#5345]
### Hyprland Version

git main

### Bug or Regression?

Bug

### Description

Hyprland cmake build script [defines](https://github.com/hyprwm/Hyprland/blob/16a9c16d9f99bd8be9f1bb15442b001fdf2ea759/CMakeLists.txt#L103C1-L103C30)
```
find_package(OpenGL REQUIRED)
```
and then tries to link target with EGL:

```
target_link_libraries(Hyprland
 ...
       OpenGL::EGL
 ...
)
```
However, `OpenGL::EGL` might be undefined at this point. Cmake documentation [confirms that](https://cmake.org/cmake/help/latest/module/FindOpenGL.html)

> OpenGL::EGL. Defined if the system has EGL.

And this is indeed the case on my system (alpine edge), where cmake complains that `OpenGL::EGL` is undefined. The way to work around this problem is like this:
```
find_package(OpenGL REQUIRED COMPONENTS GLES3)
```
This way everything builds just fine. I don't know what's the proper fix though. Maybe just use [FindEGL from extra-cmake-modules](https://api.kde.org/ecm/find-module/FindEGL.html), this is a much simpler cmake script? 

While we're here, maybe also use `FindWayland{,Scanner,Protocols}` from ECM? [link](https://api.kde.org/ecm/find-module/FindWaylandScanner.html). This will allow to clean a lot of custom logic from CMakeLists.txt. Like `find_program(WaylandScanner)`, `execute_process(pkg-config --variable=pkgdatadir wayland-protocols)`, `function(protocol)`, etc. I can prepare a PR if this looks good.

### How to reproduce

build hyprland from git main on alpine edge

**Comment by vaxerski** [comment]
feel free to make a MR. No ECM, though.
