### ISSUE TITLE
please reopen #5295

### ISSUE THREAD

**Issue by liyjii** [hyprwm/Hyprland#5347]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

The problem still exists,please see [this](https://github.com/hyprwm/Hyprland/issues/5295#issuecomment-2026568977)

### How to reproduce

#5295

**Comment by vaxerski** [comment]
please don't open such issues, just tag me under the original one again. I sometimes miss them.
