### ISSUE TITLE
workspace event isn't sent when focusing a workspace on another monitor

### ISSUE THREAD

**Issue by diniamo** [hyprwm/Hyprland#5350]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 16a9c16d9f99bd8be9f1bb15442b001fdf2ea759  ().
Date: 2024-03-31
Tag: 

flags: (if any)


```

</details>

### Bug or Regression?

Bug

### Description

When focusing a workspace on another monitor, the workspace (and now workspacev2) events aren't sent.

### How to reproduce

1. Run `socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock` in a terminal
2. Press a keybind, or click into another workspace to focus it
3. Notice that there are no workspace events printed

**Comment by vaxerski** [comment]
idk is reading that hard?

![image](https://github.com/hyprwm/Hyprland/assets/43317083/c07efee6-a864-4e53-87fb-6a1eeabfddc7)

https://wiki.hyprland.org/IPC/
