### ISSUE TITLE
Toggle focus between tiled and floating dispatcher

### ISSUE THREAD

**Issue by aacebedo** [hyprwm/Hyprland#5351]
### Description

When having a both tiled and floating windows, it seems impossible to switch between the tiled and floating ones without using the mouse. 

Would it be possible to add a dispatcher to focus the floating windows ?

**Comment by MightyPlaza** [comment]
`hyprctl dispatch focuswindow floating/tiled`

**Comment by aacebedo** [comment]
That's a good starting point yes but it is not a toggle. having it without a script would be great

**Comment by MightyPlaza** [comment]
`hyprctl dispatch focuswindow $(if [[ $(hyprctl activewindow -j | jq ."floating") == "true" ]]; then echo "tiled"; else echo "floating"; fi;)`

**Comment by aacebedo** [comment]
Thanks. I'll use it. Still it is strange to have the togglefloating dispatcher but not the equivalent for focus.

**Comment by GDYendell** [comment]
Could this be re-opened for a true toggle dispatcher to be added without the need for a script?
