### ISSUE TITLE
Alternative workspace handling

### ISSUE THREAD

**Issue by superDuperCyberTechno** [hyprwm/Hyprland#5353]
### Description

Hi, I'd like to propose an alternative way of handling workspaces.

It consists of 3 new functions:

1. Open new workspace: Opens the earliest empty workspace.
2. Go to next populated workspace: A function identical to `workspace, +1` with the caveat that it will not open empty workspaces.
3. Go to previous populated workspace: Exactly like above but with `workspace, -1`.

This opens up a very streamlined way of handling workspaces. It has a number of advantages:
1. It is extremely easy to quickly scan all populated workspaces.
2. Forgetting populated workspaces (potentially important work) becomes almost impossible.
3. Won't spread populated workspaces all over the place.
4. It can potentially untether the user from ever handling workspaces manually.
5. Will work well with the current manual implementation.

Somewhat unrelated bonus requests:
1. A complete overview of all populated workspaces.
2. A way to identify workspaces as you enter them (IE: its associated number is shown briefly in the corner).

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces

1) `empty`
2/3) `m+/-1`

bonus)
2) scriptable with ipc events, handle them with a custom layer or on your status bar for example

**Comment by superDuperCyberTechno** [comment]
Sorry for wasting your time. Awesome work.
