### ISSUE TITLE
AwesomeBump & Nifskope windows don't render 3D viewports properly on Hyprland

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#5356]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 25718754534d0ccd87b198b63459497e63887f35 dirty (format: fix format).
Date: Thu Mar 28 09:28:22 2024
Tag: v0.37.1-76-g25718754

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

![image](https://github.com/hyprwm/Hyprland/assets/5684325/fc78b59a-567d-4958-940d-a40ad339be05)

These programs are probably edge cases, but 2 is the beginning of a pattern. Both applications use Qt5. There are other weird rendering bugs in the programs (it has to do with UI updates i think, when i click menu buttons the ui doesn't update properly unless i press some specific other button or switch workspaces) but the failure to render the viewports is the most glaring issue.

### How to reproduce

Install awesomeBump or Nifskope and run them.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14816996/hyprland.log)

**Comment by MightyPlaza** [comment]
try `forcergbx` windowrule

**Comment by Rabcor** [comment]
> try `forcergbx` windowrule

Instead of being transparent, the viewports are now black, otherwise no change at all.

**Comment by MightyPlaza** [comment]
does it work on sway-git?

**Comment by Rabcor** [comment]
> does it work on sway-git?

I couldn't tell you, i don't know how to operate sway unfortunately.

**Comment by vaxerski** [comment]
then I'll say it's an issue with the app itself.

**Comment by Rabcor** [comment]
> then I'll say it's an issue with the app itself.

i've revisited this, the renderer being transparent is also an issue on sway for both applications., but there was a ui issue in nifskope that was only present on hyprland where after pressing some buttons you'd have to change back and forth between tabs for the ui to properly update.
