### ISSUE TITLE
SDL_SetRelativeMouseMode not capturing the mouse

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#536]
In SDL, running `SDL_SetRelativeMouseMode(SDL_TRUE)` under the Wayland backend should hide the mouse cursor and lock it to that window, to be used in camera controls in games for example. In Hyprland, this function only hides the cursor, but it can still freely move out of the window and thus breaks games using it.

I have verified the function works as intended in Sway.

The function's source: https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandmouse.c#L541
https://github.com/libsdl-org/SDL/blob/bdaf9a92a661debd6b31d82421ffdfa202b8ae72/src/video/wayland/SDL_waylandevents.c#L2298

I can provide a test binary if helpful.

**Comment by vaxerski** [comment]
would be nice to provide a test bin.

**Comment by TheSunCat** [comment]
Sure thing!
I have written a [test program](https://github.com/hyprwm/Hyprland/files/9365811/SDLTest.zip) and a built binary, which I have checked achieves the intended behavior on Sway (mouse is captured) and not on Hyprland.
You can build the code with `gcc SDLTest.c -lSDL2` if you prefer.

**Comment by TheSunCat** [comment]
Can you reproduce this?

**Comment by vaxerski** [comment]
dunno, I will test this once im back home from holiday

**Comment by vaxerski** [comment]
fixed in 83e4006b16e79e747888c507243c37eefabe9790
