### ISSUE TITLE
Window resize couses hyprland to crash

### ISSUE THREAD

**Issue by laycookie** [hyprwm/Hyprland#5360]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.35.0  ().
Date: 2024-02-05
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.1.79
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 23 08:12:53 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240226.13aff9b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When resizing a window under the correct circumstances the hyprland stops responding which results in the crash in a couple of seconds.

### How to reproduce

Describing how to reproduce this bug is a headeck so I will just attach a video.
Some information that might be important:
Left monitor is running at 4k with a scaling factor of 1.5x meanwhile the monitor on the right runs QHD with the scaling factor of 1x.

https://github.com/hyprwm/Hyprland/assets/80195126/0d0257d1-3882-4230-8a45-5bdd6d03c247

**Comment by MightyPlaza** [comment]
2 months old version + NVIDIA + no crash report

**Comment by vaxerski** [comment]
ye it was fixed ages ago
