### ISSUE TITLE
Some workspace sometimes randomly stays as "background" when using a gesture / bind to change workspaces

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#5361]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e1e41e54480282d9bec9957d3c578eb87bc1f2f2 dirty (reenderer: Add 1 border damage to fix number rounding issues (5343)).
Date: Sun Mar 31 15:59:22 2024
Tag: v0.37.1-93-ge1e41e54

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.8.2-zen2-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Mar 2024 03:08:19 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Sometimes a glitched version of a workspace remains visible as "background" after switching

### How to reproduce

Partially switch to another workspace using gesture (so that 2 workspaces are shown at the same time), e.g 2->3

go to ws 1 using keybinds

Shit breaks (see images)

This doesn't only happen when using this specific combination of gestures/binds, but that's the most reliable way I've found to replicate the issue

### Crash reports, logs, images, videos

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/97163c9c-bb2b-4809-a8fc-4efa7be229db)
This is actually an empty workspace

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/e686e8fa-97e2-4c86-8a58-af43905c0596)
so is this

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/1fd3ae9d-fc70-4c78-837a-a455bf8e204d)
here I have a terminal open on top of the glitched background

https://github.com/hyprwm/Hyprland/assets/84153269/78bb0a97-547e-4404-950b-0a1c2d5e4fd5

**Comment by abihf** [comment]
I have 2 monitor setup got this bug on the second monitor when I switch workspace on monitor 1. #5367 fixes my issue
