### ISSUE TITLE
Microsoft Edge's tab navigation dialog display abnormal

### ISSUE THREAD

**Issue by vimac** [hyprwm/Hyprland#5368]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: slbarch.local
Release: 6.8.2-zen2-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:20 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])
	DeviceName: VGA compatible controller


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When using Edge's tab navigation function, which is triggered by `Ctrl + Alt + A`, the display of the navigation window is abnormal (it may trigger a redraw after a few seconds, or it may lose focus and disappear).

![20240401_113201](https://github.com/hyprwm/Hyprland/assets/2765123/6e9d2966-519a-4a11-aa12-c0e1d82a0cee)

(Sorry for it's a photo and not a screenshot, because this is really hard to capture)

I tried using `sleep 3 && hyprctl clients` to check its title and class, both are empty, then try to set a windowrule to the empty title and class, whether the float, fullscreen rule,  wont get it display the correctly:
`windowrulev2 = float, class:^$, title:^$`
or
`windowrulev2 = fullscreen, class:^$, title:^$`

### How to reproduce

1. open Microsoft Edge
2. open some tabs
3. press Ctrl + Alt + A

**Comment by vaxerski** [comment]
try launching it in native wayland?

**Comment by vimac** [comment]
It should already be, here is my `~/.config/microsoft-edge-stable-flags.conf`:

```ini
--enable-features=UseOzonePlatform
--ozone-platform=wayland
--enable-wayland-ime
```

Did I miss something or make a mistake?

**Comment by vaxerski** [comment]
no clue, use hyprctl clients and see if it's running in native wayland, lol

**Comment by vimac** [comment]
Here's the result of Edge in `hyprctl clients`
```
Window 5ecabd373060 -> New tab and 26 more pages - Personal - Microsoft​ Edge:
	mapped: 1
	hidden: 0
	at: 14,37
	size: 1663,1078
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: microsoft-edge
	title: New tab and 26 more pages - Personal - Microsoft​ Edge
	initialClass: microsoft-edge
	initialTitle: New tab - Personal - Microsoft​ Edge
	pid: 1662
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 1

```

**Comment by nothendev** [comment]
try making it float?

**Comment by vaxerski** [comment]
then it's ms edge not knowing how to behave on wayland. Closing
