### ISSUE TITLE
Cannot focus in certain applications

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#537]
The most notable one is `fcitx5-config-tool`.
even using `hyprland-rs` to force focus, it doesn't seem to be focused

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/185145206-347bd3bf-1e05-474d-befa-ad11105baad0.png)

Works perfectly fine to me.

**Comment by KyleUltimate** [comment]
Nvm, I had `windowrule=nofocus,fcitx` in config, thought that only correspond to the input method window. I thought the regex was exact match? anyway it's a config issue

**Comment by vaxerski** [comment]
It's a C++ regex. `fcitx` probably matches anything with the substring `fcitx` in it
