### ISSUE TITLE
Weird Bluetooth Bug Stops My Bluetooth From Working Sometime's    

### ISSUE THREAD

**Issue by gunther6000** [hyprwm/Hyprland#5378]
### Hyprland Version

Version 0.38.0

### Bug or Regression?

Bug

### Description

Everytime I Turn off And Turn on My Pc Then My Bluetooth Stops Working Then i
Have To Hard Reboot Get It Working Again Tryed Tracking it Down And I Thank The Bug  Has To Do With The btusb btintel Module's I Do not really know.  And My Bluetooth Adapter Is A Intel
WiFi And Bluetooth A200

### How to reproduce

Everytime I Turn off And Turn on My Pc stops's Working  And My Adapter is Intel Wifi Plus Bluetooth A200.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14829291/hyprland.log)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/14829304/hyprland.log)

**Comment by deviantsemicolon** [comment]
I don't think hyprland has anything to do with this. This seems like a bluetooth or a kernel thing. You should also provide logs and images.

**Comment by entailz** [comment]
Thats a kernel thing / firmware bug. Probably have to run this a few times:
`su -c modprobe -r btusb;sleep 2;modprobe btusb`

**Comment by tharrmeehan** [comment]
downgrade the linux kernel and the headers to 6.8.1.
