### ISSUE TITLE
Cannot resize below (20,20)

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#538]
whether using hyprctl or mouse resizing, can't get lower than 20,20

**Comment by vaxerski** [comment]
intentional design - why would you want to?

**Comment by KyleUltimate** [comment]
Cause there's an app that's unable to close(cassowary related weirdness), and the current way to make it partially disappear, is by moving the window outside of the monitor. If it's possible to resize the window to (1,1), it's effectively impossible to see without doing weird stuff

**Comment by vaxerski** [comment]
I think it's such an edge case that I will not justify throwing an entire safety system for accidental oopsies away just to account for this. You can move it outside the monitor, as you've mentioned, so this is not needed.
