### ISSUE TITLE
Mouse sesnsitivity cannot be change

### ISSUE THREAD

**Issue by geeflaxx** [hyprwm/Hyprland#5384]
### Hyprland Version

Hey community,

Hyprland is brilliant!

I have a small issue with my mouse. It is really fast. I tried to change the configuration

I changed the hyprland.conf to sensitivity -0,7 but nothing happend. 

### Bug or Regression?

Bug

### Description

I can't decrease the mouse sensitivity.

For the information of dmesg and hyperctl devices please watch below.

A part of my hyprland.conf

# Touchpad

98 device {

99 name = "SynPS/2 Synaptics TouchPad"

100 sensitivity = -0.7

101 natural_scroll = true

102 }

103

### How to reproduce

Just install hyprland :D

It is by default so fast. 

### Crash reports, logs, images, videos

There is a picture of all my devices and the hyperland.conf

![image](https://github.com/hyprwm/Hyprland/assets/21129138/fe772605-7ac1-4df8-aa0b-af4330194d9d)

**Comment by sungyoonc** [comment]
Can you show the `mice` section in `hyprctl devices`?

**Comment by vaxerski** [comment]
name shouldn't have quotes.
