### ISSUE TITLE
Fcitx5's IME popup is blurry when it's fractional scale support is enabled

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#5387]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit af3a61a4e437fe728ef69c2739cae79e5a6254c0 dirty (core: assert attempted UAFs in windowExists).
Date: Tue Apr 2 08:15:58 2024
Tag: v0.38.0-2-gaf3a61a4

flags: (if any)


System Information:
System name: Linux
Node name: arch-g14
Release: 6.8.2-arch2-1.1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 01 Apr 2024 07:04:53 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hy3 by outfoxxed ver 0.1
```
(I have https://github.com/hyprwm/Hyprland/pull/5383/commits/45b865bae0436922f2a176fee93cced1cdb841e7 applied locally)
</details>

### Bug or Regression?

Bug

### Description

When "Enable fractional scale under Wayland" is enabled in fcitx5 classicui settings, the popup is blurry under HiDPI.
By running fcitx5 under `WAYLAND_DEBUG=1` one can observe that the correct preferred scale was never sent.
This has originally been mentioned https://github.com/hyprwm/Hyprland/issues/2433#issuecomment-1830160578 but I always forget to create a dedicated issue...

### How to reproduce

1. Make sure "Enable fractional scale under Wayland" is clicked in the classicui section of `fcitx5-configtool`, or have `EnableFractionalScale=True` in `~/.config/fcitx5/conf/classicui.conf`.
2. Type some text with fcitx5 in apps that support text-input-v3.
3. Observe that the popup is blurry.

### Crash reports, logs, images, videos

`WAYLAND_DEBUG=1` logs for fcitx5: [test.log](https://github.com/hyprwm/Hyprland/files/14836621/test.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14837960/patch.txt)
try

**Comment by sungyoonc** [comment]
The patch works for me

**Comment by q234rty** [comment]
works for me as well :)
