### ISSUE TITLE
Monitor Cycling

### ISSUE THREAD

**Issue by djohnson1865** [hyprwm/Hyprland#540]
Though this can be somewhat hacked around, it would be nice to have a relative ID option for monitor selection in the configuration identical to how workspaces function. Seems like it would make the configuration feel a little more consistent between monitors and workspaces.

This way it would be fairly trivial to configure a single keybind for cycling through monitors, or in the case of two monitors, swapping between the two. 

Alternatively, if the direction for monitors cycled back around, such that going right on the right most monitor would go leftmost, it would make a similar setup also trivial. But that feels like it would break existing configurations and/or cause more unintended consequences.

**Comment by vaxerski** [comment]
done in 9a9ecc25db21c2797c691ee90624e81b3c1f897c

`+1` `-1` `-82173` `+8327634274` etc
