### ISSUE TITLE
Hyprland crashes swiping through workspaces and accidentally use more fingers while swiping

### ISSUE THREAD

**Issue by DiskyToy** [hyprwm/Hyprland#5400]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit bcba3951f45f11245d424274130eb3a0ac790d93 dirty (input: Only limit drag resizes (5164)).
Date: Tue Mar 19 17:03:31 2024
Tag: v0.37.1-22-gbcba3951

flags: (if any)


System Information:
System name: Linux
Node name: Kanto
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

I configured to be able to use 3 fingers to swipe through workspaces.
While swiping through workspaces, hyprland crashes if i accidentally touch the touchpad with a fourth finger.
For this crash to happen, at least 2 workspaces need to be open (otherwise i cannot swipe to the other)

### How to reproduce

1. Launch Hyprland
2. Open a Window (Workspace 1)
3. Open another workspace (Workspace 2)
4. Open any window on Workspace 2, so it doesnt disappear while switching to another workspace
5. swipe using 3 fingers from Workspace 2 to Workspace 1 (or vice versa)
6. While swiping, place a fourth finger on the touchpad

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14850816/hyprland.log)
[hyprlandCrashReport22910.txt](https://github.com/hyprwm/Hyprland/files/14850817/hyprlandCrashReport22910.txt)

**Comment by vaxerski** [comment]
update
