### ISSUE TITLE
Hyprland crashes when quitting some applications

### ISSUE THREAD

**Issue by Ciflire** [hyprwm/Hyprland#5402]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 347b83903474ab9e95fa9d4ba123f6f78ab38d40  ().
Date: 2024-04-03
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.8.2
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Mar 26 22:23:34 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c8) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240403.a1c35e4"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Hyprland crashes when quitting some applications, the ones i noted are:
- pavucontrol
- kitty
- alacritty
- konsole
- qterminal

### How to reproduce

Launch one of those applications
Quit it
Hyprland crashes

### Crash reports, logs, images, videos

[hyprlandCrashReport12059.txt](https://github.com/hyprwm/Hyprland/files/14852818/hyprlandCrashReport12059.txt)
[hyprlandCrashReport32720.txt](https://github.com/hyprwm/Hyprland/files/14852819/hyprlandCrashReport32720.txt)
[hyprlandCrashReport36745.txt](https://github.com/hyprwm/Hyprland/files/14852821/hyprlandCrashReport36745.txt)
[hyprlandCrashReport37779.txt](https://github.com/hyprwm/Hyprland/files/14852822/hyprlandCrashReport37779.txt)
[hyprlandCrashReport38997.txt](https://github.com/hyprwm/Hyprland/files/14852823/hyprlandCrashReport38997.txt)
[hyprlandCrashReport39920.txt](https://github.com/hyprwm/Hyprland/files/14852824/hyprlandCrashReport39920.txt)
[hyprlandCrashReport40811.txt](https://github.com/hyprwm/Hyprland/files/14852825/hyprlandCrashReport40811.txt)
[hyprlandCrashReport44946.txt](https://github.com/hyprwm/Hyprland/files/14852826/hyprlandCrashReport44946.txt)
[hyprlandCrashReport46613.txt](https://github.com/hyprwm/Hyprland/files/14852827/hyprlandCrashReport46613.txt)
[hyprlandCrashReport50730.txt](https://github.com/hyprwm/Hyprland/files/14852828/hyprlandCrashReport50730.txt)
[hyprlandCrashReport55567.txt](https://github.com/hyprwm/Hyprland/files/14852829/hyprlandCrashReport55567.txt)
[hyprlandCrashReport88251.txt](https://github.com/hyprwm/Hyprland/files/14852830/hyprlandCrashReport88251.txt)
[hyprlandCrashReport2862.txt](https://github.com/hyprwm/Hyprland/files/14852831/hyprlandCrashReport2862.txt)
[hyprlandCrashReport3861.txt](https://github.com/hyprwm/Hyprland/files/14852832/hyprlandCrashReport3861.txt)
[hyprlandCrashReport6553.txt](https://github.com/hyprwm/Hyprland/files/14852833/hyprlandCrashReport6553.txt)
[hyprlandCrashReport7098.txt](https://github.com/hyprwm/Hyprland/files/14852835/hyprlandCrashReport7098.txt)
I linked every last crash i have hoping you can find what you need here

**Comment by Cyanose** [comment]
Have the same issue on Arch 6.8.2, closing basically any app in any way (either killing with hyprctl dispatcher, typing `exit` in kitty, or simply closing chromium with cross button) crashes hyprland session

**Comment by Agent00Ming** [comment]
# first bad commit: [347b83903474ab9e95fa9d4ba123f6f78ab38d40] workspaces: add visible flag

**Comment by Agent00Ming** [comment]
Reverting that commit fixes this issue. The issue only happens if your mouse cursor ends up on an empty layer when you kill a window. Killing a floating window overlapping a tiled window works as expected.

**Comment by crumpetalpaca** [comment]
having the same issue.
shouldn't the issue be called 
"Hyprland crashes when _quitting_ some applications" or have I miss understood it?

**Comment by Ciflire** [comment]
> having the same issue. shouldn't the issue be called "Hyprland crashes when _quitting_ some applications" or have I miss understood it?

indeed...

**Comment by Mr-Ples** [comment]
+1. crash logs are empty for me

**Comment by GERJanB** [comment]
+1 For me i can kill any window aslong as it is floating. Killing a tiled Window while nothing else is open leads to a crash

**Comment by sandsq** [comment]
I am able to get crashes when quitting out of applications like others have mentioned, but it seems to be when a specific monitor is enabled, and also sometimes when enabling the monitor from a disabled state. I've stripped down my conf here: [hyprland.txt](https://github.com/hyprwm/Hyprland/files/14856629/hyprland.txt)

Line 145, when I replaced `monitor = DP-2, disabled` with `monitor = DP-2, 3840x2160@60, 2560x0, 1`, I got this crash log: [hyprlandCrashReport44509.txt](https://github.com/hyprwm/Hyprland/files/14856631/hyprlandCrashReport44509.txt), though this crash does not always happen.

It also seems to happen more on some arrangements on windows, (like one window taking half the screen and two more taking the remaining quarters), but gonna try to test that some more.

Also my `hyprctl monitors all`
```
Monitor DP-2 (ID 0):
        3840x2160@59.99700 at 2560x0
        description: Samsung Electric Company LS32A70 HCPR600939
        make: Samsung Electric Company
        model: LS32A70
        serial: HCPR600939
        active workspace: 7 (7)
        special workspace: 0 ()
        reserved: 0 0 0 0
        scale: 1.00
        transform: 0
        focused: no
        dpmsStatus: 1
        vrr: 0
        activelyTearing: false
        currentFormat: XRGB8888
        availableModes: 3840x2160@60.00Hz 3840x2160@30.00Hz 3840x2160@29.97Hz 2560x1440@59.95Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x800@59.81Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz

Monitor DP-3 (ID 1):
        2560x1440@143.99899 at 0x0
        description: Lenovo Group Limited G27q-20 U6332LMP
        make: Lenovo Group Limited
        model: G27q-20
        serial: U6332LMP
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 0 0 0
        scale: 1.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
        activelyTearing: false
        currentFormat: XRGB8888
        availableModes: 2560x1440@59.95Hz 2560x1440@164.85Hz 2560x1440@144.00Hz 2560x1440@120.00Hz 2560x1440@100.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1680x1050@59.95Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@119.99Hz 1024x768@99.97Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@119.97Hz 800x600@99.66Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz 640x480@59.93Hz

```

**Comment by vaxerski** [comment]
try now

**Comment by Agent00Ming** [comment]
seems to be fixed
```
Hyprland, built from branch main at commit 10146f5ec50caeae2d835f5f6296137e2ac6f243 dirty (core: fix some crash conditions around workspace ptrs in CWindow).
```

**Comment by vaxerski** [comment]
coolio
