### ISSUE TITLE
splash text cannot be deactivated

### ISSUE THREAD

**Issue by steven-omaha** [hyprwm/Hyprland#5403]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 3875679755014997776e091ff8903acfb311dd2f  (props: bump ver to 0.38.0).
Date: Mon Apr 1 18:30:37 2024
Tag: v0.38.0

flags: (if any)


System Information:
System name: Linux
Node name: sumatrae
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland always shows a splash text like "Take on me, take me on" at the very bottom. This cannot be deactivated by `misc.disable_splash_rendering` or `misc.disable_hyprland_logo`.

### How to reproduce

Start hyprland.

### Crash reports, logs, images, videos

![20240403_16h26m44s_grim](https://github.com/hyprwm/Hyprland/assets/35634100/f467e1bd-337e-4769-adbb-e7ede98a16d1)

Very faint because of background image, but it is there.

The code path is `CCompositor::CCompositor()`, which calls `setRandomSplash()` unconditionally, which in turn takes some string from `src/helpers/Splashes.hpp` and renders it. 

Please provide an option to turn it off. Thank you.

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/issues/4338

**Comment by steven-omaha** [comment]
Thanks!

**Comment by LesesTrickshon** [comment]
same problem
