### ISSUE TITLE
hyprctl - show window order for active workspace

### ISSUE THREAD

**Issue by 3333juul** [hyprwm/Hyprland#5407]
### Description

When I type hyprctl -j clients, the grouped windows are printed in the order reflecting their arrangement in the group:
 ```
  "grouped": ["0x5f2dfd0ae6f0", "0x5f2dfd17a240", "0x5f2dfd1b82a0", "0x5f2dfc2ba980", "0x5f2dfd0f4890"],
  ```
It would be nice to have this possibility for the entire workspace as well.
This would work by printing windows info in the order in which they are placed in the layout.

I think creating something like window index similar to this function in awesomewm https://awesomewm.org/doc/api/classes/client.html#awful.client.idx would be a good idea:

![image](https://github.com/hyprwm/Hyprland/assets/103893901/b8ccad84-fbb0-4dc5-83eb-bf89361ab5a6)

**Comment by vaxerski** [comment]
Can't be accomplished: tiled windows do not have any order.
