### ISSUE TITLE
i recently updated my system and hyperland shows me a bug

### ISSUE THREAD

**Issue by pouria-shamekhi** [hyprwm/Hyprland#5408]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

i recently updated my system and hyperland shows me a bug
![240403_22h32m13s_screenshot](https://github.com/hyprwm/Hyprland/assets/102816830/978d2131-34de-45c7-a476-f6a5009fdacf)

### How to reproduce

what should i do with it?

**Comment by vaxerski** [comment]
> what should i do with it?

read the wiki or release notes.
