### ISSUE TITLE
Add support for dimming windows

### ISSUE THREAD

**Issue by rharish101** [hyprwm/Hyprland#541]
Just like the [Decoration options](https://wiki.hyprland.org/Configuring/Basic-Config/#decoration) `active_opacity` and `inactive_opacity`, could you add `active_brightness` and `inactive_brightness`? For example, [picom](https://github.com/yshui/picom) (an X11 compositor) has the config option `inactive-dim` as a float from 0.0 to 1.0 to set the brightness for inactive windows.

**Comment by vaxerski** [comment]
why

**Comment by FlafyDev** [comment]
> why

I personally think this is a great way to visually show which window is currently active

**Comment by rharish101** [comment]
I use it to visualise which window has focus, like @FlafyDev said, instead of using borders or opacity.

**Comment by vaxerski** [comment]
added in 48eb2e0d6fd756ec181b722c526f13453fa9c123

`decoration:dim_inactive=bool`
`decoration:dim_strength=float`

animation leaf for transitions `fadeDim`
