### ISSUE TITLE
Flickering on an empty workspace

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#5411]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 10146f5ec50caeae2d835f5f6296137e2ac6f243 dirty (core: fix some crash conditions around workspace ptrs in CWindow).
Date: Wed Apr 3 21:42:38 2024
Tag: v0.38.0-18-g10146f5e

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.8.2-zen2-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Mar 2024 03:08:19 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

I can see some screen flickering, especially on the bottom left part of the screen of my laptop, when on an empty workspace (and when runnig `hyprctl systeminfo`, huh), which stops if I open something, or while I move my cursor.

### How to reproduce

Do nothing (doesn't depend on hyprpaper being there)

**Comment by alba4k** [comment]
https://youtu.be/mZWlTU4gz3o

Ignore the keyboard, that's normal and can only be seen by a camera (pwm). The monitor however is quite noticeable

**Comment by alba4k** [comment]
@vaxerski fixed the link. Sorry.

**Comment by vaxerski** [comment]
try disabling vrr

**Comment by alba4k** [comment]
It's hard to tell because my eyes are relatively tired at 1am, but I am fairly sure that disabling vfr removes the flickering.

**Comment by alba4k** [comment]
disabling vfr only removes the flickering while on the desktop, doing nothing. It's still there while running hyprctl stuff (tested with systeminfo)

**Comment by vaxerski** [comment]
that would suggest a driver bug

**Comment by alba4k** [comment]
No idea, but haven't been able to replicate that since
