### ISSUE TITLE
Prevent a window from taking focus or switching workspace

### ISSUE THREAD

**Issue by constantitus** [hyprwm/Hyprland#5412]
### Description

I'm trying to prevent a window, specifically Steam, from taking focus when it opens.
I've tried the following
```
windowrule = workspace 10, ^(steam)$
windowrule = noinitialfocus, ^(steam)$
windowrule = suppressevent activatefocus, ^(steam)$
```
Now it opens windows on workspace 10, but they still switch my view to workspace 10, which I don't want.
Can I force it to spawn silently without taking focus or switching workspace ?

If this is not possible, then it's a feature request.
Thanks

**Comment by MysticBytes786** [comment]
you can use windowrulev2

like
```
windowrulev2 = workspace 8 silent, class:^(.*discord)$
```

**Comment by constantitus** [comment]
> you can use windowrulev2
> 
> like
> 
> ```
> windowrulev2 = workspace 8 silent, class:^(.*discord)$
> ```

Thanks, that did the trick. I should have read the whole wiki page on Window Rules, the silent parameter was hidden in there
