### ISSUE TITLE
Tooltip from application on hidden special-window can be triggered.

### ISSUE THREAD

**Issue by n-buck** [hyprwm/Hyprland#5418]
### Hyprland Version

Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: manjaro-desktop
Release: 6.6.19-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:16:16 UTC 2024

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

plugins:

### Bug or Regression?

Bug

### Description

Tooltip from Teams-For-Linux (i.e. hovering over a teams-meeting) is displayed, even when it is on a hidden special workspace.
In this case, the mouse was on the Chrome-Browser:
![image](https://github.com/hyprwm/Hyprland/assets/27816720/1147289d-b47e-467e-bb34-8879a2665589)

### How to reproduce

Steps to reproduce:
* Open an application (for me Webstorm, not sure if related)
* Open a seccond window with 50/50 split
* Open Teams on a Special workspace
* Trigger the tooltip
* Move the mouse, so the tooltip disappears
* Hide the Special-window
* Hover over the position, a teams-tooltip would be
* The tooltip is displayed when it should not

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14862682/hyprland.log)

**Comment by vaxerski** [comment]
your version is extremely outdated

**Comment by n-buck** [comment]
Hello @vaxerski 
I have updated Hyprland to v0.40.0, the issue remains the same.

**Comment by vaxerski** [comment]
#4903 and I think there is also another one of a similar nature.
