### ISSUE TITLE
workspace_swipe does not check if workspace is already shown on another monitor

### ISSUE THREAD

**Issue by Narcha** [hyprwm/Hyprland#5424]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 3875679755014997776e091ff8903acfb311dd2f  (props: bump ver to 0.38.0).
Date: Mon Apr 1 18:30:37 2024
Tag: v0.38.0

flags: (if any)


System Information:
System name: Linux
Node name: [redacted]
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c3) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When using the touchpad swipe gesture to switch workspace, it is possible to open a workspace on multiple monitors simultaneously. This leads to visual bugs and crashes down the line.

### How to reproduce

- Use swipe gestures to navigate to a workspace currently shown on another monitor
- done

Example on how to provoke a crash:
- Open a window on workspace x
- Focus a second monitor, navigate to the same workspace x using swipe gestures (this should not be possible)
- Open another window (on workspace x, but having the second monitor focused)
- Crash

**Comment by vaxerski** [comment]
do you have `workspace_swipe_numbered` turned on perhaps?

**Comment by Narcha** [comment]
Yes, I do. Should have mentioned that

**Comment by vaxerski** [comment]
that's your problem. It's only suited for single-monitor scenarios (tbh idek why it is there even). disable it and use the `workspace_swipe_use_r` option.

**Comment by Narcha** [comment]
Thanks. This does fix the issue for me, but IMO this is still a bug worth adressing as it can cause crashes.
Personally, I'd just set `workspace_swipe_use_r` as the default, because this is how I intuitively expected the workspace swipe to work.

**Comment by vaxerski** [comment]
I would nuke numbered

**Comment by modestbadger1773** [comment]
Seeing this thread was a game changer for me.
