### ISSUE TITLE
Stutters in some games when V-Sync is OFF

### ISSUE THREAD

**Issue by lucascoelho07** [hyprwm/Hyprland#5425]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 3875679755014997776e091ff8903acfb311dd2f  (props: bump ver to 0.38.0).
Date: Mon Apr 1 18:30:37 2024
Tag: v0.38.0

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Oland PRO [Radeon R7 240/340 / Radeon 520] [1002:6613] (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Bug or Regression?

Bug

### Description

Some games have massive stutters when in-game V-Sync is turned off and the frame rate is not the same as the monitor's refresh rate
I have noticed this mainly on Hades or Quake 2 remaster
As soon as I turn on V-Sync or limit the frame rate the games go back to running smoothly
This maybe related to DXVK, since the stutters also go away when launching the game with PROTON_USE_WINED3D=1

### How to reproduce

Play Hades with the frame rate above or bellow monitor's refresh rate

**Comment by vaxerski** [comment]
I don't think this is a hyprland issue. You can try enabling tearing, though.

**Comment by lucascoelho07** [comment]
Works fine on Plasma Wayland and even Sway though
I tested it with and without tearing on Hyprland too
I've also used the default config to make sure it wasn't something on mine
Is there any more info I can provide?

**Comment by vaxerski** [comment]
not much. It's likely some weird interaction in your configuration. I have doubts this is related to any de facto wrongdoing of hyprland.

**Comment by lucascoelho07** [comment]
So, as someone who knows more about this stuff than me, could you kindly give me a light on how I could debug this? Like any logs I should check or places I could look out for worngness.

**Comment by vaxerski** [comment]
feel free. I don't have any pointers though, stutters are probably the app itself's fault and I don't know much about dxvk

Never seen such stuff either

**Comment by lucascoelho07** [comment]
I've tried running Hades on true Vulkan (not DXVK) and it solves the issue for that game, it used to crash when I tried to use Vulkan, don't know when or how it got fixed tho.
