### ISSUE TITLE
Closing a window in a different resolution monitor makes app in main monitor freeze its corner

### ISSUE THREAD

**Issue by BananaDest** [hyprwm/Hyprland#5429]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: banana
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I have three monitors, main one in 2560x1440@165 and two in 1920x1080@60. Sometimes, when I have an app on my main monitor and one in the second monitor, and I then close the app on the second monitor, the app on the first monitor will only work in a 1920x1080 space, and the rest of the resolution will freeze until I close the app. The bug is not consistant and I haven't been able to replicate it at will.

### How to reproduce

It only happens sometimes so I haven't been able to replicate it constantly but:
1- Have three monitors, main one in 2560x1440@165 and two in 1920x1080@60.
2- Open an app in main monitor and another in second monitor (mostly has happened with firefox on main monitor and webcord on either of the other ones, but has also happened with games on main monitor)
3- Close the app on the second monitor (I use the $MAIN_MOD + Q keybind).
4- Watch the bug on main monitor app where rest of the resolution freezes.
It may help to have a video or something like that playing on main monitor.

**Comment by 42Willow** [comment]
@BananaDest 

Can you replicate this bug consistently with the method described here? https://github.com/hyprwm/Hyprland/issues/5386#issuecomment-2151090407

**Comment by BananaDest** [comment]
@42Willow I ended up changing DEs some time after this so I can replicate it anymore, but that seems to be exactly the same issue I had.

**Comment by vaxerski** [comment]
closing as dupe then
