### ISSUE TITLE
Closing animations no longer working

### ISSUE THREAD

**Issue by shadeyg56** [hyprwm/Hyprland#5432]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0569b9c30099be32f5e0d3b56a050059b9e5a8c1  ().
Date: 2024-04-04
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.8.2
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Mar 26 22:23:34 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c2) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240403.7781caa"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

Since updating to the latest commit, any windows do not animate when being closed, they just disappear. Windows are still animated when being opened. 

Just in case it matters, here is my animation settings in my `hyprland.conf`
```
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    animation=windowsIn,1,6,md3_decel,slide
    animation=windowsOut,1,6,md3_decel,slide
    animation=windowsMove,1,6,md3_decel,slide
    animation=fade,1,10,md3_decel
    animation=workspaces,1,7,md3_decel,slide
    animation=specialWorkspace,1,8,md3_decel,slide
```

### How to reproduce

For me, it just happens when closing any window. I haven't seen many reports on this so I'm not sure if you have to do something in particular to get it to happen on your system. Somebody opened a thread on the Discord and about 5 people have confirmed that their closing animations are also not working

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/31134255/ab6cb23c-06ae-4d94-8818-e5061ddaf0cc

**Comment by eaxly** [comment]
Having the same issue on ArchLinux, Hyprland version v0.38.0-31-g0569b9c3 built from commit 0569b9c30099be32f5e0d3b56a050059b9e5a8c1 (same version as issuer)

**Comment by shadeyg56** [comment]
Just did a bisect. Looks like 10146f5ec50caeae2d835f5f6296137e2ac6f243 is the bad commit

**Comment by vaxerski** [comment]
the voices in my head RAAAAAAAAAAH
