### ISSUE TITLE
Non-english layout keypress doesn't register key-codes

### ISSUE THREAD

**Issue by RainbowRivey** [hyprwm/Hyprland#5436]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 7283dde8784ece1e5c0a47e9cbcc1696535ef098 dirty (screenShader: allow camel for screensize).
Date: Tue Mar 19 00:51:32 2024
Tag: v0.37.1-15-g7283dde8

flags: (if any)


System Information:
System name: Linux
Node name: r41nbow-t450
Release: 6.7.6-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 29 Feb 2024 19:08:31 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=garudalinux


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Pressing a key with non-english layout produces a character, but other parameters are empty (like `keyCode`, `code`, `which`). This causes different applications (read: games) being not able to register events properly, keypresses just do nothing.

It may be also useful to register keys properly to spare conversions of master layout to others.

### How to reproduce

1. Select a non-english layout, for example ua.
2. Open any keyboard-checker and watch keys not being registered.

### Crash reports, logs, images, videos

```json
{
 "key": "й",
 "keyCode": 0,
 "which": 0,
 "code": "",
 "location": 0,
 "altKey": false,
 "ctrlKey": false,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}
```
example event produced by pressing 'й'.

**Comment by RainbowRivey** [comment]
Not a Hypraland issue

**Comment by RainbowRivey** [comment]
Please delete.

**Comment by vaxerski** [comment]
cant, github doesnt let us. Your clown emoji will be immortalized forever

**Comment by RainbowRivey** [comment]
![](https://media1.tenor.com/m/k5aYvVGNM3cAAAAC/daeth-funi.gif)
