### ISSUE TITLE
wrapper script does not export environment variables anymore?

### ISSUE THREAD

**Issue by logexp1** [hyprwm/Hyprland#5440]
### Description

I've been using wrapper shell script to launch hyprland.  like

```
export EDITOR=
export PATH=
...
...
exec Hyprland
```

I prefer this way since there are some environment variables that I want some variables to store the result of commands.

It's been working fine, but since I upgraded hyprland version recently, it does not set any environment variables in lines above `exec Hyprland` 

Can you help me? Thanks!

**Comment by vaxerski** [comment]
I don't think that would be a Hyprland issue? we don't override any paths...

**Comment by logexp1** [comment]
As I upgrade hyprland, hyprland.desktop was replaced! maybe I should use envs.conf instead. Thanks!
