### ISSUE TITLE
Ghost workspaces appear when disabling a monitor

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#5443]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit baad44b4ca28d62fb9d86ed1f83650b6695b501d dirty (hyprpm: fix incorrect commits number parsing (5437)).
Date: Fri Apr 5 05:40:44 2024
Tag: v0.38.0-37-gbaad44b4, commits: 4370

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.8.2-zen2-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Mar 2024 03:08:19 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0


```

</details>

### Bug or Regression?

Bug

### Description

Hard to explain, but today hyprland seems to be crashing a lot. Seems to crash on hyprctl reload too.

Most weird than all, I have some weird phantom workspaces (since logging in), possibly related to my laptop screen being disabled (I guess it tried to place them on it? Whats weird is that those are ws4, and as of writing ws5 appeared)

This is from when I had both ws4 and ws5
```
workspace ID 3 (3) on monitor DP-7:
	monitorID: 2
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x5eee8c25fe50
	lastwindowtitle: Kitty

workspace ID 4 (4) on monitor DP-5:
	monitorID: 1
	windows: 0
	hasfullscreen: 0
	lastwindow: 0x0
	lastwindowtitle: 

workspace ID 2 (2) on monitor DP-5:
	monitorID: 1
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x5eee8c28d410
	lastwindowtitle: Issues · hyprwm/Hyprland – Mozilla Firefox

workspace ID 5 (5) on monitor ?:
	monitorID: null
	windows: 0
	hasfullscreen: 0
	lastwindow: 0x0
	lastwindowtitle: 
```

They appear in waybar, but I can't switch to them, and moving a window to those will crash Hyprland.

### How to reproduce

When already docked:
* Login
* Move window to ws4
-> I now have DP-5 DP-7, and ws4 appears as phantom workspace
* run `hyprctl reload`
* Hyprland crashed

When not:
* Login with only my laptop
* Connect to my two external monitors (connected to a docking station)
-> I now have eDP-1 DP-5 DP-7
* run `hyprctl reload`, which runs `hyprctl monitors | grep "DP-5\|DP-6" && hyprctl keyword monitor "eDP-1, disabled" || hyprctl keyword monitor "eDP-1, 1920x1200, 0x0, 1"` to disable my laptop's screen when docked
-> I now have DP-5 DP-7, and ws4 appears as phantom workspace
* run `hyprctl reload`
* Hyprland crashed

Probably related to the recent ws changes

### Crash reports, logs, images, videos

[hyprlandCrashReport52636.txt](https://github.com/hyprwm/Hyprland/files/14883379/hyprlandCrashReport52636.txt)
[hyprlandCrashReport51112.txt](https://github.com/hyprwm/Hyprland/files/14883381/hyprlandCrashReport51112.txt)
[hyprlandCrashReport49807.txt](https://github.com/hyprwm/Hyprland/files/14883382/hyprlandCrashReport49807.txt)
[hyprlandCrashReport14572.txt](https://github.com/hyprwm/Hyprland/files/14883383/hyprlandCrashReport14572.txt)
[hyprlandCrashReport13735.txt](https://github.com/hyprwm/Hyprland/files/14883384/hyprlandCrashReport13735.txt)
[hyprlandCrashReport6870.txt](https://github.com/hyprwm/Hyprland/files/14883385/hyprlandCrashReport6870.txt)
[hyprlandCrashReport3216.txt](https://github.com/hyprwm/Hyprland/files/14883386/hyprlandCrashReport3216.txt)
[hyprlandCrashReport1729.txt](https://github.com/hyprwm/Hyprland/files/14883387/hyprlandCrashReport1729.txt)

**Comment by vaxerski** [comment]
we here at hyprland believe that a day without a crash is a sad day

**Comment by alba4k** [comment]
we here at userland (pun absolutely intended) believe that a day with more than 5 crashes is also a sad day

**Comment by AngeloThys** [comment]
I have experienced something similar.

When I connected to my external monitor and disabled the laptop's screen, the only remaining monitor worked for a couple of minutes, then went black, worked for 2 more minutes and then resulted in a crash.

Crash message: Aborted (core dumped) any display, wayland-display='wayland-1' display=' :0' eset by peerland/hyprland Crash Report 831.txt

**Comment by vaxerski** [comment]
try now

**Comment by alba4k** [comment]
nope

```
Hyprland, built from branch main at commit f815a33f64e72c29fb87f9fed74ec4479dc434dc dirty (workspace: remove monitor and visible flags on inert).
Date: Fri Apr 5 17:57:49 2024
Tag: v0.38.0-41-gf815a33f, commits: 4374

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.8.2-zen2-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Mar 2024 03:08:19 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0
```

**Comment by vaxerski** [comment]
where crash report

**Comment by vaxerski** [comment]
try

**Comment by vaxerski** [comment]
094bce811831675b03939e4a2d527998850c906d might also help

**Comment by alba4k** [comment]
Not sure which one of the two that was, but it seems fixed now, thanks

Btw, completely off topic, but would it be possible for hyprpm to only build enabled plugins (or build them when enabled if not already built, and if there are updates to them)? It's annoying how long it takes

**Comment by alba4k** [comment]
Before I close this - I currently have 2 workspaces open (ws2 on my left screen, ws3 on the right). Why do I find myself on ws4 (on the left screen) when running `hyprctl reload` while on ws2? 😅

**Comment by vaxerski** [comment]
> Before I close this - I currently have 2 workspaces open (ws2 on my left screen, ws3 on the right). Why do I find myself on ws4 (on the left screen) when running hyprctl reload while on ws2? 😅

good question. No clue.
