### ISSUE TITLE
Hyprland crash with Kicad into a group

### ISSUE THREAD

**Issue by Hyderman** [hyprwm/Hyprland#5448]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit dab149e4a6291dd412b594c0faba2c44f9a74263 dirty (core: fix compile without pch).
Date: Fri Apr 5 22:23:28 2024
Tag: v0.38.0-46-gdab149e4, commits: 4379

flags: (if any)


System Information:
System name: Linux
Node name: archDesktopHyderman
Release: 6.6.24-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 03 Apr 2024 14:50:23 +0000


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c1) (prog-if 00 [VGA controller])
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Here again with my beloved Kicad.

When trying to open the window to edit with the symbol editor while I have Kicad in an active group, Hyprland crash.
It doesnt crash if I create the group afterwards and then move the window into it.

### How to reproduce

Launch Kicad, togglegroup, open schematic editor with a symbol, edit symbol with the editor.

### Crash reports, logs, images, videos

[hyprlandCrashReport29527.txt](https://github.com/hyprwm/Hyprland/files/14891276/hyprlandCrashReport29527.txt)

**Comment by vaxerski** [comment]
hm. Can you try to get an ASan trace? https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by Hyderman** [comment]
[asan.log.3337.zip](https://github.com/hyprwm/Hyprland/files/14891837/asan.log.3337.zip)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14891863/patch.txt)
thanks! try this.

**Comment by Hyderman** [comment]
mmm, sry I suck with git:
```
❯ git apply ../patch.txt
warning: unable to rmdir 'subprojects/wlroots': Directory not empty
❯ git reset --hard HEAD
HEAD is now at dab149e4 core: fix compile without pch
❯ git apply ../patch.txt
warning: unable to rmdir 'subprojects/wlroots': Directory not empty
❯ rm -rf subprojects/wlroots
❯ git apply ../patch.txt
error: patch failed: src/desktop/Constraint.cpp:3
error: src/desktop/Constraint.cpp: patch does not apply
error: subprojects/wlroots: No such file or directory
❯ mkdir subprojects/wlroots
❯ git apply ../patch.txt
error: patch failed: src/desktop/Constraint.cpp:3
error: src/desktop/Constraint.cpp: patch does not apply
```

**Comment by imxyy1soope1** [comment]
```
❯ git apply ../patch.txt
warning: unable to rmdir 'subprojects/wlroots': Directory not empty
```

just ignore this

**Comment by Hyderman** [comment]
Thx.
Always crash:
[asan.log.3351.zip](https://github.com/hyprwm/Hyprland/files/14891945/asan.log.3351.zip)

**Comment by vaxerski** [comment]
git apply will revert if anything fails IIRC. Looks like the patch didnt apply. Use `patch -p1 < /path/to/patch.txt || echo ""`

**Comment by Hyderman** [comment]
Always crash but idk if the patch worked
```
❯ patch -p1 < ../patch.txt || echo ""
patching file src/desktop/Constraint.cpp
File subprojects/wlroots is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file subprojects/wlroots.rej
```
[wlroots.rej.zip](https://github.com/hyprwm/Hyprland/files/14893947/wlroots.rej.zip)
[asan.log.39618.zip](https://github.com/hyprwm/Hyprland/files/14893949/asan.log.39618.zip)

**Comment by vaxerski** [comment]
I somehow fail to believe this ASan trace is possible with the patch. I'll commit it to main.

**Comment by vaxerski** [comment]
oh, I know what's happening. `make asan` does a `git reset`, lol.

**Comment by Hyderman** [comment]
Thx, everything works fine with the commit.
