### ISSUE TITLE
Hyprland is not working, it issues a session error in light dm

### ISSUE THREAD

**Issue by rus100lan** [hyprwm/Hyprland#5454]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

I install arch linux via archisntall, choose how dekstop hyprland is downloaded, everything goes fine, select a profile, enter a password and issue a session error, while I also tried with fedora workstation, but there is also an error only there I get a profile selection. if possible, write what to do in Russian. worked in virtualbox

### How to reproduce

just installed hyprland in arch linux using archinstall in virtualbox

**Comment by vaxerski** [comment]
> just installed hyprland in arch linux using archinstall in virtualbox

https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm

VMs are not officially supported
