### ISSUE TITLE
Huge Framedrop with animations on Intel iGPU

### ISSUE THREAD

**Issue by joelmathewthomas** [hyprwm/Hyprland#5456]
should be fixed with 159444c45b6fa87d250cf694233ce0213a4585bd and f8c22916ab369e13f027b717fa1e505337ec8fd4

I'll backport them and make 38.1 probably.

_Originally posted by @vaxerski in https://github.com/hyprwm/Hyprland/issues/5426#issuecomment-2041096016_

I'm sorry for opening a new issue, coz i feel like something has been left unaddressed . The latest commit definitely fixed the issue of frame rate getting stuck at half .

But it still didn't solve the issue of huge frame drops with very small animations.
Like I mentioned earlier, i don't seem to have this issue on a AMD iGPU Laptop.
            

https://github.com/hyprwm/Hyprland/assets/90510078/87b8c380-a92a-4f14-926e-b3ba73f5a239

**Comment by vaxerski** [comment]
this is normal. That's how iGPUs work. You can force it to high clocks manually to get better fps. It's probably in power-save mode.

**Comment by joelmathewthomas** [comment]
If you don't mind can you tell me how

**Comment by MightyPlaza** [comment]
https://wiki.archlinux.org/title/AMDGPU#Power_profiles

**Comment by joelmathewthomas** [comment]
Thank you @vaxerski and @MightyPlaza for your help. I solved it by locking `intel_gpu_frequency` to max.
