### ISSUE TITLE
Does binde not work?

### ISSUE THREAD

**Issue by euuurgh** [hyprwm/Hyprland#5459]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit f7a34534873bf499fc1a04a5fa25ada03c4ee415 dirty (socket2: move to the wayland event loop).
Date: Mon Feb 26 18:20:51 2024
Tag: v0.35.0-103-gf7a34534

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.2-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I posted on reddit two days ago here: https://www.reddit.com/r/hyprland/comments/1bvupyu/binde_not_working/
but could not get any answers, so I'll try my luck here.

I got the following keybinds: 

binde =, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%+
binde =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%-

but they do not work.
It does work when instead of binde I use bind, so It's not a issue with the command.

### How to reproduce

Bind any program using bindm

**Comment by MightyPlaza** [comment]
you're using old version and it works for me

**Comment by euuurgh** [comment]
That is good to know on the one hand, but on the other hand I literally have no idea how to conveniently install and update hyprland now. I am using the latest version of the arch repos (0.38.0-1), and the aur build is even older (0.35)

**Comment by gksudolol** [comment]
> and the aur build is even older (0.35)

That's not how AUR -git builds work. They'll always pull from the latest commit regardless of the AUR version

**Comment by MightyPlaza** [comment]
> That is good to know on the one hand, but on the other hand I literally have no idea how to conveniently install and update hyprland now. I am using the latest version of the arch repos (0.38.0-1), and the aur build is even older (0.35)

from what you sent
```
Hyprland, built from branch main at commit f7a34534873bf499fc1a04a5fa25ada03c4ee415 dirty (socket2: move to the wayland event loop).
Date: Mon Feb 26 18:20:51 2024
Tag: v0.35.0-103-gf7a34534
```
so you're not using latest version

**Comment by euuurgh** [comment]
Built from source, and it works now. Thx
