### ISSUE TITLE
Can't toggle keyboard layout

### ISSUE THREAD

**Issue by thomascft** [hyprwm/Hyprland#546]
In my old `.xinitrc` I had this line: `setxkbmap -model pc105 -layout us,us -variant ,colemak -option grp:ctrls_toggle,shift:both_capslock,caps:backspace`

The important part is this `setxkbmap -layout us,us -variant ,colemak -option grp:ctrls_toggle`. Is it possible to switch layouts like this in hyprland? Because setting multiple variants fails

**Comment by vaxerski** [comment]
yus, why not use the adequate settings in the `input` section?

**Comment by thomascft** [comment]
Will that let me switch between QWERTY and COLEMAK?

**Comment by vaxerski** [comment]
I am not the oracle, why don't you try it and see?

**Comment by thomascft** [comment]
I'll give it a shot.

**Comment by thomascft** [comment]
Nah, unless I'm doing something wrong this doesn't seem to work.
```
input {
    kb_layout=us,us
    kb_variant=qwerty,colemak
    kb_model=pc105
    kb_options=shift:both_capslock,caps:backspace,grp:ctrls_toggle
    kb_rules=
	numlock_by_default=1
    follow_mouse=1
}

**Comment by vaxerski** [comment]
maybe try it with hyprctl? also check #363, i think related

**Comment by Wumianzhe** [comment]
does grp:ctrls_toggle normally toggle variants? I only ever used switching layouts, both of which are us here. If nothing else works, you can make a script polling hyprctl for variant and switching when required.

I made something similar for layout before
```
#!/usr/bin/env bash

if hyprctl devices | grep -q "Russian"
then
    hyprctl keyword input:kb_layout us
else
    hyprctl keyword input:kb_layout ru
fi
```

**Comment by vaxerski** [comment]
adding to above, if both are `us`, you can e.g. `echo "workman" > /tmp/.kblayout`. `/tmp/` is tmpfs and in ram, so it's pretty fast and doesn't bother the actual SSD.

**Comment by thomascft** [comment]
So... I can change the layout with hyprctl but not the variant

**Comment by vaxerski** [comment]
`hypctl --batch "keyword input:kb_layout us ; keyword input:kb_variant workman"`?

**Comment by thomascft** [comment]
Didn't work :(

**Comment by thomascft** [comment]
[ERR] Committing TextInput on no IME!

**Comment by vaxerski** [comment]
the IME warn is irrelevant.

Weird, works for me.

**Comment by MarcPartensky** [comment]
worked for me too

**Comment by vaxerski** [comment]
There is a minor issue with it I noticed though, will look into

**Comment by vaxerski** [comment]
with the recent per-device fixes, i was able to correctly and permanently switch between variants with `hyprctl` by making an entry for my keyboard:

```
device:ROYUAN Akko Multi-modes Keyboard-B {
    kb_layout=pl
}
```

and switching with hyprctl:

```
hyprctl --batch "keyword device:royuan-akko-multi-modes-keyboard-b:kb_layout us ; keyword device:royuan-akko-multi-modes-keyboard-b:kb_variant workman"
```

be advised this functionality was added like 10 minutes ago, so please recompile :-)

**Comment by thomascft** [comment]
I can confirm it's working great!

**Comment by thomascft** [comment]
Apparently my config file's symlink to the one in my dotfiles folder was replaced and the changes I made to the input section actually worked upon restoration. Here's the working config:
```
input {
    kb_layout=us,us
    kb_variant=,colemak
    kb_model=pc105
    kb_options=shift:both_capslock,caps:backspace,grp:ctrls_toggle
    kb_rules=
}
```
