### ISSUE TITLE
Dispatch 'Pin' + Maintain Focus/Active Client on Pinned App

### ISSUE THREAD

**Issue by nine7nine** [hyprwm/Hyprland#5460]
### Description

I've written a Widget for AGS to improve Hyprland usability on my 2-in-1 tablet, as I am sure you are aware using a keyboard-centric tiling WM comes with unique changes, when not using a keyboard ;-)

my widget is a dock that uses hyprctl dispatch && keyword to handle some basic window management stuff. (eg: swapnext, movewindow, workspace, exec, and so on). It all works reasonably well - but I have this one annoying issue when working with `hyprctl dispatch pin`... 

Specifically, I want to be able to pin a floating window and move it between workspaces -- this works, however; when the pinned app is moved to a workspace that has existing clients -- it looses focus, which causes me to have to click on the pin window again, before i can un-float it and drop it into the new workspace.

It would be nice if dispatch pin had an option to keep focus on the active window, until it's un-floated. maybe something like:

```
hyprctl dispatch pin activefocus
```

I've added a video to show what I mean. In the video I do the following:

1. float window
2. pin window
3. move to new (empty) workspace (it stays focused)
4. move it back to previous workspace (it loses focus, due to other clients)
5. I grab focus again (because below/existing window in workspace currently has it)
6. I un-float the window

https://github.com/hyprwm/Hyprland/assets/20159346/6e4e0f46-6d34-4d79-aeb5-128096eee7c9

Obviously, this isn't the end of the world - but it is somewhat annoying, and it seems like having an option for pin to 'activefocus' to maintain focus on the pin window would be a big usability improvement.

**Comment by nine7nine** [comment]
@luravoid - Interesting, I haven't actually messed ith Hyprland's IPC. 

I tend to agree though: having an official implementation would be ideal.

this seems like something dispatch pin should do OOTB.

**Comment by MightyPlaza** [comment]
imo pinned windows with focus shouldn't lose it on workspace change

**Comment by nine7nine** [comment]
@MightyPlaza  - I tend to aggee, but who knows - maybe some usage of it dictates it shoudn't be enforced explciitly that way by default? idk.

the funny thing: even if you keep your cursor on top of the pinned client and switch workspaces -- it still loses focus for a split-second... 

Regardless, in the case of a touch device: you can't help but the cursor/pointer being elsewhere though. That's part of the reason I think there should be an option to keep focus on the pinned window.... TBH, I suspect even if i used a mouse (which i don't) it's something i would want too.

**Comment by nine7nine** [comment]
@MightyPlaza - I just tested your PR above -- it works perfectly!

**Comment by nine7nine** [comment]
Closing. Fixed as of commit: df1a3a978d61b976542beaadc7c0ab8468ddb5d0
