### ISSUE TITLE
Blur effect does not work on rotated screens (WL_OUTPUT_TRANSFORM)

### ISSUE THREAD

**Issue by prali3** [hyprwm/Hyprland#547]
# Environment :

Distribution : Arch
wlroots : compiled with aur package wlroots-git the 19/08/2022
Hyprland : compiled with aur package hyptland-git the 19/08/2022
blur configuration:
`blur=true`
`blur_size=4`
`blur_passes=3`
`blur_ignore_opacity=false`
`blur_new_optimizations=true`
screen configuration:
`monitor=HDMI-A-2,preferred,0x0,1`
`monitor=HDMI-A-3,preferred,1080x230,1`
`monitor=HDMI-A-2,transform,1`

# What is the issue :

When I tried to rotate a screen by apply the parameter `monitor=NAME,transform,TRANSFORM` to a screen with TRANSFORM not equal to 0 the blur effect is not applied on the windows of this screen but the windows of screen that not rotated keeps the blur effect, the transparency and other effects/animations work regardless of orientation.

I have not found any application where the bug does not appear

# How to reproduce :

Configure a screen as described in the doc then add `monitor=NAME,transform,1` where NAME is the monitor  after the screen configuration in the config file and open an application that should display blur like terminal with transparency.

# What I tried :

I tried to change the `blur_ignore_opacity` and `blur_new_optimizations` variables in decoration, regardless what value I assign to these variables the bug persists.

I also tried to change the screen that is rotated but it doesn't change anything it is always be the screens that are rotated that will be affected by this bug regardless of number of flipped screen.

I tried to change the value of TRANSFORM but it does not change anything

# Screenshot

Screen without rotation
![swappy-20220819_021216](https://user-images.githubusercontent.com/111543876/185519818-2a380faf-82d2-44a6-8129-3facfcd143e1.png)

Screen with rotation (monitor=HDMI-A-2,transform,1) the artifact is from screenshot tool
![swappy-20220819_021232](https://user-images.githubusercontent.com/111543876/185520406-5d9188c0-abe9-428f-a765-0dc85f93cd5b.png)

**Comment by vaxerski** [comment]
yes, it's disabled on purpose, as it breaks completely.

**Comment by prali3** [comment]
This should be easily solved or it is a longer problem to fix.

**Comment by vaxerski** [comment]
no clue, probably an easy fix but idk what part is wrong, so it might take a while. Also I'm on holiday atm, can't testo

**Comment by vaxerski** [comment]
fixed in 6afab12b91baddb6d4a9c348e3fb2bf8c4e6e6ea
