### ISSUE TITLE
hyprland crashing every couple of minutes with an nvidia gpu (3060ti)

### ISSUE THREAD

**Issue by Octem** [hyprwm/Hyprland#5483]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: deimos
Release: 6.8.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti Lite Hash Rate] [10de:2489] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I've been using hyprland for a day with an Nvidia GPU (3060ti) and the nouveau drivers. It seems like every time I open spotify (or some time after opening spotify-launcher) hyprland crashes and takes me to sddm. 

It seems to be related to spotify, but could also be related to the notifications spotify sends (i'm using mako for notifications, could be related?)

 

### How to reproduce

- nvidia gpu (3060ti)
- nouveau turing drivers
- open spotify-launcher and play music (?)
- hyprland should crash after a bit

### Crash reports, logs, images, videos

[hyprlandCrashReport675.txt](https://github.com/hyprwm/Hyprland/files/14898114/hyprlandCrashReport675.txt)
[hyprlandCrashReport1604.txt](https://github.com/hyprwm/Hyprland/files/14898115/hyprlandCrashReport1604.txt)
[hyprlandCrashReport3565.txt](https://github.com/hyprwm/Hyprland/files/14898116/hyprlandCrashReport3565.txt)

**Comment by vaxerski** [comment]
dasa driber isue :(

**Comment by Octem** [comment]
@vaxerski thanks for the confirmation and quick response. would changing to proprietary drivers help in any capacity?

**Comment by vaxerski** [comment]
the only thing I know for sure that would help is changing to ayymd
