### ISSUE TITLE
workspace rule selector like window counts, but for 'containers'

### ISSUE THREAD

**Issue by zakk4223** [hyprwm/Hyprland#5488]
### Description

Some way to have the functionality of say, w[t2] but only count the number of 'containers' that are visible in the workspace. I guess just counting groups as a single window would work?

**Comment by vaxerski** [comment]
there is no concept of a container in hl tho?

**Comment by zakk4223** [comment]
Yeah I know. but groups are kinda containers. Anyways, that MR does exactly what I mean
