### ISSUE TITLE
Add window{open/close/move} IPC events

### ISSUE THREAD

**Issue by xDarksome** [hyprwm/Hyprland#549]
I am making a custom status bar using the `eww` framework. And I need to know when windows open, close and move between workspaces.

Open/close is pretty straightforward. I tried to emit IPC events in `Events::listener_mapWindow`/`Events::listener_unmapWindow` and it worked fine. 

Move, on the other hand, is tricky, because `CWindow.m_iWorkspaceID` is public and is being changed all over the place. There are at least 3 places where I need to emit the "move" IPC event:
1. Move window via keybind
2. Drag window and switch workspace
3. Pick window, switch workspace and drop it (without mouse movement)

I suggest hiding `CWindow.m_iWorkspaceID` behind getter/setter. Then it will be possible to emit the event just in the setter.

Would you be willing to merge that?

**Comment by vaxerski** [comment]
don't hide it - instead make a method (either in CWindow or CCompositor) like `moveToWorkspace` and do it there.

Yes, I would be willing to merge that, provided it's coded well, so please don't write ass code.

**Comment by xDarksome** [comment]
@vaxerski OK, here are the events

```
openwindow>>{address},{workspace_name},{class},{title}

closewindow>>{address}

movewindow>>{address},{workspace_name}
```

Any objections/suggestions?

**Comment by vaxerski** [comment]
lgtm. I commend you for not being an idiot and properly making the title last.
