### ISSUE TITLE
Replace pkg-config with pkgconf in hyprpm (and anywhere else if relevant)

### ISSUE THREAD

**Issue by blacklightpy** [hyprwm/Hyprland#5496]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: void
Release: 6.6.21_1
Version: #1 SMP PREEMPT_DYNAMIC Fri Mar  8 01:01:43 UTC 2024


GPU information:


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

As I mentioned in #5480, my Hyprland install was getting the missing header error, and updating did no help.

I tried debugging it for a while, and found out that the problem was getting `HEADERS_MISSING` after doing `headersValid()`

I figured out that the problems was in the line:
```cpp
std::string cmd     = std::format("PKG_CONFIG_PATH=\"{}/share/pkgconfig\" pkg-config --cflags --keep-system-cflags hyprland", DataState::getHeadersPath());
```

The problem was that `--keep-system-cflags` was not recognized by `pkg-config`, but it was by `pkgconf`. [`pkgconf`](https://github.com/pkgconf/pkgconf) is an active fork (last updated 2 weeks ago) of Freedesktop's [`pkg-config`](https://gitlab.freedesktop.org/pkg-config/pkg-config) (last updated 3 years ago). Arch Linux, FreeBSD, NetBSD, Fedora, Mageia and OpenSUSE had [moved to](https://lists.archlinux.org/pipermail/arch-dev-public/2018-May/029252.html) `pkgconf` by 2018, as a replacement for `pkg-config`.

`PKG_CONFIG_PATH="/home/user/.local/share/hyprpm/headersRoot/share/pkgconfig" pkgconf --cflags --keep-system-cflags hyprland` returned the three `-I/path`s.

Without recompiling, I solved the problem by symlinking `pkgconf` in place of `pkg-config`.

This could be problematic for me as Void Linux did try to make the replacement, but it's not bug compatible (as per https://github.com/void-linux/void-packages/issues/3391#issuecomment-466848064), so they didn't want to deal with the trouble of removing it. In Void Linux, `pkgconf` does not replace `pkg-config`, while other systems do that.

But for Hyprland, `pkgconf` works very well. Consider moving to `pkgconf`. It is the new standard.

### How to reproduce

`hyprpm add <repo>` or `hyprpm update`.

**Comment by kcoderhtml** [comment]
@blacklightpy can this be closed now?

**Comment by blacklightpy** [comment]
@kcoderhtml I haven't tested it, but I think yes.
