### ISSUE TITLE
Bad behavior

### ISSUE THREAD

**Issue by TAforever** [hyprwm/Hyprland#550]
Hello! I already wrote about this problem on Reddit, but it seems that you did not understand me. I completely disabled the focus from the mouse cursor, but still it is not the window that is in the focus frame that is divided, but the one over which the mouse cursor is located. I am attaching a video to make it clear.

https://user-images.githubusercontent.com/52626363/185692286-330dc946-509d-426a-a482-57be44d8108d.mp4

**Comment by vaxerski** [comment]
That's a dwindle design. I can add an option to change that.

**Comment by TAforever** [comment]
> That's a dwindle design. I can add an option to change that.

Yes, please fix this behavior. Sorry, I couldn't add the video.

**Comment by TAforever** [comment]
I would really like it to be like in BSPWM where the cursor captures the window when you explicitly move the mouse.
so that the follow_mouse=1 and force_split=2 settings work exactly like BSPWM or sway/i3 with autotiling script.

**Comment by vaxerski** [comment]
you can script that.

**Comment by TAforever** [comment]
> you can script that.

Yes, but it would be better if this behavior is "out of the box" because it is logical and this behavior is expected.

**Comment by vaxerski** [comment]
added in c2a3896cc9168a12f25a144dada6ecb94fb52b59

> Yes, but it would be better if this behavior is "out of the box" because it is logical and this behavior is expected.

imo it's the opposite - if you've configured dwindle to ALWAYS split down/right, it should do that.

**Comment by TAforever** [comment]
Thank you very much for your work, apparently you work 25 hours a day.

**Comment by TAforever** [comment]
Just tested, everything works fine, but after closing the window, the focus is transferred to the window over which the cursor is located, and not to the parent window. If you could fix this then it would be the icing on the cake.

**Comment by vaxerski** [comment]
I'll do that tomorrow, if I don't forget. I'm on holiday and it's 10:30PM

**Comment by TAforever** [comment]
Thanks a lot!

**Comment by TAforever** [comment]
And make the same behavior in the Master Layout, there, too, when the window is closed, the focus is not transferred to the parent, but to where the mouse cursor is.

**Comment by vaxerski** [comment]
fixed in 45a0e69286c5da38202542987f26c27916527093

**Comment by TAforever** [comment]
> fixed in [45a0e69](https://github.com/hyprwm/Hyprland/commit/45a0e69286c5da38202542987f26c27916527093)

Thank you so much, everything works great! Now I'm no longer sad that Baskerville doesn't port BSPWM to wayland. and btw before your commit yesterday, the force_split option was useless because whatever value was set, it still worked like force_split=0 i.e. the split follows the mouse.
