### ISSUE TITLE
animation ONOFF be boolean instead of number

### ISSUE THREAD

**Issue by LamprosPitsillos** [hyprwm/Hyprland#5500]
### Description

```hyprlang
animation = windows, 1, 2, myBezier, popin
                      ^---- why not have this be boolean so that it can be "on/off" etc
```
Really small feature request

**Comment by The-Briel-Deal** [comment]
Hey Lampros! Thanks for the feature request! I made a PR to fix it here https://github.com/hyprwm/Hyprland/pull/5659. I pretty much added "on", "off", "true", and "false" as options for this field.
