### ISSUE TITLE
Japanese regex for window rules

### ISSUE THREAD

**Issue by 31JSON** [hyprwm/Hyprland#5501]
I'm not sure if this is a bug, so I'm putting it in a blank issue.

Hyprland doesn't seem to act on window rules that have Japanese characters in the title or class. I used `hyprctl clients` to get the titles. For example, I have window rules for file operations (move/copy/etc) in Thunar.

`windowrulev2 = float,title:^(ファイル操作の進捗)$,title:^(すべてのファイルを展開中)$,title:^(ファイルが既に存在します)$`

Is there something else needed for Japanese characters to be interpreted correctly? All of my other rules work normally. I did not see anything in the wiki expressly dealing with this.

**Comment by vaxerski** [comment]
afaik this should just be unicode, idk

**Comment by 31JSON** [comment]
That's what I thought. Is there any way to monitor hyprctl as it implements the rules to debug this?

**Comment by vaxerski** [comment]
I don't think so. You can only see if it matched.

One thing worth noting is that you have 3 `title:` properties, each will overwrite the previous.

**Comment by 31JSON** [comment]
That was it. I split them into three separate rules, and it's working now. I was under the impression that they could be put together. I was trying to keep rules for the same application together for organization.
