### ISSUE TITLE
[hyprpm] Specify the commit id in the hyprpm update command

### ISSUE THREAD

**Issue by YoYomec** [hyprwm/Hyprland#5505]
### Description

I want to do something like :
`hyprpm update hyprland-plugins e45066d0741a1a4b9298a4c5ec43a5e57b059a4e`
instaid of removing and reinstalling hyprland-plugins with the wanted commit

> Or also, in my dreams :
> `hyprpm update --match-hyprland-version` (I don't think it's possible for this one but who knows...)

Thanks in advance

**Comment by vaxerski** [comment]
wdym?

**Comment by zakk4223** [comment]
I think they want the same thing as the add [rev] command, but for updating a plugin. So 'update to this revision'. 

The second thing and the fact they are adding and removing plugins to get a specific rev makes me think they are using a plugin with no commit pins and HEAD is broken on older hyprland versions.

OP, you should bother the plugin author to add commit pins. If you know the commits that work for a particular hyprland version also let them know that too. Or just PR their repo and add pins to their hyprpm.toml ;)

**Comment by YoYomec** [comment]
Ok, strange. I did this some time ago and it didn't work, but now, it works, like magic. And there was no commit on the plugin's repo since. Strange...
