### ISSUE TITLE
Some popups will be canceled when mouse point to other window in XWayland

### ISSUE THREAD

**Issue by dragove** [hyprwm/Hyprland#551]
Application: Jetbrains Pycharm
Step to reproduce:
1. set pycharm use experimental ui (in action select registry and toggle ide.experimental.ui on and restart pycharm)
2. select a configuration, and there will be options like run 'xxx' / debug 'xxx'
3. between the configurations and options there is a gap.
4. when mouse is moving to the gap, the focus will be lost and window disappears.

![image](https://user-images.githubusercontent.com/24190403/185730990-49b2d008-96b6-4cd5-b1db-38aa682ba79c.png)

**Comment by vaxerski** [comment]
Any app that doesnt require me to download 
![image](https://user-images.githubusercontent.com/43317083/186122038-146f8f68-aa1c-4ceb-a75e-1be97f6c0840.png)
?

**Comment by dragove** [comment]
Sorry for late reply. And yet, I haven't found another application has the same behavior.

**Comment by dragove** [comment]
I don't know which commit fix this problem. After I upgrade hyprland to 0.12, problem disappeared.

**Comment by vaxerski** [comment]
I am so fucking amazing that i fix problems not even knowing i fixed them
