### ISSUE TITLE
Heavy lag at random running times

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [hyprwm/Hyprland#5516]
### Hyprland Version

Hyprland, built from branch  at commit 942172d2dc9194b95d637283ec3338c06c9c6597  ().
Date: 2024-04-05
Tag: , commits: @COMMITS@

flags: (if any)

### Bug or Regression?

Bug

### Description

At random times hyprland clog up all VRAM and start wild lags of desktop, games and applications 

### How to reproduce

I don't know how to reproduce it. I'm just working and it starts lagging. On v0.34 I never had this problem before

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/54883747/030c6e62-926c-46fd-ab69-4788d9f85154)

**After rebooting and launching the same applications that were previously running:**
![image](https://github.com/hyprwm/Hyprland/assets/54883747/f4069ac6-dfe6-4f45-9117-eb8503dcc94b)

Video: https://youtu.be/D9sv19-Sllo

**Comment by tharrmeehan** [comment]
Maybe #5426 , have you tried the latest -git version?

**Comment by vaxerski** [comment]
yea as above

**Comment by IgnIVertiKalCaD** [comment]
Fixed in 0.38.1
