### ISSUE TITLE
Source files don't work

### ISSUE THREAD

**Issue by yenzzo** [hyprwm/Hyprland#5526]
### Hyprland Version

Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

### Bug or Regression?

Bug

### Description

I've tried to enable themes on hyprland and followed the steps for Catppuccin (_https://github.com/catppuccin/hyprland_) and Rose-Pine (_https://github.com/rose-pine/hyprland_), but none of them worked.

Seems to me that source filing isn't working, since i add it to hyprland.conf, reboot, and nothing changes. I searched through the internet and didn't find anyone with the same problem.

### How to reproduce

As said, just try to source a file and see if it works.

**Comment by gksudolol** [comment]
Sourcing the file alone doesn't do shit, you actually have to define the assign the colors

**Comment by gksudolol** [comment]
FWIW it's probably easier in the longrun to copy the values into `hyprland.conf`
