### ISSUE TITLE
Mixed Input Device Hotkeys (Part 2: Foot Edition)

### ISSUE THREAD

**Issue by JoshuaFern** [hyprwm/Hyprland#553]
When copying text in the terminal emulator Foot using two input devices my hotkeys are not mixing. I asked foot about this and they said it's definitely a compositor thing. I guess it does happen in other programs as well I just didn't notice.

See: https://codeberg.org/dnkl/foot/issues/1148
And also this similar issue I had: https://github.com/hyprwm/Hyprland/issues/335

**Comment by vaxerski** [comment]
part 2 electric boogaloo

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/186121407-9455be8a-5ff5-4a57-a95b-21f6318c016b.png)

can't reproduce...?

**Comment by JoshuaFern** [comment]
Just to be clear, it's about using both keyboards at the same time, and it's not just foot.

Here's an easier example, try just holding shift on one device and typing a letter on the other. Is it a capital? For me, it's not.

I've tested some additional keyboards just to make sure it's not specific to my device, I also asked someone else to try and they had the same issue.

**Comment by vaxerski** [comment]
check with 7a3b57c99c1501055512174f94840153f4e65c71

**Comment by JoshuaFern** [comment]
Thanks! Seems to be working now, I was able to paste into foot.
