### ISSUE TITLE
Stacking Mode

### ISSUE THREAD

**Issue by dacyberduck** [hyprwm/Hyprland#5531]
### Description

I know Hyprwm is a dynamic tiling wm, but any chance we can get a stacking mode like in hikari?
Basically what I am looking for is a Stacking (floating windows) layout with the ability to arrange the views in similar manner to a tiling layout with a single keystroke (keeping the window state as floating).

**Comment by vaxerski** [comment]
window groups?

**Comment by dacyberduck** [comment]
> window groups?

If I am correct window groups are similar to sway's tab groups, right? However I am looking for a layout that doesn't tile the windows when they spawn and the windows simply retain their previous size. Only difference from a complete stacking layout is the ability to organize the views like they are tiled on pressing a defined keystroke.

**Comment by vaxerski** [comment]
#2050
