### ISSUE TITLE
Info to add to Wiki about Flickering with Nvidia 

### ISSUE THREAD

**Issue by akunito** [hyprwm/Hyprland#5536]
### Hyprland Version

not related

### Bug or Regression?

Bug

### Description

Hi, 
I think this could be helpful, apologize in case this would not be the right way to issue it.

I'm using Nvidia RTX 4070 with propietary drivers

I have found that the 99% of the flickering is showing up when the apps are not open with wayland support but by xwayland. (Of course, once you have set the drivers correctly)

I think it would be very helpful to add this to the documentation. Most of the software can be open with ozone flags to support wayland, what is solving the annoying issue. Many people might be moving to Wayland thanks to Hyprland like was my case, and are not aware of this.

### How to reproduce

hyprctl clients | grep xwayland

Run the apps with 

For example in case of Vivaldi
`hyprctl dispatch exec [workspace 9 silent] ~/mySCRIPTS/wayland_app_starters/vivaldi.sh`

```
#!/bin/bash
vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland %U
```

In case of VsCode create ~/.config/code-flags.conf 
or in case of VsCodium ~/.config/codium-flags.conf
```
#!/bin/bash
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

**Comment by tharrmeehan** [comment]
I don't think Nvidia is officially supported by Hyprland, but maybe you can fork the wiki and add/suggest a pr?
https://github.com/hyprwm/hyprland-wiki/edit/main/pages/Nvidia/_index.md

**Comment by vaxerski** [comment]
this is not the hyprland-wiki repo. Plus, the information is there. If you find it not easily findable, though, feel free to mr.
