### ISSUE TITLE
Vim splits resize when switching windows in fullscreen mode

### ISSUE THREAD

**Issue by nade4tt** [hyprwm/Hyprland#5538]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 63e3668529f6c06478ec288723d0ba46374c4bc5 dirty (style: run clang-format). Date: Mon Apr 8 16:33:02 2024 Tag: v0.38.0-73-g63e36685, commits: 4406 flags: (if any) System Information: System name: Linux Node name: archlinux Release: 6.8.4-arch1-1 Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000 GPU information: 03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev ff) (prog-if 00 [VGA controller]) 12:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev ca) (prog-if 00 [VGA controller]) os-release: NAME="Arch Linux" PRETTY_NAME="Arch Linux" ID=arch BUILD_ID=rolling ANSI_COLOR="38;2;23;147;209" HOME_URL="https://archlinux.org/" DOCUMENTATION_URL="https://wiki.archlinux.org/" SUPPORT_URL="https://bbs.archlinux.org/" BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues" PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/" LOGO=archlinux-logo plugins:
```

</details>

### Bug or Regression?

Bug

### Description

https://github.com/hyprwm/Hyprland/assets/165161791/c93ceac8-3ed6-4975-888b-a653b6fe9b64

Switching between windows in fullscreen mode alters the size of splits in vim.

Terminal: Alacritty Version 0.13.2

### How to reproduce

Workflow:
- Open two terminals
- Open vim in one of the terminals and create two vertical splits (Ctrl-w + v)
- Switch to fulscreen mode (bind = SUPER, M, fullscreen, 1)
- Switch to the second window
- Switch back to the terminal with vim -> Size of the splits will be altered

**Comment by MightyPlaza** [comment]
does it happen on kitty or foot, for example?

**Comment by nade4tt** [comment]
@MightyPlaza Yes, I've managed to reproduce this issue with both kitty and foot

**Comment by vaxerski** [comment]
that's because once you shift fullscreen, the window is resized back to its tiled size.

P much #683
