### ISSUE TITLE
Comments now must start with a single `#` otherwise it will error

### ISSUE THREAD

**Issue by AyhamAl-Ali** [hyprwm/Hyprland#5543]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 558d1be7e3c9242b39fe78efe74ada1298112892 dirty (hyprpm: Improve Hyprpm Update Performance (5530)).
Date: Wed Apr 10 19:33:50 2024
Tag: v0.38.0-88-g558d1be7, commits: 4421

flags: (if any)


System Information:
System name: Linux
Node name: ayham
Release: 6.1.84-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Thu Apr  4 04:30:51 UTC 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

</details>

### Bug or Regression?

Bug

### Description

I updated my system and I am using hyprland-git and suddenly all my default configurations started giving me errors, it turned out that any comment line like `###################################### Plugins #########################################` printed an error, I suspected it was something with comment parsing so I tried making it `# ##################################### Plugins #########################################` and it worked!

### How to reproduce

Start a line in any config with 2+ hashtags `#` like `### test ###`

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/20037329/85a11cf4-0835-4c72-bbc9-71bd49b6794f)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/issues/4754
