### ISSUE TITLE
weird lines in transparent windows when changing background(in legacy render)

### ISSUE THREAD

**Issue by NotWinder** [hyprwm/Hyprland#5544]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 1343aa865d04d80313b0e674c28ecfdbeb90e876  ().
Date: 2024-04-09
Tag: , commits: @COMMITS@

flags: (if any)
legacyrenderer


System Information:
System name: Linux
Node name: winder
Release: 6.6.25
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu Apr  4 18:23:07 UTC 2024


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller [8086:2a42] (rev 07) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240408.4cba8b5"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

i have built hyprland with legacy render set to true (on nixos unstable)
and when i change the background (using swww)
these lines appear in transparent windows (like inactive windows and alacritty)

![1712806950-wayshot](https://github.com/hyprwm/Hyprland/assets/108935241/49dedb87-cd67-4aa8-9154-dd94501cdc7a)

### How to reproduce

build hyprland with legacy render set to true 
enable transparency for the apps (active or inactive)
change the background

**Comment by NotWinder** [comment]
no it dosen't happen when blur is disabled 
thanks for the quick response

i have a question though is this a problem in the legacy build or is it happening because my laptop is old and can't properly render blur?

**Comment by vaxerski** [comment]
could be either, we don't really test legacy_renderer

**Comment by NotWinder** [comment]
makes sense 
thanks
