### ISSUE TITLE
Waybar+IPC: After monitor disconnect the bar doesnt know what workspace is active

### ISSUE THREAD

**Issue by max-ishere** [hyprwm/Hyprland#5547]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.37.1  ().
Date: 2024-03-16
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: linux
Release: 6.6.23
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Mar 26 22:22:53 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240403.08b9151"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

https://github.com/Alexays/Waybar/issues/3121

After the monitor is disconnected the bar doesn't highlight the active workspace. Reconnecting the monitor doesn't notify the bar either.

### How to reproduce

# Steps to reproduce

1. Log into Hyprland
2. Attach 2 screens to a machine and make sure both are showing the desktop.
3. Start waybar with this config:

config.json
```json
[{
  "modules-left": [ "hyprland/workspaces" ],
  "hyprland/workspaces": { "move-to-monitor": true }
}]
```

style.css
```css
#workspaces button {
  padding: 0 0.5em;
  margin: 0 0.25em;
  border-radius: 3px;

  border: none;
}

#workspaces button.active {
  border: 3px solid red;
}
```
4. Focus the workspace on one of the monitors
5. Disable some other monitor (bind lid switch works too)
```shell
hyprctl keyword monitor 'eDP-1,preferred,0x0,1'
```

# Expected result

After the monitor is disabled the bar shows the selected workspace with a red outline.

# Actual result

No workspace is highlighted as active until a workspace is switched.

### Crash reports, logs, images, videos

After the monitor is disabled this is expected:
![image](https://github.com/hyprwm/Hyprland/assets/47008271/97ec7a8e-0ea1-4706-a9c2-aa1b79d07510)

Actual behavior until the ws is switched to a different one.
![image](https://github.com/hyprwm/Hyprland/assets/47008271/f397b95d-8689-4829-9ee2-ede2c0d14bd0)

**Comment by vaxerski** [comment]
that's a waybar problem
