### ISSUE TITLE
Virtual monitors (for wayvnc)

### ISSUE THREAD

**Issue by YoYomec** [hyprwm/Hyprland#5551]
### Description

I mean adding a virtual monitor meant to work with a vnc/rdp server

See [this post](https://superuser.com/questions/1434779/using-a-tablet-as-a-second-monitor-with-wayland)
It's already possible in Sway, but I didn't found the way to do this the hyprland wiki.
It would be cool, to use a tablet or something as another monitor.

**Comment by vaxerski** [comment]
read up on hyprctl output in the wiki
