### ISSUE TITLE
Animation glitches when interrupting other animations to move to empty worspace

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#5556]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 185a3b48814cc4a1afbf32a69792a6161c4038cd dirty (swipe: nuke numbered).
Date: Thu Apr 11 13:46:19 2024
Tag: v0.38.0-92-g185a3b48, commits: 4425

flags: (if any)


System Information:
System name: Linux
Node name: dell-xps
Release: 6.8.4-zen1-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 06 Apr 2024 23:01:55 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0


```

</details>

### Bug or Regression?

Regression

### Description

A weird animation plays when canceling a running ws switch animation (with a window on each workspace) to move to a third workspace, with no windows on it.

Check out the video

It looks like ws2 is still finishing the slide-right animation, but ws3 is already sliding left and pushing ws1 away.
So 3 workspaces appear to be visible at once

### How to reproduce

1. Have windows on ws1 and ws2
2. Have no windows on ws3
3. Go to ws2
4. Switch to ws1 with a keybind, then to ws3 before the animation finishes

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/84153269/9eb7f94a-10bc-422e-9ba4-465caf45ae68

**Comment by thejch** [comment]
doesn't seem like a "bug" to me. the animations take time to finish.

**Comment by alba4k** [comment]
yes but showing ws2->ws1 and ws1->ws3 at the same time makes animations feel less continuous. Less like two workspaces are sliding and more like it's just the windows

**Comment by alba4k** [comment]
Not sure, maybe I only noticed in the past two weeks. I noticed a couple of times tho, and never in the two years before that, idk

I guess this is just intended behavior then?

**Comment by alba4k** [comment]
Not sure, maybe I only noticed in the past two weeks. I noticed a couple of times tho, and never in the two years before that, idk

I guess this is just intended behavior then?

**Comment by vaxerski** [comment]
yea
