### ISSUE TITLE
Different horizontal and vertical gaps

### ISSUE THREAD

**Issue by Kommynct** [hyprwm/Hyprland#5568]
### Description

I have a special workspace, and the bottom and top gaps should be much smaller than the horizontal gaps since my (like most monitors) screen is widescreen

Is there a good way of doing that for only the special workspace?

I've seen the things about a negative reserved area, but that seems to apply to all workspaces.

**Comment by MightyPlaza** [comment]
workspace rules?

**Comment by Kommynct** [comment]
There isn't a workspace rule for negative reserved areas that I can see, and I'm already using a workspace rule for adding gaps to my special workspace, I just can't change the vertical and horizontal gaps.

**Comment by MightyPlaza** [comment]
wdym reserved area?
a few months ago that was the only solution for different gaps but now I'm pretty sure you can specify per corner values
(and maybe in workspace as well)

**Comment by Kommynct** [comment]
https://github.com/hyprwm/Hyprland/issues/148 I'm referring to this

I don't see that in the wiki, what's the syntax?

**Comment by MightyPlaza** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/123664421/c4939cfa-2c00-4f6f-8f23-5c4e6f67b2ee)

**Comment by zakk4223** [comment]
note the workspace rule gaps have a slightly different syntax. gapsin: 5 10 15 20  (spaces instead of commas).

Kinda annoying the syntax is different, but I get why it is.

**Comment by MightyPlaza** [comment]
related https://github.com/hyprwm/hyprlang/issues/9
