### ISSUE TITLE
Add More Monitor 'Auto' Positions

### ISSUE THREAD

**Issue by modestbadger1773** [hyprwm/Hyprland#5573]
### Description

Currently the `auto` position of a secondary monitor is 'Right' of the main monitor.

The solution to this is to place the monitor at the position you would like it to be in your config file. But, if you would always want the second monitor to be 'above' your main monitor, this can be annoying (as you will need to activate a new line for every time a monitor of new resolution is attached).

The suggested enhancement would be to add the following options available for monitor configuration:

`auto-up`: Automatically places the monitor at a position above the primary monitor.
`auto-left`: Automatically places the monitor at a position left of the primary monitor.
`auto-down`: Automatically places the monitor at a position below the primary monitor.
`auto-right` Automatically places the monitor at a position right of the primary monitor. (This is the current behaviour of `auto`).

I think `auto` should itself remain an option, to avoid breaking configs, even though it would be redundant with the existence of `auto-right`

----
An argument could be made that the option should exist for the 8 main directions `up`, `up-left`, `up-right`, `left`, `right`, `down`, `down-left`, & `down-right`. But just having the `auto-up` option would solve my use case, so /shrug.

**Comment by The-Briel-Deal** [comment]
Thanks for the feature request! Working on this now, should hopefully have a PR up by EOD.

**Comment by The-Briel-Deal** [comment]
PR Created https://github.com/hyprwm/Hyprland/pull/5670. I only implemented the 4 new directions as the other 4 directions suggested have a few problems in concept. I described the issue deeper in my PR description. Thanks again for the feature request!
