### ISSUE TITLE
Cannot disable automatic centering of floating windows when initially opened.

### ISSUE THREAD

**Issue by syslaz** [hyprwm/Hyprland#5576]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: workstation
Release: 6.8.5-gentoo-r1-x86_64
Version: #1 SMP PREEMPT_DYNAMIC Fri Apr 12 06:26:33 CDT 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3090] [10de:2204] (rev a1) (prog-if 00 [VGA controller])
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"
```

</details>

### Bug or Regression?

Bug

### Description

Adding a window rule to the Hyprland config file for floating windows works great. However, the compositor is centering the windows by default instead of positioning them based on the app's preference. I found the window rule for 'center' in the WIKI but it has no effect, its on by default and cannot be disabled. 

I'm experiencing issue this with KDE plasma's 'plasmashell' which I know isn't officially supported but seems to be working near perfectly with the exception of the window floating rules not applying to the shell popup windows that it opens. This isn't stopping me from being able to use it, but I would really like to fix this for the sake of my ADHD. 

If there's anything I can do to help, please point me in the right direction. I'm thinking maybe the rules aren't being applied until after the compositor has finished centering the window but unsure.

### How to reproduce

_**~/.config/hypr/hyprland.conf**_

Using KDE's plasma 'plasmashell' for the shell layer:
`exec-once = plasmashell`

Window rules for floating.
```
windowrulev2 = float,class:org.kde.plasmashell
windowrulev2 = noinitialfocus,class:org.kde.plasmashell
```
'noinitialfocus' is not required to reproduce, only 'float'. That's just my current workaround so that these popup windows don't disappear when I start moving my cursor.

### Crash reports, logs, images, videos

Screenshot of example:
![screenshot-2024-04-13_09:26:02](https://github.com/hyprwm/Hyprland/assets/3039216/4b65161f-6e73-47b8-89ad-f31191362a31)

**Comment by MightyPlaza** [comment]
what's the output of `hyprctl clients` and `hyprctl layers`?
window rules don't work for layers and I don't think that should be a window

**Comment by syslaz** [comment]
> what's the output of `hyprctl clients` and `hyprctl layers`? window rules don't work for layers and I don't think that should be a window

Hi, thanks for the reply. This is the output I get for any windows that plasma creates.

For `hyprctl clients`:
```
Window 56242d8e3810 -> plasmashell:
	mapped: 1
	hidden: 0
	at: 436,296
	size: 1688,848
	workspace: 2 (2)
	floating: 1
	monitor: 1
	class: org.kde.plasmashell
	title: plasmashell
	initialClass: org.kde.plasmashell
	initialTitle: plasmashell
	pid: 318634
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 0
```
Ran the command right after it opens. 

For `hyprctl layers`:
```
Monitor DP-1:
	Layer level 0 (background):
		Layer 56242d8af030: xywh: -2560 0 2560 1440, namespace: desktop
	Layer level 1 (bottom):
	Layer level 2 (top):
	Layer level 3 (overlay):


Monitor DP-2:
	Layer level 0 (background):
		Layer 56242d8b0c70: xywh: 0 0 2560 1440, namespace: desktop
	Layer level 1 (bottom):
	Layer level 2 (top):
		Layer 56242d8d55d0: xywh: 0 1378 2560 62, namespace: dock
	Layer level 3 (overlay):


Monitor DP-3:
	Layer level 0 (background):
		Layer 56242d8b17a0: xywh: 2560 0 2560 1440, namespace: desktop
	Layer level 1 (bottom):
	Layer level 2 (top):
	Layer level 3 (overlay):
```

I want to add, that there's no windows by default when plasmashell is just running. The actual bar works quite fine. The windows only appear in 'hyprctl clients' when they're opened like I showed on my screenshot.

**Comment by MightyPlaza** [comment]
i don't think there is any way in wayland for a window to chose where it wants to go
my guess is likely implemented with https://invent.kde.org/libraries/plasma-wayland-protocols

you can get around this by using the `move` window rule to chose the starting position of the window
another option would be having the plasma-protocols in hyprland, which if I'm not mistaken can be done with a plugin

**Comment by syslaz** [comment]
> i don't think there is any way in wayland for a window to chose where it wants to go
> 
> my guess is likely implemented with https://invent.kde.org/libraries/plasma-wayland-protocols
> 
> 
> 
> you can get around this by using the `move` window rule to chose the starting position of the window
> 
> another option would be having the plasma-protocols in hyprland, which if I'm not mistaken can be done with a plugin

Yeah you're probably right. Silly me. Maybe I'll try writing that plugin. Ive only been using Wayland and honestly Linux as my main drivers for a short while and with all these new features getting constantly added to Wayland itself, I guess I didn't realize this was one of those things that's missing from the official protocols. 

Thank you so much for helping me understand all this. I'll close this ticket as it isn't a bug in Hyprland itself. Perhaps feature request?
