### ISSUE TITLE
Adding support to access key presses by privileged programs.

### ISSUE THREAD

**Issue by luposmi** [hyprwm/Hyprland#5583]
### Description

My original goal was to implement vim like bindings to Hyprland, and thought about how to implement those.
However, the style of the config wouldn't really support this. Let's say we want to add a keybinding <Leader><number>u (leader could be for example SUPER)  to go <number> workspaces up. 
As the style of the config does not allow for dynamic (programmatic) key binds, even if Hyprland would support vim bindings in the sense of pressing multiple keys after another, you would still need to hard-code each number (in this example).

The obvious way around this would be to allow for example LUA as a second configuration language, but that would probably be a too big change with benefits to too little people (but still be a strong one as you could add dependencies very easily and expand on the functionality). 

So my idea would be to just write a program that can read the keybindings from Hyprland in a separate application and use the API to handle the behavior. This could for example be done with an option "exec-once-keyboard-input" which works like exec-once, but writes all keypress behaviours to the stdin of the program.

**Comment by MightyPlaza** [comment]
why not use the plugin system?

**Comment by zakk4223** [comment]
https://github.com/Euro20179/HyKeys

**Comment by MightyPlaza** [comment]
> https://github.com/Euro20179/HyKeys

that as well but it's unmaintained

**Comment by luposmi** [comment]
> why not use the plugin system?

Ye, can try that. I do personally do not know much about the plugin API and what it can try. The reason for the idea with stdin is that, as soon you secure the config files correctly, unprivileged (in a sense that programs I wouldn't want to be able to sniff on my keyboard) couldn't do so in contrast to using sending it to the IPC.

**Comment by luposmi** [comment]
@MightyPlaza lets start with the dumbest idea possible and wrap the api in lua XD
