### ISSUE TITLE
Allow to specify name for headless output

### ISSUE THREAD

**Issue by Serpentian** [hyprwm/Hyprland#5586]
### Description

It's difficult to write scripts for managing headless monitors. When we create monitor, it gets name `HEADLESS-*`, where `*` is some id. After that we have to parse `hyprctl monitors` and find name, which the output we created got. And finally we can use that name in other programs, like `wayvnc`.

It'd be great if either `hyprctl output create headless` allow to specify a desired name or it can at least throw a name, output got, in stdout.

**Comment by MightyPlaza** [comment]
it says you can in the wiki is that wrong or is this outdated?

**Comment by vaxerski** [comment]
issue got fixed
