### ISSUE TITLE
Use regex engine that supports negative lookahead

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#5603]
### Description

It's useful to be able to create regex rules that don't match a certain expression. This isn't possible with C++'s stdlib regex. Consider using either `Boost.Regex` or PCRE.

**Comment by vaxerski** [comment]
no, why

**Comment by andresilva** [comment]
Mainly useful for negative matches, for example you want to have window rules for the same app class but different titles. Can be scripted through the events socket though so I'll close.
