### ISSUE TITLE
Windows reset to default rotation during closing animation on rotated montior

### ISSUE THREAD

**Issue by NeutronicMC** [hyprwm/Hyprland#561]
**Steps to reproduce:**
- Open a window on a rotated monitor
- Close window

**Expected outcome:** The window should close with the same rotation that was applied to it during the rest of its lifespan. 

**Noted outcome:** Upon closing a window, it rotates back to the default rotation of the monitor during the closing animation.
This creates particular problems when taking an area selection screenshot on a rotated monitor because the area selection graphic rotates into the screenshot area *right* as the screenshot is taken.
Example:
![image](https://user-images.githubusercontent.com/17936976/185817114-7f84032f-a429-4b5c-8644-fdfe49a3f2d8.png)

**Comment by vaxerski** [comment]
What you are describing is a layer surface and not a window. At any rate, fixed in 86be6c3884033e35bf3efef4ba705d3be72cbe87
