### ISSUE TITLE
Disable built-in screen of laptop when lid off

### ISSUE THREAD

**Issue by AhJi26** [hyprwm/Hyprland#5614]
### Description

I'm using hyprland on my laptop with external screens. When I close the lid of my laptop, the built-in screen will still be recognized and used by hyprland, even if it is actually powered off. Is there any way to disable it when not in use?

**Comment by vaxerski** [comment]
disable the monitor on a lid switch

**Comment by michelhe** [comment]
And what if I enter hyprland and the laptop lid is already closed (i.e a docked laptop) ? I need to re-open the lid or come up with advanced scripting / use udev to tell hyprctl to disable the monitor.

**Comment by michelhe** [comment]
(BTW, I did `exec-once = cat /proc/acpi/button/lid/LID/state  | grep closed | sleep 3 && hyprctl keyword monitor "eDP-1, disable" && notify-send "Laptop lead closed, disabling monitor"` and it's working kinda OK for me )
