### ISSUE TITLE
Display rapidly "bouncing" up and down a single pixel at high refresh rates

### ISSUE THREAD

**Issue by bobdanek** [hyprwm/Hyprland#5615]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 3875679755014997776e091ff8903acfb311dd2f  ().
Date: 2024-04-01
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: rdk-thinkpad
Release: 6.8.5
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr 10 14:38:25 UTC 2024


GPU information:
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev d1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240412.cfd6b5f"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hy3 by outfoxxed ver 0.1
```

</details>

### Bug or Regression?

Bug

### Description

Often I'll notice that the image on my external display is bouncing, twitching, vibrating up and down rapidly by a single pixel. This only happens when using the preferred refresh rate of the monitor (120/119.98Hz) - when I drop it to 75hz the problem completely goes away.

Restarting Hyprland does not fix it, but a reboot does temporarily stop it from occurring. It seems to happen after my laptop and/or the display resume from sleep.

The external display is an LG 38WN95C-W, connected via USB-C to my ThinkPad T14s AMD (Gen 2), though the port on the monitor is Thunderbolt and my ThinkPad does not have Thunderbolt, it still works mostly fine (apart from needing to switch to a TTY and back when resuming from suspend, but that's almost certainly a separate issue).

### How to reproduce

I'm unsure how this could be reproduced without a similar hardware setup.

### Crash reports, logs, images, videos

I attached a high speed (I think 8x) video showing the twitching with the monitor at 120hz, with the big red circle on the right staying put as it's part of the monitor's OSD for changing options. at about 00:23 the screen goes dark as I save the config, switching it to 75hz, and it comes back around 00:36 showing the twitching has stopped.

https://github.com/hyprwm/Hyprland/assets/25288485/14901f87-fed0-4494-9239-6cb3fea90605

**Comment by vaxerski** [comment]
> though the port on the monitor is Thunderbolt 

very likely that's the issue.

Anyways, this does not seem like a hyprland issue, but rather drivers/kernel. Does this happen on sway?

**Comment by bobdanek** [comment]
> Does this happen on sway?

Yep, seems to. Agreed it's more likely kernel or drivers.
