### ISSUE TITLE
hyprpm and hyprctl disagreeing on loading plugins

### ISSUE THREAD

**Issue by zebogan** [hyprwm/Hyprland#5616]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 79a139c9495568f69dd995bce1ca579247a98a17  (flake.lock: update).
Date: Mon Apr 15 13:57:27 2024
Tag: v0.39.0-12-g79a139c9, commits: 4456

flags: (if any)


System Information:
System name: Linux
Node name: bogans-laptop
Release: 6.8.5-1-default
Version: #1 SMP PREEMPT_DYNAMIC Thu Apr 11 04:31:19 UTC 2024 (542f698)


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])


os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240412"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240412"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240412:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240412"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

i run ```hyprpm reload``` after ```hyprpm enable```ing all the plugins i want. hyprpm says that the plugins have been loaded successfully. however, if i run ```hyprctl plugin list``` it says ```no plugins loaded```. there aren't any errors or anything, even when running with -v

### How to reproduce

manually build hyprland version v0.39.0-12-g79a139c9, then run hyprpm update, then add official plugin repo, then enable plugins, run hyprpm reload, and then run hyprctl plugin list

**Comment by vaxerski** [comment]
well thats odd. What if you disable them and re-enable them?

**Comment by zebogan** [comment]
```sh
bogan@bogans-laptop:~> hyprpm disable hyprexpo
✔ Disabled hyprexpo
✔ Ensuring plugin load state
✔ Loaded hyprtrails
✔ Plugin load state ensured
bogan@bogans-laptop:~> hyprpm list
 → Repository hyprland-plugins:
  │ Plugin borders-plus-plus
  └─ enabled: false
  │ Plugin csgo-vulkan-fix
  └─ enabled: false
  │ Plugin hyprbars
  └─ enabled: false
  │ Plugin hyprexpo
  └─ enabled: false
  │ Plugin hyprtrails
  └─ enabled: true
  │ Plugin hyprwinwrap
  └─ enabled: false
bogan@bogans-laptop:~> hyprpm disable hyprtrails
✔ Disabled hyprtrails
✔ Ensuring plugin load state
✔ Plugin load state ensured
bogan@bogans-laptop:~> hyprpm list
 → Repository hyprland-plugins:
  │ Plugin borders-plus-plus
  └─ enabled: false
  │ Plugin csgo-vulkan-fix
  └─ enabled: false
  │ Plugin hyprbars
  └─ enabled: false
  │ Plugin hyprexpo
  └─ enabled: false
  │ Plugin hyprtrails
  └─ enabled: false
  │ Plugin hyprwinwrap
  └─ enabled: false
bogan@bogans-laptop:~> hyprpm enable hyprexpo
✔ Enabled hyprexpo
✔ Ensuring plugin load state
✔ Loaded hyprexpo
✔ Plugin load state ensured
bogan@bogans-laptop:~> hyprpm reload
✔ Ensuring plugin load state
✔ Loaded hyprexpo
✔ Plugin load state ensured
bogan@bogans-laptop:~> hyprctl plugin list
no plugins loaded
bogan@bogans-laptop:~> 
```

**Comment by zebogan** [comment]
that didn't fix it @vaxerski

**Comment by vaxerski** [comment]
no clue. Maybe there are spaces in the path somewhere? that could be an issue

**Comment by vaxerski** [comment]
all official plugins would show up a notification on fail, tho

**Comment by Mr-Ples** [comment]
might be a long shot but i think it would be fixed with this https://github.com/hyprwm/Hyprland/issues/5635

**Comment by zebogan** [comment]
> no clue. Maybe there are spaces in the path somewhere? that could be an issue
> 
> 

there shouldn't be spaces, i don't know where the so files are stored though

**Comment by zebogan** [comment]
> might be a long shot but i think it would be fixed with this https://github.com/hyprwm/Hyprland/issues/5635 (i think it has something to do with wl-roots fork)
> 
> 

i don't think so

**Comment by zebogan** [comment]
> Is there anything in the logs that indicates they're getting unloaded due to some exception?

not sure, where would i see the logs?

**Comment by zebogan** [comment]
update: figured out where to see the logs, turns out the .so files just aren't there
not sure why

**Comment by zebogan** [comment]
update 2: its because the plugins fail to build when running hyprpm add, which is due to https://github.com/hyprwm/hyprland-plugins/issues/63

it seems like that issue should have been fixed in https://github.com/hyprwm/hyprland-plugins/pull/64 so not sure why its still happening

**Comment by zebogan** [comment]
solved by https://github.com/hyprwm/hyprland-plugins/pull/150

**Comment by ipg0** [comment]
@zebogan
> update: figured out where to see the logs

And where is that?

**Comment by zebogan** [comment]
i honestly don't remember, i think it was explained in the docs? i could also be wrong, id say just google it
