### ISSUE TITLE
Always scroll the window below the mouse, instead of the one that is focused

### ISSUE THREAD

**Issue by mavonarx** [hyprwm/Hyprland#5626]
### Description

I think it would be very nice if we can scroll windows without focusing them if they are below the cursor. 
Currently always the window with focus gets scrolled even when the mouse is hovering a complete different window.

**Comment by donovanglover** [comment]
Have you tried changing [`follow_mouse`](https://wiki.hyprland.org/Configuring/Variables/#follow-mouse-cursor)?

**Comment by mavonarx** [comment]
Yes, but that does change the focus and I cannot write at the same time to a terminal or a different window. 

The use case is writing to a window via keyboard while scrolling another window with a mouse. Thats not possible with follow_mouse

**Comment by thejch** [comment]
> writing to a window via keyboard while scrolling another window with a mouse

follow_mouse = 2?
