### ISSUE TITLE
Follow mouse can't be disabled on float windows

### ISSUE THREAD

**Issue by mshzsh** [hyprwm/Hyprland#563]
in hyprland.conf `follow_mouse` is `0` but not working on float windows

**Comment by mshzsh** [comment]
focuced windows lose focus when switching between workspaces. and when use `follow_mouse=3`, cannot use window!
Is there a way to keep windows from losing focus when moving between workspaces?

**Comment by vaxerski** [comment]
bug.

**Comment by vaxerski** [comment]
> Is there a way to keep windows from losing focus when moving between workspaces?

should be fixed in 429b2bffeda0211e90b31b039a7d89cfe25ad6e6
