### ISSUE TITLE
Transfer workspaces to secondary display on closed laptop lid.

### ISSUE THREAD

**Issue by svin24** [hyprwm/Hyprland#5634]
### Description

Currently I have a laptop connected to a secondary display. When I close the laptop lid to focus only on the secondary display the workspace behind my laptop is stuck there along with any application that is there. 
In fact I can even move my mouse in that area in which I can't see.

Similar to the usage of `disable` under [monitor variables](https://wiki.hyprland.org/Configuring/Monitors/#disabling-a-monitor). There should be a way for hyprland to know that the display "may be disabled" by closing the lid and all applications should be moved to the secondary screen. Of course this obviously includes automatically re enabling the display if the lid is opened again.

**Comment by vaxerski** [comment]
this is hyprland, it's on you to configure this. See switch binding in the wiki.

**Comment by svin24** [comment]
ooooh I found it. Thanks man. 
Although i guess documentation could be a little bit better about referencing it in the monitors page. 
I'll see if I can contribute a small edit later

**Comment by alessandriniluca** [comment]
> ooooh I found it. Thanks man. Although i guess documentation could be a little bit better about referencing it in the monitors page. I'll see if I can contribute a small edit later

Hi @svin24, I apologize for the disturbance and for commenting under a closed issue. May I kindly ask you how you solved it? I can't find how to do this on the lid closure

**Comment by svin24** [comment]
@alessandriniluca 
here you go man

```
monitor=eDP-1, 1920x1080, 0x0, 1
monitor=HDMI-A-1, 1920x1080@60, -1920x-600, 1
# LAPTOP LID STUFF
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 1"
```
Adjust it to your hardware

As a side tangent please check this out and see if it happens to you. https://github.com/hyprwm/hyprlock/issues/480#issuecomment-2354784021

**Comment by alessandriniluca** [comment]
Thanks a lot, really appreciated. Unfortunately, in my case, that correctly disables the integrated laptop monitor and it does not break hyprlock, but is not enough to move the workspaces, I think I have some other problems to investigate. If I'll solve it, I'll write here / create a custom bash script to do that.

thanks again for the answer!

**Comment by alikazai** [comment]
> # LAPTOP LID STUFF
> bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
> bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 1"

thanks
