### ISSUE TITLE
Crash after a laptop was left suspended for some time

### ISSUE THREAD

**Issue by ReshetnikovPavel** [hyprwm/Hyprland#5636]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashed

### How to reproduce

So, I closed the lid of my laptop and left it for a few hours. When I opened it, Hyprland crashed. I don't know if this information would help, but I use hypridle and swaylock

### Crash reports, logs, images, videos

[hyprlandCrashReport3756.txt](https://github.com/hyprwm/Hyprland/files/15026230/hyprlandCrashReport3756.txt)

**Comment by vaxerski** [comment]
an ASan trace would help https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by ReshetnikovPavel** [comment]
Well, didn't manage to reproduce, sorry

**Comment by vaxerski** [comment]
I'll treat this as a cosmic ray hitting your RAM then, feel free to reopen if happens again
