### ISSUE TITLE
JetBrains crashes Hyprland

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#5642]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e57a2d7ec87ae775828ea8628ef4eeafce8e6e70 dirty (keybindmgr: add optional `silent` suffix to `movewindow`. (5597)).
Date: Wed Apr 17 11:04:16 2024
Tag: v0.39.1-2-ge57a2d7e, commits: 4462

flags: (if any)


System Information:
System name: Linux
Node name: roman
Release: 6.9.0-rc4-1-cachyos-rc-lto
Version: #1 SMP PREEMPT_DYNAMIC Mon, 15 Apr 2024 07:20:36 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Bug or Regression?

Bug

### Description

in jetbrains products if the mouse is hold over some specific elements hyprland starts flickering and crashes

### How to reproduce

open in my case PHPStorm use Wayland
vmoptions
```
-Xmx8192m
-XX:+UseZGC
-Drecreate.x11.input.method=true
-Dawt.ime.disabled=true4
-Dawt.toolkit.name=WLToolkit
```
open the integrated git view and click create new branch from develop 
hold the mouse over the popup until the mouse starts flickering, 
crashes within seconds

### Crash reports, logs, images, videos

[hyprlandCrashReport29419.txt](https://github.com/hyprwm/Hyprland/files/15036550/hyprlandCrashReport29419.txt)

**Comment by vaxerski** [comment]
looks like you're calling `hyprctl globalshortcuts` and that causes the crash. Why are you doing that? (it shouldnt crash regardless, but yea)

**Comment by romanstingler** [comment]
@vaxerski to be honest I have no clue how it should call `hyprctl globalshortcuts` never used it before.

**Comment by MightyPlaza** [comment]
still happening?
