### ISSUE TITLE
Artifacts when resizing floating windows

### ISSUE THREAD

**Issue by et-rnal** [hyprwm/Hyprland#5643]
[2024-04-19_22-04-1713532313.webm](https://github.com/hyprwm/Hyprland/assets/123827779/2115916b-4625-460d-a30b-7e5eb5f4f224)

### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: eternal
Release: 6.6.21-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:27:56 JST 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Upon setting a window to floating (foot terminal in the video) and resizing it, artifacts are produced on the edges of the window. This appears both when animations/blur/opacity are enabled and disabled. This occurs both with native wayland and xwayland/flatpak programs. 

The switches I toggle in the webm just enable/disable opacity and animations. 

This does not appear unless you are resizing pretty quickly. 

### How to reproduce

1.) Set a window to floating
2.) Vigorously resize it

**Comment by vaxerski** [comment]
that's a VERY old version you got there.
