### ISSUE TITLE
Can't dynamically enable/disable input devices anymore

### ISSUE THREAD

**Issue by DaniD3v** [hyprwm/Hyprland#5645]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.37.1  ().
Date: 2024-03-16
Tag:

flags: (if any)


System Information:
System name: Linux
Node name: nixOS
Release: 6.1.85
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr 10 14:28:36 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] [10de:25a2] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c8) (prog-if 00 [VGA controller])


os-release: BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.11.6272.51651a540816"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.11 (Tapir)"
SUPPORT_END="2024-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.11 (Tapir)"
VERSION_CODENAME=tapir
VERSION_ID="23.11"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Here's a Reddit [thread](https://www.reddit.com/r/hyprland/comments/1bqohmd/dynamically_enabledisable_device/) with the exact same issue I'm having. 

Hyprctl can't set the enabled state of a specific device. This is really annoying. Ideally there'd be a dispatcher that can toggle a device. That'd also remove the need for a external scrip.

The workaround mentioned in the script is hacky and I'd rather not rely on completely undefined behaviour of Hyprland updating the variable.

Also I didn't read the commit but the changes definitely don't seem justified. There's not really a reason to change the config like that. At least not for users. + These breaking changes should probably be in the release notes

**Comment by vaxerski** [comment]
`'device[name]:prop' 'value'`

**Comment by DaniD3v** [comment]
For anyone stumbling upon this issue you actually have to use the []

like this
```sh
hyprctl keyword "device[asue120a:00-04f3:319b-touchpad]:enabled" true
```

I'm mentioning this because the Hyprland wiki often uses [] as a placeholder.
Here's an example:

![image](https://github.com/hyprwm/Hyprland/assets/124387056/be416466-7d55-49ba-967b-86ba830074c4)

**Comment by kRHYME7** [comment]
Thanks! 🛞
