### ISSUE TITLE
New windows in inactive workspaces stealing focus

### ISSUE THREAD

**Issue by rrredface** [hyprwm/Hyprland#565]
To reproduce:
One way is to first make sure you have a window rule assigning whatever browser you use to a specific workspace. I have these rules:
```
windowrule = workspace 1 silent,^(librewolf)$
windowrule = workspace 1 silent,^(firefox)$
```
Then you can go to [this page](https://www.bennish.net/web-notifications.html), give it permission to display notifications, then click show in 5s. Switch to a fullscreen window in a different workspace, wait the 5 seconds for the notification window to open, and the active window will then be un-fullscreened.

Another way is by opening a terminal window and running something like this:
```sh
sleep 5; pavucontrol
```
And then again, switch to a fullscreen window in any workspace other than the one to which pavucontrol (or whatever program you choose to run) is assigned.
I have this window rule:
```
windowrule = workspace 4 silent,^(pavucontrol)$
```

Expected behavior:
If a workspace windowrule contains `silent` then matching windows should not get focus, unless that window's workspace is already the active one.

Actual behavior:
If the new window is in the same workspace as the focused one, that new window gets focus and the previous one does not get it back. I would say that's pretty normal behavior. When the new window opens in a different workspace, it seems to steal it momentarily and then give it right back to the previously focused window. The previously focused window regains focus whether `follow_mouse` is enabled or disabled.

I'm running both Hyprland and wlroots built from source, cloned less than an hour before posting this issue so I'm up to date.

**Comment by vaxerski** [comment]
check with de477a6ff589479e6ae8773ea5da097d7d0fdce5

**Comment by rrredface** [comment]
> check with [de477a6](https://github.com/hyprwm/Hyprland/commit/de477a6ff589479e6ae8773ea5da097d7d0fdce5)

Seems to have broken workspace rules completely. Now things just open in whatever workspace I'm currently on, even though according to Hyprland the rules are matching:
```
New XDG Surface created. (class: com.github.wwmm.easyeffects)
Registered signal for owner e762c660: e76b33d8 -> e762c6c8 (owner: XDG Window)
Registered signal for owner e762c660: e76b33e8 -> e762c730 (owner: XDG Window)
Registered signal for owner e762c660: e76b33a8 -> e762c798 (owner: XDG Window)
Registered signal for owner e762c660: e7413b20 -> e762cc78 (owner: Toplevel)
Registered signal for owner e762c660: e7413b30 -> e762cce0 (owner: Toplevel)
Registered signal for owner e762c660: e7413b40 -> e762cc10 (owner: Toplevel)
Searching for matching rules for com.github.wwmm.easyeffects (title: EasyEffects)
Window rule workspace 4 silent -> ^(com\.github\.wwmm\.easyeffects)$ matched e762c660 [EasyEffects]
Rule workspace matched by window e762c660, ^(com\.github\.wwmm\.easyeffects)$ applied.
OPENINGON: e732e4b0, Workspace: 1, Monitor: 0
Window got assigned a surfaceTreeNode 0
Registered signal for owner e762c660: e7598310 -> e762c660 (owner: XDG Window Late)
Registered signal for owner e762c660: e74a7a20 -> e762c800 (owner: XDG Window Late)
Registered signal for owner e762c660: e76b33c8 -> e762c938 (owner: XDG Window Late)
Registered signal for owner e762c660: e74a79b0 -> e762ca70 (owner: XDG Window Late)
Registered signal for owner e762c660: e74a79d0 -> e762ca08 (owner: XDG Window Late)
Registered signal for owner e762c660: e74a79e0 -> e762c9a0 (owner: XDG Window Late)
Registered signal for owner e762c660: e74a79f0 -> e762cad8 (owner: XDG Window Late)
Registered signal for owner e762c660: e74a79c0 -> e762c8d0 (owner: XDG Window Late)
Tried to set workspace silent rule to a nofocus window!
```
Same behavior with 7b01c3d028ee5e6423b65388966162a50813b83b as well.

**Comment by vaxerski** [comment]
oh right mb

**Comment by vaxerski** [comment]
should be fixed

**Comment by vaxerski** [comment]
done and working.

**Comment by rrredface** [comment]
> done and working.

Might I be doing something wrong here then?  
`hyprctl version`:
```                                                                                                
Hyprland, built from branch HEAD at commit f7c741317fc2084cd63d007292066292585422addirty (fix shadows on silent rule).
flags: (if any)
debug
```
Still messes with fullscreen windows on my machine. Relevant bit from my logfile:
```
New XDG Surface created. (class: pavucontrol)
Registered signal for owner 8cdfcf40: 8ce01838 -> 8cdfcfa8 (owner: XDG Window)
Registered signal for owner 8cdfcf40: 8ce01848 -> 8cdfd010 (owner: XDG Window)
Registered signal for owner 8cdfcf40: 8ce01808 -> 8cdfd078 (owner: XDG Window)
New TextInput added!
Registered signal for owner 8ce0fea0: 8cdf0f88 -> 8ce0feb0 (owner: textInput)
Registered signal for owner 8ce0fea0: 8cdf0f98 -> 8ce0ff80 (owner: textInput)
Registered signal for owner 8ce0fea0: 8cdf0fa8 -> 8ce0ff18 (owner: textInput)
Registered signal for owner 8ce0fea0: 8cdf0fb8 -> 8ce0ffe8 (owner: textInput)
Registered signal for owner 8cdfcf40: 8cb34330 -> 8cdfd558 (owner: Toplevel)
Registered signal for owner 8cdfcf40: 8cb34340 -> 8cdfd5c0 (owner: Toplevel)
Registered signal for owner 8cdfcf40: 8cb34350 -> 8cdfd4f0 (owner: Toplevel)
Searching for matching rules for pavucontrol (title: Volume Control)
Window rule workspace 4 silent -> ^(pavucontrol)$ matched 8cdfcf40 [Volume Control]
Rule workspace matched by window 8cdfcf40, ^(pavucontrol)$ applied.
OPENINGON: 8ca71bb0, Workspace: 1, Monitor: 0
Set keyboard focus to surface 8cdf2f80, with window name: Volume Control
Window got assigned a surfaceTreeNode 0
Registered signal for owner 8cdfcf40: 8cdf3240 -> 8cdfcf40 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8cdf3420 -> 8cdfd0e0 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8ce01828 -> 8cdfd218 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8cdf33b0 -> 8cdfd350 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8cdf33d0 -> 8cdfd2e8 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8cdf33e0 -> 8cdfd280 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8cdf33f0 -> 8cdfd3b8 (owner: XDG Window Late)
Registered signal for owner 8cdfcf40: 8cdf33c0 -> 8cdfd1b0 (owner: XDG Window Late)
Suppressed (ignoreevents true) event of type activewindow, content: ,
Suppressed (ignoreevents true) event of type workspace, content: 4
```
The last 2 lines there seem interesting, not sure if they mean what it sounds like they mean though.
Also: `OPENINGON: 8ca71bb0, Workspace: 1, Monitor: 0` - it always logs that it's opening on whichever workspace is focused, but pavucontrol *does* in fact open in workspace 4 as it should.

**Comment by vaxerski** [comment]
ah, wait, it's a fullscreen workspace? shucks, didnt test that. Yeah it will cancel fullscreen. Sorz, will fix tomorrow. Ping me if i forget.

**Comment by vaxerski** [comment]
fixed in b09f157b93576ccd5bd1038df2ab8f84f03ec4c8

**Comment by rrredface** [comment]
That does in fact fix the fullscreen issues. Thank you friend 🙏
I kinda feel bad for even mentioning it, but there is one more problem I've been able to find.

I found this one by accident. If I have osu! (latest AppImage from [here](https://github.com/ppy/osu/releases) if you want to test it) open in workspace 5, and I leave firefox open in workspace 1, a notification window opening still seems to momentarily steal focus before giving it right back. This wouldn't be an issue if not for the fact that osu! automatically pauses if it loses focus in the middle of a play. I checked if the same thing happens in Sway and it does not. This also happens whether the osu! window is fullscreen or not.

Not sure if anything in here is particularly relevant, but this is everything in my logfile from the moment of me switching focus to the osu! window, up to me switching back to workspace 1 to close the notification window.
If it matters, the window with a blank name is the notification window.
```
Set keyboard focus to surface cc76280, with window name: osu!
New mouse constraint at cc71500
Registered signal for owner ca2bb50: cc71608 -> ca2bbc8 (owner: Constraint)
Registered signal for owner ca2bb50: cc715f8 -> ca2bb60 (owner: Constraint)
Constraint rechecked: 0, 0 to 1920, 1080 for cc76280 (window name: )
Registered signal for owner c857450: cc76540 -> c8574a8 (owner: Mouse constraint commit)
Constrained mouse to cc71500
Enabling TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Callback c8574d0 -> c8574c8, Mouse constraint commit removed.
Unconstrained mouse from cc71500
Callback ca2bbf0 -> ca2bbe8, Constraint removed.
Callback ca2bb88 -> ca2bb80, Constraint removed.
New mouse constraint at cc71500
Registered signal for owner cc76680: cc71608 -> cc766f8 (owner: Constraint)
Registered signal for owner cc76680: cc715f8 -> cc76690 (owner: Constraint)
Constraint rechecked: 0, 0 to 1920, 1080 for cc76280 (window name: )
Registered signal for owner c857450: cc76540 -> c8574a8 (owner: Mouse constraint commit)
Constrained mouse to cc71500
Callback c8574d0 -> c8574c8, Mouse constraint commit removed.
Unconstrained mouse from cc71500
Callback cc76720 -> cc76718, Constraint removed.
Callback cc766b8 -> cc766b0, Constraint removed.
New mouse constraint at cc71500
Registered signal for owner cc74940: cc71608 -> cc749b8 (owner: Constraint)
Registered signal for owner cc74940: cc715f8 -> cc74950 (owner: Constraint)
Constraint rechecked: 0, 0 to 1920, 1080 for cc76280 (window name: )
Registered signal for owner c857450: cc76540 -> c8574a8 (owner: Mouse constraint commit)
Constrained mouse to cc71500
Committing TextInput on no IME!
Callback c8574d0 -> c8574c8, Mouse constraint commit removed.
Disabling TextInput on no IME!
Enabling TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Disabling TextInput on no IME!
Enabling TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Disabling TextInput on no IME!
Enabling TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Committing TextInput on no IME!
Keybind triggered, calling dispatcher (64, , 0)
Changed to workspace 1
Set keyboard focus to surface ca0e8d0, with window name: HTML5 Web Notifications Test - Bennish.net — LibreWolf
```
And all of my window rules, just in case I'm actually dumb and have configured something wrong:
```
# Workspace layout
# 1 = browser, anything else I need to see at the same time as it
windowrule = workspace 1 silent,^(librewolf)$
windowrule = workspace 1 silent,^(firefox)$
# 2 = mostly just a container for terminal windows that i don't want cluttering other workspaces
#
# 3 = discord, steam, other programs that will generally be left running
windowrule = workspace 3 silent,^(Discord)|(discord)$
windowrule = workspace 3 silent,^(WebCord)$
windowrule = workspace 3 silent,^(Steam)|(steam)$
windowrule = workspace 3 silent,^(lutris)$
windowrule = workspace 3 silent,^(itch-bin)$
# 4 = utilities/settings, i.e. keepass, easyeffects
windowrule = workspace 4 silent,^(org\.keepassxc\.KeePassXC)$
windowrule = workspace 4 silent,^(com\.github\.wwmm\.easyeffects)$
windowrule = workspace 4 silent,^(pavucontrol)$
windowrule = workspace 4 silent,^(org\.rncbc\.qpwgraph)$
# 5 = games
windowrule = workspace 5 silent,^(osu!)$
# 6 = anything else
```
For what it's worth, I can pretty easily avoid this problem by just not having firefox open in the background while I'm playing specifically that game, so I wouldn't fault you if this was pretty low on your priority list.

**Comment by vaxerski** [comment]
> `HTML5 Web Notifications Test - Bennish.net — LibreWolf`

Wait what?? What type of "notification" is that? dunst should NOT create a window.

**Comment by rrredface** [comment]
It's not any notification daemon creating the window. It's librewolf doing it, for reasons that I'm probably just as confused about as you. I have a mako installation that, as far as I can tell, works just fine otherwise. I tried the solution described in emersion/mako#126 with no luck. After that I have admittedly not done all that much research on it because the only problem it's caused me so far is this one.

**Comment by vaxerski** [comment]
weird. the `about:config` option didnt work? shame
