### ISSUE TITLE
Window border shown for a bit when no_gaps_when_only=1

### ISSUE THREAD

**Issue by nik012003** [hyprwm/Hyprland#5650]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 4d0a63523751a590a521fd873f770825023069ae  ().
Date: Thu Apr 18 13:44:51 2024
Tag: , commits: 4465

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.6.3-414.asahi.fc39.aarch64+16k
Version: #1 SMP PREEMPT_DYNAMIC Sun Mar 24 19:44:17 UTC 2024


GPU information: 


os-release: NAME="Fedora Linux Asahi Remix"
VERSION="39 (Thirty Nine)"
ID=fedora-asahi-remix
ID_LIKE=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux Asahi Remix 39 (Thirty Nine)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora-asahi-remix:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedora-asahi-remix.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://discussion.fedoraproject.org/c/neighbors/asahi/asahi-help/94"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39


plugins:

~
```

</details>

### Bug or Regression?

Regression

### Description

After this commit: https://github.com/hyprwm/Hyprland/commit/0634aaeac6cca12e4f72174c431c2db9da9c0072 , if you have `no_gaps_when_only=1` set in the `dwindle` layout, borders will be shown even when only one window is present until the window title is updated(e.g. till you switch firefox tabs) or you switch workspaces. Reverting said commit fixes my issue

### How to reproduce

```
dwindle {
    no_gaps_when_only=1
}
``` 
> Go to an empty workspace
> Open two windows
> Close one
> There will be no gaps(as expetected), but you can see the borders on the outside a bit (more evident with a bar running) 
> Change the name of the window/change workspace/toggle fullscreen and they will disappear

**Comment by gksudolol** [comment]
Update. It should be fixed in [dd39cd7](https://github.com/hyprwm/Hyprland/commit/dd39cd7e420750ac832e1c3e51fac87c16ae8ea3)
