### ISSUE TITLE
Implement Native Scaling Support to Avoid Blurring and Pixelating

### ISSUE THREAD

**Issue by Ate329** [hyprwm/Hyprland#5652]
### Description

I've discovered that the blurriness and pixelation issues encountered with several applications on HiDPI screens, such as Zoom Meeting, Oracle VM VirtualBox, Arch Linux Tweak Tool, Grub Customizer and Steam, may be solved by implementing a feature similar to KDE Plasma's approach for native scaling support. When I was going through [Arch Wiki](https://wiki.archlinux.org/title/HiDPI) about this issue, I found some information that might be helpful. KDE Plasma offers two scaling modes for Xwayland:

1. **Scaled by the system:** Applications are rendered at 1x and then magnified by KDE Plasma. While this approach works for all applications, it introduces blurriness due to magnification.
2. **Apply scaling themselves:** Applications render themselves at the appropriate size, avoiding blurriness. However, non-HiDPI-aware applications render at 1x scale, appearing small.

This feature request seeks to explore the possibility of implementing a similar approach to native scaling support within Hyprland to mitigate the blurriness and pixelation issues encountered with Xwayland on HiDPI screens.

**Proposal:**
I just want to ask and investigate the possibility of implementing a scaling method similar to KDE Plasma's "Apply scaling themselves" mode, where X applications are encouraged to render themselves at the appropriate size to avoid blurriness. This approach could potentially enhance the user experience for HiDPI screen users without sacrificing visual clarity.

**Additional Information:**
- The current scaling issues impact usability for tasks requiring precise visualization, such as virtual machine management and gaming (sometimes this can be quite annoying).
- If I remember correctly, my personal experience with KDE Plasma 5 Wayland suggests that similar issues weren't encountered, indicating the possibility of solving this issue by using a scaling approach similar to what is implemented in KDE Plasma.

**Comment by vaxerski** [comment]
it's literally there. RTFM. https://wiki.hyprland.org/Configuring/Variables/#xwayland

**Comment by Ate329** [comment]
Yes I know that and I have tried to enable force_zero_scaling with env = GDK_SCALE,2. However, the application doesn't seem to be scaled properly. I have no idea why maybe there is a misconfiguration?
For example in Krita:
![image](https://github.com/hyprwm/Hyprland/assets/74974216/1f15c62c-6205-4660-9855-50a390d92a13)

**Comment by vaxerski** [comment]
it is a misconfiguration. force_zero_scaling does exactly what KDE's "let apps scale themselves".

Since Krita isn't GTK, you probably want some QT env instead.

**Comment by Ate329** [comment]
Thanks I will try to do that
