### ISSUE TITLE
Contents of window not visible

### ISSUE THREAD

**Issue by saulback** [hyprwm/Hyprland#5658]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 730] [8086:4c8b] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Today after restarting (which I rarely do), opening the brave browser just results in an empty square box appearing. The window title is in waybar and I can interact with the browser. Ctrl+T -> new tab, I can type in a url and it goes to the url. I just can't see anything. I did set the ozone option (or whatever) in brave a few weeks ago and haven't had any problems. All other programs seem to open fine, it is just brave. I've tried restarting and that didn't help.

Possibly related to #2599.

<details> <summary>hyprctl clients - I'm including a kitty and a firefox window, which seem to be working fine.</summary>

``` sh
❯ hyprctl clients
Window 5cdc9eae8a20 -> New Issue · hyprwm/Hyprland — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 1,41
	size: 2558,1398
	workspace: 2 (2)
	floating: 0
	monitor: 1
	class: firefox
	title: New Issue · hyprwm/Hyprland — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 2678
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 1

Window 5cdc9dc78920 -> hyprctl clients:
	mapped: 1
	hidden: 0
	at: 2561,41
	size: 1278,1398
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: kitty
	title: hyprctl clients
	initialClass: kitty
	initialTitle: zsh
	pid: 1685
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 0

Window 5cdc9dcb5df0 -> Untitled - Brave:
	mapped: 1
	hidden: 0
	at: 3841,41
	size: 1278,1398
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: Brave-browser
	title: Untitled - Brave
	initialClass: Brave-browser
	initialTitle: New Tab - Brave
	pid: 5721
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```
</details>

### How to reproduce

I'm unsure of what sequence of events happened that caused this. I am running hyprdots as well, but I don't really modify beyond that.

**Comment by vaxerski** [comment]
have you tried nudging the size?

**Comment by saulback** [comment]
> have you tried nudging the size?

Yeah, tried floating, resizing, different workspace. It is just stuck as transparent. Apparently right clicking caused the menu to appear transparent as well.

**Comment by saulback** [comment]
I haven't tried fixing it in case there is more diagnostic stuff I can gather. If I don't hear back soon, I'm going to start uninstalling and deleting brave config, and whatever else I can think of.

**Comment by RichAyotte** [comment]
I'm having the same issue and I'm 0.39.1. 

If anyone is stuck, launch your chromium based browser with the `--no-experiments` switch

```bash
google-chrome --no-experiments
```

The issue occurs with the Preferred Ozone platform flag set to Wayland. This wasn't an issue with older versions of Hyprland.

Set it to default for X11

![2024-04-20_11-32](https://github.com/hyprwm/Hyprland/assets/294987/c76f40ea-5418-4a5d-aec1-2ef0e883a7a5)

**Comment by vaxerski** [comment]
can someone `git bisect` if this is a regression?

**Comment by RichAyotte** [comment]
My chrome window is completely blank. It's the one on the left. I'll give git bisect a shot.

![2024-04-20_11-52](https://github.com/hyprwm/Hyprland/assets/294987/e7f14c4f-5e9c-49a2-b4e5-c0f20118da04)

**Comment by RichAyotte** [comment]
I just tried 0.38.1 and I have the same issue so maybe something has changed in the latest version of chromium. I'm using Chrome Version 124.0.6367.60 (Official Build) (64-bit). I'll try a few more things.

**Comment by RichAyotte** [comment]
I think we can safely eliminate hyprland from the equation. Chrome in GNOME has the same issue. I'll try older version of Chrome.

**Comment by RichAyotte** [comment]
Chrome Version 123.0.6312.122 (Official Build) (64-bit) works fine. It's not hyprland.

If you're on Debian, you can find older versions of your packages in `/var/cache/apt/archives` Might want to copy a working version somewhere safe for now.

**Comment by RichAyotte** [comment]
ref: https://issues.chromium.org/issues/329678163

**Comment by vaxerski** [comment]
closing then
