### ISSUE TITLE
Jetbrains-IDEs causes hyprland to close sessions

### ISSUE THREAD

**Issue by Shvandre** [hyprwm/Hyprland#5661]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit e93fbd7c4f991cb8ef03e433ccc4d43587923e15  (props: bump ver to 0.39.0).
Date: Sun Apr 14 18:48:28 2024
Tag: v0.39.0, commits: 1

flags: (if any)


System Information:
System name: Linux
Node name: b4cksl4sh
Release: 6.8.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Sometimes after clicking "build" button in clion or "run" button in pycharm, Hyprland closes the sessions and i need to lig with sddm again. 

### How to reproduce

Try to use clion, Pycharm, for a while. it's a fickle problem.

### Crash reports, logs, images, videos

[hyprlandCrashReport1119.txt](https://github.com/hyprwm/Hyprland/files/15047519/hyprlandCrashReport1119.txt)
[hyprlandCrashReport1075.txt](https://github.com/hyprwm/Hyprland/files/15047527/hyprlandCrashReport1075.txt)
[logFromJournalctl.txt](https://github.com/hyprwm/Hyprland/files/15047535/logFromJournalctl.txt)

**Comment by vaxerski** [comment]
update.
