### ISSUE TITLE
Hyprland crashes on startup

### ISSUE THREAD

**Issue by Freemason-12** [hyprwm/Hyprland#5662]
Here is the error:
```
Hyprland: symbol lookup error: Hyprland: undefined symbol: _ZN10Hyprcursor18CHyprcursorManagerC1EPKcPFv19eHyprcursorLogLevelPcE
```

**Comment by oYakate** [comment]
how did you install hyprland(package manager or built manually)?

**Comment by vaxerski** [comment]
This is an issue on your end. Probably something is compiled wrong

**Comment by Freemason-12** [comment]
> how did you install hyprland(via package manager or built manually)?

I installed it from OpenSUSE official repos

**Comment by Yaikava** [comment]
Still happens on OpenSUSE tumbleweed. Guess the package is booked.
