### ISSUE TITLE
Rhythm Doctor looses focus even with windowdance and forceinput

### ISSUE THREAD

**Issue by spl3g** [hyprwm/Hyprland#5664]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit v0.37.1  ().
Date: 2024-03-16
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: ltrr-mini
Release: 6.6.26
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr 10 14:36:08 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c2) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240410.1042fd8"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Rhythm doctor looses focus when the window goes out of screen until i hover it with my mouse

### How to reproduce

1. set windowrules, follow_input=0 and float_switch_override_focus=0
2. open rhythm doctor
3. start the boss battle from the gif in the hyprlands uncommon tips and tricks
4. looses focus when the window goes out of screen

### Crash reports, logs, images, videos

https://youtu.be/22EIjclPbwA

**Comment by vaxerski** [comment]
supporting legacy x11 apps abusing the protocol is not really something I'm focused on doing. The windowdance wr has been broken for a long while.

**Comment by spl3g** [comment]
Okay, I understand.Maybe then remove the example from the uncommon tips and tricks?

**Comment by vaxerski** [comment]
right, done.
