### ISSUE TITLE
0 GPUs was found

### ISSUE THREAD

**Issue by CosmiCZephyR** [hyprwm/Hyprland#5665]
### Hyprland Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch  at commit e93fbd7c4f991cb8ef03e433ccc4d43587923e15  (props: bump ver to 0.39.0).
Date: Sun Apr 14 18:48:28 2024
Tag: v0.39.0, commits: 1

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.5-zen1-1-zen
Version: №1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:18 +0000

GPU information: 
09:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 Ti] [10de:2182] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
</details>

### Bug or Regression?

Bug

### Description

Things don't work well with the 550.67 drivers, so I wanted to downgrade to 535.113.01, but with them hyprland won't start with error message. 
All the points in the hyprland user guide when you have nvidia are done

### How to reproduce

I think you need to rollback to the 535 version of the nouveau driver on arch linux with zen kernel system

### Crash reports, logs, images, videos

```sh
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.85µs. Estimated average calc time: 0.02µs.
[LOG] Using config: /home/zephyr/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.85µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.75µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.72µs. Estimated average calc time: 0.03µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.68µs. Estimated average calc time: 0.03µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.71µs. Estimated average calc time: 0.03µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.69µs. Estimated average calc time: 0.03µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.69µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.71µs. Estimated average calc time: 0.03µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.68µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.70µs. Estimated average calc time: 0.04µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[backend/backend.c:253] Found 0 GPUs, cannot create backend
[backend/backend.c:428] Failed to open any DRM device
[CRITICAL] m_sWLRBackend was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!
```

**Comment by vaxerski** [comment]
nvidia is not officially supported
