### ISSUE TITLE
Advanced shader support

### ISSUE THREAD

**Issue by SpomJ** [hyprwm/Hyprland#5666]
### Description

So currently, only two of such shaders exist; these are blur and darken effects, inflicted whenever the user sets them to.

The proposal is to provide an interface for setting advanced shaders, and also make more places for them to apply to.

I'm not really sure how would this be configured, however. The most logical approach for it would be something like animations approach, with definitions and applications (and possibly windowrules). But unlike animations, these aren't four numbers, but a complete GLSL program. So the most logical approach now would be outsourcing a shader into a file, then importing that file using something like `defshader = shadername, <path>`, then `shader = inactive_window,, shadername [options]`. (But this is subject to change, of course).

There could also be some nice defaults available, such as tint [RGBA], blur [options, but this would be quite janky to use, perhaps also allow presetting options like we currently do)], saturation [percentage], invert and maybe some others. Also, there may be a separate option whether to use this on the subject or on the background of the subject.

**Comment by vaxerski** [comment]
No. #5282
