### ISSUE TITLE
Closing a floating window between two monitors doesn't "redraw" one monitor

### ISSUE THREAD

**Issue by pbosab** [hyprwm/Hyprland#5669]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch main at commit 4ad739ec63c9a11f0537a884ae2a4c56d6bab10b  (HookSystem: improve callback safety).
Date: Sat Apr 20 21:16:42 2024
Tag: v0.39.1-17-g4ad739ec, commits: 4477

flags: (if any)


System Information:
System name: Linux
Node name: xxx
Release: 6.8.7-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:00 +0000


GPU information: 
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  Hyprspace by KZdkm ver 0.1
```

</details>

### Bug or Regression?

Bug

### Description

I've attached a video, after the clock in the bar start the second monitor.
Making a window float between two monitors and closing it cause this behavior (on one monitor the window still apper till going on it with the mouse or a window).

### How to reproduce

as in description.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/90603492/a8af7898-5fa2-4d97-9388-ab2d8b576b7a

**Comment by Fxzzi** [comment]
bumpies

**Comment by Fxzzi** [comment]
This also happens if a floating window goes over part of the 2nd scree, and you make it tile.

**Comment by ikalco** [comment]
can you try this [patch.txt](https://github.com/user-attachments/files/17415906/patch.txt)

**Comment by Steven--** [comment]
Problem persists.

~~~
Hyprland 0.44.0 built from branch main at commit 0e630e9e74ad34683194a07cfe6afe55a2c0685f dirty (session-lock: reset seat grab on a new session lock (8147)).
Date: Thu Oct 17 22:05:55 2024
Tag: v0.44.0-53-g0e630e9e, commits: 5352
built against aquamarine 0.4.2
~~~

**Comment by Fxzzi** [comment]
the issue actually seems to be fixed for me with the patch that @ikalco provided.

**Comment by Steven--** [comment]
Upon re-testing, I cannot reproduce the issue anymore with the provided path. I suspect that I accidentally started the system's Hyprland rather than the one compiled from git. Sorry for the noise and thanks for the work!
