### ISSUE TITLE
How to bind control

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#567]
So I wanna create a shortcut for my system monitor which would be Control+Shift+Escape. I haven't found anywhere in the documentation how to, though. How do I do this/is it even possible? If not, I'd really like to see this added.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Advanced-config/#binds

**Comment by EysseW** [comment]
I'm sorry, thanks!
