### ISSUE TITLE
Hyprland crashes when closing WebCord 

### ISSUE THREAD

**Issue by hmd7284** [hyprwm/Hyprland#5673]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
Hyprland, built from branch main at commit 7c3bd4c19fe47f2d92463b81d9b38651b7a1a268  (workspace: Add fullscreen workspace selector (5640)).
Date: Sun Apr 21 07:50:08 2024
Tag: v0.39.1-21-g7c3bd4c1, commits: 4481

flags: (if any)

System Information:
System name: Linux
Node name: ArchLinuxBtw
Release: 6.8.7-tigerlake-xanmod1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 12:47:53 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes when using `killactive` to close WebCord. Can't reproduce with official Discord client or any other window.

### How to reproduce

Using `killactive` on WebCord window

### Crash reports, logs, images, videos

[hyprlandCrashReport719.txt](https://github.com/hyprwm/Hyprland/files/15051747/hyprlandCrashReport719.txt)

**Comment by vaxerski** [comment]
check with above

**Comment by hmd7284** [comment]
It was fixed, thank you
