### ISSUE TITLE
Crash when launching Hyprland

### ISSUE THREAD

**Issue by JohnRTitor** [hyprwm/Hyprland#5675]
### Hyprland Version

<details> <summary>System/Version info</summary>

None, because can't, Hyprland is not running
https://github.com/hyprwm/Hyprland/tree/7c3bd4c19fe47f2d92463b81d9b38651b7a1a268
The build commit is this though.

</details>

### Bug or Regression?

Bug

### Description

As the title suggests, Hyprland is crashing during startup and even manual launch via tty is unsuccessful.

### How to reproduce

Launch Hyprland, fails :(

### Crash reports, logs, images, videos

https://termbin.com/6qkgo from /tmp/hypr

https://termbin.com/c2vq from .cache dir

**Comment by vaxerski** [comment]
dupe #5673
