### ISSUE TITLE
Cant start Hyprland in any way

### ISSUE THREAD

**Issue by HappyCthulhu** [hyprwm/Hyprland#5682]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
[I] user@t-t14 ~ [SIGINT|SIGINT]> sp -Q | grep -i Hyprland
hyprland 0.39.1-5
```

</details>

### Bug or Regression?

Bug

### Description

I created issue earlies: https://github.com/hyprwm/Hyprland/issues/5678.

You told me, that i have outdated version. That was true, i installed new version from Manjaro test repos. Unfortunately, issue persists. Do u have any ideas, why is it happening? Should i provide some extra info for you?

### How to reproduce

1. open Hyprland via display manager or from fish-shell

**Comment by vaxerski** [comment]
crash report please

**Comment by HappyCthulhu** [comment]
> crash report please

```sessions should be nested with care, unset $TMUX to force
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[I] valera@t-t14 ~>
[I] valera@t-t14 ~> removed '/tmp/mcfly.output.Lf2yYQzp'
HYPRLAND_LOG_WLR=1 HHYPRLAND_LOG_WLR=1 Hyprland
Welcome to Hyprland!
[LOG] Instance Signature: fe7b748eb668136dd0558b7c8279bfcd7ab4d759_1713737972
[LOG] Hyprland PID: 302441
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: t-t14
[LOG] Release: 6.1.85-1-MANJARO
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:05:44 UTC 2024


pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
[LOG] GPU information:
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev d1) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG]
Current splash: The AUR packages always work, except for the times they don't.


[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 38.13µs. Estimated average calc time: 0.19µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 16.97µs. Estimated average calc time: 0.23µs.
[LOG] Using config: /home/valera/.config/hypr/hyprland.conf
[LOG] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] [hookSystem] New hook event registered: focusedMon
[LOG] [hookSystem] New hook event registered: preRender
[LOG] Creating the LayoutManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 17.67µs. Estimated average calc time: 0.19µs.
[LOG] Using config: /home/valera/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.73µs. Estimated average calc time: 0.15µs.
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)

```

Is this enough?

**Comment by vaxerski** [comment]
> pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
> amdgpu: amdgpu_cs_ctx_create2 failed. (-13)

this is a problem with your driver / setup

**Comment by HappyCthulhu** [comment]
I saw few Hyperland logs from different users, that has same errors in `pcilib`, `amdgpu`, but they didnt report about any errors. Ok, i will look into it.

Do u think, that both of this errors cause this issue or, maybe, only one of them?

**Comment by vaxerski** [comment]
no clue, never had the problem

**Comment by HappyCthulhu** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3543

`The "amdgpu: amdgpu_cs_ctx_create2 failed. (-13)" message is just amdgpu refusing to create a high-priority context...`

Hmm... Doesnt seem like smth, thats cause this issue. Is there any way to get more detailed debug? This kind of issue should have nice traceback somewhere...

**Comment by frkli1965** [comment]
Experiencing the exact same problem here so somewhat foolhardy to dismiss it so arbitarily imho...

**Comment by vaxerski** [comment]
post a crash report, then.

**Comment by frkli1965** [comment]
For me the error is as follows:-

[wlr] [render/wlr_renderer.c:262] Cannot create Vulkan renderer: disabled at compile-time
[wlr] [render/wlr_renderer.c:203] Failed to create a Vulkan renderer
[wlr] [render/wlr_renderer.c:283] Could not initialize renderer
[wlr] [backend/drm/renderer.c:20] Failed to create renderer
[wlr] [backend/drm/backend.c:226] Failed to initialize renderer
[wlr] [backend/backend.c:263] Failed to create DRM backend
[wlr] [backend/backend.c:274] Could not successfully create backend on any GPU
[wlr] [backend/backend.c:428] Failed to open any DRM device
[CRITICAL] m_sWLRBackend was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!

Unsurprising as I've always had 'WLR_RENDERER=vulkan' set for Sway.

Removing the EV resolved the issue obviously. Still, this has never been a problem, up until a few hours ago.

Did you mean to disable Vulkan?

**Comment by vaxerski** [comment]
vulkan has been fully disabled in hyprland for about a year now. There is no vulkan renderer in hyprland

**Comment by frkli1965** [comment]
Interesting and surprised it hasn't caused any issues until now tbh. Anyway, hope it helps out HappyCthulhu nevertheless.
