### ISSUE TITLE
Hyprland uses the eDp-2 as monitor randomly

### ISSUE THREAD

**Issue by DHWIDSA** [hyprwm/Hyprland#569]
# System Information

OS: Arch Linux
Kernel: 5.19.3-arch1-1
Hybrid graphics, Nvidia and Radeon.
Starting Hyprland via fish shell/greetd

# Steps to reproduce
Log into Hyprland, the monitor is eDp-2 or eDp-1.

# Expected outcome

The built-inmonitor is always eDp-1.

# Noted outcome

After performing a system update, this problem occurred.
The probability of eDp-1 may increase if the network is not available when starting (not sure)

**Comment by vaxerski** [comment]
issue with thy system, Hyprland does not handle monitor naming.
