### ISSUE TITLE
Jetbrains ide quickdocumentation tooltips are in wrong position.

### ISSUE THREAD

**Issue by lluisaliano** [hyprwm/Hyprland#5692]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: ultraluxor
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Jetbrains ide tooltips appear moved to the bottom right of where they should be. I am using xwayland zero rescaling config. I am not using any window rule.

### How to reproduce

Open jetbrains and put the cursor over a method.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/21333617/57a43b52-cb93-4cac-b754-291b7e47652a

**Comment by dnvery** [comment]
Are you using a monitor scaling more than 1?

**Comment by dnvery** [comment]
I have found out that this patch fixes the issue. What does this DELTA variable do? I haven't noticed any problems with the patch applied.
[patch.txt](https://github.com/hyprwm/Hyprland/files/15294984/patch.txt)

**Comment by vaxerski** [comment]
since the monitor is scaled, and the window thinks it's at `logicalPos * scale`, we need to `/scale` any position it requests to go back to our logical coords

**Comment by vaxerski** [comment]
ah, yea, but we already set logical so this is redundant. Correct, mind making a MR?
