### ISSUE TITLE
Pinned windows can not open fullscreen - breaks Firefox

### ISSUE THREAD

**Issue by Root-Core** [hyprwm/Hyprland#5695]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: SimplyRed
Release: 6.8.5-201.fsync.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC TKG Sat Apr 13 04:06:22 UTC 2024


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="Nobara Linux"
VERSION="39 (KDE Plasma)"
ID=nobara
ID_LIKE="rhel centos fedora"
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Nobara Linux 39 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=nobara-logo-icon
CPE_NAME="cpe:/o:nobaraproject:nobara:39"
DEFAULT_HOSTNAME="nobara"
HOME_URL="https://nobaraproject.org/"
DOCUMENTATION_URL="https://www.nobaraproject.org/"
SUPPORT_URL="https://www.nobaraproject.org/"
BUG_REPORT_URL="https://gitlab.com/gloriouseggroll/nobara-images"
REDHAT_BUGZILLA_PRODUCT="Nobara"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Nobara"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

If you have a floating window - picture in picture in this case - and try to open the fullscreen view, nothing happens.

If you do the same with a Firefox window, floating, pinned and click several times, the whole window gets pretty much unusable. If you unfloat, it reacts only sporadically, wrong and fairly broken.

### How to reproduce

Example Firefox:

1. Open some video on Youtube
2. Float window
3. Pin window
4. Click the fullscreen button
5. Unfloat
6. Click the fullscreen button

## Some video on Youtube - the Firefox window is broken after these steps

https://github.com/hyprwm/Hyprland/assets/5329652/872b1be9-c7f3-4654-b874-a7a92ece75fa

**Comment by vaxerski** [comment]
pretty sure this is a firefox bug. Whether its fullscreen requests are honored or not is:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/66fef948-970d-4bb6-9a7e-4bfe7c2a185a)

Firefox seems to not acknowledge rejections

**Comment by Root-Core** [comment]
> pretty sure this is a firefox bug. Whether its fullscreen requests are honored or not is:

Thank you for looking into it.

> Firefox seems to not acknowledge rejections

This may be correct, but the broken window is only one part of this issue.

I would still love to allow pinned windows being able to open fullscreen views. This works pretty well on every DE I tested. Not sure about other tilers though.

**Comment by vaxerski** [comment]
#1147
