### ISSUE TITLE
Allow suppression of resize / move / float

### ISSUE THREAD

**Issue by Root-Core** [hyprwm/Hyprland#5696]
### Description

I'm trying to center Steam's notification windows.
As far as I know, they are just floating windows, which get moved around by Steam.

The problem is, my window rules have no effect on the notifications as the rules are not dynamic and get overridden.

PS: This might also be helpful with issue #5694, as I suspect the window to override everything in a loop.

**Comment by vaxerski** [comment]
Can't be done. Wayland-native windows can't move or resize themselves, so it's a non-issue. X11 windows _can_ do that, and moving them incorrectly is a protocol violation and can lead to nasty side effects like e.g. infinite loops like we had with steam, bringing down the entire compositor.
