### ISSUE TITLE
Feat Req: Window swallowing

### ISSUE THREAD

**Issue by UtkarshVerma** [hyprwm/Hyprland#570]
Would it be possible to have the window swallowing feature in Hyprland?

## What is window swallowing?
Whenever a GUI app is launched through the terminal, the compositor/WM will instantly hide the terminal window and spawn the GUI app window in its place.

## A basic implementation
We can have a window rule for marking a window as a terminal application. Then, whenever such a process tries to spawn another window, we can simply have the new window swallow the terminal window.

## Demo
https://www.youtube.com/watch?v=92uo5OBOKfY

**Comment by NomisIV** [comment]
Personally I use [grouped/tabbed](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#grouped-tabbed-windows) as a solution to window swallowing. However as that solution is not completely perfect, I would prefer proper window swallowing as well.

**Comment by pomarec** [comment]
If i want to open current directory in vscode while i'm in a terminal, i use an alias that runs  `code . & disown && exit`
VSCode opens, my terminal closes. Is it what you're looking for ?

**Comment by vaxerski** [comment]
a97621b1cb203b0e3a7dd07d88c5422b798cbfd8

**Comment by ZacBouh** [comment]
Hi, is it possible to have more info on how the swallow config works ? I have found nothing in the wiki appart from 
enable_swallow and swallow_regex definitions. I have tried googling around but found nothing. So far trying class names as arguments for swallow_regex brought me nowhere

**Comment by ZacBouh** [comment]
> Hi, is it possible to have more info on how the swallow config works ? I have found nothing in the wiki appart from enable_swallow and swallow_regex definitions. I have tried googling around but found nothing. So far trying class names as arguments for swallow_regex brought me nowhere

SOLVED If someone stumbles upon this : contrary to other config options hyprland has to be restarted to take in account the swallow options. 
As an example I had to close and relaunch hyprland for it to take in account the following 
`enable_swallow = true`
`swallow_regex = ^(kitty)$`

**Comment by ZacBouh** [comment]
Well it seems to only partially work, after testing : 
If no instance of google chrome is launched, kitty window is swallowed. 
If i launch a second instance of google chrome kitty window i launch it from is not swallowed.

**Comment by vaxerski** [comment]
yeah no restarting is needed.

Swallowing is very basic, it does not travel the pid tree. The window opened has to be a direct child of the term process for it to work.

**Comment by leiserfg** [comment]
What do you think about a command (or subcommand for hyprctl) to launch an app and swallow the terminal used to call it? that way using a heuristic to find the parent/ filter out children is not required. Something like.

```sh
launch_n_swallow  mpv "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
```

**Comment by SirCartierr** [comment]
> > Hi, is it possible to have more info on how the swallow config works ? I have found nothing in the wiki appart from enable_swallow and swallow_regex definitions. I have tried googling around but found nothing. So far trying class names as arguments for swallow_regex brought me nowhere
> 
> SOLVED If someone stumbles upon this : contrary to other config options hyprland has to be restarted to take in account the swallow options. As an example I had to close and relaunch hyprland for it to take in account the following `enable_swallow = true` `swallow_regex = ^(kitty)$`

Still working as of 2024.

**Comment by ch0ccyra1n** [comment]
> > > Hi, is it possible to have more info on how the swallow config works ? I have found nothing in the wiki appart from enable_swallow and swallow_regex definitions. I have tried googling around but found nothing. So far trying class names as arguments for swallow_regex brought me nowhere
> > 
> > 
> > SOLVED If someone stumbles upon this : contrary to other config options hyprland has to be restarted to take in account the swallow options. As an example I had to close and relaunch hyprland for it to take in account the following `enable_swallow = true` `swallow_regex = ^(kitty)$`
> 
> Still working as of 2024.

I couldn't get it to work at all unfortunately. It would give a config error:

```
Error setting value <^(kitty)$> for field <swallow_regex>: No such field.
Hyprland may not work correctly.
```

I'm really unsure why this is the case.

**Comment by ciesling** [comment]
> I'm really unsure why this is the case.

i feel quite sure this is the case because those two lines of code are just standing as lone single liners in ur .conf right now. These two command MUST be nicely placed under your misc table with like a random single line of a default hyprland command. 

My friend, if you delete the two lines of code where u typed the swallow thingies, you can then change whatever your misc thingy looks like in ur personal hyprland.conf to this friendly one i always use just to enjoy window swallowing in my kitty and alacritty B)

 misc {
    enable_swallow = true
    swallow_regex = ^(kitty)$
    swallow_regex = ^(Alacritty)$
  } 

boom.

ctrl + c

ctrl + shift + v [if big pp]
or ctrl + v into ur window that u edit hyprland.conf with

boom. get swallowed

**Comment by ch0ccyra1n** [comment]
@ciesling thank you so much! It was exactly that!
