### ISSUE TITLE
lastest commit won't build/link 

### ISSUE THREAD

**Issue by alekgr** [hyprwm/Hyprland#5706]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh

```

</details>

### Bug or Regression?

Bug

### Description

489/489] Linking target src/Hyprland FAILED: src/Hyprland c++ -o src/Hyprland src/Hyprland.p/meson-generated_...._protocols_wlr-gamma-control-unstable-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_tearing-control-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_fractional-scale-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_xdg-output-unstable-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_cursor-shape-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_idle-inhibit-unstable-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_relative-pointer-unstable-v1.cpp.o src/Hyprland.p/meson-generated...._protocols_xdg-decoration-unstable-v1.cpp.o src/Hyprland.p/meson-generated.._.._protocols_alpha-modifier-v1.cpp.o src/Hyprland.p/Compositor.cpp.o src/Hyprland.p/config_ConfigManager.cpp.o src/Hyprland.p/debug_CrashReporter.cpp.o src/Hyprland.p/debug_HyprCtl.cpp.o src/Hyprland.p/debug_HyprDebugOverlay.cpp.o src/Hyprland.p/debug_HyprNotificationOverlay.cpp.o src/Hyprland.p/debug_Log.cpp.o src/Hyprland.p/desktop_Constraint.cpp.o src/Hyprland.p/desktop_Popup.cpp.o src/Hyprland.p/desktop_Subsurface.cpp.o src/Hyprland.p/desktop_Window.cpp.o src/Hyprland.p/desktop_WLSurface.cpp.o src/Hyprland.p/desktop_Workspace.cpp.o src/Hyprland.p/events_Devices.cpp.o src/Hyprland.p/events_Layers.cpp.o src/Hyprland.p/events_Misc.cpp.o src/Hyprland.p/events_Monitors.cpp.o src/Hyprland.p/events_Windows.cpp.o src/Hyprland.p/helpers_AnimatedVariable.cpp.o src/Hyprland.p/helpers_BezierCurve.cpp.o src/Hyprland.p/helpers_Box.cpp.o src/Hyprland.p/helpers_Color.cpp.o src/Hyprland.p/helpers_MiscFunctions.cpp.o src/Hyprland.p/helpers_Monitor.cpp.o src/Hyprland.p/helpers_Region.cpp.o src/Hyprland.p/helpers_SdDaemon.cpp.o src/Hyprland.p/helpers_signal_Listener.cpp.o src/Hyprland.p/helpers_signal_Signal.cpp.o src/Hyprland.p/helpers_Timer.cpp.o src/Hyprland.p/helpers_VarList.cpp.o src/Hyprland.p/helpers_Vector2D.cpp.o src/Hyprland.p/helpers_Watchdog.cpp.o src/Hyprland.p/helpers_WLClasses.cpp.o src/Hyprland.p/helpers_WLListener.cpp.o src/Hyprland.p/hyprerror_HyprError.cpp.o src/Hyprland.p/init_initHelpers.cpp.o src/Hyprland.p/layout_DwindleLayout.cpp.o src/Hyprland.p/layout_IHyprLayout.cpp.o src/Hyprland.p/layout_MasterLayout.cpp.o src/Hyprland.p/main.cpp.o src/Hyprland.p/managers_AnimationManager.cpp.o src/Hyprland.p/managers_CursorManager.cpp.o src/Hyprland.p/managers_eventLoop_EventLoopManager.cpp.o src/Hyprland.p/managers_eventLoop_EventLoopTimer.cpp.o src/Hyprland.p/managers_EventManager.cpp.o src/Hyprland.p/managers_HookSystemManager.cpp.o src/Hyprland.p/managers_input_IdleInhibitor.cpp.o src/Hyprland.p/managers_input_InputManager.cpp.o src/Hyprland.p/managers_input_InputMethodPopup.cpp.o src/Hyprland.p/managers_input_InputMethodRelay.cpp.o src/Hyprland.p/managers_input_Swipe.cpp.o src/Hyprland.p/managers_input_Tablets.cpp.o src/Hyprland.p/managers_input_TextInput.cpp.o src/Hyprland.p/managers_input_Touch.cpp.o src/Hyprland.p/managers_KeybindManager.cpp.o src/Hyprland.p/managers_LayoutManager.cpp.o src/Hyprland.p/managers_ProtocolManager.cpp.o src/Hyprland.p/managers_SessionLockManager.cpp.o src/Hyprland.p/managers_ThreadManager.cpp.o src/Hyprland.p/managers_TokenManager.cpp.o src/Hyprland.p/managers_XWaylandManager.cpp.o src/Hyprland.p/plugins_HookSystem.cpp.o src/Hyprland.p/plugins_PluginAPI.cpp.o src/Hyprland.p/plugins_PluginSystem.cpp.o src/Hyprland.p/protocols_AlphaModifier.cpp.o src/Hyprland.p/protocols_CursorShape.cpp.o src/Hyprland.p/protocols_FractionalScale.cpp.o src/Hyprland.p/protocols_GammaControl.cpp.o src/Hyprland.p/protocols_GlobalShortcuts.cpp.o src/Hyprland.p/protocols_IdleInhibit.cpp.o src/Hyprland.p/protocols_RelativePointer.cpp.o src/Hyprland.p/protocols_Screencopy.cpp.o src/Hyprland.p/protocols_TearingControl.cpp.o src/Hyprland.p/protocols_TextInputV1.cpp.o src/Hyprland.p/protocols_ToplevelExport.cpp.o src/Hyprland.p/protocols_WaylandProtocol.cpp.o src/Hyprland.p/protocols_XDGDecoration.cpp.o src/Hyprland.p/protocols_XDGOutput.cpp.o src/Hyprland.p/render_decorations_CHyprBorderDecoration.cpp.o src/Hyprland.p/render_decorations_CHyprDropShadowDecoration.cpp.o src/Hyprland.p/render_decorations_CHyprGroupBarDecoration.cpp.o src/Hyprland.p/render_decorations_DecorationPositioner.cpp.o src/Hyprland.p/render_decorations_IHyprWindowDecoration.cpp.o src/Hyprland.p/render_Framebuffer.cpp.o src/Hyprland.p/render_OpenGL.cpp.o src/Hyprland.p/render_Renderbuffer.cpp.o src/Hyprland.p/render_Renderer.cpp.o src/Hyprland.p/render_Shader.cpp.o src/Hyprland.p/render_Texture.cpp.o src/Hyprland.p/render_Transformer.cpp.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -pie -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/home/alek/.cache/paru/clone/hyprland-git/src=/usr/src/debug/hyprland-git -flto=auto -Wl,--start-group protocols/libserver_protos.a subprojects/wlroots-hyprland/libwlroots.a subprojects/udis86/liblibudis86.a -rdynamic /usr/lib/libwayland-server.so /usr/lib/libwayland-client.so /usr/lib/libdrm.so /usr/lib/libxkbcommon.so /usr/lib/libpixman-1.so -lm -lrt /usr/lib/libEGL.so /usr/lib/libgbm.so /usr/lib/libGLESv2.so /usr/lib/libudev.so /usr/lib/libseat.so /usr/lib/libdisplay-info.so /usr/lib/libliftoff.so /usr/lib/libinput.so /usr/lib/libxcb.so /usr/lib/libxcb-dri3.so /usr/lib/libxcb-present.so /usr/lib/libxcb-render.so /usr/lib/libxcb-render-util.so /usr/lib/libxcb-shm.so /usr/lib/libxcb-xfixes.so /usr/lib/libxcb-xinput.so /usr/lib/libxcb-composite.so /usr/lib/libxcb-ewmh.so /usr/lib/libxcb-icccm.so /usr/lib/libxcb-res.so /usr/lib/libxcb-errors.so /usr/lib/libcairo.so /usr/lib/libhyprcursor.so /usr/lib/libhyprlang.so /usr/lib/libGL.so -pthread /usr/lib/libpango-1.0.so /usr/lib/libgobject-2.0.so /usr/lib/libglib-2.0.so /usr/lib/libharfbuzz.so /usr/lib/libpangocairo-1.0.so -Wl,--end-group /usr/bin/ld: /tmp/ccBjsUJb.ltrans35.ltrans.o: in function CTokenManager::registerNewToken[abi:cxx11](std::any, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)': /usr/src/debug/hyprland-git/Hyprland/build/../src/managers/TokenManager.cpp:17:(.text+0x1284): undefined reference touuid_generate_random' collect2: error: ld returned 1 exit status ninja: build stopped: subcommand failed. ==> ERROR: A failure occurred in build(). Aborting...

### How to reproduce

try to build 

### Crash reports, logs, images, videos

looks like missing a header

**Comment by gksudolol** [comment]
Try https://github.com/hyprwm/Hyprland/commit/5fdd0bceac9b8b60e68635226de57c3d18d0a034

**Comment by viicslen** [comment]
> Try [5fdd0bc](https://github.com/hyprwm/Hyprland/commit/5fdd0bceac9b8b60e68635226de57c3d18d0a034)

How do I use that commit instead of version 0.39.1?

**Comment by gksudolol** [comment]
Not sure what package manager you're using, but on Gentoo I do an override like `EGIT_OVERRIDE_COMMIT_HYPRWM_HYPRLAND="commit"`

On Arch I'm guessing you pull from AUR and pin the commit in PKGBUILD? Then do a makepkg etc

Or just yay/paru hyprland-git

**Comment by viicslen** [comment]
Oh sorry about that, Im using Nix
