### ISSUE TITLE
Cursor with random movements while gaming

### ISSUE THREAD

**Issue by RochaLAJ** [hyprwm/Hyprland#571]
**Steps to reproduce**
- Start Hyprland
- Open Final Fantasy XIV or Age of Empires II DE

**Expected Outcome**
Cursor respect my mouse

My desktop experience do not show the same behavior, however, when i open FFXIV, the cursor moves by itself to the right or left corner when i click. When i try to play Age of Empires 2 DE, my cursor is not able to click anything, i always need to move further to the left or right...for a RTS it's unplayable. The game is not launching with gamescope and i know that is not Hyprland fault this part. 
The same behavior is not happening on Wayfire, KDE or Gnome. Only hyprland.

input configs
```
input {
    kb_layout=br
    kb_variant=
    kb_model=abnt2
    kb_options=terminate:ctrl_alt_bksp
    kb_rules=evdev
    follow_mouse=0
    force_no_accel=true
}

input type:pointer {
    accel_profile flat
    
}

general {
	sensitivity=0.85 # for mouse cursor
    main_mod=SUPER
    gaps_in=5
    gaps_out=25
    border_size=4
    col.active_border=0x99ee2596be
    col.inactive_border=0x66333333
    apply_sens_to_raw=0 
    damage_tracking=full 
}

```

**Comment by vaxerski** [comment]
```
input type:pointer {
    accel_profile flat
}
```

how is this valid?

```
sensitivity=0.85
```
try making this 1 and using libinput sensitivity instead. (input:sensitivity, 0 is normal, -1.0 - 1.0)

**Comment by RochaLAJ** [comment]
**AOE2 is fixed**,  weird movement to the corner still persist on FFXIV. 

> ```
> input type:pointer {
>     accel_profile flat
> }
> ```
> 
> how is this valid?
> 
> ```
> sensitivity=0.85
> ```
> 
> try making this 1 and using libinput sensitivity instead. (input:sensitivity, 0 is normal, -1.0 - 1.0)

**Comment by RochaLAJ** [comment]
Issues seems solved (played 1 match AoE II DE and FFXIV for 20min)
Wrong structure  of conf file.

**Comment by BrodieRobertson** [comment]
I've been experiencing the same problem with the camera moving at what seems like entirely random intervals when I click.

Version: hyprland-0.23.0beta-2

Input configuration:
```
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    numlock_by_default = true

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
```

Demonstration:

https://user-images.githubusercontent.com/30792656/227756223-270c35a6-5e99-4327-9445-a8e48139e04c.mp4

I've not moved my mouse at all, just clicked and the camera snaps up

**Comment by vaxerski** [comment]
what game is that?

wine? xwayland?

**Comment by BrodieRobertson** [comment]
That's Final Fantasy XIV running through Wine

**Comment by vaxerski** [comment]
have you tried launching it in wine virtual desktop mode?
