### ISSUE TITLE
Resizewindowpixel dispatcher is broken

### ISSUE THREAD

**Issue by v4u6h4n** [hyprwm/Hyprland#5710]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: desktop-0
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
13:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The resizewindowpixel dispatcher only seems to correctly resize height, and incorrectly resizes width, and when executed multiple times increases the width indefinitely. Possible a duplicate of #4047.

### How to reproduce

`hyprctl dispatch "resizewindowpixel exact 100 100,pid:<pid>"`

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/156973064/889511ac-aafe-4e98-832b-da7f593974e3

**Comment by v4u6h4n** [comment]
Okay so it seems to only working correctly with floating windows. Is it intended to work for tiled windows as well or is it just not documented correctly in the wiki?

**Comment by vaxerski** [comment]
IIRC it wasn't designed for tiled... but I am unsure

**Comment by v4u6h4n** [comment]
Yeah it seems like when its used with tiled windows it just adds/subtracts height/width. Just added a feature request for it to be extended to tiled windows as well: #5739.

**Comment by vaxerski** [comment]
I'll close this then
