### ISSUE TITLE
Firefox client window does not update properly

### ISSUE THREAD

**Issue by Agent00Ming** [hyprwm/Hyprland#5711]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit cf3596a96d5c1012c363d8243baca6431ecf835b dirty (renderer: avoid rendering frame if finalDamage is empty).
Date: Tue Apr 23 07:29:01 2024
Tag: v0.39.1-58-gcf3596a9, commits: 4518

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

Trying to reload a webpage or clicking a link within a website causes the window to lock at the last frame before loading is done until a window focus change. (i.e. moving mouse to a terminal window on the side)

### How to reproduce

Build Hyprland with this commit `cf3596a96d5c1012c363d8243baca6431ecf835b` (the one that introduces this issue). 
Use Firefox as one would normally use a browser and experience the lock ups because the client window cannot update.

EDIT: oops, copied the wrong commit hash

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15078372/patch.txt)

try this one

**Comment by vaxerski** [comment]
[patch2.txt](https://github.com/hyprwm/Hyprland/files/15078604/patch2.txt)
alternative

**Comment by Agent00Ming** [comment]
patch works

**Comment by vaxerski** [comment]
which

**Comment by Agent00Ming** [comment]
both patches work without any significantly visible differences
