### ISSUE TITLE
initial_workspace_tracking=true causes new windows to not gain focus

### ISSUE THREAD

**Issue by heather7283** [hyprwm/Hyprland#5712]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit aab1df50abbf2cd3da7837e7b457b943907a0b3e  (CI: add no PCH build (5708)).
Date: Tue Apr 23 12:02:51 2024
Tag: v0.39.1-56-gaab1df50, commits: 4516

flags: (if any)


System Information:
System name: Linux
Node name: FA506IH
Release: 6.8.7-arch1-1-FA506IH
Version: #1 SMP PREEMPT_DYNAMIC Thu, 18 Apr 2024 17:12:00 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f99] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

Before the commit that added `initial_workspace_tracking` option, I was able to launch windows that immediately gain focus with `stayfocused` rule. But now with `initial_workspace_tracking` option set to `true`, windows don't gain focus anymore until I move my mouse or focus them manually.

### How to reproduce

Easiest way to reproduce this:
1. run `hyprctl dispatch exec \[stayfocused\] -- foot` from your shell
2. observe foot window not being focused

### Crash reports, logs, images, videos

Video:
https://files.catbox.moe/05q3hp.webm

**Comment by tchofy** [comment]
Can confirm above commit fixes this particular issue, but seems like there's still another one with special workspaces where focus sticks with the current workspace until the cursor is moved, and trying to open new windows will open them in the current workspace instead of special.
