### ISSUE TITLE
When a window is moved to another workspace, `m_pWorkspace` is updated at the wrong time

### ISSUE THREAD

**Issue by HardGraphite** [hyprwm/Hyprland#5714]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: Chartreux
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Bug or Regression?

Bug

### Description

When a non-floating window is to be moved to another workspace, `CCompositor::moveWindowToWorkspaceSafe()` is called. In this function, the following steps are done in order :

1. `CWindow::moveToWorkspace()` is called to update window state *(LINE 2703)*
2. `IHyprLayout::onWindowRemovedTiling()` is called so that the layout knows the window is removed from the old workspace *(LINE 2706)*
3. the window's `m_pWorkspace` and `m_iMonitorID` members are updated *(LINE 2707-2708)*
4. `IHyprLayout::onWindowCreatedTiling()` is called so that the layout knows the window is added to the new workspace *(LINE 2709)*

https://github.com/hyprwm/Hyprland/blob/cf3596a96d5c1012c363d8243baca6431ecf835b/src/Compositor.cpp#L2703-L2710

However, in **step 1**, the function `CWindow::moveToWorkspace()` already updates window's `m_pWorkspace` to the new value, which should be done later in **step 3**. This results in `IHyprLayout::onWindowRemovedTiling()` not being able to obtain the correct value of `m_pWorkspace` in **step 2**.

https://github.com/hyprwm/Hyprland/blob/cf3596a96d5c1012c363d8243baca6431ecf835b/src/desktop/Window.cpp#L397

### How to reproduce

*(see the previous section)*

**Comment by vaxerski** [comment]
nice catch, thanks
