### ISSUE TITLE
Hyprland error banner causes major problems when trying to fix the error

### ISSUE THREAD

**Issue by Silverdev2482** [hyprwm/Hyprland#5723]
### Hyprland Version

Hyprland, built from branch  at commit cdcc5aba06f20005842cf966b23af50456dc7142  ().
Date: 2024-02-17
Tag: 

flags: (if any)

System Information:
System name: Linux
Node name: T480
Release: 6.7.4
Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Feb  5 20:17:12 UTC 2024

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240217.dirty"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

plugins:

### Bug or Regression?

Bug

### Description

The error banner are a major problem, when I get an error I will try to go to the wiki or search the web for other advice, however it is insanely hard to obtain the information needed to fix the config error when part of your screen is dead.

At this point your system is a pain to operate. You either need to know a terminal based web browser, have a different computer, or suffer through using a web browser and terminal with the top half cut off. You can't easily resize windows to not be in the area where the error is, only tiling it to the bottom left or right quarter of your screen. 

Potential solutions 1: closable error
- This would fix the problems, but it may lead to people ignoring the error.
- It also would be a nuisance to get the log pulled up to look at the error once closed.

Potential solution 2: Error displaces windows
- This would make it so windows simply would be shrunk, instead of being overlapped by the error. 
- It would make people not ignore the error, while not being a major problem while searching for a solution.
- It would make the error easy to look at to fix
- The error may still be a problem in insanely low resolutions, however a very small amount of people would be affected by this.

### How to reproduce

Do any config change that causes an error

**Comment by vaxerski** [comment]
why is the small banner such an issue to you? Why can't you float a window out of the way?

**Comment by jernejmarcic** [comment]
If you have a hard time navigating with the banner I would suggest you just to go the config and comment out wahtever Hyprland is telling you is casing the error and then search for a solution.
I never had a config error or update break the (bare) functionality of Hyprland for me

**Comment by SoSeDiK** [comment]
The banner may cover the task bar (e.g. waybar), making it unusable. I can see how this can be an inconvenience, especially on NixOS when using hm flake with plugins since each Hyprland update leads to version mismatch banner constantly flashing on top of the screen, which e.g. blocks GUI access to logout, forcing to use hotkeys (and hotkeys are interrupted by the banner, which is also quite annoying).

**Comment by Silverdev2482** [comment]
I never used float so that did not occur to me to do that, I will do that from now on. As for why the small banner is an issue, it covers all tabs in a web browser making it a massive pain to navigate. Terminals are so bad but still annoying, but web browsers are almost unsuable.

**Comment by jernejmarcic** [comment]
FYI you can use CTRL+T to open new tabs in browsers and use ALT+1-9 to navigate tabs, at least on firefox

**Comment by Silverdev2482** [comment]
I have had plenty of syntax error that can't simply be commented out. Hotkeys for firefox are probably a good idea to use but I don't see a good reason for the errors to not displace windows.

**Comment by Root-Core** [comment]
> I have had plenty of syntax error that can't simply be commented out.

Why not? You also could rename the file, which is like commenting out the whole file.

----------

Another potential solution:

Make the banner transparent when the mouse hovers over it and make it click through.

**Comment by Silverdev2482** [comment]
I didn't know it was a syntax error in the first place. idk how that bracket got deleted, strikes me as really odd, maybe I fat fingered in vim and didn't notice, until the next nixos-rebuild, idk. Still I'd rather just get to fixing the problem instead of pushing it out of the way so I can learn to fix it.

**Comment by Silverdev2482** [comment]
transparency is also a good idea though

**Comment by AERDU** [comment]
Is it possible to create another layer for the error box? I kind of remember i3 solving this by giving the error box its own area, almost like how a status bar would operate. Are there no option for this with the layers listed in ```hyprctl layers```? Would implementing it be needlessly complex?

**Comment by vaxerski** [comment]
thanks, forgot this #.
