### ISSUE TITLE
Bind mouse action without mouse-click (touch-pad freandly)

### ISSUE THREAD

**Issue by 6543** [hyprwm/Hyprland#5727]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: PC
Release: 6.8.4-artix1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 13:31:34 +0000


GPU information:
0d:00.0 VGA compatible controller [0300]: Intel Corporation DG2 [Arc A750] [8086:56a1] (rev 08) (prog-if 00 [VGA controller])


os-release: NAME="arch"
PRETTY_NAME="Artix Linux x86_64"
ID=arch
BUILD_ID=rolling


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I did try this config:
```
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod ALT, , movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod CTRL, , resizewindow
```

to be able to use the keyboard instead of an mouse click, this would make working with touch-pads easy (at the moment it's hard to use, as one hand has to click and move on it)

### How to reproduce

well apply the config I guess?!?

### Crash reports, logs, images, videos

I expect the window to resize/move but it does not ...

**Comment by 6543** [comment]
well I guess it also could be an feature request ... but in that case I would expect hyprland to at least tell me that the config in my current state is not valid. or that move-/resizewindow actions do not jet suport click-less ...

hope that pelps ;)

PS: it it could be done already I'm sorry and happy to hear how it should be done - thanks for your patience with me :)

**Comment by The-Briel-Deal** [comment]
I'll take this on and keep this ticket updated! I'm guessing it won't be the hardest thing to add lol (we'll see if thats true :laughing: )

**Comment by The-Briel-Deal** [comment]
I have good and bad news mr. @6543 . The good news is, this does work lol, your format is just wrong haha. The bad news is, I don't get to fix this bug ):

Anyway! Try this:

```
bindm = $mainMod,N,movewindow
or
bindm = $mainMod CTRL,J,movewindow
```

The reason your format doesn't work is because there is nothing after the mod. You can do a normal key without a mod, but you can't do a modkey without a normal key. I'm guessing there is a way around this but I think they are grouped into two different buckets. Maybe try figuring out the modkeys keycode and put it after the first comma and maybe that will work?

LMK if you need anything else! Thanks for the report though!

**Comment by thejch** [comment]
to use the ctrl key as a normal key do
`bindm = $mainMod, Control_L , resizewindow`

**Comment by 6543** [comment]
uh thanks that helped :)

in the end it was an **user error** in the end :)

I guess I could add this solution into the wiki for others who have a touchpad too (as an idea/suggestion)

**Comment by The-Briel-Deal** [comment]
Totally! I agree that adding this to the wiki would be useful! And NP 6543! Everyone makes mistakes and it wasn't super clear.

**Comment by 6543** [comment]
https://github.com/hyprwm/hyprland-wiki/pull/615
