### ISSUE TITLE
Make exit dispatch canceable

### ISSUE THREAD

**Issue by Micovec** [hyprwm/Hyprland#5728]
### Description

I've been using Hyprland for about a year now and during that time it accidentally happened several times that I quit session without saving work I had done. Most of apps use caching and save periodically but some do not. In those cases I lost all unsaved changes (mostly all of the work because I'm spoiled by apps that use cache and don't save until I close apps manually).

So I think that exit dispatch could use an additional bool parameter to determine if the dispatch is canceable. If true call EMIT_HOOK_EVENT_CANCELLABLE so that plugins can catch that event and potentially cancel it.

Personally I'd use it to show a dialog if the user wants to exit the session if there are open apps.

I use wlogout and could call a script that would behave exactly as described but that isn't the right solution. There could be other ways to exit such as plugins, programs or key binds.

**Comment by vaxerski** [comment]
........why not just instead of `dispatch exit` call your "are you sure" app??

**Comment by Micovec** [comment]
> I use wlogout and could call a script that would behave exactly as described but that isn't the right solution. There could be other ways to exit such as plugins, programs or key binds.

This is why. Other programs, plugins etc.

**Comment by vaxerski** [comment]
why should they call `exit` though?

**Comment by Micovec** [comment]
Because that's the only way to exit the session (I think?)

**Comment by thejch** [comment]
> Personally I'd use it to show a dialog

are you saying you want the compositor to include a gui app that lets you confirm before exiting?

**Comment by Micovec** [comment]
> are you saying you want the compositor to include a gui app that lets you confirm before exiting?

No. Just have a cancel-able exit dispatch.

To clarify the scenario I'm imagining:

1. I call `hyprctl dispatch exit true`
2. A cancel-able hook event i emitted.
3. A plugin could cancel this event based on some criteria (in my case there's an open app) and show a gui app (or do something else)
4. If the user really wants to exit the session gui app calls `hyprctl dispatch exit false` (or just without the last arg)
5. Hyprland exits the old way (without any questions asked)

It doesn't matter what exactly gets called. If it is `hyprctl dispatch exit true` or if there's some other way to call the dispatcher.

Also it

**Comment by zakk4223** [comment]
This feels like plugin territory. Hook the exitHyprland() function, do whatever you want for a confirmation dialog and  then just set the m_bExitTriggered flag if the user confirms. Probably just add another dispatcher like 'reallexitconfirmed' and have it set the exit flag, so you can just use external programs for the confirmation dialog.

It's a fairly trivial plugin to write, other than having to provide some sort of default confirmation dialog I guess. 

Or just do what Vaxry says and configure your stuff to call the script. Nothing should be causing exit in a sneaky way; there's only one path to that condition in the code. Keybinds are user configurable; if a plugin is just calling exit without you being able to prevent that then maybe look into wtf that plugin is doing etc...

**Comment by thejch** [comment]
i still dont get what the difference it makes if you just dont call exit and instead call something that lets you confirm beforehand?
unless some app that you're using is hardcoded to be calling exit instead of letting you configure that. in that case, even with the suggestion from your comment above:
> If the user really wants to exit the session gui app calls hyprctl dispatch exit false (or just without the last arg)

that app would just still call exit (false) and it would just be the exact same thing?

**Comment by The-Briel-Deal** [comment]
Yea I got around this by just adding another mod key in my keybind, like SUPER SHIFT, M. Making a shell script that prompts you to run a command should be pretty easy.

Otherwise, just comment out the bind lol. This is definitely out of scope for a compositor imo.

**Comment by Micovec** [comment]
> i still dont get what difference it makes if you just dont call exit and instead call something that lets you confirm beforehand?

Because from a programming perspective I don't believe that's the right approach to cancel a Hyprland's exit call. If I want to interrupt session exit in any way it should be on the lowest possible level so that when there are other ways to call exit I should be able to interrupt them aswell.

**Comment by thejch** [comment]
imo thats the exact correct approach though, it's not cancelling because you're not initiating the cleanup procedure in the first place (which is good). and you shouldn't be interrupting the exit procedure because that's totally dangerous and not a good idea unless you wanna end up having clients half killed, stuff half destroyed, and maybe xwayland server half hanging or some other unexpected things

**Comment by Micovec** [comment]
Yes I agree on the cleanup stuff that's why I suggested to be able to interrupt the exit dispatcher, right before any cleanup happens.

In `CKeybindManager::exitHyprland` before the `m_bExitTriggered` gets set if there would be something like this:

```cpp
if (args[0] == "true") {
    EMIT_HOOK_EVENT_CANCELLABLE("exit", &event);
}
...
}
```

then no cleanup procedure would start and the behaviour would be save. As you mentioned no clients half killed etc.

**Comment by Micovec** [comment]
I see that this feature request doesn't get much support so I'm closing the issue and instead will be creating something similar to what @zakk4223 suggested with that plugin approach.

When I'm done with that I'll probably post a link to the solution I came up with so that other people that stumble across similar problem can use it to solve this.
