### ISSUE TITLE
`kitty --single-instance` launching in old workspace

### ISSUE THREAD

**Issue by nik012003** [hyprwm/Hyprland#5732]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 34413d1f367b56e17614ee0455b6bf0b61a5aed1  ().
Date: Tue Apr 23 13:05:56 2024
Tag: , commits: 4523

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.6.3-414.asahi.fc39.aarch64+16k
Version: #1 SMP PREEMPT_DYNAMIC Sun Mar 24 19:44:17 UTC 2024


GPU information: 


os-release: NAME="Fedora Linux Asahi Remix"
VERSION="39 (Thirty Nine)"
ID=fedora-asahi-remix
ID_LIKE=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux Asahi Remix 39 (Thirty Nine)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora-asahi-remix:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedora-asahi-remix.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://discussion.fedoraproject.org/c/neighbors/asahi/asahi-help/94"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

`kitty --single-instance` launches a window in the old workspace instead of the current one. It did work in a previous version (~2 days ago, can't git bisect it rn, sowwy)

### How to reproduce

Add a bind to kitty: `bind=SUPER,RETURN,exec,kitty --single-instance`
Open kitty with the bind
move to a different workspace
try to open kittty again (nothing shows up)
go back to previous workspace, you'll have 2 kitty windows

**Comment by tchofy** [comment]
Most likely started since 29308b94ca2d95597b3c4e3ac1d3edbcd2f23cdd, it introduces the `misc:initial_workspace_tracking` setting that is enabled by default. Yoinking vaxry's announcement on discord:

```
It makes your apps open on the workspace they were opened on. For example:
- you open a launcher and launch an app on workspace 1
- you switch to workspace 2 before it opens
- the app will now open on workspace 1 regardless
```

Since there's only an on/off setting right now, what's happening is that the first kitty terminal on workspace 1 has the same token as any other kitties spawned on any other workspace, so I'd recommend disabling it for now until the feature is made more configurable.
