### ISSUE TITLE
bind=ALT,RETURN,exec,alacritty closes hyprland

### ISSUE THREAD

**Issue by GloriousWizard** [hyprwm/Hyprland#574]
Distro: Nobara release 36
Kernel: 5.18.18-201.fsync.fc36.x86_64
GPU: Radeon Vega 6

It didn't crash hyprland, only closed it since coredumpctl didn't provide anything. I've done a git bisect and this is the faulty commit cc3f0ff9e7906bff60a041fc5556e7c5cbd71df5.

[logfile](https://github.com/hyprwm/Hyprland/files/9417655/hyprland.txt)
[config](https://github.com/hyprwm/Hyprland/files/9417667/hyprland_config.txt)

**Comment by vaxerski** [comment]
Nobara again. I will throw it into the "nobara" basket. The only thing I've heard about this distro is in the crash reports.

Since the faulty commit is a wlroots dep update, it's either wlr or your distro, with me leaning towards the latter as nobody else has those issues.
