### ISSUE TITLE
windowrulev2 title matching initialTitle

### ISSUE THREAD

**Issue by apelloni** [hyprwm/Hyprland#5744]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: qfwfq
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I wanted to make some windows from betterbird as float and I've noticed that I have to match the content of `initialTitle` instead of `title` when writing:
```
windowrulev2 = float,class:^(betterbird)$,title:(.*)(Edit Item)(.*)
```
The output of `hyprctl clients` gives:
```
Window 57a6ec0b3460 -> New Event::
	mapped: 1
	hidden: 0
	at: 673,260
	size: 574,680
	workspace: 5 (5)
	floating: 1
	monitor: 0
	class: betterbird
	title: New Event:
	initialClass: betterbird
	initialTitle: Edit Item
	pid: 571118
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 1
```
When trying to use the correct `title` entry for the matching (i.e. `New Event:`) it fails to make it float,

I've seen similar things in https://github.com/hyprwm/Hyprland/issues/5550 with the problem happening in the opposite direction

### How to reproduce

Trying to match the `title` entry instead of the `initialTitle` when the two are different

**Comment by vaxerski** [comment]
that's expected, because float is a static windowrule. https://wiki.hyprland.org/Configuring/Window-Rules/

**Comment by Red007Master** [comment]
> ### Hyprland Version
> System/Version info
> ### Bug or Regression?
> 
> Bug
> ### Description
> 
> I wanted to make some windows from betterbird as float and I've noticed that I have to match the content of `initialTitle` instead of `title` when writing:
> 
> ```
> windowrulev2 = float,class:^(betterbird)$,title:(.*)(Edit Item)(.*)
> ```
> 
> The output of `hyprctl clients` gives:
> 
> ```
> Window 57a6ec0b3460 -> New Event::
> 	mapped: 1
> 	hidden: 0
> 	at: 673,260
> 	size: 574,680
> 	workspace: 5 (5)
> 	floating: 1
> 	monitor: 0
> 	class: betterbird
> 	title: New Event:
> 	initialClass: betterbird
> 	initialTitle: Edit Item
> 	pid: 571118
> 	xwayland: 0
> 	pinned: 0
> 	fullscreen: 0
> 	fullscreenmode: 0
> 	fakefullscreen: 0
> 	grouped: 0
> 	swallowing: 0
> 	focusHistoryID: 1
> ```
> 
> When trying to use the correct `title` entry for the matching (i.e. `New Event:`) it fails to make it float,
> 
> I've seen similar things in #5550 with the problem happening in the opposite direction
> ### How to reproduce
> 
> Trying to match the `title` entry instead of the `initialTitle` when the two are different
> ### Crash reports, logs, images, videos
> 
> _No response_

Was you able to achieve changes to "static rules" after window creation?
If yes - how?



As someone coming from KDE and having great general experience, only strange decisions like this and wiki that tells you to use deprecated stuff cause displeasure.
