### ISSUE TITLE
movetoworkspace breaks things

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/Hyprland#5746]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit ecf282d331a8aa19c0fe10c739cd31d3b3ab64a2  (wlr-foreign-toplevel: move to new impl).
Date: Thu Apr 25 03:10:43 2024
Tag: v0.39.1-77-gecf282d3, commits: 4537

flags: (if any)


System Information:
System name: Linux
Node name: localhost
Release: 6.8.7-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:33 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Moving a window using the `movetoworkspace` dispatcher breaks window resizing. In addition, I noticed that the compositor no longer follows the moved window.

### How to reproduce

1. Move the window to another workspace using the `movetoworkspace` dispatcher.
2. Try opening a window next to the moved window.
3. The moved window no longer changes its geometry and the newly opened window appears inside the moved window.

**Comment by Agent00Ming** [comment]
> [LOG] [ForeignToplevelWlr] Newly mapped window 00005d0bdc0f50b0

New window is created.

> [LOG] Removing last node (dwindle)
> [ERR] Listener 102305360579856 timed out and was killed by Watchdog!!!

`movetoworkspace` dispatcher is called on that window.

> [LOG] Destroying workspace ID 4

Checking on the window because the workspace wasn't switched when `movetoworkspace` was called.
The window is in a weird floating state (was tiling before).

> [LOG] OPENINGON: [Node nullptr], Monitor: 0
> [LOG] Removing last node (dwindle)

You can only interact with the window using mouse binds once (resize or drag).

> [ERR] Dragging attempted on an invalid window!
> [ERR] Dragging attempted on an invalid window!
> [ERR] Dragging attempted on an invalid window!

Subsequent attempts to interact with the window using mouse binds.

**Comment by vaxerski** [comment]
> [ERR] Listener 102305360579856 timed out and was killed by Watchdog!!!

this is prolly what went wrong...

**Comment by vaxerski** [comment]
can't repro, tho. can I get a git bisect?
