### ISSUE TITLE
External monitor freezes and possible deadlock

### ISSUE THREAD

**Issue by guilhermehubner** [hyprwm/Hyprland#5747]
### Hyprland Version

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

System Information:
System name: Linux
Node name: hades
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000

GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28e0] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

I use a docked notebook mostly with the lid down. Randomly the external monitor freezes. When I open the lid, everything is working on the built-in monitor, although if I fire any hyprctl command everything freezes (deadlock) the same happens if I try shutting down or rebooting, leading me to force it with the power buttom.

I am running arch linux, and hyprland v0.39.1 (from pacman).

### How to reproduce

It happens randomly, I couldn't find the action that triggers the problem, unfortunately.

**Comment by gulafaran** [comment]
i think this is just nvidia, https://forums.developer.nvidia.com/t/external-monitor-freezes-when-using-dedicated-gpu/265406/1
