### ISSUE TITLE
Gnome Network Display support

### ISSUE THREAD

**Issue by 95lux** [hyprwm/Hyprland#5754]
### Description

I would love to use [gnome-network-displays](https://github.com/GNOME/gnome-network-displays) with hyprland, to use my Android tablet as a second monitor. It relies on mutter. 
Is it even possible to make it work with hyprland in theory?

**Comment by vaxerski** [comment]
In theory yes, but first, it relies on the gnome desktop portal, and second, I am not planning on supporting 3rd party portals
