### ISSUE TITLE
Only Recognizing One External Display After Nvidia Driver Update

### ISSUE THREAD

**Issue by ToolmanP** [hyprwm/Hyprland#5755]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: TWorkstation
Release: 6.8.7-200.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:35:11 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28e0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev d8) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

</details>

### Bug or Regression?

Regression

### Description

Sadly still , i am using a nvidia card on my laptop with no choice.  I got a hdmi port and a type-c dp display hooked to my laptop.So after I upgraded the driver to 550.76 driver only one display can have graphics on it another one went pure black.
However, hyprctl does show that hyprland does recognize the monitor but just have no display?
I'm also having a gnome environment installed but all displays work fine as usual. Maybe a wlroots issue? So I'm assuming this as a regression issue.

If possible, can i have more detailed logging to figure out the problems?

### How to reproduce

Installed nvidia 550.76 and attach two displays on it.

**Comment by vaxerski** [comment]
I can't help with nvidia drivers

**Comment by ToolmanP** [comment]
For anyone who has similar problems, it was caused by an issue in power management of the driver. Downgrading to 550.67 solves the problem.
