### ISSUE TITLE
Maximise Sole Window

### ISSUE THREAD

**Issue by rraafays** [hyprwm/Hyprland#5756]
### Description

The only thing that I think Hyprland needs to make it absolutely perfect in my opinion is an option that can be enabled which will automatically fullscreen / maximise with 0 gaps a window when it is the only window in the current workspace and then break out of fullscreen once a new window is introduced

**Comment by gksudolol** [comment]
Yeah. It's called `no_gaps_when_only` if you put your glasses on and [read](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config) the [wiki](https://wiki.hyprland.org/Configuring/Master-Layout/#config)

**Comment by vaxerski** [comment]
worth noting no_gaps_when_only is deprecated in favor of just workspace rules
