### ISSUE TITLE
Chromium-Based Apps Produce Empty Window

### ISSUE THREAD

**Issue by kabeleh** [hyprwm/Hyprland#5757]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1d40af64d352bd5a87c7d53a52707fc5cfc6940e  (text-input-v3: move to new impl).
Date: Thu Apr 25 23:27:44 2024
Tag: v0.39.1-83-g1d40af64, commits: 4543

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.8.7-arch1-1.1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 18 Apr 2024 09:30:31 +0000


GPU information: 
0c:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [GeForce RTX 3060] [10de:2503] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

An update within the last ~48 hours caused chromium based apps like Google Chrome or Vivaldi to just produce an empty window. The border decorations and blur works as normal, but the window is just empty.

### How to reproduce

Run a chromium-based application like Google Chrome or Vivaldi.

### Crash reports, logs, images, videos

[hyprland.txt](https://github.com/hyprwm/Hyprland/files/15129421/hyprland.txt)

**Comment by vaxerski** [comment]
use the search feature please #5658

**Comment by kabeleh** [comment]
For others stumbling upon this:

1. Launch your chromium-based browser with the `--no-experiments` flag
2. Open vivaldi://flags/#ozone-platform-hint and set it to X11
