### ISSUE TITLE
Setting gestures cause Hyprland session crash and logout

### ISSUE THREAD

**Issue by ShiaHp** [hyprwm/Hyprland#5758]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
Hyprland, built from branch main at commit 9e4b2efe7e24f7b21faefbd50a88f25b5185bc35  (cmake: Some small cmake cleanups (5572)).
Date: Sat Apr 13 20:40:28 2024
Tag: v0.38.0-107-g9e4b2efe, commits: 4440

flags: (if any)


System Information:
System name: Linux
Node name: shiawase
Release: 6.6.28-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 10:11:09 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f91] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

While testing some settings in Hyprland's gestures, I  set 'workspace_swipe_distance' to 0. When I attempted to swipe to another workspace, a bug occurred, causing the Hyprland session to crash and log me out.### 

### How to reproduce

Set "workspace_swipe_distance" to 0
My current conf:
gestures {
    workspace_swipe = true
    workspace_swipe_distance = 700
    workspace_swipe_fingers = 3
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true
}

### Crash reports, logs, images, videos

[hyprlandCrashReport48860.txt](https://github.com/hyprwm/Hyprland/files/15133226/hyprlandCrashReport48860.txt)

**Comment by vaxerski** [comment]
if you set workspace_swipe_distance to something that isn't zero does it still happen?

**Comment by ShiaHp** [comment]
Trying with 100 work fine but -100 still cause the crash happen
