### ISSUE TITLE
No CWLSurface for surface in damageSurface

### ISSUE THREAD

**Issue by SoulHarsh007** [hyprwm/Hyprland#5759]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d9ec2785cb7f6493576232057752688e57925655 dirty (wlr-foreign-toplevel: send done after property changes).
Date: Fri Apr 26 17:44:50 2024
Tag: v0.39.1-84-gd9ec2785, commits: 4544

flags: (if any)


System Information:
System name: Linux
Node name: SoulHarsh007
Release: 6.8.7-2-cachyos-echo
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 17:29:46 +0000


GPU information: 
10:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK208B [GeForce GT 730] [10de:1287] (rev a1) (prog-if 00 [VGA controller])
30:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

`hyprland.log` includes alot of messages like:
```log
[ERR] BUG THIS: No CWLSurface for surface in damageSurface!!!
```

### How to reproduce

1. Add apps like `swww`, `nwg-drawer` to exec-once in `hyprland.conf`
2. check `hyprland.log`, it should include similar error messages.

### Crash reports, logs, images, videos

No crash report, but log from a running instance: 
hyprland.log: [hyprland.log](https://github.com/hyprwm/Hyprland/files/15133797/hyprland.log), web preview: https://paste.soulharsh007.dev/p/885b29e.log

relevant `hyprland.conf` snippet: https://git.soulharsh007.dev/soulharsh007/dots/src/branch/main/hypr/exec/exec.conf

**Comment by vaxerski** [comment]
:(

**Comment by SoulHarsh007** [comment]
With nwg-bar it shows just once, with swww it shows multiple times.

**Comment by SoulHarsh007** [comment]
Not sure if this helps, but here it is:
`hyprland.log` with just `nwg-drawer` in my exec-once: [hyprland.log](https://github.com/hyprwm/Hyprland/files/15134354/hyprland.log), web preview: https://paste.soulharsh007.dev/p/8253cae.log

`hyprland.log` with just `swww init` in my exec-once: [hyprland.log](https://github.com/hyprwm/Hyprland/files/15134358/hyprland.log), web preview: https://paste.soulharsh007.dev/p/7ad7900.log

**Comment by Agent00Ming** [comment]
try 5edc32930d85f5f481160b938965c8bc329487e7, the ERR log message and orphaned node messages are gone for me

**Comment by SoulHarsh007** [comment]
:tada: I can confirm that the messages are gone in the latest commit (I am on: 1237732b97fcf21a19aed16f2ef966118a3ca2aa).
