### ISSUE TITLE
lastest commit doesn't build

### ISSUE THREAD

**Issue by alekgr** [hyprwm/Hyprland#5760]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

udis86| CMake configuration: SUCCEEDED
udis86| CMake project udis86  has 3 build targets.
udis86| Generated Meson AST: /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/build/subprojects/udis86/meson.build
udis86| Project name: udis86
udis86| Project version: undefined
udis86| C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
udis86| C linker for the host machine: cc ld.bfd 2.42.0
udis86| Build targets in project: 138
udis86| Subproject udis86 finished.

Library execinfo found: NO
Found CMake: /usr/bin/cmake (3.29.2)
Run-time dependency epoll-shim found: NO (tried pkgconfig and cmake)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Dependency wayland-protocols found: YES 1.35 (cached)
Run-time dependency hyprland-protocols found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency hyprland-protocols

Executing subproject hyprland-protocols 

hyprland-protocols| Project name: hyprland-protocols
hyprland-protocols| Project version: 0.2
hyprland-protocols| Configuring hyprland-protocols.pc using configuration
hyprland-protocols| Build targets in project: 138
hyprland-protocols| Subproject hyprland-protocols finished.

Dependency hyprland-protocols found: YES 0.2 (overridden)
Dependency wayland-scanner found: YES 1.22.0 (cached)
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Build-time dependency hyprwayland-scanner found: YES 0.3.2
Program /usr/bin/hyprwayland-scanner found: YES (/usr/bin/hyprwayland-scanner)

protocols/meson.build:63:18: ERROR: File pointer-constraints-unstable-v1.xml does not exist.

A full log can be found at /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'hyprland-git-0.38.0.r105.582d6233-1': 
error: packages failed to build: hyprland-git-0.38.0.r105.582d6233-1

### How to reproduce

looks like it is missing pointer-constraints-unstable-v1.xml

**Comment by alexandru0-dev** [comment]
+1

**Comment by max-niederman** [comment]
Same issue here.

**Comment by raininja** [comment]
I am wondering about this new dependency upon [epoll-shim](https://github.com/jiixyj/epoll-shim)

**Comment by Agent00Ming** [comment]
> I am wondering about this new dependency upon [epoll-shim](https://github.com/jiixyj/epoll-shim)

It isn't new and it's for the BSD bros

**Comment by raininja** [comment]
> It isn't new and it's for the BSD bros. (You don't need it on linux)
After creating a PKGBUILD and installing it, I've realized that Linux users do not need this -_-

**Comment by use-the-fork** [comment]
Same issue here.

**Comment by gksudolol** [comment]
> > It isn't new and it's for the BSD bros. (You don't need it on linux)
> 
> After creating a PKGBUILD and installing it, I've realized that Linux users do not need this -_-

I was in the middle of writing an ebuild and I saw this haha!

**Comment by vaxerski** [comment]
for future reference dont use meson we always prefer cmake (meson is just there because fuf prefers it for nix for whatever reason)
