### ISSUE TITLE
Freeze when moving floating group with several windows

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#5768]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 25aec3ac8ce65ed224f025f8f6dfef73780577a4  ().
Date: 2024-04-27
Tag: , commits: @COMMITS@

flags: (if any)


System Information:
System name: Linux
Node name: theseus
Release: 6.6.28
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr 17 09:19:38 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240425.7bb2ccd"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Move floating group of several windows in it freezes Hypr deez land

### How to reproduce
1) Set minsize for the window, like windowrulev2=minsize 500 300, class:^(kitty)$
2) Make group from 2 windows, in my case 2 kitty terms
3) Set it float
4) Move it with mouse

After this Hyprland almost immediately become unresponsive, but no crash.

**Comment by Ligthiago** [comment]
Anyway, groups seems to be broken completely

https://github.com/hyprwm/Hyprland/assets/142721811/f44b95c8-06fb-475d-88b7-a8dd4ee9784f

**Comment by vaxerski** [comment]
pretty sure that worked before, is this a regression?

**Comment by Ligthiago** [comment]
No, same in old versions. I investigate little further and it not reproducible with default config, so repro steps now also include:
1) Set minsize for the window, like `windowrulev2=minsize 500 300, class:^(kitty)$`.

I am not a heavy groups user, so didn't notice it for a while. Also not much people use custom minsizes, so it not reported before.

**Comment by The-Briel-Deal** [comment]
I can repro, the behavior locally for me is that, any time there are rules with checks like minsize, the second window in the group will seem to follow your animation rules to animate to wherever the top window is brought.

I'm gonna take a stab at this unless you've already started this Vaxry?

**Comment by The-Briel-Deal** [comment]
I believe I fixed it, lmk if this works for you @Ligthiago. https://github.com/hyprwm/Hyprland/pull/5826

**Comment by Ligthiago** [comment]
@The-Briel-Deal Yep, thanks 👍🏻
