### ISSUE TITLE
[Enhancement] Add additional info to hyprpaper entry

### ISSUE THREAD

**Issue by WorldTeacher** [hyprwm/Hyprland#5772]
### Description

When trying to use 
`hyprctl hyprpaper listactive` using the non -git install, an `invalid command` occurs.

This is not mentioned in the wiki or the `hyprctl hyprpaper --help` 

I think it would be either mention such information in the wiki or the help page, as that could reduce confusion (or remove the help entries for hyprpaper, as the command does not work in non -git)

**Comment by The-Briel-Deal** [comment]
idk what this is supposed to do but I get invalid command on 1d40af64d352bd5a87c7d53a52707fc5cfc6940e.

my guess though is you are using out of sync versions of hyprpaper and hyprland.

I would guess if you use release Hyprland in pacman, and release hyprpaper this will work or latest git of both. 

Both of these things are very much still in development so if they aren't in sync things are bound to break.

Looking for where this broke rn though.

**Comment by The-Briel-Deal** [comment]
This does work on latest git of both.

Imo this shouldn't be expected to work unless you have matching versions.
