### ISSUE TITLE
why when float window exists, focus follow pointer

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#5773]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0

flags: (if any)


System Information:
System name: Linux
Node name: vincent-laptop
Release: 6.6.26-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:11:08 UTC 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
VERSION=rolling

plugins:


```

</details>

### Bug or Regression?

Bug

### Description

when all tiled windows, focus didnot change wherever pointer go,but when new window is float, focus will change to window which pointer hover over,I was used to disable it by using `follow_mouse = 0`, I donot care the little inconsistency but now it's a problem because I set 'hyprctl dispatch killactive' command in waybar module, I can never kill a float window as long as focus run away from it.

### How to reproduce

try it

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/87331f23-67ff-4048-a3b1-41651bb50bb5)

wiki :(

https://wiki.hyprland.org/Configuring/Variables/#input
