### ISSUE TITLE
pointer-constraints: cursor position issue

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/Hyprland#5774]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit e400a288d0f8ef75672cb201203b857b65b782bb  (pointer-constraints: remove emoji to fix clang).
Date: Sat Apr 27 15:27:24 2024
Tag: v0.39.1-88-ge400a288, commits: 4548

flags: (if any)


System Information:
System name: Linux
Node name: localhost
Release: 6.8.7-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:33 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

When interacting with some game elements, the cursor position is reset to the center of the screen. I haven't tried to `git bisect`, but I suspect [this](https://github.com/hyprwm/Hyprland/commit/25aec3ac8ce65ed224f025f8f6dfef73780577a4) commit is causing this issue.

### How to reproduce

Above.

### Crash reports, logs, images, videos

https://youtu.be/lyMbEBLJ2mk

**Comment by vaxerski** [comment]
oopsie daisy uwu

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15139503/patch.txt)
try this

**Comment by The-Briel-Deal** [comment]
God bless the 20 minute oopsie daisy fix time.

**Comment by bubba-champion** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/15139503/patch.txt) try this

Still reproducible.

**Comment by wagyourtail** [comment]
this patch worked for me to prevent everything crashing when games grabbed my mouse

**Comment by vaxerski** [comment]
hm.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15139765/patch.txt)
maybe this?

**Comment by bubba-champion** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/15139765/patch.txt) maybe this?

Nope, this patch doesn't fix the situation. I want to add that during testing, I noticed that if I go to the in-game section "The Archives" the cursor disappears briefly and then reappears, after that I cannot reproduce the problem until the game is restarted. This behavior persists both without and with these two patches.

**Comment by Agent00Ming** [comment]
Can someone test the change in #5895 to see if it breaks the previous fix

**Comment by Agent00Ming** [comment]
> this patch worked for me to prevent hyprland crashing/freezing when games (tested with cs2, minecraft) grabbed my mouse

@wagyourtail can you test if #5895 breaks it again? I've never been able to reproduce the original crashes.
