### ISSUE TITLE
Seg Fault when moving windows with windowrules

### ISSUE THREAD

**Issue by m007x** [hyprwm/Hyprland#5779]
### Hyprland Version

Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)

System Information:
System name: Linux
Node name: ventura
Release: 6.8.3-gentoo-dist-hardened
Version: #1 SMP PREEMPT_DYNAMIC Thu Apr  4 05:11:13 BST 2024

GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])

os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"

plugins:

### Bug or Regression?

Bug

### Description

When moving a windows with conflicting window rules, I got a seg fault. A check should be put in place to prevent this segfault.

### How to reproduce

See my hyprland config below to see the window rules. I have a rule that makes every window into tiling mode, I then have another rule which for a certain application makes it float. Spawn some windows (they should tile), then spawn this window which should float (it wont), then drag this window and it goes into floating, drag some more windows and it then crashes.

### Crash reports, logs, images, videos

[5bunMPCq.txt](https://github.com/hyprwm/Hyprland/files/15140172/5bunMPCq.txt)
[NXcgmbRj.txt](https://github.com/hyprwm/Hyprland/files/15140173/NXcgmbRj.txt)
[i9Ew8csP.txt](https://github.com/hyprwm/Hyprland/files/15140177/i9Ew8csP.txt)

**Comment by vaxerski** [comment]
does this happen on the default config? or are the window rules required to repro this?

Also, you're on a very outdated version, please update first.

**Comment by m007x** [comment]
> does this happen on the default config? or are the window rules required to repro this?
> 
> Also, you're on a very outdated version, please update first.

window rules are required im pretty sure to reproduce. Im updating as we speak and il let you know if the issue persists. (i commented out the top window rule which sets everything to tiling which will need to be uncommented for the issue to be present).

**Comment by m007x** [comment]
im just gonna attach the affected config here which causes the seg fault to save u time looking through the config and finding what to uncomment: 
[i9Ew8csP.txt](https://github.com/hyprwm/Hyprland/files/15140227/i9Ew8csP.txt)

**Comment by m007x** [comment]
Alright Ive confirmed its still present on the newer version.
[FW0ZOIta.txt](https://github.com/hyprwm/Hyprland/files/15142254/FW0ZOIta.txt)
[tSlSBGsM.txt](https://github.com/hyprwm/Hyprland/files/15142255/tSlSBGsM.txt)
[J9vswZA6.txt](https://github.com/hyprwm/Hyprland/files/15142256/J9vswZA6.txt)

**Comment by vaxerski** [comment]
let me know which rules precisely cause this, and which window. I am on -git and dragged kitty around with your windowrules to no crashes. (also it's worth testing on -git and not 0.39.1 if you can)

**Comment by m007x** [comment]
I also can no longer trigger this crash, I didn't change anything so I have no idea why. However I did recently do a full system upgrade. This makes me think something else was triggering it instead of hyprland directly. 

Closing this issue now.
