### ISSUE TITLE
Addressing deficiencies in documentation

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#578]
Some of the documentation is insufficient, wrong, or confusing. I will edit this issue as I come across things that I have questions about. The more questions your documentation answers, the less people bother you.

- [ ] What is [psuedotile](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config)? I can see what it does, but what is the purpose? If there were a description, I would know that it is working correctly.
  - Firefox, when in a tall tile on half of the screen, does not appear to do anything with psuedotiling mode.
  - Even with `dwindle.psuedotile` set to `false`, I can still make a bind using the `psuedo` dispatcher. How does the option interact with the bind dispatcher, and what is it supposed to do if not disable the dispatcher?
- [ ] What is [clickfinger](https://wiki.hyprland.org/Configuring/Basic-Config/#touchpad) and how does it behave?
- [ ] How does [middle button emulation](https://wiki.hyprland.org/Configuring/Basic-Config/#touchpad) work? Is it a three-finger tap? Isn't that a part of `tap-to-click`?
  - Why does `middle_button_emulation` change nothing when set to `false` (under the assumption that it is supposed to be three-finger tap)?
  - Why does `tap-to-click` have a hyphenated name versus everything else which is underscored? How does it interact with "clickfinger" and "middle button emulation"?
- [ ] What is [`animate_manual_resizes`](https://wiki.hyprland.org/Configuring/Basic-Config/#misc)? From what I can tell, it changes nothing.
- [ ] [`preserve_split`](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config) needs elaboration. What can happen to the container? How would it cause the behavior to change? How does this interact with `force_split`? If they are mutually exclusive, with the former being more "dynamic" in behavior, perhaps they should be combined into `split_mode`?
- [ ] What is "auto-split"? Why does it need a [`split_width_multiplier`](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config)?
- [ ] How does [`use_active_for_splits`](https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config) behave when `force_split` is non-zero? What does that mean for `preserve_split`?
- [ ] What is `drag_lock`?

**Comment by vaxerski** [comment]
pseudotile will shape the window with its' floating shape in tiled mode. Resize a floating window, toggle tiled and toggle pseudo and you'll see.

dwindle:pseudotile is a master switch for enabling it

clickfinger - no clue. some libinput setting for touchpads.

middle button emulation - same as above

why is tap-to-click that way? cuz thats its name in libinput

animate_manual_resizes tells the compositor whether to animate the size changes of tiled windows when main_mod+rmb

preserve_split will preserve the split type (horiz vs vert) for a window regardless of thw changes to its size. If off, when a top bottom split node is resized to be wide enough, the split direction will automatically change.

force_split only governs which window in a split should be the new one. Right or left (bottom or top)

wym auto split? split_width_multiplier is the value you multiply X by before comparing with Y to determine the split orientation

use_active_for_splits will use the active window as a split base. You're misunderstanding the feature. When you open a window, you open in on another window and those get into a node, side by side or top bottom. Use active will always use the active (focused) one. Disabling this will use the mouse's position and the window under the mouse.

**Comment by IanManske** [comment]
This should help regarding libinput:
- [Middle Button Emulation](https://wayland.freedesktop.org/libinput/doc/1.12.4/middle-button-emulation.html)
- [Click Finger Behavior](https://wayland.freedesktop.org/libinput/doc/1.12.4/clickpad-softbuttons.html#clickfinger-behavior)
- [Tap To Click](https://wayland.freedesktop.org/libinput/doc/1.12.4/tapping.html)

**Comment by vaxerski** [comment]
should we close this? super old + mostly not relevant anymore

**Comment by spikespaz** [comment]
> should we close this? super old + mostly not relevant anymore

Currently working on it, still relevant.

**Comment by hackedWifi** [comment]
This is very informative. I agree that the WIKI needs some work. 
A great software to be honest, but it lacks good documentation in some aspects.

**Comment by vaxerski** [comment]
I disagree, but you do you. I'd rather move this to https://github.com/hyprwm/hyprland-wiki though
