### ISSUE TITLE
When using Hypnland, there was a sudden crash, and after the crash, it automatically exited the tty interface.

### ISSUE THREAD

**Issue by Hausenbourne** [hyprwm/Hyprland#5783]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.7-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When using Hypnland, I suddenly experienced a crash, and after the crash, I automatically exited the tty interface. In this case, I need to restart and enter Hypnland again, and this phenomenon will occur again later.

### How to reproduce

I usually crash when opening Firefox or Edge browser after a while, and if I am in the shell interface, it will also crash for a while.

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Well this is awkward.

Hyprland received signal 6 (Aborted)

Version: fe7b748eb668136dd0558b7c8279bfcd7ab4d759
Tag: v0.39.1

System info:
	System name: Linux
	Node name: archlinux
	Release: 6.8.7-arch1-2
	Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c8) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	

Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x59da718b63f2]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x7b1) [0x59da71861431]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x4c) [0x59da717e00dc]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3c770) [0x774381c5a770]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x8d32c) [0x774381cab32c]
		main
		??:?
	#5 | /usr/lib/libc.so.6(gsignal+0x18) [0x774381c5a6c8]
		??
		??:0
	#6 | /usr/lib/libc.so.6(abort+0xd7) [0x774381c424b8]
		??
		??:0
	#7 | /usr/lib/libc.so.6(+0x243dc) [0x774381c423dc]
		??
		??:0
	#8 | /usr/lib/libc.so.6(+0x34d46) [0x774381c52d46]
		??
		??:0
	#9 | /usr/lib/libdrm_nouveau.so.2(+0x4c28) [0x77437e1a7c28]
		??
		??:0
	#10 | /usr/lib/libdrm_nouveau.so.2(nouveau_pushbuf_data+0x67) [0x77437e1a7b87]
		??
		??:0
	#11 | /usr/lib/libdrm_nouveau.so.2(+0x4cad) [0x77437e1a7cad]
		??
		??:0
	#12 | /usr/lib/libdrm_nouveau.so.2(+0x4f27) [0x77437e1a7f27]
		??
		??:0
	#13 | /usr/lib/libdrm_nouveau.so.2(+0x5c94) [0x77437e1a8c94]
		??
		??:0
	#14 | /usr/lib/dri/nouveau_dri.so(+0x97746e) [0x77437657746e]
		??
		??:0
	#15 | /usr/lib/dri/nouveau_dri.so(+0x977852) [0x774376577852]
		??
		??:0
	#16 | /usr/lib/dri/nouveau_dri.so(+0x2a4e55) [0x774375ea4e55]
		xwm_handle_selection_event
		??:?
	#17 | Hyprland(+0x28c51a) [0x59da719c451a]
		wlr_xwayland_create
		??:?
	#18 | Hyprland(+0x297486) [0x59da719cf486]
		xwm_handle_selection_client_message
		??:?
	#19 | Hyprland(drm_surface_blit+0xcf) [0x59da719730bf]
		drm_surface_blit
		??:?
	#20 | Hyprland(+0x23d50c) [0x59da7197550c]
		commit_drm_device
		??:?
	#21 | Hyprland(output_cursor_set_texture+0x53a) [0x59da7198adda]
		output_cursor_set_texture
		??:?
	#22 | Hyprland(+0x26aa86) [0x59da719a2a86]
		wlr_cursor_move
		??:?
	#23 | Hyprland(+0x26b000) [0x59da719a3000]
		wlr_cursor_set_xcursor
		??:?
	#24 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x77438264c01e]
		??
		??:0
	#25 | Hyprland(+0x269126) [0x59da719a1126]
		wlr_cursor_destroy
		??:?
	#26 | /usr/lib/libffi.so.8(+0x7596) [0x774381939596]
		??
		??:0
	#27 | /usr/lib/libffi.so.8(+0x400e) [0x77438193600e]
		??
		??:0
	#28 | /usr/lib/libffi.so.8(ffi_call+0x123) [0x774381938bd3]
		??
		??:0
	#29 | /usr/lib/libwayland-server.so.0(+0x8ada) [0x77438264aada]
		??
		??:0
	#30 | /usr/lib/libwayland-server.so.0(+0xd180) [0x77438264f180]
		??
		??:0
	#31 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x77438264dae2]
		??
		??:0
	#32 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x77438264e2d7]
		??
		??:0
	#33 | Hyprland(_ZN11CCompositor15startCompositorEv+0xf13) [0x59da717e1fe3]
		CCompositor::startCompositor()
		??:?
	#34 | Hyprland(main+0x752) [0x59da717c4892]
		main
		??:?
	#35 | /usr/lib/libc.so.6(+0x25cd0) [0x774381c43cd0]
		??
		??:0
	#36 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x774381c43d8a]
		??
		??:0
	#37 | Hyprland(_start+0x25) [0x59da717dd635]
		_start
		??:?

--------------------------------------------
   Hyprland Log
--------------------------------------------
Log tail:
[LOG] Set keyboard focus to surface 59da73300640, with [Window 59da734ab7d0: title: "New tab - Profile 1 - Microsoft​ Edge"]
[LOG] Searching for matching rules for Microsoft-edge (title: New tab - Profile 1 - Microsoft​ Edge)
[LOG] Searching for matching rules for Microsoft-edge (title: New tab - Profile 1 - Microsoft​ Edge)
[LOG] Set keyboard focus to surface 59da73459340, with [Window 59da73468130: title: "microsoft-edge-stable "]
[LOG] Searching for matching rules for kitty (title: microsoft-edge-stable )
[LOG] Window rule opacity 0.80 0.80 -> class:^(kitty)$ matched [Window 59da73468130: title: "microsoft-edge-stable "]
[LOG] TI ENABLE
[LOG] Searching for matching rules for kitty (title: microsoft-edge-stable )
[LOG] Window rule opacity 0.80 0.80 -> class:^(kitty)$ matched [Window 59da73468130: title: "microsoft-edge-stable "]
[LOG] Set keyboard focus to surface 59da73300640, with [Window 59da734ab7d0: title: "New tab - Profile 1 - Microsoft​ Edge"]
[LOG] Searching for matching rules for Microsoft-edge (title: New tab - Profile 1 - Microsoft​ Edge)
[LOG] cursorImage request: surface 59da73e88170
[LOG] Registered signal for owner 59da72920288: 59da73e88488 -> 59da729202d0 (owner: CWLSurface)
[LOG] Registered signal for owner 59da72920288: 59da73e88448 -> 59da72920338 (owner: CWLSurface)
[LOG] CWLSurface 59da72920288 called init()
[LOG] cursorImage request: surface 59da73e88170
[LOG] cursorImage request: surface 59da73e88170
[LOG] New XWayland Surface created (class null).
[LOG] Registered signal for owner 59da734ad720: 59da73477900 -> 59da734ade08 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734ad720: 59da73477910 -> 59da734ade70 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734ad720: 59da73477880 -> 59da734ad858 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734ad720: 59da734779b0 -> 59da734adda0 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734ad720: 59da73477890 -> 59da734adc00 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734ad720: 59da732feed8 -> 59da734ad788 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734ad720: 59da732feec8 -> 59da734ad720 (owner: XWayland Window)
[LOG] Registered signal for owner 59da734adf40: 59da732fef08 -> 59da734adf88 (owner: CWLSurface)
[LOG] Registered signal for owner 59da734adf40: 59da732feec8 -> 59da734adff0 (owner: CWLSurface)
[LOG] CWLSurface 59da734adf40 called init()
[LOG] New tearing hint at 59da734b04b0
[LOG] Registered signal for owner 59da73480490: 59da734b04e8 -> 59da73480500 (owner: TearingController)
[LOG] Registered signal for owner 59da73480490: 59da734b04d8 -> 59da73480498 (owner: TearingController)
[LOG] cursorImage request: surface 59da73e88170
[LOG] Registered signal for owner 59da734ad720: 59da732feee8 -> 59da734ad7f0 (owner: CWindow)
[LOG] Searching for matching rules for  (title: )
[LOG] Registered signal for owner 59da734ad720: 59da734778e0 -> 59da734ad990 (owner: XWayland Window Late)
[LOG] Registered signal for owner 59da734ad720: 59da734778f0 -> 59da734adb98 (owner: XWayland Window Late)
[LOG] Registered signal for owner 59da734ad720: 59da73477920 -> 59da734ad8c0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 59da734ad720: 59da734778c0 -> 59da734ada60 (owner: Xwayland Window Late)
[LOG] Registered signal for owner 59da734ad720: 59da734778d0 -> 59da734adac8 (owner: Xwayland Window Late)
[LOG] Registered signal for owner 59da734ad720: 59da734779c0 -> 59da734ad928 (owner: XWayland Window Late)
[LOG] Map request dispatched, monitor eDP-1, window pos: [1494.99998, 368.74999], window size: [30.00000, 106.25000]
[LOG] Searching for matching rules for kitty (title: microsoft-edge-stable )
[LOG] Window rule opacity 0.80 0.80 -> class:^(kitty)$ matched [Window 59da73468130: title: "microsoft-edge-stable "]
[LOG] Searching for matching rules for Microsoft-edge (title: New tab - Profile 1 - Microsoft​ Edge)
[LOG] Searching for matching rules for  (title: )
[LOG] cursorImage request: surface 59da73e88170

[LOG] Instance Signature: fe7b748eb668136dd0558b7c8279bfcd7ab4d759_1714275087
[LOG] Hyprland PID: 752
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: archlinux
[LOG] Release: 6.8.7-arch1-2
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000

[LOG] GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c8) (prog-if 00 [VGA controller])

[WARN] Warning: you're using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Alors on danse

[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 21.25µs. Estimated average calc time: 0.04µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 8.48µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/bourne/.config/hypr/hyprland.conf
[LOG] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug

**Comment by vaxerski** [comment]
this is a driver bug

**Comment by Hausenbourne** [comment]
> this is a driver bug

Thank you very much for pointing out the reason for this issue with my Hypnland. I would like to continue to ask a question. My Hypnland is installed through the hyprdots installation script, including various drivers. I noticed that there is a mention of/libdrm nouveau. so. 2 in the crash report, so is it because the script installed an inappropriate driver for my Nvidia graphics card? If that's the case, I might be able to solve this problem by disabling the Nvidia graphics card or installing the correct driver for it.

**Comment by vaxerski** [comment]
we can't provide official support for nvidia, and I've never dealt with it. You might have more luck reading the nvidia wiki pages or online tutorials. You could also ask around on discord.

**Comment by Hausenbourne** [comment]
Oh，Thanks.
