### ISSUE TITLE
wrong window gets focused when killing a swallowed client.

### ISSUE THREAD

**Issue by chiccoY2K** [hyprwm/Hyprland#5784]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.8.7-200.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:35:11 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] [8086:3ea0] (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME="Fedora Linux"
VERSION="39 (Thirty Nine)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Thirty Nine)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

when closing a swallowed window in a master layout, if said window is in the master position, i would expect the remaining swallow-ing window to be focused after the action. instead, the first window in the stack gets focus.
![2024-04-28-103820_hyprshot](https://github.com/hyprwm/Hyprland/assets/95131744/0f4da825-553b-44e5-b78d-febcfe1eca9b)

### How to reproduce

here are my relevant options in hyprland.config
```
general {
    layout = master
}

misc {
    enable_swallow = true
    swallow_regex = ^(kitty)$
}

master {
    new_is_master = true
    new_on_top = true
}
```
- open two windows, one enabled to swallowing. leave this one in the master position
- launch a swallowed window in the master position. (in my case, i happen to frequently launch zathura from kitty)
- close the swallowed window. the focus is now on the _other_ window, instead of remaining in the master position on the window i was actually working on

**Comment by zooeywm** [comment]
@chiccoY2K  [Hope this can help you](https://github.com/hyprwm/Hyprland/issues/4296#issuecomment-2544496665)

**Comment by chiccoY2K** [comment]
@zooeywm cant update to a version where that option is available, but i believe thats the solution. closing this
