### ISSUE TITLE
CVE in the Plugin system

### ISSUE THREAD

**Issue by m007x** [hyprwm/Hyprland#5787]
### Hyprland Version

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

System Information:
System name: Linux
Node name: ventura
Release: 6.8.7-gentoo-dist-hardened
Version: #1 SMP PREEMPT_DYNAMIC Sun Apr 28 02:05:58 BST 2024

GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])

os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"

plugins:

### Bug or Regression?

Bug

### Description

https://social.treehouse.systems/@thesamesam/112349504465197920

https://www.openwall.com/lists/oss-security/2024/04/28/3

This type of issue should be fixed immediately which is why im posting it here to hopefully quicker the process.

### How to reproduce

.

**Comment by vaxerski** [comment]
It's a joke and not a CVE. Nobody even assigned it a CVE. What are you on about?

Besides, it's fixed already: https://github.com/hyprwm/Hyprland/commit/28c85619243e6320e75d7abcfe8244fa99d054dd

**Comment by MahouShoujoMivutilde** [comment]
Does it actually allow an attacker to do anything that can't be done with `hyprctl plugin load malware-plugin.so`?

**Comment by vaxerski** [comment]
No. Someone needs access to write to /tmp/hypr, so... they have to be running code on your system already, at which point they can also `rm -rf /`. That's why this CVE is a joke.

The only "issue" is that other users could do this as well, which they now can't after 28c85619243e6320e75d7abcfe8244fa99d054dd. Though, other users can still technically `hyprctl --instance x plugin load malware.so`, maybe I should restrict --instance to same user.

**Comment by m007x** [comment]
> It's a joke and not a CVE. Nobody even assigned it a CVE. What are you on about?
> 
> Anyways, it's fixed already: [28c8561](https://github.com/hyprwm/Hyprland/commit/28c85619243e6320e75d7abcfe8244fa99d054dd)

My apologizes on the wording of the title - changing it to better reflect what the issue was.

Awesome work on Hyprland btw, keep it up.

**Comment by vaxerski** [comment]
yeah sorry for the snarky tone but I was irritated by how some people are claiming its a huge deal, where it really, really isnt
