### ISSUE TITLE
`dwindle.use_active_for_splits` does nothing

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#579]
My understanding of the option:

`dwindle.use_active_for_split = false`

New windows will open in a new split created from the bounding rectangle of the window with the current mouse focus.

`dwindle.use_active_for_split = true`

New windows will open in a new split created from the bounding rectangle of the window with current **keyboard focus**.

---

Either I am wrong and dumb, or I am wrong and there is not enough information on the wiki. Until proven however, I will report this as a bug, assuming my assumptions.

**Comment by vaxerski** [comment]
thats how it works yes and it works

**Comment by spikespaz** [comment]
Please re-open this, it does not work. You didn't even ask any other questions. If you agree that my understanding of the intended behavior is correct, and I made the issue because it does not behave according to my expectation, why would you just close the issue?

**Comment by TAforever** [comment]
See https://github.com/hyprwm/Hyprland/issues/550. I think `use_active_for_split=true` should be hardcoded and removed from the config.

**Comment by vaxerski** [comment]
verified, works as intended.

**Comment by spikespaz** [comment]
@vaxerski 
Re-verify with
`dwindle/force_split = 2`
`dwindle/preserve_split = true`
`dwindle/use_active_for_splits = true`
`input/follow_mouse = 2`

I think the may be `follow_mouse`, in #550 the mode was 1.

The issue, to state explicitly, is that *the window splits under mouse focus* irrespective of the region in focus signified by the color of `general/col.active_border`which I believe to have keyboard focus. When `follow_mouse` is "loose", **I expect the new window to appear inside the colored box** respecting the rules of `dwindle/force_split` and `dwindle/use_active_for_splits`.

**Comment by spikespaz** [comment]
The functionality I would like to achieve can be described as follows:
- Mouse focus is completely ignored unless a click happens, for example focusing a caret in a text editor, in which case keyboard focus is also switched to match mouse focus.
- Window management behavior relies entirely on *keyboard* focus, where my active border currently is. Every action should modify that region and no other.

**Comment by vaxerski** [comment]
works as expected. `use_active_for_splits` on -> if i move the mouse outside the keyboard focused window, it will still be used for the split.

with it off, the mouse is used and the window under the mouse.

**Comment by spikespaz** [comment]
If it weren't for #580, I would record with OBS and show you that it behaves differently on my machine.

**Comment by spikespaz** [comment]
So, the focus indicator border is misleading. When I launch something like Rofi, the active borer retains its position, but the keyboard focus is changed. Perhaps three focus modes (WM selection, keyboard, mouse) are needed for when an overlay like Rofi steals keyboard focus.

**Comment by spikespaz** [comment]
s/borer/border

**Comment by vaxerski** [comment]
The border is not misleading, it's just that it does not signify the keyboard focus, or the mouse focus, or any focus for that matter. It's simply the last window with a keyboard focus. Not much else.

**Comment by spikespaz** [comment]
If it is the last window with keyboard focus why does Rofi not get a border? Is Rofi not a window?

**Comment by vaxerski** [comment]
If the "active" border color stays on another window, then indeed.

No clue how rofi works (or any of its wayland forks) but for wofi, or any properly written wayland launcher - yes, they are not windows.

**Comment by spikespaz** [comment]
Then why does a new window spawn relative to something that isn't a window, not even floating?

Speaking of floating, if there isn't an option already, can we have one (`new_window_behavior`) with some modes such that:

This is a rough draft of the proposed behavior for the types of focus that are inherent to this system.

Window Manager Focus always changes to the region that receives *any* input event, *except* for scrolling, or button releases IF Mouse Focus Mode is 2.

Define **focus**:
 - Mouse Focus Mode
   - 0 - Events will be sent only when the pointer is over the region which last received a button press, and will cease when the pointer moves out of region.
   - 1 - Events will be sent only when the pointer is over the region which last received a button press, and will cease when the pointer moves out of region UNLESS a mouse button is currently held down.
   - 2 - Events will be begin sending to a region when a button press is received, and will not cease receiving movement events UNLESS another region receives mouse focus as a result of a button press.
 - Keyboard Focus Mode
   - 0 - ??? I feel like I am missing a state here.
   - 1 - Events will be sent only when the window was last selected by the window manager (binds).
   - 2 - Events will be sent either when selected by the window manager, or when a mouse button is pressed in the region of the window.

Focus Following Mode:
 - 0 - Mouse Focus follows Keyboard Focus
 - 1 - Keyboard Focus follows Mouse Focus
 - 3 - No bounds, defer to natural behavior of Mouse Focus Mode and Keyboard Focus Mode

- 0 - Default behavior. New windows will be created relative to the current window with *the border* (Window Manager Focus).
  - If the current outlined window is tiled: the new window will be inserted in a split created from the region of the currently-bordered, with respect to `force_split`.
  - If the current outlined window is floating: the new window will be inserted into a split created from an adjacent tile region, with the rules of adjacency adjusted by `force_split` for consistency.
- 1 - New windows will be created relative to the current window with *the border*.
  - If the current outlined window is floating: the new window will also be floating. It will appear at a configurable offset, there needs to be another setting for this. Overlapping, Adjacent (T,B,L,R), etc. Details need elaboration.
  - If the outlined window is tiled, a new split will be created same as mode 0.
- 2 - Same as Mode 0 except following Keyboard Focus instead of Window Manager Focus.
- 3 - Same as Mode 1 except KBF instead of WMF
- 4 - derive 0, mouse > wm
- 5 - derive 1, mouse > wm

**Comment by spikespaz** [comment]
Obviously not every scenario has been considered, but this should allow a very wide range of possibility. If implemented correctly, the state machine should be easy to keep track of. I am sure that with further thought some mutual exclusions will need to be handled.
