### ISSUE TITLE
Hyprland doesn't run on dGPU despite telling it to on Intel/Nvidia system + resume from Hibernation fails

### ISSUE THREAD

**Issue by AniAggarwal** [hyprwm/Hyprland#5790]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: arrakis
Release: 6.6.28-2-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:33 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

As shown by `nvidia-smi`, Hyprland is still running on iGPU. I followed all steps on Hyprland Nvidia docs  and whatever else I could find online to no avail. However, when using the following line, it seems most other programs run on my dGPU, like kitty, but not all (like brave) and not hyprland: `WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0`

I am also unable to resume from hibernation, presumably due to the `NVreg_PreserveVideoMemoryAllocations=1` flag.
I have attached the output from env command, my grup and mkinitcpio files.
Let me know what else I can provide.

Also, the wiki says to use symlinks for the cards but it seems wlroots doesn't support them.
I had to use `/dev/dri/card1` rather than `by-path`. 

My main goal with all this is to hopefully have vaapi working by following that section on the wiki, but it alas does not work. I hoped to instead then run hyprland on dGPU to get it to work, but doing so seems to not work + break hibernation.
In the ideal case, I would run hyprland on the iGPU and have vaapi working for brave (it does work for firefox though).

### How to reproduce

Using the provided config, try hiberating. Upon boot, you should get stuck on a flashing `_`, at which point switching to another tty and (and back optionally) allows me to log in and launch hyprland. Resume has failed though.

### Crash reports, logs, images, videos

[env.txt](https://github.com/hyprwm/Hyprland/files/15144123/env.txt)
[debug-failed-to-resume-hibernation.log](https://github.com/hyprwm/Hyprland/files/15144132/debug-failed-to-resume-hibernation.log)
[grub.txt](https://github.com/hyprwm/Hyprland/files/15144133/grub.txt)
[mkinitcpio.conf.txt](https://github.com/hyprwm/Hyprland/files/15144134/mkinitcpio.conf.txt)
[nvidia.conf.txt](https://github.com/hyprwm/Hyprland/files/15144136/nvidia.conf.txt)

**Comment by vaxerski** [comment]
we can't and don't provide official support for nvidia, sorry. Read the nvidia wiki pages, ask around on discord, google stuff up.

**Comment by MahouShoujoMivutilde** [comment]
> In the ideal case, I would run hyprland on the iGPU and have vaapi working for brave (it does work for firefox though).
> _it does work for firefox though_

So... the problem is getting hardware video decode to work in chromium-based browser, not running of a dGPU for everything.


> Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics]

Should be plenty fine for video hardware acceleration.

https://wiki.archlinux.org/title/Hardware_video_acceleration#Intel

https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration


---

Idk about symlinks, I tested them on 0.39.1 and they did work fine. 

Try simpler path, the point of a symlink is to just get rid of `:` which wlroots otherwise wants to use as a separator (can't be escaped too). 

E.g. https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/1386#note_1856055 or just `/home/.../.config/hypr/card...`

**Comment by AniAggarwal** [comment]
> we can't and don't provide official support for nvidia, sorry

No need to apologize, you guys are providing a completely free 'product'! Thanks again for all your open source contributions :)

Sorry for my confusing comments;I've been trying to debug for so long I didn't think to provide enough context.

> Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics]
> Should be plenty fine for video hardware acceleration.

If I could just use the iGPU for hardware video acceleration, I would. However, with video acceleration turned on in all chromium brower's settings, they refuse to launch. 
My ideal use case would not have Hyprland even though dGPU (though I can't disable in BIOS bc I use it for ML). 
I figured I could fix the issue with chromium browsers by running everything on my dGPU, as suggested [here](https://github.com/elFarto/nvidia-vaapi-driver/issues/272#issuecomment-1937559060).

Perhaps I'm making a silly mistake of trying to use the dPGU for vaapi via nvidia-vaapi-driver. I'll try nuking it and see if I can get vaapi running on just my iGPU as intended.
