### ISSUE TITLE
gnome-disks not run on xwayland 

### ISSUE THREAD

**Issue by mahaveergurjar** [hyprwm/Hyprland#5795]
### Hyprland Version

❯ hyprctl systeminfo
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.7-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000

GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [UHD Graphics] [8086:4628] (rev 0c) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

gnome disk not run xwayland how to force to run on xwayland because gnome-disks not compatible with wayland

![image](https://github.com/hyprwm/Hyprland/assets/57872034/0638e34c-49c5-4f4e-90d5-6b0a507c533c)

the webcord run on xwayland automatically then why gnome-disks not run 

![image](https://github.com/hyprwm/Hyprland/assets/57872034/f5aaebef-e4f4-4613-a30e-5bc780980bfd)

### How to reproduce

run this command gnome-disks 
and showing this error

![image](https://github.com/hyprwm/Hyprland/assets/57872034/7a147c37-231a-4727-8077-3abccc5868c8)

**Comment by Ligthiago** [comment]
>how to force to run on xwayland 

`GDK_BACKEND=x11 gnome-disks`

>gnome-disks not compatible with wayland

It works on wayland, it unrelated, issue with installation not done properly or bug it app itself.

>why webcord run on xwayland automatically then why gnome-disks not run

Because `GDK_BACKEND` variable set to `wayland` and GTK apps will run on wayland if they can. Webcord is electron app, so separate flags for this must be set manually, refer to arch wiki.

**Comment by mahaveergurjar** [comment]
Ok
