### ISSUE TITLE
Screenflickering when watching youtube on fullscreen with VRR enabled

### ISSUE THREAD

**Issue by RandomLegend** [hyprwm/Hyprland#5797]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 33e0bb14786dc22a0c82eaaf097b469d3fdeceea  (wlr-output-power: move to new impl).
Date: Mon Apr 29 02:38:24 2024
Tag: v0.39.1-100-g33e0bb14, commits: 4560

flags: (if any)


System Information:
System name: Linux
Node name: frank-garuda
Release: 6.8.7-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:33 +0000


GPU information:
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev cc) (prog-if 00 [VGA controller])


os-release: NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=garudalinux


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I have a 144hz FreeSync Monitor and AMD RX 7900XT. Enabling VRR on that display and watching a video that doesn't run on 144fps makes the screen flicker in brightness by a few % a couple times per second.

I have VRR on 2 so fullscreen only, so watching the videos in windowed mode doesn't produce flickering.

Running games on something lower than 144fps doesn't produce flickering aswell.

### How to reproduce

Turn VRR on 2, start video playback (youtube for example) and make it fullscreen. Observer flickering

**Comment by vaxerski** [comment]
ye thats like a driver/monitor thing

**Comment by ItzELECTR0** [comment]
I don't even have VRR on, I explicitly set it off for my monitor and it STILL flickers when ANYTHING is fullscreen for me.
It's really annoying.
