### ISSUE TITLE
No combo box or context menu dropdowns shown in Qt applications

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#580]
Qt Applications tested:
`qt5ct` - Cannot select themes with dropdown.
`dolphin` - Cannot right-click, menu not shown.

Configuration: <https://raw.githubusercontent.com/spikespaz/dotfiles/master/users/jacob/configs/hyprland.conf>

**Comment by vaxerski** [comment]
thanks for a lot of info!

Should I close this instantly as well, because:

![image](https://user-images.githubusercontent.com/43317083/186762170-8733bb84-a912-45bf-8b3d-b66d15ba1e8a.png)

**Comment by spikespaz** [comment]
Instead of being passive-aggressive, tell me what you'd like to know. I gave you my config, that is all the info I have. The description of the problem is the title. The known afflicted programs are listed in the body. If there are system specifics that you need, **ask for them** and I'll make sure to include them in any future issues.

I am not a mind reader.

**Comment by vaxerski** [comment]
well I am as lost as you are as *nobody ever* had this issue. Everybody has this working.

Thus, this leads me to believe you're missing packages / req'd configs for Wayland itself to function, probably a result of installing Arch before knowing how 2 arch.

Do you have all the required qt packages for wayland, stuff like `qt5-wayland`, etc?

**Comment by spikespaz** [comment]
That is an assumption that I'm using Arch. And I know how to Arch. I do not know how to Nix. If anything, its the fault of the Flake at the root of this repository.

**Comment by vaxerski** [comment]
@fufexan for nix

**Comment by fufexan** [comment]
Idk how to tell you but both of the issues aren't issues on my system. Dropdowns work in both applications.

**Comment by spikespaz** [comment]
@fufexan Can you update your flake lock file? Perhaps there is something strange happening that is an interaction between new library versions.

I have linked my config in multiple places, can anyone confirm that it follows the correct format, that I haven't misconfigured anything or put something in the wrong section? I have read, re-read, and read again, and it all looks good to me.

**Comment by fufexan** [comment]
> Can you update your flake lock file?

Sure, what input should I update?

> can anyone confirm that it follows the correct format, that I haven't misconfigured anything or put something in the wrong section?

I pinged you on Discord, otherwise nothing wrong I found.

**Comment by spikespaz** [comment]
> Sure, what input should I update?

I'm not sure enough about Nix yet to discern, but I have the latest everything.

**Comment by fufexan** [comment]
Updated everything and rebuilt. Testing again, everything still works.

**Comment by spikespaz** [comment]
Strange, thanks for trying. Mind sending a link to your nix config, maybe I can check out the differences between how we have it set up.

**Comment by fufexan** [comment]
It's pinned on my profile: https://github.com/fufexan/dotfiles

**Comment by spikespaz** [comment]
I was using the latest beta `0.11.1` in my `flake.nix`, but for some reason, when building I see:
```
[1/0/17 built, 0.0 MiB DL] building hyprland-0.11.0beta+date=2022-08-25_f7c74
```
flash by. Why would this be?

**Comment by fufexan** [comment]
Because the [version string](https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L37) isn't up to date.

**Comment by fufexan** [comment]
The commit is the only source of truth. Versions mean nothing.

**Comment by spikespaz** [comment]
The issue must have been fixed along with some other bug that shared faulty logic. The issue does not happen when built on commit b16a57c.

**Comment by spikespaz** [comment]
Re-opening because even though OBS has decided to cooperate, it would seem that Dolphin still won't let me have a context menu.

**Comment by spikespaz** [comment]
<https://bbs.archlinux.org/viewtopic.php?id=264229>

A workaround would be to set `QT_QPA_PLATFORM='xcb'`, though this defeats Wayland.

**Comment by spikespaz** [comment]
One day I noticed a little rectangle in the corner of a QT application. It was offset to the left, and looked like it was pinned as far as it could go. I have to thank the bug in whatever positioning code put that menu there, because I have now discovered the fix:

```
monitor = eDP-1,preferred,0x1080,1
monitor = DP-1,preferred,0x0,1
# monitor = eDP-1,preferred,1920x1080,1
# monitor = DP-1,preferred,1920x0,1
```

However, I would like to be able to reserve the space to the left of my (stacked) monitors for any third one.

**Comment by spikespaz** [comment]
Another discovery: If a monitor is not occupying whatever region is reserved, the bug takes place. For example, having that stacked configuration and removing the monitor on top, closest to (0, 0) will cause the bug.

**Comment by vaxerski** [comment]
Does this also happen in sway? I can see `wlr_xdg_popup::current::geometry` having seemingly incorrect coordinates.

**Comment by vaxerski** [comment]
Tested in sway, from my findings the same bug occurs. I'll report it to wlroots.

**Comment by vaxerski** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3485

**Comment by vyivel** [comment]
This is a Qt5 bug. https://bugreports.qt.io/browse/QTBUG-85297

**Comment by vaxerski** [comment]
yikes then, closing here.
