### ISSUE TITLE
Default monitor for cursor

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#5803]
### Description

I wasn't able to find this in the documentation, so I'm not sure if this exists already, but the option to set the monitor that the cursor will appear in on login would be great. I have both DP-1 and HDMI-A-2, and although DP-1 is my primary monitor, my cursor always appears on HDMI-A-2 on login.

**Comment by vaxerski** [comment]
yea it currently is on the first one that gets recognized by drm I believe
