### ISSUE TITLE
Hyprland stuck at tty initial stdout log, nothing after that nor crashes

### ISSUE THREAD

**Issue by PolarFill** [hyprwm/Hyprland#5804]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
# This info was taken on the latest commit i know of that i can run (consequently, the latest version i can run this command on)
# All other info is up to date. Check issue description bellow for details

Hyprland, built from branch  at commit 82222342f10a7eff0ec9be972153e740d0f95213  ().
Date: 2024-04-17
Tag: , commits: @COMMITS@

flags: (if any)


System Information:
System name: Linux
Node name: nagisa
Release: 6.6.27
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Apr 13 11:07:41 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM107 [GeForce GTX 750] [10de:1381] (rev a2) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240416.66adc1e"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

While i already commented on this above, the bug I'm reporting also applies to the currently latest commit (f2b03e9). I'm using an older one because, well, i can't boot the latest one.

After some issues with xdg-desktop-portal, i decided to update hyprland and see if it works. To my demise (or my systems demise), hyprland won't render nor crash anymore. It gets stuck at the stdout log at tty, and never exits it, not even crashing. CTRL-C and other signals also don't work, so i have to change tty's to continue using my computer (without a graphical session, in this case).

If i run ```nixos-rebuild``` inside a hyprland session, making hyprland update, my terminal (alacritty) window gets extremelly mangled, with lots of artifacts covering it, blocking the content almost entirely. This extreme mess also changes with every character typed, but it's still mangled, nonetheless. When i then exit hyprland and start a new session, it causes the bug mentioned above. I don't actually know if this is a result of the bug per se, or if it's another bug, or if it's just something that happens when you update a session currently running, but i thought mentioning it could be important. I also can't provide screenshots currently, because the version I'm in has problems with xdg-desktop-portal, apparently.
(As i was gathering logs, i ran the command inside a running session and it seems this effect didn't occur. But the main problem, not rendering, still happens regardless. So i don't know if this is related)

What I've tried:
- Deactivating my themes (as I've read on the wiki it could be causing the issue)
- Using the default hyprland configuration
- Using the software render (```WLR_RENDERER_ALLOW_SOFTWARE=1```)
- Seeking help on the discord server (to which user jappie3, thx btw, helped me bisect the problem)

Bisect results showed these 5 commits as possible origins of the problem. I can't narrow it down to one because some simply don't build in my computer (and also fail github nixos-related tests):

8afdb8403bf71daf7e25bffbbdd87e0e3e61913c
448e3208cae4f19d48021572d50b9d29efc1d74b
f041d763ae1d5ec58682e3ff1fe3159ba9c95a49
019d4900cb132f2ff43fea49334712a12c282a14
f587c3e0ba92109302032f89321d94b5d0f89236
87173bd09daa4b56adabcfc72a29aec957cb8a13
a4f38a07d7578f0b06c09de7d04682e0aaddb12a
cbed4fa5ec1c7e5b383964ce5783eba6bbed7736

If i don't skip any commit, and mark builds that won't build as bad, 8ca28dd510f9aaf1cdf28d1e22a568f57319d0ce is the culprit. But idk if this is the right way of doing this. Either way this commits fails the nixos test on github.

I can't record or screenshot anything, since
1 - Its a tty
2 - Either way, my xdg-desktop-portal isn't working at the version I'm stuck on
I can, however, provide pictures and recordings of my monitor's screen if needed

I'll be providing logs for the initialization, but there's no crashlog, because, as i mentioned, there's no crash to log. I also have my nixos dotfiles [here](https://github.com/PolarFill/flaked-dots). The only change not commited to the repo is that i upgraded nixos to it's latest commit today. I felt like that wasn't worth commiting, since it doesn't work on my pc anyway.

I'll be happy to collaborate and provide any missing details, obviously. Sorry for the long issue

### How to reproduce

0 - Maybe build my dotfiles with nixos?
1 - Try to start a hyprland session from tty (with ```Hyprland``` command)

Regardless of configurations, it will get stuck at the initial stdout log and won't render anything, basically as if the wm didn't even start

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15154571/hyprland.log)

**Comment by gulafaran** [comment]
do you have WLR_RENDERER env var set to vulkan? looking at the logs it seems to try create a vulkan rendered, fails at it and eventually makes a renderer on your onboard intel gpu

**Comment by PolarFill** [comment]
I actually have WLR_RENDERER set to vulkan. Should i set it to something else?

**Comment by gulafaran** [comment]
dont set it at all

**Comment by PolarFill** [comment]
I had already tried it when i saw your comment tbh, and it just crashed with "m_sWLRRenderer was NULL!". I thought that was intended behavior lol

Anyways heres the crashlog 
[hyprlandCrashReport827.txt](https://github.com/hyprwm/Hyprland/files/15154948/hyprlandCrashReport827.txt)

**Comment by gulafaran** [comment]
yeah its mostly just crashing because its completly failing to create a renderer, im not sure why. check https://wiki.hyprland.org/Nvidia/ so your driver is booted with modeset=1 etc, and WLR_RENDER_DRM_DEVICE isnt pointing to your intel gpu otherwise im not sure, bad driver update?

**Comment by gulafaran** [comment]
or that hw cursor patch the wlroots-hyprland fork is doing something weird on your gpu/driver, seeing as you bisected it somewhat around those changes

**Comment by HirschBerge** [comment]
I can recreate this on a laptop with Nvidia (nouveau) and a desktop with an RX7900GRE

I'm using SDDM so no TTY for me even  either a blinking cursor or black screen.

Both running NixOS with the Hyprland repo flake input. The last working commit I have is from the 25th.

**Comment by HirschBerge** [comment]
> @HirschBerge maybe check your drivers?

I'm unsure what you mean? Since it's happening on AMD and those are built into the kernel, and I have working generations with the same kernel (6.6.28).
I'm going to try removing any unneeded ENV vars that may be causing issue, excluding that, not sure what it would have been since nothing changed besides hyprland, I think

**Comment by vaxerski** [comment]
can you try removing the nvidia hw cursors patch and seeing if that works?

**Comment by HirschBerge** [comment]
> can you try removing the nvidia hw cursors patch and seeing if that works?
> 
> Also you haven't posted a crash report.

Are you speaking to me? Because the issue author posted one a few. Myself, I cannot even get into my greeter, let alone Hyprland to generate a crash report. My ISP is also currently shitting itself so I can't be of much help for a while.

**Comment by vaxerski** [comment]
if you can't get to the greeter then it's unlikely this is a hyprland issue. Since @PolarFill seems to have resolved it (nvidia issue, classic) I'll close this

**Comment by HirschBerge** [comment]
Yep. Was a skill issue on my part. Turns out i had to set `services.displayManager.sddm.wayland.enable = true` and it just works.

**Comment by vaxerski** [comment]
it's 1:02am
