### ISSUE TITLE
Build failure Missing file protocols/alpha-modifier-v1.cpp

### ISSUE THREAD

**Issue by theophilusx** [hyprwm/Hyprland#5810]
### Hyprland Version

Building from HEAD of git repo 

commit 62ae2b3f40ffce99e1d94384800e9eba6638f447 (HEAD -> main, origin/main, origin/HEAD)

### Bug or Regression?

Bug

### Description

Was able to successfully build last on April 20th. Now running make all generates the error 

-- Configuring done (7.6s)
CMake Error at CMakeLists.txt:239 (target_sources):
  Cannot find source file:

    protocols/alpha-modifier-v1.cpp
Call Stack (most recent call first):
  CMakeLists.txt:271 (protocolNew)

-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
make[1]: *** [Makefile:14: release] Error 1
make[1]: Leaving directory '/home/tim/git/hyprland/Hyprland'
make: *** [Makefile:35: all] Error 2

Since last successful build, I have upgraded from Fedora 39 to Fedora 40. Not sure if that is relevant.  Looks like it might be related to commit f587c3e0ba921093020 on April 21. 

### How to reproduce

git pull
make all

### Crash reports, logs, images, videos

Fedora 40. 
Single monitor and NVIDIA Geforce RTX 3090. Using NVIDA driver. 
Prior build form April 20 runs fine (0.39.1)

**Comment by sungyoonc** [comment]
It looks like fedora hasn't updated their wayland-protocols package yet.

**Comment by theophilusx** [comment]
OK, thanks. I will investigate further along these lines.

**Comment by vaxerski** [comment]
correct, outdated w-p
