### ISSUE TITLE
hyprctl doesn't respect XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by jbeich** [hyprwm/Hyprland#5813]
### Hyprland Version

v0.39.1-107-g62ae2b3f

### Bug or Regression?

Bug

### Description

Regressed by #5788. On BSDs and non-systemd Linux distros `/run/user` may not exist while `XDG_RUNTIME_DIR` points under `/var/run/user`, `/var/run/xdg`, `/tmp/.xdg-run` or similar.

### How to reproduce

```
$ sudo mv /run/user{,-disabled}
$ export XDG_RUNTIME_DIR=$HOME/.run
$ mkdir -m 0700 $XDG_RUNTIME_DIR
$ Hyprland
$ hyprctl monitors
Couldn't connect to /run/user/1234/hypr/62ae2b3f40ffce99e1d94384800e9eba6638f447_1714479208_817877068/.socket.sock. (3)
```

**Comment by gulafaran** [comment]
should be fixed with [d7a48cf](https://github.com/hyprwm/Hyprland/commit/d7a48cf47816041c5cb705c9de218c3395635822)
