### ISSUE TITLE
Session lock and DPMS interactions causing Hyprland to crash

### ISSUE THREAD

**Issue by Agent00Ming** [hyprwm/Hyprland#5822]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 3d09c6d526a37b3bfd81bdd6d7427272d1ba90ac dirty (makefile: fix old headers only being copied).
Date: Tue Apr 30 19:32:42 2024
Tag: v0.39.1-116-g3d09c6d5, commits: 4576

flags: (if any)


```

</details>

### Bug or Regression?

Regression

### Description

Unlocking a session and dispatching dpms to turn on a monitor in quick succession results in a few seconds of instability where spawning any non-standard window (rofi-wayland/hyprlock/swaylock but not foot/kate for example) causes Hyprland to crash. Introduced after the switch to the new session-lock impl.

### How to reproduce

<details><summary>example hypridle.conf</summary>

```
general {
    lock_cmd = hyprlock && loginctl unlock-session
    unlock_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 5
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch eDP-1 # or any primary display for the screen locker
}
```

</details>

1. Lock the session and run a screen locker. (swaylock/hyprlock)
2. Dispatch dpms off on any monitor as long as there's one that is off when unlocking. (either by idle daemon timeout or keybind for easier testing)
3. Unlock the session successfully and dispatch dpms on for all monitors (swaylock/hyprlock && dispatch dpms on)
4. Launch any non-standard window program within a few seconds (rofi-wayland/swaylock/hyprlock)
5. Experience a crash

### Crash reports, logs, images, videos

[crashreport.txt](https://github.com/hyprwm/Hyprland/files/15172492/crashreport.txt)

**Comment by vaxerski** [comment]
I love wlroots.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15172543/patch.txt)
try this

**Comment by Agent00Ming** [comment]
patch works

**Comment by iUnstable0** [comment]
how do I apply the patch, im quite new sorry
