### ISSUE TITLE
xWayland applications intermittedly freak out (see video) but fix themselves on mouseover

### ISSUE THREAD

**Issue by HoJo42** [hyprwm/Hyprland#5823]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ed58cc4c31c21e09ee780d0df818afe935181cd9  (sessionLock: remove m_pLastFocus on destroy of surface).
Date: Tue Apr 30 18:33:36 2024
Tag: v0.39.1-117-ged58cc4c, commits: 4577

flags: (if any)


System Information:
System name: Linux
Node name: TeaMaker
Release: 6.8.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080 Rev. A] [10de:1e87] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When using xWayland applications (happens on Discord, Godot, and Steam, but not wayland native firefox) sometimes the window appears visually incorrect, but when you move the mouse over the affected area it fixes everything and the window looks correct. 

https://github.com/hyprwm/Hyprland/assets/88342079/ab12eca3-9e8b-4c1f-aaa3-b05d2653e7b3

https://github.com/hyprwm/Hyprland/assets/88342079/e3f941fb-1cc0-490c-80e0-028fea8392c9

### How to reproduce

It happens randomly on all the xWayland apps I use. 

### Crash reports, logs, images, videos

[hyprctl_clients_output.txt](https://github.com/hyprwm/Hyprland/files/15173316/hyprctl_clients_output.txt)

**Comment by vaxerski** [comment]
Welcome to nvidia.
