### ISSUE TITLE
Cursor disappears

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#5824]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 70ebc3add3b941a52f460f02129ef0842f580ec7 dirty (sessionLock: call wlr_surface_map/_unmap on the surface manually).
Date: Wed May 1 04:59:07 2024
Tag: v0.39.1-115-g70ebc3ad, commits: 4575

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.8.8-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:30 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

On some sites, the cursor disappears when placed on an image.

### How to reproduce

[test url](https://www.bilibili.com/opus/925837031687323652)

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/39702328/f8778949-4bb0-4d6e-8113-2be60720f749

**Comment by hdm9527** [comment]
> ![image](https://private-user-images.githubusercontent.com/43317083/327127100-c9b0eb9f-73e1-4a17-9096-46a4a16df2de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzE4MzgsIm5iZiI6MTcxNDU3MTUzOCwicGF0aCI6Ii80MzMxNzA4My8zMjcxMjcxMDAtYzliMGViOWYtNzNlMS00YTE3LTkwOTYtNDZhNGExNmRmMmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzNTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NWVhYTJiOWE2Yzk5MTc2NWNlYjk4Y2M2YjA0Zjk1YzRiMWJhOGRjMzYzMTViMGM0MDJmZWI0YzBlNTM4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K4hNMOqYj2bjP0MF74ozeA0dbbB9MKZURbeQ50RO38g) well...
> 
> Looks like an issue with the cursor theme?

hyprland stable version in firefox and chromium cursor normal display, hyprland-git version firefox cursor display, chromium browser cursor disappears.

**Comment by vaxerski** [comment]
tested again with chromium (I am on git) and the cursor is not disappearing. Have you tried a different theme? Are you using hyprcursor?

**Comment by FUFSoB** [comment]
Can repro with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags, happens only with some shapes like zoom_in/out or ew_resize

**Comment by hdm9527** [comment]
> Can repro with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags, happens only with some shapes like zoom_in/out or ew_resize

yes

**Comment by hdm9527** [comment]
> tested again with chromium (I am on git) and the cursor is not disappearing. Have you tried a different theme? Are you using hyprcursor?

chromium works under xwayland, it disappears in wayland, use `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland` to enable wayland.

**Comment by vaxerski** [comment]
works on my end in both modes. Again, have you tried a different theme?

**Comment by FUFSoB** [comment]
Happens on all themes I have installed (Bibata, Adwaita and Breeze). Hyprcursor is unset and disabled.

**Comment by hdm9527** [comment]
After using Hyprcursor themes, the cursor works, but chromium loses some cursor styles under wayland and falls back to the default styles. [Cursor-Test](https://vibhorjaiswal.github.io/Cursor-Test/)

https://github.com/hyprwm/Hyprland/assets/39702328/03d32790-f6e1-4300-988f-7f0f5aacb12a

https://github.com/hyprwm/Hyprland/assets/39702328/7cdf7b38-60ab-4914-85f9-1974d34fa036

**Comment by vaxerski** [comment]
huh. What is the hyprcursor version you have installed?

**Comment by hdm9527** [comment]
> huh. What is the hyprcursor version you have installed?

[hyprcursor-git-0.1.8.r0.gcab47461-1](https://aur.archlinux.org/hyprcursor-git.git)

**Comment by Agent00Ming** [comment]
https://github.com/hyprwm/Hyprland/assets/107314235/430fd346-7da7-47b6-94c8-2082d83f6a08

Left half is Firefox (doesn't support hyprcursor) on the cursor test page and right half is kate (supports hyprcursor).
`col_resize` and `row_resize` are shown to fall back on default pointer on hyprcursor. The theme is extracted from the xcursor Adwaita and compiled from there.

**Comment by vaxerski** [comment]
this one is a problem with your theme. Make sure you have a shape that fits `col_resize` and `row_resize`. Worth noting that due to (ugh) web uses `-` and wl uses `_`.

Recommended overrides for the sidey side arrow:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/88da587d-0a87-4d64-8181-1e7b3bbaf5da)

analogous for toppy bottomy will be with n, s, and row.

**Comment by vaxerski** [comment]
I've committed 84278247194fd04e042821fd171be5ee59b0a8d0 which makes hyprland attempt `-` first before falling back to a pointer.

**Comment by hdm9527** [comment]
> this one is a problem with your theme. Make sure you have a shape that fits `col_resize` and `row_resize`. Worth noting that due to (ugh) web using `-` and wl `_`.
> 
> Recommended overrides for the sidey side arrow: ![image](https://private-user-images.githubusercontent.com/43317083/327450105-88da587d-0a87-4d64-8181-1e7b3bbaf5da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTc3NDgsIm5iZiI6MTcxNDY1NzQ0OCwicGF0aCI6Ii80MzMxNzA4My8zMjc0NTAxMDUtODhkYTU4N2QtMGE4Ny00ZDY0LTgxODEtMWU3YjNiYmFmNWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEzNDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2Mjg0MGE0YTAxNGQ3ZGJjYjEyMDI5YjAwZWU3YmFhODAwNGU1Mjk4NWEyMTdmNzI4YzVkMjEzMDE3YWMwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGkOIJhES7Fu5nvCBRgOyHm0NVdYFAFnESbGwT4yCRM)
> 
> analogous for toppy bottomy will be with n, s, and row.

Thanks, it's a problem with the Bibata-Modern-Ice theme, changing the `-` to `_` in the filename works.

**Comment by FUFSoB** [comment]
> this one is a problem with your theme. Make sure you have a shape that fits `col_resize` and `row_resize`. Worth noting that due to (ugh) web using `-` and wl `_`.

That made me check implementation for wlroots and I found out they're using `-` in their `shape_names`. Is there a reason for using underscores in Hyprland's re-implementation?

Replacing underscores with dashes resolves initial issue with Xcursors. They do not disappear anymore.

[diff.txt](https://github.com/hyprwm/Hyprland/files/15190169/diff.txt)

**Comment by vaxerski** [comment]
hm, right. Maybe it was a mistake somewhere, I'll fix it.
