### ISSUE TITLE
Hyprland/Workspaces not working on git / Can't connect to IPC socket

### ISSUE THREAD

**Issue by mrizla** [hyprwm/Hyprland#5825]
### Hyprland Version

[-rizla@archlinux:~]hyprctl systeminfo
Hyprland, built from branch main at commit ed58cc4c31c21e09ee780d0df818afe935181cd9  (sessionLock: remove m_pLastFocus on destroy of surface).
Date: Wed May 1 02:33:36 2024
Tag: v0.39.1-117-ged58cc4c, commits: 4577

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.7-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:33 +0000

GPU information:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev c7) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

[-rizla@archlinux:~]

### Bug or Regression?

Bug

### Description

Using the git version (which has just been updated) seems to cause hyprland IPC socket not to be able to connect. I know this because Waybar still works but throws up the error saying it cant connect to the IPC socket therefore hyprland/workspaces is disabled.

the fix  is obviously just install Hyprland from the main repo.

I just wanted to let everyone know 

### How to reproduce

Install Hyprland-git with yay
start waybar through console to see error or just observe no workspaces on the bar
install Hyprland from main repos to fix

### Crash reports, logs, images, videos

<3

**Comment by DADA30000** [comment]
It's already fixed in waybar-git, wait for new release of waybar
workaround is `ln -s $XDG_RUNTIME_DIR/hypr /tmp/hypr`
