### ISSUE TITLE
Failed to install headers

### ISSUE THREAD

**Issue by Raze4284** [hyprwm/Hyprland#5829]
### Hyprland Version

Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

System Information:
System name: Linux
Node name: shinigami
Release: 6.6.26-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:11:08 UTC 2024

GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c2) (prog-if 00 [VGA controller])

os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

plugins:

### Bug or Regression?

Bug

### Description

[v] version returned: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

[v] parsed commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47 at branch HEAD

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                         
✔ cloned                                                                                        
[v] git returned: Эта ветка соответствует «origin/main».                                        
fatal: не является репозиторием git: ../../.git/modules/wlroots
fatal: could not reset submodule index

✔ checked out to running ver                                                                    
! configuring Hyprland                                                                          
[v] setting PREFIX for cmake to /home/shinigami/.local/share/hyprpm/headersRoot                 
[v] cmake returned: Not searching for unused variables given on the command line.               
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gathering git info
-- Found Python3: /usr/bin/python3.11 (found version "3.11.8") found components: Interpreter 
Building itab.c/itab.h...
-- Setting up wlroots
-- Found WaylandScanner at /usr/bin/wayland-scanner
-- Found wayland-protocols at //usr/share/wayland-protocols
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.0") 
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Checking for modules 'wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;libdrm;xkbcommon;libinput;pango;pangocairo;pixman-1'
--   Found wayland-server, version 1.22.0
--   Found wayland-client, version 1.22.0
--   Found wayland-cursor, version 1.22.0
--   Found wayland-protocols, version 1.33
--   Found cairo, version 1.18.0
--   Found libdrm, version 2.4.120
--   Found xkbcommon, version 1.6.0
--   Found libinput, version 1.25.0
--   Found pango, version 1.52.0
--   Found pangocairo, version 1.52.0
--   Found pixman-1, version 0.43.4
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Configuration supports execinfo
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- XWAYLAND Enabled (NO_XWAYLAND not defined) checking deps...
-- Checking for module 'xcb'
--   Found xcb, version 1.16.1
-- SYSTEMD support is requested (NO_SYSTEMD not defined) checking deps...
-- Looking for systemd/sd-daemon.h
-- Looking for systemd/sd-daemon.h - found
-- Checking for module 'libsystemd'
--   Found libsystemd, version 255
-- Systemd found
-- Setting precompiled headers
-- Setting link libraries
-- Checking for module 'tomlplusplus'
--   Found tomlplusplus, version 3.4.0
-- Configuring done (2.3s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/hyprland/build

[v] meson returned:                                                                             
ERROR: Neither source directory 'build' nor build directory None contain a build file meson.build.

✔ configured Hyprland                                                                           
[v] installation will run: sed -i -e "s#PREFIX = /usr/local#PREFIX = /home/shinigami/.local/share/hyprpm/headersRoot#" /tmp/hyprpm/hyprland/Makefile && cd /tmp/hyprpm/hyprland && make installheaders
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing sources[v] installer returned: mkdir -p /home/shinigami/.local/share/hyprpm/headersRoot/include/hyprland
mkdir -p /home/shinigami/.local/share/hyprpm/headersRoot/include/hyprland/protocols
mkdir -p /home/shinigami/.local/share/hyprpm/headersRoot/include/hyprland/wlroots
mkdir -p /home/shinigami/.local/share/hyprpm/headersRoot/share/pkgconfig
find src -name '*.h*' -print0 | cpio --quiet -0dump /home/shinigami/.local/share/hyprpm/headersRoot/include/hyprland
cd subprojects/wlroots/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /home/shinigami/.local/share/hyprpm/headersRoot/include/hyprland/wlroots && cd ../../..
/bin/sh: строка 1: cd: subprojects/wlroots/include: Нет такого файла или каталога
make: *** [Makefile:83: installheaders] Ошибка 1

✖ failed to install headers with error code 2                                                   
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed

### How to reproduce

Idk

### Crash reports, logs, images, videos

In description

**Comment by vaxerski** [comment]
you're on a very outdated version. Please update before reporting issues

**Comment by Raze4284** [comment]
> you're on a very outdated version. Please update before reporting issues

command? i newbie here :D

**Comment by vaxerski** [comment]
because manjaro is very behind on updates. Latest is 0.39.1
