### ISSUE TITLE
Add keybind to move workspace to current monitor

### ISSUE THREAD

**Issue by cid-chan** [hyprwm/Hyprland#583]
I think it would be useful to be able to keybind moving a specific workspace to the monitor that contains the mouse cursor.

It should behave as follows:
The keybind should find a workspace by its name and move it to the monitor containing the mouse cursor.
If the workspace does not exist, this binding should be a no-op.
If the workspace already belongs to the monitor, the workspace should not move monitors.
It may switch to the named workspace.

**Comment by vaxerski** [comment]
seems like just cluttering up the code. Why not script that? it can be done with 2 `hyprctl` calls.

**Comment by cid-chan** [comment]
How can I find out the current monitor on an empty workspace using hyprctl?

**Comment by cid-chan** [comment]
Found it:

```bash
      hyprctl dispatch moveworkspacetomonitor $1 $(hyprctl -j monitors | jq ' .[] | select(.focused == true) | .id')
      hyprctl dispatch workspace $1
```
