### ISSUE TITLE
[Enhancement] Hold off `exec-once` until a promgram is finished

### ISSUE THREAD

**Issue by fjueic** [hyprwm/Hyprland#5832]
### Description

It might be the [XY problem](https://xyproblem.info/) i will explain what im trying to do.
i'm auto logging in my arch linux using [greetd](https://wiki.archlinux.org/title/Greetd#Enabling_autologin) and session is locked immediately with `hyprlock`
`exec-once = hyprlock || hyprctl dispatch exit`
and all the other `exec-once` and commands are ran with it
is there a way to hold off execution of other commands until i unlock

a way to set the order of priority for `exec-once` sounds nice
like don't run commands until all others are finished

i know it possible with chaining && or bash script but directly in hyprland conf would be nice

**Comment by fjueic** [comment]
a workaround i have in mind is having two config file
one with `exec-once` in it which can be import as usual
and one with `exec` which i can import later

and i can trigger update with exec file once and remove it so it cause no further runs


i will try it implement this workaround but native would be good
thanks

**Comment by fjueic** [comment]
> a workaround i have in mind is having two config file one with `exec-once` in it which can be import as usual and one with `exec` which i can import later
> 
> and i can trigger update with exec file once and remove it so it cause no further runs
> 
> i will try it implement this workaround but native would be good thanks

working as intended

**Comment by vaxerski** [comment]
I don't think this makes sense as there are a dozen ways to do it already like you mentioned yourself, and it's quite a niche case.

**Comment by fjueic** [comment]
https://github.com/hyprwm/Hyprland/assets/89282645/afc2cd55-1ed0-4d45-8d00-fc385eefd553

@vaxerski sry for opening this again 

is there a way to deal with the flash of hyprland session before hyprlock runs?

**Comment by vaxerski** [comment]
that's probably the time where the image is being loaded. If you want to minimize it, choose a solid background, or make the image smaller, so that it loads faster.
