### ISSUE TITLE
Issues in Unreal Editor on Hyprland

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#5835]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.29-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 27 Apr 2024 18:43:45 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

There are two issues, this is only tested on Xwayland, getting UE to run on native wayland is a pain.

- When the display is scaled, the cursor selection isn't matched to the position in certain submenus in the UE Editor (only happens on xwayland with `force_zero_scaling = true`)
- There's some weird flickering in the same submenus

The issues only occur on Hyprland, not on Sway.

### How to reproduce

- Scale Display
- Install UE5 Editor
- Run UE Editor

### Crash reports, logs, images, videos

# Hyprland
(at the 10th second i'm setting the display scaling to 1)

https://github.com/hyprwm/Hyprland/assets/5684325/0b5e14de-0853-4ad4-8fa0-50f9e49e6cf9

# Sway

https://github.com/hyprwm/Hyprland/assets/5684325/2203f779-0cfe-48c0-b165-8daf923d7f98

**Comment by vaxerski** [comment]
#2127 ?

**Comment by Rabcor** [comment]
> #2127 ?

Unreal Editor isn't even using XWayland anymore, it's native Wayland now (otherwise it wouldn't be scaling for me in the first place).

But I can check if this is still an issue... It is.

Hyprland:
https://github.com/hyprwm/Hyprland/assets/5684325/38b36df2-0d94-439d-a29f-9e63c4d7458c

Sway:
Gimme 10 minutes to check if it's like this on sway as well. Gonna edit this post and add it in.

**Comment by Rabcor** [comment]
> #2127 ?

I have just now confirmed that the cursor issue in the OP only occurs when `force_zero_scaling = true`

**Comment by aforsbom1** [comment]
@Rabcor you can compile only SDL2 with wayland support on the side and use SDL_DYNAMIC_API env to point to the .so output. 

This way you can start UE with `SDL_DYNAMIC_API=/path/to/new/sdl2.so SDL_VIDEODRIVER=wayland` and UE will start as a native wayland application.

However it comes with other problems. The dropdowns doesnt work other than with the keyboard. I believe that issue is UE/SDL specific as dropdowns didnt work in any wayland compositor (ive tried with gnome, kde, sway, river, hyprland, weston and wayfire). Something is going on with xdg_popups and UEs way of tracking mouse position/focus. (Probably missing grab, commits or broken parent/child window relations somewhere, not sure)

**Comment by Rabcor** [comment]
> @Rabcor you can compile only SDL2 with wayland support on the side and use SDL_DYNAMIC_API env to point to the .so output.
> 
> This way you can start UE with `SDL_DYNAMIC_API=/path/to/new/sdl2.so SDL_VIDEODRIVER=wayland` and UE will start as a native wayland application.
> 
> However it comes with other problems. The dropdowns doesnt work other than with the keyboard. I believe that issue is UE/SDL specific as dropdowns didnt work in any wayland compositor (ive tried with gnome, kde, sway, river, hyprland, weston and wayfire). Something is going on with xdg_popups and UEs way of tracking mouse position/focus. (Probably missing grab, commits or broken parent/child window relations somewhere, not sure)

Oh I've tried that approach, it always just crashes either instantly or the first time i try to do pretty much anything

**Comment by aforsbom1** [comment]
@Rabcor, try checking my latest posts here, it might give you some ideas. Ie, using sdl2-compat which uses SDL3 in the background, UE seems to work fairly well for me in native wayland, including dropdowns and stuff. 

I've also tried with libdecor activated which seems to be working well also. The only windowrule that is absolutely needed is the noinitialfocus rule.

https://github.com/hyprwm/Hyprland/issues/2127#issuecomment-2364675031

**Comment by Rabcor** [comment]
> @Rabcor, try checking my latest posts here, it might give you some ideas. Ie, using sdl2-compat which uses SDL3 in the background, UE seems to work fairly well for me in native wayland, including dropdowns and stuff.
> 
> I've also tried with libdecor activated which seems to be working well also. The only windowrule that is absolutely needed is the noinitialfocus rule.
> 
> [#2127 (comment)](https://github.com/hyprwm/Hyprland/issues/2127#issuecomment-2364675031)

No dice, i tried with normal arch sdl2 from official repos, it crashes when i try to open a dropdown.

I tried with sdl2-compat (from git), it failed to create the window.

i tried with sdl2-git build, it went the same as official sdl2 package.

i tried with the various windowrules suggested in that thread, nothing seemed to fix the dropdown menu crash.

**Comment by Rabcor** [comment]
I have retested the issues i mentioned in the op, the scaling issue is  no longer present and the dropdown menus no longer flicker as much, there are still other issues with it, such as blueprints context menu not working if the window is floating, and i just had a crash from trying to copy nodes in a blueprint, but those can be reported in separate issues (ones I don't personally intend to make at this time)

**Comment by ural89** [comment]
still no fix?

**Comment by Rabcor** [comment]
> still no fix?

You could try getting the unreal editor to run on native wayland instead of through xwayland, that should fix all issues, but I couldn't manage it personally.

**Comment by ural89** [comment]
> > still no fix?
> 
> You could try getting the unreal editor to run on native wayland instead of through xwayland, that should fix all issues, but I couldn't manage it personally; so please do share if you figure out a way that works.

We can't if it doesn't support

**Comment by Rabcor** [comment]
> > > still no fix?
> > 
> > 
> > You could try getting the unreal editor to run on native wayland instead of through xwayland, that should fix all issues, but I couldn't manage it personally; so please do share if you figure out a way that works.
> 
> We can't if it doesn't support

It does support it, it just mysteriously only works sometimes.
