### ISSUE TITLE
Build is failing: alpha-modifier-v1.xml does not exist.

### ISSUE THREAD

**Issue by SDD701** [hyprwm/Hyprland#5839]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 185a3b48814cc4a1afbf32a69792a6161c4038cd  (swipe: nuke numbered).
Date: Thu Apr 11 18:46:19 2024
Tag: v0.38.0-92-g185a3b48, commits: 4425

flags: (if any)


System Information:
System name: Linux
Node name: ExilOS
Release: 6.6.21-gentoo-exilos
Version: #3 SMP PREEMPT_DYNAMIC Mon Mar 25 22:57:40 +07 2024


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Build is failing on gentoo-live ebuild: "protocols/meson.build:84:18: ERROR: File //usr/share/wayland-protocols/staging/alpha-modifier/alpha-modifier-v1.xml does not exist."

### How to reproduce

Try to emerge hyprland-9999

**Comment by gksudolol** [comment]
Can't reproduce on Gentoo ~amd64, though I'm also building `hyprwayland-scanner-9999` and bumped libzip to 1.10.1

**Comment by SDD701** [comment]
> Can't reproduce on Gentoo ~amd64, though I'm also building `hyprwayland-scanner-9999` and bumped libzip to 1.10.1

Strange, looks like there is no [such](https://gpo.zugaina.org/dev-libs/libzip) [ebuilds](https://gpo.zugaina.org/dev-util/hyprwayland-scanner) even in overlays. Is it custom?

**Comment by gksudolol** [comment]
> > Can't reproduce on Gentoo ~amd64, though I'm also building `hyprwayland-scanner-9999` and bumped libzip to 1.10.1
> 
> Strange, looks like there is no [such](https://gpo.zugaina.org/dev-libs/libzip) [ebuilds](https://gpo.zugaina.org/dev-util/hyprwayland-scanner) even in overlays. Is it custom ebulds?

Yes

It looks like your `wayland-protocols` is out of date

```
equery b /usr/share/wayland-protocols/staging/alpha-modifier/alpha-modifier-v1.xml

dev-libs/wayland-protocols-1.36 (/usr/share/wayland-protocols/staging/alpha-modifier/alpha-modifier-v1.xml)
```

**Comment by gksudolol** [comment]
Sharing the ebuilds for prosperity
[hyprwayland-scanner-9999.txt](https://github.com/hyprwm/Hyprland/files/15185843/hyprwayland-scanner-9999.txt)
[libzip-1.10.1.txt](https://github.com/hyprwm/Hyprland/files/15185844/libzip-1.10.1.txt)

**Comment by SDD701** [comment]
> > > Can't reproduce on Gentoo ~amd64, though I'm also building `hyprwayland-scanner-9999` and bumped libzip to 1.10.1
> > 
> > 
> > Strange, looks like there is no [such](https://gpo.zugaina.org/dev-libs/libzip) [ebuilds](https://gpo.zugaina.org/dev-util/hyprwayland-scanner) even in overlays. Is it custom ebulds?
> 
> Yes
> 
> It looks like your `wayland-protocols` is out of date
> 
> ```
> equery b /usr/share/wayland-protocols/staging/alpha-modifier/alpha-modifier-v1.xml
> 
> dev-libs/wayland-protocols-1.36 (/usr/share/wayland-protocols/staging/alpha-modifier/alpha-modifier-v1.xml)
> ```

Yep, emerging `wayland-protocols-9999` solved the issue, thank you
