### ISSUE TITLE
Cannot change TTY using Ctrl-Alt-Fx

### ISSUE THREAD

**Issue by rharish101** [hyprwm/Hyprland#584]
I can't use shortcuts like Ctrl-Alt-F2 to switch the TTY. I can do it in Sway, but not in Hyprland.

Here are some relevant files:
- [hyprland.log](https://github.com/hyprwm/Hyprland/files/9434980/hyprland.log)
- [~/.config/hypr/hyprland.conf](https://github.com/hyprwm/Hyprland/files/9434994/hyprland.conf.txt) (as a .txt file)
- [~/.config/hypr/keybinds.conf](https://github.com/hyprwm/Hyprland/files/9434996/keybinds.conf.txt) (as a .txt file)

I'm running Hyprland v0.11.1beta on Arch Linux.

**Comment by vaxerski** [comment]
should be fixed in a648b452ddc64f1f9507f4f4ec995fb5c6764b9a
