### ISSUE TITLE
[feature request] applying scaling or not

### ISSUE THREAD

**Issue by Vagahbond** [hyprwm/Hyprland#5842]
Related to hyprwm/hyprlock#261

When running older versions of hyprland and hyprlock, it seems the scaling is not applied to hyprlock. 

With the latest version now, which is `ed58cc4c31c21e09ee780d0df818afe935181cd9`, I have a scaled hyprlock with blurry labels and a pixelated image. 

Some people want to have it scaled, other such as me liked it how it was before. 

Is it possible to make it into an option ? 

Sorry if this issue belongs to hyprwm/Hyprland

**Comment by vaxerski** [comment]
fixed in hyprlock as well. Either works, you don't need both.

**Comment by Vagahbond** [comment]
Thanks man, that was fast af
