### ISSUE TITLE
Hypr's own Desktop Manager 

### ISSUE THREAD

**Issue by its-19818942118** [hyprwm/Hyprland#5844]
### Description

So when logging in from either sddm or light dm or etc. there will always be a black screen as running scripts and can be slow sometimes. So a hyprlands own DM I think this issue can be solved with the added 
### **_Enhancement for customizable loading splashscreen and ability to run terminal or shell scripts_**.
 As there are projects that enables terminal to use play a video as ASCII. Plus added bonus of having a nice ecosystem **HyprWM**. I know it maybe a lot of work but I have expectations that hyprland can advance with this. :)

**Comment by vaxerski** [comment]
running scripts is not the reason for the black screen, handing over the drm master and resetting the crtc is.

At any rate, there are no plans for a login manager.

**Comment by its-19818942118** [comment]
Ok

**Comment by its-19818942118** [comment]
Then anyways to get rid of the black screen?

**Comment by vaxerski** [comment]
not that I know of.

**Comment by its-19818942118** [comment]
Aight
