### ISSUE TITLE
Window focus cannot follow the cursor.

### ISSUE THREAD

**Issue by LzzKill** [hyprwm/Hyprland#5856]
### Hyprland Version

<details> <summary>System/Version info</summary>
OS: Arch Linux 

Hyprland Version:(use ` hyprctl version `)

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

</details>

### Bug or Regression?

Bug

### Description

I do something on one window, and then I move the cursor to another window, but the keyboard action is still mapped to that window (the non-focused window, which is the previous window)

### How to reproduce

It's not hard to reproduce this problem. First you open a code editor (e.g. neovim), then you open a browser (e.g. Firefox), you type some text in the browser, and then switch to the editor to reproduce the problem, as evidenced by the video:

https://github.com/hyprwm/Hyprland/assets/76607157/0147a9ca-744a-41f1-8a28-e4b81716ad82

### Crash reports, logs, images, videos

I found some config in Wiki, they is:

```
misc {
  always_follow_on_dnd = true 
  layers_hog_keyboard_focus = true 
}
```

By the way, they not work maybe.

**Comment by hieulw** [comment]
I can't reproduce like your video, but I experienced this in latest release as well, I use win + workspace number to switch between firefox and neovim. When I switch to neovim (workspace 1) the keyboard focus still in firefox (workspace 2), it not always happen but quite frequently. Weird thing is the mouse focus is working, I can click the mouse to move the cursor in neovim but not the keyboard.

I think I can reproduce this when open wofi and close fast, notice I can click mouse but cannot type anything (I don't have screenkey but I actually typing)

https://github.com/hyprwm/Hyprland/assets/13571960/279a7410-3db4-42db-9f40-5df5c9642f27

**Comment by sungyoonc** [comment]
#5763

**Comment by vaxerski** [comment]
it is like the 10 other dupes
