### ISSUE TITLE
Coredump after reloading Hyprland

### ISSUE THREAD

**Issue by paulhaider** [hyprwm/Hyprland#5858]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d5bf15387ad3b4ee36cae7a3cd9f4a9c28790f2e  (internal: fix a few asan reported leaks on exit of hyprland (5852)).
Date: Fri May 3 15:42:08 2024
Tag: v0.39.1-135-gd5bf1538, commits: 4595

flags: (if any)


System Information:
System name: Linux
Node name: framework
Release: 6.6.26-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:11:08 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes immediately after calling `hyprctl reload` on latest commit [d5bf153](https://github.com/hyprwm/Hyprland/commit/d5bf15387ad3b4ee36cae7a3cd9f4a9c28790f2e)

### How to reproduce

Log into hyprland and call `hyprctl reload`

### Crash reports, logs, images, videos

File for crash report is created in `~/.cache/hyprland` but empty
Coredump exists though

[coredump.txt](https://github.com/hyprwm/Hyprland/files/15202849/coredump.txt)

**Comment by vaxerski** [comment]
I think 1c73beaf9bf98ba76f89fbfc137b51a0c92063a3 fixes this?

**Comment by paulhaider** [comment]
yes it did!
