### ISSUE TITLE
animate movetoworkspacesilent

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#586]
Title speaks for itself!

**Comment by vaxerski** [comment]
no, it doesn't. Wtf do u mean

**Comment by Dickby** [comment]
If i use `movetoworkspacesilent` the moved window just disapears, i think it should either fade or slide out!

**Comment by Dickby** [comment]
btw, switching to fullscreen would look nicer if the not focused windows would have an animated fading or sliding animation instead of just disapearing aswell.

**Comment by Estebiu** [comment]
But.. as the name says.. it's supposed to be silent, not fancy as you want it to be

**Comment by Dickby** [comment]
@Estebiu : That's wrong, the silent (as i understand it) is opposed to movetoworkspace means it doesn't switch the focus to that workspace, so it "silently" removes that window from the active workspace.
@vaxerski what's the actual intended meaning? if Estebiu is right i want a "movetoworkspacedontchangeworkspaceanimated"
but that would be just weird.

**Comment by izmyname** [comment]
Judging from the looking at the disscussion - this isn't gonna be imolemented. Worth closing?

**Comment by ErrorNoInternet** [comment]
wasn't this implemented in b9b8e6220f55af34e862b541a5a4b30ae6d8f15f? 

(also it doesnt seem to work for moving to special workspaces

**Comment by vaxerski** [comment]
ah yes was
