### ISSUE TITLE
Hyprland crashing a lot after moving to the new Vkeyboard impl

### ISSUE THREAD

**Issue by FlyingButteryTuna** [hyprwm/Hyprland#5860]
### Hyprland Version

<details> <summary>System/Version info</summary>
(temporarily downgraded)
Hyprland, built from branch  at commit a3ca016d42283ce1d2d5ffca40b93123b4290f4b  (cursor-shape: use - instead of _ in shapes). 
Date: Thu May 2 18:21:33 2024
Tag: v0.39.1-128-ga3ca016d, commits: 4588

flags: (if any)

System Information:
System name: Linux
Node name: arch-pc
Release: 6.8.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] [10de:1c02] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
</details>

### Bug or Regression?

Regression

### Description

since 6aa2d123ae2a601a1775486f6988385124de9369 I pretty can't do anything on my system without Hyprland crashing.
I also can't copy anything into the system's clip board from kitty. 

### How to reproduce

opening kitty and then trying to switch to another workspace/switch active window, hyprctl reload or updating kitty's opacity crashes, launching hyprpicker inside alacritty causes a crash etc, etc. 

### Crash reports, logs, images, videos

[hyprlandCrashReport15336.txt](https://github.com/hyprwm/Hyprland/files/15203135/hyprlandCrashReport15336.txt)
[hyprlandCrashReport14016.txt](https://github.com/hyprwm/Hyprland/files/15203136/hyprlandCrashReport14016.txt)
[hyprlandCrashReport12931.txt](https://github.com/hyprwm/Hyprland/files/15203137/hyprlandCrashReport12931.txt)

**Comment by vaxerski** [comment]
the stacktrace is completely bork. Can you build in debug and get the debug stacktrace? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by gulafaran** [comment]
the logs say you are on commit d5bf15387ad3b4ee36cae7a3cd9f4a9c28790f2e not the one you linked, https://github.com/hyprwm/Hyprland/commit/1c73beaf9bf98ba76f89fbfc137b51a0c92063a3 should solve it

**Comment by vaxerski** [comment]
yea I think it's fixed
