### ISSUE TITLE
Hyprland crashes on start. Error m_sWLRRenderer was NULL! and Critical error thrown: wlr_gles2_renderer_create_with_drm_fd() failed!

### ISSUE THREAD

**Issue by choppystorm** [hyprwm/Hyprland#5862]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
```

</details>

### Bug or Regression?

Bug

### Description

When i start my computer i try to log in with sddm and it does not work so i go to a new tty and and type in the command Hyprland and it crashes with the errors 
[CRITICAL] m_sWLRRenderer was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_gles2_renderer_create_with_drm_fd() failed!
i have no clue how this happened
i have a NVIDIA GPU if that maters
for the hyprland version because i cant start it i cant run the command to see it. i just updated to latest git with yay so it should be latest git. 
also i have kde plasma installed and both Wayland and x11 work so i don't think it is a GPU problem. 
just in case this matters i have a ryzen 5 5600x as my cpu

### How to reproduce

restart computer. try to login with sddm does not work. go to new tty and type in Hyperland command. crashes 

### Crash reports, logs, images, videos

[hyprlandCrashReport19469.txt](https://github.com/hyprwm/Hyprland/files/15205616/hyprlandCrashReport19469.txt)

**Comment by vaxerski** [comment]
this is an nvidia issue. Read the nvidia wiki page, and if that doesn't work, you're out of luck.

**Comment by Andreas-Hjortland** [comment]
I had the same issue, and I had to remove the `WLR_NO_HARDWARE_CURSORS` environment variable from the hyprland config which was previously recommended. If you haven't solved your issue yet @choppystorm, you might want to look into that.

**Comment by timitoerner** [comment]
I have the same issue but I am on AMD with nixos
