### ISSUE TITLE
Hyprland Crashing Shortly After Launch

### ISSUE THREAD

**Issue by dotaxis** [hyprwm/Hyprland#5863]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
os-release:
	NAME="Garuda Linux"
	PRETTY_NAME="Garuda Linux"
	ID=garuda
	ID_LIKE=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://garudalinux.org/"
	DOCUMENTATION_URL="https://wiki.garudalinux.org/"
	SUPPORT_URL="https://forum.garudalinux.org/"
	BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=garudalinux
```

</details>

### Bug or Regression?

Bug

### Description

Just updated to latest git release and now Hyprland crashes right after I log in.

### How to reproduce

Launch Hyprland

### Crash reports, logs, images, videos

[hyprlandCrashReport335954.txt](https://github.com/hyprwm/Hyprland/files/15205750/hyprlandCrashReport335954.txt)
[hyprlandCrashReport70342.txt](https://github.com/hyprwm/Hyprland/files/15205751/hyprlandCrashReport70342.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15205756/hyprland.log)

**Comment by dotaxis** [comment]
Building from 1d2acbe19355c8640d54a4b6cba225c6f4370c85 does not crash

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15205781/patch.txt)
try this

**Comment by dotaxis** [comment]
Looks like that worked :)
