### ISSUE TITLE
Crash with fcitx5 when opening new window

### ISSUE THREAD

**Issue by sungyoonc** [hyprwm/Hyprland#5868]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 40201a760acd7c5ca10f27e7d0fdeb71c20df89f  (workspacerule: Fix monitor settings being deleted when merging ws rules (5864)).
Date: Sat May 4 10:18:04 2024
Tag: v0.39.1-141-g40201a76, commits: 4601

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

First bad commit: 1237732b97fcf21a19aed16f2ef966118a3ca2aa
When I open a new window with a text input being focused, hyprland crashes.
Also when I `pkill -9 fcitx5`, hyprland crashes.

### How to reproduce

With fcitx5 5.1.9
1. Open firefox and select a text input
2. Open a terminal
3. Crash

### Crash reports, logs, images, videos

[crashreport_open_window.txt](https://github.com/hyprwm/Hyprland/files/15206521/crashreport_open_window.txt)
[crashreport_pkill_fcitx.txt](https://github.com/hyprwm/Hyprland/files/15206522/crashreport_pkill_fcitx.txt)

**Comment by hdm9527** [comment]
It could be this commit 1237732b97fcf21a19aed16f2ef966118a3ca2aa issue

**Comment by sungyoonc** [comment]
> It could be this commit [1237732](https://github.com/hyprwm/Hyprland/commit/1237732b97fcf21a19aed16f2ef966118a3ca2aa) issue

Yup, I already bisected it to that commit
