### ISSUE TITLE
fcitx5 in xfce4-terminal dropdown window can not show candidates in 0.39

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#5871]
### Hyprland Version

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

System Information:
System name: Linux
Node name: vincent-laptop
Release: 6.6.26-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:11:08 UTC 2024

GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
VERSION=rolling

plugins:
  hyprscroller by dawser ver 1.0

### Bug or Regression?

Regression

### Description

fcitx5 did not show candidates in xfce4-terminal dropdown window which is not a normal window(not listed in clients or obey window rules ) after I upgrade hyprland from 0.36 to 0.39 in manjaro.
xfce4-terminal dropdown is weird, fcitx is tricky, many apis change, I cannot figure out the cause why candidates not shown, but I do know the same fcitx5 works normally before in hyprland 0.36.

### How to reproduce

use fcitx5 in xfce4-terminal dropdown in hyprland 0.39

**Comment by vaxerski** [comment]
have you tried -git?

**Comment by vincentaxhe** [comment]
no, I think the version I used is pretty close to git. highly likely the problem remains. 
since dropdown window is quite out of law, I decide not to rely on it, I have figure out a workaround, use alacritty with class open a tmux session, with size , move ,stayfocused rule.
works almost the same.
just report a regression, hell know where could be wrong.

**Comment by luyu-wu** [comment]
> no, I think the version I used is pretty close to git. highly likely the problem remains. since dropdown window is quite out of law, I decide not to rely on it, I have figure out a workaround, use alacritty with class open a tmux session, with size , move ,stayfocused rule. works almost the same. just report a regression, hell know where could be wrong.

Please do try git, some fcitx-5 related issues were fixed between 0.39 and 0.40. Usually it's good courtesy to make sure your issue hasn't been fixed already before posting (even if they case it hasn't, just for the future).
