### ISSUE TITLE
Idle inhibitor not working with layer surface

### ISSUE THREAD

**Issue by sungyoonc** [hyprwm/Hyprland#5878]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a3309b51a254f142c535022615be6f76eb23fa9b  (shadow: fix small pixel gaps between border).
Date: Sun May 5 04:30:03 2024
Tag: v0.40.0-1-ga3309b51, commits: 4607

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When idle inhibitor is associated with a layer surface (e.g. waybar) or is not associated to any window, idle inhibitor does not work.

### How to reproduce

Activate idle inhibitor with waybar

### Crash reports, logs, images, videos

```
[LOG] Registered signal for owner 5f0a3147c260: 5f0a31462808 -> 5f0a3147c2c0 (owner: CIdleInhibitorResource)
[LOG] New idle inhibitor registered for surface 5f0a314624f0
[WARN] Inhibitor is for no window?
[LOG] Registered signal for owner 5f0a314fec50: 5f0a31463bd8 -> 5f0a314fecb0 (owner: CIdleInhibitorResource)
[LOG] New idle inhibitor registered for surface 5f0a314638c0
[WARN] Inhibitor is for no window?
```

**Comment by vaxerski** [comment]
oopsie daisy

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15211159/patch.txt)
does this work?

**Comment by vaxerski** [comment]
made some minor changes and it works.

**Comment by sungyoonc** [comment]
Yup, it's working now thanks

**Comment by zakk4223** [comment]
Pretty sure this broke command line inhibitors like wljoywake and wayland-idleinhibitor

**Comment by sungyoonc** [comment]
> Pretty sure this broke command line inhibitors like wljoywake and wayland-idleinhibitor

@zakk4223 Can you test this? #5882

**Comment by zakk4223** [comment]
That fixes it
