### ISSUE TITLE
 qBittorrent Transparency Theme Glitch and Blur issue 

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#5890]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit 589f758d947cb4e8b888d2da00076a9fb0a6d521  (CI/Nix: build with submodules).
Date: Sun May 5 19:00:39 2024
Tag: v0.40.0-8-g589f758d, commits: 4614

flags: (if any)


System Information:
System name: Linux
Node name: elite
Release: 6.8.7-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

It seems that qBittorrent behaves oddly when I use the transparent theme on Hyprland, as shown in the video. The issue doesn't seem to affect the special workspace(some times). 
#### Also, the **_blur_** doesn't work with qBittorrent. 

#
https://github.com/hyprwm/Hyprland/assets/54718375/6368a8ed-5015-4170-bcb3-ecdcd3a6fcb0

### How to reproduce

use this theme with qbit --> [Link](https://github.com/witalihirsch/qBitTorrent-fluent-theme/raw/main/themes/fluent-dark.qbtheme)

**Comment by vaxerski** [comment]
this is a qbittorrent issue. It likely marks itself as opaque when it isn't. You probably can solve this with a windowrule for opacity 0.9999
