### ISSUE TITLE
XF86ScreenSaver key not working 

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/Hyprland#5892]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit 589f758d947cb4e8b888d2da00076a9fb0a6d521  (CI/Nix: build with submodules).
Date: Sun May 5 19:00:39 2024
Tag: v0.40.0-8-g589f758d, commits: 4614

flags: (if any)


System Information:
System name: Linux
Node name: elite
Release: 6.8.7-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

XF86ScreenSaver not working 

wev output 

```bash
[14:     wl_keyboard] key: serial: 21521; time: 7218986; key: 160; state: 1 (pressed)
                      sym: XF86ScreenSaver (269025069), utf8: ''
[14:     wl_keyboard] key: serial: 21522; time: 7218986; key: 160; state: 0 (released)
                      sym: XF86ScreenSaver (269025069), utf8: ''
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 64754
```

![Sunday_18_2024_21_33_37_PM](https://github.com/hyprwm/Hyprland/assets/54718375/8844c822-8abb-459a-bc08-a1a5b67cf435)

### How to reproduce

`bind = ,XF86ScreenSaver, exec, hyprctl notify 5 2000 "rgb(22DA6E)" " i am working"`

add this keybind in your config

**Comment by vaxerski** [comment]
have you tried binding by code? lowercase?

**Comment by shadowelite-sec** [comment]
Yes, the code is working!

But I'm pretty sure XF86ScreenSaver worked before. I commented out this keybind for some reason for a long time. I just uncommented this today. I don't know; I think something affected this keybind.

**Comment by ikalco** [comment]
try this patch
[patch.txt](https://github.com/hyprwm/Hyprland/files/15214360/patch.txt)

**Comment by shadowelite-sec** [comment]
> try this patch [patch.txt](https://github.com/hyprwm/Hyprland/files/15214360/patch.txt)

yes now  XF86ScreenSaver is working but 

some keys stoped working 

eg :
```
$mainMod = SUPER

bind = $mainMod, RETURN, exec, foot
bind = $mainMod, SPACE, exec, ~/.config/rofi/bin/launcher

```

**Comment by ikalco** [comment]
oops, try this
[patch.txt](https://github.com/hyprwm/Hyprland/files/15220909/patch.txt)

**Comment by shadowelite-sec** [comment]
> oops, try this [patch.txt](https://github.com/hyprwm/Hyprland/files/15220909/patch.txt)

yes its working now :smiley_cat:

**Comment by ikalco** [comment]
this can be closed btw
