### ISSUE TITLE
Drop-down menu sometimes appears behind floating XWayland windows

### ISSUE THREAD

**Issue by ManEnfu** [hyprwm/Hyprland#590]
### How to reproduce

- Launch an XWayland application (e.g. krita)
- Make the window floating
- Open a drop-down menu (e.g. by clicking **File** on the menubar)
- Close the menu
- Reopen the menu

### Expected Outcome
The menu should appear in front of the window.

### Observed Outcome
At first glance, the menu seems to not appear. But when you drag the window away, you can see that the menu is spawned behind the window.

The same thing happened in VLC. where it affects the menubar. However, right click menu works as expected. 

![2022-08-28_16-54-21](https://user-images.githubusercontent.com/36270245/187071245-f66bde2d-cb70-42e9-b467-0f9f6b4cd4ab.png)

**Comment by vaxerski** [comment]
yeah I am aware

**Comment by vaxerski** [comment]
fixed in 5da114477fdb1c806f5ad6f6fbb22903481f24c1
