### ISSUE TITLE
Gnome apps refuse to start after Hyprland restart

### ISSUE THREAD

**Issue by acheong08** [hyprwm/Hyprland#5901]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit cddeec47a1fc0e70d8598fd10c29cd0e9489999f  (keybinds: make the keybind manager check for session lock (5894)).
Date: Sun May 5 19:28:14 2024
Tag: v0.40.0-11-gcddeec47, commits: 4617

flags: (if any)


System Information:
System name: Linux
Node name: fish
Release: 6.8.8-300.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:53:31 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

After exiting hyprland to tty with `SUPER+M` and then running `Hyprland` again, gnome apps won't start and performance for all apps drops

### How to reproduce

1. Boot into tty
2. run `Hyprland`
3. `SUPER+M` to quit Hyprland
4. run `Hyprland`
5. Do stuff

### Crash reports, logs, images, videos

```
$ gnome-calendar

(gnome-calendar:3848): Gtk-WARNING **: 20:36:23.481: Theme parser error: gtk.css:7521:21-28: Expected a valid color.
```

Waybar slows down but still starts:
```
 $ [2024-05-05 20:35:27.679] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
```

I noticed that `xdg-desktop-portal-hyprland.service` is dead, so started that up but nothing changed.

**Comment by Aqa-Ib** [comment]
Probably something wrong with your portals.
Do you have xdg-desktop-portal-gtk installed?
Do you have any config file in ~/.config/xdg-desktop-portal ?

**Comment by acheong08** [comment]
Yes it is installed but refuses to start the second time. Everything works during the first. It only breaks after killing Hyprland and then running again without restart

**Comment by ikalco** [comment]
I don't remember where I saw this but it might be a dbus issue even if you export the variables to dbus in the hyprland.conf
Try this to check
`dbus-run-session Hyprland`

**Comment by acheong08** [comment]
> `dbus-run-session Hyprland`

This indeed works

**Comment by izmyname** [comment]
Prolly, this is why everyone adds this stuff to autostart

```
 exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```
