### ISSUE TITLE
Compositor crashing to tty when clicking on MuseScore 2 Main manu items

### ISSUE THREAD

**Issue by RedIODev** [hyprwm/Hyprland#5903]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 16:24:13 2024
Tag: v0.38.1

flags: (if any)


System Information:
System name: Linux
Node name: hpc
Release: 6.6.15-amd64
Version: #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2 (2024-02-04)


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1) (prog-if 00 [VGA controller])


os-release: PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The compositor crashed to tty after clicking a main menu item.
Im not sure rather I should put this here or on MuseScore2 as it most likely caused the crash. 
I think putting it here makes more sense since an application having a problem in the main menu shouldn't crash the compositor.

### How to reproduce

Open MuseScore 2.
Click on any entry of the main  menu.
The compositor crashes

### Crash reports, logs, images, videos

[hyprlandCrashReport159996.txt](https://github.com/hyprwm/Hyprland/files/15214796/hyprlandCrashReport159996.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15214806/hyprland.log)

**Comment by MightyPlaza** [comment]
try latest version

**Comment by RedIODev** [comment]
I will come back to this once my system is stable again. The problem occurred during a distro update I unintentionally initiated using apt that broke my entire system after a reboot. I rolled back the system so I can't test rather this problem is related (likely).

**Comment by vaxerski** [comment]
this was fixed ages ago
