### ISSUE TITLE
Hyprlock or Swaylock is not usable after session-lock's new impl

### ISSUE THREAD

**Issue by RyuuyaS** [hyprwm/Hyprland#5913]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch test at commit d7a48cf47816041c5cb705c9de218c3395635822 dirty (hyprctl: use XDG_RUNTIME_DIR if available).
Date: Tue Apr 30 20:17:35 2024
Tag: v0.39.1-110-gd7a48cf4, commits: 4570

flags: (if any)


System Information:
System name: Linux
Node name: 192.168.101.3
Release: 6.8.8-200.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:42:13 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] [1002:1636] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:
  hyprsplit by shezdy ver 1.0


```

</details>

### Bug or Regression?

Bug

### Description

As I have described in the [hyprlock issue](https://github.com/hyprwm/hyprlock/issues/305), hyprlock or swaylock will crash and auto unlock after a few minutes (10 or so). I have tried to narrow it down to the commit [`90e1411`](https://github.com/hyprwm/Hyprland/commit/90e1411315065ead5b5a7873be4109bdfb9f5470) which is the root of the problem.

### How to reproduce

1. Build Hyprland from this commit  [`90e1411`](https://github.com/hyprwm/Hyprland/commit/90e1411315065ead5b5a7873be4109bdfb9f5470) or above.
2. Run the hyprlock from the terminal. 

### Crash reports, logs, images, videos

hyprlock log, the detailed one you can find in [this issue](https://github.com/hyprwm/hyprlock/issues/312)
```
[LOG] [core] dmabufFeedbackMainDevice
[LOG] output 52 make LG Display model 0x05FE
[LOG] output 52 name eDP-1
[LOG] output 52 description LG Display 0x05FE (eDP-1)
[LOG] output 52 done
[LOG] Running on Hyprland
[LOG] Locking session
[ERR] Pam module "hyprlock" not found! Falling back to "su"
[WARN] Extension: .png
[LOG] eglQueryDmaBufModifiersEXT found 8 mods
[LOG] bo chose modifier 0
[LOG] onLockFinished called. Seems we got yeeten. Is another lockscreen running?
[LOG] Got dma frame with size [Vector2D: x: 1920, y: 1080]
[LOG] PAM_PROMPT: Password:
```

### Workaround
Build Hyprland with commit [`d7a48cf`](https://github.com/hyprwm/Hyprland/commit/d7a48cf47816041c5cb705c9de218c3395635822)

**Comment by ikalco** [comment]
can you give hyprland.log

**Comment by RyuuyaS** [comment]
This log uses the latest git to reproduce the bug
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15222754/hyprland.log)

**Comment by vaxerski** [comment]
can you get the log with timestamps? From what I understand the lock just goes away after a while but the lock process (e.g. swaylock) is still running?

**Comment by vaxerski** [comment]
well, I've ran hyprlock for 4h and it hasn't happened to me. I'll need more info.

**Comment by RyuuyaS** [comment]
Sorry for the late response.

>  From what I understand the lock just goes away after a while but the lock process (e.g. swaylock) is still running?


https://github.com/hyprwm/Hyprland/assets/85359791/4431f434-e955-42a4-8e3b-6d0006cb8eb6

Yes

This is log with timestamps - [hyprland.log](https://github.com/hyprwm/Hyprland/files/15238031/hyprland.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15238114/patch.txt)
try this patch

**Comment by RyuuyaS** [comment]
I have tested the patch with two branches [`a8a04c74`](https://github.com/hyprwm/Hyprland/commit/a8a04c746b07fe80bb852bb42473d58868d3b294) and [`2bcc8d30`](https://github.com/hyprwm/Hyprland/commit/2bcc8d303f889432171c5113af5f2962858099a4) but can't test on the latest git due to from [`ec092bd`](https://github.com/hyprwm/Hyprland/commit/ec092bd601d9d351ff6ca34bd97f12055b2a4dd9) and above result in fail when building. But can confirm that the patch works.
