### ISSUE TITLE
Recurrent crashing during daily use (non heavy loads)

### ISSUE THREAD

**Issue by shinobiultra** [hyprwm/Hyprland#5914]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a8a04c746b07fe80bb852bb42473d58868d3b294  (renderer: deny solitary during a session lock).
Date: Mon May 6 03:24:11 2024
Tag: v0.40.0-12-ga8a04c74, commits: 4618

flags: (if any)


System Information:
System name: Linux
Node name: LAPArchee
Release: 6.8.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 630 [8086:591b] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

During daily use (Firefox, VSCode, SSH, SSHFS with SWWW, Waybar, etc.) I keep running into this weird Hyprland/Wayland crash. My HW is `Asus GL753VD` with Nouveau.

After that, it's straight to the SDDM login screen again. Also, I've had some (probably unrelated) issues with SWWW causing even weirder mishaps. During use of STM32CubeMX and hovering with mouse over the pin layout (nothing else caused it) the STM32CubeMX window would disappear and take VSCode with it. Even when not doing anything with the VSCode at the moment, having it on another workspace, they just disappear together and can't be restarted (killed and relaunched)!! 

I've noticed that disabling SWWW has some effect on decreasing the probability of this happening significantly but I still think it happened at least once even when SWWW was killed after login.

During the main issue described here (the crash), the SWW is running, 2 external monitors are connected.

SWWW package details:
```sh
Name            : swww-git
Version         : 0.9.5.r28.g9733f3e-1
Description     : Efficient animated wallpaper daemon for Wayland, controlled at runtime
Architecture    : x86_64
URL             : https://github.com/LGFae/swww
Licenses        : GPL-3.0-or-later
Groups          : None
Provides        : swww
Depends On      : libxkbcommon  lz4
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : swww
Replaces        : None
Installed Size  : 4.62 MiB
Packager        : Filip Kucera <24391713+shinobiultra@users.noreply.github.com>
Build Date      : Mon 06 May 2024 11:23:49 AM CEST
Install Date    : Mon 06 May 2024 11:26:49 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

### How to reproduce

Honestly, am not entirely sure what causes this... Last time happened to me during browsing of `sshfs` mounted directory with large files using `ranger`.

### Crash reports, logs, images, videos

# `sudo journalctl -r`:

May 06 16:14:57 LAPArchee wpa_supplicant[2526]: wlan0: CTRL-EVENT-BEACON-LOSS
May 06 16:14:55 LAPArchee systemd[1]: systemd-coredump@5-179001-0.service: Deactivated successfully.
May 06 16:14:55 LAPArchee systemd-coredump[179002]: [🡕] Process 167485 (Xwayland) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 167485:
                                                    #0  0x00007a9b3a758194 n/a (libc.so.6 + 0x90194)
                                                    #1  0x00007a9b3a704d70 raise (libc.so.6 + 0x3cd70)
                                                    #2  0x00007a9b3a6ec4c0 abort (libc.so.6 + 0x244c0)
                                                    #3  0x000061eb851e5ecd n/a (Xwayland + 0x152ecd)
                                                    #4  0x000061eb851e84dd n/a (Xwayland + 0x1554dd)
                                                    #5  0x000061eb850ad3df n/a (Xwayland + 0x1a3df)
                                                    #6  0x00007a9b3a6edd4a n/a (libc.so.6 + 0x25d4a)
                                                    #7  0x00007a9b3a6ede0c __libc_start_main (libc.so.6 + 0x25e0c)
                                                    #8  0x000061eb850ade15 n/a (Xwayland + 0x1ae15)
                                                    
                                                    Stack trace of thread 167503:
                                                    #0  0x00007a9b3a7528d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007a9b3a755299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007a9b252863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007a9b2529ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007a9b3a7561cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007a9b3a7d76ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 167500:
                                                    #0  0x00007a9b3a7528d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007a9b3a755299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007a9b252863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007a9b2529ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007a9b3a7561cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007a9b3a7d76ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 167502:
                                                    #0  0x00007a9b3a7528d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007a9b3a755299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007a9b252863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007a9b2529ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007a9b3a7561cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007a9b3a7d76ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 167501:
                                                    #0  0x00007a9b3a7528d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007a9b3a755299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007a9b252863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007a9b2529ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007a9b3a7561cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007a9b3a7d76ec n/a (libc.so.6 + 0x10f6ec)
                                                    ELF object binary architecture: AMD x86-64
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/opus_05_duplex
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/opus_05_duplex
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/opus_05
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/opus_05
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/faststream_duplex
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/faststream
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aptx_ll_0
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aptx_ll_1
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/sbc_xq
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/sbc_xq
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/sbc
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/sbc
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aac
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/aac
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aptx
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/aptx
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/aptx_hd
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSink/aptx_hd
May 06 16:14:55 LAPArchee sddm[530]: Running: /usr/bin/X -nolisten tcp -background none -seat seat0 vt2 -auth /run/sddm/xauth_QxdGbd -noreset -displayfd 18
May 06 16:14:55 LAPArchee sddm[530]: Writing cookie to "/run/sddm/xauth_QxdGbd"
May 06 16:14:55 LAPArchee sddm[530]: Display server starting...
May 06 16:14:55 LAPArchee sddm[530]: Using VT 2
May 06 16:14:55 LAPArchee sddm[530]: Xauthority path: "/run/sddm/xauth_QxdGbd"
May 06 16:14:55 LAPArchee sddm[530]: Loaded empty theme configuration
May 06 16:14:55 LAPArchee sddm[530]: Adding new display...
May 06 16:14:55 LAPArchee sddm[530]: Removing display SDDM::Display(0x562e9bd63cc0) ...
May 06 16:14:55 LAPArchee sddm[530]: Running display stop script  QList("/usr/share/sddm/scripts/Xstop")
May 06 16:14:55 LAPArchee sddm[530]: Display server stopped.
May 06 16:14:55 LAPArchee bluetoothd[2599]: Endpoint unregistered: sender=:1.277 path=/MediaEndpoint/A2DPSource/ldac
May 06 16:14:55 LAPArchee systemd-logind[491]: Session 5 logged out. Waiting for processes to exit.
May 06 16:14:55 LAPArchee sddm[530]: Display server stopping...
May 06 16:14:55 LAPArchee sddm[530]: Socket server stopped.
May 06 16:14:55 LAPArchee sddm[530]: Socket server stopping...
May 06 16:14:55 LAPArchee sddm[530]: Auth: sddm-helper exited with 6
May 06 16:14:55 LAPArchee sddm-helper[165370]: [PAM] Ended.
May 06 16:14:55 LAPArchee systemd[1]: Started Process Core Dump (PID 179001/UID 0).
May 06 16:14:55 LAPArchee sddm-helper[165370]: pam_unix(sddm:session): session closed for user bitwise
May 06 16:14:55 LAPArchee sddm-helper[165370]: [PAM] Closing session
May 06 16:14:55 LAPArchee polkitd[963]: Unregistered Authentication Agent for unix-session:5 (system bus name :1.282, object path /org/kde/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8>
May 06 16:14:55 LAPArchee sudo[174124]: pam_unix(sudo:session): session closed for user root
May 06 16:14:55 LAPArchee systemd[1]: systemd-coredump@4-178978-0.service: Deactivated successfully.
May 06 16:14:55 LAPArchee systemd-coredump[178979]: [🡕] Process 165374 (Hyprland) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 165374:
                                                    #0  0x00007cc736cac194 n/a (libc.so.6 + 0x90194)
                                                    #1  0x00007cc736c58d70 raise (libc.so.6 + 0x3cd70)
                                                    #2  0x00007cc736c404c0 abort (libc.so.6 + 0x244c0)
                                                    #3  0x0000580138ec5f90 _Z25handleUnrecoverableSignali (Hyprland + 0xd4f90)
                                                    #4  0x00007cc736c58e20 n/a (libc.so.6 + 0x3ce20)
                                                    #5  0x00007cc7306ccc20 n/a (iris_dri.so + 0x2ccc20)
                                                    #6  0x00007cc7306b8452 n/a (iris_dri.so + 0x2b8452)
                                                    #7  0x00007cc7304e8636 n/a (iris_dri.so + 0xe8636)
                                                    #8  0x00007cc73051008d n/a (iris_dri.so + 0x11008d)
                                                    #9  0x00007cc7304d244d n/a (iris_dri.so + 0xd244d)
                                                    #10 0x00007cc7304d522d n/a (iris_dri.so + 0xd522d)
                                                    #11 0x00007cc7304d531c n/a (iris_dri.so + 0xd531c)
                                                    #12 0x0000580139138aab n/a (Hyprland + 0x347aab)
                                                    #13 0x0000580139176008 n/a (Hyprland + 0x385008)
                                                    #14 0x00007cc7371ea596 n/a (libffi.so.8 + 0x7596)
                                                    #15 0x00007cc7371e700e n/a (libffi.so.8 + 0x400e)
                                                    #16 0x00007cc7371e9bd3 ffi_call (libffi.so.8 + 0x6bd3)
                                                    #17 0x00007cc737876ada n/a (libwayland-server.so.0 + 0x8ada)
                                                    #18 0x00007cc73787b180 n/a (libwayland-server.so.0 + 0xd180)
                                                    #19 0x00007cc737879ae2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xbae2)
                                                    #20 0x00007cc73787a2d7 wl_display_run (libwayland-server.so.0 + 0xc2d7)
                                                    #21 0x0000580139020307 _ZN17CEventLoopManager9enterLoopEP10wl_displayP13wl_event_loop (Hyprland + 0x22f307)
                                                    #22 0x0000580138ecdd3b _ZN11CCompositor15startCompositorEv (Hyprland + 0xdcd3b)
                                                    #23 0x0000580139015f4f main (Hyprland + 0x224f4f)
                                                    #24 0x00007cc736c41d4a n/a (libc.so.6 + 0x25d4a)
                                                    #25 0x00007cc736c41e0c __libc_start_main (libc.so.6 + 0x25e0c)
                                                    #26 0x0000580138e96fc5 _start (Hyprland + 0xa5fc5)
                                                    
                                                    Stack trace of thread 165398:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165386:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc736ed4ec1 __gthread_cond_wait (libstdc++.so.6 + 0xd4ec1)
                                                    #3  0x0000580138feee8e n/a (Hyprland + 0x1fde8e)
                                                    #4  0x00007cc736edcb63 execute_native_thread_routine (libstdc++.so.6 + 0xdcb63)
                                                    #5  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #6  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165396:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165391:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165392:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165390:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165394:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165393:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165389:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165395:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    
                                                    Stack trace of thread 165397:
                                                    #0  0x00007cc736ca68d9 n/a (libc.so.6 + 0x8a8d9)
                                                    #1  0x00007cc736ca9299 pthread_cond_wait (libc.so.6 + 0x8d299)
                                                    #2  0x00007cc7304863fc n/a (iris_dri.so + 0x863fc)
                                                    #3  0x00007cc73049ec2c n/a (iris_dri.so + 0x9ec2c)
                                                    #4  0x00007cc736caa1cf n/a (libc.so.6 + 0x8e1cf)
                                                    #5  0x00007cc736d2b6ec n/a (libc.so.6 + 0x10f6ec)
                                                    ELF object binary architecture: AMD x86-64
May 06 16:14:54 LAPArchee systemd[1]: Started Process Core Dump (PID 178978/UID 0).
May 06 16:14:54 LAPArchee kernel: nouveau 0000:01:00.0: Enabling HDA controller

**Comment by vaxerski** [comment]
> I've noticed that disabling SWWW has some effect on decreasing the probability of this happening significantly but I still think it happened at least once even when SWWW was killed after login.

> with Nouveau

> ```
> #3  0x0000580138ec5f90 _Z25handleUnrecoverableSignali (Hyprland + 0xd4f90)
> #4  0x00007cc736c58e20 n/a (libc.so.6 + 0x3ce20)
>  #5  0x00007cc7306ccc20 n/a (iris_dri.so + 0x2ccc20)
> ```

This is a gpu driver issue.

**Comment by shinobiultra** [comment]
> > I've noticed that disabling SWWW has some effect on decreasing the probability of this happening significantly but I still think it happened at least once even when SWWW was killed after login.
> 
> > with Nouveau
> 
> > ```
> > #3  0x0000580138ec5f90 _Z25handleUnrecoverableSignali (Hyprland + 0xd4f90)
> > #4  0x00007cc736c58e20 n/a (libc.so.6 + 0x3ce20)
> >  #5  0x00007cc7306ccc20 n/a (iris_dri.so + 0x2ccc20)
> > ```
> 
> This is a gpu driver issue.

Even then, would you be so kind as to suggest *any* ideas on how to go about solving this? I keep crashing like every 10min now so it's quite bad. I've got everything up to date and am really not sure as to what might be the cause. Like, could it be the combination of latest Hyprland & mesa? Kernel? Or something else? Could perhaps some Hyprland's config help mitigate or at least debug this issue? Some ultra logging perhaps or something lol. Or would some other logs help perhaps?

If I weren't at work (having Arch-based work laptop was quite edgy decision as it turns out, but worth it!) I'd even include anime titties to give ya some reason to help me :DD

**Comment by vaxerski** [comment]
if I knew how to fix this I would've given you tips. I have no idea on how to fix nvidia issues. Haven't touched those cards in years. Try looking up online, using the proprietary drivers, maybe ask around on the discord server or some forums

**Comment by ojoanalogo** [comment]
Same issue here, with a Zephyrus G16 and a Nvidia 4060, but as Vaxerski said this is not an Hyprland problem

@shinobiultra have you managed to find a solution? I've tried disabling nouveau and using the integrated graphics card (Intel) with no luck
