### ISSUE TITLE
Applications launched in the background when starting Hyprland always open in workspace 1 when invoked

### ISSUE THREAD

**Issue by Bruce0206** [hyprwm/Hyprland#5919]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit cddeec47a1fc0e70d8598fd10c29cd0e9489999f  (keybinds: make the keybind manager check for session lock (5894)).
Date: Sun May 5 11:28:14 2024
Tag: v0.40.0-11-gcddeec47, commits: 4617

flags: (if any)


System Information:
System name: Linux
Node name: komputer
Release: 6.8.9-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:48:53 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

My configuration sets Thunar (with the `--daemon` option) and a polkit agent to start on login using `exec-once`.  For the very first time they are invoked, they always seems to launch in workspace 1 no matter which workspace is actually focused.   The issue seems to persist no matter which polkit agent I use and which application invokes the polkit (e.g GParted).  Further launches do not have this issue.

### How to reproduce

1. Set an application to start in the background using `exec-once`
2. Logout and login
3. Switch to another workspace
4. Invoke that application

**Comment by vaxerski** [comment]
set misc:initial_workspace_tracking to false https://wiki.hyprland.org/Configuring/Variables/#misc
