### ISSUE TITLE
Multimonitor choppy mouse when not focused on a window

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [hyprwm/Hyprland#592]
Been using hyprland without any issues.

For some reason the mouse movements seem super choppy if no window is focused on any of my 3 monitors. If it's over a window it's smooth.

**Comment by vaxerski** [comment]
I think it's a dupe of #267 and #290 but holy shit you actually made me be able to reproduce this yooo

**Comment by vaxerski** [comment]
It's pretty subtle for me so I will ask: does it go away if `misc:no_vfr` is set to `true`?

**Comment by DimitrisMilonopoulos** [comment]
@vaxerski for some reason I can't see this option as valid tried appending either 

```
no_vfr=1
```
or 
```
misc{
no_vfr=1
}
```

But says that there is no such configuration choice

**Comment by vaxerski** [comment]
The wiki tells you how to use categories. You have a bunch in your config already.

```
misc {
    no_vfr = 1
}
```

**Comment by DimitrisMilonopoulos** [comment]
@vaxerski ok tried it and it didn't help, the behavior is very weird, like at first everything works great and after you open a window it starts chopping

**Comment by vaxerski** [comment]
> after you open a window

You said it happens when there are *no* windows, though?

**Comment by DimitrisMilonopoulos** [comment]
No window focused, not in general, sorry for my poor explanation 😅

**Comment by vaxerski** [comment]
try with 09495375b52de47ddd97a46be1159721d207c862

**Comment by DimitrisMilonopoulos** [comment]
@vaxerski beast! Works like a charm :D Thank you so much for your swift response
