### ISSUE TITLE
Fullscreen workspace selector doesn't work properly

### ISSUE THREAD

**Issue by diniamo** [hyprwm/Hyprland#5922]
### Hyprland Version

<details> <summary>System/Version info</summary>
The version command doesn't work due to nix shenanigans, but I'm on 57e76f91d9a388a41223e5ac0f13863d4b663bcd.
</details>

### Bug or Regression?

Bug

### Description

The fullscreen selector's functionality doesn't align with the documentation:
- `f[-1]` - selects non-fullscreen workspaces as it should
- `f[0]` - the documentation suggests that this should select both types of workspaces, but it doesn't select fake fullscreen
- `f[1]` - the documentation suggests that this should select real fullscreen, when in reality, this selects fake fullscreen
- `f[2]` - the documentation suggests that this should select fake fullscreen, whereas in reality, it doesn't do that

For all of the above, I'm not sure how to test real fullscreen, since none of the rules affect it due to all decorations being hidden.

### How to reproduce

1. Have rounded corners
2. Run `hyprctl keyword workspace 'f[0], rounding:false'` or `hyprctl keyword workspace 'f[2], rounding:false'`
3. Put a window into fake fullscreen mode with the `fullscreen, 1` dispatcher
4. Observe that the corners are still rounded

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/1566e989-5015-430b-9ebc-6f6fcf81e817)

![image](https://github.com/hyprwm/Hyprland/assets/43317083/1f2119af-29eb-4c01-8f18-124529fc4726)

I think you are confused what "fake fullscreen" means...?

![image](https://github.com/hyprwm/Hyprland/assets/43317083/35668230-5e11-4a55-8c44-8f3ec7896a89)

it follows the same numbers as here.

**Comment by diniamo** [comment]
Alright, that is my bad, didn't realize there were 3 states and what maximize meant, it's clear now thank you.
