### ISSUE TITLE
language onevent with error

### ISSUE THREAD

**Issue by coffebar** [hyprwm/Hyprland#5923]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: crab
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland is sending errors to the IPC sometimes:
> hyprland language onevent with error

in result, Waybar shows empty layout

Here is log from the Waybar:

> [2024-05-06 18:51:55.642] [debug] hyprland language onevent with English (US)
> [2024-05-06 18:51:55.648] [debug] hyprland language onevent with English (US)
> [2024-05-06 18:51:55.649] [debug] hyprland IPC received activelayout>>wlr_virtual_keyboard_v1,English (US)
> [2024-05-06 18:51:55.655] [debug] hyprland language onevent with English (US)
> [2024-05-06 18:51:55.661] [debug] hyprland language onevent with English (US)
> [2024-05-06 18:51:55.662] [debug] hyprland IPC received activelayout>>wlr_virtual_keyboard_v1,error
> [2024-05-06 18:51:55.667] [debug] hyprland language didn't find matching layout
> [2024-05-06 18:51:55.667] [debug] hyprland language onevent with error
> [2024-05-06 18:51:55.675] [debug] hyprland language didn't find matching layout
> [2024-05-06 18:51:55.675] [debug] hyprland language onevent with error

related with [issue](https://github.com/Alexays/Waybar/issues/3190) 

### How to reproduce

Didn't figure out how to reproduce, maybe it's required to go into suspend mode.
Will do my best if I can help with debugging, but don't know where to start with this.

**Comment by vaxerski** [comment]
that would be an xkb bug I'd say

**Comment by vaxerski** [comment]
it's a part of xorg but it works and as such we still use it in wayland. It handles your keyboard layouts. It's a hunk of code for "human" stuff which nobody wants to rewrite cuz it works and is horribly complicated...

Generally I ask xkb for the layout and return whatever it says: https://github.com/hyprwm/Hyprland/blob/ec092bd601d9d351ff6ca34bd97f12055b2a4dd9/src/devices/IKeyboard.cpp#L99-L116
