### ISSUE TITLE
Box drawn around dropdown menus in chromium

### ISSUE THREAD

**Issue by James-Randall-14** [hyprwm/Hyprland#5931]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0c446ec5f4c39599ea97cb703dd3ac7718fb9169  (memory: fix SP/WP hierarchy templates).
Date: Mon May 6 20:36:31 2024
Tag: v0.40.0-15-g0c446ec5, commits: 4621

flags: (if any)


System Information:
System name: Linux
Node name: randall-surface
Release: 6.8.8-arch1-1-surface
Version: #1 SMP PREEMPT_DYNAMIC Tue, 30 Apr 2024 07:52:55 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Plus Graphics 640 [8086:5926] (rev 06) (prog-if 00 [VGA controller])
00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Sunrise Point-LP Integrated Sensor Hub [8086:9d35] (rev 21)


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When interacting with dropdown menus in chromium, a blurred background is rendered around them. 
I've attached two screenshots from running chromium with a near-default Hyprland configuration (terminal is set to alacritty, and a bind is created for grimshot), as well as two screenshots from my current config. It seems like the color of the box has something to do with the wallpaper / blur settings (possibly the vibrancy?)

### How to reproduce

1. run `Hyprland`
2. run `chromium`
3. Click on the three dots in the top right, or right click the window to summon a dropdown menu

### Crash reports, logs, images, videos

![2024-05-07T19:19:46,358521899+00:00](https://github.com/hyprwm/Hyprland/assets/84990498/6644af0d-a49b-4401-94bf-5b46b0d73b7a)
![2024-05-07T19:20:08,237557378+00:00](https://github.com/hyprwm/Hyprland/assets/84990498/d4fe944e-d894-4487-8c43-a7700a8da2d2)
![2024-05-07T19:30:09,129420847+00:00](https://github.com/hyprwm/Hyprland/assets/84990498/dd2f22ab-b1c5-4e40-a509-efbd17315e42)
![2024-05-07T19:30:35,224789768+00:00](https://github.com/hyprwm/Hyprland/assets/84990498/38538fd5-e3e0-47a7-863e-5cd67963bf80)

**Comment by vaxerski** [comment]
run chromium in native wayland
