### ISSUE TITLE
VirtualBox guest has black screen on fullscreen.

### ISSUE THREAD

**Issue by joelmathewthomas** [hyprwm/Hyprland#5933]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ec092bd601d9d351ff6ca34bd97f12055b2a4dd9  (core: chase hyprwayland-scanner).
Date: Tue May 7 18:58:26 2024
Tag: v0.40.0-21-gec092bd6, commits: 4627

flags: (if any)


System Information:
System name: Linux
Node name: nitro5
Release: 6.8.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

https://github.com/hyprwm/Hyprland/assets/90510078/d6fc382a-b528-4b9b-81ab-3e7a3920362d

When using virtualbox in Hyprland, the guest when put in fullscreen , just shows a black screen.
This issue existed even on `commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759`.

### How to reproduce

Use a virtualbox guest in fullscreen in Hyprland

**Comment by vaxerski** [comment]
> This issue existed even on commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759.

uhh... is this a regression? I can't see how this can be a hl issue tbh

**Comment by joelmathewthomas** [comment]
> > This issue existed even on commit [fe7b748](https://github.com/hyprwm/Hyprland/commit/fe7b748eb668136dd0558b7c8279bfcd7ab4d759).
> 
> uhh... is this a regression? I can't see how this can be a hl issue

**Comment by joelmathewthomas** [comment]
> uhh... is this a regression?
No , i was implying that , it's not a bug that came due to the new version 0.4.

>  I can't see how this can be a hl issue tbh
I wasn't really sure if it was a Hyprland or a virtualbox problem.

**Comment by MightyPlaza** [comment]
> > uhh... is this a regression?
> 
> No , i was implying that , it's not a bug that came due to the new version v0.40.0.
> 
> > I can't see how this can be a hl issue tbh
> 
> I wasn't really sure if it was a Hyprland or a virtualbox problem.

try using hyprland's fullscreen dispatcher and passing 2 as an argument

**Comment by joelmathewthomas** [comment]
> try using hyprland's fullscreen dispatcher and passing 2 as an argument


https://github.com/hyprwm/Hyprland/assets/90510078/897d0895-62ef-4919-b8ef-b5da8fdb902a

It just makes the window fullscreen, doesn't change anything.


https://github.com/hyprwm/Hyprland/assets/90510078/7b500bdf-c96e-43c0-8bba-cb9f9ae06ca9

Scaled mode works fine although.

**Comment by MightyPlaza** [comment]
> It just makes the window fullscreen, doesn't change anything.
that was kinda the point, not telling the program it is fullscreen so it behaves properly

see if using it with fakefullscreen (and possibly resizing it) works

**Comment by joelmathewthomas** [comment]
> > It just makes the window fullscreen, doesn't change anything.
> > that was kinda the point, not telling the program it is fullscreen so it behaves properly
> 
> see if using it with fakefullscreen (and possibly resizing it) works

Tried it doesnt work

**Comment by vaxerski** [comment]
yeah I don't think this is a hl problem? what if you manually resize it to fullscreen sizes? what if you have a floating app above it?

**Comment by joelmathewthomas** [comment]
> what if you manually resize it to fullscreen sizes? what if you have a floating app or special workspace above it when fullscreen?

No change at all

**Comment by noobhacker1** [comment]
i have the same issue only on hyprland, didn't have it either on kde or gnome

```
Hyprland 0.44.0 built from branch main at commit 0baf166d39260c6d1d422cf528fb5fedc3010cdb  ([gha] Nix: update inputs).
Date: Wed Oct 16 12:01:31 2024
Tag: v0.44.0-46-g0baf166d, commits: 5345
built against aquamarine 0.4.3
```

**Comment by topaxi** [comment]
just ran into the same issue, virtualbox 7.1.4

```
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0
```

**Comment by topaxi** [comment]
I could fix it by disabling the fullscreen mini toolbar.

VirtualBox -> Machine -> Settings -> User Interface -> Mini ToolBar [ ] Show in Full-screen/Seamless

There's a VirtualBox issue filed for i3 which has the same issue: https://www.virtualbox.org/ticket/14323

**Comment by eliabexp** [comment]
> I could fix it by disabling the fullscreen mini toolbar.
> 
> VirtualBox -> Machine -> Settings -> User Interface -> Mini ToolBar [ ] Show in Full-screen/Seamless
> 
> There's a VirtualBox issue filed for i3 which has the same issue: https://www.virtualbox.org/ticket/14323

thank you so much for the hint
