### ISSUE TITLE
error setting value <50> for field <general:gaps_workspace> : no such field

### ISSUE THREAD

**Issue by lVentus** [hyprwm/Hyprland#5937]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
0.32.3
```
</details>

### Bug or Regression?

Bug

### Description

error setting value <50> for field <general:gaps_workspace> : no such field

### How to reproduce

set a value to gaps_workspace

**Comment by MightyPlaza** [comment]
your version is very old

**Comment by lVentus** [comment]
> your version is very old

I am using nixos stable pkgs and stable home-manager. Do I have to switch to unstable? or is there a way, to keep my HM stable version, but only install hyprland from unstable pkgs?
with old nix-channel, it seems possible. But I don't know how to do this with home-manager.

**Comment by MightyPlaza** [comment]
no idea what that means
@fufexan

**Comment by vaxerski** [comment]
nixos stable is extremely outdated
