### ISSUE TITLE
crash when hovering over tooltips in certain firefox extensions

### ISSUE THREAD

**Issue by pinkcreeper100** [hyprwm/Hyprland#594]
[hyprland.log.txt](https://github.com/hyprwm/Hyprland/files/9443068/hyprland.log.txt)
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by pinkcreeper100** [comment]
should I also dump core?

**Comment by vaxerski** [comment]
yes

**Comment by pinkcreeper100** [comment]
https://gist.github.com/pinkcreeper100/05eb17f0c039d162b2cf209515f94038

**Comment by vaxerski** [comment]
thats the log, not the coredump

**Comment by pinkcreeper100** [comment]
oop

**Comment by pinkcreeper100** [comment]
https://easyupload.io/5wvrs3

**Comment by vaxerski** [comment]
how is that 300MB???

Please follow the instructions in the guidelines you've even linked yourself.

**Comment by pinkcreeper100** [comment]
[hlcd.txt](https://github.com/hyprwm/Hyprland/files/9445439/hlcd.txt)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/187228044-c6a7f7f7-70ec-4501-8f7a-31ab83de7f63.png)
dunno works for me. Any step-by-step instructions? (may I remind you I will not sign up / pay just to test something)

**Comment by pinkcreeper100** [comment]
1. edit an already created item or create a new item
2. hover over the different buttons in the password section repeatedly until it crashes

**Comment by TheSunCat** [comment]
How often does this occur? I can't seem to repro on my machine hovering over the `Check if password has been exposed` and `Generate Password` buttons repeatedly. I do notice the window flickering sometimes, which is odd.

**Comment by pinkcreeper100** [comment]
on my end, the window has to flicker at least around 5 times for a crash to occur

**Comment by pinkcreeper100** [comment]
Also occurs with uBlock origin

**Comment by IanManske** [comment]
I am able to reproduce the same crash with uBlock origin and other extensions. This is with `MOZ_ENABLE_WAYLAND=1`.
From the extension's menu (like in the image above), simply hovering over buttons that have title/tooltip text enough times will trigger it (typically 3-10 hovers in my case). For me, flickering does occur but seems to not be necessary to trigger the crash (probably just a symptom).

**Comment by vaxerski** [comment]
check with e518adf1ac3db14e85fd3b8ceab71c22eab9d1c7

**Comment by vaxerski** [comment]
dump gib

**Comment by IanManske** [comment]
in class lol one sec

**Comment by IanManske** [comment]
That was more than one sec, sorry for the wait.
Not sure if I did it correctly (there's some `n\a`'s in the dump).
[dump.txt](https://github.com/hyprwm/Hyprland/files/9559765/dump.txt)

**Comment by vaxerski** [comment]
I am pretty sure this is the wrong dump.

**Comment by vaxerski** [comment]
but fixed that crash in da10022d846334fe4265ec03b44a75c41921f603

**Comment by IanManske** [comment]
Uhhh correct me if I'm doing something dumb.
1. clone the repo and cd
2. `sudo make clear`
3. `sudo make config`
4. `make debug`
5. open separate tty
6. `cd $repo/build`
7. run `Hyprland -c ../example/hyprland.conf`
8. reproduce the crash
9. `coredumpctl` and get pid of last Hyprland
10. get dump of pid

Again in case:
[dump.txt](https://github.com/hyprwm/Hyprland/files/9560125/dump.txt)

**Comment by vaxerski** [comment]
> `run Hyprland -c ../example/hyprland.conf`

man didnt learn bash in school
`./Hyprland`, not `Hyprland`

**Comment by IanManske** [comment]
:insert clown meme:
I just forgor. It's always the smallest things...
Here's the dump (hopefully):
[dump.txt](https://github.com/hyprwm/Hyprland/files/9560195/dump.txt)

**Comment by vaxerski** [comment]
```
#0  0x00000000004f2238 n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xf2238)
                #1  0x00000000004f318e n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xf318e)
                #2  0x00000000004c56fb n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xc56fb)
                #3  0x00000000004c527f n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xc527f)
                #4  0x00000000004c4dff n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xc4dff)
                #5  0x00000000004f788d n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xf788d)
                #6  0x00000000004f758d n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xf758d)
                #7  0x00000000004f70c3 n/a (/home/iama/Code/Hyprland/build/Hyprland + 0xf70c3)
                ```
                
                amazing dump. When doing a coredump of a debug build, make sure to do `coredumpctl debug <pid>` instead, *not pipe the output*, get to the gdb console (if it asks questions, enable debuginfod and continue without paging) and do `bt -full`

**Comment by IanManske** [comment]
Ikr! But [the docs](https://wiki.hyprland.org/Contributing-and-Debugging/) should probably be updated?
Third time's the charm...
[dump.txt](https://github.com/hyprwm/Hyprland/files/9560258/dump.txt)

**Comment by vaxerski** [comment]
can you `print *PNODE`?

**Comment by IanManske** [comment]
Had to familiarize myself with `gdb`...
[print.txt](https://github.com/hyprwm/Hyprland/files/9560305/print.txt)

**Comment by vaxerski** [comment]
really odd as this does not happen AT ALL to me, and the crash is really weird too. Can you also try running Hyprland with ASan? Sorry if I am asking for so much, I'd do it myself if not for the fact it never crashes for me.

CMakeLists.txt:
line 83 (insert before the line)
`asan`

line 94 (add to args)
`-fsanitize=address`

pipe the outputs of hyprland (both stdout and stderr) to a file and give me that.

**Comment by IanManske** [comment]
Yeah np, let me join the discord real quick.

**Comment by vaxerski** [comment]
since this was mentioned again, can someone produce the ASan output?

**Comment by vaxerski** [comment]
please check bf1718aec9fbb6751c27cb7b247520eab79123c0

**Comment by vaxerski** [comment]
should be fixed with 881f8282501845f57505015e85abbe668bfb740f

**Comment by pinkcreeper100** [comment]
I shall update and check

**Comment by pinkcreeper100** [comment]
still flickers, but doesn't crash!

**Comment by vaxerski** [comment]
flicker is firefox's fault
