### ISSUE TITLE
Keybinds not changing according to the keyboard layout 

### ISSUE THREAD

**Issue by Phantomwise** [hyprwm/Hyprland#5953]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```
</details>

### Bug or Regression?

Bug

### Description

The keybinds don't change according to the keyboard layout when using several layouts. They always use the keys of the first layout.

I have set up three keyboard layouts :
COLEMAK, for typing 
AZERTY. for typing french accents
QWERTY, for games that don't allow in-game remaping of WASD

```
input {
    # Keyboard layouts Qwerty/Colemak/Azerty, switching with Alt + Shift
    kb_layout = us,us,fr
    kb_options = grp:alt_shift_toggle
    kb_variant = ,colemak,
    kb_model =
    kb_rules =

    follow_mouse = 1

    # Touchpad
    touchpad {
        natural_scroll = no
    }
```

The layouts are all working correctly, and layout switching too (unless I use caps:swapescape, but that's a separate problem).

However the keybinds don't change according to the layout.

```
bind = $mainMod, F, fullscreen 
bind = CTRL ALT, F, exec, $filemanager
bind = $mainMod SHIFT, Q, killactive, 
```

QWERTY : key 41=F
QWERTY : key 26=E
COLEMAK: key 41=T
COLEMAK: key 26=F

Expected behavior :
- In QWERTY, MOD+F(key 41) enables/disables fullscreen
- In QWERTY, CTRL+ALT+F(key 41) launches file manager
- In COLEMAK, MOD+F(key 26) enables/disables fullscreen
- In COLEMAK, CTRL+ALT+F(key 26) launches file manager

Actual behavior :
- In QWERTY, MOD+F(key 41) enables/disables fullscreen (OK)
- In QWERTY, CTRL+ALT+F(key 41) launches file manager (OK)
- In COLEMAK, MOD+T(key 41) enables/disables fullscreen (weird)
- In COLEMAK, CTRL+ALT+T(key 41) launches file manager (weird)

QWERTY : key 24=Q
QWERTY : key 38=A
AZERTY: key 24=A
AZERTY: key 38=Q

Expected behavior :
- In QWERTY, MOD+SHIFT+Q(key 26) closes the active window
- In AZERTY, MOD+SHIFT+Q(key 38) closes the active window

Actual behavior :
- In QWERTY, MOD+SHIFT+Q(key 26) closes the active window (OK)
- In AZERTY, MOD+SHIFT+A(key 26) closes the active window (weird)

I tried changing the order of the layouts and the keybinds always use the keys of the first layout.

I don't know if it's a bug or intended behavior, but it feels more like a bug : if you don't want your keybinds to change with a different layout and they do change by default then you can directly use the keycode, but if you do want them to change and they don't by default then you are kind of screwed...

I don't know if the logs were uploaded correctly, either they're uploaded a dozen time or not at all, I can't tell... I tried pasting the logs in case the upload didn't work but it said "body is too long"... It's my first time using github so I apologize if I missed something obvious ^_^"

### How to reproduce

**hyprland.conf**

```
input {
    # Keyboard layouts Qwerty/Colemak/Azerty, switching with Alt + Shift
    kb_layout = us,us,fr
    kb_options = grp:alt_shift_toggle
    kb_variant = ,colemak,
    kb_model =
    kb_rules =

    # kb_options = caps:swapescape
    # PB: Prevents switching keyboard layout

    follow_mouse = 1

    # Touchpad
    touchpad {
        natural_scroll = no
    }
```

```
bind = $mainMod, F, fullscreen 
bind = CTRL ALT, F, exec, $filemanager
bind = $mainMod SHIFT, Q, killactive, 
$filemanager = nemo
```

Then try MOD+F, CTRL+ALT+F and MOD+SHIFT+Q under the different layouts.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts

![image](https://github.com/hyprwm/Hyprland/assets/43317083/dda5b925-c896-44e8-9679-4de9d5b461d9)

You can also https://wiki.hyprland.org/Configuring/Binds/#uncommon-syms--binding-with-a-keycode

![image](https://github.com/hyprwm/Hyprland/assets/43317083/6b7e13c7-9305-408c-8287-0f35089d0928)

**Comment by Phantomwise** [comment]
Okay I don't know how I missed that -__-
Thanks for taking the time to point it out !
