### ISSUE TITLE
Hyprland thinks I have an additional monitor and then crashes when a window "opens" in it.

### ISSUE THREAD

**Issue by dmadisetti** [hyprwm/Hyprland#5958]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  ().
Date: 2024-05-04
Tag: , commits: @COMMITS@

flags: (if any)


System Information:
System name: Linux
Node name: lambda
Release: 6.6.30
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 Ti] [10de:2182] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240505.25865a4"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

A regression is something that once worked but now doesn't yes?

Since 0.40.0 changing to workspace would sometimes make my cursor disappear, and hyprland in general acted as if there was another monitor (there's not). Hyprland would suddenly freeze and I would have to ssh into my system and kill the process.

This last time, I left the process running for a few hours, came home and found that Hyprland was using 40Gb of memory and 200% CPU.

I promised I looked for similar issues and did not find any.

### How to reproduce

Realized that hyprland would crash when I created a window in this virtual monitor

super-2 (change window 2, cursor disappears)
super-enter (kind binding to launch kitty)

fireworks :tada:

I explicitly tie to a given HDMI:
```
monitor=HDMI-A-2,1920x1080@60,0x0,1.0                                                                                                                                                                                           
workspace=HDMI-A-2,1  
```

But removed this once I started having issues a few days ago (and the behavior persisted)

I only have 1 physical monitor- this is new behavior. Might be graphics reporting something incorrectly, but not seeing any issue with xmonad (so far)

### Crash reports, logs, images, videos

I might have truncated some of the 10429939 lines of this last log. Crash happens around line 649

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15256750/hyprland.log)

**Comment by dmadisetti** [comment]
Trying to build from git, but I think the new `xwayland` overlay is causing a ton of cache misses: https://github.com/hyprwm/Hyprland/commit/f15513309b24790099d42974274eb23f66f7c985

[I noticed this before ](https://www.reddit.com/r/NixOS/comments/1clu0do/theres_a_reason_i_dont_use_gentoo/) but wasn't sure it was Hyprland until now. Hopefully, this will improve when CI runs?
If this persists, you might think about adding additional common build targets like qtbase to your cache CI

will update in a few hours I guess

**Comment by dmadisetti** [comment]
Yes, this is broken on head too. But head makes my log files empty?

![2024-05-08-233233_1920x1080_scrot](https://github.com/hyprwm/Hyprland/assets/2689338/9a53e147-4333-4dc9-9f87-9ad66c384ec7)

Newest "logs" are under _17*

---

Will stop the spam unless prompted, and can break these out into multiple issues if desired

**Comment by ikalco** [comment]
based on the original log this seems like a driver issue

also this might or might not do something useful
```
ls -1 /sys/class/drm/*/edid
```

**Comment by dmadisetti** [comment]
+1 the phantom screen is a reported thing:

```
/sys/class/drm/card0-Unknown-1/edid
/sys/class/drm/card1-DP-1/edid
/sys/class/drm/card1-DVI-D-1/edid
/sys/class/drm/card1-HDMI-A-1/edid
/sys/class/drm/card1-HDMI-A-2/edid
```

Also looks like this a common/ recent issue with kernel update. I can't reboot rn, but planning on playing with DRM kernel settings as per the internet.

Unresponsive failure probably still isn't good, though

**Comment by vaxerski** [comment]
yeah this is a driver issue. Often happens on nvidia fwiw. Just disable the ghost monitor in the config
