### ISSUE TITLE
Empty lines are causing issues

### ISSUE THREAD

**Issue by dieBakterie** [hyprwm/Hyprland#5962]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:48:53 +0000


GPU information: 
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2070 Rev. A] [10de:1f07] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

When sourcing from `hyprland.conf` all leading empty lines are an `invalid config line` as shown in the images. You just need to avoid leading empty lines or comment them out to fix this error.

### How to reproduce

Have an leading empty line in the first file you're sourcing.

### Crash reports, logs, images, videos

![240509_16h26m34s_screenshot](https://github.com/hyprwm/Hyprland/assets/50206827/c020e725-1dff-4bfd-8db4-9fbb67fdce12)
![240509_16h27m13s_screenshot](https://github.com/hyprwm/Hyprland/assets/50206827/6cd808a2-0a20-4c37-aa1e-ef5d9af72c57)
![240509_16h43m22s_screenshot](https://github.com/hyprwm/Hyprland/assets/50206827/5511394d-8125-4c33-872c-e872902d2917)
![240509_16h44m01s_screenshot](https://github.com/hyprwm/Hyprland/assets/50206827/2478fbea-1e01-4a68-8d0e-12333aa8f43e)

**Comment by vaxerski** [comment]
are you sure they are empty?

**Comment by dieBakterie** [comment]
As in the Images it's just an leading empty line unless you count whitespace as something.

**Comment by vaxerski** [comment]
if there are unprintable characters that could throw it off.

Also check the encoding - hyprlang supports only UTF-8, and some use something like UTF-8 with BOM or something which will throw errors.

**Comment by dieBakterie** [comment]
Ok, but these are just empty lines with nothing in it.
