### ISSUE TITLE
`no_gaps_when_only` border not hidden when only one again

### ISSUE THREAD

**Issue by jlo62** [hyprwm/Hyprland#5965]
### Hyprland Version

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

System Information:
System name: Linux
Node name: ArchLinux
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
33:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

The border is correctly hidden when using no_gaps_when_only with the master layout, But it gets showed when a window is opened and closed again:

https://github.com/hyprwm/Hyprland/assets/122014753/7f529e3d-748c-4b45-b29a-59b534564305

It repairs itself when I change workspace.

### How to reproduce

```
master {
    no_gaps_when_only = true
}
```

**Comment by gksudolol** [comment]
> Date: Tue Apr 16 16:01:03 2024
> Tag: v0.39.1, commits: 4460

Pretty sure this was fixed a while ago? in any case you should update as can't reproduce on 0.40.0/master
