### ISSUE TITLE
Groupbar font doesn't scale

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#5968]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: prometheus
Release: 6.8.9
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:35:35 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 02) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240507.b211b39"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Groupbar titles in latest verisons don't seem to scale, which is issue on multiple mons setups or  reproducible configs.

There is a not so old merged PR https://github.com/hyprwm/Hyprland/pull/4640, but apparently it fckd again or something.

### How to reproduce

check tab on hidpi display with default conf, dunno

### Crash reports, logs, images, videos

Same config.
1x:
![1x](https://github.com/hyprwm/Hyprland/assets/142721811/c137ff03-b27f-4655-b631-a90bd2ceb3ec)

2x:
![2x](https://github.com/hyprwm/Hyprland/assets/142721811/39b5cb73-d131-4267-8613-81d9cf9730c5)

**Comment by MightyPlaza** [comment]
where is the proper version info?

**Comment by Ligthiago** [comment]
No clue, some nix thing, i'm on 85f7f69046c07c61f59b0ef7cccd01e88b316413

**Comment by MightyPlaza** [comment]
lol, looks like vaxry removed a bit of the PR accidentally when moving to hyprlang and the rest later since it was an unused variable.
