### ISSUE TITLE
low-res client-side cursor

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#5970]
### Hyprland Version

36d2a09bbada583fe01d824bb8cb42284194495b

### Bug or Regression?

Regression

### Description

After https://github.com/hyprwm/Hyprland/pull/5902 client-side cursors (gtk apps) are now rendered in low-resolution, server-side cursors work fine.

### How to reproduce

- Open gtk app
- Hover cursor over it

**Comment by andresilva** [comment]
I don't have any hyprcursor theme. I have `XCURSOR_THEME` and `XCURSOR_SIZE` set, as well as the gtk cursor theme settings.

**Comment by vaxerski** [comment]
scaling?

**Comment by andresilva** [comment]
Yeah doesn't happen at 1x scaling.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15267677/patch.txt)
try

**Comment by andresilva** [comment]
Fixes it

**Comment by vaxerski** [comment]
hm?
