### ISSUE TITLE
Waybar and ags's popup not working

### ISSUE THREAD

**Issue by sungyoonc** [hyprwm/Hyprland#5977]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1753059b07be52cf78fa2676c4c71d2edb560199  (pointermgr: reset entered outputs when resetting surface).
Date: Fri May 10 07:08:40 2024
Tag: v0.40.0-46-g1753059b, commits: 4652

flags: (if any)
```

</details>

### Bug or Regression?

Regression

### Description

On commit ed411f53bdcf8d455f9e6ca769693aa84dc8372f or 84e8d1810d57b65a0bc3b5ac2998bc023df880f4 the waybar's popup(tooltip, systemtray menu) don't show up on the second monitor.
Here the popup was displayed at the wrong position and I could see the tooltip popup's 1 pixel strip on the side of my second monitor

On commit 635a02d83fe9d598cf5f6aba47e672647608fb76 popups are not showing up on any monitor. Even the 1 pixel strip was gone.

### How to reproduce

On waybar or ags, open the systemtray menu (normally by right clicking it). The menu doesn't show up.
Also hover over a widget that has tooltip and the tooltip doesn't get displayed.

**Comment by sungyoonc** [comment]
> On commit ed411f5 or 84e8d18 the waybar's popup(tooltip, systemtray menu) don't show up on the second monitor.
> Here the popup was displayed at the wrong position and I could see the tooltip popup's 1 pixel strip on the side of my second monitor

The layer's popup(tooltip) is still being rendered outside the screen of the second monitor and only shows a 1 pixel strip (systray menu does not show up at all).

![layer_popup](https://github.com/hyprwm/Hyprland/assets/65142096/ad6a6625-56ef-4745-92d6-505486f3830a)

**Comment by vaxerski** [comment]
sounds like an app bug

**Comment by sungyoonc** [comment]
Oki I'll do some further investigating, and update when I find something

**Comment by sungyoonc** [comment]
I've traced down the problem to `g_pCompositor->getMonitorFromVector()`. It returns the wrong monitor position when called by `CPopup::unconstrain()`

**Comment by Gwenodai** [comment]
This bug seemed to affect much more than just ags or waybar popups. It causes context menus on anything that I fullscreened on my second monitor to seemingly not exist at all. But I can confirm https://github.com/hyprwm/Hyprland/pull/6010 completely fixed the issue and I can once again see context menus from applications on my second monitor when said application is fullscreened.
