### ISSUE TITLE
Hyprland crashes when wofi is closed

### ISSUE THREAD

**Issue by Disr0** [hyprwm/Hyprland#5980]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 337422911895bb55099e00208bff929651dcb5d2  (core: remove unused includes and fix warn).
Date: Fri May 10 09:20:26 2024
Tag: v0.40.0-50-g33742291, commits: 4656

flags: (if any)


System Information:
System name: Linux
Node name: meilon
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When launching wofi, and choosing an app(or closing wofi using escape) hyprland crashes.
Seems to happen because of `[LOG] Forcing an unmap of a LS that did a straight destroy!`, but I am not sure as I am not confident in the workings of Hyprland.

### How to reproduce

1. Launch Hyprland
2. Open wofi
3. Launch an app (or close wofi using escape)

### Crash reports, logs, images, videos

Log from the output of a command `cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 2 | tail -n 1)/hyprland.log >> log.txt`
[log.txt](https://github.com/hyprwm/Hyprland/files/15271347/log.txt)
Crash report from ~/.cache/hyprland
[hyprlandCrashReport326.txt](https://github.com/hyprwm/Hyprland/files/15271366/hyprlandCrashReport326.txt)

**Comment by ikkihou** [comment]
I also encounter the same bug. And I also noticed that if I kill waybar with command 'pkill waybar || waybar', hyprland crahes too...


### Crash reports, logs, images, videos
[hyprlandCrashReport184.txt](https://github.com/hyprwm/Hyprland/files/15271491/hyprlandCrashReport184.txt)

**Comment by Disr0** [comment]
The same things happens with `runner`

**Comment by Insprill** [comment]
Also reproducible with `grimblast.`

[hyprlandCrashReport26486.txt](https://github.com/hyprwm/Hyprland/files/15271627/hyprlandCrashReport26486.txt)

**Comment by formadi** [comment]
> Same thing with the wayland fork of rofi Running the same program directly in a terminal runs it with no issue

me too.

**Comment by vaxerski** [comment]
why not just ask hyprland nicely not to crash

**Comment by Disr0** [comment]
tried, but the nasty little thing still crashed

**Comment by Disr0** [comment]
Thank you our god and saviour vaxry for solving this :D

**Comment by sentakuhm** [comment]
deleting cache/paru/clone/rofi-lbonn-wayland-git and reinstall again solved my issue.

**Comment by izmyname** [comment]
Same with fuzzel, popping up mako notifications (50/50) and any app I have windowrules for.  Had to switch from git version to the latest stable from Arch repos.

**Comment by izmyname** [comment]
> > Same with fuzzel, popping up mako notifications (50/50) and any app I have windowrules for. Had to switch from git version to the latest stable from Arch repos.
> 
> the issue has been fixed

How long ago? I tried 30 minutes ago and it was a disaster.

**Comment by MightyPlaza** [comment]
> > > Same with fuzzel, popping up mako notifications (50/50) and any app I have windowrules for. Had to switch from git version to the latest stable from Arch repos.
> > 
> > 
> > the issue has been fixed
> 
> How long ago? I tried 30 minutes ago and it was a disaster.

https://github.com/hyprwm/Hyprland/commit/2549f0cc9725919d2d3ef466eff60bd10e1a321e
