### ISSUE TITLE
Cursor shrinks when hovering over certian applications

### ISSUE THREAD

**Issue by Insprill** [hyprwm/Hyprland#5982]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 337422911895bb55099e00208bff929651dcb5d2  (core: remove unused includes and fix warn).
Date: Thu May 9 22:20:26 2024
Tag: v0.40.0-50-g33742291, commits: 4656

flags: (if any)


System Information:
System name: Linux
Node name: iusearchbtw
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2024.01.25"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

When hovering over QT applications, the cursor shrinks to about half the normal size. This also happens when first opening Hyprland. Hovering over a non-QT application fixes the cursor size until it's hovered over a QT application again.

### How to reproduce

- Hyprland 337422911895bb55099e00208bff929651dcb5d2
- Open a GTK and a QT application
- Move the cursor between them 

### Additional info

~~I'm theming QT with `qt6ct` and `kvantum` using the Catppuccin theme. My GTK theme is also Catppuccin. I haven't had the chance to test without a theme to see if it's related.~~

**Comment by andresilva** [comment]
Do you have `HYPRCURSOR_SIZE` set?

**Comment by Insprill** [comment]
This appears to have gotten fixed - closing.
