### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Spiderfffun** [hyprwm/Hyprland#5984]
### Hyprland Version

<details> <summary>System/Version info</summary>
I was unable to launch `hyprctl systeminfo` as hyprland can't run, but the version is in the crash report.
</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes on startup. I don't know what exactly causes this, or if it is even hyprland related at all (could be wlroots, could even be something to do with my gpu as it doesnt work for some time upon install, then works, then doesn't again, which has happened with both endavour os and bedrock via debian base.), but since I couldn't get anybody to identify the cause in the discord, I decided to just make an issue here.

### How to reproduce

Not sure. Upon install, it didn't work, then it worked for a short while, then it didn't work again.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15267572/hyprland.log)
[hyprlandCrashReport113899.txt](https://github.com/hyprwm/Hyprland/files/15267568/hyprlandCrashReport113899.txt)

**Comment by vaxerski** [comment]
something is effed up with your permissions on the system. read the last lines of the log.

Issue on your end, likely seatd or polkit or something is broken
