### ISSUE TITLE
Hyprpm doesn't work on 0.40.0

### ISSUE THREAD

**Issue by cngr** [hyprwm/Hyprland#5986]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

plugins doesn't start,in previous hyprland version hprpm work fine

### How to reproduce

when i make hyprpm update dosen't work

### Crash reports, logs, images, videos

![2024-05-10-121417_hyprshot](https://github.com/hyprwm/Hyprland/assets/10997809/34947e90-0490-4838-bc5c-3baa20c8c2ca)

**Comment by vaxerski** [comment]
I don't speak spanish

**Comment by vaxerski** [comment]
if the only thing you can do is post a screenshot with an error in spanish and refuse to elaborate, and instead :-1: my comment, I consider this invalid.

Git is erroring out, likely a problem with your network.
