### ISSUE TITLE
Crash after turning monitor on.

### ISSUE THREAD

**Issue by LienNoir** [hyprwm/Hyprland#5987]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.8.8-300.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:53:31 UTC 2024


GPU information: 
0000:03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Turning back one of my monitor resulted in a crash (back to the logging screen)

### How to reproduce

Shut down the monitor for several hours, after turning it on again tryed to open firefox and the DE crashed ( back to logging screen)

### Crash reports, logs, images, videos

[hyprlandCrashReport1835.txt](https://github.com/hyprwm/Hyprland/files/15274347/hyprlandCrashReport1835.txt)

**Comment by vaxerski** [comment]
crash report bork can you https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace (without the make debug part)

**Comment by LienNoir** [comment]
Wasn't able to copy the output from the tty session, hope it helps. bt -full > debugFile.txt was't working. 

[output_bt-full.txt](https://github.com/hyprwm/Hyprland/files/15282544/output_bt-full.txt)

``
#0  0xee0bf760 in tor<llvm::DWARFYAML::StringOffsetsTable> > > >(void) () at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:890
No locals.
#1  0xee0c12d3 in ong long, std::allocator<unsigned long long> >, const llvm::FunctionSummary *, llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int, void> > > > > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:1092
No locals.
#2  0xee0c325d in tor<llvm::DWARFYAML::AbbrevTable, std::allocator<llvm::DWARFYAML::AbbrevTable> > >, __gnu_cxx::__normal_iterator<llvm::DWARFYAML::AbbrevTable *, std::vector<llvm::DWARFYAML::AbbrevTable, std::allocator<llvm::DWARFYAML::AbbrevTable> > > >(void) () at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:1776
No locals.
#3  0xee0bf085 in ctor<llvm::DWARFYAML::StringOffsetsTable, std::allocator<llvm::DWARFYAML::StringOffsetsTable> > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:759
No locals.
#4  0xee0be7ee in ctor<llvm::DWARFYAML::StringOffsetsTable, std::allocator<llvm::DWARFYAML::StringOffsetsTable> > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:721
No locals.
#5  0xee0be7ee in ctor<llvm::DWARFYAML::StringOffsetsTable, std::allocator<llvm::DWARFYAML::StringOffsetsTable> > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:721
No locals.
#6  0xee0c5279 in ong long, std::allocator<unsigned long long> >, const llvm::FunctionSummary *, llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int, void> > > > > > > ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:261
No locals.
#7  > > >, __gnu_cxx::__normal_iterator<llvm::DWARFYAML::AbbrevTable *, std::vector<llvm::DWARFYAML::AbbrevTable, std::allocator<llvm::DWARFYAML::AbbrevTable> > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:1639
No locals.
#8  0xee0c54cb in non-virtual thunk to (anonymous namespace)::MPPassManager::addLowerLevelRequiredPass(llvm::Pass*, llvm::Pass*) () from /lib/libLLVM.so.18.1
No locals.
#9  0xee0c1260 in ong long, std::allocator<unsigned long long> >, const llvm::FunctionSummary *, llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int, void> > > > > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:1086
No locals.
#10 0xee0c3001 in tor<llvm::DWARFYAML::AbbrevTable, std::allocator<llvm::DWARFYAML::AbbrevTable> > >, __gnu_cxx::__normal_iterator<llvm::DWARFYAML::AbbrevTable *, std::vector<llvm::DWARFYAML::AbbrevTable, std::allocator<llvm::DWARFYAML::AbbrevTable> > > >(void) () at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:1745
No locals.
#11 0xee0bf085 in ctor<llvm::DWARFYAML::StringOffsetsTable, std::allocator<llvm::DWARFYAML::StringOffsetsTable> > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:759
No locals.
#12 0xee0c2cad in ong long, std::allocator<unsigned long long> >, const llvm::FunctionSummary *, llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int, void> > > > > > > ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:481
No locals.
#13 ong long, std::allocator<unsigned long long> >, const llvm::FunctionSummary *, llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int, void> > > > > > >(void) ()
    at /usr/src/debug/llvm-18.1.1-1.fc40.i386/lib/IR/LegacyPassManager.cpp:1679
No locals.
#14 0xf5438fc0 in ac_create_passmgr (target_library_info=0x8385010, check_ir=false) at ../src/amd/llvm/ac_llvm_helper.cpp:292
        passmgr = 0x8344960
#15 0xf543a7db in ac_init_llvm_compiler (compiler=0x833ee00, family=CHIP_NAVI22, tm_options=0) at ../src/amd/llvm/ac_llvm_util.c:183
        triple = 0xf62e22cc "amdgcn--"
#16 0xf53232cf in si_create_llvm_compiler (sscreen=0x8241b90) at ../src/gallium/drivers/radeonsi/si_pipe.c:152
--Type <RET> for more, q to quit, c to continue without paging--c
        compiler = 0x833ee00
        create_low_opt_compiler = <optimized out>
        tm_options = <optimized out>
#17 0xf536c883 in si_shader_select_with_key<false, si_shader_key_ge> (sctx=<optimized out>, state=<optimized out>, key=<optimized out>)
    at ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:2889
        current = <optimized out>
        variant_count = <optimized out>
        cnt = 0
        is_pure_monolithic = <optimized out>
        sel = <optimized out>
        previous_stage_sel = <optimized out>
        shader = 0x821da70
        key_size = 42
        key_opt_size = 12
        sscreen = <optimized out>
        local_key = {part = {vs = {prolog = {instance_divisor_is_one = 0, instance_divisor_is_fetched = 0, ls_vgpr_fix = 0}}, tcs = {ls_prolog = {instance_divisor_is_one = 0, 
                instance_divisor_is_fetched = 0, ls_vgpr_fix = 0}, ls = 0x0, epilog = {prim_mode = 0, invoc0_tess_factors_are_def = 0, tes_reads_tess_factors = 0}}, gs = {vs_prolog = {
                instance_divisor_is_one = 0, instance_divisor_is_fetched = 0, ls_vgpr_fix = 0}, es = 0x0}}, as_es = 0, as_ls = 0, as_ngg = 0, mono = {vs_fetch_opencode = 0, vs_fix_fetch = {{
                u = {log_size = 0 '\000', num_channels_m1 = 0 '\000', format = 0 '\000', reverse = 0 '\000'}, bits = 0 '\000'} <repeats 16 times>}, u = {vs_export_prim_id = 0, 
              gs_tri_strip_adj_fix = 0}}, opt = {kill_outputs = 0, kill_clip_distances = 0, kill_pointsize = 0, kill_layer = 0, remove_streamout = 0, ngg_culling = 0, prefer_mono = 0, 
            same_patch_vertices = 0, inline_uniforms = 0, inlined_uniform_values = {0, 0, 0, 0}}}
        again = <optimized out>
        zeroed_key = 0xf719c0e0 <zeroed>
        key_size_no_uniforms = 42
        max_inline_uniforms_variants = 5
        current_not_ready = <optimized out>
        again = <optimized out>
        sscreen = <optimized out>
        sel = <optimized out>
        previous_stage_sel = <optimized out>
        current = <optimized out>
        shader = <optimized out>
        zeroed_key = <optimized out>
        key_size_no_uniforms = <optimized out>
        key_size = <optimized out>
        key_opt_size = <optimized out>
        local_key = <optimized out>
        variant_count = <optimized out>
        max_inline_uniforms_variants = <optimized out>
        cnt = <optimized out>
        is_pure_monolithic = <optimized out>
        i = <optimized out>
        iter_key = <optimized out>
        iter = <optimized out>
        ok = <optimized out>
        shader1_key = <optimized out>
#18 si_shader_select (ctx=<optimized out>, state=<optimized out>) at ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:3041
        sctx = <optimized out>
#19 0xf59e52af in si_update_shaders<(amd_gfx_level)13, (si_has_tess)0, (si_has_gs)0, (si_has_ngg)1> (sctx=sctx@entry=0x83697d0) at ../src/gallium/drivers/radeonsi/si_state_draw.cpp:129
        ctx = 0x83697d0
        old_vs = <optimized out>
        old_pa_cl_vs_out_cntl = <optimized out>
        old_uses_vs_state_provoking_vertex = <optimized out>
        old_uses_gs_state_outprim = false
        old_ps = 0x0
        old_spi_shader_col_format = 0
        r = <optimized out>
        vgt_stages = <optimized out>
        ge_cntl = <optimized out>
        hw_vs = <optimized out>
        db_shader_control = <optimized out>
#20 0xf59eecb5 in si_draw<(amd_gfx_level)13, (si_has_tess)0, (si_has_gs)0, (si_has_ngg)1, (si_is_draw_vertex_state)0, (si_has_sh_pairs_packed)0, (util_popcnt)0> (ctx=<optimized out>, 
    info=<optimized out>, drawid_offset=<optimized out>, indirect=<optimized out>, draws=<optimized out>, num_draws=<optimized out>, state=<optimized out>, partial_velem_mask=<optimized out>)
    at ../src/gallium/drivers/radeonsi/si_state_draw.cpp:2197
        sctx = <optimized out>
        instance_count = 1
        vs = <optimized out>
        prim = <optimized out>
        total_direct_count = <optimized out>
        old_ngg_culling = <optimized out>
        gfx9_scissor_bug = <optimized out>
        masked_atoms = <optimized out>
        vstate = 0x0
        indexbuf = 0x0
        index_size = 0
        index_offset = 0
        min_direct_count = <optimized out>
        primitive_restart = <optimized out>
        sctx = <optimized out>
        instance_count = <optimized out>
        vs = <optimized out>
        vstate = <optimized out>
        prim = <optimized out>
        indexbuf = <optimized out>
        index_size = <optimized out>
        index_offset = <optimized out>
        min_direct_count = <optimized out>
        total_direct_count = <optimized out>
        old_ngg_culling = <optimized out>
        gfx9_scissor_bug = <optimized out>
        masked_atoms = <optimized out>
        primitive_restart = <optimized out>
        gs_tri_strip_adj_fix = <optimized out>
        start = <optimized out>
        count = <optimized out>
        start_offset = <optimized out>
        size = <optimized out>
        start_offset = <optimized out>
        i = <optimized out>
        count = <optimized out>
        rast_prim = <optimized out>
        hw_vs = <optimized out>
        rs = <optimized out>
        ngg_culling = <optimized out>
        zstex = <optimized out>
#21 si_draw_vbo<(amd_gfx_level)13, (si_has_tess)0, (si_has_gs)0, (si_has_ngg)1, (si_has_sh_pairs_packed)0> (ctx=0x83697d0, info=0xffc4a1d0, drawid_offset=0, indirect=0x0, draws=0xffc4a1c0, 
    num_draws=1) at ../src/gallium/drivers/radeonsi/si_state_draw.cpp:2319
No locals.
#22 0xf59e4053 in si_draw_rectangle (blitter=0x83754e0, vertex_elements_cso=0x8351620, get_vs=0xf583b130 <get_vs_passthrough_pos_generic>, x1=0, y1=0, x2=32, y2=32, depth=1, num_instances=1, 
    type=UTIL_BLITTER_ATTRIB_NONE, attrib=0x0) at ../src/gallium/drivers/radeonsi/si_state_draw.cpp:2388
        pipe = 0x83697d0
        sctx = 0x83697d0
        attribute_ring_address_lo = 0
        info = {mode = MESA_PRIM_COUNT, index_size = 0 '\000', view_mask = 0 '\000', primitive_restart = false, has_user_indices = false, index_bounds_valid = false, increment_draw_id = false, 
          take_index_buffer_ownership = false, index_bias_varies = false, was_line_loop = false, _pad = 0 '\000', start_instance = 0, instance_count = 1, restart_index = 0, index = {
            resource = 0x0, user = 0x0}, min_index = 0, max_index = 0}
        draw = {start = 0, count = 3, index_bias = 137702704}
#23 0xf583e526 in util_blitter_clear_custom (blitter=0x83754e0, width=32, height=32, num_layers=1, clear_buffers=4, color=0xec28bdc0, depth=depth@entry=1, stencil=0, custom_dsa=0x0, 
    msaa=false, custom_blend=<optimized out>) at ../src/gallium/auxiliary/util/u_blitter.c:1599
        get_vs = 0xf583b130 <get_vs_passthrough_pos_generic>
        ctx = <optimized out>
        pipe = <optimized out>
        sr = <optimized out>
        pass_generic = true
        type = UTIL_BLITTER_ATTRIB_NONE
#24 0xf583e710 in util_blitter_clear (blitter=<optimized out>, width=<optimized out>, height=<optimized out>, num_layers=<optimized out>, clear_buffers=<optimized out>, color=<optimized out>, 
    depth=1, stencil=0, msaa=false) at ../src/gallium/auxiliary/util/u_blitter.c:1618
No locals.
#25 0xf53b5255 in si_clear (ctx=0x83697d0, buffers=<optimized out>, scissor_state=0x0, color=0xec28bdc0, depth=1, stencil=0) at ../src/gallium/drivers/radeonsi/si_clear.c:1192
        sctx = 0x83697d0
        fb = 0x836a040
        zsbuf = <optimized out>
        zstex = 0x8364600
        needs_db_flush = <optimized out>
#26 0xf50fe802 in tc_call_clear (pipe=0x83697d0, call=0xec28bdac) at ../src/gallium/auxiliary/util/u_threaded_context.c:4716
        p = 0xec28bdac
#27 0xf50ff59d in batch_execute (batch=0xec28bd58, pipe=0x83697d0, last=0xec28bdd4, parsing=false) at ../src/gallium/auxiliary/util/u_threaded_context.c:461
        call = 0xec28bdac
        iter = 0xec28bdac
        first = <optimized out>
#28 tc_batch_execute (job=<optimized out>, gdata=0x0, thread_index=0) at ../src/gallium/auxiliary/util/u_threaded_context.c:512
        batch = 0xec28bd58
        pipe = 0x83697d0
        last = 0xec28bdd4
        tc = <optimized out>
        fence = <optimized out>
#29 0xf50ffebc in _tc_sync (tc=tc@entry=0xec28a010, func=<optimized out>, info=<optimized out>) at ../src/gallium/auxiliary/util/u_threaded_context.c:767
        last = <optimized out>
        next = 0xec28bd58
        synced = <optimized out>
        _mesa_trace_scope_731 = 0
#30 0xf51078a2 in tc_flush (_pipe=0xec28a010, fence=0x0, flags=0) at ../src/gallium/auxiliary/util/u_threaded_context.c:3699
        tc = 0xec28a010
        pipe = 0x83697d0
        screen = 0x8241b90
        async = false
        deferred = false
        __func__ = <optimized out>
#31 0xf4bdd4cb in st_flush (st=0x835fa70, fence=0x0, flags=0) at ../src/mesa/state_tracker/st_cb_flush.c:63
        _mesa_trace_scope_55 = 0
#32 st_glFlush (ctx=0xec254010, gallium_flush_flags=0) at ../src/mesa/state_tracker/st_cb_flush.c:99
        st = 0x835fa70
#33 0xf4d271fa in _mesa_make_current (newCtx=0x0, drawBuffer=0x0, readBuffer=0x0) at ../src/mesa/main/context.c:1506
        curCtx = 0xec254010
        __func__ = <optimized out>
#34 0xf4bf8ed6 in st_api_make_current (st=0x0, stdrawi=0x0, streadi=0x0) at ../src/mesa/state_tracker/st_manager.c:1186
        ctx = 0xec254010
        stdraw = 0x0
        stread = 0x0
        ret = <optimized out>
#35 0xf4b22371 in dri_unbind_context (ctx=0x8381070) at ../src/gallium/frontends/dri/dri_context.c:295
        st = 0x835fa70
#36 0xf4b25da2 in driUnbindContext (pcp=0x8381070) at ../src/gallium/frontends/dri/dri_util.c:739
No locals.
#37 0xf741483e in dri2_make_current (disp=0x81e8270, dsurf=0x0, rsurf=0x0, ctx=<optimized out>) at ../src/egl/drivers/dri2/egl_dri2.c:1748
        old_cctx = <optimized out>
        dri2_dpy = 0x81e90b0
        dri2_ctx = 0x0
        old_disp = 0x81e8270
        old_dri2_dpy = 0x0
        old_ctx = 0x83808c0
        old_dsurf = 0x835e760
        old_rsurf = 0x835e760
        tmp_dsurf = 0x81e8278
        tmp_rsurf = 0xf74ebf6c
        ddraw = <optimized out>
        rdraw = <optimized out>
        cctx = <optimized out>
        egl_error = 12288
#38 0xf740452d in eglMakeCurrent (dpy=0x81e8270, draw=0x0, read=0x0, ctx=0x0) at ../src/egl/main/eglapi.c:982
        __rs = {0x0, 0x0, 0x0, 0x0}
        __rsp = 0xffc4a5bc
        disp = <optimized out>
        context = <optimized out>
        draw_surf = <optimized out>
        read_surf = <optimized out>
        ret = 0
        __func__ = "eglMakeCurrent"
#39 0xf744a179 in InternalLoseCurrent () at /usr/src/debug/libglvnd-1.7.0-4.fc40.i386/src/EGL/libegl.c:551
        apiState = 0x835cc50
        ret = <optimized out>
#40 0xf7da669d in SDL_EGL_MakeCurrent (_this=0x81de100, egl_surface=0x0, context=0x0) at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/SDL_egl.c:1113
        egl_context = 0x0
#41 0xf7df888b in Wayland_GLES_MakeCurrent (_this=0x81de100, window=0x0, context=0x0) at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/wayland/SDL_waylandopengles.c:182
        ret = <optimized out>
#42 0xf7db75f7 in SDL_GL_MakeCurrent_REAL (window=0x0, context=0x0) at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/SDL_video.c:4104
        retval = <optimized out>
#43 0xf7dbe87a in SDL_DestroyWindow_REAL (window=0x83512c0) at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/SDL_video.c:3288
        display = <optimized out>
#44 0xf7dbe984 in SDL_DestroyWindow_REAL (window=<optimized out>) at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/SDL_video.c:3264
        display = <optimized out>
        display = <optimized out>
        data = <optimized out>
#45 SDL_VideoQuit_REAL () at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/SDL_video.c:3407
        i = <optimized out>
#46 0xf7cedcaf in SDL_VideoQuit_REAL () at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/video/SDL_video.c:3393
        i = <optimized out>
        display = <optimized out>
#47 SDL_QuitSubSystem_REAL (flags=62001) at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/SDL.c:440
No locals.
#48 0xf7cee163 in SDL_Quit_REAL () at /usr/src/debug/SDL2-2.30.1-1.fc40.i386/src/SDL.c:505
No locals.
#49 0xf7b1e46a in __run_exit_handlers (status=<optimized out>, listp=<optimized out>, run_list_atexit=<optimized out>, run_dtors=<optimized out>) at exit.c:108
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        arg = <optimized out>
        __futex = <optimized out>
        f = <optimized out>
        new_exitfn_called = <optimized out>
        cur = 0xf7cd43e0 <initial>
        restart = <optimized out>
#50 0xf7b1e663 in __GI_exit (status=0) at exit.c:138
No locals.
#51 0xf7b04bcf in __libc_start_call_main (main=main@entry=0x80555b7 <main>, argc=argc@entry=1, argv=argv@entry=0xffc4a904) at ../sysdeps/nptl/libc_start_call_main.h:74
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-137548236, 134567440, -135193760, 0, 781508237, -950830947}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0xf7f11b60 <_rtld_local_ro>, 
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = -135193760}}}
        not_first_call = <optimized out>
#52 0xf7b04c88 in __libc_start_main_impl (main=0x80555b7 <main>, argc=1, argv=0xffc4a904, init=0x8055610 <__libc_csu_init>, fini=0x8055680 <__libc_csu_fini>, rtld_fini=0xf7ee2fa0 <_dl_fini>, 
    stack_end=0xffc4a8fc) at ../csu/libc-start.c:360
No locals.
#53 0x08051a71 in _start ()
``

**Comment by vaxerski** [comment]
this is not from hyprland

**Comment by vaxerski** [comment]
what I meant is the stacktrace is not from hyprland, but from some sdl app
