### ISSUE TITLE
Multiple monitors on the same workspace

### ISSUE THREAD

**Issue by screwdriver99** [hyprwm/Hyprland#599]
I suggest an useful feature in my opinion.
In GNOME it's called: **"Workspaces span displays"**

In this setup, a single workspace is valid for all the display (or a part of them, why not?) and changing the workspace causes all monitors switch workspace. The new workspace is still the same for all monitors, and so on..

**Comment by vaxerski** [comment]
no. You can achieve this with a simple script. See [the wiki](https://wiki.hyprland.org/Configuring/Expanding-functionality/)

**Comment by screwdriver99** [comment]
Ok, could you please tell me how? Maybe you got me wrong. I'm talking about changing the way Hyprland manages workspaces. Currently, it assigns a workspace to every monitor. I'm talking about considering multiple monitors the same workspace. I tried to change this in the .conf but i cannot find the solution. How can i achieve this with a script?

**Comment by vaxerski** [comment]
make a script that, when called with a number, e.g. `1` changes the workspace on monitor 1 to `1a`, monitor 2 to `1b`, etc.

you can change a workspace on a select monitor by first doing `focusmonitor` and then `workspace`.

I'd recommend to put it all in a `hyprctl --batch` for a more efficient call.

**Comment by screwdriver99** [comment]
[the wiki](https://wiki.hyprland.org/Configuring/Advanced-config/#workspaces) does not tell anything about workspaces like "1a" or "1b", indeed, running a test command like:
`hyprctl --batch "dispatch focusmonitor 1 ; dispatch workspace 3b ; dispatch focusmonitor 0 ; dispatch workspace 3a"`
does nothing

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/187971425-ab1ff824-19ed-4d00-a833-a739658cf20d.png)
reading hard innit
