### ISSUE TITLE
cursor_inactive_timeout

### ISSUE THREAD

**Issue by se7en-x230** [hyprwm/Hyprland#5990]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 38911d6df4977b6b00557cc887eb151d032e505b  (box: fix noNegativeSize).
Date: Fri May 10 13:59:01 2024
Tag: v0.40.0-55-g38911d6d, commits: 4661

flags: (if any)


System Information:
System name: Linux
Node name: hypr-home
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

did the  cursor_inactive_timeout command change?

### How to reproduce

add 
cursor_inactive_timeout = 3 # Hyprland uses second
to the hyprland.conf

**Comment by gordon-ferguson** [comment]
I'm on the newest version with the same setting at 5 and it works just fine for me.

**Comment by se7en-x230** [comment]
general {
cursor_inactive_timeout = 3 # Hyprland uses second
}

in my userprefs.conf which get's sourced

even if I add it directly to hyprland.conf does not work anymore.
It did before

**Comment by se7en-x230** [comment]
> [b0861b6](https://github.com/hyprwm/Hyprland/commit/b0861b6709c1735dc5b4275e5d87b7c83f1ef1f0) the wiki hasn't been updated yet

thanks 

cursor {
inactive_timeout = 3
}

fixed it
