### ISSUE TITLE
Crash when trying to re-enable a disabled monitor

### ISSUE THREAD

**Issue by nijek** [hyprwm/Hyprland#5991]
### Hyprland Version

Hyprland, built from branch main at commit d7aed240db408259228bf09708986c82bdca23eb  (text-input-v3: atomically enable/disable on commit).
Date: Thu May 9 10:27:48 2024
Tag: v0.40.0-37-gd7aed240, commits: 4643

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

I have a laptop (monitor eDP-1) and an external monitor (monitor HDMI-A-1).  If I disable anyone of those via
`hyprctl keyword monitor "eDP-1, disable`
and try to re-enable
`hyprctl keyword monitor "eDP-1, enable`
sometimes Hyprland crashes. 
If I unplug the external monitor, Hyprland also crashes. 

### How to reproduce

1. Plug in and external monitor
2. Try to disable your laptop monitor via `hyprctl keyword monitor "eDP-1, disable`
3. Try to re-enable your laptop monitor via `hyprctl keyword monitor "eDP-1, enable`
4. Sometimes it crashes.

### Crash reports, logs, images, videos

Crash reports:
[crash trying to enable eDP1.txt](https://github.com/hyprwm/Hyprland/files/15275954/crash.trying.to.enable.eDP1.txt)
[crash Trying to enable HDMI-A-1.txt](https://github.com/hyprwm/Hyprland/files/15275955/crash.Trying.to.enable.HDMI-A-1.txt)
[crash trying to unplug or plug the external monitor.txt](https://github.com/hyprwm/Hyprland/files/15275956/crash.trying.to.unplug.or.plug.the.external.monitor.txt)

**Comment by MightyPlaza** [comment]
likely fixed in https://github.com/hyprwm/Hyprland/commit/fe4737fb9d578400ecfc63dc6ab4d684993362b8

**Comment by vaxerski** [comment]
ye

**Comment by nijek** [comment]
Yes, it is fixed now. Thanks!!
