### ISSUE TITLE
Crash when stopping Vesktop screen share after window has closed

### ISSUE THREAD

**Issue by Insprill** [hyprwm/Hyprland#5993]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 38911d6df4977b6b00557cc887eb151d032e505b  (box: fix noNegativeSize).
Date: Fri May 10 07:59:01 2024
Tag: v0.40.0-55-g38911d6d, commits: 4661

flags: (if any)


System Information:
System name: Linux
Node name: iusearchbtw
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2024.01.25"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When sharing a window with [Vesktop](https://github.com/Vencord/Vesktop) (Discord client with Linux fixes & Vencord), if the window is closed, the stream remains. Stopping the stream then causes Hyprland to crash.

### How to reproduce

- Open Vesktop and another window.
- Starting screen sharing the other window (the popup will usually show 3 times, select the same window all 3).
- Close the other window.
- Stop the stream in Vesktop.

### Crash reports, logs, images, videos

[hyprlandCrashReport3319.txt](https://github.com/hyprwm/Hyprland/files/15276239/hyprlandCrashReport3319.txt)

xdg-desktop-portal-hyprland built from https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/1f228ba2f1f254195c0b571302b37482861abee3

**Comment by Agent00Ming** [comment]
#5326

**Comment by Insprill** [comment]
Ah, I missed that, looks like the same issue. Closing.
