### ISSUE TITLE
wlr_backend_autocreate() failed!

### ISSUE THREAD

**Issue by Moorocks** [hyprwm/Hyprland#5995]
### Hyprland Version

![image](https://github.com/hyprwm/Hyprland/assets/143619572/14c77b05-c0f8-4169-b195-80c274d5ccb9)

### Bug or Regression?

Bug

### Description

My nvidia drivers were not getting detected, however i went ahead and installed hyprland. But once my vm restarted, I can see that hyprland was not installed correclty. so when i tried to run the command Hyprland, it threw me error.

### How to reproduce

1.sudo nano /etc/apt/sources.list -- remove the comments
2.sudo apt update && sudo apt upgrade -y
3.lspci | grep -i vga # did not get nvidia driver
![image](https://github.com/hyprwm/Hyprland/assets/143619572/6274b604-41e7-4636-9287-0e30fcbed822)

5.sudo apt install libdrm-dev python3-pip
6. Perform git clone of your directory
7. chmod +x install.sh
8. ./install.sh
9. did not choose y for nvidia gpu question and selected y for remaining options

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/143619572/7b171b63-1ce5-461e-8bfc-10311d219812)
[hyprland_errors.txt](https://github.com/hyprwm/Hyprland/files/15276481/hyprland_errors.txt)
[crashreport.txt](https://github.com/hyprwm/Hyprland/files/15276482/crashreport.txt)

Environment:
Linux Distro: Kali

Linux Version : Kali 6.6.15-amd64

**Comment by lespea** [comment]
I had a similar crash but in my crashreport it said "vulkan" was disabled vs yours saying x11.  Do you have `WLR_RENDERED` set in your hypr.conf?  I just commented mine out and then it at least launched.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/7bc72718-e82e-4c2b-a85f-6c28e3257b8a)

X11 is not supported

**Comment by Moorocks** [comment]
All i had to do is enable 3d acceleration and it worked, but from what i see it is not meant to be installed in vmware or hyperv platforms.
Better to install it in hardware.

https://github.com/JaKooLit/Debian-Hyprland/issues/70
