### ISSUE TITLE
Error with `hyprpm update` since updating to 0.40.0

### ISSUE THREAD

**Issue by ouzbirki** [hyprwm/Hyprland#6001]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 630 [8086:591b] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Bug or Regression?

Regression

### Description

After updating Hyprland to 0.40.0, `hyprpm update` command started giving the following error:

```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5637 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

I know it's about git, I tried to mess with `.gitconfig` changing the postbuffer size to huge amounts and changing http version to 1.1 but none of that worked. I tried executing the command on different networks, which I'm pretty sure at least one of them must be stable (altough I know my regular connection is stable), but the result remains same.

### How to reproduce

1. Update Hyprland to 0.40.0 through Arch Linux repo
2. Execute the command `hyprpm update` to update plugins & headers
3. Fails

**Comment by vaxerski** [comment]
please post the _full_ output of `hyprpm update -v`

**Comment by ouzbirki** [comment]
After a couple of reboots to both computer and router it worked again. Maybe there was a problem between Github and me at the time. So I'm closing the issue as it looks like nothing to do with Hyprland.
