### ISSUE TITLE
VirtualBox cann't show any windows at all but hyptctl says there is vbox windows

### ISSUE THREAD

**Issue by StinkAndShityAura** [hyprwm/Hyprland#6004]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

after latest update, when i try to start virtualbox, there were nothing show up. So i using `hyprctl clients` checked, it said there have vbox window. So vbox window is invisible now i guess?

VirtualBox Version:
```
(base) [10:21:21 05/11]ghoti=>~ | vboxmanage --version
7.0.18r162988
```

### How to reproduce

I didn't do any special move. Just update to latest, open virtualbox with rofi and this bug triggered.

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/28909778/51042a42-36a8-4d79-af2a-135f1df89e47)

Didn't find relevant log in `$XDG_RUNTIME_DIR/hypr` and `~/.cache/hyprland`

**Comment by vaxerski** [comment]
ah yes, xwayland.

![image](https://github.com/hyprwm/Hyprland/assets/43317083/e71ed97b-93d2-458d-9a72-a89be546b54d)

As you can see, it's in narnia. Just set a windowrule to move it to the center, or use `cyclenext` until you focus it and do `togglefloating`

At any rate, it's the app's fault
