### ISSUE TITLE
Where did /tmp/hypr go in v0.40.0?

### ISSUE THREAD

**Issue by neilking01** [hyprwm/Hyprland#6005]
### Hyprland Version

0.40.0

### Bug or Regression?

Bug

### Description

Some of my scripts require /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE to be present but this path does not exist in version 0.40.0.  If i try to run hyprctl with any command it complains that this path does not exist.  Is this a bug?

### How to reproduce

run hyprctl on version 0.40.0
it will complain about /tmp/hypr not existing

example error:
`❯ hyprctl version                                                         ~
Couldn't connect to /tmp/hypr/cba1ade848feac44b2eda677503900639581c3f4_1715395443_707746444/.socket.sock. (3)
`

**Comment by sungyoonc** [comment]
It moved to `$XDG_RUNTIME_DIR/hypr`

**Comment by neilking01** [comment]
any idea why hyprctl does not behave accordingly?

**Comment by sungyoonc** [comment]
no clue

**Comment by Aqa-Ib** [comment]
what is your output of `echo $XDG_RUNTIME_DIR/hypr`

**Comment by neilking01** [comment]
> what is your output of echo $XDG_RUNTIME_DIR/hypr

/run/user/1000/hypr

**Comment by Aqa-Ib** [comment]
do you see contents in there ?

maybe if you build hyprland from latest git commit it would fix, there are a lot of changes lately.

**Comment by sungyoonc** [comment]
Maybe you are using old version of hyprctl with the new version of Hyprland somehow? though hyprctl should be updated together when you update hyprland.

**Comment by neilking01** [comment]
I feel really stupid.  For some reason I had a hyprctl in /usr/local/bin that was overriding the one in /usr/bin.  Will close this.
