### ISSUE TITLE
[BUG] workspace breaks on key binding randomly

### ISSUE THREAD

**Issue by rtgiskard** [hyprwm/Hyprland#6015]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ed3a888fc274e09a5097ebbe3d206e4bc85bbb87  (hyprpm: fix style).
Date: Sat May 11 06:56:54 2024
Tag: v0.40.0-59-ged3a888f, commits: 4665

flags: (if any)


System Information:
System name: Linux
Node name: desk
Release: 6.8.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 730] [8086:4c8b] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Some time a workspace just suddenly disappeared(get destroyed) on key bind (not specific one), and the all the windows in it are killed.

This problem has been there since at least 0.39.1, it happens sometime, still no stable way to reproduce:

1. seems to be related to key binds, generally at the time to create a new window with key bind
2. with the first key bind to trigger the issue, the workspace seems to be freezing for seconds before it disappeared
3. it's running two monitors, the workspace in the other monitor lives well
4. a line of ERR in log right before it breaks: `[ERR] BUG THIS: key not found in m_dPressedKeys`

### How to reproduce

Not found stable ways to reproduce it, if you need any other info, please tell

### Crash reports, logs, images, videos

Here are the logs near the break:

05:38:32: [workspace_die_053832.log](https://github.com/hyprwm/Hyprland/files/15282223/workspace_die_053832.log)

08:17:22: [workspace_die_081722.log](https://github.com/hyprwm/Hyprland/files/15282224/workspace_die_081722.log)

**Comment by rtgiskard** [comment]
and again with key bind to switch workspace:
[workspace_die_091327.log](https://github.com/hyprwm/Hyprland/files/15282297/workspace_die_091327.log)

**Comment by vaxerski** [comment]
it doesn't suggest a hyprland issue - that log about pressed keys can be ignored.

launch a window from a terminal in the affected workspace(s) with WAYLAND_DEBUG=1 (e.g. `WAYLAND_DEBUG=1 kitty &| tee ./kitty1.log`) and upload the last part of the log once it "crashes". (Note: the logs might be huge if you need an hour or two to get this to happen, just `tail -n 1000` of it is ok)

**Comment by rtgiskard** [comment]
Well, this seems to be related to foot, and as many times I'm debugging waybar and something else run from terminal which is `foot-client`, once `foor-server` breaks, all of this will be killed, for which it's just like many other applications get killed, and then the free workspace get released
