### ISSUE TITLE
screen capture broken

### ISSUE THREAD

**Issue by VDFOREVER** [hyprwm/Hyprland#6016]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
System Information:
System name: Linux
Node name: artixlinux
Release: 6.8.9-artix1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 08 May 2024 17:34:57 +0000


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo
```

</details>

### Bug or Regression?

Bug

### Description

After updating to version 40, obs and vesktop stopped capturing the screen

### How to reproduce

I don't know how to reproduce this on another PC, maybe it's because I'm using openrc

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15282350/hyprland.log)

**Comment by vaxerski** [comment]
that's handled by xdph. https://wiki.hyprland.org/Useful-Utilities/xdg-desktop-portal-hyprland/

If you are on openrc, you likely need to start it manually

**Comment by VDFOREVER** [comment]
It worked fine before the update, but after that it no longer worked.

**Comment by VDFOREVER** [comment]
Although yes, if you run it manually everything works
