### ISSUE TITLE
Firefox Extensions uninfluenced by `windowrules`

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#602]
Windows that are opened by Firefox extensions cannot be affected by `windowrules`.

I have an extension called Tree Style Tabs that opens a window (that should be a modal) to ask for confirmation to discard many tabs.

The output from `hyprctl clients` when the window in question is open looks like the following:
```
Window 2734070 -> Extension: (Tree Style Tab) - Close tabs? — Mozilla Firefox:
	at: 2888,14
	size: 938,1052
	workspace: 2 (2)
	floating: 0
	monitor: 1
	class: firefox
	title: Extension: (Tree Style Tab) - Close tabs? — Mozilla Firefox
	pid: 152850
	xwayland: 0
```

I try to match `Extension` in the title for all Firefox windows, so that any window opened by an extension will float by default.
```
windowrule=float,title:^(Extension)(.+)(Firefox)(.*)$
```

Then the size is set for a more specific pattern, matching if `Close tabs` is in the middle of the title.
```
windowrule=size 630 470,title:^(Extension)(.+)(Close tabs)(.+)(Firefox)(.*)$
```

Neither of these rules work, and neither do less-strict patterns that only look for `title:Extension`.

I have verified both of these regex patterns, and that `windowrules` works for other programs.

**Comment by vaxerski** [comment]
```
watch -n 0.1 "cat /tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/hyprland.log | grep -v "efresh" | grep "rule" | tail -n 40"
```

will tail the logs. Whenever a window is open, it will log searching rules, e.g.:
```
[LOG] Searching for matching rules for org.kde.dolphin (title: Extracting Files (86%) — Dolphin)
```

Those are the arguments passed to the regex checks. If an app is written by an idiot, it may set its title *after* mapping, meaning it's basically unmatchable in the current windowrule state.

**Comment by spikespaz** [comment]
That does appear to be the issue. This is the window that opens:
```
[LOG] Set keyboard focus to surface 1ea1300, with window name: Firefox Extensions uninfluenced by `windowrules`  Issue #602  hyprwm/Hyprland  Mozilla Firefox
```
This is what it changes to:
```
Window 1ee3140 -> Extension: (Tree Style Tab) - Close tabs? — Mozilla Firefox:
	at: 968,14
	size: 938,1052
	workspace: 2 (2)
	floating: 0
	monitor: 1
	class: firefox
	title: Extension: (Tree Style Tab) - Close tabs? — Mozilla Firefox
	pid: 119264
	xwayland: 0
	```

**Comment by spikespaz** [comment]
Any hope for a remedy? Is it possible to get a signal from somewhere every time a window changes its title?

**Comment by vaxerski** [comment]
it's planned.

**Comment by vaxerski** [comment]
Since dynamic window rules have been impl'd a while back, I am closing this.

`float` rules cannot be dynamic though, as it would require an active change after the window has already been created.

**Comment by babariviere** [comment]
Hello, is there any solution to this? I have an extension which has a popup that goes fullscreen and I have no way to make floating and/or smaller. 
The `nofullscreenrequest` and `nomaximizerequest` aren't affecting these popup. Even setting maxsize/minsize/size doesn't affect the window (and I have checked that the rule matches in the log).

**Comment by musjj** [comment]
I'm having the same problem with Bitwarden popups in Firefox. The following works, but it affects all Firefox windows:

```ini
windowrulev2=float,class:^firefox$
windowrulev2=nofullscreenrequest,class:^firefox$
```

But the following doesn't:

```ini
windowrulev2=float,class:^firefox$,title:^Extension:
windowrulev2=nofullscreenrequest,class:^firefox$,title:^Extension:
```

**Comment by spikespaz** [comment]
@musjj missing `.*`

**Comment by musjj** [comment]
@spikespaz 
Doesn't work either, unfortunately.

**Comment by nikita-talalai** [comment]
That works for me: `windowrulev2=nomaximizerequest, class:.*`
In my case, I was getting annoying notifications on half screen from "Simple Tab Groups" extension (btw, great extension for managing sessions)

**Comment by littleblack111** [comment]
Anyone here figured out a solution?

**Comment by JManch** [comment]
Here's a snippet of my socket script for floating the bitwarden extension. Works well for me.
```bash
windowtitlev2() {
  IFS=',' read -r -a args <<< "$1"
  args[0]="${args[0]#*>>}"

  if [[ ${args[1]} == "Extension: (Bitwarden Password Manager) - — Mozilla Firefox" ]]; then
    hyprctl --batch "\
      dispatch setfloating address:0x${args[0]}; \
      dispatch resizewindowpixel exact 20% 50%, address:0x${args[0]}; \
      dispatch centerwindow; \
    "
  fi
}

handle() {
  case $1 in
    windowtitlev2\>*) windowtitlev2 "$1" ;;
  esac
}

socat -U - UNIX-CONNECT:"/$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" \
  | while read -r line; do handle "$line"; done
```

**Comment by thomaswilliams123** [comment]
> Here's a snippet of my socket script for floating the bitwarden extension. Works well for me.
> 
> windowtitlev2() {
>   IFS=',' read -r -a args <<< "$1"
>   args[0]="${args[0]#*>>}"
> 
>   if [[ ${args[1]} == "Extension: (Bitwarden Password Manager) - — Mozilla Firefox" ]]; then
>     hyprctl --batch "\
>       dispatch setfloating address:0x${args[0]}; \
>       dispatch resizewindowpixel exact 20% 50%, address:0x${args[0]}; \
>       dispatch centerwindow; \
>     "
>   fi
> }
> 
> handle() {
>   case $1 in
>     windowtitlev2\>*) windowtitlev2 "$1" ;;
>   esac
> }
> 
> socat -U - UNIX-CONNECT:"/$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" \
>   | while read -r line; do handle "$line"; done

was this posted into the config file or as its own thing?

**Comment by littleblack111** [comment]
> > Here's a snippet of my socket script for floating the bitwarden extension. Works well for me.
> > 
> > windowtitlev2() {
> >   IFS=',' read -r -a args <<< "$1"
> >   args[0]="${args[0]#*>>}"
> > 
> >   if [[ ${args[1]} == "Extension: (Bitwarden Password Manager) - — Mozilla Firefox" ]]; then
> >     hyprctl --batch "\
> >       dispatch setfloating address:0x${args[0]}; \
> >       dispatch resizewindowpixel exact 20% 50%, address:0x${args[0]}; \
> >       dispatch centerwindow; \
> >     "
> >   fi
> > }
> > 
> > handle() {
> >   case $1 in
> >     windowtitlev2\>*) windowtitlev2 "$1" ;;
> >   esac
> > }
> > 
> > socat -U - UNIX-CONNECT:"/$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" \
> >   | while read -r line; do handle "$line"; done
> 
> was this posted into the config file or as its own thing?

Bash script

**Comment by xoconoch** [comment]
Hey uhh, is this possible natively now with the lua config?
