### ISSUE TITLE
Using global key bindings will cause the app to lose keyboard focus

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/Hyprland#6022]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit b6a7fb9e9125e56bf742f68e0ec46f52d5c34f4c dirty (layersurface: fix invalid use of std::move).
Date: Sat May 11 16:43:44 2024
Tag: v0.40.0-61-gb6a7fb9e, commits: 4667

flags: (if any)


System Information:
System name: Linux
Node name: localhost
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7) (prog-if 00 [VGA controller])
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

The problem occurs after using a keybind with the `pass` dispatcher. Regression from https://github.com/hyprwm/Hyprland/commit/7cf810b1813a610e25f169ca9bb2d8ab9b967666. Reverting https://github.com/hyprwm/Hyprland/commit/337422911895bb55099e00208bff929651dcb5d2 and https://github.com/hyprwm/Hyprland/commit/7cf810b1813a610e25f169ca9bb2d8ab9b967666 solves the problem.

### How to reproduce

Above.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15284358/patch.txt)
I assume this fixes it then?

**Comment by bubba-champion** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/15284358/patch.txt) I assume this fixes it then?

Yea, this fixes it.
