### ISSUE TITLE
Damage tracking is broken

### ISSUE THREAD

**Issue by System64fumo** [hyprwm/Hyprland#6029]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 38911d6df4977b6b00557cc887eb151d032e505b  (box: fix noNegativeSize).
Date: Fri May 10 14:59:01 2024
Tag: v0.40.0-55-g38911d6d, commits: 4661

flags: (if any)


System Information:
System name: Linux
Node name: frostbite
Release: 6.8.9-xanmod1-1-edge
Version: #1 SMP PREEMPT_DYNAMIC Sun, 05 May 2024 20:56:31 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti Lite Hash Rate] [10de:2489] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland, forwhatever reason now freezes fullscreen videos in firefox (And only firefox)
I normally use firefox-nightly but even regular firefox has this issue..
Chromium is unaffected, Neither are any other media apps such as MPV

### How to reproduce

1: Open firefox
2: Watch a video on youtube (Or any other website with media in it)
3: Either fullscreen the video or firefox itself
4: Observe as the video stops updating unless you move your cursor

### Crash reports, logs, images, videos

I'm unable to record this as recording it causes the video to update.

Additional info:
I've recently updated from hyprland 0.39 to hyprland 0.40
For now i've set damage_tracking to 0 which fixes my issues.

**Comment by vaxerski** [comment]
dupe #5973
