### ISSUE TITLE
apply no_gaps_when_only to groups

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#603]
If there is one group on a workspace that contains all window of that workspace, 
than only one window is shown.
Of course it's not the only window on that workspace so no_gaps_when_only isn't triggered.

**Comment by vaxerski** [comment]
fixed in 56203b175752b49c46eb9303c37b80cd4c2dfcf8

**Comment by Dickby** [comment]
Great, thanks!

**Comment by Dickby** [comment]
There's a tiny glitch though:
if i have a group of 2 windows on a workspace that contains no other windows everything works fine
and the gaps are not there as they should. But if i now close one of the two grouped windows, the 
remaining window has gaps.
