### ISSUE TITLE
Cursor manages to leave the screen, hyprland crashes when opening an app in the glitched workspace.

### ISSUE THREAD

**Issue by redyf** [hyprwm/Hyprland#6030]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 33a7b7bb6b307d6e4a093f75ffdda0419cd7ffaf  ().
Date: 2024-05-11
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: redyf
Release: 6.6.30
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1650 SUPER] [10de:2187] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240509.f1010e0"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

The cursor manages to leave the screen if you drag it to the right side. Switching workspaces doesn't work all the time, and if it doesn't work, the workspace number won't be displayed on waybar. Hyprland crashes when I open an application in the glitched workspace.

Example: I'm on workspace 1 and want to go to workspace 3, I press the keybind to go there and both my workspace number on waybar and the mouse cursor disappear. If I open any application in this "glitched" workspace, hyprland crashes.

### How to reproduce

1- Install Hyprland with this flake: inputs.hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1;

2- Drag your cursor to the right side of the screen, it's going to leave the scale. 

3- Open any application, Hyprland will crash.
[hyprlandCrashReport189536.txt](https://github.com/hyprwm/Hyprland/files/15284590/hyprlandCrashReport189536.txt)

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/98139059/9d98cad7-5d76-4dbe-8be5-d5bc99ed04d7

https://cdn.discordapp.com/attachments/1094394444574371873/1238997819830833212/issue.mp4?ex=66415223&is=664000a3&hm=90706c9bf8aa60ffab79ca2d93075d2f00fd682688cccc3877ec7c1465f5b148& (discord link because github says the video has been corrupted even though it's working on my machine).

[hyprlandCrashReport201115.txt](https://github.com/hyprwm/Hyprland/files/15284582/hyprlandCrashReport201115.txt)

[hyprlandCrashReport189536.txt](https://github.com/hyprwm/Hyprland/files/15284591/hyprlandCrashReport189536.txt)

**Comment by redyf** [comment]
After hours looking for an explanation I realized that there is a second monitor being detected on hyprctl monitors (I don't have 2 monitors so I'm confused). That ghost monitor was on position 1920x0 so that's why the cursor could leave the screen, it's like going to the other monitor. Please ignore this issue :+1:

**Comment by vaxerski** [comment]
its a recent kernel/driver bug

**Comment by redyf** [comment]
> its a recent kernel/driver bug

I see, that started happening after I updated my system so it makes sense. Spent hours yesterday trying to figure out hahaha. Thanks for telling me
