### ISSUE TITLE
Mouse cursor doesn't "respawn" when an application hides it for a moment

### ISSUE THREAD

**Issue by RandomLegend** [hyprwm/Hyprland#6033]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 33a7b7bb6b307d6e4a093f75ffdda0419cd7ffaf  (core: fix on-empty workspace being called too often (6026)).
Date: Sun May 12 01:03:32 2024
Tag: v0.40.0-65-g33a7b7bb, commits: 4671

flags: (if any)


System Information:
System name: Linux
Node name: frank-garuda
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information:
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev cc) (prog-if 00 [VGA controller])


os-release: NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=garudalinux


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I don't know if this is even hyprland related but this is my first guess. Since a couple of days i have the issue that as soon as an application hides my mouse cursor (Games, Blender when moving a model, etc.) it doesn't respawn. So the cursor still works, but i can't see it anymore. Only when i move it over to my second monitor, it shows up again. In games (Hades, for example, this is particularly annoying as i want to lock my mouse to the game, but when i do that and it disappears i have no chance to get it back).

Interestingly enough, this doesn't happen with my browser and videoplayback.

I tried using different mouse cursors.

I tried setting the `WLR_NO_HARDWARE_CURSORS=1` including reboot.

Can someone help me identify if this is hyprland related?

### How to reproduce

Start using a program or game that hides your cursor for a moment. As soon as your cursor should reappear (opening the main menu of a game for example) it doesnt.

**Comment by Agent00Ming** [comment]
probably #5975

**Comment by RandomLegend** [comment]
i have no idea how i didn't see this existing. I swear i searched... thanks for the heads up

**Comment by Agent00Ming** [comment]
This can probably be closed, we'll keep tracking it the original one.
