### ISSUE TITLE
on-created-empty window not focused

### ISSUE THREAD

**Issue by tarpan** [hyprwm/Hyprland#6038]
### Discussed in https://github.com/hyprwm/Hyprland/discussions/6037

<div type='discussions-op-text'>

<sup>Originally posted by **tarpan** May 12, 2024</sup>
Hi, after the upgrade to hyprland v. 0.40.0 windows opened with the "on-created-empty" workspace option are no longer focused. This is irritating, as I have to move my mouse every time on such occasions for the window to get focus. It didn't behave like this in the previous versions. Can I change this behaviour in the config?</div>

**Comment by Agent00Ming** [comment]
You can disable `misc:initial_workspace_tracking` to correct that. Token system clashes with `on-created-empty` workspace rule so...

**Comment by tarpan** [comment]
That indeed fixed it. Thank you.
