### ISSUE TITLE
switching workspaces with special workspace active

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#604]
If the special workspace is active, switching to not empty workspaces will switch workspaces 'behind' the special workspace, keeping that special workspace visible.
But if the newly chosen workspace is empty, the special workspace disapears.
Is that the desired behaivour?

**Comment by vaxerski** [comment]
there is no desired behavior here really, I didn't pay attention to this, so either way is right. The standard should probably be that the active workspace closes.

**Comment by Dickby** [comment]
Would be nice to have a variable controlling the desired behavior.

**Comment by MightyPlaza** [comment]
doesn't seem to happen anymore
