### ISSUE TITLE
Can't build on last commit 

### ISSUE THREAD

**Issue by alekgr** [hyprwm/Hyprland#6040]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Installing /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/assets/wall2.png to /home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/share/hyprland
Installing /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/assets/hyprland-portals.conf to /home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/share/xdg-desktop-portal
Installing /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/example/hyprland.conf to /home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/share/hyprland
Installing /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/example/hyprland.desktop to /home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/share/wayland-sessions
Installing /home/alek/.cache/paru/clone/hyprland-git/src/Hyprland/build/meson-private/hyprland.pc to /home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/share/pkgconfig
mv: cannot stat '/home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/include/wlr': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'hyprland-git-0.38.0.r105.582d6233-1':

### How to reproduce

was building with arch

**Comment by kRHYME7** [comment]
Try building it by following the instructions in the Hyprland wiki. If it builds correctly then this issue should be closed, and should contact the Package maintainer for hyprland-git for AUR.

**Comment by sentakuhm** [comment]
@kRHYME7 bluilding is successful, the issue is at installing
`mv: cannot stat '/home/alek/.cache/paru/clone/hyprland-git/pkg/hyprland-git/usr/include/wlr': No such file or directory`

**Comment by vaxerski** [comment]
looks like an issue with the package
