### ISSUE TITLE
[BUG] togglefloating and settiled moves window to active workspace

### ISSUE THREAD

**Issue by v4u6h4n** [hyprwm/Hyprland#6047]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: desktop-0
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
13:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When I execute `hyprctl dispatch togglefloating title:<window>`, if the window is not on the active workspace, and the window is being toggled from a floating to a tiled state it will move to the active workspace. When it is being toggled from tiled to floating it functions as expected.

UPDATE: Just realised this also applies to the `settiled` dispatcher.

### How to reproduce

1. Execute `hyprctl dispatch togglefloating title:<window>`, where the window is not on the active workspace, and is currently in a floating state.

**Comment by Ligthiago** [comment]
Kinda dupe, mentioned it earlier https://github.com/hyprwm/Hyprland/issues/4967

**Comment by v4u6h4n** [comment]
Oops, thanks for heads up.

**Comment by vaxerski** [comment]
dupe
