### ISSUE TITLE
Native transparency not respected

### ISSUE THREAD

**Issue by nnra6864** [hyprwm/Hyprland#6048]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 38911d6df4977b6b00557cc887eb151d032e505b  (box: fix noNegativeSize).
Date: Fri May 10 13:59:01 2024
Tag: v0.40.0-55-g38911d6d, commits: 4661

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

When using hyprwinwrap to display an audio visualizer on the background(for example glava), windows that have native transparency(alacritty, kitty etc.) will block the rendering of such apps.
By native transparency I am referring to a setting in alacritty/kitty config.
If transparency is applied via a window rule it works fine.
This happens in the tiled mode only, if you make the window floating, it'll behave properly.
If you fullscreen the app whilst it's tiled, visualizer won't be rendered either, but if fullscreened while the app is floating it should still be visible.

### How to reproduce

Take an app with native window transparency and set it to a number less than 1.
Make sure that the app is not made transparent by the hyprland config via windowrule.
Have an app rendered on the background layer(can be achieved via hyprwinwrap).
Open the app with native transparency and put it in the tiling mode.
This should now block the rendering of a window placed on the background layer by hyprwinwrap.

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/104775644/cc6be3d8-b4c4-4d54-be76-81f4191c706c)
![image](https://github.com/hyprwm/Hyprland/assets/104775644/8ee0d401-dca2-4523-8286-d8d42bcfe24b)

**Comment by vaxerski** [comment]
this is a hyprwinwrap bug and is iirc reported there. If not, report it over there
