### ISSUE TITLE
(NixOS) Newest Hyprland update gives no output

### ISSUE THREAD

**Issue by marsupialgutz** [hyprwm/Hyprland#605]
Ever since updating from 0.11.1 to 0.12.1 (using the nix flake version of Hyprland) I get 0 output to the screen, at all. Hyprland *does* still run, doesn't crash, and applications run inside it (considering I still get audio output) but I've been unable to get any output at all on either my internal laptop display or external monitor.

I am using Nvidia's proprietary drivers (with the open source modules) and a patched wlroots for Hyprland to work properly w/ Nvidia drivers. The last version of Hyprland to work for me is `0.11.1beta+date=2022-08-29_179562b`.

Steps to reproduce:
* Update to the latest version of Hyprland.
* Run Hyprland.

Expected outcome:
* Audio and video both work normally.

Noted outcome:
* Audio continues to work as normal, but video is completely non-working.

**Comment by vaxerski** [comment]
@fufexan 

also if you are using patched wlroots they might be the root cause - we do not officially support any wlroots patching apart from the ones that we provide ourselves.

Proprietary nvidia should work w/o any patches.

please also share your log and config

**Comment by marsupialgutz** [comment]
Here's a log: 
[hypr.log](https://github.com/hyprwm/Hyprland/files/9465568/hypr.log)

And my current config (changed to .txt bc github go brr):
[garden.conf.txt](https://github.com/hyprwm/Hyprland/files/9465573/garden.conf.txt)
[hyprland.conf.txt](https://github.com/hyprwm/Hyprland/files/9465574/hyprland.conf.txt)

**Comment by fufexan** [comment]
Try using the `hyprland-no-hidpi` package with your patch.

**Comment by marsupialgutz** [comment]
> Try using the `hyprland-no-hidpi` package with your patch.

No luck :/

**Comment by viperML** [comment]
What nixos version? Also send your nixos config

**Comment by marsupialgutz** [comment]
NixOS 22.11 unstable, following nixpkgs-unstable-small

My config is hosted here: https://github.com/marsupialgutz/nix-config

**Comment by viperML** [comment]
You seem to be doing some patching of wlroots, does it work just by using the default package?
https://github.com/marsupialgutz/nix-config/blob/e99defd0fcb0ae3ae7c523f3e3f4b1aa7605a75d/pkgs/default.nix#L45

**Comment by viperML** [comment]
Also that wlroots is not the pinned wlroots we use

**Comment by fufexan** [comment]
There we go, found the culprit.

**Comment by fufexan** [comment]
```diff
- wlroots = prev.wlroots.overrideAttrs (oldAttrs: {
-   patchPhase = ''
+ wlroots = inputs.hyprland.packages.${prev.system}.wlroots-hyprland.overrideAttrs (oldAttrs: {
+   postPatch = ''
      substituteInPlace render/gles2/renderer.c --replace "glFlush();" "glFinish();"
    '';
  });
```

**Comment by vaxerski** [comment]
another idiot ignoring the pinned wlroots. at any rate, i've updated the dep so it will now work regardless

**Comment by marsupialgutz** [comment]
> ```diff
> - wlroots = prev.wlroots.overrideAttrs (oldAttrs: {
> -   patchPhase = ''
> + wlroots = inputs.hyprland.packages.${prev.system}.wlroots-hyprland.overrideAttrs (oldAttrs: {
> +   postPatch = ''
>       substituteInPlace render/gles2/renderer.c --replace "glFlush();" "glFinish();"
>     '';
>   });
> ```

Tried this, still no luck. Even tried completely removing nixpkgs-wayland from my config as that might be messing with wlroots and still nothing.

**Comment by fufexan** [comment]
The issue *was* that. Because Hyprland requires a specific wlroots commit in order to work.

Anyway, that Nvidia patch is now included, so you can install Hyprland with
```nix
hyprland-nvidia = inputs.hyprland.packages.${prev.system}.default.override {
  nvidiaPatches = true;
};
```

**Comment by marsupialgutz** [comment]
Even when using that patch I still have the same problem. I'm not sure if I'm just missing something or not :/
