### ISSUE TITLE
hyprland fails to build with asan

### ISSUE THREAD

**Issue by gulafaran** [hyprwm/Hyprland#6050]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 337422911895bb55099e00208bff929651dcb5d2  (core: remove unused includes and fix warn).
Date: Fri May 10 04:20:26 2024
Tag: v0.40.0-50-g33742291, commits: 4656

flags: (if any)


System Information:
System name: Linux
Node name: tom-legion
Release: 6.9.0-gentoo-tom
Version: #1 SMP PREEMPT_DYNAMIC Mon May 13 15:42:36 CEST 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104M [GeForce RTX 4080 Max-Q / Mobile] [10de:27e0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"
```

</details>

### Bug or Regression?

Bug

### Description

ninja: error: '/home/tom/dev/Hyprland/libwayland-server.a', needed by 'Hyprland', missing and no known rule to make it

seems commit https://github.com/hyprwm/Hyprland/commit/1ed1ce9506e65f76fe5236194516f23d662bba0b added a line to link towards `target_link_libraries(Hyprland ${CMAKE_SOURCE_DIR}/libwayland-server.a PkgConfig::ffidep)` but i dont see that provided in the repo.

### How to reproduce

compile with asan

**Comment by vaxerski** [comment]
oops, that's a mistake. Anyways you should be using make asan probably
