### ISSUE TITLE
Cannot completely disable window resize animation

### ISSUE THREAD

**Issue by A7R7** [hyprwm/Hyprland#6055]
### Hyprland Version

I'm using hyprland from nixpkgs-unstable, in which `hyprctl systeminfo` doesn't show useful informations, (like branch, commit, etc). 
hyprland's version is v0.39.1

### Bug or Regression?

Bug

### Description

After setting `animation = windowsMove, 0`, 
when resizing a window, the window still has 1 or 2 frames of stretching animation

I discovered this issue when investigating #5606

### How to reproduce

- add `animation = windowsMove, 0` to hyprland.conf
- open a few windows and resize them

### Crash reports, logs, images, videos

![Kooha-2024-05-14-16-23-23](https://github.com/hyprwm/Hyprland/assets/100180619/7610bde7-748c-428a-b13b-b3d8326e47cc)

**Comment by vaxerski** [comment]
this is not an animation - it takes a moment for your app to respond to a resize and adjust itself.
