### ISSUE TITLE
Hyprland gives blackscreen with moveable cursor. custom monitor

### ISSUE THREAD

**Issue by notsungod** [hyprwm/Hyprland#6060]
Hey guys i bought a laptop online and it has a custom monitor. Its a x200 with a lcd monitor 1280x800. 
Gpu: intel mobile 4 series chipset.
Please help me im stuck on this error and dont know how to troubleshoot!!!
The error im getting is: 
Glfw error 65543 EGL FAILED TO CREATE CONTEXT ARGUMENTS ARE INCONSISTENT
And
kitty/main.py create_os_window value error: failed to create GLFWwindow. Im using default hyprland config. How can i troubleshoot/ find right settings for my monitor?
Also a endeavours iso works perfectly fine with kde so the monitor is not the issue.![image](https://github.com/hyprwm/Hyprland/assets/123213569/65655120-bf77-4375-a7df-b166df828a70)
Sorry for not including log files in text form but shouldnt be a big problem. Please help me

**Comment by vaxerski** [comment]
that's not a hyprland error, that's an error from some random application running. I can see you're running hyprland as root, which is not supported and should never be done.

confront the wiki: https://wiki.hyprland.org/Getting-Started/Master-Tutorial/

**Comment by notsungod** [comment]
Nice support! NOT!!

**Comment by notsungod** [comment]
> that's not a hyprland error, that's an error from some random application running. I can see you're running hyprland as root, which is not supported and should never be done.
> 
> 
> 
> confront the wiki: https://wiki.hyprland.org/Getting-Started/Master-Tutorial/

How is it a random applicantion if the same setup works on a different device? Ibviousely there is some incompatibility with the monitor no?

**Comment by vaxerski** [comment]
when you're reading the tty, applications opened at startup also write to it, making the output garbled.

You'll find more information in the crash report and log, that you should've posted per issue guidelines, which you ignored.

**Comment by notsungod** [comment]
> when you're reading the tty, applications opened at startup also write to it, making the output garbled.
> 
> You'll find more information in the crash report and log, that you should've posted per issue guidelines, which you ignored.

Hey, so it seems like there is no crashreport because i decide to SUPER m , when i dont see kitty or any applications popup after SUPER q. But the log is (now as user):
`
[LOG] Instance Signature: cba1ade848feac44b2eda677503900639581c3f4_1715707738_998203348
[LOG] Runtime directory: /run/user/1000/hypr/cba1ade848feac44b2eda677503900639581c3f4_1715707738_998203348
[LOG] Hyprland PID: 1178
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: host
[LOG] Release: 6.8.9-hardened1-2-hardened
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:04 +0000


[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller [8086:2a42] (rev 07) (prog-if 00 [VGA controller])
	DeviceName: VGA compatible controller


[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: With the lights out, it's less dangerous


[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the ProtocolManager!
[LOG] [TearingControl] Registered global
[LOG] [FractionalScale] Registered global
[LOG] [XDGOutput] Registered global
[LOG] [CursorShape] Registered global
[LOG] [IdleInhibit] Registered global
[LOG] [RelativePointer] Registered global
[LOG] [XDGDecoration] Registered global
[LOG] [AlphaModifier] Registered global
[LOG] [GammaControl] Registered global
[LOG] [ForeignToplevel] Registered global
[LOG] [PointerGestures] Registered global
[LOG] [ForeignToplevelWlr] Registered global
[LOG] [ShortcutsInhibit] Registered global
[LOG] [TextInputV3] Registered global
[LOG] [PointerConstraints] Registered global
[LOG] [OutputPower] Registered global
[LOG] [XDGActivation] Registered global
[LOG] [IdleNotify] Registered global
[LOG] [SessionLock] Registered global
[LOG] [IMEv2] Registered global
[LOG] [VirtualKeyboard] Registered global
[LOG] [VirtualPointer] Registered global
[LOG] [OutputManagement] Registered global
[LOG] ToplevelExportManager started successfully!
[LOG] TextInputV1Manager started successfully!
[LOG] GlobalShortcutsManager started successfully!
[LOG] ScreencopyProtocolManager started successfully!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 54.27µs. Estimated average calc time: 0.08µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 34.62µs. Estimated average calc time: 0.06µs.
[LOG] Using config: /home/tokyo/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
`
What is weird to me is that on every other machine when I do Hyprland and then SUPER q it opens terminal. but not on this monitor so i SUPER m to exit.
Maybe my monitor doesnt work with the default monitor settings?

**Comment by vaxerski** [comment]
> debug {disable_logs=false}

it should be 
```
debug {
   disable_logs=false
}
```

plus, the crash report is still missing (I assume it's a crash)

**Comment by notsungod** [comment]
> > debug {disable_logs=false}
> 
> it should be
> 
> ```
> debug {
>    disable_logs=false
> }
> ```
> 
> plus, the crash report is still missing (I assume it's a crash)

It is not a crash im getting back to tty with Super m.

**Comment by notsungod** [comment]
The firstly mentioned error only appears when i press super q to open kitty
