### ISSUE TITLE
Flashing White/Static Bars Depending on Monitor Config

### ISSUE THREAD

**Issue by deronparker** [hyprwm/Hyprland#6063]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: tower
Release: 6.8.9-artix1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 08 May 2024 17:34:57 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7700S/7600/7600S/7600M XT/PRO W7600] [1002:7480] (rev cf) (prog-if 00 [VGA controller])
18:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Sometimes I use 2/3 monitors for my Hyprland machine and change the input for the other monitor to use with another machine.

triple-monitor config:
```console
monitor=HDMI-A-1,1920x1080@60,-1080x0,1,transform,1 # left 1080 vertical
monitor=DP-3,3840x2160@59.99700,0x0,1 # left 4k
monitor=DP-2,3840x2160@59.99700,3840x0,1 # right 4k
```

dual-monitor config:
```console
monitor=HDMI-A-1,1920x1080@60,-1080x0,1,transform,1 # left 1080 vertical
monitor=DP-3,3840x2160@59.99700,0x0,1 # left 4k
monitor=DP-2,disable # right 4k
```

When I switch to the dual config, I get these white/static flashes on my vertical 1080 monitor (HDMI-A-1).

When everything is idling, the issue is rare. When I am actively using the machine or playing a video, the bars are frequent.

### How to reproduce

The repro could be broader than this.

1. Use my dual-monitor config with the relevant monitors.

### Crash reports, logs, images, videos

I currently don't have time to repro with debug logging on. I may be able to later.

https://github.com/hyprwm/Hyprland/assets/24536673/a227f339-2f34-48c2-9803-95fde0563f83

**Comment by vaxerski** [comment]
yikes, looks like a driver bug

**Comment by deronparker** [comment]
Now that I think about it. I believe I remember a similar but less common issue when I would play video in XFCE -- and it was on a different monitor. So yeah, maybe a GPU driver problem. I might be able to try sway Thursday or Friday.

**Comment by The-Briel-Deal** [comment]
This smells like the hdmi forum to me. I've had this happen on my second dell vertical monitor I got from work. It only happens with hdmi and it only happens on my vertical monitor. A cablematters displayport to hdmi 2.1 adapter fixed these issues for me.

I have a 6900xt so its a different card generation but they both have the same issues with hdmi 2.1 for some reason. Also it only seemed to happen when going above hdmi 2.0 speeds so dropping from 10 bit color to 8 bit color should hopefully help if you have 10 bit enabled?

**Comment by deronparker** [comment]
I don't believe I have 10-bit on since my monitors don't have `,bitdepth,10` - [src](https://wiki.hyprland.org/Configuring/Monitors/#10-bit-support). Is there somewhere else I should check? @The-Briel-Deal

**Comment by The-Briel-Deal** [comment]
Explicitly set 8 bit, I believe 10 is default in a lot of cases without it. I think hyprctl monitors might show?

**Comment by deronparker** [comment]
With `,bitdepth,8` the problem persisted, unfortunately. I don't think this is a Hyprland issue, though. So, I'll close this indefinitely or until someone with the same issue comments. 

Thanks for the troubleshooting @The-Briel-Deal

**Comment by The-Briel-Deal** [comment]
Ty! Sorry I couldn't be of more help! Lmk if you figure out how to repro.

**Comment by deronparker** [comment]
> This smells like the hdmi forum to me. - [comment](https://github.com/hyprwm/Hyprland/issues/6063#issuecomment-2113977026) - @The-Briel-Deal 

Just wanted to add some info to avoid future goose chases.

I have switched the affected monitor from vertical to horizontal, and it is now using a DisplayPort connection to the GPU.

With the following configs
```
monitor=$left1080,1920x1080@60,-1920x540,1
monitor=$left4k,3840x2160@59.99700,0x0,1
monitor=$right4k,3840x2160@59.99700,3840x0,1
monitor=$right1080,1920x1080@60,7680x540,1
```
```
monitor=$left1080,1920x1080@60,-1920x540,1
monitor=$left4k,disabled
monitor=$right4k,3840x2160@59.99700,0x0,1
monitor=$right1080,1920x1080@60,3840x540,1
```
```
monitor=$left1080,1920x1080@60,-1920x540,1
monitor=$left4k,3840x2160@59.99700,0x0,1
monitor=$right4k,3840x2160@59.99700,3840x0,1
monitor=$right1080,disabled
```

I have no issues. However, with this config

```
monitor=$left1080,1920x1080@60,-1920x540,1
monitor=$left4k,3840x2160@59.99700,0x0,1
monitor=$right4k,disabled
monitor=$right1080,disabled
``` 

The white bars/static return. So, it seems it is not an HDMI issue and has something to do with the combination of these two monitors -- the same monitors in the original post.

<details> <summary>extra info / video</summary>

https://github.com/user-attachments/assets/19127875-e7c6-4e09-a55f-d5acb6a428bb

```
$left1080 = DP-1
$left4k = DP-3
$right1080 = HDMI-A-1
$right4k = DP-2
```

</details>

**Comment by bechampion** [comment]
I have a very similar issue with an amd 7600 , i didn't have the issue with 4600 or some old board ,  so it's def gpu/driver related
