### ISSUE TITLE
Build failure on Arch with hyprland-git.

### ISSUE THREAD

**Issue by mothsarecool524** [hyprwm/Hyprland#6067]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
(none, trying to move to hyprland-git via AUR)
</details>

### Bug or Regression?

Bug

### Description

Used `yay` to try and install `hyprland-git` to use `hyprpm`, but this is what I got instead (last few lines of the output)

mv: cannot stat '/home/admin/.cache/yay/hyprland-git/pkg/hyprland-git/usr/include/wlr': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: hyprland-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-git - exit status 4

### How to reproduce

Attempt to install `hyprland-git` via AUR.

**Comment by mothsarecool524** [comment]
I `cd`'d into the path and made the `wlr` directory myself, but still got the error whenever I tried to install.

**Comment by zakk4223** [comment]
Build directly from the PKGBUILD and delete lines 130-131 before you run makepkg

**Comment by vaxerski** [comment]
I do not maintain the aur pkgs, ask maintainers to fix it

**Comment by mothsarecool524** [comment]
> I do not maintain the aur pkgs, ask maintainers to fix it

Ok.
