### ISSUE TITLE
Can't change back to workspace after moving a window to another workspace.

### ISSUE THREAD

**Issue by nsavch** [hyprwm/Hyprland#607]
most likely introduced in this commit: https://github.com/hyprwm/Hyprland/commit/dacaf72e02b8d1819135f6aef3911e8211e98630

Steps to reproduce:

1. open two windows on a workspace (say, workspace 1)
2. move one of the windows to another workspace (workspace 2)
3. We are now switched to workspace 2.
4. Press keybind to switch to workspace 1. It doesn't work - you switch to workspace 1 and immediately get switched back to workspace 2.
5. Close the window you moved to workspace 2. You can now switch to workspace 1 as usual.
![workspace-issue](https://user-images.githubusercontent.com/44579/187884112-95d3887b-6495-4737-a000-d266ca5d715e.gif)

**Comment by vars1ty** [comment]
Was just about to report this; same issue here.

**Comment by vaxerski** [comment]
trolled

**Comment by vaxerski** [comment]
fixed in bb90ff04610023457633cf76454a39727395b3a9
