### ISSUE TITLE
wayland and xwayland clipboards are no longer in sync

### ISSUE THREAD

**Issue by MoetaYuko** [hyprwm/Hyprland#6071]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

wayland and xwayland clipboards are no longer in sync, the last good commit is https://github.com/hyprwm/Hyprland/commit/4cdddcfe466cb21db81af0ac39e51cc15f574da9

the synchronization was handled by wlroots, but Hyprland appears to be moving to custom impl since https://github.com/hyprwm/Hyprland/commit/121d3a72137d4780602cf245704615f63357ea22

### How to reproduce

copy from wayland app, paste it into xwayland app, and vice versa.

**Comment by sungyoonc** [comment]
It's a known issue and wiil be fixed when the wlr_xwayland rewrite is done
See https://github.com/hyprwm/Hyprland/pull/5999

**Comment by MoetaYuko** [comment]
> It's a known issue and wiil be fixed when the wlr_xwayland rewrite is done See #5999

oh alright
