### ISSUE TITLE
allow to set a global font, and render with pango only

### ISSUE THREAD

**Issue by rtgiskard** [hyprwm/Hyprland#6073]
### Description

Better to provide a global `font-family` settings, for overlay, splash and the others, instead of the hard coded `sans`. There are settings to select font for groupbar and splash, another one for the overlay might need to be add.

And, I'm using a local font config like this:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<match target="pattern">
		<test name="family" qual="any"><string>sans-serif</string></test>
		<edit name="family" mode="prepend" binding="strong">
			<string>Symbols Nerd Font</string>
			<string>Inconsolata</string>
			<string>LXGW WenKai Mono</string>
		</edit>
	</match>
</fontconfig>
```

The symbol only nerd font is the first to match, and then the others as fallback, this works well for my other applications, without the need to install many other nerd patched fonts.

However, hyprland is using `cairo_select_font_face()` along with `pango_layout_set_font_description()` to render the fonts, the first one from `cairo` doesn't support such font glyphs fallback, and `pango` does, so for my case, the overlay message is all blocks.

It might be better to render only with `pango` for the project, rather than using both.

If you're willing, I may make the changes and create a PR later

**Comment by vaxerski** [comment]
feel free to mr, always welcome
