### ISSUE TITLE
Crash on resume

### ISSUE THREAD

**Issue by vod3** [hyprwm/Hyprland#6075]
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: arch-laptop
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```
</details>

### Bug or Regression?

Bug

### Description

After resuming my laptop over night, sometimes I can see my hyprlock screen for a second, then Hyperland instantly crashes and I'm back on SDDM.

Using an integrated Intel GPU, more sys infos in the crash report.

### How to reproduce

- Close the laptop lid to go to sleep
- Resume after several hours

### Crash reports, logs, images, videos

[hyprlandCrashReport120502.txt](https://github.com/hyprwm/Hyprland/files/15317053/hyprlandCrashReport120502.txt)

**Comment by vaxerski** [comment]
#5565 or the 10 other issue reports
