### ISSUE TITLE
Crash when moving tab in chromium

### ISSUE THREAD

**Issue by A31Nesta** [hyprwm/Hyprland#6076]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 94c20a186372aace78b188842848b873eb3ebbd7  (primary-selection: move to hyprland impl).
Date: Wed May 15 00:13:35 2024
Tag: v0.40.0-87-g94c20a18, commits: 4693

flags: (if any)


System Information:
System name: Linux
Node name: a31msi
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.03.26"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Today I updated hyprland-git from the AUR (EndeavourOS). I use brave as my browser and I found out that moving a tab crashes hyprland. Just clicking a tab and moving the mouse causes hyprland to crash.

### How to reproduce

- Compile latest hyprland
- Open browser (chromium with ozone platform as Wayland)
- Click on the tab title on top and try to move it
- Enjoy your SDDM theme

### Crash reports, logs, images, videos

Log:
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15317840/hyprland.log)

Crash report:
[hyprlandCrashReport28059.txt](https://github.com/hyprwm/Hyprland/files/15317878/hyprlandCrashReport28059.txt)

**Comment by mauricekraus** [comment]
I also experienced that, also closing a "chrome" tab crashes hyprland.

**Comment by vaxerski** [comment]
fixd
