### ISSUE TITLE
waybar's taskbar module, xwayland app's icon uses the default icon

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6085]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4cdddcfe466cb21db81af0ac39e51cc15f574da9  (cursor: minor fixes for unhiding surfaces).
Date: Tue May 14 23:45:12 2024
Tag: v0.40.0-80-g4cdddcfe, commits: 4686

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.9.0-1-cachyos-echo-lto
Version: #1 SMP PREEMPT_DYNAMIC Mon, 13 May 2024 20:33:26 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Use the latest commit, the xwayland app icon uses the default icon.

### How to reproduce

above

### Crash reports, logs, images, videos

Default icon 
![image](https://github.com/hyprwm/Hyprland/assets/39702328/6efae6bf-cd23-4387-bf0f-874444f0d0a3)

**Comment by hdm9527** [comment]
And the crash issue.
[hyprlandCrashReport969.txt](https://github.com/hyprwm/Hyprland/files/15323170/hyprlandCrashReport969.txt)

**Comment by vaxerski** [comment]
looks like a driver bug

**Comment by vaxerski** [comment]
can you bisect the icon issue?

**Comment by hdm9527** [comment]
Use the default icon because this commit 0cfdde3d1acbfbf698af17f6986fbc4d644214da
Hyprland crashes aren't very frequent, it's not clear which commit is causing it.
