### ISSUE TITLE
exec, [float] $terminal not working as expected

### ISSUE THREAD

**Issue by urioTV** [hyprwm/Hyprland#6087]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 3fe5280ce93a7c216f47e8626e69ea015e875395  ().
Date: 2024-05-15
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: konrad-m18
Release: 6.9.0-cachyos
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun May 12 21:12:29 UTC 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev cf) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240512.2057814"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

After update setting floating on exec stopped working.

### How to reproduce

use
bind = $mainMod SHIFT, E, exec, [float] $terminal

after mod + SHIFT + E terminal spawn normally, not floating.

**Comment by vaxerski** [comment]
> After update setting floating on exec stopped working.

select regression next time then and provide a git bisect https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue

**Comment by The-Briel-Deal** [comment]
Can you drop your full config? I use this config to launch pulsemixer floating in the bottom right and it works for me. Does this not work for you?

Guessing its an edge case or something. Definitely isn't completely broken.

```
windowrulev2 = float,class:^(pulsemixer)$
windowrulev2 = size 700 400,class:^(pulsemixer)$
windowrulev2 = move 100%-800 100%-500,class:^(pulsemixer)$
windowrulev2 = opacity 0.9,class:^(pulsemixer)$

bind = $mainMod, A, exec, kitty --class=pulsemixer sh -c 'pulsemixer' 
```

**Comment by The-Briel-Deal** [comment]
```
bind = $mainMod SHIFT, E, exec, [float] $terminal
```

Also i've never seen this syntax before and I don't see it in the wiki on the binds page? Is the [float] before $terminal valid? Is that not what is actually in your config?

**Comment by urioTV** [comment]
Windowrules are working. But I want to have different shortcuts for normal terminal and a floating one. I used this syntax before and it worked. You can set different things with it like size. For example [float; size 100 100] 

https://github.com/urioTV/nix-flake-config/blob/master/dotfiles%2Fhypr%2Fhyprland.conf

You can see my config on my repo

**Comment by urioTV** [comment]
Seems fixed now
