### ISSUE TITLE
Touchpad scrolling causing issues

### ISSUE THREAD

**Issue by Agent00Ming** [hyprwm/Hyprland#6090]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit b9c58b6e75f7d0141d8ba88fb3f6f022fed0877a  (seat: send enter/leave events to all bound wl_seats for a client).
Date: Wed May 15 14:33:42 2024
Tag: v0.40.0-92-gb9c58b6e, commits: 4698

flags: (if any)


```

</details>

### Bug or Regression?

Regression

### Description

Touchpad scrolling stops working after switching tabs in Firefox. Touchpad scrolling in Kate and pcmanfm-qt only works for one of the contexts in split view.

### How to reproduce

__Firefox__
1. Open two tabs in Firefox, with one having a page long enough to scroll in
2. Switch between said tabs
3. Attempt to scroll in the previously scrollable page using a touchpad
4. Observe that it does not scroll

__Kate/pcmanfm-qt__
1. Open a file/folder with enough content to scroll
2. Open split view mode (Ctrl+Shift+L for Kate, F6 for pcmanfm-qt)
3. Attempt to scroll using the mouse wheel in both split contexts (it should work as expected)
4. Attempt to scroll using a touchpad in both split contexts
5. Observe that it only scrolls within the last context that was scrollable. Mouse wheel scrolling is also limited to that context from that point forward.

### Crash reports, logs, images, videos

[firefox_wl_debug.log](https://github.com/hyprwm/Hyprland/files/15325738/scroll_bug.log)

**Comment by vaxerski** [comment]
can you check the wl log on sway and see if theres anything oddly different?

**Comment by ehula** [comment]
I was having this same issue in every app yesterday. Scrolling using the touchpad didn't work anywhere. I guess there were some fixes overnight. Today, scrolling using the touchpad works everywhere except qutebrowser for me.

**Comment by Agent00Ming** [comment]
One stark contrast is that on sway `wl_pointer.set_cursor` is regularly called whereas on hyprland it simply stops being called 1/3 of the way into the log and does not get called a single time afterwards.
[sway_firefox_wl_debug.log](https://github.com/hyprwm/Hyprland/files/15326701/sway_firefox_wl_debug.log)

**Comment by ArtemChandragupta** [comment]
I have similar issues since yesterday. Zathura pdf viewer is also touched by this

**Comment by Agent00Ming** [comment]
Hyprland doesn't send `wl_pointer.axis_stop` events?

**Comment by ArtemChandragupta** [comment]
I don't know how to check that. There is no crash to see the log, and logs then i launch something in terminal does not show this

**Comment by Agent00Ming** [comment]
> I don't know how to check that. There is no crash to see the log, and logs then i launch something in terminal does not show this

get a log from you scrolling and breaking the scrolling in a wayland application by running it with `WAYLAND_DEBUG=1 $APPLICATION > application_scroll.log 2>&1` and attach it here

**Comment by Agent00Ming** [comment]
Seems like the scrolling gets stuck in a state where it thinks that the scrolling hasn't ended because no `axis_stop` events are logged for non-discrete scrolling events. It, therefore, attempts to scroll on the last scrollable context whether that context is gone or not and we experience the scrolling not working anymore..?

**Comment by ArtemChandragupta** [comment]
[application_scroll.log](https://github.com/hyprwm/Hyprland/files/15327369/application_scroll.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15327414/patch.txt)
this should fix it then

**Comment by Agent00Ming** [comment]
correct, it does indeed fix it

**Comment by vaxerski** [comment]
thanks a lot for finding the issue! Saved me a lot of time debugging that I spent writing the xwayland garbage instead :)
