### ISSUE TITLE
exec-once window rules ignored but still launched

### ISSUE THREAD

**Issue by shogeki** [hyprwm/Hyprland#6091]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
yprland, built from branch main at commit b9c58b6e75f7d0141d8ba88fb3f6f022fed0877a  (seat: send enter/leave events to all bound wl_seats for a client).
Date: Wed May 15 11:33:42 2024
Tag: v0.40.0-92-gb9c58b6e, commits: 4698

flags: (if any)


System Information:
System name: Linux
Node name:
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev cc) (prog-if 00 [VGA controller])
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c8) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Previously I was running Arch package version of v0.40, but I upgraded to the git version.  This caused all my exec-once commands to ignore workspace rules:

e.g. of rule
``` 
exec-once=[workspace 1 silent] alacritty
exec-once=[workspace 2 silent] librewolf
exec-once=[workspace 3 silent] thunar
```

### How to reproduce

On the arch packaged version of v0.40, launching with these rules result in my windows opening in the specified workspaces.  When using the AUR -git package and the manually compiled git version, these rules are ignored and everything is executed but dumped into Workspace 1.

Version details are from the git version I installed.  I have since revered to the Arch package v0.40 and confirmed it's working as intended again.

**Comment by frkli1965** [comment]
Although not being ignored per se, all my auto-start apps are being loaded into the default workspace assigned to the current monitor, instead of their allotted work spaces.

For instance the following:-

exec-once = [workspace 2 silent] firefox-developer-edition

results in FF being loaded into workspace 3 as that's the default for the current monitor (DP-1) i.e.

workspace = 3, monitor:DP-1, default:true

**Comment by BenCarmichael01** [comment]
yeh same here. I have `exec-once = hyprctl dispatch exec [ workspace special:fm silent ] kitty yazi` and kitty just opens on workspace 1 on launch.

**Comment by shogeki** [comment]
first broken in https://github.com/hyprwm/Hyprland/commit/121d3a72137d4780602cf245704615f63357ea22
