### ISSUE TITLE
SdDaemon.cpp: error: strnlen was not declared in this scope

### ISSUE THREAD

**Issue by cmyster** [hyprwm/Hyprland#6094]
### Hyprland Version

0.40.0

### Bug or Regression?

Bug

### Description

./hyprland-source/src/helpers/SdDaemon.cpp:40:38: error: 'strnlen' was not declared in this scope; did you mean 'strlen'?
   40 |         size_t             addrLen = strnlen(addr, 107);
      |                                      ^~~~~~~

### How to reproduce

all the information is in https://bugs.gentoo.org/931954

### Crash reports, logs, images, videos

all the information is in https://bugs.gentoo.org/931954

**Comment by vaxerski** [comment]
this should fix it then.
