### ISSUE TITLE
Latest Git Release Causes Bug with launching and Scroll Wheel

### ISSUE THREAD

**Issue by NEUKhoaLe** [hyprwm/Hyprland#6096]
### Hyprland Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch main at commit de9798fcf9494eb082bd168175390c0d47b8478b  (configmgr: shadow exec rules when window is unmapped).
Date: Wed May 15 19:55:55 2024
Tag: v0.40.0-96-gde9798fc, commits: 4702

flags: (if any)

System Information:
System name: Linux
Node name: khoa-arch
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
0b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] [10de:1e81] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

</details>

### Bug or Regression?

Regression

### Description

After updating to the latest Git release, there are some weird bugs in Blender (Wayland).

When launching the application, the application will not tile, but will go on top of current windows. 
Within Blender, scroll wheel rotates the camera view, instead of the default functionality of zooming in and out.

### How to reproduce

Install the latest Git Release. 

Launch Blender and scroll within the Viewport.

**Comment by Agent00Ming** [comment]
not flagging scroll wheel as discrete axis event causes this issue because blender then treats it as it would touchpad 'scroll' gesture

**Comment by vaxerski** [comment]
interesting, alright. I'll make a patch tomorrow if I don't forget (if you wanna do it feel free to MR)

**Comment by NEUKhoaLe** [comment]
Thank you Varxy, Agent00Ming, let me know so I can test

**Comment by The-Briel-Deal** [comment]
Haven't spent anytime going deep into this but this is definitely the case for me. When I rebuilt from source sometime today my mouse felt faster and my scroll was at least 2-3x slower in kitty. For some reason In Firefox it feels the same? Can't really explain this. Guessing this got through because it doesn't seem to affect nested sessions?

**Comment by Agent00Ming** [comment]
Well after sending the discrete events, it seems to multiply scrolling factor by a large amount. Why is the default discrete scroll ±120? (on sway it's ±1 lol)

**Comment by vaxerski** [comment]
likely forgot to /120

**Comment by Agent00Ming** [comment]
> For some reason In Firefox it feels the same?

Afaik, Firefox ignores the discrete scrolling value, it uses an internal value set in `about:config` `mousewheel.min_line_scroll_amount`
