### ISSUE TITLE
Add Config to systeminfo or bug reports.

### ISSUE THREAD

**Issue by The-Briel-Deal** [hyprwm/Hyprland#6098]
### Description

I've ran into a bunch of bug reports recently that would have been a lot easier to repro if their config was in the bug report. I'm fine to add a config dump at the top of systeminfo so that its included when people include `hyprctl systeminfo` in their report. Another option is just adding a field for config in bug reports.

I feel like people don't really include personal info in configs but we can definitely warn people to take their social security number out of their config before submitting lol.

Thoughts on adding this? Is there a reason it hasn't been added?

**Comment by rtgiskard** [comment]
Or maybe an independent sub command like `configdump`, and require it on bug report

**Comment by vaxerski** [comment]
fair enough

> Is there a reason it hasn't been added?

yes, never thought of this and was bothered enough

**Comment by The-Briel-Deal** [comment]
> Or maybe an independent sub command like `configdump`, and require it on bug report

I kind of just want it to be as simple as possible for the reporter to get this in one command, I'm kind of thinking either a debuginfo hyprctl command that contains everything we might need or just add a --config, --logs, and --all flag to systeminfo. Pretty sure there is a hyprctl command already to log config. I'll make a quick PR and you guys can give me your thoughts.

**Comment by vaxerski** [comment]
flags make sure

**Comment by The-Briel-Deal** [comment]
Addressed here: https://github.com/hyprwm/Hyprland/pull/6160

I updated the bug template and added a -c/--config flag.
