### ISSUE TITLE
GUI toolkits not being notified of scaling changes

### ISSUE THREAD

**Issue by nergdron** [hyprwm/Hyprland#610]
Steps to reproduce:
* set a fractional scaling method on a monitor, such as `1.3`, after apps are already running.

Expected outcome:
* toolkits such as QT and GTK re-render at the new scaling value, producing crisp, clear output.

Noted outcome:
* on screen items are just upscaled using video card filtering to the fractional amount, producing blurry, hard to read content.
* if apps are restarted, GTK apps at least pick up the new scaling and render correctly.
* electron apps like discord and vscodium don't seem to pick this up, even on restart, and stay ugly and blurry forever.
* QT apps like Krita also don't pick up the new scaling, and stay blurry.
* even if the scaling is set in the hyprland config and applied at login, the above problem apps stay blurry.

**Comment by nergdron** [comment]
AHA! it looks like hyprland isn't to blame for the rendering, it's toolkits not getting the new scaling factor when you change it. if I restart GTK apps, they correctly render at the right scaling factor. third party stuff like discord is still busted and ugly after changing scaling, which is weird because it doesn't have issues like that under gnome-desktop, but at least it looks like most of the pain just comes from switching things after apps are already running.

it's possible that hyprland needs to do something like what `gnome-shell` does to notify all the various toolkits and apps of a scaling change, I'm not really sure how that end of things all bolts together. :woman_shrugging:

**Comment by nergdron** [comment]
strangely, telegram is electron, but it scales correctly. no idea why it does but discord and vscodium don't.

**Comment by nergdron** [comment]
and it looks like only newer GTK stuff gets the new scaling correctly, older stuff just stays blurry as well.

**Comment by fufexan** [comment]
> electron apps like discord and vscodium don't seem to pick this up, even on restart, and stay ugly and blurry forever.

are you positive they're being run in XDG mode as opposed to XWayland? For me they look perfectly fine in XDG mode, with 1.6 scaling.

**Comment by vaxerski** [comment]
XWayland scaling. https://wiki.hyprland.org/Configuring/XWayland/
