### ISSUE TITLE
Doesn't autofocus on apps launched using workspace rules

### ISSUE THREAD

**Issue by mohammedbilalns** [hyprwm/Hyprland#6100]
### Hyprland Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)

System Information:
System name: Linux
Node name: mohammed-20ve
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2024.01.25"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:

</details>

### Bug or Regression?

Bug

### Description

I have some workspace rules to autolaunch apps when created empty. After a recent update, the launched apps don't autofocus as they did previously.

### How to reproduce

1. add workspace rule like "workspace = 5, on-created-empty: firefox"
2. Switch to the  defined workspace

**Comment by vaxerski** [comment]
try on git, iirc fixed

**Comment by PickNicko13** [comment]
Just checked on d693c44 and it's still the case

**Comment by mohammedbilalns** [comment]
still exists in the Git version

**Comment by Agent00Ming** [comment]
https://github.com/hyprwm/Hyprland/issues/6038#issuecomment-2106261311
