### ISSUE TITLE
Crash when toggling group off

### ISSUE THREAD

**Issue by PickNicko13** [hyprwm/Hyprland#6101]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: t3600
Release: 6.7.0.6.realtime1-3-rt
Version: #1 SMP PREEMPT_RT Tue, 07 May 2024 22:06:13 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev cf) (prog-if 00 [VGA controller])


os-release: NAME="Archcraft"
PRETTY_NAME="Archcraft"
ID=archcraft
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archcraft.io"
DOCUMENTATION_URL="https://wiki.archcraft.io"
SUPPORT_URL="https://www.reddit.com/r/archcraft"
BUG_REPORT_URL="https://github.com/archcraft-os/archcraft/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archcraft


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When there is only one tile and it is a group tile with multiple windows, toggling the group off causes hyprland to crash.
Same doesn't happen for a floating group.
It only happens with no_gaps_when_only turned ON.

The following line in the log looks suspicious:

> [LOG] OPENINGON: [Node **_nullptr_**], Monitor: 1

### How to reproduce

Have no_gaps_when_only turned on.
Open a blank workspace, open 2 or more windows and make them a single group. Upon toggling the group off hyprland will reliably crash.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15332091/hyprland.log)
[hyprlandCrashReport26374.txt](https://github.com/hyprwm/Hyprland/files/15332403/hyprlandCrashReport26374.txt)

Edit: added crash report.

**Comment by sungyoonc** [comment]
https://github.com/hyprwm/Hyprland/issues/5909 ?

**Comment by PickNicko13** [comment]
Sorry, I totally forgot to check closed issues in case it was already fixed in the upstream. I'll build it and test the issue this evening, but it looks like that's exactly what's happening here. Well, except for the tiny difference that #5909 specifies dwindle layout, while I can reproduce crashes in both dwindle and master-and-stack, but the fix looks universal.
