### ISSUE TITLE
Can't build Hyprland on Arch

### ISSUE THREAD

**Issue by ArchVisions** [hyprwm/Hyprland#6107]
### Hyprland Version

Can't because it is a build.

### Bug or Regression?

Bug

### Description

I tried to build Hyprland using the AUR package, but the build fails.
The main repository package in Extra works just fine.

### How to reproduce

1. Run yay -S hyprland-git
2. Enter A for clean build and for diffs to show.
3. Let the build run.

### Crash reports, logs, images, videos

[9rBVGs04.txt](https://github.com/hyprwm/Hyprland/files/15338783/9rBVGs04.txt)

**Comment by shogeki** [comment]
install hyprwayland-scanner-git from AUR

**Comment by ArchVisions** [comment]
> install hyprwayland-scanner-git from AUR

Thanks that worked!
