### ISSUE TITLE
Some Apps Open up in Fullscreen, Ignoring Window Rules

### ISSUE THREAD

**Issue by NEUKhoaLe** [hyprwm/Hyprland#6108]
### Hyprland Version

<details> <summary>System/Version info</summary>

Hyprland, built from branch main at commit 3ac0e7ead1434c172f276a12f81da1eeb0dc4491  (seat: Send discrete event when axis source is scroll wheel (6103)).
Date: Thu May 16 08:30:55 2024
Tag: v0.40.0-99-g3ac0e7ea, commits: 4705

flags: (if any)

System Information:
System name: Linux
Node name: khoa-arch
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
0b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] [10de:1e81] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

</details>

### Bug or Regression?

Regression

### Description

After Git bisecting and finding Commit: 94c20a186372aace78b188842848b873eb3ebbd7 , `primary-selection: move to hyprland impl`

Certain apps such as Blender opens in fullscreen. This is the case even if there are window rules preventing the app from opening in fullscreen.

```
windowrulev2 = tile,class:^(blender)$
windowrulev2 = suppressevent fullscreen, class:^(blender)$
```

### How to reproduce

Go to any commit after 94c20a186372aace78b188842848b873eb3ebbd7, and open blender.

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/commit/94c20a186372aace78b188842848b873eb3ebbd7 is the _regressor_ or _last working commit_?

**Comment by NEUKhoaLe** [comment]
> https://github.com/hyprwm/Hyprland/commit/94c20a186372aace78b188842848b873eb3ebbd7 is the _regressor_ or _last working commit_?

That's the first bad Commit, so regressor.

**Comment by simonoscr** [comment]
yes, same for me. When checking with `hyprctl clients` some windows have empty  `class:`  since this commit.

So many of my windowrules no longer find a matching window.

**Comment by khaneliman** [comment]
> yes, same for me. When checking with `hyprctl clients` some windows have empty `class:` since this commit.
> 
> So many of my windowrules no longer find a matching window.

In another bug, I think it appeared that only XWayland apps were missing class. Is blender xwayland?

**Comment by NEUKhoaLe** [comment]
Blender is Wayland. For some reason it is opened in fullscreen forced, even though I have it set in window rules.

**Comment by vaxerski** [comment]
check now, should be fixed

**Comment by NEUKhoaLe** [comment]
Can confirm its fixed. Thank you
