### ISSUE TITLE
Toggle ON special workspace switch the current workspace

### ISSUE THREAD

**Issue by thongpv87** [hyprwm/Hyprland#611]
All bug reports should have the following:

- Steps to reproduce
  - Open terminal on workspace 1, firefox on workspace 2
  - Open another firefox on workspace 2, then move that window to special workspace
  - On the firefox page on workspace 2, open a random url in a new tab. Then drag it to make the tab running on separate firefox window (on ws2). Move that window to special workspace and then drag the tab to current firefox instance that running on special workspace that we created on step 2. This merges two firefox windows on special workspace into one.
  - Toggle off special workspace,  set active workspace to workspace 1, then toggle on special workspace
- Expected outcome
  - Special workspace display on workspace 1
- Noted outcome
  - Special workspace displayed, but active workspace is set to workspace 2

NOTE:
- If I drag the tab on step 3 in the firefox window running on special workspace to a separate window and move it back to the original firefox window in workspace 2, Hyprland will work as expected

**Comment by vaxerski** [comment]
Can't reproduce. Are you sure you're on the latest?

**Comment by thongpv87** [comment]
I'm using the version on nixpkgs unstable branch, the repo was updated yesterday

**Comment by fufexan** [comment]
you don't mean [this version](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=hyprland), right? because that would be a joke.

**Comment by thongpv87** [comment]
I've just tried that again but can't reproduce. So I think separate the tab and merge it to other window may not be the reason.

**Comment by thongpv87** [comment]
> you don't mean [this version](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=hyprland), right? because that would be a joke.

Sorry. I added it using flake method and forgot where the package come from. Actually, I'm using this commit: https://github.com/hyprwm/Hyprland/commit/f77fac9df9c6619fe70f2b951a623095ed9d753a

**Comment by vaxerski** [comment]
welp then thats old? It should've been fixed in bb90ff04610023457633cf76454a39727395b3a9

**Comment by fufexan** [comment]
Well that's 2 days old. You should update.

**Comment by thongpv87** [comment]
> welp then thats old? It should've been fixed in [bb90ff0](https://github.com/hyprwm/Hyprland/commit/bb90ff04610023457633cf76454a39727395b3a9)

That's great, thanks. Let me update and see if the problem is gone. Thank you both for super fast response :)
