### ISSUE TITLE
Screen going black on notification

### ISSUE THREAD

**Issue by Hokkaydo** [hyprwm/Hyprland#6110]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details> 

### Bug or Regression?

Regression

### Description

Recently, I noticed that when I receive a notification from an application opened on another workspace than the one I'm working on, the screen goes black for a second and then come back.
It reminds me of how it does when the computer is connected to an external monitor.

I use notify-send as my notification sender.

### How to reproduce

No clue

**Comment by vaxerski** [comment]
is this a regression?

**Comment by Hokkaydo** [comment]
> is this a regression?

Ew yep sorry, I didn't understand what "regression" means at first

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue then

**Comment by romanstingler** [comment]
you are on arch can you install the latest version? 
or is this already resolved for you?

**Comment by Hokkaydo** [comment]
Hello, looks like it got resolved by itself
