### ISSUE TITLE
Using A Tablet in Blender Crashes Hyprland with certain actions

### ISSUE THREAD

**Issue by NEUKhoaLe** [hyprwm/Hyprland#6116]
### Hyprland Version

<details> <summary>System/Version info</summary>

hyprctl systeminfo
Hyprland, built from branch main at commit a66cfe0fbed7fb4dc69383e107c2bf3b1e7cd80a  (CMake: use add_custom_command for generating protocols (6104)).
Date: Thu May 16 18:34:03 2024
Tag: v0.40.0-103-ga66cfe0f, commits: 4709

flags: (if any)

System Information:
System name: Linux
Node name: khoa-arch
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
0b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] [10de:1e81] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

</details>

### Bug or Regression?

Regression

### Description

Rotating, Scaling when using a tablet in Blender Crashes Hyprland. Weirdly, moving an object doesn't crash blender. 

Release Build does not have this error. Will bisect tomorrow.

Additionally, clicking on the subsurface division modifier's arrow teleports the cursor to the center of the window.

### How to reproduce

1. Go on latest Commit
2. Open Blender
3. Press `R` to rotate an object or `S` to scale an object.
4. Hyprland crashes.

### Crash reports, logs, images, videos

![CleanShot 2024-05-17 at 00 49 54@2x](https://github.com/hyprwm/Hyprland/assets/77949166/c7bb12c0-7da9-4663-b62e-4d80ae5c22cb)

_No response_

**Comment by vaxerski** [comment]
post a crash report

**Comment by Agent00Ming** [comment]
Repro'd with blender (Wayland). Seems to also happen when interacting with every xWayland app as well but that's probably a different issue.
[hyprlandCrashReport879.txt](https://github.com/hyprwm/Hyprland/files/15347768/hyprlandCrashReport879.txt)

**Comment by vaxerski** [comment]
f21b6fe576b1068598d6c19fbbfd3f0659d5498d
