### ISSUE TITLE
Mouse click accuracy

### ISSUE THREAD

**Issue by obivan** [hyprwm/Hyprland#6117]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a66cfe0fbed7fb4dc69383e107c2bf3b1e7cd80a  ().
Date: 2024-05-16
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos-pc
Release: 6.9.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun May 12 21:12:29 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240515.33d1e75"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When selecting text or clicking on links/buttons, the click is registered a few pixels to the right of the actual cursor position. Similar to old issue #4691, this only seems to happen when the cursor shape is changed.

There is also a strange jump to the right when changing the cursor shape (see video).

This happens starting from commit ed411f53bdcf8d455f9e6ca769693aa84dc8372f

I'm using xcursor. Enabling or disabling hardware cursors using the WLR_NO_HARDWARE_CURSORS environment variable and/or the cursor:no_hardware_cursors option has no visible effect whatsoever.

### How to reproduce

Move the cursor to the boundary of the link.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/1916877/5260fa2a-7aa8-4bdb-becf-1769c9f90f2c

https://github.com/hyprwm/Hyprland/assets/1916877/7c3c2c35-6288-47c9-a9f6-6f3da40500d8

**Comment by vaxerski** [comment]
doesn't happen to me so I'll need more info (does it happen if you disable scaling? if you use hyprcursor? if you change the cursor size?)

**Comment by obivan** [comment]
> does it happen if you disable scaling?

Nope, with scaling 1 everything works fine. I normally use scaling 2.

> if you use hyprcursor?

It takes me a while to figure out how to do it right. I guess I'll try converting the theme I'm using to hyprcursor format and set the corresponding environment variables.

> if you change the cursor size?

I've tried two cursor themes (breeze_cursors from KDE and phinger-cursors-light) in two size options: 24 and 32. The issue persists.


Oh, one more thing - it looks like the issue is not reproducible inside XWayland apps.

**Comment by vaxerski** [comment]
likely a math error with xcursor hotspots somewhere then

**Comment by obivan** [comment]
I have checked and can reproduce this with hyprcursor as well.

**Comment by obivan** [comment]
Well, when I change this code (in main)

```cpp
CBox CPointerManager::getCursorBoxLogicalForMonitor(SP<CMonitor> pMonitor) {
    return CBox{pointerPos, currentCursorImage.size / currentCursorImage.scale}.translate(-currentCursorImage.hotspot / currentCursorImage.scale);
}
```

to this one

```cpp
CBox CPointerManager::getCursorBoxGlobal() {
    return CBox{pointerPos, currentCursorImage.size / currentCursorImage.scale}.translate(-currentCursorImage.hotspot);
}
```

it fixes the issue.

I don't know any shit about how valid this is.
But it works

**Comment by vaxerski** [comment]
does it happen if you disable hardware cursors...?

**Comment by obivan** [comment]
I see no change in behavior from enabling/disabling hardware cursors.

I mean, if I apply the nano-patch above, the issue disappears regardless of the kind of cursors used.

**Comment by vaxerski** [comment]
ok then

**Comment by obivan** [comment]
Thank you! In the latest main (553232a3e4c112c8511c8511309e6b685cb614895e714) the issue is still reproducible, but only if hardware cursors are enabled. I don't know why, maybe because of 553232a3e4c112c8511309e6b685cb614895e714, which was not present at the time of initial testing.

**Comment by vaxerski** [comment]
bing chilling

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15448239/patch.txt)
try

**Comment by obivan** [comment]
Nope, still doesn't work with hardware cursors enabled (and works with software cursors on)

**Comment by obivan** [comment]
This change fixes the hardware cursors for me (while not breaking the software cursors). Found it tinkering around your patch.
[patch2.txt](https://github.com/hyprwm/Hyprland/files/15494213/patch2.txt)

**Comment by vaxerski** [comment]
thanks, can you make a MR?

**Comment by obivan** [comment]
Sure. Please take a look.
