### ISSUE TITLE
Plugins in Webassembly

### ISSUE THREAD

**Issue by xMAC94x** [hyprwm/Hyprland#6119]
### Description

I know crashing is fun and stuff, but would you as the developers of Hyprland be opposed to injecting plugins via WASM ?

It could offer many features, security, allow C++ and other languages to compile plugins, and most probably: less bug reports by users who used plugins but clain the plugin is not responsible for a crash ;)

I dont want you to include the whole WASM runtime here, just asking for a general direction if you have a strong opinion about it because someone starts working and investing time into this

**Comment by vaxerski** [comment]
No, defeats the purpose of plugins. If you want to load plugins in another language, make your own plugin to provide such a dumb iface
