### ISSUE TITLE
Popup workspace

### ISSUE THREAD

**Issue by thongpv87** [hyprwm/Hyprland#612]
I love the special workspace which I can popup on any workspace to do some quick task or see if there are any important message. Unfortunately, there is only one special workspace. I think we could generalize the concept to have popup workspace, which works similar to special workspace but we can have as many as we want. So we can have some thing like this:
- Popup ws1 - status monitoring: open some application for monitor status. 
- Popup ws2 - communication: some messaging, email app. 
- Popup ws3 - media: music, news, or videos
- Each popup ws can be assigned to a shortcut, for example: Super+S for status monitoring, Super+M for media, ... 

Some implement considerations:
- User can assign a single kb shortcut to toggle-off any popup workspace.
- Layout, animation config per workspace
- Allow fullscreen? It would be useful for media workspace

**Comment by vaxerski** [comment]
A lot of traction this has gotten. Sorry for the wait!

added in 0a302901d26eff02a83742aa319f20f3b3a0c372, you can now have up to 97 special workspaces at a time.

**Comment by thongpv87** [comment]
Great. Thank you so much for implementing that.
