### ISSUE TITLE
Crashes to sddm when using LM Studio

### ISSUE THREAD

**Issue by keystroke3** [hyprwm/Hyprland#6121]
### Hyprland Version

Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)

System Information:
System name: Linux
Node name: atlas
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT] [1002:747e] (rev c8) (prog-if 00 [VGA controller])
12:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c5) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

When I try to run a conversation in LM Studio, Hyprland crashes to the desktop. It crashed once or twice before, but it has crashed 3 times in a row when trying to execute some prompt.
I am using `TheBloke • mistral instruct v0 2 7B q8_0 gguf ` model. It crashes with other models too, but this is the one I was using before the latest crash.

### How to reproduce

Install LM Studio and `TheBloke • mistral instruct v0 2 7B q8_0 gguf `. use Max gpu off load. Enter a prompt and click on generate. 

### Crash reports, logs, images, videos

[hyprlandCrashReport679401.txt](https://github.com/hyprwm/Hyprland/files/15347800/hyprlandCrashReport679401.txt)
[hyprland.log](https://github.com/hyprwm/Hyprland/files/15347812/hyprland.log)

**Comment by Agent00Ming** [comment]
crash report and log don't match

**Comment by floork** [comment]
I do not have a crash report, but it's also doing the same behavior with brave on arch. When I open it, it either instantly or after a short time freezes and I get sent back to the login (using `ly` as the display manager).

**Comment by keystroke3** [comment]
Oh, let me correct it. I selected the wrong crash report
[hyprlandCrashReport189198.txt](https://github.com/hyprwm/Hyprland/files/15348413/hyprlandCrashReport189198.txt)

**Comment by Agent00Ming** [comment]
```
[CRITICAL] 
==========================================================================================
ASSERTION FAILED! 

Aborting, glGetGraphicsResetStatus returned GL_INNOCENT_CONTEXT_RESET. Cannot continue until proper GPU reset handling is implemented.

at: line 265 in OpenGL.cpp
```
GPU reset, not a hyprland problem

**Comment by keystroke3** [comment]
Thanks, could you point me to some resource I can use to start looking at this? The results on Google are just pointing back to this repo

**Comment by floork** [comment]
Ok i have found the crashreport from me
[hyprlandCrashReport1265.txt](https://github.com/hyprwm/Hyprland/files/15348669/hyprlandCrashReport1265.txt)

**Comment by Agent00Ming** [comment]
> Thanks, could you point me to some resource I can use to start looking at this? The results on Google are just pointing back to this repo

Haven't found much myself but my searching suggest that it's either a driver bug or a rogue app causing the driver to malfunction

**Comment by Agent00Ming** [comment]
> Ok i have found the crashreport from me [hyprlandCrashReport1265.txt](https://github.com/hyprwm/Hyprland/files/15348669/hyprlandCrashReport1265.txt)

Can't repro with stock brave on arch. Consider opening a different issue.

**Comment by floork** [comment]
Ok seems like my last build was broken somehow, after rebuild its now working again

**Comment by keystroke3** [comment]
I will close this as I try and find a solution to my situation

**Comment by Sasikuttan2163** [comment]
Did you find anything? I'm having the same problem right now and it's not tied to any specific app

**Comment by keystroke3** [comment]
Sadly no. It happens a lot when I try to enable ray tracing, but does not happen when I am on KDE Plasma 6. I was able to enable ray tracing on Star Wars Jedi Survivor there, but when I tried it on Hyprland, it just crushed.
