### ISSUE TITLE
floating windows open in workspace 1 not in current workspace

### ISSUE THREAD

**Issue by mahaveergurjar** [hyprwm/Hyprland#6124]
### Hyprland Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch main at commit 33a7b7bb6b307d6e4a093f75ffdda0419cd7ffaf  (core: fix on-empty workspace being called too often (6026)).
Date: Sun May 12 01:03:32 2024
Tag: v0.40.0-65-g33a7b7bb, commits: 4671

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [UHD Graphics] [8086:4628] (rev 0c) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

floating windows open in workspace 1 not in current workspace
Any workspace but 1, open floating window (Bluetooth manager, nm-connection-editor, anything I have a float rule on) it opens on wksp 1

### How to reproduce

Click on Bluetooth manager and open this but open on workspace 1 not open on current workspace

**Comment by vaxerski** [comment]
have you tried disabling initial workspace tracking in the config?

**Comment by mahaveergurjar** [comment]
No how to do this ??

**Comment by mahaveergurjar** [comment]
https://github.com/hyprwm/Hyprland/assets/57872034/e050fe93-dc66-47a6-a9dc-4d7a88022779

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#misc

ctrl+f "initial"

**Comment by mahaveergurjar** [comment]
Now working properly. Thanks, varxy! You are one of the developers who are most active in helping. 🙂

**Comment by mahaveergurjar** [comment]
So I will close this issue ??

**Comment by vaxerski** [comment]
ye, it's expected since you probably launched your "managers" at launch, so they got a token for workspace 1

**Comment by mahaveergurjar** [comment]
ok
