### ISSUE TITLE
Can't interact with QML Popup Windows

### ISSUE THREAD

**Issue by AlephNought0** [hyprwm/Hyprland#6125]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit f21b6fe576b1068598d6c19fbbfd3f0659d5498d  ().
Date: 2024-05-17
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: Cirno
Release: 6.8.9-xanmod1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240515.33d1e75"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When I updated hyprland like 2 days ago the popup window in my quickshell config stopped being interactable and I can click through them. Hovering over some other things in the same program also became nonfunctional or barely functional.

### How to reproduce

1. Open quickshell
2. Create a popup window maybe with some buttons too
3. Try interacting with it

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/64273472/d20c6c8c-68a1-4423-aa21-a39bd6eb52a6

**Comment by vaxerski** [comment]
give your qs config

**Comment by AlephNought0** [comment]
> give your qs config

https://github.com/AlephNought0/Faeryshell

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/aa0caee0-882d-4919-8a2f-81197a4ced8d)
brilliant. integer overflow. congrats qml for this brilliant region.

**Comment by AlephNought0** [comment]
So is it QML not playing nice with newer versions of Hyprland or is this some bug in Hyprland? I don't think the problem is my config since it still works when I downgrade to the last known good commit.

**Comment by vaxerski** [comment]
bug in hl because qml sets an idioticly large region, gimme sec, fixing it
