### ISSUE TITLE
First popup window of session always opens on first workspace

### ISSUE THREAD

**Issue by khyerdev** [hyprwm/Hyprland#6128]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: legion-arch
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Whenever an app opens that is not opened by either an app launcher like wofi, or a hyprland keybind (triggered by clicking a waybar module, pipewire screen capture dialog, etc.), its window will appear on the first workspace, but this entire bug only happens once per session.

### How to reproduce

(using pipewire capture dialog example)

## Process
1. Log out and log back in (to get a new session)
2. Switch to any workspace other than workspace 1
3. Launch obs-studio

## View the effects
1. Switch back to workspace 1
2. You see the dialog on workspace 1

This can only be reproduced once per session

**Comment by vaxerski** [comment]
dupe and expected behavior #6124

**Comment by khyerdev** [comment]
my bad
