### ISSUE TITLE
waybar workspaces on NixOS

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#613]
I'm trying to get workspaces working correctly with waybar on NixOS. I know in https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Status-Bars/#waybar it says that it should be compiled with USE_EXPERIMENTAL flag, I was just wondering if there was a nix derivation for this

Thanks :)

**Comment by fufexan** [comment]
There is. Check the flake, it has `waybar-hyprland`.

**Comment by patrickaldis** [comment]
Ah thank you <3
