### ISSUE TITLE
Launching kickoff softlocks Hyprland due to no surface being focused

### ISSUE THREAD

**Issue by Ghosthree3** [hyprwm/Hyprland#6131]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 2ead1fd22103ce065661555513bace5897083ded  (virtual-keyboard: emit event before finishing keyboard).
Date: Sat May 18 05:07:33 2024
Tag: v0.40.0-111-g2ead1fd2, commits: 4717

flags: (if any)


System Information:
System name: Linux
Node name: milkbar
Release: 6.9.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000


GPU information: 
0b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c1) (prog-if 00 [VGA controller])
0c:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

Launching [kickoff](https://github.com/j0ru/kickoff) results in Hyprland being uninteractable due to no window being focusable (normal), but the new kickoff surface also appearing to be unfocused (no inputs work, can't type, can't close with esc).
I can still change workspaces with hotkeys, but that doesn't help. The only way I was able to escape back to a usable system was to switch TTY and terminate kickoff from another session.

I have already bisected the issue, unfortunately it's a significant commit (121d3a7).
```
121d3a72137d4780602cf245704615f63357ea22 is the first bad commit
```

### How to reproduce

Start [kickoff](https://github.com/j0ru/kickoff) on master and try to type.

**Comment by Ghosthree3** [comment]
Still the case after the release of 0.41.0.

**Comment by H0yVoy** [comment]
Same issue here
