### ISSUE TITLE
XWayland programs crash Hyprland when performing certain actions

### ISSUE THREAD

**Issue by NEUKhoaLe** [hyprwm/Hyprland#6133]
### Hyprland Version

<details> <summary>System/Version info</summary>

Hyprland, built from branch main at commit 2ead1fd22103ce065661555513bace5897083ded  (virtual-keyboard: emit event before finishing keyboard).
Date: Fri May 17 15:07:33 2024
Tag: v0.40.0-111-g2ead1fd2, commits: 4717

flags: (if any)

System Information:
System name: Linux
Node name: khoa-arch
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
0b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] [10de:1e81] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

</details>

### Bug or Regression?

Bug

### Description

When using Webstorm or IntelliJ Idea, certain actions will crash Hyprland.

### How to reproduce

1. Open Webstorm
2. Access the menu bar by pressing `...`
3. Should crash.

### Crash reports, logs, images, videos

[hyprlandCrashReport25351.txt](https://github.com/hyprwm/Hyprland/files/15359734/hyprlandCrashReport25351.txt)

After Bisecting, first bad commit is: `xdg-shell: move to new impl`

commit 0cfdde3d1acbfbf698af17f6986fbc4d644214da

**Comment by dev-null-undefined** [comment]
Same issue here on NixOS
<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 3ac0e7ead1434c172f276a12f81da1eeb0dc4491  ().
Date: 2024-05-16
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: xps
Release: 6.6.30
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Meteor Lake-P [Intel Arc Graphics] [8086:7d55] (rev 08) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD106M [GeForce RTX 4070 Max-Q / Mobile] [10de:2820] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240515.33d1e75"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

**Comment by vaxerski** [comment]
ugh. Looks like an annoying UAF due to wlroots. This should be gone with #6086, so I won't fix this in main atm.

**Comment by NEUKhoaLe** [comment]
Sounds good, will leave open for visibility
