### ISSUE TITLE
wlroots doesn't detect NVIDIA gpu after kernel update

### ISSUE THREAD

**Issue by alexlnkp** [hyprwm/Hyprland#6134]
arch linux

hyprland ver: `hyprland 0.40.0-1`

after updating from linux 6.8.9.arch1-2 to linux 6.9.1.arch1-1 wlroots refuses to see nvidia gpu. Nothing else has changed on the system, just the kernel got updated.
nvidia-smi shows the gpu correctly too.

if i run `export WLR_RENDERER_ALLOW_SOFTWARE=1` before running Hyprland - it launches, but works EXTREMELY poorly

downgrading kernel and headers back to linux 6.8.9.arch1-2 solves the problem, but i'd rather have latest kernel version.

and the crash report:
[hyprlandCrashReport22711.txt](https://github.com/hyprwm/Hyprland/files/15359905/hyprlandCrashReport22711.txt)

nvidia bs:
```
nvidia-dkms 550.78-1
nvidia-settings 550.78-1
nvidia-utils 550.78-1
```

**Comment by Agent00Ming** [comment]
> Nothing else has changed on the system, just the kernel got updated.

You said it yourself, this is not a Hyprland issue.

**Comment by tchofy** [comment]
Idk if you already tried other DEs/WMs, but check if the nvidia modules are loaded, I've had cases before where the dkms hook was skipped and had the same issue, and since nouveau is blacklisted with a modprobe.d file by nvidia-utils you're left with no display driver.

**Comment by alexlnkp** [comment]
> Idk if you already tried other DEs/WMs, but check if the nvidia modules are loaded, I've had cases before where the dkms hook was skipped and had the same issue, and since nouveau is blacklisted with a modprobe.d file by nvidia-utils you're left with no display driver.

sddm loads perfectly fine for me, it's the hyprland that just doesn't work.
regarding dkms hooks - they work correctly. i have run a bunch of tests on latest kernel, even cuda functions properly, but not hyprland.


> > Nothing else has changed on the system, just the kernel got updated.
> 
> You said it yourself, this is not a Hyprland issue.

if after a kernel update your software just breaks - it's not very nice
hyprland is the ONLY thing that broke on my system after kernel update, don't you think it is, therefore, more of a hypr-wlroots issue than the kernel's issue?

**Comment by vaxerski** [comment]
nvidia is not officially supported. Can't help you there

**Comment by alexlnkp** [comment]
reported the issue to the kernel developers. i'll edit this comment when i get the response.

**Comment by dev-null-undefined** [comment]
Maybe try latest nvidia drivers https://www.reddit.com/r/NixOS/comments/1cx9wsy/question_nvidia_555_beta_released_today/
@alexlnkp

**Comment by alexlnkp** [comment]
> Maybe try latest nvidia drivers [reddit.com/r/NixOS/comments/1cx9wsy/question_nvidia_555_beta_released_today](https://www.reddit.com/r/NixOS/comments/1cx9wsy/question_nvidia_555_beta_released_today/) @alexlnkp

Huh, didn't know they released a new driver. Thanks!
I will try it out as soon as it's packaged; I'll update this comment.
