### ISSUE TITLE
Random crash during usage

### ISSUE THREAD

**Issue by LivacoNew** [hyprwm/Hyprland#6145]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Randomly will crash, no cause that I can find. Even when I'm away from my PC, not using my desktop, I will come back to see it sitting at SDDM.
No crash reports, nothing in the logs (attached anyway)
Running through TTY and causing a crash reveals it's segfaulting but nothing else.

I'm aware this report means pretty much nothing, but I'm reporting it anyway at the chance that there's something that can be done because it's either this or I have to go through the annoyance of swapping wm's since it's kinda unusable rn.

### How to reproduce

???

### Crash reports, logs, images, videos

[hypr.log](https://github.com/hyprwm/Hyprland/files/15366702/hypr.log)
![20240518_205749](https://github.com/hyprwm/Hyprland/assets/51921257/5e42988c-a3fd-402c-a9c1-b6ab89b9706f)
(debug:disable_logs is set to false already, not sure what it's complaining for)

**Comment by LivacoNew** [comment]
Have just now got this;
![20240518_210748](https://github.com/hyprwm/Hyprland/assets/51921257/574b67ca-063c-4c72-a8fc-60035654a045)
Can confirm `wayland-1` from here exists.
![image](https://github.com/hyprwm/Hyprland/assets/51921257/53310639-ef68-461a-9345-c876c520ec84)

Going to jump ship to something else in the meantime.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace then

**Comment by LivacoNew** [comment]
[gdb.txt](https://github.com/hyprwm/Hyprland/files/15366837/gdb.txt)
This time when it crashed it froze for a while opposed to just crashing, and reported a IOT error in zsh... 
Will stay in the debug version and post another gdb log if I can get the original crash method to occur

**Comment by vaxerski** [comment]
huh, somehow looks like a memory issue. Update hyprwayland-scanner to latest git and try https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by LivacoNew** [comment]
Launching via asan doesn't even get me into Hyprland, just insta crashes.
![20240518_222147](https://github.com/hyprwm/Hyprland/assets/51921257/45798d8f-6f04-4c55-883c-6e3ebb112fb3)
[asan.log.1867915.txt](https://github.com/hyprwm/Hyprland/files/15366888/asan.log.1867915.txt)

**Comment by LivacoNew** [comment]
[asan.log.2243310.txt](https://github.com/hyprwm/Hyprland/files/15366894/asan.log.2243310.txt)

**Comment by vaxerski** [comment]
thanks! dupe of #6133 then
