### ISSUE TITLE
Hyprland crashed and not starting again

### ISSUE THREAD

**Issue by N3RDIUM** [hyprwm/Hyprland#6149]
### Hyprland version
0.40.0-1

### Bug or Regression?
Bug

### Description
I was experimenting with screen shaders when suddenly hyprland crqshed. Now it’s not even starting up. It always crashes on startup.

### How to reproduce
Play around with shaders until hyprland crqshes. Now it won’t start up again!

### Crash reports, logs, images, videos
![1354FBE3-B94B-4E9E-9DD3-931A8B6BCD74](https://github.com/hyprwm/Hyprland/assets/74598401/9e52bbc7-7979-4c7f-afd6-76e8d45e5a51)

**Comment by Aqa-Ib** [comment]
in that image you can see the location of the crash report, upload it here please.

**Comment by BeyondMagic** [comment]
Kill the process with `pkill -f Hyprland`, and remove the shader you added with a terminal editor like `vi`, `vim`, or `nvim`. Then try to start it up again.

**Comment by N3RDIUM** [comment]
Actually, it wasn’t the shader. It was a random backtick that was accidentally added just before a value in a comma separated list. The process just crashed instead of letting me know that’s it’s a problem with my .file
its working now, thanks!

Thanks,
N3RDIUM
