### ISSUE TITLE
Support for sticky windows

### ISSUE THREAD

**Issue by TravonteD** [hyprwm/Hyprland#615]
I often have a `mpv` window floating in a corner on my screen. I'd like an option to "stick" this window to the screen as I move from workspace to workspace.

**Comment by spikespaz** [comment]
Window pinning

**Comment by vaxerski** [comment]
done in d94fe3d063a910cab64fbdc132f6aa168a52e14d

dispatcher for pinning the active window: `pin`
windowrule for pinning: `pin`
