### ISSUE TITLE
Gtk menus are misaligned

### ISSUE THREAD

**Issue by Ligthiago** [hyprwm/Hyprland#6157]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit f8857e6072bd85b95393499688872aaf7f088b5b  ().
Date: 2024-05-18
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: prometheus
Release: 6.9.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:18:09 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 02) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240517.4a6b83b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

All menus in GTK4 apps become misaligned after update (from fd35b35000fa11ce540d944966ff17c71c31fd27 to latest git). Normally the arrow at the top of the menu (see pics) should be in the center of the menu, now it barely hits a corner. 
If really needed, I can bisect it later.

### How to reproduce

1) Open any gtk4 app, like nautilus
2) Click on Main Menu button in headerbar (or any other)

### Crash reports, logs, images, videos

![2024-05-19T22:39:47,096807918+04:00](https://github.com/hyprwm/Hyprland/assets/142721811/d49fad4e-61ef-431b-8683-0aa5932cb434)

![2024-05-19T22:39:24,445642381+04:00](https://github.com/hyprwm/Hyprland/assets/142721811/7ef0cb14-b499-4b33-9ce1-9359ed590d25)

**Comment by vaxerski** [comment]
#6150

**Comment by Ligthiago** [comment]
Cool closing for dupe, but commit that fix mentioned chrome issue don't seems to affect gtk, all menus are still misaligned.

**Comment by DashieTM** [comment]
Not sure if this goes together with the misalignment, but gtk popups are also completely invisible on the right edge of the screen.

https://github.com/hyprwm/Hyprland/assets/72016555/aed99eab-22c0-4af4-9511-7dc532f6033d

**Comment by pdf** [comment]
Popups/menus don't respect screen edges, and so can appear partially and entirely off-screen. Also, popups don't respect layer-shell exclusive zones, and so can appear under layer-shell windows.

**Comment by hdm9527** [comment]
6c24dc0 doesn't fix the popups/menus positioning problem, it's out of the app's window range, e.g. fcitx5's popup is sometimes in the top left corner of the screen, and the popup goes out of the screen range while typing. Related Issue #6368

**Comment by vaxerski** [comment]
fcitx's popup is a different thing and unrelated to this issue

**Comment by nhosama** [comment]
> 6c24dc0 doesn't fix the popups/menus positioning problem, it's out of the app's window range, e.g. fcitx5's popup is sometimes in the top left corner of the screen.

The popup/menu positioning problem still persists, but in a slightly different way. 

I tested it with Transmission app (GTK4 version), where
- if the button is **in the bottom-left or bottom-right corner** of the window and **the window is at the border of the screen** (like most window often does in tiling mode), the popup/menu will show under the button, thus often go out of the screen.
- Otherwise it will show the popup.

**Comment by DashieTM** [comment]
@nhosama should be fixed in main, feel free to confirm if that is the case.

**Comment by nhosama** [comment]
Yeah, it's perfect. Thanks a lot!!!
