### ISSUE TITLE
a standalone touchpad sensitivity 

### ISSUE THREAD

**Issue by qisc123** [hyprwm/Hyprland#616]
if I want the raw mouse sensitivity, I have to  set  force_no_accel=1.And then the touchpad sensitivity can not be set.
And for me ,the sensitivity is too fast. In sway and wayfire , two sensitivities all can be set.
And maybe can add a mouse wheel scroll speed option https://github.com/swaywm/sway/pull/3018

**Comment by Estebiu** [comment]
What do you mean with "touchpad sensitivity"? Like the "arrow's" speed or the scrolling? 
Anyway, if for you it's necessary to make scrolling adjustements you could try sway or kde. Neither gnome or hyprland supports it right now.

**Comment by qisc123** [comment]
> What do you mean with "touchpad sensitivity"? Like the "arrow's" speed or the scrolling? Anyway, if for you it's necessary to make scrolling adjustements you could try sway or kde. Neither gnome or hyprland supports it right now.

I mean touchpad "arrow's" speed. And another advice is that maybe hyprland  can add a mouse wheel scroll option too.  
Sorry for my unclear expression. And I had used sway and kde for several months. Just for me ,hyprland is better than them.

**Comment by vaxerski** [comment]
`force_no_accel` is a global setting and cannot be done per-device, due to how wlroots works. I do not get to differentiate between devices.

At any rate, every mouse's acceleration profile is forced to NONE (see [InputManager.cpp:740](https://github.com/hyprwm/Hyprland/blob/main/src/managers/input/InputManager.cpp#L740)) and the "force_no_accel" is kinda left only as a nuclear option. You should not experience acceleration with force_no_accel off, and then you can set the sens per-device:
```
device:name {
    sensitivity = -0.5
}
```

**Comment by qisc123** [comment]
hyprctl devices command seems cannot find wireless device. And I don‘t know how to set it

**Comment by vaxerski** [comment]
> hyprctl devices command seems cannot find wireless device. And I don‘t know how to set it

it has to be there, otherwise it wouldnt work.

Acceleration is not pointer speed. Acceleration is when if your mouse moves fast, it will move your cursor more.

Try setting sensitivity to -1 then.

Sway, afaik, only uses that for sensitivity, so the effects should be identical.

**Comment by qisc123** [comment]
> > hyprctl devices command seems cannot find wireless device. And I don‘t know how to set it
> 
> it has to be there, otherwise it wouldnt work.
> 
> Acceleration is not pointer speed. Acceleration is when if your mouse moves fast, it will move your cursor more.
> 
> Try setting sensitivity to -1 then.
> 
> Sway, afaik, only uses that for sensitivity, so the effects should be identical.

I try to set -1, and it works. But it becomes too slow... So how to set to get speed just like set force_no_accel . In another words the default speed in other wms.

**Comment by vaxerski** [comment]
it should be 0. Make sure that your `general:sensitivity` is set to `1` as well.

**Comment by qisc123** [comment]
![2022-09-12_22:59:16](https://user-images.githubusercontent.com/40145802/189687994-c6a55080-fee7-405f-b78d-20dddbecff7d.png)
It is too fast to 0, and too slow to -1 ...

**Comment by qisc123** [comment]
> recompile with [81f267d](https://github.com/hyprwm/Hyprland/commit/81f267dff95f16a6442688dbeaf25fb01b818a04)
> 
> I've added an entry to `hyprctl devices` that should tell you the default libinput sens for each mouse
Maybe the code has a problem? The default speed is always 0, no matter what value I set.

**Comment by vaxerski** [comment]
possibly, but i have no clue where and why - everything works as expected for me, and sway seems to be doing stuff the same way

**Comment by qisc123** [comment]
![2022-09-12_23:44:33](https://user-images.githubusercontent.com/40145802/189698031-2d06e353-5814-4d6f-b579-8343bb53ecdb.png)
Very Strange. The default value is  0. But the speed that set per-device to 0 is very different to the speed that set force no accel.

**Comment by vaxerski** [comment]
you can always do the measuring test and guess the speed - measure how long on your desk an entire monitor takes, and then guess until perfect :P

**Comment by qisc123** [comment]
OK😂. Maybe I can adapt to my touchpad speed. Anyway, thanks for your answer.

**Comment by slikie** [comment]
Is there anything to help with mouse scroll speed?
