### ISSUE TITLE
Hyprland crashes for some reason

### ISSUE THREAD

**Issue by enk-it** [hyprwm/Hyprland#6163]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 7c3bd4c19fe47f2d92463b81d9b38651b7a1a268  (workspace: Add fullscreen workspace selector (5640)).
Date: Sun Apr 21 02:50:08 2024
Tag: v0.39.1-21-g7c3bd4c1, commits: 4481

flags: (if any)


System Information:
System name: Linux
Node name: silencer-a320mh
Release: 6.9.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000


GPU information: 
10:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117 [GeForce GTX 1650] [10de:1f82] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME=ArcoLinux
ID=arcolinux
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://arcolinux.info/"
SUPPORT_URL="https://arcolinuxforum.com/"
BUG_REPORT_URL="https://github.com/arcolinux"
LOGO=arcolinux-hello


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Suddenly, while using using hyprland, monitor blacked and then Hyprland session stopped, then sddm login manager appeared.

### How to reproduce

Just using pc.

### Crash reports, logs, images, videos

journalctl has this in the moment of crashing.
`мая 20 14:18:45 silencer-a320mh systemd-coredump[70985]: Process 60237 (Hyprland) of user 1000 dumped core.
                                                            
                                                            Stack trace of thread 60237:
                                                            #0  0x0000701620dbde44 n/a (libc.so.6 + 0x94e44)
                                                            #1  0x0000701620d65a30 raise (libc.so.6 + 0x3ca30)
                                                            #2  0x0000701620d4d4c3 abort (libc.so.6 + 0x244c3)
                                                            #3  0x0000572c0f85c116 _Z25handleUnrecoverableSignali (Hyprland + 0xbb116)
                                                            #4  0x0000701620d65ae0 n/a (libc.so.6 + 0x3cae0)
                                                            #5  0x0000572c0f97366a n/a (Hyprland + 0x1d266a)
                                                            #6  0x0000572c0f92122b _ZN15CSignalListener4emitESt3any (Hyprland + 0x18022b)
                                                            #7  0x0000572c0f92135c _ZN7CSignal4emitESt3any (Hyprland + 0x18035c)
                                                            #8  0x0000572c0f989c3d _ZN20CCursorShapeProtocol10onSetShapeEP22CWpCursorShapeDeviceV1j26wpCursorShapeDeviceV1Shape (Hyprland + 0x1e8c3d)
                                                            #9  0x0000572c0f858411 n/a (Hyprland + 0xb7411)
                                                            #10 0x0000701620d25596 n/a (libffi.so.8 + 0x7596)
                                                            #11 0x0000701620d2200e n/a (libffi.so.8 + 0x400e)
                                                            #12 0x0000701620d24bd3 ffi_call (libffi.so.8 + 0x6bd3)
                                                            #13 0x000070162181bada n/a (libwayland-server.so.0 + 0x8ada)
                                                            #14 0x0000701621820180 n/a (libwayland-server.so.0 + 0xd180)
                                                            #15 0x000070162181eae2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xbae2)
                                                            #16 0x000070162181f2d7 wl_display_run (libwayland-server.so.0 + 0xc2d7)
                                                            #17 0x0000572c0f85eff7 _ZN11CCompositor15startCompositorEv (Hyprland + 0xbdff7)
                                                            #18 0x0000572c0f830005 main (Hyprland + 0x8f005)
                                                            #19 0x0000701620d4ec88 n/a (libc.so.6 + 0x25c88)
                                                            #20 0x0000701620d4ed4c __libc_start_main (libc.so.6 + 0x25d4c)
                                                            #21 0x0000572c0f84a3e5 _start (Hyprland + 0xa93e5)
                                                            
                                                            Stack trace of thread 60242:
                                                            #0  0x0000701620db84e9 n/a (libc.so.6 + 0x8f4e9)
                                                            #1  0x0000701620dbaed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                            #2  0x00007016210d5e61 __gthread_cond_wait (libstdc++.so.6 + 0xd5e61)
                                                            #3  0x0000572c0f926738 n/a (Hyprland + 0x185738)
                                                            #4  0x00007016210e0c84 execute_native_thread_routine (libstdc++.so.6 + 0xe0c84)
                                                            #5  0x0000701620dbbded n/a (libc.so.6 + 0x92ded)
                                                            #6  0x0000701620e3f0dc n/a (libc.so.6 + 0x1160dc)
                                                            ELF object binary architecture: AMD x86-64`

**Comment by alllexey123** [comment]
Had the same issue. Downgrading to the latest non-git version (0.40.1) solves it.

**Comment by alllexey123** [comment]
The crashes seemed to happen randomly

**Comment by enk-it** [comment]
> The crashes seemed to happen randomly
I'll try it thanks! 
By the way have you experienced absolute system freezing? Like nothing can unfreeze it, not even switching tty (ctrrl+alt+ f*)  works.

**Comment by alllexey123** [comment]
No, Hyprland would usually freeze for <10 seconds and sddm would open right after that.

**Comment by DADA30000** [comment]
> > The crashes seemed to happen randomly
> 
> I'll try it thanks! By the way have you experienced absolute system freezing? Like nothing can unfreeze it, not even switching tty (ctrrl+alt+ f*) works.

yep, sometimes I can get that, but very rarely and often because of high system load

**Comment by vaxerski** [comment]
likely #6133
