### ISSUE TITLE
Some wine apps have the hyprland border around them even though other wine apps that have custom decoration don't have it

### ISSUE THREAD

**Issue by mxaddict** [hyprwm/Hyprland#6167]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: mxaddict-pc
Release: 6.9.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
18:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

UPlay has the hyprland boarder around it as if it's not rendering it's own decorations:

![image](https://github.com/hyprwm/Hyprland/assets/1060905/85284913-6e6f-4aba-858c-be2068178a5e)

Star citizen and BSG launcher both have custom decorations but don't have this issue of having hyprland boarder around them.

Not sure if this is a hyprland bug, let me know if it's not, then I can redirect my bug report to whoever it should go to.

### How to reproduce

Launch BSG/Starcitizen via lutris
Launch any game that has UPlay via lutris/steam

**Comment by vaxerski** [comment]
it is, but I don't really care. Wine is two layers of compatibility before hyprland, and the differences between how windows works and how wayland works will lead to quirks like these. It doesn't matter in the end.

**Comment by mxaddict** [comment]
Makes sense, thanks for the speedy reply! 👍🏼

**Comment by mxaddict** [comment]
To be honest Uplay is a pain in the arse, it's one of the only apps that has this issue 🤣
