### ISSUE TITLE
Ability to silently move windows to first available empty workspace or select i-th active workspace (similar to Gnome)

### ISSUE THREAD

**Issue by JoaoDiogoDuarte** [hyprwm/Hyprland#6169]
### Description

Hi all,

I am not sure if this functionality can already be implemented with the various features in hyprland such as dispatchers, but it would nice to have an option to have workspaces behave a bit like Gnome when it comes to silently moving windows to an empty workspace. 

For example, let us say you have workspaces `1 2 3 5` open.  What would be nice would be to automatically move the windows on workspace `5` to workspace `4` such that there is never an empty workspace in between two active ones. In the end, we would have workspaces `1 2 3 4` open. I think Gnome does this silently when you move workspaces rather than forcibly drag your windows to another workspace as you're using it. 

The main use-case is that I sometimes work with multiple workspaces and as I close windows, I end up with a workspace layout like `2 4 5 7`, and it would be nice to have that automatically "convert" to `1 2 3 4`.

Is there a way to do this with the current functionality in hyprland? Maybe is there a way to map a pressing the number `i`  to move to the `i`-th active workspace rather than literally to the `i`-th workspace?

Thanks all,
João

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/322a8bc4-d51a-460d-9e8c-5d4c88598e29)
?

**Comment by JoaoDiogoDuarte** [comment]
I'm not sure how to use this to recursively go over all active workspaces and move them to `empty`. `emptyn`, `empty+2` etc

**Comment by JoaoDiogoDuarte** [comment]
![output](https://github.com/hyprwm/Hyprland/assets/14338663/b8ee3420-ffad-4e8d-8c8c-2cd625d6020c)


Maybe this gif will better explain what I mean about the workspace behavior (there may be some weird green artifacts, but the focus is on the workspace bar)

**Comment by vaxerski** [comment]
not achievable, as empty workspaces in the middle disappear, which conflicts how hyprland works.
