### ISSUE TITLE
Configure compose key

### ISSUE THREAD

**Issue by VersusF** [hyprwm/Hyprland#617]
Hello,
I'm having a hard time at configuring the compose key, as I'm using a US keyboard but I need to write in Italian too, so I need to have the special letters (like è, which I'm currently copy pasting from the web).
The idea is to have a certain key (in my case right alt) so that `Compose` + `` ` `` + `e` will result in that letter.

Searching online it should be possible with XKB options (which I'm trying to set in the `input` section) but it is not working.
Part of my config file:
```
input {
    kb_file=
    kb_layout=
    kb_variant=
    kb_model=
    kb_options="compose:ralt,level3:ralt_switch"
    kb_rules=

    follow_mouse=2

    touchpad {
        natural_scroll=yes
	tap-to-click=yes
	middle_button_emulation=yes
    }

    sensitivity=0 # -1.0 - 1.0, 0 means no modification.
}
```

I've looked into:
- https://superuser.com/questions/1160777/make-special-characters-available-on-us-keyboard-an-wayland
- https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Configuring_compose_key

and tried various combinations on options, without success

Is it a problem with the WM reload? Is it a bug or simply a lack of documentation?
Thanks in advice

**Comment by vaxerski** [comment]
> `kb_options="compose:ralt,level3:ralt_switch"`

this is not vaid, and no part of the config has ever told you to do this.

Quotes are *not* to be put there.

**Comment by VersusF** [comment]
My bad, removing the quotes fixes the issue. Thank you and sorry for the dummy question
