### ISSUE TITLE
Compiling 0.40.0+ fails on Gentoo amd64 using LLVM toolchain

### ISSUE THREAD

**Issue by soup6020** [hyprwm/Hyprland#6184]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: wendigo
Release: 6.6.30-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Wed May 15 21:00:28 PDT 2024


GPU information: 
0b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e1) (prog-if 00 [VGA controller])
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lexa XT [Radeon PRO WX 3200] [1002:6981] (rev 10) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:
```
</details>

### Bug or Regression?

Bug

### Description

Program fails to compile with undeclared references. 0.39.1 appears to work fine. 

### How to reproduce

Install Gentoo with an LLVM/Clang stage3, accept testing keyword for Hyprland, attempt to install. Compiling the repository directly will also fail. 

### Crash reports, logs, images, videos

[build-fail.log](https://github.com/hyprwm/Hyprland/files/15397047/build-fail.log)

**Comment by vaxerski** [comment]
disable -Werror? I can't see any actual errors.

**Comment by soup6020** [comment]
Line 811 of the file onward lists use of undeclared identifiers, as far as I know those are errors and not warnings turned into errors by -Werror. I will admit the formatting of the file is a little mangled, I apologize.

**Comment by vaxerski** [comment]
ah, right. That was fixed in git.
