### ISSUE TITLE
Native Lua Config Support

### ISSUE THREAD

**Issue by The-Briel-Deal** [hyprwm/Hyprland#6186]
Hey Vaxry/Hyprland team!

I'm interested in working on a Lua configuration API similar to what AwesomeWM and Neovim have. I'm aware that we already have IPC and there are a few third party bindings that aren't really maintained. What I'm interested in adding is the ability to have a `hyprland.lua` config file as your primary or only config. I'm a big fan of using non domain specific languages for config. This makes it so we don't have to deal with parsing a config, all we have to do is call the Lua init file and the user would set the appropriate field/callback on the object.

For example:

```
Hypr = import("hypr")
Hypr.conf.keymaps += Hypr.Bind(mod="Super_L", key="K", dispatch=Hypr.exec, command="kitty")
```

This makes it much easier to programmatically and dynamically set options based on anything you can watch with Lua.

This also gives you all of the niceties of a mature and battle tested scripting language like Syntax Highlighting, LSP, Debugging, and more. All without us having to implement it.

Just wanted to put this out here before working on this in case this isn't wanted or you object to something about this.

Thoughts? (Btw it doesn't have to be Lua, it can be any mature scripting language, I just love this in other configs for window managers and tools like nvim)

**Comment by vaxerski** [comment]
thoughts is "no".

I fail to see a reason for it. LSP? No, lsp still would need to verify every string to be better than what we have, which it obviously won't

Performance and codebase will suffer from this

This would be much more suited as a plugin or external framework. There is 0 need for this in core, and there are zero obstacles to even making a "lua hypr server" running in the background, writing to your hyprland.conf and talking to the sockets

**Comment by The-Briel-Deal** [comment]
Gotcha, that's all fair, would definitely be one more thing to maintain.

**Comment by ein-shved** [comment]
@vaxerski @The-Briel-Deal Hi! I have more significant reason for this (for my opinion). It is the context-based configuration (e.g. window rules).

Here is one of my cases.
I am using google-chrome. In some situations (two monitors) I have two instances of it. In some - only one. I want next behaviour of windows: the first instances (say run in first seconds) must be tiled. The other windows (e.g pop-ups, secret-keys boxes, tabs dragging) must be floating. With current configuration system I see no way to implement such (I did not find any way to run script upon window appearance).

Is there will be really performance issue? With LUA interpreter onboard you are able to get calculated values as strings on startup in context-less parts of config. So in such situations the performance will not be affected. The context-aware parts will be the lua functions.

**Comment by Dimfred** [comment]
@ein-shved I think you can write a script around your browser.
what is does:

The first case:
1. Before start, it checks the `clients` aka open windows, checks if `google-chrome` e.g. exists.
2. If not it starts `google-chrome`

The second case:
1. again check if it exists (now it exists)
2. Start google chrome again, but give it a different window class

Obviously you have 2 window rules, for both chrome classes
Voila, first window get's tiled, the others not.

Anyho actually came here for the lua config thing, +1 here, it makes stuff easier to configure in general.
But I also agree that it just adds additional maintanance overhead sadly and there is not "real" reason..

**Comment by ein-shved** [comment]
> you can write a script around your browser

Thank you! But I did better! I switched to [niri](https://github.com/YaLTeR/niri). Much faster, much stable and much easy to implement such scenarios.

**Comment by Dimfred** [comment]
Nice thanks for the tip, didn't even knew about that one. Always love to discover new WM's, but I just started yesterday configuring hyprland and idk first have to finish that, but thanks for sharing. Have a good one.

**Comment by fjueic** [comment]
@The-Briel-Deal dunno if you still need it.
i have something similar setup in python. [my config](https://github.com/fjueic/.dotfiles/blob/main/.config/hypr/hyprland.py)

i am "thinking" of re-implementing it in TS so lsp can help better with suggestions

**Comment by vaxerski** [comment]
After years of the config outgrowing hyprlang, check https://github.com/hyprwm/Hyprland/pull/13817

**Comment by Dimfred** [comment]
Damn I am on mac now 🥲 had to giggle at the fuck fuck fucking fuck commit tho.

**Comment by D1anaGonzalez** [comment]
You're not gonna believe what im about to told you
