### ISSUE TITLE
on-created-empty with multiple commands

### ISSUE THREAD

**Issue by gvolpe** [hyprwm/Hyprland#6189]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
NixOS 24.05.20240519.6c0b7a9 (Uakari) x86_64 
Linux Kernel 6.9.1 

Monitor DP-3 (ID 1):
	2560x1440@59.95100 at 0x0
```

</details>

### Bug or Regression?

Regression

### Description

Since `v0.40.0` the `on-created-empty` workspace option with a script that spawns up two footclient terminals no longer works as expected. When I switch to the second workspace, only one terminal opens up with one of the two commands and the other one opens up in the first workspace instead ---  which one stays in workspace 2 is random.

This was working as expected on` v0.39.1`: both terminals were open on the second workspace when focusing on that workspace.

### How to reproduce

```
workspace=2,persistent:true,on-created-empty:/nix/store/3nb7bpjj0yjp6miig63v8qr8lighwnj4-ws-nix/bin/ws-nix,monitor:DP-3
```

Where the script spawns up two instances of `footclient` as follows:

```bash
#!/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash
footclient -D ~/workspace/nix-config -E fish -C 'neofetch' &
footclient -D ~/workspace/nix-config -E fish -C 'nitch' &
```

### Crash reports, logs, images, videos

There are no crashes, but I could try debug-level logs if that would help.

---

### Feature request

Since we're here, it would be nice to have a `on-focus-empty` kind of behavior, e.g.: booting the machine for the first time, opening workspace 2 will open the two terminals. Next we close those two terminals and move to a different workspace. Now refocusing on workspace 2 should trigger the command once again.

This is how commands are treated with [XMonad's Dynamic Projects](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Actions-DynamicProjects.html), I would love to have that in Hyprland! (happy to raise a separate ticket for this feature request).

**Comment by vaxerski** [comment]
disable initial workspace tracking in config or dont use foot in server mode

**Comment by gvolpe** [comment]
@vaxerski can you elaborate? I fail to see why this is closed given it's a regression from v0.39.1

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#misc ctrl+f initial

it's not a regression, its a new feature and foot in server mode just breaks it.

**Comment by gvolpe** [comment]
If it's not a regression, was this working by accident in v0.39.1?

**Comment by gvolpe** [comment]
The docs say the following for `initial_workspace_tracking`:

> if enabled, windows will open on the workspace they were invoked on. 0 - disabled, 1 - single-shot, 2 - persistent (all children too)

It's not very clear to me how this is related. Shouldn't workspace rules take precedence over a "misc" config?

```
workspace=2,persistent:true,on-created-empty:footclient
```

It clearly says run this command on this specific workspace. If it opens on a different workspace, isn't this a bug?

**Comment by vaxerski** [comment]
they don't, we do not track what apps were launched by `on-created-empty`. When you switch, we simply run the app. If you add a windowrule to foot to start on workspace 9, and add foot to on-created-empty for 2, it will start on 9.

**Comment by gvolpe** [comment]
> it's not a regression, its a new feature and foot in server mode just breaks it.

Unfortunately, _this is a regression_ by definition compared to `v0.39.1` and none of the suggestions are a fix.

- Disabling `initial_workspace_tracking` has unwanted consequences, i.e. I still want windows to open in the workspace they were invoked on.
- Disabling `foot` server, or any other software, shouldn't be an acceptable solution.
- Adding window rules affects the same app in all workspaces; this is unwanted.

Spawning up processes on a given workspace is a trivial feature on most window managers, and this was actually working on ths previous version, so why can't we still have it in Hyprland? I understand that there were big changes on `v0.40.0` and things break, but denying this isn't a regression and closing the report is not a step forward.

XMonad example doing the same that was working with Hyprland in v0.39.1 below:

```haskell
projects :: [Project]
projects =
  [ Project { projectName      = ossWs
            , projectDirectory = "~/workspace/nix-config"
            , projectStartHook = Just $ do spawn (terminalWithCommand "neofetch")
                                          spawn (terminalWithCommand "nitch")
  ]
```

**Comment by gvolpe** [comment]
Appreciate the response. Any reason `initial_workspace_tracking=0` is not the default? The unwanted side-effect has to do with scratchpads, but I can live with that for now.

I'll raise a new feature request mentioned in the report above, if you think that's something that can be supported.

**Comment by vaxerski** [comment]
I doubt it can be supported with how the method currently works, but I don't know of any other method.

tracking is 1 by default cuz it's a nice feature imo
