### ISSUE TITLE
NixOS flake infinite recursion

### ISSUE THREAD

**Issue by NULLx76** [hyprwm/Hyprland#619]
After updating the flake from 0ad261aa9c408aa43b8ff846acf9dab97e29b927 to c425e620af37e4ccc63d534982bc1056976a1554 I keep encountering the following error when evaluating the nix config: 
```
 null | Evaluating null
 null | error: infinite recursion encountered
 null | 
 null |        at /nix/store/vi0fgpw6gl491jl40382ssarph2znnxh-source/lib/modules.nix:578:38:
 null | 
 null |           577|       declsByName = byName "options" (module: option:
 null |           578|           [{ inherit (module) _file; options = option; }]
 null |              |                                      ^
 null |           579|         ) options;
 ```

It seems to occur when importing the HM module here: https://git.0x76.dev/v/infrastructure/src/branch/main/nixos/hosts/thalassa/null/configuration.nix#L45 in my NixOS config

I'm unsure if this is a config fault of mine or a bug in the flake, but I have a hard time finding a fix.

**Comment by jmc-figueira** [comment]
I can confirm this has happened to me as well, as I reverted to the `0.12.1beta` release artifact and it worked fine. It must have been this commit, although I didn't test it: eee0cad4d0e58f145432bdcd6dde0b070cd73f14

**Comment by fufexan** [comment]
Oops, I somehow missed that. Sorry.
