### ISSUE TITLE
Dimaround rule crashes Hyprland

### ISSUE THREAD

**Issue by hweissi** [hyprwm/Hyprland#6190]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 93fea890433ec11d7a915f5e0466b2e8b513e895  ().
Date: 2024-05-22
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: hw-lenovo
Release: 6.9.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:18:09 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [Iris Xe Graphics] [8086:46a8] (rev 0c) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240521.3eaeaeb"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

When adding the following `windowrulev2` rule:
```
"dimaround, class:^(gcr-prompter)$"
```
anything that causes `gcr-prompter` to appear will crash Hyprland.
This includes VSCode, Evolution, and Seahorse.

This rule was in my config for a while, the last commit confirmed to work was `d7aed240db408259228bf09708986c82bdca23eb`

### How to reproduce

Add the `"dimaround, class:^(gcr-prompter)$"` `windowrulev2`, and try to unlock the keyring

### Crash reports, logs, images, videos

[hyprlandCrashReport1731.txt](https://github.com/hyprwm/Hyprland/files/15406416/hyprlandCrashReport1731.txt)

**Comment by vaxerski** [comment]
can you https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace ?

Also, for future reference:
 - do not provide a "last working commit" - it's annoying. Provide the _regressor_, aka first _bad_ commit.
 - don't wrap commit hashes in `code` so that they turn into links
