### ISSUE TITLE
Crash on start: EGL_BAD_PARAMETER

### ISSUE THREAD

**Issue by mousebyte** [hyprwm/Hyprland#6192]
### Hyprland Version

<details> <summary>System/Version info</summary>

Unable to run hyprctl, more info in crash report

</details>

### Bug or Regression?

Bug

### Description

I'm getting a crash on startup on Arch linux using `hyprland-git`. I'm using the `nvidia-dkms` drivers. Everything is set up according to the instructions in the wiki, and it was working alright before.

### How to reproduce

Start Hyprland from SDDM or from the TTY.

### Crash reports, logs, images, videos

[hyprlandCrashReport6102.txt](https://github.com/hyprwm/Hyprland/files/15406996/hyprlandCrashReport6102.txt)

**Comment by vaxerski** [comment]
out of luck, nvidia is not officially supported

**Comment by mousebyte** [comment]
> out of luck, nvidia is not officially supported

turns out I didn't have the `nvidia_drm.fbdev` kernel parameter enabled. I actually have no idea how it was working in the first place. seems fine now!
