### ISSUE TITLE
Broken OSK

### ISSUE THREAD

**Issue by System64fumo** [hyprwm/Hyprland#6196]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e419ef1873de01b0762f7f1a411994170a4d8cab  (Revert CMake: use add_custom_command for generating protocols (6104)).
Date: Tue May 21 21:29:56 2024
Tag: v0.40.0-117-ge419ef18, commits: 4723

flags: (if any)


System Information:
System name: Linux
Node name: icicle
Release: 6.9.0-rc4-baka+
Version: #1 SMP PREEMPT Thu Apr 18 09:30:50 IDT 2024


GPU information: 


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
  hyprgrass by horriblename ver 0.6
```

</details>

### Bug or Regression?

Bug

### Description

On screen keyboards seem to have stopped working on my phone as of the latest hyprland updates
Yesterday i upgraded hyprland from 0.39 to 0.40 and noticed that my OSK stopped working
Oddly enough OSKs still work just fine on desktop

### How to reproduce

1: Install any OSK (I personally use wvkbd but wf-osk is broken too)
2: Launch the OSK
3: Tap on an input field (Or launch a terminal)
4: Try typing something
5: No worky

**Comment by vaxerski** [comment]
cant repro

**Comment by System64fumo** [comment]
It appears that the issue is related to a lack of keyboard and mouse, Attaching a keyboard and mouse to my phone made the OSK start working again, Disconnecting it causes the OSK to stop working.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/15418288/patch.txt)
le try

**Comment by vaxerski** [comment]
potentially fixed by #6366 ?

**Comment by System64fumo** [comment]
Fun
```
[65/600] Compiling C++ object protocols/libserver_protos.a.p/meson-generated_.._xdg-shell.cpp.o
ninja: job failed: c++ -Iprotocols/libserver_protos.a.p -Iprotocols -I../protocols -flto=auto -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++23 -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -DHAS_EXECINFO -march=armv8-a -mtune=generic -Ofast -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto -fPIC -MD -MQ protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o -MF protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o.d -o protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o -c protocols/linux-dmabuf-v1.cpp
In file included from protocols/linux-dmabuf-v1.cpp:33:
protocols/linux-dmabuf-v1.hpp:211:22: error: ‘CWlBuffer’ has not been declared
  211 |     void sendCreated(CWlBuffer*);
      |                      ^~~~~~~~~
protocols/linux-dmabuf-v1.hpp:213:25: error: ‘CWlBuffer’ has not been declared
  213 |     void sendCreatedRaw(CWlBuffer*);
      |                         ^~~~~~~~~
protocols/linux-dmabuf-v1.cpp:224:6: error: variable or field ‘sendCreated’ declared void
  224 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
protocols/linux-dmabuf-v1.cpp:224:43: error: ‘CWlBuffer’ was not declared in this scope; did you mean ‘wl_buffer’?
  224 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
      |                                           ^~~~~~~~~
      |                                           wl_buffer
protocols/linux-dmabuf-v1.cpp:224:54: error: ‘buffer’ was not declared in this scope; did you mean ‘wl_buffer’?
  224 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
      |                                                      ^~~~~~
      |                                                      wl_buffer
protocols/linux-dmabuf-v1.cpp:232:6: error: variable or field ‘sendCreatedRaw’ declared void
  232 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
protocols/linux-dmabuf-v1.cpp:232:46: error: ‘CWlBuffer’ was not declared in this scope; did you mean ‘wl_buffer’?
  232 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
      |                                              ^~~~~~~~~
      |                                              wl_buffer
protocols/linux-dmabuf-v1.cpp:232:57: error: ‘buffer’ was not declared in this scope; did you mean ‘wl_buffer’?
  232 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
      |                                                         ^~~~~~
      |                                                         wl_buffer
../hyprpm/src/core/PluginManager.cpp: In function ‘std::string execAndGet(std::string)’:
../hyprpm/src/core/PluginManager.cpp:45:50: warning: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Wignored-attributes]
   45 |     const std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                                  ^
ninja: subcommand failed
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hyprland-git-exit status 4
 ```

**Comment by vaxerski** [comment]
its called not updating hw-s

**Comment by System64fumo** [comment]
> potentially fixed by #6366 ?

I'm afraid not

**Comment by xz-dev** [comment]
> Fun
> 
> ```
> [65/600] Compiling C++ object protocols/libserver_protos.a.p/meson-generated_.._xdg-shell.cpp.o
> ninja: job failed: c++ -Iprotocols/libserver_protos.a.p -Iprotocols -I../protocols -flto=auto -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++23 -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -DHAS_EXECINFO -march=armv8-a -mtune=generic -Ofast -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto -fPIC -MD -MQ protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o -MF protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o.d -o protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o -c protocols/linux-dmabuf-v1.cpp
> In file included from protocols/linux-dmabuf-v1.cpp:33:
> protocols/linux-dmabuf-v1.hpp:211:22: error: ‘CWlBuffer’ has not been declared
>   211 |     void sendCreated(CWlBuffer*);
>       |                      ^~~~~~~~~
> protocols/linux-dmabuf-v1.hpp:213:25: error: ‘CWlBuffer’ has not been declared
>   213 |     void sendCreatedRaw(CWlBuffer*);
>       |                         ^~~~~~~~~
> protocols/linux-dmabuf-v1.cpp:224:6: error: variable or field ‘sendCreated’ declared void
>   224 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
>       |      ^~~~~~~~~~~~~~~~~~~~~~~
> protocols/linux-dmabuf-v1.cpp:224:43: error: ‘CWlBuffer’ was not declared in this scope; did you mean ‘wl_buffer’?
>   224 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
>       |                                           ^~~~~~~~~
>       |                                           wl_buffer
> protocols/linux-dmabuf-v1.cpp:224:54: error: ‘buffer’ was not declared in this scope; did you mean ‘wl_buffer’?
>   224 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
>       |                                                      ^~~~~~
>       |                                                      wl_buffer
> protocols/linux-dmabuf-v1.cpp:232:6: error: variable or field ‘sendCreatedRaw’ declared void
>   232 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
>       |      ^~~~~~~~~~~~~~~~~~~~~~~
> protocols/linux-dmabuf-v1.cpp:232:46: error: ‘CWlBuffer’ was not declared in this scope; did you mean ‘wl_buffer’?
>   232 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
>       |                                              ^~~~~~~~~
>       |                                              wl_buffer
> protocols/linux-dmabuf-v1.cpp:232:57: error: ‘buffer’ was not declared in this scope; did you mean ‘wl_buffer’?
>   232 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
>       |                                                         ^~~~~~
>       |                                                         wl_buffer
> ../hyprpm/src/core/PluginManager.cpp: In function ‘std::string execAndGet(std::string)’:
> ../hyprpm/src/core/PluginManager.cpp:45:50: warning: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Wignored-attributes]
>    45 |     const std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.c_str(), "r"), pclose);
>       |                                                  ^
> ninja: subcommand failed
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: hyprland-git-exit status 4
> ```

When I try update hyprland from 0.40 to 0.41 in Gentoo, I also got it, but I think it's not due the same reason.

**Comment by xz-dev** [comment]
> its called not updating hw-s

I'm confused, What's meaning is hw-s

**Comment by fufexan** [comment]
@xz-dev hyprwayland-scanner.

**Comment by vaxerski** [comment]
try now

**Comment by System64fumo** [comment]
Can confirm, it works!
Another flawless victory for vaxry :+1:
