### ISSUE TITLE
Hyprland Crashing After Opening a Wine Application

### ISSUE THREAD

**Issue by coredev-uk** [hyprwm/Hyprland#6197]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 93fea890433ec11d7a915f5e0466b2e8b513e895  (renderer: render fonts with pango, add global `font_family` config option (6138)).
Date: Wed May 22 09:09:36 2024
Tag: v0.40.0-118-g93fea890, commits: 4724

flags: (if any)


System Information:
System name: Linux
Node name: corearch
Release: 6.9.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:18 +0000


GPU information:
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080 Lite Hash Rate] [10de:2216] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  csgo-vulkan-fix by Vaxry ver 1.2
```

</details>

### Bug or Regression?

Bug

### Description

When I tried running an installation script which involved installing a application using Wine, Hyprland crashed. The script I was using was the Star Citizen installation ([found here](https://github.com/starcitizen-lug/knowledge-base/wiki/Quick-Start-Guide)). 

### How to reproduce

Try installing the Star Citizen launcher using Wine. I was also able to recreate this with the Epic Games Store using Wine, shortly after the installation and launching it, Hyprland crashed with similar error messages to the log provided.

### Crash reports, logs, images, videos

[hyprlandCrashReport2187838.txt](https://github.com/hyprwm/Hyprland/files/15408310/hyprlandCrashReport2187838.txt)

**Comment by vaxerski** [comment]
for the love of god #6133 this is the 11th dupe

**Comment by fufexan** [comment]
Maybe let's pin the issues so that people can easily find them.

**Comment by vaxerski** [comment]
pin 6133 then

**Comment by coredev-uk** [comment]
My bad, I was looking for similar kind of crash logs but couldn't find any. I'd imagine GitHub's search doesn't read the log files.
