### ISSUE TITLE
[question] Is it really necessary to `handleKeybinds` twice for each keyboard event?

### ISSUE THREAD

**Issue by c0h2r** [hyprwm/Hyprland#620]
The lines 174, 176 as well as 193, 193 of the [`KeybindManager.cpp`](https://github.com/hyprwm/Hyprland/blob/fbd2b4799d9c205cb0283432ef9ae3778ff68aa7/src/managers/KeybindManager.cpp) call the manager's `handleKeybinds` method twice for each keyboard event, and are of the form `found = handleKeybinds(...) || found;`. I suspect that it's so to handle different events assigned to the same binding but using both the keysym and keycode (the question is why would anyone do so).

I'm writing a patch to add a new binding type: if a binding is pressed and held for n milliseconds and no other events occur, a specified handler is called. It's useful to have a status bar always hidden, and show it only when a user wants to move a window to a workspace but forgot which ones are currently empty (like mod + shift is pressed, and then nothing follows), for example. This involves removing a timer used to call the handler whenever any events occur, and is currently solved with the following "hack" in the beginning of the `handleKeybinds`:
```c++
// Literally any other event should suppress the timed one.
// The problem is, the method is called twice for each keyboard event,  
// and removing the timer unconditionally results in the timer being killed
// by the same event that added it (but in the second call).
// Thus the newEvent flag is introduced
static int newEvent = 0;
newEvent += key.empty();  // keyboard event -> + 1, mouse event -> + 0
newEvent %= 2;
newEvent |= !key.empty(); // key string isn't empty in case of mouse events,
                          // and those call this method only once per event,
                          // hence, always new

if (m_pTimedKeybindEventSource && newEvent){
    wl_event_source_remove(m_pTimedKeybindEventSource);
    m_pTimedKeybindEventSource = nullptr;
}
```

Alternatively, the aforementioned lines can be rewritten as
```c++
found = g_pKeybindManager->handleKeybinds(MODS, "", keysym, 0, true, e->time_msec);
found = found || g_pKeybindManager->handleKeybinds(MODS, "", 0, KEYCODE, true, e->time_msec);
```
which'll allow removing the timer unconditionally (except checking for its existence) as well as removing the repeat timers the same way, but will make it possible to handle either a keysym or a keycode bind, with the former being prioritized. Is this approach viable?

**Comment by vaxerski** [comment]
> I suspect that it's so to handle different events assigned to the same binding but using both the keysym and keycode (the question is why would anyone do so).

ye

> This involves removing a timer used to call the handler whenever any events occur, and is currently solved with the following "hack" in the beginning of the handleKeybinds:

ugly af, why not see how `binde` works?

> which'll allow removing the timer unconditionally (except checking for its existence) as well as removing the repeat timers the same way, but will make it possible to handle either a keysym or a keycode bind, with the former being prioritized. Is this approach viable?

no, you're breaking backwards compat for no reason

**Comment by c0h2r** [comment]
> how binde works
Yap, sorry, killing the timer in the onKeyEvent/onMouseEvent section definitely makes more sense.
