### ISSUE TITLE
Games don't detect ultrawide resolution by default

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#6200]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit e8e02e81e84bb04efa0c926361ec80c60744f665  (README: minor cleanup).
Date: Tue Apr 16 16:36:21 2024
Tag: v0.39.1-1-ge8e02e81, commits: 4461

flags: (if any)


System Information:
System name: Linux
Node name: ninth
Release: 6.8.7-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Thu Apr 18 14:31:14 -00 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] [1002:7340] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Games don't detect 21:9 resolution (2560x1080) by default on hyprland. I have a problem with gamescope because it makes my games not launch anymore forever when i run them with gamescope, only fix is reinstalling the game (im now having to reinstall baldurs gate 3 :smiley: ), so I can't use it to force resolution (it does work if i force it).

Some games have all res available so I'm still able to set them, but, with games that try to detect dynamically, it doesn't work.

### How to reproduce

Launch game from steam with ultrawide monitor
No ultrawide option available if it tries to detect from current monitor.

**Comment by vaxerski** [comment]
almost all games run through xwl and use the primary x monitor to detect res. Set the primary X display with xrandr to your ultrawide.

Anyways, this is not a hl issue
