### ISSUE TITLE
Hyprland crashes with multiple monitors and nouveau drivers

### ISSUE THREAD

**Issue by clementpoiret** [hyprwm/Hyprland#6209]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 7ad9116de8d0b7dac27eaf080bd92998a8fb40e5  ().
Date: 2024-05-22
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.9.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 10:18:09 UTC 2024


GPU information: 
2d:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD103 [GeForce RTX 4080] [10de:2704] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240521.5710852"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Nouveau drivers:
- Two monitors plugged: Hyprland crashes and go back to the TTY, but do not output a crash log.
- One monitor: Hyprland launches correctly

Nvidia drivers:
- The two monitors are working

Here are my env variables: https://github.com/clementpoiret/nixos-config/blob/main/modules/home/hyprland/variables.nix
I commented out what I used for the nvidia drivers.

### How to reproduce

Plug two monitors and start Hyprland.

### Crash reports, logs, images, videos

No RED error in the TTY, nor crash report. It just looks like it gracefully exits.

**Comment by vaxerski** [comment]
logs then? coredumpctl? 

Saying "no work" doesn't help

**Comment by clementpoiret** [comment]
Here is the output from coredumpctl
[dump.txt](https://github.com/hyprwm/Hyprland/files/15416530/dump.txt)

**Comment by vaxerski** [comment]
looks like a nouveau bug to me
