### ISSUE TITLE
mouse movement breaks VRR

### ISSUE THREAD

**Issue by imapotatook** [hyprwm/Hyprland#6222]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cdd3de640d7cca766135515e167b26b7bc603ada  (add back nvidia hardware cursor).
Date: Fri May 24 14:42:19 2024
Tag: v0.40.0-121-gcdd3de64, commits: 4727

flags: (if any)


System Information:
System name: Linux
Node name: artix
Release: 6.9.1-273-tkg-bore
Version: #1 SMP PREEMPT_DYNAMIC TKG Tue, 21 May 2024 00:11:39 +0000


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti] [10de:2486] (rev a1) (prog-if 00 [VGA controller])
11:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

When moving my mouse around in game, my monitors refresh rates jumps to its maximum (155), using Hyprland compiled from Main 4e42107d25dc47ee94da282db233f85f1e4 , I used my monitors OSD to view refresh rate changing. I have not tested on the amd igpu as of yet

nvidia driver version: 555.42.02

Things i have tried:

main branch:
4e42107d25dc47ee94da282db233f85f1e4c6bd0 - no atomic = 1, no hardware cursors = 1 or 0, VRR mouse issue
4e42107d25dc47ee94da282db233f85f1e4c6bd0 - no atomic = 0, no hardware cursors = 1 or 0, broken VRR, stays at monitors max refresh

I have narrowed down the commits where the issue starts > ed411f53bdcf8d455f9e6ca769693aa84dc8372f to fe4737fb9d578400ecfc63dc6ab4d684993362b8

e4e84064f2d07810e0c150bce1369a0a00503e9a Is the last working commit before having VRR issue with mouse. 
However compiling from main with both, Fixes the VRR mouse issue:
-  (#6220)
-  (#6086)

main + #6086 + #6220:
WLR_DRM_NO_ATOMIC = 1, WLR_NO_HARDWARE_CURSORS = 1, VRR mouse issue
WLR_DRM_NO_ATOMIC = 1, WLR_NO_HARDWARE_CURSORS = 0, working VRR
WLR_DRM_NO_ATOMIC = 0, WLR_NO_HARDWARE_CURSORS = 1, VRR mouse issue
WLR_DRM_NO_ATOMIC = 0, WLR_NO_HARDWARE_CURSORS = 0, working VRR, refresh rate spikes have also mostly disappeared that issue (#5918) is talking about

main + #6220:
WLR_DRM_NO_ATOMIC = 1, WLR_NO_HARDWARE_CURSORS = 1 or 0, working VRR
WLR_DRM_NO_ATOMIC = 0, WLR_NO_HARDWARE_CURSORS = 1 or 0, broken VRR

main + #6086:
WLR_DRM_NO_ATOMIC = 1, WLR_NO_HARDWARE_CURSORS = 1 or 0, VRR mouse issue
WLR_DRM_NO_ATOMIC = 0, WLR_NO_HARDWARE_CURSORS = 1 or 0, VRR mouse issue, refresh rate spikes have also mostly disappeared that issue (#5918) is talking about

### How to reproduce

Use the configs listed above with their corresponding branch/PR, use your monitors refresh rate OSD function to see if refresh rate is matching what happens with my test results.

**Comment by Agent00Ming** [comment]
FYI, the `WLR_NO_HARDWARE_CURSORS` env var has been deprecated in favour of the `cursor:no_hardware_cursors` config since #5902
