### ISSUE TITLE
Last focused window in workspace info

### ISSUE THREAD

**Issue by brannegan** [hyprwm/Hyprland#623]
Add information about last focused window in workspace to hyprcrl subcommand, e.g. `lastFocused` bool to `hyprctl clients`.
I'm writing `eww` workspace widget with dinamycally changing workspace icon, based on last active window class. It would be great to reduce complexity of that. 

Great job, b.t.w. Hyprland really awesome!

**Comment by vaxerski** [comment]
done in f6ecef0959163d10dd6597037192456977aa5bc2
