### ISSUE TITLE
KDE Arch icons randomly becoming unresponsive when alt-tabbing and then nothing is responsive ever

### ISSUE THREAD

**Issue by CodecNomad** [hyprwm/Hyprland#6231]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

KDE Arch icons randomly becoming unresponsive when alt-tabbing and then nothing is responsive ever, so I need to force close it.

### How to reproduce

It seems to randomly happen when I alt-tab into it

**Comment by vaxerski** [comment]
what is a kde arch icon?

**Comment by CodecNomad** [comment]
Nothing anymore, the entire application became unresponsive but I managed to fix it. (Idk why I said icons)
