### ISSUE TITLE
Headers missing (hyprpm)

### ISSUE THREAD

**Issue by starsprinter92** [hyprwm/Hyprland#6239]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: ethan-hpenvydesktopte020xxx
Release: 6.9.1-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:07 +0000


GPU information: 
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] [10de:2488] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2024.04.20"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"
```
(can't upload config)
</details>

### Bug or Regression?

Bug

### Description

Cannot install any plugins. also yes, i cannot do hyprpm update

### How to reproduce

???

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/97267759/68fbb354-3684-4cde-b7f4-66ac06cf956b)

**Comment by stupich** [comment]
Have you installed cpio, meson and cmake?

**Comment by CampbellL** [comment]
I think the error reporting on this is a bit odd. If you run it with -v it will give you a more detailed log, about why it failed!

For me I had to install the following packages: `meson cpio cmake hyprwayland-scanner`

**Comment by starsprinter92** [comment]
guys i just had to insta;; hyprwayland-scanner and ran hyprpm update so yes it works
