### ISSUE TITLE
Toggling border

### ISSUE THREAD

**Issue by budimanjojo** [hyprwm/Hyprland#624]
Hello, Is there a way to toggle border on/off? I want to have a keybinding to toggle window border on/off. Thanks!

**Comment by vaxerski** [comment]
`hyprctl keyword general:border_size 0`

**Comment by budimanjojo** [comment]
> `hyprctl keyword general:border_size 0`

Yes I know that I can turn off the border, what I want is to toggle it on/off though.
Maybe I can use a script? Like a keybinding to call the script that has something like this:
```
if border_size > 0; then
  hyperctl keyword general:border_size 5
else
  hyperctl keyword general:border_size 0
fi
```
Not sure how to check the `border_size` in the script though.

**Comment by avalsch** [comment]
> Not sure how to check the `border_size` in the script though.
hyprctl getoption might work?

https://wiki.hyprland.org/Configuring/Using-hyprctl/

**Comment by budimanjojo** [comment]
> > Not sure how to check the `border_size` in the script though.
> 
> hyprctl getoption might work?
> 
> https://wiki.hyprland.org/Configuring/Using-hyprctl/

Didn't know there's that command. Thanks! I'll try this when I'm home.
