### ISSUE TITLE
Bad xdg_positioner behavior with inkscape

### ISSUE THREAD

**Issue by Bartkk0** [hyprwm/Hyprland#6240]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 553232a3e4c112c8511309e6b685cb614895e714  (hyprctl: Add Config Flag to `hyprctl systeminfo` (6160)).
Date: Sat May 25 22:46:07 2024
Tag: v0.40.0-137-g553232a3, commits: 4743

flags: (if any)


System Information:
System name: Linux
Node name: fluffy
Release: 6.9.1-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:12 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] [10de:1f08] (rev a1) (prog-if 00 [VGA controller])
11:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

Long popups appear detached on wrong height.
While bisecting I found that it's caused by 0cfdde3d1acbfbf698af17f6986fbc4d644214da
![image](https://github.com/hyprwm/Hyprland/assets/32180149/9321ad6f-2edd-4330-a630-cc7f08aab73f)

Edit:
It appears that almost all popups are wrongly positioned when they would be partially off screen.

### How to reproduce

Can be reproduced by opening page format drop down in inkscape.
Inkscape > File > Document properties > Format

**Comment by Fxzzi** [comment]
Can confirm, popups for many apps are either not in the right position, or off center. For example, the Vesktop splash screen is off to the top left of my monitor whereas on 0.40.0 it was centered.

**Comment by vaxerski** [comment]
I do realize, I'll work on this after #6268 is done and merged

**Comment by vaxerski** [comment]
this should fix this.

**Comment by Agent00Ming** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/107314235/7908d0e8-a4f3-4d09-8f6d-c566b72052ce)

**Comment by vaxerski** [comment]
should be fixed

**Comment by Agent00Ming** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/107314235/f6269498-d55c-4d5a-83de-5018cc662d01)
:+1:

**Comment by vaxerski** [comment]
coolio

**Comment by Agent00Ming** [comment]
https://github.com/hyprwm/Hyprland/commit/d6337146bb99a20c96c89b7693f4ad726455f6ba actually messes with expanding popups...
![image](https://github.com/hyprwm/Hyprland/assets/107314235/13635389-d7d6-44d1-9951-87546d3e412d)

**Comment by vaxerski** [comment]
on it

**Comment by vaxerski** [comment]
done

**Comment by Agent00Ming** [comment]
now it just crashes hyprland :rofl:
[hyprlandCrashReport23767.txt](https://github.com/user-attachments/files/15743685/hyprlandCrashReport23767.txt)

**Comment by vaxerski** [comment]
it does not. Pull again :)
