### ISSUE TITLE
Specific workspace stopped showing after update

### ISSUE THREAD

**Issue by yazoink** [hyprwm/Hyprland#6241]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: cyberia
Release: 6.9.1-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:12 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])
	DeviceName: VGA compatible controller


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Cannot switch to the second workspace anymore. Windows can be moved to it but they can't be accessed afterward.

### How to reproduce

Attempt to switch to workspace 2.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/98802603/224bb5d2-a824-4dfa-9bb1-bd9b8c56a9a3

[My config](https://0x0.st/XZlX.conf)

**Comment by Agent00Ming** [comment]
check `hyprctl monitors` for an unknown monitor with a 1024x768 resolution, you'll probably need to disable it in your hyprland config

**Comment by yazoink** [comment]
Disabled the monitor and it's working fine now
