### ISSUE TITLE
Problem running vm with intel gvt-g graphics

### ISSUE THREAD

**Issue by wioo** [hyprwm/Hyprland#6252]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.9.1-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Wed, 22 May 2024 13:47:07 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:191b] (rev 06) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

When trying to run windows 11 vm with intel gvt-g graphics, screen gets black for a moment and then blank workspace without status bar opens. I can change between workspaces but only some (nb. 3 and 4  usually) show mouse cursor. 

Found similar issue here https://forum.garudalinux.org/t/intel-gvt-g-and-kvm-breaks-sway/34449

... so it may be wlroots problem?

No problem with x11 wm.

### How to reproduce

Start windows?? vm using intel gvt-g graphics with virt-manager.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/15448146/hyprland.log)
[hyprland_config.txt](https://github.com/hyprwm/Hyprland/files/15448181/hyprland_config.txt)

**Comment by wioo** [comment]
Ok, looks like hyprland creates new monitor when vm with intel gvt-g is started. Now new monitor is shown on laptop screen. Temp solution is to exit hyprland, restart it and open virt-manager. Vm is already started, so just open it. One can also move workspace with virt-manager to new monitor. 

I cant disable this new monitor because all monitors have the same name and description. Disable with ID doesnt work.

**Comment by kpzhao** [comment]
> Ok, looks like hyprland creates new monitor when vm with intel gvt-g is started. Now new monitor is shown on laptop screen. Temp solution is to exit hyprland, restart it and open virt-manager. Vm is already started, so just open it. One can also move workspace with virt-manager to new monitor.
> 
> I cant disable this new monitor because all monitors have the same name and description. Disable with ID doesnt work.

hello，I have same problem on swaywm，Do you know how to resolve it？

**Comment by wioo** [comment]
Sadly, no.

**Comment by kpzhao** [comment]
> Sadly, no.

I found that gvt-g work fine on niriwm and kde

**Comment by wioo** [comment]
Dont know how but this is fixed. Still happens on sway/wlroots. Aquamarine win I guess.
