### ISSUE TITLE
Hyprland crashes on startup

### ISSUE THREAD

**Issue by NoamLeshem** [hyprwm/Hyprland#6258]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 553232a3e4c112c8511309e6b685cb614895e714  (hyprctl: Add Config Flag to `hyprctl systeminfo` (6160)).
Date: Sat May 25 23:46:07 2024
Tag: v0.40.0-137-g553232a3, commits: 4743

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.9.2-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:09 +0000


GPU information: 
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland wont launch from sddm or from tty (but it will launch when im already in a wayland session - for example if gnome-wayland was already running the launching Hyprland through kitty will work noramlly)

the crash report tells to add the line `env = WLR_RENDERER_ALLOW_SOFTWARE, 1`
doing so and trying to launch Hyprland once again from the tty will actually launch hyrpland for a couple of second (although it will look very choppy and messy) and after those few seconds it will still crash

### How to reproduce

try to launch hyprland from the tty

### Crash reports, logs, images, videos

[hyprlandCrashReport1481.txt](https://github.com/hyprwm/Hyprland/files/15449110/hyprlandCrashReport1481.txt)

**Comment by vaxerski** [comment]
this is not a hyprland issue, this is nvidia being nvidia

**Comment by NoamLeshem** [comment]
if that is an nvidia issue then why does hyprland works when im already in a wayland session?
any way, so what am i supposed to do?
ive tried to force hyprland to use the integrated intel gpu but to no avail following [wiki](https://wiki.hyprland.org/Configuring/Multi-GPU/)

**Comment by vaxerski** [comment]
nvidia is not officially supported, you are on your own

**Comment by NoamLeshem** [comment]
got it fixed after i followed the proper documentation on the wiki [here](https://wiki.hyprland.org/Nvidia/) and [this](https://www.reddit.com/r/hyprland/comments/188a8fr/comment/kbnffc2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) comment on reddit

**Comment by vaxerski** [comment]
No clue, ask nvidia devs
