### ISSUE TITLE
In idle mode, the screen goes blank with idle inhibitor enabled

### ISSUE THREAD

**Issue by sofijacom** [hyprwm/Hyprland#6272]
### Description

In idle mode, the screen goes blank with `idle inhibitor` enabled - Hyprland v0.40.0

### How to reproduce

![screenshot-20240529-162200](https://github.com/hyprwm/Hyprland/assets/107557749/1c04bb9e-12b3-4875-92b9-21c23c6eec15)

_No response_

**Comment by vaxerski** [comment]
fixed in git
