### ISSUE TITLE
Some Wayland games unable to capture mouse clicks

### ISSUE THREAD

**Issue by Fxzzi** [hyprwm/Hyprland#6280]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: Kappa
Release: 6.9.2-zen1-1.1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 26 May 2024 20:42:15 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070] [10de:2484] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

I've tested 3 games, mainly Minecraft: Java Edition, osu!lazer, and Cemu Emulator. When running all 3 under a native backend, Minecraft and Cemu do not respond to mouse clicks, and even to hovering over buttons it doesn't highlight them. With osu!lazer, my mouse just doesn't move at all.

This is a regression between hyprland 0.40.0 and -git.

### How to reproduce

Minecraft:

- https://github.com/BoyOrigin/glfw-wayland use this and run 1.19+ with it

osu!lazer:

- run with envvar `SDL_VIDEODRIVER=Wayland`

Cemu:

- run with envvar `GDK_BACKEND=wayland`

Observe in all 3 games that you are unable to click any buttons or interact at all with the window with your mouse, and for osu!lazer your mouse may even be stuck in place.

**Comment by vaxerski** [comment]
can ya bbbbisectt

**Comment by Fxzzi** [comment]
> can ya bbbbisectt

Yup, here's the info I got:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
0cfdde3d1acbfbf698af17f6986fbc4d644214da
121d3a72137d4780602cf245704615f63357ea22
fc72df8e58bc127442a245f2f29a3246acf77cce
We cannot bisect more!
```

was unable to test these 3 commits due to simply being unable to open any programs or do anything within Hyprland. Let me know if you need any more info!

**Comment by vaxerski** [comment]
likely seat then, ping me after #6268 is merged please, I'll test this when I am back on my pc

**Comment by Fxzzi** [comment]
@vaxerski 👋🏾

**Comment by vaxerski** [comment]
I'll add this to my 0.41 blockers list to be looked at after the aforementioned mr is done

**Comment by Fxzzi** [comment]
> can you test latest git

fixed, thank you!!
