### ISSUE TITLE
Popup blur no longer working

### ISSUE THREAD

**Issue by mewoocat** [hyprwm/Hyprland#6282]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ca17a89d86b73f37019c4cc0c7087303adbcc1f9  ().
Date: 2024-03-25
Tag: 

flags: (if any)


System Information:
System name: Linux
Node name: scythe
Release: 6.6.32
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat May 25 14:22:56 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240529.ad57eef"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuña)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuña)"
VERSION_CODENAME="vicuña"
VERSION_ID="24.11"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

I found that starting at this commit (https://github.com/hyprwm/Hyprland/commit/ca17a89d86b73f37019c4cc0c7087303adbcc1f9),  Popup blur no longer works.  I have a GTK Menu right click popup in AGS that blurs just fine on the commit right before but is transparent without blur starting at this commit.  This menu is a `dbusmenugtk3.menu`.   It seems that not everyone has this issue so it may be an edge case related to something in my config.  But since this used to work just fine, it appears as a regression.  However, I noticed that popup menus in other GTK apps such as Thunar, blur just fine.

### How to reproduce

Build Hyprland with this commit https://github.com/hyprwm/Hyprland/commit/ca17a89d86b73f37019c4cc0c7087303adbcc1f9 
and
AGS config: https://github.com/mewoocat/NixOS/tree/main/home-manager/ags
Hyprland config: https://github.com/mewoocat/NixOS/blob/main/home-manager/programs/hyprland/hyprland.conf

**Comment by vaxerski** [comment]
with the commit IIRC you need to separately enable blur for layers with layerrules.

**Comment by mewoocat** [comment]
The popup menu doesn't appear as a layer to blur.  Note that bar is already blured.

https://github.com/hyprwm/Hyprland/assets/97066700/8ea970bd-a3e2-4b56-83d0-46e00738a8dc

**Comment by vaxerski** [comment]
there is a separate layerrule for the parent to have its popups blurred, iirc

**Comment by mewoocat** [comment]
Oh, I never noticed that.  Works perfect now.
