### ISSUE TITLE
Crash on startup :(

### ISSUE THREAD

**Issue by mcst12345** [hyprwm/Hyprland#6286]
### System Info and Version

<details> <summary>System/Version info</summary>

Hyprland received signal 6(ABRT)
Version: df6ebe358b30ee7b49f296e05763e5e4b0edce98
Tag: v0.40.0-145-gdf6ebe35

System info:
	System name: Linux
	Node name: Kanade
	Release: 6.6.32-1-lts
	Version: #1 SMP PREEMPT_DYNAMIC Sat, 25 May 2024 20:20:51 +0000

GPU:
	0a:00.0 VGA compatible controller [0300]: Matrox Electronics Systems Ltd. G200eR2 [102b:0534] (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo

</details>

### Bug or Regression?

Bug

### Description

Crash on startup.
I have tried manual build and legacy render,nothing helped.
Neither of starting from tty or ssh worked.

### How to reproduce

![Screenshot_2024-05-31-20-25-20-876_com server auditor ssh client](https://github.com/hyprwm/Hyprland/assets/90134069/01c0f6dd-7446-4552-9dd4-b0933b722aba)
![Screenshot_2024-05-31-20-10-05-199_com server auditor ssh client](https://github.com/hyprwm/Hyprland/assets/90134069/f1ab0479-02c2-495b-b968-fe6f95816a17)

### Crash reports, logs, images, videos

[hyprlandCrashReport17465.txt](https://github.com/user-attachments/files/15513506/hyprlandCrashReport17465.txt)
[hyprland.conf.txt](https://github.com/user-attachments/files/15513536/hyprland.conf.txt)
[environment.txt](https://github.com/user-attachments/files/15513538/environment.txt)

**Comment by vaxerski** [comment]
this looks like android? Such setups are not officially supported, and this error is from wlroots
