### ISSUE TITLE
Random crashes.

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#6288]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit db5d39a66f1285f78321d953eac398feaedfc63d  (meson: add more xcb-* dependencies after addd3e7f1aeb).
Date: Mon May 27 11:24:37 2024
Tag: v0.40.0-138-gdb5d39a6, commits: 4744

flags: (if any)


System Information:
System name: Linux
Node name: beast
Release: 6.9.2-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:09 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev df) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Bug or Regression?

Regression

### Description

I have been getting some random crashes lately. 

No pressure Vaxerski, look at this whenever you feel like it, enjoy your time in the mountains.

Thanks.

### How to reproduce

Using the computer as normal, nothing in particular, getting crashes when using any random program at any random moment. 

I have attached the two latest crash reports: one when using alacritty, other when using QPass. If you want a debug stacktrace or something just call.

### Crash reports, logs, images, videos

[hyprlandCrashReport869.txt](https://github.com/user-attachments/files/15516706/hyprlandCrashReport869.txt)
[hyprlandCrashReport1191.txt](https://github.com/user-attachments/files/15516670/hyprlandCrashReport1191.txt)

**Comment by Aqa-Ib** [comment]
The QPass crash is not random at all, it is fully reproducible 100% of the times.

**Comment by vaxerski** [comment]
I feel like I fixed that, that it's a dupe of some other issue.  If you are 100% on latest, please get a debug coredump

**Comment by Aqa-Ib** [comment]
yeah, it was fixed 6 commits after my build's. You are fast :)
