### ISSUE TITLE
Ubuntu PPA to docs

### ISSUE THREAD

**Issue by cpiber** [hyprwm/Hyprland#6290]
### Description

Currently there is not good way to install Hyprland on Ubuntu. Due to this, I have recently created a PPA which packages git master and stable: https://launchpad.net/~cppiber/+archive/ubuntu/hyprland In case someone else needs convenient packages. Maybe you want to add it to the installation docs.

P.S.: Since https://github.com/hyprwm/Hyprland/commit/addd3e7f1aeb670dd91d26005aaeccce3efb1ae7 the libxcb-errors is actually required, since you use the header indiscriminately: https://github.com/hyprwm/Hyprland/blob/a60c7283e677ed81a466d1c0c864c8a05e192cac/src/xwayland/XWM.hpp#L10
The CMakeLists.txt still lists the package as optional, though meson seems updated.

P.P.S.: I'm using a Nvidia eGPU, which caused a black screen on the Laptop. It seems on Ubuntu `libnvidia-egl-wayland1` and `libnvidia-egl-gbm1` are not automatically included with the driver, which causes wlroots to fall back to zink (Vulkan), which causes errors when trying to get the pixel format of the monitor.

**Comment by vaxerski** [comment]
oops, I'll make it required. Thanks.

**Comment by vaxerski** [comment]
regarding nvidia/ubuntu, both are on you to figure out. I can't support nvidia, and I dont use ubuntu and cant support it either as its a mess with dependencies

**Comment by cpiber** [comment]
That is clear, I just wanted to suggest that you could add it to the wiki page, but apparently I accidentally deleted the last sentence, sorry about that

**Comment by vaxerski** [comment]
wiki is under hyprland-wiki and you can make a MR there :)
