### ISSUE TITLE
Nothing happens when I type Hyprland in terminal

### ISSUE THREAD

**Issue by PrathmeshVishwakarma** [hyprwm/Hyprland#6291]
same as title, I just installed hyprland through yay and pacman same result for both. thanks

**Comment by fufexan** [comment]
Very descriptive. Now please fill in the issue properly, or it will be closed.

**Comment by PrathmeshVishwakarma** [comment]
> Very descriptive. Now please fill in the issue properly, or it will be closed.

there is no such description sir, no error nothing. It goes onto a new line. Thats why I am clueless.
I am using Vmware and Hyprland 0.40.0
Also please tell what more details you need sir

**Comment by PrathmeshVishwakarma** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/170882272/05274584-ab04-44eb-8b2d-425427605f5c)

**Comment by fufexan** [comment]
When you clicked `New issue`, it showed you two types of issues, Bug or Regression. You should have clicked on Bug.

Anyway, check whether you have any logs in `$XDG_RUNTIME_DIR/hypr`, or crash reports in `$XDG_CACHE_HOME/hyprland`.

If there's nothing there, check `which Hyprland`.

**Comment by PrathmeshVishwakarma** [comment]
> When you clicked `New issue`, it showed you two types of issues, Bug or Regression. You should have clicked on Bug.
Sorry for that, should I do it now?
> Anyway, check whether you have any logs in `$XDG_RUNTIME_DIR/hypr`, or crash reports in `$XDG_CACHE_HOME/hyprland`.
Its saying No such file or directory
> If there's nothing there, check `which Hyprland`.
Its in /usr/bin/Hyprland

**Comment by yashlala** [comment]
@PrathmeshVishwakarma Your environment likely hasn't set the `XDG` variables, which complicates getting the logs. Please check `~/.local/share/hypr` and `~/.cache/hyprland` for logs. 

As you learn, it helps to google these things so you can debug issues. For example: googling `$XDG_RUNTIME_DIR` will reveal that it's a variable that _defaults_ to `~/.local/share`. From here, you can check those directories yourself.

**Comment by fufexan** [comment]
> For example: googling `$XDG_RUNTIME_DIR` will reveal that it's a variable that _defaults_ to `~/.local/share`.

No, that's `$XDG_DATA_HOME`.

**Comment by yashlala** [comment]
Yep, I mixed it up :'). Hopefully the idea is still clear.

**Comment by vaxerski** [comment]
invalid issue, please follow the templates. Furthermore, vms are not supported
