### ISSUE TITLE
Crash Hyprland

### ISSUE THREAD

**Issue by VDFOREVER** [hyprwm/Hyprland#6293]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: void
Release: 6.9.3_1
Version: #1 SMP PREEMPT_DYNAMIC Thu May 30 22:21:45 UTC 2024


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes at random times, I can play and work, before this my hyprland just froze when I tried to switch workspace during the game

### How to reproduce

I don't know... it happens randomly

### Crash reports, logs, images, videos

[hyprlandCrashReport1058.txt](https://github.com/user-attachments/files/15518260/hyprlandCrashReport1058.txt)

**Comment by VDFOREVER** [comment]
Here is another log where hyprland crashed
[hyprlandCrashReport1054.txt](https://github.com/user-attachments/files/15518317/hyprlandCrashReport1054.txt)

**Comment by vaxerski** [comment]
please try on git
