### ISSUE TITLE
`group:groupbar:stacked` and Other Variables "Do Not Exist"; Documentation Ambiguity

### ISSUE THREAD

**Issue by brosasaki** [hyprwm/Hyprland#6296]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: ngworks
Release: 6.8.10
Version: #1 SMP PREEMPT_DYNAMIC 1


GPU information: 


os-release: NAME="Guix System"
ID=guix
PRETTY_NAME="Guix System"
LOGO=guix-icon
HOME_URL="https://guix.gnu.org"
DOCUMENTATION_URL="https://guix.gnu.org/en/manual"
SUPPORT_URL="https://guix.gnu.org/en/help"
BUG_REPORT_URL="https://lists.gnu.org/mailman/listinfo/bug-guix"


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Trying to set `group:groupbar:stacked`, `misc:col.splash`, and likely other variables results in an error message stating that these don't exist, despite them being documented in the wiki. However, these variables do exist in the source code, and there is nothing in the release notes suggesting that they would be missing from the version installed. I suspect this to be a bug, and not a version difference.

Aside from this, I am curious, why is an online wiki used instead of "on-board" documentation, which would be synchronized with the installed version? If you would like, I can port the wiki to info, which has hyperlinks, formatting, etc, or to manpages, if you insist, and submit a PR. Correct, offline documentation is a common feature of a lot of great software, and is worth the extra barrier to edit (which, arguably, is a benefit).

### How to reproduce

Try to set group:groupbar:stacked or misc:col.splash.

**Comment by MightyPlaza** [comment]
likely old version + wiki version on git

**Comment by vaxerski** [comment]
literally above

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/67f578d0-5dd6-44c2-be9b-3d996a4c6b52)
