### ISSUE TITLE
binds don't take device's `kb_variant` into account

### ISSUE THREAD

**Issue by Diaoul** [hyprwm/Hyprland#6297]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: mars
Release: 6.9.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

Config (relevant parts):
```
device {
  name = at-translated-set-2-keyboard
  kb_variant = colemak_dh
  kb_options = grp:alt_shift_toggle,caps:escape,compose:ralt
}

bind = SUPER,F,fullscreen,1
```

</details>

### Bug or Regression?

Bug

### Description

binds don't seem to take device's `kb_variant` into account

I'm using Colemak for the built-in keyboard of the laptop.
With the config attached:
- Pressing `SUPER + F` (in colemak, so E in qwerty) does nothing
- Pressing `SUPER + F` (in qwerty, so T in colemak) works

### How to reproduce

Use my config with your own keyboard name

**Comment by gksudolol** [comment]
Try `bind = SUPER SHIFT,f,fullscreen,1` fellow colemak user

**Comment by tkrzepka** [comment]
this seems strangely similar to the "issue" that i had, check out this comment
https://github.com/hyprwm/Hyprland/issues/6276#issuecomment-2139448874

**Comment by gksudolol** [comment]
> this seems strangely similar to the "issue" that i had, check out this comment [#6276 (comment)](https://github.com/hyprwm/Hyprland/issues/6276#issuecomment-2139448874)

i missed the part about multiple devices oops, sorry!

**Comment by vaxerski** [comment]
as above, rtfm
