### ISSUE TITLE
Add option to `hyprctl rollinglog` to follow the Hyprland logs

### ISSUE THREAD

**Issue by zjeffer** [hyprwm/Hyprland#6300]
### Description

Right now, to follow the current logs, I run `tail -f $XDG_RUNTIME_DIR/hypr/<id>/hyprland.log`. I notice `hyprctl rollinglog` is able to show the last 50-ish lines, but not able to follow the logs. 

Proposal: add a parameter (-f, --follow) to `hyprctl rollinglog` that follows the output similar to `tail -f <file>`.

**Comment by Truenya** [comment]
Can i try this?

**Comment by tchofy** [comment]
Honestly I'd be in favor of rollinglog follow by default, and optionally have a tail flag if someone has an use for it.
From the name I'd expect _rolling_ log to be rolling, so that seems more intuitive for me.

**Comment by Truenya** [comment]
@tchofy I think similarly, but as for me it is more correct to preserve the existing behavior(it is my first PR here).

**Comment by Truenya** [comment]
@zjeffer i think issue can be closed as for now

**Comment by zjeffer** [comment]
Yes, thank you very much!
