### ISSUE TITLE
Floating window for Bitwarden on Chrome

### ISSUE THREAD

**Issue by rdmccray** [hyprwm/Hyprland#6302]
### System Info and Version

hyprctl systeminfo
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.9.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000

GPU information:
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6950 XT] [1002:73a5] (rev c0) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Bug or Regression?

Bug

### Description

Given this:

Window 61a41348ed00 -> Bitwarden:
mapped: 1
hidden: 0
at: 1261,740
size: 1277,678
workspace: 1 (1)
floating: 0
monitor: 0
class: chrome-nngceckbapebfimnlniiiahkandclblb-Default
title: Bitwarden
initialClass: chrome-nngceckbapebfimnlniiiahkandclblb-Default
initialTitle: _crx_nngceckbapebfimnlniiiahkandclblb
pid: 5740
xwayland: 0
pinned: 0
fullscreen: 0
fullscreenmode: 0
fakefullscreen: 0
grouped: 0
swallowing: 0
focusHistoryID: 1

This works: windowrulev2 = float,class:^(chrome-[A-Za-z]±[A-Za-z]+)$

This does not: windowrulev2 = float,class:^(chrome-[A-Za-z]±[A-Za-z]+)$,title:^(Bitwarden)$

What am I missing?

### How to reproduce

1. Be user of Bitwarden
2. Pick a web site where you can use Passkeys (Amazon works)
3. Be sure to have logged out of amazon.com prior
4. Verify the rule with the title match is in effect.
5. Attempt to log into amazon.com
6. Select use passkey
7. run hyprctl clients and check the "floating" line

**Comment by MightyPlaza** [comment]
float is not dynamic so it matches `initialTitle` and not `title`

**Comment by vaxerski** [comment]
basically

**Comment by erahhal** [comment]
What does "float is not dynamic" mean? Does it mean that "float" rules only work when a window is first created?  And if so, why is it not dynamic?

**Comment by vaxerski** [comment]
> "float" rules only work when a window is first created 

yes.

because thats how it works

**Comment by erahhal** [comment]
Sure, it's clear that's how it works. I'm just trying to understand why it's designed that way. If float rules always work instead of just at window creation, what problems arise? Apologies if this is documented somewhere already.

**Comment by vaxerski** [comment]
that's just how we wrote them, thats it. One issue could be someone adding a float rule for a window title and being confused it suddenly tiles because the app decided to change its title.

**Comment by erahhal** [comment]
Got it, I can see that logic. Is there a mechanism for floating based on title rather than initialTitle?  If not,. prhaps a bit of user confusion might be worth making something possible at all. Unless I am missing some other constraint.

**Comment by vaxerski** [comment]
write a script

**Comment by erahhal** [comment]
Already have.  It would be a lot easier to use a windowrule tho.

Is this something you are philosophically opposed to, or would it be considered as a future feature if I opened a request?

**Comment by jesusfl15** [comment]
I know it's quite late but i think this may be useful to users searching about this issue in the future:
You may not need a script for bitwarden on chromium-based browsers, just change your title from `^(Bitwarden)$` to something like `(?i).*nngceckbapebfimnlniiiahkandclblb.*`, this is Bitwardens' extension ID, you can see it in the initialTitle section with `hyprctl activewindow` and it _shouldn't_ change in the near future.
