### ISSUE TITLE
Any text copied from xwayland apps are gone after it's closed

### ISSUE THREAD

**Issue by glyh** [hyprwm/Hyprland#6305]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0ebb43c1a37e7321e5ed7223ea85ed555cc82735  (renderer: fix xwayland solitary rechecks (6295)).
Date: Sun Jun 2 02:45:30 2024
Tag: v0.40.0-147-g0ebb43c1, commits: 4753

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

I can't paste once a X-app is closed.

### How to reproduce

1. Install `hyprland-git` from AUR
2. Open any X11 apps, copy from it
3. Don't close the app, paste, it works
4. Copy anything from the X11 app and close the app
5. Paste, it won't work.

**Comment by vaxerski** [comment]
kinda expected. You'll need to use a clipboard manager of some sort to preserve clipboard after app close.

**Comment by glyh** [comment]
Is there any candidate for Hyprland? I tried copyq but it's buggy on HyprLand and it toggles my window every 400ms or so.
