### ISSUE TITLE
opening imv crashes hyprland

### ISSUE THREAD

**Issue by alexmo1997** [hyprwm/Hyprland#6307]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: envy
Release: 6.9.3-hardened1-1-hardened
Version: #1 SMP PREEMPT_DYNAMIC Sat, 01 Jun 2024 00:25:24 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a1] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

[hyprland.conf](https://github.com/user-attachments/files/15525290/hyprland-conf.txt)

### Bug or Regression?

Bug

### Description

Somehow opening imv sometimes crashes hyprland, I've found it to work more consistently if you reduce the amount of env variables?

### How to reproduce

`env -i WAYLAND_DISPLAY=wayland-2 XDG_RUNTIME_DIR=/run/user/1000 imv-wayland ~/pic/lock.png`

### Crash reports, logs, images, videos

[hyprlandCrashReport346825.txt](https://github.com/user-attachments/files/15525295/hyprlandCrashReport346825.txt)

**Comment by MightyPlaza** [comment]
is it fixed on git?

**Comment by alexmo1997** [comment]
It seems so. After I bit of testing I couldn't get it to crash again there.
