### ISSUE TITLE
apply no_gaps_when_only to groups reloaded

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#631]
Concratulations, under 50 issues again! 
Let's do something about that!
Since i cannot reopen https://github.com/hyprwm/Hyprland/issues/603 ,this is just to make shure you don't forget about the problem described in the last comment.

**Comment by vaxerski** [comment]
fixed in 4a8274e5f0d6c48cf83cfdc83ecd1a02225b90e2

**Comment by Dickby** [comment]
Now that was fast!
Impressive, thanks!
