### ISSUE TITLE
Floating windows do not spawn centered

### ISSUE THREAD

**Issue by MightyPlaza** [hyprwm/Hyprland#6316]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Regression

### Description

Since one of 0cfdde3d1acbfbf698af17f6986fbc4d644214da 121d3a72137d4780602cf245704615f63357ea22 fc72df8e58bc127442a245f2f29a3246acf77cce 7eeee2c94e882a5df1914234df0571b221f9aa35, floating windows do not spawn centered anymore.
Additionally, they always seem to spawn at X = width / 2 and Y = height / 2.

### How to reproduce

Spawn a floating window on main

**Comment by vaxerski** [comment]
#6154
