### ISSUE TITLE
Rofi crash

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6318]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 358e59e69d27a69381bc0872b5b8d1184bc6b6a1 dirty (layout: fix centering of new floating windows).
Date: Mon Jun 3 05:11:55 2024
Tag: v0.40.0-150-g358e59e6, commits: 4756

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.9.3-1-cachyos-echo-lto
Version: #1 SMP PREEMPT_DYNAMIC Thu, 30 May 2024 19:14:38 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Use the latest commit, use Hyprland for some time, rofi will crash, just start Hyprland when rofi works!

### How to reproduce

1. Install rofi-lbonn-wayland-git 
2. Use Hyprland for some time
3. Use rofi will crash

### Crash reports, logs, images, videos

[rofi_coredumpctl.log](https://github.com/user-attachments/files/15528522/rofi_coredumpctl.log)

**Comment by MightyPlaza** [comment]
is this a regression?
if so please bisect

**Comment by vaxerski** [comment]
no debug symbols but looks similar to something like #6310 ?

**Comment by hdm9527** [comment]
> no debug symbols but looks similar to something like #6310 ?

Under certain circumstances rofi crashes, testing rofi at intervals, rofi goes from working -> crash -> work, can't pinpoint what makes rofi crash at the moment.

**Comment by vaxerski** [comment]
can you try to bisect?

**Comment by hdm9527** [comment]
> can you try to bisect?

Going back to a previous version of hyprland that worked fine also had this problem.

Output when rofi crashes
```sh
listener function for opcode 1 of wl_data_device is NULL
[1]    126309 IOT instruction (core dumped)  rofi
```

Re-grabbed a copy of the backtrace with debug symbols. 
[rofi_coredumpctl.log](https://github.com/user-attachments/files/15574146/rofi_coredumpctl.log)

**Comment by vaxerski** [comment]
sounds like a rofi bug tbh... though looking at the source it is non-null:
![image](https://github.com/hyprwm/Hyprland/assets/43317083/244b449c-073f-49f6-99ed-bacb01aaed89)

perhaps it wasnt set for some reason?

**Comment by hdm9527** [comment]
> sounds like a rofi bug tbh... though looking at the source it is non-null: ![image](https://private-user-images.githubusercontent.com/43317083/336927519-244b449c-073f-49f6-99ed-bacb01aaed89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODUyNTIsIm5iZiI6MTcxNzY4NDk1MiwicGF0aCI6Ii80MzMxNzA4My8zMzY5Mjc1MTktMjQ0YjQ0OWMtMDczZi00OWY2LTk5ZWQtYmFjYjAxYWFlZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE0NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYmM2MjgwMThjZDFlZDY0NDMzMGQ4NmJiOTk2MTY4ZTA0NzcyMzRkNmFhMWZkNDRmN2YxMmRiMDUxODE3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BQQx1exXK4fbIsMVDnRE4azLE5GJsJVKwevL0sEk99s)
> 
> perhaps it wasnt set for some reason?

Clicking on the tray icon always opens wechat, which is why waybar causes rofi to crash, after restarting waybar rofi works fine. waybar doesn't have cordumpctl log.

https://github.com/hyprwm/Hyprland/assets/39702328/984cbe37-adcc-4b2c-bcf2-462046bd2170

**Comment by hdm9527** [comment]
This commit 6967a31450441fc5605c05db6f65505dace4b263 seems to fix rofi crash issue. It's working fine.

**Comment by hdm9527** [comment]
I'll grab a new log later.

**Comment by hdm9527** [comment]
> I'll grab a new log later.

[waybar_coredumpctl.log](https://github.com/user-attachments/files/15823165/waybar_coredumpctl.log)
[rofi_coredumpctl.log](https://github.com/user-attachments/files/15823168/rofi_coredumpctl.log)

**Comment by hdm9527** [comment]
> It has started happening to me recently. And, I noticed something about it. (maybe)
> 
> 1. It always seems to happen after X program is started.
> 2. Regardless of the value of `follow_mouse`, Hyprland behaves like `1`.

The rofi hasn't crashed lately, what is your hyprland version?

**Comment by hdm9527** [comment]
> > > It has started happening to me recently. And, I noticed something about it. (maybe)
> > > 
> > > 1. It always seems to happen after X program is started.
> > > 2. Regardless of the value of `follow_mouse`, Hyprland behaves like `1`.
> > 
> > 
> > The rofi hasn't crashed lately, what is your hyprland version?
> 
> ```
> ArchLinux: 6.9.5-zen1-1-zen
> Hyprland: 0.41.1-1
> rofi-wayland: 1.7.5+wayland3-2
> ```

It should be fixed in git.
