### ISSUE TITLE
apply no_gaps_when_only to groups re-reloaded 

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#632]
Now the windows "in the middle" get gaps.
Reproduce with:
open 3 windows on an empty workspace,
group all of them together -> no gaps
kill the fullscreen window -> gaps
kill the new fullscreen window -> not gaps

I think the guard around the new recalculateMonitor call is causing that,
but you'll know better.

**Comment by vaxerski** [comment]
fixed in 789eedd115917bc0ae7e5ee7317af67295439fd8
