### ISSUE TITLE
Inconsistent cursor size

### ISSUE THREAD

**Issue by Xygyl** [hyprwm/Hyprland#6320]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: syn-2603-8080-3200-1fef-0000-0000-0000-168e.res6.spectrum.com
Release: 6.6.30-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Thu May 23 11:46:34 CDT 2024


GPU information: 
c1:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

My cursor changes size when it's placed over certain parts of the Steam and Firefox UIs. It also changes size when playing any type of game (either with proton via Steam like with Minecraft).

Firefox doesn't have this issue when nwg-look is used with HYPRCURSOR_THEME and HYPRCURSOR_SIZE, though the issue persists with Steam and games.

### How to reproduce

Playing any game and placing cursor over certain Steam UI parts.

### Crash reports, logs, images, videos

![4](https://github.com/hyprwm/Hyprland/assets/103771423/b2368a54-823d-4a68-ae27-cf6ecbd562bc)
![3](https://github.com/hyprwm/Hyprland/assets/103771423/d731a3f1-c464-442c-b758-ab44e4496049)
![2](https://github.com/hyprwm/Hyprland/assets/103771423/482363e4-90f3-44e0-bceb-09801fcf266e)
![1](https://github.com/hyprwm/Hyprland/assets/103771423/397f24f9-3ac6-44d8-b25c-d7040ae7874e)
[hyprland.txt](https://github.com/user-attachments/files/15529099/hyprland.txt)

I'm sorry for taking pictures instead of screenshots — I'm still trying to figure out grim and slurp. All pictures were taken from the same distance to demonstrate cursor size changes.

**Comment by vaxerski** [comment]
sad reality of cursors on linux. https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/

play with xcursor_size until it's good enough

**Comment by Xygyl** [comment]
I tried to use a different cursor and now the cursor is distorted. Is this an issue with converting xcursors to hyprcursors?
![2](https://github.com/hyprwm/Hyprland/assets/103771423/ca5caa83-8323-4131-a874-1cbf2c305d13)
![1](https://github.com/hyprwm/Hyprland/assets/103771423/783b8e53-633b-4dab-b047-dd57164eb245)

**Comment by vaxerski** [comment]
converting xcursors to hyprcursors with the util works 90% of the time without issues. For best result, you should manually replace pngs with svgs. You can also use a pre-made theme, of course.

Try using `hyprctl setcursor`, or in your config `env = XCURSOR_SIZE,24` (24 or any other size)

**Comment by Xygyl** [comment]
To ensure that I don't take up too much of your time and to give you the full context of the problem, here's the full scope of the issue:

I'm using _phinger-cursors-dark_ from [https://github.com/phisch/phinger-cursors](url). I changed it into hyprcursors via `hyprcursor-util -x phinger-cursors-dark` and `hyprcursor-util -c extracted_phinger-cursors-dark`. The hyprcursors were renamed to "phinger-cursors" and the xcursors to "phinger-cursors-X" (not just the directories, but in manifest.hl and index.theme). I placed both in ~/.icons and ~/.local/share/icons so that I can be sure that there are no discrepancies.  

These lines are in my hyprland.conf:

`env = HYPRCURSOR_THEME,phinger-cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,phinger-cursors-X
env = XCURSOR_SIZE,24`

`env = XCURSOR_SIZE,24` doesn't fix the distortion nor the size issues. `hyprctl setcursor phinger-cursors-X 24` sets the cursor to a small adwaita cursor. `hyprctl setcursor phinger-cursors 24` has the same distortion issue. 

It seems that the distortion is a problem with the xcursor to hyprcursor issue, but none of this addresses the size issue. 

It's likely that I did something wrong due to this being my first venture into hyprland, though I'm not sure where that could be.

**Comment by vaxerski** [comment]
distortion is IIRC a reported issue in hyprcursor, it's a bug in the util I believe. Try some of the SVG themes from the #hyprcursor-themes channel in discord.

**Comment by Xygyl** [comment]
I'll try that, thank you. Is there anywhere else I can get feedback on this problem? I tried posting about it in the discord but I have yet to get a reply. I feel bad bothering the lead dev with such a mundane problem.

**Comment by Xygyl** [comment]
This problem just keeps getting more complicated. I set my theme to [https://github.com/ndom91/rose-pine-hyprcursor](url) and now hyprpaper doesn't work. My cursor is now different for my desktop, firefox, and steam. The small cursor and big cursor on steam have different themes (in a different permutation than before, but that's unneeded context). I think the actual solution is to not use hyprland since  nothing seems to solve this problem. Unless you have any ideas or anyone else I can talk to about this, I think that I'm just going to try a different wm.

**Comment by vaxerski** [comment]
you can also not use hyprcursor. I feel like this is a misconfiguration of some sort on your end though as it seems to work just fine for me and many others

**Comment by Xygyl** [comment]
I just tried using just xcursor without making any changes to anything else, but it's distorted, which makes me think that the original distortion isn't because of hyprcursor-util. At this point I'm just confused, and the lack of help (not referring to you) or documentation is making this increasingly frustrating.

**Comment by nktnet1** [comment]
I had a similar issue as [this Reddit post here](https://www.reddit.com/r/hyprland/comments/1dgmg4w/cursor_size_smaller_on_desktop_than_everywhere/), where the
> cursor size smaller on desktop than everywhere else

A related issue might be "Cursor size with HiDPi #2448"

The most consistent way I've managed to get the cursors working is to install a cursor theme that exists for both XCursor and Hyprcursor, then set their sizes with nwg-looks and in hyprland config.

For example, choosing rose-pine cursor on Arch linux (just so the instructions can be simplified using an AUR helper), here are the steps:

1. Install [rose-pine/cursor](https://github.com/rose-pine/cursor) from the AUR:

    ```sh
    yay -S rose-pine-cursor
    ```
2. Install [rose-pine-hyprcursor](https://github.com/ndom91/rose-pine-hyprcursor) from the AUR:

    ```sh
    yay -S rose-pine-hyprcursor
    ```

3. Install [nwg-look](https://github.com/nwg-piotr/nwg-look)
    
    ````sh
    yay -S nwg-look
    ````

4. Open nwg-look and set your preferred Xcursor and size:

    ![nwg-look-settings](https://github.com/user-attachments/assets/1729bf4b-2595-4361-9480-f7164f45354b)


5. Open your `~/.config/hypr/hyprland.conf` and use the same configuration for Hyprcursor:
    ```
    env = HYPRCURSOR_SIZE,28
    env = HYPRCURSOR_THEME,rose-pine-hyprcursor
    ```

6. Either reboot or restart Hyprland

**Comment by HK-Sepuri** [comment]
https://github.com/hyprwm/Hyprland/issues/6320#issuecomment-2243109637

This worked !!, so i need to find xcursor theme of same hyprcursor theme got it ! Thank you :)

**Comment by xdevs23** [comment]
> The most consistent way I've managed to get the cursors working is to install a cursor theme that has both Xcursor and Hyprcursor variants, then set their sizes using nwg-look and in hyprland environment variables respectively.
>

Finally a solution for this that has been haunting me ever since.

**Comment by KukicVidan** [comment]
or just : https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/
