### ISSUE TITLE
wlr_backend_autocreate()  failed err on amd GPU

### ISSUE THREAD

**Issue by vaibd** [hyprwm/Hyprland#6324]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: battlestation
Release: 6.6.32
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat May 25 14:22:56 UTC 2024


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c0) (prog-if 00 [VGA controller])
13:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240531.805a384"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

I'm using nixOS, ever since I switched to v24.05, hyprland(v0.40.0-unstable-2024-05-05) freezes on login screen for 5sec then throws me back to login screen(lightdm), everything was working fine on v0.32.3.

I tried rolling back hyprland to v0.32.3 and it works fine, so I'm guessing v0.40 broke something?
Also, if I launch v0.40 manually from tty it works fine.

 

### How to reproduce

Use v0.40 with nixOS  v24.05

### Crash reports, logs, images, videos

[hyprlandCrashReport1517.txt](https://github.com/user-attachments/files/15535794/hyprlandCrashReport1517.txt)

**Comment by MightyPlaza** [comment]
does using a tty instead of lightdm work?

**Comment by vaibd** [comment]
> does using a tty instead of lightdm work?

Yes

**Comment by vaxerski** [comment]
then it's a lightdm issue kek
