### ISSUE TITLE
KDE Connect | Remote access doesn't work

### ISSUE THREAD

**Issue by levitskyyy** [hyprwm/Hyprland#6330]
### System Info and Version

<details> <summary>ArchLinux</summary>
hyprland 0.40.0, kdeconnect 24.05.0
</details>

### Bug or Regression?

Bug

### Description

Remote access with KDE Connect is not working. Everything works except controlling the computer from the phone.

### How to reproduce

1. Install KDE Connect, hyprland
2. Try remote input

**Comment by vaxerski** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/70 https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/64
