### ISSUE TITLE
"fullscreen" image sometimes used instead of the background image

### ISSUE THREAD

**Issue by fdev31** [hyprwm/Hyprland#6332]
### System Info and Version

I don't think the config or the version is relevant here, it happens since a very very long time but I can't figure what is the trigger, so I'll just describe the behavior as well as I can.

### Bug or Regression?

Bug

### Description

On rare occasions, instead of the (optionally blurred) background image, tiled clients will show a wrong image as the background.

As if a screenshot of the previously displayed screen was used as the background, while the directly visible parts of the background are showing the correct image.

### How to reproduce

This is rare but when happens it persists:

- playing a youtube video fullscreen on any web browser may trigger the bug (ff or chrome) (may happen in other cases but I'm not 100% confident)
- transparent windows WHICH ARE TILED get a random image from the video as the transparent background instead of the currently available background
- making the window floating fixes the issue, disabling floating produces the problem again

> [!note]
> - changing the wallpaper "fixes" the issue
> - floating windows aren't affected by this bug

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/238622/1995fce0-4a69-4479-a973-d52b3d85633b)

**Comment by vaxerski** [comment]
unless you can reproduce this I have no way of fixing it

**Comment by cdubthecoolcat** [comment]
I'm able to reproduce this on both nvidia and intel systems with these steps:

1. fullscreen firefox (was only able to reproduce with firefox so it might be a firefox bug)
2. change wallpaper while firefox is still fullscreen (reproduced with both wpaperd and swww)
3. unfullscreen
4. open tiled transparent window (reproduced with kitty and foot)

**Comment by fdev31** [comment]
> fullscreen firefox (was only able to reproduce with firefox so it might be a firefox bug)

I switched to firefox (again) a couple of months ago, but this bug is more old than this, I can tell 100% it happens with chrome-based browsers too.

**Comment by vaxerski** [comment]
thanks for the repro @cdubthecoolcat :D
