### ISSUE TITLE
Hyprland crash using an Nvidia GPU

### ISSUE THREAD

**Issue by S1n1st3rn3ss** [hyprwm/Hyprland#6335]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: chiffa-desktop
Release: 6.6.32-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 25 May 2024 20:20:51 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] [10de:21c4] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2024.01.25"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Active Hyprland instance crashes on beta Nvidia 555 drivers. It might fully be an issue with beta drivers (probably is), but I felt like it may be worth reporting anyway

### How to reproduce

No exact steps, some circumstances around the crash:

1. Nvidia 555 beta drivers installed via https://github.com/Frogging-Family/nvidia-all
2. osu!lazer (SDL2-based game) running with `SDL_VIDEODRIVER = wayland` environmental variable
3. OBS running in the background

Can't narrow it down any further right now

### Crash reports, logs, images, videos

[hyprlandCrashReport773.txt](https://github.com/user-attachments/files/15569649/hyprlandCrashReport773.txt)
[hyprlandCrashReport5695.txt](https://github.com/user-attachments/files/15569651/hyprlandCrashReport5695.txt)
[hyprlandCrashReport7384.txt](https://github.com/user-attachments/files/15569653/hyprlandCrashReport7384.txt)

[hyprland.conf](https://github.com/user-attachments/files/15569671/hyprland.txt)

**Comment by vaxerski** [comment]
can you get a debug stacktrace?

**Comment by S1n1st3rn3ss** [comment]
Couldn't even properly run the compositor, `make asan` and any further attempts to run the build `Hyprland` binary don't even let it start, so these are the only logs I managed to get currently

[asan.zip](https://github.com/user-attachments/files/15570592/asan.zip)

**Comment by vaxerski** [comment]
update hyprwayland-scanner
