### ISSUE TITLE
wired  behavior about switch workspace 

### ISSUE THREAD

**Issue by sisyphusw** [hyprwm/Hyprland#6349]
hyprland version: `v0.39.1`

When config

> bind = SUPER,10, workspace, 10 
> bind = SUPER,11, workspace, 11 

then press

> `SUPER 1` will switch to workspace 10
> `SUPER 2` will switch to workspace 11

I don't know whether this is expected right behavior or not,  but what I expected is
> press `SUPER 1` will still switch to `workspace 1`,  even `bind = SUPER,10, workspace, 10 `  is set.

**Comment by vaxerski** [comment]
what?

You set a keybind for workspace 10, to SUPER + code 10, which on us is the 1 key. Everything is working as expected
