### ISSUE TITLE
hyprcursor only changes theme if size is changed

### ISSUE THREAD

**Issue by kerichdev** [hyprwm/Hyprland#6350]
hyprcursor fails to change the cursor theme if the size isnt changed to a diffrent one - discovered with catppuccin cursors.

`hyprctl setcursor theme 24` doesn't work, but `hyprctl setcursor theme 25`, and then repeating the last command will change the cursor theme.

`Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4`
`hyprcursor 0.1.9-1`

**Comment by fufexan** [comment]
Works fine on my end, built from af5f2492.

**Comment by kerichdev** [comment]
> this is a hyprland bug

it seems to be related to both hyprland and the cursors themselves, since after a cursor rebuild from xcursor, that issue is gone, as well as a few more, like weird quality degradation that was also present specifically on hypcursors.

**Comment by izmyname** [comment]
Can't repro. Works fine on the latest git

**Comment by vaxerski** [comment]
@kerichdev ?

**Comment by kerichdev** [comment]
Can't repro on latest release either, so looks like it's fixed
