### ISSUE TITLE
Bind description

### ISSUE THREAD

**Issue by Moerliy** [hyprwm/Hyprland#6357]
### Description

I'm bad at remembering key binds and was always a fan of nvim plugins like which key. For something like this, a way of describing your key binds is necessary.

My proposal would look something like this:
```conf
bind = SUPER, T, "open my terminal", exec, kitty
```
but obviously, it should be backward compatibl so this should also be no problem:
```conf
bind = SUPER, T, exec, kitty
```

Working with any bind the description would always come after the KEY (so at index 2) and the indicator would be double quotes. I think some kind of indicator is needed to distinguish it from the dispatcher options.

PR is a WIP

**Comment by fufexan** [comment]
I assume you want this to also be shown in `hyprctl binds`?

**Comment by Moerliy** [comment]
@fufexan 
Yeah, you're right. Do you know by any chance where the code for that would be? Haven't done anything with hyprctl yet and I can't find it except for the shell scripts.
