### ISSUE TITLE
Hyprland Crashes whenever lauching Kitty terminal

### ISSUE THREAD

**Issue by Rishik-Y** [hyprwm/Hyprland#6361]
### System Info and Version

System info:
	System name: Linux
	Node name: archlinux
	Release: 6.9.3-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000

GPU:
	07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c6) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo

### Bug or Regression?

Bug

### Description

Hyprland Crashes every time I open Kitty while some other application is open.

So, to better explain this,
You can easily run Kitty while no other application is running in the Windows manager

On the other hand, later, when I run Firefox (Firefox in 3 separate tabs but in the same workspace, let's say workspace 1) and then run Kitty, it lags for a few seconds and then runs without issue [In some cases, it crashes nonetheless]

But if I keep Firefox with 3 tabs in  3 different workspaces and then run Kitty, The Hyprland crashes immediately and sends me back to the login screen.

### How to reproduce

Run Firefox --> Run Kitty --> Hyprland Crashes --> Login again --> Repeat      

### Crash reports, logs, images, videos

[hyprlandCrashReport44086.txt](https://github.com/user-attachments/files/15744622/hyprlandCrashReport44086.txt)

**Comment by vaxerski** [comment]
can you get an ASan trace? https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by Rishik-Y** [comment]
I am really sorry, but I tried to do it, but unfortunately, I am just a pure nooby when it comes to this. (I just recently moved to Arch)

```
!!WARNING!!
Only run this in the TTY.
Refusing to run with Hyprland running.
make: *** [Makefile:88: asan] Error 1
```

But to let you know, the issue was easily resolved when I modified 

`#windowrule = tile, ^(kitty)$`

from 

`#windowrule = float, ^(kitty)$`

so Now it doesn't honestly crash, 
"Phew"
But it still lags for a couple of seconds to open kitty, 
It doesn't happen with any other application.

**Comment by vaxerski** [comment]
make asan clearly tells you what to do. Run the script in the tty, with no hyprland running.

**Comment by Rishik-Y** [comment]
Okay, Thx for the instruction.
Ran Asan successfully.

But the issue has weirdly been fixed.

No matter how many times I try to recreate it now, There is no crash or even lag.

It probably has been fixed with some other fix update, but thanks for responding.

**Comment by vaxerski** [comment]
closing then
