### ISSUE TITLE
gamma control

### ISSUE THREAD

**Issue by nicholascioli** [hyprwm/Hyprland#637]
I've tried both wlsunset and wl-gammactl, with neither being able to change the gamma of the monitor.

wlsunset errors with the following message:

```shell
registry: adding output 41
gamma control of output 41 failed
```

wl-gammactl errors with the following:

```shell
failed to set gamma table
```

I looked through the logs and didn't see any mention of the word `gamma`, so I'm not sure where to start locating the source of the issue. I see that https://github.com/hyprwm/Hyprland/blob/main/src/Compositor.cpp#L99 sets up the gamma control manager just like sway, so I'm not sure why it fails to change the gamma.

**Comment by NotAShelf** [comment]
Try Gammastep, it's confirmed to be working on Hyprland.

**Comment by vaxerski** [comment]
nvidia doesnt support those, you're out of luck
