### ISSUE TITLE
Strange behavior of waybar windows

### ISSUE THREAD

**Issue by VDFOREVER** [hyprwm/Hyprland#6371]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9994b73ad0af5c9ba5fc4058234cea77d0a1ddb1  (buffer: track asynchronous buffers and don't release them until unref).
Date: Sat Jun 8 18:27:56 2024
Tag: v0.40.0-176-g9994b73a, commits: 4782

flags: (if any)


System Information:
System name: Linux
Node name: void
Release: 6.9.3_1
Version: #1 SMP PREEMPT_DYNAMIC Thu May 30 22:21:45 UTC 2024


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

waybar pop-ups moved to the right
Also, pop-up windows do not hide themselves, only if you hover over them with the cursor

### How to reproduce

Interact with waybar

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/55760436/4f81cd75-bd50-4c91-b194-d96a782e873f)
[hyprland.log](https://github.com/user-attachments/files/15748950/hyprland.log)

**Comment by MightyPlaza** [comment]
if it's a regression please bisect

**Comment by vaxerski** [comment]
thats one and two isnt this a dupe of #6157

**Comment by gulafaran** [comment]
i can reproduce since https://github.com/hyprwm/Hyprland/commit/6967a31450441fc5605c05db6f65505dace4b263 not the misaligning but the calender popup sticks around if i move the mouse out of waybar towards the desktop/wallpaper. but if i move out of the icon and continue through waybar it gets closed. doesnt matter if i launch other things or change focus its like one has to refocus waybar to make it destroy. can be reproduced in nested too

**Comment by ArtemChandragupta** [comment]
I also have this issue

**Comment by gulafaran** [comment]
should be fixed with https://github.com/hyprwm/Hyprland/commit/4168b8c17b12b90873fab1ca73c2981b53f48bf5

**Comment by VDFOREVER** [comment]
The freeze was fixed, but the problem with the popup window displacement remained
v0.40.0:
![image](https://github.com/hyprwm/Hyprland/assets/55760436/2e7111d7-5c66-44ce-ac51-d5624e7c15b7)
![image](https://github.com/hyprwm/Hyprland/assets/55760436/77b30e93-e915-412f-a36c-986890f10498)
main:
![image](https://github.com/hyprwm/Hyprland/assets/55760436/1b3d11fa-ec74-4481-bab8-6959b2cbf69a)
![image](https://github.com/hyprwm/Hyprland/assets/55760436/ca003580-dc59-4b5a-b30b-9c7711f59b82)

**Comment by VDFOREVER** [comment]
This has now been fixed in the master branch.
