### ISSUE TITLE
osu! quits rendering new frames after a few seconds when tearing

### ISSUE THREAD

**Issue by Stoppedpuma** [hyprwm/Hyprland#6377]
### System Info and Version

Hyprland, built from branch main at commit 9994b73ad0af5c9ba5fc4058234cea77d0a1ddb1 (layersurface: avoid restack on identical layers).

flags: (if any)

System Information:
System name: Linux
Release: 6.8.9-273-tkg-eevdf-llvm
Version: #1 SMP PREEMPT_DYNAMIC TKG

GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])

### Bug or Regression?

Regression

### Description

Possibly related to #6376, opening another issue since I'm reproducing this issue in another way. I'm assuming this is caused by #6268 but I haven't checked which exact commit causes this issue.

### How to reproduce

Run [osu!](https://github.com/ppy/osu) on the latest hyprland commit with tearing enabled. SDL_VIDEODRIVER=Wayland might be required to reproduce but I haven't checked.

**Comment by vpertys** [comment]
can confirm this is caused by #6268, tried on c31d9ef4172452f6f219f91d9b87a24d91f0cf3a and it works just fine. also tried SDL_VIDEODRIVER=x11 on the latest commit and it's also working normally

**Comment by vaxerski** [comment]
can someone post a WAYLAND_DEBUG=1 log of osu?

**Comment by Stoppedpuma** [comment]
@vaxerski https://puma.s-ul.eu/18v2PWBW

**Comment by vaxerski** [comment]
:thinking: does setting `debug:damage_tracking` to 0 fix this? (note: really not recommended to do this outside testing)

**Comment by Stoppedpuma** [comment]
No, none of the options 0-2 fix this.

**Comment by vaxerski** [comment]
and can I get a hyprland log?

**Comment by Stoppedpuma** [comment]
https://puma.s-ul.eu/pJFWKnpG

**Comment by vaxerski** [comment]
link is dead

**Comment by vaxerski** [comment]
can you just attach files normally? Your links expire.

**Comment by Stoppedpuma** [comment]
There were a few downloads on the original log link so I figured you were one of them and just deleted it which is why the link died.

[hyprland_log.txt](https://github.com/user-attachments/files/15807308/hyprland_log.txt)

**Comment by vaxerski** [comment]
and the wayland_debug log of osu?

**Comment by Stoppedpuma** [comment]
[wayland_debug.txt](https://github.com/user-attachments/files/15808109/wayland_debug.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/15837957/patch.txt)
CRAAAAWLING IN MY SKIIIIIIIIIIIIIIIN

anyways try

**Comment by Stoppedpuma** [comment]
Seems to solve the issue, thanks!
