### ISSUE TITLE
Hyprland crashes when restarting fcitx5 (Random)

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6378]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9994b73ad0af5c9ba5fc4058234cea77d0a1ddb1 dirty (buffer: track asynchronous buffers and don't release them until unref).
Date: Sat Jun 8 23:27:56 2024
Tag: v0.40.0-176-g9994b73a, commits: 4782

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.9.3-2-cachyos-echo-lto
Version: #1 SMP PREEMPT_DYNAMIC Thu, 06 Jun 2024 06:05:56 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland crashes when restarting fcitx. It's crashed once so far and I haven't found a way to reproduce it yet.

### How to reproduce

above

### Crash reports, logs, images, videos

[hyprlandCrashReport1055.txt](https://github.com/user-attachments/files/15750549/hyprlandCrashReport1055.txt)
[coredumpctl.log](https://github.com/user-attachments/files/15750550/coredumpctl.log)

**Comment by hdm9527** [comment]
[hyprlandCrashReport67619.txt](https://github.com/user-attachments/files/15750648/hyprlandCrashReport67619.txt)
[hyprland_coredumpctl.log](https://github.com/user-attachments/files/15750650/hyprland_coredumpctl.log)

**Comment by cunbidun** [comment]
I also encountered this problem a number of times before

**Comment by sungyoonc** [comment]
I can reproduce it by
1. open firefox
2. open and close alacritty
3. restart fcitx

**Comment by hdm9527** [comment]
> I can reproduce it by
> 
> 1. open firefox
> 2. open and close alacritty
> 3. restart fcitx

same

**Comment by Fustigate8933** [comment]
Same here, the new updates brake fcitx5 + hyprland

**Comment by yangyingchao** [comment]
[0001-fix-crash-when-restarting-fcitx.patch.txt](https://github.com/user-attachments/files/15802747/0001-fix-crash-when-restarting-fcitx.patch.txt)

I came across the same issue. Maybe you can try the patch above and see if it works (it did not crash anymore in my case).

**Comment by hdm9527** [comment]
> [0001-fix-crash-when-restarting-fcitx.patch.txt](https://github.com/user-attachments/files/15802747/0001-fix-crash-when-restarting-fcitx.patch.txt)
> 
> I came across the same issue. Maybe you can try the patch above and see if it works (it did not crash anymore in my case).

It works fine.

**Comment by vaxerski** [comment]
can you make a MR if it works? :)

**Comment by hdm9527** [comment]
> can you make a MR if it works? :)

@yangyingchao

**Comment by yangyingchao** [comment]
done, #6460

-- *Yang Yingchao*
