### ISSUE TITLE
Relative executing script

### ISSUE THREAD

**Issue by budimanjojo** [hyprwm/Hyprland#639]
Hello, there's relative sourcing file from this: https://github.com/hyprwm/Hyprland/issues/314, but I can't seem to get the same result using `exec` and `exec-once`. Can we also have this here?

EDIT: Another thing, can this be done relative to the file calling the command instead of the path of config dir? My usecase is I have config file `~/.config/hypr/hyprland.conf`, sourcing a file with `source = ./configs/appearance.conf` and inside the `appearance.conf` I have this line: `exec-once = ../scripts/set-wallpaper.sh` which will set the wallpaper.

Thanks before.

**Comment by MightyPlaza** [comment]
can't you do this with bash ```for i in ~/.config/hypr/*.sh; do "$i"; done``` ?

**Comment by izmyname** [comment]
Is this still actual?
