### ISSUE TITLE
Unable to compile new version of hyprland on gentoo

### ISSUE THREAD

**Issue by zukas97** [hyprwm/Hyprland#6390]
### System Info and Version

<details> <summary>Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

System Information:
System name: Linux
Node name: zukas-gentoo
Release: 6.9.3-gentoo-x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sun Jun  9 13:05:35 -00 2024

GPU information:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] [1002:699f] (rev 81) (prog-if 00 [VGA controller])

os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"

plugins: none</summary>

</details>

### Bug or Regression?

Bug

### Description

When updating my gentoo system It tryed to compile the latest version of hyprland. It had a nondiscriptive error in the compile phase. I scrolled up and saw:
```
error: too few arguments to function ‘liftoff_output_apply’
  410 |                 int ret = liftoff_output_apply(crtc->liftoff, req, flags);
```
this seems to be a bug in the hyprland code not portage.

### How to reproduce

try compiling the latest version of hyprland on gentoo

**Comment by gulafaran** [comment]
its fixed in https://github.com/hyprwm/Hyprland/commit/098ac916a6314a2b731532e0c85f357e3cf90d2f either some backports are needed of this or a mask  in /etc/portage/package.mask of libliftoff 0.5 until this is in a release.

**Comment by vaxerski** [comment]
as above
