### ISSUE TITLE
Monitor count +1

### ISSUE THREAD

**Issue by GimmeDataNow** [hyprwm/Hyprland#6395]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.6.32
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat May 25 14:22:56 UTC 2024


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240606.9b5328b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hyprland somehow thinks that I have more than 2 monitors attached (?) with `hyprctl monitors` providing the following:

```sh
....
Monitor Unknown-1 (ID 2):
	1024x768@59.99900 at 4480x0
	description: 
	make: 
	model: 
	serial: 
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 31 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: Invalid
	availableModes: 1024x768@60.00Hz
```

I do not own any monitors with that size nor are there any additional display devices plugged into the system.

This issue causes my mouse to go out of bounds on the right hand side of the second monitor.

### How to reproduce

I have no clue but this happened once I moved to NixOs 24.05 (did not occur on 23.11).  If this issue is not already fixed I'll try to post my nixos config.

**Comment by vaxerski** [comment]
they should make a medicine that makes you read the wiki https://wiki.hyprland.org/FAQ/#workspaces-or-clients-are-disappearing-or-monitor-related-dispatchers-cause-crashes
