### ISSUE TITLE
Screenshare is not working at all with 0.41.0 with latest xdg-desktop-portal-hyprland master

### ISSUE THREAD

**Issue by s0mebodyhelpme** [hyprwm/Hyprland#6396]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1423707dbefc0329e80895451903a77ab684f7ea  (output: remove wl_output globals for mirrored displays).
Date: Mon Jun 10 06:06:42 2024
Tag: v0.40.0-183-g1423707d, commits: 4789

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.9.3-273-tkg-eevdf
Version: #1 SMP PREEMPT_DYNAMIC TKG Sun, 09 Jun 2024 20:23:32 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c1) (prog-if 00 [VGA controller])
0e:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
[conf.zip](https://github.com/user-attachments/files/15759518/conf.zip)

```

</details>

### Bug or Regression?

Bug

### Description

The screenshare functionality using xdg-desktop-portal-hyprland-git (the latest commit version of the xdg portal implementation on Hyprland) is broken with the latest commit of the Hyprland compositor on Vesktop, at least. It only displays a black screen when sharing the window or screen from xdg-desktop-portal-hyprland, and it doesn't happen on the official arch package that uses an earlier version of hyprland.

### How to reproduce

Install hyprland-git and xdg-desktop-portal-hyprland-git from the AUR as well as any version of vesktop from the AUR and attmpt to screenshare video. I've tested this on vesktop, vesktop_electron, vencord-desktop-git and probably on other versions I can't remember the names of right now.

### Crash reports, logs, images, videos

It doesn't crash Hyprland but the screenshare is simply black/blank. Regardless, here is the report:
[hyprlandCrashReport129838.txt](https://github.com/user-attachments/files/15759634/hyprlandCrashReport129838.txt)

**Comment by Aqa-Ib** [comment]
I just installed Vesktop through AUR. I can't reproduce your issue. Screen sharing is working fine on my computer. Do notice that the screensharing window for selecting the screen/window appears multiple times, before and after vesktop's screensharing window.

**Comment by s0mebodyhelpme** [comment]
Are you using the latest commit of the hyprland-git package and xdg-desktop-portal-hyprland? It fails to really capture the screen when I use "allow a restore token" checkmark, which essentially makes it so I don't have to reselect the capture source.

**Comment by s0mebodyhelpme** [comment]
The following is the output of running vesktop from the terminal and attempting to screenshare in it:

```
[134025:0610/204442.245266:ERROR:select_file_dialog_linux_portal.cc(286)] Failed to read portal version property
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[134061:0610/204443.898842:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[134061:0610/204454.606393:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[134061:0610/204457.737277:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[134025:0610/204457.771434:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[134025:0610/204457.771459:ERROR:shared_screencast_stream.cc(940)] Dropping DMA-BUF modifier: 144115206334822913 and trying to renegotiate stream parameters
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-06-10 20:44:58.145] [venmic] [info] [patchbay] (get) running venmic 3.5.0
[2024-06-10 20:45:02.297] [venmic] [info] [patchbay] (create_mic) created: 107
[134025:0610/204502.354982:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[134025:0610/204502.355008:ERROR:shared_screencast_stream.cc(940)] Dropping DMA-BUF modifier: 144115206334822913 and trying to renegotiate stream parameters
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[134025:0610/204502.405198:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[134025:0610/204502.405244:ERROR:shared_screencast_stream.cc(940)] Dropping DMA-BUF modifier: 144115206334822913 and trying to renegotiate stream parameters
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
*** impl_ext_end_proxy called from wrong context, check thread and locking: Not in loop
```

**Comment by shogeki** [comment]
I get the same Error creating EGLImage in my logs.

Normally after the first selection of a window in Vesktop, it will display the actual window preview in the discord window popup (even though it requires to you click 2 more times.) But of late this window and all shares are black screen.

I could not, however, seem to track this down by bisecting Hyprland.  As old as Xwayland impl is now affected (which worked for me before). Could this have been a dependency?

**Comment by shogeki** [comment]
I saw what you wrote in #6370 , but reverting just Hyprland to v40 did not work for me.  

I installed OBS to test which also displays a black screen trying to capture so this is not just Vesktop

**Comment by s0mebodyhelpme** [comment]
Interesting. Screenshare works for me with the earlier version oddly enough, at least with xdg-desktop-portal-hyprland-git. Could be that either your system has specific tweaks to it or Hyprland is having issues rn with screensharing in general.

**Comment by Aqa-Ib** [comment]
Upgrading xdg-desktop-portal-hyprland from version 1.3.1-6 to latest git breaks it.

**Comment by s0mebodyhelpme** [comment]
Interestingly, using hyprland's official package with xdg-desktop-portal-hyprland-git works for me while it doesn't for @shogeki.

**Comment by shogeki** [comment]
reverting xdg to 1.3.1-6 gets it working for me.

**Comment by Aqa-Ib** [comment]
commit 12af8413417d5ad693348ee5b140a426471b0be6 from xdg-desktop-portal-hyprland broke it.

**Comment by s0mebodyhelpme** [comment]
Seems correct, @Aqa-Ib. Setting the commit to the one prior to that one fixes it.

**Comment by Aqa-Ib** [comment]
Well, the thing is that xdg-desktop-portal-hyprland built at latest commit works with Hyprland 0.40.0.

This is a problem between hyprland latest git and [12af8413417d5ad693348ee5b140a426471b0be6](https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/12af8413417d5ad693348ee5b140a426471b0be6)

**Comment by s0mebodyhelpme** [comment]
That's the odd thing. Release version hyprland (0.40.0) works fine with the latest xdg-desktop-portal master, but not with the latest hyprland at all, so you seem to be correct, @Aqa-Ib.

**Comment by vaxerski** [comment]
can someone bisect hyprland then?

**Comment by Aqa-Ib** [comment]
The break is between https://github.com/hyprwm/Hyprland/commit/9bc00897fcc896c49a83f55da9de2427e878401a and https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/12af8413417d5ad693348ee5b140a426471b0be6

**Comment by vaxerski** [comment]
not possible that's the hyprland regressor.

**Comment by Aqa-Ib** [comment]
Let me check again. I am going to my house, in an hour or two I'll tell ya.

**Comment by vaxerski** [comment]
cool, I'll check tomorrow when I am done from a meetup with a friend in the morning

**Comment by romanstingler** [comment]
screenshare on google meet and mozilla test page works on 

```
~ ❯ yay -Q | grep  hypr                                                                                                                                                                                      
hyprcursor 0.1.9-1.1
hypridle 0.1.2-1.1
hyprland-git 0.41.0.r1.811429bf-1
hyprlang 0.5.2-1.1
hyprlock 0.3.0-1.1
hyprpaper 0.7.0-1
hyprutils 0.1.1-1
hyprwayland-scanner-git 0.3.10.r0.g0f30f9ec-1
xdg-desktop-portal-hyprland 1.3.1-6.1
```

**Comment by Aqa-Ib** [comment]
> cool, I'll check tomorrow when I am back from a meetup with a friend in the morning

Sorry for the --verbose.

This bug is intermittent. Some sessions it works, others don't. I have to restart the session until I get a different result.
What I have noticed at the moment is that the portal throws this error when it fails: `[LOG] [screencopy/pipewire] Out of buffers`

**Comment by Aqa-Ib** [comment]
The bug is here:

https://github.com/hyprwm/xdg-desktop-portal-hyprland/blob/72907822c19afc0983c69d59d299204381623725/src/portals/Screencopy.cpp#L692C1-L692C183

**Comment by vaxerski** [comment]
since I don't seem to be affected, can you do some testing and then whip up a MR with whatever you find working best?

**Comment by Aqa-Ib** [comment]
I am going to continue the conversation in the portal issue tracker, since it seems clear to me that the bug is there:
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/225
