### ISSUE TITLE
crash on start Hyprland

### ISSUE THREAD

**Issue by samsep101** [hyprwm/Hyprland#6397]
### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

Tried to build with cmake and got a error:
```
meson.build:83:11: ERROR: Command `/home/samsepiol/Hyprland/subprojects/wlroots-hyprland/./patches/apply.sh` failed with status 1.

A full log can be found at /home/samsepiol/Hyprland/subprojects/wlroots-hyprland/build/meson-logs/meson-log.txt
[55/255] Building CXX object hyprpm/CMakeFiles/hyprpm.dir/src/core/PluginManager.cpp.o
/home/samsepiol/Hyprland/hyprpm/src/core/PluginManager.cpp: In function «std::string execAndGet(std::string)»:
/home/samsepiol/Hyprland/hyprpm/src/core/PluginManager.cpp:45:50: предупреждение: игнорирование атрибутов аргумента шаблона «int (*)(FILE*)» [-Wignored-attributes]
   45 |     const std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                                  ^
[56/255] Building CXX object hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o
ninja: build stopped: subcommand failed.
```
Legacy rerender give same error.
Hyprland successfully installed by aur package

### How to reproduce

Starting Hyprland

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
"stable"

Hyprland received signal 6(ABRT)
Version: cba1ade848feac44b2eda677503900639581c3f4
Tag: v0.40.0

System info:
	System name: Linux
	Node name: samsepiol-tobefilledbyoem
	Release: 6.5.13-1-MANJARO
	Version: #1 SMP PREEMPT_DYNAMIC Tue Nov 28 20:33:05 UTC 2023

GPU:
	01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Turks XT [Radeon HD 6670/7670] [1002:6758] (prog-if 00 [VGA controller])

os-release:
	NAME="Manjaro Linux"
	PRETTY_NAME="Manjaro Linux"
	ID=manjaro
	ID_LIKE=arch
	BUILD_ID=rolling
	ANSI_COLOR="32;1;24;144;200"
	HOME_URL="https://manjaro.org/"
	DOCUMENTATION_URL="https://wiki.manjaro.org/"
	SUPPORT_URL="https://forum.manjaro.org/"
	BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
	PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
	LOGO=manjarolinux
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x564d966c1d21]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xde9) [0x564d96658729]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x564d965d8281]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3cae0) [0x7fbe21a50ae0]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x94e44) [0x7fbe21aa8e44]
		??
		??:0
	#5 | /usr/lib/libc.so.6(gsignal+0x20) [0x7fbe21a50a30]
		??
		??:0
	#6 | /usr/lib/libc.so.6(abort+0xdf) [0x7fbe21a384c3]
		??
		??:0
	#7 | /usr/lib/libstdc++.so.6(+0x97b0c) [0x7fbe21c97b0c]
		??
		??:0
	#8 | /usr/lib/libstdc++.so.6(+0xadf1a) [0x7fbe21cadf1a]
		??
		??:0
	#9 | /usr/lib/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7fbe21c9750a]
		??
		??:0
	#1 | /usr/lib/libstdc++.so.6(+0xae1d6) [0x7fbe21cae1d6]
		??
		??:0
	#11 | Hyprland(+0x861b2) [0x564d9655b1b2]
		??
		??:0
	#12 | Hyprland(_ZN11CCompositor10initServerEv+0xbc6) [0x564d965e08c6]
		CCompositor::initServer()
		??:?
	#13 | Hyprland(main+0x9e5) [0x564d965a1535]
		main
		??:?
	#14 | /usr/lib/libc.so.6(+0x25c88) [0x7fbe21a39c88]
		??
		??:0
	#15 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7fbe21a39d4c]
		??
		??:0
	#16 | Hyprland(_start+0x25) [0x564d965d4bb5]
		_start
		??:?

Log tail:
[LOG] Runtime directory: /run/user/1000/hypr/cba1ade848feac44b2eda677503900639581c3f4_1718012545_1954237613
[LOG] Hyprland PID: 36220
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: samsepiol-tobefilledbyoem
[LOG] Release: 6.5.13-1-MANJARO
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Tue Nov 28 20:33:05 UTC 2023

[LOG] GPU information:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Turks XT [Radeon HD 6670/7670] [1002:6758] (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: "the only wayland compositor powered by fried chicken" - raf

[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the ProtocolManager!
[LOG] [TearingControl] Registered global
[LOG] [FractionalScale] Registered global
[LOG] [XDGOutput] Registered global
[LOG] [CursorShape] Registered global
[LOG] [IdleInhibit] Registered global
[LOG] [RelativePointer] Registered global
[LOG] [XDGDecoration] Registered global
[LOG] [AlphaModifier] Registered global
[LOG] [GammaControl] Registered global
[LOG] [ForeignToplevel] Registered global
[LOG] [PointerGestures] Registered global
[LOG] [ForeignToplevelWlr] Registered global
[LOG] [ShortcutsInhibit] Registered global
[LOG] [TextInputV3] Registered global
[LOG] [PointerConstraints] Registered global
[LOG] [OutputPower] Registered global
[LOG] [XDGActivation] Registered global
[LOG] [IdleNotify] Registered global
[LOG] [SessionLock] Registered global
[LOG] [IMEv2] Registered global
[LOG] [VirtualKeyboard] Registered global
[LOG] [VirtualPointer] Registered global
[LOG] [OutputManagement] Registered global
[LOG] ToplevelExportManager started successfully!
[LOG] TextInputV1Manager started successfully!
[LOG] GlobalShortcutsManager started successfully!
[LOG] ScreencopyProtocolManager started successfully!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 26.27µs. Estimated average calc time: 0.06µs.
[LOG] Creating the ConfigManager!
[WARN] Creating config home directory
[WARN] No config file found; attempting to generate.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 17.29µs. Estimated average calc time: 0.04µs.
[LOG] Using config: /home/samsepiol/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 17.24µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/samsepiol/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 17.21µs. Estimated average calc time: 0.04µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[backend/backend.c:224] Cannot create X11 backend: disabled at compile-time
[CRITICAL] m_sWLRBackend was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_backend_autocreate() failed!

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/issues/6364
you might be able to modify the aur package to build legacyrender

**Comment by samsep101** [comment]
> #6364 you might be able to modify the aur package to build legacyrender

i think it's maybe becase Hyprland cannot dialog with x11, before was some difficulties with xorg(
i will try to reinstall and start x11 and message here

**Comment by vaxerski** [comment]
Running hyprland on x11 is not supported.
