### ISSUE TITLE
Create New Storage - Steam

### ISSUE THREAD

**Issue by FrancisWorld** [hyprwm/Hyprland#6412]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
System Information:
System name: Linux
Node name: Jedi
Release: 6.9.3-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:26 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 SUPER] [10de:1f06] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Unable to create a new Storage for Steam.
Can't create new Storage Drive for steam games at secondary SSD

### How to reproduce

Launch Steam > Settings > Storage > Add Drive +

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/103578199/670eec7d-850a-4dd4-a84a-2f4a4bc218a7

**Comment by izmyname** [comment]
Do you have xdg-desktop-portal-gtk installed?

**Comment by vaxerski** [comment]
this is not a problem with hyprland. Likely can be fixed by above.
