### ISSUE TITLE
Extend two monitors is not working

### ISSUE THREAD

**Issue by JesusJimenezC** [hyprwm/Hyprland#6415]
### Bug or Regression?

Bug

## Current configuration

```sh
monitor = HDMI-A-2, 1920x1080@60, 0x0, 1
monitor = DP-1, 1920x1080@59.98, 1980x0, 1
```

## Monitors
![240610_19h23m11s_screenshot](https://github.com/hyprwm/Hyprland/assets/114774213/3feda4b7-e7f3-4d4c-b4c9-9d873d104da0)

### Description

I tried to replicate the configuration mentioned on Monitors configuration from hyprland but does not work. I do not see nothing on my second monitor, exept for the default message that says "No Signal".

### How to reproduce

Copy showed configuration

**Comment by vaxerski** [comment]
you havent posted systeminfo as requested, so this is invalid.

I am gonna guess nvidia dgpu on a laptop and thus HDMI will not work as it's hardwired to the dgpu without forcing a mux
