### ISSUE TITLE
Couldn't connect to socket - Bug reappears

### ISSUE THREAD

**Issue by barreiroleo** [hyprwm/Hyprland#642]
Just the same bug but with hyprctl.
Commands that should work:
`hyprctl dispatch exec kitty`
`hyprctl monitors`

Get the same code error:
`Couldn't connect to /tmp/hypr/6e195a6b8cb98e96d15c51003da4b17154c55ff3_1662634269/.socket.sock. (3`

Reference: https://github.com/hyprwm/hyprpaper/issues/5

**Comment by vaxerski** [comment]
means the hyprland socket is missing / dead. Not much else to say.

This should never happen, unless you removed it manually or something is seriously wrong with your system.

**Comment by ManEnfu** [comment]
@barreiroleo Do you happen to have 2 or more user in your system (excluding root)?

**Comment by barreiroleo** [comment]
> @barreiroleo Do you happen to have 2 or more user in your system (excluding root)?

Nop, only me

**Comment by ManEnfu** [comment]
> Nop, only me

Ah, alright then. I discovered similar issue but probably with another cause than yours. In the meantime, make sure you have write permission on `/tmp/hypr`.

**Comment by elliotwesoff** [comment]
I'm getting the same issue:

```
$ hyprctl hyprpaper wallpaper DP-3,~/Pictures/bg.jpg
Couldn't connect to /tmp/hypr/dceb463de899dbf25ef72ab2dc6735106d414716_1663094463/.hyprpaper.sock. (3)
```

I just did a `chmod 777 /tmp/hypr` to make sure that directory is writable too.

**Comment by vaxerski** [comment]
@elliotwesoff this is the hyprpaper socket. Is hyprpaper running?

**Comment by barreiroleo** [comment]
After an update, it is already working.

**Comment by magthe** [comment]
I think I'm seeing this happening:

```
❯ hyprctl version
Couldn't connect to /tmp/hypr/51a930f802c71a0e67f05e7b176ded74e8e95f87_1685874776/.socket.sock. (3)
```

while

```
❯ id
uid=1000(elendil) gid=1000(elendil) groups=1000(elendil),984(users),985(video),996(audio),998(wheel)

❯ ls -al /tmp/hypr/51a930f802c71a0e67f05e7b176ded74e8e95f87_1685910457
total 60
drwxrwx--- 2 elendil elendil   100 Jun  4 22:27 .
drwxrwxrwx 3 elendil elendil    60 Jun  4 22:27 ..
-rw-r--r-- 1 elendil elendil 58033 Jun  4 22:39 hyprland.log
srwxr-xr-x 1 elendil elendil     0 Jun  4 22:27 .socket2.sock
srwxr-xr-x 1 elendil elendil     0 Jun  4 22:27 .socket.sock
```

Currently running the latest package

```
❯ pacman -Q hyprland
hyprland 0.26.0-1
```

and `/tmp` mounted like this

```
❯ mount | rg /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
```

Also I see multiple mentions of this bug in my logs

```
❯ rg "connect to socket" /tmp/hypr/51a930f802c71a0e67f05e7b176ded74e8e95f87_1685910457/hyprland.log | tail -n 2
[LOG] Set keyboard focus to surface 556a16acedd0, with window name: Couldn't connect to socket - Bug reappears · Issue #642 · hyprwm/Hyprland — Mozilla Firefox
[LOG] Set keyboard focus to surface 556a16acedd0, with window name: Couldn't connect to socket - Bug reappears · Issue #642 · hyprwm/Hyprland — Mozilla Firefox
```

**Comment by magthe** [comment]
Building from source (using [the package in AUR](https://aur.archlinux.org/packages/hyprland-git)) made no difference

```
❯ pacman -Q hyprland-git
hyprland-git r2970.4ef684f6-1

❯ hyprctl version
Couldn't connect to /tmp/hypr/51a930f802c71a0e67f05e7b176ded74e8e95f87_1685874776/.socket.sock. (3)
```

**Comment by filippoaceto22** [comment]
I have this bug, was anyone able to solve it?

**Comment by Tomkoid** [comment]
This bug also happens to me when messing with Waybar (killing the process and then launching it again).

**Comment by filippoaceto22** [comment]
same

**Comment by noahgitsham** [comment]
This happened to me after updating Hyprland to 0.40.0-1 while it was still running

**Comment by zdarovayrodi** [comment]
Just had the same issue. Updating all the packages seems to solve it

```
❯ pacman -Q hyprpaper hyprland
hyprpaper 0.7.0-1
hyprland 0.40.0-1
```

**Comment by deng232** [comment]
nixos, still have this issue

**Comment by anufrievroman** [comment]
Yep, still happens on most recent versions of everything:
```
[ERR] Couldn't listen on the hyprpaper Socket. (3) IPC will not work.
```

**Comment by iddm** [comment]
So no solution to this?

**Comment by aryuuu** [comment]
> So, no solution to this? I just upgraded my hyprland and see this for the first time, previously it was all okay for a long time. And I indeed no longer have the `/tmp/hypr` anymore. I am just using the ArchLinux packages.
> 
> UPD:
> 
> Solved by checking that indeed the correct binaries were used: I previously had a mess up with hyprpm, hyprctl and hyprcursor installed under "/usr/local/bin", so removing those fixed the issue.
> 
> UPD2:
> 
> I still don't have the `/tmp/hypr` directory now, only the `/tmp/hyprpm` there. Any idea why?

@iddm i am facing the same issue (hyprland 0.41.2) and just noticed that based on this release changelog, the directory for hyprland socket has been moved from from `/tmp/hypr` to `$XDG_RUNTIME_DIR/hypr`.

![image](https://github.com/hyprwm/Hyprland/assets/31617773/dcccb446-757e-4296-9e5e-4792671d29c3)

i checked and it was indeed there
![image](https://github.com/hyprwm/Hyprland/assets/31617773/7de1231b-9fa9-4c69-a4ed-086e061db85f)

**Comment by giodueck** [comment]
For anyone that still has this issue, try to check the value of the env variable `HYPRLAND_INSTANCE_SIGNATURE`, as suggested in this issue: #7041.

If you are using tmux, try running the commands that fail in a fresh terminal (outside of tmux). I see several tmux users have commented before

**Comment by harryaskham** [comment]
Yup, stale tmux session was it for me. I suspect like me a lot of people have their hypr config open in a tmux session for fast back-and-forth between hyprland and GDM.
