### ISSUE TITLE
Keyboard focus issues

### ISSUE THREAD

**Issue by phonetic112** [hyprwm/Hyprland#6421]
### Bug or Regression?

Regression

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 811429bfd4a46f33c7788580f72038b0c3c1c2b1  (wayland: consistently check mmap error after 6967a3145044 (6402)).
Date: Mon Jun 10 16:31:03 2024
Tag: v0.41.0-1-g811429bf, commits: 4795

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.9.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Keyboard focus doesn't change properly with mouse focus. When there are two windows and the mouse hovers over the other window, neither windows get keyboard focus. Swapping mouse focus enough times gives keyboard focus back to the window.

### How to reproduce

1. Open 2 windows (e.g. foot)
2. Hover over the left window. the keyboard should be focused
3. Hover over the right window. The keyboard gets unfocused from both windows.
4. Repeat step 2 and 3 until one of the windows randomly gets focused again

**Comment by vaxerski** [comment]
can't repro.

**Comment by phonetic112** [comment]
seems like ags is causing it, I set my wallpaper with ags on the background layer so it's interfering somehow

**Comment by SimonBrandner** [comment]
Hmm, I am seeing this as well

**Comment by vaxerski** [comment]
can you try on latest?

**Comment by phonetic112** [comment]
still happens on b6bf4afb4861c7a7b41c6bf53daadf57a708e352

**Comment by vaxerski** [comment]
then I'll need a minimal reproducible example - aint happenin to me

**Comment by phonetic112** [comment]
1. load this ags config:

```
const Wallpaper = Widget.Window({
    monitor: 0,
    layer: "background",
    exclusivity: "ignore",
    keymode: "none",
    name: `desktop-0`,
    class_name: "desktop",
    anchor: ["top", "bottom", "left", "right"],
    child: Widget.Box({
        class_name: "wallpaper",
        expand: true,
        vpack: "center",
        hpack: "center",
    }),
})

App.config({
    windows: [
        Wallpaper
    ],
});
```

2. open two windows
3. hover over one of them
4. Hover over the other
5. Both should get unfocused

**Comment by vaxerski** [comment]
next time please give a config that will run, you omitted imports.

Anyways,
![image](https://github.com/hyprwm/Hyprland/assets/43317083/5f2a42f8-1082-4b92-846b-e8d9a3194a64)

No focus issues on my end.

**Comment by phonetic112** [comment]
another thing, both windows have to be tiled and there should be a gap between them

>you omitted imports

I didn't, your ags install might be borked?

**Comment by phonetic112** [comment]
bisect: 6967a31450441fc5605c05db6f65505dace4b263
