### ISSUE TITLE
Opening hyprpicker crashes hyprland

### ISSUE THREAD

**Issue by LivacoNew** [hyprwm/Hyprland#6422]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
sam@silverhand > hyprctl version                                                                                                 ~
Hyprland, built from branch main at commit 811429bfd4a46f33c7788580f72038b0c3c1c2b1  (wayland: consistently check mmap error after 6967a3145044 (6402)).
Date: Mon Jun 10 21:31:03 2024
Tag: v0.41.0-1-g811429bf, commits: 4795

flags: (if any)
sam@silverhand > pacman -Q hyprpicker                                                                                            ~
hyprpicker-git 0.3.0.r1.36d9741-1
```
</details>

### Description

Opening Hyprpicker after the system has been up for some time can cause Hyprland to immediately crash.
As usual, no logs or crash report gets made, so I've attached an asan log instead as well as the hyprland log from a session.

Asan log hints that it's a radeon related thing, so if it matters it's a Sapphire Nitro+ 7800XT.

### How to reproduce

Open Hyprland for a little bit, start hyprpicker, crash.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/15787584/hyprland.log)
[asan.log](https://github.com/user-attachments/files/15787591/asan.log)

**Comment by vaxerski** [comment]
:bus:

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/15792935/patch.txt)
try

**Comment by tfl** [comment]
Cannot confirm this: 0.4.1 is running here for almost two hours and hyprpickr did not crash anything.
I did browse the web, used some Alacrittis and a mpv is playing a video stream for one hour now - no problem.
Archlinux, Intel Core i5-6600, Intel HD Graphics 530; driver: i915

**Comment by LivacoNew** [comment]
> [patch.txt](https://github.com/user-attachments/files/15792935/patch.txt) try

This instead just freezes Hyprland indefinitely. Working on getting a log for you.

**Comment by LivacoNew** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/51921257/eff3a543-fc32-43eb-9358-3c2852cf0783)
I think a sigbus may be happening...
I think I may have a theory tho, in the fact that I used to keep hyprland stdout/logging on all the time. This used to be fine but as of the most recent update, hyprland is spamming the living hell out of it. The log I got that screenshot from above being 3.5GB proves this, flooding my runtime dir with shite and making it run out of space before I tried hyprpicker and sure enough it froze right afterwards.

Will turn off logging in the meantime and see if I'm right, as I obviously can't send that log above to you and this sigbus error got thrown so many times I can't see anything above it with several minutes of holding pgup. If this ends up fixing it, I would suggest moving whatever is spamming it out to a more verbose level so it doesn't spam unless verbose is enabled? If not then I'll see if I can find a way to get logs that aren't 2tb large lol

**Comment by vaxerski** [comment]
logs are off by default, turn them off. The log above is only from this patch.

**Comment by oneshotws** [comment]
Hi! I encountered same-ish bug, can you confirm that it's related?

OS: NixOS unstable
When i run `x11_ssh_askpass` hyprland freezes indefenetly (keyboard and mouse unresponsive, binds to exit hyprland don't work, and CTRL+ALT+F5 either). Previously it was working. By connecting via SSH to affected host, I can see that hyprland consumes 100% CPU (of 1 core).
Log doesn't tell much: 
[hyprland.log](https://github.com/user-attachments/files/15948435/hyprland.log)
(line 858 - Window 11d60670 set title to  TEST)
Current version:
```
~ ➤ hyprctl version
Hyprland, built from branch main at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: 2024-06-13
Tag: v0.41.1, commits: 9e781040d9067c2711ec2e9f5b47b76ef70762b3

flags: (if any)
```
Working version:
```
➤ hyprctl version
Hyprland, built from branch  at commit 2ccd45a84475fab46c6fecd2fe226d3173104743 dirty ().
Date: 2024-05-12
Tag: , commits:

flags: (if any)
```

**Comment by LivacoNew** [comment]
You'll have to give me a few days, quite busy ATM and I've had to downgrade to 0.39 because of how unstable the more recent versions are because of this rewrite business. Once I get time to go back up to 0.41 I'll let you know.

**Comment by izmyname** [comment]
Bump. How's it going?

**Comment by LivacoNew** [comment]
Forgot this issue existed, my bad.
Swapped back to latest git about a week ago, and have yet to encounter this so I'm guessing it was the overly-verbose logs filling $XDG_RUNTIME_DIR that caused issues. Haven't been able to replicate the issue with `x11_ssh_askpass` either.
As my issue itself is fixed, I'll close and let yous open a separate issue with the askpass stuff.
