### ISSUE TITLE
Window swallowing doesn't work in new update

### ISSUE THREAD

**Issue by user880907** [hyprwm/Hyprland#6425]
### Bug or Regression?

Regression

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
hyprland-0.41.0-1

misc {
  enable_swallow = true
  swallow_regex = ^(kitty)$
}
```
</details>

### Description

Window swallowing does not work which was not the case in 0.40.

### How to reproduce

Open an application through a terminal

**Comment by vaxerski** [comment]
#6095
