### ISSUE TITLE
gtk the popups have broken focus

### ISSUE THREAD

**Issue by VDFOREVER** [hyprwm/Hyprland#6426]
### Bug or Regression?

Regression

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)


System Information:
System name: Linux
Node name: void
Release: 6.9.3_1
Version: #1 SMP PREEMPT_DYNAMIC Thu May 30 22:21:45 UTC 2024


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:
```

</details>

### Description

If you open the pop-up window, it will not hide even if you interact with the main window or with others, I also noticed that there is a dead area where the pop-up window does not respond to clicks to close

### How to reproduce

Call the context menu in any gtk application and try to close it by changing focus

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/55760436/c5b5ef2e-e594-4b40-a196-39510439f4b0)

https://github.com/hyprwm/Hyprland/assets/55760436/83171b2d-fbe2-406e-add5-62d8756df6bf

**Comment by MightyPlaza** [comment]
monitor scaling?
also, if it's a regression please bisect

**Comment by tfl** [comment]
Are you sure a popup window should be closed by changing the focus? Never had this happen anywhere, anytime in any GUI - ever. I do not encounter a problem with popup property windows or context menus (tested with Gnome Nautilus) They behave as expected. No glitches whats-o-ever.

However, what I encounter recently are keyboard lags - sometimes seconds - which leads to whole words being swallowed. But thats a different story, maybe a different issue. Or a problem of my wireless keyboard.

**Comment by VDFOREVER** [comment]
Sorry, for some reason it always seems to me that something is not working right, it also works in hyprland 0.40.0, but the dead zone bothers me, but I don't have anything to check how pop-ups work there
