### ISSUE TITLE
Cursor is upside down in QEMU, even with WLR_NO_HARDWARE_CURSORS

### ISSUE THREAD

**Issue by xslhub** [hyprwm/Hyprland#6428]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)

System Information:
System name: Linux
Node name: vm
Release: 6.9.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Red Hat, Inc. Virtio 1.0 GPU [1af4:1050] (rev 01) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Description

The cursor is upside down when running Hyprland in QEMU. Previously
`export WLR_NO_HARDWARE_CURSORS=1` fixed this issue. After the update to 0.41.0 this fix is no longer working. Removing the export doesn't fix the problem either. Only a downgrade to 0.40.0 helps to resolve it.

Command used to run QEMU:
```
qemu-system-x86_64 -drive file=$HOME/vms/gui.cow,format=qcow2 \
-m 4048 -enable-kvm -machine q35 -device intel-iommu -cpu host \
-device virtio-vga-gl \
-vga none \
-display gtk,gl=on,grab-on-hover=on \
-device ich9-intel-hda \
-device hda-output
```

### How to reproduce

1. Install Hyprland in QEMU
2. Cursor is upside down

**Comment by Agent00Ming** [comment]
https://wiki.hyprland.org/Configuring/Variables/#cursor : `cursor:no_hardware_cursors` ?

**Comment by xslhub** [comment]
> https://wiki.hyprland.org/Configuring/Variables/#cursor : `cursor:no_hardware_cursors` ?

This fixed the problem. Thank you!
