### ISSUE TITLE
Dragging tabs in chrome is crashing Hyprland

### ISSUE THREAD

**Issue by re-ynd** [hyprwm/Hyprland#643]
**Steps to reproduce**
1. Launch chrome
2. Open two tabs
3. Drag a tab to change its placement

**Expected outcome**
Tab should move to the new location without a crash

**Noted outcome**
Tab moves to new location but as soon as I release the mouse, Hyprland crashes and logs me out of the session

I am using v0.13.0beta. Did not have this issue in previous version

**Comment by vaxerski** [comment]
That was already fixed in HEAD. Please use the latest HEAD and not release for reporting bugs.
