### ISSUE TITLE
Click area of a groups tabs becomes inaccurate with a lot of windows

### ISSUE THREAD

**Issue by Stoppedpuma** [hyprwm/Hyprland#6431]
### Bug or Regression?

Bug

### System Info and Version

Commit 8412ffcc42012888757cd00a004871e8bc353cf2, 0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])

### Description

The area to click on the tabs of a group becomes inaccurately sized.

### How to reproduce

Group a bunch of windows and try switching between them by clicking on the tabs

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/58333920/2ee1cf23-05bf-46e4-8b38-59a4e42cb3c6

**Comment by MightyPlaza** [comment]
please provide a version and make sure this isn't a regression
possibly regressed by https://github.com/hyprwm/Hyprland/pull/5886

**Comment by Stoppedpuma** [comment]
I'm able to reproduce this on [v0.40.0](https://github.com/hyprwm/Hyprland/releases/tag/v0.40.0) which is before that commit was merged. 

> please provide a version

Edited the title to show commit instead of just saying latest

**Comment by MightyPlaza** [comment]
yeah the groupbar clicking itself is accurate
the problem lies on the drawing
![image](https://github.com/hyprwm/Hyprland/assets/123664421/28c11022-87d3-4f91-b1f4-4f329a38f350)
this should not be happening, Imma take a look once I have the time
