### ISSUE TITLE
Can't paste from zim to firefox

### ISSUE THREAD

**Issue by Kommynct** [hyprwm/Hyprland#6436]
### Bug or Regression?

Regression

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)


System Information:
System name: Linux
Node name: anarchy-desktop
Release: 6.9.3-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:26 +0000


GPU information: 
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Description

Zim can't paste into firefox for some reason with the new version.

### How to reproduce

open zim and firefox side by side, notice you can't paste from zim to firefox

edit: just realized i was running zim in x11 mode, bug still applies but I switched to wayland mode

env GDK_BACKEND=x11 zim

is necessary for reproduction.

**Comment by The-Lost-Light** [comment]
Currently I have the problem in electron (wayland/x11 both)
And can paste by the clipboard history

**Comment by DreamMaoMao** [comment]
It seems that all electron xwayland apps are unable to copy text to the clipboard

**Comment by Kommynct** [comment]
This probably fixes it, haven't gotten the chance to test yet.

bindntr=CTRL,C,exec,hyprctl activewindow | rg -q "xwayland: 0" && wl-paste | xclip -i || xclip -o | wl-copy

**Comment by vaxerski** [comment]
dupe as above, there's also another issue open iirc
