### ISSUE TITLE
v0.41.0 with legacyrenderer Compiling FAILED: CMakeFiles/Hyprland.dir/src/helpers/Format.cpp.o

### ISSUE THREAD

**Issue by ansdim1** [hyprwm/Hyprland#6442]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
hyprctl systeminfo
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)
legacyrenderer

System Information:
System name: Linux
Node name: b570
Release: 6.9.3-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:26 +0000

GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0106] (rev 09) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
  split-monitor-workspaces by Duckonaut ver 1.1.0
  Hyprspace by KZdkm ver 0.1
</details>

### Description

Compiling FAILED
I have no errors with flag **release**
I have no errors with flag legacyrenderer and v**0.40.0**

### How to reproduce

makepkg

### Crash reports, logs, images, videos

[out.txt](https://github.com/user-attachments/files/15805795/out.txt)
[PKGBUILD.txt](https://github.com/user-attachments/files/15805846/PKGBUILD.txt)

**Comment by ansdim1** [comment]
I can`t drop my old internal GPU without vulkan.

**Comment by vaxerski** [comment]
you can drop the laptop off a cliff. I've installed hyprland on a random-ass 12 year old hp laptop in the past and havent had to use legacy.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/15806972/patch.txt)
does this let you compile again?

**Comment by ansdim1** [comment]
errors in attachments
[out1.txt](https://github.com/user-attachments/files/15807879/out1.txt)
[PKGBUILD.txt](https://github.com/user-attachments/files/15807913/PKGBUILD.txt)

**Comment by vaxerski** [comment]
my bad
[patch.txt](https://github.com/user-attachments/files/15808777/patch.txt)

**Comment by ansdim1** [comment]
errors in attachment
[out2.txt](https://github.com/user-attachments/files/15809591/out2.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/15809713/patch.txt)
sorry again

**Comment by ansdim1** [comment]
Thanks for the quick response.  No errors now. But there are many problems with speed and transparency. I will describe them later.

**Comment by ansdim1** [comment]
Thanks for the quick response.  No errors now. But there are many problems with speed and transparency. I will describe them later.
