### ISSUE TITLE
Support dynamic rules for exec dispatcher

### ISSUE THREAD

**Issue by Pummelfisch** [hyprwm/Hyprland#6445]
# Current state
Currently, the exec dispatcher, whether used from a bind command or with hyprctl, do not seem to support dynamic rules. I noticed that when I wanted to execute a program with that and directly add a tag to it, with something like that:
```
hyprctl dispatch exec [pseudo,tag +filemanager] "alacritty -e yazi"
```
The pseudo rule is applied, but the tag is not added to the launched window. This behavior also occurs when using a bind command with exec and also with other dynamic rules like `noborder`.

# Proposed implementation
Maybe it is due to the nature of dynamic rules or some other reason I don't know, but it would be great to have the possibility to add dynamic rules to the exec dispatcher, just like with the static rules.

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/Hyprland/issues/6406

**Comment by Pummelfisch** [comment]
> #6406

Thank you, missed that.
