### ISSUE TITLE
Spawn firefox on a workspace base on firefox profile.

### ISSUE THREAD

**Issue by musicfunfan** [hyprwm/Hyprland#6448]
### Description

Hello, i do not know if this is possible, but i want to ask it anyway. I use Hyprland and FireFox on ArchLinux. And i also make use of the different profiles can someone have on FireFox. 

What i want is to have FireFox open(spawn) on a different work space based on the profile i am using. For example if i use the profile "streaming" i want to open FireFox on workspace 3. 

This is useful because i and many people ( i ques) use multiple profiles on browsers. For different tasks. And is nice to capture by the `` windowrulev2`` in order to control the windows property. 

Is this possible ?

**Comment by MightyPlaza** [comment]
the only way I see this working for firefox is if they allow you to start the profile with a cli argument
if so using exec rules might work (if they don't fork themselves)

**Comment by zakk4223** [comment]
You can set the profile name and the app_id on the command line.
Something like firefox --name=new_app --no-remote -P new_profile

**Comment by vaxerski** [comment]
yea, this is not a hyprlandi sue

**Comment by musicfunfan** [comment]
ok, yea understood the ``--name`` option works. Thanks for the idea.
