### ISSUE TITLE
IME popup offest with native chromium

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#645]
These flags are set
```
--ozone-platform-hint=auto
--enable-features=WaylandWindowDecorations
--gtk-version=4
```
you can easily produce this by opening a chromium window, type in the search bar, and you will find out the selection window is higher than normal

**Comment by vaxerski** [comment]
Check on sway. The popup is XWayland and thus resizes / moves itself.

**Comment by KyleUltimate** [comment]
oh, it breaks on sway, hyprland and plasma
so this is an fcitx5/xwayland issue, I'll close this issue then
