### ISSUE TITLE
mouse cursor visibility on mirrored screen

### ISSUE THREAD

**Issue by t1nux** [hyprwm/Hyprland#6455]
### Description

I *love* the mirror feature in hyprland, where I can eg. use

```monitor=DP-1,preferred,auto,auto,mirror,eDP-1```

in order to mirror `eDP-1` to `DP-1`. 

What I find particularly great about this is that the resolutions on both displays can be different! I use this a lot to present slides to students.

It seems though, that the mouse cursor is hidden on the screen that is mirrored **to** (`DP-1` in the example) from the main screen (`eDP-1`). However, if I want to highlight something on the screen by hovering over or circling around something on my screen (`eDP-1`) the mouse cursor is not visible on the other (`DP-1`) and the students cannot see it.

It seems this behavior (ie. hidden mouse cursor on the mirrored-to-screen) is on purpose, but in the case described above, a visible cursor on both screens would be nice.

Would it be possible to add a way to make this happen? It would not have to be the default, but some way to toggle this on/off would be great!

Have a great day everyone!

**Comment by MightyPlaza** [comment]
enable software cursors
not sure why they're required, but if it could work with hardware cursors I see no reason not to do it

**Comment by lucasreis1** [comment]
Are you using an NVIDIA GPU? AFAIK, this is not a feature, it's a bug introduced with the hardware cursors patch for Nvidia.

**Comment by t1nux** [comment]
> Are you using an NVIDIA GPU? AFAIK, this is not a feature, it's a bug introduced with the hardware cursors patch for Nvidia.

No, I am on AMD.

I thought the invisibility on the mirrored screen was a feature not a bug, based on [this](https://www.reddit.com/r/hyprland/comments/1al0f7u/cursor_not_visible_on_second_monitor/) (comment by Qweedo420). I think I also saw this some place else, but I do not find it right now.

In any case, I am very interested in the cursor appearing also on the mirrored-to-screen, and would not mind to convert this feature request into a bug report.

**Comment by lucasreis1** [comment]
> I thought the invisibility on the mirrored screen was a feature not a bug, based on [this](https://www.reddit.com/r/hyprland/comments/1al0f7u/cursor_not_visible_on_second_monitor/) (comment by Qweedo420). I think I also saw this some place else, but I do not find it right now.

You may be right, then. Perhaps having a mirrored cursor is also a bug present with software cursors. Anyway, you could always try using software cursors, and the cursor appears. Works for me on NVIDIA, at least.

```
cursor {
  no_hardware_cursors = true
}
```

**Comment by t1nux** [comment]
> ```
> cursor {
>   no_hardware_cursors = true
> }
> ```

That works! Thanks so much!

Should I just close this then, or is this a bug because of the hardware_cursor?

**Comment by lucasreis1** [comment]
Looks like not rendering the cursor when mirrored is a feature after all:
https://github.com/hyprwm/Hyprland/blob/main/src/render/Renderer.cpp#L1325-L1330

I'll try to submit a PR as I'm also not a fan of having no cursor when mirrored, so just leave this open for now.

**Comment by superDuperCyberTechno** [comment]
I don't know. It seems like something's fishy. I've been using the mirror feature for months now, yesterday I updated to

**Comment by MightyPlaza** [comment]
> I don't know. It seems like something's fishy. I've been using the mirror feature for months now, yesterday I updated Hyprland from 0.40 to 0.41 and today, the cursor is gone. It might be a coincidence, but it caught my eye.
> 
> Since I started using it, I've had this in my hyprland.conf
> 
> ```
> env = WLR_NO_HARDWARE_CURSORS,1
> ```
> 
> But that doesn't seem to work anymore.

it's has been removed in favor of the config variable above
