### ISSUE TITLE
Chrome startup page distortion

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6472]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

This commit 38132ffaf53c843a3ed03be5b305702fde8f5a49 distorts the chrome startup page. I'm not sure if this issue is a bug, if not I'll close this issue.

### How to reproduce

1. Need to add a chrome profile, no need to sign in to Google account
2. Start chrome with this command `google-chrome-stable --ozone-platform=wayland`

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/39702328/c20e9eed-f011-4ce6-901a-cf88eb583c7f

https://github.com/hyprwm/Hyprland/assets/39702328/d0f332cd-ba33-473f-97b6-afce3906b6a4

**Comment by vaxerski** [comment]
same as #1462
