### ISSUE TITLE
Build failure on debian

### ISSUE THREAD

**Issue by werdahias** [hyprwm/Hyprland#648]
Os: Debian testing
GCC: 12.2

log: 
```
meson _build
The Meson build system
Version: 0.63.2
Source dir: /home/werdahias/Packaging/hyprland-0.13.1beta
Build dir: /home/werdahias/Packaging/hyprland-0.13.1beta/_build
Build type: native build
Project name: Hyprland
Project version: 0.12.1beta
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-1) 12.2.0")
C linker for the host machine: cc ld.bfd 2.38.90.20220713
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-1) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.38.90.20220713
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -std=c++23: YES 
meson.build:14: WARNING: Consider using the built-in option for language standard version instead of using "-std=c++23".

meson.build:40:0: ERROR: Subproject exists but has no meson.build file

A full log can be found at /home/werdahias/Packaging/hyprland-0.13.1beta/_build/meson-logs/meson-log.txt
```
It doesn't matter if I use meson _build or meson build, the result is the same. This seems like a bug to me.

**Comment by viperML** [comment]
Did you do a recursive clone for the wlroots submodule?

**Comment by naythanN** [comment]
I have compiled with cmake on debian testing, I haven't used it much yet, but it works.

**Comment by vaxerski** [comment]
well then whats the issue?

**Comment by werdahias** [comment]
Ah, my bad. Is there a way to build the source without cloning the wslroots package?

**Comment by vaxerski** [comment]
no.

You can use the release source tarball though it has the wlroots source cloned already

**Comment by werdahias** [comment]
hm. I'd like to package hyprland for debian/ubuntu eventually. Debian doesn't allow included sources of other programs though. That's kinda my issue here. the libwlroots-dev package is already in debian

**Comment by vaxerski** [comment]
build with meson, link statically and distribute that.

**Comment by werdahias** [comment]
The problem is I'd have to remove the src/wlroots and built it which doesn't work afaik

**Comment by eli-schwartz** [comment]
> hm. I'd like to package hyprland for debian/ubuntu eventually. Debian doesn't allow included sources of other programs though. That's kinda my issue here. the libwlroots-dev package is already in debian

https://github.com/hyprwm/Hyprland/issues/302#issuecomment-1174165318

This has already been discussed. The opinion of the Hyprland developers is:
> ok and? If $DISTRO does not want to package Hyprland, I will not force them. Their decision. I have a requirement. If a distro is unwilling to fulfill it, cool.

Oh, also if someone makes an unofficial Hyprland package that conflicts with the system wlroots:
> in which case I'll have him prosecuted for violating the geneva convention

**Comment by vaxerski** [comment]
> Oh, also if someone makes an unofficial Hyprland package that conflicts with the system wlroots:

> in which case I'll have him prosecuted for violating the geneva convention

no, that was only to t1c cuz he made a mistake in the aur pkgbuild

> The problem is I'd have to remove the src/wlroots and built it which doesn't work afaik

you can distribute compiled binaries.

**Comment by werdahias** [comment]
Would it be alright with you if I submiited a MR which allows having a meson option like NATIVE_WLROOTS so I can fulfill debian policy?

**Comment by viperML** [comment]
https://github.com/hyprwm/Hyprland/pull/552

**Comment by eli-schwartz** [comment]
> so I can fulfill debian policy?

Debian policy cannot be fulfilled.

- Debian demands that dependencies use system versions, not vendoring.
- Hyprland demands that the latest development commits of wlroots, complete with API-breaking changes, is used.

Adding an option to comply with Debian policy would only help if the project development velocity is simultaneously changed to no longer make use of in-development APIs. @vaxerski does not wish to do this, so I'm not sure there's much else to discuss.

**Comment by vaxerski** [comment]
> Hyprland demands that the latest development commits of wlroots, complete with API-breaking changes, is used.

not exactly, Hyprland demands the wlroots commit it has pinned. We have used the HEAD before, but I'd like to avoid failed builds whenever the HEAD pushes a breaking change.

> Adding an option to comply with Debian policy would only help if the project development velocity is simultaneously changed to no longer make use of in-development APIs. @vaxerski does not wish to do this, so I'm not sure there's much else to discuss.

Hyprland is meant to be bleeding-edge. We want to allow users to take advantage of the latest protocols and features that we are granted by the Wayland Gods.

Although Hyprland should work 95% of the times with wlroots-git, it will **never** be guaranteed.
