### ISSUE TITLE
Screen flickering when the refresh rate is low.

### ISSUE THREAD

**Issue by DHWIDSA** [hyprwm/Hyprland#649]
## Steps to reproduce
Set the refresh rate lower than my monitor's default.
## Expected outcome
The screen display images properly without flickering.
## Noted outcome
The screen flickering.
When the refresh rate is lower than 30,the screen flickering with some horizental white lines.

**Comment by vaxerski** [comment]
does it also happen in sway? seems like a monitor issue

**Comment by DHWIDSA** [comment]
> does it also happen in sway? seems like a monitor issue
sway cannot set a refresh rate that does not exist in the wlr-randr output, and will fallback to the default refresh rate.But hyprland can (this may cause the displayed screen to flicker)

Trying to set the refresh rate supported in wlr-randr solved the problem.

**Comment by DHWIDSA** [comment]
> does it also happen in sway? seems like a monitor issue

sway cannot set a refresh rate that does not exist in the wlr-randr output, and will fallback to the default refresh rate.But hyprland can (this may cause the displayed screen to flicker)
Trying to set the refresh rate supported in wlr-randr solved the problem.

**Comment by vaxerski** [comment]
then its not my problem when you're trying to set an unsupported resolution, is it?

**Comment by DHWIDSA** [comment]
I think hyprland should also automatically fall back to the default refresh rate,like sway
