### ISSUE TITLE
v0.41.1  BrightnessUp keybind executing Volume and Microphone mute

### ISSUE THREAD

**Issue by PxRyzl** [hyprwm/Hyprland#6490]
### Bug or Regression?

Bug

### System Info and Version

Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)

System Information:
System name: Linux
Node name: ZeonGenesis
Release: 6.6.32-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 25 May 2024 20:20:51 +0000

GPU information: 
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c2) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/PxRyzl/.config/hypr/hyprland.conf: Read Succeeded
#Setup monitors
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,1920x1080@60,0x0,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = ~/Documents/Script/startupsound.sh
exec-once = ~/.config/hypr/scripts/batterynoti
exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swaybg
exec-once = waypaper --restore --backend hyprpaper #~/.config/hypr/scripts/startwall
exec-once = waybar
exec-once = swaync
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = steam -silent
exec-once = discord --start-minimized
exec-once = whatsie
exec-once = wl-paste --watch cliphist store
exec-once = unclutter --idle 5 -root &
exec = ~/.config/hypr/scripts/wybr
exec-once = reflector

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant = 
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
	disable_while_typing = false
	clickfinger_behavior = true
    }

    sensitivity =  0.1 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2 #5
    gaps_out = 5 #10
    border_size = 3
    col.active_border= rgb(cf4a72) rgb(1793d1) 15deg
    col.inactive_border = rgba(69263aaa) rgba(1d2951aa) 15deg

    layout = dwindle
}

misc {
    disable_hyprland_logo = true
    initial_workspace_tracking = 0
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 7
    
    blur {
        enabled = true
        size = 1
        passes = 3
        new_optimizations = true
    }

    blurls = lockscreen

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    #col.shadow = rgba(a1a1aee)
}

animations {
    enabled = true

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.10, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier, slide
    animation = windowsOut, 1, 7, myBezier, slide
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = true
    workspace_swipe_create_new = false
    workspace_swipe_direction_lock = false
    workspace_swipe_forever = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
# Mouse
device {
    name = 2.4g-wireless-optical-mouse--mouse
    sensitivity = 0.1
}

#windowrule v1
#float
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(nemo)$
windowrule = float,^(thunar)$
windowrule = float,^(feh)$
windowrule = float,^(Geeqie)$
windowrule = float,^(lutris)$
windowrule = float,^(waypaper)$
windowrule = float,^(obsidian)$
windowrule = float,^(nwg-look)$
#fullscreen
windowrule = fullscreen,^(gzdoom)$
windowrule = fullscreen,^(mpv)$
windowrule = fullscreen,^(waydroid)$

#windowrule v2
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# rules below would make the specific app transparent
# Kitty
windowrulev2 = opacity 0.8 0.8,class:^(kitty)$
# Thunar
windowrulev2 = animation popin,class:^(thunar)$
windowrulev2 = opacity 0.9 0.9,class:^(thunar)$
# VSCodium
windowrulev2 = opacity 0.windowOut,class:^(VSCodium)$
# Wofi
windowrulev2 = animation windowOut,class:^(wofi -n)$
windowrulev2 = opacity 0.8 0.8,title:^()$,class:^(wofi)$
windowrulev2 = stayfocused,title:^()$,class:^(wofi)$
# Steam
windowrulev2 = center,title:^(Steam Dialog)$,class:^(Steam)$
windowrulev2 = stayfocused,title:^(Steam Dialog)$,class:^(Steam)$
windowrulev2 = minsize 1 1,title:^()$,class:^(Steam)$
# Deadbeef
windowrulev2 = opacity 0.9 0.9,class:^(deadbeef)$

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$Spr = SUPER
$Script = ~/.config/hypr/scripts

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
# Volume
binde = Control, F10, exec, $Script/volume --dec
binde = Control, F11, exec, $Script/volume --inc
binde = Control, F9, exec, $Script/volume --toggle
binde = Control, F8, exec, $Script/volume --toggle-mic
# Brightness
binde = Control, F3, exec, $Script/brightness --dec
binde = Control, F4, exec, $Script/brightness --inc

bind = $Spr, Q, exec, kitty  # open the terminal
bind = ALT, F4, killactive, # close the active window
bind = ALT, escape, exec, hyprctl kill # kill an active window 
bind = $Spr, F, fullscreen # fullscreen active window
bind = $Spr, L, exec, hyprlock # Lock the screen
bind = $Spr, M, exec, wlogout --protocol layer-shell # show the logout window
bind = $Spr SHIFT, M, exit, # Exit Hyprland all together no (force quit Hyprland)
bind = $Spr, E, exec, thunar # Show the graphical file browser
bind = $Spr, V, togglefloating # Allow a window to float
bind = $Spr, return, centerwindow # Center a floating window
bind = $alt, SPACE, exec, wofi -n # Show the graphical app launcher
bind = $Spr, P, pseudo, # dwindle
bind = $Spr, J, togglesplit, # dwindle
bind = ,Print, exec, grim $(xdg-user-dir PICTURES)/Screenshots/$(date +%Y%m%d-%H%M%S'.png')  # take a screenshot
bind = SHIFT, Print, exec, grim -g "$(slurp)" $(xdg-user-dir PICTURES)/Screenshots/$(date +%Y%m%d-%H%M%S'.png') # take a selection screenshot
bind = $Spr, Print, exec, hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - $(xdg-user-dir PICTURES)/Screenshots/$(date +%Y%m%d-%H%M%S'.png') # take screenshot on active window
bind = ALT, V, exec, cliphist list | wofi -dmenu | cliphist decode | wl-copy # open clipboard manager
bind = $Spr, W, exec, waypaper --random --backend swaybg #$Script/wallpaper # switch to random wallpaper
bind = $Spr SHIFT, W, exec, waypaper # Show the graphical wallpaper launcher

# Move focus with mainMod + arrow keys
bind = $Spr, left, movefocus, l
bind = $Spr, right, movefocus, r
bind = $Spr, up, movefocus, u
bind = $Spr, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $Spr, 1, workspace, 1
bind = $Spr, 2, workspace, 2
bind = $Spr, 3, workspace, 3
bind = $Spr, 4, workspace, 4
bind = $Spr, 5, workspace, 5
bind = $Spr, 6, workspace, 6
bind = $Spr, 7, workspace, 7
bind = $Spr, 8, workspace, 8
bind = $Spr, 9, workspace, 9
bind = $Spr, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $Spr SHIFT, 1, movetoworkspace, 1
bind = $Spr SHIFT, 2, movetoworkspace, 2
bind = $Spr SHIFT, 3, movetoworkspace, 3
bind = $Spr SHIFT, 4, movetoworkspace, 4
bind = $Spr SHIFT, 5, movetoworkspace, 5
bind = $Spr SHIFT, 6, movetoworkspace, 6
bind = $Spr SHIFT, 7, movetoworkspace, 7
bind = $Spr SHIFT, 8, movetoworkspace, 8
bind = $Spr SHIFT, 9, movetoworkspace, 9
bind = $Spr SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $Spr, mouse_down, workspace, e-1
bind = $Spr, mouse_up, workspace, e+1
bind = $Spr_alt, left, workspace, e-1
bind = $Spr_alt, right, workspace, e+1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $Spr, mouse:272, movewindow
bindm = $Spr, mouse:273, resizewindow

# trigger when the switch is toggled
bindl=,switch:on:Lid Switch,exec, hyprlock 

# Source a file (multi-file configs)
source = ~/.config/hypr/media-binds.conf
source = ~/.config/hypr/env_var.conf

Config File: /home/PxRyzl/.config/hypr/media-binds.conf: Read Succeeded
$SCRIPT = ~/.config/hypr/scripts

binde = , xf86audioraisevolume, exec, $SCRIPT/volume --inc
binde = , xf86audiolowervolume, exec, $SCRIPT/volume --dec 
binde = , xf86AudioMicMute, exec, $SCRIPT/volume --toggle-mic 
binde = , xf86audioMute, exec, $SCRIPT/volume --toggle 

bind = , xf86KbdBrightnessDown, exec, $SCRIPT/kb-brightness --dec 
bind = , xf86KbdBrightnessUp, exec, $SCRIPT/kb-brightness --inc 

bind = , xf86MonBrightnessDown, exec, $SCRIPT/brightness --dec 
bind = , xf86MonBrightnessUp, exec, $SCRIPT/brightness --inc 

Config File: /home/PxRyzl/.config/hypr/env_var.conf: Read Succeeded
# Environment Variables
# see https://wiki.hyprland.org/Configuring/Environment-variables/ 

# Theming Related Variables
# Set cursor size. See FAQ below for why you might want this variable set.
# https://wiki.hyprland.org/FAQ/
env = XCURSOR_SIZE,24

# Set a GTK theme manually, for those who want to avoid appearance tools such as lxappearance or nwg-look
env = GTK_THEME,

# Set your cursor theme. The theme needs to be installed and readable by your user.
env = XCURSOR_THEME,

# the line below may help with multiple monitors
#env = WLR_EGL_NO_MODIFIERS,1

#XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Toolkit Backend Variables

# GTK: Use wayland if available, fall back to x11 if not.
#env = GDK_BACKEND,wayland,x11

# QT: Use wayland if available, fall back to x11 if not.
#env = QT_QPA_PLATFORM,wayland,xcb

# Run SDL2 applications on Wayland. Remove or set to x11 if games that 
# provide older versions of SDL cause compatibility issues
#env = SDL_VIDEODRIVER,wayland 

# Clutter package already has wayland enabled, this variable 
#will force Clutter applications to try and use the Wayland backend
#env = CLUTTER_BACKEND,wayland 

# QT Variables

# (From the QT documentation) enables automatic scaling, based on the monitor’s pixel density
# https://doc.qt.io/qt-5/highdpi.html
#env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# Tell QT applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable
#env = QT_QPA_PLATFORM,wayland,xcb

# Disables window decorations on QT applications
#env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

#Tells QT based applications to pick your theme from qt5ct, use with Kvantum.
env = QT_QPA_PLATFORMTHEME,qt5ct

======Config-End========

### Description

Whenever I tried to turn up the brightness of my laptop with the brightness up it will also toggle the volume and microphone mute.
This only happen in the version 0.41.0

### How to reproduce

https://github.com/PxRyzl/dotfiles/blob/e6ff75ced54733c78085ea25861a3ab299d1dc8d/.config/hypr/media-binds.conf#L1-L12
Use this script to control brightness then set the media-binds.conf of hyprland like this 
https://github.com/PxRyzl/dotfiles/blob/e6ff75ced54733c78085ea25861a3ab299d1dc8d/.config/hypr/scripts/brightness#L1-L52
and then press the brightnessup button on your laptop

### Crash reports, logs, images, videos

https://github.com/PxRyzl/dotfiles/blob/e6ff75ced54733c78085ea25861a3ab299d1dc8d/.config/hypr/media-binds.conf#L1-L12

https://github.com/PxRyzl/dotfiles/blob/e6ff75ced54733c78085ea25861a3ab299d1dc8d/.config/hypr/scripts/brightness#L1-L52

**Comment by vaxerski** [comment]
use `wev` to figure out keysyms. I doubt this is a hyprland issue.

If you say it's only 0.41, bisect: https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue

But I doubt it's our problem
