### ISSUE TITLE
Hyprland crashing on launch with std::invalid_argument

### ISSUE THREAD

**Issue by RadicalityIncident** [hyprwm/Hyprland#6506]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

On Arch after updating hyprland-git to the latest commit I am unable to launch Hyprland. Not sure exactly what commit broke it as I only update hyprland every couple of weeks. No changes were made to my config file between working and non working states.  As I can't run Hyprland I cannot attach the output of hyprctl systeminfo but I have attached my crash report and config file below

### How to reproduce

Launch Hyprland with the attached config file. 

### Crash reports, logs, images, videos

[hyprlandCrashReport14587.txt](https://github.com/user-attachments/files/15846283/hyprlandCrashReport14587.txt)
[hyprland-conf.txt](https://github.com/user-attachments/files/15846286/hyprland-conf.txt)

**Comment by vaxerski** [comment]
fixed in https://github.com/hyprwm/hyprutils/commit/ea8fd1d3eaaf0cea34792315a15ed0cabcbccadb
