### ISSUE TITLE
Gesture animation is bugg with fullscreen windows

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#651]
I will upload a video

**Comment by godalming123** [comment]
https://user-images.githubusercontent.com/68993177/189475825-9a4d57cc-17d9-4411-ac01-2bf895fa2d72.mp4

**Comment by godalming123** [comment]
https://user-images.githubusercontent.com/68993177/189475825-9a4d57cc-17d9-4411-ac01-2bf895fa2d72.mp4

**Comment by godalming123** [comment]
https://user-images.githubusercontent.com/68993177/189475957-b4551fa9-6fdd-4359-8851-08827b1728f1.mp4

**Comment by Estebiu** [comment]
Can reproduce on my end.

**Comment by vaxerski** [comment]
check with a09c614c2d2e4317cf6b9bd797784ab2ac94bcf0

**Comment by godalming123** [comment]
When switch from fullscreen to non fullscreen the bug is still present it also happens when switching from fullscreen to fullscreen but is fixed for non fullscreen to fullscreen

**Comment by vaxerski** [comment]
fixed alongside adding some nice ls animations for fullscreen in 7c809a3059388b8fdbb3de4aca68656c01162f4f
