### ISSUE TITLE
Distorted hyprcursor after 0.40.0 update

### ISSUE THREAD

**Issue by Gigas002** [hyprwm/Hyprland#6517]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: gigas-acer
Release: 6.9.4-x64v3-xanmod1
Version: #0~20240612.gadde0ab SMP PREEMPT_DYNAMIC Wed Jun 12 20:03:38 UTC


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c6) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux


plugins:

```

</details>

### Description

As title says, after `0.40.0` update the `hyprcursor` is looking distorted comparing to xcursor (was working fine before update). I'm setting cursors through config this way:

```conf
# GTK cursors
# https://wiki.archlinux.org/title/GTK
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'
exec = gsettings set org.gnome.desktop.interface cursor-size 20
env = XCURSOR_THEME,Sweet-cursors
env = XCURSOR_SIZE,20

# hyprcursors
exec = hyprctl setcursor Sweet-cursors-hyprcursor 20
env = HYPRCURSOR_THEME,Sweet-cursors-hyprcursor
env = HYPRCURSOR_SIZE,20
```

Example of xcursor (1st one) and hyprcursor (2nd one) to see the difference:

![image](https://github.com/hyprwm/Hyprland/assets/24297712/3105e480-838a-4612-8ad7-2b4651baff4d)
![image](https://github.com/hyprwm/Hyprland/assets/24297712/44c250dc-3a16-4ba8-bacf-9f0687b4593e)

This is only one example, but you get the gist.
The hyprcursors's size also considerably smaller than xcursor variant.

The actual hyprcursor files are not distorted, e.g this is the same cursor file from `/usr/share/icons/Sweet-cursors-hyprcursor/hyprcursors/pointer.hlc/pointer_002.png`

![pointer_002](https://github.com/hyprwm/Hyprland/assets/24297712/a63e1825-c559-4c14-a533-88637526f33f)

Maybe related to #6320?

### How to reproduce

Build the hyprcursors from raw files with [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sweet-cursors-hyprcursor-git) or just install this package

### Crash reports, logs, images, videos

[conf.txt](https://github.com/user-attachments/files/15849141/conf.txt)

**Comment by vaxerski** [comment]
can you try a different hyprcursor theme to rule out a problem with the theme?

**Comment by vaxerski** [comment]
can you zip the buggy theme and attach it?

**Comment by Gigas002** [comment]
Sure thing

[Sweet-cursors-hyprcursor.zip](https://github.com/user-attachments/files/15858810/Sweet-cursors-hyprcursor.zip)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/6e8e112a-76e7-42c2-9f45-7e047bbfbf2d)

https://standards.hyprland.org/hyprcursor/

![20240616_17h44m33s](https://github.com/hyprwm/Hyprland/assets/43317083/f6bb148d-21fe-4c50-a725-b2e82c1289e7)

ripbozo, theme is not to spec
