### ISSUE TITLE
Hyprpm update failing

### ISSUE THREAD

**Issue by roflcow2** [hyprwm/Hyprland#6518]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Not sure what's going on, but trying to update hyprpm and getting this error. I read a bunch of other issues that seemed to be solved by dependency problems, but I don't see where this says I'm missing any packages. 

### How to reproduce

run hyprpm update

### Crash reports, logs, images, videos

[hyprpmerror.txt](https://github.com/user-attachments/files/15849285/hyprpmerror.txt)

**Comment by vaxerski** [comment]
christ brother update `Tag: v0.38.0-1-gc377caee`

**Comment by zakk4223** [comment]
Not that you can help this issue (only way to fix is to update) but you may want to change hyprpm so it does the git reset before the git submodule update. The reason for this error is the change from wlroots -> wlroots-hyprland.

**Comment by vaxerski** [comment]
I am not a git expert but you can make a MR if you know a better way I guess

**Comment by roflcow2** [comment]
> christ brother update `Tag: v0.38.0-1-gc377caee`

Damn bro you're right. Now I'm in a whole other mess trying to get hyprland to update. I've been busy and haven't had much time to sit at my pc in like 3 months and thought when I typed arch -syu and yay -syu it updated everything, but I specifically ran yay -S hyprland-git and now that's throwing me errors so that was clearly the problem. Welp if you know anything about hyprland not being able to find subprojects/wlroots that would be helpful because I have wlroots installed. If I should open a new issue I will.
