### ISSUE TITLE
How would you bind the XF86 Volume Control Keys in Hyprland?

### ISSUE THREAD

**Issue by vt-d** [hyprwm/Hyprland#652]

**Comment by vaxerski** [comment]
the amount of times I need to link the wiki is borderline comical.

https://wiki.hyprland.org/Configuring/Advanced-config/#uncommon-syms--binding-with-a-keycode

**Comment by lqlarry** [comment]
> the amount of times I need to link the wiki is borderline comical.
> 
> https://wiki.hyprland.org/Configuring/Advanced-config/#uncommon-syms--binding-with-a-keycode

Your link is a 404.  Until it is changed, try this. 

[]([](https://wiki.hyprland.org/Configuring/Binds/#bind-flags))
