### ISSUE TITLE
Compositor crashes when using `mouse_left` or `mouse_right` as input to a `wtype` command

### ISSUE THREAD

**Issue by WiredMic** [hyprwm/Hyprland#6530]
### Bug or Regression?

Regression

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: nixDesk
Release: 6.6.33
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Jun 12 09:13:03 UTC 2024


GPU information: 
0d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240612.cc54fb4"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Description

When I use my mouses horizontal scrolling to trigger wtype my compositor crashes out to sddm. 

The commands are
```hypr
bind = , mouse_left, exec, wtype -M ctrl -M shift -P Tab -m ctrl -m shift
bind = , mouse_right, exec, wtype -M ctrl -P Tab -m ctrl
```

This work when I was on Arch but now when I am on NixOS it does not. It is some time since I used Arch. Therefore the Hyprland version was also older.

### How to reproduce

Follow the Hyprland wiki I how to download Hyprland as a module in a flake system on NixOS. Use Home manager as a module and insert in the `home.nix` file:
```nix
 wayland.windowManager.hyprland = {
      enable = true;
      settings = {
          bind = [
              ", mouse_left, exec, wtype -M ctrl -M shift -P Tab -m ctrl -m shift"
              ", mouse_right, exec, wtype -M ctrl -P Tab -m ctrl"
          ];  
     };
};
```
launch Hyprland and press the left or right scroll wheel button.

ps.
I use and MX Ergo mouse. 

### Crash reports, logs, images, videos
[hyprland.log](https://github.com/user-attachments/files/15855550/hyprland.log)
[hyprlandCrashReport240569.txt](https://github.com/user-attachments/files/15855552/hyprlandCrashReport240569.txt)

**Comment by vaxerski** [comment]
can you get a debug stacktrace please https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by WiredMic** [comment]
I tried to build Hyprland from source with `make debug`. However, I could not find the necessary dependencies.  
I only need these:
```
...
   - uuid
   - wayland-server
   - wayland-client
   - wayland-cursor
   - gbm
   - hyprutils>=0.1.1
...
```
I could not find these in the nix package store and do not know where to look any further.

Is there an easier way?

I used this environment to compile.
[shell.nix.zip](https://github.com/user-attachments/files/15857577/shell.nix.zip)

**Comment by fufexan** [comment]
@WiredMic if you have the repo cloned, simply run `nix build '.?submodules=1#hyprland-debug`. If you want to go the `make` route, you can run `nix develop` first, and then run all desired commands.

**Comment by WiredMic** [comment]
Thanks for the tip. 
The issue was solved in the debug envorenment.

I got a picture of this screen. I think it is of the crash but I do not know.
![IMG_20240616_223114](https://github.com/hyprwm/Hyprland/assets/111731519/e55aab0b-c4db-4025-836d-55ffb4d7c50f)

**Comment by WiredMic** [comment]
I got this log from setting `debug:disable_logs=false` and crashing on a cleared desktop.
/home/rasmus/.cache/hyprland/hyprlandCrashReport231231.txt

**Comment by vaxerski** [comment]
looks like an old version to me? Can't be sure cuz stupid nix strips fucking hashes (I hate your os, @fufexan )

anyways I still need a debug stacktrace: https://github.com/hyprwm/Hyprland/issues/6530#issuecomment-2170959646

**Comment by fufexan** [comment]
@vaxerski only 0.40.0 had the hash stripped. New ver (landing in a few days) will even have your grandma's cakes.

Anyway 0.40 (confirmed by the NixOS version).

**Comment by vaxerski** [comment]
then maybe try git?

**Comment by WiredMic** [comment]
I dont know what I did but now it works. 
I found out I could not use my GPU. I changed to unstable nix packages. 
Then I moved away from the mesa drives on the [Hyprland wiki](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/) and over to the drivers in NixOS proper.
