### ISSUE TITLE
[BUG] window contents dont fill window after dispatch setfloating and movewindowpixel

### ISSUE THREAD

**Issue by v4u6h4n** [hyprwm/Hyprland#6533]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: desktop-0
Release: 6.9.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
13:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

For some applications if set window to float with `setfloating` and then resize the window with 'resizewindowpixel` the window contents do not resize to the window size. 

### How to reproduce

1. `hyprctl dispatch settiled title:<title>`
2. `hyprctl dispatch setfloating title:<title>`
3. `hyprctl dispatch resizewindowpixel exact x y,title:<title>`

### Crash reports, logs, images, videos

![2024-06-16-095944_hyprshot](https://github.com/hyprwm/Hyprland/assets/156973064/d8c16eef-3607-4f72-9fdd-71fd929b2131)

**Comment by vaxerski** [comment]
does it happen with anything but vs code?

**Comment by v4u6h4n** [comment]
Hey :-) yeah with Brave as well, don't think it's happened with anything else yet.

**Comment by vaxerski** [comment]
is this 100% reproducible? For me this happens very randomly and rarely which is tough to debug.

**Comment by v4u6h4n** [comment]
> is this 100% reproducible? For me this happens very randomly and rarely which is tough to debug.

Unfortunately it's the same for me, only happens some of the time. Not sure if this helps, but it does seem to be mostly restricted to `Brave`, `VSCodium` and `Obsidian`. It never seems to happen to `kitty`, and can't remember it happening to `Zotero`, `OBS` and `Dolphin`, which are the only other main applications I regularly use. I'm not entirely sure if `resizewindowpixel` is necessary, but I don't think I've seen it happen when only toggling between tiled and floating, and not resizing.

**Comment by vaxerski** [comment]
shoutout to @outfoxxed for a repro client

**Comment by v4u6h4n** [comment]
nice one!
