### ISSUE TITLE
Fcitx5 input box misaligned in xwayland

### ISSUE THREAD

**Issue by R0boter** [hyprwm/Hyprland#6534]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
                  -`                     Rav4n@Bullet
                 .o+`                    ------------
                `ooo/                    OS: Arch Linux x86_64
               `+oooo:                   Host: B650M AORUS ELITE AX (-CF)
              `+oooooo:                  Kernel: Linux 6.9.4-arch1-1
              -+oooooo+:                 Uptime: 1 hour, 6 mins
            `/:-:++oooo+:                Packages: 835 (pacman)
           `/++++/+++++++:               Shell: fish 3.7.1
          `/++++++++++++++:              Display (GM271U): 2160x3840 @ 60Hz
         `/+++ooooooooooooo/`            Display (GM271U): 3840x2160 @ 60Hz [External]
        ./ooosssso++osssssso+`           WM: Hyprland (Wayland)
       .oossssso-````/ossssss+`          Theme: Colloid-Grey-Dark-Compact-Dracula [GTK2/3]
      -osssssso.      :ssssssso.         Icons: Colloid-grey-dark [GTK2/3]
     :osssssss/        osssso+++.        Font: CodeNewRoman Nerd Font (12pt) [GTK2/3]
    /ossssssss/        +ssssooo/-        Cursor: Colloid-dark (24px)
  `/ossssso+/:-        -:/+osssso+-      Terminal: foot 1.17.2
 `+sso+:-`                 `.-/+oso:     Terminal Font: CodeNewRoman Nerd Font (8pt)
`++:.                           `-/+/    CPU: AMD Ryzen 9 7900X (24) @ 5.73 GHz
.`                                 `/    GPU: AMD Raphael @ 2.20 GHz [Integrated]
                                         Memory: 3.11 GiB / 29.02 GiB (11%)
                                         Swap: Disabled
                                         Disk (/): 81.62 GiB / 936.84 GiB (9%) - ext4
                                         Local IP (enp11s0): 192.168.8.247/24 *
                                         Locale: zh_CN.UTF-8
```

</details>

### Description

if i only open a xwayland app, when i change the input language to chinese the candidate box will displays on the top left corner of the screen, and then i open a foot terminal,fcitx5 become is normal.

### How to reproduce

using hyprland-git with aur, open a xwayland app like firfox or wezterm, change input mode to chinese(i using the hotkey is left-shift), and then you can see the candidate box will display on the top left corner of the screen, and then open a footclient and focuse firfox or wezterm, the fcitx5 is become normal, input chinese is ok

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/41858428/16a51b69-9102-4766-90d6-2783aec8fcd9)
![image](https://github.com/hyprwm/Hyprland/assets/41858428/6a7a3242-df5f-43b4-9c90-119809aacd76)

**Comment by vaxerski** [comment]
can't repro, please post output of `hyprctl version` and a hyprland log

**Comment by R0boter** [comment]
> can't repro, please post output of `hyprctl version` and a hyprland log

![image](https://github.com/hyprwm/Hyprland/assets/41858428/bb416074-f68c-4be2-a07a-77e4859eb85a)

~ ❯❯❯ cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 2 | tail -n 1)/hyprland.log
[LOG] Instance Signature: 1f5fd7e64a1c0e8d1815bdd6d168193bf9c28d6d_1718596496_835728243
[LOG] Runtime directory: /run/user/1000/hypr/1f5fd7e64a1c0e8d1815bdd6d168193bf9c28d6d_1718596496_835728243
[LOG] Hyprland PID: 777
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: Bullet
[LOG] Release: 6.9.4-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000


[LOG] GPU information:
0f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c2) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: Wir sind schon sehr lang zusammen...


[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 335.17µs. Estimated average calc time: 0.04µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 4.61µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/Rav4n/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug

**Comment by R0boter** [comment]
and this is my [config files](https://github.com/Rav4n-T/dotfiles/tree/main/hypr)
thanks for your help!

**Comment by R0boter** [comment]
I rollback to v0.39.1, this version not have this bug

**Comment by hdm9527** [comment]
I can reproduce it.

1. Start chromium(xwl) and kitty in the same workspace order.
2. In kitty use ctrl+space to switch to Chinese input method, then close kitty.
3. In chromium press ctrl+space to switch input mode, ime popup appears in the upper left corner of the screen.

https://github.com/hyprwm/Hyprland/assets/39702328/8b1375fd-f487-4a22-9829-ef0d8d11e561

**Comment by hdm9527** [comment]
> I can reproduce it.
> 
> 1. Start chromium(xwl) and kitty in the same workspace order.
> 2. In kitty use ctrl+space to switch to Chinese input method, then close kitty.
> 3. In chromium press ctrl+space to switch input mode, ime popup appears in the upper left corner of the screen.
> 
>  ime-popup.mp4

@vaxerski

**Comment by vaxerski** [comment]
I do realize, but am busy. Feel free to work on a fix yourself.

**Comment by R0boter** [comment]
this bug maybe fixed with new version, so i close this issue.
thanks for your job!

**Comment by moetayuko** [comment]
appears to be a dup of https://github.com/hyprwm/Hyprland/issues/5288
