### ISSUE TITLE
cannot start Hyprland on freshly installed gentoo

### ISSUE THREAD

**Issue by rafaeljacov** [hyprwm/Hyprland#6539]
after setting the xdg runtime dir variable I now get another error saying wlr backend autocreate failed.
 I installed using instructions from gentoo wiki

**Comment by rafaeljacov** [comment]
![Uploading IMG_20240616_190302.jpg…]()

**Comment by UjinT34** [comment]
Try `emerge "<gui-wm/hyprland-0.40"` or build and install hyprland with dependencies from git manually. 
`gui-wm/hyprland-9999` won't work because it lacks some dependencies.

**Comment by rafaeljacov** [comment]
SOLVED: XDG_RUNTIME_DIR needs to be exported in shell config (eg. .bashrc) and then set as env on hyprland config. that fixes it

**Comment by gksudolol** [comment]
> `gui-wm/hyprland-9999` won't work because it lacks some dependencies.

Yeahh for this reason i have hyprland+deps in a local overlay instead :/

I've not had to set any XDG envs on Gentoo..
