### ISSUE TITLE
Unique workspaces per monitor

### ISSUE THREAD

**Issue by kavulox** [hyprwm/Hyprland#654]
I've been messing around with writing scripts to do it for me, but I've never been able to directly make it so when I try to move a window to a different workspace (or change workspaces) to stay on the same monitor as I'm using. I think it would be cool to make that a built in feature, I'd work on it myself, but I am not familiar with C++. Hope everyone has a great day!

**Comment by vaxerski** [comment]
? please explain better?

You mean that when you switch to a workspace it always appears on your focused monitor?

**Comment by kavulox** [comment]
> ? please explain better?
> 
> You mean that when you switch to a workspace it always appears on your focused monitor?

Yeah sorry I didnt explain well. Basically what I meant was unique workspaces for each monitor. I guess the best X11 comparison would be BSPWM vs DWM, where in BSPWM by default the workspaces are shared between all monitors, but with DWM the tags/workspaces are unique per.

**Comment by vaxerski** [comment]
```
bind=SUPER,1,focusmonitor,[MON1]
bind=SUPER,1,workspace,1

...
```
???

**Comment by kavulox** [comment]
Sorry I'm stupid and didnt notice that, I apologize for wasting your time.

**Comment by kavulox** [comment]
> ? please explain better?
> 
> You mean that when you switch to a workspace it always appears on your focused monitor?

Edit: "You mean that when you switch to a workspace it always appears on your focused monitor?"
This is what I meant, I apologize for asking very badly, is there anyway to do that (with retaining the same keybinds for each monitor)

**Comment by vaxerski** [comment]
sec

**Comment by vaxerski** [comment]
recompile with f024d7114fe08f505ec9af40ee8cd471fbb6c09b

then
```
bind=SUPER,1,moveworkspacetomonitor,1 current
bind=SUPER,1,workspace,1
```

**Comment by kavulox** [comment]
Thanks, sorry again.

**Comment by D3faIt** [comment]
Is it possible to move the window to another monitor by using the same shortcut as moving a window within the same monitor?

e.g having 3 monitors, moving the window from the right monitor to the left could be; mod+shift+Left and mod+shift+Left again

**Comment by vaxerski** [comment]
no
