### ISSUE TITLE
Ability to select previous workspace per monitor

### ISSUE THREAD

**Issue by leon-erd** [hyprwm/Hyprland#6545]
### Description

Currently there only exists the `previous` parameter to select a workspace.
It would be really nice to have a `previous_per_monitor` parameter that selects the previously focused workspace on the currently focused monitor. This means it will select a different workspace depending on what monitor you are on.
For me this would be really convenient since I usually focus the different monitors just by moving the mouse (having no benefit from the current `previous` parameter) and the `$mainMod + Tab` keybind is really easy to reach which is why I use it very often. Also when moving the mouse a lot it is hard to remember what the previous workspace was whereas it is really easy to remember the previous workspace on a monitor resulting in more intentional usage of keybinds. This new parameter would greatly improve my workflow!
On a single monitor setup the behaviour is identical to the current `previous` parameter.

**Comment by Truenya** [comment]
Can i try this?

**Comment by vaxerski** [comment]
feel free

**Comment by leon-erd** [comment]
@Truenya works like a charm! Thanks for implementing this so fast :)
Only thing I noticed:
1. go to monitor 1
2. open two workspaces with apps on it
3. use dispatcher `movecurrentworkspacetomonitor` to move one of the workspaces to monitor 2
4. go back to monitor 1
5. dispatcher `workspace, previous_per_monitor` will change to monitor 2 instead of staying on 1

For me this is no big deal :) I dont know if you want to fix that so I will just close this issue.

**Comment by Truenya** [comment]
@leon-erd can u please create an issue with this?
