### ISSUE TITLE
input:sensitivity won't work as expected

### ISSUE THREAD

**Issue by VPavliashvili** [hyprwm/Hyprland#6549]
### Bug or Regression?

Bug

### System Info and Version
<details><summary>System/Version info </summary>
`Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)

System Information:
System name: Linux
Node name: dorthonion
Release: 6.9.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti] [10de:2486] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Intel Corporation DG2 [Arc A310] [8086:56a6] (rev 05) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/stranger/.config/hypr/hyprland.conf: Read Succeeded
# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto

monitor=HDMI-A-3, 1920x1080, 0x0, 1, transform, 1
monitor=DP-1, 2560x1440@165.00, 1080x525, 1.25
monitor=DP-2, 1920x1080@144.00, 3128x0, 1, transform, 1 

workspace = 1,monitor:DP-1
workspace = 2,monitor:DP-1
workspace = 3,monitor:DP-1
workspace = 4,monitor:DP-1
workspace = 5,monitor:DP-1
workspace = 6,monitor:DP-1
workspace = 7,monitor:HDMI-A-3
workspace = 8,monitor:DP-1
workspace = 9,monitor:DP-1
workspace = 10,monitor:DP-2

exec-once=handle_monitor_connect.sh

exec-once=swaybg -i ~/Pictures/wallpapers/onedark/cyberpunk-sword.png
exec = ~/.config/hypr/mouse_sensitivity.sh -0.75

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user restart xdg-desktop-portal.service
exec-once = sleep 2 && /usr/libexec/xdg-desktop-portal-hyprland -r 
exec-once = ~/bin/launch-waybar.sh
exec-once = ~/bin/waybar_ipc
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once = /usr/bin/hyprland-per-window-layout
exec-once = nm-applet
exec-once = blueman-applet
exec-once = openrgb --startminimized
#from screen sharing on hyprland wiki
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24

group {
    groupbar {
        stacked = true
        font_size = 11
    }
}

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us,ge
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =
    sensitivity = -0.75

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2
    gaps_out = 2
    border_size = 1
    col.active_border = rgba(4ca6b5ee) rgba(33ccffee) 90deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 1
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = on
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
    layerrule = blur,waybar
}

misc {
    disable_splash_rendering = true
}

animations {
    enabled = no

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
    no_gaps_when_only = 1	
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = false
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

binds {
    workspace_back_and_forth = true
    workspace_center_on = 1
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
# device:epic-mouse-v1 {
#     sensitivity = -0.5
# }

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = float, ^(yad)$
windowrule = noanim, ^(yad)$

windowrule = workspace 2 silent, ^(.*brave.*)$
windowrule = workspace 5 silent, ^(.*openrgb.*)$
windowrule = workspace 8 silent, ^(steam)$
windowrule = workspace 8 silent, ^(Steam)$
windowrule = workspace 8 silent, ^(.*lutris.*)$
windowrule = workspace 8 silent, ^(.*battle\.net.*)$
windowrule = maximize, ^(.*battle\.net.*)$
windowrule = workspace 7 silent, ^(.*Microsoft Teams.*)$
windowrule = workspace 7 silent, ^(.*discord.*)$
windowrule = workspace 7 silent, ^(.*WebCord.*)$
windowrule = workspace 6 silent, ^(.*virt-manager.*)$
windowrule = workspace 10 silent, title:^(Spotify.*)$
windowrule = workspace 4 silent, ^(.*LanMouse.*)$

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, RETURN, exec, foot
bind = $mainMod, Q, killactive, 
bind = $mainMod, D, exec, fuzzel
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -
bind = $mainMod, V, exec, cliphist list | wofi -dmenu | cliphist decode | wl-copy
bind = $mainMod SHIFT, X, exec, swaylock --indicator --clock  -e -F -S -k --effect-scale 0.3 -r --effect-vignette 0.2:7

# audio and mic
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind = $mainMod SHIFT, M, exec, ~/.config/waybar/scripts/audio/change_state.py

# laptop brightness
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+

# media control
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86audiostop, exec, playerctl stop

# touchpad toggling on laptop
bind = , XF86TouchpadToggle, exec, ~/.config/hypr/toggle-touchpad.sh

# movement and dispatching
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bind = $mainMod CTRL, H, resizeactive, -20 0
bind = $mainMod CTRL, L, resizeactive, 20 0
bind = $mainMod CTRL, K, resizeactive, 0 -20
bind = $mainMod CTRL, J, resizeactive, 0 20

bind = $mainMod, F, fakefullscreen,
bind = $mainMod SHIFT, F, fullscreen,
bind = $mainMod SHIFT, space, togglefloating 
bind = $mainMod, G, togglegroup
bind = $mainMod, K, changegroupactive, b
bind = $mainMod, J, changegroupactive, f
bind = $mainMod, A, moveintogroup, l 
bind = $mainMod, A, moveintogroup, r
bind = $mainMod, E, moveoutofgroup

bind = $mainMod SHIFT, P, pseudo, # dwindle
bind = $mainMod, T, togglesplit, # dwindle

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# bind = $mainMod  

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# reminna/vm keygrab solution
# bind = CTRL, Delete, submap, clean
# see https://wiki.hyprland.org/Configuring/Binds/#submaps for more
bind = $mainMod, Delete, submap, grabOn
submap = grabOn
bind = $mainMod SHIFT, Delete, submap, reset
submap = reset

bind = $mainMod SHIFT, V, submap, vms
submap = vms
bind = ,1,exec,~/.config/hypr/run_vm.sh -n win10_gaming
bind = ,1,submap,reset
bind = ,2,exec,~/.config/hypr/run_vm.sh -n win10_dev_environment
bind = ,2,submap,reset
bind = ,6,exec,~/.config/hypr/run_vm.sh -n linux_remmina -g -w 6 -f
bind = ,6,submap,reset
bind = ,7,exec,~/.config/hypr/run_vm.sh -n linux_teams -g -w 7 -k
bind = ,7,submap,reset
bind = ,a,exec,~/.config/hypr/run_vm.sh -n linux_remmina -g -w 6 -f && ~/.config/hypr/run_vm.sh -n linux_teams -g -w 7 -k
bind = ,a,submap,reset
bind = ,x,exec,virsh --connect qemu:///system shutdown linux_remmina && virsh --connect qemu:///system shutdown linux_teams
bind = ,x,submap,reset
bind = ,escape,submap,reset
submap = reset

bind = $mainMod, P, submap, runner
submap = runner

bind = ,O,exec,wofimoji
bind = ,O,submap,reset

bind = ,W,exec,~/.config/hypr/run_work_layout.sh
bind = ,W,submap,reset

bind = ,H,exec,~/.config/hypr/run_home_layout.sh
bind = ,H,submap,reset

bind = ,escape,submap,reset
submap = reset

======Config-End========`
</details>

### Description

Today updated hyprland from version `0.39.1-5` to `0.41.1-1` after that `keyword input:sensitivity $val` command does not work for float parameters anymore.
E.g. this works `hyprctl keyword input:sensitivity -1` (or 1)
and this returns 'help menu' and has no effect on input speed `hyprctl keyword input:sensitivity -0.75` (or 0.75)

before the update both was working as fine. Tried to look up in wiki but nothing was seemed to be changed. Am I missing something after the update?

I checked the source code and latest related change seems to be [this](https://github.com/hyprwm/Hyprland/blob/d5ef10abf429355246abcda65fe4c15d886fad7c/src/config/ConfigManager.cpp#L452) which was 4 months ago.

If I am doing something wrong please inform me

### How to reproduce

run this command from bash
 `hyprctl keyword input:sensitivity -0.75`

**Comment by vaxerski** [comment]
`hyprctl keyword input:sensitivity -- -0.75`?

**Comment by Agent00Ming** [comment]
Sounds like another case of high-res scrolling not being supported by the application because you can't be rounding discrete scrolling from 1 (or -1) to 0 or else scrolling breaks in certain applications that expect a non-zero discrete scrolling event. See https://github.com/hyprwm/Hyprland/pull/6317#issuecomment-2145033392. Maybe I'll write another patch to not send discrete scrolling events at all if the delta is less than 120 and only send the value120 instead...

**Comment by VPavliashvili** [comment]
Oh I was missing `--`, thanks vaxry
