### ISSUE TITLE
Do not allocate tiling space for application started in Full-Screen mode

### ISSUE THREAD

**Issue by KAGEYAM4** [hyprwm/Hyprland#6553]
### Description

Currently the when a new-window is opened with either `fullscreen` rule or application itself launching in fullscreen mode, even though the application will cover whole screen, hyprland allocated a space in current workspace which i think also creates some buggy animation and then window is full-screened. Now if i directly Quit/Close the window when i am in full-screen, the window disappears and tiled-space is released by another application maximizing itself in that Space.

By having this feature as a window rule, it will improve animation in cases where a newly created window start as fullscreen and the window is Quit/Close in that full-screen mode only. This way no allocation/deallocation of tiling space is needed.

Example - 

[Kooha-2024-06-17-11-47-28.webm](https://github.com/hyprwm/Hyprland/assets/75798544/5cbe5492-0f5b-4997-a0c2-8e6821a79041)

**Comment by vaxerski** [comment]
#683
