### ISSUE TITLE
Hyprland crashes when opening images in the xwayland app.

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6555]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit b15be9c77de593581007de53b2bbca97d121900a  (xwayland: do not set a new data source if it has no MIMEs).
Date: Mon Jun 17 03:34:17 2024
Tag: v0.41.1-33-gb15be9c7, commits: 4851

flags: (if any)
```

</details>

### Description

Hyprland crashes when opening an image in the xwayland app, can't reproduce it when starting Hyprland again.

### How to reproduce

I haven't found a way to reproduce it.

### Crash reports, logs, images, videos

[hyprlandCrashReport94453.txt](https://github.com/user-attachments/files/15863431/hyprlandCrashReport94453.txt)
![image](https://github.com/hyprwm/Hyprland/assets/39702328/9f1848c5-1365-47e3-af79-c32db0db0b20)

**Comment by vaxerski** [comment]
#5321
