### ISSUE TITLE
Hyprland crashes in jetbrains IDE

### ISSUE THREAD

**Issue by RaphaelZa** [hyprwm/Hyprland#6556]
### Bug or Regression?

Bug

### System Info and Version

`
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)

System Information:
System name: Linux
Node name: t14
Release: 6.9.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000

GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev dd) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Description

When using Jetrains IDEs like IntelliJ, either hyprland crashes or the program crashes and can't be opened again.
Unfortunately no crash reports were created.

### How to reproduce

Everytime it crashed i was navigating dropdown menus.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/15864530/hyprland.log)

**Comment by vaxerski** [comment]
#6398
