### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by roflcow2** [hyprwm/Hyprland#6558]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Pretty sure I'm being an idiot, but I can't figure it out. I was issue #6518 and I was politely told I was being an idiot and that I hadn't updated my hyprland. I have it installed from aur package hyprland-git, but for some reason I cannot get it to update. I have tried uninstalling and reinstalling hyprland-git, all its dependencies and anything else I can think of. I can see it says the submodule subprojects/wlroots doesn't exist, but I'm not sure why as before all I had to do was have wlroots installed and I do.

### How to reproduce

Apparently let your hyprland get out of date for who knows how long and try to update

### Crash reports, logs, images, videos

[hyprlandcrash.txt](https://github.com/user-attachments/files/15866597/hyprlandcrash.txt)

**Comment by gulafaran** [comment]
yay -Sua hyprland-git

**Comment by vaxerski** [comment]
this is a problem with the package

**Comment by roflcow2** [comment]
Thank you for replies. Sorry for late response. Hope the package gets fixed soon.
