### ISSUE TITLE
monitor on/off makes windows blurry

### ISSUE THREAD

**Issue by andresilva** [hyprwm/Hyprland#6560]
### Bug or Regression?

Bug

### System Info and Version

```
Hyprland, built from branch  at commit b15be9c77de593581007de53b2bbca97d121900a  ().
Date: 2024-06-16
Tag: , commits: 

flags: (if any)

System Information:
System name: Linux
Release: 6.9.5

GPU information: 
0a:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])

plugins:
```

### Description

After turning on/off DPMS some windows become blurry, notably Firefox and Emacs. Only happens when using scaling (doesn't need to be fractional, happens at 2x). Can replicate with empty config.

### How to reproduce

- Open firefox
- Turn on DPMS
- Wait for monitor to shutdown
- Turn off DPMS
- Firefox window is now blurry (with wrong scaling)

**Comment by andresilva** [comment]
Just turning off the monitor manually triggers the issue. I am using a single monitor.

**Comment by wxlyyy** [comment]
Same issue

**Comment by Estebiu** [comment]
Can replicate. Seems like a regression somewhere between 0.40 and 0.41, I think.

**Comment by ircurry** [comment]
Can replicate on my laptop as well. Emacs, Firefox, and MPV are all affected. Weirdly enough, Alacritty seems to be fine.

Is there some way to force Hyprland to redraw windows or in someway do a soft restart? Really just any temporary fix beyond close the window and reopen again.

**Comment by andresilva** [comment]
@vaxerski could you please have a look at this? 🥹

**Comment by andresilva** [comment]
I think this might have been magically fixed in the aquamarine branch (https://github.com/hyprwm/Hyprland/pull/6608).

**Comment by izmyname** [comment]
> I think this might have been magically fixed in the aquamarine branch (#6608), couldn't replicate with aquamarine so far.

Close, then?

**Comment by andresilva** [comment]
It's not fixed. When I was testing the aquamarine branch (before it was merged), it seemed like the issue was gone. Testing main now the issue is still present. I tried bisecting but couldn't figure what commit caused this.

**Comment by tannerellen** [comment]
I'm experiencing this one too and firefox is where it hurts the most as leaving the browser open all the time is pretty standard for me. Any time I wake my computer from suspend I am opening about:profiles in firefox and clicking reload from that window but that's far from ideal. 

If anyone has any type of work around even if it's hacky I would love to hear it until this gets fixed.

**Comment by Nojike** [comment]
> I'm experiencing this one too and firefox is where it hurts the most as leaving the browser open all the time is pretty standard for me. Any time I wake my computer from suspend I am opening about:profiles in firefox and clicking reload from that window but that's far from ideal.
> 
> If anyone has any type of work around even if it's hacky I would love to hear it until this gets fixed.
I am on the same boat as you,but I just go to customize toolbar enable/disable  the titlebar checkbox.Then firefox will refresh itself.

**Comment by tannerellen** [comment]
I've done a bit more testing on this and it seems like this is related to a timing issue where the monitor isn't ready soon enough. I was having the issue with Firefox getting blurry and more recently waybar crashing when turning my monitor off and on again or having my computer suspend and resuming.

For now I have found a work around that works for the suspend / resume scenario. I'm using a bash script to suspend my computer that waits 3 seconds on resume. This seems to give enough time to remove the race condition that seems to be happening...

```
#!/bin/bash
swaylock -f
sleep 0.5
hyprctl dispatch dpms off resume sleep 3; hyprctl dispatch dpms on
systemctl suspend -i
```

**Comment by andresilva** [comment]
@tannerellen I don't really understand your workaround and the script you posted doesn't work.

**Comment by marcelarie** [comment]
is there any fix on this? 

I know this got fix in sway in this PR: https://github.com/swaywm/wlroots/issues/2466

**Comment by Estebiu** [comment]
Doesnt seem so. I still have the problem on the latest hyprland-git. And hyprland no longer uses wlroots under the hood; so that PR doesn't have any influence over this bug, unfortunately.

**Comment by marcelarie** [comment]
> Doesnt seem so. I still have the problem on the latest hyprland-git. And hyprland no longer uses wlroots under the hood; so that PR doesn't have any influence over this bug, unfortunately.

Good to know, thanks!

**Comment by vaxerski** [comment]
can't repro, can I get a minimal `WAYLAND_DEBUG=1` log from an offending app?

**Comment by andresilva** [comment]
[emacs-wayland-debug.log](https://github.com/user-attachments/files/17401618/emacs-wayland-debug.log)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/17401727/patch.txt)
try

**Comment by andresilva** [comment]
[patch2.txt](https://github.com/user-attachments/files/17402443/patch2.txt)

Patch was missing an include. It works! 🚀

**Comment by vaxerski** [comment]
no pch mfs b like

**Comment by luciano-fiandesio** [comment]
Was this actually fixed? I am on version 0.51.1 and I can easily reproduce

**Comment by hugo-paugesteros** [comment]
I'm facing the same problem (v0.52.1). Before I was able to fix the blurry window by moving it to another monitor, but now it doesn't seem to help.

**Comment by williamviktorsson** [comment]
I'm consistently seeing this issue on Firefox/Zen browser (v0.52.1). I can only fix by restarting application.

**Comment by marcelmanz** [comment]
> I'm consistently seeing this issue on Firefox/Zen browser (v0.52.1). I can only fix by restarting application.

Same situation.

**Comment by williamviktorsson** [comment]
I went ahead and opened a discussion on this to draw attention to the matter: #12439
