### ISSUE TITLE
Maximized apps can't switch to fullscreen

### ISSUE THREAD

**Issue by diniamo** [hyprwm/Hyprland#6562]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 1360677478e867034713e5d43d7a8a8f6bf1343d  ().
Date: 2024-06-17
Tag: , commits: 1360677478e867034713e5d43d7a8a8f6bf1343d

flags: (if any)
```

</details>

### Description

Maximized applications can't switch to the fullscreen state. I ran into this on Firefox/Youtube. Note that this not only doesn't work, but after the bug happens, the app won't be able to switch to fullscreen at all until I restart it.

### How to reproduce

1. Open a Youtube video in your browser
2. Maximize it (`fullscreen, 1` dispatcher)
3. Press the fullscreen button in Youtube

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/55629891/7dd3bc9a-53f7-485b-a87f-b124271359b7

**Comment by diniamo** [comment]
Looks like this is a Firefox specific issue, works fine on Chromium.

**Comment by Meehir5907** [comment]
Well for me it doesn't work even on chromium:


https://github.com/hyprwm/Hyprland/assets/64735171/859ce1e0-e604-4a7c-80ce-cd69099d16ad


And for the firefox: I just need to enter fullscreen(Hyprland command) and then toggle out of it to non-maximized format and then the Full screen(Youtube) works normally

**Comment by diniamo** [comment]
Oh, that might have happened for me too, except I don't have a bar, nor window decorations so it looked like actual fullscreen

**Comment by Steven--** [comment]
I've been running into this too. A workaround to recover Firefox from its broken state without restarting it is to fullscreen (not fake fullscreen) its window through Hyprland (usually a couple of  times).

**Comment by sungyoonc** [comment]
The fullscreen request is being ignored, because the window is already in fullscreen(maximized).

https://github.com/hyprwm/Hyprland/blob/33a5c8ce325e1657ec5571b57e05c6378706f4cd/src/desktop/Window.cpp#L1325-L1326

`g_pCompositor->setWindowFullscreen()` doesn't get called because, `fs` and `m_bIsFullscreen` is both `true`.

**Comment by diniamo** [comment]
Technically, Hyprland doesn't have a stable release.

**Comment by terminal-enlightenment** [comment]
> Then I'd say the change needs to be made in Hyprland, which is an outlier, because fullscreening a maximized window fullscreens it, instead of unmaximizing it in every desktop environment. This would also apply to keybinds, eg.: `fullscreen, 1`, followed by `fullscreen, 0` would end up fullscreening.

Question- I'm confused about what maximizing before fullscreening does that is different from just going straight to fullscreen? I tried to reproduce your issue in a few browsers, but wasn't able to. I couldn't tell a difference whether it was maximized first or not though, so maybe I'm missing something.

**Comment by diniamo** [comment]
I'm not sure what your question is.

**Comment by diniamo** [comment]
Inactive Bugzilla issue for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1727815
