### ISSUE TITLE
hyprland-0.41.1 causes wezterm to crash when selecting copy

### ISSUE THREAD

**Issue by ystyle** [hyprwm/Hyprland#6563]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
hyprland-0.41.1 in archlinux  repo

Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: Archlinux
Release: 6.9.4-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Comet Lake UHD Graphics [8086:9bca] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

in hyprland-0.41.1, open wezterm , select some text , then the  wezterm will crash, 
After rolling back to 0.40.0, wezterm is back to normal
![image](https://github.com/hyprwm/Hyprland/assets/4478635/bdbd52bb-b218-4a87-b0ea-5a259c3bc56e)

### How to reproduce

1. in  hyprland-0.41.1
2. open wezterm and exec some command
3. use mouse select some text
4. the wezterm will crash

**Comment by khaneliman** [comment]
What wezterm version are you using? I'm using latest commit from wezterm and dont experience this. I just can't paste into wezterm.

**Comment by vaxerski** [comment]
logs from `WAYLAND_DEBUG=1 wezterm` please. Also try git, had some fixes

**Comment by ystyle** [comment]
> What wezterm version are you using? I'm using latest commit from wezterm and dont experience this. I just can't paste into wezterm.你用的是什么版本的wezterm？我正在使用wezterm的最新提交，但没有经历过这种情况。我就是无法粘贴到wezterm中。

I use `wezterm 20240203.110809.5046fc22-2`

**Comment by ystyle** [comment]
> WAYLAND_DEBUG=1 wezterm

```shell
━  WAYLAND_DEBUG=1 wezterm 
16:14:00.916  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
16:14:05.940  ERROR  wezterm_gui                 > running message loop: process_queued_xcb: process_xcb_event_ime: SendEvent {
    propagate: true,
    destination: Window(
        Window {
            res_id: 2097168,
        },
    ),
    event_mask: NO_EVENT,
    event: SelectionNotifyEvent {
        response_type: 31,
        pad: 1,
        sequence: 0,
        time: 0,
        requestor: Window {
            res_id: 2097168,
        },
        selection: Atom {
            res_id: 249,
        },
        target: Atom {
            res_id: 296,
        },
        property: Atom {
            res_id: 248,
        },
    },
}: X(Window(ValueError { response_type: 0, error_code: 3, sequence: 2914, bad_value: 2097168, minor_opcode: 0, major_opcode: 25, pad: 1 }), Some("x::SendEvent")); terminating
```

**Comment by vaxerski** [comment]
wez is running in x11 mode. Does it happen on wayland?

**Comment by ystyle** [comment]
> wez is running in x11 mode. Does it happen on wayland?wez以x11模式运行。它发生在陆地上吗？

I can't run wezterm on wayland, detail: https://github.com/wez/wezterm/issues/5604

**Comment by khaneliman** [comment]
> > wez is running in x11 mode. Does it happen on wayland?wez以x11模式运行。它发生在陆地上吗？
> 
> I can't run wezterm on wayland, detail: [wez/wezterm#5604](https://github.com/wez/wezterm/issues/5604)

hyprctl dispatch exec "[float;tile] WAYLAND_DEBUG=1 wezterm"

**Comment by vaxerski** [comment]
if it's just X11 then I have little interest in the issue

**Comment by ystyle** [comment]
> hyprctl dispatch exec "[float;tile] WAYLAND_DEBUG=1 wezterm"

![image](https://github.com/hyprwm/Hyprland/assets/4478635/424034f6-e50f-4235-b11f-4b6a60f3a002)
But no window opens

**Comment by khaneliman** [comment]
> > hyprctl dispatch exec "[float;tile] WAYLAND_DEBUG=1 wezterm"
> 
> ![image](https://private-user-images.githubusercontent.com/4478635/342222855-424034f6-e50f-4235-b11f-4b6a60f3a002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjMyMzIsIm5iZiI6MTcxOTI2MjkzMiwicGF0aCI6Ii80NDc4NjM1LzM0MjIyMjg1NS00MjQwMzRmNi1lNTBmLTQyMzUtYjExZi00YjZhNjBmM2EwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMjEwMjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZiMDIxYmQzNGNiMGMyYjZkZGU1ZTIzOWFmZTIyNWIxNDI2Mjc3NzhhZmJmMWQ0NzJhOWMxNjUwZDY4ODgzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n_ka6OzjhKpha-dewoNo-jWjHBvY86dLRC7F1TwfoEc) But no window opens

Did your wezterm to enable wayland before doing it?

**Comment by ystyle** [comment]
> > > hyprctl dispatch exec "[float;tile] WAYLAND_DEBUG=1 wezterm"
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/4478635/342222855-424034f6-e50f-4235-b11f-4b6a60f3a002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjMyMzIsIm5iZiI6MTcxOTI2MjkzMiwicGF0aCI6Ii80NDc4NjM1LzM0MjIyMjg1NS00MjQwMzRmNi1lNTBmLTQyMzUtYjExZi00YjZhNjBmM2EwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMjEwMjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZiMDIxYmQzNGNiMGMyYjZkZGU1ZTIzOWFmZTIyNWIxNDI2Mjc3NzhhZmJmMWQ0NzJhOWMxNjUwZDY4ODgzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n_ka6OzjhKpha-dewoNo-jWjHBvY86dLRC7F1TwfoEc) But no window opens
> 
> Did your wezterm to enable wayland before doing it?在做这件事之前，你的wezterm启用了wayland吗？

Yes, I enabled Wayland in the WezTerm configuration file. detail: https://github.com/wez/wezterm/issues/5604

**Comment by ystyle** [comment]
> `WAYLAND_DEBUG=1 wezterm` in the terminal
> 
> however if it's launching via X11 that won't do anything.

After wezterm is configured to enable wayland, wezterm cannot be opened in `terminator` or `anyrun`。
`terminator` and `anyrun` are running in wayland mode, confirmed with `hyprctl clients`

**Comment by ystyle** [comment]
wezterm-git is solved. (only work on wayland=true)

**Comment by vaxerski** [comment]
this is a wezterm bug
