### ISSUE TITLE
The name org.freedesktop.portal.Desktop was not provided by any .service files

### ISSUE THREAD

**Issue by Different-Name** [hyprwm/Hyprland#6579]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit d1340bd1d8eedd274283e0cb2568a3ed67b58c81  ().
Date: 2024-06-17
Tag: , commits: d1340bd1d8eedd274283e0cb2568a3ed67b58c81

flags: (if any)


System Information:
System name: Linux
Node name: lithium
Release: 6.8.12
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405] [1002:163f] (rev ae) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240613.e9ee548"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:

======Config-Start======


Config File: /home/different/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/y29cbwfiwb9nyi4db4apk9dgylzdjm1v-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
source=/nix/store/8a39xfxfq78r0fsq34cda4l522gwpmdb-source/themes/mocha.conf
source=/nix/store/mcjgrfgkrrxj9gaz8jb4nfw9711zqxjv-hyprland-red-accent.conf
source=/nix/store/aan4vsxbqpg5y6l6nyqw91hk217sbnpq-hyprland-cursors.conf
animations {
  bezier=myBezier, 0.05, 0.9, 0.1, 1.05
  animation=windows, 1, 5, myBezier
  animation=windowsOut, 1, 7, default, popin 80%
  animation=border, 1, 10, default
  animation=fade, 1, 7, default
  animation=workspaces, 1, 6, default
  enabled=yes
}

decoration {
  blur {
    brightness=0.800000
    contrast=0.900000
    enabled=true
    new_optimizations=on
    noise=0.010000
    passes=3
    popups=true
    size=8
  }
  dim_inactive=false
  drop_shadow=yes
  shadow_range=8
  shadow_render_power=2
}

dwindle {
  preserve_split=true
}

general {
  resize_on_border=true
}

input {
  kb_layout=us
}
bind=SUPER, S, exec, rofi -show drun -show-icons
bind=SUPER, Return, exec, kitty
bind=SUPER, W, exec, librewolf
bind=SUPER, E, exec, thunar
bind=CTRL ALT, Delete, exit
bind=ALT, Q, killactive
bind=SUPER, F, togglefloating
bind=SUPER, G, fullscreen
bind=SUPER, O, fakefullscreen
bind=SUPER, P, togglesplit
bind=SUPER, k, movefocus, u
bind=SUPER, j, movefocus, d
bind=SUPER, l, movefocus, r
bind=SUPER, h, movefocus, l
bind=SUPER, left, workspace, e-1
bind=SUPER, right, workspace, e+1
bind=SUPER SHIFT, left, movetoworkspace, e-1
bind=SUPER SHIFT, right, movetoworkspace, e+1
bind=SUPER CTRL, k, resizeactive, 0 -20
bind=SUPER CTRL, j, resizeactive, 0 20
bind=SUPER CTRL, l, resizeactive, 20 0
bind=SUPER CTRL, h, resizeactive, -20 0
bind=SUPER ALT, k, moveactive, 0 -20
bind=SUPER ALT, j, moveactive, 0 20
bind=SUPER ALT, l, moveactive, 20 0
bind=SUPER ALT, h, moveactive, -20 0
bind=SUPER, 1, workspace, 1
bind=SUPER, 2, workspace, 2
bind=SUPER, 3, workspace, 3
bind=SUPER, 4, workspace, 4
bind=SUPER, 5, workspace, 5
bind=SUPER, 6, workspace, 6
bind=SUPER, 7, workspace, 7
bind=SUPER SHIFT, 1, movetoworkspace, 1
bind=SUPER SHIFT, 2, movetoworkspace, 2
bind=SUPER SHIFT, 3, movetoworkspace, 3
bind=SUPER SHIFT, 4, movetoworkspace, 4
bind=SUPER SHIFT, 5, movetoworkspace, 5
bind=SUPER SHIFT, 6, movetoworkspace, 6
bind=SUPER SHIFT, 7, movetoworkspace, 7
bindm=SUPER, mouse:273, resizewindow
bindm=SUPER, mouse:272, movewindow
exec-once=swww init
exec-once=nm-applet --indicator
exec-once=waybar
exec-once=dunst
monitor=desc:Valve Corporation ANX7530 U 0x00000001, preferred, 0x0, 1, transform, 3
monitor=,preferred,auto,1


Config File: /nix/store/8a39xfxfq78r0fsq34cda4l522gwpmdb-source/themes/mocha.conf: Read Succeeded

$rosewater = rgb(f5e0dc)
$rosewaterAlpha = f5e0dc

$flamingo = rgb(f2cdcd)
$flamingoAlpha = f2cdcd

$pink = rgb(f5c2e7)
$pinkAlpha = f5c2e7

$mauve = rgb(cba6f7)
$mauveAlpha = cba6f7

$red = rgb(f38ba8)
$redAlpha = f38ba8

$maroon = rgb(eba0ac)
$maroonAlpha = eba0ac

$peach = rgb(fab387)
$peachAlpha = fab387

$yellow = rgb(f9e2af)
$yellowAlpha = f9e2af

$green = rgb(a6e3a1)
$greenAlpha = a6e3a1

$teal = rgb(94e2d5)
$tealAlpha = 94e2d5

$sky = rgb(89dceb)
$skyAlpha = 89dceb

$sapphire = rgb(74c7ec)
$sapphireAlpha = 74c7ec

$blue = rgb(89b4fa)
$blueAlpha = 89b4fa

$lavender = rgb(b4befe)
$lavenderAlpha = b4befe

$text = rgb(cdd6f4)
$textAlpha = cdd6f4

$subtext1 = rgb(bac2de)
$subtext1Alpha = bac2de

$subtext0 = rgb(a6adc8)
$subtext0Alpha = a6adc8

$overlay2 = rgb(9399b2)
$overlay2Alpha = 9399b2

$overlay1 = rgb(7f849c)
$overlay1Alpha = 7f849c

$overlay0 = rgb(6c7086)
$overlay0Alpha = 6c7086

$surface2 = rgb(585b70)
$surface2Alpha = 585b70

$surface1 = rgb(45475a)
$surface1Alpha = 45475a

$surface0 = rgb(313244)
$surface0Alpha = 313244

$base = rgb(1e1e2e)
$baseAlpha = 1e1e2e

$mantle = rgb(181825)
$mantleAlpha = 181825

$crust = rgb(11111b)
$crustAlpha = 11111b


Config File: /nix/store/mcjgrfgkrrxj9gaz8jb4nfw9711zqxjv-hyprland-red-accent.conf: Read Succeeded
$accent=$red
$accentAlpha=$redAlpha


Config File: /nix/store/aan4vsxbqpg5y6l6nyqw91hk217sbnpq-hyprland-cursors.conf: Read Succeeded
env = HYPRCURSOR_THEME,MyCursor
env = HYPRCURSOR_SIZE,24

======Config-End========
```

</details>

### Description

Attempting to share screen in webcord throws the error
`[68506:0618/060550.776853:ERROR:screen_capture_portal_interface.cc(48)] Failed to request session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files`

I have experienced this issue in other programs aswell

`echo $XDG_CURRENT_DESKTOP`
returns
`Hyprland`

### How to reproduce

1. Launch webcord
2. Join a voice channel
3. Click the share screen button

### Crash reports, logs, images, videos

[webcord.log](https://github.com/user-attachments/files/15881187/webcord.log)

**Comment by DADA30000** [comment]
Try to add this to your configuration.nix:
`xdg.portal = { enable = true; extraPortals = [ pkgs.xdg-desktop-portal-hyprland ]; }; 
   xdg.portal.config.common.default = "*";
`

**Comment by Different-Name** [comment]
> Try to add this to your configuration.nix: `xdg.portal = { enable = true; extraPortals = [ pkgs.xdg-desktop-portal-hyprland ]; }; xdg.portal.config.common.default = "*"; `

Adding the extraPortals config produces an error during build that the file `xdg-desktop-portal-hyprland.service` already exists. Removing that config option lets the build progress, however I still get the original freedesktop error

**Comment by DADA30000** [comment]
> > Try to add this to your configuration.nix: `xdg.portal = { enable = true; extraPortals = [ pkgs.xdg-desktop-portal-hyprland ]; }; xdg.portal.config.common.default = "*"; `
> 
> Adding the extraPortals config produces an error during build that the file `xdg-desktop-portal-hyprland.service` already exists. Removing that config option lets the build progress, however I still get the original freedesktop error

So if you only remove extraPortals it still doesn't work?

**Comment by DADA30000** [comment]
Also why in your nixos config you have hyprland declared both in home-manager and your main nixos config?

**Comment by Different-Name** [comment]
Correct, I only removed extraPortals, and there has been no change

**Comment by DADA30000** [comment]
> Correct, I only removed extraPortals, and there has been no change

Try to remove hyprland.nix from main nixos configuration and add extraPortals back, maybe nixos module is somehow messing with this

**Comment by Different-Name** [comment]
> Also why in your nixos config you have hyprland declared both in home-manager and your main nixos config?

I assumed that was required:

    (Required) NixOS Module: enables critical components needed to run Hyprland properly
    (Optional) Home-manager module: lets you declaratively configure Hyprland
https://wiki.hyprland.org/Nix/

**Comment by Different-Name** [comment]
> > > Also why in your nixos config you have hyprland declared both in home-manager and your main nixos config?
> > 
> > 
> > I assumed that was required:
> > ```
> > (Required) NixOS Module: enables critical components needed to run Hyprland properly
> > (Optional) Home-manager module: lets you declaratively configure Hyprland
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://wiki.hyprland.org/Nix/
> 
> Oh, wow, I'm running hyprland without nixos module, only in home-manager :D

Removing hyprland at the system level removed some packages, including some fonts and such. I assume that now none of the system level configuration (such as the extraPortals option) and managed by hyprland anymore. I can compile fine with the extraPortals option now, but it did not change the original issue

**Comment by DADA30000** [comment]
> > > > Also why in your nixos config you have hyprland declared both in home-manager and your main nixos config?
> > > 
> > > 
> > > I assumed that was required:
> > > ```
> > > (Required) NixOS Module: enables critical components needed to run Hyprland properly
> > > (Optional) Home-manager module: lets you declaratively configure Hyprland
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > https://wiki.hyprland.org/Nix/
> > 
> > 
> > Oh, wow, I'm running hyprland without nixos module, only in home-manager :D
> 
> Removing hyprland at the system level removed some packages, including some fonts and such. I assume that now none of the system level configuration (such as the extraPortals option) and managed by hyprland anymore. I can compile fine with the extraPortals option now, but it did not change the original issue

check if xdg-desktop-portal and xdg-desktop-portal-hyprland are running

**Comment by DADA30000** [comment]
Also have you relogged (rebooting is even better) after changing configuration?

**Comment by Different-Name** [comment]
Running
`systemctl status xdg-desktop-portal-hyprland`
Says the unit could not be found, same with `xdg-desktop-portal`
I have been rebooting

**Comment by DADA30000** [comment]
Also have you relogged after removing

> Running `systemctl status xdg-desktop-portal-hyprland` Says the unit could not be found, same with `xdg-desktop-portal` I have been rebooting

no I mean in btop, htop, as a process

**Comment by fufexan** [comment]
> Running `systemctl status xdg-desktop-portal-hyprland` Says the unit could not be found, same with `xdg-desktop-portal` I have been rebooting

Should be `systemctl --user status xdg-desktop-portal-hyprland` since xdg portals are user services.

**Comment by Different-Name** [comment]
> > Running `systemctl status xdg-desktop-portal-hyprland` Says the unit could not be found, same with `xdg-desktop-portal` I have been rebooting
> 
> Should be `systemctl --user status xdg-desktop-portal-hyprland` since xdg portals are user services.

Thanks for that - they are both running without errors apparently

**Comment by Different-Name** [comment]
> Also have you relogged after removing
> 
> > Running `systemctl status xdg-desktop-portal-hyprland` Says the unit could not be found, same with `xdg-desktop-portal` I have been rebooting
> 
> no I mean in btop, htop, as a process

I am going to keep the system hyprland module enabled in my config, as it is recommended by the wiki, [this reddit comment I found on the topic](https://www.reddit.com/r/NixOS/s/Zcute6rBrt) and the example nixos config from the hyprland wiki [uses it](https://www.reddit.com/r/NixOS/s/Zcute6rBrt)

**Comment by DADA30000** [comment]
I also don't have this `xdg-desktop-portal-hyprland.service` unit, or `xdg-desktop-portal.service` unit

**Comment by DADA30000** [comment]
Oh, yeah, sorry for bs, I have them both

**Comment by vaxerski** [comment]
this is not a hyprland issue

**Comment by Different-Name** [comment]
Not sure where I should have made this issue instead, maybe the xdg-desktop-portal-hyprland repo

The following config solved the problem for me:

`  xdg.portal = {
    enable = true;
    xdgOpenUsePortal= true;
    config = {
      common.default = ["gtk"];
      hyprland.default = ["gtk" "hyprland"];
    };

    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
    ];
  };`
