### ISSUE TITLE
Screen refresh problem

### ISSUE THREAD

**Issue by VDFOREVER** [hyprwm/Hyprland#6586]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: void
Release: 6.9.5_1
Version: #1 SMP PREEMPT_DYNAMIC Mon Jun 17 11:50:08 UTC 2024


GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev ef) (prog-if 00 [VGA controller])


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:
```

</details>

### Description

Sometimes when switching desktops or closing a program, part of the screen may stop updating

### How to reproduce

This happens rarely so it is quite difficult to understand why it happens

### Crash reports, logs, images, videos

I included the logs after this happened, so perhaps there will not be the necessary error there
[hyprland.log](https://github.com/user-attachments/files/15891139/hyprland.log)
![swappy-20240618_214750](https://github.com/hyprwm/Hyprland/assets/55760436/14dc373d-d15d-488f-89a7-8318e1700288)

**Comment by VDFOREVER** [comment]
By the way, this started happening after I disconnected the third monitor and changed the settings

**Comment by vaxerski** [comment]
do I really have to search the issue tracker for yall every time #5386

**Comment by VDFOREVER** [comment]
Sorry I can't find them
