### ISSUE TITLE
Hyprland gives a red screen and lags when unplugging the laptop's charger. 

### ISSUE THREAD

**Issue by ilyamiro** [hyprwm/Hyprland#6588]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

System info is in the file
[file.txt](https://github.com/user-attachments/files/15892168/file.txt)

</details>

### Description

When unplugging my laptop's charger and pluggin it back in, the screen locks itself and lags, sometimes with a red screen, or shows some console output and then goes back to normal (happens from time to time when plugging in). You can see it on the video that i attached.  IT DOES NOT HAPPEN ON OTHER WAYLAND COMPOSITORS OR VIRTUAL ENVIRONMENTS LIKE GNOME OR KDE. Only Hyprland.

My laptop:
- Asus Vivobook 15 pro
- 16 Gb of RAM
- Nvidia 3050 4gb gpu

Also, when this thing with screen lock happens, 3 strange things happen:
1. Airplane mode turns on
2. Headphones and microphone volume levels go to zero.
3. Hyprlock lags, i have to wait for 10 seconds or move my cursor before it will start to react to my keyboard input

 

### How to reproduce

Just unplug the charger and plug the charger in 

### Crash reports, logs, images, videos

A video of me reproducing a bug. Happens each time without exceptions. 

https://github.com/hyprwm/Hyprland/assets/142908366/5e072b57-317e-4319-aa92-139dd06ae52e

**Comment by Agent00Ming** [comment]
dupe of #6548 + understand your dotfiles

**Comment by ilyamiro** [comment]
Since this issue is a duplicate of #6548, and the solution of this issue was already included in the latest hyprland patch, i am closing this issue as this patch works for me and solves the issue.
