### ISSUE TITLE
Unable to build on Arch Linux

### ISSUE THREAD

**Issue by Desvelad0** [hyprwm/Hyprland#6599]
### Regression?

No

### System Info and Version

Unable to produce at the moment due to this happening on a fresh installation on bare-metal with no GUI.

### Description

In the current build for Arch Linux, when trying to build from source, I have essentially the same exact issue as #6596. Hyprland was going to be the GUI element of my Arch installation on bare metal, so I don't have an easy way of extracting logs right now, but if required, I can figure out a way to get them out. Essentially I am told I lack the required package "hyprutils>=0.1.4" just like in the issue mentioned, which does not seem to be available in AUR or in the default repos for pacman, both of which have older versions.

### How to reproduce

Build from source on Arch Linux.

**Comment by MightyPlaza** [comment]
hyprutils-git

**Comment by Desvelad0** [comment]
Right, I just stupidly assumed it wouldn't work due to hyprutils-git being older than what the error said but this worked just fine. Thank you!
