### ISSUE TITLE
decoration:dim_special should ignore layers (like waybar)

### ISSUE THREAD

**Issue by daniele821** [hyprwm/Hyprland#6610]
### Description

![20240620_23h50m35s_grim](https://github.com/hyprwm/Hyprland/assets/137685223/f9bc7c4f-ad99-4ce2-a68d-802838437251)

as can be seen in the image, setting decoration:dim_special to anything but zero, will dim also waybar, which i don't think makes sense. 

I think it could make sense to have it ignore layers like waybar

(btw, rofi is not dimmed unlike waybar, idk why)

**Comment by donovanglover** [comment]
Might be something in your waybar config? Works for me with [ironbar](https://github.com/JakeStanger/ironbar) and Hyprland v0.41.1.

**Comment by vaxerski** [comment]
if your bar is on the bottom layer thats expected. On top it shouldn't be shadowed
