### ISSUE TITLE
dwindle:no_gaps_when_only does not work in special workspaces

### ISSUE THREAD

**Issue by daniele821** [hyprwm/Hyprland#6612]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit fabc30df52ab5d2c369fc8acd4ff909a6ba3b8ac  ().
Date: Wed Jun 19 10:15:18 2024
Tag: , commits: 4870

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.9.4-200.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Wed Jun 12 13:33:34 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Plus Graphics G1 (Ice Lake) [8086:8a56] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:

```

</details>

### Description

setting dwindle:no_gaps_when_only to 1 or 2 does not removes gaps in special workspaces.

(edit: the same problem exist also with master:no_gaps_when only, ie, no_gaps_when_only doesn't work in special workspace with both window layouts)

### How to reproduce

- run `hyprctl keyword dwindle:no_gaps_when_only 1` or `hyprctl keyword dwindle:no_gaps_when_only 2` in a terminal
- open a special workspace
- open a single window in tiled mode

### Crash reports, logs, images, videos

the first image shows  windows having no gaps in workspace 1 (which is the correct behaviour), while the second show that in special workspaces the window still has gaps (which is probably not the correct behaviour)

![20240620_23h36m29s_grim](https://github.com/hyprwm/Hyprland/assets/137685223/871dfc2a-464d-48d2-af31-e122c29db959)
![20240620_23h36m42s_grim](https://github.com/hyprwm/Hyprland/assets/137685223/e335984b-35ad-4587-9678-4ce3b1f38a98)

**Comment by vaxerski** [comment]
why not use workspace rules? no_gaps_when_only is deprecated

**Comment by daniele821** [comment]
i didn't find any rules that does what no_gaps_when_only does (ie: remove gaps and border, only if there is a single tiled window). Or is there some way to emulate it with workspace rules i missed?

**Comment by daniele821** [comment]
ok, i found out what you meant. My bad

**Comment by John-Paul-R** [comment]
To any other readers like me, you probably want these [Workspace Rules](https://wiki.hyprland.org/Configuring/Workspace-Rules/):

```
workspace = w[t1], gapsout:0
workspace = w[t1], border:0
```

the condition, `w[t1]`, says

> a workspace with <code>**1**</code> <code>**t**iled</code> <code>**w**indow</code>
