### ISSUE TITLE
Windows conflicts

### ISSUE THREAD

**Issue by mshzsh** [hyprwm/Hyprland#662]
![hyprland](https://user-images.githubusercontent.com/41986782/189869699-a9ac4af4-86df-448f-b470-d13f28aeba34.gif)

This bug sometimes causes problems in drag with scroll

**Comment by vaxerski** [comment]
what the fuck

**Comment by vaxerski** [comment]
config plox

**Comment by mshzsh** [comment]
I did not catch?

**Comment by pinkcreeper100** [comment]
upload hyprland config

**Comment by mshzsh** [comment]
`monitor=HDMI-A-1,1920x1080@60,0x0,1
input {
    kb_layout=us,ir
    kb_variant=
    kb_model=
    kb_options=grp:alt_shift_toggle
    kb_rules=
    numlock_by_default=1
    follow_mouse=0
    float_switch_override_focus=0

    touchpad {
        natural_scroll=no
    }
}
general {
    sensitivity=1.3
    main_mod=SUPER
    gaps_in=3
    gaps_out=5
    border_size=0
    col.active_border=0x66ee1111
    col.inactive_border=0x66333333

    apply_sens_to_raw=0
    damage_tracking=full
}

decoration {
    rounding=12
    blur=0
    inactive_opacity=0.9
    blur_size=2
    blur_passes=1
}

animations {
    enabled=1
    animation=windows,1,5,default
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,5,default,slide
}

dwindle {
    pseudotile=0
}

gestures {
    workspace_swipe=no
}

binds {
    allow_workspace_cycles=1
    workspace_back_and_forth=0
}

bind=SUPER,W,killactive,
bind=SUPER,LEFT,workspace,-1
bind=SUPER,RIGHT,workspace,+1
bind=SUPER,UP,movewindow,u
bind=SUPER,DOWN,movewindow,d
bind=SUPER,LEFT,movefocus,ls
bind=SUPER,RIGHT,movefocus,r
bind=SUPER,UP,movefocus,u
bind=SUPER,DOWN,movefocus,d
bind=SUPER,F,fullscreen,
bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9

bind=SUPERSHIFT,1,movetoworkspace,1
bind=SUPERSHIFT,2,movetoworkspace,2
bind=SUPERSHIFT,3,movetoworkspace,3
bind=SUPERSHIFT,4,movetoworkspace,4
bind=SUPERSHIFT,5,movetoworkspace,5
bind=SUPERSHIFT,6,movetoworkspace,6
bind=SUPERSHIFT,7,movetoworkspace,7
bind=SUPERSHIFT,8,movetoworkspace,8
bind=SUPERSHIFT,9,movetoworkspace,9
bind=SUPERSHIFT,S,movetoworkspace,scratchpad

bind=SUPER,P,togglefloating,
bind=SUPER,K,splitratio,+
bind=SUPER,J,splitratio,-
bind=SUPER,mouse_down,workspace,e+1
bind=SUPER,mouse_up,workspace,e-1
bind=SUPERCTRL,RIGHT,movetoworkspace,+1
bind=SUPERCTRL,LEFT,movetoworkspace,-1
bind=SUPER,TAB,workspace,previous
bind=SUPER,RETURN,exec,guake-toggle
bind=SUPER,SPACE,exec,wofi --show drun
bind=SUPER,G,exec,~/.config/hypr/clipboard
bind=SUPERALT,P,exec,~/.config/hypr/colorpicker
bind=ALT,TAB,exec,rofi -show window
bind=SUPER,N,exec,alacritty -e note
bind=,Print,exec,grim -g "$(slurp)"


exec-once=/usr/bin/lxpolkit &
exec-once=waybar &
exec-once=dunst &
exec-once=guake --restore-preferences ~/.config/guake/conf && guake &
exec-once=mpd
exec-once=swaybg -i /home/mshzsh/Pictures/1.jpg &
exec-once=wl-paste -t text --watch clipman store --max-items=2000 &


windowrule=float,^(Guake)$
windowrule=size 95% 90%,^(Guake)$
windowrule=center,^(Guake)$
windowrule=float,Rofi
windowrule=float,Alacritty
windowrule=size 50% 50%,Alacritty
windowrule=center,Alacritty
`

**Comment by vaxerski** [comment]
attach, not paste

**Comment by mshzsh** [comment]
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/9586994/hyprland.txt)

**Comment by vaxerski** [comment]
fixado in 29626989e7ac89ee596af01dfdefad6118324d5d
