### ISSUE TITLE
Support to set display order and set a default display. 

### ISSUE THREAD

**Issue by UntitledHam** [hyprwm/Hyprland#6622]
### Description

In monitor settings you should be able to specify which monitor is considered "display 0", "display 1" etc. If the monitor marked as "display 0" does not exist it will fall back to making the monitor marked as "display 1" as display 0 and etc. 
I use a laptop and would like the ability to make my external monitor considered display 0 when it is plugged in but have it fall back to the laptop screen if that is not plugged in.

**Comment by vaxerski** [comment]
there is no such thing as a primary display in wayland

**Comment by 299792458ms** [comment]
@UntitledHam as far as I know Hyprland always falls back to to your laptop screen, so unless you chop off your screen you should be fine. If you want advanced options check out Kanshi or Shikane(Inspired on Kanshi and better) so manage monitor profiles. They set up display rules depending on which monitors are connected. Or do what I do and install nwg-displays, include the pertinent files that nwg-displays creates for you in hyprland.conf and you are done.
