### ISSUE TITLE
libdisplay-info(0.2.0-1) out and breaks dependency by hyprland

### ISSUE THREAD

**Issue by mxwmnn** [hyprwm/Hyprland#6629]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
$ hyprctl systeminfo   












Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: earth
Release: 6.9.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Wanted to update the system with pacman or yay. Not possible cause of 

```sh
[130] $ pacupg                                                                                                             ✘
:: Synchronizing package databases...
 core is up to date
 extra is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libdisplay-info (0.2.0-1) breaks dependency 'libdisplay-info.so=1-64' required by hyprland
```

### How to reproduce

Try to update arch with pacupg or sudo pacman -Syu

**Comment by mxwmnn** [comment]
wlroots and hyprland did a quickfix.

0.41.1-2 available. thanks!

**Comment by Fake4091** [comment]
Hey, I'm still having this issue. I'm on arch with the `-git` package and have used `paru -S hyprland-git` to make sure I'm on the latest commit, but I still get this when updating. I've tried installing the regular `hyprland` package, but then wlroots complains about not having the latest version of libdisplay-info. Is this something I should message the aur package maintainer about?

**Comment by cosme-benito** [comment]
I performed a system update and still have issues:

```Hyprland: error while loading shared libraries: libdisplay-info.so.1: cannot open shared object file: No such file or directory```

I have wlroots 0.17.3-2 and hyprland 0.41.1-2 installed via pacman.

**Comment by CipherJay** [comment]
I just uninstalled hyprland, updated libdisplay-info, then reinstalled hyprland. Works.
