### ISSUE TITLE
Hyprcursor makes hyprland crash on startup

### ISSUE THREAD

**Issue by Anik200** [hyprwm/Hyprland#6631]
I decided to install hyprcursor and try it on my void desktop but after installing and rebooting i can't get into hyperland, it just crashes everytime. Please let me know if there is any way to remove hyprcursor and enable it correctly

**Comment by vaxerski** [comment]
post the crash report

**Comment by izmyname** [comment]
Bump. Is the issue still actual?

**Comment by vaxerski** [comment]
it's been a month without a reply, I'll close this as "reporter mia"
