### ISSUE TITLE
Fails to start on Void Linux

### ISSUE THREAD

**Issue by xfervi** [hyprwm/Hyprland#664]
So I was using this WM often on Arch and now I've switched to Void. I've installed binaries from Releases and now I'm getting these errors:

```
Hyprland: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by Hyprland)
Hyprland: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by Hyprland)
Hyprland: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by Hyprland)
Hyprland: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib64/libwlroots.so.11032)
Hyprland: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib64/libwlroots.so.11032)
```

Though glibc is already installed and updated?

**Comment by vaxerski** [comment]
most likely outdated libstdc++. Void is known for having really outdated packages in this department. Not a hyprland issue

**Comment by xfervi** [comment]
For any Void users who wants to run Hyprland:

You will have to install `libgbm-devel`, `libglvnd-devel`, `libseat-devel`, `eudev-libudev-devel`, `libdrm-devel`, `libinput-devel`, `libxkbcommon-devel`, `pixman-devel`, `wayland-devel`, `wayland-protocols`, `vulkan-loader`, `Vulkan-Headers`, `xcb-util-errors-devel`, `xcb-util-wm-devel`, `xcb-util-renderutil-devel`, `pkg-config`, `seatd`, `dbus`, `elogind`, `pango-devel`, `cairo-devel`, `xorg-server-xwayland`. Enable `seatd`, `dbus`, `elogind`. Reboot. Add your user into `_seatd` group.

Until this pull request (https://github.com/void-linux/void-packages/pull/34902) gets merged, you will have to build gcc 12.2 manually.

Clone into this repo (https://github.com/oreo639/void-packages.git), switch to gcc11 branch and according to instructions from README.md build gcc.

Or if you want to save yourself a 3-10 hours of compiling, you can use these packages, built by me: https://drive.google.com/file/d/1NMV2WQhGVd3jIkGJUSoz9YiXuxr0PrUj/view?usp=drivesdk (can be outdated tho)

Then install it, using
```
sudo xbps-install --repository hostdir/binpkgs/gcc11 -Su
```
command.

Now, build/install binaries of Hyprland, put `Hyprland` into `/usr/bin`, `wlroots` into `/usr/lib` etc. That's it.

![screenshot.png](https://user-images.githubusercontent.com/113468120/190652709-97a9eca8-042c-4919-bf16-9f2067667993.png)

**Comment by vaxerski** [comment]
void being void as usual

**Comment by moilong** [comment]
@xfervi Thanks for sharing your effort and also pointing that void-packages PR. I tried to install your packages but getting this error:
`[*] Verifying package integrity
glibc-2.36_1: verifying SHA256 hash...
glibc-locales-2.36_1: verifying SHA256 hash...
libgcc-12.2.0_1: verifying SHA256 hash...
libgomp-12.2.0_1: verifying SHA256 hash...
libgpgme-1.18.0_1: verifying SHA256 hash...
ERROR: libgpgme-1.18.0_1: SHA256 hash is not valid: No such file or directory
Transaction failed! see above for errors.`

**Comment by xfervi** [comment]
Oh. I've probably included gpgme by mistake. Using just `xbps-install --repository hostdir/binpkgs/gcc11 gcc` works?

**Comment by xfervi** [comment]
Oh. I've probably included gpgme by mistake and it somehow left in the repo cache. Does just using `xbps-install --repository hostdir/binpkgs/gcc11 <include_every_package_from_directory>` work?
