### ISSUE TITLE
Ability to bypass hyprlock by running it again?

### ISSUE THREAD

**Issue by zorzysty** [hyprwm/Hyprland#6643]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: xps
Release: 6.9.3-3-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Mon Jun 10 09:50:04 UTC 2024


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:191b] (rev 06) (prog-if 00 [VGA controller])


os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

</details>

### Description

Given the following hyprland.conf:

```
$mainMod = SUPER 
bind = $mainMod, L, exec, hyprlock
```

when I hit `SUPER+L`, I see the hyprlock screen as expected. But when I hit `SUPER+L` again, while hyprlock is active, it closes itself as if I have typed in the password. And when I do that, I can't enable it again (the keybind seemingly stops doing anything). 

### How to reproduce

I haven't tried on other systems, but this happens every time for me.

hyprland.conf:
```
$mainMod = SUPER 
bind = $mainMod, L, exec, hyprlock
```

1. Hit `SUPER + L`  to trigger lock screen
2. Hit `SUPER + L` again to close it

**Comment by fufexan** [comment]
Old version. It doesn't seem to happen on 0.41.1.

**Comment by vaxerski** [comment]
update
