### ISSUE TITLE
Rule for specific layer

### ISSUE THREAD

**Issue by shvedes** [hyprwm/Hyprland#6646]
### Description

I searched the wiki for this information, but found nothing.
For example, I want to make a custom bezier (for example, change the animation speed), which will only apply to swaync-control-center, and not to any other layer. Is it possible?

**Comment by fufexan** [comment]
https://wiki.hyprland.org/Configuring/Window-Rules/#layer-rules

**Comment by shvedes** [comment]
You misunderstood me. What I mean is the ability to use separate rules for a specific layer.

**Comment by shvedes** [comment]
Nevermind

**Comment by DADA30000** [comment]
> Nevermind

have you found out how to change properties of animation for layers?

**Comment by shvedes** [comment]
> > Nevermind
> 
> have you found out how to change properties of animation for layers?

Sort of. Use this lines as refer. 

```
animations {

    animation = layers, 1, 4, default, fade
    animation = layersIn, 1, 3.5, default, slide
   animation = layersOut, 1, 3.5, default, slide
}

layerrule = animation fade, rofi
layerrule = animation fade, swayosd
layerrule = animation fade, logout_dialog
layerrule = animation slide right, swaync-control-center
layerrule = animation slide, swaync-notification-window
```

This is not like i wanted, but it works at least.

**Comment by musjj** [comment]
Is there a way to set the speed for a specific `layerrule`?

**Comment by shvedes** [comment]
> Is there a way to set the speed for a specific `layerrule`?

AFAIK no
