### ISSUE TITLE
`pid` selector for window rules (V2)

### ISSUE THREAD

**Issue by leon-erd** [hyprwm/Hyprland#6653]
### Description

Being able to target a specific window with a window rule using its `pid` would be really nice.
Currently, dynamic window rules are broken with the `exec` dispatcher because the dispatcher sets them only once, and as per the wiki: "dynamic window rules are re-evaluated every time a property changes" (for example changing the focus of the spawned window) which discards the rule set by the dispatcher (see https://github.com/hyprwm/Hyprland/issues/6593).
Under the hood, the exec dispatcher could set the dynamic window rules for the created window with the proposed `pid` selector which would fix this issue.
The `pid` selector would also fix https://github.com/hyprwm/Hyprland/issues/4648

**Comment by MightyPlaza** [comment]
use `hyprctl setprop`

**Comment by leon-erd** [comment]
Ah I just found out that `setprop` supports `pid`
But its not mentioned anywhere.
On the hyprland wiki it only says in the example
```
hyprctl setprop address:0x13371337 forcenoanims 1 lock  # with locking
hyprctl setprop address:0x13371337 nomaxsize 0          # without locking
```
and hyprctl only gives this information
```
➜  ~ hyprctl setprop --help
usage: hyprctl [flags] setprop <regex> <property> <value> [lock]

regex:
    Regular expression by which a window will be searched
...
```
Do you know what selection options are available? Then I will add this to the wiki

**Comment by MightyPlaza** [comment]
that's not a pid, it's the window address (aka the hex value at the start of `hyprctl clients` after `0x`)

see the `getWindowByRegex` in `src/Compositor.cpp` for all the options
```cpp
PHLWINDOW CCompositor::getWindowByRegex(const std::string& regexp) {
    if (regexp.starts_with("active"))
        return m_pLastWindow.lock();

    eFocusWindowMode mode = MODE_CLASS_REGEX;

    std::regex       regexCheck(regexp);
    std::string      matchCheck;
    if (regexp.starts_with("class:")) {
        regexCheck = std::regex(regexp.substr(6));
    } else if (regexp.starts_with("initialclass:")) {
        mode       = MODE_INITIAL_CLASS_REGEX;
        regexCheck = std::regex(regexp.substr(13));
    } else if (regexp.starts_with("title:")) {
        mode       = MODE_TITLE_REGEX;
        regexCheck = std::regex(regexp.substr(6));
    } else if (regexp.starts_with("initialtitle:")) {
        mode       = MODE_INITIAL_TITLE_REGEX;
        regexCheck = std::regex(regexp.substr(13));
    } else if (regexp.starts_with("address:")) {
        mode       = MODE_ADDRESS;
        matchCheck = regexp.substr(8);
    } else if (regexp.starts_with("pid:")) {
        mode       = MODE_PID;
        matchCheck = regexp.substr(4);
    } else if (regexp.starts_with("floating") || regexp.starts_with("tiled")) {
        // first floating on the current ws
        if (!valid(m_pLastWindow))
            return nullptr;

        const bool FLOAT = regexp.starts_with("floating");

        for (auto& w : m_vWindows) {
            if (!w->m_bIsMapped || w->m_bIsFloating != FLOAT || w->m_pWorkspace != m_pLastWindow->m_pWorkspace || w->isHidden())
                continue;

            return w;
        }

        return nullptr;
    }
```

**Comment by leon-erd** [comment]
> that's not a pid, it's the window address (aka the hex value at the start of hyprctl clients after 0x)

Yeah I know. I just found out that `hyprctl setprop pid:<...> ...` works.
Thanks! The snippet helps. Will make a MR for the wiki :)

**Comment by Vaisakhkm2625** [comment]
for me still didn't worked :(, if i toggle the special workspace, the transparency would be lost.. 

````
bind = $mainMod SHIFT, o,exec, hyprctl setprop pid:$(hyprctl activewindow -j | jq .pid) alpha 0.8 

```

**Comment by leon-erd** [comment]
`setprop` has been moved from hyprctl to the dispatchers in this MR https://github.com/hyprwm/Hyprland/pull/8275.
So please try the dispatcher instead. Also you might try locking the rule.

@MightyPlaza why have you removed a lot of the documentation of the `setprop` command in this MR https://github.com/hyprwm/hyprland-wiki/pull/832? You have only copied the prop list over but not the rest. Did you change something in the underlying code such that the documentation wasn't true anymore? Otherwise I think having the rest of the documentation in the wiki is very much needed. Else there is no mention anywhere of 
1. what locking does
2. how the modes work
3. where to find window address etc

**Comment by MightyPlaza** [comment]
locking doesn't exist anymore, I removed it a while ago but didn't notice it was still in the wiki
the modes where removed since they're just duplicated from [window parameters](https://wiki.hyprland.org/Configuring/Dispatchers/#parameter-explanation)
address is what appears in `hyprctl clients` with `0x` in front

`bind = $mainMod SHIFT, o,setprop, active alpha 0.8`

**Comment by leon-erd** [comment]
Thanks for the explanation! 
In the wiki's window parameters there is only a mention of:
"`activewindow` an active window"
(Does this mean the first active window?)
Is `active` the same as `activewindow`?
This should also be mentioned then somewhere I think.

**Comment by MightyPlaza** [comment]
it's anything that starts with active
see
```cpp
PHLWINDOW CCompositor::getWindowByRegex(const std::string& regexp_) {
    auto regexp = trim(regexp_);

    if (regexp.starts_with("active"))
        return m_pLastWindow.lock();
    else if (regexp.starts_with("floating") || regexp.starts_with("tiled")) {
        // first floating on the current ws
        if (!valid(m_pLastWindow))
            return nullptr;

        const bool FLOAT = regexp.starts_with("floating");

        for (auto const& w : m_vWindows) {
            if (!w->m_bIsMapped || w->m_bIsFloating != FLOAT || w->m_pWorkspace != m_pLastWindow->m_pWorkspace || w->isHidden())
                continue;

            return w;
        }

        return nullptr;
    }

    eFocusWindowMode mode = MODE_CLASS_REGEX;

    std::regex       regexCheck(regexp_);
    std::string      matchCheck;
    if (regexp.starts_with("class:")) {
        regexCheck = std::regex(regexp.substr(6));
    } else if (regexp.starts_with("initialclass:")) {
        mode       = MODE_INITIAL_CLASS_REGEX;
        regexCheck = std::regex(regexp.substr(13));
    } else if (regexp.starts_with("title:")) {
        mode       = MODE_TITLE_REGEX;
        regexCheck = std::regex(regexp.substr(6));
    } else if (regexp.starts_with("initialtitle:")) {
        mode       = MODE_INITIAL_TITLE_REGEX;
        regexCheck = std::regex(regexp.substr(13));
    } else if (regexp.starts_with("address:")) {
        mode       = MODE_ADDRESS;
        matchCheck = regexp.substr(8);
    } else if (regexp.starts_with("pid:")) {
        mode       = MODE_PID;
        matchCheck = regexp.substr(4);
    }
```

**Comment by leon-erd** [comment]
Thanks! :)
