### ISSUE TITLE
No way to toggle pin(ned) status of a specific client window

### ISSUE THREAD

**Issue by fdev31** [hyprwm/Hyprland#6655]
### Description

It is possible to set some rule to set the pinned attribute (and a way to clear every matching rule) which is not practical.

The current `pin` command only acts on the focused client.

It would be useful (eg: https://github.com/hyprland-community/pyprland/issues/112) to have a way to set or unset the pin status of a given window.

Something such as`hyprctl pin:0 address:0xdeadbeef` would unset the "pin" status for instance.

**Comment by MightyPlaza** [comment]
`hyprctl dispatch pin address:0xdeadbeef`?

**Comment by fdev31** [comment]
Are you kidding me ?! I was pretty sure I tested this yesterday... but today it works (I upgraded in the meantime, not sure it's recent...).
It's only a toggle, can't set, but it's good enough for me, sorry for the noise and thank you a lot for your time!
