### ISSUE TITLE
Upgrade: 0.41.1-1 -> 0.41.1-2 crashed completely and hyprland don't initialize 

### ISSUE THREAD

**Issue by rbroggi** [hyprwm/Hyprland#6656]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

After upgrading from version `0.41.1-1` to `0.41.1-2` hyprland wouldn't startup, I had to use tty and manually downgrade:

```
sudo downgrade 'wlroots=0.17.3-1' 'libdisplay-info=0.1.1-3' 'hyprland=0.41.1-1'
```

### How to reproduce

upgraded and had the issue. 

### Crash reports, logs, images, videos

couldn't find a crash report.

**Comment by fufexan** [comment]
Can you bisect?

**Comment by vaxerski** [comment]
this is an arch packaging moment. Perform a proper update of your system, possibly recheck your mirrors for some lagging ones.

**Comment by rbroggi** [comment]
Hello, I'm properly updated: see https://archlinux.org/packages/extra/x86_64/hyprland/ (latest version is `0.41.1-1`). 

@fufexan - how would you suggest for me to bisect? those two are sequential update, no way to further bisect from package-manager point of view :thinking: .

**Comment by fufexan** [comment]
Well you can diff the PKGBUILD file and see what changed. Also I don't think external `wlroots` affects Hyprland, and if it does, it shouldn't.

**Comment by vaxerski** [comment]
literally nothing changed but arch packaging, so it's not an issue on our side

**Comment by rbroggi** [comment]
I found this:

![image](https://github.com/hyprwm/Hyprland/assets/5781339/6c74ec6c-0166-47bb-8db4-513866db1442)

In here: https://archlinux.org/packages/extra/x86_64/hyprland/

**Comment by rbroggi** [comment]
this seems to be the commit difference:

https://gitlab.archlinux.org/archlinux/packaging/packages/hyprland/-/commit/006ffcfb34f45152724903f10ee429c2b52fe0ff

**Comment by rbroggi** [comment]
The only difference seems to be upgrade of `libdisplay-info` to version `0.2.0`

**Comment by rbroggi** [comment]
I have engaged with the package maintainers but it seems that they can't help me understand what is going on 😢 


I made a video showing what is happening (basically I cannot manage to pass the login screen): https://gitlab.archlinux.org/archlinux/packaging/packages/hyprland/-/issues/11#note_194829


Could you give me any advice about where I could find logs and info about potential issue?

I couldn't find any specific hyprland crash reports from tty

**Comment by vaxerski** [comment]
what if you build hyprland manually?

**Comment by rbroggi** [comment]
I could try that but my concern is that I would still lack the skill to debug an issue like that if something was to go wrong and it would become even harder for me to rollback. I completely understand your concern about the package manager but it's jsut the least worst solutio9n for mortals like me that are trying to minimize their time spent on upgrading while still getting some job done during the day :D 

this issue could even be unrelated to hyprland itself and maybe only related to the tool I use as login/llock window but I've been strugling to find the time to go back and debug even my own tools. 

Do you have any advice about files or crash reports that i could find from TTY if I attempt this upgrade once more just to try to drill-down where the problem might be?

**Comment by rbroggi** [comment]
I found a futher lead:

```
```
cat .local/share/sddm/wayland-session.log

Hyprland: error while loading shared libraries: libdisplay-info.so.1: cannot open shared object file: No such file or directory
```

it seems that after the upgrade above Hyprland cannot find the `libdisplay-info.so.1` lib...

**Comment by rbroggi** [comment]
Before the upgrade:

```
❯ ldconfig -p | grep display        
        libdisplay-info.so.1 (libc6,x86-64) => /usr/lib/libdisplay-info.so.1
        libdisplay-info.so (libc6,x86-64) => /usr/lib/libdisplay-info.so
```

after the upgrade:

```
❯ ldconfig -p | grep display
        libdisplay-info.so.2 (libc6,x86-64) => /usr/lib/libdisplay-info.so.2
        libdisplay-info.so (libc6,x86-64) => /usr/lib/libdisplay-info.so
```

**Comment by rbroggi** [comment]
I found the issue - at the end the issue was that I had 2 hyperland versions installed - one was compiled from source by me and the other was the package manager one - after upgrading some system libs the one compiled from source broke cause it expected the `libdisplay-info` version 1. I've removed the version compiled from source and it works well again...
