### ISSUE TITLE
Layer shell windows hide when connected to an external monitor that goes on power save when you suspend

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#666]
When I suspend layer shell windows on my monitor disapear I believe this is due to the monitor turning onto power save mode so when I open my laptop Hyprland moves my windows to my laptop, then my monitor starts and the windows are moved back this is fine except when I have a layer shell window on my monitor and suspend, let the monitor use power saving mode, then reopen the laptop, the window disapears with no error in the console. More info https://github.com/wmww/gtk-layer-shell/issues/135

**Comment by vaxerski** [comment]
why not restart the bar on lid open

**Comment by godalming123** [comment]
Would that be in the bar program codebase or manually? If I dont have to restart on any other wayland WM why should that be the case with hyprland also this breaks other bars such as eww.

**Comment by vaxerski** [comment]
hyprland will remove all references to orphaned layerSurfaces. Although this probably is not the best idea - yes, that's how it is right now. When you unplug a monitor, it orphans all the LSes

**Comment by godalming123** [comment]
I have updated codebase of my bar so it automatically opens on new monitors when they are connected

**Comment by vaxerski** [comment]
I generally dislike the apps that keep their LS when a monitor is unplugged. A LS connects to a wl_output, and that gets destroyed. As such, the LS should be too.

**Comment by godalming123** [comment]
Are you saying I should destroy the window object when a monitor is disconected? If so this may be implemented in future but right now I can't be bothered.

**Comment by vaxerski** [comment]
I am saying your bar / whatever program should destroy its LS when the monitor it's on gets destroyed.

**Comment by dnkl** [comment]
> I am saying your bar / whatever program should destroy its LS when the monitor it's on gets destroyed.

Not sure if this is still relevant, but is there a reason you're not calling the layer surfaces' `closed()` event when their outputs are destroyed?

From the protocol documentation:

> The closed event is sent by the compositor when the surface will no longer be shown. **The output may have been destroyed** or the user may have asked for it to be removed. Further changes to the surface will be ignored. The client should destroy the resource after receiving this event, and create a new surface if they so choose.

This question popped up here: https://codeberg.org/dnkl/yambar/issues/213

**Comment by vaxerski** [comment]
> is there a reason you're not calling the layer surfaces' closed() event when their outputs are destroyed?

yeah. The reason is that I forgot to

**Comment by vaxerski** [comment]
should be done with a33ecec61ef4c5749a17f52b15f0e0d0722b1f3d
