### ISSUE TITLE
Inputs, keyboard, touchpad, and other settings generate error notification

### ISSUE THREAD

**Issue by engjpacheco** [hyprwm/Hyprland#6669]
After the last update hyprland
Inputs, keyboard, touchpad, and other settings generate error notification, so when I comment those the error disappears but the configuration too, I mean if I comment the option of the touchpad, the error disappears but the touchpad goes disabled. I don't know if some variables changes the names or something related to that.

Thanks in advance

**Comment by lvlick** [comment]
@engjpacheco It looks like you aren't closing your general category.

The config should be: 
```
general {
  ...
}

input {
  kb_layout = gb,us
  ...
}
```

**Comment by vaxerski** [comment]
not a hyprland issue, you havent closed the general category

**Comment by engjpacheco** [comment]
aaa batman,  whata hawkeye, thanks,,, all the erros gone, 

Thanku guys
