### ISSUE TITLE
Wiki's version selector displays v0.41.0 for v0.41.1

### ISSUE THREAD

**Issue by 299792458ms** [hyprwm/Hyprland#6675]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

I do not know if both v0.40.0 and v0.41.1 wiki's are identical or not, but the page for v0.41.1 wiki displays that is for version v0.40.0. (Red text in top left corner). I'm sure it is not very important but a have seen people report issues when they did not read what version they are on an assume the wiki is wrong and this while its obviously a typo it could confuse some people.
![2024-06-26-170148_hyprshot](https://github.com/hyprwm/Hyprland/assets/152849182/fc9077a8-f7a2-47fa-b99f-2e58bd47738f)

### How to reproduce

open Hyprland's wiki site, select version v0.40.1, indicator shows v0.40.0.

**Comment by fufexan** [comment]
Looks like it only happens for 0.41.1, as 0.41.2 shows the correct version. Perhaps @vaxerski forgot to update the version.

**Comment by vaxerski** [comment]
nothing changed thats why
