### ISSUE TITLE
Xwayland cursor position gets stuck

### ISSUE THREAD

**Issue by Stoppedpuma** [hyprwm/Hyprland#6677]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e4d09aa3a9de9a9e71c10bf4b6800585b3db9a4c  (sessionLock: focus lock on creation based on mouse position (6658)).
```

</details>

### Description

Cursor position of windows running in Xwayland seems to get stuck at a certain position. Possible reason this might not have been reported yet is I'm using two displays.

### How to reproduce

Use window in Xwayland, seems to just happen randomly and persists until the session restarts.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/58333920/7d9cee26-d7af-4a2d-8b54-51fc2aa269f4

**Comment by wu4** [comment]
Likely related to #6625.

**Comment by vaxerski** [comment]
ye
