### ISSUE TITLE
Hyprland crashes on startup

### ISSUE THREAD

**Issue by SykikXO** [hyprwm/Hyprland#6680]
![IMG20240627090348.jpg](https://github.com/hyprwm/Hyprland/assets/72402072/2227cc63-5b83-47bd-ae76-518ad98cb1ce)

**Comment by khaneliman** [comment]
> ![IMG20240627090348.jpg](https://private-user-images.githubusercontent.com/72402072/343625711-2227cc63-5b83-47bd-ae76-518ad98cb1ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjE3ODksIm5iZiI6MTcxOTQ2MTQ4OSwicGF0aCI6Ii83MjQwMjA3Mi8zNDM2MjU3MTEtMjIyN2NjNjMtNWI4My00N2JkLWFlNzYtNTE4YWQ5OGNiMWNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA0MTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMTA4NzdlZTIzY2I5YzU5Yzg4YTJhOGQwM2EzZTVlZTM3ZGU4NmRjNDcwYWU1ODZjZTM1NzQ0ODY1YjU0YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUzdOihizXz5M4n8eEO7cdRAQ0_yr1kEMSeCcUe6Tzw)

Do you have WLR_RENDERER set to vulkan?

**Comment by lvlick** [comment]
Should be enough to install polkit and enable it, then reboot.

**Comment by SykikXO** [comment]
@lvlick just did and I hyprland started. 
@khaneliman I don't know how to check that, I just installed hyprland using pacman, and ran it.

Thankyou for helping me out.

**Comment by lvlick** [comment]
Glad it worked, you should close this issue.
