### ISSUE TITLE
[Hyprland 0.41.1] Logitech G903 scroll speed too high in XWayland clients and Alacritty.

### ISSUE THREAD

**Issue by CNR0706** [hyprwm/Hyprland#6681]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818

flags: (if any)


System Information:
System name: Linux
Node name: Gentoo-Linux-GPC
Release: 6.8.9-zen1-gentoo-dist
Version: #6 ZEN SMP PREEMPT_DYNAMIC Thu Jun 13 20:07:16 CEST 2024


GPU information:
29:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:
```

</details>

### Description

There is a bug with the Logitech G903 (and probably all devices supporting high-resolution scrolling) where the scroll speed in XWayland clients (and Alacritty) is ridiculously high. This is especially problematic in games where it can be very hard to select weapons for example.

Modification of the scroll_factor variable does not seem to affect the issue.

I suppose this could also be viewed as a regression as Hyprland did not have high-resolution scrolling support for Wayland clients before, thus this bug did not exist. I am unable to bisect right now though.

### How to reproduce

1. Connect device capable of high-resolution scrolling.
2. Scroll in an XWayland application.
3. Scroll in a Wayland application.
4. Compare scroll speed.

**Comment by Oglo12** [comment]
I also have a Logitech mouse and I have this issue.

**Comment by pink10000** [comment]
Also happening on Logitech M720

**Comment by The0neFreeMan** [comment]
Same here. Logitech G502. I confirmed it was an issue with the last several releases as I tested an older version and the issue immediately went away.

**Comment by mrmbernardi** [comment]
I've got it as well. Particularly annoying in video games

**Comment by jordan-josephs** [comment]
I have it as well on a G502X. I noticed it in minecraft as I zoom through the inventory bar while only moving my scroll wheel 1 notch.

**Comment by acul009** [comment]
I'm having that Issue with a Logitech g502 as well.

While I really like it for things like websites, it's basically unusable for gaming.
Would it be possible to make this configurable?

I'm happy to provide additional info if needed.

**Comment by noah427** [comment]
I have the exact opposite of this somehow with my G502 hero. I can unlock the scroll wheel and spin it with a compressed air canister and then only scroll like 1%

**Comment by Surpus** [comment]
Same with the mx master 3. I tried changing scroll_factor and using imwheel, neither of which worked.

**Comment by xor-bits** [comment]
I ran a git bisect and this commit [d0a224a4915b5a90555818ed3f9e49e1a61b7cdb](https://github.com/hyprwm/Hyprland/commit/d0a224a4915b5a90555818ed3f9e49e1a61b7cdb) seems to be the issue

**Comment by CNR0706** [comment]
> I ran a git bisect and this commit [d0a224a4915b5a90555818ed3f9e49e1a61b7cdb](https://github.com/hyprwm/Hyprland/commit/d0a224a4915b5a90555818ed3f9e49e1a61b7cdb) seems to be the issue

Thank you for the bisect :)

**Comment by Agent00Ming** [comment]
If you read the pull request thread, you'd know that this was known. It was a decision between breaking scrolling after the first click or scrolling too fast. Pick your poison :trollface:. JK, a fix is on the way either in #6608 or soon after because of the new backend making it easier (wlroots does a funny and sway uses a workaround to circumvent this issue)

**Comment by mrmbernardi** [comment]
Is there a workaround in the meantime?

**Comment by noahfraiture** [comment]
> > Is there a workaround in the meantime?
> 
> You can disable the `hid_logitech_hidpp` kernel module (see [this comment](https://github.com/hyprwm/Hyprland/issues/6707#issuecomment-2211786996) on a duplicate issue). After you create the file you need to rebuild your init ramdisk (on arch it's `sudo mkinitcpio -P`)
> 
> If you don't want to mess with kernel modules, what worked for my G502 Lightspeed and might work for you as a workaround until this is fixed in hyprland is using it in wired mode instead of using the wireless adapter, as for some reason that doesn't use hi-res scrolling.

This actually broke my system, it made me start in emergency shell

**Comment by noahfraiture** [comment]
> > This actually broke my system, it made me start in emergency shell
> 
> sorry to hear that, i simply shared what worked for me 🤷🏻‍♂️. are you sure you didn't misconfigure your system in another way that caused this?

Maybe but I touched nothing else and it's been 2 hour for now that I'm trying to get as that will boot. I reach the grub, and then ahci error -22 can't find device with UUID
However I tried to rebuild the init frames and the problem persist

**Comment by Agent00Ming** [comment]
I wrote up a PR that works on main branch and aquamarine branch. Please have a look at #6881.
