### ISSUE TITLE
misc:middle_click_paste the set value 'true' never changes. 

### ISSUE THREAD

**Issue by kRHYME7** [hyprwm/Hyprland#6683]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Hyprland, built from branch main at commit e4d09aa3a9de9a9e71c10bf4b6800585b3db9a4c  (sessionLock: focus lock on creation based on mouse position (6658)).
Date: Tue Jun 25 23:22:38 2024
Tag: v0.41.2-5-ge4d09aa3, commits: 4891

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.9.6-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:48:59 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:>
```

</details>

### Description

# Minor bug (but very uncomfortable) 

img1:
even If I make the ` misc:middle_click_paste`  into false the set value never change. but the int value changes. 

This is a bit annoying as some CAD softwares needs midle click to pan/move the perspective. Now it end up pasting something. 

Thanks!

### How to reproduce

` hyprctl getoption misc:middle_click_paste ` 

### Crash reports, logs, images, videos

img1

![image](https://github.com/hyprwm/Hyprland/assets/53417443/8c987ca9-ab07-4712-8dec-abed6e404363)

img2
![image](https://github.com/hyprwm/Hyprland/assets/53417443/dea39483-5359-429f-a630-8b45175ae8f0)

**Comment by vaxerski** [comment]
set is a flag that tells you whether the value was explicitly set (true) or sourced from defaults (false). The stored value is the `int` field.
