### ISSUE TITLE
Hyprland crashes on NVIDIA with Gentoo

### ISSUE THREAD

**Issue by CoolSoulz** [hyprwm/Hyprland#6690]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
(cant do it, dont have access to hyprland. I have mostly a base config but with some extras for NVIDIA)
I'm gonna attach my config below (it is a conf file, had to add the txt extension because github)
[hyprland.conf.txt](https://github.com/user-attachments/files/16021732/hyprland.conf.txt)

```

</details>

### Description

I tried to use Hyprland on Gentoo on NVIDIA, it crashed when trying to uses

### How to reproduce

Don't know, I just installed it via emerge hyprland on NVIDIA and it didn't work

### Crash reports, logs, images, videos

[hyprlandCrashReport29654.txt](https://github.com/user-attachments/files/16021698/hyprlandCrashReport29654.txt)
[core.txt](https://github.com/user-attachments/files/16021727/core.txt)
core is the core dump, not a txt. had to rename it because github

**Comment by vaxerski** [comment]
> "DRI2: failed to load driver"

driver issue. Consider reading the nvidia wiki page.

> Don't know, I just installed it via emerge hyprland on NVIDIA and it didn't work

this is not kde
