### ISSUE TITLE
Web Browser "Right Click" Pop-up Menu With Weird Border

### ISSUE THREAD

**Issue by ciesling** [hyprwm/Hyprland#6691]
### Regression?

 No

### Description

When I right click using any internet web browser like chrome, firefox, chromium, etc. I see a thick transparent border around the pop-up menu.

### How to reproduce

Open a browser while running hyprland as your desktop environment. Right click anywhere on the browser. Experience a T H I C C transparent border around pop-up menu.

**Comment by vaxerski** [comment]
its blur. you can use ignorealpha to something like 0.1 to rid of it

make sure the browser is in wayland native mode (chromium doiesnt do it by default, see wiki)

**Comment by be4zad** [comment]
ignorealpha didnt work for me. I disabled blur and it fixed.

**Comment by Flinner** [comment]
I went to `chrome://flags/`, Set Preferred Ozone platform to "Wayland". solved the issue

**Comment by carlosrl19** [comment]
2025 and Flinner's answer is still working!
