### ISSUE TITLE
Don't follow windowrule workspace

### ISSUE THREAD

**Issue by liabri** [hyprwm/Hyprland#670]
In some cases it is not desirable to follow a window when it is opened in another workspace using a windowrule, so a follow option should be introduced to this windowrule. This is quite common in other WMs such as bspwm.

**Comment by vaxerski** [comment]
workspace x silent

**Comment by liabri** [comment]
Oh, sorry. I didn't realise what silent meant lol.

**Comment by vaxerski** [comment]
ye
