### ISSUE TITLE
Disabling the memory for movefocus

### ISSUE THREAD

**Issue by aksu560** [hyprwm/Hyprland#6704]
### Description

Currently, if you have window setup with 2 vertically tiled windows to the side, and one large main window (essentially just master layout, but on dwindle), if you move focus away from the bottom of the vertical stack, to the main window, and then back, it will return to the bottom window. Overall, desired behaviour, but ability to disable this would be nice, to ensure consistency (always the same inputs to navigate from one window to another)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/6d42ae6d-e7f4-4912-adbb-b30b12ac8738)
rtfm
