### ISSUE TITLE
Default workspace r~1 for monitor

### ISSUE THREAD

**Issue by TRPB** [hyprwm/Hyprland#6709]
### Description

There may be a way to do this but I'm not sure.

I'm coming from Wayfire and the one thing I miss is the workspace model. Each monitor gets its own 3x3 grid of workspaces.

If I press super+1 with DP-1 focused, it switches the workspace on that monitor to 1, super+2 does the same. In this regard, each monitor has its own set of 9 workspaces. Super+N is *always* related to the active monitor.

I've been able to replicate this in hyprland with this config:

```

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, r~1
bind = $mainMod, 2, workspace, r~2
bind = $mainMod, 3, workspace, r~3
bind = $mainMod, 4, workspace, r~4 
bind = $mainMod, 5, workspace, r~5 
bind = $mainMod, 6, workspace, r~6 
bind = $mainMod, 7, workspace, r~7 
bind = $mainMod, 8, workspace, r~8 
bind = $mainMod, 9, workspace, r~9
bind = $mainMod, 10, workspace, r~10 

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, r~1
bind = $mainMod SHIFT, 2, movetoworkspace, r~2
bind = $mainMod SHIFT, 3, movetoworkspace, r~3
bind = $mainMod SHIFT, 4, movetoworkspace, r~4
bind = $mainMod SHIFT, 5, movetoworkspace, r~5
bind = $mainMod SHIFT, 6, movetoworkspace, r~6
bind = $mainMod SHIFT, 7, movetoworkspace, r~7
bind = $mainMod SHIFT, 8, movetoworkspace, r~8
bind = $mainMod SHIFT, 9, movetoworkspace, r~9
bind = $mainMod SHIFT, 0, movetoworkspace, r~1
```

`r~` is doing all the heavy lifting here.

While this works, I often end up with entirely lost windows if I do this:

- Start hyprland
- Open a program e.g. firefox on DP-1
-  Press SUPER+2 to switch to workspace 2
- Press SUPER+1 to switch to workspace 1

Firefox is lost forever, If I cycle through the workspaces 0-9 with the keys there's no way to get it back.

However, this is fixed by:

- Start hyprland
- **Press SUPER+1 on each display before doing anything else** to set the workspace
- Open a program e.g. firefox on DP-1
- Press SUPER+2 to switch to workspace 2
- Press SUPER+1 to switch to workspace 1
- Firefox is now on workspace 1 and I can get back to it.

The problem is, there doesn't seem to be a way to configure `r~1` as the default workspace for a monitor. I'd like to be able to do something like:

```
workspace = r~1,default:true,monitor:DP-1
workspace = r~1,default:true,monitor:DP-2
```

I can probably get it working with `exec-once` and `hyprctl` to set the defaults for each monitor assuming I can send `r~1`  but it would be good to have a config options for it.

**Comment by myryk31415** [comment]
maybe you just need to set some default workspace for each monitor? I mean that should be r~1 automatically then shouldn't it?

**Comment by TRPB** [comment]
Actually after testing it again my suggestion

```
workspace = r~1,default:true,monitor:DP-1
workspace = r~1,default:true,monitor:DP-2
```

Does work, I hadn't restarted hyprland when I tested it, you can use `r~` in workspace!
