### ISSUE TITLE
animation jitter when combining `workspace silent` & `fullscreen` windowrules

### ISSUE THREAD

**Issue by liabri** [hyprwm/Hyprland#671]
To reproduce apply the `fullscreen` & `workspace x silent` windowrules to the same application. eg:
```
windowrule=fullscreen,^(firefox)$
windowrule=workspace 1 silent,^(firefox)$
```

The outcome is a jitter in the animation as shown in the video below (there are 2 because discord launches 2 windows): 

https://user-images.githubusercontent.com/40229335/190617350-e15c42c0-b7f0-40b8-8906-5c1260dfdf71.mp4

**Comment by vaxerski** [comment]
fixed in fa2d81b649aaccd936193ac4341431c0836a321b
