### ISSUE TITLE
Toggle Workspaces

### ISSUE THREAD

**Issue by Prabhuomkar9** [hyprwm/Hyprland#6718]
We have `togglespecialworkspace` modifier to toggle special workspace

I was thinking if there was a way for me to toggle last and current workspace, (exlcuding special workspaces)

i very frequently go between workspace 1 and 2 as i keep terminal in one and firefox in another,

for example,
`bind = Super, grave, someNewDispacteher`
which would swap last workspace

i can use special workspace for this, but was thinking if there there was a native solution, or a workaround, just like how hyprwiki has a workaround for minimizing window

**Comment by kiecla** [comment]
go here https://wiki.hyprland.org/Configuring/Variables/#binds
and Ctrl-F for "workspace_back_and_forth"
does that do what you want?

**Comment by Prabhuomkar9** [comment]
> go here https://wiki.hyprland.org/Configuring/Variables/#binds and Ctrl-F for "workspace_back_and_forth" does that do what you want?

its so funny thay i digged the entire wiki just to put this issue and turns out it was already solved. 😅
