### ISSUE TITLE
Simulating mouse input

### ISSUE THREAD

**Issue by myryk31415** [hyprwm/Hyprland#6719]
### Description

Simulating mouse input would be awesome to have. Basically the `sendshortcut` dispatcher but instead of sending keys it would send mouse movement / scrolling / clicks. Or the `movemouse` dispatcher but with relative values.

Does that sound feasible? And if yes how would you go about that?

I already had a look around the source code but I don`t have enough understanding of it to assess whether it makes any sense for me to try to implement this or whether it would require major changes.

**Comment by myryk31415** [comment]
Was able to simulate mouse movement, but it failed to update the position correctly (just like the movemouse dispatcher) so e.g. mouse clicks would still register on the old location.

Closing because I stopped working on it and the issue's been silent for half a year

**Comment by soufhehe** [comment]
`ydotool mousemove --absolute -x 100 -y 100 && ydotool click 0xC0`

works for me

needs ydotool tough

**Comment by myryk31415** [comment]
great workaround :)
