### ISSUE TITLE
Waybar, go to workspcae on click

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#672]
![screenshot_20220916_162232](https://user-images.githubusercontent.com/90208727/190623611-cce58ad2-c256-4162-ba86-ab0039cb2057.png)

from the waybar wiki, it tells me to use this command, however on using it...

![screenshot_20220916_162515](https://user-images.githubusercontent.com/90208727/190623941-0338a77c-09b5-416a-a572-8af83669a4a7.png)

is their anything i am doing wrong, i mean, on-click takes any terminal command so, can i just know the command i should use here to switch to the workspace i click

**Comment by vaxerski** [comment]
does it work in sway or wayfire?

**Comment by System-x64** [comment]
![sway1](https://user-images.githubusercontent.com/90208727/190659330-d621cf81-6f81-4f33-a470-f700a757f4b8.png)

not on waybar but sway has its own i3 like bar which does support this on click function

**Comment by vaxerski** [comment]
oh sorry i am an idiot. The wlr workspqces protocol does not support sending a click to change request. Use the patched `waybar-hyprland-git` (aur) or apply the patch yourself that you find there in the pkgbuild. it will send a hyprctl dispatch on click

**Comment by System-x64** [comment]
but `waybar-hyprland-git` will remove `waybar-experimental-git`....does `waybar-hyprland-git` also support wlr/workspaces?

**Comment by vaxerski** [comment]
`waybar-hyprland-git` is `waybar-experimental-git` + patches

**Comment by System-x64** [comment]
ohh noice

**Comment by System-x64** [comment]
yeeeee...it worky....thx ❤️

**Comment by System-x64** [comment]
also...what about that spotify opacity thingy...is it done?

**Comment by vaxerski** [comment]
no

**Comment by DreamMaoMao** [comment]
> yeeeee...it worky....thx heart

hello  i  have  the same problem ,could you tell me what should i do ? thanks you!

**Comment by mbreno-op** [comment]
have you did this? https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#scrolling-through-workspaces

**Comment by DreamMaoMao** [comment]
> mbreno

sorry,I make a mistake ,i use the waybar project instead of hyprland-waybar project .

now it work.
