### ISSUE TITLE
Key 248 and other NoSymbol keys not working

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/Hyprland#6721]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.35-2-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 21:05:23 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Description

this setting `bind = , 248, exec, grim -g "$(slurp)"` does not work for some mysterious reason (it used to a few versions back so this is some kind of regression), changing the key to a different one works, and reading another key by it's keycode instead of keysym also works, so it's like Hyprland just really does not like this specific keycode.

`wev` and `xev` both display the key properly when it's pressed (it's FN+Print on my laptop) but Hyprland will not act on it.

This is on Hyprland 1.41.2-2

On an older version of Hyprland (forgot exactly, but it was new, 1.40 at oldest, possibly as recent as 1.41.1) I was also having an issue where when I pressed this same key, many other keybinds would fire off in hyprland (volume up/down, xf86launch, brightness...) before that version the key worked completely fine on Hyprland and i've been using it for months.

The same keybind also works fine on i3.

From wev:
```
[14:     wl_keyboard] key: serial: 36238; time: 19877312; key: 248; state: 1 (pressed)
                      sym: NoSymbol     (0), utf8: ''
```

My haphazard guess would be that this issue might have something to do with the keysym being NoSymbol.

### How to reproduce

set `bind = , 248, exec, grim -g "$(slurp)"` and press that button.

**Comment by vaxerski** [comment]
have you tried `code:248`?

**Comment by Rabcor** [comment]
> have you tried `code:248`?

Yeah, made no difference.

**Comment by MrYuto** [comment]
I have the same issue with a key after updating to 0.41.0:

`bind = , code:197, workspace, e+1`

```
[14:     wl_keyboard] key: serial: 6078; time: 1894859; key: 197; state: 1 (pressed)
                      sym: NoSymbol     (0), utf8: ''
```

I think the problem is that this key is 'NoSymbol' because as far as I've tested other keys have a symbol. Before it stopped working, sometimes after startup, this key triggered `print`, which I think was usually after a new update. I had to unbind and rebind `print`.

**Comment by hdm9527** [comment]
Similar problem? fcitx5 shortcut to switch input method sometimes no popup, log as follows.
![image](https://github.com/hyprwm/Hyprland/assets/39702328/6c41715e-872d-419b-8e75-e6078b5fd686)

**Comment by vaxerski** [comment]
can someone bisect this?

**Comment by MrYuto** [comment]
@vaxerski  I tried to bisect it but couldn't reproduce it in the debug version of the same installed version `v0.41.2`. I installed git version 4141e6755022edc19cd37cd7ad077a93b3bae5bd and I still have the issue. It's a pain to bisect if I have to install and restart every time.

**Comment by vaxerski** [comment]
such is life, but I don't have any way to test this so without a bisect you'll likely not get this fixed (unless you write a patch yourself)

**Comment by Rabcor** [comment]
> such is life, but I don't have any way to test this so without a bisect you'll likely not get this fixed (unless you write a patch yourself)

Are you sure you don't have any nosymbol key on your keyboard?  Do you have an FN key on it? You can just try holding it and smashing random buttons till you find a nosymbol one.

Alternatively maybe you could use a keystroke generator, you know keycode 248 is one that generates the issue, so something like ydotool might be able to replicate this for you?

**Comment by MrYuto** [comment]
@vaxerski I just dug into the code and look what I found!!! Somehow when you install Hyprland, it only runs the following block:

https://github.com/hyprwm/Hyprland/blob/51ffd7fa6f186419276e5d3d5fe141a3fdb3c55c/src/managers/KeybindManager.cpp#L641-L666

```
[LOG] Key event: KEYCODE = 116, keysym = 65364, internalKeysym = 65364
[LOG] Handling keybind: modmask = 0, keycode = 116, keysym = 65364, keyName = , pressed = false
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] Key event: KEYCODE = 36, keysym = 65293, internalKeysym = 65293
[LOG] Handling keybind: modmask = 0, keycode = 36, keysym = 65293, keyName = , pressed = true
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] Window 62ddac6c1bd0 set title to cat $XDG_RUNTIME_DIR ~
[LOG] Searching for matching rules for Alacritty (title: cat $XDG_RUNTIME_DIR ~)
[LOG] Window rule opacity 0.90 0.90 -> class:Alacritty matched [Window 62ddac6c1bd0: title: "cat $XDG_RUNTIME_DIR ~"]
[LOG] cursorImage request: shape 9 -> text
[hc] getShapesC: found 1 images for text
[ERR] rbo: glCheckFramebufferStatus failed
[LOG] cursorImage request: shape 1 -> default
[hc] getShapesC: found 1 images for default
[ERR] [GLES] Error in call at 142@Texture.cpp: 0x502
[ERR] rbo: glCheckFramebufferStatus failed
[LOG] Key event: KEYCODE = 36, keysym = 65293, internalKeysym = 65293
[LOG] Handling keybind: modmask = 0, keycode = 36, keysym = 65293, keyName = , pressed = false
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
[LOG] oMg such performance hit!!11!
```

and d1340bd1d8eedd274283e0cb2568a3ed67b58c81 is the reason why `NoSymbol` keys stopped working. Interestingly, if you run Hyprland nested in a window, my `NoSymbol` key works, and the `print` keybind is also triggered, lol.

**Comment by vaxerski** [comment]
MRs welcome

**Comment by MrYuto** [comment]
Sorry, I'm not a C++/Linux programmer, giving you a hint was the only thing I could do.

**Comment by ikalco** [comment]
@MrYuto does this [patch.txt](https://github.com/user-attachments/files/16513058/patch.txt) work?

**Comment by MrYuto** [comment]
@ikalco Yes, I don't see any issues

**Comment by Rabcor** [comment]
can confirm, it's fixed.
