### ISSUE TITLE
neither inactive_timeout nor cursor_inactive_timeout work

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#6728]
### Regression?

Yes

### System Info and Version

```sh
Hyprland, built from branch  at commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).
Date: Thu Jun 13 09:54:06 2024
Tag: v0.41.1, commits: 4818
System Information:
System name: Linux
Node name: vincent-laptop
Release: 6.6.34-1-MANJARO
Version: #1 SMP PREEMPT_DYNAMIC Wed Jun 19 19:00:06 UTC 2024
os-release: NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch

```

### Description

Though the hyprland version I used is not git version, but 'inactive_timeout = 5' is deemed unacceptable, contrary to hyprland wiki and source file, maybe it has been corrected. 
just report it :)

### How to reproduce

add 'inactive_timeout = 5' to general { ... } in hyprland.conf

**Comment by nhosama** [comment]
Shouldn't it be like below?
```
cursor {
    inactive_timeout = 5
}
```

**Comment by vincentaxhe** [comment]
yes! It was put in general.
