### ISSUE TITLE
The master window in master + stack layout gets changed randomly with a multimonitor setup

### ISSUE THREAD

**Issue by Toasterbirb** [hyprwm/Hyprland#673]
There seems to be something that causes the master window in master + stack layout to get swapped on a supposedly inactive monitor

I have 3 monitors and this has happened quite randomly in two different scenarios:
- Opening bemenu-run. For example, I open bemenu on the 2nd monitor and the master window suddenly gets swapped on my 3rd monitor
- Running `hyprctl dispatch focusmonitor` with a keybind to cycle from monitor to another

I haven't found a way to replicate this issue and its extremely random

**Comment by MonAaraj** [comment]
bemenu has Xorg and Wayland backends; are you sure that bemenu is using the Wayland backend?

**Comment by Toasterbirb** [comment]
I'm using the wayland backend. Xwayland doesn't really work too well on my system for some reason (or at least in hyprland).

I'll post some logs when I use hyprland next time around. I can't really daily drive it because it doesn't recover from suspend (it glitches out really badly and is unusable), so I'd have to keep my computer running 24/7, which isn't really doable with the current electricity costs

**Comment by vaxerski** [comment]
is this still a thing?

**Comment by Toasterbirb** [comment]
I tested the latest version and couldn't replicate the issue so I'd say that this problem has been fixed.
