### ISSUE TITLE
'highres' and 'highrr' makes external monitor no signal

### ISSUE THREAD

**Issue by ZreXoc** [hyprwm/Hyprland#6735]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d7ea1b7785f31e9fd6477490309721a19a835592  (xwayland: break cyclic loop of parents (6722)).
Date: Mon Jul 1 06:26:08 2024
Tag: v0.41.2-14-gd7ea1b77, commits: 4900

flags: (if any)


System Information:
System name: Linux
Node name: xc-arch
Release: 6.9.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28e0] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  555.58  Tue Jun 18 20:52:44 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

After update hyprland-git from `0.40.0.r156.098ac916-1` to `0.41.2.r14.d7ea1b77-1`, my external monitor has no signal with  `highres` and `highrr`:
```
monitor=HDMI-A-1,highres,0x0,1,transform,0
```
```
monitor=HDMI-A-1,highrr,0x0,1,transform,0
```
The monitor can be found by `hyprctl monitors` and I can move my mouse into it, just no signal.
`preferred` and set the resolution manually work fine.
`highres` and `highrr` worked before and now still works for my laptop's monitor.

### How to reproduce

in `hyprland.conf`:
```
monitor=HDMI-A-1,highres,0x0,1,transform,0
```
where `HDMI-A-1` is an external monitor.

### Crash reports, logs, images, videos

my current conf:
```
...
# Monitors
monitor=HDMI-A-1,preferred,0x0,1,transform,0
monitor=eDP-2,highres,-900x380,auto,transform,3
#monitor=eDP-2,preferred,-1600x400,auto,transform,0
#monitor=eDP-2,preferred,0x0,auto,transform,0

workspace = 1, monitor:HDMI-A-1, default:true
workspace = 0, monitor:eDP-2, default:true, persistent:true
workspace=eDP-2,0, default:true, persistent: true

...
```
```
❯ hyprctl monitors
Monitor eDP-2 (ID 0):
	2560x1440@240.00000 at -900x380
	description: BOE 0x0B7D
	make: BOE
	model: 0x0B7D
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 34 0 0
	scale: 1.60
	transform: 3
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@240.00Hz 2560x1440@60.00Hz

Monitor HDMI-A-1 (ID 1):
	2560x1440@60.00000 at 0x0
	description: Shenzhen KTC Technology Group H27T13
	make: Shenzhen KTC Technology Group
	model: H27T13
	serial: 
	active workspace: 4 (4)
	special workspace: 0 ()
	reserved: 0 34 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@60.00Hz 2560x1440@99.97Hz 2560x1440@75.00Hz 1920x1080@75.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1360x765@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz 640x480@59.93Hz
```

**Comment by ikalco** [comment]
can you give hyprland.log?
https://wiki.hyprland.org/Crashes-and-Bugs/#getting-the-log

**Comment by ZreXoc** [comment]
> can you give hyprland.log? https://wiki.hyprland.org/Crashes-and-Bugs/#getting-the-log

[hyprland.log](https://github.com/user-attachments/files/16064952/hyprland.log)

**Comment by ikalco** [comment]
try setting cursor:no_hardware_cursors in config

**Comment by ZreXoc** [comment]
not work :(
And I noticed that there's no error in hyprland.log after I changed `prefered` to `highres`

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by romanstingler** [comment]
can you try installing the latest version 
`yay -S aquamarine-git hyprlang-git hyprcursor-git hyprutils-
git hyprland-git --overwrite="*"`

if you have hyprland installed, you have to uninstall it via 
`yay -R hyprland`

I tested it, the monitor goes black for 1 sec and then turns on with the changed resolution
`monitor=DP-3, highres, 6400x0, 1.0`

```
~ ❯ hyprctl monitors
                                                                               31.846s 22:31
Monitor eDP-1 (ID 0):
	2560x1440@60.00000 at 3840x0
	description: California Institute of Technology 0x1500
	make: California Institute of Technology
	model: 0x1500
	serial: 
	active workspace: 4 (4)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 3840x2160@60.00Hz 

Monitor DP-3 (ID 2):
	4096x2160@59.94000 at 6400x0
	description: Hisense Electric Co. Ltd. HISENSE 0x676C626C
	make: Hisense Electric Co., Ltd.
	model: HISENSE
	serial: 0x676C626C
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 3840x2160@60.00Hz 4096x2160@60.00Hz 4096x2160@59.94Hz 4096x2160@50.00Hz 4096x2160@30.00Hz 4096x2160@29.97Hz 4096x2160@25.00Hz 4096x2160@24.00Hz 4096x2160@23.98Hz 3840x2160@60.00Hz 3840x2160@60.00Hz 3840x2160@59.94Hz 3840x2160@59.94Hz 3840x2160@50.00Hz 3840x2160@50.00Hz 3840x2160@30.00Hz 3840x2160@29.97Hz 3840x2160@25.00Hz 3840x2160@24.00Hz 3840x2160@23.98Hz 2560x1440@59.95Hz 1920x1080@120.00Hz 1920x1080@119.88Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@30.00Hz 1920x1080@29.97Hz 1920x1080@25.00Hz 1920x1080@24.00Hz 1920x1080@23.98Hz 1280x1024@60.02Hz 1280x960@60.00Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@60.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@60.00Hz 640x480@59.94Hz 
	```

**Comment by ZreXoc** [comment]
> can you try installing the latest version `yay -S aquamarine-git hyprlang-git hyprcursor-git hyprutils- git hyprland-git --overwrite="*"`
> 
> if you have hyprland installed, you have to uninstall it via `yay -R hyprland`
> 
> I tested it, the monitor goes black for 1 sec and then turns on with the changed resolution `monitor=DP-3, highres, 6400x0, 1.0`
> 
> ```
> ~ ❯ hyprctl monitors
>                                                                                31.846s 22:31
> Monitor eDP-1 (ID 0):
> 	2560x1440@60.00000 at 3840x0
> 	description: California Institute of Technology 0x1500
> 	make: California Institute of Technology
> 	model: 0x1500
> 	serial: 
> 	active workspace: 4 (4)
> 	special workspace: 0 ()
> 	reserved: 0 35 0 0
> 	scale: 1.00
> 	transform: 0
> 	focused: no
> 	dpmsStatus: 1
> 	vrr: 0
> 	activelyTearing: false
> 	disabled: false
> 	currentFormat: A XRGB8888 H XRGB8888
> 	availableModes: 3840x2160@60.00Hz 
> 
> Monitor DP-3 (ID 2):
> 	4096x2160@59.94000 at 6400x0
> 	description: Hisense Electric Co. Ltd. HISENSE 0x676C626C
> 	make: Hisense Electric Co., Ltd.
> 	model: HISENSE
> 	serial: 0x676C626C
> 	active workspace: 3 (3)
> 	special workspace: 0 ()
> 	reserved: 0 35 0 0
> 	scale: 1.00
> 	transform: 0
> 	focused: yes
> 	dpmsStatus: 1
> 	vrr: 0
> 	activelyTearing: false
> 	disabled: false
> 	currentFormat: A XRGB8888 H XRGB8888
> 	availableModes: 3840x2160@60.00Hz 4096x2160@60.00Hz 4096x2160@59.94Hz 4096x2160@50.00Hz 4096x2160@30.00Hz 4096x2160@29.97Hz 4096x2160@25.00Hz 4096x2160@24.00Hz 4096x2160@23.98Hz 3840x2160@60.00Hz 3840x2160@60.00Hz 3840x2160@59.94Hz 3840x2160@59.94Hz 3840x2160@50.00Hz 3840x2160@50.00Hz 3840x2160@30.00Hz 3840x2160@29.97Hz 3840x2160@25.00Hz 3840x2160@24.00Hz 3840x2160@23.98Hz 2560x1440@59.95Hz 1920x1080@120.00Hz 1920x1080@119.88Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@30.00Hz 1920x1080@29.97Hz 1920x1080@25.00Hz 1920x1080@24.00Hz 1920x1080@23.98Hz 1280x1024@60.02Hz 1280x960@60.00Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@60.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@60.00Hz 640x480@59.94Hz 
> 	```
> ```

```sh
paru -Q aquamarine-git hyprlang-git hyprcursor-git hyprutils-git hyprland-git

aquamarine-git 0.4.0_r212.gaac97a1-1
hyprlang-git 0.5.2.r11.g5b175c97-1
hyprcursor-git 0.1.9.r11.g912d5602-1
hyprutils-git 0.2.1.r3.g8976e3f6-1
hyprland-git 0.42.0.r113.9b54342b-1
```

`monitor=HDMI-A-1,highres,auto,1`:
```
❯ hyprctl monitors
Monitor eDP-2 (ID 0):
	2560x1440@240.00000 at -900x0
	description: BOE 0x0B7D
	make: BOE
	model: 0x0B7D
	serial: 
	active workspace: 10 (10)
	special workspace: 0 ()
	reserved: 0 34 0 0
	scale: 1.60
	transform: 3
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 2560x1440@240.00Hz 2560x1440@60.00Hz 

Monitor HDMI-A-1 (ID 1):
	2560x1440@99.96500 at 0x0
	description: Shenzhen KTC Technology Group H27T13
	make: Shenzhen KTC Technology Group
	model: H27T13
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 34 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 2560x1440@60.00Hz 2560x1440@99.97Hz 2560x1440@75.00Hz 1920x1080@75.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1360x765@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz 640x480@59.93Hz 
```
And `monitor=HDMI-A-1,2560x1440@100,auto,1` does not work as well. I posted a trace log here: https://github.com/hyprwm/Hyprland/issues/7503

**Comment by romanstingler** [comment]
can you try disabling your eDP2 and then try if highrr works

**Comment by ZreXoc** [comment]
> can you try disabling your eDP2 and then try if highrr works

no :(

**Comment by romanstingler** [comment]
please build `yay -S hyprland-git aquamarine-git` new and add `env = AQ_NO_MODIFIERS,1` to your `hyperland.conf`

if it resolves your issue, please close the ticket, thx

**Comment by ZreXoc** [comment]
> please build `yay -S hyprland-git aquamarine-git` new and add `env = AQ_NO_MODIFIERS,1` to your `hyperland.conf`
> 
> if it resolves your issue, please close the ticket, thx

Sorry for the late response. The monitor has no signal in any resolution and refresh rate with `env = AQ_NO_MODIFIERS,1` set. Please continue [here](https://github.com/hyprwm/Hyprland/issues/7503) for more details

**Comment by ParaN3xus** [comment]
So how did you resolve this issue

**Comment by CmdrCloud** [comment]
I want to know as well, having a similar issue

**Comment by ikalco** [comment]
> I want to know as well, having a similar issue

He removed the AQ_NO_MODIFIERS=1 env variable (see #7889)

if that doesn't work then open a bug report in the DRM discussion section
