### ISSUE TITLE
[Proposal] Introduce a Beta period before declaring a release as stable to avoid major regressions.

### ISSUE THREAD

**Issue by CNR0706** [hyprwm/Hyprland#6738]
### Description

I appreciate all the work you (Vaxry) and your contributors put in Hyprland a lot. However there has been a significant increase in regressions in recent releases, some of which are major problems (like #6681). And that's okay, there's always gonna be breakage when changing major parts of the code.
However I think that introducing these breaking changes into a stable release is a big problem as it can not only be really annoying to Hyprland's users but also ruin Hyprland's reputation as a stable Wayland compositor over time. Issues like #6681 should have been caught and more importantly, could have been caught before a stable release of 0.41.1 if there was a Beta.

Introducing a brief Beta period before declaring a release as stable similar to other big projects would go a long way to making this problem less severe.

**Comment by vaxerski** [comment]
shouldn't that go to something like RFCs? https://github.com/hyprwm/RFCs

**Comment by NotAShelf** [comment]
This is in fact something that should be addressed by the RFC process, and I intend to create one soon. If you would like to discuss this, you can reach me on Discord by the handle `@notashelf` or on Matrix via `@raf:notashelf.dev`

**Comment by vaxerski** [comment]
I'll close this, yeah, take it to an RFC
