### ISSUE TITLE
JVM fatal error running Future Client specifically on Hyprland

### ISSUE THREAD

**Issue by Sophed** [hyprwm/Hyprland#6750]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 8bb75a223db3ea9471d05d74fbed3328334a9f78  (hyprctl completions: Use only awk rather than grep + awk).
Date: Tue Jul 2 20:46:20 2024
Tag: v0.41.2-18-g8bb75a22, commits: 4904

flags: (if any)


System Information:
System name: Linux
Node name: Vertex
Release: 6.9.7-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:27 +0000


GPU information: 
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  555.52.04  Tue Jun  4 13:54:58 UTC 2024


os-release: NAME="Arch"
PRETTY_NAME="Arch Linux"
ID="arch"
ID_LIKE="arch"
BUILD_ID=rolling


plugins:
```

</details>

### Description

This is gonna be a weird one.
Opening my game gets to the "Mojang Studios" splash screen before crashing with a JVM error. This only happens on when trying to run Future Client on Hyprland, any other game mod or desktop environment works fine. I have already spoken to the client developers and from what they can tell this isn't something they can fix.

### How to reproduce

Launch game with client in mods folder

### Crash reports, logs, images, videos

[prism log](https://mclo.gs/U9L8bmZ)
[hs_err_pid4456.log](https://github.com/user-attachments/files/16082111/hs_err_pid4456.log)

**Comment by vaxerski** [comment]
if this is a regression, please bisect: https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue

**Comment by Sophed** [comment]
[0b924f541c744f96d32c9a0d98dcfd90205bab4c](https://github.com/hyprwm/Hyprland/commit/0b924f541c744f96d32c9a0d98dcfd90205bab4c) is the first bad commit

I don't know how accurate that is entirely but that's all I could find

**Comment by 0-x-2-2** [comment]
This is related to enabling v-sync on the main menu.

**Comment by Sophed** [comment]
This is an XWayland issue and was resolved by using my system installation of GLFW to run the game.

**Comment by vaxerski** [comment]
closing then
