### ISSUE TITLE
Kill middle click paste

### ISSUE THREAD

**Issue by UltraBlackLinux** [hyprwm/Hyprland#6758]
### Description

I genuinely hate middle click paste. It's never been useful to me, and it generally just makes a button on my mouse absolutely useless. It's particularly annoying in pretty much any terminal where it's easy to accidentally press middle click and have it try to paste into the terminal instead of scrolling (and thus moving the scroll bar to the very bottom), making a lot of consecutive scrolls really, really tiring and frustrating.

The wiki section on disabling middle click basically tells you to disable the middle mouse button (which is very useful in just about any browser).

Please, add an option to disable this feature. It just gets in the way of normal mouse operation and wastes a mouse button.

**Comment by Agent00Ming** [comment]
`misc:middle_click_paste` https://wiki.hyprland.org/Configuring/Variables/#misc

**Comment by UltraBlackLinux** [comment]
Well thanks for the hint haha
not too long ago this wasn't a thing

**Comment by Agent00Ming** [comment]
Firefox has a built-in way to emulate the feature that you can disable in the browser's settings

**Comment by UltraBlackLinux** [comment]
thanks for the hint, that was it!
