### ISSUE TITLE
Multiple Workspace Selectors for Window/Workspace Rules

### ISSUE THREAD

**Issue by 299792458ms** [hyprwm/Hyprland#6767]
### Description

So I have been using a lot of window rules but I have not been able to set a rule for any given window on a workspace that satisfies 2 or more parameters. (This also applies to workspace rules)

For example:
(1.) windowrulev2 = noborder, onworkspace:w[t1], floating:0
(2.) windowrulev2 = noborder, onworkspace:s[true], onworkspace:w[t1], floating:0
(3.) windowrulev2 = noborder, onworkspace:s[true]w[t1], floating:0

Example 1 works as described and intended in the wiki, but example 2 and 3 do not work, they just catch the first of the multiple match types. Anyway I thought it would be nice to have workspace selector with multiple parameters and would appreciate if someone would point me on how to solve this if I am doing this wrong.

**Comment by vaxerski** [comment]
you can do that. Use 3, but put a space between ] and w

**Comment by 299792458ms** [comment]
> you can do that. Use 3, but put a space between ] and w

Thank you!
