### ISSUE TITLE
Bugs in specialworkspace and gestures 

### ISSUE THREAD

**Issue by Devarth123** [hyprwm/Hyprland#677]
example clip: 
https://user-images.githubusercontent.com/95016816/190858715-f1b29684-5d87-46da-a978-83139351a4c2.mp4

# Specialworkspace bug
- config for special workspace 
```
bind=ALTSHIFT,S,togglespecialworkspace
bind=ALTSHIFT,M,movetoworkspace,special
```
## Describe the bug 
  i cant toggle fullscreen in special workspace and if i do the window disappears while it is still focused in the special workspace 
 ## How to repoduce 
  have one window in special workspace and try to toggle it in fullscreen mode

# Gestures Bug 
- config 
```
gestures {
    workspace_swipe=yes
    workspace_swipe_fingers=4
    workspace_swipe_invert=no
    workspace_swipe_min_speed_to_force=1
}
```
## Describe the bug 
 this only happens when u have one window in special workspace and only one active workspace, when i swipe left instead of doing nothing it moves focus to some other workspace and when i swipe right after that it move focus to some other workspace not the active workspace i talked about
  ## How to reproduce 
  have on window in specialworkspace and only one active workspace or only one workspace that has any windows , after that swipe right and then left

**Comment by vaxerski** [comment]
swipe fixed in a72a39ebd555c24751a0c4853a495de5ba4bed0d

cannot repro the special fullscreen one, but possibly fixed with 5131a4acaf0f5319dc581ad0a26498b749ffd1e6
