### ISSUE TITLE
How to move a window up/down the stack like XMonad does...

### ISSUE THREAD

**Issue by yusi1** [hyprwm/Hyprland#6770]
### Description

Hi, I have been trying to replicate how XMonad moves windows up and down the stack by pressing either Mod4+Shift+J or Mod4+Shift+K, I tried using `swapnext` but that swaps the windows, what I want to do is have something like `movewindow` but one that just goes in two directions `up` and `down` the stack.

Basically something like `cyclenext` but for moving windows.

**Comment by zakk4223** [comment]
Isn't that xmonad shortcut just a swap anyways? I guess I"m not seeing how 'swapnext' isn't what you want since that will move the window down/up the stack. 

One hyprland 'quirk' is that fullscreen windows will screw up your stack order

**Comment by yusi1** [comment]
I have tried `swapnext` but it has strange behavior sometimes, I can't explain it that well, so here's a video of me using `swapnext` to move windows up/down the stack.


https://github.com/hyprwm/Hyprland/assets/82241382/4dcb34c4-e1f4-455c-a6b4-a1cd2b61f4d9

What I find weird is, why does using `swapnext` sometimes change the focus to another window? I don't want that, all I want is to move the window that I am focused on. Also the stack order gets messed up even without a fullscreen window.

**Comment by yusi1** [comment]
The video is not playing for me through Github, so I had to upload it somewhere else, here it is, sorry: https://streamable.com/dbzbp4

**Comment by yusi1** [comment]
So for example if I have a layout like:
```
[        ] [ Window 1 ]
[ Master ] [ Window 2 ]
[        ] [ Window 3 ]
```

Then I press SUPER+SHIFT+J while focused on the "Master" window, I want the "Master" window to now be here:

```
[          ] [  Master  ]
[ Window 1 ] [ Window 2 ]
[          ] [ Window 3 ]
```

And then eventually "Master" will be where "Window 3" used to be and will loop around to being on the left again.

**Comment by yusi1** [comment]
If the "Master" window is here:

```
[          ] [ Window 2 ]
[ Window 1 ] [  Master  ]
[          ] [ Window 3 ]
```

And I press SUPER+SHIFT+K this is what happens:

```
[        ] [ Window 2 ]
[ Master ] [ Window 1 ]
[        ] [ Window 3 ]
```

Why does it go to the left? I am confused.

**Comment by yusi1** [comment]
This is a video that shows this:

https://github.com/hyprwm/Hyprland/assets/82241382/5f201742-574a-4c7f-81e8-86ba4e41e731

**Comment by yusi1** [comment]
This is a video that shows this behaviour:

https://github.com/hyprwm/Hyprland/assets/82241382/dba0ff93-db8e-4664-88f2-6583895b16b4

**Comment by zakk4223** [comment]
Oh, the window order used by cyclenext/swapnext etc is completely independent of the order of the windows visually. The layouts don't rearrange the internal list when they move windows to master etc.

If you're only ever going to use the master layout I think it has specific dispatchers for cyclenext/prev and swapnext/swapprev. Try those.

Honestly this type of window management is one of the weakest parts of Hyprland for me. There's not a maintained window list (there is but it is used for rendering order, not movement/stacking ops) so you have to rely on the individual layouts to Do What You Want[tm].

**Comment by yusi1** [comment]
> Oh, the window order used by cyclenext/swapnext etc is completely independent of the order of the windows visually. The layouts don't rearrange the internal list when they move windows to master etc.
> 
> If you're only ever going to use the master layout I think it has specific dispatchers for cyclenext/prev and swapnext/swapprev. Try those.

Thank you, using the Master layout specific dispatchers have solved the issue for me.

> Honestly this type of window management is one of the weakest parts of Hyprland for me. There's not a maintained window list (there is but it is used for rendering order, not movement/stacking ops) so you have to rely on the individual layouts to Do What You Want[tm].

**Comment by yusi1** [comment]
I think this issue can be closed now.
