### ISSUE TITLE
Lid Switch not working

### ISSUE THREAD

**Issue by 2Belette** [hyprwm/Hyprland#6773]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 918d8340afd652b011b937d29d5eea0be08467f5 portbld (?).
Date: Tue Jun 25 12:06:02 UTC 2024
Tag: v0.41.2, commits: ?

flags: (if any)


System Information:
System name: FreeBSD
Node name: xps
Release: 14.1-RELEASE
Version: FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC


GPU information: 
vgapci0@pci0:0:2:0:	class=0x030000 rev=0x0c hdr=0x00 vendor=0x8086 device=0x46a6 subvendor=0x1028 subdevice=0x0af3
    vendor     = 'Intel Corporation'
    device     = 'Alder Lake-P GT2 [Iris Xe Graphics]'
    class      = display
    subclass   = VGA


os-release: NAME=FreeBSD
VERSION="14.1-RELEASE-p2"
VERSION_ID="14.1"
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 14.1-RELEASE-p2"
CPE_NAME="cpe:/o:freebsd:freebsd:14.1"
HOME_URL="https://FreeBSD.org/"
BUG_REPORT_URL="https://bugs.FreeBSD.org/"

```

</details>

### Description

Like shown in the wiki I am trying to switch my eDP-1 off when I close the lid and when I am connected to my external display, I have tried to do  :
```
bindl=,switch:Lid Switch,exec, /home/blt/.config/hypr/hyprlock.sh
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, enable,auto,1.0"
```
But no action, the laptop screen is still on when I close the lid.

```
hyprctl devices 
Switches:
	Switch Device at 30976e86b90:
		Control Method Lid Switch
```

Do I miss something from my system maybe ?

### How to reproduce

Closing the lid, nothing happen, I was expecting my internal monitor to switch off and all the windows to be moved to my external monitor like in sway.

**Comment by yusi1** [comment]
@2Belette try using "Control Method Lid Switch" instead of just "Lid Switch" in your binds.

**Comment by 2Belette** [comment]
@yusi1 Many thanks, I can't believe that ! I would never think about using Control Method Lid Switch instead of Lid Switch, I also tried the number... Many thanks it is working as expected
