### ISSUE TITLE
Hyprctl Exec Tag Window Rule

### ISSUE THREAD

**Issue by 404Wolf** [hyprwm/Hyprland#6781]
### Regression?

No

### System Info and Version

system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.18.4, channels(root): "home-manager-23.11.tar.gz, nixos-23.11", nixpkgs: /nix/store/4p0avw1s3vf27hspgqsrqs37gxk4i83i-source

Hyprland, built from branch at commit d7ea1b7785f31e9fd6477490309721a19a835592 

```sh
hyprctl dispatch exec \[tag +testt\] kitty
```

I am trying to launch windows with tags. When I use a `tag` rule as specified in the docs, the window spawns, but I get a successful response even though the window doesn't have a tag. 

### Description

Window does not spawn tagged when using `exec` dispatcher and `tag` rule.

### How to reproduce

Run `hyprctl dispatch exec [tag +sometag] someprogram` and then `hyprctl -j clients | jq '.[].tags'`.

### Crash reports, logs, images, videos

I'm happy to share any logs but there's no crash and I'm not sure where to look for things that would help solve this.

**Comment by vaxerski** [comment]
tag is dynamic. Same as #6593
