### ISSUE TITLE
Idle inhibit deactivates after waybar is closed, while previously activated

### ISSUE THREAD

**Issue by victorkamoto** [hyprwm/Hyprland#6782]
### Regression?

Yes

### System Info and Version

Hyprland, built from branch main at commit e4d09aa3a9de9a9e71c10bf4b6800585b3db9a4c  (sessionLock: focus lock on creation based on mouse position (6658)).
Date: Wed Jun 26 00:22:38 2024
Tag: v0.41.2-5-ge4d09aa3, commits: 4891

flags: (if any)

System Information:
System name: Linux
Node name: devpc
Release: 6.9.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
  csgo-vulkan-fix by Vaxry ver 1.2
  hyprexpo by Vaxry ver 1.0

======Config-Start======

Config File: /home/vic/.config/hypr/hyprland.conf: Read Succeeded

### Description

I like to have idle inhibit activated & sometimes, waybar closed. It worked.  Now when I `killall waybar`, hypridle activates hyrlock anyways.

### How to reproduce

Have idle inhibit enabled in waybar
Killall waybar
Doesn't inhibit

**Comment by vaxerski** [comment]
if waybar is dead how do you want it to idle inhibit?

I'd say this works as intended?

**Comment by victorkamoto** [comment]
Okay.
Is it possible to have the ability hide waybar?

**Comment by ehula** [comment]
I also kill waybar to hide it, and would like it to remember the current idle_inhibit state.

**Comment by vaxerski** [comment]
`pkill -SIGUSR1 waybar`

the previous behavior was invalid. This will not be reverted

**Comment by victorkamoto** [comment]
`killall hypridle` it is
