### ISSUE TITLE
Hyprland splash text incorrectly positioned

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#679]
The text is positioned properly on my monitor but is on the left on my laptop. Will upload photo.

**Comment by godalming123** [comment]
Laptop monitor:
![IMG20220918173438.jpg](https://user-images.githubusercontent.com/68993177/190918029-4136af30-7407-4edc-9780-9925ab544ff8.jpg)
Main monitor:
![IMG20220918173425.jpg](https://user-images.githubusercontent.com/68993177/190918066-28e453c2-e32e-45a9-88b0-b8f083bd9140.jpg)

**Comment by vaxerski** [comment]
what are the monitor settings? could you paste them here in a code block?

**Comment by godalming123** [comment]
```

monitor=HDMI-A-1,1920x1080,0x0,1
monitor=eDP-1,1366x768,300x1080,1
#monitor=eDP-1,disable
workspace=eDP-1,1,1
workspace=HDMI-A-1,2
```

**Comment by godalming123** [comment]
If it helps to know this happens when monitor is plugged in or unplugged.
