### ISSUE TITLE
weird drop down menus look

### ISSUE THREAD

**Issue by firashacker** [hyprwm/Hyprland#6793]
### Regression?

No

### System Info and Version

fresh ArchLinux install with only hyprland WM
kernel: Linux Arch 6.9.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 x86_64 GNU/Linux
gpu: amd rx6600

Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

### Description

first of all i'm sorry maybe its not hyprland related issue but i don't know whats the cause of this
i tried googling for any configuration options to fix it but didn't find any

summary:
i was using bspwm, then wanted to switch ( i copied [rewrite] my bar and theme and every thing for wayland and hyprland then i burged my old bspwm install and installed fresh arch with hyprland, some thing was off
drop down menus looking very big and weird not good at all , i don't think i can live with this :/

![Screenshot_2024-07-07-00-30-41_8671](https://github.com/hyprwm/Hyprland/assets/70780581/d7d04ac8-8c71-4abb-be41-43d811af2c69)

![Screenshot_2024-07-07-00-42-47_22807](https://github.com/hyprwm/Hyprland/assets/70780581/97ebb0c9-e1a9-46b2-bd42-2ffde8be57f6)

![Screenshot_2024-07-07-00-43-19_25350](https://github.com/hyprwm/Hyprland/assets/70780581/fdf9e93f-6454-4af6-b08e-3e88bccc0190)

### How to reproduce

idk

### Crash reports, logs, images, videos

idk

**Comment by fufexan** [comment]
Looks like Qt. Do GTK programs have the same issue?

**Comment by firashacker** [comment]
i dont think its QT that image viewer is "viewnior" its gtk and i don't know what themeing applies to tray menus but it was looking fine with the same theme under bspwm

**Comment by firashacker** [comment]
this is how it looks on bspwm

![Screenshot_2024-07-07-18-58-37_1920x1080](https://github.com/hyprwm/Hyprland/assets/70780581/331db6aa-cff7-48ff-8cab-db5be57337c5)

![Screenshot_2024-07-07-18-58-53_1920x1080](https://github.com/hyprwm/Hyprland/assets/70780581/bcfdba3f-657e-4d3d-b40d-d26c94087953)

![Screenshot_2024-07-07-18-59-11_1920x1080](https://github.com/hyprwm/Hyprland/assets/70780581/f80e9f25-1625-49ea-aa59-96befa2a0f21)

**Comment by firashacker** [comment]
look how its very small and looking good

**Comment by vaxerski** [comment]
ye but thats X. Does it work on sway? kwin?

**Comment by firashacker** [comment]
@vaxerski 
so i tryied sway with my sway configs and the issue was not there for the tray menus , then i found out thats configured in waybar.css style and i fixed that status bar thing

but the wired viewnior imageviewer menu is still there i don't know where that thing must be reported 

i will  close this issue :)
