### ISSUE TITLE
Clients history

### ISSUE THREAD

**Issue by matavach** [hyprwm/Hyprland#6796]
### Description

I occasionally have a window pop up that I want apply window rules to, but it moves quickly and I can't use "hyprctl clients" quickly enough.

I would to have the ability to search for previous clients to get window names / classes.

If this feature already exists / there's a way to do it already, then I apologize for my stupidity

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/a02a8c90-9719-4dc8-bdbb-e83ece62739e)
in `hyprctl clients`

**Comment by vaxerski** [comment]
unless you mean a window that is closed in which case `socat -v unix-connect:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock -`

**Comment by matavach** [comment]
Thank you, that works perfectly.
