### ISSUE TITLE
movetoworkspacesilent,special

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#681]
This is not working properly:
It moves the selected window to the special workspace, but the special workspace is "focused" without being visible.
That introduces lots of crazy behavior.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/191042813-4660e9d0-298a-4e4a-a0e7-0e5a1f003835.png)

Why not read the wiki?

**Comment by Dickby** [comment]
My bad! 
But why not disable a function that doesn't work?

**Comment by vaxerski** [comment]
:shrug:

**Comment by Dickby** [comment]
movetoworskpace,special is weird to, it slides the windows of the previously focused workspace away.
But they should be visible behind the special workspace.
If i hide the special ws, those windows are still invisible, to make them visible again, i have to switch to another workspace and then back.

**Comment by vaxerski** [comment]
shit u right

**Comment by vaxerski** [comment]
fixed in 696253b3489fb57904b500b8265dfaf19ada56d6

silent works now, but it works the same as without silent.
