### ISSUE TITLE
Hyprland doesn't work anymore - /usr/lib/libhyprutils.so.0: file too short

### ISSUE THREAD

**Issue by Dreadfuln** [hyprwm/Hyprland#6817]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

When I tried to access Hyprland through ly (I installed that before I knew you should with hyprland, but it usually worked just fine) it gives me "logged out". 
I also tried to install sddm, with which the screen goes black for a couple of seconds and then I go back to the sddm login screen. 
I also tried to just execute Hyprland without any greeter, which gives me the error:
"hyprland: error while loading shared libraries: /usr/lib/libhyprutils.so.0: file too short"
When trying hyprctl systeminfo I get this error:
"hyprctl: error while loading shared libraries: /usr/lib/libhyprutils.so.0: file too short".
Some additional info that might be helpful: 
I did try to manually set my graphics card as the integrated card from my laptop because I read that here: https://www.reddit.com/r/hyprland/comments/183jzb6/insta_logs_out_after_login/ which didn't change anything.
I also tried to reinstall hyprland and used -Qk hyprland (403 total files, 0 missing files), neither one got me anywhere.
I don't think I did anything noteworthy before the issue started .I just copied some insignificant changes I made at my pc over to my laptop and my pc still works.

### How to reproduce

Maybe you can reproduce this by messing with libhyprutils.so.0 but I wouldn't know.

### Crash reports, logs, images, videos

There is no hypr directory in $XDG_RUNTIME_DIR.
There is also no hyprland directory in my home directory. There is a .hyprland directory, but it only has error files that are from long ago.

**Comment by vaxerski** [comment]
sounds like your binary corrupted. Reinstall hyprutils.

**Comment by Dreadfuln** [comment]
That fixed it. Thank you!
