### ISSUE TITLE
yay -S hyprland-git install successed ,but  not have hyprland command.

### ISSUE THREAD

**Issue by matianhe3** [hyprwm/Hyprland#6824]
### Regression?

Yes

### System Info and Version

Arch linux

### Description

yay -S hyprland-git install successed ,but  not have hyprland command.

### How to reproduce

yay -S hyprland-git

**Comment by MalcolmReed-ent** [comment]
Have you tried 'Hyprland' with a capital H

**Comment by romanstingler** [comment]
Yeah @zjeffer and @vaxerski are listed as maintainers, no clue why the hyprland link or executable is not created in the -git package

**Comment by zjeffer** [comment]
What's the output of ` yay - Ql hyprland-git`?

**Comment by matianhe3** [comment]
> Have you tried 'Hyprland' with a capital H

yes thanks
