### ISSUE TITLE
KDE polkit do not work for some applications. 

### ISSUE THREAD

**Issue by musicfunfan** [hyprwm/Hyprland#6833]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.9.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000

GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] [1002:67ef] (rev e5) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/musicfan/.config/hypr/hyprland.conf: Read Succeeded
#Monitor set up.
monitor = DP-1,3840x2160@60,0x0,2
monitor	= DVI-D-1,1920x1080@60,1920x0,1

#Commands to execute at start up.
exec-once = waybar &
exec-once = corectrl -m main --minimize-systray &
exec-once = xrdb -load /home/musicfan/.Xresources &
exec-once = exec exec openrgb -p cyan.orp --startminimized &
exec-once = openrgb -p cyan.orp --startminimized &
exec-once = nm-applet &
exec-once = playerctld daemon &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = wlsunset &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = $HOME/.config/scripts/SelectWallpeper.sh &
exec-once = radeontop -d gpu.txt -l 0 > /dev/null &
exec-once = blueman-applet &
exec-once = pactl load-module module-native-protocol-tcp auth-anonymous=true &
exec-once = hypridle &

#Some default env vars.
env = XCURSOR_SIZE,24
env = GDK_SCALE,2
env = QT_QPA_PLATFORMTHEME,qt5ct
env = GTK_THEME,Nordic

#Window Rules.

#Floating
windowrulev2 = float,class:(lxqt-policykit-agent)
windowrulev2 = float,size 20%,noborder,class:(mpv)

#Workspace 1
windowrulev2 = workspace 1 ,class:(discord)
windowrulev2 = workspace 1 ,class:(Skype)
windowrulev2 = workspace 1 ,class:(Element)
windowrulev2 = workspace 1 ,class:(thunderbird)
windowrulev2 = workspace 1 ,class:(FMAP)

#Workspace 2
windowrulev2 = workspace 2 ,class:(FM)

#Workspace 3
windowrulev2 = workspace 3 ,class:(FS)

#Worksapce 4
windowrulev2 = workspace 4 ,class:(FN)
windowrulev2 = size 25% ,class:(pcmanfm-qt)

#Workspace 5
windowrulev2 = workspace 5 ,class:(kitty)

#Workspace 6
windowrulev2 = workspace 6 ,class:(virt-manager)

#Workspace 7
windowrulev2 = workspace 7 ,class:(Emacs)

#Workspace 8
windowrulev2 = workspace 8 ,class:(com.obsproject.Studio)

#Workspace 9
windowrulev2 = workspace 9 ,class:(FP)

#Workspace 10
windowrulev2 = workspace 10 ,class:(steam)

#Workspace 11
windowrulev2 = workspace 11 ,class:(org.kde.kdenlive)
windowrulev2 = workspace 11 ,class:(blender)
windowrulev2 = workspace 11 ,class:(fr.handbrake.ghb)

#Workspace 12
windowrulev2 = workspace 12 ,class:(libreoffice-writer)
windowrulev2 = workspace 12 ,class:(libreoffice-calc)
windowrulev2 = workspace 12 ,class:(libreoffice-impress)
windowrulev2 = workspace 12 ,class:(libreoffice-draw)
windowrulev2 = workspace 12 ,class:(libreoffice-math)
windowrulev2 = workspace 12 ,class:(libreoffice-base)

#Workspace special
windowrulev2 = workspace special ,class:(ch.proton.bridge-gui)
windowrulev2 = workspace special ,class:(org.pulseaudio.pavucontrol)
windowrulev2 = workspace special ,class:(org.rncbc.qpwgraph)
windowrulev2 = workspace special ,class:(blueman-manager)

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, w, exec,$HOME/.config/scripts/SelectWallpeper.sh
bind = $mainMod, P, exec,$HOME/.config/scripts/power.sh
bind = $mainMod, U, movecurrentworkspacetomonitor, DVI-D-1
bind = $mainMod, I, movecurrentworkspacetomonitor, DP-1
bind = $mainMod, Y, swapactiveworkspaces,current +1
bind = $mainMod, F, workspaceopt, allfloat
bind = $mainMod, Return, exec, kitty
bind = $mainMod, M, exit,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, q, togglesplit, # dwindle
bind = $mainMod_SHIFT, s,movetoworkspace,special
bind = $mainMod, s,togglespecialworkspace,
bind = $mainMod, A, exec,passrofi

bind = ALT_L, SPACE, exec,rofi -show drun 
bind = ALT_L, W, exec, $HOME/.config/scripts/search.sh 
bind = ALT_L, E, exec, $HOME/.config/scripts/sites.sh
bind = ALT_L, 5, fullscreen
bind = ALT_L, T, togglefloating,
bind = ALT_L, f4, killactive,
bind = ALT_L, j, exec ,rofi -show emoji -theme $HOME/.config/rofi/arthur.rasi
bind = CTRL_L_SHIFT, W,exec, $HOME/.config/scripts/media.sh
bind = ,Print,exec, $HOME/.config/scripts/screenshot.sh
bind = ALT_L, q ,exec, $HOME/.config/scripts/runScript.sh

#Media buttons
bind =, XF86AudioMute, exec, $HOME/.config/scripts/volumeMeter.sh -m
binde =, XF86AudioLowerVolume, exec, $HOME/.config/scripts/volumeMeter.sh -d
binde =, XF86AudioRaiseVolume, exec, $HOME/.config/scripts/volumeMeter.sh -u
bind =, XF86AudioPlay, exec, $HOME/.config/scripts/mediaNotification.sh -p
bind =, XF86AudioPause, exec, $HOME/.cofnig/scripts/mediaNotification.sh -p
bind =, XF86AudioNext, exec, $HOME/.config/scripts/mediaNotification.sh -n
bind =, XF86AudioPrev, exec, $HOME/.config/scripts/mediaNotification.sh -b 
bind =, XF86AudioStop, exec, $HOME/.config/scripts/mediaNotification.sh -t 

#Move focus with mainMod + arrow keys
bind = $mainMod, L, movefocus, l
bind = $mainMod, H, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = CONTROL_L, F1, workspace, 1
bind = CONTROL_L, F2, workspace, 2
bind = CONTROL_L, F3, workspace, 3
bind = CONTROL_L, F4, workspace, 4
bind = CONTROL_L, F5, workspace, 5
bind = CONTROL_L, F6, workspace, 6
bind = CONTROL_L, F7, workspace, 7
bind = CONTROL_L, F8, workspace, 8
bind = CONTROL_L,  F9, workspace, 9
bind = CONTROL_L, F10, workspace, 10
bind = CONTROL_L, F11, workspace, 11
bind = CONTROL_L, F12, workspace, 12

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = CONTROL_L SHIFT, F1, movetoworkspace, 1
bind = CONTROL_L SHIFT, F2, movetoworkspace, 2
bind = CONTROL_L SHIFT, F3, movetoworkspace, 3
bind = CONTROL_L SHIFT, F4, movetoworkspace, 4
bind = CONTROL_L SHIFT, F5, movetoworkspace, 5
bind = CONTROL_L SHIFT, F6, movetoworkspace, 6
bind = CONTROL_L SHIFT, F7, movetoworkspace, 7
bind = CONTROL_L SHIFT, F8, movetoworkspace, 8
bind = CONTROL_L SHIFT, F9, movetoworkspace, 9
bind = CONTROL_L SHIFT, F10, movetoworkspace, 10
bind = CONTROL_L SHIFT, F11, movetoworkspace, 11
bind = CONTROL_L SHIFT, F12, movetoworkspace, 12

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#Lock the screen
bind = $alt, l, exec, hyprlock 

bind = $mainMod, f, exec, $HOME/.config/scripts/firefoxProfile.sh

# Submaps
bind = ALT,R,submap,resize

submap = resize

binde = ,right,resizeactive,10 0
binde = ,left,resizeactive,-10 0
binde = ,up,resizeactive,0 -10
binde = ,down,resizeactive,0 10
bind = ,escape,submap,reset
 
submap=reset

#Extra settings.
misc {
disable_hyprland_logo = true
}

#keyboard layout.
input {
    kb_layout = us,gr
    kb_options = grp:alt_shift_toggle
}

#XWayland scale.
xwayland {
  force_zero_scaling = true
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 0
    gaps_out = 0
    border_size = 4
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(59595900)
    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 0
    
    blur {
        enabled = false 
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

======Config-End========

```sh
<Paste the output of the command here>
```

</details>

### Description

So,applications work with KDE polkit. Some other do not. But they did before. I do not know if this is a hyprland issue if this is Wayland issue . After an update. I do not know if i update Hyprland (I just run update with out reading this is bad i know) Some application say that there is not polkit running but some other works fine. For example corectrl work fine. proton-bright do not work. And some other also do not work. 

This is a Hyprland problem or something else ?

### How to reproduce

If this is a hyprproblem you can install a polkit ( i use kde one) run it. And check if other application can detect it. 

### Crash reports, logs, images, videos

No crash for me.

**Comment by musicfunfan** [comment]
I try an older version of Hyprland. ``commit 9e781040d9067c2711ec2e9f5b47b76ef70762b3  (props: bump version to 0.41.1).`` problem still there. So no Regression.

**Comment by musicfunfan** [comment]
Also lxpolkit I uses to use back on i3wm. Does the same thing. :cry:

**Comment by vaxerski** [comment]
Honestly I don't think its a hyprland issue.

**Comment by musicfunfan** [comment]
I mean is very weird some app use the polkit some other do not. I do not know. :cry: 
I will install something else to check if other DE/Compositors have problems.

**Comment by musicfunfan** [comment]
I did some experiments. Well the problem is that the ``pinentry `` (GUI) do not work. I was thinking that this is was a polkit problem. But its not. The problem is with all application that needs to open a secret key. So i use pass. And i use passrofi. For easy pass gui. And Proton Bright (for Proton Mail) needs this to work in order to get access to the keys. Also passrofi do not work. 

So the whole problem is not the kde polkit is that pinentry do not work as a gui.

If i run this. 
```bash
❯ pinentry 
No Gcr System Prompter available, falling back to curses
OK Pleased to meet you
```
So... I did a duckduckgo search. 

And i find [this](https://github.com/hyprwm/Hyprland/issues/6250) report. 

Is this related. Or this is not a Hyprland problem? And i mess something up with an update or something.

**Comment by musicfunfan** [comment]
As i understand this. I have problem with all the GUI implementations of pinentry program. 

If i run ``pinentry-gnome3`` I have the same output as the above. Witch mean that by default it uses gnome3 version. 
And if i run ``pinentry-qt`` I get this:

```bash
pinentry-qt: error while loading shared libraries: libKF6GuiAddons.so.6: cannot open shared object file: No such file or directory
```
So... I think i know have found the problem. 

I also find how the system guess what implementation i want to use, via this script. ``/usr/bin/pinentry``
```bash
#!/bin/bash

# Run user-defined and site-defined pre-exec hooks.
[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}"/pinentry/preexec ]] && \
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/pinentry/preexec
[[ -r /etc/pinentry/preexec ]] && . /etc/pinentry/preexec

# Guess preferred backend based on environment.
backends=(curses tty)
if [[ -n "$DISPLAY" || -n "$WAYLAND_DISPLAY" ]]; then
	case "$XDG_CURRENT_DESKTOP" in
	KDE|LXQT|LXQt)
		backends=(qt qt5 gnome3 gtk curses tty)
		;;
	*)
		backends=(gnome3 gtk qt qt5 curses tty)
		;;
	esac
fi

for backend in "${backends[@]}"
do
	lddout=$(ldd "/usr/bin/pinentry-$backend" 2>/dev/null) || continue
	[[ "$lddout" == *'not found'* ]] && continue
	exec "/usr/bin/pinentry-$backend" "$@"
done

exit 1
```
So for me the ``"$XDG_CURRENT_DESKTOP"`` will be ``Hyprland`` so ... It will go and try gnome3 first but this does not matter because nothing except ``curses`` works. 

So do i need to report this to archlinux or this is a Hyprland problem ? :thinking:

**Comment by musicfunfan** [comment]
I fixed. I add the pinentry-gtk as my pinentry program on my ``$HOME/.gnupg/gpg-agent.conf`` file. And its working. The only pinentry program that it work on Hyprland is the gtk one. For some reason. 

If anyone wants to check it out the file is [this](https://gitlab.com/musicfunfan/main_configs_files/-/blob/main/gnugp/gpg-agent.conf?ref_type=heads). 
Its just one line. For now.
