### ISSUE TITLE
workspace_swipe_invert 'incorrect' behaviour

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#6836]
### Description

Gestures:workspace_swipe_invert inverts both the touchpad's workspace swipe direction and the touchscreen's egde drag one.
It's not possible to control these two settings separately, so I believe introducing a 'workspace_swipe_touch_invert' would be worthwhile.

**Comment by Hubro** [comment]
Personally I think `workspace_swipe_invert` simply shouldn't affect touch screens, as it don't think a single person will ever intentionally use it.

**Comment by Estebiu** [comment]
I believe so too; but in my case the gesture orientation was inverted and I don't know if it's that way for everyone, so adding maybe a toggle would be helpful.
