### ISSUE TITLE
[aquamarine] Startup freeze on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [hyprwm/Hyprland#6842]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
$ hyprctl systeminfo -c
Hyprland, built from branch main at commit 8b37e81374928856d8fd859b95a62c8bf4211901 portbld (?).
Date: Fri  9 Aug 2024 21:58:02 UTC
Tag: v0.42.0-4-g8b37e813 (aquamarine v0.3.1), commits: ?

flags: (if any)


System Information:
System name: FreeBSD
Node name: foo.bar
Release: 15.0-CURRENT
Version: FreeBSD 15.0-CURRENT #0 main-n271236-b3bbc6cc79a3: Wed Jul 17 22:47:30 UTC 2024 test@foo.bar:/usr/obj/usr/src/amd64.amd64/sys/MYKERNEL


GPU information: 
vgapci1@pci0:0:2:0:	class=0x030000 rev=0x06 hdr=0x00 vendor=0x8086 device=0x1912 subvendor=0x1462 subdevice=0x7968
    vendor     = 'Intel Corporation'
    device     = 'HD Graphics 530'
    class      = display
    subclass   = VGA


os-release: NAME=FreeBSD
VERSION="15.0-CURRENT"
VERSION_ID="15.0"
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 15.0-CURRENT"
CPE_NAME="cpe:/o:freebsd:freebsd:15.0"
HOME_URL="https://FreeBSD.org/"
BUG_REPORT_URL="https://bugs.FreeBSD.org/"


plugins:

======Config-Start======


Config File: /tmp/hyprland.conf: Read Succeeded
debug {
      enable_stdout_logs = true
      disable_logs = false
}

exec-once = foot
exec-once = vkcube-xcb

======Config-End========

```

</details>

### Description

Split from https://github.com/hyprwm/Hyprland/pull/6608. FreeBSD regressions cannot block merges.

Launching Hyprland manages to show default wallpaper but no windows appear. Neither mouse nor keyboard (including VT switch) work. Exiting Hyprland requires killing by [timeout(1)](https://man.freebsd.org/timeout/1) or from another machine (e.g., serial console, ssh).

Affects DRM (Hyprland on VT console) but **not** Wayland (aquamarine-Hyprland on wlroots-Hyprland 0.41.2) session. `AQ_NO_ATOMIC=1` doesn't help. Starting from a different VT doesn't help. Starting without Sway in background doesn't help.

### How to reproduce

Start Hyprland from VT console such as `/dev/ttyv0`.

### Crash reports, logs, images, videos

[Runtime log and stacktrace](https://github.com/user-attachments/files/16567209/hyprland-aquamarine-drm-session.log)

**Comment by vaxerski** [comment]
well it looks like a hang in `udev_monitor_receive_device` if I am reading it correctly but I have little clue as to what could be causing this.

libudev is likely compiled in release and thus some of the stack is missing but it looke like somewhere here
![image](https://github.com/user-attachments/assets/52101033-e788-4202-ae51-4bd40244bed0)

**Comment by jbeich** [comment]
- FreeBSD uses [libudev-devd](https://github.com/wulf7/libudev-devd/blob/v0.5.0/udev-monitor.c#L83) instead of systemd
- libudev-zero was built with debug symbols, so the stacktrace in the log shows line numbers
- `udev_monitor_receive_device` usage in [aquamarine](https://github.com/hyprwm/aquamarine/blob/v0.3.1/src/backend/Session.cpp#L287-L354) is similar to [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/0.18.0/backend/session/session.c#L169-226) (where it works fine)
- Hyprland shows wallpaper, so monitor stuff is likely a false positive

Could this be related to DMABUF instead? For example, FreeBSD currently [lacks explicit sync](https://github.com/freebsd/drm-kmod/issues/278).

**Comment by vaxerski** [comment]
yeah but your stacktrace shows it being stuck in `udev_monitor_receive_device` in a read syscall. Unless the stacktrace is wrong?

I'd assume it's stuck somewhere because the log is clearly empty in your case right after the event loop starts, unless you truncated the log.

> Could this be related to DMABUF instead? For example, FreeBSD currently https://github.com/freebsd/drm-kmod/issues/278.

Explicit sync is disabled with `render:explicit_sync = no` which should not require any further action.

can you post a trace log? `AQ_TRACE=1 HYPRLAND_TRACE=1 Hyprland` and make sure `debug:disable_logs = false` before you launch

**Comment by vaxerski** [comment]
My guess is that there is nothing pollable and we dispatch outstanding once, which in sysd doesn't block but in BSD might. Try this hl patch:
[patch.txt](https://github.com/user-attachments/files/16567069/patch.txt)

unsure if this is correct, but it might work.

**Comment by jbeich** [comment]
I've updated OP with the new log. After applying your patch Hyprland seems to work fine.

**Comment by vaxerski** [comment]
I assume the log is from patched, as it seems to run normally

**Comment by vaxerski** [comment]
I'll apply the patch, if anything happens after it and people report issues I'll just revert it. Doesn't hurt to try

**Comment by vaxerski** [comment]
FWIW, according to https://www.man7.org/linux/man-pages/man3/udev_monitor_enable_receiving.3.html `udev_monitor_receive_device` should return null if anything goes wrong (which I assume includes no event) so unless that manpage is sysd only that sounds like a bug in udev?

**Comment by jbeich** [comment]
> unless that manpage is sysd only that sounds like a bug in udev?

Need a smaller test case to reproduce without Hyprland. Other Wayland compositors (wlroots, smithay, kwin) didn't bump into this issue. Even Xorg uses `udev_monitor_receive_device` on FreeBSD: modesetting DDX and xf86-video-intel.

I'm not familar with libudev API myself.

**Comment by vaxerski** [comment]
at any rate, if the freeze is gone now on -git I'd consider this fixed

**Comment by jbeich** [comment]
Agree. I've [applied](https://github.com/freebsd/freebsd-ports/commit/8a07c7eca273) it downstream.
