### ISSUE TITLE
xwayland: jetbrains idea button misalignment and wrong scaling when scaling > 1

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6849]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e728e56cbc6af0a9be1276b2cf8e019a894016e7 dirty (meson: install wayland.hpp header).
Date: Fri Jul 12 04:58:23 2024
Tag: v0.41.2-31-ge728e56c, commits: 4917

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.9.8-1-cachyos-echo-lto
Version: #1 SMP PREEMPT_DYNAMIC Sat, 06 Jul 2024 12:00:36 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

jetbrains idea button misalignment and wrong scaling when scaling > 1. Revert this commit b03f41efec14273cf25c42d4cef326acc36cb319 works fine.

### How to reproduce

1. `paru -Sy intellij-idea-ultimate-edition`
2. See below

https://github.com/user-attachments/assets/bac37ca0-3056-4948-bb15-6cecc021f05b

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

not idea about the regression, but using wayland native version is probably a good idea

**Comment by hdm9527** [comment]
> JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/) Please try the versions in their Early Acess Program and see if they fix this issue. Relevant Download links: https://www.jetbrains.com/idea/nextversion/ https://www.jetbrains.com/pycharm/nextversion/ https://www.jetbrains.com/go/nextversion/
> 
> not idea about the regression, but using wayland native version is probably a good idea

The wayland mode doesn't have this problem, but it doesn't support input methods.  [JBR-5672](https://youtrack.jetbrains.com/issue/JBR-5672)
