### ISSUE TITLE
Window doesn't fade-in again

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#685]
I found another way to get a Window that is invisible.
Steps to reproduce:

-have a window on the hidden special workspace 
-have at least 2 windows open on the active workspace.
-fullscreen one of the 2 windows
-slide in that special workspace and move that window from the special  ws to the fullscreen workspace.

The last action cancels the fullscreen state of the workspace, and all windows but the fullscreen window and the window
that came from the special workspace are invisible.

**Comment by Dickby** [comment]
It's the same if you have a multi window fullscreen workspace, and you move another window to that workspace.

**Comment by Dickby** [comment]
And if you have a multi window fullscreen workspace and move away the front window, silently and unsilently

**Comment by vaxerski** [comment]
fixed in 5b6c8d5b0f9a807eaf61d7286d41a75f5e6e61e9

**Comment by Dickby** [comment]
Thanks!
