### ISSUE TITLE
Window get stuck while moving it with a mouse

### ISSUE THREAD

**Issue by Heisfer** [hyprwm/Hyprland#686]
When moving a window around with a mouse the window gets stuck

I got this bug while releasing super key before mouse button.
Window stays floating (if it wasn't before)

To get it fix I have to press super key again

OS: Arch Linux
XWayland
Version: Latest master branch

https://user-images.githubusercontent.com/28564678/191191634-b9547b47-a671-45dc-a3ce-4673ffa8b299.mp4

**Comment by vaxerski** [comment]
fixed in b82621c4ecd2697ac397ca0e47d5d75bf028632a
