### ISSUE TITLE
First instance of KDE portal file dialog always opens on workspace 1

### ISSUE THREAD

**Issue by matejdro** [hyprwm/Hyprland#6863]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: KOMP
Release: 6.9.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000


GPU information: 
28:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6950 XT] [1002:73a5] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hypreasymotion by Zakk ver 1.0
```

Config is default with very minor changes (wofi -> rofi etc.), plus the following lines appended to allow for log extraction and portal functioning:

```
debug {
    disable_logs = false
}

exec-once=systemctl --user import-environment XDG_SESSION_TYPE XDG_CURRENT_DESKTOP
exec-once=dbus-update-activation-environment --systemd --all
```

</details>

### Description

It appears that the KDE portal file dialog will always open on Workspace 1 when opened for the first time, regardless of on what workspace the triggering application was. Subsequent activations of the dialog open on the right workspace.

### How to reproduce

1. Setup KDE desktop portal (https://github.com/KDE/xdg-desktop-portal-kde) 
2. (Re)start Hyprland
3. Switch to some other workspace than 1
4. Trigger "Open" / "Save As" from some application (for example, I tested [from Firefox](https://wiki.archlinux.org/title/firefox#XDG_Desktop_Portal_integration))
5. Note that file dialog will open on the workspace 1 instead of the workspace you triggered it from
6. Close file dialog
7. Trigger "Open" / "Save As" 
8. Now, open dialog opens on the right workspace

### Crash reports, logs, images, videos

Logs of me opening "save as" KDE portal three times from Firefox. First time, it shows up on Workspace 1, but on the next two times, it opens on the right workspace.

[hyprland.log](https://github.com/user-attachments/files/16201956/hyprland.log)

**Comment by matejdro** [comment]
Possibly related to the #6495?

**Comment by vaxerski** [comment]
disable initial workspacce tracking in hl config

**Comment by matejdro** [comment]
Thank you!

This is a workaround that I came up with to keep that feature but fix startup window issues like this one:

```
misc {
    initial_workspace_tracking = false
}
exec-once = sleep 2;hyprctl keyword misc:initial_workspace_tracking true
```
