### ISSUE TITLE
Yet another case of invisible windows after fading.

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#687]
Multi-window-fullscreen-workspace + move a window from another workspace to that fullscreen workspace.

**Comment by Dickby** [comment]
Fighting for the price of the most annoying issue opener.

**Comment by vaxerski** [comment]
prize*

**Comment by Dickby** [comment]
Right! Prize.
In german it translates to the same word.

**Comment by vaxerski** [comment]
fixed in cde624ec6a98b751e67967cbaffd68b1215e8531
