### ISSUE TITLE
Screen lockers spawned by hypridle often hang/coredump

### ISSUE THREAD

**Issue by Agent00Ming** [hyprwm/Hyprland#6883]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit bc6b0880dda2607a80f000c134f573c970452a0f  (window: override noMaximize if new window takes over fullscreen (6812) (6870)).
Date: Sat Jul 13 14:44:32 2024
Tag: v0.41.2-39-gbc6b0880, commits: 4925

flags: (if any)


System Information:
System name: Linux
Node name: wrangler
Release: 6.9.9-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:19 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q] [10de:24dd] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  555.58.02  Tue Jun 25 01:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Running hyprlock or swaylock from a terminal repeatedly works as expected. However, having said screenlocker be spawned by hypridle timeout/lock command will eventually have one hang on user input and essentially brick the session. Regressed by 7486576fa7a3d394254cb07734679df4b2469071, could be a hypridle bug.

### How to reproduce

<details><summary>1. Create a hypridle config file with fast timeout and lock screen</summary>

```
general {
    lock_cmd = hyprlock && loginctl unlock-session
    unlock_cmd = # hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener{ 
    timeout = 5
    on-timeout = loginctl lock-session 
}
```

</details>

2. Run hypridle with said config file
3. Let the timeout happen
4. Attempt to unlock the screen locker
5. Repeat the last two steps 2-3 times
6. Observe a hang or a screen locker crash

### Crash reports, logs, images, videos

[hyprlock.log.gz](https://github.com/user-attachments/files/16229445/hyprlock.log.gz) (1G uncompressed `hyprlock -v` log :trollface:)
<details>

![image](https://github.com/user-attachments/assets/74f3a7fa-d0e7-496d-b54e-58c4c53eb258)
![image](https://github.com/user-attachments/assets/ceb13e99-fceb-4542-9459-ddbddb598305)
~45000 lines of nothing (when viewed in kate) and then ~22 million lines of `[TRACE] [core] got poll event` and a few others. Running the file through `uniq` shows a bunch of jumbled lines

**Comment by vaxerski** [comment]
is that any lock or just hyprlock? hyprlock was fixed iirc

**Comment by Agent00Ming** [comment]
I repro'd it with latest hyprlock and swaylock when run from hypridle and only when run from hypridle... doesn't happen when I run either in a terminal.

**Comment by Agent00Ming** [comment]
original repro conditions no longer cause the bug to happen
