### ISSUE TITLE
Guess what, i know how to make a window invisible!

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#690]
1. have 3 windows on a workspace,
2. group 2 of them together,
3. have the group focused and movewindow (Quiz: where is the group now?)
4. switch focus to the other window (that is the group now!)
5. changegroupactive
6. movewindow (that window will move, but after that it's not movable anymore)
7. movtoworkspacesilent (to another workspace)

I hope i got this right!

**Comment by vaxerski** [comment]
waht

video pls

**Comment by Dickby** [comment]
What do you use for screencasts?

**Comment by vaxerski** [comment]
screen recording? OBS

**Comment by Dickby** [comment]
Some problems here, i'm working on it

**Comment by Dickby** [comment]
wf-recorder is much easier to get into.
If you'll come across another idiot like me, it might help.

**Comment by vaxerski** [comment]
re-check this on latest

**Comment by Dickby** [comment]
Nice Thanks!
