### ISSUE TITLE
Group indicator unstable

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#692]
The small bar that indicates which window of a group is shown behaves weird in combination with focus changes triggered by both the mouse and movefocus.
For some groups the indicator changes if the focus is moved to a non group window.
For some other groups the indicator completely disappears for one of the grouped windows
(whenever that window is on top the indicator isn't visible).
I think the conditions in that the group is created are somehow controlling which of the two 
buggy behaviours show up.

**Comment by vaxerski** [comment]
verify 7a9423c782c1d3be437283410b091196bfbab8d8

**Comment by Dickby** [comment]
Well done!
