### ISSUE TITLE
follow_mouse = 2 still moves focus from and to floating windows

### ISSUE THREAD

**Issue by krims0n32** [hyprwm/Hyprland#6927]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: nyx
Release: 6.9.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
19:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

When using `follow_mouse = 2` I'd expect this apply to floating windows as well. Currently when moving the mouse cursor away from a floating window, the underlying window gets focus automatically. This causes issues with accidently closing the wrong window for example.

### How to reproduce

Set `follow_mouse = 2`. Open two terminals side by side (tiled). Open a floating window. Floating window gets focus. Move mouse away from floating window and see the underlying window gets focus without the need to click on that window.

Edit: `follow_mouse = 0` shows the same behaviour.

**Comment by MightyPlaza** [comment]
`float_switch_override_focus`

**Comment by krims0n32** [comment]
Crap I searched for all focus related vars but missed that one apparently. Thanks for the quick reply <3.
