### ISSUE TITLE
Disable togglegroup in fullscreen

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#693]
Given there are multiple windows on one workspace and one of them is shown fullscreen.
It's quite confusing to use togglegroup from that fullscreen state because it's not visible at that moment which windows are children of the visible window.
The only way to know would be to memorize it, and i don't think that would be very common.
A group that contains all windows on a workspace looks the same as a fullscreen window, but the behaviour of togglegroup is completely different and it's nessesary to be able to toggle that group. 
I think a reasonable solution would be to disable togglegroup if a fullscreen window is shown, and maybe even disable fullscreen if a group spans the full screen anyways.

**Comment by vaxerski** [comment]
done in 7f3750bd757b4fc5d62a8b7a684578ce5c3d95fb. Disabled *only* enabling a group, as dissolving a group when it's fullscreen'd is completely logical and expected.
