### ISSUE TITLE
Mouse window resizing/moving stopped working

### ISSUE THREAD

**Issue by brodi1** [hyprwm/Hyprland#694]
previous working version: `hyprland-git-r1666.abb6db9 (AUR)`
version: `hyprland-git-r1681.2dd1661 (AUR)`
config: `unchanged`

## Steps to reproduce:
`Install Hyprland version hyprland-git-r1681.2dd1661`
`Open a window and press the main_mod key and right click to resize or left click to move the window `

**Comment by Dickby** [comment]
https://github.com/hyprwm/Hyprland/issues/688

**Comment by brodi1** [comment]
oh ok thanks @Dickby
