### ISSUE TITLE
Anydesk - window closes on entering the first digit of remote machine

### ISSUE THREAD

**Issue by tarpan** [hyprwm/Hyprland#6944]
### Regression?

Yes

### System Info and Version

Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)

System Information:
System name: Linux
Node name: rodzice
Release: 6.6.40-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Mon, 15 Jul 2024 09:23:08 +0000

GPU information:
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15dd] (rev c6) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

### Description

When I open Anydesk (both the AUR and flatpak versions) and want to enter the ID of a remote machine, the window closes after I enter the first digit of the ID. The problem does not happen on other window managers (including those on Wayland).

### How to reproduce

Open Anydesk, click the "Remote Device" input field. Another window will open - try to enter an ID (digits).

**Comment by vaxerski** [comment]
is anydesk running in xwayland?

**Comment by tarpan** [comment]
Is that the command "GDK_BACKEND=x11 anydesk"?
It behaves the same when I run it.

**Comment by vaxerski** [comment]
`hyprctl clients`, find anydesk and see if it's `xwayland: 1` or `0`

**Comment by tarpan** [comment]
xwayland: 1

**Comment by vaxerski** [comment]
oke doke, likely similar to #6698 then

**Comment by vaxerski** [comment]
can you see if the fix to 6698 fixed this too?

**Comment by tarpan** [comment]
I'm not sure which fix you have in mind, the "stayfocused" windowrule? It doesn't work on my machine.

**Comment by vaxerski** [comment]
the commit that closed the issue.

**Comment by tarpan** [comment]
How can I apply the commit?

**Comment by vaxerski** [comment]
just build from git

**Comment by tarpan** [comment]
I'm on Arch, so I just installed hyprland-git from the AUR, but I'm afraid the problem still exists.

**Comment by vaxerski** [comment]
oke doke, marking for 0.42 then

**Comment by vaxerski** [comment]
![image](https://github.com/user-attachments/assets/0b2a67bb-f594-49b6-b418-687fa0c63846)
I can't repro this, although the window does close when I move my mouse off of the input window

**Comment by tarpan** [comment]
I have both effects on my machine. They might be related.

**Comment by tarpan** [comment]
You mean Anydesk's default config? I haven't changed anything, I run it as it is after installation.

**Comment by vaxerski** [comment]
hl

**Comment by tarpan** [comment]
The window does not close until I move the mouse, but I cannot see the digits I enter.

**Comment by vaxerski** [comment]
okay, thats odd. Can you find which option is responsible for the closing? Also, what if you have your mouse where the window is, does moving it inside it also close it?

**Comment by tarpan** [comment]
I think the closing happens in the master layout (which is my default), it does not in dwindle. In master the mouse pointer remains in the parent window, so when I move it, the input window closes. In dwindle, I can move my mouse within the input window, but it closes when I cross the window border.

**Comment by vaxerski** [comment]
thanks, will look into it later today or tomorrow

**Comment by tarpan** [comment]
I can confirm it works on my machine, too. Thanks.

**Comment by vaxerski** [comment]
I'll close this. It works with a hack and after some inspection I can't find any hint from the app that would tell us not to unfocus the window when the mouse moves.

**Comment by Barmanji** [comment]
Well well well , Thanks @vaxerski and @tarpan, I had the same issue, now i can see the ID properly thanks for vax.

Now the 2nd problem is arrived :(
I cant connect, it says check your internet this that, and no one can connect to me. (ofc my internet is fine) and anydesk worked great when I was In i3

**Comment by vaxerski** [comment]
does it work on sway? Generally I doubt "internet connection" issues are related to hyprland
