### ISSUE TITLE
Critical error thrown: CBackend::create() failed!

### ISSUE THREAD

**Issue by JassonCordones** [hyprwm/Hyprland#6947]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

wl_registry#2: error 0: invalid version for global zwp_linux_dmabuf_v1 (59): have 4, wanted 5
terminate called after throwing an instance of 'std::runtime_error'
  what():  CBackend::create() failed!
Hyprland has crashed :(

### How to reproduce

Launch Hyprland from Wayland session 

### Crash reports, logs, images, videos

[hyprlandCrashReport69321.txt](https://github.com/user-attachments/files/16324710/hyprlandCrashReport69321.txt)

**Comment by vaxerski** [comment]
what are you launching it on? we require linux_dmabuf_v1 version 5, which should be supported by mutter and hyprland. Though I guess I can drop it down to 4

**Comment by vaxerski** [comment]
fixed in https://github.com/hyprwm/aquamarine/commit/601f6cf95cbe4fef02dc7faf34bba58566c914e9
