### ISSUE TITLE
Hyprland doesn't work if AQ_DRM_DEVICES  is set to use intel igpu

### ISSUE THREAD

**Issue by izmyname** [hyprwm/Hyprland#6956]
### Regression?

Yes

### System Info and Version

I'm not on the latest git right now, but the problem occurred after the merge aquamarine commit

### Description

Setting AQ_DRM_DEVICES to use intel igpu prevents hyprland from starting.

### How to reproduce

 #lspci | \grep -E 'VGA|3D'
 #ls -l /dev/dri/by-path
 #ln -sf /dev/dri/by-path/pci-***-card $HOME/.config/hypr/iGPU
 
 
 env = AQ_DRM_DEVICES,$HOME/.config/hypr/iGPU

### Crash reports, logs, images, videos

[hyprlandCrashReport1466.txt](https://github.com/user-attachments/files/16325451/hyprlandCrashReport1466.txt)

**Comment by vaxerski** [comment]
Aquamarine does not read links. Make sure to set it to the actual path.

From your log, that's either `/dev/dri/card0` or `/dev/dri/card1`.

Not a hyprland issue, if you want that implemented I guess open a ticket at aq

**Comment by izmyname** [comment]
I set it literally as it was  (and is) explained on this page https://wiki.hyprland.org/Configuring/Multi-GPU/

Also, it worked with $WLR_DRM_DEVICES.

**Comment by vaxerski** [comment]
yep, that has to be updated in the wiki

> Also, it worked with $WLR_DRM_DEVICES

Yes, wlroots does. Aquamarine doesn't.

**Comment by izmyname** [comment]
Okay, can confirm AQ_DRM_DEVICES,/dev/dri/card1 fixes the issue

**Comment by vaxerski** [comment]
I've updated the wiki too

**Comment by YuvrajMehta** [comment]
in which file do I add AQ_DRM_DEVICES env variable?

**Comment by vaxerski** [comment]
wherever you want so that hyprland has the env. Can also be in the hyprland config
