### ISSUE TITLE
Clients from the top layer are not hidden when opening a full-screen game

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/Hyprland#6960]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit cbaac6deafb857662d630efbca8b0ebac0f11b44 dirty (xwm: drop invalid case for clearing X focus).
Date: Sun Jul 21 21:02:48 2024
Tag: v0.41.2-60-gcbaac6de, commits: 4946

flags: (if any)


System Information:
System name: Linux
Node name: localhost
Release: 6.9.10-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 18 Jul 2024 18:05:52 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600] [1002:7480] (rev cf) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

When you run a full-screen game through Proton, the client from the top layer (waybar) is not hidden. Prior to https://github.com/hyprwm/Hyprland/commit/cbaac6deafb857662d630efbca8b0ebac0f11b44 and https://github.com/hyprwm/Hyprland/commit/f7fb7e7e49e3b47f9b72c55fbf2d093e1a7981f5, the behavior was different in that when starting a full-screen game, the client was also not hidden, but switching to a different workspace, or opening a special workspace and then returning back to the game, helped in this situation. At the moment, the above actions do not help.

### How to reproduce

Game - SCP: Secret Laboratory. Free on Steam and does not take up much space. Proton Experimental (bleeding-edge), graphical API - Vulkan.

**Comment by TAforever** [comment]
https://github.com/hyprwm/Hyprland/issues/6568
