### ISSUE TITLE
Crash today

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#697]
I'm not shure if you can make sense out of this.
[coredump.log](https://github.com/hyprwm/Hyprland/files/9615148/coredump.log)

**Comment by vaxerski** [comment]
what were you doing? Is this reproducible? Seems weird.

**Comment by Dickby** [comment]
I'm not shure, i think i was moving a window to a workspace or something. 
Sorry

**Comment by Dickby** [comment]
got another one.
I tested something with a youtube video pinned fullscreened moved to another workspace.
[coredump.log](https://github.com/hyprwm/Hyprland/files/9615494/coredump.log)

**Comment by Dickby** [comment]
Reproduce with:
produce a pinned window,
fullscreen that window,
switch to another workspace that has some windows,
focus the pinned fullscreen window (i do it with a mouse motion (follow mouse).
try to unfullscreen the pinned window.
I hope its reproducbble it on your machine too.

**Comment by vaxerski** [comment]
should be fixed with d24f31de514be1c78fcb6a3ad392a01dd7117e3e as pinned windows can no longer be fullscreen.

**Comment by Dickby** [comment]
Reasonable,
thanks!
