### ISSUE TITLE
Login screen is upside down

### ISSUE THREAD

**Issue by 4th3LuLz0fIt** [hyprwm/Hyprland#6985]
OS Debian 12

Laptop HP Envy

No Nivdia 

My issue is the orientation has been flipped upside down after converting my laptop to tablet mode. In normal laptop mode everything is working.

I managed to resolve the screen orientation for the desktop session. But I'm a Hyprland noob and do not know what the .conf is for the login screen.

**Comment by vaxerski** [comment]
please follow the templates
