### ISSUE TITLE
Windows don't lose focus when switching workspace

### ISSUE THREAD

**Issue by Dries1234** [hyprwm/Hyprland#699]
When switching to a new workspace, windows on previous workspace don't lose focus.
Not completely sure if that is the issue but that is the assumption.
I'm taking discord as an example

Steps to reproduce:
- Have discord open in a chat
- Switch to a new workspace
- Wait for a message to be sent in that chat

Expected outcome: A notification is sent

Noted outcome: The message gets marked as read and no notification is sent.

**Comment by vaxerski** [comment]
XWayland issue, focus another XWayland window to remove the focus from the previous.

**Comment by vaxerski** [comment]
fixed in f7174acc4850ac93feb291707de9d9861c9fab56
