### ISSUE TITLE
Caps Lock does not capitalize letters in XWayland windows

### ISSUE THREAD

**Issue by raidenovich** [hyprwm/Hyprland#7000]
### Regression?

Yes

### System Info and Version

Hyprland, built from branch  at commit efcbcd7297e2c9b06e3cd5d3296d47504f502cee  ().
Date: 2024-07-21
Tag: , commits: efcbcd7297e2c9b06e3cd5d3296d47504f502cee

flags: (if any)

System Information:
System name: Linux
Node name: ShadowMoses
Release: 6.6.40-xanmod1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980

GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c0) (prog-if 00 [VGA controller])

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240719.1d9c2c9"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

plugins:

======Config-Start======

Config File: /home/vaporsnake/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/wbqwrp6gpf31acmdchik5lsj8zdw2z24-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$mainMod=SUPER
animations {
  bezier=overshot, 0.13, 0.99, 0.29, 1.1
  animation=windows, 1, 3, overshot, slide
  animation=windowsOut, 1, 7, overshot, slide
  animation=border, 1, 10, default
  animation=fade, 0, 0, default
  animation=workspaces, 0, 6, default
  enabled=true
}

decoration {
  col.shadow=rgba(1a1a1aee)
  drop_shadow=false
  rounding=5
  shadow_range=4
  shadow_render_power=3
}

dwindle {
  preserve_split=true
  pseudotile=true
}

general {
  border_size=2
  col.active_border=rgb(99D1DB)
  gaps_in=5
  gaps_out=20
  layout=dwindle
  resize_on_border=true
}

gestures {
  workspace_swipe=true
}

input {
  touchpad {
    natural_scroll=true
  }
  float_switch_override_focus=2
  follow_mouse=1
  kb_layout=tr,us
  kb_options=grp:rctrl_toggle
  sensitivity=0
}

misc {
  force_default_wallpaper=false
}
bind=$mainMod, Return, exec, kitty
bind=SUPER_SHIFT, W, killactive,
bind=SUPER_SHIFT, Del, exec, pkill Hyprland
bind=$mainMod, A, togglefloating,
bind=CTRL, Escape, exec, /nix/store/336kjgrlpg4dwad92clz5p37jgirah86-anyrun-0.1.0/bin/anyrun
bind=$mainMod SHIFT, F, exec, /nix/store/yg5pafyvv4bij1y67bni2bi57ldzb7fl-nautilus-46.2/bin/nautilus
bind=$mainMod, E, togglesplit, # dwindle
bind=$mainMod,F,fullscreen
bind=,Print, exec, /nix/store/vcrsr30s5d3m4waw287qjkkzs74rqhmm-wayfreeze/bin/wayfreeze --hide-cursor & PID=$!; sleep .1; /nix/store/x15z01i936qylmmbd3swgzvsy9c99z5k-grim-1.4.1/bin/grim -g "$(/nix/store/23ah3nycfbd5sh93w4lhxx5lwl2w9z92-slurp-1.5.0/bin/slurp)" - | /nix/store/5xki6pdx64j86i14083sgrhzjazh8p0b-shadower-0.1.4/bin/shadower | /nix/store/zdh7phcmqsmyssr0ary1gi0wb4cqml1w-wl-clipboard-2.2.1/bin/wl-copy; kill $PID
bind=$mainMod, Tab, exec, /nix/store/h3aimcim9n2akgkac3ngcnncavr910wv-SwayNotificationCenter-0.10.1/bin/swaync-client -t
bind=SUPER_SHIFT, minus, exec, /nix/store/pnjlv8vlh3pbiqf8lfk41v7kkgppsnqv-scratchpad-0.1/bin/scratchpad
bind=$mainMod, minus, exec, /nix/store/pnjlv8vlh3pbiqf8lfk41v7kkgppsnqv-scratchpad-0.1/bin/scratchpad -g
bind=Alt_L, E, exec, hyprctl dispatch workspace +1
bind=Alt_L, Q, exec, hyprctl dispatch workspace -1
bind=$mainMod, V, exec, /nix/store/0sax68hbc3g5ys4hnpb799kp2h8gxr56-cliphist-0.5.0/bin/cliphist list | /nix/store/dmpqxnj4wm6lqakzh4rbyzpvrgaihc7f-wofi-1.4.1/bin/wofi --dmenu | /nix/store/0sax68hbc3g5ys4hnpb799kp2h8gxr56-cliphist-0.5.0/bin/cliphist decode | /nix/store/zdh7phcmqsmyssr0ary1gi0wb4cqml1w-wl-clipboard-2.2.1/bin/wl-copy
bind=$mainMod, left, movefocus, l
bind=$mainMod, right, movefocus, r
bind=$mainMod, up, movefocus, u
bind=$mainMod, down, movefocus, d
bind=Alt_L, Tab, exec, sleep 0.1 && hyprswitch --daemon --ignore-monitors --switch-ws-on-hover
bind=Alt_L, quotedbl, exec, hyprswitch --stop-daemon
bind=,Caps_Lock, exec, sleep 0.1 && /nix/store/myivqnkfnl15j2j8vnhjypgxyfxgql1s-swayosd-0-unstable-2024-04-15/bin/swayosd-client --caps-lock
bind=$mainMod, Q, togglegroup
bind=$mainMod, D, changegroupactive
bind=$mainMod, W, lockgroups, toggle
bind=SUPER,F10,pass,^(com.obsproject.Studio)$
bind=SUPER,F9,pass,^(com.obsproject.Studio)$
bind=SUPER,F4,pass,^(com.obsproject.Studio)$
bind=$mainMod, Insert,pass,^(discordcanary)$
bind=$mainMod, Home,pass,^(discordcanary)$
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod SHIFT, 1, movetoworkspacesilent, 1
bind=$mainMod SHIFT, 2, movetoworkspacesilent, 2
bind=$mainMod SHIFT, 3, movetoworkspacesilent, 3
bind=$mainMod SHIFT, 4, movetoworkspacesilent, 4
bind=$mainMod SHIFT, 5, movetoworkspacesilent, 5
bind=$mainMod SHIFT, 6, movetoworkspacesilent, 6
bind=$mainMod SHIFT, 7, movetoworkspacesilent, 7
bind=$mainMod SHIFT, 8, movetoworkspacesilent, 8
bind=$mainMod SHIFT, 9, movetoworkspacesilent, 9
bind=$mainMod SHIFT, 0, movetoworkspacesilent, 10
bind=$mainMod, minus, movetoworkspace, special:scratchpad
bind=$mainMod SHIFT, left, movewindow, l
bind=$mainMod SHIFT, right, movewindow, r
bind=$mainMod SHIFT, up, movewindow, u
bind=$mainMod SHIFT, down, movewindow, d
bind=$mainMod, mouse_up, workspace, r+1
bind=$mainMod, mouse_down, workspace, r-1
bind=$mainMod, h, workspace, 11
bind=$mainMod, j, workspace, 12
bind=$mainMod, k, workspace, 13
bind=$mainMod, l, workspace, 14
bind=$mainMod SHIFT, h, movetoworkspacesilent, 11
bind=$mainMod SHIFT, j, movetoworkspacesilent, 12
bind=$mainMod SHIFT, k, movetoworkspacesilent, 13
bind=$mainMod SHIFT, l, movetoworkspacesilent, 14
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow
bindrn=Alt_L, Tab, exec, hyprswitch --daemon --ignore-monitors --switch-ws-on-hover || hyprswitch --stop-daemon
bindrn=SUPER, SUPER_L, exec, pkill wofi || /nix/store/dmpqxnj4wm6lqakzh4rbyzpvrgaihc7f-wofi-1.4.1/bin/wofi
exec-once=mullvad-gui
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=hyprctl setcursor macOS-BigSur 24
exec-once=discover-overlay
exec-once=flameshot
exec-once=sleep 0.5 && ags
exec-once=/nix/store/8l6brs42v31i96fbw27xzvd43dzm1f0k-wlsunset-0.4.0/bin/wlsunset
exec-once=/nix/store/h3aimcim9n2akgkac3ngcnncavr910wv-SwayNotificationCenter-0.10.1/bin/swaync
exec-once=/nix/store/944qm3a1k2dmg1ilayayblhiv3qamzg7-swayidle-1.8.0/bin/swayidle -C ~/.config/swayidle/config
exec-once=/nix/store/myivqnkfnl15j2j8vnhjypgxyfxgql1s-swayosd-0-unstable-2024-04-15/bin/swayosd-server
exec-once=/nix/store/48vkbazypzxh621l2s067nml1gi69y24-mate-polkit-1.28.1/libexec/polkit-mate-authentication-agent-1
exec-once=/nix/store/cp10wdvh751fc4ss3r7nbv0glfbaqpxh-hypridle-0.1.2/bin/hypridle
exec-once=/nix/store/zdh7phcmqsmyssr0ary1gi0wb4cqml1w-wl-clipboard-2.2.1/bin/wl-copy --type image --watch /nix/store/0sax68hbc3g5ys4hnpb799kp2h8gxr56-cliphist-0.5.0/bin/cliphist store
exec-once=/nix/store/zdh7phcmqsmyssr0ary1gi0wb4cqml1w-wl-clipboard-2.2.1/bin/wl-copy --type text --watch /nix/store/0sax68hbc3g5ys4hnpb799kp2h8gxr56-cliphist-0.5.0/bin/cliphist store
exec-once=/nix/store/yvd54b8i586j8bjjap7h4lgwh8y06ha3-arrpc-3.4.0/bin/arrpc
exec-once=/nix/store/8hcl0fj1w0axdbdhhp2a9aywvbxm3pjz-premid-2.3.4/bin/premid --in-process-gpu
exec-once=/nix/store/ywf960qsaw4117izfgi2bpv2zzh6ifg4-swaybg-1.2.1/bin/swaybg --o DP-2 -i /nix/store/5rha8bp2q3sjz0jm2k8qamsfvz4qcfgj-strawHats.png
exec-once=/nix/store/ywf960qsaw4117izfgi2bpv2zzh6ifg4-swaybg-1.2.1/bin/swaybg --o HDMI-A-1 -i /nix/store/hfqfzxvs9lp6h92gqj7rf6s39kf004ca-mark-of-sacrifice-vertical.png
exec-once=/nix/store/ssr703zd7ac8yh24lhq383gd9fk3mc8j-NoiseTorch-0.12.2/bin/noisetorch -i alsa_input.usb-IK_Multimedia_iRig_Mic_HD_2_N_A-00.mono-fallback
general:layout=dwindle
layerrule=noanim,rofi
layerrule=xray 1, wofi
monitor=DP-2,2560x1440@164.998993, 0x350, 1
monitor=HDMI-A-1,1920x1080,2560x0, 1, transform, 3
windowrulev2=float,title:^(flameshot)
windowrulev2=move 0 -350,title:^(flameshot)
windowrulev2=suppressevent fullscreen,title:^(flameshot)
windowrulev2=noanim,title:^(flameshot)
windowrulev2=rounding 0,title:^(flameshot)
windowrulev2=monitor DP-2,title:^(flameshot)
windowrulev2=float,title:^(Firefox — Sharing Indicator)
windowrulev2=nomaxsize,title:^(winecfg)
windowrulev2=nomaxsize,class:^(steam)
windowrulev2=noanim,title:^(wlogout)
windowrulev2=float,title:^(wlogout)
windowrulev2=workspace 1, class:^(firefox)
windowrulev2=workspace 2,class:^(discord)
windowrulev2=workspace 2,class:^(vesktop)
windowrulev2=workspace 3,title:^(Steam)
windowrulev2=workspace 3,class:^(org.prismlauncher.PrismLauncher)
windowrulev2=workspace 4,class:^(mpv)
windowrulev2=workspace 5,title:^(nvim)
windowrulev2=workspace 6,class:^(krita)
windowrulev2=workspace 6,class:^(.gimp-2.10-wrapped_)
windowrulev2=workspace 7,class:^(evince)
windowrulev2=workspace 7,class:^(info.febvre.Komikku)
windowrulev2=workspace 7,class:^(Upscayl)
windowrulev2=workspace 8,class:^(obsidian)
windowrulev2=workspace 9,class:^(Waydroid)
windowrulev2=workspace 10,class:^(steam_app*)
windowrulev2=stayfocused,class:^(Waydroid)
workspace=1,monitor:DP-2
workspace=2,monitor:DP-2
workspace=3,monitor:DP-2
workspace=4,monitor:DP-2
workspace=5,monitor:DP-2
workspace=6,monitor:DP-2
workspace=7,monitor:DP-2
workspace=8,monitor:DP-2
workspace=9,monitor:DP-2
workspace=10,monitor:DP-2
workspace=11,monitor:HDMI-A-1
workspace=12,monitor:HDMI-A-1
workspace=13,monitor:HDMI-A-1
workspace=14,monitor:HDMI-A-1
group {
  col.border_active = rgb(99D1DB)
  col.border_inactive = rgb(4d4d4d)
  groupbar {
      col.active = rgb(99D1DB)
      col.inactive = rgb(4d4d4d)
      gradients = false
      render_titles = false
    }
}
plugin {
    hyprbars {
        bar_height=29
        bar_text_font="Terminess Nerd Font"
        bar_text_size=13
        # config
        buttons {
            button_size= 13
            # button config
        }
    }
}

plugin {
  hy3 {
    # disable gaps when only one window is onscreen
    no_gaps_when_only = false

    # offset from group split direction when only one window is in a group
    group_inset = 10

    # tab group settings
    tabs {
      # height of the tab bar
      height = 10

      # padding between the tab bar and its focused node
      padding = 15

      # the tab bar should animate in/out from the top instead of below the window
      from_top = false

      # render the window title on the bar
      render_text = false

      # rounding of tab bar corners
      rounding = 15

      # font to render the window title with
      text_font = "Terminess Nerd Font"

      # height of the window title
      text_height = 10

      # left padding of the window title
      text_padding = 0

      # active tab bar segment color
      col.active = rgb(c8c093)

      # urgent tab bar segment color
      col.urgent = 0x4D6469

      # inactive tab bar segment color
      col.inactive = 0x4D6469

      # active tab bar text color
      col.text.active = 0x4D6469

      # urgent tab bar text color
      col.text.urgent = 0x4D6469

      # inactive tab bar text color
      col.text.inactive = 0x4D6469
    }
  }
}

### Description

The caps lock key does not capitalize letters on XWayland windows

Workaround: Press SHIFT once to activate it every time you press CAPS LOCK to activate the capitalization of letters while typing.

### How to reproduce

Press CAPS LOCK while in an XWayland window (on the current build I'm on, probably aquamarine related issue as it didnt happen before when I was on a build using wlroots)

XWayland Window example: Steam, Vesktop

**Comment by vaxerski** [comment]
can you check latest git

**Comment by ikalco** [comment]
is this still a problem? i think cd942ad fixed this

**Comment by vaxerski** [comment]
yes that's why I asked for a retest

**Comment by vaxerski** [comment]
closing lack of inactivity + likely fixd

**Comment by raidenovich** [comment]
It has been fixed, can confirm
