### ISSUE TITLE
nix: wlroot remnants

### ISSUE THREAD

**Issue by isabelroses** [hyprwm/Hyprland#7002]
If wlroots is no longer being used on main. Then should the remnants of its build not also have been removed too?

See:
- https://github.com/hyprwm/Hyprland/blob/3c758db95c129ed6ca7ce0c1b5b82ad6e189488d/nix/default.nix#L93
- https://github.com/hyprwm/Hyprland/blob/3c758db95c129ed6ca7ce0c1b5b82ad6e189488d/nix/default.nix#L133

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Thanks, fixed 752604cf.
