### ISSUE TITLE
Invisible Mouse Cursor

### ISSUE THREAD

**Issue by mairm1340** [hyprwm/Hyprland#7003]
### Regression?

Yes

### System Info and Version

Hyprland received signal 6(ABRT)
Version: 672bf1f8670b200da57e2f6de4e9ed7efd8c98fc
Tag: v0.41.2-63-g672bf1f8

System info:
System name: Linux
Node name: s2600cwr
Release: 6.9.10-zen1-1-zen
Version: https://github.com/hyprwm/hyprcursor/issues/1 ZEN SMP PREEMPT_DYNAMIC Thu, 18 Jul 2024 18:05:52 +0000

GPU:
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])

os-release:
NAME=ArcoLinux
ID=arcolinux
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://arcolinux.info/"
SUPPORT_URL="https://arcolinuxforum.com/"
BUG_REPORT_URL="https://github.com/arcolinux"
LOGO=arcolinux-hello

### Description

Hi
Mouse cursor works on all Window manager except hyprland.

I did enable debug and I see the below

<---- output omitted---->
[LOG] Creating the CursorManager!
[hc] CHyprcursorManager: attempting to find theme from env
[hc] themeNameFromEnv: env unset
[hc] CHyprcursorManager: attempting to find any theme
[hc] CHyprcursorManager: no themes matched
[ERR] Hyprcursor failed loading theme "", falling back to X.
[LOG] XCursor has no shape invalid, skipping
[LOG] XCursor has no shape context-menu, skipping
[LOG] XCursor has no shape progress, skipping
[LOG] XCursor has no shape vertical-text, skipping
[LOG] XCursor has no shape alias, skipping
[LOG] XCursor has no shape copy, skipping
[LOG] XCursor has no shape no-drop, skipping
[LOG] XCursor has no shape not-allowed, skipping
[LOG] XCursor has no shape grab, skipping
[LOG] XCursor failed to find a shape with name ns-resize, skipping
[LOG] XCursor has no shape nesw-resize, skipping
[LOG] XCursor has no shape nwse-resize, skipping
[LOG] XCursor has no shape col-resize, skipping
[LOG] XCursor has no shape row-resize, skipping
[LOG] XCursor has no shape all-scroll, skipping
[LOG] XCursor has no shape zoom-in, skipping
[LOG] XCursor has no shape zoom-out, skipping
<---- output omitted---->

i did try to set it manually but still the mouse cursors are invisible...
❯ hyprctl setcursor Catppuccin-Flamingo-Cursors 28
ok

Kindly assist...

### How to reproduce

NA

### Crash reports, logs, images, videos

NA

**Comment by mairm1340** [comment]
WLR_NO_HARDWARE_CURSORS returns 1
I also configure this as exec = hyprctl setcursor xxxxx 24 but that has no effect

**Comment by vaxerski** [comment]
dupe #7001
