### ISSUE TITLE
`hyprpm update` cannot checkout the correct version

### ISSUE THREAD

**Issue by nemarci** [hyprwm/Hyprland#7008]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

The only relevant info is the output of `hyprctl version`, so I will post that instead:

```
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)

```

</details>

### Description

`hyprpm update`  failed with "Headers version mismatch. Please run hyprpm update to fix those."; which is ironic, since that was the command I was running.

Note that as I posted above, the output of `hyprctl version` did not contain a branch, only a commit message. This means that in `CPluginManager::updateHeaders`, the following happens:

1, Hyprland version is fetched

```cpp
    const auto HLVER = getHyprlandVersion();
```

After that point, `HLVER.branch` is an empty string, while `HLVER.hash` should contain the correct commit hash (I didn't check if it is indeed correct, but it should be, based on the output of `hyprctl version`). 

2, Hyprland repo is cloned

This works as expected; after the clone, `HEAD` points to the `main` branch

3, The updater tries to checkout the correct version

This is the problematic step:

```cpp
    ret = execAndGet("cd " + WORKINGDIR + " && git checkout " + HLVER.branch + " 2>&1");
``` 

You can find it here:  https://github.com/hyprwm/Hyprland/blob/main/hyprpm/src/core/PluginManager.cpp#L467

The issue here is that `HLVER.branch` is an empty string, which means that `git checkout` is run without any further arguments; it doesn't check out anything, just prints the current `HEAD`, which points to the `main` branch.

After that, the update obviously breaks at some point because of the version mismatch.

I think this is simple to solve; we should use `HLVER.hash` instead of `HLVER.branch`. First of all, it seems like `branch` is not always available in `hyprctl version`. Second of all, branches are typically mutable objects in Git. Contributors push to branches, which moves the branch forward. This means that if I installed the `foo` branch at some point, there is no guarantee that `foo` will point to the exact same version (unless there's some strict policy about this in Hyprland). Commit hashes and tags are typically immutable, so they are a much better fit to find an exact version of Hyprland.

Additional notes:

- I use Arch Linux, just ran a system update (`pacman -Syu`), rebooted the system, and that's when this problem occured.
- I did the following workaround:
- - Run `gdb --args hyprpm update`
- - Added a breakpoint after the problematic call (the `git checkout`)
- - After the breakpoint was hit, I manually checked out the correct version (using the commit hash)
- - I ran `continue` in gdb
- - Now the correct version was checked out, so `hyprpm update` ran successfully

### How to reproduce

Run `hyprpm update` on a version where `hyprctl version` returns an empty string for the branch (for example, the current version in the Arch Linux repository)

**Comment by vaxerski** [comment]
doooop #6948

the reason is a submodule was deleted

**Comment by vaxerski** [comment]
it's still a dupe, it will show as linked in the original issue
