### ISSUE TITLE
Allow Capital characters in config file.

### ISSUE THREAD

**Issue by Heisfer** [hyprwm/Hyprland#701]
I have noticed in the wiki that some commands are really long, like `movecurrentworkspacetomonitor`.
My proposal is to allow capital letters in config for readability like:

camelCase: `moveCurrentWorkspaceToMonitor`
PascalCase: `MoveCurrentWorkspaceToMonitor`

Or whatever the person likes.

**Comment by vaxerski** [comment]
done in d3ffccd45ff6d6f7bf8cd08b4c1d9e0c00635ab4
