### ISSUE TITLE
Cursor size and image are different on some windows

### ISSUE THREAD

**Issue by coffebar** [hyprwm/Hyprland#7022]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 99088eaed806d9268967baf09bc09cdb987c5357  (compositor: simplify getWindowFromSurface).
Date: Wed Jul 24 10:07:28 2024
Tag: v0.41.2-84-g99088eae, commits: 4970

flags: (if any)


System Information:
System name: Linux
Node name: ***
Release: 6.10.0-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
...
```

</details>

### Description

I'm on git version from AUR, just updated to v0.41.2-84-g99088eae and something happened to the cursors.
Look at mouse cursor: 

https://github.com/user-attachments/assets/007a928a-7bbf-4990-a214-31163a333c46

Firefox has a cursor as it was before on all apps. Now most of the apps have a cursor 50% of regular size (image is also different) 

### How to reproduce

1. Move mouse cursor to firefox window (or thunar, or thunderbird) and make sure that cursor is correct size
2. Move mouse to alacritty terminal (or chrome browser or kate editor), and see that cursor is too small and it's image is different

**Comment by vaxerski** [comment]
are you using xcursor?

**Comment by coffebar** [comment]
Not sure what do you mean, I have libxcursor installed as a dependency:

> :: removing libxcursor breaks dependency 'libxcursor' required by alacritty
> :: removing libxcursor breaks dependency 'libxcursor' required by freerdp
> :: removing libxcursor breaks dependency 'libxcursor' required by gimp
> :: removing libxcursor breaks dependency 'libxcursor' required by gtk2
> :: removing libxcursor breaks dependency 'libxcursor' required by gtk3
> :: removing libxcursor breaks dependency 'libxcursor' required by gtk4
> :: removing libxcursor breaks dependency 'libxcursor' required by hyprland-git
> :: removing libxcursor breaks dependency 'libxcursor' required by sdl2

But I did nothing with cursor settings, except long time ago I selected a cursor in lxappearance.
![image](https://github.com/user-attachments/assets/8ba39cd6-91c2-421e-a922-4ed406d3a0b2)

**Comment by vaxerski** [comment]
ye so you are using xcursor. Check if hyprcursor does the same, likely not. #6983
