### ISSUE TITLE
Main mod + mouse broken in dwindle layout

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#703]
The dwindle layout has this handy feature where you can move and resize windows with mod + mouse, but it seems to be broken.
How reproduce: I think it's just install hyprland and use the dwindle layout, but it could be something specific to my config file as well.
I am using the hyprland-git from the AUR.
My config file is attached.
[hyprland.txt](https://github.com/hyprwm/Hyprland/files/9619039/hyprland.txt)

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/issues/694

**Comment by EysseW** [comment]
Thanks. I actually took some time to check if my bug report was duplicate, but I failed to find any. I guess it was because they were already closed. Sorry for the bug unnecessary bug report!
