### ISSUE TITLE
Hyprland crashed when launching wofi

### ISSUE THREAD

**Issue by Akira-uestc** [hyprwm/Hyprland#7032]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 72bce7efd5b302412f13485af27985965ddf830f dirty (keybinds: add bindp and noshortcutsinhibit (7017)).
Date: Wed Jul 24 20:10:36 2024
Tag: v0.41.2-85-g72bce7ef, commits: 4971

flags: (if any)


System Information:
System name: Linux
Node name: Akira
Release: 6.10.0-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:45:00 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 03) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/akira/.config/hypr/hyprland.conf: Read Succeeded
monitor=,1920x1080@60,0x0,1

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
$Screenshot = grim -g "$(slurp)" -t png - | tee /home/akira/Pictures/screenshot/$(date +%y-%m-%d_%H-%M-%S).png | wl-copy -t image/png 
$FullScreenshot = grim -g "0,0 1920x1080" -t png - | tee /home/akira/Pictures/screenshot/$(date +%y-%m-%d_%H-%M-%S).png | wl-copy -t image/png
$Lock = brightnessctl set 0
$Wake = brightnessctl set 50%

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
        scroll_factor = 0.2
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https:///wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = false
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_status = master
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 to disable the anime mascot wallpapers
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device {
    name = 5b07320e1350
    #sensitivity = -0.5
    sensitivity = 0
}

xwayland {
  force_zero_scaling = true
}
env = GDK_SCALE,1.5
env = XCURSOR_SIZE,24

source = /home/akira/.config/hypr/execs.conf
source = /home/akira/.config/hypr/env.conf
source = /home/akira/.config/hypr/keys.conf
source = /home/akira/.config/hypr/windowrule.conf



Config File: /home/akira/.config/hypr/execs.conf: Read Succeeded
exec-once = kwalletd5

#wallpaper
$wallpaper_path=/home/akira/Pictures/swaybg/
exec-once=swaybg -i $(find $wallpaper_path -type f | shuf -n 1) -m fill
#exec-once = swww init
#exec-once =~/.config/hypr/scripts/swww-random ~/Pictures/swaybg/

#waybar
exec-once = waybar -c /home/akira/.config/waybar/config.hypr

#fcitx5
exec-once = fcitx5 --replace -d

#network
exec-once = NetworkManager
exec-once = nm-applet

exec-once = pw-volume

exec-once = mako

exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = wl-paste --type text cliphist store
exec-once = wl-paste --type image cliphist store

exec-once = /home/akira/configuration/scripts/qq.sh



Config File: /home/akira/.config/hypr/env.conf: Read Succeeded
# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
env = QT_SCREEN_SCALE_FACTORS,1
env = QT_FONT_DPI,120


Config File: /home/akira/.config/hypr/keys.conf: Read Succeeded
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, L, exec, $Lock
bind = $mainMod, W, exec, $Wake
bind = $mainMod, PRINT, exec, $Screenshot
bind = , PRINT, exec, $FullScreenshot
bind = $mainMod, P, exec, notify-send $(hyprpicker)
bind = ,F2, exec, grim -g "$(slurp)" ~/.cache/com.pot-app.desktop/pot_screenshot_cut.png && curl "127.0.0.1:60828/ocr_translate?screenshot=false"
bind = Ctrl, L, exec, /home/akira/.config/wlogout/lock.sh


# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = ,XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%


Config File: /home/akira/.config/hypr/windowrule.conf: Read Succeeded
windowrulev2 = suppressevent,maximize, class:.* 
windowrulev2 = tile,class:^(wps|et|wpp|pdf)$,title:^(WPS文字|WPS表格|WPS演示|WPS PDF)$
windowrulev2 = tile,class:.*,title:^(WPS文字|WPS表格|WPS演示|WPS PDF)$
windowrulev2 = tile,class:^(vofa+)$,title^(VOFA+)$
windowrulev2 = tile,class:^(xmind)$,title:^(Xmind)$
windowrulev2 = tile,class:^(wechat)$
windowrulev2 = tile,class:^(netease-cloud-music)$
windowrulev2 = tile,class:^(QQ)$,title:^(QQ)$
windowrulev2 = float,class:^(NotificationViewer)$,title:^(Notification Viewer)$
windowrulev2 = size 960 540,class:^(NotificationViewer)$,title:^(Notification Viewer)$
windowrulev2 = noshadow,floating:1
windowrulev2 = noborder,floating:1
windowrulev2 = noblur,floating:1


======Config-End========

```

</details>

### Description

Hyprland crashed when launching wofi by shortcut `$mainMod,R`

Starting wofi from terminal and do not type anything won't cause crash

72bce7e is the first bad commit

### How to reproduce

- Run wofi

- Type anything

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11(SEGV)
Version: 72bce7efd5b302412f13485af27985965ddf830f
Tag: v0.41.2-85-g72bce7ef

System info:
	System name: Linux
	Node name: Akira
	Release: 6.10.0-zen1-2-zen
	Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:45:00 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 03) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x5b21fc7a4961]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xb49) [0x5b21fc727549]
		std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&)
		/usr/include/c++/14.1.1/bits/basic_string.h:632
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x5b21fc6a5b31]
		handleUnrecoverableSignal(int)
		/usr/src/debug/hyprland-git/Hyprland/src/Compositor.cpp:72
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x7410d2a4c1d0]
		??
		??:0
	#4 | Hyprland(+0xd837c) [0x5b21fc63037c]
		std::_Rb_tree<eOverridePriority, std::pair<eOverridePriority const, bool>, std::_Select1st<std::pair<eOverridePriority const, bool> >, std::less<eOverridePriority>, std::allocator<std::pair<eOverridePriority const, bool> > >::empty() const
		/usr/include/c++/14.1.1/bits/stl_tree.h:1026
	#5 | Hyprland(_ZN15CKeybindManager14handleKeybindsEjRK19SPressedKeyWithModsb+0x2ef) [0x5b21fc7e417f]
		CKeybindManager::handleKeybinds(unsigned int, SPressedKeyWithMods const&, bool)
		/usr/src/debug/hyprland-git/Hyprland/src/managers/KeybindManager.cpp:610 (discriminator 2)
	#6 | Hyprland(_ZN15CKeybindManager10onKeyEventESt3anyN9Hyprutils6Memory14CSharedPointerI9IKeyboardEE+0x649) [0x5b21fc7e58c9]
		CKeybindManager::onKeyEvent(std::any, Hyprutils::Memory::CSharedPointer<IKeyboard>)
		/usr/src/debug/hyprland-git/Hyprland/src/managers/KeybindManager.cpp:405
	#7 | Hyprland(_ZN13CInputManager13onKeyboardKeyESt3anyN9Hyprutils6Memory14CSharedPointerI9IKeyboardEE+0x30f) [0x5b21fc8346cf]
		CInputManager::onKeyboardKey(std::any, Hyprutils::Memory::CSharedPointer<IKeyboard>)
		/usr/src/debug/hyprland-git/Hyprland/src/managers/input/InputManager.cpp:1285 (discriminator 4)
	#8 | Hyprland(+0x2e3e29) [0x5b21fc83be29]
		std::any::has_value() const
		/usr/include/c++/14.1.1/any:329
	#9 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal21CStaticSignalListener4emitESt3any+0x66) [0x7410d3022c86]
		??
		??:0
	#1 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x58e) [0x7410d302326e]
		??
		??:0
	#11 | Hyprland(+0x2239c4) [0x5b21fc77b9c4]
		std::any::has_value() const
		/usr/include/c++/14.1.1/any:329
	#12 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x7410d3022b5f]
		??
		??:0
	#13 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ee) [0x7410d3022ece]
		??
		??:0
	#14 | /usr/lib/libaquamarine.so.0(_ZN10Aquamarine8CSession19handleLibinputEventEP14libinput_event+0x83d) [0x7410d34cae6d]
		??
		??:0
	#15 | /usr/lib/libaquamarine.so.0(_ZN10Aquamarine8CSession22dispatchLibinputEventsEv+0xe4) [0x7410d34cd054]
		??
		??:0
	#16 | Hyprland(+0x2c468a) [0x5b21fc81c68a]
		aquamarineFDWrite(int, unsigned int, void*)
		/usr/src/debug/hyprland-git/Hyprland/src/managers/eventLoop/EventLoopManager.cpp:35
	#17 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x1f2) [0x7410d34020a2]
		??
		??:0
	#18 | /usr/lib/libwayland-server.so.0(wl_display_run+0x2f) [0x7410d340410f]
		??
		??:0
	#19 | Hyprland(_ZN17CEventLoopManager9enterLoopEv+0x2a9) [0x5b21fc81fbf9]
		CEventLoopManager::enterLoop()
		/usr/src/debug/hyprland-git/Hyprland/src/managers/eventLoop/EventLoopManager.cpp:48 (discriminator 1)
	#2 | Hyprland(main+0xca0) [0x5b21fc6674c0]
		main
		/usr/src/debug/hyprland-git/Hyprland/src/main.cpp:160 (discriminator 1)
	#21 | /usr/lib/libc.so.6(+0x25e08) [0x7410d2a34e08]
		??
		??:0
	#22 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7410d2a34ecc]
		??
		??:0
	#23 | Hyprland(_start+0x25) [0x5b21fc6a1d95]
		_start
		??:?

Log tail:
[LOG] [LinuxDMABUF]  | plane 2: mod 72057594037927944 fd 115 stride 64 offset 8142848
[LOG] Window 5b2235b6f690 set title to paru -Scc ~
[LOG] Searching for matching rules for kitty (title: paru -Scc ~)
[LOG] Window rule suppressevent -> maximize, class:.* matched [Window 5b2235b6f690: title: "paru -Scc ~"]
[LOG] [WLCompositor] New wl_region with id 45 at 5b2235933380
[LOG] Window 5b2235b6f690 set title to ~
[LOG] Searching for matching rules for kitty (title: ~)
[LOG] Window rule suppressevent -> maximize, class:.* matched [Window 5b2235b6f690: title: "~"]
[LOG] Keybind triggered, calling dispatcher (64, , 99)
[LOG] [Window 5b2235b6f690: title: "~", class: kitty] unmapped
[LOG] Framebuffer created, status 36053
[LOG] Removing last node (dwindle)
[LOG] On closed window, new focused candidate is [Window nullptr]
[LOG] [Window 5b2235b6f690: title: "~", class: kitty] destroyed, queueing.
[LOG] CWLSurface 5b22358cecf0 called destroy()
[ERR] onWindowRemovedTiling node null?
[LOG] Unmap TI owner1
[LOG] Keybind triggered, calling dispatcher (64, , 49)
[LOG] Cleanup: destroyed a window
[LOG] cursorImage request: surface 5b22358b1790
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 334
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 334
[ERR] CPopup: orphaned (no surface/resource) and unmaps??
[LOG] CWLSurface 5b2235919d90 called destroy()
[LOG] cursorImage request: surface 5b22358b1790
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 334
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 334
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 333
[LOG] [seatmgr] Rejecting a setCursor because the client ain't in focus
[LOG] [AQ] [libinput] event5  - debounce state: DEBOUNCE_STATE_IS_UP → DEBOUNCE_EVENT_OTHERBUTTON → DEBOUNCE_STATE_IS_UP

[LOG] [AQ] [libinput] event5  - debounce state: DEBOUNCE_STATE_IS_UP → DEBOUNCE_EVENT_PRESS → DEBOUNCE_STATE_IS_DOWN_WAITING

[LOG] [hookSystem] New hook event registered: mouseButton
[LOG] [AQ] [libinput] event5  - debounce state: DEBOUNCE_STATE_IS_DOWN_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_DOWN

[LOG] [AQ] [libinput] event5  - debounce state: DEBOUNCE_STATE_IS_DOWN → DEBOUNCE_EVENT_RELEASE → DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS

[LOG] [AQ] [libinput] event5  - debounce state: DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS → DEBOUNCE_EVENT_TIMEOUT_SHORT → DEBOUNCE_STATE_IS_UP_WAITING

[LOG] [AQ] [libinput] event5  - debounce state: DEBOUNCE_STATE_IS_UP_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_UP

[LOG] Keybind triggered, calling dispatcher (64, , 114)
[LOG] Executing wofi --show drun
[LOG] Process Created with pid 1859
[LOG] [WLDataDevice] New datamgr resource bound at 5b22359315c0
[LOG] [PrimarySelection] New primary_seletion_manager at 5b2235925860
[LOG] [WLSHM] Resizing a SHM pool from 2304 to 8704
[LOG] [WLSHM] Resizing a SHM pool from 8704 to 21504
[LOG] [WLSHM] Resizing a SHM pool from 21504 to 47104
[LOG] [WLSHM] Resizing a SHM pool from 47104 to 98304
[LOG] [WLSHM] Resizing a SHM pool from 98304 to 200704
[LOG] [WLSHM] Resizing a SHM pool from 200704 to 405504
[LOG] [WLSHM] Resizing a SHM pool from 405504 to 815104
[LOG] [WLSHM] Resizing a SHM pool from 815104 to 1634304
[LOG] [WLSeat] New seat resource bound at 5b2235986920
[LOG] [WLCompositor] New wl_surface with id 20 at 5b2235938ea0
[LOG] [PrimarySelection] New primary selection data device bound at 5b223570c380
[LOG] [WLDataDevice] New data device bound at 5b22359226a0
[LOG] [WLCompositor] New wl_surface with id 23 at 5b2235920580
[LOG] [XDGShell] New xdg_wm_base at 5b223570e650
[LOG] [WLCompositor] New wl_surface with id 28 at 5b2235920060
[LOG] CWLSurface 5b223582c310 called init()
[LOG] LayerSurface 5b22368c05f0 (namespace wofi layer 2) created on monitor eDP-1
[LOG] [LayerShell] New wlr_layer_surface 5b22368c05f0
[LOG] [TextInputV3] New tiv3 at 00005b2235866480
[LOG] [WLCompositor] New wl_region with id 40 at 5b2235920df0
[LOG] LayerSurface 5b22368c05f0 mapped
[LOG] Set keyboard focus to surface 5b2235920060

**Comment by izmyname** [comment]
https://github.com/hyprwm/Hyprland/issues/7025

Try to rebuild to the latest-git.
