### ISSUE TITLE
Misaligned hardware cursor shapes with AQ_NO_ATOMIC=1

### ISSUE THREAD

**Issue by shezdy** [hyprwm/Hyprland#7033]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit a0be3de0e89f42b98d00bf0d87ad10af843d58d6  (keybinds: handle monitor change in moveWindowIntoGroup (7030)).
Date: Wed Jul 24 12:00:25 2024
Tag: v0.41.2-91-ga0be3de0, commits: 4977

flags: (if any)


System Information:
System name: Linux
Node name: plant
Release: 6.10.0-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000


GPU information: 
2d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprsplit by shezdy ver 1.0
```

</details>

### Description

~Since aq some cursor shapes are misaligned, including `crosshair` and `text` shapes (maybe others?) when using hardware cursors. The point clicked should be in the middle on these shapes, but is actually at the top left.~

With hardware cursors and AQ_NO_ATOMIC=1, cursors are misaligned, with the actual point clicked being up and to the left of the shape. Some shapes are affected more than others.

### How to reproduce

`slurp` with hardware cursors enabled, move cursor to top left of screen and notice how the crosshair's center is down and to the right of where it should be. Disable hardware cursors, do the same, and the cursor will be in the correct location. Can also be noticed when dragging to select text with the i-beam.

**Comment by vaxerski** [comment]
xcursor or hyprcursor

**Comment by shezdy** [comment]
After some more testing it appears that ALL shapes (some shapes more than others) are misaligned with hardware cursors enabled and AQ_NO_ATOMIC=1. It doesn't happen without AQ_NO_ATOMIC=1. xcursor/hyprcursor makes no difference

**Comment by vaxerski** [comment]
aq bug then, and I frankly dont care that much, legacy is buggy
