### ISSUE TITLE
Graphical glitches on NVIDIA 1050ti

### ISSUE THREAD

**Issue by CaneMandarinesco** [hyprwm/Hyprland#704]
i keep getting very rarely some black lines appearing on the screen, that last just for a few milliseconds (sometimes it happens to the whole screen). 
i followed the nvidia guide on the wiki, tried enabling performance mode but did not solve the problem.
with sway i don't have this problem, it works fine.

some gpu info:
```
01:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ZOTAC International (MCO) Ltd. Device a454
	Flags: bus master, fast devsel, latency 0, IRQ 125
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```

**Comment by vaxerski** [comment]
every nvidia graphical glitch is out of my reach. Try the nvidia patches to wlroots (provided in the nixos flake, you can also join the discord server and ask there)
