### ISSUE TITLE
[NVIDIA?] Hyprland fails to render to the screen

### ISSUE THREAD

**Issue by a-usr** [hyprwm/Hyprland#7045]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4c3b03516209a49244a8f044143c1162752b8a7a  ().
Date: 2024-07-22
Tag: , commits: 4c3b03516209a49244a8f044143c1162752b8a7a

flags: (if any)


System Information:
System name: Linux
Node name: silenos
Release: 6.6.41
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu Jul 18 11:21:27 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] [10de:2504] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  555.42.02  Mon May 13 17:24:29 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240721.63d37cc"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
  hy3 by outfoxxed ver 0.1

======Config-Start======


Config File: /home/usr/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/g56mlyricr13dqsra9ag6kh8m5v66r70-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/pvv73fhscknd4fkircwk8d8x9mks8bs6-hy3-hl0.41.2/lib/libhy3.so
$mod=SUPER
animations {
  bezier=myBezier, 0.05, 0.9, 0.1, 1.05
  animation=windows, 1, 5, myBezier
  animation=windowsOut, 1, 5, default, popin 80%
  animation=border, 1, 5, default
  animation=borderangle, 1, 8, default
  animation=fade, 1, 7, default
  animation=workspaces, 1, 6, default
  animation=specialWorkspace, 1, 3, default, slidevert
}

debug {
  disable_logs=false
}

decoration {
  blur {
    enabled=true
    passes=1
    size=5
    vibrancy=0.169600
  }
  rounding=5
}

general {
  layout=hy3
}

input {
  kb_layout=de
}
bind=$mod SHIFT, Left, hy3:movewindow, l
bind=$mod SHIFT, Right, hy3:movewindow, r
bind=$mod SHIFT, Up, hy3:movewindow, u
bind=$mod SHIFT, Down, hy3:movewindow, d
bind=$mod, Left, hy3:movefocus, l
bind=$mod, Right, hy3:movefocus, r
bind=$mod, Up, hy3:movefocus, u
bind=$mod, Down, hy3:movefocus, d
bind=$mod, X, hy3:makegroup, h
bind=$mod SHIFT, X, hy3:makegroup, v
bind=$mod, escape, exec, ags --toggle-window powermenu
bind=$mod, F, exec, chromium
bind=, Print, exec, grimblast copy area
bind=$mod, M, exit
bind=$mod, T, exec, alacritty
bind=$mod, Q, killactive
bind=ALT, space, exec, ags --toggle-window launcher
bind=$mod SHIFT, S, exec, grim -g "$(slurp)"  - | tee >(wl-copy) >(swappy -f -)
bind=SUPER_SHIFT, C, exec, cliphist list | wofi --show=dmenu | cliphist decode | wl-copy
bind=$mod, 1, workspace, 1
bind=$mod SHIFT, 1, movetoworkspace, 1
bind=$mod, 2, workspace, 2
bind=$mod SHIFT, 2, movetoworkspace, 2
bind=$mod, 3, workspace, 3
bind=$mod SHIFT, 3, movetoworkspace, 3
bind=$mod, 4, workspace, 4
bind=$mod SHIFT, 4, movetoworkspace, 4
bind=$mod, 5, workspace, 5
bind=$mod SHIFT, 5, movetoworkspace, 5
bind=$mod, 6, workspace, 6
bind=$mod SHIFT, 6, movetoworkspace, 6
bind=$mod, 7, workspace, 7
bind=$mod SHIFT, 7, movetoworkspace, 7
bind=$mod, 8, workspace, 8
bind=$mod SHIFT, 8, movetoworkspace, 8
bind=$mod, 9, workspace, 9
bind=$mod SHIFT, 9, movetoworkspace, 9
bind=$mod, 0, workspace, 10
bind=$mod SHIFT, 0, movetoworkspace, 10
bind=, F1, togglespecialworkspace, E
bindi=, code:122, exec, pamixer -d 5
bindi=, code:123, exec, pamixer -i 5
bindi=, code:173, exec, playerctl previous
bindi=, code:171, exec, playerctl next
bindi=, code:172, exec, playerctl play-pause
bindm=$mod, mouse:274, movewindow
bindm=$mod, mouse:272, resizewindow
env=XDG_CACHE_DIR,/home/usr/.cache/
env=XDG_CONFIG_HOME,/home/usr/.config/
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=NIXOS_OZONE_WL,1
exec-once=hyprpaper
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=ags
monitor=Unknown-1, disable
windowrule=fullscreen, title:(HELLDIVERS™ 2)
windowrule=fullscreen, title:(Titanfall 2)
windowrulev2=workspace special:E silent, class:(vesktop)

======Config-End========


```

</details>

### Description

On Hyprland at 33a5c8ce325e1657ec5571b57e05c6378706f4cd and Aquamarine at https://github.com/hyprwm/Aquamarine/commit/353dc1b7299d43f08de44276b93ae32726ff9d70 Im getting a blackscreen upon starting hyprland. But apart from that at the very least keybinds work perfectly fine (I bound mod+m to close hyprland and It did that successfully). 

Yes, I am aware that the mentioned commit does not match the commit stated by `hyprctl systeminfo -c`, Im currently using the version I used before attempting to update.

### How to reproduce

0. Use a Nvidia RTX 3060 with the 555 beta driver and be in a dark room
1. Build hyprland from 33a5c8ce325e1657ec5571b57e05c6378706f4cd
2. Start Hyprland from a regular `getty` tty
3. Experience blindness

### Crash reports, logs, images, videos

Here is a log that I copied while the Instance that it belonged to was still running:
[hypr_bad.txt](https://github.com/user-attachments/files/16381961/hypr_bad.txt)

**Comment by vaxerski** [comment]
please get a trace log (HYPRLAND_TRACE=1 AQ_TRACE=1)

**Comment by a-usr** [comment]
> please get a trace log (HYPRLAND_TRACE=1 AQ_TRACE=1)

I will, but it wont be until in  ~19 hours before I can get to my system

**Comment by stottm** [comment]
I encountered this on NixOS 24.11 unstable w/Hyprland flake.  Latest Nvidia Driver Version: 555.58.02 RTX-4090 and kernel 6.10.0.  I had to revert to the previous derivation to recover.  Starting Hyprland results in a black screen, no mouse but keyboard works as Super + M will logout to SDDM.  I will attempt again and capture logs when I have the time.

**Comment by UjinT34** [comment]
Some AQ versions might return incorrect cursor buffer for nvidia. Try with `cursor:no_hardware_cursors = true`

**Comment by a-usr** [comment]
> Some AQ versions might return incorrect cursor buffer for nvidia. Try with `cursor:no_hardware_cursors = true`

Its not the cursor, According to the logs hyprland fails to modeset the Output

**Comment by a-usr** [comment]
@vaxerski here is your log: 
[hypr_bad_2.txt](https://github.com/user-attachments/files/16395143/hypr_bad_2.txt)
Both hyprland and aquamarine are at the same commit as stated in the description

**Comment by a-usr** [comment]
In the meantime I'll start bisecting aquamarine

**Comment by a-usr** [comment]
https://github.com/hyprwm/aquamarine/commit/744a383a52048485445d8b34570dd9b5d3fb28bb: bad
[hypr_bad_3.txt](https://github.com/user-attachments/files/16395213/hypr_bad_3.txt)

**Comment by a-usr** [comment]
actually I probably dont need to send every log

**Comment by UjinT34** [comment]
`[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 256, y: 256] and format AR24 with modifier 216172782120099860 aka BLOCK_LINEAR_2D,HEIGHT=4,KIND=6,GEN=2,SECTOR
=1,COMPRESSION=0`

Just set `cursor:no_hardware_cursors = false`

**Comment by a-usr** [comment]
ok, how the fuck does hardware cursors and modesetting the output relate to each other aside from the fact that both operations interact with the video driver

**Comment by a-usr** [comment]
please explain

**Comment by UjinT34** [comment]
Incompatible HW cursor buffer is committed with other frame stuff

**Comment by a-usr** [comment]
and the hw cursor buffer is then passed as an argument to `drmModeAtomicCommit` ?

https://github.com/hyprwm/aquamarine/blob/f95d1509370b7f40ef356ff69a332bd0356ab044/src/backend/drm/impl/Atomic.cpp#L162-L166

Also, I found that the last good Aquamarine commit is https://github.com/hyprwm/aquamarine/commit/07eb70afb131a4450aa01f5b488228c4cce6892b

**Comment by a-usr** [comment]
amdeeznuts

**Comment by stottm** [comment]
Confirmed, setting in hyprland.conf resolved it for me. Think I removed the setting as it had no effect on earlier versions.  Perhaps default to this value if Nvidia?  I noticed the env var method was depreciated. 

```
cursor {
    no_hardware_cursors = true
}
```

**Comment by a-usr** [comment]
> Confirmed, setting in hyprland.conf resolved it for me. Think I removed the setting as it had no effect on earlier versions.  Perhaps default to this value if Nvidia?  I noticed the env var method was depreciated. 
> 
> ```
> cursor {
>     no_hardware_cursors = true
> }
> ```

I don't think defaulting to software cursors is a good Idea since it shadows any issue that could occur with hardware cursors.

**Comment by vaxerski** [comment]
doesn't look like latest aquamarine. Can you update?

**Comment by a-usr** [comment]
Sure, i'll try it out

**Comment by a-usr** [comment]
The latest aquamarine works, I think https://github.com/hyprwm/aquamarine/commit/0720a5c might have fixed the issue
Closing this as its kinda Irrelevant now, however the flake.lock probably should get updated.

@stottm I recommend you override the aquamarine Input that Hyprland uses until fufexan updates the lockfile again:
```nix
inputs = {
[ ... ]
    aquamarine.url = "github:hyprwm/aquamarine";
    hyprland.url = "git+https://github.com/hyprwm/Hyprland/?submodules=1";
    hyprland.inputs.nixpkgs.follows = "nixpkgs";
    hyprland.inputs.aquamarine.follows = "aquamarine";
[ ... ]
};
```

**Comment by vaxerski** [comment]
@fufexan flake update request thanks
