### ISSUE TITLE
Missing window resize after closing group extern window

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#705]
- open 3 windows
- group 2 of them together
- changegroupactive to show the hidden group window
- focus the non grouped window and close it

The group doesn't get resized to span the whole workspace

**Comment by vaxerski** [comment]
seems like a regression. Can you please tell me when it was introduced? `git bisect` should help.

**Comment by Dickby** [comment]
I'll try!

**Comment by Dickby** [comment]
Is there a way to don't rebuild the whole package every time?

**Comment by vaxerski** [comment]
unfortunately no. However, on arch, usually you only need to rebuild Hyprland itself, not wlroots.

**Comment by Dickby** [comment]
I started doing it manually, is there a way to use makepkg for that?
Everything i tried leads to makepkg checking out main again.

**Comment by vaxerski** [comment]
dont makepkg

clone the repo, do `git reset --hard <hash> && git submodule update --init` and then `sudo make cleaninstall`

**Comment by Dickby** [comment]
This shit is older than pinned windows!

**Comment by Dickby** [comment]
I don't think this makes any sense:
at
bb90ff0 sanity check on last window
the bug isn't there but the same action isn't well defined either.
I doupt that doing exactly what i described above, did work at any time before, but i don't know.

**Comment by Dickby** [comment]
This problem is caused by `CHyprDwindleLayout::applyNodeDataToWindow` if no_gaps_when_only is true.
Theif block starting at line 191 ends with a return statement,
that bypasses the code that deals with groupMembers.
If  I copy the last if block of that method inside the 191 block , this particular problem is solved.
But the thing is still not working properly:

If you follow the reproduction steps of this issue, now the group will resize after closing the group extern window.
But after changegroupactive the group resizes back to the incorrect size.
(This is the behaviour of the main branch without no_gaps_when_only,  so at least now it's consistent)

I could fix that by replacing the warp() calls with assigning goalv() of the former visible group window.
Now the group's size stays, but the hidden group windows are not scaled correctly.

Maybe you can make sense of this!?
Or is the plan to merge https://github.com/hyprwm/Hyprland/pull/593 soon?

**Comment by vaxerski** [comment]
#593 will not be merged any time soon. I'll try to fix this tomorrow. Thanks

**Comment by Dickby** [comment]
@vaxerski did you look into this?

**Comment by vaxerski** [comment]
fixed in da40bf823f2f307e439f4bd85c405d9e612c2df5
