### ISSUE TITLE
Request built-in status bar panel

### ISSUE THREAD

**Issue by DaiwuShen** [hyprwm/Hyprland#7050]
### Description

At present, the main functions of Hyprland are quite user-friendly, balancing aesthetics and convenience very well. But there is no built-in status bar, instead software like Waybar is used to provide relevant functions. On the one hand, configuring waybar software is quite troublesome and not aesthetically pleasing (even after configuration), with relatively few functions. So I hope to have a built-in status bar that matches Hyprland, similar to the kde panel.

**Comment by a-usr** [comment]
And how exactly do you imagine such a status bar in hyprland would be configured?

**Comment by a-usr** [comment]
I'd also like to add that personally, Hyprland doesnt need an integrated status bar. There are many options already out there, from the already mentioned waybar, over EWW with its own configuration format, to AGS, which is configured in JavaScript ( Or Typescript, if you use a TS preprocessor ). If you still want a solution that is more tightly integrated with Hyprland, and you know C++, you can also write a plugin for Hyprland.

**Comment by fufexan** [comment]
Won't be implemented, as there already are a plethora of bars. You can find more, aside from the already-mentioned ones, using GitHub Search https://github.com/search?q=wayland+bar&type=repositories.

**Comment by terminal-enlightenment** [comment]
If you prefer having everything set up for you, use the nwg-shell package and you'll have a nice-looking psuedo desktop environment running on hyprland in a few minutes (has a panel, bar, app drawer, widgets, etc). I don't use them but I admire the project and follow all the package updates - helpful for learning about gtk.
