### ISSUE TITLE
Nvidia support regarding open source kernel modules?

### ISSUE THREAD

**Issue by Eclextic** [hyprwm/Hyprland#7053]
Will Hyprland support the Nvidia open source kernel modules? I think we can forget the proprietary drivers, but as the open-source drivers for newer generation GPUs have come out as the new and recommended default for Ada Lovelace, Turing, and Ampere, I think the possibility of support should start to be considered.

**Comment by UjinT34** [comment]
There is no difference between open-source and proprietary modules from HL's perspective

**Comment by izmyname** [comment]
What do you mean by support, though? Nvidia has always been supported - look at the commits and nvidia-related issues.

**Comment by izmyname** [comment]
Also, nvidia-open doesn't support rtd3 on Turing gpus, so no.

**Comment by vaxerski** [comment]
what @izmyname said, basically.

Officially supported - no. Two reasons:
 - I don't have an nvidia card
 - The kernel modules mean jack shit. All the implementations that are a notorious buggy mess are in the userspace driver, which remains FOSS.

Please, please, please _*stop*_ calling the nvidia drivers "open source". They are absolutely not, only the kernel modules are, which is like 20% of the driver.

**Comment by vaxerski** [comment]
I still try to provide the best support regardless of the gpu - but I can't _guarantee_ anything, esp with nv.

**Comment by Eclextic** [comment]
> what @izmyname said, basically.
> 
> Officially supported - no. Two reasons:
> 
> * I don't have an nvidia card
> * The kernel modules mean jack shit. All the implementations that are a notorious buggy mess are in the userspace driver, which remains closed source.
> 
> Please, please, please __stop__ calling the nvidia drivers "open source". They are absolutely not, only the kernel modules are, which is like 20% of the driver.

While you are right, I kind of assumed native support for e.g. hardware cursor. Anyhow, just a small question, thank you for all your work as always vaxry!
