### ISSUE TITLE
Maximized windows' causes tilling issues.

### ISSUE THREAD

**Issue by Rid1FZ** [hyprwm/Hyprland#7058]
### Regression?

No

### System Info and Version
```
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.8.10-300.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Fri May 17 21:20:54 UTC 2024


GPU information:


os-release: NAME="Fedora Linux"
VERSION="40 (Forty)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Forty)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13

Plugins:

```

### Description

When any window is maximized using windowrule, this causes some tilling issues. Firstly, if more than two windows is opened in the same workspace, opening any window with maximize rule causes all of the other windows to be maximized as well. Secondly, if any of the other windows is closed, the window with maximize rule tiles automatically.

### How to reproduce

1. set the maximize rule for any window(e.g: Zathura)
2. open more than two windows in the same workspace which doesn't have the maximize or float rule set
3. now open that window with maximize rule
4. use keybinding to focus any other window.
5. close any of the windows which doesn't have maximize or float rule

from the above steps, step 3 causes all of the windows (without maximize rule) to be maximized. You can confirm that by focusing other window using keybinding. Step 5 causes all of the opened windows to tile (window with maximize rule is also included). I tried using both master and dwindle layouts, but the result was the same.

**Comment by romanstingler** [comment]
please update Hyprland first, your version is from April

**Comment by Rid1FZ** [comment]
@romanstingler just updated hyprland to 41.2. the issue still exists.

**Comment by MightyPlaza** [comment]
What is the issue?
How would you expect it to work?

**Comment by Rid1FZ** [comment]
@MightyPlaza I expect that:

1. When I open any windows with `maximize rule`, other tilling windows will not be maximized. I didn't wanted them to be maximized, so there is no rule set for them.
2: when I close any of the non maximized windows, this must not cause the maximized window to tile. Because the only way to maximize that window again is to close and open that window (I couldn't found any keybinding option to maximize windows)

The second behavior is considerable as the `maximize rule` is a static rule. But the first behavior seems like a bug to me.

**Comment by Rid1FZ** [comment]
@MightyPlaza I expect that:

1. When I open any windows with `maximize rule`, other tilling windows will not be maximized. I didn't wanted them to be maximized, so there is no rule set for them.
2: when I close any of the non maximized windows, this must not cause the maximized window to tile. Because the only way to maximize that window again is to close and open that window (I couldn't found any keybinding option to maximize windows)

The second behavior is considerable as the `maximize rule` is a static rule. But the first behavior seems like a bug to me.

**Comment by MightyPlaza** [comment]
for 1 you have `misc:new_window_takes_over_fullscreen` to set whether or not maximized should be removed when opening another window
for 2 you're supposed to toggle maximize with `hyprctl dispatch fullscreen 1` not set maximized for the entire lifetime of a program at start

**Comment by Rid1FZ** [comment]
`misc:new_window_takes_over_fullscreen` changes the behavior if I open *maximized* window first, then I open any tilled window. But the issue I described occurs when I open some tilled windows first, then open any *maximized* window. They are not same.

I will consider the second issue not to be an issue as I was unaware of this dispatcher. But the 1st issue is still here...

**Comment by MightyPlaza** [comment]
> `misc:new_window_takes_over_fullscreen` changes the behavior if I open _maximized_ window first, then I open any tilled window. But the issue I described occurs when I open some tilled windows first, then open any _maximized_ window. They are not same.

the other windows should be covered by the maximized one
are you talking about when you use the `movefocus` dispatcher? if so what behaviour were you expecting?

**Comment by Rid1FZ** [comment]
@MightyPlaza I am specifically talking about how it is treating any tilling windows if I open any `maximized` window. If I already have ***more than one*** tilling windows opened, then if I open any `maximized` window, that maximized window causes all those previously opened `tilling` windows to be `maximized` as well even though none of them have the `maximize` rule set. For me, it is a bug, as the `maximized` window is causing other `tilling` windows to maximize.

**Comment by MightyPlaza** [comment]
> @MightyPlaza I am specifically talking about how it is treating any tilling windows if I open any `maximized` window. If I already have _**more than one**_ tilling windows opened, then if I open any `maximized` window, that maximized window causes all those previously opened `tilling` windows to be `maximized` as well even though none of them have the `maximize` rule set. For me, it is a bug, as the `maximized` window is causing other `tilling` windows to maximize.

wdym, how can you tell they're all maximized if you can only see the one that is maximized?

**Comment by Rid1FZ** [comment]
let's say I have more than one tilling windows opened. How can I say that they are tilling? Obviously each one is talking a portion of the screen and I can see all of them together side by side. Right?
![image](https://github.com/user-attachments/assets/58d50356-eb3e-4dd2-b316-7e33dd985f5a)

Now how can I say that they were maximized? I was able to see them side by side before opening any `maximized` windows. As soon as I open any maximized windows, I no longer can see them side by side. Now each of them taking up the whole screen even though `hyprctl clients` is saying they are not maximized. My question is, If I have more than one `unmaximized` windows is opened in the same workspace, why aren't they tilling? Why are they taking up the whole screen and behaving as if they were `maximized` windows?

**Comment by MightyPlaza** [comment]
the point of maximizing a window is to have it cover the whole workspace
almost like fullscreen but you keep your bar, border, gaps, etc

you can't have more than one maximized window at each time
not sure what you're trying to do, but the moment you maximize a window if there is another maximized window in the workspace it will get it's maximized state removed

**Comment by Rid1FZ** [comment]
> you can't have more than one maximized window at each time

I already said this in the description:
1. create more than one `tilling` windows
2. create one `maximized` windows
3. use keybinding to cycle through all the opened windows

let's say I have two tilling windows opened side by side. One is `terminal1`, another one is `terminal2`. None of them have the window rule `maximize` set. So each of them is taking half of the screen in dwindle layout (i.e: `terminal1=50%`, `terminal2=50%`). Now let's open any window which has `maximize` rule set. Let's say it is `brave1`. As it has the `maximize` rule, it will obviously take 100% of the screen. so `brave1=100%`. Now let's move our focus to any of those previously opened tilling windows using `hyprctl dispatch movefocus ...`. Let's say we focus `terminal1`. Now you will see that `terminal1` is taking 100% of the screen. Previously it was `terminal1=50%`, now it is `terminal1=100%`. Now again use `hyprctl dispatch movefocus ...` and focus `terminal2`. It will also be taking 100%. Previously it was `terminal2=50%`, now it is `terminal2=100%`. My question is why opening `brave1` caused `terminal1` and `terminal2` to go from 50% to 100%? Aren't they tilling? If they are tilling, they must have been taking 50% each, not 100%.

**Comment by MightyPlaza** [comment]
no, when you move focus and have a fullscreen or maximized window it will unfullscreen/unmaximize it and fullscreen/maximized the next window to focus
there are already suggestions for different behaviour like https://github.com/hyprwm/Hyprland/issues/6564, so using the dispatcher would change the focus to another monitor and not the fullscreened/maximized window in that monitor
still not sure how would you expect it to work

**Comment by Rid1FZ** [comment]
@MightyPlaza I got the problem. It is not any bug, but an intended behaviour. Thanks for your time. I am closing this issue as completed...
