### ISSUE TITLE
After aquamarine kanshi does not work well

### ISSUE THREAD

**Issue by leiserfg** [hyprwm/Hyprland#7059]
### Regression?

Yes

### System Info and Version

Nixos with hyprland compiled from https://github.com/hyprwm/Hyprland/commit/57371b93a058d17affb0ca92f13b8d40582b3ea0

### Description

I use hyprland with kanshi (basically to turn off the laptop screen whenever I connect it to an external monitor). After aquamarine that does not work well, if I run `hyprctl monitors` it only shows the active (external) monitor as it should, but the laptop screen is still on (just not getting new frames). Disconnecting the external monitor (which should restart the laptop screen) crashes hyprland.

Besides that, the cursor looks tiny in apps not based in gtk  (looks fine in firefox and waybar, but wrong in the wallpaper and kitty).

Those issues don't happen in `0.41.2+date=2024-07-20_f642fb9`.

### How to reproduce

In case it matters, I'm using a framework13 with AMD igpu.

**Comment by leiserfg** [comment]
I also noticed that the screen turns white when hyprland starts (maybe it happens when kanshi rule gets applied).

**Comment by vaxerski** [comment]
where crash report

**Comment by mauricekraus** [comment]
@leiserfg, regarding the white flashing this is a dupe: https://github.com/hyprwm/Hyprland/issues/6950

**Comment by leiserfg** [comment]
I'm testing now in [04b40ea](https://github.com/hyprwm/Hyprland/commit/04b40ea2ec85dd1d74ff18edc046a233b65024ac)
Unplugging the external monitor no longer crashes, but the laptop screen is still on when it should be off (dpms maybe?). Given that it's not crashing I don't have a crash report to send, is there something I can?

**Comment by leiserfg** [comment]
I ran `hyprctl monitors all` and I'm getting:
```
Monitor eDP-1 (ID 0):
	2256x1504@59.99900 at 0x0
	description: BOE 0x0BCA
	make: BOE
	model: 0x0BCA
	serial: 
	active workspace: 0 ()
	special workspace: 0 ()
	reserved: 0 27 0 0
	scale: 1.17
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: true
	currentFormat: XRGB8888
	availableModes: 2256x1504@60.00Hz 2256x1504@48.00Hz 1920x1200@60.00Hz 1920x1080@60.00Hz 1600x1200@60.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz 
```

**Comment by leiserfg** [comment]
Shouldn't `dpmsStatus: 1` be different for eDP-1?

**Comment by 299792458ms** [comment]
@leiserfg Would recommend [shikane](https://gitlab.com/w0lff/shikane) as a better alternative that might solve(or not) the current conflict you are having since I have no problems with it.

**Comment by leiserfg** [comment]
Thanks, I will try it, but IMHO it still needs to be fixed.

**Comment by leiserfg** [comment]
@299792458ms  I tried with `shikane` and got the same problem, but I discovered that if I disable the monitor, by using `wsdisplays` the issue does not happen.

**Comment by 299792458ms** [comment]
@leiserfg It happpened to me now, it does not happen 100% of the time though and it does not crash Hyprland if the cable is removed while the external monitor profile is active.

Ln 503 where profile switches: https://pastebin.com/9d8751aW
Shikane config:  https://pastebin.com/3kx38Xh3
I dont know if this is useful at all.

**Comment by alexandru0-dev** [comment]
same problem here, `hyprctrl` says the monitor is disabled but remains on, seems is unresponsive/cannot switch to that monitor.
Unplugging the external monitor results in a crash as already reported.

@vaxerski here are the [hyprlandCrashReport.txt](https://github.com/user-attachments/files/16472964/hyprlandCrashReport.txt) and the [hyprland.log](https://github.com/user-attachments/files/16472965/hyprland.log)

**Comment by leiserfg** [comment]
I was reading the code of `kanshi` and `wdisplay` and the only difference I noticed is that the former does not call `wl_display_roundtrip`, but maybe I'm missing something else.

**Comment by alexandru0-dev** [comment]
@leiserfg, after stopping `kanshi` i could use `wdisplay` and get the monitor to shutdown, tho when disabling the laptop monitor, the monitor disabled correctly but I got a:
```sh
Gdk-Message: 21:16:34.347: Lost connection to Wayland compositor.
```
message on `wdisplay` and also the application killed itself

**Comment by leiserfg** [comment]
I'm back in master:
`hyprctl keyword  monitor "eDP-1,disable"` does the same (last frame frozen in the monitor).
The only thing that gets the monitor eDP-1 to turn off is `wdisplays` and it works only sometimes, and crashes right after (regardless of working or not) and I get the same error report as @alexandru0-dev

**Comment by leiserfg** [comment]
@vaxerski  after a painful bisect, seems like this started happening after `d03fa94c2ca1a642959e31adc4fcc2447a3cc623`

**Comment by vaxerski** [comment]
can you post a `WAYLAND_DEBUG=1 wdisplays |& tee ~/wdisplays.log`

**Comment by leiserfg** [comment]
[wdisplays.log](https://github.com/user-attachments/files/16482796/wdisplays.log)

**Comment by leiserfg** [comment]
Disabling eDP-1 with `wdisplays` in master.
[wdisplays.log](https://github.com/user-attachments/files/16482858/wdisplays.log)

**Comment by leiserfg** [comment]
@vaxerski  I reverted  https://github.com/hyprwm/Hyprland/commit/d03fa94c2ca1a642959e31adc4fcc2447a3cc623 locally and now `hyprctl keyword  monitor "eDP-1,disable"`  works fine.

kanshi still freezes the laptop screen if it starts with the login, but if I restart it after it works fine.

**Comment by leiserfg** [comment]
I've just tested `master` again, and now I can describe the issue in more detail:
The problem happens when a program tries to disable `eDP-1` and enable another display when the second display is not fully "available". 
For instance: 
- if I keep the external monitor connected, with kanshi in the config as  `exec-once=kanshi`, and then start the issue happens.  
- if I keep the external monitor connected, with kanshi in the config as  `exec-once=sleep 10 & kanshi`, and then start the issue does happens.  


- but if I keep the external monitor disconnected, with kanshi in the config as  `exec-once=sleep 10 & kanshi`, and then start and after 15s  I plug the external monitor the issue happens.  

It looks like waiting until the monitor is fully "provisioned"  before advertising it could solve the problem but not sure if that is the most correct thing to do.

Given the weirdness of the issue, most probably my bisect was incorrect.

**Comment by aruhier** [comment]
I'll try to give some debug when it will happen again, but it's also something I get quite often on  v0.41.2 with kanshine and shikane on connecting/disconnecting screens through USB-C. So it might not be entirely new.

I didn't try master yet (libinput 1.26 is not shipped on my distro yet, a requirement for aquamarine).

**Comment by leiserfg** [comment]
In  v0.41.2 I have seen crashes when disconnecting a monitor, but never when connecting.

**Comment by aruhier** [comment]
It's true, for me I think it only happens when connecting because the screen state flickers. Anyway, I'll post a debug log to see if it's related.

**Comment by leiserfg** [comment]
@vaxerski any pointer on where to look, I can try to fix it myself but I'm very rusty at C++ and don't know where to look at. Gosh, 0.42.0 is out already and this is still broken 😢

**Comment by vaxerski** [comment]
we can't fix all bugs ever before releasing any update

**Comment by leiserfg** [comment]
I know, and I think it was a smooth one given the number of changes. Is just that this one issue is very annoying, I have to turn on and off the laptop screen many times a day.

**Comment by Vladimir-csp** [comment]
An option to disable continuous monitor handling on hyprland's side would be handy. Otherwise hyprland and kanshi try doing different things.

**Comment by leiserfg** [comment]
@Vladimir-csp I'm not sure that's a good idea, every other wm (pre-aquamarine hyprland included) can handle that. Also, whatever breaks this also breaks `wdisplays` and potentially changing monitor rules on the fly.

**Comment by Vladimir-csp** [comment]
Sorry for offtopic, I meant that for avoiding situations when hyprland autoenables output that kanshi then switches off. Lots of flicker and workspaces flying around for nothing.

**Comment by Vladimir-csp** [comment]
Concocted a hyprland-native pattern-matching output manager:
<details><summary>
Code
</summary>

```
#!/bin/sh

# by https://github.com/Vladimir-csp/, WTFPL

# Operates in 'hypr' config dir.
# Expects 'source = monitors.conf' line in hyprland.conf.
# Manages 'monitors.conf'.
# Triggered by 'monitoraddedv2', 'monitorremoved' events on hyprland socket.
#
# Represents currently connected monitors as lines:
#
#   id:N;monitor:Port;description:Description;
#
# Checks 'monitors.d/*.conf' candidates which have at least one regexp or
# substring check defined as lines starting with '#re:' or 'str:':
#
#   #re: some regexp
#   #str: some substring
#
# These are checked against connected monitors representation described above.
# At least one check should be defined, all must match for file to be selected.
#
# The first matched candidate config is linked as 'monitors.conf', then
# 'hyprctl reload' is executed.
#
# If no candidate was matched, 'monitors.d/auto.conf' is selected (generated if
# not found).
#
# Example config:
#
#  # monitors.d/home.conf
#  # External monitor at home
#  #re: description:Dell.*ABCDEFG.*;
#  monitor = ,preferred,auto,1,vrr,2
#  monitor = eDP-1,disable
#  # any other setup-specific configuration

set -e

CONFIG_BASE="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
HYPRSOCKET="UNIX-CONNECT:${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock"
AUTO_PROFILE='monitor = ,preferred,auto,1,vrr,2'
N='
'

get_monitors() {
	# Fills CURRENT_MONITORS var with monitors ids, names, and descriptions
	# initiate config string
	CURRENT_MONITORS=''
	unset CURRENTMON
	while read -r line <&3; do
		case "$line" in
		'Monitor '*:)
			# start new line for new monitor
			if [ -n "${CURRENTMON-}" ]; then
				CURRENT_MONITORS="${CURRENT_MONITORS}${N}"
			fi
			# extract id and monitor
			MONITOR=${line#Monitor }
			ID=${MONITOR#*(ID }
			ID=${ID%):}
			MONITOR=${MONITOR% (*}
			# append to CURRENT_MONITORS
			CURRENT_MONITORS="${CURRENT_MONITORS}id:${ID};monitor:${MONITOR};"
			CURRENTMON=${MONITOR}
			;;
		'description: '*)
			: "${CURRENTMON?Found '$line' outside monitor section}"
			IFS=':' read -r _key value <<- EOL
				$line
			EOL
			read -r value <<- EOL
				$value
			EOL
			CURRENT_MONITORS="${CURRENT_MONITORS}description:${value};"
			;;
		esac
	done 3<<- EOF
		$(LANG=C hyprctl monitors all)
	EOF
}

select_config() {
	# Finds configs in monitors.d which have #re: or #str:
	# conditions that all match against CURRENT_MONITORS
	# default:
	CONF_FILE='monitors.d/auto.conf'
	for file in monitors.d/*.conf; do
		# skip auto.conf
		case "$file" in
		monitors.d/auto.conf) continue ;;
		esac

		echo "Considering: ${file#*/}"
		match=false
		while read -r line <&3; do
			case "$line" in
			'#re:'*)
				# drop prefix
				re=${line#"#re:"}
				# strip whitespace
				read -r re <<- EOF
					$re
				EOF
				echo "Matching regexp: $re"
				if echo "$CURRENT_MONITORS" | grep -qEe "$re"; then
					match=true
				else
					match=false
					break
				fi
				;;
			'#str:'*)
				# drop prefix
				str=${line#"#str:"}
				# strip whitespace
				read -r str <<- EOF
					$str
				EOF
				echo "Matching substring: $str"
				case "$CURRENT_MONITORS" in
				*"$str"*) match=true ;;
				*)
					match=false
					break
					;;
				esac
				;;
			esac
		done 3< "$file"
		case "$match" in
		true)
			echo Matched
			CONF_FILE=$file
			break
			;;
		*)
			echo Rejected
			;;
		esac
	done
}

cd "$CONFIG_BASE"
echo "Operating in: '$CONFIG_BASE'"

mkdir -pv monitors.d

if [ ! -f monitors.d/auto.conf ]; then
	echo "$AUTO_PROFILE" > monitors.d/auto.conf
	echo "Created default 'monitors.d/auto.conf'"
fi

# check for socket
if [ ! -S "${HYPRSOCKET#UNIX-CONNECT:}" ]; then
	echo "Socket '$HYPRSOCKET' not found!" >&2
	exit 1
fi

# check hyprland.conf for proper source keyword
if [ ! -f hyprland.conf ]; then
	echo "'hyprland.conf' not found!" >&2
	exit 1
fi

SOURCED_MON=false
while IFS='=' read -r keyword value; do
	# strin whitespace
	read -r keyword <<- EOF
		$keyword
	EOF
	read -r value <<- EOF
		$value
	EOF
	case "${keyword}=${value}" in
	'source=monitors.conf')
		SOURCED_MON=true
		break
		;;
	esac
done < hyprland.conf

case "$SOURCED_MON" in
true) true ;;
*)
	echo "No 'source = monitors.conf' in hyprland.conf" >&2
	exit 1
	;;
esac

# main event cycle
socat -U - "$HYPRSOCKET" |
	while IFS='>' read -r EVENT _empty CONTENT; do
		case "$EVENT" in
		monitoraddedv2 | monitorremoved)
			# skip headless monitor events
			case "$CONTENT" in
			*HEADLESS*) continue ;;
			esac

			echo "Triggered by: ${EVENT}>>$CONTENT"
			get_monitors
			echo "Current configuration:"
			echo "$CURRENT_MONITORS"

			select_config
			if [ "${CONF_FILE}" != "$(readlink monitors.conf)" ]; then
				echo "Applying config: ${CONF_FILE#*/}"
				ln -sf "$CONF_FILE" monitors.conf
				sleep 1
				hyprctl reload
			else
				echo "Config '${CONF_FILE#*/}' already applied"
			fi

			;;
		esac
	done
```

</details>

It does not crash hyprland, but weird things happen when switching: waybar is duplicated/triplicated (fixed by reload), and visible windows sometimes crash.

**Comment by leiserfg** [comment]
@Vladimir-csp If you are going that route, it's better to call `hyprctl keyword monitor ...` than to patch the config, I'm thinking of doing the same until some caritative soul takes care of the real problem.

**Comment by Vladimir-csp** [comment]
> @Vladimir-csp If you are going that route, it's better to call `hyprctl keyword monitor ...` than to patch the config, I'm thinking of doing the same until some caritative soul takes care of the real problem.

This would not survive the next reload.

**Comment by 299792458ms** [comment]
> > @Vladimir-csp If you are going that route, it's better to call `hyprctl keyword monitor ...` than to patch the config, I'm thinking of doing the same until some caritative soul takes care of the real problem.
> 
> This would not survive the next reload.

One can restart only the configuration file with `hyprctl reload config-only`. Maybe it could work that way?

I have it like this:

```
bind = $mod SHIFT, R, exec, hyprctl reload config-only; notify-send "hyprctl" "restarted (config only)" -i ~/Pictures/icons/hypr_logo.svg -t 2000
bind = $mod SHIFT CTRL, R, exec, hyprctl reload; notify-send "hyprctl" "restarted" -i ~/Pictures/icons/hypr_logo.svg -t 2000
```

**Comment by leiserfg** [comment]
I'm currently doing 
```
bind = $mod, S, exec, sh -c "hyprctl monitors | grep eDP-1 &&  hyprctl keyword monitor eDP-1,disable || hyprctl keyword monitor eDP-1,preferred,auto,auto"
```
To just toggle the laptop screen.

**Comment by vaxerski** [comment]
please check out https://github.com/hyprwm/Hyprland/pull/7571

**Comment by leiserfg** [comment]
@vaxerski  I think this is linked to the problem of FallbackMonitor not working correctly either (even without an external displays manager).

**Comment by levnikmyskin** [comment]
I think that's happened in the past already. If that's really the problem it shouldn't be too hard to fix. I'll look into it eventually, but not in these next days

**Comment by leiserfg** [comment]
I forwarded the comments from [Hendrik Wolff](https://gitlab.com/w0lff) to vaxry and that helped him fix the issue in https://github.com/hyprwm/Hyprland/pull/7571 so it seems this can be closed soon.
