### ISSUE TITLE
Framepacing Issues Since Aquamarine Merge

### ISSUE THREAD

**Issue by dotaxis** [hyprwm/Hyprland#7063]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>
Issue present on latest commit: 57371b93a058d17affb0ca92f13b8d40582b3ea0
Not present on: f642fb97df5c69267a03452533de383ff8023570
Did not try any versions in between as I just wanted to play my game lol but I'm happy to help narrow this down further
</details>

### Description

Something is amiss with frames being drawn to the screen. Certain groups of frames are drawn several times in a row,causing a stuttering effect in Elden Ring, but the stutter is not present in recordings when gameplay is captured via obs-vkcapture.

I tried different proton versions, disabling tearing and immediate window rules (I have them both enabled usually), and running the game without feral gamemode or obs-gamecapture running. The issue is present under all conditions. Rolling back to the last commit before the aquamarine merge makes the problem disappear so it's definitely a regression.

### How to reproduce

1. Install hyprland
2. Run game
3. ???
4. Profit

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/18867845-5a2f-4283-afea-66ddff85b98c

This was captured using PipeWire screen capture since obs-vkcapture produced footage without the stutter.

The stutter in this particular clip may have been caused by some combination of using PipeWire and the notification that popped up, but this is the closest I could get to a recording of what actually happens. The stutter is not quite as egregious as what's seen in this clip but it is still quite noticeable and very annoying. It seems to trigger during specific attack animations and only last for a few seconds each time it happens, but it's really hard to confirm that since I can't get a proper video of it.

**Comment by ikalco** [comment]
its probably #6964 and #6980

**Comment by vaxerski** [comment]
yes
