### ISSUE TITLE
Blur doesn't behave as expected

### ISSUE THREAD

**Issue by OBueckert** [hyprwm/Hyprland#707]
This is not necessarily a bug. It is simply invalid behaviour. I am also using an NVidia GPU (GTX 1060 3GB), that you say is not officially supported by Hyprland, however, this issue might not caused by this.

**Steps to reproduce:**
Enable blur with any blur_size or any amount of blur_passes.

**Expected outcome:**
Blur effect to be applied to windows.

**Noted outcome:**
Blur has little effect on the window. Does not appear as it should.

**Examples:**
blur_size:2
blur_passes:2
![image](https://user-images.githubusercontent.com/82766936/191645573-aafe4667-7af9-4108-ae6b-c6a495dd2ff0.png)

blur_size:10
blur_passes:4
![image](https://user-images.githubusercontent.com/82766936/191645691-e3f90470-65b8-45d1-83bd-a1b4ca8c6b7e.png)

Could this be a shader issue? Some GL extension that is not supported? A configuration issue?

**Comment by taylor85345** [comment]
It looks to me like you are applying your transparency via a windowrule in your hyprland.conf. Blur doesn't apply by default to windows using the opacity windowrule, and if you have transparency set in your terminal config as well you can wind up with the weird partial blur you are experiencing. 

You will need to add `decorations:blur_ignore_opacity=1` to your config to get proper blur with the windowrule. That said, I would highly recommend bypassing the opacity windowrule wherever possible and instead setting your opacity in the terminal's config.

For the record I use a 1660Ti, and I know we have a handful of 1060 users in the community, and I can confirm that the blur shader works fine with every nvidia card I've encountered.

**Comment by OBueckert** [comment]
Thanks, just setting `decorations:blur_ignore_opacity=1` worked.

But then I followed your recommendation on setting the terminal's config rule (I set 'background_opacity 0.8' in my kitty config) instead of this and I found that it didn't actually make the window transparent (it just made it darker). If I force kitty to use XWayland, it works fine. I understand this is more of a kitty and wayland issue, but maybe you had an idea of why it doesn't work?

**Comment by vaxerski** [comment]
probably an issue with your config, as kitty in wl works fine for me with opacity

**Comment by OBueckert** [comment]
I don't know. I've dug through some other people's dotfiles, even copied them entirely and it doesn't make kitty transparent.
![image](https://user-images.githubusercontent.com/82766936/191874244-f9b741d7-f39d-44fd-a53c-0f5658c858bd.png)
I tried enabling transparency with alacritty and there is no problem. I guess I'll have to ask the kitty community because this in no longer a Hyprland issue and the original issue is resolved. Can I close the issue?

**Comment by taylor85345** [comment]
There is an issue with kitty transparency on Nvidia systems that cropped up in the last few weeks. I feel like it may be resolved already, so maybe test `kitty-git` and see if transparency works there.

**Comment by OBueckert** [comment]
Great! I switched to 'kitty-git' and transparency works as expected. Thanks for all the help!

**Comment by 257** [comment]
impressive stuff. would you mind sharing your dotfiles?
