### ISSUE TITLE
Use different animation based on hotkey

### ISSUE THREAD

**Issue by Spiderfffun** [hyprwm/Hyprland#7072]
### Description

Say I had 
bind = SUPER ALT, right, workspace, e+1
bind = SUPER ALT, left, workspace, e-1
which uses the default animation

Then I want to have
bind = SUPER ALT, down, workspace, e+3
bind = SUPER ALT, up, workspace, e-3

but with a different animation (say slidevert for the up/down keys and  slidefade for the left/right keys, or just changing the lenght or bezier)
This could be an additional argument to the dispatchers which can have an animation.
It could also be implemented as an animation switch hotkey, so you could
bind = $mainMod, a, animation, workspaces, 1, 3, workspaceBezier, slidevert
bind = $mainMod SHIFT, a, animation, workspaces, 1, 3, workspaceBezier, slide

**Comment by vaxerski** [comment]
why not just `hyprctl keyword animation '...' && hyprctl dispatch workspace '...'`

**Comment by Spiderfffun** [comment]
for me using hyprctl this way is a little weird, but you are right.
