### ISSUE TITLE
Option to disable activation environment management

### ISSUE THREAD

**Issue by Vladimir-csp** [hyprwm/Hyprland#7083]
### Description

Hi!
Following  #4217, could you please also add an env option `HYPRLAND_NO_SD_VARS` to disable manipulating activation environments, for the same case of delegating it to an external session manager.

Related: if dbus implementation used is `dbus-broker`, there is no need to separately run `dbus-update-activation-environment`, it reuses activation environment of systemd.

**Comment by izmyname** [comment]
> Related: if dbus implementation used is `dbus-broker`, there is no need to separately run `dbus-update-activation-environment`, it reuses activation environment of systemd.

Wait what? If I use Arch with dbus-broker, I don't need it? ```
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
  exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```

P.S I'm sorry for off-topic, but I'm really curious about this.

**Comment by MightyPlaza** [comment]
> > Related: if dbus implementation used is `dbus-broker`, there is no need to separately run `dbus-update-activation-environment`, it reuses activation environment of systemd.
> 
> Wait what? If I use Arch with dbus-broker, I don't need it?
> 
> ```
> exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
>   exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> ```
> 
> P.S I'm sorry for off-topic, but I'm really curious about this.

```cpp
void CCompositor::startCompositor() {
    signal(SIGPIPE, SIG_IGN);

    if (m_pAqBackend->hasSession() /* Session-less Hyprland usually means a nest, don't update the env in that case */) {
        const auto CMD =
#ifdef USES_SYSTEMD
            "systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME PATH XDG_DATA_DIRS && hash "
            "dbus-update-activation-environment 2>/dev/null && "
#endif
            "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME PATH XDG_DATA_DIRS";
        g_pKeybindManager->spawn(CMD);
    }
```

**Comment by izmyname** [comment]
> > > Related: if dbus implementation used is `dbus-broker`, there is no need to separately run `dbus-update-activation-environment`, it reuses activation environment of systemd.
> > 
> > Wait what? If I use Arch with dbus-broker, I don't need it?
> > 
> > ```
> > exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> >   exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
> > ```
> > 
> > P.S I'm sorry for off-topic, but I'm really curious about this.
> 
> ```cpp
> void CCompositor::startCompositor() {
>     signal(SIGPIPE, SIG_IGN);
> 
>     if (m_pAqBackend->hasSession() /* Session-less Hyprland usually means a nest, don't update the env in that case */) {
>         const auto CMD =
> #ifdef USES_SYSTEMD
>             "systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME PATH XDG_DATA_DIRS && hash "
>             "dbus-update-activation-environment 2>/dev/null && "
> #endif
>             "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME PATH XDG_DATA_DIRS";
>         g_pKeybindManager->spawn(CMD);
>     }
> ```

If I understand the code correctly, Hyprland sets those vars for me, sends them to systemctl and dbus, which means I don't need that in my autostart, correct?

**Comment by Vladimir-csp** [comment]
> Wait what? If I use Arch with dbus-broker, I don't need it?

Yes. That's why (and also inability to properly unset vars in original dbus) I do the simplifying [special treatment](https://github.com/Vladimir-csp/uwsm/blob/5d771d1ccf177e335acbbdeafb2eaa83c5a775b0/uwsm/main.py#L929) for it and recommend its usage in [uwsm](https://github.com/Vladimir-csp/uwsm)

> If I understand the code correctly, Hyprland sets those vars for me, sends them to systemctl and dbus, which means I don't need that in my autostart, correct?

Yes. You would need to have `uwsm finalize` in autostart though if you use `uwsm`.
