### ISSUE TITLE
Add 'dim' layerrule with floating value

### ISSUE THREAD

**Issue by izmyname** [hyprwm/Hyprland#7086]
### Description

Would be especially cool for a blurred, transparent waybar.

**Comment by vaxerski** [comment]
what?

**Comment by izmyname** [comment]
E.g

`layerrule = dim 0.8, bar`

And my bar is 80% dimmed

**Comment by vaxerski** [comment]
I getchu now, but fail to see the point? just style your bar in its css

**Comment by izmyname** [comment]
Gtk 3 bad, blur no worky if there's a bar colour.
