### ISSUE TITLE
Bus factor / Long-term sustainability and maintainability

### ISSUE THREAD

**Issue by v-Nyo** [hyprwm/Hyprland#7093]
Are there any concrete plans in case Vaxry steps away from the project?
https://en.wikipedia.org/wiki/Bus_factor

I really love Hyprland and I don't know if I will still have the will to live if it gets abandoned.

**Comment by izmyname** [comment]
> I will still have the will to live
Woah, no need to be so dramatic about a piece of software, even a good one.

**Comment by vaxerski** [comment]
no plans atm

Hope that answers the question
