### ISSUE TITLE
Hyprland crash while playing minecraft

### ISSUE THREAD

**Issue by inmymum** [hyprwm/Hyprland#7113]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
System name: Linux
Node name: archlinux
Release: 6.10.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000


GPU information: 
2b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

While playing minecraft 1.21 with the iris mod and a shader, occasonially hyprland will hang and then crash after about 10 seconds. 

### How to reproduce

play the fabously optimized 6.0.0-beta.2 modpack with the complementary unbound shaderpack for around 10-20 minutes
Random crash

### Crash reports, logs, images, videos

GPU:
	2b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x59f441a89e71]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xb49) [0x59f441a10b09]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x59f441992571]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x712e7612f1d0]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x963f4) [0x712e761883f4]
		??
		??:0
	#5 | /usr/lib/libc.so.6(gsignal+0x20) [0x712e7612f120]
		??
		??:0
	#6 | Hyprland(_ZN15CHyprOpenGLImpl5beginEP8CMonitorRKN9Hyprutils4Math7CRegionEP12CFramebufferSt8optionalIS4_E+0x171) [0x59f441c1ec21]
		CHyprOpenGLImpl::begin(CMonitor*, Hyprutils::Math::CRegion const&, CFramebuffer*, std::optional<Hyprutils::Math::CRegion>)
		??:?
	#7 | Hyprland(_ZN13CHyprRenderer11beginRenderEP8CMonitorRN9Hyprutils4Math7CRegionE11eRenderModeNS2_6Memory14CSharedPointerI9IWLBufferEEP12CFramebufferb+0x34c) [0x59f441c4297c]
		CHyprRenderer::beginRender(CMonitor*, Hyprutils::Math::CRegion&, eRenderMode, Hyprutils::Memory::CSharedPointer<IWLBuffer>, CFramebuffer*, bool)
		??:?
	#8 | Hyprland(_ZN15CHyprOpenGLImpl18makeWindowSnapshotEN9Hyprutils6Memory14CSharedPointerI7CWindowEE+0x32c) [0x59f441c2778c]
		CHyprOpenGLImpl::makeWindowSnapshot(Hyprutils::Memory::CSharedPointer<CWindow>)
		??:?
	#9 | Hyprland(_ZN6Events20listener_unmapWindowEPvS0_+0x3d6) [0x59f441a73ae6]
		Events::listener_unmapWindow(void*, void*)
		??:?
	#1 | Hyprland(+0x20de0b) [0x59f441a5ae0b]
		CWindow::onResourceChangeX11()
		??:?
	#11 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x712e766a5b5f]
		??
		??:0
	#12 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ee) [0x712e766a5ece]
		??
		??:0
	#13 | Hyprland(_ZN16CXWaylandSurface5unmapEv+0x2cc) [0x59f441c56b3c]
		CXWaylandSurface::unmap()
		??:?
	#14 | Hyprland(_ZN4CXWM17handleUnmapNotifyEP24xcb_unmap_notify_event_t+0x66) [0x59f441c5ecd6]
		CXWM::handleUnmapNotify(xcb_unmap_notify_event_t*)
		??:?
	#15 | Hyprland(_ZN4CXWM7onEventEij+0x1cc) [0x59f441c6104c]
		CXWM::onEvent(int, unsigned int)
		??:?
	#16 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x1f2) [0x712e76b1b0a2]
		??
		??:0
	#17 | /usr/lib/libwayland-server.so.0(wl_display_run+0x2f) [0x712e76b1d10f]
		??
		??:0
	#18 | Hyprland(_ZN17CEventLoopManager9enterLoopEP10wl_displayP13wl_event_loop+0x59) [0x59f441afd919]
		CEventLoopManager::enterLoop(wl_display*, wl_event_loop*)
		??:?
	#19 | Hyprland(main+0xa0b) [0x59f44195618b]
		main
		??:?
	#2 | /usr/lib/libc.so.6(+0x25e08) [0x712e76117e08]
		??
		??:0
	#21 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x712e76117ecc]
		??
		??:0
	#22 | Hyprland(_start+0x25) [0x59f44198f255]
		_start
		??:?

Log tail:
[LOG] Callback 59f4745ad008 -> 59f4745ad000, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 59f47427cf10 called init()
[LOG] Registered signal for owner 59f4745acfd0: 59f4747512e8 -> 59f4745acfe0 (owner: CRenderbuffer)
[LOG] Callback 59f4745ad008 -> 59f4745ad000, CRenderbuffer removed.
[LOG] Registered signal for owner 59f4745acfd0: 59f4747512e8 -> 59f4745acfe0 (owner: CRenderbuffer)
[LOG] Callback 59f4745ad008 -> 59f4745ad000, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 59f47427cf10 called init()
[LOG] Registered signal for owner 59f4745acfd0: 59f474586708 -> 59f4745acfe0 (owner: CRenderbuffer)
[LOG] Callback 59f4745ad008 -> 59f4745ad000, CRenderbuffer removed.
[LOG] Registered signal for owner 59f4745acfd0: 59f474586708 -> 59f4745acfe0 (owner: CRenderbuffer)
[LOG] Callback 59f4745ad008 -> 59f4745ad000, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 59f47427cf10 called init()
[LOG] Registered signal for owner 59f4745acfd0: 59f4747512e8 -> 59f4745acfe0 (owner: CRenderbuffer)
[LOG] Callback 59f4745ad008 -> 59f4745ad000, CRenderbuffer removed.
[LOG] Registered signal for owner 59f4745a49c0: 59f4747512e8 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 59f47427cf10 called init()
[LOG] Registered signal for owner 59f4745a49c0: 59f474586708 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] Registered signal for owner 59f4745a49c0: 59f474586708 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 59f47427cf10 called init()
[LOG] Registered signal for owner 59f4745a49c0: 59f4747512e8 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] Registered signal for owner 59f4745a49c0: 59f4747512e8 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] cursorImage request: surface 1
[LOG] CWLSurface 59f47427cf10 called init()
[LOG] Registered signal for owner 59f4745a49c0: 59f474586708 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] Registered signal for owner 59f4745a49c0: 59f474586708 -> 59f4745a49d0 (owner: CRenderbuffer)
[LOG] Callback 59f4745a49f8 -> 59f4745a49f0, CRenderbuffer removed.
[LOG] cursorImage request: surface 0
[LOG] CWLSurface 59f47427cf10 called destroy()
[LOG] Keybind triggered, calling dispatcher (64, , 113)
[LOG] [Window 59f4745a6c00: title: "", class: ] destroyed, queueing.
[ERR] onWindowRemovedTiling node null?
[LOG] Unmapped [Window 59f4745a6c00: title: ""] removed instantly
[LOG] XWayland surface 59f47437c490 unmapping
[LOG] [Window 59f4745a4a80: title: "Minecraft* 1.21", class: Minecraft* 1.21] unmapped
[LOG] Searching for matching rules for Minecraft* 1.21 (title: Minecraft* 1.21)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 59f4745a4a80: title: "Minecraft* 1.21"]
[LOG] Framebuffer created, status 36053
[CRITICAL] 
==========================================================================================
ASSERTION FAILED! 

Aborting, glGetGraphicsResetStatus returned GL_INNOCENT_CONTEXT_RESET. Cannot continue until proper GPU reset handling is implemented.

at: line 518 in OpenGL.cpp

**Comment by vaxerski** [comment]
you cut off important information in both the log and crash report. Closing as invalid, likely dupe #7103

**Comment by inmymum** [comment]
Not a dupe, nor flickering (which would be caused by the person not selecting the option to use native glfw, hence running the game in xwayland) it is an actual hyprland crash. The system locks up, comes back after around 4 seconds, continues to hang, then hyprland crashes and kicks me out to sddm.

**Comment by vaxerski** [comment]
you are not on git + your gpu driver crashed

I had similar crashes on modded mc which were mc's fault

**Comment by inmymum** [comment]
I have only ever had this issue on hyprland, not de like plasma or gnome. Thank you for the clarification about the gpu driver. I have a feeling this crash is caused by xwayland in some way

**Comment by vaxerski** [comment]
try on git, see how that works.

You could also try to find if there's anything logged in dmesg.

**Comment by inmymum** [comment]
I see this error in dmesg: ```sh [   563.452500] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!``` 
Right after every crash. Definitely a amdgpu driver error and not a hyprland issue. Still highly annoying as it causes issues with duping items and reverting the world back a few minutes, however i have an autosave mod so it's not that bad. This issues has happened 10+ times today.
