### ISSUE TITLE
Firefox's bookmarks toolbar folder menu expands to top after 33e513d489faf5998a3831d55aa7ddd796ef3368

### ISSUE THREAD

**Issue by moetayuko** [hyprwm/Hyprland#7118]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

when clicking on a folder of Firefox's bookmarks toolbar, the menu expands from the bar to the top outside of the screen after https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368

### How to reproduce

see Description

### Crash reports, logs, images, videos

![图片](https://github.com/user-attachments/assets/71d1f844-cad6-45ad-8c88-7bb0778ec20d)

**Comment by vaxerski** [comment]
@outfoxxed

**Comment by outfoxxed** [comment]
Cannot reproduce. A screenshot of your entire screen would be helpful for determining why it was positioned that way, though I've tested all edges of my screen and it behaves normally.

I was able to find a single multi monitor edge case but you aren't getting that one.

**Comment by DHDcc** [comment]
@outfoxxed I also have this issue: 
![1722458910_grim](https://github.com/user-attachments/assets/9025a68a-8c19-4c83-832a-879a06bb8fdb)

**Comment by outfoxxed** [comment]
Are you on a version on or after https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368?

That looks exactly like the behavior before the positioner was rewritten. If you are, what does your monitor layout look like?

**Comment by moetayuko** [comment]
> Are you on a version on or after [33e513d](https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368)?
> 
> That looks exactly like the behavior before the positioner was rewritten. If you are, what does your monitor layout look like?

before bc86afea7e177a7ad4335737417fc0e468698dc4 -- ok
between bc86afea7e177a7ad4335737417fc0e468698dc4 and 33e513d489faf5998a3831d55aa7ddd796ef3368 -- ok
after 33e513d489faf5998a3831d55aa7ddd796ef3368 -- bad
latest main but revert 33e513d489faf5998a3831d55aa7ddd796ef3368 -- ok

```
❯ hyprctl monitors   
Monitor DP-1 (ID 0):
	3840x2160@59.98200 at 0x0
	description: DOME imaging systems 273B1 demoset-1
	make: DOME imaging systems
	model: 273B1
	serial: demoset-1
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 2.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 3840x2160@59.98Hz 1920x1200@59.98Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1600x1200@59.98Hz 1680x1050@59.98Hz 1400x1050@59.98Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x960@60.00Hz 1280x800@59.98Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@60.00Hz 800x600@60.32Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@60.00Hz 640x480@59.94Hz 640x480@59.94Hz 

Monitor DP-2 (ID 1):
	1920x1080@60.00000 at 1920x0
	description: Dell Inc. DELL E2417H 3KR5V78J1PYB
	make: Dell Inc.
	model: DELL E2417H
	serial: 3KR5V78J1PYB
	active workspace: 11 (11)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@60.00Hz 1680x1050@60.00Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@60.00Hz 1280x800@60.00Hz 1152x864@75.00Hz 1280x720@60.00Hz 1024x768@75.03Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@60.32Hz 640x480@75.00Hz 640x480@59.94Hz 720x400@70.08Hz
```

**Comment by outfoxxed** [comment]
> > Are you on a version on or after [33e513d](https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368)?
> > That looks exactly like the behavior before the positioner was rewritten. If you are, what does your monitor layout look like?
> 
> before [bc86afe](https://github.com/hyprwm/Hyprland/commit/bc86afea7e177a7ad4335737417fc0e468698dc4) -- ok between [bc86afe](https://github.com/hyprwm/Hyprland/commit/bc86afea7e177a7ad4335737417fc0e468698dc4) and [33e513d](https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368) -- ok after [33e513d](https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368) -- bad latest main but revert [33e513d](https://github.com/hyprwm/Hyprland/commit/33e513d489faf5998a3831d55aa7ddd796ef3368) -- ok
> 
I meant @DHDcc but thanks. Your issue does not look like the old positioner @moetayuko. Can you give me a screenshot of all monitors with the menu broken, and let me know if it still happens if you move the firefox window to the middle of the screen?

**Comment by moetayuko** [comment]
@outfoxxed I recorded a video to demonstrate the issue

https://github.com/user-attachments/assets/152e857f-b6f5-4eee-acc8-2acba0325e4b

pay attention that the broken menus are the ones that don't fit on the screen

all menus expand from down to top if I move ff window to the bottom half of the screen

**Comment by outfoxxed** [comment]
I'm not able to play that video in firefox, chromium, or mpv.

**Comment by DHDcc** [comment]
@outfoxxed I'm on v0.41.2.

**Comment by outfoxxed** [comment]
@moetayuko Alright I see the problem. Flip doesn't try to make judgements about which direction is better currently, just if it hit a constraint that should cause one.

@vaxerski @moetayuko what do you think a better behavior here is:
1. choose the original direction, slide/shrink to fit depending on constraint adjustments
2. choose whichever direction puts a larger amount of the menu on screen, slide/shrink to fit



> @outfoxxed I'm on v0.41.2.

You're on the old positioner. The referenced commits in this issue fix that.

**Comment by moetayuko** [comment]
> @vaxerski @moetayuko what do you think a better behavior here is:
> 
>     1. choose the original direction, slide/shrink to fit depending on constraint adjustments
> 
>     2. choose whichever direction puts a larger amount of the menu on screen, slide/shrink to fit

I don't understand positioning internals, does 2 mean ignoring the direction specified by apps? if so ig 1 is better

**Comment by outfoxxed** [comment]
Yes, 2 would pick based on what gives it more space instead of the app's recommendation, but on the other hand, the app has asked the compositor to flip the popup if its running out of space anyway.

An example scenario of when 1 and 2 are different is if your firefox window was nearer the bottom of the screen. It would choose to go up if more space was available that way.

**Comment by outfoxxed** [comment]
I've fixed this in quickshell's positioner (the model for hyprland's) and should have a pr up soon.
