### ISSUE TITLE
Keep pinned windows in foreground while workspace change

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#712]
During the animation of a workspace change, pinned windows are sometimes behind the windows of the newly focused workspace. After that animation finishes the pinned window is in foreground again.

**Comment by vaxerski** [comment]
can you plox record that?

**Comment by Dickby** [comment]
https://user-images.githubusercontent.com/10100765/191730312-ad8aa528-441e-42b3-af34-e52fbb7fe57d.mp4

**Comment by vaxerski** [comment]
fixed in fc37ce4a724101def1befa01b353162830f4393f
