### ISSUE TITLE
Flash back to the login interface when entering the desktop

### ISSUE THREAD

**Issue by wisme2** [hyprwm/Hyprland#7132]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
```

</details>

### Description

Flash back to the login interface when entering the desktop

### How to reproduce

I am unable to locate the problem and cannot confirm the cause of the crash

### Crash reports, logs, images, videos

[LOG] Instance Signature: 918d8340afd652b011b937d29d5eea0be08467f5_1722505585_1742306812
[LOG] Runtime directory: /run/user/1000/hypr/918d8340afd652b011b937d29d5eea0be08467f5_1722505585_1742306812
[LOG] Hyprland PID: 531
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: localhost-wansha
[LOG] Release: 6.10.2-zen1-1-zen
[LOG] Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:32 +0000

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: "If it ain't broke, don't fix it" - Lucascito_03

[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 75.35µs. Estimated average calc time: 0.09µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 23.60µs. Estimated average calc time: 0.04µs.
[LOG] Using config: /home/Wansha/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the PointerManager!
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Creating the Hypr OpenGL Renderer!
[LOG] Using: OpenGL ES 2.0 Mesa 24.1.4-arch1.2
[LOG] Vendor: Intel
[LOG] Renderer: Mesa Intel(R) HD Graphics (ILK)
[LOG] Supported extensions: (89) GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_texture_storage GL_NV_pack_subimage GL_NV_texture_barrier GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_APPLE_sync GL_EXT_draw_buffers GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_generate_mipmap_sRGB GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_debug_label GL_EXT_separate_shader_objects GL_INTEL_performance_query GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_polygon_offset_clamp GL_EXT_texture_border_clamp GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_EXT_blend_func_extended GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_s3tc_srgb GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_mirror_clamp_to_edge GL_KHR_parallel_shader_compile GL_EXT_shader_framebuffer_fetch_non_coherent GL_INTEL_blackhole_render GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_MESA_sampler_objects GL_MESA_bgra 
[LOG] EGL: GPU Supports Format AB4H (0x48344241)
[LOG] EGL: | with modifier INVALID (0xffffffffffffff)
[LOG] EGL: | with modifier X_TILED (0x100000000000001)
[LOG] EGL: | with modifier LINEAR (0x0)
[LOG] EGL: GPU Supports Format XB4H (0x48344258)
[LOG] EGL: | with modifier INVALID (0xffffffffffffff)
[LOG] EGL: | with modifier X_TILED (0x10000000000000

**Comment by romanstingler** [comment]
[LOG] Using: OpenGL ES 2.0 Mesa 24.1.4-arch1.2
 
 have you built the legacyrenderer version ??

**Comment by wisme2** [comment]
But when I installed Hyprland through aur, I encountered some errors:
FAILED: /home/wansha/.cache/paru/clone/hyprland-legacyrenderer/src/Hyprland-0.40.0/subprojects/wlroots-hyprland/src/wlroots-hyprland-stamp/wlroots-hyprland-build /home/wansha/.cache/paru/clone/hyprland-legacyrenderer/src/Hyprland-0.40.0/subprojects/wlroots-hyprland/build/libwlroots.a
cd /home/wansha/.cache/paru/clone/hyprland-legacyrenderer/src/Hyprland-0.40.0/subprojects/wlroots-hyprland && ninja -C build
ninja: Entering directory `build'


FAILED: libwlroots.a.p/backend_drm_libliftoff.c.o
cc -Ilibwlroots.a.p -I. -I.. -Iinclude -I../include -Iprotocol -Irender/gles2/shaders -Ibackend/drm -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_POSIX_C_SOURCE=200809L -DWLR_USE_UNSTABLE -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../= -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/home/wansha/.cache/paru/clone/hyprland-legacyrenderer/src=/usr/src/debug/hyprland-legacyrenderer -flto=auto -fPIC -MD -MQ libwlroots.a.p/backend_drm_libliftoff.c.o -MF libwlroots.a.p/backend_drm_libliftoff.c.o.d -o libwlroots.a.p/backend_drm_libliftoff.c.o -c ../backend/drm/libliftoff.c
../backend/drm/libliftoff.c: In function ‘commit’:
../backend/drm/libliftoff.c:410:27: error: too few arguments to function ‘liftoff_output_apply’
  410 |                 int ret = liftoff_output_apply(crtc->liftoff, req, flags);
      |                           ^~~~~~~~~~~~~~~~~~~~
In file included from ../backend/drm/libliftoff.c:2:
/usr/include/libliftoff.h:85:1: note: declared here
   85 | liftoff_output_apply(struct liftoff_output *output, drmModeAtomicReq *req,
      | ^~~~~~~~~~~~~~~~~~~~
[178/315] Compiling C object libwlroots.a.p/backend_drm_drm.c.o
[179/315] Compiling C object libwlroots.a.p/backend_libinput_events.c.o
[180/315] Compiling C object libwlroots.a.p/backend_libinput_backend.c.o
[181/315] Compiling C object libwlroots.a.p/backend_libinput_keyboard.c.o
[182/315] Compiling C object libwlroots.a.p/backend_libinput_pointer.c.o
ninja: build stopped: subcommand failed.
[16/169] Building CXX object hyprctl/CMakeFiles/hyprctl.dir/main.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:5: legacyrenderer] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'hyprland-legacyrenderer-0.40.0-1':
error: packages failed to build: hyprland-legacyrenderer-0.40.0-1

**Comment by romanstingler** [comment]
seems to be an issue with the wlroots library, 0.40 is already old. 
try installing the -git version or build it yourself

**Comment by wisme2** [comment]
OK,thanks,I successfully installed Hyprland through manual compilation, but if I install the - git version, there will also be issues:

fatal:cannot change to "subprojects/wlroots-hyprland":No such file or directory 

It seems that some files were missing during cloning,it is my problem here?
