### ISSUE TITLE
Reaper context menu opens in a random position

### ISSUE THREAD

**Issue by Stoppedpuma** [hyprwm/Hyprland#7157]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 4141e6755022edc19cd37cd7ad077a93b3bae5bd  (xcursor: rework bootleg xcursor (7140)).
Date: Fri Aug 2 23:16:20 2024
Tag: v0.41.2-159-g4141e675, commits: 5045

flags: (if any)


System Information:
System name: Linux
Release: 6.8.9-273-tkg-eevdf-llvm
Version: #1 SMP PREEMPT_DYNAMIC TKG Sat, 11 May 2024 06:09:58 +0000


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])
```

</details>

### Description

Attempting to use context menus on Reaper DAW doesn't end well, the position of the context menu seems to be way off and isn't consistent of opening in the right spot, let alone working sometimes when I can even access it.

Marking as "No" on regression as I haven't used Reaper on Hyprland before. Menus works correctly in Sway.

### How to reproduce

Use Reaper and attempt to open options on the top bar

### Crash reports, logs, images, videos

[1722642730.webm](https://github.com/user-attachments/assets/ce1f3c9f-cdd1-4544-8118-50339c355526)

**Comment by vaxerski** [comment]
#6921

**Comment by Stoppedpuma** [comment]
I don't know how I missed that, thanks!
