### ISSUE TITLE
GTK combobox not displayed correctly

### ISSUE THREAD

**Issue by krims0n32** [hyprwm/Hyprland#7171]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: nyx
Release: 6.10.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev c8) (prog-if 00 [VGA controller])
19:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

When clicking on a combobox in any GTK application, not all options immediately appear, only when you move the mouse they come up. Looks like the box is being rendered too small or something. Does not happen on GNOME. Tried various GTK themes, all have this issue. Floating or tiled makes no difference. See video.

### How to reproduce

Click on a combobox in any gtk application (galculator for example).

### Crash reports, logs, images, videos

[gtk.webm](https://github.com/user-attachments/assets/9486780d-f96b-418f-8c41-000161ca7eb3)

**Comment by vaxerski** [comment]
try on git

**Comment by krims0n32** [comment]
git doesn't have the issue. closing :heart:
