### ISSUE TITLE
border_size modifies gap size on monitor scale other than 1

### ISSUE THREAD

**Issue by bryceberger** [hyprwm/Hyprland#718]
Steps to reproduce: set monitor scale to a value other than 1 (noticed on 1.75, happens on 0.8, 1.1, 1.5, 2.0, etc). set gaps_in and gaps_out to 0. set border_size to a nonzero value (larger is easier to see)

Expected outcome: No wallpaper visible

Noted outcome: Wallpaper visible (when monitor scale above 1. Below 1 results in strange overlap of borders)

**Comment by Estebiu** [comment]
Also, if you have a multi-monitor setup with different scale settings, there'll be inconsistencies between them.
On one the borders will be too big or too small in comparation to the other one.
