### ISSUE TITLE
arch hyprland git make error

### ISSUE THREAD

**Issue by b33slayer** [hyprwm/Hyprland#7182]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

Release: 6.10.2-arch1-2

</details>

### Description

-- Gathering git info
CMake Error at CMakeLists.txt:29 (add_subdirectory):
  The source directory

    /home/user/Hyprland/subprojects/udis86

  does not contain a CMakeLists.txt file.

### How to reproduce

just try make on arch

**Comment by MahouShoujoMivutilde** [comment]
Is it also _empty_ by any chance? Then try `git submodule update --init`

**Comment by b33slayer** [comment]
> Is it also _empty_ by any chance? Then try `git submodule update --init`

now its works
