### ISSUE TITLE
Hyprland: error while loading shared libraries: libhyprutils.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Brad1944** [hyprwm/Hyprland#7185]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

Manjaro
Hyprland version: hyprland-git-0.41.2.r80.a5f58a31-1 (AUR)
Hyprutils version:  hyprutils-git 0.2.1.r0.g5dcbbc1e-1 (AUR)

```sh
hyprctl systeminfo -c
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)

idk how to use this command without getting hyprland to run
```

</details>

### Description

Hyprland won't start after system update (yay -Syu --devel)

### How to reproduce

/bin/Hyprland

### Crash reports, logs, images, videos

Crash report not present, only this error
Hyprland: error while loading shared libraries: libhyprutils.so.0: cannot open shared object file: No such file or directory

**Comment by JassonCordones** [comment]
did you clean build while updating?

**Comment by vaxerski** [comment]
this is not a hyprland bug

**Comment by moazzammoriani** [comment]
I'm getting the same issue as this so I have to ask

> did you clean build while updating?
@JassonCordones how would I go about doing this?

**Comment by Brad1944** [comment]
> did you clean build while updating?

@JassonCordones Can't really confirm. How can I try doing one?

**Comment by Brad1944** [comment]
> > did you clean build while updating?
> 
> Can't really confirm. How can I try doing one?

Figured out how, even tried deleting whole ~/.cache/yay and ~/.cache/pacman + yay cleanbuild but it still doesn't work

**Comment by MightyPlaza** [comment]
see https://github.com/hyprwm/Hyprland/issues/7142

**Comment by Brad1944** [comment]
Fixed it, If anyone stumbles upon the same issue, create a symlink in `/usr/lib/libhyprutils.so.0` that directs to `/usr/lib/libhyprutils.so.0.x.x` (e.g `0.2.1`)

```bash
cd /usr/lib
sudo ln -s libhyprutils.so.0.2.1 libhyprutils.so.0
sudo chmod 777 libhyprutils.so.0
```

(Be sure to recreate the symlink everytime hyprutils updates, atleast until the package is fixed)

Though, this isn't a permanent fix. It should be somewhat related to the AUR / Hyprutils package itself

**Comment by vaxerski** [comment]
this is a horrible fix that will make stuff crash

**Comment by Brad1944** [comment]
> this is a horrible fix that will make stuff crash

not really calling it a "fix", more of a hacky workaround. Real fix would need modification in the package itself

**Comment by MightyPlaza** [comment]
> > this is a horrible fix that will make stuff crash
> 
> not really calling it a "fix", more of a hacky workaround. Real fix would need modification in the package itself

what's the output of `pacman -Qs hypr`?

**Comment by Brad1944** [comment]
> pacman -Qs hypr
local/hyprcursor-git 0.1.9.r11.g912d5602-1
    The hyprland cursor format, library and utilities
local/hypridle-git 0.1.2.r12.g96d51ec2-1
    Hyprland's idle daemon
local/hyprland-git 0.41.2.r166.0e86808e-1
    Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't
    sacrifice on its looks.
local/hyprlang-git 0.5.2.r8.gadbefbf4-1
    The official implementation library for the hypr config language
local/hyprlock-git 0.4.1.r8.g8cffe061-1
    Hyprland's GPU-accelerated screen locking utility
local/hyprpicker-git 0.3.0.r9.c36676a-1
    A wlroots-compatible Wayland color picker that does not suck
local/hyprutils-git 0.2.1.r1.g0252fd13-1
    Hyprland utilities library used across the ecosystem
local/hyprwayland-scanner-git 0.4.0.r4.ga048a6cb-1
    A Hyprland implementation of wayland-scanner, in and for C++
local/xdg-desktop-portal-hyprland-git 1.3.2.r4.gb9b97e5b-1
    xdg-desktop-portal backend for hyprland

**Comment by MightyPlaza** [comment]
you're most likely running a (older) `Hyprland` binary unrelated to the current aur package, like in the issue I linked
see `which Hyprland` you're running and see if it's the right binary

**Comment by Brad1944** [comment]
> you're most likely running a (older) `Hyprland` binary unrelated to the current aur package, like in the issue I linked see `which Hyprland` you're running and see if it's the right binary

![image](https://github.com/user-attachments/assets/482a43da-012d-4b00-bc67-ffde83d4ca5d)

**Comment by fschuindt** [comment]
What @MightyPlaza said was truth for me.

This how I fixed it on Arch linux. Please, don't try blindly to run these commands, you should understand the gist of what I'm doing and then try the same for you. Basically, I'm uninstalling everything Hyrpland related, installing it again, and re-compiling Hyprland. This usually works for me after a system upgrade break something.

```bash
#!/bin/bash

# Remove packages related to Hyprland.
# (You might have others, or not have some of these)
sudo pacman -R aquamarine hyprland hyprutils
yay -R aquamarine-git hyprland-git hyprutils-git \
    tomlplusplus hyprlang hyprcursor \
    hyprwayland-scanner xcb-util-errors

# Install necessary packages
sudo pacman -S gdb ninja gcc cmake meson libxcb \
     cb-proto xcb-util xcb-util-keysyms libxfixes \
     libx11 libxcomposite xorg-xinput libxrender \
     pixman wayland-protocols cairo pango seatd \
     libxkbcommon xcb-util-wm xorg-xwayland \
     libinput libliftoff libdisplay-info cpio

# Reinstall the packages we removed
yay -S tomlplusplus hyprlang hyprcursor \
    hyprwayland-scanner xcb-util-errors \
    hyprutils-git aquamarine-git

# Clone Hyprland and build it
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
make all && sudo make install
```

**Comment by JassonCordones** [comment]
yay -S hyprland-git hyprutils-git 

When yay ask you if you want to clean build you select All

**Comment by Axenide** [comment]
Just updated too, same error.

**Comment by Yagth** [comment]
> I am getting the same error now, I have just updated my system , and it is giving me this message :
> 
> ```
> Hyprland: error while loading shared libraries: libhyprutils.so.1: cannot open shared object file: No such file or directory
> ```
> 
> if will restart then after that , it will get into login loop . Whenever I will try to login , it will throw me back to login screen after a black screen for some seconds .
> 
> As I haven't restared so I can still give version details :
> 
> ```
> ╭─ankur@ankur in ~ took 0s
> [🔴] × hyprctl version
> Hyprland 0.46.0 built from branch main at commit 71dc9f6128b8d2e382b2a574d2d5f15e2d907f3a  (pluginAPI: add register dispatcher v2).
> Date: Thu Dec 19 20:23:32 2024
> Tag: v0.46.0-18-g71dc9f61, commits: 5573
> built against:
>  aquamarine 0.5.1
>  hyprlang 0.6.0
>  hyprutils 0.2.6
>  hyprcursor 0.1.10
>  hyprgraphics 0.1.1
> 
> 
> flags set:
> debug
> ```

I was getting the exact same error moments ago and I had to uninstall everything related to hyprland and reinstall it again. Then it started working.

**Comment by nsavinda** [comment]
> I am getting the same error now, I have just updated my system , and it is giving me this message :
> 
> ```
> Hyprland: error while loading shared libraries: libhyprutils.so.1: cannot open shared object file: No such file or directory
> ```
> 
> if will restart then after that , it will get into login loop . Whenever I will try to login , it will throw me back to login screen after a black screen for some seconds .
> 
> As I haven't restared so I can still give version details :
> 
> ```
> ╭─ankur@ankur in ~ took 0s
> [🔴] × hyprctl version
> Hyprland 0.46.0 built from branch main at commit 71dc9f6128b8d2e382b2a574d2d5f15e2d907f3a  (pluginAPI: add register dispatcher v2).
> Date: Thu Dec 19 20:23:32 2024
> Tag: v0.46.0-18-g71dc9f61, commits: 5573
> built against:
>  aquamarine 0.5.1
>  hyprlang 0.6.0
>  hyprutils 0.2.6
>  hyprcursor 0.1.10
>  hyprgraphics 0.1.1
> 
> 
> flags set:
> debug
> ```


I got the same issue now. I had the `libhyprutils.so.2` file and I created a symlink pointing to it. Now it works.
```bash
cd /usr/lib
sudo ln -s libhyprutils.so.2 libhyprutils.so.1
sudo chmod 777 libhyprutils.so.1
```

**Comment by JassonCordones** [comment]
You just needed to update the entire hypr* stack

**Comment by opensourcecheemsburgers** [comment]
Here's how I fixed it:

1. Remove all caches: `yay -Scc` or `sudo pacman -Scc`
2. Remove all Hyprland tools. Find them by using: `pacman -Qq | grep 'hypr'`.
3. If you have the Chaotic-AUR installed, comment it out from `/etc/pacman.conf`.
4. Reinstall the packages.

**Comment by Axenide** [comment]
In my case, for some reason I had some hypr packages with their `-git` version. I just did `sudo pacman -Rdd` with them and installed their non git versions and everything is back to normal.

**Comment by DTarbet** [comment]
> In my case, for some reason I had some hypr packages with their `-git` version. I just did `sudo pacman -Rdd` with them and installed their non git versions and everything is back to normal.

Thanks as well! This sorted me out in just a few minutes.

**Comment by divital-coder** [comment]
> Here's how I fixed it:
> 
>     1. Remove all caches: `yay -Scc` or `sudo pacman -Scc`
> 
>     2. Remove all Hyprland tools. Find them by using: `pacman -Qq | grep 'hypr'`.
> 
>     3. If you have the Chaotic-AUR installed, comment it out from `/etc/pacman.conf`.
> 
>     4. Reinstall the packages.

@opensourcecheemsburgers Thank you sir!!, this is straightforward and perhaps the best solution here :)

**Comment by Eduruiz** [comment]
For people who don't want to reinstall everything, this usally will happen with the `-git` version of things, check out your log of the packages while they build and you will get something like this:
```
/sbin/ld: warning: libspng.so.0, needed by /usr/lib/libhyprgraphics.so, not found (try using -rpath or -rpath-link)
```
this happened when I tried to update `hyprlock-git`, but the error tell me (kinda) what to do, so you need to cleanbuild the hyprgraphics package (when you `yay -S hyprgraphics-git` it asks you "packages to cleanBuild"), after that you reinstall/update the original problematic package, in my case, `yay -S hyprlock-git` aswering `a` for the cleanBuild option and everything works fine. oh, and this log about the lib doesn't show up as a error, sometimes its just there with the other info while you build the package so keep an eye for it

**Comment by RT-Tap** [comment]
This has worked each time this has happened to me so if your using paru:
```
paru -S --rebuild hyprland-git
```
