### ISSUE TITLE
Flashing context menus

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#719]
https://user-images.githubusercontent.com/90208727/192094872-68cbb30b-1778-4d8f-91e7-dad7edd2fd3d.mp4

This is not a hyprland specific bug (found it on sway aswell), but it doesn't withdraw the fact that it's annoying, I use many of the options from vscode menu. The weird thing is for vscode it works perfectly for some lines whilst it doesn't for others and sometimes it just magically disappears after restarted vscode, same is with firefox. I did not find this bug in any of the gnome apps tho (i.e nautilus, eog, etc)

**Comment by fufexan** [comment]
Is your system up to date? I haven't seen this issue in quite a while, it seems strange that it appears now.
Also, are you running on nvidia? If yes, is your wlroots patched?

**Comment by vaxerski** [comment]
monitor config gib

**Comment by System-x64** [comment]
> Is your system up to date? I haven't seen this issue in quite a while, it seems strange that it appears now. Also, are you running on nvidia? If yes, is your wlroots patched?

1) Yesh, my `hyprland-git` is up to date
2) No, I am using an amd gpu (integrated)

**Comment by KyleUltimate** [comment]
`which Hyprland`?

**Comment by System-x64** [comment]
> monitor config gib

In `hyprland.conf`? 

```monitor=preferred,auto,1```

**Comment by vaxerski** [comment]
thats wrong innit?

`monitor=,preferred,auto,1`

**Comment by System-x64** [comment]
> `which Hyprland`?

[https://aur.archlinux.org/packages/hyprland-git](url)

**Comment by System-x64** [comment]
> thats wrong innit?
> 
> `monitor=,preferred,auto,1`

ye sorry , its `monitor=,preferred,auto,1` only mb

**Comment by KyleUltimate** [comment]
> > `which Hyprland`?
> 
> [https://aur.archlinux.org/packages/hyprland-git](url)

Uhh, I mean, run the command `which Hyprland`
It's possible that you got a Hyprland exec in /usr/local/bin, which doesn't get updated by the pkgbuild, therefore giving you a out-of-date Hyprland

**Comment by System-x64** [comment]
oh mb, 
its output was `/usr/bin/Hyprland`

**Comment by vaxerski** [comment]
check for gaps in the layout. `hyprctl monitors`

**Comment by System-x64** [comment]
> check for gaps in the layout. `hyprctl monitors`

![screenshot_20220925_111227](https://user-images.githubusercontent.com/90208727/192130134-c7762f94-f635-486b-91ab-601beef632b8.png)

**Comment by vaxerski** [comment]
no clue then

**Comment by System-x64** [comment]
Sed, i mean its not a hyprland only problem so nvm, atleast y'all tried to help meh

**Comment by frigaut** [comment]
@System-x64 I can confirm I am seeing the same bug - for about a week now. Indeed, it is not hyprland specific. I have seen it in sway too. it seems to be webapp related. Electron apps, and firefox. It is a bit annoying, but for now I'm just using the workarounds (keyboard) and waiting for a fix. What surprises me though is that the other hyprlanders are not seeing that. Might be graphic card related? I am using an intel integrated (VGA compatible controller: Intel Corporation Comet Lake UHD Graphics (rev 04)) on both my laptop and desktop, and having the issue on both.

**Comment by BeZaBel** [comment]
I have the same bug. If I run Firefox with xwayland the problems disappears completely.

**Comment by vaxerski** [comment]
I don't on neither my RX 6700 XT desktop or my Ryzen 7 Laptop

**Comment by System-x64** [comment]
> I don't on either my RX 6700 XT desktop or my Ryzen 7 Laptop

R u using the AUR version (if so, which one?) or client compiled?

**Comment by vaxerski** [comment]
man I compile my own compositor by myself. I don't use the AUR.

**Comment by System-x64** [comment]
Nope. Doesn't help still getting those flickers

**Comment by quasigod-io** [comment]
I have the same issue with integrated Intel graphics on NixOS. The only app I use that's affected is Firefox.

**Comment by mgbowe1** [comment]
I think this is a general webapp issue. I'm using chromium and I'm seeing this flickering for entire web pages, only when using hyprland (but I don't have any other wlroots-based compositors that work with my system).

**Comment by System-x64** [comment]
> This got solved for me with Firefox 106.
Can confirm that this issue is fixed for me aswell

But my code, it's still the same :(

So this is a more of an application based issue than hyprland based....

**Comment by System-x64** [comment]
UPDATE 6/23: FIXED. Apparently these applications were not running natively on wayland and their context menus were being treated like a separate window.
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland
