### ISSUE TITLE
Sometimes Chinese input method can not input Chinese normally in where need input Chinese

### ISSUE THREAD

**Issue by PILIHU2022** [hyprwm/Hyprland#7192]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0e86808e5912823f1c6bea1b6d5fcae297fc9f57 dirty (cursor: Better xcursor implementation (7178)).
Date: Tue Aug 6 01:58:21 2024
Tag: v0.41.2-166-g0e86808e, commits: 5052

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.10.3-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 04 Aug 2024 05:11:13 +0000


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Description

Hi! I'm using `fctix5-rime` to input Chinese, but nowadays, it have a problem. Like this picture following. 
I have asked some people, they also have this problem.
If the picture can't give enough information for developer. You can reply this issue, and I will try to give you some information what useful

The package I installed to input Chinese:
```
fcitx5
fcitx5-chinese-addons
fcitx5-rime
```

And the other packages maybe cause this issue:
```
fcitx5-configtool
fcitx5-gtk
fcitx5-material-color
fcitx5-nord
fcitx5-pinyin-chinese-idiom
fcitx5-pinyin-zhwiki
fcitx5-qt
```

### How to reproduce

Sometimes will have this problem. The people who I have asked all can't reproduce this issue

### Crash reports, logs, images, videos

![355291263-bd3f5244-5887-4e34-b1cc-ebf4488e3662](https://github.com/user-attachments/assets/ca135115-32e1-4e23-a148-af0ab653afa7)

**Comment by PILIHU2022** [comment]
Someone has recorded this video
[Link](https://pilihu2023-my.sharepoint.com/:v:/g/personal/pilihu_pilihu2023_onmicrosoft_com/EelheQHK1T1Aos2BSdZNUwEBlM5ZNQED8GMzm7R9vPTetg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=aRXXhV)

**Comment by BRS5672023** [comment]
> Someone has recorded this video [Link](https://pilihu2023-my.sharepoint.com/:v:/g/personal/pilihu_pilihu2023_onmicrosoft_com/EelheQHK1T1Aos2BSdZNUwEBlM5ZNQED8GMzm7R9vPTetg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=aRXXhV)

Are u sure this is a issue with hyprland but not the input method itself, I'm using fcitx5-pinyin and fcitx5-wubi just fine on chromium..
![swappy-20240806-120546](https://github.com/user-attachments/assets/a8e5d1ad-4e63-433f-b614-f9d8a5cdb19f)

**Comment by PILIHU2022** [comment]
> > Someone has recorded this video [Link](https://pilihu2023-my.sharepoint.com/:v:/g/personal/pilihu_pilihu2023_onmicrosoft_com/EelheQHK1T1Aos2BSdZNUwEBlM5ZNQED8GMzm7R9vPTetg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=aRXXhV)
> 
> Are u sure this is a issue with hyprland but not the input method itself, I'm using fcitx5-pinyin and fcitx5-wubi just fine on chromium.. ![swappy-20240806-120546](https://private-user-images.githubusercontent.com/162549262/355307646-a8e5d1ad-4e63-433f-b614-f9d8a5cdb19f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTc3MDcsIm5iZiI6MTcyMjkxNzQwNywicGF0aCI6Ii8xNjI1NDkyNjIvMzU1MzA3NjQ2LWE4ZTVkMWFkLTRlNjMtNDMzZi1iNjE0LWY5ZDhhNWNkYjE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNDEwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTllMTAyZTdhMDNlMmNkOWE5ZWFmYWRiN2U3NTc2YWJhM2Y1NTAzZTA0ODFmYmI3MzZkMmM4ZjVmMTlhMGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v6snvSlQk5j5H6UoL9J98GJmWYgjtBF85UQR-6eDDeA)

He says that he has changed the desktop environment but he doesn't have the problem. Me,too

**Comment by ErrorNoInternet** [comment]
Do you have the

```
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus
```

environment variables?

Also keep in mind that certain old versions of Minecraft use LWJGL2, which do not support input methods.

**Comment by PILIHU2022** [comment]
> Do you have the
> 
> ```
> XMODIFIERS=@im=fcitx
> GTK_IM_MODULE=fcitx
> QT_IM_MODULE=fcitx
> GLFW_IM_MODULE=ibus
> ```
> 
> environment variables?
> 
> Also keep in mind that certain old versions of Minecraft use LWJGL2, which does not support input methods on Linux.

Minecraft has not problem before. Just a example.
I am sorry that I am far away from my computer so I will check the environment vaiables tomorrow

**Comment by PILIHU2022** [comment]
> Do you have the
> 
> ```
> XMODIFIERS=@im=fcitx
> GTK_IM_MODULE=fcitx
> QT_IM_MODULE=fcitx
> GLFW_IM_MODULE=ibus
> ```
> 
> environment variables?
> 
> Also keep in mind that certain old versions of Minecraft use LWJGL2, which does not support input methods on Linux.

Oh. I remember that I have added that in my `/etc/.environment`file.

**Comment by PILIHU2022** [comment]
When I and my friends use `0.39.9`, the input method works very well(will not have this problem). But when the hyprland version is higer then  `0.39.9`, it will have this problem.

**Comment by PILIHU2022** [comment]
When I and my friends use `0.39.9`, the input method works very well(will not have this problem). But when the hyprland version is higer then  `0.39.9`, it will have this problem.

**Comment by PILIHU2022** [comment]
But we changed the desktop, such as `KDE`, the input method can work very well, too

**Comment by PILIHU2022** [comment]
But if we delete the environment, it also have this problem

**Comment by PILIHU2022** [comment]
But if we delete the environment, it also have this problem

**Comment by sungyoonc** [comment]
Can you try the latest git?

**Comment by PILIHU2022** [comment]
> Can you try the latest git?

I updated it. But I don't know how to regression. If it still like this issue, I will continue to report this

**Comment by PILIHU2022** [comment]
Still have this issue:(

**Comment by PILIHU2022** [comment]
Maybe just in `electron` apps.

**Comment by sungyoonc** [comment]
> Maybe just in `electron` apps.

Is the app you are having a problem running in  xwayland?

**Comment by PILIHU2022** [comment]
> > Maybe just in `electron` apps.
> 
> Is the app you are having a problem running in xwayland?

Yes. QQ for example:
```
Window 5d5f26c51e60 -> QQ:
	mapped: 1
	hidden: 0
	at: 22,571
	size: 931,487
	workspace: 1 (1)
	floating: 0
	pseudo: 0
	monitor: 0
	class: QQ
	title: QQ
	initialClass: QQ
	initialTitle: QQ
	pid: 1750
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 0
```
But thesedays I did NOT heard my friends tell me about this issue, maybe it was fixed. I will close this within check

**Comment by PILIHU2022** [comment]
```

**Comment by PILIHU2022** [comment]
The input method may have this problem when I switch workspace.

**Comment by PILIHU2022** [comment]
> The input method may have this problem when I switch workspace.

But maybe ONLY have this problem in the appication what run in `xwayland`
