### ISSUE TITLE
Slow startup of hyprland

### ISSUE THREAD

**Issue by gybo03** [hyprwm/Hyprland#7193]
### Regression?

No

### System Info and Version

Hyprland IPC didn't respond in time

Couldn't read (5)

i have a thinkpad t480 
Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)

### Description

when starting hyprland it seems that it does something longer then expected
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.35µs. Estimated average calc time: 0.06µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 55.93µs. Estimated average calc time: 0.18µs.

### How to reproduce

i dont know how should someone reproduce this 

### Crash reports, logs, images, videos

[log.txt](https://github.com/user-attachments/files/16509328/log.txt)

**Comment by vaxerski** [comment]
I don't understand the problem. What do you mean slow? What's the problem?

**Comment by gybo03** [comment]
well im not certain but my assumption was that when launching hyprland some task took 28.35µs but estimated avg time should be 0.06µs. Maybe i misunderstood

**Comment by vaxerski** [comment]
you can ignore this log, don't worry, all is good.
