### ISSUE TITLE
Wireless keyboard caps lock led light not working properly

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#7194]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0e86808e5912823f1c6bea1b6d5fcae297fc9f57 dirty (cursor: Better xcursor implementation (7178)).
Date: Tue Aug 6 01:58:21 2024
Tag: v0.41.2-166-g0e86808e, commits: 5052

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.10.3-2-cachyos-lto
Version: #1 SMP PREEMPT_DYNAMIC Sat, 03 Aug 2024 12:35:26 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Since aquamarine was merged, the caps lock led light doesn't work in wireless mode, it works in wired mode. Another problem is that one keyboard is connected using wireless mode and the other keyboard is connected using wired. When one keyboard caps lock is activated, the other keyboard needs to press caps lock twice to be deactivated.

### How to reproduce

above

**Comment by vaxerski** [comment]
odd, are you sure it's the aq mr?

**Comment by hdm9527** [comment]
yep

**Comment by hdm9527** [comment]
I've looked for reviews and it can be reproduced without modifying the key mapping. https://github.com/hyprwm/Hyprland/pull/6608#issuecomment-2218229934

**Comment by hdm9527** [comment]
It's a bluez problem, it has been fixed.
