### ISSUE TITLE
CMake installs desktop file in different folder than repo package, which login manager doesn't pick up

### ISSUE THREAD

**Issue by jannisbecker** [hyprwm/Hyprland#7195]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0e86808e5912823f1c6bea1b6d5fcae297fc9f57  (cursor: Better xcursor implementation (7178)).
Date: Mon Aug 5 19:58:21 2024
Tag: v0.41.2-166-g0e86808e, commits: 5052

flags: (if any)


System Information:
System name: Linux
Node name: kashiro
Release: 6.10.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 04 Aug 2024 05:11:32 +0000


GPU information: 
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  555.58.02  Release Build  (archlinux-builder@)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

```

</details>

### Description

Not sure if this belongs here or on "ly"'s side, but on my arch system I had initially installed Hyprland stable from the repos and ly as display manager. However I switched to a compiled version to get the focus bugfix for games, thus compiling Hyprland myself via cmake.
The docs on the website list the following steps to compile and install Hyprland via cmake:

> git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
make all && sudo make install

and I noticed that ly didnt show the hyprland session anymore.
Upon further inspection, it looks like, while the stable arch repo package installs the hyprland desktop file in /usr/share/wayland-sessions (see here https://archlinux.org/packages/extra/x86_64/hyprland/), the cmake compiled version will install it in /usr/local/share/wayland-sessions.

It could be that this is intended and that ly must be fixed to accommodate, but it could also be that there's an inconsistency that was missed in the cmake instructions, right?

### How to reproduce

- install ly from arch repos and compile hyprland with cmake using the aforementioned instructions in the documentation
- notice how the hyprland.desktop file is not installed to /usr/share/wayland-sessions like the repo package would, and how ly does not offer Hyprland as a session to login to.

**Comment by fufexan** [comment]
CMake's default PREFIX is `/usr/local`, so as not to conflict with Arch's prefix `/usr`. This is likely a bug on ly's side, but you can also work around this by using `hyprland-git` from the AUR.

**Comment by vaxerski** [comment]
or override cmake's default with a manual compile
