### ISSUE TITLE
Hyprland debug in a Hyprland window

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#720]
after https://github.com/hyprwm/Hyprland/commit/abee2da5bd38f5afdcce8aed591f3063d839df11
i get a black window if i try to run Hyprland inside a wm window.
I only use one monitor at the moment, so i don't see another way of running Hyprland inside a debugger.
Am i missing something?

**Comment by vaxerski** [comment]
sorry, fixed in 65fb0cf0f62f23d34334275ac9ae1741f72a1e10
