### ISSUE TITLE
Release candidate testing group

### ISSUE THREAD

**Issue by vaxerski** [hyprwm/Hyprland#7200]
### Description

@gulafaran @ikalco @Agent00Ming @Fxzzi @outfoxxed @fufexan @phonetic112 @MahouShoujoMivutilde
(feel free to @ more people that might be interested)

After the recent Explicit Sync MR (#7151) I'm interested in releasing 0.42.0 shortly. Alongside this, I've thought that it might be a good idea to form a small group of people with various hardware and software setups that would be a release candidate testing aid.

As Hyprland is growing more and more (and oh boy do we have a lot of users now) it's all the more important that releases don't have some completely game-breaking bugs when they release. Many distros might be slow to update if I make a .1 or .2.

Thus:
 - If you are interested in participating, leave a comment on this issue. You can also @ someone else if you think they'd be down. Include your gpu color, whether it's a laptop or a desktop, and the distro you use if you are ok with that
 - Let me know of your preferred communication method. Github kinda sucks for these. We could either have it on the discord server, I could make a channel on matrix, or if someone is willing to administer it, an IRC room (cuz I ain't got 0 clue on how to actually make a room on IRC or administer it)
 
Cheers and thanks for the support

**Comment by gulafaran** [comment]
sure thing il test the shizzle out of anything you want me to. im old enough to use irc but young enough to know how discord works and i have used matrix. discord has its advantage over irc being runnable on my phone :p

**Comment by outfoxxed** [comment]
Will do some testing shortly. Also want to get the xdg positioner edge cases fixed before release (will give that a shot today)
no preference an discord/matrix, just not IRC because I don't have a bouncer set up

**Comment by diniamo** [comment]
I've got an Nvidia desktop, and an Intel iGPU laptop with a touchscreen, both running NixOS. I'm interested but I can't promise I'll always be available. Discord pref, and please no IRC (seriously no one wants that).

**Comment by ikalco** [comment]
im always down to test, i daily -git and other important prs anyways
as for talking, definitely something newer like discord/matrix

**Comment by Fxzzi** [comment]
I'm happy to test, discord would be a good place tbh for live comms. I run -git regularly but also run stable releases on my laptop.

Nvidia only desktop
AMD igpu laptop

**Comment by vaxerski** [comment]
alright, I've made a channel for that on the discord server hyprland-release-testing and given the access roles to ikalco foxy and tom

rest of you please drop your usernames

**Comment by romanstingler** [comment]
Pls add 
DiscordUser: xeonscalable 
(itse me)

**Comment by entailz** [comment]
I'm interested in testing.
- discrete green gpu on desktop.
- arch
- discord or irc

**Comment by Fxzzi** [comment]
username: fazzi

**Comment by Honkazel** [comment]
Discord: honkazel
- Laptop and if i'll win my laziness - desktop(but that's not accurate, sorry)
- Intel iGPU
- Arch

**Comment by diniamo** [comment]
Username is the same, although the access roles don't seem to work (?)

**Comment by romanstingler** [comment]
yes if you can't chat,
compile a working version of Vaxry  :P

**Comment by Agent00Ming** [comment]
intel + nvidia, mux switch laptop
discord: agent_00ming

AMD | Intel | Nvidia | AMD (mgpu) | Intel (mgpu) | Nvidia (mgpu)
-- | -- | -- | -- | -- | --
  | x |   |   |   | x
  |   | x |   |   |

**Comment by zjeffer** [comment]
Username is the same (`zjeffer`), I have a laptop running Arch with AMD Ryzen 7 5800H + Nvidia RTX 3070 and a Dell docking station with 3 other monitors connected, one of them mirrored to my laptop screen.

**Comment by phonetic112** [comment]
Discord user is "zerowidthjoiner"

got a desktop with a green card (4070)
distro is arch

**Comment by Ciflire** [comment]
Hi i would be happy to contribute as a tester i run a laptop on NixOS with AMD 6800H and an nvidia 3060

discord is also preferred with the same pseudo "ciflire"

**Comment by MrYuto** [comment]
Hey, I'm interested in participating

- **Discord:** yutoli
- **GPU:** Nvidia
- **Type:** Desktop
- **Distro:** Arch

**Comment by vaxerski** [comment]
alright, I've added all of you to the channel. If anyone else wants to join in, feel free to reply here still. 

Thanks!

**Comment by Multipixelone** [comment]
I'd love to test as well. I'm basically always on -git because I crave pain.

red 7800xt card on desktop with NixOS and my discord username is tunnelmaker! :)
