### ISSUE TITLE
Black screen in some Wine/Proton games on startup

### ISSUE THREAD

**Issue by nonetrix** [hyprwm/Hyprland#7204]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit b0a70f63e3865eaa77f0b78a04b230aa583bc95c  ().
Date: 2024-08-06
Tag: , commits: b0a70f63e3865eaa77f0b78a04b230aa583bc95c

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.9.12
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Jul 27 09:36:19 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c3) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240804.cb9a96f"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  hyprsplit by shezdy ver 1.0
  dynamic-cursors by Virt ver 0.1

======Config-Start======


Config File: /home/noah/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/j8l2v22xypah1srykhwjlkgwwgdxnnpw-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/d6glcvk1qqch9zqppz6z16bk7v0l0i72-hyprsplit-0.1/lib/libhyprsplit.so
plugin=/nix/store/2mmiagw9mm124wlvggzaqjj3dyl6481g-hypr-dynamic-cursors/lib/libhypr-dynamic-cursors.so
$mod=SUPER
cursor {
  inactive_timeout=5
}

debug {
}

decoration {
  blur {
    brightness=0.700000
    enabled=true
  }
  blurls=bar-0
  blurls=bar-1
  blurls=rofi
  blurls=notifications0
  blurls=notifications1
  blurls=mpris
  col.shadow=rgba(1a1a1aaf)
  drop_shadow=true
  rounding=12
  shadow_offset=0, 40
  shadow_range=300
  shadow_render_power=4
  shadow_scale=0.900000
}

device {
  name=wacom-intuos-s-pen
}

dwindle {
  preserve_split=true
}

general {
  border_size=2
  col.active_border=rgba(f38ba8ff)
  col.inactive_border=rgba(1e1e2eff)
  extend_border_grab_area=25
  gaps_in=5
  gaps_out=10
  resize_on_border=1
}

input {
  accel_profile=flat
  follow_mouse=1
  mouse_refocus=false
}

misc {
  disable_hyprland_logo=true
}
animation=layers, 1, 5, default, slide
bind=, XF86AudioPlay, exec, playerctl play-pause
bind=, XF86AudioNext, exec, playerctl next
bind=, XF86AudioPrev, exec, playerctl previous
bind=$mod, f11, exec, brightness-ctrl down
bind=$mod, f12, exec, brightness-ctrl up
bind=$mod SHIFT, f12, exec, brightness-ctrl full
bind=CTRL, Print, exec, satty-shot
bind=, Print, exec, hyprshot -m output -o ~/Pictures/Screenshots
bind=$mod, p, exec, wl-copy $(hyprpicker)
bind=$mod, h, movefocus, l
bind=$mod, l, movefocus, r
bind=$mod, k, movefocus, u
bind=$mod, j, movefocus, d
bind=$mod SHIFT, h, movewindow, l
bind=$mod SHIFT, l, movewindow, r
bind=$mod SHIFT, k, movewindow, u
bind=$mod SHIFT, j, movewindow, d
bind=$mod, slash, togglesplit
bind=$mod, mouse_down, split:workspace, e-1
bind=$mod, mouse_up, split:workspace, e+1
bind=alt, tab, exec, rofi -show window
bind=$mod, t, togglefloating
bind=$mod, c, killactive
bind=$mod, q, exec, shutdown-menu
bind=$mod, B, exec, firefox
bind=$mod, y, exec, kitty -e yazi
bind=alt, f4, exec, hyprctl kill
bind=$mod, Return, exec, kitty
bind=$mod, Space, exec, rofi -show drun
bind=$mod, E, exec, rofimoji
bind=$mod, a, exec, kitty -e ollama run mixtral
bind=$mod SHIFT, escape, exec, hyprlock
bind=$mod SHIFT, a, exec, llm-actions
bind=$mod, 1, split:workspace, 1
bind=$mod SHIFT, 1, split:movetoworkspace, 1
bind=$mod, 2, split:workspace, 2
bind=$mod SHIFT, 2, split:movetoworkspace, 2
bind=$mod, 3, split:workspace, 3
bind=$mod SHIFT, 3, split:movetoworkspace, 3
bind=$mod, 4, split:workspace, 4
bind=$mod SHIFT, 4, split:movetoworkspace, 4
bind=$mod, 5, split:workspace, 5
bind=$mod SHIFT, 5, split:movetoworkspace, 5
bind=$mod, 6, split:workspace, 6
bind=$mod SHIFT, 6, split:movetoworkspace, 6
bind=$mod, 7, split:workspace, 7
bind=$mod SHIFT, 7, split:movetoworkspace, 7
bind=$mod, 8, split:workspace, 8
bind=$mod SHIFT, 8, split:movetoworkspace, 8
bind=$mod, 9, split:workspace, 9
bind=$mod SHIFT, 9, split:movetoworkspace, 9
bind=$mod, 0, split:workspace, 10
bind=$mod SHIFT, 0, split:movetoworkspace, 10
binde=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 1%+
binde=, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 1%-
binde=$mod CTRL, l, resizeactive, 10 0
binde=$mod CTRL, h, resizeactive, -10 0
binde=$mod CTRL, k, resizeactive, 0 -10
binde=$mod CTRL, j, resizeactive, 0 10
bindm=$mod, mouse:272, movewindow
bindm=$mod, mouse:273, resizewindow
exec-once=ags
exec-once=fcitx5
exec-once=wpaperd
exec-once=mpv --no-video --volume=150 /nix/store/ag6v7p7x8ksxirkyqjl9xfsmhzr45w31-start.wav
exec-once=/nix/store/kgicsqdrmk7z1gs9fkzkvdzgayihi7dl-lxqt-policykit-2.0.0/bin/lxqt-policykit-agent
layerrule=ignorealpha, bar-0
layerrule=ignorealpha, bar-1
layerrule=ignorealpha, notifications0
layerrule=ignorealpha, notifications1
layerrule=ignorealpha, mpris
layerrule=ignorealpha, rofi
layerrule=noanim,selection
monitor=DP-2, 1920x1200, 1920x0, 1
monitor=DP-1, 1920x1080@165, 0x0, 1, vrr, 1 
windowrulev2=noanim, class:^(com.gabm.satty)$
windowrulev2=size 640 360, title:(Picture-in-Picture)
windowrulev2=pin, title:^(Picture-in-Picture)$
windowrulev2=move 1906 14, title:(Picture-in-Picture)
windowrulev2=float, title:^(Picture-in-Picture)$
windowrulev2=float, title:^(Authentication Required)$

======Config-End========
```

</details>

### Description

When starting a game a lot of Wine/Proton games just show a black screen instead of splash screen now, I assume this might be because of explicit sync fixes PR

### How to reproduce

1. Open Halo Master Chief Collection or Need For Speed Most Wanted (2012)
2. Observe
3. Open it in gamescope and see that it boots

### Crash reports, logs, images, videos

![image](https://github.com/user-attachments/assets/1e4cb8fb-612b-41d1-a8f6-3caf8a13b2f6)
windowed because of another bug :-( 
![image](https://github.com/user-attachments/assets/e3880315-ddf7-4fde-ba3a-ae635c4e2e73)

**Comment by GoLD-ReaVeR** [comment]
I have the same issue, I launch my games in windowed mode so I can provide a little more curiosities:

I updated the nvidia driver to the latest version(560.28.03) yesterday. After doing this these problems started occurring. Updating Hyprland to the latest version (git) did not fix the problem. The proton logs are not providing any form of error message worth mentioning. However, all XWayland windows no longer take any mouse input while the game is running. The game does not respond to the window close command and seems to be completely hung. Games I've had this on are Granblue Fantasy Versus: Rising and it's predecessor. Both of these games are trying to obtain mouse control in a very ferocious manner despite being in windowed mode. Non-UE4/5 games seem unaffected (thus far). This problem happens both with Proton Experimental as well as the TKG variant of it.

**Comment by GoLD-ReaVeR** [comment]
@nonetrix can you try running steam with -steamos3 argument and see if that helps for you? My game (GBVSR) launched with no problems using it.

**Comment by Cloudperry** [comment]
I have this bug with Apex Legends. It just freezes as soon as the game launches and doesn't display any errors like in the first screenshot. For me input is not affected when the game is hung and I can only quit it with killall -KILL. I bisected this bug within #7151 using Apex Legends and found that the first bad commit is 158bbaaf88764e2a1e19ca1e3a11af541374432e. Before that commit Apex launches and works normally using explicit sync (other than a bug introduced yesterday by the season 22 update). Can someone else check if 2cfc6722fdbc93fd0c5987eeac0d4b96cd0128a7 works without freezes? I have an AMD GPU.

**Comment by nonetrix** [comment]
Try biding hyprctl kill to alt +f4 that's what I do :-)

**Comment by vaxerski** [comment]
cam you test git

**Comment by nonetrix** [comment]
Halo runs now but Need For Speed still broken for me

**Comment by GoLD-ReaVeR** [comment]
> cam you test git

Unless there was an update in the last 24h I'm running git.

**Comment by Cloudperry** [comment]
> cam you test git

Very nice, tested the commit from 12 minutes ago and Apex Legends is not freezing on start now.

**Comment by vaxerski** [comment]
> Unless there was an update in the last 24h I'm running git.

there were like 15 :)
![image](https://github.com/user-attachments/assets/7580f99c-2e25-40cc-92f7-48c51953cea1)

@Cloudperry great, thanks!

**Comment by nonetrix** [comment]
I was running a399f98c68d017152883fbf81d67624ac3254073 but ea728315410e220d73a993f17c83ae9dc9be9015 released I will try that, I still had issues with the latter actually with Need For Speed. Building now give my poor little Ryzen 7 3700x some time

**Comment by nonetrix** [comment]
Fixed!

**Comment by GoLD-ReaVeR** [comment]
I'll rebuild, I'm currently experiencing some very weird thing with a myriad of applications, chromium is locking up so are derivative applications like vesktop, skype and teams. Steam locked up (with the steamos3 flag) and trying to restart it popped the following error:
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadAlloc (insufficient resources for operation)
Major opcode of failed request:  150 (GLX)
Minor opcode of failed request:  5 (X_GLXMakeCurrent)
Serial number of failed request:  0
xerror_handler: X failed, continuing
src/steamexe/updateui_xwin.cpp (1502) : UpdateUI GL not available
src/steamexe/updateui_xwin.cpp (1502) : UpdateUI GL not available

**Comment by vaxerski** [comment]
yikes, tried disabling explicit sync?

**Comment by GoLD-ReaVeR** [comment]
I don't think I have explicit sync enabled, I have tearing allowed and vrr enabled for both my displays. GBVSR still is not running in x11 mode.

**Comment by vaxerski** [comment]
it's on by default

**Comment by GoLD-ReaVeR** [comment]
I'm stupid. How do I see the explicit sync status and how do I turn it off?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Configuring/Variables/#render

**Comment by GoLD-ReaVeR** [comment]
Alright, fiddling around with that seems to have locked up my system. After reboot I attempted running GBVSR again in x11 mode and it still is refusing to go beyond the black screen. Gonna set it to wayland mode and see if I can use the mouse now.

**Comment by GoLD-ReaVeR** [comment]
Somehow it got worse, the window if left unattended on another desktop will at some point timeout and crash the application. I'm also trying to make the window float because hyprland and the game are not agreeing on what resolution to go with and it causes the game to emit only one resolution to the user and it still fails to set set resolution. However, the game does not seem to have a class for me to latch onto.

**Comment by GoLD-ReaVeR** [comment]
The window manager is rather ferocious at the moment, it's even overriding gamescope's sizing and giving it a window size I did not request.

**Comment by GoLD-ReaVeR** [comment]
XWayland clients on my second display are no longer taking input.

**Comment by vaxerski** [comment]
#6860

**Comment by GoLD-ReaVeR** [comment]
I updated the nvidia drivers once again and it seems to have resolved (most) of my issues. I'm able to use the mouse on X applications on the secondary display again and GBVSR is no longer showing a black screen for me in x11 mode.

**Comment by GoLD-ReaVeR** [comment]
The mouse on second display problem came back. There is somewhat of a bug with my main TV that won't properly turn on unless it's the first in the chain to be turned on. I made a mistake and activated the secondary display too soon. Now X applications won't take input on the display that was not reactivated last (wlr-randr --output x --off; wlr-randr --output x --on).
