### ISSUE TITLE
mouse cursor is too small

### ISSUE THREAD

**Issue by Malek-Khaled** [hyprwm/Hyprland#7208]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch openSUSE at commit 0000000000000000000000000000000000000000  (Built for x86_64-suse-linux).
Date: Thu Jan 01 00:00:00 1970
Tag: 0.41.2, commits: -1

flags: (if any)

System Information:
System name: Linux
Node name: localhost.localdomain
Release: 6.10.2-1-default
Version: #1 SMP PREEMPT_DYNAMIC Mon Jul 29 08:51:47 UTC 2024 (65a34e2)

GPU information: 
1d:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240730"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240730"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240730:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240730"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"

plugins:

======Config-Start======

Config File: /home/malek/.config/hypr/hyprland.conf: Read Succeeded
# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf
source = ~/.cache/wal/hypr.conf

################
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-2,2560x1440@165,0x0,1.25,vrr,1
monitor=HDMI-A-1,2560x1080@60,2048x0,1

###################
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun

#################
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
exec-once = swww-daemon
exec-once = dunset
exec-once = polkit
exec-once = hypridle
exec-once = wal -R
exec=/usr/libexec/polkit-gnome-authentication-agent-1

#############################
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME.nvidia
env = XDG_SESSION_TYPE.wayland
env = GBM_BACKEND.nvidia-drm
env = NVD_BACKEND,direct

#####################
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $color0 $color1 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 3
        
        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

xwayland {
  force_zero_scaling = true
}

cursor {
    no_hardware_cursors = true
  }

#############
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us,ara
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

####################
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, C, exec, $terminal
bind = $mainMod, D, exec, firefox
bind = $mainMod, X, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, fullscreen,1
bind = $mainMod, V, togglefloating,
bind = $mainMod, B, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = Super,F10,sendshortcut,Ctrl_L&Shift_L,M,^(vesktop)$

bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

bind = Ctrl_L&Shift_L, S, exec, hyprshot -m region
bind = Ctrl_L&Shift_L, Pause, exec ,hyprshot -m output

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
 malek@localhost  ~  hyprctl systeminfo -c
Hyprland, built from branch openSUSE at commit 0000000000000000000000000000000000000000  (Built for x86_64-suse-linux).
Date: Thu Jan 01 00:00:00 1970
Tag: 0.41.2, commits: -1

flags: (if any)

System Information:
System name: Linux
Node name: localhost.localdomain
Release: 6.10.2-1-default
Version: #1 SMP PREEMPT_DYNAMIC Mon Jul 29 08:51:47 UTC 2024 (65a34e2)

GPU information: 
1d:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240730"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240730"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240730:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240730"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"

plugins:

======Config-Start======

Config File: /home/malek/.config/hypr/hyprland.conf: Read Succeeded
# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf
source = ~/.cache/wal/hypr.conf

################
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-2,2560x1440@165,0x0,1.25,vrr,1
monitor=HDMI-A-1,2560x1080@60,2048x0,1

###################
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun

#################
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
exec-once = swww-daemon
exec-once = dunset
exec-once = polkit
exec-once = hypridle
exec-once = wal -R
exec=/usr/libexec/polkit-gnome-authentication-agent-1

#############################
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME.nvidia
env = XDG_SESSION_TYPE.wayland
env = GBM_BACKEND.nvidia-drm
env = NVD_BACKEND,direct

#####################
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $color0 $color1 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 3
        
        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

xwayland {
  force_zero_scaling = true
}

cursor {
    no_hardware_cursors = true
  }

#############
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us,ara
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

####################
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, C, exec, $terminal
bind = $mainMod, D, exec, firefox
bind = $mainMod, X, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, fullscreen,1
bind = $mainMod, V, togglefloating,
bind = $mainMod, B, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = Super,F10,sendshortcut,Ctrl_L&Shift_L,M,^(vesktop)$

bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

bind = Ctrl_L&Shift_L, S, exec, hyprshot -m region
bind = Ctrl_L&Shift_L, Pause, exec ,hyprshot -m output

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

##############################
##############################

workspace=1 ,monitor:DP-2, default:true
workspace=2 ,monitor:DP-2
workspace=3 ,monitor:DP-2
workspace=4 ,monitor:DP-2
workspace=5 ,monitor:HDMI-A-1, default:true
workspace=6 ,monitor:HDMI-A-1
workspace=7 ,monitor:HDMI-A-1
workspace=8 ,monitor:HDMI-A-1

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

Config File: /home/malek/.cache/wal/hypr.conf: Read Succeeded
$color0 = rgb(0c091c)
$color1 = rgb(73438F)
$wallpaper = "/home/malek/Downloads/sa.jpg"### ### 

</details>

### Description

When I set the screen scale to 1.25 on my primary monitor the mouse cursor became very small on it, and when I restarted the computer the mouse cursor became small on the secondary monitor as well which is 1080p with a scale of 1.
I tried increasing the size of Hypercursor and Xcursor but it didn't solve the problem.
This problem does not occur in GTK programs.

### How to reproduce

I don't know, I have GNOME installed but I don't know if it is causing the problem or not

**Comment by PILIHU2022** [comment]
Hi! I have the same problem, but I fixed it. You just need to add this code into the `hyprland.conf` ```env = XCURSOR_SIZE,24```, '24' is the value of the cursor size

**Comment by PILIHU2022** [comment]
From [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Keywords/#setting-the-environment)
> You can use the env keyword to set environment variables at Hyprland’s start, e.g.:
```env = XCURSOR_SIZE,24```
You can also add a d flag if you want the env var to be exported to D-Bus (systemd only)
```envd = XCURSOR_SIZE,24```

It's a good habit to read the wiki first, if you still have the problem, then open an issue:)

**Comment by Malek-Khaled** [comment]
Thanks for trying to help me but I tried this solution before and it didn't work

**Comment by PILIHU2022** [comment]
> Thanks for trying to help me but I tried this solution before and it didn't work

Oh, I am sorry to hear that.
But have you tried to use `nwg-look` too change the size?

**Comment by PILIHU2022** [comment]
I tried it and it works

**Comment by Malek-Khaled** [comment]
This solution solves the problem of the GTK programs only, but the problem is with the cursor in the window manager.
This problem is strange because I installed Hyperland many times with the same hardware and it did not happen before.

**Comment by PILIHU2022** [comment]
> This solution solves the problem of the GTK programs only, but the problem is with the cursor in the window manager. This problem is strange because I installed Hyperland many times with the same hardware and it did not happen before.

I am sorry that I can't help you.
Hope you can fix it soon:)

**Comment by MahouShoujoMivutilde** [comment]
>  Hyprland, built from branch openSUSE at commit 0000000000000000000000000000000000000000 (Built for x86_64-suse-linux). Date: Thu Jan 01 00:00:00 1970 Tag: 0.41.2, commits: -1 

Are you just building it in some strange way, like downloading a git archive or is it susu stable v0.41.2 package?

Because if it isn't on stable

>  This problem does not occur in GTK programs.

https://github.com/hyprwm/Hyprland/issues/7162 was fixed recently, and it looked for me as cursor being small over my wallpaper (run by swaybg), but normal over e.g. waybar. 

But disregard the comment if it is on stable.

**Comment by Malek-Khaled** [comment]
> Are you just building it in some strange way, like downloading a git archive or is it susu stable v0.41.2 package?

No, I just installed it from the OpenSUSE repositories.

> https://github.com/hyprwm/Hyprland/issues/7162 was fixed recently

Oh, I think the problem is just that the update hasn't reached me yet.
Anyway, the problem suddenly resolved for me.
