### ISSUE TITLE
Moving focus using keybinds when there are two windows in the same workspace on some games causes them to black screen (Proton, Steam)

### ISSUE THREAD

**Issue by yorunoken** [hyprwm/Hyprland#7220]
### Regression?

No

### System Info and Version

Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)

System Information:
System name: Linux
Node name: arch
Release: 6.10.3-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:47:21 +0000

GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======
[hyprlock.txt](https://github.com/user-attachments/files/16535650/hyprlock.txt)

[keybindings.txt](https://github.com/user-attachments/files/16535651/keybindings.txt)

[windowrules.txt](https://github.com/user-attachments/files/16535652/windowrules.txt)

======Config-End========

### Description

when im playing titanfall2 and I use the keybinds to change focus to the next window, because there are two windows in the current workspace and because titanfall2 is fullscreen, it rotates the windows, causing titanfall2 to blackscreen.

I'd like to add that moving the focus to another monitor using the mouse, or changing workspaces using binds doesn't trigger this.

### How to reproduce

- Open titanfall 2
- have another window in the workspace (titanfall 2 will always have an empty EA window for some reason)
- use `movefocus, r` keybind to attempt to move focus to other monitor, or other apps
- in the current workspace, the windows will swap because they're both fullscreen
- watch as titanfall 2's screen turns completely black

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/03a145f7-ea8f-49e8-a809-a7e45760b6a1

**Comment by BluewyDiamond** [comment]
same, i don't remember the exact steps i do to produce this but to make it work again i either unfullscreen and refullscreen the game or move the focus between steam and the game

**Comment by vaxerski** [comment]
#6914

**Comment by yorunoken** [comment]
> #6914

isn't this issue for switching workspaces? I've opened a seperate issue because it doesn't happen on workspace switch.

**Comment by vaxerski** [comment]
it's related to focus changes

**Comment by yorunoken** [comment]
> it's related to focus changes

alright thank you
