### ISSUE TITLE
Startup Crash 0.42

### ISSUE THREAD

**Issue by Lanpingner** [hyprwm/Hyprland#7227]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
i cant run the command as Hyprland crashes
```

</details>

### Description

On Startup after i run Hyprland from tty, i am getting this error:
Hyprland: symbol lookup error: Hyprland: undefined symbol: _ZNK9Hyprutils4Math4CBox6extentEv

### How to reproduce

Start Hyprland from tty

### Crash reports, logs, images, videos

No crash report

**Comment by gulafaran** [comment]
thats a mismatch build issue with hyprland/hyprutils. rebuild hyprutils, rebuild hyprland.

**Comment by vaxerski** [comment]
as above

**Comment by Lanpingner** [comment]
Thanks for the quick response, idk why hyprutils didn't updated

**Comment by Hannes1909** [comment]
If it helps someone in the future, my dumb ass managed to install hyperutils-git from AUR alongside hyprland(-not-git) and aquamarine(-not-git) from extra:

`extra/aquamarine         0.4.1-1  -> 0.4.2-1
extra/hyprland           0.43.0-1 -> 0.44.0-1`

`aur/hyprutils-git 0.2.2.r0.gd97af4f6-1 (+7 2.57) (Installed)
    Hyprland utilities library used across the ecosystem
extra/hyprutils 0.2.3-1 (79.5 KiB 211.3 KiB) 
    Hyprland utilities library used across the ecosystem`

Hence version/repository/dependency mismatch.
