### ISSUE TITLE
Hyprland will not start - no seatd.sock file

### ISSUE THREAD

**Issue by Robertx999** [hyprwm/Hyprland#723]
Linux is running on VirtualBox
After installing the system i installed `hyprland` AUR package
And when i first started Hyprland it worked perfectly fine except alacritty wouldn't open even though i checked the keybind
then i installed and added `hyprpaper` and `waybar` to the `hyprland.conf` file:
![image](https://user-images.githubusercontent.com/26821114/192115979-bee347cf-c072-4c90-9bed-f67a43118841.png)

When i fired up Hyprland once again i could see the waybar but i think it froze because the keybinds didn't work so i had to force shutdown and boot the machine and once i did that and tried to run Hyprland i got this:
![image](https://user-images.githubusercontent.com/26821114/192115857-7943c661-bcfe-4f04-9290-eb557f658a08.png)

### Specs:
![image](https://user-images.githubusercontent.com/26821114/192123394-cdc95e87-ec97-4015-af76-4c03e463e99b.png)

**Comment by Dickby** [comment]
try setting the environment variable 
`LIBSEAT_BACKEND=logind`

**Comment by Robertx999** [comment]
after setting the environment variable:
![image](https://user-images.githubusercontent.com/26821114/192123614-80e2d4d9-ad14-4616-80f9-415e0e2c0bd8.png)

**Comment by Robertx999** [comment]
tried executing Hyprland using both bash and sh and both gave me this:

![image](https://user-images.githubusercontent.com/26821114/192123688-8a7a905e-7efd-4d2c-bfd4-8fa770865a67.png)

and so i got the core dump:

![Hyprland_coredump](https://user-images.githubusercontent.com/26821114/192123899-902e5238-a691-44f7-b18b-65e348d40355.png)

**Comment by vaxerski** [comment]
`WLR_RENDERER_ALLOW_SOFTWARE=1`

**Comment by Robertx999** [comment]
![image](https://user-images.githubusercontent.com/26821114/192149875-5e1c01c9-4c30-4223-8f14-bfe2744d6c90.png)

![image](https://user-images.githubusercontent.com/26821114/192149907-a573222a-cc8e-4dd8-8df3-7c8a3e5cd4ca.png)

![image](https://user-images.githubusercontent.com/26821114/192149921-74cfea4d-dd5b-4f05-a2f0-3abbcec0d444.png)

still the same problem(same coredump) remains

**Comment by Robertx999** [comment]
![image](https://user-images.githubusercontent.com/26821114/192150418-da5dd033-8daf-4f98-8b70-e68af0b02f2a.png)

**Comment by Estebiu** [comment]
I remember having this type of error and solving it by installing a polkit. Might work; might not work. Good luck

**Comment by Robertx999** [comment]
Unfortunately it didn't work. Error still stays the same

**Comment by dzintars** [comment]
![image](https://user-images.githubusercontent.com/547420/220744799-958ce67d-230b-43cc-b0bf-321c02c3179f.png)
![image](https://user-images.githubusercontent.com/547420/220745128-fa1e1f45-6040-486c-89c1-25e57fa8e676.png)

**Comment by EysseW** [comment]
I am getting this error, but I am on bare metal :/
I am pretty sure I have the proper AMD GPU drivers?
