### ISSUE TITLE
Binding mouse movement

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#724]
I'd be really interested in being able to bind movement of the mouse. For example, if I press ALT and move the mouse up while doing so, an application launcher could appear. Or we could make something like mouse scrolling on windows.

**Comment by Estebiu** [comment]
You could try using libinput-gestures, though I'm not sure if this can be done at this point.

**Comment by vaxerski** [comment]
that's something an app should do, not hyprland. If you're talking about something like that thing gnome has, yes, defo an app.

**Comment by EysseW** [comment]
What thing does gnome have?

**Comment by fufexan** [comment]
Super on GNOME brings up the Overview (workspaces + dock). Pressing it again opens up the app launcher.

**Comment by EysseW** [comment]
What has that got to do with mouse movement?

**Comment by EysseW** [comment]
Just to clear up what I mean, I want the ability to bind mouse movement. Not the application launcher. nwg-drawer exists. The two examples were only examples. For hyprland, I'd like to see a bind for mouse movement. This could loke something like:
`bindm=mouse:274,mouse-up,exec, wl-copy`. (For example)

**Comment by vaxerski** [comment]
that's not planned.

**Comment by EysseW** [comment]
That's a bummer. Thanks anyway!

**Comment by pauljhill** [comment]
I would also like this feature 
for example id like it to do a dual bind 

bind = $mainMod, R, exec, $menu
bind = $mainMod, R, move mouse to be over text field of menu

**Comment by izvyk** [comment]
> bind = $mainMod, R, move mouse to be over text field of menu

@pauljhill, his can be achieved with `movecursor` dispatcher. The line in your hyprland.conf would look like
`bind = $mainMod, R, movecursor, 500 100`
Where 500 and 100 are X and Y coordinates of the menu field.
Reference: https://wiki.hyprland.org/Configuring/Dispatchers/

But that's completely different thing. It moves the mouse when you press a shortcut. The author suggested to bind mouse move itself, which actually would be nice. Mouse gestures, kind of.

I'm looking for a way to run a script on DPMS status change. DPMS is turned on whenever a key is pressed or the mouse is moved. A custom layout works just fine for a key press, but for the mouse move... No idea. I would be grateful for any hints.

**Comment by ThatBlockyPenguin** [comment]
I would also appreciate this feature, if it ever gets reconsidered
