### ISSUE TITLE
waybar workspaces on nixos

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#725]
Hi, I'm having an issue related to [this](https://github.com/hyprwm/Hyprland/issues/672), in that on nixos waybar (+experimental) doesn't seem to recognise:
- the current workspace
- on-click actions

I know from the above thread the on-click actions are provided by extra patches - are these provided through the flake?

**Comment by vaxerski** [comment]
no they arent.

also,.it does recognise the active workspace, but the css class name is active iirc and not focused. See the wiki faq, it's in there.

**Comment by patrickaldis** [comment]
thanks, is there a way to get the on-click patches?

**Comment by vaxerski** [comment]
see the waybar-hyprland-git PKGBUILD on the AUR. It should be there.

**Comment by patrickaldis** [comment]
sorry, little bit of a newbie to nixos, do you mean I should be building the package straight from aur rather than using some nix derivation. Thanks for any help :)

**Comment by jdsee** [comment]
This might help: https://github.com/NixOS/nixpkgs/issues/157101#issuecomment-1399260749

**Comment by Sherly1001** [comment]
I am also facing this issue, and I resolved it by applying the [hyprctl.patch](https://aur.archlinux.org/cgit/aur.git/tree/hyprctl.patch?h=waybar-hyprland-git) to the package through [home-manager](https://github.com/nix-community/home-manager).

```nix
  programs.waybar.package = pkgs.waybar.overrideAttrs (oa: {
    mesonFlags = (oa.mesonFlags or  []) ++ [ "-Dexperimental=true" ];
    patches = (oa.patches or []) ++ [
      (pkgs.fetchpatch {
        name = "fix waybar hyprctl";
        url = "https://aur.archlinux.org/cgit/aur.git/plain/hyprctl.patch?h=waybar-hyprland-git";
        sha256 = "sha256-pY3+9Dhi61Jo2cPnBdmn3NUTSA8bAbtgsk2ooj4y7aQ=";
      })
    ];
  });

```
