### ISSUE TITLE
Display scaling broken with 0.42.0

### ISSUE THREAD

**Issue by LDAP** [hyprwm/Hyprland#7250]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 4b4971c06fb02df00a2bd20b6b47b5d0e7d799a7  (internal: introduce new types to avoid unsigned int rollover and signed int overflow (7216)).
Date: Thu Aug 8 21:01:50 2024
Tag: v0.42.0-2-g4b4971c0, commits: 5071

flags: (if any)


System Information:
System name: Linux
Node name: T480s-arch
Release: 6.10.3-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

I have a 1440p display that I run at 1080p:

```
monitor=eDP-1,1920x1080@60.0,0x0,1.0
```

Before 0.42. I could use this exact setting and everything, including X scaling, worked perfectly. Since the update 1.0 scaling displays everything much larger, and I need to set scaling to 1.25 (Does the resolution even apply?). However, now X scaling is broken and all Xwayland apps look bad.

### How to reproduce

- Have a 1440p screen
- Run it with the setting above
- Open a XWayland app like Signal

**Comment by vaxerski** [comment]
pass a trace log https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log

**Comment by LDAP** [comment]
[hyprland.log](https://github.com/user-attachments/files/16564063/hyprland.log)

> I assume 1080p is not listed in the EDID?

Right.

```
❯ hyprctl monitors
Monitor eDP-1 (ID 0):
	2560x1440@59.99800 at 0x0
	description: LG Display 0x058B
	make: LG Display
	model: 0x058B
	serial:
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.25
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@60.00Hz
```

The same was true for previous versions but it worked perfectly fine.

**Comment by vaxerski** [comment]
oops, typo in aq. Can you pull aquamarine-git and try again?

**Comment by RyuuyaS** [comment]
I have tested it and it fixes the problem.

**Comment by LDAP** [comment]
`[ERR] Custom resolution FAILED, falling back to preferred
[ERR] Monitor eDP-1 got an invalid requested mode: 1920x1080@60.000000, using the preferred one instead: 2560x1440@59.998001`

Installing the new aquamarine version should be enough? If so its not fixed on my end.

**Comment by vaxerski** [comment]
I've added a commit that should also log the modeline. Can you verify it's correct?

**Comment by LDAP** [comment]
[hyprland.log](https://github.com/user-attachments/files/16564742/hyprland.log)

How can I verify that it's correct? Using the setting `monitor=eDP-1,1920x1080@60.0,0x0,1.0` was what I used previously. (I can imagine that the refreshrate is wrong, since it uses 59.XXXX with 1440p)

**Comment by vaxerski** [comment]
looks like it's wrong, I've pushed a commit to aq, try now

**Comment by LDAP** [comment]
[hyprland.log](https://github.com/user-attachments/files/16565002/hyprland.log)

Works now! Thanks :)

**Comment by LDAP** [comment]
Sidenote: Issue #7234 was not resolved with this. The problem is I have a hard time getting a log since the screen does not turn back on and the log is erased at reboot. :(

**Comment by vaxerski** [comment]
ssh into the machine, you can `killall Hyprland`
