### ISSUE TITLE
Random crash while watching youtube live (firefox and brave both)

### ISSUE THREAD

**Issue by Quazi-Shams-Kabir** [hyprwm/Hyprland#7257]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: archbtw
Release: 6.10.3-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```
with -c flag
[sysinfo.txt](https://github.com/user-attachments/files/16564346/sysinfo.txt)

</details>

### Description

whenever i watch youtube live hyprland crashes and take me to tty, earlier the crash report was "Atomic commit failed, device resource busy" but I reinstalled arch and lost the reports, now I start hyprland using WLR_DRM_NO_ATOMIC, but it still crashes with new crash report

### How to reproduce

no idea, it's random

### Crash reports, logs, images, videos

[hyprlandCrashReport1171.txt](https://github.com/user-attachments/files/16564250/hyprlandCrashReport1171.txt)

**Comment by ikalco** [comment]
update to v0.42.0 or git and retry

**Comment by Quazi-Shams-Kabir** [comment]
not sure if Issue is solved or not after installing hyprland-git, no  crash while watching youtube live atleast, but it crashed only once while I was testing git version with a long youtube video, 
[hyprlandCrashReport658.txt](https://github.com/user-attachments/files/16570436/hyprlandCrashReport658.txt)
that crash threw me to tty with this message
![WhatsApp Image 2024-08-10 at 23 07 57](https://github.com/user-attachments/assets/d4744a6b-5add-4042-ad46-6dc87fe58e16)
but after rebooting again no crash yet

**Comment by gulafaran** [comment]
kinda need the debug symbols to figure that one out

**Comment by Quazi-Shams-Kabir** [comment]
How to do that? I need to make hyprland in debug mode or something?

**Comment by ikalco** [comment]
https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by Quazi-Shams-Kabir** [comment]
thanks, but no crash since then...will wait for crash( hope not )

**Comment by Quazi-Shams-Kabir** [comment]
crashed again while watching yt on firefox
updated today:- hyprland-git 0.42.0.r18.3b4aabe0-1
crash log:- 
[hyprlandCrashReport1157.txt](https://github.com/user-attachments/files/16609127/hyprlandCrashReport1157.txt)
bt -full log:- 
[btlog.txt](https://github.com/user-attachments/files/16609134/btlog.txt)

**Comment by vaxerski** [comment]
what the fuck is that log tail christ, do you have tearing or direct scanout enabled? Try disabling both

**Comment by Quazi-Shams-Kabir** [comment]
tearing is set to false in my config, and haven't set anything for direct scanout,
I used to start hyprland with WLR_DRM_NO_ATOMIC before 0.42 to not get this type of log,
you said AQ_NO_ATOMIC not recommended so haven't tried yet

**Comment by vaxerski** [comment]
so it did happen without the no_atomic env on wlroots? Sounds like a driver shitting itself?

**Comment by Quazi-Shams-Kabir** [comment]
closing cuz it was firefox issue on wayland which seems like solved now.
