### ISSUE TITLE
xwayland windows not opening

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#726]
Currently, I cannot open any xwayland windows, with each one giving some variation of `cannot open display` in command line

For example, when running **spotify** from command line:
Command Output:
```
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify

(spotify --force-device-scale-factor=2:6): Gtk-WARNING **: 10:26:05.703: cannot open display: :99.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
Hyprland logs:
```
[LOG] Window 262c730 set title to flatpak run com.spot ~
[LOG] Window 262c730 set title to ~
[LOG] New XWayland Surface created (class (null)).
[LOG] Registered signal for owner 25fbaa0: 2657d38 -> 25fbb08 (owner: XWayland Window)
[LOG] Registered signal for owner 25fbaa0: 2657d48 -> 25fbb70 (owner: XWayland Window)
[LOG] Registered signal for owner 25fbaa0: 2657cb8 -> 25fbbd8 (owner: XWayland Window)
[LOG] Window 25fbaa0 destroyed, queueing. (class unmanaged X11)
[LOG] XWayland class raw: (null)
[LOG] Callback 25fbb30 -> 25fbb28, XWayland Window removed.
[LOG] Callback 25fbb98 -> 25fbb90, XWayland Window removed.
[LOG] Callback 25fbc00 -> 25fbbf8, XWayland Window removed.
```

Or when running **emacs**:
Command output:
```
(emacs:111040): Gtk-WARNING **: 10:30:55.807: cannot open display: :0
```

Hyprland Logs:
```
[LOG] Window 262c730 set title to emacs ~
[LOG] Window 262c730 set title to ~
```

**Comment by Estebiu** [comment]
Did you try setting this in your config?
 `exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`

**Comment by patrickaldis** [comment]
both settings are enabled in the config sadly :(

**Comment by Estebiu** [comment]
Did you try installing "libcurl-gnutls" (if you're on arch)? 
Though it should be already installed by default

**Comment by patrickaldis** [comment]
I think it's already installed - I've installed spotify through the flatpak so that should be taken care of. It seems to be something specific with xorg windows

**Comment by Estebiu** [comment]
Could you try setting manually the display then? 
Like that: "export DISPLAY=:0.0"

**Comment by patrickaldis** [comment]
I've tried setting the display manually, but this doesn't do anything - still get the same error messages

**Comment by patrickaldis** [comment]
Will it make a difference if I'm using the flake or not?

**Comment by CrezyDud** [comment]
why are you using flatpak if you've got aur?
aur has arch specific things to solve your things

**Comment by fufexan** [comment]
> Will it make a difference if I'm using the flake or not?

If you're on Nix, yes. Please use the flake. The nixpkgs version is very old.

**Comment by jwijenbergh** [comment]
My emacs wasn't starting as well. Make sure to NOT set `GDK_BACKEND` globally, GTK automatically picks the right backend anyways. For emacs this breaks if you don't have the pgtk build
This properly has to be changed in the nix module @fufexan https://github.com/hyprwm/Hyprland/blob/a97621b1cb203b0e3a7dd07d88c5422b798cbfd8/nix/module.nix#L50

See: https://github.com/keybase/client/issues/19614#issuecomment-535572603

**Comment by patrickaldis** [comment]
Thanks, in the end I switched to the flake, as @fufexan suggested. This fixed the issue

**Comment by Narice** [comment]
Xserver would not start (I primarly use xfce+i3) due to the environment variables that are set in the module as said by @jwijenbergh, and I was getting the same errors.
@fufexan  I can attest that the change proposed by @jwijenbergh works.
I'll try making a pull request for that change.
