### ISSUE TITLE
Apps crashing because of memory error on Asahi

### ISSUE THREAD

**Issue by RandomPinkPeep** [hyprwm/Hyprland#7273]

**Comment by MariaSolOs** [comment]
Same here. I updated to 0.42 and now I'm unable to launch anything, or apps will just flash with a strange magenta background.

**Comment by vaxerski** [comment]
please use the template

**Comment by as400l** [comment]
Magenta background on asahi signal gpu driver problems. Possibly oom situation.

**Comment by jswent** [comment]
Also having this problem. Anything I can do to help provide info?

**Comment by vaxerski** [comment]
it's fixed on git
