### ISSUE TITLE
High Resolution Wheel

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#728]
It would be nice to see high resolution wheel support for the few mouses that supports it.
If I'm not mistaken, gnome just added it in their newer release, and there should already be support for this in wayland/libinput.
Here's other information in cause you're curious: https://who-t.blogspot.com/2021/08/libinput-and-high-resolution-wheel.html

**Comment by Philipp-M** [comment]
I think theoretically, Hyprland should support this as the version of wlroots Hyprland uses supports it already, but I haven't gotten it to to work, or I don't know how to setup firefox with wayland correctly (where it works on X with `MOZ_USE_XINPUT2=1`). Does anyone know how to properly test this (e.g. an application that works on other wayland compositors)?

**Comment by Philipp-M** [comment]
This can be closed.

Hyprland already supports high resolution scroll, I just tested it with a gtk4 app, but it seems that unfortunately a lot of applications aren't up to date with the wayland specification including firefox, they require at least the feature `wl_pointer::axis_value120` which needs `wl_pointer version 8` or later (firefox still uses version 5).
