### ISSUE TITLE
Missing animation for window dimming when using gestures

### ISSUE THREAD

**Issue by Rdeisenroth** [hyprwm/Hyprland#729]
## Steps to reproduce

- Set `dim_inactive` to true (and set `dim_strength` to a high value to notice it easier)
- enable `workspace_swipe`
- open multiple windows on two workspaces
- swipe towards another workspace with active windows completely without releasing the fingers
- now release the fingers
## Noted outcome
The new active window jumps from a dimmed state straight to the undimmed state, which feels wrong.
## Expected outcome
Either the new active window should already be undimmed when swiping or it should play the fading animation for dimming that is also present when switching focus within a single workspace.
I would personally really like to see a 1:1 dimming strength for the new active window based on the swiping progress but that would probably be more work.

PS: I have just started to use Hyprland on my laptop (sadly with nvidia) today and like it just can't get enough of these gorgeous animations :D

**Comment by vaxerski** [comment]
you probably have disabled the `fadeDim` animation.
