### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by Dickby** [hyprwm/Hyprland#730]
Would you accept a pr that deletes all the trailing whitespaces?
My editor is doing that by itself, and i have to undo it manually before every commit.

**Comment by fufexan** [comment]
Sounds good.

**Comment by Dickby** [comment]
@fufexan : is that a go, or should i wait for vaxersky's approval?

**Comment by fufexan** [comment]
If your editor does that by itself, I think it won't take too much of your time to make a PR. Vaxry can then merge it or close it.

**Comment by vaxerski** [comment]
ok
