### ISSUE TITLE
Hyprpm doesn't update well.

### ISSUE THREAD

**Issue by YuvanMichael** [hyprwm/Hyprland#7302]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
  Arch Linux x86_64
  Linux 6.10.4-zen2-1-zen
   1730 (pacman)
              `+oooooo:                   └   ➜  bash 5.2.32
              -+oooooo+:
            `/:-:++oooo+:                WM    ➜  Hyprland (Wayland)
           `/++++/+++++++:                ├ 󰀻  ➜  Papirus-Dark [GTK2/3], breeze [GTK4]
          `/++++++++++++++:               ├   ➜  breeze (24px)
         `/+++ooooooooooooo/`             ├   ➜  alacritty 0.13.2
        ./ooosssso++osssssso+`            └   ➜  FiraCode Nerd Font (12.0pt)
       .oossssso-````/ossssss+`
      -osssssso.      :ssssssso.         PC    ➜  ASUSTeK COMPUTER INC. X Type X200MA
     :osssssss/        osssso+++.         ├   ➜  Intel(R) Celeron(R)  N2840 (2) @ 2.58 GHz GHz
    /ossssssss/        +ssssooo/-         ├ 󰢮  ➜  Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display @ 0.79 GHz GHz
  `/ossssso+/:-        -:/+osssso+-       ├   ➜  1.13 GiB / 1.81 GiB (62%)
 `+sso+:-`                 `.-/+oso:      ├ 󰓡  ➜  608.84 MiB / 926.50 MiB (66%)
`++:.                           `-/+/     ├ 󰋊  ➜  72.05 GiB / 252.68 GiB (29%) - ext4
.`                                 `/     └   ➜  1366x768 px @ 59.799 Hz - 260x140 mm (11.63 inches, 134.79 ppi)

</details>

### Description

Everything seems to work, yet the hyprtrails plugin is not loaded. I've rebuilt hyprland and re-enabled the plugin. But it still doesn't work. 

### How to reproduce

Run hyprpm update on the latest git version of Hyprland

### Crash reports, logs, images, videos

hyprpm update
✔ Headers up to date.

 → checking for updates for hyprland-plugins
 → Cloning https://github.com/hyprwm/hyprland-plugins
✔ repository hyprland-plugins is up-to-date.
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4 / 4  Done!
✔ Ensuring plugin load state
✔ Loaded hyprtrails
✔ Plugin load state ensured
```

**Comment by YuvanMichael** [comment]
> hyprpm add https://github.com/hyprwm/hyprland-plugins
✔ adding a new plugin repository from https://github.com/hyprwm/hyprland-plugins
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/hyprwm/hyprland-plugins
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 6 plugins:
 → borders-plus-plus by Vaxry version
 → csgo-vulkan-fix by Vaxry version
 → hyprbars by Vaxry version
 → hyprexpo by Vaxry version
 → hyprtrails by Vaxry version
 → hyprwinwrap by Vaxry version
 → Manifest has 16 pins, checking
✔ Hyprland headers OK
 → Building borders-plus-plus
✖ Plugin borders-plus-plus failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building csgo-vulkan-fix
✖ Plugin csgo-vulkan-fix failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprbars
✖ Plugin hyprbars failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprexpo
✖ Plugin hyprexpo failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprtrails
✖ Plugin hyprtrails failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprwinwrap
✖ Plugin hyprwinwrap failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!

**Comment by YuvanMichael** [comment]
! removing a plugin repository: https://github.com/hyprwm/hyprland-plugins
  Are you sure? [Y/n] y
[v] version returned: Hyprland, built from branch main at commit 4b4971c06fb02df00a2bd20b6b47b5d0e7d799a7  (internal: introduce new types to avoid unsigned int rollover and signed int overflow (7216)).
Date: Fri Aug 9 00:31:50 2024
Tag: v0.42.0-2-g4b4971c0, commits: 5071

flags: (if any)


[v] parsed commit 4b4971c06fb02df00a2bd20b6b47b5d0e7d799a7 at branch main on Fri Aug 9 00:31:50 2024, commits 5071
✔ adding a new plugin repository from https://github.com/hyprwm/hyprland-plugins
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/hyprwm/hyprland-plugins
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 6 plugins:
 → borders-plus-plus by Vaxry version
 → csgo-vulkan-fix by Vaxry version
 → hyprbars by Vaxry version
 → hyprexpo by Vaxry version
 → hyprtrails by Vaxry version
 → hyprwinwrap by Vaxry version
 → Manifest has 16 pins, checking
✔ Hyprland headers OK
 → Building borders-plus-plus
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/yuvan && PKG_CONFIG_PATH="/home/yuvan/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C borders-plus-plus all
make: Entering directory '/tmp/hyprpm/yuvan/borders-plus-plus'
g++ -shared -fPIC --no-gnu-unique main.cpp borderDeco.cpp -o borders-plus-plus.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -O2
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from main.cpp:6:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/../../debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/../../defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:4,
                 from borderDeco.hpp:5,
                 from borderDeco.cpp:1:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/../../debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
make: Leaving directory '/tmp/hyprpm/yuvan/borders-plus-plus'


✖ Plugin borders-plus-plus failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building csgo-vulkan-fix
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/yuvan && PKG_CONFIG_PATH="/home/yuvan/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C csgo-vulkan-fix all
make: Entering directory '/tmp/hyprpm/yuvan/csgo-vulkan-fix'
g++ -shared -fPIC --no-gnu-unique main.cpp -o csgo-vulkan-fix.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -O2
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from main.cpp:5:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
make: Leaving directory '/tmp/hyprpm/yuvan/csgo-vulkan-fix'


✖ Plugin csgo-vulkan-fix failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprbars
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/yuvan && PKG_CONFIG_PATH="/home/yuvan/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C hyprbars all
make: Entering directory '/tmp/hyprpm/yuvan/hyprbars'
g++ -shared -fPIC --no-gnu-unique -g -std=c++2b -Wno-c++11-narrowing `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` main.cpp barDeco.cpp  -o hyprbars.so `pkg-config --libs pangocairo` -O2
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from main.cpp:6:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/../../debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/../../defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:4,
                 from barDeco.hpp:5,
                 from barDeco.cpp:1:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/render/decorations/../../debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:11: hyprbars.so] Error 1
make: Leaving directory '/tmp/hyprpm/yuvan/hyprbars'


✖ Plugin hyprbars failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprexpo
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/yuvan && PKG_CONFIG_PATH="/home/yuvan/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C hyprexpo all
make: Entering directory '/tmp/hyprpm/yuvan/hyprexpo'
g++ -shared -fPIC --no-gnu-unique main.cpp overview.cpp -o hyprexpo.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -Wno-narrowing
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from main.cpp:5:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/../debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/../defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/PluginAPI.hpp:26,
                 from globals.hpp:3,
                 from overview.hpp:5,
                 from overview.cpp:1:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/../debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
make: Leaving directory '/tmp/hyprpm/yuvan/hyprexpo'


✖ Plugin hyprexpo failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprtrails
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/yuvan && PKG_CONFIG_PATH="/home/yuvan/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C hyprtrails all
make: Entering directory '/tmp/hyprpm/yuvan/hyprtrails'
g++ -shared -fPIC --no-gnu-unique main.cpp trail.cpp -o hyprtrails.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -O2
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from main.cpp:6:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/../debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/../defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/PluginAPI.hpp:26,
                 from trail.hpp:6,
                 from trail.cpp:1:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/plugins/../debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
make: Leaving directory '/tmp/hyprpm/yuvan/hyprtrails'


✖ Plugin hyprtrails failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

 → Building hyprwinwrap
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/yuvan && PKG_CONFIG_PATH="/home/yuvan/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C hyprwinwrap all
make: Entering directory '/tmp/hyprpm/yuvan/hyprwinwrap'
g++ -shared -fPIC --no-gnu-unique main.cpp -o hyprwinwrap.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -O2
In file included from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/Log.hpp:9,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:2,
                 from /home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from main.cpp:11:
/home/yuvan/.local/share/hyprpm/headersRoot/include/hyprland/src/debug/../helpers/MiscFunctions.hpp:9:10: fatal error: SharedDefs.hpp: No such file or directory
    9 | #include "SharedDefs.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
make: Leaving directory '/tmp/hyprpm/yuvan/hyprwinwrap'


✖ Plugin hyprwinwrap failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!

**Comment by YuvanMichael** [comment]
I've even tried on another system with my portable ssd. But it still didn't work there either.

**Comment by vaxerski** [comment]
fixed in git already
