### ISSUE TITLE
Crash after update - m_sWLRRenderer was NULL! (AMD/NixOS)

### ISSUE THREAD

**Issue by Nocxium** [hyprwm/Hyprland#7303]
### Regression?

No

### System Info and Version

System Info and Version - Cant paste it since i cant get in to hyprland :/

### Description

As soon as i try to log in, it crashes. Have been using hyprland without any issues for over a year now.
This issue happens on both my laptop and desktop.

### How to reproduce

Updating on Nixos? On my desktop i have AMD r290, and in my laptop a intel UHD 620

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Oops

Hyprland received signal 6(ABRT)
Version: 918d8340afd652b011b937d29d5eea0be08467f5
Tag: v0.41.2

System info:
	System name: Linux
	Node name: oxygen
	Release: 6.10.3
	Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 07:01:09 UTC 2024

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] [8086:3ea0] (rev 02) (prog-if 00 [VGA controller])

os-release:
	ANSI_COLOR="1;34"
	BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
	BUILD_ID="24.11.20240809.5e0ca22"
	DOCUMENTATION_URL="https://nixos.org/learn.html"
	HOME_URL="https://nixos.org/"
	ID=nixos
	IMAGE_ID=""
	IMAGE_VERSION=""
	LOGO="nix-snowflake"
	NAME=NixOS
	PRETTY_NAME="NixOS 24.11 (Vicuna)"
	SUPPORT_URL="https://nixos.org/community.html"
	VERSION="24.11 (Vicuna)"
	VERSION_CODENAME=vicuna
	VERSION_ID="24.11"
Backtrace:
	# | /home/nocxium/.nix-profile/bin/hyprland(_Z12getBacktracev+0x48) [0x6dde98]
		getBacktrace()
		??:?
	#1 | /home/nocxium/.nix-profile/bin/hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x805) [0x6461a5]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | /home/nocxium/.nix-profile/bin/hyprland(_Z25handleUnrecoverableSignali+0x5f) [0x5c2fcf]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52/lib/libc.so.6(+0x3ff40) [0x7efdf9b6ef40]
		??
		??:0
	#4 | /nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52/lib/libc.so.6(+0x8fefc) [0x7efdf9bbeefc]
		??
		??:0
	#5 | /nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52/lib/libc.so.6(gsignal+0x16) [0x7efdf9b6ee96]
		??
		??:0
	#6 | /nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52/lib/libc.so.6(abort+0xd7) [0x7efdf9b57935]
		??
		??:0
	#7 | /nix/store/bn7pnigb0f8874m6riiw6dngsmdyic1g-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xacc2b) [0x7efdf9eacc2b]
		??
		??:0
	#8 | /nix/store/bn7pnigb0f8874m6riiw6dngsmdyic1g-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xbc20a) [0x7efdf9ebc20a]
		??
		??:0
	#9 | /nix/store/bn7pnigb0f8874m6riiw6dngsmdyic1g-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xbc275) [0x7efdf9ebc275]
		??
		??:0
	#1 | /nix/store/bn7pnigb0f8874m6riiw6dngsmdyic1g-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xbc4c7) [0x7efdf9ebc4c7]
		??
		??:0
	#11 | /home/nocxium/.nix-profile/bin/hyprland() [0x5368df]
		throwError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold]
		??:?
	#12 | /home/nocxium/.nix-profile/bin/hyprland(_ZN11CCompositor10initServerEv+0x2ae) [0x5d52ee]
		CCompositor::initServer()
		??:?
	#13 | /home/nocxium/.nix-profile/bin/hyprland(main+0x75e) [0x58645e]
		main
		??:?
	#14 | /nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52/lib/libc.so.6(+0x2a10e) [0x7efdf9b5910e]
		??
		??:0
	#15 | /nix/store/dbwp0scbb0rk78m636sb7cvycz8xzgyh-glibc-2.39-52/lib/libc.so.6(__libc_start_main+0x89) [0x7efdf9b591c9]
		??
		??:0
	#16 | /home/nocxium/.nix-profile/bin/hyprland(_start+0x25) [0x5c2e15]
		_start
		??:?

Log tail:
[LOG] Runtime directory: /run/user/1000/hypr/918d8340afd652b011b937d29d5eea0be08467f5_1723483233_1144728031
[LOG] Hyprland PID: 3338
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: oxygen
[LOG] Release: 6.10.3
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 07:01:09 UTC 2024

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] [8086:3ea0] (rev 02) (prog-if 00 [VGA controller])

[LOG] os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240809.5e0ca22"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: "I think I am addicted to hyprland" - mathisbuilder

[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 21.41µs. Estimated average calc time: 0.04µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 11.57µs. Estimated average calc time: 0.04µs.
[LOG] Using config: /home/nocxium/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 11.44µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/nocxium/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 11.59µs. Estimated average calc time: 0.04µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the PointerManager!
[render/egl.c:208] EGL_EXT_platform_base not supported
[render/egl.c:536] Failed to create EGL context
[render/gles2/renderer.c:503] Could not initialize EGL
[render/egl.c:208] EGL_EXT_platform_base not supported
[render/egl.c:536] Failed to create EGL context
[render/gles2/renderer.c:503] Could not initialize EGL
[CRITICAL] m_sWLRRenderer was NULL! This usually means wlroots could not find a GPU or enountered some issues.
[CRITICAL] Critical error thrown: wlr_gles2_renderer_create_with_drm_fd() failed!

**Comment by vaxerski** [comment]
old hl version

at any rate, this is a problem with your driver

**Comment by partisani** [comment]
i am having the same issue, but what do you mean by "hl"? (my gpu is an Intel HD Graphics 4600)

**Comment by vaxerski** [comment]
hyprland
