### ISSUE TITLE
Border_size isn't scaling across displays

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#731]
Steps to reproduce: have 2 displays with 2 different scaling settings, in this case one 4k with 2x scaling and a fhd one with 1x scaling
Expected outcome: general:border_size is costant across different scalings
Noted outcome: on the scale 1 monitor the borders will be two times bigger than on the scale 2 monitor.

It just feels wrong; above all since gaps_out and gaps_in are perfectly synchronized between different displays with different scaling but that doesn't apply to border_size.

**Comment by vaxerski** [comment]
is this a regression?

**Comment by Dickby** [comment]
Could be, shit.
But it devides by the monitor scale in applyNodeDataToWindow,
shouldn't that work for multiple monitors? 
I can't test that myself

**Comment by Dickby** [comment]
I think it should work @Estebiu can you check without borders if it's the same thing with gaps between windows?

**Comment by Dickby** [comment]
@vaxerski 
I just realized that the gaps between the windows are scaled too.
So the borders are now not changing the window gap size if the monitor is scaled,
but the scaling itself is scaling the gaps. 
I'm not shure what you want the scaling thing to be. should it look like a zoomed in Monitor, or 
should everything stay the same but the window content?

By the way @Estebiu how old is your build?

**Comment by Estebiu** [comment]
I'm running the latest hyprland-git package from the AUR.

I'd like if the border_size would scale across displays as gaps_in and gaps_out are already doing. So if you have a border_size of 4 on the config file, that should be doubled on the 4k scaled to 200% display.

**Comment by Dickby** [comment]
@vaxerski , i think that is what my former pr was doing.
Two monitors of different physical size with different resolution could look similar by scaling
if the borders are scaled itself.
What i was aiming for was same window size and decorations on similar monitors with different scaling.
Now that i understand the use case (if it's meant to do what Estebiu wants),
what i did was just silly.
I don't use multiple Monitors, and just assumed that it should not change the sizes of the window,
when playing with scaling.
The behavior that @Estebui wants would be much simpler to implement.
If i'm not mistaken, it would only need the older closed pull request.
Will be a quick revert/fix if this is what is wanted.

**Comment by vaxerski** [comment]
prolly

**Comment by Estebiu** [comment]
Love you guys, thanks.
