### ISSUE TITLE
crash immediately after the launch of hyprland 0.42.0

### ISSUE THREAD

**Issue by iamdenchik** [hyprwm/Hyprland#7311]
### Regression?

No

### System Info and Version

I can't run hyprctl systeminfo -c
yet. I will rebuild hyprland in the near future and reboot to version 0.42.0

version 0.41.2 is fully functional

### Description

installing from home-manager on nixos

```
{
  description = "Home Manager configuration of admin";

  inputs = {
    # Specify the source of Home Manager and Nixpkgs.
    # nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1&ref=main&rev=9a09eac79b85c846e3a865a9078a3f8ff65a9259"; # 0.42.0
  };
  ```
  
  after the reboot in the console, I run hyrpland and immediately crush

### How to reproduce

run ./hyprland

### Crash reports, logs, images, videos

[hyprlandCrashReport2138.txt](https://github.com/user-attachments/files/16594582/hyprlandCrashReport2138.txt)

**Comment by iamdenchik** [comment]
@sjcobb2022 Hello! I tried two options and both don't work

```
  inputs = {
    # Specify the source of Home Manager and Nixpkgs.
    # nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/hyprland";
      rev = "9a09eac79b85c846e3a865a9078a3f8ff65a9259";
      submodules = true;
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
```

```
  inputs = {
    # Specify the source of Home Manager and Nixpkgs.
    # nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

     aquamarine = {
      url = "github:hyprwm/aquamarine";
      inputs.nixpkgs.follows = "nixpkgs";
     };

     hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/hyprland";
      rev = "9a09eac79b85c846e3a865a9078a3f8ff65a9259";
      submodules = true;
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.aquamarine.follows = "aquamarine";
    };
  };
```

crash logs: 
[hyprlandCrashReport13016.txt](https://github.com/user-attachments/files/16607609/hyprlandCrashReport13016.txt)
[hyprlandCrashReport2085.txt](https://github.com/user-attachments/files/16607614/hyprlandCrashReport2085.txt)

**Comment by sjcobb2022** [comment]
Because you are using nixpkgs as nixpkgs-unstable.

You need to use nixos-24.05 or another stable branch.

**Comment by gunererd** [comment]
I also begin to have same problem but I'm not using nix. I'm using AUR package.

> [CRITICAL] m_pAqBackend couldn't start! This usually means aquamarine could not find a GPU or encountered some issues. Make sure you're running either on a tty or on a Wayland session, NOT an X11 one.

**Comment by iamdenchik** [comment]
work config:

```
  inputs = {
    # Specify the source of Home Manager and Nixpkgs.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    home-manager = {
      type = "git";
      url = "https://github.com/nix-community/home-manager";
      ref = "release-24.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/hyprland";
      rev = "9a09eac79b85c846e3a865a9078a3f8ff65a9259"; # v0.42.0
      submodules = true;
      inputs.nixpkgs.follows = "nixpkgs";

    };
...
    ```

**Comment by sjcobb2022** [comment]
> I also begin to have same problem but I'm not using nix. I'm using AUR package.
> 
> > [CRITICAL] m_pAqBackend couldn't start! This usually means aquamarine could not find a GPU or encountered some issues. Make sure you're running either on a tty or on a Wayland session, NOT an X11 one.
> 
> 

Try using hyprland-git and aquamarine-git
