### ISSUE TITLE
hyprland crashes on startup after 0.42.0 update

### ISSUE THREAD

**Issue by nergdron** [hyprwm/Hyprland#7325]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

can't run hyprland to supply systeminfo output, it's version 0.42.0-1 on Arch.

</details>

### Description

hyprland constantly crashes on startup after upgrade to 0.42.0.

### How to reproduce

on my system, 100% of the time. last line of the crash log just said it loaded my xcursor theme, there's no obvious errors, so it's unclear what's happening or why. was working fine on 0.41 before I upgraded.

### Crash reports, logs, images, videos

[hyprlandCrashReport116828.txt](https://github.com/user-attachments/files/16605298/hyprlandCrashReport116828.txt)

**Comment by nergdron** [comment]
downgraded to this previous arch package, and everything works fine again:
https://archive.archlinux.org/packages/h/hyprland/hyprland-0.41.2-3-x86_64.pkg.tar.zst

**Comment by ikalco** [comment]
somehow I found [Bibata_Ghost](https://github.com/Silicasandwhich/Bibata_Cursor_Translucent) and it seems broken
`/usr/share/icons/Bibata_Ghost/cursors/diamond_cross: broken symbolic link to diamond_cross`

but Hyprland shouldn't crash so i'll make pr

**Comment by nergdron** [comment]
interesting remnants of an old package on my system, odd. thanks for the quick diagnosis, now that I know what's causing the crash I should be able to clean it up on my end.
