### ISSUE TITLE
Screen cast not working in OBS

### ISSUE THREAD

**Issue by Swomp2** [hyprwm/Hyprland#7328]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: swomp-pc
Release: 6.6.45_1
Version: #1 SMP PREEMPT_DYNAMIC Mon Aug 12 14:22:41 UTC 2024


GPU information: 
08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"


plugins:

```

</details>

### Description

When I try to capture the screen in dropdown menu, obs shows only black screen and don't record screen or sound (on screenshots I didn't select audio device, but it doesn't work at all when I try)

![2024-08-14-021658_hyprshot](https://github.com/user-attachments/assets/be72bf31-a070-4850-8634-6aac0e6e8304)
![2024-08-14-021643_hyprshot](https://github.com/user-attachments/assets/38f6a404-8897-45c9-9507-13e3e86f5b71)
![2024-08-14-021711_hyprshot](https://github.com/user-attachments/assets/0a018df5-6682-431a-957f-1dd805f52e7c)

### How to reproduce

1. Open OBS
2. Try to select monitor or window
3. Press OK

### Crash reports, logs, images, videos

STATE_NONE

[LOG] [GammaControl] setGamma for DP-1
[LOG] [GammaControl] setting to monitor DP-1
[LOG] [WLCompositor] New wl_region with id 69 at 562c9abf2640
[LOG] [WLCompositor] New wl_region with id 69 at 562c9c9d8780
[LOG] [WLCompositor] New wl_region with id 69 at 562c9bc50660
[LOG] [GammaControl] setGamma for DP-1
[LOG] [GammaControl] setting to monitor DP-1
[LOG] [WLCompositor] New wl_region with id 69 at 562c9c90acd0
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 135
[LOG] Searching for matching rules for Firefox (title: New Issue · hyprwm/Hyprland — Mozilla Firefox)
[LOG] [WLDataDevice] New offer 562c9c9dc180 for data source 562c9c9b8440
[LOG] [WLDataDevice]  | offer 562c9c9dc180 supports mime image/png
[LOG] Set keyboard focus to surface 562c9b97f470, with [Window 562c9c16e690: title: "~"]
[LOG] Searching for matching rules for kitty (title: ~)
[LOG] [PrimarySelection] New offer 562c9c5d9130 for data source 562c9bd01290
[LOG] [seatmgr] Rejecting a setCursor because the client ain't in focus
[LOG] cursorImage request: shape 9 -> text
[LOG] CWLSurface 562c9b8026a0 called destroy()
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 135
[LOG] cursorImage request: shape 9 -> text
[LOG] [XDGShell] xdg_surface 562c9bcaab30 requests geometry 0x0 1140x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [WLCompositor] New wl_region with id 69 at 562c9c44e730
[LOG] [LinuxDMABUF] Creating a dmabuf, with id 60: size [Vector2D: x: 1396, y: 1396], fmt AR24, planes 2
[LOG] [LinuxDMABUF]  | plane 0: mod 144115188486290179 fd 119 stride 5632 offset 0
[LOG] [LinuxDMABUF]  | plane 1: mod 144115188486290179 fd 121 stride 1536 offset 7929856
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [XDGShell] xdg_surface 562c9aed4e30 requests geometry 0x0 1396x1396
[LOG] [GammaControl] setGamma for DP-1
[LOG] [GammaControl] setting to monitor DP-1
[LOG] cursorImage request: surface 0
[LOG] Hiding the cursor (hl-mandated)
[LOG] [GammaControl] setGamma for DP-1
[LOG] [GammaControl] setting to monitor DP-1

**Comment by Swomp2** [comment]
On newer kernel it doesn't work:(

**Comment by Swomp2** [comment]
Just reinstall obs from flathub and it will work :)

**Comment by Swomp2** [comment]
Just reinstall obs from flathub and it will work :)

**Comment by nikhil1xiz** [comment]
Boys the flathub version aint working for me either
