### ISSUE TITLE
how to 'focuswindow' and not move pointer

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#7332]
### Description

I try to bind movetoworkspace command to waybar 'hyprland/workspace', need to move windows while pointer hold still.I use script below, but it did not always focus to the same window. I coult get the activewindow address and hyprctl dispatch focuswindowslient address:xxxx to make sure it's the same window, but now 'focuswindow' will move pointer away from waybar.
``` shell
#!/bin/dash
if [ $1 = +1 ];then
	hyprctl dispatch movetoworkspacesilent +1
	hyprctl dispatch workspace +1
elif [ $1 = -1 ];then
	hyprctl dispatch movetoworkspacesilent -1
	hyprctl dispatch workspace -1
fi
```
input rule 'follow_mouse' did not change a bit 0 and 2 3.

**Comment by vaxerski** [comment]
you can temporarily disable cursor_warps?

**Comment by vincentaxhe** [comment]
I pull the git, and 'rg cursor_warps', did not find anything, neither wiki, maybe you misspell it.
temporarily disable something or set pointer to some x,y or focuswindowsilent will do

**Comment by vaxerski** [comment]
`cursor:no_warps`

**Comment by vincentaxhe** [comment]
yes, I turn it to true, pointer will not move around.
