### ISSUE TITLE
Cursor visible on hyprlock despite hide_cursor.

### ISSUE THREAD

**Issue by JunaidQrysh** [hyprwm/Hyprland#7346]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

The exact commit that causes this issue is 4fdc0d5. Switching to 8b37e81 fixes it.
I have setup hyprlock on startup. When I reboot my laptop cursor is visible and typing does not work until I swipe my touchpad.

### How to reproduce

1.Setup hyprlock on startup
2. Have hide_cursor = true in hyprlock.conf
2.Reboot
3.Move cursor and it disappears and now you can type.

**Comment by 42Willow** [comment]
This is probably more suited to the hyprlock issue tracker https://github.com/hyprwm/hyprlock/issues

**Comment by JunaidQrysh** [comment]
Moved the issue to https://github.com/hyprwm/hyprlock/issues/460
