### ISSUE TITLE
Droping stuff is broken in gtkmm 4 (Drag and drop)

### ISSUE THREAD

**Issue by System64fumo** [hyprwm/Hyprland#7367]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 1840a907a8c6b1f59cfa6738a8f46b320e8df8b1  (renderbuffer: ensure framebuffer gets deleted (7363)).
Date: Fri Aug 16 12:09:01 2024
Tag: v0.42.0-28-g1840a907, commits: 5097

flags: (if any)


System Information:
System name: Linux
Node name: frostbite
Release: 6.9.9-xanmod1-1-edge
Version: #1 SMP PREEMPT_DYNAMIC Sun, 14 Jul 2024 15:01:49 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti Lite Hash Rate] [10de:2489] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  555.58.02  Tue Jun 25 01:39:15 UTC 2024


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo
```

</details>

### Description

For some reason and i can't explain why, The drop feature in drag and drop is broken in gtkmm 4 on hyprland, Works fine in other comps tho.

### How to reproduce

clone and build [this](https://gitlab.gnome.org/GNOME/gtkmm-documentation/tree/master/examples/book/drag_and_drop)
Try to drag and drop
Drag works fine
Drop does not

### Crash reports, logs, images, videos

Example of drag and drop not working in HL but working in labwc (inside HL)

https://github.com/user-attachments/assets/e31d41d8-adec-4fa0-b09b-39f68b408023

This makes absolutely no sense since drag and drop works fine in gtk 3 programs or heck even gtk 4 programs

**Comment by vaxerski** [comment]
can you post WAYLAND_DEBUG=1 logs of the droppee from hl and one of the working comps

**Comment by its-darsh** [comment]
for the record, the same issue exists with vscode set to work under wayland native

**Comment by System64fumo** [comment]
@vaxerski 
[test-hyprland.log](https://github.com/user-attachments/files/16645710/test-hyprland.log)
[test-labwc.log](https://github.com/user-attachments/files/16645711/test-labwc.log)

**Comment by vaxerski** [comment]
fixed in git
