### ISSUE TITLE
Hyprland doesn't reset format after scanout reset

### ISSUE THREAD

**Issue by Honkazel** [hyprwm/Hyprland#7373]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 12d9901472c6f9128fa8b16c25b3a879d1859e60  (protocols: refactor protocol logging to a macro (7324)).
Date: Thu Aug 15 21:16:18 2024
Tag: v0.42.0-26-g12d99014, commits: 5095

flags: (if any)


System Information:
System name: Linux
Node name: bek
Release: 6.10.5-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:05 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

In scanout mode some clients requests other format, that isn't XR24(for chrome related apps it's AR24 and XB4H for vkcube-wayland) and after scanout reset Hyprland doesn't reset format back to the XR24 and it breaks screenshots _and maybe some more bruh moments, but idk._
Maybe i'll try to bisect this issue later

### How to reproduce

1) Make sure, that direct scanout is enabled(`render:direct_scanout = 1`) and check output of `hyprctl monitors` or `drm_info | grep Format`
2) Direct scanout(fullscreen) clients, that requests other format in scanout mode(eg chrome related apps and vkcube-wayland)
3) Quit from scanout mode and check the output of `hyprctl monitors` or `drm_info | grep Format`

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/16645608/patch.txt)
try this

**Comment by Honkazel** [comment]
About this patch
It seems, that this patch fixing this issue 
But what A and H means in hyprctl monitors?
And also there's a warning in the log, when Hyprland starting
> [WARN] [AQ] drm: Formats mismatch in commit, buffer is XR30 but output is set to XR24. Modesetting to XR30
It seems like it's i915 trying to make a buffer with XR30 format

![image](https://github.com/user-attachments/assets/64fc9893-c73f-4db8-87a3-82479f0a8419)

**Comment by vaxerski** [comment]
if hyprland attaches a buffer to be submitted to KMS (e.g. DS) it doesn't set the format of it as the output format, so aq automatically modesets the display to make it capable of receiving a buffer of the format submitted. The waarning can be ignored.

> But what A and H means in hyprctl monitors?

**A**quamarine **H**yprland

as long as both are the correct fmt we good

They should never be different unless we're in DS, where the aforementioned may happen
