### ISSUE TITLE
0ad and some other games aren't receiving mouse inputs. 

### ISSUE THREAD

**Issue by EvilBoi123** [hyprwm/Hyprland#738]
How to reproduce: 
1.install 0ad 
2.run the game

What to expect: 
The game draws the windows, it even uses the in-game cursor theme, but it won't receive any inputs. 

According to this #433 issue the root of the causes suppose to be wine/proton's fault. But 0ad actually works natively and works  flawlessly under sway and wayfire.

Another thing to mention, why is most game aren't launching fullscreen automatically?  

Edit: For anyone who encounters the same problem, i have found the solution, simply edit your hyprland.desktop to this: 

[Desktop Entry]
Name=Hyprland
Comment=An intelligent dynamic tiling Wayland compositor
Exec=env XDG_CURRENT_DESKTOP=Hyprland SDL_VIDEODRIVER=wayland Hyprland
Type=Application

**Comment by Estebiu** [comment]
You can add a windowrule to force input for xwayland windows: "forceinput"
See the wiki for more

https://wiki.hyprland.org/Configuring/Advanced-config/#rules

**Comment by EvilBoi123** [comment]
My "hyprctl clients" shows this 

Window e5b287f0 -> 0 A.D.:
	at: 0,0
	size: 1920,1080
	workspace: 3 (3)
	floating: 1
	monitor: 0
	class: pyrogenesis
	title: 0 A.D.
	pid: 37678
	xwayland: 1
	pinned: 0

so should i do something like this? 

`windowrule=forceinput,^(pyrogenesis)$`

or 

'windowrule=forceinput,pyrogenesis'

either way it still doesn't receive an inputs. 
or was i wrong?

**Comment by vaxerski** [comment]
> Another thing to mention, why is most game aren't launching fullscreen automatically?

Games can request to be fullscreen'd. If they don't, or they use some obscure ewmh atom to do so, Hyprland won't fullscreen them. Most games from my experience, especially wine/proton ones, send a fullscreen request usually after initializing.

**Comment by EvilBoi123** [comment]
> > Another thing to mention, why is most game aren't launching fullscreen automatically?
> 
> Games can request to be fullscreen'd. If they don't, or they use some obscure ewmh atom to do so, Hyprland won't fullscreen them. Most games from my experience, especially wine/proton ones, send a fullscreen request usually after initializing.

Not for me tho, even if i use native game, it's still not tiled. And if the game is running on wine/proton it does not render in-game cursor. 

Funny enough, i just played a game using a proton(not 0ad), it works pretty well. It even registers a mouse input, but in the case for 0ad, idk why it didn't receive the input.

**Comment by vaxerski** [comment]
it is with great pleasure that I may announce the issue has been fixed in e7961576721f1bd7cc976d14c6dccaddf6c1a69f.

**Comment by EvilBoi123** [comment]
> it is with great pleasure that I may announce the issue has been fixed in [e796157](https://github.com/hyprwm/Hyprland/commit/e7961576721f1bd7cc976d14c6dccaddf6c1a69f).

thank you very much, you're my savior. Everyday this project became more and more mature
