### ISSUE TITLE
custom modeline zoom issue

### ISSUE THREAD

**Issue by Verycuteabbey** [hyprwm/Hyprland#7390]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: UiNt-0xLA
Release: 6.10.5-x64v4-xanmod1
Version: #0~20240814.g9526b2f SMP PREEMPT_DYNAMIC Wed Aug 14 19:27:28 UTC


GPU information: 
63:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

at `v0.41.2` the custom modeline works perfectly, but since i upgraded it to `v0.42.0` that modeline on first boot will get zoom buggy like 4:3 tiny screen focus a zone on top left corner
if hot reload on wm, will does nothing to apply include blackscreen appeared during changing
also see #6953 last commented

<details> <summary>my custom modeline</summary>

`monitor = eDP-1, modeline 695.31 2880 2928 2960 3040 1800 1803 1809 1906 -hsync -vsync, auto, auto, bitdepth, 10, vrr, 1`

</details>

### How to reproduce

upgrade to `v0.42.0` then use custom modeline and restart will reproduce this issue

**Comment by vaxerski** [comment]
modelines are not supported yet in aquamarine so you gotta wait for that

**Comment by vaxerski** [comment]
can you try now

**Comment by vaxerski** [comment]
reported working

**Comment by navidmafi** [comment]
> modelines are not supported yet in aquamarine so you gotta wait for that

Can you please include these details in the "Breaking changes" section of the release notes? or on the blog?

**Comment by vaxerski** [comment]
yea sure, forgot that
