### ISSUE TITLE
Run in a framebuffer device

### ISSUE THREAD

**Issue by thememika** [hyprwm/Hyprland#7398]
### Description

Hello.
As I understand, Hyprland is a standalone implementation of the Wayland protocol.
Which types of output are supported, besides DRM? Is it possible to run Hyprland in a framebuffer device (fbdev)? Thanks for your reply!
I have a portable system without DRM support, that's why I'm asking. It perfectly runs Xorg-based desktops with `xf86-video-fbdev` driver and the `/dev/graphics/fb0` device.
But I would also really like to try Hyprland. Thanks.

**Comment by vaxerski** [comment]
I've never run hyprland in such a system, and thus if there isn't some explicit support via drm, then no. Anyways, this is something that aq would have to support anyways. No plans anyways.
