### ISSUE TITLE
Allow `hyprctl dispatch workspace <name>` without `name:` prefix

### ISSUE THREAD

**Issue by Gusser93** [hyprwm/Hyprland#740]
It would be nice if `hyprctl` would work with the names used in wlroots. With this change, the patch for waybar would work for named workspaces too. [`getWorkspaceIDFromString`#L194](https://github.com/hyprwm/Hyprland/blob/main/src/helpers/MiscFunctions.cpp#L194) could test if the input is a valid relative argument and default to test if the named workspace exists and return it. I think this should not break existing setups, but would allow easier scripting.

**Comment by vaxerski** [comment]
you can use `name:<wlrname>` and it will work perfectly fine, even with numbered workspaces.

**Comment by vaxerski** [comment]
oh no wait sec
I'll make that, would be easier

**Comment by Gusser93** [comment]
> you can use name:<wlrname> and it will work perfectly fine, even with numbered workspaces.
I tested this and `workspace 5` =/= `workspace name:5`, so I think it would break existing setups if the waybar-hyprland-git patch or the wiki would be changed in this way.
![grafik](https://user-images.githubusercontent.com/12176313/192803508-d8e5deec-581d-4166-a45e-e10e53f7fa73.png)

**Comment by vaxerski** [comment]
uhhh that happened. True.

**Comment by vaxerski** [comment]
e3b1d3c3c53c2ffad07f2ef91d5a0cf3fa452879
