### ISSUE TITLE
Matching with static rules for windows that launch with generic names

### ISSUE THREAD

**Issue by Jademalo** [hyprwm/Hyprland#7402]
### Description

I'm attempting to design a set of rules to automatically move a specific Firefox popup window to a consistent place on my desktop, however when the window spawns it always has a generic name.

I have three monitors. I always have a stream on the left hand one, and the chat on the inside edge of the right hand one.
I've got a small area of reserved space set, and I'm attempting to move the chat window to this place when it opens. 
The issue is that when the popout chat is opened, the window class is always `firefox` and the title is `Firefox`. Only once the chat page has loaded does it change the window title to an identifiable one.

The issue is that *every* Firefox window opens with that exact same class and title, meaning there is absolutely no way to differentiate this popup from every other Firefox window. This essentially means that all static rules are worthless, even though once the window is loaded it has a specific title.
I don't want the other windows to do anything special, only this chat popout, but I'm stuck in a position of all or nothing.

I attempted to get around this by setting up a windowrule to tag the chat window with `windowrulev2 = tag +chat, title:^((.*) - Chat - Twitch — Firefox(.*))` since tags are dynamic, and then a watcher script that does `hyprctl dispatch togglefloating tag:chat` as a test. Unfortunately it seems like `hyprctl dispatch` doesn't let you use tags to select windows, which is honestly a huge shame. 

The only simple solutions I can think of for this are either to allow a delay for static matches to wait for the title to be set properly, or to somehow allow you to have a static rule be evaluated dynamically. 

The latter is probably the better solution, since there are situations where most of the static rules would be useful to have re-evaluated when a parameter changes, especially when it comes to secondary browser window names. I can appreciate the use of static rules for initial layout that you then move, but it would be incredibly useful to have the option to have them behave like dynamic rules.

If I'm missing a way to actually do this then I'd appreciate some advice, but failing that I'd really like to see a solution to this. Thanks!

**Comment by vaxerski** [comment]
you can script it

**Comment by Jademalo** [comment]
Do you know of any decent examples? 
I'm a bit lost, and I'm fairly sure I'm missing something since my attempt with tags and a terrible watcher script didn't work. I'm guessing it's got something to do with the IPC bus but that's a bit beyond me.

I'd still like to see `hyprctl dispatch` be able to window match on tags, I'm surprised it doesn't honestly.

**Comment by Jademalo** [comment]
Managed it!
```bash
#!/usr/bin/env bash

chatTitle="^((.*) - Chat - Twitch — Firefox(.*))"

function handle {
  if [[ ${1:0:13} == "windowtitlev2" ]]; then
    window=address:0x${1:15:7}
    if [[ ${1:23} =~ $chatTitle ]]; then
      echo "success"
      hyprctl dispatch setfloating $window
      hyprctl dispatch resizewindowpixel exact 300 1080,$window
      hyprctl dispatch movewindowpixel exact 2048 72,$window
    fi
  fi
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
```
Not the best, but it works. [This page](https://wiki.hyprland.org/Configuring/Expanding-functionality/) was the one that helped, for anyone who stumbles on this in the future.
