### ISSUE TITLE
Cannot render Hyprland nested session after v0.42

### ISSUE THREAD

**Issue by yamabiiko** [hyprwm/Hyprland#7411]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.10.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000


GPU information:
33:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hy3 by outfoxxed ver 0.1
```

</details>

### Description

The nested debug version does not render starting from v0.42 on Arch Linux. No window shows up with the Hyprland debug session on it, although it's running.

### How to reproduce

Clone Hyprland, checkout to v0.42 or latest commit, `make debug` and run `./build/Hyprland`

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/16657819/hyprland.log)

**Comment by vaxerski** [comment]
can you try hl-git

**Comment by yamabiiko** [comment]
With hyprland-git the window renders just fine, but any input sent on the main session is also sent to the nested one even if unfocused, and when it is it doubles every keystroke on the nested session.
Also the plugin notification pop-up is blurry

https://github.com/user-attachments/assets/77e0b9b3-f674-4190-b361-31935dd296ca

[hyprland.log](https://github.com/user-attachments/files/16671118/hyprland.log)

**Comment by vaxerski** [comment]
lol how xD

**Comment by zjeffer** [comment]
Having the same issue, but on latest git I don't even get a window:

[hyprland.log](https://github.com/user-attachments/files/16921620/hyprland.log)

The line `unable to lock lockfile /run/user/1000/wayland-1.lock, maybe another compositor is running` seems interesting?

**Comment by zjeffer** [comment]
bisect: 016da234d0e852de3ef20eb2e89ac58d2a85f6e7 is the first bad commit

**Comment by vaxerski** [comment]
are you on latest aq?

**Comment by zjeffer** [comment]
Yes

**Comment by zjeffer** [comment]
@vaxerski 

Maybe this is expected but when I run nested Hyprland with `WAYLAND_DISPLAY="wayland-2"` (or anything else than "wayland-1"), it will crash instead of hanging:

```
[LOG] Using config: /home/zjeffer/.config/hypr/hyprlandd.conf
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
terminate called after throwing an instance of 'std::runtime_error'
  what():  CBackend::create() failed!
Hyprland has crashed :( Consult the crash report at /home/zjeffer/.cache/hyprland/hyprlandCrashReport927703.txt for more information.
lspci: Unable to load libkmod resources: error -2
```
(at this point it hangs and doesn't exit, so I have to SIGINT)

The crash report is useless:


<details><summary>Crash report</summary>

```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Well this is awkward.

Hyprland received signal 6(ABRT)
Version: 8b9e385943d1a9fd0f8c6070fa1eae507ae26145
Tag: v0.43.0-17-g8b9e3859
Date: Wed Sep 11 18:10:51 2024
Flags:

System info:
	System name: Linux
	Node name: zjeffer
	Release: 6.10.8-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 15:16:37 +0000

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q] [10de:24dd] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
```

</details>

**Comment by zjeffer** [comment]
Log created with `HYPRLAND_TRACE=1 AQ_TRACE=1`: [hyprland-debug-trace-nested.log](https://github.com/user-attachments/files/16970781/hyprland-debug-trace-nested.log)

**Comment by zjeffer** [comment]
Tried again on latest git (00c862686354d139a53222d41a1c80d698a50c43), works now.

**Comment by vaxerski** [comment]
closing then
