### ISSUE TITLE
kitty always crashes hyprland roughly 3 seconds after running kitty, other apps function similarly

### ISSUE THREAD

**Issue by Yearbook-enzyme** [hyprwm/Hyprland#7417]
### Regression?

Yes

### System Info and Version

inxi output while in plasma kde

System:
2	  Host: loganpc Kernel: 6.6.45-1-lts arch: x86_64 bits: 64
3	  Desktop: KDE Plasma v: 6.1.4 Distro: EndeavourOS
4	Machine:
5	  Type: Desktop System: Gigabyte product: B450M DS3H v: N/A
6	    serial: <superuser required>
7	  Mobo: Gigabyte model: B450M DS3H-CF serial: <superuser required>
8	    BIOS: American Megatrends LLC. v: F66 date: 03/22/2024
9	CPU:
10	  Info: 6-core model: AMD Ryzen 5 2600 bits: 64 type: MT MCP cache: L2: 3 MiB
11	  Speed (MHz): avg: 2430 min/max: 1550/3400 cores: 1: 2686 2: 1334 3: 3400
12	    4: 2859 5: 2363 6: 3609 7: 1550 8: 1550 9: 3400 10: 3400 11: 1463 12: 1550
13	Graphics:
14	  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
15	    driver: amdgpu v: kernel
16	  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
17	    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
18	    dri: radeonsi gpu: amdgpu resolution: 3072x1728
19	  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
20	    platforms: gbm,wayland,x11,surfaceless,device
21	  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.1.5-arch1.2
22	    renderer: AMD Radeon RX 580 Series (radeonsi polaris10 LLVM 18.1.8 DRM 3.54
23	    6.6.45-1-lts)
24	  API: Vulkan Message: No Vulkan data available.
25	Audio:
26	  Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
27	    driver: snd_hda_intel
28	  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel
29	  API: ALSA v: k6.6.45-1-lts status: kernel-api
30	  Server-1: PulseAudio v: 17.0 status: active
31	Network:
32	  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
33	    driver: r8169
34	  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: b4:2e:99:30:20:32
35	Drives:
36	  Local Storage: total: 465.76 GiB used: 153.9 GiB (33.0%)
37	  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 500GB
38	    size: 465.76 GiB
39	Partition:
40	  ID-1: / size: 457.38 GiB used: 153.9 GiB (33.6%) fs: ext4
41	    dev: /dev/nvme0n1p1
42	Swap:
43	  Alert: No swap data was found.
44	Sensors:
45	  System Temperatures: cpu: 34.9 C mobo: 26.0 C gpu: amdgpu temp: 30.0 C
46	  Fan Speeds (rpm): N/A
47	Info:
48	  Memory: total: 16 GiB available: 15.54 GiB used: 1.79 GiB (11.5%)
49	  Processes: 351 Uptime: 1m Shell: Bash inxi: 3.3.35

### Description

kitty always crashes hyprland roughly 3 seconds after running kitty, other apps function similarly such as vesktop but apps like brave and dolphin work fine, foot terminal works fine.
i am a linux and hyprland noob be gentle haha

### How to reproduce

i dont know how others would reproduce this issue, it seems to be a rare problem that nobody has had a solution to yet.

### Crash reports, logs, images, videos

[hyprlandCrashReport3354.txt](https://github.com/user-attachments/files/16665257/hyprlandCrashReport3354.txt)

**Comment by vaxerski** [comment]
can you try updating aquamarine? this seems like an aq bug tbh

**Comment by Yearbook-enzyme** [comment]
> can you try updating aquamarine? this seems like an aq bug tbh

i have tried both the -git package and the package without the -git and neither have changed anything
i dont know what all ive tried at this point but i have tried a lot of different things a few others from discord have been trying to help but havent gotten anywhere.

**Comment by Yearbook-enzyme** [comment]
woops lol didnt mean to click that

**Comment by vaxerski** [comment]
can you get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace after building aquamarine-git in debug too

**Comment by Yearbook-enzyme** [comment]
> can you get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace after building aquamarine-git in debug too, i think this is with using aquamarine not aquamarine-git

![stacktrace1](https://github.com/user-attachments/assets/20721622-a711-4922-9bdf-25b79bbdd8cf)
![stacktrace2](https://github.com/user-attachments/assets/6b9da7c0-4a98-4537-8f14-12e8bbe57e41)

**Comment by Yearbook-enzyme** [comment]
> can you get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace after building aquamarine-git in debug too
this should be with aquamarine-git and the previous ones should be just regular aquamarine

![aquamarine-git stacktrace1](https://github.com/user-attachments/assets/f58d0d6f-8da4-491c-88cc-09ff98888f94)
![aquamarine-git stacktrace2](https://github.com/user-attachments/assets/af52010b-f479-42ec-a88c-7f89f41da81e)

**Comment by Yearbook-enzyme** [comment]
@vaxerski dont know if i should ping or not but just wanted to know if you had any ideas about whats going on with this one?

**Comment by vaxerski** [comment]
ok so that should be fixed in latest aquamarine, but I am unsure why the wayland backend is running if you are on a drm session. Anyways, try latest git

**Comment by Yearbook-enzyme** [comment]
> ok so that should be fixed in latest aquamarine, but I am unsure why the wayland backend is running if you are on a drm session. Anyways, try latest git

alright so i checked it and i already was using aquamarine 0.3.3 which is the newest version im seeing on the github repo, it doesnt seem to be working.

**Comment by gulafaran** [comment]
> > ok so that should be fixed in latest aquamarine, but I am unsure why the wayland backend is running if you are on a drm session. Anyways, try latest git
> 
> alright so i checked it and i already was using aquamarine 0.3.3 which is the newest version im seeing on the github repo, it doesnt seem to have fixed the problem.

https://github.com/hyprwm/aquamarine/commit/3989aa9b2fed9638dd2c160f0a88d2c184f77330 yeah not 3.3 but -git

**Comment by Yearbook-enzyme** [comment]
> > > ok so that should be fixed in latest aquamarine, but I am unsure why the wayland backend is running if you are on a drm session. Anyways, try latest git
> > 
> > 
> > alright so i checked it and i already was using aquamarine 0.3.3 which is the newest version im seeing on the github repo, it doesnt seem to have fixed the problem.
> 
> [hyprwm/aquamarine@3989aa9](https://github.com/hyprwm/aquamarine/commit/3989aa9b2fed9638dd2c160f0a88d2c184f77330) yeah not 3.3 but -git

ohhh i totally wasnt getting it at first, ok after some playing around i got the newest version of aquamarine going and now it works thanks for the help yall! time to play around with hyprland.
