### ISSUE TITLE
`initialclass` camelCase in config

### ISSUE THREAD

**Issue by 42Willow** [hyprwm/Hyprland#7420]
![image](https://github.com/user-attachments/assets/13b9720f-d49c-43b8-bdd8-b51904ec8e77)

What is the reasoning behind having it `initialClass` in `hyprctl clients` but `initialclass` in the config? `initialTitle` does not follow this. Would it be worth changing it over to camelCase in the config and (maybe) also having flatcase for backwards compatibility?

**Comment by vaxerski** [comment]
feel free to MR

**Comment by 42Willow** [comment]
It seems this is already fixed on latest git, I have submitted a MR on the hyprland wiki here.

https://github.com/hyprwm/hyprland-wiki/pull/755
