### ISSUE TITLE
Compositor crash when setting referenced variable multiple times via `hyprctl keyword`

### ISSUE THREAD

**Issue by JL2210** [hyprwm/Hyprland#7427]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c86db7bbb0cf14d4955ee3a4d13c0ed9f8a0e0ae dirty (monitor: avoid dangling references to old monitors being undestroyed).
Date: Mon Aug 19 12:44:22 2024
Tag: v0.42.0-46-gc86db7bb, commits: 5115

flags: (if any)


System Information:
System name: Linux
Node name: WileECoyote
Release: 6.10.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2560] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.31.02  Tue Jul 30 21:02:43 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/james/.config/hypr/hyprlandd.conf: Read Succeeded
exec-once = kitty
$a = 1
$b = $a
debug {
    disable_logs = false
}

======Config-End========


```

</details>

### Description

Crashing when spamming `hyprctl keyword` on a variable that is referenced
At first it starts to become slow, and eventually it crashes

### How to reproduce

debug config:
```
exec-once = kitty
$a = 1
$b = $a
debug {
    disable_logs = false
}
```
and spam `hyprctl keyword '$a' 0`

### Crash reports, logs, images, videos

CrashReporter timed out so I had to rebuild and extend the alarm timer

[hyprlandCrashReport63615.txt](https://github.com/user-attachments/files/16669864/hyprlandCrashReport63615.txt)
[hyprlandd.log](https://github.com/user-attachments/files/16669865/hyprlandd.log)

**Comment by JL2210** [comment]
Working on it now. Arch debug symbols are massive so it might take a while

**Comment by JL2210** [comment]
Here is the Hyprlan**d** debug stacktrace, haven't built hyprlan**g** with debug yet
[Hyprland-debug-bt.log](https://github.com/user-attachments/files/16679233/Hyprland-debug-bt.log)

**Comment by vaxerski** [comment]
hyprlang with the g debug g would be nice

**Comment by vaxerski** [comment]
try on hyprlang-git now

**Comment by JL2210** [comment]
That appears to have worked, let me check my original configuration that this crashed with

**Comment by JL2210** [comment]
Works now, thanks!

**Comment by vaxerski** [comment]
yours truly
