### ISSUE TITLE
Some applications do not start via keyboard shortcuts

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [hyprwm/Hyprland#7428]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
[hsyst.txt](https://github.com/user-attachments/files/16673063/hsyst.txt)
```

</details>

### Description

I can't run telegram-desktop, multimc, obs via keyboard shortcuts.
Rofi also cannot run these applications. But if I run it from the console myself, then everything works.
This problem is found only on hyprland. 
I have a bspwm installed nearby, and it does an excellent job of this task. Everything starts up.

### How to reproduce

I dont know.

### Crash reports, logs, images, videos

[rollinglog.log](https://github.com/user-attachments/files/16672684/rollinglog.log)

**Comment by vaxerski** [comment]
are you launching hyprland from a display manager? then your .zshrc or .bashrc isn't loaded. Likely an environment issue

**Comment by vaxerski** [comment]
you can `exec, blabla 2>&1 > ~/log.txt` to inspect what went wrong

**Comment by DIMFLIX-OFFICIAL** [comment]
> you can `exec, blabla 2>&1 > ~/log.txt` to inspect what went wrong

It doesn't write anything to the file at all. It's empty.

**Comment by DIMFLIX-OFFICIAL** [comment]
> are you launching hyprland from a display manager? 

sddm

**Comment by vaxerski** [comment]
> It doesn't write anything to the file at all. It's empty.

likely the executable wasnt found in path then. `exec,env > ~/log.txt`

**Comment by DIMFLIX-OFFICIAL** [comment]
> > It doesn't write anything to the file at all. It's empty.
> 
> likely the executable wasnt found in path then. `exec,env > ~/log.txt`

I managed to solve the problem. However, I did not understand what was specifically wrong. In fact, I haven't changed anything. 
I just rewrote my environment variables and everything worked.

**Comment by vaxerski** [comment]
env was wrong ye
