### ISSUE TITLE
Hotplugging external monitor on Hyprland already started

### ISSUE THREAD

**Issue by zayihu** [hyprwm/Hyprland#7431]
### Description

Well just to be able to hot plug monitor into HDMI, right now when I hot plug it in HDMI, I get blank black screen, but if I exit Hyprland and start again with plugged in monitor, it works. Arch Linux, kernel 6.10.5, Hyprland 0.42.

**Comment by vaxerski** [comment]
dupe of one of the many black monitor issues, we're working on it, search the trackers, e.g. https://github.com/hyprwm/Hyprland/issues/7321
