### ISSUE TITLE
idle cpu usage is over 9000

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#744]
I know there was already a bug opened about that that got closed, but  this is what prevents me to finally switch to Hyprland for good. With stock Hyprland config, with no client opened and nothing happening, Hyprland is idling at ~10% CPU. This is a true problem for a laptop. I know Hyprland is still in beta and all, but I think we should keep track of this performance problem.

In comparison, Sway is idling between 0 and 0.6% on my machine. I'm wondering if there are known bottlenecks that nobody had the time to address yet (in that case I'm willing to try to take a stab at it) or this is unknown territory.

**Comment by frigaut** [comment]
are you using full damage tracking and no_vfr=0?

**Comment by frigaut** [comment]
In my case, hyprland is using 1.6% CPU (of an 8 core, so about 12% of one core, which would be compatible with what you report if what you report is CPU usage on one core). And that's with a shitload of windows opened. That's a bit on the high side for a laptop indeed, but to me, acceptable.

**Comment by vaxerski** [comment]
No clue why, but power ratings between idle sway vs idle hyprland, last time I checked, were around 10%. (hl used 10% more watts than sway) which isnt that bad considering it has to do way more than sway (animations, etc)

What's your "idle"? Do you have *anything* open? I mean a wallpaper daemon, a terminal, status bar, or literally nothing?

**Comment by Estebiu** [comment]
If you want battery life and minimal resources utilization you should probably stick with sway or the tty. Hyprland does have a lot more going on, animations and stuff.

**Comment by vaxerski** [comment]
definitely. It's worth noting though that the difference is not huge, and it's mostly constant. Aka, Hyprland will usually use 0.5-2W more than sway on my computer, regardless of how many watts overall are being used. I still get ~7-8h of battery life with enabled blur, rounded corners and shit tho lmao

**Comment by primalmotion** [comment]
Yeah I have full damage tracking, no_vfr = 0, and blur optimizations on (I tried without blur at all, but that did not change much). It's also an 8 cores.I tried with just swaybg and waybar and nothing else. I perfectly understand that animations will suck more power, but I would expect it to do so when there's actual animatiions running. Here's it's just basically sitting there, only drawing my background image :)

**Comment by vaxerski** [comment]
there is no way hyprland can magically not check animations when none are running. It has to at least check their status.

**Comment by Estebiu** [comment]
> definitely. It's worth noting though that the difference is not huge, and it's mostly constant. Aka, Hyprland will usually use 0.5-2W more than sway on my computer, regardless of how many watts overall are being used. I still get ~7-8h of battery life with enabled blur, rounded corners and shit tho lmao

I get usually 5-6h of battery life on both sway and hyprland. But it's my fault as I bough a laptop with Oled, 4k, and a intel CPU.

**Comment by Dickby** [comment]
@vaxerski : 
I found that a big hotspot is inside EventManager.cpp, i don't have much time right now to look into that,
and i don't really know how the event system works, but by just raising the nanosleep values i couldl drop the 
idle cpu usage significantly, because the framerate is the limiting factor of the main thread, it feels like the 1 millisecond
can be raised at least to 16, the higher values i've tried (until 1000) seem to reduce the load even more.

**Comment by vaxerski** [comment]
alr I'll rewrite the event manager to be nopoll

**Comment by vaxerski** [comment]
check with 49ab3890aa826918568c62f9cda4df023f3dcbb2

**Comment by vaxerski** [comment]
judging by my limited testing it seems to have worked pretty fookin well

**Comment by Dickby** [comment]
On my laptop it dropped from ~8 to maybe 2.8

**Comment by vaxerski** [comment]
thanks dickby for the find!

**Comment by vaxerski** [comment]
waiting for @primalmotion to report back

**Comment by primalmotion** [comment]
from "10%, it's life" to 0.7%. now we're talking :package: 
Works like a charm. Thanks!

**Comment by primalmotion** [comment]
0.0% when I touch absolutely nothing. Kudos guys!
