### ISSUE TITLE
Hyprpm update error

### ISSUE THREAD

**Issue by 1Finder1** [hyprwm/Hyprland#7445]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: username-hyprland
Release: 6.6.44-3-lts
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:35:07 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660] [10de:2184] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  split-monitor-workspaces by Duckonaut ver 1.1.0
```

</details>

### Description

I have one plugin: split-workspaces installed in hyprpm. When I first login (sddm) aflter start pc, I have error "invalid dispatcher" (split workspaces). I'm launching terminal and using command "hyprpm update" and error fixed. But this command in autostart.
My config:
**debug {
    disable_logs = false
    enable_stdout_logs = true
}**

ENVIRONMENT
env = XDG_CONFIG_HOME,$HOME/.config
...
MONITORS
monitor=...
WORKSPACES
plugin {
    split-monitor-workspaces {
        count = 7
        keep_focused = 1
        enable_notifications = 1
    }
}

...
exec-once = hyprpm update -n
...
bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4
bind = $mainMod, 5, split-workspace, 5
bind = $mainMod, 6, split-workspace, 6
bind = $mainMod, 7, split-workspace, 7

### How to reproduce

Install split-workpaces plugin.
Confidure it.
Reboot

### Crash reports, logs, images, videos

[LOG] Instance Signature: 918d8340afd652b011b937d29d5eea0be08467f5_1724214078_853327544
[LOG] Runtime directory: /run/user/1000/hypr/918d8340afd652b011b937d29d5eea0be08467f5_1724214078_853327544
[LOG] Hyprland PID: 799
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: username-hyprland
[LOG] Release: 6.6.44-3-lts
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:35:07 +0000

[LOG] GPU information:
03:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660] [10de:2184] (rev a1) (prog-if 00 [VGA controller])

[WARN] Warning: you're using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG]
Current splash: Súbeme la radio que esta es mi canción

[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 86.74µs. Estimated average calc time: 0.34µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 55.17µs. Estimated average calc time: 0.29µs.
[LOG] Using config: /home/username/.config/hypr/hyprland.conf
**[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug**
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 55.17µs. Estimated average calc time: 0.29µs.
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[ERR] Invalid dispatcher!
[LOG] Creating the PointerManager!
[wlr] [EGL] command: eglQueryDmaBufModifiersEXT, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In eglQueryDmaBufModifiersEXT: Invalid format

**Comment by myamusashi** [comment]
Try this hyprpm reload -n

**Comment by zjeffer** [comment]
This is fixed in https://github.com/hyprwm/Hyprland/pull/7152, so like @Thanajor says you should update to v0.42.0

**Comment by 1Finder1** [comment]
I am update Hyprland and use in auto start `hyprpm reload -n`. and this work!
