### ISSUE TITLE
GTK List choosers are bugged

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/Hyprland#745]
Steps to reproduce: Open in fullscreen Firefox and scroll in a gtk list chooser.
Expected outcome: When scrolling the list it moves
Noted outcome: The list moves AND the page beneath itself.

Tried both with a touchpad and with a mouse. 

The video is bigger than 10Mb so I shared it as a link.
https://files.estebiu.com/share/WUjn8hCB

**Comment by vaxerski** [comment]
any app to test?

**Comment by CrezyDud** [comment]
eclipse with `GTK_BACKEND=x11 eclipse`
wayland mode is broken, thats why i run it in x

**Comment by CrezyDud** [comment]
ok on gnome i get scrollbar size 0 error, but it works anyway, so its not that error

**Comment by Estebiu** [comment]
This issue seems to be resolved now.
