### ISSUE TITLE
Hyprland crashes immediately after start on 0.42.0

### ISSUE THREAD

**Issue by gilbertorconde** [hyprwm/Hyprland#7452]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>
I cant run the `hyprctl systeminfo -c` because i cant start hyprland now. This is the output on v0.41.2. I remove the configs part because, on the 0.42.0, i used the default config (auto generated) with the below envs

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: arch-p1
Release: 6.10.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a0] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107GLM [RTX 2000 Ada Generation Laptop GPU] [10de:28b8] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hy3 by outfoxxed ver 0.1

======Config-Start======

#Environment Variables for the Hyprland session

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = GDK_BACKEND,wayland,x11,*
env = GTK_THEME,Adwaita:dark
env = GTK2_RC_FILES,/usr/share/themes/AdwaitaDark/gtk-2.0/gtkrc

env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

env = _JAVA_AWT_WM_NONREPARENTING,1

env = XCURSOR_SIZE,24
env = MOZ_ENABLE_WAYLAND,1
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRCURSOR_SIZE,28


env = QT_AUTO_SCREEN_SCALE_FACTOR,1

env = CHROME_USER_FLAGS,--enable-features=UseOzonePlatform --ozone-platform=wayland
env = CHROMIUM_FLAGS,--enable-features=UseOzonePlatform --ozone-platform=wayland

env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct

# CARD0 = NVIDIA RTX 2000; CARD1 = INTEL IRIS XE
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

env = ELECTRON_OZONE_PLATFORM_HINT,auto

======Config-End========

```

</details>

### Description

Whenever i try to run Hyprland from the tty it logs a bunch of generic things, the screen blinks briefly, points to the above crash report and hyprland exits.
I tried with the git version and with the extra/hyprland package version. All the same. This works fine on the previous version (0.41.2).
I have a thinkpad p1 gen6 hybrid laptop, latest nvidia drivers (extra/nvidia 555.58.02-17). Kernel modules, all as in the wiki. 

Tried it with all the envs above, setting only the `AQ_DRM_DEVICES`, setting the old way (`WLR_DRM_DEVICES`). Nothing seems to make a difference.

I didn't put my bios to discreet mode (otherwise /dev/dri would only show one card) but it should work fine with the `AQ_DRM_DEVICES` env right?

### How to reproduce

Only know in my case. Removing the old package, and installing the new one. and replacing WLR_DRM_DEVICES by AQ_DRM_DEVICES

### Crash reports, logs, images, videos

[hyprlandCrashReport78745.txt](https://github.com/user-attachments/files/16694172/hyprlandCrashReport78745.txt)

EDIT: stdout and stderr with trace log envs (`HYPRLAND_TRACE=1 AQ_TRACE=1`)
[stderr.txt](https://github.com/user-attachments/files/16708511/stderr.txt)
[stdout.txt](https://github.com/user-attachments/files/16708512/stdout.txt)
[hyprlandCrashReport189025.txt](https://github.com/user-attachments/files/16708538/hyprlandCrashReport189025.txt)

**Comment by vaxerski** [comment]
can you upload a full trace log https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log

**Comment by gilbertorconde** [comment]
> can you upload a full trace log https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log

Sure, updated the issue

**Comment by vaxerski** [comment]
the stdout is a crash report, not a log

**Comment by vaxerski** [comment]
no wait nvm, it's just not trace

**Comment by gilbertorconde** [comment]
so, i had some time and did some experiments (btw: CARD0 = NVIDIA RTX 2000; CARD1 = INTEL IRIS XE). Just to clarify, in v0.41.2 (befor aquamarine), i had:
- my bios config in hybrid mode
- `env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0`.
Everything works fine with this configuration.

In this new version, anything works at all if `env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0`. So, every time i try to use both cards in this env, regardless of the order, anything works. This is the case i tested when opened the issue.

In bios hybrid mode, if `env = AQ_DRM_DEVICES,/dev/dri/card1` hyprland starts but i can only use the builtin display.
In bios hybrid mode, if `env = AQ_DRM_DEVICES,/dev/dri/card0` hyprland starts but i can only use an external display.

In bios discrete mode (only nvidia), no env aq_drm_devices needeed, both screens work. but now im in discrete mode :(
Btw, i still have some bugs. But not sure if is related, for instance the kitty terminal emulator starts but gets stuck in just black.

All this testes where made with the hyprland-git and aquamarine-git packages from AUR.

Dont know if you're going to follow up this or not, i notice that you have a lot of new issues to deal with, but if you're going to, and need more info, just ask me.

**Comment by gilbertorconde** [comment]
I ended up starting from scratch, installed garuda and now everything is working properly. Not sure exactly what was wrong, but because no one else seems to have the same issue is safe to assume that i had some wrong setup/configuration that i didnt notice. This can be closed now
