### ISSUE TITLE
Build through nix fails for v0.42.0

### ISSUE THREAD

**Issue by gkleen** [hyprwm/Hyprland#7472]
### Regression?

Yes

### System Info and Version

N/A

### Description

Nix build directly from flake fails for `v0.42.0`.

Seems the derivation does not specify `xfixes` as an input.

### How to reproduce

`nix build --refresh 'github:hyprwm/Hyprland?ref=v0.42.0'#packages.x86_64-linux.hyprland -L`

### Crash reports, logs, images, videos

[hyprland.log.txt](https://github.com/user-attachments/files/16711285/hyprland.log.txt)

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
That's just a CMake suggestion, it does not impact Hyprland in any way.

The real error is a few lines prior (could not find subproject udis86), and means you have not built hyprland with submodule support.

See the pinned Nix issue for more info.

**Comment by gkleen** [comment]
`nix build --refresh 'git+ssh://git@github.com/hyprwm/Hyprland?ref=v0.42.0&submodules=1'#packages.x86_64-linux.hyprland -L` does indeed work; thanks!
