### ISSUE TITLE
Cursor position is inaccurate on master

### ISSUE THREAD

**Issue by Stoppedpuma** [hyprwm/Hyprland#7473]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit cae937c51bd220d6676c6027d05ea51fc3c821bb  (layersurface: dont rollover on size_t (7451)).
Date: Wed Aug 21 23:05:03 2024
Tag: v0.42.0-54-gcae937c5, commits: 5123

GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])
```

</details>

### Description

The actual position of the mouse cursor is offset slightly upwards and to the left instead of matching the xcursor visual. This issue goes away when an application is capturing the screen.

### How to reproduce

Might be an issue with multiple displays, I haven't tested. This is extremely easy to reproduce by selecting text.

### Crash reports, logs, images, videos

https://puma.s-ul.eu/7r2ArQLY

**Comment by JL2210** [comment]
I noticed something similar while taking screenshots with `grim -g "$(slurp)"`. The center of the crosshair isn't actually where the cursor is.

**Comment by vaxerski** [comment]
do you have `AQ_NO_ATOMIC` set? if so, don't

**Comment by JL2210** [comment]
Disabling atomic modesetting made Plasma unbootable for me so I didn't even try it on Hyprland

**Comment by Stoppedpuma** [comment]
Closing this as an issue related to `AQ_NO_ATOMIC`. I didn't realise I had this enabled at the time.
