### ISSUE TITLE
Transactional resizing

### ISSUE THREAD

**Issue by diniamo** [hyprwm/Hyprland#7475]
### Description

When resizing multiple windows at once (resizing a tiled window causes other tiled windows to be resized), the inconsistent update rate makes them look laggy. It's possible to make their frames "match up" to fix that.

The idea came from Niri's implementation, see https://github.com/YaLTeR/niri/commit/cf357d7058910864018c3e3702a9723194fce916 and https://github.com/YaLTeR/niri/commit/7bfdf87bf0138d602888fc3167921bc1d029b0ab. 

https://github.com/user-attachments/assets/7b351e4d-dbf3-46bf-9a66-9e748354be36

(Credit for this video also goes to Niri's developer.)

**Comment by vaxerski** [comment]
I don't think this makes sense? throttling the layout and waiting for a window to commit (which it may do at its discretion) will make the desktop overall feel laggier.

**Comment by diniamo** [comment]
Looks like Niri has a built-in time limit of 300ms to avoid lag: https://github.com/YaLTeR/niri/blob/7bfdf87bf0138d602888fc3167921bc1d029b0ab/src/utils/transaction.rs#L15-L18

**Comment by diniamo** [comment]
FWIW sway also does this.

**Comment by vaxerski** [comment]
300ms is literally 3fps
that's very much lag.

Just because niri and sway do this, doesn't mean hyprland should.

The way sway's renderer works is very different from hyprland

**Comment by diniamo** [comment]
Yes, 300ms is way too high. I doubt I can make a convincing point here, but I think it's a nice

**Comment by diniamo** [comment]
Yes, 300ms is way too high. What would the lag actually affect though? It wouldn't freeze the entire compositor, and while you are resizing the windows, you aren't interacting with them anyway.

**Comment by vaxerski** [comment]
that does not matter, as that makes the desktop experience laggy. Although the stretching in hyprland is for sure a bit odd, the cropping looks totally fine.

I was trying to make opengl expand the ends of the texture instead in a patch once, but it didnt fully work. IMO that would be the best of both worlds

**Comment by diniamo** [comment]
Well, guess I won't be convincing you.

Here is another showcase though, maybe the difference is easier to see here (to me, it's night and day):

https://github.com/user-attachments/assets/8ea11ea5-5d8e-4b86-ab48-5d9ce0d68c02

**Comment by vaxerski** [comment]
this is better fixed in the way I've described before. Transactions are a simple, but ultimately dirty hack.

**Comment by diniamo** [comment]
In that case, good luck.

**Comment by vaxerski** [comment]
I wanna do it one day cuz @outfoxxed was complaining but my simple patch didnt really work due to.... layers of old hacks in handling surface positioning and sizing.

I'd have to prolly redo a bunch of handling there. Prolly, maybe, dunno, will have to see.

**Comment by diniamo** [comment]
I'm not sure if that's fair prioritization, I'm sure I'm not the only one with animations disabled.

**Comment by vaxerski** [comment]
very few people disable animations from my experience
