### ISSUE TITLE
Add priority/order rule for layers

### ISSUE THREAD

**Issue by darkwater** [hyprwm/Hyprland#7476]
### Description

If I open a virtual keyboard such as wvkbd, it currently shows up on top of my bar. I'd like to be able to set a higher priority to the keyboard layer such that it shows up all the way at the bottom, below any other layers, like:

```hyprlang
layerrule = priority 1, waybar
layerrule = priority 100, wvkbd
```

If someone could give me some pointers of where to look I wouldn't mind taking a stab at implementing this myself.

**Comment by vaxerski** [comment]
...no. The protocol itself is a place for that. https://wayland.app/protocols/wlr-layer-shell-unstable-v1

Configure wvkbd properly....

**Comment by darkwater** [comment]
What part of the protocol lets layers coordinate an order with other layers? I don’t see it. Or are you suggesting adding this functionality to the protocol?

**Comment by vaxerski** [comment]
is this not enough? https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_exclusive_zone

**Comment by darkwater** [comment]
That lets a layer set the *amount* to reserve, but not *where* to reserve it. I don't see a way to tell wvkbd to go under the bar.

This is what I have now, because the keyboard opens after the bar:
```
 ┌────────────┐
 │ Window     │
 │            │
 │            │
 └────────────┘
┌──────────────┐
│ Keyboard     │
└──────────────┘
===Bar==========
```

And this is what I want:
```
 ┌────────────┐
 │ Window     │
 │            │
 │            │
 └────────────┘
===Bar==========
┌──────────────┐
│ Keyboard     │
└──────────────┘
```

**Comment by vaxerski** [comment]
aah. Right. The protocol doesn't define this iirc, but in hyprland they are ordered chronologically. You could keep the layershell there, just map/unmap it. If it's started _before_ the bar, that should be the result.

**Comment by darkwater** [comment]
That’s one option, but surely it wouldn’t be bad to have a layerrule for it as well? There might be other use cases where this may be the only option.

**Comment by vaxerski** [comment]
hm, I guess.
