### ISSUE TITLE
HYPRCHANNNNnnnnn where are youuuuuu? Where did you gooooo????

### ISSUE THREAD

**Issue by ethereal-engineer** [hyprwm/Hyprland#7479]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

I updated my Hyprland, which specifically has no wallpaper so I can appreciate the randomly chosen HyprChan or Hyprland renderings..... and they are now just a black screen????!!!!! NOOOOOOO!!!!! Did they go bye bye? I love her smile!

### How to reproduce

Honestly, just a impassioned enquiry.

**Comment by solomonton** [comment]
Can you send me your config?

**Comment by vaxerski** [comment]
#7319
