### ISSUE TITLE
Hyprland Crashes When Connecting a Second Monitor

### ISSUE THREAD

**Issue by EviLuci** [hyprwm/Hyprland#7485]
### Regression?

Yes

### System Info and Version

Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)

System Information:
System name: Linux
Node name: arch
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000

GPU information:
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 03) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/sujan/.config/hypr/hyprland.conf: Read Succeeded
source = config/autostart.conf
source = config/monitor.conf
source = config/env.conf
source = config/settings.conf
source = config/nav_keybinds.conf
source = config/windowrule.conf
source = config/custom_keybinds.conf

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

Config File: /home/sujan/.config/hypr/config/autostart.conf: Read Succeeded

# Execute your favorite apps and services at launch
exec-once = wl-clipboard-history -t
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = sleep 5 && blueman-applet
exec-once = nm-applet --indicator
exec-once = udiskie &
exec-once = waybar
exec-once = hypridle
exec-once = systemctl --user restart pipewire
exec-once = copyq --start-server
exec-once = swww-daemon --format xrgb
exec-once = dbus-update-activation-environment --all
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = waypaper-engine daemon
# Notification daemon
exec-once = swaync

# Theme
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gtk.Settings.FileChooser startup-mode cwd
exec-once = gsettings set org.gtk.gtk4.Settings.FileChooser startup-mode cwd

# cursor and icon themes
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Sweet"
exec-once = gsettings set org.gnome.desktop.wm.preferences theme "Sweet"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"

Config File: /home/sujan/.config/hypr/config/monitor.conf: Read Succeeded

# Monitor
# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
# Output
# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

#monitor=HDMI-A-1,1920x1080@60,0x0,1
#workspace=HDMI-A-1,1
#monitor=HDMI-A-2,1920x1080@60,1920x0,1
#workspace=HDMI-A-2,2

# Primary Monitor
monitor=eDP-1,1920x1080@60,0x0,1
# monitor=,preferred,auto,1

# secondary monitor
# monitor=HDMI-A-1,1920x1080@60,-1920x0,1
monitor=HDMI-A-1,highres,-1920x0,1
# monitor=HDMI-A-1,1920x1080@60,1920x0,1
# monitor=,preferred,auto,1
monitor=,preferred,auto,1,mirror,eDP-1
# monitor=HDMI-A-1,1440x900@60,-1440x0,1
# monitor=HDMI-A-1,1440x900@60,1920x0,1
# monitor=HDMI-A-1,1366x788@60,1920x0,1
#monitor=eDP-1,transform,0
#monitor=eDP-1,addreserved,10,10,10,10
#workspace=5,HDMI-A-1

# High Refresh Rate
#monitor=,highrr,auto,1

# High Resolution
#monitor=,highres,auto,1

# to disable a monitor
#monitor=name,disable

# Mirror
#monitor=DP-3,1920x1080@60,0x0,1,mirror,DP-2
#monitor=,preferred,auto,1,mirror,eDP-1

Config File: /home/sujan/.config/hypr/config/env.conf: Read Succeeded

# Environment Variables

# Toolkit Backend Variables
env = GDK_BACKEND,wayland,*
env = GDK_SCALE,1
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORM,wayland
env = SDL_VIDEODRIVER=wayland
env = CLUTTER_BACKEND,wayland

# XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Qt Variables
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,0
env = QT_QPA_PLATFORMTHEME=qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct

# Theming Related Variables
env = GTK_THEME=Sweet:dark
#env = XCURSOR_THEME,"Capitaine Cursors"
env = XCURSOR_SIZE,24

# firefox
env = MOZ_ENABLE_WAYLAND,1

Config File: /home/sujan/.config/hypr/config/settings.conf: Read Succeeded

# General
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 3
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    allow_tearing = true
    resize_on_border = true
    #layout = master
}

# Decoration
decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 8
    shadow_offset = 2 2
    col.shadow = rgba(1a1a1aee)

    blur {
      contrast = 1
      xray = true
      ignore_opacity = true
      popups = false
      popups_ignorealpha = 0.1
    }

}

# Animation
animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 3, myBezier
    animation = windowsOut, 1, 3, default, popin 80%
    animation = border, 1, 3, default
    animation = borderangle, 1, 3, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, default
}

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    touchpad {
        natural_scroll = true
        drag_lock = true
    }
    special_fallthrough = true
    sensitivity = 0.3 # -1.0 - 1.0, 0 means no modification.
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_forever=true
}

# Misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
    allow_session_lock_restore = true
    initial_workspace_tracking = false
}

# Layouts
dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    no_gaps_when_only = false
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    # new_is_master = true
}

# cursor section for Hyprland v0.41.0 or newer
cursor {
        enable_hyprcursor = true
}

Config File: /home/sujan/.config/hypr/config/nav_keybinds.conf: Read Succeeded

# Move
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# Move focus
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Resize windows
binde = SUPER, left, resizeactive, -20 0
binde = SUPER, right, resizeactive, 20 0
binde = SUPER, up, resizeactive, 0 -20
binde = SUPER, down, resizeactive, 0 20

# Modes
# $submap_resize = ↔️ resize window
# bind = SUPER, R, submap, $submap_resize

# submap = $submap_resize
#     binde = , h, resizeactive, -15 0
#     binde = , l, resizeactive, 15 0
#     binde = , k, resizeactive, 0 -15
#     binde = , j, resizeactive, 0 15

#     bind  = , escape, submap, reset
#     bind  = , return, submap, reset
# submap = reset

# Switch workspaces with mainMod + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Special workspace
bind = SUPER CTRL, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

Config File: /home/sujan/.config/hypr/config/windowrule.conf: Read Succeeded

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = fullscreen, wlogout
windowrule = fullscreen, title:wlogout
windowrule = fullscreen, class:^(nwg-drawer)$

# Dialogs
windowrule = float,title:^(Open File)(.*)$
windowrule = float,title:^(Select a File)(.*)$
windowrule = float,title:^(Choose wallpaper)(.*)$
windowrule = float,title:^(Open Folder)(.*)$
windowrule = float,title:^(Save As)(.*)$
windowrule = float,title:^(Library)(.*)$
windowrule = float,title:^(File Upload)(.*)$

windowrulev2 = float,class:^(file_progress)$
windowrulev2 = float,class:^(confirm)$
windowrulev2 = float,class:^(dialog)$
windowrulev2 = float,class:^(download)$
windowrulev2 = float,class:^(error)$
windowrulev2 = float,title:^(Volume Control)$
windowrulev2 = float,title:^(Choose Files)$
windowrulev2 = float,title:^(Save As)$
windowrulev2 = float,title:^(Confirm to replace files)$
windowrulev2 = float,title:^(File Operation Progress)$
windowrulev2 = float,title:^(DevTools)$
windowrulev2 = float,title:^(Open File)$
windowrulev2 = float,title:^(branchdialog)$
windowrulev2 = float,title:^(Media viewer)$
windowrulev2 = float,title:^(Open)$

windowrule = center, title:^(Open File)(.*)$
windowrule = center, title:^(Select a File)(.*)$
windowrule = center, title:^(Choose wallpaper)(.*)$
windowrule = center, title:^(Open Folder)(.*)$
windowrule = center, title:^(Save As)(.*)$
windowrule = center, title:^(Library)(.*)$
windowrule = center, title:^(File Upload)(.*)$

# Position
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(qt5ct)$
windowrulev2 = float,class:^(nwg-look)$
windowrulev2 = float,class:^(file-roller)$
windowrulev2 = float,class:^(rofi)$
windowrulev2 = float,class:^(nwg-drawer)$
windowrulev2 = float,class:^(copyq)$
windowrulev2 = float,class:(copyq)
windowrulev2 = float,class:^(notification)$
windowrulev2 = float,class:^(splash)$
windowrulev2 = float,class:^(confirmreset)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(pavucontrol-qt)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-applet)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,title:^(wlogout)$
windowrulev2 = float,title:^(Waypaper Engine)

windowrulev2 = animation none,class:^(Rofi)$
windowrule = move 75 44%, title:^(Volume Control)$

# Workspace
# windowrulev2 = workspace 1, class:^(Brave-browser)$
# windowrulev2 = workspace 2, class:^(discord)$
# windowrulev2 = workspace 3, class:^(org.telegram.desktop)$
# windowrulev2 = workspace 4, class:^(Code)$
# windowrulev2 = workspace 4, class:^(code-url-handler)$
# windowrulev2 = workspace 5, class:^(Spotify)$

# Opacity
# windowrulev2 = opacity 0.90 0.90,class:^(Brave-browser)$
windowrulev2 = opacity 0.90 0.90,class:^(steamwebhelper)$
windowrulev2 = opacity 0.90 0.90,class:^(thunar)$
windowrulev2 = opacity 0.90 0.90,class:^(file-roller)$
windowrulev2 = opacity 0.90 0.90,class:^(nwg-look)$
windowrulev2 = opacity 0.90 0.90,class:^(qt6ct)$
windowrulev2 = opacity 0.90 0.90,class:^(discord)$ #Discord-Electron
windowrulev2 = opacity 0.90 0.90,class:^(WebCord)$ #WebCord-Electron
#windowrulev2 = opacity 0.90 0.90,class:^(org.telegram.desktop)$
#windowrulev2 = opacity 0.90 0.90,class:^(firefox)$
#windowrulev2 = opacity 0.90 0.90,class:^(microsoft-edge-stable)$
#windowrulev2 = opacity 0.90 0.90,class:^(opera)$
#windowrulev2 = opacity 0.90 0.90,class:^(vivaldi-stable)$
windowrulev2 = opacity 0.90 0.90,class:^(nemo)$
windowrulev2 = opacity 0.90 0.90,class:^(Steam)$
windowrulev2 = opacity 0.90 0.90,class:^(Spotify)$
windowrulev2 = opacity 0.90 0.90,class:^(Code)$
windowrulev2 = opacity 0.90 0.90,class:^(kitty)$
windowrulev2 = opacity 0.90 0.90,class:^(wezterm)$
windowrulev2 = opacity 0.90 0.90,class:^(org.kde.dolphin)$
windowrulev2 = opacity 0.90 0.90,class:^(org.kde.ark)$
windowrulev2 = opacity 0.90 0.90,class:^(nwg-look)$
windowrulev2 = opacity 0.90 0.90,class:^(qt6ct)$
windowrulev2 = opacity 0.90 0.90,class:^(pavucontrol)$
windowrulev2 = opacity 0.90 0.90,class:^(blueman-manager)$
windowrulev2 = opacity 0.90 0.90,class:^(nm-applet)$
windowrulev2 = opacity 0.90 0.90,class:^(nm-connection-editor)$
windowrulev2 = opacity 0.90 0.90,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = opacity 0.90 0.90,class:^(org.gnome.polkit-gnome-authentication-agent-1)$

# Size
windowrulev2 = size 800 600,class:^(download)$
windowrulev2 = size 800 600,title:^(Open File)$
windowrulev2 = size 800 600,title:^(Save File)$
windowrulev2 = size 800 600,title:^(Volume Control)$

windowrulev2 = idleinhibit focus,class:^(mpv)$
windowrulev2 = idleinhibit fullscreen,class:^(Brave-browser)$
windowrulev2 = idleinhibit fullscreen,class:^(firefox-developer-edition)$
windowrulev2 = idleinhibit fullscreen,class:^(firefox)$

# firefox Picture-in-Picture
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = pin,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(firefox-developer-edition)$,title:^(Picture-in-Picture)$
windowrulev2 = pin,class:^(firefox-developer-edition)$,title:^(Picture-in-Picture)$

# Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$

# firefox figma micro indicator
windowrulev2 = float,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$

# Telegram media viewer
windowrulev2 = float,class:^(org.telegram.desktop)$,title:^(Media viewer)$
windowrulev2 = center,class:^(org.telegram.desktop)$,title:^(Media viewer)$
windowrulev2 = monitor 1,class:^(org.telegram.desktop)$,title:^(Media viewer)$

# windowrule v2 to avoid idle for fullscreen apps
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

# Layer rules
layerrule = blur, gtk-layer-shell
layerrule = ignorezero, gtk-layer-shell
layerrule = ignorezero, waybar
layerrule = ignorezero, overview
layerrule = blur, overview
layerrule = ignorealpha
layerrule = blur,rofi
layerrule = ignorezero,rofi
layerrule = blur,notifications
layerrule = ignorezero,notifications
layerrule = blur,swaync-notification-window
layerrule = ignorezero,swaync-notification-window
layerrule = blur,swaync-control-center
layerrule = ignorezero,swaync-control-center
layerrule = blur,logout_dialog

# Tearing
windowrule=immediate,.*\.exe
windowrulev2=immediate,class:(steam_app)

Config File: /home/sujan/.config/hypr/config/custom_keybinds.conf: Read Succeeded
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# SUPER = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
# System Controls
bind = SUPER CTRL, X, exec, systemctl poweroff -i
bind = SUPER CTRL, R, exec, systemctl reboot
bind = SUPER CTRL, E, exec, pkill wleave || wleave
bind = SUPER CTRL, L, exec, hyprlock

# Hypr Controls
bind = SUPER CTRL, Q, exit,
bind = SUPER CTRL, up, exec, hyprctl dispatch splitratio -0.1
bind = SUPER CTRL, down, exec, hyprctl dispatch splitratio 0.1

# Rotate Screen
bind = SUPER SHIFT, R, exec, hyprctl keyword monitor eDP-1,preferred,auto,1,transform,1
bind = SUPER SHIFT CTRL, R, exec, hyprctl keyword monitor eDP-1,preferred,auto,1,transform,0

# Window Management
bind = SUPER, Q, killactive,
bind = SUPER, X, killactive,
bind = SUPER, tab, changegroupactive
bind = SUPER, Tab, bringactivetotop,
bind = SUPER, ., pseudo, # dwindle
bind = SUPER, /, togglesplit, # dwindle
bind = SUPER, M, fullscreen,
bind = SUPER, Space, togglefloating,
bind = SUPER CTRL, Return, layoutmsg, swapwithmaster

# Primary Applications
bind = SUPER, F, exec, figma-linux
# bind = SUPER, Return, exec, kitty -e fish
bind = SUPER, Return, exec, [float;tile] wezterm start --always-new-process
bind = SUPER, T, exec, telegram-desktop
bind = SUPER , P, exec, nwg-drawer
bind = SUPER, B, exec, firefox-developer-edition
bind = SUPER, E, exec, nemo
bind = SUPER, C, exec, code
bind = SUPER, G, exec, gimp
bind = SUPER, W, exec, libreoffice --writer
bind = SUPER, D, exec, discord
bind = SUPER, Z, exec, zeditor
bind = SUPER, V, exec, viber
bind = SUPER, S, exec, spotify-launcher

# Secondary Applications
# bind = SUPER SHIFT, Return, exec, [float;tile] wezterm start --always-new-process
bind = SUPER SHIFT, Return, exec, kitty
bind = SUPER SHIFT, B, exec, brave
bind = SUPER SHIFT, E, exec, microsoft-edge-stable
bind = SUPER SHIFT, V, exec, virtualbox

# Utility Applications
bind = SUPER CTRL, C, exec, copyq toggle
bind = SUPER CTRL, W, exec, killall -SIGUSR2 waybar
bind = SUPER SHIFT, W, exec, waypaper-engine run
bind = SUPER CTRL SHIFT, P, exec, hyprpicker -a
bind = SUPER CTRL, D, exec, code $HOME/dotfiles/

# Trying out Tor
bind = SUPER CTRL, T, exec, torbrowser-launcher
#bind = SUPER, V, exec, vivaldi-stable --proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost"
#bind = SUPER, O, exec, opera --proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost"

# Notification
bind = SUPER, N, exec, swaync-client -t
bind = SUPER CTRL, N, exec, swaync-client -rs
bind = SUPER SHIFT, N, exec, swaync-client -R

# Screenshot a window
bind = SUPER SHIFT, PRINT, exec, hyprshot -m window --clipboard-only --freeze
bind = SUPER SHIFT CTRL, PRINT, exec, hyprshot -m window --freeze
# Screenshot a region
bind = , PRINT, exec, hyprshot -m region --clipboard-only --freeze
bind = CTRL, PRINT, exec, hyprshot -m region --freeze
# Screenshot a monitor
bind = SUPER , PRINT, exec, hyprshot -m output --clipboard-only --freeze
bind = SUPER CTRL, PRINT, exec, hyprshot -m output --freeze

# Multimedia
bind =, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+
bind =SUPER, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+
bind =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bind =SUPER, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind =,XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind =, XF86AudioPlay, exec, playerctl play-pause
bind =, XF86AudioPause, exec, playerctl play-pause
bind =, XF86AudioNext, exec, playerctl next
bind =, XF86AudioPrev, exec, playerctl previous

# Backlight control
bind = , xf86monbrightnessup, exec, brightnessctl s 1%+
bind = , xf86monbrightnessdown, exec, brightnessctl s 1%-
bind = SUPER, xf86monbrightnessup, exec, brightnessctl s 100%
bind = SUPER, xf86monbrightnessdown, exec, brightnessctl s 1%
bind = SUPER CTRL, xf86monbrightnessup, exec, brightnessctl s 20%+
bind = SUPER CTRL, xf86monbrightnessdown, exec, brightnessctl s 20%-

======Config-End========

### Description

I'm experiencing a crash on my Linux system whenever I connect a second monitor while using Hyprland. The crash report displays the message:

'Calm down, it was a misinput! MISINPUT!'

I'm unsure if this is an issue with my setup or a bug within Hyprland. The crash consistently occurs immediately after connecting the second monitor. i can launch hyprland normally after the crash while the second monitor is still connected. 

### How to reproduce

Start Hyprland on a system with one monitor connected.
Connect a second monitor via HDMI/DisplayPort/etc.
Observe that Hyprland crashes immediately after the second monitor is connected.

### Crash reports, logs, images, videos

[hyprlandCrashReport726.txt](https://github.com/user-attachments/files/16723739/hyprlandCrashReport726.txt)

**Comment by romanstingler** [comment]
can you try installing  hyprland-git and aquamarine-git 

first you need to uninstall hyprland 
like yay -R hyprland aquamarine

**Comment by izmyname** [comment]
> can you try installing hyprland-git and aquamarine-git
> 
> first you need to uninstall hyprland like yay -R hyprland aquamarine

Offtopic, but better use yay -S hyprland-git, aquamarine-git hyprlang-git hyprcursor-git  hyprutils-git. Or yay -Rns hyprland , because having hyprland-git with the non-git deps can cause extra problems.

**Comment by vaxerski** [comment]
I'd rather not open the 20th issue about this, besides it's likely fixed
