### ISSUE TITLE
Remmina crashes Hyprland

### ISSUE THREAD

**Issue by MrPickles1324** [hyprwm/Hyprland#749]
after this commit https://github.com/hyprwm/Hyprland/commit/2636abca2dcf1eca2c0296bb817f644b8626a860 connecting through rdp with Remmina crashes Hyprland
[hyprland.log](https://github.com/hyprwm/Hyprland/files/9682585/hyprland.log)
[coredump.txt](https://github.com/hyprwm/Hyprland/files/9682587/coredump.txt)

**Comment by vaxerski** [comment]
check with 59a3c43913b0536112f3700251aea28768c6882e

**Comment by MrPickles1324** [comment]
works! Thank you
