### ISSUE TITLE
Drag-and-drop doesn't work under chromium (wayland)

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#7496]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 688fe5c14781c63a1db23d4d02bf239283068ff6 dirty (windowrules: add fullscreenstate field (7466)).
Date: Sat Aug 24 03:42:14 2024
Tag: v0.42.0-62-g688fe5c1, commits: 5131

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.10.5-2-cachyos-lto
Version: #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 08:14:57 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

I tried bisect and went back to aquamarine before drag-and-drop didn't work either, probably influenced by other factors.

### How to reproduce

1. with `chromium --ozone-platform=wayland` command startup chromium
2. Click on a link tag and drag

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/d59e0adc-4654-44bf-81b8-749b0ca0a9ff

**Comment by vaxerski** [comment]
works on my end? I can drag it into a new tab

**Comment by hdm9527** [comment]
I didn't describe it well, it's possible to drag a link into a new tab, followed by no response to left mouse click anywhere in chromium.

**Comment by nexsych** [comment]
Happening for me as well on brave since yesterday. After dragging something on the page or even dragging toolbar elements like extensions, the browser gets stucked with a hand symbol in place of the cursor.

See this:
- https://community.brave.com/t/brave-crashes-while-selecting-or-dragging-page-element-on-fedora-kde/545980/5
- https://chromium.googlesource.com/chromium/src/+/876fbd5552c8fb9d4889ba0371e4d7e3bfa9af84%5E%21/

> This works as a mitigation to prevent browser process from hanging, ie:
> stopping to respond to input events caused by an never ending
drag-and-drop loop when dealing with misbehaving/buggy or malicious
Wayland compositors.

> A real case of this was found in the wild with some versions of Kwin 6,
as described in the linked crbugs.

**Comment by nexsych** [comment]
> works on my end? I can drag it into a new tab

Happening for me as well on brave. After dragging something on the page or even dragging toolbar elements like extensions, the browser gets stucked with a hand symbol in place of the cursor.

See this:
- https://community.brave.com/t/brave-crashes-while-selecting-or-dragging-page-element-on-fedora-kde/545980/5
- https://chromium.googlesource.com/chromium/src/+/876fbd5552c8fb9d4889ba0371e4d7e3bfa9af84%5E%21/

> This works as a mitigation to prevent browser process from hanging, ie:
> stopping to respond to input events caused by an never ending
drag-and-drop loop when dealing with misbehaving/buggy or malicious
Wayland compositors.

> A real case of this was found in the wild with some versions of Kwin 6,
as described in the linked crbugs.

**Comment by hiddenruins** [comment]
Similar issue: https://github.com/hyprwm/Hyprland/issues/6509

This issue started appearing again on the newer versions (nightly/unstable) of the browsers.

**Comment by gmr458** [comment]
I have this issue with Brave and Google Chrome, but no with Chromium.

Brave: Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)
Google Chrome: Version 128.0.6613.84 (Official Build) (64-bit)
Chromium: Version 127.0.6533.99 (Official Build) Fedora Project (64-bit)

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.10.6-100.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:35:32 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

</details>

**Comment by hdm9527** [comment]
> I have this issue with Brave and Google Chrome, but no with Chromium.
> 
> Brave: Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) Google Chrome: Version 128.0.6613.84 (Official Build) (64-bit) Chromium: Version 127.0.6533.99 (Official Build) Fedora Project (64-bit)
> 
> System/Version info

Both chrome and brave are based on chromium.

**Comment by gmr458** [comment]
@hdm9527 I know, but for some reason Brave and Google Chrome have the issue and Chromium doesn't.

**Comment by wenjie1991** [comment]
@gmr458 I have the same issue in the most updated Chromium 130.0.6681.0

**Comment by aryklein** [comment]
Same problem here, with Brave and Chromium

```
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)
```

**Comment by karamanliev** [comment]
Got the same issue on Brave. I think it started after nvidia 560 drivers.

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: karamanliev
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


GPU information:
26:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

**Comment by MHellmund** [comment]
The Plasma/KWin people had a similar problem. Perhaps related? 
https://invent.kde.org/plasma/kwin/-/commit/711c5bb43f2823766d5189dc8d567c8f4cec253c

**Comment by alex73630** [comment]
From my testing, it seems likely that a regression occurred on Chromium side between version 127 and 128 and @gmr458 message seems to point to the same direction.

**Comment by vaxerski** [comment]
> The Plasma/KWin people had a similar problem. Perhaps related?
https://invent.kde.org/plasma/kwin/-/commit/711c5bb43f2823766d5189dc8d567c8f4cec253c

Mhm, so looks like a bug in chromium that could be somewhat alleviated on our side

**Comment by alex73630** [comment]
Just switched to `hyprland-git` on Arch and I can confirm issue is solved with the fix :+1:

**Comment by coffebar** [comment]
Can reproduce on Google Chrome 128 and hyprland-git

**Comment by hiimsergey** [comment]
Downgrading to Chromium 127 works too

**Comment by vaxerski** [comment]
yes because it's a chromium regression that can be alleviated if hyprland better responds to invalid protocol usage
