### ISSUE TITLE
Black screen with just a mouse cursor

### ISSUE THREAD

**Issue by CazSaa** [hyprwm/Hyprland#7497]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
```

This is what i got when running the command from a different TTY. I can't run the command from within Hyprland because it's just a black screen.

</details>

[hyprland.conf](https://github.com/user-attachments/files/16736660/hyprland.conf.txt)

### Description

When logging into Hyprland from SDDM, all I get is black screens (4 monitors) and a working mouse cursor. Keyboard doesn't seem to do anything.

### How to reproduce

Just log in.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/16736666/hyprland.log)

**Comment by vaxerski** [comment]
if that's your entire config then what do you expect? you didn't even use the default config which would at least give you some binds.
