### ISSUE TITLE
Crash when connecting hdmi display

### ISSUE THREAD

**Issue by staviq** [hyprwm/Hyprland#7498]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 688fe5c14781c63a1db23d4d02bf239283068ff6  (windowrules: add fullscreenstate field (7466)).
Date: Fri Aug 23 21:42:14 2024
Tag: , commits: 1

flags: (if any)


System Information:
System name: Linux
Node name: <redacted>
Release: 6.10.4-hardened1-1-hardened
Version: #1 SMP PREEMPT_DYNAMIC Wed, 14 Aug 2024 11:38:28 +0000


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Basically 100% reproducible crash when connecting external monitor.

Judging by the log ( stdout ) it looks like Hyprland tries to use the display too soon maybe ?

I pulled and built debug from main, but it produces empty crash reports due to `CrashReporter exceeded timeout`

Anyway, I puled the trace from systemd crashdump (`gdb.txt`) for ya.

**EDIT:** Happens both on `hyprland 0.42.0-1 (arch repo)` and 688fe5c14781c63a1db23d4d02bf239283068ff6

### How to reproduce

1. Start Hyprland
2. Close laptop lid
3. Connect HDMI monitor
4. Crash.

### Crash reports, logs, images, videos

[gdb.txt](https://github.com/user-attachments/files/16736824/gdb.txt)
[hyprland_1lidclose_2connecthdmi_3start_4works.log](https://github.com/user-attachments/files/16736825/hyprland_1lidclose_2connecthdmi_3start_4works.log)
[hyprland_1start_2lidclose_3connecthdmi_4crash.log](https://github.com/user-attachments/files/16736829/hyprland_1start_2lidclose_3connecthdmi_4crash.log)
[hyprland.conf.txt_because_github_dumb.txt](https://github.com/user-attachments/files/16736835/hyprland.conf.txt_because_github_dumb.txt)

**Comment by tjavdar** [comment]
Confirmed also for 07a11f49.

Same hotplug regression since v0.41.2.

**Comment by zayihu** [comment]
+1, I have them all, crashing upon hotplug, black screen upon hot plug then not crushing. Also hanging hyprlock up wake up on second screen while I can move windows to second screen even open apps there, just do not see.

**Comment by zayihu** [comment]
All was perfect in 0.41.2

**Comment by rgerardi** [comment]
+1 seeing same here. Hyprland crashes when connecting the HDMI monitor first time after boot. Upon restarting Hyprland I am able to connect and disconnect the external monitor without any issues.

Tested with package from Arch repo v 0.42.0-1

**Comment by JacobButcher-Github** [comment]
+1 seeing the same. Downgrading to Arch Repo v 0.41.2-3 solved the issue for me.

Adding I had the following log:
Aug 24 17:29:30 archlinux kernel: i915 0000:00:02.0: [drm] *ERROR* Sending link address failed with -5

for displayport to usb-c issues

**Comment by SteavenGamerYT** [comment]
+1 same issue on fedora 41
Hyprland, built from branch main at commit 688fe5c14781c63a1db23d4d02bf239283068ff6  ().

**Comment by ikalco** [comment]
try this aquamarine patch
[patch.txt](https://github.com/user-attachments/files/16740911/patch.txt)

**Comment by magthe** [comment]
I don't think this is limited to HDMI, I see the same behaviour when attaching a USB-C screen.

**Comment by staviq** [comment]
@ikalco 
> try this aquamarine patch [patch.txt](https://github.com/user-attachments/files/16740911/patch.txt)

Sorry for the late reply, I caught a bad cold

Yes, it looks like that fixes the problem (aquamarine cloned from AUR `aquamarine-git 0.3.3_r200.g3989aa9-1` and your patch applied via PKGBUILD).

So far, no additional problems caused by the path either, but I've only been testing for like half an hour.
