### ISSUE TITLE
Launching Hyprland without a monitor

### ISSUE THREAD

**Issue by lmsorry** [hyprwm/Hyprland#7500]
I want to start Hyprland automatically without using a monitor, and then use wayvnc to connect to the desktop. But I encountered a problem, hyprctl output create prompts `HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)`
But when I try to unplug the monitor and run Hyprland, it doesn't run. The log file is below, I hope to get help.

![IMG20240824235259](https://github.com/user-attachments/assets/b7fbeb38-cc63-4733-b208-cef5b169f62a)

**Comment by vaxerski** [comment]
please use a template
