### ISSUE TITLE
The "hyprctl dispatch ..." command cannot close the window

### ISSUE THREAD

**Issue by this-cat** [hyprwm/Hyprland#7502]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
                   -`                    lin@arch 
                  .o+`                   -------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.6.45-x64v1-xanmod1-1-lts 
               `+oooooo:                 Uptime: 18 mins 
               -+oooooo+:                Packages: 2379 (pacman) 
             `/:-:++oooo+:               Shell: zsh 5.9 
            `/++++/+++++++:              Resolution: 1920x1080 
           `/++++++++++++++:             DE: Hyprland 
          `/+++ooooooooooooo/`           Theme: Nordic [GTK2/3] 
         ./ooosssso++osssssso+`          Icons: Tela-light [GTK2/3] 
        .oossssso-````/ossssss+`         Terminal: kitty 
       -osssssso.      :ssssssso.        CPU: Intel i7-10700KF (16) @ 5.100GHz 
      :osssssss/        osssso+++.       GPU: NVIDIA GeForce GTX 1660 SUPER 
     /ossssssss/        +ssssooo/-       Memory: 3769MiB / 31997MiB 

```

</details>

### Description

╰─ hyprctl clients                             
Window 55c3dbed4550 -> androp:
	mapped: 1
	hidden: 0
	at: 22,22
	size: 1876,1036
	workspace: 2 (2)
	floating: 0
	pseudo: 0
	monitor: 1
	class: flix
	title: androp
	initialClass: flix
	initialTitle: androp
	pid: 10777
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 2

╭─ ~                                                                                         ✔  system Node  12:22:15 
╰─ sleep 3s; hyprctl dispatch kill 55c3dbed4550
Invalid dispatcher

╭─ ~                                                                                    ✔  3s  system Node  12:22:30 
╰─ sleep 3s; hyprctl dispatch killactive       
ok

Unable to close the window using the command, but using pkill flix can close it.

### How to reproduce

The software originates from "https://flix.center/"

**Comment by ikalco** [comment]
`hyprctl dispatch kill` doesn't exist,
if you want to close a window by its address you can use something like 
`hyprctl dispatch closewindow address:0x123456789123`
or if you want to close one using your cursor, use `hyprctl kill`

**Comment by vaxerski** [comment]
as above

**Comment by this-cat** [comment]
The command "hyprctl kill" can close windows (but it forcefully closes them). The commands "hyprctl dispatch killactive" and "hyprctl dispatch closewindow address:0x55c3dbed4550" still fail to close the window.
