### ISSUE TITLE
Allow corner radius for groupbars

### ISSUE THREAD

**Issue by freerunner** [hyprwm/Hyprland#7521]
### Description

![hyprland_groupbars_mockup](https://github.com/user-attachments/assets/c7d90af5-7491-45e4-9663-53d087ad4298)

If you look at the provided mock-up, you can see the current look of the groupbars on the left side. Corners are straight 90 degree angles. Unpleasant to the eyes.

The right side has been modified with a radius, similar to the window border (and shadows). Imho, this looks much better.

Currently, the groupbars do not really fit with the aesthaetics of the rest. 
It would be so nice if we could define a radius for the groupbars. Shadow options (like in the hyprbars plugin), although no must would be great as well. 

If we could at least get rid of the sharp corners...

**Comment by vaxerski** [comment]
pretty much #2415
