### ISSUE TITLE
XWayland Borderless Window No Inputs

### ISSUE THREAD

**Issue by CrezyDud** [hyprwm/Hyprland#753]
I cannot interact with a borderless xwayland window in any other way than moving it
it wont accept keyboard or mouse
it probably just doesnt know its selected

umm

i dont know what to say sounds kinda empty, so here some more info:
- I use XWayland HiDPI patch with scaling 2
- The application with the bug is RDR2 with proton experimentel (it sets itself into borderless when i choose fullscreen while its running, so i cant really avoid unless using window, with border)

this is all, no crashes and so no logs

would this be fixed :)?

~ me

(if you need more info, tell me)

**Comment by vaxerski** [comment]
run through gamescope

**Comment by CrezyDud** [comment]
its still a bug, but thanks!

**Comment by vaxerski** [comment]
check with e7961576721f1bd7cc976d14c6dccaddf6c1a69f

**Comment by romanstingler** [comment]
@CrezyDud can this be closed?
