### ISSUE TITLE
Float: doesnt send input outside of window

### ISSUE THREAD

**Issue by CrezyDud** [hyprwm/Hyprland#754]
It seems as Hyperland is too picky about when to send mouse events, i have a good example

the wine task-bar

![grafik](https://user-images.githubusercontent.com/84625713/193303426-af45e53b-a9cf-4da9-8b3c-636efcba63bd.png)

i can click exit, because its inside the window, but the above options (Open & Settings), i cannot
because they are outside, this works fine in wayfire, but not here,
so it should be fixable

again, not much else here

soo.. i say happy day!

**Comment by vaxerski** [comment]
the fuck is a wine taskbar

**Comment by CrezyDud** [comment]
wine's taskbar

**Comment by CrezyDud** [comment]
for background applications

**Comment by vaxerski** [comment]
check with 355366714eb725d72286a7b6744d20a993ad57e5
