### ISSUE TITLE
Duplicate mouse when changing focus to another monitor

### ISSUE THREAD

**Issue by William-Bentley** [hyprwm/Hyprland#7543]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: ThinkStation
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630] [8086:3e98] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:


# Important Config info:

#Monitor Layout:

monitor = DP-2, 2560x1440@120, 0x0, 1
monitor = DP-3, 1920x1080@60, 2560x-180, 1, transform, 3

# Keybinding for focus monitor and kill window

bind = $mainMod, TAB, focusmonitor, +1
bind = $mainMod SHIFT, TAB, focusmonitor, -1
bind = $mainMod, Q, killactive,

```

</details>

### Description

On a dual monitor setup (config above):

After opening and closing a window, then using a keybind for "focusmonitor, +1", two instances of the mouse appear on both monitors until:

- keybind for focusmonitor is pressed
- mouse is moved
- timeout and mouse disappears

### How to reproduce

Assumed prerequisite:

- At lease two monitors
- Key bind for focus monitors like mine above

Also my monitors (config above):
Monitor 1: a 1440p screen
Monitor 2: a 1080p screen

Steps:

1. On an empty workspace on monitor 2 (for me this only worked from my 1080p monitor. I couldn't replicate the issue from my 1440p monitor), open any application, kitty or firefox both produced the issue (didn't test anything else)
2. Close the newly opened window (Super + Q for me)
3. Super + Tab: takes mouse to monitor 1 BUT leaves another mouse on monitor 2
4. [Optional] Sometimes (can't really figure out the pattern here) pressing Super + Tab one more time actually causes the issue - not step 3

**Comment by naksudev** [comment]
Hi, I managed to reproduce the bug with two 1920x1080@60 monitors.

I noticed that it only happens on my side when the env `WLR_NO_HARDWARE_CURSORS` is set at the start of Hyprland. I removed it (then restarted Hyprland) and the bug doesn't seems to happen again.

<details>
<summary>System info and version just in case..</summary>

```
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: NAKSU-PC
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Plus Graphics G1 (Ice Lake) [8086:8a56] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```
</details>

It might be a hint to fix this bug..

**Comment by Blackburn29** [comment]
![IMG_0120](https://github.com/user-attachments/assets/9baf7dcb-1837-42d7-a4f2-c3489ac746eb)
Can confirm the same issue on both of my machines. One on AMD graphics and the other on i915 Intel. 

I do not have `WLR_NO_HARDWARE_CURSORS` set and still experience the issue.

**Comment by vaxerski** [comment]
dupe but I forgot which #
