### ISSUE TITLE
No display at all

### ISSUE THREAD

**Issue by TheLastTeapot** [hyprwm/Hyprland#755]
I just updated Hyprland and it now is just a gray screen with the mouse

Error:

00:00:00.051 [GLES2] GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)

==========================================================================================
ASSERTION FAILED!

Attempted to draw NULL texture!

at: line 390 in OpenGL.cpp
2022-09-30 15:28:16 - [swaybg-1.1.1/main.c:579] Missing a required Wayland interface

**Comment by vaxerski** [comment]
since this is a regression, do a bisect and provide the faulty commit.

**Comment by TheLastTeapot** [comment]
I like your funny words magic man

**Comment by vaxerski** [comment]
`git bisect`. For more, see [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by TheLastTeapot** [comment]
fatal: not a git repository (or any of the parent directories): .git

**Comment by vaxerski** [comment]
maybe at least tell me the version that broke it?

**Comment by TheLastTeapot** [comment]
sorry I'm really not familiar with git

**Comment by vaxerski** [comment]
git gud.

At least tell me the version that broke it (which release, or latest 0.14.0 vs HEAD)

**Comment by TheLastTeapot** [comment]
It's waiting for good commit

**Comment by TheLastTeapot** [comment]
built from source, idk when I last updated it

**Comment by TheLastTeapot** [comment]
so master branch ig

**Comment by vaxerski** [comment]
does 0.14.0 work?

**Comment by TheLastTeapot** [comment]
let me see

**Comment by TheLastTeapot** [comment]
ok when I downloaded the code for that version, subprojects/wlroots was empty so it won't compile and if i replace subprojects/wlroots with the same folder from my original clone it gives the same error

**Comment by pltanton** [comment]
Can confirm gray screen on master and v0.14.0beta

**Comment by vaxerski** [comment]
I see GLES2 - are you using LEGACY_RENDERER, perhaps?

**Comment by vaxerski** [comment]
> Can confirm gray screen on master and v0.14.0beta

How far down does it go? Can you provide the latest release on which it doesn't occur?

**Comment by TheLastTeapot** [comment]
I am not using legacyrender

**Comment by pltanton** [comment]
Can't find any working commit at all Oo. Is there some cache or smt?

**Comment by vaxerski** [comment]
get the binary from each compiled release and replace the installed one with it, no?

**Comment by TheLastTeapot** [comment]
I am now about 99% certain it is a problem with your wlroots repo

**Comment by pltanton** [comment]
> get the binary from each compiled release and replace the installed one with it, no?
Not that easy with NixOS )))

> I am now about 99% certain it is a problem with your wlroots repo
Can confirm this! I lock version from previous generation: 7c575922c05e4d5fd9a403c2aa631a54c7531d44, and everything works fine with it!

**Comment by vaxerski** [comment]
can you try locking the latest HEAD of wlroots then and testing on it?

**Comment by fufexan** [comment]
> > get the binary from each compiled release and replace the installed one with it, no?
> 
> Not that easy with NixOS )))

You mean *way easier* on NixOS. Just point the flake ref to the release's commit and rebuild.

> > I am now about 99% certain it is a problem with your wlroots repo
> 
> Can confirm this! I lock version from previous generation: 7c575922c05e4d5fd9a403c2aa631a54c7531d44, and everything works fine with it!

No problems here with the latest wlroots.

**Comment by vaxerski** [comment]
possibly https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3499 ?

seems to affect only select intel gpu users.

**Comment by TheLastTeapot** [comment]
It randomly started working again, though it still gives the same error from terminal

**Comment by TheLastTeapot** [comment]
maybe bc I rolled back all my updates

**Comment by TheLastTeapot** [comment]
Im an idiot, the reason it was giving that error from terminal was bc I was using GNOME ON XORG  >:(
Facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm facepalm

**Comment by TheLastTeapot** [comment]
We still don't know what caused the gray screen though, that wasn't from testing on xorg

**Comment by vaxerski** [comment]
oh well, prolly your driver
