### ISSUE TITLE
Hyprland crashing on start.

### ISSUE THREAD

**Issue by Nel-xhan** [hyprwm/Hyprland#7552]
### Regression?

Yes

### System Info and Version

Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 21:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)

System Information:
System name: Linux
Node name: arch
Release: 6.10.6
Version: #1 SMP PREEMPT_DYNAMIC Wed Aug 21 16:06:37 CEST 2024

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB] [10de:249c] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/iwaniv/.config/hypr/hyprland.conf: Read Succeeded
#Hyprland Config#

#Window Rules

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl -s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl -s 5%-

# Keyboard backlight
bind = SUPER, F3, exec, brightnessctl -d *::kbd_backlight set +33%
bind = SUPER, F2, exec, brightnessctl -d *::kbd_backlight set 33%-
 

# League stuff
#
#
# Riot Client
windowrulev2 = nomaxsize, class:^(riotclientux\.exe)$,title:^(Riot\sClient\sMain)$
windowrulev2 = float, class:^(riotclientux\.exe)$,title:^(Riot\sClient\sMain)$
windowrulev2 = size 1530 850, class:^(riotclientux\.exe)$,title:^(Riot\sClient\sMain)$
windowrulev2 = opacity 1.0 override 1.0 override, class:^(riotclientux\.exe)$,title:^(Riot\sClient\sMain)$
# "center" doesnt seem to properly work on this client
windowrulev2 = move -200 -100, class:^(riotclientux\.exe)$,title:^(Riot\sClient\sMain)$

# League Clientsudo touch wg-client.conf
windowrulev2 = nomaxsize, class:^(leagueclientux\.exe)$,title:^(League\sof\sLegends)$
windowrulev2 = float, class:^(leagueclientux\.exe)$,title:^(League\sof\sLegends)$
windowrulev2 = size 1280 720,class:^(leagueclientux\.exe)$,title:^(League\sof\sLegends)$
windowrulev2 = center, class:^(leagueclientux\.exe)$,title:^(League\sof\sLegends)$
windowrulev2 = opacity 1.0 override 1.0 override, class:^(leagueclientux\.exe)$,title:^(League\sof\sLegends)$

# Game Client
windowrulev2 = opacity 1.0 override 1.0 override, class:^(league\sof\slegends\.exe)$,title:^(League\sof\sLegends\s\(TM\)\sClient)$
windowrulev2 = float,  class:^(league\sof\slegends\.exe)$,title:^(League\sof\sLegends\s\(TM\)\sClient)$
windowrulev2 = size 1680 1050, class:^(league\sof\slegends\.exe)$,title:^(League\sof\sLegends\s\(TM\)\sClient)$

#Monitor Settings

# unscale XWayland
xwayland {
  force_zero_scaling = true
}

monitor=eDP-1,1920x1080@240,0x0,1,bitdepth,10
monitor=HDMI-A-1,1680x1050@60,1920x0,1,bitdepth,10
#monitor=HDMI-A-1,2560x1440@60,1920x0,1,bitdepth,10
#monitor=DP-1,1920x1200@60,-1920x-120,1,bitdepth,10
workspace=1, monitor:eDP-1
workspace=2, monitor:HDMI-A-1
#workspace=DP-1,2

#Autostart

exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = dunst
exec-once = waybar 
exec-once = /usr/lib/polkit-kde-authentication-agent-1
#exec-once = pypr 

#Environment Variables 

env = XCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME=nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = VKD3D_CONFIG=dxr
env = PROTON_ENABLE_NVAPI=1
env = PROTON_ENABLE_NGX_UPDATER=1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = ENABLE_VKBASALT=1
env = __NV_PRIME_RENDER_OFFLOAD,1
env = __VK_LAYER_NV_optimus,NVIDIA_only
env = WAYLAND_DISPLAY=wayland-0
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = SDL_VIDEODRIVER,wayland
#env = SDL_VIDEODRIVER=x11
env = QT_QPA_PLATFORM,wayland
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1
env = NVreg_EnableGpuFirmware,1

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0.0
    accel_profile = flat

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2 #5
    gaps_out = 5 #20
    border_size = 0 #2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    #new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    #workspace_swipe = off
}

misc {
	force_default_wallpaper = 2
}
# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
#device:epic-mouse-v1 {
#    sensitivity = -0.5
#}

# Example windowrule v1
#windowrule = float, title:^(krusader)$
 windowrule = float, title:^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, RETURN, exec, [float] kitty
bind = $mainMod, Q, killactive, 
bind = $mainMod, L, exit, 
bind = $mainMod, E, exec, [float] krusader 
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, [float] rofi -show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, B, exec, librewolf
bind = $mainMod, W, exec, waybar
bind = $mainMod|SHIFT, W, exec, killall waybar && waybar 		
bind = $mainMod, S, exec, [float] /home/iwaniv/Git/Signal-Desktop/release/linux-unpacked/signal-desktop 
bind = $mainMod, comma, workspace, e-1
bind = $mainMod, period, workspace, e+1
bind = $mainMod, C, exec, rpcs3
#Special Workspace
#bind = $mainMod, S, movetoworkspace, special

# Move focus with mainMod + arrow keys-fgraphite-identity -floop-nest-optimize -fPIE -fomit-frame-pointer -fprofile-generate -fprofile-arcs -fearly-inlining -fvpt"
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

======Config-End========

### Description

Hyprland is crashing on start, every version after the 0.42.0 release.

### How to reproduce

Pull from github, compile, start from tty.

### Crash reports, logs, images, videos

[hyprlandCrashReport3218.txt](https://github.com/user-attachments/files/16778792/hyprlandCrashReport3218.txt)
[hyprlandCrashReport3359.txt](https://github.com/user-attachments/files/16778793/hyprlandCrashReport3359.txt)

**Comment by vaxerski** [comment]
can you install aquamarine-git?

**Comment by Nel-xhan** [comment]
Thanks that did it, thought i had installed it.
