### ISSUE TITLE
Fractional values for `border-size`

### ISSUE THREAD

**Issue by Anik200** [hyprwm/Hyprland#7557]
### Description

well currently only interger values are supported for border size which dosent allow me to set eg. 1.23 or 3.44 values as border size, i would really like to have this feature in the future updates :)

**Comment by vaxerski** [comment]
no? fractional pixels dont exist

**Comment by Anik200** [comment]
> no? fractional pixels dont exist

But like in css for eg. Waybar i am able to set border like `2.3px solid green` is that a thing ?

**Comment by vaxerski** [comment]
sure you can set it but fractional pixels don't exist.

The rendering engine will either outright ignore you and do 2 or add a translucent outline
