### ISSUE TITLE
Toolbar in ImageJ registers no input [proposed label not-hyprland]

### ISSUE THREAD

**Issue by Lornake** [hyprwm/Hyprland#757]
Hello,

When opening the image analysis software ImageJ in hyprland I get a very specific issue: the program by default has two toolbars at the top of its window, and I can click on one but not the other. The program works cpompletely fine otherwise, but the top one of the two does not register any hovering/clicking input whatsoever, and it is essential for full functionality.

I love hyprland and want to use it on my work computer, but I need this software, and haven't had this issue in any other desktop environment/window manager/compositor/etc..

OS: Arch Linux x86_64 
Kernel: 5.19.10-arch1-1-surface 
Resolution: 2256x1504 
DE: Hyprland 
CPU: Intel i5-7200U (4) @ 3.100GHz 
GPU: Intel HD Graphics 620 

Duplicate:
1. Download ImageJ for Linux (imagej.net it's completely free and safe, ubiquitous in scientific laboratories)

2. Unzip the file (it's like a portable application)

3. run */ImageJ-linux64

![image](https://user-images.githubusercontent.com/102933579/193406947-2eaf71f9-4c56-41f2-badd-9ed03e07bfef.png)

4. the window will open and work perfectly well, except for the uppermost toolbar (with the tabs File, Edit, Image, etc.) which will register no input.

To solve this I've tried:
a)Changing the window type/resolution/fullscreen in hyprland
b) Other versions of this same software (like the AUR package since I'm on Arch)
c) Running it in other versions of Java
d) Running it through gamescope, as a last ditch effort. Although it is not usable in gamescope, within it the toolbar I'm talking about does indeed register input. But gamescope doesn't handle the software properly enough for it to be functional, I just tried it to see if it would give me a hint.

I know this is quite the specific issue, but I hope it can be resolved.
Thank you and please let me know if I can give more information.

Edits: added picture of the ImageJ UI for reference

**Comment by Lornake** [comment]
Resolved by adding 

`export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24`

to Hyprland script

**Comment by vaxerski** [comment]
as explained in the wiki :)

**Comment by Lornake** [comment]
So that worked for excactly 5 minutes, then I restarted the program and the problem was back. Ideas?

**Comment by vaxerski** [comment]
you should be able to focus on the drop-down menu only on the part that is actually *inside* the main window. (blame X11). Then, you can navigate with the arrow keys.

**Comment by vaxerski** [comment]
clicking *kind of* fixed in 355366714eb725d72286a7b6744d20a993ad57e5

if you don't leave the dropdown it will work. If you leave it, it won't be focusable anymore until you focus the parent again.
