### ISSUE TITLE
Sometimes, Hyprland crashes when I plug an HDMI in

### ISSUE THREAD

**Issue by ValentinMATHIEU** [hyprwm/Hyprland#7570]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: laptop
Release: 6.10.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/vmathieu/.config/hypr/hyprland.conf: Read Succeeded
# ##########################################################
# ENV VARS

env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct # qt5ct / qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1

# ##########################################################
# Start apps / background apps / system tray applets

exec-once = swaybg --image ~/Wallpapers/3840x1600/ponta_de_sao_lourenco_madeira_portugal.jpg --mode center
exec-once = swaync
exec-once = ~/.config/waybar/launcher.sh
exec-once = ~/.config/hypr/scripts/xdg-desktop-portal-hyprland-launcher

# Screen sharing
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Clipboard managers
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# ##########################################################
# Start workspaces apps

bind = ALT, j, exec, ~/.aldris/hyprland/deploy-apps

exec-once = [workspace special:magic silent] alacritty -e btop

# ##########################################################
# MONITORS

source = ~/.config/hypr/monitor.conf/monitor

bind = SUPER SHIFT, L, exec, ln -sf ~/.config/hypr/monitor.conf/laptop.conf ~/.config/hypr/monitor.conf/monitor
bind = SUPER SHIFT, K, exec, ln -sf ~/.config/hypr/monitor.conf/home.conf   ~/.config/hypr/monitor.conf/monitor
bind = SUPER SHIFT, J, exec, ln -sf ~/.config/hypr/monitor.conf/office.conf ~/.config/hypr/monitor.conf/monitor

# ##########################################################
# VARIABLES

source = ~/.config/hypr/input.conf/input
bind = SUPER SHIFT, U, exec, ln -sf ~/.config/hypr/input.conf/input-us.conf ~/.config/hypr/input.conf/input
bind = SUPER SHIFT, F, exec, ln -sf ~/.config/hypr/input.conf/input-fr.conf ~/.config/hypr/input.conf/input

general {
    layout                = dwindle
    gaps_in               = 0
    gaps_out              = 0
    border_size           = 1
    no_border_on_floating = false
    col.active_border     = 0xffffffff
    col.inactive_border   = 0xff444444
    allow_tearing         = false
}

decoration {
    rounding         = 1
    active_opacity   = 1.0
    inactive_opacity = 1.0
    blur {
        enabled = true
        size    = 3
        passes  = 1
    }
    dim_inactive        = true
    dim_strength        = 0
    drop_shadow         = false
    shadow_range        = 4
    shadow_render_power = 3
    col.shadow          = rgba(1a1a1aee)
}

animations {
    enabled   = no

    #bezier    = myBezier,    0.05, 0.9, 0.1,     1.05
    #animation = windows,     1,    7,   myBezier
    #animation = windowsOut,  1,    7,   default, popin 80%
    #animation = border,      1,    10,  default
    #animation = borderangle, 1,    8,   default
    #animation = fade,        1,    7,   default
    #animation = workspaces,  1,    6,   default
}

dwindle {
    pseudotile     = yes
    preserve_split = yes
}

misc {
    force_default_wallpaper    = 0   # Set to 0 or 1 to disable the anime mascot wallpapers
    vfr                        = true
    mouse_move_focuses_monitor = true
}

# ##########################################################
# DEVICES CONFIG

input {
    sensitivity        = 0.6
    accel_profile      = flat
    force_no_accel     = true
    numlock_by_default = true

    touchpad {
        scroll_factor = 0.2
    }
}

device {
    name        = Wireless Mouse MX Master
    sensitivity = 1.0
}

device {
    name        = logitech-g502-hero-gaming-mouse
    sensitivity = 1
}

# ##########################################################
# WINDOW RULES (use "hyprctl clients" or "hyprprop" to get class)

# Dynamic rules for windows
  # Open those program in floating mode
windowrulev2 = float,class:(1Password|subl|strawberry|piper|blueberry.py|org.telegram.desktop|org.gnome.Nautilus|minecraft-launcher|xdg-desktop-portal-gtk)
  # Picture-in-picture window as floating and pinned
windowrulev2 = float,title:(Picture-in-Picture)
windowrulev2 = pin,title:(Picture-in-Picture)
  # Open Google Meet in float and pin
windowrulev2 = float,initialTitle:meet.google.com
windowrulev2 = pin,initialTitle:meet.google.com
windowrulev2 = size 850 620,initialTitle:meet.google.com

# Screen sharing
# @see https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/
windowrulev2 = opacity 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$

# ##########################################################
# BINDINGS

# MEDIA KEYS
  # Sound
bind = , XF86AudioMute,        exec, pactl set-sink-mute   @DEFAULT_SINK@   toggle
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@   +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@   -5%
bind = , XF86AudioMicMute,     exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Toggle tile fullscreen
bind = ALT, F, fullscreen

# Toggle notification center / swaync-client
bind = ALT, N, exec, swaync-client -t -sw

# Toggle animations
bind = ALT SHIFT, F1, exec, ~/.config/hypr/toggle_perf-mode.sh 1
bind = ALT SHIFT, F2, exec, ~/.config/hypr/toggle_perf-mode.sh 2

# System tools
bind = ALT,         S, exec, [floating] pavucontrol
bind = ALT,         P, exec, slurp | grim -g - - | wl-copy
bind = ALT SHIFT,   P, exec, slurp | grim -g - Screenshots/screenshot-$(date +"%Y-%m-%d_%H:%M:%S")-$(openssl rand -hex 4).png.png

# Galculator
bind = ALT,         G, exec, [floating] galculator
# Blueberry (bluetooth application wrapped to use gnome-bluetooth outside of GNOME)
bind = ALT,         B, exec, blueberry
# Nautilus (file explorer)
bind = ALT,         E, exec, nautilus

# Clipboard manager
bind = ALT,         L, exec, cliphist list | wofi --dmenu --width 1000 --height 300 --insensitive --gtk-dark | cliphist decode | wl-copy
bind = ALT SHIFT,   L, exec, cliphist wipe

# Toggle gammastep
bind = SUPER,       G, exec, gammastep -m wayland -O 4500K
bind = SUPER SHIFT, G, exec, pkill gammastep

# Change Dwindle orientation split
bind = ALT, Tab, layoutmsg, togglesplit

# System - Screen brightness
bind = SUPER, Up,                     exec, xbacklight -set 100
bind = SUPER, Down,                   exec, xbacklight -set 0.1
bind = ,      XF86MonBrightnessUp,    exec, xbacklight -inc 5
bind = ,      XF86MonBrightnessDown,  exec, xbacklight -dec 5

# System apps binds
bind = ALT,         Q,               killactive,
bind = ALT,         Space,           togglefloating
bind = ALT  SHIFT,  Space,           pin
bind = ALT,         D,         exec, wofi --dmenu --show=drun --width 1000 --height 400 --insensitive --gtk-dark --allow-images --allow-markup --term alacritty
bind = ALT,         Return,    exec, alacritty
bind = ALT,         A,         exec, [floating] alacritty
bind = SUPER SHIFT, Backspace, exec, wlogout
bind = SUPER,       L,         exec, ~/.aldris/hyprland/bind-scripts/swaylock

# Goto next/previous workspaces
bind = ALT, right, workspace, e+1
bind = ALT, left,  workspace, e-1

# Move between workspaces
bind = ALT, code:10, workspace, 1
bind = ALT, code:11, workspace, 2
bind = ALT, code:12, workspace, 3
bind = ALT, code:13, workspace, 4
bind = ALT, code:14, workspace, 5
bind = ALT, code:15, workspace, 6
bind = ALT, code:16, workspace, 7
bind = ALT, code:17, workspace, 8
bind = ALT, code:18, workspace, 9
bind = ALT, code:19, workspace, 10

# Send active app to workspaces
bind = ALT SHIFT, code:10, movetoworkspacesilent, 1
bind = ALT SHIFT, code:11, movetoworkspacesilent, 2
bind = ALT SHIFT, code:12, movetoworkspacesilent, 3
bind = ALT SHIFT, code:13, movetoworkspacesilent, 4
bind = ALT SHIFT, code:14, movetoworkspacesilent, 5
bind = ALT SHIFT, code:15, movetoworkspacesilent, 6
bind = ALT SHIFT, code:16, movetoworkspacesilent, 7
bind = ALT SHIFT, code:17, movetoworkspacesilent, 8
bind = ALT SHIFT, code:18, movetoworkspacesilent, 9
bind = ALT SHIFT, code:19, movetoworkspacesilent, 10

# Move current workspace to focused monitor
bind = ALT CTRL SHIFT, code:10, exec, hyprctl dispatch moveworkspacetomonitor 1  current
bind = ALT CTRL SHIFT, code:11, exec, hyprctl dispatch moveworkspacetomonitor 2  current
bind = ALT CTRL SHIFT, code:12, exec, hyprctl dispatch moveworkspacetomonitor 3  current
bind = ALT CTRL SHIFT, code:13, exec, hyprctl dispatch moveworkspacetomonitor 4  current
bind = ALT CTRL SHIFT, code:14, exec, hyprctl dispatch moveworkspacetomonitor 5  current
bind = ALT CTRL SHIFT, code:15, exec, hyprctl dispatch moveworkspacetomonitor 6  current
bind = ALT CTRL SHIFT, code:16, exec, hyprctl dispatch moveworkspacetomonitor 7  current
bind = ALT CTRL SHIFT, code:17, exec, hyprctl dispatch moveworkspacetomonitor 8  current
bind = ALT CTRL SHIFT, code:18, exec, hyprctl dispatch moveworkspacetomonitor 9  current
bind = ALT CTRL SHIFT, code:19, exec, hyprctl dispatch moveworkspacetomonitor 10 current

# Use special workspace (scratchpad)
bind = ALT,       M, togglespecialworkspace, magic
bind = ALT SHIFT, M, movetoworkspacesilent,  special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = ALT, mouse_down, workspace, e+1
bind = ALT, mouse_up,   workspace, e-1

# Windows move
    # Using Left Mouse Button
bindm = ALT, mouse:272, movewindow
    # Using keyboard
        # Slap window
bind = ALT Ctrl,  right, movewindow, r
bind = ALT Ctrl,  left,  movewindow, l
bind = ALT Ctrl,  up,    movewindow, u
bind = ALT Ctrl,  down,  movewindow, d
        # Gently ask to move by X pixel stop
bind = ALT SHIFT, right, moveactive,  50 0
bind = ALT SHIFT, left,  moveactive, -50 0
bind = ALT SHIFT, up,    moveactive, 0   -50
bind = ALT SHIFT, down,  moveactive, 0   50

# Window resize
    # Using Right Mouse Button
bindm = ALT, mouse:273, resizewindow
    # Using keyboard
bind = ALT, R, submap, resize
submap=resize
    bind = ,      right,  resizeactive, 100 0
    bind = ,      left,   resizeactive, -100 0
    bind = ,      down,   resizeactive, 0 100
    bind = ,      up,     resizeactive, 0 -100
    bind = SHIFT, right,  resizeactive, 10 0
    bind = SHIFT, left,   resizeactive, -10 0
    bind = SHIFT, down,   resizeactive, 0 10
    bind = SHIFT, up,     resizeactive, 0 -10
    bind = ,      escape, submap,       reset
submap=reset



Config File: /home/vmathieu/.config/hypr/monitor.conf/monitor: Read Succeeded
monitor=desc:BOE 0x0A89,1920x1080,0x0,1



Config File: /home/vmathieu/.config/hypr/input.conf/input: Read Succeeded
input {
    # See https://wiki.hyprland.org/Configuring/Variables/
    # => sudo localectl set-keymap --no-convert fr us && sudo loadkeys fr us
    kb_layout    = us
    kb_variant   = intl
    kb_model     =
    #kb_options   = grp:win_space_toggle,ctrl:nocaps # Remap Caps-Lock to Ctrl
    kb_rules     =
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

======Config-End========
```

</details>

### Description

The Display Server crash and i am back to the Display manager.

### How to reproduce

Plug a HDMI cable in

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Maybe you should try dusting your PC in the meantime?

Hyprland received signal 11(SEGV)
Version: 9a09eac79b85c846e3a865a9078a3f8ff65a9259
Tag: v0.42.0
Date: Wed Aug 7 19:17:10 2024
Flags:

System info:
	System name: Linux
	Node name: laptop
	Release: 6.10.6-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a60] (rev 01) (prog-if 00 [VGA controller])

os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x5b41c06466a1]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xb89) [0x5b41c05c6609]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x5b41c0546f71]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x7e9da664c1d0]
		??
		??:0
	#4 | /usr/lib/libaquamarine.so.2(+0x311af) [0x7e9da70721af]
		??
		??:0
	#5 | Hyprland(_ZN15CPointerManager17setHWCursorBufferEN9Hyprutils6Memory14CSharedPointerINS_20SMonitorPointerStateEEENS2_IN10Aquamarine7IBufferEEE+0x2d8) [0x5b41c069ee78]
		CPointerManager::setHWCursorBuffer(Hyprutils::Memory::CSharedPointer<CPointerManager::SMonitorPointerState>, Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>)
		??:?
	#6 | Hyprland(_ZN15CPointerManager21attemptHardwareCursorEN9Hyprutils6Memory14CSharedPointerINS_20SMonitorPointerStateEEE+0x217) [0x5b41c06a18d7]
		CPointerManager::attemptHardwareCursor(Hyprutils::Memory::CSharedPointer<CPointerManager::SMonitorPointerState>)
		??:?
	#7 | Hyprland(_ZN15CPointerManager19updateCursorBackendEv+0x3d0) [0x5b41c06a1f70]
		CPointerManager::updateCursorBackend()
		??:?
	#8 | Hyprland(_ZN15CPointerManager15setCursorBufferEN9Hyprutils6Memory14CSharedPointerIN10Aquamarine7IBufferEEERKNS0_4Math8Vector2DERKf+0xb2) [0x5b41c069a712]
		CPointerManager::setCursorBuffer(Hyprutils::Memory::CSharedPointer<Aquamarine::IBuffer>, Hyprutils::Math::Vector2D const&, float const&)
		??:?
	#9 | Hyprland(_ZN14CCursorManager15setCursorBufferEN9Hyprutils6Memory14CSharedPointerI13CCursorBufferEERKNS0_4Math8Vector2DERKf+0x9e) [0x5b41c06789fe]
		CCursorManager::setCursorBuffer(Hyprutils::Memory::CSharedPointer<CCursorBuffer>, Hyprutils::Math::Vector2D const&, float const&)
		??:?
	#1 | Hyprland(_ZN14CCursorManager17setCursorFromNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x183) [0x5b41c067a843]
		CCursorManager::setCursorFromName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
		??:?
	#11 | Hyprland(_ZN14CCursorManager11updateThemeEv+0x149) [0x5b41c067b799]
		CCursorManager::updateTheme()
		??:?
	#12 | Hyprland(+0x29095c) [0x5b41c067b95c]
		CCursorManager::updateTheme()
		??:?
	#13 | Hyprland(_ZN18CHookSystemManager4emitEPSt6vectorI14SCallbackFNPtrSaIS1_EER13SCallbackInfoSt3any+0x4bf) [0x5b41c067eacf]
		CHookSystemManager::emit(std::vector<SCallbackFNPtr, std::allocator<SCallbackFNPtr> >*, SCallbackInfo&, std::any)
		??:?
	#14 | Hyprland(_ZN13CHyprRenderer16applyMonitorRuleEP8CMonitorP12SMonitorRuleb+0xb39) [0x5b41c0831b99]
		CHyprRenderer::applyMonitorRule(CMonitor*, SMonitorRule*, bool)
		??:?
	#15 | Hyprland(_ZN8CMonitor9onConnectEb+0xca1) [0x5b41c06446a1]
		CMonitor::onConnect(bool)
		??:?
	#16 | Hyprland(_ZN11CCompositor12onNewMonitorEN9Hyprutils6Memory14CSharedPointerIN10Aquamarine7IOutputEEE+0x329) [0x5b41c05690c9]
		CCompositor::onNewMonitor(Hyprutils::Memory::CSharedPointer<Aquamarine::IOutput>)
		??:?
	#17 | Hyprland(+0x186c06) [0x5b41c0571c06]
		std::any::_Manager_internal<Hyprutils::Memory::CSharedPointer<CMonitor> >::_S_manage(std::any::_Op, std::any const*, std::any::_Arg*)
		??:?
	#18 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal21CStaticSignalListener4emitESt3any+0x66) [0x7e9da6c0fdc6]
		??
		??:0
	#19 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x59e) [0x7e9da6c103be]
		??
		??:0
	#2 | /usr/lib/libaquamarine.so.2(_ZN10Aquamarine13SDRMConnector7connectEP17_drmModeConnector+0x133d) [0x7e9da70e4cbd]
		??
		??:0
	#21 | /usr/lib/libaquamarine.so.2(_ZN10Aquamarine11CDRMBackend14scanConnectorsEv+0xc10) [0x7e9da70df500]
		??
		??:0
	#22 | /usr/lib/libaquamarine.so.2(+0xa96f4) [0x7e9da70ea6f4]
		??
		??:0
	#23 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x7e9da6c0fc9f]
		??
		??:0
	#24 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ee) [0x7e9da6c1000e]
		??
		??:0
	#25 | /usr/lib/libaquamarine.so.2(_ZN10Aquamarine8CSession18dispatchUdevEventsEv+0x4c1) [0x7e9da70b89b1]
		??
		??:0
	#26 | Hyprland(+0x2dd11a) [0x5b41c06c811a]
		handleTimer(void*)
		??:?
	#27 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x1f2) [0x7e9da6fef0a2]
		??
		??:0
	#28 | /usr/lib/libwayland-server.so.0(wl_display_run+0x2f) [0x7e9da6ff110f]
		??
		??:0
	#29 | Hyprland(_ZN17CEventLoopManager9enterLoopEv+0x2a9) [0x5b41c06ca359]
		CEventLoopManager::enterLoop()
		??:?
	#3 | Hyprland(main+0xc98) [0x5b41c0504768]
		main
		??:?
	#31 | /usr/lib/libc.so.6(+0x25e08) [0x7e9da6634e08]
		??
		??:0
	#32 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7e9da6634ecc]
		??
		??:0
	#33 | Hyprland(_start+0x25) [0x5b41c0542fc5]
		_start
		??:?

Log tail:
[LOG] [AQ] drm: Mode 13: 1440x900@59.90Hz
[LOG] [AQ] drm: Mode 14: 1366x768@59.79Hz
[LOG] [AQ] drm: Mode 15: 1280x800@59.91Hz
[LOG] [AQ] drm: Mode 16: 1152x864@75.00Hz
[LOG] [AQ] drm: Mode 17: 1280x720@60.00Hz
[LOG] [AQ] drm: Mode 18: 1280x720@60.00Hz
[LOG] [AQ] drm: Mode 19: 1280x720@59.94Hz
[LOG] [AQ] drm: Mode 20: 1280x720@50.00Hz
[LOG] [AQ] drm: Mode 21: 1024x768@75.03Hz
[LOG] [AQ] drm: Mode 22: 1024x768@70.07Hz
[LOG] [AQ] drm: Mode 23: 1024x768@60.00Hz
[LOG] [AQ] drm: Mode 24: 832x624@74.55Hz
[LOG] [AQ] drm: Mode 25: 800x600@75.00Hz
[LOG] [AQ] drm: Mode 26: 800x600@72.19Hz
[LOG] [AQ] drm: Mode 27: 800x600@60.32Hz
[LOG] [AQ] drm: Mode 28: 720x576@50.00Hz
[LOG] [AQ] drm: Mode 29: 720x480@60.00Hz
[LOG] [AQ] drm: Mode 30: 720x480@60.00Hz
[LOG] [AQ] drm: Mode 31: 720x480@59.94Hz
[LOG] [AQ] drm: Mode 32: 720x480@59.94Hz
[LOG] [AQ] drm: Mode 33: 640x480@75.00Hz
[LOG] [AQ] drm: Mode 34: 640x480@72.81Hz
[LOG] [AQ] drm: Mode 35: 640x480@66.67Hz
[LOG] [AQ] drm: Mode 36: 640x480@60.00Hz
[LOG] [AQ] drm: Mode 37: 640x480@59.94Hz
[LOG] [AQ] drm: Mode 38: 720x400@70.08Hz
[LOG] [AQ] drm: Physical size [Vector2D: x: 890, y: 500] (mm)
[LOG] [AQ] drm: Description Samsung Electric Company SyncMaster 0x00000001 (HDMI-A-1)
[LOG] New aquamarine output with name HDMI-A-1
[LOG] New output with name HDMI-A-1
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 364
[WARN] No rule found for HDMI-A-1, trying to use the first.
[WARN] No rules configured. Using the default hardcoded one.
[LOG] Applying monitor rule for HDMI-A-1
[LOG] Setting preferred mode for HDMI-A-1
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 1920, y: 1080] and format XR24 with modifier 72057594037927944 aka Y_TILED_GEN12_RC_CCS_CC
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 1920, y: 1080] and format XR24 with modifier 72057594037927944 aka Y_TILED_GEN12_RC_CCS_CC
[LOG] [AQ] Swapchain: Reconfigured a swapchain to [Vector2D: x: 1920, y: 1080] XR24 of length 2
[LOG] CMonitorState::ensureBufferPresent: no buffer, attaching one from the swapchain for modeset being possible
[ERR] [AQ] drm: No CRTC attached to output
[ERR] output HDMI-A-1 failed basic test on format DRM_FORMAT_XRGB8888
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 1920, y: 1080] and format XB24 with modifier 72057594037927944 aka Y_TILED_GEN12_RC_CCS_CC
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 1920, y: 1080] and format XB24 with modifier 72057594037927944 aka Y_TILED_GEN12_RC_CCS_CC
[LOG] [AQ] Swapchain: Reconfigured a swapchain to [Vector2D: x: 1920, y: 1080] XB24 of length 2
[ERR] [AQ] drm: No CRTC attached to output
[ERR] output HDMI-A-1 failed basic test on format DRM_FORMAT_XBGR8888
[ERR] [AQ] drm: No CRTC attached to output
[ERR] output HDMI-A-1 failed basic test on format DRM_FORMAT_INVALID
[ERR] [AQ] drm: No CRTC attached to output
[ERR] Couldn't commit output named HDMI-A-1
[LOG] Monitor HDMI-A-1 -> destroyed all render data
[LOG] arrangeMonitors: 2 to arrange
[LOG] arrangeMonitors: eDP-1 explicit [0, 0]
[LOG] arrangeMonitors: HDMI-A-1 auto [-1, -1]
[LOG] arrangeMonitors: eDP-1 xwayland [0, 0]
[LOG] arrangeMonitors: HDMI-A-1 xwayland [1920, 0]
[LOG] Monitor HDMI-A-1 data dump: res 1920x1080@60.00Hz, scale 1.00, transform 0, pos 1920x0, 10b 0
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 364
[LOG] [AQ] GBM: Automatically selected format AR24 for new GBM buffer
[LOG] [AQ] GBM: Buffer is marked as multigpu, forcing linear
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 256, y: 256] and format AR24 with modifier 0 aka LINEAR
[LOG] [AQ] GBM: Automatically selected format AR24 for new GBM buffer
[LOG] [AQ] GBM: Buffer is marked as multigpu, forcing linear
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 256, y: 256] and format AR24 with modifier 0 aka LINEAR
[LOG] [AQ] Swapchain: Reconfigured a swapchain to [Vector2D: x: 256, y: 256] AR24 of length 2
[LOG] Shaders initialized successfully.
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 314

**Comment by MightyPlaza** [comment]
try hyprland-git and aquamarine-git

**Comment by vaxerski** [comment]
ye thats fixed in git

**Comment by ValentinMATHIEU** [comment]
Thx for the tip.

I just switched, will see !
