### ISSUE TITLE
[ Feature ] Graceful exit/logout dispatcher

### ISSUE THREAD

**Issue by ArtemSmaznov** [hyprwm/Hyprland#7576]
### Description

I currently have this in my config:
```bind = SUPER CTRL , q , exit , # quit hyprland```
there are a number of use cases for this (e.g. switching to a different compositor/wm, testing an issue in xorg, testing hyprland startup, etc).

What I've noticed when using this is that hyprland seems to just forcefully kill all applications running under it. This is not an issue for things like a terminal, but for more complex applications, it doesn't allow them to do any shutdown tasks like saving session (e.g. qutebrowser, emacs), or saving recently accessed files (emacs) and possibly even some cache cleaning.

Initially I though that it was an issue with the actual tools, my most obvious example being having qutebrowser launch with tabs, that I have closed, being re-opened. I have tested it now and see that it always remembers the state of the tabs no matter if I exit it or send SIGTERM, so my assumption is that hyprland just sends SIGKILL to all the processes when the `exit` dispatcher is triggered. And that's understandable, as we don't want to soft-lock the system if some rogue process doesn't cooperate.

My suggestion is to add an integer argument to the `exit` dispatcher that will act as a timeout in seconds before killing the remaining processes (like is the case now), and hyprland would first try a more graceful termination. Value of 0 would mean current behaviour.

If my assumptions are way off or if I am missing some setup, please let me know.

Secondary note is that currently using the `exit` dispatcher doesn't actually log out the user properly.  My drives remain unencrypted even though I am on my login screen, which looks like I'm logged out. `systemctl logout` does actually encrypt my drives as expeted.

**Comment by Vladimir-csp** [comment]
You might want to use a [session manager](https://github.com/Vladimir-csp/uwsm) for such things. Among other things, will make systemd terminate things in proper order when deactivating compositor.

**Comment by Vladimir-csp** [comment]
As a side note, stopping compositor and logging out (ending a login session) are completely different things, but they can be bound together (uwsm does it). Plus, depending on user's linger status, terminating the last session might not mean terminating other user services. There is `loginctl terminate-user ""` for that.

**Comment by ArtemSmaznov** [comment]
Thanks for the info, I'll definitely check the session manager out, haven't used them before.

**Comment by ArtemSmaznov** [comment]
Lazy question, is uwsm a replacement for a login manager like sddm or it can be set to run alongside it?

I will research this myself more when I have some time but a quick read of the GitHub repo seems to suggest it is a replacement.

**Comment by Vladimir-csp** [comment]
> is uwsm a replacement for a login manager like sddm or it can be set to run alongside it

It can work alongside it, see [here](https://github.com/Vladimir-csp/uwsm#from-a-display-manager). Although some DMs might have trouble handling [quoting](https://specifications.freedesktop.org/desktop-entry-spec/latest/exec-variables.html) properly. In this case, use single-word arguments and file a bugreport DM.

**Comment by ArtemSmaznov** [comment]
Finally got some time to check uwsm out. Having issues launching it from sddm but seems to work when launched from tty.

Quick question: am I understanding this correctly - I need to replace all binding in hyprland config to launch apps `via uwsm app--`?

**Comment by Vladimir-csp** [comment]
Anything that makes sense to run as an "app". That is, a file manager, or a calculator - yes, but there is no need to bother with some one-shot script that tweaks volume.

**Comment by ArtemSmaznov** [comment]
Thanks for the info, I'll play with this some more over the coming weeks but think this issue is invalid in the context of hyprland then so I'm closing it.
