### ISSUE TITLE
Add rounding to grouped apps

### ISSUE THREAD

**Issue by cmihail** [hyprwm/Hyprland#7580]
### Description

Currently Hyprland allows adding rounding to applications inside `decorations`, e.g.:
```
decoration {
   rounding = 10
   ......
}
```

But this `rounding` does not apply to the [groupbar](https://wiki.hyprland.org/Configuring/Variables/#groupbar):
![20240830-130814](https://github.com/user-attachments/assets/9c767614-e210-474c-a553-5ebf75f53cb2)

It will be great to add a new `rounding` setting in `groupbar` with which to achieve a similar `rounding`/feel for both applications and the `groupbar`.

Note: I would like to implement this feature probably somewhere at the end of next month when I will have more time.

**Comment by vaxerski** [comment]
#2415
