### ISSUE TITLE
Hyprland Crashes due to failiure at binding to socket @/tmp/.X11-unix/X0

### ISSUE THREAD

**Issue by selselse** [hyprwm/Hyprland#7596]
Steps to reproduce the bug:
1.  Installation of the dotfiles https://github.com/end-4/dots-hyprland/tree/main
2. Start Hyprland from TTY

Description of the bug:
From the login screen I encounter the image shwon below:
![20240831_163159.jpg](https://github.com/user-attachments/assets/36ace359-91ac-4429-bebd-b502a631904b)

From TTY the core falls out:![20240831_161724.jpg](https://github.com/user-attachments/assets/d8787ff3-5d29-4645-b3e8-24a1ef913527)

Log files:
![20240831_162156.jpg](https://github.com/user-attachments/assets/4b3c575f-9522-434b-8578-85eed3d4499d)

![20240831_162142.jpg](https://github.com/user-attachments/assets/cc07d2e2-6bc6-4738-9440-e059d3ecbeef)

![20240831_162206.jpg](https://github.com/user-attachments/assets/37800202-949b-4fb3-b049-6e347539097b)

![20240831_162200.jpg](https://github.com/user-attachments/assets/dc285d92-faa9-4055-a4ec-6eb527653917)

I wasn't able to find anything related to this issue, your help would be appreciated!

**Comment by selselse** [comment]
Output of journalctl -xeu postgresql.service:

![20240831_164634.jpg](https://github.com/user-attachments/assets/37bedd79-0118-44b3-9a2d-349d8cfb5b2e)

![20240831_164647.jpg](https://github.com/user-attachments/assets/654c8b51-ea22-4d34-abb3-2ca400176f83)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/aquamarine/issues/70 likely

post a debug stacktrace there
