### ISSUE TITLE
disabled monitor does not turn off since 0.42.0

### ISSUE THREAD

**Issue by rowanG077** [hyprwm/Hyprland#7599]
### Regression?

Yes

### System Info and Version

<details> <summary>NixOs + asahi on hyprland 0.42</summary>

with as https://github.com/hyprwm/Hyprland/commit/279ec1c291021479b050c83a0435ac7076c1aee0 as seperate patch to make asahi work

```sh
λ hyprctl version
Hyprland, built from branch main at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: 2024-08-07
Tag: v0.42.0, commits: 9a09eac79b85c846e3a865a9078a3f8ff65a9259

flags: (if any)

```

</details>

### Description

I usually turn off my laptop display when I'm working on my external screen. This worked fine pre 0.42.0 but now the screen is removed from hyprland but the last frame is still displayed.  

### How to reproduce

Connect external monitor and run `hyprctl keyword monitor "eDP-1, disable"` to turn off internal monitor. The last frame will still be displayed instead of the monitor turning off.

**Comment by vaxerski** [comment]
can you try on aquamarine-git and hyprland-git?

**Comment by rowanG077** [comment]
I can compile aquamaring-git fine but hyprland-git fails with:

```
/build/source/src/debug/Log.cpp: In function 'void Debug::init(const std::string&)':
/build/source/src/debug/Log.cpp:13:26: error: 'std::ofstream' {aka 'class std::basic_ofstream<char>'} has no member named 'native_handle'
   13 |     auto handle = logOfs.native_handle();
      |    
```

**Comment by vaxerski** [comment]
you need gcc >= 14 or clang >= 18

**Comment by rowanG077** [comment]
I had gcc 14 but I had to manually add `-std=gnu++26` flag to the build system. I can confirm with https://github.com/hyprwm/aquamarine/pull/72 it is works as expected.

Thanks for the speedy fix.
