### ISSUE TITLE
Gnome App Draggable Header

### ISSUE THREAD

**Issue by jncsotk30** [hyprwm/Hyprland#7604]
### Description

I know the purpose of Hyprland is ultimately efficiency through keyboard navigation. I also know there's the hyprbars plugin for mouse click and drag functionality of windows. One thing I was hoping to maybe request is mouse click and drag recognition for gnome based apps which already have a header sort-of built in to them. 

I'd prefer to disable hyprbars on such apps with a gnome style header pre-existing so there's not a duplicate "titlebar" so to speak.

Sometimes, I'm not always using my laptop with two hands, and it'd be nice to fallback to mouse window movement via hyprbars titlebar / gnome header bars.

See picture for example.

![17:55:30-2024-08-31-area](https://github.com/user-attachments/assets/833c4ab3-e0dc-4c37-8697-d72d573ae142)

**Comment by vaxerski** [comment]
#1556

**Comment by vaxerski** [comment]
(btw, hyprbars can be dragged with just the mouse)

**Comment by vaxerski** [comment]
> I'd prefer to disable hyprbars on such apps with a gnome style header pre-existing so there's not a duplicate "titlebar" so to speak.

can't

**Comment by jncsotk30** [comment]
> (btw, hyprbars can be dragged with just the mouse)

Oh, yeah I'm aware. Not saying the problem is with hyprbars, just looking to click and drag on gnome app headers if possible. Thanks!

**Comment by jncsotk30** [comment]
> > I'd prefer to disable hyprbars on such apps with a gnome style header pre-existing so there's not a duplicate "titlebar" so to speak.
> 
> can't

I'll just do this manually via rules for the gnome apps I use. Thanks again!

**Comment by vaxerski** [comment]
yeah no other way afaik cuz we let all apps know we dont want csd and gnome just ignores it

**Comment by jncsotk30** [comment]
> yeah no other way afaik cuz we let all apps know we dont want csd and gnome just ignores it

Gotcha -- makes sense from your perspective. I'm betting gnome just forces them to display because they expect their apps to be run within their DE so the look and feel is consistent. They probably figure there's no need to disable CSD.

**Comment by khalid151** [comment]
@vaxerski What about sending events when a window requests to be moved? We already have that for minimize requests
https://github.com/hyprwm/Hyprland/blob/b1ab0f7539f81e646aab40855608514cf8fa5075/src/protocols/XDGShell.cpp#L213-L217


@jncsotk30 I made [a plugin](https://github.com/khalid151/csd-titlebar-move) to help with that, just make sure you'd disable hyprbars with a window rule.
