### ISSUE TITLE
Add the ability to set windowrules based on the command it was ran from.

### ISSUE THREAD

**Issue by tdljayden** [hyprwm/Hyprland#762]
I am currently working on a overlay-type menu that runs firefox (ran within a profile with no extra ui elements that come with a web browser) so I can see my calendar (proton calendar) by pressing a keybind. However, I am unable to set a windowrule for a specific window (or web page) for firefox. When I open htop or anything similar it allows me to see the original command it was ran with, arguments and all. But when I run hyprctl clients, there isn't any unique information for that window (apart from maybe the title which is dynamic based on what day/week it is). A possible fix for this is allowing exec to run commands with arguments to tell hyprland where to put the resulting window (I'm not sure if this is too complex for hyprland though).

Summary: The problem is I can set a windowrule for firefox, but it is global and I want to set it for a specific window.

**Comment by wuyoli** [comment]
I would need something similar: the ability to run a command and open the resulting window on a specific monitor.
I know, a possible solution was mentioned [here](https://github.com/hyprwm/Hyprland/wiki/FAQ#how-do-i-autostart-my-favorite-apps), but this feature would help me for the same reason as OP.
I would suggest to make this a optional argument for the exec dispatcher:
`exec <command> [<workspace>]`

**Comment by vaxerski** [comment]
I think something like
```
bind=SUPER,E,exec [ workspace 3;noblur;size 1280 720 ],kitty
```
would work nicely

**Comment by tdljayden** [comment]
> I think something like
> 
> ```
> bind=SUPER,E,exec [ workspace 3;noblur;size 1280 720 ],kitty
> ```
> 
> would work nicely
> 
> edit: actually, due to the backend, it'd be easier to make it
> 
> ```
> bind=SUPER,E,exec,[workspace 3;noblur] kitty
> ```
> 
> since `[...] blah blah` isn't valid bash anyways, this shouldn't be an issue

yeah this sounds like a good solution, kinda like how i3/sway does it

**Comment by vaxerski** [comment]
sorry for the long wait

added in 851df11eb595c5863bb931c32cbaa446c7071813
