### ISSUE TITLE
Can't launch Hyprland

### ISSUE THREAD

**Issue by YuvanMichael** [hyprwm/Hyprland#7620]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
                  .                       /\rch Linux | Linux 6.10.7-zen1-1-zen
                 / \                     >-----------<+>---------------------------------------------<
                /   \                       Uptime    | 17 mins
               /     \                      Shell     | bash 5.2.32
              /       \                     Terminal  | kitty 0.36.1
             />,       \                    Font      | CaskaydiaCoveNerdFontCompleteM-Regular (13pt)
            /  `*.      \                   Packages  | 1554 (pacman)
           /      `      \                  Local IP  | 192.168.1.5/24
          /               \              >-----------<+>---------------------------------------------<
         /                 \                Display   | 1366x768 @ 60 Hz in 12″ [Built-in]
        /      ,.-+-..      \               CPU       | Intel(R) Celeron(R)  N2840 (2) @ 2.58 GHz
       /      ,/'   `\.      \              GPU       | Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display @ 0.79 GHz []
      /      .|'     `|.   _  \             RAM       | 1.16 GiB / 1.81 GiB (64%)
     /       :|.     ,|;    `+.\            SWAP      | 664.25 MiB / 926.50 MiB (72%)
    /        .\:     ;/,      "<\           Disk      | 46.36 GiB / 456.39 GiB (10%) - ext4
   /     __,--+"     "+--.__     \          Battery   | 0% [Charging]
  /  _,+'"                 "'+._  \      >-----------<+>---------------------------------------------<
 /,-'                           `-.\
'                                   '                                           
                                                                                

~ 
> 
```

</details>

### Description

Just updated Hyprland yesterday, tried to launch Hyprland multiple times. Didn't work, reinstalled packages related to Hyprland and their up to date git versions. I used this command. "yay -S gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender pixman-git wayland-protocols-git cairo-git pango-git seatd libxkbcommon xcb-util-wm xorg-xwayland-git libinput libliftoff libdisplay-info cpio tomlplusplus hyprlang-git hyprcursor-git hyprwayland-scanner-git xcb-util-errors hyprutils-git hyprland-git aquamarine-git udis86-git" In the logs I don't get any information that I can understand. 

### How to reproduce

Build from the latest Hyprland-git using "yay -Syu --devel" and try to run Hyprland. 

### Crash reports, logs, images, videos

[hyprlandCrashReport535.txt](https://github.com/user-attachments/files/16831982/hyprlandCrashReport535.txt)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/aquamarine/issues/70

**Comment by YuvanMichael** [comment]
the issue still persists
