### ISSUE TITLE
Window Rules managed by plugins

### ISSUE THREAD

**Issue by dawsers** [hyprwm/Hyprland#7622]
### Description

Currently, window rules can only be defined in Hyprland, and there is no way for plugins to create their own.

`ConfigManager::handleWindowRuleV2(...)` first verifies whether a window rule is valid by calling `windowRuleValid(...)` ,which in turn checks the rule against the syntax of those window rules defined by Hyprland (stored in a list).

If a plugin wants to define a new rule that will be handled in `onWindowCreatedTiling()`, the rule will be rejected by the `ConfigManager`.

It would be great to have a mechanism for plugins to be able to register at least the name of rules they would be able to handle, so they are not filtered out with an error.

For example https://github.com/dawsers/hyprscroller/issues/45

I have implemented several rules that would be private to the plugin, like for example centering a window after adding it to the row, setting automatic marks depending on the window title, or changing to *row* or *column* mode depending on certain attributes of a window. In my case, those rules start with `scroller:`, like for example:

```
windowrulev2 = scroller:alignwindow center, class:(kitty)
```

The implementation works if I comment out rule validity checking in `ConfigManager.cpp:ConfigManager::handleWindowRuleV2()`, but of course that is not a good solution. Maybe we would need some way to register window rules in a similar way a plugin can register its own options.

Thank you.

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprland-plugins/commit/18daf37b7c4e6e51ca2bf8953ce4cff1c38ca725
