### ISSUE TITLE
Swallowed windows can't be moved

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#763]
It can be resized tho

**Comment by Dickby** [comment]
@KyleUltimate could you be a bit more specific?
How to reproduce? Works fine on my end!

**Comment by KyleUltimate** [comment]
Nope, it's still broken on latest commit.
First, I use foot in single terminal mode(`foot -s`)
Second, I opened a window correlation like this!(left is simply a swallowed mpv window)
![image](https://user-images.githubusercontent.com/68589851/193851241-68060a68-150b-4ee3-87a5-df5aa617a109.png)
Third, I try to use mouse bindings to "pickup" the mpv window, I failed

**Comment by vaxerski** [comment]
check with 719a5b4f0b2039a8cc7cbf3610ade82aaf26f190

**Comment by KyleUltimate** [comment]
It's now fixed!
