### ISSUE TITLE
Hyprland crashes and logouts back to SDDM on HDMI connect

### ISSUE THREAD

**Issue by artem110101** [hyprwm/Hyprland#7631]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.10.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000


GPU information: 
33:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev d1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======
```

</details>

### Description

Session logged out back to SDDM login screen

### How to reproduce

Fresh reboot and HDMI connect

### Crash reports, logs, images, videos

Sep 02 16:02:20 archlinux systemd-coredump[3261]: [🡕] Process 2487 (Hyprland) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 2487:
                                                  #0  0x000071fabb1b63f4 n/a (libc.so.6 + 0x963f4)
                                                  #1  0x000071fabb15d120 raise (libc.so.6 + 0x3d120)
                                                  #2  0x000071fabb1444c3 abort (libc.so.6 + 0x244c3)
                                                  #3  0x00005e1cb337df77 _Z25handleUnrecoverableSignali (Hyprland + 0x15bf77)
                                                  #4  0x000071fabb15d1d0 n/a (libc.so.6 + 0x3d1d0)
                                                  #5  0x000071fabbb471af n/a (libaquamarine.so.2 + 0x311af)
                                                  #6  0x00005e1cb34d5e78 _ZN15CPointerManager17setHWCursorBufferEN9Hyprutils6Memory14CSharedPointerINS_20SMonitorPointerStateEEENS2_IN10Aquamarine7IBufferEEE (Hyprland + 0x2b3e78)
                                                  #7  0x00005e1cb34d88d7 _ZN15CPointerManager21attemptHardwareCursorEN9Hyprutils6Memory14CSharedPointerINS_20SMonitorPointerStateEEE (Hyprland + 0x2b68d7)
                                                  #8  0x00005e1cb34d8f70 _ZN15CPointerManager19updateCursorBackendEv (Hyprland + 0x2b6f70)
                                                  #9  0x00005e1cb34d1712 _ZN15CPointerManager15setCursorBufferEN9Hyprutils6Memory14CSharedPointerIN10Aquamarine7IBufferEEERKNS0_4Math8Vector2DERKf (Hyprland + 0x2af712)
                                                  #10 0x00005e1cb34af9fe _ZN14CCursorManager15setCursorBufferEN9Hyprutils6Memory14CSharedPointerI13CCursorBufferEERKNS0_4Math8Vector2DERKf (Hyprland + 0x28d9fe)
                                                  #11 0x00005e1cb34b1843 _ZN14CCursorManager17setCursorFromNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (Hyprland + 0x28f843)
                                                  #12 0x00005e1cb34b2799 _ZN14CCursorManager11updateThemeEv (Hyprland + 0x290799)
                                                  #13 0x00005e1cb34b295c n/a (Hyprland + 0x29095c)
                                                  #14 0x00005e1cb34b5acf _ZN18CHookSystemManager4emitEPSt6vectorI14SCallbackFNPtrSaIS1_EER13SCallbackInfoSt3any (Hyprland + 0x293acf)
                                                  #15 0x00005e1cb3668b99 _ZN13CHyprRenderer16applyMonitorRuleEP8CMonitorP12SMonitorRuleb (Hyprland + 0x446b99)
                                                  #16 0x00005e1cb347b6a1 _ZN8CMonitor9onConnectEb (Hyprland + 0x2596a1)
                                                  #17 0x00005e1cb33a00c9 _ZN11CCompositor12onNewMonitorEN9Hyprutils6Memory14CSharedPointerIN10Aquamarine7IOutputEEE (Hyprland + 0x17e0c9)
                                                  #18 0x00005e1cb33a8c06 n/a (Hyprland + 0x186c06)
                                                  #19 0x000071fabb6e5dc6 _ZN9Hyprutils6Signal21CStaticSignalListener4emitESt3any (libhyprutils.so.1 + 0x8dc6)
                                                  #20 0x000071fabb6e63be _ZN9Hyprutils6Signal7CSignal4emitESt3any (libhyprutils.so.1 + 0x93be)
                                                  #21 0x000071fabbbb9cbd _ZN10Aquamarine13SDRMConnector7connectEP17_drmModeConnector (libaquamarine.so.2 + 0xa3cbd)
                                                  #22 0x000071fabbbb4500 _ZN10Aquamarine11CDRMBackend14scanConnectorsEv (libaquamarine.so.2 + 0x9e500)
                                                  #23 0x000071fabbbbf6f4 n/a (libaquamarine.so.2 + 0xa96f4)
                                                  #24 0x000071fabb6e5c9f _ZN9Hyprutils6Signal15CSignalListener4emitESt3any (libhyprutils.so.1 + 0x8c9f)
                                                  #25 0x000071fabb6e600e _ZN9Hyprutils6Signal7CSignal4emitESt3any (libhyprutils.so.1 + 0x900e)
                                                  #26 0x000071fabbb8d9b1 _ZN10Aquamarine8CSession18dispatchUdevEventsEv (libaquamarine.so.2 + 0x779b1)
                                                  #27 0x00005e1cb34ff11a n/a (Hyprland + 0x2dd11a)
                                                  #28 0x000071fabbac40a2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xa0a2)
                                                  #29 0x000071fabbac610f wl_display_run (libwayland-server.so.0 + 0xc10f)
                                                  #30 0x00005e1cb3501359 _ZN17CEventLoopManager9enterLoopEv (Hyprland + 0x2df359)
                                                  #31 0x00005e1cb333b768 main (Hyprland + 0x119768)
                                                  #32 0x000071fabb145e08 n/a (libc.so.6 + 0x25e08)
                                                  #33 0x000071fabb145ecc __libc_start_main (libc.so.6 + 0x25ecc)
                                                  #34 0x00005e1cb3379fc5 _start (Hyprland + 0x157fc5)
                                                  
                                                  Stack trace of thread 2562:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2559:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2544:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2547:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2549:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2535:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fabb4d6cf1 __gthread_cond_wait (libstdc++.so.6 + 0xd6cf1)
                                                  #3  0x00005e1cb348a070 n/a (Hyprland + 0x268070)
                                                  #4  0x000071fabb4e1cf4 execute_native_thread_routine (libstdc++.so.6 + 0xe1cf4)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2546:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2561:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2555:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2545:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2556:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2560:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2563:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2548:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2557:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2570:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2873:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2566:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2569:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2871:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2567:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2568:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2564:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2565:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2872:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  
                                                  Stack trace of thread 2870:
                                                  #0  0x000071fabb1b0a19 n/a (libc.so.6 + 0x90a19)
                                                  #1  0x000071fabb1b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                  #2  0x000071fab80a5cae n/a (libgallium-24.2.1-arch1.1.so + 0xa5cae)
                                                  #3  0x000071fab80826cc n/a (libgallium-24.2.1-arch1.1.so + 0x826cc)
                                                  #4  0x000071fab80a5bdd n/a (libgallium-24.2.1-arch1.1.so + 0xa5bdd)
                                                  #5  0x000071fabb1b439d n/a (libc.so.6 + 0x9439d)
                                                  #6  0x000071fabb23949c n/a (libc.so.6 + 0x11949c)
                                                  ELF object binary architecture: AMD x86-64

**Comment by artem110101** [comment]
```
monitor = eDP-1,preferred, auto, 1
monitor = HDMI-A-1,preferred, 0x0, 1
```

**Comment by vaxerski** [comment]
fixed in git
