### ISSUE TITLE
Hyprland crashes

### ISSUE THREAD

**Issue by YuvanMichael** [hyprwm/Hyprland#7636]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
                  .                       /\rch Linux | Linux 6.10.7-zen1-1-zen
                 / \                     >-----------<+>---------------------------------------------<
                /   \                       Uptime    | 13 mins
               /     \                      Shell     | bash 5.2.32
              /       \                     Terminal  | kitty 0.36.1
             />,       \                    Font      | CaskaydiaCoveNerdFontCompleteM-Regular (13pt)
            /  `*.      \                   Packages  | 1549 (pacman)
           /      `      \                  Local IP  | 192.168.1.3/24
          /               \              >-----------<+>---------------------------------------------<
         /                 \                Display   | 1366x768 @ 60 Hz in 19″ [External]
        /      ,.-+-..      \               CPU       | Intel(R) Core(TM) i5-3470 (4) @ 3.60 GHz
       /      ,/'   `\.      \              GPU       | Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller @ 1.10 G]
      /      .|'     `|.   _  \             RAM       | 1.91 GiB / 3.74 GiB (51%)
     /       :|.     ,|;    `+.\            SWAP      | 0 B / 1.87 GiB (0%)
    /        .\:     ;/,      "<\           Disk      | 41.44 GiB / 456.39 GiB (9%) - ext4
   /     __,--+"     "+--.__     \       >-----------<+>---------------------------------------------<
  /  _,+'"                 "'+._  \
 /,-'                           `-.\                                            
'                                   '                                           

~ 
> 


```

</details>

### Description

issue #7620  still persists.  And please don't just refer to another issue and close this. 

### How to reproduce

Use yay -Syu --devel. 

### Crash reports, logs, images, videos

[hyprlandCrashReport535.txt](https://github.com/user-attachments/files/16844437/hyprlandCrashReport535.txt)
[hyprlandCrashReport542.txt](https://github.com/user-attachments/files/16844438/hyprlandCrashReport542.txt)
[hyprlandCrashReport543.txt](https://github.com/user-attachments/files/16844439/hyprlandCrashReport543.txt)
[hyprlandCrashReport559.txt](https://github.com/user-attachments/files/16844440/hyprlandCrashReport559.txt)
[hyprlandCrashReport693.txt](https://github.com/user-attachments/files/16844441/hyprlandCrashReport693.txt)
[hyprlandCrashReport1483.txt](https://github.com/user-attachments/files/16844442/hyprlandCrashReport1483.txt)
[hyprlandCrashReport1591.txt](https://github.com/user-attachments/files/16844443/hyprlandCrashReport1591.txt)

**Comment by YuvanMichael** [comment]
This has never happened before. Should I migrate to hyprland Arch repo instead of git?

**Comment by YuvanMichael** [comment]
~ 
> yay -Syu --needed --devel aquamarine-git aquamarine-git-debug hyprland-git hyprland-git-debug
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
error: failed retrieving file 'core.db' from mirror.osbeck.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'extra.db' from mirror.osbeck.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
 -> aquamarine-git-0.4.0_r212.gaac97a1-1 is up to date -- skipping
 -> No AUR package found for aquamarine-git-debug
 -> hyprland-git-0.42.0.r112.8f9887b0-1 is up to date -- skipping
 -> No AUR package found for hyprland-git-debug
:: Searching AUR for updates...
:: Checking development packages...
 -> devel check for package failed: '/usr/bin/git ls-remote https://github.com/hyprwm/hyprlang.git HEAD' encountered an error: signal: killed
 -> devel check for package failed: '/usr/bin/git ls-remote https://gitlab.gnome.org/GNOME/pango.git HEAD' encountered an error: signal: killed
 -> devel check for package failed: '/usr/bin/git ls-remote https://github.com/sardemff7/libnkutils.git HEAD' encountered an error: signal: killed
 -> devel check for package failed: '/usr/bin/git ls-remote https://github.com/hyprwm/contrib.git HEAD' encountered an error: signal: killed
:: Searching databases for updates...
 there is nothing to do

~ took 2m22s 
>

**Comment by YuvanMichael** [comment]
I had downgraded and everything works fine. What went wrong with git?

**Comment by YuvanMichael** [comment]
No debug packages are available but in missing-debug-packages I get all of them when I downgrade. I can uninstall but not install?

**Comment by Aqa-Ib** [comment]
It is working fine on my side. You can bisect though.

**Comment by Aqa-Ib** [comment]
If I were in your situation, I would try first installing hyprland-git and downgrading only aquamarine to see if the regression is in aquamarine.

**Comment by Honkazel** [comment]
https://github.com/hyprwm/Hyprland/issues/7625#issuecomment-2325768381
@YuvanMichael

**Comment by YuvanMichael** [comment]
Thank you, @Aqa-Ib and @Honkazel for your advice. I shall try "Remove and install" instead of reinstalling aquamarine and rebuild Hyprland. First thing tomorrow.

**Comment by Honkazel** [comment]
> @Honkazel is it needed to compile aquamarine before compiling hyprland ? does the order matter ?

Right. Order does matter

**Comment by Aqa-Ib** [comment]
Can you explain why please ? 
If one tries to bisect aquamarine is it needed to recompile hyprland everytime the aquamarine version is changed ?

**Comment by YuvanMichael** [comment]
Um, still doesn't work

**Comment by YuvanMichael** [comment]
[issue.txt](https://github.com/user-attachments/files/16861872/issue.txt)
[issue2.txt](https://github.com/user-attachments/files/16861873/issue2.txt)

**Comment by YuvanMichael** [comment]
Even after reinstalling the latest aquamarine and rebuilding Hyprland, it still doesn't work

**Comment by YuvanMichael** [comment]
If I'm doing anything wrong please let me know

**Comment by YuvanMichael** [comment]
hyprwm/aquamarine#74

**Comment by Honkazel** [comment]
I read txt files and it seems like it did build hyprland-git before aquamarine
Install aquamarine from arch repos(0.4.0) and then recompile hyprland-git

**Comment by YuvanMichael** [comment]
Even the stable version from Arch repos doesn't work now. Chaotic AUR won't help me downgrade.

**Comment by YuvanMichael** [comment]
Will try again on recompiling hyprland git and aquamarine from arch

**Comment by YuvanMichael** [comment]
> I read txt files and it seems like it did build hyprland-git before aquamarine Install aquamarine from arch repos(0.4.0) and then recompile hyprland-git

I don't really think so, Pretty sure it did aquamarine and then hyprland.

**Comment by YuvanMichael** [comment]
Um, hyprland-git requires aquamarine-git as dependency. Nukes the purpose of aquamarine from arch?

**Comment by Honkazel** [comment]
Then idk. I'm just compile hypr packages(hyprwayland-scanner, hyprutils, aquamarine and then hyprland) by myself(trying to less use AUR and chaotic AUR repo too) and don't have those issues.

**Comment by YuvanMichael** [comment]
Yeah, I used to do that too. Will try your method with help from the wiki

**Comment by YuvanMichael** [comment]
I made this script which worked before on a fresh reinstall of Arch I did a while ago, Trying this again. Hopefully it works.

**Comment by YuvanMichael** [comment]
EDIT, compiling from the git worked.

**Comment by YuvanMichael** [comment]
I used this, 

<details> 

```sh
#!/usr/bin/env bash
yay -S --needed gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols-git cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland-git libinput libliftoff libdisplay-info cpio tomlplusplus hyprlang-git hyprcursor-git hyprwayland-scanner-git xcb-util-errors hyprutils-git
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
make all && sudo make install
```

</details>

**Comment by YuvanMichael** [comment]
```sh 
~ 
> hyprctl systeminfo
Hyprland, built from branch main at commit 9b54342baa27d8de0460e1103ec4c3cc65592ed8  (Revert syncobj: wait for deadline instead of available).
Date: Tue Sep 3 18:17:34 2024
Tag: v0.42.0-113-g9b54342b, commits: 5182

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.10.7-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:33 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller [8086:0152] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprexpo by Vaxry ver 1.0
  hyprtrails by Vaxry ver 1.0


~ 
>

**Comment by Honkazel** [comment]
That's newest version of Hyprland for now
And maybe `ls /usr/lib | grep aquamarine`?
Or `/usr/local/lib`

**Comment by YuvanMichael** [comment]
```sh
> ls /usr/lib | grep aquamarine
libaquamarine.so -> libaquamarine.so.3
libaquamarine.so.0.4.0
libaquamarine.so.3 -> libaquamarine.so.0.4.0

**Comment by Honkazel** [comment]
> ```shell
> > ls /usr/lib | grep aquamarine
> libaquamarine.so -> libaquamarine.so.3
> libaquamarine.so.0.4.0
> libaquamarine.so.3 -> libaquamarine.so.0.4.0
> ```

I guess now you can close issue?

**Comment by YuvanMichael** [comment]
If possible, could you try the aur version of this git? If you can reproduce this issue, then I would be happy if you guys can notify the AUR package maintainers.

**Comment by Aqa-Ib** [comment]
I can't reproduce with the AUR package.

**Comment by YuvanMichael** [comment]
then what went wrong with mine?

**Comment by YuvanMichael** [comment]
well, since it isn't able to be replicated, I guess I can close it now, As long as mine's fixed.

**Comment by YuvanMichael** [comment]
Although in a not so preferred way of doing it manually instead of yay

**Comment by YuvanMichael** [comment]
Just checked and upgraded to AUR hyprland-git, Everything works fine now, Probably was just a bad commit.
