### ISSUE TITLE
source tar for 0.13 and 0.14 have wrong versions in them

### ISSUE THREAD

**Issue by Aiffelowy** [hyprwm/Hyprland#764]
Both source-v0.14.0beta.tar.gz and source-v0.13.1beta.tar.gz in Release tab are version 0.12.1beta. (which is screwing with gentoo ebuilds too)

Steps to reproduce:
1. download either source-v0.14.0beta.tar.gz or source-v0.13.1beta.tar.gz from Release tab
2. extract the tar
3. check the version in meson.build

Expected outcome:
the version should say 0.14.0beta or 0.13.1beta

Noted outcome:
version is actually 0.12.1beta

**Comment by vaxerski** [comment]
the version is meson.build is rarely bumped, and it's done manually. You should stick to using `hyprctl version` for versioning. The tarballs are generated automatically so there is no possibility that they are the wrong source.
