### ISSUE TITLE
Drag and drop does not work in Hyprland (Wayland)

### ISSUE THREAD

**Issue by kuberpunk666** [hyprwm/Hyprland#7644]
### Regression?

Yes

### System Info and Version

Hyprland, built from branch main at commit 9b54342baa27d8de0460e1103ec4c3cc65592ed8  (Revert syncobj: wait for deadline instead of available).
Date: Tue Sep 3 09:47:34 2024
Tag: v0.42.0-113-g9b54342b, commits: 5182

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.10.7-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:33 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

### Description

I was waiting to make sure I reported it here, that is, I've had this bug for a month and a half. In this case, until the middle to the end of July I was able to drag and drop files, etc. into my hyprland, however, at the end of July and beginning of August, the drag and drop function simply stopped working. The first time I noticed this bug was in GIMP, and no, it's not a GIMP problem. I went to drag and drop an image, as usual, but it wouldn't open the image. Even though I use Firefox, after a few weeks I noticed that other browsers weren't working with the drag and drop function either, such as Vivaldi, YandexBrowser and Brave. In other words, none of them work with the drag and drop function anymore. This last week, I went back to BSPWM (x11) and everything is working perfectly with browsers and GIMP, that is, it is not a problem with these applications. My intention is just to report so that you know that, in fact, this problem exists, as I haven't seen anyone talking about it, at least not recently.

### How to reproduce

Open Vivaldi, Yandex, Brave or GIMP and drag a local image into these applications.

### Crash reports, logs, images, videos

https://jmp.sh/D7dPrWLF

**Comment by pulsar256** [comment]
dragging selected text seems to swallow the mouse-up event on vivaldi as well. (wayland mode)

**Comment by vaxerski** [comment]
thats a chromium bug fixed in hl-git

**Comment by jordicunillerarivera** [comment]
For me, if I try to drag and drop an item to the scene in Unreal Engine, it simply insta stop draging, i need to do it fast as hell to it register properlly, and the folder explorer bugs hard when you drag and drop a folder or archive into the terminal.

**Comment by dkumza** [comment]
i cannot drag and drop in Nautilus too

**Comment by CommanderT3706** [comment]
I cannot drag and drop in Kdenlive either, using Nixos instead of Arch though

**Comment by SteavenGamerYT** [comment]
please fix this, this is #1 issue why i use sway

**Comment by kaixenberg** [comment]
Yeah I updated to the latest git:
```
Hyprland 0.44.0 built from branch main at commit f309681d4a78d1c12d8a04fe37075a50a750c2ec  (example: update desktop file to include DesktopNames).
Date: Mon Oct 14 20:56:07 2024
Tag: v0.44.0-42-gf309681d, commits: 5341
built against aquamarine 0.4.2


flags set:
debug
```
And drag on drop doesn't work on brave and gimp but works on telegram

**Comment by m2neral** [comment]
can drop from thunar to kitty but can't to mpv brave vesktop etc.

**Comment by Ghoul072** [comment]
works from thunar to firefox but not to vesktop, or discord. works seamlessly between most apps. probably an issue with xwayland integration

**Comment by ronasimi** [comment]
I'm not sure if I have the same issue, I am unable to copy/paste within GIMP, under xwayland.  I am using wl-clip-persist and clipboard-sync

**Comment by mrepol742** [comment]
With 1.1K active issues, I don’t think this will be the highest priority among them... im having a hard time tryna find out how to drag and drop crx extensions...

**Comment by mmBesar** [comment]
Drag and drop from Wayland to Xwayland works just fine under GNOME, but it's broken under Hyprland!
I wonder what did GNOME did to fix this issue!

**Comment by 0xl30** [comment]
I'm facing same problem with genymotion.
Does anyone have a solution for this?

**Comment by vaxerski** [comment]
fixed with #8708

**Comment by mmBesar** [comment]
Which version will get this fix?

**Comment by vaxerski** [comment]
0.46.0

**Comment by AyushmanOfficial** [comment]
I still have it even if i am on 0.46.2 should i create a new issue?

**Comment by vaxerski** [comment]
what are you dnd-ing from and to?

**Comment by laodc** [comment]
Just want to note, i am still having this issue with 0.46.3.

Attempting to drag a file from Thunar to VSCode.

If i attempt this as a normal user would (speed wise), the DnD will not function.

BUT

If you DnD at a slow pace, the feature works as intended.

**Comment by AyushmanOfficial** [comment]
> what are you dnd-ing from and to?

Sorry for the late reply, Uhh actually from nautilus to vscode...

**Comment by vaxerski** [comment]
> Just want to note, i am still having this issue with 0.46.3.

are you from an alternate universe? 
![image](https://github.com/user-attachments/assets/4e304a9d-4860-44b1-89bc-94c8a4044528)

> Uhh actually from nautilus to thorium...

which ones run in xwayland (if any)?

**Comment by laodc** [comment]
sorry, is .2 did a typo.

**Comment by edmondburnett** [comment]
Seeing this in 0.48.1. For example 

- Dragging a Firefox tab onto a desktop containing VLC. 
- Dragging any dock area in OBS Studio (without necessarily leaving the window)

**Comment by nguyentran0212** [comment]
Similar problem on the latest version of Hyprland on Arch. For example

- Dragging an image from dolphin or Firefox to Obsidian or OnlyOffice, both applications stop receiving click input (but I can still interact with them using keyboard and they still run).
- Dragging a PDF from dolphin to JabRef, both applications stop receiving click input.

Neither of these problem exist on KDE Plasma with the same set of applications.

**Comment by thetrung** [comment]
Same problem for `Hyprland 0.52.1` on `Omarchy 3.1.7`

**Comment by justinkozak** [comment]
Same issue exists dragging images to browser windows, or media files into VLC using Wayland on `Hyprland 0.53.0` with `6.18.3-2-cachyos`

Pretty big usability issue I think.

**Comment by tram98** [comment]
> Same issue exists dragging images to browser windows, or media files into VLC using Wayland on `Hyprland 0.53.0` with `6.18.3-2-cachyos`
> 
> Pretty big usability issue I think.

Same issue on vanilla arch with hyprland and vlc when dragging from nautilus.
