### ISSUE TITLE
GTK apps loading very slowly despite applying fixes.

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#765]
Since some time ago (probably like a week), I have been experiencing all GTK apps to load really slowly. Infact, I am using brave to submit this because firefox is loading too slow. I have also seen someone else in the discord server claiming they are experiencing the same issue. Also, the issue does not occur in other WM's, DE's and WC's (wayland compositors). I have also checked if it could have to do with the fcgu repo I've been playing around with, but even when removing all of the packages from it, I still have very long loading times. We are talking half a minute here.

I have applied all fixes referring to GTK apps on the FAQ.

**Comment by vaxerski** [comment]
Hyprland has nothing to do with your xdg_desktop_portal timing out. Issue on your system's side. if the instructions in the wiki do not work, check stuff like the journal or dmesg for potential issues with your system.

**Comment by EysseW** [comment]
Why don't these issue occur on other environment then?

**Comment by vaxerski** [comment]
no clue. Nobody apart from you has such an issue.

**Comment by EysseW** [comment]
Someone in the discord server pointed claimed to have the same issue.
![image](https://user-images.githubusercontent.com/80292589/193451192-dce8df10-b784-4800-8c6b-18d811e6889b.png)

**Comment by vaxerski** [comment]
check your xdg_desktop_portal.

**Comment by EysseW** [comment]
I am sorry. What exactly do you mean I should do? I don't know much about xdg stuff.

**Comment by vaxerski** [comment]
its logs should tell you what's wrong. either that or the app's that launches 30 secs

**Comment by EysseW** [comment]
Thanks! I'll look into it.
