### ISSUE TITLE
Memory Leak on LockScreen

### ISSUE THREAD

**Issue by CatWithCode** [hyprwm/Hyprland#7653]
### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch openSUSE at commit 0000000000000000000000000000000000000000  (Built for x86_64-suse-linux).
Date: Thu Jan 01 00:00:00 1970
Tag: 0.42.0, commits: -1

flags: (if any)


System Information:
System name: Linux
Node name: username
Release: 6.10.7-1-default
Version: #1 SMP PREEMPT_DYNAMIC Fri Aug 30 04:50:21 UTC 2024 (54e6893)


GPU information: 
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev cc) (prog-if 00 [VGA controller])


os-release: NAME="openSUSE Tumbleweed"
# VERSION="20240902"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240902"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240902:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240902"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

config: https://github.com/CatWithCode/HyprLainDotFiles

</details>

### Description

Hyprland starts to memory leak when it locks the screen, turns off.

In about 30 seconds, the memory leak increases by 10MB. The more often you lock the screen, the more extreme the leak becomes. It happens with swaylock and hyprlock. The maximum I was able to record was around 15GB of memory usage of Hyprland.

`hyprctl dispatch dpms off & hyprlock; hyprctl dispatch dpms on`

The command makes that the screens get turned off, screen gets locked and as soon as you unlock the dekstop screens turn on.

### How to reproduce

Use the Command to lock the Screen. Wait around 30 seconds, type your password and hit enter. Memory usage of hyprland will be around 10 mb bigger and never gets cleard. Around 10gb the desktop gets slow.

**Comment by vaxerski** [comment]
IIRC fixed in git.
