### ISSUE TITLE
hyprland crashes when using hyprspace

### ISSUE THREAD

**Issue by Postboote1** [hyprwm/Hyprland#7663]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 76b82fdde7d3f38cb70db0bec3318a7fb6c27a0c  ().
Date: 2024-08-31
Tag: , commits: 76b82fdde7d3f38cb70db0bec3318a7fb6c27a0c

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.10.6
Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:05:40 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])
00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Sunrise Point-LP Integrated Sensor Hub [8086:9d35] (rev 21)


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240828.71e91c4"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  hyprgrass by horriblename ver 0.7
  Hyprspace by KZdkm ver 0.1
```

</details>

### Description

Hello
So i recently installed hyprspace as a plugin. But the problem is, that everytime i want to drag a window from one workspace to the other ( in the workspace overview) hyprland crashes.
it crashes without a Crash Report but with following message:
`Error reading events from display: Broken pipeE_STATE_UNKNOWN -> GESTURE_EVENT_POINTER_MOTION -> GESTURE_STATE_POINTER_MOTIONEA = 2024-08-25_b328501/lib/libHyprspace.so`

I already opend an issue on the hyprspace github, but the only thing we know is that in 0.42.0 it worked fine.

### How to reproduce

install hyprlands newest version
Install hyprspace plugin
open overview and drag any window in another workspace

### Crash reports, logs, images, videos

`Error reading events from display: Broken pipeE_STATE_UNKNOWN -> GESTURE_EVENT_POINTER_MOTION -> GESTURE_STATE_POINTER_MOTIONEA = 2024-08-25_b328501/lib/libHyprspace.so`

**Comment by vaxerski** [comment]
well then its aproblem with the plugin not hyprland

**Comment by Postboote1** [comment]
Yeah but the version befor it worked and suddenly it doesen't

**Comment by vaxerski** [comment]
plugins need to chase hyprland changes

**Comment by Postboote1** [comment]
already wrote a bug report on the hyprspcae github page.
But there the developer replied with : "Cant reproduce on 0.42 either. Git changes are not tracked and might break the plugin, I recommend you to use tagged 0.42 version if there are no substantial reason for you to stay on git."
But i need to use hyprland from git because i am on Nixos. Without it gets very difficult with Submodules/Plugins
