### ISSUE TITLE
Comma seperated settings do not function as the user would expect

### ISSUE THREAD

**Issue by BrodieRobertson** [hyprwm/Hyprland#767]
**Steps to reproduce**
When setting a variable you can freely use a space to seperate the variable and value
`layout=dwindle` is valid
`layout = dwindle` is also valid

The same is not true for things like bindings and animations
`bind = SUPER,F,fullscreen` is valid

`bind = SUPER, F, fullscreen` is not as the spaces after the comma are treated as part of the function name

**Expected outcome**
Spaces to work like the user would expect from a comma seperated syntax

**Comment by vaxerski** [comment]
Not a bug, but I agree. I've been planning on unifying arg passing on the backend for a while.

**Comment by vaxerski** [comment]
done in 0a08830375bb3a206e1b966a11bf069edea8b780
