### ISSUE TITLE
a command to be executed during shutdown

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#7671]
### Description

like a command that executes before anything start to shutdown.

use cases of this can be for sth like: https://github.com/hyprwm/Hyprland/issues/2475#issuecomment-2333359383
or stuff like writing script to see if system is updating and cancel the shutdown if it is

**Comment by Aqa-Ib** [comment]
You can script this with a systemd unit targetting shutdown.target

Not a hyprland issue imo.

**Comment by littleblack111** [comment]
ik. i mean this isnt really a issue... its a feature request

but if i do before shutdown.target
it would be like display manger closed, pipwire and everything.

thus stuff like https://github.com/hyprwm/Hyprland/issues/2475#issuecomment-2333359383 won't be achivable

**Comment by Aqa-Ib** [comment]
Still a systemd thing. You need a hyprland.service started by systemd and a script.service that triggers `After=hyprland.service`

**Comment by littleblack111** [comment]
uncertain wdym by a hyprland.service. but if its a service that runs along hyprland or starts hyprland. then i'm pretty sure After=hyprland will make it start after hyprland start instead of when hyprland is shutting down. but even if it runs after hyprland shuts. still wont be able to do stuff like https://github.com/hyprwm/Hyprland/issues/2475#issuecomment-2333359383 cuz
> it would be like display manger closed, pipwire and everything.

**Comment by Aqa-Ib** [comment]
True my bad, it is not After. You can use `ExecStopPost` probably in the systemd unit. You have to play with systemd to achieve this.

**Comment by littleblack111** [comment]
I see.. May I know wdym by hyprland.service though? like replace display manager and just start hyprland?

**Comment by Aqa-Ib** [comment]
Yes

**Comment by littleblack111** [comment]
Actually, that sounds like a good idea. since my display manager config is just autologin... ill have a try

**Comment by littleblack111** [comment]
nope. doesnt work. i'm pretty sure theres a service that sets xdg_runtime_dir. suggested by https://www.reddit.com/r/archlinux/comments/167v652/hyprland_refusing_to_start_says_xdg_runtime_dir/ its a pam_systemd probelm. which idk what the service is. thus this wont work...

**Comment by Aqa-Ib** [comment]
what problem do you face? Why are you looking for that service? Create a new systemd service to start Hyprland from the tty or automatic at boot time, whatever you want, and then use systemd flags in the service file to achieve what you want.

**Comment by littleblack111** [comment]
please read the link provided. i am experiencing that issue. and if the env is not set. my runtime is prob not mounted as well... so hyprland will prob fail

**Comment by Aqa-Ib** [comment]
I am pretty sure that you can achieve it someway or another. User and group should be your user's in the service file. also, the After field is not good probably, because sddm has other needs different than hyprland. I havent use systemd to start hyprland before, but I would try login with my user in the tty and starting the service manually from it to see whats going on.

**Comment by littleblack111** [comment]
starting it manually worrd work

wdym  by the user and ggroup should be in my users service file? like ~/.config/systemd?

**Comment by Aqa-Ib** [comment]
User=youruser
Group=youruser

Also look at After= , because you just need your user to login first and after trigger it automatically. You can achieve it. Look https://wiki.archlinux.org/title/Getty#Virtual_console

**Comment by Vladimir-csp** [comment]
Ordering is reversed on deactivation. Setting `After=unit1.service` in `unit2.service` will delay deactivation of `unit1.service` until `unit2.service` is deactivated

Also, check [this](https://github.com/Vladimir-csp/uwsm) out.

**Comment by littleblack111** [comment]
cool repo!

**Comment by littleblack111** [comment]
yes. thats Y i'm filing this feature request. hope some maintainer sees this :D

**Comment by Aqa-Ib** [comment]
> > ik i can do that. but i dont wanna login. i want it to be automaticlly on. dont worry about security cuz they would need to unlock the LUKS via password first in order to unlock the disk

Look at the archwiki link I provided to you. Learn your init system to achieve what you want. You can ask on hyprland's discord too. Good luck.

**Comment by littleblack111** [comment]
i see you can auto login. but i think
> On the topic though, exec-shutdown might be handy anyway.
as well

**Comment by Aqa-Ib** [comment]
You can set up the hyprland service after the autologin service running as your user. That should work fine.

**Comment by Trimutex** [comment]
@littleblack111 Try #7683

**Comment by littleblack111** [comment]
> @littleblack111 Try #7683  

Ty for making it! I'll try later when I get on my computer

**Comment by vaxerski** [comment]
closing per #7683
