### ISSUE TITLE
Hyprland-git failed to install  Could not resolve all dependencies.

### ISSUE THREAD

**Issue by AkariH** [hyprwm/Hyprland#7691]
### Regression?

No

### System Info and Version

<details> <summary>
❯ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo</summary>

```sh
could not install hyprrland-git
```

</details>

### Description

==> Leaving fakeroot environment.
==> Finished making: aquamarine-git 0.4.1_r215.ge4a1320-1 (Sun 08 Sep 2024 09:36:29 AM CST)
==> Cleaning up...
loading packages...
resolving dependencies...
looking for conflicting packages...
:: hyprcursor-git-0.1.9.r11.g912d5602-1 and hyprcursor-0.1.9-1 are in conflict. Remove hyprcursor? [y/N] y
Packages (5) hyprcursor-0.1.9-1 [removal]  aquamarine-git-0.4.1_r215.ge4a1320-1  aquamarine-git-debug-0.4.1_r215.ge4a1320-1
hyprcursor-git-0.1.9.r11.g912d5602-1  hyprcursor-git-debug-0.1.9.r11.g912d5602-1
Total Installed Size:  21.90 MiB
Net Upgrade Size:
21.28 MiB
:: Proceed with installation? [Y/n] y
(4/4) checking keys in keyring
[###################################################] 100%(4/4) checking package integrity
[###################################################] 100%(4/4) loading package files
[###################################################] 100%(4/4) checking for file conflicts
[###################################################] 100%error: failed to commit transaction (conflicting files)
aquamarine-git: /usr/include/aquamarine/allocator/Allocator.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/allocator/GBM.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/allocator/Swapchain.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Backend.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/DRM.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Headless.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Misc.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Session.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Wayland.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/drm/Atomic.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/drm/Legacy.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/buffer/Buffer.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/input/Input.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/misc/Attachment.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/output/Output.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/lib/libaquamarine.so exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/lib/pkgconfig/aquamarine.pc exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/share/licenses/aquamarine/LICENSE exists in filesystem (owned by aquamarine)
Errors occurred, no packages were upgraded.

-> Failed to install layer, rolling up to next layer.error:error installing: [/home/akari/.cache/yay/hyprcursor-git/hyprcursor-git-0.1.9.r11.g912d5602-1-any.pkg.tar.zst /home/akari/.cache/yay/hyprcursor-git/hyprcursor-git-debug-0.1.9.r11.g912d5602-1-any.pkg.tar.zst /home/akari/.cache/yay/aquamarine-git/aquamarine-git-0.4.1_r215.ge4a1320-1-x86_64.pkg.tar.zst /home/akari/.cache/yay/aquamarine-git/aquamarine-git-debug-0.4.1_r215.ge4a1320-1-x86_64.pkg.tar.zst] - exit status 1
==> Making package: hyprland-git 0.42.0.r64.82c67e61-1 (Sun 08 Sep 2024 09:39:57 AM CST)
==> Checking runtime dependencies...
==> Missing dependencies:
-> aquamarine-git
-> hyprcursor-git
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
-> error making: hyprland-git-exit status 8
==> Making package: hyprcursor-git 0.1.9.r11.g912d5602-1 (Sun 08 Sep 2024 09:39:58 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Updating hyprcursor git repo...
==> Validating source files with sha256sums...
hyprcursor ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
-> Creating working copy of hyprcursor git repo...
Cloning into 'hyprcursor'...
done.
==> Starting pkgver()...
==> Sources are ready.
-> hyprcursor-git-0.1.9.r11.g912d5602-1 already made -- skipping build
==> Making package: hyprcursor-git 0.1.9.r11.g912d5602-1 (Sun 08 Sep 2024 09:40:01 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
==> Making package: aquamarine-git 0.4.1_r215.ge4a1320-1 (Sun 08 Sep 2024 09:40:02 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Updating aquamarine git repo...
==> Validating source files with sha256sums...
aquamarine ... Skipped

==> Removing existing $srcdir/ directory...
==> Extracting sources...
-> Creating working copy of aquamarine git repo...
Cloning into 'aquamarine'...
done.
==> Starting pkgver()...
==> Sources are ready.
-> aquamarine-git-0.4.1_r215.ge4a1320-1 already made -- skipping build
==> Making package: aquamarine-git 0.4.1_r215.ge4a1320-1 (Sun 08 Sep 2024 09:40:05 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
loading packages...
resolving dependencies...
looking for conflicting packages...
:: hyprcursor-git-0.1.9.r11.g912d5602-1 and hyprcursor-0.1.9-1 are in conflict. Remove hyprcursor? [y/N] y
Packages (5) hyprcursor-0.1.9-1 [removal]  aquamarine-git-0.4.1_r215.ge4a1320-1  aquamarine-git-debug-0.4.1_r215.ge4a1320-1
hyprcursor-git-0.1.9.r11.g912d5602-1  hyprcursor-git-debug-0.1.9.r11.g912d5602-1
Total Installed Size:  21.90 MiB
Net Upgrade Size:      21.28 MiB
:: Proceed with installation? [Y/n] y
(4/4) checking keys in keyring
[###################################################] 100%(4/4) checking package integrity
[###################################################] 100%(4/4) loading package files
[###################################################] 100%(4/4) checking for file conflicts
[###################################################] 100%error: failed to commit transaction (conflicting files)

error: failed to commit transaction (conflicting files)
aquamarine-git: /usr/include/aquamarine/allocator/Allocator.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/allocator/GBM.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/allocator/Swapchain.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Backend.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/DRM.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Headless.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Misc.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Session.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/Wayland.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/drm/Atomic.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/backend/drm/Legacy.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/buffer/Buffer.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/input/Input.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/misc/Attachment.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/include/aquamarine/output/Output.hpp exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/lib/libaquamarine.so exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/lib/pkgconfig/aquamarine.pc exists in filesystem (owned by aquamarine)
aquamarine-git: /usr/share/licenses/aquamarine/LICENSE exists in filesystem (owned by aquamarine)
Errors occurred, no packages were upgraded.
-> error installing: [/home/akari/.cache/yay/hyprcursor-git/hyprcursor-git-0.1.9.r11.g912d5602-1-any.pkg.tar.zst /home/akari/.cache/yay/hyprcursor-git/hyprcursor-git-debug-0.1.9.r11.g912d5602-1-any.pkg.tar.zst /home/akari/.cache/yay/aquamarine-git/aquamarine-git-0.4.1_r215.ge4a1320-1-x86_64.pkg.tar.zst /home/akari/.cache/yay/aquamarine-git/aquamarine-git-debug-0.4.1_r215.ge4a1320-1-x86_64.pkg.tar.zst] - exit status 1
error installing: [/home/akari/.cache/yay/hyprcursor-git/hyprcursor-git-0.1.9.r11.g912d5602-1-any.pkg.tar.zst /home/akari/.cache/yay/hyprcursor-git/hyprcursor-git-debug-0.1.9.r11.g912d5602-1-any.pkg.tar.zst /home/akari/.cache/yay/aquamarine-git/aquamarine-git-0.4.1_r215.ge4a1320-1-x86_64.pkg.tar.zst /home/akari/.cache/yay/aquamarine-git/aquamarine-git-debug-0.4.1_r215.ge4a1320-1-x86_64.pkg.tar.zst] - exit status 1

### How to reproduce

yay -S hyprland-git

**Comment by myamusashi** [comment]
You can delete all aquamarine in /usr/include/, did you build and install aquamarine  before installing Hyprland-git?

**Comment by AkariH** [comment]
Thanks myamusashi. I could launch hyprland after running sudo pacman -R aquamarine

**Comment by AkariH** [comment]
After sucessfully install Hyprland and launch it, when I launch kitty, it launched and immediately disappear...

**Comment by AkariH** [comment]
hyprland log

[LOG] Instance Signature: 312411fc7073143a8bf1fc3ba23ef403b7d15eee_1725768344_1358391955
[LOG] Runtime directory: /run/user/1000/hypr/312411fc7073143a8bf1fc3ba23ef403b7d15eee_1725768344_1358391955
[LOG] Hyprland PID: 72441
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: moe
[LOG] Release: 6.10.6-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000


[LOG] GPU information:
00:0f.0 VGA compatible controller [0300]: VMware SVGA II Adapter [15ad:0405] (prog-if 00 [VGA controller])
	Subsystem: VMware SVGA II Adapter [15ad:0405]


[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: The AUR packages always work, except for the times they don't.


[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 56.75µs. Estimated average calc time: 0.07µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 15.27µs. Estimated average calc time: 0.05µs.
[LOG] Using config: /home/akari/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug

**Comment by myamusashi** [comment]
Are you using a virtual machine? and yes it doesn't work in vm.

**Comment by myamusashi** [comment]
I recommend you to use foot instead

**Comment by AkariH** [comment]
Yes, I am running archlinux on VMware workstation. I will try to use foot. Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vaxerski** [comment]
this is not a bug tracker for packaging issues on external distributions
