### ISSUE TITLE
Hyprland can't start on Debug build

### ISSUE THREAD

**Issue by myamusashi** [hyprwm/Hyprland#7696]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Can't start Hyprland on debug mode

### How to reproduce

I'm using OpenRC so I don't know if this can be reproduced in systemd

Cloned and built the most recent Hyprland and ran it

### Crash reports, logs, images, videos

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Who tried dividing by zero?!

Hyprland received signal 11(SEGV)
Version: 312411fc7073143a8bf1fc3ba23ef403b7d15eee
Tag: v0.42.0-126-g312411fc
Date: Sun Sep 8 06:46:46 2024
Flags:

System info:
	System name: Linux
	Node name: artix
	Release: 6.10.8-zen1-1-zen
	Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 07 Sep 2024 18:22:22 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])

os-release:
	NAME="Artix Linux"
	PRETTY_NAME="Artix Linux"
	ID=artix
	BUILD_ID=rolling
	ANSI_COLOR="0;36"
	HOME_URL="https://www.artixlinux.org/"
	DOCUMENTATION_URL="https://wiki.artixlinux.org/"
	SUPPORT_URL="https://forum.artixlinux.org/"
	BUG_REPORT_URL="https://bugs.artixlinux.org/"
	PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
	LOGO=artixlinux-logo
Backtrace:
	# | ./src/Hyprland(_Z12getBacktracev+0x49) [0x5b7cca1859ee]
		getBacktrace()
		/home/gilang/Documents/Project/CONTRIBUTE/Hyprland_dbg/build/../src/helpers/MiscFunctions.cpp:791 (discriminator 1)
	#1 | ./src/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x84e) [0x5b7cca0ac83f]
		CrashReporter::createAndSaveCrash(int)
		/home/gilang/Documents/Project/CONTRIBUTE/Hyprland_dbg/build/../src/debug/CrashReporter.cpp:202
	#2 | ./src/Hyprland(_Z25handleUnrecoverableSignali+0xbe) [0x5b7cc9fc5f71]
		handleUnrecoverableSignal(int)
		/home/gilang/Documents/Project/CONTRIBUTE/Hyprland_dbg/build/../src/Compositor.cpp:73
	#3 | /usr/lib/libc.so.6(+0x3cb80) [0x73ccf3931b80]
		??
		??:0
	#4 | [0x5b7cd84765c0]
		??
		??:0

Log tail:
[LOG] XCursor already has a shape ns-resize loaded, skipping
[LOG] XCursor failed to find a legacy shape with name fd_double_arrow, skipping
[LOG] XCursor failed to find a legacy shape with name bd_double_arrow, skipping
[LOG] XCursor already has a shape col-resize loaded, skipping
[LOG] XCursor already has a shape row-resize loaded, skipping
[LOG] XCursor already has a shape all-scroll loaded, skipping
[LOG] XCursor already has a shape zoom-in loaded, skipping
[LOG] XCursor already has a shape zoom-out loaded, skipping
[hc] loadThemeStyle: loading for size 24
[hc] getShapesC: found 1 images for left_ptr
[LOG] Starting XWayland
[LOG] Starting up the XWayland server
[LOG] XWayland found a suitable display socket at DISPLAY: :1
[WARN] Failed to change process scheduling strategy
[LOG] Hyprland init finished.
[LOG] Running on WAYLAND_DISPLAY: wayland-2
[LOG] New aquamarine output with name HEADLESS-1
[LOG] New output with name FALLBACK
[LOG] [hookSystem] New hook event registered: newMonitor
[hc] getShapesC: found 1 images for left_ptr
[LOG] Hyprland is ready, running the event loop!
[LOG] [AQ] backend: poll fd 11 for implementation headless
[LOG] [AQ] backend: poll fd 13 for implementation wayland
[LOG] [AQ] backend: poll fd 12 for idle
[LOG] New aquamarine keyboard with name wl_keyboard
[LOG] ApplyConfigToKeyboard for "wl_keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Updating keyboard 5b7cd8b87000's translation state from a provided keymap
[LOG] xkb: LED index 0 (name Num Lock) got index 1
[LOG] xkb: LED index 1 (name Caps Lock) got index 0
[LOG] xkb: LED index 2 (name Scroll Lock) got index 2
[LOG] xkb: Mod index 0 (name Shift) got index 0
[LOG] xkb: Mod index 1 (name Lock) got index 1
[LOG] xkb: Mod index 2 (name Control) got index 2
[LOG] xkb: Mod index 3 (name Mod1) got index 3
[LOG] xkb: Mod index 4 (name Mod2) got index 4
[LOG] xkb: Mod index 5 (name Mod3) got index 5
[LOG] xkb: Mod index 6 (name Mod4) got index 6
[LOG] xkb: Mod index 7 (name Mod5) got index 7
[LOG] Updating keymap fd for keyboard wl_keyboard
[LOG] Updated keymap fd to 458
[LOG] [hookSystem] New hook event registered: activeLayout
[LOG] Set the keyboard layout to us and variant to  for keyboard "wl_keyboard"
[LOG] New keyboard created, pointers Hypr: 5b7cd8b87000 and AQ: 5b7cd841a4b0
[LOG] New aquamarine pointer with name wl_pointer
[LOG] Attached pointer wl_pointer to global
[LOG] New mouse created, pointer AQ: 5b7cd84a92f0
[LOG] New aquamarine output with name WAYLAND-1
[LOG] New output with name WAYLAND-1
[WARN] No rule found for WAYLAND-1, trying to use the first.
[LOG] Applying monitor rule for WAYLAND-1
[ERR] Monitor WAYLAND-1 has NO PREFERRED MODE
[WARN] updateSwapchain: No mode?
[LOG] CMonitorState::ensureBufferPresent: no buffer or mismatched format, attaching one from the swapchain for modeset being possible
[LOG] output WAYLAND-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[WARN] updateSwapchain: No mode?
[LOG] CMonitorState::ensureBufferPresent: no buffer or mismatched format, attaching one from the swapchain for modeset being possible
[ERR] [AQ] Output WAYLAND-1: pending state rejected: invalid mode
[ERR] Couldn't commit output named WAYLAND-1
[LOG] arrangeMonitors: 1 to arrange
[LOG] arrangeMonitors: WAYLAND-1 auto [-1, -1]
[LOG] arrangeMonitors: WAYLAND-1 xwayland [0, 0]
[LOG] Monitor WAYLAND-1 data dump: res 0x0@60.00Hz, scale 1.00, transform 0, pos 0x0, 10b 0
[hc] loadThemeStyle: loading for size 24
[hc] getShapesC: found 1 images for left_ptr
[LOG] [AQ] GBM: Automatically selected format XR24 for new GBM buffer
[LOG] [AQ] GBM: Buffer is marked as multigpu, forcing linear
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 24, y: 24] and format XR24 with modifier 0 aka LINEAR
[LOG] [AQ] GBM: Automatically selected format XR24 for new GBM buffer
[LOG] [AQ] GBM: Buffer is marked as multigpu, forcing linear
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 24, y: 24] and format XR24 with modifier 0 aka LINEAR

**Comment by vaxerski** [comment]
stacktrace is bogus, but this looks like something that has been fixed in aquamarine a while abck
