### ISSUE TITLE
Minimum required CMake version is 3.30

### ISSUE THREAD

**Issue by jpalus** [hyprwm/Hyprland#7707]
### Regression?

Yes

### System Info and Version

0.43.0
GCC 14.2.0
CMake 3.29.7

### Description

Compilation fails due to missing c++26 std in command line required in this version. While `Hyprland` declares minimum required CMake version as 3.27, it is effectively 3.30 since it's the first version with support for C++26 in GCC:
https://gitlab.kitware.com/cmake/cmake/-/commit/1ba4a0633833903a3429e87a4c72ffe738139dd4

### How to reproduce

Build hyprland with CMake < 3.30

**Comment by fufexan** [comment]
Ah, so that's why Hyprland wouldn't build on Nix without https://github.com/hyprwm/Hyprland/blob/main/nix/stdcxx.patch. Nix has CMake 3.29 still. I assume there are many other non-Arch distros in the same boat.

I suggest we don't bump the required version yet.

**Comment by leiserfg** [comment]
Yes, that's the same I commented long time ago @fufexan, I think that patch should be part of the default CMakeLists.txt
until cmake 3.30 is more common.

**Comment by vaxerski** [comment]
Now that we bumped to 3.30 this can be closed.
