### ISSUE TITLE
allow managing desktop lid

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#771]
I realize I'm missing something big from sway: the ability to handle the laptop LID events.

Sway has a way to bind a switch like so

```
bindswitch --reload --locked lid:toggle exec ~/.bin/lid.sh
```
reload means to rerun the script to align the state on sway reload
locked means it should trigger even if locked
lid:toggle is a handler that will make the binding trigger on change of the LID switch state

This is the first thing I miss from Hyprland (I know logind can handle this, but it sucks and I can't do what I want to do)

Second (maybe I missed it) is to be able to toggle on and off a *single* monitor (with `swaymsg output <name|*> enable|disable`). Hyprland seems to be able to completely disable a monitor (and completely loose track of it until reload) or dpms off all the monitors at once

Here's the content of my lid.sh script

```
#!/bin/env bash

if grep -q open /proc/acpi/button/lid/LID0/state; then
	swaymsg "output eDP-1 enable"
else
	# If we are not in CLAMSHELL mode
	if [[ "$(swaymsg -t get_outputs | grep -c name)" == "1" ]]; then
		suspend.sh force
	else
		swaymsg "output eDP-1 disable"
	fi
fi
```

I don't see any way to replicate any of these in Hyprland

**Comment by primalmotion** [comment]
I tried to use wlr-randr --output eDP-1 --off, but that crashes Hyprland

**Comment by vaxerski** [comment]
`hyprctl dpms off`???

**Comment by primalmotion** [comment]
@vaxerski that turns all monitors off. When I close tge lid, I only want to turn the screen off

**Comment by vaxerski** [comment]
oh, alr

**Comment by primalmotion** [comment]
when this is in, I'll consider myself a Hyprland citizen and will make a donation for your awesome work and responsiveness :)

**Comment by vaxerski** [comment]
0d702b556d0a52f1df53ac1e52fac11b8302783b 

tested with
```
bindl=,switch:Lid Switch,exec,kitty
```
check `hyprctl devices` for the switch name

and leave me alone

**Comment by primalmotion** [comment]
I'm almost about to leave you alone, but it seems this does not solve the "single monitor dpms control" or at least "don't crash with wlr-randr" :p

In the meantime let me test this! Thanks

**Comment by vaxerski** [comment]
because don't use wlr-randr

```
hyprctl keyword monitor DP-1,disable
```

**Comment by primalmotion** [comment]
but as i stated above, if I do this, I cannot reenable it because it says it does not know DP-1 after this

**Comment by vaxerski** [comment]
you can.
```
hyprctl keyword monitor DP-1,preferred,auto,1
```

**Comment by primalmotion** [comment]
ok let me try all of this. reporting back in a few

**Comment by primalmotion** [comment]
I understand, but what I really need it more like granular dpms :)

I I have several setups (home and office) where the monitor physical positionning are not the same (in the office my screen is above my laptop screen and I sometimes close the lid or not) and at home, the my screen is to the left of the laptop and additionally scaled to 1.3.  Both are display port over USB-C and related to #775, I would have no way to know (easily) which monitor is actually plugged in and which static conf I could add. 

Also I would like to keep my scripts work both with Sway and Hyprland for a little while, so I have created the following script to abstract the control of screen power

```
#!/bin/bash


monitor="$1"
action="$2"

case "$action" in
	on|enable)
		if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then
			if [[ "$monitor" == "*" ]]; then
				hyprctl dpms on
			else
				hyprctl keyword monitor "${monitor},preferred,auto,1"
			fi
		else
			swaymsg "output $monitor enable"
		fi
		;;
	off|disable)
		if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then
			if [[ "$monitor" == "*" ]]; then
				hyprctl dpms off
			else
				hyprctl keyword monitor "${monitor},disable"
			fi
		else
			swaymsg "output $monitor disable"
		fi
		;;
esac
```

As you can see the hyprland world is less clean :)

**Comment by vaxerski** [comment]
dpms will only "turn the screen off", while `disable` will actually remove it from the layout and delegate all the workspaces it contains to the rest.

No plans atm for toggleable disable, dpms per-monitor is something I have on my todo list tho

**Comment by primalmotion** [comment]
dpms per monitor is all I'm asking for :)

**Comment by primalmotion** [comment]
from what you said I understand the workspaces on the dpms off'ed screen would stay there, but that's nothing I can't workaround

**Comment by vaxerski** [comment]
dpms per mon in 0e4a894edb44f4fedfca597f41889d3668b36b17

```
hyprctl dispatch dpms "on DP-1"
```

**Comment by primalmotion** [comment]
works like a charm. Thanks!

**Comment by jollySleeper** [comment]
> [0d702b5](https://github.com/hyprwm/Hyprland/commit/0d702b556d0a52f1df53ac1e52fac11b8302783b)
> 
> tested with
> 
> ```
> bindl=,switch:Lid Switch,exec,kitty
> ```
> 
> check `hyprctl devices` for the switch name
> 
> and leave me alone you bribing binch

Hi @vaxerski thanks for this amazing work, much appreciated.
But for some reason this binding isn't working for me. 
It worked once then it stopped working.
And sometimes after a reboot it works but only once.

Note: my laptop suspends after 5-10mins of lid close maybe that is stopping swaylock?
