### ISSUE TITLE
Ignore monitors not explicitly defined in hyprland.conf

### ISSUE THREAD

**Issue by ctilley83** [hyprwm/Hyprland#7719]
After upgrading to kernel 6.10.8-1 on openSUSE Tumbleweed, an additional monitor appeared on my system. This broke Hyprland's workspaces like issue https://github.com/hyprwm/Hyprland/issues/6309.

It was difficult to track down since I only have one monitor listed in my config file

```monitor = HDMI-A-1, preferred, auto, 1```

However, hyprland still detected and enabled the 'Uknown-1' monitor even though the expected behavior is that only monitors specified in hyprland.conf would be enabled. Adding this feature would eliminated the need to disable ghost monitors.

**Comment by vaxerski** [comment]
No, that's not the expected behavior.

You can add a fallback rule to disable any unknown monitor
