### ISSUE TITLE
Window swallowing doesn't work with multiple windows owned by a single process

### ISSUE THREAD

**Issue by micamoan** [hyprwm/Hyprland#772]
If multiple terminal windows are owned by a single process (for example terminals that run in client/server mode), only the first window will actually be swallowed.

### Steps to reproduce:

Open two kitty windows using kitty --single-instance (I've also tested this with foot using foot -s and footclient). Launch MPV (or any other command that spawns a window) in both terminals.

### Expected outcome:

Both windows should be swallowed by their respective commands.

### Noted outcome:

Only the first window is actually swallowed. The second one is not.

### Workaround:

You get the expected behavior however when you use terminals that run as separate processes, but this uses much more system resources and is thus less than ideal.

**Comment by vaxerski** [comment]
I do be aware

**Comment by vaxerski** [comment]
check with 3e3f6aef5efa5d3b20c9cb3db8df40127b9222d1

**Comment by micamoan** [comment]
Now it works like this: Launch two kitty --single-instance windows (I also checked this with footclient, identical behavior). Now try launching both terminals with MPV again. If you do the first window, then the second, it swallows correctly. (I use force_split 2 in my config so the new window always spawns on the right.) However, if you do the second window first, then the first window is swallowed and the second one is not. So it incorrectly chooses which window to swallow based on which order the windows were spawned.

**Comment by vaxerski** [comment]
yeah I see now

**Comment by vaxerski** [comment]
a80e0cecfed48fbe61058015ad77653e0f48dff0

**Comment by vaxerski** [comment]
you're cloning wrong then

**Comment by micamoan** [comment]
Yeah my bad, I ripped out Hyprland entirely, recloned, reinstalled, didn't work. Then I tried installing hyprland-git from the AUR and for some reason that worked. Can confirm it's working right with kitty as well.
