### ISSUE TITLE
HDMI monitor shows noisy stripe/point under custom refresh rate after updated to v0.43

### ISSUE THREAD

**Issue by shilkazx** [hyprwm/Hyprland#7727]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

HDMI monitor shows noisy stripe/point under custom refresh rate(1920x1080@75Hz) after updated to v0.43. The default refresh rate(marked as "preferred" by wlr-randr, 60Hz in my case) still works fine.
My previous setting works fine through v0.38-0.42, but v0.43 induce the bug.
I'll resurvey this issue on other monitor tomorrow.
System: Archlinux x64 with official hyprland package.

https://github.com/user-attachments/assets/ac5fea5b-65cc-4ce6-b975-214ff0da60be

https://github.com/user-attachments/assets/dd21ff61-c83d-4aa8-91fa-7ffebdb03f51

### How to reproduce

Start hyprland as usual.

**Comment by vaxerski** [comment]
bisect then please

**Comment by shilkazx** [comment]
> bisect then please

Update: I've tested on another monitor(with another cable) and all things fine. So I'll investigate the hardware problem in near further. The bisection would be taken after the hardware problem being excluded.

**Comment by shilkazx** [comment]
Update: During some univariate test of the hardware and software, the bug gone and everything back to normal. I can't figure out what happened, maybe mystery interference or something unknown T_T.  Thanks for your patient @vaxerski .
