### ISSUE TITLE
As @danjm is mentioning, I'm also getting some trouble upgrading from another version, having Rinkeby selected, and then loading this version.

### ISSUE THREAD

**Issue by tazimamatovzeka** [hyprwm/Hyprland#774]
As @danjm is mentioning, I'm also getting some trouble upgrading from another version, having Rinkeby selected, and then loading this version.

I am seeing the Restart MetaMask page and this error on the background console:

![image](https://user-images.githubusercontent.com/54408225/192811731-23830cf9-4fa9-4ba8-82a1-4c67fa7a9f70.png)

Here the flow:

[testnets-deprecation.webm](https://user-images.githubusercontent.com/54408225/192811388-c657c82d-e1d8-4788-b83c-6f8dc10c08e4.webm)

_Originally posted by @seaona in https://github.com/MetaMask/metamask-extension/pull/15989#issuecomment-1261034958_

**Comment by fufexan** [comment]
How does this have anything to do with Hyprland?
