### ISSUE TITLE
wintypes like features?

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#7742]
### Description

in picom, you can have configs like this(this is my picom config before):
```
wintypes:
{
  normal = { fade = true; shadow = false; opacity = 0.95 }
  tooltip = { fade = false; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; opacity: 0.8 }
  dnd = { shadow = false; opacity: 0.8 }
  popup_menu = { opacity = 0.7; }
  dropdown_menu = { opacity = 0.8; }
  utility = { shadow = false; opacity = 0.8; };
};
```

but i think the important ones are popup_menu and dropdown_menu and tooltip. because these can apply to chromium and more apps. anyway to do layerrule or something like that?

**Comment by vaxerski** [comment]
popups can be styled with the popup-targeting variables (e.g. blur popups)

For other stuff, no, they are not targetable.

**Comment by littleblack111** [comment]
is there a section on the hyprland wiki?(link pls) i wanna see more details about this. or is this undocumented?

**Comment by vaxerski** [comment]
opacity? no. Popup blur is here: https://wiki.hyprland.org/Configuring/Variables/#blur
