### ISSUE TITLE
Move all files from a workspace to a special one called hidden

### ISSUE THREAD

**Issue by F5T3** [hyprwm/Hyprland#7747]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>
Hyprland, built from branch main at commit 9b54342baa27d8de0460e1103ec4c3cc65592ed8  (Revert syncobj: wait for deadline instead of available).
Date: Tue Sep 3 14:47:34 2024
Tag: v0.42.0-113-g9b54342b, commits: 5182

flags: (if any)

System Information:
System name: Linux
Node name: IuseArchBTW
Release: 6.10.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070 SUPER] [10de:2783] (rev a1) (prog-if 00 [VGA controller])
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```sh
<Paste the output of the command here>
```
Hyprland, built from branch main at commit 9b54342baa27d8de0460e1103ec4c3cc65592ed8  (Revert syncobj: wait for deadline instead of available).
Date: Tue Sep 3 14:47:34 2024
Tag: v0.42.0-113-g9b54342b, commits: 5182

flags: (if any)

System Information:
System name: Linux
Node name: IuseArchBTW
Release: 6.10.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070 SUPER] [10de:2783] (rev a1) (prog-if 00 [VGA controller])
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/F5T3/.config/hypr/hyprland.conf: Read Succeeded
#--GENERAL--#
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/disabled.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/nvariables.conf
source = ~/.config/hypr/layouts.conf
#--LOOKS--#

debug {
    disable_logs = false
    enable_stdout_logs = true
}

cursor {
    no_hardware_cursors = true
}

#-GENERAL-#
    general {

        ##--GAPS--##
            gaps_in = 3
            gaps_out = 5

        ##--BORDERS--##
            no_border_on_floating = true
            border_size = 2

            col.active_border = rgb(EED2CC) rgb(C5283D) 45deg
            col.inactive_border = rgb(348AA7)
            col.nogroup_border = rgb(080357)
            col.nogroup_border_active = rgb(EED2CC) rgb(B9F18C) 45deg

        ##--DISABLED/NOT-CONFIGURED--##
            gaps_workspaces = 0
            no_focus_fallback = false
            allow_tearing = false
            resize_corner = 1

        ###---BORDER---###
            resize_on_border = false
            extend_border_grab_area = 15
            hover_icon_on_border = true
    }
#-DECORATION-#
    decoration {
        rounding = 5 

        active_opacity = 1.0
        inactive_opacity = 1.0

        drop_shadow = true
        shadow_range = 4
        shadow_render_power = 3
        col.shadow = rgba(1a1a1aee)

        ##-BLUR-##
            blur {
            enabled = true
            size = 3
            passes = 1
        
            vibrancy = 0.1696
            }
    }

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    initial_workspace_tracking = 2
    font_family	= Monospace
    force_default_wallpaper = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = false
    enable_swallow = true
}

#############
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 1.25 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

Config File: /home/F5T3/.config/hypr/monitors.conf: Read Succeeded
monitor=DP-2,1920x1080@165,0x0,1

Config File: /home/F5T3/.config/hypr/variables.conf: Read Succeeded
$terminal = kitty
$fileManager = kitty -e nnn
$menu = walker
$clipboardManager = kitty --class=clipse -e clipse

env = RUST_BACKTRACE,full
env = XDG_SESSION_TYPE,wayland

Config File: /home/F5T3/.config/hypr/keybinds.conf: Read Succeeded
bind = Ctrl&Alt, T, exec, $terminal
bind = Alt, F4, killactive,
bind = Super&Alt, F4, exit,
bind = Super, E, exec, $fileManager
bind = Super, F, togglefloating,
bind = Super, Super_L, exec, $menu
bind = Super, P, pseudo, # dwindle
bind = Super, J, togglesplit, # dwindle
bind = Super, V, exec, $clipboardManager
bind = Super, Tab, exec, ags -t overview
bind = , Print, exec, screenshot
bind = Super, M, exec, ~/.scripts/show_desktop.sh hide
bindr = Super, M, exec, ~/.scripts/show_desktop.sh show
bind = Super&Shift, M, exec, ~/.scripts/show_desktop.sh toggle

# Switch workspaces with mainMod + [0-9]
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10
bind = Super, D, workspace, hidden

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = Super SHIFT, 1, movetoworkspace, 1
bind = Super SHIFT, 2, movetoworkspace, 2
bind = Super SHIFT, 3, movetoworkspace, 3
bind = Super SHIFT, 4, movetoworkspace, 4
bind = Super SHIFT, 5, movetoworkspace, 5
bind = Super SHIFT, 6, movetoworkspace, 6
bind = Super SHIFT, 7, movetoworkspace, 7
bind = Super SHIFT, 8, movetoworkspace, 8
bind = Super SHIFT, 9, movetoworkspace, 9
bind = Super SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = Super, mouse_down, workspace, e+1
bind = Super, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = Ctrl, mouse:272, movewindow
bindm = Ctrl, mouse:273, resizewindow

Config File: /home/F5T3/.config/hypr/disabled.conf: Read Succeeded
#-LAYOUT-#
dwindle {
    pseudotile = false
    smart_resizing = true
    permanent_direction_override = false
    split_width_multiplier= 1.0
    no_gaps_when_only = 0
    use_active_for_splits = true
    default_split_ratio = 1.0
}

master {

}

Config File: /home/F5T3/.config/hypr/startup.conf: Read Succeeded
exec-once = workspace_listener.sh
exec-once = wl-paste --w clipse -wl-store && clipse -listen
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprctl setcursor VisionCursor 64
exec-once = hyprnotify & ~/.scripts/swww.sh & waybar
exec = rm /tmp/sovpipe && mkfifo /tmp/sovpipe && tail -f /tmp/sovpipe | sov -t 500

Config File: /home/F5T3/.config/hypr/rules.conf: Read Succeeded
windowrulev2 = float, class:^(.*com.github.Aylur.ags*)$
windowrulev2 = float, class:(clipse)
windowrulev2 = size 622 652, class:(clipse)
windowrulev2 = float, class:(net.F5T3.HyprSettings)
windowrulev2 = float, class:(hyprexpo)

windowrulev2 = suppressevent maximize, class:.*

Config File: /home/F5T3/.config/hypr/nvariables.conf: Read Succeeded
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

Config File: /home/F5T3/.config/hypr/layouts.conf: Read Succeeded
master {
    allow_small_split = true
    special_scale_factor = 1.5
    mfact = 0.25
    new_status = inherit
    new_on_top = true
    new_on_active = before 
    orientation = right
    inherit_fullscreen = true
}

dwindle {
    force_split = 2
    preserve_split = true
    smart_split = true
    special_scale_factor = 1.5 
}

general {
    layout = master
}

======Config-End========

</details>

### Description

I am trying to move all windows from a workspace, so I am trying to use the "movetoworkspace" dispatcher. And it is only moving the active window, or the first window of the second workspace. And now I am wondering how the fuck I should do this, I also forgot to mention, that when I try to add a window pid, id or address it says Window not found

My English isn't the best so... yea sorry for any misplaced commas and other mistakes

### How to reproduce

hyprctl dispatch movetoworkspace special:hidden,<workspace_id>
or for the second workspace thing
hyprctl dispatch movetoworkspace special:hidden

### Crash reports, logs, images, videos

![Command OutPut](https://github.com/user-attachments/assets/55ea3f24-0194-4fd0-83e9-4b4488bd19dc)

**Comment by vaxerski** [comment]
![image](https://github.com/user-attachments/assets/0930b12a-acd7-4751-b1b8-372096c5e489)

`window` is a window type param:

![image](https://github.com/user-attachments/assets/daeb10fb-5a49-4086-81a7-dae8f40538a4)


The wiki is well documented, and you should reaad it _carefully_.

![image](https://github.com/user-attachments/assets/c3488aa1-83e2-4f4f-b3ca-9180a922b8f8)


not found cuz you didn't prefix the address with `address:`

**Comment by F5T3** [comment]
Oh thanks for explaining this to me. But how would I move all windows from a workspace to another one, like said in the title?

Cuz I want to make a interact with widgets and desktop shortcut (using a bash script)

Thx if anyway could help

**Comment by vaxerski** [comment]
parse `hyprctl clients` (probably add `-j` and parse the json)

Every window will have a workspace field. Get the addresses and just `hyprctl --batch 'dispatch movetoworkspace special:hidden,address:0x.... ; dispatch movetoworkspace special:hidden,address:0x.... ; ...`
