### ISSUE TITLE
touchpad scrolling fallthroughs in special workspace

### ISSUE THREAD

**Issue by daniele821** [hyprwm/Hyprland#7749]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit c67b257e51133a2aaeec050fc4d283e2eaea6375  ().
Date: Mon Sep 09 22:06:37 2024
Tag: , commits: 5207

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.10.8-200.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Wed Sep  4 21:41:11 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Plus Graphics G1 (Ice Lake) [8086:8a56] (rev 07) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:


```

</details>

### Description

I scroll through an application with my touchpad, then i toggle the special workspace, and I try to scroll a window i open in said special workspace. But until i click the window in the special workspace, scrolling on the touchpad, scrolls the window behind the special workspace

### How to reproduce

open an application. 
Scroll with touchpad.
open a special workspace.
open an application.
Scrolling now will scroll the window behind, until you click the window in the special workspace

### Crash reports, logs, images, videos

here a preview of the bug.

https://github.com/user-attachments/assets/a166b178-71ca-445d-a8d8-4d9505e04e0a

Also, this bug may be related to #7655 ?

**Comment by izmyname** [comment]
https://github.com/hyprwm/Hyprland/issues/6269

**Comment by daniele821** [comment]
my bad, i am closing this
