### ISSUE TITLE
allow to identify monitor by name

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#775]
I use a laptop and move from 2 different main setups, home and office. In both setups, I use a different second monitor arrangement. Hyprland  only allows to identify a monitor based it's port name (DP-1, eDP-1, HDMI-1 etc). This makes me unable to segregate both monitors so I can position them correctly. Sway for instance, allows to identify a monitor from it's name, in addition to the port name.

For instance:

```
$ swaymsg -t get_outputs
Output eDP-1 'Chimei Innolux Corporation 0x1415 Unknown' (focused)
  Current mode: 1920x1080 @ 60.001 Hz
  [snip]

Output DP-1 'Dell Inc. DELL U3419W GF2W5T2'
  Current mode: 3440x1440 @ 59.973 Hz
  [snip]
```

I can reference office's DP-1 as `Dell Inc. DELL U3419W GF2WXXX` and  my other home monitor as whatever its name is

**Comment by vaxerski** [comment]
done in 71e2562a4151b506cece69f7d121847957d4bac4

**Comment by vaxerski** [comment]
`desc:blah blah` in monitor rules, see `hyprctl monitors`

**Comment by primalmotion** [comment]
It works however, the description seems to be `Dell Inc. DELL U3419W GF2W5T2 (DP-2 via HDMI)' which still ties it to a port. I think it should just be `Dell Inc. DELL U3419W GF2W5T2`

**Comment by vaxerski** [comment]
done in 9c5023ab1acf2297e4bbcc3bcb008bbc818a1972

**Comment by primalmotion** [comment]
awesome let me try :)

**Comment by primalmotion** [comment]
the `desc:bla bla` can be use anywhere we normally need to reference a monitor?

**Comment by vaxerski** [comment]
only in monitor rules

**Comment by Programmerino** [comment]
It seems like monitors with commas in their descriptions can't be modified with this method. Am I missing anything?

**Comment by vaxerski** [comment]
you aren't

**Comment by Hubro** [comment]
Also monitors with hash symbols doesn't work, such as my Asus PG279Q:

```
Ancor Communications Inc ROG PG279Q #ASNREOhpntPd
```

The hash is interpreted as a comment. My newest monitor has a comma in the description :smile: At this point 2 out of my 3 monitors can't be targeted with `desc`. We definitely need a way to escape these symbols, or support for quotes, e.g.:

```
monitor=desc:"Ancor Communications Inc ROG PG279Q #ASNREOhpntPd",2560x1440@165,0x0,1
```

**Comment by JustSimplyKyle** [comment]
http://wiki.hyprland.org/Configuring/Configuring-Hyprland/#comments

**Comment by Hubro** [comment]
> http://wiki.hyprland.org/Configuring/Configuring-Hyprland/#comments

Right, forgot about that! :grin: So only 1 out of my 3 monitors can't be targeted with `desc:`
