### ISSUE TITLE
Could not initialise OpenGL support

### ISSUE THREAD

**Issue by falsificatedcybernetics** [hyprwm/Hyprland#7751]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 18:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: B450-GAMING-X
Release: 6.8.0-44-generic
Version: #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] [10de:1c82] (rev a1) (prog-if 00 [VGA controller])


os-release: PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

</details>

### Description

default ubuntu video player(totem) shows me this error(Could not initialise OpenGL support)
after trying to open video file 
also VLC stucks at first frame when trying to play any video

### How to reproduce

idk

### Crash reports, logs, images, videos

(VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[00005aeb66e52550] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00005aeb66eea0d0] main playlist: playlist is empty
libEGL warning: egl: failed to create dri2 screen
libva info: VA-API version 1.20.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
[00007995fc001fc0] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[000079960c00a960] main video output error: video output creation failed
[0000799614c11f00] main decoder error: failed to create video output
[00007995fc0c2f70] glconv_vdpau gl error: glVDPAUInitNV failed: 0x502)

**Comment by vaxerski** [comment]
you're on a very outdated hyprland version, and this is a driver issue
