### ISSUE TITLE
xwayland: There are two IME popups in JetBrains idea

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#7757]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 73b9756b8d7ee06fc1c9f072f2a41f2dd1aeb2c9  (xwayland: remove extra x11 deactivation (7755)).
Date: Thu Sep 12 17:15:01 2024
Tag: v0.43.0-18-g73b9756b, commits: 5214

flags: (if any)
```

</details>

### Description

When opening IDEA and a Wayland client, fcitx5 does not work properly in IDEA and needs to close the Wayland client.

### How to reproduce

1. Open Jetbrains software and a wayland client
2. Using fcitx5 in jetbrains idea

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/c895372e-dc53-4d51-b02e-48323a8c94bf

**Comment by hdm9527** [comment]
@sungyoonc

**Comment by sungyoonc** [comment]
is idea running in wayland or xwayland?

**Comment by hdm9527** [comment]
xwayland

**Comment by hdm9527** [comment]
> Try this. This was probably caused because I forgot to remove some debug code in the previous MR [patch.txt](https://github.com/user-attachments/files/16980329/patch.txt)

Thank you for the patch, it works fine.
