### ISSUE TITLE
Mouse left handed mode

### ISSUE THREAD

**Issue by g33kex** [hyprwm/Hyprland#776]
Libinput has an option to swap the right and left button of an input device called left handed mode: https://man.archlinux.org/man/libinput.4#Option~11

I don't see how to enable this option in Hyprland, could it be added?

**Comment by vaxerski** [comment]
why are you left-handed? yikes

60c414ccadd0e2ff6be22bb880f605a164f451d5

`input:left_handed`

per-device: `left_handed`

**Comment by g33kex** [comment]
Thank you! Yes I'm left-handed, so I usually have my mouse buttons swapped with that option.
