### ISSUE TITLE
Crashes at launch 

### ISSUE THREAD

**Issue by 168211681** [hyprwm/Hyprland#7760]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
>
```
-
</details>

### Description

crashes

### How to reproduce

-

### Crash reports, logs, images, videos

[hyprlandCrashReport2419.txt](https://github.com/user-attachments/files/16981360/hyprlandCrashReport2419.txt)
[hyprlandCrashReport4281.txt](https://github.com/user-attachments/files/16981361/hyprlandCrashReport4281.txt)
[hyprlandCrashReport5249.txt](https://github.com/user-attachments/files/16981362/hyprlandCrashReport5249.txt)
[hyprlandCrashReport1388363.txt](https://github.com/user-attachments/files/16981363/hyprlandCrashReport1388363.txt)
[hyprlandCrashReport1388452.txt](https://github.com/user-attachments/files/16981364/hyprlandCrashReport1388452.txt)

**Comment by Honkazel** [comment]
> Tag: v0.41.2

Too old

> ![image](https://github.com/user-attachments/assets/8ad652b3-e02a-4daa-9699-6d2917c2ef26)

Where?

> [backend/backend.c:224] Cannot create X11 backend: disabled at compile-time

Eh?

**Comment by vaxerski** [comment]
as above, wildly out of date + you're launching on an X11 session
