### ISSUE TITLE
errors : Invalid dispatcher,requested "code" does not exist

### ISSUE THREAD

**Issue by ilushian** [hyprwm/Hyprland#7763]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

`    #         __ _ ____ _  _ ____ __ __ _ ____ __ __ _  ___ ____ 
    #        (  / |  __| \/ |  _ (  |  ( (    (  |  ( \/ __) ___)
    #         )  ( ) _) )  / ) _ ()(/    /) D ()(/    ( (_ \___ \
    #        (__\_|____|__/ (____(__)_)__|____(__)_)__)\___(____/

$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, T, exec, kitty
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, W, togglefloating,
bind = $mainMod, V, code,

bind = ALT, return, fullscreen ,1 
bind = $mainMod, J, togglesplit, # dwindle

bind = $mainMod, R, exec, pkill -x rofi || $HOME/.config/rofi/launchers/type-5/launcher.sh
bind = ALT, W , exec , $HOME/.config/script/selectswww.sh
bind = $mainMod, Escape, exec, pkill -x rofi || $HOME/.config/rofi/powermenu/type-4/powermenu.sh

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = Alt, Tab, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-
</details>

### Description

Invalid dispatcher,requested "code" does not exist

### How to reproduce

Invalid dispatcher,requested "code" does not exist

### Crash reports, logs, images, videos

![Screenshot-airy@2024913137](https://github.com/user-attachments/assets/ca59e613-5ff0-4269-8566-99be39ffecb7)

**Comment by Honkazel** [comment]
Keybinds issues on your side
If ya wanna launch app(vscode ig?), then instead of this:
`bind = $mainMod, V, code`
Do this:
`bind = $mainMod, V, exec, code`

**Comment by Honkazel** [comment]
Also pls, read the whole hyprland wiki
