### ISSUE TITLE
Control text opacity separately

### ISSUE THREAD

**Issue by keliss** [hyprwm/Hyprland#7765]
### Description

Hello. While having transparent windows is nice, it affects the readability of text: regardless of the terminal settings, white becomes gray-ish and starts to blend in with wallpapers. So users have to choose between the eye candy and practicality. Maybe it would be possible to add an option to make only the window transparent, while keeping the text intact? Thank you.

**Comment by fufexan** [comment]
Hyprland has no way of differentiating text and other elements from the background of a window.

This is usually handled by setting the background opacity in the program's configuration. Most terminals have such an option, so it shouldn't be an issue.
