### ISSUE TITLE
Replicate previous `fakefullscreen` behavior

### ISSUE THREAD

**Issue by jficz** [hyprwm/Hyprland#7770]
### Description

Now with the `fullscreenstate` it's impossible to replicate previous `fakefullscreen` behavior fully (or it is at least unclear _how_ would one do that).

Specifically, setting `fullscreenstate 0 2`, which is the closest, always touches both client and internal meaning if the window is, for example, already maximized by something like `fullscreenstate 1 1`, it doesn't seem possible to just trigger a "`fakefullscreen`" without resizing the window back to the original state. Previously, with `fakefullscreen`, this was possible.

I guess what I want is the option to set fullscreen state for client and internal independently.

**Comment by vaxerski** [comment]
`-1` can be used to not alter the selected state

**Comment by LachTrip** [comment]
Fullscreen toggle (without affecting "fakefullscreen"):
fullscreenstate, 2, -1

Equivalent to deprecated fakefullscreen toggle:
fullscreenstate, -1, 2
