### ISSUE TITLE
hyprland v0.43 crash report with nix-unstable package

### ISSUE THREAD

**Issue by Vetoes** [hyprwm/Hyprland#7773]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh

<Paste the output of the command here>
```

</details>

### Description

this is my flake.nix
```
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    hyprland={
    url =  "git+https://github.com/hyprwm/Hyprland?submodules=1";
    inputs.nixpkgs.follows ="nixpkgs-unstable";
    };
```
and configuration.nix
```
	programs = {
		hyprland = {
			enable = true;

      package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
# make sure to also set the portal package, so that they are in sync
      portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;

		};
```

seems problem with aquamarine but cant fix myself..

### How to reproduce

nixos
nvidia

### Crash reports, logs, images, videos

[hyprlandCrashReport2723.txt](https://github.com/user-attachments/files/16994638/hyprlandCrashReport2723.txt)

[coredump_2723.txt](https://github.com/user-attachments/files/16994652/coredump_2723.txt)

**Comment by vaxerski** [comment]
driver/mesa bug to me

**Comment by gesker** [comment]
Seeing the same behavior @Vetoes. Not sure the relationship between the Hyprland project and the NixOS project so will open an issue in the NixOS repo and link to this report just so the item is not lost/overlooked.

**Comment by Vetoes** [comment]
> Seeing the same behavior @Vetoes. Not sure the relationship between the Hyprland project and the NixOS project so will open an issue in the NixOS repo and link to this report just so the item is not lost/overlooked.

i tested older version over   0.40 
now i solve crash issue accidentally

```
master{
    new_status = master
}
```
remove this option make it work v0.43
