### ISSUE TITLE
textinput: No deactive when leaving tiv1

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#7775]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 118be4dea048df88fd21b84580fe62950c868c8f dirty (textinput: fix tiv3 leave (7761)).
Date: Fri Sep 13 00:41:24 2024
Tag: v0.43.0-19-g118be4de, commits: 5215

flags: (if any)
```

</details>

### Description

Same as issue #7757

### How to reproduce

1. Open vscode with `code --ozone-platform=wayland --enable-wayland-ime`, and open an xwayland client
2. After activating fcitx5 in vscode, switch to xwayland client to use fcitx5

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/7fb9332f-cff5-41fc-b84c-8b901b489526

**Comment by hdm9527** [comment]
@sungyoonc Same as issue #7753, but occurs on tiv1.

**Comment by sungyoonc** [comment]
> @sungyoonc Same as issue #7757, but occurs on tiv1.

Will check it out when I have time

**Comment by hdm9527** [comment]
> > @sungyoonc Same as issue #7757, but occurs on tiv1.
> 
> Will check it out when I have time

Thanks

**Comment by sungyoonc** [comment]
Try this.
[patch.txt](https://github.com/user-attachments/files/17005291/patch.txt)

**Comment by hdm9527** [comment]
> Try this. ~[patch.txt](https://github.com/user-attachments/files/17005291/patch.txt)~
> 
> edit: new patch [patch.txt](https://github.com/user-attachments/files/17005374/patch.txt)

No fix, still the same problem.

**Comment by sungyoonc** [comment]
Even with the new patch? In my side it's fixed with the repro step that is provided.

**Comment by hdm9527** [comment]
> Even with the new patch? In my side it's fixed with the repro step that is provided.

I forgot to patch it, it fixed this problem. Except that the position of imepopup is sometimes incorrect, no other problems were found.

**Comment by sungyoonc** [comment]
> > Even with the new patch? In my side it's fixed with the repro step that is provided.
> 
> I forgot to patch it, it fixed this problem. Except that the position of imepopup is sometimes incorrect, no other problems were found.

Yeah had that issue too, but dunno how to fix that. Anyways making a MR then.

**Comment by hdm9527** [comment]
> > > Even with the new patch? In my side it's fixed with the repro step that is provided.
> > 
> > 
> > I forgot to patch it, it fixed this problem. Except that the position of imepopup is sometimes incorrect, no other problems were found.
> 
> Yeah had that issue too, but dunno how to fix that. Anyways making a MR then.

The imepopup position problem seems to only exist in the wayland client. When the wayland client is opened or the window is switched, the imepopup position is not recalculated. I will open a new issue and see if you have any good ideas.
