### ISSUE TITLE
left_handed has no effect

### ISSUE THREAD

**Issue by mrshmllow** [hyprwm/Hyprland#778]
My mouse has changed to being left handed i _believe_ since https://github.com/hyprwm/Hyprland/commit/60c414ccadd0e2ff6be22bb880f605a164f451d5 & #776, and setting `left_handed = false` has no effect even after restarting

**Comment by mrshmllow** [comment]
Just ran a bisect- 
with `input:left_handed = false`, 60c414c is the first bad commit

**Comment by EvilBoi123** [comment]
yeah i got this problem too, now, by default my mouse were inverted rmb and lmb
