### ISSUE TITLE
Buffer overread on hyprpm enable

### ISSUE THREAD

**Issue by bodby** [hyprwm/Hyprland#7781]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
On mobile and can't access my PC yet, will add this once I can. Sorry.
```

</details>

### Description

Running hyprpm enable without anything after (no plugin name) prints a bunch of stuff unrelated to Hyprland; things like GCC compiler flags and a part of my PATH (as far as I remember).

Hyprpm disable does not have this problem; it does tell you that you haven't entered a valid plugin name.

Nothing else seems to happen when I do this though. Everything works as expected afterwards, though I haven't checked if there's a memory leak.

### How to reproduce

Write hyprpm update and see output.

### Crash reports, logs, images, videos

Will add output once I can. Sorry again.

**Comment by vaxerski** [comment]
![image](https://github.com/user-attachments/assets/fa893941-acdb-4318-ba25-faf86c01026b)
eee?

**Comment by bodby** [comment]
Try with a space after enable?

**Comment by vaxerski** [comment]
![image](https://github.com/user-attachments/assets/551ded4f-c1d8-46cc-b791-83247ef12eca)

nope

**Comment by bodby** [comment]
Looking at the CMakeLists shows this:

![image](https://github.com/user-attachments/assets/be7d5c59-3d8e-46e9-ae5a-a4de54cf1f34)

I usually only use -O2 and -Wall for all my packages; will try the options above soon.

**Comment by bodby** [comment]
Did not work. I'm on GCC 14 if that means anything, though it shouldn't matter.

**Comment by bodby** [comment]
Not on systemd. Can I compile with -ggdb (think it was that flag)? I'm not that familiar with debuggers. Or build systems in general.

I also can't get a debug target. I tried using cmake in hyprpm and in the base hyprland directory. Neither had a make debug option.

**Comment by vaxerski** [comment]
hyprland does have a debug target, see the wiki's debug instructions

you can launch hyprpm with `gdb` and then get it to crash and follow the instructions as for hyprland

**Comment by bodby** [comment]
I did follow but the makefile that CMake generates doesn't have a debug target. Could I still run with -ggdb and gdb somehow?

**Comment by bodby** [comment]
Sorry, have no time and I can't seem to get cmake to generate a debug target or provide a strace.
