### ISSUE TITLE
Hyprland crashes on startup.

### ISSUE THREAD

**Issue by AbooMinister25** [hyprwm/Hyprland#7791]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: 2024-06-25
Tag: v0.41.2, commits: 918d8340afd652b011b937d29d5eea0be08467f5

flags: (if any)


System Information:
System name: Linux
Node name: rayyanc-desktop
Release: 6.6.50
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun Sep  8 05:54:49 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] [10de:21c4] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240910.44a71ff"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:

======Config-Start======


Config File: /home/rcyclegar/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/rvr416z148cjcxh2bmf5anxpsdvmcvrk-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$mod=SUPER
bind=$mod, B, exec, firefox
bind=$mod, Return, exec, wezterm
bind=$mod, C, killactive
bind=$mod, Tab, focuscurrentorlast
bind=$mod, Left, workspace, r-1
bind=$mod, Right, workspace, r+1
bind=$mod, F, fullscreen
bind=$mod, X, togglefloating
bind=$mod, A, exec, ags -t applauncher
bind=$mod, code:10, workspace, 1
bind=$mod SHIFT, code:10, movetoworkspace, 1
bind=$mod, code:11, workspace, 2
bind=$mod SHIFT, code:11, movetoworkspace, 2
bind=$mod, code:12, workspace, 3
bind=$mod SHIFT, code:12, movetoworkspace, 3
bind=$mod, code:13, workspace, 4
bind=$mod SHIFT, code:13, movetoworkspace, 4
bind=$mod, code:14, workspace, 5
bind=$mod SHIFT, code:14, movetoworkspace, 5
bind=$mod, code:15, workspace, 6
bind=$mod SHIFT, code:15, movetoworkspace, 6
bind=$mod, code:16, workspace, 7
bind=$mod SHIFT, code:16, movetoworkspace, 7
bind=$mod, code:17, workspace, 8
bind=$mod SHIFT, code:17, movetoworkspace, 8
bind=$mod, code:18, workspace, 9
bind=$mod SHIFT, code:18, movetoworkspace, 9
bindm=$mod, mouse:273, resizewindow
bindm=$mod, mouse:272, movewindow
env=LIBVA_DRIVER_NAME, nvidia
env=XDG_SESSION_TYPE, wayland
env=GBM_BACKEND, nvidia-drm
env=__GLX_VENDOR_LIBRARY_NAME, nvidia
env=WLR_NO_HARDWARE_CURSORS, 1
exec-once=ags
exec-once=swaync
exec-once=systemctl --user start plasma-polkit-agent
monitor=DP-1, 2560x1440@165, auto, 1
monitor=HDMI-A-1, 1920x1080, auto-left, 1
monitor=Unknown-1, disable

======Config-End========
```

</details>

### Description

I'm using the hyprland flake on NixOS, and it's not starting whenever I start hyprland from the TTY, crashing with the following crash report:  https://pastebin.com/yyhB4YpN. I'm not exactly sure what's happening, I've tried using newer nvidia drivers, updating the flake, and so on.

### How to reproduce

My nix config looks like the following:

`flake.nix`
```nix
{
  inputs = {
    blah blah
    home-manager = blah blah;
    hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1";
  }
  outputs = { self, nixpkgs, blah blah, home-manager, hyprland)@inputs: {
    nixosConfigurations.me = nixpkgs.lib.nixosSystem {
      blah blah;
      specialArgs = { inherit inputs; };
      modules = [
        ./configuration.nix
        home-manager.nixosModules.home-manager
        {
          blah blah
        }
      ];
    };
  };
};
```

`home.nix`
```nix
{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
  }
}
```

`configuration.nix`
```nix
{
  programs.hyprland.enable = true;
  programs.hyprland.package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
  programs.hyprland.portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland
}
```

and I run `Hyprland` from the TTY.

### Crash reports, logs, images, videos

Here's the crash report: https://pastebin.com/yyhB4YpN

**Comment by rukmal** [comment]
+1 I'm having the same issue

**Comment by AbooMinister25** [comment]
I think I may have found the fix - I think it might be because the hyprland flake is a newer version than the one on nixpkgs, and so it uses the new AQ backend. Setting the `AQ_DRM_DEVICES` environment variable to the GPU you're running (in my case, it was `/dev/dri/card1`) fixed the issue, and I can now run hyprland.

@rukmal maybe this would work for you as well, I'm not sure if you're also running an nvidia GPU.

**Comment by rukmal** [comment]
@AbooMinister25 can you confirm that you also started seeing this issue after updating your kernel to 6.10.9? My crash report log is identical to yours, specifically:
```
[ERR] [AQ] drm: failed to parse edid
[LOG] [AQ] drm: Description    (Unknown-1)
[LOG] [AQ] drm: connector Unknown-1 crtc is incapable of vrr: props.vrr_capable -> 0, crtc->props.vrr_enabled -> 24
[LOG] [AQ] drm: Explicit sync unsupported
[LOG] [AQ] Starting the Aquamarine backend!
[LOG] [AQ] Starting the Wayland backend!
[ERR] [AQ] Wayland backend cannot start: wl_display_connect failed (is a wayland compositor running?)
[ERR] [AQ] Requested backend (wayland) could not start, enabling fallbacks
[ERR] [AQ] Implementation wayland failed, erasing.
[LOG] [AQ] Created a GBM allocator with drm fd 32
[LOG] [AQ] drm: Connectors size2 6
[LOG] [AQ] Created a GBM allocator with drm fd 136
```

I also reproduced the crash (just by switching around workspaces and launching some applications) with `hyprctl rollinglog -f >> out.log`, and I saw the following being printed continuously to the log file during the freeze:

```
[ERR] Failed to configure primary swapchain for Unknown-1
[ERR] renderer: couldn't beginRender()!
```

These two lines specifically repeat until I forced a reboot by holding down the power button. As I mentioned above, trying to launch a TTY in this state does not work, as the keyboard inputs are not being passed through.
```

**Comment by rukmal** [comment]
I'm on a ThinkPad laptop, so no NVIDIA card. I will try that now and get back.

**Comment by AbooMinister25** [comment]
> @AbooMinister25 can you confirm that you also started seeing this issue after updating your kernel to 6.10.9? My crash report log is identical to yours, specifically:
> 
> ```
> [ERR] [AQ] drm: failed to parse edid
> [LOG] [AQ] drm: Description    (Unknown-1)
> [LOG] [AQ] drm: connector Unknown-1 crtc is incapable of vrr: props.vrr_capable -> 0, crtc->props.vrr_enabled -> 24
> [LOG] [AQ] drm: Explicit sync unsupported
> [LOG] [AQ] Starting the Aquamarine backend!
> [LOG] [AQ] Starting the Wayland backend!
> [ERR] [AQ] Wayland backend cannot start: wl_display_connect failed (is a wayland compositor running?)
> [ERR] [AQ] Requested backend (wayland) could not start, enabling fallbacks
> [ERR] [AQ] Implementation wayland failed, erasing.
> [LOG] [AQ] Created a GBM allocator with drm fd 32
> [LOG] [AQ] drm: Connectors size2 6
> [LOG] [AQ] Created a GBM allocator with drm fd 136
> ```
> 
> I also reproduced the crash (just by switching around workspaces and launching some applications) with `hyprctl rollinglog -f >> out.log`, and I saw the following being printed continuously to the log file during the freeze:
> 
> ```
> [ERR] Failed to configure primary swapchain for Unknown-1
> [ERR] renderer: couldn't beginRender()!
> ```
> 
> These two lines specifically repeat until I forced a reboot by holding down the power button. As I mentioned above, trying to launch a TTY in this state does not work, as the keyboard inputs are not being passed through.

I'm currently on kernel version 6.6.50 - I've never updated, I only started having this issue once I switched over to using the hyprland flake, which shipped a newer version of hyprland than nixpkgs. Maybe try setting the environment variable and see how it goes?

**Comment by rukmal** [comment]
I just tried setting the environment variable accordingly (`card1` for me too, after checking the card). It does not work, and I'm still seeing the crash. I was able to pull the hyprland logs with `hyprctl rollinglog -f >> out.log`, and I'm seeing the same output:

```
[LOG] cursorImage request: surface 0
[LOG] Callback 7f1cf20 -> 7f1cf18, CPointerManager removed.
[LOG] Following log to socket: 117 started
[LOG] In followlog thread, got connection, start writing: 117
[LOG] RollingLogFollow, got 1 connections
[LOG] cursorImage request: shape 9 -> text
[LOG] Registered signal for owner 7f1ce40: 8d8d208 -> 7f1cef8 (owner: CPointerManager)
[LOG] Registered signal for owner 8fc0b50: 921f7b8 -> 8fc0b60 (owner: CRenderbuffer)
[LOG] Callback 8fc0b88 -> 8fc0b80, CRenderbuffer removed.
[LOG] Keybind triggered, calling dispatcher (65, , 50)
[LOG] Removing last node (dwindle)
[LOG] Searching for matching rules for kitty (title: zsh)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
[LOG] OPENINGON: [Node 8d18130: workspace: 2, pos: [0.00, 0.00], size: [0.00, 0.00], window: 91c3230], Monitor: 1
[LOG] Searching for matching rules for kitty (title: zsh)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
[LOG] Searching for matching rules for kitty (title: zsh)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
[LOG] Searching for matching rules for kitty (title: zsh)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
[LOG] Searching for matching rules for kitty (title: zsh)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
[LOG] Searching for matching rules for kitty (title: zsh)
[LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
[ERR] Failed to configure primary swapchain for Unknown-1
[ERR] renderer: couldn't beginRender()!
[ERR] Failed to configure primary swapchain for Unknown-1
[ERR] renderer: couldn't beginRender()!
[ERR] Failed to configure primary swapchain for Unknown-1
[ERR] renderer: couldn't beginRender()!
[ERR] Failed to configure primary swapchain for Unknown-1
[ERR] renderer: couldn't beginRender()!
[ERR] Failed to configure primary swapchain for Unknown-1
```

The 2 lines, beginning with `renderer:` and `Failed to configure` continue until I force a reboot. A new crash log is not generated in the `.cache/hyprland` directory either.

Are you also seeing a hard freeze (i.e. no change at all to the screen regardless of input) when it does crash?

When I revert to 6.10.6 I no longer see an issue. I'm wondering if something else changed in that time too. I'm using hyprland installed directly from nixpkgs, so am running:
```
Hyprland, built from branch main at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: 2024-06-25
Tag: v0.41.2, commits: 918d8340afd652b011b937d29d5eea0be08467f5
``` 

(This is unrelated to the issue at hand, but I don't think your flake is working! The `hyprland` repo is on version 0.43.0; you're still using the version from nixpkgs @AbooMinister25)

**Comment by AbooMinister25** [comment]
> I just tried setting the environment variable accordingly (`card1` for me too, after checking the card). It does not work, and I'm still seeing the crash. I was able to pull the hyprland logs with `hyprctl rollinglog -f >> out.log`, and I'm seeing the same output:
> 
> ```
> [LOG] cursorImage request: surface 0
> [LOG] Callback 7f1cf20 -> 7f1cf18, CPointerManager removed.
> [LOG] Following log to socket: 117 started
> [LOG] In followlog thread, got connection, start writing: 117
> [LOG] RollingLogFollow, got 1 connections
> [LOG] cursorImage request: shape 9 -> text
> [LOG] Registered signal for owner 7f1ce40: 8d8d208 -> 7f1cef8 (owner: CPointerManager)
> [LOG] Registered signal for owner 8fc0b50: 921f7b8 -> 8fc0b60 (owner: CRenderbuffer)
> [LOG] Callback 8fc0b88 -> 8fc0b80, CRenderbuffer removed.
> [LOG] Keybind triggered, calling dispatcher (65, , 50)
> [LOG] Removing last node (dwindle)
> [LOG] Searching for matching rules for kitty (title: zsh)
> [LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
> [LOG] OPENINGON: [Node 8d18130: workspace: 2, pos: [0.00, 0.00], size: [0.00, 0.00], window: 91c3230], Monitor: 1
> [LOG] Searching for matching rules for kitty (title: zsh)
> [LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
> [LOG] Searching for matching rules for kitty (title: zsh)
> [LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
> [LOG] Searching for matching rules for kitty (title: zsh)
> [LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
> [LOG] Searching for matching rules for kitty (title: zsh)
> [LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
> [LOG] Searching for matching rules for kitty (title: zsh)
> [LOG] Window rule suppressevent maximize ->  class:.* matched [Window 91c3230: title: "zsh"]
> [ERR] Failed to configure primary swapchain for Unknown-1
> [ERR] renderer: couldn't beginRender()!
> [ERR] Failed to configure primary swapchain for Unknown-1
> [ERR] renderer: couldn't beginRender()!
> [ERR] Failed to configure primary swapchain for Unknown-1
> [ERR] renderer: couldn't beginRender()!
> [ERR] Failed to configure primary swapchain for Unknown-1
> [ERR] renderer: couldn't beginRender()!
> [ERR] Failed to configure primary swapchain for Unknown-1
> ```
> 
> The 2 lines, beginning with `renderer:` and `Failed to configure` continue until I force a reboot. A new crash log is not generated in the `.cache/hyprland` directory either.
> 
> Are you also seeing a hard freeze (i.e. no change at all to the screen regardless of input) when it does crash?
> 
> When I revert to 6.10.6 I no longer see an issue. I'm wondering if something else changed in that time too. I'm using hyprland installed directly from nixpkgs, so am running:
> 
> ```
> Hyprland, built from branch main at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
> Date: 2024-06-25
> Tag: v0.41.2, commits: 918d8340afd652b011b937d29d5eea0be08467f5
> ```
> 
> (This is unrelated to the issue at hand, but I don't think your flake is working! The `hyprland` repo is on version 0.43.0; you're still using the version from nixpkgs @AbooMinister25)

I'm not seeing any freezes, hyprland just wouldn't start at all in the first place. I'd run `Hyprland` from the TTY, and it'd crash immediately.

Also, I can confirm I'm using the flake - my hyprland version isn't `41.2`, but built from the commit `d35e70a8c6599bb058cf86eb87c783ce1cf72471`. I believe that crash report is from when I pinned the flake to 41.2 for debugging purposes, but I am currently running off of the latest commit.

**Comment by rukmal** [comment]
Hm that's weird, especially considering our crash reports were identical.

@vaxerski any idea what could be going on here?

**Comment by idlip** [comment]
Is there any issue making you avoid latest version 0.43?

**Comment by vaxerski** [comment]
mesa bug to me, esp considering:
> Started having this issue after my kernel updated from 6.10.6 to 6.10.9

**Comment by jeikashu** [comment]
I'm having a similar issue, it crashes with this 
```
[LOG] [AQ] Starting the Aquamarine backend!
[LOG] [AQ] Starting the Wayland backend!
[ERR] [AQ] Wayland backend cannot start: wl_display_connect failed (is a wayland compositor running?)
[ERR] [AQ] Requested backend (wayland) could not start, enabling fallbacks
[ERR] [AQ] Implementation wayland failed, erasing.
[LOG] [AQ] Created a GBM allocator with drm fd 31
[LOG] [AQ] drm: Connectors size2 4
[LOG] [AQ] Created a GBM allocator with drm fd 135
```
at the end, both on 6.6.51 and 6.10.10 kernel

https://pastebin.com/vkkADKyL

**Comment by MitterdorferMathias** [comment]
I have the same issue:
NixOS Setup (24.05 stable channel) with 6.6.51 Kernel and a NVIDIA GeForce RTX 4070
Hyrland (and only this package) is included from NixOS unstable channel. With hyprland v0.42.0 it boots up correctly, with v0.43.0 it produces the same crash report as seen here (https://github.com/hyprwm/Hyprland/issues/7791#issuecomment-2351715408)

**Comment by vaxerski** [comment]
can you bisect then?

**Comment by MitterdorferMathias** [comment]
@vaxerski The commits causing the issue are:
- https://github.com/hyprwm/Hyprland/commit/4b5b8a763073593ac48af3bdcf04cf65b219120b
- https://github.com/hyprwm/Hyprland/commit/5b1375141bd77c26023fb4a8dc087272be82849a

As https://github.com/hyprwm/Hyprland/commit/4b5b8a763073593ac48af3bdcf04cf65b219120b crashes and https://github.com/hyprwm/Hyprland/commit/4af9410dc2d0e241276a0797d3f3d276310d956e starts as expected.

So i assume the bug is located in the modules referenced by the flakes.

**Comment by vaxerski** [comment]
can you build aq in debug and get a debug stacktrace? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by MitterdorferMathias** [comment]
@vaxerski Here the stacktrace of the crash:
```
(gdb) bt -full
#0  0x00007fe43406d7dc in __pthread_kill_implementation () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#1  0x00007fe43401b516 in raise () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#2  0x00007fe434003935 in abort () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#3  0x0000000000627f44 in handleUnrecoverableSignal(int) ()
No symbol table info available.
#4  <signal handler called>
No symbol table info available.
#5  0x00007fe43415495c in __strlen_evex () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#6  0x00007fe434082d32 in strdup () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#7  0x00007fe42678daca in dri2_initialize_drm () from /nix/store/sqg9g1xw98fy3cmh59jhp8x0k164d9y0-mesa-24.0.7-drivers/lib/libEGL_mesa.so.0
No symbol table info available.
#8  0x00007fe426785900 in dri2_initialize () from /nix/store/sqg9g1xw98fy3cmh59jhp8x0k164d9y0-mesa-24.0.7-drivers/lib/libEGL_mesa.so.0
No symbol table info available.
#9  0x00007fe4267774a8 in eglInitialize () from /nix/store/sqg9g1xw98fy3cmh59jhp8x0k164d9y0-mesa-24.0.7-drivers/lib/libEGL_mesa.so.0
No symbol table info available.
#10 0x00007fe434df7ab1 in Aquamarine::CDRMRenderer::attempt (allocator_=..., backend_=...) at /build/9pbjdm4azs943sqdwb02z9miywj0i5fx-source/src/backend/drm/Renderer.cpp:270
        renderer = {impl_ = 0x1306dd30}
        EGLEXTENSIONS = {_M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x13017820 "EGL_EXT_platform_base EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_KHR_platform_x11 EGL_EXT_pla"...}, _M_string_length = 401, {_M_local_buf = "\221\001\000\000\000\000\000\000\003\000\000\000\000\000\000", _M_allocated_capacity = 401}}
        attrs = {<std::_Vector_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<int>> = {<std::__new_allocator<int>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data> = {_M_start = 0x1306e070, _M_finish = 0x1306e074, _M_end_of_storage = 0x1306e074}, <No data fields>}}, <No data fields>}
        major = -797586400
        minor = 32766
        EGLEXTENSIONS2 = {_M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1306ddb0 "P\351\3454\344\177"}, _M_string_length = 316570256, {_M_local_buf = "6\000\000\000\000\000\000\000\023\311\a4\344\177\000", _M_allocated_capacity = 54}}
#11 0x00007fe434dd47f0 in Aquamarine::CDRMBackend::initMgpu (this=this@entry=0x12e75c20) at /build/9pbjdm4azs943sqdwb02z9miywj0i5fx-source/src/backend/drm/DRM.cpp:516
        newAllocator = {impl_ = 0x1306ddb0}
#12 0x00007fe434ddf0d4 in Aquamarine::CDRMBackend::onReady (this=0x12e75c20) at /build/9pbjdm4azs943sqdwb02z9miywj0i5fx-source/src/backend/drm/DRM.cpp:895
No locals.
#13 0x00007fe434da7846 in Aquamarine::CBackend::start (this=0x12de7b90) at /build/9pbjdm4azs943sqdwb02z9miywj0i5fx-source/src/backend/Backend.cpp:166
        b = @0x12e49430: {impl_ = 0x12e53fb0}
        __for_range = @0x12de7d48: {<std::_Vector_base<Hyprutils::Memory::CSharedPointer<Aquamarine::IBackendImplementation>, std::allocator<Hyprutils::Memory::CSharedPointer<Aquamarine::IBackendImplementation> > >> = {_M_impl = {<std::allocator<Hyprutils::Memory::CSharedPointer<Aquamarine::IBackendImplementation> >> = {<std::__new_allocator<Hyprutils::Memory::CSharedPointer<Aquamarine::IBackendImplementation> >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<Hyprutils::Memory::CSharedPointer<Aquamarine::IBackendImplementation>, std::allocator<Hyprutils::Memory::CSharedPointer<Aquamarine::IBackendImplementation> > >::_Vector_impl_data> = {_M_start = 0x12e49420, _M_finish = 0x12e49438, _M_end_of_storage = 0x12e49440}, <No data fields>}}, <No data fields>}
        __for_begin = <optimized out>
        __for_end = <optimized out>
        fallback = <optimized out>
        started = <optimized out>
        optionsForType = <optimized out>
#14 0x00000000006442c1 in CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) ()
No symbol table info available.
#15 0x00000000005cbb7d in main ()
No symbol table info available.
```

**Comment by vaxerski** [comment]
tbh I fail to see how that happened, something in drm itself imploded

**Comment by MitterdorferMathias** [comment]
@vaxerski OK, how can we proceed then?

**Comment by vaxerski** [comment]
dunno, I don't have this. Post a trace log https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log

**Comment by MitterdorferMathias** [comment]
@vaxerski here the trace log

[hyprland.log](https://github.com/user-attachments/files/17185699/hyprland.log)

**Comment by vaxerski** [comment]
isnt that the nvidia bug on recent drivers?

**Comment by akselander** [comment]
> mesa bug to me, esp considering:

I had this issue on Lenovo Thinkpad T14 with following hardware/drivers:

```
c4:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 (rev d0) (prog-if 00 [VGA controller])
        Subsystem: Lenovo Device 50ee
        Flags: bus master, fast devsel, latency 0, IRQ 42, IOMMU group 16
        Memory at 2c00000000 (64-bit, prefetchable) [size=256M]
        Memory at 90000000 (64-bit, prefetchable) [size=2M]
        I/O ports at 1000 [size=256]
        Memory at 90500000 (32-bit, non-prefetchable) [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
```

I followed the docs at [NixOS flakes section](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/) about mesa version mismatch. After adding these patches my Hyprland could finally start with version 0.44.0.

**Comment by MitterdorferMathias** [comment]
@akselander Thanks, this also fixes it for me :+1: .
As I was using only Hyprland from the unstable NixOS channel, I also had to use the unstable OpenGL mesa drivers.

**Comment by 34j** [comment]
> > mesa bug to me, esp considering:
> 
> I had this issue on Lenovo Thinkpad T14 with following hardware/drivers:
> 
> ```
> c4:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 (rev d0) (prog-if 00 [VGA controller])
>         Subsystem: Lenovo Device 50ee
>         Flags: bus master, fast devsel, latency 0, IRQ 42, IOMMU group 16
>         Memory at 2c00000000 (64-bit, prefetchable) [size=256M]
>         Memory at 90000000 (64-bit, prefetchable) [size=2M]
>         I/O ports at 1000 [size=256]
>         Memory at 90500000 (32-bit, non-prefetchable) [size=512K]
>         Capabilities: <access denied>
>         Kernel driver in use: amdgpu
>         Kernel modules: amdgpu
> ```
> 
> I followed the docs at [NixOS flakes section](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/) about mesa version mismatch. After adding these patches my Hyprland could finally start with version 0.44.0.

Same here, as this issue is more than "experiencing lag and FPS drops" which is stated in the documentation, it would be nice if the documentation could be fixed
