### ISSUE TITLE
ArmCord freezes when someone calls

### ISSUE THREAD

**Issue by FormunaGit** [hyprwm/Hyprland#7792]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: shomachine
Release: 6.10.8-200.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Wed Sep  4 21:41:11 UTC 2024


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Tiger Lake-LP GT2 [UHD Graphics G4] [8086:9a78] (rev 03) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde


plugins:
```

</details>

### Description

Whenever someone calls me in Discord while I have the ArmCord client opened, the ArmCord client completely "freezes" - I can't interact with it, but the call music and chats still update.

### How to reproduce

> be me
> install hyprland on fedora 40 and configure some stuff on it
> friend calls me
> armcord is now a music jackbox

**Comment by FormunaGit** [comment]
Calling seems to work on the browser version, microphone works OOTB, only issue is the little window that shows that a tab is using my microphone gets treated as its own window, although I can always just send it to the shadow realm (the 10th workspace)

**Comment by vaxerski** [comment]
very old version + my guess is missing notif daemon
