### ISSUE TITLE
Stuck on Desktop, no elements, only wallpaper

### ISSUE THREAD

**Issue by piLovr** [hyprwm/Hyprland#7795]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
(Thats the output of hyprctl systeminfo -c, obviously in another desktopEnv while Hyprland is running, since I cannot open the terminal in Hyprland. Maybe messed up here, let me know if you need info and how I can provide it)

### Description

I can't interact with the system at all, besides pressing meta+m, in that case it crashes.
Tried yay install, official build, legacyrenderdebug build, always the same error

I can only see the wallpaper, nothing else. (See screenshot (made in another DE since running Hyprland is visible in a window here))

### How to reproduce

git clone --recurse-submodules -j8 https://github.com/hyprwm/Hyprland.git
make legacyrendererdebug

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/17004239/hyprland.log)
config file is default, only debug variables changed.

Screenshot in next message, messed up

**Comment by piLovr** [comment]
![Screenshot-2024-09-15-03:21:06](https://github.com/user-attachments/assets/b9e91f0c-6c92-49b8-b9eb-4a028cc55ecc)

**Comment by Honkazel** [comment]
There's a hyprland config in ~/.config/hypr/
For debug hyprland it's hyprlandd.conf and for release build - hyprland.conf
Read your config, read the wiki, edit your config and that's all

**Comment by izmyname** [comment]
Install kitty terminal emulator, go to Hyprland and press meta+Q. If kitty is opened - everything is ok.

**Comment by piLovr** [comment]
> Install kitty terminal emulator, go to Hyprland and press meta+Q. If kitty is opened - everything is ok.

Sorry for the issue, ofc that was the "problem".
didn't expect hyprland install would be THAT minimalisic
