### ISSUE TITLE
2D workspaces

### ISSUE THREAD

**Issue by rabaimorp** [hyprwm/Hyprland#7799]
### Description

It would be cool and useful if workspaces would could open up and down as well as left and right. For me who uses **at least** 10 workspaces it would be easier to manage. It would make more sense to have 2 rows of 10 workspaces (or 4 rows of 5 workspaces), than a super long row of 20 workspaces. I would see this as a really unique optional feature. (also I can't imagine that I'm the first one who has this idea).

**Comment by fufexan** [comment]
What you're describing sounds like [hyprexpo](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprexpo) or Wayfire's overview plugin. As for the animations themselves, I don't know of a plugin that changes those.

**Comment by rabaimorp** [comment]
> What you're describing sounds like [hyprexpo](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprexpo) or Wayfire's overview plugin. As for the animations themselves, I don't know of a plugin that changes those.


No, I did not mean an overview. I meant that you could open new workspaces up and down as well, instead of just left and right, and scroll the same way as we normally switch workplaces. hyprexpo is completely different.

**Comment by vaxerski** [comment]
this is unrelated. How you treat the workspaces is up to you.

**Comment by rabaimorp** [comment]
> this is unrelated. How you treat the workspaces is up to you.

what? Of course it is what do you mean? What does this has to do with my idea? I'm not saying I can't live without this feature, but I thought it would be useful. Or you are saying that I can already do this?

**Comment by vaxerski** [comment]
you can already do this by scripting which way the animation should be played

**Comment by rabaimorp** [comment]
That's not what I meant though. I'm not talking about the animation. I'm talking about workspace dimensions. If I could have 4 workspaces next to my current one. (that's what I meant by up and down and left and right).

**Comment by fufexan** [comment]
That can also be scripted, or a plugin can be made to organize the workspaces "row" into a grid.

**Comment by vaxerski** [comment]
correct
