### ISSUE TITLE
XWayland drag-and-drop doesn't work

### ISSUE THREAD

**Issue by zukas97** [hyprwm/Hyprland#7800]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: zukas-gentoo
Release: 6.9.8-gentoo-x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sun Jul  7 00:53:15 -00 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] [1002:699f] (rev 81) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:

```

</details>

### Description

I can't drag and drop files to the Shotcut video editor but I can do it with Kdenlive. This is most likely not a shotcut problem because it works on sway. I am on Gentoo with shotcut 24.06.26. I have tried both xdph and xdp-wlr.

### How to reproduce

install shotcut and run it in Hyprland on Gentoo Linux.

**Comment by zukas97** [comment]
I didn't realize I also had the flatpak installed. It works fine on the system package. maybe this is a bug with the portals idk

**Comment by vaxerski** [comment]
is the flatpak version running in xwayland?

**Comment by marvix97** [comment]
> is the flatpak version running in xwayland?

I'm having the same issue with other xwayland programs so I installed the flatpak version of shotcut to check it out and yes, it is running in xwayland. 

I've also tried to run dolphin in xwayland (with QT_QPA_PLATFORM=xcb) to test xwl -> xwl drag and drop, but then I can't even initiate the dragging. 

Right now it seems that drag and drop works only for wl -> wl

I'm running hyprland-git from AUR, but the issue was also present in the stable hyprland package from the repos.

**Comment by vaxerski** [comment]
> Right now it seems that drag and drop works only for wl -> wl

that would be correct, we dont implement X11 dnd

**Comment by m2neral** [comment]
Sorry if this is necro. Do the changes in 0.46.0 affect this? I'm still unable to drag and drop from thunar to mpv, discord and brave while I can dnd from thunar to gimp, which is also wl to xwl afaik.

**Comment by vaxerski** [comment]
you can dnd only from wayland clients to xwayland ones.

**Comment by vaxerski** [comment]
I think the original post is about this so I think we can close this

**Comment by m2neral** [comment]
Discord, gimp, brave and mpv are all xwayland and thunar is wayland but I can only dnd from thunar to gimp in this list. If I'm the only one saying this then it might be an issue with my setup but I'll still leave this info here in case it's relevant and shut up.

**Comment by vaxerski** [comment]
how is mpv xwayland?

Anyways, everything with xwayland is dicey. From my experience DnD works most of the time. I've tested gimp, wine, and a small C test client, all seem to work. If your issues are reproducible on a default config, you cna open a new issue (as this one is indeed fixed, the support has been impl'd)
