### ISSUE TITLE
Blur on a layer is leaking into the shadows of the layer

### ISSUE THREAD

**Issue by yashranjan1** [hyprwm/Hyprland#7824]
I have an ags widget with an opacity of 0.85. It also has the following css attribute for a shadow which is:

```
box-shadow: 0 0 5px 2px rgba(0, 0, 0, 0.5);
```
when i tried to blur the layer with a layerrule, the blur seems to be applied to the shadow as well and I dont want it to be this way. I made sure to use ignorealpha as well and even tried different opacity settings. 

Config code that handles bluring
```
layerrule = blur, bar1
layerrule = blur, bar0
layerrule = ignorealpha[0.8], bar1
layerrule = ignorealpha[0.8], bar0
```

Im not sure what im doing wrong here and would really appreciate your assistance. Here is an image of what it looks like:
![image](https://github.com/user-attachments/assets/34d35963-452b-4a06-81ae-55df145194f4)

**Comment by vaxerski** [comment]
your syntax for ignorealpha is wrong, it should be `ignorealpha 0.8`

**Comment by yashranjan1** [comment]
Worked :+1: thanks a lot
