### ISSUE TITLE
Allow touch screen rotation

### ISSUE THREAD

**Issue by histausse** [hyprwm/Hyprland#783]
By default, my touch screen is rotated to the side. `monitor=DSI-1,transform,3` fixed the display, but the inputs are registered with a 90 degree rotation.
It looks like libinput can fix this using `libinput_device_config_calibration_set_matrix()` (https://wayland.freedesktop.org/libinput/doc/latest/absolute-axes.html#calibration-of-absolute-devices), but I did not find a way to configure it in hyprland.

It would be nice to have a way to set a calibration matrix, or a least to use the common ones presented in the documentation of libinput.

**Comment by vaxerski** [comment]
what's wrong with you

**Comment by vaxerski** [comment]
done in cee0645fd1e8f84438635483fd17007c077812fe
