### ISSUE TITLE
Infinity opening kitty

### ISSUE THREAD

**Issue by MrCybo** [hyprwm/Hyprland#7830]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
Idk
</details>

### Description

Hey guys, I have with infinite opening kitty and I don't know what to do. 
My PC:
Ryzen 5 2600
GTX 1060

### How to reproduce

I used Arch with nouveau nvidia drivers

**Comment by vaxerski** [comment]
what?

**Comment by MrCybo** [comment]
Kitty is infinity opening

**Comment by vaxerski** [comment]
excuse me?

**Comment by MrCybo** [comment]
kitty terminal emulator opens endlessly
(Sorry for bad English)

**Comment by vaxerski** [comment]
endlessly as in doesn't open or as in multiple windows are opened

**Comment by MrCybo** [comment]
Many windows open

**Comment by vaxerski** [comment]
I don't see how that's possible. I think it might be an issue on your end, as nobody else seems to have this problem

**Comment by MrCybo** [comment]
https://github.com/user-attachments/assets/9ab8dcb0-237f-4113-94cc-ceee6a064eaa

Hyprland is just installed

**Comment by vaxerski** [comment]
this just looks like some graphical corruption. Are you perhaps on legacy_renderer? might be blur (it doesn't work on aforementioned)

**Comment by MrCybo** [comment]
What is legacy_renderer? (I'm new in WM's)
I install it with archinstall

**Comment by MrCybo** [comment]
Still not working
I found error message:
To Wayland several display error: Broken pipe error: [org.freedesktop.DBud.Error.ServiceUnknown] The name is not activatable

**Comment by vaxerski** [comment]
that's not an error. Idk, something's wrong with your gpu drivers probably then

**Comment by MrCybo** [comment]
Can it be repaired with updates?

**Comment by vaxerski** [comment]
no clue, you seem to be the only one affected

**Comment by MrCybo** [comment]
OK. Thanks for try
