### ISSUE TITLE
hyprctl should return useful error codes

### ISSUE THREAD

**Issue by ppenguin** [hyprwm/Hyprland#7834]
### Description

If `hyprctl` would return useful error codes (instead of success for (almost?) everything), it would be _much_ more powerful to do one-line scripts. Now this has to be achieved by matching the "error" message as a string, like this one:

```sh
# toggle or start pavucontrol (e.g. as a waybar click action)
[[ $(hyprctl dispatch movetoworkspacesilent $(hyprctl -j activeworkspace | jq -r '.id'),address:$(hyprctl -j clients | jq -r '.[] | select(.class | test(".*pavucontrol")) | select(.workspace.id == 88) | .address')) =~ "not found" ]] && [[ $(hyprctl dispatch movetoworkspacesilent 88,address:$(hyprctl -j clients | jq -r '.[] | select(.class | test(".*pavucontrol")) | .address')) =~ "not found" ]] && pavucontrol
```

For the values of the error code to be returned for e.g. "window not found", we could e.g. borrow from [`sysexits.h`](https://stackoverflow.com/a/1535733/12771809), to make it at least somewhat standardised and not reinvent the wheel. In this particular case maybe `EX_NOUSER  67`.

**Comment by littleblack111** [comment]
https://github.com/hyprwm/hyprpaper/issues/202

**Comment by vaxerski** [comment]
yea, dup

**Comment by ppenguin** [comment]
Ok thanks (even though it probably belongs in `hyprctl` and not in `hyprpaper`? But whatever makes people happy I guess...)

**Comment by littleblack111** [comment]
yes @vaxerski i think hyprland should be the repo that this issue should be on, since hyprctl is from it...

**Comment by vaxerski** [comment]
it's both.

**Comment by littleblack111** [comment]
yes, true, its both
