### ISSUE TITLE
When a floating group is focused, add new windows to it

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#7840]
### Description

I wish that when a floating grouped window is focused, new windows would be added to the group instead of creating a new standalone window. [This behavior is present on tiling grouped windows already.](https://github.com/hyprwm/Hyprland/blob/e6cf643f5ab1c1545fb858ab1fd9d7538ef9e0f3/src/layout/DwindleLayout.cpp#L343-L360)

This would be a huge improvement to the floating grouped windows workflow. Also adds consistency with the tiling worflow.

Cheers!

**Comment by Aqa-Ib** [comment]
How can we check if a floating window is grouped?

**Comment by Aqa-Ib** [comment]
where is the code that allows floating windows to be grouped ?

**Comment by Aqa-Ib** [comment]
Am I tripping ?
```
void IHyprLayout::onWindowCreatedFloating(PHLWINDOW pWindow) {

  if (pWindow->m_sGroupData.pNextWindow.lock()) {  
        static auto USECURRPOS = CConfigValue<Hyprlang::INT>("group:insert_after_current");
        (*USECURRPOS ? pWindow.lock() : pWindow->getGroupTail())->insertWindowToGroup(pWindow);

        pWindow->setGroupCurrent(pWindow);
        pWindow->applyGroupRules();
        pWindow->updateWindowDecos();
        recalculateWindow(pWindow);

        if (!pWindow->getDecorationByType(DECORATION_GROUPBAR))
            pWindow->addWindowDeco(std::make_unique<CHyprGroupBarDecoration>(pWindow));

        return;

  }

```

**Comment by vaxerski** [comment]
see dwindle@344

**Comment by Aqa-Ib** [comment]
I have made this change on MasterLayout.cpp: `auto OPENINGON = getNodeFromWindow(g_pCompositor->m_pLastWindow.lock());`
Still it does not open the new windows in the floating group. Why?
