### ISSUE TITLE
terminal opened with exec-once is unresponsive

### ISSUE THREAD

**Issue by MysticFlowChart** [hyprwm/Hyprland#7841]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.10.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000
```

</details>

### Description

I use `exec-once = $terminal` in my config to save a keypress on startup.

Ever since 0.43 the terminal is spawned on my secondary monitor in workspace 2 and is unresponsive until I switch away from and then back to that workspace or spawn any other program.
This also happens regardless of the terminal emulator used since I tried Kitty, Alacritty and Foot all with the same results.

~~I bisected the issue and got 511eea71c60e10f3d3d757a376f1ca98b9034ae0 is the first bad commit (It's the first time I bisect an issue so I hope I did it right)~~

Edit:
Forgot to say, If I just leave the terminal on second monitor and start mashing keys it suddenly becomes responsive again after 5-10 seconds, so it's possible that the terminal spawning on the wrong monitor and it being unresponsive are 2 different issues.

Edit2:
I just had the terminal hang for several minutes, at which point I just closed and opened a new one. I can't seem to find a pattern for the unresponsiveness, later I'll try to bisect that too.

Edit3:
I'm dumb, disregard the part about spawning on the second monitor, it's fixed in latest git and should have tried that sooner.

I bisected the terminal being unresponsive and got 4fdc0d55e4b44bb5300679025d2378fb6de0cae4 is the first bad commit.

### How to reproduce

- add `exec-once = $terminal` to your config, where $terminal is a terminal of your choice
- launch Hyprland
- try to type on said terminal

**Comment by vaxerski** [comment]
I dont think the bisect is right. Maybe it's random?

**Comment by tannerellen** [comment]
I'm curious if you move your mouse or switch workspaces and back, if your terminal becomes responsive? I have Hyprland open to Firefox and my keyboard is unresponsive in the app until I move my mouse or switch workspaces. 

I suspect your issue isn't that your terminal isn't unresponsive it's that the app behaves as if it doesn't have focus.

I think that's the bug. The app isn't in focus on boot even though it visually shows that it is until you move the mouse or do another window operation of some kind. Check to see if that's the case for you.

**Comment by VirtCode** [comment]
can confirm that reverting that commit fixes it, sounds like the same issue as #7391 to me

**Comment by MysticFlowChart** [comment]
> I dont think the bisect is right. Maybe it's random?

I'll try to bisect again and see if I reach the same result, will post an edit as soon as I'm done

> I'm curious if you move your mouse or switch workspaces and back, if your terminal becomes responsive?

Yeah, as I mentioned switching workspaces or spawning anything else fixes the issue, so I'm inclined to believe that the app doesn't have focus even though it's visually behaving like it does (border lights up).

**Comment by vaxerski** [comment]
yes same as #7391
