### ISSUE TITLE
Steam nor discord starts on latest git

### ISSUE THREAD

**Issue by DockterTeagle** [hyprwm/Hyprland#7849]
### Discussed in https://github.com/hyprwm/Hyprland/discussions/7845

<div type='discussions-op-text'>

<sup>Originally posted by **DockterTeagle** September 18, 2024</sup>
Howdy,
I am writing this as a discussion as I am also unable to access discord atm due to a similar issue I believe. It seems that xwayland is somehow not being loaded or something, I am sure that I have it enabled in my nix config. The error I get when I try to start steam is this:
![2024-09-18T21:08:36,033994827-05:00](https://github.com/user-attachments/assets/9fffb42a-d056-4112-98ef-4a7afb30446c)

Also when I run discord from the command line I get this error
```
[WebContents] double crashed (reason: crashed, exitCode: 139)... RIP =(
notificationScreen.webContentsSend: win is invalid undefined.
```
i have made sure that mako is running so Idk what the issue could be for the time being I am going to revert to my previous generation, and try again this switch again in a few days to see if it has been fixed.
</div>

**Comment by khaneliman** [comment]
Same... I assume https://github.com/hyprwm/Hyprland/pull/7807

**Comment by ctilley83** [comment]
I'm curious if this is related to me suddenly getting no 'authorization protocol specified' errors when opening Xwayland applications. I'm also on the latest git.

**Comment by Morbiuzx** [comment]
I have this problem too

**Comment by Arisa-Snowbell** [comment]
it originally used ```c
std::format("/tmp/.X11-unix/X{}", display);
```
```c
        return std::format("/tmp/.X11-unix{}", display);
``` it was refactored to this

think this is the mistake

**Comment by DockterTeagle** [comment]
Damn Im surprised it took so little time to fix this, much appreciated.

**Comment by DockterTeagle** [comment]
I have had this issue resurface on the latest git

**Comment by DockterTeagle** [comment]
I cant seem to reproduce it again, so nevermind, I had this issue on latest git, switched to release, it went away, then switched back and it disappeared, no need to reopen
