### ISSUE TITLE
consider adding a way to move all workspaces on a monitor to another one

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#785]
something like `moveworkspacesfrommonitor X Y` where X is a monitor and Y a monitor, a direct or next/previous. That would allow to clean up everything on a monitor (useful when using `dpms off eDP-1` in a script)

**Comment by vaxerski** [comment]
kinda cringe

**Comment by primalmotion** [comment]
I can script something but then I would need to know the dpms status when calling hyprctl monitors

**Comment by primalmotion** [comment]
thanks, alien

**Comment by vaxerski** [comment]
11ce4689963f52a72817a9395ecccc1b034447a7

**Comment by primalmotion** [comment]
works. thanks!
