### ISSUE TITLE
Graphics corruption with AMD GPU and Linux 6.10.5+ regression

### ISSUE THREAD

**Issue by 0xC0ncord** [hyprwm/Hyprland#7850]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: bubbles
Release: 6.10.10-gentoo-hardened1
Version: #5 SMP Wed Sep 18 23:31:52 EDT 2024


GPU information: 
0c:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] [1002:744c] (rev cc) (prog-if 00 [VGA controller])
0d:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2080] [10de:1e82] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:

```

</details>

### Description

*(Please ignore the NVIDIA GPU in my hardware; it is for GPU passthrough via VFIO)*

After upgrading to Linux 6.10.5 or higher, I noticed severe graphical corruption (see below) in my setup: 2 4K monitors running at 144Hz connected to an AMD RX 7900 XT. I bisected this down to [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.10.y&id=150f56fffe2cc54eee671e1982f425130f88bb31) in the stable tree.

I also periodically switch to using KDE Plasma 6 on this system, and I never experienced this corruption before or after this kernel version there. To me this means Hyprland is doing something wrong.

I can reliably revert this commit in 6.10.10 and the problem goes away.

I can reproduce this issue regardless of the state of VRR, explicit sync, or direct scanout.

### How to reproduce

(Taking a guess, as it seems I'm the only one who has seen this)

1. Linux 6.10.5 or higher.
2. Two 4K monitors at 144Hz connected to an AMD GPU (RX 7900 XT).

### Crash reports, logs, images, videos

![PXL_20240918_193134452](https://github.com/user-attachments/assets/4d848177-b29c-48af-8989-e7c2887dda7a)

**Comment by 0xC0ncord** [comment]
Another thing to note: when this bug occurs, quitting Hyprland causes the system to hang.

**Comment by vaxerski** [comment]
I am not a kernel dev but they shouldnt break userspace so isnt this an amdgpu bug?

**Comment by vaxerski** [comment]
could be a kernel/mesa/amdgpu bug tbh, 6.10 has been a disaster for me on amd too and I've locked kernel to 6.9 for now

**Comment by 0xC0ncord** [comment]
It could be an amdgpu or Mesa bug. Forgive me as I'm not familiar with the Linux graphics stack at all, but wouldn't I be seeing this corruption on Plasma as well if that was the case?

**Comment by vaxerski** [comment]
@0xC0ncord

**Comment by 0xC0ncord** [comment]
I'll give this a spin on Linux 6.11 later today and see if I can still reproduce.

**Comment by 0xC0ncord** [comment]
> I'll give this a spin on Linux 6.11 later today and see if I can still reproduce.

I'm no longer seeing this problem on Hyprland 0.44.1, AQ 0.4.2, and Linux 6.11.4. Thanks!
