### ISSUE TITLE
musl support on Hyprland?

### ISSUE THREAD

**Issue by S41G0N** [hyprwm/Hyprland#7858]
### Description

Hyprland doesn't compile on musl systems (only on glibc systems). I only found some old issues that tried to patch very outdated versions. Are there any existing patches to compile the most recent versions of Hyprland on musl?

Will Hyprland ever consider adding musl support?

**Comment by vaxerski** [comment]
we don't officially support musl cuz nobody from the dev team uses musl. No plans for this to change
