### ISSUE TITLE
Can't start Hyprland 

### ISSUE THREAD

**Issue by xeyossr** [hyprwm/Hyprland#7873]
When I try to start Hyprland, I get the following error:

--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11(SEGV)
Version: 0f594732b063a90d44df8c5d402d658f27471dfe
Tag: v0.43.0
Date: Sun Sep 8 16:48:21 2024
Flags:

System info:
	System name: Linux
	Node name: abraa7v146
	Release: 6.10.10-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000

GPU:
	01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28a1] (rev a1) (prog-if 00 [VGA controller])

os-release:
	NAME="EndeavourOS"
	PRETTY_NAME="EndeavourOS"
	ID="endeavouros"
	ID_LIKE="arch"
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://endeavouros.com"
	DOCUMENTATION_URL="https://discovery.endeavouros.com"
	SUPPORT_URL="https://forum.endeavouros.com"
	BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
	PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
	LOGO="endeavouros"
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x5742f5e66e81]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xb88) [0x5742f5de6b78]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x5742f5d64581]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x7b73a435d1d0]
		??
		??:0
	#4 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0xa46866) [0x7b73a1e46866]
		??
		??:0
	#5 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0xa48f7d) [0x7b73a1e48f7d]
		??
		??:0
	#6 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0xa49b3d) [0x7b73a1e49b3d]
		??
		??:0
	#7 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0xfeef69) [0x7b73a23eef69]
		??
		??:0
	#8 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0x10581af) [0x7b73a24581af]
		??
		??:0
	#9 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0x105cd31) [0x7b73a245cd31]
		??
		??:0
	#1 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0x105cf0f) [0x7b73a245cf0f]
		??
		??:0
	#11 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0x105eee0) [0x7b73a245eee0]
		??
		??:0
	#12 | /usr/lib/libgallium-24.2.3-arch1.1.so(+0x2ce0c7) [0x7b73a16ce0c7]
		CKeybindManager::sendshortcut(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
		??:?
	#13 | Hyprland(_ZN15CHyprOpenGLImpl31renderTextureInternalWithDamageEN9Hyprutils6Memory14CSharedPointerI8CTextureEEPNS0_4Math4CBoxEfPNS5_7CRegionEibbbbNS2_I13CSyncTimelineEEm+0x763) [0x5742f60462f3]
		CHyprOpenGLImpl::renderTextureInternalWithDamage(Hyprutils::Memory::CSharedPointer<CTexture>, Hyprutils::Math::CBox*, float, Hyprutils::Math::CRegion*, int, bool, bool, bool, bool, Hyprutils::Memory::CSharedPointer<CSyncTimeline>, unsigned long)
		??:?
	#14 | Hyprland(_ZN15CHyprOpenGLImpl13renderTextureEN9Hyprutils6Memory14CSharedPointerI8CTextureEEPNS0_4Math4CBoxEfibb+0xc9) [0x5742f6046bb9]
		CHyprOpenGLImpl::renderTexture(Hyprutils::Memory::CSharedPointer<CTexture>, Hyprutils::Math::CBox*, float, int, bool, bool)
		??:?
	#15 | Hyprland(_ZN10CHyprError4drawEv+0x194) [0x5742f5e78d34]
		CHyprError::draw()
		??:?
	#16 | Hyprland(_ZN13CHyprRenderer13renderMonitorEP8CMonitor+0x1906) [0x5742f6064456]
		CHyprRenderer::renderMonitor(CMonitor*)
		??:?
	#17 | Hyprland(+0x2814eb) [0x5742f5e6a4eb]
		CMonitor::updateMatrix()
		??:?
	#18 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x7b73a4939c9f]
		??
		??:0
	#19 | /usr/lib/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ee) [0x7b73a493a00e]
		??
		??:0
	#2 | /usr/lib/libaquamarine.so.3(+0x9b027) [0x7b73a4fe5027]
		??
		??:0
	#21 | /usr/lib/libdrm.so.2(drmHandleEvent+0x130) [0x7b73a4c73f30]
		??
		??:0
	#22 | /usr/lib/libaquamarine.so.3(_ZN10Aquamarine11CDRMBackend14dispatchEventsEv+0x63) [0x7b73a4fe4283]
		??
		??:0
	#23 | Hyprland(+0x30ae3a) [0x5742f5ef3e3a]
		std::any::_Manager_internal<Hyprutils::Memory::CSharedPointer<CIdleInhibitor> >::_S_manage(std::any::_Op, std::any const*, std::any::_Arg*)
		??:?
	#24 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0x1f2) [0x7b73a4eee112]
		??
		??:0
	#25 | /usr/lib/libwayland-server.so.0(wl_display_run+0x37) [0x7b73a4ef01f7]
		??
		??:0
	#26 | Hyprland(_ZN17CEventLoopManager9enterLoopEv+0x282) [0x5742f5ef4b32]
		CEventLoopManager::enterLoop()
		??:?
	#27 | Hyprland(main+0xc80) [0x5742f5d21310]
		main
		??:?
	#28 | /usr/lib/libc.so.6(+0x25e08) [0x7b73a4345e08]
		??
		??:0
	#29 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7b73a4345ecc]
		??
		??:0
	#3 | Hyprland(_start+0x25) [0x5742f5d60815]
		_start
		??:?

Log tail:
[LOG] Process Created with pid 1059
[WARN] No rule found for eDP-1, trying to use the first.
[LOG] Applying monitor rule for eDP-1
[LOG] Setting preferred mode for eDP-1
[LOG] [AQ] legacy drm: Modesetting CRTC 62
[LOG] [AQ] legacy drm: Modesetting CRTC, mode: clock 353090 hdisplay 1920 vdisplay 1080 vrefresh 144
[LOG] [AQ] legacy drm: cursor fb: 33 with bo handle 1 from fd 258, size [Vector2D: x: 256, y: 256]
[LOG] output eDP-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] [AQ] drm: Modesetting eDP-1 with 1920x1080@144.00Hz
[ERR] [AQ] drm: Cannot commit when a page-flip is awaiting
[ERR] Couldn't commit output named eDP-1
[LOG] arrangeMonitors: 1 to arrange
[LOG] arrangeMonitors: eDP-1 auto [0, 0]
[LOG] arrangeMonitors: eDP-1 xwayland [0, 0]
[LOG] Monitor eDP-1 data dump: res 1920x1080@144.00Hz, scale 1.00, transform 0, pos 0x0, 10b 0
[hc] loadThemeStyle: loading for size 24
[hc] getShapesC: found 1 images for left_ptr
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 115
[hc] loadThemeStyle: loading for size 24
[hc] getShapesC: found 1 images for left_ptr
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 115
[LOG] [hookSystem] New hook event registered: render
[LOG] Monitor eDP-1 -> destroyed all render data
[LOG] Shaders initialized successfully.
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Creating a texture for BGTex
[LOG] Framebuffer created, status 36053
[ERR] createBGTextureForMonitor: failed, file "/usr/local/share/hypr/wall1.png" doesn't exist or access denied, ec: Success
[ERR] [GLES] Error in call at 153@Texture.cpp: 0x506
[LOG] [AQ] drm: Modesetting eDP-1 with 1920x1080@144.00Hz
[ERR] [AQ] drm: Cannot commit when a page-flip is awaiting
[ERR] [EGL] Command eglCreateSyncKHR errored out with EGL_BAD_ATTRIBUTE (0x12292): _eglCreateSync
[ERR] eglCreateSyncKHR failed
[WARN] Failed to change process scheduling strategy
[LOG] Hyprland init finished.
[LOG] Executing systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME PATH XDG_DATA_DIRS && hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORMTHEME PATH XDG_DATA_DIRS
[LOG] Process Created with pid 1062
[LOG] Running on WAYLAND_DISPLAY: wayland-1
[LOG] New aquamarine output with name HEADLESS-1
[LOG] New output with name FALLBACK
[hc] getShapesC: found 1 images for left_ptr
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 117
[LOG] Hyprland is ready, running the event loop!
[LOG] [AQ] backend: poll fd 11 for implementation headless
[LOG] [AQ] backend: poll fd 33 for implementation drm
[LOG] [AQ] backend: poll fd 12 for session
[LOG] [AQ] backend: poll fd 14 for session
[LOG] [AQ] backend: poll fd 15 for session
[LOG] [AQ] backend: poll fd 18 for idle
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 117
[LOG] [hookSystem] New hook event registered: tick
[LOG] [AQ] drm: Modesetting eDP-1 with 1920x1080@144.00Hz
[LOG] [AQ] legacy drm: Modesetting CRTC 62
[LOG] [AQ] legacy drm: Modesetting CRTC, mode: clock 353090 hdisplay 1920 vdisplay 1080 vrefresh 144
[LOG] [AQ] legacy drm: cursor fb: 33 with bo handle 1 from fd 258, size [Vector2D: x: 256, y: 256]
[ERR] [EGL] Command eglCreateSyncKHR errored out with EGL_BAD_ATTRIBUTE (0x12292): _eglCreateSync
[ERR] eglCreateSyncKHR failed
[LOG] [AQ] legacy drm: cursor fb: 33 with bo handle 1 from fd 258, size [Vector2D: x: 256, y: 256]
[ERR] [EGL] Command eglCreateSyncKHR errored out with EGL_BAD_ATTRIBUTE (0x12292): _eglCreateSync
[ERR] eglCreateSyncKHR failed

Can someone help me? It works fine on my other computer without RTX4050 Graphics card.

**Comment by vaxerski** [comment]
invalid issue, please follow the templates. 

Anyways, read the nvidia wiki page.
