### ISSUE TITLE
Add defaultName to "hyprctl workspacerules" output (and equivalent IPC response)

### ISSUE THREAD

**Issue by crsaracco** [hyprwm/Hyprland#7886]
### Description

Hi,

I'm currently playing around with Hyprland as a replacement for Sway, and I quickly ran into some issues replicating my Sway workflow in Hyprland while using Waybar.

Overall, Hyprland looks awesome, so I'm hoping I can shore up a few things and start using it as my daily driver soon.

### Original problem

I use persistent workspaces exclusively, 10 on each monitor. So I set up my workspaces in Hyprland similarly to how I did on Sway:

```
workspace = 10, defaultName:1/1, monitor:DP-3, persistent:true, default:true
workspace = 11, defaultName:1/2, monitor:DP-3, persistent:true
workspace = 12, defaultName:1/3, monitor:DP-3, persistent:true
workspace = 13, defaultName:1/4, monitor:DP-3, persistent:true
workspace = 14, defaultName:1/5, monitor:DP-3, persistent:true
workspace = 15, defaultName:1/6, monitor:DP-3, persistent:true
workspace = 16, defaultName:1/7, monitor:DP-3, persistent:true
workspace = 17, defaultName:1/8, monitor:DP-3, persistent:true
workspace = 18, defaultName:1/9, monitor:DP-3, persistent:true
workspace = 19, defaultName:1/0, monitor:DP-3, persistent:true

workspace = 20, defaultName:2/1, monitor:DP-1, persistent:true, default:true
workspace = 21, defaultName:2/2, monitor:DP-1, persistent:true
workspace = 22, defaultName:2/3, monitor:DP-1, persistent:true
workspace = 23, defaultName:2/4, monitor:DP-1, persistent:true
workspace = 24, defaultName:2/5, monitor:DP-1, persistent:true
workspace = 25, defaultName:2/6, monitor:DP-1, persistent:true
workspace = 26, defaultName:2/7, monitor:DP-1, persistent:true
workspace = 27, defaultName:2/8, monitor:DP-1, persistent:true
workspace = 28, defaultName:2/9, monitor:DP-1, persistent:true
workspace = 29, defaultName:2/0, monitor:DP-1, persistent:true
```

Waybar immediately shows these workspaces on the correct monitor whenever I save `hyprland.conf` (which is an awesome feature, btw), using my old Sway styling for persistent + empty workspaces, ***but*** there are a few problems:

 1. If I haven't moved to that workspace yet, Waybar just displays the workspace ID (eg. `10` or `25`), which isn't what I want.
 2. If I move to that workspace, Waybar now shows *two* different workspace buttons. Eg. if I move to `2/5` I'll have:
    - One workspace button for `24`, always styled as an empty + persistent workspace.
    - One workspace button for `2/5`, always styled as an active workspace containing windows. If I switch away from that workspace it sticks around and is still stylized as an active workspace containing windows, even if it's empty (which I assume I can fix later in Waybar somehow).

### Digging into the code

In sitting down to try to understand why this is happening, I took a look at what Waybar is doing and how it interacts with Hyprland to create these buttons. Here's what I came up with:

 - When first launching Waybar, to get the list of persistent workspaces from Hyprland, Waybar reads `hyprctl workspacerules` [here](https://github.com/Alexays/Waybar/blob/master/src/modules/hyprland/workspaces.cpp#L288). Seeing that there are persistent workspaces that Waybar hasn't tracked yet, it starts tracking them and creates buttons for them. However, Waybar [only gets the workspace ID](https://github.com/Alexays/Waybar/blob/master/src/modules/hyprland/workspaces.cpp#L297) and not the `defaultName` from `hyprctl workspacerules`, so that's what it has to use.
    - *(It does this via IPC instead of the actual terminal commands, but I'll treat these two things as if they are the same throughout the rest of this FR.)*
 - Whenever a workspace is created in Hyprland, Waybar reads `hyprctl workspaces` [here](https://github.com/Alexays/Waybar/blob/master/src/modules/hyprland/workspaces.cpp#L368). However, [now it gets the workspace name](https://github.com/Alexays/Waybar/blob/master/src/modules/hyprland/workspaces.cpp#L373), so Waybar uses that instead.
 - Since the workspace name and the workspace ID aren't the same, Waybar treats this as two different workspaces that it needs to track, seemingly causing my issue.

*(Definitely not an expert, just started looking into these two codebases today, could be wrong, yada yada yada.)*

### Proposed feature

Assuming I'm correct in how these two projects interact, it seems to me like the best path forward towards getting my workflow to work properly is the following:

 - Waybar should be tracking Hyprland workspaces by IDs under the hood, not by name. This way Waybar can read the configs *and* listen for other events (eg. workspace renames, etc), without having to translate through workspace names as a proxy, and the ID/name mismatch I described above won't break stuff.
    - I can make a FR on Waybar if someone confirms I'm correct on the interaction, and I could probably even take a swing at fixing it myself if Waybar devs OK the direction.
 - **Hyprland should include the `defaultName` in the `hyprctl workspacerules` [response](https://github.com/hyprwm/Hyprland/blob/main/src/debug/HyprCtl.cpp#L337), so that Waybar can immediately show the persistent workspace's name rather than having to show its ID whenever the workspace hasn't been created yet.**
    - I could maybe take a swing at this too if someone points me in the right direction. Does `src/debug/HyprCtl.cpp` actually feed into the IPC response as well? Or does this just control `hyprctl`?

### Backmatter

I also played around with the `name:foo` format of Hyprland workspace identifiers, and it actually gets me *closer* to my intended workflow. However, two problems there:

 1. Waybar seems to handle this much better at the moment: most of my workspaces will only ever have one button which is how it worked in Sway. However, for some reason (which I haven't stepped through the code to figure out quite yet), Waybar still indefinitely shows two buttons for my default persistent workspaces (eg. I'll have two `1/1` buttons on the one screen, and two `2/1` buttons on the other screen).
 2. I have less control over the ordering of my workspaces in Waybar. Eg: `1/0` and `2/0` always show up on the left of the workspace list, but I want the workspaces to be in "keyboard order" (eg. `1/1, 1/2, [...], 1/9, 1/0`) to match my workspace-related binds. From #665 and #4336, it looks like this is WAI and I should be using ID-based workspace identifiers if I want to be able to order "named" workspaces.
 
Either way:

 - It kinda just *feels* more-correct if Waybar tracks Hyprland workspaces by ID rather than name.
 - I feel like `hyprctl workspacerules` should probably just include the `defaultName` setting regardless, and it *seems* (?) like a small FR.

LMK if my workflow is actually supported via some other means and I'll go try it out :)

**Comment by vaxerski** [comment]
I aint readin allat but I can add defaultName to the output, sure.
