### ISSUE TITLE
Grim does not work

### ISSUE THREAD

**Issue by Kochanac** [hyprwm/Hyprland#7893]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: linuxnb-kveselov-PF2V2MCS
Release: 6.10.10-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:17:51 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/kochan/.config/hypr/hyprland.conf: Read Succeeded
#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,highres,0x1080,2,bitdepth,10

# UP
monitor=DP-1,highres,0x0,2,bitdepth,10
monitor=DP-2,highres,0x0,2,bitdepth,10
monitor=DP-3,highres,0x0,2,bitdepth,10

monitor= desc:BNQ BenQ GW2270 RCG05528SL0,highres,1920x0,1,bitdepth,10

monitor=HDMI-A-1,highres,1920x0,1,bitdepth,10
monitor=HDMI-A-1,highres,0x-1080,1,bitdepth,10

monitor= desc:Xiaomi Corporation Redmi 27 NU 3948623RM0FDD,highres,0x0,2,bitdepth,10

# Right
#monitor=DP-1,highres,1920x0,2,bitdepth,10
#monitor=DP-2,highres,1920x0,2,bitdepth,10
#monitor=DP-3,highres,1920x0,2,bitdepth,10


xwayland {
    force_zero_scaling = true
}

env = GDK_SCALE,2
env = XCURSOR_SIZE,24
#env = QT_SCALE_FACTOR,2


env = PATH,/home/kochan/.bun/bin/:$PATH
# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Set programs that you use
$terminal = konsole
$fileManager = dolphin
$menu = wofi --show drun

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us,ru
    kb_variant = ,mac
    kb_model = qwerty
    kb_options = grp:caps_toggle,altwin:swap_alt_win,altwin:menu_win
    kb_rules =

    touchpad {
        natural_scroll = yes
	scroll_factor = 0.8
    }

    follow_mouse = 2
    mouse_refocus = false
    float_switch_override_focus = 0
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

device {
	name = synps/2-synaptics-touchpad
	sensitivity = +0.35
}


general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 5
    border_size = 2
    gaps_workspaces = 100
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    resize_on_border = true

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    no_focus_fallback = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 7
    
    blur {
        enabled = false
        size = 3
        passes = 1
    }

    drop_shadow = no
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = kek, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, kek
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 3, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
    default_split_ratio = 1.3
    permanent_direction_override = yes
    smart_split = no
    force_split = 2
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    #new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = on
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
#    force_default_wallpaper = 2 # Set to 0 or 1 to disable the anime mascot wallpapers

    vfr = true
    focus_on_activate = false
    enable_swallow = false
}

binds {
	movefocus_cycles_fullscreen = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# WINDOW RULES

windowrulev2 = opacity 0.95 override 0.8 override,class:org.kde.konsole

windowrulev2 = float,title:Picture-in-Picture
windowrulev2 = pin,title:Picture-in-Picture

# ???? windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrule = center, class:jetbrains-idea

windowrulev2 = noanim, class:^(.*jetbrains.*)$

# windowrulev2=windowdance,class:^(jetbrains-.*)$
# search dialog
windowrulev2=dimaround,class:^(jetbrains-.*)$,floating:1,title:^(?!win)
windowrulev2=center,class:^(jetbrains-.*)$,floating:1, title:^(?!win)
# autocomplete & menus
#windowrulev2=noanim,class:^(jetbrains-.*)$
windowrulev2=noinitialfocus,class:^(jetbrains-.*)$, title:^(win.*)$
windowrulev2=rounding 0,class:^(jetbrains-.*)$,title:^(win.*)$


# Workspace binding

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1


workspace = 10, monitor:DP-1, monitor:DP-2
workspace = 11, monitor:DP-1, monitor:DP-2
workspace = 12, monitor:DP-1, monitor:DP-2
workspace = 13, monitor:DP-1, monitor:DP-2
workspace = 14, monitor:DP-1, monitor:DP-2
workspace = 15, monitor:DP-1, monitor:DP-2
workspace = 16, monitor:DP-1, monitor:DP-2
workspace = 17, monitor:DP-1, monitor:DP-2
workspace = 18, monitor:DP-1, monitor:DP-2
workspace = 19, monitor:DP-1, monitor:DP-2
workspace = 20, monitor:DP-1, monitor:DP-2

# HOTKEYS

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, return, exec, $terminal
bind = $mainMod, Q, killactive,
# bind = $mainMod, M, exit, 
# bind = $mainMod, E, exec, $fileManager
bind = $mainMod, X, fullscreen, 1
bind = $mainMod alt, X, fullscreen, 0
bind = ctrl alt, X, togglefloating, 

# bind = $mainMod, R, exec, $menu
bind = $mainMod, R, exec, ags -t launcher

bind = $mainMod alt, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = $mainMod, E, exec, /home/kochan/.config/wofi/itc.sh

# Move focus with mainMod + arrow keys
# bind = $mainMod, left, movefocus, l
# bind = $mainMod, right, movefocus, r
# bind = $mainMod, up, movefocus, u
# bind = $mainMod, down, movefocus, d

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# move to workspaces L/R
bind = ctrl alt shift, left, movetoworkspace, -1
bind = ctrl alt shift, right, movetoworkspace, +1
bind = $mainMod ctrl alt shift, left, movetoworkspace, -10
bind = $mainMod ctrl alt shift, right, movetoworkspace, +10

bind = ctrl alt shift, h, movetoworkspace, -1
bind = ctrl alt shift, l, movetoworkspace, +1

#bind = ctrl alt shift, up, movetoworkspace, +10
#bind = ctrl alt shift, down, movetoworkspace, -10

bind = ctrl alt shift, up, movewindow, mon:+1
bind = ctrl alt shift, down, movewindow, mon:-1



# resize
bind = $mainMod alt, right, resizeactive, 100 0
bind = $mainMod alt, left, resizeactive, -100 0
bind = $mainMod alt, up, resizeactive, 0 -100
bind = $mainMod alt, down, resizeactive, 0 100

bind = $mainMod alt, +, resizeactive, 100 100

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10


bind = ctrl alt, h, workspace, -1
bind = ctrl alt, l, workspace, +1
bind = ctrl alt, left, workspace, -1
bind = ctrl alt, right, workspace, +1
bind = $mainMod ctrl, left, workspace, -1
bind = $mainMod ctrl, right, workspace, +1
bind = $mainMod ctrl alt, left, workspace, -10
bind = $mainMod ctrl alt, right, workspace, +10


# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)hyprland/language
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
workspace = special:magic, gapsout:20 60 20 60

bind = $mainMod, D, togglespecialworkspace, magic2
bind = $mainMod SHIFT, D, movetoworkspace, special:magic2
workspace = special:magic2, gapsout:20 60 20 60

bind = $mainMod, A, togglespecialworkspace, magic3
bind = $mainMod SHIFT, A, movetoworkspace, special:magic3
workspace = special:magic3, gapsout:20 60 20 60

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# bind = ctrl, mouse:272, exec, notify-send kek

# clipboard 
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
bind = SUPER, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy


# INFRA
# exec-once = waybar # now ags

exec-once = ags
exec-once = dunst
exec-once = nm-applet
exec-once = exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = kdeconnect-indicator
exec-once = hyprpaper
exec-once = syncthing

# exec-once = hyprpm enable hyprexpo

# screenshot
bind = $mainMod, P, exec, grim -g "$(slurp -d)" - | wl-copy

# lock
bind = $mainMod, L, exec, hyprlock


bind = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = ,XF86MonBrightnessUp, exec, brightnessctl s 5%+
bind = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-

bind = alt,F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = alt,F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = alt,F4, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = alt,F5, exec, brightnessctl s 5%+
bind = alt,F6, exec, brightnessctl s 5%-




plugin {
    hyprexpo {
        columns = 3
        gap_size = 8
        bg_col = rgb(111111)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1

        enable_gesture = true # laptop touchpad
        gesture_fingers = 3  # 3 or 4
        gesture_distance = 300 # how far is the "max"
        gesture_positive = 0 # positive = swipe down. Negative = swipe up.
    }
}



======Config-End========

```

</details>

### Description

https://todo.sr.ht/~emersion/grim/97

```
❯ grim
[destroyed object]: error 0: Format invalid
failed to screenshoot all outputs
```

basically grim stopped working for me after 0.42.0.

<details><summary>WAYLAND_DEBUG=1 grim</summary>
<pre>
❯ WAYLAND_DEBUG=1 grim

[ 280912.413] {Default Queue}  -> wl_display#1.get_registry(new id wl_registry#2)
[ 280912.433] {Default Queue}  -> wl_display#1.sync(new id wl_callback#3)
[ 280912.623] {Display Queue} wl_display#1.delete_id(3)
[ 280912.635] {Default Queue} wl_registry#2.global(1, "wl_seat", 9)
[ 280912.644] {Default Queue} wl_registry#2.global(2, "wl_data_device_manager", 3)
[ 280912.650] {Default Queue} wl_registry#2.global(3, "wl_compositor", 6)
[ 280912.656] {Default Queue} wl_registry#2.global(4, "wl_subcompositor", 1)
[ 280912.662] {Default Queue} wl_registry#2.global(5, "wl_shm", 1)
[ 280912.670] {Default Queue}  -> wl_registry#2.bind(5, "wl_shm", 1, new id [unknown]#4)
[ 280912.678] {Default Queue} wl_registry#2.global(6, "wp_viewporter", 1)
[ 280912.684] {Default Queue} wl_registry#2.global(7, "wp_tearing_control_manager_v1", 1)
[ 280912.690] {Default Queue} wl_registry#2.global(8, "wp_fractional_scale_manager_v1", 1)
[ 280912.696] {Default Queue} wl_registry#2.global(9, "zxdg_output_manager_v1", 3)
[ 280912.705] {Default Queue}  -> wl_registry#2.bind(9, "zxdg_output_manager_v1", 2, new id [unknown]#5)
[ 280912.712] {Default Queue} wl_registry#2.global(10, "wp_cursor_shape_manager_v1", 1)
[ 280912.719] {Default Queue} wl_registry#2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[ 280912.725] {Default Queue} wl_registry#2.global(12, "zwp_relative_pointer_manager_v1", 1)
[ 280912.731] {Default Queue} wl_registry#2.global(13, "zxdg_decoration_manager_v1", 1)
[ 280912.737] {Default Queue} wl_registry#2.global(14, "wp_alpha_modifier_v1", 1)
[ 280912.744] {Default Queue} wl_registry#2.global(15, "zwlr_gamma_control_manager_v1", 1)
[ 280912.750] {Default Queue} wl_registry#2.global(16, "ext_foreign_toplevel_list_v1", 1)
[ 280912.756] {Default Queue} wl_registry#2.global(17, "zwp_pointer_gestures_v1", 3)
[ 280912.763] {Default Queue} wl_registry#2.global(18, "zwlr_foreign_toplevel_manager_v1", 3)
[ 280912.769] {Default Queue} wl_registry#2.global(19, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 280912.776] {Default Queue} wl_registry#2.global(20, "zwp_text_input_manager_v1", 1)
[ 280912.782] {Default Queue} wl_registry#2.global(21, "zwp_text_input_manager_v3", 1)
[ 280912.788] {Default Queue} wl_registry#2.global(22, "zwp_pointer_constraints_v1", 1)
[ 280912.794] {Default Queue} wl_registry#2.global(23, "zwlr_output_power_manager_v1", 1)
[ 280912.800] {Default Queue} wl_registry#2.global(24, "xdg_activation_v1", 1)
[ 280912.806] {Default Queue} wl_registry#2.global(25, "ext_idle_notifier_v1", 1)
[ 280912.812] {Default Queue} wl_registry#2.global(26, "ext_session_lock_manager_v1", 1)
[ 280912.818] {Default Queue} wl_registry#2.global(27, "zwp_input_method_manager_v2", 1)
[ 280912.825] {Default Queue} wl_registry#2.global(28, "zwp_virtual_keyboard_manager_v1", 1)
[ 280912.840] {Default Queue} wl_registry#2.global(29, "zwlr_virtual_pointer_manager_v1", 2)
[ 280912.847] {Default Queue} wl_registry#2.global(30, "zwlr_output_manager_v1", 4)
[ 280912.853] {Default Queue} wl_registry#2.global(31, "org_kde_kwin_server_decoration_manager", 1)
[ 280912.859] {Default Queue} wl_registry#2.global(32, "hyprland_focus_grab_manager_v1", 1)
[ 280912.865] {Default Queue} wl_registry#2.global(33, "zwp_tablet_manager_v2", 1)
[ 280912.871] {Default Queue} wl_registry#2.global(34, "zwlr_layer_shell_v1", 5)
[ 280912.877] {Default Queue} wl_registry#2.global(35, "wp_presentation", 1)
[ 280912.883] {Default Queue} wl_registry#2.global(36, "xdg_wm_base", 6)
[ 280912.889] {Default Queue} wl_registry#2.global(37, "zwlr_data_control_manager_v1", 2)
[ 280912.895] {Default Queue} wl_registry#2.global(38, "zwp_primary_selection_device_manager_v1", 1)
[ 280912.901] {Default Queue} wl_registry#2.global(39, "xwayland_shell_v1", 1)
[ 280912.908] {Default Queue} wl_registry#2.global(40, "zwlr_screencopy_manager_v1", 3)
[ 280912.915] {Default Queue}  -> wl_registry#2.bind(40, "zwlr_screencopy_manager_v1", 1, new id [unknown]#6)
[ 280912.922] {Default Queue} wl_registry#2.global(41, "hyprland_toplevel_export_manager_v1", 2)
[ 280912.929] {Default Queue} wl_registry#2.global(42, "hyprland_global_shortcuts_manager_v1", 1)
[ 280912.935] {Default Queue} wl_registry#2.global(43, "xdg_dialog_v1", 1)
[ 280912.941] {Default Queue} wl_registry#2.global(44, "wp_drm_lease_device_v1", 1)
[ 280912.947] {Default Queue} wl_registry#2.global(45, "wp_linux_drm_syncobj_manager_v1", 1)
[ 280912.953] {Default Queue} wl_registry#2.global(46, "wl_drm", 2)
[ 280912.959] {Default Queue} wl_registry#2.global(47, "zwp_linux_dmabuf_v1", 5)
[ 280912.965] {Default Queue} wl_registry#2.global(48, "wl_output", 4)
[ 280912.971] {Default Queue}  -> wl_registry#2.bind(48, "wl_output", 3, new id [unknown]#7)
[ 280912.979] {Default Queue} wl_registry#2.global(50, "wl_output", 4)
[ 280912.986] {Default Queue}  -> wl_registry#2.bind(50, "wl_output", 3, new id [unknown]#8)
[ 280912.993] {Default Queue} wl_callback#3.done(4790)
[ 280913.000] {Default Queue}  -> zxdg_output_manager_v1#5.get_xdg_output(new id zxdg_output_v1#3, wl_output#8)
[ 280913.008] {Default Queue}  -> zxdg_output_manager_v1#5.get_xdg_output(new id zxdg_output_v1#9, wl_output#7)
[ 280913.016] {Default Queue}  -> wl_display#1.sync(new id wl_callback#10)
[ 280913.185] {Display Queue} wl_display#1.delete_id(10)
[ 280913.192] {Default Queue} discarded wl_shm#4.format(0)
[ 280913.198] {Default Queue} discarded wl_shm#4.format(1)
[ 280913.203] {Default Queue} discarded wl_shm#4.format(808669761)
[ 280913.208] {Default Queue} discarded wl_shm#4.format(808669784)
[ 280913.213] {Default Queue} discarded wl_shm#4.format(808665665)
[ 280913.218] {Default Queue} discarded wl_shm#4.format(875708993)
[ 280913.224] {Default Queue} discarded wl_shm#4.format(875709016)
[ 280913.229] {Default Queue} wl_output#7.geometry(0, 0, 310, 170, 0, "California Institute of Technology", "0x1405", 0)
[ 280913.239] {Default Queue} wl_output#7.scale(2)
[ 280913.245] {Default Queue} wl_output#7.mode(1, 3840, 2160, 60000)
[ 280913.253] {Default Queue} wl_output#7.done()
[ 280913.258] {Default Queue} wl_output#8.geometry(0, 0, 600, 340, 0, "Xiaomi Corporation", "Redmi 27 NU", 0)
[ 280913.267] {Default Queue} wl_output#8.scale(2)
[ 280913.272] {Default Queue} wl_output#8.mode(1, 3840, 2160, 60000)
[ 280913.279] {Default Queue} wl_output#8.done()
[ 280913.284] {Default Queue} zxdg_output_v1#3.name("DP-3")
[ 280913.290] {Default Queue} zxdg_output_v1#3.description("Xiaomi Corporation Redmi 27 NU 3948623RM0FDD (DP-3)")
[ 280913.296] {Default Queue} zxdg_output_v1#3.logical_position(0, 0)
[ 280913.303] {Default Queue} zxdg_output_v1#3.logical_size(1920, 1080)
[ 280913.309] {Default Queue} zxdg_output_v1#3.done()
[ 280913.315] {Default Queue} zxdg_output_v1#9.name("eDP-1")
[ 280913.320] {Default Queue} zxdg_output_v1#9.description("California Institute of Technology 0x1405  (eDP-1)")
[ 280913.326] {Default Queue} zxdg_output_v1#9.logical_position(0, 1080)
[ 280913.333] {Default Queue} zxdg_output_v1#9.logical_size(1920, 1080)
[ 280913.339] {Default Queue} zxdg_output_v1#9.done()
[ 280913.344] {Default Queue} wl_callback#10.done(4790)
[ 280913.351] {Default Queue}  -> zwlr_screencopy_manager_v1#6.capture_output(new id zwlr_screencopy_frame_v1#10, 0, wl_output#8)
[ 280913.361] {Default Queue}  -> zwlr_screencopy_manager_v1#6.capture_output(new id zwlr_screencopy_frame_v1#11, 0, wl_output#7)
[ 280913.416] {Default Queue} zwlr_screencopy_frame_v1#10.buffer(808665688, 3840, 2160, 15360)
[ 280913.473] {Default Queue}  -> wl_shm#4.create_pool(new id wl_shm_pool#12, fd 5, 33177600)
[ 280913.483] {Default Queue}  -> wl_shm_pool#12.create_buffer(new id wl_buffer#13, 0, 3840, 2160, 15360, 808665688)
[ 280913.492] {Default Queue}  -> wl_shm_pool#12.destroy()
[ 280913.500] {Default Queue}  -> zwlr_screencopy_frame_v1#10.copy(wl_buffer#13)
[ 280913.507] {Default Queue} zwlr_screencopy_frame_v1#11.buffer(808665688, 3840, 2160, 15360)
[ 280913.532] {Default Queue}  -> wl_shm#4.create_pool(new id wl_shm_pool#14, fd 6, 33177600)
[ 280913.540] {Default Queue}  -> wl_shm_pool#14.create_buffer(new id wl_buffer#15, 0, 3840, 2160, 15360, 808665688)
[ 280913.548] {Default Queue}  -> wl_shm_pool#14.destroy()
[ 280913.555] {Default Queue}  -> zwlr_screencopy_frame_v1#11.copy(wl_buffer#15)
[ 280913.634] {Display Queue} wl_display#1.error(nil, 0, "Format invalid")
[destroyed object]: error 0: Format invalid
failed to screenshoot all outputs
</pre>
</details>

### How to reproduce

Try to screenshot anything using grim, hyprshot or anything else. 

I guess not everyone has this problem, so please help me get more diagnostic data to specify how to reproduce this

**Comment by Kochanac** [comment]
> 0.42.0.

This is from my memory, I didn't test this. But it certainly worked before in v0.41 and it doesn't in v0.43 now

**Comment by vaxerski** [comment]
does it work without 10b

**Comment by Kochanac** [comment]
you mean without `bitdepth,10`?

**Comment by Kochanac** [comment]
yes, if I remove `bitdepth,10`, it does work.

**Comment by vaxerski** [comment]
hm, odd, it does work just fine on my end. Can you try git?

**Comment by JassonCordones** [comment]
shall this be closed?
