### ISSUE TITLE
activelyTearing is always false on my Nvidia setup

### ISSUE THREAD

**Issue by itouchdennis** [hyprwm/Hyprland#7900]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

-

### System Info and Version

Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)

System Information:
System name: Linux
Node name: dat-ms
Release: 6.10.10-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:17:51 +0000

GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Ti] [10de:2482] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:

======Config-Start======

Config File: /home/dat/.config/hypr/hyprland.conf: Read Succeeded

general {
  allow_tearing = true
  sensitivity = 1.00
  border_size = 2
  apply_sens_to_raw = 1
  gaps_in = 6
  gaps_out = 8

  resize_on_border = true

  col.active_border = #7303fc
  col.inactive_border = $backgroundCol

  layout = dwindle
}

$configs = $HOME/.config/hypr/configs

source=$configs/Settings.conf
source=$configs/Keybinds.conf

$UserConfigs = $HOME/.config/hypr/UserConfigs

source= $UserConfigs/Startup_Apps.conf
source= $UserConfigs/ENVariables.conf
#source= $UserConfigs/Monitors.conf
#source= $UserConfigs/Laptops.conf
#source= $UserConfigs/LaptopDisplay.conf
source= $UserConfigs/WindowRules.conf
source= $UserConfigs/UserKeybinds.conf
source= $UserConfigs/UserSettings.conf
source= $UserConfigs/WorkspaceRules.conf

##Homeoffice
monitor=DP-1, 3440x1440@164.89000,0x0,1

#3440x1440@164.89000
monitor=HDMI-A-1,1920x1080@165.00301,830x-1080, 1,transform,2
#monitor=HDMI-A-1,disabled
workspace=1,monitor:DP-1
workspace=2,monitor:DP-1
workspace=3,monitor:DP-1
workspace=4,monitor:DP-1

workspace=5,monitor:HDMI-A-1

exec-once = /home/dat/scripts/autostart_hyprland.sh
exec-once = waybar &|

exec-once = solaar -w hide > /dev/null &
exec-once = sleep 1 && sudo systemctl restart arduino-connect.service
exec-once = steam -silent

exec-once=hyprctl dispatch workspace 1

windowrulev2 = workspace 4, class:^(steam)$

windowrulev2 = workspace 4, title:^(Friends List)$

windowrulev2 = immediate,fullscreen:1
#windowrulev2 = immediate, title:^(Counter-Strike 2)$
windowrulev2 = float, class:^([Ss]team)$,title:^((?![Ss]team).*|[Ss]team [Ss]ettings)$
windowrulev2 = workspace 3, title:^(Counter-Strike 2)$

windowrulev2 = workspace 3, class:^(steam_app\d+)$
windowrulev2 = workspace 3, class:^(steam_app_1551360)$

Config File: /home/dat/.config/hypr/configs/Settings.conf: Read Succeeded

exec-once = $HOME/.config/hypr/initial-boot.sh

Config File: /home/dat/.config/hypr/UserConfigs/Startup_Apps.conf: Read Succeeded

#Commands & Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh

exec-once = swww-daemon --format xrgb
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $scriptsDir/Polkit.sh
exec-once = waybar &
exec-once = nm-applet --indicator &
exec-once = swaync &
exec-once = ags &
#exec-once = blueman-applet &
#exec-once = rog-control-center &

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hypridle &
persistent wallpaper

Config File: /home/dat/.config/hypr/UserConfigs/ENVariables.conf: Read Succeeded

env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm

env = NVD_BACKEND,direct
env = __VK_LAYER_NV_optimus,NVIDIA_only
env = DRI_PRIME,pci-0000_01_00_0
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = CLUTTER_BACKEND,wayland
#env = GDK_BACKEND,wayland,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = WLR_DRM_NO_ATOMIC,1

Config File: /home/dat/.config/hypr/UserConfigs/WindowRules.conf: Read Succeeded
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
	vfr = true
  vrr = 0
  mouse_move_enables_dpms = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
  focus_on_activate = false
  #no_direct_scanout = true #for fullscreen games
  initial_workspace_tracking = 0
  middle_click_paste = false
}

xwayland {
  force_zero_scaling = true
}

cursor {
  no_hardware_cursors = false
  enable_hyprcursor = true
  warp_on_change_workspace = true # for -git or Hyprland >v0.41.1
}
------------------------------------------------------------------------------------------
### Description

First thing:

Yes I have the allow tearing var + immediate windowrule set up (for fullscreen apps, I also tried to catch the window directly for a game, in my case CS2, the class selector works, as I also let the game launch on a different workspace)

Plus I have set up the nvidia related stuff (obv. if something isn't working it must be a nvidia setup).

If I start e.g. CS2 and look at the second screen (watch -n hyprctl monitors)

I can see, that the activelyTearing is false - which should be true!

The game is set to fullscreen (not fake fullscreen), also other games like Forza don't trigger the activelyTearing var of my monitor, which causes stuttering if I hit more then my monitors HZ as refresh rate.

My Setup overall:

- NVidia 3070 ti Latest driver [560.35.03](https://www.nvidia.com/de-de/drivers/details/230926/)
- 12600k
- Hyprland 41.2 / 43 (I switch between these versions as it seems like on 41.2 with wl roots included my setup will work a bit smoother as on 43, especially for Counter Strike + the sunshine /moonlight fake worskapce / screen setup is working here - I am willing to switch to the newest one if CS works fine on my setup / tearing should be the trick, the sunshine / moonlight setup is more  a testing thing)
- 6.10 Zen Kernel
- 2 Monitors

I can't get it working to set this to true. Any help would be glad, maybe I am missing something... I also tried other games e.g. via lutris.

Dang it Nvidia y r u like this

PS: I think its like this kind of this issue:
https://github.com/hyprwm/Hyprland/issues/4935
But I can not reproduce what was written in here to get it working..

Anyway - any help or suggestion highly appreciated! I am out of knowledge at this point.... 
PPS: I hope this report is halfway okay-ish? Tried to remove a lot of unnecessary configs to make this halfway clear... 

### How to reproduce

Have a Nvidia card with current driver, start a game, watch on 2. monitor the output of hyprctl monitors and see that tearing is still disabled, which causes stutters when hitting a higher framerate then the HZ on the monitor.

**Comment by vaxerski** [comment]
that's a very old hyprland version. Please try git. Also make sure `solitary` in monitors doesn't show up as 0

**Comment by itouchdennis** [comment]
Will check it later this day.

**Comment by itouchdennis** [comment]
> that's a very old hyprland version. Please try git. Also make sure `solitary` in monitors doesn't show up as 0



The game feels completely choppy on 43.0 - even when I lock the game on my / under my displays HZ / FPS. 
On 41.2 its running okay-ish when I lock the FPS direct to the HZ of the monitor.  If I get it to manage tearing working Ill ditch the old version.. 

I Tried the git version (43.0-61), same problem, game is fullscreen on one screen , on the other via sleep / watch the output:

![swappy-20240925-210210](https://github.com/user-attachments/assets/7071e5fd-1a80-4317-bfd1-49055a4e6d37)
(Its the DP-1)

Is it normal that the client says its floating while in fullscreen? 

How do I check the solitary? The hyperctl monitors command doesnt seem like to provide me the needed info.

I am grateful for any advice / tip (unless its ditch nvidia and buy an AMD, it might be come some day but not so far..)!

**Comment by vaxerski** [comment]
> Is it normal that the client says its floating while in fullscreen?

probably

> The game feels completely choppy on 43.0

could be nvidia being nvidia, try disabling explicit sync?

> How do I check the solitary?

it was added today, recompile latest git.

**Comment by itouchdennis** [comment]
Checked out the newest version. 
Solitary = 0   (how can I change this?)

Tried turning off explicit sync, the game feels a bit better when not hitting above the HZ of the display. 

tearing still not allowed. Yeah I think its mostly caused by nvidia

**Comment by vaxerski** [comment]
solitary not passing means direct scanout isnt possible which means tearing won't happen
