### ISSUE TITLE
Syntax for combining keybinds with similar functionality.

### ISSUE THREAD

**Issue by neddey** [hyprwm/Hyprland#7904]
### Description

A form of syntax to combine multiple key-binds into one line, like in sxhkd.
I.E instead of having
```
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
```
You could have
```
bind = $mainMod, {left,right,up,down}, movefocus, {l,r,u,d}
```

**Comment by vaxerski** [comment]
no. Parsing would be borderline impossible considering the last param in bind can be literally whatever

**Comment by neddey** [comment]
If a list of option is provided it would be relatively simple. This also isn't even a new idea, SXHKD does exactly this.

**Comment by vaxerski** [comment]
doesn't mean hyprland has to.

> If a list of option is provided it would be relatively simple

We don't really have a "list of options" for keys.

**Comment by neddey** [comment]
The user can easily provide a list of keys. You can say you don't want to do it, that's fine, but saying it's "borderline impossible" is clearly wrong unless something is getting lost in translation.
