### ISSUE TITLE
Invalid monitor description with json flag

### ISSUE THREAD

**Issue by aalhitennf** [hyprwm/Hyprland#791]
`hyperctl monitors -j` outputs invalid json data:  

    [{
        "id": 0,
         "name": "DP-1",
        "description": "��U", // this here causes problems
        "width": 3440,
        "height": 1440,
        "refreshRate": 99.982002,
        "x": 0,
        "y": 0,
        "activeWorkspace": {
            "id": 2,
            "name": "2"
        },
        "reserved": [0, 56, 0, 0],
        "scale": 1.00,
        "transform": 0,
        "focused": true,
        "dpmsStatus": true
    }]

Without json flag:  

    Monitor DP-1 (ID 0):
	    3440x1440@99.982002 at 0x0
	    description: Samsung Electric Company CF791 HTJM300242 (DP-1)
	    active workspace: 2 (2)
	    reserved: 0 56 0 0
	    scale: 1.00
	    transform: 0
	    focused: yes
	    dpmsStatus: 1

hyprctl version:   

    Hyprland, built from branch main at commit 32e8eda40a93f9c4a304faa54a3996087eae86e4dirty ().
    flags: (if any)

**Comment by vaxerski** [comment]
fixed in d264fbd36a7085ac8078d120a88acf1b8cae9289

also its `hyprctl` not `hyperctl`
