### ISSUE TITLE
device specific settings keyboard layout

### ISSUE THREAD

**Issue by Hyppothalamus** [hyprwm/Hyprland#792]
when setting the keyboard layout for a specific device in the config it changes the keyboard layout but the defined keybinds still use the default layout.

I use a laptop with an AZERTY keyboard but sometimes I use a keychron K8 PRO with QWERTY over Bluetooth. So the specific device layout is kinda nice except the keybindings don't change.

config example:
```
input {
    kb_layout=be
}

device:Keychron K8 Pro Keyboard {
    kb_layout=us
}
```

**Comment by vaxerski** [comment]
expected behaviour: https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/

**Comment by hardfau18** [comment]
I have the same issue too, in my laptop i use dvorak layout, but my external keyboard  by default comes in dvorak, so I set dvorak on my laptop keyboard only not global by
```
device:AT Translated Set 2 keyboard {
    kb_layout=dvorak
}
```
now keyboard shortcuts uses us keyboard
