### ISSUE TITLE
Change monitor frequency when switching AC on/off

### ISSUE THREAD

**Issue by 3ri4nG0ld** [hyprwm/Hyprland#7921]
### Description

Long story short, I got a new laptop (this time AMD 😉), and I wanted to configure the computer to reduce the monitor frequency (from the 165Hz it is set to) to 60Hz to save battery life.

I found this about it:
https://www.reddit.com/r/hyprland/comments/1dhcasm/refresh_rate_dependent_on_batterycharger/

But I think this could be implemented inside hyprland,
I had thought something like this when configuring a monitor:

`monitor=eDP-1,1920x1200@165,0x0,1,AC,1920x1200@60`

Maybe this feature could be added as part of hypridle:
[https://github.com/hyprwm/hypridle/issues/67](https://github.com/hyprwm/hypridle/issues/67)

**Comment by vaxerski** [comment]
nope, hyprland doesnt read or control your power modes

**Comment by tendan** [comment]
It would be such a nice feature, but maybe for another ecosystem package, like ```hyprpower``` or something anything but included in Hyprland itself.

Maybe additional API for display management provided by Hyprland that can be used by 3rd party utilities.

**Comment by vaxerski** [comment]
there already is one, and apps like kanshi or shikane use it
