### ISSUE TITLE
Window focus/unfocus animation

### ISSUE THREAD

**Issue by Azarattum** [hyprwm/Hyprland#7927]
### Description

It would be nice if it were possible to configure an animation when a window is focused or unfocused. This is especially useful in configurations where other focus indicators (shadows, opacity, dimming) are disabled. It could be in the animation tree under `global.windows` and disabled by default (for backwards compatibility).

I imagine it looking something like [this](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAA4WQ0UrFMAyGX6UEBIV5TicMtBsHfQ7rRV2zrZy1HWk3HWPvLnWTo6B4E5I_35-ELNCYHgOI5wWcsggCnoYBMojzkIowYR8RMgh-pDoplTbTqTqmKN3fBZOuCnHu8SSdjNpMbEmJjG9Gx06wvODDe7lJHZq2iz-1V08a6ZaUNmMQ7P7SUPW5JT86LViffC2pee9ZRa1xn3QSVun25aLzE9LXCcoZq6LxTrDG12Ngd5zbUH6zPJ5xbkhZDDuxO_kVW1gk5ULjyQoWatXjdX5TsnUDit8JfngoLlDO_5mzSlcdt-9BBtZr0xjUICKNuL6sHwKQ03q1AQAA)

**Comment by vaxerski** [comment]
I think you are looking for https://github.com/VortexCoyote/hyprfocus
