### ISSUE TITLE
Permission denied [/run/user/1000/hypr ]

### ISSUE THREAD

**Issue by EssenSea** [hyprwm/Hyprland#7939]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>
gentoo-kernel-bin -6.10.11

hyprland 0.43.0 USE="X"
```sh
Hyprland (launch from tty) 
dbus-run-session Hyprland
```

</details>

### Description

Permission denied /run/user/1000 
I could "chown" to current user, then it can be launch. But, next time when I restart mechine, It still happens, and I chown again.
Could I get away from this?

### How to reproduce

[help request] Sorry, I have  no idea

### Crash reports, logs, images, videos

Hyprland threw in ctor: filesystem error: status: Permission denied [/run/user/1000/hypr]

Cannot continue.

**Comment by vaxerski** [comment]
means your XDG environment is invalid, this is a problem with your system
