### ISSUE TITLE
[Question] Is it possible to set static value for HYPRLAND_INSTANCE_SIGNATURE env variable ?

### ISSUE THREAD

**Issue by HakaishinShwet** [hyprwm/Hyprland#7940]
can we make hyprland set static value for Variable HYPRLAND_INSTANCE_SIGNATURE so it doesnt create random folder number at /run/user/1000/hypr/  ? 
i need to create bashscript and i tried with different functions to get this changed value of variable after every reboot and took gpt help but still couldnt make it possible so yeah if it is possible then please guide. 

Btw what i wanted was to create system service which would run hyprctl dispatch command with workspace number so that whenever i came back from suspend state i wanted to be at that workspace directly.

**Comment by vaxerski** [comment]
no

> hyprctl dispatch command with workspace number so that whenever i came back from suspend state i wanted to be at that workspace directly

`hyprctl --instance 0 dispatch command`
