### ISSUE TITLE
Feature Request: Monocle Layout Behavior in Hyprland

### ISSUE THREAD

**Issue by rlanggx** [hyprwm/Hyprland#7942]
### Description

**Description:**

I’d like to request an enhancement for the monocle layout in Hyprland. Specifically, I want the ability to cycle through windows using `cyclenext`, `cycleprev` without triggering unnecessary resizing. 

**Context:**

Here’s a [YouTube example](https://youtu.be/wB49sH0hvYk?si=7T8dG1UyOszFlFic) that demonstrates the issue. The resizing feels disruptive and hinders my workflow. 

Is it possible to disable resizing when cycling window?.

Thank you for considering this feature!

**Comment by vaxerski** [comment]
#683 #2050
