### ISSUE TITLE
bindr wont trigger if super is pressed during release

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#7948]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes, No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
bind = ,mouse:276, exec, exec -a autoclicker-left zsh -c 'while true; do wlrctl pointer click; sleep $((0.$RANDOM/10)); done'
bind = ,mouse:275, exec, exec -a autoclicker-right zsh -c 'while true; do wlrctl pointer click right; sleep $((0.$RANDOM/10)); done'
bindr = ,mouse:276, exec, kill $(pgrep -f autoclicker-left)
bindr = ,mouse:275, exec, kill $(pgrep -f autoclicker-right)
```

</details>

### Description

i hav the above keybind, and if i hold SUPER when releasing, the autoclicker wont stop...

I can confirm its a issue only with super because if i hold other key, no difference, it will still trigger. but super, and if i comment every bind = and only leave this, and hold super and release, it will still not stop it...

### How to reproduce

1. add the above keybinds to config
2. hold the mouse key
3. hold super
4. release mouse key before releasing super
5. now autoclicker will be still on

**Comment by littleblack111** [comment]
update: shift does that as well

**Comment by vaxerski** [comment]
use the ignore mod flag
