### ISSUE TITLE
DRM / monitor error, Hyprland can't send a signal

### ISSUE THREAD

**Issue by sg-hk** [hyprwm/Hyprland#7949]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
0.43.0-1 (latest Arch release)
```

</details>

### Description

I am able to run Wayland through the river compositor, and previously I could run Hyprland with no issues on my old monitors. I've recently switched to an ultrawide monitor that requires a gpu, and it seems Hyrpland isn't recognising it.

I've looked through the previous issues with "atomic drm request: failed to commit" but couldn't find a relevant fix. I've attached both the hyprland error log and the drm log; have I configured something wrong or how should I solve the issue?

Thanks

### How to reproduce

Try Hyprland on a 5120x1440 monitor with a radeon 6600

### Crash reports, logs, images, videos

[hyprland_error.txt](https://github.com/user-attachments/files/17178333/hyprland_error.txt)
[dmesg.txt.gz](https://github.com/user-attachments/files/17178340/dmesg.txt.gz)

**Comment by vaxerski** [comment]
```
[341691.192495] i915 0000:00:02.0: [drm:skl_plane_check [i915]] requested Y/RGB source size 5120x1440 outside limits (min: 1x1 max: 4096x4096)
```
uno primo, your gpu doesn't seem to support that resolution?

duo primo, how is the dmesg log from i915 when you are using amd? i915 is intel no?

**Comment by sg-hk** [comment]
> ```
> [341691.192495] i915 0000:00:02.0: [drm:skl_plane_check [i915]] requested Y/RGB source size 5120x1440 outside limits (min: 1x1 max: 4096x4096)
> ```
> 
> uno primo, your gpu doesn't seem to support that resolution?
> 
> duo primo, how is the dmesg log from i915 when you are using amd? i915 is intel no?

thanks for the really quick reply

i915 is the cpu's integrated graphics, which indeed can't support the monitor - hence I believe it's being handled by the gpu (radeon 6600); otherwise why would cpu load be minimal even when playing video media and upscaling them - and radeontop showing high GPU load at that time

or is this a wrong assumption?

**Comment by vaxerski** [comment]
wrong assumption

**Comment by sg-hk** [comment]
then I suppose the issue is on my end, and I haven't set up the gpu correctly
thanks for clearing that up @vaxerski
