### ISSUE TITLE
NVIDIA cursor allow_dumb_copy and no_hardware_cursors have difference in size

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#7951]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes, No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

if i use allow_dumb_copy = true, it will have a bigger mouse then     no_hardware_cursors = true

### How to reproduce

1. choose one

**Comment by vaxerski** [comment]
no system info
