### ISSUE TITLE
hyprland.conf not aware of shell aliases

### ISSUE THREAD

**Issue by xavwe** [hyprwm/Hyprland#7963]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: xwpc
Release: 6.10.10-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770] [8086:a780] (rev 04) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Description

On my system i have added several shell aliases. For example one to open program exported by distrobox. Now I wanted to add some keybindings to the `hyprland.conf` file and call these aliases but it didn't work. I added the shell aliases to my `.zshrc` file.

I already checked if Hyprland uses the right shell. It uses zsh in my case.

There is also a related [reddit-post ](https://www.reddit.com/r/hyprland/comments/16pzoxw/is_there_a_way_to_make_hyprland_aware_of_shell/?rdt=46505)form a year ago.

#### Shell aliases
Add shell aliases to your shell configuration file. I my case it is the `.zshrc` file.
For example you can add the following:
```
alias brave-browser="distrobox enter -n brave -e brave-browser"
```

#### Create the keybining
```
bind = SUPER, B, exec, brave-browser
```

#### Test
By pressing `SUPER + B` nothing happens.

**Comment by vaxerski** [comment]
your display manager does not source zshrc

**Comment by vaxerski** [comment]
rtfm'ing should work: https://wiki.hyprland.org/Configuring/Keywords/#defining-variables
