### ISSUE TITLE
Fractional scaling issues

### ISSUE THREAD

**Issue by System64fumo** [hyprwm/Hyprland#7964]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 68fd32c81013541f237e2046779185b41db1538e  (byteoperations: add missing header).
Date: Mon Sep 30 19:27:10 2024
Tag: v0.43.0-87-g68fd32c8, commits: 5283
built against aquamarine 0.4.1


flags: (if any)


System Information:
System name: Linux
Node name: frostbite
Release: 6.10.6-xanmod1-1-edge
Version: #1 SMP PREEMPT_DYNAMIC Wed, 28 Aug 2024 21:25:04 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti Lite Hash Rate] [10de:2489] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
```

</details>

### Description

Fractional scaling seems to be buggy with some programs (I've only noticed this in GTK 4 tho i have not checked QT or gtk 3)

When using GSK_RENDERER=cairo paired with a fractional scale (eg 1.6x) there will be visual artifacts on the program,
Such as lines or borders or ghost/duplicate renders of something

When using GSK_RENDERER=gl paired with a fractional scale some programs don't scale properly on startup and look a little blurry

### How to reproduce

1: Set scaling to 1.6 or whatever fractional scale your monitor supports
2: Launch a GTK 4 program with GSK_RENDERER=cairo (In my case syslock)
3: Observe some visual artifacts
4: Launch a GTK 4 program with GSK_RENDERER=gl (In my case syspower)
5: Observe as the window launches with an unscaled desktop resolution (Native res) and goes outside of the screen

### Crash reports, logs, images, videos

Just for the record, Regular scaling works fine, Ie 1x, 2x, 3x, ect

1.6x:
<img src="https://github.com/user-attachments/assets/a5903eae-a711-429f-b905-11b0902df748" width="700"><br>

2x:
<img src="https://github.com/user-attachments/assets/7598db81-2cd7-4d95-b75f-0b3ea8093fc9" width="700"><br>

**Comment by System64fumo** [comment]
https://github.com/System64fumo/syspower
or
https://github.com/System64fumo/syslock

sysbar too
basically any GTK 4.0 program i guess

**Comment by Honkazel** [comment]
> When using GSK_RENDERER=gl paired with a fractional scale some programs don't scale properly on startup and look a little blurry

Sounds like old gl renderer being old gl renderer
Don't know bout cairo
And what bout ngl and vulkan with frac scale?

**Comment by System64fumo** [comment]
ngl still starts up with full res instead of scaled res tho i think it looks less blurry not sure
vulkan is fine (Works perfectly fine)

**Comment by Honkazel** [comment]
...Yeah, GSK_RENDERER=cairo works like shit
Tested it with easyeffects
I think, that cairo is being cairo, but maybe test this with other WM/DEs?(like sway, KDE)

**Comment by Honkazel** [comment]
...But there's a trouble on discord(or other discord electron clients, in my case vesktop) with frac scale(ozone wayland)
But web discord works fine(chromium, don't know about firefox)

**Comment by System64fumo** [comment]
Upon testing this with labwc i can confirm that this also happens there.
Could not test with mutter because mutter is seemingly broken on x86_64 lol nice

**Comment by vaxerski** [comment]
then I think this can be closed?

**Comment by System64fumo** [comment]
Depends on if it could be fixed in hyprland or if this is a GTK specific issue?
