### ISSUE TITLE
Add CTM support (needed for Asahi Linux to have night light working)

### ISSUE THREAD

**Issue by sfiedler0** [hyprwm/Hyprland#7965]
### Description

I already suggested the CTM in hyprwm/aquamarine#89, and after that one is done it would be really nice to have it here.

**Comment by MahouShoujoMivutilde** [comment]
Not saying it should or shouldn't be supported, but if you want night light by itself as a _feature_, regardless of the implementation, hyprland supports shaders, and it's what [I've been using](https://github.com/hyprwm/Hyprland/issues/1140#issuecomment-1335128437) for a long time before nvidia implemented GAMMA_LUT (which is needed for gammastep).

With [hyprshade](https://github.com/loqusion/hyprshade) you even make it use appropriate shader depending on the time of day. They don't seem to use it, but there is also [astral](https://sffjunkie.github.io/astral/) which you can use to calculate sunsets and sunrises for a given place and date.

**Comment by sfiedler0** [comment]
> With [hyprshade](https://github.com/loqusion/hyprshade) you can even make it use appropriate shader depending on the time of day. 

Thanks, didn't know about that one. I'll use it until CTM works.

**Comment by vaxerski** [comment]
glad to hear
