### ISSUE TITLE
Hyprland Failed to create screen in Vmware virtual machine of ArchLinux 

### ISSUE THREAD

**Issue by aleOS2** [hyprwm/Hyprland#797]
Hi, i have just installed archlinux in a VM, I installed Hyprland using yay (no bin or git), When i launch it from SDDM nothing appened, when i start from the TTY i receive this: 
![image](https://user-images.githubusercontent.com/65780895/194353835-3e832968-f13e-4129-b776-024b1ab06e9b.png)

This is the log: ![image](https://user-images.githubusercontent.com/65780895/194352981-247ebdee-33f1-403d-9f4f-349976215bc4.png)

I have read some issues but i can't find my specific error.
I use example conf
Anyone can help? Thanks
I think that i need Vmware tools, idk

Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by vaxerski** [comment]
you need to enable software rendering with `WLR_RENDERER_ALLOW_SOFTWARE=1` because obviously a vm doesn't have a gpu

**Comment by aleOS2** [comment]
You can teach me how? With export, put in conf and run this before Hyperland don't work.  I'm doing it wrong?

**Comment by aleOS2** [comment]
I have tried this, but i receive the same error.
I will install it in my laptop.

**Comment by vaxerski** [comment]
try not using a VM.

**Comment by kjeremy** [comment]
Setting `WLR_NO_HARDWARE_CURSORS = "1"` fixed this for me in a vmware guest.
