### ISSUE TITLE
[NixOS] Hyprland doesn't start after upgrade to 0.43 and 24.11 

### ISSUE THREAD

**Issue by kubni** [hyprwm/Hyprland#7970]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 5c6c300abfea2539ffad9bcbf857325eec5ab765  ().
Date: 2024-09-30
Tag: , commits: 5285
built against aquamarine 0.4.1


flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.11.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Sun Sep 15 14:57:56 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240929.06cf0e1"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

plugins:
	unknown: not runtime
```

</details>

### Description

I have a stable system that is using 24.05 and Hyprland 0.41.2.
I tried using nixos-unstable, and with it NixOS 24.11, Hyprland 0.43 and Linux kernel 6.11, however Hyprland doesn't start.
I don't see that it generated a crash log.
I enabled debug logs and I will attach the coredump, journalctl and dmesg below in hopes of someone finding an issue.

### How to reproduce

I am not sure if it is reproducible yet.

### Crash reports, logs, images, videos

[hyprland_coredump.txt](https://github.com/user-attachments/files/17216382/hyprland_coredump.txt)
[journalctl.txt](https://github.com/user-attachments/files/17216384/journalctl.txt)
[dmesg.txt](https://github.com/user-attachments/files/17216385/dmesg.txt)

**Comment by kubni** [comment]
My config is on my profile, [here](https://github.com/kubni/nix.dots)

**Comment by skurpi** [comment]
I'm running Arch with Hyprland and Wayland. After an upgrade this morning to the latest kernel, hyprland (and all other packages that come with a rolling update), it stopped working. I don't have any logs at the moment, I'll dig some out.

**Comment by edpyt** [comment]
faced the same problem, downgrade the latest package synchronization

```
#/etc/pacman.conf

[core]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2024/10/01/$repo/os/$arch
#Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2024/10/01/$repo/os/$arch
#Include = /etc/pacman.d/mirrorlist
```

sudo pacman -Syyuu \
reboot \
yay -Syu # exclude nvidia-dkms and nvidia-utils here

**Comment by kubni** [comment]
The problem I have is on NixOS, so I doubt Arch things are relevant.

**Comment by hyperboly** [comment]
could this be related to #6967 ? i have a similar journalctl
[journal.log](https://github.com/user-attachments/files/17220477/journal.log)

System info
```
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: nixon
[LOG] Release: 6.6.52
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Sep 18 17:24:10 UTC 2024


[LOG] GPU information:
c1:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])


[LOG] os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240930.1719f27"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"
```

**Comment by kubni** [comment]
> could this be related to #6967 ? i have a similar journalctl [journal.log](https://github.com/user-attachments/files/17220477/journal.log)
> 
> System info
> 
> ```
> [LOG] ===== SYSTEM INFO: =====
> [LOG] System name: Linux
> [LOG] Node name: nixon
> [LOG] Release: 6.6.52
> [LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Sep 18 17:24:10 UTC 2024
> 
> 
> [LOG] GPU information:
> c1:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])
> 
> 
> [LOG] os-release:
> ANSI_COLOR="1;34"
> BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
> BUILD_ID="24.05.20240930.1719f27"
> DOCUMENTATION_URL="https://nixos.org/learn.html"
> HOME_URL="https://nixos.org/"
> ID=nixos
> IMAGE_ID=""
> IMAGE_VERSION=""
> LOGO="nix-snowflake"
> NAME=NixOS
> PRETTY_NAME="NixOS 24.05 (Uakari)"
> SUPPORT_END="2024-12-31"
> SUPPORT_URL="https://nixos.org/community.html"
> VERSION="24.05 (Uakari)"
> VERSION_CODENAME=uakari
> VERSION_ID="24.05"
> ```

I will check it, though my Hyprland doesn't generate a crash report if i am not mistaken. I couldn't find the appropriate crash log in the crash directory, nor did I see the output that it generated one.

**Comment by hyperboly** [comment]
`cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 1)/hyprland.log`
this doesn't work?

**Comment by iddm** [comment]
I can run it, but have like 2 hertz refresh rate, and a weird fake monitor between my two. According to the logs, somehow, aquamarine detects two GPUs and creates the rendering backends for both of them, however, only one is enabled in BIOS (the discrete GPU):
```
   11 [LOG] GPU information:
   12 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD102 [GeForce RTX 4090] [10de:2684] (rev a1) (prog-if 00 [VGA controller])

  561 [LOG] DRM driver information: simpledrm v1.0.0 from 0 description DRM driver for simple-framebuffer platform devices
  562 [LOG] DRM driver information: nvidia-drm v0.0.0 from 0 description NVIDIA DRM driver

 81 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1
   82 [LOG] [AQ] libseat: Device /dev/dri/card1 supports kms
   83 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-DP-1
   84 [ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-DP-1, no devnode
   85 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-DP-2
   86 [ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-DP-2, no devnode
   87 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-DP-3
   88 [ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-DP-3, no devnode
   89 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-HDMI-A-1
   90 [ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card1/card1-HDMI-A-1, no devnode
   91 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/simple-framebuffer.0/drm/card0
   92 [LOG] [AQ] libseat: Device /dev/dri/card0 supports kms
   93 [LOG] [AQ] drm: Enumerated device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/simple-framebuffer.0/drm/card0/card0-Unknown-1
   94 [ERR] [AQ] drm: Skipping device /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/simple-framebuffer.0/drm/card0/card0-Unknown-1, no devnode
   95 [LOG] [AQ] drm: Found 2 GPUs
   96 [LOG] [AQ] drm: Starting backend for /dev/dri/card0, with driver simpledrm
   97 [LOG] [AQ] drm: Registered gpu /dev/dri/card0
   98 [LOG] [AQ] drm: Atomic supported, using atomic for modesetting
   99 [LOG] [AQ] drm: drmProps.supportsAsyncCommit: false
  100 [LOG] [AQ] drm: drmProps.supportsAddFb2Modifiers: true
  101 [LOG] [AQ] drm: drmProps.supportsTimelines: false
  102 [LOG] [AQ] drm: found 1 CRTCs
  103 [LOG] [AQ] drm: found 1 planes
  104 [LOG] [AQ] drm: Plane 32 has type 1
  105 [LOG] [AQ] drm: Plane 32 has 1 formats
  106 [LOG] [AQ] drm: Plane: checking for modifiers
  107 [LOG] [AQ] drm: Basic init pass for gpu /dev/dri/card0
  108 [LOG] [AQ] drm: Scanning connectors for /dev/dri/card0
  109 [LOG] [AQ] drm: Scanning connector id 36
  110 [LOG] [AQ] drm: Initializing connector id 36
  111 [LOG] [AQ] drm: Connector gets name Unknown-1
  112 [LOG] [AQ] drm: Connector 36 connection state: 1
  113 [LOG] [AQ] drm: Rechecking CRTCs
  114 [LOG] [AQ] drm: Skipping connector Unknown-1, has crtc 34 and is connected
  115 [LOG] [AQ] drm: slot 0 crtc 34 taken by Unknown-1, skipping
  116 [LOG] [AQ] drm: rescanning after realloc
  117 [LOG] [AQ] drm: Scanning connectors for /dev/dri/card0
  118 [LOG] [AQ] drm: Scanning connector id 36
  119 [LOG] [AQ] drm: Connector id 36 already initialized
  120 [LOG] [AQ] drm: Connector 36 connection state: 1
  121 [LOG] [AQ] drm: Connector Unknown-1 connected
  122 [LOG] [AQ] drm: Connecting connector Unknown-1, CRTC ID 34
  123 [LOG] [AQ] drm: Dumping detected modes:
  124 [LOG] [AQ] drm: Mode 0: 2560x1440@60.00Hz  (preferred)
  125 [LOG] [AQ] drm: Physical size [Vector2D: x: 677, y: 381] (mm)
  126 [ERR] [AQ] drm: failed to parse edid
  127 [LOG] [AQ] drm: Description    (Unknown-1)
  128 [LOG] [AQ] drm: connector Unknown-1 crtc is incapable of vrr: props.vrr_capable -> 0, crtc->props.vrr_enabled -> 24
  129 [LOG] [AQ] drm: Explicit sync unsupported
  130 [LOG] [AQ] drm: gpu /dev/dri/card0 becomes primary drm
  131 [LOG] [AQ] drm: Starting backend for /dev/dri/card1, with driver nvidia-drm with primary /dev/dri/card0
  132 [LOG] [AQ] drm: Registered gpu /dev/dri/card1
  133 [LOG] [AQ] drm: Atomic supported, using atomic for modesetting
  ```
  Then, further in the logs it says that the "card0" becomes the primary DRM, while card1 being the NVIDIA one (the discrete GPU only enabled in BIOS). And the last problem is many-many messages of:
  ```
eglCreateSyncKHR failed
  ```
  And other sorts of error messages. Just before yesterday's evening ArchLinux update everything was flawless, nothing except the new packages has changed.

**Comment by kubni** [comment]
> `cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 1)/hyprland.log` this doesn't work?

I don't have the hypr directory in XDG_RUNTIME_DIR

**Comment by Randomneo** [comment]
Not sure if I should create new issue or write here, but it looks related.

I also got problems with upgrade on Arch
after upgrading this packages hyprland starts stuttering, lagging apps, artifacts. Also `hyprctl monitors` starts to recognize one more - `Unknown-1` monitor (not 1 of connected).

Here is ignored upgrades. If one nvidia or linux error appear.
```
warning: linux: ignoring package upgrade (6.10.10.arch1-1 => 6.11.1.arch1-1)
warning: nvidia: ignoring package upgrade (560.35.03-6 => 560.35.03-9)
warning: nvidia-utils: ignoring package upgrade (560.35.03-3 => 560.35.03-4)
```

**Comment by ccptr** [comment]
> I also got problems with upgrade on Arch after upgrading this packages hyprland starts stuttering, lagging apps, artifacts. Also `hyprctl monitors` starts to recognize one more - `Unknown-1` monitor (not 1 of connected).
> 
> Here is ignored upgrades. If one nvidia or linux error appear.

I was having exactly the same issue(s). I was able to get it down to only pinning `linux` to `6.10.10-arch1-1` (and in my case `linux-headers` because of dkms).

I'm not sure if it's related or not, but I've had to pin `hyprland` to `0.41.2` as well since Xwayland hasn't been able to launch since then. _**However**_ Xwayland worked for the first time on the newer Hyprland versions while I was on the latest Arch kernel.

**Comment by kubni** [comment]
I noticed that 0.41.2 + 24.11 combination also makes Hyprland not start, so it might not even be Hyprland's problem.

**Comment by Neburski** [comment]
From the Arch forums: https://bbs.archlinux.org/viewtopic.php?id=299450

It seems that NVIDIA renamed an fbdev header file. This leads to issues for Hyprland when using kernel 6.11 and NVIDIA. See https://github.com/NVIDIA/open-gpu-kernel-modules/pull/692/files

Solutions, downgrade your kernel or apply the patch from NVIDIA and recompile your kernel.

This does not appear to be an issue in Hyprland itself.

**Comment by vaxerski** [comment]
closing then
