### ISSUE TITLE
Window Resizing

### ISSUE THREAD

**Issue by TheLastTeapot** [hyprwm/Hyprland#80]
I'm not sure if this is a bug or a feature, but either way it annoys me to death. When resizing windows, the window at a certain size will switch from a horizontal window to a vertical, or vice versa. This is sometimes irreversible. Also, there is always a vertical line of complete separation down the screen, meaning I cannot have a window go all the way across the bottom of the screen when any other windows are present. What I think would solve both these problems is to prioritize the window being resized above all others, and resize them around it with no exceptions. If necessary I can attach a video of the issue.

**Comment by vaxerski** [comment]
This is intentional and by-design.

![20220516_17h14m58s_grim](https://user-images.githubusercontent.com/43317083/168625995-561afa02-ce95-4e59-8ba9-3dc0e09c3045.png)

However, what I might add, is an option to disable extra split recalcs and maybe add a keybind to override the split.

**Comment by vaxerski** [comment]
`preserve_split` added in e90c1f7022ffd82e463c48260a97850c834f347d

wait a sec while i add a keybind to force a split change

**Comment by TheLastTeapot** [comment]
Hyprland fails to compile

**Comment by TheLastTeapot** [comment]
I'll attach the error if you want

**Comment by TheLastTeapot** [comment]
Thanks! I did try sudo pacman -Syu but nothing changed. wlroots-git is a aur package though so it wouldn't have updated

**Comment by TheLastTeapot** [comment]
Now it works. Thanks for all the optimizations you've done, now even my potato gpu can run heavy blur without struggle =)

**Comment by vaxerski** [comment]
Just recompiled against main upstream and I can confirm both libreoffice and watching dank memes on vlc works as it should.
