### ISSUE TITLE
weird kill -TERM behavior

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#800]
On Hyprland (and only on Hyprland) kill -TERM has no effect anywhere. This work fine on raw tty or Sway. Could Hyprland trap this somehow?

**Comment by vaxerski** [comment]
it's odd yes, everything started with `exec-once` needs `kill -9`

**Comment by primalmotion** [comment]
doesn not seems to be exec-once too. I can't kill my terminal that is launched with simple exec

**Comment by vaxerski** [comment]
possible, although I can't repro that one.

**Comment by vaxerski** [comment]
try commenting out line 53 (wl_event_loop_add_signal) in Compositor.cpp and lmk how that goes.

**Comment by primalmotion** [comment]
yeah I was looking at that. Could this be related https://github.com/swaywm/sway/commit/7d8413d9628ed493790454410a28b9f0c41444e6 ?

**Comment by primalmotion** [comment]
yep. as expected commenting this line restores normal kill behavior

**Comment by vaxerski** [comment]
check 922e978f56ed8a00700ed7730ea56bd1e10665b3 then

**Comment by primalmotion** [comment]
fixed. Faster than light :)

**Comment by vaxerski** [comment]
thanks for the PR link.
