### ISSUE TITLE
more then just X1 Y1 for animations?

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#8000]
### Description

is it possible to do sth like X0, Y0, X1, Y1, X2, Y2, X3, Y3...

I want to create a animation that bounces back and forth. but cant do that with only X0 X1 and Y0 Y1

**Comment by vaxerski** [comment]
not possible atm and I doubt it will ever be as it's kinda not the right thing to do, I'd rather implement springs
