### ISSUE TITLE
all sub window/layer selection

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#8001]
### Description

for example. I want all popup window or window that is spawned by another program to be float

**Comment by vaxerski** [comment]
what?

**Comment by littleblack111** [comment]
like if in a file manager, i double click a file, and it opened something. I want to select that thing

**Comment by vaxerski** [comment]
just match whatever properties it has, there isnt much we can do here? otherwise if you want by pid thats a dupe of #7861
