### ISSUE TITLE
0.44.0 (binary) doesn't start on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by vaskark** [hyprwm/Hyprland#8009]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0c7a7e2d569eeed9d6025f3eef4ea0690d90845d  (version: bump to 0.44.0).
Date: Sun Oct 6 11:04:13 2024
Tag: , commits: 1
built against aquamarine 0.4.1


flags: (if any)


System Information:
System name: Linux
Node name: jabberwookiee
Release: 6.11.1-custom
Version: #1 SMP PREEMPT_DYNAMIC Mon Sep 30 23:27:55 EDT 2024


GPU information: 
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c5) (prog-if 00 [VGA controller])


os-release: PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo


plugins:
    unknown: not runtime
```

</details>

### Description

Upgraded the binaries of 0.44.0 release and Hyprland wouldn't start. I received this error:

`Hyprland: symbol lookup error: Hyprland: undefined symbol: wl_display_set_default_max_buffer_size`

### How to reproduce

N/A

### Crash reports, logs, images, videos

The debug log didn't produce anything (and it is set to false) just the basic startup messages plus above error, and there's nothing in `~/.cache/hyprland ` (never has been afaik). And coredumpctl doesn't produce anything either.

Just thought I'd report, even though Ubuntu isn't a priority. I do have the dependencies built and installed (from latest git).

Thanks.

**Comment by vaxerski** [comment]
outdated dependencies
