### ISSUE TITLE
Improve check for XDG_CURRENT_DESKTOP=Hyprland

### ISSUE THREAD

**Issue by stefonarch** [hyprwm/Hyprland#8019]
### Description

LXQt with Hyprland uses `XDG_CURRENT_DESKTOP=LXQt:Hyprland:wlroots`, needed for the taskbar to load the correct plugin and it allows also building plugins (e.g.pager) only for Hyprland.

With v0.44 an annoying message is now seen at login:
![immagine](https://github.com/user-attachments/assets/85cada9d-925a-40bb-be44-620ac7f70b22) introduced by https://github.com/hyprwm/Hyprland/commit/883d01084c52fdc5da0e6bfff7fd0f5cf0f62352

Could this check be changed to check for _containing_  `Hyprland` , accepting also the above and other multiple env vars? 

Or can the message be disabled? (second best).

**Comment by MightyPlaza** [comment]
the whole point of the commit was not to override your setting, you can still set it yourself or disable the warning with the config option added in the commit

**Comment by stefonarch** [comment]
My bad, didn't scroll down the commit. 
But it's still valid, as the check gives a false positive here.

**Comment by vaxerski** [comment]
no, this is not a false positive, this is correct behavior. You can disable the warning.
