### ISSUE TITLE
Add warning if kitty is not detected on machine.

### ISSUE THREAD

**Issue by piee-kun** [hyprwm/Hyprland#8033]
### Description

On Arch, often if a user installs hyprland manually through terminal, not through the archinstall profile, it's possible for hyprland to not ship with kitty, therefore leave the user confused when using SUPER+Q by default. I think either adding a warning that a program failed to start, or that kitty is not present would be a good solution if kitty or other programs are not installed.

**Comment by Aqa-Ib** [comment]
Fixed on git.
