### ISSUE TITLE
High CPU Usage on mouse movement hyprland 0.44

### ISSUE THREAD

**Issue by mewt666** [hyprwm/Hyprland#8047]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0c7a7e2d569eeed9d6025f3eef4ea0690d90845d  (version: bump to 0.44.0).
Date: Sun Oct 6 11:04:13 2024
Tag: v0.44.0, commits: 5299
built against aquamarine 0.4.1


flags: (if any)


System Information:
System name: Linux
Node name: Minas-tirith
Release: 6.11.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000


GPU information: 
26:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 SUPER] [10de:1f06] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime
```

</details>

### Description

Upgrading from hyprland 0.43 to 0.44 (Archlinux package) results in stuttery mouse movement and high cpu usage (80-100%) on a single core (hyprland process).

This is observed on a freshly booted session with no programs open apart from kitty to monitor cpu usage in htop.
Reverting to 0.43 immediately resolves the issue. 

### How to reproduce

1. Upgrade to 0.44
2. reboot and login
3. Notice stuttery mouse movement
4. check cpu usage and find 100% cpu usage by the hyprland process. CPU usage goes down if mouse movement stopped

**Comment by vaxerski** [comment]
dupe, you have _not_ searched the issue tracker. #8036
