### ISSUE TITLE
No more wallpaper & firefox not launching

### ISSUE THREAD

**Issue by Stephixus** [hyprwm/Hyprland#8048]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Bad version : 0.44.0-20-bc299928
Good version : 0.44.0-19-ac658500

### Description

NVIDIA GM206M [GeForce GTX 965M] driver: nvidia v: 560.35.03
- No more wallpaper launching: swww nor hyprpaper
- Firefox doesn’t lauch. Tor does. (Both wayland mode)

### How to reproduce

Relative to NVidia video card? (Not tested with another)
- Try running `hypraper` or `swww-daemon --format xrgb`

### Crash reports, logs, images, videos

Indication concerning `firefox`?

`[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt`

**Comment by iUnstable0** [comment]
Wth i am having the exact same issue rn!!!!

**Comment by NoDwen** [comment]
Same as #8046

**Comment by Stephixus** [comment]
Yes, same as [https://github.com/hyprwm/Hyprland/issues/8046](https://github.com/hyprwm/Hyprland/issues/8046).
Thanks.
I close.
