### ISSUE TITLE
[hyprpm] plugin search paths 

### ISSUE THREAD

**Issue by fiersik** [hyprwm/Hyprland#8051]
### Description

It would be nice if hyprpm could find plugins not only in the home directory.

For example, the path /usr/share/hyprpm/ would help to compile plugins into packages for distributions.

In this case, hyprpm should not manage plugin versions, but only allow you to turn them on and off.

**Comment by vaxerski** [comment]
please just don't do that, plugins are not stable and need to be recompiled against every single commit change
