### ISSUE TITLE
Hyprpm fails every time

### ISSUE THREAD

**Issue by CitrusIntellect** [hyprwm/Hyprland#8059]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2

flags: (if any)

System Information:
System name: Linux
Node name: elias-archlinux
Release: 6.11.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107 [GeForce RTX 4060] [10de:2882] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

======Config-Start======

Config File: /home/elias/.config/hypr/hyprland.conf: Read Succeeded

monitor = DP-1, 1920x1080@74.97, 0x0, 1
monitor = DP-2, 1920x10800@74.97, 1920x0, 1
monitor = , preferred, auto, 1

# Environment Variables

env = RSPOTIFY_CLIENT_ID=no
env = RSPOTIFY_CLIENT_SECRET=no
env = QT_QPA_PLATFORMTHEME=qt6ct

#On Startup
plugin:split-monitor-workspaces:count = 5
exec-once = hyprpm reload -n
exec-once = RSPOTIFY_CLIENT_SECRET=no RSPOTIFY_CLIENT_ID=no waybar
exec-once = hyprpaper
exec-once = $HOME/.config/hypr/scripts/sleep.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start plasma-polkit-agent
exec-once = hyprpm update

## Backend Environment Variables

# DisplayServer Type
env = XCURSOR_SIZE,24vs
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11
env = SDL_VIDEODRIVER,wayland
# Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
# Platform
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

input {
    kb_layout = us
    kb_variant =
    kb_model = pc105
    kb_options = compose:menu
    kb_rules =
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
    sensitivity = 0
    accel_profile = flat
    scroll_points =
}

general {
    gaps_in = 5
    gaps_out = 5,10,10,10
    border_size = 3
    col.active_border = rgba(d6783aff)
    col.inactive_border = rgba(3d484dff)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 2
        passes = 3
        new_optimizations = true
    }
    drop_shadow = true
    shadow_range = 15
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    new_status = true
}

gestures {
    workspace_swipe = off
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

windowrule = opacity 0.8 override,^(kitty)$

# Keybinds
$mainMod = SUPER

bind = $mainMod, Return, exec, kitty
bind = $mainMod, A, exec, dolphin
bind = $mainMod, W, exec, brave
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, B, exec, pkill -USR1 gammastep || gammastep
bind = $mainMod ALT, E, exec, rofi -show emoji

bind = $mainMod, F, fullscreen
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, E, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle

# Keyboard Binds
# l -> do stuff even when locked
# e -> repeats when key is held 
bindle=, XF86AudioRaiseVolume, exec, pamixer -i 2
bindle=, XF86AudioLowerVolume, exec, pamixer -d 2
bindle=, XF86AudioMuteVolume, exec, pamixer -t

bindle=, XF86Search, exec, launchpad
# bindl=, XF86AudioMute, exec, amixer set Master toggle
bindl=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=, XF86AudioPlay, exec, playerctl play-pause # the stupid key is called play , but it toggles 
bindl=, XF86AudioNext, exec, playerctl next 
bindl=, XF86AudioPrev, exec, playerctl previous

# HYPRSHOT
# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output
# Screenshot a region
bind = $mainMod SHIFT, PRINT, exec, hyprshot -m region

# Move focus with mainMod + [H, L, K, J]
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Move active window with mainMod + SHIFT + [H, L, K, J]
bind = $mainMod ALT, left, movewindow, l
bind = $mainMod ALT, right, movewindow, r
bind = $mainMod ALT, up, movewindow, u
bind = $mainMod ALT, down, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod ALT, Y, exec, pkill waybar && RSPOTIFY_CLIENT_SECRET=no RSPOTIFY_CLIENT_ID=no waybar

bind = ALT, R, submap, resize
submap = resize
binde = , right, resizeactive, 10 0
binde = , left, resizeactive, -10 0
binde = , up, resizeactive, 0 -10
binde = , down, resizeactive, 0 10

bind = , escape, submap, reset
submap = reset

bind = ALT, M, submap, move
submap = move
binde = , right, movewindow, r
binde = , left, movewindow, l
binde = , up, movewindow, u
binde = , down, movewindow, d

bind = , escape, submap, reset
submap = reset

======Config-End========

### Description

Running hyprpm update freezes on 0/5, then gives an error saying cant checkout branch. Running Git clone manually prompts me for a username and password, with an error at the end. Cloning other repo's does not produce this error. 

### How to reproduce

Run hyprpm update
To get the password error run git clone github.com/hyprwm/Hyprland

### Crash reports, logs, images, videos

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                          
✔ cloned                                                                                                         
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Checking out sources                                 
✖ Could not checkout the running Hyprland commit. If you are on -git, try updating.
You can also try re-running hyprpm update with --no-shallow.

Git Clone manually:
Cloning into 'Hyprland'...
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/hyprvm/Hyprland/'

**Comment by vincentaxhe** [comment]
I once run hyprland plugin 'hyprscroller' on 0.41.9, and never complie it successfully again after updates, now I give it up, if hyprscroller merged to hyprland core code, it'll be guaranteed its availability. no confidence as long as it is offered as a plugin.

**Comment by vaxerski** [comment]
`hyprpm update -v` output pls

**Comment by CitrusIntellect** [comment]
Output, It just said cloned but I am assuming it is a timeout:

❱ hyprpm update -v                                                                            
[v] version returned: Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


[v] parsed commit 4520b30d498daca8079365bdb909a8dea38e8d55 at branch  on Wed Oct 9 12:54:39 2024, commits 5309

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                          
[v] will shallow since: Wed Oct 02 12:54:39 2024                                                                 

✔ cloned                                                                                                         
[v] will run: cd /tmp/hyprpm/hyprland-elias && git checkout 4520b30d498daca8079365bdb909a8dea38e8d55 2>&1        
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Checking out sources                                 
✖ Could not checkout the running Hyprland commit. If you are on -git, try updating.
You can also try re-running hyprpm update with --no-shallow.

**Comment by jorgemota** [comment]
I just got same error, fixed with:

hyprpm update --no-shallow                                                                                                                                                                                                               
Got Headers and plugins working again.

**Comment by CitrusIntellect** [comment]
> I just got same error, fixed with:
> 
> hyprpm update --no-shallow Got Headers and plugins working again.

Worked for me

**Comment by vincentaxhe** [comment]
yeah add '--no-shallow' and complied hyprscroller!

**Comment by vaxerski** [comment]
no way, the proposed fix works, almost as if reading would be convenient

**Comment by CitrusIntellect** [comment]
wow, its not like I did exactly what the wiki said to do with an error,  it worked before and it just stopped, laziness at its peak. Also when I originally used --no-shallow, same exact error, fixed now. Suggest updating your wiki.

**Comment by vaxerski** [comment]
MRs welcome, it's open source
