### ISSUE TITLE
Noanim doesn't work

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#806]
The noanim window rule simply doesn't work. I have tried the hyprland-bin from the AUR and the hyprland-git from the AUR, which both seem to be version 0.15.1Beta. Red bar at the top saying my config is broken and the feature doesn't work either.

**Comment by vaxerski** [comment]
config line pls, pretty sure it does

**Comment by EysseW** [comment]
[hyprland-config.txt](https://github.com/hyprwm/Hyprland/files/9736424/hyprland-config.txt)

**Comment by vaxerski** [comment]
the rule is a comment...

it works, just tested with kitty.

**Comment by EysseW** [comment]
I know it's a comment. I am not going to deal with that red message the entire time. It didn't work on my system, despite having the proper version...

**Comment by vaxerski** [comment]
check your `hyprctl version`
