### ISSUE TITLE
Opinions?

### ISSUE THREAD

**Issue by nnyyxxxx** [hyprwm/Hyprland#8075]
### Description

![image](https://github.com/user-attachments/assets/a89618b6-eecd-4a35-8c58-03ad9a772194)

**Comment by myamusashi** [comment]
You built a GUI for Hyprland configuration? That's cool.

**Comment by nnyyxxxx** [comment]
> You built a GUI for Hyprland configuration? That's cool.

yeah i'm working on it, bit buggy atm

**Comment by myamusashi** [comment]
It would be better to make it an open-source project

**Comment by nnyyxxxx** [comment]
> It would be better to make it an open-source project

yeah, it will be, just got to squeeze out these last bugs and ill unprivate the repo

**Comment by myamusashi** [comment]
Did you build it in Rust?

**Comment by nnyyxxxx** [comment]
> Did you build it in Rust?

no, i used python

**Comment by izmyname** [comment]
One step for Hypr* to become a full-featured DE and overthrow GNOME.

Keep up the good work. I'm not the target audience for GUI config tools, but I can see how it can possibly improve Hypr* experience for some people and attract a new auditory.

**Comment by fufexan** [comment]
There's also https://github.com/hyprland-community/hyprset

**Comment by vaxerski** [comment]
I don't know what the point of this issue is

**Comment by nnyyxxxx** [comment]
> One step for Hypr* to become a full-featured DE and overthrow GNOME.
> 
> Keep up the good work. I'm not the target audience for GUI config tools, but I can see how it can possibly improve Hypr* experience for some people and attract a new auditory.
> 
> P.S Is this GTK? IMHO, qt6 would be a better choice, since xpdh uses it and it supports hyprcursor.

yeah its gtk

**Comment by nnyyxxxx** [comment]
> There's also https://github.com/hyprland-community/hyprset

yeah i didn't see that until now, good to know someone has already done this before

**Comment by nnyyxxxx** [comment]
remade it in rust, https://github.com/nnyyxxxx/hyprgui source is public, has a custom-made parser lib for it as well
