### ISSUE TITLE
Hyprland doesn't start and kicks me back to SDDM

### ISSUE THREAD

**Issue by barbas66** [hyprwm/Hyprland#8077]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2

flags: (if any)

System Information:
System name: Linux
Node name: elitebook2
Release: 6.6.54-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sat, 05 Oct 2024 17:53:31 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:
	unknown: not runtime

</details>

### Description

Upon logging into hyprland through SDDM the screen goes blank and reverts back to SDDM login screen after few seconds.

### How to reproduce

1. Login into a hyprland session from SDDM

### Crash reports, logs, images, videos

[hyprlandCrashReport21946.txt](https://github.com/user-attachments/files/17338662/hyprlandCrashReport21946.txt)

**Comment by mcourteaux** [comment]
You might want to compile Hyprland in debug mode to get more info from that backtrace. Then running Hyprland in `gdb` will probably show you what's happening. That would be useful to fix any bugs.

**Comment by vaxerski** [comment]
something is wrong with your setup, as hyprland cannot find a config and fails to autogenerate one. Looks like neither HOME nor XDG_CONFIG_HOME are in the environment, or the fs has some permissions f-d up
