### ISSUE TITLE
Hyprland would not start

### ISSUE THREAD

**Issue by RQuarx** [hyprwm/Hyprland#8079]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.11.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])
	DeviceName: VGA
	DeviceName: Second VGA


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime
```

</details>

### Description

After doing some post install (installing conda, vscodium, etc) i went to restart the computer, and when i tried to log in... Hyprland does not / refused to start

### How to reproduce

1, Log in
2, Start Hyprland

### Crash reports, logs, images, videos

[hyprlandCrashReport55573.txt](https://github.com/user-attachments/files/17344075/hyprlandCrashReport55573.txt)

**Comment by vaxerski** [comment]
can you get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

my guess is permissions are fucked in your xcursor theme

**Comment by RQuarx** [comment]
> can you get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace
> 
> my guess is permissions are fucked in your xcursor theme

[gdb.txt](https://github.com/user-attachments/files/17348663/gdb.txt)
is it this?

**Comment by RQuarx** [comment]
Tried to remove the icons and themes, then it works, copying from a saved home dir caused some permissions issues

**Comment by vaxerski** [comment]
thanks, fixed in git too, should not crash anymore
