### ISSUE TITLE
Add suport for NV12 colorspace 

### ISSUE THREAD

**Issue by leiserfg** [hyprwm/Hyprland#8081]
### Description

Borrow this from KDE:
https://invent.kde.org/plasma/kwin/-/merge_requests/4581/diffs?commit_id=3568829216ca4a1796d86dd5f67da5c3724adf55#c1c0a1d7f564ffdfb1eacab53c2f3f73b4e32a29

to cooperate with mpv dmabuf-wayland .

**Comment by vaxerski** [comment]
but y

**Comment by leiserfg** [comment]
I thought it could make mpv's dmabuf-wayland vo work (by tone mapping at composer level) but I just checked in kde and there the tone mapping is still not happening. So I will close it, and cry.
