### ISSUE TITLE
hyprland notification moving waybar layer

### ISSUE THREAD

**Issue by pbosab** [hyprwm/Hyprland#8082]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
❯ hyprctl version  
Hyprland 0.44.0 built from branch main at commit 7564b26b7d386d248eaa47c1a481c09eefd8e3ca  (internal: improve version query and define HYPRLAND_VERSION (8034)).
Date: Fri Oct 11 13:19:16 2024
Tag: v0.44.0-29-g7564b26b, commits: 5328
built against aquamarine 0.4.2


flags set:

```
</details>

### Description

starting without having plugins updated so there is a notification, waybar is displayed below the notification. before didn't happen.

### How to reproduce

start without updated plugins

### Crash reports, logs, images, videos

![2024-10-11T20:09:14,066415153+02:00](https://github.com/user-attachments/assets/b2856b82-2e80-44e7-9039-e4635a51c8c1)

**Comment by vaxerski** [comment]
that's a feature so that the error doesn't cover stuff
