### ISSUE TITLE
Cursor stutter

### ISSUE THREAD

**Issue by Luxvao** [hyprwm/Hyprland#8084]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

[systeminfo.txt](https://github.com/user-attachments/files/17346906/systeminfo.txt)

### Description

The cursor stutters after a mouse has been left alone for a few seconds and is then moved. The first bad commit is:
```
e6cf643f5ab1c1545fb858ab1fd9d7538ef9e0f3 is the first bad commit
commit e6cf643f5ab1c1545fb858ab1fd9d7538ef9e0f3
Author: Vaxry <43317083+vaxerski@users.noreply.github.com>
Date:   Wed Sep 18 18:47:53 2024 +0100

    pointermgr: Hide hardware cursor on leave (#7806)

 src/managers/PointerManager.cpp | 31 +++++++++++++++++++++++++++++--
 1 file changed, 29 insertions(+), 2 deletions(-)
```
Side note: I deleted a bunch of `[ERR] rbo: glCheckFramebufferStatus failed` lines from the hyprland log. There were so many that the file had ~30k lines. It now only has ~7k

### How to reproduce

1. Run  hyprland v0.44.0+
2. Don't move the mouse for at least 5 seconds
3. Move the mouse quickly. It should stutter as well as anything else happening on screen

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/17346867/hyprland.log)

**Comment by Luxvao** [comment]
Apparently the fix is quite easy. I just had to disable hardware cursors. Though it's still a bug and should probably be addressed, no? I'll leave the issue open. Feel free to close

**Comment by vaxerski** [comment]
apparently you ticked the "I searched issues" box without actually doing so and thus waste both of us' time #8036

**Comment by Luxvao** [comment]
@vaxerski Sorry. Must've missed it. I did search for it though.
