### ISSUE TITLE
VRAM and RAM Memory Leak on config reload

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [hyprwm/Hyprland#809]
## How to reproduce

1. To monitor memory usage open `nvtop` (displays both RAM and VRAM) or run `watch -n 1 -d nvidia-smi` (VRAM only).

2. Run `hyprctl reload` few times

## Expected behavior

VRAM / RAM usage +- stays at the level it was.

## Actual behavior

After about 20 reloads VRAM peaks at about max capacity.
Further reloads don't increase usage, but it never decreases on its own.

Here is how it looks in `nvtop`:

<details>
  <summary>nvtop</summary>

![screenshot2](https://user-images.githubusercontent.com/14999778/194642012-5d604be7-b185-46c1-ad48-ae33de7b92f8.png)
![screenshot3](https://user-images.githubusercontent.com/14999778/194642028-c3627eb3-144f-4313-adc3-fc41ec7c288e.png)

</details>

## System

* Arch Linux latest
* linux-zen 5.19.13
* nvidia-dkms 515.76-1 ([Instructions](https://wiki.hyprland.org/Nvidia/) from the wiki applied except fixes for flickering)
* Hyprland 0.15.1beta, generated config + few bindings, nothing fancy

Log, obtained by commenting -> saving -> uncommenting -> saving one option (binding) a bunch of times (I didn't realized then that you can trigger the same behavior with `hyprctl reload`):
[hyprland-reload-vram-memoryleak.log](https://github.com/hyprwm/Hyprland/files/9737135/hyprland-reload-vram-memoryleak.log)

Originally mentioned in https://github.com/hyprwm/Hyprland/issues/357#issuecomment-1271873742

(sway's reload works as expected)

**Comment by vaxerski** [comment]
does `hyprctl dispatch forcerendererreload 1` leak too?

**Comment by MahouShoujoMivutilde** [comment]
Yeah

<details>
  <summary>pic</summary>

![screenshot4](https://user-images.githubusercontent.com/14999778/194645051-e6b0a7b7-5b73-4241-9133-c3061f6d0ba4.png)

</details>

**Comment by vaxerski** [comment]
dope

**Comment by vaxerski** [comment]
check with 33d264eaa78b10d38d483900a293d09eff00faad

**Comment by MahouShoujoMivutilde** [comment]
<details>
  <summary>Still leaks</summary>

Here is `hyprctl dispatch forcerendererreload 1` followed by `hyprctl reload`

![screenshot5](https://user-images.githubusercontent.com/14999778/194646582-7275f18f-4fef-4dae-b831-bc494bf32730.png)


</details>

**Comment by vaxerski** [comment]
fixed in abc2d442dd41cfd41e5c88795a4e892a6d2750dc

**Comment by MahouShoujoMivutilde** [comment]
Yeah, works fine now. Thanks!
