### ISSUE TITLE
crashes an launch

### ISSUE THREAD

**Issue by k1f1t** [hyprwm/Hyprland#8094]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Linux archvm 6.11.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000 x86_64 GNU/Linux
```

</details>

### Description

Hyprland crashes on start, "failling on Hyprland", crashes in terminal emulator (kitty on gnome) and in clear arch terminal with just text mode

### How to reproduce

Nope, I have just installed and that's all

### Crash reports, logs, images, videos

Here you have folder with what I found:
[link](https://drive.google.com/drive/folders/1F4t0KqWWCUkbfx6HTtFkGM328UTkytif?usp=sharing)

**Comment by vaxerski** [comment]
```
[LOG] [AQ] Connected to a wayland compositor: GNOME
[LOG] [AQ] Got registry at 0x5e7d4586fef0
[LOG] [AQ] Output WAYLAND-1: initialized
[CRITICAL] m_pAqBackend couldn't start! This usually means aquamarine could not find a GPU or encountered some issues. Make sure you're running either on a tty or on a Wayland session, NOT an X11 one.
```

GNOME doesn't support necessary protocols for a nested session. Why are you running it on gnome anyways? Please confront the wiki's master tutorial.
