### ISSUE TITLE
native Wayland Vesktop freezes system

### ISSUE THREAD

**Issue by Projectzblack** [hyprwm/Hyprland#8102]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit 1822707c7e7394ce8c7572f2fe890763a307f499  (drm-syncobj: fix crash on missing timelines).
Date: Sat Oct 12 18:56:46 2024
Tag: v0.44.0-33-g1822707c, commits: 5332
built against aquamarine 0.4.2


flags set:
debug


System Information:
System name: Linux
Node name: Alpha15
Release: 6.11.1-x64v4-xanmod1
Version: #0~20240930.ga9fe44d SMP PREEMPT_DYNAMIC Mon Sep 30 17:08:58 UTC


GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Description

When switching to the workspace that Vesktop that is running on Wayland natively often causes the whole system to freeze (Can't switch to tty and can't connect to ssh. must hard reboot).

When Vesktop is unfocused, the window sometimes turns white. (probably GPU rendering stop while it's not focused) and switching to it causes the problem.

I also sometimes see other behaviors when switching:

- Hyprland freezes for a second and crashed back to the login manager.

- Hyprland freezes for a second and unfreezes. Vesktop re-renders but show some graphic glitches that disappear when the cursor is moved to.

- Vesktop re-renders and works as expected.

This doesn't happen when Vesktop is running under XWayland. 

Similar to #6123 

### How to reproduce

1. Run Vesktop (Flatpak) with `--socket=wayland` and `--ozone-platform-hint=auto` flag
2. Switch to another workspace
3. Switch back to the Vesktop workspace

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/17355096/hyprland.log)

**Comment by vaxerski** [comment]
you are getting a gpu reset. The total freeze is odd for sure, but everything else just points to vesktop committing a gpu fault.

Can you ssh into your system when it freezes, attach gdb to hyprland, and provide the `bt -full`?

**Comment by vaxerski** [comment]
this just looks like a gpu reset. Probably vesktop's fault
