### ISSUE TITLE
Very few scaling options

### ISSUE THREAD

**Issue by dxwil** [hyprwm/Hyprland#8109]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: 2024-09-08
Tag: v0.43.0, commits: 0f594732b063a90d44df8c5d402d658f27471dfe

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.10.6-asahi
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
apple,agx-t6020

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11pre689866.c31898adf5a8"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:

======Config-Start======


Config File: /home/dxwil/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/l43j2pr459mshapy67vi1q8xg53fgd49-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$mainMod=SUPER
decoration {
  blur {
    size=5
  }
  drop_shadow=false
  inactive_opacity=0.8
  rounding=7
}

dwindle {
  preserve_split=true
  pseudotile=true
}

general {
  border_size=2
  col.active_border=rgb(A5BEDD)
  col.inactive_border=rgba(595959aa)
  gaps_in=2
  gaps_out=6
  resize_on_border=true
}

gestures {
  workspace_swipe=true
}

input {
  touchpad {
    clickfinger_behavior=true
    natural_scroll=yes
    scroll_factor=0.17
  }
  follow_mouse=1
  kb_layout=us,lt
  kb_options=grp:lalt_lshift_toggle
  kb_options=caps:swapescape
  repeat_delay=300
  repeat_rate=50
  sensitivity=-0.1
}

misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
  force_default_wallpaper=-1
  vrr=2
}
bind=$mainMod, Q, exec, kitty
bind=$mainMod, space, exec, eww update workspaces_visible=false && tofi-drun && eww update workspaces_visible=true
bind=$mainMod, W, exec, firefox
bind=$mainMod, C, killactive,
bind=$mainMod, M, exit,
bind=$mainMod, E, exec, nautilus
bind=$mainMod, V, togglefloating,
bind=$mainMod, P, pseudo,
bind=$mainMod, J, togglesplit,
bind=$mainMod, left, movefocus, l
bind=$mainMod, right, movefocus, r
bind=$mainMod, up, movefocus, u
bind=$mainMod, down, movefocus, d
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod SHIFT, 1, movetoworkspace, 1
bind=$mainMod SHIFT, 2, movetoworkspace, 2
bind=$mainMod SHIFT, 3, movetoworkspace, 3
bind=$mainMod SHIFT, 4, movetoworkspace, 4
bind=$mainMod SHIFT, 5, movetoworkspace, 5
bind=$mainMod SHIFT, 6, movetoworkspace, 6
bind=$mainMod SHIFT, 7, movetoworkspace, 7
bind=$mainMod SHIFT, 8, movetoworkspace, 8
bind=$mainMod SHIFT, 9, movetoworkspace, 9
bind=$mainMod SHIFT, 0, movetoworkspace, 10
bind=CTRL_SHIFT, 4, exec, hyprshot -o ~/Pictures/Screenshots/ -m region
bind=, XF86AudioMute, exec, ~/.config/eww/scripts/volume.sh mute
bind=, XF86MonBrightnessUp, exec, brillo -q -u 50000 -A 5 && eww update current_brightness=$(brillo | awk '{printf("%.0f%%", $1)}')
bind=, XF86MonBrightnessDown, exec, brillo -q -u 50000 -U 5 && eww update current_brightness=$(brillo | awk '{printf("%.0f%%", $1)}')
binde=, XF86AudioRaiseVolume, exec, ~/.config/eww/scripts/volume.sh up
binde=, XF86AudioLowerVolume, exec, ~/.config/eww/scripts/volume.sh down
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, Control_L, movewindow
bindm=$mainMod, mouse:273, resizewindow
bindm=$mainMod, ALT_L, resizewindow
exec-once=hyprpaper
exec-once=eww open bar
exec-once=hyprctl setcursor macOS 20
monitor=eDP-1,preferred,auto,2,bitdepth,10
monitor=HDMI-A-1,3440x1440@100,auto,1
windowrulev2=suppressevent maximize, class:.*

======Config-End========
```

</details>

### Description

On a Macbook Pro M2 Pro 14inch, very few scaling options are accepted. The options accepted are for example 1.3, and 2.0, nothing in between and these both are too big and too small. On macOS with a third party display app, I can get a HiDPI scaling option every 30 horizontal pixels for example. Is there any option to enable more scaling factors in hyprland?

### How to reproduce

Have the same resolution display as the Macbook Pro M2 Pro 14inch

**Comment by vaxerski** [comment]
`debug:disable_scale_checks` https://wiki.hyprland.org/Configuring/Variables/#debug

Not recommended.

**Comment by dxwil** [comment]
I calculated the correct scale and set it, but now, as probably expected, there is a line of pixels at the left and bottom that are kind of not used. I didn't notice them at first because they were black, but when I moved content or my mouse to them, they became white and started flickering white. Is it possible to just make them black, because then I wouldn't even know that they are there.

**Comment by vaxerski** [comment]
no such mechanism is there because generally we do not expect users to use those scales, that's why I said not recommended

**Comment by dxwil** [comment]
Yeah but there are no accepted scales that are usable. So nothing I can do?

**Comment by vaxerski** [comment]
try disabling logo (`misc:disable_hyprland_logo`) and see if that doesnt get rid of the bug

**Comment by dxwil** [comment]
I pasted my system info in the required field above, my whole config is there. I have the logo disabled.

**Comment by vaxerski** [comment]
my bad, missed that. Can you just for testing try disabling damage tracking? Set it to 1.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/17357082/patch.txt)
also try this

**Comment by dxwil** [comment]
So the patch and damage tracking didn't change anything, but I discovered that this is actually a hyprpaper bug. Without hyprpaper, the mouse artifacts are not left behind even on custom scaling. And I double checked that this doesn't happen on 2x scale, it doesn't. So a combination of hyprpaper and custom scale.

**Comment by dxwil** [comment]
Basically when I move my mouse to the very left and bottom of the screen, it is still slightly visible (more precisely, the white outline of the mouse) and moving along those edges leaves the white mouse pixels behind, which then also start weirdly moving and glitch even tho I move my mouse away

**Comment by vaxerski** [comment]
what if you use --no-fractional with hyprpaper? what about swaybg?

**Comment by dxwil** [comment]
Happens with --no-fractional hyprpaper, does not happen with swaybg

**Comment by vaxerski** [comment]
you got a workaround then
