### ISSUE TITLE
What use in place of no_gaps_when_only

### ISSUE THREAD

**Issue by cjuniorfox** [hyprwm/Hyprland#8114]
### Description

Hi,
At [this commit](https://github.com/hyprwm/Hyprland/commit/d655a10381f01212635f2eadd69e1f22930f8f06#diff-9993bc2bbc311ab9e2cb878dbc44bc4f9d5edc5216b9aa3172e4b10b9b0d61f5L450) you "nuked" `no_gaps_when_only` that was used to remove gaps and borders to fill the screen when there was only one Window. This was even at the default version of `hyprland.conf` file. What do we would use in place?

Suggestion, Instead of suddenly discontinuing configurations, would be nice if some notification warning should be issued to alert when some instruction in use at the config file is to be discontinued.

Also, if you agree with this notification warning idea, would be very nice if a drop-in replacement for the instruction to be discontinued would be presented at this notification allowing users to update the configuration file beforehand and with no pain.

**Comment by MahouShoujoMivutilde** [comment]
https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps

**Comment by vaxerski** [comment]
link above relevant

> Suggestion, Instead of suddenly discontinuing configurations, would be nice if some notification warning should be issued to alert when some instruction in use at the config file is to be discontinued.

No point, I mention removed features in release notes. If you use -git, it's your responsibility to catch up and update when you have some spare time.

**Comment by cjuniorfox** [comment]
> link above relevant
> 
> > Suggestion, Instead of suddenly discontinuing configurations, would be nice if some notification warning should be issued to alert when some instruction in use at the config file is to be discontinued.
> 
> No point, I mention removed features in release notes. If you use -git, it's your responsibility to catch up and update when you have some spare time.

People, in general, do not have time to read the changelog for the compositor they are using regularly. People work and have other duties than fiddling with their desktop environment every day.
Deprecating instructions and configuration it's a common thing and helps to keep the base code clear, but PEOPLE NEEDS TO KNOW WHAT IS GOING ON.
With Hyprland, every update is a surprise, like the support for mirroring virtual screens with Sunshine that you suddenly dropped the support days ago, which has impacted the lives of many users. From time to time, some instruction is discontinued from your compositor with no notification for the users beforehand and for anyone who uses your compositor, the excuse is always to "Read the changelog".
I think Hyprland is an amazing product, but things like that are very frustrating.

**Comment by cjuniorfox** [comment]
Huum, let's see:
`pacman -Su`
User: *Wow! 312 updates. Let's read the changelog one by one before updating.*
After spending two days reading all of them, `pacman -Su` now has 442 updates. "*On sh#t, there are more than 130 changelogs to read now...*"
 
Your project is not only a DIY project but a great one. One of the best I have seen in years. I'm a real enthusiast of Hyprland. With **Ublue project** I even created my own Immutable version of Hyprland. You can check it out by [following here](https://github.com/cjuniorfox/hyprland-atomic/). I believe that your goal is to have Hyprland on a daily basis for many users all over the place, which is a great thing and is turning into a reality. Hyprland is stable and you are very committed to resolving the issues as fast as possible. I thank you for that.

I just made a suggestion. Would be easier for people to know beforehand from the compositor itself that SOON, the user would need to change some settings beforehand.

**Comment by vaxerski** [comment]
...you can also just read the changelog when you notice something broke?

Again, breaking changes are mentioned at the top of the changelog of a release.

Read the last paragraph of what I said in my last message.

**Comment by cjuniorfox** [comment]
I wasn't talking necessarily about me. Some people look at my computer, see Hyprland, and ask me, how to install that, I don't have the confidence to incentivize them because many of them just want to use the computer without the need to customize many things. If you have a look at the immutable version I created, after installing, the user has a basic but complete experience with Hyprland.

Explaining to people, who want just to use the computer, that they will NEED to regularly read the changelog for things they are using because their setup will break from time to time is discouraging.

I know that many users of a TWM love fiddling with their setup to take a snapshot (with a hyprshot) and post their printscreen on Reddit, but there are people who see the great big value of a TWM which is productivity.

Hyprland's documentation is great, but making a life of people easier, could help Hyprland get traction with a broader group of people, which would be great.

**Comment by vaxerski** [comment]
Again, I don't see a better alternative other than "never remove options" which is not what we want to do.

**Comment by MahouShoujoMivutilde** [comment]
Have a separate pinned and locked issue (so people could subscribe to it, and receive notifications) for replaced / phased out options / other breaking changes.

E.g. like this

```
https://github.com/hrsh7th/nvim-cmp/issues/231
```

So, what changed and will no longer work, and what to use instead (if applicable).

@cjuniorfox Barring that, from the user side - `diff`-ing wiki's repo between releases (or approximate dates of offending hyprland commits) works great to track changes and possible/suggested replacements too.

**Comment by vaxerski** [comment]
@MahouShoujoMivutilde's solution aint bad.

> One solution could be:
feature x is deprecated, use y instead. ( in the error message)

Read my message https://github.com/hyprwm/Hyprland/issues/8114#issuecomment-2411147184

**Comment by HirschBerge** [comment]
> @MahouShoujoMivutilde's solution aint bad.
> 
> > One solution could be:
> feature x is deprecated, use y instead. ( in the error message)
> 
> Read my message 

I may be different than many, but in NixOS their implementation of this is well done. It still builds for <seems to depend on package/option> and then breaks. If it's deprecated it will  show you a nice warning that is hard to miss, or fail and show you a red error telling you what to do (doesn't fix stupid or people who can't read, but that's not who we should care about).

That said, it's easier to implement in that situation and less so in Hyprland's. Not sure of a way to implement, but perhaps having an option to `xdg-open https://hyprland-version-release-notes` when first running a new version? I think other suggestions here are maybe more realistic though.
