### ISSUE TITLE
Sharp-Edged Shadows

### ISSUE THREAD

**Issue by BowlBird** [hyprwm/Hyprland#8123]
# What do I mean
In some window managers you have the ability to have completely sharp shadows, such as swayfx, awesome, and probably others. 
# The problem
Hyprland, however, does not have this ability. You can set the shadow power only so high so shadows will always look generally blurred. I understand this is how most people will probably want their shadows to look, however it would be nice to be able to completely sharpen the shadows so it could look like this:
![5](https://github.com/user-attachments/assets/462908e3-d907-4015-8444-2f200bf75840)
# What I've tried
I looked into existing plugins, and the official extra borders plugin seemed to be the closest bet, but it doesn't support an offset which would be necessary for this effect.

Thanks!

**Comment by vaxerski** [comment]
reasonable

**Comment by vaxerski** [comment]
d1638a09bacd84b994de3f77746b74f427b9d41e
