### ISSUE TITLE
Need opinions on GUI

### ISSUE THREAD

**Issue by nnyyxxxx** [hyprwm/Hyprland#8124]
### Description

SO, I have made this recently: https://github.com/nnyyxxxx/hyprgui it is a GUI for configuring Hyprland built entirely in Rust 🦀 I have made an issue before regarding this BUT that was before I decided to remake it.

The point of this issue to gather opinions on it from most notably @vaxerski and other people apart of HyprWM, as I have spent a great deal of time on it. I have linked a Preview below of what it currently looks like.

It's populated with most of the values from the documentation, includes tooltips explaining each feature (Uses descriptions provided in documentation), etc.

The GUI also includes it's own custom-made parser: https://github.com/nnyyxxxx/hyprparser

I know there is another GUI that exists (Hyprset, was informed by a member of HyprWM) but it seems outdated and incomplete.

The GUI uses gtk, btw.

![image](https://github.com/user-attachments/assets/2e1607b1-88df-4edf-94d8-27c1d5c6af3c)

**Comment by vaxerski** [comment]
> The point of this issue to gather opinions on it from most notably @vaxerski and other people apart of HyprWM, as I have spent a great deal of time on it. I have linked a Preview below of what it currently looks like.

This should be done in a discussion, or on discord/matrix.

I don't know what you want me to say tbh.

We have some utils planned for the future (as you may have noticed recently the ecosystem is expanding) but they definitely won't be gtk.

Feel free to develop utilities for hyprland, everyone is welcome to make stuff for hl.

**Comment by nnyyxxxx** [comment]
> This should be done in a discussion, or on discord/matrix.

Thanks yeah ill do that
