### ISSUE TITLE
the Hyprland unix sockets are located in the old location

### ISSUE THREAD

**Issue by lolplayer69420** [hyprwm/Hyprland#8131]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

0.44.0 (pacman)
0.28.0 (hyprctl version, `Hyprland --systeminfo` and `hyprctl systeminfo -c`    dont work either)

### Description

I tried launching `astal-hyprland`  , but it failed because it couldnt find the hyprland sockets, diving deeper into the problem i noticed that the sockets are not located in `  $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE`   but in `  /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE`  ,

### How to reproduce

i dont know, i just stumbled upon that

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/17388201/hyprland.log)

**Comment by fufexan** [comment]
> 0.28.0 (hyprctl version, Hyprland --systeminfo and hyprctl systeminfo -c dont work either)

looks like you have an ancient version somewhere on the system.

**Comment by lolplayer69420** [comment]
yeah, it was that, i got confused, sorry
