### ISSUE TITLE
Middle click not working for anything but pasting text/scrolling globally & opening links on new tabs in browser

### ISSUE THREAD

**Issue by almonds-game** [hyprwm/Hyprland#8149]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)
```

</details>

### Description

I have a ThinkPad L14 Gen 3 (AMD) and am trying to use the mouse buttons above the touchpad for games. However, clicking the middle mouse button does nothing (except paste text, the default behavior in hyprland if I'm not mistaken). I've tried using an external mouse, clicking the scroll wheel does nothing either. I figured it was an issue with the game itself, but when testing my mouse input on a few sites ((https://www.onlinemictest.com/mouse-test/), https://cpstest.org/mouse-test/) my middle click is not detected. However, pressing the button and using the trackpoint does in fact allow me to scroll in any program. 

I'm running Fedora 40 minimal, I would update Hyprland by building from source but upon trying to build, it tells me my version of cmake is too outdated. Tried updating cmake, but the version installed as of writing this (3.28.2) is the latest version in the repo.

### How to reproduce

Here is the input part of my config:

```
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    scroll_method = on_button_down
    scroll_button = 274 
    # mouse:274 results in error, hence the value just being "274"
    follow_mouse = 2
    touchpad {
        natural_scroll = yes 
        scroll_factor = 0.2
        middle_button_emulation = true
    }
    sensitivity = 0.2
}
```

**Comment by vaxerski** [comment]
I can't take your report as valid until you update to 0.44.0 or git. If on fedora, IIRC solopasha's copr has an up-to-date hyprland

**Comment by almonds-game** [comment]
> I can't take your report as valid until you update to 0.44.0 or git. If on fedora, IIRC solopasha's copr has an up-to-date hyprland
> 
> 0.39.1 is _extremely_ outdated

Thank you, I didn't even think of it possibly being on copr, I'll check if it's there and if the issue persists I'll repost the issue, seriously thank you for pointing me there!
