### ISSUE TITLE
New windows do not swallow terminals when spawned from scripts

### ISSUE THREAD

**Issue by micamoan** [hyprwm/Hyprland#815]
Window swallowing behaves differently depending on whether the window is spawned directly from a terminal command or from a script.

## Steps to reproduce:

Run a command that spawns a new window (for example, mpv or swayimg). The terminal is swallowed as it should be. Now, plug that same command into a bash script, then run the script in the terminal.

## Expected outcome:

The new window should spawn and swallow the terminal, same as if you'd run the command directly.

## Noted outcome:

The new window is spawned, but the terminal is not swallowed.

**Comment by vaxerski** [comment]
what do you expect? it comes from a different process...?

**Comment by micamoan** [comment]
For example here's the bit in my qtile config that handles window swallowing:

```@hook.subscribe.client_new
def _swallow(window):
    pid = window.window.get_net_wm_pid()
    ppid = psutil.Process(pid).ppid()
    cpids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
    for i in range(5):
        if not ppid:
            return
        if ppid in cpids:
            parent = window.qtile.windows_map.get(cpids[ppid])
            parent.minimized = True
            window.parent = parent
            return
        ppid = psutil.Process(ppid).ppid()


@hook.subscribe.client_killed
def _unswallow(window):
    if hasattr(window, 'parent'):
        window.parent.minimized = False```

And it swallows terminal windows whether you're launching from the terminal directly or from a script that's running. Would it be possible to make swallowing in Hyprland work this way?

**Comment by vaxerski** [comment]
this is how it works, though.

**Comment by micamoan** [comment]
Just rebuilt from latest and, sure enough, it's working as I expect it to now.

**Comment by Eragonfr** [comment]
I still found this bug in the latest version.
I launch foot, inside of foot I launch ranger. And from ranger I open a file with gimp. Gimp will not swallow the window.
But if I launch gimp directly from foot (in my shell, fish) it will swallow the foot window.
