### ISSUE TITLE
Group members disappear when you move the group to another monitor

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#8153]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
latest git (my hyprctl version is broken since the bisecting party)
```

</details>

### Description

Regressor: https://github.com/hyprwm/Hyprland/commit/16a9c16d9f99bd8be9f1bb15442b001fdf2ea759

### How to reproduce

- Open a **tiled** group with 2 or more members.
- Use the movetoworkspace dispatcher to move it to a workspace on a different monitor.
- Change the focus to another group member.
- The group member is gone.

**Comment by htomeht** [comment]
I have noticed that when moving a group to different monitors and then switching between clients of the group, other clients become invisible until I move the group (with invisible client open) to the original monitor and back again. This must be done for each client.

**Comment by Aqa-Ib** [comment]
yeah that is this same bug, I noticed today.

**Comment by Aqa-Ib** [comment]
@thejch excuse me, could you please give us a hint of where could be the regression from https://github.com/hyprwm/Hyprland/commit/16a9c16d9f99bd8be9f1bb15442b001fdf2ea759 ?
