### ISSUE TITLE
Hyprland defaults to 120Hz Refresh Rate when i try to use 165Hz

### ISSUE THREAD

**Issue by EuroBlue** [hyprwm/Hyprland#8154]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: archpc
Release: 6.11.3-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:02 +0000


GPU information: 
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

</details>

### Description

When I try to set my my monitor refresh rate to my monitors max rate 165Hz. using the following line in my hyprland.conf
`monitor=,2560x1440@165,auto,1`
it dose not work and defaults to 120Hz which is my monitors preferred.
I works as expected when i use
`monitor=,2560x1440@60,auto,1` or
`monitor=,2560x1440@144,auto,1` for example.
This is my monitor LG Electronics 32GN600-B
only this monitor is used. I do not have any other monitor.
Also when i use
`monitor=,highres@highrr,auto,1` It still uses 144Hz. Apparently hyprland can't detect that my monitor has 165Hz support or something.

### How to reproduce

1. Have a 165Hz supported monitor
2. Use `monitor=,2560x1440@165,auto,1` in your config file.

**Comment by EuroBlue** [comment]
Yes the available modes are completely bollocks 

[euroblue@archpc ~]$ hyprctl monitors all
Monitor HDMI-A-1 (ID 0):
	2560x1440@143.93300 at 0x0
	description: LG Electronics LG ULTRAGEAR [[REDACTED]]
	make: LG Electronics
	model: LG ULTRAGEAR
	serial: [[REDACTED]]
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 24 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@120.00Hz 3840x2160@59.94Hz 3840x2160@50.00Hz 3840x2160@29.97Hz 3840x2160@25.00Hz 3840x2160@23.98Hz 2560x1440@143.93Hz 2560x1440@59.95Hz 1920x1080@119.88Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@60.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@59.94Hz

**Comment by EuroBlue** [comment]
Hey, so i started to think that it has something to do with m HDMI Cable. I ordered a DP 2.1 that should arrive tomorrow. I will update the issue after i test it.

**Comment by Karidus-423** [comment]
Do you have wlr-randr? I had this same issue and setting the refresh it helped hyprland see what I wanted to use.

**Comment by vaxerski** [comment]
hyprland lists what your monitor sends via the EDID to the driver. So if your mode is not there, it's either:
 - driver doesn't support it
 - device doesn't support it
 - configuration doesn't support it (e.g. old cable)
 
Although sometimes you _can_ force a custom mode and it might work, it's not a great solution, because usually there is a _reason_ why the mode isn't there

**Comment by EuroBlue** [comment]
Hey, so this issue is closed. I switched to Displayport 2.1 and it works perfectly. Sorry for the disturbance hopefully this "issue" will help someone else.
