### ISSUE TITLE
Hyprland doesnt start

### ISSUE THREAD

**Issue by kkflto** [hyprwm/Hyprland#8162]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: gentoo
Release: 6.10.13-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Fri Oct  4 16:27:35 -00 2024


GPU information: 
33:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev d1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"


plugins:
	unknown: not runtime
```

</details>

### Description

Trying to launch hyprland, but it crashes with a pcilib error

### How to reproduce

Type Hyprland in the tty

### Crash reports, logs, images, videos

[hyprlandCrashReport5392.txt](https://github.com/user-attachments/files/17437507/hyprlandCrashReport5392.txt)

**Comment by ZeyadMoustafaKamal** [comment]
Well can you post what you are getting from the tty ?? I guess you may try something like

`Hyprland > hyprlogs.log &`

and then open another desktop environment and post the content of that file here. But wait for like 5 seconds until Hyprland process is finished.

**Comment by kkflto** [comment]
[log.txt](https://github.com/user-attachments/files/17437914/log.txt), in the tty it also says `pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted` Dunno why it doesnt show in the log

It may not actually be a hyrland issue.

```
doas lspci -k | grep -A 3 -E "(VGA|3D)"
pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
33:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] (rev d1)
	Subsystem: Lenovo Device 50b4
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

**Comment by vaxerski** [comment]
my guess is you compiled something wrong. Can you build aq and hl in debug and get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by kkflto** [comment]
It may be a clang issue. I'm using 19.1.2+libcxx. I tried compiling all the dependencies with gcc 14 and it now works

**Comment by kkflto** [comment]
However now I'm getting `✖ Headers version mismatch. Please run hyprpm update to fix those.` When I run `hyprpm update`
