### ISSUE TITLE
Better gaming support || Lutris errors

### ISSUE THREAD

**Issue by TropicLegend** [hyprwm/Hyprland#818]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

Steps to reproduce:
Open lutris
Try starting Overwatch / Battle.net Launcher

Expected behavior:
Seeing the launcher in a normal way so I can start the game. - Already tested, works on KDE Plasma (Wayland)

Noted outcome:
Just a blackscreen and some errors in the lutris log.

https://pastebin.com/bcKALjKg

It could be some misconfiguration of Hyprland, but I couldn't find any solutions.

**Comment by vaxerski** [comment]
testing in KDE plasma does not help much. Test in sway, please.

**Comment by freundTech** [comment]
> Already tested, works on KDE Plasma (Wayland)
Have you tested it on the same PC? There are other people reporting issues with Battle.net not working independent of desktop environment.

The errors in your lutris log are all normal and also appear when battle.net is working.

**Comment by TropicLegend** [comment]
> 

Yes, I've tried it on the exact same PC. I can even switch between the compositors and see it working on KDE but not on Hyprland. It's really strange.

**Comment by TropicLegend** [comment]
Which other possible problems could cause this kind of behavior? 
Are there maybe some libraries or dependencies that I would have to install for it to work?

**Comment by NotAShelf** [comment]
I don't know if you are still having this issue, but this was acknowledged as an issue on Battle.net's end and was fixed recently.

**Comment by TropicLegend** [comment]
I don't know why, but it has gotten even worse. Now lutris crashes when starting up Battle.net if I'm using hyprland.
```
(lutris:5805): Gtk-WARNING **: 20:33:35.185: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached

(lutris:5805): Gtk-WARNING **: 20:33:35.195: Creating a portal monitor failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached
Gdk-Message: 20:33:35.196: Error flushing display: Broken pipe
```

**Comment by TropicLegend** [comment]
This error doesn't happen every time I start up Overwatch/Battle.net though. 
Now it worked but the battle.net launcher window is still black
Full Lutris log, when the Battle.net Launcher starts but shows a black window:

```
2022-10-15 20:34:44,943: Starting Lutris 0.5.11
2022-10-15 20:34:44,998: Using NVIDIA drivers 515.76 for x86_64
2022-10-15 20:34:44,999: GPU: NVIDIA GeForce RTX 3080 Ti
2022-10-15 20:34:44,999: GPU: 10DE:2208 1458:4088 (nvidia drivers)
2022-10-15 20:34:45,091: Startup complete

(lutris:7153): Gtk-WARNING **: 20:35:29.261: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached

(lutris:7153): Gtk-WARNING **: 20:35:29.275: Creating a portal monitor failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached
lutris-wrapper: Overwatch
Started initial process 8187 from gamemoderun /home/amani/.local/share/lutris/runners/wine/caffe-7.18-x86_64/bin/wine /home/amani/Games/overwatch/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch Pro
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
fsync: up and running.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
[1015/203533.639:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
[1015/203534.066:ERROR:dxva_video_decode_accelerator_win.cc(1397)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not found. (0x7E)
[1015/203534.067:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
[1015/203534.311:ERROR:dxva_video_decode_accelerator_win.cc(1320)] DXVAVDA fatal error: Could not load msmpeg2vdec.dll: Module not found. (0x7E)
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
[1015/203534.669:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
[1015/203536.932:ERROR:angle_platform_impl.cc(40)] rx::SwapChain11::reset(615): Could not create additional swap chains or offscreen surfaces, HRESULT: 0x80070057
[1015/203536.932:ERROR:gl_surface_egl.cc(787)] EGL Driver message (Critical) eglCreateWindowSurface: Bad allocation.
[1015/203536.932:ERROR:gl_surface_egl.cc(1394)] eglCreateWindowSurface failed with error EGL_BAD_ALLOC
[1015/203536.932:ERROR:in_process_command_buffer.cc(450)] ContextResult::kSurfaceFailure: Failed to create surface.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

```

> I don't know why, but it has gotten even worse. Now lutris crashes when starting up Battle.net if I'm using hyprland.
> 
> Lutris log:
> 
> ```
> (lutris:5805): Gtk-WARNING **: 20:33:35.185: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached
> 
> (lutris:5805): Gtk-WARNING **: 20:33:35.195: Creating a portal monitor failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code24: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached
> Gdk-Message: 20:33:35.196: Error flushing display: Broken pipe
> ```

**Comment by NotAShelf** [comment]
Please confirm this is present on other wlroots based compositors (e.g. sway)

**Comment by umop3plsdn** [comment]
the battle.net lutris thing happens to me even on X it'snot hyprland specific

**Comment by EysseW** [comment]
Is there a workaround? G haven't been able to play OW2 because of it.
