### ISSUE TITLE
Hyprland wont start on brand new arch install

### ISSUE THREAD

**Issue by tysongrosz** [hyprwm/Hyprland#8184]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

I apologize for the photos, but i cant copy/paste things off the machine I'm having issues with.
Hyprland --systeminfo returns the following

### Description

running a brand new install of arch. Absolutely bare minimum nothing installed besides defaults, iwd, and nano. No graphics server or graphics drivers installed.  I followed the installation master guide and installed with pacman, but when i execute 'Hyprland', it returns the following:

![IMG_20241019_231814](https://github.com/user-attachments/assets/fadd6dd4-eb19-4488-b471-8bfa1a6fb342)

The error appears to be occuring in the last 5 lines

### How to reproduce

brand new install of arch installation. install hyprland with pacman and attempt to start.

**Comment by tysongrosz** [comment]
sorry forgot to attach output of hyprland --systeminfo

![IMG_20241019_232337](https://github.com/user-attachments/assets/e03448f8-7517-48dd-ab1d-2663359ad190)

**Comment by myamusashi** [comment]
https://wiki.hyprland.org/Crashes-and-Bugs/

**Comment by tysongrosz** [comment]
I didnt see my problem on there anywhere

**Comment by ZeyadMoustafaKamal** [comment]
we need the crash report. one way to get these things is to install another deskstop environment to get all files we need like the [crash report](https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-the-hyprland-crash-report).

**Comment by ZeyadMoustafaKamal** [comment]
Are you running it as a root ? if yes then try with a regular user and install `sudo` package and configure it.

**Comment by tysongrosz** [comment]
I am not running it as root. I already had sudo installed and all that

**Comment by tysongrosz** [comment]
does hyprland require graphics drivers at all? I havent installed any, and i suspect that could be my issue? i cant find any info about that in any of the wiki articles for either arch or hyprland

**Comment by Eugenenoble2005** [comment]
Are you sure you have permission to write  your home directory? try:

`sudo chown -R $USER .home/{your-user-name}`

**Comment by tysongrosz** [comment]
Im currently redoing my arch install. Ill try that first thing once im back to where I was

**Comment by tysongrosz** [comment]
During setup this time i made sure i had write permissions. Same error now after reinstalling everything

**Comment by kkflto** [comment]
> does hyprland require graphics drivers at all? I havent installed any, and i suspect that could be my issue? i cant find any info about that in any of the wiki articles for either arch or hyprland

Does a graphic app need graphic drivers?

**Comment by tysongrosz** [comment]
No that was the thing. I knew it probably needed graphics drivers, but i have no clue which ones to install(same ones i needed for X11?). That is why i prominantly stated i didnt have any. The installation guide only mentions graphics drivers for NVIDIA chips. I have never installed wayland or hyprland before, so I dont know what to download. do you know the name of a package i can download containing drivers for my gpu(listed above)?

**Comment by tysongrosz** [comment]
All the videos i can find of people installing Hyprland are people who already have a GUI installed and therefore already have graphics drivers.

**Comment by tysongrosz** [comment]
I have found and installed the proper drivers(Included in mesa). my error persists

**Comment by tysongrosz** [comment]
fixed. I hadnt installed polkit and missed its mention in the Arch wiki page for Hyprland
