### ISSUE TITLE
Text Selection not working in GTK apps

### ISSUE THREAD

**Issue by joelmathewthomas** [hyprwm/Hyprland#8187]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit e4a26f4f1d9d30569b9e7e6c265fccfd42fa5d72  (dispatchers: allow leading whitespace in window parameter (8016)).
Date: Tue Oct 8 22:20:06 2024
Tag: v0.44.0-14-ge4a26f4f, commits: 5313
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: void
Release: 6.11.2-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28e1] (rev a1) (prog-if 00 [VGA controller])
35:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 0a) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  560.35.03  Release Build  (archlinux-builder@)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Description

Text Selection does not work on GTK based apps.

https://github.com/user-attachments/assets/b2dbb59d-cbfe-45cb-93ce-c2070e964145

### How to reproduce

Try to select some text on GTK apps.

**Comment by vaxerski** [comment]
how is this a hyprland issue? have you tested on kde or sway?

**Comment by joelmathewthomas** [comment]
> how is this a hyprland issue? have you tested on kde or sway?

It works fine on kde.

**Comment by joelmathewthomas** [comment]
I got the solution from this closed [issue](https://github.com/hyprwm/Hyprland/issues/2619#issuecomment-1899270343).

> > I was having similar issues, but for me the solution was not using wl-clip-persist. Another issue using wl-clip-persist that caused for me was corrupted images when they're pasted to discord.
> 
> For me _--clipboard_ regular instead of _--clipboard both_ was enough

This issue didn't come up during my initial search for open issues.
