### ISSUE TITLE
Feature Request - FSE (Fullscreen Exclusive)

### ISSUE THREAD

**Issue by JustOptimize** [hyprwm/Hyprland#8189]
### Description

First off, I just want to say thank you for all the hard work you’ve put into Hyprland! I’ve been using it for a while now, and I absolutely love it. It’s hands down the best experience I’ve had with a window manager, and it keeps getting better with each update.

I was wondering if there are any plans to add support for Fullscreen Exclusive Mode? It’s a handy feature, especially for gaming, since it helps with performance by bypassing the compositor. Plus, it can improve things like input latency and frame pacing for games that need that mode.

Thanks again for making such an awesome project! I really appreciate all the effort that goes into it!

**Comment by MightyPlaza** [comment]
direct scanout?

**Comment by JustOptimize** [comment]
> direct scanout?

Oh my bad, was searching exactly for that lol, thanks
