### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by TropicLegend** [hyprwm/Hyprland#819]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.
Steps to reproduce:
Install Flatpak Spotify
Open Spotify

Expected behavior:
Spotify opens

Noted outcome:
Spotify fails to open and throws error.

```
➜  ~ flatpak run com.spotify.Client                                                                              
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)                                             
➜  ~ [spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
[libprotobuf ERROR ../core/vendor/protobuf3/src/google/protobuf/wire_format_lite.cc:577] String field 'spotify.event_sender.proto.DroppedEvents.DroppedEventsBySequenceIdEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[spotifywm] spotify window found
/app/bin/spotify: line 41: Xlib.xauth:: command not found
```

**Comment by vaxerski** [comment]
how is that related to hyprland?

**Comment by TropicLegend** [comment]
It works on other compositors, only not working on Hyprland

**Comment by vaxerski** [comment]
@fufexan you use spotify, help this man, no clue whats wrong here

**Comment by fufexan** [comment]
I don't use flatpak. Spotify installed with Nix works fine.

**Comment by TropicLegend** [comment]
> I don't use flatpak. Spotify installed with Nix works fine.

Tried with Nix, didn't work for me as well.

`[nix-shell:~]$ spotify
/nix/store/38dc4j251qjfdaa7ixyq88s0057bfg28-spotify-1.1.84.716.gc5f8b819/bin/spotify: /nix/store/76phxskwa0dz8hr2gnzylna5xx4wz6hk-curl-7.85.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/38dc4j251qjfdaa7ixyq88s0057bfg28-spotify-1.1.84.716.gc5f8b819/bin/spotify)
/nix/store/i0100mlj1s4gp6gk4n0qzkdknmpf1j1j-spotify-unwrapped-1.1.84.716.gc5f8b819/share/spotify/.spotify-wrapped: /nix/store/76phxskwa0dz8hr2gnzylna5xx4wz6hk-curl-7.85.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/i0100mlj1s4gp6gk4n0qzkdknmpf1j1j-spotify-unwrapped-1.1.84.716.gc5f8b819/share/spotify/.spotify-wrapped)
/nix/store/i0100mlj1s4gp6gk4n0qzkdknmpf1j1j-spotify-unwrapped-1.1.84.716.gc5f8b819/share/spotify/.spotify-wrapped: /nix/store/76phxskwa0dz8hr2gnzylna5xx4wz6hk-curl-7.85.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/i0100mlj1s4gp6gk4n0qzkdknmpf1j1j-spotify-unwrapped-1.1.84.716.gc5f8b819/share/spotify/.spotify-wrapped)

(process:21495): Gtk-WARNING **: 17:03:15.225: Locale not supported by C library.
	Using the fallback 'C' locale.
/proc/self/exe: /nix/store/76phxskwa0dz8hr2gnzylna5xx4wz6hk-curl-7.85.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)`

**Comment by fufexan** [comment]
sounds like you have a haunted system, as Vaxry usually says.

**Comment by freundTech** [comment]
The libprotobuf and Locale not supported errors make me think that it might be something encoding related. Do you have any non-ascii characters in your username or some file path?

**Comment by TropicLegend** [comment]
I don’t have any non-ascii characters in my file paths or username. So unfortunately that’s not the problem. 
Could the problem maybe be related to me using a Nvidia gpu (RTX 3080ti)? 
I’ve read about Nvidia support issues with Hyprland, but it still seems strange to me.

**Comment by NotAShelf** [comment]
I'm also on Nvidia, this is not an issue I was able to reproduce. Spotify installed through flatpak or AUR work perfectly fine.
Tried with a 1660s and a 3060.

**Comment by pupbrained** [comment]
Works fine for me here too, 3050 mobile on NixOS, latest Hyprland commit.

**Comment by vaxerski** [comment]
Does this still happen or can we close this?

**Comment by TropicLegend** [comment]
Can be closed.
