### ISSUE TITLE
fuck hyprland fuck huprland fuck hyprland 

### ISSUE THREAD

**Issue by MahadRegent** [hyprwm/Hyprland#8195]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>g

### Description

After installing fucking Hyprland, (It was very buggy, and im just go to kfe plasma) and after im loading in KDE plasma it off my monitor, but when im loading in Hyprland after this - nothing happened (not including all bugs of hyprland).

### How to reproduce

Check up

### Crash reports, logs, images, videos

F

**Comment by 299792458ms** [comment]
Say no to drugs
