### ISSUE TITLE
[][Human_live][]How do I get a human at Expedia?Get_Help 24^7 iNFO CAll~2$#

### ISSUE THREAD

**Issue by maddogopc** [hyprwm/Hyprland#8198]
### Description

𝘛𝘰 𝘵𝘢𝘭𝘬 𝘵𝘰 𝘢 𝘳𝘦𝘢𝘭 𝘩𝘶𝘮𝘢𝘯 𝘢𝘵 𝘌𝘹𝘱𝘦𝘥𝘪𝘢, 𝘺𝘰𝘶 𝘩𝘢𝘷𝘦 𝘢 𝘧𝘦𝘸 𝘰𝘱𝘵𝘪𝘰𝘯𝘴. 𝘠𝘰𝘶 𝘤𝘢𝘯 𝘤𝘢𝘭𝘭 𝘵𝘩𝘦𝘪𝘳 𝘤𝘶𝘴𝘵𝘰𝘮𝘦𝘳 𝘴𝘦𝘳𝘷𝘪𝘤𝘦 𝘩𝘰𝘵𝘭𝘪𝘯𝘦 𝘢𝘵 +1-(802)-551-81.60, 𝘤𝘩𝘢𝘵 𝘸𝘪𝘵𝘩 𝘵𝘩𝘦𝘮 𝘭𝘪𝘷𝘦 𝘰𝘯 𝘵𝘩𝘦𝘪𝘳 𝘸𝘦𝘣𝘴𝘪𝘵𝘦, 𝘰𝘳 𝘶𝘴𝘦 𝘵𝘩𝘦𝘪𝘳 𝘦𝘮𝘢𝘪𝘭 𝘴𝘶𝘱𝘱𝘰𝘳𝘵. 𝙏𝙤 𝙜𝙚𝙩 𝙖 𝙝𝙪𝙢𝙖𝙣 𝙖𝙩 𝙀𝙭𝙥𝙚𝙙𝙞𝙖, 𝙘𝙖𝙡𝙡 𝙩𝙝𝙚𝙞𝙧 𝙘𝙪𝙨𝙩𝙤𝙢𝙚𝙧 𝙨𝙚𝙧𝙫𝙞𝙘𝙚 𝙖𝙩 1-800-𝙀𝙓𝙋𝙀𝘿𝙄𝘼+1-802||551||-81/60#.

**Comment by izmyname** [comment]
Ah, shit, here we go again

**Comment by myamusashi** [comment]
scamming on github is crazy actually
