### ISSUE TITLE
Hyprland as wayland compositor for sddm

### ISSUE THREAD

**Issue by autofool** [hyprwm/Hyprland#820]
Latest sddm offers wayland and x11 as optional display server. Currently sddm can run on weston and kwin_wayland compositor like this:
CompositorCommand=weston --shell=fullscreen-shell.so
CompositorCommand=kwin_wayland --no-lockscreen

I wonder if hyprland can be used like this since its also a compositor. I'm currently running with kwin but if hyprland is supported then it would remove bloated kwin deps.

As an experiment I tried using Hyprland as command and Hyprland does show up during boot but there's no sddm login screen (Obviously). Hyprland binary doesn't show much option on help and hyprctl is only used for communication with Hyprland during runtime. Is this feature feasible to implement in Hyprland?

**Comment by vaxerski** [comment]
what?

So you want to launch hyprland as the first thing and then magically have sddm cover it up? No clue about how it does that, but if it uses the ext lockscreen protocol that's planned for support.

You could also exec-once your favorite lockscreen app tho to achieve a similiar effect, no?

**Comment by autofool** [comment]
I'm not completely sure how sddm is working but I think its using external compositor to prepare session where its ready to start a client. Those compositor commands are written in it's configuration file so I'm not sure how sddm uses them during runtime. Of course you guys would know more about compositors and how they work.

**Comment by autofool** [comment]
In [this](https://github.com/sddm/sddm/issues/1421) thread peeps are talking about detecting installed compositor and [here](https://github.com/sddm/sddm/issues/1417) how to change sddm's compositor from weston to kwin. Maybe that will shed some light on topic?

**Comment by vaxerski** [comment]
that just seems to me like the compositor that SDDM is using to render itself. Why would you want that to be Hyprland?

**Comment by autofool** [comment]
So that systems using sddm as login manager and hyprland as window manager will not have to depend on another compositor? I don't know if talk about in-house `sddm-compositor` in second thread I mentioned is solid or not. If it is then this will definitely be redundant. But if other proposal of detecting user installed compositor is accepted then maybe Hyprland could be one of the officially supported compositor for sddm to provide better user experience? It seems far fetched but I guess worth talking about?

**Comment by fufexan** [comment]
I think `cage` fits the bill better, since it's designed to only run one application, fullscreen. Just like a barebones X server running Steam or a web browser directly.

**Comment by kkanungo17** [comment]
If single application compositors are okay `gamescope` is also a viable alternative. It runs the Steam Deck GUI after all.

**Comment by niksingh710** [comment]
> that just seems to me like the compositor that SDDM is using to render itself. Why would you want that to be Hyprland?

so that we don't have to install weston or kwin to run sddm using wayland rederer.

**Comment by niksingh710** [comment]
> I think `cage` fits the bill better, since it's designed to only run one application, fullscreen. Just like a barebones X server running Steam or a web browser directly.

`cage`? how can I use it in place of sddm compositer?

**Comment by TheSunCat** [comment]
I use `cage` to run qtgreet, it works okay but doesn't support mirroring displays so I'm stuck with the login screen on oen display and my other displays completely black.

**Comment by fufexan** [comment]
I myself use sway for running gtkgreet, it works perfectly fine.

**Comment by DaniAndTheWeb** [comment]
Right now you can enable hyprland as the sddm-git compositor by creating a simple file as shown in the arch wiki and replacing kwin suggested compositor with hyprland. However, at least on hyprland-git, this results in frequent of sddm crashes. It seems that with some optimization it may be possible to solve the crashes and make it usable as a compositor for sddm.

**Comment by autofool** [comment]
At the time of writing this issue I experienced only black screen with no SDDM. I guess SDDM itself is improving for Wayland support. Last I heard that Weston is also working for some people with SDDM but I couldn't make it work. Maybe it need's some special arguments. Weston would be much lighter and less bloated dependency than kwin. Let's see how SDDM and hyprland work after SDDM releases stable wayland support.

**Comment by vlad196** [comment]
> At the time of writing this issue I experienced only black screen with no SDDM. I guess SDDM itself is improving for Wayland support. Last I heard that Weston is also working for some people with SDDM but I couldn't make it work. Maybe it need's some special arguments. Weston would be much lighter and less bloated dependency than kwin. Let's see how SDDM and hyprland work after SDDM releases stable wayland support.

arguments like this? 
...
[Wayland]
[CompositorCommand=weston --shell=fullscreen-shell.so](https://man.archlinux.org/man/sddm.conf.5#CompositorCommand=)
...

**Comment by KAGEYAM4** [comment]
for me its working, unless i am interpreting it wrong.

```
       │ File: /etc/sddm.conf.d/10-wayland.conf
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [General]
   2   │ DisplayServer=wayland
   3   │ CompositorCommand=Hyprland
 ```

**Comment by DevDorrejo** [comment]
Found this issue,

I had make sddm work with hyperland:![P_20240821_172021.jpg](https://github.com/user-attachments/assets/28247284-5dd6-477e-a685-c5921ecb27fd)

But when booting it will first show hyprland desktop and later show sddm, how can I improve this?

**Comment by ArtemSmaznov** [comment]
Man this is amazing! I literally only had 2 lines in my config before. I do see some windows opening up before sddm loads but it's practically instant. Much better than using X11 or installing another compositor just for sddm.

BTW in case no one else want's to type this out
```
[General]
Numlock=on
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=xdg-shell
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=sober

[Users]
DefaultPath=/usr/local/bin:/usr/bin:/bin
HideShells=
HideUsers=
MaximumUid=60000
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true
ReuseSession=true

[Wayland]
# path of wayland compositor to execute when starting the greeter
CompositorCommand=Hyprland
EnableHiDPI=true
SessionCommand=/usr/share/sddm/scripts/wayland-session
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions
SessionLogFile=.local/share/sddm/wayland-session.log

[X11]
Enable=false
```

**Comment by DevDorrejo** [comment]
> Man this is amazing! I literally only had 2 lines in my config before. I do see some windows opening up before sddm loads but it's practically instant. Much better than using X11 or installing another compositor just for sddm.
> 
> BTW in case no one else want's to type this out
> 
> ```
> [General]
> Numlock=on
> DisplayServer=wayland
> GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=xdg-shell
> HaltCommand=/usr/bin/systemctl poweroff
> RebootCommand=/usr/bin/systemctl reboot
> 
> [Theme]
> Current=sober
> 
> [Users]
> DefaultPath=/usr/local/bin:/usr/bin:/bin
> HideShells=
> HideUsers=
> MaximumUid=60000
> MinimumUid=1000
> RememberLastUser=true
> RememberLastSession=true
> ReuseSession=true
> 
> [Wayland]
> # path of wayland compositor to execute when starting the greeter
> CompositorCommand=Hyprland
> EnableHiDPI=true
> SessionCommand=/usr/share/sddm/scripts/wayland-session
> SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions
> SessionLogFile=.local/share/sddm/wayland-session.log
> 
> [X11]
> Enable=false
> ```

I am trying to fix that issue, is a CVE, because I can execute command in the close moments.

**Comment by kRHYME7** [comment]
@DevDorrejo 

You can tell Hyrpland what config to use using -c | --config flag
![image](https://github.com/user-attachments/assets/5f707bd0-682c-421a-a616-dc497f7a6a8f)

:- in my case ` CompositorCommand=Hyprland -c /etc/sddm.conf.d/hyprland.conf ` I added that. 

Now inside ` /etc/sddm.conf.d/hyprland.conf ` 

I added this 


```
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}
windowrulev2 = noanim on,class:^(.*)$
windowrulev2 = noblur on,class:^(.*)$
windowrulev2 = nodim on,class:^(.*)$
windowrulev2 = noshadow on,class:^(.*)$
windowrulev2 = opaque on,class:^(.*)$
windowrulev2 = bordersize 0,class:^(.*)$
windowrulev2 = rounding 0,class:^(.*)$
windowrulev2 = decorate 0,class:^(.*)$
windowrulev2 = fullscreen,class:^(.*)$
windowrulev2 = forcergbx [on],class:^(.*)$
windowrulev2 = nomaxsize [on],class:^(.*)$
windowrulev2 = nearestneighbor [on],class:^(.*)$
windowrulev2 = focusonactivate [on],class:^(.*)$

#? We can source a monitor configuration here (or whatever) 
#? I do not know if we can match .* all monitors to be mirrored (scaling issues)
# source = /path/to/monitor.conf # this can be inside /etc/sddm.conf.d/ or anywhere inside /usr/local/ 
#
#monitor=eDP-1,3000x2000@60.0,0x0,2.0,mirror,DP-1
#monitor=DP-1,1366x768@59.79,1500x0,1.0

```

This is not complete so I tried to reach out here for some advice on the perfect config. 
** Which config to add/ remove

**Comment by DevDorrejo** [comment]
With this you stop Hyprland  appear when loading sddm?

**Comment by kRHYME7** [comment]
> With this you stop Hyprland appear when loading sddm?

If you meant the logos,splashscreen/background? 
yes, And some of the window rules are added so sddm "Window" won't have hyprland decorations, animations etc. 
Also learned that sddm-greeter is running as a window, NOT as a layer.
No, as sddm is now handled by Hyprland

**Comment by DevDorrejo** [comment]
I am building a SDDM-WL (Wayland), focused for hyprland, I found that the user sddm will get a hyper config file autogenerated too, so you can have this or edit the generate one in the sddm user folder.

> @DevDorrejo 
> 
> You can tell Hyrpland what config to use using -c | --config flag
> ![image](https://github.com/user-attachments/assets/5f707bd0-682c-421a-a616-dc497f7a6a8f)
> 
> :- in my case ` CompositorCommand=Hyprland -c /etc/sddm.conf.d/hyprland.conf ` I added that. 
> 
> Now inside ` /etc/sddm.conf.d/hyprland.conf ` 
> 
> I added this 
> 
> 
> ```
> misc {
>     disable_hyprland_logo = true
>     disable_splash_rendering = true
>     force_default_wallpaper = 0
> }
> windowrulev2 = noanim on,class:^(.*)$
> windowrulev2 = noblur on,class:^(.*)$
> windowrulev2 = nodim on,class:^(.*)$
> windowrulev2 = noshadow on,class:^(.*)$
> windowrulev2 = opaque on,class:^(.*)$
> windowrulev2 = bordersize 0,class:^(.*)$
> windowrulev2 = rounding 0,class:^(.*)$
> windowrulev2 = decorate 0,class:^(.*)$
> windowrulev2 = fullscreen,class:^(.*)$
> windowrulev2 = forcergbx [on],class:^(.*)$
> windowrulev2 = nomaxsize [on],class:^(.*)$
> windowrulev2 = nearestneighbor [on],class:^(.*)$
> windowrulev2 = focusonactivate [on],class:^(.*)$
> 
> #? We can source a monitor configuration here (or whatever) 
> #? I do not know if we can match .* all monitors to be mirrored (scaling issues)
> # source = /path/to/monitor.conf # this can be inside /etc/sddm.conf.d/ or anywhere inside /usr/local/ 
> 
> # Mirror monitors and try to catch as much monitors
> monitor=,highres,auto,auto,mirror,DP-2,mirror,DP-1
> 
> 
> ```
> 
> This is not complete so I tried to reach out here for some advice on the perfect config. 
> ** Which config to add/ remove  
> 
> 
> We got 4 options for monitor ig, 
> 1. which comes first (whichever sddm choose to render)
> 2.  mirror all monitor (with scaling issue)
> 3. launch ` sddm-greeter-qt6 ` to all monitors. But I don't know how (x11 behaves like this) 
> 4.  Re-render  a single instance of a window to multiple different monitors (++dynamic scaling and not YET possible ) 
> 
> 
> ### Additional/Related info
> * 2 instance of Hyprland consuming mem. Not an issue for me.  
> ![image](https://github.com/user-attachments/assets/7f2bc951-b206-491c-8b39-a58d046fe07a)
> 
>

**Comment by kRHYME7** [comment]
> , I found that the user sddm will get a hyper config file autogenerated too, so you can have this or edit the generate one in the sddm user folder.

I think touching this will cause errors on PKGBUILD/ or Makefile in case one want to package it

**Comment by ArtemSmaznov** [comment]
Is anyone else having this weird issue where the login password cannot be typed until the mouse is moved with this setup?
It's like sddm is not fully focused on startup.

**Comment by autofool** [comment]
@ArtemSmaznov No Issues that you mentioned and you don't need that much info in sddm config.

@kRHYME7 Mirror desktop is not needed if you can pin the sddm window.

Can both of you run this config and let me know if issues still persists.

Make sure you have packages (names from archlinux)
- qt6-wayland
- layer-shell-qt

```
# /etc/sddm.conf.d/hypr.conf

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=hyprland -c /opt/hypr/sddm.conf
```

Here is hyprland config:

```
# /opt/hypr/sddm.conf

misc {
        disable_hyprland_logo = true
        disable_splash_rendering = true
        force_default_wallpaper = 0
}

windowrulev2 = float, maximize, pin, stayfocused, decorate 0, noanim, noborder, nodim, norounding, noshadow, class:^(sddm-greeter)$
```

**Comment by ArtemSmaznov** [comment]
Thanks, my mouse-move-focus-password issue was actually fixed about a week ago after some update (haven't tracked which one). But I'll review this later and see if I need to update my config. Will likely not have anything to report back.

**Comment by kRHYME7** [comment]
Will report back later. Will float, maximize,pin pushes or assign the new window to another monitor?

**Comment by kRHYME7** [comment]
Are there any rules to make the sddm-greeter move to corresponding monitors?

**Comment by autofool** [comment]
Power options are filling space so its the background image in theme that's low resolution for rest of monitors. Its should be easy to center the Highest resolution image with fill property. I'm sorry I don't know much about SDDM theme so maybe try look at other themes that work with responsive designs.

**Comment by kRHYME7** [comment]
Thank you for confirming. I also observe this one. and the issue is not consistent across themes.

Now I can finally utilize sddm using Hyprland.

**Comment by ArtemSmaznov** [comment]
I've replaced the rules from the example posted here earlier with the one-liner from the last suggestion and see no difference (all works as expected) so I am keeping it.
Don't see the point in having the greeter on all monitors so I still have a monitor section.

```
# /etc/sddm.conf.d/hypr/hyprland.conf
monitor=DP-1 , highrr , 0x0 , auto
monitor= , disable

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

windowrulev2 = float, maximize, pin, stayfocused, decorate 0, noanim, noborder, nodim, norounding, noshadow, class:^(sddm-greeter)$
```

Now in regards to the `sddm.conf`, if I switch to `layer-shell` as you have in your config I just get a black screen with a mouse, probably cause I don't have `layer-shell-qt` installed. `xdg-shell` works fine as it did before. Would you recommend I install and switch to `layer-shell`? 

```
# /etc/sddm.conf.d/10-wayland.conf

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=xdg-shell
# GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
# path of wayland compositor to execute when starting the greeter
CompositorCommand=Hyprland -c /etc/sddm.conf.d/hypr/hyprland.conf
EnableHiDPI=true
SessionCommand=/usr/share/sddm/scripts/wayland-session
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions
SessionLogFile=.local/share/sddm/wayland-session.log

[X11]
Enable=false
```

**Comment by autofool** [comment]
@ArtemSmaznov layer-shell is new protocol for displaying surface windows in wayland like walls, locks and bars. Eventually xdg-shell will may be replaced with layer-shell on wlroots based compositors. However since hyprland no longer depends on wlroots I'm not sure whats it's take on xdg-shell. (@vaxerski ?) Personally I'd keep layer-shell cause its supported by wayland community so it should offer more stability in future.

**Comment by ArtemSmaznov** [comment]
Weird, I installed `layer-shell-qt` (`qt6-wayland` was already installed), updated config to `layer-shell` and expected it to work, but I still get just blank screen with a mouse cursor. Is there any configuration I need to do in some other place?

**Comment by kRHYME7** [comment]
> Personally I'd keep layer-shell cause its supported by wayland community so it should offer more stability in future.

@autofool Layer shell is always supported in hyprland. It is the sddm that's not using layer-shell-qt6 yet.

> Weird, I installed layer-shell-qt (qt6-wayland was already installed), updated config to layer-shell and expected it to work, but I still get just blank screen with a mouse cursor. Is there any configuration I need to do in some other place?

@ArtemSmaznov  Install ` layer-shell-qt5 ` 

- https://wiki.archlinux.org/title/SDDM#Wayland
- https://bbs.archlinux.org/viewtopic.php?id=293540


Now, for anyone who might stumble upon this post.  ` Window rules` are useless on layer-shell protocol. 
Using layer-shell  ` GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell ` should make sddm work OOTB.

This repo https://github.com/HyDE-Project/sddm-hyprland concludes this discussion, with Makefile for easy installation.

**Comment by autofool** [comment]
SDDM supports both qt6 and qt5. Its the theme thats running on qt5. I have [this](https://github.com/Keyitdev/sddm-astronaut-theme) theme installed with only layer-shell-qt6 installed. SDDM v0.21.0 runs perfectly fine without layer-shell-qt5. Just run xdg-shell if that floats your boat no need to install extra stuff. If it works, leave it. I use layer-shell cause it's kde's default and since sddm is part of (kind of) plasma eco system it should offer more stability that's it, nothing more of it.

**Comment by CD11b** [comment]
Is there a way to get logout to work with this? loginctl terminate-session $XDG_SESSION_ID and loginctl terminate-user $(whoami) put me in tty instead of sddm.

**Comment by ArtemSmaznov** [comment]
Is your TTY functional after logout? Because all I get is a few `^@^@` and I have to switch to a different tty to restart sddm.

We should really have a separate issue for this though. Maybe there is one even, I haven't looked.

**Comment by kRHYME7** [comment]
> Is there a way to get logout to work with this? loginctl terminate-session $XDG_SESSION_ID and loginctl terminate-user $(whoami) put me in tty instead of sddm. 


I don't know about this stuff but if using hyprland there is ` hyprctl dispatch exit  0`

**Comment by CD11b** [comment]
> Is your TTY functional after logout? Because all I get is a few `^@^@` and I have to switch to a different tty to restart sddm.
> 
> We should really have a separate issue for this though. Maybe there is one even, I haven't looked.

You're right, I just get stuck on a cursor, though. I'm needing to switch to another tty to run `# systemctl restart sddm.service`. Seems like I confused this with something else... anyways



> I don't know about this stuff but if using hyprland there is ` hyprctl dispatch exit 0`

This didn't work for me as I get `Couldn't connect to /run/user/1000/hypr/.../.socket.sock. (3)`, BUT ` hyprctl --instance 0 dispatch exit` did work. Thank you!

**Comment by ArtemSmaznov** [comment]
Does it terminate everything properly? When I was using the exit dispatcher before switching to uwsm it was just killing all the processes (not allowing the apps to do any of the termination tasks like saving recent files and so on). Haven't tried this on uwsm.
