### ISSUE TITLE
movefocus do not act as I expect when a window is fullscreen

### ISSUE THREAD

**Issue by logexp1** [hyprwm/Hyprland#8208]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0c7a7e2d569eeed9d6025f3eef4ea0690d90845d  (version: bump to 0.44.0).
Date: Sun Oct 6 11:04:13 2024
Tag: v0.44.0, commits: 5299
built against aquamarine 0.4.1


flags: (if any)


System Information:
System name: Linux
Node name: AL02462227
Release: 6.10.12-200.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Mon Sep 30 21:38:25 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28a1] (rev a1) (prog-if 00 [VGA controller])
c3:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: NAME="Fedora Linux"
VERSION="40 (Sway)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Sway)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://gitlab.com/fedora/sigs/sway/SIG/-/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Sway"
VARIANT_ID=sway


plugins:
```

</details>

### Description

I am using hyprland with my laptop and a external monitor. I placed laptop display and external monitor side by side and move cursors these two displays using "movefocus, l/r". When windows are tiled, it works as expected. But I sometimes make window as monocle or fullscreen using "fullscreen, 0/1" Then, I can't move cursors across monitors any more, when I execute movefocus, focus is cycling through the windows in the current workspace not moving to the other monitor. Currently  I can just toggle fullscreen off and execute movefocus, but is there a better way? Thank you!

### How to reproduce

described in above section

**Comment by vaxerski** [comment]
`focusmonitor,l`?

**Comment by logexp1** [comment]
I just tried `focusmonitor,l`. It acts in exact same way as before when window is fullscreen. (only cycles through the windows in current workspace) 
It moves focus to another monitor when window is not in fullscreen, but I still want to move focus in window level..

**Comment by vaxerski** [comment]
write a script then. You can query properties of the active window with hyprctl activewindow. read the wiki

**Comment by MightyPlaza** [comment]
```
binds {
    movefocus_cycles_fullscreen = false
}
```

**Comment by vaxerski** [comment]
right, that exists

**Comment by logexp1** [comment]
> ```
> binds {
>     movefocus_cycles_fullscreen = false
> }
> ```

@MightyPlaza That was exactly what I was looking for. Thanks a lot!!!
