### ISSUE TITLE
Focus restored incorrectly after closing floating window

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [hyprwm/Hyprland#821]
## How to reproduce

To make sure no shenanigans going on with the mouse I've set `input:follow_mouse = 0` and `input:float_switch_override_focus = 0`, but it doesn't seem to matter for this issue (happens on defaults too).

1. Open 3 windows, focus the 3rd

```
+-----------------+-------+
|                 |       |
|                 |  [3]  |
|                 |       |
|        1        +-------+
|                 |       |
|                 |   2   |
|                 |       |
+-----------------+-------+
```

2. Open and close floating window

3. Now window __2__ is focused

## Expected behavior

Window 3 should be focused (window that was originally focused should receive the focus back).

## Demo

https://user-images.githubusercontent.com/14999778/194760983-4703df29-5f3f-414a-b7b1-cc86f332194a.mp4

Also, it doesn't happen with e.g. wofi.

## System

* Arch Linux latest
* linux-zen 5.19.13
* nvidia-dkms 515.76-1 (Instructions from the wiki applied except fixes for flickering)
* Hyprland https://github.com/hyprwm/Hyprland/commit/90f2259f5e4b8d4c1c51db8d463a7a7e47624bce, generated config + bindings

## Real use case

For me it's opening `copyq show` in floating window to select clipboard's content from history.

**Comment by vaxerski** [comment]
that's intended behavior

**Comment by MahouShoujoMivutilde** [comment]
Okay, is there a way to force it to give the focus to the previously focused window, after float is closed?

**Comment by MahouShoujoMivutilde** [comment]
The only sort of way I see so far is listening on socket2 for `activewindow`, recording `hyprctl -j activewindow | jq -r '.address, .floating'`, and on `closewindow` if window was floating calling `hyprctl dispatch focuswindow address:__previous__`.

But is there a better way?

**Comment by vaxerski** [comment]
probably not. Hyprland does not record the "last tiled window"

But since this script works and isn't very heavy, I think this should not be an issue.

**Comment by MahouShoujoMivutilde** [comment]
Sure, I didn't expect to figure out the solution so fast after I opened the issue, otherwise I wouldn't have opened it.

**Comment by vaxerski** [comment]
don't worry :P
