### ISSUE TITLE
Cannot overwrite hyprland.conf after the first start

### ISSUE THREAD

**Issue by mylinuxforwork** [hyprwm/Hyprland#8211]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

I am using the autogenerated config file.

### Description

Hi.

Just made some tests on pure Hyprland installation. After successful installation and start with Hyprland command, I am not able to edit or delete the autogenerated hyprland.conf.

After every change or deletion, the file will be re-generated immediatly.

But when I logout and login again, the file is editable and deletable.

### How to reproduce

Arch Linux Minimal
Install with yay -S hyprland
Start Hyprland
Try to delete .config/hypr/hyprland.conf
hyprland.conf will be re-generated after deletion

**Comment by mylinuxforwork** [comment]
The autogenerated warning message is also blinking. Looks like that the config is getting reloaded all the time.

Stops with the second login.

**Comment by PaideiaDilemma** [comment]
Got fix in https://github.com/hyprwm/Hyprland/pull/8164

**Comment by vaxerski** [comment]
yea, closing
