### ISSUE TITLE
Regression on 0.44.1 regarding shikane

### ISSUE THREAD

**Issue by leiserfg** [hyprwm/Hyprland#8221]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Hyprland 0.44.1

### Description

After 0.44.1 shikane does not work again: after disconnecting the external monitor the internal one does not kick in. I tested the related commits in the release:

With ad46257ccef8cf3a87083b00d808539368436c25  shikane works fine but it makes many apps misbehave (not even the wallpaper works)
With 8405aa111df785e865f64b91d1424806dd452f80  the apps work again but then shikane does not work anymore.

### How to reproduce

See https://github.com/hyprwm/Hyprland/pull/7571

**Comment by vaxerski** [comment]
wayland_debug of shikane pls?

**Comment by leiserfg** [comment]
`env WAYLAND_DEBUG=1 shikane 2>&1 |tee /tmp/wayland.log`
[wayland.log](https://github.com/user-attachments/files/17507572/wayland.log)


`env SHIKANE_LOG=trace shikane  2>&1 | grep  Event::`
[shikane.log](https://github.com/user-attachments/files/17507562/shikane.log)

**Comment by leiserfg** [comment]
I don't see the `Finished` events again, 😢

**Comment by vaxerski** [comment]
yabba dabba doo refcounting oopsie woohoo

**Comment by vaxerski** [comment]
should be fixed lmk

**Comment by Mikilio** [comment]
Just tried master and I still have the issue.

**Comment by vaxerski** [comment]
can you get a WAYLAND_DEBUG log?

**Comment by Mikilio** [comment]
Here it is:
[waylandt.log](https://github.com/user-attachments/files/17531922/waylandt.log)

I started running Hyprland connected to my dock with my laptop being disabled by shikane:
1. turn off my service for shikane
2. running `env WAYLAND_DEBUG=1 shikane 2>&1 |tee /tmp/wayland.log`
3. disconnecting from my dock (laptop screen stays black)
4. switching to VT and logging in
5. running `pkill shikane`
6. copying the logs
7. restarting shikane service
8. switching back to Hyprland (at this point on my laptop was actually displaying a workspace)
9. connect to the dock (Hypland crashes)

**Comment by vaxerski** [comment]
finished logs are there tho huh? @leiserfg does it also not work for you?

**Comment by leiserfg** [comment]
I'm back  from NixCon. Tested in a3d3b4fd64a51a8c1663b450bd2a408f1f0fa9b3 and it works for me.

**Comment by vaxerski** [comment]
closing then @Mikilio you can open a separate one
