### ISSUE TITLE
Swipe up and down gestures?

### ISSUE THREAD

**Issue by Fennix900** [hyprwm/Hyprland#8235]
### Description

Yet i couldn't find any way to implement swipe up or down gestures.
For example, i would like to swipe up with three fingers to open a menu to open Apps, or swipe down to open a drop down terminal. 

Is there already a way to use swipe up and down? 
If not so, this would be a useful feature

**Comment by fufexan** [comment]
https://github.com/bulletmark/libinput-gestures
https://github.com/maurges/wzmach

**Comment by vaxerski** [comment]
as above
