### ISSUE TITLE
Hyprctl outputs invalid json when there are too many things going on

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#824]
In my testing, if you have more than 23 clients, hyprctl fails to generate actual jsons
![image](https://user-images.githubusercontent.com/68589851/194856915-63059a5a-aec5-429b-ae15-c336b0a45e0b.png)
This *probably* has smth to do with buffer size?

**Comment by vaxerski** [comment]
probably yeah, the buf size is 8192 iirc. I should make it not be bound to the buffer size.

**Comment by vaxerski** [comment]
fixed in 46e51a81c4c457078ac144c010d9d4d64d02f9df
