### ISSUE TITLE
Electron apps crash hyprland back to tty.

### ISSUE THREAD

**Issue by Imaweasle** [hyprwm/Hyprland#8243]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<hyprland-backgrounds/oracular,oracular 0.41.2+ds-1.1 all
hyprland-dev/oracular 0.41.2+ds-1.1 amd64
hyprland-protocols/oracular,oracular 0.2+20240505-1.1 all
hyprland/oracular,now 0.41.2+ds-1.1 amd64 [installed]>
```

</details>

### Description

First I'll say neither command worked to check Hyprland version for me.  I just did `sudo apt list | grep hyprland`.  Okay so most electron apps do weird things to my GPU I think?  (Yes I have followed the instruction on the master guide for configuring hyprland, it doesn't fix it for me).  Either the app crashes or Hyprland crashes (most often it's Hyprland).  Some apps, like VSCode appear to work, but when I take focus off of them, hyprland crashes after 30 seconds.  It slows down a lot before it crashes too. 

### How to reproduce

Install hyprland from the Ubuntu 24.20 apt repo and try to launch electron apps: specifically Joplin crashes the system immediately, Discord fails to launch but does not crash Hyprland, and VSCode crashes if focus is removed for more than 30 seconds from the window.  

### Crash reports, logs, images, videos

Okay so I have a lot of data that may or may not be helpful because I don't know what most of these crash logs mean.  I think it has to do with my GPU. 

Attached are all of my crash logs, my system specs(neofetch), and terminal ouput when discord is run:
[hyprland crash data.zip](https://github.com/user-attachments/files/17529152/hyprland.crash.data.zip)

**Comment by vaxerski** [comment]
> First I'll say neither command worked to check Hyprland version for me

update hyprland then. You're on an extremely outdated version.

**Comment by Imaweasle** [comment]
I mean I am using the newest version in the apt repos and it wont build from source because of hyprutils < 0.2.1 but I can't find where to install that.  Looking up install scripts tell me that I have the latest version of hyprland. 0.41 instead of 0.44.

**Comment by vaxerski** [comment]
I don't really care about your repos. You're using a very outdated version, that's what matters.

> because of hyprutils < 0.2.1 but I can't find where to install that

build it from source as well??

**Comment by Imaweasle** [comment]
Ok, I'm still having the same issues but I am now on 0.44.1 (hyperctl version output was added to original issue)

**Comment by vaxerski** [comment]
post a crash report pls
