### ISSUE TITLE
Unable to run OpenGL games with Integrated Graphics mode while my NVidia card is preferred in the hyprland.conf file.

### ISSUE THREAD

**Issue by ItsFireStorm** [hyprwm/Hyprland#8247]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3


flags: (if any)


System Information:
System name: Linux
Node name: ARCHUS
Release: 6.11.5-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000


GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-H GT1 [UHD Graphics] [8086:9a68] (rev 01) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  560.35.03  Release Build  (archlinux-builder@)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

```

</details>

### Description

I have an Asus TUF laptop, and I'm running supergfxctl to switch between Integrated and Hybrid whenever I need to save battery power, here's the issue though, as of recently I've had [this error](https://bbs.archlinux.org/viewtopic.php?pid=2204794#p2204794) pop up whenever I tried to run games in Integrated Graphics (sounds stupid, I know, but I sometimes kill time with this).

_TL;DR: Whenever trying to run Minecraft this error printed:_ `GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig` _which was due to me having selected NVidia Graphics as my OpenGL backend when they didn't exist running Integrated Graphics._

Now the issue is that whenever running Hybrid Graphics, it prefers using the MESA Intel Graphics rather than the ones from my NVidia Card. I was wondering if anyone who had used supergfxctl in Hyprland had been successfully able to run games on Integrated Graphics while also being able to run NVidia Graphics in Hybrid mode, without Integrated mode failing.

### How to reproduce

Have an Asus TUF/ROG Laptop or similar with a NVidia Dedicated GPU.

1. Add these following lines to your hyprland.conf
```
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
```
2. Use supergfxctl to run Integrated Graphics mode.
3. Run any OpenGL game.

**Comment by vaxerski** [comment]
does it work on sway or kde? I fail to see how this is a hyprland issue

**Comment by ItsFireStorm** [comment]
This issue has already been resolved in a separate forum.
