### ISSUE TITLE
"hyprctl keyword binds:" fails when setting a property 

### ISSUE THREAD

**Issue by Ringflash** [hyprwm/Hyprland#8250]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Hi! Command
`hyprctl keyword binds:window_direction_monitor_fallback 1`
Outputs "bind: invalid flag"

Seems that hyprctl tries to execute keybind and not set the "binds:window_direction_monitor_fallback" property.
How can I solve this problem?

But this commands work:
`hyprctl getoption binds:window_direction_monitor_fallback`
`hyprctl keyword general:border_size 10`

NixOS 24.05, zsh shell, Hyprland v0.41.2, commits: 918d8340afd652b011b937d29d5eea0be08467f5

### How to reproduce

hyprctl keyword binds:window_direction_monitor_fallback 1

**Comment by vaxerski** [comment]
update from your horribly outdated version
