### ISSUE TITLE
startup/shutdown animation

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/Hyprland#8253]
### Description

i noticed that KDE have animation for shutting, it popin all the apps, maybe we could do that? or just popin the whole wm(altogether)? and the same for startup animation?

**Comment by fufexan** [comment]
There is a startup animation already. Might be hard to see if your display takes a long time to react to input signals.

**Comment by nonetrix** [comment]
For some reason after Aquamarine merge it's harder to see, I guess it's faster or doesn't wait for display to connect?

**Comment by vaxerski** [comment]
it's not after aq merge it's after I optimized assets to prevent hyprland hanging for a few seconds on launch.

I have not found any single method that I could query to see if the display is "preparing" to show an image (modesetting in progress) so I think it's not queryable from our side.

**Comment by littleblack111** [comment]
anyways, why is the issue closed? is it not gonna get implementedcustom startup and shutdown animation)?

**Comment by vaxerski** [comment]
correct
