### ISSUE TITLE
implement inhibit_idle windowrule

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#826]
Maybe I missed it, but I don't find any equivalent of `inhibit_idle fullscreen|open|focus`  equivalent in sway.

For instance, in Sway I have this rule

```
for_window [app_id="fceux"] inhibit_idle focus, inhibit_idle fullscreen
```

Which inhibits idling when fceux is either focus or fullscreen.

**Comment by vaxerski** [comment]
fyi, in before this gets eventually implemented, some people like @taylor85345 (iirc) have simply made a script to play fake audio from some inhibit idle app within a script that listens to .socket2

**Comment by taylor85345** [comment]
I use sway-audio-idle-inhibit-git. My primary use case is for gaming, where the game audio alone is enough to trigger the inhibitor and prevent locking, no scripting required.

**Comment by vaxerski** [comment]
done in a69fd21a1ac90c24cee659595d62329f8638d632

windowrule `idleinhibit`, modes: `none`, `always`, `focus`, `fullscreen`

**Comment by primalmotion** [comment]
thanks!

**Comment by AdsonCicilioti** [comment]
@vaxerski It seems like this isn't working anymore... Could you take a look at #3526?
