### ISSUE TITLE
do not let the focus to wander away from the currently focused monitor

### ISSUE THREAD

**Issue by laszloszurok** [hyprwm/Hyprland#8262]
### Description

Hello!

I have some window rules that bind clients to workspaces.

My problem is if a workspace is visible on an unfocused monitor, then that monitor will get focused when I open a window belonging to that workspace. I'd like to keep the focus on one monitor, until I manually change focus. 

So I'd like to bring the workspace on the unfocused monitor to the focused one automatically, when a new client is opened on that workspace.

I tried to script this, but as far as I've seen, hyprctl does not have a "focus previously focused mon" dispatcher and I was unable to come up with a properly working solution.

I tried something like this:

```sh
    if [ "$event" = "focusedmon" ]; then
        curr_mon=$(hyprctl monitors -j | jq -r ".[] | select(.focused==true).id")
        echo "$curr_mon" > ~/.config/hypr/scripts/monid
    fi

    if [ "$event" = "openwindow" ]; then
        curr_mon=$(hyprctl monitors -j | jq -r ".[] | select(.focused==true).id")
        prev_mon=$(cat ~/.config/hypr/scripts/monid)

        if [ "$curr_mon" != "$prev_mon" ]; then
            hyprctl dispatch focusmonitor "$prev_mon"
            hyprctl dispatch swapactiveworkspaces "$prev_mon" "$curr_mon"
            echo "$curr_mon" > ~/.config/hypr/scripts/monid
        fi
    fi
```
but this makes the workspaces switch back-and-forth when I open windows

**Comment by Aqa-Ib** [comment]
Quoting the wiki at window rules, workspace: 
```
You can also add silent after the workspace to make the window open silently.
```
I think that is what you want.

**Comment by laszloszurok** [comment]
Based on your tip I put this in my event handler scirpt:
```sh
    if [ "$event" = "openwindow" ]; then
        curr_ws_id=$(hyprctl activeworkspace -j | jq .id)
        new_win_addr=0x$(echo "$2" | cut -d , -f 1)
        new_ws_id=$(hyprctl clients -j | jq ".[] | select(.address==\"$new_win_addr\").workspace.id")
        if [ "$curr_ws_id" != "$new_ws_id" ]; then
            hyprctl dispatch focusworkspaceoncurrentmonitor "$new_ws_id"
            hyprctl dispatch focuswindow "address:$new_win_addr"
        fi
    fi
```
This with the `silent` option for the workspace rules fits my usecase, so I'll close the issue.

Thank you!
