### ISSUE TITLE
[FEATURE REQ] To be able to highlight or draw on any screen/workspace of hyprland like Gromit-MPX (FOSS program but works best for x11 only) 

### ISSUE THREAD

**Issue by Greatz08** [hyprwm/Hyprland#8263]
### Description

Gromit-MPX - https://github.com/bk138/gromit-mpx

This is great open source app to help people draw on any working screen so that they can highlight or draw anything. So if a person is teacher or presenter and is trying to highlight some key things of any screen they can or if they need to write anything on screen they can too or draw any minor they can easily with some key shortcuts. Excalidraw is another awesome open source project for similar thing but it is limited to its own web app so we cant just use its great highlighter or other functionalities on screen while presenting any pdf or app app for some specific things. With Gromit-MPX we can do some stuff of drawing and erasing but it doesnt have highlighter like excalidraw plus it works best on x11 altho i and many were able to run it on wayland but it by no mean is smooth and properly functional using xwayland . I have tested personally and while screen sharing,  it freezes the whole screen even tho system is functional and drawing but it doesn't show anything after sometime to other users so overall no perfect experience.

I have seen many hyprland plugins which do add some additional things  to hyprland so thought if it would be possible to create something similar for hyprland which would solve this purpose will be great for many users. U know those users who will be using this feature are not many but still it will be great to have it . So if this is possible then do add it in hyprland as plugin or maybe as native feature.

**Comment by vaxerski** [comment]
this would be better as a client.
