### ISSUE TITLE
Position of client (window) inside the workspace.

### ISSUE THREAD

**Issue by jovanmaric** [hyprwm/Hyprland#8269]
### Description

I am using the master layout and can calculate the position of the client (window) through the `at` key from `hyprctl clients`. But triggering `fullscreen` or using something like `movewindow, mon:+1` makes this really hard.

Considering that `movewindow, mon:+1` works I assume that the client position is persisted internally and it would be really handy if the position of a window whithin a workspace is exposed somehow to `hyprctl clients`.

**Comment by vaxerski** [comment]
cache your monitor layout and use the `monitor` part to determine which one it's on

**Comment by jovanmaric** [comment]
Ah wait I copied the wrong command :disappointed:. I meant with `layoutmsg, cyclenext` instead of `movewindow, mon:+1`. I've edited it in the original question ^^

**Comment by vaxerski** [comment]
I don't understand, are you saying that `cyclenext` layoutmsg doesn't update the `at` and `size` fields of `hyprctl clients`?!

fullscreen is there and you can make a special case for that in your script program whatever

**Comment by jovanmaric** [comment]
No what I mean is that the `at` values of windows in `fullscreen` mode are a bit unexpected and that adding an `order` value to the `hyprctl clients` output for both fullscreen and normal view, would make it easier to figure out in what order the clients inside a workspace are.

For instance in the following setup:
* **Kitty**: master and fullscreen
* **VSCode**: slave
* **Thunar**: slave

When switching windows with `cyclenext` and `fullscreen = 1`, a strange thing happens where it isn't clear from `hyprctl clients` what the next client is in the cycle order, because order can't be derived from the `at` coordinates. The `dot` below represents the focused fullscreen window when cycling.

```
.Kitty 		at: [0, 0]
Code 		at: [1242, 1]
Thunar 		at: [1242, 753]

.Code 	        at: [0, 0]
Kitty 	        at: [1, 1]
Thunar	        at: [1242, 753]

.Thunar         at: [0, 0]
Kitty 	        at: [1, 1]
Code 		at: [1242, 1]

.Kitty 		at: [0, 0]
Code 		at: [1242, 1]
Thunar 		at: [1242, 753]
```

The second and third state make it look like `Kitty` is always next in line to be cycled to, while the inner state of hyprland does know what it points to, and cycles properly to `Thunar`.

**Comment by jovanmaric** [comment]
Are there maybe any plans to expose this layout (specific) data through the IPC events or hyprctl commands? This would make it exponentially easier to implement something like a bar with (positioned) client icons (in eww, ags whatev).

**Comment by vaxerski** [comment]
atm no

**Comment by jovanmaric** [comment]
Ah that's too bad, I'll have to figure this out in a different way. Thanks for the quick replies and Hyprland!
