### ISSUE TITLE
Floating window with special workspace

### ISSUE THREAD

**Issue by thomascft** [hyprwm/Hyprland#827]
When moving a floating window to the special workspace it floats above other clients and doesn't tile. This could be fixed by switching the window to tiling somewhere through the process, but having a check before moving to the special workspace would be good.

**Comment by vaxerski** [comment]
I was thinking about allowing floats in special in general.

**Comment by thomascft** [comment]
Ok, I think the windows in the special need to be resizable somehow.

**Comment by ttmx** [comment]
This would be really nice, it would allow for easy "dropdown" windows, which I would say are very useful.
Thank you

**Comment by thomascft** [comment]
> This would be really nice, it would allow for easy "dropdown" windows, which I would say are very useful.
> Thank you

I didn't do the best job at phrasing my initial issue but the special workspace essentially creates a second workspace overlaying the current. My issue was when sending a floating window to the special workspace. Upon toggling the special you'll find the floating window above all the other special windows often covering them as if on a third layer. When trying to resize or move the special window it's placed on the active normal workspace

**Comment by TheSunCat** [comment]
I am experiencing this issue, except moving/resizing the floating window in the special workspace does not tile it, nor does executing the `toggletiling` bind. The only way I've found to get it out of that state is to move it to another workspace.
I'm not opposed to having floating windows in the special workspace, though I think the default behavior being tiled works quite well (if this bug didn't exist).
I can trigger it by making any window floating, then moving it to the special workspace using `movetoworkspace,special`.

**Comment by MightyPlaza** [comment]
@vaxerski
