### ISSUE TITLE
Keyboard and mice connected at login not working with lightdm

### ISSUE THREAD

**Issue by MartinEmrich** [hyprwm/Hyprland#8278]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit d49a1334a8af7c704626cdf1746cb72415ad6d0d  (swallow: check if swallow_regex doesn't exist (8265)).
Date: Mon Oct 28 17:52:14 2024
Tag: v0.44.0-88-gd49a1334, commits: 5387
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: x230
Release: 6.11.2-amd64
Version: #1 SMP PREEMPT_DYNAMIC Debian 6.11.2-1 (2024-10-05)


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])


os-release: PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


plugins:
        unknown: not runtime
```

</details>

### Description

Runing on my laptop (Thinkpad X230), Hyprland starts and looks as expected, but neither the pointer moves nor it accepts keyboard input.

Plugging in USB mouse or keyboard, these work fine. Only the builtin keyboard and trackpoint/trackpad are affected.

Hyprland logs input events from the builtin devices, but does not act on them or relays them to the applications.

The same (input-wise default) configuration works fine on my desktop PC.

Running sway, there the mouse moves fine. With X11 based DE they work, too.

### How to reproduce

* Install Debian testing on a Thinkpad X230
* Login manager is lightdm
* build hyprland (including hyprutils and aquamarine) from current git main

### Crash reports, logs, images, videos

Log snippet: One is the built-in mouse button, the other is from the external USB mouse.

```

[LOG] [AQ] [libinput] event16 - debounce state: DEBOUNCE_STATE_IS_UP → DEBOUNCE_EVENT_PRESS → DEBOUNCE_STATE_IS_DOWN_WAITING

[LOG] [AQ] [libinput] event16 - debounce state: DEBOUNCE_STATE_IS_DOWN_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_DOWN

[LOG] [AQ] [libinput] event16 - debounce state: DEBOUNCE_STATE_IS_DOWN → DEBOUNCE_EVENT_RELEASE → DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS

[LOG] [AQ] [libinput] event16 - debounce state: DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS → DEBOUNCE_EVENT_TIMEOUT_SHORT → DEBOUNCE_STATE_IS_UP_WAITING

[LOG] [AQ] [libinput] event16 - debounce state: DEBOUNCE_STATE_IS_UP_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_UP

[LOG] [AQ] [libinput] event6  - debounce state: DEBOUNCE_STATE_IS_UP → DEBOUNCE_EVENT_PRESS → DEBOUNCE_STATE_IS_DOWN_WAITING

[LOG] [AQ] [libinput] event6  - debounce state: DEBOUNCE_STATE_IS_DOWN_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_DOWN

[LOG] [AQ] [libinput] event6  - debounce state: DEBOUNCE_STATE_IS_DOWN → DEBOUNCE_EVENT_RELEASE → DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS

[LOG] [AQ] [libinput] event6  - debounce state: DEBOUNCE_STATE_IS_UP_DETECTING_SPURIOUS → DEBOUNCE_EVENT_TIMEOUT_SHORT → DEBOUNCE_STATE_IS_UP_WAITING

[LOG] [AQ] [libinput] event6  - debounce state: DEBOUNCE_STATE_IS_UP_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_UP
```

**Comment by MartinEmrich** [comment]
I tried a different DM to be sure...

and indeed, with GDM3 the keyboard and mouse work.

With lightdm, indeed  _all_ input devices connected during login are affected, including USB devices.
Unplugging and reinserting the external devices after logging in makes them work (obviously not possible with the laptop devices).

**Comment by gulafaran** [comment]
https://github.com/canonical/lightdm/issues/63

**Comment by MartinEmrich** [comment]
@gulafaran Thanks, that ticks lightdm off my list.
