### ISSUE TITLE
Auto back and forth triggered by window rules

### ISSUE THREAD

**Issue by horriblename** [hyprwm/Hyprland#828]
when `binds:auto_back_and_forth = true` and a window rule is set to move the window to the currently focused workspace, the window spawns in the previous workspace instead.
This happened to me on steam because for some reason steam creates separate windows for dropdown menus

### Steps to reproduce
1. config:
```
binds {
	workspace_back_and_forth=true
}
windowrule = workspace 7,^(Steam)$
```

2. Open steam  (on workspace 7)  and open any drop down menu  (anything on the top left corner of the window)

**Comment by vaxerski** [comment]
should be fixed in 624303bfb934761518d601053bfb54cf0a73e0bd
