### ISSUE TITLE
Ability to get window Z-orders from `hyprctl`

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#8283]
### Description

I would like to see the `zorder` listed on each `hyprctl clients -j` object.

**Comment by vaxerski** [comment]
as in the order in the stack? they are sorted then in the output. Tiled windows are on their own (base) plane. Filtering out those will leave you with a sorted list from bottom to top

**Comment by spikespaz** [comment]
> as in the order in the stack?

I think, yes. Whatever the `alterzorder` dispatcher changes (for floating windows).

>  they are sorted then in the output ... from bottom to top

Would that be ascending or descending? :stuck_out_tongue: I can find out.

I think that is unintuitive, but it is also problematic for `hyprland-rs`. `Vec` is ordered by implementation detail, but ordering can't be relied upon. I will have to make a PR to change `Clients` inner `Vec` into an `OrdredVec` of some kind, which brings in another dependency. @yavko 

I think the most straightforward solution would be a backwards compatible additive feature,
the introduction of a `zorder` or `zindex` which is always `0` for base plane, and greater than zero for floating windows. Or, `null` for base plane, if you *must*.

---

Now, I thought the order listed by `hyprctl` was corresponding to `focusHistoryId`? It appears to be this way.

**Comment by yavko** [comment]
> > as in the order in the stack?
> 
> I think, yes. Whatever the `alterzorder` dispatcher changes (for floating windows).
> 
> >  they are sorted then in the output ... from bottom to top
> 
> Would that be ascending or descending? :stuck_out_tongue: I can find out.
> 
> I think that is unintuitive, but it is also problematic for `hyprland-rs`. `Vec` is ordered by implementation detail, but ordering can't be relied upon. I will have to make a PR to change `Clients` inner `Vec` into an `OrdredVec` of some kind, which brings in another dependency. @yavko 
> 
> I think the most straightforward solution would be a backwards compatible additive feature,
> the introduction of a `zorder` or `zindex` which is always `0` for base plane, and greater than zero for floating windows. Or, `null` for base plane, if you *must*.
> 
> ---
> 
> Now, I thought the order listed by `hyprctl` was corresponding to `focusHistoryId`? It appears to be this way.

Isn't Vec ordered, why would it require another dependency?

**Comment by vaxerski** [comment]
> Now, I thought the order listed by hyprctl was corresponding to focusHistoryId? It appears to be this way.

No.

> but it is also problematic for hyprland-rs

That's not my problem though is it? :P

zindex would be fine... but it is not kept anywhere internally. It doesn't exist. That's not how our renderer works.

All I could give you would be `i` when iterating over the vector, but that's kinda pointless... otherwise I'd have to count the tiled windows that came before, which can be done by the client too..

**Comment by spikespaz** [comment]
@yavko Sorry, I am misremembering. My concern is coming from how the memory layout is an implementation detail, not to be relied upon after insertions/removals. Yes, `Vec` is ordered. What a silly statement I made.
