### ISSUE TITLE
obs screen recording cannot hide the mouse

### ISSUE THREAD

**Issue by eqfae** [hyprwm/Hyprland#8286]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

双系统现在win 有必要再补充
Dual systems in Win. I'll add more if necessary.
<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

https://github.com/user-attachments/assets/8fc21055-5606-4e36-9b66-cce6f50ddd3c

https://github.com/user-attachments/assets/7065b343-1544-4b52-b7d1-fb696b597841

二者我都停留在obs界面
I stay on the obs interface for both
我已经重装过1次系统 让hyprland 更多用home配置 但依旧如此
I've already reinstalled the system once to make hyprland use more home configurations, but it still does.

### How to reproduce

```
  programs.hyprland = {
    enable = true;
  };
  xdg.portal = {
    enable = true;
    xdgOpenUsePortal = true;
    config = {
      common.default = [ "hyprland" ];
      hyprland.default = [
        "hyprland"
      ];
    };
    extraPortals =
      [
      ];
  };
  environment.sessionVariables.NIXOS_OZONE_WL = "1";
  environment.sessionVariables.WLR_NO_HARDWARE_CURSORS = "1";


  ### home.nix

  wayland.windowManager.hyprland = {
    enable = true;
    systemd = {
      enable = true;
      enableXdgAutostart = true;
      variables = [
        "--all"
      ];
    };
    settings = {
      source = [
        "~/.config/hypr/hyprland/env.conf"
        "~/.config/hypr/hyprland/general.conf"
        "~/.config/hypr/hyprland/rules.conf"
        "~/.config/hypr/hyprland/colors.conf"
        # 自定义配置
        "~/.config/hypr/custom/env.conf"
        "~/.config/hypr/custom/execs.conf"
        "~/.config/hypr/custom/general.conf"
        "~/.config/hypr/custom/rules.conf"
        "~/.config/hypr/custom/keybinds.conf"
      ];
    };
  };  
```

**Comment by vaxerski** [comment]
you did not put version info, so I am assuming you're on nvidia. Nvidia has broken hardware cursors, so they are always software, so they will be visible with recordings.

**Comment by eqfae** [comment]
> you did not put version info, so I am assuming you're on nvidia. Nvidia has broken hardware cursors, so they are always software, so they will be visible with recordings.

是amd显卡
It's an amd video card.

**Comment by eqfae** [comment]
重装时想要一份最小配置
Want a minimum configuration when reinstalling
```
  xdg.portal = {
    enable = true;
    xdgOpenUsePortal = true;
    config = {
      common.default = [ "hyprland" ];
      hyprland.default = [
        "hyprland"
      ];
    };
    extraPortals =
      [
      ];
  };
```
没有这个 obs 将没有pipewire录屏的选项 原配置还有gtk gtk还放在了hyprland前面 但是依然没用
因为我不懂nix 这些配置主要是抄的
Without this obs, there will be no pipewire screen recording option. The original configuration and gtk are still in front of hyprland, but it is still useless
Because I don't understand nix, these configurations are mainly copied

```
  environment.sessionVariables.WLR_NO_HARDWARE_CURSORS = "1";
```
这个没作用 This doesn't work.

**Comment by eqfae** [comment]
Hyprland, built from branch v0.44.1-b at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: 2024-10-09
Tag: v0.44.1, commits: 4520b30d498daca8079365bdb909a8dea38e8d55
built against aquamarine 0.4.3


flags: (if any)


System Information:
System name: Linux
Node name: 112
Release: 6.11.4-cachyos
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu Oct 17 13:27:02 UTC 2024


GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241025.18536bf"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
        unknown: not runtime

**Comment by vaxerski** [comment]
`WLR_NO_HARDWARE_CURSORS` isnt used since.. 0.39 I believe. See `no_hardware_cursors` in the wiki

**Comment by eqfae** [comment]
> `WLR_NO_HARDWARE_CURSORS` isnt used since.. 0.39 I believe. See `no_hardware_cursors` in the wiki

I'll try.
cursor {
    no_hardware_cursors = true
}

**Comment by eqfae** [comment]
https://github.com/user-attachments/assets/ed87f8c1-3f51-4507-abfe-8127c5691877
修改后重新登陆
gtk早在flake删除了 我也不知道为什么还在
Log in again after modification
Gtk deleted it in flake and I don't know why it's still there

**Comment by eqfae** [comment]
有人吗 
有运行过kde但是在alpine可以隐藏 但桌面体验不好那个系统 nixos使用hyprland 但无法隐藏鼠标 
还没使用过别的 我看到comsic 但他还没发稳定版
Anyone?
Have run kde but can hide it in alpine but desktop experience is not good with that system nixos uses hyprland but can't hide the mouse
Haven't used anything else yet. I saw comsic, but he hasn't released a stable version yet.
