### ISSUE TITLE
Rotation using external app (kanshi)

### ISSUE THREAD

**Issue by etrnal70** [hyprwm/Hyprland#829]
Hello, thank you for this really cool project ! Is rotation using external app support planned in the future ? My usecase is that i'm using kanshi for automatic screen configuration for my home and work profile. It's literally the only bug that stopping me from using hyprland daily 😄

**Comment by vaxerski** [comment]
it's maybe planned? never thought of this really, as you can set the transforms in the config.

**Comment by vaxerski** [comment]
should be done in c47581fc5aedcff172b76b658593a1e7c712e448

**Comment by etrnal70** [comment]
Still not working, tried using both kanshi and wdisplays. Currently on latest commit `b4c45aa2e3`

**Comment by pdamianik** [comment]
Should become possible with #3234 (not tested)
