### ISSUE TITLE
Moving full screen game causes to crash

### ISSUE THREAD

**Issue by Heisfer** [hyprwm/Hyprland#831]
So I was trying to move fullscreen game to another monitor but it crashed ( have happened before)
below is coredump file

[test.txt](https://github.com/hyprwm/Hyprland/files/9757874/test.txt)

**Comment by vaxerski** [comment]
move with movetoworkspace?

**Comment by Heisfer** [comment]
yes

**Comment by vaxerski** [comment]
can't reproduce, but please check 1396d2a39bec3be434dcb79e5c29d5c52a017d21

**Comment by Heisfer** [comment]
Now it's working fine (artifact on between changing), Maybe it's because laptop is 16:10 and monitor is 16:9?

artifact get removed when creating new window (terminal) or focusing terminal on it

**Comment by vaxerski** [comment]
if you can record that I could look into it. But since the crash is fixed, closing

**Comment by KyleUltimate** [comment]
Can confirmed this is fixed! It used to always crash when I launch a wayland native game(`osu-lazer` on wayland)
But now it doesn't, but I can't see artifacts either
