### ISSUE TITLE
Hide floating windows and only show tiled windows while holding keybind

### ISSUE THREAD

**Issue by farelmapm** [hyprwm/Hyprland#8315]
### Description

I mostly work with tiled windows, but I have set some rules for certain programs like my file manager or my download managers to float by default. However, because of the nature of Hyprland, floating windows will always be on top of tiled windows. Sometimes I need to see something in the tiled window covered under the floating window, and currently I need to either move the window out of the way or I just turn it into a tile window or even close the floating window all together. What I want is a functionality that, when assigned to a keybind and held, hides all floating windows on the current workspace. Something like Windows' functionality that allows you to hide all currently open windows while you hover your cursor on the bottom right of your screen. 

Is this even possible to implement? Perhaps maybe something like detecting if the client is floating=1 and is in the current active workspace, and then setting opacity to 0?

**Comment by vaxerski** [comment]
`hyprctl -r keyword 'windowrulev2' 'opacity 0,floating:1'`, to revert `hyprctl -r keyword 'windowrulev2' 'opacity 1,floating:1'`

needs lates hyprland-git to work properly. You can combine this with transparent binds.
