### ISSUE TITLE
OBS makes cursor high-res

### ISSUE THREAD

**Issue by colin-heffernan** [hyprwm/Hyprland#832]
Whenever I open OBS and capture the screen, my cursor goes high-res. It's as if it's using a higher-resolution version of the cursor and downscaling it. Is there any way to make this change permanent?

**Comment by pinkcreeper100** [comment]
Set the `XCURSOR_SIZE` environment variable

**Comment by vaxerski** [comment]
`export XCURSOR_SIZE=24` in your wrapper

**Comment by colin-heffernan** [comment]
It's not the normal X cursor, though. I know about it changing the cursor size. This is different. The cursor is the same size, just clearer. As well, the cursor is still changed after the mouse leaves the OBS window. Any ideas?

**Comment by vaxerski** [comment]
it might be a GTK / Qt cursor theme mismatch
