### ISSUE TITLE
If and else on the config file

### ISSUE THREAD

**Issue by Wateir** [hyprwm/Hyprland#8332]
### Description

I live on two different place, and my setup change for the monitor, so each time i change place i have to uncomment some preconfig monitor setup and comment other, so i want to automatise it with some conditional code, sometinght like this :

if monitor1 and monitor2 connect
then
 monitor = monitor1, prefered, auto, auto
  monitor = monitor2, prefered, auto, auto
  monitor = Lid, disable

elif monitorA connect
then
  monitor = monitorA, prefered, auto, auto
  monitor = Lid, prefered, auto, auto

else
  monitor = Lid, prefered, auto, auto

of course this if and else can be use for other purpose than mine

**Comment by vaxerski** [comment]
use kanshi or shikane, they do exactly that
