### ISSUE TITLE
Hyprland Crashes to Logout Screen When Opening File Picker in Multiple Applications

### ISSUE THREAD

**Issue by fr0st-iwnl** [hyprwm/Hyprland#8335]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit 40081cb330fa838ad9c0a7b87c20b2300ea7fb38  (renderer: improve api around new framebuffer changes).
Date: Sat Nov 2 15:26:45 2024
Tag: v0.44.0-104-g40081cb3, commits: 5403
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: archlinux
Release: 6.11.6-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:35 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime
```

</details>

### Description

I am encountering a problem with Hyprland on Arch Linux where the system crashes and returns to the logout screen whenever I try to open the file picker dialog in various applications.

### How to reproduce

This issue occurs when I open the file picker in applications like VSCodium or Vesktop. To reproduce, follow these steps:

1. Open any application that uses a file picker (like VSCodium or Vesktop [`vesktop-bin`] it seems to happen for this version of vesktop).
2. Click on **"Open Folder"** or **"Upload a file"**.
3. The application opens the file picker, and the entire **DE** crashes, taking me back to the logout screen. This crash happens when I try to click on categories like Downloads or Pictures, or when I try to move the file picker.

This issue specifically occurs with non-Wayland applications. For example, it wasn't happening before with the normal VSCodium application, and while running the VSCodium Wayland version fixed the clicking issue for the categories, it still crashes when I try to move the file picker. I don’t really know why this issue started happening randomly.

### Crash reports, logs, images, videos

Crash report : [hyprlandCrashReport66311.txt](https://github.com/user-attachments/files/17609125/hyprlandCrashReport66311.txt)

**Video :**

https://github.com/user-attachments/assets/e91135f8-3a46-4ba8-bdc4-3b829fffb0b9

**Comment by UltraBlackLinux** [comment]
exact duplicate of #8331

**Comment by fr0st-iwnl** [comment]
I fixed the issue by switching from `hyprland-git` to the regular `hyprland` package. I uninstalled `hyprland-git` and then installed `hyprland` from the **AUR**, which resolved the problem.
