### ISSUE TITLE
Incorrect generation of a Systemd unit when building via CMake

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/Hyprland#8340]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit 514e0ff509f3bf4c98515f08216ac2eeb8797517 dirty (flake: update nixpkgs).
Date: Sun Nov 3 13:14:49 2024
Tag: v0.44.0-105-g514e0ff5, commits: 5404
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: localhost
Release: 6.11.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600] [1002:7480] (rev cf) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

After https://github.com/hyprwm/Hyprland/commit/32b18179dd789cde948c97eb3c2ebbdd6af36bf7, the unit content responsible for starting and shutting down Hyprland looks like this:
```
ExecStart=/usr//usr/bin/Hyprland
ExecStop=/usr//usr/bin/hyprctl dispatch exit
```
Due to this problem, for the unit to work properly, I had to manually set the correct path via `systemctl edit`. I was able to fix this issue locally with this patch (it will break the compilation via Meson):
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -15,7 +15,7 @@
 set(HYPRLAND_VERSION ${VER})
 set(PREFIX ${CMAKE_INSTALL_PREFIX})
 set(INCLUDEDIR ${CMAKE_INSTALL_INCLUDEDIR})
-set(BINDIR ${CMAKE_INSTALL_BINDIR})
+set(BINDIR ${CMAKE_INSTALL_FULL_BINDIR})
 configure_file(hyprland.pc.in hyprland.pc @ONLY)

 set(CMAKE_MESSAGE_LOG_LEVEL "STATUS")
--- a/systemd/hyprland-session.service.in
+++ b/systemd/hyprland-session.service.in
@@ -9,8 +9,8 @@

 [Service]
 Type=notify
-ExecStart=@PREFIX@/@BINDIR@/Hyprland
-ExecStop=@PREFIX@/@BINDIR@/hyprctl dispatch exit
+ExecStart=@BINDIR@/Hyprland
+ExecStop=@BINDIR@/hyprctl dispatch exit
 ExecStopPost=systemctl --user unset-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP
 Restart=on-failure
 Slice=session.slice
```

### How to reproduce

Above

**Comment by fufexan** [comment]
From https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html:

CMAKE_INSTALL_FULL_\<dir>
> These variables shouldn't be used in [install()](https://cmake.org/cmake/help/latest/command/install.html#command:install) commands as they do not work with the cmake --install command's [--prefix](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake--install-0) option, or with the [cpack](https://cmake.org/cmake/help/latest/manual/cpack.1.html#manual:cpack(1)) installer generators.

**Comment by fufexan** [comment]
Actually you're right, it seems that `<dir>`s are passed with full path, not taking `prefix` into account. I will fix this soon:tm:

**Comment by izmyname** [comment]
I think it should be closed as Hyprland no longer provides its own systemd unit. See https://github.com/hyprwm/Hyprland/issues/8424
