### ISSUE TITLE
Add a way to dismiss a the config error notification

### ISSUE THREAD

**Issue by laine-hallot** [hyprwm/Hyprland#8341]
### Description

While I appreciate hyprland letting me know my config has issues not being able to dismiss the error notification makes dealing with said errors a little annoying, especially on a laptop with a relatively small screen.

Dismissing the notification with `hyprctl dismissnotify` doesn't work, neither does trying to kill the popup with `hyprctl kill`, so I end up needing to resort to some pretty dumb window positioning to be able to read my browser tabs and terminal.
![image](https://github.com/user-attachments/assets/648bc422-aa2b-4db0-b100-d1d1e424051f)

**Comment by zakk4223** [comment]
debug:suppress_errors = true
You can retrieve the errors via the command line with 'hyprctl configerrors'

If you're a bar using type person you could write a widget to give you a visual display when there are errors. If you're not you could maybe watch the ipc socket for config reloads and then retrieve the errors and display them some other way.

**Comment by laine-hallot** [comment]
> debug:suppress_errors = true
> You can retrieve the errors via the command line with 'hyprctl configerrors'

I did see people suggest that but I actually like being notified about config issues so I'd rather not out right disable it. The issue is just that I can't dismiss them once I've seen them


> If you're a bar using type person you could write a widget to give you a visual display when there are errors. If you're not you could maybe watch the ipc socket for config reloads and then retrieve the errors and display them some other way. 


at that point i feel like my time would be better spent implementing the feature myself and making a pull request

**Comment by vaxerski** [comment]
it will push your windows too on git. Dismissing is not planned.

**Comment by laine-hallot** [comment]
> it will push your windows too on git. Dismissing is not planned.

Do you mean that the pop up will take up actual space in the window grid? That sounds slightly odd but I guess it would fix my issue so I'm looking forward to that getting out of git and into the main release

**Comment by vaxerski** [comment]
yes.
