### ISSUE TITLE
`inherit_fullscreen` : on The master Layout make new window also inherit fullscreen and be the active one

### ISSUE THREAD

**Issue by simanga-dev** [hyprwm/Hyprland#8348]
### Description

I am not sure if this already exists, as I am new to Hyprland coming from `dwm`. I am in fullscreen mode, such as `monocle`, and when opening a new window, I want it to also be in fullscreen mode and become the current active window.

**Comment by TAforever** [comment]
You can achieve this behavior if you set 

```
misc {
        new_window_takes_over_fullscreen = 1
}
```

**Comment by soufhehe** [comment]
> You can achieve this behavior if you set
> 
> ```
> misc {
>         new_window_takes_over_fullscreen = 1
> }
> ```

And it can be made togglable if you want

here is an example to disable battery effect dynamically : 
![image](https://github.com/user-attachments/assets/bc4cec27-fa8e-4993-8fb4-36515359f194)

just change hyprctl commands with  
> hyprctl keyword misc:new_window_takes_over_fullscreen 1 
and
> hyprctl keyword misc:new_window_takes_over_fullscreen 0

**Comment by simanga-dev** [comment]
Thank you everyone who @TAforever  and @soufhehe  That work perfect... I have another question but I think I will ask this one on reddit hyprland channel.

How can I set the `special workspace to off` or `on`? I don't mean `togglespecialworkspace`. in sense is I want to be able to set the special workspace hidden by command  if it is open... and if not just do nothing

**Comment by soufhehe** [comment]
> Thank @TAforever and @soufhehe That work perfect... I have another question but I think I will ask this one on reddit hyprland channel.
> 
> How can I set the `special workspace to off` or `on`? I don't mean `togglespecialworkspace`. in sense is I want to be able to set the special workspace hidden by command if it is open... and if not just do nothing

yes it's possible, i've used this to exit special workspace when switching to another workspace :+1: 
 
```
special=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .specialWorkspace.name')
if [ $special -a $special == 'special:special' ] ; then hyprctl dispatch togglespecialworkspace special ; fi
```

you can do almost everything you want with hyprctl
