### ISSUE TITLE
fedora 41 Hyprland no longer working with 6 monitors

### ISSUE THREAD

**Issue by kingmaj0r** [hyprwm/Hyprland#8354]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.11.5-300.fc41.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024


GPU information: 
25:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] [1002:6fdf] (rev ef) (prog-if 00 [VGA controller])
28:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Fedora Linux"
VERSION="41 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=41
VERSION_CODENAME=""
PLATFORM_ID="platform:f41"
PRETTY_NAME="Fedora Linux 41 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:41"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f41/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=41
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=41
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:
	unknown: not runtime
```

</details>

### Description

I have a system running Fedora 41 with two AMD GPUs: an RX 6600 as the primary GPU and an RX 580 as the secondary. In the Hyprland environment, the RX 6600 successfully outputs to its connected monitors, but the RX 580 does not display anything on its assigned screens.

### How to reproduce

How to reproduce:

1. Set up a system with Fedora 41 and two AMD GPUs.
2. Log into the Hyprland environment.
3. Observe that the monitors connected to the primary GPU display correctly, while those connected to the second GPU remain inactive with no output.

### Crash reports, logs, images, videos

None as it does not crash.

**Comment by vaxerski** [comment]
- have you tried `AQ_NO_MODIFIERS`?
- please send a trace log https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log

**Comment by vaxerski** [comment]
the last line literally screams at you

**Comment by kingmaj0r** [comment]
I have now enabled logging, and here are the relevant logs indicating the cause of the issue:

```
[ERR] [EGL] Command eglCreateSyncKHR errored out with EGL_BAD_MATCH (0x12297): _eglCreateSync
[ERR] eglCreateSyncKHR failed
[TRACE] Explicit: can't add sync, EGLSync failed
[TRACE] Aquamarine did not return an explicit out fence
[TRACE] Explicit: 0 presented
[LOG] [AQ] drm: Modesetting DP-1 with 1920x1080@60.00Hz
[ERR] [AQ] EGL (verifyDestinationDMABUF): FAIL, format is unsupported by EGL
[ERR] [AQ] EGL (blit): failed to blit: destination dmabuf unsupported
[ERR] [AQ] drm: Backend requires blit, but blit failed
[TRACE] Monitor state commit failed, retrying without a fence
[LOG] [AQ] drm: Modesetting DP-1 with 1920x1080@60.00Hz
[ERR] [AQ] EGL (verifyDestinationDMABUF): FAIL, format is unsupported by EGL
[ERR] [AQ] EGL (blit): failed to blit: destination dmabuf unsupported
[ERR] [AQ] drm: Backend requires blit, but blit failed
[TRACE] Monitor state commit failed
[TRACE] Aquamarine did not return an explicit out fence
[TRACE] Explicit: 0 presented
[ERR] [EGL] Command eglCreateSyncKHR errored out with EGL_BAD_MATCH (0x12297): _eglCreateSync
[ERR] eglCreateSyncKHR failed
[TRACE] Explicit: can't add sync, EGLSync failed
[LOG] [AQ] drm: Modesetting HDMI-A-1 with 1920x1080@74.97Hz
[ERR] [AQ] EGL (verifyDestinationDMABUF): FAIL, format is unsupported by EGL
[ERR] [AQ] EGL (blit): failed to blit: destination dmabuf unsupported
[ERR] [AQ] drm: Backend requires blit, but blit failed
[TRACE] Monitor state commit failed, retrying without a fence
[LOG] [AQ] drm: Modesetting HDMI-A-1 with 1920x1080@74.97Hz
[ERR] [AQ] EGL (verifyDestinationDMABUF): FAIL, format is unsupported by EGL
[ERR] [AQ] EGL (blit): failed to blit: destination dmabuf unsupported
[ERR] [AQ] drm: Backend requires blit, but blit failed
[TRACE] Monitor state commit failed
[TRACE] Aquamarine did not return an explicit out fence
[TRACE] Explicit: 0 presented
[ERR] [EGL] Command eglCreateSyncKHR errored out with EGL_BAD_MATCH (0x12297): _eglCreateSync
[ERR] eglCreateSyncKHR failed
```

**Comment by vaxerski** [comment]
@ikalco wanna take a look at this?

**Comment by kingmaj0r** [comment]
Hello, is there any progress on this issue?

**Comment by vaxerski** [comment]
if there was someone would've left a comment

**Comment by ikalco** [comment]
@kingmaj0r
can you provide the full log?
its probably something to do with the rx580 not support certain extensions but Hyprland trying to use them on it anyways

**Comment by kingmaj0r** [comment]
Hello @ikalco, heres my full log file.
[hyprland.log](https://github.com/user-attachments/files/18031161/hyprland.log)

**Comment by ikalco** [comment]
> Hello @ikalco, heres my full log file. [hyprland.log](https://github.com/user-attachments/files/18031161/hyprland.log)

alr this aq patch might fix it, but it'll also give more logs if it doesn't so I can find the bug, so
* compile aq with this [patch.txt](https://github.com/user-attachments/files/18049114/patch.txt)
* run Hyprland with **both `AQ_TRACE=1` and `HYPRLAND_TRACE=1`**  set in environment from cmdline
* upload full trace log again, if it doesn't work

**Comment by kingmaj0r** [comment]
Hello @ikalco, I've applied the patch, compiled, and installed it on my system using the following steps:
```
git apply patch.txt
mkdir build && cd build
cmake .. && make
sudo make install
```

I also added the following environment variables to my `Hyprland.conf`:
```
env = HYPRLAND_TRACE,1
env = AQ_TRACE,1
```

The logs appear to remain unchanged, but here they are:
[hyprland.log](https://github.com/user-attachments/files/18050037/hyprland.log)

**Comment by ikalco** [comment]
it doesn't seem like the patch or AQ_TRACE was applied based on the log

for AQ_TRACE, it needs to be set in the environment _**before**_ Hyprland runs, putting it in config won't work
to do so, run Hyprland like the following from a TTY 
```
HYPRLAND_TRACE=1 AQ_TRACE=1 ./build/Hyprland
```

to ensure the patch is applied please follow these steps
```
git apply patch.txt
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target all -j
sudo cmake --install ./build
```
and then ensure the install command outputs something like `Installing: /usr/lib/libaquamarine.so.0.5.0`

**Comment by kingmaj0r** [comment]
Hello @ikalco, I've run the commands you listed above, and it seems the installation was successful. However, the issue is still persisting.

here are the logs. Please note that i had to trim a bit of the logs due to its size.
[hyprland.log](https://github.com/user-attachments/files/18051283/hyprland.log)

**Comment by ikalco** [comment]
ok try this [patch.txt](https://github.com/user-attachments/files/18054632/patch.txt) with the same process as above

**Comment by kingmaj0r** [comment]
Hello @ikalco, this patch has fixed it. Thank you so much for the patch. Let me know if you need anything else.
