### ISSUE TITLE
Hyprland crashing during normal use

### ISSUE THREAD

**Issue by different-name** [hyprwm/Hyprland#8364]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch  at commit e3882b23d09aad7f5c3a708536c87b062f3b0d8d  ().
Date: 2024-11-05
Tag: , commits: 5411
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: sodium
Release: 6.6.58
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 22 13:46:36 UTC 2024


GPU information: 
05:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070 Ti] [10de:2782] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241029.807e915"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:

======Config-Start======


Config File: /home/different/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/ldpr2fzzk97pzml87z7lmvhqg7pp65lf-dbus-1.14.10/bin/dbus-update-activation-environment --systemd --all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$mod=SUPER
source=/nix/store/5nqbr4x6yb7bmny12m1fda75brsh8naz-source/themes/mocha.conf
source=/nix/store/caz8xlhy8grg2lgxa0dc9ardlv580vcg-hyprland-red-accent.conf
animations {
  animation=border, 1, 2, default
  animation=fade, 1, 4, default
  animation=windows, 1, 3, default, popin 80%
  animation=workspaces, 1, 2, default, slide
  enabled=true
}

cursor {
  allow_dumb_copy=true
  no_hardware_cursors=true
}

debug {
  disable_logs=false
}

decoration {
  col.shadow=rgba(00000055)
  dim_inactive=false
  drop_shadow=true
  rounding=5
  shadow_ignore_window=true
  shadow_range=8
  shadow_render_power=3
}

dwindle {
  preserve_split=true
  pseudotile=true
}

general {
  col.active_border=rgb(ed507c)
  col.inactive_border=rgba(18182588)
  gaps_in=3
  gaps_out=6
}

gestures {
  workspace_swipe=true
  workspace_swipe_forever=true
}

group {
  groupbar {
    col.active=rgb(cba6f7)
    col.inactive=rgb(181825)
    col.locked_active=rgb(ed507c)
    col.locked_inactive=rgb(181825)
    height=6
    render_titles=false
  }
  col.border_active=rgb(cba6f7)
  col.border_inactive=rgba(18182588)
  col.border_locked_active=rgb(ed507c)
  col.border_locked_inactive=rgba(18182588)
}

input {
  touchpad {
    disable_while_typing=false
    natural_scroll=true
    scroll_factor=0.500000
  }
  accel_profile=flat
  kb_layout=us
}

misc {
  disable_autoreload=true
  disable_hyprland_logo=true
  disable_splash_rendering=true
}

render {
  direct_scanout=false
}

xwayland {
  force_zero_scaling=true
}
bind=$mod, Q, killactive
bind=$mod, F, fullscreenstate, 2 -1
bind=$mod SHIFT, F, fullscreenstate, -1 2
bind=$mod, R, togglesplit
bind=$mod, G, togglefloating
bind=$mod, A, togglegroup
bind=$mod SHIFT, A, lockactivegroup, toggle
bind=ALT, TAB, changegroupactive, f
bind=ALT SHIFT, TAB, changegroupactive, b
bind=$mod, P, pseudo
bind=$mod, T, pin
bind=CTRL ALT, DELETE, exec, hyprctl kill
bind=CTRL ALT SHIFT, DELETE, exec, pkill Hyprland
bind=$mod, Return, exec, kitty
bind=$mod, L, exec, pgrep hyprlock || hyprlock
bind=$mod, S, exec, rofi -show drun -show-icons
bind=$mod, W, exec, zen
bind=$mod, E, exec, thunar
bind=$mod, left, movefocus, l
bind=$mod, right, movefocus, r
bind=$mod, up, movefocus, u
bind=$mod, down, movefocus, d
bind=$mod SHIFT, left, swapwindow, l
bind=$mod SHIFT, right, swapwindow, r
bind=$mod SHIFT, up, swapwindow, u
bind=$mod SHIFT, down, swapwindow, d
bind=, Print, exec, pgrep grimblast || grimblast --notify --freeze copy area
bind=$mod SHIFT, S, exec, pgrep grimblast || grimblast --notify --freeze copy area
bind=CTRL, Print, exec, pgrep grimblast || grimblast --notify --cursor copy output
bind=$mod SHIFT CTRL, S, exec, pgrep grimblast || grimblast --notify --cursor copy output
bind=$mod, bracketleft, workspace, m-1
bind=$mod, bracketright, workspace, m+1
bind=,mouse:275, workspace, m-1
bind=,mouse:276, workspace, m+1
bind=$mod SHIFT, bracketleft, focusmonitor, l
bind=$mod SHIFT, bracketright, focusmonitor, r
bind=$mod SHIFT ALT, bracketleft, movecurrentworkspacetomonitor, l
bind=$mod SHIFT ALT, bracketright, movecurrentworkspacetomonitor, r
bind=$mod SHIFT, C, exec, pgrep hyprpicker || hyprpicker --autocopy
bind=$mod, 1, workspace, 1
bind=$mod, 2, workspace, 2
bind=$mod, 3, workspace, 3
bind=$mod, 4, workspace, 4
bind=$mod, 5, workspace, 5
bind=$mod, 6, workspace, 6
bind=$mod, 7, workspace, 7
bind=$mod, 8, workspace, 8
bind=$mod, 9, workspace, 9
bind=$mod SHIFT, 1, movetoworkspace, 1
bind=$mod SHIFT, 2, movetoworkspace, 2
bind=$mod SHIFT, 3, movetoworkspace, 3
bind=$mod SHIFT, 4, movetoworkspace, 4
bind=$mod SHIFT, 5, movetoworkspace, 5
bind=$mod SHIFT, 6, movetoworkspace, 6
bind=$mod SHIFT, 7, movetoworkspace, 7
bind=$mod SHIFT, 8, movetoworkspace, 8
bind=$mod SHIFT, 9, movetoworkspace, 9
binde=$mod CTRL, up, resizeactive, 0 -20
binde=$mod CTRL, down, resizeactive, 0 20
binde=$mod CTRL, left, resizeactive, -20 0
binde=$mod CTRL, right, resizeactive, 20 0
bindl=, XF86AudioPlay, exec, playerctl play-pause
bindl=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindle=, XF86AudioRaiseVolume, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 6%+
bindle=, XF86AudioLowerVolume, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 6%-
bindle=, XF86MonBrightnessUp, exec, brillo -q -u 300000 -A 5
bindle=, XF86MonBrightnessDown, exec, brillo -q -u 300000 -U 5
bindm=$mod, mouse:272, movewindow
bindm=$mod, mouse:273, resizewindow
bindm=$mod CTRL, mouse:272, resizewindow
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=XCURSOR_SIZE,16
exec-once=goxlr-daemon
exec-once=steam -silent
monitor=desc:BNQ BenQ EW3270U 5BL00174019, preferred, 0x0, 1.5
monitor=,preferred,auto,1
windowrulev2=suppressevent maximize, class:.*
windowrulev2=float, class:^(qalculate-gtk)$
windowrulev2=size 850 575, class:^(qalculate-gtk)$
windowrulev2=float, title:^(Picture-in-Picture)$
windowrulev2=pin, title:^(Picture-in-Picture)$
windowrulev2=size 480 270, title:^(Picture-in-Picture)$
windowrulev2=keepaspectratio, title:^(Picture-in-Picture)$
windowrulev2=float, class:^(xdg-desktop-portal-gtk)$
windowrulev2=float, class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2=size 1000 750, class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2=float, title:^(File Operation Progress)$
windowrulev2=float, class:^(file-roller)$
windowrulev2=float, title:^(MainPicker)$
windowrulev2=suppressevent fullscreen, class:^(steam_app_[0-9]+|steam_app_default|hl2_linux|Paradox Launcher|AcrossTheObelisk\.x86_64|TerraTechLinux64\.x86_64|diablo iv\.exe|Minecraft(\*)? [0-9\.]+|osu!)$, title:.+
windowrulev2=fullscreen, class:^(steam_app_[0-9]+|steam_app_default|hl2_linux|Paradox Launcher|AcrossTheObelisk\.x86_64|TerraTechLinux64\.x86_64|diablo iv\.exe|Minecraft(\*)? [0-9\.]+|osu!)$, title:.+
windowrulev2=workspace 2, class:^(steam_app_[0-9]+|steam_app_default|hl2_linux|Paradox Launcher|AcrossTheObelisk\.x86_64|TerraTechLinux64\.x86_64|diablo iv\.exe|Minecraft(\*)? [0-9\.]+|osu!)$, title:.+
windowrulev2=stayfocused, class:^(steam_app_[0-9]+)$, title:.+
windowrulev2=stayfocused, class:^(osu!)$, title:.+
windowrulev2=unset, title:Wine System Tray
windowrulev2=workspace special:hidden silent, title:Wine System Tray
windowrulev2=noinitialfocus, title:Wine System Tray
windowrulev2=tile, class:^(battle\.net\.exe)$


Config File: /nix/store/5nqbr4x6yb7bmny12m1fda75brsh8naz-source/themes/mocha.conf: Read Succeeded

$rosewater = rgb(f5e0dc)
$rosewaterAlpha = f5e0dc

$flamingo = rgb(f2cdcd)
$flamingoAlpha = f2cdcd

$pink = rgb(f5c2e7)
$pinkAlpha = f5c2e7

$mauve = rgb(cba6f7)
$mauveAlpha = cba6f7

$red = rgb(f38ba8)
$redAlpha = f38ba8

$maroon = rgb(eba0ac)
$maroonAlpha = eba0ac

$peach = rgb(fab387)
$peachAlpha = fab387

$yellow = rgb(f9e2af)
$yellowAlpha = f9e2af

$green = rgb(a6e3a1)
$greenAlpha = a6e3a1

$teal = rgb(94e2d5)
$tealAlpha = 94e2d5

$sky = rgb(89dceb)
$skyAlpha = 89dceb

$sapphire = rgb(74c7ec)
$sapphireAlpha = 74c7ec

$blue = rgb(89b4fa)
$blueAlpha = 89b4fa

$lavender = rgb(b4befe)
$lavenderAlpha = b4befe

$text = rgb(cdd6f4)
$textAlpha = cdd6f4

$subtext1 = rgb(bac2de)
$subtext1Alpha = bac2de

$subtext0 = rgb(a6adc8)
$subtext0Alpha = a6adc8

$overlay2 = rgb(9399b2)
$overlay2Alpha = 9399b2

$overlay1 = rgb(7f849c)
$overlay1Alpha = 7f849c

$overlay0 = rgb(6c7086)
$overlay0Alpha = 6c7086

$surface2 = rgb(585b70)
$surface2Alpha = 585b70

$surface1 = rgb(45475a)
$surface1Alpha = 45475a

$surface0 = rgb(313244)
$surface0Alpha = 313244

$base = rgb(1e1e2e)
$baseAlpha = 1e1e2e

$mantle = rgb(181825)
$mantleAlpha = 181825

$crust = rgb(11111b)
$crustAlpha = 11111b


Config File: /nix/store/caz8xlhy8grg2lgxa0dc9ardlv580vcg-hyprland-red-accent.conf: Read Succeeded
$accent = $red
$accentAlpha = $redAlpha

======Config-End========
```

</details>

### Description

While sharing screen (thought I am not certain yet if this is exclusively to sharing screen) and using Hyprland normally (does not seem limited to one activity), Hyprland will crash randomly. The screen will freeze, I will still be able to hear audio and speak if I am currently in a call, but cannot interact with anything. After the freeze a random amount of time will pass (a few seconds to 5 minutes) and then Hyprland will crash

### How to reproduce

Use Hyprland as normal while screen casting

### Crash reports, logs, images, videos

First crash today:
[hyprlandCrashReport4582.txt](https://github.com/user-attachments/files/17642022/hyprlandCrashReport4582.txt)

A second crash occurred while writing this report:
[hyprlandCrashReport235479.txt](https://github.com/user-attachments/files/17642024/hyprlandCrashReport235479.txt)

**Comment by vaxerski** [comment]
this does look bad. I'll need some repro case, though.

**Comment by different-name** [comment]
I'm happy to do any testing, but this has happened in a wide variety of circumstances and fairly infrequently (every few hours) so it's difficult to pin down

I believe it has only happened while streaming though - I'll keep an eye out for it in the case that changed

**Comment by different-name** [comment]
Another crash - was sharing screen and left PC for a bit, came back and it was frozen, Hyprland exited shortly after

[hyprlandCrashReport4568.txt](https://github.com/user-attachments/files/17655940/hyprlandCrashReport4568.txt)

**Comment by vaxerski** [comment]
can you try running 0.44.1 or 0.43.0 and see if it happens there too? if not, it would be nice to bisect. I've never seen this happen, but something is wrong here.

**Comment by different-name** [comment]
[hyprlandCrashReport4935.txt](https://github.com/user-attachments/files/17670624/hyprlandCrashReport4935.txt)

Here's one that happened on Tuesday on 0.44.1, I was using stable in hopes that it would help, switched to git to make this report

In this case, it happened right as I closed a browser window - screen froze while the window was fading out, then the crash

**Comment by different-name** [comment]
I'll switch to 0.43.0 and see if that works, if it does I'll bisect - hopefully I get fast crashes :laughing: bisecting will take forever with the few hour frequency

**Comment by different-name** [comment]
Crashed again on 0.43.0, though its currently just screen frozen - taking a while to completely crash

I can SSH in and look at the logs while its in this state, I seem to be able to still perform some kind of inputs

Will upload the logs when/if it finishes crashing

**Comment by different-name** [comment]
I don't think it's going to crash this time, but it is in the frozen state that led to the other crashes

I'm currently playing around with it, hyprctl clients (over ssh) states that the focus changes when I switch workspaces, so clearly the display is frozen (switching between last 2 frames it seems) but there is still stuff working in the background

...

It crashed! I switched workspaces and moved my mouse to try target my browser (zen) and audio froze, hyprctl was unresponsive and stated hyprland ipc did not respond in time

It was frozen for 15-20 minutes

**Comment by different-name** [comment]
[hyprlandCrashReport5156.txt](https://github.com/user-attachments/files/17685996/hyprlandCrashReport5156.txt)

This is the log related to the previous two messages, 0.43.0

Will switch back to git now, as I can't perform a bisect

**Comment by different-name** [comment]
[hyprlandCrashReport3992.txt](https://github.com/user-attachments/files/17689278/hyprlandCrashReport3992.txt)
Another crash log, I was using the browser (zen) as normal, froze as soon as I clicked something

**Comment by ferrreo** [comment]
> [hyprlandCrashReport3992.txt](https://github.com/user-attachments/files/17689278/hyprlandCrashReport3992.txt) Another crash log, I was using the browser (zen) as normal, froze as soon as I clicked something
> 
> Maybe some weird combination of sharing screen and having zen browser open?

https://github.com/hyprwm/Hyprland/issues/8396

I think we are getting the same crash?

**Comment by different-name** [comment]
The last error message looks to be the same

Interesting that you're on AMD, i'm Nvidia

Are you getting it while screen casting?

I have definitely frozen/crashed while not touching the mouse, but it could still be the same issue

**Comment by different-name** [comment]
> This seems to be since https://github.com/hyprwm/Hyprland/commit/d8b865366af9d5ed30d2ee0a437b9a3ed43c10bd

This issue exists at least back to 0.43.0 for me

**Comment by vaxerski** [comment]
looks to me like errors in SHM stuff, can you try not casting with shm and instead with dmabuf?

**Comment by ferrreo** [comment]
> The last error message looks to be the same
> 
> Interesting that you're on AMD, i'm Nvidia
> 
> Are you getting it while screen casting?
> 
> I have definitely frozen/crashed while not touching the mouse, but it could still be the same issue

I'm not screencasting, just existing. Hardware cursors off also seems to fix it for me, which you already had off so I think we do actually have different bugs maybe just with a similar log?

**Comment by different-name** [comment]
> Hardware cursors off also seems to fix it for me, which you already had off so I think we do actually have different bugs maybe just with a similar log?

Most likely different issues then, I don't believe I have ever crashed without screen casting and I have had hardware cursors off for quite a while

**Comment by different-name** [comment]
> looks to me like errors in SHM stuff, can you try not casting with shm and instead with dmabuf?

I'm not familiar with these, how might I cast with dmabuf instead? I had a look at the Hyprland and XDPH variables on the wiki and didn't find any options related

Is it application specific? If so, do you know what application I could use to test?

**Comment by vaxerski** [comment]
yeah some apps or setups might not want to use dmabuf sharing. OBS should work with dmabuf unless your hardware hates it or something

**Comment by different-name** [comment]
Is there supposed to be a source for dmabuf in OBS? I only have the following sources available:

![image](https://github.com/user-attachments/assets/2074628f-b2ba-4627-9a7b-e8a36322543e)

**Comment by different-name** [comment]
Manage to get it by installing the wlrobs plugin

**Comment by different-name** [comment]
However, OBS instantly crashes

```
info: User added source 'Wayland output(dmabuf)' (wlrobs-dmabuf) to scene 'Scene'
fish: Job 1, 'obs' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by vaxerski** [comment]
no, just pipewire

**Comment by different-name** [comment]
> no, just pipewire

It crashed, is there a way to verify OBS is using dmabuf?

**Comment by different-name** [comment]
[hyprlandCrashReport354496.txt](https://github.com/user-attachments/files/17693035/hyprlandCrashReport354496.txt)

Crash log when using OBS

**Comment by different-name** [comment]
New crash today, I was not sharing screen at the time, I don't believe I had shared screen since boot at all

I was using the webcam and was away from the PC at the time of the crash

[hyprlandCrashReport2617.txt](https://github.com/user-attachments/files/17693747/hyprlandCrashReport2617.txt)

**Comment by vaxerski** [comment]
yeah it's constantly the same, looks like some.... double free? UAF? In texture handling... again no clue how

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/17693781/patch.txt)
apply this patch, build in debug, then attach a debug stacktrace: https://wiki.hyprland.org/Nix/Contributing-and-Debugging/#getting-a-debug-stacktrace

**Comment by different-name** [comment]
[debug stacktrace.txt](https://github.com/user-attachments/files/17694613/debug.stacktrace.txt)

Think I did it right!

**Comment by different-name** [comment]
Not sure if this helps, but I also grabbed one for xdph
[xdph debug stacktrace.txt](https://github.com/user-attachments/files/17694641/xdph.debug.stacktrace.txt)

This is from 1s after the previous stacktrace I posted for hyprland

**Comment by vaxerski** [comment]
I dont think you applied the patch

**Comment by different-name** [comment]
[hyprland stacktrace.txt](https://github.com/user-attachments/files/17710426/hyprland.stacktrace.txt)
[xdph stacktrace.txt](https://github.com/user-attachments/files/17710425/xdph.stacktrace.txt)

Sorry about that, I forgot to commit the patch and NixOS ignored it, took a while to get a crash again

**Comment by vaxerski** [comment]
only hyprland stacktrace is needed, and I still don't think you applied the patch xd

**Comment by different-name** [comment]
I've patched it again with text in `hyprctl version` as proof of patching, will wait for another crash and post the stacktrace

![image](https://github.com/user-attachments/assets/64a4d33a-0065-42d4-8370-05c0ffeb187a)

If that doesn't work, maybe I'm getting the wrong stacktrace

**Comment by different-name** [comment]
[gdb.txt](https://github.com/user-attachments/files/17728462/gdb.txt)
Seems to have not worked again, but the patch has been applied:
```console
$ git show c7d9caef052d7cf8a538bdcfbe5bade25083946d
commit c7d9caef052d7cf8a538bdcfbe5bade25083946d
Author: Different <hello@different-name.dev>
Date:   Wed Nov 13 12:00:31 2024 +1000

    Debug patch

diff --git a/src/debug/HyprCtl.cpp b/src/debug/HyprCtl.cpp
index 709d8b69..9210ecfc 100644
--- a/src/debug/HyprCtl.cpp
+++ b/src/debug/HyprCtl.cpp
@@ -869,7 +869,7 @@ std::string versionRequest(eHyprCtlOutputFormat format, std::string request) {
     std::replace(commitMsg.begin(), commitMsg.end(), '#', ' ');
 
     if (format == eHyprCtlOutputFormat::FORMAT_NORMAL) {
-        std::string result = std::format("Hyprland {} built from branch {} at commit {} {} ({}).\n"
+        std::string result = std::format("Hyprland (patched by different) {} built from branch {} at commit {} {} ({}).\n"
                                          "Date: {}\n"
                                          "Tag: {}, commits: {}\n"
                                          "built against aquamarine {}\n\n\n",
diff --git a/src/render/Texture.cpp b/src/render/Texture.cpp
index 91e70afa..91b4b562 100644
--- a/src/render/Texture.cpp
+++ b/src/render/Texture.cpp
@@ -139,7 +139,13 @@ void CTexture::update(uint32_t drmFormat, uint8_t* pixels, uint32_t stride, cons
 
 void CTexture::destroyTexture() {
     if (m_iTexID) {
-        GLCALL(glDeleteTextures(1, &m_iTexID));
+        glDeleteTextures(1, &m_iTexID);                                                                                                                                                                  \
+        auto err = glGetError();                                                                                                                                                   \
+        if (err != GL_NO_ERROR) {                                                                                                                                                  \
+            Debug::log(ERR, "[GLES] Error in call at {}@{}: 0x{:x}", __LINE__,                                                                                                     \
+                       ([]() constexpr -> std::string { return std::string(__FILE__).substr(std::string(__FILE__).find_last_of('/') + 1); })(), err);                              \
+            abort();
+        }
         m_iTexID = 0;
     }
 
```
```console
$ hyprctl version
Hyprland (patched by different) 0.45.0 built from branch  at commit c7d9caef052d7cf8a538bdcfbe5bade25083946d  ().
```

**Comment by vaxerski** [comment]
the hell

let's go atomic I guess
[patch.txt](https://github.com/user-attachments/files/17736665/patch.txt)

**Comment by different-name** [comment]
Patched and waiting for a crash - do you just want the same stacktrace?

<details>
<summary>Proof of patching stuff</summary>

```console
$ git show c23ac4225e91b1d5d2b4c8aa5bebbafb8ac1c8c0
commit c23ac4225e91b1d5d2b4c8aa5bebbafb8ac1c8c0
Author: Different <hello@different-name.dev>
Date:   Thu Nov 14 08:26:36 2024 +1000

    Debug patch 2

diff --git a/src/debug/HyprCtl.cpp b/src/debug/HyprCtl.cpp
index 709d8b69..035095a6 100644
--- a/src/debug/HyprCtl.cpp
+++ b/src/debug/HyprCtl.cpp
@@ -869,7 +869,7 @@ std::string versionRequest(eHyprCtlOutputFormat format, std::string request) {
     std::replace(commitMsg.begin(), commitMsg.end(), '#', ' ');
 
     if (format == eHyprCtlOutputFormat::FORMAT_NORMAL) {
-        std::string result = std::format("Hyprland {} built from branch {} at commit {} {} ({}).\n"
+        std::string result = std::format("Hyprland (patch 2) {} built from branch {} at commit {} {} ({}).\n"
                                          "Date: {}\n"
                                          "Tag: {}, commits: {}\n"
                                          "built against aquamarine {}\n\n\n",
diff --git a/src/macros.hpp b/src/macros.hpp
index 8915e12d..7efd9be7 100644
--- a/src/macros.hpp
+++ b/src/macros.hpp
@@ -100,6 +100,7 @@
         if (err != GL_NO_ERROR) {                                                                                                                                                  \
             Debug::log(ERR, "[GLES] Error in call at {}@{}: 0x{:x}", __LINE__,                                                                                                     \
                        ([]() constexpr -> std::string { return std::string(__FILE__).substr(std::string(__FILE__).find_last_of('/') + 1); })(), err);                              \
+            abort();                                                                                                                                                               \
         }                                                                                                                                                                          \
     }
 
diff --git a/src/render/Texture.cpp b/src/render/Texture.cpp
index 91e70afa..fc6712e1 100644
--- a/src/render/Texture.cpp
+++ b/src/render/Texture.cpp
@@ -139,7 +139,13 @@ void CTexture::update(uint32_t drmFormat, uint8_t* pixels, uint32_t stride, cons
 
 void CTexture::destroyTexture() {
     if (m_iTexID) {
-        GLCALL(glDeleteTextures(1, &m_iTexID));
+        glDeleteTextures(1, &m_iTexID);                                                                                                                                                                  \
+        auto err = glGetError();                                                                                                                                                   \
+        if (err != GL_NO_ERROR) {                                                                                                                                                  \
+            Debug::log(ERR, "[GLES] Error in call at {}@{}: 0x{:x}", __LINE__,                                                                                                     \
+                       ([]() constexpr -> std::string { return std::string(__FILE__).substr(std::string(__FILE__).find_last_of('/') + 1); })(), err);                              \
+            abort();
+        }  
         m_iTexID = 0;
     }
```

```console
$ hyprctl version
Hyprland (patch 2) 0.45.0 built from branch  at commit c23ac4225e91b1d5d2b4c8aa5bebbafb8ac1c8c0  ().
Date: 2024-11-13
Tag: , commits: 5439
built against aquamarine 0.4.3


flags set:
debug
```

</details>

**Comment by different-name** [comment]
Well that was fast thankfully

[gdb.txt](https://github.com/user-attachments/files/17740172/gdb.txt)

**Comment by different-name** [comment]
[gdb.txt](https://github.com/user-attachments/files/17742885/gdb.txt)
Another

**Comment by vaxerski** [comment]
this is mega odd. Does `dmesg` have some logs wrt any faults?

**Comment by different-name** [comment]
Last bit of output from `sudo dmesg` after a crash, not sure if this is what you wanted

```log
[ 5390.764500] NVRM: Xid (PCI:0000:06:00): 69, pid='<unknown>', name=<unknown>, Class Error: ChId 0004, Class 0000c997, Offset 00000808, Data 00200f00, ErrorCode 00000004
[ 5410.152446] .xdg-desktop-po[4506]: segfault at 0 ip 00000000004414e8 sp 00007ffce5466e50 error 4 in .xdg-desktop-portal-hyprland-wrapped[414e8,40b000+7b000] likely on CPU 1 (core 1, socket 0)
[ 5410.152457] Code: 84 a3 fe ff ff 48 8b 44 24 30 48 8d 70 01 e8 cf 9b fc ff e9 90 fe ff ff 66 2e 0f 1f 84 00 00 00 00 00 48 8b 40 08 c6 43 10 00 <48> 8b 38 e8 10 fc ff ff 85 ed 75 54 49 8b 04 24 48 8b 33 48 8b 40
```

**Comment by vaxerski** [comment]
oh wait, nvrm, that's nvidia? Maybe I can blame nvidia hehe :trollface: 

> Last bit of output from sudo dmesg after a crash, not sure if this is what you wanted

No I mean check the dmesg if ther arent any errors logged. Segfaults dont matter, I am talking about something like an e.g. LV2 fault

**Comment by vaxerski** [comment]
nope, not really. What we see is:
- a gl call randomly fails: usually an indication of either gpu memory corruption or an invalid operation
- a gpu reset is performed: driver believes something got really messed up

However:
 - the gl call fails could be a sign of a gpu reset _already_ having happened
 
Generally, a gpu reset means the driver decided that something went so terribly wrong that it needs to tear apart everything and start over.
 
Hyprland, at the moment, _cannot_ recover from that.
 
Problem is, you seem to be the only one affected.

- are you on nvidia?
- do any other environments (kde, sway) exhibit some weird behavior?
- do you live next to a thermonuclear reactor?

**Comment by different-name** [comment]
- Yes Nvidia :(
- I am only using hyprland currently, I'll give kde a go
- Thankfully not

**Comment by vaxerski** [comment]
keep in mind some environments like KDE can survive a gpu reset, but most apps can't. Keep stuff like firefox, or a game open. If stuff suddenly lags and gets closed, it's likely a gpu reset happened.

**Comment by different-name** [comment]
Just got the same issue without screencasting

**Comment by different-name** [comment]
Interestingly, now that I have hardware cursors enabled, I can see my cursor even though everything is frozen

**Comment by different-name** [comment]
Attempted on sway with proprietary drivers, same issue

Going to close this now, thank you so much for all the assistance I really appreciate it, I love the project

Do you think the fault is in the hardware or the drivers?

**Comment by vaxerski** [comment]
likely drivers, welcome to nvidia

**Comment by different-name** [comment]
> you _could_ try windows to make sure it's not hardware tho

I *think* it is hardware or bios config

I have an issue with VR games (not SteamVR itself) freezing on Windows & didn't connect the dots until I saw Sway survive a GPU reset with only games freezing

I have had a undervolt on my CPU with PBO2 for a while, and ran various stability tests, all passing and then took the value down a couple notches to be safe. Had it in my head that this was a software issue, but seems silly now

I've reset my bios settings to default (which I should probably have tried at the beginning) and it seems ok for now, but will need to test more

Hopefully if anyone else comes across this issue they can be less silly
