### ISSUE TITLE
why focus animation not builtin?

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#8365]
### Description

I found a plugin 'hyprfocus', it provide focused window flash or shrink animation, without it ,focused window also flash a bit, but shrink is better, why not builtin focus animation? after 'hyprfocus' enabled, window pop animation is affected. focus is an understandable option in window actions.

**Comment by vaxerski** [comment]
whats wrong with it being a plugin? Hyprland doesn't have to have everything built in
