### ISSUE TITLE
Add support for automatically top-layer-ing the selected floating window when moving the window

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/Hyprland#837]
Currently(at least from what I've observed) hyprland sorts the floating window's layer by the order which it has been launched(or the order which has been turn into a floating window)
I hope that there could be an option to change that to what the title says

**Comment by KyleUltimate** [comment]
oh, I mean moving the window doesn't change focus

**Comment by vaxerski** [comment]
added `bringactivetotop` dispatcher in a7bdfc06ca5747f9a689160c93b8d8c621462757

should solve this issue
