### ISSUE TITLE
Brave won't display save passwords

### ISSUE THREAD

**Issue by EvilBoi123** [hyprwm/Hyprland#8372]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>
Linux archlinux 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
```sh
<Paste the output of the command here>
```

</details>

### Description

The brave browser seems to not output the small tiny window that asks for saving passwords. In kde this is fine. Only occurs at hyprland with brave browser in wayland mode 

### How to reproduce

Just install brave browser and enable it on wayland mode (this is default out of box anyway)

### Crash reports, logs, images, videos

![Screenshot_20241107_085003](https://github.com/user-attachments/assets/56f42fba-38d8-490f-af0c-4da4273693ab)

**Comment by vaxerski** [comment]
get a keyring. This is not a hyprland issue

**Comment by EvilBoi123** [comment]
> get a keyring. This is not a hyprland issue

no, i have tested this with brave on xwayland. it prompts normally.
