### ISSUE TITLE
Improve default groupbar appearance

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/Hyprland#8375]
### Description

We need a good rice
Cheers

**Comment by Aqa-Ib** [comment]
Besides colors and sizes, the font family is very important here. Maybe we should choose a good font to be a dependency of Hyprland?

**Comment by izmyname** [comment]
Second this. I want my groupbars rounded, like the rest of the compositor

**Comment by vaxerski** [comment]
discussions are better
