### ISSUE TITLE
Hyprland crashing on startup

### ISSUE THREAD

**Issue by MightyCoderX** [hyprwm/Hyprland#8379]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.44.0 built from branch main at commit e58e97b0a38b8ccc87a4304c9e4e2b37c9966875  (Nix: build aquamarine and hyprutils in debug when using hyprland-debug).
Date: Thu Nov 7 09:54:52 2024
Tag: v0.44.0-126-ge58e97b0, commits: 5425
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: archlinux
Release: 6.11.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P Integrated Graphics Controller [8086:4626] (rev 0c) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime

```

</details>

### Description

Hyprland briefly flashes then crashes

### How to reproduce

run `Hyprland` from a TTY after updating to latest in AUR

### Crash reports, logs, images, videos

Crash Report: [hyprlandCrashReport8868.txt](https://github.com/user-attachments/files/17675994/hyprlandCrashReport8868.txt)

**Comment by myamusashi** [comment]
Did you update hyprutils and aquamarine too?

**Comment by Honkazel** [comment]
![image](https://github.com/user-attachments/assets/25c5f277-715c-4637-8ade-9b5f3cfc3d55)
![image](https://github.com/user-attachments/assets/785d515a-43f5-4e98-86c0-4d54ea9cd7ae)
I'm confused

**Comment by MightyCoderX** [comment]
I updated my whole system with paru, these are the versions I have installed
```sh
$ pacman -Qi aquamarine
Name            : aquamarine-git
Version         : 0.4.3_r227.ga49bc35-1
Description     : a very light linux rendering backend library
Architecture    : x86_64
URL             : https://github.com/hyprwm/aquamarine
Licenses        : BSD-3-Clause
Groups          : None
Provides        : aquamarine
Depends On      : gcc-libs  glibc  hyprutils-git  hyprwayland-scanner-git  libdisplay-info  libdrm  libglvnd  libinput  mesa
                  opengl-driver  pixman  pugixml  seatd  systemd-libs  wayland  wayland-protocols
Optional Deps   : None
Required By     : hyprland-git
Optional For    : None
Conflicts With  : aquamarine
Replaces        : None
Installed Size  : 1196.41 KiB
Packager        : Unknown Packager
Build Date      : Fri Nov 8 06:41:48 2024
Install Date    : Fri Nov 8 06:42:27 2024
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : None

$ pacman -Qi hyprutils
Name            : hyprutils-git
Version         : 0.2.3.r4.g3ce0cde8-1
Description     : Hyprland utilities library used across the ecosystem
Architecture    : any
URL             : https://github.com/hyprwm/hyprutils
Licenses        : BSD-3-Clause
Groups          : None
Provides        : hyprutils=0.2.3  libhyprutils.so=1-64
Depends On      : pixman
Optional Deps   : None
Required By     : aquamarine-git  hyprcursor-git  hyprland-git  hyprlock-git  hyprpaper  xdg-desktop-portal-hyprland
Optional For    : None
Conflicts With  : hyprutils
Replaces        : None
Installed Size  : 220.11 KiB
Packager        : Unknown Packager
Build Date      : Fri Nov 8 06:41:18 2024
Install Date    : Fri Nov 8 06:41:38 2024
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : None
```

**Comment by MightyCoderX** [comment]
> ![image](https://private-user-images.githubusercontent.com/169346573/384340657-25c5f277-715c-4637-8ade-9b5f3cfc3d55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODg5NzUsIm5iZiI6MTczMTA4ODY3NSwicGF0aCI6Ii8xNjkzNDY1NzMvMzg0MzQwNjU3LTI1YzVmMjc3LTcxNWMtNDYzNy04YWRlLTliNWYzY2ZjM2Q1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjkzYzE3NjE1ZjMxYzNjYjZmNmEwMGMyZmM4MzdkNGQ2NWNjNjE4NzM4ZTY3YzhmM2NmNjU3NmYyMDhmOGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vX4904u7z5MkN-_-4PTQod6X7IjlGgr6sPDHsFVRr2s) ![image](https://private-user-images.githubusercontent.com/169346573/384340721-785d515a-43f5-4e98-86c0-4d54ea9cd7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODg5NzUsIm5iZiI6MTczMTA4ODY3NSwicGF0aCI6Ii8xNjkzNDY1NzMvMzg0MzQwNzIxLTc4NWQ1MTVhLTQzZjUtNGU5OC04NmMwLTRkNTRlYTljZDdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWFmOTY4MTJmODNhNTU0NTM2MDZiZGE0NjMzY2NhMTQ5NTdhN2U0ZTEzMjg2ZjY0OTU2MzNkNTkwZGMzN2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Sl-RhbnQt_QPtjwFrj4EJbbhdbdzBeXWc0kPJgTY4w4) I'm confused

Maybe it's because I don't have it compiled with debug symbols?

**Comment by Aqa-Ib** [comment]
What gpu do you have amd what drivers have you installed?

**Comment by vaxerski** [comment]
cooked stacktrace, but I'd suspect something isnt linked right. Can you rebuild aquamarine then hyprland?

**Comment by MightyCoderX** [comment]
I used paru to compile and install, I'm now updating to latest commit, I'll verify if it works, otherwise I might try to build and install it manually following your suggestion, even tho I remember I didn't have success compiling Hyprland last time I tried.

**Comment by MightyCoderX** [comment]
> What gpu/s does your computer have and what drivers has your system installed?

![image](https://github.com/user-attachments/assets/d4914e75-f1e2-4641-a97e-43868830f051)

this are my specs.

After updating to latest commit hyprland now starts correctly, with only those few errors in the config cause of shadow sub category, which I fixed.

It now seems to work fine, the only problem I notice is this:
![image](https://github.com/user-attachments/assets/f6d08f98-5a77-4fb3-a04e-6608b0ec0f56)

the small white triangles on the corners

**Comment by MightyCoderX** [comment]
![image](https://github.com/user-attachments/assets/f43520ed-6d2b-44af-a650-0e3dc383a3ac)

**Comment by vaxerski** [comment]
closing then
