### ISSUE TITLE
Add group switching animations

### ISSUE THREAD

**Issue by George-1717** [hyprwm/Hyprland#8383]
### Description

I just started using groups and was surprised when there wasn't any animation for switching between applications similar to the one for switching between workspaces. I'm using changegroupactive to switch and would like to have the option for a fancy animation, especially since Hyprland is the compositor with the looks.
Some example binds just in case I'm just doing it wrong and animations do exist:

```hyprland.conf
bind = $mainMod, G, togglegroup, 
bind =  CTRL SHIFT, SPACE, changegroupactive, b
bind =  CTRL , SPACE, changegroupactive, f
```

**Comment by vaxerski** [comment]
#544
