### ISSUE TITLE
Crash on cursor movement

### ISSUE THREAD

**Issue by ferrreo** [hyprwm/Hyprland#8396]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Not sure

### System Info and Version

[sysinfo.txt](https://github.com/user-attachments/files/17688889/sysinfo.txt)

### Description

After some random time but always when moving the cursor Hyprland crashes. 

### How to reproduce

It's pretty random, the only thing in common is mouse is being moved.

### Crash reports, logs, images, videos

[hyprlandCrashReport1654.txt](https://github.com/user-attachments/files/17688724/hyprlandCrashReport1654.txt)

**Comment by ferrreo** [comment]
Disabling hardware cursors seems to prevent this crash, but I also might just be lucky right now as it is intermittent.

**Comment by ferrreo** [comment]
> Needs more testing, I am skeptical the bisected commit is correct

I'll redo the bisect, it is intermittent which makes it rough testing the bisects.

**Comment by vaxerski** [comment]
also you could try and grab the DRM log depending on how long it takes to crash https://wiki.hyprland.org/Crashes-and-Bugs/#debugging-drm-issues

the log will be humongous so you can like attach just the `| tail -n 5000` and it will be fine

**Comment by ferrreo** [comment]
Yeah the bisect was bollocks, edited my post. I can't find a good commit to properly bisect as it is so random, keep getting ones I think are fine then turn out not to be. Hardware cursors turning off also did nothing, again a placebo, crashed with them on and off.

I'll get you a drm log tomorrow even if it takes like 50gb of logfile.

**Comment by ferrreo** [comment]
I am starting to wonder if hyprland has tripped over some amdgpu drm bug here as the "only" thing I've changed is going from Nvidia to AMD gpu and it was not present on Nvidia.

**Comment by vaxerski** [comment]
it could also be a bug in the kernel / drivers, for all we know. I am not hitting this.

**Comment by ferrreo** [comment]
This mysteriously stopped happening, with no config, software or hardware changes, so I'll close for now. If it starts happening again I'll grab the drm log and reopen.
