### ISSUE TITLE
Looking for a xtrlock replacement for Wayland

### ISSUE THREAD

**Issue by linux36524** [hyprwm/Hyprland#8397]
### Description

As the title says, I'm looking for a program similar to xtrlock but that works under a Wayland session.

**Comment by ferrreo** [comment]
https://github.com/hyprwm/hyprlock ?

**Comment by MightyPlaza** [comment]
for the keep rendering part see https://wayland.app/protocols/ext-session-lock-v1#ext_session_lock_v1
which you might be able to get around by scripting grim + https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#image

**Comment by vaxerski** [comment]
this is not a place to ask for that. Forums, discussions, discord...
