### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Heisfer** [hyprwm/Hyprland#840]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

Last thing what I did:
1. yay -S toolbox
2. (laptop monitor froze)
3. Saved Hyprland config (reload)
4. Full crash
[crash.log](https://github.com/hyprwm/Hyprland/files/9767149/crash.log)

**Comment by Heisfer** [comment]
Second monitor was working fine when laptop monitor froze

**Comment by vaxerski** [comment]
where log

**Comment by Heisfer** [comment]
Blue text crash.log

**Comment by Heisfer** [comment]
Hyprland, built from branch main at commit 2ee9fb067526f51c6e13aa399ff540efe20cb540dirty (don't recalc offset on monitor reload offset auto).
flags: (if any)

this is my hyprland version

**Comment by Heisfer** [comment]
[lastSession.log](https://github.com/hyprwm/Hyprland/files/9767219/lastSession.log)
This is last session log, if it helps too.

**Comment by Heisfer** [comment]
I'm going to close this issue because it seems to be driver issue
