### ISSUE TITLE
Help: windowrulev2 for title kind like not working

### ISSUE THREAD

**Issue by thyeun** [hyprwm/Hyprland#8407]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

OS : Arch linux : 6.11.6
Hyprland :  0.44.1-4
Aquamarine : 0.4.4-1

</details>

### Description

For windowrulev2, i have two different command for emacs.
1. ```emacsclient -cn``` and below is the outcome from ```hyprctl client```
```
Window 61e635671a00 -> windowrules.conf - GNU Emacs at thyeun-xps159560:
	mapped: 1
	hidden: 0
	at: 965,10
	size: 945,1029
	workspace: 1 (1)
	floating: 0
	pseudo: 0
	monitor: 0
	class: emacs
	title: windowrules.conf - GNU Emacs at thyeun-xps159560
	initialClass: emacs
	initialTitle: *scratch* - GNU Emacs at thyeun-xps159560
	pid: 92546
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 4
```
2. Make an emacs apps-launcher and below is the outcome from ```hyprctl client```
```
Window 61e6396bb500 -> emacs-run-launcher:
	mapped: 1
	hidden: 0
	at: 192,64
	size: 1536,950
	workspace: 2 (2)
	floating: 1
	pseudo: 0
	monitor: 0
	class: emacs
	title: emacs-run-launcher
	initialClass: emacs
	initialTitle: emacs-run-launcher
	pid: 92546
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 1
```

And my windowrulev2 setting for both as below
```
windowrulev2 = animation popin, class:^(emacs)$ 
windowrulev2 = float, class:^(emacs)$
windowrulev2 = size 80% 88%, class:^(emacs)$
windowrulev2 = center, class:^(emacs)$
windowrulev2 = animation popin, title:^(emacs-run-launcher)
windowrulev2 = float, title:^(emacs-run-launcher)
windowrulev2 = size 50% 18%, title:^(emacs-run-launcher)
windowrulev2 = center, title:^(emacs-run-launcher)
```

My issue are, the floating size from ```emacs-run-launcher``` always follow to ```class:^(emacs)$``` even i use one for ```class``` and one for ```title```.

Anyone know how to make windowrulev2 like that?

### How to reproduce

-

**Comment by Aqa-Ib** [comment]
In this case, don't match the class, match `initialTitle=.*GNU Emacs.*`

**Comment by thyeun** [comment]
@Aqa-Ib i already try all the combination, than only i asked help here,  if i change, my ``emacsclient``` to ```title```, ```initialTitle``` or even ```initialClass```, my ```emacsclient``` wont get floating mode. it only stay to floating mode with ```class```, same goes to ```emacs-run-launcher```. 

i even try out using ```kitty``` to change the class name for ```emacs-run-launcher``` by using ```kitty --class emacs-run-launcher``` but still cant make both working according the floating size i want in ```windowrulev2```.
