### ISSUE TITLE
Workspace change animations affects other monitors when using a multimonitor setup

### ISSUE THREAD

**Issue by herlev** [hyprwm/Hyprland#841]
### Steps to reproduce

- Use a multimonitor setup
- Change to a workspace on the same monitor, such that the workspace slides in from the direction the other monitor is located

### Expected outcome
Changing workspace on one monitor doesn't result in animations on other monitor

### Noted outcome
Changing workspace on one monitor results in animations on other monitor

[hyprland-bug.webm](https://user-images.githubusercontent.com/33587268/195409360-b8eae2c6-c1de-4e49-be0d-1d1b6a14b876.webm)

**Comment by vaxerski** [comment]
aslo check with 170def35d79210f9124cdfd7da563d5d384dcae9

**Comment by herlev** [comment]
Just changed to aur/hyprland-git from 0.15.3beta-1 and the issues seems to be gone
