### ISSUE TITLE
function hooks for plugins are broken

### ISSUE THREAD

**Issue by VirtCode** [hyprwm/Hyprland#8410]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit a8ff3a452c1c445d24bdd9e7e4fcd66c8ef2a147  (core: move to os/Process from hyprutils).
Date: Sat Nov 9 17:14:25 2024
Tag: v0.45.0-2-ga8ff3a45, commits: 5435
built against aquamarine 0.4.4


flags set:
debug


System Information:
System name: Linux
Node name: board
Release: 6.11.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000


GPU information: 


os-release: 

plugins:
  Hypr-DarkWindow by micha4w ver 2.0.0


```

</details>

### Description

Function hooks in plugins don't work since a8ff3a452c1c445d24bdd9e7e4fcd66c8ef2a147. It is probably some bug in the `execAndGet` impl.

When trying to load e.g. dynamic cursors, it fails and prints this in the logs:
```
Unable to search for function "renderSoftwareCursorsFor": no symbols found in binary (is "nm" in path?)
```

This implies that the output from `execAndGet` for the symbols seems to be empty for some reason.

For the record, `nm -D -j /usr/bin/Hyprland | grep renderSoftwareCursorsFor` yields:
```
_ZN15CPointerManager24renderSoftwareCursorsForEN9Hyprutils6Memory14CSharedPointerI8CMonitorEEP8timespecRNS0_4Math7CRegionESt8optionalINS7_8Vector2DEE
```

### How to reproduce

Load a plugin that uses hooks.

**Comment by vaxerski** [comment]
nix?

**Comment by matt1432** [comment]
I'm on nix and I have this issue. Can't tell you if it works on another distro though

**Comment by vaxerski** [comment]
oh shit sec
