### ISSUE TITLE
Preinclude libxcb-errors.so.0 for fedora release based installation

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#842]
When trying to install on fedora you cannot and get error:
```
Hyprland: error while loading shared libraries: libxcb-errors.so.0: cannot open shared object file: No such file or directory
```
I think pre including `libxcb-errors.so.0` would fix this.

**Comment by vaxerski** [comment]
no.
1) I am not a fedora user and thus I cannot build it against fedora libraries.
2) That's not even my issue
3) I think it is in the fedora repos
