### ISSUE TITLE
Add support for customizable splash messages in Hyprland

### ISSUE THREAD

**Issue by L4znet** [hyprwm/Hyprland#8420]
It could be cool to have the option to customize the splash messages that appear in Hyprland, instead of modifying them directly in the source code (specifically in the SPLASHES vector within the .hpp file). Currently, making these changes requires recompiling Hyprland, and they are lost with every update. 

Proposed Solution: 
    Loading splash messages from a separate configuration file, for example: ~/.config/hypr/splash_messages.conf.
    If the file is not present, default messages (the current SPLASHES messages) could be used.
    Each line in this file could represent a different message, allowing users to add, remove, or modify messages freely.

Thank you for considering this feature!

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/issues/4354
