### ISSUE TITLE
function hooks for plugins freeze hyprland

### ISSUE THREAD

**Issue by VirtCode** [hyprwm/Hyprland#8425]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit c10739e6e35c30ef5f273bfe5d219d361a31e226  (core: fixup execAndGet).
Date: Sun Nov 10 22:53:11 2024
Tag: v0.45.0-5-gc10739e6, commits: 5438
built against aquamarine 0.4.4


flags set:
debug


System Information:
System name: Linux
Node name: board
Release: 6.11.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] [8086:3ea0] (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Description

With #8410 fixed, the function hooks don't just fail anymore but outright freeze the compositor. This seems to be caused by the `nm` command not exiting anymore?

I really don't know what it is this time, but it again seems to be something about the `runSync` implementation. It is weird, because commands like `cat /etc/os-release` are being executed just fine, as seen e.g. in the version info printed to the logs. 

For some reason though, `nm` doesn't exit, so hyprland will wait indefinitely until the command exits, which means the compositor freezes. By attaching via ssh I can indeed see the `nm` process still being open and not exiting. Killing `nm` a couple of times un-freezes hyprland.

I am having the same issue on both my systems, and can even reproduce it in nest. I am running up-to-date arch on all these systems. I don't know whether I have missed something, so I'd be glad if someone else could also reproduce this.

### How to reproduce

Try load a plugin using function hooks.

**Comment by vaxerski** [comment]
:(

**Comment by vaxerski** [comment]
just compiled main and it doesnt freeze for me...?

**Comment by vaxerski** [comment]
pipe deadlock

**Comment by vaxerski** [comment]
check now

**Comment by VirtCode** [comment]
seems to work, thanks a lot
