### ISSUE TITLE
limit how narrow a window can become through tiling

### ISSUE THREAD

**Issue by Atemu** [hyprwm/Hyprland#8435]
### Description

Currently, tiling windows further and further results in smaller and smaller windows as expected. At some point they become much too small to be useful which is also expected but what I want to argue here is that the point at which a window loses its usefulness happens much sooner for width than height.

A window that can display only a single sentence of text can still be very useful but rarely does a narrow column of space contain useful information (at least in western scripts).

There therefore should be a variable which defines a minimum tiling width which, when subceded, would force any further splits to be horizontal even if other rules would have ordinarily dictated a vertical split.

This should apply to both the master and dwindle layouts equally.

What's a bit trickier and what I'm undecided on is the unit for this variable. It should not be hardware-pixels as e.g. character width depends on font size and screen scale/DPI. At the minimum, it should scale with the display scaling. Do you know of any good candidates?

**Comment by vaxerski** [comment]
sir #4414

**Comment by Atemu** [comment]
Ah, at first read I thought that issue was about letting windows dictate their maximum width but it's actually the same.

The unit for `maxsize` is pixels right? Is there precedent for non-pixel units where scale applies in Hyprland?

**Comment by vaxerski** [comment]
logical pixels. (scaled pixels, e.g. 1200px on scale 2 is 600 logical px)
