### ISSUE TITLE
Implement opt-in for global tearing, like in X11 Picom.

### ISSUE THREAD

**Issue by ratmarrow** [hyprwm/Hyprland#8439]
### Description

The mechanics of this is strictly out of my wheelhouse, so forgive my naivete.

This is something that personally irks me about Hyprland —alongside other Wayland compositors— and is a peeve that has kept me on i3. 

With how finicky it is to get tearing to work on singular applications (at least to me, the setup is a little... involved), I would prefer to just have the ability to opt-in to global tearing like I can with Picom.

**Comment by vaxerski** [comment]
no

**Comment by ratmarrow** [comment]
> no

Alright, could you please elaborate on  _why?_ In my mind this seems like a very inoffensive request but if there is a philosophical conflict then I would like to know.

**Comment by vaxerski** [comment]
not how wayland works, would require massive restructuring of the code, legacy drm api usage (atomic is still flaky) way more resource usage, rethinking how hyprland is rendered, etc

**Comment by Aqa-Ib** [comment]
this would be the closest to achieving what you want:
`windowrulev2 = immediate, class:.*`
