### ISSUE TITLE
Fulscreen window without sending a fullscreen signal to the app

### ISSUE THREAD

**Issue by Cyliann** [hyprwm/Hyprland#8447]
### Description

Is there a way to fullscreen a window without sending the fullscreen signal to the opened app and 'unfullscreen' without sending the signal?

My usecase is: 
sometimes I have yt fullscreen and I want to see my bar for a second. I used to be able to do it on bspwm, where 'unfullscreening' a window doesn't go out of yt fullscreen, but on Hyprland my yt goes back to being a normal player and I have to fullscreen again (which takes valuable miliseconds).

Thanks in advance

**Comment by vaxerski** [comment]
yes, fullscreenstate
