### ISSUE TITLE
Deep color support (10bit per color)?

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [hyprwm/Hyprland#845]
Hello there, thank you for the amazing WM!

I don't know if it is implemented on WLroots, but does Hyprland support 10bit color? Run a test on my 10bit color supported monitor but looks like it wasn't enabled.

Do you have knowledge regarding this?

**Comment by fufexan** [comment]
Wayland color management is still a WIP. So no, Hyprland does not implement 10bit color depth.

**Comment by vaxerski** [comment]
Wayland has no support for 10 bit color (HDR) yet.

**Comment by vaxerski** [comment]
k. Although I doubt I will ever change the way colors are registered in hyprland to support 10b.

**Comment by VexfulNiko** [comment]
That's a bummer but understandable.
