### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by matt1432** [hyprwm/Hyprland#8455]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info Laptop</summary>

```sh
Hyprland 0.45.0 built from branch  at commit dca75db127fedc58fc85ae0e6e47162e3d5d16f9  ().
Date: 2024-11-09
Tag: , commits: 
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: wim
Release: 6.11.5-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev d1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241109.76612b1"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=wim
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  hyprgrass by horriblename ver v0.8.2
  hyprexpo by Vaxry ver 1.0

======Config-Start======


Config File: /home/matt/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/ii86djqx6kb39qqhzsbwd5hmqf276xzz-dbus-1.14.10/bin/dbus-update-activation-environment --systemd -all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/rgf18nx2j0v3vsp3pm82z1y8d1jmwjvs-hyprgrass-v0.8.2-/lib/libhyprgrass.so
plugin=/nix/store/d1qnqwnqakw3r6wic1dyg4m3nmyb88x9-hyprexpo-0.1/lib/libhyprexpo.so
$mainMod=SUPER
source=/home/matt/.nix/devices/wim/config/hypr/main.conf
animations {
  bezier=easeInOutQuart, 0.77, 0   , 0.175, 1
  bezier=easeInExpo    , 0.95, 0.05, 0.795, 0.035
  animation=fadeLayersIn , 0
  animation=fadeLayersOut, 1, 3000, easeInExpo
  animation=layers       , 1, 4   , easeInOutQuart, slide left
}

cursor {
  hide_on_touch=true
  no_hardware_cursors=false
}

device {
  name=logitech-g502-x
  accel_profile=flat
  sensitivity=0
}

device {
  name=logitech-g502-hero-gaming-mouse
  accel_profile=flat
  sensitivity=0
}

dwindle {
  smart_split=true
  special_scale_factor=0.800000
}

gestures {
  workspace_swipe=true
  workspace_swipe_cancel_ratio=0.150000
  workspace_swipe_fingers=3
  workspace_swipe_touch=false
}

input {
  touchpad {
    disable_while_typing=false
    drag_lock=true
    natural_scroll=true
    tap-and-drag=true
  }
  follow_mouse=true
  kb_layout=ca
  kb_variant=multix
  numlock_by_default=true
  repeat_rate=25
}

misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
  vfr=true
}

plugin {
  hyprexpo {
    bg_col=rgb(111111)
    columns=3
    enable_gesture=true
    gap_size=5
    gesture_distance=300
    gesture_fingers=3
    gesture_positive=true
    workspace_method=center current
  }

  touch_gestures {
    experimental {
      send_cancel=0
    }
    edge_margin=10
    hyprgrass-bind=, edge:u:d, exec, ags request 'open win-applauncher'
    hyprgrass-bind=, edge:d:u, exec, ags request 'osk open'
    hyprgrass-bindm=, longpress:2, movewindow
    long_press_delay=400
    resize_on_border_long_press=true
    sensitivity=4.000000
    workspace_swipe_fingers=3
  }
}

xwayland {
  force_zero_scaling=true
}
bind=,XF86AudioPlay, exec, playerctl play-pause
bind=,XF86AudioStop, exec, playerctl stop
bind=,XF86AudioNext, exec, playerctl next
bind=,XF86AudioPrev, exec, playerctl previous
bind=ALT, tab, hyprexpo:expo, toggle
bind=$mainMod SHIFT, E    , exec, ags toggle win-powermenu
bind=$mainMod      , D    , exec, ags toggle win-applauncher
bind=$mainMod      , V    , exec, ags toggle win-clipboard
bind=              , Print, exec, ags toggle win-screenshot
bind=$mainMod, F,    fullscreen
bind=$mainMod, C,    killactive
bind=$mainMod SHIFT, SPACE,     togglefloating
bind=$mainMod, J,    layoutmsg, togglesplit
bind=$mainMod, left,  movefocus, l
bind=$mainMod, right, movefocus, r
bind=$mainMod, up,    movefocus, u
bind=$mainMod, down,  movefocus, d
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod SHIFT, 1, movetoworkspace, 1
bind=$mainMod SHIFT, 2, movetoworkspace, 2
bind=$mainMod SHIFT, 3, movetoworkspace, 3
bind=$mainMod SHIFT, 4, movetoworkspace, 4
bind=$mainMod SHIFT, 5, movetoworkspace, 5
bind=$mainMod SHIFT, 6, movetoworkspace, 6
bind=$mainMod SHIFT, 7, movetoworkspace, 7
bind=$mainMod SHIFT, 8, movetoworkspace, 8
bind=$mainMod SHIFT, 9, movetoworkspace, 9
bind=$mainMod SHIFT, 0, movetoworkspace, 10
bind=,XF86AudioMute,    exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=,XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind=$mainMod, Print, exec, bash -c "grim -g \"$(slurp)\" - | satty -f -"
bind=$mainMod, L, exec, /nix/store/xkx8y74df6wvwxd2k7mj3aqn0lr31hpa-lock/bin/lock
bind=$mainMod, Q, exec, foot
bind=$mainMod SHIFT, C, exec, wl-color-picker
bind=$mainMod, P, togglespecialworkspace, protonmail
bind=$mainMod, S, togglespecialworkspace, spot
binde=, XF86MonBrightnessUp  , exec, ags request 'Brightness.screen +0.05'
binde=, XF86MonBrightnessDown, exec, ags request 'Brightness.screen -0.05'
binde=, XF86AudioRaiseVolume , exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ & ags request 'popup speaker' &
binde=, XF86AudioLowerVolume , exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- & ags request 'popup speaker' &
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow
bindn=    , Escape   , exec, ags request closeAll
bindr=CAPS, Caps_Lock, exec, ags request fetchCapsState
envd=XCURSOR_THEME, Dracula-cursors
envd=XCURSOR_SIZE, 24
envd=GTK_USE_PORTAL, 1
envd=NIXOS_OZONE_WL, 1
envd=ELECTRON_OZONE_PLATFORM_HINT, auto
envd=XDG_DATA_DIRS, /nix/store/h42324qxqnmmmpjg3skvvmllr1l75cma-gsettings-desktop-schemas-47.1/share/gsettings-schemas/gsettings-desktop-schemas-47.1:/nix/store/3xs715zn5mm3isblz1qxa78zwnlhhjgx-gtk+3-3.24.43/share/gsettings-schemas/gtk+3-3.24.43:$XDG_DATA_DIRS
exec-once=hyprctl setcursor Dracula-hyprcursor 24
exec-once=hyprctl dispatch focusmonitor eDP-1
exec-once=ags
exec-once=sleep 3; ags request 'open win-applauncher'
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=/nix/store/8df6r0103z59zpf67y9j21sk9gklh4qr-polkit-kde-agent-1-5.27.11/libexec/polkit-kde-authentication-agent-1
exec-once=/nix/store/h38d7d6chfbfvd85ng3ijjjwmdm78kr9-kdeconnect-kde-23.08.5/libexec/kdeconnectd
exec-once=kdeconnect-indicator
exec-once=wl-paste --watch cliphist store
exec-once=sleep 3; nextcloud --background
exec-once=sleep 10; tmux new-session -s protonmail-bridge -d 'bash -c protonmail-bridge -c'
exec-once=[workspace special:protonmail silent] sleep 10; proton-mail
exec-once=[workspace special:spot silent] spotify
exec-once=sleep 3; /nix/store/ffvjj8c6q27h2kwygnnha8xp6q53swmx-restartTailscale/bin/restartTailscale
layerrule=noanim, ^(?!win-).*
layerrule=blur, ^(blur-bg.*)
layerrule=ignorealpha 0.19, ^(blur-bg.*)
monitor=desc:Acer Technologies Acer K212HQL T3EAA0014201,1920x1080@60,840x450, 1, transform, 3
monitor=desc:BOE 0x0964,1920x1200@60,0x2920, 1
monitor=desc:Samsung Electric Company C27JG5x HTOM100586,2560x1440@120,1920x120, 1
monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D,2560x1440@120,1920x1560, 1
monitor=desc:Sharp Corporation LC-40LB480U 0x00000001,1680x1050, auto, 1,mirror, eDP-1
windowrule=float,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=size 741 288,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=center,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=size 741 288,^(org.kde.ksshaskpass)$
windowrule=move cursor -370 -144,^(org.kde.ksshaskpass)$
windowrule=tile,^(libreoffice)$
windowrule=float,^(org.gnome.Calculator)$
windowrule=float,^(com.gabm.satty)$
windowrule=size 1000 700,^(com.gabm.satty)$
windowrule=float,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=move cursor -15 -10,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=size 400 581,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=workspace special:protonmail silent,^(Proton Mail)$
windowrule=workspace special:spot silent,^(Spotify)$


Config File: /home/matt/.nix/devices/wim/config/hypr/main.conf: Read Succeeded
# Cosmetic
general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = rgb(411C6C)
    col.inactive_border = rgba(595959aa)
}

decoration {
    rounding = 20

    blur {
        enabled = true
        size = 3
        passes = 1
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = yes

    # Fade out bezier
    bezier = easeInExpo    , 0.95 , 0.05, 0.795, 0.035
    # Fade in bezier
    bezier = easeOutExpo   , 0.19 , 1   , 0.22 , 1

    bezier = easeInOutQuart, 0.77 , 0   , 0.175, 1
    bezier = easeOutQuart  , 0.165, 0.84, 0.44 , 1
    bezier = easeInQuart   , 0.895, 0.03, 0.685, 0.22

    animation = windowsIn  , 1, 4, easeOutQuart, slide
    animation = windowsOut , 1, 4, easeInQuart , slide
    animation = windowsMove, 1, 4, easeOutQuart, slide

    animation = workspaces, 1, 6, easeOutQuart, slide

    animation = fadeIn , 1, 10, easeOutExpo
    animation = fadeOut, 1, 10, easeInExpo
}

======Config-End========


```

</details>

<details> <summary>System/Version info Desktop</summary>
Hyprland 0.45.0 built from branch  at commit dca75db127fedc58fc85ae0e6e47162e3d5d16f9  ().
Date: 2024-11-09
Tag: , commits:
built against aquamarine 0.4.3

flags set:
debug

System Information:
System name: Linux
Node name: binto
Release: 6.11.5-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980

GPU information:
06:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] [10de:2488] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  560.35.03  Fri Aug 16 21:39:15 UTC 2024

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241109.76612b1"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=binto
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

plugins:
  hyprexpo by Vaxry ver 1.0

======Config-Start======

Config File: /home/matt/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/ii86djqx6kb39qqhzsbwd5hmqf276xzz-dbus-1.14.10/bin/dbus-update-activation-environment --systemd -all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/d1qnqwnqakw3r6wic1dyg4m3nmyb88x9-hyprexpo-0.1/lib/libhyprexpo.so
$mainMod=SUPER
source=/home/matt/.nix/devices/binto/config/hypr/main.conf
animations {
  bezier=easeInOutQuart, 0.77, 0   , 0.175, 1
  bezier=easeInExpo    , 0.95, 0.05, 0.795, 0.035
  animation=fadeLayersIn , 0
  animation=fadeLayersOut, 1, 3000, easeInExpo
  animation=layers       , 1, 4   , easeInOutQuart, slide left
}

cursor {
  hide_on_touch=true
  no_hardware_cursors=true
}

device {
  name=logitech-g502-x
  accel_profile=flat
  sensitivity=0
}

device {
  name=logitech-g502-hero-gaming-mouse
  accel_profile=flat
  sensitivity=0
}

dwindle {
  smart_split=true
  special_scale_factor=0.800000
}

input {
  touchpad {
    disable_while_typing=false
    drag_lock=true
    natural_scroll=true
    tap-and-drag=true
  }
  follow_mouse=true
  kb_layout=ca
  kb_variant=multix
  numlock_by_default=true
  repeat_rate=25
}

misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
  vfr=true
}

plugin {
  hyprexpo {
    bg_col=rgb(111111)
    columns=3
    enable_gesture=true
    gap_size=5
    gesture_distance=300
    gesture_fingers=3
    gesture_positive=true
    workspace_method=center current
  }
}

xwayland {
  force_zero_scaling=true
}
bind=,XF86AudioPlay, exec, playerctl play-pause
bind=,XF86AudioStop, exec, playerctl stop
bind=,XF86AudioNext, exec, playerctl next
bind=,XF86AudioPrev, exec, playerctl previous
bind=ALT, tab, hyprexpo:expo, toggle
bind=$mainMod SHIFT, E    , exec, ags toggle win-powermenu
bind=$mainMod      , D    , exec, ags toggle win-applauncher
bind=$mainMod      , V    , exec, ags toggle win-clipboard
bind=              , Print, exec, ags toggle win-screenshot
bind=,F8, exec, ags request 'save-replay'
bind=$mainMod, F,    fullscreen
bind=$mainMod, C,    killactive
bind=$mainMod SHIFT, SPACE,     togglefloating
bind=$mainMod, J,    layoutmsg, togglesplit
bind=$mainMod, left,  movefocus, l
bind=$mainMod, right, movefocus, r
bind=$mainMod, up,    movefocus, u
bind=$mainMod, down,  movefocus, d
bind=$mainMod, 1, workspace, 1
bind=$mainMod, 2, workspace, 2
bind=$mainMod, 3, workspace, 3
bind=$mainMod, 4, workspace, 4
bind=$mainMod, 5, workspace, 5
bind=$mainMod, 6, workspace, 6
bind=$mainMod, 7, workspace, 7
bind=$mainMod, 8, workspace, 8
bind=$mainMod, 9, workspace, 9
bind=$mainMod, 0, workspace, 10
bind=$mainMod SHIFT, 1, movetoworkspace, 1
bind=$mainMod SHIFT, 2, movetoworkspace, 2
bind=$mainMod SHIFT, 3, movetoworkspace, 3
bind=$mainMod SHIFT, 4, movetoworkspace, 4
bind=$mainMod SHIFT, 5, movetoworkspace, 5
bind=$mainMod SHIFT, 6, movetoworkspace, 6
bind=$mainMod SHIFT, 7, movetoworkspace, 7
bind=$mainMod SHIFT, 8, movetoworkspace, 8
bind=$mainMod SHIFT, 9, movetoworkspace, 9
bind=$mainMod SHIFT, 0, movetoworkspace, 10
bind=,XF86AudioMute,    exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=,XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind=$mainMod, Print, exec, bash -c "grim -g \"$(slurp)\" - | satty -f -"
bind=$mainMod, L, exec, /nix/store/xkx8y74df6wvwxd2k7mj3aqn0lr31hpa-lock/bin/lock
bind=$mainMod, Q, exec, foot
bind=$mainMod SHIFT, C, exec, wl-color-picker
bind=$mainMod, P, togglespecialworkspace, protonmail
bind=$mainMod, S, togglespecialworkspace, spot
binde=, XF86MonBrightnessUp  , exec, ags request 'Brightness.screen +0.05'
binde=, XF86MonBrightnessDown, exec, ags request 'Brightness.screen -0.05'
binde=, XF86AudioRaiseVolume , exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ & ags request 'popup speaker' &
binde=, XF86AudioLowerVolume , exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- & ags request 'popup speaker' &
bindm=$mainMod, mouse:272, movewindow
bindm=$mainMod, mouse:273, resizewindow
bindn=    , Escape   , exec, ags request closeAll
bindr=CAPS, Caps_Lock, exec, ags request fetchCapsState
envd=XCURSOR_THEME, Dracula-cursors
envd=XCURSOR_SIZE, 24
envd=GTK_USE_PORTAL, 1
envd=NIXOS_OZONE_WL, 1
envd=ELECTRON_OZONE_PLATFORM_HINT, auto
envd=XDG_DATA_DIRS, /nix/store/h42324qxqnmmmpjg3skvvmllr1l75cma-gsettings-desktop-schemas-47.1/share/gsettings-schemas/gsettings-desktop-schemas-47.1:/nix/store/3xs715zn5mm3isblz1qxa78zwnlhhjgx-gtk+3-3.24.43/share/gsettings-schemas/gtk+3-3.24.43:$XDG_DATA_DIRS
envd=LIBVA_DRIVER_NAME, nvidia
envd=XDG_SESSION_TYPE, wayland
envd=GBM_BACKEND, nvidia-drm
envd=__GLX_VENDOR_LIBRARY_NAME, nvidia
exec-once=hyprctl setcursor Dracula-hyprcursor 24
exec-once=hyprctl dispatch focusmonitor desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D
exec-once=ags
exec-once=sleep 3; ags request 'open win-applauncher'
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=/nix/store/8df6r0103z59zpf67y9j21sk9gklh4qr-polkit-kde-agent-1-5.27.11/libexec/polkit-kde-authentication-agent-1
exec-once=/nix/store/h38d7d6chfbfvd85ng3ijjjwmdm78kr9-kdeconnect-kde-23.08.5/libexec/kdeconnectd
exec-once=kdeconnect-indicator
exec-once=wl-paste --watch cliphist store
exec-once=sleep 3; nextcloud --background
exec-once=sleep 10; tmux new-session -s protonmail-bridge -d 'bash -c protonmail-bridge -c'
exec-once=[workspace special:protonmail silent] sleep 10; proton-mail
exec-once=[workspace special:spot silent] spotify
exec-once=sleep 3; /nix/store/ffvjj8c6q27h2kwygnnha8xp6q53swmx-restartTailscale/bin/restartTailscale
layerrule=noanim, ^(?!win-).*
layerrule=blur, ^(blur-bg.*)
layerrule=ignorealpha 0.19, ^(blur-bg.*)
monitor=desc:Acer Technologies Acer K212HQL T3EAA0014201,1920x1080@60,840x450, 1, transform, 3
monitor=desc:BOE 0x0964,1920x1200@60,0x2920, 1
monitor=desc:Samsung Electric Company C27JG5x HTOM100586,2560x1440@120,1920x120, 1
monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D,2560x1440@120,1920x1560, 1
monitor=desc:Sharp Corporation LC-40LB480U 0x00000001,1680x1050, auto, 1,mirror, desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC 0x00000B1D
windowrule=float,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=size 741 288,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=center,^(org.kde.polkit-kde-authentication-agent-1)$
windowrule=size 741 288,^(org.kde.ksshaskpass)$
windowrule=move cursor -370 -144,^(org.kde.ksshaskpass)$
windowrule=tile,^(libreoffice)$
windowrule=float,^(org.gnome.Calculator)$
windowrule=float,^(com.gabm.satty)$
windowrule=size 1000 700,^(com.gabm.satty)$
windowrule=float,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=move cursor -15 -10,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=size 400 581,^(com.nextcloud.desktopclient.nextcloud)$
windowrule=workspace special:protonmail silent,^(Proton Mail)$
windowrule=workspace special:spot silent,^(Spotify)$

Config File: /home/matt/.nix/devices/binto/config/hypr/main.conf: Read Succeeded
# Cosmetic
general {
    gaps_in = 10
    gaps_out = 20
    border_size = 0
}

======Config-End========
</details>

### Description

I get a black screen whenever I launch my desktops.

Any commit from c10739e6e35c30ef5f273bfe5d219d361a31e226 gives the black screen and I can't even change TTY.

This affects both my AMD laptop and NVIDIA desktop. Both configs are in the system info but they share most of the same things.

Last working commit was 9e628067fc54851dc9138c2882abb21f72c5a5a6 but that one is affected by https://github.com/hyprwm/Hyprland/issues/8410 so right now I'm pinning Hyprland to dca75db127fedc58fc85ae0e6e47162e3d5d16f9.

The issue only happens with those specific configs. I also use Hyprland with Greetd and that works.

### How to reproduce

The issue probably comes from `execAndGet`, so I'm guessing maybe one of the `exec`s in my config is causing this?

### Crash reports, logs, images, videos

No crash logs

**Comment by VirtCode** [comment]
what hyprutils commit are you on? sounds like #8425 to me

**Comment by clotodex** [comment]
on newest master nix build (flake) it is also broken

**Comment by dev-null-undefined** [comment]
Have you tried without plugins? For me adding plugins results in similar error (black screen)

**Comment by clotodex** [comment]
yeah, see #8425 - the reason is in the plugin system; the bug is already fixed
a "simple" flake lock update would fix it likely on main

**Comment by dev-null-undefined** [comment]
Was about to say that :D , or you can override the flake input your self

**Comment by dev-null-undefined** [comment]
For now this worked as fix, before the flake.lock gets updated here
```
    hyprutils = {
      url = "github:hyprwm/hyprutils";
      inputs = {
        nixpkgs.follows = "hyprland/nixpkgs";
        systems.follows = "hyprland/systems";
      };
    };
    hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/Hyprland";
      submodules = true;
      inputs = {
        nixpkgs.follows = "nixpkgs";
        hyprutils.follows = "hyprutils";
      };
    };
```

**Comment by hambosto** [comment]
yeah the plugin causing black screen, strange. disabling will fixed this issue, for now.

**Comment by matt1432** [comment]
> For now this worked as fix, before the flake.lock gets updated here
> 
> ```
>     hyprutils = {
>       url = "github:hyprwm/hyprutils";
>       inputs = {
>         nixpkgs.follows = "hyprland/nixpkgs";
>         systems.follows = "hyprland/systems";
>       };
>     };
>     hyprland = {
>       type = "git";
>       url = "https://github.com/hyprwm/Hyprland";
>       submodules = true;
>       inputs = {
>         nixpkgs.follows = "nixpkgs";
>         hyprutils.follows = "hyprutils";
>       };
>     };
> ```

you don't need the submodules anymore for Hyprland btw

**Comment by matt1432** [comment]
I can confirm that the issue is fixed with latest hyprutils though. Guess I'll keep that in my inputs from now on

@fufexan

**Comment by matt1432** [comment]
yup, thanks
