### ISSUE TITLE
Can't run Hyprland due to seatd not running

### ISSUE THREAD

**Issue by HyperSilver69** [hyprwm/Hyprland#846]
`[libseat] [libseat/backend/seatd.c:66] could not connect to socket /run/seatd.sock: Permission denied`
`[libseat] [libseat/.c:76] backend 'seatd' failed to open seat, skipping`
when running Hyprland
when running sudo Hyprland
`terminate called after throwing an instance of 'std::runtime_error`
     `what(): XDG_RUNTIME_DIR is not set!`
     `aborted`
This is a clear arch install btw, just installed using the archinstall script and then copied the git and did `makepkg -si`

**Comment by vaxerski** [comment]
not a hyprland issue. If you use a clear arch install, you should learn how to use arch first.

**Comment by HyperSilver69** [comment]
> 

wow wow wow idk what you think you're saying about me being new because I've been using arch for ~2 months now and The error is most certainly Hyprland related, otherwise I wouldn't be getting it. Hyprland is the thing using seatd (which configured properly)

**Comment by vaxerski** [comment]
> which configured properly

> `[libseat] [libseat/backend/seatd.c:66] could not connect to socket /run/seatd.sock: Permission denied`

yeah right.

Provide a coredump then from running Hyprland without sudo (thou shalt not sudo hyprland)

**Comment by HyperSilver69** [comment]
Issue was Hyprland related, reinstalled and it works fine now.
