### ISSUE TITLE
Opening an app within special workspace glitches it out

### ISSUE THREAD

**Issue by atimofeev** [hyprwm/Hyprland#8465]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

Using today's latest Nix flake.
```sh
❯ hyprctl systeminfo 
Hyprland, built from branch  at commit  dirty ().
Date: 
Tag: , commits: 

flags: (if any)


System Information:
System name: Linux
Node name: milaptop
Release: 6.9.3-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240606.9b5328b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

</details>

### Description

When I go to special workspace and launch some app with rule to open it in special workspace, this will glitch it out, making the workspace to completely disappear. You have to cycle togglespecialworkspace and upon return workspace appears normally with the app you've launched.
This also reproduces if you have telegram opened in special workspace and click on any media, which opens in a new window.

### How to reproduce

- Add this, or similar config:
```
bind = SUPER SHIFT, S, exec, kitty -o term=xterm-kitty --class spotify_player -e spotify_player
windowrulev2 = workspace special, class:^(spotify_player)$
```
- Go to special workspace (togglespecialworkspace)
- Execute keybind to launch the app
- Special workspace visually completely disappears, but, apparently, you're still in there
- Cycle togglespecialworkspace to return to special and finally see the launched app.

OR

- Move Telegram to special workspace
- Click on any media, which opens in separate window

### Crash reports, logs, images, videos

[hyprland.conf.txt](https://github.com/user-attachments/files/17738479/hyprland.conf.txt)

**Comment by vaxerski** [comment]
`workspace special silent`?

**Comment by atimofeev** [comment]
Thanks! `silent` finally made it function properly, when I call the app from the `special` itself.
But now, when I launch apps from other workspaces, they won't open `special` workspace and launch silently (duh).

Looks like now I have to implement some conditional logic to use `silent` or not, depending on current workspace. 

Overall, this is a rather strange behavior, unique to `special` workspaces. I can't reproduce anything like this with regular workspaces, as I'm able to launch apps from anywhere to any destination.

**Comment by vaxerski** [comment]
nah, this is a bug, I just offered a quick solution

**Comment by vaxerski** [comment]
cant repro on git

**Comment by atimofeev** [comment]
No longer reproducible for me, too. Must be something in scope of upgrade to 24.11 NixOS. My hyprland experience overall is way more smooth and stable now. Probably something was messed up in my previous config or previous OS release.

Let's close this!
