### ISSUE TITLE
[Bug]: Hyprland crashes on startup in Fedora 41

### ISSUE THREAD

**Issue by dani0221** [hyprwm/Hyprland#8466]
## System information

- Operating system: Fedora 41
- Hyprland version: [ aquamarine 0.4.4]
- Desktop environment: [Gnome v47]

## 
steps to reproduce
1. Start Hyprland.
2. After starting, the program does not work
3. When trying to start the program manually, it crashes immediately and displays an error message.

## Expected behavior
Hyprland should start correctly and display the desktop environment without errors
## Actual behavior
Hyprland crashes during startup and displays an error message related to 'wl_registry. The program terminates with an IOT instruction error.
Hyprland has crashed :(
## error output (wl_registry#2: error 0: invalid version for global wl_seat (15): have 8, wanted 9
terminate called after throwing an instance of 'std::runtime_error'
  what():  CBackend::create() failed!
Hyprland has crashed :( Consult the crash report at /home/angel-dev/.cache/hyprland/hyprlandCrashReport11565.txt for more information.
[1]    11565 IOT instruction (core dumped)  Hyprland)

## files of crashed
[hyprlandCrashReport11565.txt](https://github.com/user-attachments/files/17739340/hyprlandCrashReport11565.txt)

**Comment by vaxerski** [comment]
> Desktop environment: [Gnome v47]

are you launching it _from_ gnome? That's not possible due to gnome having some protocol extensions too outdated.

Please launch it from a tty

**Comment by dani0221** [comment]
I already fixed it
