### ISSUE TITLE
Wrong path in hyprland-session.service

### ISSUE THREAD

**Issue by ansdim1** [hyprwm/Hyprland#8475]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```
Hyprland 0.45.0 built from branch master at commit d3ecc149fee2b5382df8f4fd9b6dcb594f531188 dirty ().
Date: Wed Oct 4 09:14:57 2023
Tag: v2.1.10, commits: 2692
built against aquamarine 0.4.5

flags set:
legacyrenderer
debug

System Information:
System name: Linux
Node name: b570
Release: 6.11.6-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:35 +0000

GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0106] (rev 09) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:
  Hyprspace by KZdkm ver 0.1
  split-monitor-workspaces by Duckonaut ver 1.2.0

======Config-Start======

Config File: /home/dim/.config/hypr/hyprland.conf: Read Succeeded
</details>

### Description

In ExecStart and ExecStop wrong path:

ExecStart=/usr//usr/bin/Hyprland
ExecStop=/usr//usr/bin/hyprctl dispatch exit

### How to reproduce

Install Hyprland 0.45.0 . and check /usr/lib/systemd/user/hyprland-session.service

### Crash reports, logs, images, videos

[Unit]
Description=Hyprland - Tiling compositor with the looks
Documentation=man:Hyprland(1)
BindsTo=graphical-session.target
Before=graphical-session.target
Wants=xdg-desktop-autostart.target
Wants=graphical-session-pre.target
After=graphical-session-pre.target

[Service]
Type=notify
ExecStart=**/usr/**/usr/bin/Hyprland
ExecStop=**/usr/**/usr/bin/hyprctl dispatch exit
ExecStopPost=systemctl --user unset-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP
Restart=on-failure
Slice=session.slice

**Comment by izmyname** [comment]
Usage of hyprland-session.service is discouraged and it won't be present in future versions. Use [uwsm](https://github.com/Vladimir-csp/uwsm) instead. See https://github.com/hyprwm/Hyprland/issues/8424#issuecomment-2468421611
