### ISSUE TITLE
`primary-selection-unstable-v1` not accessible in flatpak after `v0.45.0`

### ISSUE THREAD

**Issue by zefr0x** [hyprwm/Hyprland#8479]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit da86aac0f5c5c3604351961b901f62cdf7186a10  (security-context: implement protocol).
Date: Sun Oct 6 16:07:07 2024
Tag: v0.44.0-1-gda86aac0, commits: 5300
built against aquamarine 0.4.5


flags: (if any)


System Information:
System name: Linux
Node name: mypc
Release: 6.11.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 17:57:56 +0000


GPU information: 
07:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] [10de:1380] (rev a2) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.57.01  Thu Oct 10 12:29:05 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/<USERNAME>/test.conf: Read Succeeded
monitor=,preferred,auto,1

exec-once = flatpak run dev.serebit.Waycheck
exec-once = dash -c "hyprctl systeminfo -c > sysinfo"

======Config-End========

```

</details>

### Description

`primary-selection-unstable-v1` protocol not accessible in flatpak sandboxed applications after https://github.com/hyprwm/Hyprland/commit/da86aac0f5c5c3604351961b901f62cdf7186a10 due to `security-context-v1` Hyprland's implementation.

I didn't find any issue on KWin, sway or niri which also have `security-context-v1` implemented, so it is less possible that it is a flatpak issue?

### How to reproduce

Use the middle-click copy from or to a flatpak sandboxed application.

Or use Waycheck (flatpak version) to list available wayland protocols.

**Comment by vaxerski** [comment]
different compositors have different black/whitelists :)
