### ISSUE TITLE
Renderer error

### ISSUE THREAD

**Issue by HyperSilver69** [hyprwm/Hyprland#848]
![afbeelding](https://user-images.githubusercontent.com/91153148/195680263-d9d27224-04e6-4e59-be1c-c7a50c26d497.png)
When running `Hyprland` command.
Sorry if wrong place to ask, could not find anything else.

**Comment by brodi1** [comment]
@HyperSilver69 Could you provide more information? like for e.g. version, distro, gpu.....

**Comment by HyperSilver69** [comment]
> @HyperSilver69 Could you provide more information? like for e.g. version, distro, gpu.....

I'm sorry, I'm on arch version (latest)
Hyprland version (latest)
Gpu: whatever virtualbox uses

I tried using polkit instead of seatd and got this:
![afbeelding](https://user-images.githubusercontent.com/91153148/195684685-069a170a-463d-4427-a2b7-6dbcae2d3d42.png)

**Comment by HyperSilver69** [comment]
> > @HyperSilver69 Could you provide more information? like for e.g. version, distro, gpu.....
> 
> I'm sorry, I'm on arch version (latest) Hyprland version (latest) Gpu: whatever virtualbox uses
> 
> I tried using polkit instead of seatd and got this: ![afbeelding](https://user-images.githubusercontent.com/91153148/195684685-069a170a-463d-4427-a2b7-6dbcae2d3d42.png)

@brodi1 since it didnt seem to pinng you

**Comment by HyperSilver69** [comment]
Didnt mean to close

**Comment by brodi1** [comment]
@HyperSilver69 did you install it from the AUR? if yes are you using the -git version?

**Comment by HyperSilver69** [comment]
> @HyperSilver69 did you install it from the AUR? if yes are you using the -git version?

I am not using the git version, am i supposed to be using that?

**Comment by brodi1** [comment]
@HyperSilver69 nope I'm just asking so I know which exact version you are using 😁

**Comment by HyperSilver69** [comment]
> @HyperSilver69 nope I'm just asking so I know which exact version you are using 😁

It just keeps giving me the "eg1Initialize" error and I can't find anything about it online.

**Comment by brodi1** [comment]
@HyperSilver69 I think this is probably more and virtualbox issue.....have you checked your virtualbox settings? and do you have the additions installed too?

**Comment by HyperSilver69** [comment]
> @HyperSilver69 I think this is probably more and virtualbox issue.....have you checked your virtualbox settings? and do you have the additions installed too?

I don't have any additions installed, My virtualbox settings are pretty normal (set as closely to a real machine as possible) and I'm using EFI not bios.

**Comment by brodi1** [comment]
@HyperSilver69 have you tried if another wlroots wm like sway starts?

**Comment by HyperSilver69** [comment]
> @HyperSilver69 have you tried if another wlroots wm like sway starts?

I have not, Let me attempt Sway.

**Comment by HyperSilver69** [comment]
> @HyperSilver69 have you tried if another wlroots wm like sway starts?

When running `sway --unsupported-gpu` (Thought that'd be the safest to run since Idk if Virtualbox is supported)
My system just freezes like it's trying to run something but in ~1 minute nothing has happened.

**Comment by HyperSilver69** [comment]
> > @HyperSilver69 have you tried if another wlroots wm like sway starts?
> 
> When running `sway --unsupported-gpu` (Thought that'd be the safest to run since Idk if Virtualbox is supported) My system just freezes like it's trying to run something but in ~1 minute nothing has happened.

While later, still frozen. This doesnt seem to be going anywhere

**Comment by HyperSilver69** [comment]
> First, test Hyprland on a real machine, not a VM.
> 
> Second, you said you didn't install the guest additions. Why? That might be part of your issue.

I don't have official hardware to test it on as of right now, I'm sorry.

I can't figure out how to install the guest additions. All I can find is how to install virtualbox on Arch.

**Comment by pinkcreeper100** [comment]
@HyperSilver69 wdym by
> official hardware

**Comment by HyperSilver69** [comment]
> @HyperSilver69 wdym by
> 
> > official hardware

Real machine

**Comment by HyperSilver69** [comment]
> 

Apologies, but where do I put "WLR_RENDERER_ALLOW_SOFTWARE=1"?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/195704913-8804dd4f-75ed-49b6-a080-4785f63806f8.png)

**Comment by HyperSilver69** [comment]
![afbeelding](https://user-images.githubusercontent.com/91153148/195705705-bd3013b9-26d5-408d-a5e6-1924f3f61c37.png)
Did not do anything.
I'm really sorry for all this. I'm just trying to get this to work.
