### ISSUE TITLE
CANT LAUNCH HYPRLAND AT ALL.

### ISSUE THREAD

**Issue by fantabaridi1** [hyprwm/Hyprland#8490]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

yprland 0.45.0 built from branch  at commit  dirty ().
Date: 
Tag: , commits: 
built against aquamarine 0.4.3

flags set:
debug

System Information:
System name: Linux
Node name: cachyos-x8664
Release: 6.11.7-1-cachyos
Version: #1 SMP PREEMPT_DYNAMIC Sat, 09 Nov 2024 08:37:52 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

os-release: NAME="CachyOS Linux"
PRETTY_NAME="CachyOS"
ID=cachyos
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://cachyos.org/"
DOCUMENTATION_URL="https://wiki.cachyos.org/"
SUPPORT_URL="https://discuss.cachyos.org/"
BUG_REPORT_URL="https://github.com/cachyos"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=cachyos

### Description

Hyprland crashes on startup due to a failure in initializing the backend, caused by libseat not being able to open a seat (Permission denied) and fallback backends also failing. Additionally, there is a conflict with session management, likely from another active compositor or session.

### How to reproduce

dont understand.

### Crash reports, logs, images, videos

 Hyprland Crash Report
--------------------------------------------
I hope you didn't have any unsaved progress.

Hyprland received signal 6(ABRT)
Version: 
Tag: 
Date: 
Flags:

System info:
	System name: Linux
	Node name: cachyos-x8664
	Release: 6.11.7-1-cachyos
	Version: #1 SMP PREEMPT_DYNAMIC Sat, 09 Nov 2024 08:37:52 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

os-release:
	NAME="CachyOS Linux"
	PRETTY_NAME="CachyOS"
	ID=cachyos
	ID_LIKE=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://cachyos.org/"
	DOCUMENTATION_URL="https://wiki.cachyos.org/"
	SUPPORT_URL="https://discuss.cachyos.org/"
	BUG_REPORT_URL="https://github.com/cachyos"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=cachyos
Backtrace:
	# | Hyprland(_Z12getBacktracev+0x61) [0x5b17ac477d71]
		getBacktrace()
		??:?
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xb80) [0x5b17ac3f7260]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x71) [0x5b17ac36f491]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x7ace8604c1d0]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x963f4) [0x7ace860a53f4]
		??
		??:0
	#5 | /usr/lib/libc.so.6(gsignal+0x20) [0x7ace8604c120]
		??
		??:0
	#6 | /usr/lib/libc.so.6(abort+0xdf) [0x7ace860334c3]
		??
		??:0
	#7 | /usr/lib/libstdc++.so.6(+0x97b2c) [0x7ace86297b2c]
		??
		??:0
	#8 | /usr/lib/libstdc++.so.6(+0xadf3a) [0x7ace862adf3a]
		??
		??:0
	#9 | /usr/lib/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7ace8629752a]
		??
		??:0
	#1 | /usr/lib/libstdc++.so.6(+0xae1f6) [0x7ace862ae1f6]
		??
		??:0
	#11 | Hyprland(+0xcbdb0) [0x5b17ac2b1db0]
		??
		??:0
	#12 | Hyprland(_ZN11CCompositor10initServerENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x82d) [0x5b17ac375ddd]
		CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
		??:?
	#13 | Hyprland(main+0xb15) [0x5b17ac32a035]
		main
		??:?
	#14 | /usr/lib/libc.so.6(+0x25e08) [0x7ace86034e08]
		??
		??:0
	#15 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7ace86034ecc]
		??
		??:0
	#16 | Hyprland(_start+0x25) [0x5b17ac36b6d5]
		_start
		??:?

Log tail:
[LOG] System name: Linux
[LOG] Node name: cachyos-x8664
[LOG] Release: 6.11.7-1-cachyos
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Sat, 09 Nov 2024 08:37:52 +0000

[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

[LOG] os-release:
NAME="CachyOS Linux"
PRETTY_NAME="CachyOS"
ID=cachyos
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://cachyos.org/"
DOCUMENTATION_URL="https://wiki.cachyos.org/"
SUPPORT_URL="https://discuss.cachyos.org/"
BUG_REPORT_URL="https://github.com/cachyos"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=cachyos

[LOG] ========================

[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] 
Current splash: Alors on danse

[LOG] Old rlimit: soft -> 1024, hard -> 1048576
[LOG] New rlimit: soft -> 1048576, hard -> 1048576
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 43.53µs. Estimated average calc time: 0.10µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 26.71µs. Estimated average calc time: 0.05µs.
[LOG] Using config: /home/fantabaridi/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 35.26µs. Estimated average calc time: 0.05µs.
[LOG] Using config: /home/fantabaridi/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 33.73µs. Estimated average calc time: 0.12µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 32.17µs. Estimated average calc time: 0.05µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.96µs. Estimated average calc time: 0.05µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.92µs. Estimated average calc time: 0.05µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.92µs. Estimated average calc time: 0.05µs.
[LOG] Disabling stdout logs! Check the log for further logs.
[LOG] Creating the PointerManager!
[LOG] Creating the EventManager!
[LOG] [AQ] Creating an Aquamarine backend!
[ERR] [AQ] [libseat] [libseat/backend/seatd.c:66] Could not connect to socket /run/seatd.sock: Permission denied
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[ERR] [AQ] [libseat] [libseat/backend/logind.c:302] Could not take control of session: Device or resource busy
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'logind' failed to open seat, skipping
[ERR] [AQ] [libseat] [libseat/libseat.c:79] No backend was able to open a seat
[ERR] [AQ] libseat: failed to open a seat
[ERR] [AQ] Failed to open a session
[ERR] [AQ] DRM Backend failed
[LOG] [AQ] Starting the Aquamarine backend!
[LOG] [AQ] Starting the Wayland backend!
[ERR] [AQ] Wayland backend cannot start: wl_display_connect failed (is a wayland compositor running?)
[ERR] [AQ] Requested backend (wayland) could not start, enabling fallbacks
[ERR] [AQ] Implementation wayland failed, erasing.
[CRITICAL] m_pAqBackend couldn't start! This usually means aquamarine could not find a GPU or encountered some issues. Make sure you're running either on a tty or on a Wayland session, NOT an X11 one.
[CRITICAL] Critical error thrown: CBackend::create() failed!

**Comment by myamusashi** [comment]
https://bbs.archlinux.org/viewtopic.php?id=290280

**Comment by vaxerski** [comment]
read the wiki
