### ISSUE TITLE
something wrong 

### ISSUE THREAD

**Issue by axax-loll** [hyprwm/Hyprland#8499]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch  at commit bb160cfe377da2d2b2e4431a3399fa60114f3911  ().
Date: 2024-11-12
Tag: , commits: 
built against aquamarine 0.4.3


flags set:
debug


System Information:
System name: Linux
Node name: jetpure
Release: 6.11.5-zen1
Version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980


GPU information: 
2b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241109.76612b1"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=jetpure
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  unknown: not runtime
```

</details>

### Description

When i launch hyprland windows starts glitching

### How to reproduce

I dont know, will its work but my flake https://git.sr.ht/~azikx/ultima

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/177ad6db-2dc8-414c-8632-0d0448150dae

**Comment by vaxerski** [comment]
to me this looks like drivers/card dying

**Comment by MCPO-Spartan-117** [comment]
Can't replicate with a 6700XT on Hyprland commit 1ba050d603dca644aca48872f62388d794c030b9 and Aquamarine b31a6a4da8199ae3489057db7d36069a70749a56.

**Comment by axax-loll** [comment]
im stupid lol, fixed that by adding
`(modulesPath + "/installer/scan/not-detected.nix")`
to imports
