### ISSUE TITLE
toggle dispatcher

### ISSUE THREAD

**Issue by ralencode** [hyprwm/Hyprland#8500]
### Description

same as exec, executes a command. but, it remembers the status (0 or 1), and switches statuses when issued. and it accepts two commands. for example:
bind = $mainMod, T, toggle, hyprctl keyword decoration:blur:enabled true, hyprctl keyword decoration:blur:enabled false
so, it will be possible to set a shortcut for toggling blur with a single config line (blur is just an example, there can be more wonderful applications)

**Comment by vaxerski** [comment]
you can script this yourself
