### ISSUE TITLE
Can we use screen shaders for upscaling Full-screen Apps

### ISSUE THREAD

**Issue by lalishansh** [hyprwm/Hyprland#8502]
### Description

Can we use upscale filters in Apps (especially Fullscreen apps).

There's an all purpose window upscaler [Magpie](https://github.com/Blinue/Magpie) for Windows 10/11.
I use it extensively for old games and visual novels.

NOTE: I'll be creating my own upscale filters for the same (wrapper around [Anime4k](https://github.com/bloc97/Anime4K/) possibly), screen-shaders look simple enough, i'm asking for viability of this as i'm noob to hyprland code-base and window managers, scaling inside them in general.

**Comment by vaxerski** [comment]
you can yes
