### ISSUE TITLE
`float_switch_override_focus` should have higher priority than `follow_mouse`

### ISSUE THREAD

**Issue by spikespaz** [hyprwm/Hyprland#851]
`input:float_switch_override_focus` should have higher priority than `input:follow_mouse`

For example, I have
```c
input {
    follow_mouse = 2
    float_switch_override_focus = false
}
```

When `follow_mouse` is not `1`, the option `float_switch_override_focus` is useless because it respects the former. Perhaps the latter needs three modes, `0: false`, `1: true`, and `3: ignore`?

**Comment by vaxerski** [comment]
wot, iirc it did work...

**Comment by vaxerski** [comment]
works for me. The behavior of `float_switch_override_focus` is that if disabled, hovering with your mouse over a window that has a different float status will NOT keyboard focus it on `follow_mouse` != 1

**Comment by spikespaz** [comment]
Reversing this in my head: follow mouse != 1, true, override focus = true, should keyboard focus. If that sounds correct, the behavior I expect and am wanting to read, then can you think of any other options that might interfere with the same internals?

**Comment by spikespaz** [comment]
Probably not, but just in case you do want a looksie: https://termbin.com/kdso

**Comment by vaxerski** [comment]
whats the issue

**Comment by spikespaz** [comment]
It doesn't work when moving mouse to another to another floating window, it is inconsistent. Feels like the setting moves the window focus across "layers" not "tiles"

**Comment by vaxerski** [comment]
yes, that's exactly what the setting means.

**Comment by spikespaz** [comment]
It works when moving mouse from tiled to floating, no workie when mouse go floating to floating. Can I have a new setting for that

**Comment by vaxerski** [comment]
yeh

**Comment by vaxerski** [comment]
edeb759bb18fe9e8343d5d1c2ff8615811c23115
float_switch_override_focus 2
