### ISSUE TITLE
Automatically focus newly created windows in an empty workspace

### ISSUE THREAD

**Issue by kawa-sanmyaku** [hyprwm/Hyprland#8510]
### Description

New windows in empty workspaces should automatically be focused if follow_mouse=1

Currently windows open unfocused and it's necessary to move the mouse cursor a little bit

**Comment by Aqa-Ib** [comment]
For me, new windows get the focus automatically when created in an empty workspace. What hyprland version are you using? Does this behavior always happen for you or only under some circumtances?

**Comment by kawa-sanmyaku** [comment]
I just tested with a default config, the issue isn't present so it's probably my config that's causing the problem; I'm using hyprland 0.45 but I've had this config since 0.42 and the only things that have changed were the shadow options with the most recent hyprland update, and switching between different file managers

I'll just go ahead and re-write my config
