### ISSUE TITLE
smart_gaps / no_gaps_when_only workspace rules not working on latest HEAD

### ISSUE THREAD

**Issue by nawfalmrouyan** [hyprwm/Hyprland#8523]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch  at commit 936dfedbadbae761cd307ba7509467b55ac5e1ae  (keybinds: move to managed pointers).
Date: Tue Nov 19 03:56:26 2024
Tag: v0.45.0-45-g936dfedb, commits: 5478
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: opalMMU
Release: 6.11.9-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:09 +0000


GPU information:
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```
This version is compiled without the bad commit.

</details>

### Description

https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps not working on latest git

First bad commit: 47a1650c4810ad3cb3e9f125cb0addf18aa7395c

### How to reproduce

Install latest hyprland-git with https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps rules.

Open a single app, it will still have borders although the smart gaps rule is configured.

**Comment by vaxerski** [comment]
can't repro?

**Comment by nawfalmrouyan** [comment]
Oops, noticed I set the the ws rules to exempt when special is true.

workspace = w[tv1] s[0], gapsout:0, gapsin:0
workspace = w[tg1] s[0], gapsout:0, gapsin:0
workspace = f[1] s[0], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1] s[0]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1] s[0]
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tg1] s[0]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tg1] s[0]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1] s[0]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1] s[0]

It was working previously. Now if I remove s[0] from the rules, it works. But I would like the rules to not work on special workspaces.

**Comment by vaxerski** [comment]
Can you try removing the spaces between the selectors?

**Comment by nawfalmrouyan** [comment]
You mean like this?

w[tv1]s[0] ?

Borders still showing.

Doing on version without the bad commit also doesn't work (borders showing).
