### ISSUE TITLE
Auto-* positions don't work in first monitor rule.

### ISSUE THREAD

**Issue by GiantBlargg** [hyprwm/Hyprland#8529]
When the auto-* positions were added in #5670, it was decided that the first monitor should always be placed at 0x0, however the way it was implemented was that the first monitor rule should be set to `auto-right`, which would then place the first monitor at 0x0.
https://github.com/hyprwm/Hyprland/blob/67cee430061626ccd73dc6d30eed9db289053608/src/config/ConfigManager.cpp#L1944-L1952

This works alright assuming there's a 1:1 mapping between rules and monitors, but then you can't do this:
```
monitor=,preferred,auto-left,auto
```

Since this is the first (and only) rule it gets converted to `auto-right`, and then ALL monitors are arranged left-to-right, instead of right-to-left as requested.

**Comment by vaxerski** [comment]
please follow the templates. Also make sure it's not #8518

**Comment by GiantBlargg** [comment]
> please follow the templates. Also make sure it's not #8518

I wasn't sure if this was right for the bug template as I felt I had already identified the issue, and I didn't want to share my system info as I don't believe it's system dependant.

This is not #8518. Here monitors are arranged in valid way just not in the way specified, as opposed to #8518 where monitors positions are invalid.
