### ISSUE TITLE
Recovering a removed monitor fails

### ISSUE THREAD

**Issue by brodi1** [hyprwm/Hyprland#853]
Distro: Arch Linux
Hyprland Version: AUR (-git | commit 670d6ce8f476cbdced7aa62e7d8c16a48bccf0d5)
Config:
```
monitor=HDMI-A-3,1920x1080@60,0x0,1,mirror,eDP-1
monitor=,preferred,auto,1
```
Log: [hyprland.log](https://github.com/hyprwm/Hyprland/files/9786555/hyprland.log)

## Steps to reproduce
1. Use the config I used
2. Start hyprland with external monitor connected
3. Disconnect monitor cable
4. Reconnect monitor cable

## Expected outcome
Mirror the screen after reconnecting

## Noted outcome
After reconnecting the external monitor (HDMI-A-3) it stays black and the windows on the integrated one (eDP-1) go invisible...

**Comment by vaxerski** [comment]
Check with recent commits.

**Comment by brodi1** [comment]
@vaxerski k so I tested both 0ffaa8d and 5530cf6 with the same results.

 It improved a lot but the part of the bug that causes the windows to go invisible still is there....but it happens less often. While I did the testing I got it like 4-5 on average after disconnecting and connecting the cable. Atleast when it happens im able to disconnect and reconnect the cable and everything is normal again....not like in previous versions where I had to kill the Hyprland process. 

I tried figure it out the cause but I can't find anything abnormal inside the logs imo...
I'm not 100% sure but I got a feeling that it happens when switching very quickly from a workspace with a XWayland window to another workspace with a native Wayland application

**Comment by vaxerski** [comment]
the windows don't disappear for me, the monitor just switches to a different workspace. You sure they *disappear*?

**Comment by brodi1** [comment]
@vaxerski

> You sure they disappear?

yup! I just see my wallpaper and when I'm switching workspaces I can see the current focused window title on my waybar.
And the screen output on the second monitor is frozen

**Comment by vaxerski** [comment]
super odd. That was fixed for me with recent commits.

**Comment by vaxerski** [comment]
make sure you updated by verifying the hash with `hyprctl version`

**Comment by brodi1** [comment]
@vaxerski 
![grafik](https://user-images.githubusercontent.com/69462234/202897915-b1a6d5d6-5b86-49f8-91e5-53bdf3530b62.png)

**Comment by vaxerski** [comment]
alr. Odd.

**Comment by brodi1** [comment]
@vaxerski idk if this helps but here's a part of the log (I enabled time logging). The frame on the second monitor stopped at `17:26:54`
[hyprland.log](https://github.com/hyprwm/Hyprland/files/10050196/hyprland.log)

**Comment by vaxerski** [comment]
Nothing out of the ordinary. Possibly a driver bug?

**Comment by vaxerski** [comment]
Can't even see any logs related to connecting / disconnecting mons

**Comment by brodi1** [comment]
> Nothing out of the ordinary. Possibly a driver bug?

I also thought about that....

Sometimes I get layersurface messages inside the logs right when the frame freezes idk if it's related... one of them was this one https://github.com/hyprwm/Hyprland/blob/31aa357c17ab670041695da3d8ba8586063bf5a6/src/events/Layers.cpp#L29
I also tried turning off blur completly

**Comment by brodi1** [comment]
So I tried using the same installation but on other hardware (same iGPU) no problems at all.... imma close this issue for now

**Comment by vaxerski** [comment]
welcome to another episode of "your system is haunted"

**Comment by nmateo** [comment]
I have nearly the same issue, when i shutdown my only monitor, and i turn it on after the night all the window have disappeared but programs are still running.., log:
```
[LOG] Applying monitor rule for DP-1
[LOG] Setting preferred mode for DP-1
[LOG] Pending output DP-1 does not accept VRR.
[LOG] Monitor DP-1 -> destroyed all render data
[LOG] LayerSurface 5768e7f0 arranged: x: 0 y: 0 w: 2560 h: 32 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 574ea950 arranged: x: 0 y: 0 w: 2560 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-1 layers arranged: reserved: 0.000000 32.000000 0.000000 0.000000
[LOG] LayerSurface 5768e7f0 arranged: x: 0 y: 0 w: 2560 h: 32 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 574ea950 arranged: x: 0 y: 0 w: 2560 h: 1080 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-1 layers arranged: reserved: 0.000000 32.000000 0.000000 0.000000
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Allocated texture for BGTex
[LOG] Background created for monitor DP-1
[LOG] Shaders initialized successfully.
[LOG] Framebuffer created, status 36053
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[ERR] Committing TextInput on no IME!
[LOG] Hyprland received signal 15
```
