### ISSUE TITLE
Apps open as floating since 45.1-1

### ISSUE THREAD

**Issue by smoor3s** [hyprwm/Hyprland#8533]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>Hyprland 0.45.1 on Arch (6.11.9-zen1-1-zen)</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Since update to 45.1-1, chromium browsers (incl. brave)  and most (all?) gnome apps (evince, eog, text editor, etc.) open as floating. The browsers tile after changing the title bar setting; however, this was not necessary prior to 45.1. Apps seems to ignore manually setting each app to tiling with windowrules in the config. Was concerned over max. window size, but this was not an issue prior to 45.1-1 with the same apps. Other GTK apps appear to behave (tile) as expected.

### How to reproduce

Launch above apps in 45.0, upgrade Hyprland to 45.1-1 or 45.1-2 and re-open apps. I also tried this on a laptop with a fresh install of 45.0 and the example config. Worked perfectly...updated to 45.1-1 and the floating issue surfaced there, too.

### Crash reports, logs, images, videos

Nothing weird in the logs. Identical between Hyprland versions.

**Comment by Ghosthree3** [comment]
Fixed on master, see #8522

**Comment by smoor3s** [comment]
Sorry...I can't believe I missed that (8522).
