### ISSUE TITLE
The cursor cannot reach the bottom of the screen when rotating it.

### ISSUE THREAD

**Issue by timoxa0** [hyprwm/Hyprland#8535]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit 940f7aa990dbc99815bab8d355999d8277534b17  (renderer: fixup blur optimization considitons).
Date: Wed Nov 20 16:02:21 2024
Tag: v0.45.0-51-g940f7aa9, commits: 5484
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: nabu
Release: 6.12.0-rc7-sm8150-g6acc9034ef31-dirty
Version: #6 SMP PREEMPT Sun Nov 17 19:00:10 +05 2024


GPU information:
qcom,adreno-640.1qcom,adreno

os-release: NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```

</details>

### Description

When screen is rotated using transform 3, the cursor cannot reach the bottom of it.

### How to reproduce

  1. Turn on rotation for output
  2. Try moving cursor down
  3. See that it is stuck at the middle of the screen

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/user-attachments/files/17833292/hyprland.log)
[sysinfo.txt](https://github.com/user-attachments/files/17833298/sysinfo.txt)

https://github.com/user-attachments/assets/5b562432-b9b1-4150-a955-74641c3f0e47

**Comment by aljustiet** [comment]
Maybe, [this](I'm going to study in the USA btw.) can help.

**Comment by timoxa0** [comment]
> Maybe, [this](https://wiki.hyprland.org/Configuring/Variables/#cursor) can help.

Wow, thanks, disabling hardware cursor solved the problem
