### ISSUE TITLE
No keybinds working

### ISSUE THREAD

**Issue by JoMaZu787** [hyprwm/Hyprland#8537]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
hyprland 0.45.2-3
```
(Can't paste command output because that requires the ability to open a program) 
</details>

### Description

All my keybinds suddenly stopped working. I tried restarting the computer and deleting my hyprland.conf, but that did nothing. Trying to launch alcacritty using `hyprctl --instance 0 dispatch exec alacritty` seems to crash hyprland completely.

### How to reproduce

I don't know how to reproduce this

**Comment by JoMaZu787** [comment]
Installed xfce to get a browser window and copy-paste, here is the output from `hyprland --systeminfo`:
```
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: desktop-jomazu787
Release: 6.11.9-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:17 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080] [10de:2206] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  565.57.01  Release Build  (archlinux-builder@desktop-jomazu787)  


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime

```

**Comment by vaxerski** [comment]
can you post a log from running hyprland?

**Comment by JoMaZu787** [comment]
[hyprland.log](https://github.com/user-attachments/files/17870874/hyprland.log)

**Comment by vaxerski** [comment]
I don't think anything looks terribly amiss here, maybe an nvidia update broke something?

**Comment by JoMaZu787** [comment]
It started while I was using the computer normally, specifically when I tried to paste text I copied from the minecraft chat input box into a discord (vesktop) text channel, which resulted in vesktop crashing. I'll try reinstalling hyprland and switching back to `nvidia-dkms` from `nvidia-open-dkms` even though nvidia recommends the open source kernel modules for newer GPUs.

**Comment by JoMaZu787** [comment]
UPDATE: I changed the hyprland.conf to autostart the terminal and I can use it normally, but when I try to use a hyprland shortcut, like Super+M to exit hyprland, it types the key I pressed (M) into the terminal as if hyprland isn't seeing the modifier key. I will test if adding a keybind with shift, control or Alt as the modifier or with no modifier will work.

**Comment by JoMaZu787** [comment]
So I found an old microsoft keyboard, crustiest thing known to man, and i don't have any AAA batteries to power it (its wireless) but it came with a mouse that has working batteries and a windows key (on the mouse) and that works.

**Comment by JoMaZu787** [comment]
It was my keyboard the whole time! I tried it on a different machine and the windows key didn't work.
