### ISSUE TITLE
Allow window rules to specify a workspace tile direction

### ISSUE THREAD

**Issue by paul-hansen** [hyprwm/Hyprland#8540]
## Request
Allow window rules to open matching windows in a specific workspace in the top right while still being tiled.

Maybe something like:
```
windowrulev2 = workspace 1 silent tr, class:^(bevy.+)$
```
The logic for the placement would be similar to `layoutmsg preselect tr` but limited to the workspace.

## Considered alternatives
I could use `hyprctl dispatch layoutmsg preselect tr` as described here: https://wiki.hyprland.org/Configuring/Dwindle-Layout/#layout-messages , but this requires me to have control over what is launching the window which isn't always the case.

I could make a bash script to detect when the matching window is created, but I think my only option is to call `movewindow` dispatcher but this doesn't have an option to move it within the workspace, so depending where my windows are it could end up in the wrong workspace, requiring even more scripting to accomplish this.

## Thanks
Loving Hyprland so far! Looking for alternatives to KDE because many of their window rules are broken on Wayland.

Opened this because it sounded like a feature others could could find useful. If you disagree, don't worry about it, I can figure something out for my use case.

**Comment by paul-hansen** [comment]
Other possible implementations:
```
windowrulev2 = preselect tr, class:^(bevy.+)$
```
Or
```
windowrulev2 = move tr, class:^(bevy.+)$
```
Which would allow it to be also be used without specifying a workspace. As long as there's a way to make sure it stays in a workspace those would work for me too.

**Comment by vaxerski** [comment]
I don't think I understand?

**Comment by paul-hansen** [comment]
I wanted to have a window rule so that when a matching window is opened it would be tiled but prefer being placed in the top right corner of my second monitor. I haven't found a way to do this, perhaps I'm missing something?

Will close for now, probably not worth the effort if it isn't obvious to others what my suggestion would do from the examples.
