### ISSUE TITLE
Cannot start Hyprland in VM

### ISSUE THREAD

**Issue by SUSEEnthusiasts** [hyprwm/Hyprland#855]
Outside of root it gives the error:
`Couldn't query the DRM FD!
terminate called after throwing an instance of 'std::runtime_error'
  what():  wlr_backend_get_drm_fd() failed!
Aborted (core dumped)`
while in root I get `terminate called after throwing an instance of 'std::runtime_error'
  what():  XDG_RUNTIME_DIR is not set!
Aborted (core dumped)`.

**Comment by SUSEEnthusiasts** [comment]
This is in OpenSUSE VM.
I used both `Hyprland` and `WLR_RENDERER_ALLOW_SOFTWARE=1 Hyprland`.
I've seen people saying "Don't use a VM". But that really shouldn't be an plausible option

**Comment by Heisfer** [comment]
seems like gpu drm error for me.

**Comment by SUSEEnthusiasts** [comment]
> seems like gpu drm error for me.

Seems like it, however every single person who has ran this in a VM (according to the Issues page) has been getting this error.
Doesn't that mean the issue can't be on our side and has to be a bug that needs to be solved?

**Comment by vaxerski** [comment]
many people have ran hl in a VM with success.

**Comment by vaxerski** [comment]
try starting sway and seeing if that works.

**Comment by SUSEEnthusiasts** [comment]
> 

Running sway just gives this:
![afbeelding](https://user-images.githubusercontent.com/115837274/195938199-2a594ac5-e461-4963-bd4e-33072d309908.png)

**Comment by SUSEEnthusiasts** [comment]
> Are you trying to run Hyprland while on GNOME or..?

Yes, Should I not be doing this?

**Comment by SUSEEnthusiasts** [comment]
> > > Are you trying to run Hyprland while on GNOME or..?
> > 
> > 
> > Yes, Should I not be doing this?
> 
> No. Run Hyprland from TTY. [Did you even read the wiki](https://wiki.hyprland.org/Getting-Started/Quick-start/)?

I did, must've looked over it, oh lord

**Comment by SUSEEnthusiasts** [comment]
> > > > Are you trying to run Hyprland while on GNOME or..?
> > > 
> > > 
> > > Yes, Should I not be doing this?
> > 
> > 
> > No. Run Hyprland from TTY. [Did you even read the wiki](https://wiki.hyprland.org/Getting-Started/Quick-start/)?
> 
> I did, must've looked over it, oh lord

I appear to be getting the same error while running in root, outside of root I get this:
![afbeelding](https://user-images.githubusercontent.com/115837274/195939515-a86537de-8166-426c-8ca2-b54f5493ac98.png)

**Comment by pinkcreeper100** [comment]
You aren't supposed to run hyprland as root

**Comment by SUSEEnthusiasts** [comment]
> You aren't supposed to run hyprland as root

besides the point, it also doesnt work outside of root.

**Comment by SUSEEnthusiasts** [comment]
> Are you running it via `WLR_RENDERER_ALLOW_SOFTWARE=1`?

if by that you mean running `WLR_RENDERER_ALLOW_SOFTWARE=1 Hyprland` then yes.

**Comment by Heisfer** [comment]
is polkit or seatd installed?
seatd:
check if seatd service is enabled
check if your user is inside seat group.

**Comment by SUSEEnthusiasts** [comment]
> 

I'm using polkit, should I be using seatd?
![afbeelding](https://user-images.githubusercontent.com/115837274/195940758-e06fc955-b223-4212-bff6-df4e17f4fc5a.png)

**Comment by SUSEEnthusiasts** [comment]
> is polkit or seatd installed? seatd: check if seatd service is enabled check if your user is inside seat group.

Tried to use seatd: Got this error:
![afbeelding](https://user-images.githubusercontent.com/115837274/195941114-ecf85947-fbf7-4ebc-bc18-15c7590990ee.png)
I'm just gonna assume this is me being an idiot.

**Comment by vaxerski** [comment]
of course it is.

As I've repeated 20 times, this entire issue is arising because you're using arch without knowing how to use arch.

**Comment by SUSEEnthusiasts** [comment]
> of course it is.
> 
> As I've repeated 20 times, this entire issue is arising because you're using arch without knowing how to use arch. Or any other babrebones distro, for that matter. I can guarantee you that if you'd set up an Endeavour / Manjaro / etc VM it would magically work.

arch? I'm on OpenSUSE, I just followed the official Hyprland install manual which recommended I use OpenSUSE which luckily enough I am on.
I could open a Manjaro VM if you want me to, sure, but I don't know why you assumed I was on arch.

**Comment by vaxerski** [comment]
> arch? I'm on OpenSUSE, I just followed the official Hyprland install manual which recommended I use OpenSUSE which luckily enough I am on.

where do we recommend any distro?
![image](https://user-images.githubusercontent.com/43317083/195942505-15d9f769-f695-40e0-9a4f-be8aa4ff4450.png)

I was opposing adding OpenSUSE to this list precisely because of that. *No one* from the hyprwm team uses SUSE, but the Suse contributor insisted.

Nobody here is able to provide any Suse support, we've never used it.

Hyprland works fine in a VM, provided you pass the software rendering flag and have everything config'd properly.

> I don't know why you assumed I was on arch.

because 99% of our users are either Arch or Nix

**Comment by SUSEEnthusiasts** [comment]
> > arch? I'm on OpenSUSE, I just followed the official Hyprland install manual which recommended I use OpenSUSE which luckily enough I am on.
> 
> where do we recommend any distro? ![image](https://user-images.githubusercontent.com/43317083/195942505-15d9f769-f695-40e0-9a4f-be8aa4ff4450.png)
> 
> I was opposing adding OpenSUSE to this list precisely because of that. _No one_ from the hyprwm team uses SUSE, but the Suse contributor insisted.
> 
> Nobody here is able to provide any Suse support, we've never used it.
> 
> Hyprland works fine in a VM, provided you pass the software rendering flag and have everything config'd properly.
> 
> > I don't know why you assumed I was on arch.
> 
> because 99% of our users are either Arch or Nix

I see, I'm sorry for causing you any trouble.
I'll be trying out with manjaro now and closing this issue

If anyone is reading this and trying it figure out their issue, sorry you've come to the wrong thread.
Have luck figuring it out :d

**Comment by SUSEEnthusiasts** [comment]
@vaxerski 
Sorry for @ but CMake (git clone --recursive https://github.com/hyprwm/Hyprland) requires logging in, while password authentication was removed back in 2021

**Comment by vaxerski** [comment]
it does not. what the hell are you on? It's a public repo...

**Comment by SUSEEnthusiasts** [comment]
> it does not. what the hell are you on? It's a public repo...

According to my Manjaro machine it's... not...? I'm confused

![afbeelding](https://user-images.githubusercontent.com/115837274/195949564-1843fbb3-d08d-40b8-b83c-2319e53fe553.png)

**Comment by vaxerski** [comment]
*hyperwm*

**Comment by SUSEEnthusiasts** [comment]
> _hyperwm_

Bruh I really jut typed that wrong 5 times without noticing, sorry.

**Comment by vaxerski** [comment]
also on manjaro you have the AUR. `yay -S hyprland-git`

**Comment by SUSEEnthusiasts** [comment]
> also on manjaro you have the AUR. `yay -S hyprland-git`

I'm aware, I've been using yay.

**Comment by GHydrogen** [comment]
Trying to turn on _3D acceleration_, I turned on _3D acceleration_ in VBox and successfully got into _Hyprland_.

![example](https://github.com/hyprwm/Hyprland/assets/111329731/36c5940e-b269-4132-ac80-8231a69084c2)

I've had similar errors before, I found references [here](https://github.com/hyprwm/Hyprland/issues/723#issuecomment-1440718676) .

Hope that helps.

**Comment by rusted-snow** [comment]
> Trying to turn on _3D acceleration_, I turned on _3D acceleration_ in VBox and successfully got into _Hyprland_.

That worked! 
Thanks!

**Comment by LongYinStudio** [comment]
> Trying to turn on _3D acceleration_, I turned on _3D acceleration_ in VBox and successfully got into _Hyprland_.
> 
> ![example](https://private-user-images.githubusercontent.com/111329731/256531904-36c5940e-b269-4132-ac80-8231a69084c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjE1OTQsIm5iZiI6MTcwMjEyMTI5NCwicGF0aCI6Ii8xMTEzMjk3MzEvMjU2NTMxOTA0LTM2YzU5NDBlLWIyNjktNDEzMi1hYzgwLTgyMzFhNjkwODRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxMTI4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGYxZTM2NjBhMDUyOWE0OWYyYWMxODIwOTRiNGYxNGRmY2I4YzM5ZDI2NGY3OTA5MzQ5OTkzODc2MDc0MDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MfyEitp88IcOcmQIkmn-qPWyTHzW4qz9c775w4VQy6U)
> 
> I've had similar errors before, I found references [here](https://github.com/hyprwm/Hyprland/issues/723#issuecomment-1440718676) .
> 
> Hope that helps.

大佬，牛逼
