### ISSUE TITLE
Black Screen at Launch [VirtualBox]

### ISSUE THREAD

**Issue by jkim5959** [hyprwm/Hyprland#856]
Hyprland suddenly shows black screen at launch.

It was working fine until yesterday. I believe I updated Hyprland to 0.15.3 a few days before that.

I tried `WLR_RENDERER_ALLOW_SOFTWARE=1 Hyprland` yet it didn't work. In fact, I didn't even need this when it was working fine.

What's weird about this is that I think apps actually open, it's just the screen output is black.

Because I can press `super + Enter` then type `poweroff` and enter my password and hit enter and it WILL poweroff.

I am sorry if I missed something obvious, but I did go through every issues and faq guidelines on wiki that has any relevance to vm or black screen.

Here are my logs, and again, I'm sorry for my choice of colors and screenshot instead of actual text.

![VirtualBox_Waybar_15_10_2022_21_00_40](https://user-images.githubusercontent.com/85728320/195983311-7a8cf1ae-c583-4449-bc1d-7730a5620ff2.png)
![VirtualBox_Waybar_15_10_2022_21_01_19](https://user-images.githubusercontent.com/85728320/195983312-799784a1-4469-44b3-8778-ab39761b819b.png)
![VirtualBox_Waybar_15_10_2022_21_01_40](https://user-images.githubusercontent.com/85728320/195983316-28169688-e15d-4e2e-8c7a-be9ec2487a06.png)
![VirtualBox_Waybar_15_10_2022_21_01_55](https://user-images.githubusercontent.com/85728320/195983318-7bfad833-64c8-4841-b554-b0003844f752.png)
![VirtualBox_Waybar_15_10_2022_21_02_09](https://user-images.githubusercontent.com/85728320/195983319-717f59e0-b85e-4150-b2ef-83460d5015f0.png)
![VirtualBox_Waybar_15_10_2022_21_02_17](https://user-images.githubusercontent.com/85728320/195983320-3f60ea70-db0b-4676-bc45-3bab5b16954c.png)
![VirtualBox_Waybar_15_10_2022_21_02_31](https://user-images.githubusercontent.com/85728320/195983321-cdab694a-c050-4ce6-a9e2-a2f612b2b0cc.png)
![VirtualBox_Waybar_15_10_2022_21_02_40](https://user-images.githubusercontent.com/85728320/195983322-ea4a3084-c9cf-4a37-a5f3-30c872451ac4.png)

**Comment by jkim5959** [comment]
I do understand the devs hate vm and that's fair. But please understand it's my only laptop and i can't really afford to install this on a bare metal without learning through vm ;(

**Comment by vaxerski** [comment]
If this is a regression, please provide the faulty commit by doing a `git bisect`. You can input the good commit by using the last version that worked, the bad as HEAD and git will let you know which commits to test later.

**Comment by jkim5959** [comment]
> If this is a regression, please provide the faulty commit by doing a `git bisect`. You can input the good commit by using the last version that worked, the bad as HEAD and git will let you know which commits to test later.

I'm not sure if what I did is right because this is the first time using bisect but I think I did it. It says `Bisecting: 16 revisions left to test after this (roughly 4 steps)`
Then it says a bunch of numbers and letters then goes `check for same workspace in workspace rule`.

**Comment by jkim5959** [comment]
You know what, I re-installed v0.15.2beta and now it's back to normal. I think I'll just use it like this until I get good enough to install on bare metal :)

**Comment by vaxerski** [comment]
@Dickby that would imply your matrix PR broke VMs
