### ISSUE TITLE
Breaks with Mesa 24.3 on Cachyos

### ISSUE THREAD

**Issue by thehouseisonfire** [hyprwm/Hyprland#8560]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0

flags set:
debug

System Information:
System name: Linux
Node name: next
Release: 6.12.1-2-cachyos
Version: #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 17:05:17 +0000

GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [UHD Graphics] [8086:a720] (rev 04) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28e1] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  565.57.01  Release Build  (notroot@cd245b0679c6)  Fri Nov 22 17:18:10 UTC 2024

os-release: NAME="CachyOS Linux"
PRETTY_NAME="CachyOS"
ID=cachyos
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://cachyos.org/"
DOCUMENTATION_URL="https://wiki.cachyos.org/"
SUPPORT_URL="https://discuss.cachyos.org/"
BUG_REPORT_URL="https://github.com/cachyos"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=cachyos

plugins:

======Config-Start======

Config File: /home/eagle/.config/hypr/hyprland.conf: Read Succeeded

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

monitor= eDP-2, 1920x1200@144.00101, 0x0, 1.00

exec-once = nm-applet --indicator

# Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &
#exec-once = xdg-desktop-portal-hyprland &

# ## Idle configuration
#
exec-once = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# ## Input configuration
#
input {
kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    numlock_by_default= true
    follow_mouse = 1

touchpad {
    natural_scroll = false
    tap-to-click = true
    disable_while_typing = true
}

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 9
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(8f00ffee) 45deg
    col.inactive_border = rgba(595959aa)
    # allow_tearing = true
    layout = dwindle
}

# windowrulev2 = immediate, class:^(cs2)$
# windowrulev2 = immediate, class:^(ds3)$

decoration {
    # active_opacity = 0.98
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    rounding = 4
    blur {
        enabled = true
        size = 5
        passes = 1 # more passes = more resource intensive.
        new_optimizations = true
        xray = true
        ignore_opacity = false
    }

    # drop_shadow = false
    # shadow_range = 4
    # shadow_render_power = 3
    # shadow_ignore_window = true

    dim_inactive = false
    # col.shadow = rgba(1a1a1aee)
}

# Blur for waybar
#blurls = waybar

animations {
    enabled = true

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.2, 1.05
    #bezier = overshot, 0.13, 0.99, 0.29, 1.1
    bezier = overshot2, 0.05, 0.9, 0.20, 1.04

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    #animation = workspaces, 1, 6, default
    #animation = workspaces, 1, 6, overshot2, slide
    animation = workspaces, 1, 6, overshot2

}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

# workspace = w[tv1], gapsout:2, gapsin:2
# workspace = f[1], gapsout:2, gapsin:2
# windowrulev2 = bordersize 2, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 10, floating:0, onworkspace:w[tv1]
# windowrulev2 = bordersize 2, floating:0, onworkspace:f[1]
# windowrulev2 = rounding 10, floating:0, onworkspace:f[1]

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    # no_gaps_when_only = false
    new_status = master
    special_scale_factor = 0.8
}

misc {
    # vrr = 2
    #disable_autoreload = true
    disable_hyprland_logo = true
    always_follow_on_dnd = true
    layers_hog_keyboard_focus = true
    animate_manual_resizes = false
    enable_swallow = true
    swallow_regex =
    focus_on_activate = true
    vfr = 1
}

gestures {
     workspace_swipe = true
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# bind = $mainMod, SHIFT, C, movetoworkspacesilent, 1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

bind = $mainMod SHIFT,C, exec, killall -9 wpaperd && wpaperd
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, RETURN, exec, alacritty
bind = $mainMod, A, exec, grim -g "$(slurp)" - | swappy -f -
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, D, exec, wofi --normal-window --show drun --allow-images
bind = $mainMod, V, togglefloating,
# bind = CTRL, SPACE, exec, rofi -show combi -modi window,run,combi -combi-modi window,run
#bind = CTRL, SPACE, exec, wofi
bind = $mainMod, F, fullscreen
bind = $mainMod, Y, pin
#bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = $mainMod, K, togglegroup,
bind = $mainMod, Tab, changegroupactive, f

bind = $mainMod SHIFT, G,exec,hyprctl --batch "keyword general:gaps_out 5;keyword general:gaps_in 3"
bind = $mainMod , G,exec,hyprctl --batch "keyword general:gaps_out 0;keyword general:gaps_in 0"

# Volume control

bind=,XF86AudioLowerVolume,exec,pamixer -ud 3 && pamixer --get-volume > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob
bind=,XF86AudioRaiseVolume,exec,pamixer -ui 3 && pamixer --get-volume > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob
# mute sound
bind=,XF86AudioMute,exec,amixer sset Master toggle | sed -En '/\[on\]/ s/.*\[([0-9]+)%\].*/\1/ p; /\[off\]/ s/.*/0/p' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob

# Playback control

bind=,XF86AudioPlay,exec, playerctl play-pause
bind=,XF86AudioNext,exec, playerctl next
bind=,XF86AudioPrev,exec, playerctl previous

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

bind = $mainMod SHIFT, P, exec, gnome-calculator
bind = $mainMod, L, exec, swaylock-fancy -e -K -p 10 -f Hack-Regular
#bind = $mainMod, P, exec, ~/.scripts/dmshot

bind = $mainMod, O, exec, killall -SIGUSR2 waybar

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod, period, workspace, e+1
bind = $mainMod, comma, workspace,e-1

bind = $mainMod, minus, movetoworkspace,special
bind = $mainMod, equal, togglespecialworkspace

bind = $mainMod SHIFT,left ,movewindow, l
bind = $mainMod SHIFT,right ,movewindow, r
bind = $mainMod SHIFT,up ,movewindow, u
bind = $mainMod SHIFT,down ,movewindow, d

# Move active window to a workspace with mainMod + CTRL + [0-9]
bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10
bind = $mainMod CTRL, left, movetoworkspace, -1
bind = $mainMod CTRL, right, movetoworkspace, +1

# same as above, but doesnt switch to the workspace
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

binds {
     workspace_back_and_forth = 1
     allow_workspace_cycles = 1
}
bind = $mainMod,slash,workspace,previous

bind = $mainMod,R,submap,resize
submap = resize
binde =,right,resizeactive,15 0
binde =,left,resizeactive,-15 0
binde =,up,resizeactive,0 -15
binde =,down,resizeactive,0 15
binde =,l,resizeactive,15 0
binde =,h,resizeactive,-15 0
binde =,k,resizeactive,0 -15
binde =,j,resizeactive,0 15
bind =,escape,submap,reset
submap = reset

bind=CTRL SHIFT, left, resizeactive,-15 0
bind=CTRL SHIFT, right, resizeactive,15 0
bind=CTRL SHIFT, up, resizeactive,0 -15
bind=CTRL SHIFT, down, resizeactive,0 15
bind=CTRL SHIFT, l, resizeactive, 15 0
bind=CTRL SHIFT, h, resizeactive,-15 0
bind=CTRL SHIFT, k, resizeactive, 0 -15
bind=CTRL SHIFT, j, resizeactive, 0 15

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#exec-once = alacritty
#exec-once = telegram-desktop
#exec-once = armcord
#exec-once = swaybg -o \* -i /usr/share/wallpapers/cachyos-wallpapers/Liquid.png -m fill
#------------#
# auto start #
#------------#

exec-once = wpaperd

exec-once = waybar
layerrule = blur , waybar
layerrule = ignorezero , waybar

exec-once = fcitx5 -d &
exec-once = mako &
exec-once = nm-applet --indicator &
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown" &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = foot --server
# Float Necessary Windows
windowrule=float,Rofi
windowrule=float,pavucontrol
windowrulev2 = float,class:^()$,title:^(Picture in picture)$
windowrulev2 = float,class:^(brave)$,title:^(Save File)$
windowrulev2 = float,class:^(brave)$,title:^(Open File)$
windowrulev2 = float,class:^(LibreWolf)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float,class:^(xdg-desktop-portal-kde)$
windowrulev2 = float,class:^(xdg-desktop-portal-hyprland)$
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float,class:^(CachyOSHello)$
windowrulev2 = float,class:^(zenity)$
windowrulev2 = float,class:^()$,title:^(Steam - Self Updater)$

# Increase the opacity
windowrule=opacity 0.92,Thunar
windowrule=opacity 0.92,Nautilus
windowrule=opacity 0.96,discord
windowrule=opacity 0.96,armcord
windowrule=opacity 0.96,webcord

#---------------#
# windows rules #
#---------------#
#`hyprctl clients` get class、title...
windowrule=float,title:^(Picture-in-Picture)$
windowrule=size 960 540,title:^(Picture-in-Picture)$
windowrule=move 25%-,title:^(Picture-in-Picture)$
windowrule=float,imv
windowrule=move 25%-,imv
windowrule=size 960 540,imv
windowrule=float,mpv
windowrule=move 25%-,mpv
windowrule=size 960 540,mpv
windowrule=float,danmufloat
windowrule=move 25%-,danmufloat
windowrule=pin,danmufloat
windowrule=rounding 5,danmufloat
windowrule=size 960 540,danmufloat
windowrule=float,termfloat
windowrule=move 25%-,termfloat
windowrule=size 960 540,termfloat
windowrule=rounding 5,termfloat
windowrule=float,nemo
windowrule=move 25%-,nemo
windowrule=size 960 540,nemo
windowrule=opacity 0.95,title:Telegram
windowrule=opacity 0.95,title:QQ
windowrule=opacity 0.95,title:NetEase Cloud Music Gtk4
windowrule=animation slide right,kitty
windowrule=animation slide right,alacritty
windowrule=float,ncmpcpp
windowrule=move 25%-,ncmpcpp
windowrule=size 960 540,ncmpcpp
windowrule=noblur,^(firefox)$
windowrule=noblur,^(waybar)$

======Config-End========

### Description

Hello, and before anything I want to thank the hyprland team for their amazing project, I have been using it for 6 months now, ever since I switched from bspwm, a bug report might not be the place to do this but I never came around to doing so elsewhere so I figured I'd use this to tell my gradiude (btw @vaxerski is, in fact, based, and the ban was unwarranted imho).

So I had just upgraded to mesa 24.3.0-2 (and vulkan intel) on my cachyos machine, rebooted as they always recommend you, but after logging pass sddm I am greeted with a black screen. Rebooted switched to TTY(3?) and tried launching hypr from there, just to get the same result, so I tried downgrading mesa back to 24.2.7-1, and it began working again from sddm logging and all, so I suspect that is the source of the issue. If you guys need any more info from journald or other logs just ask me, I'm willing to try and replicate this again if needed too.

Thanks again in advance.

### How to reproduce

Again, I suspect just installed mesa 24.3.0-2 in a intel/nvidia machine does it, but that's just my assessment.

### Crash reports, logs, images, videos

logs were disabled during it, I can try again if needed.

**Comment by vaxerski** [comment]
if it's a mesa regression then this is the wrong repo to report it?
