### ISSUE TITLE
hyprland crashes for unknown reason

### ISSUE THREAD

**Issue by valentin-buick** [hyprwm/Hyprland#8575]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3


flags: (if any)


System Information:
System name: Linux
Node name: LAPTOP-LTPT14SG4AMD
Release: 6.12.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000


GPU information: 
c3:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev dd) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/valentin/.config/hypr/hyprland.conf: Read Succeeded
# This is an example Hyprland config file.
#
# Refer to the wiki for more information.

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,1920x1200@60,0x0,1.50

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

exec-once = dunst
exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

$terminal = kitty

# Some default env vars.
env = XCURSOR_SIZE,24
env = WLR_DRM_NO_ATOMIC,1
env = GDK_SCALE,1.5

xwayland:force_zero_scaling = true

# Tearing support for games
# https://wiki.hyprland.org/Configuring/Tearing/
#windowrulev2 = immediate, class:^(cs2)$

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = de
    kb_variant = nodeadkeys
    kb_model = pc86
    kb_options =
    kb_rules =

    follow_mouse = 2

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    #allow_tearing = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 1
    }
    #shadow {
    #  enabled = true
    #  range = 4
    #  render_power = 3
    #  color = rgba(1a1a1aee)
    #}

    active_opacity = 1
    inactive_opacity = 1
    dim_inactive = false
    dim_strength = 0
}

windowrulev2 = opacity 0.9 override,class:(kitty)

animations {
    enabled = true

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    #new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = false
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, exec, kitty
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy #togglefloating,
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, K, exec, wlogout

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a wor 
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

======Config-End========

```

</details>

### Description

Hi, there. I encountered an issue after updating to hyprland 0.45.2-3 (apologies, the systeminfo is from after I downgraded again. Not sure if this fixes things)

System: Lenovo ThinkPad T14s Gen4 AMD (Model: 21F8)
OS: Arch Linux
Kernel: 6.12.1-arch1-1

This first two occurrences it happened while running firefox. The system froze, hyprland crashed, and after some time returned to SDDM.
The third time happened in nvim. The screen was still updating, but the last key I entered (backspace) seemingly got "stuck." This time I had to force reset the machine.
I don't know if my downgrading has worked yet, since I really couldn't tell you how to reproduce this issue. I'm assuming hyprland is the cause since it's the only process that coredumped during both the first two occurrences.
For some reason there is no hyprland crash report sooo, I'm kinda doubting my assumptions...
Please let me know if this issue should be reported elsewhere. This is my first time reporting a software issue.

### How to reproduce

Unfortunately I really couldn't tell you

### Crash reports, logs, images, videos

[journalctl_hyprland2.log](https://github.com/user-attachments/files/17894984/journalctl_hyprland2.log)
[journalctl_hyprland1.log](https://github.com/user-attachments/files/17894985/journalctl_hyprland1.log)

**Comment by myamusashi** [comment]
Can you get the debug stacktrace? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by ikalco** [comment]
the crash is caused by a gpu reset which probably isn't hyprland's fault
but to be safe give the debug stacktrace and also a full hyprland.log

to fix it you can try downgrading your linux kernel
I have a feeling its a regression from the recent update to 6.12.1

**Comment by valentin-buick** [comment]
> the crash is caused by a gpu reset which probably isn't hyprland's fault
> but to be safe give the debug stacktrace and also a full hyprland.log
> 
> to fix it you can try downgrading your linux kernel
> I have a feeling its a regression from the recent update to 6.12.1

Thank you for the suggestions!
You say a gpu reset is causing this. Could you, from the log, see what is causing that gpu reset? Since I don't know how to replicate the issue deliberately..
Apologies, I'm a total noob when it comes to the Linux graphics stack.

**Comment by ikalco** [comment]
> > the crash is caused by a gpu reset which probably isn't hyprland's fault
> > but to be safe give the debug stacktrace and also a full hyprland.log
> > to fix it you can try downgrading your linux kernel
> > I have a feeling its a regression from the recent update to 6.12.1
> 
> Thank you for the suggestions! You say a gpu reset is causing this. Could you, from the log, see what is causing that gpu reset? Since I don't know how to replicate the issue deliberately.. Apologies, I'm a total noob when it comes to the Linux graphics stack.

Not entirely sure, it seems the reason for the reset happens before the start of the log, but there is this
```
Nov 23 22:18:00 LAPTOP-LTPT14SG4AMD kernel: amdgpu 0000:c3:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
```
and based on [this issue](https://github.com/ROCm/ROCm/issues/2196) and some hints in the logs, the crash could be caused by high vram usage and/or just crappy AMD drivers...

**Comment by notquitethereyet** [comment]
I think i have this issue again. SDDM does not correctly start Hyprland. I get stuck on the login screen and can't do anything, but somehow if i connect a HDMI monitor, Hyprland works as expected? The laptop screen still displays the sddm screen.

**Comment by notquitethereyet** [comment]
[hyprland.log](https://github.com/user-attachments/files/17911931/hyprland.log)
adding my hyprland.log for reference.

**Comment by solitudealma** [comment]
> I think i have this issue too. SDDM does not correctly start Hyprland. I get stuck on the login screen and can't do anything, but somehow if i connect a HDMI monitor, Hyprland works as expected? The laptop screen still displays the sddm screen.

I can't use the new version of hyprland properly with regreet on nixos. Although I can enter, I can't establish communication with services such as dbus, causing some services and applications to not work properly.

**Comment by notquitethereyet** [comment]
hi, just informing that my issue was with the new mesa update breaking intel. downgrading worked for me

**Comment by valentin-buick** [comment]
> > > the crash is caused by a gpu reset which probably isn't hyprland's fault
> > > but to be safe give the debug stacktrace and also a full hyprland.log
> > > to fix it you can try downgrading your linux kernel
> > > I have a feeling its a regression from the recent update to 6.12.1
> > 
> > Thank you for the suggestions! You say a gpu reset is causing this. Could you, from the log, see what is causing that gpu reset? Since I don't know how to replicate the issue deliberately.. Apologies, I'm a total noob when it comes to the Linux graphics stack.
> 
> Not entirely sure, it seems the reason for the reset happens before the start of the log, but there is this
> ```
> Nov 23 22:18:00 LAPTOP-LTPT14SG4AMD kernel: amdgpu 0000:c3:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
> ```
> and based on [this issue](https://github.com/ROCm/ROCm/issues/2196) and some hints in the logs, the crash could be caused by high vram usage and/or just crappy AMD drivers...

I cut the log there deliberately because there wasn't anything even gpu related before that. I've also downgraded hyprland the kernel and firmware to previous versions and so far it seems to be working fine

**Comment by withoutme432** [comment]
maybe the issue is related to https://github.com/hyprwm/Hyprland/issues/8605

**Comment by ikalco** [comment]
@valentin-buick
any update on that debug stacktrace?

**Comment by valentin-buick** [comment]
> @valentin-buick
> any update on that debug stacktrace and full trace log?

Thanks for still checking in on this issue!
However, as I said before, I could not identify a concrete cause for the crash, since it, seemingly, happened for "no reason." So I wouldn't even know how to go about triggering a crash deliberately. Although I can confirm that after downgrading hyprland, kernel and kernel firmware the problem doesn't seem to reoccur.
For now, I was planning on waiting for new releases of the kernel and firmware to upgrade to and see if the crash happens again.
But if you could point me in the right direction, in regards to deliberately triggering the crash, I would be happy to get you that stacktrace!

**Comment by ikalco** [comment]
i see, if the reset happened out of nowhere for no reason then yeah its either a hardware or driver bug  and this can probably be closed, but be sure to reopen along with the logs if it crashes the same way again

also just to be sure, does updating Hyprland but keeping the downgraded kernel and firmware make the crash show up?
if it does then it's a Hyprland issue, so give the stacktrace and log

**Comment by valentin-buick** [comment]
Yesterday I did a complete system update. Both hyprland, the kernel and firmware to the newest versions. The kernel version I have now is also a newer one than the one I had when it was crashing.
So far the crash hasn't reoccured, but I also haven't been able to test for all that long.
So for now I'm going to, tentatively, mark this as closed. But I'll be sure to update here if I learn something new!
