### ISSUE TITLE
[Animation] Borders in a tiling window becomes lighter before closing

### ISSUE THREAD

**Issue by ghost** [hyprwm/Hyprland#858]
## How to reproduce
* Set `col.active_border` to `0x66ee1111` or any transparent color
* Open a window in tiling mode
* Close the window

## Expected behavior
The border should fade along with the window.

## Current behavior
The border becomes lighter (kinda "flashes") before closing.

# Infos
### Tiling mode
https://user-images.githubusercontent.com/93444783/195999743-627a9762-e963-4ef7-b0c4-18350fb3808c.mp4

### Floating mode (compared to tiling mode at the end
https://user-images.githubusercontent.com/93444783/195999747-c6324335-db7d-4f6c-9f3c-a64bd1dadc6f.mp4

## Configuration
[`hyprland.conf`](https://raw.githubusercontent.com/0x4nt/dotfiles/wayland/Hyprland/src/.config/hypr/hyprland.conf)

**Comment by MightyPlaza** [comment]
@vaxerski why was this closed?
It's still happening. When a tiling window is closed the opacity of the snapshot starts at 1, unlike for floating windows which start at the current value

**Comment by vaxerski** [comment]
cuz account removed
