### ISSUE TITLE
Screen flashes black on actions randomly

### ISSUE THREAD

**Issue by SeanMcnabb** [hyprwm/Hyprland#859]
When running just about any action such as a keybind, the screen will flash black, almost as if it's the display refreshing or detecting a new input. It happens sometimes when I press my keybind for wofi, when I start any application, when I move the cursor to a different monitor, resizing a window, and pretty much anything else besides letting the cursor hover over a single application. 

I have a dual monitor setup, rx 6700xt graphics card. I have tested with a config for only using one monitor and have unplugged the second monitor (same exact monitor model, scale, refresh rate and resolution) but it still does the same thing. It happens maybe half of the time or more when I do anything besides keep focus on a single window.

I am running arch and have tried the git version without using AUR and receive the same results. I have tested with a couple of different kernels because I experienced a weird issue with linux 6.0  when awaking from sleep even in X but the behavior was the same in the other kernels as well. 

I have also tested building older versions of Hyperland back to the 0.14beta version. It happens on default config and with my minimally edited config.

Sway does not experience this same behavior.

I have also ran as a new user without any configs to see if something else may have been messing with it but it still does the same exact thing. It didn't crash so I'm not sure if there are any useful logs but if logs are needed, let me know and I can easily reproduce and get a log file attached.

**Comment by vaxerski** [comment]
I have the exact same card and have not seen this, neither has anyone else.

This, imho, has to be a driver bug, somehow. Overclocking / weird configuration / broken peripherals / some wacky configs.

**Comment by SeanMcnabb** [comment]
I don't have any overclocking, and have ran with fresh configs, but I'll give it a shot with a fresh arch install and report back

**Comment by SeanMcnabb** [comment]
So I have a fresh install and this still happens randomly. I installed dolphin, kate, firefox and alacritty to see what would happen. I don't have any strange configs going on and nothing special about my video card. No overclocking on anything and this doesn't happen on sway. There doesn't seem to be a rhyme or reason to it, just happens randomly when moving/resizing things or doing pretty much anything.

Here is a log of the time-frame where it happened I think 3 or 4 times. Not sure if this helps, but I really don't think its my system, as it's a fresh install and doing the exact same thing.
`
[LOG] Set keyboard focus to surface 8bf33840, with window name: COSTA RICA IN 4K 60fps HDR (ULTRA HD) - YouTube — Mozilla Firefox
[LOG] Keybind triggered, calling dispatcher (64, mouse:273, 0)
[LOG] Set keyboard focus to surface 8c11cba0, with window name: hyprland.log  — KWrite
[LOG] Set keyboard focus to surface 8c080680, with window name: 993106c348188a2f292c66fb5739867ab0566ea4_1665885133 — Dolphin
[LOG] Set keyboard focus to surface 8bf33840, with window name: COSTA RICA IN 4K 60fps HDR (ULTRA HD) - YouTube — Mozilla Firefox
[LOG] Keybind triggered, calling dispatcher (64, mouse:273, 0)
[LOG] Set keyboard focus to surface 8c080680, with window name: 993106c348188a2f292c66fb5739867ab0566ea4_1665885133 — Dolphin
[LOG] Keybind triggered, calling dispatcher (64, mouse:273, 0)
[LOG] Set keyboard focus to surface 8c11cba0, with window name: hyprland.log  — KWrite
[LOG] Set keyboard focus to surface 8bf33840, with window name: COSTA RICA IN 4K 60fps HDR (ULTRA HD) - YouTube — Mozilla Firefox
[LOG] Set keyboard focus to surface 8bdb5820, with window name: Screen flashes black on actions randomly · Issue #859 · hyprwm/Hyprland — Mozilla Firefox
[LOG] Set keyboard focus to surface 8c11cba0, with window name: hyprland.log  — KWrite
[LOG] Keybind triggered, calling dispatcher (64, mouse:273, 0)
[LOG] Set keyboard focus to surface 8bf33840, with window name: COSTA RICA IN 4K 60fps HDR (ULTRA HD) - YouTube — Mozilla Firefox
[LOG] New idle inhibitor registered
[LOG] Registered signal for owner 8c08e850: 8c167568 -> 8c08e860 (owner: IdleInhibitor)
[LOG] New idle inhibitor registered
[LOG] Registered signal for owner 8c1cddd0: 8c1c57d8 -> 8c1cdde0 (owner: IdleInhibitor)
[LOG] Set keyboard focus to surface 8c11cba0, with window name: hyprland.log  — KWrite
[LOG] Set keyboard focus to surface 8bf33840, with window name: COSTA RICA IN 4K 60fps HDR (ULTRA HD) - YouTube — Mozilla Firefox
[LOG] Callback 8c08e888 -> 8c08e880, IdleInhibitor removed.
[LOG] Destroyed an idleinhibitor
[LOG] Callback 8c1cde08 -> 8c1cde00, IdleInhibitor removed.
[LOG] Destroyed an idleinhibitor
[LOG] Set keyboard focus to surface 8c11cba0, with window name: hyprland.log  — KWrite
`

**Comment by SeanMcnabb** [comment]
Here is a video of it happening as well. I'm still not sure what would be causing this doesn't happen in any other WM on either X or wayland. Is there a specific vulkan driver I should be using or version of mesa? Right now I'm using vulkan-radeon and the mesa version for the arch repo.

https://drive.google.com/file/d/1kWHC7feaUUOPTnRfu7v0L2-HMZ4dtl9I/view?usp=sharing

**Comment by SeanMcnabb** [comment]
I was able to resolve this by replacing my HDMI cords with Displayport cords that support 4k@120hz.
