### ISSUE TITLE
Add protocol for getting mouse clicks outside window

### ISSUE THREAD

**Issue by Libadoxon** [hyprwm/Hyprland#8595]
### Description

Currently there are no real ways to implement a popup window in Wayland that closes when clicked outside of it because for security reasons Wayland doesn't provide such information. I think the security impact would be minimal at least if a window could know that a mouse click outside of it occurred.

**Comment by vaxerski** [comment]
this is just wrong https://wayland.app/protocols/xdg-shell#xdg_popup:request:grab

**Comment by Libadoxon** [comment]
Well that's awkward, I search like 2 months for something like this without ever stumbling about it. Well ty for the help I guess
