### ISSUE TITLE
(EE) could not connect to wayland server

### ISSUE THREAD

**Issue by jamstec0** [hyprwm/Hyprland#8599]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

Hyprland 0.45.0 built from branch main at commit cc38e7e18fd762d5cdb34d06335223b7d7874106  (config: don't overwrite errors in gradients).
Date: Sun Nov 24 14:53:36 2024
Tag: v0.45.0-61-gcc38e7e1, commits: 5494
built against aquamarine 0.5.0

flags set:
debug

System Information:
System name: Linux
Node name: alarm
Release: 6.1.75-rockchip-g5c43412639fd-dirty
Version: #1 SMP Tue Nov 19 14:16:35 UTC 2024

GPU information: 

os-release: NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo

plugins:
	unknown: not runtime

### Description

I installed Hyprland on Arch linux right after installation and ran Hyprland on a tty without editing the configuration. The desktop should have shown up, but all I got was a black screen.
The log shows (EE) could not connect to wayland server.
I thought it was the wayland server, so I tried sway, river, weston, (i3), etc., and they all output the screen normally, so I think it is a problem specific to hyprland.
As far as the log of WAYLAND_DEBUG=1 is concerned, it seems that wl_display is created, deleted, and created again repeatedly.
I even tried building the latest hyprland from git, but the result seems to be the same.
I have tried running it on weston gui as well as tty, but it crashes and doesn't seem to work. I will attach the logs of running river and weston,sway if needed.
How can i get this error resolved?

### How to reproduce

Sorry, I don't know how to do that.

### Crash reports, logs, images, videos

WAYLAND_DEBUG=1 Hyprland > hypr.log 2>&1
[hypr.log](https://github.com/user-attachments/files/17936412/hypr.log)
cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 1)/hyprlandd.log
[hyprlandd.log](https://github.com/user-attachments/files/17936444/hyprlandd.log)
bt -full
[gdb.txt](https://github.com/user-attachments/files/17936480/gdb.txt)
Just in case: hyprland in weston
[hyprland-weston.log](https://github.com/user-attachments/files/17936500/hyprland-weston.log)

**Comment by r3k2** [comment]
I have this issue after I upgraded in the last 4-5 days now is like is not using the GPU or something is going on obscrure everything is super slow, keystrokes, mouse, windows etc :( upgrading to git now see if it help

**Comment by Sim23F** [comment]
I have the same issue on Opensuse Tumbleweed
my error message is `(EE) could not connect to wayland server X serverKbdInputAssistNextgrou`

**Comment by r3k2** [comment]
I am suspecting is has something to do with vulkan,  because since I was not able to do any work I  tried to launch sway and  I know wlroots and hyprland are not in the same line anymore, it must be related since both use vulkan at least in my case with nvidia GPU, when I removed the WLR env variable to force vulkan into using egl  then sway run fine, of course hyprland still does not.. so is why im suspecting is an issue with aquamarine+vulkan+nvidia(maybe)

**Comment by Sim23F** [comment]
On OpenSUSE the issue appear after I update this list of packages to the current version:
`Mesa Mesa-KHR-devel Mesa-dri Mesa-gallium Mesa-libEGL-devel Mesa-libEGL1 Mesa-libGL1 Mesa-libGLESv3-devel Mesa-libglapi0 Mesa-libva gtk4-schema gtk4-tools lastlog2 libLLVM19 libblkid1 libfdisk1 libgbm1 libgtk-4-1 libgtksourceview-5-0 libjack0 liblastlog2-2 libmount1 libnetfilter_conntrack3 libnvme-mi1 libnvme1 libply-splash-core5 libply-splash-graphics5 libseat1 libsmartcols1 libsnmp40 libsoup-3_0-0 libtracker-sparql-3_0-0 libtree-sitter0_24 libuuid1 libwsutil16 openSUSE-release openSUSE-release-appliance-custom`

**Comment by r3k2** [comment]
hmm I am almost sure in my case I did reboot after Nov 13 but if it helps this is my latest update for mesa-*
```
ls -alh | grep "Nov" | grep mesa
-rw-r--r-- 1 root root   19M Nov 13 18:28 lib32-mesa-1:24.2.7-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root   119 Nov 13 18:28 lib32-mesa-1:24.2.7-1-x86_64.pkg.tar.zst.sig
-rw-r--r-- 1 root root   20M Nov 13 18:28 mesa-1:24.2.7-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root   119 Nov 13 18:28 mesa-1:24.2.7-1-x86_64.pkg.tar.zst.sig
```
Nov 13

**Comment by Sim23F** [comment]
For my case Hyprland works with Mesa version `24.2.7-393.1` and  breaks when I update to `24.3.0-394.1`
My GPU is not Nvidia btw, it's an integrated intel

**Comment by r3k2** [comment]
ok happy to report that in my case it was the new kernel, I downgraded to 6.11.9-arch1-1 from 6.12.1-arch* and problems and glitches are gone, the real issue not sure, must be something incompatible with the new kernel between mesa,vulkan,wayland and the compositors since according to this post on the arch forums it also happened in KDE https://bbs.archlinux.org/viewtopic.php?pid=2210324  hope this helps resolve it so we can upgrade kernel soon.

**Comment by jamstec0** [comment]
I reinstalled the OS and it worked correctly. The cause seems to be mesa(egl), which does not work if mesa egl does not work properly.

When using arch linux, I always have to try to get in from the toe to the mental picture, but I forgot to do that. Sorry for the lack of knowledge and for the trouble.

Finally... Long live Hyprland!
