### ISSUE TITLE
Update to xdg-shell v5

### ISSUE THREAD

**Issue by VexfulNiko** [hyprwm/Hyprland#862]
What the title says; update Hyprland to use the newest xdg-shell release (v5).

**Comment by NotAShelf** [comment]
Why, what are the benefits of doing so?

**Comment by vaxerski** [comment]
exactly, why?

**Comment by VexfulNiko** [comment]
Cc: @NotAShelf @vaxerski This would be useful for people making Wayland applications since the newest xdg shell fixes bugs and adds new compatability based features which makes maintaining Wayland applications much easier and makes UI design much more consistent (because of said new feature)

**Comment by vaxerski** [comment]
@fufexan can you test whether xdg shell 5 breaks anything? It's a matter of changing the ver from 4 to 5 in the ccompositor constructor for xdgsh

**Comment by fufexan** [comment]
Yea will test in a bit.

**Comment by VexfulNiko** [comment]
How did the test go? If you don't mind me asking

**Comment by fufexan** [comment]
No issue so far.

**Comment by vaxerski** [comment]
Will check myself after my lectures.

**Comment by vaxerski** [comment]
done in 1ccb0b5f96ad2bac353e1e6e9935a4021d9a43a7

**Comment by VexfulNiko** [comment]
Thank you!
