### ISSUE TITLE
Crash on an attempt to close  mpv fullscreen window

### ISSUE THREAD

**Issue by izmyname** [hyprwm/Hyprland#8628]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit 6d7544458d0fafcae410c1978a0cabce2fb4a346  (cleanup: use doLater instead of adding idle event handlers (8624)).
Date: Sun Dec 1 22:14:35 2024
Tag: v0.45.0-74-g6d754445, commits: 5507
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: archbtw
Release: 6.12.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:23 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.57.01  Thu Oct 10 12:29:05 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Hyprland crashes during an attempt to close fullscreened mpv window.

### How to reproduce

Open a videofile with mpv, fullscreen it with an mpv keybind (f), try to close it (q)

### Crash reports, logs, images, videos

[hyprlandCrashReport1347.txt](https://github.com/user-attachments/files/17978257/hyprlandCrashReport1347.txt)
[hyprlandCrashReport18776.txt](https://github.com/user-attachments/files/17978258/hyprlandCrashReport18776.txt)

**Comment by ikalco** [comment]
it's probably caused by latest commit, will fix later today

**Comment by izmyname** [comment]
> it's probably caused by latest commit, will fix later today

Also, I don't know whether it's related - but an attempt to exit hyprand session via `loginctl terminate-user $USER`, when there's a fullscreen window (fullscreen, 0) causes crash before actually exiting the compositor. Happens with any gui app 100% chance, and a terminal window 50%. Here are the logs for when firefox was on fullscreen
[hyprlandCrashReport38134.txt](https://github.com/user-attachments/files/17978816/hyprlandCrashReport38134.txt)

and foot terminal window
[hyprlandCrashReport39201.txt](https://github.com/user-attachments/files/17978820/hyprlandCrashReport39201.txt)

**Comment by izmyname** [comment]
**UPD:** Looks like it's not just fullscreened windows. Here's the crash upon exiting via loginctl command, when a foot window (not fullscreened) was focused. Visually, the compositor crashed in the middle of closing window animation.
[hyprlandCrashReport41459.txt](https://github.com/user-attachments/files/17979030/hyprlandCrashReport41459.txt)


Worth to mention, that closing non-mpv windows (fullscreen or not) with hyprland killactive keybind does not cause the crash

**Comment by ikalco** [comment]
try this [patch.txt](https://github.com/user-attachments/files/17986022/patch.txt)

**Comment by izmyname** [comment]
> try this [patch.txt](https://github.com/user-attachments/files/17986022/patch.txt)

loginctl terminate-session and exiting mpv don't crash the compositor for me

**Comment by blackxored** [comment]
I would also like to add that aside from the crashes (mine happens with looking glass), I also see way longer startup time for my session in general until I reverted back to d26439a0fe5594fb26d5a3c01571f9490a9a2d2c. Things like my second monitor activating, AGS bar loading, etc were significantly slower on that build.

**Comment by vaxerski** [comment]
git fix
