### ISSUE TITLE
:bulb: dynamic borders

### ISSUE THREAD

**Issue by Permafrozen** [hyprwm/Hyprland#8629]
### Description

The idea is, that borders behave a bit differently, for example when only one window is open, there is no border and it only appears when a second window is opened. That is one of such edge cases I can think of.

I found this script that does something similar: https://github.com/devadathanmb/hyprland-smart-borders

I feel like this maybe could be nice to have included, maybe as a option.

**Comment by soufhehe** [comment]
https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps

**Comment by Permafrozen** [comment]
oopos I feel silly now :( sowyyyyyyyyy
