### ISSUE TITLE
Some floating XWayland windows wrong sized

### ISSUE THREAD

**Issue by tagomaco** [hyprwm/Hyprland#863]
It is annoying that some XWayland applications (in my case citra-qt, teamspeak3) have floating windows displaying a size of 100, 30. By starting citra-qt with QT_QPA_PLATFORM=wayland its floating windows have however the right size. I don't want to manually resize them or set a window rule for each wrong sized window. Other compositors doesn't have this problem.

![xwayland](https://user-images.githubusercontent.com/80169692/196056058-5f2437f1-fca0-40b4-88a9-e2965fbd595c.png)
![wayland](https://user-images.githubusercontent.com/80169692/196056066-fb0fb65b-7075-4953-9ecb-8a8a4f0787df.png)

**Comment by fufexan** [comment]
Why not export `QT_QPA_PLATFORM=wayland` and have the programs run in wayland mode? That seems desirable to me.

**Comment by tagomaco** [comment]
Firstable, citra-qt has bugs in wayland where it crashes when switching workspaces and teamspeak3 for example has completely no wayland support. I can't run a 100% X free environment, so I simply use XWayland. Like I already said, other compositors (for example river) display these floating XWayland windows correctly.

**Comment by vaxerski** [comment]
can you give me an example of this in teamspeak 3? I have used it and haven't noticed issues.

**Comment by tagomaco** [comment]
If you mean the wayland support:
![no-wayland](https://user-images.githubusercontent.com/80169692/196147261-a654fb7e-08e6-4baf-9257-89f0708fee83.png)

Some wrong sized windows:

(1) Joining a server: 
![join-server](https://user-images.githubusercontent.com/80169692/196147463-d30a0772-3c92-4d03-a15b-abaacf168288.png)
-> resizes correctly when using shortly the bind for resizewindow
(2) Poking a user:
![poking](https://user-images.githubusercontent.com/80169692/196147524-8d558c7b-abd0-4c57-ba83-7c013b12270f.png)
-> 100,30 window

**Comment by vaxerski** [comment]
fixed in da4cfb9c32fecf2e5d2fa065c9e180a2bdec76a3
