### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by B1nus** [hyprwm/Hyprland#8630]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0

flags set:
debug

System Information:
System name: Linux:
Release: 6.6.63-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 15:39:56 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

### Description

Starting hyprland gives me a black screen. It does not respond to any keycombinations except for **WIN + M** for exiting hyprland. A window does appear if I start hyprland inside of KDE, but it's unresponsive. Starting it with sddm or through the linux console gives a black screen. I think this happened after I updated my system.

### How to reproduce

1. update your system
2. launch hyprland
3. cry

**Comment by vaxerski** [comment]
please use the search feature
