### ISSUE TITLE
How to disable Hyprland from calling NVIDIA graphics cards.

### ISSUE THREAD

**Issue by wxqwinner** [hyprwm/Hyprland#8640]
![image](https://github.com/user-attachments/assets/d41dec13-9a0a-431d-b512-eca08ecfc598)

I hope nvidia graphics cards are only used for calculations.

**Comment by izmyname** [comment]
https://github.com/izmyname/archlinux-backup/blob/main/etc%2Fudev%2Frules.d%2F80-nvidia.rules

`env = AQ_DRM_DEVICES,/dev/dri/cardx`

**Comment by wxqwinner** [comment]
@izmyname Cool,thanks.

**Comment by vaxerski** [comment]
not an issue and this is not a help forum, please use the discord or some other place
