### ISSUE TITLE
Unfocused window slowes down and lagging in the background(New issue: mouse stutters)

### ISSUE THREAD

**Issue by Noiidor** [hyprwm/Hyprland#8642]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

I have games/programs opened in one workspace, when im switching to another workspace they are slowing down in the background and FPS(in case of a game) drops drastically, and moreover its messes up in-game behavior(im guess because slower CPU cycles or smth). Important note: its NOT behavior of applications themselves, in KDE Plasma everything works fine. 

### How to reproduce

Open any game, start any long-running in-game task, switch to another workspace, everything almost froze while you were in different workspace.

**Comment by Noiidor** [comment]
P.S: KDE Plasma is also wayland, working fine

**Comment by vaxerski** [comment]
are you actually sure it's not the behavior of apps that KDE somehow tricks into not doing it?

Try sway

**Comment by Noiidor** [comment]
> are you actually sure it's not the behavior of apps that KDE somehow tricks into not doing it?
> 
> Try sway

Im completely sure that it is not the app behavior. It is online game and something like this is not acceptable.
I've searched online and found "renderunfocused" window rule. It may be solution for my issue but i cannot test is because i encountered even bigger issue.
Now in-game my mouse stutters and causing frame lags, game stutters only when im trying to move my mouse. Appeared after i updated from v0.42 to 0.45. Option "no_hardware_cursors" doesn't help.

**Comment by Noiidor** [comment]
Correction: updated from v0.41.2, not v0.42

**Comment by Noiidor** [comment]
Option "direct_scanout" solves issue with mouse stutters, but enables horrible rendering artifacts.

**Comment by Noiidor** [comment]
Closing due to likely solution by "renderunfocused", which i cannot test now and appearence of new issue with cursor.
