### ISSUE TITLE
Tabbing

### ISSUE THREAD

**Issue by mongugit333** [hyprwm/Hyprland#8650]
### Description

Qtile and i3 provide tabbing; Qtile has the tree concept where a specific window can be selected and i3 displays the various open windows at the top. With tabbing, one always know swhich windows are available and does not have to use the fullscreen feature. Will this be available in hyprland? So far, I am really liking hyprland, but miss this feature because I work with spreadsheets a lot. Thanks in advance.

**Comment by vaxerski** [comment]
rtfm
