### ISSUE TITLE
Program specific dpi

### ISSUE THREAD

**Issue by patrickaldis** [hyprwm/Hyprland#866]
The HiDPI experience is really nice,

However I have one program that isn't dpi-aware and doesnt respond to `GDK_SCALE` etc, is there a way I can specifiy to use the old 1x upscaling, by passing some environment vars or something?

I have:

```
exec-once=xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```
In my config.

Thanks for any help

**Comment by fufexan** [comment]
You have the `xprop` line in the config, but are your XWayland and Wlroots patched to support HiDPI XWL?

**Comment by patrickaldis** [comment]
yep. using the nix flake - I think it's patched automatically no?

**Comment by fufexan** [comment]
Yes. If a program has no way of controlling its scale, then I'm not sure what measure you can take to force it.

**Comment by patrickaldis** [comment]
Is there no way I can revert to the old blurry upscaling (without the wlroots patches) just for this specific program?

**Comment by vaxerski** [comment]
native wayland - no. XWayland - most likely no.

**Comment by fufexan** [comment]
> Is there no way I can revert to the old blurry upscaling (without the wlroots patches) just for this specific program?

Use the `hyprland-nohidpi` package.

**Comment by vaxerski** [comment]
That will revert it for all XWayland apps, though.

**Comment by vaxerski** [comment]
closing. I am afraid this is not possible and it's not our fault.
