### ISSUE TITLE
Hyprland Crashes after Mesa update to 24.3.1-3

### ISSUE THREAD

**Issue by degobbis** [hyprwm/Hyprland#8666]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit b1e5cc66bdb20b002c93479490c3a317552210b3  (core: Add support for hyprqtutils' update screen (8651)).
Date: Fri Dec 6 14:45:02 2024
Tag: v0.45.0-88-gb1e5cc66, commits: 5521
built against:
 aquamarine 0.5.0
 hyprlang 0.5.3
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: FRAMEWORK16
Release: 6.12.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:23 +0000


GPU information: 
c2:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
  hyprbars by Vaxry ver 1.0
  split-monitor-workspaces by Duckonaut ver 1.2.0

```
Used configuration from PKG: `ml4w-hyprland 2.9.7.0-1`
</details>

### Description

Found this issue #8560 but my error from LOG are different:
```sh
[LOG] [11:45:36.336652947] Running on DRMFD: 38
[LOG] [11:45:36.336696057] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Creating the CHyprOpenGLImpl!
[LOG] [11:45:36.336712398] Supported EGL extensions: (16) EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_explicit_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
[LOG] [11:45:36.337271754] eglDeviceFromDRMFD: Using device /dev/dri/card1
```
Downgrade to mesa 24.2.7-1 works fine.

### How to reproduce

Update to latest mesa 

### Crash reports, logs, images, videos
[hyprlandCrashReport236.txt](https://github.com/user-attachments/files/18049439/hyprlandCrashReport236.txt)
[hyprland.log](https://github.com/user-attachments/files/18048188/hyprland.log)

**Comment by ikalco** [comment]
can you give a debug stacktrace of crash
https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by vaxerski** [comment]
\>Crashes
\>no crash report provided

mfw

**Comment by degobbis** [comment]
Is this what you mean?
[gdb.txt](https://github.com/user-attachments/files/18049241/gdb.txt)

**Comment by degobbis** [comment]
> >Crashes
> >no crash report provided

Crash report is provided in my initial post > hyprland.log

**Comment by Pummelfisch** [comment]
Had the same issue earlier today. With the current package upgrade of linux and nvidia this got fixed for me.

**Comment by degobbis** [comment]
@Pummelfisch 
Thanks for the hint, I just received the latest kernel 6.12.3-zen1-1 for updating, but unfortunately it did not solve the problem

**Comment by vaxerski** [comment]
> Crash report is provided in my initial post > hyprland.log

that is not a crash report

**Comment by ikalco** [comment]
yeah that's definitely a driver bug, shouldn't be crashing inside eglInitialize

archlinux packagers released 24.3.1-3 20 min ago though and it probably fixes this

**Comment by degobbis** [comment]
Thanks for the hint, as soon as I get the package offered for installation I will give feedback if it has fixed the problem.

**Comment by bd-was-taken** [comment]
any updates guys??

i have been facing a similar issue as well

**Comment by degobbis** [comment]
@bd-was-taken 
I am still waiting for the update of version 24.3.1-3 of the mesa package zo test.
In the meantime, I'm currently using version 24.2.7-1, which is still working.

**Comment by bd-was-taken** [comment]
I have downgraded the mesa packages to 24.2.7-1 as well
But the issue still persists

Is it a kernel issue or could it also be because of my dGPU

**Comment by bd-was-taken** [comment]
> @bd-was-taken I am still waiting for the update of version 24.3.1-3 of the mesa package to test it. In the meantime, I'm currently using version 24.2.7-1, which is still working.



> I have downgraded the mesa packages to 24.2.7-1 as well But the issue still persists
> 
> Is it a kernel issue or could it also be because of my dGPU

**Comment by bd-was-taken** [comment]
> @bd-was-taken I am still waiting for the update of version 24.3.1-3 of the mesa package to test it. In the meantime, I'm currently using version 24.2.7-1, which is still working.

I have downgraded to mesa 24.2.7-1 as well, but the issue still persists

Could it also be because of the dGPU

**Comment by degobbis** [comment]
I use an iGPU from AMD, if you have an NVIDIA the problem may be different.

**Comment by bd-was-taken** [comment]
@degobbis well the issue started because of the mesa driver update as everything was fine till the update

But i'm not completely blaming on the update as well because of my setup

**Comment by ikalco** [comment]
@bd-was-taken if updating or downgrading mesa versions fixes the crash then it's almost definitely a mesa bug
but to be sure can you give a crashReport

**Comment by degobbis** [comment]
Today I updated Hyprland with the chaotic-aur packages, and also updated mesa to 1:24.3.1-3, unfortunately without success.
[hyprlandCrashReport2376.txt](https://github.com/user-attachments/files/18083113/hyprlandCrashReport2376.txt)

**Comment by vaxerski** [comment]
looks like a mesa bug to me

**Comment by degobbis** [comment]
For the sake of interest, is it necessary to keep the mesa package up to date in order to use Hyprland?

**Comment by degobbis** [comment]
Found this solution https://github.com/mylinuxforwork/dotfiles/issues/515 
After removing `env = LIBGL_ALWAYS_SOFTWARE,1` from my configuration, all works fine again with the latest mesa package.
