### ISSUE TITLE
no_gaps_when_only

### ISSUE THREAD

**Issue by bryant-the-coder** [hyprwm/Hyprland#8667]
I recently updated hyprland. Then there is this error where it says `no_gaps_when_only` is not valid. May i ask what are the other options to enable `no_gaps_when_only` feature? I have went through the wiki several times but still can't find any solution

**Comment by Aqa-Ib** [comment]
https://github.com/hyprwm/Hyprland/releases/tag/v0.45.0

**Comment by 11xx** [comment]
It got nuked: [hyprwm/Hyprland/Pull Request #8072/layouts: Nuke no_gaps_when_only by vaxerski](https://github.com/hyprwm/Hyprland/pull/8072).

Replacement for `no_gaps_when_only` are normal workspace rules:

    workspace = w[t1], gapsin:0, gapsout:0, border:1
    workspace = w[tg1], gapsin:0, gapsout:0, border:1
    workspace = f[1], gapsin:0, gapsout:0, border:1

where `gapsout:0` removes the gaps, `border:1` still leaves borders.

**Comment by vaxerski** [comment]
oh no! totally not like the release notes explicitly state what to do!

![image](https://github.com/user-attachments/assets/e286f49c-941e-41e5-9f80-7ce8ca827f37)

**Comment by bryant-the-coder** [comment]
Thanks!!!
