### ISSUE TITLE
Window rule checking size of windows

### ISSUE THREAD

**Issue by SeanMcnabb** [hyprwm/Hyprland#867]
I couldn't find anything similar to this on the wiki, but it would be nice to be able to use the size of a window as a rule. I like to remove borders/gaps for windows that are within like 5% of my screens dimensions which makes them look a little better when they are alone on the screen (imo).

**Comment by SeanMcnabb** [comment]
I don't think this use case is needed, it looks like no_gaps_when_only is the option I was looking for. Not sure if this would benefit others in some way to have this option though

**Comment by vaxerski** [comment]
no, doesnt make sense. Also, syntax-wise would be a nightmare
