### ISSUE TITLE
you can't switch layouts aka from english us to arabic while using kanata

### ISSUE THREAD

**Issue by beh-10257** [hyprwm/Hyprland#8671]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.45.0 built from branch  at commit b1e5cc66bdb20b002c93479490c3a317552210b3  ().
Date: 2024-12-06
Tag: @TAG@, commits: 
built against:
 aquamarine 0.5.0
 hyprlang 0.5.3
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: laptop
Release: 6.12.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Nov 22 14:30:26 UTC 2024


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20241203.566e53c"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"


plugins:
	unknown: not runtime
```

</details>

### Description

use kanata try to switch layout to arabic even switching to colemak doesn't work so yeah help

### How to reproduce

use kanata

try to switch layout

### Crash reports, logs, images, videos

maybe this is gonna be helpful

https://github.com/jtroo/kanata/discussions/474#discussioncomment-11492622

thats all thanks

**Comment by rszyma** [comment]
Listed steps are incomplete, what command exactly you're trying to use to switch layouts? 

Have you actually checked if it doesn't happen without running kanata?

**Comment by beh-10257** [comment]
@rszyma thanks this really helped
I was using ```hyprctl switchxkblayout at-translated-set-2-keyboard next``` which is my physical keyboard
what I should use is ```hyprctl switchxkblayout kanata next```
thanks a lot
