### ISSUE TITLE
Enhance Keymapping Syntax To Faciliated Defining Nested Submaps within Submaps

### ISSUE THREAD

**Issue by Nicknamely** [hyprwm/Hyprland#8672]
### Description

Currently, in Hyprland's keybinding configuration, it seems impossible to define multiple submaps within a submap. For instance, if I have a submap at level 1, I cannot have more than one distinct submap at level 2.

This limitation makes it difficult to create complex keybinding hierarchies, such as emulating (Neo)vim-like leader shortcuts, where pressing a leader key opens one submap of options, and selecting from those options opens additional nested submaps.

Below is an example that demonstrates the issue.

```bash
#Testing nested submap

# Goal: Implement (Neo)vim-like shortcuts
# Press $mainMod + P -> access quickPrograms submap (level 1)
# Inside utilities, have two nested submaps (level 2): monitoring and cmdTools (.

bind = $mainMod, P, submap, Utils
  submap = Utils # level 1 submap
  bind = , U, submap, monitoring
  bind = , escape, submap, reset
  # want to have another lvl 1 submap here but it seems impossible :( 
  submap = reset
    submap = monitoring # level 2 submap
    # Add shorcut here
    bind = , B, exec, kitty btop
    bind = , B, submap, reset
    # ...
    bind = , escape, submap, reset
    submap = reset

```

**Comment by vaxerski** [comment]
![image](https://github.com/user-attachments/assets/82e3fb62-6846-4a2f-8526-2a8c7bea78c8)
works for me.

**Comment by vaxerski** [comment]
I don't understand what you are trying to do that isn't possible.

You can't "nest" submaps as something like this doesn't exist. You move from one to another.
```
SUBMAP1 -> SUBMAP2
        -> SUBMAP3
```
What's the issue?

**Comment by Nicknamely** [comment]
Submap 1
|-Submap 1
|  |-Bind 1
|  |-Bind 2
|  |- ...
|-Submap 2
|  |-Bind 1
|  |- ...
|-Submap 3
|-Submap 4



I want to be able to move from Submap1-1 to Submap1 and from there go to submap 2 then Bind 1. 

And have a Bind to return to global  (reset all)


Is it possible ?

**Comment by vaxerski** [comment]
yes, I don't see why not.

```
bind = , B, submap, reset
```
instead of reset, go to `submap1`?

**Comment by davc0n** [comment]
Maybe you can start from this example:

```
bind = $mainMod, P, submap, utils
submap = utils

bind = , Q, exec, $example

# monitoring
    bind = , U, submap, monitoring
    submap = monitoring
    
    bind = , W, exec, $example
    
    bind = , B, exec, kitty btop
    bind = , B, submap, utils
    
    bind = SHIFT, escape, submap, reset
    bind =      , escape, submap, utils
    submap = utils
# /monitoring

# cmdTools
    bind = , I, submap, cmdTools
    submap = cmdTools
    
    bind = , E, exec, $example
    
    bind = SHIFT, escape, submap, reset
    bind =      , escape, submap, utils
    submap = utils
# /cmdTools

bind = , escape, submap, reset
submap = reset
```

**Comment by vaxerski** [comment]
I am closing this, I don't see anything not possible here

**Comment by Nicknamely** [comment]
Yeah, I think you should. 
Here what i have done so far
![image](https://github.com/user-attachments/assets/01216ef0-7f39-4b99-b0e2-6d04374259a5)
By the way, can I just have one `submap = reset` at the end and still expect it to work?

**Comment by davc0n** [comment]
Idk, just try it out.
