### ISSUE TITLE
Warp back to old cursor position when coming back from pen focus

### ISSUE THREAD

**Issue by caffeine01** [hyprwm/Hyprland#8675]
### Description

I use an HP Envy x360 2-in-1 as my daily driver for work, creative shit, gaming etc. I have spent quite some time setting up hyprland to work such that I can have three different configurations for my needs:

1. Internal display (eDP-1 built in), 6 workspaces

2. External display, the 6 workspaces are moved from the internal to the external display and the internal display is off. This gets triggered when the lid is closed and the external monitor is plugged in.

3. Dual display, the main 6 workspaces are moved to the external display and i let hyprland create a workspace on my laptops screen, I only really use this mode when im making notes in xournalpp but i also like to do other things on it sometimes too.

Now, the problem is that when i use the pen input (which is bound to eDP-1), the cursor is moved as well. Now while that sounds normal as fuck, what i would like to happen is that i can use my pen or touch input on my laptop and then move my mouse and have the cursor back to where it was before i used the pen/touchscreen.

Some related things so you can get a better picture:
https://github.com/swaywm/sway/issues/1054
https://github.com/swaywm/wlroots/issues/351

**Comment by vaxerski** [comment]
that's completely unrelated to multi-seat or whatever. Can be just hacked in by adding an option to remember cursor pos before pen and warp on non-pen input.

**Comment by caffeine01** [comment]
copied title from post i thought was related, by no means am i an expert in any of this lol

**Comment by vaxerski** [comment]
No-one expects that from you, don't worry, that's why I edited the title.

**Comment by caffeine01** [comment]
okay thank u mr hyprland :)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/18136386/patch.txt)
try this. Turn on `cursor:warp_back_after_non_mouse_input`

**Comment by caffeine01** [comment]
@vaxerski it works!
However, when i right click with my mouse i am unable to move my cursor with my mouse anymore.

**Comment by vaxerski** [comment]
uhh... what?

**Comment by caffeine01** [comment]
Like, its weird, if i have the patch loaded, my right click causes mouse movement to become unresponsive until i do another pen/touch input.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/18140915/patch.txt)
try this (new aptch)

**Comment by caffeine01** [comment]
Will do, currently doing work so allow me some time.

**Comment by caffeine01** [comment]
Aha, doesn't work for scroll events. E.g. if i have my mouse on a web page, and then use my pen input on another monitor, and then don't move my mouse but scroll, it warps my mouse cursor to the pen input and scrolls there. Ideally it would not do this.

**Comment by caffeine01** [comment]
Never mind it stopped doing that?

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/18141661/patch.txt)

**Comment by caffeine01** [comment]
works! again, gimme like an hour of usage and ill let yk if anything is fucked up or not. this seems like it should be good tho.

**Comment by caffeine01** [comment]
ok so not really a problem more of an aesthetic thing but i feel as though the cursor icon should be reset upon warp, for example if my cursor was on a web page and displayed the funny 4-way arrow thing for navigating an image, if i then moved my cursor with the pen on my laptop to another screen the cursor stays as the previous one.

**Comment by vaxerski** [comment]
"something that updates it" being...? Just moving it?

**Comment by caffeine01** [comment]
ill show you what i mean

**Comment by caffeine01** [comment]
https://github.com/user-attachments/assets/e0fa95d4-b392-473b-b1ea-19128178a5f4

**Comment by caffeine01** [comment]
My touch input is also sometimes interpreted as mouse input, but thats probably a separate issue.

**Comment by vaxerski** [comment]
cosmetic tbh, I think it might be because we are missing some motion event there to the app, or maybe not. I'll just commit it in this state, good enough tbh

**Comment by caffeine01** [comment]
> cosmetic tbh, I think it might be because we are missing some motion event there to the app, or maybe not. I'll just commit it in this state, good enough tbh

yea, good enough, no other issues.
Thank you!
