### ISSUE TITLE
Hyprland is suddenly failing to create a backend

### ISSUE THREAD

**Issue by Eridith** [hyprwm/Hyprland#8676]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Uncertain

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit c106f454c136ecca47f84c659c58e19670050412  (CI/Nix: temporarily disable cross build).
Date: Sat Dec 7 12:01:32 2024
Tag: v0.45.0-91-gc106f454, commits: 5524
built against:
 aquamarine 0.5.0
 hyprlang 0.5.3
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1

flags set:
debug

System Information:
System name: Linux
Node name: Sentinel
Release: 6.12.0-zen1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Wed, 20 Nov 2024 22:39:20 +0000
GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080 Ti] [10de:2208] (rev a1) (prog-if 00 [VGA controller])
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64

os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:
               unknown: not runtime
```

</details>

### Description

As of today, launching Hyprland against the most recent build no longer seems to work. This configuration has not had issues running Hyprland all year, so it would not have anything to do with Nvidia.

I have verified all dependancies are present (including the newest hyprgraphics repo) and have checked to ensure that all system packages are up to date.

After launching the program, it crashes before it can even leave the tty and begin drawing the screen.

### How to reproduce

Launch Hyprland with the listed package, kernel, and driver versions.

### Crash reports, logs, images, videos

[hyprlandCrashReport12076.txt](https://github.com/user-attachments/files/18050526/hyprlandCrashReport12076.txt)

**Comment by Eridith** [comment]
One thing I should add is that after trying to build from source again, I'm noticing that the hyprland-protocols (>=0.4.0) package is not present when building Hyprland. This seems like it would be a breaking condition, but I would like to get confirmation on that. I've tried to clone the repository for hyprland-protocols, but I don't see a way to build the package from there.

Just a potential lead that I thought should be mentioned.

**Comment by BeauTaapken** [comment]
I seem to have the same issue as you, just with the normal upstream kernel. Maybe the report i have can help resolving the issues. Mine just doesn't seem to generate a crash report.

https://github.com/hyprwm/Hyprland/issues/8680#issue-2725417575

**Comment by Eridith** [comment]
[hyprlandCrashReport8573.txt](https://github.com/user-attachments/files/18054630/hyprlandCrashReport8573.txt)
Here is the most recent crash report after rebuilding all of the hypr-suite from source.

In summary, wl_display_connect fails, and aquamarine is unable to create a GBM Allocator/gbm fails to create a device.

Are there any potential culprits for this?
I'm noting that Aquamarine starts a backend for /dev/dri/card0 (which should be the Nvidia GPU) but mentions it is using an i915 driver.
I am not sure whether that is the correct behavior for it, but hopefully there is a relatively simple fix for it that I'm not seeing.

**Comment by Eridith** [comment]
SOLUTION:
"Downgrading" Linux-Zen kernel from 6.12.0 to 6.12.3 resolved the issue. It seems like there was an issue that was introduced in that older version that was patched out in the newer version.

Very odd that the update wasn't available by using pacman -Syu though.
