### ISSUE TITLE
Include Discord Canary in Hyprland Wiki

### ISSUE THREAD

**Issue by spencer-thompson** [hyprwm/Hyprland#8688]
### Description

[Discord Canary](https://support.discord.com/hc/en-us/articles/360035675191-Discord-Testing-Clients) runs like a charm on Wayland. I am on Arch, and after following the wiki with "Must Have", screen sharing works out of the box, and performance is excellent. I can open a pull request if needed.

**Comment by vaxerski** [comment]
please move to the wiki repo. This is the wrong place
