### ISSUE TITLE
Can set nvidia as primary gpu in dual monitor env on laptop.

### ISSUE THREAD

**Issue by kimsoso** [hyprwm/Hyprland#8709]
### Description

According to the official setting recommendation, I use intel as the main graphics card, but the system doesn't run smoothly, however I can't turn off the built-in graphics card in the bios.

I used to use gnome,add /usr/lib/udev/rules.d/61-mutter-primary-gpu.rules in gnome and set the following:
ENV{DEVNAME}=="/dev/dri/card1", TAG+="mutter-device-preferred-primary"

so that all the rendering work is done by nvidia, and intel is only used as a display device, and then you get a very smooth running environment. 

I don't know if there is such a setting in hyprland.

**Comment by vaxerski** [comment]
> so that all the rendering work is done by nvidia, and intel is only used as a display device, and then you get a very smooth running environment.

That is physically not possible.
