### ISSUE TITLE
Fullscreen in window only

### ISSUE THREAD

**Issue by jiiiijiij** [hyprwm/Hyprland#871]
A config option to force all apps on workspace to go fullscreen inside the window. Then the user will decided which app their want to really fullscreen. I only see option to rule specific app to use fullscreen.
Example is this youtube fullscreen.
![jjjj](https://user-images.githubusercontent.com/115423672/196413262-45fff18d-01bd-48c3-8cf7-f7e75a53c72c.png)

**Comment by vaxerski** [comment]
what? In english please, I don't understand

**Comment by MahouShoujoMivutilde** [comment]
He might have meant [fakefullscreen](https://dwm.suckless.org/patches/fakefullscreen/) type of thing, idk.

It's like `fullscreen 0`, the app goes full screen _mode_ (e.g. chromium will hide tabs etc), but it is contained within its own window and the window itself _doesn't_ go full screen.

**Comment by vaxerski** [comment]
oh ok

**Comment by vaxerski** [comment]
cool youtuber you watching there

**Comment by Dickby** [comment]
@jiiiijiij I opened an issue with the same wish before (which was rejected).
Your browser might have the option to limit fullscreen to the browser window.
I use qutebrowser the option there is called "content.fullscreen.window".
For chrome the add-on fullscreen-anything might help.
@vaxerski I still think this would be a nice addition to hyprland.

**Comment by vaxerski** [comment]
added in cb4f7482269664dd20c373eef5d862a770df1643

**Comment by H0yVoy** [comment]
Thx for picking it up so quickly!

Could you elaborate on the expected behavior of this?
I observe the following:
fullscreen keybinding:
- any window toggles fullscreen, covers all other windows

fakefullscreen keybinding:
-  no effect on some windows; e.g. foot terminal (probably doesn't have a fullscreen function)
- identical to fullscreen keybinding on other windows e.g. firefox toggles fullscreen, covers all other windows

From the thread above I would expect firefox in the second case to 'go fullscreen' without covering other windows. 

Am I doing something wrong here? Or did I misinterpret something?

**Comment by vaxerski** [comment]
only tested chrome and it seemed to work.

**Comment by vaxerski** [comment]
chromium in wayland works perfectly fine.

As for firefox, yeah it seems to send its own events, will see what I can do bout those.

**Comment by ItsDrike** [comment]
> chromium in wayland works perfectly fine.

Indeed, it does. I was running chromium over XWayland though, and that's when I've seen the issue.

**Comment by vaxerski** [comment]
for the love of god dont

**Comment by ItsDrike** [comment]
Yeah, that's fair. But still, it should work on apps running through XWayland in general.

**Comment by vaxerski** [comment]
fixed in 461fab0f27e4913993c6321625b343537aba1bdf

one thing that I noticed is that firefox will use the monitor's size in fullscreen (in some cases, for some reason) regardless of the window size, so fullscreen content may be cropped. (e.g. youtube videos)

**Comment by nativerv** [comment]
> one thing that I noticed is that firefox will use the monitor's size in fullscreen (in some cases, for some reason) regardless of the window size, so fullscreen content may be cropped. (e.g. youtube videos)

This is actually the same behavior that i had on xmonad, but the other way around for some reason (chromium was getting cropped, firefox was not), and the same (hacky) fix works in hyprland: resize window one pixel and back again in an event hook.
https://xmonad.github.io/xmonad-docs/xmonad-contrib/XMonad-Util-Hacks.html
https://xmonad.github.io/xmonad-docs/xmonad-contrib/src/XMonad.Util.Hacks.html#windowedFullscreenFixEventHook

> windows will now not be allowed to change their fullscreen state if fakefullscreen is active for them. only you can with a manual keybind.

And this is preventing me implementing the same hack for hyprland with a `socket2` script.

Speaking of scripting, i have questions on now to implement this and other things, but they would get pretty long and off topic, so i'll create a discussion thread

Back to the `fakefullscreen` though, i've found that toggling it on an mpv window with `--force-window=immediate` isn't preventing it from going fullscreen. I don't know if this is a separate issue from #1375 or not, but seems like one.
