### ISSUE TITLE
Hyprland shows blank screen on pinebook pro

### ISSUE THREAD

**Issue by Dev380** [hyprwm/Hyprland#8716]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
(Manually typing because can't get it to start)
Hyprland 0.45.2 commit 12f9a0d
Aquamarine 0.5.0
Flags: debug
Kernel: 6.13.3
NixOS version: 25.05.20242211.5d67ea6
Plugins: none
```

</details>

### Description

On nixos-unstable, Hyprland shows nothing forever on pinebook pro. Switching to another tty and back turns the screen on at least (but still black) and shows the default cursor (but immovable). I tried deleting my hyprland.conf, using uwsm and not using it and using the home-manager module and neither of them did anything. I'm using the same config as my other computer (which works fine) and programs.hyprland.enable is on. I'm using the pbp hardware overlay. Strangely, all my exec-once programs seem to have been run successfully in the log.
I haven't found anyone else using the pbp with the same issue, and [this config](https://github.com/adobrich/nixos-config/tree/d13ccd77c81aee767fae2170f5376079f526bf05) I found with github search seems to imply that it was working on pbp 5 months ago out of the box, without doing any special configuration to get it working? (Edit: also [this](https://www.lorenzobettini.it/2024/10/hyprland-endeavouros-on-a-pinebook-pro/) blog post says hyprland worked on endeavouros in October)

### How to reproduce

1) Install Hyprland using programs.hyprland.enable = true with systemd integration on on nixos-unstable and empty hyprland.conf.
2) Launched Hyprland
3) Observe screen not on
4) Switch to other tty and back and see screen turning on with a frozen cursor

### Crash reports, logs, images, videos

Log file (no crash so I killed it from another tty at the end): [XF1P.log.txt](https://github.com/user-attachments/files/18137772/XF1P.log.txt)

**Comment by vaxerski** [comment]
Your driver doesn't allow aquamarine to start a backend

```
[ERR] [AQ] CDRMRenderer: fail, eglCreateContext failed
```

if you want to add support for rockchip to aquamarine, feel free. I won't.
