### ISSUE TITLE
Drop shadow breaks blurls

### ISSUE THREAD

**Issue by autofool** [hyprwm/Hyprland#872]
Installed from AUR hyprland-git
I'm using eww as example. I have seen this behaviour with other transparent layer shells too.

### Steps to reproduce:
 1. Set blurls=gtk-layer-shell to blur eww window.
 2. set some active border thickness and color in Hyprland config. Also enable blur.
 4. In eww config set window stacking to 'fg' or 'overlay' and exclusive to 'false'. Set background transparent in scss.
 5. open eww window and some normal windows.
 
### Expected outcome:
  eww window should have blur from opened windows from background.

### Noted outcome:
  eww window does have blur but border of active window is too sharp. Its like blur is ignoring active window border.

![blur](https://user-images.githubusercontent.com/50569653/196450016-3b622798-d377-4793-92eb-59b15f0297a2.png)

**Comment by fufexan** [comment]
I think you need to increase the passes. The top one is the same, but the color is closer to the background so it isn't as noticeable.

**Comment by autofool** [comment]
Okay I tried setting both borders same yet active border is still a bit sharper.

![blur](https://user-images.githubusercontent.com/50569653/196460748-1674ba32-2514-4b1d-b391-e393cba063c0.png)

**Comment by fufexan** [comment]
It's not sharper, it's just the drop shadows creating higher contrast.

**Comment by autofool** [comment]
Isn't that contrast bleeding into actual window where there's not shadow? Is it intended behavior?

**Comment by fufexan** [comment]
Contrast isn't bleeding. Contrast is just the higher difference between 2 colors that make one of them appear brighter.
So I don't really understand the question.

**Comment by autofool** [comment]
I don't know. Currently my blur is set to size to 5 and passes to 3. Even if shadow should add some contrast, aren't windows just way sharper?

**Comment by autofool** [comment]
For example check this screen shot, same configs
no shadow:
![blur](https://user-images.githubusercontent.com/50569653/196465290-7137d038-2672-4bcc-b10f-6e7058effb5a.png)

with shdaow:
![blur](https://user-images.githubusercontent.com/50569653/196465459-58145df6-3e49-4d7d-a2ea-6bffbd497814.png)

I can actually make out text in the white area which should not be affected by shadow right?

**Comment by fufexan** [comment]
Something *is wrong*. The shadow shouldn't influence the blur.

**Comment by autofool** [comment]
Should I open another issue for this?

**Comment by fufexan** [comment]
No.

**Comment by autofool** [comment]
This behavior is like what you get when you set blur_ignore_opacity=false and set window_opacity.

**Comment by autofool** [comment]
This behavior is like what you get when you set blur_ignore_opacity=false and set window_opacity.

**Comment by vaxerski** [comment]
finally fixed 6c10c384813890ed137f73ee79452cbe8c6f1dca :)
