### ISSUE TITLE
warn user when the same key is set for multiple binds

### ISSUE THREAD

**Issue by nhasian** [hyprwm/Hyprland#8723]
### Description

As a user, when editing the hyprland.conf configuration file, I would like to receive a notification if the same key has been set for multiple keybinds.

For example:

```
bind = $mainMod, V, togglefloating,
bind = $mainMod, V, $menu,
```

After hyprland.conf has been saved and automatically reloaded, a warning message could appear, for example:

```
hyprctl notify 0 10000 "rgb(ff0000)" "fontsize:35  Key V is used in multiple keybinds"
```

**Comment by izmyname** [comment]
Might be a problem in situations, where reusing the same keybind is intentional. For example, a use one keybind for switching keyboard layout and triggering a notification script and I don't want to see a warning message every time, I reload my config.

**Comment by vaxerski** [comment]
No, this is completely valid and widely used. You can make your own parser for checking that.
