### ISSUE TITLE
Crash on enabling plugins in Kate-Editor

### ISSUE THREAD

**Issue by omagdy7** [hyprwm/Hyprland#8727]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

Hyprland 0.45.0 built from branch main at commit 92186898c0ca1b3f72922b72c4af1723f0d9b888  (version: add link versions for other utils (8619)).
Date: Mon Dec 2 17:31:22 2024
Tag: v0.45.0-76-g92186898, commits: 5509
built against:
 aquamarine 0.5.0
 hyprlang 0.5.3
 hyprutils 0.2.6
 hyprcursor 0.1.10

flags set:
debug

System Information:
System name: Linux
Node name: omagdy
Release: 6.12.1-zen1-1-zen

GPU information: 
1c:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] [10de:1f08] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.57.01  Thu Oct 10 12:29:05 UTC 2024

os-release: NAME=ArcoLinux
ID=arcolinux
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://arcolinux.info/"
SUPPORT_URL="https://arcolinuxforum.com/"
BUG_REPORT_URL="https://github.com/arcolinux"
LOGO=arcolinux-hello

plugins:

======Config-Start======

Config File: /home/omar/.config/hypr/hyprland.conf: Read Succeeded

$mainMod = SUPER
$localBin = $HOME/.local/bin
$scriptsDir = $HOME/.config/hypr/scripts
$hyprDir = $HOME/.config/hypr
$term = alacritty
$menu = $scriptsDir/menu
$fullmenu = $scriptsDir/fullmenu
$volume = $scriptsDir/volume
$backlight = $scriptsDir/brightness
$screenshot = $scriptsDir/screenshot
$lock = $scriptsDir/lockscreen
$colorpicker = $scriptsDir/colorpicker
$wofi_beats = $scriptsDir/wofi-beats
$files = thunar
$browser = brave
$editor = nvim

env = XCURSOR_SIZE,24

exec-once = $scriptsDir/startup
exec-once = swaybg -m fill -i $HOME/Pictures/wallpapers/0465.jpg
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $scriptsDir/portal

exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $term
exec-once = [workspace 3 silent] spotify
exec-once = [workspace 4 silent] ticktick
exec-once = [workspace 5 silent] obsidian

windowrulev2=noblur,class:^()$,title:^()$

input {
  kb_layout = us,eg

  kb_options = grp:alt_shift_toggle, caps:escape

  kb_model =
  kb_rules =

  follow_mouse = 1
  numlock_by_default = 1

  touchpad {
    natural_scroll = true
    tap-to-click = true
    drag_lock = true
    disable_while_typing = true
  }

}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
}

binds {
  workspace_back_and_forth = false
}

general {

  gaps_in = 2
  gaps_out = 4
  border_size = 3

  col.active_border = rgba(fa282dEE)
  col.inactive_border = rgba(414868aa)

  layout = master
}

decoration {

    rounding = 4

    blur {
        enabled = true
        size = 1
        passes = 2
    }

    shadow {
      enabled = true
      range = 4
      render_power = 3
      color = rgba(1a1a1aee)
    }
}

blurls = waybar

animations {
  enabled = true

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05

  animation = windows, 1, 3, myBezier
  animation = windowsOut, 1, 3, default, popin 80%
  animation = border, 1, 5, default
  animation = fade, 1, 3, default
  animation = workspaces, 1, 3, default
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
  mfact = 0.5
}

gestures {
  workspace_swipe = false
  workspace_swipe_fingers = 3
}

windowrule = float, nlogout

windowrulev2 = tile, class:^(Spotify)$

windowrulev2 = animation popin, class:^(update)$, title:^(update)$
windowrulev2 = float, class:^(update)$, title:^(update)$
windowrulev2 = size 60% 50%, class:^(update)$, title:^(update)$
windowrulev2 = center, class:^(update)$, title:^(update)$

windowrulev2 = float, class:^(clock)$, title:^(clock)$
windowrulev2 = size 33% 27%, class:^(clock)$, title:^(clock)$
windowrulev2 = center, class:^(clock)$, title:^(clock)$

bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod SHIFT, D, exec, $fullmenu
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, exec, $files
bind = $mainMod SHIFT, Space, togglefloating
bind = $mainMod, C, killactive,
bind = $mainMod, E, exec, neovide
bind = $mainMod SHIFT, F, fullscreen
bind = $mainMod, Return, exec, $term
bind = $mainMod, B, exec, $browser
bind = $mainMod, V, exec, pavucontrol

bind = CTRL ALT, A, exec, xfce4-appfinder
bind = CTRL ALT, C, exec, catfish
bind = CTRL ALT, B, exec, $files
bind = CTRL ALT, E, exec, archlinux-tweak-tool
bind = CTRL ALT, F, exec, firefox
bind = CTRL ALT, G, exec, chromium -no-default-browser-check
bind = CTRL ALT, I, exec, nitrogen
bind = CTRL ALT, K, exec, $scriptsDir/lockscreen
bind = CTRL ALT, L, exec, $scriptsDir/lockscreen
bind = CTRL ALT, NEXT, exec, conky-rotate -n
bind = CTRL ALT, P, exec, pamac-manager
bind = CTRL ALT, PREVIOUS, exec, conky-rotate -p
bind = CTRL ALT, R, exec, rofi-theme-selector
bind = CTRL ALT, Return, exec, foot
bind = CTRL ALT, S, exec, spotify
bind = CTRL ALT, T, exec, $term
bind = CTRL ALT, U, exec, pavucontrol
bind = CTRL ALT, V, exec, vivaldi-stable
bind = CTRL ALT, W, exec, arcolinux-welcome-app

bind = CTRL SHIFT, Escape, exec, $term --class btop -T btop -e btop
bind = CTRL ALT, END, exec, $term --class btop -T btop -e btop

bind = ALT, t, exec, variety -t
bind = ALT, n, exec, variety -n
bind = ALT SHIFT, n, exec, variety -n && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) && ~/.config/hypr/scripts/statusbar &
bind = ALT, right, exec, variety -n
bind = ALT, p, exec, variety -p
bind = ALT SHIFT, p, exec, variety -p && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) && ~/.config/hypr/scripts/statusbar &
bind = ALT, left, exec, variety -p
bind = ALT, f, exec, variety -f
bind = ALT, up, exec, variety --toggle-pause
bind = ALT SHIFT, up, exec, variety --toggle-pause && wal -i $(cat $HOME/.config/variety/wallpaper/wallpaper.jpg.txt) && ~/.config/hypr/scripts/statusbar &
bind = ALT, down, exec, variety --resume

bind = ALT, g, exec, $scriptsDir/glassmorphismToggle

bind = ALT, F3, exec, xfce4-appfinder

bind = , F12, exec, xfce4-terminal --drop-down

bind = $mainMod SHIFT, M, exec, hyprctl dispatch splitratio -0.1
bind = $mainMod, M, fullscreen, 1

bind = $mainMod SHIFT, Y, exec, $term --class clock -T clock -e tty-clock -c -C 7 -r -s -f "%A, %B, %d"
bind = $mainMod, Escape, exec, hyprctl kill
bind = $mainMod, I, layoutmsg, addmaster

bind = $mainMod, P, pseudo
bind = $mainMod CTRL, Return, layoutmsg, swapwithmaster
bind = $mainMod, Space, exec, $scriptsDir/changeLayout
bind = $mainMod, X, exec, archlinux-logout
bind = ALT, X, exec, nlogout
bind = ALT SHIFT, X, exec, nlogout
bind = $mainMod SHIFT, X, exec, arcolinux-powermenu

bind = $mainMod, F1, exec, $browser
bind = $mainMod, F2, exec, $editor
bind = $mainMod, F3, exec, inkscape
bind = $mainMod, F4, exec, gimp
bind = $mainMod, F5, exec, meld
bind = $mainMod, F6, exec, vlc
bind = $mainMod, F7, exec, virtualbox
bind = $mainMod, F8, exec, $files
bind = $mainMod, F9, exec, lollypop
bind = $mainMod, F10, exec, spotify
bind = $mainMod, d, exec, rofi -show run
bind = $mainMod, o, exec, rofi -show drun
bind = $mainMod, w, exec, rofi -show window
bind = $mainMod, a, exec, albert toggle

bind = , xf86audioraisevolume, exec, $volume --inc
bind = , xf86audiolowervolume, exec, $volume --dec
bind = , xf86audiomute, exec, $volume --toggle
bind = , xf86audioplay, exec, playerctl play-pause
bind = , xf86audionext, exec, playerctl next
bind = , xf86audioprev, exec, playerctl previous
bind = , xf86audiostop, exec, playerctl stop
bind = , xf86monbrightnessup, exec, $brightness --inc
bind = , xf86monbrightnessdown, exec, $brightness --dec

bind = $mainMod SHIFT, equal, submap, backlight
submap = backlight
bind = , equal, exec, $backlight --inc
bind = , minus, exec, $backlight --dec
bind = , escape, submap, reset
submap = reset

bind = $mainMod, equal, submap, volume
submap = volume
bind = , equal, exec, $volume --inc
bind = , minus, exec, $volume --dec
bind = , 0, exec, $volume --toggle
bind = , 9, exec, $volume --toggle-mic
bind = , escape, submap, reset
submap = reset

binde = $mainMod SHIFT, H, resizeactive,-50 0
binde = $mainMod SHIFT, L, resizeactive,50 0
binde = $mainMod SHIFT, K, resizeactive,0 -50
binde = $mainMod SHIFT, J, resizeactive,0 50

bind = $mainMod CTRL, H, movewindow, l
bind = $mainMod CTRL, L, movewindow, r
bind = $mainMod CTRL, K, movewindow, u
bind = $mainMod CTRL, J, movewindow, d

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, N, movetoworkspacesilent, special
bind = $mainMod, U, togglespecialworkspace,

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod, period, workspace, e+1
bind = $mainMod, comma, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, G, togglegroup
bind = $mainMod, tab, workspace, m+1
bind = $mainMod SHIFT, tab, workspace, m-1
bind = ALT, tab, workspace, m+1
bind = ALT SHIFT, tab, workspace, m-1

bind = $mainMod, O, exec, $colorpicker
bind = $mainMod SHIFT, O, exec, $term --class hyprpicker --hold -e hyprpicker
bind = $mainMod CTRL, S, exec, $wofi_beats

bind = , Print, exec, $screenshot --now
bind = $mainMod, Print, exec, $screenshot --in5
bind = SHIFT, Print, exec, $screenshot --in10
bind = CTRL, Print, exec, $screenshot --win
bind = $mainMod SHIFT, S, exec, flameshot gui

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bind = $mainMod, bracketleft, movetoworkspace, -1
bind = $mainMod, bracketright, movetoworkspace, +1

bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10
bind = $mainMod SHIFT, bracketleft, movetoworkspacesilent, -1
bind = $mainMod SHIFT, bracketright, movetoworkspacesilent, +1

debug:disable_logs = false

bind = $alt,b,exec, $HOME/.scripts/books.sh
bind = $mainMod,p,exec, $HOME/.scripts/toggle_waybar.sh
bind = $mainMod,y,exec, $HOME/.scripts/config_files.sh
bind = $mainMod,t,exec, $HOME/.scripts/create_tmp.sh

======Config-End========

### Description

I have been having random crashes lately but couldn't report because they were so random and unreproducable for example hyprland crashed when saving a file in neovim and some other random crashes that I don't remember the last thing happened before it crahed, but mostly it involved stuff like saving a file or writing to a file(Maybe an IO problem just a thought though), but I found one where it's easy to reproduce. The crash happens when I try to enable the debugger plugin in Kate-Editor(I made sure this isn't a problem with Kate because the same steps to reproduce the bug doesn't happen on an awesome session in X11 didn't test on other wayland sessions other than hyprland though because I don't have any so this maybe a wayland specific bug but I doubt it since like I said I've had other random crashes lately with hyprland). Hopefully the underlying bug is related to my other crashes because this is very random.

### How to reproduce

1. Open Kate the editor or install it if you don't have it
2. Navigate in the toolbar to settings then Configure Kate
3. Go to plugins tab
4. Select the Kate debugger plugin
5. Click Apply

### Crash reports, logs, images, videos
[hyprland.log](https://github.com/user-attachments/files/18149693/hyprland.log)
[hyprlandCrashReport3898.txt](https://github.com/user-attachments/files/18149694/hyprlandCrashReport3898.txt)

**Comment by vaxerski** [comment]
I'll need a crash report for that one.

**Comment by omagdy7** [comment]
Whoops I attached the wrong file updated now in the issue? or is this just the logs I reproduced the bug then took that last log file in $XDG_RUNTIME_DIR/hypr.

**Comment by vaxerski** [comment]
that is a log and not the crash report

**Comment by omagdy7** [comment]
Okay I have now updated the issue to contain the crash report and the log file

**Comment by vaxerski** [comment]
this is weird, I think the stacktrace is bork.

Can you get a debug stacktrace? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by omagdy7** [comment]
Okay I updated the system and it's now fixed couldn't reproduce the bug.
