### ISSUE TITLE
Blur doesn't work on a bar layer

### ISSUE THREAD

**Issue by izmyname** [hyprwm/Hyprland#8741]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit e340e9f431c7f1792fd6bfea20eb2f71a59d511f  (nix/meson: add re2 dependency (8738)).
Date: Tue Dec 17 00:22:36 2024
Tag: v0.45.0-120-ge340e9f4, commits: 5553
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: archbtw
Release: 6.12.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:30:31 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.77  Wed Nov 27 23:33:08 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Blur doesn't work on a bar layer, bit works on launcher and notifications layers

Here's my config

```
layerrule = blur,launcher
layerrule = ignorealpha, launcher
layerrule = dimaround, launcher
layerrule = blur, notifications
layerrule = ignorealpha, notifications
layerrule = blur, bar
layerrule = ignorealpha, bar
layerrule = blurpopups, bar
```

### How to reproduce

Have a semi-transparent launcher, apply layerrules, cry.

### Crash reports, logs, images, videos

![20241217_01h00m38s_grim](https://github.com/user-attachments/assets/a9256ed2-1caa-4f3f-8b66-e0a3cfc542dc)

**Comment by vaxerski** [comment]
ignorealpha requires a parameter

**Comment by izmyname** [comment]
ignorezero doesn't work, either, btw

**Comment by izmyname** [comment]
Also, commenting `ignorealpha` layerrule doesn't return that blur I posted in a previous issue, so blur is, indeed, broken and not just `ignorealpha`

**Comment by izmyname** [comment]
**UPD 2:** changing "bar" to "waybar" fixed the issue. The strange thing is -  it did work with generic "bar" name before, but it doesn't, now. Closing as it's not a big deal for me - how this layer is called.

**Comment by vaxerski** [comment]
with the move to RE2 regex now requires a full match, not any match.

**Comment by vaxerski** [comment]
I'll mention that as breaking
