### ISSUE TITLE
Hyprland Crash

### ISSUE THREAD

**Issue by Phenessy** [hyprwm/Hyprland#8745]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

![image](https://github.com/user-attachments/assets/ee9a953b-d447-40e2-9911-cbbcc02aa7be)
Equipment:

Lenovo Thinkpad X220i

Core i3

4GB ram

128GB SSD

### Description

I was missing the configuration of hyprland (I’m a beginner btw to Linux and hyprland) and messing with the animations then hyprland crashed.

### How to reproduce

Inserting a bezier curve into the animation configuration.

### Crash reports, logs, images, videos

![IMG_0587](https://github.com/user-attachments/assets/542acd98-d146-4fa5-8a97-0ede7f0a5a08)

**Comment by vaxerski** [comment]
I believe this is fixed in 0.46, but you're missing a crash report so I can't say for sure.
