### ISSUE TITLE
windowrulev2 onworkspace stopped working

### ISSUE THREAD

**Issue by soufhehe** [hyprwm/Hyprland#8746]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.0 built from branch main at commit 788ae588979c2a1ff8a660f16e3c502ef5796755  (version: bump to 0.46.0).
Date: Tue Dec 17 00:38:56 2024
Tag: v0.46.0, commits: 5555
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug
```

</details>

### Description

smart gaps // no gaps when only stopped working

### How to reproduce

with https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps
`
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
`
border are still present even with only 1 window

**Comment by soufhehe** [comment]
rule bordersize broke too

**Comment by vaxerski** [comment]
oopsie tehee
