### ISSUE TITLE
blurls breaks layerSurface fadeOut animation

### ISSUE THREAD

**Issue by autofool** [hyprwm/Hyprland#875]
Installed with AUR package hyprland-git

#### Steps to reproduce:
  1. Enable blur and set blurls=gtk-layer-shell
  2. Enable animations
  3. Open a layer shell window (e.g eww)
  4. Close layer shell window

#### Expected behavior:
  Layer shell window animates for opening and closing

#### Noted behavior:
  Layer shell window animates for opening but flickers out in closing animation in an instant.

[recording.webm](https://user-images.githubusercontent.com/50569653/196512883-81b869e8-ef74-46ba-9cea-4dfdc7668928.webm)

**Comment by vaxerski** [comment]
check with 98a32f5e52143bd40cb574822889d7ae64818fb0

**Comment by autofool** [comment]
It works now!

**Comment by autofool** [comment]
Everything is enabled, from border to shadow to rounding. No problem in animations.

**Comment by autofool** [comment]
Is it possible to force or disable specific animation on layer surface? like make it slide and disable fade?

**Comment by vaxerski** [comment]
nope
