### ISSUE TITLE
Make windows opened from special workspace spawn in underlying active workspace

### ISSUE THREAD

**Issue by jbirnick** [hyprwm/Hyprland#8770]
### Description

Let's say you have a file manager on your special workspace (=scratchpad).
If you open a file, you usually want it to open in the _underlying_ (normal) workspace, and _not_ in the special workspace (as it is right now).

Do you think one could make an option for this behavior?

**Comment by vaxerski** [comment]
> If you open a file, you usually want it to open in the underlying (normal) workspace, and not in the special workspace (as it is right now).

excuse me what kind of psychopath wants that?!

This is such a weird edge case that you can just script it yourself.

**Comment by jbirnick** [comment]
Well how could I script it myself? Do you mean with the sockets? I don't see how to do it with rules.

**Comment by vaxerski** [comment]
yeah, with sockets. Easy to do.

**Comment by jbirnick** [comment]
If anyone wants the same behavior, this is now implemented here: https://github.com/hyprwm/Hyprland/issues/8770
