### ISSUE TITLE
Add Matrix and/or IRC.

### ISSUE THREAD

**Issue by pjalsGit** [hyprwm/Hyprland#878]
Some people (including me) do not want to use Discord, I will not go into detail for what reasons but you can see an overview [here](https://stallman.org/discord.html).

It would be nice to have a Matrix room (and/or IRC) for those who do not want to use Discord. Preferrably it would be bridged but seperate is also fine.

**Comment by vars1ty** [comment]
There will be a bridge later on, as seen in the screenshot below

![image](https://user-images.githubusercontent.com/54314240/196682976-854cc284-b131-423e-904d-1366510388a3.png)

**Comment by vaxerski** [comment]
no matrix and no irc

**Comment by NotAShelf** [comment]
> mom im famous

and still italian, ew

**Comment by Froggo8311** [comment]
Shame :pensive:
