### ISSUE TITLE
catchall doesn't work anymore

### ISSUE THREAD

**Issue by soufhehe** [hyprwm/Hyprland#8794]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.0 built from branch main at commit 71dc9f6128b8d2e382b2a574d2d5f15e2d907f3a  (pluginAPI: add register dispatcher v2).
Date: Thu Dec 19 21:23:32 2024
Tag: v0.46.0-18-g71dc9f61, commits: 5573
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug
```

</details>

### Description

I use that to change my wallpaper

`bind = $mainMod CTRL, 		W, 		submap, 		wall`
`submap=wall`
`bind = , 			W, 		exec, 			~/.config/hypr/scripts/auto_wallpaper/auto_wallpaper_current.sh`
`bind = , 			catchall, 	exec, 			notify-send "Leaving wallpaper mode." -t 1000 `
`bind = , 			catchall, 	submap, 		reset`
`submap = reset`
and the catchall keyword don't work. I don't know since when because I was using escape to leave submap

### How to reproduce

create a submap
use catchall to leave submap
you are now stuck insine the submap :) (keep a terminal at hand to `hyprctl dispatch submap reset`)

**Comment by vaxerski** [comment]
a bisect would be convenient

**Comment by soufhehe** [comment]
ok, found the problem. I was using 2 consecutives catchall and obviously the second bind wasn't registered

`bind = , 			catchall, 	exec, 			notify-send "Leaving wallpaper mode." -t 1000 `
`bind = , 			catchall, 	submap, 		reset`
