### ISSUE TITLE
Hyprland crashing when trying to start

### ISSUE THREAD

**Issue by ienjir** [hyprwm/Hyprland#8797]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

pacman -Qe hyprland outputs:
hyprland 0.46.2-1

system information:
laptop: asus zenbook 14 oled
Kernel Version: 6.12.4-arch1-1 (64-
Processors: 16 × 13th Gen Intel® Core™ i7-1360P
Memory: 15.2 GiB of RAM
Graphics Processor: Mesa Intel® Iris® Xe Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: Zenbook Flip UP3404VA_UP3404VA
System Version: 1.0

### Description

When I try to start Hyprland either normally or in KDE through a Terminal it always gives me the the error 
fish: Job 1, 'hyprland' terminated by signal SIGSEGV (Address boundary error)

I updated my system and all packages today and later restarted, maybe it has something to do with that but I don't know. I'm quiet new to Linux so I don't much yet. 

I read the regression part but I think it hasn't to do with that there is a faulty commit in the hyprland repo as the latest commit is from over a week ago and it worked fine until the restart today.

### How to reproduce

Start Hyprland either in the login screen or when starting hyperland through the Hyprland command in a terminal on KDE (havent tried it on something different but I'm guessing it will be the same)

### Crash reports, logs, images, videos

This is the report it gives me when starting hyprland trough the terminal:
Welcome to Hyprland!
[LOG] Instance Signature: 0bd541f2fd902dbfa04c3ea2ccf679395e316887_1734785147_1816563720
[LOG] Runtime directory: /run/user/1000/hypr/0bd541f2fd902dbfa04c3ea2ccf679395e316887_1734785147_1816563720
[LOG] Hyprland PID: 8133
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: randomadmin
[LOG] Release: 6.12.4-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000

fish: Job 1, 'Hyprland' terminated by signal SIGSEGV (Address boundary)

**Comment by akaneboy** [comment]
yeah it's also happening to me right now, same update, same error please someone can fix this
btw i semi-solved this by downgradin hyprland but for some reason wifi and internet in general wasnt working so idrk imma wait for some update

**Comment by arc-nazrin** [comment]
Isn't this related to the closed issue https://github.com/hyprwm/Hyprland/issues/8785

**Comment by vaxerski** [comment]
build manually and get a debug stacktrace then https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by Nel-xhan** [comment]
I have the same issue. My: [gdb.txt](https://github.com/user-attachments/files/18221426/stackstrace.txt)
Will try bisect today

**Comment by Nel-xhan** [comment]
There was an update to the wayland-protocols today, works again on my end. By bisecting i could find nothing.

**Comment by vaxerski** [comment]
the gdb trace is a 404 lol

**Comment by vaxerski** [comment]
this can be fixed by recompiling the hypr* tree, see linked issue

**Comment by ienjir** [comment]
I fixed it
To fix it you have to downgrade to a earlier version, I went to 0.45.2. Now everything works fine

**Comment by Maheshgithub111** [comment]
@ienjir downgrading didn't worked for me because there was problem with the hyprland tools (every hyprland tool that was install from git) so i simply remove all of it by using sudo pacman -Rdd <hyprland too-git> and reinstall them and it worked.....
