### ISSUE TITLE
Crash on launch, presumably after using hyprshot

### ISSUE THREAD

**Issue by RambilE** [hyprwm/Hyprland#8798]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Installed via `$ sudo pacman -S hyprland`
<details> <summary>System/Version info</summary>

```sh
$ Hyprland --systeminfo
Segmentation fault (core dumped)
$ hyprland -v
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug
$ hyprland
Welcome to Hyprland!
[LOG] Instance Signature: 0bd541f2fd902dbfa04c3ea2ccf679395e316887_1734793748_1176772357
[LOG] Runtime directory: /run/user/1000/hypr/0bd541f2fd902dbfa04c3ea2ccf679395e316887_1734793748_1176772357
[LOG] Hyprland PID: 20318
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: archbtw
[LOG] Release: 6.12.4-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000


Segmentation fault (core dumped)
```

</details>

### Description

Something very strange happened. After i used hyprshot, i couldn't click on anything but swaync notifications (which never happened before), so i rebooted and after that i can't log into hyprland via terminal or sddm.

### How to reproduce

As written in description (i don't really know how that happened), ran hyprshot with `hyprshot --clipboard-only -m region --freeze` (keybind)

### Crash reports, logs, images, videos

Logs have the same written in them as when i run `$ hyprland` (without Segmentation fault (core dumped))
Only crash report i have is from dec 11, so it's not relevant

**Comment by vaxerski** [comment]
build manually and get a debug stacktrace then https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by vaxerski** [comment]
#8797 as well
