### ISSUE TITLE
Command does not get executed on release

### ISSUE THREAD

**Issue by UnaTried** [hyprwm/Hyprland#8800]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

When I try to execute my custom script with the keybinds
bind = Super, D, exec, ./show_desktop.sh move
bindr= Super, D, exec, ./show_desktop.sh restore

It doesn't execute the bindr part.

### How to reproduce

1. Put this code into a document called show_desktop
```
current_workspace=$(hyprctl activewindow | grep -Po '(?<=workspace: )\d+')
mkdir -p $HOME/.scripts/tmp
move() {
	hyprctl clients -j | jq -r --arg ws "$current_workspace" '
  		.[] | 
  		select(.workspace.id == ($ws | tonumber)) | 
		.address' >> $HOME/.scripts/tmp/show_desktop.txt
	cat $HOME/.scripts/tmp/show_desktop.txt | while read -r line; do
		address=$(echo "$line")
		if [ -n "$address" ]; then
			hyprctl dispatch movetoworkspacesilent special:minimized,address:"$address"
		fi
	done
}

restore() {
	cat $HOME/.scripts/tmp/show_desktop.txt | while read -r line; do
		address=$(echo "$line")
		if [ -n "$address" ]; then
			hyprctl dispatch movetoworkspacesilent $current_workspace,address:"$address"
		fi
	done
}

case "$1" in
"move")
    move
    ;;
"restore")
    restore
	echo "" >> $HOME/.scripts/tmp/show_desktop.txt
    ;;
*)
    echo "Usage: $0 move"
	echo "       $0 restore"
    ;;
esac
```
2. Execute `chmod +x ./show_desktop.sh`
3. Add the keybinds
```
bind = Super, D, exec, ./show_desktop.sh move
bindr = Super, D, exec, ./show_desktop.sh restore
```
4. Do they keybind
5. Release the keybind

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/bce916a6-34c8-4948-ba00-d0900293dc3e

**Comment by vaxerski** [comment]
try adding the `t` flag as well to your release bind

**Comment by UnaTried** [comment]
bind = Super, D, exec, $HOME/.scripts/commands/show_desktop.sh move
bindrt = Super, D, exec, $HOME/.scripts/commands/show_desktop.sh restore

Did not work

and
bind = Super, D, exec, $HOME/.scripts/commands/show_desktop.sh move
bindtr = Super, D, exec, $HOME/.scripts/commands/show_desktop.sh restore

**Comment by vaxerski** [comment]
it works on my end even without t, are you sure it's not your script failing?

**Comment by UnaTried** [comment]
Have you tried my script or is it something else?

**Comment by vaxerski** [comment]
I just put `notify-send a` and `notify-send b` for the binds

**Comment by UnaTried** [comment]
It works with notify-send, I wonder what is wrong with my script then.

**Comment by vaxerski** [comment]
well that's for you to figure out. Not a hyprland issue
