### ISSUE TITLE
Add the movealltoworkspace, movealltoworkspacesilent and the lastWorkspace value 

### ISSUE THREAD

**Issue by UnaTried** [hyprwm/Hyprland#8801]
### Description

These values are shown in `hyprctl clients`.
`lastWorkspace` shows you the workspace the application or client was last on, before the move.
`movealltoworkspace` and `movealltoworkspacesilent` moves all appplications and or "clients" to the specified workspace. `movealltoworkspace` silent does it without moving you to the workspace.

**Comment by vaxerski** [comment]
I don't see the point

**Comment by UnaTried** [comment]
They are there to make scripts easier and add more window rules.

**Comment by vaxerski** [comment]
_what_ scripts easier? You can always make up a weird edge case. Adding more stuff for the sake of adding stuff is not a good thing.

**Comment by UnaTried** [comment]
I guess I'll close this then.
