### ISSUE TITLE
Focus on activate request

### ISSUE THREAD

**Issue by ttmx** [hyprwm/Hyprland#881]
I request an equivalent to the i3/sway option `focus_on_window_activation`.
I have not found anything of sorts on the wiki nor on other issues.

This would be very nice to have since currently after pressing a link somewhere you have to manually swap to the browser workspace.

Thank you poland

**Comment by vaxerski** [comment]
check with 2c714eace5bc903e5e9ef9e2c3048cb65a2ca9b4
