### ISSUE TITLE
Global keybinds isnt work

### ISSUE THREAD

**Issue by Spbog** [hyprwm/Hyprland#8810]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: arch
Release: 6.12.4-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:30:31 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
	unknown: not runtime
```

</details>

### Description

Previously, global binds worked fine for me. There was a bind on Teamspeak. After the update, the bind stopped working. Teamspeak does not see the button pressed even if the window is active. And if the global bind is removed from the config, then Teamspeak will begin to see the button press, but only if the window is active

### How to reproduce

in hyprland.conf
`bind = , mouse:276, pass, ^(TeamSpeak 3)`

and try to bind "mouse button 5" in teamspeak

**Comment by MisterrrX** [comment]
Yep, same for me on TeamSpeak 5

**Comment by vaxerski** [comment]
as above, that's not a valid window parameter

**Comment by ThomChroma** [comment]
It used to work like this but the wiki wasn't updated, I sent a PR https://github.com/hyprwm/hyprland-wiki/pull/916
