### ISSUE TITLE
Why using uwsm/systemd is better than just launching Hyprland from TTY?

### ISSUE THREAD

**Issue by aljustiet** [hyprwm/Hyprland#8818]
I noticed that when I launch Hyprland with uwsm, it consumes more RAM than if I would launch it directly from TTY. What benefits are there for using Hyprland with uwsm/systemd?</div>

**Comment by izmyname** [comment]
Uwsm acts as an analog of `desktop-session` from `GNOME` or `KDE` desktops, which means - you can use `.desktop` files to autostart apps, enable systemd services, that depend on a graphical session and cleanly shutdown the system (all apps exit gracefully and no 90sec shutdowns)

**Comment by izmyname** [comment]
I suggest closing this as there are several discussions, related to the topic and the answer was given.
