### ISSUE TITLE
windowrule move to cursor/pointer

### ISSUE THREAD

**Issue by DominickVale** [hyprwm/Hyprland#882]
First of all: thank you for hyprland; it's awesome.
I'm trying to port my old i3 setup to hyprland and noticed there's no way to make a window pop at the current cursor position, it would be a nice thing to have :)
(something like windowrule=move cursor,app)

**Comment by vaxerski** [comment]
you mean to the center of the cursor or the top-left corner where the cursor is?

**Comment by DominickVale** [comment]
> you mean to the center of the cursor or the top-left corner where the cursor is?

top-left would probably be better, honestly, it would be top-notch if it could be offset in the rule like this:
windowrule=move cursor [x] [y]

**Comment by vaxerski** [comment]
added in c0bb4db15c91b172bb71accee28bd338f43ee8e5

```
move cursor -50% -50%
```
centers the window around your cursor.
