### ISSUE TITLE
bug when trying to upgrade system

### ISSUE THREAD

**Issue by sansroot** [hyprwm/Hyprland#8820]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

is it just me, or everyone having the same bug when trying to upgrade system?
i'm running arch

:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by aquamarine
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprgraphics
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprland
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprlang
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprpaper
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by xdg-desktop-portal-hyprland

### Description

is it just me, or everyone having the same bug when trying to upgrade system?
i'm running arch

:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by aquamarine
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprgraphics
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprland
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprlang
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by hyprpaper
:: installing hyprutils (0.3.0-1) breaks dependency 'libhyprutils.so=1-64' required by xdg-desktop-portal-hyprland

### How to reproduce

sudo pacman -Syu

**Comment by izmyname** [comment]
I think you should address this to Arch maintainers, as this issue will be closed as not planned.

**Comment by kobinabrandon** [comment]
Hi there. I suspect the maintainers have already addressed this, but I on my  end, the issue persists. Is there something I can do to overcome it?
