### ISSUE TITLE
Hyprland error while loading shared libraries: libhyprutils.so.1 not found

### ISSUE THREAD

**Issue by vaskark** [hyprwm/Hyprland#8825]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Keeps erroring out. Using latest git anyway.```

</details>

### Description

Error message:

`Hyprland: error while loading shared libraries: libhyprutils.so.1: cannot open shared object file: No such file or directory`

### How to reproduce

Hyprland from tty.

### Crash reports, logs, images, videos

I do not have` ~/.cache/hyprland` or `/run/user/1000/hypr`. So I can't attach anything. And doing a stacktrace didn't work either. No coredumps were listed.

I've encountered this type of error before with other packages and have usually created a symlink and that fixed the problem.

```
sudo ln -s /usr/local/lib/libhyprutils.so.0.3.0 /usr/local/lib/libhyprutils.so.1
sudo ldconfig
```
Didn't work this time.
I've rebuilt aquamarine, hyprutils, and Hyprland from scratch. Nothing helped.

I'm on Ubuntu 24.10.1. So I know it isn't a priority. Just thought I'd report. Started happening last night.

Any advice would be appreciated.
Thanks.

**Comment by alekgr** [comment]
this is more a arch maintenance issue. I had the same issue and had to re install the whole hyprland* eccosystem

**Comment by vaskark** [comment]
But I'm on Ubuntu, not Arch.
Oh well. I'll get to working rebuilding everything then. Not a big deal.
Thanks for rsponding.

**Comment by alekgr** [comment]
are you using hyprland-git ?

**Comment by vaskark** [comment]
> are you using hyprland-git ?

Yup. Also tried the 0.46.2 release version. Same error.

**Comment by vaskark** [comment]
Update: Just rebuilt the entire ecosystem from scratch and I'm back in.

**Comment by jacobrreed** [comment]
Can confirm this issue using chaotic AUR full hyprland-meta-git package on a  fresh Arch install

**Comment by stefonarch** [comment]
The missing piece is in ` libhyprutils-git`.  For official arch packages creating a symlink solves:

```
cd /usr/lib
sudo ln -s libhyprutils.so.2 libhyprutils.so.1
```

**Comment by lkxe** [comment]
> The missing piece is in ` libhyprutils-git`. For official arch packages creating a symlink solves:
> 
> ```
> cd /usr/lib
> sudo ln -s libhyprutils.so.2 libhyprutils.so.1
> ```

This is a terrible idea and will break things in the future

**Comment by dotaxis** [comment]
Rebuilt all git packages and getting the same error here.

**Comment by vaskark** [comment]
> Rebuilt all git packages and getting the same error here.

I had to delete each build/ folder and started from scratch for each.

**Comment by dotaxis** [comment]
Rebuilding against latest aquamarine fixed it. Forgot about that package 🤷‍♂️

**Comment by stefonarch** [comment]
On arch it looks that it's not provided by any package, here it's absence breaks only `hyprctl` as I can tell.

**Comment by vaxerski** [comment]
this is not a hyprland issue. This can be fixed by rebuilding hyprland.

**Comment by os-guy** [comment]
> > The missing piece is in ` libhyprutils-git`. For official arch packages creating a symlink solves:
> > ```
> > cd /usr/lib
> > sudo ln -s libhyprutils.so.2 libhyprutils.so.1
> > ```
> 
> This is a terrible idea and will break things in the future

Yes, it's a terrible idea but it doesn't matter for me bcz I will format my computer soon.

**Comment by stefonarch** [comment]
I'm not so sure if in future anything will really look for `libhyprutils.so.1`. 
And symlinks can also be removed btw.

**Comment by MightyCoderX** [comment]
@vaskark
> Update: Just rebuilt the entire ecosystem from scratch and I'm back in.

how? did you just delete paru cache and ran `paru -S hyprland-git`? because that doesn't work in my case

**Comment by vaskark** [comment]
@MightyCoderX 

Sorry. I'm on Ubuntu. Someone else will have to chime in on an Arch solution.

**Comment by MightyCoderX** [comment]
> @MightyCoderX 
> 
> Sorry. I'm on Ubuntu. Someone else will have to chime in on an Arch solution.

I fixed it by updating all the deps when trying to compile manually.

**Comment by vaskark** [comment]
@MightyCoderX 

Good stuff. I pretty much did the same. Rebuilt everything from scratch.

**Comment by Eduruiz** [comment]
On arch using AUR, I tried a clean build of hyprland-git. The output showed that the missing lib was from `hyprgraphics-git,` so I did a clean build of `hyprgraphics-git,` and everything is working now.

**Comment by GHOST-mHBr** [comment]
Same problem here with AUR package hyprland-git version 0.46.0.r119.g0dc7367a-1 and also manual building.

CMake clearly says that libaquamarine.so needs libhyprutils.so.1 and it is not found.

**Comment by stefonarch** [comment]
Afaik it's an arch packaging issue. I use the official packages and if I remove the symlink I created (see above) `hyprctl` fails because missing.

**Comment by Eduruiz** [comment]
@stefonarch I'm using the `-git` packages without any symlink, just a clean build of  `hyprgraphics-git`
