### ISSUE TITLE
hyprctl version incorrect version

### ISSUE THREAD

**Issue by soufhehe** [hyprwm/Hyprland#8827]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.0 built from branch main at commit 5f7ad767dbf0bac9ddd6bf6c825fb9ed7921308a  (flake.lock: update).
Date: Sun Dec 22 23:39:17 2024
Tag: v0.46.0-27-g5f7ad767, commits: 5582
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


flags set:
debug
```

</details>

### Description

`Hyprland 0.46.0 built from branch main at commit 5f7ad767dbf0bac9ddd6bf6c825fb9ed7921308a  (flake.lock: update).`

[5f7ad76](https://github.com/hyprwm/Hyprland/commit/5f7ad767dbf0bac9ddd6bf6c825fb9ed7921308a) is latest git and hyprctl says it's 0.46.0 instead of 0.46.2

### How to reproduce

hyprctl version
hyprctl systeminfo -c
Hyprland --systeminfo

**Comment by zjeffer** [comment]
It's because the 0.46.2 branch hasn't been merged into main, so [this commit](https://github.com/hyprwm/Hyprland/commit/0bd541f2fd902dbfa04c3ea2ccf679395e316887) isn't present in the main branch.

**Comment by vaxerski** [comment]
a .1 or .2 etc releases are essentially .0 + patches backported from main.

Main is always last main release (.0) + continued git development.
