### ISSUE TITLE
noob i just need help.

### ISSUE THREAD

**Issue by jeffneedshelp** [hyprwm/Hyprland#8832]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1

flags set:
debug

System Information:
System name: Linux
Node name: fantabaridi-latitudee5510
Release: 6.12.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

plugins:
	unknown: not runtime

### Description

hyprland being hyprland refusing to start.

### How to reproduce

dont know what this means.

### Crash reports, logs, images, videos

❯ cat /home/fantabaridi/.cache/hyprland/hyprlandCrashReport5753.txt
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
*thud*

Hyprland received signal 6(ABRT)
Version: 0bd541f2fd902dbfa04c3ea2ccf679395e316887
Tag: v0.46.2
Date: Thu Dec 19 19:26:47 2024
Flags:

System info:
	System name: Linux
	Node name: fantabaridi-latitudee5510
	Release: 6.12.6-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])

os-release:
	NAME="EndeavourOS"
	PRETTY_NAME="EndeavourOS"
	ID="endeavouros"
	ID_LIKE="arch"
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://endeavouros.com"
	DOCUMENTATION_URL="https://discovery.endeavouros.com"
	SUPPORT_URL="https://forum.endeavouros.com"
	BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
	PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
	LOGO="endeavouros"
Backtrace:
	# | hyprland(_Z12getBacktracev+0x61) [0x62c5bcf0cba1]
		getBacktrace()
		??:?
	#1 | hyprland(_ZN14NCrashReporter18createAndSaveCrashEi+0xb50) [0x62c5bce8ab90]
		NCrashReporter::createAndSaveCrash(int)
		??:?
	#2 | hyprland(_Z25handleUnrecoverableSignali+0x71) [0x62c5bce1e471]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /usr/lib/libc.so.6(+0x3d1d0) [0x7389de84c1d0]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x963f4) [0x7389de8a53f4]
		??
		??:0
	#5 | /usr/lib/libc.so.6(gsignal+0x20) [0x7389de84c120]
		??
		??:0
	#6 | hyprland(_ZN15CHyprOpenGLImpl7initEGLEb+0x914) [0x62c5bd0f9bc4]
		CHyprOpenGLImpl::initEGL(bool)
		??:?
	#7 | hyprland(_ZN15CHyprOpenGLImplC1Ev+0xc0a) [0x62c5bd0fbbfa]
		CHyprOpenGLImpl::CHyprOpenGLImpl()
		??:?
	#8 | hyprland(_ZN11CCompositor12initManagersE18eManagersInitStage+0xc99) [0x62c5bce23b89]
		CCompositor::initManagers(eManagersInitStage)
		??:?
	#9 | hyprland(_ZN11CCompositor10initServerENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0xd88) [0x62c5bce253d8]
		CCompositor::initServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
		??:?
	#1 | hyprland(main+0xa5d) [0x62c5bcdef97d]
		main
		??:?
	#11 | /usr/lib/libc.so.6(+0x25e08) [0x7389de834e08]
		??
		??:0
	#12 | /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7389de834ecc]
		??
		??:0
	#13 | hyprland(_start+0x25) [0x62c5bce1a655]
		_start
		??:?

Log tail:
[LOG] [AQ] drm: Initializing connector id 86
[LOG] [AQ] drm: Connector gets name HDMI-A-2
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Connector 86 connection state: 2
[LOG] [AQ] drm: Scanning connector id 90
[LOG] [AQ] drm: Initializing connector id 90
[LOG] [AQ] drm: Connector gets name DP-2
[ERR] [AQ] drm: getCurrentCRTC: No CRTC 0
[LOG] [AQ] drm: Connector 90 connection state: 2
[LOG] [AQ] drm: Rechecking CRTCs
[LOG] [AQ] drm: Skipping connector eDP-1, has crtc 47 and is connected
[LOG] [AQ] drm: connector VGA-1, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector HDMI-A-1, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector DP-1, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector HDMI-A-2, has crtc -1, will be rechecked
[LOG] [AQ] drm: connector DP-2, has crtc -1, will be rechecked
[LOG] [AQ] drm: slot 0 crtc 47 taken by eDP-1, skipping
[LOG] [AQ] drm: slot 1 crtc 63 unassigned
[LOG] [AQ] drm: Connector VGA-1 is not connected
[LOG] [AQ] drm: Connector HDMI-A-1 is not connected
[LOG] [AQ] drm: Connector DP-1 is not connected
[LOG] [AQ] drm: Connector HDMI-A-2 is not connected
[LOG] [AQ] drm: Connector DP-2 is not connected
[LOG] [AQ] drm: Connector eDP-1 connected
[LOG] [AQ] drm: Connecting connector eDP-1, CRTC ID 47
[LOG] [AQ] drm: Dumping detected modes:
[LOG] [AQ] drm: Mode 0: 1366x768@60.03Hz  (preferred)
[LOG] [AQ] drm: Mode 1: 1366x768@40.02Hz 
[LOG] [AQ] drm: Physical size [Vector2D: x: 340, y: 190] (mm)
[LOG] [AQ] drm: Description AU Optronics 0x25EC  (eDP-1)
[LOG] [AQ] drm: connector eDP-1 crtc is incapable of vrr: props.vrr_capable -> 0, crtc->props.vrr_enabled -> 24
[LOG] [AQ] drm: Explicit sync supported
[LOG] [AQ] drm: connector eDP-1 crtc supports CTM
[LOG] [AQ] drm: gpu /dev/dri/card1 becomes primary drm
[LOG] [AQ] DRM Dumb: created a dumb allocator
[LOG] [AQ] Starting the Aquamarine backend!
[LOG] [AQ] Starting the Wayland backend!
[LOG] [AQ] Connected to a wayland compositor: Hyprland
[LOG] [AQ] Got registry at 0x62c5c9802bf0
[LOG] [AQ] Output WAYLAND-1: initialized
[LOG] [AQ] reopenDRMNode: opening node /dev/dri/renderD128
[LOG] [AQ] Created a GBM allocator with drm fd 32
[LOG] [AQ] drm: Connectors size2 6
[LOG] [AQ] reopenDRMNode: opening node /dev/dri/renderD128
[LOG] [AQ] Created a GBM allocator with drm fd 36
[LOG] [AQ] CDRMRenderer: got a high priority context
[LOG] [AQ] CDRMRenderer: success
[LOG] [AQ] drm: onReady: connector 67
[LOG] [AQ] drm: onReady: connector 67 has output name eDP-1
[LOG] [AQ] Swapchain: Clearing
[LOG] New aquamarine output with name eDP-1
[LOG] [AQ] drm: onReady: connector 64
[LOG] [AQ] drm: onReady: connector 74
[LOG] [AQ] drm: onReady: connector 81
[LOG] [AQ] drm: onReady: connector 86
[LOG] [AQ] drm: onReady: connector 90
[LOG] [AQ] CDRMRenderer: got a high priority context
[LOG] [AQ] CDRMRenderer: success
[LOG] Running on DRMFD: 29
[LOG] wl_display_add_socket for wayland-1 succeeded with 0
[LOG] Creating the CHyprOpenGLImpl!
[LOG] Supported EGL extensions: (16) EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_explicit_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
[LOG] eglDeviceFromDRMFD: Using device /dev/dri/card1
[LOG] EGL: IMG_context_priority supported, requesting high
[LOG] EGL: EXT_create_context_robustness supported, requesting lose on reset
[ERR] [EGL] Command eglCreateContext errored out with EGL_BAD_MATCH (0x12297): dri2_create_context
[WARN] EGL: Failed to create a context with GLES3.2, retrying 3.0
[ERR] [EGL] Command eglCreateContext errored out with EGL_BAD_MATCH (0x12297): dri2_create_context
[CRITICAL] 
==========================================================================================
ASSERTION FAILED! 

EGL: failed to create a context with either GLES3.2 or 3.0

at: line 172 in OpenGL.cpp

**Comment by vaxerski** [comment]
this is not a help forum. Looking at your gpu, it's too old.
