### ISSUE TITLE
unable to start hyprpicker, hypridle and hyprshade

### ISSUE THREAD

**Issue by Saifullah-Balghari** [hyprwm/Hyprland#8833]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: archlinux
Release: 6.12.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

then all my configs appears...

</details>

### Description

i am unable to run hyprpicker, hyprshade and hypridle after the latest update.

### How to reproduce

try runing hyprpicker, hyprshade or hypridle.

### Crash reports, logs, images, videos

```sh
hyprpicker
hyprpicker: error while loading shared libraries: libhyprutils.so.1: cannot open shared object file: No such file or directory
```

**Comment by fufexan** [comment]
As mentioned in at least 3 other closed issues, rebuild your whole hypr stack.

**Comment by Saifullah-Balghari** [comment]
Updating these fixed the problem for me.

extra/aquamarine                   0.5.1-2   to  0.5.1-3   
extra/hyprgraphics                 0.1.1-2   to   0.1.1-3    
extra/hypridle                     0.1.5-1   to   0.1.5-2        
extra/hyprland                     0.46.2-3   to  0.46.2-4    
extra/hyprlang                     0.6.0-2   to   0.6.0-3       
extra/hyprlock                     0.6.0-2   to   0.6.0-3        
extra/hyprpicker                   0.4.1-1   to   0.4.1-2
