### ISSUE TITLE
borders plus plus plugin didnt work

### ISSUE THREAD

**Issue by maotseantonio** [hyprwm/Hyprland#8835]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>**
```
bug
</details>

### Description

in startup load plugin message is shown but actually borders is not visible

### How to reproduce

bug

### Crash reports, logs, images, videos

borders plus plus plugin

**Comment by vaxerski** [comment]
wrong repoooo, fixed anyway

**Comment by maotseantonio** [comment]
thanks man. u are the best
