### ISSUE TITLE
Shift all workspaces right/Insert workspace

### ISSUE THREAD

**Issue by non-bin** [hyprwm/Hyprland#8842]
### Description

Hi :)

I'd like the ability to insert a workspace between already used ones, essentially shifting all existing workspaces to the right. Heres an example of inserting a new workspace 2, when 1-5 are in use:

```
1 2 3 4 5
| \ \ \ \
|  \ \ \ \
1 2 3 4 5 6
```

Essentially:
- Move windows on workspace 5, to 6, preserving layout
- Repeat with 4-5, 3-4, & 2-3
- Switch to the now empty workspace 2

This is likely possible with a plugin so I'll investigate that, but I thought I'd ask
Thanks for all your work <3

**Comment by vaxerski** [comment]
No, this is doable with a plugin or script, and I fail to see the usefulness of that to a broad audience. Maybe something for [xtra-dispatchers](https://github.com/hyprwm/hyprland-plugins/tree/main/xtra-dispatchers)
