### ISSUE TITLE
TV compact/expand animation for closing/opening windows

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#885]
This might be a bit hard to describe, but an animation for closing/opening windows that looks like an old-school turning off or on might look really cool, where folds upon itself or expands upon itself, like this:

![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F80%2F5d%2F5f%2F805d5fbc1b0370a1258009be3a32f1c5.gif&f=1&nofb=1&ipt=9686129995ef60409a4057d40c354cf442346a7c8f45333637882e002c374a50&ipo=images)

**Comment by vaxerski** [comment]
I mean yeah but i'd say it's quite low prio lol

**Comment by ThatOneCalculator** [comment]
Fair, it'd still be sick to see. I think something similar is in https://github.com/Selenium-H/Animation-Tweaks

**Comment by vaxerski** [comment]
won't be core, can be a plugin
