### ISSUE TITLE
What is hyprland-qtutils and why I need 300mb of new dependencies

### ISSUE THREAD

**Issue by DusanLesan** [hyprwm/Hyprland#8850]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```
0.45.2 on arch
```
Cannot paste since I do not have browser on affected machine but tell me if you really need it...

</details>

### Description

After updating system now, I was forced to accept bunch of new dependencies to be installed on my system. The chain ends with `hyprland-qtutils`

I have been presented with a extensive list of new dependencies like: qt6-base, breeze-icons etc. Turns out qt6-base is required by hyprland-qtutils. How to prevent this mess? Can I build Hyprland without all this?

### How to reproduce

Have V 0.46 installed from arch repo

**Comment by izmyname** [comment]
Hyprland tries to become tiling KDE.

> Can I build Hyprland without all this?
AFAIK it's just needed for a message, which pops up when the new version of the compositor is installed, and it wasn't a mandatory dep, when it was first released. You can manually remove the dep from `PKGBUILD` and `SRCINFO`

**Comment by DusanLesan** [comment]
> AFAIK it's just needed for a message, which pops up when the new version of the compositor is installed

Isn't `notify-send` available on wayland?

**Comment by izmyname** [comment]
Ask package maintainers

**Comment by DusanLesan** [comment]
I mean I do not have notifications to try it out, but I meant is it working since it can be installed obviously.

**Comment by izmyname** [comment]
It is. All notification daemons use `notify-send`, including wayland-exclusive ones - like `mako`

**Comment by DusanLesan** [comment]
I do not want to take anymore of your time. Thank you for responding. I am actually not willing to deal with manually editing build files or continuing to use software willing to add all this even with some big reasons and especially if added only because of notifications.

**Comment by vaxerski** [comment]
qt6-base is required by qtutils, because it requires qt.

breeze-icons are due to qqc2-desktop-style, which I'd want to get rid of too but @outfoxxed can't get the fuckin qml done

**Comment by DusanLesan** [comment]
What is qt used for? `breeze-icons` as far as I remember from earlier was also required by `qt6-base`. Can't you make all this optional?

**Comment by vaxerski** [comment]
it _technically_ is.

And no, because some features I want to use depend on having a graphical toolkit. Even xdph depends on qt for its share picker.

I don't know what your deal over qt is.

**Comment by DusanLesan** [comment]
I apologize. I just had wrong expectations from this project. Thank you

**Comment by outfoxxed** [comment]
Hyprland the compositor does not depend on qt itself. Hyprland's helper utilities do, because it's not worth the time to roll a custom graphical toolkit. You can build and use hyprland without them but you won't have a screen share picker or other future dialogs.

**Comment by DusanLesan** [comment]
> Hyprland the compositor does not depend on qt itself

That is what I would expect from a compositor.

> Hyprland's helper utilities do

As they are now tied in with the compositor, I could say Hyprland, the desktop environment, now depends on them. I see no reason for a compositor to show me any dialogs, pickers, or measure task responsiveness.

**Comment by izmyname** [comment]
> I see no reason for a compositor to show me any dialogs, pickers, or measure task responsiveness.

You only need `xdg-desktop-portal-hyprland` and any polkit agent for Hyprland to function properly.


> As they are now tied in with the compositor

They are not.

**Comment by vaxerski** [comment]
I don't think there is a point in arguing here.

Hyprland will continue working without qtutils for the forsseable future, only partially disabling features that depend on them if they are not found.

If you don't see _any_ reason for a compositor to show you _any_ dialog, you are probably either stupid, or you don't use anything but the terminal.

For an average user, a picker to select what to share when sharing a screen, an ANR dialog, and other(s) are very useful utilities that improve the workflow.

**Comment by DusanLesan** [comment]
I do not want to argue. You previously said that you are not willing to make all this optional and want to include features with a graphical toolkit, which led me to believe that I cannot separate qtutils from this project. I want to have my own dialogs, pickers, etc. I am used to dealing with dwm on a daily basis and I've tried emulating my workflow here, hoping to make them behave similarly enough to switch in the future.

**Comment by vaxerski** [comment]
if your stable system does not need screen sharing at all (xdph) or (in the future) permission management for recording your screen / etc, then yes. You do not need qtutils.

It will stay optional, but highly recommended.

**Comment by DusanLesan** [comment]
Cool. On Wayland/Hyprland, permission management is not done through polkit agents? Or are you talking about something else? Also I do need screen sharing (and have not really tried on wayland after all these years), but I was guessing that the picker GUI comes from the app you use (slack, browser) and the compositor only provides it the interface at best

**Comment by outfoxxed** [comment]
> Cool. On Wayland/Hyprland, permission management is not done through polkit agents?

Polkit is used for acquiring root perms, generally not inter-process perms.

> Also I do need screen sharing (and I have not really tried it on wayland after all these years), but I was guessing that the picker GUI comes from the app you use (slack, browser etc) and the compositor only provides it the interface at best

This could be done on X11 because the app could see every window on your screen. Under wayland, the app asks your desktop portal to give it a video stream, and the portal is responsible for showing you a picker. XDPH, Hyprland's picker, uses qt.

**Comment by DusanLesan** [comment]
Thanks for explaining. I will be waiting for that protocol to retry using wayland.
