### ISSUE TITLE
Key Binding Ignoring Modifiers

### ISSUE THREAD

**Issue by hellmind** [hyprwm/Hyprland#8863]
### Description

Currently, in Hyprland, there isn't a straightforward way to bind a key so that its action is executed regardless of whether any modifiers (like Super, Ctrl, Shift, etc.) are pressed.

Proposed Feature:

I would like to propose the addition of new syntax for bind or a new directive that allows completely ignoring modifiers when pressing a key. This would be useful for configurations like "push-to-talk," where you want the key to function regardless of modifiers.

Proposed Syntax:

For bind:
plaintext
bind = <no_mod>, <key>, <action>

Where <no_mod> could be a new keyword indicating that the action should be performed regardless of modifiers.
Or alternatively, a new directive:
plaintext
bind_ignore_mod = , <key>, <action>

Example Usage:

If I wanted to bind the Caps Lock key to execute a command regardless of modifiers, it could be:

plaintext
bind = <no_mod>, Caps_Lock, exec, /path/to/script.sh

or

plaintext
bind_ignore_mod = , Caps_Lock, exec, /path/to/script.sh

Reason and Benefit:

This functionality would simplify keyboard configurations for specific use cases like push-to-talk, where the key should work independently of other pressed modifiers. It would save the need for additional scripts or complicated setups to achieve the same result.

Possible Implications:

Need to review keyboard event handling to ensure this new functionality doesn't interfere with other bindings that do depend on modifiers.
Updated documentation to reflect this new configuration option.

Current State:

Currently, bindr is used for bindings that only work if no modifiers are pressed during the key press, but it doesn't fully address the case where you want to ignore modifiers entirely when pressing a key.

**Comment by hellmind** [comment]
My Specific Use Case:

In my current setup, I use Push-To-Talk (PTT) for Discord with multiple modifier combinations, but this still requires separate bindings for each condition:

plaintext
#ptt
bind = , Num_lock, pass, class:^discord$
bind = $mod, Num_lock, pass, class:^discord$
bind = CTRL, Num_lock, pass, class:^discord$
bind = $mod + CTRL, Num_lock, pass, class:^discord$
bind = CTRL, Num_lock, pass, class:^discord$

This setup shows how cumbersome it can be to manage PTT functionality with modifiers. Having a feature to ignore modifiers would significantly simplify this configuration.

**Comment by hellmind** [comment]
I think i found it:
i -> ignore mods, will ignore modifiers.

**Comment by vaxerski** [comment]
yep, it's there
