### ISSUE TITLE
Hyprland crashes when reading from socket2.sock is interrupted

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/Hyprland#887]
Hyprland seems to crash the moment I stop `socat` (with Ctrl+C), that's listening to the socket2.sock 

```bash
socat - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock > socat.txt
```

However this doesn't always happen, I was able to consistently replicate it only when quickly switching between workspaces and interrupting socat after that. With that, hyprland freezes for a moment and then crashes to TTY.

This same crash occurs when using netcat (`nc -U /tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock | while read test;do;echo $test;done`).

The used Hyprland was compiled from latest master (b71d7c9)

Attaching:
- coredump ([`coredump.txt`](https://github.com/hyprwm/Hyprland/files/9840804/coredump.txt))
- My hyprland config file ([`hyprland-config.txt`](https://github.com/hyprwm/Hyprland/files/9840822/hyprland-config.txt))
- Hyprland log ([`hyprland.log`](https://github.com/hyprwm/Hyprland/files/9840805/hyprland.log)),
- captured output coming from the Hyprland executable (each line prefixed with a unix timestamp) ([`captured-output.txt`](https://github.com/hyprwm/Hyprland/files/9840803/captured-output.txt)),
- Output from socat when this happened ([`socat.txt`](https://github.com/hyprwm/Hyprland/files/9840806/socat.txt)),

**Comment by vaxerski** [comment]
fixed in 0d7d7a970dc047517ed4d3922c1da3638cb51aed
