### ISSUE TITLE
Hyprland crashes when using kvm switch

### ISSUE THREAD

**Issue by mgbowe1** [hyprwm/Hyprland#888]
When I switch from my desktop to my laptop on my kvm switch hyprland (running on my desktop) crashes. This is repeatable behavior. I'm not sure if the crash happens after I switch from the desktop, or when I switch back. The kvm I'm using does not send EDID data.

I know this use case works on GNOME on wayland, so a fix is most likely possible.
Environment is Arch linux using the hyprland-nvidia-git AUR package and the recommended nvidia modifications from the wiki https://wiki.hyprland.org/Nvidia/

### Reproduction steps:
1) be connected to a kvm switch running hyprland
2) switch the kvm to a different input
3) switch the kvm back to hyprland system

### Expected Result:
hyprland is still running and the system hasn't been kicked back to the login manager

### Actual Result:
system has been kicked back to the display manager and hyprland is not running

#### Note:
I'm submitting this issue without logs temporarily as I need to reproduce the issue and collect them. I'll add them as a comment when I'm finished collecting them.

Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by mgbowe1** [comment]
[tmphyprlog-for-bug-report.log](https://github.com/hyprwm/Hyprland/files/9841235/tmphyprlog-for-bug-report.log)
Attached logs

**Comment by vaxerski** [comment]
> I know this use case works on GNOME on wayland

ha-ha. That doesn't mean anything. Test with sway / wayfire.

**Comment by mgbowe1** [comment]
Thanks for the response, I'll try sway to see if the issue is present there.

I was able to replicate the issue without actually switching the kvm. It seems to be a crash when a monitor is plugged in while hyprland is running.

Here's updated reproduction steps:

1) use multiple monitors
2) unplug one monitor's display cable (note that the workspaces will actually move to the other monitor)
3) plug the display cable back in, hyprland will crash and you'll either be in a tty or your login manager.

**Comment by ferrreo** [comment]
I am having this issue too with latest git when switching my kvm. 
Sway is fine. 
Also replicated it by just turning both monitors off, no kvm or unplug needed, just turn them off and wait a little bit.

**Comment by vaxerski** [comment]
give a coredump then

**Comment by ferrreo** [comment]
Ah I don't use systemd so that might be a pain, will try get one though

**Comment by vaxerski** [comment]
on all systems coredumps should be stored somewhere. If you find the dump file, you can use `gdb` to load it against the compiled binary.

**Comment by iraizo** [comment]
Got the same issue, pretty sure this is the correct coredump using `hyprland-git r2704.801a1719-1` 

[dump.tar.gz](https://github.com/hyprwm/Hyprland/files/11184322/dump.tar.gz)

**Comment by vaxerski** [comment]
if you're using a modern hl ver then pass me the crash report from `~/.hyprland` or `$XDG_CACHE_DIR/hyprland` if you have the cache dir set.

**Comment by iraizo** [comment]
[hyprlandCrashReport93109.txt](https://github.com/hyprwm/Hyprland/files/11184491/hyprlandCrashReport93109.txt)

here you go

**Comment by vaxerski** [comment]
haha almost the same shit as #804

**Comment by iraizo** [comment]
> haha almost the same shit as #804

Looks like it, if i can somehow help debugging/fixing this let me knoww

**Comment by nmccarty** [comment]
[hyprlandd.log](https://github.com/hyprwm/Hyprland/files/12032665/hyprlandd.log)
[hyprlandCrashReport5652.txt](https://github.com/hyprwm/Hyprland/files/12032666/hyprlandCrashReport5652.txt)

I did a debug build against `5e577ac` (latest commit at time of writing) and have attached my log and crash report.

This is unfortunately making hyprland nearly unusable for me, as KVM switch usage is a critical part of my workflow, so I'm highly motivated to help out getting this fixed. Please let me know if there's any more information I can provide or anything else my hasn't-touched-C++-in-a-decade ass can do to help out

**Comment by nmccarty** [comment]
After [`629e61c`](https://github.com/hyprwm/Hyprland/commit/629e61c7a56561ee5d565dda6d0d8b7c41dbe9c7) I am pleased to announce that hyprland now survives kvm switch usage for me

:tada: :tada: :tada:
