### ISSUE TITLE
0-indexed workspaces

### ISSUE THREAD

**Issue by Quantenzitrone** [hyprwm/Hyprland#889]
I'm coming from i3 and I would really like to have 0-indexed workspace numbers.
Well i could name every single workspace to have the previous number, 
but that is just a dirty workaround and only works for a finite amount of workspaces.

**Comment by vaxerski** [comment]
please no

**Comment by Quantenzitrone** [comment]
why not?

**Comment by vaxerski** [comment]
0 is used for other purposes. Generally all IDs have a purpose, and > 0 means ID-based ws for example, < -1337 named, -99 special, etc etc

 "just having 0 cuz i like it" is not a good enough argument for me to change how the system works internally

**Comment by Quantenzitrone** [comment]
hm thats true thanks for the answer
