### ISSUE TITLE
windowrule move negative values

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#890]
It would be helpful to be able to do something like

`windowrule = move (100%-400) 4,something`

Or any syntax you prefer, but basically being able to move a window relative to right side or bottom side of the screen.

**Comment by vaxerski** [comment]
done in 83ad59fae7d3d3afa6d827d918d32b7077a6b400

`windowrule = move 100%-400 4,something`

**Comment by primalmotion** [comment]
awesome thanks!

**Comment by primalmotion** [comment]
hum that does not seem to work. I see the window animating then disapearing out of visible bounds

```
windowrule = float,wttr
windowrule = size 390 200,wttr
windowrule = move 100%-400 30,wttr
```

**Comment by primalmotion** [comment]
basically a script that launches alacritty this way

```
alacritty --class wttr --hold -e curl https://wttr.in/\?m0
```

**Comment by vaxerski** [comment]
works completely fine on my end...

**Comment by primalmotion** [comment]
my bad it works. I somehow failed my yay -Syyu

**Comment by vaxerski** [comment]
dunce...

**Comment by primalmotion** [comment]
shit happens :) thanks for the patch
