### ISSUE TITLE
How to use install plugins in nixos without HM?

### ISSUE THREAD

**Issue by darshanCommits** [hyprwm/Hyprland#8902]
From what i can see, I must use home-manager to install plugins. I tried using hyprpm to actually install the plugin, but they fail to build, tried hacking my way through a nix flake, this was the result. 
![image](https://github.com/user-attachments/assets/b8b67673-318d-49dd-930e-9021fc8d3d98)

**Comment by vaxerski** [comment]
this is a place to report issues not ask for support. Please use discussions, the discord server, or online forums for that.

**Comment by fufexan** [comment]
HM is not a requirement. As long as you have something that can generate a hyprconf file from a nix expression (or at least interpolate the plugin build result) you should be fine. The nix2hypr generator wasn't integrated into NixOS but can be ported from HM.
