### ISSUE TITLE
XCURSOR_SIZE for qt and xwayland cannot both be satisfied

### ISSUE THREAD

**Issue by Aleksanaa** [hyprwm/Hyprland#894]
I'm using xwayland with advised patches with hyprland 1.25x scaling, and GDK_SCALE=2. In order to make xwayland cursor display normally, I need XCURSOR_SIZE=48, but for Qt I need XCURSOR_SIZE=24. Obviously they can't both be satisfied.

**Comment by vaxerski** [comment]
you mean Qt native? What about gtk native?

**Comment by Aleksanaa** [comment]
> you mean Qt native? What about gtk native?

Gtk native works with hyprctl setcursor. Qt cursors behave larger if environment variables not set, as mentioned in document.

**Comment by vaxerski** [comment]
so, what you want is to export a variable only for XWayland?

**Comment by Aleksanaa** [comment]
> so, what you want is to export a variable only for XWayland?

It's acceptable, if can be achieved (already tried xsettingsd xrdb .x* config file but with no luck)

**Comment by vaxerski** [comment]
I can code it in.

**Comment by TheSunCat** [comment]
This would entirely solve the issue of cursors being small while on XWayland windows!

**Comment by Aleksanaa** [comment]
> so, what you want is to export a variable only for XWayland?

This is a workaround. The permanent solution would be waiting for wayland to export cursor size accordingly, and Qt to support it. But we would also very appreciate a workaround in the short term, though.

See https://lists.freedesktop.org/archives/wayland-devel/2018-October/039515.html

**Comment by TheSunCat** [comment]
Is anything needed for the workaround of defining variables for XWayland only to be implemented?

**Comment by vaxerski** [comment]
I've tried that but it does not work.
