### ISSUE TITLE
Blank screen except for a cursor.

### ISSUE THREAD

**Issue by Si-Ki** [hyprwm/Hyprland#897]
### Discussed in https://github.com/hyprwm/Hyprland/discussions/896

<div type='discussions-op-text'>

<sup>Originally posted by **Si-Ki** October 22, 2022</sup>
Hyprland version: hyprland-bin form aur `0.16.0 beta-1`
I wasn't sure if this classifies as a bug, so posting this here instead of creating an issue,

I install hyprland, 
I make this [file](https://0x0.st/oxL_.sh), and run it 
hyprland starts, I see cursor, nothing else, 
I can launch alacritty, but can't see it (sure that it launched cuz I wrote "killall Hyprland" and it worked, the screen was black all the time, the cursor changed to a caret)

Log [here](https://0x0.st/oxLQ.log),

sorry for any stupid mistakes I might have made, and thank for helping @vaxerski</div>

**Comment by vaxerski** [comment]
@Dickby this looks to me like your matrix PR broke GLES2 compat

```
[wlr] [GLES2] GL_INVALID_VALUE in glUniformMatrix(matrix transpose is not GL_FALSE)
[wlr] [GLES2] GL_INVALID_VALUE in glUniformMatrix(matrix transpose is not GL_FALSE)
[wlr] [GLES2] GL_INVALID_VALUE in glUniformMatrix(matrix transpose is not GL_FALSE)
[wlr] [GLES2] GL_INVALID_VALUE in glUniformMatrix(matrix transpose is not GL_FALSE)
[wlr] [GLES2] GL_INVALID_VALUE in glUniformMatrix(matrix transpose is not GL_FALSE)
```

@Si-Ki can you try compiling with LEGACY_RENDERER? (see wiki)

**Comment by Si-Ki** [comment]
fuck, I was waiting at the discussion page... posted as you asked [here](https://github.com/hyprwm/Hyprland/discussions/896#discussioncomment-3940558)

also, I go compile with that flag, might take a long time, thanks @vaxerski

**Comment by Si-Ki** [comment]
Compiled with legacy_renderer, log(when ran with [startw](https://0x0.st/ox93.sh) file [here](https://0x0.st/ox94.log), still the same results... I mean, Graphically. @vaxerski

**Comment by vaxerski** [comment]
basically, blame Dickby, and your poor choice of hardware. Also, no need to ping me every single time.

**Comment by Si-Ki** [comment]
ok, cool

**Comment by vaxerski** [comment]
we should make GLES2 have the matrix transposed by us tho @Dickby

**Comment by vaxerski** [comment]
Should be fixed on HEAD with LEGACY_RENDERER.

**Comment by Dickby** [comment]
@vaxerski , i found this issue just now! I'm really sorry for causing this issue and not responding. 
I was quite busy at that time. 
Fucking GLES, stupid me!

**Comment by vaxerski** [comment]
lol no worries
