### ISSUE TITLE
Independent Touchpad Acceleration Profile

### ISSUE THREAD

**Issue by Kab1r** [hyprwm/Hyprland#898]
I want to be able to have a flat acceleration profile on mice and adaptive acceleration on trackpads.

The config might look something like this:
```conf
input {
    accel_profile=flat
    touchpad {
        accel_profile=adaptive
        natural_scroll=yes
        tap-to-click=yes
    }
}
````

**Comment by vaxerski** [comment]
you have a per-device accel profile though, why not use that?
