### ISSUE TITLE
waybar popups shown behind windows even when set layer to top

### ISSUE THREAD

**Issue by Aleksanaa** [hyprwm/Hyprland#899]
archlinux
waybar 0.9.13-2.1
hyprland r1918 (latest git at this moment) or 0.16.0beta-1
![1](https://user-images.githubusercontent.com/42209822/197326103-59f4055f-8345-419a-8aa2-d900b5a69d36.png)
![2](https://user-images.githubusercontent.com/42209822/197326128-01c114c2-d4ed-4a0e-9a7d-7a24059eaab0.png)

```
// waybar-clock
    "clock": {
		"interval": 60,
		"align": 0,
		"rotate": 0,
        //"timezone": "America/New_York",
        "tooltip-format": "<big>{:%B %Y}</big>\n<tt><big>{calendar}</big></tt>",
        "format": " {:%H:%M}",
        "format-alt": " {:%a %b %d, %G}"
    },
```

```
    "include": "~/.config/waybar/modules",
    "name": "main-bar", 
    "id": "main-bar", 	
    "layer": "top", 	
    "mode": "dock", 	
    "exclusive": true, 	
    "passthrough": false, 
    "position": "top",
    "output": "eDP-1", 	
    "height": 36, 		
    "width": "", 		
    "spacing": 6, 		
    "margin": 0, 		
    "margin-top": 0, 	
    "margin-bottom": 0, 
    "margin-left": 0, 	
    "margin-right": 0, 	
    "fixed-center": true, 
    "ipc": true, 		
```

Sway already has [this pull request](https://github.com/swaywm/sway/pull/4781) merged. May be releavant

**Comment by JustSimplyKyle** [comment]
They already said the layer is set to top

**Comment by Aleksanaa** [comment]
> cant even repo, lol

The waybar version is said above btw.

**Comment by Aleksanaa** [comment]
> i still dont know what's v0.9.13-**2.1** but it still doesnt happen to me on the official waybar package on the community repo.

That is the wrong version. Tried 0.9.13-1 and git version (right now), the same.

**Comment by Aleksanaa** [comment]
tried `"passthrough":true`, but still doesn't work

**Comment by vaxerski** [comment]
If the layer popups render below windows, it's safe to assume waybar is NOT on the top layer (you can see for yourself that it is not with `hyprctl layers`)

This means that this is purely your fault (either misconfiguration or forgetting waybar does NOT hot-reload the config and you need to restart it)

**Comment by Aleksanaa** [comment]
> If the layer popups render below windows, it's safe to assume waybar is NOT on the top layer (you can see for yourself that it is not with `hyprctl layers`)
> 
> This means that this is purely your fault (either misconfiguration or forgetting waybar does NOT hot-reload the config and you need to restart it)

![IMG_20221023_184235_219.png](https://user-images.githubusercontent.com/42209822/197387644-c0c3c0be-07e8-4247-82a1-348403b34cec.png)

Firstly I've checked that no layer is set in modules. Then the config file. Then I killed and restarted waybar. Then hyprland layers.

I don't think that is the case.

**Comment by vaxerski** [comment]
You can clearly see waybar is on layer 1 which is the BOTTOM layer, when it needs to be on layer 2, which is the TOP layer:

![image](https://user-images.githubusercontent.com/43317083/197388737-281ff7da-7189-431d-8531-08268ab623dd.png)

Since the layer is decided 100% by the app itself, it's an issue in your config without a shed of doubt.

**Comment by Aleksanaa** [comment]
> You can clearly see waybar is on layer 1 which is the BOTTOM layer, when it needs to be on layer 2, which is the TOP layer:
> 
> ![image](https://user-images.githubusercontent.com/43317083/197388737-281ff7da-7189-431d-8531-08268ab623dd.png)
> 
> Since the layer is decided 100% by the app itself, it's an issue in your waybar config (or an issue in waybar, but it works without any for me) without a shed of doubt.

I've figured out why. Setting `"mode": "dock"` causes the issue. Since it's quite confusing even after reading waybar wiki, maybe you can add it to the document.

**Comment by vaxerski** [comment]
That's down to waybar, no clue why we should make waybar's docs for them

**Comment by Aleksanaa** [comment]
> That's down to waybar, no clue why we should make waybar's docs for them

https://wiki.hyprland.org/FAQ/#waybar-popups-render-behind-the-windows

here

**Comment by dev-null-undefined** [comment]
> > You can clearly see waybar is on layer 1 which is the BOTTOM layer, when it needs to be on layer 2, which is the TOP layer:
> > ![image](https://user-images.githubusercontent.com/43317083/197388737-281ff7da-7189-431d-8531-08268ab623dd.png)
> > Since the layer is decided 100% by the app itself, it's an issue in your waybar config (or an issue in waybar, but it works without any for me) without a shed of doubt.
> 
> I've figured out why. Setting `"mode": "dock"` causes the issue. Since it's quite confusing even after reading waybar wiki, maybe you can add it to the document.

had the exact same issue, any chance on adding this to the documentation?
I know this is up to waybar but still would have been nice to know

**Comment by vaxerski** [comment]
make a pr to the wiki it's a public repo?

**Comment by Sinhran** [comment]
> > You can clearly see waybar is on layer 1 which is the BOTTOM layer, when it needs to be on layer 2, which is the TOP layer:
> > ![image](https://user-images.githubusercontent.com/43317083/197388737-281ff7da-7189-431d-8531-08268ab623dd.png)
> > Since the layer is decided 100% by the app itself, it's an issue in your waybar config (or an issue in waybar, but it works without any for me) without a shed of doubt.
> 
> I've figured out why. Setting `"mode": "dock"` causes the issue. Since it's quite confusing even after reading waybar wiki, maybe you can add it to the document.

Was having the exact problem and fixed it by changing "mode" to "mod". I'm pretty sure this isn't the right way but hey, works.
