### ISSUE TITLE
hyprctl: add support for getting mouse location

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#900]
maybe this is possible? idk

**Comment by vaxerski** [comment]
Umm it is yeah, but it would encourage spamming socket1, which is generally a bad idea. Why?

**Comment by JustSimplyKyle** [comment]
I wanna make a script that can accept `bind=super,mouse_up,workspace,e+1` only if the cursor is in a specific location

**Comment by vaxerski** [comment]
added in 4aebb73de005e50bb08bacb0bb26ea89e0bd2818

**Comment by JustSimplyKyle** [comment]
After thought, wouldn't this be better if you create a UNIX socket just for this?(kinda like socket2)
If that is possible, maybe add an option to disable this outputing to a UNIX socket for performance/security reasons

**Comment by vaxerski** [comment]
no
