### ISSUE TITLE
Dialog focus/refocus issues with forceinput

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#901]
There are some focusing/refocusing issues when opening and closing dialogs. The documentation suggests to add `forceinput` for solving the issue where windows would not receive focus in certain situations. However, when windows get closed, the pass the focus to the wrong window.

## Steps to reproduce
- Add `windowrule = forceinput, (.+)`
- Open VSCode and Chrome on the same workspace and monitor
- Focus VSCode and hit <kbd>Ctrl+Shift+O</kbd> to launch the open-dialog
- The dialog is focused
- Close dialog with <kbd>Esc</kbd>
- Chrome is focused instead of VSCode

**Comment by vaxerski** [comment]
odd xwayland issues, welcome to xwayland. Try using both chrome and vscode in wayland native (`--enable-features=UseOzonePlatform --ozone-platform=wayland`)

**Comment by vaxerski** [comment]
should be fixed anyways with c04563734e0482bd10045c70d9d85177e5448143
