### ISSUE TITLE
Hyprland crashes at launch

### ISSUE THREAD

**Issue by Cherro59** [hyprwm/Hyprland#902]
Hyprland crashes at start with strings like : "Backend seat failed to open seat.skipping" and that's all. 
Btw, if i try open it in gnome-terminal its go far away and stops  when there are already working wayland compositor.
I'm on fedora 37 with libdrm2.4.113 which

 i built by myself
There is my [log.txt](https://github.com/hyprwm/Hyprland/files/9847317/log1.txt)

**Comment by brodi1** [comment]
@Cherro59 Hi! normally if you report a crash it would be very useful if you share a `coredump` with us.

**Comment by Cherro59** [comment]
There is no any info about Hypland in core dump list

**Comment by vaxerski** [comment]
give the log with HYPRLAND_LOG_WLR=1 then

**Comment by vaxerski** [comment]
and it leaves no coredump?

**Comment by Cherro59** [comment]
Still nope

**Comment by vaxerski** [comment]
then it's an issue with your system

**Comment by vaxerski** [comment]
there's literally nothing that suggests anything being amiss. Probably fedora issue.

**Comment by pwnwriter** [comment]
I was having the same issue when I set my `GRUB_CMDLINE` option to `nomodset`. (It just disables kernel mode settings `kms`) fyi.
I removed it and its working well :)
