### ISSUE TITLE
`size` not respected if workspace unfocused

### ISSUE THREAD

**Issue by rscottyy** [hyprwm/Hyprland#904]
Simple one to reproduce.

1. Ensure the following rules 
class referenced as _x_
_x_ opens silently on workspace 9. `windowrulev2=workspace 9 silent,class:^(x)$`
_x_ has size rule. `windowrulev2=size 700 350,class:^(x)$`
_x_ is floating. `windowrulev2=float,class:^(x)$`
2. Window will not respect rules if the target workspace is not focused.

As shown in the video below.
https://streamable.com/ctjlrf

**Comment by rscottyy** [comment]
s/opens on/opens silently on/

**Comment by rscottyy** [comment]
e4527c6 was supposed to fix this bug, I previously had this problem. You can also see additional information at
https://discord.com/channels/961691461554950145/961694014615208048/1024685093312270356

**Comment by vaxerski** [comment]
fixed in 1d0d350fc31c7b7b834dcf15016bf1495b81d7e1

**Comment by rscottyy** [comment]
I have tested it,
Now `nofocus` windows don't seem to listen to `workspace x silent`.
As shown in the video below.
https://streamable.com/baj2e4

**Comment by rscottyy** [comment]
https://streamable.com/vatpoi
here is a better video

**Comment by rscottyy** [comment]
@vaxerski

**Comment by vaxerski** [comment]
stop pinging me ffs. It works for me, maybe you didn't update. check `hyprctl version`

**Comment by rscottyy** [comment]
I did update that's why I shown you cf869d9. 

I might be dumb, I'm not that dumb lmao

**Comment by vaxerski** [comment]
check `hyprctl version`

**Comment by rscottyy** [comment]
https://imgur.com/a/FTMT7RF

**Comment by vaxerski** [comment]
you can paste images here. Imgur is over capacity.

**Comment by rscottyy** [comment]
I have no idea how you managed to fck it up this badly. Lol.
https://streamable.com/pnyaql

**Comment by rscottyy** [comment]
Steam is now launching in workspace 9 (where mpd stuff is supposed to be)
even tho it has rules (https://gitlab.com/rscotty-rice/dotfiles/-/blob/main/home/rscott/.config/hypr/steam.conf)

**Comment by rscottyy** [comment]
Yeas...

The issue is has two videos, before and after this patch, showing that `silent` was working, it is now not working. And surely you are aware of this...

Would you really want me to prove to you that silent was working before cf869d9? Since you somehow believe I'm talking bollocks or?

**Comment by rscottyy** [comment]
Before cf869d9:
https://streamable.com/vatpoi
After cf869d9:
https://streamable.com/8k1iha
& on startup: https://streamable.com/pnyaql

**Comment by vaxerski** [comment]
https://user-images.githubusercontent.com/43317083/197565874-f1909367-5050-4d56-85bc-d6d39c8295d4.mp4

cuz u are talking bollocks

**Comment by vaxerski** [comment]
Wait are you setting a silent rule to move to a workspace on a different monitor?? That's not allowed, you need to set `monitor` rule too.

**Comment by rscottyy** [comment]
> Before https://github.com/hyprwm/Hyprland/commit/cf869d963687d26876f6e203a925cd6648380c4a:
> https://streamable.com/vatpoi
> After https://github.com/hyprwm/Hyprland/commit/cf869d963687d26876f6e203a925cd6648380c4a:
> https://streamable.com/8k1iha
> & on startup: https://streamable.com/pny

h.

clearly the shit worked be4 and doesn't work now.
blaintant autism.

**Comment by rscottyy** [comment]
Soz for the language bud but I dont speak bollocks.

**Comment by vaxerski** [comment]
69f1d7b3607bb088512420052b9e0d48e529772d should fix all your issues and please go outside and touch grass now

**Comment by rscottyy** [comment]
Newest silent patch (69f1d7b), still has issues.

For odd reasons my mpd workspace (9) is bound to my TV (HDMI-A-2), despite having rules (wsbind) to specifically bind workspace 9 to my monitor (HDMI-A-1). 

As shown in the video below.
https://streamable.com/qtz7o6
