### ISSUE TITLE
Allow hash escaping in the config

### ISSUE THREAD

**Issue by anstadnik** [hyprwm/Hyprland#905]
Sometimes in the config there is a need to use a hash (#) symbol (for example, to define color or message etc). Currently AFAIK there is no way to escape it. Please allow to do so using backslash or 2 hashes
https://github.com/hyprwm/Hyprland/blob/077c1491a8590488256aa8cb207b3e4ed7f05f88/src/config/ConfigManager.cpp#L1019-L1025

**Comment by vaxerski** [comment]
done in cdb331076afcd1069d4d62805c3b48d237cc0b05
`##` will escape
