### ISSUE TITLE
More complex animation curves

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#907]
As seen [here](https://easings.net/#), there are much more complex animations then are supported in hyprland right now, such as the [EaseInBounce](https://easings.net/#easeInBounce) animation. Altough no priority, I'd really like to seen support for such animation eventually.

**Comment by EysseW** [comment]
What do you mean? I think it is really cool to have o window bouncing on the bottom of your screen when I switch workspace. Something that's not possible (I believe) as of writing. 

If you meant "I don't like it", say that instead of "no point".

**Comment by vaxerski** [comment]
calculating nth-power beziers is difficult and would require a pile of code more to parse, even when we ignore the fact they'd be less efficient.

I think it's a lot of work for something very niche and ultimately useless.

**Comment by EysseW** [comment]
Understandable, have a nice day!
