### ISSUE TITLE
Fullscreen 1 should respect no_gaps_when_only

### ISSUE THREAD

**Issue by micamoan** [hyprwm/Hyprland#908]
If you have dwindle.no_gaps_when_only=1, then set a window to fullscreen with fullscreen 1 (to keep the panel), you get gaps between the monitor edge and the window. It'd be nice if the config value was respected in this case and there were no gaps. (Perhaps an additional variable for whether fullscreen 1 should have no gaps?)

**Comment by vaxerski** [comment]
done in 5530cf6e7939365ef6197a50c59bed20a64e3e11
