### ISSUE TITLE
Vivaldi loses focus on creation of new tab

### ISSUE THREAD

**Issue by owenh28** [hyprwm/Hyprland#910]
Vivaldi loses focus on creation of new tab / open link in new tab etc...
Makes it annoying to type in address bar, as I have to move the mouse from the center of the screen. This only happens on my second monitor (1920x1080). Main monitor is 3840x2160

Monitor config:
`monitor=eDP-1,preferred,0x0,2`
`monitor=,preferred,auto,1`

Mouse:
`follow_mouse=1`

**Comment by vaxerski** [comment]
use in native wayland and check if it still happens (`--enable-features=UseOzonePlatform --ozone-platform=wayland`)

**Comment by owenh28** [comment]
oops--
I have them set in Vivaldi://flags, would I need to also launch it with the args in the command line?

**Comment by vaxerski** [comment]
check if it is running in xwayland with `hyprctl clients`. Look for the `xwayland:` flag

**Comment by owenh28** [comment]
Here is the result:     
```
Window 58689a0 -> Vivaldi loses focus on creation of new tab · Issue #910 · hyprwm/Hyprland - Vivaldi:
	at: 967,52
	size: 931,1006
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: 
	title: Vivaldi loses focus on creation of new tab · Issue #910 · hyprwm/Hyprland - Vivaldi
	pid: 63941
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
```
Looks like xwayland is not being used.

**Comment by owenh28** [comment]
That seems to have fixed it! Thank you

**Comment by vaxerski** [comment]
defaulted it to false.
