### ISSUE TITLE
Media control keys not working

### ISSUE THREAD

**Issue by demperor-music** [hyprwm/Hyprland#914]
# **The issue**
Whenever i try to stop a song via the button on my keyboard, or use any other media control key it just does nothing.

## **Steps to reproduce**

1. Play any media via youtube or media app
2. Try using media control keys

## **Expected outcome**

The stop key should stop the playing song, the "next song" key should play the next song in queue and so on

## **Noted outcome**

Just straight up no response

**Comment by brodi1** [comment]
@demperor-music 
you can use these bindings if you have ![playerctl](https://github.com/altdesktop/playerctl) installed
use `bindl=` if you want to be able to use them while its locked. If you don't want this just use `bind=`
```
bindl=,XF86AudioPlay,exec,playerctl play-pause
bindl=,XF86AudioPause,exec,playerctl pause
bindl=,XF86AudioStop,exec,playerctl stop
bindl=,XF86AudioNext,exec,playerctl next
bindl=,XF86AudioPrev,exec,playerctl previous
```
