### ISSUE TITLE
Workspace improvements

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#916]
I'm running awesomewm currently and been playing around with Hyprland to probably switch to. Here are some workspace suggestions, which I think might be useful to others too.

## 1. Show empty workspaces (waybar)
It would be nice to have empty workspaces shown in waybar too. 

## 2. Styling for active workspace even when the monitor has not the focus (waybar)
As per the waybar documentation, `#workspaces button.active` (hyprland) sets the styling for the active workspace. However, this styling is only applied on the focused monitor, but not on other monitors. Do open/active workspaces of non-focused monitors have a class assigned to it?

## 3. Workspaces per output, aka tags, aka groups

This one leads to a lot of confusion, since not everyone can explain what the actual demand is. But I'll try me best. In short, it's basically how awesomewm handles it.

Let's say I have 4 monitors (DP-1... DP-4) and **n** workspaces  (A, B, C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q).
Now, I'd expect each output to show all 3 workspaces (A, B, C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q). When I configure `bind=SUPER,7,workspace,7` it should switch to **G**, but only on the currently focused monitor.

iirc, there's some mentioning about workspace groups in the wayland specs, but I'm not sure whether it covers this usecase or not.

### 3.1 Partial workaround
For anyone interested, I was able to find a workaround for this specific usecase. 

<details>
<summary>hyprland.conf</summary>

This will bind workspace numbers 11-13 to DP-1, 21-23, to DP-2, ... etc. The numbers are apart by 10, so one can use the numbers 1-0 to switch to the workspaces
```
wsbind=11,DP-1
wsbind=12,DP-1
wsbind=13,DP-1

wsbind=21,DP-2
wsbind=22,DP-2
wsbind=23,DP-2

wsbind=31,HDMI-A-1
wsbind=32,HDMI-A-1
wsbind=33,HDMI-A-1

wsbind=41,DP-3
wsbind=42,DP-3
wsbind=43,DP-3

workspace=DP-1,11
workspace=DP-2,21
workspace=HDMI-A-1,31
workspace=DP-3,41

bind=SUPER,2,exec,~/.local/bin/setworkspace.sh 2

```
</details>

<details>
<summary>setworkspace.sh</summary>

```bash
#!/bin/bash
from=$(hyprctl -j monitors | jq -r '.[] | select(."focused"==true).activeWorkspace.id') # ex: 21
mod=$(( $from%10)) # ex: 1
to=$(($from - $mod + $1)) # ex 21-1+2
hyprctl dispatch workspace $to
```

</details>

<details>
<summary>.config/waybar/config</summary>
This will assign a custom icon/text to the specific workspace numbers

```
"wlr/workspaces": {
        "format": "{icon}",
        "format-icons": {
            "1": "A ",
        "11": "A ",
        "21": "A ",
        "31": "A ",
        "41": "A ",
        "2": "B ",
        "12": "B ",
        "22": "B ",
        "32": "B ",
        "42": "B ",
        "3": "C ",
        "13": "C ",
        "23": "C ",
        "33": "C ",
        "43": "C ",
            "focused": "",
            "default": ""
        },
        "active-only": false
    },
```
</details>

## 4. m+1 seems not to work
`bind=SUPER_SHIFT,l,workspace,m+1` I'd expect it to switch to the next workspace on the current monitor, but it does not. Am I misunderstanding something?

**Comment by vaxerski** [comment]
1. that's up to waybar. It's missing the functionality atm on wlr/workspaces, and there is an open issue.

2. not possible as per how the protocol works.

3. Not planned as it's possible with a simple script, as you have managed to do.

There are also programs written in go and rust iirc to do the same if I'm not mistaken called "hyprsome".

4. weird, I'll check.

**Comment by vaxerski** [comment]
4. works for me. Remember it only switches to *open* workspaces.

**Comment by ad-on-is** [comment]
aah ok... thx!
