### ISSUE TITLE
Are wayland compositors interchangeable?

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#917]
I wanted to implement a window switcher with wofi/rofi, etc... and found this script for swaywm:
https://github.com/argosatcore/Deb_Dots/blob/main/.local/bin/window_selector.sh

For Hyprland, I'd need to adapt **the whole script**, thereforeI was curious, whethere wayland compositors are supposed to be interchangeable as per the specs, so that I could just swap out `swaymsg -t get_tree` to `hyprctl -j clients`, instead of rewriting the whole script.

**Comment by vaxerski** [comment]
no.

**Comment by MahouShoujoMivutilde** [comment]
No, but there is https://github.com/hyprwm/Hyprland/discussions/830#discussioncomment-3868467
