### ISSUE TITLE
Firefox takes a long time to start (~20 seconds)

### ISSUE THREAD

**Issue by AndroGR** [hyprwm/Hyprland#929]
I switched to Hyprland yesterday, and while it is great, Firefox takes a long time to open. This is only happening on Firefox, no other program. On KDE (Which I have as a backup) it opens instantly, same on XFCE. Also Brave works as expected. Why is this happening?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open

If you have used kde wayland, make sure to also uninstall the kde desktop portal as it will interfere.
