### ISSUE TITLE
Support for more gestures

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#930]
With how great the workspace swipe gestures feel, it would be great to add more 1:1 gestures to Hyprland. Some ideas that would be very useful in my workflow (with a large touchpad), more of a wishlist as I know some of these would be hard to implement:
- [ ] 5-finger pinch to close window
- [ ] Four-finger pinch/expand to zoom in and out of the screen (currently I use hyprpicker to get a sort of zoom effect, but it's not practical)
- [ ] Three-finger click-and-drag to move a window around
- [ ] Drag up for an overview of all workspaces or open windows
- [ ] Configurable workspace swiping up/down instead of left-right

**Comment by fufexan** [comment]
Imo only the last point is remotely feasible right now. The rest would need those specific functions to be implemented.

> Three-finger click-and-drag to move a window around

Hmm, how would you differentiate that from 3-finger swipe?

> Drag up for an overview of all workspaces or open windows

I believe vaxry said he won't make it, as this isn't gnome.

**Comment by vaxerski** [comment]
the last point is already impl'd. If workspace swipe has style vert, swiping will be vertical too.

**Comment by vaxerski** [comment]
pinch to close - no
pinch to zoom - zoom in itself is eeeeh I have not much against it existing, but coding it would make the codebase a bit more ugle
move a window - no
overview - see fuf's reply above
