### ISSUE TITLE
Commit to avoid layout changes when unnecessary in applyMonitorRule breaks Multi-Monitor-Setup

### ISSUE THREAD

**Issue by Gajus84** [hyprwm/Hyprland#931]
Seems that commit 05f3eeb breaks Multi-Monitor-Rendering.

Only one monitor gets rendered, while the second does not. 
In my setup, DP-2 works and DP-1 stays black. 
All monitors get detected properly (via hyprctl), workspaces are created. Reverting to before the commit solves the issue.

**Comment by vaxerski** [comment]
do you think this was unintentional?

**Comment by vaxerski** [comment]
if so, you are right. Fixed in 2caebb3b108fdc57fd5da3d46832cbef51bd110f

**Comment by Gajus84** [comment]
Indeed, I did. Unfortunately, it seems 2caebb3 isn't fixing it for me. I autostart apps on both monitors, so the workspaces are in use.

**Comment by vaxerski** [comment]
reverted the changes. Check now.

**Comment by Gajus84** [comment]
Yep, it's working again.
