### ISSUE TITLE
Source games don't go fullscreen

### ISSUE THREAD

**Issue by Redlolz** [hyprwm/Hyprland#932]
When launching a Source engine game with fullscreen enabled in the game settings, it does not launch fullscreen.

![Screenshot-2022-10-29_21:59:25](https://user-images.githubusercontent.com/11429984/198850495-6b877139-d9d1-4ee9-9eea-5b8668b26203.png)

![Screenshot-2022-10-29_22:06:14](https://user-images.githubusercontent.com/11429984/198850666-57711a46-6943-4633-be3d-f3e187254809.png)

This does not happen in other games that are not based on the Source engine, I've tested OMORI and Unturned and both launch fullscreen (although in Unturned waybar acts a little funky).

![Screenshot-2022-10-29_22:04:33](https://user-images.githubusercontent.com/11429984/198850643-39154d61-cd0f-445e-91d2-d35acafa86aa.png)

Current workaround is using the keycombo that activates fullscreen or maybe setting a window rule for every Source game.

**Comment by vaxerski** [comment]
it's the game's fault. Not much else to say. Maybe also X11's fault. Stupid protocol.

**Comment by Redlolz** [comment]
Oh lol then I'm the one acting funky.
Guess I'll have to create an issue at the CS:GO repo.
Also thanks for creating Hyprland, it works more intuitively than any window manager I've ever used.

**Comment by vaxerski** [comment]
> Guess I'll have to create an issue at the CS:GO repo.

I'd advise against. It doesn't matter + it's prolly hyprland's fault.

**Comment by AbisamW** [comment]
It's not only source games. Running any game through gamescope --fullscreen results in the same issue. Gamescope launches in windowed mode but at the resolution of the monitor.

**Comment by vaxerski** [comment]
afaik gamescope just doesn't pass those events.

**Comment by AbisamW** [comment]
I have the same issue with Hearts of Iron IV, but if you do some magic to launch the game using the system SDL2 library instead of the bundled one and set SDL_VIDEODRIVER=wayland the game launches in fullscreen mode, so it's probably an XWayland issue

**Comment by AbisamW** [comment]
Tested gamescope --fullscreen on sway and kde plasma wayland. It seems to work perfectly, so it's a Hyprland/XWayland issue.
