### ISSUE TITLE
IntelliJ Idea (goland) stops responding to keystrokes in context interaction

### ISSUE THREAD

**Issue by labi-le** [hyprwm/Hyprland#933]
after changing the file name, the code editor does not respond to keyboard presses

_JAVA_AWT_WM_NONREPARENTING is enabled

https://user-images.githubusercontent.com/65619560/198860124-542d0524-0c8e-420b-97c3-34f9c3b50fb6.mp4

**Comment by System-x64** [comment]
how did you even manage to get intelliJ IDEA running!? for me it just breaks....i have tried `export _JAVA_AWT_WM_NONREPARENTING=1` in `~/.profile` still no success :"(

**Comment by labi-le** [comment]
> how did you even manage to get intelliJ IDEA running!? for me it just breaks....i have tried `export _JAVA_AWT_WM_NONREPARENTING=1` in `~/.profile` still no success :"(

i run ide with jetbrains toolbox

**Comment by System-x64** [comment]
OMG!! THANK YOU SO MUCH DUDE!!!!! it worked....have been trying to use android studio in hyprland for days

**Comment by labi-le** [comment]
Press Help | Edit Custom VM options...
add 
```sh
-Drecreate.x11.input.method=true
```
restart ide

**Comment by dragove** [comment]
This happens after a popup menu missing. For example, if you use `ctrl+shift+f` to search texts and press `Enter` to open a file. Then the search box is missing, and it seems that the focus of editing is still in the search box and not come back to the editor area. Temporary solution is right click in file tree (any folder or file) and select refactor or new or other things which can produce a new popup and make the focus back, then cancel the popup and things will be fine.

**Comment by dragove** [comment]
Add `_JAVA_AWT_WM_NONREPARENTING=1` in profile or add
```
-Drecreate.x11.input.method=true
-Dawt.ime.disabled=true
```
in vmoptions didn't help in my situation.

**Comment by pltanton** [comment]
Reformatting code `ctrl+alt+l` also represent that issue in intellij idea.

**Comment by pltanton** [comment]
I notice, that you got correct behavior if your mouse pointer is over the popup before pop-up window closed. It relates to that comment https://github.com/hyprwm/Hyprland/issues/1229#issuecomment-1353216339 . As a extremely dirty агзе hack we can make a script, that monitor for new floating windows with intellij-idea class, which will move cursor in center of that windows D:

Or even better script, that will watch for intellij-idea window closes and if other intellij-idea client is in focus it will "refocus" on that client. That hack looks better imo, but I can't find any hyprctl command to implement it.

**Comment by dragove** [comment]
https://github.com/hyprwm/Hyprland/issues/1317#issuecomment-1386074867 may help ones who wanna a better experience on ij's IDEs. 

quote configuration:
```
windowrulev2 = forceinput,class:^jetbrains-
windowrulev2 = windowdance,class:^jetbrains-
```

**Comment by hikkidev** [comment]
I use the following rules:

hypr.conf
```
# Jetbrains products
windowrulev2 = float,floating:0,class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = float,class:^(jetbrains-.*),title:^(Welcome to.*)
windowrulev2 = center,class:^(jetbrains-.*),title:^(Replace All)$
windowrulev2 = forceinput,class:^(jetbrains-.*)
```
Env:
`_JAVA_AWT_WM_NONREPARENTING=1`

Custom VM opt:
```
-Drecreate.x11.input.method=true
-Dawt.ime.disabled=true
```

**Comment by android10** [comment]
@System-x64 for android studio you can use @hikkidev solution (thank you very much 💪🏻 ) , but replacing `jetbrains` for `android`. At least in my case, this improved considerably:

```bash
# android studio
windowrulev2 = float,floating:0,class:^(android-.*),title:^(win.*)
windowrulev2 = float,class:^(android-.*),title:^(Welcome to.*)
windowrulev2 = center,class:^(android-.*),title:^(Replace All)$
windowrulev2 = forceinput,class:^(android-.*)
windowrulev2 = windowdance,class:^(android-.*) # allows IDE to move child windows
```

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/
