### ISSUE TITLE
When there are no workspaces in one monitor, weird stuff starting to happen

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprwm/Hyprland#934]
First, do this in config(or similar stuff)
```
wsbind=1,DP-3
wsbind=2,DP-3
wsbind=3,DP-3
wsbind=4,DP-3
wsbind=5,DP-3
wsbind=6,DP-3
wsbind=7,DP-3
wsbind=8,DP-3
wsbind=9,DP-3
wsbind=10,HDMI-A-1
```
I'll refer `DP-3` as `mon-1` and `HDMI-A-1` as `mon-2`
then use dispatcher `movecurrentworkspacetomonitor` to move workspace 10 from `mon-2` to `mon-1`
Launch a window in workspace 10(currently in `mon-1`
Now try to launch a window in `mon-2`, you can't

**Comment by vaxerski** [comment]
check with 6245c92bd0dbec65dbb1b2bd6d6277ba8f53fef9

**Comment by JustSimplyKyle** [comment]
Can confirm it's fixed!
Hyprland will always has a workspace in my second monitor no matter what
