### ISSUE TITLE
Cursor Size

### ISSUE THREAD

**Issue by RosGtHub** [hyprwm/Hyprland#935]
Can someone help me to fix the cursor size?
I tried to set also XCURSOR_SIZE to /etc/environment but didn't work.

https://user-images.githubusercontent.com/89165766/198881571-3a4fdce4-6bef-43b7-96dc-81cb6e8a7758.mp4

**Comment by vaxerski** [comment]
if you want to export a different cursor size than 24 do it in your wrapper. *Never* use /etc/environment

furthermore, xcursor_size is read only by qt, so make it match your gtk settings

**Comment by RosGtHub** [comment]
how?

**Comment by vaxerski** [comment]
how about reading the wiki? https://wiki.hyprland.org/Getting-Started/Quick-start/

**Comment by RosGtHub** [comment]
k k thanks.

**Comment by RosGtHub** [comment]
i tried to create the wrapper but can't launch it for some reason i'm not an expert.What can i do? 
![20221030_16h41m53s_grim](https://user-images.githubusercontent.com/89165766/198887748-f942548d-ee73-45ed-b224-dfa5fc6ffc5f.png)
![20221030_16h41m25s_grim](https://user-images.githubusercontent.com/89165766/198887749-81689a62-b29b-41d4-a864-ad5a96bacb52.png)

**Comment by vaxerski** [comment]
is ~/.local/bin in your PATH? is the wrapper executable? Basic linux knowledge.

**Comment by RosGtHub** [comment]
yes it is

**Comment by vaxerski** [comment]
if you are using a login manager, it doesn't run as your user. Use absolute paths and make sure the ~/.local/bin directory is readable by everyone.

**Comment by RosGtHub** [comment]
Fixed.Thanks you.
