### ISSUE TITLE
TTY Switching is broken

### ISSUE THREAD

**Issue by japrogramer** [hyprwm/Hyprland#94]
**Describe the bug**

if I have firefox open and I navigate to tty2 via "ctrl+alt+f2" and then return to Hyprland there are
a lot of drawing artifacts that get drawn and drawn away. This does not happen with weston.

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

**Comment by vaxerski** [comment]
yes switching ttys is broken. Just, don't, for now.

**Comment by japrogramer** [comment]
ok, good to know.

**Comment by dmadisetti** [comment]
Hyprland CPU usage doubles when doing this too. But I hear your warning.

**Comment by godalming123** [comment]
I use tty's a lot it would be useful to see this fixed

**Comment by vaxerski** [comment]
the problem is idk what the bug is.

**Comment by vaxerski** [comment]
mostly fixed in d743ac7bb1339a7407affb97792eb47fb0fe708c, only reported issue is that it doesn't work when you're running a separate Xorg session on another tty.

**Comment by vaxerski** [comment]
fixed in 6708f3b1334e8b6a966f424fe04713a4e74d5fdb
