### ISSUE TITLE
systemdIntegration in Nix module doesn't wait for dbus-update-activation-environment before starting hyprland-session.target

### ISSUE THREAD

**Issue by sunziping2016** [hyprwm/Hyprland#940]
Here was my previous nix home configuration.
```nix
{
  wayland.windowManager.hyprland = {
    enable = true;
    systemdIntegration = true;
    extraConfig = builtins.readFile ./hyprland.conf;
  };
}
```

Occasionally, I found commands triggered by `hyprland-session.target` such as `waybar` doesn't have the desired ` WAYLAND_DISPLAY`, `HYPRLAND_INSTANCE_SIGNATURE`, etc., environment variables. It seemed to be caused by the two detached commands below raced, and the later command was executed before the side effects of the first command.

https://github.com/hyprwm/Hyprland/blob/a69fd21a1ac90c24cee659595d62329f8638d632/nix/hm-module.nix#L105-L106

I fixed this by using the following home configuration.

```nix
{
  wayland.windowManager.hyprland = {
    enable = true;
    systemdIntegration = false;
    extraConfig = ''
      exec-once = export WAYLAND_DISPLAY DISPLAY && ${pkgs.dbus}/bin/dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && systemctl --user start hyprland-session.target
    '' + builtins.readFile ./hyprland.conf;
  };
  # following lines are copied from nix/hw-module.nix
  systemd.user.targets.hyprland-session = ...;
}
```

**Comment by fufexan** [comment]
Huh, I've never seen this behaviour. Do you maybe have an older machine/slower cpu?

**Comment by sunziping2016** [comment]
> Huh, I've never seen this behaviour. Do you maybe have an older machine/slower cpu?

My CPU is AMD Ryzen 9 4600H. The system is installed on a SSD. Nevertheless, I think this issue may be helpful for those unlucky guys like me.

**Comment by fufexan** [comment]
Alright, I'll make the change then.
