### ISSUE TITLE
Remove an unnecessary check for an API handle

### ISSUE THREAD

**Issue by elfring** [hyprwm/Hyprland#944]
[An extra check is not needed for a zero API handle](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml "Description from the OpenGL reference") in [the destructor for the class “CShader”](https://github.com/hyprwm/Hyprland/blob/dbd774fedb21fa55a23a741cc0ecaf1be556e6aa/src/render/Shader.cpp#L15 "Update candidate").

**Comment by vaxerski** [comment]
what?

**Comment by elfring** [comment]
How do you think about to integrate the following change? :thinking:

```diff
 CShader::~CShader() {
     // destroy shader
-    if (program) {
-        glDeleteProgram(program);
-    }
+    glDeleteProgram(program);
 }
```

**Comment by vaxerski** [comment]
but why, it doesnt make a difference anyways

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid a duplicate check at this source code place.
Would you like to take information from the sentence “A value of 0 for _program_ will be silently ignored.” (of the OpenGL® reference specification) better into account?

**Comment by vaxerski** [comment]
sure I can remove it but still it doesn't change anything and the performance impact is 0.

**Comment by elfring** [comment]
>sure I can remove it

This would be nice.


>but still it doesn't change anything

I prefer an other development view.


>and the performance impact is 0.

:thought_balloon: The differences on the software run time characteristics are measurable, aren't they?

**Comment by vaxerski** [comment]
> The differences on the software run time characteristics are measurable, aren't they?

this change's impact is unmeasurably small.

**Comment by elfring** [comment]
:thought_balloon: I agree that it can occasionally be hard to notice desirable effects despite of measurable differences.
