### ISSUE TITLE
Make window floating by dragging it with mouse

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#945]
As title says, it would be nice to have something like that. Instead of mod+mouse:272 only move window, also float that window when in a tiled mode.

**Comment by digitalwtf** [comment]
Good idea, I also believe when you want to drop the window in the tiling stack, you can hold the window over the place you want it, and the other windows move out of the way allowing you to put it there.

**Comment by romanstingler** [comment]
@vaxerski this can be closed as well, thx 4 cleanup
