### ISSUE TITLE
Make a keybind constant

### ISSUE THREAD

**Issue by jabuxas** [hyprwm/Hyprland#946]
I have set on my config `bind = $mainMod, h, resizeactive, -30 0` and `bind = $mainMod, l, resizeactive, 30 0`, which is the default on a lot of wm's.  The problem is that while it works, I have to manually click it like 10 times to get to the size I want, is it possible to add a way to make it constant, so while I hold it it will continue resizing? 

I couldn't find anything on the wiki like that.

**Comment by vaxerski** [comment]
> I couldn't find anything on the wiki like that.

consider learning to read then:

https://wiki.hyprland.org/Configuring/Binds/#bind-flags
