### ISSUE TITLE
windowrule "opacity" is not override

### ISSUE THREAD

**Issue by System-x64** [hyprwm/Hyprland#948]
https://user-images.githubusercontent.com/90208727/199522898-b9c3c0c4-642d-4b72-9891-97f5d10a107c.mp4

Ok..say i've set my alacritty windowrule to have some transparency...the first time I focus the app, the opacity is as specified however on opening another app and focusing back on the previous one the opacity for some reason gets below the specified amount...this only happens when an app has windowrule transparency not regular apps so could we maybe make it so that the windowrule opacity literally overrides the `active_opacity` setting and makes sure the window stays at the specified opacity? Basically I don't want its opacity to keep changing even after setting my `active_opacity` to `1`.

and i've read that _note_ at the bottom of the window rules tab...but still won't this approach make it just simpler to setup?

**Comment by vaxerski** [comment]
can you send me your config?

**Comment by System-x64** [comment]
Sure 

[hyprland.txt](https://github.com/hyprwm/Hyprland/files/9922015/hyprland.txt)

**Comment by Quantenzitrone** [comment]
I think have the same problem on NixOS.

I also have every opacity set to 1 but then defined a windowrulev2 for every window I want to make opaque. 

but for me, it kinda acts differently:
When I open any window that I defined opacity for, the initial opacity is lower than what I defined
after that it acts the same: focused less opaque, unfocused more opaque

**Comment by EvilBoi123** [comment]
still present on my hyprland-git

**Comment by zjeffer** [comment]
Same problem here: all windows have the set opacity, but the focused window has less opacity. I understand some people like to make unfocused windows more transparent, but here it's the other way around. Very strange behavior. 

In my case, I want focused and unfocused windows to have **the same** opacity. Is this not possible? @vaxerski

**Comment by zjeffer** [comment]
Sure, but that is for all windows, correct? I only want certain windows to have transparency.

**Comment by Quantenzitrone** [comment]
yup but you can define exceptions with windowrules

**Comment by vaxerski** [comment]
e8b99ae13a0525f9fbd6899fe39fe723879f86b9

```
windowrule = opacity 1.0 override,kitty
windowrule = opacity 1.0 override 0.5 override,kitty
```
