### ISSUE TITLE
Nix HM: `exec-once` in systemd integration does not run properly

### ISSUE THREAD

**Issue by PlayerNameHere** [hyprwm/Hyprland#949]
Seems to be caused by 0d71767. The backslashes are written to `hyprland.conf`, perhaps unintentionally? Hyprland's configuration file does not seem to have a way to escape characters, so the backslashes do not have any special meaning and are taken literally. Relevant part of the generated config:
```
exec-once=/nix/store/bijbd0r4qarawscxi26x9a3bvlri25cm-dbus-1.14.4/bin/dbus-update-activation-environment --systemd \
  DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP && \
  systemctl --user start hyprland-session.target
```

Relevant part of the logs show that only the first line is executed, while the lines after are seemingly ignored:
```
[LOG] Config executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:1 /nix/store/bijbd0r4qarawscxi26x9a3bvlri25cm-dbus-1.14.4/bin/dbus-update-activation-environment --systemd \
[LOG] Process created with pid 4036
```

The only possible fix I see is to generate only a single line for the `exec-once`, rather than splitting into multiple lines.

@fufexan

**Comment by fufexan** [comment]
Dammit. I was afraid this would happen. Thanks for pointing it out.

@vaxerski why no shell escaping?

**Comment by vaxerski** [comment]
hyprland doesn't support escaping with \
