### ISSUE TITLE
focusmonitor keybind does not emit focusedmon event in socket

### ISSUE THREAD

**Issue by Stupremee** [hyprwm/Hyprland#950]
If you move the mouse to another monitor, you get a `focusedmon` event in the socket. However, if you use the `focusmonitor` keybind, it won't emit an event. 

## Steps to reproduce

- bind `focusmonitor` to a hotkey
- use the hotkey to focus another monitor
- check socket, there won't be a focusedmon event

I'm using the nix flake build of hyprland at commit d0e47d9fe09dfa3be0c46833bee832ddbe0fcb51.

**Comment by vaxerski** [comment]
fixed in 653b9ed0e4933d83b2e3f378cdc76f1ebeb97e51
