### ISSUE TITLE
CSGO via steam (runtime) starts with blackscreen among other issues.

### ISSUE THREAD

**Issue by ghost** [hyprwm/Hyprland#952]
Reproduction:
1. Start the game iwith launch options: ` -refresh 144 -console -fullscreen -novid -nojoy -high -threads 6 -tickrate 128  +fps_max 0 -forcenovsync +cl_forcepreload 1`
3. Game appears as a window but very small (about 400x400px)
4. Notice there is only audio and no video output, only black
5. Notice when you open the steamoverlay with shift+tab and you close it, the overlay still is slightly visible with a variable 'ghost' in the background

I know the consensus is the use gamescope, but I would very much like to play CSGO directly with hyprland as it makes it much easier and a painless process, so if you could look into this issue for me that would be awesome.

I am currently running the Hyprland-git current releaes as of Thursday, November 3, 2022 available via the AUR on Arch Linux x86-64

Thank you :)

**Comment by vaxerski** [comment]
ran CS:GO with your launch options and everything works as expected. Yes, it starts as a window, but you can use the fullscreen dispatcher to fullscreen it. Everything renders as normal.

**Comment by digitalwtf** [comment]
> both are fine

Hmm i added the option `-vulkan` now I am able to play the game, however, there is no sound, anything on that?

**Comment by vaxerski** [comment]
sound is not handled by hyprland.

**Comment by digitalwtf** [comment]
> both are fine

Could it be that im running an nvidia gpu, I still cannot get it to run under opengl and I am not sure what to do.

**Comment by romanstingler** [comment]
@vaxerski should we close this issue, as this user has been deleted, and I can start CS:GO with AMD, intel iGPU and Nvidia card just fine.

**Comment by vaxerski** [comment]
ye
