### ISSUE TITLE
Option to drag window border to resize

### ISSUE THREAD

**Issue by schance995** [hyprwm/Hyprland#953]
This matches the behavior of other compositors (eg Sway) and it would improve accessibility (no need to use keyboard).

**Comment by digitalwtf** [comment]
Truth, one main purpose of other projects such as this one is keyboard accessibility.

+1

**Comment by Alex45463** [comment]
Do u mean this?
`bindm = $mainMod, mouse:273, resizewindow`
with this setting u can resize holding your RIGHT button mouse, but you can change it to everything else (this should be by default).
The LEFT mouse button by default is use to move windows around so pay attention to don't bind keys you already used to.
So the first idea that comes to my mind would be for using your still your RIGHT mouse button, would be while holding SHIFT:
`bindm = $mainMod SHIFT, mouse:272, resizewindow`

Hope it helps

**Comment by vaxerski** [comment]
there are 2 types of people here:

- Why is this feature mouse-only? I wanna use only the keyboard

- Why is this feature keyboard-only? I wanna use my mouse

**Comment by MightyPlaza** [comment]
@vaxerski `resize_on_border` probably closes this

**Comment by vaxerski** [comment]
do be do be doo ba
