### ISSUE TITLE
Title bars?

### ISSUE THREAD

**Issue by schance995** [hyprwm/Hyprland#954]
Right now I use Waybar with the window title module, but that is not as flexible as title bars. Far from being [useless eye candy](https://github.com/hyprwm/Hypr/issues/49), titlebars let the user manage windows with only the mouse, which is important for accessibility. It's a lot to ask for but no rush:

- show window title
- show window status: right now there's no visual indicator for fullscreen 1 windows, and the tabbed/grouped indicator border is narrow and hard to see. It seems natural to make the indicator borders bigger to make them title bars, since they're already rendered above the window border.
- left click/scroll to switch tabbed window 
- left click/drag title bar to move window
- bind mouse buttons (eg right click title bar to toggle floating, middle click to close)
- toggle title bars per window/globally

**Comment by JustSimplyKyle** [comment]
I think everything you said can be done with extensive `eww` configs + `hyprctl` scripting 
I personally is agaiest adding bars to hyprland since it probably should belong in a separate project(`hyprbar`)

**Comment by vaxerski** [comment]
this is not KDE and we are not focused on accesibility, but rather productiveness. 

They are very much useless eye candy. All they do is give you another way to do what you could've already done with binds.

I am not saying they will never land, but I doubt for the forseeable future. There is not enough people wanting them (1 is not enough) and they're virtually useless.

**Comment by FaceHiddenInsideTheDark** [comment]
Please, never consider title bars. IMHO, it is the worst thing about other DEs/WMs. I always have to spend a lot of free time trying to get rid of those for everything else.

**Comment by amilonop** [comment]
Title bars are useless. 

Love the differentiation between user centric and user friendly :D

**Comment by n0nvme** [comment]
Title bars are really useful when you have a touchscreen device like Lenovo Yoga

**Comment by vaxerski** [comment]
Noise, noise noise.

Titlebars will eventually make it to hyprland, in the form of disabled by default, enabled if someone wants it. Not soon though, this is really low on a priority list for a *tiling* compositor.

**Comment by mustardfrog** [comment]
Title bars will be definitely attractive for former i3 users. Title bars should be available for tabbed/stacked modes and floating windows. And of course, these should be optional.

**Comment by cmiles74** [comment]
> I think some things you said can be done with extensive `eww` configs + `hyprctl` scripting I personally is agaiest adding bars to hyprland since it probably should belong in a separate project(`hyprbar`)
> 
> Although I support some basic function of a title bar(such as title for groups) could be ahded

I use tab groups on my secondary monitor and it would be nice to have an easier way to see what windows are in the tab group.

**Comment by vaxerski** [comment]
Now that we have a plugin system, I am probably going to implement title bars as a plugin.

**Comment by vaxerski** [comment]
Added very simple title bars in the [hyprland-plugins](https://github.com/hyprwm/hyprland-plugins) repo.

They will be improved a bit, don't worry. Any further requests though please report to the issue tracker there.

**Comment by pshirshov** [comment]
Oh, they aren't useless for screen reader users.

**Comment by renatolfc** [comment]
(I know this issue is closed, but my two cents:)

I'm currently considering migrating from i3/sway to hyprland and one particularly useful feature i3 and sway have is the ability to stack windows.

When windows are stacked, the title bars let you know what other windows are there, as well as what's the currently focused one.

This can be seen, for example, on the right side of the image below:

[![Stacked Windows on i3](https://goral.net.pl/post/i3a/i3-stack.png)](https://goral.net.pl/post/i3a/)

I usually do this type of stacking to have a main window where I work, and other stacked windows I take a look for reference.

So, if Hyprland supports stacked windows (which it doesn't seem to, but I haven't checked thoroughly yet), that'd be really helpful and not useless at all.

**Comment by fufexan** [comment]
Hyprland supports groups, which are rendered like this.
![image](https://github.com/hyprwm/Hyprland/assets/36706276/b0c4da9d-b1a4-4f80-b95b-4ac1ca620944)

If you want more of the i3/sway functionality, take a look at the [hy3 plugin](https://github.com/outfoxxed/hy3/).

**Comment by renatolfc** [comment]
Sweet! That seems to be what I’m looking for.

thanks, @fufexan!
