### ISSUE TITLE
How to set no border when there is only one window？

### ISSUE THREAD

**Issue by Ruixi-rebirth** [hyprwm/Hyprland#955]

**Comment by vars1ty** [comment]
This doesn't exist by default, if the wiki doesn't mention it then it isn't there.
You'll have to script it yourself.

**Comment by Ruixi-rebirth** [comment]
Okay, I get it.

**Comment by fufexan** [comment]
`dwindle:no_gaps_when_only` should do that @Ruixi-rebirth.

**Comment by vlfldr** [comment]
Is there a way to accomplish the inverse - i.e. automatic large gaps when there is only one window, normal gaps when a second window is spawned?

**Comment by vaxerski** [comment]
script it
