### ISSUE TITLE
Rofi ignores the windowrule=float

### ISSUE THREAD

**Issue by ailen-cmd** [hyprwm/Hyprland#957]
Other windows open in floating mode, but not rofi.

==Steps to reproduce: I wrote "windowrule=float,^(rofi)$" in the config file
==Expected outcome: Rofi will open in floating mode
==Noted outcome: Rofi still opens in tiling mode

Gif: https://media.giphy.com/media/fi2Vae9SrTX0xsbcqf/giphy-downsized-large.gif

**Comment by vaxerski** [comment]
then the class is simply wrong or another "tile" rule overwrites this?

besides, rofi is made for xorg. Use either the wayland fork or something like wofi.
