### ISSUE TITLE
when you try to close a tabbed app, the tab freezes and you cant do anything with it

### ISSUE THREAD

**Issue by Rishabh672003** [hyprwm/Hyprland#958]
here you can see it happening in the video - https://i.imgur.com/e8EAhMs.mp4
in the end of the video i tried closing the tabbed alacritty window and it just freezes

**Comment by dmichalskii** [comment]
After this freezes you see in htop that process alacritty is done?

**Comment by vaxerski** [comment]
fixed in 22384869a63e5c9c46f2cfbd0c914ceb01ca9a2e

**Comment by Rishabh672003** [comment]
thanks
