### ISSUE TITLE
Keybind to switch between last two workspaces

### ISSUE THREAD

**Issue by experiacc** [hyprwm/Hyprland#959]
It would be great to have a keybind to quickly switch between last opened workspace and current workspace. It would be easy to implement also or maybe there's already some way to do this that I'm not aware of?

**Comment by vaxerski** [comment]
rtfw
![image](https://user-images.githubusercontent.com/43317083/200133723-13cc782e-8d49-4925-aa58-22df1ea7bb70.png)

**Comment by experiacc** [comment]
thanks but i already tried that.
I've set this bind
```
bind = SUPER, Tab, workspace, previous
```
If I keep pressing the bind, it changes some workspaces and finally gets stuck on a single workspace but I want it to keep toggling between 2 workspaces (that is: current <-> last opened workspace)

**Comment by vaxerski** [comment]
rtfw
![image](https://user-images.githubusercontent.com/43317083/200139022-797399f0-bd72-4245-8d1d-094c404771b2.png)
