### ISSUE TITLE
fullscreening apps make them  go behind the waybar

### ISSUE THREAD

**Issue by Rishabh672003** [hyprwm/Hyprland#960]
when you full screen apps using `bind=SUPER,F,fullscreen,1` the apps go behind the waybar 
like you can see here - 
![image](https://user-images.githubusercontent.com/53911515/200135049-afd6a70f-cca9-4acc-b63b-0b8364043c07.png)
you can see the firefox tabs are behind the waybar
this is with waybar-hyprland-git from aur

**Comment by vaxerski** [comment]
fixed in 6553fb5a40f5f10f10c2b6aebd143044af40ab59

**Comment by Rishabh672003** [comment]
thanks
