### ISSUE TITLE
configuration of mouse pressence

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [hyprwm/Hyprland#962]
it would be nice to be able to explicitly manipulate if the cursor is hidden or not would be nice

**Comment by MahouShoujoMivutilde** [comment]
IDK about explicit manipulation, but unclutter is already here:

```
general {
    cursor_inactive_timeout = 5
    # hide after 5 seconds of not moving
}
```

**Comment by SomeGuyNamedMy** [comment]
thanks for pointing that out, i must have missed that in the docs, i went ahead and corrected my comment

**Comment by vaxerski** [comment]
manually as in with hyprctl?

**Comment by SomeGuyNamedMy** [comment]
ideally configuring pressence through dispatchers, ie hidecursor, showcursor, perhapsit could also take a param that determines what workspaces it hides and shows the cursor on. sorry for not explaining it better initially lol

**Comment by SomeGuyNamedMy** [comment]
closing. this was a dumb issue on my part tbh, ive come to the conclusion this can all be done with ipc.

**Comment by SomeGuyNamedMy** [comment]
This was a dumb issue on my part tbh, all of this can be done via ipc. my bad
