### ISSUE TITLE
Emulating some ion3 behaviour

### ISSUE THREAD

**Issue by bwachter** [hyprwm/Hyprland#964]
I'm currently still an [ion3](https://tuomov.iki.fi/software/ion/) user, and regularly check if there are some new developments allowing me to switch to wayland - hyprland was the first one that looks like I'm fine with it on my notebook (the scratchpad helped a lot with that..), though there are a few issues there still, and I don't see yet how I can use it on my multi display workstation. 

This is a collection of those things - some of which may already be possible via scripting, and I just don't see how, while for others the answer might be "write a new layout manager". I can split off individual items to separate issues if they're deemed sensible on their own.

1. tagging and attaching a window
Ion3 allows me to tag a window, go somewhere else, and then attach whichever window is tagged. Attaching makes it lose its tag. This _might_ be scriptable already, but I don't quite see how.

2. float splits
Ion3 allows 'float splits', both horizontal and vertical. For those splits the active frame overlaps the inactive frame(s) fully or partially, depending on the active frames size. This is very useful on devices with a small screen - I can work in a frame covering most of the screen while keeping just enough of another frame visible to see if something interesting has happened, without resizing it.

4. static splits
On my workstation I typically have a static 3x3 split one one screen, a more complex layout on a second, and the others keep changing (i.e., would work fine with hyprlands dynamic splits). I currently don't see how I could do that, and "needs a static layouter" might be the answer here.

5. titles in tab groups
There's #954 open about titles - which I also think are usually stupid. The one exception is tab containers - there it sometimes is useful to have an overview of what is inside of the container.

6. query module
Ion has a built in query module which allows ssh/app launcher/editing files/... - I've replaced most of that by wofi scripts now. The one bit where things are lacking currently is window manager control - ion3 is fully controllable via embedded lua, so I can just open a query and interact with the WM.
Most (if not all) of this might be solvable with launcher+external scripting, though it looks to be a bit clumbsy in some times - this might benefit from either having an internal query for this, or having hyprctl to be a bit more friendly for building completion output for launchers.

7. tab groups splitting
This is the main annoyance I currently have on my notebook - I often end up in a situation with a group at full screen height, and two frames at half height each next to it. Then I would like to have the group only fill half the screen, and another frame either above or below. Currently it seems I have to ungroup, open frame, regroup

8. ability to cancel operation from a submap
In ion3 I can enter resize/move modes with a submap, with similar behaviour as in hyprland. The big difference is that I have the option of pressing Enter to accept the resize operation, or Esc to leave, reverting the resize.

**Comment by vaxerski** [comment]
1. what does attach mean

2. what

3. what??

4. #520 

5. hyprctl is very friendly. Even has -j for combining with something like e.g. gojq

6. yes, I am planning on doing something with that

7. no. Also, scriptable.

**Comment by bwachter** [comment]
1. attach means pretty much "move window` to the active frame". ion3 has mainly 2 methods for that: via query in the active frame  based on the window name (I guess that's already scriptable), and via the tag/attach tagged workflow. I mostly use the tag/attach thing
2. http://matthieu-moy.fr/ion/ion3/ has two screenshots ("floating split"), if it's still unclear I can try to make a short video
3. pretty much just the option to have a static layout on some workspaces, which will never change until I actively change it. ion3 is pretty much only static - the dynamic behaviour of hyprland makes a few things easier, especially on the notebook, but I don't see that working for all my screens on my workstation
7. any pointers how to script that? I couldn't imagine how to do that from the documentation

**Comment by vaxerski** [comment]
script:
save dims on submap enter event

bind escape to revert and exit submap
bind enter to just exit submap

1. still no clue what you mean
2. no.
3. hyprland is dynamic by definition and I am not planning on adding any static layouts.

**Comment by bwachter** [comment]
Maybe this script makes it a bit clearer. I didn't find anything suitable to do the windows move:

    #!/bin/bash
    # bind = $mainMod, t, exec, hyprwindow tag
    # bind = $mainMod, a, exec, hyprwindow attach
     
    if [ "$1" == "tag" ]; then
        address=`hyprctl -j activewindow|jq -r .address`
        echo -n "address=$address" > ~/.cache/hyprland_tag
    elif [ "$1" == "attach" ]; then
        if [ -f ~/.cache/hyprland_tag ]; then
            . ~/.cache/hyprland_tag
            # sample operation with something taking the window address
            # this actually should do a "move the window to where the cursor is,
            # and then either split or add it to the focused group"
            hyprctl dispatch focuswindow address:$address
            rm -f ~/.cache/hyprland_tag
        fi
    fi

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/200196503-e089d647-3eff-4bce-9c61-b2b780971a73.png)

damn man get some glasses

https://wiki.hyprland.org/Configuring/Dispatchers/

for cursor:
![image](https://user-images.githubusercontent.com/43317083/200196527-d5fab5b9-9edc-4f5e-8a97-9f934351ba03.png)

https://wiki.hyprland.org/Configuring/Using-hyprctl/

**Comment by bwachter** [comment]
It isn't obvious to somebody not too familiar with this thing that I need to go through cursor coordinates instead of basing it on an active window. Also dwindle currently doesn't seem to be able to handle this:

    [LOG] Dwindle cannot move a tiled window in moveActiveWindow!
    [LOG] Hyprctl: dispatcher movewindowpixel : exact 1324 2557,address:0x56650930

Best case I just get this log message and nothing happens, worst case about 30 seconds after that a split in the region where I was trying to attach it vanishes, losing one of the clients. I couldn't get useful logs or properly reproduce what triggers the latter behaviour so far.

```
#!/bin/bash
# bind = $mainMod, t, exec, hyprwindow tag
# bind = $mainMod, a, exec, hyprwindow attach

if [ "$1" == "tag" ]; then
    address=`hyprctl -j activewindow|jq -r .address`
    echo -n "address=$address" > ~/.cache/hyprland_tag
elif [ "$1" == "attach" ]; then
    if [ -f ~/.cache/hyprland_tag ]; then
        . ~/.cache/hyprland_tag
        cursor="`hyprctl cursorpos | sed 's/,//'`"
        hyprctl dispatch movewindowpixel exact $cursor,address:$address
        #hyprctl dispatch focuswindow address:$address
        rm -f ~/.cache/hyprland_tag
    fi
fi
```

**Comment by vaxerski** [comment]
oh if you want nodes in floating mode that you can move around and stuff, while them being "tiled", no, that's not gonna happen.

**Comment by bwachter** [comment]
I don't use anything floating outside of short lived dialogs created that way.

    bindm = $mainMod, mouse:272, movewindow

This allows me to move that window somewhere else by mode+mouse, doing splits or adding it to a layout - whatever makes sense at the point where I release the mouse button.

So I'm trying to get pretty much the same thing, without touching the mouse, by getting the window ID, and then hoping it to do something sensible with it at the cursor location - just as with the drop there by mouse.

**Comment by vaxerski** [comment]
ah, like move left right up or down but not swap like it currently does? yeah I have that planned, no way to do so atm

**Comment by vaxerski** [comment]
I think all of this is fixed
