### ISSUE TITLE
odd transition between two fullscreen windows within a workspace 

### ISSUE THREAD

**Issue by 257** [hyprwm/Hyprland#966]
Steps to reproduce:
- fire up a terminal (kitty/alacritty)
- fire up a browser (qutebrowser/chrome)
- given `bind=ALT,f,fullscreen` `ALT-f` to make everything fullscreen
- now `movefocus,{l,r,u,d}` and watch the transition between windows

driver notes: this is less obvious (happens quicker?) on Intel graphics compared to Nvidia

**Comment by vaxerski** [comment]
how is it odd

**Comment by 257** [comment]
> how is it odd


https://user-images.githubusercontent.com/1268392/200398383-426480dd-0211-4c6d-8278-000d566a16cf.mp4

**Comment by vaxerski** [comment]
completely normal and how it's expected to be. dupe of #683
