### ISSUE TITLE
RX 6600 Xwayland not  working

### ISSUE THREAD

**Issue by IceDBorn** [hyprwm/Hyprland#975]
I was previously using Hyprland with a RTX 2060, everything was working like a charm. I recently switched to a RX 6600 and Xwayland does not work using Hyprland. 

Programs complain that the X server is missing.

![image](https://user-images.githubusercontent.com/51162078/200606708-96a3f07e-5366-460f-9d2a-8479b7cecd9f.png)
![image](https://user-images.githubusercontent.com/51162078/200606818-572234ed-fd33-4de1-99f5-f47e48a0fe8d.png)

the contents of `/tmp/.X11-unix/` are
![image](https://user-images.githubusercontent.com/51162078/200607019-3ea99ea9-4c0d-42ac-a60e-e4d2ba904ba0.png)

Running `Xwayland -rootless` works, and programs launch but their windows do not spawn. Running `Xwayland` though works, the command spawns an Xwayland window and any X app I launch spawns in that window.

![image](https://user-images.githubusercontent.com/51162078/200607679-eaa0cfc1-4f18-4634-95e2-57f9b5a097dd.png)

[Here are my hyprland session logs](https://pastebin.com/rgFX66Gf)

**Comment by vaxerski** [comment]
dunno looks like a your compoota problem. Maybe you forgot to purge some nvidia drivers? X settings for nvidia? That'd be my guess. You need a fair bit of settings for nvidia for X, and that might interfere with AMD.

**Comment by vaxerski** [comment]
I mean the settings in `/etc/X11`

**Comment by IceDBorn** [comment]
@vaxerski 
![image](https://user-images.githubusercontent.com/51162078/200612070-74fc0046-6437-48f2-8e5d-d52c5d0b5767.png)

**Comment by vaxerski** [comment]
sir I am not xorg tech support. No need to send me these. I have no clue. All I know is that for xorg on nvidia the driver sets some values, and you might want to **investigate yourself** what's there.

It's clearly an issue on your side and not Hyprland's.

**Comment by vaxerski** [comment]
Yes. GNOME and Hyprland run on completely different grounds, so if anything, this seems like a wlroots problem. 

You can search for wlroots errors by examining the log when Hyprland is ran with the `HYPRLAND_LOG_WLR=1` env var.

**Comment by tdljayden** [comment]
I'm using an RX 6600 as well and it would appear most things work fine. I'll reproduce the error when I get the chance.

**Comment by IceDBorn** [comment]
@tdljayden I'm on NixOS, I installed Arch and the issue is not present.

**Comment by IceDBorn** [comment]
I was not using the unstable packages of NixOS
