### ISSUE TITLE
Apps like JOSM and SDRtrunk open with blank white screen

### ISSUE THREAD

**Issue by owenh28** [hyprwm/Hyprland#977]
Both of these apps are java based, and I would assume use the same toolkit? The image below shows what happens on launch, and switching from floating to tiled doesn't change anything. 

JOSM can be found [here](https://josm.openstreetmap.de), 
and SDRtrunk can be found [here](https://github.com/DSheirer/sdrtrunk). 

![image](https://user-images.githubusercontent.com/43768471/200644229-59affd80-f503-4f1f-8559-48e88e75980e.png)

**Comment by owenh28** [comment]
Also, here is the ```hyprctl clients``` output for that window:
```
Window 2a06b0d0 -> Java OpenStreetMap Editor:
	at: 419,306
	size: 990,710
	workspace: 3 (3)
	floating: 1
	monitor: 0
	class: org-openstreetmap-josm-gui-MainApplication
	title: Java OpenStreetMap Editor
	pid: 32143
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0

```

**Comment by vaxerski** [comment]
did you export `_JAVA_AWT_WM_NONREPARENTING=1` as the wiki prompts you to do?

**Comment by owenh28** [comment]
After changing how I wrapped the launch of hyprland, I seemed to have fixed my problem. ```_JAVA_AWT_WM_NONREPARENTING=1``` was not exporting correctly.

Closing

**Comment by vaxerski** [comment]
L
