### ISSUE TITLE
Disabling animations on specific layers

### ISSUE THREAD

**Issue by Gustash** [hyprwm/Hyprland#978]
## Issue

I've been trying to disable animations for rofi, specifically. I'm using `rofi-lbonn-wayland-git`, which renders rofi in Layer 3:

```
$ hyprctl layers
Monitor DP-1:
	Layer level 0:
		Layer 3184fd10: xywh: 1920 0 1920 1080, namespace: hyprpaper
	Layer level 1:
	Layer level 2:
		Layer 31816a70: xywh: 1920 0 1920 35, namespace: waybar
	Layer level 3:


Monitor DP-2:
	Layer level 0:
		Layer 31846b80: xywh: 0 0 1920 1080, namespace: hyprpaper
	Layer level 1:
	Layer level 2:
		Layer 31f24a50: xywh: 0 0 1920 35, namespace: waybar
	Layer level 3:
		Layer 31fb9c70: xywh: 480 320 960 474, namespace: rofi

```

I've tried setting a window rule with noanim, but that obviously didn't work since rofi isn't a window in this case, but a layer.

Is there currently a way to disable animations for specific layers? If not, would it be feasible to port some of the `windowrule`s to a `layerrule` config option?

## Steps to reproduce

1. Install `rofi-lbonn-wayland-git`
2. Try using `windowrulev2 = noanim, class:^(rofi)$` to disable all animations for rofi
3. Open rofi

## Expected outcome

The ability to disable animations, in this instance, for specific layers

## Noted outcome

Animations still play. No apparent way to disable them in the config, except disabling all animations in general.

**Comment by vaxerski** [comment]
On my radar.

**Comment by vaxerski** [comment]
done with 8ae1fd01730ebd8382d850d1d5526fee0fb076f1

see layer rules https://wiki.hyprland.org/Configuring/Window-Rules/#layer-rules
