### ISSUE TITLE
weird behavior when swipping between workspaces

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#979]
This happens seemingly randomly on random workspaces. Some windows seem to be "late" in the swipe animatiion then make up for it by zooming in. A video will probably describe this better

https://user-images.githubusercontent.com/208711/200702326-914aebe5-5621-495e-8570-f254c876478b.mp4

**Comment by vaxerski** [comment]
ay what in the fuck

how do I reproduce, this doesnt happen to me

**Comment by primalmotion** [comment]
I don't know it happens completely randomly. I also noticed the shadow are in position. Here's a screenshot during the middle of a swipe

![screenshot-2022-11-08-18:11:14](https://user-images.githubusercontent.com/208711/200720063-27715134-0ce5-4d53-920e-9295c474fa00.png)

**Comment by primalmotion** [comment]
It does not happen on 1a55fb417093fb945942dba63d0edb9467d782ef I;ll try to bisect it more tomorow if the cause is not obvious to you

**Comment by Rik034** [comment]
Something similar happens to me too but only on my second monitor: the border animation happens faster or earlier than the window animation.

https://user-images.githubusercontent.com/60218806/200721767-1c71153a-f801-446e-906b-30fbf8d7de5f.mp4

**Comment by primalmotion** [comment]
starting to bisect

**Comment by primalmotion** [comment]
2a20cf5379161adc16424652313371c558b1467e is the first bad commit
commit 2a20cf5379161adc16424652313371c558b1467e
Author: vaxerski <43317083+vaxerski@users.noreply.github.com>
Date:   Mon Nov 7 21:23:19 2022 +0000

    Added decoration:shadow_scale

 src/config/ConfigManager.cpp                       |  1 +
 .../decorations/CHyprDropShadowDecoration.cpp      | 38 +++++++++++++++++-----
 2 files changed, 31 insertions(+), 8 deletions(-)

**Comment by vaxerski** [comment]
stupid ass developer introducing retarded bugs

at any rate wtf?? Exactly on that commit and no issues.

**Comment by vaxerski** [comment]
share your configs gentlemen

**Comment by Rik034** [comment]
not at home rn, i'll be sure to do it once i get back

**Comment by primalmotion** [comment]
```
monitor=eDP-1,preferred,10000x10000,1
monitor=desc:Dell Inc. DELL U2720Q 12PZP83,preferred,11920x9180,1.3
monitor=desc:Dell Inc. DELL U3419W GF2W5T2,preferred,9230x8560,1
exec = lid.sh

input {
	kb_layout =
	kb_variant =
	kb_model =
	kb_options = compose:caps
	kb_rules =
	follow_mouse = 1
	touchpad {
		natural_scroll = 1
		disable_while_typing = 1
		drag_lock = true
	}
}

general {
	sensitivity = 1.0
	main_mod = SUPER
	layout = master
	gaps_in = 6
	gaps_out = 12
	border_size= 3
	no_border_on_floating = 1
	source = ~/.config/hypr/color.conf
}

master {
	new_is_master = false
	no_gaps_when_only = true
}

dwindle {
	preserve_split = true
	no_gaps_when_only = true
	force_split = 2
}

gestures {
	workspace_swipe = true
	workspace_swipe_invert = true
	workspace_swipe_fingers = 4
	workspace_swipe_distance = 1300
	workspace_swipe_cancel_ratio = 0.5
	workspace_swipe_min_speed_to_force = 20
	workspace_swipe_create_new = false
}

misc {
	 disable_hyprland_logo = true
	 no_vfr = false
	 animate_manual_resizes = true
	 enable_swallow = true
	 swallow_regex = ^(Alacritty)$
}

decoration {
	rounding = 4
	blur = true
	blur_size = 3
	blur_passes = 3
	blur_new_optimizations = true
	drop_shadow = true
	shadow_range = 32
	shadow_render_power = 18
	col.shadow = rgba(00000044)
}

animations {
	enabled = 1
	animation = windows,1,3,default,slide
	animation = border,1,2,default
	animation = fade,1,2,default
	animation = workspaces,1,3,default
	animation = specialWorkspace,1,5,default,fade
}

...
```

**Comment by primalmotion** [comment]
I think the key thing is to have another monitor, as it seems a common variable to all people reporting this issue

**Comment by vaxerski** [comment]
scheisse, you're right. On the 0,0 monitor it's fine. On the other, not so much. Let me fix that.

Are both issues coming from the same commit?

**Comment by primalmotion** [comment]
yeah. the initial issue is basically because FF is set to have no border, which only gives the impression of the window being later. I think it's the same issue

**Comment by vaxerski** [comment]
nononono it is late

**Comment by vaxerski** [comment]
fixed in f41fe59cb67e31c495008227d42060eebafe4c9e

![image](https://user-images.githubusercontent.com/43317083/200957549-7e890c75-7c9b-4e02-aa37-bfec7e674015.png)

**Comment by primalmotion** [comment]
let me check that :)

**Comment by primalmotion** [comment]
fixed indeed! Thanks!

**Comment by Rik034** [comment]
Usually, I don't like building things from GitHub (I forget to update them) but hyprland-git in the AUR is still behind. Thanks a lot

**Comment by vaxerski** [comment]
-git is ***never*** behind. You need to cleanbuild -git packages to update! (paru users need to remove the appropriate cache entry, while based gigachad yay users can just type A)

**Comment by Rik034** [comment]
Oh my bad, thanks. Sorry I'm not based
