### ISSUE TITLE
movewindow leaves artifacts of the moved window ontop of other windows

### ISSUE THREAD

**Issue by japrogramer** [hyprwm/Hyprland#98]
**Describe the bug**
when movewindow is triggered and the moved window moves over other windows artifacts of the moved window remain drawn over the windows that weren't moved

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)

** possible solution **

force a redraw on all windows after the animation ends

**Comment by vaxerski** [comment]
cant reproduce

**Comment by japrogramer** [comment]
I was able to replicate but this time the artifacts are around the edges near the bottom of the screen, where the wallpaper show

https://user-images.githubusercontent.com/1387859/169592454-6aa68c4f-a27d-4add-a488-708af90e0794.mp4

s

**Comment by vaxerski** [comment]
ah, its firefox again. right. It's that issue.

**Comment by japrogramer** [comment]
@vaxerski when I have terminal windows with an opacity of .75 and I replicate the movement shown in the video the artifacts now happen on the transparent window and not just at the bottom part of the screen

https://user-images.githubusercontent.com/1387859/169679487-515f8a5f-ae9a-4dd9-97a6-23cfc17607a6.mp4

**Comment by vaxerski** [comment]
well, yeah. It's an issur with firefox, as I've said.

**Comment by siemato** [comment]
i have the same issue with alacritty, foot and pretty much everything i tried when closing the last window of a workspace,

**Comment by vaxerski** [comment]
video please?

**Comment by japrogramer** [comment]
I'm also using alacritty, may be the same issue.

**Comment by vaxerski** [comment]
should be fixed in f461ea3105fbe7979a44d702bd9b2f7ee46a9441
