### ISSUE TITLE
Specific animations on layers

### ISSUE THREAD

**Issue by Icelk** [hyprwm/Hyprland#981]
Great project!

I've scoured the docs searching for ways to customize the animations and properties of layers.

Are there plans on allowing customization of individual layers' animations (fade duration, window resize animations) & possibly window rules?
I saw that you mentioned this in #875, but then closed the issue. So I opened another one for specifically this feature.

Thanks!

**Comment by vaxerski** [comment]
planned

**Comment by ronasimi** [comment]
any progress on this.  Since waybar can't be hidden in Hyprland, I'd love to be able to set a vertical slide on open/close.

**Comment by vaxerski** [comment]
it's moved from planned to planned

**Comment by vaxerski** [comment]
cooked

**Comment by Icelk** [comment]
Thanks a lot! Your work is really appreciated.

**Comment by mooncoffee1** [comment]
fr, man, ur a god, thanks, but how we configure the animation speed, etc ?

**Comment by Icelk** [comment]
@mooncoffee1 
You can modify it using the animation setting:
`animation = layers, 1, 4, default, fade`
Then you can change the animation style using layerrule:
`layerrule = animation slide, notifications`

Its all explained in the wiki
