### ISSUE TITLE
[Feature Request] Options for window group indicator and asymetrical gaps

### ISSUE THREAD

**Issue by BionicKnight** [hyprwm/Hyprland#989]
I have a lowres monitor so this propels me to use very small gaps, this made me didn't notice a very useful feature, the grouped window tab indicator.

So it maybe very useful to have alternative options for it, like configure it's distance from the window, thickness, position etc. and maybe a option for having integrated in the border, like if there are two windows grouped, only half of the border use the active accent color, with three, only a third but this may be an over complication for the code base.

And another thing that would pair well would be ability to set out gaps with different spacing per side, eg. have out gaps only above

I'm probably one of the few with below FullHD monitor, but it can affect any person who uses very small gaps

Didn't saw anybody suggesting this, but if it's a duplicate please just close, sorry to bother and good work.

**Comment by vaxerski** [comment]
outer gaps can be adjusted per-side by manipulating the reserved area.
