### ISSUE TITLE
Apex Legends only left part of the window clickable

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#993]
I run Apex Legends through Proton. I noticed that only 3/4 of the left part of the window area is clickable, but not the right part. 

So, when I move the mouse across 1/4 of the right part it triggers actually elements from the left-part.

Strangely, when I move the window to the left (and outside the screen area), the right part becomes clickable again.

**Comment by Gustash** [comment]
Have you seen [this](http://wiki.hyprland.org/FAQ/#my-games-work-poorly-especially-proton-ones)?

**Comment by ad-on-is** [comment]
Using gamescope fixes it

**Comment by vaxerski** [comment]
oddity
