### ISSUE TITLE
Minimize windows

### ISSUE THREAD

**Issue by ad-on-is** [hyprwm/Hyprland#995]
Is there such an option as minimizing windows, or am I blind to find it in the docs?

**Comment by vaxerski** [comment]
no this is not kde

**Comment by Gustash** [comment]
The closest thing would be [this](https://wiki.hyprland.org/Configuring/Dispatchers/#special-workspace). You can basically have a keybinding to move the active window to the special workspace, then another keybinding for toggling said workspace.

That said, if you want proper window minimizing, you should probably be using a floating window manager instead of a tiling window manager. Completely different paradigms

**Comment by ad-on-is** [comment]
I'm on awesomewm right now, which is a tiling WM and minimizing is a thing there.

Also, there's an action for wlr/taskbar in waybar called minimize, so I thought minimizing is a thing in wlroots too.

Sometimes I have windows open, which I don't need right now, so i minimize them, and bring them back later on

**Comment by EysseW** [comment]
I'd recommend using the special workspace for that. It achieves the same goals in the end. That being said, I'd also like so see this, as it would enable people to using hyprland as a floating WM as well, just like you can in awesomewm. There is a reason awesome is so damn popular.

**Comment by EysseW** [comment]
@vaxerski is revision on this possible? The compositor is way more advanced nowadays, I think it's time to get to these things. Minimizing would be the only thing that's really needed to be able to use hyprland as a stacking window manager. It might not be your intention of the project, but such a simple and small feature could mean a lot for a lot of people. I can't think of much that wouldn't be possible in your compositor at that point.

**Comment by vaxerski** [comment]
why not make a special workspace called `minimized` and use that as a minimized container?

**Comment by EysseW** [comment]
Because waybar's minimize option of the taskbar doesn't support it,does it? It's also not just waybar, it's also other apps having a "minimize" function, like every libadwaita app. I might be wrong about the technical details, though. I don't have the technical knowledge..

**Comment by EysseW** [comment]
I don't know what is meant by half of the things you just said, but if it will enable us to use the minimize function of waybar and other apps - by scripting or without, I am all for it.

**Comment by EysseW** [comment]
just looked it up. I understand the message now xD. It think that be nice. I don't think people need it that much for wine programs and games.

**Comment by vaxerski** [comment]
done in 5d35c0432b70e2d5e82296caf7f496dc4612f3e5

**Comment by EysseW** [comment]
I went and testing it right away, but it freezes and crashes. Making a bug report.

**Comment by EysseW** [comment]
I am however, grateful you added the option. Thanks!

**Comment by EysseW** [comment]
That's also scriptable

**Comment by imxyy1soope1** [comment]
> I tried the special workspace, works fine 😄 .
> 
> However, I think it would be better if **every workspace has a dedicated special workspace**, which would be more like what I understand as "minimize".

You can use named special workspaces.
See [Workspaces](https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces).

**Comment by ildar** [comment]
Adopted the idea of special workspaces and love it. My example bindings:
```
bind = $mainMod, E, movetoworkspace, special:minimized
bind = $mainMod, W, movetoworkspace, +0
bind = $mainMod, W, togglespecialworkspace, minimized
```
So that I push `$mainMod, W`, choose the window to restore and push `$mainMod, W` again. Voila!
thanks!

**Comment by DreamMaoMao** [comment]
> Why don't you write a plugin?

plugin cannot do everythin .

**Comment by valerii15298** [comment]
I just wanna have a shortcut to hide all windows so that I can see that beautiful girl on wallpaper. Seriously, sometimes I wanna just show my wallpaper to friends and I need to close all windows just for that. It is a bit of pain. Has anyone know a simple way how to hide all windows at once? And then unhide them all

**Comment by vaxerski** [comment]
`hyprctl dispatch workspace 1337`

**Comment by relief-melone** [comment]
I do not want to argue about the technical details or argue that it would be easy to implement. I can imagine if it wasn't supposed to be in that can be hard to implement in a adequate matter. But just from the convenience aspect I think minimizing is a totally valid feature that would make a lot of sense. I would definitely love it! Thank you for your effort nonetheless. Hyprland really is a great project!

**Comment by DreamMaoMao** [comment]
> I do not want to argue about the technical details or argue that it would be easy to implement. I can imagine if it wasn't supposed to be in that can be hard to implement in a adequate matter. But just from the convenience aspect I think minimizing is a totally valid feature that would make a lot of sense. I would definitely love it! Thank you for your effort nonetheless. Hyprland really is a great project!

https://github.com/DreamMaoMao/hych


I am working on a plugin for this feature but some of the plugins (clicking on the status bar chart to trigger minimization) do not work on the latest hyprland, only on older versions of hyprland, I am still looking for a fix.

**Comment by ad-on-is** [comment]
> Adopted the idea of special workspaces and love it. My example bindings:
> 
> ```
> bind = $mainMod, E, movetoworkspace, special:minimized
> bind = $mainMod, W, movetoworkspace, +0
> bind = $mainMod, W, togglespecialworkspace, minimized
> ```
> 
> So that I push `$mainMod, W`, choose the window to restore and push `$mainMod, W` again. Voila! thanks!

Wow, amazing.. Thx so much!

This perfectly covers my use-case. I can even bring them back, one by one.

**Comment by DreamMaoMao** [comment]
> > Adopted the idea of special workspaces and love it. My example bindings:
> > ```
> > bind = $mainMod, E, movetoworkspace, special:minimized
> > bind = $mainMod, W, movetoworkspace, +0
> > bind = $mainMod, W, togglespecialworkspace, minimized
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So that I push `$mainMod, W`, choose the window to restore and push `$mainMod, W` again. Voila! thanks!
> 
> Wow, amazing.. Thx so much!
> 
> This perfectly covers my use-case. I can even bring them back, one by one.

This configuration gave me a lot of inspiration, so I have more bold ideas to improve. Like the following:
such as bind to `alt + w`:

- 1.`alt + w` will enter special workspace when you not in special workspace(please hold alt,don't make it release)

- 2.`alt + w` will switch window focus circularly when you in special workspace. (please hold alt,don't make it release)

- 3.when you release `alt` , it will auto exit special workspace and restore the select window.


https://github.com/DreamMaoMao/hych/assets/30348075/c42c38db-8d21-4ca9-886c-5e21a4c14864

**Comment by SykikXO** [comment]
**UPDATE V0.55 LUA CONFIG BELOW IN THIS THREAD**

> i pretty much solved this issue albeit in a hacky way.. 
> version i'm using is 0.37.1
> edit. still works on 0.39.1
> modified @ildar 's code..
> 
> `bind = $mainMod, N, movetoworkspacesilent, special:minimized`
> `bind = $mainMod Control, N, togglespecialworkspace, minimized`
> `bind = $mainMod Control, N, movetoworkspace, +0`
> 
> make sure to not mess up the order of the bind commands.
> 
> [a video of how it works](https://files.catbox.moe/0ppdnw.mkv)
> [link-2](https://filebin.net/qh0ctzrb22xb1yan)
> 
> // EXPLANATION.
> // move active window to a special workspace `minimized` , and dont follow. 
> // move to the workspace `minimized`, and auto-focus on the last added window.
> // move the focused/last added window out of the `minimized` workspace and place it on normal numbered workspace.
> 
> // notice the 2nd and 3rd command have the same key combination, so both commands run, one after other, and swiftly pull the last added window, as the focus gets switched to it, out of the special workspace.
> 
> // NOTE - if there are no minimized window , you will just see an 'EMPTY SPECIAL WORKSPACE'. press the combination [in this case MODKEY+CTRL+N] to get out of it.
>_ig this is the first [hopefully valuable] contribution i have done on github_ :)









!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
hello people, after multiple updates to hyprland (gestures) found a new method to implement the 3 finger minimize from windows on hyprland. just add these two files to your hyprland config and ignore the stuff written above

`gesture = 3, down, dispatcher, movetoworkspacesilent, special:minimized`
`gesture = 3, up, dispatcher, exec, hyprctl --batch "dispatch togglespecialworkspace minimized; dispatch movetoworkspace +0"`

**Comment by maydayv7** [comment]
As an alternative to the previous comment, in order to choose which window to unmaximize, this is what I've done: (may be useful for others)

```
bind = ALT, Q, movetoworkspacesilent, special:minimized
bind = ALT SHIFT, Q, togglespecialworkspace, minimized
bind = ALT SHIFT, Q, submap, minimized
submap = minimized
bind = , F4, killactive
bind = , Return, movetoworkspace, +0
bind = , Return, submap, reset
bind = , mouse:272, movetoworkspace, +0
bind = , mouse:272, submap, reset
bind = , escape, togglespecialworkspace, minimized
bind = , escape, submap, reset
submap = reset
```

And added this to my Waybar config:
```

"modules-...": [ ... "custom/minimized" ... ]

"custom/minimized": {
  "format": "",
  "tooltip = false,
  "on-click": "
    hyprctl --batch "\
      dispatch submap reset;\
      dispatch workspace special:minimized;\
      dispatch submap minimized"
    exit"
  "
}
```

And thanks a lot @SykikXO and @ildar !

**Comment by atasoglou** [comment]
hey @maydayv7 can you explain the keybindings please? thanks!

**Comment by maydayv7** [comment]
Explanation:
- `Alt Q` sends active window to the _minimized_ workspace`
- `Alt SHIFT Q` shows that  workspace with all the _minimized_ windows that it contains, and activates a submap where the following can be done:
  - A specific window can be _unminimized_ (sent back to previous workspace) by clicking it (or) pressing `Enter`
  - `F4` kills focused window
  - `Escape` exits workspace without doing anything

**Comment by nazya** [comment]
here is my solution, the next is llm generated

### Quick Minimize to Hidden Workspace

```ini
bind = $mainMod, N, movetoworkspacesilent, +10
```

Pressing \`$mainMod + N\` moves the active window silently to workspace \`current_workspace_id + 10\`, effectively “minimizing” the window by hiding it on a dedicated hidden workspace.

### Preview and Restore Window

```ini
bind = $mainMod, M, exec, [stayfocused;bordersize 0;float;size 30% 100%;move 70% 0%] foot --font='CodeNewRoman Nerd Font Mono:size=16' -e bash -c 'active=$(hyprctl activeworkspace -j | jq ".id"); tmpfile="/dev/shm/fzf_prev_addr"; > "$tmpfile"; address=$(hyprctl -j clients | jq -r --argjson target_ws $((10 + active)) ".[] | select(.workspace.id == \$target_ws) | \"\(.address)\t\(.title)\t\(.workspace.id)\"" | fzf --wrap --delimiter=$"\t" --with-nth=2 --preview "addr={1}; ws={3}; if [ -f \"$tmpfile\" ]; then prev_addr=\$(cat $tmpfile); if [ -n \"\$prev_addr\" ] && [ \"\$prev_addr\" != \"\$addr\" ]; then hyprctl dispatch movetoworkspacesilent $((10 + active)),address:\$prev_addr > /dev/null; fi; fi; hyprctl dispatch setfloating address:\$addr > /dev/null; hyprctl dispatch movewindowpixel exact 0% 0%, address:\$addr > /dev/null; hyprctl dispatch resizewindowpixel exact 70% 100%, address:\$addr > /dev/null; hyprctl dispatch movetoworkspacesilent $active,address:\$addr > /dev/null; echo \$addr > $tmpfile; hyprctl -j clients | jq -r \".[] | select(.address == \\\"\$addr\\\") | \\\"address: \(.address)\ntitle: \(.title)\nclass: \(.class)\nworkspace: \(.workspace.id)\ntags: \(.tags)\\\"\"" --bind "ctrl-c:execute-silent( if [ -f $tmpfile ]; then addr=\$(cat $tmpfile); hyprctl dispatch movetoworkspacesilent $((10 + active)),address:\$addr; fi; )+abort" --preview-window=down:30%:wrap --layout=reverse | awk -F"\t" "{print \$1}"); hyprctl dispatch togglefloating address:$address; hyprctl dispatch focuswindow address:$address; rm -f \"$tmpfile\"'
```
Press `$mainMod + M` to:

- Open an interactive preview menu (using `fzf`) of hidden windows in workspace \`10 + current_workspace_id\`.
- Preview the selected window:
  - Temporarily sets the window to floating (on a current workspace) and adjusts size/position to align with fzf.
  - Shows details like window address, title, and tags in `fzf`’s preview pane.
- Restore the window back to your current workspace when selected.
- Press `Ctrl+C` during preview to send the window back to the hidden workspace.

This leverages `hyprctl`, `fzf`, and the `foot` terminal, providing a minimal yet powerful “minimize + restore” workflow within Hyprland.

**Comment by maydayv7** [comment]
Is there any reason why the IPC event for minimize was removed? If possible, can it be added back

**Comment by vaxerski** [comment]
I haven't even realized it was removed tbh. I should bring it back for wlr foreign

**Comment by SykikXO** [comment]
just as a final thing 

> hello people, after multiple updates to hyprland (gestures) found a new method to implement the **3 finger minimize** from windows on hyprland. just add these two files to your hyprland config and ignore the stuff written above
> 
> `gesture = 3, down, dispatcher, movetoworkspacesilent, special:minimized`
> `gesture = 3, up, dispatcher, exec, hyprctl --batch "dispatch togglespecialworkspace minimized; dispatch movetoworkspace +0"`
> 

i know of a annoying bug of doing thing this way, if you accidently 3finger swipe up, it opens a special workspace that "dims" screen,
so here's a better version


`gesture = 3, down, dispatcher, movetoworkspacesilent, special:minimized`

^ looks for 3 finger down gesture, if found puts current selected window to a special workspace called minimized

`gesture = 3, up, dispatcher, exec, hyprctl workspaces -j | jq -e '.[] | select(.name=="special:minimized")' >/dev/null && hyprctl --batch "dispatch togglespecialworkspace minimized; dispatch movetoworkspace +0"`

^ looks for 3 finger up gesture, if found, looks for a special workspace called minimized (**if it doesnt have any windows in it, it wont exist**) and retrieves the last pushed window to current workspace (stack??) 





 **UPDATE v0.55 LUA CONFIG**

this thingy for minimize with 3 finger down,

`
hl.gesture({
	fingers = 3,
	direction = "down",
	action = function()
		hl.dispatch(hl.dsp.window.move({ workspace = "special:minimized", follow = false }))
	end,
})`


this thingy for un-minimize with 3 finger up.

`
hl.gesture({
	fingers = 3,
	direction = "up",
	action = function()
		hl.dispatch(
			hl.dsp.exec_cmd(
				[[hyprctl workspaces -j | jq -e '.[] | select(.name=="special:minimized")' >/dev/null && hyprctl dispatch 'hl.dsp.workspace.toggle_special("minimized")' && hyprctl dispatch 'hl.dsp.window.move({ workspace = "+0" })']]
			)
		)
	end,
})`



or you can just use the "action = function() asdfasdfjasldfhjashdflk" thingy with a keybind so you can minimize and unminimize with a keybind instead of gesture like below

for minimize 

`
hl.bind(mainMod .. "+ Z", hl.dsp.window.move({ workspace = "special:minimized", follow = false }))`

for maximize 

hl.bind(mainMod .. " + SHIFT + Z",function()
  local ws = hl.get_workspace("special:minimized")
  if ws and ws.windows > 0 then
    hl.dispatch(hl.dsp.workspace.toggle_special("minimized"))
    hl.dispatch(hl.dsp.window.move({ workspace = "+0" }))
  end
end)

//functionality exactly same as the older implementation above
