### ISSUE TITLE
Touchscreen input does not reset swayidle idle timer

### ISSUE THREAD

**Issue by Smona** [hyprwm/Hyprland#996]
I'm using swayidle with Hyprland 0.17, with the home manager & NixOS modules. For the most part it works correctly, but when I'm using my laptop (XPS 13 2-in-1) in tablet mode the idle timer will invariably trigger no matter how much I'm touching the screen. This is strange because I can see the mouse pointer is moving along with my finger.

I originally reported this to swayidle, but they let me know [it should be handled by the compositor](https://github.com/swaywm/swayidle/issues/135).

### Steps to reproduce
1. Install swayidle
2. Configure a short idle timer
3. Once the timer is active, interact only using touchscreen input
4. The idle timer should trigger incorrectly.

**Comment by vaxerski** [comment]
fixed in dd11434e901ec616a5acc1008bb1ce4c1ef33a65

**Comment by Smona** [comment]
That must be the quickest bug resolution I've ever seen!! Thank you, love this project :slightly_smiling_face:

**Comment by vaxerski** [comment]
I have never seen a woman

**Comment by Elu43** [comment]
Hello,

@Smona was the problem solved for you ? I have the problem with swayidle as well, especially with my stylus. It never stops the timer when I use it, but the mouse is moving.

Even weirder when using the touchscreen with my finger : it doesn't stops the timer as well, but when I use "swayidle -d" in a terminal to look if my touch is detected, then it starts working, my touch is detected. Then I Ctrl + C to stop the command, and it keeps working, the timer is stopped when I touch the screen until I reboot. Stylus never stops the timer though. 

Here is my `hyprctl devices` :

mice:
	Mouse at 55a5e4055910:
		microsoft-surface-type-cover-mouse
			default speed: 0.00000
	Mouse at 55a5e3f08320:
		microsoft-surface-type-cover-consumer-control-1
			default speed: 0.00000
	Mouse at 55a5e36d5b10:
		microsoft-surface-type-cover-touchpad
			default speed: 0.00000


Keyboards:
	Keyboard at 55a5e4080010:
		video-bus
			rules: r "", m "", l "fr", v "", o ""
			active keymap: French
			main: no
	Keyboard at 55a5e40616a0:
		microsoft-surface-type-cover-keyboard
			rules: r "", m "", l "fr", v "", o ""
			active keymap: French
			main: no
	Keyboard at 55a5e4057140:
		microsoft-surface-type-cover-consumer-control
			rules: r "", m "", l "fr", v "", o ""
			active keymap: French
			main: no
	Keyboard at 55a5e404e5b0:
		gpio-keys
			rules: r "", m "", l "fr", v "", o ""
			active keymap: French
			main: no
	Keyboard at 55a5e4328e90:
		gpio-keys-1
			rules: r "", m "", l "fr", v "", o ""
			active keymap: French
			main: yes


Tablets:
	Tablet at 55a5e4215040:
		ipts-stylus


Touch:
	Touch Device at 55a5e40ece60:
		ipts-045e:001f-touchscreen
	Touch Device at 55a5e40df6e0:
		ipts-touch


Switches:
	Switch Device at 55a5e3df38f0:
		Lid Switch
	Switch Device at 55a5e3d4bb60:
		Microsoft Surface Type Cover Tablet Mode Switch

Best regards.

**Comment by Smona** [comment]
The fix did work for me, although I didn't test it with my stylus, only my fingers. I know those are different input types (tablet vs touchdevice).

**Comment by Elu43** [comment]
> The fix did work for me, although I didn't test it with my stylus, only my fingers. I know those are different input types (tablet vs touchdevice).

Do you have a stylus to test it by any chance, so I could understand if it comes from my side ? Sorry to bother you.

Best regards

**Comment by Smona** [comment]
I can reproduce your issue, swayidle hooks will still trigger even if i am inputting with my stylus more or less continuously. (XPS 7390 + wacom stylus)

You may want to file a new issue like this one, but for touchdevices (pens) rather than tablets (fingers).
