### ISSUE TITLE
Change mouse cursor to grabbing one when moving a window

### ISSUE THREAD

**Issue by EysseW** [hyprwm/Hyprland#999]
Excuse me if this is already possible with bash scripting, but I'm pretty sure it is not.
So my idea is to make the cursor a grabbing one when you are moving a window around by mouse with the `bindm=ALT,mouse:272,movewindow` thing. It's a very small thing, but it makes the session feel a lot more premium IMO.

**Comment by vaxerski** [comment]
done in d5eafe192649b290fd587b41f772887058f7418b
